### ISSUE TITLE
[regression] can't dup NilClass in latest release (2.53.0)

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#10028]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After upgrading to the latest fastlane, got the error "can't dup NilClass". Seems like changes in #9952 regressed the things for Xcode < 9. Really need a fix ASAP.

##### Complete output when running fastlane, including the stack trace and command used

```ruby
[17:13:07]: -----------------
[17:13:07]: --- Step: gym ---
[17:13:07]: -----------------
[17:13:07]: Sending crash report...
[17:13:07]: The stacktrace is sanitized so no personal information is sent.
[17:13:07]: To see what we are sending, look here: /Users/travis/.fastlane/latest_crash.json
[17:13:07]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[17:13:07]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
[17:13:10]: ▸ [17:13:09]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
+------------------------------------+---------------------------------------------------------+
|                                         Lane Context                                         |
+------------------------------------+---------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                     |
| PLATFORM_NAME                      | ios                                                     |
| LANE_NAME                          | ios auto                                                |
| PRODUCE_APPLE_ID                   |                                                         |
| SIGH_PROFILE_TYPE                  | app-store                                               |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.project.id"=>"match AppStore com.project.id"} |
| VERSION_NUMBER                     | 1.0.1                                              |
| BUILD_NUMBER                       | 1.0.1                                               |
+------------------------------------+---------------------------------------------------------+
[17:13:10]: can't dup NilClass
+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | git_branch                                                    | 0           |
| 3    | awk -F '=' '/PRODUCT_BUNDLE_IDENTIFIER = com.project/ {print $2 | 0           |
| 4    | git rev-list HEAD --count                                     | 0           |
| 5    | last_git_commit                                               | 0           |
| 6    | is_ci                                                         | 0           |
| 7    | is_ci                                                         | 0           |
| 8    | create_keychain                                               | 0           |
| 9   | update_info_plist                                             | 0           |
| 10   | Switch to ios deploy lane                                     | 0           |
| 11   | find "../Pods/Target Support Files" -name Info.plist -exec /u | 0           |
| 12   | produce                                                       | 2           |
| 13   | match                                                         | 283         |
| 14   | Switch to ios build lane                                      | 0           |
| 15   | increment_version_number                                      | 7           |
| 16   | increment_build_number                                        | 1           |
| 17   | match                                                         | 231         |
| 18   | is_ci                                                         | 0           |
| 19   | security set-key-partition-list -S apple-tool:,apple:,codesig | 0           |
| 💥   | gym                                                           | 0           |
| 21   | is_ci                                                         | 0           |
| 22   | fastlane env                                                  | 2           |
+------+---------------------------------------------------------------+-------------+
[17:13:11]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
➡️  can't dup NilClass error
    https://github.com/fastlane/fastlane/issues/3070 [closed] 3 💬
    22 Sep 2016
➡️  Added environments with dotenv
    https://github.com/fastlane/fastlane/pull/28 [closed] 31 💬
    04 Feb 2017
🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/bin/fastlane)
TypeError: [!] can't dup NilClass
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/actions/gym.rb:26:in `dup'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/actions/gym.rb:26:in `run'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:143:in `block (2 levels) in parsing_binding'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:217:in `block (2 levels) in parsing_binding'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:244:in `block (2 levels) in parsing_binding'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.0/bin/fastlane:20:in `<top (required)>'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'
```

### Environment

[17:13:09]: ▸ [17:13:09]: Generating fastlane environment output, this might take a few seconds...
[17:13:09]: ▸ <details><summary>✅ fastlane environment ✅</summary>
[17:13:09]: ▸ ### Stack
[17:13:09]: ▸ | Key                         | Value                                                      |
[17:13:09]: ▸ | --------------------------- | ---------------------------------------------------------- |
[17:13:09]: ▸ | OS                          | 10.12.1                                                    |
[17:13:09]: ▸ | Ruby                        | 2.3.1                                                      |
[17:13:09]: ▸ | Bundler?                    | true                                                       |
[17:13:09]: ▸ | Git                         | git version 2.11.0                                         |
[17:13:09]: ▸ | Installation Source         | ~/build/company/iOS/vendor/bundle/ruby/2.3.0/bin/fastlane |
[17:13:09]: ▸ | Host                        | Mac OS X 10.12.1 (16B2555)                                 |
[17:13:09]: ▸ | Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                               |
[17:13:09]: ▸ | OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                                |
[17:13:09]: ▸ | Is contained                | false                                                      |
[17:13:09]: ▸ | Is homebrew                 | false                                                      |
[17:13:09]: ▸ | Is installed via Fabric.app | false                                                      |
[17:13:09]: ▸ | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
[17:13:09]: ▸ | Xcode Version               | 8.2                                                        |
[17:13:09]: ▸ ### System Locale
[17:13:09]: ▸ | Variable | Value       |   |
[17:13:09]: ▸ | -------- | ----------- | - |
[17:13:09]: ▸ | LANG     | en_US.UTF-8 | ✅ |
[17:13:09]: ▸ | LC_ALL   | en_US.UTF-8 | ✅ |
[17:13:09]: ▸ | LANGUAGE |             |   |
[17:13:10]: ▸ ### fastlane gems
[17:13:10]: ▸ | Gem      | Version | Update-Status |
[17:13:10]: ▸ | -------- | ------- | ------------- |
[17:13:10]: ▸ | fastlane | 2.53.0  | ✅ Up-To-Date  |
[17:13:10]: ▸ ### Loaded fastlane plugins:
[17:13:10]: ▸ **No plugins Loaded**
[17:13:10]: ▸ <details><summary><b>Loaded gems</b></summary>
[17:13:10]: ▸ | Gem                       | Version      |
[17:13:10]: ▸ | ------------------------- | ------------ |
[17:13:10]: ▸ | io-console                | 0.4.5        |
[17:13:10]: ▸ | CFPropertyList            | 2.3.5        |
[17:13:10]: ▸ | i18n                      | 0.8.6        |
[17:13:10]: ▸ | minitest                  | 5.10.3       |
[17:13:10]: ▸ | thread_safe               | 0.3.6        |
[17:13:10]: ▸ | tzinfo                    | 1.2.3        |
[17:13:10]: ▸ | activesupport             | 4.2.9        |
[17:13:10]: ▸ | public_suffix             | 2.0.5        |
[17:13:10]: ▸ | addressable               | 2.5.1        |
[17:13:10]: ▸ | babosa                    | 1.0.2        |
[17:13:10]: ▸ | bundler                   | 1.15.3       |
[17:13:10]: ▸ | claide                    | 1.0.2        |
[17:13:10]: ▸ | colored                   | 1.2          |
[17:13:10]: ▸ | colored2                  | 3.1.2        |
[17:13:10]: ▸ | highline                  | 1.7.8        |
[17:13:10]: ▸ | commander-fastlane        | 4.4.5        |
[17:13:10]: ▸ | declarative               | 0.0.9        |
[17:13:10]: ▸ | declarative-option        | 0.1.0        |
[17:13:10]: ▸ | unf_ext                   | 0.0.7.4      |
[17:13:10]: ▸ | unf                       | 0.1.4        |
[17:13:10]: ▸ | domain_name               | 0.5.20170404 |
[17:13:10]: ▸ | dotenv                    | 2.2.1        |
[17:13:10]: ▸ | excon                     | 0.58.0       |
[17:13:10]: ▸ | multipart-post            | 2.0.0        |
[17:13:10]: ▸ | faraday                   | 0.12.2       |
[17:13:10]: ▸ | http-cookie               | 1.0.3        |
[17:13:10]: ▸ | faraday-cookie_jar        | 0.0.6        |
[17:13:10]: ▸ | faraday_middleware        | 0.12.2       |
[17:13:10]: ▸ | fastimage                 | 2.1.0        |
[17:13:10]: ▸ | gh_inspector              | 1.0.3        |
[17:13:10]: ▸ | jwt                       | 1.5.6        |
[17:13:10]: ▸ | little-plugger            | 1.1.4        |
[17:13:10]: ▸ | multi_json                | 1.12.1       |
[17:13:10]: ▸ | logging                   | 2.2.2        |
[17:13:10]: ▸ | memoist                   | 0.16.0       |
[17:13:10]: ▸ | os                        | 0.9.6        |
[17:13:10]: ▸ | signet                    | 0.7.3        |
[17:13:10]: ▸ | googleauth                | 0.5.3        |
[17:13:10]: ▸ | httpclient                | 2.8.3        |
[17:13:10]: ▸ | mime-types-data           | 3.2016.0521  |
[17:13:10]: ▸ | mime-types                | 3.1          |
[17:13:10]: ▸ | uber                      | 0.1.0        |
[17:13:10]: ▸ | representable             | 3.0.4        |
[17:13:10]: ▸ | retriable                 | 3.1.1        |
[17:13:10]: ▸ | google-api-client         | 0.12.0       |
[17:13:10]: ▸ | json                      | 2.1.0        |
[17:13:10]: ▸ | mini_magick               | 4.5.1        |
[17:13:10]: ▸ | multi_xml                 | 0.6.0        |
[17:13:10]: ▸ | plist                     | 3.3.0        |
[17:13:10]: ▸ | rubyzip                   | 1.2.1        |
[17:13:10]: ▸ | security                  | 0.1.3        |
[17:13:10]: ▸ | slack-notifier            | 1.5.1        |
[17:13:10]: ▸ | terminal-notifier         | 1.8.0        |
[17:13:10]: ▸ | unicode-display_width     | 1.3.0        |
[17:13:10]: ▸ | terminal-table            | 1.8.0        |
[17:13:10]: ▸ | tty-screen                | 0.5.0        |
[17:13:10]: ▸ | word_wrap                 | 1.0.0        |
[17:13:10]: ▸ | nanaimo                   | 0.2.3        |
[17:13:10]: ▸ | xcodeproj                 | 1.5.1        |
[17:13:10]: ▸ | rouge                     | 2.0.7        |
[17:13:10]: ▸ | xcpretty                  | 0.2.8        |
[17:13:10]: ▸ | xcpretty-travis-formatter | 0.0.4        |
[17:13:10]: ▸ | ffi                       | 1.9.18       |
[17:13:10]: ▸ | mustache                  | 0.99.8       |
[17:13:10]: ▸ | mini_portile2             | 2.2.0        |
[17:13:10]: ▸ | nokogiri                  | 1.8.0        |
[17:13:10]: ▸ | redcarpet                 | 3.4.0        |
[17:13:10]: ▸ | rb-fsevent                | 0.10.2       |
[17:13:10]: ▸ | rb-inotify                | 0.9.10       |
[17:13:10]: ▸ | sass-listen               | 4.0.0        |
[17:13:10]: ▸ | sass                      | 3.5.1        |
[17:13:10]: ▸ | jazzy                     | 0.0.14       |
[17:13:10]: ▸ </details>
[17:13:10]: ▸ *generated on:* **2017-08-10**
[17:13:10]: ▸ </details>

**Comment by sebastian312** [comment]
I have exactly the same error with version 2.53.0

**Comment by spandana-batchu** [comment]
I have the same issue too. can't dup NilClass
Im using version 2.53.0

**Comment by glancashire** [comment]
Same here with version 2.53.0. Unchanged fastfile, can't dup nilclass in gym.rb line 26.

**Comment by gigi-mohemian** [comment]
Same issue with version `2.53.0`

**Comment by senart** [comment]
I can confirm the same with `2.53.0`. I suppose a possible solution would be to rollback to `2.52.0` by removing the new version and then changing the Gemfile to `gem "fastlane", '2.52.0'`, but due to some unrelated provisioning profile issues I can't confirm that this will be a valid workaround.

**Comment by richard-lifeco** [comment]
same issue with version `2.53.0`

**Comment by Sega-Zero** [comment]
Reverting to 2.52.0 solved the issue, using now as a temporary solution. @KrauseFx we need a fix :)

**Comment by jQrgen** [comment]
@Sega-Zero How did you revert? I have the same issue.

Thanks.

**Comment by Sega-Zero** [comment]
I set this in my Gemfile
```ruby
gem 'fastlane', '< 2.53.0'
```

**Comment by KrauseFx** [comment]
Argh, sorry it took so long, was off my Mac. Here's a fix: https://github.com/fastlane/fastlane/pull/10031 and new release should be out in about 15 minutes 👍  Really sorry for introducing this error

**Comment by KrauseFx** [comment]
This must be specific to a Ruby version btw, when I run `nil.dup` on my local machine, it works just as expected...

**Comment by Sega-Zero** [comment]
My travis instance runs 2.3.1 ruby, should it be upgraded to a newer version?

**Comment by KrauseFx** [comment]
Nah, it's fine, you can stay with 2.3.1, we want to support 2.0, but just didn't test this particular change on older versions of Ruby. Expect the release to be live soon  🚀
