### ISSUE TITLE
oclint - How can I define `FL_OCLINT_SELECT_REGEX` value in a `.env` file

### ISSUE THREAD

**Issue by gtatgh** [fastlane/fastlane#10069]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

How can I define `FL_OCLINT_SELECT_REGEX` value in a `.env` file? If try to use `FL_OCLINT_SELECT_REGEX=/src/` then I get `type mismatch: String given`.

Same error if I try to use:
```
FL_OCLINT_SELECT_REGEX=/src/
FL_OCLINT_SELECT_REGEX=`/src/`
FL_OCLINT_SELECT_REGEX=\/src\/
FL_OCLINT_SELECT_REGEX=\\/src\\/
```

##### Complete output when running fastlane, including the stack trace and command used

```
10:25 user:MyProject$ fastlane ios run_analyzer --verbose
[10:25:16]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-08-17 10:25:19.07]: Checking if there are any plugins that should be loaded...
INFO [2017-08-17 10:25:19.19]: gem 'spaceship' is already installed
INFO [2017-08-17 10:25:19.19]: -------------------------------------------------
INFO [2017-08-17 10:25:19.19]: --- Step: Verifying required fastlane version ---
INFO [2017-08-17 10:25:19.20]: -------------------------------------------------
INFO [2017-08-17 10:25:19.20]: Your fastlane version 2.53.1 matches the minimum requirement of 2.50.0  ✅
INFO [2017-08-17 10:25:19.20]: ------------------------------
INFO [2017-08-17 10:25:19.20]: --- Step: default_platform ---
INFO [2017-08-17 10:25:19.20]: ------------------------------
INFO [2017-08-17 10:25:19.20]: Driving the lane 'ios run_analyzer' 🚀
INFO [2017-08-17 10:25:19.20]: Lane run_analyzer started.
INFO [2017-08-17 10:25:19.20]: --------------------
INFO [2017-08-17 10:25:19.20]: --- Step: oclint ---
INFO [2017-08-17 10:25:19.20]: --------------------
DEBUG [2017-08-17 10:25:19.21]: Taking value for 'compile_commands' from environment variable 'FL_OCLINT_COMPILE_COMMANDS'
DEBUG [2017-08-17 10:25:19.21]: Taking value for 'compile_commands' from environment variable 'FL_OCLINT_COMPILE_COMMANDS'
DEBUG [2017-08-17 10:25:19.21]: Taking value for 'select_regex' from environment variable 'FL_OCLINT_SELECT_REGEX'
DEBUG [2017-08-17 10:25:19.21]: Taking value for 'select_regex' from environment variable 'FL_OCLINT_SELECT_REGEX'
INFO [2017-08-17 10:25:24.98]: Lane run_analyzer failed to complete.
WARN [2017-08-17 10:25:24.98]: Lane Context:
INFO [2017-08-17 10:25:24.98]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios run_analyzer"}
ERROR [2017-08-17 10:25:24.98]: type mismatch: String given
INFO [2017-08-17 10:25:24.98]: Successfully generated documentation at path '/Users/user/projects/ios/project/MyProject/fastlane/README.md'

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 💥   | oclint                       | 0           |
+------+------------------------------+-------------+

ERROR [2017-08-17 10:25:24.99]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: type mismatch: String given

URL: https://api.github.com/search/issues?q=type%20mismatch:%20String%20given+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/actions/oclint.rb:45:in `=~': [!] type mismatch: String given (TypeError)
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/actions/oclint.rb:45:in `block in run'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/actions/oclint.rb:42:in `select!'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/actions/oclint.rb:42:in `run'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:140:in `block (2 levels) in parsing_binding'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/user/.gem/gems/fastlane-2.53.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/user/.gem/gems/fastlane-2.53.1/bin/fastlane:20:in `<top (required)>'
	from /Users/user/.gem/bin/fastlane:23:in `load'
	from /Users/user/.gem/bin/fastlane:23:in `<main>'

```

**Comment by taquitos** [comment]
Hmmm, I would expect `FL_OCLINT_SELECT_REGEX=/src/` to work, so I think that means it's getting turned into a string somewhere.

**Comment by gtatgh** [comment]
I have tried your branch, but get another error
<details>

```
[09:35:27]: -------------------------------------------------
[09:35:27]: --- Step: Verifying required fastlane version ---
[09:35:27]: -------------------------------------------------
[09:35:27]: Your fastlane version 2.53.1 matches the minimum requirement of 2.50.0  ✅
[09:35:27]: ------------------------------
[09:35:27]: --- Step: default_platform ---
[09:35:27]: ------------------------------
[09:35:27]: Driving the lane 'ios run_analyzer' 🚀
[09:35:27]: Lane run_analyzer started.
[09:35:27]: --------------------
[09:35:27]: --- Step: oclint ---
[09:35:27]: --------------------
+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | ios              |
| PLATFORM_NAME    | ios              |
| LANE_NAME        | ios run_analyzer |
+------------------+------------------+

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 3    | oclint                       | 0           |
+------+------------------------------+-------------+

[09:35:34]: fastlane finished with errors
bundler: failed to load command: fastlane (/Users/user/.gem/bin/fastlane)
SecurityError: Insecure operation - eval
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/oclint.rb:102:in `eval'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/oclint.rb:102:in `block in ensure_regex_is_not_string!'
```

</details>

**Comment by taquitos** [comment]
Le-sigh. Ok, making one small change.

**Comment by taquitos** [comment]
@gtatgh, I think this will work now 🤞

**Comment by gtatgh** [comment]
Commit `a434818da28482d613c4f7d7841f775484569401`, right? Unfortunately the same error. 
I have tried
```
FL_OCLINT_SELECT_REGEX=/MyProject/
FL_OCLINT_SELECT_REGEX='/MyProject/'
FL_OCLINT_SELECT_REGEX="/MyProject/"
FL_OCLINT_SELECT_REGEX='MyProject' <- Unknown method 'MyProject'
FL_OCLINT_SELECT_REGEX="MyProject" <- Unknown method 'MyProject'
```

<details>

```
[09:14:13]: -------------------------------------------------
[09:14:13]: --- Step: Verifying required fastlane version ---
[09:14:13]: -------------------------------------------------
[09:14:13]: Your fastlane version 2.53.1 matches the minimum requirement of 2.50.0  ✅
[09:14:13]: ------------------------------
[09:14:13]: --- Step: default_platform ---
[09:14:13]: ------------------------------
[09:14:13]: Driving the lane 'ios run_analyzer' 🚀
[09:14:13]: Lane run_analyzer started.
[09:14:13]: --------------------
[09:14:13]: --- Step: oclint ---
[09:14:13]: --------------------
[09:14:20]: Lane run_analyzer failed to complete.
+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | ios              |
| PLATFORM_NAME    | ios              |
| LANE_NAME        | ios run_analyzer |
+------------------+------------------+
[09:14:20]: type mismatch: String given

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 💥   | oclint                       | 0           |
+------+------------------------------+-------------+

[09:14:20]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  oclint - How can I define `FL_OCLINT_SELECT_REGEX` value in a `.env` file
    https://github.com/fastlane/fastlane/issues/10069 [open] 5 💬
    9 hours ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/user/.gem/bin/fastlane)
TypeError: [!] type mismatch: String given
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/oclint.rb:48:in `=~'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/oclint.rb:48:in `!~'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/oclint.rb:48:in `block in run'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/oclint.rb:44:in `select!'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/oclint.rb:44:in `run'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:140:in `block (2 levels) in parsing_binding'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/user/3party/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/user/3party/fastlane/bin/fastlane:20:in `<top (required)>'
  /Users/user/.gem/bin/fastlane:23:in `load'
  /Users/user/.gem/bin/fastlane:23:in `<top (required)>'
```

</details>
