### ISSUE TITLE
[pilot] Faraday::ParsingError: [!] 765: unexpected token at '<!DOCTYPE html><html lang="en">

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#10097]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Just caught build failure when building for Testflight. The build went fine, ipa uploaded succesfully, but then pilot failed while waiting for build to appear in itunes connect. When I opened itunesconnect web interface, I see the processing build fine.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```bash
[20:35:11]: Successfully exported and compressed dSYM file
[20:35:11]: Successfully exported and signed the ipa file:
[20:35:11]: /Users/travis/build/company/iOS/Project/Project.ipa
[20:35:13]: -------------------------
[20:35:13]: --- Step: crashlytics ---
[20:35:13]: -------------------------
[20:35:14]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[20:44:08]: iTunes Transporter successfully finished its job
[20:44:08]: --------------------------------------------------------------------
[20:44:08]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[20:44:08]: --------------------------------------------------------------------
[20:44:08]: Successfully uploaded the new binary to iTunes Connect
[20:44:08]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[20:44:23]: Waiting for iTunes Connect to finish processing the new build (1.11.1111 - 1.11.1111)
[20:44:54]: Waiting for iTunes Connect to finish processing the new build (1.11.1111 - 1.11.1111)
[20:45:24]: Waiting for iTunes Connect to finish processing the new build (1.11.1111 - 1.11.1111)
[20:45:55]: Waiting for iTunes Connect to finish processing the new build (1.11.1111 - 1.11.1111)
[20:46:25]: Waiting for iTunes Connect to finish processing the new build (1.11.1111 - 1.11.1111)
[20:46:56]: Waiting for iTunes Connect to finish processing the new build (1.11.1111 - 1.11.1111)
[20:47:27]: Waiting for iTunes Connect to finish processing the new build (1.11.1111 - 1.11.1111)
[20:47:57]: Waiting for iTunes Connect to finish processing the new build (1.11.1111 - 1.11.1111)
[20:48:28]: Waiting for iTunes Connect to finish processing the new build (1.11.1111 - 1.11.1111)
[20:48:59]: Build doesn't show up in the build list anymore, waiting for it to appear again
[20:49:30]: Build doesn't show up in the build list anymore, waiting for it to appear again
[20:50:01]: Build doesn't show up in the build list anymore, waiting for it to appear again
[20:50:31]: Build doesn't show up in the build list anymore, waiting for it to appear again
[20:51:02]: Build doesn't show up in the build list anymore, waiting for it to appear again
[20:51:33]: Build doesn't show up in the build list anymore, waiting for it to appear again
[20:52:04]: Build doesn't show up in the build list anymore, waiting for it to appear again
[20:52:35]: Build doesn't show up in the build list anymore, waiting for it to appear again
[20:53:06]: Sending crash report...
[20:53:06]: The stacktrace is sanitized so no personal information is sent.
[20:53:06]: To see what we are sending, look here: /Users/travis/.fastlane/latest_crash.json
[20:53:06]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[20:53:06]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
[20:53:14]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
+------------------------------------+-------------------------------------------------------------------------------------------------+
|                                                             Lane Context                                                             |
+------------------------------------+-------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                             |
| PLATFORM_NAME                      | ios                                                                                             |
| LANE_NAME                          | ios auto                                                                                        |
| PRODUCE_APPLE_ID                   |                                                                                                 |
| SIGH_PROFILE_TYPE                  | app-store                                                                                       |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.bundle.id"=>"match AppStore com.bundle.id"}                                         |
| VERSION_NUMBER                     | 1.11.1111                                                                                       |
| BUILD_NUMBER                       | 1.11.1111                                                                                       |
| IPA_OUTPUT_PATH                    | /Users/travis/build/company/iOS/Project/Project.ipa                                            |
| DSYM_OUTPUT_PATH                   | /Users/travis/build/company/iOS/Project/Project.app.dSYM.zip                                   |
| XCODEBUILD_ARCHIVE                 | /Users/travis/Library/Developer/Xcode/Archives/2017-08-21/Project 2017-08-21 19.55.14.xcarchive |
+------------------------------------+-------------------------------------------------------------------------------------------------+
[20:53:15]: 765: unexpected token at '<!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>
<body><div id="wrapper" class="j42">
<h2>Internal Server Error</h2></div>
<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="http://www.apple.com/legal/internet-services/itunes/us/terms.html">Terms of Service</a></li><li><a href="http://www.apple.com/legal/privacy">Privacy Policy</a></li><li><a href="http://www.apple.com/support/">Contact Us</a></li></ul>
</div>
<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>
</body>
</html>'
+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
<skipped>
| 25   | gym                                                           | 2403        |
| 26   | crashlytics                                                   | 203         |
| 💥   | pilot                                                         | 869         |
| 28   | is_ci                                                         | 0           |
| 29   | fastlane env                                                  | 8           |
+------+---------------------------------------------------------------+-------------+
[20:53:15]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
bundler: failed to load command: fastlane (/Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/bin/fastlane)
Faraday::ParsingError: [!] 765: unexpected token at '<!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>
<body><div id="wrapper" class="j42">
<h2>Internal Server Error</h2></div>
<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="http://www.apple.com/legal/internet-services/itunes/us/terms.html">Terms of Service</a></li><li><a href="http://www.apple.com/legal/privacy">Privacy Policy</a></li><li><a href="http://www.apple.com/support/">Contact Us</a></li></ul>
</div>
<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>
</body>
</html>'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:51:in `parse'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:40:in `process_response'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:33:in `block in call'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/client.rb:680:in `block in send_request'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/client.rb:520:in `with_retry'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/client.rb:679:in `send_request'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/client.rb:568:in `request'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/test_flight/client.rb:33:in `block in get_builds_for_train'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/client.rb:520:in `with_retry'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/test_flight/client.rb:32:in `get_builds_for_train'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/test_flight/build.rb:89:in `builds_for_train'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/build_watcher.rb:33:in `matching_build'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/build_watcher.rb:11:in `block in wait_for_build_processing_to_be_complete'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/build_watcher.rb:10:in `loop'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/build_watcher.rb:10:in `wait_for_build_processing_to_be_complete'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/pilot/lib/pilot/build_manager.rb:38:in `upload'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/actions/pilot.rb:16:in `run'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:218:in `block (2 levels) in parsing_binding'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:244:in `block (2 levels) in parsing_binding'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/bin/fastlane:20:in `<top (required)>'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  /Users/travis/build/company/iOS/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[20:53:06]: $ fastlane env
[20:53:13]: ▸ [20:53:13]: Generating fastlane environment output, this might take a few seconds...
[20:53:14]: ▸ <details><summary>✅ fastlane environment ✅</summary>
[20:53:14]: ▸ ### Stack
[20:53:14]: ▸ | Key                         | Value                                                      |
[20:53:14]: ▸ | --------------------------- | ---------------------------------------------------------- |
[20:53:14]: ▸ | OS                          | 10.12.1                                                    |
[20:53:14]: ▸ | Ruby                        | 2.3.1                                                      |
[20:53:14]: ▸ | Bundler?                    | true                                                       |
[20:53:14]: ▸ | Git                         | git version 2.11.0                                         |
[20:53:14]: ▸ | Installation Source         | ~/build/company/iOS/vendor/bundle/ruby/2.3.0/bin/fastlane |
[20:53:14]: ▸ | Host                        | Mac OS X 10.12.1 (16B2555)                                 |
[20:53:14]: ▸ | Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                               |
[20:53:14]: ▸ | OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                                |
[20:53:14]: ▸ | Is contained                | false                                                      |
[20:53:14]: ▸ | Is homebrew                 | false                                                      |
[20:53:14]: ▸ | Is installed via Fabric.app | false                                                      |
[20:53:14]: ▸ | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
[20:53:14]: ▸ | Xcode Version               | 8.2                                                        |
[20:53:14]: ▸ ### System Locale
[20:53:14]: ▸ | Variable | Value       |   |
[20:53:14]: ▸ | -------- | ----------- | - |
[20:53:14]: ▸ | LANG     | en_US.UTF-8 | ✅ |
[20:53:14]: ▸ | LC_ALL   | en_US.UTF-8 | ✅ |
[20:53:14]: ▸ | LANGUAGE |             |   |
[20:53:14]: ▸ ### fastlane gems
[20:53:14]: ▸ | Gem      | Version | Update-Status |
[20:53:14]: ▸ | -------- | ------- | ------------- |
[20:53:14]: ▸ | fastlane | 2.53.1  | ✅ Up-To-Date  |
[20:53:14]: ▸ ### Loaded fastlane plugins:
[20:53:14]: ▸ **No plugins Loaded**
[20:53:14]: ▸ <details><summary><b>Loaded gems</b></summary>
[20:53:14]: ▸ | Gem                       | Version      |
[20:53:14]: ▸ | ------------------------- | ------------ |
[20:53:14]: ▸ | io-console                | 0.4.5        |
[20:53:14]: ▸ | CFPropertyList            | 2.3.5        |
[20:53:14]: ▸ | i18n                      | 0.8.6        |
[20:53:14]: ▸ | minitest                  | 5.10.3       |
[20:53:14]: ▸ | thread_safe               | 0.3.6        |
[20:53:14]: ▸ | tzinfo                    | 1.2.3        |
[20:53:14]: ▸ | activesupport             | 4.2.9        |
[20:53:14]: ▸ | public_suffix             | 2.0.5        |
[20:53:14]: ▸ | addressable               | 2.5.1        |
[20:53:14]: ▸ | babosa                    | 1.0.2        |
[20:53:14]: ▸ | bundler                   | 1.15.4       |
[20:53:14]: ▸ | claide                    | 1.0.2        |
[20:53:14]: ▸ | colored                   | 1.2          |
[20:53:14]: ▸ | colored2                  | 3.1.2        |
[20:53:14]: ▸ | highline                  | 1.7.8        |
[20:53:14]: ▸ | commander-fastlane        | 4.4.5        |
[20:53:14]: ▸ | declarative               | 0.0.9        |
[20:53:14]: ▸ | declarative-option        | 0.1.0        |
[20:53:14]: ▸ | unf_ext                   | 0.0.7.4      |
[20:53:14]: ▸ | unf                       | 0.1.4        |
[20:53:14]: ▸ | domain_name               | 0.5.20170404 |
[20:53:14]: ▸ | dotenv                    | 2.2.1        |
[20:53:14]: ▸ | excon                     | 0.58.0       |
[20:53:14]: ▸ | multipart-post            | 2.0.0        |
[20:53:14]: ▸ | faraday                   | 0.13.1       |
[20:53:14]: ▸ | http-cookie               | 1.0.3        |
[20:53:14]: ▸ | faraday-cookie_jar        | 0.0.6        |
[20:53:14]: ▸ | faraday_middleware        | 0.12.2       |
[20:53:14]: ▸ | fastimage                 | 2.1.0        |
[20:53:14]: ▸ | gh_inspector              | 1.0.3        |m
[20:53:14]: ▸ | jwt                       | 1.5.6        |
[20:53:14]: ▸ | little-plugger            | 1.1.4        |
[20:53:14]: ▸ | multi_json                | 1.12.1       |
[20:53:14]: ▸ | logging                   | 2.2.2        |
[20:53:14]: ▸ | memoist                   | 0.16.0       |
[20:53:14]: ▸ | os                        | 0.9.6        |
[20:53:14]: ▸ | signet                    | 0.7.3        |
[20:53:14]: ▸ | googleauth                | 0.5.3        |
[20:53:14]: ▸ | httpclient                | 2.8.3        |
[20:53:14]: ▸ | mime-types-data           | 3.2016.0521  |
[20:53:14]: ▸ | mime-types                | 3.1          |
[20:53:14]: ▸ | uber                      | 0.1.0        |
[20:53:14]: ▸ | representable             | 3.0.4        |
[20:53:14]: ▸ | retriable                 | 3.1.1        |
[20:53:14]: ▸ | google-api-client         | 0.12.0       |
[20:53:14]: ▸ | json                      | 2.1.0        |
[20:53:14]: ▸ | mini_magick               | 4.5.1        |
[20:53:14]: ▸ | multi_xml                 | 0.6.0        |
[20:53:14]: ▸ | plist                     | 3.3.0        |
[20:53:14]: ▸ | rubyzip                   | 1.2.1        |
[20:53:14]: ▸ | security                  | 0.1.3        |
[20:53:14]: ▸ | slack-notifier            | 1.5.1        |
[20:53:14]: ▸ | terminal-notifier         | 1.8.0        |
[20:53:14]: ▸ | unicode-display_width     | 1.3.0        |
[20:53:14]: ▸ | terminal-table            | 1.8.0        |
[20:53:14]: ▸ | tty-screen                | 0.5.0        |
[20:53:14]: ▸ | word_wrap                 | 1.0.0        |
[20:53:14]: ▸ | nanaimo                   | 0.2.3        |
[20:53:14]: ▸ | xcodeproj                 | 1.5.1        |
[20:53:14]: ▸ | rouge                     | 2.0.7        |
[20:53:14]: ▸ | xcpretty                  | 0.2.8        |
[20:53:14]: ▸ | xcpretty-travis-formatter | 0.0.4        |
[20:53:14]: ▸ | ffi                       | 1.9.18       |
[20:53:14]: ▸ | mustache                  | 0.99.8       |
[20:53:14]: ▸ | mini_portile2             | 2.2.0        |
[20:53:14]: ▸ | nokogiri                  | 1.8.0        |
[20:53:14]: ▸ | redcarpet                 | 3.4.0        |
[20:53:14]: ▸ | rb-fsevent                | 0.10.2       |
[20:53:14]: ▸ | rb-inotify                | 0.9.10       |
[20:53:14]: ▸ | sass-listen               | 4.0.0        |
[20:53:14]: ▸ | sass                      | 3.5.1        |
[20:53:14]: ▸ | jazzy                     | 0.0.14       |
[20:53:15]: ▸ </details>
[20:53:15]: ▸ *generated on:* **2017-08-21**
[20:53:15]: ▸ </details>

**Comment by mpirri** [comment]
Thanks for writing in about this. Definitely looks like a problem on Apple's end ("Internal Server Error" in the HTML returned). Have you been able to try submitting again?

Fingers crossed that this resolves on its own!  🤞

**Comment by Sega-Zero** [comment]
Well, the build was successfully uploaded and turned on for TestFlight, it's just pilot waiting for processing failed and I had to upload symbols to Crashlytics by myself. Not a fatal error, but I can't call it a successful CI :)

That looks like a sporadic error, since I'm not catching it in a new builds for now.

**Comment by Sega-Zero** [comment]
But I definitely caught that before several times.

**Comment by mpirri** [comment]
We definitely need to improve our retries when this sort of thing happens - treat this sort of error the same as a "app hasn't appeared yet" and try again in 30 seconds. I wonder if _fastlane_ had polled again if the same error would have happened or if it would have been successful?  🤔

**Comment by Sega-Zero** [comment]
I think it should poll until itc returns ready status

**Comment by mpirri** [comment]
@Sega-Zero Thanks for the feedback - I will share with the team. Our current thought is that while waiting for builds to appear (like in your case) we should retry on an "Internal Server Error", but only up until (maybe?) 10 times, and then fail after that.  That way, _fastlane_ can be more resilient against transient iTC failures.

Thanks again!  🚀

**Comment by thibaudrobelain** [comment]
@mpirri It seems like the exception comes from the JSON lib that Faraday uses to parse the page? As far as I can see with that trace, the JSON lib fails to parse the page and therefore a Faraday::ParsingError exception is raised, but that specific exception is not in the [rescue statement](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L528-L531)  therefore never triggering the retry logic? I could be interpreting that wrong since my knowledge of ruby's limited though.

I'm interested in this being solved as it triggers CI failures that might have been prevented if the retry logic was executed!

**Comment by Sega-Zero** [comment]
Got this today again
```ruby
Faraday::ParsingError: [!] 765: unexpected token at '<!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>
<body><div id="wrapper" class="j42">
<h2>Internal Server Error</h2></div>
<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="http://www.apple.com/legal/internet-services/itunes/us/terms.html">Terms of Service</a></li><li><a href="http://www.apple.com/legal/privacy">Privacy Policy</a></li><li><a href="http://www.apple.com/support/">Contact Us</a></li></ul>
</div>
<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>
</body>
</html>'
```

**Comment by BennettSmith** [comment]
I am seeing the same error mentioned by Sega-Zero above.  It started happening late yesterday afternoon on all of our pilot uploads to TestFlight.

**Comment by Sega-Zero** [comment]
Haven't seen this for a month, so, I hope this issue is resolved.
