### ISSUE TITLE
oclint - undefined method `map'

### ISSUE THREAD

**Issue by gtatgh** [fastlane/fastlane#10119]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I getting following error for `FL_OCLINT_THRESHOLDS=["LONG_LINE=200","SHORT_VARIABLE_NAME=1"]`

```
ERROR [2017-08-23 09:08:03.89]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `map' for "[\"LONG_LINE=200\",\"SHORT_VARIABLE_NAME=1\"]":String
Did you mean?  tap

```

<details>

```
DEBUG [2017-08-23 09:07:56.85]: Checking if there are any plugins that should be loaded...
INFO [2017-08-23 09:07:56.95]: gem 'spaceship' is already installed
INFO [2017-08-23 09:07:56.95]: -------------------------------------------------
INFO [2017-08-23 09:07:56.95]: --- Step: Verifying required fastlane version ---
INFO [2017-08-23 09:07:56.95]: -------------------------------------------------
INFO [2017-08-23 09:07:56.95]: Your fastlane version 2.54.0 matches the minimum requirement of 2.50.0  ✅
INFO [2017-08-23 09:07:56.95]: ------------------------------
INFO [2017-08-23 09:07:56.95]: --- Step: default_platform ---
INFO [2017-08-23 09:07:56.95]: ------------------------------
INFO [2017-08-23 09:07:56.96]: Driving the lane 'ios run_analyzer' 🚀
INFO [2017-08-23 09:07:56.96]: Lane run_analyzer started.
INFO [2017-08-23 09:07:56.96]: --------------------
INFO [2017-08-23 09:07:56.96]: --- Step: oclint ---
INFO [2017-08-23 09:07:56.96]: --------------------
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'compile_commands' from environment variable 'FL_OCLINT_COMPILE_COMMANDS'
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'compile_commands' from environment variable 'FL_OCLINT_COMPILE_COMMANDS'
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'select_regex' from environment variable 'FL_OCLINT_SELECT_REGEX'
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'select_regex' from environment variable 'FL_OCLINT_SELECT_REGEX'
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'exclude_regex' from environment variable 'FL_OCLINT_EXCLUDE_REGEX'
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'report_type' from environment variable 'FL_OCLINT_REPORT_TYPE'
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'report_path' from environment variable 'FL_OCLINT_REPORT_PATH'
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'report_path' from environment variable 'FL_OCLINT_REPORT_PATH'
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'thresholds' from environment variable 'FL_OCLINT_THRESHOLDS'
DEBUG [2017-08-23 09:07:56.96]: Taking value for 'thresholds' from environment variable 'FL_OCLINT_THRESHOLDS'
INFO [2017-08-23 09:08:03.88]: Lane run_analyzer failed to complete.
WARN [2017-08-23 09:08:03.88]: Lane Context:
INFO [2017-08-23 09:08:03.88]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios run_analyzer"}
ERROR [2017-08-23 09:08:03.88]: undefined method `map' for "[\"LONG_LINE=200\",\"SHORT_VARIABLE_NAME=1\"]":String
Did you mean?  tap
INFO [2017-08-23 09:08:03.88]: Successfully generated documentation at path '/Users/user/projects/ios/gt-armory/MyProject/fastlane/README.md'

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 💥   | oclint                       | 0           |
+------+------------------------------+-------------+

ERROR [2017-08-23 09:08:03.89]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `map' for "[\"LONG_LINE=200\",\"SHORT_VARIABLE_NAME=1\"]":String
Did you mean?  tap

URL: https://api.github.com/search/issues?q=undefined%20method%20%60map'%20for%20%22[%5C%22LONG_LINE=200%5C%22,%5C%22SHORT_VARIABLE_NAME=1%5C%22]%22:String%0ADid%20you%20mean?%20%20tap+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/user/.gem/bin/fastlane)
NoMethodError: [!] undefined method `map' for "[\"LONG_LINE=200\",\"SHORT_VARIABLE_NAME=1\"]":String
Did you mean?  tap
Did you mean?  tap
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/oclint.rb:70:in `run'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:140:in `block (2 levels) in parsing_binding'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/user/3party/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/user/3party/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/user/3party/fastlane/bin/fastlane:20:in `<top (required)>'
  /Users/user/.gem/bin/fastlane:23:in `load'
  /Users/user/.gem/bin/fastlane:23:in `<top (required)>'
```

</details>

**Comment by mpirri** [comment]
@gtatgh Where are you setting the value `FL_OCLINT_THRESHOLDS=["LONG_LINE=200","SHORT_VARIABLE_NAME=1"]` - is it a shell environment variable, or set in a Ruby script? It sure looks like it is being parsed as a string, not an array, so you might need to use a different syntax, depending on where you are setting this.

**Comment by gtatgh** [comment]
Hi @mpirri, I set this variable in an `.env` file. I think this is an identical issue as  #10069 and #10117.

**Comment by ohayon** [comment]
Hey @gtatgh it looks like we assume that argument is going to be an array. Is there any way that you could pass it into your `oclint` action via the option rather than an environment variable? It might be difficult to convert the string into an array just because of all the different ways someone might express an array in an env variable string. 🐙

**Comment by gtatgh** [comment]
Hi @ohayon, I want to make an universally usable `Fastfile`, so to edit configuration only in `.env` file. To answer your question, yes this may be possible, but I think this is anyway a bug in `fastlane` or `oclint`.

**Comment by ohayon** [comment]
Yeah, doing something like that is definitely an option, I think the concern is just: what if the string looks like the one you originally had, which had brackets in it? That would end up having `[` with the first item in the array and `]` with the last item. I wonder if there is a way with the `Dotenv` gem that we can define an array in the `.env` file?

**Comment by gtatgh** [comment]
As an exsample you can define `SCAN_DEVICES="iPhone 7,iPhone 6"` as array of devices in `.env` file and this works.

**Comment by ohayon** [comment]
Yeah, that makes sense, I am just concerned that there are a couple of different ways that an array could be defined by our users in a string. This would cause some complexity with creating the array from a string by just calling `split(',')` because if someone puts spaces after commas in their array it will cause issues. Unless I could be missing something here? 🐒

**Comment by gtatgh** [comment]
> I am just concerned that there are a couple of different ways that an array could be defined by our users in a string

Exactly my opinion. There is no definition of standardised interfaces.

> because if someone puts spaces after commas in their array it will cause issues

I have to learn this by try and error too, but I think this is a better approach, as the exception error `undefined method `map'`. By the way someone can improve the description, which explain to not to use spaces after commas and maybe some examples.

**Comment by ohayon** [comment]
We could put something in the verify block to make sure that it is in the right format and print out a nice message if it's not. The only issue would be making sure that we are checking for all of the different permutations of arrays in strings?

**Comment by gtatgh** [comment]
The verification idea may not solve the string input but will surely help preventing errors. Any forecast on a fixing ?

**Comment by gtatgh** [comment]
@ohayon Any update in this?

**Comment by ohayon** [comment]
Hey @gtatgh, I'm not sure if that is the right direction as we are going to have to have a map of every different string-based array permutation and it seems like it could be a bit messy. Would you have any interest in giving this a shot and submitting a PR and we can talk about it more once we have something to look at? 🐙

**Comment by gtatgh** [comment]
Sorry for the late answer. I have a lot of work to do at the moment.
I would do not worry about different array permutations. We could parse in the format like  `SCAN_DEVICES="iPhone 7,iPhone 6"`. All other throws an exception, with an example of right format in description.

**Comment by gtatgh** [comment]
Sorry for the late answer. I have a lot of work to do at the moment.
I would do not worry about different array permutations. We could parse in the format like  `SCAN_DEVICES="iPhone 7,iPhone 6"`. All other throws an exception, with an example of right format in description.

**Comment by ohayon** [comment]
Thats a good point @gtatgh! Would you want to submit a PR to make this fix and make sure to add the documentation to the description about how we want this string to be formatted?

**Comment by gtatgh** [comment]
I can do that, but in some point in the future. As I sad, I have a lot of work to do at the moment.

**Comment by gtatgh** [comment]
Yes it's the same result.

<details>

```

[14:29:22]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:29:24]: -------------------------------------------------
[14:29:24]: --- Step: Verifying required fastlane version ---
[14:29:24]: -------------------------------------------------
[14:29:24]: Your fastlane version 2.64.0 matches the minimum requirement of 2.50.0  ✅
[14:29:24]: ------------------------------
[14:29:24]: --- Step: default_platform ---
[14:29:24]: ------------------------------
[14:29:24]: Driving the lane 'ios run_analyzer' 🚀
[14:29:24]: Lane run_analyzer started.
[14:29:24]: --------------------
[14:29:24]: --- Step: oclint ---
[14:29:24]: --------------------
[14:29:30]: Lane run_analyzer failed to complete.
+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | ios              |
| PLATFORM_NAME    | ios              |
| LANE_NAME        | ios run_analyzer |
+------------------+------------------+
[14:29:30]: undefined method `map' for "[\"LONG_LINE=200\",\"SHORT_VARIABLE_NAME=1\"]":String
Did you mean?  tap

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 💥   | oclint                       | 0           |
+------+------------------------------+-------------+

[14:29:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  oclint - undefined method `map'
    https://github.com/fastlane/fastlane/issues/10119 [open] 17 💬
    4 days ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/actions/oclint.rb:70:in `run': [!] undefined method `map' for "[\"LONG_LINE=200\",\"SHORT_VARIABLE_NAME=1\"]":String (NoMethodError)
Did you mean?  tap
Did you mean?  tap
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:140:in `block (2 levels) in parsing_binding'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/user/.gem/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/user/.gem/gems/fastlane-2.64.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/user/.gem/gems/fastlane-2.64.0/bin/fastlane:20:in `<top (required)>'
	from /Users/user/.gem/bin/fastlane:23:in `load'
	from /Users/user/.gem/bin/fastlane:23:in `<main>'

```

</details>

**Comment by gtatgh** [comment]
Fixed with https://github.com/fastlane/fastlane/pull/10839

**Comment by gtatgh** [comment]
Fixed with https://github.com/fastlane/fastlane/pull/10839
