### ISSUE TITLE
Supply not working with pro guard enabled

### ISSUE THREAD

**Issue by dabele91** [fastlane/fastlane#10144]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Supply seems to be broken if you're using proguard. It crashes in the upload_mapping functionionality.

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | update_fastlane     | 6           |
| 4    | git_pull            | 19          |
| 5    | Switch to android   | 0           |
|      | buildApk lane       |             |
| 6    | gradle              | 101         |
| 7    | Switch to android   | 0           |
|      | alpha lane          |             |
| 💥   | supply              | 19          |
+------+---------------------+-------------+

[10:29:45]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/supply/lib/supply/client.rb:228:in `block in upload_mapping': [!] undefined method `upload_deobfuscationfile' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007f84732da600> (NoMethodError)
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/supply/lib/supply/client.rb:367:in `call_google_api'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/supply/lib/supply/client.rb:227:in `upload_mapping'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/supply/lib/supply/uploader.rb:119:in `block in upload_binaries'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/supply/lib/supply/uploader.rb:117:in `each'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/supply/lib/supply/uploader.rb:117:in `upload_binaries'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/supply/lib/supply/uploader.rb:26:in `perform_upload'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/actions/supply.rb:21:in `run'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:98:in `block (2 levels) in parsing_binding'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:48:in `block (2 levels) in parsing_binding'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/dennis.abele/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.54.1/bin/fastlane:20:in `<top (required)>'
	from /Users/dennis.abele/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/dennis.abele/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.104.0"

default_platform :android

skip_docs

platform :android do
  def version_string(options)
    "#{options[:major]}.#{options[:minor]}.#{options[:patch]}"
  end
  def version_code(options)
    options[:major].to_i * 100000 + options[:minor].to_i * 10000 + options[:patch].to_i * 1000 + options[:bld].to_i
  end
  def version_changelog(options)
    options[:major].to_i * 100000 + options[:minor].to_i * 10000 + options[:patch].to_i
  end
  before_all do
    update_fastlane
    git_pull(only_tags: true)
  end

  desc "Builds apk for tab1 with the given buildtype"
  lane :tab1 do |options|
      buildApk({:major => options[:major], :minor => options[:minor], :patch => options[:patch], :bld => options[:bld], :buildType => options[:buildType], :product => 'Tab1'})
  end

  desc "Builds apk for minix with the given buildtype"
  lane :minix do |options|
      buildApk({:major => options[:major], :minor => options[:minor], :patch => options[:patch], :bld => options[:bld], :buildType => options[:buildType], :product => 'Minix'})
  end

  desc "Creates Release Branch and sets Git Tags and finishes release"
  lane :playStore do |options|
      buildApk({:major => options[:major], :minor => options[:minor], :patch => options[:patch], :bld => options[:bld], :buildType => options[:buildType], :product => 'PlayStore'})
      alpha(:product => "PlayStore", :buildType => options[:buildType])
  end

  desc "Creates Release Branch and sets Git Tags and finishes release"
  lane :release do |options|
    gradle(
          task: "clean"
    )
    prepareRollOut({:major => options[:major], :minor => options[:minor], :patch => options[:patch], :bld => options[:bld]})
    tab1({:major => options[:major], :minor => options[:minor], :patch => options[:patch], :bld => options[:bld], :buildType => options[:buildType]})
    minix({:major => options[:major], :minor => options[:minor], :patch => options[:patch], :bld => options[:bld], :buildType => options[:buildType]})
    playStore({:major => options[:major], :minor => options[:minor], :patch => options[:patch], :bld => options[:bld], :buildType => options[:buildType]})
  end

  desc "builds an apk"
  lane :buildApk do |options|

    properties = {:major => options[:major], :minor => options[:minor], :patch => options[:patch], :bld => options[:bld]}

    if options[:product].downcase == "Tab1".downcase
      	properties[:forceShrink] = "true"
    else
      	properties[:forceShrink] = "false"
    end

    gradle(
        task: "assemble#{options[:product]}#{options[:buildType].capitalize}",
	properties: properties
    )
  end

  desc "Creates Release Branch and sets Git Tags and finishes release"
  lane :prepareRollOut do |options|
    if !Dir.glob("metadata/android/de-DE/changelogs/#{version_changelog(options)}*.txt").empty?
        UI.user_error!("You need to pass a valid Changelog File for VersionCode #{version_changelog(options)}")
    end
    ensure_git_branch(
        branch: "develop"
    )
    ensure_git_status_clean
    sh ("git flow release start #{version_string(options)}")
    ensure_git_branch(
        branch: "(release\\S)"
    )
    add_git_tag(tag:"beta/#{version_string(options)}-#{options[:bld]}")
    push_to_git_remote(tags:"1")
  end

  desc "Submit a new alpha Build to Playstore"
  lane :alpha do |options|
    supply(
        track: "alpha",
        apk: "app/build/outputs/apk/app-PlayStore-#{options[:buildType]}.apk",
        skip_upload_metadata: "1",
        skip_upload_images: "1",
        skip_upload_screenshots: "1",
        mapping: "app/build/outputs/mapping/PlayStore/release/mapping.txt")
  end

  desc "Promotes all alpha builds to beta in Google Play Store"
  lane :beta do |options|
    ensure_git_branch(
          branch: "(release\\S)"
      )
      ensure_git_status_clean
    supply(
        apk:"app/build/outputs/apk/app-PlayStore-#{options[:buildType]}.apk",
        track:"alpha",
        track_promote_to:"beta",
        skip_upload_apk:"1",
        skip_upload_metadata:"1",
        skip_upload_images:"1",
        skip_upload_screenshots:"1")
  end

  desc "Promotes all beta builds to production in Google Play Store and publishes all local meta data like screenshots ..."
  lane :deploy do |options|
    ensure_git_branch(
          branch: "(release\\S)"
    )
    ensure_git_status_clean
    sh ("git flow release finish -n #{version_string(options)}")
    sh("git checkout master")
    ensure_git_branch(
              branch: "(master)"
        )

    add_git_tag(tag:"release/#{version_string(options)}-#{options[:bld]}")
    promote_to_production(buildType: options[:buildType])

  end

  desc "Promotes to production in playstore"
  lane :promote_to_production do |options|
    supply(
          track:"beta",
          track_promote_to:"production",
          apk:"app/build/outputs/apk/app-PlayStore-#{options[:buildType]}.apk",
          skip_upload_apk:"1")
  end

  desc "Just refreshes the metadata in playstore"
  lane :update_meta_data do |options|
  supply(
        apk:"app/build/outputs/apk/app-#{options[:product]}-#{options[:buildType]}.apk",
        skip_upload_apk:"1")
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "../certificates/Wearparts/secret.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "ag.saitow.wearparts.android" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.1       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.1        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-25**
</details>

**Comment by dabele91** [comment]
Fixed with version 2.54.3
