### ISSUE TITLE
Undefined method `load_configuration_file - trying to call `match` action from a custom action.

### ISSUE THREAD

**Issue by Otbivnoe** [fastlane/fastlane#10158]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to call a `match` action from a custom action. Have used few ways:  just `match(...)` and `Fastlane::Actions::MatchAction.run`, but it doesn't work.
<details><summary>Custom action</summary>

```ruby
module Fastlane
  module Actions
    class MatchForTypeAction < Action

      def self.run(options)
        return unless match_git_url = ENV['MATCH_GIT_URL']

        branch = ENV['MATCH_GIT_BRANCH']
        username = ENV['APPLE_ID']
        team_name = ENV['TEAM']

        app_identifier = options[:app_identifier]
        type = options[:type]
        force = options[:force]
        readonly = options[:readonly]

        Fastlane::Actions::MatchAction.run(
          git_url: match_git_url,
          git_branch: branch,
          type: type,
          app_identifier: app_identifier,
          username: username,
          team_name: team_name,
          force: force,
          readonly: readonly
        )
      end

      def self.description
        'Easily sync your certificates and profiles across your team using git'
      end

      def self.available_options
        require 'match'
        Match::Options.available_options
      end

      def self.authors
        %w[nermolenko]
      end

      def self.is_supported?(platform)
        true
      end

    end
  end
end
```

</details>

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `rsb_match`
<details><summary>Output/Log</summary>

```


+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | import_from_git  | 3           |
| 2    | default_platform | 0           |
| 3    | import_from_git  | 5           |
| 💥   | match_for_type   | 0           |
+------+------------------+-------------+


Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `load_configuration_file' for Hash

URL: https://api.github.com/search/issues?q=undefined%20method%20%60load_configuration_file'%20for%20Hash+repo:fastlane/fastlane
➡️  Call Fastlane actions from another class
    https://github.com/fastlane/fastlane/issues/4603 [closed] 2 💬
    08 Nov 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.4                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.4 (16E195)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import_from_git(
    url: 'https://github.com/rosberry/RSBFastlane.git',
    branch: 'refactoring-actions',
    path: 'RSBFastfile.rb'
)```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| faraday                   | 0.13.1       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.3       |
</details>


*generated on:* **2017-08-26**
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by ohayon** [comment]
Hey @Otbivnoe would you mind running this with `--verbose` so we can see some more context of the issue? Thank you!! 🚀

**Comment by Otbivnoe** [comment]
@ohayon Hey!

```
fastlane rsb_match --verbose                  
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[20:20:32]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-08-29 20:20:35.17]: Checking if there are any plugins that should be loaded...
INFO [2017-08-29 20:20:35.29]: -----------------------------
INFO [2017-08-29 20:20:35.29]: --- Step: import_from_git ---
INFO [2017-08-29 20:20:35.29]: -----------------------------
INFO [2017-08-29 20:20:35.29]: Cloning remote git repo...
INFO [2017-08-29 20:20:35.29]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://github.com/rosberry/RSBFastlane.git' '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-jfpi3g/RSBFastlane.git' --depth 1 -n --branch refactoring-actions
INFO [2017-08-29 20:20:35.30]: ▸ Cloning into '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-jfpi3g/RSBFastlane.git'...
INFO [2017-08-29 20:20:37.41]: $ cd '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-jfpi3g/RSBFastlane.git' && git checkout refactoring-actions 'RSBFastfile.rb'
INFO [2017-08-29 20:20:37.42]: $ cd '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-jfpi3g/RSBFastlane.git' && git checkout refactoring-actions './actions'
INFO [2017-08-29 20:20:37.43]: Successfully loaded custom action '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-jfpi3g/RSBFastlane.git/actions/credentials.rb'.
INFO [2017-08-29 20:20:37.44]: Successfully loaded custom action '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-jfpi3g/RSBFastlane.git/actions/match_for_type.rb'.
INFO [2017-08-29 20:20:37.44]: -----------------------------
INFO [2017-08-29 20:20:37.44]: --- Step: import_from_git ---
INFO [2017-08-29 20:20:37.44]: -----------------------------
INFO [2017-08-29 20:20:37.44]: Cloning remote git repo...
INFO [2017-08-29 20:20:37.44]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://github.com/rosberry/RSBFastlane.git' '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git' --depth 1 -n --branch refactoring-actions
INFO [2017-08-29 20:20:37.45]: ▸ Cloning into '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git'...
INFO [2017-08-29 20:20:39.65]: $ cd '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git' && git checkout refactoring-actions 'RSBMatch.rb'
INFO [2017-08-29 20:20:39.66]: $ cd '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git' && git checkout refactoring-actions './actions'
INFO [2017-08-29 20:20:39.67]: Successfully loaded custom action '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git/actions/credentials.rb'.
INFO [2017-08-29 20:20:39.70]: Successfully loaded custom action '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git/actions/match_for_type.rb'.
INFO [2017-08-29 20:20:39.72]: ------------------------------
INFO [2017-08-29 20:20:39.72]: --- Step: default_platform ---
INFO [2017-08-29 20:20:39.72]: ------------------------------
INFO [2017-08-29 20:20:39.73]: Driving the lane 'rsb_match' 🚀
INFO [2017-08-29 20:20:39.74]: ----------------------------
INFO [2017-08-29 20:20:39.74]: --- Step: match_for_type ---
INFO [2017-08-29 20:20:39.74]: ----------------------------
WARN [2017-08-29 20:20:40.97]: Lane Context:
INFO [2017-08-29 20:20:40.97]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"rsb_match"}
ERROR [2017-08-29 20:20:40.97]: undefined method `load_configuration_file' for #<Hash:0x007f99e7397348>
INFO [2017-08-29 20:20:40.97]: Successfully generated documentation at path '/Users/otbivnoe/Documents/Projects/BEATMix/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | import_from_git  | 2           |
| 2    | default_platform | 0           |
| 3    | import_from_git  | 4           |
| 💥   | match_for_type   | 0           |
+------+------------------+-------------+

ERROR [2017-08-29 20:20:40.98]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `load_configuration_file' for Hash

URL: https://api.github.com/search/issues?q=undefined%20method%20%60load_configuration_file'%20for%20Hash+repo:fastlane/fastlane
➡️  Undefined method `load_configuration_file - trying to call `match` action from a custom action.
    https://github.com/fastlane/fastlane/issues/10158 [open] 1 💬
    17 hours ago

➡️  Call Fastlane actions from another class
    https://github.com/fastlane/fastlane/issues/4603 [closed] 2 💬
    08 Nov 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/actions/match.rb:11:in `run': [!] undefined method `load_configuration_file' for #<Hash:0x007f99e7397348> (NoMethodError)
	from /var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git/actions/match_for_type.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from ../../../../../../var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git/RSBMatch.rb:28:in `block (2 levels) in parsing_binding'
	from ../../../../../../var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git/RSBMatch.rb:27:in `each'
	from ../../../../../../var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170829-4222-j0tcyt/RSBFastlane.git/RSBMatch.rb:27:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by ohayon** [comment]
Hey @Otbivnoe! Thanks for sharing that output. Do you think you could try explicitly doing a `require 'fastlane_core'` before your line of code that calls into `match`? It looks like that method is just unavailable to your call? 🚀

**Comment by Otbivnoe** [comment]
Hi @ohayon, I tried to put `require` just before `Fastlane::Actions::MatchAction.run` in custom action - doesn't work. Tried to put this line before calling my custom action - `match_for_type` - doesn't work as well :(

**Comment by ohayon** [comment]
Hmmm... thats interesting. Okay, I think I have one more thing I'd like for you to try but you may already be doing this. Do you have a `Gemfile` in your directory? If not, could you try making one, and make sure that `gem 'fastlane'` is in side of it. Then run `bundle update` followed by `bundle exec fastlane rsb_match` (or whatever your fastlane command is, just make sure to prefix with `bundle exec`. All that will ensure that you're running in an environment where _match_ and _fastlane_ will be available to you. Let me know if that changes anything. Thanks! 🐙

**Comment by Otbivnoe** [comment]
@ohayon  Unsuccessfully :( Just to make sure, I placed a `Gemfile` on the same level with fastlane folder.
```
Gemfile
fastlane/Fastfile
```

New error:
> bundler: failed to load command: fastlane (/usr/local/bin/fastlane)

Full output:

```
bundle exec fastlane rsb_match --verbose
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
DEBUG [2017-08-30 20:31:39.48]: Checking if there are any plugins that should be loaded...
INFO [2017-08-30 20:31:40.27]: -----------------------------
INFO [2017-08-30 20:31:40.27]: --- Step: import_from_git ---
INFO [2017-08-30 20:31:40.27]: -----------------------------
INFO [2017-08-30 20:31:40.27]: Cloning remote git repo...
INFO [2017-08-30 20:31:40.27]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://github.com/rosberry/RSBFastlane.git' '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-14a3b15/RSBFastlane.git' --depth 1 -n --branch refactoring-actions
INFO [2017-08-30 20:31:40.28]: ▸ Cloning into '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-14a3b15/RSBFastlane.git'...
INFO [2017-08-30 20:31:43.61]: $ cd '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-14a3b15/RSBFastlane.git' && git checkout refactoring-actions 'RSBFastfile.rb'
INFO [2017-08-30 20:31:43.62]: $ cd '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-14a3b15/RSBFastlane.git' && git checkout refactoring-actions './actions'
INFO [2017-08-30 20:31:43.64]: Successfully loaded custom action '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-14a3b15/RSBFastlane.git/actions/credentials.rb'.
INFO [2017-08-30 20:31:43.64]: Successfully loaded custom action '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-14a3b15/RSBFastlane.git/actions/match_for_type.rb'.
INFO [2017-08-30 20:31:43.64]: -----------------------------
INFO [2017-08-30 20:31:43.64]: --- Step: import_from_git ---
INFO [2017-08-30 20:31:43.64]: -----------------------------
INFO [2017-08-30 20:31:43.64]: Cloning remote git repo...
INFO [2017-08-30 20:31:43.64]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://github.com/rosberry/RSBFastlane.git' '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git' --depth 1 -n --branch refactoring-actions
INFO [2017-08-30 20:31:43.65]: ▸ Cloning into '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git'...
INFO [2017-08-30 20:31:45.86]: $ cd '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git' && git checkout refactoring-actions 'RSBMatch.rb'
INFO [2017-08-30 20:31:45.87]: $ cd '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git' && git checkout refactoring-actions './actions'
INFO [2017-08-30 20:31:45.89]: Successfully loaded custom action '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git/actions/credentials.rb'.
INFO [2017-08-30 20:31:45.89]: Successfully loaded custom action '/var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git/actions/match_for_type.rb'.
INFO [2017-08-30 20:31:45.91]: ------------------------------
INFO [2017-08-30 20:31:45.91]: --- Step: default_platform ---
INFO [2017-08-30 20:31:45.91]: ------------------------------
INFO [2017-08-30 20:31:45.92]: Driving the lane 'rsb_match' 🚀
INFO [2017-08-30 20:31:45.93]: ----------------------------
INFO [2017-08-30 20:31:45.93]: --- Step: match_for_type ---
INFO [2017-08-30 20:31:45.93]: ----------------------------
WARN [2017-08-30 20:31:47.17]: Lane Context:
INFO [2017-08-30 20:31:47.17]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"rsb_match"}
ERROR [2017-08-30 20:31:47.17]: undefined method `load_configuration_file' for #<Hash:0x007ff2540b8a08>
INFO [2017-08-30 20:31:47.17]: Successfully generated documentation at path '/Users/otbivnoe/Documents/Projects/BEATMix/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | import_from_git  | 2           |
| 2    | default_platform | 0           |
| 3    | import_from_git  | 5           |
| 💥   | match_for_type   | 0           |
+------+------------------+-------------+

ERROR [2017-08-30 20:31:47.18]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `load_configuration_file' for Hash

URL: https://api.github.com/search/issues?q=undefined%20method%20%60load_configuration_file'%20for%20Hash+repo:fastlane/fastlane
➡️  Undefined method `load_configuration_file - trying to call `match` action from a custom action.
    https://github.com/fastlane/fastlane/issues/10158 [open] 5 💬
    11 minutes ago

➡️  Call Fastlane actions from another class
    https://github.com/fastlane/fastlane/issues/4603 [closed] 2 💬
    08 Nov 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `load_configuration_file' for #<Hash:0x007ff2540b8a08>
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/actions/match.rb:11:in `run'
  /var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git/actions/match_for_type.rb:17:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  ../../../../../../var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git/RSBMatch.rb:30:in `block (2 levels) in parsing_binding'
  ../../../../../../var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git/RSBMatch.rb:29:in `each'
  ../../../../../../var/folders/kv/0ry83zbj0b14d6gwkp8qc3th0000gn/T/fl_clone20170830-2276-1t6hxil/RSBFastlane.git/RSBMatch.rb:29:in `block in parsing_binding'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.54.3/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

**Comment by Otbivnoe** [comment]
@ohayon Hey! Any ideas? :( I've also tried to accomplish it by some helper functions, [but without results](https://stackoverflow.com/questions/45840991/fastlane-cannot-load-file-by-require-command).

**Comment by KrauseFx** [comment]
instead of 
```ruby
Fastlane::Actions::MatchAction.run(
          git_url: match_git_url,
          git_branch: branch,
          type: type,
          app_identifier: app_identifier,
          username: username,
          team_name: team_name,
          force: force,
          readonly: readonly
        )
```
could you just try
```ruby
other_action.match(git_url: match_git_url, ...)
```

with `...` being the other parameters.

**Comment by Otbivnoe** [comment]
@KrauseFx it works, awesome! Thanks! :)
