### ISSUE TITLE
Unable to send the crash report.

### ISSUE THREAD

**Issue by wd** [fastlane/fastlane#10197]
### Issue Description
Every time I generate an error from my plugin, fastlane will try to send a crash report, and will stuck there 1min.

How to disable this action? This almost make me crazy, to slow.

```
INFO [2017-08-30 21:34:40.83]: Yafirim Begin process
ERROR [2017-08-30 21:35:40.87]: Unable to send the crash report.
ERROR [2017-08-30 21:35:40.87]: Please open an issue on GitHub if you need help!
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by ohayon** [comment]
Hey @wd, apologies for the frustration with that output! Could you share the output from before that message about the crash report so we can see some more of the context? Thanks! 🐙

**Comment by wd** [comment]
Sorry, I was frustrated yesterday. Here is the detailed output. `fastlane-plugin-yafirim` is a plugin write by me, 

```
$ bundle exec fastlane publish_firim --verbose                                                                                                                                                                                                                             DEBUG [2017-08-30 21:34:40.64]: Checking if there are any plugins that should be loaded...                                                                                                                                                                                                                                             DEBUG [2017-08-30 21:34:40.64]: Loading 'fastlane-plugin-yafirim' plugin
INFO [2017-08-30 21:34:40.68]: gem 'fastlane-plugin-yafirim' is already installed                                                                                                                                                                                                                                                      +-------------------------+---------+-----------------------+                                                                                                                                                                                                                                                                          |                       Used plugins                        |
+-------------------------+---------+-----------------------+                                                                                                                                                                                                                                                                          | Plugin                  | Version | Action                |                                                                                                                                                                                                                                                                          +-------------------------+---------+-----------------------+
| fastlane-plugin-yafirim | 0.1.0   | detect_values yafirim |                                                                                                                                                                                                                                                                          +-------------------------+---------+-----------------------+
INFO [2017-08-30 21:34:40.82]: -------------------------------------------------                                                                                                                                                                                                                                                       INFO [2017-08-30 21:34:40.82]: --- Step: Verifying required fastlane version ---                                                                                                                                                                                                                                                       INFO [2017-08-30 21:34:40.82]: -------------------------------------------------
INFO [2017-08-30 21:34:40.82]: Your fastlane version 2.54.3 matches the minimum requirement of 2.54.3  ✅                                                                                                                                                                                                                               INFO [2017-08-30 21:34:40.82]: ------------------------------                                                                                                                                                                                                                                                                          INFO [2017-08-30 21:34:40.82]: --- Step: default_platform ---
INFO [2017-08-30 21:34:40.82]: ------------------------------                                                                                                                                                                                                                                                                          INFO [2017-08-30 21:34:40.82]: Driving the lane 'android publish_firim' 🚀                                                                                                                                                                                                                                                              INFO [2017-08-30 21:34:40.83]: ---------------------
INFO [2017-08-30 21:34:40.83]: --- Step: yafirim ---                                                                                                                                                                                                                                                                                   INFO [2017-08-30 21:34:40.83]: ---------------------                                                                                                                                                                                                                                                                                   INFO [2017-08-30 21:34:40.83]: Yafirim Begin process
ERROR [2017-08-30 21:35:40.87]: Unable to send the crash report.                                                                                                                                                                                                                                                                       ERROR [2017-08-30 21:35:40.87]: Please open an issue on GitHub if you need help!
WARN [2017-08-30 21:35:40.87]: Lane Context:
INFO [2017-08-30 21:35:40.87]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android publish_firim"}
ERROR [2017-08-30 21:35:40.87]: Error, file ./app/build/outputs/apk/release.apk not exists.
INFO [2017-08-30 21:35:40.87]: Successfully generated documentation at path '/Users/wd/android/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | yafirim                             | 0           |
+------+-------------------------------------+-------------+

DEBUG [2017-08-30 21:35:40.88]: All plugins are up to date
ERROR [2017-08-30 21:35:40.88]: fastlane finished with errors
ERROR [2017-08-30 21:36:40.90]: Unable to send the crash report.
ERROR [2017-08-30 21:36:40.90]: Please open an issue on GitHub if you need help!
DEBUG [2017-08-30 21:36:40.90]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Error, file ./app/build/outputs/apk/release.apk not exists.
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/wd/work/yafirm/fastlane-plugin-yafirim/lib/fastlane/plugin/yafirim/actions/yafirim_action.rb:22:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:30:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'                                                                                                                                                                                                                           /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:45:in `execute'                                                                                                                                                                                                                                    /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'                                                                                                                                                                                                                          /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'                                                                                                                                                                                                       /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'                                                                                                                                                                                                                                    /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'                                                                                                                                                                                                                       /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'                                                                                                                                                                                                                                   /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'                                                                                                                                                                                                                           /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'                                                                                                                                                                                                                    /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/bin/fastlane:20:in `<top (required)>'                                                                                                                                                                                                                                              /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
```

**Comment by wd** [comment]
Is there a way that I can disable the 'send the crash report' behavior of fastlane? I have tried `fastlane disable_crash_reporting`, but get lane not found error.

**Comment by ohayon** [comment]
Hey @wd, you can disable crash reporting by setting the `FASTLANE_OPT_OUT_CRASH_REPORTING=1` 🚀

**Comment by wd** [comment]
@ohayon  ok, thanks.
