### ISSUE TITLE
`brew install git-flow`fails with error

### ISSUE THREAD

**Issue by Blackjacx** [fastlane/fastlane#10288]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
```
╭─stherold@StefansMBPTouch.fritz.box ~/dev/projects/private/Gasoline ‹system› ‹develop›
╰─➤  bundle exec fastlane playground
/Users/stherold/.gem/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
+---------------------------+---------+-------------------------------------------------------------------+
|                                              Used plugins                                               |
+---------------------------+---------+-------------------------------------------------------------------+
| Plugin                    | Version | Action                                                            |
+---------------------------+---------+-------------------------------------------------------------------+
| fastlane-plugin-changelog | 0.7.0   | emojify_changelog read_changelog stamp_changelog update_changelog |
+---------------------------+---------+-------------------------------------------------------------------+

[00:01:28]: -------------------------------------------------
[00:01:28]: --- Step: Verifying required fastlane version ---
[00:01:28]: -------------------------------------------------
[00:01:28]: Your fastlane version 2.55.0 matches the minimum requirement of 2.45.0  ✅
[00:01:28]: ------------------------------
[00:01:28]: --- Step: default_platform ---
[00:01:28]: ------------------------------
[00:01:29]: Driving the lane 'playground' 🚀
[00:01:29]: -----------------------
[00:01:29]: --- Step: cocoapods ---
[00:01:29]: -----------------------
[00:01:29]: $ bundle exec pod install
[00:01:30]: ▸ Analyzing dependencies
[00:01:30]: ▸ Downloading dependencies
[00:01:30]: ▸ Using Crashlytics (3.8.5)
[00:01:30]: ▸ Using Fabric (1.6.12)
[00:01:30]: ▸ Using Nimble (7.0.1)
[00:01:30]: ▸ Using Quick (1.1.0)
[00:01:30]: ▸ Using SHDateFormatter (0.9.6)
[00:01:30]: ▸ Using SwiftLint (0.22.0)
[00:01:30]: ▸ Generating Pods project
[00:01:30]: ▸ Integrating client project
[00:01:31]: ▸ Sending stats
[00:01:31]: ▸ Pod installation complete! There are 6 dependencies from the Podfile and 6 total pods installed.
[00:01:31]: -----------------------------------
[00:01:31]: --- Step: brew install git-flow ---
[00:01:31]: -----------------------------------
[00:01:31]: $ brew install git-flow
[00:01:32]: ▸ /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find CFPropertyList-2.3.5 in any of the sources (Bundler::GemNotFound)
[00:01:32]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
[00:01:32]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
[00:01:32]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
[00:01:32]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
[00:01:32]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
[00:01:32]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
[00:01:32]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
[00:01:32]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
[00:01:32]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
[00:01:32]: ▸ from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[00:01:32]: ▸ from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[00:01:34]: ▸ Updating Homebrew...
[00:01:39]: ▸ /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find CFPropertyList-2.3.5 in any of the sources (Bundler::GemNotFound)
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
[00:01:39]: ▸ from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[00:01:39]: ▸ from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[00:01:39]: ▸ /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find CFPropertyList-2.3.5 in any of the sources (Bundler::GemNotFound)
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
[00:01:39]: ▸ from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
[00:01:39]: ▸ from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[00:01:39]: ▸ from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[00:01:39]: --------------------------
[00:01:39]: --- Step: notification ---
[00:01:39]: --------------------------
[00:01:39]: -------------------
[00:01:39]: --- Step: slack ---
[00:01:39]: -------------------
[00:01:40]: Successfully sent Slack notification
+------------------+------------+
|         Lane Context          |
+------------------+------------+
| DEFAULT_PLATFORM | ios        |
| PLATFORM_NAME    |            |
| LANE_NAME        | playground |
+------------------+------------+
[00:01:40]: Exit status of command 'brew install git-flow' was 1 instead of 0.
/Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find CFPropertyList-2.3.5 in any of the sources (Bundler::GemNotFound)
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Updating Homebrew...
/Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find CFPropertyList-2.3.5 in any of the sources (Bundler::GemNotFound)
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find CFPropertyList-2.3.5 in any of the sources (Bundler::GemNotFound)
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'


+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 2           |
| 💥   | brew install git-flow               | 8           |
| 5    | notification                        | 0           |
| 6    | slack                               | 0           |
+------+-------------------------------------+-------------+

[00:01:40]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/stherold/.gem/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'brew install git-flow' was 1 instead of 0.
/Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find CFPropertyList-2.3.5 in any of the sources (Bundler::GemNotFound)
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Updating Homebrew...
/Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find CFPropertyList-2.3.5 in any of the sources (Bundler::GemNotFound)
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find CFPropertyList-2.3.5 in any of the sources (Bundler::GemNotFound)
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /Users/stherold/.gem/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `sh_control_output'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/helper/sh_helper.rb:14:in `sh_no_action'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/fast_file.rb:177:in `block in sh'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/fast_file.rb:176:in `sh'
  Fastfile:76:in `block in parsing_binding'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/stherold/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/stherold/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/stherold/.gem/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/stherold/.gem/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Users/stherold/.gem/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/stherold/.gem/gems/fastlane-2.55.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/stherold/.gem/gems/fastlane-2.55.0/bin/fastlane:20:in `<top (required)>'
  /Users/stherold/.gem/bin/fastlane:22:in `load'
  /Users/stherold/.gem/bin/fastlane:22:in `<top (required)>'
```

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.13.1                                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/               |
| Xcode Version               | 9.0                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Fastlane Documentation:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
#
# Fastlane actions: 
# https://docs.fastlane.tools/actions/
#
# Bitrise with fastlane example:
# https://github.com/bitrise-samples/fastlane/blob/master/BitriseFastlaneSample/fastlane/Fastfile
#
# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`
#
#
# This file was created by the help of https://gist.github.com/ulhas/e8e529d08849b8cda947
#
#
# NOTE: To use faslane first do:
#           gem install bundler && bundle install
#
#       and then run:
#           bundle exec fastlane release product_name:Gasoline version:"1.0.0" github_account:"blackjacx"
#           bundle exec fastlane test product_name:Gasoline
#
# Configure the following environment variables for your project 
# on your CI and in fastlane/.env:
#
# ENV["SLACK_URL"] = "..."
# ENV["GITHUB_TOKEN"] = "..."
# ENV["BITRISE_DEPLOY_DIR"] = "..."





# TODO: Include Bitrise Public Page URL in SlackMessge
# TODO: Setup Crashlytics
# TODO: deploy to TestFlight, Crashlytics, Hockey, ... & move away from Bitrise



# This is the minimum version number required. 
# Update this, if you use features of a newer version.
fastlane_version "2.45.0"

default_platform :ios



before_all do
  cocoapods(use_bundle_exec: true)
end

# after_all do |lane|
# end

error do |lane, exception|
  # This block is called, only if the executed lane failed
  slack(success: false, message: "*#{exception.message}*")
end

################################################################################
# Release Lane
################################################################################

desc "Releases a new product version"
lane :release do |options|

  if !options[:product_name] || !options[:version] || !options[:github_account]
    raise "No product_name, version specified, or github_account specified!".red
  end

  product_name = options[:product_name]
  version = options[:version]
  github_account = options[:github_account]
  project = "#{product_name}.xcodeproj"
  workspace = "#{product_name}.xcworkspace"
  deploy_dir = ENV["BITRISE_DEPLOY_DIR"]
  ipa_name = "#{product_name}.ipa"
  dsym_name = "#{product_name}.app.dSYM.zip"
 
  ensure_git_status_clean(show_uncommitted_changes: true)
  ensure_git_branch(branch: "develop")
  git_pull

  test(product_name: product_name, run_danger: true)

  sh "cd /tmp && wget --no-check-certificate -q -O - https://github.com/nvie/gitflow/raw/develop/contrib/gitflow-installer.sh | bash && cd -"
  sh "git checkout master && git checkout develop" # init local branches
  sh "git flow init -d" # initialize git-flow with defaults
  sh "git flow release start #{version}"

  # Increments CFBundleVersion by one and sets CFBundleShortVersionString
  increment_version_number(xcodeproj: project, version_number: version)
  increment_build_number(xcodeproj: project)

  # read changelog
  changelog = read_changelog

  # stamp unreleased section with released version
  stamp_changelog(section_identifier: version)

  sh "git commit -am 'Fastlane: Release on Production #{version}'"
  
  # Finish the release branch. The shell may hang here because it: 
  # 1) promts for a merge message.
  # 
  # To get around this do the following:
  # 1) git config --global core.mergeoptions --no-edit
  sh "git flow release finish -m 'finished_release_on_production_#{version}' #{version}"   

  # push all changes on all branches and all tags
  push_to_git_remote(local_branch: "develop", remote_branch: "develop", force: true)
  push_to_git_remote(local_branch: "master", remote_branch: "master", force: true)

  gym(
	workspace: workspace, 
	scheme: product_name,
	output_directory: deploy_dir,
	output_name: ipa_name,
	export_method: "ad-hoc",
	include_bitcode: true,
  )

  github_release = set_github_release(
    repository_name: "#{github_account}/#{product_name}",
    api_token: ENV["GITHUB_TOKEN"],
    name: version,
    tag_name: version,
    description: ("#{changelog}" rescue "No changelog provided"),
    commitish: "master",
    upload_assets: ["#{deploy_dir}/#{ipa_name}", "#{deploy_dir}/#{dsym_name}"]
  )

  # crashlytics(
  #   crashlytics_path: "./Crashlytics.framework",
  #   api_token: ENV['CRASHLYTICS_API_TOKEN'],
  #   build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
  # 	ipa_path: "#{deploy_dir}/#{ipa_name}"
  # )

  # This is called, only if the executed lane was successful
  slack(success: true, message: "*Successfully deployed new update.*")
end

################################################################################
# Test Lane
################################################################################

desc "Runs tests optionally with danger"
lane :test do |options|

  if !options[:product_name]
    raise "No product_name or use_ci specified".red
  end

  product_name = options[:product_name]
  run_danger = options[:run_danger]

  # Easily run tests of your iOS app using scan
  scan(
    workspace: "#{product_name}.xcworkspace",
    scheme: product_name,
    clean: true,
    devices: ["iPhone 7"],
    skip_build: true,
    thread_sanitizer: true,
    output_types: "html",
    output_directory: ENV["BITRISE_DEPLOY_DIR"]
  )

  # Runs danger for the project
  if run_danger
    danger(
      use_bundle_exec: true,
      github_api_token: ENV["GITHUB_TOKEN"],
      verbose: true
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-changelog | 0.7.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.15.4       |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.6        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.9        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.14.0       |
| no_proxy_fix              | 0.1.1        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.7.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| danger                    | 5.4.0        |
| danger-plugin-api         | 1.0.0        |
| danger-changelog          | 0.2.1        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.5       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| fastlane-plugin-changelog | 0.7.0        |
</details>

*generated on:* **2017-09-08**
</details>

**Comment by KrauseFx** [comment]
Why do you run `brew install git-flow` as part as your Fastfile? is that in your config? I'd recommend not to install dependencies on the fly as part of your deployment

**Comment by Blackjacx** [comment]
Yep I need it as part of my deployment since I have local changes in my project after the deployment that I want to be committed and built. For that I use the gitflow tool. It proper handels version increments and changelog updates.

**Comment by Blackjacx** [comment]
OK @KrauseFx I changed my workflow how I release the app. Now I don't need t change my repo inside the script anymore. So this can be closed. 

But still it should be possible to install 3rd party dependencies, i.e. for a CI machine that runs a VM which has nothing initially...

**Comment by 123kyky** [comment]
We have (what we think) is a valid scenario to run a brew install. Does this affect your decision that we should not be using calling homebrew from within a fastfile? This was previously working, only just caught these errors last week.

We have an onboarding lane where we do some initial setup/help like pulling all submodules from git, pulling provisioning and signing from Apple, and installing an xcode documentation plugin. We were also install homebrew and swiftlint (through homebrew). This is helpful to get new machines up and running with our project and useful to call periodically (like when you just need a clean slate in git).

We are encountering this issue with any operation calling homebrew, either installing it itself, installing a dependency, or updating existing. Should we move all of our homebrew operations elsewhere?

**Comment by Blackjacx** [comment]
Yeah for exactly these scenarios I think calling brew inside a fastlane environment should definitely work

**Comment by m-ruhl** [comment]
We created a fastlane-plugin for exactly this purpose:
https://github.com/NovaTecConsulting/fastlane-plugin-brew

**Comment by Blackjacx** [comment]
Oh nice! Didn't know that... Why isn't that listet on the official Actions page?

**Comment by Blackjacx** [comment]
Btw. @123kyky you can install swiftlint through Cocoapods which is a very nice way to install and maintain commandline tool dependencies.
