### ISSUE TITLE
Can't Update Fastlane to Latest Version

### ISSUE THREAD

**Issue by herberzt** [fastlane/fastlane#10294]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I was trying to install a plugin for Cordova support and got the following error: 
```
bash-3.2$ fastlane add_plugin cordova
Ignoring nokogiri-1.6.6.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.6.2

/Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
[13:22:32]: -------------------------------------------------
[13:22:32]: --- Step: Verifying required fastlane version ---
[13:22:32]: -------------------------------------------------
[13:22:32]: fastlane version valid
[13:22:32]: ------------------------------
[13:22:32]: --- Step: default_platform ---
[13:22:32]: ------------------------------
[13:22:32]: Variable Dump:
[13:22:32]: {:DEFAULT_PLATFORM=>:ios}
[13:22:32]: Could not find lane 'add_plugin cordova'. Available lanes: ios test, ios beta, ios deploy

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

[13:22:32]: fastlane finished with errors
/Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/lib/fastlane/runner.rb:31:in `execute': Could not find lane 'add_plugin cordova'. Available lanes: ios test, ios beta, ios deploy (RuntimeError)
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/lib/fastlane/command_line_handler.rb:31:in `handle'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/bin/fastlane:36:in `block (2 levels) in run'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/bin/fastlane:127:in `run'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/bin/fastlane:133:in `<top (required)>'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/fastlane:23:in `load'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/fastlane:23:in `<main>'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/ruby_executable_hooks:15:in `eval'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/ruby_executable_hooks:15:in `<main>'
```

So then I was looking at https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md
and decided that I should upgrade to the latest version of fastlane.

```
bash-3.2$ fastlane -v
fastlane 1.29.2

bash-3.2$ fastlane update_fastlane
Ignoring nokogiri-1.6.6.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.6.2
/Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
[13:26:06]: -------------------------------------------------
[13:26:06]: --- Step: Verifying required fastlane version ---
[13:26:06]: -------------------------------------------------
[13:26:06]: fastlane version valid
[13:26:06]: ------------------------------
[13:26:06]: --- Step: default_platform ---
[13:26:06]: ------------------------------
[13:26:06]: Variable Dump:
[13:26:06]: {:DEFAULT_PLATFORM=>:ios}
[13:26:06]: Could not find lane 'ios update_fastlane'. Available lanes: ios test, ios beta, ios deploy

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

[13:26:06]: fastlane finished with errors
/Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/lib/fastlane/runner.rb:31:in `execute': Could not find lane 'ios update_fastlane'. Available lanes: ios test, ios beta, ios deploy (RuntimeError)
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/lib/fastlane/command_line_handler.rb:31:in `handle'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/bin/fastlane:36:in `block (2 levels) in run'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/bin/fastlane:127:in `run'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/bin/fastlane:133:in `<top (required)>'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/fastlane:23:in `load'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/fastlane:23:in `<main>'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/ruby_executable_hooks:15:in `eval'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/ruby_executable_hooks:15:in `<main>'

bash-3.2$ gem update fastlane
Updating installed gems
Nothing to update
```

None of these steps got me to the latest version.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
bash-3.2$ fastlane
Ignoring nokogiri-1.6.6.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.6.2
/Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
[13:27:39]: -------------------------------------------------
[13:27:39]: --- Step: Verifying required fastlane version ---
[13:27:39]: -------------------------------------------------
[13:27:39]: fastlane version valid
[13:27:39]: ------------------------------
[13:27:39]: --- Step: default_platform ---
[13:27:39]: ------------------------------
[13:27:39]: You must provide a lane to drive. Available lanes:
1) ios test
2) ios beta
3) ios deploy
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
bash-3.2$ fastlane env
Ignoring nokogiri-1.6.6.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.6.2
/Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
[13:28:08]: -------------------------------------------------
[13:28:08]: --- Step: Verifying required fastlane version ---
[13:28:08]: -------------------------------------------------
[13:28:08]: fastlane version valid
[13:28:08]: ------------------------------
[13:28:08]: --- Step: default_platform ---
[13:28:08]: ------------------------------
[13:28:08]: Variable Dump:
[13:28:08]: {:DEFAULT_PLATFORM=>:ios}
[13:28:08]: Could not find lane 'ios env'. Available lanes: ios test, ios beta, ios deploy

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

[13:28:08]: fastlane finished with errors
/Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/lib/fastlane/runner.rb:31:in `execute': Could not find lane 'ios env'. Available lanes: ios test, ios beta, ios deploy (RuntimeError)
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/lib/fastlane/command_line_handler.rb:31:in `handle'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/bin/fastlane:36:in `block (2 levels) in run'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/bin/fastlane:127:in `run'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/gems/fastlane-1.29.2/bin/fastlane:133:in `<top (required)>'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/fastlane:23:in `load'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/fastlane:23:in `<main>'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/ruby_executable_hooks:15:in `eval'
        from /Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/ruby_executable_hooks:15:in `<main>'
```

## Additional information to help:
```
bash-3.2$ which ruby
/Users/zack/.rvm/rubies/ruby-2.3.1/bin/ruby

bash-3.2$ which fastlane
/Users/zack/.rvm/gems/ruby-2.3.1@bidwrangler_phonegap/bin/fastlane
```

**Comment by KrauseFx** [comment]
You're using a really old version of fastlane, please make sure to update using `[sudo] gem update fastlane`, or if you have a Gemfile, use `bundle update`

**Comment by herberzt** [comment]
I think that worked! thanks a bunch
