### ISSUE TITLE
spaceship - Get only 'live' apps from itc

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#10310]
What's the most efficient way to get the list of live apps from the `spaceship` apis? There seems to be one method `live_version` which could be possibly used to get the live version but I am not sure if this is the efficient way because calling `live_version` would iterate through list of all application objects and call network API ([reference](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/application.rb#L107)).

**Comment by KrauseFx** [comment]
Calling `live_version` doesn't query all application objects from my understanding, but instead sends this request https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tunes_client.rb#L316-L332

**Comment by RishabhTayal** [comment]
It doesn't query all applications. My code looks like this. 

```
all_apps = Spaceship::Tunes::Application.all
live_apps = all_apps.select { |app|
  app.live_version != nil
}
```

This will send request in a loop. Is this the correct way?

**Comment by ohayon** [comment]
Hey @RishabhTayal that is what I would say to do for now. I don't believe there is a way to get just all the live versions from iTC directly sadly :( .

**Comment by RishabhTayal** [comment]
@ohayon for my apps I am getting exception in [here](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L588) when I access the ```live_version```.

Here is the ```all_apps``` array in my case.

<details><summary>all_apps</summary>

```
<Spaceship::Tunes::Application 
	apple_id="1252772653", 
	name="Github Release Tracker", 
	vendor_id="1498506458", 
	bundle_id="com.rtayal.GHReleases", 
	last_modified=1499117755000, 
	issues_count=0, 
	app_icon_preview_url="https://is4-ssl.mzstatic.com/image/thumb/Purple117/v4/9b/c9/db/9bc9db4c-4e8e-3ebf-7998-571b72352c8a/pr_source.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1170208387", 
	name="Cotton Calculator", 
	vendor_id="com.rtayal.cotton", 
	bundle_id="com.rtayal.Cotton", 
	last_modified=1504295706000, 
	issues_count=1, 
	app_icon_preview_url="https://is4-ssl.mzstatic.com/image/thumb/Purple22/v4/5d/28/cf/5d28cf5d-2d2b-8ea8-5c29-ca39a6bf4d5e/mzl.okcddume.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1142324557", 
	name="Joke A Day", 
	vendor_id="com.rtayal.Jokes", 
	bundle_id="com.rtayal.Jokes", 
	last_modified=1479315967000, 
	issues_count=0, 
	app_icon_preview_url="https://is4-ssl.mzstatic.com/image/thumb/Purple62/v4/66/65/17/6665173d-1de6-4c7a-57dd-287bee41790d/pr_source.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="898275446", 
	name="GoCandid - Add fun and motion to your pictures", 
	vendor_id="com.rtayal.ping", 
	bundle_id="com.rtayal.gocandid", 
	last_modified=1504295706000, 
	issues_count=0, 
	app_icon_preview_url="https://is1-ssl.mzstatic.com/image/thumb/Purple5/v4/73/12/ba/7312baeb-bd85-6368-f5a3-c22a92b03edc/mzl.royirmmi.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1239136676", 
	name="DaringFireball", 
	vendor_id="1495341340", 
	bundle_id="com.rtayal.Daring-Fireball", 
	last_modified=1495341346000, 
	issues_count=0, 
	app_icon_preview_url=nil, 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1166260530", 
	name="Translate - translate in different languages", 
	vendor_id="com.rtayal.Translate", 
	bundle_id="com.rtayal.Translate", 
	last_modified=1483974069000, 
	issues_count=0, 
	app_icon_preview_url="https://is3-ssl.mzstatic.com/image/thumb/Purple71/v4/c9/f1/e4/c9f1e419-876f-13fc-a931-1389d7fbdb18/mzl.yehkaxah.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1061690782", 
	name="TVExample", 
	vendor_id="tvexample", 
	bundle_id="com.rtayal.tvexample", 
	last_modified=1451536222000, 
	issues_count=0, 
	app_icon_preview_url=nil, 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="appletvos">]>
<Spaceship::Tunes::Application 
	apple_id="943609004", 
	name="ParseBoard - Dashboard for Parse", 
	vendor_id="com.rtayal.parse", 
	bundle_id="com.rtayal.ParseBoard", 
	last_modified=1479492037000, 
	issues_count=0, 
	app_icon_preview_url="https://is3-ssl.mzstatic.com/image/thumb/Purple4/v4/84/2e/2a/842e2ab7-2d6f-b207-0f1f-51d6b3174932/mzl.dikyhfsh.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="979972793", 
	name="Jump Jump Jump Game", 
	vendor_id="com.rtayal.jump", 
	bundle_id="com.rtayal.jump", 
	last_modified=1492889468000, 
	issues_count=0, 
	app_icon_preview_url="https://is1-ssl.mzstatic.com/image/thumb/Purple111/v4/12/48/db/1248dbc7-9348-3f93-40f1-3715a05cd4f9/mzm.pwqrwici.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1066002152", 
	name="EmailCollector", 
	vendor_id="com.rtayal.emailcollector", 
	bundle_id="com.rtayal.emailcollector", 
	last_modified=1504297078000, 
	issues_count=0, 
	app_icon_preview_url="https://is1-ssl.mzstatic.com/image/thumb/Purple69/v4/6a/3f/d3/6a3fd387-cf4a-c2f4-5d10-93cdbf4ef50c/pr_source.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="955870904", 
	name="test game parakeet", 
	vendor_id="com.testgame", 
	bundle_id="com.jjustind.purrocket2", 
	last_modified=1494882099000, 
	issues_count=0, 
	app_icon_preview_url="https://is4-ssl.mzstatic.com/image/thumb/Purple127/v4/bf/5c/cc/bf5ccc6b-4685-191b-c899-e7967feb73e2/pr_source.jpg/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="875395391", 
	name="vCinity - Chat Without Internet", 
	vendor_id="com.rtayal.chatapp", 
	bundle_id="com.rtayal.ChatApp", 
	last_modified=1505057915000, 
	issues_count=1, 
	app_icon_preview_url="https://is3-ssl.mzstatic.com/image/thumb/Purple30/v4/b2/5a/f1/b25af1cd-13d1-1ebc-bf74-196693942107/mzl.cmpqhutn.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="957426073", 
	name="RepairShift Test", 
	vendor_id="com.rtayal.repairshift", 
	bundle_id="com.rtayal.RepairShift2", 
	last_modified=1492772859000, 
	issues_count=1, 
	app_icon_preview_url="https://is1-ssl.mzstatic.com/image/thumb/Purple122/v4/f2/6d/8b/f26d8bad-5503-57f7-fad6-2b68375a56bc/contsched.cvcfjqdy.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1158085895", 
	name="Scratch `em", 
	vendor_id="com.rtayal.scratchitstickers", 
	bundle_id="com.rtayal.ScratchItStickers", 
	last_modified=1480699375000, 
	issues_count=0, 
	app_icon_preview_url="https://is5-ssl.mzstatic.com/image/thumb/Purple62/v4/87/91/2f/87912fdc-814a-2e60-4bb5-8ba6c0e4ff8e/pr_source.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1281668115", 
	name="Review Monitor - Manage App Reviews", 
	vendor_id="io.rtayal.ReviewMonitor", 
	bundle_id="io.rtayal.ReviewMonitor", 
	last_modified=1505168041000, 
	issues_count=0, 
	app_icon_preview_url=nil, 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="950713207", 
	name="ttes", 
	vendor_id="asdfdsa", 
	bundle_id="com.joeldwyerTumbleCat2", 
	last_modified=1448303541000, 
	issues_count=0, 
	app_icon_preview_url=nil, 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1239119564", 
	name="Pods_DaringFireball", 
	vendor_id="1495328632", 
	bundle_id="org.cocoapods.Pods-DaringFireball", 
	last_modified=1495328638000, 
	issues_count=0, 
	app_icon_preview_url=nil, 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1074388907", 
	name="Trafficking", 
	vendor_id="com.rtayal.Trafficking", 
	bundle_id="com.rtayal.TraffickingPolice1", 
	last_modified=1478887978000, 
	issues_count=0, 
	app_icon_preview_url="https://is4-ssl.mzstatic.com/image/thumb/Purple49/v4/2d/18/89/2d1889a3-1a68-9844-86fa-6b8e63e01863/mzl.zbdolorm.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="1185165692", 
	name="TempMessageApp", 
	vendor_id="1481343968", 
	bundle_id="com.rtayal.MessageGame", 
	last_modified=1481929502000, 
	issues_count=0, 
	app_icon_preview_url=nil, 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
<Spaceship::Tunes::Application 
	apple_id="853205272", 
	name="FilterVilla - Apply Filters To All Your Photos", 
	vendor_id="filtervilla", 
	bundle_id="com.rtayal.FilterVilla", 
	last_modified=1448303553000, 
	issues_count=0, 
	app_icon_preview_url="https://is2-ssl.mzstatic.com/image/thumb/Purple/v4/e3/ea/bc/e3eabcea-407f-935c-7ab2-9f3e6ba50e1f/mzl.bfgpblom.png/340x340bb-80.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>
```
</details>

**Comment by ohayon** [comment]
Hey @RishabhTayal, would you mind sharing the entire output from the command line? Would be helpful to see all of the context.

**Comment by RishabhTayal** [comment]
@ohayon How can I get the entire output if I am running `spaceship` from `irb`?

**Comment by RishabhTayal** [comment]
@ohayon Any update here?

**Comment by ohayon** [comment]
Ah, apologies, I didnt realize that you were using `irb`. But you should see a stack trace in `irb` right?

**Comment by RishabhTayal** [comment]
Any special parameter I need to pass while running irb? By default I don't see the stack trace.

**Comment by RishabhTayal** [comment]
@ohayon This is the complete error I get in the stack trace.

<details><summary>Error</summary>

```
Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unexpected Error"]}, "statusCode"=>"ERROR"}
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-b50b0af82a14/spaceship/lib/spaceship/client.rb:588:in `parse_response'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-b50b0af82a14/spaceship/lib/spaceship/tunes/tunes_client.rb:332:in `app_version'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-b50b0af82a14/spaceship/lib/spaceship/tunes/app_version.rb:267:in `find'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-b50b0af82a14/spaceship/lib/spaceship/tunes/application.rb:107:in `live_version'
	from (irb):6:in `block in irb_binding'
	from (irb):5:in `select'
	from (irb):5
	from /Users/rtayal/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<top (required)>'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rtayal/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```
</details>

**Comment by RishabhTayal** [comment]
This seems like an issue with a particular app in my iTunes account. The app is returned in the `	Spaceship::Tunes::Application.all` list, but the app is not showing up in the iTunes connect dashboard portal website. I think there was some corrupted data in the Apple database which is causing this error. Nothing wrong with `spaceship`. I have contacted Apple regarding this issue and expecting to hear back from them in couple of days.

**Comment by ohayon** [comment]
Thanks @RishabhTayal ! Going to close this issue for now! Let us know if you are still running into issues! 🚀

**Comment by RishabhTayal** [comment]
**Update on this issue:** 

Apple responded to me saying I deleted this particular app 2 years back that's why it's not showing up in the iTC dashboard. 

I am not sure how you can delete the app from App Store. Is there a feature to delete the app from itc? Even if there is, why they are returning this app in the api response when called from `spaceship`.

**Comment by ohayon** [comment]
Yeah thats pretty bizarre that they are doing that. I didnt realize you could even delete an app from iTC hahaha.
