### ISSUE TITLE
Supply commands stuck at fetching a new access token from google

### ISSUE THREAD

**Issue by swl367** [fastlane/fastlane#10401]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm not sure why this isn't working anymore, but it seems like anything I run with fastlane supply results in a timeout. My json containing the service account keys/secrets are untouched.

##### Complete output when running fastlane, including the stack trace and command used
[fastlane supply run --track alpha --verbose

+-------------------------+---------------------------------------+
|                    Summary for supply 2.58.0                    |
+-------------------------+---------------------------------------+
| track                   | alpha                                 |
| package_name            | com.xxx.yyyy           |
| json_key                | ./fastlaneaccess.json                 |
| apk                     | app/build/outputs/apk/app-release.apk |
| skip_upload_apk         | false                                 |
| skip_upload_metadata    | false                                 |
| skip_upload_images      | false                                 |
| skip_upload_screenshots | false                                 |
| validate_only           | false                                 |
| check_superseded_tracks | false                                 |
+-------------------------+---------------------------------------+

DEBUG [2017-09-22 10:45:18.25]: Fetching a new access token from Google...
ERROR [2017-09-22 10:47:18.28]: Unable to send the crash report.
ERROR [2017-09-22 10:47:18.28]: Please open an issue on GitHub if you need help!

Looking for related GitHub issues on fastlane/fastlane...
Search query: execution expired

URL: https://api.github.com/search/issues?q=execution%20expired+repo:fastlane/fastlane
➡️  OBB upload times out (TransmissionError: execution expired)
    https://github.com/fastlane/fastlane/issues/9573 [closed] 3 💬
    3 weeks ago

➡️  in initialize: execution expired (Faraday::ConnectionFailed)
    https://github.com/fastlane/fastlane/issues/9197 [closed] 11 💬
    4 weeks ago

➡️  setting FASTLANE_SKIP_UPDATE_CHECK env variable does not prevent update check
    https://github.com/fastlane/fastlane/issues/10163 [open] 6 💬
    2 weeks ago

and 15 more at: https://github.com/fastlane/fastlane/search?q=execution%20expired&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/kelee/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `initialize': [!] execution expired (Faraday::ConnectionFailed)
	from /Users/kelee/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `open'
	from /Users/kelee/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
	from /Users/kelee/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /Users/kelee/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:902:in `connect'
	from /Users/kelee/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
	from /Users/kelee/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:876:in `start'
	from /Users/kelee/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/faraday-0.13.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:960:in `fetch_access_token'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:998:in `fetch_access_token!'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/googleauth-0.5.3/lib/googleauth/signet.rb:69:in `fetch_access_token!'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/supply/lib/supply/client.rb:63:in `initialize'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/supply/lib/supply/client.rb:36:in `new'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/supply/lib/supply/client.rb:36:in `make_from_config'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/supply/lib/supply/uploader.rb:211:in `client'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/supply/lib/supply/commands_generator.rb:59:in `run'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/supply/lib/supply/commands_generator.rb:12:in `start'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/gems/fastlane-2.58.0/bin/fastlane:20:in `<top (required)>'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kelee/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>']

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.44.1"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build App"
  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end

  desc "Deploy On Staging"
  lane :alpha_staging do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
    update_android_strings(
      xml_path: './app/src/main/res/values/strings.xml',
      block: lambda { |strings|
        strings['reactNativeCodePush_androidDeploymentKey'] = "zzzz"
      }
    )
    sh "cd .. && npm run build-android-staging"
    supply(track: "alpha")
  end

  desc "Deploy On Production"
  lane :alpha_production do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
    update_android_strings(
      xml_path: './app/src/main/res/values/strings.xml',
      block: lambda { |strings|
        strings['reactNativeCodePush_androidDeploymentKey'] = "bbvvvdfbdfbdfb"
      }
    )
    sh "cd .. && npm run build-android-production"
    supply(track: "alpha")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "./fastlaneaccess.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.xxx.yyyy"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.58.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-update_android_strings | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.1.0        |
| executable-hooks                       | 1.3.2        |
| bundler-unload                         | 1.0.2        |
| rubygems-bundler                       | 1.4.4        |
| bundler                                | 1.15.1       |
| io-console                             | 0.4.6        |
| CFPropertyList                         | 2.3.5        |
| public_suffix                          | 2.0.5        |
| addressable                            | 2.5.2        |
| babosa                                 | 1.0.2        |
| colored                                | 1.2          |
| highline                               | 1.7.8        |
| commander-fastlane                     | 4.4.5        |
| dotenv                                 | 2.2.1        |
| excon                                  | 0.59.0       |
| multipart-post                         | 2.0.0        |
| faraday                                | 0.13.1       |
| unf_ext                                | 0.0.7.4      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20170404 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday_middleware                     | 0.12.2       |
| fastimage                              | 2.1.0        |
| gh_inspector                           | 1.0.3        |
| jwt                                    | 1.5.6        |
| little-plugger                         | 1.1.4        |
| multi_json                             | 1.12.2       |
| logging                                | 2.2.2        |
| memoist                                | 0.16.0       |
| os                                     | 0.9.6        |
| signet                                 | 0.7.3        |
| googleauth                             | 0.5.3        |
| httpclient                             | 2.8.3        |
| mime-types-data                        | 3.2016.0521  |
| mime-types                             | 3.1          |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| uber                                   | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.1        |
| google-api-client                      | 0.13.6       |
| json                                   | 2.1.0        |
| mini_magick                            | 4.5.1        |
| multi_xml                              | 0.6.0        |
| plist                                  | 3.3.0        |
| rubyzip                                | 1.2.1        |
| security                               | 0.1.3        |
| slack-notifier                         | 1.5.1        |
| terminal-notifier                      | 1.8.0        |
| unicode-display_width                  | 1.3.0        |
| terminal-table                         | 1.8.0        |
| tty-screen                             | 0.5.0        |
| word_wrap                              | 1.0.0        |
| claide                                 | 1.0.2        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.2.3        |
| xcodeproj                              | 1.5.1        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.2.8        |
| xcpretty-travis-formatter              | 0.0.4        |
| ox                                     | 2.7.0        |
| fastlane-plugin-update_android_strings | 0.1.0        |
</details>

*generated on:* **2017-09-22**
</details>]

**Comment by swl367** [comment]
alright... and it just started working again after an hour
