### ISSUE TITLE
SSL Error Running Gradle on Ubuntu 14.04 CI environment

### ISSUE THREAD

**Issue by sharat** [fastlane/fastlane#10461]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Throws errors on running gradle plugin, when it tries to install latest version of Gradle on (CircleCI) CI server. Installing latest version of openssl did not help (`sudo apt-get install openssl`)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
ubuntu@box1814:~/my-project$ fastlane qc
[13:14:20]: fastlane detected a Gemfile in the current directory
[13:14:20]: however it seems like you don't use `bundle exec`
[13:14:20]: to launch fastlane faster, please use
[13:14:20]:
[13:14:20]: $ bundle exec fastlane qc
[13:14:20]:
[13:14:20]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:14:22]: -------------------------------------------------
[13:14:22]: --- Step: Verifying required fastlane version ---
[13:14:22]: -------------------------------------------------
[13:14:22]: Your fastlane version 2.59.0 matches the minimum requirement of 2.50.0  ✅
[13:14:22]: ------------------------------
[13:14:22]: --- Step: default_platform ---
[13:14:22]: ------------------------------
[13:14:22]: Driving the lane 'android qc' 🚀
[13:14:22]: --------------------
[13:14:22]: --- Step: gradle ---
[13:14:22]: --------------------
[13:14:22]: $ /home/ubuntu/my-project/gradlew assembleQcRelease -p .
[13:14:22]: ▸ Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip
[13:14:23]: ▸ Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
[13:14:23]: ▸ at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
[13:14:23]: ▸ at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1914)
[13:14:23]: ▸ at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1872)
[13:14:23]: ▸ at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1855)
[13:14:23]: ▸ at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1376)
[13:14:23]: ▸ at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1353)
[13:14:23]: ▸ at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[13:14:23]: ▸ at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[13:14:23]: ▸ at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1348)
[13:14:23]: ▸ at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[13:14:23]: ▸ at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
[13:14:23]: ▸ at org.gradle.wrapper.Download.download(Download.java:44)
[13:14:23]: ▸ at org.gradle.wrapper.Install$1.call(Install.java:61)
[13:14:23]: ▸ at org.gradle.wrapper.Install$1.call(Install.java:48)
[13:14:23]: ▸ at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[13:14:23]: ▸ at org.gradle.wrapper.Install.createDist(Install.java:48)
[13:14:23]: ▸ at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[13:14:23]: ▸ at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[13:14:23]: ▸ Caused by: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
[13:14:23]: ▸ at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1024)
[13:14:23]: ▸ at sun.security.pkcs11.P11Key.equals(P11Key.java:158)
[13:14:23]: ▸ at java.util.ArrayList.indexOf(ArrayList.java:298)
[13:14:23]: ▸ at java.util.ArrayList.contains(ArrayList.java:281)
[13:14:23]: ▸ at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:239)
[13:14:23]: ▸ at sun.security.validator.Validator.validate(Validator.java:260)
[13:14:23]: ▸ at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
[13:14:23]: ▸ at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[13:14:23]: ▸ at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
[13:14:23]: ▸ at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1459)
[13:14:23]: ▸ at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
[13:14:23]: ▸ at sun.security.ssl.Handshaker.processLoop(Handshaker.java:961)
[13:14:23]: ▸ at sun.security.ssl.Handshaker.process_record(Handshaker.java:897)
[13:14:23]: ▸ at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1033)
[13:14:23]: ▸ at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
[13:14:23]: ▸ at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1369)
[13:14:23]: ▸ ... 13 more
[13:14:23]: ▸ Caused by: java.security.InvalidKeyException: EC parameters error
[13:14:23]: ▸ at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:284)
[13:14:23]: ▸ at sun.security.ec.ECPublicKeyImpl.<init>(ECPublicKeyImpl.java:59)
[13:14:23]: ▸ at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1021)
[13:14:23]: ▸ ... 28 more
[13:14:23]: ▸ Caused by: java.security.NoSuchProviderException: no such provider: SunEC
[13:14:23]: ▸ at sun.security.jca.GetInstance.getService(GetInstance.java:83)
[13:14:23]: ▸ at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
[13:14:23]: ▸ at java.security.Security.getImpl(Security.java:697)
[13:14:23]: ▸ at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:199)
[13:14:23]: ▸ at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:279)
[13:14:23]: ▸ ... 30 more
+------------------+------------+
|         Lane Context          |
+------------------+------------+
| DEFAULT_PLATFORM | android    |
| PLATFORM_NAME    | android    |
| LANE_NAME        | android qc |
+------------------+------------+
[13:14:23]: Exit status of command '/home/ubuntu/my-project/gradlew assembleQcRelease -p .' was 1 instead of 0.
Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip

Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1914)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1872)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1855)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1376)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1353)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1348)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
        at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1024)
        at sun.security.pkcs11.P11Key.equals(P11Key.java:158)
        at java.util.ArrayList.indexOf(ArrayList.java:298)
        at java.util.ArrayList.contains(ArrayList.java:281)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:239)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1459)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:961)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:897)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1033)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1369)
        ... 13 more
Caused by: java.security.InvalidKeyException: EC parameters error
        at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:284)
        at sun.security.ec.ECPublicKeyImpl.<init>(ECPublicKeyImpl.java:59)
        at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1021)
        ... 28 more
Caused by: java.security.NoSuchProviderException: no such provider: SunEC
        at sun.security.jca.GetInstance.getService(GetInstance.java:83)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
        at java.security.Security.getImpl(Security.java:697)
        at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:199)
        at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:279)
        ... 30 more


+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | gradle                              | 0           |
+------+-------------------------------------+-------------+

[13:14:23]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!': [!] Exit status of command '/home/ubuntu/my-project/gradlew assembleQcRelease -p .' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip

Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1914)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1872)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1855)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1376)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1353)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1348)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
        at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1024)
        at sun.security.pkcs11.P11Key.equals(P11Key.java:158)
        at java.util.ArrayList.indexOf(ArrayList.java:298)
        at java.util.ArrayList.contains(ArrayList.java:281)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:239)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1459)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:961)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:897)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1033)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1369)
        ... 13 more
Caused by: java.security.InvalidKeyException: EC parameters error
        at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:284)
        at sun.security.ec.ECPublicKeyImpl.<init>(ECPublicKeyImpl.java:59)
        at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1021)
        ... 28 more
Caused by: java.security.NoSuchProviderException: no such provider: SunEC
        at sun.security.jca.GetInstance.getService(GetInstance.java:83)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
        at java.security.Security.getImpl(Security.java:697)
        at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:199)
        at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:279)
        ... 30 more

        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `sh_control_output'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/action.rb:98:in `sh'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/actions/gradle.rb:49:in `run'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:43:in `block (2 levels) in parsing_binding'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/gems/fastlane-2.59.0/bin/fastlane:20:in `<top (required)>'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
        from /opt/circleci/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
```

**Comment by sharat** [comment]
This is an interesting issue, and not really related to Fastlane. Initially, I thought if it's an [SSL error mentioned in the FAQ](https://docs.fastlane.tools/faqs/#im-getting-an-ssl-error). threads like [this](https://github.com/travis-ci/travis-ci/issues/8503), [this](https://github.com/facebook/react-native/issues/14091) and [this](https://github.com/facebook/react-native/issues/11697) helped me to narrow down OpenJDK7 issue with SSL in Ubuntu Trusty environment.

Just change to JDK 8 🚀  will fix the issue.
