### ISSUE TITLE
install_xcode_plugin fails with "cannot create extraction directory"

### ISSUE THREAD

**Issue by anton-matosov** [fastlane/fastlane#1048]
While running:
```
install_xcode_plugin(
    url: "https://github.com/fastlane/FixCode/releases/download/0.2.0/FixCode.xcplugin.zip"
  )
```

I get error:
```
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/helper/sh_helper.rb:40:in `sh_no_action': Exit status of command 'unzip -qo '/var/folders/wh/dn2x2bkx6clgd8wfhn6qmrdw00007h/T/plugin.zip' -d '/Users/Shared/Jenkins/Library/Application Support/Developer/Shared/Xcode/Plug-ins'' was 2 instead of 0. (RuntimeError)
checkdir:  cannot create extraction directory: /Users/Shared/Jenkins/Library/Application Support/Developer/Shared/Xcode/Plug-ins

	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/action.rb:67:in `sh'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/actions/install_xcode_plugin.rb:7:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/runner.rb:127:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:135:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/bin/fastlane:37:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/bin/fastlane:155:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.49.0/bin/fastlane:161:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by anton-matosov** [comment]
Running
```
mkdir -p "/Users/Shared/Jenkins/Library/Application Support/Developer/Shared/Xcode/Plug-ins"
```
Fixed the problem.
That means that install_xcode_plugin doesn't try to recreate the full path to Plug-ins directory, which doesn't exit by default

**Comment by KrauseFx** [comment]
Thanks, I just pushed a fix, this will be in the next release :+1:
