### ISSUE TITLE
Snapshot unsupported screen size for iPhone2017-C

### ISSUE THREAD

**Issue by AdrianBinDC** [fastlane/fastlane#10582]
### Issue Description

Snapshot generates incorrect screen shot size for iPhone2017-C

##### Complete output when running fastlane, including the stack trace and command used

> [!] Unsupported screen size [1125, 2436] for path './fastlane/screenshots/en-US/iPhone2017-C-01-mainScreen.png'

**Comment by SeanRobinson159** [comment]
That is not an incorrect screen size. That is the resolution of the iPhone2017-C (iPhone X). 
https://www.apple.com/iphone-x/specs/

iTunes connect doesn't currently support iPhone X screenshots. 

A simple fix is to remove that simulator from your devices array in your Snapfile.
OR
You could delete the iPhone2017-C simulator from your simulators list in Xcode.
Open Xcode > Window > Devices and Simulators
- click the Simulators tab 
- find the iPhone2017-C in the list on the left side
- right click and delete.

Then the next time you run Snapshot, it won't use that device to take screenshots.

**Comment by adellibovi** [comment]
Related to #10501

**Comment by SeanRobinson159** [comment]
iTunes connect now supports iPhone X screenshots. As of October 27. 

https://itunespartner.apple.com/en/apps/news/5993372

Snapshot should now be able to upload iPhone X screenshots without errors.

**Comment by Domsware** [comment]
Snapshot produce screenshots with correct size for iPhone X.
Deliver produce an error with these screenshots:
`[!] Unsupported screen size [1125, 2436] for path './fastlane/screenshots/en-US/iPhone X-01-home.png'`

**Comment by stefanwichmann** [comment]
I also get this error for iPhone X screen sizes.

Has anyone managed to successfully upload screenshots with the given resolution? Does the target have to be iOS 11.1?

**Comment by Kaspik** [comment]
Still getting this error with new fastlane update.

**Comment by ohayon** [comment]
Hi folks! Would you mind sharing the entire output from your command line so we can have as much context as possible? Running with `--verbose` would be extra helpful!

**Comment by Kaspik** [comment]
Sure @ohayon :)

```

+-------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
|                                                                         deliver 2.63.0 Summary                                                                          |
+-------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| skip_binary_upload                                          | true                                                                                                      |
| skip_screenshots                                            | false                                                                                                     |
| skip_metadata                                               | true                                                                                                      |
| submit_for_review                                           | false                                                                                                     |
| app_identifier                                              | xxxxxx                                                                                             |
| release_notes.en-US                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.da                                            | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.de-DE                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.el                                            | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.en-AU                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.en-CA                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.en-GB                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.es-ES                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.es-MX                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.fr-CA                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.fr-FR                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.it                                            | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.id                                            | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.nl-NL                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.no                                            | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.pt-PT                                         | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.ru                                            | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.tr                                            | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.zh-Hant                                       | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| release_notes.ko                                            | We fixed a few bugs and improved the performance of the app in this update! More things still to come :)  |
| screenshots_path                                            | ./fastlane/screenshots/                                                                                   |
| submission_information.add_id_info_uses_idfa                | false                                                                                                     |
| submission_information.export_compliance_uses_encryption    | false                                                                                                     |
| submission_information.export_compliance_encryption_updated | false                                                                                                     |
| metadata_path                                               | ./fastlane/metadata                                                                                       |
| username                                                    | xxxxxxxxxxx                                                                                         |
| edit_live                                                   | false                                                                                                     |
| platform                                                    | ios                                                                                                       |
| skip_app_version_update                                     | false                                                                                                     |
| force                                                       | false                                                                                                     |
| automatic_release                                           | false                                                                                                     |
| dev_portal_team_id                                          | xxxxxx                                                                                                |
| overwrite_screenshots                                       | false                                                                                                     |
| run_precheck_before_submit                                  | true                                                                                                      |
| precheck_default_rule_level                                 | warn                                                                                                      |
| ignore_language_directory_validation                        | false                                                                                                     |
+-------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

INFO [2017-11-01 09:16:48.46]: -----------------------------------
INFO [2017-11-01 09:16:48.46]: --- Step: clean_build_artifacts ---
INFO [2017-11-01 09:16:48.46]: -----------------------------------
INFO [2017-11-01 09:16:48.46]: Cleaned up build artifacts 🐙
INFO [2017-11-01 09:16:48.49]: --------------------------
INFO [2017-11-01 09:16:48.49]: --- Step: notification ---
INFO [2017-11-01 09:16:48.49]: --------------------------
WARN [2017-11-01 09:16:48.71]: Lane Context:
INFO [2017-11-01 09:16:48.71]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios update_screenshots"}
ERROR [2017-11-01 09:16:48.71]: Unsupported screen size [1125, 2436] for path './fastlane/screenshots/iMessage/en-US/1_iphone58_1.Simulator Screen Shot - iPhone X - 2017-10-30 at 10.28.51.png'
INFO [2017-11-01 09:16:48.71]: Successfully generated documentation at path '/Users/kaspik/Documents/Vyvoj/STRV/ClassDojo/dojo-behavior/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | default_platform                    | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | Switch to ios update_app_info lane  | 0           |
| 💥   | deliver                             | 7           |
| 5    | clean_build_artifacts               | 0           |
| 6    | notification                        | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-11-01 09:16:48.71]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Unsupported screen size [1125, 2436] for path './fastlane/screenshots/iMessage/en-US/1_iphone58_1.Simulator Screen Shot - iPhone X - 2017-10-30 at 10.28.51.png' (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/app_screenshot.rb:232:in `calculate_screen_size'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/app_screenshot.rb:57:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:117:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:117:in `block (2 levels) in collect_screenshots_for_languages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:108:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:108:in `block in collect_screenshots_for_languages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:84:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:84:in `collect_screenshots_for_languages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:89:in `block in collect_screenshots_for_languages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:84:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:84:in `collect_screenshots_for_languages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/upload_screenshots.rb:73:in `collect_screenshots'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/runner.rb:95:in `upload_metadata'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/deliver/lib/deliver/runner.rb:25:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/actions/deliver.rb:16:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:253:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:228:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.63.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by ohayon** [comment]
Thanks @Kaspik - one more question: could you share the code you are using to call deliver? Are you calling from the command line or using a Fastfile?

**Comment by Kaspik** [comment]
@ohayon 
`Fastfile` - terminal `fastlane update_screenshots`

```
lane :update_screenshots do |options|
    update_app_info(skip_screenshots: false, skip_metadata: true)
  end
```
```
private_lane :update_app_info do |options|

    skip_screenshots = options[:skip_screenshots]
    skip_metadata = options[:skip_metadata]

    # Upload the build to iTunes Connect.
    deliver(
      skip_binary_upload: true,
      skip_screenshots: skip_screenshots,
      skip_metadata: skip_metadata,
      submit_for_review: false
    )
  end
```

**Comment by ohayon** [comment]
We just merged a change that should hopefully help this out! Would you mind running off master? Or, we will likely push another release out this week if you can hold tight? 😄  🚀

**Comment by Kaspik** [comment]
Thank you, I'll wait. 😄

**Comment by Kaspik** [comment]
Looks good and fixed, can be closed.

**Comment by taquitos** [comment]
🎉
