### ISSUE TITLE
Xcode9 GM，fastlane 2.61.0, I need help, thanks.

### ISSUE THREAD

**Issue by yfldj** [fastlane/fastlane#10618]
Xcode9 GM，fastlane 2.61.0, I need help, thanks.

[22:02:28]: Uploading metadata to iTunes Connect
[22:02:32]: [32mSuccessfully uploaded set of metadata to iTunes Connect[0m
[22:02:41]: Uploading binary to iTunes Connect
[22:02:42]: Going to upload updated app to iTunes Connect
[22:02:42]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
[22:03:59]: [31m[Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[0m
[22:03:59]: [31mTransporter transfer failed.[0m
[22:03:59]: 
[22:03:59]: [31mCould not start delivery: all transports failed diagnostics
[0m
[22:03:59]: [33m[iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine.access$1200(TransferEngine.java:149)
[0m
[22:03:59]: [33m[iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$8.run(TransferEngine.java:4060)
[0m
[22:03:59]: [33m[iTMSTransporter] 
[0m
[22:03:59]: [33m[iTMSTransporter] [2017-10-17 22:03:59 CST] <Transport Protocol> DEBUG: Received failed transfer notification; aborting
[0m
[22:03:59]: [33m[iTMSTransporter] [2017-10-17 22:03:59 CST] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED
[0m
[22:03:59]: [33m[iTMSTransporter] [2017-10-17 22:03:59 CST] <main> ERROR: Could not start delivery: all transports failed diagnostics
[0m
[22:03:59]: [33m[iTMSTransporter] 
[0m
[22:03:59]: [33m[iTMSTransporter] 
[0m
[22:03:59]: [33m[iTMSTransporter] 
[0m
[22:03:59]: [33m[iTMSTransporter] Package Summary:
[0m
[22:03:59]: [33m[iTMSTransporter]  
[0m
[22:03:59]: [33m[iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[0m
[22:03:59]: [33m[iTMSTransporter] 	/tmp/509256354.itmsp - Error Messages:
[0m
[22:03:59]: [33m[iTMSTransporter] 		Could not start delivery: all transports failed diagnostics
[0m
[22:03:59]: [33m[iTMSTransporter] [2017-10-17 22:03:59 CST] <main> DBG-X: Returning 1
[0m
[22:03:59]: iTunes Transporter output above ^
[22:03:59]: [31mCould not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure

**Comment by mpirri** [comment]
@yfldj Had you previously had this working with another version of Xcode or _fastlane_? Just trying to understand if this might be related to either the new Xcode version or that particular version of _fastlane_.

Thanks for writing in!  🚀

**Comment by antonino-u** [comment]
I have the same problem on fastlane 2.62.0. Same version of Xcode too!

**Comment by mpirri** [comment]
@antonino-u Great advice!  More on this approach is documented in [this issue](https://github.com/fastlane-old/deliver/issues/235). 🚀

**Comment by yfldj** [comment]
@antonino-u Yes! Had fixed the issue, thank you.
