### ISSUE TITLE
fastlane init error 

### ISSUE THREAD

**Issue by sunforcode** [fastlane/fastlane#10678]
error message:
/Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:379:in `block in inflate_adapter': stack level too deep (SystemStackError)
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:411:in `call_block'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:402:in `<<'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:102:in `read'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:401:in `read'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:290:in `block in read_body_0'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:261:in `inflater'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:280:in `read_body_0'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
	 ... 8723 levels...
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/CharlyZhang/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.0/bin/fastlane:20:in `<top (required)>'
	from /Users/CharlyZhang/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/CharlyZhang/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by sunforcode** [comment]
no use

**Comment by sunforcode** [comment]
fresh
