### ISSUE TITLE
Fastlane 2.62.1 syntax error, unexpected keyword_end, expecting end-of-input

### ISSUE THREAD

**Issue by hexagonstar** [fastlane/fastlane#10698]
Fastlane fails since recently with following errors:

```
/Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/credentials_manager/lib/credentials_manager/appfile_config.rb:44:in `eval': (eval):8: syntax error, unexpected keyword_end, expecting end-of-input (SyntaxError)
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/credentials_manager/lib/credentials_manager/appfile_config.rb:44:in `block in initialize'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/credentials_manager/lib/credentials_manager/appfile_config.rb:32:in `chdir'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/credentials_manager/lib/credentials_manager/appfile_config.rb:32:in `initialize'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/credentials_manager/lib/credentials_manager/appfile_config.rb:8:in `new'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/credentials_manager/lib/credentials_manager/appfile_config.rb:8:in `try_fetch_value'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:33:in `guess_package_name_from_appfile'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:68:in `guess_package_name'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:56:in `android_app_identifier'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:16:in `initialize'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:18:in `new'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/analytics/action_launch_context.rb:18:in `context_for_action_name'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:63:in `run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/bin/fastlane:20:in `<top (required)>'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

Appfile looks like this:

```
app_identifier "jp.co.*******.************"
apple_id "******.******@******.com"
team_id "273T3T1CK5"

for_lane :build_appstore
  app_identifier 'jp.co.*******.************'
  team_id "273T3T1CK5"
end

for_lane :build_dev_prd
  app_identifier 'jp.co.*******.************.production'
  team_id "273T3T1CK5"
end

for_lane :build_dev_stg
  app_identifier 'jp.co.*******.************.staging'
  team_id "273T3T1CK5"
end

for_lane :build_dist_prd
  app_identifier 'jp.co.*******.************.enterprise.production'
  team_id "5J3GVEN56B"
end

for_lane :build_dist_stg
  app_identifier 'jp.co.*******.************.enterprise.staging'
  team_id "5J3GVEN56B"
end
```

It was running fine just a few days before. all that changed is that Fastlane was updated to newest version. Please help! Our Jenkins server builds depend on this!

Can't include the output of 'fastlane env' since that causes the same error.

**Comment by ohayon** [comment]
Hey @hexagonstar - is it possible this file changed at all? I believe that you need to have a `do` after each of those `for_lane :lane_name` lines, i.e: 
```
for_lane :lane_name do
  thing_to_do....
end
```

Could you let us know if that helps?

**Comment by hexagonstar** [comment]
@ohayon Thanks for the hint! That fixed it! It's strange though as it was working fine so far and I never added the 'do's before.

**Comment by ohayon** [comment]
Hmmm that is very strange! Glad that you are back up and running! 🚀
