### ISSUE TITLE
Fastlane init error

### ISSUE THREAD

**Issue by emreozdil** [fastlane/fastlane#10838]
[14:49:50]: Starting login with user 'xxx@xxx.xx'
(eval):3:in `to_nfc': stack level too deep (SystemStackError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/domain_name-0.5.20170404/lib/domain_name.rb:289:in `normalize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/domain_name-0.5.20170404/lib/domain_name.rb:100:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/domain_name-0.5.20170404/lib/domain_name.rb:180:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/domain_name-0.5.20170404/lib/domain_name.rb:180:in `<=>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/domain_name-0.5.20170404/lib/domain_name.rb:218:in `<='
	from /usr/local/lib/ruby/gems/2.4.0/gems/domain_name-0.5.20170404/lib/domain_name.rb:163:in `cookie_domain?'
	from /usr/local/lib/ruby/gems/2.4.0/gems/http-cookie-1.0.3/lib/http/cookie.rb:560:in `acceptable_from_uri?'
	from /usr/local/lib/ruby/gems/2.4.0/gems/http-cookie-1.0.3/lib/http/cookie.rb:591:in `valid_for_uri?'
	 ... 10909 levels...
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.64.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.64.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.59.0       |
| openssl                   | 2.0.3        |
| faraday                   | 0.13.1       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
</details>

*generated on:* **2017-11-08**
</details>

**Comment by emreozdil** [comment]
Write the terminal
`fastlane spaceship`
then `fastlane init` run properly
