### ISSUE TITLE
Pilot crashes when iTunesConnect account has insufficient permissions

### ISSUE THREAD

**Issue by arodus** [fastlane/fastlane#10852]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running pilot with an account without proper permissions. Fastlane is crashing with the message:
```
  [22:19:06]: fastlane finished with errors
/Users/redacted/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:379:in `inflate': stack level too deep (SystemStackError)
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:379:in `block in inflate_adapter'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:411:in `call_block'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:402:in `<<'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:106:in `read'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:401:in `read'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:290:in `block in read_body_0'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:261:in `inflater'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:280:in `read_body_0'
	 ... 8722 levels...
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/bin/fastlane:20:in `<top (required)>'
	from /Users/redacted/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/redacted/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```
When manually canceling the execution the following output is shown:
```
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:641:in `raise_insuffient_permission_error!'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:625:in `detect_most_common_errors_and_raise_exceptions'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:598:in `parse_response'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:185:in `user_details_data'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:130:in `teams'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:192:in `team_id'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:641:in `raise_insuffient_permission_error!'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:625:in `detect_most_common_errors_and_raise_exceptions'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:598:in `parse_response'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:185:in `user_details_data'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:130:in `teams'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:192:in `team_id'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:641:in `raise_insuffient_permission_error!'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:625:in `detect_most_common_errors_and_raise_exceptions'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:598:in `parse_response'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:185:in `user_details_data'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:130:in `teams'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:192:in `team_id'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:641:in `raise_insuffient_permission_error!'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:625:in `detect_most_common_errors_and_raise_exceptions'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:598:in `parse_response'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:185:in `user_details_data'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:130:in `teams'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:192:in `team_id'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:641:in `raise_insuffient_permission_error!'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:625:in `detect_most_common_errors_and_raise_exceptions'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:598:in `parse_response'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:185:in `user_details_data'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:130:in `teams'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:192:in `team_id'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:641:in `raise_insuffient_permission_error!'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:625:in `detect_most_common_errors_and_raise_exceptions'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:598:in `parse_response'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:185:in `user_details_data'
	from /Users/redacted/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.0/spaceship/lib/spaceship/client.rb:130:in `teams'
```

```
## fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>
```

**Comment by joshdholtz** [comment]
@Arodus This is interesting! What permissions does your account have so I can try to replicate this? 😇

**Comment by Arodus** [comment]
@joshdholtz At this point the Account was just registered in the Apple AppStore but didn't had access to iTunesConnect at all.

**Comment by taquitos** [comment]
Should be resolved when we merge: https://github.com/fastlane/fastlane/pull/10899 🎉
