### ISSUE TITLE
XCodeServer trigger cannot find bundle command

### ISSUE THREAD

**Issue by Cyclic** [fastlane/fastlane#1093]
When running XCode server builds, we receive an error that popen cannot find the 'bundle' gem. The bundler gem is right next to the fastlane gem though, and I have confirmed that the trigger is using ruby 2.0. Is there an additional line required in the trigger script or am I missing something really simple here? Here is the trigger script now:
```
export LC_ALL="en_US.UTF-8"
cd ./someapp
export PATH="/Users/_xcsbuildd/.rvm/rubies/default/bin:$PATH"
source ~/.bash_profile
source ~/.rvm/scripts/rvm
sudo gem list >> "../GEMS.txt"
sudo ruby --version >> "../RUBY.txt"
/usr/local/bin/fastlane ios alpha
```
IO.popen(command, err: [:child, :out]) do
https://github.com/fastlane/fastlane/blob/master/lib/fastlane/helper/sh_helper.rb#L26

```
Assertion: Trigger script exited with code: 1 /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/helper/sh_helper.rb:26:in `popen': No such file or directory - bundle (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/helper/sh_helper.rb:26:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/actions/cocoapods.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:34:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/runner.rb:49:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/bin/fastlane:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/bin/fastlane:155:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.50.0/bin/fastlane:161:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by vpolouchkine** [comment]
Check out this tutorial: https://honzadvorsky.com/articles/2015-08-17-17-30-xcode_server_tutorials_3_prebuild__postbuild_scripts/

**Comment by Cyclic** [comment]
@vpolouchkine Thank, sir! This at the top of the trigger did the trick:
export PATH="/usr/local/bin:$PATH"  :rocket:
