### ISSUE TITLE
Unable to upload Android APKs to crashlytics Beta using a Docker Fastlane Image

### ISSUE THREAD

**Issue by phaniteja** [fastlane/fastlane#10951]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
**Unable to upload Android APKs to crashlytics Beta using a Docker Fastlane Image.** 
##### Complete output when running fastlane, including the stack trace and command used

**root@afd062352536:/tmp/fastlaneTemporary# fastlane upload --verbose
/var/lib/gems/2.1.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/usr/lib/ruby/2.1.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[11:40:07]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-11-20 11:40:09.91]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
ERROR [2017-11-20 11:40:09.91]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
INFO [2017-11-20 11:40:09.92]: -------------------------------------------------
INFO [2017-11-20 11:40:09.92]: --- Step: Verifying required fastlane version ---
INFO [2017-11-20 11:40:09.92]: -------------------------------------------------
INFO [2017-11-20 11:40:09.92]: Your fastlane version 2.64.1 matches the minimum requirement of 1.109.0  ✅
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
INFO [2017-11-20 11:40:09.92]: ------------------------------
INFO [2017-11-20 11:40:09.92]: --- Step: default_platform ---
INFO [2017-11-20 11:40:09.92]: ------------------------------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
INFO [2017-11-20 11:40:09.92]: Driving the lane 'upload' 🚀
INFO [2017-11-20 11:40:09.92]: ------------------------------------
INFO [2017-11-20 11:40:09.92]: --- Step: Switch to flavor1 lane ---
INFO [2017-11-20 11:40:09.92]: ------------------------------------
INFO [2017-11-20 11:40:09.92]: Cruising over to lane 'flavor1' 🚖
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
INFO [2017-11-20 11:40:09.92]: -------------------------
INFO [2017-11-20 11:40:09.92]: --- Step: crashlytics ---
INFO [2017-11-20 11:40:09.92]: -------------------------
INFO [2017-11-20 11:40:09.92]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2017-11-20 11:40:09.92]: java -jar /tmp/fastlaneTemporary/crashlytics-devtools-1.0.jar -androidRes . -apiKey [[API_TOKEN]] -apiSecret [[BUILD_SECRET]] -uploadDist '/tmp/fastlaneTemporary/Flavor1_Android_v7.0.0-SNAPSHOT.apk' -androidManifest '/tmp/xml20171120-49-xxpvkf' -betaDistributionNotifications true
ERROR [2017-11-20 11:46:32.32]: Shell command exited with exit status 1 instead of 0.
ERROR [2017-11-20 11:46:32.37]: Unable to send the crash report.
ERROR [2017-11-20 11:46:32.37]: Please open an issue on GitHub if you need help!
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
WARN [2017-11-20 11:46:32.37]: Lane Context:
INFO [2017-11-20 11:46:32.37]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>nil, :LANE_NAME=>"upload"}
ERROR [2017-11-20 11:46:32.37]:  WARN - Crashlytics had a problem uploading the distribution.
org.apache.http.conn.HttpHostConnectException: Connect to distribution-uploads.crashlytics.com:443 [distribution-uploads.crashlytics.com/54.235.107.91, distribution-uploads.crashlytics.com/54.243.118.164, distribution-uploads.crashlytics.com/54.235.82.47] failed: Connection timed out (Connection timed out)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.crashlytics.api.RestfulWebApi.request(RestfulWebApi.java:143)
        at com.crashlytics.api.RestfulWebApi.request(RestfulWebApi.java:131)
        at com.crashlytics.api.RestfulWebApi.createDistribution(RestfulWebApi.java:1042)
        at com.crashlytics.api.ota.DistributionController.uploadDistribution(DistributionController.java:113)
        at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:71)
        at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
        at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
        at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:251)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
        ... 18 more
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
        at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
        at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
        at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it had a problem uploading the distribution.Please check network connectivity and try again.
        at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:95)
        at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
        ... 2 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to distribution-uploads.crashlytics.com:443 [distribution-uploads.crashlytics.com/54.235.107.91, distribution-uploads.crashlytics.com/54.243.118.164, distribution-uploads.crashlytics.com/54.235.82.47] failed: Connection timed out (Connection timed out)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.crashlytics.api.RestfulWebApi.request(RestfulWebApi.java:143)
        at com.crashlytics.api.RestfulWebApi.request(RestfulWebApi.java:131)
        at com.crashlytics.api.RestfulWebApi.createDistribution(RestfulWebApi.java:1042)
        at com.crashlytics.api.ota.DistributionController.uploadDistribution(DistributionController.java:113)
        at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:71)
        ... 3 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:251)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
        ... 18 more

INFO [2017-11-20 11:46:32.37]: Successfully generated documentation at path '/tmp/fastlaneTemporary/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | Switch to flavor1 lane              | 0           |
| 💥   | crashlytics                         | 382         |
+------+-------------------------------------+-------------+

ERROR [2017-11-20 11:46:32.39]: fastlane finished with errors
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/tmp/fastlaneTemporary/fastlane/Appfile'
-------
ERROR [2017-11-20 11:46:32.43]: Unable to send the crash report.
ERROR [2017-11-20 11:46:32.43]: Please open an issue on GitHub if you need help!
/var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!]  WARN - Crashlytics had a problem uploading the distribution. (FastlaneCore::Interface::FastlaneError)
org.apache.http.conn.HttpHostConnectException: Connect to distribution-uploads.crashlytics.com:443 [distribution-uploads.crashlytics.com/54.235.107.91, distribution-uploads.crashlytics.com/54.243.118.164, distribution-uploads.crashlytics.com/54.235.82.47] failed: Connection timed out (Connection timed out)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.crashlytics.api.RestfulWebApi.request(RestfulWebApi.java:143)
        at com.crashlytics.api.RestfulWebApi.request(RestfulWebApi.java:131)
        at com.crashlytics.api.RestfulWebApi.createDistribution(RestfulWebApi.java:1042)
        at com.crashlytics.api.ota.DistributionController.uploadDistribution(DistributionController.java:113)
        at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:71)
        at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
        at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
        at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:251)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
        ... 18 more
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
        at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
        at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
        at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it had a problem uploading the distribution.Please check network connectivity and try again.
        at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:95)
        at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
        ... 2 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to distribution-uploads.crashlytics.com:443 [distribution-uploads.crashlytics.com/54.235.107.91, distribution-uploads.crashlytics.com/54.243.118.164, distribution-uploads.crashlytics.com/54.235.82.47] failed: Connection timed out (Connection timed out)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.crashlytics.api.RestfulWebApi.request(RestfulWebApi.java:143)
        at com.crashlytics.api.RestfulWebApi.request(RestfulWebApi.java:131)
        at com.crashlytics.api.RestfulWebApi.createDistribution(RestfulWebApi.java:1042)
        at com.crashlytics.api.ota.DistributionController.uploadDistribution(DistributionController.java:113)
        at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:71)
        ... 3 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:251)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
        ... 18 more

        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/crashlytics.rb:42:in `block in run'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `call'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/crashlytics.rb:45:in `run'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:21:in `block in parsing_binding'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:43:in `block in parsing_binding'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
        from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
        from /var/lib/gems/2.1.0/gems/fastlane-2.64.1/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'**

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]
root@afd062352536:/tmp/fastlaneTemporary# fastlane env
/var/lib/gems/2.1.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/usr/lib/ruby/2.1.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[12:53:42]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:53:44]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                            |
| --------------------------- | ---------------------------------------------------------------- |
| OS                          | debian_based 8.7                                                 |
| Ruby                        | 2.1.5                                                            |
| Bundler?                    | false                                                            |
| Git                         | git version 2.1.4                                                |
| Installation Source         | /usr/local/bin/fastlane                                          |
| Host                        | Debian GNU/Linux 8 debian_based 8.7 (3.10.0-514.21.1.el7.x86_64) |
| Ruby Lib Dir                | /usr/lib                                                         |
| OpenSSL Version             | OpenSSL 1.0.1t  3 May 2016                                       |
| Is contained                | false                                                            |
| Is homebrew                 | false                                                            |
| Is installed via Fabric.app | false                                                            |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "c39a2c31-1795-4d76-a1a9-190f7cb016c4"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :flavor1 do
  # build the release variant

  # upload to Beta by Crashlytics
    crashlytics(
    crashlytics_path: "./crashlytics-devtools-1.0.jar",
    api_token: "token",
    build_secret: "secret",
    apk_path: "./Flavor1_Android_v7.0.0-SNAPSHOT.apk"
  )
end
lane :flavor2 do
  # build the release variant

  # upload to Beta by Crashlytics
    crashlytics(
    crashlytics_path: "./crashlytics-devtools-1.0.jar",
    api_token: "token",
    build_secret: "secret",
    apk_path: "./Flavor2_Android_v7.0.0-SNAPSHOT.apk"
  )
end
#here i have added individual lanes so that they will run sequentially
  desc "upload to crashlytics”
  lane :upload do
  flavor1
  flavor2
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf                       | 0.2.0.beta2  |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.2        |
</details>

*generated on:* **2017-11-20**
</details>

**Comment by teja99** [comment]
I had used the JAVA_TOOL_OPTIONS environment vriable for setting the proxy to get this working.

**Comment by phaniteja** [comment]
I had used the JAVA_TOOL_OPTIONS environment variable for setting the proxy to get this working.
