### ISSUE TITLE
download_dsyms Platform not passing down To new TestFlight API

### ISSUE THREAD

**Issue by bassrock** [fastlane/fastlane#10957]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After upgrading to the recently released Fastlane this morning that uses the new TestFlight API, I decided to refresh my DSYMS. It looks like with the new api the platform parameter is not getting passed down from the download_dsyms command.

### Stack trace

```
 bundler: failed to load command: fastlane (/Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/bin/fastlane)
NameError: [!] `platform' is a required parameter
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/spaceship/lib/spaceship/test_flight/client.rb:288:in `block in assert_required_params'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/spaceship/lib/spaceship/test_flight/client.rb:286:in `each'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/spaceship/lib/spaceship/test_flight/client.rb:286:in `assert_required_params'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/spaceship/lib/spaceship/test_flight/client.rb:24:in `get_build_trains'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/spaceship/lib/spaceship/test_flight/build_trains.rb:13:in `all'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/spaceship/lib/spaceship/tunes/application.rb:264:in `build_trains'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/spaceship/lib/spaceship/tunes/application.rb:270:in `all_build_train_numbers'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/actions/download_dsyms.rb:53:in `run'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:160:in `block (2 levels) in parsing_binding'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/gems/fastlane-2.65.0/bin/fastlane:20:in `<top (required)>'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/bin/fastlane:22:in `load'
  /Users/daniel/Work/TestCompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/bin/fastlane:22:in `<top (required)>'
```

### Captured Output

Command Used: `refresh_dsyms`
<details><summary>Output/Log</summary>

```

DEBUG [2017-11-20 09:38:18.59]: Checking if there are any plugins that should be loaded...
DEBUG [2017-11-20 09:38:18.59]: Loading 'fastlane-plugin-appicon' plugin
INFO [2017-11-20 09:38:18.63]: gem 'fastlane-plugin-appicon' is already installed
+------------------------+---------+------------------+
|                    Used plugins                     |
+------------------------+---------+------------------+
| Plugin                 | Version | Action           |
+------------------------+---------+------------------+
| fastlane-plugin-appic  | 0.10.0  | android_appicon  |
| on                     |         | appicon          |
+------------------------+---------+------------------+

Successfully loaded Appfile at path '/Users/daniel/Work/testcompany/CoolApp/CoolAppiOS/fastlane/Appfile'
- app_identifier: 'com.test.CoolApp'
- apple_id: 'test@test.com'
-------
INFO [2017-11-20 09:38:18.98]: -------------------------------------------------
INFO [2017-11-20 09:38:18.98]: --- Step: Verifying required fastlane version ---
INFO [2017-11-20 09:38:18.98]: -------------------------------------------------
INFO [2017-11-20 09:38:18.98]: Your fastlane version 2.65.0 matches the minimum requirement of 1.5.0  ✅
INFO [2017-11-20 09:38:19.02]: ------------------------------
INFO [2017-11-20 09:38:19.02]: --- Step: default_platform ---
INFO [2017-11-20 09:38:19.02]: ------------------------------
INFO [2017-11-20 09:38:19.02]: Driving the lane 'ios refresh_dsyms' 🚀
INFO [2017-11-20 09:38:19.06]: -------------------
INFO [2017-11-20 09:38:19.06]: --- Step: is_ci ---
INFO [2017-11-20 09:38:19.06]: -------------------
INFO [2017-11-20 09:38:19.09]: ----------------------------
INFO [2017-11-20 09:38:19.09]: --- Step: download_dsyms ---
INFO [2017-11-20 09:38:19.09]: ----------------------------
INFO [2017-11-20 09:38:19.09]: Login to iTunes Connect (test@test.com)
Loading session from '/Users/daniel/.fastlane/spaceship/test@test.com/cookie'
Looking for iTunes Connect Team with ID 239758
INFO [2017-11-20 09:38:20.99]: Login successful
INFO [2017-11-20 09:38:21.68]: Looking for dSYM files for com.test.CoolApp
WARN [2017-11-20 09:38:22.14]: Lane Context:
INFO [2017-11-20 09:38:22.14]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios refresh_dsyms"}
ERROR [2017-11-20 09:38:22.14]: `platform' is a required parameter
INFO [2017-11-20 09:38:22.14]: Successfully generated documentation at path '/Users/daniel/Work/testcompany/CoolApp/CoolAppiOS/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | is_ci               | 0           |
| 💥   | download_dsyms      | 2           |
+------+---------------------+-------------+

DEBUG [2017-11-20 09:38:22.15]: All plugins are up to date
ERROR [2017-11-20 09:38:22.15]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: `platform' is a required parameter

URL: https://api.github.com/search/issues?q=%60platform'%20is%20a%20required%20parameter+repo:fastlane/fastlane
➡️  Parameters are ignored
    https://github.com/fastlane/fastlane/issues/10667 [open] 3 💬
    4 weeks ago

➡️  latest_testflight_build_number return incorrect build number & crash when live_version parameter is true
    https://github.com/fastlane/fastlane/issues/10923 [open] 9 💬
    14 hours ago

➡️  "You passed invalid parameters to 'resign'" when resign
    https://github.com/fastlane/fastlane/issues/10737 [open] 3 💬
    3 weeks ago

and 359 more at: https://github.com/fastlane/fastlane/search?q=%60platform%27%20is%20a%20required%20parameter&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2017-11-20 09:38:22.81]: All plugins are up to date


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                      |
| --------------------------- | ------------------------------------------------------------------------------------------ |
| OS                          | 10.13.1                                                                                    |
| Ruby                        | 2.4.0                                                                                      |
| Bundler?                    | true                                                                                       |
| Git                         | git version 2.15.0                                                                         |
| Installation Source         | ~/Work/testcompany/CoolApp/CoolAppiOS/vendor/bundle/ruby/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.13.1 (17B48)                                                                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                                                                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                                                                |
| Is contained                | false                                                                                      |
| Is homebrew                 | false                                                                                      |
| Is installed via Fabric.app | false                                                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                                |
| Xcode Version               | 9.1                                                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.5.0"

default_platform :ios

platform :ios do

    before_all do
		ENV["MATCH_GIT_URL"] =  "git@gitlab.testcompany.com:testcompany/apple-certificates.git"
		ENV['FASTLANE_TEAM_ID'] = 'OBFUSCATED'
	
		if ENV['FASTLANE_USER'].nil?
			ENV['FASTLANE_USER'] = 'test@test.com'
		end
        ENV['MATCH_KEYCHAIN_NAME'] = 'login.keychain-db'
		ENV['MATCH_USERNAME'] = ENV['FASTLANE_USER']
		ENV['DELIVER_USERNAME'] = ENV['FASTLANE_USER']
		ENV['PILOT_USERNAME'] = ENV['FASTLANE_USER']
        ENV['MATCH_KEYCHAIN_NAME'] = 'login.keychain-db'
        ENV['CERT_KEYCHAIN_PATH'] = '~/Library/Keychains/login.keychain-db'

		if is_ci?
			unlock_keychain
		end
    end

    desc "Runs all the tests"
        lane :test do
#         appicon(
# 			appicon_devices: [:iphone, :marketing, :ipad], 
# 			appicon_path: 'CoolApp/Images.xcassets' # output path
# 		)
        type_certificates(type: 'development')
        Actions.sh('bundle exec pod repo update')
        Actions.sh('rm -rf ../Pods')
        cocoapods
        Actions.sh('rm -rf ../ios-build-*')
        Actions.sh('rm -rf ../tvos-build-*')
        type_certificates(type: 'development', platform: 'ios')
        gym(scheme: "CoolApp", configuration: "Debug", include_symbols: true, include_bitcode: true, clean: true, archive_path: "ios-build-dev/", output_directory: "ios-build-dev/", export_method: "development")
        type_certificates(type: 'development', platform: 'tvos')
        gym(scheme: "CoolApp tvOS", destination: "generic/platform=tvOS", include_symbols: true, include_bitcode: true, configuration: "Debug", archive_path: "tvos-build-dev/", output_directory: "tvos-build-dev/", export_method: "development")
        Actions.sh('mv ../tvos-build-dev/.xcarchive.xcarchive ../tvos-build-dev/CoolApp\ tvOS.xcarchive')
        Actions.sh('mv ../ios-build-dev/.xcarchive.xcarchive ../ios-build-dev/CoolApp.xcarchive')
    end

    desc "Builds release versions"
    lane :release_build do
        Actions.sh('bundle exec pod repo update')
        Actions.sh('rm -rf ../Pods')
        cocoapods

        # Increment build number
        increment_build_number

        # Set version number to the one at the top of the CHANGELOG
        readme = File.read("../CHANGELOG.md")
        latest_version = readme.split("\n## ").first
        first_line = latest_version.split("\n").first
        version_number = first_line.split(" ")[1]

        increment_version_number(version_number: version_number)

        clean_build_artifacts

        commit_version_bump(message: "[ci skip] Deploying build version #{lane_context[SharedValues::BUILD_NUMBER]} and main version #{version_number}", xcodeproj: 'CoolApp.xcodeproj', force: true)
        push_to_git_remote

        # Generate release notes from CHANGELOG
        release_notes = latest_version.split("\n")[1..-1].join("\n")

        Actions.sh('rm -rf ../ios-build-*')
        Actions.sh('rm -rf ../tvos-build-*')
        type_certificates(type: 'appstore', platform: 'ios')
        gym(scheme: "CoolApp", configuration: "Release", include_symbols: true, include_bitcode: true, archive_path: "ios-build-release/", output_directory: "ios-build-release/", export_method: "app-store")
        type_certificates(type: 'appstore', platform: 'tvos')
        gym(scheme: "CoolApp tvOS", destination: "generic/platform=tvOS", configuration: "Release", include_symbols: true, include_bitcode: true, archive_path: "tvos-build-release/", output_directory: "tvos-build-release/", export_method: "app-store")
        Actions.sh('mv ../tvos-build-release/.xcarchive.xcarchive ../tvos-build-release/CoolApp\ tvOS.xcarchive')
        Actions.sh('mv ../ios-build-release/.xcarchive.xcarchive ../ios-build-release/CoolApp.xcarchive')
        deliver(precheck_default_rule_level: :error, skip_binary_upload: true, app_version: version_number, force: true)
    end

    desc "Submits a new Beta Build to Apple TestFlight"
    lane :deploy do
    	deploy_ios
		deploy_tvos
    end

    desc "Submits a new Beta Build to Apple TestFlight"
    lane :deploy_ios do
		# Set version number to the one at the top of the CHANGELOG
		readme = File.read("../CHANGELOG.md")
		latest_version = readme.split("\n## ").first
		first_line = latest_version.split("\n").first
		version_number = first_line.split(" ")[1]

		# Generate release notes from CHANGELOG
		release_notes = latest_version.split("\n")[1..-1].join("\n")

        pilot(changelog: release_notes, ipa: 'ios-build-release/CoolApp.ipa')
    end

    desc "Submits a new Beta Build to Apple TestFlight"
    lane :deploy_tvos do
		# Set version number to the one at the top of the CHANGELOG
		readme = File.read("../CHANGELOG.md")
		latest_version = readme.split("\n## ").first
		first_line = latest_version.split("\n").first
		version_number = first_line.split(" ")[1]

		# Generate release notes from CHANGELOG
		release_notes = latest_version.split("\n")[1..-1].join("\n")

        pilot(changelog: release_notes, ipa: 'tvos-build-release/CoolApptvOS.ipa')
    end

    lane :certificates do
        type_certificates(type: 'appstore', platform: 'ios')
        type_certificates(type: 'appstore', platform: 'tvos')
        type_certificates(type: 'development', platform: 'ios')
        type_certificates(type: 'development', platform: 'tvos')
    end

	private_lane :type_certificates do |options|
		ENV['MATCH_TYPE'] = options[:type]
        platform = options[:platform]
        if platform=="ios"
        match(app_identifier: ["com.test.CoolApp.CoolAppTodayExtension","com.test.CoolApp.watchkitapp","com.test.CoolApp.watchkitapp.watchkitextension", "com.test.CoolApp.WaitTimesMessage", "com.test.CoolApp"], force: true)
        end

        if platform=="tvos"
            match(app_identifier: ["com.test.CoolApp"], platform: "tvos",force: true)
        end
	end


    lane :screenshots do
        snapshot
        sh "cp -R ./watchscreenshots/* ./screenshots/en-US"
    end

    lane :refresh_dsyms do
        download_dsyms(app_identifier: "com.test.CoolApp", platform: 'ios')                 # Download dSYM files from iTC
        upload_symbols_to_crashlytics   # Upload them to Crashlytics
        clean_build_artifacts           # Delete the local dSYM files

        download_dsyms(app_identifier: "com.test.CoolApp", platform: 'tvOS')                 # Download dSYM files from iTC
        upload_symbols_to_crashlytics   # Upload them to Crashlytics
        clean_build_artifacts           # Delete the local dSYM files
    end

    # You can define as many lanes as you want

    after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    end


    error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
    end
end


# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.test.CoolApp" # The bundle identifier of your app
apple_id "test@test.com" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
# team_name "Felix Krause"
# team_id "Q2CBPJ58CA"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#the-appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.65.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.10.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appicon   | 0.10.0       |
| openssl                   | 2.0.6        |
</details>

*generated on:* **2017-11-20**
</details>

**Comment by pablog** [comment]
Same error using `Spaceship` after updating to `2.65.0`.

**Comment by ohayon** [comment]
Hey folks! Thanks for reporting this. We are working on fixes for these new TestFlight changes currently. We will have a fix for this one up soon! Stay tuned!

**Comment by ohayon** [comment]
Here is a fix: https://github.com/fastlane/fastlane/pull/10961

**Comment by bassrock** [comment]
Can confirm its fixed in 2.66.0

**Comment by sebastienhannay** [comment]
I still have an issue with 2.66.0

I'm trying to get latest dsym with `'fastlane run download_dsyms version:'latest'` and got this error : 
```
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/actions/download_dsyms.rb:34:in `run': [!] undefined method `build_version' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/commands_generator.rb:192:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.66.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

If I specify the version and build I want, it doesn't find the dsym : 
```
[15:50:52]: No dSYM URL for 20171121.1312 (2.2.4)
[15:50:52]: No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet
```
Works perfectly with fastlane 2.64.1

**Comment by ninjudd** [comment]
I'm having the same issue as @sebastienhannay

**Comment by ninjudd** [comment]
I'm still getting the same error:
```
[13:40:51]: No dSYM URL for 8 (1.5.0)
[13:40:51]: No dSYM URL for 6 (1.5.0)
[13:40:51]: No dSYM URL for 5 (1.5.0)
[13:40:51]: No dSYM URL for 4 (1.5.0)
[13:40:51]: No dSYM URL for 3 (1.5.0)
[13:40:51]: No dSYM URL for 2 (1.5.0)
[13:40:51]: No dSYM URL for 1 (1.5.0)
[13:40:51]: No dSYM URL for 0 (1.5.0)
[13:40:51]: No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet
```

**Comment by ninjudd** [comment]
I'm still getting the same error on `2.66.2`:
```
[13:43:40]: No dSYM URL for 8 (1.5.0)
[13:43:40]: No dSYM URL for 6 (1.5.0)
[13:43:40]: No dSYM URL for 5 (1.5.0)
[13:43:40]: No dSYM URL for 4 (1.5.0)
[13:43:40]: No dSYM URL for 3 (1.5.0)
[13:43:40]: No dSYM URL for 2 (1.5.0)
[13:43:40]: No dSYM URL for 1 (1.5.0)
[13:43:40]: No dSYM URL for 0 (1.5.0)
[13:43:40]: No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet
```
