### ISSUE TITLE
undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by swarchen** [fastlane/fastlane#10977]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm using jenkins and fastlane to do the CI/CD. All the build step are all passed like below.

```
ERROR [2017-11-22 00:30:50.39]: [31mundefined method `split' for nil:NilClass[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 14          |
| 4    | get_version_number                  | 0           |
| 5    | increment_build_number              | 0           |
| 6    | commit_version_bump                 | 0           |
| 7    | push_to_git_remote                  | 5           |
| 8    | gym                                 | 223         |
| 9    | changelog_from_git_commits          | 0           |
| 10   | pilot                               | 173         |
| 11   | slack                               | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-11-22 00:30:50.46]: [31mfastlane finished with errors[0m

/Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:360:in `version_range_info': [31m[!] undefined method `split' for nil:NilClass[0m (NoMethodError)
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:354:in `version'
	from Fastfile:95:in `block (2 levels) in parsing_binding'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:287:in `call'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:287:in `execute_flow_block'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:54:in `block in execute'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/caringloop/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.66.1/bin/fastlane:20:in `<top (required)>'
	from /Users/caringloop/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/caringloop/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
Build step 'Execute shell' marked build as failure
```

### Environment
Command Used: `env`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/Shared/Jenkins/Home/workspace/clhealthcare.ios staging/fastlane/Appfile'
- app_identifier: '********'
- apple_id: '********'
- team_id: '********'
-------
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | 10.12.6                                             |
| Ruby                        | 2.2.4                                               |
| Bundler?                    | false                                               |
| Git                         | git version 2.13.6 (Apple Git-96)                   |
| Installation Source         | /Users/caringloop/.fastlane/bin/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G1036)                          |
| Ruby Lib Dir                | /Users/caringloop/.fastlane/bin/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                          |
| Is contained                | false                                               |
| Is homebrew                 | true                                                |
| Is installed via Fabric.app | false                                               |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/         |
| Xcode Version               | 9.1                                                 |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.61.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "********"
    ENV["FASTLANE_PASSWORD"] = "********"
    ENV["MATCH_PASSWORD"] = "********"
    skip_docs
    # cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    match(type: "development", readonly: true)

    # increment build number
    version = get_version_number
    build_number = increment_build_number

    # commit version bump
    commit_version_bump(message:"[ci skip] Version Bump to version #{version} & Build number : #{build_number}")

    # push to remote
    push_to_git_remote(
        local_branch: "HEAD",  # optional, aliased by "branch", default: "master"
        remote_branch: "develop"
    )

    # Build
    gym(
      scheme: "CLHealthCare",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "Caringloop.CLHealthCare" => "match Development Caringloop.CLHealthCare"
        }
      },
      export_xcargs: "-allowProvisioningUpdates"
    ) # Build your app - more options available

    changelog_from_git_commits(
      commits_count: 10,
      merge_commit_filtering: "exclude_merges"
    )

    pilot(
      skip_waiting_for_build_processing: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "CLHealthCare") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    slack(
      message: ":airplane: 新版的 App 發佈到TestFlight上啦！: version #{version} & Build number : #{build_number}",
      success: true,        # Optional, defaults to true.
      payload: {  # Optional, lets you specify any number of your own Slack attachments.
        "Build Date" => Time.new.to_s,
      }
      # default_payloads: [:git_branch, :git_author], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
            # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit_message`, `last_git_commit_hash`.
      # attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
      #      # This hash is deep merged with the existing properties set using the other properties above. This allows your own fields properties to be appended to the existing fields that were created using the `payload` property for instance.
      #   thumb_url: "http://example.com/path/to/thumb.png",
      #   fields: [{
      #     title: "My Field",
      #     value: "My Value",
      #     short: true
      #   }]
      # }
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.2        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-11-22**
</details>

```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | 10.12.6                                             |
| Ruby                        | 2.2.4                                               |
| Bundler?                    | false                                               |
| Git                         | git version 2.13.6 (Apple Git-96)                   |
| Installation Source         | /Users/caringloop/.fastlane/bin/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G1036)                          |
| Ruby Lib Dir                | /Users/caringloop/.fastlane/bin/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                          |
| Is contained                | false                                               |
| Is homebrew                 | true                                                |
| Is installed via Fabric.app | false                                               |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/         |
| Xcode Version               | 9.1                                                 |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.61.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "*********"
    ENV["FASTLANE_PASSWORD"] = "********"
    ENV["MATCH_PASSWORD"] = "********"
    skip_docs
    # cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    match(type: "development", readonly: true)

    # increment build number
    version = get_version_number
    build_number = increment_build_number

    # commit version bump
    commit_version_bump(message:"[ci skip] Version Bump to version #{version} & Build number : #{build_number}")

    # push to remote
    push_to_git_remote(
        local_branch: "HEAD",  # optional, aliased by "branch", default: "master"
        remote_branch: "develop"
    )

    # Build
    gym(
      scheme: "CLHealthCare",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "Caringloop.CLHealthCare" => "match Development Caringloop.CLHealthCare"
        }
      },
      export_xcargs: "-allowProvisioningUpdates"
    ) # Build your app - more options available

    changelog_from_git_commits(
      commits_count: 10,
      merge_commit_filtering: "exclude_merges"
    )

    pilot(
      skip_waiting_for_build_processing: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "CLHealthCare") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    slack(
      message: ":airplane: 新版的 App 發佈到TestFlight上啦！: version #{version} & Build number : #{build_number}",
      success: true,        # Optional, defaults to true.
      payload: {  # Optional, lets you specify any number of your own Slack attachments.
        "Build Date" => Time.new.to_s,
      }
      # default_payloads: [:git_branch, :git_author], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
            # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit_message`, `last_git_commit_hash`.
      # attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
      #      # This hash is deep merged with the existing properties set using the other properties above. This allows your own fields properties to be appended to the existing fields that were created using the `payload` property for instance.
      #   thumb_url: "http://example.com/path/to/thumb.png",
      #   fields: [{
      #     title: "My Field",
      #     value: "My Value",
      #     short: true
      #   }]
      # }
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "*********" # The bundle identifier of your app
apple_id "*******" # Your Apple email address

team_id "********" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.2        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

**Comment by milch** [comment]
Hi @swarchen, thanks for submitting a separate issue! 

I believe I've found your error: in your after_all block you are referencing `build_number` and `version`, which are undefined there (it seems they are only defined in the beta lane). The error message you are getting is a bit odd though. 

You can use ENV to pass values around globally, e.g. `ENV['version'] = version` at the end of your beta lane, or you can also define a variable outside of any lanes to give it global context. 

Let me know if that fixes your issue!

**Comment by swarchen** [comment]
@milch It works!  💯✈️   
Thank you for saving my day   🙇

**Comment by milch** [comment]
No problem, always a pleasure to help out!
