### ISSUE TITLE
Update doesn't work

### ISSUE THREAD

**Issue by cherpake** [fastlane/fastlane#10986]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

update_fastlane produces this

`[22:20:05]: Looking for updates for fastlane...
[22:20:09]: Updating fastlane from 2.66.1 to 2.66.2... 🚀
WARN: Unresolved specs during Gem::Specification.reset:
      gh_inspector (< 2.0.0, >= 1.0.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

#######################################################################
# fastlane 2.66.2 is available. You are on 2.66.1.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.66.2 Fix download_dsyms and pilot export
* Search for app version platform using symbol instead of string (#10984) via Joshua Liebowitz
* Don't assume date is integer (#10981) via Joshua Liebowitz

Please update using `sudo gem install fastlane`
/Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/rdoc.rb:193:in `generate': [!] undefined method `reset' for RDoc::TopLevel:Class (NoMethodError)
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/rdoc.rb:82:in `block in generation_hook'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/rdoc.rb:81:in `each'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/rdoc.rb:81:in `generation_hook'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/request_set.rb:186:in `block in install'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/request_set.rb:185:in `each'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/request_set.rb:185:in `install'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/dependency_installer.rb:405:in `install'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/commands/update_command.rb:212:in `update_gem'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/actions/update_fastlane.rb:73:in `block in run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/actions/update_fastlane.rb:59:in `each'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/actions/update_fastlane.rb:59:in `run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:10:in `parsing_binding'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:54:in `eval'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:54:in `block in parse'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:43:in `chdir'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:43:in `parse'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:33:in `initialize'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/lane_manager.rb:12:in `new'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/bin/fastlane:20:in `<top (required)>'
	from /Users/cherpake/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /Users/cherpake/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'
`

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.2                           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :ios

platform :ios do
  lane :deploy do
	cocoapods
    increment_build_number
	commit_version_bump(message: "Version Bump", xcodeproj: "./Control.xcodeproj")
    gym(include_bitcode: true, workspace: "Control.xcworkspace", scheme: "Control")
    deliver(skip_screenshots: true, force: true, edit_live: false, ignore_language_directory_validation: true)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.cherpake.macrc.adsfree" # The bundle identifier of your app
apple_id "d314127481@gmail.com" # Your Apple email address

team_id "MCKT7VHXP5"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.2        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2017-11-21**
</details>

**Comment by cherpake** [comment]
[22:20:05]: -----------------------------
[22:20:05]: --- Step: update_fastlane ---
[22:20:05]: -----------------------------
[22:20:05]: Looking for updates for fastlane...
[22:20:09]: Updating fastlane from 2.66.1 to 2.66.2... 🚀
WARN: Unresolved specs during Gem::Specification.reset:
      gh_inspector (< 2.0.0, >= 1.0.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

#######################################################################
# fastlane 2.66.2 is available. You are on 2.66.1.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.66.2 Fix download_dsyms and pilot export
* Search for app version platform using symbol instead of string (#10984) via Joshua Liebowitz
* Don't assume date is integer (#10981) via Joshua Liebowitz

Please update using `sudo gem install fastlane`
/Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/rdoc.rb:193:in `generate': [!] undefined method `reset' for RDoc::TopLevel:Class (NoMethodError)
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/rdoc.rb:82:in `block in generation_hook'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/rdoc.rb:81:in `each'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/rdoc.rb:81:in `generation_hook'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/request_set.rb:186:in `block in install'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/request_set.rb:185:in `each'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/request_set.rb:185:in `install'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/dependency_installer.rb:405:in `install'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/commands/update_command.rb:212:in `update_gem'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/actions/update_fastlane.rb:73:in `block in run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/actions/update_fastlane.rb:59:in `each'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/actions/update_fastlane.rb:59:in `run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:10:in `parsing_binding'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:54:in `eval'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:54:in `block in parse'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:43:in `chdir'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:43:in `parse'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/fast_file.rb:33:in `initialize'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/lane_manager.rb:12:in `new'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/cherpake/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.66.1/bin/fastlane:20:in `<top (required)>'
	from /Users/cherpake/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /Users/cherpake/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'

**Comment by cherpake** [comment]
Actually I think it did work (the update part) but it did not restart itself as it used to be to continue the run with updated version
