### ISSUE TITLE
deliver fails to select a build for review

### ISSUE THREAD

**Issue by oborudko** [fastlane/fastlane#10998]
### Issue Description

After 2.64.1, deliver started to fail submitting the build for review, not exactly sure what is wrong, it all started with saying my marketing and support urls are unreachable for some reason, both of them works fine.

I have a feeling I'm disabling the unreachable_urls properly in a wrong way or something is going on there with the Precheckfile.

Basically it throws error at 2.64.1 too, but does not causes deliver to fail and block the rest of my publishing script.

Any help or advice will be very much appreciated, since I do not want to get stucked with older version of fastlane.

#####  Extract from output when running fastlane, including the stack trace and command used

ERROR [2017-11-22 19:13:56.46]: fastlane precheck just tried to inspect your app's metadata for App Store guideline violations and ran into a problem. We're not sure what the problem was, but precheck failed to finished. You can run it in verbose mode if you want to see the whole error. We'll have a fix out soon 🚀
DEBUG [2017-11-22 19:13:56.46]: #<NoMethodError: undefined method `[]' for false:FalseClass>
DEBUG [2017-11-22 19:13:56.46]: /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/precheck/lib/precheck/rule_processor.rb:57:in `block in process_rules'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/precheck/lib/precheck/rule_processor.rb:55:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/precheck/lib/precheck/rule_processor.rb:55:in `process_rules'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/precheck/lib/precheck/rule_processor.rb:46:in `process_app_and_version'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/precheck/lib/precheck/runner.rb:99:in `check_for_rule_violations'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/precheck/lib/precheck/runner.rb:31:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/deliver/lib/deliver/runner.rb:62:in `precheck_app'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/deliver/lib/deliver/runner.rb:34:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/actions/deliver.rb:16:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
Fastfile:150:in `block (2 levels) in parsing_binding'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/lane.rb:33:in `call'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/bin/fastlane:20:in `<top (required)>'
/usr/local/bin/fastlane:22:in `load'
/usr/local/bin/fastlane:22:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:335:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.2 (17C79a)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Precheckfile`</summary>

```ruby
include_in_app_purchases false
unreachable_urls false
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "***"
apple_id "***" # Your Apple email address
package_name "***"
team_id "***"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.0        |
| slack-notifier        | 1.5.1        |
| CFPropertyList        | 2.3.5        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-screen            | 0.6.2        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| highline              | 1.7.8        |
| commander-fastlane    | 4.4.5        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| fastimage             | 2.1.0        |
| gh_inspector          | 1.0.3        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.1        |
| security              | 0.1.3        |
| bundler               | 1.14.3       |
| json                  | 2.1.0        |
| io-console            | 0.4.6        |
| excon                 | 0.59.0       |
| openssl               | 2.0.2        |
| plist                 | 3.3.0        |
| faraday               | 0.13.1       |
| faraday_middleware    | 0.12.2       |
| os                    | 0.9.6        |
| googleauth            | 0.6.2        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.13.6       |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| signet                | 0.8.1        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.3        |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.3.0        |
</details>

*generated on:* **2017-11-22**
</details>

**Comment by oborudko** [comment]
ignore me
