### ISSUE TITLE
Cannot upload metadata anymore - Error regarding App Preview for larger display size

### ISSUE THREAD

**Issue by ricperrott** [fastlane/fastlane#11022]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have an app that has 5 localizations. I use screenshots for iPhone X, iPhone 5.5", and iPhone 12.9" only and let iTunes derive the rest of them. I have an app preview for the default localization and then one overridden app preview for one of the other localizations.

When I attempt to update metadata using Deliver (metadata only, not screenshots), the process fails with the following error:

> Potential server error received: 'Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-GB]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.'. Retrying after 10 seconds (remaining: 5)...

And them Fastlane simply errors out and does not complete the upload.

This is confusing because I am not even trying to upload an App Preview at this time. I do not know what the potential path forward is for this?

##### Complete output when running fastlane, including the stack trace and command used

`### Captured Output

Command Used: `metadata`
<details><summary>Output/Log</summary>

`fastlane metadata
[11:21:09]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:21:11]: -------------------------------------------------
[11:21:11]: --- Step: Verifying required fastlane version ---
[11:21:11]: -------------------------------------------------
[11:21:11]: Your fastlane version 2.66.2 matches the minimum requirement of 2.64.1  ✅
[11:21:11]: ------------------------------
[11:21:11]: --- Step: default_platform ---
[11:21:11]: ------------------------------
[11:21:11]: Driving the lane 'ios metadata' 🚀
[11:21:11]: -------------------------------------
[11:21:11]: --- Step: ensure_git_status_clean ---
[11:21:11]: -------------------------------------
[11:21:11]: $ git status --porcelain
[11:21:11]: Git status is clean, all good! 💪
[11:21:11]: ---------------------
[11:21:11]: --- Step: deliver ---
[11:21:11]: ---------------------
[11:21:11]: Successfully loaded '/Users/perrottr/git/X/src/X/Apps/X/fastlane/Deliverfile' 📄

+------------------+----------------------------+
| Detected Values from './fastlane/Deliverfile' |
+------------------+----------------------------+
| app_identifier   | [REDACTED] |
| username         | [REDACTED]        |
+------------------+----------------------------+

[11:21:11]: Login to iTunes Connect ([REDACTED] )
[11:21:15]: Login successful

+--------------------------------------+----------------------------+
|                      deliver 2.66.2 Summary                       |
+--------------------------------------+----------------------------+
| force                                | true                       |
| submit_for_review                    | false                      |
| skip_binary_upload                   | true                       |
| skip_screenshots                     | true                       |
| precheck_include_in_app_purchases    | false                      |
| screenshots_path                     | ./fastlane/screenshots     |
| metadata_path                        | ./fastlane/metadata        |
| username                             | [REDACTED]        |
| app_identifier                       | [REDACTED]  |
| edit_live                            | false                      |
| platform                             | ios                        |
| skip_metadata                        | false                      |
| skip_app_version_update              | false                      |
| automatic_release                    | false                      |
| dev_portal_team_id                   | [REDACTED]                  |
| overwrite_screenshots                | false                      |
| run_precheck_before_submit           | true                       |
| precheck_default_rule_level          | warn                       |
| ignore_language_directory_validation | false                      |
+--------------------------------------+----------------------------+

[11:21:17]: Loading './fastlane/metadata/en-AU/description.txt'...
[11:21:17]: Loading './fastlane/metadata/en-AU/keywords.txt'...
[11:21:17]: Loading './fastlane/metadata/en-AU/release_notes.txt'...
[11:21:17]: Loading './fastlane/metadata/en-AU/support_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-AU/marketing_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-AU/promotional_text.txt'...
[11:21:17]: Loading './fastlane/metadata/en-AU/name.txt'...
[11:21:17]: Loading './fastlane/metadata/en-AU/subtitle.txt'...
[11:21:17]: Loading './fastlane/metadata/en-AU/privacy_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-CA/description.txt'...
[11:21:17]: Loading './fastlane/metadata/en-CA/keywords.txt'...
[11:21:17]: Loading './fastlane/metadata/en-CA/release_notes.txt'...
[11:21:17]: Loading './fastlane/metadata/en-CA/support_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-CA/marketing_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-CA/promotional_text.txt'...
[11:21:17]: Loading './fastlane/metadata/en-CA/name.txt'...
[11:21:17]: Loading './fastlane/metadata/en-CA/subtitle.txt'...
[11:21:17]: Loading './fastlane/metadata/en-CA/privacy_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-GB/description.txt'...
[11:21:17]: Loading './fastlane/metadata/en-GB/keywords.txt'...
[11:21:17]: Loading './fastlane/metadata/en-GB/release_notes.txt'...
[11:21:17]: Loading './fastlane/metadata/en-GB/support_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-GB/marketing_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-GB/promotional_text.txt'...
[11:21:17]: Loading './fastlane/metadata/en-GB/name.txt'...
[11:21:17]: Loading './fastlane/metadata/en-GB/subtitle.txt'...
[11:21:17]: Loading './fastlane/metadata/en-GB/privacy_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-US/description.txt'...
[11:21:17]: Loading './fastlane/metadata/en-US/keywords.txt'...
[11:21:17]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[11:21:17]: Loading './fastlane/metadata/en-US/support_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[11:21:17]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[11:21:17]: Loading './fastlane/metadata/en-US/name.txt'...
[11:21:17]: Loading './fastlane/metadata/en-US/subtitle.txt'...
[11:21:17]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[11:21:17]: Loading './fastlane/metadata/fr-FR/description.txt'...
[11:21:17]: Loading './fastlane/metadata/fr-FR/keywords.txt'...
[11:21:17]: Loading './fastlane/metadata/fr-FR/release_notes.txt'...
[11:21:17]: Loading './fastlane/metadata/fr-FR/support_url.txt'...
[11:21:17]: Loading './fastlane/metadata/fr-FR/marketing_url.txt'...
[11:21:17]: Loading './fastlane/metadata/fr-FR/promotional_text.txt'...
[11:21:17]: Loading './fastlane/metadata/fr-FR/name.txt'...
[11:21:17]: Loading './fastlane/metadata/fr-FR/subtitle.txt'...
[11:21:17]: Loading './fastlane/metadata/fr-FR/privacy_url.txt'...
[11:21:17]: Loading './fastlane/metadata/copyright.txt'...
[11:21:17]: Loading './fastlane/metadata/primary_category.txt'...
[11:21:17]: Loading './fastlane/metadata/secondary_category.txt'...
[11:21:17]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[11:21:17]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[11:21:17]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[11:21:17]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/trade_name.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/first_name.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/last_name.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/address_line1.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/address_line2.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/city_name.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/state.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/country.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/postal_code.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/phone_number.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/email_address.txt'...
[11:21:17]: Loading './fastlane/metadata/trade_representative_contact_information/is_displayed_on_app_store.txt'...
[11:21:17]: Loading './fastlane/metadata/review_information/first_name.txt'...
[11:21:17]: Loading './fastlane/metadata/review_information/last_name.txt'...
[11:21:17]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[11:21:17]: Loading './fastlane/metadata/review_information/email_address.txt'...
[11:21:17]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[11:21:17]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[11:21:17]: Loading './fastlane/metadata/review_information/notes.txt'...
[11:21:24]: Activating languages en-AU, en-CA, en-GB, en-US, fr-FR...
Potential server error received: 'Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-GB]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.'. Retrying after 10 seconds (remaining: 5)...
Potential server error received: 'Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-GB]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.'. Retrying after 10 seconds (remaining: 5)...
[11:21:49]: -----------------------------------
[11:21:49]: --- Step: clean_build_artifacts ---
[11:21:49]: -----------------------------------
[11:21:49]: Cleaned up build artifacts 🐙
[11:21:49]: 
(╯°□°）╯︵ ┻━┻

[11:21:49]: --------------------------
[11:21:49]: --- Step: notification ---
[11:21:49]: --------------------------
+-----------------------------+--------------+
|                Lane Context                |
+-----------------------------+--------------+
| DEFAULT_PLATFORM            | ios          |
| PLATFORM_NAME               | ios          |
| LANE_NAME                   | ios metadata |
| GIT_REPO_WAS_CLEAN_ON_START | true         |
+-----------------------------+--------------+
[11:21:50]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-GB]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ensure_git_status_clean             | 0           |
| 💥   | deliver                             | 37          |
| 5    | clean_build_artifacts               | 0           |
| 6    | notification                        | 0           |
+------+-------------------------------------+-------------+

[11:21:50]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[!] The request could not be completed because:
	Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-GB]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.
`

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# All lines starting with a # are ignored when running `fastlane`

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.64.1"
skip_docs
default_platform :ios

  desc "Upload Just Metadata to iTunes"
  lane :metadata do
    deliver(force: true, submit_for_review: false, skip_binary_upload: true, skip_screenshots: true, precheck_include_in_app_purchases:false)
  end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.2        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.5        |
</details>

*generated on:* **2017-11-25**
</details>`

**Comment by janpio** [comment]
Anything special about en-GB or the metadata you are uploading for it?

**Comment by ricperrott** [comment]
Hi,

No, that just happens to be the default localization. Like I said, I have an app Preview and screenshots uploaded for iPhoneX, iPhone 5.5", and iPad 12.9" and I let iTC derive the rest. It looks like iTC is throwing this error and it is causing Fastlane to terminate the whole process rather than ignore and continue with the rest of the metadata.

Thanks

**Comment by janpio** [comment]
Ok, so the error message maybe even isn't caused by anything localized, but the lang code is maybe included because it is the default language.

Are app preview and screenshots localized?

Some code research:

The error message "Potential server error received" comes from here:
https://github.com/fastlane/fastlane/blob/33bf0721b283c692eaf7e8e312a6c7dade5cb6a4/spaceship/lib/spaceship/tunes/tunes_client.rb#L1297

Which is raised here:
https://github.com/fastlane/fastlane/blob/33bf0721b283c692eaf7e8e312a6c7dade5cb6a4/spaceship/lib/spaceship/tunes/tunes_client.rb#L211

Which depends on `flaky_api` setting:
https://github.com/fastlane/fastlane/blob/33bf0721b283c692eaf7e8e312a6c7dade5cb6a4/spaceship/lib/spaceship/tunes/tunes_client.rb#L140
This seems to be used sometimes and seems to be the case for you here.

But: Your error message doesn't really indicate flakiness, more a logic error maybe that causes too much data to be submitted?

Could you rerun with `--verbose` and see if this gives you additional output?

**Comment by ricperrott** [comment]
Thanks. Running with verbose didn't give much more info. This was at the bottom of the run..

`ERROR [2017-11-26 15:52:26.77]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/tunes/tunes_client.rb:211:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectPotentialServerError)
	Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. [en-GB]: Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. There is an error for 1 of your localizations.
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/tunes/tunes_client.rb:401:in `block in update_app_version!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/tunes/tunes_client.rb:1285:in `with_tunes_retry'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/tunes/tunes_client.rb:394:in `update_app_version!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/spaceship/lib/spaceship/tunes/app_version.rb:392:in `save!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/deliver/lib/deliver/upload_metadata.rb:248:in `verify_available_languages!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/deliver/lib/deliver/upload_metadata.rb:68:in `upload'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.66.2/deliver/lib/deliver/runner.rb:109:in `upload_metadata'`

At this point, I have to consider this a bug in Fastlane as I am not trying to upload screenshots at all, just text metadata. An error about screenshots should not interrupt the processing of text metadata.

**Comment by ricperrott** [comment]
Ok, further investigation into this seems to point to having an iPhone X App Preview video. If I have one for the en-GB locale, I get the failure, if I remove it, then I do not get the failure any longer. So, this could be a bug in iTunes Connect.

**Comment by max-ott** [comment]
Having the same issue with a brand new app without any app previews uploaded. I try to upload an app preview for 5.5-inch. I can upload the exact same app preview on Safari without any issues. I only have one locale.

**Comment by taquitos** [comment]
Hey @max-ott if you could open a new issue with your output (after running fastlane --verbose) that would be great! The fact you isolated this down to just 1 preview + the fact that uploading the same preview in safari works is super helpful.

**Comment by max-ott** [comment]
I was testing it directly with the spaceship playground. Is there any way to get the --verbose output or similar?

**Comment by gerbil802** [comment]
I have the same issue with no preview at all on ITC. I try to upload screenshots.

**Comment by jkammerer** [comment]
Had the same. I removed the default language folder (in my case en-US) and then the upload worked fine.

**Comment by anfriis** [comment]
Have the same issue. Needs to remove the video from iTunes Connect before running in order to succeed

**Comment by tkiener** [comment]
Same here. Had to remove preview videos from ITC before uploading screenshots via fastlane

**Comment by evilmint** [comment]
Same issue here. Is there any way around?

**Comment by gerbil802** [comment]
Same here.
