### ISSUE TITLE
xcversion started to fail with latest falstane on Travis

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#11048]
```
Cleaning up installed gems...
Clean up complete
Updating installed gems
Updating fastlane
Fetching: xcodeproj-1.5.3.gem (100%)
Successfully installed xcodeproj-1.5.3
Fetching: tty-screen-0.6.3.gem (100%)
Successfully installed tty-screen-0.6.3
Fetching: commander-fastlane-4.4.5.gem (100%)
Successfully installed commander-fastlane-4.4.5
Fetching: declarative-0.0.10.gem (100%)
Successfully installed declarative-0.0.10
Fetching: declarative-option-0.1.0.gem (100%)
Successfully installed declarative-option-0.1.0
Fetching: representable-3.0.4.gem (100%)
Successfully installed representable-3.0.4
Fetching: mime-types-data-3.2016.0521.gem (100%)
Successfully installed mime-types-data-3.2016.0521
Fetching: mime-types-3.1.gem (100%)
Successfully installed mime-types-3.1
Fetching: google-api-client-0.13.6.gem (100%)
Successfully installed google-api-client-0.13.6
Fetching: fastlane-2.67.0.gem (100%)
Successfully installed fastlane-2.67.0
Gems updated: commander-fastlane declarative declarative-option fastlane google-api-client mime-types mime-types-data representable tty-screen xcodeproj
[10:03:24]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:03:27]: -------------------------------------------------
[10:03:27]: --- Step: Verifying required fastlane version ---
[10:03:27]: -------------------------------------------------
[10:03:27]: Your fastlane version 2.67.0 matches the minimum requirement of 2.35.0  ✅
[10:03:27]: -------------------
[10:03:27]: --- Step: is_ci ---
[10:03:27]: -------------------
[10:03:27]: -------------------
[10:03:27]: --- Step: is_ci ---
[10:03:27]: -------------------
[10:03:27]: -------------------
[10:03:27]: --- Step: is_ci ---
[10:03:27]: -------------------
[10:03:27]: ------------------------------
[10:03:27]: --- Step: default_platform ---
[10:03:27]: ------------------------------
[10:03:27]: Driving the lane 'ios travis_create_keychain' 🚀
[10:03:27]: ----------------------------------------
[10:03:27]: --- Step: Switch to ios prepare lane ---
[10:03:27]: ----------------------------------------
[10:03:27]: Cruising over to lane 'ios prepare' 🚖
[10:03:27]: -----------------------
[10:03:27]: --- Step: xcversion ---
[10:03:27]: -----------------------
[10:03:27]: Installing Ruby gem 'xcode-install'...
Fetching: xcode-install-2.3.1.gem (100%)
[10:03:41]: Successfully installed 'xcode-install'
[10:03:41]: Setting Xcode version to /Applications/Xcode.app for all build steps
[10:03:42]: ----------------------------------
[10:03:42]: --- Step: ensure_xcode_version ---
[10:03:42]: ----------------------------------
[10:03:42]: $ xcversion selected
[10:03:42]: ▸ /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:283:in `matching_specs': uninitialized constant Gem::BundlerVersionFinder (NameError)
[10:03:42]: ▸ Did you mean?  Gem::BundlerVersionFinder
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:302:in `to_specs'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2648:in `block in traverse'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `each'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `traverse'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1103:in `block in find_in_unresolved_tree'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `each'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `find_in_unresolved_tree'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `require'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:283:in `matching_specs'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:302:in `to_specs'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2648:in `block in traverse'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `each'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `traverse'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1103:in `block in find_in_unresolved_tree'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `each'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `find_in_unresolved_tree'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `require'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:239:in `finish_resolve'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:311:in `block in activate_bin_path'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:309:in `synchronize'
[10:03:42]: ▸ from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:309:in `activate_bin_path'
[10:03:42]: ▸ from /Users/travis/.rvm/gems/ruby-2.4.1/bin/xcversion:23:in `<main>'
+------------------+----------------------------+
|                 Lane Context                  |
+------------------+----------------------------+
| DEFAULT_PLATFORM | ios                        |
| PLATFORM_NAME    | ios                        |
| LANE_NAME        | ios travis_create_keychain |
+------------------+----------------------------+
[10:03:43]: Exit status of command 'xcversion selected' was 1 instead of 0.
/Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:283:in `matching_specs': uninitialized constant Gem::BundlerVersionFinder (NameError)
Did you mean?  Gem::BundlerVersionFinder
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:302:in `to_specs'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2648:in `block in traverse'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `each'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `traverse'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1103:in `block in find_in_unresolved_tree'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `each'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `find_in_unresolved_tree'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:283:in `matching_specs'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:302:in `to_specs'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2648:in `block in traverse'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `each'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `traverse'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1103:in `block in find_in_unresolved_tree'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `each'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `find_in_unresolved_tree'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:239:in `finish_resolve'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:311:in `block in activate_bin_path'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:309:in `synchronize'
	from /Users/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:309:in `activate_bin_path'
	from /Users/travis/.rvm/gems/ruby-2.4.1/bin/xcversion:23:in `<main>'
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | is_ci                               | 0           |
| 3    | is_ci                               | 0           |
| 4    | is_ci                               | 0           |
| 5    | default_platform                    | 0           |
| 6    | Switch to ios prepare lane          | 0           |
| 7    | xcversion                           | 14          |
| 💥    | ensure_xcode_version                | 0           |
+------+-------------------------------------+-------------+
[10:03:43]: fastlane finished with errors
```

**Comment by romk1n** [comment]
can't get env from travis, but that's with fastlane `2.67.0` probably ruby conflict

**Comment by florianreinhart** [comment]
I am getting a similar error when running watchbuild on my Mac.

```
$ watchbuild 
/Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:283:in `matching_specs': uninitialized constant Gem::BundlerVersionFinder (NameError)
Did you mean?  Gem::BundlerVersionFinder
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:302:in `to_specs'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2648:in `block in traverse'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `each'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `traverse'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1103:in `block in find_in_unresolved_tree'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `each'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `find_in_unresolved_tree'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:283:in `matching_specs'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:302:in `to_specs'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2648:in `block in traverse'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `each'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2646:in `traverse'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1103:in `block in find_in_unresolved_tree'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `each'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1102:in `find_in_unresolved_tree'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems.rb:241:in `finish_resolve'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems.rb:313:in `block in activate_bin_path'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems.rb:311:in `synchronize'
	from /Users/flo/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems.rb:311:in `activate_bin_path'
	from /Users/flo/.rbenv/versions/2.4.2/bin/watchbuild:23:in `<main>'
```

**Comment by heach** [comment]
Running `gem cleanup` solved this issue for me.

**Comment by nubek** [comment]
@heach "gem cleanup" solved also the issue for me 👍

**Comment by KrauseFx** [comment]
Awesome, thanks everyone 👍
