### ISSUE TITLE
match fails with error "[!] undefined method `com' for nil:NilClass (NoMethodError)"

### ISSUE THREAD

**Issue by dukeow94** [fastlane/fastlane#11088]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I followed match tutorials from [here](https://docs.fastlane.tools/actions/match/),
but It doesn't work as it is supposed.

##### Complete output when running fastlane, including the stack trace and command used

```
❯ fastlane match appstore

Looking for related GitHub issues on fastlane/fastlane...

➡️  `fastlane deliver download_metadata` crash: NoMethodError: [!] undefined method `version' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11046 [open] 8 💬
    16 hours ago

➡️  Type Checking error: got 'Fixnum' for attribute 'fileEncoding' and undefined method `each' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11016 [open] 1 💬
    a week ago

➡️  `app_store_build_number` fails with `undefined method `current_build_number' for nil:NilClass (NoMethodError)`
    https://github.com/fastlane/fastlane/issues/10447 [open] 11 💬
    a week ago

and 250 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60com%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:43:in `eval': [!] undefined method `com' for nil:NilClass (NoMethodError)
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:43:in `eval'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:43:in `initialize'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:175:in `new'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:175:in `load_configuration_file'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/match/lib/match/commands_generator.rb:53:in `block (3 levels) in run'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/match/lib/match/commands_generator.rb:134:in `run'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/match/lib/match/commands_generator.rb:13:in `start'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/cli_tools_distributor.rb:67:in `take_off'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.0/bin/fastlane:20:in `<top (required)>'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/HyeonsuGo/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/HyeonsuGo/workspace/iOS/Washow/fastlane/Appfile'
- app_identifier: 'com.jocoos.washow.app'
- apple_id: 'dev@jocoos.com'
- team_id: '5CXMSK555F'
-------
WARN [2017-12-01 21:22:34.39]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2017-12-01 21:22:37.63]: Checking if there are any plugins that should be loaded...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.0"

generated_fastfile_id "6f67a1fd-042a-4660-8fe4-363928105358"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
	get_certificates(           # invokes cert
			development: true)
    get_provisioning_profile   # invokes sigh
    build_app(
			workspace: "Washow.xcworkspace",
			scheme: "Washow") # more options available
#upload_to_testflight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

    # upload to Beta by Crashlytics
	crashlytics(
    # keys for organization: Jocoos_temp
    api_token: "17814dd81835807f712cbfb0c9cee57818fbba48",
    build_secret: "9fcd12a24f2c4705b0e0a60bcb7449254ed98f7aa56f629d10dde033c9e09e32"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # sync_code_signing(type: "appstore")
    capture_screenshots
    build_app(scheme: "washow") # Build your app - more options available
    upload_to_app_store(force: true)
    # frame_screenshots
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.jocoos.washow.app" # The bundle identifier of your app
apple_id "dev@jocoos.com" # Your Apple email address

team_id "5CXMSK555F" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.10       |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.3.1        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| concurrent-ruby           | 1.0.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.9.1        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.6.3        |
| tzinfo                    | 1.2.4        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-12-01**
</details>
WARN [2017-12-01 21:22:37.67]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
INFO [2017-12-01 21:22:37.67]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.0"

generated_fastfile_id "6f67a1fd-042a-4660-8fe4-363928105358"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
	get_certificates(           # invokes cert
			development: true)
    get_provisioning_profile   # invokes sigh
    build_app(
			workspace: "Washow.xcworkspace",
			scheme: "Washow") # more options available
#upload_to_testflight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

    # upload to Beta by Crashlytics
	crashlytics(
    # keys for organization: Jocoos_temp
    api_token: "17814dd81835807f712cbfb0c9cee57818fbba48",
    build_secret: "9fcd12a24f2c4705b0e0a60bcb7449254ed98f7aa56f629d10dde033c9e09e32"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # sync_code_signing(type: "appstore")
    capture_screenshots
    build_app(scheme: "washow") # Build your app - more options available
    upload_to_app_store(force: true)
    # frame_screenshots
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.jocoos.washow.app" # The bundle identifier of your app
apple_id "dev@jocoos.com" # Your Apple email address

team_id "5CXMSK555F" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.10       |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| cocoapods                 | 1.3.1        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| concurrent-ruby           | 1.0.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.9.1        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.6.3        |
| tzinfo                    | 1.2.4        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-12-01**
</details>

**Comment by dukeow94** [comment]
I found that I wrote username without quotes("") in Matchfile.
