### ISSUE TITLE
Match profiles become ineligible when having multiple projects

### ISSUE THREAD

**Issue by rogerkerse** [fastlane/fastlane#11101]
I have 2 projects with different bundle ids. They both use fastlane and fastlane match.
When I create certificate for the other with 'match appstore', then the other project stops recognizing the provisioning profile and says it is ineligible.

It is very annoying if I do weekly releases, to go and delete old certificates from the repo and regenerating them every time for a release, because generating them for another project made previous ones invalid.

**Comment by rogerkerse** [comment]
I use 2.68.0 version of fastlane.

**Comment by ohayon** [comment]
Hey @rogerkerse, could you provide some more information about your problem, seeing the output from your command line would be helpful if you could run your command with `--verbose` so we can see all of the ins and outs of whats happening? Thanks! 🚀

**Comment by rogerkerse** [comment]
```
Successfully loaded Appfile at path '/Users/rogerkerse/Documents/Projects/Bolt/coconut/ios/fastlane/Appfile'
- app_identifier: 'ee.bolt.coconut'
- apple_id: 'email@email.email'
- team_id: 'TEAM_ID'
-------
INFO [2017-12-14 16:10:05.46]: Successfully loaded '/Users/rogerkerse/Documents/Projects/Bolt/coconut/ios/fastlane/Matchfile' 📄

+---------+--------------------------------------+
|  Detected Values from './fastlane/Matchfile'   |
+---------+--------------------------------------+
| git_url | https://bitbucket.org/boltstudios/c  |
|         | oconut-certificates                  |
| type    | development                          |
+---------+--------------------------------------+

DEBUG [2017-12-14 16:10:05.47]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'

+-----------------------+--------------------------------------+
|                   Summary for match 2.64.1                   |
+-----------------------+--------------------------------------+
| verbose               | true                                 |
| git_url               | https://bitbucket.org/email/x  |
|                       | -certificates                  |
| type                  | development                          |
| git_branch            | master                               |
| app_identifier        | ee.bolt.coconut                      |
| username              | email@email.email             |
| keychain_name         | login.keychain                       |
| readonly              | false                                |
| team_id               | TEAM_ID                           |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

INFO [2017-12-14 16:10:05.48]: Cloning remote git repo...
INFO [2017-12-14 16:10:05.48]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2017-12-14 16:10:05.48]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://bitbucket.org/email/x-certificates' '/var/folders/5t/h6ycvwtd6kl9wfzdhs0tbbnc0000gn/T/d20171214-29657-lc3opc'
INFO [2017-12-14 16:10:05.50]: ▸ Cloning into '/var/folders/5t/h6ycvwtd6kl9wfzdhs0tbbnc0000gn/T/d20171214-29657-lc3opc'...
INFO [2017-12-14 16:10:06.72]: ▸ git: 'credential-wincred' is not a git command. See 'git --help'.
INFO [2017-12-14 16:10:08.35]: ▸ remote: Counting objects: 137, done.
INFO [2017-12-14 16:10:08.87]: ▸ remote: Compressing objects: 100% (116/116), done.
INFO [2017-12-14 16:10:09.34]: ▸ remote: Total 137 (delta 12), reused 0 (delta 0)
INFO [2017-12-14 16:10:09.34]: ▸ Receiving objects: 100% (137/137), 174.08 KiB | 408.00 KiB/s, done.
INFO [2017-12-14 16:10:09.34]: ▸ Resolving deltas: 100% (12/12), done.
INFO [2017-12-14 16:10:09.42]: 🔓  Decrypted 'H24P8BZ88B.cer'
INFO [2017-12-14 16:10:09.48]: 🔓  Decrypted 'H24P8BZ88B.p12'
INFO [2017-12-14 16:10:09.54]: 🔓  Decrypted 'AppStore_ee.bolt.coconut.mobileprovision'
INFO [2017-12-14 16:10:09.54]: 🔓  Successfully decrypted certificates repo
INFO [2017-12-14 16:10:09.58]: Verifying that the certificate and profile are still valid on the Dev Portal...
WARN [2017-12-14 16:10:12.81]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+--------------------------------------+
|               Summary for cert 2.64.1                |
+---------------+--------------------------------------+
| development   | true                                 |
| force         | true                                 |
| username      | email@email.email             |
| team_id       | TEAM_ID                           |
| keychain_path | /Users/rogerkerse/Library/Keychains  |
|               | /login.keychain-db                   |
| platform      | ios                                  |
+---------------+--------------------------------------+

INFO [2017-12-14 16:10:12.84]: Starting login with user 'email@email.email'
INFO [2017-12-14 16:10:14.88]: Successfully logged in

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not create another Development certificate, reached the maximum number of available Development certificates.

URL: https://api.github.com/search/issues?q=Could%20not%20create%20another%20Development%20certificate,%20reached%20the%20maximum%20number%20of%20available%20Development%20certificates.+repo:fastlane/fastlane
➡️  Match can't find certificate in repo if run again.
    https://github.com/fastlane/fastlane/issues/10489 [open] 27 💬
    22 hours ago

➡️  Match "Couldn't find a valid code signing identity in the git repo for development"
    https://github.com/fastlane/fastlane/issues/10512 [closed] 6 💬
    2 weeks ago

➡️  match failed in development
    https://github.com/fastlane/fastlane/issues/9215 [closed] 8 💬
    26 Sep 2017

and 22 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20create%20another%20Development%20certificate,%20reached%20the%20maximum%20number%20of%20available%20Development%20certificates.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

#######################################################################
# fastlane 2.69.2 is available. You are on 2.64.1.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.69.2 Hotfix for match requiring an Array for app_identifier
* Version bump to 2.69.2 (#11213) via Joshua Liebowitz
* Fix match requiring an Array for app_identifier (#11212) via Joshua Liebowitz
* Revert "Change sync_code_signing example to use an array type" (#11211) via Mark Pirri

2.69.1 Bug fixes
[fastlane_core] Fix the property list workaround for ruby ~2.0 (#11202) via Manu Wallner
[fastlane_core] Fix unnecessary Xcode check for macOS (revert #4631) (#11184) via Jan Piotrowski
[gym] Fix issue with wrong #to_plist in package_command_generator_xcode7.rb (#11208) via Jimmy Dee
[gym] Fix verbose logging with gym
[docs] Fix some documentation typos (#11193) via Nate West
[Fastlane.swift] Update Fastfile.swift template to use new core action names (#11194) via Mark Pirri
[sync_code_signing] Change sync_code_signing example to use an array type (#11195) via Mark Pirri

2.69.0 fastlane Swift support, beta
* Write your fastfile in Swift, calling: fastlane init swift
* Updated snapshot to include Snapfile.swift can now run fastlane snapshot init swift via Joshua Liebowitz
* Updated screengrab to include Screengrabfile.swift can now call fastlane screengrab init swift via Joshua Liebowitz
* Updated scan to include Scanfile.swift can now call fastlane scan init swift via Joshua Liebowitz
* Updated Match to include Matchfile.swift can now call fastlane match init swift via Joshua Liebowitz
* Updated Gym to include Gymfile.swift Can now call fastlane gym init swift via Joshua Liebowitz
* Updated Precheck to include Precheckfile.swift can call fastlane precheck init swift now via Joshua Liebowitz
* Updated deliver to include Deliver.swift Updated appFile to include AppFile.swift Piped is_swift throughout setup can now run fastlane init swift to init for Fastlane.swift via Joshua Liebowitz
* Added calling of beforeAll/afterall Add ability to run fastlane socket server like: $fastlane socket_server via Joshua Liebowitz
* Autogenerate all the various tools protocols and default implementations Ignore some default param values that are derived from the environment Added processing of Options types via Joshua Liebowitz
* Added Default Swift Fastfile Improved type inference from ruby to Swift types Updated handling of environment variables in Swift via Joshua Liebowitz
* Create subclass structures for Lanefile subclasses via Joshua Liebowitz
* Sometimes you can get a nil provider hash (#11179) via Joshua Liebowitz
* Fix simulator_path (#11177) via Jan Piotrowski
* Limit testing of Timeout-Process-Bug to macOS only (#11178) via Jan Piotrowski
* Sometimes we can get a value that doesn't support .to_sym (#11173) via Joshua Liebowitz
* Added require for 'addressable' (#11171) via Joshua Liebowitz
* Fix doc link in error handler (#11172) via Joshua Liebowitz
* Fix conflict between CFPropertyList and plist in gym (was: Move require 'cfpropertylist' to limit its scope.) (#11163) via Jimmy Dee
* Improve GitHub Issue and Pull Request templates (#11157) via Iulian Onofrei
* Add support for a postfix block with sh (#11152) via Jimmy Dee
* Add supported platforms for platform parameter description. (#11148) via Kristaps Grinbergs
* [frameit] Ensure both texts use same baseline (issue #10440) (#11124) via funnel20
* Added BUILDKITE_BRANCH ENV var to git_branch action (#11146) via Michael Smith
* Further improvements to sh (#11068) via Jimmy Dee
* Show plugin actions on the plugin page (#11117) via Manu Wallner
* Update tty-screen dependency for fastlane (#11035) via Felix Krause
* Version bump to 2.69.0 (#11192) via Joshua Liebowitz
* Option descriptions cannot include newlines (#11185) via Jimmy Dee

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `bundle update fastlane`
/Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Could not create another Development certificate, reached the maximum number of available Development certificates. (FastlaneCore::Interface::FastlaneError)
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/cert/lib/cert/runner.rb:151:in `rescue in create_certificate'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/cert/lib/cert/runner.rb:146:in `create_certificate'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/cert/lib/cert/runner.rb:37:in `run'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/cert/lib/cert/runner.rb:6:in `launch'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/match/lib/match/generator.rb:21:in `generate_certificate'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/match/lib/match/runner.rb:85:in `fetch_certificate'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/match/lib/match/runner.rb:42:in `run'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/match/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/match/lib/match/commands_generator.rb:134:in `run'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/match/lib/match/commands_generator.rb:13:in `start'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/rogerkerse/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.64.1/bin/fastlane:20:in `<top (required)>'
	from /Users/rogerkerse/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/rogerkerse/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by SimonStefan** [comment]
You should call cert only once! Use nuke to delete your three recently created certificates and start again.

**Comment by rogerkerse** [comment]
I explain the flow again. I nuked all my certificates and when I create certificate for first project with bundle id of example.app1, then this works. Now I start creating certificates for second project that is with bundle id of example.app2. This works as well and now example.app2 works, but example.app1 does not work anymore!

**Comment by rogerkerse** [comment]
In short, when creating certificate for totally different bundle-id, it invalidates the other certificates (and they don't have the same bundle-id)

**Comment by getaaron** [comment]
Are you trying to use the same certificate repo for 2 different apps?

**Comment by rogerkerse** [comment]
No seperate repos

**Comment by rogerkerse** [comment]
@chkchk isn't it unsafe? If I give someone access to one of my projects so they would be able to deploy, does it mean they can deploy the other one as well now?

**Comment by chkchk** [comment]
@rogerkerse create three repo:
1. Project A
2. Project B
3. Certificate 
give other member access to Project A and Certificate so your Project B will be safe

**Comment by rogerkerse** [comment]
I would say it's not fixing the problem, but just bypassing, but well for now works, thanks
