### ISSUE TITLE
Android Screengrab fails on API >=24

### ISSUE THREAD

**Issue by DhulipalaS** [fastlane/fastlane#11105]
Opening a new one since https://github.com/fastlane/fastlane/issues/9676 was auto-closed without a solution.

### New Issue Checklist

- [ ✔️] Updated fastlane to the latest version
- [✔️ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ✔️] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✔️ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Android Screengrab fails on API >=24

Screengrab works on Nexus 4 with API 23 Emulator with Android Studio 3.0, compileSdk set to 26. And has been throwing the error below for API above 23 i.e., 24, 25 and 26.

This line in ExampleInstrumentedTest.java causes the failure. Once removed, it works fine, but we are trying to look for a string in a drop down which is preset on the screen (can confirm from the View hierarchy from device monitor)

`onView(withText("All")).perform(click());` 

### Environment

<details><summary>🚫 fastlane environment 🚫</summary

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:
<details><summary>`./fastlane/Appfile`</summary>

```ruby
package_name "com.xxxx.android"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                              | Version | Update-Status      |
| ----------------------------------- | ------- | ------------------ |
| fastlane-plugin-android_versioning  | 0.2.2   | 🚫 Update available |
| fastlane-plugin-find_replace_string | 0.1.0   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                                 | Version      |
| ----------------------------------- | ------------ |
| executable-hooks                    | 1.3.2        |
| bundler-unload                      | 1.0.2        |
| rubygems-bundler                    | 1.4.4        |
| bundler                             | 1.14.6       |
| CFPropertyList                      | 2.3.5        |
| public_suffix                       | 2.0.5        |
| addressable                         | 2.5.2        |
| babosa                              | 1.0.2        |
| backports                           | 3.8.0        |
| claide                              | 1.0.2        |
| colored                             | 1.2          |
| colored2                            | 3.1.2        |
| highline                            | 1.7.10       |
| commander-fastlane                  | 4.4.5        |
| connection_pool                     | 2.2.1        |
| declarative                         | 0.0.10       |
| declarative-option                  | 0.1.0        |
| unf_ext                             | 0.0.7.4      |
| unf                                 | 0.1.4        |
| domain_name                         | 0.5.20170404 |
| dotenv                              | 2.2.1        |
| ffi                                 | 1.9.18       |
| ethon                               | 0.10.1       |
| excon                               | 0.59.0       |
| multipart-post                      | 2.0.0        |
| faraday                             | 0.13.1       |
| http-cookie                         | 1.0.3        |
| faraday-cookie_jar                  | 0.0.6        |
| faraday_middleware                  | 0.12.2       |
| fastimage                           | 2.1.0        |
| gh_inspector                        | 1.0.3        |
| jwt                                 | 2.1.0        |
| little-plugger                      | 1.1.4        |
| multi_json                          | 1.12.2       |
| logging                             | 2.2.2        |
| memoist                             | 0.16.0       |
| os                                  | 0.9.6        |
| signet                              | 0.8.1        |
| googleauth                          | 0.6.2        |
| httpclient                          | 2.8.3        |
| mime-types-data                     | 3.2016.0521  |
| mime-types                          | 3.1          |
| uber                                | 0.1.0        |
| representable                       | 3.0.4        |
| retriable                           | 3.1.1        |
| google-api-client                   | 0.13.6       |
| json                                | 2.1.0        |
| mini_magick                         | 4.5.1        |
| multi_xml                           | 0.6.0        |
| plist                               | 3.3.0        |
| rubyzip                             | 1.2.1        |
| security                            | 0.1.3        |
| slack-notifier                      | 1.5.1        |
| terminal-notifier                   | 1.8.0        |
| unicode-display_width               | 1.3.0        |
| terminal-table                      | 1.8.0        |
| tty-screen                          | 0.6.3        |
| word_wrap                           | 1.0.0        |
| nanaimo                             | 0.2.3        |
| xcodeproj                           | 1.5.3        |
| rouge                               | 2.0.7        |
| xcpretty                            | 0.2.8        |
| xcpretty-travis-formatter           | 1.0.0        |
| fastlane-plugin-android_versioning  | 0.2.2        |
| fastlane-plugin-find_replace_string | 0.1.0        |
| net-http-persistent                 | 3.0.0        |
| net-http-pipeline                   | 1.0.1        |
| gh                                  | 0.14.0       |
| launchy                             | 2.4.3        |
| mail                                | 2.6.6        |
| pony                                | 1.11         |
| websocket                           | 1.2.4        |
| pusher-client                       | 0.6.2        |
| typhoeus                            | 0.8.0        |
| travis                              | 1.8.8        |
| trollop                             | 2.1.2        |
| web_translate_it                    | 2.4.1        |
</details>

*generated on:* **2017-12-04**
</details>

### fastlane screengrab

```
bundle exec fastlane screengrab

+-----------------------------+------------------------------------------------+
|                        Summary for screengrab 2.68.0                         |
+-----------------------------+------------------------------------------------+
| tests_package_name          | com.xxxx.android.test                    |
| android_home                | /Users/sirisha.dhulipala
com.xxxx.android.test                    |
| android_home                | /Users/sirisha.dhulipala/Library/Android/sdk   |
| locales                     | ["en-US"]                                      |
| clear_previous_screenshots  | false                                          |
| output_directory            | fastlane/metadata/android                      |
| skip_open_summary           | false                                          |
| app_package_name            | com.xxxx.android                         |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner |
| ending_locale               | en-US                                          |
| device_type                 | phone                                          |
| exit_on_test_failure        | true                                           |
| reinstall_app               | false                                          |
+-----------------------------+------------------------------------------------+

[10:30:58]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[10:30:58]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[10:30:58]: $ adb devices -l
[10:30:58]: ▸ List of devices attached
[10:30:58]: ▸ emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
[10:30:58]: $ adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[10:30:59]: ▸ /sdcard
[10:30:59]: Cleaning screenshots on device
ls: /sdcard/com.xxxxx.android/screengrab: No such file or directory
[10:30:59]: Exit status: 1
ls: /data/data/com.xxxxx.android/app_screengrab: No such file or directory
[10:30:59]: Exit status: 1
[10:30:59]: To not be asked about this value, you can specify it using 'app_apk_path'
[10:30:59]: Select your debug app APK
1. rlbase/build/outputs/apk/androidTest/prod/alpha/rlbase-prod-alpha-androidTest-unsigned.apk
2. app/build/outputs/apk/prod/alpha/app-prod-alpha.apk
3. app/build/outputs/apk/androidTest/prod/alpha/app-prod-alpha-androidTest.apk
?  2
[10:31:00]: To not be asked about this value, you can specify it using 'tests_apk_path'
[10:31:00]: Select your debug tests APK
1. rlbase/build/outputs/apk/androidTest/prod/alpha/rlbase-prod-alpha-androidTest-unsigned.apk
2. app/build/outputs/apk/prod/alpha/app-prod-alpha.apk
3. app/build/outputs/apk/androidTest/prod/alpha/app-prod-alpha-androidTest.apk
?  3
[10:31:00]: Validating app APK
[10:31:00]: $ /Users/sirisha.dhulipala/Library/Android/sdk/build-tools/27.0.1/aapt dump permissions app/build/outputs/apk/prod/alpha/app-prod-alpha.apk
[10:31:00]: ▸ package: com.xxxxx.android
[10:31:00]: ▸ permission: com.xxxxx.android.permission.C2D_MESSAGE
[10:31:00]: ▸ uses-permission: name='com.xxxxx.android.permission.C2D_MESSAGE'
[10:31:00]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[10:31:00]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[10:31:00]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[10:31:00]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[10:31:00]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[10:31:00]: ▸ uses-permission: name='com.google.android.providers.gsf.permission.READ_GSERVICES'
[10:31:00]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[10:31:00]: ▸ uses-permission: name='android.permission.INTERNET'
[10:31:00]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[10:31:00]: ▸ uses-permission: name='android.permission.CALL_PHONE'
[10:31:00]: ▸ uses-permission: name='android.permission.USE_FINGERPRINT'
[10:31:00]: ▸ uses-permission: name='android.permission.READ_PHONE_STATE'
[10:31:00]: ▸ uses-permission: name='android.permission.INTERACT_ACROSS_USERS'
[10:31:00]: ▸ uses-permission: name='com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY'
[10:31:00]: ▸ uses-permission: name='com.sec.android.provider.badge.permission.READ'
[10:31:00]: ▸ uses-permission: name='com.sec.android.provider.badge.permission.WRITE'
[10:31:00]: ▸ uses-permission: name='com.htc.launcher.permission.READ_SETTINGS'
[10:31:00]: ▸ uses-permission: name='com.htc.launcher.permission.UPDATE_SHORTCUT'
[10:31:00]: ▸ uses-permission: name='com.sonyericsson.home.permission.BROADCAST_BADGE'
[10:31:00]: ▸ uses-permission: name='com.sonymobile.home.permission.PROVIDER_INSERT_BADGE'
[10:31:00]: ▸ uses-permission: name='com.anddoes.launcher.permission.UPDATE_COUNT'
[10:31:00]: ▸ uses-permission: name='com.majeur.launcher.permission.UPDATE_BADGE'
[10:31:00]: ▸ uses-permission: name='com.huawei.android.launcher.permission.CHANGE_BADGE'
[10:31:00]: ▸ uses-permission: name='com.huawei.android.launcher.permission.READ_SETTINGS'
[10:31:00]: ▸ uses-permission: name='com.huawei.android.launcher.permission.WRITE_SETTINGS'
[10:31:00]: ▸ uses-permission: name='android.permission.READ_APP_BADGE'
[10:31:00]: ▸ uses-permission: name='com.oppo.launcher.permission.READ_SETTINGS'
[10:31:00]: ▸ uses-permission: name='com.oppo.launcher.permission.WRITE_SETTINGS'
[10:31:00]: ▸ uses-permission: name='me.everything.badger.permission.BADGE_COUNT_READ'
[10:31:00]: ▸ uses-permission: name='me.everything.badger.permission.BADGE_COUNT_WRITE'
[10:31:00]: Installing app APK
[10:31:00]: $ adb -s emulator-5554 install -r app/build/outputs/apk/prod/alpha/app-prod-alpha.apk
[10:31:02]: ▸ Success
[10:31:02]: Installing tests APK
[10:31:02]: $ adb -s emulator-5554 install -r app/build/outputs/apk/androidTest/prod/alpha/app-prod-alpha-androidTest.apk
[10:31:02]: ▸ Success
[10:31:02]: Granting the permission necessary to change locales on the device
[10:31:02]: $ adb -s emulator-5554 shell pm grant com.xxxxx.android android.permission.CHANGE_CONFIGURATION
[10:31:03]: $ adb -s emulator-5554 shell getprop ro.build.version.sdk
[10:31:03]: ▸ 24
[10:31:03]: Granting the permissions necessary to access device external storage
[10:31:03]: $ adb -s emulator-5554 shell pm grant com.xxxxx.android android.permission.WRITE_EXTERNAL_STORAGE
[10:31:03]: $ adb -s emulator-5554 shell pm grant com.xxxxx.android android.permission.READ_EXTERNAL_STORAGE
[10:31:04]: Running tests for locale: en-US
[10:31:04]: $ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
com.xxxxx.android.test/android.support.test.runner.AndroidJUnitRunner
[10:31:08]: ▸ com.xxxx.android.ExampleInstrumentedTest:
[10:31:08]: ▸ Error in testScreenshot(com.xxxx.android.ExampleInstrumentedTest):
[10:31:08]: ▸ java.lang.IllegalStateException: Couldn't get the activity from the view context
[10:31:08]: ▸ at tools.fastlane.screengrab.DecorViewScreenshotStrategy$ScreenshotViewAction.perform(DecorViewScreenshotStrategy.java:69)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:356)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:241)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
[10:31:08]: ▸ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[10:31:08]: ▸ at android.os.Handler.handleCallback(Handler.java:751)
[10:31:08]: ▸ at android.os.Handler.dispatchMessage(Handler.java:95)
[10:31:08]: ▸ at android.os.Looper.loop(Looper.java:154)
[10:31:08]: ▸ at android.app.ActivityThread.main(ActivityThread.java:6077)
[10:31:08]: ▸ at java.lang.reflect.Method.invoke(Native Method)
[10:31:08]: ▸ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
[10:31:08]: ▸ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
[10:31:08]: ▸ Time: 3.785
[10:31:08]: ▸ There was 1 failure:
[10:31:08]: ▸ 1) testOverviewScreen(com.xxxx.android.ExampleInstrumentedTest)
[10:31:08]: ▸ java.lang.IllegalStateException: Couldn't get the activity from the view context
[10:31:08]: ▸ at tools.fastlane.screengrab.DecorViewScreenshotStrategy$ScreenshotViewAction.perform(DecorViewScreenshotStrategy.java:69)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:356)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:241)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
[10:31:08]: ▸ at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
[10:31:08]: ▸ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[10:31:08]: ▸ at android.os.Handler.handleCallback(Handler.java:751)
[10:31:08]: ▸ at android.os.Handler.dispatchMessage(Handler.java:95)
[10:31:08]: ▸ at android.os.Looper.loop(Looper.java:154)
[10:31:08]: ▸ at android.app.ActivityThread.main(ActivityThread.java:6077)
[10:31:08]: ▸ at java.lang.reflect.Method.invoke(Native Method)
[10:31:08]: ▸ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
[10:31:08]: ▸ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
[10:31:08]: ▸ FAILURES!!!
[10:31:08]: ▸ Tests run: 1,  Failures: 1
```

**Comment by ohayon** [comment]
Hey @fastlane/android folks!

**Comment by janpio** [comment]
@DhulipalaS, could you please create a super simple sample project that includes all the setup (necessary app content, tests, `Fastfile`) already and upload it to a Github repo so it is easier for someone to recreate the problem? Thanks.

**Comment by DhulipalaS** [comment]
@janpio Here you go. 
https://github.com/DhulipalaS/ScreengrabTest

**Comment by janpio** [comment]
What lanes to run to build before running `fastlane screengrab`?

**Comment by DhulipalaS** [comment]
None really. It is just  a test project with one button. Try `fastlane screengrab` (after building both the debug and test apk s) on emulator with API 24/25/26.

**Comment by DhulipalaS** [comment]
@janpio Just checking to see if we have updates on this issue?

**Comment by janpio** [comment]
No one else posted anything, and I didn't have the time to investigate as I am busy with other stuff. Sorry.

**Comment by choiks14** [comment]
same here.

**Comment by euler0** [comment]
Maybe you’ve to use the new screenshot strategy. ([Improved screenshot capture with UI Automator](https://docs.fastlane.tools/actions/screengrab/#improved-screenshot-capture-with-ui-automator))

I’ve solved the same issue by adding the below code:
```
@BeforeClass
public static void setUp() {
    Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy());
}
```
