### ISSUE TITLE
`sh` has strange, repeating error output and unclear stacktrace at the end

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11140]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a lane that uses https://github.com/ionic-zone/fastlane-plugin-ionic to build an Ionic project. The plugin uses `sh` to run a CLI command. This command is failing and throwing an error. Unfortunately this causes quite strangem repeating output of said error and a stacktrace at the end that doesn't help at all.

Here is the code that is calling `sh`: 
https://github.com/ionic-zone/fastlane-plugin-ionic/blob/59f895897ea6cde2e339746b6698403fd279f5b9/lib/fastlane/plugin/ionic/actions/ionic_action.rb#L91

This is the console output I get when running my lane:

```
Virtuals-Mac:ionic-fastlane foo$ fastlane ios build_debug
...
[02:39:14]: -------------------
[02:39:14]: --- Step: ionic ---
[02:39:14]: -------------------
...
[02:40:15]: $ ionic cordova compile ios --debug --device --prod -- --packageType=development --developmentTeam=4Z338HBBX3
> cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --debug --device
Building project: /Users/foo/ionic-fastlane/platforms/ios/FastlaneExample.xcworkspace
...
[02:40:37]: ▸ Check dependencies
Code Signing Error: No profiles for 'zone.ionic.fastlane' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'zone.ionic.fastlane'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
** ARCHIVE FAILED **
[02:40:37]: ▸ The following build commands failed:
[02:40:37]: ▸ Check dependencies
[02:40:37]: ▸ (1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/foo/ionic-fastlane/platforms/ios/cordova/build-debug.xcconfig,-workspace,FastlaneExample.xcworkspace,-scheme,FastlaneExample,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,FastlaneExample.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/sharedpch
[ERROR] An error occurred while running cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --deb... (exit code 1).
+------------------+-----------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | ios             |
| LANE_NAME        | ios build_debug |
+------------------+-----------------+
[02:40:38]: Exit status of command 'ionic cordova compile ios --debug --device --prod -- --packageType=development --developmentTeam=4Z338HBBX3' was 1 instead of 0.
> cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --debug --device
Building project: /Users/foo/ionic-fastlane/platforms/ios/FastlaneExample.xcworkspace
...
Check dependencies
Code Signing Error: No profiles for 'zone.ionic.fastlane' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'zone.ionic.fastlane'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/foo/ionic-fastlane/platforms/ios/cordova/build-debug.xcconfig,-workspace,FastlaneExample.xcworkspace,-scheme,FastlaneExample,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,FastlaneExample.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/sharedpch
[ERROR] An error occurred while running cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --deb... (exit code 1).
        


+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | ionic               | 82          |
+------+---------------------+-------------+

[02:40:39]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Could not access the GitHub API, you may have better luck via the website.
https://github.com/fastlane/fastlane/search?q=Exit status of command 'ionic cordova compile ios --debug --device --prod -- --packageType=development --developmentTeam=4Z338HBBX3' was 1 instead of 0.
> cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --debug --device
...
Check dependencies
Code Signing Error: No profiles for 'zone.ionic.fastlane' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'zone.ionic.fastlane'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/foo/ionic-fastlane/platforms/ios/cordova/build-debug.xcconfig,-workspace,FastlaneExample.xcworkspace,-scheme,FastlaneExample,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,FastlaneExample.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/sharedpch
[ERROR] An error occurred while running cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --deb... (exit code 1).
        
&type=Issues&utf8=✓
/Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!': [!] Exit status of command 'ionic cordova compile ios --debug --device --prod -- --packageType=development --developmentTeam=4Z338HBBX3' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
> cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --debug --device
...
Check dependencies
Code Signing Error: No profiles for 'zone.ionic.fastlane' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'zone.ionic.fastlane'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/foo/ionic-fastlane/platforms/ios/cordova/build-debug.xcconfig,-workspace,FastlaneExample.xcworkspace,-scheme,FastlaneExample,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,FastlaneExample.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/sharedpch
[ERROR] An error occurred while running cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --deb... (exit code 1).
        

	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/helper/sh_helper.rb:57:in `sh_control_output'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/action.rb:98:in `sh'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-ionic-0.0.4/lib/fastlane/plugin/ionic/actions/ionic_action.rb:107:in `build'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-ionic-0.0.4/lib/fastlane/plugin/ionic/actions/ionic_action.rb:126:in `run'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:78:in `block (2 levels) in parsing_binding'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:304:in `run'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/bin/fastlane:20:in `<top (required)>'
	from /Users/foo/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/foo/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
Virtuals-Mac:ionic-fastlane foo$ 
```
(I removed thousands of lines of useless output of the `ionic` command that repeats between the "Building project" and "▸ Check dependencies" lines)

Analyzing and separating this to annotate I have the following blocks:

Calling the action that then hands over to the `ionic` action:
```
Virtuals-Mac:ionic-fastlane foo$ fastlane ios build_debug
...
[02:39:14]: -------------------
[02:39:14]: --- Step: ionic ---
[02:39:14]: -------------------
...
```
`sh` call that executes the CLI command, which causes an error and fails (1):
```
[02:40:15]: $ ionic cordova compile ios --debug --device --prod -- --packageType=development --developmentTeam=4Z338HBBX3
> cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --debug --device
Building project: /Users/foo/ionic-fastlane/platforms/ios/FastlaneExample.xcworkspace
...
[02:40:37]: ▸ Check dependencies
Code Signing Error: No profiles for 'zone.ionic.fastlane' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'zone.ionic.fastlane'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
** ARCHIVE FAILED **
[02:40:37]: ▸ The following build commands failed:
[02:40:37]: ▸ Check dependencies
[02:40:37]: ▸ (1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/foo/ionic-fastlane/platforms/ios/cordova/build-debug.xcconfig,-workspace,FastlaneExample.xcworkspace,-scheme,FastlaneExample,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,FastlaneExample.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/sharedpch
```
Error is recognized in fastlane and lane context output:
```
[ERROR] An error occurred while running cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --deb... (exit code 1).
+------------------+-----------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | ios             |
| LANE_NAME        | ios build_debug |
+------------------+-----------------+
```
Then it outputs the status again, but also the whole output of the command that failed as well (2):
```
[02:40:38]: Exit status of command 'ionic cordova compile ios --debug --device --prod -- --packageType=development --developmentTeam=4Z338HBBX3' was 1 instead of 0.
> cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --debug --device
Building project: /Users/foo/ionic-fastlane/platforms/ios/FastlaneExample.xcworkspace
...
Check dependencies
Code Signing Error: No profiles for 'zone.ionic.fastlane' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'zone.ionic.fastlane'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/foo/ionic-fastlane/platforms/ios/cordova/build-debug.xcconfig,-workspace,FastlaneExample.xcworkspace,-scheme,FastlaneExample,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,FastlaneExample.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/sharedpch
[ERROR] An error occurred while running cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --deb... (exit code 1).
```
Then fastlane prints the summary that includes the fact that `ionic` crashed: 
```

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | ionic               | 82          |
+------+---------------------+-------------+

[02:40:39]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
```
It seems to try to access the Github API by searching for the _full error message_ that is a few hundred lines long, which of course fails (3):
```
Could not access the GitHub API, you may have better luck via the website.
https://github.com/fastlane/fastlane/search?q=Exit status of command 'ionic cordova compile ios --debug --device --prod -- --packageType=development --developmentTeam=4Z338HBBX3' was 1 instead of 0.
> cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --debug --device
...
Check dependencies
Code Signing Error: No profiles for 'zone.ionic.fastlane' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'zone.ionic.fastlane'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/foo/ionic-fastlane/platforms/ios/cordova/build-debug.xcconfig,-workspace,FastlaneExample.xcworkspace,-scheme,FastlaneExample,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,FastlaneExample.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/sharedpch
[ERROR] An error occurred while running cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --deb... (exit code 1).
        
&type=Issues&utf8=✓
```
Then again the full error for good measure (4):
```
/Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!': [!] Exit status of command 'ionic cordova compile ios --debug --device --prod -- --packageType=development --developmentTeam=4Z338HBBX3' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
> cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --debug --device
...
Check dependencies
Code Signing Error: No profiles for 'zone.ionic.fastlane' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'zone.ionic.fastlane'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/foo/ionic-fastlane/platforms/ios/cordova/build-debug.xcconfig,-workspace,FastlaneExample.xcworkspace,-scheme,FastlaneExample,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,FastlaneExample.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/foo/ionic-fastlane/platforms/ios/build/sharedpch
[ERROR] An error occurred while running cordova compile ios --packageType=development --developmentTeam=4Z338HBBX3 --deb... (exit code 1).
        
```
and finally a stacktrace that I don't understand at all:
```
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/helper/sh_helper.rb:57:in `sh_control_output'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/action.rb:98:in `sh'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-ionic-0.0.4/lib/fastlane/plugin/ionic/actions/ionic_action.rb:107:in `build'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-ionic-0.0.4/lib/fastlane/plugin/ionic/actions/ionic_action.rb:126:in `run'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:78:in `block (2 levels) in parsing_binding'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:304:in `run'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /Users/foo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.2/bin/fastlane:20:in `<top (required)>'
	from /Users/foo/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/foo/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
Virtuals-Mac:ionic-fastlane foo$ 
```

Seems the failing command is output 4 times in total.

I know the `ionic` command (actually `cordova that it is executing behind the scenes) is unnecessary long and verbose, but that can not be changed.

Is fastlane a bit to eager to print the error output?
Should the Github URL maybe not be output if it fails?
What does that stacktrace mean?

(That the error shows a code signing error is caused by the fact that it was easiest to trigger by the way. Normally `match` makes sure this doesn't happen)

**Comment by jdee** [comment]
I have some insight. This basically appears to be working as I would expect from the code. You can override this behavior to some degree using `error_callback`. Then the exception that generates the stack trace is not raised. An error message is printed using `UI.error`. That will still have the full command output, unless you disable it. There are some other options that help control that, but they are different depending where you're calling `sh`:

In an action:

```Ruby
sh "command", print_command_output: false, error_callback: ->(result) { ... }
```

In a Fastfile:

```Ruby
sh "command", log: false, error_callback: ->(result) { ... }
```

Obviously this could be improved.

**Comment by janpio** [comment]
Meaning I could improve the plugin's `sh` usage by using the `error_callback` and `log/print_command_output` param?

How would I do this in the case of fastlane-plugin-ionic - because the command output really **is** an ugly wall of text. Could I "swallow" some of the 4 outputs of this text in the callback? (I still want the default output on successful calls I think)

**Comment by jdee** [comment]
I was just looking at your fork, I think, in ionic-zone. Where you currently have

```Ruby
sh "ionic cordova platform add #{platform}"
```

You could make that

```Ruby
command = "ionic cordova platform add #{platform}"
sh(
  command,
  print_command_output: false,
  error_callback: ->(result) { error_occurred = true }
)
UI.user_error "command failed: #{command}" if error_occurred
```

You can even

```Ruby
def self.run_command(command)
  sh(
    command,
    print_command_output: false,
    error_callback: ->(result) { error_occurred = true }
  )
  UI.user_error "command failed: #{command}" if error_occurred
end
```

And then

```Ruby
run_command "ionic cordova platform add #{platform}"
```

**Comment by janpio** [comment]
Thanks, will play with that.

(Yep, correct repo: https://github.com/ionic-zone/fastlane-plugin-ionic)
