### ISSUE TITLE
Specify Fastfile to be executed by fastlane

### ISSUE THREAD

**Issue by realdeadfish** [fastlane/fastlane#11241]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I want to start `fastlane` with a specific `Fastfile`, i.e. not the default one it falls back onto. How do I do this?

Rationale: My complete fastlane configuration is hidden away in a subdirectory that is linked into several projects via git submodules. So I end up with some `ROOT/build-scripts/fastlane/Fastfile`, but still need to execute `fastlane` in `ROOT` and not in `ROOT/build-scripts`, since the `Fastfile` contains `ROOT` relative commands.

Now I read that you can import `Fastfile`s via `import`, so I theoretically could add a `ROOT/fastlane/Fastfile` that would point to `ROOT/build-scripts/fastlane/Fastfile`, but I find this very clumsy. I'd much rather prefer to give `fastlane` the alternative configuration directory `ROOT/build-scripts/fastlane` as a whole and not create any kind of "redirect". Is this somehow possible?

**Comment by KrauseFx** [comment]
Sorry, that's not possible, however there are multiple ways for you to solve it, for example you can use the `import` feature of fastlane to import different Fastfiles

**Comment by realdeadfish** [comment]
Yeah, thought as much - that's a real pity. Thanks for the clarification anyways.

**Comment by KrauseFx** [comment]
Sorry I couldn't be of more help

**Comment by realdeadfish** [comment]
That's fine :)

**Comment by realdeadfish** [comment]
```
[12:00:26]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:00:28]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?
```

Hrm... guess I need a symlink to the fastlane directory after all :(

**Comment by realdeadfish** [comment]
Ok, I symlinked `shared/fastlane` to  `fastlane` and fastlane seems to start up properly, but now I have a problem with a plugin that I use:

```
/virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Plugin 'automated_test_emulator_run_xing' was not properly loaded, make sure to follow the plugin docs for troubleshooting: https://docs.fastlane.tools/plugins/plugins-troubleshooting/ (FastlaneCore::Interface::FastlaneError)
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/runner.rb:161:in `rescue in trigger_action_by_name'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/runner.rb:155:in `trigger_action_by_name'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from ../../fastlane/Fastfile:22:in `block (2 levels) in parsing_binding'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/commands_generator.rb:343:in `run'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/gems/fastlane-2.70.0/bin/fastlane:20:in `<top (required)>'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/bin/fastlane:22:in `load'
	from /virtual/jenkins/workspace/crit_tk_XMESS-1954_ci-setup-YRCIXQHVJEF43SNG5ZEMJKCYSQWLFET5IN465PKY2MGZ43VLJNPA/gems/bin/fastlane:22:in `<main>'
script returned exit code 1
```

So, `fastlane/Pluginfile` is found, the gem listed there (automated_test_emulator_run_xing) is available, but still fastlane seems to be unable to use it. What am I doing wrong?
