### ISSUE TITLE
[Swift] Error message when lane can't be found is unclear

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#11394]
```
[✔] 🚀
+-------------------------------+---------+---------------+
|                      Used plugins                       |
+-------------------------------+---------+---------------+
| Plugin                        | Version | Action        |
+-------------------------------+---------+---------------+
| fastlane-plugin-emoji_fetcher | 0.2.0   | emoji_fetcher |
| fastlane-plugin-trainer       | 0.4.0   | trainer       |
+-------------------------------+---------+---------------+

[12:11:55]: FastlaneSwiftRunner project is up-to-date
[12:11:55]: $ xcodebuild -list -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[12:11:56]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[12:11:56]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' | tee /Users/felixkrause/Library/Logs/gym/App-FastlaneRunner.log | xcpretty
[12:11:59]: Waiting for 5 seconds for a connection from FastlaneRunner
[12:11:59]: $ ./fastlane/FastlaneRunner lane screenshots > /dev/null
[12:11:59]: Client connected
[12:11:59]: ▸ Fatal error: unable to find lane named: screenshots: file /Users/felixkrause/Developer/themoji/fastlane/swift/LaneFileProtocol.swift, line 89
[12:12:00]: Client disconnected, or a pipe broke
[12:12:00]: ▸ sh: line 1: 17755 Illegal instruction: 4  ./fastlane/FastlaneRunner lane screenshots > /dev/null
[12:12:00]: Exit status of command './fastlane/FastlaneRunner lane screenshots > /dev/null' was 132 instead of 0.
Fatal error: unable to find lane named: screenshots: file /Users/felixkrause/Developer/themoji/fastlane/swift/LaneFileProtocol.swift, line 89
sh: line 1: 17755 Illegal instruction: 4  ./fastlane/FastlaneRunner lane screenshots > /dev/null

[12:12:00]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/felixkrause/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command './fastlane/FastlaneRunner lane screenshots > /dev/null' was 132 instead of 0.
Fatal error: unable to find lane named: screenshots: file /Users/felixkrause/Developer/themoji/fastlane/swift/LaneFileProtocol.swift, line 89
sh: line 1: 17755 Illegal instruction: 4  ./fastlane/FastlaneRunner lane screenshots > /dev/null

  /Users/felixkrause/Developer/fastlane/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!'
  /Users/felixkrause/Developer/fastlane/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/felixkrause/Developer/fastlane/fastlane/lib/fastlane/helper/sh_helper.rb:75:in `sh_control_output'
  /Users/felixkrause/Developer/fastlane/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
  /Users/felixkrause/Developer/fastlane/fastlane/lib/fastlane/swift_lane_manager.rb:68:in `block in cruise_swift_lane_in_thread'
```

In this case, I forgot to append `Lane` at the end of the lane name my my Swift file. This is a common error, and should be handled more nicely, similar to how we handle it in the Ruby version:

```
[✔] 🚀
+-----------------------------+---------+--------------------------------+
|                              Used plugins                              |
+-----------------------------+---------+--------------------------------+
| Plugin                      | Version | Action                         |
+-----------------------------+---------+--------------------------------+
| fastlane-plugin-ruby        | 0.1.3   | rspec rubocop                  |
| fastlane-plugin-clubmate    | 0.1.0   | clubmate                       |
| fastlane-plugin-slack_train | 0.2.0   | slack_train slack_train_crash  |
|                             |         | slack_train_start              |
+-----------------------------+---------+--------------------------------+

[!] Could not find 'yolo123'. Available lanes: test, bump, generate_swift_api, release, verify_docs, update_docs, show_changelog
```

**Comment by taquitos** [comment]
Yeah, this isn't great.
