### ISSUE TITLE
[gym] Useless check of Xcode project when using `skip_build_archive`

### ISSUE THREAD

**Issue by kapfab** [fastlane/fastlane#11402]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`gym` expects to find an Xcode project file even when it is only requested to export from an existing archive and not to build the whole thing (`skip_build_archive` option).
As a quick workaround, we had to add to our lanes a dummy Xcode project file. We don't reference it anywhere but it is found by some global check which seems happy with it…

**Comment by KrauseFx** [comment]
Could you help me resolve this by running it again without the dummy project, with `--verbose`, and then when you get asked for the path, cancel with `control + c`, and share the output + stack trace? Thanks 👍

**Comment by kapfab** [comment]
Of course, there it is:
```
[✔] 🚀 
[11:06:21]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-01-04 11:06:21.76]: Checking if there are any plugins that should be loaded...
INFO [2018-01-04 11:06:21.92]: Driving the lane 'export_xcarchive' 🚀
INFO [2018-01-04 11:06:21.95]: -----------------
INFO [2018-01-04 11:06:21.95]: --- Step: gym ---
INFO [2018-01-04 11:06:21.95]: -----------------
 [2018-01-04 11:06:21.97]: Couldn't automatically detect the project file, please provide a path: ^CWARN [2018-01-04 11:11:11.09]: Lane Context:
INFO [2018-01-04 11:11:11.09]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"export_xcarchive"}
INFO [2018-01-04 11:11:11.09]: Successfully generated documentation at path '/usr/local/opt/moto/uploads/test/fastlane/README.md'

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 1    | gym    | 289         |
+------+--------+-------------+

ERROR [2018-01-04 11:11:11.14]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.4.0/gems/highline-1.7.10/lib/highline.rb:870:in `gets': Interrupt
	from /usr/local/lib/ruby/gems/2.4.0/gems/highline-1.7.10/lib/highline.rb:870:in `get_line'
	from /usr/local/lib/ruby/gems/2.4.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:104:in `input'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/project.rb:42:in `block in select_project'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/project.rb:41:in `loop'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/project.rb:41:in `select_project'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/project.rb:36:in `detect_projects'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/gym/lib/gym/detect_values.rb:15:in `set_additional_default_values'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/gym/lib/gym.rb:26:in `config='
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/gym/lib/gym/manager.rb:4:in `work'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/actions/build_ios_app.rb:65:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:35:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:343:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/cli_tools_distributor.rb:91:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.72.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```
And there is our test Fastfile:
```
lane :export_xcarchive do

  app_identifier = "com.company.testapp"
  app_provisioning_profile_identifier = "(PROD) Company Test"

  gym(
    skip_build_archive: true,
    skip_profile_detection: true,
    archive_path: "Product.xcarchive",
    export_team_id: "8BADC0FFEE",
    export_options: {
      provisioningProfiles: {
        app_identifier => app_provisioning_profile_identifier
      }
    }
  )

end
```

**Comment by KrauseFx** [comment]
Awesome, thanks, that was super helpful, I just pushed a PR that should fix it: https://github.com/fastlane/fastlane/pull/11449

Could you clone the repo and check out the branch and confirm that this change will make the setup work for you?

**Comment by kapfab** [comment]
You're welcome!
I'm afraid this change is not as straightforward as I expected…

I had to set the optional `output_name` parameter to prevent an error in `gym/lib/gym/detect_values.rb` (it tries to remove the ".ipa" extension from a null string, as output name can not be retrieved from the project file).

I have another error in `gym/lib/gym/runner.rb` (which makes use of `Gym.project.ios`, `Gym.project.tvos` and `Gym.project.macos`), but this will probably need some archive inspection to retrieve the same info.

Also, I guess `skip_profile_detection` has also to be set to true when using `skip_archive` as it also uses `Gym.project.path`.

I'll try to make some local changes to make sure all impacts are identified.

**Comment by KrauseFx** [comment]
@kapfab do you feel like it's worth the work + risk introducing the change, or is it good enough for your to have a dummy project for now?

**Comment by kapfab** [comment]
Well, it’s a quite ugly workaround but it seems to work for our current use cases and I guess there are more urgent issues for you to work on…
We will play on our side with the additional changes I’ve listed above and come back to you in a few days once I’ve made my mind regarding the complexity and risk.

**Comment by KrauseFx** [comment]
Yah, sorry that this happened, and sorry I don't have a better solution for your right now
