### ISSUE TITLE
Can't update code signing on cli to manual with action 'automatic_code_signing'

### ISSUE THREAD

**Issue by mkozjak** [fastlane/fastlane#11438]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane run automatic_code_signing path:"foo.xcodeproj" use_automatic_signing:false team_id:"foobar"

[12:19:16]: ------------------------------------
[12:19:16]: --- Step: automatic_code_signing ---
[12:19:16]: ------------------------------------

+-----------------------+------------------+
|    Summary for Automatic Codesigning     |
+-----------------------+------------------+
| path                  | uniqtv.xcodeproj |
| use_automatic_signing | false            |
| team_id               | M3KYHBA4RT       |
+-----------------------+------------------+


Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:321:in `configure_with_plist': [!] [!] Xcodeproj doesn't know about the following attributes {"refType"=>"0"} for the 'PBXFileReference' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:287:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:202:in `initialize_from_file'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:102:in `open'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/actions/automatic_code_signing.rb:10:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:231:in `block (2 levels) in run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:343:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/cli_tools_distributor.rb:91:in `take_off'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/bin/fastlane:20:in `<top (required)>'
	from /Users/mkozjak/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/mkozjak/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.72.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-01-05**
</details>

**Comment by mkozjak** [comment]
Might be related to CocoaPods/Xcodeproj#233.
Once I try opening pbxproj file manually with xcode, it kinda fixes the file, but adds a new line which fastlane also doesn't like: `Xcodeproj doesn't know about the following attributes {"name"=>"Compile Sources"} for the 'PBXSourcesBuildPhase' isa. (RuntimeError)`

**Comment by mkozjak** [comment]
Also, check CocoaPods/Xcodeproj#535.
