### ISSUE TITLE
remove_method: method app_id not defined in Spaceship

### ISSUE THREAD

**Issue by ciathyza** [fastlane/fastlane#11485]
Updated to latest Fastlane today, now getting this error when trying to launch fastlane:

$ fastlane

/Users/user/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.74.1/spaceship/lib/spaceship/base.rb:137:in `remove_method': method `app_id' not defined in Spaceship::TestFlight::Build (NameError)

Haven't changed anything else on the system other than the fastlane update. What was changed that makes the pipeline break yet again?

**Comment by ciathyza** [comment]
nevermind. problem disappeared by itself after a while.

**Comment by miloslavskacel** [comment]
```
$ fastlane env
[⠋] 🚀 /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/tty-screen-0.6.3/lib/tty/version.rb:3: warning: already initialized constant TTY::Screen::VERSION
/Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/tty-screen-0.6.3/lib/tty/version.rb:3: warning: previous definition of VERSION was here
[⠴] 🚀 /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-2.74.1/spaceship/lib/spaceship/base.rb:137:in `remove_method': method `app_id' not defined in Spaceship::TestFlight::Build (NameError)
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-2.74.1/spaceship/lib/spaceship/base.rb:137:in `block in attr_mapping'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-2.74.1/spaceship/lib/spaceship/base.rb:134:in `each'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-2.74.1/spaceship/lib/spaceship/base.rb:134:in `attr_mapping'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/fastlane-2.74.1/spaceship/lib/spaceship/test_flight/build.rb:62:in `<class:Build>'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/fastlane-2.74.1/spaceship/lib/spaceship/test_flight/build.rb:11:in `<module:TestFlight>'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/fastlane-2.74.1/spaceship/lib/spaceship/test_flight/build.rb:10:in `<module:Spaceship>'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/fastlane-2.74.1/spaceship/lib/spaceship/test_flight/build.rb:9:in `<top (required)>'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-2.74.1/fastlane_core/lib/fastlane_core/build_watcher.rb:1:in `<top (required)>'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/fastlane-2.74.1/fastlane_core/lib/fastlane_core.rb:30:in `require_relative'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/fastlane-2.74.1/fastlane_core/lib/fastlane_core.rb:30:in `<top (required)>'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/fastlane-2.74.1/fastlane/lib/fastlane.rb:1:in `<top (required)>'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/fastlane-2.74.1/fastlane/lib/fastlane/cli_tools_distributor.rb:33:in `take_off'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/gems/fastlane-2.74.1/bin/fastlane:20:in `<top (required)>'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/bin/fastlane:22:in `load'
	from /Users/rozumny/.rvm/rubies/ruby-2.2.4/bin/fastlane:22:in `<main>'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rozumny/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by AbeiOS** [comment]
I have the same problem. how to fix it?

**Comment by KrauseFx** [comment]
@miloslavskacel looks like a different error, check out and subscribe https://github.com/fastlane/fastlane/issues/11481

**Comment by Tayphoon** [comment]
When this fix will be released, all my fastlane builds broken :(

**Comment by KrauseFx** [comment]
Shipping in about 10 minutes, really sorry about that

**Comment by a455455b** [comment]
emmmmm,Is this bug fixed? all my fastlane builds broken :( ):

**Comment by KrauseFx** [comment]
Yep, new release is live. Does it not work @a455455b? Did you update?
