### ISSUE TITLE
interactive mode error with CircleCI v1.0

### ISSUE THREAD

**Issue by BenRx** [fastlane/fastlane#11547]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description and Environment

Hello ! 
We have encounted an issue since ~4 month with fastline in our CI system. We are using CircleCI v1.0 and we have already set those environment variables : 
`FASTLANE_PASSWORD`
`MATCH_PASSWORD`

**Our circle.yml :** 
```
general:
  artifacts:
    - ./build/

machine:
  xcode:
    version: 9.0
  environment:

dependencies:
  pre:
    - chruby system
    - sudo gem cleanup
    - sudo gem update spaceship
    - sudo gem update fastlane
    - sudo gem update gym
    - sudo gem install bundler
    - npm install -g firebase-tools
    - fastlane init
    - fastlane certificates
    - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development
  cache_directories:
    - vendor/bundle

test:
  pre:
    # Clone the submodule containing test data.
    - source scripts/prepareTests.sh
    - firebase init < /dev/null
  override:
    - fastlane build config:Integration

deployment:
  # When something is pushed on the integration branch, upload the
  # buildIntegration to HockeyApp and deploy the rules on the
  # integration-ios Firebase project.
  ...

  master:
    ...

  # Upload to App Store when a new tag is created.
  release:
    ...
```

**The output:**
```
[07:34:41]: fastlane detected a Gemfile in the current directory
[07:34:41]: however it seems like you don't use `bundle exec`
[07:34:41]: to launch fastlane faster, please use
[07:34:41]: 
[07:34:41]: $ bundle exec fastlane certificates --capture_output
[07:34:41]: 
[07:34:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2018-01-12 07:34:43.63]: Checking if there are any plugins that should be loaded...
INFO [2018-01-12 07:34:43.82]: -------------------------------------------------
INFO [2018-01-12 07:34:43.82]: --- Step: Verifying required fastlane version ---
INFO [2018-01-12 07:34:43.82]: -------------------------------------------------
INFO [2018-01-12 07:34:43.82]: Your fastlane version 2.61.0 matches the minimum requirement of 1.106.2  ✅
INFO [2018-01-12 07:34:43.83]: ------------------------------
INFO [2018-01-12 07:34:43.83]: --- Step: default_platform ---
INFO [2018-01-12 07:34:43.83]: ------------------------------
INFO [2018-01-12 07:34:43.83]: Driving the lane 'ios certificates' 🚀
INFO [2018-01-12 07:34:43.83]: -----------------------------
INFO [2018-01-12 07:34:43.83]: --- Step: setup_circle_ci ---
INFO [2018-01-12 07:34:43.83]: -----------------------------
INFO [2018-01-12 07:34:43.83]: Skipping Keychain setup as a keychain was already specified
INFO [2018-01-12 07:34:43.83]: Skipping Log Path setup as FL_OUTPUT_DIR is unset
INFO [2018-01-12 07:34:43.83]: -------------------
INFO [2018-01-12 07:34:43.83]: --- Step: match ---
INFO [2018-01-12 07:34:43.83]: -------------------
INFO [2018-01-12 07:34:43.86]: Successfully loaded '/Users/distiller/angel-ios/fastlane/Matchfile' 📄
DEBUG [2018-01-12 07:34:43.86]: Taking value for 'keychain_name' from environment variable 'MATCH_KEYCHAIN_NAME'
DEBUG [2018-01-12 07:34:43.86]: Taking value for 'keychain_password' from environment variable 'MATCH_KEYCHAIN_PASSWORD'
DEBUG [2018-01-12 07:34:43.86]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'
INFO [2018-01-12 07:34:43.87]: Cloning remote git repo...
INFO [2018-01-12 07:34:43.87]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-01-12 07:34:43.87]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:liberty-rider/angel-ios.git' '/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/d20180112-1211-k1tz0u'
INFO [2018-01-12 07:34:43.88]: ▸ Cloning into '/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/d20180112-1211-k1tz0u'...
INFO [2018-01-12 07:34:44.27]: ▸ remote: Counting objects: 20046, done.
INFO [2018-01-12 07:34:44.27]: ▸ remote: Compressing objects: 100% (5/5), done.
INFO [2018-01-12 07:35:03.16]: ▸ remote: Total 20046 (delta 4), reused 8 (delta 4), pack-reused 20037
INFO [2018-01-12 07:35:03.16]: ▸ Receiving objects: 100% (20046/20046), 360.40 MiB | 19.08 MiB/s, done.
INFO [2018-01-12 07:35:04.20]: ▸ Resolving deltas: 100% (13957/13957), done.
WARN [2018-01-12 07:35:06.01]: Migrating to new match...
INFO [2018-01-12 07:35:06.60]: Sending crash report...
INFO [2018-01-12 07:35:06.60]: The stack trace is sanitized so no personal information is sent.
INFO [2018-01-12 07:35:06.60]: To see what we are sending, look here: /Users/distiller/.fastlane/latest_crash.json
INFO [2018-01-12 07:35:06.60]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
INFO [2018-01-12 07:35:06.60]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
WARN [2018-01-12 07:35:06.60]: Lane Context:
INFO [2018-01-12 07:35:06.60]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios certificates"}
ERROR [2018-01-12 07:35:06.60]: This code should only run in interactive mode
INFO [2018-01-12 07:35:06.60]: Successfully generated documentation at path '/Users/distiller/angel-ios/fastlane/README.md'
ERROR [2018-01-12 07:35:06.61]: fastlane finished with errors
WARN [2018-01-12 07:35:06.97]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2018-01-12 07:35:07.14]: Checking if there are any plugins that should be loaded...
### Captured Output

Command Used: `certificates`
<details><summary>Output/Log</summary>

Successfully loaded Appfile at path '/Users/distiller/angel-ios/fastlane/Appfile'
- app_identifier: 'com.liberty-rider.liberty-rider'
- apple_id: 'ios-dev@liberty-rider.com'
- team_id: 'LNEA24X427'
-------

+---------+--------------------------------------------+
|     Detected Values from './fastlane/Matchfile'      |
+---------+--------------------------------------------+
| git_url | git@github.com:liberty-rider/angel-ios.git |
+---------+--------------------------------------------+


+-----------------------+-----------------------------------------------------------------------------------------------------------------------------+
|                                                              Summary for match 2.61.0                                                               |
+-----------------------+-----------------------------------------------------------------------------------------------------------------------------+
| type                  | development                                                                                                                 |
| app_identifier        | ["com.liberty-rider.liberty-rider.dev", "com.liberty-rider.liberty-rider.integ", "com.liberty-rider.liberty-rider.staging"] |
| force_for_new_devices | true                                                                                                                        |
| force                 | true                                                                                                                        |
| git_url               | git@github.com:liberty-rider/angel-ios.git                                                                                  |
| git_branch            | master                                                                                                                      |
| username              | xxxx@xxxxx.com                                                                                                   |
| keychain_name         | circle                                                                                                                      |
| keychain_password     | ********                                                                                                                    |
| readonly              | false                                                                                                                       |
| team_id               | xxxx                                                                                                                  |
| verbose               | false                                                                                                                       |
| skip_confirmation     | false                                                                                                                       |
| shallow_clone         | false                                                                                                                       |
| clone_branch_directly | false                                                                                                                       |
| skip_docs             | false                                                                                                                       |
| platform              | ios                                                                                                                         |
+-----------------------+-----------------------------------------------------------------------------------------------------------------------------+


+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | setup_circle_ci                     | 0           |
| 💥   | match                               | 22          |
+------+-------------------------------------+-------------+


Looking for related GitHub issues on fastlane/fastlane...
Search query: This code should only run in interactive mode

URL: https://api.github.com/search/issues?q=This%20code%20should%20only%20run%20in%20interactive%20mode+repo:fastlane/fastlane
➡️  fastlane cert --output_path doesn't generate p12 file
    https://github.com/fastlane/fastlane/issues/11009 [open] 13 💬
    a week ago

➡️  Fastlane Precheck fails with 'Failed: No broken urls-> unreachable URLs in app metadata'
    https://github.com/fastlane/fastlane/issues/11027 [open] 35 💬
    4 weeks ago

➡️  missing team id in non interactive mode still blocks
    https://github.com/fastlane/fastlane/issues/9154 [closed] 11 💬
    20 Aug 2017

and 11 more at: https://github.com/fastlane/fastlane/search?q=This%20code%20should%20only%20run%20in%20interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.6                                           |
| Ruby                        | 2.3.5                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.13.5 (Apple Git-94)                 |
| Installation Source         | ~/.gem/ruby/2.3.5/bin/fastlane                    |
| Host                        | Mac OS X 10.12.6 (16G29)                          |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.5/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-9.0.1.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   | fr_FR.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.106.2"

default_platform :ios

platform :ios do
 before_all do
    setup_circle_ci
  end
#      _ ______   ____  __
#   __| / ___\ \ / /  \/  |___
#  / _` \___ \\ V /| |\/| / __|
# | (_| |___) || | | |  | \__ \
#  \__,_|____/ |_| |_|  |_|___/

  desc "Dowload dsyms from iTunes Connect and push them to Crashlytics"
  #https://krausefx.com/blog/download-dsym-symbolication-files-from-itunes-connect-for-bitcode-ios-apps
  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

 #   ____          _   _  __ _           _
 #  / ___|___ _ __| |_(_)/ _(_) ___ __ _| |_ ___  ___
 # | |   / _ \ '__| __| | |_| |/ __/ _` | __/ _ \/ __|
 # | |__|  __/ |  | |_| |  _| | (_| (_| | ||  __/\__ \
 #  \____\___|_|   \__|_|_| |_|\___\__,_|\__\___||___/
 #

  desc "Get Liberty Rider certificates and provisioning profiles"
  lane :certificates do
    match(
      type: "development",
      app_identifier: [
        "com.liberty-rider.liberty-rider.dev",
        "com.liberty-rider.liberty-rider.integ",
        "com.liberty-rider.liberty-rider.staging"
      ],
      force_for_new_devices: true,
      force: true
    )
    match(
      type: "appstore",
      app_identifier: [
        "com.liberty-rider.liberty-rider",
      ],
      force_for_new_devices: true,
      force: true
    )
  end

  #  _____         _
  # |_   _|__  ___| |_
  #   | |/ _ \/ __| __|
  #   | |  __/\__ \ |_
  #   |_|\___||___/\__|
  #
  desc "Unit test of Liberty Rider, scheme Integration"
  lane :test do
    scan(
      scheme: "Liberty Rider - Integration",
      workspace: "Liberty Rider.xcworkspace",
      devices: ["iPhone 6s", "iPhone SE"],
      clean: true
    )
  end

  #   ____        _ _     _
  #  | __ ) _   _(_) | __| |
  #  |  _ \| | | | | |/ _` |
  #  | |_) | |_| | | | (_| |
  #  |____/ \__,_|_|_|\__,_|
  #

  desc "Build ipa"
  lane :build do |options|

    if options[:config] == "Integration"
      configuration = options[:config]
      gym(
        codesigning_identity: "iPhone Developer: iOS Developer Liberty Rider",
        scheme: "Liberty Rider - Integration",
        configuration: options[:config],
        output_name: "LibertyRider" + options[:config] + ".ipa",
        output_directory: "./build",
        include_symbols: true,
        include_bitcode: true,
        export_method: "enterprise"
      )
    end

    if options[:config] == "Staging"
      configuration = options[:config]
      gym(
        codesigning_identity: "iPhone Distribution: Liberty Rider",
        scheme: "Liberty Rider - Staging",
        configuration: options[:config],
        output_name: "LibertyRider" + options[:config] + ".ipa",
        include_symbols: true,
        include_bitcode: true
      )
    end

    if options[:config] == "Release"
      configuration = options[:config]
      gym(
        codesigning_identity: "iPhone Distribution: Liberty Rider",
        scheme: "Liberty Rider - Release",
        configuration: options[:config],
        output_name: "LibertyRider" + options[:config] + ".ipa",
        include_symbols: true,
        include_bitcode: true
      )
    end

  end

  #   ____             _
  #  |  _ \  ___ _ __ | | ___  _   _
  #  | | | |/ _ \ '_ \| |/ _ \| | | |
  #  | |_| |  __/ |_) | | (_) | |_| |
  #  |____/ \___| .__/|_|\___/ \__, |
  #             |_|            |___/
  #

  desc "Deploy to hockey or Testflight"
  lane :deploy do |options|



release_notes = sh("./../scripts/releaseNotes.sh")

    if options[:config] == "Integration"
      configuration = options[:config]
      build(config: configuration)
      hockey(
        api_token: ENV['HOCKEY_API_TOKEN'],
        ipa: './build/LibertyRider' + configuration + '.ipa',
        notes: release_notes,
        build_server_url: ENV['CIRCLE_BUILD_URL'],
        repository_url: ENV['CIRCLE_REPOSITORY_URL'],
      )
    end

    if options[:config] == "Staging"
      configuration = options[:config]
      build(config: configuration)
      hockey(
        api_token: ENV['HOCKEY_API_TOKEN'],
        ipa: './build/LibertyRider' + configuration + '.ipa',
        notes: release_notes,
        build_server_url: ENV['CIRCLE_BUILD_URL'],
        repository_url: ENV['CIRCLE_REPOSITORY_URL'],
      )
    end

    if options[:config] == "Release"
      configuration = options[:config]
      build(config: configuration)
      testflight(
        username: "ios-dev@liberty-rider.com",
        ipa: './build/LibertyRider' + configuration + '.ipa',
        skip_submission: true,
        skip_waiting_for_build_processing: true
      )
    end

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer


</details>

<details><summary>`./fastlane/Appfile`</summary>

ruby
app_identifier "com.xxxxx.xxxx" # The bundle identifier of your app
apple_id "xxxx@xxxxx.com" # Your Apple email address

team_id "xxxxxx"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md


</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.61.0  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| bundler                   | 1.16.1       |
</details>


*generated on:* **2018-01-12**
</details>
WARN [2018-01-12 07:35:07.16]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
INFO [2018-01-12 07:35:07.16]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

#######################################################################
# fastlane 2.75.1 is available. You are on 2.61.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.75.1 Bugfixes
* Add missing require statements for legacy spaceship (#11499) via Felix Krause
* Cache the homebrew repo on Circle  (#11489) via Manu Wallner
* Improve error handling when parse plist file (#11329) via Vinh Quốc Nguyễn
* Fix spaceship crash on some Ruby environments (#11493) via Felix Krause

2.75.0 Completely new fastlane onboarding
* Complete rewrite of the `fastlane init` onboarding flow (#11386) via Felix Krause
* Keep track of files modified when generating Swift API (#11482) via Joshua Liebowitz
* Update all remaining links that still linked to old GitHub docs (#11483) via Felix Krause
* Add tests to verify the built-in actions follow the conventions (#11332) via Felix Krause
* spaceship and deliver: add support for the new iPad (#11330) via Felix Krause
* Check for missing requires  (#11472) via Manu Wallner
* Pin ruby version on Circle (#11488) via Manu Wallner
* Add parentheses for all method calls (#11474) via Felix Krause

2.74.1 Bugfixes
* Handle old Swift FastlaneRunner commands (#11475) via Joshua Liebowitz
* release: use upcoming version number when generating swift files (relates to #11458) (#11467) via Jerome Lacoste

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem install fastlane`
/Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/match/lib/match/change_password.rb:41:in `ensure_ui_interactive': [!] This code should only run in interactive mode (RuntimeError)
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/match/lib/match/change_password.rb:5:in `update'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/match/lib/match/git_helper.rb:59:in `clone'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/match/lib/match/runner.rb:13:in `run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/actions/match.rb:12:in `run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:45:in `block (2 levels) in parsing_binding'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/distiller/.gem/ruby/2.3.5/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/distiller/.gem/ruby/2.3.5/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/distiller/.gem/ruby/2.3.5/gems/fastlane-2.61.0/bin/fastlane:20:in `<top (required)>'
	from /Users/distiller/.gem/ruby/2.3.5/bin/fastlane:22:in `load'
	from /Users/distiller/.gem/ruby/2.3.5/bin/fastlane:22:in `<main>'

fastlane certificates --capture_output returned exit code 1

Action failed: fastlane certificates --capture_output
```

I'd like to know if something appears to be wrong for you in my actual configuration because we didn't change anything and it worked until September.
Thanks 🙏

**Comment by mrtnrst** [comment]
I've seen this problem on and off with the CircleCI environment I work with. I was able to resolve the issue by creating a generic keychain and setting that as the default for match:

`    create_keychain(
      name: 'Generic-keychain',
      default_keychain: true,
      password: ENV['MATCH_PASSWORD'],
      unlock: true,
      timeout: false,
      lock_when_sleeps: true
    )
`

and after the all the scripts are run deleting the keychain with 
`delete_keychain(name: 'Generic-keychain')`

**Comment by BenRx** [comment]
@mrtnrst Hello !
First of all, thanks for your reply. I've just added your code in my fastfile but the problem still  seems to be there :/

```
#   ____          _   _  __ _           _
 #  / ___|___ _ __| |_(_)/ _(_) ___ __ _| |_ ___  ___
 # | |   / _ \ '__| __| | |_| |/ __/ _` | __/ _ \/ __|
 # | |__|  __/ |  | |_| |  _| | (_| (_| | ||  __/\__ \
 #  \____\___|_|   \__|_|_| |_|\___\__,_|\__\___||___/
 #

  desc "Get Liberty Rider certificates and provisioning profiles"
  lane :certificates do
    create_keychain(
      name: 'Generic-keychain',
      default_keychain: true,
      password: ENV['MATCH_PASSWORD'],
      unlock: true,
      timeout: false,
      lock_when_sleeps: true
    )
    match(
      type: "development",
      app_identifier: [
        "com.liberty-rider.liberty-rider.dev",
        "com.liberty-rider.liberty-rider.integ",
        "com.liberty-rider.liberty-rider.staging"
      ],
      force_for_new_devices: true,
      force: true
    )
    match(
      type: "appstore",
      app_identifier: [
        "com.liberty-rider.liberty-rider",
      ],
      force_for_new_devices: true,
      force: true
    )
  delete_keychain(name: 'Generic-keychain')
  end
```

Any idea ? 🙏

**Comment by taquitos** [comment]
Ok, I think I see 2 problems, the first being: It looks like this step is failing-
```
if !Helper.test? and GitHelper.match_version(@dir).nil? and manual_password.nil? and File.exist?(File.join(@dir, "README.md"))
        UI.important("Migrating to new match...")
```

And that has to do with some migration of old match to new match. Typically you run this on your local environment and commit the changes.


The other problem: I can see you're using fastlane `2.61` which is months old, probably because that's the system ruby's gem.

A good place to start is to use `bundle exec` when calling fastlane. That way you're using bundler instead of the super outdated fastlane.

**Comment by BenRx** [comment]
Hello ! Thanks for your reply ! 
I have correctly updated fastlane using bundle exec command and I completely removed my fastlane folder to recreate a new MatchFile, Appfile and Fastfile (with the same content for this one). I have removed my Gemfile and Gemfile.lock too to completely clean my project but the result is still the same... :(

**Comment by taquitos** [comment]
Oh sadness, can you post the newest result of `--capture_output`?
I'm trying to see if at the very least, the correct version of fastlane is being used

**Comment by jtcreative** [comment]
@BenRx did you do anything manual to your certificates or profiles on your developer account or match certificate repo?

**Comment by BenRx** [comment]
Hi !

Yup, indeed I signed my certificates manually and I think that was the problem. 
Now, I am using only Xcode managed profile to manage my dev team’s certificates and match to manage certificates that sign my app on testflight and it seems to work.

Thank you guys for your patience and your investment ! 🙇
