### ISSUE TITLE
Error running update_fastlane action

### ISSUE THREAD

**Issue by bdominguez** [fastlane/fastlane#11598]
When I ran update_fastlane action it successfully updates it but then I get an error (I know that its updating it because if I run it again it says that there are no updates):

```
[10:07:30]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:07:31]: Driving the lane 'android beta' 🚀
[10:07:31]: -----------------------------
[10:07:31]: --- Step: update_fastlane ---
[10:07:31]: -----------------------------
[10:07:31]: Looking for updates for fastlane...
[10:07:34]: Updating fastlane from 2.76.0 to 2.76.1... 🚀
+---------------+--------------+
|         Lane Context         |
+---------------+--------------+
| PLATFORM_NAME | android      |
| LANE_NAME     | android beta |
+---------------+--------------+
[10:08:00]: error generating Scan/DetectValues.html: no implicit conversion of nil into String (TypeError)

+------+-----------------+-------------+
|           fastlane summary           |
+------+-----------------+-------------+
| Step | Action          | Time (in s) |
+------+-----------------+-------------+
| 💥   | update_fastlane | 28          |
+------+-----------------+-------------+

[10:08:00]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

#######################################################################
# fastlane 2.76.1 is available. You are on 2.76.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.76.1 Fix for crash during fastlane init
* Fix for missing variable in setup_ios.rb (#11587) via Joshua Liebowitz
* Update scan test result poster to use new slack API (#11591) via Felix Krause
* Add link to all contributors in README (#11581) via Felix Krause
* Version bump to 2.76.1 (#11589) via Joshua Liebowitz

Please update using `sudo gem install fastlane`
/usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/token_stream.rb:64:in `escapeHTML': [!] error generating Scan/DetectValues.html: no implicit conversion of nil into String (TypeError) (RDoc::Error)
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/token_stream.rb:64:in `block in to_html'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/token_stream.rb:19:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/token_stream.rb:19:in `to_html'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/markup.rb:114:in `markup_code'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:168:in `block (5 levels) in generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:125:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:125:in `block (4 levels) in generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:118:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:118:in `block (3 levels) in generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:116:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:116:in `block (2 levels) in generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/context.rb:765:in `block in each_section'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/context.rb:764:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/context.rb:764:in `each_section'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:54:in `block in generate_class'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:753:in `template_result'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:732:in `block in render_template'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:727:in `open'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:727:in `open'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:727:in `render_template'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:356:in `generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:382:in `block in generate_class_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:379:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:379:in `generate_class_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:246:in `generate'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:137:in `block in document'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:134:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:134:in `document'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:196:in `generate'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:55:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:55:in `generation_hook'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/request_set.rb:206:in `block in install'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/request_set.rb:205:in `each'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/request_set.rb:205:in `install'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/dependency_installer.rb:409:in `install'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/commands/update_command.rb:213:in `update_gem'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/actions/update_fastlane.rb:73:in `block in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/actions/update_fastlane.rb:59:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/actions/update_fastlane.rb:59:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:2:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:288:in `execute_flow_block'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/fastlane/lib/fastlane/cli_tools_distributor.rb:94:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.76.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'`

**Comment by janpio** [comment]
What command are you running here?
Is it possible that you have two fastlane installations, one with sudo and one without?

**Comment by bdominguez** [comment]
I'm running "fastlane" command and on Fastfile I have:

before_all do
  update_fastlane
end

How can I see if I have two fastlane installations?

**Comment by janpio** [comment]
I am not sure tbh - I am a newb on these problems as well. Try `sudo which fastlane`.
Or see what happens if you do `sudo gem install fastlane` vs. `gem install fastlane`.

**Comment by bdominguez** [comment]
running:

sudo which fastlane and which fastlane I get the same result.

**Comment by hernangonzalez** [comment]
I get the same error updating my gems. I just run it twice, and the it goes though. Although it is weird..

**Comment by bdominguez** [comment]
I'm still having the same problem, it successfully updates (the second attempt doesn't update anything so the previous attempt succeeded) but I get an error:

```
[11:51:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:51:01]: Driving the lane 'android alpha' ðŸš€
[11:51:01]: -----------------------------
[11:51:01]: --- Step: update_fastlane ---
[11:51:01]: -----------------------------
[11:51:01]: Looking for updates for fastlane...
[11:51:04]: Updating fastlane from 2.80.0 to 2.81.0... ðŸš€
+---------------+---------------+
|         Lane Context          |
+---------------+---------------+
| PLATFORM_NAME | android       |
| LANE_NAME     | android alpha |
+---------------+---------------+
[11:51:28]: error generating Scan/DetectValues.html: no implicit conversion of nil into String (TypeError)

+------+-----------------+-------------+
|           fastlane summary           |
+------+-----------------+-------------+
| Step | Action          | Time (in s) |
+------+-----------------+-------------+
| ðŸ’¥   | update_fastlane | 26          |
+------+-----------------+-------------+

[11:51:28]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

âž¡ï¸�  RDOC error when installing with gem
    https://github.com/fastlane/fastlane/issues/11629 [open] 5 ðŸ’¬
    3 weeks ago

âž¡ï¸�  Error running update_fastlane action
    https://github.com/fastlane/fastlane/issues/11598 [open] 6 ðŸ’¬
    4 weeks ago

ðŸ”—  You can âŒ˜ + double-click on links to open them directly in your browser.

#######################################################################
# fastlane 2.81.0 is available. You are on 2.80.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.81.0 Swift and other improvements
* Prioritize user's lane over actions (#11786) via Felix Krause
* Make name conflict error message more obvious (#11787) via Felix Krause
* Generate more idomatic screenshots.html file when using screengrab. (#11811) via Niklas Baudy
* Fastlane.swift: Fix default type for Integer parameters (#11793) via Thi
* Fastlane.swift: Changing type of activeDaysLimit to Int to creathe pushcertificates (#11791) via Johannes BoÃŸ
* Include contents of BCSymbolMaps directory in dSYM.zip file. (#11771) via Peder Toftegaard Olsen
* Screengrab + snapshot: Also allow h + l for navigating between screenshots. (#11817) via Niklas Baudy
* Fix erroneous success message during setup (#11810) via Patrick Nollet
* Option to upload symbols to Firebase Crashlytics via GoogleService-Info.plist (#11798) via Jonas Rottmann
* changed cert checker to use ruby openssl to generate sha1 fingerprint (#11652) via Cyberbeni
* [match/utils] using ruby openssl instead of terminal version (#11720) via Cyberbeni
* [match] using ruby openssl instead of terminal one (#11641) via Cyberbeni
* pilot - added changelog validation (#11777) via Rishabh Tayal
* Make sure that the local testing docs is the same (#11775) via Iulian Onofrei
* Forcing ASCII for this ASCII encoded certificate (#11770) via Jonathan Arbogast

Please update using `sudo gem install fastlane`
/usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/token_stream.rb:64:in `escapeHTML': [!] error generating Scan/DetectValues.html: no implicit conversion of nil into String (TypeError) (RDoc::Error)
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/token_stream.rb:64:in `block in to_html'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/token_stream.rb:19:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/token_stream.rb:19:in `to_html'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/markup.rb:114:in `markup_code'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:168:in `block (5 levels) in generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:125:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:125:in `block (4 levels) in generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:118:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:118:in `block (3 levels) in generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:116:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:116:in `block (2 levels) in generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/context.rb:765:in `block in each_section'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/context.rb:764:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/context.rb:764:in `each_section'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/template/darkfish/class.rhtml:54:in `block in generate_class'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:753:in `template_result'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:732:in `block in render_template'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:727:in `open'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:727:in `open'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:727:in `render_template'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:356:in `generate_class'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:382:in `block in generate_class_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:379:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:379:in `generate_class_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/generator/darkfish.rb:246:in `generate'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:137:in `block in document'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:134:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:134:in `document'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:196:in `generate'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:55:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rubygems_hook.rb:55:in `generation_hook'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/request_set.rb:206:in `block in install'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/request_set.rb:205:in `each'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/request_set.rb:205:in `install'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/dependency_installer.rb:409:in `install'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/commands/update_command.rb:213:in `update_gem'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/update_fastlane.rb:73:in `block in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/update_fastlane.rb:59:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/update_fastlane.rb:59:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:2:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:288:in `execute_flow_block'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.80.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by bdominguez** [comment]
I still have the same problem so its not resolved in the latest version.

**Comment by bdovaz** [comment]
#11629 It seems related to this issue.
