### ISSUE TITLE
Error on raise_if_conflicts

### ISSUE THREAD

**Issue by YannickSteph** [fastlane/fastlane#11657]
### New Issue Checklist

- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)

### Issue Description

I try use the supply command, but I got an error. It shows conflict. I uninstall/Install/Update fastlane and ruby from my system. But still the same problem. 

```
fastlane finished with errors
/Users/**/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate xcov-1.3.0, because slack-notifier-2.3.2 conflicts with slack-notifier (~> 1.3) (Gem::ConflictError)
	from /Users/**/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1408:in `activate'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems.rb:196:in `rescue in try_activate'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems.rb:193:in `try_activate'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/actions/xcov.rb:41:in `available_options'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/configuration_helper.rb:4:in `parse'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:237:in `block (2 levels) in execute_action'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:148:in `test_cov'
	from Fastfile:52:in `block (2 levels) in parsing_binding'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
	from /Users/**/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/**/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.78.0"
default_platform :ios

### Fastlane methods
ENV["CRASHLYTICS_API_TOKEN"]    = "***"
ENV["CRASHLYTICS_BUILD_SECRET"] = "**"
ENV["SLACK_URL"]                = "**"

platform :ios do

  ### Pull Request Analysis ###

  # Check Pull Request Analysis
  desc "Pull Request Analysis"
  lane :analysis_pull_request do |options|
    begin
      notification_display("🚀 Begin analysis 📦", "")
      clear_derived_data
      test_scan() 
      test_cov()
    rescue => e
      notification_display("❌ Fail analysis 🚩", e.error_info.to_s)
    end
    notification_display("✅ Successful analysis 🎉", "")
  end

  # Check Pull Request Analysis by bitrise
  desc "Pull Request Analysis"
  lane :analysis_pull_request_bitrise do |options|
    clear_derived_data
    begin
      test_scan()
    rescue => exception 
      on_error("❌ Fail tests 🚩", exception)
      sleep(0.5)
      raise exception
    end
    begin
      test_cov()
    rescue => exception 
      on_error("❌ Fail covorage 🚩", exception)
      sleep(0.5)
      raise exception
    end
  end

  # Build to send fabric
  desc "Build and submit to Fabric"
  lane :build_beta do |options|
      notification_display("🚀 Begin send to fabric 📦", "📲")
      begin
        begin
          cert(development: true)
          sigh(development: true)
          clear_derived_data
        rescue => exception 
          notification_display("❌ Fail Cert and sign 🚩", "📲")
          raise exception
        end

        begin
          gen_ipa_staging()
        rescue => exception 
          notification_display("❌ Fail on Gen IPA 🚩", "📲")
          raise exception
        end

        begin
          gen_crashlytics_team_deployment()
        rescue => exception 
          notification_display("❌ Fail on Gen crashlytics 🚩", "📲")
          raise exception
        end
        notification_display("✅ Successful send to fabric 🎉", "📦")
      rescue => exception 
        notification_display("❌ Fail Gen IPA 🚩", "📲")
      end
  end  


end

### Methods

### Gen fabric build team deployment
def gen_crashlytics_team_deployment
  begin
    crashlytics(
      notification:                       true,
      debug:                              true,                     
      ipa_path:                           "beta.ipa",
      groups:                             "***",
      skip_waiting_for_build_processing:  true
    )
  rescue => exception 
    raise exception
  end
end

### Gen Build Staging

def gen_ipa_staging
  begin
    gym(
      configuration:        "**",
      workspace:            "**.xcworkspace",
      scheme:               "**",
      output_name:          "beta.ipa",
      silent:               true,      
      clean:                true,
      include_bitcode:      true
    )
  rescue => exception 
    raise exception
  end
end

### Test UX
def test_scan
  begin
    scan(
      configuration:      "Staging",
      workspace:          "**.xcworkspace",
      scheme:             "**",      
      device:             "iPhone 6"
    )
  rescue => exception 
    raise exception
  end
end

### Test Covorage
def test_cov
  begin
    xcov(
      workspace:                    "**",
      configuration:                "**",
      scheme:                       "**",
      output_directory:             "./fastlane/xcov_output",
      html_report:                  true,
      include_targets:              "**",
      minimum_coverage_percentage:  "98.0",
      slack_username:               "Bitrise CI",
      slack_url:                    "**"
    )
  rescue => exception 
    raise exception
  end
end

##### Slack display #####

def notification_display(title, message) 
  notification(
    subtitle: title, 
    message:  message,
    app_icon: "**"
  )
end

def on_error(title, exception)
  slack(
    message:           title,
    success:           false,
    slack_url:         "**",
    default_payloads:  [:git_branch, :last_git_commit_hash, :lane],
    username:          "Bitrise CI",
    icon_url:          "https://i.imgur.com/6gDn65n.jpg",
    attachment_properties: {
      fields: [
        {
          title: exception.error_info.to_s,
          value: exception.to_s,
          short: false
        }
      ]
    }
  )
end

# Display success message
def slack_display_success(title) 
  slack(
    message:           title,
    success:           true,
    slack_url:         "**",
    default_payloads:  [:git_branch, :last_git_commit_hash, :lane],
    username:          "Bitrise CI",
    icon_url:          "https://i.imgur.com/8dT2ynG.jpg"
  )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.13.6       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 2.3.2        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.5.0        |
| tty-screen                | 0.6.4        |
| tty-spinner               | 0.8.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.3        |
| xcov                      | 1.3.0        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2018-01-22**
</details>

**Comment by KrauseFx** [comment]
Have you tried using a `Gemfile` and using `bundle exec`? https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

**Comment by YannickSteph** [comment]
i have create the `Gemfile` and install. But now i have this error.


```
Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Fastfile:185:in `on_error': [!] undefined method `error_info' for #<FastlaneCore::Interface::FastlaneDependencyCausedException:0x007fc5189dcf08> (NoMethodError)
	from Fastfile:47:in `rescue in block (2 levels) in parsing_binding'
	from Fastfile:44:in `block (2 levels) in parsing_binding'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
	from /Users/**/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/**/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by YannickSteph** [comment]
i have create the `Gemfile` and install. But now i have this error.


```
fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Fastfile:35:in `rescue in block (2 levels) in parsing_binding': [!] undefined method `error_info' for #<FastlaneCore::Interface::FastlaneBuildFailure:0x007fd0cd29ae00> (NoMethodError)
	from Fastfile:29:in `block (2 levels) in parsing_binding'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/**/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
	from /Users/**/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/**/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by KrauseFx** [comment]
Looks great:
```
Fastfile:35:in `rescue in block (2 levels) in parsing_binding': [!] undefined method `error_info'
```

This is an error in your Fastfile 👍

**Comment by KrauseFx** [comment]
```
      notification_display("❌ Fail analysis 🚩", e.error_info.to_s)
```


try
```
      notification_display("❌ Fail analysis 🚩", e.to_s)

```

**Comment by joshdholtz** [comment]
@YannickSteph Are you running this like `bundle exec fastlane <lane_name>`?

**Comment by joshdholtz** [comment]
@YannickSteph Going to close this issue as it looks like the `Gemfile` fixed your error and now its an error in your `Fastfile`. But feel free to comment here if this is still an issue and we can reopen!
