### ISSUE TITLE
Fastlane suddenly started hanging on start

### ISSUE THREAD

**Issue by hammertoe** [fastlane/fastlane#1183]
Working on deployment stuff today and then all of a sudden fastlane hangs on start on our Mac Mini builds server with El Capitain. Tried rebooting it, not help.

Seems eventually it returns, but takes several minutes. e.g.:

```
Ghyston:workspace iosbuilds$ time fastlane lanes
[20:22:54]: -------------------------------------------------
[20:22:54]: --- Step: Verifying required fastlane version ---
[20:22:54]: -------------------------------------------------
[20:22:54]: fastlane version valid
[20:22:54]: ------------------------------
[20:22:54]: --- Step: default_platform ---
[20:22:54]: ------------------------------

--------- ios---------
----- fastlane ios tests

----- fastlane ios build

----- fastlane ios alpha

----- fastlane ios build_alpha

----- fastlane ios deploy_alpha

----- fastlane ios build_release

----- fastlane ios deploy_release

Execute using `fastlane [lane_name]`

real	3m11.084s
user	3m7.640s
sys	0m3.250s
Ghyston:workspace iosbuilds$ md5 fastlane/Fastfile
MD5 (fastlane/Fastfile) = d6589096ebb11d352402e9efcc0817d8
```

versus running the same Fastlane setup on my laptop:

```
Matts-MacBook-Air:mib.ios.nutrition matt$ time fastlane lanes
[12:23:00]: -------------------------------------------------
[12:23:00]: --- Step: Verifying required fastlane version ---
[12:23:00]: -------------------------------------------------
[12:23:00]: fastlane version valid
[12:23:00]: ------------------------------
[12:23:00]: --- Step: default_platform ---
[12:23:00]: ------------------------------

--------- ios---------
----- fastlane ios tests

----- fastlane ios build

----- fastlane ios alpha

----- fastlane ios build_alpha

----- fastlane ios deploy_alpha

----- fastlane ios build_release

----- fastlane ios deploy_release

Execute using `fastlane [lane_name]`

real	0m5.599s
user	0m4.663s
sys	0m0.606s
Matts-MacBook-Air:mib.ios.nutrition matt$ md5 fastlane/Fastfile
MD5 (fastlane/Fastfile) = d6589096ebb11d352402e9efcc0817d8
```

**Comment by hammertoe** [comment]
If I interrupt it when it is 'hung' this is the stack trace:

```
^C/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1396:in `block (2 levels) in contains_requirable_file?': Interrupt
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1396:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1396:in `any?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1396:in `block in contains_requirable_file?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1394:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1394:in `any?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1394:in `contains_requirable_file?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:890:in `block (2 levels) in find_in_unresolved_tree'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2317:in `[]'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2317:in `block (2 levels) in traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2316:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2316:in `block in traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2315:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2315:in `traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2318:in `block (2 levels) in traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2316:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2316:in `block in traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2315:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2315:in `traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2318:in `block (2 levels) in traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2316:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2316:in `block in traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2315:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2315:in `traverse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:888:in `block in find_in_unresolved_tree'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:886:in `reverse_each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:886:in `find_in_unresolved_tree'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:93:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.52.0/lib/fastlane/actions/actions_helper.rb:68:in `block in load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.52.0/lib/fastlane/actions/actions_helper.rb:67:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.52.0/lib/fastlane/actions/actions_helper.rb:67:in `load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.52.0/lib/fastlane.rb:24:in `<module:Fastlane>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.52.0/lib/fastlane.rb:20:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.52.0/bin/fastlane:6:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by hammertoe** [comment]
Aha! I did a `sudo gem cleanup` and suddenly all is fine now. No idea why this suddenly happened and why it jumped to many minutes to start ruby.
