### ISSUE TITLE
Match::Utils.get_cert_info breaking from 2.80.0 to 2.81.0

### ISSUE THREAD

**Issue by pangers** [fastlane/fastlane#11885]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Match::Utils.get_cert_info seems to break when upgrading from 2.80.0 to 2.81.0.

Fastfile to reproduce issue looks like:

```
desc "Get certificate name"
  lane :get_name do
    certificate = Match::Utils.get_cert_info("path-to-`.cer`-file")
    full_common_name_array = certificate[1]
    full_common_name = full_common_name_array[1]
    puts "Certificate name is #{full_common_name}".blue
  end
```
Replace "path-to-`.cer`-file" with an actual path.

##### Complete output when running fastlane, including the stack trace and command used
When running the above in 2.80.0

```
[✔] 🚀 
[17:06:59]: ----------------------------------------
[17:06:59]: --- Step: Verifying fastlane version ---
[17:06:59]: ----------------------------------------
[17:06:59]: Your fastlane version 2.80.0 matches the minimum requirement of 2.80.0  ✅
[17:06:59]: ------------------------------
[17:06:59]: --- Step: default_platform ---
[17:06:59]: ------------------------------
[17:07:00]: Driving the lane 'ios get_name' 🚀
[17:07:00]: Certificate name is iPhone Distribution: David Smith (3W2L7QF026)

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
+------+----------------------------+-------------+

[17:07:00]: fastlane.tools finished successfully 🎉
```

When running the same Fastfile in 2.81.0

```
[✔] 🚀 
[17:10:30]: ----------------------------------------
[17:10:30]: --- Step: Verifying fastlane version ---
[17:10:30]: ----------------------------------------
[17:10:30]: Your fastlane version 2.81.0 matches the minimum requirement of 2.80.0  ✅
[17:10:30]: ------------------------------
[17:10:30]: --- Step: default_platform ---
[17:10:30]: ------------------------------
[17:10:30]: Driving the lane 'ios get_name' 🚀
[17:10:30]: undefined method `append' for #<Array:0x007f8eda07c950>
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | ios          |
| PLATFORM_NAME    | ios          |
| LANE_NAME        | ios get_name |
+------------------+--------------+
[17:10:30]: undefined method `[]' for nil:NilClass

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
+------+----------------------------+-------------+

[17:10:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Undefined method `in_app_purchases' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11883 [open] 2 💬
    8 hours ago

➡️  nuke development [!] undefined method `strftime' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/11630 [open] 3 💬
    4 weeks ago

➡️  undefined method `build_settings' for nil:NilClass Error
    https://github.com/fastlane/fastlane/issues/11168 [open] 6 💬
    2 weeks ago

and 327 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Fastfile:76:in `block (2 levels) in parsing_binding': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/gems/fastlane-2.81.0/bin/fastlane:20:in `<top (required)>'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/bin/fastlane:22:in `load'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/bin/fastlane:22:in `<main>'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/james.pang/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

Perhaps there is a better way to get the Common name of a certificate?

**Comment by minuscorp** [comment]
This is solved by https://github.com/fastlane/fastlane/pull/11838, you can use fastlane on its `master` branch or wait a a couple of days for a new release!

**Comment by pangers** [comment]
Ah ok cheers, I'll look out for the next release. Ill close this issue.
