### ISSUE TITLE
Cannot add internal users

### ISSUE THREAD

**Issue by Alarson93** [fastlane/fastlane#11952]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to figure out how to add internal testers via Fastlane (probably using pilot?). I've read a few threads on the matter and can see support of some kind was added in #9002.

I'm having no luck though. Let's ignore my Fastlane script and output consider that this is reproducible using command-line. 

Ideally I would like to provide an email (not yet associated with the account) and add it as a brand new internal tester and then add the new user as a tester of the app, but I would settle for adding an internal tester (already associated with the account) to the app.

I'm using the following command:
`fastlane pilot add -e foo@foobar.com -a com.potato.app --distribute_external false`

##### Output (after the ITC login prompt)
```
[15:10:59]: You must provide 1 or more groups (with the `:groups` option)
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.83.0/fastlane_core/lib/fastlane_core/ui/interface.rb:133:in `user_error!': Some operations failed: You must provide 1 or more groups (with the `:groups` option) (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.83.0/fastlane_core/lib/fastlane_core/ui/ui.rb:16:in `method_missing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.83.0/pilot/lib/pilot/commands_generator.rb:44:in `handle_multiple'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.83.0/pilot/lib/pilot/commands_generator.rb:101:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:69:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.83.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.83.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-2.0.0/bin/pilot:13:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'
```

**Comment by Alarson93** [comment]
Thank you for your suggestion Fastlane Bot lol
To all those that read this - I emphasize that I don't feel the Fastlane environment is necessary given the reproducibility of this from a single command.

**Comment by Alarson93** [comment]
I would still appreciate some input on this.
Basically I want to be able to add internal testers to a given app. Is that possible in the current version of Fastlane and, if not, is it a feature that could be added in a future release?
