### ISSUE TITLE
Downloading metadata with appletvos crash

### ISSUE THREAD

**Issue by fassko** [fastlane/fastlane#11969]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Downloading metadata for **appletvos** crash. I understand that it's not available, but would be nice to give a error message.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>» fastlane deliver download_metadata
[✔] 🚀
[16:44:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:44:40]: Successfully loaded '/Users/kristaps/Documents/qminder/qminder-tv/fastlane/Deliverfile' 📄

+-----------------------+-----------------------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------------+-----------------------+
| platform              | appletvos             |
+-----------------------+-----------------------+

[16:44:40]: Login to iTunes Connect (ios-dev@qminderapp.com)
[16:44:43]: Login successful

+--------------------------------------+------------------------+
|                    deliver 2.84.0 Summary                     |
+--------------------------------------+------------------------+
| screenshots_path                     | ./fastlane/screenshots |
| metadata_path                        | ./fastlane/metadata    |
| app_version                          | 1.40                   |
| username                             | ios-dev@qminderapp.com |
| app_identifier                       | com.qminderapp.connect |
| edit_live                            | false                  |
| ipa                                  | qminder-tv.ipa         |
| platform                             | appletvos              |
| skip_binary_upload                   | false                  |
| use_live_version                     | false                  |
| skip_screenshots                     | false                  |
| skip_metadata                        | false                  |
| skip_app_version_update              | false                  |
| force                                | false                  |
| submit_for_review                    | false                  |
| automatic_release                    | false                  |
| phased_release                       | false                  |
| dev_portal_team_id                   | XT7W2QD6JZ             |
| overwrite_screenshots                | false                  |
| run_precheck_before_submit           | true                   |
| precheck_default_rule_level          | warn                   |
| ignore_language_directory_validation | false                  |
| precheck_include_in_app_purchases    | true                   |
+--------------------------------------+------------------------+

[16:44:43]: Do you want to overwrite existing metadata on path
'/Users/kristaps/Documents/qminder/qminder-tv/fastlane/metadata'? (y/n)
y

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.84.0/deliver/lib/deliver/commands_generator.rb:172:in `block (2 levels) in run': [!] Neither the current nor live version match specified app_version "1.40" (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.84.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.84.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.84.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.84.0/fastlane/lib/fastlane/cli_tools_distributor.rb:90:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.84.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D47)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

default_platform :appletvos
update_fastlane

platform :ios do

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: "qminder-tv.xcworkspace",
      scheme: "qminder-tv",
      devices: ["Apple TV 1080p"]
      # destination: "platform=tvOS Simulator,name=Apple TV 1080p,OS=10.2",
    )
  end

  desc "Build"
  lane :build do
    increment_build_number build_number: get_version_number + "." + Time.new.strftime("%y%m%d.%H%M")

    gym(
      workspace: "qminder-tv.xcworkspace",
      scheme: "qminder-tv",
      clean: true
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    build
    deploy_to_testflight
  end

  desc "Download dSYMs and upload to Testflight"
  lane :dsyms do
    download_dsyms(
      platform: "appletvos",
      version: "latest"
    )
    upload_symbols_to_crashlytics(
      api_token: "TOKEN",
      platform: "appletvos"
    )
    clean_build_artifacts
  end

  desc "Testflight"
  lane :deploy_to_testflight do
    testflight(
      skip_waiting_for_build_processing: true,
      app_platform: "appletvos"
    )
  end

  desc "Provisional profiles"
  lane :provisional_profiles do
    sigh(
      platform: :tvos,
      development: false
    )

    sigh(
      platform: :tvos,
      development: true
    )
  end

  desc "Register devices"
  lane :register_test_devices do
    # register devices
    register_devices(devices_file: "./fastlane/devices.txt")
  end

  desc "Create certificates"
  lane :certificates do
    unlock_keychain(path: "login")

    register_test_devices

    match(type: "adhoc", app_identifier: ["com.qminderapp.connect"], force_for_new_devices: true)
    match(type: "appstore", app_identifier: ["com.qminderapp.connect"])
    match(type: "development", app_identifier: ["com.qminderapp.connect"], force_for_new_devices: true)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    ensure_git_branch
    version = get_version_number
    changelog = changelog_from_git_commits(merge_commit_filtering: "exclude_merges")

    github_release = set_github_release(
      repository_name: "Qminder/qminder-tv",
      api_token: ENV['GITHUB_TOKEN'],
      name: version,
      tag_name: version,
      description: changelog,
      commitish: "master"
    )
    sh("git fetch --tags")
  end

  desc "Swiftlint"
  lane :lint do
    swiftlint(
      mode: :lint,                            # SwiftLint mode: :lint (default) or :autocorrect
      executable: "Pods/SwiftLint/swiftlint", # The SwiftLint binary path (optional). Important if you've installed it via CocoaPods
      output_file: "swiftlint.result.json",   # The path of the output file (optional)
      reporter: "json",                       # The custom reporter to use (optional)
      config_file: ".swiftlint-ci.yml",       # The path of the configuration file (optional)
      ignore_exit_status: true                # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.qminderapp.connect" # The bundle identifier of your app
apple_id "ios-dev@qminderapp.com" # Your Apple email address

team_id "XT7W2QD6JZ"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.84.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.57.1       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.2       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-03-02**
</details></pre>
</details>

**Comment by fassko** [comment]
If someone can help a bit I could improve this this check for this or other actions which are not available for tvOS.
