### ISSUE TITLE
Could not retrieve response as fastlane runs in non-interactive mode while using fastlane match nuke development

### ISSUE THREAD

**Issue by zerozheng** [fastlane/fastlane#12028]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

ruby-2.3.4
fastlane-2.85.0

When use `match nuke development`, error occurred.

```
[22:49:18]: ---
[22:49:18]: Are you sure you want to completely delete and revoke all the
[22:49:18]: certificates and provisioning profiles listed above? (y/n)
[22:49:18]: Warning: The :app_identifier value will be ignored - this will delete all profiles for all your apps!
[22:49:18]: ---
[22:49:18]: Do you really want to nuke everything listed above?

Looking for related GitHub issues on fastlane/fastlane...

➡️  Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/12011 [open] 2 💬
    2 days ago

➡️  Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
    https://github.com/fastlane/fastlane/issues/11802 [open] 5 💬
    20 hours ago

➡️  FR : Improve non interactive mode for latest_testflight_build_number
    https://github.com/fastlane/fastlane/issues/10772 [open] 5 💬
    3 weeks ago

and 26 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/interface.rb:121:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:140:in `verify_interactive!'
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:118:in `confirm'
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/match/lib/match/nuke.rb:52:in `run'
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/match/lib/match/commands_generator.rb:139:in `block (3 levels) in run'
	from /Users/zero/.rvm/gems/ruby-2.3.4@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/zero/.rvm/gems/ruby-2.3.4@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/zero/.rvm/gems/ruby-2.3.4@global/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/zero/.rvm/gems/ruby-2.3.4@global/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/match/lib/match/commands_generator.rb:146:in `run'
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/match/lib/match/commands_generator.rb:19:in `start'
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/fastlane/lib/fastlane/cli_tools_distributor.rb:90:in `take_off'
	from /Users/zero/.rvm/gems/ruby-2.3.4/gems/fastlane-2.85.0/bin/fastlane:20:in `<top (required)>'
	from /Users/zero/.rvm/gems/ruby-2.3.4/bin/fastlane:23:in `load'
	from /Users/zero/.rvm/gems/ruby-2.3.4/bin/fastlane:23:in `<main>'
	from /Users/zero/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/zero/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

I can't type any information, like `y` or `n`, into the *zsh* terminal when it ask me `Are you sure you want to completely delete and revoke all the certificates and provisioning profiles listed above? (y/n)`. 
The terminal just list all the information include the error and can't be interactive on the whole time until end.

what's happen?

Update: fastlane env

```
<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>
```

**Comment by zerozheng** [comment]
Is there anyone could help me?

**Comment by zerozheng** [comment]
@kommen @cbowns @andrew @brad

**Comment by joshdholtz** [comment]
@zerozheng Try running `match nuke development --skip_confirmation` or `match nuke development --skip_confirmation true` (one of those should work for you). That option was added in this PR (https://github.com/fastlane/fastlane)

And can be found by running `fastlane match help`

<img width="1039" alt="screen shot 2018-03-13 at 8 45 54 am" src="https://user-images.githubusercontent.com/401294/37345439-f7363bf0-269a-11e8-9d16-8569a0a3d4fd.png">

Happy fastlaning 🚀
