### ISSUE TITLE
各位好，我在使用fastlane上传ipa包时出现了这个错误一直解决不了

### ISSUE THREAD

**Issue by zuqiu123** [fastlane/fastlane#12143]
[✔] Activating language zh-Hans... 
[✔] Uploading metadata to iTunes Connect 
[16:43:44]: Successfully uploaded set of metadata to iTunes Connect
[16:43:47]: Starting with the upload of screenshots...
[✔] Activating language zh-Hans... 
[16:43:52]: Uploading 3 screenshots for language zh-Hans
[16:43:52]: Uploading './fastlane/screenshots/zh-Hans/1_iphone6Plus_1.11.png'...
[16:43:57]: Uploading './fastlane/screenshots/zh-Hans/2_iphone6Plus_2.22.png'...
[16:44:05]: Uploading './fastlane/screenshots/zh-Hans/3_iphone6Plus_3.33.png'...
[✔] Saving changes 
[16:44:17]: Successfully uploaded screenshots to iTunes Connect
[16:44:20]: Price Tier unchanged (tier 0)
[16:44:23]: Uploading app icon...
[16:44:29]: Uploading binary to iTunes Connect
[16:44:29]: Going to upload updated app to iTunes Connect
[16:44:29]: This might take a few minutes. Please don't interrupt the script.
[16:46:03]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[16:46:04]: Transporter transfer failed.
[16:46:04]: 
[16:46:04]: Could not start delivery: all transports failed diagnostics
[16:46:04]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine.access$1200(TransferEngine.java:149)

[16:46:04]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$8.run(TransferEngine.java:4060)

[16:46:04]: [iTMSTransporter] 

[16:46:04]: [iTMSTransporter] [2018-03-23 16:46:03 CST] <Transport Protocol> DEBUG: Received failed transfer notification; aborting

[16:46:04]: [iTMSTransporter] [2018-03-23 16:46:03 CST] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED

[16:46:04]: [iTMSTransporter] [2018-03-23 16:46:03 CST] <main> ERROR: Could not start delivery: all transports failed diagnostics

[16:46:04]: [iTMSTransporter] 

[16:46:04]: [iTMSTransporter] 

[16:46:04]: [iTMSTransporter] 

[16:46:04]: [iTMSTransporter] Package Summary:

[16:46:04]: [iTMSTransporter]  

[16:46:04]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[16:46:04]: [iTMSTransporter] 	/tmp/1362939904.itmsp - Error Messages:

[16:46:04]: [iTMSTransporter] 		Could not start delivery: all transports failed diagnostics

[16:46:04]: [iTMSTransporter] [2018-03-23 16:46:04 CST] <main> DBG-X: Returning 1

[16:46:04]: iTunes Transporter output above ^
[16:46:04]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+--------------------+-----------------------------------------+
|                         Lane Context                         |
+--------------------+-----------------------------------------+
| DEFAULT_PLATFORM   | ios                                     |
| PLATFORM_NAME      | ios                                     |
| LANE_NAME          | ios beta                                |
| BUILD_NUMBER       | 21                                      |
| IPA_OUTPUT_PATH    | /Users/zuqiu/.jenkins/workspace/icon_c  |
|                    | ut/测试2/测试2.ipa                      |
| DSYM_OUTPUT_PATH   | /Users/zuqiu/.jenkins/workspace/icon_c  |
|                    | ut/测试2/测试2.app.dSYM.zip             |
| XCODEBUILD_ARCHIVE | /Users/zuqiu/Library/Developer/Xcode/A  |
|                    | rchives/2018-03-23/测试2 2018-03-23     |
|                    | 16.42.11.xcarchive                      |
+--------------------+-----------------------------------------+
[16:46:04]: Could not upload binary to iTunes Connect. Check out the error above

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_number | 3           |
| 3    | build_ios_app          | 68          |
| 💥   | deliver                | 172         |
+------+------------------------+-------------+

[16:46:04]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  gym: error-reporting: codesigning failures in Check Dependencies aren't caught/noticed?
    https://github.com/fastlane/fastlane/issues/10081 [open] 8 💬
    3 days ago

➡️  [Transporter Error Output]: description length:3125638  followed by precheck/spaceship exception
    https://github.com/fastlane/fastlane/issues/11026 [open] 18 💬
    a day ago

➡️  Pilot fails after successful upload: "Could not set changelog"
    https://github.com/fastlane/fastlane/issues/10088 [closed] 27 💬
    06 Jan 2018

and 67 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20upload%20binary%20to%20iTunes%20Connect.%20Check%20out%20the%20error%20above&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] Could not upload binary to iTunes Connect. Check out the error above
zuqiudeMacBook-Pro:fastlane zuqiu$ at com.signiant.interactivetransfer.engine.TransferEngine.access$1200(TransferEngine.java:149)

**Comment by zuqiu123** [comment]
fastlane env
[✔] 🚀 
[02:00:37]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[02:00:38]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.86.2  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| excon                     | 0.61.0       |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
</details>


*generated on:* **2018-03-30**
</details>
[02:00:39]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[02:00:39]: 🙄  Wow, that's a lot of markdown text... should fastlane put it
into your clipboard, so you can easily paste it on GitHub? (y/n)
y
[02:01:04]: Successfully copied markdown into your clipboard 🎨
[02:01:04]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

#######################################################################
# fastlane 2.88.0 is available. You are on 2.86.2.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.88.0 Improvements
* [action] Fix crashlytics to not autoload gsp_path if api_token is set (#12176) via Josh Holtz
* Improve error message when specified scheme is not found (#12182) via Cédric Luthi
* [action] Support checking remote git tags existence (#11675) via Takeru Chuganji
* Use Android environment to find adb (don't just rely on it being in PATH) (#12168) via Adam Cohen-Rose
* [snapshot] Make sure matched window has a non-empty frame (#12174) via François Pradel
* [swift] Fixes string return value and shows all lanes (even without description) (#12171) via Josh Holtz
* [scan] Default skip_build to true in Scanfile template (#12162) via Aaron Brager

2.87.0 Lots of action fixes and xcodeproj gem update
* [supply] Added internal track (#12128) via Josh Holtz
* [Action] get_latest_version handles $(SRCROOT) and tries to get target that isn't test (#12138) via Josh Holtz
* [Action] app_store_build_number converts return to int if possible (#12148) via Josh Holtz
* Workspace contained schemes now get loaded (#12147) via Lou Franco
* Ignore *.xcodeproj & *.xcworkspace in gem paths for detecting iOS projects (#12142) via Hiroyuki Morita
* [Action] Add use_bundle_exec option to pod_push action (#11947) via Nicolas Braun
* [match] Write Match encrypted files in binary mode to avoid UndefinedConversion error (#12112) via Michael Smith
* [Action] Fix a bug that upload_symbols_to_crashlytics fails if path has a space (#12098) via Takeru Chuganji

**Comment by saitjr** [comment]
朋友。。。你这都 put it into your clipboard，issue 里面没有有用的信息啊

**Comment by saitjr** [comment]
@zuqiu123 朋友，重新输出的这个日志里面，都 copied markdown into your clipboard，没有有用信息啊
