### ISSUE TITLE
Errors when using an account with 2-Step authentication

### ISSUE THREAD

**Issue by sergiocampama** [fastlane/fastlane#12211]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We're getting errors when using the Fastlane gem and the account has 2 step authentication (SMS, not 2 factor).

```
bundler: failed to load command: [REDACTED]/loader.rb ([REDACTED]/loader.rb)
Spaceship::Client::UnauthorizedAccessError: Unauthorized Access
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/spaceship/lib/spaceship/client.rb:708:in `block in send_request'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/spaceship/lib/spaceship/client.rb:538:in `with_retry'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/spaceship/lib/spaceship/client.rb:702:in `send_request'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/spaceship/lib/spaceship/client.rb:590:in `request'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/spaceship/lib/spaceship/two_step_client.rb:9:in `handle_two_step'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/spaceship/lib/spaceship/client.rb:477:in `send_shared_login_request'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/spaceship/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/spaceship/lib/spaceship/client.rb:669:in `do_login'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/spaceship/lib/spaceship/client.rb:405:in `login'
  [REDACTED]/lib/portal.rb:70:in `block in login'
  [REDACTED]/lib/portal.rb:68:in `each'
  [REDACTED]/lib/portal.rb:68:in `login'
  [REDACTED]/lib/cli.rb:28:in `confirm_before'
  [REDACTED]/commands/profile.rb:207:in `block (3 levels) in <module:CLI>'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:69:in `run!'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/configure.rb:9:in `block in configure'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/configure.rb:8:in `class_exec'
  [REDACTED]/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/configure.rb:8:in `configure'
  [REDACTED]/commands/profile.rb:22:in `<module:CLI>'
  [REDACTED]/commands/profile.rb:20:in `<module:ADCon>'
  [REDACTED]/commands/profile.rb:19:in `<top (required)>'
  [REDACTED]/loader.rb:32:in `load'
  [REDACTED]/loader.rb:32:in `run'
  [REDACTED]/loader.rb:56:in `<top (required)>'
```

##### Complete output when running fastlane, including the stack trace and command used

Not using fastlane the binary.

### Environment

The above trace should have the necessary versions

**Comment by joshdholtz** [comment]
@sergiocampama Has two step worked for you in the past? In other words, did this error just start happening?

**Comment by sergiocampama** [comment]
Yes, it worked initially, but then stopped working.
