### ISSUE TITLE
separate AppleIDs for development and distribution

### ISSUE THREAD

**Issue by zantoku** [fastlane/fastlane#1223]
It seems that fastlane is set up to use a single AppleID for everything. We have our work environment set up differently: developer accounts generally do not have iTunes Connect access, and the iTunes Connect users are not on the developer portal. Currently this prevents me from even using 'fastlane init', resulting in a crash.

Apart from the issue that the crash reason should be communicated to the user in some way (I had to read the crash report json to have an idea of what failed) - is it possible to somehow manage user identities in the different fastlane tools? For example, enterprise builds will need a different AppleID and team than app store builds.

**Comment by KrauseFx** [comment]
Have you seen the Appfile docs: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md

**Comment by zantoku** [comment]
Sorry, I'm a new user - hadn't seen the Appfile docs yet. Thanks for the heads-up! Maybe "fastlane init" should offer some guidance if it fails due to 401 errors, instead of just crashing?

**Comment by KrauseFx** [comment]
What do you mean just crashing? Can you share the complete output when running `fastlane init`, including the crash with its stack trace?

**Comment by zantoku** [comment]
Sure. I reproduced the crashes with fastlane 1.56. 

This is the crash when using fastlane init with the developer account: 4f1d9609f6a32cff15d5e3a6f016264b

And this is the crash with the itunes connect account: a5bbe27daff37774e0f3aeee8a4de03c

Before, I was using fastlane 1.53 and I'll say that the error messages are somewhat better now, as it explicitly says "unauthorized access" in red on stdout. But I still can't set up fastlane on this project.

**Comment by KrauseFx** [comment]
Please share the complete output when running it, and your configuration files

**Comment by zantoku** [comment]
Alright, although I will redact any AppleIDs and developer portal output. What configuration files are you interested in? Here is the output when running `fastlane init` with the developer account:

```
[11:18:52]: Detected iOS/Mac project in current directory...
[11:18:52]: This setup will help you get up and running in no time.
[11:18:52]: fastlane will check what tools you're already using and set up
[11:18:52]: the tool automatically for you. Have fun! 
[11:18:52]: Created new folder './fastlane'.
[11:18:52]: xcrun xcodebuild -list -workspace './sonntagsapp-ios.xcworkspace'
2016-02-03 11:18:53.105 xcodebuild[42069:903391] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:18:53.106 xcodebuild[42069:903391] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:18:53.106 xcodebuild[42069:903391] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/TOCAssetCatalogBackground.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:18:53.107 xcodebuild[42069:903391] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:18:53.107 xcodebuild[42069:903391] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:18:53.900 xcodebuild[42073:903468] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:18:53.901 xcodebuild[42073:903468] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:18:53.901 xcodebuild[42073:903468] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/TOCAssetCatalogBackground.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:18:53.902 xcodebuild[42073:903468] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:18:53.902 xcodebuild[42073:903468] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Your Apple ID (e.g. fastlane@krausefx.com): ...
[11:19:03]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[11:19:03]: Starting login with user '...'
Multiple teams found, please enter the number of the team you want to use: 
1) ...
2) ...
3) ...
4) ...
5) ...
2
[11:19:21]: Error occurred with the setup program! Reverting changes now!
[11:19:21]: Deleting the 'fastlane' folder
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '1c961b6ea6b1159c9006a10e3590e9b9'
The crash report has been stored locally '/tmp/sentry_1c961b6ea6b1159c9006a10e3590e9b9.json'
/Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.19.3/lib/spaceship/client.rb:268:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:45:in `teams'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:83:in `select_team'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.19.3/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:173:in `detect_if_app_is_available'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:29:in `run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/bin/fastlane:51:in `block (2 levels) in run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/bin/fastlane:150:in `run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/bin/fastlane:156:in `<top (required)>'
	from /Users/karsten/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `load'
	from /Users/karsten/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `<main>'
	from /Users/karsten/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/karsten/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```


And this is the output when running the command with the iTunesConnect account:
```
[11:25:44]: Detected iOS/Mac project in current directory...
[11:25:44]: This setup will help you get up and running in no time.
[11:25:44]: fastlane will check what tools you're already using and set up
[11:25:44]: the tool automatically for you. Have fun! 
[11:25:44]: Created new folder './fastlane'.
[11:25:44]: xcrun xcodebuild -list -workspace './sonntagsapp-ios.xcworkspace'
2016-02-03 11:25:44.887 xcodebuild[42104:914097] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:25:44.888 xcodebuild[42104:914097] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:25:44.889 xcodebuild[42104:914097] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/TOCAssetCatalogBackground.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:25:44.889 xcodebuild[42104:914097] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:25:44.889 xcodebuild[42104:914097] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:25:45.661 xcodebuild[42108:914171] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:25:45.662 xcodebuild[42108:914171] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:25:45.663 xcodebuild[42108:914171] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/TOCAssetCatalogBackground.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:25:45.663 xcodebuild[42108:914171] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-02-03 11:25:45.663 xcodebuild[42108:914171] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Your Apple ID (e.g. fastlane@krausefx.com): ...
[11:25:52]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[11:25:52]: Starting login with user '...'
[11:25:54]: Error occurred with the setup program! Reverting changes now!
[11:25:54]: Deleting the 'fastlane' folder
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'e7a1068cf280dd554c395759311b5d2a'
The crash report has been stored locally '/tmp/sentry_e7a1068cf280dd554c395759311b5d2a.json'
/Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.19.3/lib/spaceship/portal/ui/select_team.rb:37:in `select_team': [!] Your account is in no teams (RuntimeError)
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.19.3/lib/spaceship/portal/portal_client.rb:78:in `select_team'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.19.3/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.19.3/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:169:in `detect_if_app_is_available'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:29:in `run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/bin/fastlane:51:in `block (2 levels) in run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/bin/fastlane:150:in `run'
	from /Users/karsten/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.57.0/bin/fastlane:156:in `<top (required)>'
	from /Users/karsten/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `load'
	from /Users/karsten/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `<main>'
	from /Users/karsten/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/karsten/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ohwutup** [comment]
Hey @zantoku ! We have pushed a couple fixes for this type of issue when running `fastlane init`. If you could please update your tools, and give this another shot, that would be awesome! :shipit:
