### ISSUE TITLE
undefined method `in_house?' for nil:NilClass with fastlane 2.92

### ISSUE THREAD

**Issue by erdem-inan** [fastlane/fastlane#12327]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Impossible to run a lane with the new version of fastlane 2.92 

##### Complete output when running fastlane, including the stack trace and command used

```
[10:30:50]: undefined method `in_house?' for nil:NilClass
[08:30:50][Step 1/1] 
[08:30:50][Step 1/1] +------+----------------------------+-------------+
[08:30:50][Step 1/1] |                fastlane summary                 |
[08:30:50][Step 1/1] +------+----------------------------+-------------+
[08:30:50][Step 1/1] | Step | Action                     | Time (in s) |
[08:30:50][Step 1/1] +------+----------------------------+-------------+
[08:30:50][Step 1/1] | 1    | Verifying fastlane version | 0           |
[08:30:50][Step 1/1] | 2    | default_platform           | 0           |
[08:30:50][Step 1/1] | 3    | is_ci                      | 0           |
[08:30:50][Step 1/1] | 4    | ensure_git_status_clean    | 0           |
[08:30:50][Step 1/1] | 5    | reset_simulator_contents   | 0           |
[08:30:50][Step 1/1] |       | match                      | 4           |
[08:30:50][Step 1/1] | 7    | is_ci                      | 0           |
[08:30:50][Step 1/1] | 8    | reset_git_repo             | 0           |
[08:30:50][Step 1/1] | 9    | reset_simulator_contents   | 0           |
[08:30:50][Step 1/1] | 10   | is_ci                      | 0           |
[08:30:50][Step 1/1] | 11   | slack                      | 0           |
[08:30:50][Step 1/1] +------+----------------------------+-------------+
[08:30:50][Step 1/1] 
[08:30:50][Step 1/1] [10:30:50]: fastlane finished with errors
[08:30:50][Step 1/1] 
[08:30:50][Step 1/1] Looking for related GitHub issues on fastlane/fastlane...
[08:30:50][Step 1/1] 
[08:30:50][Step 1/1] ➡️  [match] Correct how match handles enterprise adhoc
[08:30:50][Step 1/1]     https://github.com/fastlane/fastlane/pull/12281 [closed] 2   
[08:30:50][Step 1/1]     an hour ago
[08:30:50][Step 1/1] 
[08:30:50][Step 1/1] ➡️  Remove Shenzhen dependency
[08:30:50][Step 1/1]     https://github.com/fastlane/fastlane/pull/6991 [closed] 19   
[08:30:50][Step 1/1]     13 Mar 2017
[08:30:50][Step 1/1] 
[08:30:50][Step 1/1]     You can ⌘ + double-click on links to open them directly in your browser.
[08:30:50][Step 1/1] /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/match/lib/match/module.rb:19:in `cert_type_sym': [!] undefined method `in_house?' for nil:NilClass (NoMethodError)
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/match/lib/match/runner.rb:92:in `fetch_certificate'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/match/lib/match/runner.rb:57:in `run'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
[08:30:50][Step 1/1] 	from Fastfile:139:in `block (2 levels) in parsing_binding'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/lane.rb:33:in `call'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.92.0/bin/fastlane:20:in `<top (required)>'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/bin/fastlane:22:in `load'
[08:30:50][Step 1/1] 	from /Users/admin/.rbenv/versions/2.3.1/bin/fastlane:22:in `<main>'
[08:30:50][Step 1/1] Process exited with code 1
[08:30:51][Step 1/1] Step Submit a new Dev Build to Crashlytics (Command Line) failed
[08:30:51]Ant JUnit report watcher
```

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.92.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.1        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.1       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.0        |
</details>

**Comment by satheeshkumarf** [comment]
+1

**Comment by GaborWnuk** [comment]
+1

**Comment by fburel** [comment]
Same here,
Seems the problem comes from match...
When I run match directly, it informs me that Apple updated it's licence agreement and that I have to go to the website to approve them.
I did, but the problem is still here.

`
[13:12:28]: undefined method `in_house?' for nil:NilClass

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | update_fastlane            | 4           |
| 2    | Verifying fastlane version | 0           |
| 3    | default_platform           | 0           |
| 4    | cocoapods                  | 5           |
| 5    | changelog_from_git_commits | 0           |
| 💥   | match                      | 5           |
+------+----------------------------+-------------+

[13:12:28]: fastlane finished with errors

`

**Comment by michalciurus** [comment]
+1

**Comment by Dids** [comment]
Disabling `readonly` is not really a fix though.

**Comment by satheeshkumarf** [comment]
I just reverted my fastlane version to 2.91.0 in my Gemfile and the issue is not there in that version. So, until its fixed, I think we need to use the previous version.

**Comment by joshdholtz** [comment]
Looking into 😬

**Comment by joshdholtz** [comment]
Reverted the breaking PR and making bump for `2.92.1`

**Comment by erdem-inan** [comment]
@joshdholtz Thanks !

**Comment by joshdholtz** [comment]
Okay, `2.92.1 is out! Would you be able to give it a try to make sure it works for you all? 🙃

**Comment by bcorrea2-luizalabs** [comment]
I had same problem here, after the update everything is fine again! Tk you very much!!!

**Comment by erdem-inan** [comment]
@joshdholtz It is fixed ! Thanks !

**Comment by joshdholtz** [comment]
@erdem-inan Woot, glad it works for you! Sorry about that 🙃

**Comment by fburel** [comment]
Perfect! It is fixed :)
