### ISSUE TITLE
Match won't terminate in non-interactive mode without Match password

### ISSUE THREAD

**Issue by priitlatt** [fastlane/fastlane#12342]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When `MATCH_PASSWORD` environment variable is not set *and* Match password is missing from the local keychain, then running `fastlane match` in non-interactive mode (with `CI=true`) results in looping errors:

```
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
ERROR [2018-04-19 17:55:33.60]: Neither the MATCH_PASSWORD environment variable nor the local keychain contained a password.
ERROR [2018-04-19 17:55:33.60]: Bailing out instead of asking for a password, since this is non-interactive mode.
ERROR [2018-04-19 17:55:33.60]: Couldn't decrypt the repo, please make sure you enter the right password!
```

Link to possibly relevant line in source: https://github.com/fastlane/fastlane/blob/14336f8d2b98d25701238f140e8da3e1f4351fed/match/lib/match/encrypt.rb#L67

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>(gh) 17:55:22 priit@marmot ios-test2 fastlane ? CI=true bundle exec fastlane match --verbose                                                                                                                                                                            130 ↵
[✔] 🚀
Successfully loaded Appfile at path '/Users/priit/git/banaan-ios/ios-test2/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/priit/git/banaan-ios/ios-test2/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/priit/git/banaan-ios/ios-test2/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/priit/git/banaan-ios/ios-test2/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/priit/git/banaan-ios/ios-test2/fastlane/Appfile'
-------
INFO [2018-04-19 17:55:31.51]: Successfully loaded '/Users/priit/git/banaan-ios/ios-test2/fastlane/Matchfile' 📄

+---------+-----------------------------------------------+
|       Detected Values from './fastlane/Matchfile'       |
+---------+-----------------------------------------------+
| git_url | git@github.com:priitlatt/ios-certificates.git |
| type    | development                                   |
+---------+-----------------------------------------------+

+-----------------------+-----------------------------------------------+
|                       Summary for match 2.92.1                        |
+-----------------------+-----------------------------------------------+
| verbose               | true                                          |
| git_url               | git@github.com:priitlatt/ios-certificates.git |
| git_branch            | master                                        |
| type                  | development                                   |
| username              | priit@*************.com                        |
| keychain_name         | login.keychain                                |
| readonly              | false                                         |
| force                 | false                                         |
| skip_confirmation     | false                                         |
| shallow_clone         | false                                         |
| clone_branch_directly | false                                         |
| force_for_new_devices | false                                         |
| skip_docs             | false                                         |
| platform              | ios                                           |
+-----------------------+-----------------------------------------------+

INFO [2018-04-19 17:55:31.52]: Cloning remote git repo...
INFO [2018-04-19 17:55:31.52]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-04-19 17:55:31.52]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:priitlatt/ios-certificates.git' '/var/folders/2d/62rk_6991sx73v2kfszdvftm0000gn/T/d20180419-12064-1e5pjy2'
INFO [2018-04-19 17:55:31.53]: ▸ Cloning into '/var/folders/2d/62rk_6991sx73v2kfszdvftm0000gn/T/d20180419-12064-1e5pjy2'...
INFO [2018-04-19 17:55:33.21]: ▸ remote: Counting objects: 25, done.
INFO [2018-04-19 17:55:33.33]: ▸ remote: Total 25 (delta 0), reused 0 (delta 0), pack-reused 25
INFO [2018-04-19 17:55:33.33]: ▸ Receiving objects: 100% (25/25), 31.50 KiB | 15.75 MiB/s, done.
INFO [2018-04-19 17:55:33.33]: ▸ Resolving deltas: 100% (2/2), done.
ERROR [2018-04-19 17:55:33.52]: Neither the MATCH_PASSWORD environment variable nor the local keychain contained a password.
ERROR [2018-04-19 17:55:33.52]: Bailing out instead of asking for a password, since this is non-interactive mode.
ERROR [2018-04-19 17:55:33.52]: Couldn't decrypt the repo, please make sure you enter the right password!
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
ERROR [2018-04-19 17:55:33.60]: Neither the MATCH_PASSWORD environment variable nor the local keychain contained a password.
ERROR [2018-04-19 17:55:33.60]: Bailing out instead of asking for a password, since this is non-interactive mode.
ERROR [2018-04-19 17:55:33.60]: Couldn't decrypt the repo, please make sure you enter the right password!
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
^C/Users/priit/vendor/bundle/ruby/2.3.0/gems/security-0.1.3/lib/security/password.rb:88:in ``': Interrupt
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/security-0.1.3/lib/security/password.rb:88:in `find'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:19:in `password'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:62:in `block in decrypt_repo'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:80:in `block in iterate'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:78:in `each'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:78:in `iterate'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:59:in `decrypt_repo'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:67:in `rescue in block in decrypt_repo'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:60:in `block in decrypt_repo'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:80:in `block in iterate'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:78:in `each'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:78:in `iterate'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:59:in `decrypt_repo'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:67:in `rescue in block in decrypt_repo'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:60:in `block in decrypt_repo'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:80:in `block in iterate'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:78:in `each'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:78:in `iterate'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/encrypt.rb:59:in `decrypt_repo'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/git_helper.rb:72:in `clone'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/runner.rb:24:in `run'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/commands_generator.rb:46:in `block (2 levels) in run'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/commands_generator.rb:146:in `run'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/match/lib/match/commands_generator.rb:19:in `start'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/fastlane/lib/fastlane/cli_tools_distributor.rb:99:in `take_off'
	from /Users/priit/vendor/bundle/ruby/2.3.0/gems/fastlane-2.92.1/bin/fastlane:20:in `<top (required)>'
	from /Users/priit/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `load'
	from /Users/priit/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `<top (required)>'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
	from /Users/priit/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
	from /Users/priit/.rbenv/versions/2.3.6/bin/bundle:22:in `load'
	from /Users/priit/.rbenv/versions/2.3.6/bin/bundle:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.4                                         |
| Ruby                        | 2.3.6                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.14.1                              |
| Installation Source         | ~/vendor/bundle/ruby/2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.4 (17E199)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.6/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.2.app/Contents/Developer/ |
| Xcode Version               | 9.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Build the app"
lane :build_banaan do
  xcversion(version: "9.2")
  build_ios_app(
    project: "banaan.xcodeproj",
    configuration: "Release",
    scheme: "banaan",
    # output_directory: "path/to/dir",   # Destination directory. Defaults to current directory.
    output_name: "banaan-ios.ipa",       # specify the name of the .ipa file to generate (including file extension)
    sdk: "iOS 11.2",                     # use SDK as the name or path of the base SDK when building the project.
    # export_method: "app-store",
    # export_options: {
    #   provisioningProfiles: {
    #     "io.nevercode.banaan" => "match AppStore io.nevercode.banaan"
    #   }
    # }
  )
end

lane :build_and_setup_signing do
  match(type: "appstore", readonly: true)
  gym
end

platform :android do
  desc "Description of what the lane does"
  lane :custom_lane do
    sh "echo 'tere talv'"
  end
end

platform :ios do
  lane :test_banaan do
    run_tests(workspace: "banaan.xcworkspace",
              devices: ["iPhone 6s"],  # , "iPad Air"],
              scheme: "banaan")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.92.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.2.2        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.3.1        |
</details>

*generated on:* **2018-04-19**
</details></pre>
</details>

**Comment by priitlatt** [comment]
No bot, this issue is not a code signing issue in the usual way. The issue occurs way before we get to actual code signing.
