### ISSUE TITLE
Server error (Google::Apis::ServerError)

### ISSUE THREAD

**Issue by ankur-sardar** [fastlane/fastlane#12391]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
It is failing when I am trying to upload android app in alpha google play console. Showing this message.
```
and 560 more at: https://github.com/fastlane/fastlane/search?q=Server%20error&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
[02:44:59]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
/Users/distiller/.gem/ruby/2.3.5/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:221:in `check_status': [!] Server error (Google::Apis::ServerError)
	from /Users/distiller/.gem/ruby/2.3.5/gems/google-api-client-0.13.6/lib/google/apis/core/api_command.rb:118:in `check_status'
	from /Users/distiller/.gem/ruby/2.3.5/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:183:in `process_response'
	from /Users/distiller/.gem/ruby/2.3.5/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:299:in `execute_once'
	from /Users/distiller/.gem/ruby/2.3.5/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
	from /Users/distiller/.gem/ruby/2.3.5/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
	from /Users/distiller/.gem/ruby/2.3.5/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
	from /Users/distiller/.gem/ruby/2.3.5/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
	from /Users/distiller/.gem/ruby/2.3.5/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:101:in `block in execute'
	from /Users/distiller/.gem/ruby/2.3.5/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
	from /Users/distiller/.gem/ruby/2.3.5/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
	from /Users/distiller/.gem/ruby/2.3.5/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
	from /Users/distiller/.gem/ruby/2.3.5/gems/google-api-client-0.13.6/lib/google/apis/core/http_command.rb:93:in `execute'
	from /Users/distiller/.gem/ruby/2.3.5/gems/google-api-client-0.13.6/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	from /Users/distiller/.gem/ruby/2.3.5/gems/google-api-client-0.13.6/generated/google/apis/androidpublisher_v2/service.rb:92:in `commit_edit'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/supply/lib/supply/client.rb:118:in `block in commit_current_edit!'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/supply/lib/supply/client.rb:372:in `call_google_api'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/supply/lib/supply/client.rb:118:in `commit_current_edit!'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/supply/lib/supply/uploader.rb:36:in `perform_upload'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:32:in `block (2 levels) in parsing_binding'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/distiller/.rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/fastlane-2.93.1/bin/fastlane:20:in `<top (required)>'
	from /Users/distiller/.gem/ruby/2.3.5/bin/fastlane:22:in `load'
	from /Users/distiller/.gem/ruby/2.3.5/bin/fastlane:22:in `<main>'
```

 I am using Fastlane for a long time, I never faced this problem before.
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@ankur-sardar I just uploaded an APK to `alpha` with version `2.93.1` without any problems. Can you try again? Maybe Google has a hiccup. If that still doesn't work, can you run `fastlane env` and paste the output in a comment so we can see exactly what you are working with?

**Comment by ankur-sardar** [comment]
@joshdholtz , Yes, You are right, I think it was some problem with Google. Now It is working fine. Thank you so much for your help.
