### ISSUE TITLE
screengrab error on android 

### ISSUE THREAD

**Issue by Kgothatso09** [fastlane/fastlane#12422]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[11:22:06]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[11:22:06]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[11:22:06]: $ C:\Users\test\AppData\Local\Android\Sdk\platform-tools/adb.EXEadb devices -l
No such file or directory - C:\Users\test\AppData\Local\Android\Sdk\platform-tools/adb.EXEadb devices -l

[11:22:06]: Error accessing file, this might be due to fastlane's directory handling
[11:22:06]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - C:\Users\test\AppData\Local\Android\Sdk\platform-tools/adb.EXEadb devices -l (Errno::ENOENT)
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:190:in `popen2e'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/fastlane_pty.rb:13:in `rescue in spawn'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/fastlane_pty.rb:6:in `spawn'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/command_executor.rb:51:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/screengrab/lib/screengrab/runner.rb:352:in `run_adb_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/screengrab/lib/screengrab/runner.rb:80:in `select_device'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/screengrab/lib/screengrab/runner.rb:56:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.94.0/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/bin/fastlane:23:in `<main>'</pre>
</details>

### Environment

<details>
  <pre>[11:52:01]: fastlane detected a Gemfile in the current directory
[11:52:01]: however it seems like you don't use `bundle exec`
[11:52:01]: to launch fastlane faster, please use
[11:52:01]:
[11:52:01]: $ bundle exec fastlane env
[11:52:01]:
[11:52:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:52:05]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.4.4                        |
| Bundler?                    | false                        |
| Git                         | git version 2.11.1.windows.1 |
| Installation Source         | C:/Ruby24-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/Ruby24-x64/lib            |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018  |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.test") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.93.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| CFPropertyList            | 3.0.0        |
| json                      | 2.1.0        |
| openssl                   | 2.0.7        |
</details></pre>
</details>

**Comment by Kgothatso09** [comment]
Updated issue details with stacktrace

**Comment by Kgothatso09** [comment]
It is also interesting to not further up there is this:

`[11:26:47]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
'cat' is not recognized as an internal or external command,
operable program or batch file.`
