### ISSUE TITLE
Faild xcarchive backup

### ISSUE THREAD

**Issue by bartoszj** [fastlane/fastlane#1247]
When I try to archive xcarchive using `backup_xcarchive` and the destination path is set to the same folder where xcarchive is placed `backup_xcarchive` crashes with error:

```
fileutils.rb:1570:in `block in fu_each_src_dest': [!] same file: /Users/user/MyApp.xcarchive.zip and ./MyApp.xcarchive.zip (ArgumentError)
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:1585:in `fu_each_src_dest0'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/actions/backup_xcarchive.rb:41:in `run'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:127:in `block (2 levels) in parsing_binding'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:110:in `try_switch_to_lane'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from Fastfile:184:in `block (2 levels) in parsing_binding'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/bin/fastlane:150:in `run'
	from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.55.0/bin/fastlane:156:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.3.0/bin/fastlane:23:in `load'
	from /Users/user/.rbenv/versions/2.3.0/bin/fastlane:23:in `<main>'
```

Problem exists because the temporary zip file is created in the folder where xcarchive is placed. Moving this file to the destination folder (which is the same place) is not possible and the `FileUtils.mv` fails.

**Comment by vpolouchkine** [comment]
Thanks for the PR!
