### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#12480]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I am getting this error very often and randomly, is this related to Fastlane?

```
Testing failed:
unable to spawn process (Resource temporarily unavailable)
** TEST FAILED **


The following build commands failed:
Ld /Users/me/Library/Developer/Xcode/Build/Products/Debug-MySCheme-iphonesimulator/MyApp_MySCheme.app/MyApp_MySCheme normal x86_64
(1 failure)
▸ Linking MyApp_MySCheme

❌  error: unable to spawn process (Resource temporarily unavailable)

[16:40:22]: Exit status: 65
[16:40:22]: Tests failed while running on: iPhone 6s Plus
[16:40:22]: For more detail about the test failures, check the logs here:
[16:40:22]: /Users/me/Library/Logs/snapshot/MyApp_MySCheme-Screenshots_MySCheme.log
[16:40:22]:
[16:40:22]: You can also find the test result data here:
[16:40:22]: /Users/me/Library/Developer/Xcode/Logs/Test
[16:40:22]:
[16:40:22]: You can find the incomplete screenshots here:
[16:40:22]: /Users/me/Library/Caches/tools.fastlane/screenshots
[16:40:22]: /Users/me/Repository/myCompany-ios/fastlane/screenshotsRaw/MyApp_MySCheme
[16:40:22]: Caught error... 65
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    |             |
| LANE_NAME        | screenshots |
+------------------+-------------+
[16:40:22]: Too many errors... no more retries...

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | snapshot                   | 87          |
+------+----------------------------+-------------+

[16:40:22]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Make spaceship even more stable and robust
    https://github.com/fastlane/fastlane/issues/7768 [closed] 18 💬
    03 Dec 2017

➡️  Snapshot not launching simulators on Xcode 9.1
    https://github.com/fastlane/fastlane/issues/11047 [closed] 6 💬
    30 Jan 2018

➡️  "no implicit conversion of nil into String" when executing snapshpt
    https://github.com/fastlane/fastlane/issues/7433 [closed] 8 💬
    13 Sep 2017

and 15 more at: https://github.com/fastlane/fastlane/search?q=Too%20many%20errors...%20no%20more%20retries...&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/ui/interface.rb:121:in `crash!': [!] Too many errors... no more retries... (FastlaneCore::Interface::FastlaneCrash)
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:132:in `block in execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/command_executor.rb:93:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:108:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:155:in `retry_tests'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:129:in `block in execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/command_executor.rb:93:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:108:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:94:in `launch_simultaneously'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:70:in `block (3 levels) in take_screenshots_simultaneously'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:69:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:69:in `block (2 levels) in take_screenshots_simultaneously'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each_with_index'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `block in take_screenshots_simultaneously'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `take_screenshots_simultaneously'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/snapshot/lib/snapshot/runner.rb:45:in `work'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/actions/capture_ios_screenshots.rb:14:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
        from Fastfile:75:in `block in parsing_binding'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.94.0/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:22:in `load'
        from /usr/local/bin/fastlane:22:in `<main>'
```

Fastfile:

```ruby
  ENV["SCREENSHOT_SCHEME"] = "Screenshots_MY_SCHEME"
  ENV["APP_IDENTIFIER"] = "com.my.app"
  ENV["SCHEME"] = "MyScheme"
  snapshot(
    workspace: "MyApp.xcworkspace",
    scheme: ENV["SCREENSHOT_SCHEME"],
    derived_data_path: "/Users/me/Library/Developer/Xcode",
    output_simulator_logs: true,
    skip_open_summary: true,
    erase_simulator: true,
    clear_previous_screenshots: false,
    test_without_building: false,
    reinstall_app: true,
    concurrent_simulators: false,
    stop_after_first_error: true)
```

Snapfile:

```ruby
devices([
  "iPhone 6s Plus"
])

languages([
  ["en-US", "en-GB", "pt_BR"]
])

scheme(ENV["SCREENSHOT_SCHEME"])
app_identifier(ENV["APP_IDENTIFIER"])
output_directory "./fastlane/screenshotsRaw/#{ENV["SCHEME"]}"
clear_previous_screenshots(true)
```

#### Question Description

I have no idea why this is happening, it started happening on recent versions of Fastlane. My Mac is not under heavy load to this happen but I noticed that my terminal gets really slow sometimes.

Thank you.

**Comment by ppamorim** [comment]
![screen shot 2018-05-10 at 14 29 43](https://user-images.githubusercontent.com/5521682/39872042-9cf700ec-545e-11e8-9159-05e15582525d.png)

Also getting this screen after the main error.
