### ISSUE TITLE
Scan doesn't handle Xcode 9 format of `simctl list`

### ISSUE THREAD

**Issue by ben-lings-tessella** [fastlane/fastlane#12488]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running the `scan` action with Xcode 9.3 when there are simulators created for iOS 11.2, but no iOS 11.2 simulator runtime installed for Xcode 9.3 crashes with the following output:

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
 /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/version.rb:207:in `initialize': [!] Malformed version number string com.apple.CoreSimulator.SimRuntime.iOS-11-2 (ArgumentError)
[14:19:32][Step 2/2] 	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/version.rb:199:in `new'
[14:19:32][Step 2/2] 	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/version.rb:199:in `new'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/scan/lib/scan/detect_values.rb:84:in `block in filter_simulators'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/scan/lib/scan/detect_values.rb:83:in `select'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/scan/lib/scan/detect_values.rb:83:in `filter_simulators'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/scan/lib/scan/detect_values.rb:113:in `detect_simulator'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/scan/lib/scan/detect_values.rb:32:in `set_additional_default_values'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/scan/lib/scan/module.rb:17:in `config='
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/run_tests.rb:16:in `run'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
[14:19:32][Step 2/2] 	from Fastfile:204:in `block (2 levels) in parsing_binding'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane.rb:33:in `call'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
[14:19:32][Step 2/2] 	from /Users/[redacted]/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.95.0/bin/fastlane:20:in `<top (required)>'
[14:19:32][Step 2/2] 	from /Users/[redacted]/bin/fastlane:29:in `load'
[14:19:32][Step 2/2] 	from /Users/[redacted]/bin/fastlane:29:in `<main>'
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.13.4                                        |
| Ruby                        | 2.3.1                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.15.1 (Apple Git-101)             |
| Installation Source         | /usr/local/bin/fastlane                        |
| Host                        | Mac OS X 10.13.4 (17E199)                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib             |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode930.app/Contents/Developer/ |
| Xcode Version               | 9.3                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.95.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.8        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| json                      | 2.1.0        |
| bundler                   | 1.16.1       |
</details>

*generated on:* **2018-05-10**
</details>

**Comment by ben-lings-tessella** [comment]
Looks like a similar problem to https://github.com/fastlane/fastlane/issues/10174

**Comment by ben-lings-tessella** [comment]
This issue isn't yet resolved

**Comment by meyer-solutions** [comment]
In Xcode preferences (Locations tab) try to set "Command line tools" back to 9.4.1.
That works for me.

**Comment by ben-lings-tessella** [comment]
This issue isn't yet resolved
