### ISSUE TITLE
Screengrab does not work with P Preview

### ISSUE THREAD

**Issue by vanniktech** [fastlane/fastlane#12516]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running `fastlane screengrab` will fail on a device with Android P installed.

```
[13:17:23]: ▸ com.vanniktech.chessclock.screenshots.ScreenshotsTest:
[13:17:23]: ▸ Error in com.vanniktech.chessclock.screenshots.ScreenshotsTest:
[13:17:23]: ▸ java.lang.RuntimeException: java.lang.NoSuchFieldException: userSetLocale
[13:17:23]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:51)
[13:17:23]: ▸ at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:35)
[13:17:23]: ▸ at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[13:17:23]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:17:23]: ▸ at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
[13:17:23]: ▸ at org.junit.runners.Suite.runChild(Suite.java:128)
[13:17:23]: ▸ at org.junit.runners.Suite.runChild(Suite.java:27)
[13:17:23]: ▸ at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[13:17:23]: ▸ at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[13:17:23]: ▸ at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[13:17:23]: ▸ at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[13:17:23]: ▸ at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[13:17:23]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:17:23]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[13:17:23]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[13:17:23]: ▸ at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[13:17:23]: ▸ at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
[13:17:23]: ▸ at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2136)
[13:17:23]: ▸ Caused by: java.lang.NoSuchFieldException: userSetLocale
[13:17:23]: ▸ at java.lang.Class.getField(Class.java:1601)
[13:17:23]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:37)
[13:17:23]: ▸ ... 17 more
[13:17:23]: ▸ Time: 0.026
[13:17:23]: ▸ There was 1 failure:
[13:17:23]: ▸ 1) com.vanniktech.chessclock.screenshots.ScreenshotsTest
[13:17:23]: ▸ java.lang.RuntimeException: java.lang.NoSuchFieldException: userSetLocale
[13:17:23]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:51)
[13:17:23]: ▸ at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:35)
[13:17:23]: ▸ at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[13:17:23]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:17:23]: ▸ at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
[13:17:23]: ▸ at org.junit.runners.Suite.runChild(Suite.java:128)
[13:17:23]: ▸ at org.junit.runners.Suite.runChild(Suite.java:27)
[13:17:23]: ▸ at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[13:17:23]: ▸ at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[13:17:23]: ▸ at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[13:17:23]: ▸ at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[13:17:23]: ▸ at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[13:17:23]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:17:23]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[13:17:23]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[13:17:23]: ▸ at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[13:17:23]: ▸ at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
[13:17:23]: ▸ at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2136)
[13:17:23]: ▸ Caused by: java.lang.NoSuchFieldException: userSetLocale
[13:17:23]: ▸ at java.lang.Class.getField(Class.java:1601)
[13:17:23]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:37)
[13:17:23]: ▸ ... 17 more
[13:17:23]: ▸ FAILURES!!!
[13:17:23]: ▸ Tests run: 0,  Failures: 1
```

**Comment by joshdholtz** [comment]
@vanniktech Thanks for reporting this! I will look into this 🙃

**Comment by vanniktech** [comment]
This is still an issue.

**Comment by vanniktech** [comment]
This is still an issue.

**Comment by vanniktech** [comment]
With the final P version this does not happen anymore. Only previews were affected. Hence closing.
