### ISSUE TITLE
badge action not working when added to Fastfile

### ISSUE THREAD

**Issue by s0mmer** [fastlane/fastlane#1260]
I was a bit unsure if I should create this issue on this repo or on the action's repo. Please let me know if I should have done it otherwise.

Anyways, I can't make `badge` work when adding it to my Fastfile, it does however work fine when I run it in the terminal. My Fastfile does not contain anything else than the `badge` action. Fastlane version 1.56.0. Here's the error log:

```
12:46:00]: -------------------
[12:46:00]: --- Step: badge ---
[12:46:00]: -------------------
[12:46:01]: Variable Dump:
[12:46:01]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios internalrelease"}
[12:46:01]: wrong number of arguments (6 for 2)

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | badge                               | 0           |
+------+-------------------------------------+-------------+

[12:46:01]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/sds/.rvm/gems/ruby-2.1.2@global/gems/badge-0.1.1/lib/badge/runner.rb:8:in `run': [!] wrong number of arguments (6 for 2) (ArgumentError)
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/actions/badge.rb:6:in `run'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:75:in `block (2 levels) in parsing_binding'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/bin/fastlane:150:in `run'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.56.0/bin/fastlane:156:in `<top (required)>'
	from /Users/sds/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `load'
	from /Users/sds/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `<main>'
	from /Users/sds/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sds/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by carlosefonseca** [comment]
yup… tried to use badge today for the first time and got the same problem…

https://github.com/HazAT/badge/blob/master/lib/badge/runner.rb#L8
```
module Badge
  class Runner

    def run(path, options)
    …
```


https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/badge.rb#L6
```
module Fastlane
  module Actions
    class BadgeAction < Action
      def self.run(params)
        require 'badge'
        Badge::Runner.new.run('.', params[:dark], params[:custom], params[:no_badge], params[:shield])
      end
```

**Comment by HazAT** [comment]
Thanks for reporting there is an open pull request https://github.com/fastlane/fastlane/pull/1255 for this.
Meanwhile you can use version 0.0.4 of badge which only does not have the `--alpha` parameter but should otherwise work perfectly fine.

**Comment by carlosefonseca** [comment]
Version 0.0.5 doesn't crash.

**Comment by HazAT** [comment]
Depends which version of fastlane you run, 0.0.4 will work 100%
With the next release I took care that this never happens again.

**Comment by KrauseFx** [comment]
Should be closed with https://github.com/fastlane/fastlane/pull/1255, preparing a new release now :+1:

**Comment by ldrr** [comment]
Had the same issue because of an old version of badge.

Try to update gem badge and it will work with the latest version of fastlane.

`sudo gem update badge`
