### ISSUE TITLE
Can't build the project using gym. Exit status: 1

### ISSUE THREAD

**Issue by Quarezz** [fastlane/fastlane#1261]
Hi, 

for some reasons, when I run gym separately - I get this result:
```
▸ Archive Succeeded
ERROR [2016-02-02 13:59:09.17]: Exit status: 1
/Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/interface.rb:132:in `user_error!': [!] Error building the application - see the log above (FastlaneCore::Interface::FastlaneError)
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/gym-1.4.0/lib/gym/error_handler.rb:52:in `handle_build_error'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/gym-1.4.0/lib/gym/runner.rb:86:in `block in build_app'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.36.1/lib/fastlane_core/command_executor.rb:82:in `call'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.36.1/lib/fastlane_core/command_executor.rb:82:in `execute'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/gym-1.4.0/lib/gym/runner.rb:82:in `build_app'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/gym-1.4.0/lib/gym/runner.rb:15:in `run'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/gym-1.4.0/lib/gym/manager.rb:10:in `work'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/gym-1.4.0/lib/gym/commands_generator.rb:41:in `block (2 levels) in run'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/gym-1.4.0/lib/gym/commands_generator.rb:60:in `run'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/gym-1.4.0/lib/gym/commands_generator.rb:14:in `start'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/gym-1.4.0/bin/gym:6:in `<top (required)>'
    from /Users/quarezz/.rvm/rubies/ruby-2.2.1/bin/gym:23:in `load'
    from /Users/quarezz/.rvm/rubies/ruby-2.2.1/bin/gym:23:in `<main>'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/quarezz/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```
This Exit status 1 doesn't provide any info about what is actually wrong.
Params of the gym setup are following:
```
+---------------------------+----------------------------------------------------------------------------------------------+
|                                                  Summary for gym 1.4.0                                                   |
+---------------------------+----------------------------------------------------------------------------------------------+
| project                   | ./Prj.xcodeproj                                                                             |
| scheme                    | ****                                                                                         |
| clean                     | true                                                                                         |
| output_directory          | .                                                                                            |
| output_name               | ****                                                                                         |
| configuration             | AdHoc                                                                                        |
| silent                    | false                                                                                        |
| include_symbols           | true                                                                                         |
| include_bitcode           | false                                                                                        |
| use_legacy_build_api      | true                                                                                         |
| export_method             | ad-hoc                                                                                       |
| buildlog_path             | ~/Library/Logs/gym                                                                           |
| provisioning_profile_path | /Users/quarezz/Documents/Job/**** |
| destination               | generic/platform=iOS                                                                         |
+---------------------------+----------------------------------------------------------------------------------------------+

```

And if I try and use it in fastlane - I receive error:
```
▸ Archive Succeeded
[14:14:55]: Exit status: 1
[14:14:55]: Variable Dump:
[14:14:55]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios dev"}
[14:14:55]: Error building the application - see the log above
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'fc4086bd6fc4c43fc343b940ed916f20'
The crash report has been stored locally '/tmp/sentry_fc4086bd6fc4c43fc343b940ed916f20.json'
/Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.56.0/lib/fastlane/documentation/docs_generator.rb:39:in `write': [!] Permission denied @ rb_sysopen - ./fastlane/README.md (Errno::EACCES)
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.56.0/lib/fastlane/documentation/docs_generator.rb:39:in `run'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.56.0/lib/fastlane/lane_manager.rb:55:in `cruise_lane'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.56.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.56.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.56.0/bin/fastlane:150:in `run'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.56.0/bin/fastlane:156:in `<top (required)>'
	from /Users/quarezz/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/quarezz/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/quarezz/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

```

I must say, that xcodebuild runs flawlessly and gives me result:
```
** ARCHIVE SUCCEEDED **

Signing Identity:     "iPhone Distribution: **** (****)"
Provisioning Profile: "**** AdHoc"  (2c56bb99-3b78-4877-9e81-72f3f56f8a1c)
```

**Comment by KrauseFx** [comment]
```
/Users/quarezz/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.56.0/lib/fastlane/documentation/docs_generator.rb:39:in `write': [!] Permission denied @ rb_sysopen - ./fastlane/README.md (Errno::EACCES)
```

Why don't you have write permission to the README?

**Comment by Quarezz** [comment]
It seems like something wrong with my rvm permissions. I will look deeper in it, never mind :)
Thanks

**Comment by ShadyElyaski** [comment]
I'm running into the same issue trying to run fastlane from Jenkins. I think it's because when Jenkins creates the workspace, all files are set to read-only. @Quarezz How did you fix this error?

**Comment by Quarezz** [comment]
@ShadyElyaski I had to reinstall my rvm with right permissions and everything started to work. Don't know if this is your case though..

**Comment by TKBurner** [comment]
@ShadyElyaski Let me know how it goes with resetting rvm!

**Comment by ShadyElyaski** [comment]
@TKBurner after digging more into the issue, knowing the fact that Jenkins was creating the workspace folder as read-only, I figured out those 2 solutions:-

1- Change umask into umask 002 (explained here: https://support.apple.com/en-us/HT201684)
But this can cause security issues.
2- Add this line before running fastlane 
chmod -R 755 "${WORKSPACE}/"
which will fix permissions for the workspace folder.

Thanks for following up.

**Comment by TKBurner** [comment]
@ShadyElyaski Awesome! Really glad to hear you got up and running. Hope you have a great week!
