### ISSUE TITLE
Archive failed with Exit Status 65

### ISSUE THREAD

**Issue by kamranahmedse** [fastlane/fastlane#12636]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Keeps failing with exit code 65 when archiving. I have checked the logs and couldn't find any meaningful indicators.

<details>
    <summary>Here is the fastlane output from the section where it fails</summary>

```
▸ Compiling LaunchScreen.xib
▸ Processing Info.plist
▸ Generating 'loremipsum.app.dSYM'
▸ Running script 'Bundle React Native code and images'
the transform cache was reset.
▸ Touching loremipsum.app
▸ Signing /Users/kamranahmed/Library/Developer/Xcode/DerivedData/loremipsum-dldzryeabysysnfwufszrziyhmom/Build/Intermediates.noindex/ArchiveIntermediates/loremipsum/InstallationBuildProductsLocation/Applications/loremipsum.app
▸ Touching loremipsum.app.dSYM
** ARCHIVE FAILED **
ERROR [2018-05-29 14:40:00.52]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.96.1                  |
| export_method | development             |
| sdk           | iPhoneOS11.3.sdk        |
+---------------+-------------------------+

INFO [2018-05-29 14:40:00.57]: ▸ Touch /Users/kamranahmed/Library/Developer/Xcode/DerivedData/loremipsum-dldzryeabysysnfwufszrziyhmom/Build/Intermediates.noindex/ArchiveIntermediates/loremipsum/BuildProductsPath/Release-iphoneos/loremipsum.app.dSYM
INFO [2018-05-29 14:40:00.57]: ▸     cd /Users/kamranahmed/Workspace/loremipsum/loremipsum-hybrid/ios
INFO [2018-05-29 14:40:00.57]: ▸     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/lib/ruby/gems/2.5.0/bin:/Users/kamranahmed/.rbenv/shims:/usr/local/php5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/node/9.8.0/bin:/usr/local/go/bin:/Users/kamranahmed/gospace/bin:/usr/local/opt/go/libexec/bin:/Users/kamranahmed/.composer/vendor/bin"
INFO [2018-05-29 14:40:00.57]: ▸     /usr/bin/touch -c /Users/kamranahmed/Library/Developer/Xcode/DerivedData/loremipsum-dldzryeabysysnfwufszrziyhmom/Build/Intermediates.noindex/ArchiveIntermediates/loremipsum/BuildProductsPath/Release-iphoneos/loremipsum.app.dSYM
INFO [2018-05-29 14:40:00.57]:
ERROR [2018-05-29 14:40:00.58]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
WARN [2018-05-29 14:40:00.58]: 📋  For the complete and more detailed error log, check the full log at:
WARN [2018-05-29 14:40:00.58]: 📋  /Users/kamranahmed/Library/Logs/gym/loremipsum-loremipsum.log
INFO [2018-05-29 14:40:00.58]:
ERROR [2018-05-29 14:40:00.58]: Your `export_method` in gym is defined as `development`
ERROR [2018-05-29 14:40:00.58]: which might cause problems when signing your application
ERROR [2018-05-29 14:40:00.58]: Are you sure want to build and export for development?
ERROR [2018-05-29 14:40:00.58]: Please make sure to define the correct export methods when calling
ERROR [2018-05-29 14:40:00.58]: gym in your Fastfile or from the command line
INFO [2018-05-29 14:40:00.58]:
INFO [2018-05-29 14:40:00.58]:
ERROR [2018-05-29 14:40:00.58]: Looks like fastlane ran into a build/archive error with your project
ERROR [2018-05-29 14:40:00.58]: It's hard to tell what's causing the error, so we wrote some guides on how
ERROR [2018-05-29 14:40:00.58]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
ERROR [2018-05-29 14:40:00.58]: Before submitting an issue on GitHub, please follow the guide above and make
ERROR [2018-05-29 14:40:00.58]: sure your project is set up correctly.
ERROR [2018-05-29 14:40:00.58]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
ERROR [2018-05-29 14:40:00.58]: the full commands printed out in yellow in the above log.
ERROR [2018-05-29 14:40:00.58]: Make sure to inspect the output above, as usually you'll find more error information there
INFO [2018-05-29 14:40:00.58]:
WARN [2018-05-29 14:40:00.58]: Lane Context:
INFO [2018-05-29 14:40:00.58]: {:PLATFORM_NAME=>:ios, :LANE_NAME=>"ios alpha", :SIGH_PROFILE_TYPE=>"development", :MATCH_PROVISIONING_PROFILE_MAPPING=>{"com.loremipsum.app"=>"match Development com.loremipsum.app"}}
ERROR [2018-05-29 14:40:00.58]: Error building the application - see the log above
INFO [2018-05-29 14:40:00.58]: Successfully generated documentation at path '/Users/kamranahmed/Workspace/loremipsum/loremipsum-hybrid/fastlane/README.md'

+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | Verifying fastlane version      | 0           |
| 2    | automatic_code_signing          | 0           |
| 3    | Switch to ios certificates lane | 0           |
| 4    | match                           | 7           |
| 💥   | gym                             | 126         |
+------+---------------------------------+-------------+

ERROR [2018-05-29 14:40:00.59]: fastlane finished with errors
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneBuildFailure: [!] Error building the application - see the log above
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/gym/lib/gym/error_handler.rb:73:in `handle_build_error'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/gym/lib/gym/runner.rb:97:in `block in build_app'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/command_executor.rb:93:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/gym/lib/gym/runner.rb:93:in `build_app'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/gym/lib/gym/runner.rb:18:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/gym/lib/gym/manager.rb:19:in `work'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/actions/build_ios_app.rb:64:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `chdir'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:24:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```
</details>

### Environment

Have a look at the output from `env` command below. I have also uploaded all my fastlane files [in this gist](https://gist.github.com/kamranahmedse/6e51950d2b212505b454d88fc17bad99) if that helps.

<details><summary>Fastlane environment</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.96.1'

# before_all do
#  ensure_git_branch
#  ensure_git_status_clean
#  git_pull
# end

platform :ios do
   automatic_code_signing(
     path: "ios/loremipsum.xcodeproj",
     use_automatic_signing: false,
     profile_name: "match Development com.loremipsum.app"
   )

   desc 'Fetch certificates and provisioning profiles'
   lane :certificates do
     match(app_identifier: 'com.loremipsum.app', type: 'development', readonly: true)
   end

   desc 'Build and Ship to Testflight.'
   lane :alpha do
     certificates
     gym(
      scheme: 'loremipsum',
      project: 'ios/loremipsum.xcodeproj',
      export_method: 'development',
      output_directory: "./native_builds/",
      archive_path: "./native_builds/loremipsum_ios",
      clean: true
     )
     pilot
   end
end

platform :android do
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: '../android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: '../android/')
  end

  desc "Submit a new Alpha Build to Play Store"
  lane :alpha do
    build
    supply(track: "alpha", apk: "../android/app/build/outputs/apk/app-release.apk") # Upload the APK to the Play Store (alpha)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
# https://docs.fastlane.tools/advanced/#appfile

# iOS
app_identifier("com.loremipsum.app")
apple_id("Apple-dev@loremipsum.com")

itc_team_id("230325677") # iTunes Connect Team ID
team_id("6NKC9IQ0YL")    # Developer Portal Team ID

# Android
json_key_file "./google-play-api-secret.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.loremipsum.app" # Your Android app package

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.3        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-05-29**
</details>

**Comment by kamranahmedse** [comment]
Got it to work. If it may help anyone, I am using react native, all I had to do was

```bash
rm -rf ios
react-native upgrade
react-native link
```
and revoke my certificates and provisioning profiles

```bash
bundle exec fastlane match nuke development
```
