### ISSUE TITLE
The login credentials for '<username>' seem to be wrong.

### ISSUE THREAD

**Issue by rndcmo** [fastlane/fastlane#1265]
I am trying to user fastlane and keep getting this authentication failed error.  I have tried this just running sigh to prompt for username and password but getting the same error.  I have logged into the dev portal just fine with the username and password I am entering for sigh.

Here is the output:
Do you want to re-enter your password? (y/n)
y
Removing Keychain entry for user '<username>@<co>.com'...
keychain: "/Users/<user>/Library/Keychains/login.keychain"
class: "inet"
attributes:
    0x00000007 <blob>="deliver.<username>@<co>.com"
    0x00000008 <blob>=<NULL>
    "acct"<blob>="<username>@<co>.com"
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303136303230323135353434375A00  "20160202155447Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303136303230323135353434375A00  "20160202155447Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="deliver.<username>@<co>.com"
    "type"<uint32>=<NULL>
password has been deleted.
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` env variable
More information about it on GitHub: https://github.com/fastlane/credentials_manager
-------------------------------------------------------------------------------------
Password (for <username>@<co>.com): ********
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/automation/.rvm/gems/ruby-2.2.0@global/gems/spaceship-0.19.3/lib/spaceship/client.rb:268:in `parse_response': [!] {"responseId"=>"fa020fe4-4df7-4e83-9c61-511d12df9527", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2016-02-02T15:54:53Z", "protocolVersion"=>"QH65B2", "requestId"=>nil, "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200} (Spaceship::Client::UnexpectedResponse)
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/spaceship-0.19.3/lib/spaceship/portal/portal_client.rb:62:in `teams'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/spaceship-0.19.3/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/spaceship-0.19.3/lib/spaceship/portal/portal_client.rb:78:in `select_team'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/spaceship-0.19.3/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/spaceship-0.19.3/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/sigh-1.3.0/lib/sigh/runner.rb:16:in `run'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/sigh-1.3.0/lib/sigh/manager.rb:7:in `start'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/sigh-1.3.0/bin/sigh:35:in `block (2 levels) in run'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/sigh-1.3.0/bin/sigh:90:in `run'
	from /Users/automation/.rvm/gems/ruby-2.2.0@global/gems/sigh-1.3.0/bin/sigh:108:in `<top (required)>'
	from /Users/automation/.rvm/rubies/ruby-2.2.0/bin/sigh:23:in `load'
	from /Users/automation/.rvm/rubies/ruby-2.2.0/bin/sigh:23:in `<main>'

**Comment by rndcmo** [comment]
This appeared to be an issue with the certificate not being installed.
