### ISSUE TITLE
undefined method `compact' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by kai60** [fastlane/fastlane#12652]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[Traceback (most recent call last):
	37: from /usr/local/bin/fastlane:23:in `<main>'
	36: from /usr/local/bin/fastlane:23:in `load'
	35: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/bin/fastlane:20:in `<top (required)>'
	34: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	33: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	32: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	31: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	30: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	29: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	28: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	27: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	26: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	25: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	24: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	23: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	21: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	19: from Fastfile:21:in `block (2 levels) in parsing_binding'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/actions/get_certificates.rb:17:in `run'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/cert/lib/cert/runner.rb:13:in `launch'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/cert/lib/cert/runner.rb:34:in `run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/cert/lib/cert/runner.rb:24:in `login'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/spaceship/lib/spaceship/portal/spaceship.rb:98:in `login'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/spaceship/lib/spaceship/client.rb:72:in `login'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/spaceship/lib/spaceship/client.rb:364:in `login'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/spaceship/lib/spaceship/client.rb:663:in `do_login'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/spaceship/lib/spaceship/portal/portal_client.rb:27:in `send_login_request'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/spaceship/lib/spaceship/client.rb:459:in `send_shared_login_request'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/spaceship/lib/spaceship/client.rb:498:in `fetch_olympus_session': [!] undefined method `compact' for nil:NilClass (NoMethodError)]</pre>
</details>

### Environment

<details>
  <pre>[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.2                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :fly do
   cert
   sigh
   gym(scheme:"E-Mobile");
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
 app_identifier("com.xxxx.xxxxxx") 
 apple_id("xxxxxxxx.com") 


 
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.96.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.3        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-05-30**
</details>]</pre>
</details>

**Comment by kai60** [comment]
I know there no "compact" method why would this happen anyhelp? I am not familiar with ruby

**Comment by taquitos** [comment]
@kai60 I'm wondering if the AppleID you're using to sign might not have an iTunes Connect account
- Can you try manually logging into Apple Developer Center and iTunesConnect on the Web and confirm that works?

**Comment by kai60** [comment]
@taquitos YES, I am  sure  I can login in the Apple Developer Center and  iTunes Connect，but still the same error. At first，I am able to login in Apple Developer Center  and create certificates and profile but can not get to   iTunes Connect ，the fastlane just shows "can not login and need to acknowledge to Apple's Apple ID and Privacy statement",after, I solved the iTunes Connect stuff and acknowledge the Privacy statement . I did it again, fastlane shows the error above.

**Comment by joshdholtz** [comment]
This is super weird 😔 I am not able to get any account to show a `nil` for `body["availableProviders"]`. We could default the array to an empty array but this shouldn't be `nil` to begin with. 

@taquitos What are your thoughts on `(body["availableProviders"] || []).compact`?

**Comment by taquitos** [comment]
Oh boy, I think we can actually delete that code. I just did a search and we don't use `available_providers` anymore.

**Comment by joshdholtz** [comment]
Aye aye, I will 💣 it

**Comment by kai60** [comment]
@taquitos @joshdholtz @kommen @cbowns @andrew sorry guys, because,I don't actually own the AppleID，I just check the AppleID can login in the ITC，but I didn't find that the AppleID has no right to create an application，just can login! when i get the right permission, problem solved! It's my fault,thankyou，guys.

**Comment by taquitos** [comment]
No problem at all! You helped us find a bug in our code too, so that's great! Now we can handle this situation with a more friendly error message 🎉
