### ISSUE TITLE
fastlane match stuck: git prompts not accessible to the user

### ISSUE THREAD

**Issue by marcelelements** [fastlane/fastlane#12706]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The issue has been seen prior in #9243 - Once fastlane match hits the git clone command, the git process will ask for credentials. This query is muted by fastlane and it is not possible to enter the password at this stage. The match command is stuck at this point and requires multiple Ctrl+Cs to return to the command line. 

Expected behaviour: the ssh key passphrase prompt is presented to the user.

Note that for security reasons I do not want to keep my private key unlocked, so unlike the referenced issue I do not consider that a valid workaround.

##### Steps to reproduce

Several flavours have been tried and give the same result, among which:
- `fastlane match development`
- `bundle exec fastlane match development`
- `bundle exec fastlane match development --verbose --readonly`

Possibly required extra steps to recreate a sufficiently similar environment:
1) have certificates in a non-http git repository protected by a private key (i.e. the repo url takes the form of user@domain:path/to/repo.git)
2) Use a private key that's passphrase protected
3) Run `killall ssh-agent` to prevent autofilling said passphrase

##### Complete output when running fastlane, including the stack trace and command used

(company and project info have been anonymized or -snip-'ed)

<details>
  <pre>$ bundle exec fastlane match development --verbose --readonly
[✔] 🚀 
Successfully loaded Appfile at path '/Development/-snip-/fastlane/Appfile'
- apple_id: 'fastlanematch@domain.com'
- team_id: '-snip-'
- app_identifier: 'com.domain.enterprise.app'
-------
git@git.domain.com:ios/certificates.git
INFO [2018-06-07 11:17:05.38]: Successfully loaded '/Development/-snip-/fastlane/Matchfile' 📄

+---------+---------------------------------------------------+
|         Detected Values from './fastlane/Matchfile'         |
+---------+---------------------------------------------------+
| git_url | git@domain.com:ios/certificates.git |
+---------+---------------------------------------------------+

+-----------------------+---------------------------------------------------+
|                         Summary for match 2.97.0                          |
+-----------------------+---------------------------------------------------+
| verbose               | true                                              |
| readonly              | true                                              |
| type                  | development                                       |
| git_url               | git@git.domain.com:ios/certificates.git |
| git_branch            | master                                            |
| app_identifier        | ["com.domain.enterprise.app"]               |
| username              | fastlanematch@domain.com                         |
| keychain_name         | login.keychain                                    |
| team_id               | -snip-                                        |
| force                 | false                                             |
| skip_confirmation     | false                                             |
| shallow_clone         | false                                             |
| clone_branch_directly | false                                             |
| force_for_new_devices | false                                             |
| skip_docs             | false                                             |
| platform              | ios                                               |
+-----------------------+---------------------------------------------------+

INFO [2018-06-07 11:17:05.39]: Cloning remote git repo...
INFO [2018-06-07 11:17:05.39]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-06-07 11:17:05.39]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@git.domain.com:ios/certificates.git' '/var/folders/lx/xm5xv3556wx2yk_ybwmc6nh00000gp/T/d20180607-3418-16u39x1'
INFO [2018-06-07 11:17:05.40]: ▸ Cloning into '/var/folders/lx/xm5xv3556wx2yk_ybwmc6nh00000gp/T/d20180607-3418-16u39x1'...

^C^CTraceback (most recent call last):
	20: from /usr/local/bin/fastlane:23:in `<main>'
	19: from /usr/local/bin/fastlane:23:in `load'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/bin/fastlane:20:in `<top (required)>'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/match/lib/match/commands_generator.rb:19:in `start'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/match/lib/match/commands_generator.rb:146:in `run'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/match/lib/match/commands_generator.rb:61:in `block (3 levels) in run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/match/lib/match/runner.rb:24:in `run'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/match/lib/match/git_helper.rb:43:in `clone'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/command_executor.rb:51:in `execute'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/fastlane_pty.rb:8:in `spawn'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/fastlane_pty.rb:8:in `spawn'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/fastlane_pty.rb:9:in `block in spawn'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/command_executor.rb:70:in `block in execute'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/command_executor.rb:70:in `ensure in block in execute'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/command_executor.rb:70:in `wait': Interrupt

</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "ca89faad-2093-427e-88c1-1ff3ee0bfce5"

import_from_git(
  url: "git@git.domain.com:ios/fastlane-template.git",
  path: "fastlane/Fastfile",
  version: "~> 1.1.0"
)

platform :ios do
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "fastlanematch@domain.com"
team_id "-snip-"
app_identifier "com.domain.enterprise.app" # unique per project

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.97.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                            | Version | Update-Status  |
| --------------------------------- | ------- | -------------- |
| fastlane-plugin-office_fastlane | 1.2.2   | 💥 Check failed |
| fastlane-plugin-badge             | 1.1.0   | ✅ Up-To-Date   |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.2.0        |
| bundler                                     | 1.16.1       |
| fileutils                                   | 1.0.2        |
| CFPropertyList                              | 3.0.0        |
| public_suffix                               | 2.0.5        |
| addressable                                 | 2.5.2        |
| atomos                                      | 0.1.2        |
| babosa                                      | 1.0.2        |
| curb                                        | 0.9.6        |
| fastimage                                   | 2.1.3        |
| colored                                     | 1.2          |
| highline                                    | 1.7.10       |
| commander-fastlane                          | 4.4.6        |
| dotenv                                      | 2.4.0        |
| emoji_regex                                 | 0.1.1        |
| excon                                       | 0.62.0       |
| multipart-post                              | 2.0.0        |
| faraday                                     | 0.15.2       |
| unf_ext                                     | 0.0.7.5      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20180417 |
| http-cookie                                 | 1.0.3        |
| faraday-cookie_jar                          | 0.0.6        |
| faraday_middleware                          | 0.12.2       |
| gh_inspector                                | 1.1.3        |
| jwt                                         | 2.1.0        |
| little-plugger                              | 1.1.4        |
| multi_json                                  | 1.13.1       |
| logging                                     | 2.2.2        |
| memoist                                     | 0.16.0       |
| os                                          | 0.9.6        |
| signet                                      | 0.8.1        |
| googleauth                                  | 0.6.2        |
| httpclient                                  | 2.8.3        |
| mime-types-data                             | 3.2016.0521  |
| mime-types                                  | 3.1          |
| declarative                                 | 0.0.10       |
| declarative-option                          | 0.1.0        |
| uber                                        | 0.1.0        |
| representable                               | 3.0.4        |
| retriable                                   | 3.1.1        |
| google-api-client                           | 0.21.2       |
| json                                        | 2.1.0        |
| mini_magick                                 | 4.5.1        |
| multi_xml                                   | 0.6.0        |
| plist                                       | 3.4.0        |
| rubyzip                                     | 1.2.1        |
| security                                    | 0.1.3        |
| naturally                                   | 2.2.0        |
| simctl                                      | 1.6.4        |
| slack-notifier                              | 2.3.2        |
| terminal-notifier                           | 1.8.0        |
| unicode-display_width                       | 1.4.0        |
| terminal-table                              | 1.8.0        |
| tty-screen                                  | 0.6.4        |
| tty-cursor                                  | 0.5.0        |
| tty-spinner                                 | 0.8.0        |
| word_wrap                                   | 1.0.0        |
| claide                                      | 1.0.2        |
| colored2                                    | 3.1.2        |
| nanaimo                                     | 0.2.5        |
| xcodeproj                                   | 1.5.9        |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.2.8        |
| xcpretty-travis-formatter                   | 1.0.0        |
| badge                                       | 0.9.1        |
| colorize                                    | 0.8.1        |
| fastlane-plugin-badge                       | 1.1.0        |
| fastlane-plugin-commit_android_version_bump | 0.2.0        |
| fastlane-plugin-increment_version_code      | 0.4.3        |
| mini_portile2                               | 2.3.0        |
| nokogiri                                    | 1.8.2        |
| netrc                                       | 0.11.0       |
| rest-client                                 | 2.0.2        |
| fastlane-plugin-office_fastlane           | 1.2.2        |
</details>

*generated on:* **2018-06-07**
</details></pre>
</details>

**Comment by marcelelements** [comment]
Still broken in 2.99.0
