### ISSUE TITLE
Cannot run fastlane 

### ISSUE THREAD

**Issue by antons81** [fastlane/fastlane#12755]
Hi, trying to run build after fastlane init and getting following error

```
> /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.9/lib/xcodeproj/project.rb:100:in `open': [!] [Xcodeproj] Unable to open `/Users/antons/Desktop/iOS_Projects/FulcrumChat/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj` because it doesn't exist. (RuntimeError)
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/swift_runner_upgrader.rb:38:in `initialize'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/swift_lane_manager.rb:258:in `new'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/swift_lane_manager.rb:258:in `ensure_runner_up_to_date_fastlane!'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/swift_lane_manager.rb:32:in `cruise_lane'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
> 	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
> 	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
> 	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
> 	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.97.0/bin/fastlane:20:in `<top (required)>'
> 	from /usr/local/bin/fastlane:22:in `load'
> 	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by joshdholtz** [comment]
@antons81 Heyyyy 👋 

1) If you could please use one of the provided issue templates next time you create an issue that would be 💯 This helps the maintainers better help you out
2) It looks like you are trying to use Fastlane.swift, is this correct?
3) Has this worked for you before? Or is this your first time trying this out?

**Comment by antons81** [comment]
Hi. I think I resolved this issue, need to run with sudo
