### ISSUE TITLE
"Could not find app with app identifier" 

### ISSUE THREAD

**Issue by Austinate** [fastlane/fastlane#1277]
I had app-id configured in dev-portal properly but had no entry in iTunes connect. 
Fastlane asked me if i'd like to create one and after failed immediately.  
Was able to workaround by creating entry in iTC manually and re-running `fastlane init`. 
```
[14:12:14]: Error occurred with the setup program! Reverting changes now!
[14:12:14]: Deleting the 'fastlane' folder
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/austinate/.rvm/gems/ruby-2.2.1/gems/deliver-1.9.0/lib/deliver/detect_values.rb:30:in `find_app': [!] Could not find app with app identifier '*my_app_id*' in your iTunes Connect account (*my@email* - Team: *team id*) (RuntimeError)
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/deliver-1.9.0/lib/deliver/detect_values.rb:5:in `run!'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/deliver-1.9.0/lib/deliver/runner.rb:8:in `initialize'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:213:in `new'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:213:in `enable_deliver'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:55:in `default_setup'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:33:in `run'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/fastlane-1.57.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/fastlane-1.57.0/bin/fastlane:51:in `block (2 levels) in run'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/fastlane-1.57.0/bin/fastlane:150:in `run'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/fastlane-1.57.0/bin/fastlane:156:in `<top (required)>'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/austinate/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Did you run `fastlane init`? Can you share your complete output and your `Fastfile`?

**Comment by Austinate** [comment]
Sorry, forgot to mention that this happened during fastlane init. I'll try to reproduce and share files when I'll have access to my machine 
Thanks for fast response 👍

**Comment by Austinate** [comment]
Can this happen because i've used this in project with tvos only target?

**Comment by ohwutup** [comment]
hmm, that is possible maybe @Austinate, do you use the same app id for the tvOS app as you do the iOS version?

**Comment by CraigSiemens** [comment]
I'm running into the same issue running `fastlane init` with a brand new app that doesnt exist in iTunes Connect. Here's the complete output I'm getting.

```
$ fastlane init
/Users/craig/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
[21:25:45]: Detected iOS/Mac project in current directory...
[21:25:45]: This setup will help you get up and running in no time.
[21:25:45]: fastlane will check what tools you're already using and set up
[21:25:45]: the tool automatically for you. Have fun! 
[21:25:45]: Created new folder './fastlane'.
2016-02-09 21:25:45.301 xcodebuild[51921:1870632] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSImageNamed.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Your Apple ID (e.g. fastlane@krausefx.com): EMAIL
[21:25:57]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[21:25:57]: Starting login with user 'EMAIL'

+----------------+----------------------------------------------------+
|                           Detected Values                           |
+----------------+----------------------------------------------------+
| Apple ID       | EMAIL                                              |
| App Name       | APP NAME                                           |
| App Identifier | APP ID                                             |
| Project        | PATH                                               |
+----------------+----------------------------------------------------+

[21:26:06]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
Please confirm the above values (y/n)
y
[21:26:08]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
[21:26:08]: Loading up 'deliver', this might take a few seconds
[21:26:08]: Login to iTunes Connect (EMAIL)
[21:26:10]: Login successful
[21:26:14]: Error occurred with the setup program! Reverting changes now!
[21:26:14]: Deleting the 'fastlane' folder
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'b1f1b516e24f723ab6578643dbf44c8a'
The crash report has been stored locally '/tmp/sentry_b1f1b516e24f723ab6578643dbf44c8a.json'
/Users/craig/.rvm/gems/ruby-2.3.0/gems/deliver-1.9.0/lib/deliver/detect_values.rb:30:in `find_app': [!] Could not find app with app identifier 'APP ID' in your iTunes Connect account (EMAIL - Team: TEAM ID) (RuntimeError)
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/deliver-1.9.0/lib/deliver/detect_values.rb:5:in `run!'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/deliver-1.9.0/lib/deliver/runner.rb:8:in `initialize'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:213:in `new'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:213:in `enable_deliver'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:55:in `default_setup'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/fastlane-1.57.0/lib/fastlane/setup/setup_ios.rb:33:in `run'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/fastlane-1.57.0/lib/fastlane/setup/setup.rb:19:in `run'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/fastlane-1.57.0/bin/fastlane:51:in `block (2 levels) in run'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/fastlane-1.57.0/bin/fastlane:150:in `run'
    from /Users/craig/.rvm/gems/ruby-2.3.0/gems/fastlane-1.57.0/bin/fastlane:156:in `<top (required)>'
    from /Users/craig/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
    from /Users/craig/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
    from /Users/craig/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/craig/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ohwutup** [comment]
@Austinate are you an admin on your iTunes Connect team?

**Comment by Austinate** [comment]
@ohwutup sorry for delay in response (timezones ¯\_(ツ)_/¯ ) 
I have account with 1 team, and yes, i'm owner & admin of that team. 

After investigation i can see that right now even for tvos targets match creates Provisioning profiles with iOS target

**Comment by ohwutup** [comment]
@Austinate, yeah, things have been touch with mixing tvOS and iOS targets. do you use the same bundle id (app_identifier) for both?

**Comment by Austinate** [comment]
@ohwutup i have no iOS target in my project at all :)

**Comment by ohwutup** [comment]
hey @Austinate is this still an issue you are running into?

**Comment by ohwutup** [comment]
this should be fixed with some upcoming changes to make the error handling a bit better when there are iTunes connect issues. going to close this for now and please reopen if you have further issues.

**Comment by yanyuqingshi** [comment]
I'm have same issue,which running "fastlane init" on Terminal.
[16:55:11]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[16:55:11]: Starting login with user '111123223@163.com'

+----------------+---------------------------------------------------------------------------+
|                                      Detected Values                                       |
+----------------+---------------------------------------------------------------------------+
| Apple ID       | 111123223@163.com                                                         |
| App Name    |    Test                                                                                  |
| App Identifier |       Identifier                                                                       |
| Workspace      | /Users/Test.xcworkspace |
+----------------+---------------------------------------------------------------------------+
[16:55:44]: Could not find app with app identifier 'identifier' in your iTunes Connect account (eg:111123223@163.com)
[16:55:44]: An error occured during the setup process. Falling back to manual setup!
how to resolve this issue,please.

**Comment by ohwutup** [comment]
Hey @yanyuqingshi, you can definitely keep going though the process here as it is just going to ask you a handful of questions to walk you through manual setup!
