### ISSUE TITLE
Screengrab doesn't work on Android 7.0

### ISSUE THREAD

**Issue by ViktorBylbas** [fastlane/fastlane#12831]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

Errors:
```
java.lang.RuntimeException: Unable to capture screenshot.
at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:56)
at tools.fastlane.screengrab.UiAutomatorScreenshotStrategy.takeScreenshot(UiAutomatorScreenshotStrategy.java:39)
at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)
```

My test:
```
@RunWith(JUnit4.class)
 public class MainActivityTest {
    @ClassRule
     public static final LocaleTestRule localeTestRule = new LocaleTestRule();

    @Rule
     public ActivityTestRule<MainActivity> activityRule = new ActivityTestRule<>(MainActivity.class);

    @Test
    public void testTakeScreenshot() {
         Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy());
        Screengrab.screenshot("Main");
    }
}
```

build.gradle:
`androidTestCompile('tools.fastlane:screengrab:1.2.0')`

AndroidManifest:
```
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.CHANGE_CONFIGURATION" />
```

Help me please. What is the problem?
I using droid 7.0

**Comment by jaroslavas** [comment]
I have the same issue with android 8. You can fix it manually but confirming write permission for the app through Settings. But of course that should be fixed in fastlane to be made automatically!
