### ISSUE TITLE
Unable to install Fastlane on macOS Mojave

### ISSUE THREAD

**Issue by Rubenfer** [fastlane/fastlane#12905]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to install Fastlane on my MacBook Pro with macOS Mojave but I can't due to:

ERROR:  Error installing fastlane:
ERROR: Failed to build gem native extension.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>

HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=fastlane
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/quick/Marshal.4.8/fastlane-2.99.1.gemspec.rz
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=CFPropertyList,addressable,babosa,bundler,colored,commander-fastlane,dotenv,emoji_regex,excon,faraday,faraday-cookie_jar,faraday_middleware,fastimage,gh_inspector,google-api-client,highline,json,mini_magick,multi_json,multi_xml,multipart-post,plist,public_suffix,rubyzip,security,simctl,slack-notifier,terminal-notifier,terminal-table,tty-screen,tty-spinner,word_wrap,xcodeproj,xcpretty,xcpretty-travis-formatter
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=atomos,claide,colored2,nanaimo
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=unicode-display_width
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=http-cookie,naturally,rouge,tty-cursor
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=domain_name,googleauth,httpclient,mime-types,representable,retriable
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=declarative,declarative-option,uber,unf
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=mime-types-data
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=jwt,logging,memoist,os,signet,unf_ext
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=little-plugger
200 OK
GET https://api.rubygems.org/quick/Marshal.4.8/unf_ext-0.0.7.5.gemspec.rz
200 OK
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/.document
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/.gitignore
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/.travis.yml
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/CHANGELOG.md
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/Gemfile
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/LICENSE.txt
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/README.md
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/Rakefile
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext/extconf.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext/unf.cc
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext/unf/normalizer.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext/unf/table.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext/unf/trie/char_stream.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext/unf/trie/node.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext/unf/trie/searcher.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext/unf/util.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/lib/unf_ext.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/lib/unf_ext/version.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/test/helper.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/test/normalization-test.txt
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/test/test_unf_ext.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/unf_ext.gemspec
Building native extensions.  This could take a while...
current directory: /Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180715-872-js1mr6.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:535:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:532:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:6:in `<main>'
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.5 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5/gem_make.out

</pre>
</details>

**Comment by Rubenfer** [comment]
Update:

mkmf.log file contains:

> "xcrun clang -o conftest -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS -iwithsysroot /usr/local/libressl/include conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib -L.     -lruby.2.3.0  -lpthread -ldl -lobjc "
In file included from conftest.c:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^~~~~~~~~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

**Comment by Rubenfer** [comment]
Solved changing Xcode command line tools to Xcode 10
