### ISSUE TITLE
Fastlane won't upload IPA to Crashlytics Beta

### ISSUE THREAD

**Issue by fabiogomezdiaz** [fastlane/fastlane#12945]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I used to be able to run the `beta` lane, which builds the code, creates an IPA, and then uploads it to Crashlytics.

But for whatever reason, the `send_to_crashlytics` lane errors out and does not really tell you what's wrong. So I tried running the `build` pipeline separately to get an IPA, and then passed the IPA path to `send_to_crashlytics` lane and still get the same explanation-less error.

Any thoughts on what's going on and how I can fix this? I am forced to manually build an archive using Xcode and send it to Crashlytics Beta using the Fabric Mac App.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>Ignoring executable-hooks-1.4.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.4.2
Ignoring gem-wrappers-1.3.2 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.3.2
[✔] 🚀
[19:07:25]: ----------------------------------------
[19:07:25]: --- Step: Verifying fastlane version ---
[19:07:25]: ----------------------------------------
[19:07:25]: Your fastlane version 2.100.1 matches the minimum requirement of 2.100.1  ✅
[19:07:25]: ------------------------------
[19:07:25]: --- Step: default_platform ---
[19:07:25]: ------------------------------
[19:07:25]: Driving the lane 'ios send_to_crashlytics' 🚀
[19:07:25]: -------------------------
[19:07:25]: --- Step: crashlytics ---
[19:07:25]: -------------------------
[19:07:25]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[19:07:47]: Shell command exited with exit status  instead of 0.
[19:07:47]: -------------------
[19:07:47]: --- Step: slack ---
[19:07:47]: -------------------
[19:07:48]: Successfully sent Slack notification
+------------------+-------------------------+
|                Lane Context                |
+------------------+-------------------------+
| DEFAULT_PLATFORM | ios                     |
| PLATFORM_NAME    | ios                     |
| LANE_NAME        | ios send_to_crashlytics |
+------------------+-------------------------+
[19:07:48]: 2018-07-22 19:07:25.202 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | crashlytics                | 22          |
| 4    | slack                      | 0           |
+------+----------------------------+-------------+

[19:07:48]: fastlane finished with errors

[!] 2018-07-22 19:07:25.202 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane                            |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Most values are stored in environment variables
# Check out env.sh for the available environment variables

fastlane_version "2.100.1"

# To get the name of the available environment variables, run
# fastlane action [action_name].

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #

  desc "Test that fastlane is working"
  lane :test do |options|
    sh("echo testing things")
  end

  desc "Upload a new build to Crashlytics"
  lane :beta do |options|
    build(options)
    send_to_crashlytics
    notify_slack
  end

  desc "Provision, take screenshots, build and upload to App Store"
  lane :send_to_appstore do |options|
    #provision
    #screenshot
    #snapshot

    build(options)

    if options[:release_notes]
      deliver(
        release_notes: options[:release_notes]
      )
    else
      deliver
    end

    notify_slack(
      message: "Submitted Build \"" + options[:build_number] + "\" to App Store and for Review"
    )
  end


  # UTILITY LANES
  desc "Install Pods"
  lane :install_pods do
    cocoapods(
      try_repo_update_on_error: true
    )
  end

  desc "Install Pods, Increment Build Number, then Build Code"
  lane :build do |options|
    # Code Signing
    match(force_for_new_devices: true)

    # Cocoapods
    install_pods

    # Read in value in case the user has specified input params
    if options[:build_number]
      increment_build_number(
        build_number: options[:build_number]
      )
    else
      increment_build_number
    end

    # Build the code
    gym
  end

  # CRASHLYTICS
  desc "Send Build to Crashlytics"
  lane :send_to_crashlytics do
    crashlytics(
      ipa_path: "./build/unWine.ipa"
    )
  end

  # SLACK
  desc "Notify Slack"
  lane :notify_slack do |options|
    if options[:message]
      slack(
        message: options[:message],
        success: true,
        slack_url: ENV["SLACK_BETA_URL"]
      )
    else
      slack(
        success: true,
        slack_url: ENV["SLACK_BETA_URL"]
      )
    end
  end

  lane :register do |options|
    register_device
    match(force_for_new_devices: true)
  end

end

# Lanes executed by all other lanes
after_all do |lane|
  # This block is called, only if the executed lane was successful
  if ENV["SLACK_URL"] && (lane == "send_to_crashlytics")
    slack(
      message: nil,
      success: true,
      default_payloads: [:test_result, :git_branch]
    )
  end

  #clean_build_artifacts
end

error do |lane, exception|
  if ENV["SLACK_URL"]
    slack(
      message: exception.to_s,
      success: false
    )
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.100.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.3       |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| ZenTest                   | 4.11.1       |
| RubyInline                | 3.12.4       |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.3        |
| dotenv                    | 2.5.0        |
| osx_keychain              | 1.0.2        |
| cocoapods-keys            | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-07-22**
</details></pre>
</details>

**Comment by fabiogomezdiaz** [comment]
I ran the `send_to_crashlytics` lane with `debug` set to `true` on the `crashlytics` function. I also enabled verbose loggin on fastlane and this is what I ended up with. Not sure if it helps

```bash
$ bundle exec fastlane send_to_crashlytics --verbose
Ignoring executable-hooks-1.4.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.4.2
Ignoring gem-wrappers-1.3.2 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.3.2
[✔] 🚀
DEBUG [2018-07-23 08:06:01.68]: Checking if there are any plugins that should be loaded...
INFO [2018-07-23 08:06:01.84]: ----------------------------------------
INFO [2018-07-23 08:06:01.84]: --- Step: Verifying fastlane version ---
INFO [2018-07-23 08:06:01.84]: ----------------------------------------
INFO [2018-07-23 08:06:01.84]: Your fastlane version 2.100.1 matches the minimum requirement of 2.100.1  ✅
INFO [2018-07-23 08:06:01.85]: ------------------------------
INFO [2018-07-23 08:06:01.85]: --- Step: default_platform ---
INFO [2018-07-23 08:06:01.85]: ------------------------------
INFO [2018-07-23 08:06:01.85]: Driving the lane 'ios send_to_crashlytics' 🚀
INFO [2018-07-23 08:06:01.85]: -------------------------
INFO [2018-07-23 08:06:01.85]: --- Step: crashlytics ---
INFO [2018-07-23 08:06:01.85]: -------------------------
INFO [2018-07-23 08:06:01.85]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2018-07-23 08:06:01.85]: ./Pods/Crashlytics/submit [[API_TOKEN]] [[BUILD_SECRET]] -ipaPath './build/unWine.ipa' -emails 'fabiongo123@hotmail.com' -notesPath '/var/folders/d3/l2hvgd0n0d16cvmzd32djrg00000gq/T/changelog20180723-94817-ksb3b5' -groupAliases 'unwine' -notifications YES -debug YES
ERROR [2018-07-23 08:06:19.62]: Shell command exited with exit status  instead of 0.
INFO [2018-07-23 08:06:19.62]: -------------------
INFO [2018-07-23 08:06:19.62]: --- Step: slack ---
INFO [2018-07-23 08:06:19.62]: -------------------
INFO [2018-07-23 08:06:19.96]: Successfully sent Slack notification
WARN [2018-07-23 08:06:19.96]: Lane Context:
INFO [2018-07-23 08:06:19.96]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios send_to_crashlytics"}
ERROR [2018-07-23 08:06:19.96]: 2018-07-23 08:06:01.871 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)
2018-07-23 08:06:01.878 submit Crashlytics: Path to IPA manually provided: ./build/unWine.ipa
2018-07-23 08:06:03.692 submit Crashlytics: Path To App: /var/folders/d3/l2hvgd0n0d16cvmzd32djrg00000gq/T/unWine/Payload/unWine.app

INFO [2018-07-23 08:06:19.96]: Successfully generated documentation at path '/Users/fabiogomez/Documents/unwine-ios/unWine/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | crashlytics                | 17          |
| 4    | slack                      | 0           |
+------+----------------------------+-------------+

ERROR [2018-07-23 08:06:19.97]: fastlane finished with errors
FastlaneCore::Interface::FastlaneError: [!] 2018-07-23 08:06:01.871 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)
2018-07-23 08:06:01.878 submit Crashlytics: Path to IPA manually provided: ./build/unWine.ipa
2018-07-23 08:06:03.692 submit Crashlytics: Path To App: /var/folders/d3/l2hvgd0n0d16cvmzd32djrg00000gq/T/unWine/Payload/unWine.app

  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/actions/crashlytics.rb:42:in `block in run'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/helper/sh_helper.rb:78:in `sh_control_output'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/actions/crashlytics.rb:45:in `run'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:82:in `block (2 levels) in parsing_binding'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/gems/fastlane-2.100.1/bin/fastlane:20:in `<top (required)>'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/bin/fastlane:22:in `load'
  /Users/fabiogomez/.rvm/gems/ruby-2.4.1/bin/fastlane:22:in `<top (required)>'
bundler: failed to load command: fastlane (/Users/fabiogomez/.rvm/gems/ruby-2.4.1/bin/fastlane)
```

**Comment by joshdholtz** [comment]
@fabiogomezdiaz Heyyy 👋 This is an issue with the version of Crashlytics that you have installed (see https://github.com/fastlane/fastlane/issues/12820). Crashlytics shipped with a bad binary (1.3.5) that was fixed in Crashlytics `3.10.5` (which has a binary of 1.3.6). The version of the binary that you have (1.3.5) had a bug where uploading with notes would cause a segfault (which is fixed in 1.3.6)

Solution - https://github.com/fastlane/fastlane/issues/12820#issuecomment-404222985

**Comment by fabiogomezdiaz** [comment]
@joshdholtz sweet, thanks. Will check it out and close after I confirm it works

**Comment by Kalvin126** [comment]
```
+ bundle exec fastlane upload_to_crashlytics
+------------------------+---------+--------+
|               Used plugins                |
+------------------------+---------+--------+
| Plugin                 | Version | Action |
+------------------------+---------+--------+
| fastlane-plugin-simctl | 0.2.1   | simctl |
+------------------------+---------+--------+

[10:56:15]: ----------------------------------------
[10:56:15]: --- Step: Verifying fastlane version ---
[10:56:15]: ----------------------------------------
[10:56:15]: Your fastlane version 2.101.1 matches the minimum requirement of 2.86.0  ✅
[10:56:15]: ------------------------------
[10:56:15]: --- Step: default_platform ---
[10:56:15]: ------------------------------
[10:56:15]: ----------------------------------------
[10:56:15]: --- Step: Verifying fastlane version ---
[10:56:15]: ----------------------------------------
[10:56:15]: Your fastlane version 2.101.1 matches the minimum requirement of 2.86.0  ✅
[10:56:15]: ----------------------------------------
[10:56:15]: --- Step: Verifying fastlane version ---
[10:56:15]: ----------------------------------------
[10:56:15]: Your fastlane version 2.101.1 matches the minimum requirement of 2.86.0  ✅
[10:56:15]: Driving the lane 'ios upload_to_crashlytics' 🚀
[10:56:15]: -----------------------
[10:56:15]: --- Step: preflight ---
[10:56:15]: -----------------------
[10:56:15]: -----------------------------
[10:56:15]: --- Step: last_git_commit ---
[10:56:15]: -----------------------------
[10:56:15]: -----------------------------
[10:56:15]: --- Step: last_git_commit ---
[10:56:15]: -----------------------------
[10:56:16]: ------------------------
[10:56:16]: --- Step: git_branch ---
[10:56:16]: ------------------------
[10:56:16]: -------------------------
[10:56:16]: --- Step: crashlytics ---
[10:56:16]: -------------------------
[10:56:16]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[10:56:54]: Shell command exited with exit status 1 instead of 0.
+------------------+---------------------------+
|                 Lane Context                 |
+------------------+---------------------------+
| DEFAULT_PLATFORM | ios                       |
| PLATFORM_NAME    | ios                       |
| LANE_NAME        | ios upload_to_crashlytics |
+------------------+---------------------------+
[10:56:54]: 2018-08-09 10:56:16.059 submit Crashlytics: Crashlytics.framework/submit 1.3.6 (19)
2018-08-09 10:56:16.064 submit Crashlytics: Path to IPA manually provided: PayPal Business.ipa
2018-08-09 10:56:19.038 submit Crashlytics: Path To App: /var/folders/vx/vcqcqkmd6vb_1zz_ttn75cs40000gn/T/PayPal Business/Payload/PayPal Business.app
2018-08-09 10:56:35.905 submit Crashlytics: Added Release Notes Successfully 200
2018-08-09 10:56:36.307 submit Crashlytics: Added Testers/Groups Successfully 200
2018-08-09 10:56:36.346 submit Crashlytics: Submitting IPA at /var/folders/vx/vcqcqkmd6vb_1zz_ttn75cs40000gn/T/com.crashlytics.mac/distributions/30F8ED1E-C99E-44A7-BAF1-DF8101BA9E7F.ipa
2018-08-09 10:56:53.663 submit Crashlytics: Unable to submit build. Response code: 0
2018-08-09 10:56:54.296 submit Crashlytics: Failed to upload binary


+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | Verifying fastlane version | 0           |
| 4    | Verifying fastlane version | 0           |
| 5    | preflight                  | 0           |
| 6    | last_git_commit            | 0           |
| 7    | last_git_commit            | 0           |
| 8    | git_branch                 | 0           |
| 💥   | crashlytics                | 38          |
+------+----------------------------+-------------+

[10:56:54]: fastlane finished with errors

[!] 2018-08-09 10:56:16.059 submit Crashlytics: Crashlytics.framework/submit 1.3.6 (19)
2018-08-09 10:56:16.064 submit Crashlytics: Path to IPA manually provided: PayPal Business.ipa
2018-08-09 10:56:19.038 submit Crashlytics: Path To App: /var/folders/vx/vcqcqkmd6vb_1zz_ttn75cs40000gn/T/PayPal Business/Payload/PayPal Business.app
2018-08-09 10:56:35.905 submit Crashlytics: Added Release Notes Successfully 200
2018-08-09 10:56:36.307 submit Crashlytics: Added Testers/Groups Successfully 200
2018-08-09 10:56:36.346 submit Crashlytics: Submitting IPA at /var/folders/vx/vcqcqkmd6vb_1zz_ttn75cs40000gn/T/com.crashlytics.mac/distributions/30F8ED1E-C99E-44A7-BAF1-DF8101BA9E7F.ipa
2018-08-09 10:56:53.663 submit Crashlytics: Unable to submit build. Response code: 0
2018-08-09 10:56:54.296 submit Crashlytics: Failed to upload binary

script returned exit code 1
```

**Comment by Kalvin126** [comment]
```
+ bundle exec fastlane upload_to_crashlytics
+------------------------+---------+--------+
|               Used plugins                |
+------------------------+---------+--------+
| Plugin                 | Version | Action |
+------------------------+---------+--------+
| fastlane-plugin-simctl | 0.2.1   | simctl |
+------------------------+---------+--------+

[10:56:15]: ----------------------------------------
[10:56:15]: --- Step: Verifying fastlane version ---
[10:56:15]: ----------------------------------------
[10:56:15]: Your fastlane version 2.101.1 matches the minimum requirement of 2.86.0  ✅
[10:56:15]: ------------------------------
[10:56:15]: --- Step: default_platform ---
[10:56:15]: ------------------------------
[10:56:15]: ----------------------------------------
[10:56:15]: --- Step: Verifying fastlane version ---
[10:56:15]: ----------------------------------------
[10:56:15]: Your fastlane version 2.101.1 matches the minimum requirement of 2.86.0  ✅
[10:56:15]: ----------------------------------------
[10:56:15]: --- Step: Verifying fastlane version ---
[10:56:15]: ----------------------------------------
[10:56:15]: Your fastlane version 2.101.1 matches the minimum requirement of 2.86.0  ✅
[10:56:15]: Driving the lane 'ios upload_to_crashlytics' 🚀
[10:56:15]: -----------------------
[10:56:15]: --- Step: preflight ---
[10:56:15]: -----------------------
[10:56:15]: -----------------------------
[10:56:15]: --- Step: last_git_commit ---
[10:56:15]: -----------------------------
[10:56:15]: -----------------------------
[10:56:15]: --- Step: last_git_commit ---
[10:56:15]: -----------------------------
[10:56:16]: ------------------------
[10:56:16]: --- Step: git_branch ---
[10:56:16]: ------------------------
[10:56:16]: -------------------------
[10:56:16]: --- Step: crashlytics ---
[10:56:16]: -------------------------
[10:56:16]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[10:56:54]: Shell command exited with exit status 1 instead of 0.
+------------------+---------------------------+
|                 Lane Context                 |
+------------------+---------------------------+
| DEFAULT_PLATFORM | ios                       |
| PLATFORM_NAME    | ios                       |
| LANE_NAME        | ios upload_to_crashlytics |
+------------------+---------------------------+
[10:56:54]: 2018-08-09 10:56:16.059 submit Crashlytics: Crashlytics.framework/submit 1.3.6 (19)
2018-08-09 10:56:16.064 submit Crashlytics: Path to IPA manually provided: redact.ipa
2018-08-09 10:56:19.038 submit Crashlytics: Path To App: /var/folders/vx/vcqcqkmd6vb_1zz_ttn75cs40000gn/T/Refact/Payload/redact.app
2018-08-09 10:56:35.905 submit Crashlytics: Added Release Notes Successfully 200
2018-08-09 10:56:36.307 submit Crashlytics: Added Testers/Groups Successfully 200
2018-08-09 10:56:36.346 submit Crashlytics: Submitting IPA at /var/folders/vx/vcqcqkmd6vb_1zz_ttn75cs40000gn/T/com.crashlytics.mac/distributions/30F8ED1E-C99E-44A7-BAF1-DF8101BA9E7F.ipa
2018-08-09 10:56:53.663 submit Crashlytics: Unable to submit build. Response code: 0
2018-08-09 10:56:54.296 submit Crashlytics: Failed to upload binary


+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | Verifying fastlane version | 0           |
| 4    | Verifying fastlane version | 0           |
| 5    | preflight                  | 0           |
| 6    | last_git_commit            | 0           |
| 7    | last_git_commit            | 0           |
| 8    | git_branch                 | 0           |
| 💥   | crashlytics                | 38          |
+------+----------------------------+-------------+

[10:56:54]: fastlane finished with errors

[!] 2018-08-09 10:56:16.059 submit Crashlytics: Crashlytics.framework/submit 1.3.6 (19)
2018-08-09 10:56:16.064 submit Crashlytics: Path to IPA manually provided: Redact.ipa
2018-08-09 10:56:19.038 submit Crashlytics: Path To App: /var/folders/vx/vcqcqkmd6vb_1zz_ttn75cs40000gn/T/Redact/Payload/redact.ipa
2018-08-09 10:56:35.905 submit Crashlytics: Added Release Notes Successfully 200
2018-08-09 10:56:36.307 submit Crashlytics: Added Testers/Groups Successfully 200
2018-08-09 10:56:36.346 submit Crashlytics: Submitting IPA at /var/folders/vx/vcqcqkmd6vb_1zz_ttn75cs40000gn/T/com.crashlytics.mac/distributions/30F8ED1E-C99E-44A7-BAF1-DF8101BA9E7F.ipa
2018-08-09 10:56:53.663 submit Crashlytics: Unable to submit build. Response code: 0
2018-08-09 10:56:54.296 submit Crashlytics: Failed to upload binary

script returned exit code 1
```

**Comment by Kalvin126** [comment]
huh. Even though above says it failed to upload the binary, I can actually see it succeeded as the build is available on Crashlytics

**Comment by fabiogomezdiaz** [comment]
I updated Crashlytics pod and it all worked. Closing this issue.
