### ISSUE TITLE
Fastlane match init fails to intialize

### ISSUE THREAD

**Issue by miteshkotak** [fastlane/fastlane#12965]
### New Issue Checklist

- [ yes] Updated fastlane to the latest version
- [ yes] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ yes] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ yes] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
fastlane match init ( not working )

#####  output when running fastlane match init

fastlane match init 
[✔] 🚀 

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:230:in `mkdir': [!] Operation not permitted @ dir_s_mkdir - /Users/sieglinde.fischer/.fastlane (Errno::EPERM)
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:230:in `fu_mkdir'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:208:in `block (2 levels) in mkdir_p'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:206:in `reverse_each'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:206:in `block in mkdir_p'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:191:in `each'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/module.rb:28:in `fastlane_user_dir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:57:in `did_show_message?'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:22:in `action_launched'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.100.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:72:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.100.1/match/lib/match/commands_generator.rb:146:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.100.1/match/lib/match/commands_generator.rb:19:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.100.1/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.100.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

Even after setting up environment variable it's still showing the same issue.

**Comment by miteshkotak** [comment]
Fastlane match init fails to intialize

**Comment by miteshkotak** [comment]
file permission issue solved file was locked in mac file system
