### ISSUE TITLE
Impressions of using fastlane on Windows

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#12987]
I am currently playing around with fastlane on Windows for #11687 and this will be a collection of things I notice that should be taken care of or fixed:

- cmd.exe and Powershell don't display "special characters" like the spinner:
```
[✔] 🚀
```

displays as

![image](https://user-images.githubusercontent.com/183673/43419201-94204466-9440-11e8-93ca-80a7ff2aa9f8.png)
- UTF-8 problem:
```
[18:42:54]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment
-variables
```
- screengrab doesn't recognize adb.exe as adb: https://github.com/fastlane/fastlane/issues/13681
- ~~screengrab: "No child processes": https://github.com/fastlane/fastlane/issues/12144~~
- Update notice for `fastlane-v` contains `sudo`, which is not available on Windows:
```
PS C:\Projects> fastlane -v
fastlane installation at path:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.100.1/bin/fastlane
-----------------------------
[✔] 🚀
[...]

#######################################################################
# fastlane 2.101.0 is available. You are on 2.100.1.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.101.0 Improvements
* [supply] added new timeout option (#12981) via Josh Holtz
[...]
* [supply] make Google API Client gemspec version looser (#12918) via Takeru Chuganji

Please update using `sudo gem install fastlane`
```
* Both `oclint` and `swiftlint` actions use `which ...` to find the executable, which does not exist on Windows in Powershell or cmd.exe:
https://github.com/fastlane/fastlane/blob/3bc37e5dbd4fc319ce0688e582fe0e9aff31a4b2/fastlane/lib/fastlane/actions/oclint.rb#L11
https://github.com/fastlane/fastlane/blob/3bc37e5dbd4fc319ce0688e582fe0e9aff31a4b2/fastlane/lib/fastlane/actions/swiftlint.rb#L5
Alternative: https://stackoverflow.com/a/304447/252627
* `verify_build` action uses `unzip` which is unknown to Powershell and cmd.exe:
https://github.com/fastlane/fastlane/blob/3bc37e5dbd4fc319ce0688e582fe0e9aff31a4b2/fastlane/lib/fastlane/actions/verify_build.rb#L30
* Curious: Running `bundle exec rspec` in cmd.exe and Powershell returns a lot less tests than in Cmder:
```
3550 examples, 36 failures, 24 pending
```
vs.
```
5361 examples, 7 failures, 199 pending
```
* Cmd also doesn't like _some_ kind of emojis:
```
[23:31:18]: What would you like to use fastlane for?
1. ­ƒô©  Automate screenshots
2. ­ƒæ®ÔÇìÔ£ê´©Å  Automate beta distribution to TestFlight
3. ­ƒÜÇ  Automate App Store distribution
4. ­ƒøá  Manual setup - manually setup your project to automate your tasks
```
* `echo` works a bit different on Windows:
```
[10:29:20]: Seems like launching fastlane takes a while - please run
[10:29:20]:
[10:29:20]: $ [sudo] gem cleanup
[10:29:20]:
[10:29:20]: to uninstall outdated gems and make fastlane launch faster
[10:29:20]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[10:29:20]: To get started with a Gemfile, run
[10:29:20]:
[10:29:20]: $ bundle init
[10:29:20]: $ echo 'gem "fastlane"' >> Gemfile
[10:29:20]: $ bundle install
[10:29:20]:
[10:29:20]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[10:29:20]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
```
This will create a Gemfile with content:
```
'gem "fastlane"' 
```
Note the additional and breaking `'`
* Mentiones of "macOS keychain" are strange:
```
λ fastlane deliver init
[✔] 🚀
[14:07:39]: To not be asked about this value, you can specify it using 'username'
[14:07:39]: Your Apple ID Username: piotrowski@gmail.com
[14:07:50]: Login to App Store Connect (piotrowski@gmail.com)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
```
* `fastlane snapshot reset_simulators` errors out:
```
λ fastlane snapshot reset_simulators
[✔] 🚀

[15:17:28]: Error accessing file, this might be due to fastlane's directory handling
[15:17:28]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - xcodebuild -version -sdk (Errno::ENOENT)
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:95:in `popen3'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.101.0/snapshot/lib/snapshot/latest_os_version.rb:20:in `version_for_os'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.101.0/snapshot/lib/snapshot/latest_os_version.rb:13:in `version'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.101.0/snapshot/lib/snapshot/latest_os_version.rb:8:in `ios_version'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.101.0/snapshot/lib/snapshot/commands_generator.rb:75:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.101.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.101.0/snapshot/lib/snapshot/commands_generator.rb:106:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fastlane-2.101.0/snapshot/lib/snapshot/commands_generator.rb:14:in `start'
```
But error message is a bit strange (error is because there is no xcodebuild, not because of any directory handling
* `screengrab` docs tell you to run `./gradlew assembleDebug assembleAndroidTest` to build the test APK. On Windows this doesn't work:
```
λ ./gradlew assembleDebug assembleAndroidTest
'.' is not recognized as an internal or external command,
operable program or batch file.`
```
Without the `./` it works.
* More emoji issues with `fastlane screengrab`:
![image](https://user-images.githubusercontent.com/183673/43831655-22c6bd9c-9b05-11e8-879f-89019cb606c4.png)
* Shells are different: `echo $foo` on Windows is equal to `echo \$foo` on Mac (macOS tries to get the value of `$foo` first before handing it over to `echo`. Sometimes that is not what you want. See https://github.com/fastlane/fastlane/pull/13064
* <strike>`fastlane deliver download_screenshots` downloads broken files:
![image](https://user-images.githubusercontent.com/183673/44156739-eeeff84c-a0b0-11e8-828b-d0cd4bfab400.png)</strike>https://github.com/fastlane/fastlane/issues/13209
* `fastlane deliver download_metadata` downloads files with/without newline at end of file which Windows files normally (don't) have
* `fastlane env` is missing some info:
![image](https://user-images.githubusercontent.com/183673/44294046-ed4cef80-a291-11e8-9ada-6b5dc087edfd.png)
* fastlane still writes _so_ much stuff to `/tmp` - we should get rid of all of those
* Still relevant: https://github.com/fastlane/fastlane/compare/master...janpio-crossplatform_TODOs
* `fastlane enable_auto_complete` is broken:
```
λ bundle exec fastlane enable_auto_complete
[✔] 🚀

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/auto_complete.rb:12:in `execute': [!] undefined method `end_with?' for nil:NilClass (NoMethodError)
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:254:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Projects/Fastlane/win-fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        from C:/Projects/Fastlane/win-fastlane/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<main>'
```
* <strike>`fastlane supply init` also creates broken files, e.g. `\fastlane\metadata\android\de-DE\images\icon.png` </strike>https://github.com/fastlane/fastlane/issues/13209
* `swiftlint`is missing, doesn't matter in tests though:
```
[18:33:47]: -----------------------
[18:33:47]: --- Step: swiftlint ---
[18:33:47]: -----------------------
which: no swiftlint in (/c/Ruby24-x64/lib/ruby/gem...p/cmder_mini)
```

---

I will update this issue as I encounter things.

**Comment by janpio** [comment]
nope, not this one bot.

**Comment by janpio** [comment]
- When running an action directly, you can't Ctrl+C out of a prompt/ask:
```
λ bundle exec fastlane run slack                                                                                        
[✔] 🚀                                                                                                                  
[15:20:50]: It seems like you wanted to load some plugins, however they couldn't be loaded                              
[15:20:50]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/       
[15:20:50]: -------------------                                                                                         
[15:20:50]: --- Step: slack ---                                                                                         
[15:20:50]: -------------------                                                                                         
[15:20:51]: To not be asked about this value, you can specify it using 'slack_url'                                      
[15:20:51]: Create an Incoming WebHook for your Slack group: *****************************                              
[15:35:36]: Error setting value '♥♥♥♥←←←←←♥♥♥♥♥♥♥♥♥♥♥ccccc♥♥♥♥' for option 'slack_url'                                  
Invalid URL, must start with https://                                                                                   
[15:35:36]: To not be asked about this value, you can specify it using 'slack_url'                                      
[15:35:36]: Create an Incoming WebHook for your Slack group: *                                                          
[15:35:41]: Error setting value '♥' for option 'slack_url'                                                              
Invalid URL, must start with https://                                                                                   
[15:35:41]: To not be asked about this value, you can specify it using 'slack_url'                                      
[15:35:41]: Create an Incoming WebHook for your Slack group: *                                                          
[15:35:42]: Error setting value '♥' for option 'slack_url'                                                              
Invalid URL, must start with https://                                                                                   
[15:35:42]: To not be asked about this value, you can specify it using 'slack_url'                                      
[15:35:42]: Create an Incoming WebHook for your Slack group: *                                                          
[15:35:44]: Error setting value '♥' for option 'slack_url'                                                              
Invalid URL, must start with https://                                                                                   
[15:35:44]: To not be asked about this value, you can specify it using 'slack_url'                                      
[15:35:44]: Create an Incoming WebHook for your Slack group: *                                                          
[15:35:45]: Error setting value '♥' for option 'slack_url'                                                              
Invalid URL, must start with https://                                                                                   
[15:35:45]: To not be asked about this value, you can specify it using 'slack_url'                                      
[15:35:45]: Create an Incoming WebHook for your Slack group: *                                                          
[15:35:46]: Error setting value '♥' for option 'slack_url'                                                              
Invalid URL, must start with https://                                                                                   
[15:35:46]: To not be asked about this value, you can specify it using 'slack_url'                                      
[15:35:46]: Create an Incoming WebHook for your Slack group: *                                                          
[15:35:47]: Error setting value '♥' for option 'slack_url'                                                              
Invalid URL, must start with https://                                                                                   
[15:35:47]: To not be asked about this value, you can specify it using 'slack_url'                                      
[15:35:47]: Create an Incoming WebHook for your Slack group:                                                            
```
(Have to check if this is actually a Windows thing or also happens on macOS)

**Comment by janpio** [comment]
- `~/Library` is never a valid location for things on Windows
