### ISSUE TITLE
Sometimes fast lane crashes for no reason

### ISSUE THREAD

**Issue by NicosKaralis** [fastlane/fastlane#13073]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Sometimes fastlane can't run, there is no apparent reason, sometimes the same command gives an error, sometimes it's just a warning (Fastfile not found), sometimes everything works fine

I suspect the problem happens on the config loading section, because if the config is all loaded then all the steps defined in the lane will work

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$> fastlane deliver --skip_binary_upload true --skip_screenshots true --verbose
[✔] 🚀
Traceback (most recent call last):
	8: from /Users/user/.rvm/gems/ruby-2.5.1@ios-app/bin/ruby_executable_hooks:24:in `<main>'
	7: from /Users/user/.rvm/gems/ruby-2.5.1@ios-app/bin/ruby_executable_hooks:24:in `eval'
	6: from /Users/user/.rvm/gems/ruby-2.5.1@ios-app/bin/fastlane:23:in `<main>'
	5: from /Users/user/.rvm/gems/ruby-2.5.1@ios-app/bin/fastlane:23:in `load'
	4: from /Users/user/.rvm/gems/ruby-2.5.1@ios-app/gems/fastlane-2.101.1/bin/fastlane:20:in `<top (required)>'
	3: from /Users/user/.rvm/gems/ruby-2.5.1@ios-app/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:74:in `take_off'
	2: from /Users/user/.rvm/gems/ruby-2.5.1@ios-app/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:167:in `available_lanes'
	1: from /Users/user/.rvm/gems/ruby-2.5.1@ios-app/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/fastlane_folder.rb:52:in `fastfile_path'
/Users/user/.rvm/gems/ruby-2.5.1@ios-app/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/fastlane_folder.rb:52:in `join': no implicit conversion of nil into String (TypeError)</pre>
</details>
The exception that sometimes happens

<details>
  <pre>$> fastlane deliver --skip_binary_upload true --skip_screenshots true --capture_output
[✔] 🚀
cat: ./Fastfile: No such file or directory
[...] Procedes to work  fine</pre>
</details>
The warning that sometimes happens

<details>
  <pre>$> fastlane deliver --skip_binary_upload true --skip_screenshots true
[✔] 🚀
[11:09:53]: Successfully loaded '/Users/user/ios-app/fastlane/Deliverfile' 📄

+-----------------------------------+---------------------------------------------------------------+
|                                     Detected Values from './fastlane/Deliverfile'                 |
+-----------------------------------+---------------------------------------------------------------+
| price_tier                        | 0                                                             |
| app_review_information            | {:first_name=>"...", :last_name=>"...", :phone_number=>"...", |
|                                   | :email_address=>"...", :demo_user=>"demo@apple.com",          |
|                                   | :demo_password=>"demopassword", :notes=>"Review\n"}           |
| copyright                         | 2018 CopyRh                                                   |
| app_icon                          | ./fastlane/metadata/app_icon.jpg                              |
| automatic_release                 | false                                                         |
| submit_for_review                 | false                                                         |
| app_rating_config_path            | ./fastlane/metadata/rating_config.json                        |
| precheck_include_in_app_purchases | false                                                         |
+-----------------------------------+---------------------------------------------------------------+

[11:09:53]: Login to App Store Connect (...)
[11:09:56]: Login successful

+--------------------------------------+----------------------------------------+
|                            deliver 2.101.1 Summary                            |
+--------------------------------------+----------------------------------------+
| skip_binary_upload                   | true                                   |
| skip_screenshots                     | true                                   |
| screenshots_path                     | ./fastlane/screenshots                 |
| metadata_path                        | ./fastlane/metadata                    |
| username                             | ...                                    |
| app_identifier                       | com.ios.app                            |
| edit_live                            | false                                  |
| platform                             | ios                                    |
| use_live_version                     | false                                  |
| skip_metadata                        | false                                  |
| skip_app_version_update              | false                                  |
| force                                | false                                  |
| submit_for_review                    | false                                  |
| reject_if_possible                   | false                                  |
| automatic_release                    | false                                  |
| phased_release                       | false                                  |
| price_tier                           | 0                                      |
| app_rating_config_path               | ./fastlane/metadata/rating_config.json |
| team_id                              | 95658813                               |
| team_name                            |  ...                                   |
| dev_portal_team_id                   |  ...                                   |
| overwrite_screenshots                | false                                  |
| run_precheck_before_submit           | true                                   |
| precheck_default_rule_level          | warn                                   |
| app_icon                             | ./fastlane/metadata/app_icon.jpg       |
| copyright                            | 2018 CopyRh                            |
| app_review_information.first_name    | ...                                    |
| app_review_information.last_name     | ...                                    |
| app_review_information.phone_number  | ...                                    |
| app_review_information.email_address | ...                                    |
| app_review_information.demo_user     | demo@apple.com                         |
| app_review_information.demo_password | ********                               |
| app_review_information.notes         | Notas para review                      |
| ignore_language_directory_validation | false                                  |
| precheck_include_in_app_purchases    | false                                  |
+--------------------------------------+----------------------------------------+

[11:09:58]: Loading './fastlane/metadata/default/description.txt'...
[11:09:58]: Loading './fastlane/metadata/default/keywords.txt'...
[11:09:58]: Loading './fastlane/metadata/default/support_url.txt'...
[11:09:58]: Loading './fastlane/metadata/default/marketing_url.txt'...
[11:09:58]: Loading './fastlane/metadata/default/promotional_text.txt'...
[11:09:58]: Loading './fastlane/metadata/default/subtitle.txt'...
[11:09:58]: Loading './fastlane/metadata/default/privacy_url.txt'...
[11:09:58]: Loading './fastlane/metadata/es-ES/description.txt'...
[11:09:58]: Loading './fastlane/metadata/es-ES/keywords.txt'...
[11:09:58]: Loading './fastlane/metadata/es-ES/release_notes.txt'...
[11:09:58]: Loading './fastlane/metadata/es-ES/promotional_text.txt'...
[11:09:58]: Loading './fastlane/metadata/es-ES/name.txt'...
[11:09:58]: Loading './fastlane/metadata/es-ES/subtitle.txt'...
[11:09:58]: Loading './fastlane/metadata/pt-BR/description.txt'...
[11:09:58]: Loading './fastlane/metadata/pt-BR/keywords.txt'...
[11:09:58]: Loading './fastlane/metadata/pt-BR/release_notes.txt'...
[11:09:58]: Loading './fastlane/metadata/pt-BR/promotional_text.txt'...
[11:09:58]: Loading './fastlane/metadata/pt-BR/name.txt'...
[11:09:58]: Loading './fastlane/metadata/pt-BR/subtitle.txt'...
[11:09:58]: Loading './fastlane/metadata/primary_category.txt'...
[11:09:58]: Loading './fastlane/metadata/secondary_category.txt'...
[11:09:58]: Loading './fastlane/metadata/trade_representative_contact_information/trade_name.txt'...
[11:09:58]: Loading './fastlane/metadata/trade_representative_contact_information/address_line1.txt'...
[11:09:58]: Loading './fastlane/metadata/trade_representative_contact_information/address_line2.txt'...
[11:09:58]: Loading './fastlane/metadata/trade_representative_contact_information/city_name.txt'...
[11:09:58]: Loading './fastlane/metadata/trade_representative_contact_information/state.txt'...
[11:09:58]: Loading './fastlane/metadata/trade_representative_contact_information/country.txt'...
[11:09:58]: Loading './fastlane/metadata/trade_representative_contact_information/postal_code.txt'...
[11:09:58]: Loading './fastlane/metadata/trade_representative_contact_information/is_displayed_on_app_store.txt'...
[11:09:59]: Detected languages: ["default", "es-ES", "pt-BR"]
[11:09:59]: Verifying the upload via the HTML file can be disabled by either adding
[11:09:59]: `force true` to your Deliverfile or using `fastlane deliver --force`
[11:10:00]: Does the Preview on path './fastlane/Preview.html' look okay for you? (y/n)
y
[11:10:05]: HTML file confirmed...
[✔] Activating languages es-ES, pt-BR...
[11:10:14]: Setting the app's age rating...
[✔] Uploading metadata to App Store Connect
[11:10:46]: Successfully uploaded set of metadata to App Store Connect
[11:10:48]: Price Tier unchanged (tier 0)
[11:10:50]: Uploading app icon...
[11:11:11]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[11:11:11]: Running precheck 👮‍♀️ 👮

+--------------------------+-------------------------------------+
|                  Summary for precheck 2.101.1                  |
+--------------------------+-------------------------------------+
| default_rule_level       | warn                                |
| include_in_app_purchases | false                               |
| app_identifier           | com.ios.app                         |
| username                 | ...                                 |
| team_id                  | ...                                 |
| team_name                | ...                                 |
+--------------------------+-------------------------------------+

[11:11:11]: Checking app for precheck rule violations
[11:11:18]: ✅  Passed: No negative  sentiment
[11:11:18]: ✅  Passed: No placeholder text
[11:11:18]: ✅  Passed: No mentioning  competitors
[11:11:18]: ✅  Passed: No future functionality promises
[11:11:18]: ✅  Passed: No words indicating test content
[11:11:18]: ✅  Passed: No curse words
[11:11:18]: ✅  Passed: No words indicating your IAP is free
[11:11:18]: ✅  Passed: Incorrect, or missing copyright date
[11:11:22]: 😵  Failed: No broken urls-> unreachable URLs in app metadata
+----------------------+----------------+
|          Potential problems           |
+----------------------+----------------+
| Field                | Failure reason |
+----------------------+----------------+
| support URL: (en-US) | empty url      |
+----------------------+----------------+
[11:11:22]: precheck 👮‍♀️ 👮  found one or more potential metadata problems, but this won't prevent fastlane from completing 👍
</pre>
</details>
The output of a successfull run

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 10.13.5                                              |
| Ruby                        | 2.5.1                                                |
| Bundler?                    | true                                                 |
| Git                         | git version 2.15.2 (Apple Git-101.1)                 |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1@ios-app/bin/fastlane |
| Host                        | Mac OS X 10.13.5 (17F77)                             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                         |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                          |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version               | 9.4.1                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

app_scheme = 'iOSApp'
uitest_scheme = 'iOSAppUITests'

default_platform(:ios)

desc "Verify XCode instalation"
lane :xcode do
  verify_xcode
end

platform :ios do
  
  lane :snap do
    snapshot(
      clean: true,
      reinstall_app: true,
      stop_after_first_error: true,
      scheme: app_scheme,
      skip_open_summary: false
    )
    deliver(force: false, skip_binary_upload: true)
  end
  
  desc "Runs all the tests"
  lane :test do
    scan(scheme: app_scheme)
  end
  
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # ensure_git_status_clean
    match(type: "appstore") # more information: https://codesigning.guide
    changelog_from_git_commits(pretty: '- (%ae) %s')
    increment_build_number(build_number: latest_testflight_build_number + 1)
    cocoapods
    gym(scheme: app_scheme) # Build your app - more options available
    pilot(distribute_external: true, groups: 'Anfeli')
    # commit_version_bump
    # add_git_tag
    # push_to_git_remote
  end
  
  desc "Deploy a new version to the App Store"
  lane :release do
    verify_xcode
    match(type: "appstore")
    pem
    increment_build_number(build_number: latest_testflight_build_number.to_i + 1)
    cocoapods
    snapshot(
      scheme: app_scheme,
      clean: true,
      reinstall_app: true,
      stop_after_first_error: true
    )
    gym(scheme: app_scheme) # Build your app - more options available
    deliver(force: true)
    download_dsyms
    upload_symbols_to_crashlytics
    # frameit
    commit_version_bump
    add_git_tag
    push_to_git_remote
  end
  
  desc "Prepare environment for development"
  lane :development do
    match(type: 'development')
    # pem(development: true)
    match(type: 'appstore')
    pem
    cocoapods
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier 'com.ios.app' # The bundle identifier of your app
apple_id '...' # Your Apple email address
team_id '...' # Developer Portal Team ID
itc_team_id '...'
itc_team_name '...'

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.5.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.3       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.4        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.4       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-08-09**
</details>

**Comment by NicosKaralis** [comment]
@fastlane-bot NO, bad bot
