### ISSUE TITLE
CircleCi 2.0 + GYM failure only on CI

### ISSUE THREAD

**Issue by GregTheGreek** [fastlane/fastlane#13081]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I thought I'd try the fastlane community first, since the circleci forums aren't usually that helpfull.

In short, I am using React-Native with OneSignal and had to create custom bridging of a header file, see [one signal solution](https://github.com/geektimecoil/react-native-onesignal/issues/530). This works fine locally, I can archive locally no problem and upload the build successfully to test flight. But when CircleCi runs it always fails stating it cannot find the `"RCTOneSignalExtensionService.h"`.

##### Complete output when running fastlane, including the stack trace and command used
```
+----------------------------------------------------------------------------------------------------------------+----------------------+
|                                                        Generated Build Command                                                        |
+----------------------------------------------------------------------------------------------------------------+----------------------+
| Option                                                                                                         | Value                |
+----------------------------------------------------------------------------------------------------------------+----------------------+
| set -o pipefail &&                                                                                             |                      |
| xcodebuild                                                                                                     |                      |
| -workspace ./ios/boro.xcworkspace                                                                              |                      |
| -scheme boro                                                                                                   |                      |
| -destination                                                                                                   | generic/platform=iOS |
| -archivePath /Users/distiller/Library/Developer/Xcode/Archives/2018-08-10/boro\ 2018-08-10\ 05.43.40.xcarchive |                      |
| archive                                                                                                        |                      |
| | tee /Users/distiller/project/output/buildlogs/gym/boro-boro.log                                              |                      |
| | xcpretty                                                                                                     |                      |
+----------------------------------------------------------------------------------------------------------------+----------------------+
INFO [2018-08-10 05:43:40.88]: $ set -o pipefail && xcodebuild -workspace ./ios/boro.xcworkspace -scheme boro -destination 'generic/platform=iOS' -archivePath /Users/distiller/Library/Developer/Xcode/Archives/2018-08-10/boro\ 2018-08-10\ 05.43.40.xcarchive archive | tee /Users/distiller/project/output/buildlogs/gym/boro-boro.log | xcpretty
INFO [2018-08-10 05:43:42.17]: ▸ Building boro/OneSignalNotificationServiceExtension [Release]
INFO [2018-08-10 05:43:42.17]: ▸ Check Dependencies
INFO [2018-08-10 05:43:42.25]: ▸ Processing Info.plist
INFO [2018-08-10 05:43:42.56]: ▸ Compiling NotificationService.swift
INFO [2018-08-10 05:43:45.31]: ▸ ❌  /Users/distiller/project/ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension-Swift.h:11:9: 'RCTOneSignalExtensionService.h' file not found
INFO [2018-08-10 05:43:45.31]: ▸ #import "RCTOneSignalExtensionService.h"
INFO [2018-08-10 05:43:45.31]: ▸         ^
INFO [2018-08-10 05:43:45.31]: ▸ ❌  error: failed to emit precompiled header '/Users/distiller/Library/Developer/Xcode/DerivedData/boro-edtwdmqkzfolqrbpuahdimnyrdko/Build/Intermediates.noindex/ArchiveIntermediates/boro/PrecompiledHeaders/OneSignalNotificationServiceExtension-Swift-swift_1Z6ZX17BM3EFJ-clang_AWTHD9RZFNM0.pch' for bridging header /Users/distiller/project/ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension-Swift.h
INFO [2018-08-10 05:43:45.35]: ▸ ** ARCHIVE FAILED **
INFO [2018-08-10 05:43:45.35]: ▸ The following build commands failed:
INFO [2018-08-10 05:43:45.35]: ▸ CompileSwift normal arm64 /Users/distiller/project/ios/OneSignalNotificationServiceExtension/NotificationService.swift
INFO [2018-08-10 05:43:45.35]: ▸ CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
INFO [2018-08-10 05:43:45.35]: ▸ (2 failures)
▸ Building boro/OneSignalNotificationServiceExtension [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling NotificationService.swift

❌  /Users/distiller/project/ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension-Swift.h:11:9: 'RCTOneSignalExtensionService.h' file not found

#import "RCTOneSignalExtensionService.h"
        ^



❌  error: failed to emit precompiled header '/Users/distiller/Library/Developer/Xcode/DerivedData/boro-edtwdmqkzfolqrbpuahdimnyrdko/Build/Intermediates.noindex/ArchiveIntermediates/boro/PrecompiledHeaders/OneSignalNotificationServiceExtension-Swift-swift_1Z6ZX17BM3EFJ-clang_AWTHD9RZFNM0.pch' for bridging header /Users/distiller/project/ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension-Swift.h


** ARCHIVE FAILED **


The following build commands failed:
CompileSwift normal arm64 /Users/distiller/project/ios/OneSignalNotificationServiceExtension/NotificationService.swift
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
ERROR [2018-08-10 05:43:45.36]: Exit status: 65
INFO [2018-08-10 05:43:45.37]: 
WARN [2018-08-10 05:43:45.38]: Maybe the error shown is caused by using the wrong version of Xcode
WARN [2018-08-10 05:43:45.38]: Found multiple versions of Xcode in '/Applications/'
WARN [2018-08-10 05:43:45.38]: Make sure you selected the right version for your project
WARN [2018-08-10 05:43:45.38]: This build process was executed using '/Applications/Xcode-9.4.1.app'
WARN [2018-08-10 05:43:45.38]: If you want to update your Xcode path, either
INFO [2018-08-10 05:43:45.38]: 
INFO [2018-08-10 05:43:45.38]: - Specify the Xcode version in your Fastfile
INFO [2018-08-10 05:43:45.38]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
INFO [2018-08-10 05:43:45.38]: 
INFO [2018-08-10 05:43:45.38]: - Specify an absolute path to your Xcode installation in your Fastfile
INFO [2018-08-10 05:43:45.38]: ▸ xcode_select "/Applications/Xcode8.app"
INFO [2018-08-10 05:43:45.38]: 
INFO [2018-08-10 05:43:45.38]: - Manually update the path using
INFO [2018-08-10 05:43:45.38]: ▸ sudo xcode-select -s /Applications/Xcode.app
INFO [2018-08-10 05:43:45.38]: 

+---------------+-------------------------------+
|               Build environment               |
+---------------+-------------------------------+
| xcode_path    | /Applications/Xcode-9.4.1.app |
| gym_version   | 2.101.1                       |
| export_method | app-store                     |
| sdk           | iPhoneOS11.4.sdk              |
+---------------+-------------------------------+

INFO [2018-08-10 05:43:45.40]: ▸ /Users/distiller/project/ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension-Swift.h:11:9: error: 'RCTOneSignalExtensionService.h' file not found
INFO [2018-08-10 05:43:45.40]: ▸ #import "RCTOneSignalExtensionService.h"
INFO [2018-08-10 05:43:45.40]: ▸         ^
INFO [2018-08-10 05:43:45.40]: ▸ 1 error generated.
INFO [2018-08-10 05:43:45.40]: ▸ <unknown>:0: error: failed to emit precompiled header '/Users/distiller/Library/Developer/Xcode/DerivedData/boro-edtwdmqkzfolqrbpuahdimnyrdko/Build/Intermediates.noindex/ArchiveIntermediates/boro/PrecompiledHeaders/OneSignalNotificationServiceExtension-Swift-swift_1Z6ZX17BM3EFJ-clang_AWTHD9RZFNM0.pch' for bridging header '/Users/distiller/project/ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension-Swift.h'
INFO [2018-08-10 05:43:45.40]: 
ERROR [2018-08-10 05:43:45.40]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
WARN [2018-08-10 05:43:45.40]: 📋  For the complete and more detailed error log, check the full log at:
WARN [2018-08-10 05:43:45.40]: 📋  /Users/distiller/project/output/buildlogs/gym/boro-boro.log
INFO [2018-08-10 05:43:45.40]: 
ERROR [2018-08-10 05:43:45.40]: Looks like fastlane ran into a build/archive error with your project
ERROR [2018-08-10 05:43:45.40]: It's hard to tell what's causing the error, so we wrote some guides on how
ERROR [2018-08-10 05:43:45.40]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
ERROR [2018-08-10 05:43:45.40]: Before submitting an issue on GitHub, please follow the guide above and make
ERROR [2018-08-10 05:43:45.40]: sure your project is set up correctly.
ERROR [2018-08-10 05:43:45.40]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
ERROR [2018-08-10 05:43:45.40]: the full commands printed out in yellow in the above log.
ERROR [2018-08-10 05:43:45.40]: Make sure to inspect the output above, as usually you'll find more error information there
INFO [2018-08-10 05:43:45.40]: 
WARN [2018-08-10 05:43:45.40]: Lane Context:
INFO [2018-08-10 05:43:45.40]: {:PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"38", :ORIGINAL_DEFAULT_KEYCHAIN=>"\"/Users/distiller/Library/Keychains/login.keychain-db\"", :SIGH_PROFILE_TYPE=>"app-store", :MATCH_PROVISIONING_PROFILE_MAPPING=>{"com.borotechnologiescorp.boro"=>"match AppStore com.borotechnologiescorp.boro", "com.borotechnologiescorp.boro.OneSignalNotificationServiceExtension"=>"match AppStore com.borotechnologiescorp.boro.OneSignalNotificationServiceExtension"}}
ERROR [2018-08-10 05:43:45.40]: Error building the application - see the log above
INFO [2018-08-10 05:43:45.41]: Successfully generated documentation at path '/Users/distiller/project/fastlane/README.md'

+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | Verifying fastlane version      | 0           |
| 2    | increment_build_number          | 2           |
| 3    | setup_circle_ci                 | 0           |
| 4    | Switch to ios build lane        | 0           |
| 5    | Switch to ios certificates lane | 0           |
| 6    | match                           | 1           |
| 7    | match                           | 1           |
| 💥   | gym                             | 6           |
+------+---------------------------------+-------------+

ERROR [2018-08-10 05:43:45.41]: fastlane finished with errors
bundler: failed to load command: fastlane (/Users/distiller/project/vendor/bundle/ruby/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneBuildFailure: [!] Error building the application - see the log above
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/gym/lib/gym/error_handler.rb:73:in `handle_build_error'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/gym/lib/gym/runner.rb:97:in `block in build_app'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/command_executor.rb:93:in `execute'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/gym/lib/gym/runner.rb:93:in `build_app'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/gym/lib/gym/runner.rb:18:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/gym/lib/gym/manager.rb:19:in `work'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/build_ios_app.rb:64:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:38:in `block (2 levels) in parsing_binding'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:43:in `block (2 levels) in parsing_binding'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.101.1/bin/fastlane:20:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `load'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `<top (required)>'
Exited with code 1
```

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.4                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.6.4                                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.4 (17E202)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-screen                | 0.6.5        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| xcodeproj                 | 1.5.9        |
</details>

*generated on:* **2018-08-10**
</details></pre>
</details>

**Comment by masondaven** [comment]
I'm having the same exact issue in circleci.

**Comment by dwmkerr** [comment]
Same, intermittently for months

**Comment by monkeyxdd** [comment]
same,local is ok, but don't work in CI

**Comment by GregTheGreek** [comment]
Assuming no one has found a temporary solution aside from uploading manually?

**Comment by GregTheGreek** [comment]
Is this a circle-ci issue or fastlane?

**Comment by megakode** [comment]
This might be a CircleCi problem. I am running cocoapods + circleci on a project, and ran into the same problem after the following scenario:

- Removed a pod (RXCollections)
- Ran 'pod install'
- Local build ok
- Triggedered CircleCI build
- CircleCi build fails with "FBInlineTweak.h" not found and "failed to emit precompiled header" even though nothing related to that pod has been changed (Tweaks).
