### ISSUE TITLE
Hockey not working due to plist gem conflict?

### ISSUE THREAD

**Issue by shaps80** [fastlane/fastlane#1308]
I'm having an unusual issue on my local machine. CI and other machines appear to be working fine.

However when I run fastlane from my local machine I'm now getting the following error when it attempts to upload to hockey (in fact its re-producable through `fastlane run hockey`):

```
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate krausefx-shenzhen-0.14.7, because plist-3.2.0 conflicts with plist (~> 3.1.0) (Gem::ConflictError)
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1408:in `activate'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:196:in `rescue in try_activate'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:193:in `try_activate'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/lib/fastlane/actions/hockey.rb:16:in `run'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/lib/fastlane/one_off.rb:31:in `execute'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/bin/fastlane:106:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/Shaps/.gems/gems/fastlane_core-0.36.3/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/bin/fastlane:150:in `run'
	from /Users/Shaps/.gems/gems/fastlane-1.59.0/bin/fastlane:156:in `<top (required)>'
	from /Users/Shaps/.gems/bin/fastlane:22:in `load'
	from /Users/Shaps/.gems/bin/fastlane:22:in `<main>'
```

I had plist-3.2.0 installed, tried switching over to 3.1.0 and even tried removing completely and re-installing fastlane but I keep getting this error.

Anyone else having this issue? Would appreciate any input or advice to get this resolved. FYI: I have only tested this on one project so far.

**Comment by gose** [comment]
This worked for me:

$ gem install plist -v 3.1.0
$ gem uninstall plist -v 3.2.0

**Comment by shaps80** [comment]
I had tried that but didn't work for me. Have moved on since I had this issue and doesn't seem to be reproducible on another project so not sure what happened ;)
