### ISSUE TITLE
Add a message on large APK

### ISSUE THREAD

**Issue by sofianegargouri** [fastlane/fastlane#13092]
#### Motivation Behind Feature
I've been trying to upload my app for hours now, and Fastlane didn't seem to crash or anything, just working while the timeout comes. I was asking myself why, so I tried to upload manually on the Google Play Console, and here is the error Google gave me: "You need to reduce your APK file size to 100MB or use APK Expansion Files."

#### Feature Description
When trying to upload an APK > 100Mo, prevent it or send a warning to the user, or get the response from Google API

**Comment by janpio** [comment]
Interesting. Would it actually have finished? 

Fastlane's `supply`/`upload_to_play_store` is using a different API than the Google Play Console, that unfortunately not always behaves identical to the web interface.

**Comment by janpio** [comment]
Can you post the timeout message please? 
How big was your APK that you tried to upload?

**Comment by sofianegargouri** [comment]
The APK I tried to upload is 205Mo

Here are the logs:

```
[12:41:11]: Preparing apk at path '/Users/sofianegargouri/my_app/android/app/build/outputs/apk/release/app-release.apk' for upload...
+-----------------------------+----------------------------------------------------------------------------------------------------------+
|                                                              Lane Context                                                              |
+-----------------------------+----------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM            | android                                                                                                  |
| PLATFORM_NAME               | android                                                                                                  |
| LANE_NAME                   | android internal                                                                                         |
| GRADLE_ALL_APK_OUTPUT_PATHS | ["/Users/sofianegargouri/my_app/android/app/build/outputs/apk/release/app-release.apk"] |
| GRADLE_ALL_AAB_OUTPUT_PATHS | []                                                                                                       |
| GRADLE_APK_OUTPUT_PATH      | /Users/sofianegargouri/my_app/android/app/build/outputs/apk/release/app-release.apk     |
+-----------------------------+----------------------------------------------------------------------------------------------------------+
[12:56:15]: execution expired

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | gradle           | 4           |
| 3    | gradle           | 106         |
| 💥   | supply           | 906         |
+------+------------------+-------------+

[12:56:15]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Supply] SendTimeoutError: execution expired
    https://github.com/fastlane/fastlane/issues/12173 [closed] 2 💬
    3 days ago

➡️  Being able to set send timeout for supply
    https://github.com/fastlane/fastlane/issues/12943 [closed] 2 💬
    2 weeks ago

➡️  Could not find a matching provisioning profile (using match!)
    https://github.com/fastlane/fastlane/issues/12878 [open] 5 💬
    a day ago

and 25 more at: https://github.com/fastlane/fastlane/search?q=execution%20expired&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
[12:56:19]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
Traceback (most recent call last):
	70: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
	69: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
	68: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/bin/fastlane:23:in `<main>'
	67: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/bin/fastlane:23:in `load'
	66: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/bin/fastlane:20:in `<top (required)>'
	65: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	64: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	63: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	62: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	61: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	60: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	59: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	58: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	57: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	56: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	55: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	54: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	53: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	52: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	51: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	50: from Fastfile:11:in `block (2 levels) in parsing_binding'
	49: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	48: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	47: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	46: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	45: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	44: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	43: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	42: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
	41: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/supply/lib/supply/uploader.rb:27:in `perform_upload'
	40: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/supply/lib/supply/uploader.rb:138:in `upload_apks'
	39: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/supply/lib/supply/uploader.rb:138:in `each'
	38: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/supply/lib/supply/uploader.rb:139:in `block in upload_apks'
	37: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/supply/lib/supply/uploader.rb:175:in `upload_binary_data'
	36: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/supply/lib/supply/client.rb:223:in `upload_apk'
	35: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/supply/lib/supply/client.rb:397:in `call_google_api'
	34: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/fastlane-2.101.1/supply/lib/supply/client.rb:224:in `block in upload_apk'
	33: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.23.4/generated/google/apis/androidpublisher_v2/service.rb:631:in `upload_apk'
	32: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	31: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:93:in `execute'
	30: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	29: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	28: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	27: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:101:in `block in execute'
	26: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	25: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	24: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	23: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
	22: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/upload.rb:254:in `execute_once'
	21: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/upload.rb:228:in `send_upload_command'
	20: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
	19: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
	18: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
	17: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	16: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	15: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	14: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
	13: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
	12: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
	11: from /Users/sofianegargouri/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
	10: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:517:in `block in query'
	 9: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:962:in `dump'
	 8: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:508:in `dump'
	 7: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:582:in `dump_file'
	 6: from /Users/sofianegargouri/.rvm/gems/ruby-2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:80:in `<<'
	 5: from /Users/sofianegargouri/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:343:in `write'
	 4: from /Users/sofianegargouri/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:343:in `inject'
	 3: from /Users/sofianegargouri/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:343:in `each'
	 2: from /Users/sofianegargouri/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:344:in `block in write'
	 1: from /Users/sofianegargouri/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:325:in `do_write'
/Users/sofianegargouri/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:325:in `syswrite': [!] execution expired (Google::Apis::TransmissionError)
```

**Comment by janpio** [comment]
Ok, so >200MB and the timeout took 15 minutes.

Last thing I will ask for: Can you share the complete lane you were running?

**Comment by sofianegargouri** [comment]
Sure:

```ruby
default_platform(:android)

platform :android do
  before_all do
    gradle(task: 'clean')
    gradle(task: 'assembleRelease')
  end

  desc 'Submit Internal'
  lane :internal do
    supply(track: 'internal')
  end
end
```
