### ISSUE TITLE
[precheck] `precheck` can't handle Umlaut URLs / IDN

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13119]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`precheck` fails with "Failed: No broken urls-> unreachable URLs in app metadata" when using Umlaut domains as support, marketing or privacy URL.

##### Complete output when running fastlane, including the stack trace and command used
```
λ fastlane precheck --verbose
[✔] 🚀
Successfully loaded Appfile at path 'C:/Projects/Stromzaehler/stromzaehler/fastlane/Appfile'
- app_identifier: 'de.janpiotrowski.zaehlerstand'
- apple_id: 'pio...@gmail.com'
- team_id: '4Z...X3'
- json_key_file: 'C...son'
- package_name: 'de.janpiotrowski.zaehlerstand'
-------

+--------------------------+-------------------------------+
|               Summary for precheck 2.101.1               |
+--------------------------+-------------------------------+
| app_identifier           | de.janpiotrowski.zaehlerstand |
| username                 | pio...@gmail.com          |
| default_rule_level       | error                         |
| include_in_app_purchases | true                          |
+--------------------------+-------------------------------+

INFO [2018-08-15 19:35:12.91]: Starting login with user 'pio...@gmail.com'
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for pio...@gmail.com): ********
Loading session from 'C:/Users/Jan/.fastlane/spaceship/pio...@gmail.com/cookie'
Looking for App Store Connect Team with ID 42...53
INFO [2018-08-15 19:38:35.52]: Successfully logged in
INFO [2018-08-15 19:38:35.52]: Checking app for precheck rule violations
INFO [2018-08-15 19:38:41.22]: Reading in-app purchases. If you have a lot, this might take a while
INFO [2018-08-15 19:38:41.22]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
INFO [2018-08-15 19:38:41.81]: Done reading in-app purchases
INFO [2018-08-15 19:38:42.44]: ✅  Passed: No negative  sentiment
INFO [2018-08-15 19:38:42.45]: ✅  Passed: No placeholder text
INFO [2018-08-15 19:38:42.45]: ✅  Passed: No mentioning  competitors
INFO [2018-08-15 19:38:42.45]: ✅  Passed: No future functionality promises
INFO [2018-08-15 19:38:42.45]: ✅  Passed: No words indicating test content
INFO [2018-08-15 19:38:42.47]: ✅  Passed: No curse words
INFO [2018-08-15 19:38:42.47]: ✅  Passed: No words indicating your IAP is free
DEBUG [2018-08-15 19:38:42.47]: custom_text excluded because no data was passed to it e.g.: custom_text(data: <data here>)
INFO [2018-08-15 19:38:42.47]: ✅  Passed: Incorrect, or missing copyright date
DEBUG [2018-08-15 19:38:42.53]: URL https://zählerstand.app not reachable 😵
DEBUG [2018-08-15 19:38:42.56]: URL https://zählerstand.app not reachable 😵
DEBUG [2018-08-15 19:38:42.59]: URL https://zählerstand.app not reachable 😵
ERROR [2018-08-15 19:38:42.59]: 😵  Failed: No broken urls-> unreachable URLs in app metadata
+------------------------+--------------------------------------+
|                      Potential problems                       |
+------------------------+--------------------------------------+
| Field                  | Failure reason                       |
+------------------------+--------------------------------------+
| support URL: (de-DE)   | unreachable: https://zählerstand.app |
| marketing URL: (de-DE) | unreachable: https://zählerstand.app |
| privacy URL: (de-DE)   | unreachable: https://zählerstand.app |
+------------------------+--------------------------------------+
```

**Comment by janpio** [comment]
I modified the code of precheck to output the exception:

```
        rescue StandardError => e  
          puts e.message  
          puts e.backtrace.inspect
          UI.verbose("URL #{url} not reachable 😵")
```

```
Failed to open TCP connection to z%C3%A4hlerstand.app:443 (getaddrinfo: No such host is known. )
["C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect'", "C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'", "C:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "C:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:103:in `timeout'", "C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:902:in `connect'", "C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:887:in `do_start'", "C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:876:in `start'", "C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1407:in `request'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:87:in `perform_request'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/connection.rb:138:in `head'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/rules/unreachable_urls_rule.rb:37:in `block in rule_block'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/rule.rb:151:in `perform_check'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/rule.rb:124:in `check_item'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/rule_processor.rb:83:in `block (2 levels) in process_rules'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/rule_processor.rb:82:in `each'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/rule_processor.rb:82:in `block in process_rules'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/rule_processor.rb:58:in `each'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/rule_processor.rb:58:in `process_rules'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/rule_processor.rb:49:in `process_app_and_version'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/runner.rb:101:in `check_for_rule_violations'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/runner.rb:33:in `run'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/commands_generator.rb:41:in `block (2 levels) in run'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'", "C:/Projects/Fastlane/win-fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/commands_generator.rb:71:in `run'", "C:/Projects/Fastlane/win-fastlane/precheck/lib/precheck/commands_generator.rb:19:in `start'", "C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'", "C:/Projects/Fastlane/win-fastlane/bin/fastlane:20:in `<top (required)>'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<main>'"]
DEBUG [2018-08-15 19:48:48.94]: URL https://zählerstand.app not reachable 😵
```

**Comment by janpio** [comment]
Seems we are already using `addressable` to parse the URI.
Using `uri.normalize` converts the URL from https://zählerstand.app to https://xn--zhlerstand-q5a.app/ which can be resolved and reached.

PR incoming.
