### ISSUE TITLE
[pilot] undefined method `latest_build' for #<Spaceship::TestFlight::Tester:0x0000000005ca4e78>

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13127]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`fastlane pilot find user@example.org` fails with error.

```
λ bundle exec fastlane pilot find pio...ki@gmail.com --verbose
[✔] 🚀
Successfully loaded Appfile at path 'C:/Projects/Stromzaehler/stromzaehler/fastlane/Appfile'
- app_identifier: 'de.janpiotrowski.zaehlerstand'
- apple_id: 'pi...ski@gmail.com'
- team_id: '4Z...X3'
-------
INFO [2018-08-16 11:02:55.67]: Login to App Store Connect (pio...i@gmail.com)
Loading session from 'C:/Users/Jan/.fastlane/spaceship/p...ski@gmail.com/cookie'
Looking for App Store Connect Team with ID 42...
INFO [2018-08-16 11:02:58.46]: Login successful
INFO [2018-08-16 11:03:01.07]: Found existing tester p...ski@gmail.com
ERROR [2018-08-16 11:03:01.07]: undefined method `latest_build' for #<Spaceship::TestFlight::Tester:0x0000000005ca4e78>
Did you mean?  latest_install_info
C:/Projects/Fastlane/win-fastlane/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Some operations failed: undefined method `latest_build' for #<Spaceship::TestFlight::Tester:0x0000000005ca4e78> (FastlaneCore::Interface::FastlaneError)
Did you mean?  latest_install_info
        from C:/Projects/Fastlane/win-fastlane/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from C:/Projects/Fastlane/win-fastlane/pilot/lib/pilot/commands_generator.rb:44:in `handle_multiple'
        from C:/Projects/Fastlane/win-fastlane/pilot/lib/pilot/commands_generator.rb:125:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Projects/Fastlane/win-fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Projects/Fastlane/win-fastlane/pilot/lib/pilot/commands_generator.rb:166:in `run'
        from C:/Projects/Fastlane/win-fastlane/pilot/lib/pilot/commands_generator.rb:18:in `start'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
        from C:/Projects/Fastlane/win-fastlane/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<main>'
```

previously reported at https://github.com/fastlane/fastlane/issues/11366 and https://github.com/fastlane/fastlane/issues/12371

**Comment by janpio** [comment]
Code is here:
https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/tester_manager.rb#L208

Commenting out this line fixes the problem.

**Comment by janpio** [comment]
Actual structure of a tester object:
```
<Spaceship::TestFlight::Tester
        tester_id="b0a46351-891a-421c-bb3d-48ab840ce083",
        email="piotrowski@gmail.com",
        first_name="Jan",
        last_name="Piotrowski",
        status="installed",
        status_mod_time=2017-09-22 09:36:21 +0000,
        latest_install_info={"latestInstalledAppAdamId"=>"1267445457", "latestInstalledBuildId"=>"22628481", "latestInstalledDate"=>"1506072981617", "latestInstalledShortVersion"=>"0.0.1", "latestInstalledVersion"=>"3"},
        latest_installed_date=1506072981617,
        session_count=0,
        groups=["ITC.apps.tf.labels.internalTesters"]>
```
