### ISSUE TITLE
Import certificate causes a crash

### ISSUE THREAD

**Issue by lisovet** [fastlane/fastlane#1314]
```ruby
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/interface.rb:120:in `crash!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/actions/import_certificate.rb:12:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:78:in `import_certificates'
	from Fastfile:29:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/bin/fastlane:38:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/bin/fastlane:150:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
ERRO[21:20:15] Step (fastlane@2.1.0) failed, error: (exit status 1) 
```

```
def import_certificates
  create_keychain(
    name: ENV['KEYCHAIN_NAME'],
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: true,
    password: 'shouldnt_matter'
  )

  import_certificate(
    certificate_path: "./fastlane/certificates/staging.p12",
    certificate_password: ENV['CERT_PASSWORD'],
    keychain_name: ENV["KEYCHAIN_NAME"]
  )

  import_certificate(
    certificate_path: "./fastlane/certificates/staging.cer",
    keychain_name: ENV["KEYCHAIN_NAME"]
  )
end
```

Any ideas for how to debug this?

**Comment by KrauseFx** [comment]
Can you share the complete output when running this?

**Comment by designatednerd** [comment]
I ran into this issue and was able to work around it by setting `default_keychain` to `false` and removing the `lock_when_sleeps` parameter altogether.

I think this is exacerbated by [this commit](https://github.com/fastlane/fastlane/commit/660a19b706af1a6d9f852ed8274ef490d6862d26), which changed logging behavior and made it more obtuse if someone chooses to use `false` for logging shell command failures (which is the case in the `create_keychain` action). I think that's a good change overall, and I can understand why the default is false in `create_keychain`, but it'd be nice to be able to have the ability to log temporarily if there are issues with the command.

**Comment by king5956** [comment]
@designatednerd  I have try the setting  as you suggested but it's still crash 
def import_certificates
    return unless Helper.is_ci? 
    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      default_keychain: false,
      unlock: true,
      timeout: 3600,
      password: ENV["KEYCHAIN_PASSWORD"]
    )

    import_certificate(
      certificate_path: "fastlane/certificates/distribution.p12",
      certificate_password: ENV['CERT_PASSWORD'],
      keychain_name: ENV["KEYCHAIN_NAME"]
    )

    import_certificate(
      certificate_path: "fastlane/certificates/ios_distribution.cer",
      keychain_name: ENV["KEYCHAIN_NAME"]
    )
  end

**Comment by king5956** [comment]
`[14:14:35]: -----------------------------
[14:14:35]: --- Step: create_keychain ---
[14:14:35]: -----------------------------
[14:14:35]: Variable Dump:
[14:14:35]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"82", :VERSION_NUMBER=>"7.0.29"}
[14:14:35]: Shell command exited with exit status 48 instead of 0.
+------+---------------------------------------+-------------+
|                      fastlane summary                      |
+------+---------------------------------------+-------------+
| Step | Action                                | Time (in s) |
+------+---------------------------------------+-------------+
| 1    | Verifying required fastlane version   | 0           |
| 2    | default_platform                      | 0           |
| 3    | cocoapods                             | 13          |
| 4    | increment_build_number                | 0           |
| 5    | increment_version_number              | 0           |
| 6    | ./actions/copy_version_to_settings.sh | 0           |
| 7    | generate_release_notes                | 0           |
| 8    | globo_git_commit                      | 0           |
| 9    | create_keychain                       | 0           |
+------+---------------------------------------+-------------+

[14:14:35]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.6/lib/fastlane_core/ui/interface.rb:120:in `crash!': [!] Shell command exited with exit status 48 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.6/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/actions/create_keychain.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:157:in `import_certificates'
	from Fastfile:76:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.6/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:156:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
Recording test results
Finished: FAILURE`

**Comment by king5956** [comment]
@KrauseFx  More update: 
1. when I run the fastlane on my local machine it's working fine.
2.When I run this fastfile with jenkin's this error will popup

**Comment by lisovet** [comment]
@KrauseFx 

```| (6) fastlane@2.1.1                                                           |
+------------------------------------------------------------------------------+
| id: fastlane                                                                 |
| version: 2.1.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-02-13T18:58:59-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
$ cd /Users/vagrant/git
 (i) No Gemfile found - using system installed fastlane ...
 (i) Updating system installed fastlane ...
$ gem install fastlane --no-document
Successfully installed fastlane_core-0.36.4
Successfully installed spaceship-0.19.4
Successfully installed cert-1.3.0
Successfully installed deliver-1.10.2
Successfully installed gym-1.6.0
Successfully installed match-0.3.0
Successfully installed pem-1.2.0
Successfully installed pilot-1.3.0
Successfully installed scan-0.5.0
Successfully installed screengrab-0.2.0
Successfully installed snapshot-1.7.0
Successfully installed fastlane-1.59.0
12 gems installed
Fastlane version:
$ fastlane --version
fastlane 1.59.0
Run fastlane:
$ fastlane staging
[18:59:16]: -------------------------------------------------
[18:59:16]: --- Step: Verifying required fastlane version ---
[18:59:16]: -------------------------------------------------
[18:59:16]: fastlane version valid
[18:59:16]: ------------------------------
[18:59:16]: --- Step: default_platform ---
[18:59:16]: ------------------------------
[18:59:16]: Driving the lane 'ios staging' 🚀
[18:59:16]: ----------------------------------------
[18:59:16]: --- Step: cd ..; ionic state restore ---
[18:59:16]: ----------------------------------------
[18:59:16]: $ cd ..; ionic state restore
[18:59:19]: ▸ ******************************************************
[18:59:19]: ▸  Dependency warning - for the CLI to run correctly,      
[18:59:19]: ▸  it is highly suggested to install/upgrade the following:     
[18:59:19]: ▸  Install ios-sim to deploy iOS applications. `npm install -g ios-sim` (may require sudo)
[18:59:19]: ▸  Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)
[18:59:19]: ▸ ******************************************************
[18:59:19]: ▸ Attempting to restore your Ionic application from package.json
[18:59:19]: ▸ 
[19:00:19]: ▸ Restore plugins is complete
[19:00:19]: ▸ 
[19:00:19]: ▸ Ionic state restore completed
[19:00:19]: ▸ 
[19:00:19]: ----------------------------------------------
[19:00:19]: --- Step: cd ..; ionic build ios --release ---
[19:00:19]: ----------------------------------------------
[19:00:19]: $ cd ..; ionic build ios --release
[19:00:39]: -----------------------------
[19:00:39]: --- Step: create_keychain ---
[19:00:39]: -----------------------------
[19:00:39]: $ security list-keychains -d user
[19:00:39]: ▸ "/Users/vagrant/Library/Keychains/TempKeychain.keychain"
[19:00:39]: --------------------------------
[19:00:39]: --- Step: import_certificate ---
[19:00:39]: --------------------------------
[19:00:39]: --------------------------------
[19:00:39]: --- Step: import_certificate ---
[19:00:39]: --------------------------------
[19:00:39]: Variable Dump:
[19:00:39]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios staging", :ORIGINAL_DEFAULT_KEYCHAIN=>"\"/Users/vagrant/Library/Keychains/login.keychain\""}
[19:00:39]: Shell command exited with exit status 1 instead of 0.
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cd ..; ionic state restore          | 63          |
| 4    | cd ..; ionic build ios --release    | 17          |
| 5    | create_keychain                     | 0           |
| 6    | import_certificate                  | 0           |
| 7    | import_certificate                  | 0           |
+------+-------------------------------------+-------------+
[19:00:39]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/interface.rb:120:in `crash!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/actions/import_certificate.rb:12:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:78:in `import_certificates'
	from Fastfile:29:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/bin/fastlane:38:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/bin/fastlane:150:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.59.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
ERRO[19:00:39] Step (fastlane@2.1.1) failed, error: (exit status 1) 
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | fastlane@2.1.1 (exit code: 1)                                | 102 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-fastlane/issues           |
| Source: https://github.com/bitrise-io/steps-fastlane                         |
+----+--------------------------------------------------------------+----------+```

**Comment by ehlersd** [comment]
I'm having the exact same crash.

**Comment by fabioknoedt** [comment]
Me too.

**Comment by TKBurner** [comment]
Hi @fabioknoedt. Thanks for reaching out. Can you send over the full ouput when you run this command fastlane run import_certificates? Also, can you run fastlane -v and send the output?

Thanks!

**Comment by fabioknoedt** [comment]
Hey @TKBurner, I just realized that (possibly) the error was caused because I was trying to use a "in-house" provisioning profile. Match is not able to work with this kind of profile for security issues, right?

**Comment by TKBurner** [comment]
@fabioknoedt Thanks for following up. Correct:

Attackers could use an In-House profile to distribute signed application to a potentially unlimited number of devices. All this would run under your company name and it could eventually lead to Apple revoking your In-House account. However it is very easy to revoke a certificate to remotely break the app on all devices.

Because of the potentially dangerous nature of In-House profiles we decided to not allow the use of match with enterprise accounts.

Thanks! :+1: 

Closing this out until we get pinged with an update :+1:

**Comment by fabioknoedt** [comment]
Hey @TKBurner, unfortunately I'm still getting the error. It's something about caching or the keychain being there already when creating. I tried to use delete_keychain but it fails when the keychain is not there. Is there a good way to handle that? Below you can see my output.

```
fastlane ios alpha --verbose
INFO [2016-04-08 09:35:46.13]: -------------------------------------------------
INFO [2016-04-08 09:35:46.13]: --- Step: Verifying required fastlane version ---
INFO [2016-04-08 09:35:46.13]: -------------------------------------------------
INFO [2016-04-08 09:35:46.13]: fastlane version valid
INFO [2016-04-08 09:35:46.13]: ------------------------------
INFO [2016-04-08 09:35:46.13]: --- Step: default_platform ---
INFO [2016-04-08 09:35:46.13]: ------------------------------
INFO [2016-04-08 09:35:46.15]: Driving the lane 'ios alpha' 🚀
INFO [2016-04-08 09:35:46.15]: -----------------------------
INFO [2016-04-08 09:35:46.15]: --- Step: create_keychain ---
INFO [2016-04-08 09:35:46.15]: -----------------------------
WARN [2016-04-08 09:35:46.17]: Variable Dump:
INFO [2016-04-08 09:35:46.17]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios alpha"}
ERROR [2016-04-08 09:35:46.17]: Shell command exited with exit status 48 instead of 0.
INFO [2016-04-08 09:35:46.17]: Successfully generated documentation to path '/Users/<user>/projects/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | create_keychain                     | 0           |
+------+-------------------------------------+-------------+

ERROR [2016-04-08 09:35:46.18]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'ced4d3c569da514cb433813089e55e72'
The crash report has been stored locally '/tmp/sentry_ced4d3c569da514cb433813089e55e72.json'
/Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Shell command exited with exit status 48 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/actions/create_keychain.rb:15:in `run'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:108:in `import_certificates'
	from Fastfile:43:in `block (2 levels) in parsing_binding'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/bin/fastlane:158:in `run'
	from /Users/<user>/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.80.0/bin/fastlane:164:in `<top (required)>'
	from /Users/<user>/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/<user>/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/<user>/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/<user>/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by TKBurner** [comment]
@fabioknoedt Thanks for following up. We are going to have a look into this over here. I'll update you when we have news :+1:

**Comment by mrudulp** [comment]
I am seeing this issue as well...(Fastlane 1.81.0)
Work around was to disable import_certificate and use following two commands --
- Unlocking Keychain
`security unlock-keychain -p <pwd>`

- Importing p12 certificate to relevant(login in my case) keychain(actual command that import_certificate achieves).  
`security import <distribution.p12> -k ~/Library/Keychains/login.keychain -P <pwd> -T /usr/bin/codesign -T /usr/bin/security`

I use this on Jenkins within same shell where fastlane is called.

Would be good to have actual fix to import_certificate though

**Comment by fabioknoedt** [comment]
Just want to share my solution with you guys... my way of fixing it was `try`ing to import the certificate and `rescue`ing when the certificate was already there. So, I just added a `begin`, `rescue` and `end` when executing the `import_certificate` command.

```
    begin

      puts 'Importing certificates...'

      # Unlock keychain.
      unlock_keychain(
        path: ENV['KEYCHAIN_NAME'],
        password: ENV['KEYCHAIN_PASSWORD']
      )

      # Import in-house distribution certificate
      import_certificate(
        certificate_path: ENV["CERTIFICATE_P12_PATH"],
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_name: ENV['KEYCHAIN_NAME']
      )

      # Import in-house distribution certificate
      import_certificate(
        certificate_path:  ENV["APPLE_CERTIFICATE_PATH"],
        keychain_name: ENV["KEYCHAIN_NAME"]
      )

      puts 'Certificates imported succesfully.'

    rescue

      puts 'Certificates were already imported to the keychain before.'

    end
```

**Comment by TKBurner** [comment]
@fabioknoedt Thanks for letting me know the solution you found. Closing this out for housekeeping. Thanks! 👍

**Comment by designatednerd** [comment]
One thing I noticed while fighting with this again I could get certs to import using the raw `security` command only if I passed in the path relative to the Fastfile: 

```ruby
sh "security import Certificates/ReleaseCertificates.p12 ......"
```

But, once I figured out what my problem was, `import_certificates` would only work if the path to the certificate was relative to source root: 

```ruby
import_certificate(
  keychain_name: keychain_name,
  certificate_path: "fastlane/Certificates/ReleaseCertificates.p12",
  certificate_password: cert_password,
)
```

Just a PSA for anyone else fighting with this 😝
