### ISSUE TITLE
getaddrinfo: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by yusuftor** [fastlane/fastlane#1315]
I'm using the beta lane of the fastfile that does gym then pilot through Jenkins. It successfully builds and uploads to iTunes Connect, then sends me a notification on Slack saying there was an error and gives me the following error in the output: 

```
`[16:16:48]: [31mgetaddrinfo: nodename nor servname provided, or not known[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | increment_build_number              | 1           |
| 5    | cocoapods                           | 15          |
| 6    | gym                                 | 157         |
| 7    | pilot                               | 278         |
| 8    | slack                               | 0           |
+------+-------------------------------------+-------------+

[16:16:48]: [31mfastlane finished with errors[0m
[33m-------------------------------------------------------------------------------------------[0m
[33m😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.[0m
[33m👍  This makes resolving issues much easier and helps improve fastlane.[0m
[33m🔒  The reports will be stored securely on getsentry.com.[0m
[33m🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3[0m
[33m-------------------------------------------------------------------------------------------[0m
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': [31m[!] getaddrinfo: nodename nor servname provided, or not known[0m (Faraday::ConnectionFailed)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1131:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/client.rb:252:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/client.rb:186:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/client.rb:186:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/client.rb:251:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/client.rb:227:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:513:in `build_trains'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/application.rb:202:in `pre_processing_builds'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/application.rb:231:in `all_processing_builds'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:73:in `block in wait_for_processing_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:70:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:70:in `wait_for_processing_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:21:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:41:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.3/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE`
```

What's causing this problem??

**Comment by KrauseFx** [comment]
```
getaddrinfo: nodename nor servname provided, or not known
```

This seems to be an issue with your internet connection

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
