### ISSUE TITLE
Using Gemfile with `gemspec path` for `fastlane` breaks error reporting for missing methods/actions

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13160]
I locally have fastlane checked out in a folder `win-fastlane` two levels above my project.
In my `Gemfile` I have this `fastlane` checkout configured to be used:

`gemspec path: File.expand_path('..\\..\\win-fastlane')`

This works as expected, unless I break something in my `Fastfile` and use an action or method name that does not exist:

```
...
[01:44:50]:
[!] There was an error parsing `Gemfile`: There are no gemspecs at C:/Projects/Fastlane/fastlane-manual-integration-tests/win-fastlane. Bundler cannot continue.

 #  from C:/Projects/Fastlane/fastlane-manual-integration-tests/android/Gemfile:7
 #  -------------------------------------------
 #
 >  gemspec path: File.expand_path('..\\..\\win-fastlane')
 #  # frozen_string_literal: true
 #  -------------------------------------------


+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | build_android_app | 11          |
+------+-------------------+-------------+

[01:44:50]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:87:in `gemspec':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: There are no gemspecs at C:/Projects/Fastlane/fastlane-manual-integration-tests/win-fastlane. Bundler cannot continue.

 #  from C:/Projects/Fastlane/fastlane-manual-integration-tests/android/Gemfile:7
 #  -------------------------------------------
 #
 >  gemspec path: File.expand_path('..\\..\\win-fastlane')
 #  # frozen_string_literal: true
 #  -------------------------------------------
        from C:/Projects/Fastlane/fastlane-manual-integration-tests/android/Gemfile:7:in `eval_gemfile'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:47:in `instance_eval'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:47:in `eval_gemfile'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:12:in `evaluate'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:57:in `available_gems'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:64:in `available_plugins'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:73:in `plugin_is_added_as_dependency?'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:164:in `trigger_action_by_name'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
        from Fastfile:58:in `get_relative_path'
        from Fastfile:24:in `block in parsing_binding'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Projects/Fastlane/win-fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        from C:/Projects/Fastlane/win-fastlane/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<main>'
```

In this case I used a wrong method name in line 58 in my `Fastfile` (`from Fastfile:58:in 'get_relative_path'`), but somehow fastlane tried to load a plugin, eval'd the `Gemfile` in the wrong context (probably inside `fastlane` instead of `.`) which causes this second, misleading error.

**Comment by janpio** [comment]
See investigation on this topic here: https://github.com/fastlane/fastlane/issues/13215#issuecomment-415855002
