### ISSUE TITLE
[Plugin development] All lane execution crashes with local fastlane checkout via Gemfile

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13215]
I develop a plugin locally. As I have some unreleased changes for _fastlane_ that I need, I modified the `Gemfile` and replaced `gemspec` with `gemspec(path: File.expand_path("../win-fastlane"))` so it points to my local fastlane checkout. (This follows the description at https://github.com/fastlane/fastlane/blob/master/Testing.md#test-your-local-fastlane-code-base-with-your-setup)

Unfortunately all lanes, even the default and generated `test` lane, crash now:

```
λ bundle exec fastlane test
[✔] 🚀
gemfile_path: C:/Projects/Fastlane/fastlane-plugin-repro/Gemfile
[20:01:58]: Driving the lane 'test' 🚀
plugin_name: fastlane-plugin-repro
gemfile_path: C:/Projects/Fastlane/fastlane-plugin-repro/Gemfile
+---------------+------+
|     Lane Context     |
+---------------+------+
| PLATFORM_NAME |      |
| LANE_NAME     | test |
+---------------+------+
[20:01:58]:
[!] There was an error parsing `Gemfile`: There are no gemspecs at C:/Projects/Fastlane/fastlane-plugin-repro/win-fastlane. Bundler cannot continue.

 #  from C:/Projects/Fastlane/fastlane-plugin-repro/Gemfile:4
 #  -------------------------------------------
 #  plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
 >  eval_gemfile(plugins_path) if File.exist?(plugins_path)
 #  source('https://rubygems.org')
 #  -------------------------------------------

[20:01:58]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:87:in `gemspec':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: There are no gemspecs at C:/Projects/Fastlane/fastlane-plugin-repro/win-fastlane. Bundler cannot continue.

 #  from C:/Projects/Fastlane/fastlane-plugin-repro/Gemfile:4
 #  -------------------------------------------
 #  plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
 >  eval_gemfile(plugins_path) if File.exist?(plugins_path)
 #  source('https://rubygems.org')
 #  -------------------------------------------
        from C:/Projects/Fastlane/fastlane-plugin-repro/Gemfile:4:in `eval_gemfile'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:47:in `instance_eval'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:47:in `eval_gemfile'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:12:in `evaluate'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:58:in `available_gems'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:65:in `available_plugins'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:75:in `plugin_is_added_as_dependency?'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:164:in `trigger_action_by_name'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
        from Fastfile:2:in `block in parsing_binding'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Projects/Fastlane/win-fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        from C:/Projects/Fastlane/win-fastlane/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<main>'
```

If I read the stacktrace correctly it tries to find out if the lane I am running is from a loaded plugin
(which I am actually just developing)
and does that by checking the Gemfile
but this time probably not from `/` context but `/fastlane` (edited)

## Reproduction steps:

1. `fastlane new_plugin repro`
2. `cd fastlane-plugin-repro`
3. `bundle exec fastlane test` - observe successful execution of lane
4. Replace `gemspec` with `gemspec(path: File.expand_path("../win-fastlane"))` in `Gemfile` (set your local fastlane path of course)
5. `bundle update` - observe that `fastlane` is now loaded from path
6. `bundle exec fastlane test` and observe crash

## Workaround
<strike>I can undo the changes in my `Gemfile` and _not_  run `bundle update`. Then `bundle exec fastlane` still uses my local checkout, but lane execution succeeds.</strike>

(Maybe related to https://github.com/fastlane/fastlane/issues/13160)

**Comment by janpio** [comment]
Same behavior on Mac:

```
MacBook-Pro:fastlane-plugin-repro sujan$ bundle exec fastlane test
[✔] 🚀 
[20:51:53]: Driving the lane 'test' 🚀
+---------------+------+
|     Lane Context     |
+---------------+------+
| PLATFORM_NAME |      |
| LANE_NAME     | test |
+---------------+------+
[20:51:53]: 
[!] There was an error parsing `Gemfile`: There are no gemspecs at /Users/sujan/fastlane_experiments/fastlane. Bundler cannot continue.

 #  from /Users/sujan/fastlane_experiments/fastlane-plugin-repro/Gemfile:4
 #  -------------------------------------------
 #  #gemspec
 >  gemspec(path: File.expand_path("../../fastlane"))
 #  
 #  -------------------------------------------

[20:51:53]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/sujan/.rvm/gems/ruby-2.4.1/bin/fastlane)
Bundler::Dsl::DSLError: 
[!] There was an error parsing `Gemfile`: There are no gemspecs at /Users/sujan/fastlane_experiments/fastlane. Bundler cannot continue.

 #  from /Users/sujan/fastlane_experiments/fastlane-plugin-repro/Gemfile:4
 #  -------------------------------------------
 #  #gemspec
 >  gemspec(path: File.expand_path("../../fastlane"))
 #  
 #  -------------------------------------------

  /Users/sujan/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/dsl.rb:81:in `gemspec'
  /Users/sujan/fastlane_experiments/fastlane-plugin-repro/Gemfile:4:in `eval_gemfile'
  /Users/sujan/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/dsl.rb:41:in `instance_eval'
  /Users/sujan/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/dsl.rb:41:in `eval_gemfile'
  /Users/sujan/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/dsl.rb:11:in `evaluate'
  /Users/sujan/fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:57:in `available_gems'
  /Users/sujan/fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:64:in `available_plugins'
  /Users/sujan/fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:73:in `plugin_is_added_as_dependency?'
  /Users/sujan/fastlane/fastlane/lib/fastlane/runner.rb:164:in `trigger_action_by_name'
  /Users/sujan/fastlane/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:2:in `block in parsing_binding'
  /Users/sujan/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/sujan/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/sujan/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/sujan/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/sujan/fastlane/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/sujan/fastlane/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/sujan/fastlane/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/sujan/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/sujan/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/sujan/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/sujan/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /Users/sujan/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/sujan/fastlane/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/sujan/fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/sujan/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/sujan/fastlane/bin/fastlane:20:in `<top (required)>'
  /Users/sujan/.rvm/gems/ruby-2.4.1/bin/fastlane:22:in `load'
  /Users/sujan/.rvm/gems/ruby-2.4.1/bin/fastlane:22:in `<top (required)>'
MacBook-Pro:fastlane-plugin-repro sujan$ 
```

**Comment by janpio** [comment]
Ok, problem is here:
https://github.com/fastlane/fastlane/blob/c3befb46e76166d72a2c322a60ce72d66e330070/fastlane/lib/fastlane/plugins/plugin_manager.rb#L55-L59

I hacked this locally to:
```
  def available_gems
      return [] unless gemfile_path
      puts 'gemfile_path: '+gemfile_path
      puts `pwd`
      dsl = Bundler::Dsl.evaluate(gemfile_path, nil, true)
      return dsl.dependencies.map(&:name)
    end
```

which then gives the following output for the lane:

```
λ bundle exec fastlane foo
[✔] 🚀
gemfile_path: C:/Projects/Fastlane/fastlane-plugin-managed_google_play/Gemfile
/c/Projects/Fastlane/fastlane-plugin-managed_google_play
+----------------------------------------+---------+------------------------+
|                               Used plugins                                |
+----------------------------------------+---------+------------------------+
| Plugin                                 | Version | Action                 |
+----------------------------------------+---------+------------------------+
| fastlane-plugin-rename_android_package | 0.1.0   | rename_android_package |
+----------------------------------------+---------+------------------------+

[20:59:51]: Driving the lane 'foo' 🚀
gemfile_path: C:/Projects/Fastlane/fastlane-plugin-managed_google_play/Gemfile
/c/Projects/Fastlane/fastlane-plugin-managed_google_play/fastlane
+---------------+-----+
|    Lane Context     |
+---------------+-----+
| PLATFORM_NAME |     |
| LANE_NAME     | foo |
+---------------+-----+
[20:59:51]:
[!] There was an error parsing `Gemfile`: There are no gemspecs at C:/Projects/Fastlane/fastlane-plugin-managed_google_play/win-fastlane. Bundler cannot continue.

 #  from C:/Projects/Fastlane/fastlane-plugin-managed_google_play/Gemfile:4
 #  -------------------------------------------
 #  plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
 >  eval_gemfile(plugins_path) if File.exist?(plugins_path)
 #  source('https://rubygems.org')
 #  -------------------------------------------

[20:59:51]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:87:in `gemspec':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: There are no gemspecs at C:/Projects/Fastlane/fastlane-plugin-managed_google_play/win-fastlane. Bundler cannot continue.

 #  from C:/Projects/Fastlane/fastlane-plugin-managed_google_play/Gemfile:4
 #  -------------------------------------------
 #  plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
 >  eval_gemfile(plugins_path) if File.exist?(plugins_path)
 #  source('https://rubygems.org')
 #  -------------------------------------------
        from C:/Projects/Fastlane/fastlane-plugin-managed_google_play/Gemfile:4:in `eval_gemfile'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:47:in `instance_eval'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:47:in `eval_gemfile'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:12:in `evaluate'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:59:in `available_gems'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:66:in `available_plugins'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/plugins/plugin_manager.rb:76:in `plugin_is_added_as_dependency?'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:164:in `trigger_action_by_name'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
        from Fastfile:51:in `block in parsing_binding'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Projects/Fastlane/win-fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from C:/Projects/Fastlane/win-fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        from C:/Projects/Fastlane/win-fastlane/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<main>'
```

Right at the beginning the method is executed and outputs:
```
gemfile_path: C:/Projects/Fastlane/fastlane-plugin-managed_google_play/Gemfile
/c/Projects/Fastlane/fastlane-plugin-managed_google_play
```

Then a bit later:
```
gemfile_path: C:/Projects/Fastlane/fastlane-plugin-managed_google_play/Gemfile
/c/Projects/Fastlane/fastlane-plugin-managed_google_play/fastlane
```

As you can see the `Gemfile` path is correct both times, but the execution context is a different one.

**Comment by janpio** [comment]
To make things a bit _more_ complicated, the stacktrace and bundler error message on Windows are misleading:

```
...
 #  from C:/Projects/Fastlane/fastlane-plugin-repro/Gemfile:4
 #  -------------------------------------------
 #  plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
 >  eval_gemfile(plugins_path) if File.exist?(plugins_path)
 #  source('https://rubygems.org')
 #  -------------------------------------------
        from C:/Projects/Fastlane/fastlane-plugin-repro/Gemfile:4:in `eval_gemfile'
...
```

Line 4 of the `Gemfile` is not the `eval_gemfile` for the plugins, but `gemspec ...`. This becomes clear when one looks at the 3 output lines a bit more and actually comments them out in the file:
```
[!] There was an error parsing `Gemfile`: There are no gemspecs at C:/Projects/Fastlane/fastlane-plugin-repro/win-fastlane. Bundler cannot continue.

 #  from C:/Projects/Fastlane/fastlane-plugin-repro/Gemfile:4
 #  -------------------------------------------
 #  #plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
 >  #eval_gemfile(plugins_path) if File.exist?(plugins_path)
 #  source('https://rubygems.org')
 #  -------------------------------------------
        from C:/Projects/Fastlane/fastlane-plugin-repro/Gemfile:4:in `eval_gemfile'
```

Here the `> ` points to a line that is not even executed. Additionally you can notice that it shows line #1 (`source('https://rubygems.org')`)  at the end of the file.

---

The correct stacktrace is the macOS one:
https://github.com/fastlane/fastlane/issues/13215#issuecomment-415851363

**Comment by janpio** [comment]
So: Should we change the execution context in `available_gems` for `Bundler::Dsl.evaluate(...)` somehow? 
We can't just `Dir.chdir('../')` as the code is executed in both contexts: `/` and `/fastlane` and both times have to succeed. Is there a variable or method that returns the project path without `/fastlane` at the end?

**Comment by janpio** [comment]
One solution or workaround (I am not sure which yet) seems to be to **keep** the normal `gemspec` and then just _add_  the `gemspec(path: File.expand_path("../win-fastlane"))` line.

If this is a proper solution, it might be enough to change some documentation.

**Comment by janpio** [comment]
See https://gist.github.com/quincunx/4f3e0f31c24bb4b38d302fd15e4b3d0a
