### ISSUE TITLE
[CI] Sometimes `match/spec/encrypt_spec.rb:29` and `match/spec/encryption/openssl_spec.rb:31` fail

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13217]
macOS:

https://circleci.com/gh/fastlane/fastlane/22928

```
  1) Match Match::Encrypt raises an exception if invalid password is passed
     Failure/Error:
       expect do
         @e.decrypt_repo(path: @directory, git_url: @git_url)
       end.to raise_error("Invalid password passed via 'MATCH_PASSWORD'")

       expected Exception with "Invalid password passed via 'MATCH_PASSWORD'" but nothing was raised
     # ./match/spec/encrypt_spec.rb:29:in `block (3 levels) in <top (required)>'
```

Rerun of the exact same commit succeeds: https://circleci.com/gh/fastlane/fastlane/22933

---

Windows:

https://ci.appveyor.com/project/KrauseFx/fastlane/builds/21710677

```
  1) Match Match::Encryption::OpenSSL raises an exception if invalid password is passed
     Failure/Error:
       expect do
         @e.decrypt_files
       end.to raise_error("Invalid password passed via 'MATCH_PASSWORD'")
       expected Exception with "Invalid password passed via 'MATCH_PASSWORD'" but nothing was raised
     # ./match/spec/encryption/openssl_spec.rb:31:in `block (3 levels) in <top (required)>'
```

Rerun also fixes the problem.

**Comment by janpio** [comment]
This failure pops up from time to time on all the CI systems. There has to be some randomness in those tests.
