### ISSUE TITLE
How to pass testflight demo account information to pilot?

### ISSUE THREAD

**Issue by WilliamIzzo83** [fastlane/fastlane#13232]
Hello everybody,

I'd like to supply testflight information during beta upload and I was wondering: how to set up the demo account? I know there is an option to tell pilot that test flight needs a demo account, but I don't seem to find anything to set up the credentials.

Thank you!

**Comment by WilliamIzzo83** [comment]
Hello thank you for your time!

Yes those credentials refers to my app of course. What I wanted to know was if there is a way to provide them with fastlane as we can do with other metadata (like itunes stuff)

Hope this better clarifies my needs

**Comment by janpio** [comment]
Yes it does :) I think there was another issue recently requesting that functionality - which was missing by the time. You might want to search for that issue.

**Comment by awgeorge** [comment]
@janpio - I can see that `Deliver` can supply this information using `app_review_information` - but this issue is specifically released to `Pilot` or the TestFlight actions. Can you help? As I have the same issue, thanks :)

**Comment by awgeorge** [comment]
Seems like we need the hit the following APIs when when we're on the beta testing page - it's probably a similar payload but the endpoints are `beta`isd 

```
PATCH v1/betaAppLocalizations/{UUID}
{"data":{"type":"betaAppLocalizations","id":"{UUID}","attributes":{"description":"Description","feedbackEmail":"email@example.com","marketingUrl":"http://example.com,"privacyPolicyUrl":"http://example.com","tvOsPrivacyPolicy":null}}}
```

```
PATCH v1/betaAppReviewDetails/{ID}
{"data":{"type":"betaAppReviewDetails","id":"{id}","attributes":{"contactFirstName":"firstname","contactLastName":"lastname","contactPhone":"+0000000000","contactEmail":"email@example.com","demoAccountRequired":true,"demoAccountName":"apple.demo@example.com","demoAccountPassword":"password","notes":"notes"}}}
```

```
PATCH v1/betaLicenseAgreements/{UUID}
{"data":{"type":"betaLicenseAgreements","id":"{UUID}","attributes":{"agreementText":null}}}
```

**Comment by awgeorge** [comment]
Without submitting the information above - the command crashes with:

```
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/test_flight/client.rb:333:in `handle_response': [!] {"code"=>"The email is required.", "description"=>"Failed to submit build for review."} (Spaceship::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/test_flight/build.rb:217:in `submit_for_testflight_review!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/pilot/lib/pilot/build_manager.rb:183:in `distribute_build'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/pilot/lib/pilot/build_manager.rb:108:in `distribute'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/pilot/lib/pilot/build_manager.rb:61:in `upload'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from ../../../../../../../../../var/folders/xm/1f8f18411bd98mczv8mm293m0000gp/T/fl_clone20181012-15792-1nkh2t1/fastlane.git/fastlane/Fastfile:120:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```
