### ISSUE TITLE
An error occurs when I run `fastlane init`

### ISSUE THREAD

**Issue by Quentiu** [fastlane/fastlane#1336]
All I'm doing is running `fastlane init` and then supplying an Apple ID. The Apple ID does not have an iTunes Connect account assigned to it.

This is the error output I see:
```
[16:51:10]: Error occurred with the setup program! Reverting changes now!
[16:51:10]: Deleting the 'fastlane' folder
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '430ba8caf85a3f92cb79389fefc140ca'
The crash report has been stored locally '/tmp/sentry_430ba8caf85a3f92cb79389fefc140ca.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/client.rb:268:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:45:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:83:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/setup/setup_ios.rb:173:in `detect_if_app_is_available'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/setup/setup_ios.rb:29:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/bin/fastlane:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

We had a conversation on Twitter about is here: https://twitter.com/KrauseFx/status/700119350196490242

Thank you!

**Comment by Quentiu** [comment]
I think this issue is a duplicate of: https://github.com/fastlane/fastlane/issues/1277. I'll close this one out.

**Comment by Quentiu** [comment]
Also a duplicate of https://github.com/fastlane/fastlane/issues/1317
