### ISSUE TITLE
Upload multiple dSYMs for multiple applications caused crash

### ISSUE THREAD

**Issue by GerritPost** [fastlane/fastlane#13386]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`Upload_symbols_to_crashlytics` failed due uploading a not-existing dSYM. 

I want to upload multiple dSYMs to multiple firebase crashlytics projects. When i'm uploading the dsyms 'one by one' it works fine. When i'm uploading dSYMs for multiple applications  it fails on the second application. The problem is clear, it tries to upload a dsym that does not exists because it is removed by the function `clean_build_artifacts`

```
 #failed (multiple dSYM upload)
  lane :uploadDsyms do
      StaticInfo.new.application_schemes.each{|scheme|
        app_identifier, app_scheme, team_id, testflight_teamid, company, platform = getBuildVarsIos(scheme)
        download_dsyms(app_identifier: app_identifier, platform: platform, username: username, team_id: testflight_teamid, version:'latest')
        upload_symbols_to_crashlytics   # Upload them to Crashlytics
        clean_build_artifacts         # Delete the local dSYM files
      }
  end

#works (single dSYM upload)
  lane :uploadDsym do |options|
    app_identifier, app_scheme, team_id, testflight_teamid, company, platform = getBuildVarsIos(options[:scheme])
    download_dsyms(app_identifier: app_identifier, platform: platform, username: username, team_id: testflight_teamid, version:'latest')
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts         # Delete the local dSYM files
  end
```

When `clean_build_artifacts` is removed from the for-each it will cause that FirstApplication dSYMs will be uploaded to SecondApplication

i'm guessing that there is some 'magic' when the fastlane finished a lane. That is the only way i can explain why **single** dSYM upload in a single lane is working and **multiple** uploads in a single lane fails. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>iMac-C02Q1080FY11local:ios post$ fastlane uploadDsyms
[08:15:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:15:19]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
[08:15:20]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
[08:15:20]: You have required a gem, if this is a third party gem, please use `fastlane_require "spaceship"` to ensure the gem is installed locally.
[08:15:20]: ----------------------------------------
[08:15:20]: --- Step: Verifying fastlane version ---
[08:15:20]: ----------------------------------------
[08:15:20]: Your fastlane version 2.104.0 matches the minimum requirement of 2.98.0  ✅
[08:15:20]: ------------------------------
[08:15:20]: --- Step: default_platform ---
[08:15:20]: ------------------------------
[08:15:20]: Driving the lane 'ios uploadDsyms' 🚀
"scheme: FirstApplication  🙌"
[08:15:20]: ----------------------------
[08:15:20]: --- Step: download_dsyms ---
[08:15:20]: ----------------------------
[08:15:20]: Login to App Store Connect (developer@example.com)
[08:15:23]: Login successful
[08:15:24]: Looking for latest version...
[08:15:28]: Looking for dSYM files for com.example.FirstApplication v3.2.6 (36)
[08:15:31]: 🔑  Successfully downloaded dSYM file for 3.2.6 - 36 to 'com.example.FirstApplication-3.2.6-36.dSYM.zip'
[08:15:31]: -------------------------------------------
[08:15:31]: --- Step: upload_symbols_to_crashlytics ---
[08:15:31]: -------------------------------------------
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: invalid byte sequence in UTF-8
[08:15:32]: Extracting '/Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip'...
[08:15:32]: $ unzip -qo /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip
[08:15:33]: Uploading '14BC5197-38B6-3770-87A0-D40FB3261013.dSYM'...
[08:15:37]: Uploading '20C3CF2F-4004-304F-AA3A-29882375C10E.dSYM'...
[08:15:43]: Successfully uploaded dSYM files to Crashlytics 💯
[08:15:43]: -----------------------------------
[08:15:43]: --- Step: clean_build_artifacts ---
[08:15:43]: -----------------------------------
[08:15:43]: Cleaned up build artifacts 🐙
"scheme: SecondApplication  🙌"
[08:15:43]: ----------------------------
[08:15:43]: --- Step: download_dsyms ---
[08:15:43]: ----------------------------
[08:15:43]: Login to App Store Connect (developer@example.com)
[08:15:45]: Login successful
[08:15:46]: Looking for latest version...
[08:15:50]: Looking for dSYM files for com.example.SecondApplicationtv v3.2.6 (36)
[08:15:53]: 🔑  Successfully downloaded dSYM file for 3.2.6 - 36 to 'com.example.SecondApplicationtv-3.2.6-36.dSYM.zip'
[08:15:53]: -------------------------------------------
[08:15:53]: --- Step: upload_symbols_to_crashlytics ---
[08:15:53]: -------------------------------------------
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: invalid byte sequence in UTF-8
[08:15:54]: Extracting '/Users/post/Documents/react-native/react-native-app/ios/com.example.SecondApplicationtv-3.2.6-36.dSYM.zip'...
[08:15:54]: $ unzip -qo /Users/post/Documents/react-native/react-native-app/ios/com.example.SecondApplicationtv-3.2.6-36.dSYM.zip
[08:15:54]: Uploading '0ED371C8-FA61-30F9-BE77-1B40A42FF97B.dSYM'...
[08:15:59]: Uploading 'A35C8232-AE56-3C52-A70A-47F6DF09736E.dSYM'...
[08:16:04]: Extracting '/Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip'...
[08:16:04]: $ unzip -qo /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip
[08:16:04]: ▸ unzip:  cannot find or open /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip, /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip.zip or /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip.ZIP.
+-----------------------------------+--------------------------------------+
|                               Lane Context                               |
+-----------------------------------+--------------------------------------+
| DEFAULT_PLATFORM                  | ios                                  |
| PLATFORM_NAME                     | ios                                  |
| LANE_NAME                         | ios uploadDsyms                      |
| DSYM_PATHS                        | ["/Users/post/Documents/react  |
|                                   | -native/react-native-app/ios/eu.tra  |
|                                   | decast.FirstApplication-3.2.6-36.dSYM  |
|                                   | .zip",                               |
|                                   | "/Users/post/Documents/react-  |
|                                   | native/react-native-app/ios/eu.trad  |
|                                   | ecast.SecondApplication-3.2.6-36.dSYM.zip  |
|                                   | "]                                   |
| GET_INFO_PLIST_VALUE_CUSTOM_VALUE |                                      |
+-----------------------------------+--------------------------------------+
[08:16:04]: Exit status of command 'unzip -qo /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip' was 9 instead of 0.
unzip:  cannot find or open /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip, /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip.zip or /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip.ZIP.

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying fastlane     | 0           |
|      | version                |             |
| 2    | default_platform       | 0           |
| 3    | download_dsyms         | 11          |
| 4    | upload_symbols_to_cra  | 12          |
|      | shlytics               |             |
| 5    | clean_build_artifacts  | 0           |
| 6    | download_dsyms         | 9           |
| 💥   | upload_symbols_to_cra  | 11          |
|      | shlytics               |             |
+------+------------------------+-------------+

[08:16:04]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'unzip -qo /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip' was 9 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
unzip:  cannot find or open /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip, /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip.zip or /Users/post/Documents/react-native/react-native-app/ios/com.example.FirstApplication-3.2.6-36.dSYM.zip.ZIP.

	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:56:in `block (2 levels) in handle_dsym'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:55:in `chdir'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:55:in `block in handle_dsym'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:54:in `handle_dsym'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:39:in `block in run'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:38:in `each'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:38:in `run'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:504:in `block (4 levels) in parsing_binding'
	from Fastfile:501:in `each'
	from Fastfile:501:in `block (3 levels) in parsing_binding'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/post/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/bin/fastlane:20:in `<top (required)>'
	from /Users/post/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/post/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.104.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-09-19**
</details></pre>
</details>

**Comment by GerritPost** [comment]
For now i've found a workaround. 

By using shell script and calling the `uploadDsym` lane for each scheme

```
lane :uploadDsyms do
    StaticInfo.new.application_schemes.each{|scheme|
      # Ugly workaround
      sh "fastlane uploadDsym scheme:#{scheme}"
    }
end

#works (single dSYM upload)
lane :uploadDsym do |options|
  app_identifier, app_scheme, team_id, testflight_teamid, company, platform = getBuildVarsIos(options[:scheme])
  download_dsyms(app_identifier: app_identifier, platform: platform, username: username, team_id: testflight_teamid, version:'latest')
  upload_symbols_to_crashlytics   # Upload them to Crashlytics
  clean_build_artifacts         # Delete the local dSYM files
end
```
