### ISSUE TITLE
Problem when using fastlane with jenkins and changing version number

### ISSUE THREAD

**Issue by Ricardo1980** [fastlane/fastlane#13387]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

I have a problem with fastlane but only if I use jenkins, when using the terminal, everything works fine.
Here is the test project: https://github.com/Ricardo1980/TestFastlane

This works properly if I use the terminal:

```
build_number = increment_build_number(xcodeproj: "TestFastlane.xcodeproj")
commit_version_bump(
  message: 'Build Version Bump by fastlane',
  xcodeproj: "TestFastlane.xcodeproj",
  force: true
)
push_to_git_remote
```

But if I use that in jenkins I receive this error:
```
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [31m[!] Exit status of command 'git push origin master:master --tags' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
error: src refspec master does not match any.
error: failed to push some refs to 'git@github.com:Ricardo1980/TestFastlane.git'
```

Here the entire jenkins log:
[jenkins_log.txt](https://github.com/fastlane/fastlane/files/2396852/jenkins_log.txt)

However, if I use the HEAD solution explained here (I have the same problem, btw):
https://github.com/fastlane/fastlane/issues/7588

Like this:
```
build_number = increment_build_number(xcodeproj: "TestFastlane.xcodeproj")
commit_version_bump(
  message: 'Build Version Bump by fastlane',
  xcodeproj: "TestFastlane.xcodeproj",
  force: true
)
push_to_git_remote(remote: "origin", local_branch: "HEAD", remote_branch: "master", force: true, tags: true)
```

It appears to work, but the testflight upload process fails at the end with a problem regarding version numbers. It seems when using HEAD, the version number is not processed properly. Not sure.

```
[17:54:30]: [32mBuild 2.0.0 - 185 is already being tested[0m
[17:54:30]: [33mUploaded app 2.0.0 - 188, but received build 2.0.0 - 185. If you want to wait for uploaded build to be finished processing, use the `wait_for_uploaded_build` option[0m
“/Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/spaceship/lib/spaceship/test_flight/client.rb:333:in `handle_response’: [31m[!] {“code”=>“ITC.response.error.INVALID_REQUEST”, “”description”=>“Failed to submit build for review.“}[0m (Spaceship::UnexpectedResponse)”
```

Can anyone help me with this?
Perhaps it is related with how jnkins checks out the project, or something about GIT I cannot see.
Thanks a lot for your help.

This is my fastlane env output:
[fastlane_env.txt](https://github.com/fastlane/fastlane/files/2396851/fastlane_env.txt)

**Comment by Ricardo1980** [comment]
I found 2 ways to solve this.

Adding sh("git checkout development") to my fastlane script or using an option called "Check out to specific local branch" in jenkins.
