### ISSUE TITLE
fastlane deliver fails to generate html (XCode10)

### ISSUE THREAD

**Issue by chnbr** [fastlane/fastlane#13383]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I use fastlane deliver 2.104.0 along with Xcode 10. When deliver I get the following error during html generation. This deliver file worked in earlier versions with Xcode 9.4 perfectly.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>.....
[18:35:34]: Loading './metadata/review_information/phone_number.txt'...
[18:35:34]: Loading './metadata/review_information/email_address.txt'...
[18:35:34]: Loading './metadata/review_information/demo_user.txt'...
[18:35:34]: Loading './metadata/review_information/demo_password.txt'...
[18:35:34]: Loading './metadata/review_information/notes.txt'...
[18:35:35]: Detected languages: ["de-DE", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fr-CA", "fr-FR", "ja", "ko", "pt-BR", "pt-PT", "ru", "zh-Hans", "default"]
[18:35:35]: #TypeError: no implicit conversion of nil into String
[18:35:35]: /Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/deliver/lib/deliver/html_generator.rb:61:in `join'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/deliver/lib/deliver/html_generator.rb:61:in `render'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/deliver/lib/deliver/html_generator.rb:13:in `run'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/deliver/lib/deliver/runner.rb:180:in `validate_html'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/deliver/lib/deliver/runner.rb:117:in `upload_metadata'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/deliver/lib/deliver/runner.rb:38:in `run'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
/Users/neu/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.104.0/bin/fastlane:20:in `<top (required)>'
/Users/neu/.fastlane/bin/bundle/bin/fastlane:22:in `load'
/Users/neu/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
[18:35:35]: Could not render HTML preview. Do you still want to continue?

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.13.6                              |
| Ruby                        | 2.2.4                                |
| Bundler?                    | false                                |
| Git                         | git version 2.17.1 (Apple Git-112)   |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.13.6 (17G65)             |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained                | false                                |
| Is homebrew                 | true                                 |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.104.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-09-18**
</details>

**Comment by chnbr** [comment]
> It seems like you have not included the output of `fastlane env`
> 
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

corrected ;-)

**Comment by chnbr** [comment]
Anybody who experiences similar problems ? 

In addition deliver seems to be extremely moody because currently  I need up to 10 attempts to upload metadata. 9 fails and then suddenly 1 successful upload.

Any help ?
