### ISSUE TITLE
Missing dependency for 'scp' action

### ISSUE THREAD

**Issue by tomassliz** [fastlane/fastlane#1339]
There is missing `net-scp` dependency for **scp** action. I have to install it manually because I got this error:
```
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/helper/gem_helper.rb:20:in `rescue in verify_gem!': [!] You have to install the `net-scp` (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/helper/gem_helper.rb:6:in `verify_gem!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/actions/scp.rb:9:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:19:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.60.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
That is by design to keep `fastlane` slim and fast. You should use bundler with a Gemfile to define this dependency. 
I just pushed a new commit improving the error message with more information about this. Also if you scroll up a little bit you'll see more information about how to add this dependency.

**Comment by tomassliz** [comment]
Ok, I understand. Thank you.
