### ISSUE TITLE
Fastlane failed with errors

### ISSUE THREAD

**Issue by kamarshad** [fastlane/fastlane#13397]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have been getting following random issues while running `fastlane deploy` command. I am not able to understand the error logs properly.

-  **Gym failed**
-  **auto_changelog failed**

I wonder for  **au_changelog failed** case, following steps are being performed successfully.
- Unit test cases passed
- iPA archived
- DSYM file generated.

The only place where issue is coming is notes are being added to `hockey`. 
 
hockey(
      api_token: "#{environment['ThirdParty']['HockeyAPIToken']}",
      public_identifier: "#{environment['ThirdParty']['HockeyAppId']}",
      notify: '1',
      notes: auto_changelog()
    )
 
Here are the error logs

[15:28:20]: Successfully exported and compressed dSYM file
[15:28:20]: Successfully exported and signed the ipa file:
[15:28:20]: /Users/jenkins/Desktop/xyz-ios/xyz.ipa
[15:28:20]: ----------------------------
[15:28:20]: --- Step: auto_changelog ---
[15:28:20]: ----------------------------
[15:28:20]: Trying to get changes from changelog
+----------------------------+-------------------------------------------------------------------------------------+
|                                                   Lane Context                                                   |
+----------------------------+-------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                                 |
| PLATFORM_NAME              | ios                                                                                 |
| LANE_NAME                  | ios deploy                                                                          |
| SCAN_DERIVED_DATA_PATH     | /Users/jenkins/Library/Developer/Xcode/DerivedData/App-anydfisgvpjzabhivjwiveiuiac  |
|                            | z                                                                                   |
| SCAN_GENERATED_PLIST_FILES | ["/Users/jenkins/Library/Developer/Xcode/DerivedData/App-anydfisgvpjzabhivjwiveiui  |
|                            | acz/Logs/Test/0A7B0AF7-1A39-42F7-829C-BAC4B9BF9F45_TestSummaries.plist"]            |
| SCAN_GENERATED_PLIST_FILE  | /Users/jenkins/Library/Developer/Xcode/DerivedData/App-anydfisgvpjzabhivjwiveiuiac  |
|                            | z/Logs/Test/0A7B0AF7-1A39-42F7-829C-BAC4B9BF9F45_TestSummaries.plist                |
| BUILD_NUMBER               | 1809191458                                                                          |
| IPA_OUTPUT_PATH            | /Users/jenkins/Desktop/xyz-ios/xyz.ipa                                |
| DSYM_OUTPUT_PATH           | /Users/jenkins/Desktop/xyz-ios/xyz.app.dSYM.zip                       |
| XCODEBUILD_ARCHIVE         | /Users/jenkins/Library/Developer/Xcode/Archives/2018-09-19/Lxyz 2018-09-19    |
|                            | 15.13.18.xcarchive                                                                  |
+----------------------------+-------------------------------------------------------------------------------------+

+------+--------------------------------------------------------+-------------+
|                              fastlane summary                               |
+------+--------------------------------------------------------+-------------+
| Step | Action                                                 | Time (in s) |
+------+--------------------------------------------------------+-------------+
| 1    | Verifying fastlane version                             | 0           |
| 2    | default_platform                                       | 0           |
| 3    | is_ci                                                  | 0           |
| 4    | cocoapods                                              | 210         |
| 5    | Switch to ios environment lane                         | 0           |
| 6    | Switch to ios test lane                                | 0           |
| 7    | scan                                                   | 859         |
| 8    | increment_build_number                                 | 6           |
| 9    | open                                                   | 0           |
|      | ./provisioning_profiles/LC/Develop/App.mobileprovisio  |             |
|      | n                                                      |             |
| 10   | open                                                   | 0           |
|      | ./provisioning_profiles/LC/Develop/ChooserOnly.mobile  |             |
|      | pro                                                    |             |
| 11   | open                                                   | 0           |
|      | ./provisioning_profiles/LC/Develop/FileChooser.mobile  |             |
|      | pro                                                    |             |
| 12   | gym                                                    | 920         |
| 💥   | auto_changelog                                         | 0           |
+------+--------------------------------------------------------+-------------+

[15:28:21]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [screengrab] No device detection doesn't work on Windows
    https://github.com/fastlane/fastlane/issues/13173 [open] 1 💬
    4 weeks ago

➡️  undefined method `compact' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/12652 [closed] 8 💬
    01 Aug 2018

➡️  undefined method when running frameit
    https://github.com/fastlane/fastlane/issues/12934 [closed] 2 💬
    4 weeks ago

and 354 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/jenkins/Desktop/xyz-ios/fastlane/actions/auto_changelog.rb:10:in `run': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:124:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

###  auto_changelog.rb source 
<details>
  <pre>
module Fastlane
  module Actions
    class AutoChangelogAction < Action
      def self.run(params)
        UI.message "Trying to get changes from changelog"
        path = params[:path] || "./fastlane/.auto_changelog.txt"
        commit_from = self.get(path)
        last_commit = other_action.last_git_commit[:commit_hash]
        self.set(path, last_commit)
        if commit_from.empty?
          commit_from = last_commit
        end
        other_action.changelog_from_git_commits(between: [commit_from, "HEAD"])
      end
      def self.get(path)
        changelog = ""
        if File.exist? path
          changelog = File.read(path)
        end
        changelog.strip
      end
      def self.set(path, content)
        File.open(path, 'w') do |fo|
          fo.puts content
        end
      end
      #####################################################
      # @!group Documentation
      #####################################################
      def self.description
        "Auto generating changelog"
      end
      def self.details
        "Auto generating changelog"
      end
      def self.available_options
        [
          FastlaneCore::ConfigItem.new(
            key: :path,
            description: "Path for temporary file. Please add this file to .gitignore. If you are using reset_git_repo please remember to set disregard_gitignore to false",
            is_string: false,
            default_value: "./fastlane/.auto_changelog.txt"
          )
        ]
      end
      def self.output
        []
      end
      def self.return_value
        "Generated changelog"
      end
      def self.authors
        ["author-name"]
      end
      def self.is_supported?(platform)
        platform == :ios
      end
    end
  end
end
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.1 (Apple Git-101)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.104.0"

default_platform :ios

platform :ios do
  before_all do
    # before all
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "0"
  end

  private_lane :environment do |options|
    path_plist = Plist::parse_xml("../App/Path.plist")
    folder_path = path_plist[options[:folder_name]]
    plist = Plist::parse_xml("#{folder_path}")

    plist[options[:name]]
  end

  desc "Add specific device"
  lane :add_device do |options|
    configuration = options[:configuration]
    environment = environment(name: configuration)
      
    register_devices(
      team_id: "#{environment['Configuration']['teamId']}",
      devices: {
        options[:name] => options[:udid]
      }
    )
  end

  desc "Download provisioning profile"
  lane :update_provisioning_profile do |options|
    configuration = options[:configuration]
    traget = options[:target]
    environment = environment(name: configuration, folder_name: target)
    
    sigh(
      app_identifier: "#{environment['Configuration']['bundleId']}",
      team_id: "#{environment['Configuration']['teamId']}",
      provisioning_name: "#{environment['Configuration']['bundleId']} #{configuration}",
      development: environment['Configuration']['gymExportMethod'] == "development",
      force: true,
      filename: "fastlane/provisioning_profiles/#{target}/#{configuration}/App.mobileprovision",
      ignore_profiles_with_different_name: true
    )
  end

  desc "Runs all the tests"
  lane :test do |options|
    scan(
      scheme: options[:target_name],
      skip_slack: true,
      clean: true
    )
  end
  
  lane :t do |options|
    ensure_git_status_clean
    UI.message auto_changelog
    reset_git_repo(
      disregard_gitignore: false
    )
  end

  desc "Deploy a new version"
  lane :deploy do |options|
    if is_ci
      ensure_git_status_clean
    end

    cocoapods(
        repo_update: true
    )

    build_number = Time.new.strftime("%y%m%d%H%M")
    configuration = options[:configuration]
    target = options[:target]
    environment = environment(name: configuration, folder_name: target)
    developConfiguration = 'Develop'
    productionConfiguration = 'Production'
    iCloudContainerEnvVariable = 'Development'

    if configuration == productionConfiguration
        iCloudContainerEnvVariable = "Production"
    end

    if configuration == developConfiguration
        test(target_name: target)
    end

    if configuration != productionConfiguration
        increment_build_number(
            build_number: build_number
        )
    end


    sh "open ./provisioning_profiles/#{target}/#{configuration}/App.mobileprovision"
    sh "open ./provisioning_profiles/#{target}/#{configuration}/ChooserOnly.mobileprovision"
    sh "open ./provisioning_profiles/#{target}/#{configuration}/FileChooser.mobileprovision"

    gym(
      scheme: "#{target}",
      configuration: "#{configuration}",
      export_method: "#{environment['Configuration']['gymExportMethod']}",
      export_options: {
        compileBitcode: false,
        iCloudContainerEnvironment: iCloudContainerEnvVariable,
        method: options[:export_method],
        teamID: "#{environment['Configuration']['teamId']}",
        provisioningProfiles: {
            "#{environment['Configuration']['bundleId']}": "./fastlane/provisioning_profiles/#{target}/#{configuration}/App.mobileprovision",
            "#{environment['Configuration']['chooserBundleId']}": "./fastlane/provisioning_profiles/#{target}/#{configuration}/ChooserOnly.mobileprovision",
            "#{environment['Configuration']['fileChooserBundleId']}": "./fastlane/provisioning_profiles/#{target}/#{configuration}/FileChooser.mobileprovision"
            }
        },
      include_symbols: true
    )
    hockey(
      api_token: "#{environment['ThirdParty']['HockeyAPIToken']}",
      public_identifier: "#{environment['ThirdParty']['HockeyAppId']}",
      notify: '1',
      notes: auto_changelog()
    )
    if is_ci
      reset_git_repo(
        disregard_gitignore: false
      )
    end
  end
  
  lane :fetch_dsyms do |options|
    configuration = options[:configuration]
    environment = environment(name: configuration)
    
    download_dsyms(
      app_identifier: "#{environment['Configuration']['bundleId']}"
    )
  end

  after_all do |lane|
    # success
  end

  error do |lane, exception|
    # error
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xyz.blahblah" # The bundle identifier of your app
#apple_id "xyz@blahblah.com" # Your Apple email address

team_id "D5NWSMACX3"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.104.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 2.1.0        |
| signet                    | 0.9.2        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-09-20**
</details>
</pre>
</details>

Any suggestion is highly appreciated!
Thanks

**Comment by kamarshad** [comment]
No, it is not related to code signing. @fastlane-bot

**Comment by kamarshad** [comment]
@hjanuschka @KrauseFx 
Can someone please look into the issue and provide the help?

**Comment by kamarshad** [comment]
Waiting for your help @KrauseFx @hjanuschka

**Comment by kamarshad** [comment]
No, @fastlane-bot I am still not able to fix it. Can someone help me out?
