### ISSUE TITLE
ui.rb:17:in `method_missing'

### ISSUE THREAD

**Issue by ksflip** [fastlane/fastlane#13434]
### Issue Description

Getting a Null Pointer Exception with ui.rb:17:in `method_missing' when running FastLane script.

Java version is <b>8 Update 181</b>.
Fastlane <b>2.105.2</b>
Platform: macOS <b>10.13.6 (17G65)</b>
Target platform for build: Android

<b>This is the script:</b>
<details>
  <pre>
default_platform(:android)

platform :android do
  before_all do
    ENV["VERSION_CODE"] = sh("git rev-list HEAD --count").gsub(/\s+/, "")

    gradle(task: "clean")
  end

  desc "Uploads a debugQA build to hockey. Must be on hockey-uk branch"
  lane :uk_staging_hockey_release do |options|
    begin
      ensure_git_branch(branch:"hockey-uk")
      gradle(task: "assembleUkDebugQA")

      file = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

      hockey(
        api_token: "XXX",
        public_identifier: "XXX",
        apk: file,
        notify: "1",
        notes: changelog_from_git_commits)

      #add_git_tag(
      #  tag: tag,
      #  force: true)

      #push_git_tags(
      #  remote: "origin",
      #  tag: tag
      #)

      slack(
          message: "XXX (Android) QA pointing at Staging Released to Hockey",
          success: true,
          slack_url: "https://XXX")
    rescue => exception
      if is_ci
        on_error("UK QA Failed",exception)
      end
      raise exception
    end
  end

end

def on_error(message,exception)
   slack(
       message: "XXX: "+message,
       success: false,
       slack_url: "https://XXX",
       attachment_properties: {
           fields: [
               {
                   title: "Build number",
                   value: ENV["BUILD_NUMBER"],
               },
               {
                   title: "Error message",
                   value: exception,
                   short: false
               }
           ]
       }
   )
end

def getVersionNameFromGit()
  versionName = sh("git describe --match version/[0-9]*.[0-9]*.[0-9]* --abbrev=0 HEAD")
  shortened = versionName.sub! 'version/', ''
  return shortened.gsub(/\s+/, "")
end</pre>
</details>
<br>
<b>Terminal Output is:</b>
<br>
<details>
  <pre>
[!] Exit status of command '/Users/xxx/Documents/Projects/Android/xxx/gradlew clean -p .' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
WARNING: BuildType(debugQA): buildConfigField 'GOOGLE_PAY_TIMEOUT' value is being replaced: 0L -> 4L
WARNING: BuildType(debugQA): buildConfigField 'SOCKET_TIMEOUT_THRESHOLD_SECONDS' value is being replaced: 60L -> 30L
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `sh'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/gradle.rb:52:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:18:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:281:in `execute_flow_block'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
</pre>
</details>

**Comment by ksflip** [comment]
I had to add this to grade.properties:
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
