### ISSUE TITLE
error running screengrab

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#13477]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
While running `screengrab` I am getting following error. This has been reported in the past in #9521

```
Error in com.package.BasicTest:
[13:28:53]: ▸ java.lang.RuntimeException: java.lang.NoSuchMethodException: getConfiguration []
[13:28:53]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:46)
[13:28:53]: ▸ at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:35)
[13:28:53]: ▸ at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[13:28:53]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:28:53]: ▸ at org.junit.runners.Suite.runChild(Suite.java:128)
[13:28:53]: ▸ at org.junit.runners.Suite.runChild(Suite.java:27)
[13:28:53]: ▸ at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[13:28:53]: ▸ at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[13:28:53]: ▸ at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[13:28:53]: ▸ at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[13:28:53]: ▸ at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[13:28:53]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:28:53]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[13:28:53]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[13:28:53]: ▸ at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[13:28:53]: ▸ at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
[13:28:53]: ▸ at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2074)
[13:28:53]: ▸ Caused by: java.lang.NoSuchMethodException: getConfiguration []
[13:28:53]: ▸ at java.lang.Class.getMethod(Class.java:2068)
[13:28:53]: ▸ at java.lang.Class.getMethod(Class.java:1690)
[13:28:53]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:28)
[13:28:53]: ▸ ... 16 more
[13:28:53]: ▸ Time: 0.008
[13:28:53]: ▸ There was 1 failure:
[13:28:53]: ▸ 1) com.package.BasicTest
[13:28:53]: ▸ java.lang.RuntimeException: java.lang.NoSuchMethodException: getConfiguration []
[13:28:53]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:46)
[13:28:53]: ▸ at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:35)
[13:28:53]: ▸ at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[13:28:53]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:28:53]: ▸ at org.junit.runners.Suite.runChild(Suite.java:128)
[13:28:53]: ▸ at org.junit.runners.Suite.runChild(Suite.java:27)
[13:28:53]: ▸ at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[13:28:53]: ▸ at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[13:28:53]: ▸ at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[13:28:53]: ▸ at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[13:28:53]: ▸ at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[13:28:53]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:28:53]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[13:28:53]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[13:28:53]: ▸ at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[13:28:53]: ▸ at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
[13:28:53]: ▸ at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2074)
[13:28:53]: ▸ Caused by: java.lang.NoSuchMethodException: getConfiguration []
[13:28:53]: ▸ at java.lang.Class.getMethod(Class.java:2068)
[13:28:53]: ▸ at java.lang.Class.getMethod(Class.java:1690)
[13:28:53]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:28)
[13:28:53]: ▸ ... 16 more
[13:28:53]: ▸ FAILURES!!!
[13:28:53]: ▸ Tests run: 0,  Failures: 1
```

**Comment by RishabhTayal** [comment]
Looks like this issue happens only on the newer android OS version.

**Comment by janpio** [comment]
Possibly related: https://github.com/fastlane/fastlane/pull/13231

**Comment by RishabhTayal** [comment]
@janpio Any update on this? When is PR #13231 going to be merged?

**Comment by RishabhTayal** [comment]
@janpio I have pointed my fastlane setup to that branch but I am still getting the same error. Looks like the issue still exists that PR.

**Comment by janpio** [comment]
That would be bad news - because then I have no idea what is causing this.

**Comment by RishabhTayal** [comment]
@janpio I think it can be easily reproduced. Just need to run screen grab against latest Android SDK.

**Comment by hosek** [comment]
btw, which version of screengrab are you using? I hit the same issue with 1.0.0, running fine with 1.2.0

**Comment by nicosommi** [comment]
Hi @hosek @RishabhTayal just adding some information. I ran into this now, and updating to screengrab 1.2.0 solved it for me, but I had to update the minSdkVersion from 16 to 18 when using UIAutomator strategy (in my case that was not an issue).

One extra thing to note is that [the docs points to](https://docs.fastlane.tools/getting-started/android/screenshots/#gradle-dependency) use the latest version of screengrab listed on rubygems, [which seems to be 1.0.0](https://rubygems.org/gems/screengrab)... so is apparently outdated there? (I'm not from the ruby world so I may be omitting something)

**Comment by hosek** [comment]
@nicosommi yes, this should be definitely updated - it confused me too.

**Comment by janpio** [comment]
I created https://github.com/fastlane/fastlane/issues/13679 to track and fix this @nicosommi + @hosek.

**Comment by plastiv** [comment]
> That would be bad news - because then I have no idea what is causing this.

Full explanation is here: https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces#about-api-lists

On Android Pie and above applications with targetSdk 28 have been restricted by Google to use reflection for accessing private api. 

Screengrab is using such "black greylisted api" to change location here: https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/screengrab/screengrab-lib/src/main/java/tools.fastlane.screengrab/locale/LocaleUtil.java#L44-L46

It is black greylisted here: https://android.googlesource.com/platform/prebuilts/runtime/+/master/appcompat/hiddenapi-dark-greylist.txt#136

`Landroid/app/IActivityManager$Default;->updateConfiguration(Landroid/content/res/Configuration;)Z`

Meaning screengrab becomes incompatible with androidP(28) and above for usages where locale test rule is being used.

**Comment by janpio** [comment]
Thanks for this research @plastiv! 💟 🍒 
Are you up to creating a PR for `screengrab-lib` that fixes this? That would be awesome and make a lot of people very happy around here 🚀

**Comment by RishabhTayal** [comment]
@fastlane-bot Please keep this open
