### ISSUE TITLE
Snapshot iOS: device.plist not readable!

### ISSUE THREAD

**Issue by philipacrowe** [fastlane/fastlane#13476]
I keep getting this error about CI not being able to read the device.plist . The device GUID referenced in the error does not exist, but I can't work out why fast lane is trying to use it.

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/CFPropertyList-3.0.0/lib/cfpropertylist/rbCFPropertyList.rb:333:in `load': [!] File /Users/philipc/Library/Developer/CoreSimulator/Devices/8CDAB961-8043-42BA-BB14-105E7A232AEC/device.plist not readable! (IOError)
	from /Library/Ruby/Gems/2.3.0/gems/CFPropertyList-3.0.0/lib/cfpropertylist/rbCFPropertyList.rb:238:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/simctl-1.6.5/lib/simctl/device.rb:233:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/simctl-1.6.5/lib/simctl/device.rb:233:in `plist'
	from /Library/Ruby/Gems/2.3.0/gems/simctl-1.6.5/lib/simctl/device.rb:38:in `devicetype'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/test_command_generator.rb:96:in `block in get_device_type_with_simctl'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/test_command_generator.rb:93:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/test_command_generator.rb:93:in `get_device_type_with_simctl'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/test_command_generator.rb:61:in `verify_devices_share_os'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/test_command_generator.rb:36:in `destination'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/test_command_generator.rb:15:in `generate'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:85:in `launch_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:70:in `block (3 levels) in take_screenshots_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:69:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:69:in `block (2 levels) in take_screenshots_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each_with_index'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `block in take_screenshots_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `take_screenshots_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/runner.rb:45:in `work'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/commands_generator.rb:40:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/commands_generator.rb:104:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/snapshot/lib/snapshot/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.105.2/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.1 (Apple Git-112)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G65)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "xxxxxx" # The bundle identifier of your app
apple_id "xxxxxx@xxxxxxx" # Your Apple email address
git_url "https://xxxxxx-xxxx@xxxxxx/xxxx/xxxxxx"
team_id "xxxxxxxx" # Developer Portal Team ID

#build stuff
for_lane :Build do
 app_identifier 'xxxxxxxxx'
end


# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.3       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.5       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.10.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-10-01**
</details></pre>
</details>

**Comment by philipacrowe** [comment]
I've put a temporary hack fix into CFPropertyList-3.0.0/lib/cfpropertylist/rbCFPropertyList.rb load method to swap out the path that fastlane is trying to use for the simulator to the correct one... Where does Fastlane get the device folders from? wherever they come from it isnt getting the correct guid for the simulator its trying to test, its one that doesnt exist on the machine...
