### ISSUE TITLE
make_changelog_from_jenkins doesn't work with authenticated jenkins

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#1348]
WRT 54dcdf97bfda2f27843244d4c1d339d6c487affb

Note that this won't work if your jenkins requires authentication. See https://wiki.jenkins-ci.org/display/JENKINS/Authenticating+scripted+clients

This causes: 
````
/Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in `initialize': [!] Operation timed out - connect(2) for "...." port .... (Errno::ETIMEDOUT)
	from /Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:583:in `start'
	from /Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:478:in `get_response'
	from /Users/Shared/Jenkins/Home/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:455:in `get'
	from /Users/Shared/Jenkins/Home/.rvm/gems/ruby-2.2.4/bundler/gems/fastlane/lib/fastlane/actions/make_changelog_from_jenkins.rb:14:in `run'
```

Given jenkins limitations, I wonder if it's not easier to write a jenkins plugin whose job is to dump the changelog to file then simply read it ? @mandrizzle  ?

(reference on how to generate the changelog: https://github.com/jenkinsci/testflight-plugin/commit/e8edfef012d4bdefb95ee24818891a27ac920a36)

**Comment by mandrizzle** [comment]
Interesting, I did not have to really deal with authentication since my jenkins instance is hosted on a VPN. It looks like a simple fix according to this:

https://wiki.jenkins-ci.org/display/JENKINS/Authenticating+scripted+clients

I can add some environment variables to the script like `FL_JENKINS_USERNAME`, `FL_JENKINS_PASSWORD`, `FL_JENKINS_TOKEN` which can be used to supply jenkins credentials

**Comment by lacostej** [comment]
it's a bit strange in my head to have to use my own HTTP credentials + a personal token to make the script that runs inside the job call back to the jenkins HOST. The execuion might be on a slave, maybe without proper HTTP connection.

Still attached is a potential improvement.

**Comment by mandrizzle** [comment]
I like it, I was not aware of a json api. I might try playing around with auth on jenkins, but if you already are working on it, you should totally make an update to the script!

**Comment by mandrizzle** [comment]
Just to add, looks like simple auth is easy with the networking lib

http://ruby-doc.org/stdlib-2.3.0/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Basic+Authentication

**Comment by TiagoVeloso** [comment]
I've also had problems getting the changelog from my Jenkins instance.

```
Unable to read/parse changelog from jenkins: 776: unexpected token at '<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fjob%2Fios-game-develop%2F507%2Fapi%2Fjson%3Fwrapper%3Dchanges%26xpath%3D%2F%2FchangeSet%2F%2Fcomment'/><script>window.location.replace('/login?from=%2Fjob%2Fios-game-develop%2F507%2Fapi%2Fjson%3Fwrapper%3Dchanges%26xpath%3D%2F%2FchangeSet%2F%2Fcomment');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:
  
Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html>                                                                                                                                                                                                                                                                                                            '
```

It seems authentication is the issue here. Anonymous access is not enough for my set up.

**Comment by ohwutup** [comment]
Going to close this issue for now as it has been quite a while since there has been any activity. Let us know if there are any issues still happening and we can investigate further. 🔍 🐰

**Comment by lacostej** [comment]
So I found a work-around that reuses some fastlane built in tasks and Jenkins Git plugin environment variables:

````
    changelog = changelog_from_git_commits(
      between: [ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'], ENV['GIT_COMMIT']],
      pretty: "* (%h) [%aN] %s"
    )
    changelog = "Empty changelog..." if changelog.to_s.length == 0
````
