### ISSUE TITLE
Constantly getting the error could not find expected ':' while scanning a simple key at line 110 column 1

### ISSUE THREAD

**Issue by beloso** [fastlane/fastlane#13490]
In my Jenkins environment I am constantly getting the following error. It does not happen every time. And some times it happens in the middle of a lane.

The steps it normally crashes on are `latest_testflight_build_number` and `upload_to_testflight`

I am updating my gems in Jenkins every time a lane runs.

```
bundler: failed to load command: fastlane (/Users/****/.rbenv/versions/2.5.1/bin/fastlane)
Psych::SyntaxError: [!] (<unknown>): could not find expected ':' while scanning a simple key at line 110 column 1
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:402:in `parse'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:350:in `parse'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:263:in `load'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/http-cookie-1.0.3/lib/http/cookie_jar/yaml_saver.rb:24:in `load'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:325:in `block in load'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `open'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `load'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/two_step_client.rb:92:in `load_session_from_file'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/client.rb:391:in `send_shared_login_request'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/tunes/tunes_client.rb:124:in `send_login_request'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/client.rb:667:in `do_login'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/client.rb:363:in `login'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/client.rb:71:in `login'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/pilot/lib/pilot/manager.rb:23:in `login'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/pilot/lib/pilot/manager.rb:16:in `start'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/pilot/lib/pilot/build_manager.rb:13:in `upload'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:79:in `block (2 levels) in parsing_binding'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/****/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/bin/fastlane:20:in `<top (required)>'
  /Users/****/.rbenv/versions/2.5.1/bin/fastlane:23:in `load'
  /Users/****/.rbenv/versions/2.5.1/bin/fastlane:23:in `<top (required)>'
```

**Comment by shtnkgm** [comment]
I have encountered the same issue.

**Comment by shtnkgm** [comment]
This error is probably caused by corruption of the cookie file used by fastlane. To temporarily avoid this problem, delete the cookie file.

just like this
```bash
rm ~/.fastlane/spaceship/[your_email]/cookie
```

I referred to the spaceship reference here.
https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

**Comment by beloso** [comment]
@shtnkgm's solution fixed my issue.

**Comment by dale-french** [comment]
I am having the same issue on Bitrise CI
