### ISSUE TITLE
S3 - gem conflict - plist

### ISSUE THREAD

**Issue by triage** [fastlane/fastlane#1350]
Hey there
getting a gem conflict on plist when trying to upload to S3:

log:
```
[07:49:24]: ----------------
[07:49:24]: --- Step: s3 ---
[07:49:24]: ----------------
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate krausefx-shenzhen-0.14.7, because plist-3.2.0 conflicts with plist (~> 3.1.0) (Gem::ConflictError)
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1408:in `activate'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems.rb:193:in `try_activate'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/actions/s3.rb:29:in `run'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:128:in `chdir'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:125:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/bin/fastlane:38:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/bin/fastlane:150:in `run'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.60.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.0.0/bin/fastlane:22:in `load'`
```
--------

fastfile:
```
lane :appstore do |options|
  #my custom action to download a specific provisioning profile and return its path
  profile = sigh_download_profile({
    password: options[:password],
    app_identifier: "com.mycompany.mycompany",
    provisioning_name: "MyCompany App Store",
  })
  gym(
    scheme: "App Store",
    provisioning_profile_path: profile,
    codesigning_identity: "iPhone Distribution: MyCompany, Inc.",
    xcargs: "APP_VERSION=#{options[:version]} BUILD_VERSION=#{options[:build]}",
    output_name: "MyCompany",
    include_bitcode: true
  )
  s3({
    access_key: ENV["AWS_ACCESS_KEY_ID"],
    secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
    region: ENV["AWS_DEFAULT_REGION"],
    bucket: "bucketname",
    path: "iOS/builds/#{options[:version]}-#{options[:build]}/"
  })
  clean_build_artifacts
end
```

-------
command:
```
fastlane appstore version:$APP_VERSION build:$CIRCLE_BUILD_NUM
```

**Comment by KrauseFx** [comment]
Can you try running `gem cleanup`

**Comment by triage** [comment]
@KrauseFx same issue, unfortunately.

**Comment by triage** [comment]
`sudo gem uninstall plist -v 3.2.0` resolved the conflict.
