### ISSUE TITLE
ITMS Error 3000 can't upload app

### ISSUE THREAD

**Issue by hjanuschka** [fastlane/fastlane#1360]
hello

i am currently having troubles uploading a build to testflight - using `gym`->`pilot`:

```
[22:02:44]: [Transporter Error Output]: ERROR ITMS-3000: "Line 3 column 66: value of attribute "app_platform" is invalid; must be equal to "appletvos", "ios" or "osx" at XPath /package/software_assets"
```

actually in the metadata.xml from the itmsupload - there seems to be the wrong platform.
has anyone a clue where this value comes from?! and how to fix this?

 * already tried  deleting  ` ~/.itmstransporter/` and re-update itmstranspporter, didn't help

metadata.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://apple.com/itunes/importer" version="software5.4">
  <software_assets apple_id="1017625238" app_platform="iphoneos">
    <asset type="bundle">
      <data_file>
        <size>8304181</size>
        <file_name>01719f9d947bb956c1215b6af13e6c89.ipa</file_name>
        <checksum type="md5">0579c5df77eb55958c657c193e2537d9</checksum>
      </data_file>
    </asset>
  </software_assets>
</package>
```

here is the itms output:
```
:02:42]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[22:02:42]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[22:02:42]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[22:02:42]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.3 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[22:02:42]: [Transporter]: DBG-X:   parameter Password = **hidden value**
[22:02:42]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u helmut@januschka.com -p **hidden value** -f /tmp/1017625238.itmsp -t Signiant -k 100000
[22:02:42]: [Transporter]: DBG-X:   parameter Username = helmut@januschka.com
[22:02:42]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[22:02:42]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[22:02:42]: [Transporter]: INFO: id = 20160218220242-893
[22:02:43]: [Transporter]: DBG-X: Apple's web service operation return value:
[22:02:43]: [Transporter]: DBG-X:   parameter SessionId = CIKnDBIQY0g0qt6RQxyQLcFK+rcQ6Q==
[22:02:43]: [Transporter]: DBG-X:   parameter SharedSecret = 1ededee6-762e-4bdb-8d90-cc5721c45e18
[22:02:43]: [Transporter]: DBG-X: Deflated 456 bytes to 400
[22:02:43]: [Transporter]: DBG-X: Using operation named: validateMetadata
[22:02:43]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[22:02:43]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[22:02:43]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[22:02:43]: [Transporter]: DBG-X:   parameter Files = [01719f9d947bb956c1215b6af13e6c89.ipa, metadata.xml]
[22:02:43]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
[22:02:43]: [Transporter]: DBG-X:   parameter MetadataChecksum = f92d1a3e6bd351a9bcbf1b9f9368fed0
[22:02:43]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
[22:02:43]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.3 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[22:02:43]: [Transporter]: DBG-X:   parameter PackageName = 1017625238.itmsp
[22:02:43]: [Transporter]: DBG-X:   parameter PackageSize = 8304612
[22:02:43]: [Transporter]: DBG-X:   parameter Throttle = 100000
[22:02:43]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u helmut@januschka.com -p **hidden value** -f /tmp/1017625238.itmsp -t Signiant -k 100000
[22:02:43]: [Transporter]: DBG-X:   parameter Username = helmut@januschka.com
[22:02:43]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[22:02:43]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[22:02:43]: [Transporter]: INFO: id = 20160218220243-392
[22:02:44]: [Transporter]: DBG-X: Apple's web service operation return value:
[22:02:44]: [Transporter]: DBG-X:   parameter ErrorMessage = ERROR ITMS-3000: "Line 3 column 66: value of attribute "app_platform" is invalid; must be equal to "appletvos", "ios" or "osx" at XPath /package/software_assets
[22:02:44]: [Transporter]: DBG-X:   parameter CPUToken = 21bbea31-bbd7-4029-bd52-1bddf71e473b/1455829364143
[22:02:44]: [Transporter]: DBG-X:   parameter AssetsToDescribe = []
[22:02:44]: [Transporter]: DBG-X:   parameter Errors = [ERROR ITMS-3000: "Line 3 column 66: value of attribute "app_platform" is invalid; must be equal to "appletvos", "ios" or "osx" at XPath /package/software_assets"]
[22:02:44]: [Transporter]: DBG-X:   parameter ErrorCode = 1102
[22:02:44]: [Transporter]: DBG-X:   parameter Success = false
[22:02:44]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml]
[22:02:44]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[22:02:44]: [Transporter Error Output]: ERROR ITMS-3000: "Line 3 column 66: value of attribute "app_platform" is invalid; must be equal to "appletvos", "ios" or "osx" at XPath /package/software_assets"
[22:02:44]: [Transporter]: DBG-X: The error code is: 1102
[22:02:44]: Transporter transfer failed.
[22:02:44]: 
[22:02:44]: ERROR ITMS-3000: "Line 3 column 66: value of attribute "app_platform" is invalid; must be equal to "appletvos", "ios" or "osx" at XPath /package/software_assets"
[22:02:44]: Return status of iTunes Transporter was 1: ERROR ITMS-3000: "Line 3 column 66: value of attribute "app_platform" is invalid; must be equal to "appletvos", "ios" or "osx" at XPath /package/software_assets"
[22:02:44]: ERROR ITMS-3000: "Line 3 column 66: value of attribute "app_platform" is invalid; must be equal to "appletvos", "ios" or "osx" at XPath /package/software_assets"
Return status of iTunes Transporter was 1: ERROR ITMS-3000: "Line 3 column 66: value of attribute "app_platform" is invalid; must be equal to "appletvos", "ios" or "osx" at XPath /package/software_assets"
[22:02:44]: Could not download/upload from iTunes Connect! It's probably related to your password or your internet connection.
[22:02:44]: ---------------------------------------
[22:02:44]: --- Step: Switch to slack_team lane ---
[22:02:44]: ---------------------------------------
[22:02:44]: Cruising over to lane 'slack_team' 🚖
[22:02:44]: -------------------
[22:02:44]: --- Step: slack ---
[22:02:44]: -------------------
[22:02:45]: Successfully sent Slack notification
[22:02:45]: Cruising back to lane 'upload_testflight' 🚘
[22:02:45]: Variable Dump:
[22:02:45]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"testflight", :LATEST_TESTFLIGHT_BUILD_NUMBER=>192, :BUILD_NUMBER=>"193", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/ios/builds/51f33b85/0/FXF/fxf-ios/FiveXFive/Willi.ipa", :DSYM_OUTPUT_PATH=>"/Users/ios/builds/51f33b85/0/FXF/fxf-ios/FiveXFive/Willi.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/ios/Library/Developer/Xcode/Archives/2016-02-18/Willi 2016-02-18 21.59.12.xcarchive"}
[22:02:45]: Error uploading ipa file, more information see above
```

and here is the crashdump from fastlane:

```
+------+----------------------------------+-------------+
|                   fastlane summary                    |
+------+----------------------------------+-------------+
| Step | Action                           | Time (in s) |
+------+----------------------------------+-------------+
| 1    | skip_docs                        | 0           |
| 2    | import_from_git                  | 0           |
| 3    | Switch to build_ipa lane         | 0           |
| 4    | Switch to before_build lane      | 0           |
| 5    | clear_derived_data               | 0           |
| 6    | latest_testflight_build_number   | 34          |
| 7    | increment_build_number           | 0           |
| 8    | cocoapods                        | 136         |
| 9    | unlock_keychain                  | 0           |
| 10   | Switch to certificates lane      | 0           |
| 11   | match                            | 14          |
| 12   | match                            | 12          |
| 13   | gym                              | 149         |
| 14   | Switch to update_metadata lane   | 0           |
| 15   | deliver                          | 51          |
| 16   | Switch to upload_testflight lane | 0           |
| 17   | pilot                            | 15          |
| 18   | Switch to slack_team lane        | 0           |
| 19   | slack                            | 0           |
+------+----------------------------------+-------------+
​
[22:02:45]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '58c8bb6af88ef1e352ca7630b3bb796e'
The crash report has been stored locally '/tmp/sentry_58c8bb6af88ef1e352ca7630b3bb796e.json'
/Library/Ruby/Gems/2.0.0/gems/pilot-1.4.0/lib/pilot/build_manager.rb:29:in `upload': [!] Error uploading ipa file, more information see above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from ../../../../../../../../../var/folders/2h/vvk1jc1n171bxtbqqn45ddsh0000gp/T/fl_clone20160218-68359-1zknr3/fastlane.git/fastlane/Fastfile:138:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:110:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from ../../../../../../../../../var/folders/2h/vvk1jc1n171bxtbqqn45ddsh0000gp/T/fl_clone20160218-68359-1zknr3/fastlane.git/fastlane/Fastfile:146:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

regards

**Comment by hjanuschka** [comment]
duplicate of: https://github.com/fastlane/spaceship/issues/247

**Comment by hjanuschka** [comment]
as downgrading spaceship helped, closing ticket here continuing in fastlane/spaceship#247
