### ISSUE TITLE
/fastlane_core/lib/fastlane_core/fastlane_folder.rb:53:in `join': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#13680]
`bundle exec fastlane supply init --package_name=tools.fastlane.androidapp --json-key="D:\a\_temp\google_play_key.json` on Azure Devops Pipelines:

```
2018-11-14T10:11:42.5208421Z [10:11:42]: [36m$ bundle exec fastlane supply init --package_name=tools.fastlane.androidapp --json-key="D:\a\_temp\google_play_key.json"[0m
2018-11-14T10:11:45.2461679Z [10:11:45]: Γû╕ [35m[10:11:45]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
2018-11-14T10:11:45.2706573Z [10:11:45]: Γû╕ [35m[10:11:45]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
2018-11-14T10:11:45.2841757Z [10:11:45]: Γû╕ [35mC:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:53:in `join': no implicit conversion of nil into String (TypeError)[0m
2018-11-14T10:11:45.2848691Z [10:11:45]: Γû╕ [35mfrom C:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:53:in `fastfile_path'[0m
2018-11-14T10:11:45.2849085Z [10:11:45]: Γû╕ [35mfrom C:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:167:in `available_lanes'[0m
2018-11-14T10:11:45.2849364Z [10:11:45]: Γû╕ [35mfrom C:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:74:in `take_off'[0m
2018-11-14T10:11:45.2850115Z [10:11:45]: Γû╕ [35mfrom C:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'[0m
2018-11-14T10:11:45.2850592Z [10:11:45]: Γû╕ [35mfrom C:/hostedtoolcache/windows/Ruby/2.5.0/x64/bin/fastlane:23:in `load'[0m
2018-11-14T10:11:45.2850907Z [10:11:45]: Γû╕ [35mfrom C:/hostedtoolcache/windows/Ruby/2.5.0/x64/bin/fastlane:23:in `<main>'[0m
2018-11-14T10:11:45.3041008Z +-----------------------------+-------------------------------------------------------------------------------+
2018-11-14T10:11:45.3041164Z |                                                [33mLane Context[0m                                                 |
2018-11-14T10:11:45.3041281Z +-----------------------------+-------------------------------------------------------------------------------+
2018-11-14T10:11:45.3041367Z | DEFAULT_PLATFORM            | android                                                                       |
2018-11-14T10:11:45.3041476Z | PLATFORM_NAME               | android                                                                       |
2018-11-14T10:11:45.3041560Z | LANE_NAME                   | android all                                                                   |
2018-11-14T10:11:45.3041667Z | GRADLE_BUILD_TYPE           | Release                                                                       |
2018-11-14T10:11:45.3041762Z | GRADLE_ALL_APK_OUTPUT_PATHS | ["D:/a/1/s/android/androidapp/app/build/outputs/apk/release/app-release.apk"] |
2018-11-14T10:11:45.3042054Z | GRADLE_ALL_AAB_OUTPUT_PATHS | []                                                                            |
2018-11-14T10:11:45.3042142Z | GRADLE_APK_OUTPUT_PATH      | D:/a/1/s/android/androidapp/app/build/outputs/apk/release/app-release.apk     |
2018-11-14T10:11:45.3042252Z +-----------------------------+-------------------------------------------------------------------------------+
2018-11-14T10:11:45.3046277Z [10:11:45]: [31mExit status of command 'bundle exec fastlane supply init --package_name=tools.fastlane.androidapp --json-key="D:\a\_temp\google_play_key.json"' was 1 instead of 0.
2018-11-14T10:11:45.3046429Z [10:11:45]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
2018-11-14T10:11:45.3046542Z [10:11:45]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
2018-11-14T10:11:45.3046669Z C:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:53:in `join': no implicit conversion of nil into String (TypeError)
2018-11-14T10:11:45.3046765Z 	from C:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:53:in `fastfile_path'
2018-11-14T10:11:45.3046881Z 	from C:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:167:in `available_lanes'
2018-11-14T10:11:45.3046970Z 	from C:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:74:in `take_off'
2018-11-14T10:11:45.3047206Z 	from C:/hostedtoolcache/windows/Ruby/2.5.0/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'
2018-11-14T10:11:45.3047287Z 	from C:/hostedtoolcache/windows/Ruby/2.5.0/x64/bin/fastlane:23:in `load'
2018-11-14T10:11:45.3047377Z 	from C:/hostedtoolcache/windows/Ruby/2.5.0/x64/bin/fastlane:23:in `<main>'
```

**Comment by janpio** [comment]
See #12789

**Comment by janpio** [comment]
Another one:

```
...
2018-11-15T22:16:39.7376222Z [22:16:39]: [31mExit status of command 'bundle exec fastlane screengrab init' was 1 instead of 0.
2018-11-15T22:16:39.7376470Z bundler: failed to load command: fastlane (/opt/hostedtoolcache/Ruby/2.5.1/x64/bin/fastlane)
2018-11-15T22:16:39.7376530Z TypeError: no implicit conversion of nil into String
2018-11-15T22:16:39.7377217Z   /opt/hostedtoolcache/Ruby/2.5.1/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:53:in `join'
2018-11-15T22:16:39.7377536Z   /opt/hostedtoolcache/Ruby/2.5.1/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:53:in `fastfile_path'
2018-11-15T22:16:39.7378025Z   /opt/hostedtoolcache/Ruby/2.5.1/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:167:in `available_lanes'
2018-11-15T22:16:39.7378348Z   /opt/hostedtoolcache/Ruby/2.5.1/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:74:in `take_off'
2018-11-15T22:16:39.7378623Z   /opt/hostedtoolcache/Ruby/2.5.1/x64/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'
2018-11-15T22:16:39.7379019Z   /opt/hostedtoolcache/Ruby/2.5.1/x64/bin/fastlane:23:in `load'
2018-11-15T22:16:39.7379426Z   /opt/hostedtoolcache/Ruby/2.5.1/x64/bin/fastlane:23:in `<top (required)>'
2018-11-15T22:16:39.7379602Z [0m
2018-11-15T22:16:39.7428166Z 
...
```
