### ISSUE TITLE
app_identifier is nil on fastlane init

### ISSUE THREAD

**Issue by bitops** [fastlane/fastlane#1372]
I am trying to set up fastlane on my project and it's blowing up.

## Versions
fastlane - `1.61.0`
OS X - Yosemite, version `10.10.5`
ruby (via rvm) - `ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]`

## Steps
* installed fastlane via `sudo gem install fastlane`
* cd'd to my app's root directory and ran `fastlane init` with no additional parameters.
* fastlane prompts me for my userid and password. it detects that my app is not in iTunes Connect yet so it offers to create app identifier for me. When I say `'y'` to accept, I receive a stack trace.

## Fastlane Output
```
[12:32:18]: Detected iOS/Mac project in current directory...
[12:32:18]: This setup will help you get up and running in no time.
[12:32:18]: fastlane will check what tools you're already using and set up
[12:32:18]: the tool automatically for you. Have fun! 
[12:32:18]: Created new folder './fastlane'.
[12:32:18]: xcrun xcodebuild -list -workspace './FooApp.xcworkspace'
Your Apple ID (e.g. fastlane@krausefx.com): my-id-here
[12:32:29]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[12:32:29]: Starting login with user 'my-id-here'

+----------------+------------------------------------------------------------+
|                               Detected Values                               |
+----------------+------------------------------------------------------------+
| Apple ID       | my-id-here                                        |
| App Name       | my-app-name-here                                                       |
| App Identifier |                                                            |
| Workspace      | /Users/sebastian/src/foo/FooApp.xcworkspace |
+----------------+------------------------------------------------------------+

[12:32:36]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[12:32:36]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
Please confirm the above values (y/n)
y
[12:32:39]: Error occurred with the setup program! Reverting changes now!
[12:32:39]: Deleting the 'fastlane' folder
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
```

## Stack trace
```
/Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.61.0/lib/fastlane/setup/setup_ios.rb:157:in `gsub!': [!] no implicit conversion of nil into String (TypeError)
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.61.0/lib/fastlane/setup/setup_ios.rb:157:in `generate_appfile'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.61.0/lib/fastlane/setup/setup_ios.rb:50:in `default_setup'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.61.0/lib/fastlane/setup/setup_ios.rb:33:in `run'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.61.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.61.0/bin/fastlane:51:in `block (2 levels) in run'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.61.0/bin/fastlane:150:in `run'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.61.0/bin/fastlane:156:in `<top (required)>'
	from /Users/sebastian/.rvm/rubies/ruby-2.1.1/bin/fastlane:23:in `load'
	from /Users/sebastian/.rvm/rubies/ruby-2.1.1/bin/fastlane:23:in `<main>'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sebastian/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

I opened up the ruby code and put in some debug statements via the logger. What it tells me is that `self.app_identifier` is ending up `nil`. Let me know if I can provide any additional info. Thanks! :smile:

**Comment by ohwutup** [comment]
Hey @bitops, it looks like for some reason there is likely not a `PRODUCT_BUNDLE_IDENTIFIER` key in your build settings. Instead of hitting `y` when fastlane asks `Please confirm the above values`, answer `n` and then it will ask for the information to be entered manually! Let us know if you have any more issues! :+1:
