### ISSUE TITLE
Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by maciekish** [fastlane/fastlane#1373]
I get the error below when i try to `fastlane init` in a new Xcode iOS project. I'm using an admin account to log in, and the account is able to log in to iTunes Connect no problem and see all the apps. The error report number is `0ebf5dda56a980dc123529249ffae030`.

```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/client.rb:268:in `parse_response': [!] {"creationTimestamp"=>"2016-02-19T20:43:28Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestUrl"=>"https://developerservices2.apple.com:443//services/QH65B2/listTeams.action", "responseId"=>"d2061b86-****-****-****-901af1cfc6f5"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/portal/portal_client.rb:63:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/portal/portal_client.rb:79:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/setup/setup_ios.rb:169:in `detect_if_app_is_available'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/setup/setup_ios.rb:29:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by vpolouchkine** [comment]
Can give the latest version a whirl?

**Comment by maciekish** [comment]
It still throws an error but then asks for my bundle id and eventually allows me to complete the init.

**Comment by maciekish** [comment]
Same issue with `sigh repair` and i cannot get around it in any way :(

**Comment by vpolouchkine** [comment]
@maciekish Are you still hitting this?

**Comment by edwardmp** [comment]
Encountered same issue today. Occurred with a specially created account for fastlane. I noticed that when going to the developer site I needed to accept some terms for that account. After this was done the issue was still there. What I still needed to do is invite that new account to my development team. Issue was solved then.

> .rvm/gems/ruby-2.2.1@global/gems/spaceship-0.25.1/lib/spaceship/client.rb:427:in `parse_response': [!] {"creationTimestamp"=>"2016-04-17T22:08:57Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestUrl"=>"https://developerservices2.apple.com:443/services/QH65B2/listTeams.action", "responseId"=>"33b00bc8-ee5b-4037-b327-af116c534a22"}

**Comment by vpolouchkine** [comment]
@edwardmp Thanks for the report. Looks like everyone is up and running.
