### ISSUE TITLE
The login credentials for 'apple id' seem to be wrong

### ISSUE THREAD

**Issue by Darkreaper101** [fastlane/fastlane#1377]
Good day all,

I'm struggling with this issue it seems that the credentials manager has some issues because some passwords doesn't want to go through.

I've removed all of my deliver. passwords in the keychain and it's still giving me an issue with certain passwords.

It's almost as if certain characters in the password messes around with the credentials manager.

If someone has some information as to why some passwords keeps on failing through the use of fastlane that would be great.

I am able to login to the account manually through the browser with the same credentials that I provide fastlane with.

See stack trace below:

```Shell
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:63:in `login': [!] Invalid User Credentials (Spaceship::Client::InvalidUserCredentialsError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.3.0/lib/cert/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.3.0/lib/cert/runner.rb:6:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/actions/cert.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:23:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:110:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from Fastfile:93:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.6/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.61.0/bin/fastlane:156:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

Regards

**Comment by vpolouchkine** [comment]
Can you give the latest version a whirl?

**Comment by Darkreaper101** [comment]
Hi @vpolouchkine,

Thanks will give v1.63 a go and let everyone know if the issue has been resolved. :smile:

**Comment by lacostej** [comment]
@Darkreaper101 @vpolouchkine if your problem isn't fixed, note that the security gem has a known issue with non ASCII passwords. https://github.com/mattt/security/pull/3 Could it be that ?

**Comment by vpolouchkine** [comment]
@Darkreaper101 Are you still running into this?

**Comment by Darkreaper101** [comment]
@vpolouchkine @lacostej It seems the issue has been resolved as far as I can tell, haven't used the specified account in quite a while, but if this issue does come up again I'll open up the issue.

**Comment by TKBurner** [comment]
@Darkreaper101 Awesome! Glad to hear you are up and running. Please let us know if you see this issue again! Hope you have a great week :+1:
