### ISSUE TITLE
FastlaneSwiftRunner[setGithubRelease]- Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by jprickett821** [fastlane/fastlane#13852]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to utilize `setGithubRelease` via Fastlane Swift and I am receiving a very strange error. Everything works successfully (tag created & archive uploaded), then the final response from the GitHub API seems to be causing a crash. I verified that the issue only occurs using the Swift version of Fastlane. I've been attempting to resolve the issue on my own but any help would be greatly appreciated! 

Fastfile method:
```
    private func createReleaseTag(with tag: String, 
                                  asset paths: String,
                                  apiKey key: String,
                                  commit sha: String) {
        setGithubRelease(repositoryName: "my/ios-repo",
                         apiToken: key,
                         tagName: tag,
                         name: tag,
                         commitish: sha,
                         description: tag,
                         uploadAssets: [paths])
    }
```

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>$ bundle exec fastlane tagArchive ... --verbose
[⠙] 🚀 
[✔] 🚀
DEBUG [2018-12-07 10:28:07.37]: Checking if there are any plugins that should be loaded...
...
INFO [2018-12-07 10:28:07.51]: loading manifest: /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/swift/upgrade_manifest.json
DEBUG [2018-12-07 10:28:07.56]: No missing groups found, so we don't need to worry about adding new groups
DEBUG [2018-12-07 10:28:07.56]: Fastlane.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.33/0.9.33
DEBUG [2018-12-07 10:28:07.56]: DeliverfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.4/0.9.4
DEBUG [2018-12-07 10:28:07.56]: GymfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.56]: MatchfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.56]: PrecheckfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2018-12-07 10:28:07.56]: ScanfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.6/0.9.6
DEBUG [2018-12-07 10:28:07.56]: ScreengrabfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.1/0.9.1
DEBUG [2018-12-07 10:28:07.56]: SnapshotfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.4/0.9.4
DEBUG [2018-12-07 10:28:07.56]: LaneFileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.56]: ControlCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.56]: RubyCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.56]: RubyCommandable.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.56]: Runner.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.56]: SocketClient.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.57]: SocketClientDelegateProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.57]: SocketResponse.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.57]: ArgumentProcessor.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.57]: main.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.57]: RunnerArgument.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2018-12-07 10:28:07.57]: Checking for new user-provided tool configuration files
INFO [2018-12-07 10:28:07.58]: FastlaneSwiftRunner project is up-to-date
DEBUG [2018-12-07 10:28:07.58]: Waiting for 5 seconds for a connection from FastlaneRunner
INFO [2018-12-07 10:28:07.83]: $ ./fastlane/FastlaneRunner lane tagArchive ... logMode verbose swiftServerPort 2000 > /dev/null
INFO [2018-12-07 10:28:07.88]: --------------------------------
INFO [2018-12-07 10:28:07.88]: --- Step: set_github_release ---
INFO [2018-12-07 10:28:07.88]: --------------------------------
WARN [2018-12-07 10:28:07.88]: Creating release of repo/ios-repo on tag "TEST" with name "TEST".
WARN [2018-12-07 10:28:07.88]: Will also upload assets ["build/APP-NAME.txt"].
DEBUG [2018-12-07 10:28:07.88]: POST : <REDACTED>
DEBUG [2018-12-07 10:28:08.72]: Response:
DEBUG [2018-12-07 10:28:08.72]: <REDACTED>
DEBUG [2018-12-07 10:28:08.72]: ---
INFO [2018-12-07 10:28:08.72]: Successfully created release at tag <REDACTED> on GitHub
WARN [2018-12-07 10:28:08.72]: See release at <REDACTED>
WARN [2018-12-07 10:28:08.72]: Uploading APP-NAME.txt
DEBUG [2018-12-07 10:28:08.73]: POST : <REDACTED>
DEBUG [2018-12-07 10:28:09.34]: Response:
DEBUG [2018-12-07 10:28:09.34]: <REDACTED>
DEBUG [2018-12-07 10:28:09.34]: ---
INFO [2018-12-07 10:28:09.34]: Successfully uploaded APP-NAME.txt.
DEBUG [2018-12-07 10:28:09.34]: GET : <REDACTED>
DEBUG [2018-12-07 10:28:09.66]: Response:
DEBUG [2018-12-07 10:28:09.66]: <REDACTED>
DEBUG [2018-12-07 10:28:09.66]: ---
INFO [2018-12-07 10:28:09.66]: Successfully uploaded assets ["build/APP-NAME.txt"] to release <REDACTED>
DEBUG [2018-12-07 10:28:09.66]: sending <REDACTED>
INFO [2018-12-07 10:28:09.66]: ▸ Fatal error: Unexpectedly found nil while unwrapping an Optional value
#<Thread:0x00007fc253203998@/Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/swift_lane_manager.rb:228 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/swift_lane_manager.rb:231:in `block in start_socket_thread'
	8: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	7: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
	6: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
	5: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
	4: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
	3: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:81:in `parse_and_execute_command'
	2: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/command_parser.rb:12:in `parse'
	1: from /Users/USERNAME/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/Users/USERNAME/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)
WARN [2018-12-07 10:28:09.66]: Lane Context:
INFO [2018-12-07 10:28:09.67]: <REDACTED>
ERROR [2018-12-07 10:28:09.67]: 765: unexpected token at ''
INFO [2018-12-07 10:28:09.67]: ▸ sh: line 1: 15722 Illegal instruction: 4  ./fastlane/FastlaneRunner lane tagArchive ... logMode verbose swiftServerPort 2000 > /dev/null
#<Thread:0x00007fc252a2f6b8@/Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/swift_lane_manager.rb:104 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/swift_lane_manager.rb:105:in `block in cruise_swift_lane_in_thread'
	3: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	2: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	1: from /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane tagArchive ... logMode verbose swiftServerPort 2000 > /dev/null' was 132 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Fatal error: Unexpectedly found nil while unwrapping an Optional value
sh: line 1: 15722 Illegal instruction: 4  ./fastlane/FastlaneRunner lane tagArchive ... logMode verbose swiftServerPort 2000 > /dev/null

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | git_branch         | 0           |
| 2    | set_github_release | 1           |
+------+--------------------+-------------+

ERROR [2018-12-07 10:28:09.67]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: 765: unexpected token at ''

URL: https://api.github.com/search/issues?q=765%3A%20unexpected%20token%20at%20%27%27+repo:fastlane/fastlane
➡️  784/776: unexpected token at 'Bad Request' (Faraday::ParsingError)
    https://github.com/fastlane/fastlane/issues/13666 [open] 54 💬
    3 days ago

➡️  Provisioning Profile Delete Error Token
    https://github.com/fastlane/fastlane/issues/13256 [closed] 5 💬
    5 weeks ago

➡️  [spaceship] Remove ensure_csrf in 'delete_provisioning_profile!' for more relability
    https://github.com/fastlane/fastlane/pull/13258 [closed] 8 💬
    5 weeks ago

and 9 more at: https://github.com/fastlane/fastlane/search?q=765%3A%20unexpected%20token%20at%20%27%27&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

JSON::ParserError: [!] 765: unexpected token at ''
  /Users/USERNAME/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse'
  /Users/USERNAME/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse'
  /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/command_parser.rb:12:in `parse'
  /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:81:in `parse_and_execute_command'
  /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
  /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
  /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
  /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
  /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
  /Users/USERNAME/.rvm/gems/ruby-2.5.3/bundler/gems/fastlane-500331774f5b/fastlane/lib/fastlane/swift_lane_manager.rb:231:in `block in start_socket_thread'</pre>
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.109.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.17.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| openssl                   | 2.1.2        |
| date                      | 1.0.0        |
| fileutils                 | 1.1.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.3        |
</details>

*generated on:* **2018-12-07**
</details>

**Comment by jprickett821** [comment]
Hi @fastlane-bot, I do not believe it is a code signing issue unfortunately! The project builds and archives successfully, but upon uploading to GitHub it looks as though a response is coming in from the GitHub API that FastlaneSwiftRunner can't convert from a Ruby dictionary to a Swift dictionary possibly? That's the only thing that would explain it working in Ruby, but not in Swift?
