### ISSUE TITLE
Unable to distribute build via fastlane

### ISSUE THREAD

**Issue by qasimsqm** [fastlane/fastlane#13863]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am unable to share adhco, development and even apptore build via fastlane. 

##### Complete output when running fastlane, including the stack trace and command used
```
Nadeems-MacBook-Pro:Boilerplate syedqasim$ fastlane adhoc
[✔] 🚀 
[18:40:28]: fastlane detected a Gemfile in the current directory
[18:40:28]: however it seems like you don't use `bundle exec`
[18:40:28]: to launch fastlane faster, please use
[18:40:28]: 
[18:40:28]: $ bundle exec fastlane adhoc
[18:40:28]: 
[18:40:28]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:40:28]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[18:40:29]: loading manifest: /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/swift/upgrade_manifest.json
+-----------+-------+
|   Lane Context    |
+-----------+-------+
| LANE_NAME | adhoc |
+-----------+-------+
[18:40:29]: [Xcodeproj] Unable to open `/Users/syedqasim/Documents/Boilerplate/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj` because it doesn't exist.
[18:40:29]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
[18:40:30]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.7.0/lib/xcodeproj/project.rb:105:in `open': [!] [Xcodeproj] Unable to open `/Users/syedqasim/Documents/Boilerplate/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj` because it doesn't exist. (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/swift_runner_upgrader.rb:38:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/swift_lane_manager.rb:263:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/swift_lane_manager.rb:263:in `ensure_runner_up_to_date_fastlane!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/swift_lane_manager.rb:34:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.109.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by RishabhTayal** [comment]
@qasimsqm Can you try running `bundle exec fastlane adhoc` and see if it fixes the issue?

**Comment by janpio** [comment]
Does the file `/Users/syedqasim/Documents/Boilerplate/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj` exist?

I can't check your lane, as you didn't include your environment information as the issue template suggests.
