### ISSUE TITLE
nodename nor servname provided, or not known (SocketError)

### ISSUE THREAD

**Issue by huos3203** [fastlane/fastlane#13922]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

i want use fast lane.swift ,but 
```
FastlaneSwiftRunner project is up-to-date
#<Thread:0x00007faf0655ce88@/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/fastlane/lib/fastlane/swift_lane_manager.rb:228 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/fastlane/lib/fastlane/swift_lane_manager.rb:231:in `block in start_socket_thread'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/fastlane/lib/fastlane/server/socket_server.rb:140:in `listen'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/fastlane/lib/fastlane/server/socket_server.rb:140:in `open'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/fastlane/lib/fastlane/server/socket_server.rb:140:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
```
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | /usr/local/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by huos3203** [comment]
> It seems like you have not included the output of `fastlane env`
> 
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | /usr/local/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
	func customLane() {
	desc("Description of what the lane does")
		// add actions here: https://docs.fastlane.tools/actions
	}
}

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.112.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| json                      | 2.1.0        |
| bundler                   | 1.16.6       |
| openssl                   | 2.1.2        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>


*generated on:* **2018-12-27**
</details>

**Comment by huos3203** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
> 
> Please make sure to update to the latest `fastlane` version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

update lastest fastlane，run **fastlane customLane**：
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.115.0/fastlane/lib/fastlane/server/socket_server.rb:140:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
