### ISSUE TITLE
Using App Store VSTS Extension fails after uploading to TestFlight successfully

### ISSUE THREAD

**Issue by jmichas** [fastlane/fastlane#13937]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm using the VSTS extension in a azure devops pipeline.
My build gets uploaded to apple fine but seems to fail at the point where it is submitting the build for TestFlight review, I'm not sure why.

Here is the relevant part of my log. The only errors previous to this log snippet are a warning for SDK version but it still succeeds. I can manually go in to submit the build for review but I'd love this step to be automated.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
2018-12-16T20:53:45.2332430Z [20:53:44]: Although errors occurred during execution of iTMSTransporter, it returned success status.
2018-12-16T20:53:45.2332950Z [20:53:44]: --------------------------------------------------------------------
2018-12-16T20:53:45.2333570Z [20:53:44]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
2018-12-16T20:53:45.2334090Z [20:53:44]: --------------------------------------------------------------------
2018-12-16T20:53:45.2334190Z [20:53:44]: Successfully uploaded the new binary to App Store Connect
2018-12-16T20:53:45.2334260Z [20:53:44]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
2018-12-16T20:53:45.8087050Z [20:53:45]: Started watching build 1.0.5 - 1.0.5.2 but expected  1.0.5 -  1.0.5.2
2018-12-16T20:53:46.2340620Z [20:53:46]: Waiting for App Store Connect to finish processing the new build (1.0.5 - 1.0.5.2)
2018-12-16T20:54:16.8706650Z [20:54:16]: Waiting for App Store Connect to finish processing the new build (1.0.5 - 1.0.5.2)
2018-12-16T20:54:47.2806810Z [20:54:47]: Waiting for App Store Connect to finish processing the new build (1.0.5 - 1.0.5.2)
2018-12-16T20:55:17.8094860Z [20:55:17]: Waiting for App Store Connect to finish processing the new build (1.0.5 - 1.0.5.2)
2018-12-16T20:55:48.6101730Z [20:55:48]: Waiting for App Store Connect to finish processing the new build (1.0.5 - 1.0.5.2)
2018-12-16T20:56:19.1351050Z [20:56:19]: Waiting for App Store Connect to finish processing the new build (1.0.5 - 1.0.5.2)
2018-12-16T20:56:49.5408490Z [20:56:49]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
2018-12-16T20:57:19.9077280Z [20:57:19]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
2018-12-16T20:57:50.4408140Z [20:57:50]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
2018-12-16T20:58:20.9632950Z [20:58:20]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
2018-12-16T20:58:51.5603170Z [20:58:51]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
2018-12-16T20:59:22.0747440Z [20:59:22]: Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)
2018-12-16T20:59:52.4862260Z [20:59:52]: Successfully finished processing the build 1.0.5 - 1.0.5.2
2018-12-16T20:59:52.4863210Z [20:59:52]: Uploaded app  1.0.5 -  1.0.5.2, but received build 1.0.5 - 1.0.5.2. If you want to wait for uploaded build to be finished processing, use the `wait_for_uploaded_build` option
2018-12-16T20:59:56.4652020Z [20:59:56]: Successfully set the changelog for build
2018-12-16T20:59:56.4653510Z [20:59:56]: Distributing new build to testers: 1.0.5 - 1.0.5.2
2018-12-16T20:59:56.6826460Z 
2018-12-16T20:59:56.6826930Z Looking for related GitHub issues on fastlane/fastlane...
2018-12-16T20:59:56.6827450Z 
2018-12-16T20:59:56.7831790Z /Users/vsts/.gem-cache/gems/fastlane-2.111.0/spaceship/lib/spaceship/test_flight/client.rb:330:in `handle_response': [!] <!DOCTYPE html><html lang="en"> (Spaceship::UnexpectedResponse)
2018-12-16T20:59:56.7831970Z <head>
2018-12-16T20:59:56.7832110Z <title></title>
2018-12-16T20:59:56.7832180Z <link rel="stylesheet" href="/styles/main.css">
2018-12-16T20:59:56.7833040Z <style type='text/css'>
2018-12-16T20:59:56.7833200Z     /*include ../../dist/styles/main.css*/
2018-12-16T20:59:56.7833300Z </style>
2018-12-16T20:59:56.7833350Z </head>
2018-12-16T20:59:56.7833570Z 
2018-12-16T20:59:56.7833650Z <body><div id="wrapper" class="j42">
2018-12-16T20:59:56.7833730Z <h2>Not Found</h2></div>
2018-12-16T20:59:56.7833880Z 
2018-12-16T20:59:56.7833950Z <div class="footer">
2018-12-16T20:59:56.7834510Z     <p>Copyright &copy; <span id='year'>2015 Apple Inc. All rights reserved.</p>
2018-12-16T20:59:56.7835210Z     <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
2018-12-16T20:59:56.7835340Z </div>
2018-12-16T20:59:56.7835370Z 
2018-12-16T20:59:56.7835570Z 
2018-12-16T20:59:56.7836070Z <script type='text/javascript'>(function() {
2018-12-16T20:59:56.7836150Z     var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
2018-12-16T20:59:56.7836790Z     document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
2018-12-16T20:59:56.7837280Z     var yearEl = document.getElementById('year');
2018-12-16T20:59:56.7837440Z     if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
2018-12-16T20:59:56.7837510Z })();
2018-12-16T20:59:56.7837850Z </script>
2018-12-16T20:59:56.7837970Z 
2018-12-16T20:59:56.7838030Z </body>
2018-12-16T20:59:56.7838080Z </html>
2018-12-16T20:59:56.7838740Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review'
2018-12-16T20:59:56.7839340Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/spaceship/lib/spaceship/test_flight/build.rb:217:in `submit_for_testflight_review!'
2018-12-16T20:59:56.7839900Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/pilot/lib/pilot/build_manager.rb:183:in `distribute_build'
2018-12-16T20:59:56.7840550Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/pilot/lib/pilot/build_manager.rb:108:in `distribute'
2018-12-16T20:59:56.7841110Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/pilot/lib/pilot/build_manager.rb:61:in `upload'
2018-12-16T20:59:56.7841760Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
2018-12-16T20:59:56.7842320Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2018-12-16T20:59:56.7842930Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2018-12-16T20:59:56.7843500Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2018-12-16T20:59:56.7844050Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2018-12-16T20:59:56.7844690Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2018-12-16T20:59:56.7845240Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
2018-12-16T20:59:56.7845880Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
2018-12-16T20:59:56.7846420Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
2018-12-16T20:59:56.7846980Z 	from /Users/vsts/.gem-cache/gems/fastlane-2.111.0/bin/fastlane:23:in `<top (required)>'
2018-12-16T20:59:56.7847580Z 	from /usr/local/lib/ruby/gems/2.5.0/bin/fastlane:23:in `load'
2018-12-16T20:59:56.7848100Z 	from /usr/local/lib/ruby/gems/2.5.0/bin/fastlane:23:in `<main>'
2018-12-16T20:59:56.8136380Z ##[error]Error: fastlane failed with return code: 1
</pre>
</details>

### Environment

Not sure how to get the environment from the azure pipeline.
<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
Apple changed something, see more information here: https://github.com/fastlane/fastlane/issues/13903 A fix is in place and will be included in the next release.
