### ISSUE TITLE
Test execution failed. Exit status: 1

### ISSUE THREAD

**Issue by p-nicolaou** [fastlane/fastlane#14001]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I can't have scan finish successfully 

#### Question Description
I am trying to setup Fastlane on a new project, new machine but for some reason it fails every time. I can see sample test passing but after that point, I am getting exit status 1. Please check logs below. 

```
DEBUG [2018-12-28 21:09:59.44]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/pnikolaou/Documents/repositories/xxxxx-ios/fastlane/Appfile'
- app_identifier: 'xxxxx'
- apple_id: 'xxxxx'
- itc_team_id: 'xxxxx'
- team_id: 'xxxxx'
-------
INFO [2018-12-28 21:09:59.68]: ------------------------------
INFO [2018-12-28 21:09:59.68]: --- Step: default_platform ---
INFO [2018-12-28 21:09:59.68]: ------------------------------
INFO [2018-12-28 21:09:59.68]: Driving the lane 'ios test' 🚀
INFO [2018-12-28 21:09:59.68]: ------------------
INFO [2018-12-28 21:09:59.68]: --- Step: scan ---
INFO [2018-12-28 21:09:59.68]: ------------------
INFO [2018-12-28 21:09:59.83]: $ xcodebuild -showBuildSettings -workspace xxxxx.xcworkspace -scheme xxxxx-Stage
WARN [2018-12-28 21:10:02.84]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
DEBUG [2018-12-28 21:10:05.50]: Fetching available simulator devices
INFO [2018-12-28 21:10:05.91]: Found simulator "iPhone 5s (12.1)"
DEBUG [2018-12-28 21:10:05.91]: Detected derived data path '/Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn'
INFO [2018-12-28 21:10:06.31]: $ xcodebuild -showBuildSettings -workspace xxxxx.xcworkspace -scheme xxxxx-Stage
DEBUG [2018-12-28 21:10:08.67]: Fetching available simulator devices
INFO [2018-12-28 21:10:09.08]: Found simulator "iPhone 5s (12.1)"

+----------------------------+--------------------------------------+
|                     Summary for scan 2.112.0                      |
+----------------------------+--------------------------------------+
| workspace                  | xxxxx.xcworkspace               |
| scheme                     | xxxxx-Stage                     |
| derived_data_path          | /Users/pnikolaou/Library/Developer/  |
|                            | Xcode/DerivedData/xxxxx-gbuqxv  |
|                            | qyqxosnrcnfbiwewejuojn               |
| skip_detect_devices        | false                                |
| reinstall_app              | false                                |
| app_identifier             | xxxxx                                |
| clean                      | false                                |
| open_report                | false                                |
| output_directory           | ./fastlane/test_output               |
| output_types               | html,junit                           |
| buildlog_path              | ~/Library/Logs/scan                  |
| include_simulator_logs     | false                                |
| should_zip_build_products  | false                                |
| result_bundle              | false                                |
| use_clang_report_name      | false                                |
| disable_concurrent_testing | false                                |
| skip_build                 | false                                |
| skip_slack                 | false                                |
| slack_only_on_failure      | false                                |
| fail_build                 | true                                 |
| xcode_path                 | /Applications/Xcode.app              |
+----------------------------+--------------------------------------+

INFO [2018-12-28 21:10:09.11]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace xxxxx.xcworkspace -scheme xxxxx-Stage -destination 'platform=iOS Simulator,id=0BEDD1BE-5A4C-4CF7-A73B-CA51888C08E6' -derivedDataPath '/Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn' build test | tee '/Users/pnikolaou/Library/Logs/scan/xxxxx-xxxxx-Stage.log' | xcpretty  --report html --output '/Users/pnikolaou/Documents/repositories/xxxxx-ios/fastlane/test_output/report.html' --report junit --output '/Users/pnikolaou/Documents/repositories/xxxxx-ios/fastlane/test_output/report.junit' --report junit --output '/var/folders/tg/ts742gm96bb4j3hm1z6299c80000gn/T/junit_report20181228-26044-ztj9pi' 
INFO [2018-12-28 21:10:09.11]: ▸ Loading...
INFO [2018-12-28 21:10:09.13]: ▸ tee: /Users/pnikolaou/Library/Logs/scan/xxxxx-xxxxx-Stage.log: Permission denied
INFO [2018-12-28 21:10:14.60]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.60]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.82]: ▸ Processing ResourceBundle-TOCropViewControllerBundle-Info.plist
INFO [2018-12-28 21:10:14.83]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.83]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.84]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.85]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.89]: ▸ Generating 'Core.framework.dSYM'
INFO [2018-12-28 21:10:14.90]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.92]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.92]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.92]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.93]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.93]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.94]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.95]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.95]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.95]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.95]: ▸ Copying /Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Build/Products/Debug-iphonesimulator/CropViewController/TOCropViewControllerBundle.bundle
INFO [2018-12-28 21:10:14.96]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:14.96]: ▸ Generating 'UI.framework.dSYM'
INFO [2018-12-28 21:10:15.05]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:15.08]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:15.08]: ▸ Generating 'Inner.framework.dSYM'
INFO [2018-12-28 21:10:15.31]: ▸ Linking xxxxx
INFO [2018-12-28 21:10:16.94]: ▸ Processing xxxxx Test-Info.plist
INFO [2018-12-28 21:10:16.96]: ▸ Running script 'Fabric'
INFO [2018-12-28 21:10:17.16]: ▸ Copying /Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Build/Products/Debug-iphonesimulator/xxxxx.framework
INFO [2018-12-28 21:10:17.16]: ▸ Copying /Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Build/Products/Debug-iphonesimulator/UI.framework
INFO [2018-12-28 21:10:17.16]: ▸ Copying /Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Build/Products/Debug-iphonesimulator/Core.framework
INFO [2018-12-28 21:10:17.29]: ▸ Running script 'Run Script'
INFO [2018-12-28 21:10:17.68]: ▸ Generating 'xxxxx.app.dSYM'
INFO [2018-12-28 21:10:20.60]: ▸ Build Succeeded
INFO [2018-12-28 21:10:23.38]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:23.39]: ▸ Linking xxxxx
INFO [2018-12-28 21:10:24.70]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:24.72]: ▸ Running script 'Fabric'
INFO [2018-12-28 21:10:24.86]: ▸ Running script 'Run Script'
INFO [2018-12-28 21:10:25.06]: ▸ Generating 'xxxxx.app.dSYM'
INFO [2018-12-28 21:10:28.04]: ▸ Processing Info.plist
INFO [2018-12-28 21:10:28.04]: ▸ Linking xxxxx
INFO [2018-12-28 21:10:29.62]: ▸ 2018-12-28 21:10:29.625 xcodebuild[26100:265608]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
INFO [2018-12-28 21:10:29.62]: ▸ /Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Logs/Test/Run-xxxxx-Stage-2018.12.28_21-10-11-+0200.xcresult/2_Test/Diagnostics/xxxxx-C7754B45-4A9C-4DDD-BD13-ED1592018578/xxxxx-3D0783BA-CBBA-49AB-AED7-824458A4C706/Session-xxxxx-2018-12-28_211029-DCNqA3.log
INFO [2018-12-28 21:10:29.62]: ▸ 2018-12-28 21:10:29.625 xcodebuild[26100:264499] [MT] IDETestOperationsObserverDebug: (DB670290-6457-4A5B-954B-D418B9D154D2) Beginning test session xxxxx-DB670290-6457-4A5B-954B-D418B9D154D2 at 2018-12-28 21:10:29.625 with Xcode 10B61 on target <DVTiPhoneSimulator: 0x7fa3be7a7910> {
INFO [2018-12-28 21:10:29.62]: ▸ SimDevice: iPhone 5s (0BEDD1BE-5A4C-4CF7-A73B-CA51888C08E6, iOS 12.1, Shutdown)
INFO [2018-12-28 21:10:29.62]: ▸ } (12.1 (16B91))
INFO [2018-12-28 21:10:53.35]: ▸ All tests
INFO [2018-12-28 21:10:53.48]: ▸ Test Suite xxxxx.xctest started
INFO [2018-12-28 21:10:53.48]: ▸ xxxxx
INFO [2018-12-28 21:10:53.80]: ▸ ✓ testExample (0.361 seconds)
INFO [2018-12-28 21:10:53.81]: ▸ 	 Executed 1 test, with 0 failures (0 unexpected) in 0.361 (0.422) seconds
INFO [2018-12-28 21:10:53.81]: ▸ 
INFO [2018-12-28 21:10:53.81]: ▸ XCTest_Gherkin.framework
INFO [2018-12-28 21:10:54.12]: ▸ 2018-12-28 21:10:54.127 xcodebuild[26100:264499] [MT] IDETestOperationsObserverDebug: 24.517 elapsed -- Testing started completed.
INFO [2018-12-28 21:10:54.12]: ▸ 2018-12-28 21:10:54.127 xcodebuild[26100:264499] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
INFO [2018-12-28 21:10:54.12]: ▸ 2018-12-28 21:10:54.127 xcodebuild[26100:264499] [MT] IDETestOperationsObserverDebug: 24.517 sec, +24.517 sec -- end
INFO [2018-12-28 21:10:54.78]: ▸ Test Succeeded
tee: /Users/pnikolaou/Library/Logs/scan/xxxxx-xxxxx-Stage.log: Permission denied
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing ResourceBundle-TOCropViewControllerBundle-Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Generating 'Core.framework.dSYM'
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Processing Info.plist
▸ Copying /Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Build/Products/Debug-iphonesimulator/CropViewController/TOCropViewControllerBundle.bundle
▸ Processing Info.plist
▸ Generating 'UI.framework.dSYM'
▸ Processing Info.plist
▸ Processing Info.plist
▸ Generating 'xxxxx.framework.dSYM'
▸ Linking xxxxx
▸ Processing xxxxx Test-Info.plist
▸ Running script 'Fabric'
▸ Copying /Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Build/Products/Debug-iphonesimulator/xxxxx.framework
▸ Copying /Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Build/Products/Debug-iphonesimulator/UI.framework
▸ Copying /Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Build/Products/Debug-iphonesimulator/Core.framework
▸ Running script 'Run Script'
▸ Generating 'xxxxx.app.dSYM'
▸ Build Succeeded
▸ Processing Info.plist
▸ Linking xxxxx
▸ Processing Info.plist
▸ Running script 'Fabric'
▸ Running script 'Run Script'
▸ Generating 'xxxxx.app.dSYM'
▸ Processing Info.plist
▸ Linking xxxxx
2018-12-28 21:10:29.625 xcodebuild[26100:265608]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Logs/Test/Run-xxxxx-Stage-2018.12.28_21-10-11-+0200.xcresult/2_Test/Diagnostics/xxxxx-C7754B45-4A9C-4DDD-BD13-ED1592018578/xxxxx-3D0783BA-CBBA-49AB-AED7-824458A4C706/Session-xxxxx-2018-12-28_211029-DCNqA3.log
2018-12-28 21:10:29.625 xcodebuild[26100:264499] [MT] IDETestOperationsObserverDebug: (DB670290-6457-4A5B-954B-D418B9D154D2) Beginning test session xxxxx-DB670290-6457-4A5B-954B-D418B9D154D2 at 2018-12-28 21:10:29.625 with Xcode 10B61 on target <DVTiPhoneSimulator: 0x7fa3be7a7910> {
SimDevice: iPhone 5s (0BEDD1BE-5A4C-4CF7-A73B-CA51888C08E6, iOS 12.1, Shutdown)
} (12.1 (16B91))
All tests
Test Suite xxxxx.xctest started
xxxxx
✓ testExample (0.361 seconds)


	 Executed 1 test, with 0 failures (0 unexpected) in 0.361 (0.422) seconds

XCTest_Gherkin.framework
2018-12-28 21:10:54.127 xcodebuild[26100:264499] [MT] IDETestOperationsObserverDebug: 24.517 elapsed -- Testing started completed.
2018-12-28 21:10:54.127 xcodebuild[26100:264499] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2018-12-28 21:10:54.127 xcodebuild[26100:264499] [MT] IDETestOperationsObserverDebug: 24.517 sec, +24.517 sec -- end
▸ Test Succeeded
ERROR [2018-12-28 21:11:00.86]: Exit status: 1
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 1 |
| Number of failures | 0 |
+--------------------+---+

WARN [2018-12-28 21:11:01.32]: Lane Context:
INFO [2018-12-28 21:11:01.32]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test", :SCAN_DERIVED_DATA_PATH=>"/Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn", :SCAN_GENERATED_PLIST_FILES=>["/Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Logs/Test/Run-xxxxx-Stage-2018.12.28_21-10-11-+0200.xcresult/TestSummaries.plist"], :SCAN_GENERATED_PLIST_FILE=>"/Users/pnikolaou/Library/Developer/Xcode/DerivedData/xxxxx-gbuqxvqyqxosnrcnfbiwewejuojn/Logs/Test/Run-xxxxx-Stage-2018.12.28_21-10-11-+0200.xcresult/TestSummaries.plist"}
ERROR [2018-12-28 21:11:01.32]: Test execution failed. Exit status: 1
INFO [2018-12-28 21:11:01.32]: Successfully generated documentation at path '/Users/pnikolaou/Documents/repositories/xxxxx-ios/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | scan             | 61          |
+------+------------------+-------------+

ERROR [2018-12-28 21:11:01.35]: fastlane finished with errors
/Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane_core/lib/fastlane_core/ui/interface.rb:172:in `test_failure!': [!] Test execution failed. Exit status: 1 (FastlaneCore::Interface::FastlaneTestFailure)
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/scan/lib/scan/runner.rb:100:in `handle_results'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/scan/lib/scan/runner.rb:22:in `run'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/scan/lib/scan/manager.rb:18:in `work'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/actions/run_tests.rb:23:in `run'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:20:in `block (2 levels) in parsing_binding'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/pnikolaou/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.112.0/bin/fastlane:23:in `<top (required)>'
	from /Users/pnikolaou/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/pnikolaou/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14 (18A389)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :test do
    scan(workspace: "LocumsNest.xcworkspace", scheme: "LocumsNest-Stage")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Locums Nest.xcodeproj")
    build_app(workspace: "LocumsNest.xcworkspace", scheme: "LocumsNest-Prod")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("uk.co.locumsnest.doctorapp") # The bundle identifier of your app
apple_id("panagiotis.nikolaou@locumsnest.co.uk") # Your Apple email address

itc_team_id("118383596") # App Store Connect Team ID
team_id("YG4UEG7JX7") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.112.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2018-12-28**
</details>

**Comment by p-nicolaou** [comment]
Looks like similar issue with #12725
