### ISSUE TITLE
Books and Apps => Creation of apps of this type is not available

### ISSUE THREAD

**Issue by AmauriC** [fastlane/fastlane#14058]
Hey 👋

I have an app store connect account that sell books and I want to add an app.

produce fail with the error : Creation of apps of this type is not available

On app store connect the team name are the same for books and apps, probably why produce select the wrong account.

There is something I can do to fix this?

**Comment by janpio** [comment]
How exactly did you use `produce`?

**Comment by AmauriC** [comment]
**Appfile**
```
app_identifier "xxx"
apple_id "xxx"
itc_team_name "xxx"


ENV["FASTLANE_DONT_STORE_PASSWORD"] = "1"
ENV["FASTLANE_PASSWORD"] = "xxx"
ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "xxx"

ENV["KEYCHAIN_PASSWORD"] = "xxx"

team_id "xxx"
````

**Fastfile**
```
produce(
      app_identifier: "xxxx",
      app_name: "xxxx",
      language: 'English',
      app_version: "1.2",
      sku: "xxxx",
      company_name: "xxxx"
)
```

**lane output**
```
+----------------+----------------------------------+
|            Summary for produce 2.112.0            |
+----------------+----------------------------------+
| app_identifier | xxx                              |
| app_name       | xxx                              |
| language       | English                          |
| app_version    | 1.2                              |
| sku            | xxx                              |
| company_name   | xxx                              |
| username       | xxx                              |
| platform       | ios                              |
| skip_itc       | false                            |
| skip_devcenter | false                            |
| team_id        | xxx                              |
| itc_team_name  | xxx                              |
+----------------+----------------------------------+

[20:33:38]: [DevCenter] App 'xxx' already exists, nothing to do on the Dev Center
[20:33:42]: Creating new app 'xxx' on App Store Connect


+------------------+---------------+
|           Lane Context           |
+------------------+---------------+
| DEFAULT_PLATFORM | ios           |
| PLATFORM_NAME    | ios           |
| LANE_NAME        | ios publishit |
+------------------+---------------+
[20:33:43]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Creation of apps of this type is not available"]}, "statusCode"=>"ERROR"}
```

**.xml report**
```
actions/actions_helper.rb:48:in `execute_action' 
runner.rb:232:in `block in execute_action' 
runner.rb:227:in `chdir' 
runner.rb:227:in `execute_action' 
runner.rb:157:in `trigger_action_by_name' 
fast_file.rb:154:in `method_missing' Fastfile:21:in `block (2 levels) in parsing_binding' 
lane.rb:33:in `call' 
runner.rb:49:in `block in execute' 
runner.rb:45:in `chdir' 
runner.rb:45:in `execute' 
lane_manager.rb:56:in `cruise_lane' 
command_line_handler.rb:36:in `handle' 
commands_generator.rb:108:in `block (2 levels) in run' 
commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call' 
commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run' 
commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command' 
fastlane-2.112.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!' 
commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!' 
commands_generator.rb:333:in `run' 
commands_generator.rb:41:in `start' 
cli_tools_distributor.rb:108:in `take_off' 
fastlane-2.112.0/bin/fastlane:23:in `<top (required)>'
fastlane:22:in `load'
fastlane:22:in `<main>' {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Creation of apps of this type is not available"]}, "statusCode"=>"ERROR"}"/
```

**itc account**
![book & app](https://wpmobile.app/itc_book_apps.png)

**Comment by janpio** [comment]
Hm yep, the spaceship logs confirm: fastlane creates a session for the wrong `contentProviderId` (`119567781`). The `ra/apps/manageyourapps/summary/v2` response even tells fastlane that this account can't create iOS apps, but this is ignored and you get the error 500.

But: `contentProviderId` is just what the documentation calls "Team ID". You should be able to work around that by adding `itc_team_id: 403769` to your `produce` call.

Is `team_id` in your `Appfile` that value already? If so, and my suggestion works, we will have to understand why the value from the Appfile didn't get picked up.

**Comment by AmauriC** [comment]
`itc_team_id: 403769` in the produce call work 👍 

The value in the Appfile is different, it's the team id of the Membership section on developer.apple.com (10 characters, A-Z0-9).

Tested with `403769`, didn't work.

--

This is solved for me, thanks!

If I can help more to debug this issue, I'm here ; )

**Comment by janpio** [comment]
Can you get rid of the `itc_team_name` in the Appfile as well and try again with `403769` in the Appfile (and without specifying it directly for `produce` of course)?

**Comment by AmauriC** [comment]
If `itc_team_id` is on the Appfile, it's working well.


```
+----------------+----------------------------------+
|            Summary for produce 2.113.0            |
+----------------+----------------------------------+
| itc_team_id    | 403769                           |
+----------------+----------------------------------+

[14:18:54]: [DevCenter] App 'xx' already exists, nothing to do on the Dev Center
[14:18:57]: App 'xx' already exists (xx), nothing to do on App Store Connect
```


```
+----------------+----------------------------------+
|            Summary for produce 2.113.0            |
+----------------+----------------------------------+
| team_id        | D--GV--49D                       |
| itc_team_id    | 403769                           |
| itc_team_name  | username                         |
+----------------+----------------------------------+

[14:19:29]: [DevCenter] App 'xx' already exists, nothing to do on the Dev Center
[14:19:32]: App 'xx' already exists (xx), nothing to do on App Store Connect
```
