### ISSUE TITLE
Simulator Localization Fails as `.GlobalPreferences.plist` is missing

### ISSUE THREAD

**Issue by joshuajung** [fastlane/fastlane#14108]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to create screenshots for two languages on one device. Fastlane crashes very soon after start, missing a `.GlobalPreferences.plist`file in the simulator directory.

##### Command executed

`bundle exec fastlane snapshot`

##### Complete output when running fastlane, including the stack trace and command used

```
$ bundle exec fastlane snapshot
[✔] 🚀 
[15:23:31]: Successfully loaded '/Users/jaj/Repositories/curry-ios/Curry/Snapfile' 📄

+----------------------------+--------------------+
|        Detected Values from './Snapfile'        |
+----------------------------+--------------------+
| devices                    | ["iPhone XS"]      |
| languages                  | ["en-US", "de-DE"] |
| localize_simulator         | true               |
| scheme                     | CurryScreenshots   |
| output_directory           | ./screenshots      |
| clear_previous_screenshots | true               |
+----------------------------+--------------------+

[15:23:31]: $ xcodebuild -showBuildSettings -scheme CurryScreenshots -project ./Curry.xcodeproj

+----------------------------+-----------------------------------------------------+
|                           Summary for snapshot 2.114.0                           |
+----------------------------+-----------------------------------------------------+
| project                    | ./Curry.xcodeproj                                   |
| output_directory           | /Users/jaj/Repositories/curry-ios/Curry/screenshots |
| devices                    | ["iPhone XS"]                                       |
| languages                  | ["en-US", "de-DE"]                                  |
| launch_arguments           | [""]                                                |
| output_simulator_logs      | false                                               |
| skip_open_summary          | false                                               |
| skip_helper_version_check  | false                                               |
| clear_previous_screenshots | true                                                |
| reinstall_app              | false                                               |
| erase_simulator            | false                                               |
| localize_simulator         | true                                                |
| buildlog_path              | ~/Library/Logs/snapshot                             |
| clean                      | false                                               |
| scheme                     | CurryScreenshots                                    |
| number_of_retries          | 1                                                   |
| stop_after_first_error     | false                                               |
| result_bundle              | false                                               |
| concurrent_simulators      | true                                                |
| xcode_path                 | /Applications/Xcode.app                             |
+----------------------------+-----------------------------------------------------+

[15:23:33]: Clearing previously generated screenshots
[15:23:33]: Building and running project - this might take some time...
[15:23:34]: Patching simulators '/Users/jaj/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
[15:23:36]: Erasing iPhone XS...
[15:23:38]: Localizing iPhone XS (AppleLocale=en_US AppleLanguages=[en-US])

[15:23:38]: Error accessing file, this might be due to fastlane's directory handling
[15:23:38]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

Traceback (most recent call last):
	29: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	28: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	27: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	26: from /Users/jaj/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	25: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/bin/fastlane:23:in `<top (required)>'
	24: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/cli_tools_distributor.rb:105:in `take_off'
	23: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/commands_generator.rb:14:in `start'
	22: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/commands_generator.rb:104:in `run'
	21: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	20: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	19: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	18: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	17: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	16: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/commands_generator.rb:40:in `block (2 levels) in run'
	15: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/runner.rb:45:in `work'
	14: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `take_screenshots_simultaneously'
	13: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `each'
	12: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `block in take_screenshots_simultaneously'
	11: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each_with_index'
	10: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each'
	 9: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:69:in `block (2 levels) in take_screenshots_simultaneously'
	 8: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:69:in `each'
	 7: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:70:in `block (3 levels) in take_screenshots_simultaneously'
	 6: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:80:in `launch_simultaneously'
	 5: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:31:in `prepare_for_launch'
	 4: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:57:in `prepare_simulators_for_launch'
	 3: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:57:in `each'
	 2: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:61:in `block in prepare_simulators_for_launch'
	 1: from /Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:123:in `localize_simulator'
/Users/jaj/.rvm/gems/ruby-2.6.0/gems/fastlane-2.114.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:123:in `write': No such file or directory @ rb_sysopen - /Users/jaj/Library/Developer/CoreSimulator/Devices/DF8D015A-93AF-41EF-960A-2E374D90C54B/data/Library/Preferences/.GlobalPreferences.plist (Errno::ENOENT)
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.114.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bundler                   | 1.17.2       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.6.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| google-cloud-storage      | 1.15.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-01-20**
</details>

### Remarks
This seems to happen as line 110 (`erase_simulator`) in `simulator_launcher_base.rb` removes the entire `Library` folder for the simulator, which is then missing in line 123 (`localize_simulator`), called right afterwards. If I comment out line 110, everything seems to work fine.

**Comment by joshuajung** [comment]
This is still an issue in Fastlane 2.116.1 and does not seem to be related to Ruby 2.6.0 - is totally reproducible in 2.5.3.
