### ISSUE TITLE
Supply isn't working on CI with Google auth .p12 files

### ISSUE THREAD

**Issue by juanimoli** [fastlane/fastlane#14128]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Since Fastlane 2.108.0, we're experiencing issues deploying our application to the Google Play Store. This is mainly because, in this version, there was introduced [this refactor](https://github.com/fastlane/fastlane/pull/13431). Although we're evaluating using JSON key, we're still using p12 file to authenticate with Google, which is something you still support (maybe not anymore?). 

Regarding to the issue, in the refactor mentioned before, [this particular line](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/client.rb#L18) doesn't work in CI (we're using CircleCI), because of the interactive checking. Fastlane is waiting for some user input, but none can be made because we're running on CI. I'm guessing that this can be easily fixed by adding `Helper:ci?` somewhere.

If you're not supporting this anymore, It would be great if you could update the documentation so we can migrate to the new authentication files and there is more visibility, because we found nothing by just reading the changelog or the online docs.

Thanks!

##### Command executed
`supply(track: 'alpha', apk_paths: ${CUSTOM_APK_PATHS_ARRAY})`

##### Complete output when running fastlane, including the stack trace and command used
```
Running Fastlane
[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [⠴] 🚀 [✔] 🚀 
[02:08:25]: Sending anonymous analytics information
[02:08:25]: Learn more at https://docs.fastlane.tools/#metrics
[02:08:25]: No personal or sensitive data is sent.
[02:08:25]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[02:08:25]: ----------------------------------------
[02:08:25]: --- Step: Verifying fastlane version ---
[02:08:25]: ----------------------------------------
[02:08:25]: Your fastlane version 2.114.0 matches the minimum requirement of 2.108.0  ✅
[02:08:25]: Driving the lane 'android start_deploy' 🚀
[02:08:25]: -----------------------------------------------
[02:08:25]: --- Step: Switch to android deploy_app lane ---
[02:08:25]: -----------------------------------------------
[02:08:25]: Cruising over to lane 'android deploy_app' 🚖
[02:08:25]: Running in Circle CI
[02:08:25]: --------------------
[02:08:25]: --- Step: gradle ---
[02:08:25]: --------------------
//Gradle Build...
[02:21:14]: ▸ BUILD SUCCESSFUL in 12m 48s
[02:21:14]: ▸ 128 actionable tasks: 128 executed
[02:21:15]: --------------------
[02:21:15]: --- Step: supply ---
[02:21:15]: --------------------
Appfile: DEPRECATED issuer: use json_key_file instead
Appfile: DEPRECATED keyfile: use json_key_file instead
Appfile: DEPRECATED issuer: use json_key_file instead
Appfile: DEPRECATED keyfile: use json_key_file instead
Appfile: DEPRECATED issuer: use json_key_file instead
Appfile: DEPRECATED keyfile: use json_key_file instead
Appfile: DEPRECATED issuer: use json_key_file instead
Appfile: DEPRECATED keyfile: use json_key_file instead
Appfile: DEPRECATED issuer: use json_key_file instead
Appfile: DEPRECATED keyfile: use json_key_file instead
[02:21:15]: DEPRECATED --issuer OPTION. Use --json_key instead
//some ENV variables prints here
[02:21:15]: To not be asked about this value, you can specify it using 'json_key'
[02:21:15]: The service account json file used to authenticate with Google: 
//some ENV variables prints here
[02:21:15]: Could not retrieve response as fastlane runs in non-interactive mode

+------+----------------------------------------+-------------+
|                      fastlane summary                       |
+------+----------------------------------------+-------------+
| Step | Action                                 | Time (in s) |
+------+----------------------------------------+-------------+
| 1    | Verifying fastlane version             | 0           |
| 2    | Switch to android deploy_app lane      | 0           |
| 3    | gradle                                 | 769         |
| 💥   | supply                                 | 0           |
+------+----------------------------------------+-------------+

[02:21:15]: fastlane finished with errors
bundler: failed to load command: fastlane (/home/circleci/.rubies/ruby-2.4.3/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:155:in `verify_interactive!'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:128:in `input'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/supply/lib/supply/client.rb:18:in `make_from_config'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/supply/lib/supply/client.rb:101:in `make_from_config'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/supply/lib/supply/uploader.rb:262:in `client'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  android/AndroidFastfile:187:in `block in parsing_binding'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  android/AndroidFastfile:27:in `block in parsing_binding'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
  /home/circleci/.rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/fastlane-2.114.0/bin/fastlane:23:in `<top (required)>'
  /home/circleci/.rubies/ruby-2.4.3/bin/fastlane:23:in `load'
  /home/circleci/.rubies/ruby-2.4.3/bin/fastlane:23:in `<top (required)>'
Error running Fastlane for the android platform
Exited with code 1
```

### Environment

- Running on CircleCI Images (api-28)
- Using parameters values for `SUPPLY_KEY` and `SUPPLY_ISSUER`
- Working on 2.107.0 and below
- We're using our own Fastfile, which uses gradle(...) and then supply(...), as mentioned before

**Comment by juanimoli** [comment]
> I am pretty sure that was not intentional, sorry about that.

It wasn't my intention to blame someone, I just tried to make the issue easy to find/fix :D

> Can you share your `fastlane env` and at least the relevant lane from your `Fastfile` so I can better understand exactly what you are calling and execute it?

Of course, here it is:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | debian_based 9.6                                        |
| Ruby                        | 2.4.3                                                   |
| Bundler?                    | true                                                    |
| Git                         | git version 2.11.0                                      |
| Installation Source         | ~/.rubies/ruby-2.4.3/bin/fastlane                       |
| Host                        | Debian GNU/Linux 9 debian_based 9.6 (4.4.0-141-generic) |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.3/lib                                |
| OpenSSL Version             | OpenSSL 1.1.0j  20 Nov 2018                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |


### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.108.0"

ENV['FASTLANE_HIDE_GITHUB_ISSUES'] = '1'

# Require Fastlane's UI to handle log messages. To be sure which method you should use check: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ui/interface.rb
require 'fastlane_core/ui/ui.rb'
require 'fastlane_core/helper.rb'

platform :ios do
    import "ios/IOSFastfile"
end

platform :android do
    import "android/AndroidFastfile"
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
for_platform :ios do
    app_identifier ENV["BUNDLE_IDENTIFIER"] # The bundle identifier of your app
    apple_id ENV["APPLE_ID"]
end

for_platform :android do
    # TODO: issuer and keyfile are deprecated use json_key_file instead
    issuer ENV["API_ISSUER"]
    keyfile ENV["API_KEYFILE"]
    package_name ENV["PACKAGE_NAME"]
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.114.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 2.0.1        |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.5.0        |
| kramdown                  | 1.17.0       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.7.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| danger                    | 5.5.13       |
| danger-plugin-api         | 1.0.0        |
| danger-permission_lint    | 0.0.1        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.6.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.0       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| google-cloud-storage      | 1.15.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-01-24**
</details>

<details>
<summary>Custom Fastfile extract</summary>
```ruby
lane :deploy_app do
        # Using custom CIHelper/CIProvider class
	if CIHelper::is_running_in_ci?
		UI.message "Running in #{CIProvider::ENVIRONMENT}"
		if CIHelper::can_deploy_application?
			project_name = AndroidHelper::APP_PROJECT_NAME
			apk_paths = "#{CIProvider::BUILD_DIR}/#{project_name}/build/outputs/apk/release";
			release_notes = CIHelper::get_release_notes

			# Generate apk with custom Android Helper. This call gradle(...) inside
			AndroidHelper::run_gradle(self, project_dir: CIProvider::BUILD_DIR, task: ":#{project_name}:assembleRelease", flags: "-PsplitApk --no-build-cache --daemon --parallel -Ppublish --rerun-tasks -Dorg.gradle.jvmargs=\"-XX:+HeapDumpOnOutOfMemoryError -XX:+UseCompressedOops\"")

			# This gets all the splits except the universal. Returns Dir[path]
			apk_split_paths = CIHelper::get_file_names_from_dir(apk_paths, "#{project_name}-*{[!universal]}*-release.apk")

			# This gets all the universal apk path
			universal_apk = Dir.glob("#{apk_paths}/*universal*.apk")[0]

			# This gets the proguard mappings for the released version (since we run assembleRelease, we get the release flavor)
			proguard_mappings = "#{CIProvider::BUILD_DIR}/#{project_name}/build/outputs/mapping/release/mapping.txt"

			# Upload apk to Google Play, check options.rb (in Fastlane repo) to see options.
			UI.message "Checking if we are in CI: #{Helper.ci?}"
			supply(track: 'alpha', apk_paths: apk_split_paths)
			UI.success 'Release published to the Play Store to the alpha channel successfully'

			# Upload apk to HockeyApp
			hockey(api_token: CIHelper::HOCKEY_TOKEN, ipa: universal_apk, notes: release_notes)
			UI.success 'Release published to HockeyApp successfully'

			# Create release in GitHub
			version = AndroidHelper::project_version(project_name)
			versionName = version['versionName']

			gh_release_assets = [apk_paths, universal_apk]
			if File.file?(proguard_mappings)
				gh_release_assets << proguard_mappings
			end

			UI.message "Creating release #{versionName} in GitHub"

			# Note that for the GitHub release we also upload the universal APK. See set_github_release.rb (in fastlane repo) to see accepted parameters.
			# We also add the APKs path, this automatically creates a zip with the directory, and uploads it to the Github release.
			set_github_release(repository_name: CIHelper::repo_name,
				api_token: CIHelper::GITHUB_TOKEN,
				name: "v#{versionName}",
				tag_name: "v#{versionName}",
				description: release_notes,
				commitish: CIProvider::get_base_branch,
				upload_assets: gh_release_assets)

			UI.success 'Release Published to the Play Store as well as GitHub successfully'

			# Notify deploy to Bugsnag
			if CIHelper::has_bugsnag_api_key?
				sh("curl -d 'apiKey=#{CIHelper::BUGSNAG_API_KEY}&appVersion=#{versionName}' https://notify.bugsnag.com/deploy")
			end
		end
	else
		UI.error 'Not running in CI environment. Local run not yet supported'
	end
end
```
<details>
