### ISSUE TITLE
[!] Operation timed out - connect(2) for 192.168.5.71:49246

### ISSUE THREAD

**Issue by demoker** [fastlane/fastlane#14129]
#### Question Description
This error occurred when I uploaded files to the server using FTP command. Please give me some guidance. Thank you.

command:

```   
   Net::FTP.open("#{$ftp_url}") do |ftp|
      ftp.login("#{$ftp_login_name}","#{$ftp_login_password}")
      ftp.chdir('/')
      ftp.chdir("iOS/#{FTP_FileName[$i]}/#{release_path}/")
      ftp.putbinaryfile("#{$project_root_path}#{$project_name}/fastlane/build/#{release_path}/#{branches[$i]}/update.json")
      ftp.putbinaryfile("#{$project_root_path}#{$project_name}/fastlane/build/#{release_path}/#{branches[$i]}/#{$project_name}.ipa")
      puts "上传ftp完毕"
   end
``` 

```
/Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:64:in `connect': [!] Operation timed out - connect(2) for 192.168.5.71:49246 (Errno::ETIMEDOUT)
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:64:in `connect_internal'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:137:in `connect'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:627:in `block in tcp'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:227:in `each'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:227:in `foreach'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:617:in `tcp'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/ftp.rb:339:in `block in open_socket'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:76:in `timeout'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/ftp.rb:334:in `open_socket'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/ftp.rb:547:in `transfercmd'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/ftp.rb:692:in `block (2 levels) in storbinary'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/ftp.rb:310:in `with_binary'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/ftp.rb:691:in `block in storbinary'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/ftp.rb:690:in `storbinary'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/ftp.rb:842:in `putbinaryfile'
	from Fastfile:179:in `block (3 levels) in parsing_binding'
	from /Users/fslb/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/ftp.rb:165:in `open'
	from Fastfile:168:in `block (2 levels) in parsing_binding'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/gems/fastlane-2.114.0/bin/fastlane:23:in `<top (required)>'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:24:in `eval'
	from /Users/fslb/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:24:in `<main>'
```

### fastlane env

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.0"

fastlane_require 'rubygems'
fastlane_require 'json'
fastlane_require 'net/ftp'


# 配置区域

# 工程配置
$project_bundle_id = "-----"
$project_profile_name = "vehicleEvaluation_distribution"
$project_root_path =  "/Users/fslb/Downloads/cp_iphone/"
$project_name = "LubaoCar" # 一般情况也是lubao_store_2_path
$project_info_plist_name = "LubaoCar-Info.plist"
$project_net_config_path = "../LubaoCar/Common/LBConstant.h"
$project_scheme = "LubaoCar"

# 路宝商店根地址
$lubao_store_host = "https://---------" # lubao_store_1_path

# 环境配置，这里一般不需要修改
$lubao_store_3_pre_path = "prerelease" # 准生产
$lubao_store_3_release_path = "release" # 生产

# ftp相关配置
$ftp_url = "--------"
$ftp_login_name = "------"
$ftp_login_password = "----"

$pgy_apiKey = "----"
$pgy_userKey = "----"
$pgy_upload_url = "https://www.pgyer.com/apiv1/app/upload"

default_platform :ios

platform :ios do
  before_all do
    # 执行lane之前必会执行这里

  end

  # lane :test do
  #   scan
  # end

  # desc "准生产打包"
  lane :release do |options|    
  #   # match(type: "appstore") # more information: https://codesigning.guide
    is_release = options[:release] 
    if is_release == 1 
      is_release = true 
      release_path = "#{$lubao_store_3_release_path}"
    else
      is_release = false
      release_path = "#{$lubao_store_3_pre_path}"
    end


    is_ftp = options[:store]

    if is_ftp.length == 0
      is_ftp = "ftp"
    end 

    branch = options[:branch]
    version_Number = options[:v]
    build_Number = options[:b]

    if !build_Number
       build_Number = 0;
    end

    update_desc = options[:desc]


    if branch == "all"
      branches = Array["changanbaoxian","develop","guotai","yingda"]
      FTP_FileName = Array["CHAAssessment","Assessment","ATAssessment","YDAssessment"]
    else
      branches = Array[branch]

      case branch
      when "changanbaoxian"
          FTP_FileName = Array["CHAAssessment"]
      when "develop"
          FTP_FileName = Array["Assessment"]
      when "guotai"
          FTP_FileName = Array["ATAssessment"]
      when "yingda"
          FTP_FileName = Array["YDAssessment"]
      else
          puts "你输入的分支名称可能不正确"
      end
      
    end

    $i = 0
    $num = branches.length
    while $i < $num
      var_branch = branches[$i]

      puts "Begin to run git pull #{var_branch}"

      # 确认分支、git状态、拉取最新代码
      

      # 修改对应环境
      if is_release
      ostr="#define PRE_RELEASE_MODE 1"
      nstr="//#define PRE_RELEASE_MODE 1"
      else
      ostr="//#define PRE_RELEASE_MODE 1"
      nstr="#define PRE_RELEASE_MODE 1"
      end
      File.open("#{$project_net_config_path}","r:utf-8") do |lines| # r:utf-8表示以utf-8编码读取文件，要与当前代码文件的编码相同
       buffer = lines.read.gsub(ostr,nstr) # 将文件中所有的ostr替换为nstr，并将替换后文件内容赋值给buffer
       File.open("#{$project_net_config_path}","w"){|l| # 以写的方式打开文件，将buffer覆盖写入文件
       l.write(buffer)
      }

      end

      # sh "git push origin #{branch}" # push本地仓库到远端

      if version_Number
        set_info_plist_value(path: "./#{$project_name}/#{$project_info_plist_name}", key: "CFBundleShortVersionString", value: version_Number)
      else
        increment_version_number # 版本号+1
      end

      if build_Number
        set_info_plist_value(path: "./#{$project_name}/#{$project_info_plist_name}", key: "CFBundleVersion", value: build_Number)
      else
        increment_build_number # build+1
      end

      # Build your app - more options available
       
      

      # sh "git add ../LubaoCar/LubaoCar-Info.plist"
      # build_Number = get_build_number(xcodeproj: "LubaoCar.xcodeproj")
      build_Number = get_info_plist_value(path: "./#{$project_name}/#{$project_info_plist_name}", key: "CFBundleVersion")

      


    
    # 开始上传ipa 和 update.json
    puts "开始上传ipa"

    case is_ftp
    when "ftp"
      Net::FTP.open("#{$ftp_url}") do |ftp|
      puts "1111111"
puts "#{$ftp_url}"
      ftp.login("#{$ftp_login_name}","#{$ftp_login_password}")
      ftp.chdir('/')
      ftp.chdir("iOS/#{FTP_FileName[$i]}/#{release_path}/")
puts "iOS/#{FTP_FileName[$i]}/#{release_path}/"
puts "#{$project_root_path}#{$project_name}/fastlane/build/#{release_path}/#{branches[$i]}/update.json"
puts "#{$project_root_path}#{$project_name}/fastlane/build/#{release_path}/#{branches[$i]}/#{$project_name}.ipa"

      ftp.putbinaryfile("#{$project_root_path}#{$project_name}/fastlane/build/#{release_path}/#{branches[$i]}/update.json")
      ftp.putbinaryfile("#{$project_root_path}#{$project_name}/fastlane/build/#{release_path}/#{branches[$i]}/#{$project_name}.ipa")

      puts "上传ftp完毕"
      end
    when "pgy"
      
          pgyer(api_key: "#{$pgy_apiKey}", user_key: "#{$pgy_userKey}", password: "lubao", install_type: "2", update_description:"#{update_desc}")
          puts "上传蒲公英完毕"
    when "fir"

      
      
    end

      $i +=1

    end

    # pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  
  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
   

    desc "🍺 successful"
  end

  error do |lane, exception|
    # notification (subtitle:"报错",message:exception.message)
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "----" # The bundle identifier of your app
apple_id "mdk132@qq.com" # Your Apple email address

team_id "-----" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.114.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| faraday_middleware        | 0.13.0       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.0.2        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2019-01-24**
</details>

**Comment by demoker** [comment]
Transmit is fine, but the command can't.
Ruby has been reinstalled, but not yet.

**Comment by janpio** [comment]
That is not really a fastlane question, but we can try to solve this anyway.

So `$ftp_url` is `192.168.5.71:49246`?
Strange is that it seems to fail only in line 179, which means 178 succeeds. Does it successfully upload `update.json`?

**Comment by demoker** [comment]
@janpio FTP default port is 21, update.json file has not been uploaded successfully.
Is it the ruby environment? I've reinstalled ruby, but it still won't work

**Comment by demoker** [comment]
solved!
`ftp.passive = false`

**Comment by janpio** [comment]
So the code didn'T match the functionality of your FTP server? Did I understand that correctly?
