### ISSUE TITLE
some wrong happen when I use fastlane to upload an ipa file

### ISSUE THREAD

**Issue by longzixinyu** [fastlane/fastlane#14272]
### Issue Description
I use fastlane to upload the ipa to the store in a script run by an Xcode bot.
Xcode  version is 9.3

Result
```
2019-02-20 18:33:16 +0800
current_dir:/var/folders/k0/sq54d7ln0k787kwny5s1x7r80000gp/T/d20190220-46925-5mw4li
➡️  Pilot fails to upload ipa: itunes_transporter can't initialise
    https://github.com/fastlane/fastlane/issues/11605 [closed] 5 💬
    22 Mar 2018

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:326:in `initialize': [!] undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/pilot/lib/pilot/build_manager.rb:37:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/pilot/lib/pilot/build_manager.rb:37:in `upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/cli_tools_distributor.rb:105:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by janpio** [comment]
Your post is missing necessary information @longzixinyu. Please see what @fastlane-bot posted. Thanks.

**Comment by zxfrank** [comment]
Hello all! Same issue here
[fastlane_env.txt](https://github.com/fastlane/fastlane/files/2928173/fastlane_env.txt)

**Comment by zxfrank** [comment]
@longzixinyu you may have a look to #11605, https://github.com/fastlane/fastlane/issues/11605#issuecomment-359163627 solved my issue

this can be closed
