### ISSUE TITLE
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for:

### ISSUE THREAD

**Issue by Kenny9999** [fastlane/fastlane#14287]
Please help, 

I just can't get fastlane scregrab to work, 

I have a InstrumentedTest running well in an emulator, all fine, but when I try to run
bundle exec fastlane screengrab

it give me an error that it can't find instrumentation on my apk , but they just have worked on the emulator!?!?!?

*********************************************

[19:09:57]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[19:09:57]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[19:09:57]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb devices -l
[19:09:57]: ▸ List of devices attached
[19:09:57]: ▸ emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:9
[19:09:57]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[19:09:57]: ▸ /sdcard
[19:09:57]: Cleaning screenshots on device
[19:09:57]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell rm -rf /sdcard/com.appcom.coworkingspace/screengrab
ls: /data/data/com.appcom.coworkingspace/app_screengrab: No such file or directory
[19:09:57]: Exit status: 1
[19:09:57]: To not be asked about this value, you can specify it using 'app_apk_path'
[19:09:57]: Select your debug app APK
1. room/build/outputs/apk/debug/room-debug.apk
2. app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
3. app/build/outputs/apk/debug/app-debug.apk
?  3
[19:10:06]: To not be asked about this value, you can specify it using 'tests_apk_path'
[19:10:06]: Select your debug tests APK
1. room/build/outputs/apk/debug/room-debug.apk
2. app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
3. app/build/outputs/apk/debug/app-debug.apk
?  2
[19:10:11]: Validating app APK
[19:10:11]: $ /Users/patricemainville/Library/Android/sdk/build-tools/28.0.3/aapt dump permissions app/build/outputs/apk/debug/app-debug.apk
[19:10:11]: ▸ package: com.appcom.coworkingspace
[19:10:11]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[19:10:11]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[19:10:11]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[19:10:11]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[19:10:11]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[19:10:11]: ▸ uses-permission: name='android.permission.REORDER_TASKS'
[19:10:11]: ▸ uses-permission: name='android.permission.INTERNET'
[19:10:11]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[19:10:11]: ▸ uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
[19:10:11]: ▸ uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
[19:10:11]: ▸ uses-permission: name='android.permission.READ_CALENDAR'
[19:10:11]: ▸ uses-permission: name='android.permission.WRITE_CALENDAR'
[19:10:11]: ▸ uses-permission-sdk-23: name='android.permission.SYSTEM_ALERT_WINDOW'
[19:10:11]: ▸ uses-permission: name='android.permission.USE_BIOMETRIC'
[19:10:11]: ▸ uses-permission: name='android.permission.USE_FINGERPRINT'
[19:10:11]: ▸ uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
[19:10:11]: ▸ uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
[19:10:11]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[19:10:11]: Installing app APK
[19:10:11]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/debug/app-debug.apk
[19:10:14]: ▸ Success
[19:10:14]: Installing tests APK
[19:10:14]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
[19:10:15]: ▸ Success
[19:10:15]: Granting the permission necessary to change locales on the device
[19:10:15]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.appcom.coworkingspace android.permission.CHANGE_CONFIGURATION
[19:10:15]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[19:10:15]: ▸ 25
[19:10:15]: Granting the permissions necessary to access device external storage
[19:10:15]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.appcom.coworkingspace android.permission.WRITE_EXTERNAL_STORAGE
[19:10:15]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.appcom.coworkingspace android.permission.READ_EXTERNAL_STORAGE
[19:10:15]: Running tests for locale: en-US
[19:10:15]: $ /Users/patricemainville/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
com.appcom.coworkingspace.test/android.support.test.runner.AndroidJUnitRunner
[19:10:16]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.appcom.coworkingspace.test/android.support.test.runner.AndroidJUnitRunner
[19:10:16]: ▸ at com.android.commands.am.Am.runInstrument(Am.java:890)
[19:10:16]: ▸ at com.android.commands.am.Am.onRun(Am.java:400)
[19:10:16]: ▸ at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
[19:10:16]: ▸ at com.android.commands.am.Am.main(Am.java:121)
[19:10:16]: ▸ at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[19:10:16]: ▸ at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
[19:10:16]: ▸ INSTRUMENTATION_STATUS: id=ActivityManagerService
[19:10:16]: ▸ INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.appcom.coworkingspace.test/android.support.test.runner.AndroidJUnitRunner}
[19:10:16]: ▸ INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.appcom.coworkingspace.test/android.support.test.runner.AndroidJUnitRunner
at com.android.commands.am.Am.runInstrument(Am.java:890)
at com.android.commands.am.Am.onRun(Am.java:400)
at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
at com.android.commands.am.Am.main(Am.java:121)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.appcom.coworkingspace.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1
[19:10:16]: Exit status: 1

******************************************

fastlane env give 
*****************************************

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.14.3                              |
| Ruby                        | 2.2.4                                |
| Bundler?                    | false                                |
| Git                         | git version 2.20.1                   |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.14.3 (18D109)            |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained                | false                                |
| Is homebrew                 | true                                 |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.appcom.coworkingspace") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.1          |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.5.0        |
| fastimage                 | 2.1.5        |
| addressable               | 2.6.0        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| multi_json                | 1.13.1       |
| jwt                       | 2.1.0        |
| os                        | 1.0.0        |
| psych                     | 2.0.8        |
| uber                      | 0.1.0        |
</details>

*generated on:* **2019-02-20**
</details>

*************************************************

IDK if that couls be related, but
I'm using kotlin and latest androidx stuff

testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

androidTestImplementation 'tools.fastlane:screengrab:1.2.0'
androidTestImplementation 'androidx.test:runner:1.1.1'
androidTestImplementation 'androidx.test:rules:1.1.1'
androidTestImplementation 'org.hamcrest:hamcrest-library:1.3'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'

and have basically the generated stuff into Appvile and Fastfile

Please help

**Comment by PetrKubes97** [comment]
Hi, what was the issue? I've run to the exac same problem.

**Comment by pmarois** [comment]
Did you try with the addition of `test_instrumentation_runner 'androidx.test.runner.AndroidJUnitRunner'` to your `Screengrabfile`?
