### ISSUE TITLE
undefined method 'public_url' when uploading to s3

### ISSUE THREAD

**Issue by oronbz** [fastlane/fastlane#1433]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Trying to upload ipa to s3 with s3 action but receiving `[!] undefined method 'public_url' for #<AWS::S3::ObjectVersion:0x007fdc9b8f8430>`

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane upload_s3
[11:22:35]: ------------------------------
[11:22:35]: --- Step: default_platform ---
[11:22:35]: ------------------------------
[11:22:35]: Driving the lane 'ios upload_s3' 🚀
[11:22:35]: --------------------------------
[11:22:35]: --- Step: get_version_number ---
[11:22:35]: --------------------------------
[11:22:35]: $ cd /Users/oron/Development/DriverBox-iOS && agvtool what-marketing-version -terse1
[11:22:35]: ▸ 6.18.9
[11:22:35]: ----------------
[11:22:35]: --- Step: s3 ---
[11:22:35]: ----------------
[11:22:35]: krausefx-ipa distribute:s3 -f "./Dist/DriverApp-v6.18.9.ipa" -a "--HIDDEN FOR SECURITY PURPOSES---" -s "--HIDDEN FOR SECURITY PURPOSES---" -b "--HIDDEN FOR SECURITY PURPOSES---" -r "eu-west-1" -P "--HIDDEN FOR SECURITY PURPOSES---"
[11:22:35]: $ krausefx-ipa distribute:s3 -f "./Dist/DriverApp-v6.18.9.ipa" -a "--HIDDEN FOR SECURITY PURPOSES---" -s "--HIDDEN FOR SECURITY PURPOSES---" -b "--HIDDEN FOR SECURITY PURPOSES---" -r "eu-west-1" -P "--HIDDEN FOR SECURITY PURPOSES---"
[11:22:45]: ▸ Error while uploading to S3: undefined method `public_url' for
[11:22:45]: ▸ #<AWS::S3::ObjectVersion:0x007fa669b87678>
[11:22:46]: Variable Dump:
[11:22:46]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios upload_s3", :VERSION_NUMBER=>"6.18.9", :S3_IPA_OUTPUT_PATH=>"---HIDDEN FOR SECURITY PURPOSES---"}
[11:22:46]: undefined method `public_url' for #<AWS::S3::ObjectVersion:0x007f9842f04790>

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | default_platform   | 0           |
| 2    | get_version_number | 0           |
| 3    | s3                 | 10          |
+------+--------------------+-------------+

[11:22:46]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '1aa196e38c59351fdcc9ed4e917764aa'
The crash report has been stored locally '/tmp/sentry_1aa196e38c59351fdcc9ed4e917764aa.json'
/Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/actions/s3.rb:235:in `upload_plist_and_html_to_s3': [!] undefined method `public_url' for #<AWS::S3::ObjectVersion:0x007f9842f04790> (NoMethodError)
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/actions/s3.rb:182:in `run'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:111:in `block (2 levels) in parsing_binding'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/oron/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/oron/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/oron/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/oron/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.36.8/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/oron/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
	from /Users/oron/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.63.1/bin/fastlane:162:in `<top (required)>'
	from /Users/oron/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `load'
	from /Users/oron/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `<main>'
	from /Users/oron/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/oron/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Fastfile:
```ruby
  lane :upload_s3 do

    # build

    version = get_version_number(xcodeproj: "DriverBox.xcodeproj")

    s3(
      access_key: ENV['S3_ACCESS_KEY'],               # Required from user.
      secret_access_key: ENV['S3_SECRET_ACCESS_KEY'], # Required from user.
      bucket: ENV['S3_BUCKET'],                       # Required from user.
      ipa: "./Dist/DriverApp-v#{version}.ipa",
      region: 'eu-west-1',
      path: "driverbox/DriverBox-iOS/test_version_#{version}/",
			html_template_path: './fastlane/templates/s3_html_template.erb',
			plist_template_path: './fastlane/templates/s3_plist_template.erb'
   )

  end
```

### Environment

fastlane version (fastlane -v): fastlane 1.63.1
Do you use bundler, rbenv or rvm? No

**Comment by oronbz** [comment]
Note: the file and plist actually uploaded regardless of the error thrown.
