### ISSUE TITLE
iTMSTransporter completed with a non-zero exit status: 1

### ISSUE THREAD

**Issue by sardzoski** [fastlane/fastlane#14343]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
upload_to_testflight fails because of a iTMSTransporter error

#### Question Description
I'm trying to upload a build to TestFlight, but the lane upload_to_testflight fails with the following error. I'm trying to do this on a Jenkins CI machine (it that helps you in any way)
Also this was not happening before I added itc_provider. I got the itc_provider using the following command 
"/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter -m provider -u 'xxxxxx@xxxxxx.com' -p 'xxxxxx' -account_type itunes_connect -v off"

This is what is in my Fastfile:
 upload_to_testflight(
      ipa: "xxxxx.ipa",
      skip_submission: true,
      distribute_external: false,
      itc_provider: "xxxxx",
      skip_waiting_for_build_processing: true
    )

This is the output:
[15:29:17]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[15:29:20]: [32m------------------------------[0m
[15:29:20]: [32m--- Step: default_platform ---[0m
[15:29:20]: [32m------------------------------[0m
[15:29:20]: [32mDriving the lane 'ios deliver_prod' 🚀[0m
[15:29:20]: [32m----------------------------------[0m
[15:29:20]: [32m--- Step: upload_to_testflight ---[0m
[15:29:20]: [32m----------------------------------[0m
[15:29:20]: Login to App Store Connect (xxxxxx@xxxxxx.com)
[15:29:22]: Login successful
[15:29:23]: [32mReady to upload new build to TestFlight (App: xxxxxx)...[0m
[15:29:50]: Going to upload updated app to App Store Connect
[15:29:50]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
[15:29:51]: [33m[iTMSTransporter] java.lang.reflect.InvocationTargetException
[0m
[15:29:51]: [33m[iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[0m
[15:29:51]: [33m[iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[0m
[15:29:51]: [33m[iTMSTransporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[0m
[15:29:51]: [33m[iTMSTransporter] 	at java.lang.reflect.Method.invoke(Method.java:498)
[0m
[15:29:51]: [33m[iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:206)
[0m
[15:29:51]: [33m[iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:519)
[0m
[15:29:51]: [33m[iTMSTransporter] Caused by: java.lang.IllegalStateException: could not find needed OSGiFramework
[0m
[15:29:51]: [33m[iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapHelper.setupClassLoader(BootstrapHelper.java:160)
[0m
[15:29:51]: [33m[iTMSTransporter] 	at com.apple.transporter.osgi.FelixOSGiBootstrapper.bootstrap(FelixOSGiBootstrapper.java:39)
[0m
[15:29:51]: [33m[iTMSTransporter] 	... 6 more
[0m
[15:29:51]: iTunes Transporter output above ^
[15:29:51]: [31mThe call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m
+------------------+------------------+
|            [33mLane Context[0m             |
+------------------+------------------+
| DEFAULT_PLATFORM | ios              |
| PLATFORM_NAME    | ios              |
| LANE_NAME        | ios deliver_prod |
+------------------+------------------+
[15:29:51]: [31mError uploading ipa file, for more information see above[0m

+------+----------------------+-------------+
|             [32mfastlane summary[0m              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 💥   | [31mupload_to_testflight[0m | 31          |
+------+----------------------+-------------+

[15:29:51]: [31mfastlane finished with errors[0m
[31m
[!] Error uploading ipa file, for more information see above[0m

Note: This didn't help
ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

**Comment by mgrebenets** [comment]
Have you tried to enable verbose output for the upload action? It should have more info in the output that way. Probably will help to pin point the actual error
