### ISSUE TITLE
`commit_version_bump` Error with uncommitted changes in working directory: .app.dSYM.zip file

### ISSUE THREAD

**Issue by timcamber** [fastlane/fastlane#1438]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`commit_version_bump` fails because it finds unexpected uncommitted changes in my working directory, namely, the `MyAppName.app.dSYM.zip` file. I'm not sure why this should be the case and similar setups (if memory serves) have worked fine.

##### Complete output when running fastlane, including the stack trace and command used

Run fastlane with `fastlane beta`. Everything works fine until the `after_all` loop when `commit_version_bump` is invoked. This is the output from this point onwards:
```
[10:51:58]: Variable Dump:
[10:51:58]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :GIT_REPO_WAS_CLEAN_ON_START=>true, :BUILD_NUMBER=>"18", :VERSION_NUMBER=>"1.0", :IPA_OUTPUT_PATH=>"/Users/timcamber/Documents/FTW/wargame/Wargame.ipa", :DSYM_OUTPUT_PATH=>"/Users/timcamber/Documents/FTW/wargame/Wargame.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/timcamber/Library/Developer/Xcode/Archives/2016-02-29/Wargame 2016-02-29 10.28.32.xcarchive"}
[10:51:58]: Found unexpected uncommited changes in the working directory. Expected these files to have 
changed: 
Wargame.xcodeproj/project.pbxproj
Wargame/Info.plist
WargameTests/Info.plist
Wargame Editor/Info.plist.
But found these actual changes: 
Wargame Editor/Info.plist
Wargame.xcodeproj/project.pbxproj
Wargame/Info.plist
WargameTests/Info.plist
Wargame.app.dSYM.zip.
Make sure you have cleaned up the build artifacts and 
are only left with the changed version files at this stage in your lane, and don't touch the 
working directory while your lane is running. You can also use the :force option to bypass this 
check, and always commit a version bump regardless of the state of the working directory.

+------+-------------------------+-------------+
|               fastlane summary               |
+------+-------------------------+-------------+
| Step | Action                  | Time (in s) |
+------+-------------------------+-------------+
| 1    | default_platform        | 0           |
| 2    | ensure_git_status_clean | 0           |
| 3    | increment_build_number  | 2           |
| 4    | get_version_number      | 1           |
| 5    | get_build_number        | 1           |
| 6    | gym                     | 108         |
| 7    | pilot                   | 1300        |
| 8    | commit_version_bump     | 0           |
| 9    | clean_build_artifacts   | 0           |
| 10   | reset_git_repo          | 0           |
| 11   | slack                   | 0           |
+------+-------------------------+-------------+

[10:51:58]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '164efc61cd02654c9bd4876f51fe5912'
The crash report has been stored locally '/tmp/sentry_164efc61cd02654c9bd4876f51fe5912.json'
/Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/commit_version_bump.rb:82:in `run': [!] Found unexpected uncommited changes in the working directory. Expected these files to have  (RuntimeError)
changed: 
Wargame.xcodeproj/project.pbxproj
Wargame/Info.plist
WargameTests/Info.plist
Wargame Editor/Info.plist.
But found these actual changes: 
Wargame Editor/Info.plist
Wargame.xcodeproj/project.pbxproj
Wargame/Info.plist
WargameTests/Info.plist
Wargame.app.dSYM.zip.
Make sure you have cleaned up the build artifacts and 
are only left with the changed version files at this stage in your lane, and don't touch the 
working directory while your lane is running. You can also use the :force option to bypass this 
check, and always commit a version bump regardless of the state of the working directory.
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:24:in `block (2 levels) in parsing_binding'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:56:in `call'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:56:in `block in execute'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane_core-0.36.8/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:162:in `<top (required)>'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/bin/fastlane:23:in `load'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby

default_platform :ios

platform :ios do
  version = nil
  build_number = nil

  before_all do
    ENV["SLACK_URL"] = SLACK_HOOK_URL

    ensure_git_status_clean
    increment_build_number

    version = get_version_number(xcodeproj: "Wargame.xcodeproj")
    build_number = get_build_number(xcodeproj: "Wargame.xcodeproj")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(scheme: "Wargame Beta", use_legacy_build_api: true)
    pilot
  end

  after_all do |lane|
    commit_version_bump
    tag_string = lane + "/" + version + "(" + build_number + ")"
    add_git_tag(tag: tag_string)

    push_to_git_remote
    clean_build_artifacts
    reset_git_repo

    slack(
      message: "Successfully deployed update to Wargame"
    )
  end

  error do |lane, exception|
    clean_build_artifacts
    reset_git_repo
    
    slack(
      message: exception.message,
      success: false
    )
  end
end


```

### Environment

fastlane version (fastlane -v):
`fastlane 1.63.1`

Do you use bundler, rbenv or rvm?
`rbenv`

**Comment by lacostej** [comment]
Hello @timcamber have you tried adding `wargame.app.dSYM.zip` to your .gitignore ?

**Comment by dusek** [comment]
I use `clean_build_artifacts` before `commit_version_bump`.

**Comment by ohwutup** [comment]
Going to close this issue as @lacostej and @dusek have both called out some good solutions/work arounds! Thanks!!
