### ISSUE TITLE
Crashlytics halted compilation because it can't extract Crashlytics build info from the APK

### ISSUE THREAD

**Issue by charafau** [fastlane/fastlane#14507]
Hello I got a problem with Android upload to crashlytics, project compiles normally and it was working before, but now I have some problems when I upgraded project to new build tools `28.0.3` and to AndroidX, here's my output:

### Issue Description

Upload to crashlytics fails because with error:

```
Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: ../app/build/outputs/apk/app-release.apk
```

##### Command executed
`fastlane beta_develop`

which goes to:

```
crashlytics(
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_API_SECRET'],
      apk_path: '../build/app/outputs/apk/release/app-release.apk',
      notes_path: '../release-notes.txt',
      groups: 'my-group',
      notifications: false
    )
```

##### Complete output when running fastlane, including the stack trace and command used

```
[17:29:53]:  WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/user/builds/e56a3751/0/user/project/build/app/outputs/apk/release/app-release.apk
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/user/builds/e56a3751/0/user/project/build/app/outputs/apk/release/app-release.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
```

### Environment

```

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.1        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
```

Thank you!

**Comment by gmcdowell** [comment]
same issue here too

**Comment by yerayrm** [comment]
I have the same problem...

**Comment by zanuka** [comment]
same here

any updates on this issue by fastlane or crashlytics?

**Comment by janpio** [comment]
This sounds like a problem of Crashlytics, not of Fastlane - if their CLI can't handle a file, there is unfortunately nothing fastlane can do about it. You should contact the Crashlytics people about this.

**Comment by pjanuario** [comment]
Also facing the same problem, here. :/

**Comment by janpio** [comment]
Any update on this or even feedback from Crashlytics @charafau @gmcdowell @yerayrm @zanuka @pjanuario?

**Comment by pjanuario** [comment]
Indeed I had this problem but now it's working, to be honest I can't recall what I did.
