### ISSUE TITLE
Compilation Error Execution failed for task ':app:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by Dark7SiD** [fastlane/fastlane#14539]
When trying to make a beta version on Crashlytics using Fastlane  

##### Command executed
fastlane beta

##### Complete output when running fastlane, including the stack trace and command used

```
 [✔] 🚀
[12:55:54]: fastlane detected a Gemfile in the current directory
[12:55:54]: however it seems like you don't use `bundle exec`
[12:55:54]: to launch fastlane faster, please use
[12:55:54]:
[12:55:54]: $ bundle exec fastlane beta
[12:55:54]:
[12:55:54]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:55:54]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[12:55:55]: ------------------------------
[12:55:55]: --- Step: default_platform ---
[12:55:55]: ------------------------------
[12:55:55]: Driving the lane 'android beta' 🚀
[12:55:55]: --------------------
[12:55:55]: --- Step: gradle ---
[12:55:55]: --------------------
[12:55:55]: $ C:/Users/bahaa/AndroidStudioProjects/brandatt/AndroidNewBrandatt/gradlew clean assembleRelease -p .
[12:55:56]: ▸ > Configure project :app
[12:55:56]: ▸ WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
[12:55:56]: ▸ Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!
[12:55:56]: ▸ Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
[12:55:56]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[12:55:56]: ▸ Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
[12:55:56]: ▸ registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[12:55:56]: ▸ > Task :clean UP-TO-DATE
[12:55:57]: ▸ > Task :app:clean
[12:55:57]: ▸ > Task :expandablelayout:clean
[12:55:57]: ▸ > Task :app:preBuild UP-TO-DATE
[12:55:57]: ▸ > Task :expandablelayout:preBuild UP-TO-DATE
[12:55:57]: ▸ > Task :expandablelayout:preReleaseBuild UP-TO-DATE
[12:55:57]: ▸ > Task :expandablelayout:checkReleaseManifest
[12:55:57]: ▸ > Task :expandablelayout:processReleaseManifest
[12:56:09]: ▸ > Task :app:preReleaseBuild
[12:56:09]: ▸ > Task :expandablelayout:compileReleaseAidl NO-SOURCE
[12:56:09]: ▸ > Task :app:compileReleaseAidl NO-SOURCE
[12:56:09]: ▸ > Task :expandablelayout:packageReleaseRenderscript NO-SOURCE
[12:56:09]: ▸ > Task :app:compileReleaseRenderscript
[12:56:09]: ▸ > Task :app:checkReleaseManifest
[12:56:09]: ▸ > Task :app:generateReleaseBuildConfig
[12:56:09]: ▸ > Task :app:prepareLintJar UP-TO-DATE
[12:56:09]: ▸ > Task :app:generateReleaseSources
[12:56:09]: ▸ > Task :app:dataBindingExportBuildInfoRelease
[12:56:09]: ▸ > Task :app:dataBindingExportFeaturePackageIdsRelease
[12:56:09]: ▸ > Task :app:dataBindingMergeDependencyArtifactsRelease
[12:56:09]: ▸ > Task :app:mergeReleaseShaders
[12:56:09]: ▸ > Task :app:compileReleaseShaders
[12:56:09]: ▸ > Task :app:generateReleaseAssets
[12:56:09]: ▸ > Task :expandablelayout:mergeReleaseShaders
[12:56:09]: ▸ > Task :expandablelayout:compileReleaseShaders
[12:56:09]: ▸ > Task :expandablelayout:generateReleaseAssets
[12:56:09]: ▸ > Task :expandablelayout:packageReleaseAssets
[12:56:09]: ▸ > Task :app:mergeReleaseAssets
[12:56:09]: ▸ > Task :app:processReleaseGoogleServices
[12:56:09]: ▸ Parsing json file: C:\Users\bahaa\AndroidStudioProjects\brandatt\AndroidNewBrandatt\app\google-services.json
[12:56:09]: ▸ > Task :app:createReleaseCompatibleScreenManifests
[12:56:09]: ▸ > Task :app:mainApkListPersistenceRelease
[12:56:09]: ▸ > Task :app:processReleaseManifest
[12:56:09]: ▸ > Task :app:fabricGenerateResourcesRelease
[12:56:09]: ▸ > Task :app:generateReleaseResValues
[12:56:09]: ▸ > Task :app:generateReleaseResources
[12:56:09]: ▸ > Task :expandablelayout:compileReleaseRenderscript
[12:56:09]: ▸ > Task :expandablelayout:generateReleaseResValues
[12:56:09]: ▸ > Task :expandablelayout:generateReleaseResources
[12:56:09]: ▸ > Task :expandablelayout:packageReleaseResources
[12:56:14]: ▸ C:\Users\bahaa\AndroidStudioProjects\brandatt\AndroidNewBrandatt\app\build\intermediates\incremental\mergeReleaseResources\merged.dir\values-ar\values-ar.xml:777: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
[12:56:14]: ▸ C:\Users\bahaa\AndroidStudioProjects\brandatt\AndroidNewBrandatt\app\build\intermediates\incremental\mergeReleaseResources\merged.dir\values\values.xml:1912: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
[12:56:18]: ▸ > Task :app:mergeReleaseResources
[12:56:18]: ▸ > Task :app:transformDataBindingBaseClassLogWithDataBindingMergeGenClassesForRelease
[12:56:18]: ▸ > Task :app:dataBindingGenBaseClassesRelease
[12:56:18]: ▸ > Task :expandablelayout:generateReleaseBuildConfig
[12:56:18]: ▸ > Task :expandablelayout:generateReleaseRFile
[12:56:18]: ▸ > Task :expandablelayout:prepareLintJar UP-TO-DATE
[12:56:18]: ▸ > Task :expandablelayout:generateReleaseSources
[12:56:18]: ▸ > Task :expandablelayout:javaPreCompileRelease
[12:56:19]: ▸ > Task :expandablelayout:compileReleaseJavaWithJavac
[12:56:19]: ▸ warning: [options] source value 7 is obsolete and will be removed in a future release
[12:56:19]: ▸ warning: [options] target value 7 is obsolete and will be removed in a future release
[12:56:19]: ▸ warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
[12:56:19]: ▸ 3 warnings
[12:56:19]: ▸ > Task :expandablelayout:processReleaseJavaRes NO-SOURCE
[12:56:19]: ▸ > Task :expandablelayout:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
[12:56:19]: ▸ > Task :app:javaPreCompileRelease
[12:56:20]: ▸ warn: removing resource com.brandat.brandat:string/com_facebook_loginview_logged_in_using_facebook_f1gender without required default value.
[12:56:21]: ▸ > Task :app:processReleaseResources
[12:56:22]: ▸ > Task :app:compileReleaseJavaWithJavac FAILED
[12:56:22]: ▸ Gradle may disable incremental compilation as the following annotation processors are not incremental: butterknife-compiler-8.8.1.jar (com.jakewharton:butterknife-compiler:8.8.1), compiler-4.8.0.jar (com.github.bumptech.glide:compiler:4.8.0), databinding-compiler-3.3.0.jar (androidx.databinding:databinding-compiler:3.3.0).
[12:56:22]: ▸ Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
[12:56:22]: ▸ FAILURE: Build failed with an exception.
[12:56:22]: ▸ * What went wrong:
[12:56:22]: ▸ Execution failed for task ':app:compileReleaseJavaWithJavac'.
[12:56:22]: ▸ > javax/xml/bind/JAXBException
[12:56:22]: ▸ * Try:
[12:56:22]: ▸ Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[12:56:22]: ▸ * Get more help at https://help.gradle.org
[12:56:22]: ▸ Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[12:56:22]: ▸ Use '--warning-mode all' to show the individual deprecation warnings.
[12:56:22]: ▸ See https://docs.gradle.org/5.3.1/userguide/command_line_interface.html#sec:command_line_warnings
[12:56:22]: ▸ BUILD FAILED in 26s
[12:56:22]: ▸ 40 actionable tasks: 37 executed, 3 up-to-date
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android beta |
+------------------+--------------+
[12:56:22]: Exit status of command 'C:/Users/bahaa/AndroidStudioProjects/brandatt/AndroidNewBrandatt/gradlew clean assembleRelease -p .' was 1 instead of 0.

> Configure project :app
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :clean UP-TO-DATE
> Task :app:clean
> Task :expandablelayout:clean
> Task :app:preBuild UP-TO-DATE
> Task :expandablelayout:preBuild UP-TO-DATE
> Task :expandablelayout:preReleaseBuild UP-TO-DATE
> Task :expandablelayout:checkReleaseManifest
> Task :expandablelayout:processReleaseManifest
> Task :app:preReleaseBuild
> Task :expandablelayout:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :expandablelayout:packageReleaseRenderscript NO-SOURCE
> Task :app:compileReleaseRenderscript
> Task :app:checkReleaseManifest
> Task :app:generateReleaseBuildConfig
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateReleaseSources
> Task :app:dataBindingExportBuildInfoRelease
> Task :app:dataBindingExportFeaturePackageIdsRelease
> Task :app:dataBindingMergeDependencyArtifactsRelease
> Task :app:mergeReleaseShaders
> Task :app:compileReleaseShaders
> Task :app:generateReleaseAssets
> Task :expandablelayout:mergeReleaseShaders
> Task :expandablelayout:compileReleaseShaders
> Task :expandablelayout:generateReleaseAssets
> Task :expandablelayout:packageReleaseAssets
> Task :app:mergeReleaseAssets

> Task :app:processReleaseGoogleServices
Parsing json file: C:\Users\bahaa\AndroidStudioProjects\brandatt\AndroidNewBrandatt\app\google-services.json

> Task :app:createReleaseCompatibleScreenManifests
> Task :app:mainApkListPersistenceRelease
> Task :app:processReleaseManifest
> Task :app:fabricGenerateResourcesRelease
> Task :app:generateReleaseResValues
> Task :app:generateReleaseResources
> Task :expandablelayout:compileReleaseRenderscript
> Task :expandablelayout:generateReleaseResValues
> Task :expandablelayout:generateReleaseResources
> Task :expandablelayout:packageReleaseResources
C:\Users\bahaa\AndroidStudioProjects\brandatt\AndroidNewBrandatt\app\build\intermediates\incremental\mergeReleaseResources\merged.dir\values-ar\values-ar.xml:777: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

C:\Users\bahaa\AndroidStudioProjects\brandatt\AndroidNewBrandatt\app\build\intermediates\incremental\mergeReleaseResources\merged.dir\values\values.xml:1912: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

> Task :app:mergeReleaseResources
> Task :app:transformDataBindingBaseClassLogWithDataBindingMergeGenClassesForRelease
> Task :app:dataBindingGenBaseClassesRelease
> Task :expandablelayout:generateReleaseBuildConfig
> Task :expandablelayout:generateReleaseRFile
> Task :expandablelayout:prepareLintJar UP-TO-DATE
> Task :expandablelayout:generateReleaseSources
> Task :expandablelayout:javaPreCompileRelease

> Task :expandablelayout:compileReleaseJavaWithJavac
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

> Task :expandablelayout:processReleaseJavaRes NO-SOURCE
> Task :expandablelayout:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
> Task :app:javaPreCompileRelease
warn: removing resource com.brandat.brandat:string/com_facebook_loginview_logged_in_using_facebook_f1gender without required default value.

> Task :app:processReleaseResources

> Task :app:compileReleaseJavaWithJavac FAILED
Gradle may disable incremental compilation as the following annotation processors are not incremental: butterknife-compiler-8.8.1.jar (com.jakewharton:butterknife-compiler:8.8.1), compiler-4.8.0.jar (com.github.bumptech.glide:compiler:4.8.0), databinding-compiler-3.3.0.jar (androidx.databinding:databinding-compiler:3.3.0).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> javax/xml/bind/JAXBException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.3.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 26s
40 actionable tasks: 37 executed, 3 up-to-date


+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | gradle           | 27          |
+------+------------------+-------------+

[12:56:22]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[12:56:23]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
Traceback (most recent call last):
        30: from C:/Ruby25-x64/bin/fastlane:23:in `<main>'
        29: from C:/Ruby25-x64/bin/fastlane:23:in `load'
        28: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/bin/fastlane:23:in `<top (required)>'
        27: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        26: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        25: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        24: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        23: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        22: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        21: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        20: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        19: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        18: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        17: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        15: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        12: from Fastfile:26:in `block (2 levels) in parsing_binding'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/actions/gradle.rb:52:in `run'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'C:/Users/bahaa/AndroidStudioProjects/brandatt/AndroidNewBrandatt/gradlew clean assembleRelease -p .' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

> Configure project :app
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :clean UP-TO-DATE
> Task :app:clean
> Task :expandablelayout:clean
> Task :app:preBuild UP-TO-DATE
> Task :expandablelayout:preBuild UP-TO-DATE
> Task :expandablelayout:preReleaseBuild UP-TO-DATE
> Task :expandablelayout:checkReleaseManifest
> Task :expandablelayout:processReleaseManifest
> Task :app:preReleaseBuild
> Task :expandablelayout:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :expandablelayout:packageReleaseRenderscript NO-SOURCE
> Task :app:compileReleaseRenderscript
> Task :app:checkReleaseManifest
> Task :app:generateReleaseBuildConfig
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateReleaseSources
> Task :app:dataBindingExportBuildInfoRelease
> Task :app:dataBindingExportFeaturePackageIdsRelease
> Task :app:dataBindingMergeDependencyArtifactsRelease
> Task :app:mergeReleaseShaders
> Task :app:compileReleaseShaders
> Task :app:generateReleaseAssets
> Task :expandablelayout:mergeReleaseShaders
> Task :expandablelayout:compileReleaseShaders
> Task :expandablelayout:generateReleaseAssets
> Task :expandablelayout:packageReleaseAssets
> Task :app:mergeReleaseAssets

> Task :app:processReleaseGoogleServices
Parsing json file: C:\Users\bahaa\AndroidStudioProjects\brandatt\AndroidNewBrandatt\app\google-services.json

> Task :app:createReleaseCompatibleScreenManifests
> Task :app:mainApkListPersistenceRelease
> Task :app:processReleaseManifest
> Task :app:fabricGenerateResourcesRelease
> Task :app:generateReleaseResValues
> Task :app:generateReleaseResources
> Task :expandablelayout:compileReleaseRenderscript
> Task :expandablelayout:generateReleaseResValues
> Task :expandablelayout:generateReleaseResources
> Task :expandablelayout:packageReleaseResources
C:\Users\bahaa\AndroidStudioProjects\brandatt\AndroidNewBrandatt\app\build\intermediates\incremental\mergeReleaseResources\merged.dir\values-ar\values-ar.xml:777: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

C:\Users\bahaa\AndroidStudioProjects\brandatt\AndroidNewBrandatt\app\build\intermediates\incremental\mergeReleaseResources\merged.dir\values\values.xml:1912: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

> Task :app:mergeReleaseResources
> Task :app:transformDataBindingBaseClassLogWithDataBindingMergeGenClassesForRelease
> Task :app:dataBindingGenBaseClassesRelease
> Task :expandablelayout:generateReleaseBuildConfig
> Task :expandablelayout:generateReleaseRFile
> Task :expandablelayout:prepareLintJar UP-TO-DATE
> Task :expandablelayout:generateReleaseSources
> Task :expandablelayout:javaPreCompileRelease

> Task :expandablelayout:compileReleaseJavaWithJavac
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

> Task :expandablelayout:processReleaseJavaRes NO-SOURCE
> Task :expandablelayout:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
> Task :app:javaPreCompileRelease
warn: removing resource com.brandat.brandat:string/com_facebook_loginview_logged_in_using_facebook_f1gender without required default value.

> Task :app:processReleaseResources

> Task :app:compileReleaseJavaWithJavac FAILED
Gradle may disable incremental compilation as the following annotation processors are not incremental: butterknife-compiler-8.8.1.jar (com.jakewharton:butterknife-compiler:8.8.1), compiler-4.8.0.jar (com.github.bumptech.glide:compiler:4.8.0), databinding-compiler-3.3.0.jar (androidx.databinding:databinding-compiler:3.3.0).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> javax/xml/bind/JAXBException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.3.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 26s
40 actionable tasks: 37 executed, 3 up-to-date
```

fastlane env

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.5.3                        |
| Bundler?                    | false                        |
| Git                         | git version 2.21.0.windows.1 |
| Installation Source         | C:/Ruby25-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/Ruby25-x64/lib            |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018   |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
     gradle(task: "clean assembleRelease")
    crashlytics(
    api_token: 'xxzxxx',
    build_secret: 'xxxxxx'
  )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("\com.brandat.brandat") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.2        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| openssl                   | 2.1.2        |
| fiddle                    | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-04-09**
</details>
[12:57:17]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[12:57:17]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
[12:57:17]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables

**Comment by tessmerandre** [comment]
Are you using Dagger2?

**Comment by janpio** [comment]
@Dark7SiD The error message indicates that your Android project can not be built with Gradle. Make sure the command `gradlew clean assembleRelease -p .` does succeed before building with Fastlane.
