### ISSUE TITLE
Spaceship Access to build_trains errors

### ISSUE THREAD

**Issue by zek** [fastlane/fastlane#14531]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

My app is published on testflight but I am getting this error. Therefore I cant do any further action like notifying slack or commiting to git 

##### Command executed

fastlane ios beta

##### Complete output when running fastlane, including the stack trace and command used

<details>

~~~
[00:53:40]: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/118630533/apps/1454700652/platforms/ios/trains. Reason:
<pre>    Gone</pre></p>
</body>
</html>


+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | Verifying fastlane version      | 0           |
| 2    | Switch to ios build lane        | 0           |
| 3    | Switch to ios certificates lane | 0           |
| 4    | match                           | 2           |
| 5    | match                           | 2           |
| 6    | increment_build_number          | 2           |
| 7    | cocoapods                       | 13          |
| 8    | gym                             | 346         |
| 💥    | pilot                           | 190         |
+------+---------------------------------+-------------+

[00:53:40]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/client.rb:321:in `handle_response': [!] <html> (Spaceship::UnexpectedResponse)
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/118630533/apps/1454700652/platforms/ios/trains. Reason:
<pre>    Gone</pre></p>
</body>
</html>

	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/client.rb:31:in `get_build_trains'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/build_trains.rb:16:in `all'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/build.rb:110:in `all'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/build.rb:121:in `all_processing_builds'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/build_watcher.rb:38:in `watching_build'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/build_watcher.rb:12:in `wait_for_build_processing_to_be_complete'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/pilot/lib/pilot/build_manager.rb:61:in `wait_for_build_processing_to_be_complete'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/pilot/lib/pilot/build_manager.rb:53:in `upload'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:48:in `block (2 levels) in parsing_binding'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/zack/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/zack/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.119.0/bin/fastlane:23:in `<top (required)>'
	from /Users/zack/.rvm/rubies/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/zack/.rvm/rubies/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/zack/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/zack/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
~~~

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.119.0'

ENV["FL_BUILD_NUMBER_PROJECT"] = "./ios/Clack.xcodeproj"
ENV["FL_COCOAPODS_PODFILE"] = "./ios/Podfile"


before_all do
  #ensure_git_branch
  #ensure_git_status_clean
  #git_pull
end

platform :ios do


    desc 'Sertifikaları ve Provisioning Profillerini yükler.'
    lane :certificates do
        match(type: 'development', readonly: true)
        match(type: 'appstore', readonly: true)
    end

    desc "App Store'a uygulama publish etmek için gereken ekran görüntülerini tüm dillerde ve tüm cihazlara göre oluşturur. "
    desc "Ayrıca, ekran görüntüsünü ilgili cihazın frame'inin içine alacak, ilgili başlıkları ekleyecektir."
    lane :screenshots do
        snapshot
        frameit(white: true, path: './fastlane/screenshots')
    end

    desc "Sadece metadata'yı yükler - ipa dosyası yüklenmeyecektir!"
    desc "Yükleme işleminden önce toplanan metadata özetini göreceksiniz."
    lane :upload_metadata do
        deliver(metadata_only: true)
    end

    desc 'iOS uygulamasını build eder.'
    private_lane :build do
        certificates
        increment_build_number(build_number: ENV['CI_BUILD_ID'])
        cocoapods()
        gym()
    end

    desc "Apple TestFlight için uygulamayı build alır, imzalar ve yükler."
    desc "Bütün testcilere mail gitmeyecektir. Sadece TestFlight'a yüklenecektir."
    lane :beta do
        build
        pilot
        commit_version_bump(message: 'Bump build')
        push_to_git_remote
        slack(message: "App successfully published on TestFlight!")
    end


    desc "AppStore için uygulamayı build alır, imzalar ve metadatayla birlikte yükler."
    desc "Aşağıdaki işlemler yapılacaktır:"
    desc ""
    desc "- Screenshotları `./fastlane/screenshots` klasörüne oluşturacaktır."
    desc "- Metadatayı `./fastlane/metadata` klasöründen toplayacaktır."
    desc "- Ekran görüntülerini ve metadata'yı yükleyecektir."
    desc "- Build alır, imzalar ve uygulamayı yükler."
    desc ""
    desc "Uygulamayı review için göndermeyecektir."

    lane :appstore do
        snapshot
        build_app
        deliver(
            skip_deploy: true,
            force: true
        )
    end

end

platform :android do
  # Android Lanes
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

app_identifier "com.clack" # The bundle identifier of your app

# apple_id "xxx@gmail.com" # Your Apple email address

team_id "FR4CK7ZM35"  # Developer Portal Team ID
itc_team_id "118630533"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 2.0.1        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| minitest                  | 5.8.4        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.6.1        |
| cocoapods-deintegrate     | 1.0.3        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.2.0        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| cocoapods                 | 1.6.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.0.15       |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.5.2        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-04-06**
</details>

**Comment by zek** [comment]
Duplicate of #14521
