### ISSUE TITLE
Pilot fails after package is successfully uploaded to iTunes Connect.

### ISSUE THREAD

**Issue by ecaselles** [fastlane/fastlane#1453]
### Issue Description

Recent changes on iTC compliance break pilot step. It finishes with the following error:
> You must provide an answer for this question.

Despite the pilot step being able to successfully upload and wait for Apple to process the build, it will fail with the above error without giving any more information.

##### Relevant output

```
[10:47:11]: -------------------
[10:47:11]: --- Step: pilot ---
[10:47:11]: -------------------
[10:47:11]: Login to iTunes Connect (<Apple ID>)
[10:47:19]: Login successful
[10:47:19]: Ready to upload new build to TestFlight (App: <app_id>)...
[10:47:19]: Going to upload updated app to iTunes Connect
[10:47:19]: This might take a few minutes, please don't interrupt the script
[10:47:22]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
[10:47:22]: [Transporter]: INFO: Logging configured successfully.
...
[10:47:51]: [Transporter]: DBG-X: Returning 0
[10:47:52]: ------------------------------------------------------------------------------------------------------
[10:47:52]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[10:47:52]: ------------------------------------------------------------------------------------------------------
[10:47:52]: Successfully uploaded the new binary to iTunes Connect
[10:47:52]: Waiting for iTunes Connect to process the new build
...
[11:03:11]: Waiting for iTunes Connect to process the new build
[11:03:41]: Waiting for iTunes Connect to finish processing the new build (2.2 - 91)
[11:03:41]: Successfully finished processing the build
[11:03:41]: You can now tweet:
[11:03:41]: iTunes Connect #iosprocessingtime 16 minutes
[11:03:41]: Distributing new build to testers

[11:08:02]: Variable Dump:
[11:08:02]: <Prints variables with right values.>

**[11:08:02]: You must provide an answer for this question.
**
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | increment_version_number            | 0           |
| 5    | Switch to ios build_app lane        | 0           |
| 6    | sigh                                | 5           |
| 7    | gym                                 | 59          |
| 8    | pilot                               | 1245        |
| 9    | is_ci                               | 0           |
| 10   | say                                 | 5           |
| 11   | clean_build_artifacts               | 0           |
| 12   | slack                               | 0           |
+------+-------------------------------------+-------------+

[11:08:02]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:221:in `handle_itc_response': [!] You must provide an answer for this question. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:541:in `update_build_trains!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.1/lib/spaceship/tunes/build_train.rb:118:in `update_testing_status!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.4.1/lib/pilot/build_manager.rb:124:in `distribute_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.4.1/lib/pilot/build_manager.rb:26:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:122:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.9/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

fastlane version (fastlane -v): 1.63.1
Not using bundler, rbenv nor rvm.

**Comment by ecaselles** [comment]
Ok, we have solved the issue now, but I will still post here what was causing it and how we fixed it in case it is helpful for someone else.

After debugging `Spaceship::TunesClient` in order to be able to log the response received from iTunes, we have just realised that the error `` comes from the `sectionErrorKeys` array. Causing Fastlane to fail the step, although the `statusCode` is returned as `SUCCESS`.

```
 {"data"=>
  {"sectionErrorKeys"=>["You must provide an answer for this question."],
   "sectionInfoKeys"=>[],
   "sectionWarningKeys"=>[],
   ...
  }
 "messages"=>{"warn"=>nil, "error"=>nil, "info"=>nil},
 "statusCode"=>"SUCCESS"}
```

Then, digging a bit more on the response, we realised that the `exportComplianceRequired` was set to `true` and the `exportComplianceState` was `missing`. At this point, if we go to iTC front-end (TestFlight tab), we see all the latest builds marked as _Missing compliance_.

Therefore, we have managed to solve the above issue, by specifying the following key `ITSAppUsesNonExemptEncryption` as `false` in the project's Info.plist to avoid having this issue.

In Apple words...
> If your encryption doesn't change, use the following key in your Info.plist so you don't have to provide export compliance information with your next build:
`<key>ITSAppUsesNonExemptEncryption</key><false/>`

:bulb: It might be worth making Fastlane aware of this behaviour, so it can propose the above solution when this situation happens.
