### ISSUE TITLE
Unable to upload screenshot for Appletvos and iOS at the same time

### ISSUE THREAD

**Issue by aniketgaur** [fastlane/fastlane#14547]
I am trying to upload screenshot for appletvos. my appletv screenshots are in ./screenshots/AppleTV/en-US/ . I have tried uploading these screenshot manually and faced no problem there. But with fastlane it fails with error of bad dimension with message "[!] App Store Connect error: Couldn't find device family for iphone6Plus ".

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
+--------------------------------------------------------------------+---------------------------+
|                                    deliver 2.120.0 Summary                                     |
+--------------------------------------------------------------------+---------------------------+
| force                                                              | true                      |
| team_id                                                            | ********                  |
| dev_portal_team_id                                                 | ********                  |
| username                                                           | ********                  |
| app_identifier                                                     | ********                  |
| overwrite_screenshots                                              | true                      |
| skip_metadata                                                      | true                      |
| skip_screenshots                                                   | false                     |
| price_tier                                                         | 0                         |
| platform                                                           | appletvos                 |
| app_version                                                        | 2                         |
| submit_for_review                                                  | true                      |
| build_number                                                       | latest                    |
| metadata_path                                                      | ./metadata                |
| edit_live                                                          | false                     |
| use_live_version                                                   | false                     |
| screenshots_path                                                   | ./screenshots/AppleTV     |
| skip_binary_upload                                                 | false                     |
| skip_app_version_update                                            | false                     |
| reject_if_possible                                                 | false                     |
| automatic_release                                                  | false                     |
| phased_release                                                     | false                     |
| reset_ratings                                                      | false                     |
| app_rating_config_path                                             | rating_config.json        |
| submission_information.add_id_info_tracks_install                  | true                      |
| submission_information.export_compliance_uses_encryption           | false                     |
| submission_information.export_compliance_encryption_updated        | false                     |
| submission_information.add_id_info_uses_idfa                       | true                      |
| submission_information.content_rights_contains_third_party_content | false                     |
| submission_information.content_rights_has_rights                   | true                      |
| submission_information.add_id_info_limits_tracking                 | true                      |
| run_precheck_before_submit                                         | true                      |
| precheck_default_rule_level                                        | warn                      |
| individual_metadata_items                                          | []                        |
| ignore_language_directory_validation                               | false                     |
| precheck_include_in_app_purchases                                  | true                      |
+--------------------------------------------------------------------+---------------------------+

[09:52:00]: Making sure the latest version on App Store Connect matches '2' from the ipa file...
[09:52:03]: '2' is the latest version on App Store Connect
[09:52:08]: Starting with the upload of screenshots...
[09:52:08]: Removing all previously uploaded screenshots...
[✔] Activating language en-US... 
[09:52:18]: Uploading 3 screenshots for language en-US
[09:52:18]: Uploading './screenshots/AppleTV/en-US/tv_cover_1553675298_7040513.png'...

Looking for related GitHub issues on fastlane/fastlane...

➡️  spaceship and deliver: add support for the 10.5" iPad
    https://github.com/fastlane/fastlane/pull/11330 [closed] 10 💬
    11 Mar 2018

➡️  IMG_BAD_DIMENSIONS error when updating IAP.
    https://github.com/fastlane/fastlane/issues/9390 [closed] 6 💬
    20 Oct 2017

➡️  In-App Purchase screenshots review error in spaceship
    https://github.com/fastlane/fastlane/issues/8348 [closed] 6 💬
    02 Aug 2017

and 1 more at: https://github.com/fastlane/fastlane/search?q=%5BIMG_BAD_DIMENSIONS%5D%20The%20image%20dimensions%20are%20not%20supported.%20Please%20adjust%20to%20acceptable%20dimensions%20and%20re-save%20it.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/spaceship/lib/spaceship/du/du_client.rb:172:in `parse_upload_response': [!] [IMG_BAD_DIMENSIONS] The image dimensions are not supported. Please adjust to acceptable dimensions and re-save it. (Spaceship::UnexpectedResponse)
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/spaceship/lib/spaceship/du/du_client.rb:96:in `upload_file'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/spaceship/lib/spaceship/du/du_client.rb:21:in `upload_screenshot'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/spaceship/lib/spaceship/tunes/tunes_client.rb:825:in `upload_screenshot'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/spaceship/lib/spaceship/tunes/app_version.rb:497:in `upload_screenshot!'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/upload_screenshots.rb:65:in `block (2 levels) in upload'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/upload_screenshots.rb:52:in `each'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/upload_screenshots.rb:52:in `block in upload'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/upload_screenshots.rb:50:in `each'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/upload_screenshots.rb:50:in `upload'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/runner.rb:121:in `upload_metadata'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/runner.rb:38:in `run'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/commands_generator.rb:94:in `block (2 levels) in run'
        from /Users/user1/.rvm/gems/ruby-2.2.3@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/user1/.rvm/gems/ruby-2.2.3@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/user1/.rvm/gems/ruby-2.2.3@global/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Users/user1/.rvm/gems/ruby-2.2.3@global/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /Users/user1/.rvm/gems/ruby-2.2.3@global/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        from /Users/user1/.rvm/gems/ruby-2.2.3/gems/fastlane-2.120.0/bin/fastlane:23:in `<top (required)>'
        from /Users/user1/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `load'
        from /Users/user1/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by janpio** [comment]
Hm, the error message you are seeing is what Apple is returning to your request.

Can you please check your spaceship logs at `/tmp/spaceship*.log` and post the request and repsonse that are failing?

What resolution are your screenshots?

Can you use `fastlane deliver init` for a Apple TV app that already has screenshots uploaded? Where does deliver put the downloaded screenshots?

**Comment by aniketgaur** [comment]
This is the output when I execute `fastlane deliver init`
<details>
  <pre> [11:53:23]: Login to App Store Connect (**********)
[11:53:27]: Login successful

+--------------------------------------+-----------------------+
|                   deliver 2.120.0 Summary                    |
+--------------------------------------+-----------------------+
| team_id                              | **********            |
| dev_portal_team_id                   | **********            |
| username                             | **********            |
| app_identifier                       | **********            |
| platform                             | appletvos             |
| run_precheck_before_submit           | false                 |
| screenshots_path                     | ./screenshots         |
| metadata_path                        | ./metadata            |
| edit_live                            | false                 |
| use_live_version                     | false                 |
| skip_binary_upload                   | false                 |
| skip_screenshots                     | false                 |
| skip_metadata                        | false                 |
| skip_app_version_update              | false                 |
| force                                | false                 |
| overwrite_screenshots                | false                 |
| submit_for_review                    | false                 |
| reject_if_possible                   | false                 |
| automatic_release                    | false                 |
| phased_release                       | false                 |
| reset_ratings                        | false                 |
| precheck_default_rule_level          | warn                  |
| individual_metadata_items            | []                    |
| ignore_language_directory_validation | false                 |
| precheck_include_in_app_purchases    | true                  |
+--------------------------------------+-----------------------+

[11:53:34]: Writing to './metadata/en-US/description.txt'
[11:53:34]: Writing to './metadata/en-US/keywords.txt'
[11:53:34]: Writing to './metadata/en-US/release_notes.txt'
[11:53:34]: Writing to './metadata/en-US/support_url.txt'
[11:53:34]: Writing to './metadata/en-US/marketing_url.txt'
[11:53:34]: Writing to './metadata/en-US/promotional_text.txt'
[11:53:34]: Writing to './metadata/en-US/name.txt'
[11:53:34]: Writing to './metadata/en-US/subtitle.txt'
[11:53:34]: Writing to './metadata/en-US/privacy_url.txt'
[11:53:34]: Writing to './metadata/copyright.txt'
[11:53:34]: Writing to './metadata/primary_category.txt'
[11:53:34]: Writing to './metadata/secondary_category.txt'
[11:53:34]: Writing to './metadata/primary_first_sub_category.txt'
[11:53:34]: Writing to './metadata/primary_second_sub_category.txt'
[11:53:34]: Writing to './metadata/secondary_first_sub_category.txt'
[11:53:34]: Writing to './metadata/secondary_second_sub_category.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/trade_name.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/first_name.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/last_name.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/address_line1.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/address_line2.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/address_line3.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/city_name.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/state.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/country.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/postal_code.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/phone_number.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/email_address.txt'
[11:53:34]: Writing to './metadata/trade_representative_contact_information/is_displayed_on_app_store.txt'
[11:53:34]: Writing to './metadata/review_information/first_name.txt'
[11:53:34]: Writing to './metadata/review_information/last_name.txt'
[11:53:34]: Writing to './metadata/review_information/phone_number.txt'
[11:53:34]: Writing to './metadata/review_information/email_address.txt'
[11:53:34]: Writing to './metadata/review_information/demo_user.txt'
[11:53:34]: Writing to './metadata/review_information/demo_password.txt'
[11:53:34]: Writing to './metadata/review_information/notes.txt'
[11:53:34]: Successfully created new configuration files.
[11:53:35]: Successfully downloaded large app icon
[11:53:37]: Successfully downloaded watch icon
[11:53:37]: Downloading all existing screenshots...
[11:53:39]: Downloading existing screenshot '1_iphone4_1.ftl_b47c015ae3dc4cfc2a0e164b2a25141d_86fef17afadddaeb57c488a068409e7c.png' for language 'en-US'
[11:53:41]: Downloading existing screenshot '2_iphone4_2.ftl_effd6a4fb75f996138b8e090b2fb3005_33a24b8d4faecccb8dcb5bbac8bb46b0.png' for language 'en-US'
[11:53:42]: Downloading existing screenshot '1_iphone6Plus_1.ftl_96a31f424c0a1f3d2526bd47425a0f5f_64ae89aacc59cb18924f513e5bf78097.png' for language 'en-US'
[11:53:44]: Downloading existing screenshot '2_iphone6Plus_2.ftl_96a31f424c0a1f3d2526bd47425a0f5f_10b5bb5d348319fc5684f060015e3e9d.png' for language 'en-US'
[11:53:46]: Downloading existing screenshot '1_iphone65_1.ftl_f519d2091200f15b8d780f8d38aa4210_fd798a5ce7bc9f0c53f31337bf3ad1dd.png' for language 'en-US'
[11:53:48]: Downloading existing screenshot '1_watch_1.ftl_6beb2f7aef5b9ff56e695441368b1364_37aa9d25f063b12de1eceac9ed1e1cec.png' for language 'en-US'
[11:53:49]: Downloading existing screenshot '1_iphone6_1.ftl_76da85603ad2359cb7db4eca0766f71c_ba83d280c40de29557835d621af7c715.png' for language 'en-US'
[11:53:50]: Downloading existing screenshot '2_iphone6_2.ftl_3f854a84dbb529ff3ff7d05eb30e5adc_14821b2e0f0e9d5635281cc5ae4be2a7.png' for language 'en-US'
[11:53:52]: Downloading existing screenshot '1_ipadPro_1.ftl_7a602d715e772bdfb17b6ada54ceea8d_ac9e7fbfabf8873f39ca38cf8b26123a.png' for language 'en-US'
[11:53:57]: Downloading existing screenshot '2_ipadPro_2.ftl_7a602d715e772bdfb17b6ada54ceea8d_734ef54be4e5bebcbc0bf730adb814a3.png' for language 'en-US'
[11:53:59]: Downloading existing screenshot '3_ipadPro_3.ftl_24adf1c268b876a1f93f248e928441c1_8f3e8c89b4de1c4118f0d199e7970b73.png' for language 'en-US'
[11:54:06]: Successfully downloaded all existing screenshots
[11:54:06]: Successfully created new Deliverfile at path './Deliverfile'
 </pre>
</details>

It downloads screenshots from my ios setup only. But on appstoreconnect I had manually uploaded screenshots for appletv  and it did not download them. So I added them at directory ./screenshots/AppleTV/en-US. I have tried` fastlane deliver submit_build ` with two scenarios keeping ios screenshots and appletv screenshots and only keeping appletv screenshots. In both cases it fails 

![Screen Shot 2019-04-11 at 12 08 20 PM](https://user-images.githubusercontent.com/44966189/55935962-8a5dfd80-5c52-11e9-891d-612b90854c0a.png)

<details>
<pre>
[12:15:38]: Login to App Store Connect (**********)
[12:15:42]: Login successful

+--------------------------------------+-----------------------+
|                   deliver 2.120.0 Summary                    |
+--------------------------------------+-----------------------+
| force                                | true                  |
| team_id                              | **********            |
| dev_portal_team_id                   | **********            |
| username                             | **********            |
| app_identifier                       | **********            |
| overwrite_screenshots                | true                  |
| skip_metadata                        | true                  |
| skip_screenshots                     | false                 |
| price_tier                           | 0                     |
| platform                             | appletvos             |
| app_version                          | 2                     |
| submit_for_review                    | true                  |
| build_number                         | latest                |
| screenshots_path                     | ./screenshots         |
| metadata_path                        | ./metadata            |
| edit_live                            | false                 |
| use_live_version                     | false                 |
| skip_binary_upload                   | false                 |
| skip_app_version_update              | false                 |
| reject_if_possible                   | false                 |
| automatic_release                    | false                 |
| phased_release                       | false                 |
| reset_ratings                        | false                 |
| run_precheck_before_submit           | true                  |
| precheck_default_rule_level          | warn                  |
| individual_metadata_items            | []                    |
| ignore_language_directory_validation | false                 |
| precheck_include_in_app_purchases    | true                  |
+--------------------------------------+-----------------------+

[12:15:46]: Making sure the latest version on App Store Connect matches '2' from the ipa file...
[12:16:08]: Successfully set the version to '2'
[12:16:18]: Starting with the upload of screenshots...
[12:16:18]: Removing all previously uploaded screenshots...
[✔] Activating language en-US...
[12:16:43]: Uploading 11 screenshots for language en-US
[12:16:43]: Uploading './screenshots/en-US/1_ipadPro_1.ftl_7a602d715e772bdfb17b6ada54ceea8d_ac9e7fbfabf8873f39ca38cf8b26123a.png'...
[12:17:14]: Uploading './screenshots/en-US/1_iphone4_1.ftl_b47c015ae3dc4cfc2a0e164b2a25141d_86fef17afadddaeb57c488a068409e7c.png'...
[12:17:23]: Uploading './screenshots/en-US/1_iphone65_1.ftl_f519d2091200f15b8d780f8d38aa4210_fd798a5ce7bc9f0c53f31337bf3ad1dd.png'...
[12:17:38]: Uploading './screenshots/en-US/1_iphone6Plus_1.ftl_96a31f424c0a1f3d2526bd47425a0f5f_64ae89aacc59cb18924f513e5bf78097.png'...
[12:17:51]: Uploading './screenshots/en-US/1_iphone6_1.ftl_76da85603ad2359cb7db4eca0766f71c_ba83d280c40de29557835d621af7c715.png'...
[12:18:04]: Uploading './screenshots/en-US/1_watch_1.ftl_6beb2f7aef5b9ff56e695441368b1364_37aa9d25f063b12de1eceac9ed1e1cec.png'...
[12:18:09]: Uploading './screenshots/en-US/2_ipadPro_2.ftl_7a602d715e772bdfb17b6ada54ceea8d_734ef54be4e5bebcbc0bf730adb814a3.png'...
[12:18:41]: Uploading './screenshots/en-US/2_iphone4_2.ftl_effd6a4fb75f996138b8e090b2fb3005_33a24b8d4faecccb8dcb5bbac8bb46b0.png'...
[12:18:51]: Uploading './screenshots/en-US/2_iphone6Plus_2.ftl_96a31f424c0a1f3d2526bd47425a0f5f_10b5bb5d348319fc5684f060015e3e9d.png'...
[12:19:10]: Uploading './screenshots/en-US/2_iphone6_2.ftl_3f854a84dbb529ff3ff7d05eb30e5adc_14821b2e0f0e9d5635281cc5ae4be2a7.png'...
[12:19:18]: Uploading './screenshots/en-US/3_ipadPro_3.ftl_24adf1c268b876a1f93f248e928441c1_8f3e8c89b4de1c4118f0d199e7970b73.png'...
[✔] Saving changes
[12:20:29]: Successfully uploaded screenshots to App Store Connect
[12:20:32]: Price Tier unchanged (tier 0)
[12:20:34]: Uploading app icon...
[12:20:38]: Uploading apple watchapp icon...
[12:20:59]: Finished the upload to App Store Connect
[12:20:59]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[12:20:59]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+-----------------------+
|           Summary for precheck 2.120.0           |
+--------------------------+-----------------------+
| default_rule_level       | warn                  |
| include_in_app_purchases | true                  |
| app_identifier           | **********            |
| username                 | **********            |
+--------------------------+-----------------------+

[12:20:59]: Checking app for precheck rule violations
[12:21:14]: Reading in-app purchases. If you have a lot, this might take a while
[12:21:14]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[12:24:31]: Done reading in-app purchases
[12:24:37]: ✅  Passed: No negative  sentiment
[12:24:37]: ✅  Passed: No placeholder text
[12:24:37]: ✅  Passed: No mentioning  competitors
[12:24:37]: ✅  Passed: No future functionality promises
[12:24:37]: ✅  Passed: No words indicating test content
[12:24:37]: ✅  Passed: No curse words
[12:24:37]: ✅  Passed: No words indicating your IAP is free
[12:24:37]: ✅  Passed: Incorrect, or missing copyright date
[12:24:47]: ✅  Passed: No broken urls
[12:24:47]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[12:24:50]: Selecting the latest build...
[12:24:55]: Selecting build 1 (1)...
[12:25:16]: Successfully selected build
[12:25:16]: Submitting the app for review...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Deliver fails on every other locale when uploading screenshots
    https://github.com/fastlane/fastlane/issues/9859 [closed] 11 💬
    11 Dec 2017

➡️  Incorrect error message when trying to upload build while the app is in Waiting-for-review status [mac]
    https://github.com/fastlane/fastlane/issues/7905 [closed] 8 💬
    05 Sep 2017

➡️  Problem uploading screenshots with Deliver
    https://github.com/fastlane/fastlane/issues/9304 [closed] 7 💬
    31 Aug 2017

and 1 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09You%20must%20add%20at%20least%20one%20screenshot.%20%5Ben-US%5D%3A%20You%20must%20add%20at%20least%20one%20screenshot.%20There%20are%20one%20or%20more%20errors%20on%20the%20page.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
        You must add at least one screenshot. [en-US]: You must add at least one screenshot. There are one or more errors on the page.
</pre>
</details>
In above case It ignored AppleTV/en-US. 
Interestingly overwrite_screenshots is working, It removes all the screenshots at appstoreconnect for appletv. While uploading screenshots it uploads if for ios only.

<br>
I could not find /tmp/spaceship*.log.

Appletv screenshots are 1920 × 1080. I have manually tried them.

I feel it is a bug on fastlane deliver, because when there is no ios I had observed that it can upload screenshot for appletv. and when both ios and appletvos are present it is considering ios instead of appletv and giving bad dimension error.

**Comment by janpio** [comment]
Ok, so you think that fastlane can currently only handle iOS _or_ Apple TV screenshots, but not both at the same time?

**Comment by aniketgaur** [comment]
Yes. If both iOS and apple tv are there then  only iOS screenshots get uploaded.

**Comment by janpio** [comment]
You also discovered that it can not download screenshots for both iOS and Apple TV. Could you please check if it can download if you only have Apple TV screenshots, and none for iOS?

**Comment by aniketgaur** [comment]
For ios screenshot upload/download everything works fine with apple tv or without apple tv setup.
Problem I have observed is that, while uploading screenshots for apple tv if ios setup is already present then deilver fails to upload/download screenshots for apple tv.

I have tried the case where only apple tv is present

![Screen Shot 2019-04-11 at 9 26 34 PM](https://user-images.githubusercontent.com/44966189/55972126-8953bd00-5ca0-11e9-8e51-c0a6ccbd6a38.png)


output for `fastlane deliver setup`
<details>
<pre>
[21:17:02]: Login to App Store Connect (**********)
[21:17:05]: Login successful

+--------------------------------------+-------------------------+
|                    deliver 2.120.0 Summary                     |
+--------------------------------------+-------------------------+
| force                                | true                    |
| team_id                              | 2052991                 |
| dev_portal_team_id                   | **********              |
| username                             | **********              |
| app_identifier                       | **********              |
| skip_metadata                        | false                   |
| skip_screenshots                     | false                   |
| price_tier                           | 0                       |
| platform                             | appletvos               |
| app_version                          | 2                       |
| screenshots_path                     | ./screenshots           |
| metadata_path                        | ./metadata              |
| edit_live                            | false                   |
| use_live_version                     | false                   |
| skip_binary_upload                   | false                   |
| skip_app_version_update              | false                   |
| overwrite_screenshots                | false                   |
| submit_for_review                    | false                   |
| reject_if_possible                   | false                   |
| automatic_release                    | false                   |
| phased_release                       | false                   |
| reset_ratings                        | false                   |
| run_precheck_before_submit           | true                    |
| precheck_default_rule_level          | warn                    |
| individual_metadata_items            | []                      |
| ignore_language_directory_validation | false                   |
| precheck_include_in_app_purchases    | true                    |
+--------------------------------------+-------------------------+

[21:17:07]: Making sure the latest version on App Store Connect matches '2' from the ipa file...
[21:17:09]: '2' is the latest version on App Store Connect
[21:17:14]: Loading './metadata/en-US/description.txt'...
[21:17:14]: Loading './metadata/en-US/keywords.txt'...
[21:17:14]: Loading './metadata/en-US/release_notes.txt'...
[21:17:14]: Loading './metadata/en-US/support_url.txt'...
[21:17:14]: Loading './metadata/en-US/marketing_url.txt'...
[21:17:14]: Loading './metadata/en-US/promotional_text.txt'...
[21:17:14]: Loading './metadata/en-US/name.txt'...
[21:17:14]: Loading './metadata/en-US/subtitle.txt'...
[21:17:14]: Loading './metadata/en-US/privacy_url.txt'...
[21:17:14]: Loading './metadata/en-US/apple_tv_privacy_policy.txt'...
[21:17:14]: Loading './metadata/copyright.txt'...
[21:17:14]: Loading './metadata/primary_category.txt'...
[21:17:14]: Loading './metadata/secondary_category.txt'...
[21:17:14]: Loading './metadata/primary_first_sub_category.txt'...
[21:17:14]: Loading './metadata/primary_second_sub_category.txt'...
[21:17:14]: Loading './metadata/secondary_first_sub_category.txt'...
[21:17:14]: Loading './metadata/secondary_second_sub_category.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/trade_name.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/first_name.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/last_name.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/address_line1.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/address_line2.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/address_line3.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/city_name.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/state.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/country.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/postal_code.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/phone_number.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/email_address.txt'...
[21:17:14]: Loading './metadata/trade_representative_contact_information/is_displayed_on_app_store.txt'...
[21:17:14]: Loading './metadata/review_information/first_name.txt'...
[21:17:14]: Loading './metadata/review_information/last_name.txt'...
[21:17:14]: Loading './metadata/review_information/phone_number.txt'...
[21:17:14]: Loading './metadata/review_information/email_address.txt'...
[21:17:14]: Loading './metadata/review_information/demo_user.txt'...
[21:17:14]: Loading './metadata/review_information/demo_password.txt'...
[21:17:14]: Loading './metadata/review_information/notes.txt'...
[✔] Activating language en-US...
[✔] Uploading metadata to App Store Connect
[21:17:27]: Successfully uploaded set of metadata to App Store Connect
[21:17:29]: Starting with the upload of screenshots...
[✔] Activating language en-US...
[21:17:32]: Uploading 3 screenshots for language en-US
[21:17:32]: Uploading './screenshots/appleTV/en-US/tv_cover_1553675298_7040513.png'...
[21:18:05]: Uploading './screenshots/appleTV/en-US/tv_cover_1553675351_5076082.png'...
[21:18:17]: Uploading './screenshots/appleTV/en-US/tv_cover_1553675372_110112.png'...
[✔] Saving changes
[21:18:36]: Successfully uploaded screenshots to App Store Connect
[21:18:40]: Price Tier unchanged (tier 0)
[21:18:42]: Uploading app icon...
[21:18:45]: Uploading apple watchapp icon...
[21:18:53]: Finished the upload to App Store Connect
[21:18:53]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[21:18:53]: Running precheck 👮‍♀️ 👮

+--------------------------+-------------------------+
|            Summary for precheck 2.120.0            |
+--------------------------+-------------------------+
| default_rule_level       | warn                    |
| include_in_app_purchases | true                    |
| app_identifier           | **********              |
| username                 | **********              |
+--------------------------+-------------------------+

[21:18:53]: Checking app for precheck rule violations
[21:19:13]: Reading in-app purchases. If you have a lot, this might take a while
[21:19:13]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[21:19:14]: Done reading in-app purchases
[21:19:16]: ✅  Passed: No negative  sentiment
[21:19:16]: ✅  Passed: No placeholder text
[21:19:16]: ✅  Passed: No mentioning  competitors
[21:19:16]: ✅  Passed: No future functionality promises
[21:19:16]: ✅  Passed: No words indicating test content
[21:19:16]: ✅  Passed: No curse words
[21:19:16]: ✅  Passed: No words indicating your IAP is free
[21:19:16]: ✅  Passed: Incorrect, or missing copyright date
[21:19:20]: ✅  Passed: No broken urls
[21:19:20]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
</pre>
</details>

**Comment by aniketgaur** [comment]
I have solved this problem, https://github.com/aniketgaur/fastlane/commit/960d9c209f972bc8730141e09589b1cd5282cca0
