### ISSUE TITLE
[deliver] Incorrectly allows 5.5 inch screenshots @ native device resolution

### ISSUE THREAD

**Issue by liamnichols** [fastlane/fastlane#14585]
### Issue Description

Deliver has some validation and screenshot resolution detection logic that incorrectly thinks that iPhone 6/7/8 Plus screenshots at the devices native display resolution (1080x1920 pixels) are supported however when uploading such screenshot to via Spaceship, the following error is reported:

```
Spaceship::UnexpectedResponse: [!] [IMG_BAD_DIMENSIONS] The image dimensions are not supported. Please adjust to acceptable dimensions and re-save it.
```

For reference, the way that the @3x display on iPhone 6 Plus works is as follows: 

<img width="113" alt="Screenshot 2019-04-14 at 12 56 43" src="https://user-images.githubusercontent.com/482871/56092515-f50e7380-5eb4-11e9-87cf-bf4832dc9ab8.png">

Apples help documents say that only the following resolutions are supported:

```
1242 x 2208 pixels (portrait)
2208 x 1242 pixels (landscape)
```

##### Command executed
`bundle exec fastlane deliver`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>➜  ScreenshotTest be fastlane deliver
[✔] 🚀
[12:49:28]: Successfully loaded '/Users/liamnichols/Code/Local/ScreenshotTest/fastlane/Deliverfile' 📄

+----------------------------+------------------+
| Detected Values from './fastlane/Deliverfile' |
+----------------------------+------------------+
| force                      | false            |
| skip_binary_upload         | true             |
| skip_metadata              | true             |
| skip_app_version_update    | true             |
| overwrite_screenshots      | true             |
| run_precheck_before_submit | false            |
+----------------------------+------------------+

[12:49:28]: Login to App Store Connect (XXXXXXXXXX)
Available session is not valid any more. Continuing with normal login.
Session loaded from environment variable is not valid. Continuing with normal login.
[12:49:32]: Login successful

+--------------------------------------+----------------------------+
|                      deliver 2.120.0 Summary                      |
+--------------------------------------+----------------------------+
| screenshots_path                     | ./fastlane/screenshots     |
| metadata_path                        | ./fastlane/metadata        |
| username                             | XXXXXXXXXX   |
| app_identifier                       | XXXXXXXXXX |
| platform                             | ios                        |
| edit_live                            | false                      |
| use_live_version                     | false                      |
| skip_binary_upload                   | true                       |
| skip_screenshots                     | false                      |
| skip_metadata                        | true                       |
| skip_app_version_update              | true                       |
| force                                | false                      |
| overwrite_screenshots                | true                       |
| submit_for_review                    | false                      |
| reject_if_possible                   | false                      |
| automatic_release                    | false                      |
| phased_release                       | false                      |
| reset_ratings                        | false                      |
| team_id                              | XXXXXXXX                   |
| dev_portal_team_id                   | XXXXXXXXXX                 |
| run_precheck_before_submit           | false                      |
| precheck_default_rule_level          | warn                       |
| individual_metadata_items            | []                         |
| ignore_language_directory_validation | false                      |
| precheck_include_in_app_purchases    | true                       |
+--------------------------------------+----------------------------+

[12:49:34]: Unaccepted device screenshots are detected! 🚫 Screenshot file will be skipped. 🏃
[12:49:34]: 🏃 Skipping screenshot file: ./fastlane/screenshots/en-US/iPhone XR-0Launch.png - Not an accepted App Store Connect device...
[12:49:34]: 🏃 Skipping screenshot file: ./fastlane/screenshots/es-MX/iPhone XR-0Launch.png - Not an accepted App Store Connect device...
[12:49:38]: Verifying the upload via the HTML file can be disabled by either adding
[12:49:38]: `force true` to your Deliverfile or using `fastlane deliver --force`
[12:49:38]: Does the Preview on path './fastlane/Preview.html' look okay for you? (y/n)
y
[12:49:48]: HTML file confirmed...
[12:49:50]: Starting with the upload of screenshots...
[12:49:50]: Removing all previously uploaded screenshots...
[✔] Activating languages en-US, es-MX...
[12:49:55]: Uploading 5 screenshots for language en-US
[12:49:55]: Uploading './fastlane/screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-0Launch.png'...
[12:49:58]: Uploading './fastlane/screenshots/en-US/iPad Pro (12.9-inch)-0Launch.png'...
[12:50:01]: Uploading './fastlane/screenshots/en-US/iPhone 8 Plus-0Launch.png'...
[12:50:03]: Uploading './fastlane/screenshots/en-US/iPhone XS Max-0Launch.png'...
[12:50:05]: Uploading './fastlane/screenshots/en-US/iPhone8Plus-NativeResolution.png'...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Unable to upload screenshot for Appletvos and iOS at the same time
    https://github.com/fastlane/fastlane/issues/14547 [open] 8 💬
    a day ago

➡️  spaceship and deliver: add support for the 10.5" iPad
    https://github.com/fastlane/fastlane/pull/11330 [closed] 10 💬
    11 Mar 2018

➡️  IMG_BAD_DIMENSIONS error when updating IAP.
    https://github.com/fastlane/fastlane/issues/9390 [closed] 6 💬
    20 Oct 2017

and 2 more at: https://github.com/fastlane/fastlane/search?q=%5BIMG_BAD_DIMENSIONS%5D%20The%20image%20dimensions%20are%20not%20supported.%20Please%20adjust%20to%20acceptable%20dimensions%20and%20re-save%20it.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/liamnichols/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/fastlane)
Spaceship::UnexpectedResponse: [!] [IMG_BAD_DIMENSIONS] The image dimensions are not supported. Please adjust to acceptable dimensions and re-save it.
  /Users/liamnichols/Code/Github/fastlane/spaceship/lib/spaceship/du/du_client.rb:172:in `parse_upload_response'
  /Users/liamnichols/Code/Github/fastlane/spaceship/lib/spaceship/du/du_client.rb:96:in `upload_file'
  /Users/liamnichols/Code/Github/fastlane/spaceship/lib/spaceship/du/du_client.rb:21:in `upload_screenshot'
  /Users/liamnichols/Code/Github/fastlane/spaceship/lib/spaceship/tunes/tunes_client.rb:825:in `upload_screenshot'
  /Users/liamnichols/Code/Github/fastlane/spaceship/lib/spaceship/tunes/app_version.rb:497:in `upload_screenshot!'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/upload_screenshots.rb:65:in `block (2 levels) in upload'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/upload_screenshots.rb:52:in `each'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/upload_screenshots.rb:52:in `block in upload'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/upload_screenshots.rb:50:in `each'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/upload_screenshots.rb:50:in `upload'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/runner.rb:121:in `upload_metadata'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/runner.rb:38:in `run'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
  /Users/liamnichols/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/liamnichols/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/liamnichols/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/liamnichols/Code/Github/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/liamnichols/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/commands_generator.rb:182:in `run'
  /Users/liamnichols/Code/Github/fastlane/deliver/lib/deliver/commands_generator.rb:17:in `start'
  /Users/liamnichols/Code/Github/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /Users/liamnichols/Code/Github/fastlane/bin/fastlane:23:in `<top (required)>'
  /Users/liamnichols/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
  /Users/liamnichols/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre>N/A</pre>
</details>

**Comment by liamnichols** [comment]
FYI I am already working on a fix for this and a few other issues that I've spotted

**Comment by liamnichols** [comment]
Fix was merged and released 👍🏼
