### ISSUE TITLE
"invalid option: -f" on `krausefx-ipa distribute:s3` command

### ISSUE THREAD

**Issue by sundeepgupta** [fastlane/fastlane#1458]
Trying to get distribution to S3 going and running into this error. Below is the full error and stack trace. I'm using Fastlane v1.64.0. And Ruby v2.3.0.

I also noticed a couple of things. The help for `krausefx-ipa` doesn't mention and S3 option. And shenzhen gem can't find the aws-sdk file:

krausefx-ipa error and trace:
```
krausefx-ipa

  Build and distribute iOS apps (.ipa files)

  Commands:
    distribute:deploygate    Distribute an .ipa file over deploygate
    distribute:ftp           Distribute an .ipa file over FTP
    distribute:hockeyapp     Distribute an .ipa file over HockeyApp
    distribute:itunesconnect Upload an .ipa file to iTunes Connect
    distribute:rivierabuild  Distribute an .ipa file over RivieraBuild
    distribute:testfairy     Distribute an .ipa file over TestFairy
    help                     Display global or [command] help documentation

  Aliases:
    distribute:sftp distribute:ftp --protocol sftp

  Global Options:
    --verbose
    -h, --help           Display help documentation
    -v, --version        Display version information
    -t, --trace          Display backtrace when an error occurs

  Author:
    Mattt Thompson <m@mattt.me>

  Website:
    http://mattt.me


/Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- aws-sdk (LoadError)
        from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dev/.rvm/gems/ruby-2.3.0/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/plugins/s3.rb:1:in `<top (required)>'
        from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dev/.rvm/gems/ruby-2.3.0/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/commands.rb:9:in `<top (required)>'
        from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/dev/.rvm/gems/ruby-2.3.0/gems/krausefx-shenzhen-0.14.7/bin/krausefx-ipa:25:in `<top (required)>'
        from /Users/dev/.rvm/gems/ruby-2.3.0/bin/krausefx-ipa:23:in `load'
        from /Users/dev/.rvm/gems/ruby-2.3.0/bin/krausefx-ipa:23:in `<main>'
        from /Users/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Original error and trace:
```
/Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/interface.rb:120:in `crash!': [!] Exit status of command 'krausefx-ipa distribute:s3 -f "QA.ipa" -d "QA.app.dSYM.zip" -a "" -s "" -b "builds" -P "v{CFBundleShortVersionString}_b{CFBundleVersion}/"' was 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
invalid option: -f
/Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- aws-sdk (LoadError)
	from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/plugins/s3.rb:1:in `<top (required)>'
	from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/commands.rb:9:in `<top (required)>'
	from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/krausefx-shenzhen-0.14.7/bin/krausefx-ipa:25:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.3.0/bin/krausefx-ipa:23:in `load'
	from /Users/dev/.rvm/gems/ruby-2.3.0/bin/krausefx-ipa:23:in `<main>'
	from /Users/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/actions/s3.rb:81:in `run'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:83:in `block (2 levels) in parsing_binding'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:56:in `block in execute'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/bin/fastlane:156:in `run'
	from /Users/dev/.rvm/gems/ruby-2.3.0/gems/fastlane-1.64.0/bin/fastlane:162:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/dev/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by vpolouchkine** [comment]
krausefx-ipa is deprecated, you should try `gym`. :+1:

**Comment by sundeepgupta** [comment]
I should have mentioned that I'm using this `s3` action in my fastfile. If it matters, I also use `gym` to build the .ipa. 

How do I tell Fastlane to use `gym` for the `s3` action?

**Comment by oronbz** [comment]
I'm working on refactoring s3 action that would use the s3 sdk instead of krausefx-ipa command to upload the ipa. We'll link this issue.
@KrauseFx @sundeepgupta

**Comment by sundeepgupta** [comment]
Great, thanks!
