### ISSUE TITLE
/Users/**/.rvm/gems/ruby-2.4.1/gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!':

### ISSUE THREAD

**Issue by huipengo** [fastlane/fastlane#14603]
```
Xcode version: 10.2

/Users/**/.rvm/gems/ruby-2.4.1/gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'bundle exec pod lib lint --allow-warnings --use-libraries' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

nil versions are discouraged and will be deprecated in Rubygems 4
 -> **-configure (0.0.3)
    - WARN  | description: The description is shorter than the summary.
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: com.apple.coresimulator.simruntime.ios-10-3, com.apple.coresimulator.simruntime.ios-12-2, com.apple.coresimulator.simruntime.ios-9-3, com.apple.coresimulator.simruntime.tvos-12-2, com.apple.coresimulator.simruntime.watchos-5-2). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

```

**Comment by janpio** [comment]
Could you please create a new bug issue where you fill the issue template instead of deleting it? This is missing pretty much all necessary information. Thanks.
