### ISSUE TITLE
Cannot specify or inherit team_id from action latest_testflight_build_number

### ISSUE THREAD

**Issue by AndrewBarba** [fastlane/fastlane#1464]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
[10:58:01]: fastlane beta
[10:58:01]: Driving the lane 'beta' 🚀
[10:58:01]: --------------------------------------------
[10:58:01]: --- Step: latest_testflight_build_number ---
[10:58:01]: --------------------------------------------
[10:58:01]: You passed invalid parameters to 'latest_testflight_build_number'.
[10:58:01]: Check out the error below and available options by running `fastlane action latest_testflight_build_number`
[10:58:01]: Variable Dump:
[10:58:01]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"beta"}
[10:58:01]: Could not find option 'team_id' in the list of available options: app_identifier, username, version, initial_build_number
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby

lane :beta do

  increment_build_number(
    build_number: latest_testflight_build_number(team_id: "1234567") + 1
  )

  gym(
    workspace: "XXX.xcworkspace",
    scheme: "XXX Prod",
    clean: true
  )

  deliver(
    force: true,
  )

  commit_version_bump(
    message: 'Build Version Bump by Fastlane',
    force: true
  )

  push_to_git_remote
end

```
### Environment

fastlane version (fastlane -v): 1.64.0
Do you use bundler, rbenv or rvm?

**Comment by AndrewBarba** [comment]
The motivation for this issue is to prevent being prompt for a Team (I have multiple)

**Comment by jstubenrauch** [comment]
I would also very appreciate if this could be added. But I think what we need here is support for the itc_team_id not the team_id

**Comment by TKBurner** [comment]
@jstubenrauch Thanks for reaching out. We will look this over soon. Hope you hava a great weekend :+1:

**Comment by laksgandikota** [comment]
I ran into the same issue. Watching this thread.

**Comment by KrauseFx** [comment]
Nice catch, thanks everybody, I'll work on a fix 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/5668, which will be in the next release 🚀

**Comment by jlubeck** [comment]
After installing 1.100.0, fastlane just hangs on the latest_testflight_build_number step.

I tried running with verbose, but nothing shows up after 

```
INFO [2016-08-11 15:28:11.11]: --------------------------------------------
INFO [2016-08-11 15:28:11.11]: --- Step: latest_testflight_build_number ---
INFO [2016-08-11 15:28:11.11]: --------------------------------------------
```

**Comment by jlubeck** [comment]
Ok, when I finally canceled the execution, I got this back:

```
/Library/Ruby/Gems/2.0.0/gems/security-0.1.3/lib/security/password.rb:88:in ``': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/security-0.1.3/lib/security/password.rb:88:in `find'
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.16.0/lib/credentials_manager/account_manager.rb:27:in `password'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/latest_testflight_build_number.rb:14:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:177:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:34:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:248:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'


```

**Comment by jlubeck** [comment]
Ok, sorry about that. It was something to do with my Keychain. Although I second what @jstubenrauch said that itc_team_id should be used instead of team_id. As this is an Itunes Connect feature. 

Thanks!

**Comment by TKBurner** [comment]
Hi @jlubeck Thanks for following up on this. Are you still running into the issue after the fix? Thanks!

**Comment by jlubeck** [comment]
I'm waiting until I have to send a new build to TestFlight, should happen sometime between today and monday! Thanks!

**Comment by jlubeck** [comment]
Ok, it's still not taking the itc_team_id from the Appfile
Using fastlane 1.101.0

**Comment by TKBurner** [comment]
Hi @jlubeck Can you share the current output? I'd love to take a look. Thanks!

**Comment by jlubeck** [comment]
mmm, is this the output you mean?

```
[12:20:01]: --------------------------------------------
[12:20:01]: --- Step: latest_testflight_build_number ---
[12:20:01]: --------------------------------------------
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
1) "Fyra Studio SA" (343611)
2) "Gorilla Troop LLC" (118054640)
1
[12:20:36]: Fetching the latest build number for version 1.0
[12:20:39]: Latest upload is build number: 25
```

**Comment by Matthewspear** [comment]
Also running into this problem!
