### ISSUE TITLE
Malformed version number string undefined

### ISSUE THREAD

**Issue by turowicz** [fastlane/fastlane#14663]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
At the end of the gym task, everything finishes well and an `.ipa` file is created. After that I get the error.

##### Command executed
`fastlane ios build build_number:20180424.1`

##### Complete output when running fastlane, including the stack trace and command used
[17.txt](https://github.com/fastlane/fastlane/files/3112136/17.txt)

### Environment

```
[14:15:15]: fastlane detected a Gemfile in the current directory
[14:15:15]: however it seems like you don't use `bundle exec`
[14:15:15]: to launch fastlane faster, please use
[14:15:15]:
[14:15:15]: $ bundle exec fastlane env
[14:15:15]:
[14:15:15]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:15:21]: Generating fastlane environment output, this might take a few seconds...
[14:15:22]: It seems like you wanted to load some plugins, however they couldn't be loaded
[14:15:22]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_PL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

ruby
fastlane_version '2.119.0'

#before_all do
#  ensure_git_branch(branch: 'HEAD')
#  ensure_git_status_clean
#end

platform :ios do
   # iOS Lanes

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    get_certificates(username: 'service@varunit.com')
    get_provisioning_profile(username: 'service@varunit.com', app_identifier: 'com.varunit.prosoma')
  end

  desc 'Build the iOS application.'
  lane :build do |options|
    certificates
    increment_build_number(xcodeproj: './ios/Prosoma.xcodeproj', build_number: options[:build_number])
    gym(scheme: 'Prosoma', workspace: './ios/Prosoma.xcworkspace')
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot(username: 'service@varunit.com')
    #commit_version_bump(message: 'Bump build', xcodeproj: './ios/Prosoma.xcworkspace')
    #push_to_git_remote
  end
end

platform :android do
  # Android Lanes

  desc 'Build the Android application.'
  lane :build do |options|
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/', properties: { 'versCode' => options[:build_number], 'versName' => options[:build_name] })
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    #git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    #push_to_git_remote
  end
end


</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.121.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.2        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>


*generated on:* **2019-04-24**
</details>
[14:15:22]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.

Looking for related GitHub issues on fastlane/fastlane...

➡️  Malformed version number string undefined
    https://github.com/fastlane/fastlane/issues/14663 [open] 0 💬
    9 minutes ago

➡️  invalid byte sequence in UTF-8 when importing XLIFF files containing non UTF8 characters
    https://github.com/fastlane/fastlane/issues/12442 [closed] 3 💬
    05 Oct 2018

➡️   invalid byte sequence in US-ASCII (ArgumentError) Jenkins CI with Fastlane
    https://github.com/fastlane/fastlane/issues/12164 [closed] 6 💬
    04 Jun 2018

and 28 more at: https://github.com/fastlane/fastlane/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:730:in `gsub': [!] invalid byte sequence in US-ASCII (ArgumentError)
        from /Library/Ruby/Gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:730:in `format_statement'
        from /Library/Ruby/Gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:621:in `say'
        from /Library/Ruby/Gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:261:in `ask'
        from /Library/Ruby/Gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:227:in `agree'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `agree'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/environment_printer.rb:13:in `output'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:263:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:22:in `load'
        from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by turowicz** [comment]
Turns out I had to remove the unused plugin from PluginFile and everything if fine now.
