### ISSUE TITLE
cert fails with: Couldn't download certificate, got this instead: HTTP 405 Method Not Allowed

### ISSUE THREAD

**Issue by vlider** [fastlane/fastlane#1469]
When I run fastlane lane for submitting to internal beta testers(iOS), I'm getting this problem: `Couldn't download certificate, got this instead: HTTP 405 Method Not Allowed`
My lane script is pretty simple, I haven't changed anything since it was generated:
```
lane :production_server do
    sigh
    gym(scheme: "Production") # Build your app - more options available
    pilot
  end
```

So after cocoa pods and increment build number it fails on *cert*

##### Complete output when running fastlane, including the stack trace and command used

```
Valeriys-MacBook-Pro:Flashmob valerii$ fastlane
[23:52:38]: -------------------------------------------------
[23:52:38]: --- Step: Verifying required fastlane version ---
[23:52:38]: -------------------------------------------------
[23:52:38]: fastlane version valid
[23:52:38]: ------------------------------
[23:52:38]: --- Step: default_platform ---
[23:52:38]: ------------------------------
[23:52:38]: You must provide a lane to drive. Available lanes:
[23:52:38]: 1) ios test
[23:52:38]: 2) ios production_server
[23:52:38]: 3) ios development_server
[23:52:38]: 4) ios deploy
2
[23:52:39]: Driving the lane ios production_server. Next time launch fastlane using `fastlane ios production_server`
[23:52:39]: Driving the lane 'ios production_server' 🚀
[23:52:39]: -----------------------
[23:52:39]: --- Step: cocoapods ---
[23:52:39]: -----------------------
[23:52:39]: $ pod install
[23:52:40]: ▸ Updating local specs repositories
[23:52:43]: ▸ CocoaPods 1.0.0.beta.4 is available.
[23:52:43]: ▸ To update use: `gem install cocoapods --pre`
[23:52:43]: ▸ [!] This is a test version we'd love you to try.
[23:52:43]: ▸ For more information see http://blog.cocoapods.org
[23:52:43]: ▸ and the CHANGELOG for this version http://git.io/BaH8pQ.
[23:52:43]: ▸ Analyzing dependencies
[23:52:50]: ▸ Downloading dependencies
[23:52:50]: ▸ Using AFNetworkActivityLogger (2.0.4)
[23:52:50]: ▸ Using AFNetworking (2.6.3)
[23:52:50]: ▸ Using Bolts (1.6.0)
[23:52:50]: ▸ Using CCHMapClusterController (1.7.0)
[23:52:50]: ▸ Using CWStatusBarNotification (2.3.4)
[23:52:50]: ▸ Using CocoaLumberjack (2.2.0)
[23:52:50]: ▸ Using Crashlytics (3.7.0)
[23:52:50]: ▸ Using CustomBadge (3.0.0)
[23:52:50]: ▸ Using Digits (1.15.1)
[23:52:50]: ▸ Using FBSDKCoreKit (4.10.0)
[23:52:50]: ▸ Using FBSDKLoginKit (4.10.0)
[23:52:50]: ▸ Using FBSDKShareKit (4.10.0)
[23:52:50]: ▸ Using Fabric (1.6.6)
[23:52:50]: ▸ Using Flurry-iOS-SDK (7.5.1)
[23:52:50]: ▸ Using GoogleMaps (1.12.3)
[23:52:50]: ▸ Using JSONModel (1.2.0)
[23:52:50]: ▸ Using JSQMessagesViewController (7.2.0)
[23:52:50]: ▸ Using JSQSystemSoundPlayer (2.0.1)
[23:52:50]: ▸ Using SDWebImage (3.7.5)
[23:52:50]: ▸ Using SVProgressHUD (1.1.3)
[23:52:50]: ▸ Using SVWebViewController (1.0)
[23:52:50]: ▸ Using SlackTextViewController (1.8)
[23:52:50]: ▸ Using TTTAttributedLabel (1.13.4)
[23:52:50]: ▸ Using TWPhotoPicker (1.0.0)
[23:52:50]: ▸ Using TwitterCore (1.15.1)
[23:52:50]: ▸ Using TwitterKit (1.15.1)
[23:52:50]: ▸ Generating Pods project
[23:53:00]: ▸ Integrating client project
[23:53:02]: ▸ Sending stats
[23:53:02]: ▸ Pod installation complete! There are 24 dependencies from the Podfile and 26 total pods installed.
[23:53:02]: ------------------
[23:53:02]: --- Step: cert ---
[23:53:02]: ------------------

+---------------+-------------------------------------------------+
|                     Summary for cert 1.3.0                      |
+---------------+-------------------------------------------------+
| development   | false                                           |
| force         | false                                           |
| username      | hidden@hidden.com                                  |
| keychain_path | /Users/valerii/Library/Keychains/login.keychain |
+---------------+-------------------------------------------------+

[23:53:03]: Starting login with user 'hidden@hidden.com'
[23:53:05]: Successfully logged in
[23:53:08]: -------------------
[23:53:08]: --- Step: slack ---
[23:53:08]: -------------------
[23:53:10]: Successfully sent Slack notification
[23:53:10]: Variable Dump:
[23:53:10]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios production_server"}
[23:53:10]: Couldn't download certificate, got this instead: HTTP 405 Method Not Allowed

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 23          |
| 4    | cert                                | 5           |
| 5    | slack                               | 1           |
+------+-------------------------------------+-------------+

[23:53:10]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '39cacc269cd8ca88c284edd7cac3d2bf'
The crash report has been stored locally '/tmp/sentry_39cacc269cd8ca88c284edd7cac3d2bf.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/portal/portal_client.rb:311:in `download_certificate': [!] Couldn't download certificate, got this instead: HTTP 405 Method Not Allowed (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/portal/certificate.rb:298:in `download_raw'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.3.0/lib/cert/runner.rb:132:in `store_certificate'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.3.0/lib/cert/runner.rb:46:in `block in find_existing_cert'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.3.0/lib/cert/runner.rb:41:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.3.0/lib/cert/runner.rb:41:in `find_existing_cert'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.3.0/lib/cert/runner.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.3.0/lib/cert/runner.rb:6:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/actions/cert.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:43:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.41.1"

default_platform :ios


platform :ios do
  before_all do
    ENV["SLACK_URL"] = "slack url here"
    cocoapods
    
    increment_build_number

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    # snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :production_server do
    sigh
    gym(scheme: "Production") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :development_server do
    sigh
    gym(scheme: "Development") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    # snapshot
    sigh
    gym(scheme: "Production") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
```

### Environment
Mac OS X 10.11.3 (15D21)

fastlane version (fastlane -v): 1.64.0
Do you use bundler, rbenv or ram? NO

**Comment by KrauseFx** [comment]
Sorry about this, we already pushed a new version of spaceship: https://github.com/fastlane/spaceship/releases/tag/0.22.0. Please update using `sudo gem update spaceship` and let us know if that solves the issue :rocket:

**Comment by jlampa** [comment]
Yes, this does the trick - thanks for the quick reaction!

**Comment by JackieQi** [comment]
I still have this error. Any help please?
