### ISSUE TITLE
[spaceship] test_flight/build_trains.rb:43:in `block (2 levels) in all': [!] undefined method `[]' for nil:NilClass (NoMethodError) - after waiting for app processing

### ISSUE THREAD

**Issue by NxSoftware** [fastlane/fastlane#14696]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

An unknown error occurs after waiting for app processing while running the `pilot upload` command.

##### Command executed

```
fastlane pilot upload -u *** -i /Users/ci/Documents/Build-Agent/_work/r1/a/iOS.Release.Build/export/App.ipa --changelog Multi
line
what's new
text
-q ***TeamID Redacted*** -a ***Bundle ID Redacted***
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
2019-04-30T11:06:26.4478320Z [12:06:26]: Waiting for App Store Connect to finish processing the new build (8.6 - 201904300848)
2019-04-30T11:07:04.5542720Z [12:07:04]: Waiting for App Store Connect to finish processing the new build (8.6 - 201904300848)
2019-04-30T11:07:40.1424920Z [12:07:40]: Waiting for App Store Connect to finish processing the new build (8.6 - 201904300848)
2019-04-30T11:08:17.4020670Z [12:08:17]: Waiting for App Store Connect to finish processing the new build (8.6 - 201904300848)
2019-04-30T11:08:53.8210770Z 
2019-04-30T11:08:53.8211410Z Looking for related GitHub issues on fastlane/fastlane...
2019-04-30T11:08:53.8211610Z 
2019-04-30T11:08:54.9428050Z ➡️  [deliver] submit_build, promote build to production: undefined method `select_build' for nil:NilClass
2019-04-30T11:08:54.9428810Z     https://github.com/fastlane/fastlane/issues/13809 [open] 21 💬
2019-04-30T11:08:54.9431510Z     2 weeks ago
2019-04-30T11:08:54.9431640Z 
2019-04-30T11:08:54.9432490Z ➡️  fastlane pilot add: Error 410 Gone / 405 Method Not Allowed
2019-04-30T11:08:54.9433480Z     https://github.com/fastlane/fastlane/issues/14562 [open] 8 💬
2019-04-30T11:08:54.9433880Z     5 days ago
2019-04-30T11:08:54.9434000Z 
2019-04-30T11:08:54.9434700Z ➡️  Rate limit has been exceeded for: testflight|default|APPLE_CONNECT
2019-04-30T11:08:54.9435440Z     https://github.com/fastlane/fastlane/issues/12845 [open] 61 💬
2019-04-30T11:08:54.9435760Z     2 days ago
2019-04-30T11:08:54.9435890Z 
2019-04-30T11:08:54.9436570Z and 386 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓
2019-04-30T11:08:54.9436840Z 
2019-04-30T11:08:54.9437480Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
2019-04-30T11:08:54.9439320Z /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:43:in `block (2 levels) in all': [!] undefined method `[]' for nil:NilClass (NoMethodError)
2019-04-30T11:08:54.9440250Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:43:in `each'
2019-04-30T11:08:54.9441070Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:43:in `find'
2019-04-30T11:08:54.9441880Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:43:in `block in all'
2019-04-30T11:08:54.9442680Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:38:in `map'
2019-04-30T11:08:54.9443470Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:38:in `all'
2019-04-30T11:08:54.9444250Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build.rb:110:in `all'
2019-04-30T11:08:54.9445620Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/build_watcher.rb:38:in `matching_build'
2019-04-30T11:08:54.9446460Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/build_watcher.rb:16:in `block in wait_for_build_processing_to_be_complete'
2019-04-30T11:08:54.9447270Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/build_watcher.rb:15:in `loop'
2019-04-30T11:08:54.9448100Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/build_watcher.rb:15:in `wait_for_build_processing_to_be_complete'
2019-04-30T11:08:54.9448930Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/build_manager.rb:61:in `wait_for_build_processing_to_be_complete'
2019-04-30T11:08:54.9449700Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/build_manager.rb:53:in `upload'
2019-04-30T11:08:54.9450520Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
2019-04-30T11:08:54.9451310Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2019-04-30T11:08:54.9452080Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2019-04-30T11:08:54.9452860Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2019-04-30T11:08:54.9453660Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2019-04-30T11:08:54.9454440Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2019-04-30T11:08:54.9455200Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
2019-04-30T11:08:54.9456000Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
2019-04-30T11:08:54.9456780Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2019-04-30T11:08:54.9457540Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/bin/fastlane:23:in `<top (required)>'
2019-04-30T11:08:54.9458230Z 	from /usr/local/bin/fastlane:23:in `load'
2019-04-30T11:08:54.9458890Z 	from /usr/local/bin/fastlane:23:in `<main>'
2019-04-30T11:08:54.9459730Z /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:43:in `block (2 levels) in all': undefined method `[]' for nil:NilClass (NoMethodError)
2019-04-30T11:08:54.9460550Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:43:in `each'
2019-04-30T11:08:54.9461340Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:43:in `find'
2019-04-30T11:08:54.9462590Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:43:in `block in all'
2019-04-30T11:08:54.9463400Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:38:in `map'
2019-04-30T11:08:54.9464180Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build_trains.rb:38:in `all'
2019-04-30T11:08:54.9464970Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/build.rb:110:in `all'
2019-04-30T11:08:54.9465770Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/build_watcher.rb:38:in `matching_build'
2019-04-30T11:08:54.9466610Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/build_watcher.rb:16:in `block in wait_for_build_processing_to_be_complete'
2019-04-30T11:08:54.9467440Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/build_watcher.rb:15:in `loop'
2019-04-30T11:08:54.9468630Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/build_watcher.rb:15:in `wait_for_build_processing_to_be_complete'
2019-04-30T11:08:54.9469460Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/build_manager.rb:61:in `wait_for_build_processing_to_be_complete'
2019-04-30T11:08:54.9470240Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/build_manager.rb:53:in `upload'
2019-04-30T11:08:54.9471020Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
2019-04-30T11:08:54.9471800Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2019-04-30T11:08:54.9472560Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2019-04-30T11:08:54.9473370Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2019-04-30T11:08:54.9474160Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2019-04-30T11:08:54.9475030Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2019-04-30T11:08:54.9475840Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
2019-04-30T11:08:54.9476620Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
2019-04-30T11:08:54.9477500Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2019-04-30T11:08:54.9478250Z 	from /Users/ci/.gem-cache/gems/fastlane-2.121.1/bin/fastlane:23:in `<top (required)>'
2019-04-30T11:08:54.9478930Z 	from /usr/local/bin/fastlane:23:in `load'
2019-04-30T11:08:54.9479620Z 	from /usr/local/bin/fastlane:23:in `<main>'
2019-04-30T11:08:54.9701860Z ##[error]Error: fastlane failed with return code: 1
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.6.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.2/lib            |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.121.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.2        |
| unicode-display_width     | 1.5.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| mime-types-data           | 3.2019.0331  |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.2       |
</details>

*generated on:* **2019-04-30**
</pre>
</details>

**Comment by janpio** [comment]
Can you please use https://docs.fastlane.tools/actions/spaceship_logs/ and post the logs of the relevant requests? Maybe we can find out what triggered this. Thanks.

**Comment by NxSoftware** [comment]
@janpio looks like the `GET` request to the build details endpoint causes a 500:

```
INFO  [12:09:04]: >> GET ra/apps/286274367/platforms/ios/trains/8.6/builds/201904300848/details: [undefined body] 
DEBUG [12:09:05]: << GET ra/apps/286274367/platforms/ios/trains/8.6/builds/201904300848/details: 500 {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unexpected Error"]}, "statusCode"=>"ERROR"}
DEBUG [12:09:05]: Request was successful
```

**Comment by janpio** [comment]
That is indeed a pretty unexpected response. 
I guess the previous requests were to the same exact URLs but returned a 200?

Can you please log in to App Store Connect and then request that URL manually? What happens?

Depending on the result we could add a retry here if `500` is returned. But not sure how common that is, and if retrying is _always_ a good idea.

**Comment by NxSoftware** [comment]
It's still returning the same response as shown in the logs:

```json
{"data":null,"messages":{"warn":null,"info":null,"error":["Unexpected Error"]},"statusCode":"ERROR"}
```

It's worth pointing out a few things:
* The build is still in the "Processing" state (approx. 8 hours now).
* If I hit this URL while logged into an account that doesn't have access to the team this app is part of, I get the same response.
* There are a few login messages from the top of the logs that I didn't actually include in the original issue...

```
2019-04-30T10:35:26.1563500Z [11:35:26]: Login to App Store Connect (***)
2019-04-30T10:35:27.0313630Z Available session is not valid any more. Continuing with normal login.
2019-04-30T10:35:27.5079370Z Session loaded from environment variable is not valid. Continuing with normal login.
2019-04-30T10:35:30.4441910Z [11:35:30]: Login successful
2019-04-30T10:35:31.4373910Z [11:35:31]: Ready to upload new build to TestFlight (App: 286274367)...
2019-04-30T10:35:33.2666630Z [11:35:33]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
2019-04-30T10:35:33.2667090Z [11:35:33]: Going to upload updated app to App Store Connect
2019-04-30T10:35:33.2668250Z [11:35:33]: This might take a few minutes. Please don't interrupt the script.
2019-04-30T10:43:42.8778630Z [11:43:42]: iTunes Transporter successfully finished its job
2019-04-30T10:43:43.0159580Z [11:43:43]: --------------------------------------------------------------------
2019-04-30T10:43:43.0160450Z [11:43:43]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
2019-04-30T10:43:43.0161870Z [11:43:43]: --------------------------------------------------------------------
2019-04-30T10:43:43.0240470Z [11:43:43]: Successfully uploaded the new binary to App Store Connect
```

**Comment by janpio** [comment]
Interesting, so that build somehow messed things up at Apple. Strange.

**Comment by NxSoftware** [comment]
Uploaded a new version, same thing :/

**Comment by janpio** [comment]
Where do you have the "unknown error" you quote in the issue title from btw?

**Comment by NxSoftware** [comment]
Ah that was just because it wasn’t clear what the problem was at that point

**Comment by NxSoftware** [comment]
FYI the two builds that were uploaded finally finished processing over night

**Comment by janpio** [comment]
Wow, finally. This has to be a special state somehow.
What do the URLs return now?

**Comment by NxSoftware** [comment]
They return a valid JSON structure with a lot of info about the build. On my phone at the minute so don’t want to paste the whole response and mask out certain parts but it starts with:

```json
"data":{"uploadDate":1556621482000,"binaryState":"ITC.apps.preReleaseBuildStatus.Validated“
```

**Comment by janpio** [comment]
Yep, that looks like what spaceship would normally expect and be able to parse.

Error 500 with `"Unexpected Error"` as new state "this will take really long, we're sorry"?

**Comment by NxSoftware** [comment]
FWIW it looks like the last few attempts at a release are now failing because of issue https://github.com/fastlane/fastlane/issues/14372.
