### ISSUE TITLE
Err: Couldn't download certificate, got this instead: {"There is no certificate with ID &#x27 ...

### ISSUE THREAD

**Issue by kikolobo** [fastlane/fastlane#1477]
### Issue Description
When performing 'sigh' command I get an error. This didn't happened prior to the upgrade to latest version. (1.66.0)

**Error:**
```ruby
download_certificate': [!] Couldn't download certificate, got this instead: {"responseId"=>"9ff3e459-9ebc-42f3-a149-b53575d2508d", "resultCode"=>7100, "resultString"=>"Certificate 'VGFB8JESL7' not found", "userString"=>"There is no certificate with ID &#x27;VGFB8JESL7&#x27; on this team.", "creationTimestamp"=>"2016-03-04T20:47:05Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US"
```

I am assuming that the : **&#x27; ** characters in this output is a verbose character issue in how it translate to the debug output, but if not, that might be the issue. The only change from working environment to a none-working environment was the latest upgrade of fastlane.

##### Complete output when running fastlane, including the stack trace and command used

This output happens weather i run : **fastlane beta**    or    **sigh**  directly from the command line in the project folder.

```ruby
+-------------------------------------+-----------------+
|                Summary for sigh 1.4.0                 |
+-------------------------------------+-----------------+
| adhoc                               | false           |
| skip_install                        | false           |
| development                         | false           |
| force                               | false           |
| app_identifier                      | xxxxx         |
| username                            | apps@xxxx         |
| ignore_profiles_with_different_name | false           |
| skip_fetch_profiles                 | false           |
| skip_certificate_verification       | false           |
+-------------------------------------+-----------------+

[14:47:00]: Starting login with user 'xxx@xxxx'
[14:47:03]: Successfully logged in
[14:47:03]: Fetching profiles...
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/portal_client.rb:311:in `download_certificate': [!] Couldn't download certificate, got this instead: {"responseId"=>"9ff3e459-9ebc-42f3-a149-b53575d2508d", "resultCode"=>7100, "resultString"=>"Certificate 'VGFB8JESL7' not found", "userString"=>"There is no certificate with ID &#x27;VGFB8JESL7&#x27; on this team.", "creationTimestamp"=>"2016-03-04T20:47:05Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/downloadCertificateContent.action", "httpCode"=>200} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/certificate.rb:309:in `download_raw'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/runner.rb:87:in `block (2 levels) in fetch_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/runner.rb:85:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/runner.rb:85:in `block in fetch_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/runner.rb:82:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/runner.rb:82:in `find_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/runner.rb:82:in `fetch_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/bin/sigh:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/bin/sigh:91:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/bin/sigh:109:in `<top (required)>'
	from /usr/local/bin/sigh:23:in `load'
	from /usr/local/bin/sigh:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# =======================[SETUP]=======================
fastlane_version "1.48.0"
default_platform :ios


platform :ios do
# =======================[BEFORE ALL]=======================
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/xxxxxx"    
    
    ensure_git_status_clean
 end

  desc "Runs all the tests"
  lane :test do
    snapshot
  end

# ======================= ======================= =========
# ACTIONS
# ======================= ======================= =========

# =======================[BETA]=======================
  desc "Submit a new Beta Build to Apple TestFlight"  
  lane :beta do
    slack(
        message: "[Fastlane] Starting GIT Activities (BuildBumps/Commit/Push).",
        payload: { 
            'At :' => Time.new.to_s        
        })
      
    ensure_git_branch(
      branch: 'develop'
    )
      
    git_pull      
    increment_build_number
      
    commit_version_bump(
      message: 'minor [CI] Build Bump'            
    )
                
    push_to_git_remote          
    
      
  slack(
      message: "[Fastlane] Starting Signing of provisioning profiles.",
      success: true,
    payload: { 
        'At :' => Time.new.to_s        
    })
      
    sigh
      
    slack(
        message: "[Fastlane] Building the App (XCODE)",
        success: true,
    payload: { 
        'At :' => Time.new.to_s        
    })
      
    gym(scheme: "xxxxx"        
        ) # Build your app - more options available    
      
    slack(
        message: "[Fastlane] Delivering app to Testflight servers.",
        success: true,
    payload: { 
        'At :' => Time.new.to_s        
    })
      
    pilot(distribute_external: false)
    
    slack(
        message: "[Fastlane] Cleaning GIT Repo.",
        success: true,
    payload: { 
        'At :' => Time.new.to_s        
    })
      
    reset_git_repo
    
  end
    

  # ======================= ======================= =========
  # GENERAL HANDLERS
  # ======================= ======================= =========
  # =======================[AFTER ALL]=======================
  after_all do |lane|
    # This block is called, only if the executed lane was successful

     slack(
       message: "Successfully deployed new App Update to TestFlight",
       success: true
     )
  end

  error do |lane, exception|
     slack(
       message: exception.message,
       success: false
     )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
```

### Environment

fastlane version (fastlane -v): 1.66.0
Do you use bundler, rbenv or rvm? Nope

**Comment by Killectro** [comment]
I'm seeing this exact issue. I have enabled crash reporting on fastlane and ran `sigh` and this is the ID it gave me for the crash report: `ae9ab8c36b43bcd2a80816bbf92b0d93` Might it have something to do with the new Apple Dev Portal?

**Comment by hiltonc** [comment]
I'm hitting this same issue too.

**Comment by kikolobo** [comment]
I have tried reinstalling and have the same
Issue on two computers.

**Comment by zOrder** [comment]
same here, fastlane (1.66.0), sigh (1.4.0), spaceship (0.22.0) - both on local machine and CI

**Comment by tefinger** [comment]
Same here (fastlane 1.66.0 | sigh 1.4.0 | cert 1.4.0 | 0.22.0)

**Comment by madoke** [comment]
I confirm this issue. Downgrading to older versions of fastlane, sigh and spaceship didn't solve the problem

**Comment by kikolobo** [comment]
I believe the issue is with sigh using spaceships to download and/or find a certificate on apple server. Downgrading does not work because Apple changed the iTunes connect portal. And using the latest version does not work either because of this bug.

**Comment by stephanheilner** [comment]
:+1:

**Comment by sfransen** [comment]
That the same error I get when I try to update devices in existing provision profile

**Comment by kikolobo** [comment]
Can anyone comment if this got fixed on the latest release?

I am unable to access my server at this moment.

**Comment by kikolobo** [comment]
After much debate, I cleared all my provisioning profiles from the local computer and the developer portal. Started from scratch and it started to work.

So in my case this was fixed by replacing all my certificates. Can't tell which one was the culprit.

**Comment by stephanheilner** [comment]
In my case, I finally got it working by installing the new Apple WWDR root certificate. The one I've be using for years expired at the end of February. Installing the new root certs solved the problem.

**Comment by kikolobo** [comment]
So I am going to close the issue then.

Thanks everyone!

**Comment by madoke** [comment]
cleared everything with match nuke; then generated new certificates with match; and then sigh worked just fine
