### ISSUE TITLE
Screenshot tests fail.

### ISSUE THREAD

**Issue by adamstyrc** [fastlane/fastlane#14771]
Hello, I wanted to start Fastlane screenshots with this very prmitive test:
```
@RunWith(JUnit4.class)
public class MainActivityTest {

    @ClassRule
    public static final LocaleTestRule localeTestRule = new LocaleTestRule();

    @Rule
    public ActivityTestRule<MainActivity> activityTestRule = new ActivityTestRule<>(MainActivity.class);

    @Test
    public void useAppContext() {
        onView(withId(R.id.navigation_notifications)).perform(click());
        Screengrab.screenshot("after_button_click");
    }
}
```

However when it comes to execution of **Screengrab.screenshot()** I get below error:

```
java.lang.IllegalStateException: Couldn't get the activity from the view context
at tools.fastlane.screengrab.DecorViewScreenshotStrategy$ScreenshotViewAction.perform(DecorViewScreenshotStrategy.java:69)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:360)
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:251)
at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:64)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:157)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:154)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:210)
at android.app.ActivityThread.main(ActivityThread.java:7046)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```

I also tried to change recommended parameter with **Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy());** however then I land with such stacktrace:

```
java.lang.RuntimeException: Unable to capture screenshot.
at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:56)
at tools.fastlane.screengrab.UiAutomatorScreenshotStrategy.takeScreenshot(UiAutomatorScreenshotStrategy.java:39)
at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)
at com.adamstyrc.fastlanescreenshottest.MainActivityTest.useAppContext(MainActivityTest.java:38)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:32)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
at android.app.ContextImpl.checkMode(ContextImpl.java:2495)
at android.app.ContextImpl.getDir(ContextImpl.java:2270)
at android.content.ContextWrapper.getDir(ContextWrapper.java:294)
at tools.fastlane.screengrab.FileWritingScreenshotCallback.getFilesDirectory(FileWritingScreenshotCallback.java:74)
at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:39)
... 37 more
```

I add my gradle setup. For now Fastlane screenshots don't work at all for me :( Please help!
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.adamstyrc.fastlanescreenshottest"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.core:core-ktx:1.0.2'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    androidTestImplementation 'com.android.support.test:rules:1.0.2'
    androidTestImplementation 'tools.fastlane:screengrab:1.0.0'
}
```

**Comment by janpio** [comment]
@vanniktech androidx related problem here?

**Comment by vanniktech** [comment]
It shouldn't. I'm using fastlane with an AndroidX codebase without any problems

**Comment by heitorcolangelo** [comment]
I'm facing the same problem here:
```
E/Screengrab: Failed to initialize directory: /storage/emulated/0/com.package.name/screengrab/en-US/images/screenshots
    java.io.IOException: Unable to create output dir: /storage/emulated/0/com.package.name
        at tools.fastlane.screengrab.FileWritingScreenshotCallback.createPathTo(FileWritingScreenshotCallback.java:123)
        at tools.fastlane.screengrab.FileWritingScreenshotCallback.createPathTo(FileWritingScreenshotCallback.java:120)
        at tools.fastlane.screengrab.FileWritingScreenshotCallback.createPathTo(FileWritingScreenshotCallback.java:120)
        at tools.fastlane.screengrab.FileWritingScreenshotCallback.createPathTo(FileWritingScreenshotCallback.java:120)
        at tools.fastlane.screengrab.FileWritingScreenshotCallback.createPathTo(FileWritingScreenshotCallback.java:120)
        at tools.fastlane.screengrab.FileWritingScreenshotCallback.initializeDirectory(FileWritingScreenshotCallback.java:90)
        at tools.fastlane.screengrab.FileWritingScreenshotCallback.getFilesDirectory(FileWritingScreenshotCallback.java:70)
        at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:39)
        at tools.fastlane.screengrab.UiAutomatorScreenshotStrategy.takeScreenshot(UiAutomatorScreenshotStrategy.java:39)
        at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
        at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
        at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)

E/TestRunner: java.lang.RuntimeException: Unable to capture screenshot.
        at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:56)
        at tools.fastlane.screengrab.UiAutomatorScreenshotStrategy.takeScreenshot(UiAutomatorScreenshotStrategy.java:39)
        at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
        at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
        at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)
```
I'm also using AndroidX, but not sure if it's a problem with it.

**Comment by vanniktech** [comment]
You do need `test_instrumentation_runner('androidx.test.runner.AndroidJUnitRunner')`

**Comment by heitorcolangelo** [comment]
Do you mean this?
```
defaultConfig {
    testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
}
```
This is already set.

**Comment by vanniktech** [comment]
No in the `Screengrab` file.

**Comment by heitorcolangelo** [comment]
Same error.
But I'll have to park this issue for now and move on with other tasks.
I'll make sure to come back here once I have a proper explanation of the error and a proper solution.

**Comment by RishabhTayal** [comment]
I am seeing the same issue.
