### ISSUE TITLE
fastlane requires your locale to be set to UTF-8. /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/pilot/lib/pilot/build_manager.rb:182:in `=~': [!] incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by jjbencomo** [fastlane/fastlane#14775]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Using bullets (https://en.wikipedia.org/wiki/Bullet_(typography)) or trademark symbol (https://en.wikipedia.org/wiki/Trademark_symbol) throws an error during `fastlane --changelog
`
##### Complete output when running fastlane, including the stack trace and command used

>2019-05-16T20:11:03.3178350Z ##[debug]fastlane arg: ["pilot","upload","-u","*** ","-i","/Users/Shared/Work/MB_A00/r1/a/MyAppGoBuild/iOSBuildDrop/MyAppGo.ipa"]
2019-05-16T20:11:03.3180270Z ##[debug]fastlane arg: ["--changelog","Save Files into MyApp™\r\n•\tDocuments can be saved into a preselected category (i.e. via the Context menu option)\r\n•\tDocuments can be created into an open case (i.e. via the Context menu option).\r\n\r\nUI Advancements\r\n•\tText fields can now include multiple lines. \r\n\r\nMyApp™ Go is no longer supported by iOS 10."]
2019-05-16T20:11:03.3182500Z ##[debug]fastlane arg: ["-q","26YN77JF52"]
2019-05-16T20:11:03.3183590Z ##[debug]fastlane arg: ["-r","MyApp Corporation"]
2019-05-16T20:11:03.3184690Z ##[debug]fastlane arg: ["-a","com.MyApp.TheMobileApp"]
2019-05-16T20:11:03.3185540Z ##[debug]fastlane arg: ["--skip_submission","true"]
2019-05-16T20:11:03.3186100Z ##[debug]distributedToExternalTesters=false
2019-05-16T20:11:03.3186470Z ##[debug]exec tool: fastlane
2019-05-16T20:11:03.3187020Z ##[debug]Arguments:
2019-05-16T20:11:03.3187470Z ##[debug]   pilot
2019-05-16T20:11:03.3187870Z ##[debug]   upload
2019-05-16T20:11:03.3188630Z ##[debug]   -u
2019-05-16T20:11:03.3189240Z ##[debug]   ***
2019-05-16T20:11:03.3190160Z ##[debug]   -i
2019-05-16T20:11:03.3190600Z ##[debug]   /Users/Shared/Work/MB_A00/r1/a/MyAppGoBuild/iOSBuildDrop/MyAppGo.ipa
2019-05-16T20:11:03.3191450Z ##[debug]   --changelog
2019-05-16T20:11:03.3192420Z ##[debug]   Save Files into MyApp™
2019-05-16T20:11:03.3193370Z •	Documents can be saved into a preselected category (i.e. via the Context menu option)
2019-05-16T20:11:03.3194390Z •	Documents can be created into an open case (i.e. via the Context menu option).
2019-05-16T20:11:03.3194860Z 
2019-05-16T20:11:03.3195210Z UI Advancements
2019-05-16T20:11:03.3196120Z •	Text fields can now include multiple lines. 
2019-05-16T20:11:03.3196680Z 
2019-05-16T20:11:03.3197420Z MyApp™ Go is no longer supported by iOS 10.
2019-05-16T20:11:03.3198400Z ##[debug]   -q
2019-05-16T20:11:03.3199080Z ##[debug]   26YN77JF52
2019-05-16T20:11:03.3200080Z ##[debug]   -r
2019-05-16T20:11:03.3200620Z ##[debug]   MyApp Corporation
2019-05-16T20:11:03.3201440Z ##[debug]   -a
2019-05-16T20:11:03.3202030Z ##[debug]   com.MyApp.TheMobileApp
2019-05-16T20:11:03.3202840Z ##[debug]   --skip_submission
2019-05-16T20:11:03.3203660Z ##[debug]   true
2019-05-16T20:11:03.3204880Z [command]fastlane pilot upload -u *** -i /Users/Shared/Work/MB_A00/r1/a/MyAppGoBuild/iOSBuildDrop/MyAppGo.ipa --changelog Save Files into MyApp™
2019-05-16T20:11:03.3205920Z •	Documents can be saved into a preselected category (i.e. via the Context menu option)
2019-05-16T20:11:03.3207020Z •	Documents can be created into an open case (i.e. via the Context menu option).
2019-05-16T20:11:03.3207490Z 
2019-05-16T20:11:03.3207830Z UI Advancements
2019-05-16T20:11:03.3208860Z •	Text fields can now include multiple lines. 
2019-05-16T20:11:03.3209500Z 
2019-05-16T20:11:03.3210390Z MyApp™ Go is no longer supported by iOS 10. -q 26YN77JF52 -r MyApp Corporation -a com.MyApp.TheMobileApp --skip_submission true
2019-05-16T20:11:05.1477260Z [22:11:05]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2019-05-16T20:11:05.1548740Z [22:11:05]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
2019-05-16T20:11:06.5949470Z [22:11:06]: Login to App Store Connect (***)
2019-05-16T20:11:07.1001680Z Available session is not valid any more. Continuing with normal login.
2019-05-16T20:11:09.2219910Z [22:11:09]: Login successful
2019-05-16T20:11:09.2335610Z 
2019-05-16T20:11:09.2336660Z Looking for related GitHub issues on fastlane/fastlane...
2019-05-16T20:11:09.2337180Z 
2019-05-16T20:11:10.0981130Z   incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
2019-05-16T20:11:10.0982700Z     https://github.com/fastlane/fastlane/issues/14347 [closed] 3 💬
2019-05-16T20:11:10.0992800Z     4 weeks ago
2019-05-16T20:11:10.0993320Z 
2019-05-16T20:11:10.0994690Z   incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
2019-05-16T20:11:10.0996590Z     https://github.com/fastlane/fastlane/issues/8600 [closed] 15 💬
2019-05-16T20:11:10.0997450Z     10 Jul 2017
2019-05-16T20:11:10.0997750Z 
2019-05-16T20:11:10.0998580Z   incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
2019-05-16T20:11:10.0999570Z     https://github.com/fastlane/fastlane/issues/3182 [closed] 5 💬
2019-05-16T20:11:10.0999910Z     22 Sep 2016
2019-05-16T20:11:10.1000400Z 
2019-05-16T20:11:10.1001190Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
2019-05-16T20:11:10.1002830Z [22:11:10]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
2019-05-16T20:11:10.1006190Z /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/pilot/lib/pilot/build_manager.rb:182:in '=~': [!] incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encoding::CompatibilityError)
2019-05-16T20:11:10.1007520Z 	from /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/pilot/lib/pilot/build_manager.rb:182:in 'strip_emoji'
2019-05-16T20:11:10.1008600Z 	from /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/pilot/lib/pilot/build_manager.rb:190:in 'sanitize_changelog'
2019-05-16T20:11:10.1009590Z 	from /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/pilot/lib/pilot/build_manager.rb:18:in 'upload'
2019-05-16T20:11:10.1010480Z 	from /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/pilot/lib/pilot/commands_generator.rb:66:in 'block (2 levels) in run'
2019-05-16T20:11:10.1011450Z 	from /Users/tfs3builds/.gem-cache/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in 'call'
2019-05-16T20:11:10.1012470Z 	from /Users/tfs3builds/.gem-cache/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in 'run'
2019-05-16T20:11:10.1013430Z 	from /Users/tfs3builds/.gem-cache/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2019-05-16T20:11:10.1014380Z 	from /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in 'run!'
2019-05-16T20:11:10.1015220Z 	from /Users/tfs3builds/.gem-cache/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in 'run!'
2019-05-16T20:11:10.1016280Z 	from /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/pilot/lib/pilot/commands_generator.rb:166:in 'run'
2019-05-16T20:11:10.1017160Z 	from /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/pilot/lib/pilot/commands_generator.rb:18:in 'start'
2019-05-16T20:11:10.1018140Z 	from /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in 'take_off'
2019-05-16T20:11:10.1019000Z 	from /Users/tfs3builds/.gem-cache/gems/fastlane-2.123.0/bin/fastlane:23:in '<top (required)>'
2019-05-16T20:11:10.1019890Z 	from /Users/tfs3builds/.gem-cache/bin/fastlane:22:in 'load'
2019-05-16T20:11:10.1020650Z 	from /Users/tfs3builds/.gem-cache/bin/fastlane:22:in '<main>'
2019-05-16T20:11:10.1362340Z ##[debug]rc:1
2019-05-16T20:11:10.1363380Z ##[debug]success:false
2019-05-16T20:11:10.1384560Z ##[debug]task result: Failed
2019-05-16T20:11:10.1426110Z ##[error]Error: fastlane failed with return code: 1
2019-05-16T20:11:10.1427070Z ##[debug]Processed: ##vso[task.issue type=error;]Error: fastlane failed with return code: 1
2019-05-16T20:11:10.1455890Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: fastlane failed with return code: 1
2019-05-16T20:11:10.1504290Z ##[section]Finishing: Publish to the App Store TestFlight track

### Temporary Solution

After removing both, the trademark symbol and the bullet from my changelog file, the warning stayed but the app was successfully uploaded

**Comment by jjbencomo** [comment]
#14347
