### ISSUE TITLE
Investigate In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space.

### ISSUE THREAD

**Issue by cpk1** [fastlane/fastlane#14780]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Bringing this up again to investigate: https://github.com/fastlane/fastlane/issues/13832
One cause looks to be from turning on new languages and only providing text without any images.
##### Command executed

```
+--------------------------------------+-------------------------------------+
|                          deliver 2.120.0 Summary                           |
+--------------------------------------+-------------------------------------+
| username                             | cpk1                   |
| team_id                              | 123456                              |
| app_identifier                       | app.id                   |
| app_version                          | 1.0                               |
| skip_screenshots                     | true                                |
| edit_live                            | false                               |
| skip_binary_upload                   | true                                |
| force                                | true                                |
| metadata_path                        | game/metadata    |
| screenshots_path                     | game/screenshots |
| precheck_include_in_app_purchases    | false                               |
| run_precheck_before_submit           | true                                |
| platform                             | ios                                 |
| use_live_version                     | false                               |
| skip_metadata                        | false                               |
| skip_app_version_update              | false                               |
| overwrite_screenshots                | false                               |
| submit_for_review                    | false                               |
| reject_if_possible                   | false                               |
| automatic_release                    | false                               |
| phased_release                       | false                               |
| reset_ratings                        | false                               |
| precheck_default_rule_level          | warn                                |
| individual_metadata_items            | []                                  |
| ignore_language_directory_validation | false                               |
+--------------------------------------+-------------------------------------+
```
##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2019-05-17 14:45:28.69]: Loading 'game/metadata/review_information/notes.txt'...
INFO [2019-05-17 14:45:31.51]: Activating languages de-DE, en-AU, en-GB, en-US, es-ES, es-MX, fr-CA, fr-FR, id, it, ja, ko, no, pt-BR, pt-PT, sv, tr, zh-Hans, zh-Hant...
Potential server error received: 'In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space.'. Retrying after 10 seconds (remaining: 2)...
Potential server error received: 'In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space.'. Retrying after 10 seconds (remaining: 1)...



Spaceship::Tunes::PotentialServerError: [31m[!] The request could not be completed because:
  In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 12.9&quot; displays must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space.[0m
  /gems/fastlane-2.120.0/spaceship/lib/spaceship/tunes/tunes_client.rb:228:in `handle_itc_response'
  /gems/fastlane-2.120.0/spaceship/lib/spaceship/tunes/tunes_client.rb:445:in `block in update_app_version!'
  /gems/fastlane-2.120.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1466:in `with_tunes_retry'
  /gems/fastlane-2.120.0/spaceship/lib/spaceship/tunes/tunes_client.rb:438:in `update_app_version!'
  /gems/fastlane-2.120.0/spaceship/lib/spaceship/tunes/app_version.rb:403:in `save!'
  /gems/fastlane-2.120.0/deliver/lib/deliver/upload_metadata.rb:277:in `verify_available_languages!'
  /gems/fastlane-2.120.0/deliver/lib/deliver/upload_metadata.rb:72:in `upload'
  /gems/fastlane-2.120.0/deliver/lib/deliver/runner.rb:120:in `upload_metadata'
  /gems/fastlane-2.120.0/deliver/lib/deliver/runner.rb:38:in `run'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:176:in `block in parsing_binding'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /gems/fastlane-2.120.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /gems/fastlane-2.120.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /gems/fastlane-2.120.0/bin/fastlane:23:in `<top (required)>'
  /bin/fastlane:23:in `load'
  /bin/fastlane:23:in `<top (required)>'
```

  Going to look into if my suspicion of activating a new language with text only is causing this.
If this is the case, then look at providing more actionable messaging to the user and looking into providing an option to help automatically handle this (allow the user to specify they want text only localized and use unlocalized(default) images)

**Comment by cpk1** [comment]
Original hunch was correct - We weren't properly handling images in our screenshots directory. I think the next step here is to see if anything can be done RE: better messaging for the user to take action

**Comment by max-ott** [comment]
@ckp1 Could you please provide some more background information what you mean with "properly handling images" for future reference?

**Comment by cpk1** [comment]
In this specific case we had two languages that we did not have all the iPad sizes for, this is harder to track down than you would think when you have many localizations and a mix of "use default language screenshots" and localized images. Ideally we would be able to see in the log which language we failed saving on which would allow us to find the issue pretty quickly.
