### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by 460467069** [fastlane/fastlane#14830]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

 My code is the same as the [Sample code](https://github.com/fastlane/fastlane/pull/7834). Below is sample code.
```
 app.in_app_purchases.create!(
  type: Spaceship::Tunes::IAPType::CONSUMABLE, 
  versions: {
    'en-US': {
      name: "test name1",
      description: "Description has at least 10 characters"
    },
    'de-DE': {
      name: "test name german1",
      description: "German has at least 10 characters"
    },
    'da': {
      name: "test name danish",
      description: "German has at least 10 characters"
    }
  },
  reference_name: "locallizeddemo11111",
  product_id: "x.a.a.b.b.c.d.x.y.f",
  cleared_for_sale: true,
  review_notes: "Some Review Notes here bla bla bla",
  review_screenshot: "/Users/hjanuschka/Desktop/review.jpg", 
  pricing_intervals: 
    [
      {
        country: "WW",
        begin_date: nil,
        end_date: nil,
        tier: 1
      }
    ] 
)
```
The previous code is working fine, but when I try it today, I get an error. I also tried to run the sample code, the result is the same.
```
[22:02:24]: Driving the lane 'ios createIAP' 🚀
+------------------+---------------+
|           Lane Context           |
+------------------+---------------+
| DEFAULT_PLATFORM | ios           |
| PLATFORM_NAME    | ios           |
| LANE_NAME        | ios createIAP |
+------------------+---------------+
[22:02:30]: no implicit conversion of nil into String

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
+------+----------------------------+-------------+

[22:02:30]: fastlane finished with errors
Traceback (most recent call last):
	59: from /Users/WangRuzhou/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	58: from /Users/WangRuzhou/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	57: from /Users/WangRuzhou/.rvm/gems/ruby-2.6.0@global/bin/fastlane:23:in `<main>'
	56: from /Users/WangRuzhou/.rvm/gems/ruby-2.6.0@global/bin/fastlane:23:in `load'
	55: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/bin/fastlane:23:in `<top (required)>'
	54: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	53: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	52: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	51: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	50: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	49: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	48: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	47: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	46: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	45: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	44: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	43: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	42: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	41: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	40: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	39: from Fastfile:167:in `block (2 levels) in parsing_binding'
	38: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/tunes/iap.rb:75:in `create!'
	37: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1339:in `create_iap!'
	36: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/tunes/tunes_client.rb:799:in `upload_purchase_review_screenshot'
	35: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/du/du_client.rb:26:in `upload_purchase_review_screenshot'
	34: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/du/du_client.rb:76:in `upload_file'
	33: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/client.rb:688:in `request'
	32: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/client.rb:844:in `send_request'
	31: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/client.rb:620:in `with_retry'
	30: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/client.rb:845:in `block in send_request'
	29: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'
	28: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	27: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	26: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
	25: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
	24: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
	23: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	22: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.124.0/spaceship/lib/spaceship/helper/rels_middleware.rb:17:in `call'
	21: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
	20: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	19: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
	18: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:87:in `perform_request'
	17: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	16: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:920:in `start'
	15: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
	14: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	13: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
	12: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
	11: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1507:in `block in transport_request'
	10: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http/generic_request.rb:123:in `exec'
	 9: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http/generic_request.rb:189:in `send_request_with_body'
	 8: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:247:in `write'
	 7: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:265:in `writing'
	 6: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:248:in `block in write'
	 5: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:275:in `write0'
	 4: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:275:in `each_with_index'
	 3: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:275:in `each'
	 2: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:277:in `block in write0'
	 1: from /Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/openssl/buffering.rb:383:in `write_nonblock'
/Users/WangRuzhou/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/openssl/buffering.rb:383:in `syswrite_nonblock': [!] no implicit conversion of nil into String (TypeError)
```

**Comment by joshdholtz** [comment]
@460467069 Heyyy 👋 I don't think anything was changed in this part of the code base in any recent versions 🤔 What is the last version of _fastlane_ this was working with?

**Comment by max-ott** [comment]
@460467069 Did you actually use `  review_screenshot: "/Users/hjanuschka/Desktop/review.jpg",` ? This path is probably not available on your machine and therefore the `lane` should crash.

**Comment by 460467069** [comment]
> review_screenshot



> @460467069 Did you actually use ` review_screenshot: "/Users/hjanuschka/Desktop/review.jpg",` ? This path is probably not available on your machine and therefore the `lane` should crash.

No, I used my own image path

**Comment by 460467069** [comment]
> @460467069 Heyyy 👋 I don't think anything was changed in this part of the code base in any recent versions 🤔 What is the last version of _fastlane_ this was working with?

I think it should be a ruby problem, I reduced the ruby version to 2.5.3, everything works fine.
