### ISSUE TITLE
How to use sigh on centos

### ISSUE THREAD

**Issue by simpleway2016** [fastlane/fastlane#14893]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

sigh

#### Question Description
I try to use sigh to resign my ipa file on centos 7, but i got this message:

```
/usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/resign.rb:205:in ``': No such file or directory - security (Errno::ENOENT)
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/resign.rb:205:in `request_valid_identities'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/resign.rb:189:in `installed_identities'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/resign.rb:210:in `installed_identity_descriptions'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/resign.rb:179:in `print_available_identities'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/resign.rb:183:in `ask_for_signing_identity'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/resign.rb:90:in `get_inputs'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/resign.rb:11:in `run'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/commands_generator.rb:117:in `block (2 levels) in run'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:69:in `run!'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/commands_generator.rb:138:in `run'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/fastlane-2.125.2/sigh/lib/sigh/commands_generator.rb:16:in `start'
	from /usr/local/rvm/gems/ruby-2.4.4/gems/sigh-2.0.1/bin/sigh:13:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.4/bin/sigh:23:in `load'
	from /usr/local/rvm/gems/ruby-2.4.4/bin/sigh:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `eval'
	from /usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by janpio** [comment]
This is line 205: https://github.com/fastlane/fastlane/blob/11257afda89b4f4447d76279d6ec263f0f2f9af6/sigh/lib/sigh/resign.rb#L205
`security` is a macOS only tool to manage certificates, so I don't think this currently can work on non-macOS operating systems unfortunately.
