### ISSUE TITLE
could not read Username for 'https://bitbucket.org': Device not configured

### ISSUE THREAD

**Issue by mehmetfarhan** [fastlane/fastlane#14923]
### Question Checklist

- [YES] Updated fastlane to the latest version
- [YES] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [YES] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [YES] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
could not read Username for 'https://bitbucket.org': Device not configured 
[12:34:21]: Exit status of command 'git pull && git fetch --tags' was 1 instead of 0.

#### Question Description

```
+ bundle exec fastlane beta
+----------------------------+---------+------------------------------------+
|                               Used plugins                                |
+----------------------------+---------+------------------------------------+
| Plugin                     | Version | Action                             |
+----------------------------+---------+------------------------------------+
| fastlane-plugin-versioning | 0.3.4   | get_version_number_from_git_branch |
|                            |         | get_version_number_from_plist      |
|                            |         | get_build_number_from_plist        |
|                            |         | ci_build_number                    |
|                            |         | increment_version_number_in_plist  |
|                            |         | get_app_store_version_number       |
|                            |         | get_info_plist_path                |
|                            |         | increment_build_number_in_plist    |
+----------------------------+---------+------------------------------------+

[12:34:20]: ----------------------------------------
[12:34:20]: --- Step: Verifying fastlane version ---
[12:34:20]: ----------------------------------------
[12:34:20]: Your fastlane version 2.125.2 matches the minimum requirement of 2.28.8  ✅
[12:34:20]: ------------------------------
[12:34:20]: --- Step: default_platform ---
[12:34:20]: ------------------------------
[12:34:20]: Driving the lane 'ios beta' 🚀
[12:34:20]: -------------------------------
[12:34:20]: --- Step: ensure_git_branch ---
[12:34:20]: -------------------------------
[12:34:20]: Git branch matches `develop`, all good! 💪
[12:34:20]: ----------------------
[12:34:20]: --- Step: git_pull ---
[12:34:20]: ----------------------
[12:34:20]: $ git pull && git fetch --tags
[12:34:21]: ▸ fatal: could not read Username for 'https://bitbucket.org': Device not configured
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[12:34:21]: Exit status of command 'git pull && git fetch --tags' was 1 instead of 0.
fatal: could not read Username for 'https://bitbucket.org': Device not configured


+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | ensure_git_branch          | 0           |
| 💥   | git_pull                   | 0           |
+------+----------------------------+-------------+

[12:34:21]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...

➡️  Improve Beta Setup
    https://github.com/fastlane/fastlane/pull/1 [closed] 1 💬
    04 Feb 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'git pull && git fetch --tags' was 1 instead of 0.
fatal: could not read Username for 'https://bitbucket.org': Device not configured

  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/git_pull.rb:13:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:64:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'

**Comment by janpio** [comment]
And what exactly is your question?

> [12:34:20]: --- Step: git_pull ---
> [12:34:20]: ----------------------
> [12:34:20]: $ git pull && git fetch --tags
> [12:34:21]: ▸ fatal: could not read Username for 'https://bitbucket.org': Device not configured

Seems like your machine is not configured to be able to pull from the repository you are using. You should be able to run the command manually on the command line.

As you didn't include your `fastlane env` output, I don't really know what you are trying to do though.
