### ISSUE TITLE
Schemes detections seems broken

### ISSUE THREAD

**Issue by gheaeckkseqrz** [fastlane/fastlane#14988]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to build a end to end automatic delivery for cocos2d-x projects, that is, get it to work without ever opening the Xcode GUI. Goal is to be able to reproduce on CI server (Travis).

Problem is, the scheme I'm trying to build is missing untill I fire up XCode and build it through the GUI, which doesn't work with the idea of automatic end to end CI.

The interresting bit is : If I comment out some code in project.rb (L134-137), everything works nicely.

```
        # Verify the scheme is available
        unless schemes.include?(options[:scheme].to_s)
          UI.error("Couldn't find specified scheme '#{options[:scheme]}'. Please make sure that the scheme is shared, see https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_g\
uide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3")
          options[:scheme] = nil
        end
```

My guess is that the method ```schemes``` (project.rb L119) is not looking in the right place to find the schemes available for build.

I printed out the value of ```schemes``` on line 135 and got ```'["COCOS"]'```
Whereas ```xcodebuild -list``` returns
```Information about project "COCOS":
    Targets:
        COCOS-mobile
        COCOS-desktop

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Debug" is used.

    Schemes:
        COCOS-desktop
        COCOS-mobile
        libcocos2d iOS
        libcocos2d Mac
        libcocos2d tvOS
```

##### Command executed
```
cocos new COCOS -l cpp
cd COCOS/proj.ios_mac
COPY MY FASTLANE CONFIG IN THAT FOLDER (CONTENT IN THE ENV SECTION)
fastlane beta
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> proj.ios_mac git:(master) ✗ fastlane beta
[19:39:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[19:39:43]: ------------------------------
[19:39:43]: --- Step: default_platform ---
[19:39:43]: ------------------------------
[19:39:43]: Driving the lane 'ios beta' 🚀
[19:39:43]: ---------------------------------
[19:39:43]: --- Step: update_project_team ---
[19:39:43]: ---------------------------------
[19:39:44]: Updating development team (#########) for target `COCOS-mobile` in the project 'COCOS.xcodeproj'
[19:39:44]: Successfully updated project settings to use Developer Team ID '########' for target `COCOS-mobile`
[19:39:44]: Updating development team (########) for target `COCOS-desktop` in the project 'COCOS.xcodeproj'
[19:39:44]: Successfully updated project settings to use Developer Team ID '#######' for target `COCOS-desktop`
[19:39:44]: -----------------------
[19:39:44]: --- Step: build_app ---
[19:39:44]: -----------------------
[19:39:44]: Couldn't find specified scheme 'COCOS-mobile'. Please make sure that the scheme is shared, see https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3
[19:39:44]: $ xcodebuild -showBuildSettings -scheme COCOS -project ./COCOS.xcodeproj
xcodebuild: error: The project named "COCOS" does not contain a scheme named "COCOS". The "-list" option can be used to find the names of the schemes in the project.
[19:39:46]: Could not read build settings. Make sure that the scheme "COCOS" is configured for running by going to Product → Scheme → Edit Scheme…, selecting the "Build" section, checking the "Run" checkbox and closing the scheme window.
[19:39:46]: Could not read the "SUPPORTED_PLATFORMS" build setting, assuming that the project supports iOS only.
[19:39:46]: Could not read the "SUPPORTED_PLATFORMS" build setting, assuming that the project supports iOS only.

+------------------------+--------------------------------------+
|                    Summary for gym 2.126.0                    |
+------------------------+--------------------------------------+
| scheme                 | COCOS                                |
| project                | ./COCOS.xcodeproj                    |
| destination            | generic/platform=iOS                 |
| output_name            | App                                  |
| build_path             | /Users/wilmot_p/Library/Developer/X  |
|                        | code/Archives/2019-07-07             |
| clean                  | false                                |
| output_directory       | .                                    |
| silent                 | false                                |
| skip_package_ipa       | false                                |
| result_bundle          | false                                |
| buildlog_path          | ~/Library/Logs/gym                   |
| skip_profile_detection | false                                |
| xcode_path             | /Applications/Xcode.app              |
+------------------------+--------------------------------------+

[19:39:47]: $ set -o pipefail && xcodebuild -scheme COCOS -project ./COCOS.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/wilmot_p/Library/Developer/Xcode/Archives/2019-07-07/App\ 2019-07-07\ 19.39.47.xcarchive archive | tee /Users/wilmot_p/Library/Logs/gym/App-COCOS.log | xcpretty
[19:39:49]: ▸ xcodebuild: error: The project named "COCOS" does not contain a scheme named "COCOS". The "-list" option can be used to find the names of the schemes in the project.
xcodebuild: error: The project named "COCOS" does not contain a scheme named "COCOS". The "-list" option can be used to find the names of the schemes in the project.
[19:39:49]: Exit status: 65

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.126.0                 |
+-------------+-------------------------+

+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 2    | update_project_team | 0           |
| 💥   | build_app           | 4           |
+------+---------------------+-------------+

[19:39:49]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Error "undefined method `[]' for nil:NilClass" when trying to use command "fastlane frameit"
    https://github.com/fastlane/fastlane/issues/14876 [open] 4 💬
    2 weeks ago

➡️  upload_to_testflight: fails with nil in pilot/build_manager.rb:449:in `update_build_beta_details`
    https://github.com/fastlane/fastlane/issues/14977 [open] 13 💬
    3 days ago

➡️   undefined method `each' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/13959 [closed] 19 💬
    3 weeks ago

and 152 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60each%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/gym/lib/gym/error_handler.rb:147:in `print_full_log_path': [!] undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/gym/lib/gym/error_handler.rb:59:in `handle_build_error'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/gym/lib/gym/runner.rb:97:in `block in build_app'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `call'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/gym/lib/gym/runner.rb:93:in `build_app'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/gym/lib/gym/runner.rb:18:in `run'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/gym/lib/gym/manager.rb:19:in `work'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/build_ios_app.rb:64:in `run'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:22:in `block (2 levels) in parsing_binding'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/wilmot_p/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/bin/fastlane:23:in `<top (required)>'
	from /Users/wilmot_p/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/wilmot_p/.fastlane/bin/bundle/bin/fastlane:22:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    update_project_team(path: "COCOS.xcodeproj", teamid: "#########")
    build_app(scheme: "COCOS-mobile")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("#########") # The bundle identifier of your app
apple_id("########") # Your Apple email address

itc_team_id("#######") # App Store Connect Team ID
team_id("########") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.126.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.7.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.1          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-07-07**
</details> </pre>
</details>

**Comment by gheaeckkseqrz** [comment]
Having digged into it a bit more, problem seems to be comming from [XCodeproj](https://github.com/CocoaPods/Xcodeproj/). There is some work currently being done on schemes detection (https://github.com/CocoaPods/Xcodeproj/pull/680). Hope they'll fix it, and problem should get fixed here too.
