### ISSUE TITLE
fastlane swift readPodspec got error

### ISSUE THREAD

**Issue by lanjing99** [fastlane/fastlane#14986]
### Issue Description

I got the error below when I use swift readPodspec method :
Reading podspec from file ../XBehaviorReport.podspec
[15:46:05]: ▸ Fatal error: Unexpectedly found nil while unwrapping an Optional value

##### Command executed

```
XYSZM00461:Example lanjing$ fastlane pod
[✔] 🚀 
[15:46:04]: loading manifest: /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/swift/upgrade_manifest.json
[15:46:04]: FastlaneSwiftRunner project is up-to-date
[15:46:04]: $ ./fastlane/FastlaneRunner lane pod swiftServerPort 2000 > /dev/null
[15:46:04]: ----------------------
[15:46:04]: --- Step: git_pull ---
[15:46:04]: ----------------------
[15:46:04]: $ git pull && git fetch --tags
[15:46:05]: ▸ Already up to date.
[15:46:05]: ----------------------------------
[15:46:05]: --- Step: version_bump_podspec ---
[15:46:05]: ----------------------------------
[15:46:05]: --------------------------
[15:46:05]: --- Step: read_podspec ---
[15:46:05]: --------------------------
[15:46:05]: Reading podspec from file ../XBehaviorReport.podspec
[15:46:05]: ▸ Fatal error: Unexpectedly found nil while unwrapping an Optional value
#<Thread:0x00007fbcc461c398@/Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/swift_lane_manager.rb:228 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/swift_lane_manager.rb:231:in `block in start_socket_thread'
	8: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	7: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
	6: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
	5: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
	4: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
	3: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/server/socket_server.rb:81:in `parse_and_execute_command'
	2: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/server/command_parser.rb:12:in `parse'
	1: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
/Users/lanjing/.rvm/gems/ruby-2.5.1/gems/json-2.2.0/lib/json/common.rb:156:in `parse': 785: unexpected token at '' (JSON::ParserError)
[15:46:05]: ▸ sh: line 1: 59576 Illegal instruction: 4  ./fastlane/FastlaneRunner lane pod swiftServerPort 2000 > /dev/null
#<Thread:0x00007fbcc45edf20@/Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/swift_lane_manager.rb:104 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/swift_lane_manager.rb:105:in `block in cruise_swift_lane_in_thread'
	3: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	2: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	1: from /Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/lanjing/.rvm/gems/ruby-2.5.1/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane pod swiftServerPort 2000 > /dev/null' was 132 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Fatal error: Unexpectedly found nil while unwrapping an Optional value
sh: line 1: 59576 Illegal instruction: 4  ./fastlane/FastlaneRunner lane pod swiftServerPort 2000 > /dev/null
+------------------------+--------------------------------------------------------------------------------------+
|                                                 Lane Context                                                  |
+------------------------+--------------------------------------------------------------------------------------+
| LANE_NAME              | pod                                                                                  |
| PODSPEC_VERSION_NUMBER | 1.0.16                                                                               |
| READ_PODSPEC_JSON      | {"name"=>"XBehaviorReport", "version"=>"1.0.16", "summary"=>"A user behavior report  |
|                        | library.", "description"=>"TODO: Add long description of the pod here.",             |
|                        | "platforms"=>{"osx"=>nil, "ios"=>nil, "tvos"=>nil, "watchos"=>nil}}                  |
+------------------------+--------------------------------------------------------------------------------------+
[15:46:05]: 785: unexpected token at ''

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | git_pull             | 1           |
| 2    | version_bump_podspec | 0           |
| 3    | read_podspec         | 0           |
+------+----------------------+-------------+

[15:46:05]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
```

### podspec file content
```
Pod::Spec.new do |s|
  s.name             = 'XBehaviorReport'
  s.version          = '1.0.16'
  s.summary          = 'A user behavior report library.'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  s.description      = <<-DESC
TODO: Add long description of the pod here.
                       DESC
end
```

**Comment by janpio** [comment]
The issue template also asks for your `fastlane env`, which for example would have included your `Fastfile` to be able to look at what you are actually doing.

Have you tried it with a Ruby `Fastfile` and `read_podspec`?

**Comment by lanjing99** [comment]
No, I didn't, I am not familiar with Ruby, So I just use Fastlane Swift, I think it's easy to reproduce it when use readPodspec function in Fastfile.swift
