### ISSUE TITLE
Spaceship::InternalServerError when executing pilot distribute

### ISSUE THREAD

**Issue by fl0cke** [fastlane/fastlane#14994]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I exectute the command 

`fastlane pilot distribute --distribute_external true -g "Test" -w "Test"`
 
I get the message 

> The request could not be completed because: (Spaceship::InternalServerError) Server error got 500

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/client.rb:126:in `handle_response': [!] The request could not be completed because: (Spaceship::InternalServerError)
        Server error got 500
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/client.rb:96:in `post'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:105:in `post_beta_app_review_submissions'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/models/build.rb:140:in `post_beta_app_review_submission'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/pilot/lib/pilot/build_manager.rb:300:in `distribute_build'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/pilot/lib/pilot/build_manager.rb:136:in `distribute'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/pilot/lib/pilot/commands_generator.rb:78:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.126.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:22:in `load'
        from /usr/local/bin/fastlane:22:in `<main>'
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.5                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.5 (18F132)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build, archive and sign the app"
  lane :build do
    build_app(scheme: "Runner",
              workspace: "Runner.xcworkspace",
              include_bitcode: true,
              export_xcargs: "-allowProvisioningUpdates")

  end

  lane :internal do
    build
    upload_to_testflight(
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("rocks.clickbar.fkaszentral") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.126.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.4        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-07-09**
</details>

**Comment by fl0cke** [comment]
It seems like this only happens if the test and beta review information are not completely set in App Store Connect. Maybe pilot should catch this and notify the user and/or prompt him to enter the required information?
