### ISSUE TITLE
[action] `sh` looses whitespace and empty lines in command output

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#15021]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`sh` looses whitespace and empty lines in command output:

#### Whitespace

```
[18:28:02]: ▸ Failed to install 'cordova-plugin-googlemaps': CordovaError: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
[18:28:02]: ▸ at Context.requireCordovaModule (C:\ProgramData\scoop\persist\nvm\nodejs\v12.5.0\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:57:15)
[18:28:02]: ▸ at module.exports (E:\Projects\Xcode4Windows\CI\xcodebuild\tmp\app\plugins\cordova-plugin-googlemaps\src\before_plugin_install.js:3:16)
[18:28:02]: ▸ at runScriptViaModuleLoader (C:\ProgramData\scoop\persist\nvm\nodejs\v12.5.0\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:181:32)
[18:28:02]: ▸ at runScript (C:\ProgramData\scoop\persist\nvm\nodejs\v12.5.0\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:16)
[18:28:02]: ▸ at C:\ProgramData\scoop\persist\nvm\nodejs\v12.5.0\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:125:20
[18:28:03]: ▸ at processTicksAndRejections (internal/process/task_queues.js:82:5)
```

vs.

```
Failed to install 'cordova-plugin-googlemaps': CordovaError: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (C:\ProgramData\scoop\persist\nvm\nodejs\v12.5.0\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:57:15)
    at module.exports (E:\Projects\Xcode4Windows\CI\xcodebuild\tmp\app\plugins\cordova-plugin-googlemaps\src\before_plugin_install.js:3:16)
    at runScriptViaModuleLoader (C:\ProgramData\scoop\persist\nvm\nodejs\v12.5.0\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:181:32)
    at runScript (C:\ProgramData\scoop\persist\nvm\nodejs\v12.5.0\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:16)

    at C:\ProgramData\scoop\persist\nvm\nodejs\v12.5.0\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:125:20
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
```

#### Empty Lines

```
[18:27:45]: ▸ Install complete for cordova-plugin-whitelist on android.
[18:27:45]: ▸ This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
[18:27:45]: ▸ Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-whitelist on android platform only.
```

vs.

```
Install complete for cordova-plugin-whitelist on android.

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-whitelist on android platform only.
```

That's both from the same run, once via `sh` and once via the error output (because the command crashed) of fastlane that repeats the original command output.

**Comment by janpio** [comment]
Culprit is probably somewhere in here: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/helper/sh_helper.rb#L28

Ah, already found the `strip`: https://github.com/fastlane/fastlane/blob/5780dae27dd17e51f06e069a7ecaaa04271ba203/fastlane/lib/fastlane/helper/sh_helper.rb#L57

**Comment by janpio** [comment]
The empty line problem is not fully solved by removing the `strip`, I think the empty lines could be "lost" here somehow:

https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb#L70-L80

**Comment by janpio** [comment]
Ok, for empty lines `actual` is just `\n`, which means that `actual.split("\n")` doesn't return anything that we could iterate over.

Any idea how to fix?

**Comment by janpio** [comment]
Change where this was added: https://github.com/fastlane/fastlane/commit/b9a4b0fe4e7f77038d4713db896949e9c0d90f60#diff-8bde500a3a4c5f751f8d556a2922cbe6R53 I don't understand what it is doing :/

**Comment by janpio** [comment]
Ok, one way to work around this problem would be to do this:

```
	  if actual == "\n"
		actual = " \n" 
	  end
```
before the `actual.split("\n")`. This adds a space, so the split actually gets a result that it can output.

This pretty much is what is expected, but of course this is super super ugly.

**Comment by janpio** [comment]
Okay, `split` has a "helpful" (?) feature that is happening here:

> If the _limit_ parameter is omitted, trailing null fields are suppressed. If _limit_ is a positive number, at most that number of split substrings will be returned (captured groups will be returned as well, but are not counted towards the limit). If _limit_ is 1, the entire string is returned as the only entry in an array. If negative, there is no limit to the number of fields returned, and trailing null fields are not suppressed.

https://apidock.com/ruby/String/split

As we have no `limit` param (the second one), "trailing null fields are suppressed". Unfortunately this pretty much is required, because otherwise splitting "foo\n" also returns 2 values:

```
irb(main):001:0> string = "\n"
=> "\n"
irb(main):002:0> string.split("\n")
=> []
irb(main):003:0> string.split("\n", -1)
=> ["", ""]

irb(main):009:0> string2 = "foo\n"
=> "foo\n"
irb(main):010:0> string2.split("\n")
=> ["foo"]
irb(main):011:0> string2.split("\n", -1)
=> ["foo", ""]
```

What we would actually want here, is for `split` to return `[""]` somehow for `"\n"`.

**Comment by joshdholtz** [comment]
@janpio I think this is it!
```rb
irb(main):001:0> "line1\nline2\n\nline3\nline4".lines.map(&:chomp)
=> ["line1", "line2", "", "line3", "line4"]
```

**Comment by janpio** [comment]
This looks good:
```
irb(main):001:0> "line1\n    line2\n\nline3\nline4".lines.map(&:chomp)
=> ["line1", "    line2", "", "line3", "line4"]
```

The `\r` stuff in the original code is still confusing me.

We should definitely add some tests about the cases we want to have covered.

**Comment by janpio** [comment]
Tested your suggestion locally. As it produced perfect results for me, I added it to the PR: https://github.com/fastlane/fastlane/pull/15022/commits/44ac1c3805c564433d6e85589e3e1ebd8c71d51f 

So https://github.com/fastlane/fastlane/pull/15022 can now be reviewed - but we should still add some tests somehow.

**Comment by McNeely12** [comment]
Hello janpio,
Thank you for asking This problem. I am also having the same Issue. Did you get any solution?
