### ISSUE TITLE
Connection reset by peer - get_provisioning_profile

### ISSUE THREAD

**Issue by tedgonzalez** [fastlane/fastlane#15051]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm getting Connection reset by peer when running get_provisioning_profile. Note that I've checked the existing issues here, tried most solutions posted.

##### Command executed
get_provisioning_profile

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [18:33:06]: ------------------------------
[18:33:06]: --- Step: default_platform ---
[18:33:06]: ------------------------------
[18:33:06]: Driving the lane 'build_production' 🚀
[18:33:06]: -----------------------
[18:33:06]: --- Step: xcversion ---
[18:33:06]: -----------------------
[18:33:06]: Setting Xcode version to /Users/anka/Downloads/Xcode.app for all build steps
[18:33:06]: --------------------------------------
[18:33:06]: --- Step: get_provisioning_profile ---
[18:33:06]: --------------------------------------

+-------------------------------------+----------------------------------+
|                        Summary for sigh 2.127.1                        |
+-------------------------------------+----------------------------------+
| username                            | redacted |
| app_identifier                      | redacted |
| team_id                             | redacted |
| provisioning_name                   | redacted |
| skip_certificate_verification       | true                             |
| readonly                            | true                             |
| adhoc                               | false                            |
| developer_id                        | false                            |
| development                         | false                            |
| skip_install                        | false                            |
| force                               | false                            |
| ignore_profiles_with_different_name | false                            |
| skip_fetch_profiles                 | false                            |
| platform                            | ios                              |
+-------------------------------------+----------------------------------+

[18:33:06]: Starting login with user 'redacted '
[18:33:09]: Successfully logged in
[18:33:09]: Fetching profiles...
+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | ios              |
| PLATFORM_NAME    |                  |
| LANE_NAME        | build_production |
+------------------+------------------+
[18:33:25]: Connection reset by peer

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | xcversion              | 0           |
| 💥   | get_provisioning_prof  | 18          |
|      | ile                    |             |
+------+------------------------+-------------+

[18:33:25]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Connection reset by peer - SSL_connect
    https://github.com/fastlane/fastlane/issues/14240 [closed] 1 💬
    17 Apr 2019

➡️  Connection reset by peer - SSL_connect 
    https://github.com/fastlane/fastlane/issues/13460 [closed] 4 💬
    15 Jan 2019

➡️  Broken pipe for upload binary to Hockeyapp
    https://github.com/fastlane/fastlane/issues/14699 [closed] 47 💬
    2 weeks ago

and 32 more at: https://github.com/fastlane/fastlane/search?q=Connection%20reset%20by%20peer&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock': [!] Connection reset by peer (Faraday::ConnectionFailed)
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:33:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/spaceship/lib/spaceship/helper/rels_middleware.rb:17:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:186:in `post'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/spaceship/lib/spaceship/client.rb:845:in `block in send_request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/spaceship/lib/spaceship/client.rb:620:in `with_retry'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/spaceship/lib/spaceship/client.rb:844:in `send_request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/spaceship/lib/spaceship/client.rb:688:in `request'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/spaceship/lib/spaceship/portal/portal_client.rb:646:in `provisioning_profiles_via_xcode_api'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:319:in `all'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:356:in `find_by_bundle_id'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/sigh/lib/sigh/runner.rb:70:in `fetch_profiles'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/sigh/lib/sigh/runner.rb:24:in `run'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/sigh/lib/sigh/manager.rb:8:in `start'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/actions/get_provisioning_profile.rb:19:in `run'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:61:in `block in parsing_binding'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/anka/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.127.1/bin/fastlane:23:in `<top (required)>'
	from /Users/anka/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/anka/.fastlane/bin/bundle/bin/fastlane:22:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> ### Stack

| Key                         | Value                                     |
| --------------------------- | ----------------------------------------- |
| OS                          | 10.14.5                                   |
| Ruby                        | 2.2.4                                     |
| Bundler?                    | true                                      |
| Git                         | git version 2.20.1 (Apple Git-117)        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane       |
| Host                        | Mac OS X 10.14.5 (18F132)                 |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                |
| Is contained                | true                                      |
| Is homebrew                 | false                                     |
| Is installed via Fabric.app | false                                     |
| Xcode Path                  | ~/Downloads/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |</pre>
</details>

bundle exec openssl version returns 1.0.2s 28 May 2019
openssl version returns 1.0.2s 28 May 2019
but fastlane env shows 1.0.2g

Is there a way to tell fastlane to use the one installed by brew or better use 1.1.1?

**Comment by tedgonzalez** [comment]
Yes I've seen Code Signing Troubleshooting Guide and I attached the fastlane env but removed my code

**Comment by tedgonzalez** [comment]
### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.127.1 | 🚫 Update available |

**Comment by tedgonzalez** [comment]
Tried with rvm

### Stack

| Key                         | Value                                     |
| --------------------------- | ----------------------------------------- |
| OS                          | 10.14.5                                   |
| Ruby                        | 2.4.4                                     |
| Bundler?                    | true                                      |
| Git                         | git version 2.20.1 (Apple Git-117)        |
| Installation Source         | ~/.rvm/gems/ruby-2.4.4/bin/fastlane       |
| Host                        | Mac OS X 10.14.5 (18F132)                 |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.4/lib                |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                |
| Is contained                | false                                      |
| Is homebrew                 | false                                     |
| Is installed via Fabric.app | false                                     |
| Xcode Path                  | ~/Downloads/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.127.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

**Comment by tedgonzalez** [comment]
I'm following this [stackoverflow post](https://stackoverflow.com/questions/57117153/how-to-make-fastlane-use-specific-version-of-openssl) in case other people are looking into it
