### ISSUE TITLE
Bundler::GemNotFound: Could not find CFPropertyList-3.0.0 in any of the sources

### ISSUE THREAD

**Issue by zhancheng** [fastlane/fastlane#15056]
fastlane 2.127.2

**Comment by ppamorim** [comment]
Run `bundle update --all`. Probably your dependencies are outdated.

**Comment by zhancheng** [comment]
@fastlane-bot  this mine fastlane env.
```shell
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.127.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.11.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>


*generated on:* **2019-07-22**
</details>
```

**Comment by zhancheng** [comment]
@ppamorim  when I execute ```shell bundle update --all ```  I got this below.

``` shell
/Library/Ruby/Site/2.3.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.3.0/rubygems.rb:303:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
192:haipei-flutter zhancheng$ fastlane env
```

**Comment by ppamorim** [comment]
Delete your `Gemfile.lock` and run `gem update bundler`.

**Comment by zhancheng** [comment]
@ppamorim 
too many Gemfile.lock  which should be deleted?
```shell
/usr/local/Homebrew/Library/Homebrew/Gemfile.lock
/usr/local/Homebrew/docs/Gemfile.lock
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/terminal-notifier-1.7.1/vendor/terminal-notifier/Ruby/Gemfile.lock
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/excon-0.55.0/Gemfile.lock
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.1/Gemfile.lock
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/security-0.1.3/Gemfile.lock
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.3/Gemfile.lock
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/os-0.9.6/Gemfile.lock
```

**Comment by ppamorim** [comment]
None of these, the one inside your project.

**Comment by janpio** [comment]
What command are you trying to execute @zhancheng? You deleted the issue template, which asks all the right questions we need to have answers for to be able to help you.
