### ISSUE TITLE
Unauthorized Access when I use Fastlane pilot upload

### ISSUE THREAD

**Issue by a-elnajjar** [fastlane/fastlane#15125]
### Unauthorized Access when I use Fastlane pilot upload

I am trying to upload the app to testFlight using action pilot. I have 2FA enabled, and entered the verification code. the requested session failed and "Unauthorized Access."

Notes:
My developer account is a member of an enterprise Apple developer.

- I have changed my password to a simple password with no special characters. "no use."  
- can't turn off my 2FA because of apple new rules on a developer  account 
- remove Fastlane-credential and added again "no use."

```
 You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/client.rb:852:in `block in send_request': [!] The request could not be completed because: (Spaceship::UnauthorizedAccessError)
	Unauthorized Access
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/client.rb:620:in `with_retry'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/client.rb:844:in `send_request'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/client.rb:688:in `request'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:12:in `handle_two_step_or_factor'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/client.rb:494:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/client.rb:770:in `do_login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/client.rb:384:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/client.rb:346:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/pilot/lib/pilot/manager.rb:23:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/pilot/lib/pilot/manager.rb:16:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/pilot/lib/pilot/build_manager.rb:17:in `upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.128.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'


<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G84)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.3                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| tty-screen                | 0.7.0        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.65.0       |
| rubyzip                   | 1.2.3        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.11.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| unicode-display_width     | 1.6.0        |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
</details>


*generated on:* **2019-08-07**
</details>

**Comment by janpio** [comment]
Please don't delete the issue template, it asks for the relevant information we need to understand a problem: `fastlane env` output and most importantly the _complete_  output of the command.

**Comment by anasUltimitATS** [comment]
i face the same issue , but  i try again and it work fine .

**Comment by a-elnajjar** [comment]
@janpio I have solved the issue. first, remove the `fastlane fastlane-credentials remove --username <appleID>`, second, create apple application password on AppleID  and use variable"FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD" .finally, run Fastlane pilot

**Comment by simonbengtsson** [comment]
We just got this as well. Output:

<details>
<summary>fastlane environment</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.19.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | âœ… |
| LC_ALL   | en_US.UTF-8 | âœ… |
| LANGUAGE | en_US.UTF-8 | âœ… |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'spaceship'
require 'date'

#
# PLATFORM ANDROID
#

platform :android do
    lane :playstore do |options|
      line_num = 0
      password = ""
      alias_username = ""
      alias_password = ""

      File.open('/android_release_files/auth').each do |line|
        line_num += 1
        if line_num == 1
            password = line.strip
        elsif line_num == 2
            alias_username = line.strip
        else
            alias_password = line.strip
        end
      end

      # Get the last version code and increment it.
      version_code = File.read('/android_release_files/versionnumber').to_i
      version_code = version_code + 1

      f = File.new('android_release_files/versionnumber', "w")
      f.write(version_code)
      f.close

      isoString = File.read('Workspace/android_release_files/releasedate').to_s
      version_name = File.read('/Workspace/android_release_files/versionname').to_s

      dateTime = DateTime.parse(isoString)
      today = DateTime.now
      string_array = version_name.split('.')

      first = string_array[0].to_i
      second = string_array[1].to_i
      third = string_array[2].to_i

      if dateTime.day == today.day then
        if (second + 1) > 9 then
          first = first + 1
          second = 0
          third = 0
        else
          second = second + 1
          third = 0
        end

        array = [ first, second, third ]
        version_name = array.join('.')
        newDate = dateTime + 14

        fs = File.new('/android_release_files/releasedate',"w")
        fs.write(newDate)
        fs.close

      else
      third = third + 1
      array = [ first, second, third ]
      version_name = array.join('.')
      print(version_name)
      end

      fil = File.new('/android_release_files/versioname',"w")
      fil.write(version_name)
      fil.close
      
      print version_code
      print version_name
      
      props = {
          "versionCode" => version_code,
          "versionName" => version_name,
          "android.injected.signing.store.file" => "/android_release_files/UploadKey.jks",
          "android.injected.signing.store.password" => password || options[:password] || prompt(text: "Sign key with password "),
          "android.injected.signing.key.alias" => alias_username || options[:alias] || prompt(text: "Enter alias for key "),
          "android.injected.signing.key.password" => alias_password || options[:alias_password] || prompt(text: "Enter password for alias " )
      }
     
      gradle(
        project_dir: './android/',
        task: ':app:assemble',
        build_type: 'release',
        print_command: false,
        properties: props
      )

      upload_to_play_store(
        package_name: 'xxx',
        track: 'internal',
        apk: "./android/app/build/outputs/apk/release/app-release.apk",
        json_key: '/android_release_files/api-5478903763947850773-82861-c5eb18547ca1.json',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        version_codes_to_retain: Array(1026)
      )
    end
end

#
# PLATFORM IOS
#

platform :ios do
  before_all do
    # Stuff
  end

  desc "Updates iOS version (update locale -> new react bundle -> bump version numbers -> commit -> push)"
  desc "Usage: fastlane ios version [type:none:patch|minor|major]"
  desc "type:none only updates version string if required, otherwise only build number"

  lane :version do |options|
    type = options[:type] || 'none'
    
    ensure_git_status_clean
        
    Dir.chdir("../ios") do
      repo_status = Actions.sh("git status --porcelain")
      repo_clean = repo_status.empty?
            
      # Check if repo is clean (in ios subfolder, ensure_git_status_clean can only check current folder?)
      if repo_clean
        UI.success('Git status is clean, all good! ðŸ’ª')
      else
        abort("The iOS repo is dirty (commit changes before running this command)")
      end
    end
    
    version = get_version_number(xcodeproj: "./ios/App.xcodeproj", target: "App")

    # Bump even if type is set to none if live version is same as current (upload will fail otherwise)
    if type == 'none'
        username = options[:username] || prompt(text: "Login to App Store Connect with username/email: ")
        Spaceship::Tunes.login(username)
        Spaceship::Tunes.client.team_id = "118281422"
        app = Spaceship::Tunes::Application.find(1133163586)

        # app.live_version.app_status == "Ready for sale" version when there is a newer version waiting for review
        
        if Gem::Version.new(app.latest_version.version) >= Gem::Version.new(version)
           type = 'patch'
           print("Current version cannot be lower than live version (will bump patch)")
        else
           UI.success("Versions ok: Current: #{version} Live: #{app.live_version.version}")
        end
    end

    Dir.chdir("../ios") do
      build = increment_build_number(
        xcodeproj: "./ios/Equilab.xcodeproj"
      )
    
      if type != 'none'
        increment_version_number(bump_type: type, xcodeproj: "./ios/Equilab.xcodeproj")
      end
      
      sh("npm run bundle-ios")
      sh("npm run update-locale-ios")
      
      version_name = "v#{version} (#{build})"
      sh("git add -A && git commit -m \"#{version_name}\"")
      sh("git push origin master")
      sh("git tag v#{version} --force && git push --tags -f")
    end
    
    sh("npm run ulc")
    sh("git tag ios-v#{version} -f && git push --tags -f")
    sh("git push origin master")
  end

  desc "Upload new version to TestFlight (build -> upload -> internal test flight -> upload symbols)"
  lane :deploy do |options|
    username = options[:username] || prompt(text: "Login to App Store Connect with username/email: ")
    Spaceship::Tunes.login(username)

    version = get_version_number(xcodeproj: "./ios/Equilab.xcodeproj", target: "Equilab")
    build_number = get_build_number(xcodeproj: "./ios/Equilab.xcodeproj")

    today = Date.parse(Time.at(Time.now.to_i - 3600 * 4).to_s)
    is_release_week = today.cweek % 2 != 0
    is_wednesday = today.wday == 3
    is_friday = today.wday == 5
    is_scheduled_time = DateTime.now.hour >= 18 || DateTime.now.hour < 4

    UI.success("Release week: #{is_release_week} Wednesday: #{is_wednesday} Friday: #{is_friday} Time: #{is_scheduled_time}")

    UI.success("Will build and upload #{version} (#{build_number}) with user #{username}")

    build_ios_app(
      workspace: "./ios/Equilab.xcworkspace",
      output_directory: "./ios",
      export_xcargs: "-allowProvisioningUpdates",
      xcpretty_formatter: './fastlane/xcpretty-json-formatter.rb',
      analyze_build_time: true,
      scheme: "Release",
      clean: true
    )

    # Retry upload 5 times since iTMSTransporter often fails on us with this error:
    # "An error occurred while uploading the package: 1133163586.itmsp."
    begin
      retries ||= 0
      UI.message("Starting attempt #{retries} at uploading build...")
      upload_to_testflight(
        groups: is_wednesday ? ["External"] : [],
        notify_external_testers: is_release_week && is_wednesday,
        changelog: "New features and bugfixes",
        ipa: "./ios/Equilab.ipa",
        username: username,
        reject_build_waiting_for_review: true
      )
    rescue
      retry if (retries += 1) < 5
      raise
    end

    UI.success("Release week: #{is_release_week} Wednesday: #{is_wednesday} Friday: #{is_friday} Time: #{is_scheduled_time}")
    if (is_wednesday || is_friday) && is_release_week && is_scheduled_time
      begin
          # Set release notes separately to avoid having to store and upload all meta data
          # https://github.com/fastlane/fastlane/issues/3716
          set_release_notes(notes: "Bug fixes and improvements", username: username, version: version)

          upload_to_app_store(
            username: username,
            build_number: build_number,
            app_version: version,
            submission_information: {
                :add_id_info_tracks_install => true,
                :add_id_info_uses_idfa => true,
            },
            submit_for_review: true,
            reject_if_possible: true,
            automatic_release: false,
            force: true,
            skip_metadata: true,
            skip_screenshots: true,
            skip_binary_upload: true
          )
      rescue
        # This failed often, but we still want to upload dsyms etc
        UI.error("Submit to app store failed")
      end
    end

    # Experiment with sleep here since we had an issue were dsyms were not immediately
    # available after upload_to_testflight
    UI.success("Sleep for 10 min...")
    sleep(60 * 10)

    # No need to upload non bitcode dsyms
    # sh("rm ../ios/Equilab.app.dSYM.zip || true")

    download_dsyms(
      version: version,
      build_number: build_number,
      username: username
    )

    upload_symbols_to_crashlytics(
      gsp_path: "./ios/GoogleService-Info.plist",
      binary_path: "./ios/Pods/Fabric/upload-symbols"
    )

  end

  lane :symbols do |options|
      username = options[:username] || prompt(text: "Login to App Store Connect with username/email: ")
      version = prompt(text: "Version to fetch: ")
      bn = prompt(text: "Build number to fetch (\"all\" or number): ")
      if bn == "all"
        bn = nil
      end

      download_dsyms(
        version: version,
        build_number: bn,
        username: username
      )

      upload_symbols_to_crashlytics(
        gsp_path: "./ios/GoogleService-Info.plist",
        binary_path: "./ios/Pods/Fabric/upload-symbols"
      )
  end

  lane :play do |options|
    begin
      retries ||= 0
      puts "try ##{ retries }"
      raise "the roof"
    rescue Exception => e
      retry if (retries += 1) < 3
      raise
    end
  end

  lane :tests do
    run_tests(
        workspace: "./ios/App.xcworkspace",
        scheme: "Release"
    )
  end

  # Inspired by https://github.com/fastlane/fastlane/issues/13635
  lane :set_release_notes do |options|
    username = options[:username] || prompt(text: "Login to App Store Connect with username/email: ")
    notes = options[:notes] || prompt(text: "Release notes: ")
    force = options[:force]
    app_version = options[:version]

    Spaceship::Tunes.login(username)
    app = Spaceship::Tunes::Application.find(xxx)

    if app_version
        changed = app.ensure_version!(app_version, platform: nil)
        UI.success("Ensured version #{app_version}. Changed: #{changed}")
    end

    version = app.edit_version

    if version.nil?
        UI.abort("No version to set release notes for")
    end

    release_notes = version.release_notes
    release_notes.languages.each do |key|
      value = release_notes[key]
      if value.to_s.size == 0 || force
        release_notes[key] = notes
      end
    end

    version.save!
  end

  after_all do |lane|
    # Stuff
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "xxx"

team_id "xxx" 
itc_team_id "xxx" 
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | âœ… Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.11.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>


*generated on:* **2019-08-06**
</details>
