### ISSUE TITLE
Spaceship - PotentialServerError on save! method

### ISSUE THREAD

**Issue by sp-luciano-chinke** [fastlane/fastlane#15246]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am trying to upload trailers/videos to App Store using Spaceship, without success. The only output error received is the following: 

```
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/tunes/tunes_client.rb:228:in `handle_itc_response': Unexpected Error (Spaceship::Tunes::PotentialServerError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/tunes/tunes_client.rb:445:in `block in update_app_version!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1517:in `with_tunes_retry'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/tunes/tunes_client.rb:438:in `update_app_version!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/spaceship/lib/spaceship/tunes/app_version.rb:408:in `save!'
	from /fastlane/upload.rb:60:in `<main>'
```

I have checked all docs, lines of code, variables and I can't find anything about this. 

##### Command executed

I am executing a ruby file that uploads trailers. The workflow is something like:

```
v = app.edit_version
v.upload_trailer!(video_path, sort_order.to_i, language, device, timestamp, thumb_path)
v.save!
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.22.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G87)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.66.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-08-30**
</details>

**Comment by sp-luciano-chinke** [comment]
# Update
This happens when I try to upload videos with the main language (en-US). When I try to do it with a secondary language, already activated, i receive no error message; everything seems fine. 

BUT, in the response of `v.save!` (that you can catch with puts) the trailer doesn't appear there (and yes in puts `v.upload_trailer!`. In App Store Connect no video is shown, so it seem that is not working either. :(

**Comment by sp-luciano-chinke** [comment]
Any news about this? 

My script can change the metadata of the project and I can upload the desired video manually to iTunes Connect. So, it still seems a problem of spaceship and not a problem caused by me...

**Comment by sp-luciano-chinke** [comment]
Hi, I tried to upload a preview again after upgrading fastlane but the same behaviour is still happening. PotentialServerError for the main languague (en-US), no error (but no upload) for a secondary language.

**Comment by sp-luciano-chinke** [comment]
Now, when I try to upload manually the app preview through itunes connect with Chrome, this error appears: 

To upload your app previews, you must use Safari and OS X v10.10 or later.

When I try to upload it manually with Safari, it uploads witouth problem.

**Comment by sp-luciano-chinke** [comment]
Hi, I tried to upload a preview again after upgrading fastlane but the same behaviour is still happening. PotentialServerError for the main languague (en-US), no error (but no upload) for a secondary language.
