### ISSUE TITLE
[Fastlane.Swift] undefined method '[]' for nil:NilClass

### ISSUE THREAD

**Issue by jhandguy** [fastlane/fastlane#15257]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.130.0`]
- Last working version: [e.g. `2.129.0`]

### Regression Description

Updating Fastlane to the latest version (2.130.0) broke Fastlane Swift.
Right after upgrading FastlaneSwiftRunner, the lane ran just fine. But once running again (with already updated FastlaneSwiftRunner), it seems that the script responsible for checking if the runner is up to date crashes.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
➜ bundle exec fastlane runTests --verbose
[✔] 🚀
DEBUG [2019-09-02 10:34:47.48]: Checking if there are any plugins that should be loaded...
INFO [2019-09-02 10:34:47.59]: loading manifest: /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/swift/upgrade_manifest.json
DEBUG [2019-09-02 10:34:47.62]: No missing groups found, so we don't need to worry about adding new groups
WARN [2019-09-02 10:34:47.62]: Lane Context:
INFO [2019-09-02 10:34:47.62]: {:LANE_NAME=>"runTests"}
ERROR [2019-09-02 10:34:47.62]: undefined method `[]' for nil:NilClass
ERROR [2019-09-02 10:34:47.62]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `[]' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60%5B%5D%27%20for%20nil+repo:fastlane/fastlane
➡️  Pilot - undefined method `strip' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15204 [open] 10 💬
    2 weeks ago

➡️  [pilot] undefined method `id' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15138 [open] 15 💬
    4 days ago

➡️  [Spaceship] Error 'undefined method `each' for nil:NilClass' when using Spaceship::Portal::Persons
    https://github.com/fastlane/fastlane/issues/15216 [open] 3 💬
    a day ago

and 399 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/xxxxx/vendor/bundle/ruby/2.6.0/bin/fastlane)
NoMethodError: [!] undefined method `[]' for nil:NilClass
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/swift_runner_upgrader.rb:93:in `file_needs_update?'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/swift_runner_upgrader.rb:111:in `copy_file_if_needed!'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/swift_runner_upgrader.rb:62:in `block in upgrade_files!'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/swift_runner_upgrader.rb:61:in `each'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/swift_runner_upgrader.rb:61:in `upgrade_files!'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/swift_runner_upgrader.rb:47:in `upgrade_if_needed!'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/swift_lane_manager.rb:265:in `ensure_runner_up_to_date_fastlane!'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/swift_lane_manager.rb:34:in `cruise_lane'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.130.0/bin/fastlane:23:in `<top (required)>'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/xxxxx/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
  </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 10.14.6                                                    |
| Ruby                        | 2.6.3                                                      |
| Bundler?                    | true                                                       |
| Git                         | git version 2.20.1 (Apple Git-117)                         |
| Installation Source         | ~/xxxxx/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G87)                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib                           |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                                |
| Is contained                | false                                                      |
| Is homebrew                 | false                                                      |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 10.3                                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-09-02**
</details></pre>
</details>

**Comment by jhandguy** [comment]
After removing `Actions.swift` and `Plugins.swift` from the `SwiftRunnerProject`, running a lane without upgrading the project works fine.

While investigating those 2 new files in detail, I found out what the issue is:
**Both Actions.swift and Plugins.swift are missing a `// Generated with fastlane 2.108.0` at the end.** 

@joshdholtz I will push a PR to you guys 👍
