### ISSUE TITLE
INSTRUMENTATION_RESULT: shortMsg=Process crashed.

### ISSUE THREAD

**Issue by Raymond1337** [fastlane/fastlane#15367]
- [x] Updated fastlane to the latest version
- [x] I read the Contribution Guidelines
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Subject
Tool: Fastlane / Sceengrab
It seems Screengrab errors out with the GoogleInstrumentationTestRunner.

#### Description
Expected behavior: Screenshots are taken.
The test class is a copy of the one in the setup manual.

Code:
<details><summary>♨️ Java JUnitTestClass ♨️</summary>

```
@RunWith(JUnit4.class)
public class ScreenShots {

    @ClassRule
    public static final LocaleTestRule localeTestRule = new LocaleTestRule();

    @Rule
    public GrantPermissionRule mRuntimePermissionRule = GrantPermissionRule .grant(Manifest.permission.CHANGE_CONFIGURATION);

    @Rule
    public ActivityTestRule<DashboardActivity> activityRule = new ActivityTestRule<>(DashboardActivity.class);

    @Test
    public void testTakeScreenshot() {
        Screengrab.screenshot("before_button_click");
        onView(withId(R.id.cardView_transmitted)).perform(click());
        Screengrab.screenshot("after_button_click");
    }
}
```
</details>

Error Log:
<details><summary>🔍 Terminal output 🔍</summary>

```
Computer:project-android me$ bundle exec fastlane screengrab --verbose
[✔] 🚀 
DEBUG [2019-09-24 12:23:12.53]: Couldn't find xcodebuild at /Library/Developer/CommandLineTools//usr/bin/xcodebuild, check that it exists
Successfully loaded Appfile at path '/Users/me/project-android/fastlane/Appfile'
- package_name: '[Package name]'
-------
INFO [2019-09-24 12:23:12.55]: Successfully loaded '/Users/me/project-android/fastlane/Screengrabfile' 📄

+-----------------------------+---------------------------------------------+
|             Detected Values from './fastlane/Screengrabfile'              |
+-----------------------------+---------------------------------------------+
| test_instrumentation_runner | com.google.android.apps.common.testing.tes  |
|                             | trunner.GoogleInstrumentationTestRunner     |
| app_package_name            | [Flavor.name]                        |
| tests_package_name          | [Flavor.name.test]                   |
| use_tests_in_packages       | ["[Package.name]"]                   |
| app_apk_path                | /Users/me/project-android/app/buil  |
|                             | d/outputs/apk/flavorF/debug/app-flavor-debug.apk     |
| tests_apk_path              | /Users/me/project-android/app/buil  |
|                             | d/outputs/apk/androidTest/flavorF/debug/app-flavorF-  |
|                             | debug-androidTest.apk                       |
| locales                     | ["en-US", "de"]                             |
| clear_previous_screenshots  | true                                        |
+-----------------------------+---------------------------------------------+


+-----------------------------+---------------------------------------------+
|                      Summary for screengrab 2.131.0                       |
+-----------------------------+---------------------------------------------+
| android_home                | /Users/me/Library/Android/sdk/         |
| locales                     | ["en-US", "de"]                             |
| clear_previous_screenshots  | true                                        |
| output_directory            | fastlane/metadata/android                   |
| skip_open_summary           | false                                       |
| app_package_name            | [Flavor.name]                        |
| tests_package_name          | [Flavor.name.test]                   |
| use_tests_in_packages       | ["[Package.name]"]                   |
| test_instrumentation_runner | com.google.android.apps.common.testing.tes  |
|                             | trunner.GoogleInstrumentationTestRunner     |
| ending_locale               | en-US                                       |
| app_apk_path                | /Users/me/project-android/app/buil  |
|                             | d/outputs/apk/flavorF/debug/app-flavor-debug.apk     |
| tests_apk_path              | /Users/me/project-android/app/buil  |
|                             | d/outputs/apk/androidTest/flavorF/debug/app-flavorF-  |
|                             | debug-androidTest.apk                       |
| device_type                 | phone                                       |
| exit_on_test_failure        | true                                        |
| reinstall_app               | false                                       |
+-----------------------------+---------------------------------------------+

INFO [2019-09-24 12:23:12.65]: Clearing phoneScreenshots within fastlane/metadata/android
INFO [2019-09-24 12:23:12.65]: $ /Users/me/Library/Android/sdk/platform-tools/adb devices -l
INFO [2019-09-24 12:23:12.66]: ▸ List of devices attached
INFO [2019-09-24 12:23:12.66]: ▸ FA7C61A01112           device usb:338690048X product:walleye model:Pixel_2 device:walleye transport_id:1
INFO [2019-09-24 12:23:12.66]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell echo \$EXTERNAL_STORAGE
INFO [2019-09-24 12:23:12.68]: ▸ /sdcard
INFO [2019-09-24 12:23:12.68]: Cleaning screenshots on device
INFO [2019-09-24 12:23:12.70]: ▸ ls: /sdcard/[Flavor.name]/screengrab: No such file or directory
ls: /sdcard/[Flavor.name]/screengrab: No such file or directory
ERROR [2019-09-24 12:23:12.70]: Exit status: 1
INFO [2019-09-24 12:23:12.73]: ▸ ls: /data/data/[Flavor.name]/app_screengrab: Permission denied
ls: /data/data/[Flavor.name]/app_screengrab: Permission denied
ERROR [2019-09-24 12:23:12.73]: Exit status: 1
INFO [2019-09-24 12:23:12.73]: Validating app APK
INFO [2019-09-24 12:23:12.73]: $ /Users/me/Library/Android/sdk/build-tools/28.0.3/aapt dump permissions /Users/me/project-android/app/build/outputs/apk/flavirF/debug/app-flavorF-debug.apk
INFO [2019-09-24 12:23:12.74]: ▸ package: [Flavor.name]
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='android.permission.CAMERA'
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='android.permission.INTERNET'
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
INFO [2019-09-24 12:23:12.74]: ▸ uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
INFO [2019-09-24 12:23:12.74]: Installing app APK
INFO [2019-09-24 12:23:12.74]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 install -t -r /Users/me/project-android/app/build/outputs/apk/flavorF/debug/app-flavorF-debug.apk
INFO [2019-09-24 12:23:12.75]: ▸ Performing Streamed Install
INFO [2019-09-24 12:23:14.16]: ▸ Success
INFO [2019-09-24 12:23:14.16]: Installing tests APK
INFO [2019-09-24 12:23:14.16]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 install -t -r /Users/me/project-android/app/build/outputs/apk/androidTest/flavorF/debug/app-flavorF-debug-androidTest.apk
INFO [2019-09-24 12:23:14.17]: ▸ Performing Streamed Install
INFO [2019-09-24 12:23:14.86]: ▸ Success
INFO [2019-09-24 12:23:14.86]: Granting the permission necessary to change locales on the device
INFO [2019-09-24 12:23:14.86]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell pm grant [Flavor.name] android.permission.CHANGE_CONFIGURATION
INFO [2019-09-24 12:23:14.90]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell getprop ro.build.version.sdk
INFO [2019-09-24 12:23:14.92]: ▸ 29
INFO [2019-09-24 12:23:14.92]: Granting the permissions necessary to access device external storage
INFO [2019-09-24 12:23:14.92]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell pm grant [Flavor.name] android.permission.WRITE_EXTERNAL_STORAGE
INFO [2019-09-24 12:23:14.99]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell pm grant [Flavor.name] android.permission.READ_EXTERNAL_STORAGE
INFO [2019-09-24 12:23:15.04]: Running tests for locale: en-US
INFO [2019-09-24 12:23:15.04]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
-e package [Package.name] \
[Package.name.test]/com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner
INFO [2019-09-24 12:23:15.80]: ▸ INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INFO [2019-09-24 12:23:15.80]: ▸ INSTRUMENTATION_CODE: 0
INFO [2019-09-24 12:23:15.83]: Running tests for locale: de
INFO [2019-09-24 12:23:15.83]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell am instrument --no-window-animation -w \
-e testLocale de \
-e endingLocale en_US \
-e package [Package.name] \
[Flavor.name.test]/com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner
INFO [2019-09-24 12:23:16.66]: ▸ INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INFO [2019-09-24 12:23:16.66]: ▸ INSTRUMENTATION_CODE: 0
INFO [2019-09-24 12:23:16.70]: Pulling captured screenshots from the device
DEBUG [2019-09-24 12:23:16.70]: Starting screenshot count is: 0
INFO [2019-09-24 12:23:16.73]: ▸ ls: /sdcard/[Flavor.name]/screengrab: No such file or directory
ls: /sdcard/[Flacor.name]/screengrab: No such file or directory
ERROR [2019-09-24 12:23:16.73]: Exit status: 1
INFO [2019-09-24 12:23:16.78]: ▸ ls: /data/data/[Flavor.name]/app_screengrab: Permission denied
ls: /data/data/[Flacor.name]/app_screengrab: Permission denied
ERROR [2019-09-24 12:23:16.78]: Exit status: 1
DEBUG [2019-09-24 12:23:16.78]: Ending screenshot count is: 0
ERROR [2019-09-24 12:23:16.78]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneCommonException: [!] No screenshots were detected 📷❌
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/interface.rb:184:in `abort_with_message!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/screengrab/lib/screengrab/runner.rb:309:in `pull_screenshots_from_device'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/screengrab/lib/screengrab/runner.rb:72:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
```
</details>

Fastlane env:
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G95)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build and take screenshots"
  lane :screenshots do
    gradle(
      task:"clean"
    )
    build_android_app(
      task: 'assemble',
  	  properties: {
    		# // sensitive data commented out
    		},
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
  	  properties: {
    		# // sensitive data commented out
    		},
      build_type: 'AndroidTest' # Screenshots are done in AndroidTest
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>
```
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("[Package name]") # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.66.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.4        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-09-17**
</details>

**Comment by TheIronMarx** [comment]
I've run into the same issue. I've made some progress by updating my test dependencies to their androidx replacements. Most critically, `testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"` -> `testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"` 

It doesn't work yet, but at least I get a stack trace now. I'll report back if I discover anything else.
FWIW, here's the stacktrace.
```
android.util.AndroidException: INSTRUMENTATION_FAILED: com.myapp.testableapp.test/android.support.test.runner.AndroidJUnitRunner
	at com.android.commands.am.Instrument.run(Instrument.java:486)
	at com.android.commands.am.Am.runInstrument(Am.java:194)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)```

**Comment by TheIronMarx** [comment]
I'm not sure if I missed this the first time or if something changed, but this now accompanies my stack trace.
```
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.myapp.asdf.test/android.support.test.runner.AndroidJUnitRunner}```

Running `adb shell pm list instrumentation`, I see my Androidx test runner, specifically `androidx.test.runner.AndroidJUnitRunner`, but the stack trace is complaining about missing the wrong one.

@janpio Could it be an issue with the internals of Screengrab referencing the wrong, pre-AndroidX AndroidJUnitRunner? I wouldn't even know where to begin verifying this.

**Comment by TheIronMarx** [comment]
Bingo!

As per https://docs.fastlane.tools/actions/capture_android_screenshots/#parameters, one can manually specify which instrumentation runner to use. The default, android.support.test.runner.AndroidJUnitRunner, is in fact not Androidx compatible. I added the following argument to my command to explicitly override it -- `--test_instrumentation_runner androidx.test.runner.AndroidJUnitRunner`

**Comment by Raymond1337** [comment]
Thank you so very much. 
You can also override the test runner in the Screengrabfile:
test_instrumentation_runner('androidx.test.runner.AndroidJUnitRunner')
