### ISSUE TITLE
Unable to push the App to Testflight

### ISSUE THREAD

**Issue by rkhandelwal17** [fastlane/fastlane#15390]
Hi All,

While pushing the App to TestFlight I am receiving the below error. Is this an intermittent issue with Testflight from past couple of days as I was able to push the app to TestFlight 2 days ago
Also attaching fastlane env output below

```
build	27-Sep-2019 16:06:38	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [31m[Transporter Error Output]: Could not start delivery: all transports failed diagnostics
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [31mTransporter transfer failed.[0m
build	27-Sep-2019 16:07:17	[16:07:17]: 
build	27-Sep-2019 16:07:17	[16:07:17]: [31mCould not resolve hostname: contentdelivery.itunes.apple.com.
build	27-Sep-2019 16:07:17	Could not start delivery: all transports failed diagnostics
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] [2019-09-27 16:07:17 AEST] <Transport Protocol> DEBUG: Received failed transfer notification; aborting
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] [2019-09-27 16:07:17 AEST] <Transport Protocol>  INFO: The Signiant transfer engine's status is CONNECTING
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] Exception in thread "Transport Protocol Seeker" java.lang.ArrayIndexOutOfBoundsException: 1
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$5.run(TransferEngine.java:3603)
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] [2019-09-27 16:07:17 AEST] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] [2019-09-27 16:07:17 AEST] <main> ERROR: Could not start delivery: all transports failed diagnostics
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] 
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] 
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] 
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] Package Summary:
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter]  
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] 1 package(s) were not uploaded because they had problems:
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] 	/var/folders/tl/2mv00gpj0n3223y_4mbvcgrr0000gr/T/d20190927-37711-c657h7/1480800005.itmsp - Error Messages:
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] 		Could not start delivery: all transports failed diagnostics
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: [33m[iTMSTransporter] [2019-09-27 16:07:17 AEST] <main> DBG-X: Returning 1
build	27-Sep-2019 16:07:17	[0m
build	27-Sep-2019 16:07:17	[16:07:17]: iTunes Transporter output above ^


<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.6                                          |
| Ruby                        | 2.6.3                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.17.2 (Apple Git-113)               |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane      |
| Host                        | Mac OS X 10.14.6 (18G103)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_10.1.app/Contents/Developer/ |
| Xcode Version               | 10.1                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.129.0 | 🚫 Update available |


### Loaded fastlane plugins:

| Plugin                                | Version | Update-Status |
| ------------------------------------- | ------- | ------------- |
| fastlane-plugin-airwatch_workspaceone | 2.2.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                   | Version      |
| ------------------------------------- | ------------ |
| did_you_mean                          | 1.3.0        |
| slack-notifier                        | 2.3.2        |
| atomos                                | 0.1.3        |
| CFPropertyList                        | 3.0.1        |
| claide                                | 1.0.3        |
| colored2                              | 3.1.2        |
| nanaimo                               | 0.2.6        |
| xcodeproj                             | 1.12.0       |
| rouge                                 | 2.0.7        |
| xcpretty                              | 0.3.0        |
| terminal-notifier                     | 2.0.0        |
| unicode-display_width                 | 1.6.0        |
| terminal-table                        | 1.8.0        |
| plist                                 | 3.5.0        |
| public_suffix                         | 2.0.5        |
| addressable                           | 2.6.0        |
| multipart-post                        | 2.0.0        |
| word_wrap                             | 1.0.0        |
| tty-screen                            | 0.7.0        |
| tty-cursor                            | 0.7.0        |
| tty-spinner                           | 0.9.1        |
| babosa                                | 1.0.2        |
| colored                               | 1.2          |
| highline                              | 1.7.10       |
| commander-fastlane                    | 4.4.6        |
| excon                                 | 0.66.0       |
| faraday                               | 0.15.4       |
| unf_ext                               | 0.0.7.6      |
| unf                                   | 0.1.4        |
| domain_name                           | 0.5.20190701 |
| http-cookie                           | 1.0.3        |
| faraday-cookie_jar                    | 0.0.6        |
| fastimage                             | 2.1.5        |
| gh_inspector                          | 1.1.3        |
| json                                  | 2.2.0        |
| mini_magick                           | 4.9.5        |
| multi_xml                             | 0.6.0        |
| rubyzip                               | 1.2.3        |
| security                              | 0.1.3        |
| xcpretty-travis-formatter             | 1.0.0        |
| dotenv                                | 2.7.5        |
| faraday_middleware                    | 0.13.1       |
| naturally                             | 2.2.0        |
| simctl                                | 1.6.5        |
| jwt                                   | 2.1.0        |
| uber                                  | 0.1.0        |
| declarative                           | 0.0.10       |
| declarative-option                    | 0.1.0        |
| representable                         | 3.0.4        |
| retriable                             | 3.1.2        |
| mime-types-data                       | 3.2019.0331  |
| mime-types                            | 3.2.2        |
| multi_json                            | 1.13.1       |
| signet                                | 0.11.0       |
| memoist                               | 0.16.0       |
| os                                    | 1.0.1        |
| googleauth                            | 0.6.7        |
| httpclient                            | 2.8.3        |
| google-api-client                     | 0.23.9       |
| bundler                               | 1.17.2       |
| digest-crc                            | 0.4.1        |
| google-cloud-env                      | 1.2.1        |
| google-cloud-core                     | 1.3.1        |
| google-cloud-storage                  | 1.16.0       |
| emoji_regex                           | 1.0.1        |
| mini_portile2                         | 2.4.0        |
| nokogiri                              | 1.10.4       |
| http-accept                           | 1.7.0        |
| netrc                                 | 0.11.0       |
| rest-client                           | 2.1.0        |
| pngdefry                              | 0.1.3        |
| ruby_android                          | 0.7.7        |
| image_size                            | 1.5.0        |
| app-info                              | 1.1.0        |
| fastlane-plugin-airwatch_workspaceone | 2.2.0        |
</details>


*generated on:* **2019-09-27**
</details>

**Comment by werderpoddi** [comment]
I have the same Problem, I could not upload the App with fastlane. I tried uploading the App with Xcode and the same AppstoreConnect User (App-Manager-Role) but it did not work. Just with a different User including the Admin and Account-Holder-Role I managed to upload the App manually. 2 days ago everything I did upload the last version successfully with fastlane to AppstoreConnect.

**Comment by atom-wintermute** [comment]
Same for me

**Comment by virus91** [comment]
Same for me

**Comment by SimonErm** [comment]
https://github.com/fastlane/fastlane/pull/15387

**Comment by reuvenlevitsky** [comment]
Apple has update the AppStoreConnect's terms of service. You need to login to their portal and approve them. Then you could update as usual.

**Comment by jalmaas** [comment]
> Apple updated the AppStoreConnect's terms of service. You need to login to their portal and approve them. Then you could upload as usual.

Don't think it's that. I get the same error mostly, but some builds go through and gets uploaded. I have no terms of service that needs to be approved

**Comment by lordnelson** [comment]
I just had the same error and was able to uploaded manually. However inside the AppStoreConnect webapp there was an issue with encryption compliance. I completed the questions which results in a new property to include in your `info.plist`: `App Uses Non-Exempt Encryption`. After that I retried fastlane and it works successfully when uploading a beta to TestFlight.

This might be an issue only related to me but thought I'd add it here in case it helps anyone else.

**Comment by andreyoshev** [comment]
Same: sometimes it's ok, sometimes it's failed.

**Comment by jalmaas** [comment]
> I just had the same error and was able to uploaded manually. However inside the AppStoreConnect webapp there was an issue with encryption compliance. I completed the questions which results in a new property to include in your `info.plist`: `App Uses Non-Exempt Encryption`. After that I retried fastlane and it works successfully when uploading a beta to TestFlight.
> 
> This might be an issue only related to me but thought I'd add it here in case it helps anyone else.

Might have been a coincidence. I've used that key in the info.plist for a while, so I don't think it's the culprint for this issue. But nice if it is a solution for some :)

**Comment by werderpoddi** [comment]
> > Apple updated the AppStoreConnect's terms of service. You need to login to their portal and approve them. Then you could upload as usual.
> 
> Don't think it's that. I get the same error mostly, but some builds go through and gets uploaded. I have no terms of service that needs to be approved

Me too I accepted every Terms and conditions this morning, and still have these Problems.

**Comment by ilkengin** [comment]
I have the same issue as well. I am behind a firewall and I realized today fastlane started to use **signiant** to upload the .ipa file even I set `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS` I tried with `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"` and `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV -Dhttp.proxyHost=MY_PROXY -Dhttp.proxyPort=MY_PROXY_PORT"` Both didn't work for me.

I tried to update iTMSTransporter to v2.0.0 and then tried with `xcrun altool --upload-app` and I got the same issue. Then I tried with`xcrun altool --upload-app -ITunesTransport DAV` and then it worked. So, setting the ITunesTransport parameter helped me.

**Comment by mollyIV** [comment]
👋 @ilkengin , 
most probably relates to https://github.com/fastlane/fastlane/issues/15375.

**Comment by Andrewpk** [comment]
It's failing every time for me. Getting fun stuff like the following:
```
[15:12:44]: [Transporter Warning Output]: The following option was specified but is not recognized: -t DAV

[15:16:43]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics

[15:16:43]: Transporter transfer failed.
[15:16:43]: The following option was specified but is not recognized: -t DAV

[15:16:43]: Could not start delivery: all transports failed diagnostics

[15:16:43]: The following option was specified but is not recognized: -t DAV
```

**Comment by derrikammons** [comment]
It's failing to upload for me too.  It was working on Sep 24th but failed on Sep 27th.  I upload 2 apps, the free version and the paid version sequentially.  The first free app uploads fine, but the second one gets the following error:

`[iTMSTransporter] Exception in thread "Transport Protocol Seeker" java.lang.ArrayIndexOutOfBoundsException: 2`

Here's a more complete log:

```[2019-09-27T20:03:53.454Z] [13:03:52]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [32m----------------------------------------[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [32m--- Step: Verifying fastlane version ---[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [32m----------------------------------------[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: Your fastlane version 2.131.0 matches the minimum requirement of 1.99.0  ✅
[2019-09-27T20:03:54.018Z] [13:03:53]: [32m------------------------------[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [32m--- Step: default_platform ---[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [32m------------------------------[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [31m------------------------------------------------[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [31mName of the lane 'appstore' is already taken by the action named 'appstore'[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [31m------------------------------------------------[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [32mDriving the lane 'ios wbEliteBeta' 🚀[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [32m------------------------[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [32m--- Step: testflight ---[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: [32m------------------------[0m
[2019-09-27T20:03:54.018Z] [13:03:53]: Login to App Store Connect (****)
[2019-09-27T20:03:54.018Z] Available session is not valid any more. Continuing with normal login.
[2019-09-27T20:03:55.855Z] [13:03:55]: Login successful
[2019-09-27T20:03:57.097Z] [13:03:56]: [32mReady to upload new build to TestFlight (App: 310647896)...[0m
[2019-09-27T20:03:58.263Z] [13:03:58]: Going to upload updated app to App Store Connect
[2019-09-27T20:03:58.263Z] [13:03:58]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [31m[Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [31mTransporter transfer failed.[0m
[2019-09-27T20:09:01.217Z] [13:08:49]: 
[2019-09-27T20:09:01.217Z] [13:08:49]: [31mCould not start delivery: all transports failed diagnostics
[0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] [2019-09-27 13:08:49 PDT] <main>  INFO: Using Signiant UDP transport
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] [2019-09-27 13:08:49 PDT] <main> DBG-X: Setting the target rate to 15000001 bytes per second.
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] [2019-09-27 13:08:49 PDT] <main> DBG-X: Setting the throttle to 12500000 bytes per second.
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] Exception in thread "Transport Protocol Seeker" java.lang.ArrayIndexOutOfBoundsException: 2
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$5.run(TransferEngine.java:3603)
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] [2019-09-27 13:08:49 PDT] <main> ERROR: Could not start delivery: all transports failed diagnostics
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] 
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] 
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] 
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] Package Summary:
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter]  
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] 	/var/folders/8w/zk20tjq15_j2m074x8yvd0h00000gn/T/d20190927-92541-vo1bl6/310647896.itmsp - Error Messages:
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] 		Could not start delivery: all transports failed diagnostics
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: [33m[iTMSTransporter] [2019-09-27 13:08:49 PDT] <main> DBG-X: Returning 1
[2019-09-27T20:09:01.217Z] [0m
[2019-09-27T20:09:01.217Z] [13:08:49]: iTunes Transporter output above ^
[2019-09-27T20:09:01.217Z] [13:08:49]: [31mCould not start delivery: all transports failed diagnostics
[2019-09-27T20:09:01.217Z] Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
[2019-09-27T20:09:01.217Z] The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m
[2019-09-27T20:09:01.217Z] +------------------+-----------------+
[2019-09-27T20:09:01.217Z] |            [33mLane Context[0m            |
[2019-09-27T20:09:01.217Z] +------------------+-----------------+
[2019-09-27T20:09:01.217Z] | DEFAULT_PLATFORM | ios             |
[2019-09-27T20:09:01.217Z] | PLATFORM_NAME    | ios             |
[2019-09-27T20:09:01.217Z] | LANE_NAME        | ios wbEliteBeta |
[2019-09-27T20:09:01.217Z] +------------------+-----------------+
[2019-09-27T20:09:01.217Z] [13:08:49]: [31mError uploading ipa file, for more information see above[0m
[2019-09-27T20:09:01.217Z] 
[2019-09-27T20:09:01.217Z] +------+----------------------------+-------------+
[2019-09-27T20:09:01.217Z] |                [32mfastlane summary[0m                 |
[2019-09-27T20:09:01.217Z] +------+----------------------------+-------------+
[2019-09-27T20:09:01.217Z] | Step | Action                     | Time (in s) |
[2019-09-27T20:09:01.217Z] +------+----------------------------+-------------+
[2019-09-27T20:09:01.217Z] | 1    | Verifying fastlane version | 0           |
[2019-09-27T20:09:01.217Z] | 2    | default_platform           | 0           |
[2019-09-27T20:09:01.217Z] | 💥   | [31mtestflight[0m                 | 296         |
[2019-09-27T20:09:01.217Z] +------+----------------------------+-------------+
[2019-09-27T20:09:01.217Z] 
[2019-09-27T20:09:01.217Z] [13:08:49]: [31mfastlane finished with errors[0m
[2019-09-27T20:09:01.217Z] [31m
[2019-09-27T20:09:01.217Z] [!] Error uploading ipa file, for more information see above[0m```

Here's the `fastlane env`:

```<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.19.2                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D42)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.2       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.3.2        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.1       |
| unf_ext | 0.0.7.5 |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.4.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.0.3        |
| psych                     | 2.2.2        |
</details>


*generated on:* **2019-09-28**
</details>```

**Comment by ilkengin** [comment]
> 👋 @ilkengin ,
> most probably relates to #15375.

Thank you, I tried setting `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS=“-t DAV #”` and it's working like a charm! However, there should be a proper explanation for that.

**Comment by AnarionII** [comment]
I had the same issue, but because I was using upload_to_testflight the workaround that worked for me was:

(in Fastfile)
ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV #"
upload_to_testflight()

**Comment by Neilpoulin** [comment]
This just started happening to me earlier this morning (6 hours ago or so). I had successfully been uploading builds to testflight via fastlane only a few hours or less before that. Not sure why it all of a sudden started failing unless it had to do with the date change to Oct 1 in the Pacific timezone. The workaround provided vy @AnarionII et al worked for me. Thanks!

**Comment by jjlehtinen** [comment]
Seems like `Signiant` fails but `Aspera` seems to work. `/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter -m diagnostic -t <transport> -u <username> -p <password>` replace transport with either `Signiant` or `Aspera`

**Comment by ilkengin** [comment]
The problem is fixed when updating fastlane to the latest version (2.133.0)

**Comment by vance** [comment]
Confirmed this fix. Fastlane was uploading fine until two weeks ago, this patch fixes the transporter problem.
