### ISSUE TITLE
xcov failures running on macOS catalina

### ISSUE THREAD

**Issue by willdeberry** [fastlane/fastlane#15459]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to run `xcov` to generate code coverage documentation. Only differences between working last night and not working today is macOS 10.15 update.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>fastlane run xcov scheme:MobileRemote workspace:MobileRemote.xcworkspace derived_data_path:coverage
[✔] 🚀
[16:13:36]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:13:36]: ------------------
[16:13:36]: --- Step: xcov ---
[16:13:36]: ------------------
[16:13:37]: Skipping file blacklisting as no ignore file was found at path ./fastlane/.xcovignore

+-----------------------------+-------------------------------------------------------------------------+
|                                        Summary for xcov 1.6.0                                         |
+-----------------------------+-------------------------------------------------------------------------+
| scheme                      | MobileRemote                                                            |
| workspace                   | MobileRemote.xcworkspace                                                |
| derived_data_path           | coverage                                                                |
| output_directory            | ./fastlane/xcov_report                                                  |
| html_report                 | true                                                                    |
| markdown_report             | false                                                                   |
| json_report                 | false                                                                   |
| minimum_coverage_percentage | 0                                                                       |
| skip_slack                  | false                                                                   |
| slack_username              | xcov                                                                    |
| slack_message               | Your *xcov* coverage report                                             |
| ignore_file_path            | ./fastlane/.xcovignore                                                  |
| include_test_targets        | false                                                                   |
| only_project_targets        | false                                                                   |
| disable_coveralls           | false                                                                   |
| ideFoundationPath           | /Applications/Xcode.app/Contents/Developer/../Frameworks/IDEFoundation  |
|                             | .framework/Versions/A/IDEFoundation                                     |
| legacy_support              | false                                                                   |
+-----------------------------+-------------------------------------------------------------------------+

[16:13:37]: $ /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov-core/bin/xcov-core -s /var/folders/_1/_tkk5q2x13n37dr5vn43rpbr0000h1/T/d20191008-36009-nr7gas/action_0.xccovreport -o ./fastlane/xcov_report/tmp/report.json20191008-36009-spyqx0 --ide-foundation-path /Applications/Xcode.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation
[16:13:37]: ▸ Loading...
[16:13:37]: ▸ Opening .xccoverage file at path: /var/folders/_1/_tkk5q2x13n37dr5vn43rpbr0000h1/T/d20191008-36009-nr7gas/action_0.xccovreport
[16:13:37]: ▸ Parsing .xccoverage file...
[16:13:37]: ▸ File successfully parsed
Opening .xccoverage file at path: /var/folders/_1/_tkk5q2x13n37dr5vn43rpbr0000h1/T/d20191008-36009-nr7gas/action_0.xccovreport
Parsing .xccoverage file...
File successfully parsed
[16:13:37]: Exit status:

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	26: from /Users/wdeberry/.gem/bin/fastlane:23:in `<main>'
	25: from /Users/wdeberry/.gem/bin/fastlane:23:in `load'
	24: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/bin/fastlane:23:in `<top (required)>'
	23: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	22: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	21: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	20: from /Users/wdeberry/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	19: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	18: from /Users/wdeberry/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	17: from /Users/wdeberry/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	16: from /Users/wdeberry/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	15: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	14: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	13: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	12: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	11: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	10: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 9: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 8: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	 7: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/xcov.rb:8:in `run'
	 6: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov/manager.rb:32:in `run'
	 5: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov/manager.rb:65:in `parse_xccoverage'
	 4: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov-core.rb:24:in `parse'
	 3: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov-core.rb:30:in `execute_command'
	 2: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
	 1: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov-core.rb:38:in `block in execute_command'
/Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov/error_handler.rb:20:in `handle_error': Error creating your coverage report - see the log above (RuntimeError)
	26: from /Users/wdeberry/.gem/bin/fastlane:23:in `<main>'
	25: from /Users/wdeberry/.gem/bin/fastlane:23:in `load'
	24: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/bin/fastlane:23:in `<top (required)>'
	23: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	22: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	21: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	20: from /Users/wdeberry/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	19: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	18: from /Users/wdeberry/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	17: from /Users/wdeberry/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	16: from /Users/wdeberry/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	15: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	14: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	13: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	12: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	11: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	10: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 9: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 8: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	 7: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/xcov.rb:8:in `run'
	 6: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov/manager.rb:32:in `run'
	 5: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov/manager.rb:65:in `parse_xccoverage'
	 4: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov-core.rb:24:in `parse'
	 3: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov-core.rb:30:in `execute_command'
	 2: from /Users/wdeberry/.gem/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
	 1: from /Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov-core.rb:38:in `block in execute_command'
/Users/wdeberry/.gem/gems/xcov-1.6.0/lib/xcov/error_handler.rb:20:in `handle_error': [!] Error creating your coverage report - see the log above (RuntimeError)</pre>
</details>

### Environment
<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib            |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
update_fastlane

fastlane_version "2.17.1"

default_platform :ios
lanes = [:buildci, :qa]

platform :ios do
  before_all do |lane|
    if lanes.include?(lane)
      reset_simulator_contents
    end
  end

  ############
  desc "Version Bump"
  lane :versionbump do
    increment_build_number({
      build_number: latest_testflight_build_number(username: '<hidden>') + 1
    })
  end

  ############
  desc "Create ci ipa"
  lane :buildci do
    build_app
  end

  ############
  desc "Upload latest for testflight"
  lane :qa do
    increment_build_number({
      build_number: latest_testflight_build_number(username: '<hidden>') + 1
    })
    build_app
    deliver(
      price_tier: 0,
      username: '<hidden>',
      force: true,
      submit_for_review: false
    )
  end

  desc "Unit test and Code Coverage"
  lane :test do
    scan(
      scheme: 'MobileRemote',
      workspace: 'MobileRemote.xcworkspace',
      devices: ["iPhone 11"],
      derived_data_path: 'coverage',
      code_coverage: true
    )
    xcov(
      scheme: 'MobileRemote',
      workspace: 'MobileRemote.xcworkspace',
      derived_data_path: 'coverage',
      #minimum_coverage_percentage: 90.0
    )
  end

  after_all do |lane|
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "<hidden>" # The bundle identifier of your app

apple_id ENV["APPLE_ID"]

team_id "<hidden>"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| faraday_middleware        | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.1        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.12.0       |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| excon                     | 0.67.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.4       |
</details>

*generated on:* **2019-10-08**
</details></pre>
</details>

**Comment by willdeberry** [comment]
Found older and related bug report #15295
