### ISSUE TITLE
Upload To Testflight (Xcode 11.1): INFO: Invalid checksum on resource download for: 

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#15455]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
upload_to_testfight fails with Xcode 11.1

##### Complete output when running fastlane, including the stack trace and command used

<details>
[15:01:34]: ----------------------------------
[15:01:34]: --- Step: upload_to_testflight ---
[15:01:34]: ----------------------------------
[15:01:34]: Login to App Store Connect (xxx@xxx.com)
[15:01:36]: Login successful
[15:01:37]: Ready to upload new build to TestFlight (App: xxxx)...
[15:01:38]: Going to upload updated app to App Store Connect
[15:01:38]: This might take a few minutes. Please don't interrupt the script.
[15:02:47]: [iTMSTransporter] [2019-10-08 15:02:47 EEST] <main>  INFO: Invalid checksum on resource download for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.0.0/bundles/org.apache.logging.log4j.api-2.11.2.jar expected: 3f7ee51e3dd0830de799dae0b90243dd, received: 4cf6ebbac28c65b9fffd58cc363df6c0

[15:02:47]: [iTMSTransporter] java.lang.reflect.InvocationTargetException

[15:02:47]: [iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[15:02:47]: [iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[15:02:47]: [iTMSTransporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[15:02:47]: [iTMSTransporter] 	at java.lang.reflect.Method.invoke(Method.java:498)

[15:02:47]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:220)

[15:02:47]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:658)

[15:02:47]: [iTMSTransporter] Caused by: com.apple.transporter.bootstrap.BundleNotFoundException: bundle=[org.apache.logging.log4j.api] version=[2.11.2,3.0.0) not found.

[15:02:47]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.downloadNeededBundles(BootstrapperPhase1.java:269)

[15:02:47]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:97)

[15:02:47]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)

[15:02:47]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)

[15:02:47]: [iTMSTransporter] 	... 6 more

</details>

**Comment by neil-askfinally** [comment]
@richardtop did you resolve the issue above? If so, do you mind sharing how? I'm running into the same issue now.

**Comment by richardtop** [comment]
It seems that it was a temporary issue with the Apple platform.
