### ISSUE TITLE
Xcov seems to be not working on Xcode 11

### ISSUE THREAD

**Issue by giovas17** [fastlane/fastlane#15538]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.6.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.6.4/bin/fastlane        |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.4/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Does a static analysis of the project. Configure the options in .swiftlint.yml"
  lane :lint do
    swiftlint(
    mode: :lint,
    executable: "Pods/SwiftLint/swiftlint",
    reporter: "html",
    output_file: "fastlane/swiftlint-results.html",
    config_file: '.swiftlint.yml',
    ignore_exit_status: true )
  end
  
  desc "Test an measure code coverage"
  lane :test do
    run_tests(devices: ["iPhone 11"],
              scheme: "ProVisitRCE-debug")
    xcov(
    workspace: "ProVisitRCE.xcworkspace",
    output_directory: "fastlane/xcov_output" )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.2        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-10-23**
</details>

**Comment by janpio** [comment]
Please do not delete the issue template, but fill it.

Why do you think it is not working?

**Comment by giovas17** [comment]
I just realized that the problem is not Xcode 11 but is Catalina, I have exactly the configuration that I attached below and is working, when I did the update from OS Mojave to Catalina I didn't know that xcov will crash, I have 3 more big projects with this configuration and all are crashing in the CI because of this, the xcov step for now is skipped but we want to have the reports of the coverage in order to keep all automated and with the quality.

So, if you have a solution for the reporting I will appreciate it.

The configuration is:

### Fastfile
```
default_platform(:ios)

platform :ios do
  desc "Does a static analysis of the project. Configure the options in .swiftlint.yml"
  lane :lint do
    swiftlint(
    mode: :lint,
    executable: "Pods/SwiftLint/swiftlint",
    reporter: "html",
    output_file: "fastlane/swiftlint-results.html",
    config_file: '.swiftlint.yml',
    ignore_exit_status: true )
  end
  
  desc "Test an measure code coverage"
  lane :test do
    run_tests(devices: ["iPhone 11"],
              scheme: "ProVisitRCE-debug")
    xcov(
    workspace: "ProVisitRCE.xcworkspace",
    output_directory: "fastlane/xcov_output" )
  end
end
```
### Gemfile
```
source "https://rubygems.org"
gem "fastlane"
gem "cocoapods"
gem "xcov"
```
### Gitlab CI Configuration
```
stages:
  - lint
  - unit_test

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - bundle install --path vendor/bundle
  - bundle exec pod install

quality_check:
  stage: lint
  script:
    - bundle exec fastlane lint
  artifacts:
    name: "quality_report"
    expire_in: 5 days
    paths:
      - fastlane/report.xml
      - fastlane/swiftlint-results.html
  tags:
    - ios_12
    - ios_11
    - xcode_10.1
  only:
    - merge_request


unit_tests:
  stage: unit_test
  script:
    - bundle exec fastlane test
  artifacts:
    name: "tests_report"
    expire_in: 5 days
    paths:
      - fastlane/test_output/
      - fastlane/xcov_output/
  tags:
    - ios_12
    - ios_11
    - xcode_10.1
  only:
    - merge_request
```
### Error shown by the CI and the local console
```
[20:04:32]: ▸ All tests
[20:04:32]: ▸ Test Suite ProVisitRCETests.xctest started
[20:04:32]: ▸ ProVisitRCETests
[20:04:32]: ▸     ✓ testExample (0.002 seconds)
[20:04:33]: ▸     ◷ testPerformanceExample measured (0.000 seconds)
[20:04:33]: ▸     ✓ testPerformanceExample (0.323 seconds)
[20:04:33]: ▸ 	 Executed 2 tests, with 0 failures (0 unexpected) in 0.324 (0.327) seconds
[20:04:33]: ▸ 
[20:04:33]: ▸ 2019-10-27 20:04:33.536 xcodebuild[1001:13344] [MT] IDETestOperationsObserverDebug: 32.214 elapsed -- Testing started completed.
[20:04:33]: ▸ 2019-10-27 20:04:33.536 xcodebuild[1001:13344] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[20:04:33]: ▸ 2019-10-27 20:04:33.536 xcodebuild[1001:13344] [MT] IDETestOperationsObserverDebug: 32.214 sec, +32.214 sec -- end
[20:04:35]: ▸ Test Succeeded
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 2 |
| Number of failures | 0 |
+--------------------+---+

[20:04:41]: ------------------
[20:04:41]: --- Step: xcov ---
[20:04:41]: ------------------
[20:04:41]: Skipping file blacklisting as no ignore file was found at path ./fastlane/.xcovignore

+-----------------------------+-------------------------------------------------------------------------+
|                                        Summary for xcov 1.6.0                                         |
+-----------------------------+-------------------------------------------------------------------------+
| workspace                   | ProVisitRCE.xcworkspace                                                 |
| output_directory            | fastlane/xcov_output                                                    |
| scheme                      | ProVisitRCE-debug                                                       |
| html_report                 | true                                                                    |
| markdown_report             | false                                                                   |
| json_report                 | false                                                                   |
| minimum_coverage_percentage | 0                                                                       |
| skip_slack                  | false                                                                   |
| slack_username              | xcov                                                                    |
| slack_message               | Your *xcov* coverage report                                             |
| ignore_file_path            | ./fastlane/.xcovignore                                                  |
| include_test_targets        | false                                                                   |
| only_project_targets        | false                                                                   |
| disable_coveralls           | false                                                                   |
| ideFoundationPath           | /Applications/Xcode.app/Contents/Developer/../Frameworks/IDEFoundation  |
|                             | .framework/Versions/A/IDEFoundation                                     |
| legacy_support              | false                                                                   |
+-----------------------------+-------------------------------------------------------------------------+

[20:04:41]: $ xcodebuild -showBuildSettings -workspace ProVisitRCE.xcworkspace -scheme ProVisitRCE-debug
[20:04:44]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[20:04:49]: Copying .xccovarchive to fastlane/xcov_output/action_0.xccovarchive
[20:04:49]: Copying .xccovreport to fastlane/xcov_output/action_0.xccovreport
[20:04:49]: $ /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bundler/gems/xcov-ad261af3e945/lib/xcov-core/bin/xcov-core -s fastlane/xcov_output/action_0.xccovreport -o fastlane/xcov_output/tmp/report.json20191027-946-15d5c3f --ide-foundation-path /Applications/Xcode.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation
[20:04:49]: ▸ Loading...
[20:04:49]: ▸ Opening .xccoverage file at path: /Users/darkgeat/iOSProjects/Provisit/fastlane/xcov_output/action_0.xccovreport
[20:04:49]: ▸ Parsing .xccoverage file...
[20:04:49]: ▸ File successfully parsed
Opening .xccoverage file at path: /Users/darkgeat/iOSProjects/Provisit/fastlane/xcov_output/action_0.xccovreport
Parsing .xccoverage file...
File successfully parsed
[20:04:49]: Exit status: 
+----------------------------+-------------------------------------------------------------------------+
|                                             Lane Context                                             |
+----------------------------+-------------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                     |
| PLATFORM_NAME              | ios                                                                     |
| LANE_NAME                  | ios test                                                                |
| SCAN_DERIVED_DATA_PATH     | /Users/darkgeat/Library/Developer/Xcode/DerivedData/ProVisitRCE-flvlhu  |
|                            | gbennntnfgabtiertbftsx                                                  |
| SCAN_GENERATED_PLIST_FILES | []                                                                      |
| SCAN_GENERATED_PLIST_FILE  |                                                                         |
+----------------------------+-------------------------------------------------------------------------+
[20:04:49]: Error creating your coverage report - see the log above

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | run_tests        | 198         |
| 💥   | xcov             | 7           |
+------+------------------+-------------+

[20:04:49]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bin/fastlane)
RuntimeError: [!] Error creating your coverage report - see the log above
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bundler/gems/xcov-ad261af3e945/lib/xcov/error_handler.rb:20:in `handle_error'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bundler/gems/xcov-ad261af3e945/lib/xcov-core.rb:38:in `block in execute_command'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bundler/gems/xcov-ad261af3e945/lib/xcov-core.rb:30:in `execute_command'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bundler/gems/xcov-ad261af3e945/lib/xcov-core.rb:24:in `parse'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bundler/gems/xcov-ad261af3e945/lib/xcov/manager.rb:83:in `parse_xccoverage'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bundler/gems/xcov-ad261af3e945/lib/xcov/manager.rb:32:in `run'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/actions/xcov.rb:8:in `run'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:34:in `block (2 levels) in parsing_binding'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/gems/fastlane-2.134.0/bin/fastlane:23:in `<top (required)>'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/darkgeat/iOSProjects/Provisit/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
```

I checked in several posts and blogs and other folks and we tried to with `gem "xcov", :git => 'https://github.com/fastlane-community/xcov.git', :branch => 'joshdholtz-export-xccovarchive-and-xccreport'` but same error happen.

For some reason xcov seems to be finish properly but has errors at the moment of the report creation.

**Comment by giovas17** [comment]
Finally, I see this working in Catalina, please see [this related issue](https://github.com/fastlane-community/xcov/issues/157#issuecomment-547908404), I just need to update my gems and be sure that is `Gemfile.lock` working with:

```
xcov (1.7.0)
      fastlane (>= 2.82.0, < 3.0.0)
      multipart-post
      terminal-table
      xcodeproj
      xcresult (~> 0.2.0)
xcresult (0.2.0) 
```

I did that and is working, I will close this issue.
