### ISSUE TITLE
Could not retrieve response as fastlane runs in non-interactive mode

### ISSUE THREAD

**Issue by tomirisweb** [fastlane/fastlane#15548]
Hi,
I have a problem when I want to exec the command "bundle exec fastlane".

According to the messages, there is a problem whith Fastlane but I don't find the solution.

Can you help me please ? How I can solve this problem ?

Thank you :)

You can see the problem in this code :

```
    $ bundle exec fastlane
    [21:46:31]: ----------------------------------------
    [21:46:31]: --- Step: Verifying fastlane version ---
    [21:46:31]: ----------------------------------------
    [21:46:31]: Your fastlane version 2.134.0 matches the minimum requirement of 2.93.0  ✅
    [21:46:31]: ------------------------------
    [21:46:31]: --- Step: default_platform ---
    [21:46:31]: ------------------------------
    [21:46:31]: Welcome to fastlane! Here's what your app is setup to do:
    +--------+------------------+---------------------+
    |             Available lanes to run              |
    +--------+------------------+---------------------+
    | Number | Lane Name        | Description         |
    +--------+------------------+---------------------+
    | 1      | ios beta         |                     |
    | 2      | ios beta_release |                     |
    | 3      | ios release      |                     |
    | 0      | cancel           | No selection, exit  |
    |        |                  | fastlane!           |
    +--------+------------------+---------------------+
    [21:46:31]: Which number would you like run?
    
    Looking for related GitHub issues on fastlane/fastlane...
    
    ➡️  CircleCI: Could not find fastlane in current directory.
        https://github.com/fastlane/fastlane/issues/15341 [open] 5 💬
        3 weeks ago
    
    ➡️  Match with Google Cloud: Impossible to run in noninteractive mode (CI)
        https://github.com/fastlane/fastlane/issues/15426 [closed] 3 💬
        3 weeks ago
    
    ➡️  Fastlain Android screengrab. Could not retrieve response as fastlane runs in non-interactive mode
        https://github.com/fastlane/fastlane/issues/14869 [closed] 6 💬
        4 weeks ago
    
    and 42 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓
    
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:156:in `verify_interactive!'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:129:in `input'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager.rb:120:in `choose_lane'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/bin/fastlane:23:in `<top (required)>'
            from C:/Ruby26-x64/bin/fastlane:23:in `load'
            from C:/Ruby26-x64/bin/fastlane:23:in `<main>'
    C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:156:in `verify_interactive!'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:129:in `input'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager.rb:120:in `choose_lane'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
            from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/bin/fastlane:23:in `<top (required)>'
            from C:/Ruby26-x64/bin/fastlane:23:in `load'
            from C:/Ruby26-x64/bin/fastlane:23:in `<main>'
```

**Comment by janpio** [comment]
What did you enter to the prompt

**Comment by rodrigobaroni** [comment]
I have the same problem
I run fastlane env and output is this:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.64.1"
default_platform :ios

platform :ios do
  
  lane :beta do
    begin 
      ensure_git_status_clean
      increment_build_number
  
      gym(scheme: "Release Homolog", export_xcargs: "-allowProvisioningUpdates")

      pilot(
        username: "",
        team_name: "",
        skip_waiting_for_build_processing: true,
        app_identifier: ""
      )
      slack(
          message: "App enviado com sucesso para o TestFlight.",
          success: true,
          slack_url: "https://hooks.slack.com/services/"
      )
    rescue => exception
      on_error(exception)
    end
  end

  lane :prod do
    ensure_git_status_clean
    increment_build_number  
    gym(scheme: "Release", export_xcargs: "-allowProvisioningUpdates")

    pilot(
      username: "",
      team_name: "",
      skip_waiting_for_build_processing: true,
      app_identifier: ""
    )
  end
  
  lane :sendCrashlytics do
    crashlytics(
      notes: "Automated build from Fastlane." + get_version_number + get_build_number,
      # notes_path: "",
      crashlytics_path: "./Pods/Crashlytics/Crashlytics.framework",
      api_token: '',
      build_secret: '',
      ipa_path: "./.ipa",
      groups: ['testers-fabric'],
      notifications: true
    )
  end
end

def on_error(exception)
       slack(
           message: "Falha no envio : #{exception}",
           success: false,
           slack_url: "https://hooks.slack.com/services/",
       )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "BUNDLE_IDENTIFIER" # The bundle identifier of your app
apple_id "APPLEID@APPLE.COM" # Your Apple email address

team_id "TEM_ID" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.3       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2019-11-14**
</details>

**Comment by janpio** [comment]
Then you should also post your output and answer the question I asked before: https://github.com/fastlane/fastlane/issues/15548#issuecomment-546738223

**Comment by JoaquinFernandez** [comment]
@tomirisweb @rodrigobaroni 
That error is sent when fastlane prompts the user for input, but since it is running in automated mode, it can't stop, i.e. in a CI tool (I was using CircleCI).

In @tomirisweb case, you have to run 

`bundle exec fastlane ios beta` (or any of the other options) in your command.

**Comment by hyahm** [comment]
> fastlane env
```
<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>
```
