### ISSUE TITLE
deliver key not found "value"

### ISSUE THREAD

**Issue by cinder92** [fastlane/fastlane#15576]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Everything works ok, until fastlane goes to `deliver` step i get this error

`key not found : "value"`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>

Using `fastlane ios beta --verbose`

***
INFO [2019-10-31 14:23:34.22]: Successfully sent Slack notification
WARN [2019-10-31 14:23:34.22]: Lane Context:
INFO [2019-10-31 14:23:34.22]: {:PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :GIT_REPO_WAS_CLEAN_ON_START=>true, :BUILD_NUMBER=>"7", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/dantecervantes/Documents/projects/watsontapp/watsontapp.ipa", :DSYM_OUTPUT_PATH=>"/Users/dantecervantes/Documents/projects/watsontapp/watsontapp.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/dantecervantes/Library/Developer/Xcode/Archives/2019-10-31/watsontapp 2019-10-31 14.18.40.xcarchive"}
ERROR [2019-10-31 14:23:34.22]: key not found: "value"
INFO [2019-10-31 14:23:34.23]: Successfully generated documentation at path '/Users/dantecervantes/Documents/projects/watsontapp/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | opt_out_usage          | 0           |
| 2    | ensure_git_branch      | 0           |
| 3    | ensure_git_status_cle  | 0           |
|      | an                     |             |
| 4    | increment_build_numbe  | 0           |
|      | r                      |             |
| 5    | Switch to ios build    | 0           |
|      | lane                   |             |
| 6    | Switch to ios          | 0           |
|      | certificates lane      |             |
| 7    | match                  | 5           |
| 8    | match                  | 5           |
| 9    | gym                    | 289         |
| 💥   | deliver                | 3           |
| 11   | slack                  | 6           |
+------+------------------------+-------------+

ERROR [2019-10-31 14:23:34.29]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: key not found: "value"

URL: https://api.github.com/search/issues?q=key%20not%20found%3A%20%22value%22+repo:fastlane/fastlane
➡️  Fastlane ruby version not found
   https://github.com/fastlane/fastlane/issues/15509 [open] 1 💬
   2 weeks ago

➡️  Arabic language not supported in metadata
   https://github.com/fastlane/fastlane/issues/14959 [open] 24 💬
   3 days ago

➡️  Regenerate Profiles from Different Machine
   https://github.com/fastlane/fastlane/issues/15492 [open] 3 💬
   2 weeks ago

and 1964 more at: https://github.com/fastlane/fastlane/search?q=key%20not%20found%3A%20%22value%22&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:740:in `fetch': [!] key not found: "value" (KeyError)
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:740:in `block in setup_trailers_for'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:739:in `each'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:739:in `setup_trailers_for'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:726:in `block in setup_trailers'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:724:in `each'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:724:in `setup_trailers'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:323:in `setup'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/base.rb:215:in `initialize'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:168:in `new'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:168:in `factory'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/app_version.rb:189:in `find'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/application.rb:111:in `edit_version'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/deliver/lib/deliver/upload_metadata.rb:153:in `verify_available_languages!'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/deliver/lib/deliver/upload_metadata.rb:44:in `upload'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/deliver/lib/deliver/runner.rb:62:in `upload_metadata'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/deliver/lib/deliver/runner.rb:21:in `run'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/deliver.rb:16:in `run'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:40:in `block (2 levels) in parsing_binding'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
        from /Users/dantecervantes/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/bin/fastlane:20:in `<top (required)>'
        from /Users/dantecervantes/.fastlane/bin/bundle/bin/fastlane:22:in `load'
        from /Users/dantecervantes/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre>

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G103)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |
</pre>
</details>

**Comment by cinder92** [comment]
never mind, i just updated fastlane to last version and it works!
