### ISSUE TITLE
Mapping values are not allowed in this context

### ISSUE THREAD

**Issue by alexcroox** [fastlane/fastlane#15616]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running fastlane for the first time  I get hit with Ruby errors on the `Pilot` stage.

##### Command executed
`fastlane beta`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>[19:07:10]: Successfully exported and compressed dSYM file
[19:07:10]: Successfully exported and signed the ipa file:
[19:07:10]: /Users/alex/Projects/sml/App.ipa
[19:07:10]: -------------------
[19:07:10]: --- Step: pilot ---
[19:07:10]: -------------------
[19:07:10]: Login to iTunes Connect (xxx@xxx.xxx)
Error loading session from environment
Make sure to pass the session in a valid format
+--------------------+--------------------------------------+
|                       Lane Context                        |
+--------------------+--------------------------------------+
| DEFAULT_PLATFORM   | ios                                  |
| PLATFORM_NAME      | ios                                  |
| LANE_NAME          | ios beta                             |
| IPA_OUTPUT_PATH    | /Users/alex/Projects/sml/App.ipa     |
| DSYM_OUTPUT_PATH   | /Users/alex/Projects/sml/App.app.dS  |
|                    | YM.zip                               |
| XCODEBUILD_ARCHIVE | /Users/alex/Library/Developer/Xcode  |
|                    | /Archives/2019-11-09/App 2019-11-09  |
|                    | 19.06.16.xcarchive                   |
+--------------------+--------------------------------------+
[19:07:10]: (<unknown>): mapping values are not allowed in this context at line 3 column 7

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | gym                 | 57          |
| 💥   | pilot               | 0           |
+------+---------------------+-------------+

[19:07:10]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  testmunk intro text
   https://github.com/fastlane/fastlane/pull/3 [closed] 0 💬
   04 Feb 2017

➡️  Typo
   https://github.com/fastlane/fastlane/pull/7 [closed] 4 💬
   04 Feb 2017

➡️  Remove Shenzhen dependency
   https://github.com/fastlane/fastlane/pull/6991 [closed] 19 💬
   13 Mar 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/alex/.fastlane/bin/bundle/lib/ruby/2.2.0/psych.rb:370:in `parse': [!] (<unknown>): mapping values are not allowed in this context at line 3 column 7 (Psych::SyntaxError)
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/2.2.0/psych.rb:318:in `parse'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/2.2.0/psych.rb:245:in `load'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/http-cookie-1.0.3/lib/http/cookie_jar/yaml_saver.rb:24:in `load'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:325:in `block in load'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `open'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `load'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/two_step_client.rb:104:in `load_session_from_env'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/client.rb:366:in `send_shared_login_request'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/tunes_client.rb:161:in `send_login_request'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/client.rb:585:in `do_login'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/client.rb:346:in `login'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/client.rb:119:in `login'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/pilot/lib/pilot/manager.rb:15:in `login'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/pilot/lib/pilot/manager.rb:8:in `start'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/pilot/lib/pilot/build_manager.rb:6:in `upload'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/pilot.rb:15:in `run'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:39:in `block (2 levels) in parsing_binding'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/bin/fastlane:20:in `<top (required)>'
	from /Users/alex/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/alex/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G1012)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(
      scheme: "App",
      #project: "ios/App/App.xcodeproj",
      workspace: "ios/App/App.xcworkspace",
    ) # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "xxx.xxx.xxx" # The bundle identifier of your app
apple_id "xxx@xxx.xxx" # Your Apple email address

team_id "xxx" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>

*generated on:* **2019-11-09**
</details></pre>
</details>

**Comment by alexcroox** [comment]
This was solved by removing homebrew version, updating ruby and installing gem version of Fastlane
