### ISSUE TITLE
Google Api Error: applicationNotFound: No application was found for the given package name. - No application was found for the given package name.

### ISSUE THREAD

**Issue by davidnk301** [fastlane/fastlane#15648]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have an android application that I want to upload to the play store using the `fastlane internal` or `fastlane supply init` command but I receive the following error.

`Google Api Error: applicationNotFound: No application was found for the given package name. - No application was found for the given package name.`

The general fix for this issue is to create the project in the Play Console and then manually uploading the APK. I have created the application in the Play Console by manually uploading an APK but I am still getting the same error when I run `fastlane internal`.  

##### Command executed
`fastlane internal`

##### Complete output when running fastlane, including the stack trace and command used
```
[<REDACTED>@localhost android-client]$ fastlane internal --verbose
[✔] 🚀
[22:47:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2019-11-13 22:47:56.17]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '<REDACTED>/fastlane/Appfile'
- json_key_file: '<REDACTED>/play-store-config.json'
- package_name: '<REDACTED>'
-------
INFO [2019-11-13 22:47:56.19]: ---------------------------
INFO [2019-11-13 22:47:56.19]: --- Step: opt_out_usage ---
INFO [2019-11-13 22:47:56.19]: ---------------------------
INFO [2019-11-13 22:47:56.19]: Disabled upload of used actions
INFO [2019-11-13 22:47:56.19]: ------------------------------
INFO [2019-11-13 22:47:56.19]: --- Step: default_platform ---
INFO [2019-11-13 22:47:56.19]: ------------------------------
INFO [2019-11-13 22:47:56.19]: Driving the lane 'android internal' 🚀
INFO [2019-11-13 22:47:56.19]: ----------------------------------
INFO [2019-11-13 22:47:56.19]: --- Step: upload_to_play_store ---
INFO [2019-11-13 22:47:56.19]: ----------------------------------
Successfully loaded Appfile at path '<REDACTED>'
- json_key_file: '<REDACTED>/play-store-config.json'
- package_name: '<REDACTED>'
-------
Successfully loaded Appfile at path '<REDACTED>/fastlane/Appfile'
- json_key_file: '<REDACTED>/play-store-config.json'
- package_name: '<REDACTED>'
-------
Successfully loaded Appfile at path '<REDACTED>/fastlane/Appfile'
- json_key_file: '<REDACTED>/play-store-config.json'
- package_name: '<REDACTED>'
-------
Successfully loaded Appfile at path '<REDACTED>/fastlane/Appfile'
- json_key_file: '<REDACTED>/play-store-config.json'
- package_name: '<REDACTED>'
-------
Successfully loaded Appfile at path '<REDACTED>/fastlane/Appfile'
- json_key_file: '<REDACTED>/play-store-config.json'
- package_name: '<REDACTED>'
-------
Successfully loaded Appfile at path '<REDACTED>/fastlane/Appfile'
- json_key_file: '<REDACTED>/play-store-config.json'
- package_name: '<REDACTED>'
-------
Successfully loaded Appfile at path '<REDACTED>/fastlane/Appfile'
- json_key_file: '<REDACTED>/play-store-config.json'
- package_name: '<REDACTED>'
-------

+-------------------------+-----------------------------------------------+
|                       Summary for supply 2.135.2                        |
+-------------------------+-----------------------------------------------+
| track                   | internal                                      |
| apk                     | app/build/outputs/apk/release/app-release.apk |
| package_name            | <REDACTED>                  |
| release_status          | completed                                     |
| json_key                | <REDACTED>/play-store-config.json            |
| skip_upload_apk         | false                                         |
| skip_upload_aab         | false                                         |
| skip_upload_metadata    | false                                         |
| skip_upload_changelogs  | false                                         |
| skip_upload_images      | false                                         |
| skip_upload_screenshots | false                                         |
| validate_only           | false                                         |
| check_superseded_tracks | false                                         |
| timeout                 | 300                                           |
| deactivate_on_promote   | true                                          |
+-------------------------+-----------------------------------------------+

DEBUG [2019-11-13 22:47:56.20]: Fetching a new access token from Google...
WARN [2019-11-13 22:47:56.56]: Lane Context:
INFO [2019-11-13 22:47:56.56]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android internal"}
ERROR [2019-11-13 22:47:56.56]: Google Api Error: applicationNotFound: No application was found for the given package name. - No application was found for the given package name.
INFO [2019-11-13 22:47:56.56]: Successfully generated documentation at path '<REDACTED>/fastlane/README.md'

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | opt_out_usage        | 0           |
| 2    | default_platform     | 0           |
| 💥   | upload_to_play_store | 0           |
+------+----------------------+-------------+

ERROR [2019-11-13 22:47:56.56]: fastlane finished with errors
Traceback (most recent call last):
        32: from <REDACTED>/bin/fastlane:23:in `<main>'
        31: from <REDACTED>/bin/fastlane:23:in `load'
        30: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/bin/fastlane:23:in `<top (required)>'
        29: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        28: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        27: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        26: from <REDACTED>/.gem/ruby/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        25: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        24: from <REDACTED>/.gem/ruby/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        23: from <REDACTED>/.gem/ruby/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        22: from <REDACTED>/.gem/ruby/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        21: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        20: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        19: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        18: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
        17: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        16: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        15: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/lane.rb:33:in `call'
        14: from Fastfile:32:in `block (2 levels) in parsing_binding'
        13: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        12: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        11: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        10: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
         9: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
         8: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
         7: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
         6: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
         5: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/supply/lib/supply/uploader.rb:7:in `perform_upload'
         4: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/supply/lib/supply/client.rb:138:in `begin_edit'
         3: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/supply/lib/supply/client.rb:79:in `call_google_api'
         2: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/supply/lib/supply/client.rb:94:in `rescue in call_google_api'
         1: from <REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
<REDACTED>/.gem/ruby/gems/fastlane-2.135.2/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: applicationNotFound: No application was found for the given package name. - No application was found for the given package name. (FastlaneCore::Interface::FastlaneError)
```
### Environment

```
[22:46:48]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[22:46:48]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
[22:46:48]: [31mundefined method `strip' for nil:NilClass[0m
[22:46:48]: [31mError rendering markdown table using the following text:[0m
[22:46:48]: | Key | Value |
| fastlane | 2.135.2 |
| OS | fedora Fedora release 28 (Twenty Eight) |
| Ruby | 2.5.5 |
| Bundler? | false |
| Git | git version 2.17.2 |
| Installation Source | ~/bin/fastlane |
| Host | \S
Kernel \r on an \m (\l) fedora Fedora release 28 (Twenty Eight) (5.0.16-100.fc28.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.1.0i  14 Aug 2018 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.135.2 |
| OS | fedora Fedora release 28 (Twenty Eight) |
| Ruby | 2.5.5 |
| Bundler? | false |
| Git | git version 2.17.2 |
| Installation Source | ~/bin/fastlane |
| Host | \S
Kernel \r on an \m (\l) fedora Fedora release 28 (Twenty Eight) (5.0.16-100.fc28.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.1.0i  14 Aug 2018 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
###################################################################################################
# Copyright (C) 2019-2019 <REDACTED>. <https://<REDACTED>.com>
###################################################################################################

opt_out_usage

default_platform(:android)

platform :android do
  desc "Compiling Project"
  lane :compile do
    gradle(task: "assemble")
  end

  desc "Running Checkstyle"
  lane :checkstyle do
    gradle(task: "ktlint")
  end

  desc "Running Unit Tests"
  lane :test do
    gradle(task: "test")
  end
 
  desc "Running Functional Tests"
  lane :androidtest do
    gradle(task: "connectedAndroidTest")
  end

  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    upload_to_play_store(track: 'internal', apk: 'app/build/outputs/apk/release/app-release.apk')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
###################################################################################################
# Copyright (C) 2019-2019 <REDACTED>. <https://<REDACTED>.com>
###################################################################################################

json_key_file("<REDACTED>/play-store-config.json")
package_name("<REDACTED>")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| stringio                  | 0.0.1        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2019-11-13**
</details>
[22:46:49]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[22:46:49]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m

```

**Comment by janpio** [comment]
There is unfortunately no way around this: You have to manually create the app in Google Play Dev Console and upload an initial version as there is no API to create an app.

**Comment by markymc** [comment]
@davidnk301 I'm also seeing this problem. I've already uploaded an AAB to the Play Console under our internal test track but am receiving the same `Google Api Error: applicationNotFound: No application was found for the given package name. - No application was found for the given package name.` error.

Did you find a solution to this problem? I'm wondering if it's because our app is showing as "Processing update" on the Dashboard page, which is related to the new app review process at Google it seems.

**Comment by janpio** [comment]
That would be an interesting observation @marymc. Can you please create a new issue so this doesn't get lost here in this closed issue? We usually don't look at those.

**Comment by markymc** [comment]
@janpio Sorry for the delay. Done!
