### ISSUE TITLE
Unable to login through fastlane

### ISSUE THREAD

**Issue by jeremyspatrick** [fastlane/fastlane#15657]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane is unable to login this morning. Not sure if apple is down or if they changed something. Appears to be an issue logging in via https://idmsa.apple.com/appleauth/auth

##### Command executed

Initially noticed with produce

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
|          [32mSummary for produce 2.117.1[0m          |
+----------------+------------------------------+
| app_identifier | com.csiweb.salescustom5.bk5  |
| username       | digitalappdevteam@csiweb.com |
| app_name       | Centier                      |
| itc_team_name  | Computer Services, Inc.      |
| skip_devcenter | true                         |
| company_name   | Centier                      |
| language       | English                      |
| sku            | 1573747837                   |
| platform       | ios                          |
| skip_itc       | false                        |
+----------------+------------------------------+

Available session is not valid any more. Continuing with normal login.

Looking for related GitHub issues on fastlane/fastlane...

#######################################################################
# fastlane 2.135.2 is available. You are on 2.117.1.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/json/common.rb:156:in `parse': [31m[!] 751: unexpected token at '<!DOCTYPE html> (JSON::ParserError)
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Not Found</h3>
    <p>The requested page could not be found.</p>
</div>
</body>
</html>

'[0m
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/spaceship/lib/spaceship/client.rb:520:in `fetch_olympus_session'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/spaceship/lib/spaceship/client.rb:490:in `send_shared_login_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/spaceship/lib/spaceship/client.rb:769:in `do_login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/spaceship/lib/spaceship/client.rb:384:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/spaceship/lib/spaceship/client.rb:346:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/produce/lib/produce/itunes_connect.rb:12:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/produce/lib/produce/manager.rb:12:in `start_producing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/produce/lib/produce/commands_generator.rb:39:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/produce/lib/produce/commands_generator.rb:232:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/produce/lib/produce/commands_generator.rb:16:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.117.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
****** produce *******
fastlane produce create -a com.website -u email@work.com -b number -q name -i
[10:10:47]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
</pre>
</details>
### Environment

<details>
  <pre> <details><summary>ðŸš« fastlane environment ðŸš«</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.2                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | âœ… |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.117.1 | ðŸš« Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| faraday                   | 0.15.4       |
| openssl                   | 2.0.5        |
| highline                  | 1.7.10       |
| io-console                | 0.4.6        |
| excon                     | 0.64.0       |
| CFPropertyList            | 3.0.0        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| addressable               | 2.6.0        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2019-11-14**
</details>
 </pre>
</details>

**Comment by jeremyspatrick** [comment]
Upgrading fastlane to the latest version fixed the issue
