### ISSUE TITLE
Test Center plugin throws an exception after update

### ISSUE THREAD

**Issue by mykola-mokhnach** [fastlane/fastlane#15686]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After updating fastlane and test center plugin to the most recent version our testing script on Travis started failing with the following stack trace:
```
Found no similar issues. To create a new issue, please visit:
2001https://github.com/fastlane/fastlane/issues/new
2002Run `fastlane env` to append the fastlane environment to your issue
2003bundler: failed to load command: fastlane (/Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/bin/fastlane)
2004NameError: [!] uninitialized constant Fastlane::Actions::MultiScanAction::ScanHelper
2005Did you mean?  Fastlane::Helper
2006  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.8.13/lib/fastlane/plugin/test_center/actions/multi_scan.rb:140:in `use_scanfile_to_override_settings'
2007  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.8.13/lib/fastlane/plugin/test_center/actions/multi_scan.rb:116:in `prepare_for_testing'
2008  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.8.13/lib/fastlane/plugin/test_center/actions/multi_scan.rb:16:in `run'
2009  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
2010  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
2011  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
2012  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
2013  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
2014  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
2015  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2016  ../fastlane/Fastfile:20:in `block in parsing_binding'
2017  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/lane.rb:33:in `call'
2018  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
2019  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
2020  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
2021  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
2022  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
2023  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
2024  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2025  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2026  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2027  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2028  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2029  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
2030  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
2031  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
2032  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/gems/fastlane-2.136.0/bin/fastlane:23:in `<top (required)>'
2033  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
2034  /Users/travis/build/appium/WebDriverAgent/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
```

Please find the full log at https://travis-ci.org/appium/WebDriverAgent/jobs/614495760

**Comment by mykola-mokhnach** [comment]
It also looks like the problem is only reproducible with Xcode 10 SDK. Xcode 11 works properly though

**Comment by janpio** [comment]
You should probably report this at the plugin's repository.

**Comment by mykola-mokhnach** [comment]
@janpio Thanks for your response. Reported the problem as https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/174
