### ISSUE TITLE
Supply crashes with a nil reference error

### ISSUE THREAD

**Issue by mfcollins3** [fastlane/fastlane#15718]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am using Fastlane to publish a new Android application to the Google Play Store. I did not have any problem initially publishing the APK to the store using Supply, but last night I tried switching to using an AAB instead. When I do this with the latest Fastlane version (2.137.0), it fails with a nil reference error. I was successfully able to publish with 2.133.0 when I got it to run accidentally instead of the latest version.

##### Command executed
`bundle exec fastlane android release`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[13:44:06]: [32m------------------------------[0m
[13:44:06]: [32m--- Step: default_platform ---[0m
[13:44:06]: [32m------------------------------[0m
[13:44:06]: [32mDriving the lane 'android release' 🚀[0m
[13:44:06]: [32m-----------------------------------------[0m
[13:44:06]: [32m--- Step: Switch to android test lane ---[0m
[13:44:06]: [32m-----------------------------------------[0m
[13:44:06]: Cruising over to lane 'android test' 🚖
[13:44:06]: [32m--------------------[0m
[13:44:06]: [32m--- Step: gradle ---[0m
[13:44:06]: [32m--------------------[0m
[13:44:06]: [36m$ /Users/michaelcollins/Projects/mfcollins3/paycheck-simulator/android/gradlew test -p .[0m
[13:44:08]: ▸ [35m> Task :app:preBuild UP-TO-DATE[0m
[13:44:08]: ▸ [35m> Task :app:preDebugBuild UP-TO-DATE[0m
[13:44:08]: ▸ [35m> Task :app:compileDebugAidl NO-SOURCE[0m
[13:44:08]: ▸ [35m> Task :app:checkDebugManifest[0m
[13:44:08]: ▸ [35m> Task :app:compileDebugRenderscript NO-SOURCE[0m
[13:44:08]: ▸ [35m> Task :app:generateDebugBuildConfig[0m
[13:44:08]: ▸ [35m> Task :app:mainApkListPersistenceDebug[0m
[13:44:08]: ▸ [35m> Task :app:generateDebugResValues[0m
[13:44:08]: ▸ [35m> Task :app:generateDebugResources[0m
[13:44:14]: ▸ [35m> Task :app:mergeDebugResources[0m
[13:44:14]: ▸ [35m> Task :app:createDebugCompatibleScreenManifests[0m
[13:44:14]: ▸ [35m> Task :app:preDebugUnitTestBuild UP-TO-DATE[0m
[13:44:14]: ▸ [35m> Task :app:processDebugJavaRes NO-SOURCE[0m
[13:44:14]: ▸ [35m> Task :app:processDebugUnitTestJavaRes NO-SOURCE[0m
[13:44:14]: ▸ [35m> Task :app:preReleaseBuild UP-TO-DATE[0m
[13:44:14]: ▸ [35m> Task :app:compileReleaseAidl NO-SOURCE[0m
[13:44:14]: ▸ [35m> Task :app:compileReleaseRenderscript NO-SOURCE[0m
[13:44:14]: ▸ [35m> Task :app:checkReleaseManifest UP-TO-DATE[0m
[13:44:14]: ▸ [35m> Task :app:generateReleaseBuildConfig UP-TO-DATE[0m
[13:44:14]: ▸ [35m> Task :app:processDebugManifest[0m
[13:44:15]: ▸ [35m> Task :app:processDebugResources[0m
[13:44:15]: ▸ [35m> Task :app:compileDebugKotlin[0m
[13:44:15]: ▸ [35m> Task :app:mainApkListPersistenceRelease[0m
[13:44:15]: ▸ [35m> Task :app:generateReleaseResValues UP-TO-DATE[0m
[13:44:15]: ▸ [35m> Task :app:generateReleaseResources UP-TO-DATE[0m
[13:44:15]: ▸ [35m> Task :app:mergeReleaseResources UP-TO-DATE[0m
[13:44:15]: ▸ [35m> Task :app:createReleaseCompatibleScreenManifests[0m
[13:44:16]: ▸ [35m> Task :app:processReleaseManifest[0m
[13:44:18]: ▸ [35m> Task :app:processReleaseResources[0m
[13:44:18]: ▸ [35m> Task :app:compileReleaseKotlin UP-TO-DATE[0m
[13:44:18]: ▸ [35m> Task :app:javaPreCompileRelease UP-TO-DATE[0m
[13:44:18]: ▸ [35m> Task :app:compileReleaseJavaWithJavac UP-TO-DATE[0m
[13:44:19]: ▸ [35m> Task :app:compileReleaseUnitTestKotlin[0m
[13:44:19]: ▸ [35m> Task :app:preReleaseUnitTestBuild UP-TO-DATE[0m
[13:44:19]: ▸ [35m> Task :app:processReleaseJavaRes NO-SOURCE[0m
[13:44:19]: ▸ [35m> Task :app:processReleaseUnitTestJavaRes NO-SOURCE[0m
[13:44:19]: ▸ [35m> Task :app:javaPreCompileDebug[0m
[13:44:19]: ▸ [35m> Task :app:compileDebugJavaWithJavac[0m
[13:44:19]: ▸ [35mwarning: [options] source value 7 is obsolete and will be removed in a future release[0m
[13:44:19]: ▸ [35mwarning: [options] target value 7 is obsolete and will be removed in a future release[0m
[13:44:19]: ▸ [35mwarning: [options] To suppress warnings about obsolete options, use -Xlint:-options.[0m
[13:44:19]: ▸ [35m3 warnings[0m
[13:44:20]: ▸ [35m> Task :app:compileDebugUnitTestKotlin[0m
[13:44:20]: ▸ [35m> Task :app:javaPreCompileReleaseUnitTest[0m
[13:44:20]: ▸ [35m> Task :app:compileReleaseUnitTestJavaWithJavac NO-SOURCE[0m
[13:44:20]: ▸ [35m> Task :app:testReleaseUnitTest[0m
[13:44:20]: ▸ [35m> Task :app:javaPreCompileDebugUnitTest[0m
[13:44:20]: ▸ [35m> Task :app:compileDebugUnitTestJavaWithJavac NO-SOURCE[0m
[13:44:21]: ▸ [35m> Task :app:testDebugUnitTest[0m
[13:44:21]: ▸ [35m> Task :app:test[0m
[13:44:21]: ▸ [35mBUILD SUCCESSFUL in 14s[0m
[13:44:21]: ▸ [35m28 actionable tasks: 21 executed, 7 up-to-date[0m
[13:44:21]: Cruising back to lane 'android release' 🚘
[13:44:21]: [32m--------------------[0m
[13:44:21]: [32m--- Step: gradle ---[0m
[13:44:21]: [32m--------------------[0m
[13:44:21]: [36m$ /Users/michaelcollins/Projects/mfcollins3/paycheck-simulator/android/gradlew clean bundleRelease -p . -Pandroid.injected.signing.store.file=keystore.jks -Pandroid.injected.signing.store.password=xMVHtUu7zyPgNZmksMVLAbpc -Pandroid.injected.signing.key.alias=upload -Pandroid.injected.signing.key.password=FbqcNtUhRXycJrAqn2tTEzgV[0m
[13:44:22]: ▸ [35m> Task :clean[0m
[13:44:23]: ▸ [35m> Task :app:clean[0m
[13:44:23]: ▸ [35m> Task :app:preBuild UP-TO-DATE[0m
[13:44:23]: ▸ [35m> Task :app:preReleaseBuild UP-TO-DATE[0m
[13:44:23]: ▸ [35m> Task :app:generateReleaseResValues[0m
[13:44:23]: ▸ [35m> Task :app:checkReleaseManifest[0m
[13:44:23]: ▸ [35m> Task :app:createReleaseCompatibleScreenManifests[0m
[13:44:23]: ▸ [35m> Task :app:mainApkListPersistenceRelease[0m
[13:44:23]: ▸ [35m> Task :app:compileReleaseRenderscript NO-SOURCE[0m
[13:44:23]: ▸ [35m> Task :app:generateReleaseResources[0m
[13:44:24]: ▸ [35m> Task :app:processReleaseManifest[0m
[13:44:24]: ▸ [35m> Task :app:mergeReleaseResources[0m
[13:44:24]: ▸ [35m> Task :app:checkReleaseDuplicateClasses[0m
[13:44:25]: ▸ [35m> Task :app:generateReleaseBuildConfig[0m
[13:44:25]: ▸ [35m> Task :app:compileReleaseAidl NO-SOURCE[0m
[13:44:26]: ▸ [35m> Task :app:processReleaseResources[0m
[13:44:27]: ▸ [35m> Task :app:compileReleaseKotlin[0m
[13:44:27]: ▸ [35m> Task :app:bundleReleaseResources[0m
[13:44:27]: ▸ [35m> Task :app:javaPreCompileRelease[0m
[13:44:27]: ▸ [35m> Task :app:compileReleaseJavaWithJavac[0m
[13:44:27]: ▸ [35mwarning: [options] source value 7 is obsolete and will be removed in a future release[0m
[13:44:27]: ▸ [35mwarning: [options] target value 7 is obsolete and will be removed in a future release[0m
[13:44:27]: ▸ [35mwarning: [options] To suppress warnings about obsolete options, use -Xlint:-options.[0m
[13:44:27]: ▸ [35m3 warnings[0m
[13:44:28]: ▸ [35m> Task :app:transformClassesWithDexBuilderForRelease[0m
[13:44:28]: ▸ [35m> Task :app:mergeExtDexRelease[0m
[13:44:28]: ▸ [35m> Task :app:mergeReleaseShaders[0m
[13:44:28]: ▸ [35m> Task :app:compileReleaseShaders[0m
[13:44:28]: ▸ [35m> Task :app:generateReleaseAssets[0m
[13:44:28]: ▸ [35m> Task :app:mergeReleaseAssets[0m
[13:44:28]: ▸ [35m> Task :app:processReleaseJavaRes NO-SOURCE[0m
[13:44:28]: ▸ [35m> Task :app:mergeReleaseJniLibFolders[0m
[13:44:28]: ▸ [35m> Task :app:collectReleaseDependencies[0m
[13:44:28]: ▸ [35m> Task :app:configureReleaseDependencies[0m
[13:44:28]: ▸ [35m> Task :app:validateSigningRelease[0m
[13:44:28]: ▸ [35m> Task :app:signingConfigWriterRelease[0m
[13:44:28]: ▸ [35m> Task :app:mergeReleaseNativeLibs[0m
[13:44:28]: ▸ [35m> Task :app:stripReleaseDebugSymbols[0m
[13:44:28]: ▸ [35m> Task :app:mergeReleaseJavaResource[0m
[13:44:29]: ▸ [35m> Task :app:mergeDexRelease[0m
[13:44:29]: ▸ [35m> Task :app:buildReleasePreBundle[0m
[13:44:29]: ▸ [35m> Task :app:packageReleaseBundle[0m
[13:44:29]: ▸ [35m> Task :app:signReleaseBundle[0m
[13:44:29]: ▸ [35m> Task :app:bundleRelease[0m
[13:44:29]: ▸ [35mBUILD SUCCESSFUL in 7s[0m
[13:44:29]: ▸ [35m32 actionable tasks: 32 executed[0m
[13:44:30]: [32m----------------------------------[0m
[13:44:30]: [32m--- Step: upload_to_play_store ---[0m
[13:44:30]: [32m----------------------------------[0m

+-------------------------+--------------------------------------+
|                   [32mSummary for supply 2.137.0[0m                   |
+-------------------------+--------------------------------------+
| json_key_data           | ********                             |
| release_status          | draft                                |
| aab                     | /Users/michaelcollins/Projects/mfco  |
|                         | llins3/paycheck-simulator/android/a  |
|                         | pp/build/outputs/bundle/release/app  |
|                         | -release.aab                         |
| package_name            | me.michaelfcollins3.paychecksimulat  |
|                         | or                                   |
| track                   | production                           |
| metadata_path           | ./fastlane/metadata/android          |
| skip_upload_apk         | false                                |
| skip_upload_aab         | false                                |
| skip_upload_metadata    | false                                |
| skip_upload_changelogs  | false                                |
| skip_upload_images      | false                                |
| skip_upload_screenshots | false                                |
| validate_only           | false                                |
| check_superseded_tracks | false                                |
| timeout                 | 300                                  |
| deactivate_on_promote   | true                                 |
+-------------------------+--------------------------------------+

[13:44:31]: Preparing aab at path '/Users/michaelcollins/Projects/mfcollins3/paycheck-simulator/android/app/build/outputs/bundle/release/app-release.aab' for upload...
[13:44:40]: Updating track 'production'...
+-------------------------------------+--------------------------------------+
|                                [33mLane Context[0m                                |
+-------------------------------------+--------------------------------------+
| DEFAULT_PLATFORM                    | android                              |
| PLATFORM_NAME                       | android                              |
| LANE_NAME                           | android release                      |
| GRADLE_BUILD_TYPE                   | Release                              |
| GRADLE_ALL_APK_OUTPUT_PATHS         | []                                   |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | ["/Users/michaelcollins/Projects/mf  |
|                                     | collins3/paycheck-simulator/android  |
|                                     | /app/build/outputs/bundle/release/a  |
|                                     | pp-release.aab"]                     |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                                   |
| GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS | []                                   |
| GRADLE_AAB_OUTPUT_PATH              | /Users/michaelcollins/Projects/mfco  |
|                                     | llins3/paycheck-simulator/android/a  |
|                                     | pp/build/outputs/bundle/release/app  |
|                                     | -release.aab                         |
+-------------------------------------+--------------------------------------+

+------+----------------------+-------------+
|             [32mfastlane summary[0m              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | Switch to android    | 0           |
|      | test lane            |             |
| 3    | gradle               | 14          |
| 4    | gradle               | 8           |
| 💥   | [31mupload_to_play_store[0m | 10          |
+------+----------------------+-------------+

[13:44:41]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mFrameit private method `select' called for nil:NilClass[0m
    https://github.com/fastlane/fastlane/issues/15350 [[32mclosed[0m] 3 💬
    4 weeks ago

➡️  [33m[!] undefined method `set_setting' for nil:NilClass (NoMethodError) on automatic_code_signing.rb[0m
    https://github.com/fastlane/fastlane/issues/15590 [[32mclosed[0m] 1 💬
    a week ago

➡️  [33m[FrameIt] Hindi letters not rendering [0m
    https://github.com/fastlane/fastlane/issues/15247 [[32mclosed[0m] 6 💬
    2 days ago

and 26 more at: https://github.com/fastlane/fastlane/search?q=private%20method%20%60select%27%20called%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.6.0/bin/fastlane)
NoMethodError: [!] private method `select' called for nil:NilClass
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/supply/lib/supply/client.rb:350:in `tracks'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/supply/lib/supply/uploader.rb:360:in `update_track'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/supply/lib/supply/uploader.rb:22:in `perform_upload'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:89:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<top (required)>' </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.0                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib            |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | ~/Downloads/Xcode.app/Contents/Developer/   |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  private_lane :build_app_for_screengrab do
    gradle(task: "clean")
    build_android_app(
      task: "assemble",
      build_type: "Debug"
    )
    build_android_app(
      task: "assemble",
      build_type: "AndroidTest"
    )
  end

  desc "Capture screenshots for a phone"
  lane :capture_phone_screenshots do
    build_app_for_screengrab
    screengrab(
      device_type: "phone",
      skip_open_summary: true
    )
  end

  desc "Capture screenshots for a 7-inch tablet"
  lane :capture_small_tablet_screenshots do
    build_app_for_screengrab
    screengrab(
      device_type: "sevenInch",
      skip_open_summary: true,
      use_adb_root: true
    )
  end

  desc "Capture screenshots for a 10-inch tablet"
  lane :capture_large_tablet_screenshots do
    build_app_for_screengrab
    screengrab(
      device_type: "tenInch",
      skip_open_summary: true,
      use_adb_root: true
    )
  end

  desc "Submit a new Paycheck Simulator build for internal testing"
  lane :internal do
    test
    gradle(
      task: "clean bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => "keystore.jks",
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
      }
    )
    upload_to_play_store(
      # json_key_data: ENV["JSON_KEY_DATA"],
      json_key: "/Users/michaelcollins/Downloads/api-8329566455821274439-982877-dedaadd3d8c2.json",
      track: "internal"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :release do
    test
    gradle(
      task: "clean bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => "keystore.jks",
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
      }
    )
    upload_to_play_store(
      json_key_data: ENV["JSON_KEY_DATA"],
      release_status: "draft"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
package_name("me.michaelfcollins3.paychecksimulator")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.69.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.1       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-11-26**
</details> </pre>
</details>

**Comment by riglar** [comment]
This is causing us issues, if there is anything I can do to help, please shout.

**Comment by cjohn001** [comment]
Helle @riglar,
have you found a workaround for it yet? I am having the same issue.

Best regards,
 Christoph

**Comment by riglar** [comment]
I've not yet. We are currently manually uploading to Google.

**Comment by cjohn001** [comment]
Ok, same here. If someone finds a workaround it would be great if he mentions it here.

**Comment by mfcollins3** [comment]
I believe that I fixed the issue. I'm preparing a PR right now.

**Comment by mfcollins3** [comment]
I verified that my fix is working (for me at least), in my build running in GitHub Actions. You can use my branch until my fix PR is accepted. Here's the info for your `Gemfile`:

```ruby
gem 'fastlane', :git => "https://github.com/mfcollins3/fastlane.git", :branch => "supply-fix-missing-tracks"
```

The version on my branch reports itself as 2.137.0, so you'll need to uninstall the official Fastlane release if you have it installed.
