### ISSUE TITLE
[supply] Issue when promoting app from beta to prod and specifying version code

### ISSUE THREAD

**Issue by mhdtouban** [fastlane/fastlane#15769]
### Issue Description
When promoting the app from beta to prod and specifying version code I got the following error

##### Command executed
bundle exec fastlane android promote_app_to_production brand:example rollout:0.5

##### Complete output when running fastlane, including the stack trace and command used
``` bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `include?' for nil:NilClass
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/supply/lib/supply/uploader.rb:150:in `block in promote_track'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/supply/lib/supply/uploader.rb:149:in `select'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/supply/lib/supply/uploader.rb:149:in `promote_track'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/supply/lib/supply/uploader.rb:26:in `perform_upload'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:589:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
```

``` desc "Promote specific brand app from beta track to production with a rollout %"
  desc 'Options:'
  desc ' - `rollout` (required).'
  desc ' - `brand` (required).'
  lane :promote_app_to_production do |options|
      if options[:rollout]
        supply(
          package_name: ANDROID_PRODUCTION_PACKAGE_NAMES[options[:brand]],
          json_key: get_google_play_api_access_key(options[:brand]),
          version_code: get_android_build_code, # ex. 140
          track: 'beta',
          track_promote_to: 'production',
          rollout: options[:rollout],
          release_status: 'inProgress',
          skip_upload_apk: true,
          skip_upload_aab: true,
          skip_upload_metadata: false,
          skip_upload_changelogs: false,
          skip_upload_images: true,
          skip_upload_screenshots: true,
          validate_only: true,
         )
     else
         UI.user_error!("Parameter rollout must be provided")
     end
  end ```

### Environment
fastlane version 2.137.0

**Comment by mhdtouban** [comment]
It works fine when you don't provide the version_code .. according to docs ```Version code (used when updating rollout or promoting specific versions```
