### ISSUE TITLE
Fastlane Error : Is a directory @ rb_sysopen 

### ISSUE THREAD

**Issue by aiOSFuture** [fastlane/fastlane#15828]
```
[16:43:46]: Is a directory @ rb_sysopen - /Users/fuyq/Library/MobileDevice/Provisioning Profiles/

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | my_run           | 19          |
+------+------------------+-------------+

[16:43:46]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/fuyq/Desktop/Fastlane/Fastlane/actions/my_run.rb:51:in `write': [!] Is a directory @ rb_sysopen - /Users/fuyq/Library/MobileDevice/Provisioning Profiles/ (Errno::EISDIR)
	from /Users/fuyq/Desktop/Fastlane/Fastlane/actions/my_run.rb:51:in `block in run'
	from /Users/fuyq/Desktop/Fastlane/Fastlane/actions/my_run.rb:48:in `each'
	from /Users/fuyq/Desktop/Fastlane/Fastlane/actions/my_run.rb:48:in `run'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from ../fastlane/Fastfile:22:in `block (2 levels) in parsing_binding'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/gems/fastlane-2.138.0/bin/fastlane:23:in `<top (required)>'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `load'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `<main>'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/fuyq/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'
```
Help me with above all~

**Comment by aiOSFuture** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.4.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.5/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G103)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.5/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "一步到位"
  lane:my_test do |options|

  	my_run(
  		appleID:options[:appleID],
  		applePassword:options[:applePassword],
  		)

  	end

# desc "自动更新fastlane session"
#   lane:my_update

#   	update_fastlane_session (


#   		)

#   	end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

**Comment by janpio** [comment]
The code in `my_run` seems to try to do something that does not work. This is your custom code, not a problem of fastlane. If you can post the code, we might have a look and try to help you, but in general there is not much we can do about this.

**Comment by aiOSFuture** [comment]
> The code in `my_run` seems to try to do something that does not work. This is your custom code, not a problem of fastlane. If you can post the code, we might have a look and try to help you, but in general there is not much we can do about this.

Thanks for your reply，i probably resolved this！
