### ISSUE TITLE
`lane': [!] wrong number of arguments (given 0, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by RithvikSharma** [fastlane/fastlane#15842]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The error returns that lane method in line `83` in fastfile.rb is not receiving any arguments. The argument for this function seems to be the lane name for every user defined lane that is called.
All my lanes have stopped working and return the same error message.
##### Command executed

`bundle exec fastlane test`
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [16:53:35]: Plugin 'Telegram' overwrites already loaded action 'telegram'
./gradlew
hello
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | Version | Action                 |
+------------------------+---------+------------------------+
| fastlane-plugin-teleg  | 0.1.3   | telegram               |
| ram                    |         |                        |
| fastlane-plugin-autom  | 1.6.0   | automated_test_emulat  |
| ated_test_emulator_ru  |         | or_run test            |
| n                      |         |                        |
+------------------------+---------+------------------------+

[16:53:36]: ------------------------------
[16:53:36]: --- Step: default_platform ---
[16:53:36]: ------------------------------

Looking for related GitHub issues on fastlane/fastlane...

➡️  Wrong number of arguments provisioning_profile.rb
    https://github.com/fastlane/fastlane/issues/14557 [closed] 3 💬
    18 Jul 2019

➡️  pilot import CSV library wrong number of arguments
    https://github.com/fastlane/fastlane/issues/12403 [closed] 10 💬
    10 Oct 2018

➡️  Spaceship::TestFlight::Group.create!(app_id, group_name) does not accept arguments
    https://github.com/fastlane/fastlane/issues/13044 [closed] 3 💬
    07 Oct 2018

and 15 more at: https://github.com/fastlane/fastlane/search?q=wrong%20number%20of%20arguments%20%28given%200%2C%20expected%201%29&type=Issues&utf8=✓

C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:83:in `lane': [!] wrong number of arguments (given 0, expected 1) (ArgumentError)
        from Fastfile:79:in `block in parsing_binding'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:127:in `platform'
        from Fastfile:18:in `parsing_binding'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/lane_manager.rb:16:in `new'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/lane_manager.rb:16:in `cruise_lane'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/bin/fastlane:23:in `<top (required)>'
        from C:/Users/rithvik.sharma/Ruby26-x64/bin/fastlane:23:in `load'
        from C:/Users/rithvik.sharma/Ruby26-x64/bin/fastlane:23:in `<main>'
C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:83:in `lane': wrong number of arguments (given 0, expected 1) (ArgumentError)
        from Fastfile:79:in `block in parsing_binding'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:127:in `platform'
        from Fastfile:18:in `parsing_binding'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/lane_manager.rb:16:in `new'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/lane_manager.rb:16:in `cruise_lane'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        from C:/Users/rithvik.sharma/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.138.0/bin/fastlane:23:in `<top (required)>'
        from C:/Users/rithvik.sharma/Ruby26-x64/bin/fastlane:23:in `load'
        from C:/Users/rithvik.sharma/Ruby26-x64/bin/fastlane:23:in `<main>'

 </pre>
</details>

### Environment

<details>
  <pre>[16:55:44]: fastlane detected a Gemfile in the current directory
[16:55:44]: However, it seems like you didn't use `bundle exec`
[16:55:44]: To launch fastlane faster, please use
[16:55:44]:
[16:55:44]: $ bundle exec fastlane env
[16:55:44]:
[16:55:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:55:47]: Generating fastlane environment output, this might take a few seconds...
[16:55:48]: Plugin 'Telegram' overwrites already loaded action 'telegram'
./gradlew
hello
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | UNKNOWN                                         |
| Ruby                        | 2.6.5                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.24.0.windows.2                    |
| Installation Source         | C:/Users/rithvik.sharma/Ruby26-x64/bin/fastlane |
| Host                        | Unknown  ()                                     |
| Ruby Lib Dir                | C:/Users/rithvik.sharma/Ruby26-x64/lib          |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  # Runs before all tasks
  before_all do

   # Add SLACK_URL & make it accessible to all lanes
   ENV["SLACK_URL"]
  end

  desc "Build a debug APK"
  lane :debug_build do
    gradle(task: "clean assembleDebug")
  end

  desc "Build a signed release APK & deploy to slack"
  lane :slack_apk_build do
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      }
    )
    upload_to_slack()
    slack(message: ":rocket: *Build Successful!* :rocket:")
  end

  desc "Upload APK to Slack channel"
  private_lane :upload_to_slack do |options|
    file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    file_name = file_path.gsub(/\/.*\//,"")
    access_token = ENV["ACCESS_TOKEN"]
    channel_name = "testing-a-tool"

    sh "echo Uploading " + file_name + " to Slack"
    sh "curl https://slack.com/api/files.upload -F token=\"" + access_token + "\" -F channels=\"" + channel_name + "\" -F title=\"" + file_name + "\" -F filename=\"" + file_name + "\" -F file=@" + file_path
  end

  lane

  desc "Telegram plugin test"
  lane :message_telegram do
    telegram(
      token: "xyz",
      chat_id: "xyz",
      text: "Hello world!",
      proxy: ""

    )
  end

  desc "Run tests with usage of emulator plugin"
  lane :automation_integrationTests do
    #Dir.chdir("..") do
        automated_test_emulator_run(
            AVD_setup_path: "C:\\Users\\rithvik.sharma\\AndroidStudioProjects\\MyFirstApp\\fastlane\\AVD_configs\\AVD_setup.json",
            AVD_recreate_new: false,
            AVD_clean_after: false,
            gradle_task: "connectedAndroidTest"
        )
    #end
  end

  # Runs after all tasks. This block is called only when the executed lane is successful
  after_all do |lane|

    # Slack action
     slack(message: ":rocket: Successful Deployment! :rocket:")
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
      )
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.example.myfirstapp") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.138.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-telegram                    | 0.1.3   | ✅ Up-To-Date  |
| fastlane-plugin-telegram                    | 0.1.3   | ✅ Up-To-Date  |
| fastlane-plugin-automated_test_emulator_run | 1.6.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.3.0        |
| slack-notifier                              | 2.3.2        |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.3.0        |
| terminal-notifier                           | 2.0.0        |
| unicode-display_width                       | 1.6.0        |
| terminal-table                              | 1.8.0        |
| plist                                       | 3.5.0        |
| public_suffix                               | 2.0.5        |
| addressable                                 | 2.7.0        |
| multipart-post                              | 2.0.0        |
| word_wrap                                   | 1.0.0        |
| tty-screen                                  | 0.7.0        |
| babosa                                      | 1.0.3        |
| colored                                     | 1.2          |
| highline                                    | 1.7.10       |
| commander-fastlane                          | 4.4.6        |
| excon                                       | 0.71.1       |
| faraday                                     | 0.17.1       |
| unf_ext                                     | 0.0.7.6      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20190701 |
| http-cookie                                 | 1.0.3        |
| faraday-cookie_jar                          | 0.0.6        |
| faraday_middleware                          | 0.13.1       |
| fastimage                                   | 2.1.7        |
| gh_inspector                                | 1.1.3        |
| mini_magick                                 | 4.9.5        |
| multi_xml                                   | 0.6.0        |
| rubyzip                                     | 1.3.0        |
| security                                    | 0.1.3        |
| xcpretty-travis-formatter                   | 1.0.0        |
| dotenv                                      | 2.7.5        |
| bundler                                     | 2.0.2        |
| jwt                                         | 2.1.0        |
| uber                                        | 0.1.0        |
| declarative                                 | 0.0.10       |
| declarative-option                          | 0.1.0        |
| representable                               | 3.0.4        |
| retriable                                   | 3.1.2        |
| mime-types-data                             | 3.2019.1009  |
| mime-types                                  | 3.3          |
| multi_json                                  | 1.14.1       |
| signet                                      | 0.12.0       |
| memoist                                     | 0.16.2       |
| os                                          | 1.0.1        |
| googleauth                                  | 0.6.7        |
| httpclient                                  | 2.8.3        |
| google-api-client                           | 0.23.9       |
| google-cloud-env                            | 1.3.0        |
| google-cloud-core                           | 1.4.1        |
| digest-crc                                  | 0.4.1        |
| google-cloud-storage                        | 1.16.0       |
| emoji_regex                                 | 1.0.1        |
| nanaimo                                     | 0.2.6        |
| colored2                                    | 3.1.2        |
| claide                                      | 1.0.3        |
| CFPropertyList                              | 3.0.2        |
| atomos                                      | 0.1.3        |
| xcodeproj                                   | 1.14.0       |
| tty-cursor                                  | 0.7.0        |
| tty-spinner                                 | 0.9.2        |
| json                                        | 2.3.0        |
| naturally                                   | 2.2.0        |
| simctl                                      | 1.6.7        |
| forwardable                                 | 1.2.0        |
| logger                                      | 1.3.0        |
| stringio                                    | 0.0.2        |
| ipaddr                                      | 1.2.2        |
| openssl                                     | 2.1.2        |
| ostruct                                     | 0.1.0        |
| strscan                                     | 1.0.0        |
| fiddle                                      | 1.0.0        |
| date                                        | 2.0.0        |
| fileutils                                   | 1.1.0        |
| etc                                         | 1.0.1        |
| zlib                                        | 1.0.0        |
| rexml                                       | 3.1.9        |
| psych                                       | 3.1.0        |
| mutex_m                                     | 0.1.0        |
| fastlane-plugin-telegram                    | 0.1.3        |
| fastlane-plugin-automated_test_emulator_run | 1.6.0        |
</details>

*generated on:* **2019-12-30**
</details>
[16:55:51]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[16:55:51]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
 </pre>
</details>

**Comment by RithvikSharma** [comment]
The issue is solved.
An unintended `lane' had creeped into my Fastfile, which I wasn't able to see before. 
Since I'm new to ruby, I currently don't use any linters (or know of any for code checking/syntax mistakes).

Any recommendations for the above? Silly errors that go undetected like this would waste a lot of developer time.
