### ISSUE TITLE
fastlane commands not running

### ISSUE THREAD

**Issue by danishashfaq** [fastlane/fastlane#15865]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I want to generate login session using fastlane command "fastlane spaceauth -u user@abc.com" for Continuous Integration. It was working fine previously on my MacOS. But when I update Ruby version from 2.3 to 2.7, now no fastlane command is running and it is giving me following error;
Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError). I have tried to update gem, bundler and fastlane but could not get any solution.
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
**fastlane spaceauth -u someuser@domain.com**
[⠙] 🚀 /Users/vsts/.rvm/gems/ruby-2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[⠼] 🚀 /Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
[⠴] 🚀 Traceback (most recent call last):
	24: from /Users/vsts/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	23: from /Users/vsts/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	22: from /usr/local/bin/fastlane:23:in `<main>'
	21: from /usr/local/bin/fastlane:23:in `load'
	20: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/fastlane-2.139.0/bin/fastlane:23:in `<top (required)>'
	19: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/cli_tools_distributor.rb:41:in `take_off'
	18: from /Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	17: from /Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	16: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/fastlane-2.139.0/fastlane/lib/fastlane.rb:27:in `<top (required)>'
	15: from /Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	14: from /Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	13: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
	12: from /Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	11: from /Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	10: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:3:in `<top (required)>'
	 9: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:4:in `<module:Fastlane>'
	 8: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:5:in `<class:PluginManager>'
	 7: from /Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 5: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `<top (required)>'
	 4: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `require_relative'
	 3: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:3:in `<top (required)>'
	 2: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<module:Bundler>'
	 1: from /Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/Users/vsts/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)

**gem env**

RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.7.0 (2019-12-25 patchlevel 0) [x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Users/vsts/.rvm/gems/ruby-2.7.0
  - USER INSTALLATION DIRECTORY: /Users/vsts/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/vsts/.rvm/rubies/ruby-2.7.0/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /Users/vsts/.rvm/gems/ruby-2.7.0/bin
  - SPEC CACHE DIRECTORY: /Users/vsts/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/vsts/.rvm/rubies/ruby-2.7.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-18
  - GEM PATHS:
     - /Users/vsts/.rvm/gems/ruby-2.7.0
     - /Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/vsts/.rvm/gems/ruby-2.7.0/bin
     - /Users/vsts/.rvm/gems/ruby-2.7.0@global/bin
     - /Users/vsts/.rvm/rubies/ruby-2.7.0/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Applications/git-tf/
     - /usr/local/share/dotnet
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /Users/vsts/Library/Android/sdk/platform-tools
     - /Users/vsts/Library/Android/sdk/tools
     - /opt/gradle/bin
     - /Users/vsts/.gem-cache/gems/fastlane-2.118.1/bin
     - /Users/vsts/.rvm/bin

**bundle env**

## Environment

```
Bundler             2.1.4
  Platforms         ruby, x86_64-darwin-18
Ruby                2.7.0p0 (2019-12-25 revision 647ee6f091eafcce70ffb75ddf7e121e192ab217) [x86_64-darwin18]
  Full Path         /Users/vsts/.rvm/rubies/ruby-2.7.0/bin/ruby
  Config Dir        /Users/vsts/.rvm/rubies/ruby-2.7.0/etc
RubyGems            3.1.2
  Gem Home          /Users/vsts/.rvm/gems/ruby-2.7.0
  Gem Path          /Users/vsts/.rvm/gems/ruby-2.7.0:/Users/vsts/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0
  User Home         /Users/vsts
  User Path         /Users/vsts/.gem/ruby/2.7.0
  Bin Dir           /Users/vsts/.rvm/gems/ruby-2.7.0/bin
Tools               
  Git               2.21.0 (Apple Git-122)
  RVM               1.29.9 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true

gem which fastlane
/Users/vsts/.rvm/gems/ruby-2.7.0/gems/fastlane-2.139.0/fastlane/lib/fastlane.rb
</pre>
</details>

### Environment

<!-- Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option, please remove this block as it is already included there. -->

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by danishashfaq** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

Because fastlane command is not running and it gives the same error as I mentioned above.

**Comment by danishashfaq** [comment]
I have solved the issue by simply deleting the latest bundler version and using old default version;
gem uninstall bundler
