### ISSUE TITLE
No such file or directory - sysctl

### ISSUE THREAD

**Issue by userException** [fastlane/fastlane#16090]
I was trying to execute the snapshot feature but got stuck with this error: **No such file or directory - sysctl**

Here is the detailed log. Please assist.

```
out: [07:17:19]: ▸ resolved source packages: 
1331	out: [07:17:19]: $ xcodebuild -showBuildSettings -scheme FastlaneSnapshotUITest -project ./CustomerPortal.xcodeproj
1332	out: 
1333	out: +----------------------------+--------------------------------------+
1334	out: |                   Summary for snapshot 2.142.0                    |
1335	out: +----------------------------+--------------------------------------+
1336	out: | project                    | ./CustomerPortal.xcodeproj           |
1337	out: | output_directory           | /Users/anka/Desktop/tempClone/fastl  |
1338	out: |                            | ane/screenshots                      |
1339	out: | devices                    | ["iPhone 11"]                        |
1340	out: | languages                  | ["en-US"]                            |
1341	out: | launch_arguments           | [""]                                 |
1342	out: | output_simulator_logs      | false                                |
1343	out: | skip_open_summary          | false                                |
1344	out: | skip_helper_version_check  | false                                |
1345	out: | clear_previous_screenshots | true                                 |
1346	out: | reinstall_app              | false                                |
1347	out: | erase_simulator            | false                                |
1348	out: | localize_simulator         | false                                |
1349	out: | app_identifier             | com.paymentus.cp.ios                 |
1350	out: | buildlog_path              | ~/Library/Logs/snapshot              |
1351	out: | clean                      | false                                |
1352	out: | scheme                     | FastlaneSnapshotUITest               |
1353	out: | number_of_retries          | 1                                    |
1354	out: | stop_after_first_error     | false                                |
1355	out: | result_bundle              | false                                |
1356	out: | concurrent_simulators      | true                                 |
1357	out: | disable_slide_to_type      | false                                |
1358	out: | xcode_path                 | /Applications/Xcode.app              |
1359	out: +----------------------------+--------------------------------------+
1360	out: 
1361	out: [07:17:20]: Clearing previously generated screenshots
1362	out: [07:17:20]: Building and running project - this might take some time...
1363	
1364	out: +------------------+----------------+
1365	out: |           Lane Context            |
1366	out: +------------------+----------------+
1367	
1368	out: | DEFAULT_PLATFORM | ios            |
1369	out: | PLATFORM_NAME    | ios            |
1370	out: | LANE_NAME        | ios screenshot |
1371	out: +------------------+----------------+
1372	out: [07:17:20]: No such file or directory - sysctl
1373	out: 
1374	out: +------+------------------+-------------+
1375	out: |           fastlane summary            |
1376	out: +------+------------------+-------------+
1377	out: | Step | Action           | Time (in s) |
1378	out: +------+------------------+-------------+
1379	out: | 1    | default_platform | 0           |
1380	out: | 💥   | snapshot         | 2           |
1381	out: +------+------------------+-------------+
1382	out: 
1383	out: [07:17:20]: fastlane finished with errors
1384	out: 
1385	out: [07:17:20]: Error accessing file, this might be due to fastlane's directory handling
1386	out: [07:17:20]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details
1387	out: 
1388	err: /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:23:in ``': No such file or directory - sysctl (Errno::ENOENT)
1389	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:23:in `cpu_count'
1390	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:35:in `default_number_of_simultaneous_simulators'
1391	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:63:in `block (3 levels) in take_screenshots_simultaneously'
1392	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:63:in `each'
1393	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:63:in `flat_map'
1394	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:63:in `block (2 levels) in take_screenshots_simultaneously'
1395	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each'
1396	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each_with_index'
1397	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `block in take_screenshots_simultaneously'
1398	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `each'
1399	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `take_screenshots_simultaneously'
1400	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/snapshot/lib/snapshot/runner.rb:45:in `work'
1401	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/capture_ios_screenshots.rb:14:in `run'
1402	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
1403	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
1404	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
1405	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
1406	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
1407	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
1408	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
1409	err: 	from Fastfile:39:in `block (2 levels) in parsing_binding'
1410	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/lane.rb:33:in `call'
1411	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
1412	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
1413	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
1414	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
1415	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
1416	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
1417	err: 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
1418	err: 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
1419	err: 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
1420	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
1421	err: 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
1422	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
1423	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
1424	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
1425	err: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
1426	err: 	from /usr/local/bin/fastlane:23:in `load'
1427	err: 	from /usr/local/bin/fastlane:23:in `<main>'
1428

**Comment by janpio** [comment]
Probably this code:
https://github.com/fastlane/fastlane/blob/d9340c5bf7541c0eb0e101e64018538ea9cf4aa9/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb#L10-L28

Please follow what @fastlane-bot posted - this might give us some information what is special about your environment.
