### ISSUE TITLE
bundler: failed to load command: pod (/usr/local/bin/pod) Bundler::GemNotFound: Could not find CFPropertyList-3.0.2 in any of the sources

### ISSUE THREAD

**Issue by PavelKatunin** [fastlane/fastlane#16102]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I run my unit tests lane something happens with cocoapods

```
Exit status of command 'bundle exec pod install' was 1 instead of 0.
bundler: failed to load command: pod (/usr/local/bin/pod)
Bundler::GemNotFound: Could not find CFPropertyList-3.0.2 in any of the sources
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'

    lane :unit_test_app_chemistry do
        setup_circle_ci
        cocoapods(
          clean: true,
          use_bundle_exec: true
        )
        match(type: "development")
        scan(
          scheme: 'MyScheme',        # XCTest scheme
          clean: true,                        # Recommended: This would ensure the build would not include unnecessary files
          skip_detect_devices: true,          # Required
          build_for_testing: true,            # Required
          sdk: 'iphoneos',                    # Required
          should_zip_build_products: true,    # Must be true to set the correct format for Firebase Test Lab
          disable_slide_to_type: true         # Workaround 2.142.0 error on scan
        )
        xcov(
          workspace: "MyProject.xcworkspace",
          scheme: "MyScheme",
          only_project_targets: true,
          json_report: true,
          output_directory: "./fastlane/xcov_output"
        )
    end

##### Command executed
sudo bundle exec fastlane unit_test_app_chemistry

##### Complete output when running fastlane, including the stack trace and command used
#!/bin/bash --login -eo pipefail
sudo fastlane unit_test_app_chemistry
[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [⠴] 🚀 [⠦] 🚀 [⠧] 🚀 [⠇] 🚀 [⠏] 🚀 [✔] 🚀 
[11:33:16]: fastlane detected a Gemfile in the current directory
[11:33:16]: However, it seems like you didn't use `bundle exec`
[11:33:16]: To launch fastlane faster, please use
[11:33:16]: 
[11:33:16]: $ bundle exec fastlane unit_test_app_chemistry
[11:33:16]: 
[11:33:16]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:33:17]: Sending anonymous analytics information
[11:33:17]: Learn more at https://docs.fastlane.tools/#metrics
[11:33:17]: No personal or sensitive data is sent.
[11:33:17]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[11:33:17]: ----------------------------------------
[11:33:17]: --- Step: Verifying fastlane version ---
[11:33:17]: ----------------------------------------
[11:33:17]: Your fastlane version 2.140.0 matches the minimum requirement of 2.140.0  ✅
[11:33:17]: ------------------------------
[11:33:17]: --- Step: default_platform ---
[11:33:17]: ------------------------------
[11:33:17]: Driving the lane 'ios unit_test_app_chemistry' 🚀
[11:33:17]: -----------------------------
[11:33:17]: --- Step: update_fastlane ---
[11:33:17]: -----------------------------
[11:33:17]: Looking for updates for fastlane...
[11:33:20]: Updating fastlane from 2.140.0 to 2.142.0... 🚀
[11:34:07]: Finished updating fastlane
[11:34:07]: Cleaning up old versions...
[11:34:08]: fastlane.tools successfully updated! I will now restart myself... 😴
[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [✔] 🚀 
[11:34:10]: fastlane detected a Gemfile in the current directory
[11:34:10]: However, it seems like you didn't use `bundle exec`
[11:34:10]: To launch fastlane faster, please use
[11:34:10]: 
[11:34:10]: $ bundle exec fastlane unit_test_app_chemistry
[11:34:10]: 
[11:34:10]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:34:11]: ----------------------------------------
[11:34:11]: --- Step: Verifying fastlane version ---
[11:34:11]: ----------------------------------------
[11:34:11]: Your fastlane version 2.142.0 matches the minimum requirement of 2.140.0  ✅
[11:34:11]: ------------------------------
[11:34:11]: --- Step: default_platform ---
[11:34:11]: ------------------------------
[11:34:11]: Driving the lane 'ios unit_test_app_chemistry' 🚀
[11:34:11]: -----------------------------
[11:34:11]: --- Step: update_fastlane ---
[11:34:11]: -----------------------------
[11:34:11]: -----------------------------
[11:34:11]: --- Step: setup_circle_ci ---
[11:34:11]: -----------------------------
[11:34:11]: Not running on CI, skipping CI setup
[11:34:11]: Using deprecated option: '--clean' (true)
[11:34:11]: -----------------------
[11:34:11]: --- Step: cocoapods ---
[11:34:11]: -----------------------
[11:34:11]: $ bundle exec pod install
[11:34:11]: ▸ bundler: failed to load command: pod (/usr/local/bin/pod)
[11:34:11]: ▸ Bundler::GemNotFound: Could not find CFPropertyList-3.0.2 in any of the sources
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
[11:34:11]: ▸ /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
[11:34:11]: Exit status of command 'bundle exec pod install' was 1 instead of 0.
bundler: failed to load command: pod (/usr/local/bin/pod)
Bundler::GemNotFound: Could not find CFPropertyList-3.0.2 in any of the sources
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'

+------------------+-----------------------------+
|                  Lane Context                  |
+------------------+-----------------------------+
| DEFAULT_PLATFORM | ios                         |
| PLATFORM_NAME    | ios                         |
| LANE_NAME        | ios unit_test_app_chemistry |
+------------------+-----------------------------+
[11:34:11]: bundler: failed to load command: pod (/usr/local/bin/pod)
Bundler::GemNotFound: Could not find CFPropertyList-3.0.2 in any of the sources
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'


+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying fastlane  | 0           |
|      | version             |             |
| 2    | default_platform    | 0           |
| 3    | update_fastlane     | 0           |
| 4    | setup_circle_ci     | 0           |
| 💥   | cocoapods           | 0           |
+------+---------------------+-------------+

[11:34:11]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	32: from /usr/local/bin/fastlane:23:in `<main>'
	31: from /usr/local/bin/fastlane:23:in `load'
	30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	26: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	22: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	14: from Fastfile:21:in `block (2 levels) in parsing_binding'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/cocoapods.rb:29:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/helper/sh_helper.rb:78:in `sh_control_output'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/cocoapods.rb:36:in `block in run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/cocoapods.rb:55:in `call_error_callback'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] bundler: failed to load command: pod (/usr/local/bin/pod) (FastlaneCore::Interface::FastlaneShellError)
Bundler::GemNotFound: Could not find CFPropertyList-3.0.2 in any of the sources
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'


Exited with code exit status 1

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:48:21]: Sending anonymous analytics information
[11:48:21]: Learn more at https://docs.fastlane.tools/#metrics
[11:48:21]: No personal or sensitive data is sent.
[11:48:21]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[11:48:21]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.25.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-11.3.1.app/Contents/Developer/             |
| Xcode Version               | 11.3.1                                                         |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.melscience.melchemistry"         # The bundle identifier of your app
apple_dev_portal_id "infrastructure@melscience.com"  # Apple Developer Account
team_id "7M23Z4PMXZ"                                 # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.15.0       |
| unicode-display_width     | 1.6.1        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.72.0       |
| json                      | 2.3.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.11.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-03-01**
</details>
[11:48:22]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[11:48:22]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by dev-kang** [comment]
I have the same issue.

**Comment by JoveI** [comment]
"bundle update" did the job for me.
