### ISSUE TITLE
[sigh] When only AppleDistribution certificate exists, sigh crashes on provisioning profile repair.

### ISSUE THREAD

**Issue by barakwei** [fastlane/fastlane#16103]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When the only existing distribution certificate is an "Apple Distribution", and no "iOS Distribution" exist, `sigh` crashes when trying to repair distribution provisioning profiles.

The problem is that when repairing provisioning profiles, a certificate needs to be chosen for the profile and the [code ignores Apple developement/distribution certs](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/provisioning_profile.rb#L431-L448). It should probably use the same logic [that exist in a different place in sigh](https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/runner.rb#L157-L191) to choose a certificate.

##### Command executed
`fastlane sigh repair`

##### Complete output when running fastlane, including the stack trace and command used
```
[13:57:32]: Repairing profile 'XXXXXXX'...

Looking for related GitHub issues on fastlane/fastlane...
Traceback (most recent call last):
	19: from /Users/barakwei/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
	18: from /Users/barakwei/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
	17: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	16: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	14: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/sigh/lib/sigh/commands_generator.rb:138:in `run'
	13: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/sigh/lib/sigh/commands_generator.rb:95:in `block (2 levels) in run'
	 7: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/sigh/lib/sigh/repair.rb:26:in `repair_all'
	 6: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/sigh/lib/sigh/repair.rb:26:in `each'
	 5: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/sigh/lib/sigh/repair.rb:28:in `block in repair_all'
	 4: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:418:in `repair!'
	 3: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:450:in `update!'
	 2: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/spaceship/lib/spaceship/client.rb:625:in `with_retry'
	 1: from /Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:456:in `block in update!'
/Users/barakwei/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:456:in `map': undefined method `id' for nil:NilClass (NoMethodError)
```

### Environment
I don't think it's relevant, the bug is pretty clear.

**Comment by barakwei** [comment]
Doesn't look like this was resolved
