### ISSUE TITLE
fastlane match init doesn't work with S3

### ISSUE THREAD

**Issue by arturgrigor** [fastlane/fastlane#16183]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`fastlane match init` doesn't work when you select the S3 storage mode.

##### Command executed
`fastlane match init`

##### Complete output when running fastlane, including the stack trace and command used
fastlane match init
[✔] 🚀
[16:23:22]: fastlane match supports multiple storage modes, please select the one you want to use:
1. git
2. google_cloud
3. s3
?  3
NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3

Looking for related GitHub issues on fastlane/fastlane...

➡️  Provisioning Profile mapping in build_ios_app is not used
    https://github.com/fastlane/fastlane/issues/14061 [closed] 4 💬
    17 Mar 2019

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	25: from /usr/local/bin/fastlane:23:in `<main>'
	24: from /usr/local/bin/fastlane:23:in `load'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/bin/fastlane:23:in `<top (required)>'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/commands_generator.rb:25:in `start'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/commands_generator.rb:186:in `run'
	19: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	17: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	16: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/commands_generator.rb:90:in `block (2 levels) in run'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/setup.rb:18:in `run'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage.rb:40:in `for_mode'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage.rb:18:in `block in backends'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage/s3_storage.rb:35:in `configure'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage/s3_storage.rb:35:in `new'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage/s3_storage.rb:57:in `initialize'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage/s3_storage.rb:57:in `new'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:15:in `initialize'
	 5: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:105:in `new'
	 4: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:21:in `initialize'
	 3: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:83:in `after_initialize'
	 2: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:83:in `each'
	 1: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:84:in `block in after_initialize'
/Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/aws-sdk-core/plugins/regional_endpoint.rb:39:in `after_initialize': missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
	25: from /usr/local/bin/fastlane:23:in `<main>'
	24: from /usr/local/bin/fastlane:23:in `load'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/bin/fastlane:23:in `<top (required)>'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/commands_generator.rb:25:in `start'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/commands_generator.rb:186:in `run'
	19: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	17: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	16: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/commands_generator.rb:90:in `block (2 levels) in run'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/setup.rb:18:in `run'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage.rb:40:in `for_mode'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage.rb:18:in `block in backends'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage/s3_storage.rb:35:in `configure'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage/s3_storage.rb:35:in `new'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage/s3_storage.rb:57:in `initialize'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/storage/s3_storage.rb:57:in `new'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:15:in `initialize'
	 5: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:105:in `new'
	 4: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:21:in `initialize'
	 3: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:83:in `after_initialize'
	 2: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:83:in `each'
	 1: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/seahorse/client/base.rb:84:in `block in after_initialize'
/Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-2.11.463/lib/aws-sdk-core/plugins/regional_endpoint.rb:39:in `after_initialize': [!] missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)

**Comment by janpio** [comment]
> [!] missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)

Did you try to set this ENV var?

**Comment by arturgrigor** [comment]
> > [!] missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
> 
> 
> 
> Did you try to set this ENV var?

Yes, and still nothing, but that’s the whole purpose of ‘match init’, to set up the base configuration step by step, isn’t it?

**Comment by janpio** [comment]
The docs say you need to provide those values for sure: https://docs.fastlane.tools/actions/match/#amazon-s3-storage-access (also listed in https://docs.fastlane.tools/actions/match/#parameters) The error message indicates that might not have worked for you.

**Comment by FadiAboMsalam** [comment]
same issue here did you manage to make it work ?

**Comment by arturgrigor** [comment]
I did by manually creating the `Matchfile` with all the required info but I got into another problem with the build afterward; `gym` would not load the code signing stuff properly even after I recreated them several times so I reverted back to the Git storage mode and everything worked just fine.

**Comment by gordonmleigh** [comment]
Despite the misleading error message and complete lack of documentation, I found the real names of the environment variables here:

https://github.com/fastlane/fastlane/blob/e16aaebd699497ba2204e0d8bf5a90ebc1e79f0d/match/lib/match/options.rb#L163-L178

**Comment by Lucashuang0802** [comment]
+1 on https://github.com/fastlane/fastlane/issues/16183#issuecomment-601840742
