### ISSUE TITLE
swiftlint files parameter broken?

### ISSUE THREAD

**Issue by schweizerm** [fastlane/fastlane#16195]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running the swiftlint command together with the files parameter always throws errors, saying that map can't be called on a string. Other parameters like reporter and output_file are working fine. According to the docs arrays have to be submitted like _param:"1,2,3"_, but for me neither this nor single files work. 
Issue might be this line since it tries to run map on a string (if it's not me just being using it totally wrong..):
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/swiftlint.rb#L23
[Line differs from the outcome tho 🤔]

##### Command executed
Tried multiple things:
```
fastlane run swiftlint files:File.swift
fastlane run swiftlint files:"File.swift"
fastlane run swiftlint files:'File.swift'
fastlane run swiftlint files:[File.swift]
fastlane run swiftlint files:["File.swift"]
```

Also with multiple files like:
`fastlane run swiftlint files:"FileA.swift,FileB.swift"`
...also with multiple different notations like above as well as with breaks after comma etc.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>

```
markus@macpro $ fastlane run swiftlint files:LightMaintenance.swift
[✔] 🚀
[10:13:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:13:22]: -----------------------
[10:13:22]: --- Step: swiftlint ---
[10:13:22]: -----------------------

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	21: from /Users/markus/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	20: from /Users/markus/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	19: from /Users/markus/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `<main>'
	18: from /Users/markus/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `load'
	17: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/bin/fastlane:23:in `<top (required)>'
	16: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	15: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	14: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	13: from /Users/markus/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Users/markus/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /Users/markus/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /Users/markus/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	 7: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	 6: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	 5: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 4: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 3: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 2: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 1: from /Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
/Users/markus/.rvm/gems/ruby-2.6.5/gems/fastlane-2.143.0/fastlane/lib/fastlane/actions/swiftlint.rb:29:in `run': undefined method `map' for "LightMaintenance.swift":String (NoMethodError)
Did you mean?  tap
```
</pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.25.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane         |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   | de_DE.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 2.11.463     |
| aws-sdk-resources         | 2.11.463     |
| aws-sdk                   | 2.11.463     |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.15.0       |
| unicode-display_width     | 1.6.1        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| faraday                   | 0.17.3       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.11.0       |
| digest-crc                | 0.5.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-03-21**
</details>

**Comment by schweizerm** [comment]
The issue still occurs with 2.146.1
