### ISSUE TITLE
Fastlane fails due to HTTP errors

### ISSUE THREAD

**Issue by racer1988** [fastlane/fastlane#16192]
Sigh fails and Fastlane start failing too

```
[14:20:08]: 784: unexpected token at '<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Request failed.</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /v1/session. Reason:
<pre>    Request failed.</pre></p>
</body>
</html>

```

```
[14:20:08]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
bundler: failed to load command: fastlane (/Users/vagrant/.rbenv/versions/2.6.5/bin/fastlane)
JSON::ParserError: [!] 784: unexpected token at '<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Request failed.</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /v1/session. Reason:
<pre>    Request failed.</pre></p>
</body>
</html>
'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/spaceship/lib/spaceship/client.rb:521:in `fetch_olympus_session'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/spaceship/lib/spaceship/client.rb:490:in `send_shared_login_request'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/spaceship/lib/spaceship/client.rb:775:in `do_login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/spaceship/lib/spaceship/client.rb:384:in `login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/spaceship/lib/spaceship/client.rb:346:in `login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/sigh/lib/sigh/runner.rb:19:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/sigh/lib/sigh/manager.rb:8:in `start'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/generator.rb:92:in `generate_provisioning_profile'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/runner.rb:254:in `fetch_provisioning_profile'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/runner.rb:107:in `block (2 levels) in run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/runner.rb:106:in `loop'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/runner.rb:106:in `block in run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/runner.rb:105:in `each'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/match/lib/match/runner.rb:105:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:348:in `block (2 levels) in parsing_binding'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:141:in `block (2 levels) in parsing_binding'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:120:in `block (2 levels) in parsing_binding'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.143.0/bin/fastlane:23:in `<top (required)>'
  /Users/vagrant/.rbenv/versions/2.6.5/bin/fastlane:23:in `load'
  /Users/vagrant/.rbenv/versions/2.6.5/bin/fastlane:23:in `<top (required)>'
Fastlane command: (bundle "_2.1.4_" "exec" "fastlane" "x" "x") failed
If you want to send an issue report to fastlane (https://github.com/fastlane/fastlane/issues/new), you can find the output of fastlane env in the following log file:
/Users/vagrant/deploy/fastlane_env.log
Command failed, error: exit status 1
```

**Comment by janpio** [comment]
Did I read correctly from the output snippet that you are running `sync_code_signing`/`match` in a lane and you are getting this error?

Can you log in to the web interface from Apple? Looks like their API is returning errors for you - but if this would be a more widespread outage there would be many more people reporting this here, so I doubt that is what is happening.

**Comment by nancy-gomez** [comment]
Hello! I have seen this issue also on an account we use for CI and my own personal account. I have seen it using fastlane to download profiles or to utilize the spaceship. It happens quite often lately :( But the error is an "Access Denied" in our case. I have a feeling this is due to Apple's API

**Comment by racer1988** [comment]
This happens on my CI: BitRise only starting this week.
So I suppose it's a recent issue, maybe for the network strain due to Corona.

if it happens.. it starts happening for all builds.. so feels like a outage

**Comment by max-ott** [comment]
These kind of errors happen, if there is something not "quite right" with Apple's servers. There are 2-3 different types of errors, which are really hard to catch, so I'm afraid we can't do much here. Usually retrying helps.

**Comment by gruaig** [comment]
Also same for me.

<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Request failed.</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /v1/session. Reason:
<pre>    Request failed.</pre></p>
</body>
</html>
'[0m
INFO [2020-03-20 20:30:59.37]: [32mSuccessfully generated documentation at path '/Users/xcloud/jenkins/workspace/lotto-ui-player_development/automatic-build/fastlane/README.md'[0m

+------+--------------------------------------------------------+-------------+
|                              [32mfastlane summary[0m                               |
+------+--------------------------------------------------------+-------------+
| Step | Action                                                 | Time (in s) |
+------+--------------------------------------------------------+-------------+
| 1    | Verifying fastlane version                             | 0           |
| 2    | default_platform                                       | 0           |
| 3    | cd $FOLDER_PATH/automatic-build ; ./configProcessor.sh | 0           |
| 4    | get_certificates                                       | 4           |
| 💥   | [31mget_provisioning_profile[0m                               | 1           |
+------+--------------------------------------------------------+-------------+

ERROR [2020-03-20 20:30:59.38]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...
Search query: 765: unexpected token at '<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Request failed.</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /v1/session. Reason:
<pre>    Request failed.</pre></p>
</body>
</html>
