### ISSUE TITLE
CircleCI build (in docker) problem with fastlane not having permissions to access the android folders

### ISSUE THREAD

**Issue by springcoil** [fastlane/fastlane#16208]
### New Issue Checklist

- [] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
version - fastlane-2.144.0
### Issue Description
Got a docker installation within circle ci. And can't get fastlane to work within it. 
##### Command executed
fastlane android release --verbose
##### Complete output when running fastlane, including the stack trace and command used
```#!/bin/bash -eo pipefail
fastlane android release  --verbose
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (***********)
[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [⠴] 🚀 [⠦] 🚀 [✔] 🚀 
[18:45:04]: fastlane detected a Gemfile in the current directory
[18:45:04]: However, it seems like you didn't use `bundle exec`
[18:45:04]: To launch fastlane faster, please use
[18:45:04]: 
[18:45:04]: $ bundle exec fastlane android release --verbose
[18:45:04]: 
[18:45:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2020-03-25 18:45:05.35]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/home/circleci/project/fastlane/Appfile'
- json_key_file: 'google-play-key.json'
- package_name: 'com.aflorithmic.withhislight4'
- team_id: '**********'
- itunes_connect_id: '119733192'
- itc_team_name: 'Aflorithmic Labs Ltd'
-------
INFO [2020-03-25 18:45:05.41]: Sending anonymous analytics information
INFO [2020-03-25 18:45:05.41]: Learn more at https://docs.fastlane.tools/#metrics
INFO [2020-03-25 18:45:05.41]: No personal or sensitive data is sent.
INFO [2020-03-25 18:45:05.41]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
INFO [2020-03-25 18:45:05.43]: ------------------------------
INFO [2020-03-25 18:45:05.43]: --- Step: default_platform ---
INFO [2020-03-25 18:45:05.43]: ------------------------------
ERROR [2020-03-25 18:45:05.43]: ------------------------------------------------
ERROR [2020-03-25 18:45:05.43]: Name of the lane 'appstore' is already taken by the action named 'appstore'
ERROR [2020-03-25 18:45:05.43]: ------------------------------------------------
INFO [2020-03-25 18:45:05.43]: Driving the lane 'android release' 🚀
INFO [2020-03-25 18:45:05.44]: ---------------------------------------------------
INFO [2020-03-25 18:45:05.44]: --- Step: Switch to android assemble_build lane ---
INFO [2020-03-25 18:45:05.44]: ---------------------------------------------------
INFO [2020-03-25 18:45:05.44]: Cruising over to lane 'android assemble_build' 🚖
INFO [2020-03-25 18:45:05.44]: -----------------------------
INFO [2020-03-25 18:45:05.44]: --- Step: assembleRelease ---
INFO [2020-03-25 18:45:05.44]: -----------------------------
INFO [2020-03-25 18:45:05.44]: $ /home/circleci/project/android assembleRelease -p . -Pandroid.injected.signing.store.file=key-store.jks -Pandroid.injected.signing.store.password=******************************** -Pandroid.injected.signing.key.alias=**************************************** -Pandroid.injected.signing.key.password=********************************
WARN [2020-03-25 18:45:05.45]: Lane Context:
INFO [2020-03-25 18:45:05.45]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:android, :LANE_NAME=>"android release", :GRADLE_BUILD_TYPE=>"Release"}
ERROR [2020-03-25 18:45:05.45]: Permission denied - /home/circleci/project/android
INFO [2020-03-25 18:45:05.45]: Successfully generated documentation at path '/home/circleci/project/fastlane/README.md'

+------+---------------------------------------+-------------+
|                      fastlane summary                      |
+------+---------------------------------------+-------------+
| Step | Action                                | Time (in s) |
+------+---------------------------------------+-------------+
| 1    | default_platform                      | 0           |
| 2    | Switch to android assemble_build lane | 0           |
| 💥   | assembleRelease                       | 0           |
+------+---------------------------------------+-------------+

ERROR [2020-03-25 18:45:05.45]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Permission denied - /home/circleci/project/android

URL: https://api.github.com/search/issues?q=Permission%20denied%20-%20%2Fhome%2Fcircleci%2Fproject%2Fandroid+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	37: from /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `<main>'
	36: from /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `load'
	35: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
	34: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	33: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	32: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	31: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	30: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	29: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	28: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	27: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	26: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	25: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	24: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	23: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	22: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	21: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	20: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	19: from Fastfile:112:in `block (2 levels) in parsing_binding'
	18: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	17: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	16: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	15: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	14: from Fastfile:100:in `block (2 levels) in parsing_binding'
	13: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	12: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	11: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	10: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 9: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 8: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 7: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 6: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
	 5: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
	 4: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:230:in `sh'
	 3: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
	 2: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/open3.rb:208:in `popen2e'
	 1: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
/home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/open3.rb:213:in `spawn': Permission denied - /home/circleci/project/android (Errno::EACCES)
	37: from /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `<main>'
	36: from /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `load'
	35: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
	34: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	33: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	32: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	31: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	30: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	29: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	28: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	27: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	26: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	25: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	24: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	23: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	22: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	21: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	20: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	19: from Fastfile:112:in `block (2 levels) in parsing_binding'
	18: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	17: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	16: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	15: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	14: from Fastfile:100:in `block (2 levels) in parsing_binding'
	13: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	12: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	11: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	10: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 9: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 8: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 7: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 6: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
	 5: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
	 4: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:230:in `sh'
	 3: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
	 2: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/open3.rb:208:in `popen2e'
	 1: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
/home/circleci/.rubies/ruby-2.6.1/lib/ruby/2.6.0/open3.rb:213:in `spawn': [!] Permission denied - /home/circleci/project/android (Errno::EACCES)

Exited with code exit status 1
CircleCI received exit code 1
```
I've tried three docker containers and various users and each time I run into this. Can anyone help?

**Comment by springcoil** [comment]
Possibly related to https://github.com/fastlane/fastlane/issues/8597

**Comment by springcoil** [comment]
Funnily enough the same issue happens locally on my mac. 
Fastlane env:
```<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.4.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.4 (18E227)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.3_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Installs the certificates and profiles locally"
  lane :certificates do |options|
    if options[:use_temporary_keychain]
      create_temporary_keychain
    end
  
    readonly = (options[:refresh_certificates] ? false : true)
    force_for_new_devices = !readonly
  

  
    match(
      git_branch: "dev",
      app_identifier: "com.aflorithmic.withhislight-testflight",
      team_id: "2WR562YK22",
      type: "development",
      readonly: readonly
    )
  
    match(
      git_branch: "master",
      app_identifier: "com.aflorithmic.withhislight",
      team_id: "2WR562YK22",
      type: "appstore",
      readonly: readonly
    )
  
    if options[:use_temporary_keychain]
      sh "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV["KEYCHAIN_NAME"]} #{ENV["KEYCHAIN_PASSWORD"]}"
    end
  end
  
  private_lane :create_temporary_keychain do
    keychain_name = "temporary_keychain"
    ENV["KEYCHAIN_NAME"] = keychain_name
    ENV["KEYCHAIN_PASSWORD"] = keychain_name
    ENV["MATCH_KEYCHAIN_NAME"] = keychain_name 
    ENV["MATCH_KEYCHAIN_PASSWORD"] = keychain_name
  
    create_keychain(
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
  end


  desc "Submit a new build to iTunes Connect"
  lane :appstore do |options|
  certificates(
      use_temporary_keychain: options[:use_temporary_keychain],
      refresh_certificates: options[:refresh_certificates]
  )

  gym(
      verbose: true,
      workspace: "ios/WithHisLight.xcworkspace",
      configuration: "Release",
      scheme: "Withhislight",
      clean: true,
      include_symbols: true,
      export_method: "app-store"
  )

  testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
  )
  end
end 

platform :android do
  before_all do |lane, options|
    @build_type = "Debug"
    if not options.empty?
      @build_type = options["release"] ? "Release" : "Debug"
    end
  end

  desc "Assemble Build"
  lane :assemble_build do |options|
    properties = {
      "android.injected.signing.store.file" => "key-store.jks",
      "android.injected.signing.store.password" => ENV['EXPO_ANDROID_KEYSTORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['EXPO_ANDROID_KEYSTORE_ALIAS'],
      "android.injected.signing.key.password" => ENV['EXPO_ANDROID_KEY_PASSWORD'],
    } if @build_type == "Release"

    gradle(task: "assemble", build_type: @build_type, properties: properties, gradle_path: 'android')
  end

  
  desc "Assemble Build Application"
  lane :assemble do |options|
    assemble_build options
  end

  desc "Deploy a new version to the Google Play"
  lane :release do
    @build_type = "Release"
    assemble_build
    upload_to_play_store
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "google-play-key.json"
package_name "com.aflorithmic.withhislight4"

team_id "2WR562YK22"
itunes_connect_id "119733192"
itc_team_name "Aflorithmic Labs Ltd"


for_lane :alpha do
    app_identifier "com.aflorithmic.withhislight-testflight"
end

for_lane :production do
    app_identifier "com.aflorithmic.withhislight"
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.144.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.3       |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| tty-spinner               | 0.9.3        |
| tty-cursor                | 0.7.1        |
| tty-screen                | 0.7.1        |
| openssl                   | 2.0.5        |
| json                      | 2.3.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| babosa                    | 1.0.3        |
| fastimage                 | 2.1.7        |
| bundler                   | 2.1.4        |
| unicode-display_width     | 1.7.0        |
| googleauth                | 0.11.0       |
| signet                    | 0.13.0       |
| addressable               | 2.7.0        |
| google-cloud-storage      | 1.25.1       |
| multi_json                | 1.14.1       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| psych                     | 2.2.2        |
| aws-partitions            | 1.287.0      |
</details>


*generated on:* **2020-03-27**
</details>```

**Comment by springcoil** [comment]
@max-ott Do you by any chance know what kind of error this is?
