### ISSUE TITLE
match nuke fails with deleting from S3

### ISSUE THREAD

**Issue by theirix** [fastlane/fastlane#16216]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am running `fastlane match nuke distribution`.
Fastlane deletes certificates from Apple but leaves them in S3 because it fails here.
Access to S3 is read/write and checked by previous runs of `fastlane match appstore`.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
irix@tau ~/projects/REDPROJECT/ios [∓ ci +] % fastlane match nuke distribution
[✔] 🚀
[13:46:44]: fastlane detected a Gemfile in the current directory
[13:46:44]: However, it seems like you didn't use `bundle exec`
[13:46:44]: To launch fastlane faster, please use
[13:46:44]:
[13:46:44]: $ bundle exec fastlane match nuke distribution
[13:46:44]:
[13:46:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:46:46]: Successfully loaded '/Users/irix/projects/REDPROJECT/ios/fastlane/Matchfile' 📄

+----------------------+------------------------------------------+
|           Detected Values from './fastlane/Matchfile'           |
+----------------------+------------------------------------------+
| storage_mode         | s3                                       |
| s3_bucket            | REDBUCKET                                |
| s3_region            | eu-west-1                                |
| s3_access_key        | RED                                      |
| s3_secret_access_key | RED                                      |
| type                 | appstore                                 |
+----------------------+------------------------------------------+

[13:46:50]: 🔓  Successfully decrypted certificates repo

+----------------------------+------------------------------------------+
|                    Summary for match nuke 2.144.0                     |
+----------------------------+------------------------------------------+
| type                       | appstore                                 |
| readonly                   | false                                    |
| generate_apple_certs       | true                                     |
| skip_provisioning_profiles | false                                    |
| username                   | RED                                      |
| team_id                    | RED                                      |
| storage_mode               | s3                                       |
| git_branch                 | master                                   |
| shallow_clone              | false                                    |
| clone_branch_directly      | false                                    |
| s3_region                  | eu-west-1                                |
| s3_access_key              | RED                                      |
| s3_secret_access_key       | RED                                      |
| s3_bucket                  | REDBUCKET                                |
| keychain_name              | login.keychain                           |
| force                      | false                                    |
| force_for_new_devices      | false                                    |
| skip_confirmation          | false                                    |
| skip_docs                  | false                                    |
| platform                   | ios                                      |
| verbose                    | false                                    |
+----------------------------+------------------------------------------+

[13:46:50]: Fetching certificates and profiles...

+--------------+------------+-------------------+------------+
|         Certificates that are going to be revoked          |
+--------------+------------+-------------------+------------+
| Name         | ID         | Type              | Expires    |
+--------------+------------+-------------------+------------+
| Distribution | RED_______ | AppleDistribution | 2021-03-27 |
| Distribution | RED_______ | AppleDistribution | 2021-03-27 |
| Distribution | RED_______ | AppleDistribution | 2021-03-27 |
| Distribution | RED_______ | AppleDistribution | 2021-03-27 |
+--------------+------------+-------------------+------------+

+---------------------+------------+--------+------------------+------------+
|            Provisioning Profiles that are going to be revoked             |
+---------------------+------------+--------+------------------+------------+
| Name                | ID         | Status | Type             | Expires    |
+---------------------+------------+--------+------------------+------------+
| match AppStore      | JL3DTBA4D8 | Active | iOS Distribution | 2021-03-27 |
| RED                 |            |        |                  |            |
+---------------------+------------+--------+------------------+------------+

+-----------------------+----------------------------------------------+
|                  Files that are going to be deleted                  |
| S3 Bucket [REDBUCKET] on region eu-west-1                            |
+-----------------------+----------------------------------------------+
| Type                  | File Name                                    |
+-----------------------+----------------------------------------------+
| distribution cert     | XV3J38D5RH.cer                               |
| distribution cert     | J395LL23Y5.cer                               |
| distribution cert     | XV3J38D5RH.p12                               |
| distribution cert     | J395LL23Y5.p12                               |
| appstore profile      | AppStore_RED.mobileprovision                 |
+-----------------------+----------------------------------------------+

[13:47:13]: ---
[13:47:13]: Are you sure you want to completely delete and revoke all the
[13:47:13]: certificates and provisioning profiles listed above? (y/n)
[13:47:13]: Warning: By nuking distribution, both App Store and Ad Hoc profiles will be deleted
[13:47:13]: Warning: The :app_identifier value will be ignored - this will delete all profiles for all your apps!
[13:47:13]: ---
[13:47:13]: Do you really want to nuke everything listed above? (y/n)
y
[13:47:35]: -------------------------------------------
[13:47:35]: --- Deleting 1 provisioning profiles... ---
[13:47:35]: -------------------------------------------
[13:47:35]: Deleting profile 'match AppStore RED' (JL3DTBA4D8)...
[13:47:36]: Successfully deleted profile
[13:47:36]: ----------------------------------
[13:47:36]: --- Revoking 4 certificates... ---
[13:47:36]: ----------------------------------
[13:47:36]: Revoking certificate 'Distribution' (XV3J38D5RH)...
[13:47:38]: Successfully deleted certificate
[13:47:38]: Revoking certificate 'Distribution' (J395LL23Y5)...
[13:47:39]: Successfully deleted certificate
[13:47:39]: Revoking certificate 'Distribution' (XV3J38D5RH)...
[13:47:39]: {"responseId"=>"a9be006a-af2e-4e39-8dbe-c5b155651230", "resultCode"=>7470, "resultString"=>"This certificate cannot be revoked because it is not in an \"issued\" state.", "userString"=>"This certificate cannot be revoked because it is not in an \"issued\" state.", "creationTimestamp"=>"2020-03-27T10:47:39Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/revokeCertificate.action", "httpCode"=>200}
[13:47:39]: Successfully deleted certificate
[13:47:39]: Revoking certificate 'Distribution' (J395LL23Y5)...
[13:47:39]: {"responseId"=>"f954c446-6f3e-4775-86ed-c1d0b3de15b0", "resultCode"=>7470, "resultString"=>"This certificate cannot be revoked because it is not in an \"issued\" state.", "userString"=>"This certificate cannot be revoked because it is not in an \"issued\" state.", "creationTimestamp"=>"2020-03-27T10:47:39Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/revokeCertificate.action", "httpCode"=>200}
[13:47:39]: Successfully deleted certificate
[13:47:39]: --------------------------------------------
[13:47:39]: --- Deleting 5 files from the storage... ---
[13:47:39]: --------------------------------------------
[13:47:39]: Deleting file 'XV3J38D5RH.cer'...
[13:47:39]: Successfully deleted file
[13:47:39]: Deleting file 'J395LL23Y5.cer'...
[13:47:39]: Successfully deleted file
[13:47:39]: Deleting file 'XV3J38D5RH.p12'...
[13:47:39]: Successfully deleted file
[13:47:39]: Deleting file 'J395LL23Y5.p12'...
[13:47:39]: Successfully deleted file
[13:47:39]: Deleting file 'AppStore_RED.mobileprovision'...
[13:47:40]: Successfully deleted file
[13:47:40]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	20: from /Users/irix/.rbenv/versions/2.5.5/bin/fastlane:23:in `<main>'
	19: from /Users/irix/.rbenv/versions/2.5.5/bin/fastlane:23:in `load'
	18: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
	17: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	16: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/commands_generator.rb:25:in `start'
	15: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/commands_generator.rb:186:in `run'
	14: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	13: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	12: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	11: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	10: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 9: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/commands_generator.rb:179:in `block (3 levels) in run'
	 8: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/nuke.rb:78:in `run'
	 7: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/nuke.rb:240:in `nuke_it_now!'
	 6: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/storage/interface.rb:59:in `save_changes!'
	 5: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/storage/interface.rb:59:in `chdir'
	 4: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/storage/interface.rb:78:in `block in save_changes!'
	 3: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/storage/s3_storage.rb:132:in `delete_files'
	 2: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/storage/s3_storage.rb:132:in `each'
	 1: from /Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/match/lib/match/storage/s3_storage.rb:133:in `block in delete_files'
/Users/irix/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:44:in `delete_file': [!] undefined local variable or method `bucket_name' for #<FastlaneCore::Helper::S3ClientHelper:0x00007f8dc357c9b8> (NameError)
Did you mean?  bucket
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.5.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.25.1                          |
| Installation Source         | ~/.rbenv/versions/2.5.5/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G3020)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.5/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Prepare beta release"
  lane :beta do
    match(type: "appstore")
    build_app(workspace: "RED.xcworkspace", scheme: "RED")
  end

  desc "Push a new release build to the App Store"
  lane :release do
    match(type: "appstore")
    increment_build_number(xcodeproj: "RED.xcodeproj")
    build_app(workspace: "RED.xcworkspace", scheme: "RED")
    #upload_to_app_store(skip_metadata: true, skip_screenshots: true, skip_binary_upload: true)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("RED") # The bundle identifier of your app
apple_id("RED") # Your Apple email address

itc_team_id("RED") # App Store Connect Team ID
team_id("RED") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.144.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.13.2       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.288.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| json                      | 2.2.0        |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| io-console                | 0.4.6        |
| zlib                      | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.3       |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-03-27**
</details>
</pre>
</details>

**Comment by theirix** [comment]
Thanks! The fix helped at least one person so I think it should work. I will check it later (cannot drop certificates right now).
