### ISSUE TITLE
match: No matching provisioning profiles found  Question

### ISSUE THREAD

**Issue by l819183457** [fastlane/fastlane#16269]
I created a provisioning using match and kept reporting No matching provisioning profiles found for 'AdHoc_com.epay.LPAutoPackage'
I created the encrypted file name, which is AdHoc_com.epay.LPAutoPackage, and uses penssl encryption

**Comment by l819183457** [comment]
INFO [2020-04-07 13:33:48.50]: Cloning remote git repo...
INFO [2020-04-07 13:33:48.50]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2020-04-07 13:33:48.50]: $ git clone git@github.5upay.com:liangziqiang/certificates.git /var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-13652-1f1js9o
INFO [2020-04-07 13:33:48.52]: ▸ Cloning into '/var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-13652-1f1js9o'...
INFO [2020-04-07 13:33:51.59]: ▸ ssh: connect to host github.5upay.com port 22: Connection refused
INFO [2020-04-07 13:33:51.59]: ▸ fatal: Could not read from remote repository.
INFO [2020-04-07 13:33:51.59]: ▸ Please make sure you have the correct access rights
INFO [2020-04-07 13:33:51.59]: ▸ and the repository exists.
Cloning into '/var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-13652-1f1js9o'...
ssh: connect to host github.5upay.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR [2020-04-07 13:33:51.60]: Exit status: 128
ERROR [2020-04-07 13:33:51.60]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
ERROR [2020-04-07 13:33:51.60]: Run the following command manually to make sure you're properly authenticated:
INFO [2020-04-07 13:33:51.60]: $ git clone git@github.5upay.com:liangziqiang/certificates.git /var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-13652-1f1js9o
WARN [2020-04-07 13:33:51.60]: Lane Context:
INFO [2020-04-07 13:33:51.60]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios development_build"}
ERROR [2020-04-07 13:33:51.60]: Error cloning certificates git repo, please make sure you have access to the repository - see instructions above
INFO [2020-04-07 13:33:51.60]: Successfully generated documentation at path '/Users/gongping/Desktop/a_lq/serverspace/server/iOS/LPAutoPackage/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | match                      | 3           |
+------+----------------------------+-------------+

ERROR [2020-04-07 13:33:51.60]: fastlane finished with errors

#######################################################################
# fastlane 2.145.0 is available. You are on 2.144.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

ERROR [2020-04-07 13:33:56.55]: RubyGems is not listed as your Gem source
ERROR [2020-04-07 13:33:56.55]: You can run `gem sources` to see all your sources
ERROR [2020-04-07 13:33:56.55]: Please run the following command to fix this:
INFO [2020-04-07 13:33:56.55]: $ gem sources --add https://rubygems.org
Traceback (most recent call last):
	33: from /usr/local/bin/fastlane:23:in `<main>'
	32: from /usr/local/bin/fastlane:23:in `load'
	31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
	30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	27: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	15: from Fastfile:115:in `block (2 levels) in parsing_binding'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/runner.rb:58:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/storage/git_storage.rb:95:in `download'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/helper.rb:322:in `with_env_values'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/storage/git_storage.rb:96:in `block in download'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/command_executor.rb:91:in `execute'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Exit status: 128 (FastlaneCore::Interface::FastlaneError)
	31: from /usr/local/bin/fastlane:23:in `<main>'
	30: from /usr/local/bin/fastlane:23:in `load'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	22: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	13: from Fastfile:115:in `block (2 levels) in parsing_binding'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/runner.rb:58:in `run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/storage/git_storage.rb:93:in `download'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/storage/git_storage.rb:107:in `rescue in download'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Error cloning certificates git repo, please make sure you have access to the repository - see instructions above (FastlaneCore::Interface::FastlaneError)

**Comment by l819183457** [comment]
INFO [2020-04-07 13:33:48.50]: Cloning remote git repo...
INFO [2020-04-07 13:33:48.50]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2020-04-07 13:33:48.50]: $ git clone git@github.xxx:liangziqiang/certificates.git /var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-13652-1f1js9o
INFO [2020-04-07 13:33:48.52]: ▸ Cloning into '/var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-13652-1f1js9o'...
INFO [2020-04-07 13:33:51.59]: ▸ ssh: connect to host github.xxx port 22: Connection refused
INFO [2020-04-07 13:33:51.59]: ▸ fatal: Could not read from remote repository.
INFO [2020-04-07 13:33:51.59]: ▸ Please make sure you have the correct access rights
INFO [2020-04-07 13:33:51.59]: ▸ and the repository exists.
Cloning into '/var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-13652-1f1js9o'...
ssh: connect to host github.xxxx port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR [2020-04-07 13:33:51.60]: Exit status: 128
ERROR [2020-04-07 13:33:51.60]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
ERROR [2020-04-07 13:33:51.60]: Run the following command manually to make sure you're properly authenticated:
INFO [2020-04-07 13:33:51.60]: $ git clone git@github.xxx:liangziqiang/certificates.git /var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-13652-1f1js9o
WARN [2020-04-07 13:33:51.60]: Lane Context:
INFO [2020-04-07 13:33:51.60]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios development_build"}
ERROR [2020-04-07 13:33:51.60]: Error cloning certificates git repo, please make sure you have access to the repository - see instructions above
INFO [2020-04-07 13:33:51.60]: Successfully generated documentation at path '/Users/gongping/Desktop/a_lq/serverspace/server/iOS/LPAutoPackage/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | match                      | 3           |
+------+----------------------------+-------------+

ERROR [2020-04-07 13:33:51.60]: fastlane finished with errors

#######################################################################
# fastlane 2.145.0 is available. You are on 2.144.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

ERROR [2020-04-07 13:33:56.55]: RubyGems is not listed as your Gem source
ERROR [2020-04-07 13:33:56.55]: You can run `gem sources` to see all your sources
ERROR [2020-04-07 13:33:56.55]: Please run the following command to fix this:
INFO [2020-04-07 13:33:56.55]: $ gem sources --add https://rubygems.org
Traceback (most recent call last):
	33: from /usr/local/bin/fastlane:23:in `<main>'
	32: from /usr/local/bin/fastlane:23:in `load'
	31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
	30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	27: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	15: from Fastfile:115:in `block (2 levels) in parsing_binding'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/runner.rb:58:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/storage/git_storage.rb:95:in `download'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/helper.rb:322:in `with_env_values'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/storage/git_storage.rb:96:in `block in download'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/command_executor.rb:91:in `execute'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Exit status: 128 (FastlaneCore::Interface::FastlaneError)
	31: from /usr/local/bin/fastlane:23:in `<main>'
	30: from /usr/local/bin/fastlane:23:in `load'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	22: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	13: from Fastfile:115:in `block (2 levels) in parsing_binding'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/runner.rb:58:in `run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/storage/git_storage.rb:93:in `download'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/match/lib/match/storage/git_storage.rb:107:in `rescue in download'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Error cloning certificates git repo, please make sure you have access to the repository - see instructions above (FastlaneCore::Interface::FastlaneError)

**Comment by l819183457** [comment]
Wait a moment, I will relaunch the screenshot

**Comment by l819183457** [comment]
<img width="500" alt="WeChat2d682dfc77752ebc7423efb734422dfe" src="https://user-images.githubusercontent.com/16470589/78634427-80f38980-78d6-11ea-94d2-45bb4eace54a.png">

**Comment by l819183457** [comment]
<img width="500" alt="WeChat2d682dfc77752ebc7423efb734422dfe" src="https://user-images.githubusercontent.com/16470589/78634470-9ff21b80-78d6-11ea-9993-ffe1ef512c37.png">

**Comment by l819183457** [comment]
INFO [2020-04-07 13:47:22.34]: ▸ Cloning into '/var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-14886-1y87zth'...
INFO [2020-04-07 13:47:23.09]: ▸ remote: Enumerating objects: 120, done.
INFO [2020-04-07 13:47:23.18]: ▸ remote: Counting objects: 100% (120/120), done.
INFO [2020-04-07 13:47:23.25]: ▸ remote: Compressing objects: 100% (81/81), done.
INFO [2020-04-07 13:47:23.65]: ▸ remote: Total 120 (delta 26), reused 86 (delta 15)
INFO [2020-04-07 13:47:23.73]: ▸ Receiving objects: 100% (120/120), 130.51 KiB | 272.00 KiB/s, done.
INFO [2020-04-07 13:47:23.74]: ▸ Resolving deltas: 100% (26/26), done.
INFO [2020-04-07 13:47:23.82]: 🔓  Decrypted 'cert_id.cer'
INFO [2020-04-07 13:47:23.85]: 🔓  Decrypted 'cert_id.p12'
INFO [2020-04-07 13:47:23.88]: 🔓  Decrypted 'AdHoc_com.epay.LPAutoPackage.mobileprovision'
INFO [2020-04-07 13:47:23.88]: 🔓  Successfully decrypted certificates repo
DEBUG [2020-04-07 13:47:23.88]: Your certificate 'cert_id.cer' is valid
INFO [2020-04-07 13:47:23.88]: Installing certificate...
INFO [2020-04-07 13:47:23.88]: $ security list-keychains -d user
INFO [2020-04-07 13:47:23.89]: ▸     "/Users/gongping/Library/Keychains/login.keychain-db"
INFO [2020-04-07 13:47:23.89]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/gongping/Library/Keychains/login.keychain-db
INFO [2020-04-07 13:47:23.92]: ▸ keychain: "/Users/gongping/Library/Keychains/login.keychain-db"
INFO [2020-04-07 13:47:23.92]: ▸ version: 512
INFO [2020-04-07 13:47:23.92]: ▸ class: 0x80001000 
INFO [2020-04-07 13:47:23.92]: ▸ attributes:
INFO [2020-04-07 13:47:23.92]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2020-04-07 13:47:23.92]: ▸     "cenc"<uint32>=0x00000003 
INFO [2020-04-07 13:47:23.92]: ▸     "ctyp"<uint32>=0x00000001 
INFO [2020-04-07 13:47:23.92]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2020-04-07 13:47:23.92]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2020-04-07 13:47:23.92]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2020-04-07 13:47:23.92]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2020-04-07 13:47:23.92]: ▸     "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"
INFO [2020-04-07 13:47:23.92]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
DEBUG [2020-04-07 13:47:24.08]: Certificate 'cert_id.cer' is already installed on this machine
INFO [2020-04-07 13:47:24.08]: $ security import /var/folders/bw/3lzmmzf971s4z2d7y8pwk9480000gn/T/d20200407-14886-1y87zth/certs/distribution/cert_id.p12 -k '/Users/gongping/Library/Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
ERROR [2020-04-07 13:47:24.12]: security: SecKeychainItemImport: Unknown format in import.

+-------------------+--------------------------------------------------------------------------------+
|                                       Installed Certificate                                        |
+-------------------+--------------------------------------------------------------------------------+
| User ID           | BSNMQ3E4FW                                                                     |
| Common Name       | Apple Distribution: Beijing Yihuijin Information Service Co.,Ltd. (BSNMQ3E4FW) |
| Organisation Unit | BSNMQ3E4FW                                                                     |
| Organisation      | Beijing Yihuijin Information Service Co.,Ltd.                                  |
| Country           | CN                                                                             |
| Start Datetime    | 2020-04-01 06:34:20 UTC                                                        |
| End Datetime      | 2021-04-01 06:34:20 UTC                                                        |
+-------------------+--------------------------------------------------------------------------------+

ERROR [2020-04-07 13:47:24.12]: No matching provisioning profiles found for 'AdHoc_com.epay.LPAutoPackage'
ERROR [2020-04-07 13:47:24.12]: A new one cannot be created because you enabled `readonly`
ERROR [2020-04-07 13:47:24.12]: Provisioning profiles in your repo for type `adhoc`:
ERROR [2020-04-07 13:47:24.12]: - 'AdHoc_com.epay.LPAutoPackage'
ERROR [2020-04-07 13:47:24.12]: - 'AdHoc_com.epay.LPAutoPackage.mobileprovision'
ERROR [2020-04-07 13:47:24.12]: If you are certain that a profile should exist, double-check the recent changes to your match repository
WARN [2020-04-07 13:47:24.13]: Lane Context:
INFO [2020-04-07 13:47:24.13]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios development_build"}
ERROR [2020-04-07 13:47:24.13]: No matching provisioning profiles found and can not create a new one because you enabled `readonly`. Check the output above for more information.
INFO [2020-04-07 13:47:24.13]: Successfully generated documentation at path '/Users/gongping/Desktop/a_lq/serverspace/server/iOS/LPAutoPackage/fastlane/README.md'
