### ISSUE TITLE
Google Api Error: forbidden: The caller does not have permission - The caller does not have permission

### ISSUE THREAD

**Issue by kikoso** [fastlane/fastlane#16283]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
- App has been uploaded to the Play Store on the Internal and Alpha Track.
- I can see the App in Google Play.
- Executing `fastlane run validate_play_store_json_key json_key:app/file.json` works
Executing `fastlane supply init --track alpha --verbose` drops an error.

##### Command executed
`fastlane supply init --track alpha --verbose`

##### Complete output when running fastlane, including the stack trace and command used
<details>
`[✔] 🚀 
Successfully loaded Appfile at path '/Users/enriquelopezmanas/Documents/project-folder/fastlane/Appfile'
- json_key_file: 'app/file.json'
- package_name: 'my.package'
-------

+-------------------------+-------------------------------------+
|                  Summary for supply 2.145.0                   |
+-------------------------+-------------------------------------+
| package_name            | my.package |
| release_status          | completed                           |
| track                   | production                          |
| json_key                | app/file.json                       |
| skip_upload_apk         | false                               |
| skip_upload_aab         | false                               |
| skip_upload_metadata    | false                               |
| skip_upload_changelogs  | false                               |
| skip_upload_images      | false                               |
| skip_upload_screenshots | false                               |
| validate_only           | false                               |
| check_superseded_tracks | false                               |
| timeout                 | 300                                 |
| deactivate_on_promote   | true                                |
+-------------------------+-------------------------------------+

DEBUG [2020-04-09 08:04:03.38]: Fetching a new access token from Google...
Traceback (most recent call last):
	30: from /Users/enriquelopezmanas/gems/bin/fastlane:23:in `<main>'
	29: from /Users/enriquelopezmanas/gems/bin/fastlane:23:in `load'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/bin/fastlane:23:in `<top (required)>'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/commands_generator.rb:12:in `start'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/commands_generator.rb:59:in `run'
	24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	22: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/uploader.rb:7:in `perform_upload'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/client.rb:138:in `begin_edit'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/client.rb:80:in `call_google_api'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/client.rb:138:in `block in begin_edit'
	14: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/generated/google/apis/androidpublisher_v3/service.rb:200:in `insert_edit'
	13: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	12: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:102:in `execute'
	11: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	10: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 9: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 8: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:110:in `block in execute'
	 7: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	 6: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 5: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 4: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
	 3: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:310:in `execute_once'
	 2: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:193:in `process_response'
	 1: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/api_command.rb:117:in `check_status'
/Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:228:in `check_status': forbidden: The caller does not have permission (Google::Apis::ClientError)
	17: from /Users/enriquelopezmanas/gems/bin/fastlane:23:in `<main>'
	16: from /Users/enriquelopezmanas/gems/bin/fastlane:23:in `load'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/bin/fastlane:23:in `<top (required)>'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/commands_generator.rb:12:in `start'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/commands_generator.rb:59:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/uploader.rb:7:in `perform_upload'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/client.rb:138:in `begin_edit'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/client.rb:79:in `call_google_api'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/supply/lib/supply/client.rb:94:in `rescue in call_google_api'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.145.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: forbidden: The caller does not have permission - The caller does not have permission (FastlaneCore::Interface::FastlaneError)`
</details>

### Environment

<details>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.1 (Apple Git-126)                             |
| Installation Source         | ~/gems/bin/fastlane                                            |
| Host                        | Mac OS X 10.15.4 (19E266)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.53.1"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "app/file.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "my.package" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.15.0       |
| unf_ext                   | 0.0.7.7      |
| json                      | 2.3.0        |
| bundler                   | 2.1.4        |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.1        |
| aws-partitions            | 1.296.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-04-09**
</details>
</details>

**Comment by kikoso** [comment]
Problem was with user not having permissions.
