### ISSUE TITLE
Deliver for iOS and macOS at the same time (Universal Purchase)

### ISSUE THREAD

**Issue by lighthouse16** [fastlane/fastlane#16330]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Deliver

#### Question Description
I have an app in the App Store for macOS and iOS. It is one product, not two separate products in App Store Connect. Apple calls it [Universal Purchase](https://developer.apple.com/support/universal-purchase/)

The meta data gets uploaded for the App information part and the iOS app. But not for the macOS app.

When the upload for screenshots start it stops and crashes:

```
[20:38:51]: Uploading 25 screenshots for language ar-SA
[20:38:51]: Uploading './fastlane/screenshots/ar-SA/Mac 1_framed.png'...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Snapshot generating screenshots at 50% in Xcode 9.0.1
    https://github.com/fastlane/fastlane/issues/10645 [closed] 4 💬
    19 Dec 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	22: from /usr/local/Cellar/fastlane/2.145.0/libexec/bin/fastlane:23:in `<main>'
	21: from /usr/local/Cellar/fastlane/2.145.0/libexec/bin/fastlane:23:in `load'
	20: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/bin/fastlane:23:in `<top (required)>'
	19: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	18: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	17: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	16: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	15: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	14: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	13: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	12: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	11: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	10: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/runner.rb:38:in `run'
	 9: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/runner.rb:121:in `upload_metadata'
	 8: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/upload_screenshots.rb:49:in `upload'
	 7: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/upload_screenshots.rb:49:in `each'
	 6: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/upload_screenshots.rb:51:in `block in upload'
	 5: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/upload_screenshots.rb:51:in `each'
	 4: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/deliver/lib/deliver/upload_screenshots.rb:64:in `block (2 levels) in upload'
	 3: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/app_version.rb:513:in `upload_screenshot!'
	 2: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/app_version.rb:746:in `screenshots_data_for_language_and_device'
	 1: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/app_version.rb:753:in `container_data_for_language_and_device'
/usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/app_version.rb:766:in `rescue in container_data_for_language_and_device': [!] App Store Connect error: Couldn't find device family for desktop (RuntimeError)
```

I tried multiple names for the Mac screenshots. I run the latest version of fastlane. I check the sizes of the screenshots and they are good.

What can I do?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.4                                                 |
| Ruby                        | 2.5.8                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.26.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.145.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.4 (19E287)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.8/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.4.1                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | nl_NL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

opt_out_usage(true)
default_platform(:ios)

before_all do
  update_fastlane
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see: https://docs.fastlane.tools/advanced/#appfile

```
</details>

<details><summary>`./fastlane/DeliverFile`</summary>

```ruby
skip_binary_upload(true)
force(true)
overwrite_screenshots(true)
run_precheck_before_submit(false)
app_identifier("com.company.productname")
metadata_path("./fastlane/metadata/")
screenshots_path("./fastlane/screenshots/")

</details>
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.12.0       |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.296.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
</details>


*generated on:* **2020-04-17**
</details>

**Comment by l1ghthouse** [comment]
Not yet solved

**Comment by l1ghthouse** [comment]
The issue still exists with the current fastlane version 2.150

**Comment by l1ghthouse** [comment]
The issue still exists with the current fastlane version 2.156.1

**Comment by l1ghthouse** [comment]
The issue still exists with the current fastlane version 2.160.0

**Comment by lighthouse16** [comment]
For everyone that is looking for a solution... just make two lanes.. one for iOS and one for macOS. Yes you will upload app info twice... you can share metadata :)...

I don't think this issue will ever be fixed...
