### ISSUE TITLE
Error match s3 when try to run command

### ISSUE THREAD

**Issue by rafagan** [fastlane/fastlane#16338]
I trying to run this without success:

```
lane :run_match do
  match(s3_region: 'us-east-1', s3_bucket: 'kolb-apps-ios-match')
end
```

The following error occurs. What's going on? How to use s3 integration?

```
Traceback (most recent call last):
	31: from /usr/local/Cellar/fastlane/2.145.0/libexec/bin/fastlane:23:in `<main>'
	30: from /usr/local/Cellar/fastlane/2.145.0/libexec/bin/fastlane:23:in `load'
	29: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/bin/fastlane:23:in `<top (required)>'
	28: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	27: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	26: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	25: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	24: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	23: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	22: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	21: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	20: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	19: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	18: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	17: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	16: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	15: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	14: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	13: from Fastfile:29:in `block (2 levels) in parsing_binding'
	12: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	11: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	10: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 9: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 8: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 7: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 6: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 5: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
	 4: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/match/lib/match/runner.rb:58:in `run'
	 3: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/match/lib/match/storage/s3_storage.rb:91:in `download'
	 2: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/fastlane-2.145.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:50:in `find_bucket!'
	 1: from /usr/local/Cellar/fastlane/2.145.0/libexec/gems/aws-sdk-s3-1.61.2/lib/aws-sdk-s3/bucket.rb:74:in `exists?'
/usr/local/Cellar/fastlane/2.145.0/libexec/gems/aws-sdk-s3-1.61.2/lib/aws-sdk-s3/bucket.rb:79:in `rescue in exists?': [!]  (Aws::S3::Errors::BadRequest)

**Comment by youngern** [comment]
Have you included the `s3_access_key` and `s3_secret_access_key` variables somewhere, either in `Matchfile` or through the cli?
