### ISSUE TITLE
iTMSTransporter “Error accessing file” after upgrade to Catalina

### ISSUE THREAD

**Issue by reubits** [fastlane/fastlane#16368]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After upgrading macOS to Catalina I cannot use `pilot` to upload builds to the app store anymore. Looks like it is because the HOME directory path changed (from `/Local/Users/jenkins` to `/Users/jenkins`) and transporter still has a reference to the old directory.

```
Resolver: Install error - org.apache.httpcomponents.httpcore Exception's name: java.io.IOException, Exception's message: Error accessing file:/Local/Users/jenkins/Library/Caches/com.apple.amp.itmstransporter/obr/2.0.0/org.apache.httpcomponents.httpcore-4.4.11.jar
ERROR [2020-04-23 13:32:09.94]: [Transporter Error Output]: could not find the service with interface (com.apple.transporter.osgi.TransporterService)
```

##### Command executed

```
fastlane pilot upload -i MyApp.ipa -s true -z true --verbose
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
fastlane pilot upload -i MyApp.ipa -s true -z true --verbose
[✔] 🚀
[13:32:03]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/jenkins/workspace/iOS/_____/fastlane/Appfile'
- app_identifier: '_____'
- apple_id: '_____'
- team_id: '_____'
- itc_team_id: '_____'
-------
INFO [2020-04-23 13:32:04.15]: Login to App Store Connect (_____)
Reading keychain entry, because either user or password were empty
Loading session from '/Users/jenkins/.fastlane/spaceship/_____/cookie'
Looking for App Store Connect Team with ID _____
INFO [2020-04-23 13:32:05.05]: Login successful
DEBUG [2020-04-23 13:32:05.05]: App identifier (_____)
INFO [2020-04-23 13:32:06.18]: Ready to upload new build to TestFlight (App: _____)...
DEBUG [2020-04-23 13:32:06.18]: App Platform (ios)
INFO [2020-04-23 13:32:07.17]: Wrote XML data to '/var/folders/9x/v3j3pwzs14z_lfxj40n_tmsw000034/T/d20200423-35508-1onk1n2/938467045.itmsp'
INFO [2020-04-23 13:32:07.22]: Going to upload updated app to App Store Connect
INFO [2020-04-23 13:32:07.22]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2020-04-23 13:32:07.29]: /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/lib/itmstransporter-launcher.jar -m upload -u _____ -p YourPassword -f /var/folders/9x/v3j3pwzs14z_lfxj40n_tmsw000034/T/d20200423-35508-1onk1n2/938467045.itmsp -t DAV,Signiant -k 100000 2>&1
DEBUG [2020-04-23 13:32:09.63]: [Transporter]: INFO: Configuring logging...
DEBUG [2020-04-23 13:32:09.64]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2020-04-23 13:32:09.64]: [Transporter]: INFO: Transporter is searching for new software components.
DEBUG [2020-04-23 13:32:09.64]: [Transporter]: INFO: INFO: using cached repository.xml file.
DEBUG [2020-04-23 13:32:09.78]: [Transporter]: INFO: Update check complete.
ERROR [2020-04-23 13:32:09.94]: [Transporter Error Output]: Resolver: Install error - org.apache.httpcomponents.httpcore Exception's name: java.io.IOException, Exception's message: Error accessing file:/Local/Users/jenkins/Library/Caches/com.apple.amp.itmstransporter/obr/2.0.0/org.apache.httpcomponents.httpcore-4.4.11.jar
ERROR [2020-04-23 13:32:09.94]: [Transporter Error Output]: could not find the service with interface (com.apple.transporter.osgi.TransporterService)
WARN [2020-04-23 13:32:10.00]: [iTMSTransporter] [2020-04-23 13:32:09 EDT] <main>  INFO: Configuring logging...

WARN [2020-04-23 13:32:10.00]: [iTMSTransporter] [2020-04-23 13:32:09 EDT] <main>  INFO: Logging level set to eXtreme

WARN [2020-04-23 13:32:10.00]: [iTMSTransporter] [2020-04-23 13:32:09 EDT] <main>  INFO: Transporter is searching for new software components.

WARN [2020-04-23 13:32:10.00]: [iTMSTransporter] [2020-04-23 13:32:09 EDT] <main>  INFO: INFO: using cached repository.xml file.

WARN [2020-04-23 13:32:10.00]: [iTMSTransporter] [2020-04-23 13:32:09 EDT] <main>  INFO: Update check complete.

WARN [2020-04-23 13:32:10.00]: [iTMSTransporter] [2020-04-23 13:32:09 EDT] <Equinox Log Thread - Equinox Container: 8bb65b6e-fec1-4f6a-a767-104b8a5dfc93> ERROR: Resolver: Install error - org.apache.httpcomponents.httpcore Exception's name: java.io.IOException, Exception's message: Error accessing file:/Local/Users/jenkins/Library/Caches/com.apple.amp.itmstransporter/obr/2.0.0/org.apache.httpcomponents.httpcore-4.4.11.jar

WARN [2020-04-23 13:32:10.00]: [iTMSTransporter] [2020-04-23 13:32:09 EDT] <main> ERROR: could not find the service with interface (com.apple.transporter.osgi.TransporterService)

INFO [2020-04-23 13:32:10.00]: iTunes Transporter output above ^
ERROR [2020-04-23 13:32:10.00]: Resolver: Install error - org.apache.httpcomponents.httpcore Exception's name: java.io.IOException, Exception's message: Error accessing file:/Local/Users/jenkins/Library/Caches/com.apple.amp.itmstransporter/obr/2.0.0/org.apache.httpcomponents.httpcore-4.4.11.jar
could not find the service with interface (com.apple.transporter.osgi.TransporterService)
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

#######################################################################
# fastlane 2.146.1 is available. You are on 2.146.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.146.1Improvements
* [action] fix update_code_signing_settings for unknown keys (#16357) via Josh Holtz

Please update using `sudo gem install fastlane`
Traceback (most recent call last):
	14: from /usr/local/Cellar/fastlane/2.146.0/libexec/bin/fastlane:23:in `<main>'
	13: from /usr/local/Cellar/fastlane/2.146.0/libexec/bin/fastlane:23:in `load'
	12: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/fastlane-2.146.0/bin/fastlane:23:in `<top (required)>'
	11: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/fastlane-2.146.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/fastlane-2.146.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	 9: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/fastlane-2.146.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	 8: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/fastlane-2.146.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/fastlane-2.146.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	 2: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/fastlane-2.146.0/pilot/lib/pilot/build_manager.rb:37:in `upload'
	 1: from /usr/local/Cellar/fastlane/2.146.0/libexec/gems/fastlane-2.146.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.146.0/libexec/gems/fastlane-2.146.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Error uploading ipa file, for more information see above (FastlaneCore::Interface::FastlaneError)
 </pre>
</details>

### Environment

<details>
  <pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.4                                                 |
| Ruby                        | 2.5.8                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.2 (Apple Git-127)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.146.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.4 (19E287)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.8/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.4.1                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.61.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "SANDBOX/QA BUILD"
  lane :sandbox do
    sigh
    gym(
      workspace: "________________",
      scheme: "________________",
      export_method: "ad-hoc",
      silent: true)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "________________") # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    gym(scheme: "________________) # Build your app - more options available
    deliver(force: true)
  end

  lane :refresh_dsyms do |options|
    download_dsyms(version:options[:version])  # Download dSYM files from iTC
    upload_symbols_to_crashlytics(dsym_worker_threads: 5, gsp_path: "________________")  # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "_______________" # The bundle identifier of your app
apple_id "________________" # Your Apple email address

team_id "________________" # Developer Portal Team ID
itc_team_id "________________" # Consumer App iTunes team


```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.146.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.300.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.2        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.62.0       |
</details>

*generated on:* **2020-04-23**
</details>

 </pre>
</details>

**Comment by reubits** [comment]
I was able to solve this by deleting the following pesky file which had the invalid directory reference:

`./System/Volumes/Data/Users/jenkins/Library/Caches/com.apple.amp.itmstransporter/obr/2.0.0/repository.xml`

I noticed `INFO: using cached repository.xml file` so I searched for that file.
