### ISSUE TITLE
Updating a staged rollout percentage while retaining a bundle in Google Play Console

### ISSUE THREAD

**Issue by bmcadams** [fastlane/fastlane#16362]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi,

I am using fastlane supply to update the rollout percentage of my release to Google Play Console. I ran into an interesting scenario that I believe requires a fix. 

In this scenario I have two bundles assigned to a track
- Bundle 1 - Rolled out 5%, version code 18400202
- Bundle 2 - Rolled out 100%, version code 17900185, Retained

My goal is to update Bundle 1's rollout percentage to 100% while retaining Bundle 2. To do so, I used the following fastlane command and I ran into the proceeding error

```bash
12:18:26 + /usr/local/bin/fastlane supply --json=<KEY> --package_name=<PACKAGE> --track=Release_Test_Track --metadata_path=./metadata --rollout=1 --version_code=18400202 --validate_only=false --skip_upload_apk=true --skip_upload_aab=true --skip_upload_metadata=true --skip_upload_screenshots=true --skip_upload_images=true --skip_upload_changelogs=true
12:18:28 [12:18:31]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
12:18:34 
12:18:34 +-------------------------+----------------------------------------------------+
12:18:34 |                          Summary for supply 2.146.1                          |
12:18:34 +-------------------------+----------------------------------------------------+
12:18:34 | json_key                | <KEY> |
12:18:34 | package_name            | <PACKAGE>                                |
12:18:34 | track                   | Release_Test_Track                                 |
12:18:34 | metadata_path           | ./metadata                                         |
12:18:34 | rollout                 | 1                                                  |
12:18:34 | version_code            | 18400202                                           |
12:18:34 | validate_only           | false                                              |
12:18:34 | skip_upload_apk         | true                                               |
12:18:34 | skip_upload_aab         | true                                               |
12:18:34 | skip_upload_metadata    | true                                               |
12:18:34 | skip_upload_screenshots | true                                               |
12:18:34 | skip_upload_images      | true                                               |
12:18:34 | skip_upload_changelogs  | true                                               |
12:18:34 | release_status          | completed                                          |
12:18:34 | check_superseded_tracks | false                                              |
12:18:34 | timeout                 | 300                                                |
12:18:34 | deactivate_on_promote   | true                                               |
12:18:34 +-------------------------+----------------------------------------------------+
12:18:34 
12:18:36 [12:18:38]: Updating 17900185's rollout to '1' on track 'Release_Test_Track'...
12:18:36 
12:18:36 [!] Google Api Error: badRequest: Only one completed release is allowed. - Only one completed release is allowed.
```

The log `Updating 17900185's rollout to '1' on track 'Release_Test_Track'...` indicates that fastlane attempted to update Bundle 2's rollout percentage instead of Bundle 1s even though Bundle 1s version code (18400202) was supplied in the fastlane command.

This lead me to dig into the code.

When the client retrieves the release list in fetch_track_and_release!, it selects a release via code here: https://github.com/fastlane/fastlane/blob/37c2aff3edacd9144ef0c7ca1ccf3aacbd6bd779/supply/lib/supply/uploader.rb#L114. In my scenario, the releases list would then contain the two version codes: [17900185, 18400202]

Link to the original code https://github.com/fastlane/fastlane/blob/37c2aff3edacd9144ef0c7ca1ccf3aacbd6bd779/supply/lib/supply/uploader.rb#L128  appears to always return the first item in this list, which in my scenario is 17900185, and not my expected outcome.

Is there an intention behind always using the first item of this list? 

I'm happy to hear any workarounds for accomplishing my goal. Thanks!

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
/usr/local/bin/fastlane supply --json=<PATH_TO_KEY> --package_name=<PACKAGE> --track=Release_Test_Track --metadata_path=./metadata --rollout=1 --version_code=18400202 --validate_only=false --skip_upload_apk=true --skip_upload_aab=true --skip_upload_metadata=true --skip_upload_screenshots=true --skip_upload_images=true --skip_upload_changelogs=true --verbose
[✔] 🚀
[16:50:51]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-------------------------+----------------------------------------------------+
|                          Summary for supply 2.146.1                          |
+-------------------------+----------------------------------------------------+
| json_key                | <PATH_TO_KEY> |
| package_name            | <PACKAGE>                                |
| track                   | Release_Test_Track                                 |
| metadata_path           | ./metadata                                         |
| rollout                 | 1                                                  |
| version_code            | 18400202                                           |
| validate_only           | false                                              |
| skip_upload_apk         | true                                               |
| skip_upload_aab         | true                                               |
| skip_upload_metadata    | true                                               |
| skip_upload_screenshots | true                                               |
| skip_upload_images      | true                                               |
| skip_upload_changelogs  | true                                               |
| release_status          | completed                                          |
| check_superseded_tracks | false                                              |
| timeout                 | 300                                                |
| deactivate_on_promote   | true                                               |
+-------------------------+----------------------------------------------------+

DEBUG [2020-04-22 16:50:52.67]: Fetching a new access token from Google...
INFO [2020-04-22 16:50:55.14]: Updating 17900185's rollout to '1' on track 'Release_Test_Track'...
Traceback (most recent call last):
	31: from /usr/local/bin/fastlane:23:in `<main>'
	30: from /usr/local/bin/fastlane:23:in `load'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/bin/fastlane:23:in `<top (required)>'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/commands_generator.rb:12:in `start'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/commands_generator.rb:59:in `run'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	22: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/uploader.rb:28:in `perform_upload'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/uploader.rb:143:in `update_rollout'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/client.rb:386:in `update_track'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/client.rb:80:in `call_google_api'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/client.rb:387:in `block in update_track'
	14: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.3/generated/google/apis/androidpublisher_v3/service.rb:1540:in `update_edit_track'
	13: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.3/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	12: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.3/lib/google/apis/core/http_command.rb:102:in `execute'
	11: from /Users/mobile/.gem/ruby/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	10: from /Users/mobile/.gem/ruby/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 9: from /Users/mobile/.gem/ruby/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 8: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.3/lib/google/apis/core/http_command.rb:110:in `block in execute'
	 7: from /Users/mobile/.gem/ruby/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	 6: from /Users/mobile/.gem/ruby/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 5: from /Users/mobile/.gem/ruby/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 4: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.3/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
	 3: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.3/lib/google/apis/core/http_command.rb:310:in `execute_once'
	 2: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.3/lib/google/apis/core/http_command.rb:193:in `process_response'
	 1: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.3/lib/google/apis/core/api_command.rb:117:in `check_status'
/Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.3/lib/google/apis/core/http_command.rb:228:in `check_status': badRequest: Only one completed release is allowed. (Google::Apis::ClientError)
	18: from /usr/local/bin/fastlane:23:in `<main>'
	17: from /usr/local/bin/fastlane:23:in `load'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/bin/fastlane:23:in `<top (required)>'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/commands_generator.rb:12:in `start'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/commands_generator.rb:59:in `run'
	12: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/uploader.rb:28:in `perform_upload'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/uploader.rb:143:in `update_rollout'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/client.rb:386:in `update_track'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/client.rb:79:in `call_google_api'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/supply/lib/supply/client.rb:94:in `rescue in call_google_api'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: badRequest: Only one completed release is allowed. - Only one completed release is allowed. (FastlaneCore::Interface::FastlaneError)
tw-172-24-220-55:~ mobile$
</pre>
</details>

### Environment

<details>
  <pre>
tw-172-24-220-55:~ mobile$ fastlane env
[✔] 🚀
[16:57:32]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:57:34]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.3       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.286.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| babosa                    | 1.0.3        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-04-22**
</details>
</pre>
</details>

(updated github links to point to original commits)

**Comment by bmcadams** [comment]
Hi @max-ott, 

This is still an issue for us. Do you know of a work around?

I am also curious if there is any intention behind returning the first element at this line https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L128. 

Thanks,
Ben

**Comment by bmcadams** [comment]
Hi @max-ott, any word on this?

**Comment by kelvSYC** [comment]
The issue does not appear to have changed in the latest master. Updating to the latest version will have no effect.

**Comment by KeithRoberson25** [comment]
This is still an issue for us. Do you know of a work around?

**Comment by bmcadams** [comment]
Is there any intention behind returning the first element at this line?https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L128.

This appears to be the issue at first glance. 

Thanks,
Ben

**Comment by lacostej** [comment]
According to  #20998 this one should be fixed.
