### ISSUE TITLE
fastlane init gives error when run in to the root directory of my react-native project

### ISSUE THREAD

**Issue by KaushalP25** [fastlane/fastlane#16371]
[⠼] 🚀 /Users/kaushalpatel/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[✔] 🚀 
DEBUG [2020-04-24 10:57:21.68]: Checking if there are any plugins that should be loaded...
DEBUG [2020-04-24 10:57:21.69]: Couldn't find xcodebuild at /Library/Developer/CommandLineTools//usr/bin/xcodebuild, check that it exists
/Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
[✔] Looking for iOS and Android projects in current directory...
ERROR [2020-04-24 10:57:22.69]: It looks like there is no iOS project in the current directory, though we did find one in a sub-directory
ERROR [2020-04-24 10:57:22.69]: Please `cd` into the directory of the intended Xcode project you wish to use.
Traceback (most recent call last):
	16: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	15: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	14: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `<main>'
	13: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `load'
	12: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/bin/fastlane:23:in `<top (required)>'
	11: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	10: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	 9: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	 8: from /Users/kaushalpatel/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Users/kaushalpatel/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Users/kaushalpatel/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Users/kaushalpatel/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
	 2: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/setup/setup.rb:93:in `start'
	 1: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again (FastlaneCore::Interface::FastlaneError)
	16: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	15: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	14: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `<main>'
	13: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `load'
	12: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/bin/fastlane:23:in `<top (required)>'
	11: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	10: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	 9: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	 8: from /Users/kaushalpatel/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Users/kaushalpatel/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Users/kaushalpatel/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Users/kaushalpatel/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
	 2: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/setup/setup.rb:93:in `start'
	 1: from /Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/kaushalpatel/.rvm/gems/ruby-2.7.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again\e[0m (FastlaneCore::Interface::FastlaneError)

**Comment by KaushalP25** [comment]
below is my output of fastlane env

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.14.5                              |
| Ruby                        | 2.7.0                                |
| Bundler?                    | true                                 |
| Git                         | git version 2.20.1 (Apple Git-117)   |
| Installation Source         | /usr/local/bin/fastlane              |
| Host                        | Mac OS X 10.14.5 (18F132)            |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib         |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.302.0      |
| aws-sigv4                 | 1.1.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| babosa                    | 1.0.3        |
| bundler                   | 2.1.2        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2020-04-24**
</details>
