### ISSUE TITLE
fastlane pilot upload error when trying to uploading the IPA file to the App Store

### ISSUE THREAD

**Issue by xplatform** [fastlane/fastlane#16387]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I was using Azure DevOps's Apple App Store Release pipeline to upload IPA file to the App Store, and running into the following error when executing "fastlane pilot upload" command.

2020-04-27T15:44:59.2852120Z /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
2020-04-27T15:44:59.2855050Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `require'
2020-04-27T15:44:59.2856870Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:230:in `finish_resolve'
2020-04-27T15:44:59.2858720Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:297:in `block in activate_bin_path'
2020-04-27T15:44:59.2860400Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:295:in `synchronize'
2020-04-27T15:44:59.2862020Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:295:in `activate_bin_path'
2020-04-27T15:44:59.2863480Z 	from /usr/local/bin/fastlane:23:in `<main>'
2020-04-27T15:44:59.3050400Z ##[error]Error: fastlane failed with return code: 1

##### Command executed
fastlane pilot upload -u *** -i /Users/user/Downloads/vsts-agent-osx-x64-2.165.2/_work/r2/a/TestApp iOS/drop/TestApp/TestAppiOS.ipa -a com.ipathsystem.TestApp

##### Complete output when running fastlane, including the stack trace and command used
2020-04-27T15:44:14.0182700Z ##[section]Starting: Publish Live File Explorer to the App Store TestFlight track
2020-04-27T15:44:14.0195280Z ==============================================================================
2020-04-27T15:44:14.0195710Z Task         : Apple App Store Release
2020-04-27T15:44:14.0196090Z Description  : Release an app to TestFlight or the Apple App Store
2020-04-27T15:44:14.0196440Z Version      : 1.158.0
2020-04-27T15:44:14.0196730Z Author       : Microsoft Corporation
2020-04-27T15:44:14.0198110Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2020-04-27T15:44:14.0198670Z ==============================================================================
2020-04-27T15:44:14.6885030Z c01c02bc-af94-408f-ac90-e6c3c5a5d22b exists true
2020-04-27T15:44:14.7074530Z [command]/usr/local/opt/ruby/bin/gem install fastlane
2020-04-27T15:44:14.7565140Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7566920Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7570030Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7572420Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7574910Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7577280Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7579440Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7582310Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7585000Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7590110Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7593670Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7596080Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7599540Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7600910Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7602020Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7603190Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7604410Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7605710Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7685300Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7688110Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7689700Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7691020Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7692370Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7693690Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7694920Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7696070Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7697210Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7698370Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:14.7699420Z (node:8951) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-27T15:44:22.0417070Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:22.0419330Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/rouge-2.0.7.gemspec:17.
2020-04-27T15:44:28.8162880Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:28.8166540Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/excon-0.59.0.gemspec:19.
2020-04-27T15:44:29.2221030Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:29.2222410Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/highline-1.7.8.gemspec:20.
2020-04-27T15:44:29.2242570Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:29.2243850Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:29.2247960Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:29.2249230Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/logging-2.2.2.gemspec:18.
2020-04-27T15:44:39.4912580Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:39.4913890Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/excon-0.59.0.gemspec:19.
2020-04-27T15:44:39.4915120Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:39.4916230Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/highline-1.7.8.gemspec:20.
2020-04-27T15:44:40.2797780Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:40.2799210Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/rouge-2.0.7.gemspec:17.
2020-04-27T15:44:41.6613120Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6615090Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:41.6616710Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6617860Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:41.6620990Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6622450Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:41.6624590Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6625810Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:41.6630490Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6631930Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:41.6639840Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6642520Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:41.6644760Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6647020Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/logging-2.2.2.gemspec:18.
2020-04-27T15:44:41.6653220Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6657390Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:41.6690800Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6692280Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/logging-2.2.2.gemspec:18.
2020-04-27T15:44:41.6694400Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6696530Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/logging-2.2.2.gemspec:18.
2020-04-27T15:44:41.6702880Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6704180Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/logging-2.2.2.gemspec:18.
2020-04-27T15:44:41.6707780Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6709030Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/logging-2.2.2.gemspec:18.
2020-04-27T15:44:41.6713600Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:41.6714940Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/logging-2.2.2.gemspec:18.
2020-04-27T15:44:42.1998960Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:42.2000320Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/multipart-post-2.0.0.gemspec:17.
2020-04-27T15:44:44.9321840Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:44.9323150Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/rouge-2.0.7.gemspec:17.
2020-04-27T15:44:53.9013200Z Successfully installed fastlane-2.146.1
2020-04-27T15:44:53.9014650Z Parsing documentation for fastlane-2.146.1
2020-04-27T15:44:53.9015370Z Done installing documentation for fastlane after 9 seconds
2020-04-27T15:44:53.9015940Z 1 gem installed
2020-04-27T15:44:54.0372200Z [command]/usr/local/opt/ruby/bin/gem update fastlane -i /Users/user/.gem-cache
2020-04-27T15:44:54.3568410Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:54.3570000Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/rouge-2.0.7.gemspec:17.
2020-04-27T15:44:54.4235150Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:54.4236510Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/excon-0.59.0.gemspec:19.
2020-04-27T15:44:54.4730110Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:54.4732300Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/highline-1.7.8.gemspec:20.
2020-04-27T15:44:54.4753830Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:54.4755370Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:54.4759350Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:54.4761260Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/logging-2.2.2.gemspec:18.
2020-04-27T15:44:54.9982490Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:54.9983810Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/rouge-2.0.7.gemspec:17.
2020-04-27T15:44:55.0731160Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:55.0733440Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/excon-0.59.0.gemspec:19.
2020-04-27T15:44:55.1290040Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:55.1291390Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/highline-1.7.8.gemspec:20.
2020-04-27T15:44:55.1310670Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:55.1311900Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/little-plugger-1.1.4.gemspec:18.
2020-04-27T15:44:55.1314800Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:55.1315960Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/logging-2.2.2.gemspec:18.
2020-04-27T15:44:58.5394070Z Updating installed gems
2020-04-27T15:44:58.5394500Z Nothing to update
2020-04-27T15:44:58.5728930Z [command]fastlane pilot upload -u *** -i /Users/user/Downloads/vsts-agent-osx-x64-2.165.2/_work/r2/a/TestApp iOS/drop/TestApp/TestAppiOS.ipa -a com.ipathsystem.TestApp
2020-04-27T15:44:58.7945160Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:58.7946770Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/rouge-2.0.7.gemspec:17.
2020-04-27T15:44:58.8204740Z NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
2020-04-27T15:44:58.8207900Z Gem::Specification#rubyforge_project= called from /Users/user/.gem-cache/specifications/highline-1.7.8.gemspec:20.
2020-04-27T15:44:59.2852120Z /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
2020-04-27T15:44:59.2855050Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:175:in `require'
2020-04-27T15:44:59.2856870Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:230:in `finish_resolve'
2020-04-27T15:44:59.2858720Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:297:in `block in activate_bin_path'
2020-04-27T15:44:59.2860400Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:295:in `synchronize'
2020-04-27T15:44:59.2862020Z 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:295:in `activate_bin_path'
2020-04-27T15:44:59.2863480Z 	from /usr/local/bin/fastlane:23:in `<main>'
2020-04-27T15:44:59.3050400Z ##[error]Error: fastlane failed with return code: 1
2020-04-27T15:44:59.3112910Z ##[section]Finishing: Publish TestApp to the App Store TestFlight track

### Environment

MacMini2014:vsts-agent-osx-x64-2.133.3 user$ fastlane env

[✔] 🚀 

[08:32:33]: fastlane detected a Gemfile in the current directory

[08:32:33]: However, it seems like you didn't use `bundle exec`

[08:32:33]: To launch fastlane faster, please use

[08:32:33]: 

[08:32:33]: $ bundle exec fastlane env

[08:32:33]: 

[08:32:33]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

[08:35:13]: Generating fastlane environment output, this might take a few seconds...

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |

| --------------------------- | ------------------------------------------- |

| OS                          | 10.15.4                                     |

| Ruby                        | 2.6.5                                       |

| Bundler?                    | false                                       |

| Git                         | git version 2.24.2 (Apple Git-127)          |

| Installation Source         | /usr/local/bin/fastlane                     |

| Host                        | Mac OS X 10.15.4 (19E266)                   |

| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib            |

| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |

| Is contained                | false                                       |

| Is homebrew                 | false                                       |

| Is installed via Fabric.app | false                                       |

| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |

| Xcode Version               | 11.4.1                                      |

### System Locale

| Variable | Value       |   |

| -------- | ----------- | - |

| LANG     | en_US.UTF-8 | ✅ |

| LC_ALL   |             |   |

| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |

| -------- | ------- | ------------- |

| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |

| ------------------------- | ------------ |

| did_you_mean              | 1.3.0        |

| slack-notifier            | 2.3.2        |

| atomos                    | 0.1.3        |

| CFPropertyList            | 3.0.2        |

| claide                    | 1.0.3        |

| colored2                  | 3.1.2        |

| nanaimo                   | 0.2.6        |

| xcodeproj                 | 1.16.0       |

| rouge                     | 2.0.7        |

| xcpretty                  | 0.3.0        |

| terminal-notifier         | 2.0.0        |

| unicode-display_width     | 1.7.0        |

| terminal-table            | 1.8.0        |

| plist                     | 3.5.0        |

| public_suffix             | 2.0.5        |

| addressable               | 2.7.0        |

| multipart-post            | 2.0.0        |

| word_wrap                 | 1.0.0        |

| tty-screen                | 0.7.1        |

| tty-cursor                | 0.7.1        |

| tty-spinner               | 0.9.3        |

| babosa                    | 1.0.3        |

| colored                   | 1.2          |

| highline                  | 1.7.10       |

| commander-fastlane        | 4.4.6        |

| excon                     | 0.73.0       |

| faraday                   | 0.17.3       |

| unf_ext                   | 0.0.7.7      |

| unf                       | 0.1.4        |

| domain_name               | 0.5.20190701 |

| http-cookie               | 1.0.3        |

| faraday-cookie_jar        | 0.0.6        |

| faraday_middleware        | 0.13.1       |

| fastimage                 | 2.1.7        |

| gh_inspector              | 1.1.3        |

| json                      | 2.3.0        |

| mini_magick               | 4.10.1       |

| multi_xml                 | 0.6.0        |

| rubyzip                   | 1.3.0        |

| security                  | 0.1.3        |

| xcpretty-travis-formatter | 1.0.0        |

| dotenv                    | 2.7.5        |

| naturally                 | 2.2.0        |

| simctl                    | 1.6.8        |

| jwt                       | 2.1.0        |

| uber                      | 0.1.0        |

| declarative               | 0.0.10       |

| declarative-option        | 0.1.0        |

| representable             | 3.0.4        |

| retriable                 | 3.1.2        |

| mini_mime                 | 1.0.2        |

| multi_json                | 1.14.1       |

| signet                    | 0.14.0       |

| memoist                   | 0.16.2       |

| os                        | 1.1.0        |

| googleauth                | 0.12.0       |

| httpclient                | 2.8.3        |

| google-api-client         | 0.36.4       |

| google-cloud-env          | 1.3.1        |

| google-cloud-errors       | 1.0.0        |

| google-cloud-core         | 1.5.0        |

| digest-crc                | 0.5.1        |

| google-cloud-storage      | 1.26.0       |

| emoji_regex               | 1.0.1        |

| jmespath                  | 1.4.0        |

| aws-partitions            | 1.303.0      |

| aws-eventstream           | 1.1.0        |

| aws-sigv4                 | 1.1.2        |

| aws-sdk-core              | 3.94.0       |

| aws-sdk-kms               | 1.30.0       |

| aws-sdk-s3                | 1.63.0       |

| bundler                   | 2.1.4        |

</details>

*generated on:* **2020-04-27**

</details>

[08:35:22]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.

[08:35:22]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into

your clipboard, so you can easily paste it on GitHub? (y/n)

y

[08:37:52]: Successfully copied markdown into your clipboard 🎨

[08:37:52]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by miscampbell** [comment]
Hi @xplatform 

Were you ever able to find a solution to this issue?
