### ISSUE TITLE
Crash during `fastlane init` with wrong AppleID

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#164]
I run `fastlane init`, then answer `y` for all questions.

Here is a crash-log after answer `y` to promt to re-enter user/password:

```
Do you want to re-enter your username and password?
(y/n)
y
Removing keychain item: deliver.XXXXXXXX
keychain: "/Users/XXXXXXXX/Library/Keychains/login.keychain"
class: "inet"
attributes:
    0x00000007 <blob>="deliver.XXXXXXXX"
    0x00000008 <blob>=<NULL>
    "acct"<blob>="XXXXXXXX"
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303135303333313133313534345A00  "20150331131544Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303135303333313133313534345A00  "20150331131544Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="deliver.XXXXXXXX"
    "type"<uint32>=<NULL>
password has been deleted.
You will have to re-run the recent command to use the new username/password.
DEBUG [2015-03-31 16:16:35.20]: [Transporter Output]: DBG-X: The error code is: -20101
FATAL [2015-03-31 16:16:35.20]: Transporter transfer failed.
WARN [2015-03-31 16:16:35.20]:
ERROR [2015-03-31 16:16:35.20]: Your Apple ID or password was entered incorrectly. (-20101)
FATAL [2015-03-31 16:16:35.20]: Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
ERROR [2015-03-31 16:16:35.20]: Your Apple ID or password was entered incorrectly. (-20101)
Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
FATAL [2015-03-31 16:16:35.20]: Could not download metadata from iTunes Connect! It's probably related to your password or your internet connection.
FATAL [2015-03-31 16:16:35.20]: Error occured with the setup program! Reverting changes now!
INFO [2015-03-31 16:16:35.20]: Moving './fastlane/screenshots' to 'screenshots'
INFO [2015-03-31 16:16:35.20]: Deleting the 'fastlane' folder
/Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/deliver-0.8.0/lib/deliver/app_metadata.rb:302:in `read': No such file or directory @ rb_sysopen - /tmp/956170225.itmsp//metadata.xml (Errno::ENOENT)
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/deliver-0.8.0/lib/deliver/app_metadata.rb:302:in `parse_package'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/deliver-0.8.0/lib/deliver/app_metadata.rb:66:in `initialize'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/deliver-0.8.0/lib/deliver/app.rb:113:in `new'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/deliver-0.8.0/lib/deliver/app.rb:113:in `metadata'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/deliver-0.8.0/lib/deliver/deliverfile/deliverfile_creator.rb:59:in `create_based_on_identifier'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/deliver-0.8.0/lib/deliver/deliverfile/deliverfile_creator.rb:31:in `create'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/fastlane-0.4.2/lib/fastlane/setup.rb:80:in `ask_to_enable_other_tools'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/fastlane-0.4.2/lib/fastlane/setup.rb:18:in `run'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/fastlane-0.4.2/bin/fastlane:45:in `block (2 levels) in run'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/command.rb:178:in `call'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/command.rb:178:in `call'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/command.rb:153:in `run'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/runner.rb:68:in `run!'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/delegates.rb:15:in `run!'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/fastlane-0.4.2/bin/fastlane:60:in `run'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5@global/gems/fastlane-0.4.2/bin/fastlane:64:in `<top (required)>'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.1.5/bin/fastlane:23:in `load'
	from /Users/XXXXXXXX/.rvm/rubies/ruby-2.1.5/bin/fastlane:23:in `<main>'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/XXXXXXXX/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by KrauseFx** [comment]
Mh, does it work when you run it again?

**Comment by skywinder** [comment]
Yes, but next time I set valid user/password combination and it's works as expected.
I can try to reproduce this exception, if it's needed.

**Comment by KrauseFx** [comment]
Okay, I'll take a look, thanks.

**Comment by skywinder** [comment]
1. you are close issue, but it reproducible and problem still exists in last version.
2. FYI: It caused by not very clear explanation:
When I saw first time `Your Apple ID:` I though, that script ask about "Apple ID for application".
So probably it's better to add description like  `Your iTunes Connect Apple ID` or  `Your Apple ID (email):`
3. The parameter, that you ask in init `App Identifier` actually named `Bundle ID` (in iTunes Connect) or `Bundle identifier` (in Xcode). So, probably it's better rename it to not confuse the developers with another name of this parameter.

**Comment by JaviSoto** [comment]
@skywinder hi! Is this still an issue? :)

**Comment by ohwutup** [comment]
hey @skywinder! we are currently working on making this a little bit of an easier process. let us know if this is still an issue for you or if you have any requests for new functionality in here!

**Comment by skywinder** [comment]
@ohwutup  @JaviSoto No, still an issue.
Here is a crash log: '09a63d8274c8b33cc02bf314e134fd63'


```
Password (for dslksdj@ldl.dd): ******
The login credentials for 'dslksdj@ldl.dd' seem to be wrong
Do you want to re-enter your password? (y/n)
n
Please run this tool again to apply the new password
[11:38:02]: Error occurred with the setup program! Reverting changes now!
[11:38:02]: Deleting the 'fastlane' folder

Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '09a63d8274c8b33cc02bf314e134fd63'
The crash report has been stored locally '/tmp/sentry_09a63d8274c8b33cc02bf314e134fd63.json'
```

**Comment by asfalcone** [comment]
@skywinder This issue is mentioned in #3876. It is working correctly with the latest version of `deliver`?

**Comment by TKBurner** [comment]
Closing because of merged changes. Let us know if you are still seeing this :+1:
