### ISSUE TITLE
上传pgy失败

### ISSUE THREAD

**Issue by 290138645** [fastlane/fastlane#16465]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
```
[16:42:30]: 开始上传蒲公英
+--------------------+----------------------------------------------+
|                           Lane Context                            |
+--------------------+----------------------------------------------+
| DEFAULT_PLATFORM   | ios                                          |
| PLATFORM_NAME      | ios                                          |
| LANE_NAME          | ios adHoc                                    |
| BUILD_NUMBER       | 56                                           |
| IPA_OUTPUT_PATH    | /Users/raolei/Desktop/工作文件/ipa/智慧鸡蛋  |
|                    | Beta_56.ipa                                  |
| XCODEBUILD_ARCHIVE | /Users/raolei/Library/Developer/Xco          |
|                    | de/Archives/2020-05-15/智慧鸡蛋Beta_56       |
|                    | 2020-05-15 16.34.05.xcarchive                |
| DSYM_OUTPUT_PATH   | /Users/raolei/Desktop/工作文件/ipa/智慧鸡蛋  |
|                    | Beta_56.app.dSYM.zip                         |
+--------------------+----------------------------------------------+
[16:42:30]: wrong number of arguments (given 0, expected 1)

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | get_build_number | 0           |
| 3    | gym              | 524         |
+------+------------------+-------------+

[16:42:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  `lane': [!] wrong number of arguments (given 0, expected 1) (ArgumentError)
    https://github.com/fastlane/fastlane/issues/15842 [closed] 1 💬
    28 Feb 2020

➡️  Wrong number of arguments provisioning_profile.rb
    https://github.com/fastlane/fastlane/issues/14557 [closed] 3 💬
    18 Jul 2019

➡️  pilot import CSV library wrong number of arguments
    https://github.com/fastlane/fastlane/issues/12403 [closed] 10 💬
    10 Oct 2018

and 16 more at: https://github.com/fastlane/fastlane/search?q=wrong%20number%20of%20arguments%20%28given%200%2C%20expected%201%29&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	19: from /usr/local/bin/fastlane:23:in `<main>'
	18: from /usr/local/bin/fastlane:23:in `load'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/bin/fastlane:23:in `<top (required)>'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	13: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	 1: from Fastfile:88:in `block (2 levels) in parsing_binding'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/fast_file.rb:223:in `desc': [!] wrong number of arguments (given 0, expected 1) (ArgumentError)
```

#### Question Description

Key | Value
-- | --
OS | 10.12.4
Ruby | 2.4.0
Bundler? | false
Git | git version 2.11.0 (Apple Git-81)
Installation Source | ~/.rvm/gems/ruby-2.4.0/bin/fastlane
Host | Mac OS X 10.12.4 (16E195)
Ruby Lib Dir | ~/.rvm/rubies/ruby-2.4.0/lib
OpenSSL Version | OpenSSL 1.1.0e 16 Feb 2017
Is contained | false
Is homebrew | false
Is installed via Fabric.app | false
Xcode Path | /Applications/Xcode.app/Contents/Developer/
Xcode Version | 8.3.2

**Comment by 290138645** [comment]
怎么写？

**Comment by janpio** [comment]
What is `pgy`?

**Comment by max-ott** [comment]
Your issue is missing a clear question. Please re-open it with a question and the required information.
