### ISSUE TITLE
Fastlane deliver: upload_metadata.rb:299:in `[]=': [!] string not matched (IndexError)

### ISSUE THREAD

**Issue by matsoftware** [fastlane/fastlane#16471]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

An exception is thrown on fastlane deliver 2.148.1 when running `fastlane deliver` after pulling metadata from the store and after populating the new fields.

##### Command executed

`fastlane deliver`

##### Complete output when running fastlane, including the stack trace and command used

This is my `metadata` folder structure:
<img width="401" alt="Screenshot 2020-05-18 at 17 50 38" src="https://user-images.githubusercontent.com/1196694/82233308-bc4a9480-9927-11ea-85f1-93c09adf5db4.png">

The only empty files are `subtitle.txt` and `apple_tv_privacy_policy.txt`

<details>
  <pre>
fastlane deliver             
[✔] 🚀 
[17:46:52]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:46:53]: Successfully loaded '~/secret/Deliverfile' 📄

+-----------------------+------------------------------------------+
|               Detected Values from './Deliverfile'               |
+-----------------------+------------------------------------------+
| app_identifier        | ----       |
| username              | -----               |
| overwrite_screenshots | true                                     |
| copyright             | ---- |
| support_url           | ----                     |
| marketing_url         | ----                   |
+-----------------------+------------------------------------------+

[17:46:53]: Login to App Store Connect (-----)
Multiple App Store Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "---"

or

  itc_team_name "----"

----

[17:46:55]: Login successful

+--------------------------------------+------------------------------------------+
|                             deliver 2.148.1 Summary                             |
+--------------------------------------+------------------------------------------+
| screenshots_path                     | ./screenshots                            |
| metadata_path                        | ./metadata                               |
| username                             | -----                   |
| app_identifier                       | -----      |
| platform                             | ios                                      |
| edit_live                            | false                                    |
| use_live_version                     | false                                    |
| skip_binary_upload                   | false                                    |
| skip_screenshots                     | false                                    |
| skip_metadata                        | false                                    |
| skip_app_version_update              | false                                    |
| force                                | false                                    |
| overwrite_screenshots                | true                                     |
| submit_for_review                    | false                                    |
| reject_if_possible                   | false                                    |
| automatic_release                    | false                                    |
| phased_release                       | false                                    |
| reset_ratings                        | false                                    |
| run_precheck_before_submit           | true                                     |
| precheck_default_rule_level          | warn                                     |
| individual_metadata_items            | []                                       |
| copyright                            | ----- |
| support_url                          | -----                 |
| marketing_url                        | -----                     |
| ignore_language_directory_validation | false                                    |
| precheck_include_in_app_purchases    | true                                     |
+--------------------------------------+------------------------------------------+

[17:46:57]: Loading './metadata/de-DE/description.txt'...
[17:46:57]: Loading './metadata/de-DE/keywords.txt'...
[17:46:57]: Loading './metadata/de-DE/release_notes.txt'...
[17:46:57]: Loading './metadata/de-DE/support_url.txt'...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Wrong screen sizes on recent iphones
    https://github.com/fastlane/fastlane/issues/14951 [closed] 18 💬
    30 Aug 2019

➡️  CFBundleShortVersionString changes to git branch name causing ERROR ITMS-90060
    https://github.com/fastlane/fastlane/issues/13427 [closed] 17 💬
    03 Jan 2019

➡️  Getting No profiles for '...' were found
    https://github.com/fastlane/fastlane/issues/12741 [closed] 11 💬
    01 Dec 2018

and 9 more at: https://github.com/fastlane/fastlane/search?q=string%20not%20matched&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	19: from /usr/local/bin/fastlane:23:in `<main>'
	18: from /usr/local/bin/fastlane:23:in `load'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/bin/fastlane:23:in `<top (required)>'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/commands_generator.rb:183:in `run'
	13: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/commands_generator.rb:80:in `block (2 levels) in run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/runner.rb:38:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/runner.rb:108:in `upload_metadata'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:291:in `load_from_filesystem'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:291:in `each'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:293:in `block in load_from_filesystem'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:293:in `each'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:299:in `block (2 levels) in load_from_filesystem'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:299:in `[]=': string not matched (IndexError)
	19: from /usr/local/bin/fastlane:23:in `<main>'
	18: from /usr/local/bin/fastlane:23:in `load'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/bin/fastlane:23:in `<top (required)>'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/commands_generator.rb:183:in `run'
	13: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/commands_generator.rb:80:in `block (2 levels) in run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/runner.rb:38:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/runner.rb:108:in `upload_metadata'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:291:in `load_from_filesystem'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:291:in `each'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:293:in `block in load_from_filesystem'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:293:in `each'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:299:in `block (2 levels) in load_from_filesystem'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/deliver/lib/deliver/upload_metadata.rb:299:in `[]=': [!] string not matched (IndexError)
</pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.312.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-sdk-core              | 3.95.0       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.64.0       |
| bundler                   | 2.1.4        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-05-19**
</details>
</pre>
</details>

**Comment by matsoftware** [comment]
The issue persists in 2.148.1 .

**Comment by matsoftware** [comment]
Ok so apparently the issue happens if I override some values in the `Deliverfile`:

```ruby
copyright "Copyright ⓒ Mattia Campolese 2009 - 2020"

support_url "http://my.url"

marketing_url "http://my.url"
```

despite fastlane notifies me that he has successful loaded the file.
