### ISSUE TITLE
fastlane match with aws got `Aws::S3::Errors::NotFound`

### ISSUE THREAD

**Issue by Lucashuang0802** [fastlane/fastlane#16586]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`fastlane match development` with AWS gave `Aws::S3::Errors::NotFound`. I can ping the bucket using `awscli` without issues.

##### Command executed
`fastlane match development`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀 
[13:31:26]: fastlane detected a Gemfile in the current directory
[13:31:26]: However, it seems like you didn't use `bundle exec`
[13:31:26]: To launch fastlane faster, please use
[13:31:26]: 
[13:31:26]: $ bundle exec fastlane match development
[13:31:26]: 
[13:31:26]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:31:29]: Successfully loaded '/Users/lhuang/iOS/fastlane/Matchfile' 📄

+----------------------+------------------------------------------+
|           Detected Values from './fastlane/Matchfile'           |
+----------------------+------------------------------------------+
| s3_region            | us-west-1                                |
| s3_bucket            | ***                            |
| s3_access_key        | ***                    |
| s3_secret_access_key | *** |
| storage_mode         | s3                                       |
| type                 | development                              |
| app_identifier       | ["***"]                  |
| username             | ***                      |
+----------------------+------------------------------------------+

+----------------------------+------------------------------------------+
|                       Summary for match 2.149.1                       |
+----------------------------+------------------------------------------+
| type                       | development                              |
| readonly                   | false                                    |
| generate_apple_certs       | true                                     |
| skip_provisioning_profiles | false                                    |
| app_identifier             | ["*****"]                  |
| username                   | *****                      |
| team_id                    | *****                               |
| storage_mode               | s3                                       |
| git_branch                 | master                                   |
| shallow_clone              | false                                    |
| clone_branch_directly      | false                                    |
| s3_region                  | us-west-1                                |
| s3_access_key              | *****                     |
| s3_secret_access_key       | ***** |
| s3_bucket                  | ****                            |
| keychain_name              | login.keychain                           |
| force                      | false                                    |
| force_for_new_devices      | false                                    |
| skip_confirmation          | false                                    |
| skip_docs                  | false                                    |
| platform                   | ios                                      |
| fail_on_name_taken         | false                                    |
| verbose                    | false                                    |
+----------------------------+------------------------------------------+

Traceback (most recent call last):
        48: from /usr/local/bin/fastlane:23:in `<main>'
        47: from /usr/local/bin/fastlane:23:in `load'
        46: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
        45: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        44: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/commands_generator.rb:25:in `start'
        43: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/commands_generator.rb:187:in `run'
        42: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        41: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        40: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        39: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        38: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        37: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/commands_generator.rb:68:in `block (3 levels) in run'
        36: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/runner.rb:58:in `run'
        35: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/storage/s3_storage.rb:91:in `download'
        34: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:56:in `each'
        33: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:56:in `each'
        32: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:56:in `each'
        31: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:50:in `block in each'
        30: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:50:in `each'
        29: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:50:in `each'
        28: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:99:in `block in non_empty_batches'
        27: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:99:in `each'
        26: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:99:in `each'
        25: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/bucket.rb:754:in `block in objects'
        24: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/pageable_response.rb:89:in `each'
        23: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/bucket.rb:764:in `block (2 levels) in objects'
        22: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/bucket.rb:764:in `yield'
        21: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:100:in `block (2 levels) in non_empty_batches'
        20: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:100:in `yield'
        19: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:51:in `block (2 levels) in each'
        18: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:51:in `each'
        17: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:52:in `block (3 levels) in each'
        16: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:52:in `yield'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/storage/s3_storage.rb:98:in `block in download'
        14: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/customizations/object_summary.rb:78:in `download_file'
        13: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/customizations/object.rb:368:in `download_file'
        12: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/file_downloader.rb:34:in `download'
        11: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/file_downloader.rb:54:in `multipart_download'
        10: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/client.rb:5564:in `head_object'
         9: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/request.rb:70:in `send_request'
         8: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
         7: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
         6: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
         5: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
         4: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
         3: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
         2: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
         1: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
/Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Aws::S3::Errors::NotFound
        48: from /usr/local/bin/fastlane:23:in `<main>'
        47: from /usr/local/bin/fastlane:23:in `load'
        46: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
        45: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        44: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/commands_generator.rb:25:in `start'
        43: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/commands_generator.rb:187:in `run'
        42: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        41: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        40: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        39: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        38: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        37: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/commands_generator.rb:68:in `block (3 levels) in run'
        36: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/runner.rb:58:in `run'
        35: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/storage/s3_storage.rb:91:in `download'
        34: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:56:in `each'
        33: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:56:in `each'
        32: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:56:in `each'
        31: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:50:in `block in each'
        30: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:50:in `each'
        29: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:50:in `each'
        28: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:99:in `block in non_empty_batches'
        27: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:99:in `each'
        26: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:99:in `each'
        25: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/bucket.rb:754:in `block in objects'
        24: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/pageable_response.rb:89:in `each'
        23: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/bucket.rb:764:in `block (2 levels) in objects'
        22: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/bucket.rb:764:in `yield'
        21: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:100:in `block (2 levels) in non_empty_batches'
        20: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:100:in `yield'
        19: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:51:in `block (2 levels) in each'
        18: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:51:in `each'
        17: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:52:in `block (3 levels) in each'
        16: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/resources/collection.rb:52:in `yield'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/storage/s3_storage.rb:98:in `block in download'
        14: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/customizations/object_summary.rb:78:in `download_file'
        13: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/customizations/object.rb:368:in `download_file'
        12: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/file_downloader.rb:34:in `download'
        11: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/file_downloader.rb:54:in `multipart_download'
        10: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/client.rb:5564:in `head_object'
         9: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/request.rb:70:in `send_request'
         8: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
         7: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
         6: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
         5: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
         4: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
         3: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
         2: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
         1: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
/Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': [!]  (Aws::S3::Errors::NotFound) </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    gym(
      workspace: "***.xcworkspace",
      scheme: "***",
      sdk: "iOS 13.2",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      silent: true
    )
    # upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("***") # The bundle identifier of your app
apple_id("***") # Your Apple email address

itc_team_id("*****") # App Store Connect Team ID
team_id("*****") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| tty-screen                | 0.8.0        |
| json                      | 2.3.0        |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.2        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.4        |
| aws-partitions            | 1.326.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.98.0       |
| aws-sdk-kms               | 1.33.0       |
| aws-sdk-s3                | 1.67.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-06-09**
</details>

**Comment by Lucashuang0802** [comment]
This looks a bit weird, why does `fastlane` need to download anything 🤔 ?
```
15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/match/lib/match/storage/s3_storage.rb:98:in `block in download'
```

**Comment by Lucashuang0802** [comment]
looks like someone experienced a similar issue - https://github.com/fastlane/fastlane/issues/16183#issuecomment-601840742. Can anyone take a look, please?

**Comment by Lucashuang0802** [comment]
also, any reason why we iterate every single file in order to look up the certs&keys? https://github.com/fastlane/fastlane/blob/31ff25306872292d02459d226c8fd982912c1e8a/match/lib/match/storage/s3_storage.rb#L91-L101

@erneestoc, since you are the author of https://github.com/fastlane/fastlane/pull/15200, hope you don't mind I tag you here. 😄
