### ISSUE TITLE
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

### ISSUE THREAD

**Issue by abhinavsingh** [fastlane/fastlane#16852]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`fastlane beta` for Android (flutter) app leads into `Could not initialize class org.codehaus.groovy.runtime.InvokerHelper` exception.

##### Command executed
`fastlane beta`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
fastlane beta        
[✔] 🚀 
[21:16:32]: fastlane detected a Gemfile in the current directory
[21:16:32]: However, it seems like you didn't use `bundle exec`
[21:16:32]: To launch fastlane faster, please use
[21:16:32]: 
[21:16:32]: $ bundle exec fastlane beta
[21:16:32]: 
[21:16:32]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[21:16:36]: ------------------------------
[21:16:36]: --- Step: default_platform ---
[21:16:36]: ------------------------------
/usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
[21:16:36]: Driving the lane 'android beta' 🚀
[21:16:36]: -----------------------------------
[21:16:36]: --- Step: clean assembleRelease ---
[21:16:36]: -----------------------------------
[21:16:36]: $ /Users/abhinavsingh/Dev/jaxl/myflutterapp/app/myflutterapp/android/gradlew clean assembleRelease -p .
[21:16:37]: ▸ FAILURE: Build failed with an exception.
[21:16:37]: ▸ * What went wrong:
[21:16:37]: ▸ Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
[21:16:37]: ▸ * Try:
[21:16:37]: ▸ Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[21:16:37]: ▸ * Get more help at https://help.gradle.org
[21:16:37]: ▸ BUILD FAILED in 479ms
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android beta |
+------------------+--------------+
[21:16:37]: Exit status of command '/Users/abhinavsingh/Dev/jaxl/myflutterapp/app/myflutterapp/android/gradlew clean assembleRelease -p .' was 1 instead of 0.

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 479ms

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | default_platform      | 0           |
| 💥   | clean assembleRelease | 0           |
+------+-----------------------+-------------+

[21:16:37]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	31: from /usr/local/Cellar/fastlane/2.152.0/libexec/bin/fastlane:23:in `<main>'
	30: from /usr/local/Cellar/fastlane/2.152.0/libexec/bin/fastlane:23:in `load'
	29: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/bin/fastlane:23:in `<top (required)>'
	28: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	27: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	26: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	25: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	24: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	23: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	22: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	21: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	20: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	19: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	18: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	17: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	16: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	15: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	14: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	13: from Fastfile:26:in `block (2 levels) in parsing_binding'
	12: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	11: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	10: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 9: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 8: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 7: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 6: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 5: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
	 4: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
	 3: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/forwardable.rb:235:in `sh'
	 2: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.152.0/libexec/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Exit status of command '/Users/abhinavsingh/Dev/jaxl/myflutterapp/app/myflutterapp/android/gradlew clean assembleRelease -p .' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 479ms
  </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.5                                                 |
| Ruby                        | 2.7.1                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.152.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.5                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/Users/abhinavsingh/Dev/jaxl/myflutterapp/service-account.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.myflutterapp") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.152.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.17.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.75.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.14.0       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.1        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.13.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.341.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-sdk-core              | 3.103.0      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.74.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-07-14**
</details>

**Comment by abhinavsingh** [comment]
I realized this is more of a gradle issue and not necessarily under fastlane purview.  Closing.
