### ISSUE TITLE
App screenshot missing (APP_IPAD_PRO_3GEN_129)

### ISSUE THREAD

**Issue by ameffert** [fastlane/fastlane#16975]
### New Issue Checklist

✅ Updated fastlane to the latest version
✅ I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
✅ I read [docs.fastlane.tools](https://docs.fastlane.tools)
✅ I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

iPad Pro 3rd gen screenshots were saved in iPad Pro 2nd gen screenshot slots on App Store Connect
Submitting for review failed

##### Command executed

fastlane deliver

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀 
+-------------------------+---------+---------+
|                Used plugins                 |
+-------------------------+---------+---------+
| Plugin                  | Version | Action  |
+-------------------------+---------+---------+
| fastlane-plugin-cordova | 3.0.0   | cordova |
+-------------------------+---------+---------+

[17:17:25]: Driving the lane 'ios deliver_ex' 🚀
[17:17:25]: ---------------------
[17:17:25]: --- Step: deliver ---
[17:17:25]: ---------------------
[17:17:25]: Successfully loaded '/Users/andy/Dev/Cordova/M*****R******/packages/de.b***-s*******.r******/fastlane/Deliverfile' 📄

+-----------------------------------+-----------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------------------------+-----------+
| submit_for_review                 | true      |
| force                             | true      |
| overwrite_screenshots             | true      |
| automatic_release                 | true      |
| precheck_include_in_app_purchases | false     |
+-----------------------------------+-----------+

[17:17:25]: Login to App Store Connect (a*******@a******.de)
Available session is not valid any more. Continuing with normal login.
Two-step Verification (4 digits code) is enabled for account 'a*******@a******.de'
More information about Two-step Verification: https://support.apple.com/en-us/HT204152

Please select a trusted device to verify your identity
1. +•• •••• ••••••37	SMS	(1772228721)
?  1
Successfully requested notification
Please enter the 4 digit code: ****
Requesting session...
[17:17:50]: Login successful

+----------------------------------------------+----------------------------------------------+
|                                   deliver 2.154.0 Summary                                   |
+----------------------------------------------+----------------------------------------------+
| ipa                                          | platforms/ios/build/device/B*** S*******.ipa |
| submission_information.add_id_info_uses_idfa | false                                        |
| screenshots_path                             | ./fastlane/screenshots                       |
| metadata_path                                | ./fastlane/metadata                          |
| app_version                                  | 3.0.2                                        |
| username                                     | a*******@a******.de                          |
| app_identifier                               | de.b***-s*******.r******                     |
| platform                                     | ios                                          |
| edit_live                                    | false                                        |
| use_live_version                             | false                                        |
| skip_binary_upload                           | false                                        |
| skip_screenshots                             | false                                        |
| skip_metadata                                | false                                        |
| skip_app_version_update                      | false                                        |
| force                                        | true                                         |
| overwrite_screenshots                        | true                                         |
| submit_for_review                            | true                                         |
| reject_if_possible                           | false                                        |
| automatic_release                            | true                                         |
| phased_release                               | false                                        |
| reset_ratings                                | false                                        |
| team_id                                      | 5*****                                       |
| dev_portal_team_id                           | P*********                                   |
| run_precheck_before_submit                   | true                                         |
| precheck_default_rule_level                  | warn                                         |
| ignore_language_directory_validation         | false                                        |
| precheck_include_in_app_purchases            | false                                        |
+----------------------------------------------+----------------------------------------------+

[17:17:54]: Making sure the latest version on App Store Connect matches '3.0.2'...
[17:17:54]: '3.0.2' is the latest version on App Store Connect
[17:17:57]: Loading './fastlane/metadata/de-DE/description.txt'...
[17:17:57]: Loading './fastlane/metadata/de-DE/keywords.txt'...
[17:17:57]: Loading './fastlane/metadata/de-DE/release_notes.txt'...
[17:17:57]: Loading './fastlane/metadata/de-DE/support_url.txt'...
[17:17:57]: Loading './fastlane/metadata/de-DE/marketing_url.txt'...
[17:17:57]: Loading './fastlane/metadata/de-DE/promotional_text.txt'...
[17:17:57]: Loading './fastlane/metadata/de-DE/name.txt'...
[17:17:57]: Loading './fastlane/metadata/de-DE/subtitle.txt'...
[17:17:57]: Loading './fastlane/metadata/de-DE/privacy_url.txt'...
[17:17:57]: Loading './fastlane/metadata/de-DE/apple_tv_privacy_policy.txt'...
[17:17:57]: Loading './fastlane/metadata/copyright.txt'...
[17:17:57]: Loading './fastlane/metadata/primary_category.txt'...
[17:17:57]: Loading './fastlane/metadata/secondary_category.txt'...
[17:17:57]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[17:17:57]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[17:17:57]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[17:17:57]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[17:17:57]: Loading './fastlane/metadata/review_information/first_name.txt'...
[17:17:57]: Loading './fastlane/metadata/review_information/last_name.txt'...
[17:17:57]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[17:17:57]: Loading './fastlane/metadata/review_information/email_address.txt'...
[17:17:57]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[17:17:57]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[17:17:57]: Loading './fastlane/metadata/review_information/notes.txt'...
[17:18:05]: Will begin uploading metadata for '3.0.2' on App Store Connect
[17:18:05]: Skipping 'release_notes'... this is the first version of the app
[17:18:05]: Uploading metadata to App Store Connect for version
[17:18:06]: Uploading metadata to App Store Connect for localized version 'de-DE'
[17:18:07]: Uploading metadata to App Store Connect for localized info 'de-DE'
[17:18:16]: Uploading app review information to App Store Connect
[17:18:17]: Error fetching app store review detail - The specified resource does not exist - There is no resource of type 'appStoreReviewDetails' with id 'null'
[17:18:21]: Will begin uploading snapshots for '3.0.2' on App Store Connect
[17:18:21]: Starting with the upload of screenshots...
[17:18:24]: Number of screenshots not deleted: 0
[17:18:24]: Successfully deleted all screenshots
[17:18:24]: Will wait for screenshot image processing
[17:18:24]: Set env DELIVER_SKIP_WAIT_FOR_SCREENSHOT_PROCESSING=true to skip waiting for screenshots to process
[17:18:25]: Uploading 20 screenshots for language de-DE
[17:18:25]: Uploading './fastlane/screenshots/de-DE/0_APP_IPAD_PRO_129_0.png'...
[17:18:43]: Uploading './fastlane/screenshots/de-DE/0_APP_IPAD_PRO_3GEN_129_0.png'...
[17:18:59]: Uploading './fastlane/screenshots/de-DE/0_APP_IPHONE_55_0.png'...
[17:19:10]: Uploading './fastlane/screenshots/de-DE/0_APP_IPHONE_65_0.png'...
[17:19:16]: Uploading './fastlane/screenshots/de-DE/1_APP_IPAD_PRO_129_1.png'...
[17:19:25]: Uploading './fastlane/screenshots/de-DE/1_APP_IPAD_PRO_3GEN_129_1.png'...
[17:19:33]: Uploading './fastlane/screenshots/de-DE/1_APP_IPHONE_55_1.png'...
[17:19:42]: Uploading './fastlane/screenshots/de-DE/1_APP_IPHONE_65_1.png'...
[17:19:51]: Uploading './fastlane/screenshots/de-DE/2_APP_IPAD_PRO_129_2.png'...
[17:19:59]: Uploading './fastlane/screenshots/de-DE/2_APP_IPAD_PRO_3GEN_129_2.png'...
[17:20:06]: Uploading './fastlane/screenshots/de-DE/2_APP_IPHONE_55_2.png'...
[17:20:17]: Uploading './fastlane/screenshots/de-DE/2_APP_IPHONE_65_2.png'...
[17:20:26]: Uploading './fastlane/screenshots/de-DE/3_APP_IPAD_PRO_129_3.png'...
[17:20:37]: Uploading './fastlane/screenshots/de-DE/3_APP_IPAD_PRO_3GEN_129_3.png'...
[17:20:47]: Uploading './fastlane/screenshots/de-DE/3_APP_IPHONE_55_3.png'...
[17:20:54]: Uploading './fastlane/screenshots/de-DE/3_APP_IPHONE_65_3.png'...
[17:21:03]: Uploading './fastlane/screenshots/de-DE/4_APP_IPAD_PRO_129_4.png'...
[17:21:10]: Uploading './fastlane/screenshots/de-DE/4_APP_IPAD_PRO_3GEN_129_4.png'...
[17:21:18]: Uploading './fastlane/screenshots/de-DE/4_APP_IPHONE_55_4.png'...
[17:21:30]: Uploading './fastlane/screenshots/de-DE/4_APP_IPHONE_65_4.png'...
[17:21:37]: Successfully uploaded screenshots to App Store Connect
[17:21:37]: Uploading binary to App Store Connect
[17:21:37]: Going to upload updated app to App Store Connect
[17:21:37]: This might take a few minutes. Please don't interrupt the script.
[17:22:23]: iTunes Transporter successfully finished its job
[17:22:23]: ------------------------------------------------------------------------------------------------------------------
[17:22:23]: --- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
[17:22:23]: ------------------------------------------------------------------------------------------------------------------
[17:22:23]: Finished the upload to App Store Connect
[17:22:23]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[17:22:23]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+--------------------------+
|            Summary for precheck 2.154.0             |
+--------------------------+--------------------------+
| default_rule_level       | warn                     |
| include_in_app_purchases | false                    |
| app_identifier           | de.b***-s*******.r****** |
| username                 | a*******@a******.de      |
| team_id                  | 5*****                   |
+--------------------------+--------------------------+

[17:22:23]: Checking app for precheck rule violations
[17:22:44]: ✅  Passed: No negative  sentiment
[17:22:44]: ✅  Passed: No placeholder text
[17:22:44]: ✅  Passed: No mentioning  competitors
[17:22:44]: ✅  Passed: No future functionality promises
[17:22:44]: ✅  Passed: No words indicating test content
[17:22:44]: ✅  Passed: No curse words
[17:22:44]: ✅  Passed: No words indicating your IAP is free
[17:22:44]: ✅  Passed: Incorrect, or missing copyright date
[17:22:46]: ✅  Passed: No broken urls
[17:22:46]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[17:22:46]: Selecting the latest build...
[17:22:46]: Waiting for processing on... app_id: 1*********, app_version: 3.0.2, build_version: 3.0.22, platform: IOS
[17:22:47]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
[17:22:47]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[17:23:03]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[17:23:18]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[17:23:34]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[17:23:55]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 3.0.22) for IOS
[17:24:12]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 3.0.22) for IOS
[17:24:28]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 3.0.22) for IOS
[17:24:44]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 3.0.22) for IOS
[17:25:00]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 3.0.22) for IOS
[17:25:16]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 3.0.22) for IOS
[17:25:32]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 3.0.22) for IOS
[17:25:48]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 3.0.22) for IOS
[17:26:04]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 3.0.22) for IOS
[17:26:20]: Successfully finished processing the build 3.0.2 - 3.0.22 for IOS
[17:26:20]: Selecting build 3.0.2 (3.0.22)...
[17:26:22]: Successfully selected build
[17:26:25]: Successfully updated IDFA declarations on App Store Connect
+---------------+----------------+
|          Lane Context          |
+---------------+----------------+
| PLATFORM_NAME | ios            |
| LANE_NAME     | ios deliver_ex |
+---------------+----------------+
[17:26:26]: The request cannot be fulfilled because of the state of another resource. - Submit for review errors found.
App screenshot missing (APP_IPAD_PRO_3GEN_129).

+------+---------+-------------+
|       fastlane summary       |
+------+---------+-------------+
| Step | Action  | Time (in s) |
+------+---------+-------------+
| 💥   | deliver | 541         |
+------+---------+-------------+

[17:26:26]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  DELIVER (2.150.0.rc3/4) always ask attribute whatsNew
    https://github.com/fastlane/fastlane/issues/16700 [open] 37 💬
    4 weeks ago

➡️  Completely new app gets: You must provide a value for the attribute 'usesNonExemptEncryption' with this request
    https://github.com/fastlane/fastlane/issues/16645 [closed] 11 💬
    2 weeks ago

➡️  Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
    https://github.com/fastlane/fastlane/issues/16639 [closed] 116 💬
    3 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/andy/.gems/bin/fastlane)
Spaceship::UnexpectedResponse: [!] The request cannot be fulfilled because of the state of another resource. - Submit for review errors found.
App screenshot missing (APP_IPAD_PRO_3GEN_129).
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/spaceship/lib/spaceship/connect_api/client.rb:99:in `post'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:825:in `post_app_store_version_submission'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:157:in `create_app_store_version_submission'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/deliver/lib/deliver/submit_for_review.rb:26:in `submit!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/deliver/lib/deliver/runner.rb:171:in `submit_for_review'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/deliver/lib/deliver/runner.rb:52:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:46:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/bin/fastlane:23:in `<top (required)>'
  /Users/andy/.gems/bin/fastlane:23:in `load'
  /Users/andy/.gems/bin/fastlane:23:in `<top (required)>' </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.6                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
# https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
# https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)
# default_platform(:ios)

platform :ios do
  desc "Deploy ios app on the appstore"
  lane :deploy do
    cordova(
      platform: 'ios',
      cordova_build_config_file: ENV['CORDOVA_BUILD_CONFIG_FILE']
    )
    # echo(message: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      workspace: ENV['XCWORKSPACE'],
      scheme: ENV['SCHEME']
    )
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(
      workspace: ENV['XCWORKSPACE'],
      scheme: ENV['SCHEME']
    )
    upload_to_app_store
  end
  
  desc "Deliver with preconfigured settings"
  lane :deliver_ex do
    deliver(
      ipa: ENV['IPA'],
      submission_information: { add_id_info_uses_idfa: false }
    )
  end
end

platform :android do
  desc "Deploy android app on play store"
  lane :deploy do
    cordova(
      platform: 'android',
      cordova_build_config_file: ENV['CORDOVA_BUILD_CONFIG_FILE']
    )
    # echo(message: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
  end

  desc "Supply with preconfigured settings"
  lane :supply_ex do
    supply(
      track: 'production',
      apk: ENV['APK'],
      skip_upload_aab: true,
      release_status: 'draft'
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

app_identifier(ENV['BUNDLE_IDENTIFIER']) # The bundle identifier of your app
apple_id(ENV['APPLE_ID']) # Your Apple email address
itc_team_id(ENV['ITC_TEAM_ID']) # App Store Connect Team ID
team_id(ENV['TEAM_ID']) # Developer Portal Team ID

json_key_file(ENV['JSON_KEY_FILE']) # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name(ENV['PACKAGE_NAME']) # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.154.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-cordova | 3.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.0       |
| public_suffix             | 4.0.5        |
| tty-screen                | 0.8.0        |
| excon                     | 0.75.0       |
| json                      | 2.3.1        |
| jwt                       | 2.2.1        |
| declarative               | 0.0.20       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.2        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.339.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.103.0      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.73.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
| fastlane-plugin-cordova   | 3.0.0        |
</details>

*generated on:* **2020-07-30**
</details> </pre>
</details>

**Comment by reishka** [comment]
Echoing this issue. We've tried using both `ipadPro129` and `iPad Pro (12.9-inch) (3rd generation)` filenames, per fastlane docs, but screenshots still get uploaded to iPadPro 2nd gen slots.

**Comment by reishka** [comment]
Not sure what (if anything) changed, but as of yesterday this seems to have been resolved. We just did a batch upload and both sets of iPad screenshots uploaded as intended.

**Comment by ameffert** [comment]
Same problem 7 weeks later:

ERROR [2020-09-10 11:38:40.54]: The request cannot be fulfilled because of the state of another resource. - Submit for review errors found.
App screenshot missing (APP_IPAD_PRO_3GEN_129). - A screenshot with type ipadPro129 is required but was not provided

**Comment by rogerluan** [comment]
Hey, I was facing this issue as well, and following [the docs](https://docs.fastlane.tools/actions/deliver/#uploading-screenshots-for-ipad-pro-129-inch-3rd-generation) helped me make it work. I called my 3rd gen screenshots `ipadPro129-3rd-gen-<number from 1 to 10>`, and all the other screenshots can have any naming.

I'm on latest fastlane version FWIW, v2.160.0

> Echoing this issue. We've tried using both `ipadPro129` and `iPad Pro (12.9-inch) (3rd generation)` filenames, per fastlane docs, but screenshots still get uploaded to iPadPro 2nd gen slots.

@reishka not sure what could be causing that to you 🤔 can you share more about your env, and screenshot files so maybe I can help you?

**Comment by Hawkins326** [comment]
I will ensure that I bookmark your blog and will come back sometime soon.

<a href="https://www.omegle.vin/">omegle</a>
