### ISSUE TITLE
Unable to find instrumentation info

### ISSUE THREAD

**Issue by NicholasIoanJones** [fastlane/fastlane#16997]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
android.util.AndroidException: INSTRUMENTATION_FAILED: com.xxx.xxx.test/androidx.test.runner.AndroidJUnitRunner encountered trying to create screenshots

##### Command executed
Running bundle exec fastlane screenshots
The apks build, they are installed, locale commands are updated but the "shell am instrument" command fails.

These tests have worked prior to RN 0.60 update and all the AndroidX changes after which they fell into disrepair. I have now changed the test to use androidx, changed the dependencies to
```
    androidTestImplementation('tools.fastlane:screengrab:1.2.0') {
        exclude group: 'com.android.support.test.uiautomator', module: 'uiautomator-v18'
    }
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test:rules:1.1.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'
```

##### Complete output when running fastlane, including the stack trace and command used
The full output from fastlane screenshots is obviously pretty long, but the error is reproducible by just running the last step again (for concise output).
<details>
  <pre> Nicks-MacBook-Pro:android nickjones$ adb -s emulator-5554 shell am instrument --no-window-animation -w -e testLocale en_US -e endingLocale en_US com.xxxx.xxxx.test/androidx.test.runner.AndroidJUnitRunner
android.util.AndroidException: INSTRUMENTATION_FAILED: com.xxxx.xxxx.test/androidx.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Instrument.run(Instrument.java:514)
        at com.android.commands.am.Am.runInstrument(Am.java:196)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.xxxx.xxxx.test/androidx.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1
Nicks-MacBook-Pro:android nickjones$ 
 </pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | ~/.gems/bin/fastlane                                           |
| Host                        | Mac OS X 10.15.6 (19G73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.6                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Generate all correct icon sizes from source"
  lane :icons do
    android_appicon(
      appicon_image_file: 'AppIcon/IconAndroid.png',
      appicon_path: './app/src/main/res/mipmap'
    )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "clearData")
    gradle(task: "test")
  end

  desc "Capture a new set of screenshots"
  lane :screenshots do
    gradle(task: "assembleDebug assembleAndroidTest")
    gradle(task: "clearData")
    screengrab(
        clear_previous_screenshots: true,
        test_instrumentation_runner: 'androidx.test.runner.AndroidJUnitRunner',
        app_apk_path: "./app/build/outputs/apk/debug/app-debug.apk",
        tests_apk_path: "./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk",
        # Note: Since we need to reset the app data between the tests we cannot supply multiple locales
        #        here. As a workaround just call screengrab multiple times.
        locales: ["en-US"]
    )
  end

  desc "Submit a new build to the Google Play store on alpha track and then promote to beta track (closed testing)"
  lane :beta do
    gradle(task: "clean bundleRelease")
    supply(
        aab: "./app/build/outputs/bundle/release/app-release.aab",
        track: "alpha",
    )
    supply(
        track: "alpha",
        track_promote_to: "beta",
        skip_upload_apk: true,
        skip_upload_aab: true,
        skip_upload_images: true,
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_screenshots: true,
    )
  end

  desc "Deploy a new version to Google Play (by promoting the build currently in the beta track)"
  lane :deploy do
    supply(
        track: "beta",
        track_promote_to: "production",
        skip_upload_apk: true,
        skip_upload_aab: true,
        skip_upload_images: true,
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_screenshots: true,
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "./secrets.json" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name "com.xxxx.xxxx"

```
</details>

### fastlane gems

| Gem        | Version | Update-Status |
| ---------- | ------- | ------------- |
| fastlane   | 2.154.0 | ✅ Up-To-Date  |
| screengrab | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.15.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.351.0      |
| aws-sigv4                 | 1.2.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.1        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.27.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.17.1       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appicon   | 0.15.0       |
</details>

*generated on:* **2020-08-05**
</details>

**Comment by NicholasIoanJones** [comment]
I am not seeing this error anymore, possibly due to latest fastlane version, possibly because of configuration changes in my environment.
