### ISSUE TITLE
"\x82" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by philCc** [fastlane/fastlane#17083]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

`fastlane ipa --env .adhoc --swift_server_port 2001`

##### 
```shell
Available session is not valid any more. Continuing with normal login.
[15:28:45]: Successfully logged in
[15:28:45]: Fetching profiles...
[15:28:50]: Verifying certificates...
+----------------+--------+
|      Lane Context       |
+----------------+--------+
| ENVIRONMENT    | .adhoc |
| LANE_NAME      | ipa    |
| VERSION_NUMBER | 1.6.0  |
| BUILD_NUMBER   | 630    |
+----------------+--------+
[15:28:50]: "\x82" from ASCII-8BIT to UTF-8
[15:28:50]: ▸ sh: line 1: 23253 Illegal instruction: 4  ./fastlane/FastlaneRunner lane ipa swiftServerPort 2001 > /dev/null
#<Thread:0x00007fe0a73358f8@/Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/swift_lane_manager.rb:96 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        4: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/swift_lane_manager.rb:97:in `block in cruise_swift_lane_in_thread'
        3: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
        2: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
        1: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane ipa swiftServerPort 2001 > /dev/null' was 132 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
sh: line 1: 23253 Illegal instruction: 4  ./fastlane/FastlaneRunner lane ipa swiftServerPort 2001 > /dev/null

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | update_fastlane        | 5           |
| 2    | get_version_number     | 0           |
| 3    | get_build_number       | 0           |
| 4    | increment_build_number | 1           |
| 💥   | match                  | 33          |
+------+------------------------+-------------+

[15:28:50]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Swift] PEM crash when exporting certificate with "\x82" from ASCII-8BIT to UTF-8 error
    https://github.com/fastlane/fastlane/issues/14709 [closed] 8 💬
    04 Nov 2019

➡️  PEM crash when exporting certificate with "\x82" from ASCII-8BIT to UTF-8 error
    https://github.com/fastlane/fastlane/issues/14019 [closed] 13 💬
    29 Jun 2019

➡️  Write Match encrypted files in binary mode to avoid UndefinedConversi…
    https://github.com/fastlane/fastlane/pull/12112 [closed] 5 💬
    22 May 2018

and 6 more at: https://github.com/fastlane/fastlane/search?q=%22%5Cx82%22%20from%20ASCII-8BIT%20to%20UTF-8&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
        34: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
        33: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
        32: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
        31: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
        30: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
        29: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
        28: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:86:in `parse_and_execute_command'
        27: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:123:in `handle_action_command'
        26: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:176:in `process_action_command'
        25: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:181:in `execute_action_command'
        24: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:42:in `execute'
        23: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:73:in `run'
        22: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        21: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        20: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        19: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        18: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        17: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
        16: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:107:in `run'
        15: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:107:in `each'
        14: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:108:in `block in run'
        13: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:108:in `loop'
        12: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:109:in `block (2 levels) in run'
        11: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:262:in `fetch_provisioning_profile'
        10: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/generator.rb:103:in `generate_provisioning_profile'
         9: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/manager.rb:8:in `start'
         8: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:26:in `run'
         7: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:108:in `fetch_profiles'
         6: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:108:in `find_all'
         5: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:108:in `each'
         4: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:126:in `block in fetch_profiles'
         3: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:126:in `each'
         2: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:130:in `block (2 levels) in fetch_profiles'
         1: from /Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:349:in `write': "\x82" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
        34: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
        33: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
        32: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
        31: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
        30: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
        29: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
        28: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:86:in `parse_and_execute_command'
        27: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:123:in `handle_action_command'
        26: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:176:in `process_action_command'
        25: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server.rb:181:in `execute_action_command'
        24: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:42:in `execute'
        23: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:73:in `run'
        22: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        21: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        20: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        19: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        18: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        17: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
        16: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:107:in `run'
        15: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:107:in `each'
        14: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:108:in `block in run'
        13: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:108:in `loop'
        12: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:109:in `block (2 levels) in run'
        11: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/runner.rb:262:in `fetch_provisioning_profile'
        10: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/match/lib/match/generator.rb:103:in `generate_provisioning_profile'
         9: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/manager.rb:8:in `start'
         8: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:26:in `run'
         7: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:108:in `fetch_profiles'
         6: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:108:in `find_all'
         5: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:108:in `each'
         4: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:126:in `block in fetch_profiles'
         3: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:126:in `each'
         2: from /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/fastlane-2.156.1/sigh/lib/sigh/runner.rb:130:in `block (2 levels) in fetch_profiles'
         1: from /Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:349:in `write': [!] "\x82" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.6                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
	override init() {
		super.init()
		updateFastlane(nightly: true)
	}

	func pipeLane(withOptions options:[String: String]?) {
		updateLane(withOptions: options)
		ipaLane(withOptions: options)
		deployLane(withOptions: options)
		commitLane(withOptions: options)
		maketagLane(withOptions: options)
		sentryLane(withOptions: options)
	}

	func updateLane(withOptions options:[String: String]?) {
		sh(command: "pod install")
		sh(command: "carthage update --platform iOS")
	}

	func ipaLane(withOptions options:[String: String]?) {
		let env = Env.instance(by: options)
		incrementBuildNumber(xcodeproj: xcodeproj)
		match(
			type: env.sign,
			readonly: false,
			appIdentifier: [env.identifier],
			teamId: teamID,
			forceForNewDevices: true
		)
		updateCodeSigningSettings(
			path: xcodeproj,
			teamId: teamID,
			codeSignIdentity: "iPhone Distribution",
			profileName: "${sigh_\(env.identifier)_\(env.sign)}"
		)
		buildApp(
			workspace: workspace, 
			scheme: Config.scheme,
			clean: true,
			outputDirectory: "./output",
			configuration: env.config,
			exportMethod: env.export,
            xcargs: "FLUTTER_BUILD_MODE=release"
		) 
		automaticCodeSigning(
			path: xcodeproj,
			useAutomaticSigning: true,
			codeSignIdentity: "iPhone Developer"
		)
	}

	func deployLane(withOptions options:[String: String]?) {
		let env = Env.instance(by: options)
		guard env.export == ExportType.appstore.rawValue else {
			var changelog = ""
			if !env.commitId.isEmpty {
				changelog = changelogFromGitCommits(
					between: ["\(env.commitId)", "HEAD"],
					pretty: "- (%an) %s"
				)
			}
			pgyer(
				apiKey: pgyer_api_key,
				userKey: pgyer_user_key,
				ipa: "./output/\(Config.scheme).ipa",
				password: "1",
				updateDescription: changelog,
				installType: "2"
				)
			return
		}
		deliver(
				appVersion: env.version,
				ipa: "./output/\(Config.scheme).ipa",
				skipBinaryUpload: false,
				skipScreenshots: true,
				skipMetadata: true,
				force: true,
				submitForReview: false,
				automaticRelease: false,
                precheckIncludeInAppPurchases: false
			)
	}

	func commitLane(withOptions options:[String: String]?) {
		let env = Env.instance(by: options)
		gitPull()
		gitAdd(path: "./")
		gitCommit(path: "./", message: "- [fastlane] \(env.version)(Build \(env.buildNum))")
		pushToGitRemote()
	}

	func maketagLane(withOptions options:[String: String]?) {
		let env = Env.instance(by: options)
		let tagName = "\(Config.scheme)/\(env.version)/\(env.sign)-\(env.buildNum)"
		sh(command: "git tag -d $(git tag -l | grep \(tagName))")
		sh(command: "git push origin :refs/tags/\(tagName)")
		addGitTag(
			tag: tagName, 
			grouping: env.config,
			buildNumber: env.buildNum,
			message: "- [fastlane] auto make tag"
		)
		sh(command: "git push --tags origin")
	}

	func sentryLane(withOptions options:[String: String]?) {
		let env = Env.instance(by: options)
		var projectSlug = ProjectSlug.prod.rawValue
		if env.export != ExportType.appstore.rawValue {
			projectSlug = ProjectSlug.dev.rawValue
		}
		uploadSymbolsToSentry(
			authToken: SENTRY_TOKEN, 
			orgSlug: "sentry", 
			projectSlug: projectSlug, 
			dsymPath: "./output/\(Config.scheme).app.dSYM.zip"
		)
		// plugin("sentry_upload_dsym", args: [
		// 	"auth_token": SENTRY_TOKEN,
		// 	"org_slug": "sentry",
		// 	"project_slug": projectSlug,
		// 	"dsym_path": "./output/\(Config.scheme).app.dSYM.zip"
		// ])
	}
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.156.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-pgyer  | 0.2.2   | ✅ Up-To-Date  |
| fastlane-plugin-sentry | 1.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-firim  | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.3       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.355.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.78.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.3        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| cocoapods                 | 1.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.1        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.27.0       |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| firim                     | 0.2.5        |
| fastlane-plugin-firim     | 0.2.2        |
| fastlane-plugin-pgyer     | 0.2.2        |
| fastlane-plugin-sentry    | 1.6.0        |
| http-accept               | 1.7.0        |
| mime-types-data           | 3.2020.0512  |
| mime-types                | 3.3.1        |
| rest-client               | 2.1.0        |
</details>

*generated on:* **2020-08-24**
</details>

**Comment by philCc** [comment]
fixed by:
`fastlane match adhoc`
