### ISSUE TITLE
[supply] undefined method `map' for nil:NilClass on "draft" tracks

### ISSUE THREAD

**Issue by bezigon** [fastlane/fastlane#17086]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

1. Create a **draft** version in alpha track
2. Run command
3. How to handle this error?

##### Command executed

    track = "alpha"
    version_code = google_play_track_version_codes(track: track).sort.last
    upload_to_play_store(
        track: track,
        metadata_path: "./metadata",
        skip_upload_apk: true,
        skip_upload_aab: true,
        version_code: version_code,
      )
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>2020-08-24T13:36:14.2459390Z bundler: failed to load command: fastlane (/Users/Agent/.gems/bin/fastlane)
2020-08-24T13:36:14.2462270Z NoMethodError: [31m[!] undefined method `map' for nil:NilClass[0m
2020-08-24T13:36:14.2463700Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:114:in `block in fetch_track_and_release!'
2020-08-24T13:36:14.2465220Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:114:in `select'
2020-08-24T13:36:14.2466520Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:114:in `fetch_track_and_release!'
2020-08-24T13:36:14.2467930Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:84:in `block in perform_upload_meta'
2020-08-24T13:36:14.2468920Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:81:in `each'
2020-08-24T13:36:14.2469750Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:81:in `perform_upload_meta'
2020-08-24T13:36:14.2470670Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:32:in `perform_upload'
2020-08-24T13:36:14.2471650Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
2020-08-24T13:36:14.2472530Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
2020-08-24T13:36:14.2473480Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
2020-08-24T13:36:14.2474340Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
2020-08-24T13:36:14.2475760Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
2020-08-24T13:36:14.2476630Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
2020-08-24T13:36:14.2477460Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
2020-08-24T13:36:14.2478310Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2020-08-24T13:36:14.2479080Z   Fastfile:36:in `block (2 levels) in parsing_binding'
2020-08-24T13:36:14.2479780Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane.rb:33:in `call'
2020-08-24T13:36:14.2480560Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
2020-08-24T13:36:14.2481410Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
2020-08-24T13:36:14.2482200Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
2020-08-24T13:36:14.2482990Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
2020-08-24T13:36:14.2483890Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
2020-08-24T13:36:14.2485120Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
2020-08-24T13:36:14.2486040Z   /Users/Agent/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-08-24T13:36:14.2487050Z   /Users/Agent/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-08-24T13:36:14.2488010Z   /Users/Agent/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-08-24T13:36:14.2488940Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-08-24T13:36:14.2489910Z   /Users/Agent/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-08-24T13:36:14.2490780Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
2020-08-24T13:36:14.2491610Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
2020-08-24T13:36:14.2492520Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
2020-08-24T13:36:14.2493310Z   /Users/Agent/.gems/gems/fastlane-2.154.0/bin/fastlane:23:in `<top (required)>'
2020-08-24T13:36:14.2493940Z   /Users/Agent/.gems/bin/fastlane:23:in `load'
2020-08-24T13:36:14.2494620Z   /Users/Agent/.gems/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.7.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.26.2                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.6                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Upload sort of (changelogs|metadata|screenshots|all) to the Google Play"
  lane :upload do |options|
    track = "alpha"
    version_code = google_play_track_version_codes(track: track).sort.last
    params = {
      track: track,
      metadata_path: "./metadata",
      skip_upload_apk: true,
      skip_upload_aab: true,
      version_code: version_code,
      validate_only: true,
    }
    case options[:method]
    when nil, "all"
      upload_to_play_store(params)
    when "changelogs", "metadata", "screenshots"
      upload_to_play_store(
        params.merge({
          skip_upload_changelogs: options[:method] != "changelogs",
          skip_upload_metadata: options[:method] != "metadata",
          skip_upload_images: options[:method] != "screenshots",
          skip_upload_screenshots: options[:method] != "screenshots",
        })
      )
    else
      raise "unknown method \"#{options[:method]}\""
    end
  end

  error do |lane, exception|
    if ENV["SLACK_URL"]
      slack(
        message: exception.to_s,
        success: false
      )
    end
  end

end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.156.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| bundler                   | 2.1.4        |
| uri                       | 0.10.0       |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.356.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.78.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| coderay                   | 1.1.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.27.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| method_source             | 1.0.0        |
| pry                       | 0.13.1       |
</details>

*generated on:* **2020-08-25**
</details></pre>
</details>

**Comment by long1eu** [comment]
I also have this when uploading to app_store.

```
2020-08-27T06:38:59.5711810Z ▌14:38:57▐ RUNNING: cd mobile/ios; ../../bundle exec fastlane run upload_to_app_store force:true ipa:/Users/admin/actions-runner/_work/yitnow/yitnow/mobile/build/ios/iphoneos/Runner_appstore_prod.ipa
2020-08-27T06:39:00.3963320Z /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
2020-08-27T06:39:00.3964350Z /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
2020-08-27T06:39:00.5302040Z [14:39:00]: [32m---------------------------------[0m
2020-08-27T06:39:00.5302710Z [14:39:00]: [32m--- Step: upload_to_app_store ---[0m
2020-08-27T06:39:00.5303210Z [14:39:00]: [32m---------------------------------[0m
2020-08-27T06:39:00.5303470Z [14:39:00]: Login to App Store Connect (razvan@upcode.dev)
2020-08-27T06:39:02.8464910Z [14:39:02]: Login successful
2020-08-27T06:39:05.8498160Z 
2020-08-27T06:39:05.8539080Z +--------------------------------------+----------------------------------------------------------------------------------------------------+
2020-08-27T06:39:05.8540740Z |                                                          [32mdeliver 2.156.1 Summary[0m                                                          |
2020-08-27T06:39:05.8542250Z +--------------------------------------+----------------------------------------------------------------------------------------------------+
2020-08-27T06:39:05.8542910Z | force                                | true                                                                                               |
2020-08-27T06:39:05.8544180Z | ipa                                  | /Users/admin/actions-runner/_work/yitnow/yitnow/mobile/build/ios/iphoneos/Runner_appstore_prod.ipa |
2020-08-27T06:39:05.8544890Z | app_identifier                       | com.yitnow.yitnow                                                                                  |
2020-08-27T06:39:05.8545490Z | screenshots_path                     | ./fastlane/screenshots                                                                             |
2020-08-27T06:39:05.8546550Z | metadata_path                        | ./fastlane/metadata                                                                                |
2020-08-27T06:39:05.8547200Z | app_version                          | 1.3.2                                                                                              |
2020-08-27T06:39:05.8547850Z | username                             | razvan@upcode.dev                                                                                  |
2020-08-27T06:39:05.8549110Z | platform                             | ios                                                                                                |
2020-08-27T06:39:05.8549750Z | edit_live                            | false                                                                                              |
2020-08-27T06:39:05.8550350Z | use_live_version                     | false                                                                                              |
2020-08-27T06:39:05.8550970Z | skip_binary_upload                   | false                                                                                              |
2020-08-27T06:39:05.8551430Z | skip_screenshots                     | false                                                                                              |
2020-08-27T06:39:05.8551790Z | skip_metadata                        | false                                                                                              |
2020-08-27T06:39:05.8552140Z | skip_app_version_update              | false                                                                                              |
2020-08-27T06:39:05.8552500Z | overwrite_screenshots                | false                                                                                              |
2020-08-27T06:39:05.8552840Z | submit_for_review                    | false                                                                                              |
2020-08-27T06:39:05.8553200Z | reject_if_possible                   | false                                                                                              |
2020-08-27T06:39:05.8553540Z | automatic_release                    | false                                                                                              |
2020-08-27T06:39:05.8553890Z | phased_release                       | false                                                                                              |
2020-08-27T06:39:05.8554250Z | reset_ratings                        | false                                                                                              |
2020-08-27T06:39:05.8554640Z | team_id                              | 121818504                                                                                          |
2020-08-27T06:39:05.8555030Z | dev_portal_team_id                   | F3Z67HQL83                                                                                         |
2020-08-27T06:39:05.8555420Z | run_precheck_before_submit           | true                                                                                               |
2020-08-27T06:39:05.8555790Z | precheck_default_rule_level          | warn                                                                                               |
2020-08-27T06:39:05.8556150Z | ignore_language_directory_validation | false                                                                                              |
2020-08-27T06:39:05.8556510Z | precheck_include_in_app_purchases    | true                                                                                               |
2020-08-27T06:39:05.8557440Z +--------------------------------------+----------------------------------------------------------------------------------------------------+
2020-08-27T06:39:05.8557530Z 
2020-08-27T06:39:05.8558070Z [14:39:05]: Making sure the latest version on App Store Connect matches '1.3.2'...
2020-08-27T06:40:17.7888270Z 
2020-08-27T06:40:17.7889060Z Looking for related GitHub issues on fastlane/fastlane...
2020-08-27T06:40:17.7889190Z 
2020-08-27T06:40:20.4032970Z ➡️  [33mNoMethodError: [!] undefined method `status' for nil:NilClass[0m
2020-08-27T06:40:20.4033620Z     https://github.com/fastlane/fastlane/issues/17066 [[31mopen[0m] 5 💬
2020-08-27T06:40:20.4036670Z     a day ago
2020-08-27T06:40:20.4036850Z 
2020-08-27T06:40:20.4038130Z ➡️  [33m[!] undefined method `any?' for nil:NilClass (NoMethodError)[0m
2020-08-27T06:40:20.4040000Z     https://github.com/fastlane/fastlane/issues/17048 [[31mopen[0m] 10 💬
2020-08-27T06:40:20.4040330Z     2 weeks ago
2020-08-27T06:40:20.4040440Z 
2020-08-27T06:40:20.4041500Z ➡️  [33m[supply] undefined method `map' for nil:NilClass on "draft" tracks[0m
2020-08-27T06:40:20.4042440Z     https://github.com/fastlane/fastlane/issues/17086 [[31mopen[0m] 0 💬
2020-08-27T06:40:20.4043030Z bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.7.0/bin/fastlane)
2020-08-27T06:40:20.4043960Z NoMethodError: [31m[!] undefined method `status' for nil:NilClass[0m
2020-08-27T06:40:20.4044910Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/spaceship/lib/spaceship/connect_api/client.rb:151:in `handle_response'
2020-08-27T06:40:20.4045820Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/spaceship/lib/spaceship/connect_api/client.rb:110:in `patch'
2020-08-27T06:40:20.4046810Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:742:in `patch_app_store_version'
2020-08-27T06:40:20.4047760Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:90:in `update'
2020-08-27T06:40:20.4048550Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/spaceship/lib/spaceship/connect_api/models/app.rb:171:in `ensure_version!'
2020-08-27T06:40:20.4049080Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/deliver/lib/deliver/runner.rb:97:in `verify_version'
2020-08-27T06:40:20.4049580Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/deliver/lib/deliver/runner.rb:36:in `run'
2020-08-27T06:40:20.4050100Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
2020-08-27T06:40:20.4050640Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
2020-08-27T06:40:20.4051180Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
2020-08-27T06:40:20.4051710Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
2020-08-27T06:40:20.4052210Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
2020-08-27T06:40:20.4052720Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
2020-08-27T06:40:20.4053220Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/one_off.rb:42:in `run'
2020-08-27T06:40:20.4053720Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
2020-08-27T06:40:20.4054260Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
2020-08-27T06:40:20.4054770Z   /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-08-27T06:40:20.4055250Z   /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-08-27T06:40:20.4055770Z   /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-08-27T06:40:20.4056310Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-08-27T06:40:20.4056820Z   /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-08-27T06:40:20.4057950Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
2020-08-27T06:40:20.4058470Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
2020-08-27T06:40:20.4058980Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
2020-08-27T06:40:20.4059740Z   /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.156.1/bin/fastlane:23:in `<top (required)>'
2020-08-27T06:40:20.4060240Z   /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
2020-08-27T06:40:20.4060670Z   /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<top (required)>'
2020-08-27T06:40:20.4060820Z     a day ago
2020-08-27T06:40:20.4060900Z 
2020-08-27T06:40:20.4061590Z and 271 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60status%27%20for%20nil&type=Issues&utf8=✓
2020-08-27T06:40:20.4061730Z 
2020-08-27T06:40:20.4062250Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
2020-08-27T06:40:20.4284440Z ▌14:40:20▐ ELAPSED TIME: 1min 22.730s for ../../bundle exec fastlane run upload_to_app_store force:true ipa:/Users/admin/actions-runner/_work/yitnow/yitnow/mobile/build/ios/iphoneos/Runner_appstore_prod.ipa in mobile/ios
2020-08-27T06:40:20.4285110Z ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2020-08-27T06:40:20.4285410Z ERROR: Last command exited with 1 (expected: zero).
2020-08-27T06:40:20.4286190Z Command: ../../bundle exec fastlane run upload_to_app_store force:true ipa:/Users/admin/actions-runner/_work/yitnow/yitnow/mobile/build/ios/iphoneos/Runner_appstore_prod.ipa
2020-08-27T06:40:20.4286400Z Relative working directory: mobile/ios
2020-08-27T06:40:20.4286880Z ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
