### ISSUE TITLE
Match should also take into account FASTLANE_SESSION when checking for certificates validity

### ISSUE THREAD

**Issue by TPXP** [fastlane/fastlane#17177]
🔑 

### New Issue Checklist

- [x] Updated fastlane to the latest version - same issue with the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm running match as part of my CI process to compile my app (fastlane is a real lifesaver btw, thanks so much ❤️). It seems that the recent addition of the certificate validity check broke my process, as `match` now asks for my AppleID password:
```
 [07:47:14]: 🔓  Successfully decrypted certificates repo
[07:47:14]: You can also run `fastlane match` in readonly mode to not require any access to the
[07:47:14]: Developer Portal. This way you only share the keys and credentials
[07:47:14]: $ fastlane match --readonly
[07:47:14]: More information https://docs.fastlane.tools/actions/match/#access-control
[07:47:14]: Verifying that the certificate and profile are still valid on the Dev Portal...
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
+---------------+------+
|     Lane Context     |
+---------------+------+
| PLATFORM_NAME |      |
| LANE_NAME     | keys |
+---------------+------+
[07:47:14]: Missing password for user ***, and running in non-interactive shell
```
I'm fine with running match in readonly mode as a workaround, but I think we should also provide the possibility to pass the `FASTLANE_SESSION` env variable so that match can also check the keys against the app store directly, as done in other parts (like uploading to TestFlight). For now, the code does not seem to allow that
https://github.com/fastlane/fastlane/blob/39ce1dd6d7b609a559c8fec561d34a36cb52d187/match/lib/match/spaceship_ensure.rb#L12-L14

##### Command executed
Here's a part of my CI script:
```
bundle exec fastlane run create_keychain password:$MATCH_KEYCHAIN_PASSWORD default_keychain:true name:$MATCH_KEYCHAIN_NAME timeout:false unlock:true
bundle exec fastlane keys
```
Env variables: MATCH_GIT_PRIVATE_KEY, MATCH_PASSWORD, MATCH_KEYCHAIN_PASSWORD, MATCH_KEYCHAIN_NAME

`MatchFile`:
```rb
git_url("git@github.com:****/****")

storage_mode("git")

type("appstore") # The default type, can be: appstore, adhoc, enterprise or development

app_identifier(["****"])
username("***@***.**") # Your Apple Developer Portal username

# For all available options run `fastlane match --help`
# Remove the # in the beginning of the line to enable the other options

# The docs are available on https://docs.fastlane.tools/actions/match
```

##### Complete output when running fastlane, including the stack trace and command used
```
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.6.0/bin/fastlane)
RuntimeError: [!] Missing password for user ***, and running in non-interactive shell
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/client.rb:377:in `login'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/client.rb:349:in `login'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/match/lib/match/spaceship_ensure.rb:22:in `initialize'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/match/lib/match/runner.rb:70:in `new'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/match/lib/match/runner.rb:70:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:8:in `block in parsing_binding'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.157.2/bin/fastlane:23:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<top (required)>'
```

### Environment
* Github actions runner, with `macos-latest` as the OS

**Comment by TPXP** [comment]
I believe this is still an issue, it could be solved in my case if match supported app store connect api keys.

**Comment by rogerluan** [comment]
> I believe this is still an issue, it could be solved in my case if match supported app store connect api keys.

In that case, would you mind testing my PR? :) https://github.com/fastlane/fastlane/pull/17390
