### ISSUE TITLE
match is not working

### ISSUE THREAD

**Issue by figengungor** [fastlane/fastlane#17287]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I run any match command I get the following error: 
 Could not find option 'certificates' in the list of available options: ...
##### Command executed

Any fastlane match command gives this response
fastlane match nuke development or fastlane match --verbose

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>  fastlane match --verbose
[✔] 🚀 
[15:51:05]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/figengungor/my_app/ios/fastlane/Appfile'
- app_identifier: 'com.blah.myapp'
- apple_id: 'blah@me.com'
- itc_team_name: 'Blah Blah'
-------
Traceback (most recent call last):
        17: from /usr/local/bin/fastlane:23:in `<main>'
        16: from /usr/local/bin/fastlane:23:in `load'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/bin/fastlane:23:in `<top (required)>'
        14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/match/lib/match/commands_generator.rb:25:in `start'
        12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/match/lib/match/commands_generator.rb:187:in `run'
        11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/match/lib/match/commands_generator.rb:52:in `block (2 levels) in run'
         5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:180:in `load_configuration_file'
         4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:180:in `each'
         3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:181:in `block in load_configuration_file'
         2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:328:in `verify_options_key!'
         1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Could not find option 'certificates' in the list of available options: type, additional_cert_types, readonly, generate_apple_certs, skip_provisioning_profiles, app_identifier, username, team_id, team_name, storage_mode, git_url, git_branch, git_full_name, git_user_email, shallow_clone, clone_branch_directly, git_basic_authorization, git_bearer_authorization, git_private_key, google_cloud_bucket_name, google_cloud_keys_file, google_cloud_project_id, s3_region, s3_access_key, s3_secret_access_key, s3_bucket, s3_object_prefix, keychain_name, keychain_password, force, force_for_new_devices, skip_confirmation, skip_docs, platform, derive_catalyst_app_identifier, template_name, profile_name, fail_on_name_taken, output_path, verbose (FastlaneCore::Interface::FastlaneError)
        17: from /usr/local/bin/fastlane:23:in `<main>'
        16: from /usr/local/bin/fastlane:23:in `load'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/bin/fastlane:23:in `<top (required)>'
        14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/match/lib/match/commands_generator.rb:25:in `start'
        12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/match/lib/match/commands_generator.rb:187:in `run'
        11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/match/lib/match/commands_generator.rb:52:in `block (2 levels) in run'
         5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:180:in `load_configuration_file'
         4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:180:in `each'
         3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:181:in `block in load_configuration_file'
         2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:328:in `verify_options_key!'
         1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Could not find option 'certificates' in the list of available options: type, additional_cert_types, readonly, generate_apple_certs, skip_provisioning_profiles, app_identifier, username, team_id, team_name, storage_mode, git_url, git_branch, git_full_name, git_user_email, shallow_clone, clone_branch_directly, git_basic_authorization, git_bearer_authorization, git_private_key, google_cloud_bucket_name, google_cloud_keys_file, google_cloud_project_id, s3_region, s3_access_key, s3_secret_access_key, s3_bucket, s3_object_prefix, keychain_name, keychain_password, force, force_for_new_devices, skip_confirmation, skip_docs, platform, derive_catalyst_app_identifier, template_name, profile_name, fail_on_name_taken, output_path, verbose (FastlaneCore::Interface::FastlaneError)</pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.6                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "no-way"
  end
  
  lane :releaseFirst do
    produce(
      username: 'blah@me.com',
      app_identifier: 'com.blah.myapp',
      app_name: 'My App',
      language: 'English',
      app_version: '1.0.0',
      sku: 'blahblah',
      team_name: 'Blah Blah',
      enable_services: {
        push_notification: "on"       # Valid values: "on", "off"
      }
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  desc "Push a new build to app store connect"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store                  # upload your app to App Store Connect
  end

  desc "Just send updated metadata to app store"
    lane :metadata do
      deliver(
      skip_screenshots: true, skip_binary_upload: true,
      )    
  end

  desc "Just send updated screenshots to app store"
      lane :screenshots do
        deliver(
        skip_metadata: true, skip_binary_upload: true
        )
  end

  lane :submit_review do
    deliver(
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end

  lane :first_submit_review do
      deliver(
        build_app(workspace: "Runner.xcworkspace", scheme: "Runner"),
        submit_for_review: true,
        automatic_release: true,
        force: true, # Skip HTMl report verification
      )
   end
    
  lane :just_generate_ipa do
       build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
  end 
   
  lane :deliver_trial do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    deliver(
      submit_for_review: false,
      automatic_release: false,
      force: true, # Skip HTMl report verification
    )
  end
  
  lane :deliver_download_metadata do
    ENV["DELIVER_FORCE_OVERWRITE"] = "1"
    sh "fastlane deliver download_metadata"
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.blah.myapp"
apple_id "blah@me.com"
itc_team_name "Blah Blah"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.371.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.0       |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| google-cloud-env          | 1.3.3        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-21**
</details> </pre>
</details>

**Comment by figengungor** [comment]
This is is solved on my side. The issue was I just copy pasted example content of Matchfile in the docs(https://docs.fastlane.tools/actions/match/). It was missing  storage_mod git part.
