### ISSUE TITLE
Match failed to download certificates within CircleCi var directory

### ISSUE THREAD

**Issue by LamourBt** [fastlane/fastlane#17308]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Match is failing when cloning the repo despite using a valid auth token. 

##### Command executed

Currently, Fastlane is being executed within Circle-Ci via command 
`bundle exec fastlane build  --env confs --verbose`

Then the code below is being executed within the Fastlane lane
```
personal_token = ENV["PERSONAL_GITHUB_ACCESS_TOKEN"] #options[:token]
username = ENV["USERNAME"] #options[:username]
auth_token = Base64.strict_encode64("#{username}:#{personal_token}")
  	
    match(
    	git_basic_authorization: auth_token,
    	type: "development",
    	app_identifier: app_identifiers(),
    	readonly: true,
    	verbose:true
    )
```

After replacing the tmp destination path, I was able to run the command that match asked to verified. 
`git clone <private> ~/Desktop/certs/ -c http.extraheader='Authorization: Basic <token>`

##### Complete output when running fastlane, including the stack trace and command used

```
ERROR [2020-09-23 17:06:02.57]: Exit status: 128
ERROR [2020-09-23 17:06:02.57]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
ERROR [2020-09-23 17:06:02.57]: Run the following command manually to make sure you're properly authenticated:
INFO [2020-09-23 17:06:02.57]: $ git clone <private> /var/folders/pt/0xykrh9j62g34sc7znh47kbc0000gn/T/d20200923-2318-g47nq8 -c http.extraheader='Authorization: Basic <token>'
```

```
ERROR [2020-09-23 17:06:02.97]: fastlane finished with errors
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Error cloning certificates git repo, please make sure you have access to the repository - see instructions above
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/match/lib/match/storage/git_storage.rb:121:in `rescue in download'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/match/lib/match/storage/git_storage.rb:107:in `download'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/match/lib/match/runner.rb:60:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:73:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details>
  <pre> Installing fastlane 2.160.0 </pre>
</details>

**Comment by LamourBt** [comment]
Using [Adding a User key to CircleCi Project](https://circleci.com/docs/2.0/ios-codesigning/#adding-a-user-key-to-the-circleci-project) solve the issue.
