### ISSUE TITLE
repairing a provisioning profile with 'fastlane sigh' ends with a spaceship error

### ISSUE THREAD

**Issue by Qwix** [fastlane/fastlane#17428]
**Summary:** I am trying to use fastlane sigh to update and then download an invalid appstore provisioning profile using a newly created distribution certificate.  I am getting an error ```/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:306:in `block in certificates_to_use': undefined method `owner_name' for #<Spaceship::ConnectAPI::Certificate:0x00007fc3c198c5b0> (NoMethodError)```

**Expected result:** The provisioning profile is updated on the developer portal to use the new distribution certificate and is then downloaded to my local machine.

**Actual result:** The command results in an error ```/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:306:in `block in certificates_to_use': undefined method `owner_name' for #<Spaceship::ConnectAPI::Certificate:0x00007fc3c198c5b0> (NoMethodError)```

**Input:** 
`fastlane sigh --username <username> --team_id <team_id> --app_identifier <app_identifier> --provisioning_name <profile_name> --ignore_profiles_with_different_name true --cert_owner_name "<cert_owner>" --force`

**Output:** 
```
[:heavy_check_mark:] :rocket: 
[15:29:38]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+-------------------------------------+-------------------------------------------------------+
|                 Summary for sigh 2.162.0                  |
+-------------------------------------+-------------------------------------------------------+
| username						| <username>		|
| team_id						| <team_id>		|
| app_identifier					| <app_identifier>	|
| provisioning_name					| <profile_name>	|
| ignore_profiles_with_different_name			| true			|
| cert_owner_name					| <cert_owner>		|
| force							| true			|
| adhoc							| false			|
| developer_id						| false			|
| development						| false			|
| skip_install						| false			|
| skip_fetch_profiles					| false			|
| skip_certificate_verification				| false			|
| platform						| ios			|
| readonly						| false			|
| fail_on_name_taken					| false			|
+-------------------------------------+-------------------------------------------------------+

[15:29:39]: Starting login with user '<username>'
Available session is not valid any more. Continuing with normal login.
[15:29:41]: Successfully logged in
[15:29:41]: Fetching profiles...
[15:29:42]: Verifying certificates...
[15:29:42]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[15:29:50]: Creating new provisioning profile for '<app_identifier>' with name '<profile_name>' for 'ios' platform

Looking for related GitHub issues on fastlane/fastlane...Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	18: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	17: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	16: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	9: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	8: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	7: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/manager.rb:8:in `start'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:48:in `run'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:300:in `certificates_to_use'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:300:in `find_all'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:300:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:306:in `block in certificates_to_use': undefined method `owner_name' for #<Spaceship::ConnectAPI::Certificate:0x00007fc3c198c5b0> (NoMethodError)
	18: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	17: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	16: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	9: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	8: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	7: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/manager.rb:8:in `start'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:48:in `run'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:300:in `certificates_to_use'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:300:in `find_all'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:300:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/sigh/lib/sigh/runner.rb:306:in `block in certificates_to_use': [!] undefined method `owner_name' for #<Spaceship::ConnectAPI::Certificate:0x00007fc3c198c5b0> (NoMethodError)
```

Output of 'fastlane env' here:
```
<details><summary>:white_check_mark: fastlane environment :white_check_mark:</summary>
### Stack
| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.4                                          |
| Ruby                        | 2.6.1                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.20.1 (Apple Git-117)               |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane      |
| Host                        | Mac OS X 10.14.4 (18E226)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-10_2.app/Contents/Developer/ |
| Xcode Version               | 10.2                                             |

### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | :white_check_mark: |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:
*No Fastfile found*
*No Appfile found*

### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | :white_check_mark: Up-To-Date  |

### Loaded fastlane plugins:
*No plugins Loaded*

<details><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.380.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |

</details>
generated on: *2020-10-12*
</details>
```

**Comment by rogerluan** [comment]
The reason behind this is that in this line (the offending line):

https://github.com/fastlane/fastlane/blob/4753b8dea25c9f9d9b7fc49101b4ee1e4590cb80/sigh/lib/sigh/runner.rb#L306

We used to use `spaceship/lib/spaceship/portal/certificate.rb` and now we're using `spaceship/lib/spaceship/connect_api`, and the later doesn't have any reference to the owner of the certificate (e.g. `owner_type` or `owner_name`) like the old model used to have. 

I investigated briefly and looks like the new App Store Connect API doesn't offer an "owner name" attribute (or anything associated to the owner) 😕 I could be wrong, but that's what I found in a first glance.

Not sure how to solve this, or if it's even possible to solve this. @joshdholtz any thoughts?

@Qwix you could easily work around this issue by omitting the `--cert_owner_name "<cert_owner>"` in your command. Is this something that would work for you? Please let me know 🙏

**Comment by Qwix** [comment]
Thanks for the reply @rogerluan .  Unfortunately that gives the same error :(
It fails right after the line `[23:10:16]: Available Code Signing Identities for current filters:`
I am happy to keep trying if you have other suggestions though!

**Input:** 
`fastlane sigh --username <username> --team_id <team_id> --app_identifier <application_identifier> --provisioning_name <profile_name> --ignore_profiles_with_different_name true --force`

**Output:**
```
[:heavy_check_mark:] :rocket: 
[23:09:43]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-------------------------------------+-------------------------------------------------------+
|                 Summary for sigh 2.163.0                  |
+-------------------------------------+-------------------------------------------------------+
| username						| <username>		|
| team_id						| <team_id>		|
| app_identifier					| <app_identifier>	|
| provisioning_name					| <profile_name>	|
| ignore_profiles_with_different_name			| true			|
| force							| true			|
| adhoc							| false			|
| developer_id						| false			|
| development						| false			|
| skip_install						| false			|
| skip_fetch_profiles					| false			|
| skip_certificate_verification				| false			|
| platform						| ios			|
| readonly						| false			|
| fail_on_name_taken					| false			|
+-------------------------------------+-------------------------------------------------------+

[23:09:44]: Starting login with user '<username>'
Available session is not valid any more. Continuing with normal login.
[23:09:55]: Successfully logged in
[23:09:55]: Fetching profiles...
[23:09:56]: Verifying certificates...
[23:09:56]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[23:10:03]: Creating new provisioning profile for '<application_identifier>' with name '<profile_name>' for 'ios' platform
[23:10:16]: Found more than one code signing identity. Choosing the first one. Check out `fastlane sigh --help` to see all available options.
[23:10:16]: Available Code Signing Identities for current filters:

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	17: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	16: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/bin/fastlane:23:in `<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	9: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	8: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	7: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/manager.rb:8:in `start'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:48:in `run'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:329:in `certificates_to_use'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:329:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:330:in `block in certificates_to_use': undefined method `owner_name' for #<Spaceship::ConnectAPI::Certificate:0x00007fe0f476d8d8> (NoMethodError)
	17: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	16: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/bin/fastlane:23:in `<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	9: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	8: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	7: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/manager.rb:8:in `start'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:48:in `run'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:329:in `certificates_to_use'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:329:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.163.0/sigh/lib/sigh/runner.rb:330:in `block in certificates_to_use': [!] undefined method `owner_name' for #<Spaceship::ConnectAPI::Certificate:0x00007fe0f476d8d8> (NoMethodError)
```

**Comment by joshdholtz** [comment]
Will look into today and report back!

**Comment by addbrick** [comment]
@joshdholtz I think I figured it out. `owner_name` was removed, I added a helper to concat `requester_first_name` and `requester_last_name` which I believe is the equivalent. See https://github.com/fastlane/fastlane/pull/17432

**Comment by joshdholtz** [comment]
Oh perfect! I will give that a review 😊 Thank you!

**Comment by mtr1012** [comment]
Please fix thisssssssss :(

**Comment by mtr1012** [comment]
You can hotfix by manual create adhoc profile and remove force:true in sigh command @Qwix Q

**Comment by IoT-Tobi** [comment]
After updating to fastlane 2.165.0 I've tried to sign again and unfortunately I get an similar error.
Now it says undefined method "expires"...

`[08:23:20]: Your Apple ID Username: <username>
[08:26:59]: Starting login with user '<username>'
[08:27:01]: Successfully logged in
[08:27:01]: Fetching profiles...
[08:27:02]: To not be asked about this value, you can specify it using 'app_identifier'
/usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[08:27:02]: The bundle identifier of your app: <app_identifier> 
[08:31:05]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[08:31:06]: Creating new provisioning profile for '<app_identifier>' with name '<app_identifier> AppStore' for 'ios' platform
[08:31:07]: Found more than one code signing identity. Choosing the first one. Check out `fastlane sigh --help` to see all available options.
[08:31:07]: Available Code Signing Identities for current filters:

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	17: from /usr/local/bin/fastlane:23:in `<main>'
	16: from /usr/local/bin/fastlane:23:in `load'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/bin/fastlane:23:in `<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/manager.rb:8:in `start'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:48:in `run'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:329:in `certificates_to_use'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:329:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:330:in `block in certificates_to_use': undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9303a1bb28> (NoMethodError)
	17: from /usr/local/bin/fastlane:23:in `<main>'
	16: from /usr/local/bin/fastlane:23:in `load'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/bin/fastlane:23:in `<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/manager.rb:8:in `start'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:48:in `run'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:329:in `certificates_to_use'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:329:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/sigh/lib/sigh/runner.rb:330:in `block in certificates_to_use': \e[31m[!] **undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9303a1bb28>\e[0m (NoMethodError)`**

**Comment by mtr1012** [comment]
Me same @IoT-Tobi

**Comment by mtr1012** [comment]
Please take a look on this @joshdholtz
