### ISSUE TITLE
Fastlane promote failed 

### ISSUE THREAD

**Issue by lpaulusLohr** [fastlane/fastlane#17434]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Problem on fastlane pipeline when promoting from TestFlight to Production using it with AzureDevops (AppStore Promote Task)

##### Command executed
```
fastlane deliver submit_build -u *** -a APP --skip_binary_upload true --skip_metadata true --skip_screenshots true --automatic_release --force --verbose
```

##### Complete output when running fastlane, including the stack trace and command used
```
2020-10-14T07:15:31.0834520Z INFO [2020-10-14 09:15:31.07]: Checking app for precheck rule violations
2020-10-14T07:15:44.7438290Z INFO [2020-10-14 09:15:44.74]: Reading in-app purchases. If you have a lot, this might take a while
2020-10-14T07:15:44.7440910Z INFO [2020-10-14 09:15:44.74]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
2020-10-14T07:15:45.2433920Z INFO [2020-10-14 09:15:45.23]: Done reading in-app purchases
2020-10-14T07:15:45.2535010Z ERROR [2020-10-14 09:15:45.23]: [31mfastlane precheck just tried to inspect your app's metadata for App Store guideline violations and ran into a problem. We're not sure what the problem was, but precheck failed to finished. You can run it in verbose mode if you want to see the whole error. We'll have a fix out soon 🚀[0m
2020-10-14T07:15:45.2648980Z DEBUG [2020-10-14 09:15:45.24]: #<NoMethodError: undefined method `copyright' for nil:NilClass>
2020-10-14T07:15:45.2751700Z DEBUG [2020-10-14 09:15:45.24]: /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/precheck/lib/precheck/rule_processor.rb:177:in `generate_version_items_to_check'
2020-10-14T07:15:45.2852240Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/precheck/lib/precheck/rule_processor.rb:48:in `process_app_and_version'
2020-10-14T07:15:45.2953850Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/precheck/lib/precheck/runner.rb:121:in `check_for_rule_violations'
2020-10-14T07:15:45.3055070Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/precheck/lib/precheck/runner.rb:47:in `run'
2020-10-14T07:15:45.3156500Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:101:in `precheck_app'
2020-10-14T07:15:45.3257910Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:63:in `run'
2020-10-14T07:15:45.3361130Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2020-10-14T07:15:45.3453770Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-10-14T07:15:45.3497080Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-10-14T07:15:45.3529820Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-10-14T07:15:45.3583990Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-10-14T07:15:45.3662550Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-10-14T07:15:45.3715450Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2020-10-14T07:15:45.3818080Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2020-10-14T07:15:45.3920630Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2020-10-14T07:15:45.4024430Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/bin/fastlane:23:in `<top (required)>'
2020-10-14T07:15:45.4078710Z /usr/local/bin/fastlane:23:in `load'
2020-10-14T07:15:45.4107480Z /usr/local/bin/fastlane:23:in `<main>'
2020-10-14T07:15:46.2227030Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [31m[!] Cannot submit for review - could not find an editable version for 'IOS'[0m (FastlaneCore::Interface::FastlaneError)
2020-10-14T07:15:46.2304360Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2020-10-14T07:15:46.2356800Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/submit_for_review.rb:16:in `submit!'
2020-10-14T07:15:46.2459660Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
2020-10-14T07:15:46.2562600Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:64:in `run'
2020-10-14T07:15:46.2660320Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2020-10-14T07:15:46.2705380Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-10-14T07:15:46.2775000Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-10-14T07:15:46.2779550Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-10-14T07:15:46.2897590Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-10-14T07:15:46.2913120Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-10-14T07:15:46.2938130Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2020-10-14T07:15:46.2952680Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2020-10-14T07:15:46.2979280Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2020-10-14T07:15:46.3007420Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/bin/fastlane:23:in `<top (required)>'
2020-10-14T07:15:46.3013350Z 	from /usr/local/bin/fastlane:23:in `load'
2020-10-14T07:15:46.3014800Z 	from /usr/local/bin/fastlane:23:in `<main>'
2020-10-14T07:15:46.3041600Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Cannot submit for review - could not find an editable version for 'IOS' (FastlaneCore::Interface::FastlaneError)
2020-10-14T07:15:46.3144970Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2020-10-14T07:15:46.3147220Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/submit_for_review.rb:16:in `submit!'
2020-10-14T07:15:46.3149010Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
2020-10-14T07:15:46.3150670Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:64:in `run'
2020-10-14T07:15:46.3152430Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2020-10-14T07:15:46.3169360Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-10-14T07:15:46.3182840Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-10-14T07:15:46.3204340Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-10-14T07:15:46.3211710Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-10-14T07:15:46.3234280Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-10-14T07:15:46.3237260Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2020-10-14T07:15:46.3239460Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2020-10-14T07:15:46.3241480Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2020-10-14T07:15:46.3300270Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/bin/fastlane:23:in `<top (required)>'
2020-10-14T07:15:46.3358270Z 	from /usr/local/bin/fastlane:23:in `load'
2020-10-14T07:15:46.3362250Z 	from /usr/local/bin/fastlane:23:in `<main>'
```

fastline env
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.163.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.381.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>
```

**Comment by mariana288** [comment]
I have faced this problem you can try [expresshr](https://www.expresshr.me/)

**Comment by lpaulusLohr** [comment]
@mariana288  What has expresshr to deal with fastlane and my problem ?

**Comment by rogerluan** [comment]
The issue here is on _precheck_, on this line:

https://github.com/fastlane/fastlane/blob/61cbd91e48f34a7a951642928dbc9b138fb04c8c/precheck/lib/precheck/rule_processor.rb#L177

`app_version` was nil there. It was nil there because this variable returned nil:

https://github.com/fastlane/fastlane/blob/61cbd91e48f34a7a951642928dbc9b138fb04c8c/precheck/lib/precheck/runner.rb#L186-L189

@lpaulusLohr are you sure you had an editable version in App Store Connect when you ran that command? 🤔

**Comment by rogerluan** [comment]
Actually this is a duplicated issue of https://github.com/fastlane/fastlane/issues/17176

**Comment by vgaidarji** [comment]
@rogerluan hey. Regarding your comment 
https://github.com/fastlane/fastlane/issues/17434#issuecomment-709407707

This change https://github.com/fastlane/fastlane/commit/71d42bb5549313b69a5834764804c24a6c8797a1#diff-10a3804e907e825b3a262ecbe102a182135de576bd1e7720023a9b84b745b05aR169
![image](https://user-images.githubusercontent.com/3036347/100457391-a124c280-30ca-11eb-968e-fd2aa2b710a0.png) broke the `precheck` for me as well.


`get_edit_app_store_version` is looking for particular statuses 
https://github.com/fastlane/fastlane/blob/2bdb19d08db3964ddf6b20c830c63eb069b5a1ed/spaceship/lib/spaceship/connect_api/models/app.rb#L239

![image](https://user-images.githubusercontent.com/3036347/100457488-ca455300-30ca-11eb-8dbf-3aa6466b49f4.png)
and the build is getting successfully uploaded to TestFlight before `precheck` but build is in `Missing Compliance` state ([app build statuses](https://help.apple.com/app-store-connect/#/dev3d6869aff)) which is not part of `get_edit_app_store_version` build statuses filter so no application version is returned.

**Comment by rogerluan** [comment]
Hey @vgaidarji 👋 

This PR should fix that issue :) https://github.com/fastlane/fastlane/pull/17738
