### ISSUE TITLE
Seems to be a very old project file format - please open your project file in a more recent version of Xcode

### ISSUE THREAD

**Issue by rafagan** [fastlane/fastlane#17514]
I'm experiencing the following error:

```
ERROR [2020-10-28 19:12:52.66]: fastlane finished with errors
DEBUG [2020-10-28 19:12:52.66]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/var/rbenv/versions/2.7.1/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Seems to be a very old project file format - please open your project file in a more recent version of Xcode
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/actions/update_code_signing_settings.rb:15:in `run'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  ../../pads-ios/Pads/fastlane/Base:20:in `run_match'
  Fastfile:36:in `block (2 levels) in parsing_binding'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/var/rbenv/versions/2.7.1/bin/fastlane:23:in `load'
  /usr/local/var/rbenv/versions/2.7.1/bin/fastlane:23:in `<top (required)>'
```

The command which causes the error is:

```
update_code_signing_settings(
  use_automatic_signing: false,
  path: ENV['XCPROJ_PATH'],
  team_id: ENV['TEAM_ID']
)
```

Any help?

**Comment by max-ott** [comment]
Please re-open the issue with complete information as per issue template.
