### ISSUE TITLE
Uploading trailer fails

### ISSUE THREAD

**Issue by kristiyandobrev** [fastlane/fastlane#17678]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am having the following lane for uploading app preview/trailers to App Store Connect: 

<img width="1098" alt="Carbonize 2020-11-26 at 12 00 08" src="https://user-images.githubusercontent.com/8437817/100343097-38ace700-2fdf-11eb-88b7-f7425221cafa.png">

Unfortunately it fails.

##### Command executed
`fastlane upload_app_videos`

##### Complete output when running fastlane, including the stack trace and command used
```
✔] 🚀
+------------------------------------------+---------+--------------------------+
|                                 Used plugins                                  |
+------------------------------------------+---------+--------------------------+
| Plugin                                   | Version | Action                   |
+------------------------------------------+---------+--------------------------+
| fastlane-plugin-clean_testflight_testers | 0.3.0   | clean_testflight_testers |
+------------------------------------------+---------+--------------------------+

[12:01:04]: ------------------------------
[12:01:04]: --- Step: default_platform ---
[12:01:04]: ------------------------------
[12:01:04]: Driving the lane 'ios upload_app_videos' 🚀
[12:01:11]: --------------------------
[12:01:11]: --- Step: notification ---
[12:01:11]: --------------------------
+------------------+-----------------------+
|               Lane Context               |
+------------------+-----------------------+
| DEFAULT_PLATFORM | ios                   |
| PLATFORM_NAME    | ios                   |
| LANE_NAME        | ios upload_app_videos |
+------------------+-----------------------+
[12:01:12]: Error in your Fastfile at line 201
[12:01:12]:     199:	    editedVersion = app.get_edit_app_store_version
[12:01:12]:     200:
[12:01:12]:  => 201:	    editedVersion.upload_trailer('./fastlane/previews/6.5/app-preview-6-5-de.mp4', 1, "de-DE", "iphone65")
[12:01:12]:     202:
[12:01:12]:     203:	    editedVersion.save!

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | notification     | 0           |
+------+------------------+-------------+

[12:01:12]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `upload_trailer' for #<Spaceship::ConnectAPI::AppStoreVersion:0x00007fcfe82a2190>
  Fastfile:201:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.168.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

**Comment by max-ott** [comment]
You can't simply replace the previous `Tunes` call for getting the edit version with the new `ConnectAPI` calls. As the error message shows, there is no `upload_trailer` method anymore. Please check out https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/models/app_preview_set.rb#L72 for more information.

**Comment by kristiyandobrev** [comment]
@max-ott It makes sense. But then how would I get the edit version where I can call `upload_trailer` ?
