### ISSUE TITLE
 Cannot submit for review - could not find an editable version for 'IOS'

### ISSUE THREAD

**Issue by lpaulusLohr** [fastlane/fastlane#17747]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Impossible to deliver (promote) : `  Cannot submit for review - could not find an editable version for 'IOS' (FastlaneCore::Interface::FastlaneError)` 

Using Azure promote iOS with FastLane

##### Command executed

`fastlane deliver submit_build -u *** -a APP -n 2.0.4410 --skip_binary_upload true --skip_metadata true --skip_screenshots true --automatic_release --force --precheck_include_in_app_purchases false --verbose`

##### Complete output when running fastlane, including the stack trace and command used

```
2020-12-07T16:15:55.4987300Z INFO [2020-12-07 17:15:55.49]: Checking app for precheck rule violations
2020-12-07T16:16:10.9724170Z Timeout received! Retrying after 3 seconds (remaining: 5)...
2020-12-07T16:16:11.2720450Z Timeout received! Retrying after 3 seconds (remaining: 4)...
2020-12-07T16:16:11.5787110Z Timeout received! Retrying after 3 seconds (remaining: 3)...
2020-12-07T16:16:11.8788820Z Timeout received! Retrying after 3 seconds (remaining: 2)...
2020-12-07T16:16:12.1553010Z Timeout received! Retrying after 3 seconds (remaining: 1)...
2020-12-07T16:16:12.1558060Z ERROR [2020-12-07 17:16:12.15]: [31mfastlane precheck just tried to inspect your app's metadata for App Store guideline violations and ran into a problem. We're not sure what the problem was, but precheck failed to finished. You can run it in verbose mode if you want to see the whole error. We'll have a fix out soon 🚀[0m
2020-12-07T16:16:12.1565120Z DEBUG [2020-12-07 17:16:12.15]: #<Spaceship::InternalServerError: Server error got 500>
2020-12-07T16:16:12.1582350Z DEBUG [2020-12-07 17:16:12.15]: /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:185:in `handle_response'
2020-12-07T16:16:12.1587060Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
2020-12-07T16:16:12.1590050Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:677:in `get_app_info_localizations'
2020-12-07T16:16:12.1593460Z /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get_app_info_localizations'
2020-12-07T16:16:12.1596450Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/models/app_info.rb:96:in `get_app_info_localizations'
2020-12-07T16:16:12.1599840Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/precheck/lib/precheck/rule_processor.rb:134:in `generate_app_items_to_check'
2020-12-07T16:16:12.1602070Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/precheck/lib/precheck/rule_processor.rb:47:in `process_app_and_version'
2020-12-07T16:16:12.1604300Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/precheck/lib/precheck/runner.rb:121:in `check_for_rule_violations'
2020-12-07T16:16:12.1606340Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/precheck/lib/precheck/runner.rb:47:in `run'
2020-12-07T16:16:12.1608130Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:101:in `precheck_app'
2020-12-07T16:16:12.1609880Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:63:in `run'
2020-12-07T16:16:12.1611630Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2020-12-07T16:16:12.1613390Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-12-07T16:16:12.1615050Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-12-07T16:16:12.1616730Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-12-07T16:16:12.1618420Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-12-07T16:16:12.1620030Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-12-07T16:16:12.1621730Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2020-12-07T16:16:12.1623420Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2020-12-07T16:16:12.1625160Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2020-12-07T16:16:12.1626790Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
2020-12-07T16:16:12.1628110Z /usr/local/bin/fastlane:23:in `load'
2020-12-07T16:16:12.1629210Z /usr/local/bin/fastlane:23:in `<main>'
2020-12-07T16:16:12.4900570Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [31m[!] Cannot submit for review - could not find an editable version for 'IOS'[0m (FastlaneCore::Interface::FastlaneError)
2020-12-07T16:16:12.4904830Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2020-12-07T16:16:12.4907500Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/submit_for_review.rb:16:in `submit!'
2020-12-07T16:16:12.4909760Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
2020-12-07T16:16:12.4912030Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:64:in `run'
2020-12-07T16:16:12.4915170Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2020-12-07T16:16:12.4916800Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-12-07T16:16:12.4918050Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-12-07T16:16:12.4919230Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-12-07T16:16:12.4920450Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-12-07T16:16:12.4921620Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-12-07T16:16:12.4922760Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2020-12-07T16:16:12.4924020Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2020-12-07T16:16:12.4926250Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2020-12-07T16:16:12.4928340Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
2020-12-07T16:16:12.4929780Z 	from /usr/local/bin/fastlane:23:in `load'
2020-12-07T16:16:12.4931030Z 	from /usr/local/bin/fastlane:23:in `<main>'
2020-12-07T16:16:12.4933280Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Cannot submit for review - could not find an editable version for 'IOS' (FastlaneCore::Interface::FastlaneError)
2020-12-07T16:16:12.4935650Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2020-12-07T16:16:12.4937510Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/submit_for_review.rb:16:in `submit!'
2020-12-07T16:16:12.4939360Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
2020-12-07T16:16:12.4941060Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:64:in `run'
2020-12-07T16:16:12.4942900Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2020-12-07T16:16:12.4944720Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-12-07T16:16:12.4946430Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-12-07T16:16:12.4948190Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-12-07T16:16:12.4950010Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-12-07T16:16:12.4951790Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-12-07T16:16:12.4953610Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2020-12-07T16:16:12.4955390Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2020-12-07T16:16:12.4957230Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2020-12-07T16:16:12.4958950Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
2020-12-07T16:16:12.4960330Z 	from /usr/local/bin/fastlane:23:in `load'
2020-12-07T16:16:12.4961430Z 	from /usr/local/bin/fastlane:23:in `<main>'```
-->

```
### Environment
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.29.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.1                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   | fr_FR.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.381.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>




*generated on:* **2020-12-07**
```

**Comment by max-ott** [comment]
Can you submit the app through App Store Connect? Are you getting any errors there? (privacy stuff?)

**Comment by lpaulusLohr** [comment]
With deliver I want to promote a specific version from TestFlight to the Production, to deliver to Testflight I use 
`fastlane pilot upload -u *** -i MY-IPA.FILE  -a APP_NAME --skip_waiting_for_build_processing true --uses_non_exempt_encryption true`

**Comment by rogerluan** [comment]
@lpaulusLohr I do the same as you in my workflow (testflight → release, what you're calling "promote"), and you must explicitly pass the app version in order for _deliver_ to work. Let me know if that works for you 🙏

**Comment by lpaulusLohr** [comment]
@rogerluan Hi, sorry it's my professional account, I take more time to give an answer : 
With the version 1.175.0 seems pass the precheck (only copyright date failed due to 2020) but the problem is deplaced after the prechecks.

Command :
```
fastlane deliver submit_build -u *** -a APP -n BuildNumber --skip_binary_upload true --skip_metadata true --skip_screenshots true --automatic_release --force --precheck_include_in_app_purchases false --verbose
```

Console:

```2021-01-04T11:57:54.6020630Z INFO [2021-01-04 12:57:54.60]: Checking app for precheck rule violations
2021-01-04T11:58:11.4683740Z INFO [2021-01-04 12:58:11.04]: ✅  Passed: No negative  sentiment
2021-01-04T11:58:11.4685900Z INFO [2021-01-04 12:58:11.04]: ✅  Passed: No placeholder text
2021-01-04T11:58:11.4789590Z INFO [2021-01-04 12:58:11.05]: ✅  Passed: No mentioning  competitors
2021-01-04T11:58:11.4892860Z INFO [2021-01-04 12:58:11.05]: ✅  Passed: No future functionality promises
2021-01-04T11:58:11.4993340Z INFO [2021-01-04 12:58:11.05]: ✅  Passed: No words indicating test content
2021-01-04T11:58:11.5097030Z INFO [2021-01-04 12:58:11.13]: ✅  Passed: No curse words
2021-01-04T11:58:11.5192540Z INFO [2021-01-04 12:58:11.13]: ✅  Passed: No words indicating your IAP is free
2021-01-04T11:58:11.5325630Z DEBUG [2021-01-04 12:58:11.13]: custom_text excluded because no data was passed to it e.g.: custom_text(data: <data here>)
2021-01-04T11:58:11.5437330Z DEBUG [2021-01-04 12:58:11.13]: 😭  CopyrightDateRule didn't find words "2021"
2021-01-04T11:58:11.5502490Z WARN [2021-01-04 12:58:11.13]: [33m😵  Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date[0m
2021-01-04T11:59:00.8981850Z INFO [2021-01-04 12:59:00.89]: ✅  Passed: No broken urls
2021-01-04T11:59:00.8991540Z +-----------+----------------+
2021-01-04T11:59:00.8992860Z |     [33mPotential problems[0m     |
2021-01-04T11:59:00.8993890Z +-----------+----------------+
2021-01-04T11:59:00.9015390Z | Field     | Failure reason |
2021-01-04T11:59:00.9017460Z +-----------+----------------+
2021-01-04T11:59:00.9018690Z | copyright | [33mmissing: 2021[0m  |
2021-01-04T11:59:00.9019800Z +-----------+----------------+
2021-01-04T11:59:00.9021270Z WARN [2021-01-04 12:59:00.89]: [33m[33mprecheck 👮‍♀️ 👮  found one or more potential metadata problems, but this won't prevent fastlane from completing 👍[0m
2021-01-04T11:59:01.3467110Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [31m[!] Cannot submit for review - could not find an editable version for 'IOS'[0m (FastlaneCore::Interface::FastlaneError)
2021-01-04T11:59:01.3469820Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2021-01-04T11:59:01.3471870Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/submit_for_review.rb:16:in `submit!'
2021-01-04T11:59:01.3473820Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
2021-01-04T11:59:01.3477080Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/runner.rb:64:in `run'
2021-01-04T11:59:01.3479380Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2021-01-04T11:59:01.3481210Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2021-01-04T11:59:01.3483310Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2021-01-04T11:59:01.3485340Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2021-01-04T11:59:01.3487210Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2021-01-04T11:59:01.3488430Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2021-01-04T11:59:01.3489580Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2021-01-04T11:59:01.3490780Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2021-01-04T11:59:01.3491970Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2021-01-04T11:59:01.3493100Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
2021-01-04T11:59:01.3494000Z 	from /usr/local/bin/fastlane:23:in `load'
2021-01-04T11:59:01.3494790Z 	from /usr/local/bin/fastlane:23:in `<main>'
2021-01-04T11:59:01.3496700Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Cannot submit for review - could not find an editable version for 'IOS' (FastlaneCore::Interface::FastlaneError)
2021-01-04T11:59:01.3498960Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2021-01-04T11:59:01.3500180Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/submit_for_review.rb:16:in `submit!'
2021-01-04T11:59:01.3502280Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
2021-01-04T11:59:01.3503390Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/runner.rb:64:in `run'
2021-01-04T11:59:01.3504570Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2021-01-04T11:59:01.3505750Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2021-01-04T11:59:01.3506850Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2021-01-04T11:59:01.3507990Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2021-01-04T11:59:01.3509170Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2021-01-04T11:59:01.3510340Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2021-01-04T11:59:01.3511480Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2021-01-04T11:59:01.3512630Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2021-01-04T11:59:01.3513820Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2021-01-04T11:59:01.3514920Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
2021-01-04T11:59:01.3515820Z 	from /usr/local/bin/fastlane:23:in `load'
2021-01-04T11:59:01.3516620Z 	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by rogerluan** [comment]
@lpaulusLohr that error is thrown when you haven't created a new version of the app yet, so it can't find an "editable" version of your app - only "live" ones.
