### ISSUE TITLE
Mac app store version of sigh

### ISSUE THREAD

**Issue by fastlane-bot** [fastlane/fastlane#1781]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/565053?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @rickbdotcom - Imported from <a href='https://github.com/fastlane/sigh/issues/40'>fastlane/sigh#40</a>
        </td>
      </tr>
    </table>

Are there any plans for a Mac app store version of these tools? For the most part just changing the paths from /ios/ to /mac/ would do the trick. I just tried that on the Nomad Cupertino tools and got those to working with the Mac app store without too much trouble.

**Comment by anlumo** [comment]
@KrauseFx asked me to share the log of sigh failing on a Mac app:

```
INFO [2016-09-26 23:11:04.97]: Successfully logged in
INFO [2016-09-26 23:11:04.97]: Fetching profiles...
WARN [2016-09-26 23:11:04.97]: To not be asked about this value, you can specify it using 'app_identifier'
The bundle identifier of your app: com.greenandslimy.Deskscribble
WARN [2016-09-26 23:11:12.93]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
INFO [2016-09-26 23:11:13.77]: 
INFO [2016-09-26 23:11:13.77]: ==========================================
INFO [2016-09-26 23:11:13.77]: Could not find App ID with bundle identifier 'com.greenandslimy.Deskscribble'
INFO [2016-09-26 23:11:13.77]: You can easily generate a new App ID on the Developer Portal using 'produce':
INFO [2016-09-26 23:11:13.77]: 
INFO [2016-09-26 23:11:13.77]: produce -u XXXXXXXXXX -a com.greenandslimy.Deskscribble --skip_itc
INFO [2016-09-26 23:11:13.77]: 
INFO [2016-09-26 23:11:13.77]: You will be asked for any missing information, like the full name of your app
INFO [2016-09-26 23:11:13.77]: If the app should also be created on iTunes Connect, remove the --skip_itc from the command above
INFO [2016-09-26 23:11:13.77]: ==========================================
INFO [2016-09-26 23:11:13.77]: 
/Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Could not find App with App Identifier 'com.greenandslimy.Deskscribble' (FastlaneCore::Interface::FastlaneError)
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.11.1/lib/sigh/runner.rb:218:in `ensure_app_exists!'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.11.1/lib/sigh/runner.rb:38:in `run'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.11.1/lib/sigh/manager.rb:7:in `start'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.11.1/lib/sigh/commands_generator.rb:56:in `block (2 levels) in run'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.11.1/lib/sigh/commands_generator.rb:120:in `run'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.11.1/lib/sigh/commands_generator.rb:11:in `start'
	from /Users/anlumo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.11.1/bin/sigh:6:in `<top (required)>'
	from /Users/anlumo/.rbenv/versions/2.3.0/bin/sigh:23:in `load'
	from /Users/anlumo/.rbenv/versions/2.3.0/bin/sigh:23:in `<main>'
```

The app ID does exist, the app is even in the store already. I suspect that it looks for iOS app IDs, not macOS app IDs.

**Comment by TKBurner** [comment]
@anlumo Can you open up a new issue for this? That'd help!

**Comment by KrauseFx** [comment]
Hey @anlumo, thanks for the stack trace. I took a closer look, and seems like _sigh_ only supports iOS projects at the moment ([source](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/sigh.rb#L64)). Unfortunately we don't have the time to focus on Mac support for _fastlane_. I do know however, that @radex added Mac support to _spaceship_, so it could potentially be added to _sigh_ 👍
