### ISSUE TITLE
Issue installing with bundler

### ISSUE THREAD

**Issue by lexicalninja** [fastlane/fastlane#17877]
# Error Report

## Questions

- **What did you do?**

  I ran the command `/Users/pasqualelsaxton/.gem/ruby/2.6.0/bin/bundle update`

- **What did you expect to happen?**

  I expected Bundler to run the installer and create a lock file

- **What happened instead?**

  Instead, what happened was the installer started then errored out 

It seems to be breaking when it installs unf_ext v0.0.7.7

I have reinstalled x-code and accepted the license and still the issue is persisting. I am not installing fastlane via brew or gems or any other way because of requirements for this specific app. 

I need to be able to install from the gemfile on local machines and circle ci in the exact same way and there seems to be something breaking in the installs. 

I am using the following:
```
   Mac OS: 10.15.7
   XCode: 12.3 (12C33)
```

Any help would be great, thank you. 

## Backtrace

```
Errno::EACCES: Permission denied @ rb_sysopen - /Users/pasqualelsaxton/Documents/repos/va-mobile-app/VAMobile/ios/vendor/bundle/ruby/2.6.0/gems/json-2.5.1/CHANGES.md
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:431:in `initialize'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:431:in `open'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:431:in `block (2 levels) in extract_tar_gz'
  /Library/Ruby/Site/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:412:in `block in extract_tar_gz'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:541:in `block in open_tar_gz'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:538:in `wrap'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:538:in `open_tar_gz'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:411:in `extract_tar_gz'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:391:in `block (2 levels) in extract_files'
  /Library/Ruby/Site/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:388:in `block in extract_files'
  /Library/Ruby/Site/2.6.0/rubygems/package/file_source.rb:29:in `open'
  /Library/Ruby/Site/2.6.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /Library/Ruby/Site/2.6.0/rubygems/package.rb:385:in `extract_files'
  /Library/Ruby/Site/2.6.0/rubygems/installer.rb:830:in `extract_files'
  /Library/Ruby/Site/2.6.0/rubygems/installer.rb:310:in `install'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/source/rubygems.rb:158:in `install'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/installer/gem_installer.rb:67:in `install'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/installer/parallel_installer.rb:163:in `do_install'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/installer/parallel_installer.rb:154:in `block in worker_pool'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/worker.rb:62:in `apply_func'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/worker.rb:54:in `loop'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/worker.rb:54:in `process_queue'
  /Users/pasqualelsaxton/.gem/ruby/2.6.0/gems/bundler-2.2.3/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.3
  Platforms   ruby, universal-darwin-19
Ruby          2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.2.3
  Gem Home    /Users/pasqualelsaxton/Documents/repos/va-mobile-app/VAMobile/ios/vendor/bundle/ruby/2.6.0
  Gem Path    /Users/pasqualelsaxton/Documents/repos/va-mobile-app/VAMobile/ios/vendor/bundle/ruby/2.6.0
  User Home   /Users/pasqualelsaxton
  User Path   /Users/pasqualelsaxton/.gem/ruby/2.6.0
  Bin Dir     /Users/pasqualelsaxton/Documents/repos/va-mobile-app/VAMobile/ios/vendor/bundle/ruby/2.6.0/bin
OpenSSL       
  Compiled    LibreSSL 2.8.3
  Loaded      LibreSSL 2.8.3
  Cert File   /private/etc/ssl/cert.pem
  Cert Dir    /private/etc/ssl/certs
Tools         
  Git         2.24.3 (Apple Git-128)
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-12-22
Git SHA           29dc3c8398
Released Version  true
```

## Bundler settings

```
path
  Set for your local app (/Users/pasqualelsaxton/Documents/repos/va-mobile-app/VAMobile/ios/.bundle/config): "vendor/bundle"
  Set for the current user (/Users/pasqualelsaxton/.bundle/config): "vendor/bundle"
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "fastlane"
```

### Gemfile.lock

```

```

**Comment by lexicalninja** [comment]
There is no fastlane env because the install fails

**Comment by ainame** [comment]
> Errno::EACCES: Permission denied @ rb_sysopen - /Users/pasqualelsaxton/Documents/repos/va-mobile-app/VAMobile/ios/vendor/bundle/ruby/2.6.0/gems/json-2.5.1/CHANGES.md

It looks like the issue is on your end.  Can you please make sure if the install directory's permission is correct?
