### ISSUE TITLE
Scan action fails due to slack notifications even though tests succeed

### ISSUE THREAD

**Issue by asifmohd** [fastlane/fastlane#17898]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.171.0`]
- Last working version: [e.g. `2.170.0`]

### Regression Description

Executing the scan action with the `SLACK_URL` env variable set, but the `SCAN_SLACK_DEFAULT_PAYLOADS` env variable not set, causes scan to fail with an error: 

```undefined method `map' for nil:NilClass```

Example invocation command:

```
SLACK_URL=https://example.com SLACK_CHANNEL="ios-fastlane-notifs" SCAN_WORKSPACE=/Users/asif/Documents/Test/Test.xcworkspace BUNDLE_GEMFILE=/Users/asif/Documents/Test/Gemfile bundle exec fastlane scan --scheme Test --clean false --derived_data_path build
```

The immediate fix has been to set 

```
slack_default_payloads: ['lane', 'test_result', 'git_branch', 'git_author', 'last_git_commit', 'last_git_commit_hash']
```

and pass this value to scan invocation in our fastfile

Example fixed command

```
SLACK_URL=https://example.com SLACK_CHANNEL="ios-fastlane-notifs" SCAN_WORKSPACE=/Users/asif/Documents/Test/Test.xcworkspace BUNDLE_GEMFILE=/Users/asif/Documents/Test/Gemfile bundle exec fastlane scan --scheme Test --clean false --derived_data_path build --slack_default_payloads "['lane', 'test_result', 'git_branch', 'git_author', 'last_git_commit', 'last_git_commit_hash']"
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[16:31:42]: ▸ Test Succeeded

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `id' for nil
    https://github.com/fastlane/fastlane/issues/17818 [open] 0 💬
    2 weeks ago

➡️  Download DSYMs action broken
    https://github.com/fastlane/fastlane/issues/17677 [open] 1 💬
    4 weeks ago

➡️  [supply] undefined method `map' for nil:NilClass on "draft" tracks
    https://github.com/fastlane/fastlane/issues/17086 [closed] 4 💬
    2 weeks ago

and 99 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60map%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/asif/.rbenv/versions/2.6.6/bin/fastlane)
NoMethodError: [!] undefined method `map' for nil:NilClass
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/slack.rb:191:in `block in generate_slack_attachments'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/slack.rb:213:in `generate_slack_attachments'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/slack.rb:44:in `run'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/slack_poster.rb:46:in `run'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/runner.rb:89:in `handle_results'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/runner.rb:23:in `run'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/manager.rb:23:in `work'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/commands_generator.rb:44:in `block (2 levels) in run'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/commands_generator.rb:75:in `run'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/commands_generator.rb:15:in `start'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /Users/asif/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
  /Users/asif/.rbenv/versions/2.6.6/bin/fastlane:23:in `load'
  /Users/asif/.rbenv/versions/2.6.6/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.6                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.29.2                          |
| Installation Source         | ~/.rbenv/versions/2.6.6/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import('../common/fastlane/Fastfile')

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.3       |
| CFPropertyList            | 3.0.3        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 1.8.6        |
| minitest                  | 5.14.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.9        |
| activesupport             | 5.2.4.4      |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.5.1        |
| algoliasearch             | 1.27.5       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.414.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| netrc                     | 0.11.0       |
| ffi                       | 1.14.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.10.0       |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| cocoapods                 | 1.10.0       |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday-net_http          | 1.0.0        |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| faraday-http-cache        | 2.2.0        |
| rchardet                  | 1.8.0        |
| git                       | 1.8.1        |
| rexml                     | 3.2.4        |
| kramdown                  | 2.3.0        |
| kramdown-parser-gfm       | 1.1.0        |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.2        |
| octokit                   | 4.20.0       |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| danger                    | 8.2.1        |
| danger-plugin-api         | 1.0.0        |
| danger-SwiftInfo          | 0.0.5        |
| thor                      | 0.20.3       |
| danger-swiftlint          | 0.24.5       |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.3        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| mini_magick               | 4.11.0       |
| plist                     | 3.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.1        |
| git_diff_parser           | 3.2.0        |
| mime-types-data           | 3.2020.1104  |
| mime-types                | 3.3.1        |
| multi_xml                 | 0.6.0        |
| httparty                  | 0.18.1       |
| gitlab                    | 4.15.0       |
| pool                      | 0.0.1        |
| thread                    | 0.2.2        |
| xcresult                  | 0.2.1        |
| xcov                      | 1.7.4        |
</details>

*generated on:* **2021-01-04**
</details></pre>
</details>

**Comment by asifmohd** [comment]
I think that the bug could have been introduced due to [this modification](https://github.com/fastlane/fastlane/pull/17866/files#diff-e17259d099a0447ae1c18920e3251ec219f6069913276bf742f6687d9ea8ff80L191)

IMHO possible fixes include:
1. Revert the above modification
2. Give a default value to `:slack_default_payloads` config and make it non optional, similar to how the previous `:default_payloads` config [used to work](https://github.com/fastlane/fastlane/blob/e2ff4990a44f28fa7b25d745666007dc8e315577/fastlane/lib/fastlane/actions/slack.rb#L119)

**Comment by stherold** [comment]
we have exactly the same issue.

**Comment by khoogheem** [comment]
same same 
```
block in generate_slack_attachments': [!] undefined method `map' for nil:NilClass
```

**Comment by maplestory06** [comment]
Is it because of Slack's outage today? 
https://status.slack.com/

![image](https://user-images.githubusercontent.com/18542103/103571279-72df9300-4e7f-11eb-9fe3-23de6a16d0f5.png)

**Comment by khoogheem** [comment]
my issues were pre-outage

**Comment by masamichiueta** [comment]
I have a same issue. 
I resolved this issue by adding `slack_default_payloads` in `scan`.
I agree with giving a default value to `slack_default_payloads` config.

**Comment by crazymanish** [comment]
Hi @asifmohd  @stherold @khoogheem @masamichiueta

can you please verify the fix, PR https://github.com/fastlane/fastlane/pull/17919
You need to update your Gemfile as:
`gem 'fastlane', :git => "git://github.com/crazymanish/fastlane.git", :branch => "slack-issue-fix"`
