### ISSUE TITLE
Error running `screenshots` command - latest_simulator_version_for_device: undefined method `os_version' for nil:NilClass

### ISSUE THREAD

**Issue by SpencerLynn** [fastlane/fastlane#17894]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am running into an issue trying to setup/execute fastlane. 

I followed the setup instructions, but am hitting an error when running the `fastlane screenshots` command. 

The Xcode UI unit test passes when run, but only fails through the CLI.

##### Command executed
I'm using `bundle exec fastlane screenshots`

I've also tried `fastlane screenshots` directly.

##### Complete output when running fastlane, including the stack trace and command used
```
bundle exec fastlane screenshots
[✔] 🚀
[14:50:50]: ------------------------------
[14:50:50]: --- Step: default_platform ---
[14:50:50]: ------------------------------
[14:50:50]: Driving the lane 'ios screenshots' 🚀
[14:50:55]: ---------------------------------
[14:50:55]: --- Step: capture_screenshots ---
[14:50:55]: ---------------------------------
[14:50:55]: Successfully loaded '/<redacted>/fastlane/Snapfile' 📄

+----------------------------+----------------------------------------------------------+
|                      Detected Values from './fastlane/Snapfile'                       |
+----------------------------+----------------------------------------------------------+
| devices                    | ["iPhone 12 Pro Max", "iPhone 12 Pro", "iPhone 12 mini   |
|                            | ", "iPhone SE (2nd generation)", "iPhone 8", "iPhone 8   |
|                            | Plus", "iPad Pro (12.9-inch) (4th generation)", "iPad    |
|                            | Pro (11-inch) (2nd generation)", "iPad Pro (9.7-inch)",  |
|                            | "iPad Air (4th generation)", "iPad (8th generation)"]    |
| languages                  | ["en-US"]                                                |
| scheme                     | <redacted>                                    |
| output_directory           | ./screenshots                                            |
| clear_previous_screenshots | true                                                     |
| override_status_bar        | true                                                     |
+----------------------------+----------------------------------------------------------+

[14:50:55]: Resolving Swift Package Manager dependencies...
[14:50:55]: $ xcodebuild -resolvePackageDependencies -scheme <redacted> -project ./<redacted>.xcodeproj
[14:51:00]: ▸ Command line invocation:
[14:51:00]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme <redacted> -project ./<redacted>.xcodeproj
[14:51:01]: ▸ resolved source packages:
[14:51:01]: $ xcodebuild -showBuildSettings -scheme <redacted> -project ./<redacted>.xcodeproj
[14:51:02]: Could not read the "SUPPORTED_PLATFORMS" build setting, assuming that the project supports iOS only.

+----------------------------+----------------------------------------------------------+
|                             Summary for snapshot 2.171.0                              |
+----------------------------+----------------------------------------------------------+
| scheme                     | <redacted>                                    |
| project                    | ./<redacted>.xcodeproj                               |
| output_directory           | /<redacted>/screenshots       |
| devices                    | ["iPhone 12 Pro Max", "iPhone 12 Pro", "iPhone 12 mini   |
|                            | ", "iPhone SE (2nd generation)", "iPhone 8", "iPhone 8   |
|                            | Plus", "iPad Pro (12.9-inch) (4th generation)", "iPad    |
|                            | Pro (11-inch) (2nd generation)", "iPad Pro (9.7-inch)",  |
|                            | "iPad Air (4th generation)", "iPad (8th generation)"]    |
| languages                  | ["en-US"]                                                |
| launch_arguments           | [""]                                                     |
| output_simulator_logs      | false                                                    |
| skip_open_summary          | false                                                    |
| skip_helper_version_check  | false                                                    |
| clear_previous_screenshots | true                                                     |
| reinstall_app              | false                                                    |
| erase_simulator            | false                                                    |
| headless                   | true                                                     |
| override_status_bar        | true                                                     |
| localize_simulator         | false                                                    |
| app_identifier             | <redacted>                             |
| buildlog_path              | ~/Library/Logs/snapshot                                  |
| clean                      | false                                                    |
| number_of_retries          | 1                                                        |
| stop_after_first_error     | false                                                    |
| result_bundle              | false                                                    |
| concurrent_simulators      | true                                                     |
| disable_slide_to_type      | false                                                    |
| xcode_path                 | /Applications/Xcode.app                                  |
+----------------------------+----------------------------------------------------------+

[14:51:03]: Clearing previously generated screenshots
[14:51:03]: Building and running project - this might take some time...
+------------------+-----------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | ios             |
| LANE_NAME        | ios screenshots |
+------------------+-----------------+

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 💥   | capture_screenshots | 8           |
+------+---------------------+-------------+

[14:51:04]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Support for test-only runs for Snapshot using test binary only
    https://github.com/fastlane/fastlane/issues/12723 [closed] 10 💬
    14 Nov 2018

➡️  Snapshot support for macOS projects
    https://github.com/fastlane/fastlane/issues/11092 [closed] 30 💬
    26 May 2018

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	37: from /usr/local/Cellar/fastlane/2.171.0/libexec/bin/fastlane:23:in `<main>'
	36: from /usr/local/Cellar/fastlane/2.171.0/libexec/bin/fastlane:23:in `load'
	35: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
	34: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	33: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	32: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	31: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	30: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	29: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	28: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	27: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	26: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	25: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	24: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	23: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	22: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	21: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	20: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	19: from Fastfile:21:in `block (2 levels) in parsing_binding'
	18: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	17: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	16: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	15: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	14: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	13: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	12: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	11: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/capture_ios_screenshots.rb:14:in `run'
	10: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/runner.rb:45:in `work'
	 9: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `take_screenshots_simultaneously'
	 8: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `each'
	 7: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `block in take_screenshots_simultaneously'
	 6: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each_with_index'
	 5: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each'
	 4: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `block (2 levels) in take_screenshots_simultaneously'
	 3: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `group_by'
	 2: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `each'
	 1: from /usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `block (3 levels) in take_screenshots_simultaneously'
/usr/local/Cellar/fastlane/2.171.0/libexec/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/device_manager.rb:134:in `latest_simulator_version_for_device': \e[31m[!] undefined method `os_version' for nil:NilClass\e[0m (NoMethodError)
```

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.1                                                    |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | true                                                    |
| Git                         | git version 2.23.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.171.0/libexec/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.3                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "MilitaryRetireUITests")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("--redacted--") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| rake                      | 13.0.3       |
| CFPropertyList            | 3.0.3        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.414.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| babosa                    | 1.0.4        |
| bundler                   | 2.1.4        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.3        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| faraday-net_http          | 1.0.0        |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| json                      | 2.5.1        |
| mini_magick               | 4.11.0       |
| plist                     | 3.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.1        |
</details>

*generated on:* **2021-01-02**
</details>
 </pre>
</details>

**Comment by SpencerLynn** [comment]
Quick update: I was able to run `snapshots` command just fine on some simulator names but not others. The simulators should exist, but getting this error not a "simulator does not exist" error or something along those lines. I will update more if I find anything else.

**Comment by SpencerLynn** [comment]
It seemed that only the iPhone 12 Pro Max was causing issues. However, after running it several times on other simulators, it is now working for iPhone 12 Pro Max also. I checked the spelling several times and that didn't seem to be the issue, ever.

I'm going to close this issue for now, since I can no longer reproduce this issue. Thanks!
