### ISSUE TITLE
The URL path is not valid - The resource 'bulkBetaTesterAssignments' does not exist (FastlaneCore::Interface::FastlaneError)

### ISSUE THREAD

**Issue by nawaahme** [fastlane/fastlane#18004]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
 bulkBetaTesterAssignments error while adding new testers using fastlane with API Keys

##### Command executed
fastlane pilot add -a <apple-id> --api_key_path "APIKey.json" --team_id ***** --groups ${bamboo.tester.groups} -f ${bamboo.tester.firstname} -l ${bamboo.tester.lastname} -e ${bamboo.tester.email} --verbose 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> INFO [2021-01-18 22:42:41.43]: Creating authorization token for App Store Connect API
--
18-Jan-2021 22:42:47 | ERROR [2021-01-18 22:42:47.09]: The URL path is not valid - The resource 'bulkBetaTesterAssignments' does not exist
18-Jan-2021 22:42:47 | /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Some operations failed: The URL path is not valid - The resource 'bulkBetaTesterAssignments' does not exist (FastlaneCore::Interface::FastlaneError)
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:44:in `handle_multiple'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:101:in `block (2 levels) in run'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
18-Jan-2021 22:42:47 | /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Some operations failed: The URL path is not valid - The resource 'bulkBetaTesterAssignments' does not exist (FastlaneCore::Interface::FastlaneError)
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:44:in `handle_multiple'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:101:in `block (2 levels) in run'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
18-Jan-2021 22:42:47 | from /Users/mobosxbuilder/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
18-Jan-2021 22:42:47 | Failing task since return code of [/bin/sh /var/folders/6f/cq53pb957z97l4kydh3bsch40000gn/T/MT-TATTGM-JOB1-5-ScriptBuildTask-5290173111371978382.sh] was 1 while expected 0
18-Jan-2021 22:42:47 | Finished task 'Add Tester to Group' with result: Failed </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by nawaahme** [comment]
[21:52:12]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[21:52:14]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| unicode-display_width     | 1.7.0        |
| plist                     | 3.6.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| excon                     | 0.78.1       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| ruby2_keywords            | 0.0.2        |
| faraday-net_http          | 1.0.1        |
| faraday                   | 1.3.0        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.1        |
| json                      | 2.3.0        |
| mini_magick               | 4.11.0       |
| xcpretty-travis-formatter | 1.0.1        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.14.0       |
| rake                      | 12.3.2       |
| digest-crc                | 0.6.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.4.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.416.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.111.0      |
| aws-sdk-kms               | 1.41.0       |
| aws-sdk-s3                | 1.87.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| date                      | 2.0.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| fileutils                 | 1.2.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.2       |
| rexml                     | 3.2.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2021-01-19**
</details>

**Comment by febaisi** [comment]
I am still not able to use this -- At this point, looking at this comment [here](https://github.com/fastlane/fastlane/issues/18098#issuecomment-772959186), I believe this is a kind of limitation. So, not sure if I should go ahead and open a new issue here...<br>
I still have the same response using the below code, though:
`    Spaceship::ConnectAPI.post_bulk_beta_tester_assignments(beta_group_id: groups.first.id, beta_testers: testers)` <br>

![image](https://user-images.githubusercontent.com/1815030/110126992-0e638600-7d93-11eb-966c-eed84c763969.png)

<br>All the other Spaceship calls were fine connecting Spaceship with my apiKey:
```
    apiKey = app_store_connect_api_key(
      key_id: "X****.",
      issuer_id: "x********************************",
      key_content: "-----BEGIN PRIVATE KEY-----\nKEY_CONTENT\n-----END PRIVATE KEY-----",
      duration: 1200,
      in_house: false
    )
    Spaceship::ConnectAPI::Token.create(apiKey) if apiKey
```

**Comment by choli** [comment]
Seeing the same issue since switching to api key. Do we have any news on this? But I have an additional question: Can I call pilot anyhow in a lane that calls import only? I cannot find a way but running `sh "fastlane pilot import ..."`

**Comment by stmitt** [comment]
I have the same issue. 
I created an action which calls `Pilot::TesterImporter.new.import_testers`directly but i still get the error: `The resource 'bulkBetaTesterAssignments' does not exist`

**Comment by whalemare** [comment]
Still reproduced in fastlane-2.187.0

**Comment by FelixLisczyk** [comment]
I receive the same error message in fastlane 2.191.0:

`fastlane pilot add <email> -a <app-identifier> -g <group> --api_key_path <path-to-json>`

```
[12:12:58]: Creating authorization token for App Store Connect API
[12:13:04]: The URL path is not valid - The resource 'bulkBetaTesterAssignments' does not exist
```

**Comment by whalemare** [comment]
Bump

**Comment by choli** [comment]
Haven't had time to check yet, but is this actually fixed?

**Comment by RobertoPelonara** [comment]
As of today not fixed yet!

**Comment by FelixLisczyk** [comment]
This issue still occurs in the latest fastlane version 2.204.3.

<details>
<summary>Fastlane</summary>

```
sh "fastlane pilot add #{tester_email} -a #{app_id} -g #{group_id} --api_key_path #{api_key_path}"
```

</details>

<details>
<summary>Stack trace</summary>

```
[15:36:51]: Creating authorization token for App Store Connect API
[15:36:59]: \e[31mThe URL path is not valid - The resource 'bulkBetaTesterAssignments' does not exist\e[0m
\e[31m
[!] Some operations failed: The URL path is not valid - The resource 'bulkBetaTesterAssignments' does not exist\e[0m
\e[0m
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/fast_file.rb:223:in `block in sh'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/fast_file.rb:222:in `sh'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/fast_file.rb:216:in `sh'
        from configuration/Fastfile_Testflight:54:in `block (2 levels) in parsing_binding'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/bin/fastlane:23:in `<top (required)>'
        from /Users/felix/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `load'
        from /Users/felix/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `<top (required)>'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
        from /Users/felix/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
        from /Users/felix/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'
```

</details>

**Comment by FelixLisczyk** [comment]
This is still an issue in the latest fastlane version 2.205.2.

**Comment by rahul-readwhere** [comment]
any update on this ?

**Comment by btrautmann** [comment]
Not sure if this helps, but I ran into this when using spaces in my `PILOT_GROUPS` environment variable when doing `pilot add`. Using something like `PILOT_GROUPS=my_internal_testers` succeeds (but it's not a valid group name, so doesn't actually do what I want it to do), while `PILOT_GROUPS=My Internal Testers` fails with the error mentioned in this issue.

**Comment by btrautmann** [comment]
Update on the above ☝️ 

Switching to using `--group=My Internal Testers` (instead of the environment variable or `-g`) for `pilot add` succeeded.

**Comment by CraigSiemens** [comment]
We're still having this issue with 2.210.1.

**Comment by cerupcat** [comment]
Was able to get this working? I'm running into this now too.

**Comment by cerupcat** [comment]
Was able to get this working? I'm running into this now too.

@btrautmann I tried your suggestion, but it didn't change anything for me. Can you share your full command that is working?

**Comment by btrautmann** [comment]
> @btrautmann I tried your suggestion, but it didn't change anything for me. Can you share your full command that is working?

I'm sorry, we abandoned the effort that included this work and I no longer have a working memory of any of this 😓 so I'm unfortunately no help 😭

**Comment by dromeromoran-wish** [comment]
Still having this issue as of 2.211.0, has anyone found a workaround? Thanks in advance

**Comment by cerupcat** [comment]
@dromeromoran-wish haven't found a workaround. @joshdholtz have you had a chance to look at what might be the cause?

**Comment by tmm1** [comment]
Workaround is to not use the API because the API doesn't support these features.

For me I had to remove `APP_STORE_CONNECT_API_KEY_PATH` for these commands.

**Comment by cerupcat** [comment]
How are you supposed to do this than via CI? The only way to auth is via
API isn't it in that case?
ᐧ

**Comment by dromeromoran-wish** [comment]
+1 to @cerupcat 's comment, we are trying to perform the add action via CI, but without API auth this is just not possible. Generating a verified session wouldn't be feasible either since there is no guarantee on the duration of the session's validity.  It kind of defeats the whole purpose of having this automated through CI if we manually need to generate a session every x days.

**Comment by nawaahme** [comment]
NA

**Comment by nawaahme** [comment]
NA

**Comment by cerupcat** [comment]
@nawaahme why did you close this issue?

**Comment by cerupcat** [comment]
@nawaahme why did you close this issue? In what way is it resolved?

**Comment by cerupcat** [comment]
@nawaahme @joshdholtz can you re-open this issue? I don't understand why it was closed.

**Comment by joshdholtz** [comment]
Reopened! And... actually going to look into tonight/tomorrow 😁

**Comment by cerupcat** [comment]
Thanks so much. Happy to help if needed.
ᐧ

**Comment by miguelslemos** [comment]
> Reopened! And... actually going to look into tonight/tomorrow 😁

Hey @joshdholtz any news about this issue?

**Comment by LetticiaNicoli** [comment]
do we have any news about it? 👀 😄

**Comment by cerupcat** [comment]
Any updates on this @joshdholtz? Even some general idea of what issue could be would be great.

**Comment by tikidunpon** [comment]
I tried an alternative with `fastlane pilot add` but it didn't work, because `pilot add` also depends on `bulkBetaTesterAssignments`.

It seems that adding the Create a Beta Tester API to [here](https://github.com/fastlane/fastlane/blob/4ac1d96753c33cfdb5e0f46086860cdcecdf7daa/spaceship/lib/spaceship/connect_api/testflight/testflight.rb) would work, but unfortunately this implementation does not  exist for now.
https://developer.apple.com/documentation/appstoreconnectapi/create_a_beta_tester

**Comment by eytanbiala** [comment]
Hello, hitting this now - has anyone found a workaround?

**Comment by AndreParenteNeon** [comment]
hitting on this now! anyone solved?

**Comment by jpvargasdev** [comment]
Hitting on this as well, seems like the https://developer.apple.com/documentation/appstoreconnectapi api doesnt have bulkBetaTesterAssignments API? so is a limitation with the apple api? https://github.com/fastlane/fastlane/blob/806c80c39754034c3dfcdade6beb51bb55c7f3b1/pilot/lib/pilot/tester_manager.rb#L22C15-L22C48 

```
        token = Spaceship::ConnectAPI::Token.create(key_id: api_key_id, issuer_id: issuer_id, filepath: api_key_path)
        client = Spaceship::ConnectAPI::Client.new(token: token)
        beta_testers = [
          {email: "test@test.com", firstName: "juan", lastName: "test"}
        ]
        testers = client.post_bulk_beta_tester_assignments(beta_testers:beta_testers)
        list_by_app(testers, "All Testers")
```

The URL path is not valid - The resource 'v1/bulkBetaTesterAssignments' does not exist...

**Comment by marcos-strava** [comment]
I believe I have a fix here: https://github.com/fastlane/fastlane/pull/29519

CC @joshdholtz @AliSoftware

**Comment by salvatoreboemia** [comment]
Guys do you have fixes this issue?

Thanks a lot

**Comment by nrajput05** [comment]
Got this today.
I can see it used to work 3 months back in my deoployment history. Has apple removed this API?

Error adding tester zzz@company.com: The URL path is not valid - The resource 'v1/bulkBetaTesterAssignments' does not exist.

Command used: fastlane pilot import -c ../testers.csv --api_key_path ./appstoreConnectAPI.json -g MyAppGroup

**Comment by btrautmann** [comment]
Sadly, this still seems to not work. Even worse, past me above suggested something that for sure doesn't fix the issue (using `--group` instead of `-g` or an environment variable). I likely saw a red herring and thought I'd addressed the issue. Sorry about that @cerupcat!

It would be awesome if the correct API could be integrated into `pilot add`!

**Comment by btrautmann** [comment]
I had issues using both `pilot add` and `pilot remove`, both of which are fixed (at least for me) on the fork referenced in this PR: https://github.com/fastlane/fastlane/pull/29689

If you want to give it a run and confirm, feel free to use the following in your Gemfile:

```rb
gem 'fastlane', git: 'https://github.com/btrautmann/fastlane', branch: 'bt/fix-find-tester'
```

You should see the following in your `Gemfile.lock`:
```rb
GIT
  remote: https://github.com/btrautmann/fastlane
  revision: 5e9a6b76ce346626cac262230e768b307daca08a # or a later commit
  branch: bt/fix-find-tester
```
