### ISSUE TITLE
Error during Fastlane installation on MacOS Catalina

### ISSUE THREAD

**Issue by egor-sorokin** [fastlane/fastlane#18104]
OS version: v.10.15.7
xcode-select: v.2373
gem: v.3.2.8

I tried to install it via:
```
sudo gem install fastlane -NV
```
and 
https://github.com/fastlane/fastlane/issues/15183#issuecomment-548602350

but nothing helped me, every time installation failed with the following error:
```
Building native extensions. This could take a while...
current directory: /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.7.7/ext/unf_ext
["/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby", "-I", "/Library/Ruby/Site/2.6.0", "-r", "./siteconf20210203-22406-f1dew1.rb", "extconf.rb"]
checking for -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:789:in `try_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
	from extconf.rb:6:in `<main>'
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.7.7/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /Library/Ruby/Site/2.6.0 -r ./siteconf20210203-22406-f1dew1.rb extconf.rb
Building has failed. See above output for more information on the failure.
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.7.7 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.7/gem_make.out
```

I also tried 
```
xcrun gem install fastlane
```
but got permission error:
```
...
Fetching artifactory-3.0.15.gem
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /Library/Ruby/Gems/2.6.0
```

**Comment by egor-sorokin** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

can't provide output of `fastlane env` because I wasn't able to install it

**Comment by ainame** [comment]
@egor-sorokin 

Hi. we've recently updated the document about the installation. We now don't recommend using "sudo" to install fastlane. Could you please try rbenv + Bundler to set up the project? System Ruby is already deprecated by Apple so you won't be able to use fastlane in that way soon. 
https://docs.fastlane.tools/getting-started/ios/setup/

If you really don't want to install Ruby, there is a way to install RubyGems to your own directories introduced by CocoaPods team. You can do the same for fastlane. Do that at your own risk. This is much safer than using "sudo" though.
https://guides.cocoapods.org/using/getting-started.html#sudo-less-installation
