### ISSUE TITLE
Get_provisioning_profile issue on CI Machine - decode parser error -

### ISSUE THREAD

**Issue by pjcau** [fastlane/fastlane#18114]
Hi All, 
I'm implementing the fastlane on CI machine. So I try the same code on local machine and it works.

So in the CI machine, get error from get_provisioning_profile.

##### Command executed
 get_provisioning_profile(
 	 app_identifier: "com.xxxx.yyy"
)
##### Complete output when running fastlane, including the stack trace and command used
<details>
Available session is not valid any more. Continuing with normal login.
[23:58:26]: Successfully logged in
[23:58:26]: Fetching profiles...
[23:58:27]: Verifying certificates...
[23:58:28]: [32mFound 1 matching profile(s)[0m
[23:58:28]: [33mDownloading provisioning profile...[0m
[23:58:28]: [32mSuccessfully downloaded provisioning profile...[0m
[23:58:28]: [31mFailure to decode /Users/AAAA/.jenkins/workspace/ZZZ_Release_AppStore_Testflight/AppStore_com.XXX.YY.mobileprovision. Exit: 1: security: cert import failed: UNIX[File exists]
security: problem decoding

</details>

<details>
  
[23:58:28]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': \e[31m[!] Error parsing provisioning profile at path '/Users/AAAA/.jenkins/workspace/ZZZ_Release_AppStore_Testflight/AppStore_com.XXX.YY.mobileprovision'\e[0m (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:33:in `parse'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:39:in `uuid'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/sigh/lib/sigh/manager.rb:39:in `install_profile'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/sigh/lib/sigh/manager.rb:26:in `start'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/actions/get_provisioning_profile.rb:20:in `run'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:62:in `block (2 levels) in parsing_binding'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/bin/fastlane:23:in `load'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/bin/fastlane:23:in `<main>'
/usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Error parsing provisioning profile at path '/Users/AAAA/.jenkins/workspace/ZZZ_Release_AppStore_Testflight/AppStore_com.XXX.YY.mobileprovision' (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:33:in `parse'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:39:in `uuid'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/sigh/lib/sigh/manager.rb:39:in `install_profile'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/sigh/lib/sigh/manager.rb:26:in `start'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/actions/get_provisioning_profile.rb:20:in `run'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:62:in `block (2 levels) in parsing_binding'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/bin/fastlane:23:in `load'
	from /usr/local/Cellar/fastlane/2.172.0/libexec/bin/fastlane:23:in `<main>'
</details>

### Environment

<details>
  <pre> [09:02:50]: [36m$ bundle exec fastlane env[0m
[09:02:50]: 
[09:02:50]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[09:02:57]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.7                                                 |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.172.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H114)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.3                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |
</pre>
</details>

**Comment by pjcau** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍
I Did it.
Thanks to bot
