### ISSUE TITLE
pilot fails after successfully uploading and processing TestFlight build

### ISSUE THREAD

**Issue by aksswami** [fastlane/fastlane#18117]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

bundle exec fastlane release

##### Complete output when running fastlane, including the stack trace and command used
```
01:38:09 
01:38:09 [01:38:09]: [31mfastlane finished with errors[0m
01:38:09 
01:38:09 Looking for related GitHub issues on fastlane/fastlane...
01:38:09 
01:38:11 ➡️  [33mUndefined method `status' for nil:NilClass (NoMethodError)[0m
01:38:11     https://github.com/fastlane/fastlane/issues/17910 [[31mopen[0m] 5 💬
01:38:11     2 weeks ago
01:38:11 
01:38:11 ➡️  [33mundefined method `id' for nil[0m
01:38:11     https://github.com/fastlane/fastlane/issues/17818 [[31mopen[0m] 2 💬
01:38:11     21 hours ago
01:38:11 
01:38:11 ➡️  [33mTaking screenshots: build working but "undefined method `each' for nil:NilClass "[0m
01:38:11     https://github.com/fastlane/fastlane/issues/17911 [[31mopen[0m] 2 💬
01:38:11     5 days ago
01:38:11 
01:38:11 and 302 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60status%27%20for%20nil&type=Issues&utf8=✓
01:38:11 
01:38:11 🔗  You can ⌘ + double-click on links to open them directly in your browser.
01:38:11 bundler: failed to load command: fastlane (/Users/XXXXXX/.gem/ruby/2.6.0/bin/fastlane)
01:38:11 /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/connect_api/api_client.rb:181:in `handle_response': [31m[!] undefined method `status' for nil:NilClass[0m (NoMethodError)
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:88:in `patch_beta_app_review_detail'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/2.6.0/forwardable.rb:230:in `patch_beta_app_review_detail'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:445:in `update_review_detail'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:223:in `update_beta_app_meta'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:153:in `distribute'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:61:in `upload'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:27:in `run'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
01:38:11 	from Fastfile:87:in `block in parsing_binding'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane.rb:33:in `call'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
01:38:11 	from Fastfile:22:in `block in parsing_binding'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane.rb:33:in `call'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
01:38:11 	from Fastfile:13:in `block in parsing_binding'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane.rb:33:in `call'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/gems/fastlane-2.172.0/bin/fastlane:23:in `<top (required)>'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/bin/fastlane:23:in `load'
01:38:11 	from /Users/XXXXXX/.gem/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli/exec.rb:63:in `load'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli/exec.rb:63:in `kernel_load'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli/exec.rb:28:in `run'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli.rb:497:in `exec'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli.rb:30:in `dispatch'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/cli.rb:24:in `start'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/exe/bundle:49:in `block in <top (required)>'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.2/exe/bundle:37:in `<top (required)>'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
01:38:11 	from /Users/XXXXXX/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
01:38:11 Build step 'Execute shell' marked build as failure
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.6                                       |
| Bundler?                    | false                                       |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Version               | 12.4                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-teams | 0.2.0   | ✅ Up-To-Date  |

</details>

<details>
  Moved from non-2FA to 2FA based authentication, and added public API key. `pilot` upload is successful and processing complete, but after that pilot exit out with an above error. This makes the lane fail.
</details>

**Comment by aksswami** [comment]
Duplicate:- https://github.com/fastlane/fastlane/issues/17910

**Comment by aksswami** [comment]
The issue was resolved after using a proper key with the correct issuer id.
