### ISSUE TITLE
[deliver] Deliver ignores api_key if FASTLANE_SESSION environment variable exists

### ISSUE THREAD

**Issue by Kaspik** [fastlane/fastlane#18162]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running deliver() with `api_key` provided and having `FASTLANE_SESSION` in `.env` - the `api_key` is ignored and command fails on session expired.

We have `FASTLANE_SESSION` saved for Enterprise account used in other fastlane lanes, so we can't remove it and we can't replace it as api_key is not supported for enterprise programs. But - `api_key` provided as a param should have the highest priority for `deliver` imho.

##### Command executed

`bundle exec fastlane update_app_info`

```
lane :update_app_info do |options|
      api_key = app_store_connect_api_key(key_id: classdojo_api_key_id, issuer_id: classdojo_api_key_issuer_id, key_filepath: File.absolute_path(classdojo_api_key_path), duration: 1200, in_house: false)
      skip_screenshots = options[:skip_screenshots]
      skip_metadata = options[:skip_metadata]
      force = options[:force]

      # Upload the build to iTunes Connect.
      deliver(
         api_key: api_key,
         skip_binary_upload: true,
         phased_release: true,
         automatic_release: false,
         skip_screenshots: skip_screenshots,
         skip_metadata: skip_metadata,
         submit_for_review: false,
         force: force
      )
   end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [20:18:16]: ------------------------------
[20:18:16]: --- Step: default_platform ---
[20:18:16]: ------------------------------
[20:18:16]: ----------------------------------------
[20:18:16]: --- Step: Verifying fastlane version ---
[20:18:16]: ----------------------------------------
[20:18:16]: Your fastlane version 2.173.0 matches the minimum requirement of 2.172.0  ✅
[20:18:17]: Driving the lane 'ios update_release_notes' 🚀
[20:18:17]: --------------------------------------------------------------------
[20:18:17]: --- Step: bundle exec fastlane deliver download_metadata --force ---
[20:18:17]: --------------------------------------------------------------------
[20:18:17]: $ bundle exec fastlane deliver download_metadata --force
[20:18:18]: ▸ [20:18:18]: Successfully loaded '/Users/kaspik/Documents/Vyvoj/ClassDojo/dojo-behavior-ios/fastlane/Deliverfile' 📄
[20:18:18]: ▸ +------------------------+--------------------------------------+
[20:18:18]: ▸ |             Detected Values from './Deliverfile'              |
[20:18:18]: ▸ +------------------------+--------------------------------------+
[20:18:18]: ▸ | submission_information | {:add_id_info_uses_idfa=>false,      |
[20:18:18]: ▸ |                        | :export_compliance_uses_encryption=  |
[20:18:18]: ▸ |                        | >false,                              |
[20:18:18]: ▸ |                        | :export_compliance_encryption_updat  |
[20:18:18]: ▸ |                        | ed=>false}                           |
[20:18:18]: ▸ +------------------------+--------------------------------------+
[20:18:18]: ▸ [20:18:18]: Login to App Store Connect (ios_enterprise@classdojo.com)
[20:18:19]: ▸ Available session is not valid any more. Continuing with normal login.
[20:18:19]: ▸ Session loaded from environment variable is not valid. Continuing with normal login.
[20:18:20]: ▸ Looking for related GitHub issues on fastlane/fastlane...
[20:18:20]: ▸ ➡️  `fastlane spaceauth` is failing with `2FA can only be performed in interactive mode`
[20:18:20]: ▸ https://github.com/fastlane/fastlane/issues/18094 [closed] 6 💬
[20:18:20]: ▸ 21 hours ago
[20:18:20]: ▸ ➡️  [spaceship] allow 2FA request only in interactive mode
[20:18:20]: ▸ https://github.com/fastlane/fastlane/pull/17854 [closed] 11 💬
[20:18:20]: ▸ a week ago
[20:18:20]: ▸ ➡️  "Need to acknowledge to Apple's Apple ID and Privacy statement" error when using fastlane with non-2FA account (yeah, I know...)
[20:18:20]: ▸ https://github.com/fastlane/fastlane/issues/18098 [closed] 127 💬
[20:18:20]: ▸ 5 hours ago
[20:18:20]: ▸ 🔗  You can ⌘ + double-click on links to open them directly in your browser.
[20:18:20]: ▸ bundler: failed to load command: fastlane (/Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane)
[20:18:20]: ▸ RuntimeError: [!] 2FA can only be performed in interactive mode
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:7:in `handle_two_step_or_factor'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:501:in `send_shared_login_request'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:805:in `do_login'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:390:in `login'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:352:in `login'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/runner.rb:36:in `login'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/runner.rb:22:in `initialize'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:163:in `new'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:163:in `block (2 levels) in run'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/bin/fastlane:23:in `<top (required)>'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane:23:in `load'
[20:18:20]: ▸ /Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane:23:in `<top (required)>'
[20:18:20]: -----------------------------------
[20:18:20]: --- Step: clean_build_artifacts ---
[20:18:20]: -----------------------------------
[20:18:20]: Cleaned up build artifacts 🐙
+---------------------------+--------------------------+
|                     Lane Context                     |
+---------------------------+--------------------------+
| DEFAULT_PLATFORM          | ios                      |
| PLATFORM_NAME             | ios                      |
| LANE_NAME                 | ios update_release_notes |
| SIGH_PROFILE_PATHS        |                          |
| DSYM_PATHS                |                          |
| DSYM_LATEST_UPLOADED_DATE |                          |
+---------------------------+--------------------------+
[20:18:20]: Exit status of command 'bundle exec fastlane deliver download_metadata --force' was 1 instead of 0.
[20:18:18]: Successfully loaded '/Users/kaspik/Documents/Vyvoj/ClassDojo/dojo-behavior-ios/fastlane/Deliverfile' 📄

+------------------------+--------------------------------------+
|             Detected Values from './Deliverfile'              |
+------------------------+--------------------------------------+
| submission_information | {:add_id_info_uses_idfa=>false,      |
|                        | :export_compliance_uses_encryption=  |
|                        | >false,                              |
|                        | :export_compliance_encryption_updat  |
|                        | ed=>false}                           |
+------------------------+--------------------------------------+

[20:18:18]: Login to App Store Connect (ios_enterprise@classdojo.com)
Available session is not valid any more. Continuing with normal login.
Session loaded from environment variable is not valid. Continuing with normal login.

Looking for related GitHub issues on fastlane/fastlane...

➡️  `fastlane spaceauth` is failing with `2FA can only be performed in interactive mode`
    https://github.com/fastlane/fastlane/issues/18094 [closed] 6 💬
    21 hours ago

➡️  [spaceship] allow 2FA request only in interactive mode
    https://github.com/fastlane/fastlane/pull/17854 [closed] 11 💬
    a week ago

➡️  "Need to acknowledge to Apple's Apple ID and Privacy statement" error when using fastlane with non-2FA account (yeah, I know...)
    https://github.com/fastlane/fastlane/issues/18098 [closed] 127 💬
    5 hours ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane)
RuntimeError: [!] 2FA can only be performed in interactive mode
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:7:in `handle_two_step_or_factor'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:501:in `send_shared_login_request'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:805:in `do_login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:390:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:352:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/runner.rb:36:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/runner.rb:22:in `initialize'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:163:in `new'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:163:in `block (2 levels) in run'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/bin/fastlane:23:in `<top (required)>'
  /Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane:23:in `load'
  /Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane:23:in `<top (required)>'

+------+--------------------------------------------------------+-------------+
|                              fastlane summary                               |
+------+--------------------------------------------------------+-------------+
| Step | Action                                                 | Time (in s) |
+------+--------------------------------------------------------+-------------+
| 1    | default_platform                                       | 0           |
| 2    | Verifying fastlane version                             | 0           |
| 💥   | bundle exec fastlane deliver download_metadata --force | 3           |
| 4    | clean_build_artifacts                                  | 0           |
+------+--------------------------------------------------------+-------------+

[20:18:20]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'bundle exec fastlane deliver download_metadata --force' was 1 instead of 0.
[20:18:18]: Successfully loaded '/Users/kaspik/Documents/Vyvoj/ClassDojo/dojo-behavior-ios/fastlane/Deliverfile' 📄

+------------------------+--------------------------------------+
|             Detected Values from './Deliverfile'              |
+------------------------+--------------------------------------+
| submission_information | {:add_id_info_uses_idfa=>false,      |
|                        | :export_compliance_uses_encryption=  |
|                        | >false,                              |
|                        | :export_compliance_encryption_updat  |
|                        | ed=>false}                           |
+------------------------+--------------------------------------+

[20:18:18]: Login to App Store Connect (ios_enterprise@classdojo.com)
Available session is not valid any more. Continuing with normal login.
Session loaded from environment variable is not valid. Continuing with normal login.

Looking for related GitHub issues on fastlane/fastlane...

➡️  `fastlane spaceauth` is failing with `2FA can only be performed in interactive mode`
    https://github.com/fastlane/fastlane/issues/18094 [closed] 6 💬
    21 hours ago

➡️  [spaceship] allow 2FA request only in interactive mode
    https://github.com/fastlane/fastlane/pull/17854 [closed] 11 💬
    a week ago

➡️  "Need to acknowledge to Apple's Apple ID and Privacy statement" error when using fastlane with non-2FA account (yeah, I know...)
    https://github.com/fastlane/fastlane/issues/18098 [closed] 127 💬
    5 hours ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane)
RuntimeError: [!] 2FA can only be performed in interactive mode
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:7:in `handle_two_step_or_factor'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:501:in `send_shared_login_request'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:805:in `do_login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:390:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:352:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/runner.rb:36:in `login'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/runner.rb:22:in `initialize'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:163:in `new'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:163:in `block (2 levels) in run'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/bin/fastlane:23:in `<top (required)>'
  /Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane:23:in `load'
  /Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane:23:in `<top (required)>'

  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/fast_file.rb:219:in `block in sh'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/fast_file.rb:218:in `sh'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/fast_file.rb:212:in `sh'
  Fastfile:484:in `block (2 levels) in parsing_binding'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/kaspik/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/bin/fastlane:23:in `<top (required)>'
  /Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane:23:in `load'
  /Users/kaspik/.rbenv/versions/2.7.2/bin/fastlane:23:in `<top (required)>' </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2                                        |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.2 (20D64)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1h  22 Sep 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.173.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                                  | Version      |
| ------------------------------------ | ------------ |
| did_you_mean                         | 1.4.0        |
| bundler                              | 2.1.4        |
| uri                                  | 0.10.0       |
| rake                                 | 13.0.3       |
| CFPropertyList                       | 3.0.3        |
| public_suffix                        | 4.0.6        |
| addressable                          | 2.7.0        |
| artifactory                          | 3.0.15       |
| atomos                               | 0.1.3        |
| aws-eventstream                      | 1.1.0        |
| aws-partitions                       | 1.424.0      |
| aws-sigv4                            | 1.2.2        |
| jmespath                             | 1.4.0        |
| aws-sdk-core                         | 3.112.0      |
| aws-sdk-kms                          | 1.42.0       |
| aws-sdk-s3                           | 1.88.0       |
| babosa                               | 1.0.4        |
| claide                               | 1.0.3        |
| colored2                             | 3.1.2        |
| cork                                 | 0.3.0        |
| nap                                  | 1.1.0        |
| open4                                | 1.3.4        |
| claide-plugins                       | 0.9.2        |
| colored                              | 1.2          |
| highline                             | 1.7.10       |
| commander-fastlane                   | 4.4.6        |
| faraday-net_http                     | 1.0.1        |
| multipart-post                       | 2.0.0        |
| ruby2_keywords                       | 0.0.4        |
| faraday                              | 1.3.0        |
| faraday-http-cache                   | 2.2.0        |
| rchardet                             | 1.8.0        |
| git                                  | 1.8.1        |
| rexml                                | 3.2.4        |
| kramdown                             | 2.3.0        |
| kramdown-parser-gfm                  | 1.1.0        |
| no_proxy_fix                         | 0.1.2        |
| sawyer                               | 0.8.2        |
| octokit                              | 4.20.0       |
| unicode-display_width                | 1.7.0        |
| terminal-table                       | 1.8.0        |
| danger                               | 8.2.2        |
| danger-duplicate_localizable_strings | 0.3.0        |
| thor                                 | 0.20.3       |
| danger-swiftlint                     | 0.24.5       |
| dotenv                               | 2.7.6        |
| emoji_regex                          | 3.2.1        |
| excon                                | 0.79.0       |
| unf_ext                              | 0.0.7.7      |
| unf                                  | 0.1.4        |
| domain_name                          | 0.5.20190701 |
| http-cookie                          | 1.0.3        |
| faraday-cookie_jar                   | 0.0.7        |
| faraday_middleware                   | 1.0.0        |
| fastimage                            | 2.2.2        |
| gh_inspector                         | 1.1.3        |
| jwt                                  | 2.2.2        |
| memoist                              | 0.16.2       |
| multi_json                           | 1.15.0       |
| os                                   | 1.1.1        |
| signet                               | 0.14.1       |
| googleauth                           | 0.15.0       |
| httpclient                           | 2.8.3        |
| mini_mime                            | 1.0.2        |
| declarative                          | 0.0.20       |
| declarative-option                   | 0.1.0        |
| uber                                 | 0.1.0        |
| representable                        | 3.0.4        |
| retriable                            | 3.1.2        |
| google-api-client                    | 0.38.0       |
| digest-crc                           | 0.6.3        |
| webrick                              | 1.7.0        |
| google-apis-core                     | 0.2.1        |
| google-apis-iamcredentials_v1        | 0.1.0        |
| google-apis-storage_v1               | 0.1.0        |
| google-cloud-env                     | 1.4.0        |
| google-cloud-errors                  | 1.0.1        |
| google-cloud-core                    | 1.5.0        |
| google-cloud-storage                 | 1.30.0       |
| json                                 | 2.5.1        |
| mini_magick                          | 4.11.0       |
| plist                                | 3.6.0        |
| rubyzip                              | 2.3.0        |
| security                             | 0.1.3        |
| naturally                            | 2.2.1        |
| simctl                               | 1.6.8        |
| slack-notifier                       | 2.3.2        |
| terminal-notifier                    | 2.0.0        |
| tty-screen                           | 0.8.1        |
| tty-cursor                           | 0.7.1        |
| tty-spinner                          | 0.9.3        |
| word_wrap                            | 1.0.0        |
| nanaimo                              | 0.3.0        |
| xcodeproj                            | 1.19.0       |
| rouge                                | 2.0.7        |
| xcpretty                             | 0.3.0        |
| xcpretty-travis-formatter            | 1.0.1        |
| xcresult                             | 0.2.1        |
| xcov                                 | 1.7.5        |
| danger-xcov                          | 0.5.0        |
</details>

*generated on:* **2021-02-09**
</details>

**Comment by Kaspik** [comment]
Seems related to https://github.com/fastlane/fastlane/pull/17854, but I'm not able to find out why...

**Comment by Kaspik** [comment]
Found an issue on our end. Closing.
