### ISSUE TITLE
Passing api-key to sigh via CLI doesn't work

### ISSUE THREAD

**Issue by JaviSoto** [fastlane/fastlane#18222]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Invoking `sigh` via the CLI doesn't allow passing the api-key as JSON.

##### Command executed
```bash
fastlane sigh download_all --api-key "\{\"key_id\":\"REDACTED\",\"issuer_id\":\"REDACTED\",\"key\":\"-----BEGIN\ PRIVATE\ KEY-----\\nREDACTED\n-----END\ PRIVATE\ KEY-----\",\"is_key_content_base64\":false,\"duration\":1200,\"in_house\":null\}" --platform ios --readonly true --output_path /tmp --team_id REDACTED
```

##### Complete output when running fastlane, including the stack trace and command used

<details>

```bash
[13:56:05]: ▸ /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/spaceship/lib/spaceship/connect_api/token.rb:44:in `create': [!] wrong number of arguments (given 1, expected 0) (ArgumentError)
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/download_all.rb:63:in `api_token'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/download_all.rb:12:in `download_all'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/manager.rb:35:in `download_all'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/commands_generator.rb:83:in `block (2 levels) in run'
[13:56:05]: ▸ from /nix/store/dr9033fcc519m36hyyhiwm9wkyp9lmkw-ruby2.6.6-commander-fastlane-4.4.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[13:56:05]: ▸ from /nix/store/dr9033fcc519m36hyyhiwm9wkyp9lmkw-ruby2.6.6-commander-fastlane-4.4.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
[13:56:05]: ▸ from /nix/store/dr9033fcc519m36hyyhiwm9wkyp9lmkw-ruby2.6.6-commander-fastlane-4.4.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[13:56:05]: ▸ from /nix/store/dr9033fcc519m36hyyhiwm9wkyp9lmkw-ruby2.6.6-commander-fastlane-4.4.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
[13:56:05]: ▸ from /nix/store/hvxg5npwjk5i0q1a5g4lcd479m4xn6hx-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/bin/fastlane:23:in `<top (required)>'
[13:56:05]: ▸ from /nix/store/hvxg5npwjk5i0q1a5g4lcd479m4xn6hx-fastlane-2.174.0/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
[13:56:05]: ▸ from /nix/store/hvxg5npwjk5i0q1a5g4lcd479m4xn6hx-fastlane-2.174.0/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
[13:56:05]: ▸ /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/spaceship/lib/spaceship/connect_api/token.rb:44:in `create': wrong number of arguments (given 1, expected 0) (ArgumentError)
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/download_all.rb:63:in `api_token'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/download_all.rb:12:in `download_all'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/manager.rb:35:in `download_all'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/commands_generator.rb:83:in `block (2 levels) in run'
[13:56:05]: ▸ from /nix/store/dr9033fcc519m36hyyhiwm9wkyp9lmkw-ruby2.6.6-commander-fastlane-4.4.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[13:56:05]: ▸ from /nix/store/dr9033fcc519m36hyyhiwm9wkyp9lmkw-ruby2.6.6-commander-fastlane-4.4.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
[13:56:05]: ▸ from /nix/store/dr9033fcc519m36hyyhiwm9wkyp9lmkw-ruby2.6.6-commander-fastlane-4.4.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[13:56:05]: ▸ from /nix/store/dr9033fcc519m36hyyhiwm9wkyp9lmkw-ruby2.6.6-commander-fastlane-4.4.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
[13:56:05]: ▸ from /nix/store/w9sg86s2j35p7rhakw7mf8a5qbwddclj-ruby2.6.6-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
[13:56:05]: ▸ from /nix/store/hvxg5npwjk5i0q1a5g4lcd479m4xn6hx-fastlane-2.174.0/lib/ruby/gems/2.6.0/gems/fastlane-2.174.0/bin/fastlane:23:in `<top (required)>'
[13:56:05]: ▸ from /nix/store/hvxg5npwjk5i0q1a5g4lcd479m4xn6hx-fastlane-2.174.0/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
[13:56:05]: ▸ from /nix/store/hvxg5npwjk5i0q1a5g4lcd479m4xn6hx-fastlane-2.174.0/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
[13:56:05]: ▸ Looking for related GitHub issues on fastlane/fastlane...
[13:56:05]: ▸ ➡️  Match: wrong number of arguments (given 1, expected 0)
[13:56:05]: ▸ https://github.com/fastlane/fastlane/issues/17437 [closed] 5 💬
[13:56:05]: ▸ 6 weeks ago
[13:56:05]: ▸ ➡️  DELIVER (2.150.0.rc3/4) always ask attribute whatsNew
[13:56:05]: ▸ https://github.com/fastlane/fastlane/issues/16700 [open] 75 💬
[13:56:05]: ▸ a day ago
[13:56:05]: ▸ ➡️  "Need to acknowledge to Apple's Apple ID and Privacy statement" error when using fastlane with non-2FA account (yeah, I know...)
[13:56:05]: ▸ https://github.com/fastlane/fastlane/issues/18098 [closed] 127 💬
[13:56:05]: ▸ a week ago
[13:56:05]: ▸ and 21 more at: https://github.com/fastlane/fastlane/search?q=wrong%20number%20of%20arguments%20%28given%201%2C%20expected%200%29&type=Issues&utf8=✓
[13:56:05]: ▸ 🔗  You can ⌘ + double-click on links to open them directly in your browser.
```

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                              |
| --------------------------- | ---------------------------------------------------------------------------------- |
| OS                          | 10.15.7                                                                            |
| Ruby                        | 2.6.6                                                                              |
| Bundler?                    | true                                                                               |
| Git                         | git version 2.30.1                                                                 |
| Installation Source         | /nix/store/hvxg5npwjk5i0q1a5g4lcd479m4xn6hx-fastlane-2.174.0/bin/.fastlane-wrapped |
| Host                        | Mac OS X 10.15.7 (19H512)                                                          |
| Ruby Lib Dir                | /nix/store/mw183g8j7k652nz9vqbd9d5kn2mnc93h-ruby-2.6.6/lib                         |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                                                         |
| Is contained                | false                                                                              |
| Is homebrew                 | false                                                                              |
| Is installed via Fabric.app | false                                                                              |
| Xcode Path                  | /Applications/Xcode12.4.app/Contents/Developer/                                    |
| Xcode Version               | 12.4                                                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "redacted" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
itc_team_name "Redacted"
itc_team_id "Redacted"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.174.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.5   | ✅ Up-To-Date  |
| fastlane-plugin-test_center               | 3.15.2  | ✅ Up-To-Date  |
| fastlane-plugin-sentry                    | 1.8.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| rake                                      | 13.0.3       |
| CFPropertyList                            | 3.0.3        |
| concurrent-ruby                           | 1.1.8        |
| i18n                                      | 1.8.9        |
| minitest                                  | 5.14.3       |
| tzinfo                                    | 2.0.4        |
| zeitwerk                                  | 2.4.2        |
| activesupport                             | 6.1.2.1      |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| artifactory                               | 3.0.15       |
| jwt                                       | 2.1.0        |
| atlassian-jwt                             | 0.2.0        |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.427.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.112.0      |
| aws-sdk-kms                               | 1.42.0       |
| aws-sdk-s3                                | 1.88.1       |
| babosa                                    | 1.0.4        |
| bundler                                   | 2.1.4        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| colorize                                  | 0.8.1        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.3        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.1        |
| excon                                     | 0.79.0       |
| faraday-net_http                          | 1.0.1        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.4        |
| faraday                                   | 1.3.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.2        |
| gh_inspector                              | 1.1.3        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.1       |
| googleauth                                | 0.15.1       |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| rexml                                     | 3.2.4        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.2.1        |
| google-apis-iamcredentials_v1             | 0.1.0        |
| google-apis-storage_v1                    | 0.2.0        |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.30.0       |
| json                                      | 2.5.1        |
| mini_magick                               | 4.11.0       |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.1        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.2.5        |
| fastlane-plugin-sentry                    | 1.8.0        |
| trainer                                   | 0.9.1        |
| xctest_list                               | 1.2.1        |
| fastlane-plugin-test_center               | 3.15.2       |
| oauth                                     | 0.5.5        |
| jira-ruby                                 | 2.1.5        |
| xcode-install                             | 2.6.8        |
</details>

*generated on:* **2021-02-16**
</details>

**Comment by lilyball** [comment]
Ultimately the problem is the `:api_key` config option ends up as a Hash with string keys. If you change the caller to use `**` you get a new error saying the hash's keys aren't symbols.

I think the best solution here is to extend `FastlaneCore::ConfigItem` to let you mark the option as needing symbolized keys (possibly as an alternative type value, or as an extra flag that only applies to hashes) which will then pass the appropriate option to `JSON.parse`. Alternatively it could post-process the item value (does `verify_block` get a reference to the value that can be mutated, e.g. `verify_block: proc { |value| value.transform_keys!(&:to_sym) }`, but I question whether this is the only config item that wants symbolized keys.

**Comment by tomvisions** [comment]
Which would be the preferred way to download all profiles using api authentication? Using the command line or using sigh(api_key: api_key) (as an example?) with a download_all option available? From what I can tell, download_all works using the command line, but you have issues with api authentication. Api authentication works when using sigh within fastlane, however, no option to do a download_all.

**Comment by Fisher95856** [comment]
It's important to protect your API from unauthorized access. (For the extra credit section, not required) cURL installed on your machine to make API calls from the command line. Go to https://apigee.com/edge and sign in.

**Comment by raghavmathur1993** [comment]
Any update on fixing this? I am getting the below error on fast lane deliver() step 
```
deliver(
        submit_for_review: false,
        force: true,
        api_key_path: "./path/to/json/file",
        precheck_include_in_app_purchases: false
      )
```

Error:

> 
> [16:14:14]: fastlane finished with errors
> 
> Looking for related GitHub issues on fastlane/fastlane...
> 
> ➡️  Passing api-key to sigh via CLI doesn't work
>     https://github.com/fastlane/fastlane/issues/18222 [open] 2 💬
>     an hour ago
> 
> ➡️  Match: wrong number of arguments (given 1, expected 0)
>     https://github.com/fastlane/fastlane/issues/17437 [closed] 5 💬
>     03 Jan 2021
> 
> ➡️  DELIVER (2.150.0.rc3/4) always ask attribute whatsNew
>     https://github.com/fastlane/fastlane/issues/16700 [open] 75 💬
>     a week ago
>

**Comment by wibbly13** [comment]
I experienced a similar problem. [This](https://docs.fastlane.tools/app-store-connect-api/#use-return-value-and-pass-in-as-an-option) solved the problem.
