### ISSUE TITLE
Cannot upload IPA to testflight

### ISSUE THREAD

**Issue by yargolan** [fastlane/fastlane#18228]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to upload via fastlane ends with an exception.
The exception doesn't say much and very not informative.
Tried to run it with --verbose didn't reveal much

##### Command executed
fastlane upload_to_testflight

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[17:00:49]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[17:00:49]: Going to upload updated app to App Store Connect
[17:00:49]: This might take a few minutes. Please don't interrupt the script.
[17:00:50]: [iTMSTransporter] java.lang.reflect.InvocationTargetException

[17:00:50]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[17:00:50]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[17:00:50]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[17:00:50]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

[17:00:50]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:450)

[17:00:50]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:947)

[17:00:50]: [iTMSTransporter] Caused by: java.io.IOException: Could not connect to any repositories

[17:00:50]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.getRepositoryUriAndEtag(RemoteBundleRepository.java:227)

[17:00:50]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.loadResourcesFromRepository(RemoteBundleRepository.java:141)

[17:00:50]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.downloadNeededBundles(BootstrapperPhase1.java:247)

[17:00:50]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:97)

[17:00:50]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)

[17:00:50]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)

[17:00:50]: [iTMSTransporter] 	... 6 more

[17:00:50]: iTunes Transporter output above ^
[17:00:50]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------+------------------------------+
|                  Lane Context                   |
+------------------+------------------------------+
| DEFAULT_PLATFORM | ios                          |
| PLATFORM_NAME    | ios                          |
| LANE_NAME        | ios upload_ipa_to_testflight |
+------------------+------------------------------+
[17:00:50]: Error uploading ipa file, for more information see above

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | upload_to_testflight       | 13          |
+------+----------------------------+-------------+

[17:00:51]: fastlane finished with errors

[!] Error uploading ipa file, for more information see above</pre>
</details>

### Environment

<details>
  <pre>
➜ fastlane env
[✔] 🚀
[17:03:08]: fastlane detected a Gemfile in the current directory
[17:03:08]: However, it seems like you didn't use `bundle exec`
[17:03:08]: To launch fastlane faster, please use
[17:03:08]:
[17:03:08]: $ bundle exec fastlane env
[17:03:08]:
[17:03:08]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:03:17]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.7                                                 |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.174.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H524)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.4                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.25.0"

default_platform :ios

platform :ios do

    lane :upload_ipa_to_testflight do
      upload_to_testflight(
        username: "xxxxxxxxx@gmail.com",
        skip_waiting_for_build_processing: true,
        ipa: "xxxxx.ipa"
        )
    end

end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.174.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.1.4        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.1       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.15.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| rexml                         | 3.2.3        |
| webrick                       | 1.6.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.1        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.426.0      |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.0       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| open3                         | 0.1.0        |
| singleton                     | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-02-17**

</pre>
</details>

**Comment by Suri1044** [comment]
Even I am unable to upload to TestFlight using fastlane.
Details:
**Fastlane version:** 2.174.0
**Error:** 
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '.8.12' in the Info.plist file at '${bundlePath}' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at

Note: 1. We are using the right version of our app and somehow it is logging wrong error.
           2. Issue is failing on upload ie, on pilot.
           
 ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV #"
    pilot(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      skip_submission: true,
      skip_waiting_for_build_processing: true
    ) 

3. upload working fine on appcenter

**Comment by max-ott** [comment]
@Suri1044 the ERROR ITMS comes directly from Apple. The short version string is incorrect. It can't start with a `.` (dot). This has nothing to do with this issue and fastlane.

@yargolan I think there was a similar issue. The problem is that the error message gets truncated and does not show the full issue of ITMSTransporter (Apple's upload tool) Can you upload via the Transporter.app without any problems?
