### ISSUE TITLE
[gym] `crash!': Couldn't find application in '<archive>.xcarchive' (FastlaneCore::Interface::FastlaneCrash)

### ISSUE THREAD

**Issue by akselilukkarila** [fastlane/fastlane#18317]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After successful archive, fastlane gym crashes with `Couldn't find application in 'launcher.xcarchive' (FastlaneCore::Interface::FastlaneCrash)`

##### Command executed

`fastlane gym` / `fastlane gym --verbose`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> INFO [2021-03-02 19:02:24.26]: ▸ Archive Succeeded
INFO [2021-03-02 19:02:24.54]: Successfully stored the archive. You can find it in the Xcode Organizer.
DEBUG [2021-03-02 19:02:24.54]: Stored the archive in: launcher.xcarchive

Looking for related GitHub issues on fastlane/fastlane...
Search query: Couldn't find application in 'launcher.xcarchive'

URL: https://api.github.com/search/issues?q=Couldn%27t%20find%20application%20in%20%27launcher.xcarchive%27+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	16: from /usr/local/Cellar/fastlane/2.176.0/libexec/bin/fastlane:23:in `<main>'
	15: from /usr/local/Cellar/fastlane/2.176.0/libexec/bin/fastlane:23:in `load'
	14: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/bin/fastlane:23:in `<top (required)>'
	13: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	12: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/commands_generator.rb:15:in `start'
	11: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/commands_generator.rb:75:in `run'
	10: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 9: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 8: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 7: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 6: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 5: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/commands_generator.rb:44:in `block (2 levels) in run'
	 4: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/manager.rb:19:in `work'
	 3: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/runner.rb:47:in `run'
	 2: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/runner.rb:277:in `copy_mac_app'
	 1: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Couldn't find application in 'launcher.xcarchive' (FastlaneCore::Interface::FastlaneCrash)
	16: from /usr/local/Cellar/fastlane/2.176.0/libexec/bin/fastlane:23:in `<main>'
	15: from /usr/local/Cellar/fastlane/2.176.0/libexec/bin/fastlane:23:in `load'
	14: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/bin/fastlane:23:in `<top (required)>'
	13: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	12: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/commands_generator.rb:15:in `start'
	11: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/commands_generator.rb:75:in `run'
	10: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 9: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 8: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 7: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 6: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 5: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/commands_generator.rb:44:in `block (2 levels) in run'
	 4: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/manager.rb:19:in `work'
	 3: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/runner.rb:47:in `run'
	 2: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/gym/lib/gym/runner.rb:277:in `copy_mac_app'
	 1: from /usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.176.0/libexec/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': \e[31m[!] Couldn't find application in 'launcher.xcarchive'\e[0m (FastlaneCore::Interface::FastlaneCrash) </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.7                                                 |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.176.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H524)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.4                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.176.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.1.4        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.1       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.15.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| rexml                         | 3.2.3        |
| webrick                       | 1.6.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.429.0      |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.1       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| open3                         | 0.1.0        |
| singleton                     | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-03-02**
</details>

**Comment by akselilukkarila** [comment]
Issue was that the app path inside the Xcode archive was different from what gym was expecting. Changing the _installation path_ option in Xcode from `$(HOME)/Applications` to `/Applications` fixed the issue. *However, it would be great to improve this from the gym side*, to have a more meaningful error message that clearly indicates what the problem is, instead of a hard crash. We had to go looking into the gym source code where the error message comes from to understand what was happening...
