### ISSUE TITLE
(supply): Could not find option 'key' in the list of available options: json_key, json_key_data, root_url, timeout

### ISSUE THREAD

**Issue by andreialecu** [fastlane/fastlane#18338]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Been scratching my head for a while regarding this error. It seems that I cannot connect to Google Play using supply. The JSON file does not seem to validate.

##### Command executed

The json file looks like: 

```json
{
  "type": "service_account",
  "project_id": "...",
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----\n...",
  "client_email": "...",
  "client_id": "...",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/..."
}

```

`fastlane run validate_play_store_json_key google-play-auth.json --verbose`

```
ERROR [2021-03-05 12:21:53.67]: Could not establish a connection to Google Play Store with this json key file.
ERROR [2021-03-05 12:21:53.67]: Could not find option 'key' in the list of available options: json_key, json_key_data, root_url, timeout
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:332:in `verify_options_key!'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:215:in `fetch'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/supply/lib/supply/client.rb:116:in `service_account_authentication'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/supply/lib/supply/client.rb:18:in `make_from_config'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/actions/validate_play_store_json_key.rb:14:in `run'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
/Users/andreialecu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/bin/fastlane:23:in `<top (required)>'
/Users/andreialecu/.rbenv/versions/2.7.2/bin/fastlane:23:in `load'
/Users/andreialecu/.rbenv/versions/2.7.2/bin/fastlane:23:in `<main>'
```

##### Complete output when running fastlane, including the stack trace and command used

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2.2                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.2.2 (20D80)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
    yarn(step_name: 'install_dependencies')
    yarn(command: 'gql-codegen', step_name: 'gql_codegen')
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    changelog = prompt(text: "Changelog: ")

    match(type: "appstore", readonly: is_ci)
    cocoapods(podfile: "./ios/Podfile")
    increment_build_number(xcodeproj: "./ios/ProjectSport.xcodeproj", build_number: latest_testflight_build_number + 1)
    build_app(workspace: "./ios/ProjectSport.xcworkspace", scheme: "ProjectSport", configuration: "Release")
    upload_to_testflight(
      distribute_external: true,
      groups: ["Public Beta"],
      changelog: changelog
    )
  end
end

platform :android do
  before_all do
    setup_circle_ci
  end

  desc "Push a new beta build to Google Play"
  lane :beta do
    android_set_version_code(
      gradle_file: 'android/app/build.gradle'
    )
    gradle(
      project_dir: 'android',
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["KEY_STORE_FILE"],
        "android.injected.signing.store.password" => ENV["KEY_STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
      }
    )
    #upload_to_play_store(track: 'internal')
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.176.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-versioning_android | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-yarn               | 1.2     | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.5.0        |
| slack-notifier                     | 2.3.2        |
| atomos                             | 0.1.3        |
| CFPropertyList                     | 3.0.3        |
| claide                             | 1.0.3        |
| colored2                           | 3.1.2        |
| nanaimo                            | 0.3.0        |
| xcodeproj                          | 1.19.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| plist                              | 3.6.0        |
| public_suffix                      | 4.0.6        |
| addressable                        | 2.7.0        |
| multipart-post                     | 2.0.0        |
| word_wrap                          | 1.0.0        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| artifactory                        | 3.0.15       |
| babosa                             | 1.0.4        |
| colored                            | 1.2          |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| excon                              | 0.79.0       |
| faraday-net_http                   | 1.0.1        |
| ruby2_keywords                     | 0.0.4        |
| faraday                            | 1.3.0        |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.7        |
| faraday_middleware                 | 1.0.0        |
| gh_inspector                       | 1.1.3        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| rubyzip                            | 2.3.0        |
| security                           | 0.1.3        |
| xcpretty-travis-formatter          | 1.0.1        |
| dotenv                             | 2.7.6        |
| simctl                             | 1.6.8        |
| jwt                                | 2.2.2        |
| uber                               | 0.1.0        |
| declarative                        | 0.0.20       |
| declarative-option                 | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.2        |
| mini_mime                          | 1.0.2        |
| httpclient                         | 2.8.3        |
| google-api-client                  | 0.38.0       |
| google-cloud-env                   | 1.4.0        |
| google-cloud-errors                | 1.0.1        |
| google-cloud-core                  | 1.5.0        |
| google-apis-core                   | 0.2.1        |
| google-apis-iamcredentials_v1      | 0.1.0        |
| google-apis-storage_v1             | 0.2.0        |
| rake                               | 13.0.3       |
| digest-crc                         | 0.6.3        |
| google-cloud-storage               | 1.30.0       |
| uri                                | 0.10.1       |
| fastimage                          | 2.2.3        |
| json                               | 2.5.1        |
| bundler                            | 2.2.9        |
| multi_json                         | 1.15.0       |
| signet                             | 0.15.0       |
| os                                 | 1.1.1        |
| memoist                            | 0.16.2       |
| googleauth                         | 0.16.0       |
| rexml                              | 3.2.4        |
| webrick                            | 1.7.0        |
| emoji_regex                        | 3.2.2        |
| aws-eventstream                    | 1.1.1        |
| aws-sigv4                          | 1.2.3        |
| aws-partitions                     | 1.431.0      |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.112.1      |
| aws-sdk-kms                        | 1.42.0       |
| aws-sdk-s3                         | 1.89.0       |
| forwardable                        | 1.3.2        |
| logger                             | 1.4.3        |
| cgi                                | 0.2.0        |
| date                               | 3.1.1        |
| timeout                            | 0.1.1        |
| stringio                           | 3.0.0        |
| zlib                               | 1.1.0        |
| openssl                            | 2.2.0        |
| ipaddr                             | 1.2.2        |
| ostruct                            | 0.3.3        |
| strscan                            | 3.0.0        |
| delegate                           | 0.2.0        |
| fileutils                          | 1.5.0        |
| io-console                         | 0.5.8        |
| open3                              | 0.1.1        |
| singleton                          | 0.1.1        |
| yaml                               | 0.1.1        |
| psych                              | 3.3.0        |
| mutex_m                            | 0.1.1        |
| fastlane-plugin-versioning_android | 0.1.0        |
| fastlane-plugin-yarn               | 1.2          |
</details>

*generated on:* **2021-03-05**
</details>

I also tried with the system ruby (`ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]`), but got the same error.

**Comment by andreialecu** [comment]
It appears that the correct syntax of the CLI command is:

`fastlane run validate_play_store_json_key json_key:google-play-auth.json`

My bad.
