### ISSUE TITLE
Fastlane gradle task crashes on GCP build (Docker)

### ISSUE THREAD

**Issue by landry42** [fastlane/fastlane#18435]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to deploy my android on with fastlane on an preconfigured docker with fastlane and bundler on GCP build.
But when I want to use Fastlane, it crashes on the gradle command. 😕 

##### Command executed
bundle exec fastlane alpha

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> 
[15:05:24]: It seems like you wanted to load some plugins, however they couldn't be loaded
[15:05:24]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
[15:05:24]: ------------------------------
[15:05:24]: --- Step: default_platform ---
[15:05:24]: ------------------------------
[15:05:24]: Driving the lane 'android alpha' 🚀
[15:05:24]: ----------------------------------------
[15:05:24]: --- Step: changelog_from_git_commits ---
[15:05:24]: ----------------------------------------
[15:05:24]: $ git rev-list --tags --max-count\=1
[15:05:24]: Collecting Git commits between  and HEAD

[15:05:24]: ---------------------------
[15:05:24]: --- Step: bundleRelease ---
[15:05:24]: ---------------------------
[15:05:24]: $ /workspace/android/gradlew bundleRelease -p /workspace/android
+-------------------+---------------+
|           Lane Context            |
+-------------------+---------------+
| DEFAULT_PLATFORM  | android       |
| PLATFORM_NAME     | android       |
| LANE_NAME         | android alpha |
| FL_CHANGELOG      |               |
| GRADLE_BUILD_TYPE | Release       |
+-------------------+---------------+
[15:05:24]: Permission denied - /workspace/android/gradlew

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | changelog_from_git_co  | 0           |
|      | mmits                  |             |
| 💥   | bundleRelease          | 0           |
+------+------------------------+-------------+

[15:05:24]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/bin/fastlane)
/usr/lib/ruby/2.7.0/open3.rb:213:in `spawn': \e[31m[!] Permission denied - /workspace/android/gradlew\e[0m (Errno::EACCES)
	from /usr/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
	from /usr/lib/ruby/2.7.0/open3.rb:208:in `popen2e'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
	from /usr/lib/ruby/2.7.0/forwardable.rb:235:in `sh'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:28:in `block (2 levels) in parsing_binding'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/bin/fastlane:23:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/cli/exec.rb:63:in `load'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/cli/exec.rb:28:in `run'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/cli.rb:494:in `exec'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/cli.rb:30:in `dispatch'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/cli.rb:24:in `start'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/exe/bundle:49:in `block in <top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/exe/bundle:37:in `<top (required)>'
	from /usr/bin/bundle:23:in `load'
	from /usr/bin/bundle:23:in `<main>'
 </pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                                               |
| --------------------------- | ------------------------------------------------------------------------------------------------------------------- |
| OS                          | Linux fa30b99e24dc 5.4.0-1036-gcp #39~18.04.1-Ubuntu SMP Sun Jan 17 11:08:21 UTC 2021 x86_64 Linux                  |
| Ruby                        | 2.7.2                                                                                                               |
| Bundler?                    | true                                                                                                                |
| Git                         | git version 2.30.2                                                                                                  |
| Installation Source         | /usr/bin/fastlane                                                                                                   |
| Host                        | Linux fa30b99e24dc 5.4.0-1036-gcp #39~18.04.1-Ubuntu SMP Sun Jan 17 11:08:21 UTC 2021 x86_64 Linux (5.4.0-1036-gcp) |
| Ruby Lib Dir                | /usr/lib                                                                                                            |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                                                                                          |
| Is contained                | false                                                                                                               |
| Is homebrew                 | false                                                                                                               |
| Is installed via Fabric.app | false                                                                                                               |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal test Build the Google play"
  lane :alpha do
    changelog_from_git_commits

    gradle(
      project_dir: '/workspace/android',
      gradle_path: 'gradlew',
      task: 'bundle',
      build_type: 'Release'
    )

    upload_to_play_store(
      track: 'alpha'
      # release_status: 'draft'
    )
    
    # gradle(task: "clean assembleRelease")
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    changelog_from_git_commits
    
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    upload_to_play_store(track: 'beta')
    
    # gradle(task: "clean assembleRelease")
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("gc_keys.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.gamifaction.twinty") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.5.0        |
| bundler                       | 2.2.14       |
| uri                           | 0.10.1       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.433.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.91.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-03-21**
</details>
[15:05:21]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[15:05:21]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by landry42** [comment]
OK, solution found... I ignored that GCP build disabled automatically the execution rights...
Just have to add the step:
`name: <YOUR IMAGE>`
`args: ["bash", "-c", "chmod +x gradlew"]`
`dir: <ANDROID PROJECT PATH>`
Sorry for the disturbance...
