### ISSUE TITLE
"Unable to capture screenshot" starting from API29 on clean emulated device

### ISSUE THREAD

**Issue by tenzap** [fastlane/fastlane#18461]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This is sort of a continuation of #15886 which was closed automatically

### Steps to reproduce
First of all:
1. remove the directory created by screengrab for the package at the root of the external_storage (/sdcard it seems)
For me it was com.exifthumbnailadder.app
2. uninstall the package

Then try to launch `./gradlew assembleDebug assembleAndroidTest`
followed by `fastlane screengrab` by setting the targetSdkVersion like below in this exact order.

3. _targetSdkVersion 30_
--> Error java.lang.RuntimeException: Unable to capture screenshot.
Directory at the root of external_storage doesn't exist

4. _targetSdkVersion 29_
--> Error java.lang.RuntimeException: Unable to capture screenshot.
Directory at the root of external_storage doesn't exist

5. _targetSdkVersion 28_
--> Works (screenshot is taken)
Directory at the root of external_storage now exists

6. _targetSdkVersion 29 or 30_
--> Now works (screenshot is taken)

My project uses compileSdkVersion 30, device is running Android 10 (ie api29)

So, on a clean emulated device, there is an error if targetSdk>=29
Once the test has been run at least once with targetSdk<=28, rerunning with targetSdk > 29 works.

Looks like a permission issue or something like that? I remember getExternalStorage... is deprecated since API29, maybe this is the reason ?

##### Command executed
`fastlane screengrab`

##### Complete output when running fastlane, including the stack trace and command used
`java.lang.RuntimeException: Unable to capture screenshot.`

<details>
```
[13:42:41]: ▸ com.exifthumbnailadder.app.ExampleInstrumentedTest:
[13:42:41]: ▸ Error in testTakeScreenshot(com.exifthumbnailadder.app.ExampleInstrumentedTest):
[13:42:41]: ▸ java.lang.RuntimeException: Unable to capture screenshot.
[13:42:41]: ▸   at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:56)
[13:42:41]: ▸   at tools.fastlane.screengrab.UiAutomatorScreenshotStrategy.takeScreenshot(UiAutomatorScreenshotStrategy.java:39)
[13:42:41]: ▸   at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
[13:42:41]: ▸   at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
[13:42:41]: ▸   at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)
[13:42:41]: ▸   at com.exifthumbnailadder.app.ExampleInstrumentedTest.testTakeScreenshot(ExampleInstrumentedTest.java:45)
[13:42:41]: ▸   at java.lang.reflect.Method.invoke(Native Method)
[13:42:41]: ▸   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[13:42:41]: ▸   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[13:42:41]: ▸   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[13:42:41]: ▸   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[13:42:41]: ▸   at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:549)
[13:42:41]: ▸   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[13:42:41]: ▸   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[13:42:41]: ▸   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[13:42:41]: ▸   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[13:42:41]: ▸   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[13:42:41]: ▸   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[13:42:41]: ▸   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[13:42:41]: ▸   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[13:42:41]: ▸   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[13:42:41]: ▸   at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:32)
[13:42:41]: ▸   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[13:42:41]: ▸   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:42:41]: ▸   at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
[13:42:41]: ▸   at org.junit.runners.Suite.runChild(Suite.java:128)
[13:42:41]: ▸   at org.junit.runners.Suite.runChild(Suite.java:27)
[13:42:41]: ▸   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[13:42:41]: ▸   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[13:42:41]: ▸   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[13:42:41]: ▸   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[13:42:41]: ▸   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[13:42:41]: ▸   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[13:42:41]: ▸   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[13:42:41]: ▸   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[13:42:41]: ▸   at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[13:42:41]: ▸   at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
[13:42:41]: ▸   at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
[13:42:41]: ▸ Caused by: java.io.IOException: Unable to get a screenshot storage directory
[13:42:41]: ▸   at tools.fastlane.screengrab.FileWritingScreenshotCallback.getFilesDirectory(FileWritingScreenshotCallback.java:81)
[13:42:41]: ▸   at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:39)
[13:42:41]: ▸   ... 37 more
```
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | debian_based 10.9                                       |
| Ruby                        | 2.5.5                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.20.1                                      |
| Installation Source         | /usr/local/bin/fastlane                                 |
| Host                        | Debian GNU/Linux 10 debian_based 10.9 (4.19.0-14-amd64) |
| Ruby Lib Dir                | /usr/lib                                                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | fr:en_US    | 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

opt_out_usage

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.exifthumbnailadder.app") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.179.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.2.1        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.15       |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.3        |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.2.4        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.436.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| excon                         | 0.79.0       |
| json                          | 2.5.1        |
| multi_json                    | 1.15.0       |
| webrick                       | 1.7.0        |
| rake                          | 13.0.3       |
| date                          | 1.0.0        |
| stringio                      | 0.0.1        |
| zlib                          | 1.0.0        |
| openssl                       | 2.1.2        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.0.2        |
| etc                           | 1.0.0        |
| ipaddr                        | 1.2.0        |
| psych                         | 3.0.2        |
</details>

**Comment by tenzap** [comment]
Using
`androidTestImplementation 'tools.fastlane:screengrab:2.0.0'`
 instead of
`androidTestImplementation 'tools.fastlane:screengrab:1.2.0'`
seems to fix the problem

The doc is slightly outdated because it links to https://rubygems.org/gems/screengrab which says the last version is 1.0.0 while it is 2.0.0
