### ISSUE TITLE
Supply promote_track fails, when there is a draft release

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#18470]
Supply `track_promote_to` fails, when there is a draft `release`.

Small debug showed, that this line fails:
https://github.com/fastlane/fastlane/blob/d21cda030555531b1138f1af045c7d716eb938bb/supply/lib/supply/uploader.rb#L178
As draft release doesn't have a `version_codes` field:
`#<Google::Apis::AndroidpublisherV3::TrackRelease:0x000000000484e898 @status="draft">`

As a workaround I discarded the draft release and Supply succeeded.

##### Command executed

`fastlane run supply --track_promote_to --version_code`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Traceback (most recent call last):
        17: from /usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
        16: from /usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
        15: from /usr/local/rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
        14: from /usr/local/rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
        13: from /usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
        12: from /usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
        11: from /usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/supply/lib/supply/commands_generator.rb:12:in `start'
        10: from /usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/supply/lib/supply/commands_generator.rb:60:in `run'
         9: from /usr/local/rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
         8: from /usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         7: from /usr/local/rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         6: from /usr/local/rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         5: from /usr/local/rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         4: from /usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/supply/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
         3: from /usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/supply/lib/supply/uploader.rb:26:in `perform_upload'
         2: from /usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/supply/lib/supply/uploader.rb:179:in `promote_track'
         1: from /usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/supply/lib/supply/uploader.rb:179:in `select'
/usr/local/rvm/gems/ruby-2.5.1/gems/fastlane-2.179.0/supply/lib/supply/uploader.rb:182:in `block in promote_track': [!] undefined method `include?' for nil:NilClass (NoMethodError) </pre>
</details>

**Comment by yakimant** [comment]
@fastlane-bot, env is not related I guess.
