### ISSUE TITLE
update_project_provisioning.rb:74:in `block (2 levels) in run': \e[31m[!] undefined method `[]' for nil:NilClass\e[0m (NoMethodError)

### ISSUE THREAD

**Issue by leonardommello** [fastlane/fastlane#18486]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using update_project_provisioning to set my development provisioning profile, it crashes because the script wasn't able to parse the provisioning profile.

##### Command executed

/usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:74:in `block (2 levels) in run': \e[31m[!] undefined method `[]' for nil:NilClass\e[0m (NoMethodError)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 	30: from /usr/local/Cellar/fastlane/2.179.0/libexec/bin/fastlane:23:in `<main>'
	29: from /usr/local/Cellar/fastlane/2.179.0/libexec/bin/fastlane:23:in `load'
	28: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
	27: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	26: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	25: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	24: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	23: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	22: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	21: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	20: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	19: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	18: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	17: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	16: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	15: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	14: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	13: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	12: from Fastfile:45:in `block (2 levels) in parsing_binding'
	11: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	10: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 9: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 8: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 7: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 6: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 5: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 4: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:49:in `run'
	 3: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:49:in `each'
	 2: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:57:in `block in run'
	 1: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:57:in `each'
/usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:73:in `block (2 levels) in run': \e[31m[!] undefined method `[]' for nil:NilClass\e[0m (NoMethodError)</pre>
</details>

### Environment

<details><summary>?? fastlane environment ??</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.7                                                 |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.21.1 (Apple Git-122.3)                    |
| Installation Source         | /usr/local/Cellar/fastlane/2.179.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H2)                                 |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode_11.3.1.app/Contents/Developer/      |
| Xcode Version               | 11.3.1                                                  |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found ?? |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

            default_platform(:ios)
                platform :ios do
                desc "Description of what the lane does"
                lane :build do
                    update_app_identifier(
                        plist_path:"Info.plist",
                        app_identifier:"com.pilotgames.gameclient",
                        xcodeproj:"Unity-iPhone.xcodeproj"
                    )
                    update_info_plist(
                        plist_path:"Info.plist",
                        display_name:"Pilot Head",
                        app_identifier:"com.pilotgames.gameclient"
                    )
                    set_info_plist_value(
                        path:"Info.plist",
                        key: "UIFileSharingEnabled",
                        value: true
                    )
                    set_info_plist_value(
                        path:"Info.plist",
                        key: "UIRequiresFullScreen",
                        value: true
                    )
                    set_info_plist_value(
                        path:"Info.plist",
                        key: "UIStatusBarHidden~ipad",
                        value: true
                    )
                    set_info_plist_value(
                        path:"Info.plist",
                        key:"CFBundleShortVersionString",
                        value: "21.3.2.11"
                    )
                    set_info_plist_value(
                        path:"Info.plist",
                        key:"CFBundleVersion",
                        value: "11"
                    )
                    update_project_team(
                        path:"Unity-iPhone.xcodeproj",
                        teamid:"ZZJJ4HBLFS"
                    )
                    update_project_provisioning(
                        xcodeproj:"Unity-iPhone.xcodeproj",
                        build_configuration:"Release",
                        code_signing_identity:"iPhone Distribution: Maxbet Group LLC",
                        certificate:"/Users/pilot/BuildAgent/work/84081a2600a41255/pulltab.ios/developer_certificates/enterprise/ios_distribution_devel1_enterprise.cer",
                        profile:"/Users/pilot/BuildAgent/work/84081a2600a41255/pulltab.ios/developer_certificates/enterprise/Pilot_Games_Head.mobileprovision"
                    )
                    build_app(
                        scheme:"Unity-iPhone",
                        clean:true,
                        include_bitcode:false,
                        export_options:{
                            method:"enterprise",
                            provisioningProfiles:{
                                "com.pilotgames.gameclient" => "Pilot Games Head"
                                }
                        }
                    )
                end
            end
        
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.179.0 | ? Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.1.4        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.3        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.2.3        |
| webrick                       | 1.6.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.435.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| open3                         | 0.1.0        |
| singleton                     | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-03-30**
</details>

**Comment by leonardommello** [comment]
the problem is apparently occurring with the certificate parameter. 

https://docs.fastlane.tools/actions/update_project_provisioning/
