### ISSUE TITLE
No devices can be associated to Provisioning Profiles for the App Store

### ISSUE THREAD

**Issue by lyptt** [fastlane/fastlane#18487]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When attempting to run `fastlane match adhoc` for a macOS app, fastlane crashes.

##### Command executed
fastlane match adhoc

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀 
[00:26:21]: fastlane detected a Gemfile in the current directory
[00:26:21]: However, it seems like you didn't use `bundle exec`
[00:26:21]: To launch fastlane faster, please use
[00:26:21]: 
[00:26:21]: $ bundle exec fastlane match adhoc
[00:26:21]: 
[00:26:21]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[00:26:22]: Successfully loaded '/Users/{snip}/Documents/Projects/{snip}/app/fastlane/Matchfile' 📄

+----------------+--------------------------------------------+
|         Detected Values from './fastlane/Matchfile'         |
+----------------+--------------------------------------------+
| git_url        | git@{snip}:{snip}/{snip}-signing.git       |
| platform       | macos                                      |
| storage_mode   | git                                        |
| type           | development                                |
| app_identifier | com.{snip}.{snip}                          |
| username       | admin@{snip}.com                           |
+----------------+--------------------------------------------+

+--------------------------------+--------------------------------------------+
|                          Summary for match 2.179.0                          |
+--------------------------------+--------------------------------------------+
| type                           | adhoc                                      |
| readonly                       | false                                      |
| generate_apple_certs           | true                                       |
| skip_provisioning_profiles     | false                                      |
| app_identifier                 | ["com.{snip}.{snip}"]                      |
| username                       | admin@{snip}.com                           |
| storage_mode                   | git                                        |
| git_url                        | git@{snip}:{snip}/{snip}-signing.git       |
| git_branch                     | master                                     |
| shallow_clone                  | false                                      |
| clone_branch_directly          | false                                      |
| keychain_name                  | login.keychain                             |
| force                          | false                                      |
| force_for_new_devices          | false                                      |
| skip_confirmation              | false                                      |
| skip_docs                      | false                                      |
| platform                       | macos                                      |
| derive_catalyst_app_identifier | false                                      |
| fail_on_name_taken             | false                                      |
| skip_certificate_matching      | false                                      |
| skip_set_partition_list        | false                                      |
| verbose                        | false                                      |
+--------------------------------+--------------------------------------------+

[00:26:22]: Cloning remote git repo...
[00:26:22]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[00:26:22]: Checking out branch master...
[00:26:22]: 🔓  Successfully decrypted certificates repo
[00:26:22]: Verifying that the certificate and profile are still valid on the Dev Portal...
[00:26:24]: Installing certificate...

+-------------------+-----------------------------------------------+
|                       Installed Certificate                       |
+-------------------+-----------------------------------------------+
| User ID           | {snip}                                        |
| Common Name       | Apple Distribution: {snip} Ltd ({snip})       |
| Organisation Unit | {snip}                                        |
| Organisation      | {snip} Ltd                                    |
| Country           | GB                                            |
| Start Datetime    | 2021-03-30 23:13:35 UTC                       |
| End Datetime      | 2022-03-30 23:13:34 UTC                       |
+-------------------+-----------------------------------------------+

+-------------------------------------+-------------------------------------+
|                         Summary for sigh 2.179.0                          |
+-------------------------------------+-------------------------------------+
| app_identifier                      | com.{snip}.{snip}                   |
| username                            | admin@{snip}.com                    |
| force                               | false                               |
| cert_id                             | {snip}                              |
| provisioning_name                   | match AdHoc com.{snip}.{snip} macos |
| ignore_profiles_with_different_name | true                                |
| fail_on_name_taken                  | false                               |
| platform                            | macos                               |
| adhoc                               | true                                |
| developer_id                        | false                               |
| development                         | false                               |
| skip_install                        | false                               |
| skip_fetch_profiles                 | false                               |
| skip_certificate_verification       | false                               |
| readonly                            | false                               |
+-------------------------------------+-------------------------------------+

[00:26:25]: Starting login with user 'admin@{snip}.com'
[00:26:26]: Successfully logged in
[00:26:26]: Fetching profiles...
[00:26:27]: Verifying certificates...
[00:26:27]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[00:26:28]: Creating new provisioning profile for 'com.{snip}.{snip}' with name 'match AdHoc com.{snip}.{snip} macos' for 'macos' platform
[00:26:30]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
[00:26:30]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
[00:26:30]: to just install the certificates and profiles without accessing the Dev Portal.
[00:26:30]: To do so, just pass `readonly: true` to your match call.

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	27: from /Users/{snip}/.gem/ruby/2.6.0/bin/fastlane:23:in `<main>'
	26: from /Users/{snip}/.gem/ruby/2.6.0/bin/fastlane:23:in `load'
	25: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
	24: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	23: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/commands_generator.rb:25:in `start'
	22: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/commands_generator.rb:187:in `run'
	21: from /Users/{snip}/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	20: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	19: from /Users/{snip}/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	18: from /Users/{snip}/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	17: from /Users/{snip}/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	16: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/commands_generator.rb:68:in `block (3 levels) in run'
	15: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/runner.rb:109:in `run'
	14: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/runner.rb:109:in `each'
	13: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/runner.rb:110:in `block in run'
	12: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/runner.rb:110:in `loop'
	11: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/runner.rb:111:in `block (2 levels) in run'
	10: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/runner.rb:270:in `fetch_provisioning_profile'
	 9: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/match/lib/match/generator.rb:108:in `generate_provisioning_profile'
	 8: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/sigh/lib/sigh/manager.rb:8:in `start'
	 7: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/sigh/lib/sigh/runner.rb:52:in `run'
	 6: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	 5: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/models/profile.rb:76:in `create'
	 4: from /opt/local/lib/ruby2.6/2.6.0/forwardable.rb:230:in `post_profiles'
	 3: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:185:in `post_profiles'
	 2: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
	 1: from /Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:73:in `proxy_post'
/Users/{snip}/.gem/ruby/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/api_client.rb:194:in `handle_response': [!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "000a6736-1533-4eb4-92af-728034ce0d35",
    "status" : "409",
    "code" : "ENTITY_ERROR.RELATIONSHIP.NOT_ALLOWED",
    "title" : "A relationship in the provided entity is not allowed for this request",
    "detail" : "No devices can be associated to Provisioning Profiles for the App Store."
  } ]
}
  </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2.1                                      |
| Ruby                        | 2.6.6                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.2                          |
| Installation Source         | ~/.gem/ruby/2.6.0/bin/fastlane              |
| Host                        | macOS 11.2.1 (20D74)                        |
| Ruby Lib Dir                | /opt/local/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:mac)

platform :mac do
  lane :ci do
    build_mac_app(
      project: "{snip}.xcodeproj",
      configuration: "Debug",
      scheme: "{snip}",
      silent: true,
      clean: true,
      skip_archive: true,
      skip_codesigning: true
    )
  end

  lane :release do
    match(
      type: "adhoc",
      readonly: true
    )
    gym(
      project: "{snip}.xcodeproj",
      configuration: "Release",
      scheme: "{snip}",
      silent: true,
      clean: true
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.{snip}.{snip}")
apple_id("admin@{snip}.com")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.179.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.1.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 1.17.2       |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.3        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.1.9        |
| webrick                       | 1.4.2        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 12.3.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.437.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.113.1      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| forwardable                   | 1.2.0        |
| logger                        | 1.3.0        |
| date                          | 2.0.0        |
| stringio                      | 0.0.2        |
| zlib                          | 1.0.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.1.0        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.1.0        |
| etc                           | 1.0.1        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-03-31**
</details>

**Comment by lyptt** [comment]
FWIW I'm pretty sure Ad Hoc isn't a thing for Mac apps, so this could potentially just need a validation error raised rather than falling back to an error log.
