### ISSUE TITLE
AppStoreConnect api rate limit: Uploading screenshots - Waiting for all the screenshots processed

### ISSUE THREAD

**Issue by cltnschlosser** [fastlane/fastlane#18540]
### New Issue Checklist

- [2.178.0 currently, but not seeing any changes to screenshot upload] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hitting rate limit when uploading screenshots

##### Command executed
```
bundle exec fastlane deliver run --api_key_path <redacted> --app_identifier <redacted> --overwrite_screenshots true --run_precheck_before_submit false --skip_binary_upload true --app_version <redacted> --phased_release true --force true --submission_information <redacted>
```

##### Complete output when running fastlane, including the stack trace and command used
```
[13:54:30]: Waiting for all the screenshots processed...
#<Thread:0x00007f8c33955800 /<home_path>/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/deliver/lib/deliver/app_screenshot_iterator.rb:24 run> terminated with exception (report_on_exception is true):
/<home_path>/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': The request rate limit has been reached. - We’ve received too many API requests for this API key in the past 60 seconds. Please wait and try again. (Spaceship::UnexpectedResponse)
	from /<home_path>/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
	from /<home_path>/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:481:in `get_app_screenshot_sets'
	from /<home_path>/.rbenv/versions/2.7.1/lib/ruby/2.7.0/forwardable.rb:235:in `get_app_screenshot_sets'
	from /<home_path>/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/spaceship/lib/spaceship/connect_api/models/app_screenshot_set.rb:117:in `all'
	from /<home_path>/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:88:in `get_app_screenshot_sets'
	from /<home_path>/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/deliver/lib/deliver/app_screenshot_iterator.rb:25:in `block (3 levels) in each_app_screenshot_set'
```

I haven't dug into this yet, it looks like fastlane is making a call in a loop, maybe that can be batched. Also maybe it's hitting the api too often while waiting for the screenshots to be processed.

**Comment by cltnschlosser** [comment]
Looks like `wait_for_complete` is doing 1 request per locale every 5 seconds.

**Comment by cltnschlosser** [comment]
Well I'm not seeing a batch endpoint, but that delay could be longer than 5 seconds

**Comment by cltnschlosser** [comment]
Turns out I had a few screenshots that were bugged and stuck in a processing state. I had to manually delete them. This likely made it worse because it was indefinitely waiting.
