### ISSUE TITLE
screengrab: java.lang.NoSuchMethodException: getConfiguration []

### ISSUE THREAD

**Issue by benomatis** [fastlane/fastlane#18597]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Getting error `java.lang.NoSuchMethodException: getConfiguration []` when running screengrab

My test starts like...
```java
@LargeTest
@RunWith(JUnit4.class)
public class ScreenGrabInstrumentedTest {
    @ClassRule
    public static final LocaleTestRule localeTestRule = new LocaleTestRule();

    // My IDE gives a deprecated warning for ActivityTestRule!
    @Rule
    public ActivityTestRule<MainActivity> activityRule = new ActivityTestRule<>(MainActivity.class);
    // ...
}
```

##### Command executed
`bundle exec fastlane android grab`

Expanding the lane (plus adding the options from `Screengrabfile`:
```ruby
screengrab(
  locales: ["en-CA"],
  clear_previous_screenshots: true,
  app_apk_path: "android/app/build/outputs/apk/debug/app-debug.apk",
  tests_apk_path: "android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk",
  app_package_name: "com.xxxxxxxxxxxx",
  ending_locale: "en-CA"
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details><summary>Error log</summary>

```
% bundle exec fastlane android grab
[✔] 🚀 
+------------------------------------+---------+--------------------------------------------------------------------+
|                                                   Used plugins                                                    |
+------------------------------------+---------+--------------------------------------------------------------------+
| Plugin                             | Version | Action                                                             |
+------------------------------------+---------+--------------------------------------------------------------------+
| fastlane-plugin-versioning_android | 0.1.0   | android_get_version_name android_set_version_code                  |
|                                    |         | android_set_version_name android_get_version_code                  |
| fastlane-plugin-load_json          | 0.0.1   | load_json                                                          |
| fastlane-plugin-versioning         | 0.4.4   | get_version_number_from_git_branch                                 |
|                                    |         | increment_build_number_in_xcodeproj get_version_number_from_plist  |
|                                    |         | get_build_number_from_plist ci_build_number                        |
|                                    |         | get_version_number_from_xcodeproj                                  |
|                                    |         | increment_version_number_in_xcodeproj                              |
|                                    |         | increment_version_number_in_plist get_app_store_version_number     |
|                                    |         | get_info_plist_path get_build_number_from_xcodeproj                |
|                                    |         | increment_build_number_in_plist                                    |
+------------------------------------+---------+--------------------------------------------------------------------+

[22:39:48]: ------------------------------
[22:39:48]: --- Step: default_platform ---
[22:39:48]: ------------------------------
[22:39:48]: Driving the lane 'android grab' 🚀
[22:39:48]: ------------------------
[22:39:48]: --- Step: screengrab ---
[22:39:48]: ------------------------
[22:39:48]: Successfully loaded 'XXXXX/fastlane/Screengrabfile' 📄

+----------------------------+---------------------------------------------------------------------------+
|                            Detected Values from './fastlane/Screengrabfile'                            |
+----------------------------+---------------------------------------------------------------------------+
| locales                    | ["en-CA"]                                                                 |
| clear_previous_screenshots | true                                                                      |
| app_apk_path               | android/app/build/outputs/apk/debug/app-debug.apk                         |
| tests_apk_path             | android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk |
| app_package_name           | com.xxxxxxxxxxxxxxxxxxx                                                   |
| ending_locale              | en-CA                                                                     |
+----------------------------+---------------------------------------------------------------------------+

[22:39:48]: The `aapt` command could not be found relative to your provided ANDROID_HOME at XXXXX/Library/Android/sdk
[22:39:48]: Please ensure that the Android SDK is installed and you have the build tools downloaded

+-----------------------------+---------------------------------------------------------------------------+
|                                     Summary for screengrab 2.181.0                                      |
+-----------------------------+---------------------------------------------------------------------------+
| tests_package_name          | com.xxxxxxxxxxxxxxxxxxx.test                                              |
| android_home                | XXXXX/Library/Android/sdk                                                 |
| locales                     | ["en-CA"]                                                                 |
| clear_previous_screenshots  | true                                                                      |
| output_directory            | fastlane/metadata/android                                                 |
| skip_open_summary           | false                                                                     |
| app_package_name            | com.xxxxxxxxxxxxxxxxxxx                                                   |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner                                   |
| ending_locale               | en-CA                                                                     |
| use_adb_root                | false                                                                     |
| app_apk_path                | android/app/build/outputs/apk/debug/app-debug.apk                         |
| tests_apk_path              | android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk |
| device_type                 | phone                                                                     |
| exit_on_test_failure        | true                                                                      |
| reinstall_app               | false                                                                     |
| use_timestamp_suffix        | true                                                                      |
+-----------------------------+---------------------------------------------------------------------------+

[22:39:48]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[22:39:48]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[22:39:48]: Clearing phoneScreenshots within fastlane/metadata/android
[22:39:48]: $ XXXXX/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[22:39:48]: ▸ /sdcard
[22:39:48]: Cleaning screenshots on device
ls: /sdcard/com.xxxxxxxxxxxxxxxxxxx/screengrab/en-CA/images/screenshots: No such file or directory
[22:39:48]: Exit status: 1
ls: /data/user/0/com.xxxxxxxxxxxxxxxxxxx/files/com.xxxxxxxxxxxxxxxxxxx/screengrab/en-CA/images/screenshots: No such file or directory
[22:39:48]: Exit status: 1
ls: /data/data/com.xxxxxxxxxxxxxxxxxxx/files/com.xxxxxxxxxxxxxxxxxxx/screengrab/en-CA/images/screenshots: No such file or directory
[22:39:48]: Exit status: 1
ls: /data/data/com.xxxxxxxxxxxxxxxxxxx/app_screengrab/en-CA/images/screenshots: No such file or directory
[22:39:48]: Exit status: 1
ls: /data/data/com.xxxxxxxxxxxxxxxxxxx/screengrab/en-CA/images/screenshots: No such file or directory
[22:39:48]: Exit status: 1
[22:39:48]: The `aapt` command could not be found on your system, so your app APK could not be validated
[22:39:48]: Installing app APK
[22:39:48]: $ XXXXX/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r android/app/build/outputs/apk/debug/app-debug.apk
[22:39:48]: ▸ Performing Streamed Install
[22:39:49]: ▸ Success
[22:39:49]: Installing tests APK
[22:39:49]: $ XXXXX/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
[22:39:49]: ▸ Performing Streamed Install
[22:39:50]: ▸ Success
[22:39:50]: Granting the permission necessary to change locales on the device
[22:39:50]: $ XXXXX/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.xxxxxxxxxxxxxxxxxxx android.permission.CHANGE_CONFIGURATION
[22:39:50]: $ XXXXX/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[22:39:50]: ▸ 28
[22:39:50]: Granting the permissions necessary to access device external storage
[22:39:50]: $ XXXXX/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.xxxxxxxxxxxxxxxxxxx android.permission.WRITE_EXTERNAL_STORAGE
[22:39:51]: $ XXXXX/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.xxxxxxxxxxxxxxxxxxx android.permission.READ_EXTERNAL_STORAGE
[22:39:51]: $ XXXXX/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[22:39:51]: ▸ 28
[22:39:51]: The `aapt` command could not be found, so status bar could not be cleaned. Make sure android_home is configured for screengrab or ANDROID_HOME is set in the environment
[22:39:51]: Running tests for locale: en-CA
[22:39:51]: $ XXXXXLibrary/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en_CA \
-e endingLocale en_CA \
-e appendTimestamp true \
com.xxxxxxxxxxxxxxxxxxx.test/androidx.test.runner.AndroidJUnitRunner
[22:39:53]: ▸ com.xxxxxxxxxxxxxxxxxxx.ScreenGrabInstrumentedTest:
[22:39:53]: ▸ Error in com.xxxxxxxxxxxxxxxxxxx.ScreenGrabInstrumentedTest:
[22:39:53]: ▸ java.lang.RuntimeException: java.lang.NoSuchMethodException: getConfiguration []
[22:39:53]: ▸   at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:46)
[22:39:53]: ▸   at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:35)
[22:39:53]: ▸   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[22:39:53]: ▸   at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[22:39:53]: ▸   at org.junit.runners.Suite.runChild(Suite.java:128)
[22:39:53]: ▸   at org.junit.runners.Suite.runChild(Suite.java:27)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[22:39:53]: ▸   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[22:39:53]: ▸   at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[22:39:53]: ▸   at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[22:39:53]: ▸   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[22:39:53]: ▸   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[22:39:53]: ▸   at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[22:39:53]: ▸   at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
[22:39:53]: ▸   at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
[22:39:53]: ▸ Caused by: java.lang.NoSuchMethodException: getConfiguration []
[22:39:53]: ▸   at java.lang.Class.getMethod(Class.java:2068)
[22:39:53]: ▸   at java.lang.Class.getMethod(Class.java:1690)
[22:39:53]: ▸   at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:28)
[22:39:53]: ▸   ... 18 more
[22:39:53]: ▸ Time: 0.013
[22:39:53]: ▸ There was 1 failure:
[22:39:53]: ▸ 1) com.xxxxxxxxxxxxxxxxxxx.ScreenGrabInstrumentedTest
[22:39:53]: ▸ java.lang.RuntimeException: java.lang.NoSuchMethodException: getConfiguration []
[22:39:53]: ▸   at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:46)
[22:39:53]: ▸   at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:35)
[22:39:53]: ▸   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[22:39:53]: ▸   at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[22:39:53]: ▸   at org.junit.runners.Suite.runChild(Suite.java:128)
[22:39:53]: ▸   at org.junit.runners.Suite.runChild(Suite.java:27)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[22:39:53]: ▸   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[22:39:53]: ▸   at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[22:39:53]: ▸   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[22:39:53]: ▸   at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[22:39:53]: ▸   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[22:39:53]: ▸   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[22:39:53]: ▸   at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[22:39:53]: ▸   at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
[22:39:53]: ▸   at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
[22:39:53]: ▸ Caused by: java.lang.NoSuchMethodException: getConfiguration []
[22:39:53]: ▸   at java.lang.Class.getMethod(Class.java:2068)
[22:39:53]: ▸   at java.lang.Class.getMethod(Class.java:1690)
[22:39:53]: ▸   at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:28)
[22:39:53]: ▸   ... 18 more
[22:39:53]: ▸ FAILURES!!!
[22:39:53]: ▸ Tests run: 0,  Failures: 1
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | ios          |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android grab |
+------------------+--------------+
[22:39:53]: Tests failed for locale en-CA on device emulator-5554

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | screengrab       | 5           |
+------+------------------+-------------+

[22:39:53]: fastlane finished with errors

[!] Tests failed for locale en-CA on device emulator-5554
```
</details>

### Captured Output

Command Used: `android grab --capture_output`
<details><summary>Output/Log</summary>

```

DEBUG [2021-04-23 22:48:13.41]: Checking if there are any plugins that should be loaded...
DEBUG [2021-04-23 22:48:13.41]: Loading 'fastlane-plugin-versioning_android' plugin
INFO [2021-04-23 22:48:13.41]: gem 'fastlane-plugin-versioning_android' is already installed
DEBUG [2021-04-23 22:48:13.41]: Loading 'fastlane-plugin-load_json' plugin
INFO [2021-04-23 22:48:13.41]: gem 'fastlane-plugin-load_json' is already installed
DEBUG [2021-04-23 22:48:13.42]: Loading 'fastlane-plugin-versioning' plugin
INFO [2021-04-23 22:48:13.42]: gem 'fastlane-plugin-versioning' is already installed


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2.3                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.23.0                                             |
| Installation Source         | ~/.gems/bin/fastlane                                           |
| Host                        | macOS 11.2.3 (20D91)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   | en_GB.UTF-8 | ✅ |
| LANGUAGE | en_GB.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Heavily redacted!!!
default_platform(:ios)

platform :ios do
  desc "Push a new internal testing build to TestFlight"
  lane :internal do
    # ...
  end
end

platform :android do
  desc "Push a new internal testing build to PlayStore"
  lane :internal do
    # ...
  end

  desc "Create screenshots"
  lane :grab do
    screengrab
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.xxxxxxxxxx") # The bundle identifier of your app
apple_id("email@address.com") # Your Apple email address

itc_team_id("1234567890") # App Store Connect Team ID
team_id("XXXXXXXXX") # Developer Portal Team ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-versioning_android | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-load_json          | 0.0.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning         | 0.4.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.3.0        |
| bundler                            | 2.2.11       |
| rake                               | 13.0.3       |
| CFPropertyList                     | 3.0.3        |
| public_suffix                      | 4.0.6        |
| addressable                        | 2.7.0        |
| artifactory                        | 3.0.15       |
| atomos                             | 0.1.3        |
| aws-eventstream                    | 1.1.1        |
| aws-partitions                     | 1.446.0      |
| aws-sigv4                          | 1.2.3        |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.114.0      |
| aws-sdk-kms                        | 1.43.0       |
| aws-sdk-s3                         | 1.93.1       |
| babosa                             | 1.0.4        |
| claide                             | 1.0.3        |
| colored                            | 1.2          |
| colored2                           | 3.1.2        |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| declarative                        | 0.0.20       |
| digest-crc                         | 0.6.3        |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| dotenv                             | 2.7.6        |
| emoji_regex                        | 3.2.2        |
| excon                              | 0.80.1       |
| faraday-excon                      | 1.1.0        |
| faraday-net_http                   | 1.0.1        |
| faraday-net_http_persistent        | 1.1.0        |
| multipart-post                     | 2.0.0        |
| ruby2_keywords                     | 0.0.4        |
| faraday                            | 1.4.1        |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.7        |
| faraday_middleware                 | 1.0.0        |
| fastimage                          | 2.2.3        |
| gh_inspector                       | 1.1.3        |
| jwt                                | 2.2.3        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.15.0       |
| os                                 | 1.1.1        |
| signet                             | 0.15.0       |
| googleauth                         | 0.16.1       |
| httpclient                         | 2.8.3        |
| mini_mime                          | 1.1.0        |
| trailblazer-option                 | 0.1.1        |
| uber                               | 0.1.0        |
| representable                      | 3.1.1        |
| retriable                          | 3.1.2        |
| google-api-client                  | 0.38.0       |
| rexml                              | 3.2.5        |
| webrick                            | 1.7.0        |
| google-apis-core                   | 0.3.0        |
| google-apis-iamcredentials_v1      | 0.3.0        |
| google-apis-storage_v1             | 0.3.0        |
| google-cloud-env                   | 1.5.0        |
| google-cloud-errors                | 1.1.0        |
| google-cloud-core                  | 1.6.0        |
| google-cloud-storage               | 1.31.0       |
| json                               | 2.5.1        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| plist                              | 3.6.0        |
| rubyzip                            | 2.3.0        |
| security                           | 0.1.3        |
| simctl                             | 1.6.8        |
| slack-notifier                     | 2.3.2        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| word_wrap                          | 1.0.0        |
| nanaimo                            | 0.3.0        |
| xcodeproj                          | 1.19.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| xcpretty-travis-formatter          | 1.0.1        |
| fastlane-plugin-load_json          | 0.0.1        |
| fastlane-plugin-versioning         | 0.4.4        |
| fastlane-plugin-versioning_android | 0.1.0        |
</details>

*generated on:* **2021-04-23**
</details>

**Comment by benomatis** [comment]
Sorry I didn't follow up on this earlier, but I did get to fix the issue but I unfortunately don't remember what I did exactly to fix it.
