### ISSUE TITLE
Fastlane Pilot "Missing password for user" but still succeed

### ISSUE THREAD

**Issue by louis030195** [fastlane/fastlane#18610]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running <https://github.com/maierj/fastlane-action> and [Fastlane Pilot](https://docs.fastlane.tools/actions/pilot/) succeed and still displays a failure error.

##### Command executed

```yaml
deploy_ios:
    name: Deploy beta build to TestFlight
    runs-on: macos-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
      - name: Decrypt iOS keys
        run: sh ./ios/decrypt.sh
        env:
          RELEASE_SECRET_PASSPHRASE: ${{ secrets.RELEASE_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.0.4
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign --flavor prod
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: closed_beta
          subdirectory: ios
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'

```
Fastfile
```rb
default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: false
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :closed_beta do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    match(
      type: 'appstore',
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password 
    )

    gym(
      configuration: "Release-prod",
      workspace: "Runner.xcworkspace",
      scheme: "prod",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      }
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./Runner.ipa",
      changelog: "Fixed notifications and improved UX a bit"
    )

    delete_temp_keychain(keychain_name)
  end
end

```
Matchfile
```rb
git_url("https://github.com/louis030195/certificates.git")
storage_mode("git")
type("appstore")
```
Appfile
```rb
app_identifier(ENV["DEVELOPER_APP_IDENTIFIER"])
apple_id(ENV["FASTLANE_APPLE_ID"])

itc_team_id(ENV["APP_STORE_CONNECT_TEAM_ID"])
team_id(ENV["DEVELOPER_PORTAL_TEAM_ID"])
```

##### Complete output when running fastlane, including the stack trace and command used

```
[15:30:53]: -------------------
[15:30:53]: --- Step: pilot ---
[15:30:53]: -------------------
[15:30:53]: Ready to upload new build to TestFlight (App: ***)...
[15:30:53]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[15:30:53]: Going to upload updated app to App Store Connect
[15:30:53]: This might take a few minutes. Please don't interrupt the script.
[15:32:50]: iTunes Transporter successfully finished its job
[15:32:50]: --------------------------------------------------------------------
[15:32:50]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
[15:32:50]: --------------------------------------------------------------------
[15:32:50]: Successfully uploaded the new binary to App Store Connect
[15:32:50]: Login to App Store Connect (***)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
+------------------------------------+------------------------------------------------------------------------------------------------+
|                                                            Lane Context                                                             |
+------------------------------------+------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                            |
| PLATFORM_NAME                      | ios                                                                                            |
| LANE_NAME                          | ios closed_beta                                                                                |
| KEYCHAIN_PATH                      | ~/Library/Keychains/***                                                                      |
| SIGH_PROFILE_TYPE                  | app-store                                                                                      |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"***"=>"***"}                                              |
| IPA_OUTPUT_PATH                    | /Users/runner/work/langame-app/langame-app/ios/Runner.ipa                                      |
| XCODEBUILD_ARCHIVE                 | /Users/runner/Library/Developer/Xcode/Archives/2021-04-27/Runner 2021-04-27 15.14.21.xcarchive |
| DSYM_OUTPUT_PATH                   | /Users/runner/work/langame-app/langame-app/ios/Runner.app.dSYM.zip                             |
+------------------------------------+------------------------------------------------------------------------------------------------+
[15:32:50]: Missing password for user ***, and running in non-interactive shell

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | create_keychain  | 0           |
| 3    | match            | 1           |
| 4    | gym              | 1002        |
| 💥   | pilot            | 117         |
+------+------------------+-------------+

[15:32:50]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane)
Found no similar issues. To create a new issue, please visit:
/Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': \e[31m[!] Missing password for user ***, and running in non-interactive shell\e[0m (RuntimeError)
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/client.rb:383:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/client.rb:355:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/pilot/lib/pilot/manager.rb:31:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/pilot/lib/pilot/build_manager.rb:56:in `upload'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:31:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:56:in `block (2 levels) in parsing_binding'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/bin/fastlane:23:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane:23:in `load'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane:23:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `load'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `<main>'
/Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': Missing password for user ***, and running in non-interactive shell (RuntimeError)
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/client.rb:383:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/client.rb:355:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/pilot/lib/pilot/manager.rb:31:in `login'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/pilot/lib/pilot/build_manager.rb:56:in `upload'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:31:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:56:in `block (2 levels) in parsing_binding'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.181.0/bin/fastlane:23:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane:23:in `load'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane:23:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `load'
	from /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `<main>'
```

![Screenshot 2021-04-27 at 18 06 39](https://user-images.githubusercontent.com/25003283/116274856-5398a880-a783-11eb-81fd-a5ec104b1650.png)

This is not blocking but can be unnecessarily worrisome.

Thank you for your help, I hope no mistake on my part?🤔

**Comment by crazymanish** [comment]
Hi @louis030195 

One small suggestion, (Unrelated to this issue)
You don't need to use `maierj/fastlane-action` to run Fastlane, and `maierj/fastlane-action` action is even tracking you with extra API call....which we can avoid
https://github.com/maierj/fastlane-action/blob/1c48e141e0c0f87112c5cf9ca6604d8decde1ad1/main.js#L17


```ruby
# NOW

- name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v2.0.1     # Running using 3rd party, making extra API call for the tracking details
        with:
          lane: closed_beta
          subdirectory: ios
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          ...
          ...    
```     


```ruby
# Proposal

- name: Deploy iOS Beta to TestFlight via Fastlane
        run: bundle exec fastlane ios closed_beta        # Running Fastlane directly
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          ...
          ...    
```

**Comment by louis030195** [comment]
@crazymanish thank you for the tips!

Somehow the error stopped occurring
