### ISSUE TITLE
Fastlane installation is broken due to rdoc 6.3.1 version

### ISSUE THREAD

**Issue by LeonidLapshin** [fastlane/fastlane#18642]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane installation is broken since Sunday on Ubuntu 20. 
Rdoc 6.3.1 breaks fastlane installation, manual installation 6.3.0 rdoc version before fastlane installation works well and fastlane installation succeeds.

##### Command executed

gem install fastlane

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
  
```
2021-05-04T14:10:25.0152970Z ==> azure-arm: Exception `LoadError' at /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92 - cannot load such file -- rdoc/markup/table
2021-05-04T14:10:25.0157794Z ==> azure-arm: Exception `LoadError' at /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:170 - cannot load such file -- rdoc/markup/table
2021-05-04T14:10:25.0167876Z ==> azure-arm: /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rdoc/markup/table (LoadError)
2021-05-04T14:10:25.0172506Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
2021-05-04T14:10:25.0175651Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:15955:in `_Table'
2021-05-04T14:10:25.0181483Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:481:in `apply'
2021-05-04T14:10:25.0186611Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:926:in `_Block'
2021-05-04T14:10:25.0202454Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:481:in `apply'
2021-05-04T14:10:25.0210951Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:877:in `_Doc'
2021-05-04T14:10:25.0215831Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:481:in `apply'
2021-05-04T14:10:25.0219289Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:855:in `_root'
2021-05-04T14:10:25.0223023Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:481:in `apply'
2021-05-04T14:10:25.0233812Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:385:in `parse'
2021-05-04T14:10:25.0235530Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:790:in `parse'
2021-05-04T14:10:25.0245034Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/markdown.rb:621:in `parse'
2021-05-04T14:10:25.0253706Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/text.rb:139:in `parse'
2021-05-04T14:10:25.0256887Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/comment.rb:203:in `parse'
2021-05-04T14:10:25.0308359Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/text.rb:133:in `parse'
2021-05-04T14:10:25.0310216Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/top_level.rb:203:in `marshal_dump'
2021-05-04T14:10:25.0356319Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/store.rb:916:in `dump'
2021-05-04T14:10:25.0358317Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/store.rb:916:in `block in save_page'
2021-05-04T14:10:25.0364611Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/store.rb:915:in `open'
2021-05-04T14:10:25.0368961Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/store.rb:915:in `save_page'
2021-05-04T14:10:25.0377306Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/store.rb:770:in `block in save'
2021-05-04T14:10:25.0379188Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/store.rb:769:in `each'
2021-05-04T14:10:25.0384136Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/store.rb:769:in `save'
2021-05-04T14:10:25.0387802Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/generator/ri.rb:27:in `generate'
2021-05-04T14:10:25.0392532Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/rubygems_hook.rb:137:in `block in document'
2021-05-04T14:10:25.0398664Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/rubygems_hook.rb:134:in `chdir'
2021-05-04T14:10:25.0404664Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/rubygems_hook.rb:134:in `document'
2021-05-04T14:10:25.0407119Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/rubygems_hook.rb:193:in `generate'
2021-05-04T14:10:25.0417488Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
2021-05-04T14:10:25.0422844Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/rubygems_hook.rb:55:in `each'
2021-05-04T14:10:25.0425301Z ==> azure-arm: 	from /var/lib/gems/2.7.0/gems/rdoc-6.3.1/lib/rdoc/rubygems_hook.rb:55:in `generation_hook'
2021-05-04T14:10:25.0434506Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/request_set.rb:323:in `block in install_hooks'
2021-05-04T14:10:25.0439251Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/request_set.rb:322:in `each'
2021-05-04T14:10:25.0443288Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/request_set.rb:322:in `install_hooks'
2021-05-04T14:10:25.0448036Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/request_set.rb:221:in `install'
2021-05-04T14:10:25.0452471Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:208:in `install_gem'
2021-05-04T14:10:25.0460047Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:224:in `block in install_gems'
2021-05-04T14:10:25.0466995Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:217:in `each'
2021-05-04T14:10:25.0477588Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:217:in `install_gems'
2021-05-04T14:10:25.0488129Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:165:in `execute'
2021-05-04T14:10:25.0491749Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/command.rb:325:in `invoke_with_build_args'
2021-05-04T14:10:25.0497190Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/command_manager.rb:178:in `process_args'
2021-05-04T14:10:25.0503010Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/command_manager.rb:148:in `run'
2021-05-04T14:10:25.0512718Z ==> azure-arm: 	from /usr/lib/ruby/2.7.0/rubygems/gem_runner.rb:59:in `run'
2021-05-04T14:10:25.0521156Z ==> azure-arm: 	from /usr/bin/gem:21:in `<main>'
```

</pre>
</details>

**Comment by ainame** [comment]
I can't find the tag for 6.3.1 on https://github.com/ruby/rdoc but this seems to be the diff between the two versions https://my.diffend.io/gems/rdoc/6.3.0/6.3.1

**Comment by ainame** [comment]
Reported the issue here
https://github.com/ruby/rdoc/issues/808

**Comment by ainame** [comment]
rdoc seemed to be fixed. I hope we'll see a new release within a couple of days🤞

**Comment by igoriuz** [comment]
New rdoc version is finally released and therefore this issue can be closed. Maybe @LeonidLapshin can confirm it too?

**Comment by cynicer** [comment]
rdoc 6.3.2 works for me
