### ISSUE TITLE
warning: already initialized constant Bundler::FileUtils::VERSION

### ISSUE THREAD

**Issue by richardtop** [fastlane/fastlane#18679]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Getting this error when trying to run Fastlane (see output)

##### Command executed
`fastlane`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> richard@Richards-MacBook-Pro infrakit-field-app-ios % fastlane  
[⠴] 🚀 /Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
Traceback (most recent call last):
	24: from /Users/richard/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	23: from /Users/richard/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	22: from /Users/richard/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `<main>'
	21: from /Users/richard/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `load'
	20: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/fastlane-2.182.0/bin/fastlane:23:in `<top (required)>'
	19: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/fastlane-2.182.0/fastlane/lib/fastlane/cli_tools_distributor.rb:41:in `take_off'
	18: from /Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	17: from /Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	16: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/fastlane-2.182.0/fastlane/lib/fastlane.rb:27:in `<top (required)>'
	15: from /Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	14: from /Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	13: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/fastlane-2.182.0/fastlane/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
	12: from /Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	11: from /Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	10: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/fastlane-2.182.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:3:in `<top (required)>'
	 9: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/fastlane-2.182.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:4:in `<module:Fastlane>'
	 8: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/fastlane-2.182.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:5:in `<class:PluginManager>'
	 7: from /Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /Users/richard/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 5: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler.rb:7:in `<top (required)>'
	 4: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler.rb:7:in `require_relative'
	 3: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/errors.rb:3:in `<top (required)>'
	 2: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/errors.rb:20:in `<module:Bundler>'
	 1: from /Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/Users/richard/.rvm/gems/ruby-2.7.0/gems/bundler-2.2.17/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)
</pre>
</details>

### Environment

<details>
Same error
</details>

**Comment by richardtop** [comment]
@fastlane-bot read again
