### ISSUE TITLE
Unexpected token JSON error when notarizing MacOS app

### ISSUE THREAD

**Issue by thecoolwinter** [fastlane/fastlane#18685]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to use the `notarize` action and it's failing with the error:
```bash
Search query: 809: unexpected token at '{
  "key_id": "XXXXXXXX",
  "issuer_id": "XXX",
  "key": "KEY HERE ON ONE LINE",
  "duration": 1200, 
  "in_house": false,
}'
```

my `api_key_path` goes to a JSON file with the exact contents:
```json
{
  "key_id": "XXX",
  "issuer_id": "XXX",
  "key": "XXX",
  "duration": 1200, 
  "in_house": false,
}

```

##### Command executed
```ruby
notarize(
		verbose: true,
		package: "XXX.app",
		bundle_id: "XXX",
		print_log: true,
		api_key_path: "PATH/TO/AuthKey_XXXXXXXXjson"
)
```

##### Complete output when running fastlane, including the stack trace and command used
Command: `bundle exec fastlane notarize_and_upload --capture_output

<details>
  Nothing happened when using the --capture_output command. But here's the stack trace and everything:

```
Successfully loaded Appfile at path 'PATH/TO/fastlane/Appfile'
- app_identifier: 'XXX'
- apple_id: 'XXX'
- team_id: 'XXX'
-------
INFO [2021-05-12 16:30:55.93]: Driving the lane 'notarize_and_upload' 🚀
INFO [2021-05-12 16:30:55.93]: ----------------------
INFO [2021-05-12 16:30:55.93]: --- Step: notarize ---
INFO [2021-05-12 16:30:55.93]: ----------------------
INFO [2021-05-12 16:30:55.93]: $ ditto -c -k --rsrc --keepParent "PATH/TO/archive.xcarchive/Products/Applications/APP.app" "PATH TO/APP.app.zip"
INFO [2021-05-12 16:30:57.97]: Uploading package to notarization service, might take a while
WARN [2021-05-12 16:30:57.98]: Lane Context:
INFO [2021-05-12 16:30:57.98]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"notarize_and_upload"}
ERROR [2021-05-12 16:30:57.98]: 809: unexpected token at '{
  "key_id": "XXX",
  "issuer_id": "XXX",
  "key": "XXX",
  "duration": 1200, 
  "in_house": false,
}'

+------+----------+-------------+
|       fastlane summary        |
+------+----------+-------------+
| Step | Action   | Time (in s) |
+------+----------+-------------+
| 💥   | notarize | 2           |
+------+----------+-------------+

ERROR [2021-05-12 16:30:57.99]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: 809: unexpected token at '{
  "key_id": "XXX",
  "issuer_id": "XXX",
  "key": "XXX",
  "duration": 1200, 
  "in_house": false,
}'

ERROR [2021-05-12 16:30:58.24]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
Traceback (most recent call last):
	30: from /usr/local/Cellar/fastlane/2.182.0/libexec/bin/fastlane:23:in `<main>'
	29: from /usr/local/Cellar/fastlane/2.182.0/libexec/bin/fastlane:23:in `load'
	28: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/bin/fastlane:23:in `<top (required)>'
	27: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	26: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	25: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	24: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	23: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	22: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	21: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	20: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	19: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	18: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	17: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	16: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	15: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	14: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	13: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	12: from Fastfile:28:in `block in parsing_binding'
	11: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	10: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 9: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 8: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 7: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 6: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 5: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 4: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/actions/notarize.rb:38:in `run'
	 3: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/fastlane/lib/fastlane/actions/notarize.rb:137:in `with_notarize_authenticator'
	 2: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/fastlane-2.182.0/spaceship/lib/spaceship/connect_api/token.rb:29:in `from_json_file'
	 1: from /usr/local/Cellar/fastlane/2.182.0/libexec/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
/usr/local/Cellar/fastlane/2.182.0/libexec/gems/json-2.5.1/lib/json/common.rb:216:in `parse': \e[31m[!] 809: unexpected token at '{ (JSON::ParserError)
  "key_id": "XXX",
  "issuer_id": "XXX",
  "key": "XXX",
  "duration": 1200, 
  "in_house": false,
}'\e[0m

```

</details>

### Environment

<details>
  <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.2.1                                                  |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.182.0/libexec/bin/fastlane |
| Host                        | macOS 11.2.1 (20D75)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.3                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
skip_docs

lane :notarize_and_upload do
	notarize(
		verbose: true,
		package: "XXX.app",
		bundle_id: "XXX",
		print_log: true,
		api_key_path: "XXX/AuthKey_XXXXXXXX.json"
	)
end

# Archive the iPad scheme and save it to zip
lane :archive_and_zip do 

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("XXX")
apple_id("XXX")

team_id "XXX"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.182.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 2.0.3        |
| commander                     | 4.6.0        |
| excon                         | 0.81.0       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.15       |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.3        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| trailblazer-option            | 0.1.1        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.2       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.94.1       |
| uri                           | 0.10.0       |
| json                          | 2.5.1        |
| rexml                         | 3.2.5        |
| webrick                       | 1.7.0        |
| aws-partitions                | 1.453.0      |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| io-console                    | 0.5.6        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| singleton                     | 0.1.0        |
| open3                         | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-05-12**
</details>
</details>

**Comment by thecoolwinter** [comment]
Okay I figured out a work-around. I modified the `notarize` command to take two new inputs: `key_id` and `issuer_id` which it passes to the command if `api_key_path` wasn't passed. That tells altool to look in one of these directories for a AuthKey_[KEY_ID].p8 file:

- `./private_keys`
- `~/private_keys`
- `~/.private_keys`
- `~/.appstoreconnect/private_keys`

Then altool generates the required JWT/JWK to upload, and the rest of the notarize script works fine.

I think my original problem is because of some JSON parsing issue. Looking at past problems with a similar error (though none of them had a solution) the problem looked to be the same JSON 'unexpected token at '_''. I don't know what's causing that, but whatever it is this solution works for me for now.
