### ISSUE TITLE
Pilot fails even though it finishes uploading the Build

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1873]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/11356621?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @Ybrin - Imported from <a href='https://github.com/fastlane/pilot/issues/157'>fastlane/pilot#157</a>
        </td>
      </tr>
    </table>

I am currently using pilot together with fastlane in travis-ci and everything works fine, my builds are being uploaded to TestFlight and published to the internal Testers as it should.

But the thing I don't understand is, fastlane finishs with exit code 1 and says "You must provide an answer for this question" without even asking something.

I think this error is pilot related and has nothing to do with fastlane so I am posting this here.

This is the weird output:

```
[12:29:40]: Successfully finished processing the build
[12:29:40]: You can now tweet: 
[12:29:40]: iTunes Connect #iosprocessingtime 15 minutes
[12:29:40]: Distributing new build to testers
[12:29:43]: Variable Dump:
[12:29:43]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta_ci", :SIGH_PROFILE_TYPE=>"app-store", :LATEST_TESTFLIGHT_BUILD_NUMBER=>3, :BUILD_NUMBER=>"4", :IPA_OUTPUT_PATH=>"/Users/travis/build/KWStudios/Walk-iOS/Pods.ipa", :DSYM_OUTPUT_PATH=>"/Users/travis/build/KWStudios/Walk-iOS/Pods.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/travis/Library/Developer/Xcode/Archives/2016-03-01/Pods 2016-03-01 12.06.19.xcarchive"}
[12:29:43]: You must provide an answer for this question.
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 110         |
| 4    | match                               | 27          |
| 5    | match                               | 4           |
| 6    | latest_testflight_build_number      | 8           |
| 7    | increment_build_number              | 2           |
| 8    | gym                                 | 413         |
| 9    | pilot                               | 995         |
+------+-------------------------------------+-------------+
[12:29:43]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] You must provide an answer for this question. (Spaceship::TunesClient::ITunesConnectError)
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:538:in `update_build_trains!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/spaceship-0.21.1/lib/spaceship/tunes/build_train.rb:118:in `update_testing_status!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/pilot-1.4.1/lib/pilot/build_manager.rb:124:in `distribute_build'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/pilot-1.4.1/lib/pilot/build_manager.rb:26:in `upload'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:68:in `block (2 levels) in parsing_binding'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane_core-0.36.9/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/bin/fastlane:162:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/fastlane:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
The command "fastlane beta_ci" exited with 1.
```

I appreciate any help because being notified for each Commit from travis because of a Failed build is really annoying.

**Comment by greenmood** [comment]
Same here. Just after it's finished processing, i receive 'You must provide an answer for this question.' Which looks a bit odd, since no one asked me anything :)

**Comment by timcamber** [comment]
I'm also seeing this issue and not sure why

**Comment by tabuchid** [comment]
Had this start happening to me and was able to fix by adding `<key>ITSAppUsesNonExemptEncryption</key><false/>` to my info.plist.
Use `false` or `true` depending on how you would answer the encryption question Connect asks.

**Comment by timcamber** [comment]
That sounds like a very plausible solution, I'll give it a shot, thanks!

**Comment by mfurtak** [comment]
Would it make sense to detect whether this plist key is present as part of the process, and fail earlier with a better message in that case?

**Comment by timcamber** [comment]
I'm still getting this response after trying @tabuchid's solution. Is there another question iTC asks that needs to be in my `plist`?

**Comment by KrauseFx** [comment]
Closing this issue for now due to inactivity

**Comment by GabLeRoux** [comment]
I had the same problem, thanks for answering here. For reference, Using XCode, it's in Info tab, add key `ITSAppUsesNonExemptEncryption` (and will translate to `App UsesNon-Exempt Encryption`).

More informations can be found here:
http://stackoverflow.com/questions/35739361/itsappusesnonexemptencryption-export-compliance-while-internal-testing

**Comment by TKBurner** [comment]
@GabLeRoux Awesome! Thanks so much for sharing. Hope that you have a great week 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/6766, which will add instructions on how to fix the error right in the build output 👍
