### ISSUE TITLE
Distributing build to testers failed with error: You must provide an answer for this question

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1874]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/232005?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @Pr0Ger - Imported from <a href='https://github.com/fastlane/pilot/issues/156'>fastlane/pilot#156</a>
        </td>
      </tr>
    </table>

When submiting beta build for internal testing I receive following error. When I tried to distribute this build manually iTunes Connect requsted answering to questions about used encryption, so this is probably a reason for this exception.

```
/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] You must provide an answer for this question. (Spaceship::TunesClient::ITunesConnectError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:538:in `update_build_trains!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.21.1/lib/spaceship/tunes/build_train.rb:118:in `update_testing_status!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.4.1/lib/pilot/build_manager.rb:124:in `distribute_build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.4.1/lib/pilot/build_manager.rb:26:in `upload'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/actions/pilot.rb:18:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/actions/testflight.rb:5:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:63:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/bin/fastlane:38:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.36.9/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.63.1/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by Guillaume-Guffroy** [comment]
Thank you @gpbl , it solve my problem
