### ISSUE TITLE
"iTunes Transporter successfully finished its job" but pilot ends with an error

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1886]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/3725610?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @lifeisfoo - Imported from <a href='https://github.com/fastlane/pilot/issues/110'>fastlane/pilot#110</a>
        </td>
      </tr>
    </table>

I've an issue very similar to fastlane/deliver#124 and fastlane/deliver#44 but with pilot 1.2.0.
I'm using it with fastlane, calling it without parameters.
```
  lane :beta do
    gym
    pilot
  end

```

After the ipa file was transferred, an operation called `uploadDoneWithArguments` was executed ending with a timeout, then was executed a second time ending correctly (`Apple's web service operation return value: parameter Success = true`), but seems that pilot is not handling correctly this. At the end of the output it first prints "`iTunes Transporter successfully finished its job`", and then "`Error uploading ipa file, more information see above`", ending with an error.

Complete logs:
```
[09:41:16]: [Transporter]: DBG-X: The status for the file, b5b4f7feb96abd046e9b54511dcf9984.ipa, is TRANSFERRED.
[09:41:16]: [Transporter]: INFO: Package upload progress: 100% completed
[09:41:18]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[09:41:18]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[09:41:18]: [Transporter]: INFO: The file, metadata.xml, was uploaded successfully.
[09:41:18]: [Transporter]: INFO: The file, b5b4f7feb96abd046e9b54511dcf9984.ipa, was uploaded successfully.
[09:41:18]: [Transporter]: INFO: The status for the upload is SUCCESSFUL.
[09:41:18]: [Transporter]: INFO: The package's files (1066879813.itmsp) uploaded successfully.
[09:41:18]: [Transporter]: INFO: Done performing upload.
[09:41:18]: [Transporter]: DBG-X: The transfer time for the package 1066879813.itmsp was 1000734 milliseconds.
[09:41:18]: [Transporter]: DBG-X: Throughput information for 1066879813.itmsp: 16 minutes, 40,73 seconds, 42,00MB, 42,97KB/sec
[09:41:18]: [Transporter]: INFO: Performing uploadDone notification to Apple for package 1066879813.itmsp ...
[09:41:18]: [Transporter]: DBG-X: Deflated 814 bytes to 404
[09:41:18]: [Transporter]: DBG-X: Memory: [JVM] 936M free, 980M total, 980M max [System] (Physical) 365M free, 10240M total (Swap) 615M free, 1024M total
[09:41:18]: [Transporter]: DBG-X: Using operation named: uploadDoneWithArguments
[09:41:18]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[09:41:18]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[09:41:18]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[09:41:18]: [Transporter]: DBG-X:   parameter CPUToken = 1a7d8997-bec1-49f7-a9dc-fff7c35b34c7/1450340674995
[09:41:18]: [Transporter]: DBG-X:   parameter ClientChecksumInfo = [{FileSize=44038402, CalculatedChecksum=8c1de3251f3af41363bfc9d5cf7d26f3, FileLastModified=1450340581000, Filename=b5b4f7feb96abd046e9b54511dcf9984.ipa, CalculationTime=201}]
[09:41:18]: [Transporter]: DBG-X:   parameter ExtraTransportLogCompressed = (suppressed)
[09:41:18]: [Transporter]: DBG-X:   parameter FileSizeInfo = {metadata.xml=433, b5b4f7feb96abd046e9b54511dcf9984.ipa=44038402}
[09:41:18]: [Transporter]: DBG-X:   parameter NewPackageName = 1066879813-20151217002435-284.itmsp
[09:41:18]: [Transporter]: DBG-X:   parameter NumberBytesTransferred = 44038835
[09:41:18]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[09:41:18]: [Transporter]: DBG-X:   parameter PackagePathWithoutBase = sgr6_pod1/transporter/content/transporter/MyCompany
[09:41:18]: [Transporter]: DBG-X:   parameter Throttle = 100000
[09:41:18]: [Transporter]: DBG-X:   parameter TransferTime = 1000734
[09:41:18]: [Transporter]: DBG-X:   parameter Transport = Signiant
[09:41:18]: [Transporter]: DBG-X:   parameter TransportLogCompressed = (suppressed)
[09:41:18]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u my@email.me -p **hidden value** -f /tmp/1066879813.itmsp -t Signiant -k 100000
[09:41:18]: [Transporter]: DBG-X:   parameter Username = my@email.me
[09:41:18]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[09:41:18]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[09:41:18]: [Transporter]: INFO: id = 20151217094118-688
[09:51:34]: [Transporter Error Output]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
[09:51:34]: [Transporter Error Output]: An exception has occurred: Operation timed out
[09:51:34]: [Transporter]: DEBUG: java.net.SocketException: Operation timed out
[09:52:04]: [Transporter]: DBG-X: Using operation named: uploadDoneWithArguments
[09:52:04]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[09:52:04]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[09:52:04]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[09:52:04]: [Transporter]: DBG-X:   parameter CPUToken = 1a7d8997-bec1-49f7-a9dc-fff7c35b34c7/1450340674995
[09:52:04]: [Transporter]: DBG-X:   parameter ClientChecksumInfo = [{FileSize=44038402, CalculatedChecksum=8c1de3251f3af41363bfc9d5cf7d26f3, FileLastModified=1450340581000, Filename=b5b4f7feb96abd046e9b54511dcf9984.ipa, CalculationTime=201}]
[09:52:04]: [Transporter]: DBG-X:   parameter ExtraTransportLogCompressed = (suppressed)
[09:52:04]: [Transporter]: DBG-X:   parameter FileSizeInfo = {metadata.xml=433, b5b4f7feb96abd046e9b54511dcf9984.ipa=44038402}
[09:52:04]: [Transporter]: DBG-X:   parameter NewPackageName = 1066879813-20151217002435-284.itmsp
[09:52:04]: [Transporter]: DBG-X:   parameter NumberBytesTransferred = 44038835
[09:52:04]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[09:52:04]: [Transporter]: DBG-X:   parameter PackagePathWithoutBase = sgr6_pod1/transporter/content/transporter/MyCompany
[09:52:04]: [Transporter]: DBG-X:   parameter Throttle = 100000
[09:52:04]: [Transporter]: DBG-X:   parameter TransferTime = 1000734
[09:52:04]: [Transporter]: DBG-X:   parameter Transport = Signiant
[09:52:04]: [Transporter]: DBG-X:   parameter TransportLogCompressed = (suppressed)
[09:52:04]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u my@email.me -p **hidden value** -f /tmp/1066879813.itmsp -t Signiant -k 100000
[09:52:04]: [Transporter]: DBG-X:   parameter Username = my@email.me
[09:52:04]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[09:52:04]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[09:52:04]: [Transporter]: INFO: id = 20151217095204-080
[09:52:07]: [Transporter]: DBG-X: Apple's web service operation return value:
[09:52:07]: [Transporter]: DBG-X:   parameter Success = true
[09:52:08]: [Transporter]: DBG-X: Unlocking token at path /Users/alessandro/.itmstransporter/UploadTokens/MacBook-Pro-di-Alessandro.local_MyCompany_1066879813.itmsp.token
[09:52:08]: [Transporter]: DBG-X: Releasing token file lock
[09:52:08]: [Transporter]: DBG-X: Removing token at path /Users/alessandro/.itmstransporter/UploadTokens/MacBook-Pro-di-Alessandro.local_MyCompany_1066879813.itmsp.token
[09:52:08]: [Transporter]: INFO: Done performing uploadDone notification to Apple.
[09:52:08]: [Transporter]: INFO: The package: /tmp/1066879813.itmsp has been successfully uploaded.
[09:52:08]: iTunes Transporter successfully finished its job
[09:52:08]: [Transporter]: DBG-X: Returning 0
[09:52:08]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
An exception has occurred: Operation timed out
[09:52:08]: Variable Dump:
[09:52:08]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/alessandro/Dev/MyCompany/MyApp/MyApp.ipa", :DSYM_OUTPUT_PATH=>"/Users/alessandro/Dev/MyCompany/MyApp/MyApp.app.dSYM.zip"}
[09:52:08]: Error uploading ipa file, more information see above

```

Error stack: 
```
/Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/pilot-1.2.0/lib/pilot/build_manager.rb:27:in `upload': Error uploading ipa file, more information see above (RuntimeError)
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `execute_action'
[cut]
```

**Comment by lifeisfoo** [comment]
Another project with latest fastlane and latest xcode has the same error:
```
[18:09:17]: Login successful
[18:09:17]: Ready to upload new build to TestFlight (App: XXXXXXXXXX)...
[18:09:18]: Going to upload updated app to iTunes Connect
[18:09:18]: This might take a few minutes, please don't interrupt the script
[18:44:12]: [Transporter Error Output]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
[18:44:12]: [Transporter Error Output]: An exception has occurred: Operation timed out
[18:44:46]: iTunes Transporter successfully finished its job
[18:44:46]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
An exception has occurred: Operation timed out
[18:44:46]: Variable Dump:
[18:44:46]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/alessandro/Dev/app-ios/APP.ipa", :DSYM_OUTPUT_PATH=>"/Users/alessandro/Dev/app-ios/APP.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/alessandro/Library/Developer/Xcode/Archives/2016-06-09/APP 2016-06-09 18.04.42.xcarchive"}
[18:44:46]: Error uploading ipa file, for more information see above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 3           |
| 4    | gym                                 | 263         |
| 5    | pilot                               | 2141        |
+------+-------------------------------------+-------------+

[18:44:46]: fastlane finished with errors

[!] Error uploading ipa file, for more information see above
```

**Comment by lifeisfoo** [comment]
I'm not behind a firewall or a proxy, but I've tried also with `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" fastlane --verbose beta`

But I've the same issue:

```
[...]
DEBUG [2016-06-10 10:25:34.96]: [Transporter]: INFO: Package upload progress: 100% completed
DEBUG [2016-06-10 10:25:34.96]: [Transporter]: INFO: Finished upload of file: /tmp/1122600377.itmsp/metadata.xml.
DEBUG [2016-06-10 10:25:34.96]: [Transporter]: INFO: Gathering list of uploaded files from Apple's webDAV...
DEBUG [2016-06-10 10:25:34.96]: [Transporter]: DBG-X: Memory: [JVM] 801M free, 982M total, 982M max [System] (Physical) 1170M free, 16384M total (Swap) 1208M free, 5120M total
DEBUG [2016-06-10 10:25:35.31]: [Transporter]: INFO: Done gathering list of uploaded files from Apple's webDAV...
DEBUG [2016-06-10 10:25:35.31]: [Transporter]: INFO: Checking if any encryption/compression files are outdated locally ...
DEBUG [2016-06-10 10:25:35.31]: [Transporter]: DEBUG:   checking file: metadata.xml
DEBUG [2016-06-10 10:25:35.31]: [Transporter]: DBG-X:   Looking for compressed version of file: metadata.xml in folder: /tmp/1122600377.itmsp ...
DEBUG [2016-06-10 10:25:35.31]: [Transporter]: DEBUG:   checking file: 132e9c41b565ba08dcba22fdffdc3707.ipa
DEBUG [2016-06-10 10:25:35.31]: [Transporter]: DBG-X:   Looking for compressed version of file: 132e9c41b565ba08dcba22fdffdc3707.ipa in folder: /tmp/1122600377.itmsp ...
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: INFO: Finished checking if any encryption/compression files are outdated locally.
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: INFO: Confirming that the previously uploaded files were uploaded correctly ...
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DBG-X:    Ignoring file size while confirming files: false
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DEBUG:    confirmed file: 132e9c41b565ba08dcba22fdffdc3707.ipa
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DEBUG:    confirmed file: metadata.xml
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: INFO: Finished confirming that the previously uploaded files were uploaded correctly.
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DBG-X: Files previously uploaded successfully:
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: INFO: Determining which files were not uploaded ...
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DEBUG: Valid local files will be checked:
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DEBUG: Remote files uploaded:
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DEBUG: Skipped, metadata.xml has already been uploaded successfully
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DEBUG: Skipped, 132e9c41b565ba08dcba22fdffdc3707.ipa has already been uploaded successfully
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: INFO: Finished determining which files were not uploaded.
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DBG-X: ITMSPackage: files not uploaded:
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: INFO: Done performing upload.
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DBG-X: The transfer time for the package 1122600377.itmsp was 1340371 milliseconds.
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DBG-X: Throughput information for 1122600377.itmsp: 22 minutes, 20,37 seconds, 53,98MB, 41,24KB/sec
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: INFO: Performing uploadDone notification to Apple for package 1122600377.itmsp ...
DEBUG [2016-06-10 10:25:35.32]: [Transporter]: DBG-X: Deflated 6401 bytes to 976
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X: Memory: [JVM] 791M free, 982M total, 982M max [System] (Physical) 1162M free, 16384M total (Swap) 1208M free, 5120M total
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X: Using operation named: uploadDoneWithArguments
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.8
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter CPUToken = 8e10ff3f-c40b-4f6c-9624-46230efd3f84/1465545790828
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter ClientChecksumInfo = [{FileSize=56604506, CalculatedChecksum=ced28aae6dbeb7f268647b65ddf3a34c, FileLastModified=1465545693000, Filename=132e9c41b565ba08dcba22fdffdc3707.ipa, CalculationTime=172}]
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter ExtraTransportLogCompressed = (suppressed)
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter FileSizeInfo = {metadata.xml=452, 132e9c41b565ba08dcba22fdffdc3707.ipa=56604506}
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter NewPackageName = 1122600377-20160610010311-078.itmsp
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter NumberBytesTransferred = 56604958
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter PackagePathWithoutBase = /4/secret/uploading
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter TransferTime = 1340371
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter Transport = DAV
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter TransportLogCompressed = (suppressed)
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u alessandro@secrete -p **hidden value** -f /tmp/1122600377.itmsp -t DAV -t Signiant -k 100000
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter Username = alessandro@secrete
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter Version = 1.8.8
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-06-10 10:25:35.33]: [Transporter]: INFO: id = 20160610102535-219
ERROR [2016-06-10 10:25:35.40]: [Transporter Error Output]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
ERROR [2016-06-10 10:25:35.40]: [Transporter Error Output]: An exception has occurred: Connection reset
DEBUG [2016-06-10 10:25:35.40]: [Transporter]: DEBUG: java.net.SocketException: Connection reset
DEBUG [2016-06-10 10:26:05.40]: [Transporter]: DBG-X: Using operation named: uploadDoneWithArguments
DEBUG [2016-06-10 10:26:05.40]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-06-10 10:26:05.40]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.8
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter CPUToken = 8e10ff3f-c40b-4f6c-9624-46230efd3f84/1465545790828
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter ClientChecksumInfo = [{FileSize=56604506, CalculatedChecksum=ced28aae6dbeb7f268647b65ddf3a34c, FileLastModified=1465545693000, Filename=132e9c41b565ba08dcba22fdffdc3707.ipa, CalculationTime=172}]
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter ExtraTransportLogCompressed = (suppressed)
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter FileSizeInfo = {metadata.xml=452, 132e9c41b565ba08dcba22fdffdc3707.ipa=56604506}
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter NewPackageName = 1122600377-20160610010311-078.itmsp
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter NumberBytesTransferred = 56604958
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter PackagePathWithoutBase = /4/secret/uploading
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter TransferTime = 1340371
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter Transport = DAV
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter TransportLogCompressed = (suppressed)
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u alessandro@secrete -p **hidden value** -f /tmp/1122600377.itmsp -t DAV -t Signiant -k 100000
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter Username = alessandro@secrete
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter Version = 1.8.8
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-06-10 10:26:05.41]: [Transporter]: INFO: id = 20160610102605-082
DEBUG [2016-06-10 10:26:11.96]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2016-06-10 10:26:11.96]: [Transporter]: DBG-X:   parameter Success = true
DEBUG [2016-06-10 10:26:12.26]: [Transporter]: DBG-X: Unlocking token at path /Users/alessandro/.itmstransporter/UploadTokens/MBP-al.local_secret_1122600377.itmsp.token
DEBUG [2016-06-10 10:26:12.26]: [Transporter]: DBG-X: Releasing token file lock
DEBUG [2016-06-10 10:26:12.26]: [Transporter]: DBG-X: Removing token at path /Users/alessandro/.itmstransporter/UploadTokens/MBP-al.local_secret_1122600377.itmsp.token
DEBUG [2016-06-10 10:26:12.26]: [Transporter]: INFO: Done performing uploadDone notification to Apple.
DEBUG [2016-06-10 10:26:12.27]: [Transporter]: INFO: The package: /tmp/1122600377.itmsp has been successfully uploaded.
INFO [2016-06-10 10:26:12.38]: iTunes Transporter successfully finished its job
DEBUG [2016-06-10 10:26:12.38]: [Transporter]: DBG-X: Returning 0
ERROR [2016-06-10 10:26:12.45]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
An exception has occurred: Connection reset
WARN [2016-06-10 10:26:12.50]: Variable Dump:
INFO [2016-06-10 10:26:12.50]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/alessandro/Dev/app/app-ios/app.ipa", :DSYM_OUTPUT_PATH=>"/Users/alessandro/Dev/app/app-ios/app.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/alessandro/Library/Developer/Xcode/Archives/2016-06-10/app 2016-06-10 09.57.02.xcarchive"}
ERROR [2016-06-10 10:26:12.50]: Error uploading ipa file, for more information see above
INFO [2016-06-10 10:26:12.50]: Successfully generated documentation to path '/Users/alessandro/Dev/app/app-ios/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 2           |
| 4    | gym                                 | 265         |
| 5    | pilot                               | 1485        |
+------+-------------------------------------+-------------+

ERROR [2016-06-10 10:26:12.51]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Error uploading ipa file, for more information see above (FastlaneCore::Interface::FastlaneError)
```

Seems that the error is the same of #1914 

Fastlane tools version are: `fastlane 1.94.1` and `pilot 1.9.2`
