### ISSUE TITLE
Error when trying to retrieve TestFlight tester data

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1895]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/3168994?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @tomdixon - Imported from <a href='https://github.com/fastlane/pilot/issues/85'>fastlane/pilot#85</a>
        </td>
      </tr>
    </table>

I'm getting the following error when running either `pilot list` or `pilot export`. It authenticates successfully but then gets an error response from iTunes Connect. `pilot builds` is working fine.

```
[18:22:40]: Login successful
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.14.2/lib/spaceship/client.rb:263:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Forbidden"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.14.2/lib/spaceship/tunes/tunes_client.rb:636:in `testers'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.14.2/lib/spaceship/tunes/tester.rb:74:in `all'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/tester_manager.rb:70:in `list_testers'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/commands_generator.rb:76:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/commands_generator.rb:120:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/commands_generator.rb:17:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'
```

**Comment by gnasit** [comment]
any update on this issue?

**Comment by jorgeazevedo** [comment]
@gnasit this pull request addresses the issue
https://github.com/fastlane/fastlane/issues/4686 , still to be merged though

**Comment by TKBurner** [comment]
Hi @jorgeazevedo Thanks for following up. Can you add test coverage to your PR?

@gnasit Can you try the PR and see if it resolves your issue? Thanks! 👍
