### ISSUE TITLE
Additional login required after Spaceship::Portal.provisioning_profile

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [fastlane/fastlane#18973]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm seeing some weird behaviour when trying to create new iOS provisioning profiles. I have to login an additional time after calling `Spaceship::Portal.provisioning_profile.all` and before calling `Spaceship::Portal.provisioning_profile.app_store.create!` or I'll get a "Bad Request" error.

So, in below `Fastfile` having this in the `create_profile_test` lane will fail:

```
  spaceship_portal_login(username, password, team_id)
  existing_profiles = Spaceship::Portal.provisioning_profile.all
  certificate = Spaceship::Portal.certificate.all.find {|cert| cert.id === cert_id}
  create_provisioning_profile(app_identifier, provisioning_name, certificate)
```

But this will succeed (added an additional login call after fetching provisioning profiles):

```
  spaceship_portal_login(username, password, team_id)
  existing_profiles = Spaceship::Portal.provisioning_profile.all
  spaceship_portal_login(username, password, team_id)                           # Added
  certificate = Spaceship::Portal.certificate.all.find {|cert| cert.id === cert_id}
  create_provisioning_profile(app_identifier, provisioning_name, certificate)
```

And this will also succeed (removed fetching provisioning profiles):

```
  spaceship_portal_login(username, password, team_id)
  # existing_profiles = Spaceship::Portal.provisioning_profile.all              # Removed
  certificate = Spaceship::Portal.certificate.all.find {|cert| cert.id === cert_id}
  create_provisioning_profile(app_identifier, provisioning_name, certificate)
```

I would expect this to work without having to log in again after fetching existing provisioning profiles.

##### Command executed

Create a `Fastfile` with the following content:

```
# Fastfile

lane :create_profile_test do
  username = "<APPLE_USERNAME>"
  password = "<APPLE_PASSWORD"
  app_identifier = "<BUNDLE_ID>"
  provisioning_name = "FOO BAR"
  cert_id = "<CERTIFICATE_ID>"
  team_id = "<TEAM_ID>"

  ## CHANGE BELOW LINES
  spaceship_portal_login(username, password, team_id)
  existing_profiles = Spaceship::Portal.provisioning_profile.all
  # spaceship_portal_login(username, password, team_id) # <-- Uncommenting this second login line will fix the "Bad Request" error
  ## CHANGE ABOVE LINES

  certificate = Spaceship::Portal.certificate.all.find {|cert| cert.id === cert_id}
  create_provisioning_profile(app_identifier, provisioning_name, certificate)
end

def create_provisioning_profile(app_identifier, provisioning_name, certificate)
  profile = Spaceship::Portal.provisioning_profile.app_store.create!(
    name: provisioning_name,
    bundle_id: app_identifier,
    certificate: certificate
  )
end

def spaceship_portal_login(username, password, team_id)
  Spaceship::Portal.login(username, password)
  Spaceship::Portal.client.team_id = team_id
end
```

Run the following command:
`bundle exec fastlane create_profile_test`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> ### Captured Output

Command Used: `create_profile_test --capture_output`
<details><summary>Output/Log</summary>

```

DEBUG [2021-06-25 10:27:41.51]: Checking if there are any plugins that should be loaded...
DEBUG [2021-06-25 10:27:41.51]: Loading 'fastlane-plugin-update_project_codesigning' plugin
INFO [2021-06-25 10:27:41.51]: gem 'fastlane-plugin-update_project_codesigning' is already installed
DEBUG [2021-06-25 10:27:41.51]: Loading 'fastlane-plugin-tpa' plugin
INFO [2021-06-25 10:27:41.52]: gem 'fastlane-plugin-tpa' is already installed
DEBUG [2021-06-25 10:27:41.52]: Loading 'fastlane-plugin-prepare_build_resources' plugin
INFO [2021-06-25 10:27:41.52]: gem 'fastlane-plugin-prepare_build_resources' is already installed
DEBUG [2021-06-25 10:27:41.52]: Loading 'fastlane-plugin-versioning' plugin
INFO [2021-06-25 10:27:41.52]: gem 'fastlane-plugin-versioning' is already installed
DEBUG [2021-06-25 10:27:41.53]: Loading 'fastlane-plugin-badge' plugin
INFO [2021-06-25 10:27:41.53]: gem 'fastlane-plugin-badge' is already installed
DEBUG [2021-06-25 10:27:41.53]: Loading 'fastlane-plugin-swiftlint_codequality' plugin
INFO [2021-06-25 10:27:41.53]: gem 'fastlane-plugin-swiftlint_codequality' is already installed


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                   |
| --------------------------- | ----------------------------------------------------------------------- |
| OS                          | 11.4                                                                    |
| Ruby                        | 3.0.1                                                                   |
| Bundler?                    | true                                                                    |
| Git                         | git version 2.30.0                                                      |
| Installation Source         | ~/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.1/lib                                        |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                                             |
| Is contained                | false                                                                   |
| Is homebrew                 | false                                                                   |
| Is installed via Fabric.app | false                                                                   |
| Xcode Path                  | /Applications/Xcode_12_0.app/Contents/Developer/                        |
| Xcode Version               | 12.5.1                                                                  |
| Swift Version               | 5.4.2                                                                   |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.186.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status      |
| ------------------------------------------ | ------- | ------------------ |
| fastlane-plugin-update_project_codesigning | 0.2.0   | ✅ Up-To-Date       |
| fastlane-plugin-tpa                        | 2.2.0   | ✅ Up-To-Date       |
| fastlane-plugin-prepare_build_resources    | 1.0.4   | ✅ Up-To-Date       |
| fastlane-plugin-versioning                 | 0.4.5   | ✅ Up-To-Date       |
| fastlane-plugin-badge                      | 1.5.0   | ✅ Up-To-Date       |
| fastlane-plugin-swiftlint_codequality      | 1.0.1   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| did_you_mean                               | 1.5.0        |
| bundler                                    | 2.2.15       |
| tsort                                      | 0.1.0        |
| uri                                        | 0.10.1       |
| pathname                                   | 0.1.0        |
| rake                                       | 13.0.3       |
| CFPropertyList                             | 3.0.3        |
| concurrent-ruby                            | 1.1.9        |
| i18n                                       | 1.8.10       |
| minitest                                   | 5.14.4       |
| thread_safe                                | 0.3.6        |
| tzinfo                                     | 1.2.9        |
| activesupport                              | 5.2.6        |
| public_suffix                              | 4.0.6        |
| addressable                                | 2.7.0        |
| httpclient                                 | 2.8.3        |
| json                                       | 2.5.1        |
| algoliasearch                              | 1.27.5       |
| artifactory                                | 3.0.15       |
| atomos                                     | 0.1.3        |
| aws-eventstream                            | 1.1.1        |
| aws-partitions                             | 1.471.0      |
| aws-sigv4                                  | 1.2.3        |
| jmespath                                   | 1.4.0        |
| aws-sdk-core                               | 3.115.0      |
| aws-sdk-kms                                | 1.44.0       |
| aws-sdk-s3                                 | 1.96.1       |
| babosa                                     | 1.0.4        |
| fastimage                                  | 2.2.4        |
| colored                                    | 1.2          |
| highline                                   | 2.0.3        |
| commander                                  | 4.6.0        |
| dotenv                                     | 2.7.6        |
| emoji_regex                                | 3.2.2        |
| excon                                      | 0.82.0       |
| faraday-em_http                            | 1.0.0        |
| faraday-em_synchrony                       | 1.0.0        |
| faraday-excon                              | 1.1.0        |
| faraday-net_http                           | 1.0.1        |
| faraday-net_http_persistent                | 1.1.0        |
| multipart-post                             | 2.0.0        |
| ruby2_keywords                             | 0.0.4        |
| faraday                                    | 1.4.3        |
| unf_ext                                    | 0.0.7.7      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20190701 |
| http-cookie                                | 1.0.4        |
| faraday-cookie_jar                         | 0.0.7        |
| faraday_middleware                         | 1.0.0        |
| gh_inspector                               | 1.1.3        |
| jwt                                        | 2.2.3        |
| memoist                                    | 0.16.2       |
| multi_json                                 | 1.15.0       |
| os                                         | 1.1.1        |
| signet                                     | 0.15.0       |
| googleauth                                 | 0.16.2       |
| mini_mime                                  | 1.1.0        |
| declarative                                | 0.0.20       |
| trailblazer-option                         | 0.1.1        |
| uber                                       | 0.1.0        |
| representable                              | 3.1.1        |
| retriable                                  | 3.1.2        |
| rexml                                      | 3.2.5        |
| webrick                                    | 1.7.0        |
| google-apis-core                           | 0.3.0        |
| google-apis-androidpublisher_v3            | 0.6.0        |
| google-apis-playcustomapp_v1               | 0.3.0        |
| digest-crc                                 | 0.6.3        |
| google-apis-iamcredentials_v1              | 0.4.0        |
| google-apis-storage_v1                     | 0.4.0        |
| google-cloud-env                           | 1.5.0        |
| google-cloud-errors                        | 1.1.0        |
| google-cloud-core                          | 1.6.0        |
| google-cloud-storage                       | 1.32.0       |
| mini_magick                                | 4.11.0       |
| naturally                                  | 2.2.1        |
| plist                                      | 3.6.0        |
| rubyzip                                    | 2.3.0        |
| security                                   | 0.1.3        |
| simctl                                     | 1.6.8        |
| terminal-notifier                          | 2.0.0        |
| unicode-display_width                      | 1.7.0        |
| terminal-table                             | 1.8.0        |
| tty-screen                                 | 0.8.1        |
| tty-cursor                                 | 0.7.1        |
| tty-spinner                                | 0.9.3        |
| word_wrap                                  | 1.0.0        |
| claide                                     | 1.0.3        |
| colored2                                   | 3.1.2        |
| nanaimo                                    | 0.3.0        |
| xcodeproj                                  | 1.19.0       |
| rouge                                      | 2.0.7        |
| xcpretty                                   | 0.3.0        |
| xcpretty-travis-formatter                  | 1.0.1        |
| badge                                      | 0.13.0       |
| chunky_png                                 | 1.4.0        |
| fuzzy_match                                | 2.0.4        |
| nap                                        | 1.1.0        |
| netrc                                      | 0.11.0       |
| ffi                                        | 1.15.3       |
| ethon                                      | 0.14.0       |
| typhoeus                                   | 1.4.0        |
| cocoapods-core                             | 1.10.1       |
| cocoapods-deintegrate                      | 1.0.4        |
| cocoapods-downloader                       | 1.4.0        |
| cocoapods-plugins                          | 1.0.0        |
| cocoapods-search                           | 1.0.0        |
| cocoapods-trunk                            | 1.5.0        |
| cocoapods-try                              | 1.2.0        |
| escape                                     | 0.0.4        |
| fourflusher                                | 2.3.1        |
| molinillo                                  | 0.6.6        |
| ruby-macho                                 | 1.4.0        |
| cocoapods                                  | 1.10.1       |
| fastlane-plugin-badge                      | 1.5.0        |
| fastlane-plugin-prepare_build_resources    | 1.0.4        |
| fastlane-plugin-swiftlint_codequality      | 1.0.1        |
| mime-types-data                            | 3.2021.0225  |
| mime-types                                 | 3.3.1        |
| rest-client                                | 2.0.2        |
| fastlane-plugin-tpa                        | 2.2.0        |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
| fastlane-plugin-versioning                 | 0.4.5        |
| rqrcode_core                               | 1.0.0        |
| rqrcode                                    | 2.0.0        |
| xcode-install                              | 2.7.0        |
</details>

*generated on:* **2021-06-25**
</details> </pre>
</details>

Command output/error:
<details>
<pre>
jens@C02D40FVMD6T ios % bundle exec fastlane create_profile_test

[✔] 🚀
+-------------------------------+---------+-------------------------------+
|                              Used plugins                               |
+-------------------------------+---------+-------------------------------+
| Plugin                        | Version | Action                        |
+-------------------------------+---------+-------------------------------+
| fastlane-plugin-update_proje  | 0.2.0   | update_project_codesigning    |
| ct_codesigning                |         |                               |
| fastlane-plugin-tpa           | 2.2.0   | tpa, upload_symbols_to_tpa,   |
|                               |         | upload_to_tpa                 |
| fastlane-plugin-prepare_buil  | 1.0.4   | prepare_build_resources       |
| d_resources                   |         |                               |
| fastlane-plugin-versioning    | 0.4.5   | ci_build_number,              |
|                               |         | get_app_store_version_number  |
|                               |         | ,                             |
|                               |         | get_build_number_from_plist,  |
|                               |         | get_build_number_from_xcodep  |
|                               |         | roj, get_info_plist_path,     |
|                               |         | get_version_number_from_git_  |
|                               |         | branch,                       |
|                               |         | get_version_number_from_plis  |
|                               |         | t,                            |
|                               |         | get_version_number_from_xcod  |
|                               |         | eproj,                        |
|                               |         | increment_build_number_in_pl  |
|                               |         | ist,                          |
|                               |         | increment_build_number_in_xc  |
|                               |         | odeproj,                      |
|                               |         | increment_version_number_in_  |
|                               |         | plist,                        |
|                               |         | increment_version_number_in_  |
|                               |         | xcodeproj                     |
| fastlane-plugin-badge         | 1.5.0   | add_badge                     |
| fastlane-plugin-swiftlint_co  | 1.0.1   | swiftlint_codequality         |
| dequality                     |         |                               |
+-------------------------------+---------+-------------------------------+

[10:44:47]: ------------------------------
[10:44:47]: --- Step: default_platform ---
[10:44:47]: ------------------------------
[10:44:47]: Driving the lane 'create_profile_test' 🚀
[10:44:47]: -----------------------
[10:44:47]: --- Step: xcversion ---
[10:44:47]: -----------------------
[10:44:47]: Setting Xcode version to /Applications/Xcode_12_0.app for all build steps
Available session is not valid any more. Continuing with normal login.
+------------------+---------------------+
|              Lane Context              |
+------------------+---------------------+
| DEFAULT_PLATFORM | ios                 |
| PLATFORM_NAME    |                     |
| LANE_NAME        | create_profile_test |
+------------------+---------------------+
[10:44:52]: Bad Request

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | xcversion        | 0           |
+------+------------------+-------------+

+-----------------------+--------------+----------------+
|               Plugin updates available                |
+-----------------------+--------------+----------------+
| Plugin                | Your Version | Latest Version |
+-----------------------+--------------+----------------+
| swiftlint_codequality | 1.0.1        | 2.0.1          |
+-----------------------+--------------+----------------+
[10:44:52]: To update all plugins, just run
[10:44:52]: $ bundle exec fastlane update_plugins

[10:44:52]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlane supply aab to internal track fail with google api error bad request
    https://github.com/fastlane/fastlane/issues/18670 [open] 10 💬
    2 weeks ago

➡️  [Discuss] Operating System compatibility of tools and actions
    https://github.com/fastlane/fastlane/issues/11859 [open] 11 💬
    07 Mar 2021

➡️  [pilot] Add support for using App Store Connect API keys for iTunes Transporter
    https://github.com/fastlane/fastlane/pull/14486 [open] 7 💬
    03 Jul 2020

and 415 more at: https://github.com/fastlane/fastlane/search?q=Bad%20Request&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/bin/fastlane)
/Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/spaceship/lib/spaceship/client.rb:747:in `parse_response': \e[31m[!] Bad Request\e[0m (Spaceship::UnexpectedResponse)
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/spaceship/lib/spaceship/portal/portal_client.rb:703:in `create_provisioning_profile!'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:297:in `block in create!'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/spaceship/lib/spaceship/client.rb:646:in `with_retry'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:296:in `create!'
	from Fastfile:497:in `create_provisioning_profile'
	from Fastfile:493:in `block in parsing_binding'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/gems/fastlane-2.186.0/bin/fastlane:23:in `<top (required)>'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/bin/fastlane:23:in `load'
	from /Users/jens/Documents/repos/mobile-bank/ios/vendor/bundle/ruby/3.0.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:494:in `exec'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
	from /usr/local/opt/ruby/bin/bundle:23:in `load'
	from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
</pre>
</details>

**Comment by Klaudas** [comment]
I'm facing the same problem
