### ISSUE TITLE
Error running tests: Operation not permitted - //Library/Application Support/com.apple.TCC

### ISSUE THREAD

**Issue by nsoojin** [fastlane/fastlane#19098]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running a simple `run_tests` command, but failing with error `Operation not permitted - //Library/Application Support/com.apple.TCC`

##### Command executed

```ruby
lane :run_myapp_tests do
    run_tests(
      scheme: "MyApp-BetaTests",
      devices: ["iPhone 12 Pro Max"],
    )
 end
```

Running tests from Xcode works perfectly fine.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀 
+--------------------------+---------+---------------------------------------------------------------+
|                                            Used plugins                                            |
+--------------------------+---------+---------------------------------------------------------------+
| Plugin                   | Version | Action                                                        |
+--------------------------+---------+---------------------------------------------------------------+
| fastlane-plugin-xcconfig | 2.0.0   | update_xcconfig_value, set_xcconfig_value, get_xcconfig_value |
+--------------------------+---------+---------------------------------------------------------------+

[17:56:10]: ------------------------------
[17:56:10]: --- Step: default_platform ---
[17:56:10]: ------------------------------
[17:56:10]: Driving the lane 'ios run_maker_tests' 🚀
[17:56:10]: --------------------------------
[17:56:10]: --- Step: clear_derived_data ---
[17:56:10]: --------------------------------
[17:56:10]: Derived Data path located at: /Users/soojin/Library/Developer/Xcode/DerivedData
[17:56:11]: Successfully cleared Derived Data ♻️
[17:56:11]: -----------------------
[17:56:11]: --- Step: run_tests ---
[17:56:11]: -----------------------
[17:56:11]: Resolving Swift Package Manager dependencies...
[17:56:11]: $ xcodebuild -resolvePackageDependencies -workspace ./Momenti-iOS.xcworkspace -scheme MOMaker-BetaTests
[17:56:11]: ▸ objc[9073]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f79eec10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1183b82b8). One of the two will be used. Which one is undefined.
[17:56:11]: ▸ objc[9073]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f79eec60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1183b8308). One of the two will be used. Which one is undefined.
[17:56:11]: ▸ Command line invocation:
[17:56:11]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./Momenti-iOS.xcworkspace -scheme MOMaker-BetaTests
[17:56:11]: ▸ User defaults from command line:
[17:56:11]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[17:56:12]: ▸ Resolve Package Graph
[17:56:12]: ▸ Fetching from https://github.com/xmartlabs/Eureka.git (cached)
[17:56:13]: ▸ Fetching from https://github.com/optonaut/ActiveLabel.swift (cached)
[17:56:13]: ▸ Fetching from https://github.com/kean/Nuke.git (cached)
[17:56:13]: ▸ Fetching from https://github.com/apple/swift-protobuf.git (cached)
[17:56:13]: ▸ Fetching from https://github.com/marmelroy/Localize-Swift.git (cached)
[17:56:13]: ▸ Fetching from https://github.com/apple/swift-log.git (cached)
[17:56:16]: ▸ Cloning local copy of package ‘ActiveLabel.swift’
[17:56:16]: ▸ Checking out 1.1.0 of package ‘ActiveLabel.swift’
[17:56:16]: ▸ Cloning local copy of package ‘Nuke’
[17:56:16]: ▸ Checking out 8.4.1 of package ‘Nuke’
[17:56:16]: ▸ Cloning local copy of package ‘Eureka’
[17:56:16]: ▸ Checking out 5.3.1 of package ‘Eureka’
[17:56:17]: ▸ Cloning local copy of package ‘Localize-Swift’
[17:56:17]: ▸ Checking out 3.1.0 of package ‘Localize-Swift’
[17:56:17]: ▸ Cloning local copy of package ‘swift-protobuf’
[17:56:17]: ▸ Checking out 1.8.0 of package ‘swift-protobuf’
[17:56:17]: ▸ Cloning local copy of package ‘swift-log’
[17:56:17]: ▸ Checking out 1.2.0 of package ‘swift-log’
[17:56:18]: ▸ Resolved source packages:
[17:56:18]: ▸   Nuke: https://github.com/kean/Nuke.git @ 8.4.1
[17:56:18]: ▸   SwiftProtobuf: https://github.com/apple/swift-protobuf.git @ 1.8.0
[17:56:18]: ▸   Eureka: https://github.com/xmartlabs/Eureka.git @ 5.3.1
[17:56:18]: ▸   swift-log: https://github.com/apple/swift-log.git @ 1.2.0
[17:56:18]: ▸   Localize_Swift: https://github.com/marmelroy/Localize-Swift.git @ 3.1.0
[17:56:18]: ▸   ActiveLabel: https://github.com/optonaut/ActiveLabel.swift @ 1.1.0
[17:56:18]: ▸ resolved source packages: Nuke, SwiftProtobuf, Eureka, swift-log, Localize_Swift, ActiveLabel
[17:56:18]: $ xcodebuild -showBuildSettings -workspace ./Momenti-iOS.xcworkspace -scheme MOMaker-BetaTests
objc[9485]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f79eec10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x113fbc2b8). One of the two will be used. Which one is undefined.
objc[9485]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f79eec60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x113fbc308). One of the two will be used. Which one is undefined.
+------------------------+---------------------+
|                 Lane Context                 |
+------------------------+---------------------+
| DEFAULT_PLATFORM       | ios                 |
| PLATFORM_NAME          | ios                 |
| LANE_NAME              | ios run_maker_tests |
| SCAN_DERIVED_DATA_PATH | /                   |
+------------------------+---------------------+
[17:56:20]: Operation not permitted - //Library/Application Support/com.apple.TCC

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | default_platform   | 0           |
| 2    | clear_derived_data | 0           |
| 💥   | run_tests          | 9           |
+------+--------------------+-------------+

[17:56:20]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/soojin/.rbenv/versions/2.7.3/bin/fastlane)
Traceback (most recent call last):
	44: from /Users/soojin/.rbenv/versions/2.7.3/bin/bundle:23:in `<main>'
	43: from /Users/soojin/.rbenv/versions/2.7.3/bin/bundle:23:in `load'
	42: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/exe/bundle:37:in `<top (required)>'
	41: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	40: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/exe/bundle:49:in `block in <top (required)>'
	39: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli.rb:24:in `start'
	38: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	37: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli.rb:30:in `dispatch'
	36: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	35: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	34: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	33: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli.rb:474:in `exec'
	32: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:28:in `run'
	31: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:63:in `kernel_load'
	30: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:63:in `load'
	29: from /Users/soojin/.rbenv/versions/2.7.3/bin/fastlane:23:in `<top (required)>'
	28: from /Users/soojin/.rbenv/versions/2.7.3/bin/fastlane:23:in `load'
	27: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
	26: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	25: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	24: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	23: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	22: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	21: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	20: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	19: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	18: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	17: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	16: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	15: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	14: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	13: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	12: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:25:in `block (2 levels) in parsing_binding'
	10: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 7: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 6: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 5: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 4: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 3: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/run_tests.rb:16:in `run'
	 2: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/scan/lib/scan/manager.rb:12:in `work'
	 1: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/scan/lib/scan/manager.rb:30:in `test_summary_filenames'
/Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/scan/lib/scan/manager.rb:30:in `[]': Operation not permitted - //Library/Application Support/com.apple.TCC (Errno::EPERM)
	44: from /Users/soojin/.rbenv/versions/2.7.3/bin/bundle:23:in `<main>'
	43: from /Users/soojin/.rbenv/versions/2.7.3/bin/bundle:23:in `load'
	42: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/exe/bundle:37:in `<top (required)>'
	41: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	40: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/exe/bundle:49:in `block in <top (required)>'
	39: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli.rb:24:in `start'
	38: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	37: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli.rb:30:in `dispatch'
	36: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	35: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	34: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	33: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli.rb:474:in `exec'
	32: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:28:in `run'
	31: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:63:in `kernel_load'
	30: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:63:in `load'
	29: from /Users/soojin/.rbenv/versions/2.7.3/bin/fastlane:23:in `<top (required)>'
	28: from /Users/soojin/.rbenv/versions/2.7.3/bin/fastlane:23:in `load'
	27: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
	26: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	25: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	24: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	23: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	22: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	21: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	20: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	19: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	18: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	17: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	16: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	15: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	14: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	13: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	12: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:25:in `block (2 levels) in parsing_binding'
	10: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 7: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 6: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 5: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 4: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 3: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/run_tests.rb:39:in `run'
	 2: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/run_tests.rb:36:in `ensure in run'
	 1: from /Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/scan/lib/scan/manager.rb:30:in `test_summary_filenames'
/Users/soojin/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/scan/lib/scan/manager.rb:30:in `[]': \e[31m[!] Operation not permitted - //Library/Application Support/com.apple.TCC\e[0m (Errno::EPERM) </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.4                                        |
| Ruby                        | 2.7.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.32.0                          |
| Installation Source         | ~/.rbenv/versions/2.7.3/bin/fastlane        |
| Host                        | macOS 11.4 (20F71)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    clear_derived_data
  end

  lane :run_maker_tests do
    run_tests(
      scheme: "MOMaker-BetaTests",
      # workspace: "Momenti-iOS.xcworkspace",
      devices: ["iPhone 12 Pro Max"],
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                   | Version | Update-Status |
| ------------------------ | ------- | ------------- |
| fastlane-plugin-xcconfig | 2.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| bundler                         | 2.2.19       |
| uri                             | 0.10.0       |
| rake                            | 13.0.3       |
| CFPropertyList                  | 3.0.3        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.473.0      |
| aws-sigv4                       | 1.2.3        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.115.0      |
| aws-sdk-kms                     | 1.44.0       |
| aws-sdk-s3                      | 1.96.1       |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.3        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.83.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.3        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.0        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.0        |
| google-apis-androidpublisher_v3 | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.4.0        |
| google-apis-iamcredentials_v1   | 0.5.0        |
| google-apis-storage_v1          | 0.5.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.0       |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-xcconfig        | 2.0.0        |
</details>

*generated on:* **2021-07-14**
</details> </pre>
</details>

**Comment by nsoojin** [comment]
It was resolved after setting the 'Executable' in the test scheme's Run tab
