### ISSUE TITLE
Could not find action, lane or variable 'chcp'

### ISSUE THREAD

**Issue by AlaaZarifa** [fastlane/fastlane#19093]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

---

### Issues #15835 & #15434 are very similar to my problem, but none of them have been solved yet. 

---

##### Command executed
```
bundle exec fastlane base_app app:base_app 

// Sometimes it gives me the error below after running the prev command 
[(ArgumentError) unknown encoding name - CP720]

..but I slove it by running this [chcp 1252]
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>Everything used to work fine for the last months or so, I upload it to Google Play Store
   with every sprint release and no problem shows, but suddenly a few days ago when I run the command to
   upload a new release to the store, this error keeps showing:

   **Could not find action, lane or variable 'chcp'. Check out the documentation for more details: https://docs.fastlane.tools/actions\e[0m (FastlaneCore::Interface::FastlaneError)**
 Keeping in mind that I haven't change anything inside the Fastfile, I just generate a new aab and run the command, and every time it works normally, expect this time. 😕 </pre>

**Fastfile:** (P.S I replaced the app name with *)
```
  lane :base_app do
    supply(track: 'production',package_name: 'com.******',aab: "C:\\Android Projects\\New folder\\******\\app\\******\\release\\app-******-release.aab")
  end
```

**Debug Info (verbose mode):** 

<details>
<summary>Show results..</summary>
<p>

```


C:\Android Projects\New folder\******>bundle exec fastlane base_app --verbose
[✔] �
DEBUG [2021-07-13 16:56:07.50]: Checking if there are any plugins that should be loaded...
DEBUG [2021-07-13 16:56:07.51]: Loading 'fastlane-plugin-ruby' plugin
INFO [2021-07-13 16:56:07.51]: gem 'fastlane-plugin-ruby' is already installed
DEBUG [2021-07-13 16:56:07.52]: Loading 'fastlane-plugin-get_version_name' plugin
INFO [2021-07-13 16:56:07.53]: gem 'fastlane-plugin-get_version_name' is already installed
DEBUG [2021-07-13 16:56:07.54]: Loading 'fastlane-plugin-increment_version_code' plugin
INFO [2021-07-13 16:56:07.54]: gem 'fastlane-plugin-increment_version_code' is already installed
DEBUG [2021-07-13 16:56:07.55]: Loading 'fastlane-plugin-get_version_code' plugin
INFO [2021-07-13 16:56:07.55]: gem 'fastlane-plugin-get_version_code' is already installed
DEBUG [2021-07-13 16:56:07.57]: Loading 'fastlane-plugin-commit_android_version_bump' plugin
INFO [2021-07-13 16:56:07.57]: gem 'fastlane-plugin-commit_android_version_bump' is already installed
DEBUG [2021-07-13 16:56:07.58]: Loading 'fastlane-plugin-bundletool' plugin
INFO [2021-07-13 16:56:07.58]: gem 'fastlane-plugin-bundletool' is already installed
+---------------------------------------------+---------+-----------------------------+
|                                    Used plugins                                     |
+---------------------------------------------+---------+-----------------------------+
| Plugin                                      | Version | Action                      |
+---------------------------------------------+---------+-----------------------------+
| fastlane-plugin-ruby                        | 0.1.3   | rspec, rubocop              |
| fastlane-plugin-get_version_name            | 0.2.2   | get_version_name            |
| fastlane-plugin-increment_version_code      | 0.4.3   | increment_version_code      |
| fastlane-plugin-get_version_code            | 0.2.0   | get_version_code            |
| fastlane-plugin-commit_android_version_bump | 0.2.0   | commit_android_version_bump |
| fastlane-plugin-bundletool                  | 1.0.3   | bundletool                  |
+---------------------------------------------+---------+-----------------------------+

Successfully loaded Appfile at path 'C:/Android Projects/New folder/******/fastlane/Appfile'
- json_key_file: 'C:\Android Projects\New folder\******\fastlane\service_account_key.json'
-------
Successfully loaded Appfile at path 'C:/Android Projects/New folder/******/fastlane/Appfile'
- json_key_file: 'C:\Android Projects\New folder\******\fastlane\service_account_key.json'
-------
INFO [2021-07-13 16:56:07.65]: ------------------------------
INFO [2021-07-13 16:56:07.65]: --- Step: default_platform ---
INFO [2021-07-13 16:56:07.66]: ------------------------------
DEBUG [2021-07-13 16:56:07.66]: E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
Fastfile:245:in `parsing_binding'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:15:in `new'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:15:in `cruise_lane'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
E:/Ruby27-x64/bin/fastlane:23:in `load'
E:/Ruby27-x64/bin/fastlane:23:in `<main>'
DEBUG [2021-07-13 16:56:50.65]: All plugins are up to date
Traceback (most recent call last):
24: from E:/Ruby27-x64/bin/fastlane:23:in `<main>'
23: from E:/Ruby27-x64/bin/fastlane:23:in `load'
22: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
21: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
20: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
19: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
18: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
17: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
16: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
15: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
14: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
13: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
12: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
11: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:15:in `cruise_lane'
10: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:15:in `new'
9: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
8: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
7: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
6: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
5: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
4: from Fastfile:245:in `parsing_binding'
3: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:174:in `trigger_action_by_name'
1: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Could not find action, lane or variable 'chcp'. Check out the documentation fo
r more details: https://docs.fastlane.tools/actions (FastlaneCore::Interface::FastlaneError)
24: from E:/Ruby27-x64/bin/fastlane:23:in `<main>'
23: from E:/Ruby27-x64/bin/fastlane:23:in `load'
22: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
21: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
20: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
19: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
18: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
17: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
16: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
15: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
14: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
13: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
12: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
11: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:15:in `cruise_lane'
10: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:15:in `new'
9: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
8: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
7: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
6: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
5: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
4: from Fastfile:245:in `parsing_binding'
3: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Could not find action, lane or variable 'chcp'. Check out the documentation for more details: https://docs.fastlane.tools/actions\e[0m (FastlaneCore::Interface::FastlaneError)    E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Could not find action, lane or variable 'chcp'. Check out the documentationE:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastE:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31mE:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Could not find action, lane or variable 'chcp'.
Check out the documentation for more details: https://docs.fastlane.tools/actions\e[0m (FastlaneCore::Interface::FastlaneError)

```

</p>
</details>
 

</details>

### Environment

<details>
  <pre>
| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.7.1                        |
| Bundler?                    | false                        |
| Git                         | git version 2.27.0.windows.1 |
| Installation Source         | E:/Ruby27-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | E:/Ruby27-x64/lib            |
| OpenSSL Version             | OpenSSL 1.1.1e  17 Mar 2020  |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

</pre>
</details>

**Comment by AlaaZarifa** [comment]
@fastlane-bot I did in fact included the output of `fastlane env`  check again mr bot 🤖

**Comment by AlaaZarifa** [comment]
I just found that the root problem comes from this line` chcp 1252` that was inside the `Fastfile `and apparently I forgot to comment it 😓  forgive my sutpidity guys 😄
