### ISSUE TITLE
REGARDING_PILOT

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1913]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/7186437?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @parthitheindian - Imported from <a href='https://github.com/fastlane/pilot/issues/39'>fastlane/pilot#39</a>
        </td>
      </tr>
    </table>

Hi All,
         Am trying to upload a IPA file to TestFlight through PILOT, but its throwing the following error as follows,

The console shows the following,

```
[15:12:51]: [Transporter]: DBG-X: Apple's web service operation return value:

[15:12:51]: [Transporter]: DBG-X:   parameter Success = true

[15:12:51]: Transporter transfer failed.

[15:12:51]: 

[15:12:51]: 

[15:12:51]: Return status of iTunes Transporter was 1: 

[15:12:51]: Return status of iTunes Transporter was 1: 

/Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/build_manager.rb:25:in `upload': Error uploading ipa file, more information see above (RuntimeError)

from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/commands_generator.rb:48:in `block (2 levels) in run'

from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'

from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'

from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'

from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'

from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'

from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'

from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/commands_generator.rb:120:in `run'

from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/commands_generator.rb:17:in `start'

from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/bin/pilot:6:in `<top (required)>'

from /usr/bin/pilot:23:in `load'

from /usr/bin/pilot:23:in `<main>'
```

Could anyone please help on this??

Thanks

**Comment by mfurtak** [comment]
I'm going to close this issue due to a long period of inactivity. @parthitheindian - please feel free to continue the conversation and we can reopen as needed! :+1:
