### ISSUE TITLE
The fastlane deliver action fails to update long description metadata text

### ISSUE THREAD

**Issue by lukeleleh** [fastlane/fastlane#19130]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

TL;DR: The same metadata description text can be updated manually using the App Store Connect portal but fails using the fastlane deliver action. 

We used [the deliver action](https://docs.fastlane.tools/actions/deliver/) to update the metadata in the App Store Connect and got the following error: `An attribute value is too long. - App Description cannot be longer than 4000 characters.`.

I opened the description.txt file and the characters count was 3978. In the beginning, we thought it was related to some break lines we had at the end but someone pointed out that this can be related to Unicode code points and bytes. We checked the latest using [this tool](https://onlineunicodetools.com/count-unicode-characters) and we got different results if we count the number of:
- individual symbols in unicode text:  3978
- the number encoded bytes: 4334

We updated our description to test a new text having a lower count taking into account the number of encoded bytes and the deliver action succeeded.

However, If I paste manually the initial description that failed due to being too long in the App Store Connect portal, I don't reach the limit and there are 22 characters left to add. That's why I created this issue.

The error comes from the API but we're not sure if this is an App Store Connect API issue or a fastlane's one. I checked how the metadata was being uploaded [here](https://github.com/fastlane/fastlane/blob/16db9e0f2526772b9365e052a37b555e376cf7ea/deliver/lib/deliver/upload_metadata.rb) to see if it's an encoding problem but I'm not that familiar with Ruby.

<details><summary>Screenshot of the action error</summary>

![fastlane deliver description](https://user-images.githubusercontent.com/18327422/126620718-6629ce77-87a7-426d-9f9e-3b985ae7d1ad.png)

</details>

<details><summary>Useful description text with encoded bytes</summary>

```
Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.

Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan "de Finibus Bonorum et Malorum" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan "Lorem ipsum dolor sit amet" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.

1500'lerden beri kullanılmakta olan standard Lorem Ipsum metinleri ilgilenenler için yeniden üretilmiştir. Çiçero tarafından yazılan 1.10.32 ve 1.10.33 bölümleri de 1914 H. Rackham çevirisinden alınan İngilizce sürümleri eşliğinde özgün biçiminden yeniden üretilmiştir.

Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.

Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan "de Finibus Bonorum et Malorum" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan "Lorem ipsum dolor sit amet" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.

1500'lerden beri kullanılmakta olan standard Lorem Ipsum metinleri ilgilenenler için yeniden üretilmiştir. Çiçero tarafından yazılan 1.10.32 ve 1.10.33 bölümleri de 1914 H. Rackham çevirisinden alınan İngilizce sürümleri eşliğinde özgün biçiminden yeniden üretilmiştir.

Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.
```

</details>

##### Command executed

```
bundle exec fastlane deliver
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [17:47:08]: ----------------------------------------
[17:47:08]: --- Step: Verifying fastlane version ---
[17:47:08]: ----------------------------------------
[17:47:08]: Your fastlane version 2.187.0 matches the minimum requirement of 2.134.0  ✅
[17:47:08]: ------------------------------
[17:47:08]: --- Step: default_platform ---
[17:47:08]: ------------------------------
[17:47:08]: Driving the lane 'ios <lane>' 🚀
[17:47:08]: ---------------------------------------
[17:47:08]: --- Step: app_store_connect_api_key ---
[17:47:08]: ---------------------------------------
[17:47:08]: ---------------------
[17:47:08]: --- Step: deliver ---
[17:47:08]: ---------------------
[17:47:08]: Successfully loaded '<path>/fastlane/Deliverfile' 📄

+--------------------+--------------------------+
| Detected Values from './fastlane/Deliverfile' |
+--------------------+--------------------------+
| app_identifier     | <app_identifier>         |
| username           | <username>       			  |
+--------------------+--------------------------+

[17:47:08]: Creating authorization token for App Store Connect API

+-------------------------------------------------------------+--------------------------+
|                                deliver 2.187.0 Summary                                 |
+-------------------------------------------------------------+--------------------------+
| api_key                                                     | **********               |
| phased_release                                              | true                     |
| force                                                       | true                     |
| skip_screenshots                                            | true                     |
| skip_metadata                                               | false                    |
| skip_app_version_update                                     | false                    |
| skip_binary_upload                                          | true                     |
| submission_information.export_compliance_encryption_updated | false                    |
| submission_information.add_id_info_uses_idfa                | true                     |
| submission_information.add_id_info_serves_ads               | false                    |
| submission_information.add_id_info_tracks_install           | true                     |
| submission_information.add_id_info_tracks_action            | true                     |
| precheck_include_in_app_purchases                           | false                    |
| screenshots_path                                            | ./fastlane/screenshots   |
| metadata_path                                               | ./fastlane/metadata      |
| username                                                    | <username>               |
| app_identifier                                              | <app_identifier>         |
| platform                                                    | ios                      |
| edit_live                                                   | false                    |
| use_live_version                                            | false                    |
| overwrite_screenshots                                       | false                    |
| submit_for_review                                           | false                    |
| reject_if_possible                                          | false                    |
| reset_ratings                                               | false                    |
| run_precheck_before_submit                                  | true                     |
| precheck_default_rule_level                                 | warn                     |
| ignore_language_directory_validation                        | false                    |
+-------------------------------------------------------------+--------------------------+

[17:47:14]: Loading './fastlane/metadata/fr-FR/description.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-FR/keywords.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-FR/release_notes.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-FR/support_url.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-FR/marketing_url.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-FR/promotional_text.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-FR/name.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-FR/subtitle.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-FR/privacy_url.txt'...
[17:47:14]: Loading './fastlane/metadata/es-ES/description.txt'...
[17:47:14]: Loading './fastlane/metadata/es-ES/keywords.txt'...
[17:47:14]: Loading './fastlane/metadata/es-ES/release_notes.txt'...
[17:47:14]: Loading './fastlane/metadata/es-ES/support_url.txt'...
[17:47:14]: Loading './fastlane/metadata/es-ES/marketing_url.txt'...
[17:47:14]: Loading './fastlane/metadata/es-ES/promotional_text.txt'...
[17:47:14]: Loading './fastlane/metadata/es-ES/name.txt'...
[17:47:14]: Loading './fastlane/metadata/es-ES/subtitle.txt'...
[17:47:14]: Loading './fastlane/metadata/es-ES/privacy_url.txt'...
[17:47:14]: Loading './fastlane/metadata/no/description.txt'...
[17:47:14]: Loading './fastlane/metadata/no/keywords.txt'...
[17:47:14]: Loading './fastlane/metadata/no/release_notes.txt'...
[17:47:14]: Loading './fastlane/metadata/no/support_url.txt'...
[17:47:14]: Loading './fastlane/metadata/no/marketing_url.txt'...
[17:47:14]: Loading './fastlane/metadata/no/promotional_text.txt'...
[17:47:14]: Loading './fastlane/metadata/no/name.txt'...
[17:47:14]: Loading './fastlane/metadata/no/subtitle.txt'...
[17:47:14]: Loading './fastlane/metadata/no/privacy_url.txt'...
[17:47:14]: Loading './fastlane/metadata/es-MX/description.txt'...
[17:47:14]: Loading './fastlane/metadata/es-MX/keywords.txt'...
[17:47:14]: Loading './fastlane/metadata/es-MX/release_notes.txt'...
[17:47:14]: Loading './fastlane/metadata/es-MX/support_url.txt'...
[17:47:14]: Loading './fastlane/metadata/es-MX/marketing_url.txt'...
[17:47:14]: Loading './fastlane/metadata/es-MX/promotional_text.txt'...
[17:47:14]: Loading './fastlane/metadata/es-MX/name.txt'...
[17:47:14]: Loading './fastlane/metadata/es-MX/subtitle.txt'...
[17:47:14]: Loading './fastlane/metadata/es-MX/privacy_url.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-CA/description.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-CA/keywords.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-CA/release_notes.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-CA/support_url.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-CA/marketing_url.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-CA/promotional_text.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-CA/name.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-CA/subtitle.txt'...
[17:47:14]: Loading './fastlane/metadata/fr-CA/privacy_url.txt'...
[17:47:14]: Loading './fastlane/metadata/en-CA/description.txt'...
[17:47:14]: Loading './fastlane/metadata/en-CA/keywords.txt'...
[17:47:14]: Loading './fastlane/metadata/en-CA/release_notes.txt'...
[17:47:14]: Loading './fastlane/metadata/en-CA/support_url.txt'...
[17:47:14]: Loading './fastlane/metadata/en-CA/marketing_url.txt'...
[17:47:14]: Loading './fastlane/metadata/en-CA/promotional_text.txt'...
[17:47:14]: Loading './fastlane/metadata/en-CA/name.txt'...
[17:47:14]: Loading './fastlane/metadata/en-CA/subtitle.txt'...
[17:47:14]: Loading './fastlane/metadata/en-CA/privacy_url.txt'...
[17:47:14]: Loading './fastlane/metadata/en-US/description.txt'...
[17:47:14]: Loading './fastlane/metadata/en-US/keywords.txt'...
[17:47:14]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[17:47:14]: Loading './fastlane/metadata/en-US/support_url.txt'...
[17:47:14]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[17:47:14]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[17:47:14]: Loading './fastlane/metadata/en-US/name.txt'...
[17:47:14]: Loading './fastlane/metadata/en-US/subtitle.txt'...
[17:47:14]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[17:47:14]: Loading './fastlane/metadata/tr/description.txt'...
[17:47:14]: Loading './fastlane/metadata/tr/keywords.txt'...
[17:47:14]: Loading './fastlane/metadata/tr/release_notes.txt'...
[17:47:14]: Loading './fastlane/metadata/tr/support_url.txt'...
[17:47:14]: Loading './fastlane/metadata/tr/marketing_url.txt'...
[17:47:14]: Loading './fastlane/metadata/tr/promotional_text.txt'...
[17:47:14]: Loading './fastlane/metadata/tr/name.txt'...
[17:47:14]: Loading './fastlane/metadata/tr/subtitle.txt'...
[17:47:14]: Loading './fastlane/metadata/tr/privacy_url.txt'...
[17:47:14]: Loading './fastlane/metadata/copyright.txt'...
[17:47:14]: Loading './fastlane/metadata/primary_category.txt'...
[17:47:14]: Loading './fastlane/metadata/secondary_category.txt'...
[17:47:14]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[17:47:14]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[17:47:14]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[17:47:14]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[17:47:14]: Loading './fastlane/metadata/review_information/first_name.txt'...
[17:47:14]: Loading './fastlane/metadata/review_information/last_name.txt'...
[17:47:14]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[17:47:14]: Loading './fastlane/metadata/review_information/email_address.txt'...
[17:47:14]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[17:47:14]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[17:47:14]: Loading './fastlane/metadata/review_information/notes.txt'...
[17:47:21]: Will begin uploading metadata for '<version>' on App Store Connect
[17:47:21]: Release type will not be set because neither `automatic_release` nor `auto_release_date` were provided. Please explicitly set one of these options if you need a release type set
[17:47:21]: Uploading metadata to App Store Connect for version
[17:47:25]: Uploading metadata to App Store Connect for localized version 'es-MX'
[17:47:25]: Uploading metadata to App Store Connect for localized version 'fr-CA'
[17:47:25]: Uploading metadata to App Store Connect for localized version 'en-US'
[17:47:25]: Uploading metadata to App Store Connect for localized version 'es-ES'
[17:47:25]: Uploading metadata to App Store Connect for localized version 'en-CA'
[17:47:25]: Uploading metadata to App Store Connect for localized version 'no'
[17:47:25]: Uploading metadata to App Store Connect for localized version 'tr'
[17:47:25]: Uploading metadata to App Store Connect for localized version 'fr-FR'
#<Thread:0x00007f8d23ee8fb0@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/queue_worker.rb:37 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
	5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.187.0/deliver/lib/deliver/upload_metadata.rb:207:in `block in upload'
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:57:in `update'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `patch_app_store_version_localization'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:805:in `patch_app_store_version_localization'
	1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': An attribute value is too long. - App Description cannot be longer than 4000 characters. - /data/attributes/description (Spaceship::UnexpectedResponse)
[17:47:26]: --------------------------
[17:47:26]: --- Step: notification ---
[17:47:26]: --------------------------
[17:47:26]: exception: An attribute value is too long. - App Description cannot be longer than 4000 characters. - /data/attributes/description
+------------------+------------------------+
|               Lane Context                |
+------------------+------------------------+
| DEFAULT_PLATFORM | ios                    |
| PLATFORM_NAME    | ios                    |
| LANE_NAME        | ios <lane>             |
+------------------+------------------------+
[17:47:26]: An attribute value is too long. - App Description cannot be longer than 4000 characters. - /data/attributes/description

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | app_store_connect_api_key  | 0           |
| 💥   | deliver                    | 17          |
| 5    | notification               | 0           |
+------+----------------------------+-------------+
 </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

Note: I cannot add here some information like the Fastfile, sorry 🙏

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |
| Swift Version               | 5.3.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status      |
| ----------------------------------------- | ------- | ------------------ |
| fastlane-plugin-badge                     | 1.4.0   | 🚫 Update available |
| fastlane-plugin-firebase_app_distribution | 0.2.5   | 🚫 Update available |

*generated on:* **2021-07-22**
</details>

**Comment by lucgrabowski** [comment]
Hi, the error that you see is API response as you say, the description is too long for Appstore. I see that you successfully set the same description manually on AppstoreConnect. Could you download metadata and diff the version downloaded with the one that you try to upload?
'fastlane deliver download_metadata'

**Comment by lukeleleh** [comment]
Hey, sorry for the late reply. We had some issues running the `download_metadata` subaction using a custom lane we created for getting the API key and through sh, execute the subaction. Something like this:

```ruby
desc "Download App Store Connect metadata"
lane :download_app_store_metadata do
  api_key = app_store_connect_api_key(
    key_id: apple_auth_key_id,
    issuer_id: apple_auth_issuer_id,
    key_filepath: apple_auth_key_filepath
  )

  sh "bundle exec fastlane deliver download_metadata --api_key '#{api_key}'"
end
```

The issue was related to the `api_key` parameter value format and in the end, we succeed in running the subaction directly without a lane, using the `api_key_path` parameter instead and providing the API Key JSON file path with `is_key_content_base64` parameter set to `true`. Something like this (if anyone encounters the same problem):

```ruby
bundle exec fastlane deliver download_metadata --api-key-path "fastlane/json_api_key.json"
```

Regarding your question, we diffed both versions and there's no difference between them. Also, we used [the tool](https://onlineunicodetools.com/count-unicode-characters) I shared in the issue description checking the characters count in both (taking into account encoded bytes) and the result is also the same.

**Comment by lukeleleh** [comment]
Just to let you know, we filled a radar to inform Apple of this issue (FB9460861)

**Comment by akaralar** [comment]
@lucgrabowski Apple replied back asking us the exact request that we made.. Is there a way to get a cURL version of the request fastlane is making, so that we can attach that?

**Comment by lucgrabowski** [comment]
@akaralar You could see requests in logs. To look for the log file you can execute `fastlane run spacehip_logs`, it will show you where logs are located.
If you want to get a complete cURL of the request, the best would be to setup Charles as a proxy, run fastlane commands, look for the request in Charles and copy cURL request.
https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Debugging.md
https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md

**Comment by BobDG** [comment]
I also had this issue lately and I finally created my own check for all the metadata files, to see if anything was too long. Using this I finally found the culprit. I used the fastlane run spacehip_logs and I did see in there that there's an ID that you can use to actually see the one that's causing the issue. It would however be much better if the error in terminal actually shows the language where it goes wrong, now you have to search/check each language yourself (or create a script yourself to check these all).
