### ISSUE TITLE
artifactory: API path missing!

### ISSUE THREAD

**Issue by mieliespoor** [fastlane/fastlane#19141]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When calling the artifcatory action, the expectation is that the file is uploaded to artifactory. However, the upload happens and I can view the file in artifactory, but fastlane then fails with an error `API path missing`. 

This would seem because the action is setting lane context out put where it uses a property not set.
`Actions.lane_context[SharedValues::ARTIFACTORY_DOWNLOAD_URL] = upload.uri`

When I copy the code from the action locally and execute it without trying to access the uri, I get no errors back from the action.

##### Command executed

```
artifactory(
    username: "#{options[:username]}",
    password: "#{options[:password]}",
    endpoint: "https://artifactory.xxxx.net/artifactory/",
    file: "#{options[:output_directory]}/#{filename}",
    repo: "smb-mobile",
    repo_path: "#{repo_path}"
  )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/Users/jkbuilder/.gems/gems/artifactory-3.0.15/lib/artifactory/resources/artifact.rb:374:in `block in <class:Artifact>': [!] API path missing! (RuntimeError)
from /Users/jkbuilder/.gems/gems/artifactory-3.0.15/lib/artifactory/resources/base.rb:58:in `block in attribute'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/artifactory.rb:31:in `run'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
from libraryFile:147:in `block in parsing_binding'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane.rb:33:in `call'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
from Fastfile:193:in `block (2 levels) in parsing_binding'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane.rb:33:in `call'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
from /Users/jkbuilder/.gems/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
from /Users/jkbuilder/.gems/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
from /Users/jkbuilder/.gems/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
from /Users/jkbuilder/.gems/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
from /Users/jkbuilder/.gems/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
from /usr/local/bin/fastlane:23:in `load'
from /usr/local/bin/fastlane:23:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by mieliespoor** [comment]
This is still an issue

**Comment by mieliespoor** [comment]
still an issue

**Comment by mieliespoor** [comment]
still an issue
