### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by xinatcg** [fastlane/fastlane#19199]
Updating certs resolved it.

_Originally posted by @garyhooper in https://github.com/fastlane/fastlane/issues/12344#issuecomment-382953526_

basic log

```
fastlane spaceauth
[✔] 🚀 
[17:38:29]: fastlane detected a Gemfile in the current directory
[17:38:29]: However, it seems like you didn't use `bundle exec`
[17:38:29]: To launch fastlane faster, please use
[17:38:29]: 
[17:38:29]: $ bundle exec fastlane spaceauth
[17:38:29]: 
[17:38:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Logging into to App Store Connect (xin@xxx)...
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
Could not login to App Store Connect
Please check your credentials and try again.
This could be an issue with App Store Connect,
Please try unsetting the FASTLANE_SESSION environment variable by calling 'unset FASTLANE_SESSION'
(if it is set) and re-run `fastlane spaceauth`

Exception type: Spaceship::AppleTimeoutError

Looking for related GitHub issues on fastlane/fastlane...


[!] The request could not be completed because:
	Could not receive latest API key from App Store Connect, this might be a server issue.
```

verbose log

```
ERROR [2021-08-03 18:07:56.70]: Error finding relevant GitHub issues: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
/usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:590:in `rescue in itc_service_key': \e[31m[!] The request could not be completed because: (Spaceship::AppleTimeoutError)
	Could not receive latest API key from App Store Connect, this might be a server issue.\e[0m
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:569:in `itc_service_key'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:497:in `block in send_shared_login_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:890:in `extract_key_from_block'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:840:in `log_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:731:in `request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:492:in `send_shared_login_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/tunes_client.rb:130:in `send_login_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:824:in `do_login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:404:in `login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:366:in `login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/spaceauth_runner.rb:20:in `run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/commands_generator.rb:46:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/commands_generator.rb:52:in `run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/commands_generator.rb:15:in `start'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/bin/fastlane:23:in `load'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/bin/fastlane:23:in `<main>'
/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (Faraday::SSLError)
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:1038:in `connect'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:129:in `request_with_wrapped_block'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-1.6.0/lib/faraday/adapter.rb:50:in `connection'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/stats_middleware.rb:45:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/helper/rels_middleware.rb:17:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-cookie_jar-0.0.7/lib/faraday/cookie_jar.rb:24:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-1.6.0/lib/faraday/rack_builder.rb:154:in `build_response'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-1.6.0/lib/faraday/connection.rb:495:in `run_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-1.6.0/lib/faraday/connection.rb:199:in `get'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:899:in `block in send_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:657:in `with_retry'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:898:in `send_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:742:in `request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:579:in `itc_service_key'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:497:in `block in send_shared_login_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:890:in `extract_key_from_block'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:840:in `log_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:731:in `request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:492:in `send_shared_login_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/tunes_client.rb:130:in `send_login_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:824:in `do_login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:404:in `login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:366:in `login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/spaceauth_runner.rb:20:in `run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/commands_generator.rb:46:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/commands_generator.rb:52:in `run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/commands_generator.rb:15:in `start'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/bin/fastlane:23:in `load'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/bin/fastlane:23:in `<main>'
/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:1038:in `connect'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:129:in `request_with_wrapped_block'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-1.6.0/lib/faraday/adapter.rb:50:in `connection'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/stats_middleware.rb:45:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/helper/rels_middleware.rb:17:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-cookie_jar-0.0.7/lib/faraday/cookie_jar.rb:24:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-1.6.0/lib/faraday/rack_builder.rb:154:in `build_response'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-1.6.0/lib/faraday/connection.rb:495:in `run_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/faraday-1.6.0/lib/faraday/connection.rb:199:in `get'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:899:in `block in send_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:657:in `with_retry'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:898:in `send_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:742:in `request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:579:in `itc_service_key'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:497:in `block in send_shared_login_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:890:in `extract_key_from_block'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:840:in `log_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:731:in `request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:492:in `send_shared_login_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/tunes_client.rb:130:in `send_login_request'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:824:in `do_login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:404:in `login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:366:in `login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/spaceauth_runner.rb:20:in `run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/commands_generator.rb:46:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/commands_generator.rb:52:in `run'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/spaceship/lib/spaceship/commands_generator.rb:15:in `start'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/gems/fastlane-2.190.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/bin/fastlane:23:in `load'
	from /usr/local/Cellar/fastlane/2.190.0/libexec/bin/fastlane:23:in `<main>'
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.4                                                    |
| Ruby                        | 3.0.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.190.0/libexec/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5.1                                                  |
| Swift Version               | 5.4.2                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # increment_build_number(xcodeproj: "Unity-iPhone.xcodeproj")
    # automatic_code_signing(
    #   path:"Unity-iPhone.xcodeproj",
    #   use_automatic_signing:true
    # )
    build_app(xcargs: "-allowProvisioningUpdates", workspace: "Unity-iPhone.xcworkspace", scheme: "Unity-iPhone")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com") # The bundle identifier of your app
apple_id("xin@.com") # Your Apple email address

itc_team_id("") # App Store Connect Team ID
team_id("") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.190.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.20.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.6.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.482.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-sdk-core                    | 3.119.0      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.98.0       |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| optparse                        | 0.1.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2021-08-03**
</details>

**Comment by xinatcg** [comment]
is it related to ruby on the mac?
