### ISSUE TITLE
Getting `Server error got 500` despite successful testflight publish

### ISSUE THREAD

**Issue by CatalinVoss** [fastlane/fastlane#19217]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Recently, we started getting inconsistent `Server error got 500` errors at the very end of the `upload_to_testflight` step despite the fact that the testflight push successfully completed and the app was published.  Interestingly, this does not happen for us on another app despite basically the same exact Fastfile, fastlane version, etc. At first, I thought it was related to the `ITSAppUsesNonExemptEncryption` issue from #13452, but that's not it. The error also changes from `Server error got 500` to an Apple authentication issue occasionally.

##### Command executed

```
upload_to_testflight(
  api_key_path: API_KEY_PATH,
  skip_waiting_for_build_processing: false,
  beta_app_feedback_email: "...",
  changelog: commit[:message],
  groups: ["..."],
  distribute_external: true,
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
2021-08-06T22:04:15.1944150Z INFO [2021-08-06 15:04:15.19]: [32m-----------------------------------------------------[0m
2021-08-06T22:04:15.1946570Z INFO [2021-08-06 15:04:15.19]: [32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.[0m
2021-08-06T22:04:15.1948730Z INFO [2021-08-06 15:04:15.19]: [32m-----------------------------------------------------[0m
2021-08-06T22:04:15.1982990Z INFO [2021-08-06 15:04:15.19]: [32mSuccessfully uploaded the new binary to App Store Connect[0m
2021-08-06T22:04:15.1986090Z INFO [2021-08-06 15:04:15.19]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
2021-08-06T22:04:15.1989690Z INFO [2021-08-06 15:04:15.19]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
2021-08-06T22:04:15.1992040Z DEBUG [2021-08-06 15:04:15.19]: App Platform (ios)
2021-08-06T22:04:15.2727100Z INFO [2021-08-06 15:04:15.27]: Waiting for processing on... app_id: 1578806524, app_version: 0.0.7, build_version: 11, platform: IOS
2021-08-06T22:04:15.4778340Z WARN [2021-08-06 15:04:15.47]: [33mRead more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997[0m
2021-08-06T22:04:15.4782310Z INFO [2021-08-06 15:04:15.47]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
2021-08-06T22:04:45.6668150Z INFO [2021-08-06 15:04:45.66]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
2021-08-06T22:05:15.8317190Z INFO [2021-08-06 15:05:15.83]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
2021-08-06T22:05:48.8236550Z INFO [2021-08-06 15:05:48.82]: Waiting for App Store Connect to finish processing the new build (0.0.7 - 11) for IOS
2021-08-06T22:06:19.5459960Z INFO [2021-08-06 15:06:19.54]: Waiting for App Store Connect to finish processing the new build (0.0.7 - 11) for IOS
2021-08-06T22:06:49.9040310Z INFO [2021-08-06 15:06:49.90]: Waiting for App Store Connect to finish processing the new build (0.0.7 - 11) for IOS
2021-08-06T22:07:20.2701010Z INFO [2021-08-06 15:07:20.26]: Waiting for App Store Connect to finish processing the new build (0.0.7 - 11) for IOS
2021-08-06T22:07:51.1647260Z INFO [2021-08-06 15:07:51.16]: [32mSuccessfully finished processing the build 0.0.7 - 11 for IOS[0m
2021-08-06T22:07:51.3586500Z INFO [2021-08-06 15:07:51.35]: [32mSuccessfully set the beta_app_feedback_email and/or beta_app_description[0m
2021-08-06T22:07:51.4987020Z INFO [2021-08-06 15:07:51.49]: [32mSuccessfully set the changelog for build[0m
2021-08-06T22:07:51.4991820Z WARN [2021-08-06 15:07:51.49]: [33mUsing App Store Connect's default for notifying external testers (which is true) - set `notify_external_testers` for full control[0m
2021-08-06T22:07:51.4994810Z INFO [2021-08-06 15:07:51.49]: Distributing new build to testers: 0.0.7 - 11
2021-08-06T22:07:51.6805140Z WARN [2021-08-06 15:07:51.67]: [33mExport compliance has been set to 'false'. Need to wait for build to finishing processing again...[0m
2021-08-06T22:07:51.6809480Z WARN [2021-08-06 15:07:51.68]: [33mSet 'ITSAppUsesNonExemptEncryption' in the 'Info.plist' to skip this step and speed up the submission[0m
2021-08-06T22:07:52.5219380Z Timeout received! Retrying after 3 seconds (remaining: 5)...
2021-08-06T22:07:52.7156470Z Timeout received! Retrying after 3 seconds (remaining: 4)...
2021-08-06T22:07:52.9206320Z Timeout received! Retrying after 3 seconds (remaining: 3)...
2021-08-06T22:07:53.1182550Z Timeout received! Retrying after 3 seconds (remaining: 2)...
2021-08-06T22:07:53.3376900Z Timeout received! Retrying after 3 seconds (remaining: 1)...
2021-08-06T22:07:53.3393410Z WARN [2021-08-06 15:07:53.33]: [33m[33mLane Context:[0m
2021-08-06T22:07:53.3404190Z INFO [2021-08-06 15:07:53.33]: ***:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"11", :SIGH_PROFILE_TYPE=>"app-store", :MATCH_PROVISIONING_PROFILE_MAPPING=>***"com.[...].assessment"=>"match AppStore com.[...].assessment 1627624700"***, :IPA_OUTPUT_PATH=>"/Users/[...]/actions-runner/_work/[...]/[...]/[...]/ios/[...].ipa", :XCODEBUILD_ARCHIVE=>"/Users/[...]/Library/Developer/Xcode/Archives/2021-08-06/[...] 2021-08-06 14.43.21.xcarchive", :DSYM_OUTPUT_PATH=>"/Users/[...]/actions-runner/_work/[...]/[...]/[...]/ios/[...].app.dSYM.zip"***
2021-08-06T22:07:53.3410840Z ERROR [2021-08-06 15:07:53.33]: [31mServer error got 500[0m
2021-08-06T22:07:53.3939730Z INFO [2021-08-06 15:07:53.39]: [32mSuccessfully generated documentation at path '/Users/[...]/actions-runner/_work/[...]/[...]/[...]/ios/fastlane/README.md'[0m
2021-08-06T22:07:53.9550810Z 
2021-08-06T22:07:53.9583510Z +------+------------------------------------------+-------------+
2021-08-06T22:07:53.9586790Z |                       [32mfastlane summary[0m                        |
2021-08-06T22:07:53.9589560Z +------+------------------------------------------+-------------+
2021-08-06T22:07:53.9591440Z | Step | Action                                   | Time (in s) |
2021-08-06T22:07:53.9594010Z +------+------------------------------------------+-------------+
2021-08-06T22:07:53.9604040Z | 1    | default_platform                         | 0           |
2021-08-06T22:07:53.9605480Z | 2    | last_git_commit                          | 2           |
2021-08-06T22:07:53.9606500Z | 3    | increment_build_number                   | 14          |
2021-08-06T22:07:53.9607600Z | 4    | Switch to ios configure_codesigning lane | 0           |
2021-08-06T22:07:53.9608660Z | 5    | sync_code_signing                        | 5           |
2021-08-06T22:07:53.9609690Z | 6    | update_project_provisioning              | 0           |
2021-08-06T22:07:53.9610700Z | 7    | build_app                                | 1232        |
2021-08-06T22:07:53.9612420Z | 💥   | [31mupload_to_testflight[0m                     | 293         |
2021-08-06T22:07:53.9613990Z +------+------------------------------------------+-------------+
2021-08-06T22:07:53.9614640Z 
2021-08-06T22:07:53.9616070Z ERROR [2021-08-06 15:07:53.95]: [31mfastlane finished with errors[0m
2021-08-06T22:07:54.0282230Z 
2021-08-06T22:07:54.0284930Z Looking for related GitHub issues on fastlane/fastlane...
2021-08-06T22:07:54.0287750Z Search query: The request could not be completed because:
2021-08-06T22:07:54.0289850Z    Server error got 500
2021-08-06T22:07:54.0290650Z 
2021-08-06T22:07:54.0292920Z URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Server%20error%20got%20500+repo:fastlane/fastlane
2021-08-06T22:07:55.2274320Z ➡️  [33mbeta_pa path is relative to the fastlane directory, not the project directory[0m
2021-08-06T22:07:55.2277790Z     https://github.com/fastlane/fastlane/issues/500 [[32mclosed[0m] 4 💬
2021-08-06T22:07:55.2279390Z     22 Sep 2016
2021-08-06T22:07:55.2280040Z 
2021-08-06T22:07:55.2282350Z ➡️  [33mServer error got 500 when submitting to TestFlight[0m
2021-08-06T22:07:55.2284180Z     https://github.com/fastlane/fastlane/issues/19148 [[32mclosed[0m] 2 💬
2021-08-06T22:07:55.2289050Z bundler: failed to load command: fastlane (/Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/bin/fastlane)
2021-08-06T22:07:55.2292220Z Spaceship::InternalServerError: [31m[!] The request could not be completed because:
2021-08-06T22:07:55.2293820Z    Server error got 500[0m
2021-08-06T22:07:55.2295940Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/api_client.rb:191:in `handle_response'
2021-08-06T22:07:55.2298840Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
2021-08-06T22:07:55.2301870Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:115:in `post_beta_app_review_submissions'
2021-08-06T22:07:55.2304320Z   /usr/local/Cellar/ruby@2.7/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `post_beta_app_review_submissions'
2021-08-06T22:07:55.2306830Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/models/build.rb:180:in `post_beta_app_review_submission'
2021-08-06T22:07:55.2309680Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/pilot/lib/pilot/build_manager.rb:404:in `distribute_build'
2021-08-06T22:07:55.2312310Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/pilot/lib/pilot/build_manager.rb:179:in `distribute'
2021-08-06T22:07:55.2314890Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/pilot/lib/pilot/build_manager.rb:62:in `upload'
2021-08-06T22:07:55.2317570Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:32:in `run'
2021-08-06T22:07:55.2320380Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
2021-08-06T22:07:55.2323180Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
2021-08-06T22:07:55.2325950Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
2021-08-06T22:07:55.2328560Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
2021-08-06T22:07:55.2331170Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
2021-08-06T22:07:55.2333840Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
2021-08-06T22:07:55.2336510Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2021-08-06T22:07:55.2338370Z   Fastfile:45:in `block (2 levels) in parsing_binding'
2021-08-06T22:07:55.2340370Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/lane.rb:33:in `call'
2021-08-06T22:07:55.2342970Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
2021-08-06T22:07:55.2346070Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
2021-08-06T22:07:55.2348670Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
2021-08-06T22:07:55.2351300Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
2021-08-06T22:07:55.2353980Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
2021-08-06T22:07:55.2356750Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
2021-08-06T22:07:55.2359370Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2021-08-06T22:07:55.2361820Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2021-08-06T22:07:55.2370430Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2021-08-06T22:07:55.2373650Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2021-08-06T22:07:55.2376290Z   /Users/[...]/actions-runner/_work/[...]/[...]/[...]/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2021-08-06T22:07:55.2377530Z     a week ago
2021-08-06T22:07:55.2377920Z 
</pre>
</details>

### Environment

<details>
  <pre>Mac Mini CI server on Big Sur, fastlane `2.172.0`</pre>
</details>

**Comment by lucgrabowski** [comment]
Hi @CatalinVoss , could you update fastlane to the newest version and confirm if the issue still occurs?

**Comment by CatalinVoss** [comment]
@lucgrabowski yep, confirmed that the issue occurs with 2.191.0

**Comment by lucgrabowski** [comment]
Could you execute `fastlane run spaceship_logs` (which will show you spaceship logfile's path), open logfile and see if you can find the answer why server returns 500?

**Comment by CatalinVoss** [comment]
@lucgrabowski It seems to have something to do with Apple's localization API?

```
2021-08-09T23:01:12.6154900Z INFO  [23:01:05]: >> GET betaAppLocalizations: [undefined body] 
2021-08-09T23:01:12.6157320Z DEBUG [23:01:06]: << GET betaAppLocalizations: 200 ***"data"=>[], "links"=>***"self"=>"https://api.appstoreconnect.apple.com/v1/betaAppLocalizations?filter%5Bapp%5D=1578806524"***, "meta"=>***"paging"=>***"total"=>0, "limit"=>50***
2021-08-09T23:01:12.6159250Z INFO  [23:01:06]: >> GET betaBuildLocalizations: [undefined body] 
2021-08-09T23:01:12.6162520Z DEBUG [23:01:06]: << GET betaBuildLocalizations: 200 ***"data"=>[], "links"=>***"self"=>"https://api.appstoreconnect.apple.com/v1/betaBuildLocalizations?filter%5Bbuild%5D=05c785e8-285b-448b-9143-1c51b1e9c2f0"***, "meta"=>***"paging"=>***"total"=>0, "limit"=>50***
2021-08-09T23:01:12.6166000Z INFO  [23:01:06]: >> POST betaAppReviewSubmissions: ***"data":***"type":"betaAppReviewSubmissions","relationships":***"build":***"data":***"type":"builds","id":"05c785e8-285b-448b-9143-1c51b1e9c2f0"*** 
2021-08-09T23:01:12.6169110Z DEBUG [23:01:06]: << POST betaAppReviewSubmissions: 500 ***"errors"=>[***"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."***]***
2021-08-09T23:01:12.6172610Z INFO  [23:01:06]: >> POST betaAppReviewSubmissions: ***"data":***"type":"betaAppReviewSubmissions","relationships":***"build":***"data":***"type":"builds","id":"05c785e8-285b-448b-9143-1c51b1e9c2f0"*** 
2021-08-09T23:01:12.6175670Z DEBUG [23:01:07]: << POST betaAppReviewSubmissions: 500 ***"errors"=>[***"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."***]***
2021-08-09T23:01:12.6179790Z INFO  [23:01:07]: >> POST betaAppReviewSubmissions: ***"data":***"type":"betaAppReviewSubmissions","relationships":***"build":***"data":***"type":"builds","id":"05c785e8-285b-448b-9143-1c51b1e9c2f0"*** 
2021-08-09T23:01:12.6182950Z DEBUG [23:01:07]: << POST betaAppReviewSubmissions: 500 ***"errors"=>[***"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."***]***
2021-08-09T23:01:12.6186540Z INFO  [23:01:07]: >> POST betaAppReviewSubmissions: ***"data":***"type":"betaAppReviewSubmissions","relationships":***"build":***"data":***"type":"builds","id":"05c785e8-285b-448b-9143-1c51b1e9c2f0"*** 
2021-08-09T23:01:12.6190530Z DEBUG [23:01:07]: << POST betaAppReviewSubmissions: 500 ***"errors"=>[***"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."***]***
2021-08-09T23:01:12.6210370Z INFO  [23:01:07]: >> POST betaAppReviewSubmissions: ***"data":***"type":"betaAppReviewSubmissions","relationships":***"build":***"data":***"type":"builds","id":"05c785e8-285b-448b-9143-1c51b1e9c2f0"*** 
2021-08-09T23:01:12.6213500Z DEBUG [23:01:07]: << POST betaAppReviewSubmissions: 500 ***"errors"=>[***"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."***]***
2021-08-09T23:01:12.6215050Z 
2021-08-09T23:01:12.6216390Z [23:01:12]: [32mResult: ["/tmp/spaceship1628549809_8787_5000.log"][0m
```

**Comment by CatalinVoss** [comment]
@lucgrabowski Any indication what this might be or what localization settings could be involved that might affect this?

**Comment by lucgrabowski** [comment]
As the error is on the server side, the only thing that comes to my mind is reporting the issue on https://developer.apple.com/bug-reporting/
If there is a need for more data on the request, you could setup Charles as a proxy, run fastlane commands, look for the request in Charles and copy cURL request.
https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Debugging.md
https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md

**Comment by George-823** [comment]
A really good post, very thankful and hopeful that you will write many more posts like this one.

[DinarGuru](https://apps.apple.com/us/app/dinar-guru-top-dinar-recaps/id1581089419)

**Comment by smaljaar** [comment]
I ran into a similar 500 error when running `create_app_online`. I look in the spaceship logs and found:
```
INFO  [10:39:25]: >> GET users: [undefined body] 
DEBUG [10:39:27]: << GET users: 500 {"errors"=>[{"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."}]}
```
In `create_app_online` I was sending the property `itc_users: []`. Since that was the only clue in the error logs I removed it (it's not really needed anyway), and this fixed the issue. This was not giving a 500 error last week.

**Comment by Unknoob** [comment]
We also ran into 500 errors when uploading the app to external testers(`distribute_external: true` in fastlane), in our case it was because we were distributing a newly created app and the Test Information fields in Appstore Connect were empty.
