### ISSUE TITLE
Match import with storage-mode set to s3 still asks for git_url

### ISSUE THREAD

**Issue by xraymemory** [fastlane/fastlane#19230]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using fastlane latest version 2.191.0 on MacOS Big Sur 11.4, importing new certs fails if using an AWS S3 backend as the interactive prompt still asks for a `git_url`. If I give this input an S3 URI, it says _"Looks like you still define a `git_url` somewhere, even though you use S3 Storage. You can remove the `git_url`from your Matchfile and Fastfile"_ but this is not the case for my repo (as a quick grep shows). It eventually fails with 
```
/usr/local/Cellar/fastlane/2.191.0/libexec/gems/aws-sdk-s3-1.98.0/lib/aws-sdk-s3/bucket.rb:885:in `extract_name': \e[31m[!] missing required option :name\e[0m (ArgumentError)
```

##### Command executed
`fastlane match import --storage-mode=s3`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> fastlane match import --storage-mode=s3 
[⠋] 🚀 Ignoring digest-crc-0.6.4 because its extensions are not built. Try: gem pristine digest-crc --version 0.6.4
Ignoring unf_ext-0.0.7.7 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.7
[✔] 🚀 
[12:10:35]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:10:36]: Certificate (.cer) path:
mycert.cer
[12:10:38]: Private key (.p12) path:
mykey.p12
[12:10:41]: Provisioning profile (.mobileprovision or .provisionprofile) path or leave empty to skip
this file:
profile.mobileprovision
[12:10:45]: To not be asked about this value, you can specify it using 'git_url'
[12:10:45]: URL to the git repo containing all the certificates: s3://my-cert-bucket
[12:10:52]: Looks like you still define a `git_url` somewhere, even though
[12:10:52]: you use S3 Storage. You can remove the `git_url`
[12:10:52]: from your Matchfile and Fastfile
[12:35:05]: URL to the git repo containing all the certificates: 

Looking for related GitHub issues on fastlane/fastlane...

➡️  App screenshot missing (APP_IPAD_PRO_3GEN_129)
    https://github.com/fastlane/fastlane/issues/16975 [open] 6 💬
    6 weeks ago

➡️  Promoting non-latest alpha track version to production fails on Google Play Store
    https://github.com/fastlane/fastlane/issues/18497 [open] 4 💬
    2 weeks ago

➡️  Pilot: Fails because url is incorrect format.
    https://github.com/fastlane/fastlane/issues/18648 [open] 5 💬
    4 days ago

and 635 more at: https://github.com/fastlane/fastlane/search?q=missing%20required%20option%20%3Aname&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/Cellar/fastlane/2.191.0/libexec/gems/aws-sdk-s3-1.98.0/lib/aws-sdk-s3/bucket.rb:885:in `extract_name': \e[31m[!] missing required option :name\e[0m (ArgumentError)
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/aws-sdk-s3-1.98.0/lib/aws-sdk-s3/bucket.rb:24:in `initialize'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/aws-sdk-s3-1.98.0/lib/aws-sdk-s3/customizations/bucket.rb:14:in `call'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/aws-sdk-s3-1.98.0/lib/aws-sdk-s3/customizations/bucket.rb:14:in `block in <class:Bucket>'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:49:in `new'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:49:in `find_bucket!'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/storage/s3_storage.rb:104:in `download'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/importer.rb:46:in `import_cert'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:147:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:188:in `run'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:26:in `start'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/bin/fastlane:23:in `load'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/bin/fastlane:23:in `<main>'
/usr/local/Cellar/fastlane/2.191.0/libexec/gems/aws-sdk-s3-1.98.0/lib/aws-sdk-s3/bucket.rb:885:in `extract_name': missing required option :name (ArgumentError)
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/aws-sdk-s3-1.98.0/lib/aws-sdk-s3/bucket.rb:24:in `initialize'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/aws-sdk-s3-1.98.0/lib/aws-sdk-s3/customizations/bucket.rb:14:in `call'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/aws-sdk-s3-1.98.0/lib/aws-sdk-s3/customizations/bucket.rb:14:in `block in <class:Bucket>'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:49:in `new'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:49:in `find_bucket!'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/storage/s3_storage.rb:104:in `download'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/importer.rb:46:in `import_cert'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:147:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:188:in `run'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:26:in `start'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/bin/fastlane:23:in `load'
	from /usr/local/Cellar/fastlane/2.191.0/libexec/bin/fastlane:23:in `<main>'
 </pre>
</details>

### Environment

<details>
  <pre> ### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.4                                                    |
| Ruby                        | 3.0.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.191.0/libexec/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5.1                                                  |
| Swift Version               | 5.4.2                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**My fastline file**

**My appfile**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.191.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.20.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.6.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.484.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-sdk-core                    | 3.119.0      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.98.0       |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| optparse                        | 0.1.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |</pre>
</details>

**Comment by xraymemory** [comment]
From what I can tell the issue is happening [here in s3_storage.rb](https://github.com/fastlane/fastlane/blob/master/match/lib/match/storage/s3_storage.rb#L32) - it seems something is causing the `git_url` param to be surreptitiously passed and triggering this condition which short circuits the whole process

**Comment by xraymemory** [comment]
Quick follow up: tracing the interactive prompt about the git_url brought me to (options.rb)[https://github.com/fastlane/fastlane/blob/1cf43bf3a764293215558e9061585ed2deedb6e6/match/lib/match/options.rb#L133]. Here, it appears that the `git_url` is the only ConfigItem with `optional: false` which might be what is causing the clause in s3_storage to think there's a git_url supplied?

**Comment by xraymemory** [comment]
Ah okay I figured it out - it's missing the `--s3_bucket` argument but I was getting confused with the git_url prompt.
