### ISSUE TITLE
A parameter has an invalid value - 'bundleId][' is not a valid filter type

### ISSUE THREAD

**Issue by Mrc527** [fastlane/fastlane#19379]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It looks like there is something broken in the library which is currently used to communicate with the App Store.
Publishing a Beta (Test Flight) works perfectly but whenever I try to publish for production I get this error:
`A parameter has an invalid value - 'bundleId][' is not a valid filter type`

I tried on different, even clean, machines to ensure it's not coming from my CI environment. Without any luck.
##### Command executed
`fastlane deliver --verbose`
but also
`fastlane deliver download_metadata`
or
using `upload_to_app_store` target

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> % fastlane deliver download_metadata
[✔] 🚀 
[16:45:50]: fastlane detected a Gemfile in the current directory
[16:45:50]: However, it seems like you didn't use `bundle exec`
[16:45:50]: To launch fastlane faster, please use
[16:45:50]: 
[16:45:50]: $ bundle exec fastlane deliver download_metadata
[16:45:50]: 
[16:45:50]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:45:56]: Login to App Store Connect (xxx@yyy.com)
[16:45:58]: Login successful

Looking for related GitHub issues on fastlane/fastlane...

➡️  [spaceship, pilot] Getting "410 gone"
    https://github.com/fastlane/fastlane/issues/14521 [closed] 177 💬
    22 Jun 2019

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	21: from /usr/local/bin/fastlane:23:in `<main>'
	20: from /usr/local/bin/fastlane:23:in `load'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/bin/fastlane:23:in `<top (required)>'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	13: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	12: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/commands_generator.rb:164:in `block (2 levels) in run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/commands_generator.rb:164:in `new'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/runner.rb:25:in `initialize'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/detect_values.rb:17:in `run!'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/detect_values.rb:46:in `find_app'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/models/app.rb:80:in `find'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/models/app.rb:74:in `all'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get_apps'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:22:in `get_apps'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': A parameter has an invalid value - 'bundleId][' is not a valid filter type (Spaceship::UnexpectedResponse)
	21: from /usr/local/bin/fastlane:23:in `<main>'
	20: from /usr/local/bin/fastlane:23:in `load'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/bin/fastlane:23:in `<top (required)>'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	13: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	12: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/commands_generator.rb:164:in `block (2 levels) in run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/commands_generator.rb:164:in `new'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/runner.rb:25:in `initialize'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/detect_values.rb:17:in `run!'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/deliver/lib/deliver/detect_values.rb:46:in `find_app'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/models/app.rb:80:in `find'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/models/app.rb:74:in `all'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get_apps'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:22:in `get_apps'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': [!] A parameter has an invalid value - 'bundleId][' is not a valid filter type (Spaceship::UnexpectedResponse)
</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |
| Swift Version               | 5.3.2                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(["xxx.xxx.xxx"]) # The bundle identifier of your app
apple_id("xxx@xxx.com") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
json_key_file ENV["ANDROID_KEY_JSON"] || "fastlane/key.json"
package_name("xxx.xxx.xxx")

for_platform :android do
  app_identifier(["xxx.xxx.xxx"]) # The bundle identifier of your app
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.194.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-msbuild | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf_ext                         | 0.0.7.6      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.6        |
| faraday-net_http                | 1.0.1        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.3.0        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| google-apis-playcustomapp_v1    | 0.2.0        |
| uber                            | 0.1.0        |
| declarative-option              | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.0.2        |
| memoist                         | 0.16.2       |
| signet                          | 0.14.1       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-cloud-core               | 1.5.0        |
| google-apis-iamcredentials_v1   | 0.3.0        |
| google-apis-storage_v1          | 0.3.0        |
| google-cloud-storage            | 1.31.0       |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.428.0      |
| aws-eventstream                 | 1.1.0        |
| aws-sigv4                       | 1.2.2        |
| aws-sdk-core                    | 3.112.0      |
| aws-sdk-kms                     | 1.42.0       |
| aws-sdk-s3                      | 1.88.1       |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.19.0       |
| unicode-display_width           | 1.7.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| tty-screen                      | 0.8.1        |
| babosa                          | 1.0.4        |
| excon                           | 0.79.0       |
| fastimage                       | 2.2.2        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.11       |
| jwt                             | 2.2.2        |
| declarative                     | 0.0.20       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| rexml                           | 3.2.4        |
| webrick                         | 1.7.0        |
| google-cloud-env                | 1.4.0        |
| google-cloud-errors             | 1.0.1        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| emoji_regex                     | 3.2.2        |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| zlib                            | 1.0.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
| mini_portile2                   | 2.4.0        |
| nokogiri                        | 1.10.1       |
| fastlane-plugin-msbuild         | 0.1.4        |
</details>

*generated on:* **2021-09-24**
</details>

**Comment by Mrc527** [comment]
Guys, I found it!

If ever someone is getting the same weird message, the cause was the Appfile.
In there I setup the app_identifier the following way:
`app_identifier(["com.company.product.iOS"])`

Long story short, I put an array of strings. This should be supported as for the examples I found online but removing the array and setting the app_identifier as a simple string, everything works perfectly!

As for reference, this is what I mean:
`app_identifier("com.company.product.iOS")`
