### ISSUE TITLE
Not able to install fastlane (An error occurred while installing json (2.5.1), and Bundler cannot continue)

### ISSUE THREAD

**Issue by nerychucuy** [fastlane/fastlane#19384]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm using fastlane on Github Actions, so far it's been working great. Today, due to a library dependency on iOS, I had to setup a specific version of Swift (5.4.2) but after doing that, fastlane will not install anymore.

##### Command executed

I'm trying to install fastlane by doing `bundle install`, my Gemfile looks like this:

```
source "https://rubygems.org"

gem "fastlane"
```

And I'm getting this:

```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies........................................
Fetching rake 13.0.6
Installing rake 13.0.6
Using rexml 3.2.5
Using public_suffix 4.0.6
Using artifactory 3.0.15
Using atomos 0.1.3
Using aws-eventstream 1.2.0
Using jmespath 1.4.0
Using babosa 1.0.4
Using bundler 2.2.27
Using claide 1.0.3
Using colored 1.2
Using colored2 3.1.2
Using highline 2.0.3
Using declarative 0.0.20
Using digest-crc 0.6.4
Using unf_ext 0.0.8
Using dotenv 2.7.6
Using emoji_regex 3.2.2
Using excon 0.85.0
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using faraday-httpclient 1.0.1
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using multipart-post 2.0.0
Using ruby2_keywords 0.0.5
Using fastimage 2.2.5
Using gh_inspector 1.1.3
Using jwt 2.2.3
Using memoist 0.16.2
Using multi_json 1.15.0
Using os 1.1.1
Using httpclient 2.8.3
Using mini_mime 1.1.1
Using trailblazer-option 0.1.1
Using uber 0.1.0
Using retriable 3.1.2
Fetching webrick 1.7.0
Fetching aws-partitions 1.506.0
Fetching google-cloud-errors 1.2.0
Installing webrick 1.7.0
Installing aws-partitions 1.506.0
Installing google-cloud-errors 1.2.0
Fetching json 2.5.1
Using mini_magick 4.11.0
Using naturally 2.2.1
Using optparse 0.1.1
Using plist 3.6.0
Using rubyzip 2.3.2
Using security 0.1.3
Using terminal-notifier 2.0.0
Using unicode-display_width 1.8.0
Using tty-screen 0.8.1
Using tty-cursor 0.7.1
Using word_wrap 1.0.0
Using nanaimo 0.3.0
Using rouge 2.0.7
Fetching CFPropertyList 3.0.4
Installing json 2.5.1 with native extensions
Installing CFPropertyList 3.0.4
Using addressable 2.8.0
Using aws-sigv4 1.4.0
Using commander 4.6.0
Using unf 0.1.4
Using faraday 1.8.0
Using representable 3.1.1
Using terminal-table 1.8.0
Using tty-spinner 0.9.3
Using xcpretty 0.3.0
Fetching aws-sdk-core 3.121.1
Using domain_name 0.5.20190701
Using faraday_middleware 1.1.0
Using signet 0.16.0
Using google-cloud-env 1.5.0
Using simctl 1.6.8
Using xcodeproj 1.21.0
Using xcpretty-travis-formatter 1.0.1
Using http-cookie 1.0.4
Using googleauth 0.17.1
Using google-cloud-core 1.6.0
Using faraday-cookie_jar 0.0.7
Using google-apis-core 0.4.1
Using google-apis-androidpublisher_v3 0.11.0
Using google-apis-playcustomapp_v1 0.5.0
Using google-apis-iamcredentials_v1 0.7.0
Fetching google-apis-storage_v1 0.7.0
Installing google-apis-storage_v1 0.7.0
Installing aws-sdk-core 3.121.1
Using google-cloud-storage 1.34.1
Using aws-sdk-kms 1.48.0
Using aws-sdk-s3 1.103.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/lib/ruby/gems/2.7.0/gems/json-2.5.1/ext/json/ext/generator
/usr/local/opt/ruby@2.7/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.7.0 -r
./siteconf20210925-5539-185ktw5.rb extconf.rb
creating Makefile

current directory:
/usr/local/lib/ruby/gems/2.7.0/gems/json-2.5.1/ext/json/ext/generator
make DESTDIR\= clean

current directory:
/usr/local/lib/ruby/gems/2.7.0/gems/json-2.5.1/ext/json/ext/generator
make DESTDIR\=
compiling generator.c
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from
/usr/local/Cellar/ruby@2.7/2.7.4/include/ruby-2.7.0/ruby.h:33:
In file included from
/usr/local/Cellar/ruby@2.7/2.7.4/include/ruby-2.7.0/ruby/ruby.h:29:
/usr/local/Cellar/ruby@2.7/2.7.4/include/ruby-2.7.0/ruby/defines.h:126:10: fatal
error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/usr/local/lib/ruby/gems/2.7.0/gems/json-2.5.1 for inspection.
Results logged to
/usr/local/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-19/2.7.0/json-2.5.1/gem_make.out

  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:92:in `run'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:43:in `block in
make'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:35:in `each'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:35:in `make'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:63:in
`block in build'
  /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/tempfile.rb:291:in `open'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:26:in
`build'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:158:in
`build_extension'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:192:in `block in
build_extensions'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:189:in `each'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:189:in
`build_extensions'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/installer.rb:837:in
`build_extensions'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/rubygems_gem_installer.rb:66:in
`build_extensions'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/rubygems_gem_installer.rb:26:in
`install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/source/rubygems.rb:199:in
`install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:62:in
`apply_func'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:57:in
`block in process_queue'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:54:in
`loop'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:54:in
`process_queue'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing json (2.5.1), and Bundler cannot continue.

In Gemfile:
  fastlane was resolved to 2.195.0, which depends on
    json
Error: Process completed with exit code 5.
```

Any hints?

Thank you!

**Comment by lucgrabowski** [comment]
Hi, such issues happen if you don't use proper command line tools. 
Which version of Xcode and commandline tools do you use? I think that 12.5.1 is required to be able to use swift 5.4.2.

**Comment by nerychucuy** [comment]
Hi @lucgrabowski , thank you so much, that was the problem. I'm adding further  details here in case  someone else faces this issue:

In order to fix it, I had to do the following

1. Setup my Github Actions environment to macos-11
```yml
runs-on: macos-11
```
2. This allowed me to setup Xcode to `12.5.1` as you mentioned
```yml
uses: maxim-lobanov/setup-xcode@v1
with:
  xcode-version: '12.5.1'
```
3. Finally, I setup Swift version  like so:
```yml
uses: fwal/setup-swift@v1
with:
  swift-version: "5.4.2"
```

Now I'm able to nicely install fastlane!
