### ISSUE TITLE
fastlane match 2.195 : S3 access fails due to SSL certificate validation error

### ISSUE THREAD

**Issue by sebsto** [fastlane/fastlane#19391]
### New Regression Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.x.x`] : 2.195.0
- Last working version: [e.g. `2.x.x`] 2.194.0

Installed on a fresh 11.6 machine with `brew install fastlane`

### Regression Description

Match can not access certificates stored on S3 buckets. Invalid SSL certificate

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock': \e[31m[!] SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)\e[0m (Seahorse::Client::NetworkingError)
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:1038:in `connect'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:965:in `start'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/delegate.rb:87:in `method_missing'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/net_http/connection_pool.rb:300:in `start_session'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/net_http/connection_pool.rb:99:in `session_for'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/net_http/handler.rb:124:in `session'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/net_http/handler.rb:76:in `transmit'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/net_http/handler.rb:50:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/plugins/content_length.rb:17:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/plugins/request_callback.rb:85:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/s3_signer.rb:130:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/s3_signer.rb:61:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/s3_host_id.rb:17:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/xml/error_handler.rb:10:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/s3_signer.rb:108:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/redirects.rb:20:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:349:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:383:in `retry_request'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `retry_if_possible'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:360:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:383:in `retry_request'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `retry_if_possible'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:360:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:383:in `retry_request'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `retry_if_possible'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/retry_errors.rb:360:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/http_checksum.rb:18:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/dualstack.rb:46:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/accelerate.rb:61:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/expect_100_continue.rb:22:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:26:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/bucket_dns.rb:35:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/arn.rb:62:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/rest/handler.rb:10:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/endpoint_discovery.rb:80:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/arn.rb:95:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/dualstack.rb:36:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/seahorse/client/request.rb:72:in `send_request'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/poller.rb:65:in `send_request'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/poller.rb:51:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/waiter.rb:107:in `block in poll'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/waiter.rb:104:in `loop'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/waiter.rb:104:in `poll'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/waiter.rb:94:in `block (2 levels) in wait'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/waiter.rb:93:in `catch'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/waiter.rb:93:in `block in wait'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/waiter.rb:92:in `catch'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-core-3.121.1/lib/aws-sdk-core/waiters/waiter.rb:92:in `wait'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/waiters.rb:123:in `wait'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/bucket.rb:98:in `wait_until_exists'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/aws-sdk-s3-1.103.0/lib/aws-sdk-s3/bucket.rb:79:in `exists?'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:50:in `find_bucket!'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/match/lib/match/storage/s3_storage.rb:104:in `download'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/match/lib/match/runner.rb:63:in `run'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/match/lib/match/commands_generator.rb:69:in `block (3 levels) in run'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/match/lib/match/commands_generator.rb:188:in `run'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/match/lib/match/commands_generator.rb:26:in `start'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `load'
	from /usr/local/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre>[✔] 🚀 
[08:40:44]: fastlane detected a Gemfile in the current directory
[08:40:44]: However, it seems like you didn't use `bundle exec`
[08:40:44]: To launch fastlane faster, please use
[08:40:44]: 
[08:40:44]: $ bundle exec fastlane env
[08:40:44]: 
[08:40:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:40:45]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.26.9 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.6                                                    |
| Ruby                        | 3.0.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.195.0/libexec/bin/fastlane |
| Host                        | macOS 11.6 (20G165)                                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.0                                                    |
| Swift Version               | 5.5                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# before_all do
#   create_keychain(
#     name: "macos_build",
#     default_keychain: true,
#     unlock: true,
#     timeout: 0,
#     lock_when_sleeps: false,
#     password: "Passw0rd!"
#   )
# end

platform :ios do
  
  lane :clean do 
    clean_build_artifacts
    clear_derived_data
  end

  lane :beta do
    desc "Push a new beta build to TestFlight"
    # match(type: "appstore", readonly: true)
    increment_build_number(xcodeproj: "getting started.xcodeproj")
    build_app(workspace: "getting started.xcworkspace", scheme: "getting started")
    upload_to_testflight
  end
  

  lane :build do
#    unlock_keychain( 
#        path: "/Users/ec2-user/Library/Keychains/dev.keychain-db",
#        password: "Passw0rd",
#        set_default: true
#    )
    desc "Build the project"
    match(type: "development", readonly: true)
    build_app(workspace: "getting started.xcworkspace", scheme: "getting started",
              skip_archive: false,
              export_method: "development")
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.amazonaws.amplify.mobile.getting-started") # The bundle identifier of your app

apple_id(ENV['APPLE_ID']) # Your Apple email address
itc_team_id(ENV['ITC_TEAM_ID']) # App Store Connect Team ID
team_id(ENV['TEAM_ID']) # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.195.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.4        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 0.17.1       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.7.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.506.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.121.1      |
| aws-sdk-kms                     | 1.48.0       |
| aws-sdk-s3                      | 1.103.0      |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2021-09-27**
</details>
[08:40:49]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[08:40:49]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)
y
[08:40:50]: Successfully copied markdown into your clipboard 🎨
[08:40:50]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅</pre>
</details>

**Comment by sebsto** [comment]
I don't think this is a regression.

It fails on a fresh macOS 11.6 +Xcode 13  install 

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | 11.6                                                            |
| Ruby                        | 3.0.2                                                           |
| Bundler?                    | false                                                           |
| Git                         | git version 2.30.1 (Apple Git-130)                              |
| Installation Source         | /usr/local/Cellar/fastlane@2.194.0/2.194.0/libexec/bin/fastlane |
| Host                        | macOS 11.6 (20G165)                                             |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2/lib                                |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                                     |
| Is contained                | false                                                           |
| Is homebrew                 | true                                                            |
| Is installed via Fabric.app | false                                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                     |
| Xcode Version               | 13.0                                                            |
| Swift Version               | 5.5                                                             |

But it works has expected on a macOS 11.5.2 + Xcode 12.5.1 machine 

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.5.2                                                  |
| Ruby                        | 3.0.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.195.0/libexec/bin/fastlane |
| Host                        | macOS 11.5.2 (20G95)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5.1                                                  |
| Swift Version               | 5.4.2                                                   |

**Comment by sebsto** [comment]
Similar issues https://github.com/fastlane-community/fastlane-plugin-s3/issues/90#issuecomment-929504315
