### ISSUE TITLE
No simulators found on local machine

### ISSUE THREAD

**Issue by acecilia** [fastlane/fastlane#19395]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Getting the error `No simulators found on local machine` while trying to run `scan` in a machine with both xcode 12.3 and xcode 12.5.1

##### Command executed
* When running `xcode-select -p` the machine returns `/Applications/Xcode-12.5.1.app/Contents/Developer`
* When running `xcrun simctl list`, the machine return correctly the usual output:
```
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone SE (1st generation) (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone 8 (com.apple.CoreSimulator.SimDeviceType.iPhone-8)
iPhone 8 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus)
iPhone X (com.apple.CoreSimulator.SimDeviceType.iPhone-X)
iPhone Xs (com.apple.CoreSimulator.SimDeviceType.iPhone-XS)
iPhone Xs Max (com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max)
iPhone Xʀ (com.apple.CoreSimulator.SimDeviceType.iPhone-XR)
iPhone 11 (com.apple.CoreSimulator.SimDeviceType.iPhone-11)
iPhone 11 Pro (com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro)
iPhone 11 Pro Max (com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro-Max)
iPhone SE (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPhone-SE--2nd-generation-)
iPhone 12 mini (com.apple.CoreSimulator.SimDeviceType.iPhone-12-mini)
iPhone 12 (com.apple.CoreSimulator.SimDeviceType.iPhone-12)
iPhone 12 Pro (com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro)
iPhone 12 Pro Max (com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro-Max)
iPod touch (7th generation) (com.apple.CoreSimulator.SimDeviceType.iPod-touch--7th-generation-)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad mini 2 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-2)
iPad mini 3 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-3)
iPad mini 4 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-4)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (1st generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
iPad (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-)
iPad Pro (12.9-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-)
iPad Pro (10.5-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-)
iPad (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-)
iPad (7th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--7th-generation-)
iPad Pro (11-inch) (1st generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch-)
iPad Pro (12.9-inch) (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-)
iPad Pro (11-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch---2nd-generation-)
iPad Pro (12.9-inch) (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---4th-generation-)
iPad mini (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-mini--5th-generation-)
iPad Air (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-)
iPad (8th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--8th-generation-)
iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-)
iPad Pro (11-inch) (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro-11-inch-3rd-generation)
iPad Pro (12.9-inch) (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro-12-9-inch-5th-generation)
Apple TV (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple TV 4K (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K)
Apple TV 4K (at 1080p) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p)
Apple TV 4K (2nd generation) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-2nd-generation-4K)
Apple TV 4K (at 1080p) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-2nd-generation-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
Apple Watch Series 3 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm)
Apple Watch Series 3 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm)
Apple Watch Series 4 - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm)
Apple Watch Series 4 - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm)
Apple Watch Series 5 - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-40mm)
Apple Watch Series 5 - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-44mm)
Apple Watch SE - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-SE-40mm)
Apple Watch SE - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-SE-44mm)
Apple Watch Series 6 - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-6-40mm)
Apple Watch Series 6 - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-6-44mm)
== Runtimes ==
iOS 14.5 (14.5 - 18E182) - com.apple.CoreSimulator.SimRuntime.iOS-14-5
tvOS 14.5 (14.5 - 18L191) - com.apple.CoreSimulator.SimRuntime.tvOS-14-5
watchOS 7.4 (7.4 - 18T187) - com.apple.CoreSimulator.SimRuntime.watchOS-7-4
== Devices ==
-- iOS 14.5 --
-- tvOS 14.5 --
-- watchOS 7.4 --
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-14-3 --
    iPhone 8 (1C8F4D31-F909-4039-9B08-30022B98BFA2) (Shutdown) (unavailable, runtime profile not found)
    iPhone 8 Plus (C8D552EB-FB27-485D-93C1-1317F5FFFC28) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 (59868374-06FC-497B-BD14-384A701DB60A) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro (F204C0F1-AD6E-4661-AAB6-08413CA81985) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro Max (4E163810-45DB-46E7-834A-19F53B3C20D3) (Shutdown) (unavailable, runtime profile not found)
    iPhone SE (2nd generation) (3A126AE2-5DE0-4860-852A-56F57A80C1A0) (Shutdown) (unavailable, runtime profile not found)
    iPhone 12 mini (F8E1DBCA-720C-457F-8C4B-3883827A63DB) (Shutdown) (unavailable, runtime profile not found)
    iPhone 12 (F407BC6A-70AE-4DCA-8D8E-8B6958E215FB) (Shutdown) (unavailable, runtime profile not found)
    iPhone 12 Pro (BECFFDD1-2518-41CB-8CA7-AB14EEFC1792) (Shutdown) (unavailable, runtime profile not found)
    iPhone 12 Pro Max (4CDB1A12-B954-4149-BDDF-78D6F43F7C16) (Shutdown) (unavailable, runtime profile not found)
    iPod touch (7th generation) (AB74CBA8-5A38-4778-897D-65329AD6D96F) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (9.7-inch) (8979696A-40D0-4042-9E12-5E4C0A35412D) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (11-inch) (2nd generation) (27822BFB-1448-40C4-A4F7-4E7056BC9D2E) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9-inch) (4th generation) (D59E7225-C253-454C-9B78-F0526C2979FF) (Shutdown) (unavailable, runtime profile not found)
    iPad (8th generation) (992AB103-EBF9-4A20-9865-85D1BC138207) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (4th generation) (69F29F2A-4320-4548-BE86-0E672923E16B) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-14-3 --
    Apple TV (AEF285AD-99EA-4B50-8AFF-F271F5018BDE) (Shutdown) (unavailable, runtime profile not found)
    Apple TV 4K (4E26CCB0-A271-446D-8E5F-638F51CE98EB) (Shutdown) (unavailable, runtime profile not found)
    Apple TV 4K (at 1080p) (64950549-D81B-4F9C-B185-D2C75AC37514) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-7-2 --
    Apple Watch Series 5 - 40mm (6B652F01-862F-4D46-B1B1-BAE5624B0BA6) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 5 - 44mm (1C2FAA57-1C55-4AF9-82B0-74FCC7D6A7DA) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 6 - 40mm (73CDAD0C-A3E8-4289-ABB1-3822B839FC48) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 6 - 44mm (1DF2B108-7C24-4B63-A346-3D55B1D6B340) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
CF54EADF-21A5-4E42-BAAF-4EEA8E9E6F79 (unavailable)
    Watch: Apple Watch Series 5 - 40mm (6B652F01-862F-4D46-B1B1-BAE5624B0BA6) (Shutdown)
    Phone: iPhone 12 mini (F8E1DBCA-720C-457F-8C4B-3883827A63DB) (Shutdown)
B00DD9C8-2399-4F4C-B76D-B6083ACF0AB4 (unavailable)
    Watch: Apple Watch Series 5 - 44mm (1C2FAA57-1C55-4AF9-82B0-74FCC7D6A7DA) (Shutdown)
    Phone: iPhone 12 (F407BC6A-70AE-4DCA-8D8E-8B6958E215FB) (Shutdown)
8654B217-F81B-45BC-BA91-91913FEE26D8 (unavailable)
    Watch: Apple Watch Series 6 - 40mm (73CDAD0C-A3E8-4289-ABB1-3822B839FC48) (Shutdown)
    Phone: iPhone 12 Pro (BECFFDD1-2518-41CB-8CA7-AB14EEFC1792) (Shutdown)
725A7349-1807-448E-AD16-01935B656F40 (unavailable)
    Watch: Apple Watch Series 6 - 44mm (1DF2B108-7C24-4B63-A346-3D55B1D6B340) (Shutdown)
    Phone: iPhone 12 Pro Max (4CDB1A12-B954-4149-BDDF-78D6F43F7C16) (Shutdown)
```

* I run a lane that triggered scan. The device I pass to `scan` is `iPhone 8 (14.5)`
* The lane execution fails with a `No simulators found on local machine` error

##### Complete output when running fastlane, including the stack trace and command used

```
bundler: failed to load command: fastlane (/Users/user/my_project/vendor/bundle/ruby/2.6.0/bin/fastlane)
Traceback (most recent call last):
	49: from /Users/user/.gem/ruby/2.6.0/bin/bundle:23:in `<main>'
	48: from /Users/user/.gem/ruby/2.6.0/bin/bundle:23:in `load'
	47: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/exe/bundle:37:in `<top (required)>'
	46: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	45: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/exe/bundle:49:in `block in <top (required)>'
	44: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/cli.rb:24:in `start'
	43: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	42: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/cli.rb:30:in `dispatch'
	41: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	40: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	38: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/cli.rb:494:in `exec'
	37: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/cli/exec.rb:28:in `run'
	36: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/cli/exec.rb:63:in `kernel_load'
	35: from /Users/user/.gem/ruby/2.6.0/gems/bundler-2.2.8/lib/bundler/cli/exec.rb:63:in `load'
	34: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
	33: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	32: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/bin/fastlane:23:in `<top (required)>'
	31: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	30: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	29: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	28: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	27: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	26: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	25: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	24: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	23: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	22: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:828:in `block in parsing_binding'
	15: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	12: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	11: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	10: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 9: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 8: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane/lib/fastlane/actions/run_tests.rb:16:in `run'
	 7: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/scan/lib/scan/manager.rb:10:in `work'
	 6: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/scan/lib/scan/module.rb:17:in `config='
	 5: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/scan/lib/scan/detect_values.rb:34:in `set_additional_default_values'
	 4: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/scan/lib/scan/detect_values.rb:122:in `detect_simulator'
	 3: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/scan/lib/scan/detect_values.rb:122:in `tap'
	 2: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/scan/lib/scan/detect_values.rb:124:in `block in detect_simulator'
	 1: from /Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/user/my_project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': No simulators found on local machine (FastlaneCore::Interface::FastlaneError)
```

Both xcodes in the machine were installed with [xcversion](https://github.com/xcpretty/xcode-install)

**Comment by acecilia** [comment]
Issue was that there really were zero available simulators. To see it more clearly, do `xcrun simctl list devices`, and will see no simulators printed
