### ISSUE TITLE
Getting 'CocoaPods not installed or not in valid state' when using sh

### ISSUE THREAD

**Issue by Kondamon** [fastlane/fastlane#19407]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm building a flutter app and invoke flutter via a shell command within an AppFile. After upgrading to latest version of fastlane I receive the error 'Getting `CocoaPods not installed or not in valid state' when using sh`. I have had this error before but could fix it permanently via this solution: https://github.com/fastlane/fastlane/issues/16683#issuecomment-661751872 However, after upgrading to latest Fastlane 195.0 it is broken again. Also a downgrade to 194.0 doesn't fix the issue. The invocation of the command in the terminal succeeds without any error:

* Fastfile with this command leads to the error:
`sh("flutter build ios --release --build-name 2.1.0 --build-number 77.2 --no-codesign")`
* Manual execution on terminal works fine
`flutter build ios --release --build-name 2.1.0 --build-number 77.2 --no-codesign`

##### Command executed

fastlane beta

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Exit status of command 'flutter build ios --release --build-name 2.1.0 --build-number 77.2 --no-codesign' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Changing current working directory to: /Users/abc/pg/
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.app for device (ios-release)...
Warning: CocoaPods is installed but broken. Skipping pod install.
  You appear to have CocoaPods installed but it is not working.
  This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
  This can usually be fixed by re-installing CocoaPods.
To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

CocoaPods not installed or not in valid state.
\e[0m
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/fast_file.rb:223:in `block in sh'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/fast_file.rb:222:in `sh'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/fast_file.rb:216:in `sh'
        from Fastfile:29:in `block (2 levels) in parsing_binding'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `load'
        from /usr/local/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> [<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.5.2                                                  |
| Ruby                        | 3.0.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.195.0/libexec/bin/fastlane |
| Host                        | macOS 11.5.2 (20G95)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5.1                                                  |
| Swift Version               | 5.4.2                                                   |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	marketing_version = prompt_for_marketing_version()
  	build_number = get_build_number_master_branch()

  	# Use match in git for provisoning profiles
  	# install match via 1) 'fastlane match init' and then 2) 'fastlane match appstore'
  	match(type: "appstore", readonly: is_ci)

  	# invoke build with flutter
  	#sh("flutter build ios --release --build-name #{marketing_version.strip} --build-number #{build_number} --no-codesign")
  	build_app(
         workspace: "../ios/Runner.xcworkspace",
         scheme: "Runner",
         clean: true,
         export_options: {
         method: "appstore"
         })
  
    upload_to_testflight()
    upload_symbols_to_crashlytics()
  end
end

# Asks user for marketing version
private_lane :prompt_for_marketing_version do |options|
  marketing_version = get_version_number
  new_version = UI.input("What marketing version? <enter to keep it at #{marketing_version}>")
  unless new_version.strip == ""
    UI.message("Version number set to #{new_version}")
    marketing_version = new_version
  end
  marketing_version # return value
end

# Calculate build number from master branch commits + feature branch commits
# e.g. 54 on master branch or 54.4 on feature branch
private_lane :get_build_number_master_branch do
	build_number = ""
	master_commits = sh("echo $(expr $(git rev-list master --count) - $(git rev-list HEAD..master --count))")
	branch_commits = number_of_commits()
	if master_commits == branch_commits
		UI.message("Detected: on master branch (or feature witout commits)")
		build_number = master_commits
	else
		UI.message("Detected: on feature branch")	
		diff = branch_commits.to_i - master_commits.to_i 
		build_number = "#{master_commits.strip}.#{diff}".strip
	end
	UI.message("Build number: #{build_number}")	
	build_number #return value
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.app") # The bundle identifier of your app

itc_team_id("123456") # App Store Connect Team ID
team_id("123456") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.195.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.4        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 0.17.1       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.7.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.506.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.121.1      |
| aws-sdk-kms                     | 1.48.0       |
| aws-sdk-s3                      | 1.103.0      |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2021-09-29**
</details> </pre>
</details>

**Comment by Kondamon** [comment]
I resolved the issue via `sudo gem uninstall cocoapods`. It seems like that cocoapods shouldn't be installed manually on your system when running fastlane with flutter. When Cocoapods is automatically installed with the ios/Gemfile  it works fine, see this https://github.com/fastlane/fastlane/issues/16683#issuecomment-661751872.

**Comment by Kondamon** [comment]
After doing `bundle install` the problem occurs again. When I uninstall cocoapods fastlane works again but Android Studio is not able to build because cocoapods is missing. Any idea why the shell of fastlane can't execute `flutter build`? I guess the problem could be related to some PATH properties in the environment.

**Comment by Kondamon** [comment]
So, I have found a final fix for the issue and it's seems it is related to bundler and the used ruby version.

1. Install ruby and follow exactly [the instructions](https://stackoverflow.com/a/54873916) in section _"If you know for sure you don't need more than one version of Ruby at the same time (besides the one that came with macOS)"_
2. Go to your /ios directory where the Gemfile is located
3. `gem install bundler`
4. `bundle install`
5. `bundle exec fastlane` # Always use bundle exec
