### ISSUE TITLE
googleauth/signet.rb:112:in `rescue in retry_with_error': [!] Unexpected error: #<Faraday::ConnectionFailed wrapped=#<Errno::ECONNRESET: Connection reset by peer - SSL_connect>> (Signet::AuthorizationError)

### ISSUE THREAD

**Issue by sreeraj-ramesh** [fastlane/fastlane#19566]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Traceback (most recent call last):
	34: from /usr/local/bin/fastlane:23:in `<main>'
	33: from /usr/local/bin/fastlane:23:in `load'
	32: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/bin/fastlane:23:in `<top (required)>'
	31: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	30: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	29: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	28: from /var/lib/gems/2.5.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	27: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	26: from /var/lib/gems/2.5.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	25: from /var/lib/gems/2.5.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	24: from /var/lib/gems/2.5.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	23: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	22: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:14:in `block (2 levels) in parsing_binding'
	15: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	12: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	11: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	10: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 9: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 8: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
	 7: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/supply/lib/supply/uploader.rb:7:in `perform_upload'
	 6: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/supply/lib/supply/uploader.rb:428:in `client'
	 5: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/supply/lib/supply/client.rb:19:in `make_from_config'
	 4: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/supply/lib/supply/client.rb:19:in `new'
	 3: from /var/lib/gems/2.5.0/gems/fastlane-2.197.0/supply/lib/supply/client.rb:53:in `initialize'
	 2: from /var/lib/gems/2.5.0/gems/googleauth-1.1.0/lib/googleauth/signet.rb:74:in `fetch_access_token!'
	 1: from /var/lib/gems/2.5.0/gems/googleauth-1.1.0/lib/googleauth/signet.rb:101:in `retry_with_error'
/var/lib/gems/2.5.0/gems/googleauth-1.1.0/lib/googleauth/signet.rb:112:in `rescue in retry_with_error': [!] Unexpected error: #<Faraday::ConnectionFailed wrapped=#<Errno::ECONNRESET: Connection reset by peer - SSL_connect>> (Signet::AuthorizationError)

##### Command executed
fastlane android deploy

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by sreeraj-ramesh** [comment]
fastlane env
[✔] 🚀 
[12:52:14]: fastlane detected a Gemfile in the current directory
[12:52:14]: However, it seems like you didn't use `bundle exec`
[12:52:14]: To launch fastlane faster, please use
[12:52:14]: 
[12:52:14]: $ bundle exec fastlane env
[12:52:14]: 
[12:52:14]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:52:16]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | debian_based buster/sid                                         |
| Ruby                        | 2.5.1                                                           |
| Bundler?                    | false                                                           |
| Git                         | git version 2.17.1                                              |
| Installation Source         | /usr/local/bin/fastlane                                         |
| Host                        | Ubuntu 18.04.6 LTS debian_based buster/sid (4.15.0-161-generic) |
| Ruby Lib Dir                | /usr/lib                                                        |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                                      |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby


platform :android do
  desc "Deploy android app on play store"

  lane :deploy do
    cordova(
      platform: 'android',
      keystore_path: '../portal.keystore',
      keystore_alias: 'portal',
      keystore_password: 'amma123'

    )
  supply(
  apk_paths: [
   '../app-release-unsigned.apk',
  ],
)
    # Alternatively, deploy an Android Application Bundle
    # cordova(
    #   package_type: 'bundle',
    #   platform: 'android',
    #   keystore_path: './prod.keystore',
    #   keystore_alias: 'prod',
    #   keystore_password: 'password'
    # )
    # supply(aab: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "/usr/local/AT_Dev_Env/atech/BUILD_V/aamp/amritasurvey-enumero-cd2de2c6acf6.json"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.197.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-cordova | 3.1.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.4        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.88.0       |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.30       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.121.5      |
| aws-sdk-kms                     | 1.50.0       |
| aws-sdk-s3                      | 1.104.0      |
| json                            | 2.6.1        |
| webrick                         | 1.7.0        |
| rake                            | 13.0.6       |
| aws-partitions                  | 1.522.0      |
| date                            | 3.2.0        |
| openssl                         | 2.2.1        |
| ipaddr                          | 1.2.3        |
| rack                            | 2.2.3        |
| rack-test                       | 1.1.0        |
| fileutils                       | 1.6.0        |
| racc                            | 1.6.0        |
| nokogiri                        | 1.12.5       |
| psych                           | 3.0.2        |
| fastlane-plugin-cordova         | 3.1.1        |
</details>


*generated on:* **2021-11-03**
</details>
[12:52:17]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[12:52:17]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
