### ISSUE TITLE
Language "da-DK" is not activated for this app version

### ISSUE THREAD

**Issue by mortenholmgaard** [fastlane/fastlane#1958]
When I use deliver it fails saying: 

> "Language "da-DK" is not activated for this app version" 

I my deliver file I have this code:
```
name({ "da-DK" => app["Title"] })
description({ "da-DK" => app["AppStoreText"] })
keywords({ "da-DK" => app["AppStoreKeywords"] })
marketing_url({ "da-DK" => app["MarketingUrl"] })
support_url({ "da-DK" => app["MarketingUrl"] })
```

Should I use "default" and not "da-DK"?
Do I need to setup any thing else to make this work?

##### Complete output when running fastlane, including the stack trace and command used
```
Does the Preview on path './Preview.html' look okay for you? (y/n)
y
 [21:42:18]: HTML file confirmed...

[21:42:18]: Activating language da-DK...
[21:42:20]: -----------------
[21:42:20]: --- Step: say ---
[21:42:20]: -----------------
[21:42:20]: $ say 'Language "da-DK" is not activated for this app version.'
[21:42:25]: Variable Dump:
[21:42:25]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"create_app_for_app_store", :CERT_FILE_PATH=>"xxx", :CERT_CERTIFICATE_ID=>"XXX", :PRODUCE_APPLE_ID=>"xxx", :SIGH_PROFILE_PATH=>"xxx.mobileprovision", :SIGH_PROFILE_PATHS=>["xxx.mobileprovision"], :SIGH_UDID=>"bad3f6d7-bccf-4445-8af0-f779c82fc8c1", :SIGH_PROFILE_TYPE=>"app-store"}
[21:42:25]: Language 'da-DK' is not activated for this app version.

+------+---------+-------------+
|       fastlane summary       |
+------+---------+-------------+
| Step | Action  | Time (in s) |
+------+---------+-------------+
| 1    | cert    | 9           |
| 2    | produce | 7           |
| 3    | sigh    | 7           |
| 4    | pem     | 2           |
| 5    | deliver | 24          |
| 6    | say     | 4           |
+------+---------+-------------+

[21:42:25]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '517c9d86c2ad98f085494f00c0c5de0b'
The crash report has been stored locally '/tmp/sentry_517c9d86c2ad98f085494f00c0c5de0b.json'
/Users/mortenholmgaard/.gems/gems/spaceship-0.22.0/lib/spaceship/tunes/language_item.rb:29:in `get_lang': [!] Language 'da-DK' is not activated for this app version. (RuntimeError)
	from /Users/mortenholmgaard/.gems/gems/spaceship-0.22.0/lib/spaceship/tunes/language_item.rb:20:in `[]='
	from /Users/mortenholmgaard/.gems/gems/deliver-1.10.3/lib/deliver/upload_metadata.rb:41:in `block (2 levels) in upload'
	from /Users/mortenholmgaard/.gems/gems/deliver-1.10.3/lib/deliver/upload_metadata.rb:38:in `each'
	from /Users/mortenholmgaard/.gems/gems/deliver-1.10.3/lib/deliver/upload_metadata.rb:38:in `block in upload'
	from /Users/mortenholmgaard/.gems/gems/deliver-1.10.3/lib/deliver/upload_metadata.rb:29:in `each'
	from /Users/mortenholmgaard/.gems/gems/deliver-1.10.3/lib/deliver/upload_metadata.rb:29:in `upload'
	from /Users/mortenholmgaard/.gems/gems/deliver-1.10.3/lib/deliver/runner.rb:58:in `upload_metadata'
	from /Users/mortenholmgaard/.gems/gems/deliver-1.10.3/lib/deliver/runner.rb:21:in `run'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:47:in `block in parsing_binding'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/mortenholmgaard/.gems/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/bin/fastlane:156:in `run'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.66.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```
### Configuration Files
Fastfile command:
```ruby
deliver(submit_for_review: false)
```

Deliver file:
```ruby
app ENV["PRODUCE_APPLE_ID"] #produce must be run before deliver
app_version ENV["APP_VERSION_NUMBER"] # remove this if you provide an ipa file
release_notes({ "da-DK" => app["AppStoreChangeLog"] })
app_icon ".#{app_target}/icon.png"
screenshots_path ".#{app_target}/screenshots/"

#User settings
name({ "da-DK" => app["Title"] })
description({ "da-DK" => app["AppStoreText"] })
keywords({ "da-DK" => app["AppStoreKeywords"] })
marketing_url({ "da-DK" => app["MarketingUrl"] })
support_url({ "da-DK" => app["MarketingUrl"] })
copyright_name = app["Copyright"]
copyright "#{Time.now.year} #{copyright_name}"

price_tier 0 # free app
primary_category "Reference"
secondary_category "Social Networking"
automatic_release true
app_rating_config_path "./fastlane/ratings_config.json"
```
### Environment
fastlane 1.66.0

**Comment by vpolouchkine** [comment]
Doesn't look like "da-DK" is supported, per https://github.com/fastlane/fastlane/tree/master/deliver#available-language-codes.

**Comment by mortenholmgaard** [comment]
You are right - it should just da. But please add this link to the error message and improve the error message, so people in the future is able to figure this out by them self.

**Comment by vpolouchkine** [comment]
Glad to hear you're up and running. Thanks for the feedback.
