### ISSUE TITLE
sh command crashes when trying to call xcrun xccov 

### ISSUE THREAD

**Issue by mime29** [fastlane/fastlane#19618]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I migrated from Xcode 12.5.1 to 13.1.0 on circle ci (tried 13.0.0 too)
and lanes is now failing.
But the command executed `xcrun xccov view` does not have a different output according to xcode13 changelog

NOTE: If I set `log: true` then the lane passes successfully! But that's not a solution here.

##### Command executed

```
    xccov_result = sh("xcrun xccov view --report --json #{coverage_path}", log: false)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
FastlaneCore::Interface::FastlaneShellError: [!] Shell command exited with exit status 1 instead of 0.
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:223:in `block in sh'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:222:in `sh'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:214:in `sh'
  lanes/test:483:in `block in parsing_binding'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  lanes/test:239:in `block in parsing_binding'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  lanes/test:14:in `block in parsing_binding'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.197.0/bin/fastlane:23:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `load'
  /Users/distiller/project/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `<top (required)>'
 </pre>
</details>

### Environment

Circle CI https://discuss.circleci.com/t/xcode-13-1-rc-released/41577

<details>
  <pre> 
</pre>
</details>

**Comment by mime29** [comment]
Can't post fastlane env because of confidentiality issues but we are using the latest version of fastlane. `2.198.0`
