### ISSUE TITLE
The request cannot be fulfilled because of the state of another resource. - Can't Reorder Assets after Submission appScreenshots

### ISSUE THREAD

**Issue by SwiftiSwift** [fastlane/fastlane#19661]
Hi,

I am trying to upload my macOS build of my MacCatalyst app to Itunes Connect using fastlane but I get the following error 
`The request cannot be fulfilled because of the state of another resource. - Can't Reorder Assets after Submission appScreenshots`
while running `upload_to_app_store(submit_for_review: true)`

This is my lane
```
platform :macOS do
  desc "Push a new MACOS release build to the App Store"
  lane :release do
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Das Gedenken.xcodeproj"
    )

    snapshot(skip_open_summary: true)

    build_app(
      workspace: "Das Gedenken.xcworkspace", 
      scheme: "Das Gedenken"
    )

    upload_to_app_store(submit_for_review: true)
  end

  desc "Push a new MACOS release build to the App Store"
  lane :releaseW do
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Das Gedenken.xcodeproj"
    )

    upload_to_app_store(submit_for_review: true)
  end
end
```

Output:

```
......
[17:23:16]: HTML file confirmed...
[17:23:21]: Will begin uploading metadata for '1.4.5' on App Store Connect
[17:23:21]: Release type will not be set because neither `automatic_release` nor `auto_release_date` were provided. Please explicitly set one of these options if you need a release type set
[17:23:21]: Uploading metadata to App Store Connect for version
[17:23:25]: Uploading metadata to App Store Connect for localized version 'ar-SA'
[17:23:25]: Uploading metadata to App Store Connect for localized version 'en-US'
[17:23:25]: Uploading metadata to App Store Connect for localized version 'de-DE'
[17:23:27]: Uploading metadata to App Store Connect for localized info 'en-US'
[17:23:27]: Uploading metadata to App Store Connect for localized info 'de-DE'
[17:23:27]: Uploading metadata to App Store Connect for localized info 'ar-SA'
[17:23:32]: Uploading app review information to App Store Connect
[17:23:38]: Will begin uploading snapshots for '1.4.5' on App Store Connect
[17:23:38]: Starting with the upload of screenshots...
[✔] Waiting for all the screenshots to finish being processed... 
[17:23:40]: Successfully uploaded all screenshots
[⠴] Sorting screenshots uploaded... #<Thread:0x00007fd9d42b13c0 /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/queue_worker.rb:37 run> terminated with exception (report_on_exception is true):
/usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': The request cannot be fulfilled because of the state of another resource. - Can't Reorder Assets after Submission appScreenshots (Spaceship::UnexpectedResponse)
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:522:in `patch_app_screenshot_set_screenshots'
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app_screenshot_set_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/models/app_screenshot_set.rb:156:in `reorder_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/deliver/lib/deliver/upload_screenshots.rb:242:in `block in sort_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
#<Thread:0x00007fd9d42b16b8 /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/queue_worker.rb:37 run> terminated with exception (report_on_exception is true):
/usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': The request cannot be fulfilled because of the state of another resource. - Can't Reorder Assets after Submission appScreenshots (Spaceship::UnexpectedResponse)
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:522:in `patch_app_screenshot_set_screenshots'
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app_screenshot_set_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/models/app_screenshot_set.rb:156:in `reorder_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/deliver/lib/deliver/upload_screenshots.rb:242:in `block in sort_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
#<Thread:0x00007fd9d42b15a0 /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/queue_worker.rb:37 run> terminated with exception (report_on_exception is true):
/usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': The request cannot be fulfilled because of the state of another resource. - Can't Reorder Assets after Submission appScreenshots (Spaceship::UnexpectedResponse)
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:522:in `patch_app_screenshot_set_screenshots'
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app_screenshot_set_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/models/app_screenshot_set.rb:156:in `reorder_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/deliver/lib/deliver/upload_screenshots.rb:242:in `block in sort_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
+---------------------+----------------+
|             Lane Context             |
+---------------------+----------------+
| DEFAULT_PLATFORM    | ios            |
| PLATFORM_NAME       | macOS          |
| LANE_NAME           | macOS releaseW |
| LATEST_BUILD_NUMBER | 37             |
| LATEST_VERSION      | 1.4.4          |
| BUILD_NUMBER        | 38             |
+---------------------+----------------+
[⠦] Sorting screenshots uploaded... [17:23:41]: The request cannot be fulfilled because of the state of another resource. - Can't Reorder Assets after Submission appScreenshots

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | app_store_build_number | 8           |
| 3    | increment_build_number | 1           |
| 💥   | upload_to_app_store    | 42          |
+------+------------------------+-------------+

[17:23:41]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[⠙] Sorting screenshots uploaded... Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': \e[31m[!] The request cannot be fulfilled because of the state of another resource. - Can't Reorder Assets after Submission appScreenshots\e[0m (Spaceship::UnexpectedResponse)
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:522:in `patch_app_screenshot_set_screenshots'
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app_screenshot_set_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/models/app_screenshot_set.rb:156:in `reorder_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/deliver/lib/deliver/upload_screenshots.rb:242:in `block in sort_screenshots'
	from /usr/local/Cellar/fastlane/2.198.1/libexec/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
```

**Comment by SwiftiSwift** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.0.1                                                  |
| Ruby                        | 3.0.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.31.1                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.198.1/libexec/bin/fastlane |
| Host                        | macOS 12.0.1 (21A559)                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.1                                                    |
| Swift Version               | 5.5.1                                                   |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Das Gedenken.xcodeproj"
    )

    snapshot(skip_open_summary: true)

    build_app(
      workspace: "Das Gedenken.xcworkspace", 
      scheme: "Das Gedenken"
    )

    upload_to_app_store(submit_for_review: true)
  end

  lane :updateScreenshots do
    #snapshot(skip_open_summary: true)

    deliver(overwrite_screenshots: true, skip_binary_upload: true)
  end
end

platform :watchOS do
  lane :screenshots do
    snapshot(scheme: "GedenkenWatchOSUITests")
  end
end

platform :mac do
  desc "Push a new MACOS release build to the App Store"
  lane :release do
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Das Gedenken.xcodeproj"
    )

    snapshot(skip_open_summary: true)

    build_app(
      workspace: "Das Gedenken.xcworkspace", 
      scheme: "Das Gedenken"
    )

    upload_to_app_store(submit_for_review: true)
  end

  desc "Push a new MACOS release build to the App Store"
  lane :releaseW do
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "Das Gedenken.xcodeproj"
    )

    upload_to_app_store(submit_for_review: true)
  end
end
```
</details>

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.198.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.88.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| json                            | 2.6.1        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.534.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.123.0      |
| aws-sdk-kms                     | 1.51.0       |
| aws-sdk-s3                      | 1.107.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>


*generated on:* **2021-11-30**
</details>
