### ISSUE TITLE
Shell copy command does not work inside fast file.

### ISSUE THREAD

**Issue by NitinChronext** [fastlane/fastlane#19668]
I have a simple command to replace one file with another inside fastfile and does not run, here is my lane which run to replace file

```
lane: repalce 
 sh "cp ../.env.development ../.env.production"
end
```

I get below error ```
Exit status of command 'cp "../.env.development" "../.env.production"' was 1 instead of 0.
cp: ../.env.development: No such file or directory
```

`
🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	31: from /usr/local/bin/fastlane:23:in `<main>'
	30: from /usr/local/bin/fastlane:23:in `load'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	22: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	13: from Fastfile:188:in `block (2 levels) in parsing_binding'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	 8: from Fastfile:147:in `block (2 levels) in parsing_binding'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/fast_file.rb:216:in `sh'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/fast_file.rb:222:in `sh'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/fast_file.rb:223:in `block in sh'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'cp ".../.env.development" ".../.env.production"' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
cp: .../.env.development: No such file or directory`

Same command works fine if I run from terminal, I would appreciate any quick help

**Comment by NitinChronext** [comment]
updated full output

**Comment by Kukurijek** [comment]
Actually, the shell copy command does work inside Fastfile 😄 
The path to your file is  incorrect.
When you run a lane, you are not in the root of the project, but in the `fastlane` directory. 
Run `sh "ls"` or `sh "pwd"`and you will see.

**Comment by Nebel69** [comment]
Please make sure to update to the latest fastlane version and check if that solves the issue. Let us know if that works for you by adding a comment.
