### ISSUE TITLE
Undefined method shellscape for nil:NilClass

### ISSUE THREAD

**Issue by jayshah-swiggy** [fastlane/fastlane#19709]
### New Issue Checklist

Error:
```
bundler: failed to load command: fastlane (/Users/jay.shah/Documents/swiggy-private-github/ipartner/ios/vendor/bundle/bin/fastlane)
NoMethodError: [!] undefined method `shellescape' for nil:NilClass
```

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

```
  lane :beta do
    #increment_build_number(xcodeproj: "MyAppName.xcodeproj")
    gym(
        workspace: "MyAppName.xcworkspace",
        scheme: "MyAppName-Release",
        export_xcargs: "-allowProvisioningUpdates",
        silent: true,
        clean: true
     )
     upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1111111111")
  end
```

##### Complete output when running fastlane, including the stack trace and command used

Command executed: `bundle exec fastlane beta`

<details>
  <pre> 
  bundler: failed to load command: fastlane (/Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/bin/fastlane)
NoMethodError: [!] undefined method `shellescape' for nil:NilClass
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:273:in `build_upload_command'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:519:in `upload'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/pilot/lib/pilot/build_manager.rb:41:in `upload'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:37:in `block (2 levels) in parsing_binding'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/gems/fastlane-2.199.0/bin/fastlane:23:in `<top (required)>'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/bin/fastlane:23:in `load'
  /Users/jay.shah/Documents/my-github/myapp/ios/vendor/bundle/bin/fastlane:23:in `<top (required)>'
   </pre>
</details>

### Environment

<details>
  <pre> 
  
| Key                         | Value                                                                     |
| --------------------------- | ------------------------------------------------------------------------- |
| OS                          | 11.6                                                                      |
| Ruby                        | 2.6.3                                                                     |
| Bundler?                    | true                                                                      |
| Git                         | git version 2.30.1 (Apple Git-130)                                        |
| Installation Source         | ~/Documents/my-github/myapp/ios/vendor/bundle/bin/fastlane |
| Host                        | macOS 11.6 (20G165)                                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib            |
| OpenSSL Version             | LibreSSL 2.8.3                                                            |
| Is contained                | false                                                                     |
| Is homebrew                 | false                                                                     |
| Is installed via Fabric.app | false                                                                     |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                               |
| Xcode Version               | 13.1                                                                      |
| Swift Version               | 5.5.1                                                                     |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.199.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.2   | ✅ Up-To-Date  |

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 1.17.2       |
| etc                                       | 1.0.1        |
| forwardable                               | 1.2.0        |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.5        |
| concurrent-ruby                           | 1.1.8        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.14.3       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.9        |
| activesupport                             | 4.2.11.3     |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.541.0      |
| aws-sigv4                                 | 1.4.0        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.124.0      |
| aws-sdk-kms                               | 1.52.0       |
| aws-sdk-s3                                | 1.109.0      |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| clamp                                     | 0.6.5        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| cocoapods-core                            | 1.5.3        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| netrc                                     | 0.11.0       |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.0.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.21.0       |
| cocoapods                                 | 1.5.3        |
| colored                                   | 1.2          |
| colorize                                  | 0.8.1        |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.4        |
| unf_ext                                   | 0.0.8        |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.89.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.8.0        |
| http-cookie                               | 1.0.4        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.5        |
| jwt                                       | 2.3.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.16.0       |
| googleauth                                | 1.1.0        |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.1.2        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.4.1        |
| google-apis-androidpublisher_v3           | 0.14.0       |
| google-apis-playcustomapp_v1              | 0.6.0        |
| google-apis-iamcredentials_v1             | 0.9.0        |
| google-apis-storage_v1                    | 0.10.0       |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.35.0       |
| json                                      | 2.6.1        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.3.2        |
| synx                                      | 0.2.1        |

   </pre>
</details>

**Comment by jayshah-swiggy** [comment]
worked after I added `username` field in `upload_to_tesflight` task, in previous versions of fastlane, it used to prompt for username if it was missing in fastfile.
