### ISSUE TITLE
upload_app_privacy_details_to_app_store fails and returns error when NSUserTrackingUsageDescription is present in info.plist

### ISSUE THREAD

**Issue by PWhittle86** [fastlane/fastlane#19781]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Error is being returned from upload_app_privacy_details_to_app_store when privacy details have previously been uploaded to the app store and the bundle contains NSUserTrackingUsageDescription. This is the same issue that was described in https://github.com/fastlane/fastlane/issues/19487.

Temporarily we are going to stop uploading privacy data after the first privacy details upload in order to stop users from getting confused when they're presented with errors, but it would be good if updates to existing privacy data could also be uploaded to the App Store when provided.

Thanks

##### Command executed
fastlane ios upload_privacy

##### Complete output when running fastlane, including the stack trace and command used

+---------------+--------------------+
|            Lane Context            |
+---------------+--------------------+
| PLATFORM_NAME | ios                |
| LANE_NAME     | ios upload_privacy |
+---------------+--------------------+
[12:24:51]: Your binary indicates that your app tracks users. - Your app indicates that you track users.

+------+-----------------------------+-------------+
|                 fastlane summary                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 💥   | upload_app_privacy_details  | 9           |
|      | _to_app_store               |             |
+------+-----------------------------+-------------+

[12:24:51]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  upload_app_privacy_details_to_app_store returns error "Your binary indicates that your app tracks users. - Your app indicates that you track users"
    https://github.com/fastlane/fastlane/issues/19487 [closed] 6 💬
    3 days ago

➡️  Error upload to AppStore TestFlight using fastlane v2.198.0 (An error occurred while processing the json request. (1268)) using Azure Devops
    https://github.com/fastlane/fastlane/issues/19613 [closed] 27 💬
    a week ago

➡️  [FAILING] Unable to upload app privacy details using fastlane upload_app_privacy_details_to_app_store 
    https://github.com/fastlane/fastlane/issues/18653 [closed] 15 💬
    18 Oct 2021

and 3 more at: https://github.com/fastlane/fastlane/search?q=Your%20binary%20indicates%20that%20your%20app%20tracks%20users.%20-%20Your%20app%20indicates%20that%20you%20track%20users.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': \e[31m[!] Your binary indicates that your app tracks users. - Your app indicates that you track users.\e[0m (Spaceship::UnexpectedResponse)
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/api_client.rb:148:in `delete'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:264:in `delete_app_data_usage'
	from /usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/forwardable.rb:238:in `delete_app_data_usage'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/spaceship/lib/spaceship/connect_api/models/app_data_usage.rb:55:in `delete!'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `each'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `upload_app_data_usages'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:43:in `run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:22:in `block (2 levels) in parsing_binding'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/bin/fastlane:25:in `load'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/bin/fastlane:25:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.5.2                                                  |
| Ruby                        | 3.0.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.32.0 (Apple Git-132)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.199.0/libexec/bin/fastlane |
| Host                        | macOS 11.5.2 (20G95)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.2.1                                                  |
| Swift Version               | 5.5.2                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :ios do
  APP_IDENTIFIER = 'bundle-id-goes-here'
  TEAM_NAME = 'APPLE TEAM'
  USERNAME = 'aaa@aaaaa.co.uk'

  desc 'Update privacy details'
  lane :upload_privacy do
    upload_app_privacy_details_to_app_store(
      username: USERNAME,
      team_name: TEAM_NAME,
      app_identifier: APP_IDENTIFIER,
      json_path: 'fastlane/app_privacy_details.json'
    )
  end
  
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.199.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.14.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.10.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.35.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.540.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.124.0      |
| aws-sdk-kms                     | 1.52.0       |
| aws-sdk-s3                      | 1.109.0      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| securerandom                    | 0.1.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2022-01-12**
</details>

<details>
  <pre>   </pre>
</details>

**Comment by PWhittle86** [comment]
Bump. Issue still occurring.

**Comment by max-ott** [comment]
What are the values in the privacy report? As far as I know you need to declare some values for TRACKING if you upload the respective plist values.

**Comment by PWhittle86** [comment]
Privacy details are:

```
[
    {
      "category": "NAME",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU"
      ]
    },
    {
      "category": "EMAIL_ADDRESS",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU"
      ]
    },
    {
      "category": "PHONE_NUMBER",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU"
      ]
    },
    {
      "category": "PHYSICAL_ADDRESS",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU"
      ]
    },
    {
      "category": "PAYMENT_INFORMATION",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU"
      ]
    },
    {
      "category": "PRECISE_LOCATION",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU"
      ]
    },
    {
      "category": "SEARCH_HISTORY",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU",
        "DATA_USED_TO_TRACK_YOU"
      ]
    },
    {
      "category": "USER_ID",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU"
      ]
    },
    {
      "category": "DEVICE_ID",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU",
        "DATA_USED_TO_TRACK_YOU"
      ]
    },
    {
      "category": "PURCHASE_HISTORY",
      "purposes": [
        "APP_FUNCTIONALITY"
      ],
      "data_protections": [
        "DATA_LINKED_TO_YOU"
      ]
    },
    {
      "category": "PRODUCT_INTERACTION",
      "purposes": [
        "ANALYTICS"
      ],
      "data_protections": [
        "DATA_NOT_LINKED_TO_YOU"
      ]
    },
    {
      "category": "ADVERTISING_DATA",
      "purposes": [
        "ANALYTICS"
      ],
      "data_protections": [
        "DATA_NOT_LINKED_TO_YOU"
      ]
    },
    {
      "category": "CRASH_DATA",
      "purposes": [
        "ANALYTICS"
      ],
      "data_protections": [
        "DATA_NOT_LINKED_TO_YOU"
      ]
    }
]
```

**Comment by PWhittle86** [comment]
Bump.

**Comment by yood** [comment]
Ran into this issue as well.

**Comment by PWhittle86** [comment]
Hi. 

Yes, the issue is still occurring on the latest fastlane version.

We're working around it at the moment - we don't use upload_app_privacy_details_to_app_store when submitting an app if we know that privacy data has been published for the app in the past, as it causes the error described above.

It would be good to get a fix for this if possible, so that we could provide updates to existing privacy data when needed.

Thanks

**Comment by mortenholmgaard** [comment]
I have the same problem

**Comment by gavrichards** [comment]
Still very much an issue, shouldn't have been closed.

**Comment by rogerluan** [comment]
Hi @gavrichards 👋 thanks for commenting. Reopening, and I have a PR open for this here: https://github.com/fastlane/fastlane/pull/20695 — this issue won't be closed by the bot anymore 👍

**Comment by kpowelltech** [comment]
Hello!  I am having this issue as well.  In my case, there is a connection made between Fastlane and App Store Connect, but the full Data Type scope is not populating; `Device ID` is showing in App Store Connect, but even this data point is empty.  I have 9 or 11 data points, given the binary's different states.

**Comment by kpowelltech** [comment]
Hi Team - I'm still experiencing this issue.  The apps I manage change their Privacy Settings quite frequently.

**Comment by rogerluan** [comment]
Perhaps you could help us test this branch @kpowelltech ? https://github.com/fastlane/fastlane/pull/20695 🙏

**Comment by kpowelltech** [comment]
@rogerluan I am testing now...I was able to successfully submit on one app so far and that's huge!  I have quite a few more, so I will keep you posted on results.

**Comment by kpowelltech** [comment]
@rogerluan Doesn't seem there is consistency.  Our apps fall into two categories...tracking and non tracking.  I uploaded 3 apps that 2 of them didn't populate the data properly and seemed to error out as it was uploading.  I say this because there are only two data points declared (out of 11), and only one of them is filled out completely.  

When running the script again, the error occurs very quickly as opposed to it taking close to a minute to complete (which is fine)

The 3rd app was uploaded successfully.  

```+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 💥   | upload_app_privacy_details_to_app_  | 6           |
|      | store                               |             |
| 💥   | upload_app_privacy_details_to_app_  | 40          |
|      | store                               |             |
| 3    | upload_app_privacy_details_to_app_  | 86          |
|      | store                               |             |
+------+-------------------------------------+-------------+```



```[13:12:49]: -----------------------------------------------------
[13:12:49]: --- Step: upload_app_privacy_details_to_app_store ---
[13:12:49]: -----------------------------------------------------
[13:12:49]: Login to App Store Connect (<invite-email>)
[13:13:01]: Login successful
[13:13:03]: Preparing to upload App Data Usage
[13:13:04]: An error occurred: Your binary indicates that your app tracks users. - Your app indicates that you track users.```

**Comment by gavrichards** [comment]
Still getting this.

**Comment by githubbla** [comment]
[01:06:09]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [upload_app_privacy_details_to_app_store] fix error when `Info.plist` contains `NSUserTrackingUsageDescription`
    https://github.com/fastlane/fastlane/pull/20695 [open] 3 💬
    22 May 2024

➡️  [deliver] increase chances of success when creating a new app version even when Apple servers are degraded
    https://github.com/fastlane/fastlane/pull/21742 [closed] 58 💬
    22 Feb 2024

➡️  [Deliver] - Not able to reject the app version which is in Pending Developer Release
    https://github.com/fastlane/fastlane/issues/17539 [closed] 41 💬
    19 Mar 2022

and 2 more at: https://github.com/fastlane/fastlane/search?q=The%20provided%20entity%20includes%20a%20relationship%20with%20an%20invalid%20value%20-%20You%20cannot%20create%20a%20new%20version%20of%20the%20App%20in%20the%20current%20state.%20-%20%2Fdata%2Frelationships%2Fapp&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/roman/.rbenv/versions/2.7.5/bin/fastlane)
Traceback (most recent call last):
	48: from /Users/roman/.rbenv/versions/2.7.5/bin/bundle:23:in `<main>'
	47: from /Users/roman/.rbenv/versions/2.7.5/bin/bundle:23:in `load'
	46: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/exe/bundle:29:in `<top (required)>'
	45: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	44: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/exe/bundle:37:in `block in <top (required)>'
	43: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/cli.rb:28:in `start'
	42: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	41: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/cli.rb:34:in `dispatch'
	40: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	39: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	38: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	37: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/cli.rb:492:in `exec'
	36: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:23:in `run'
	35: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
	34: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:58:in `load'
	33: from /Users/roman/.rbenv/versions/2.7.5/bin/fastlane:23:in `<top (required)>'
	32: from /Users/roman/.rbenv/versions/2.7.5/bin/fastlane:23:in `load'
	31: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
	30: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	29: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	28: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	27: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	26: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	25: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	24: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	23: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	22: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	21: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	20: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	19: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	18: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	17: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	16: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	15: from Fastfile:120:in `block (2 levels) in parsing_binding'
	14: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	13: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	12: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	11: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	10: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 9: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 8: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 7: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
	 6: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/deliver/lib/deliver/runner.rb:55:in `run'
	 5: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/deliver/lib/deliver/runner.rb:127:in `verify_version'
	 4: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/spaceship/lib/spaceship/connect_api/models/app.rb:225:in `ensure_version!'
	 3: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/2.7.0/forwardable.rb:235:in `post_app_store_version'
	 2: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:910:in `post_app_store_version'
	 1: from /Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/spaceship/lib/spaceship/connect_api/api_client.rb:125:in `post'
/Users/roman/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.222.0/spaceship/lib/spaceship/connect_api/api_client.rb:223:in `handle_response': \e[31m[!] The provided entity includes a relationship with an invalid value - You cannot create a new version of the App in the current state. - /data/relationships/app\e[0m (Spaceship::UnexpectedResponse)
