### ISSUE TITLE
SFTP fails on state of remote directory

### ISSUE THREAD

**Issue by odrobnik** [fastlane/fastlane#19792]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am uploading the results from notarize to my SFTP server and that was working until my server was updated. Now the sftp action failed with this long error:

```
[22:03:15]: SFTP Uploader running...
1740[22:03:15]: upload...
1741[22:03:15]: Using custom port 222...
1742[22:03:15]: Logging in with username/password...
1743[22:03:15]: Uploading files...
1744[22:03:15]: Checking remote directory DIRECTORY
```

The lengthy log states that it happens on the stat! of the remote directory. The response there seems to be NIL and 

```
/usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/protocol/01/attributes.rb:109:in `parse_extended': [!] undefined method `times' for nil:NilClass (NoMethodError)
1786	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/protocol/01/attributes.rb:66:in `block in from_buffer'
1787	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/protocol/01/attributes.rb:63:in `each'
1788	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/protocol/01/attributes.rb:63:in `from_buffer'
1789	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/protocol/01/base.rb:49:in `parse_attrs_packet'
1790	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/protocol/base.rb:33:in `parse'
1791	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:83:in `respond_to'
1792	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:948:in `dispatch_request'
1793	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:911:in `when_channel_polled'
1794	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/channel.rb:323:in `process'
1795	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:250:in `block in ev_preprocess'
1796	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:540:in `each'
1797	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:540:in `each_channel'
1798	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:250:in `ev_preprocess'
1799	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/event_loop.rb:101:in `each'
1800	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/event_loop.rb:101:in `ev_preprocess'
1801	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/event_loop.rb:29:in `process'
1802	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:228:in `process'
1803	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:181:in `block in loop'
1804	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:181:in `loop'
1805	from /usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:181:in `loop'
1806	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
1807	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:72:in `wait'
1808	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:842:in `wait_for'
1809	from /usr/local/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:561:in `stat!'
1810	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-plugin-sftp-1.2.0/lib/fastlane/plugin/sftp/helper/sftp_helper.rb:126:in `remote_dir_exists?'
1811 ```

Could this somehow be caused by an incompatibility with the sftp server? that it disconnects the channel because it doesn’t work with the internal stat command?

**Comment by odrobnik** [comment]
We've narrowed it down to a bug in on version of ProFTP 1.3.6c. Using a later version fixed the issue. The current Ubuntu 20.04 LTS had the broken version and taking it from the desktop Ubuntu remedied the issue.

```
Proftpd STAT bug :
-------------------------

Ubuntu 18.04 LTS (bionic) :
proftpd-basic_1.3.5e-1_amd64.deb (WORKING)

Ubuntu 20.04 LTS (focal) :
proftpd-basic_1.3.6c-2_amd64.deb (BROKEN)

Ubuntu 21.04 (hirsute) :
proftpd-basic_1.3.7a+dfsg-12_all.deb (WORKING)
```
