### ISSUE TITLE
[Cocoapods] FrozenError - can't modify frozen String

### ISSUE THREAD

**Issue by 2Grey** [fastlane/fastlane#19880]
### Checklist

- [x] Updated fastlane to the latest version (2.203.0)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After upgrading to macOS Monterey fastlane fails to build a project that previously built successfully on macOS BigSur.

The project is built on Jenkins CI (MacMini) using _bundle_.

##### Command executed
`bundle exec pod install --repo-update`

##### Complete output when running fastlane, including the stack trace and command used

<details>
<div>
bundle exec pod install --repo-update
Updating local specs repositories
Analyzing dependencies
bundler: failed to load command: pod (/usr/local/bin/pod)
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:34:in 'force_encoding': can't modify frozen String (FrozenError)
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:34:in 'report'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in 'report_error'
from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in 'handle_exception'
from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in 'rescue in run'
from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in 'run'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in 'run'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in '<top (required)>'
from /usr/local/bin/pod:23:in 'load'
from /usr/local/bin/pod:23:in '<top (required)>'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in 'load'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in 'kernel_load'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in 'run'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in 'exec'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'run'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'invoke_command'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in 'dispatch'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in 'dispatch'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in 'start'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in 'start'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:48:in 'block in <top (required)>'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in 'with_friendly_errors'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:36:in '<top (required)>'
from /usr/local/bin/bundle:23:in 'load'
from /usr/local/bin/bundle:23:in '<main>'
/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:284:in 'raise_parser_error': [!] Found additional characters after parsing the root plist object (Nanaimo::Reader::ParseError)
#  -------------------------------------------
#  		};
#  /* End XCConfigurationList section */
22539>  	};
^
#  	rootObject = 784C4EA023015AC40050ED86 /* Project object */;
#  }
#  -------------------------------------------
from /Library/Ruby/Gems/2.6.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:110:in 'parse!'
from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/plist.rb:27:in 'read_from_path'
from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:211:in 'initialize_from_file'
from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:113:in 'open'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1190:in 'block (2 levels) in inspect_targets_to_integrate'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1189:in 'each'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1189:in 'block in inspect_targets_to_integrate'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in 'section'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1184:in 'inspect_targets_to_integrate'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:106:in 'analyze'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in 'analyze'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in 'block in resolve_dependencies'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in 'section'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in 'resolve_dependencies'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in 'install!'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in 'run'
from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in 'run'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in 'run'
from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in '<top (required)>'
from /usr/local/bin/pod:23:in 'load'
from /usr/local/bin/pod:23:in '<top (required)>'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in 'load'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in 'kernel_load'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in 'run'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in 'exec'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'run'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'invoke_command'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in 'dispatch'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in 'dispatch'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in 'start'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in 'start'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:48:in 'block in <top (required)>'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in 'with_friendly_errors'
from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:36:in '<top (required)>'
from /usr/local/bin/bundle:23:in 'load'
from /usr/local/bin/bundle:23:in '<main>'

Exit status of command 'bundle exec pod install --repo-update' was 1 instead of 0.
Updating local specs repositories
Analyzing dependencies
bundler: failed to load command: pod (/usr/local/bin/pod)
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:34:in 'force_encoding': can't modify frozen String (FrozenError)
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:34:in 'report'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in 'report_error'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in 'handle_exception'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in 'rescue in run'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in 'run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in 'run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in '<top (required)>'
	from /usr/local/bin/pod:23:in 'load'
	from /usr/local/bin/pod:23:in '<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in 'load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in 'kernel_load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in 'run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in 'exec'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'invoke_command'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in 'dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in 'dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in 'start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in 'start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:48:in 'block in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in 'with_friendly_errors'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:36:in '<top (required)>'
	from /usr/local/bin/bundle:23:in 'load'
	from /usr/local/bin/bundle:23:in '<main>'
/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:284:in 'raise_parser_error': [!] Found additional characters after parsing the root plist object (Nanaimo::Reader::ParseError)
     #  -------------------------------------------
     #  		};
     #  /* End XCConfigurationList section */
22539>  	};
        	 ^
     #  	rootObject = 784C4EA023015AC40050ED86 /* Project object */;
     #  }
     #  -------------------------------------------
	from /Library/Ruby/Gems/2.6.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:110:in 'parse!'
	from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/plist.rb:27:in 'read_from_path'
	from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:211:in 'initialize_from_file'
	from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:113:in 'open'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1190:in 'block (2 levels) in inspect_targets_to_integrate'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1189:in 'each'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1189:in 'block in inspect_targets_to_integrate'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in 'section'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1184:in 'inspect_targets_to_integrate'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:106:in 'analyze'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in 'analyze'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in 'block in resolve_dependencies'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in 'section'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in 'resolve_dependencies'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in 'install!'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in 'run'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in 'run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in 'run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in '<top (required)>'
	from /usr/local/bin/pod:23:in 'load'
	from /usr/local/bin/pod:23:in '<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in 'load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in 'kernel_load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in 'run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in 'exec'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'invoke_command'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in 'dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in 'dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in 'start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in 'start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:48:in 'block in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in 'with_friendly_errors'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:36:in '<top (required)>'
	from /usr/local/bin/bundle:23:in 'load'
	from /usr/local/bin/bundle:23:in '<main>'
</div>
</details>

### Environment

<details>
<summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.2                                                           |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.35.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.2 (21D49)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.2.1                                                         |
| Swift Version               | 5.5.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.203.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.5        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| unicode-display_width           | 1.8.0        |
| excon                           | 0.90.0       |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.9.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.1        |
| rubyzip                         | 2.3.2        |
| bundler                         | 2.3.6        |
| jwt                             | 2.3.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.11.0       |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.551.0      |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.125.5      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.3      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2022-01-31**
</details>

**Comment by 2Grey** [comment]
Not relevant
