### ISSUE TITLE
latest_testflight_build_number is failing with "[!] Could not find an app on App Store Connect with app_identifier: "

### ISSUE THREAD

**Issue by ramnac** [fastlane/fastlane#19898]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
just noticed all our builds got failed and the error was due to latest_testflight_build_number

fastlane finished with errors

[!] Could not find an app on App Store Connect with app_identifier: 

##### Command executed
latest_testflight_build_number

##### Complete output when running fastlane, including the stack trace and command used

 iOS % fastlane -v                                        
fastlane installation at path:
/Users/ram/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.204.0/bin/fastlane

[✔] 🚀 
fastlane 2.204.0
 % fastlane run latest_testflight_build_number
[✔] 🚀 
[12:30:58]: fastlane detected a Gemfile in the current directory
[12:30:58]: However, it seems like you didn't use `bundle exec`
[12:30:58]: To launch fastlane faster, please use
[12:30:58]: 
[12:30:58]: $ bundle exec fastlane run latest_testflight_build_number
[12:30:58]: 
[12:30:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+------------------------------+---------+--------------+
|                     Used plugins                      |
+------------------------------+---------+--------------+
| Plugin                       | Version | Action       |
+------------------------------+---------+--------------+
| fastlane-plugin-xchtmlreport | 0.1.1   | xchtmlreport |
+------------------------------+---------+--------------+

[12:30:58]: --------------------------------------------
[12:30:58]: --- Step: latest_testflight_build_number ---
[12:30:58]: --------------------------------------------
[12:30:58]: To not be asked about this value, you can specify it using 'username'
[12:30:58]: Your Apple ID Username: 
[12:34:54]: Login to App Store Connect ()

Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager

Password (for ): 
Two-factor Authentication (6 digits code) is enabled for account 
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship_2fa_sms_default_phone_number)

Please enter the 6 digit code:
864071
Requesting session...
Multiple App Store Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  
1
[12:35:35]: Login successful
[12:35:35]: To not be asked about this value, you can specify it using 'app_identifier'
[12:35:35]: The bundle identifier of your app: 

### **[!] Could not find an app on App Store Connect with app_identifier:**

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 12.0.1                                          |
| Ruby                        | 3.0.1                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.30.1 (Apple Git-130)              |
| Installation Source         | ~/.rbenv/versions/3.0.1/bin/fastlane            |
| Host                        | macOS 12.0.1 (21A559)                           |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.1/lib                     |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode13.1.app/Contents/Developer/ |
| Xcode Version               | 13.1                                            |
| Swift Version               | 5.5.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_NZ.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                       | Version | Update-Status |
| ---------------------------- | ------- | ------------- |
| fastlane-plugin-xchtmlreport | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.5        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| unicode-display_width           | 1.8.0        |
| excon                           | 0.90.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.1        |
| rubyzip                         | 2.3.2        |
| bundler                         | 2.2.17       |
| jwt                             | 2.3.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.11.0       |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.551.0      |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.125.6      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.3      |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| net-smtp                        | 0.2.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| nokogiri                        | 1.13.1       |
| racc                            | 1.6.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
| fastlane-plugin-xchtmlreport    | 0.1.1        |
</details>

*generated on:* **2022-02-03**
</details>

**Comment by andrewclaus** [comment]
Seems like I might be having a similar issue with the Pilot task,

'''
2022-02-02T23:48:53.6037290Z ERROR [2022-02-02 23:48:53.48]: [31mCouldn't find app 'XXX' on the account of 'XXX' on App Store Connect[0m
'''

I double checked the bundle ID has not changed anywhere (it has been working just fine).

Stacktrace output on the failure:
```
2022-02-02T23:48:53.6051770Z /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Couldn't find app 'XXX' on the account of 'XXX' on App Store Connect\e[0m (FastlaneCore::Interface::FastlaneError)
2022-02-02T23:48:53.6053640Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2022-02-02T23:48:53.6055080Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/pilot/lib/pilot/manager.rb:65:in `fetch_app_id'
2022-02-02T23:48:53.6056800Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/pilot/lib/pilot/manager.rb:43:in `app'
2022-02-02T23:48:53.6058290Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/pilot/lib/pilot/build_manager.rb:123:in `wait_for_build_processing_to_be_complete'
2022-02-02T23:48:53.6059770Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:31:in `run'
2022-02-02T23:48:53.6061280Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
2022-02-02T23:48:53.6062730Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
2022-02-02T23:48:53.6064230Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
2022-02-02T23:48:53.6065590Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
2022-02-02T23:48:53.6067000Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
2022-02-02T23:48:53.6068390Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
2022-02-02T23:48:53.6069860Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2022-02-02T23:48:53.6071130Z 	from Fastfile:169:in `block (2 levels) in parsing_binding'
2022-02-02T23:48:53.6072370Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/lane.rb:33:in `call'
2022-02-02T23:48:53.6073750Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
2022-02-02T23:48:53.6075420Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
2022-02-02T23:48:53.6076820Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
2022-02-02T23:48:53.6078190Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
2022-02-02T23:48:53.6079650Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
2022-02-02T23:48:53.6081110Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
2022-02-02T23:48:53.6082520Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2022-02-02T23:48:53.6083790Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2022-02-02T23:48:53.6085180Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2022-02-02T23:48:53.6086590Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2022-02-02T23:48:53.6087980Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2022-02-02T23:48:53.6089320Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
2022-02-02T23:48:53.6090990Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
2022-02-02T23:48:53.6092410Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
2022-02-02T23:48:53.6093810Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/bin/fastlane:23:in `<top (required)>'
2022-02-02T23:48:53.6094980Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
2022-02-02T23:48:53.6096180Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<top (required)>'
2022-02-02T23:48:53.6097750Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `load'
2022-02-02T23:48:53.6099180Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
2022-02-02T23:48:53.6100440Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in `run'
2022-02-02T23:48:53.6101740Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in `exec'
2022-02-02T23:48:53.6103030Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2022-02-02T23:48:53.6104470Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
2022-02-02T23:48:53.6105830Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
2022-02-02T23:48:53.6107280Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
2022-02-02T23:48:53.6108600Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
2022-02-02T23:48:53.6110020Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
2022-02-02T23:48:53.6111280Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
2022-02-02T23:48:53.6112680Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
2022-02-02T23:48:53.6113980Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
2022-02-02T23:48:53.6115180Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `load'
2022-02-02T23:48:53.6116270Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `<main>'
2022-02-02T23:48:53.6118460Z /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Couldn't find app 'XXX' on the account of 'XXX' on App Store Connect (FastlaneCore::Interface::FastlaneError)
2022-02-02T23:48:53.6120280Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2022-02-02T23:48:53.6121700Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/pilot/lib/pilot/manager.rb:65:in `fetch_app_id'
2022-02-02T23:48:53.6123000Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/pilot/lib/pilot/manager.rb:43:in `app'
2022-02-02T23:48:53.6124470Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/pilot/lib/pilot/build_manager.rb:123:in `wait_for_build_processing_to_be_complete'
2022-02-02T23:48:53.6125930Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:31:in `run'
2022-02-02T23:48:53.6127470Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
2022-02-02T23:48:53.6128980Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
2022-02-02T23:48:53.6130430Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
2022-02-02T23:48:53.6131830Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
2022-02-02T23:48:53.6133280Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
2022-02-02T23:48:53.6134730Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
2022-02-02T23:48:53.6136140Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2022-02-02T23:48:53.6137420Z 	from Fastfile:169:in `block (2 levels) in parsing_binding'
2022-02-02T23:48:53.6139000Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/lane.rb:33:in `call'
2022-02-02T23:48:53.6140420Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
2022-02-02T23:48:53.6141760Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
2022-02-02T23:48:53.6143130Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
2022-02-02T23:48:53.6144490Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
2022-02-02T23:48:53.6145940Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
2022-02-02T23:48:53.6147390Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
2022-02-02T23:48:53.6148820Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2022-02-02T23:48:53.6150110Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2022-02-02T23:48:53.6151480Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2022-02-02T23:48:53.6152880Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2022-02-02T23:48:53.6154290Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2022-02-02T23:48:53.6155630Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
2022-02-02T23:48:53.6157080Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
2022-02-02T23:48:53.6158820Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
2022-02-02T23:48:53.6160250Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/bin/fastlane:23:in `<top (required)>'
2022-02-02T23:48:53.6161420Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
2022-02-02T23:48:53.6162610Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<top (required)>'
2022-02-02T23:48:53.6163820Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `load'
2022-02-02T23:48:53.6165140Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
2022-02-02T23:48:53.6166390Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in `run'
2022-02-02T23:48:53.6167640Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in `exec'
2022-02-02T23:48:53.6168950Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2022-02-02T23:48:53.6170990Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
2022-02-02T23:48:53.6172460Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
2022-02-02T23:48:53.6173860Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
2022-02-02T23:48:53.6175170Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
2022-02-02T23:48:53.6176520Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
2022-02-02T23:48:53.6177770Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
2022-02-02T23:48:53.6179170Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
2022-02-02T23:48:53.6180650Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
2022-02-02T23:48:53.6182300Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `load'
2022-02-02T23:48:53.6183390Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `<main>'
```

**Comment by KieranHa** [comment]
I am getting the same error as of ~15 hours ago, tried adding team_id and itc_provider to pilot step but no luck

**Comment by christopherdcunha** [comment]
I get this too. I was able to work around this by patching `spaceship/lib/spaceship/connect_api/models/app.rb`

Looks like the filter that is sent to TestFlight doesn't work for some reason.

```
$ diff -u /Users/.../spaceship/lib/spaceship/connect_api/models/app.rb{.bk,}
```
```diff
--- /Users/.../spaceship/lib/spaceship/connect_api/models/app.rb.bk	2022-02-03 00:00:11.000000000 +0000
+++ /Users/.../spaceship/lib/spaceship/connect_api/models/app.rb	2022-02-02 23:59:11.000000000 +0000
@@ -78,7 +78,7 @@

       def self.find(bundle_id, client: nil)
         client ||= Spaceship::ConnectAPI
-        return all(client: client, filter: { bundleId: bundle_id }).find do |app|
+        return all(client: client).find do |app|
           app.bundle_id == bundle_id
         end
       end
```

**Comment by ramnac** [comment]
Thank you @christopherdcunha 

Just adding - this change will cause 2 failures 

rspec ./spaceship/spec/connect_api/models/app_spec.rb:84 # Spaceship::ConnectAPI::App App object finds app by bundle id
rspec ./spaceship/spec/connect_api/models/app_spec.rb:89 # Spaceship::ConnectAPI::App App object creates beta group

I think Apple has changed some key name possibly / how the filtering should work. Weird. 

Will create a branch with your fix for the time being.

**Comment by ramnac** [comment]
For now - you can use my own repo (until the fix gets merged to fastlane)

in your gemfile

gem "fastlane", :git => "https://github.com/ramnac/fastlane", :branch => "fix-tesflight-latest-build-number-issue"

**Comment by SolorzanoJose** [comment]
Experiencing the same issue.

**Comment by joshdholtz** [comment]
✨ OFFICIAL UPDATE

Bumping and making a release now. `2.204.1` should be out in less than an hour.

**Comment by joshdholtz** [comment]
✨ OFFICIAL UPDATE

I've created a radar for it (FB9876626) and I sent it over to someone at Apple so that it can hopefully get bumped up in priority.

**Comment by KieranHa** [comment]
@joshdholtz you are a beautiful man sir

**Comment by joshdholtz** [comment]
If anybody could verify that this _does_ work for you that would be ❤️ Thanks!

**Comment by andrewclaus** [comment]
> If anybody could verify that this _does_ work for you that would be ❤️ Thanks!

Successful here!

**Comment by KieranHa** [comment]
@joshdholtz silly question, will this be available to update via brew soon as well?

**Comment by joshdholtz** [comment]
Not a silly question at all!

It will be soon after https://github.com/Homebrew/homebrew-core/pull/94377 gets merged but it's out of my hands 🤷‍♂️ The homebrew team is usually pretty quick at getting these merged in though! ❤️

**Comment by joshdholtz** [comment]
Just released `2.204.2` which revert the changes. App Store Connect API is back to working 100%

Please update to newest version as soon as you can! It will be more performant for everyone 😊 Homebrew version as been submitted and it just waiting for approval

**Comment by JimDabell** [comment]
We have just started seeing this error crop up again – could this issue be reopened?

**Comment by edodusi** [comment]
Same issue here, fastlane `2.204.3`

**Comment by minhnguyenvan95** [comment]
same issue here

**Comment by Arceoavs** [comment]
I have the same issue right now. This is really bad for me right now, how can I fix it (preliminarily at least)?

**Comment by lkravchuk** [comment]
Same issue, version `2.205.1`

**Comment by whalemare** [comment]
Same issue, version `2.205.0`

**Comment by arnoorani** [comment]
Is anyone facing this issue again?

**Comment by EmDee** [comment]
We're seeing the same error right now. I've created a new issue, as discussing this in an old, closed issue probably has no visibility. Maybe @joshdholtz can take a look at the problem again: https://github.com/fastlane/fastlane/issues/20368
