### ISSUE TITLE
I am using Azure Devops to Deploy IOS Application on Test-flight During build i received this error 

### ISSUE THREAD

**Issue by malikfayaz1** [fastlane/fastlane#19937]
##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1

Please tell me what is this issue for and how to solve it we search a lot but no get any information

**Comment by malikfayaz1** [comment]
2022-02-07T13:16:56.4536850Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
2022-02-07T13:16:56.4538420Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<main>'
2022-02-07T13:16:56.4542610Z /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/token.rb:71:in `initialize': string contains null byte (ArgumentError)
2022-02-07T13:16:56.4545040Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/token.rb:71:in `new'
2022-02-07T13:16:56.4548000Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/token.rb:71:in `create'
2022-02-07T13:16:56.4553060Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/token.rb:49:in `from_json_file'
2022-02-07T13:16:56.4557760Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/token.rb:33:in `from'
2022-02-07T13:16:56.4563430Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/pilot/lib/pilot/manager.rb:23:in `login'
2022-02-07T13:16:56.4565480Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/pilot/lib/pilot/manager.rb:19:in `start'
2022-02-07T13:16:56.4570790Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/pilot/lib/pilot/build_manager.rb:17:in `upload'
2022-02-07T13:16:56.4573200Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
2022-02-07T13:16:56.4575150Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2022-02-07T13:16:56.4578640Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2022-02-07T13:16:56.4581150Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2022-02-07T13:16:56.4584070Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2022-02-07T13:16:56.4586540Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2022-02-07T13:16:56.4588340Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/pilot/lib/pilot/commands_generator.rb:167:in `run'
2022-02-07T13:16:56.4590910Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/pilot/lib/pilot/commands_generator.rb:19:in `start'
2022-02-07T13:16:56.4592230Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
2022-02-07T13:16:56.4593600Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/bin/fastlane:23:in `<top (required)>'
2022-02-07T13:16:56.4594630Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
2022-02-07T13:16:56.4595530Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<main>'
2022-02-07T13:16:56.4639000Z ##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
2022-02-07T13:16:56.4661300Z ##[section]Finishing: Publish to the App Store TestFlight track

**Comment by max-ott** [comment]
Please edit your issue or open a new one following our issue template so our community will be able to help you!

**Comment by EmilAlipiev** [comment]
what was the solution here? Did you find the reason? I get the same issue

**Comment by malikfayaz1** [comment]
Change the build number

**Comment by sadanandhexalitcs** [comment]
Has anyone found the solution ?

**Comment by EmilAlipiev** [comment]
@sadanandhexalitcs still not working today for me. looks like that tool has a bug for some settings.

**Comment by sadanandhexalitcs** [comment]
@EmilAlipiev Please share your YML file

**Comment by EmilAlipiev** [comment]
@sadanandhexalitcs in my case I am getting this error

`ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'production' for key 'aps-environment'`

But this shouldnt be an error to define aps-environment in Entitlements. Xcode is compiling, packing and publishing just fine witht it. Why do I get this error in Fastlane?
