### ISSUE TITLE
Getting an error - couldn't find login name -- expanding ~

### ISSUE THREAD

**Issue by zivbaz** [fastlane/fastlane#20025]
### Issue Description
Try to use the `firebase_app_distribution plugin` to distribute APK to firebase.
Getting an error when the lane is executed.
This process was working on a different VM in the past.

I'm running:
```
gem install bundler
sudo bundle install
bundle exec fastlane createapk --verbose
```

The lane configuration:
```
lane :createapk do
  firebase_app_distribution( #https://github.com/fastlane/fastlane-plugin-firebase_app_distribution
    firebase_cli_token: ENV['FIREBASE_TOKEN'],
    android_artifact_type: 'APK',
    android_artifact_path: 'build/Android/Android.apk',
    app: "<ID>",
    groups: 'qa, unitydev, product'
  )
end
```
Commands output:
<details>
Successfully installed bundler-2.3.8
Parsing documentation for bundler-2.3.8
Installing ri documentation for bundler-2.3.8
Done installing documentation for bundler after 0 seconds
1 gem installed
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Fetching rake 13.0.6
Installing rake 13.0.6
Fetching minitest 5.14.4
Fetching zeitwerk 2.5.1
Using httpclient 2.8.3
Using rexml 3.2.5
Fetching concurrent-ruby 1.1.9
Using public_suffix 4.0.6
Fetching json 2.6.1
Using artifactory 3.0.15
Using atomos 0.1.3
Using aws-eventstream 1.2.0
Fetching aws-partitions 1.554.0
Using jmespath 1.6.0
Using babosa 1.0.4
Using bundler 2.3.8
Fetching claide 1.0.3
Fetching fuzzy_match 2.0.4
Fetching nap 1.1.0
Installing claide 1.0.3
Installing zeitwerk 2.5.1
Installing aws-partitions 1.554.0
Installing minitest 5.14.4
Installing json 2.6.1 with native extensions
Installing fuzzy_match 2.0.4
Installing nap 1.1.0
Fetching netrc 0.11.0
Fetching ffi 1.15.4
Fetching cocoapods-deintegrate 1.0.5
Installing concurrent-ruby 1.1.9
Installing netrc 0.11.0
Fetching cocoapods-downloader 1.5.1
Installing cocoapods-deintegrate 1.0.5
Fetching cocoapods-search 1.0.1
Fetching cocoapods-try 1.2.0
Installing cocoapods-downloader 1.5.1
Using colored2 3.1.2
Fetching escape 0.0.4
Installing cocoapods-search 1.0.1
Fetching fourflusher 2.3.1
Installing escape 0.0.4
Installing cocoapods-try 1.2.0
Installing fourflusher 2.3.1
Installing ffi 1.15.4 with native extensions
Using gh_inspector 1.1.3
Fetching molinillo 0.8.0
Fetching ruby-macho 2.5.1
Installing molinillo 0.8.0
Installing ruby-macho 2.5.1
Using nanaimo 0.3.0
Using colored 1.2
Using highline 2.0.3
Using declarative 0.0.20
Using digest-crc 0.6.4
Using dotenv 2.7.6
Using unf_ext 0.0.8
Using emoji_regex 3.2.3
Using excon 0.91.0
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using faraday-httpclient 1.0.1
Using multipart-post 2.0.0
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using faraday-retry 1.0.3
Using ruby2_keywords 0.0.5
Using fastimage 2.2.6
Using jwt 2.3.0
Using memoist 0.16.2
Using multi_json 1.15.0
Using os 1.1.4
Using mini_mime 1.1.2
Using trailblazer-option 0.1.2
Using uber 0.1.0
Using retriable 3.1.2
Fetching webrick 1.7.0
Using mini_magick 4.11.0
Using google-cloud-errors 1.2.0
Using naturally 2.2.1
Using optparse 0.1.1
Using plist 3.6.0
Using rubyzip 2.3.2
Using security 0.1.3
Using terminal-notifier 2.0.0
Using unicode-display_width 1.8.0
Using tty-screen 0.8.1
Using tty-cursor 0.7.1
Using word_wrap 1.0.0
Using rouge 2.0.7
Fetching fastlane-plugin-firebase_app_distribution 0.3.2
Using addressable 2.8.0
Using CFPropertyList 3.0.5
Using aws-sigv4 1.4.0
Fetching cocoapods-plugins 1.0.0
Fetching cocoapods-trunk 1.6.0
Installing webrick 1.7.0
Installing cocoapods-plugins 1.0.0
Installing fastlane-plugin-firebase_app_distribution 0.3.2
Using commander 4.6.0
Using unf 0.1.4
Using faraday-multipart 1.0.3
Using representable 3.1.1
Using terminal-table 1.8.0
Using tty-spinner 0.9.3
Using xcpretty 0.3.0
Using xcodeproj 1.21.0
Using simctl 1.6.8
Fetching aws-sdk-core 3.1[26](https://github.com/papayagaming/PapayaUnity/runs/5378601892?check_suite_focus=true#step:4:26).2
Using domain_name 0.5.20190701
Using faraday 1.10.0
Using xcpretty-travis-formatter 1.0.1
Using http-cookie 1.0.4
Using faraday_middleware 1.2.0
Fetching signet 0.16.0
Using google-cloud-env 1.5.0
Using faraday-cookie_jar 0.0.7
Using google-cloud-core 1.6.0
Installing signet 0.16.0
Installing cocoapods-trunk 1.6.0
Fetching googleauth 1.1.1
Fetching i18n 1.8.11
Fetching tzinfo 2.0.4
Installing googleauth 1.1.1
Installing i18n 1.8.11
Using google-apis-core 0.4.2
Using google-apis-iamcredentials_v1 0.10.0
Using google-apis-androidpublisher_v3 0.16.0
Using google-apis-playcustomapp_v1 0.7.0
Using google-apis-storage_v1 0.11.0
Using google-cloud-storage 1.36.1
Installing tzinfo 2.0.4
Installing aws-sdk-core 3.126.2
Fetching activesupport 6.1.4.1
Installing activesupport 6.1.4.1
Fetching aws-sdk-kms 1.54.0
Installing aws-sdk-kms 1.54.0
Fetching aws-sdk-s3 1.112.0
Installing aws-sdk-s3 1.112.0
Fetching ethon 0.15.0
Installing ethon 0.15.0
Fetching typhoeus 1.4.0
Installing typhoeus 1.4.0
Fetching algoliasearch 1.[27](https://github.com/papayagaming/PapayaUnity/runs/5378601892?check_suite_focus=true#step:4:27).5
Fetching fastlane 2.204.3
Installing algoliasearch 1.27.5
Fetching cocoapods-core 1.11.2
Installing fastlane 2.204.3
Installing cocoapods-core 1.11.2
Fetching cocoapods 1.11.2
Installing cocoapods 1.11.2
Fetching xcode-install 2.8.0
Installing xcode-install 2.8.0
Bundle complete! 4 Gemfile dependencies, [117](https://github.com/papayagaming/PapayaUnity/runs/5378601892?check_suite_focus=true#step:4:117) gems now installed.
Use bundle info [gemname] to see where a bundled gem is installed.
Post-install message from algoliasearch:
A new major version is available for Algolia! Please now use the https://rubygems.org/gems/algolia gem to get the latest features.
</details>

Full Log:
<details>
/var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/module.rb:27:in `home': \e[31m[!] couldn't find login name -- expanding `~'\e[0m (ArgumentError)
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/module.rb:27:in `fastlane_user_dir'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:59:in `should_show_message?'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:22:in `action_launched'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:115:in `run!'
Run `fastlane env` to append the fastlane environment to your issue
DEBUG [2022-03-01 16:24:10.71]: All plugins are up to date
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
/var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/module.rb:27:in `home': couldn't find login name -- expanding `~' (ArgumentError)
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/module.rb:27:in `fastlane_user_dir'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:59:in `should_show_message?'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:22:in `action_launched'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:115:in `run!'
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /var/lib/gems/2.7.0/gems/fastlane-2.204.3/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Error: Process completed with exit code 1.

</details>

I managed to run `fastlane env` after ssh to the VM (Fastlane env shows the same error when running in the CI) 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | debian_based bullseye/sid                                      |
| Ruby                        | 2.7.0                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.25.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Ubuntu 20.04.3 LTS debian_based bullseye/sid (5.11.0-1028-aws) |
| Ruby Lib Dir                | /usr/lib                                                       |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
desc "Run only for IOS lanes and before all lanes"
before_all do |lane|
  if [:createipa].include?(lane)
    xcversion(version: '13.0') # What Xcode to use - http://docs.fastlane.tools/actions/xcversion/#xcversion
    cocoapods( #http://docs.fastlane.tools/actions/cocoapods/#cocoapods
      repo_update: true
    )
    reset_simulator_contents #http://docs.fastlane.tools/actions/reset_simulator_contents/#reset_simulator_contents

    if ENV['PRE_RLEASE'] == 'true' # What certificate to use - prod or dev
      _keychain_name = 'ios-build-prod.keychain-db'
      File.write('../ios-build.p12', Base64.decode64(ENV['IOS_PRODUCTION_P12'])) #P12 certificate
    else
      _keychain_name = 'ios-build-dev.keychain-db'
      File.write('../ios-build.p12', Base64.decode64(ENV['IOS_DEVELOPMENT_P12'])) #P12 certificate
    end

    if(!File.exist?("/Users/runner/Library/Keychains/#{_keychain_name}"))
        keychain_password = ENV['KEYCHAIN_PASS']
        create_keychain( #https://docs.fastlane.tools/actions/create_keychain/
            name: _keychain_name,
            password: keychain_password,
            default_keychain: true,
            unlock: true,
            timeout: 0
        )
        import_certificate( #http://docs.fastlane.tools/actions/import_certificate/#import_certificate
          certificate_path: 'ios-build.p12',
          keychain_name: _keychain_name,
          keychain_path: _keychain_name,
          keychain_password: keychain_password,
          log_output: true
        )
      end
    unlock_keychain( #http://docs.fastlane.tools/actions/unlock_keychain/#unlock_keychain
      path: "/Users/runner/Library/Keychains/#{_keychain_name}",
      password: ENV['KEYCHAIN_PASS']
    )
  end
end

desc "Upload APK to Firebase"
lane :createapk do
  firebase_app_distribution( #https://github.com/fastlane/fastlane-plugin-firebase_app_distribution
    firebase_cli_token: ENV['FIREBASE_TOKEN'],
    android_artifact_type: 'APK',
    android_artifact_path: 'build/Android/Android.apk',
    app: "1:<>:android:#{ENV['ANDROID_APP_ID']}",
    groups: 'qa, unitydev, product'
  )
end

desc "Build and deploy IPA to Firebase/testflight"
lane :createipa do
  if ENV['PRE_RLEASE'] == 'true' # What provisioning profile to use - prod or dev
    _provisioning_profile = "mobileprovisions/#{ENV['GAME_NAME']}_2022.mobileprovision"
    _code_sign_identity = 'Apple Distribution: Papaya Gaming LTD (L7W27DVCCQ)'
    _method = 'app-store'
    _configuration = 'Release'
  else
    _provisioning_profile = "mobileprovisions/#{ENV['GAME_NAME']}_CI_CD.mobileprovision"
    _code_sign_identity = 'Apple Development: Ziv Rechnitser (2VVR69CSN3)'
    _method = 'development'
    _configuration = 'Debug'
  end
  install_provisioning_profile( #http://docs.fastlane.tools/actions/install_provisioning_profile/#install_provisioning_profile
    path: _provisioning_profile
  )
  update_code_signing_settings( #http://docs.fastlane.tools/actions/update_code_signing_settings/#update_code_signing_settings
    path: './Unity-iPhone.xcodeproj',
    use_automatic_signing: false,
    code_sign_identity: _code_sign_identity,
    targets: 'Unity-iPhone',
    bundle_identifier: "com.papaya.#{ENV['GAME_NAME']}"
  )
  update_project_provisioning( #http://docs.fastlane.tools/actions/update_project_provisioning/#update_project_provisioning
    profile: _provisioning_profile,
    xcodeproj: './Unity-iPhone.xcodeproj',
    target_filter: 'Unity-iPhone'
  )
  increment_build_number( #http://docs.fastlane.tools/actions/increment_build_number/#increment_build_number
    build_number: ENV['BUILD_NUMBER'],
    xcodeproj: "./Unity-iPhone.xcodeproj"
  )
  gym( #http://docs.fastlane.tools/actions/gym/#gym
    scheme: 'Unity-iPhone',
    workspace: './Unity-iPhone.xcworkspace',
    clean: true,
    archive_path: "./archive",
    include_symbols: true,
    configuration: _configuration,
    export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
    export_options: {
      method: _method,
      uploadSymbols: true
    }
  )
  if ENV['PRE_RLEASE'] == 'true' # Publish to Firebase (dev) or Testflight (prod)
    File.write('../AuthKey.p8', Base64.decode64(ENV['APP_STOTE_KEY']))
    app_store_connect_api_key( #http://docs.fastlane.tools/actions/app_store_connect_api_key/#app_store_connect_api_key
      key_id: "<>",
      issuer_id: "<>",
      key_filepath: "./AuthKey.p8"
    )
    upload_to_testflight( #http://docs.fastlane.tools/actions/upload_to_testflight/#upload_to_testflight
      ipa: "#{ENV['IPA_NAME']}.ipa",
      skip_waiting_for_build_processing: true,
      changelog: ENV['PAPAYA_KIT']
    )
  else
    firebase_app_distribution( #https://github.com/fastlane/fastlane-plugin-firebase_app_distribution
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      ipa_path: "#{ENV['IPA_NAME']}.ipa",
      app: "1:<>:ios:#{ENV['IOS_APP_ID']}",
      groups: 'qa, unitydev, product'
    )
    upload_symbols_to_crashlytics( #http://docs.fastlane.tools/actions/upload_symbols_to_crashlytics/#upload_symbols_to_crashlytics
      dsym_path: "#{ENV['DSYM_PATH']}.app.dSYM.zip",
      gsp_path: "#{ENV['GSP_PATH']}/Assets/GoogleService-Info.plist"
    )
  end
end

desc "Prepare new version for submission - AppStore"
lane :new_version do #https://docs.fastlane.tools/actions/upload_to_app_store/
  File.write('../AuthKey.p8', Base64.decode64(ENV['APP_STOTE_KEY']))
  app_store_connect_api_key( #http://docs.fastlane.tools/actions/app_store_connect_api_key/#app_store_connect_api_key
      key_id: "<>",
      issuer_id: "<>,
      key_filepath: "./AuthKey.p8"
  )
  deliver(
    app_identifier: "com.papaya.#{ENV['GAME_NAME']}",
    force: true,
    app_version: ENV['VERSION'],
    skip_screenshots: true,
    run_precheck_before_submit: false, #Precheck cannot check In-app purchases with the App Store Connect API Key (yet)
    metadata_path: "./fastlane/#{ENV['GAME_NAME']}/metadata",
    phased_release: true,
    automatic_release: false,
    reset_ratings: false
  )
end


```
</details>

<details><summary>`./Appfile`</summary>

```ruby
team_id "<>"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.5        |
| concurrent-ruby                           | 1.1.9        |
| i18n                                      | 1.8.11       |
| minitest                                  | 5.14.4       |
| tzinfo                                    | 2.0.4        |
| zeitwerk                                  | 2.5.1        |
| activesupport                             | 6.1.4.1      |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.6.1        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.554.0      |
| aws-sigv4                                 | 1.4.0        |
| jmespath                                  | 1.6.0        |
| aws-sdk-core                              | 3.126.2      |
| aws-sdk-kms                               | 1.54.0       |
| aws-sdk-s3                                | 1.112.0      |
| babosa                                    | 1.0.4        |
| bundler                                   | 2.3.8        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.4       |
| ethon                                     | 0.15.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.11.2       |
| cocoapods-deintegrate                     | 1.0.5        |
| cocoapods-downloader                      | 1.5.1        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.1        |
| cocoapods-trunk                           | 1.6.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.8.0        |
| ruby-macho                                | 2.5.1        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.21.0       |
| cocoapods                                 | 1.11.2       |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.4        |
| unf_ext                                   | 0.0.8        |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.91.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| multipart-post                            | 2.0.0        |
| faraday-multipart                         | 1.0.3        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.0       |
| http-cookie                               | 1.0.4        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.6        |
| jwt                                       | 2.3.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.16.0       |
| googleauth                                | 1.1.1        |
| mini_mime                                 | 1.1.2        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.4.2        |
| google-apis-androidpublisher_v3           | 0.16.0       |
| google-apis-playcustomapp_v1              | 0.7.0        |
| google-apis-iamcredentials_v1             | 0.10.0       |
| google-apis-storage_v1                    | 0.11.0       |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.36.1       |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.3.2        |
| xcode-install                             | 2.8.0        |
</details>

*generated on:* **2022-03-02**
</details>

**Comment by zivbaz** [comment]
I needed to an env var ${HOME}:~/ to solve the issue
