### ISSUE TITLE
App store submit for review fails with 'Version is not ready to be submitted yet'

### ISSUE THREAD

**Issue by rohanp-91** [fastlane/fastlane#20065]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Using the latest version of fastlane, the submit for review fails with 'Version is not ready to be submitted yet'. Below is the complete error log:

##### Complete output when running fastlane, including the stack trace and command used

`2022-02-04T03:00:28.0332510Z /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/api_client.rb:199:in 'handle_response': [!] appStoreVersions with id 'e0207fc5-203a-4902-9f63-9abeffcb29e1' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why. (Spaceship::UnexpectedResponse)
2022-02-04T03:00:28.0335240Z The request cannot be fulfilled because of the state of another resource. - Version is not ready to be submitted yet, please try again later.
2022-02-04T03:00:28.0336490Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/api_client.rb:135:in 'patch'
2022-02-04T03:00:28.0337730Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:1173:in 'patch_review_submission'
2022-02-04T03:00:28.0338880Z 	from /usr/local/Cellar/ruby@2.7/2.7.5/lib/ruby/2.7.0/forwardable.rb:235:in 'patch_review_submission'
2022-02-04T03:00:28.0340090Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/models/review_submission.rb:55:in 'submit_for_review'
2022-02-04T03:00:28.0341330Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/deliver/lib/deliver/submit_for_review.rb:50:in 'create_review_submission'
2022-02-04T03:00:28.0342480Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/deliver/lib/deliver/submit_for_review.rb:26:in 'submit!'
2022-02-04T03:00:28.0343590Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/deliver/lib/deliver/runner.rb:223:in 'submit_for_review'
2022-02-04T03:00:28.0344660Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/deliver/lib/deliver/runner.rb:65:in 'run'
2022-02-04T03:00:28.0345780Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/deliver/lib/deliver/commands_generator.rb:82:in 'block (2 levels) in run'
2022-02-04T03:00:28.0346870Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in 'call'
2022-02-04T03:00:28.0347930Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in 'run'
2022-02-04T03:00:28.0349000Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in 'run_active_command'
2022-02-04T03:00:28.0350130Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in 'run!'
2022-02-04T03:00:28.0351250Z 	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in 'run!'
2022-02-04T03:00:28.0352330Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/deliver/lib/deliver/commands_generator.rb:187:in 'run'
2022-02-04T03:00:28.0353440Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/deliver/lib/deliver/commands_generator.rb:18:in 'start'
2022-02-04T03:00:28.0354570Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in 'take_off'
2022-02-04T03:00:28.0355660Z 	from /Users/runner/.gem-cache/gems/fastlane-2.204.2/bin/fastlane:23:in '<top (required)>'
2022-02-04T03:00:28.0356590Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in 'load'
2022-02-04T03:00:28.0357450Z 	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in '<main>'`

##### Command executed

`fastlane deliver --force --precheck_include_in_app_purchases false --api_key_path /Users/runner/work/_temp/api_key***.json -a <app_id> -i app.ipa -j ios -m ios-release/metadata --skip_screenshots true --submit_for_review true --automatic_release false`

**Comment by Emmitt121** [comment]
I got the same error today. No more details, just some general error. Unable to finish submission.

**Comment by arefinsami** [comment]
I'm hitting the same issue-

`appStoreVersions with id '<guid>' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why. The request cannot be fulfilled because of the state of another resource. - Version is not ready to be submitted yet, please try again later.`

**Comment by rohanp-91** [comment]
Any updates on this?

**Comment by 404pilot** [comment]
> Version is not ready to be submitted yet

I think on this [line](https://github.com/fastlane/fastlane/blob/acb7d84e7ac068e424da231c2eca39fe2ec7297d/deliver/lib/deliver/submit_for_review.rb#L50), apple will check if the state of the editing app version is `READY_FOR_REVIEW` or not.

Need to add a small wait until the state becomes `READY_FOR_REVIEW` from `PREPARE_FOR_SUBMISSION`

**Comment by robmaceachern** [comment]
We've hit this problem too.

**Comment by lingzlu** [comment]
Any workaround for this yet?

**Comment by rsortiz** [comment]
I'm having the same issue here, any update?

**Comment by itsschubert** [comment]
I'm having the same issue, using Azure Devops pipeline and Fastlane

**Comment by hermannkuschke** [comment]
We are experiencing this issue using Azure DevOps pipelines and Fastlane, but we have been running pipelines successfully for months before this. Any updates?
