### ISSUE TITLE
Crash occur when multiple teams exist in App Store Connect

### ISSUE THREAD

**Issue by zizi4n5** [fastlane/fastlane#20085]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.205.0`
- Last working version: `2.204.3`

### Regression Description

fastlane deliver crashed.
It seems to be caused by having multiple App Store Connect teams.
Note that the crash did not occur when the team id was specified in the environment variable FASTLANE_ITC_TEAM_ID.

```console
$DELIVER_USER=XXXX@YYYY.com bundle exec fastlane deliver // NG
$DELIVER_USER=XXXX@YYYY.com bundle exec fastlane deliver download_metadata // NG
$DELIVER_USER=XXXX@YYYY.com FASTLANE_ITC_TEAM_ID=ZZZZ bundle exec fastlane deliver // OK
$DELIVER_USER=XXXX@YYYY.com FASTLANE_ITC_TEAM_ID=ZZZZ bundle exec fastlane deliver download_metadata // OK
```

##### Complete output when running fastlane, including the stack trace and command used

<details><summary>✅ fastlane deliver download_metadata output ✅</summary>

```console
$DELIVER_USER=XXXX@YYYY.com bundle exec fastlane deliver download_metadata
[✔] 🚀 
[11:45:01]: Successfully loaded '/Users/XXXX/Develop/tp/fastlane/Deliverfile' 📄

+-----------------------+-----------------------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------------+-----------------------+
| app_identifier        | com.tp                |
| languages             | ["ja", "en-US"]       |
| submit_for_review     | false                 |
| force                 | true                  |
| skip_screenshots      | true                  |
| skip_metadata         | false                 |
| skip_binary_upload    | true                  |
+-----------------------+-----------------------+

[11:45:01]: Login to App Store Connect (XXXX@YYYY.com)
Multiple App Store Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable


Looking for related GitHub issues on fastlane/fastlane...

➡️  [supply] added support for refresh tokens as an authentication method
    https://github.com/fastlane/fastlane/pull/16414 [open] 10 💬
    23 May 2020

➡️  Undefined method shellscape for nil:NilClass
    https://github.com/fastlane/fastlane/issues/19709 [closed] 1 💬
    4 weeks ago

➡️  snapshot doesn't seem to work for macOS apps
    https://github.com/fastlane/fastlane/issues/18709 [open] 8 💬
    3 weeks ago

and 546 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/bin/fastlane)
Traceback (most recent call last):
	34: from /Users/XXXX/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
	33: from /Users/XXXX/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
	32: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/exe/bundle:37:in `<top (required)>'
	31: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	30: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/exe/bundle:49:in `block in <top (required)>'
	29: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli.rb:24:in `start'
	28: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	27: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli.rb:30:in `dispatch'
	26: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	25: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	24: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	23: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli.rb:474:in `exec'
	22: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:28:in `run'
	21: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:63:in `kernel_load'
	20: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:63:in `load'
	19: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
	18: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	17: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/bin/fastlane:23:in `<top (required)>'
	16: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	15: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
	14: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
	13: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	12: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	11: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	10: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 9: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 8: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/commands_generator.rb:164:in `block (2 levels) in run'
	 7: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/commands_generator.rb:164:in `new'
	 6: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/runner.rb:23:in `initialize'
	 5: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/runner.rb:43:in `login'
	 4: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	 3: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/connect_api/client.rb:69:in `login'
	 2: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/tunes_client.rb:91:in `select_team'
	 1: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/tunes_client.rb:91:in `loop'
/Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/tunes_client.rb:98:in `block in select_team': undefined method `[]' for nil:NilClass (NoMethodError)
	34: from /Users/XXXX/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
	33: from /Users/XXXX/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
	32: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/exe/bundle:37:in `<top (required)>'
	31: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	30: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/exe/bundle:49:in `block in <top (required)>'
	29: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli.rb:24:in `start'
	28: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	27: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli.rb:30:in `dispatch'
	26: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	25: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	24: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	23: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli.rb:474:in `exec'
	22: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:28:in `run'
	21: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:63:in `kernel_load'
	20: from /Users/XXXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.19/lib/bundler/cli/exec.rb:63:in `load'
	19: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
	18: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	17: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/bin/fastlane:23:in `<top (required)>'
	16: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	15: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
	14: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
	13: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	12: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	11: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	10: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 9: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 8: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/commands_generator.rb:164:in `block (2 levels) in run'
	 7: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/commands_generator.rb:164:in `new'
	 6: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/runner.rb:23:in `initialize'
	 5: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/deliver/lib/deliver/runner.rb:43:in `login'
	 4: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	 3: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/connect_api/client.rb:69:in `login'
	 2: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/tunes_client.rb:91:in `select_team'
	 1: from /Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/tunes_client.rb:91:in `loop'
/Users/XXXX/Develop/tp/vendor/bundle/ruby/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/tunes_client.rb:98:in `block in select_team': [!] undefined method `[]' for nil:NilClass (NoMethodError)
```

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                       |
| --------------------------- | ----------------------------------------------------------- |
| OS                          | 12.2.1                                                      |
| Ruby                        | 2.6.5                                                       |
| Bundler?                    | true                                                        |
| Git                         | git version 2.32.0 (Apple Git-132)                          |
| Installation Source         | ~/Develop/tp/vendor/bundle/ruby/2.6.0/bin/fastlane         |
| Host                        | macOS 12.2.1 (21D62)                                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                                 |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                                 |
| Is contained                | false                                                       |
| Is homebrew                 | false                                                       |
| Is installed via Fabric.app | false                                                       |
| Xcode Path                  | /Applications/Xcode_13.2.1.app/Contents/Developer/          |
| Xcode Version               | 13.2.1                                                      |
| Swift Version               | 5.5.2                                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.0 | ✅ Up-To-Date  |

*generated on:* **2022-03-18**
</details>

**Comment by zizi4n5** [comment]
The issue description include the output of fastlane env.

**Comment by ronpelayo** [comment]
We got the same issue #20086
