### ISSUE TITLE
update_project_provisioning failed

### ISSUE THREAD

**Issue by perfectdim** [fastlane/fastlane#20172]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

fastlane finished with errors:
```
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/update_project_provisioning.rb:73:in `block (2 levels) in run': [!] undefined method `[]' for nil:NilClass (NoMethodError)
```

##### Command executed

```
  update_project_provisioning(
    xcodeproj: "#{PROJECT_NAME}.xcodeproj",
    target_filter: PROJECT_NAME,
    code_signing_identity: "iPhone Distribution",
    profile: CERTIFICATES_PATH+"AppStore_#{APP_IDENTIFIER}.mobileprovision"
  )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
$ fastlane test
[✔] 🚀 
[13:13:07]: fastlane detected a Gemfile in the current directory
[13:13:07]: However, it seems like you didn't use `bundle exec`
[13:13:07]: To launch fastlane faster, please use
[13:13:07]: 
[13:13:07]: $ bundle exec fastlane test
[13:13:07]: 
[13:13:07]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:13:09]: ------------------------------
[13:13:09]: --- Step: default_platform ---
[13:13:09]: ------------------------------
[13:13:09]: Driving the lane 'ios test' 🚀
[13:13:10]: -----------------------------------------
[13:13:10]: --- Step: update_project_provisioning ---
[13:13:10]: -----------------------------------------
[13:13:10]: You’re updating provisioning profiles directly in your project, but have you considered easier ways to do code signing?
[13:13:10]: https://docs.fastlane.tools/codesigning/GettingStarted/
[13:13:10]: Parsing mobile provisioning profile from '/Users/***/AppStore_***.mobileprovision'
[13:13:10]: Going to update project '***.xcodeproj' with UUID
[13:13:10]: Updating target ***...
[13:13:10]: Updating configuration Debug...
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios test |
+------------------+----------+

+------+-----------------------------+-------------+
|                 fastlane summary                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 💥   | update_project_provisioning | 0           |
+------+-----------------------------+-------------+

[13:13:10]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  select_team': undefined method `[]' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/20086 [closed] 17 💬
    3 weeks ago

➡️  [spaceship][tunes] fix 'block in select_team': [!] undefined method `[]' for nil:NilClass
    https://github.com/fastlane/fastlane/pull/20088 [closed] 5 💬
    3 weeks ago

➡️  [supply] added support for refresh tokens as an authentication method
    https://github.com/fastlane/fastlane/pull/16414 [open] 10 💬
    23 May 2020

and 554 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/update_project_provisioning.rb:73:in `block (2 levels) in run': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/update_project_provisioning.rb:57:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/update_project_provisioning.rb:57:in `block in run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/update_project_provisioning.rb:49:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/update_project_provisioning.rb:49:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:54:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:25:in `load'
	from /usr/local/bin/fastlane:25:in `<main>'
 </pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.3.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.33.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.3.1 (21E258)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.3.1                                                         |
| Swift Version               | 5.6                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| plist                           | 3.5.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.10.1       |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.0        |
| simctl                          | 1.6.8        |
| google-apis-playcustomapp_v1    | 0.2.0        |
| uber                            | 0.1.0        |
| declarative-option              | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.0.2        |
| memoist                         | 0.16.2       |
| signet                          | 0.14.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.4.4        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-cloud-core               | 1.5.0        |
| google-apis-iamcredentials_v1   | 0.3.0        |
| google-apis-storage_v1          | 0.3.0        |
| google-cloud-storage            | 1.31.0       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.2        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| public_suffix                   | 4.0.6        |
| tty-screen                      | 0.8.1        |
| babosa                          | 1.0.4        |
| excon                           | 0.78.0       |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| ruby2_keywords                  | 0.0.2        |
| faraday                         | 1.1.0        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.0        |
| json                            | 2.3.1        |
| naturally                       | 2.2.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.1.4        |
| jwt                             | 2.3.0        |
| declarative                     | 0.0.20       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| google-cloud-env                | 1.4.0        |
| google-cloud-errors             | 1.0.1        |
| rake                            | 13.0.1       |
| digest-crc                      | 0.6.1        |
| emoji_regex                     | 3.2.1        |
| aws-eventstream                 | 1.1.0        |
| aws-sigv4                       | 1.2.2        |
| aws-partitions                  | 1.393.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.109.2      |
| aws-sdk-kms                     | 1.39.0       |
| aws-sdk-s3                      | 1.84.1       |
| forwardable                     | 1.3.1        |
| logger                          | 1.3.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| date                            | 3.0.1        |
| io-console                      | 0.5.6        |
| fileutils                       | 1.4.1        |
| zlib                            | 1.0.0        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2022-04-13**
</details>
</pre>
</details>

**Comment by grifotv** [comment]
I started getting this error this morning. It was working fine the last few days.

**Comment by msangals** [comment]
same here

**Comment by tobiloeb** [comment]
same here

**Comment by jprinsloo** [comment]
Also getting the same error at the moment.

**Comment by akshaykhanoreraw** [comment]
Getting same error from Today morning

**Comment by yixiangfeng** [comment]
regenerate provision pofile in Apple develop

**Comment by BDProject** [comment]
Same, error messaging around provisioning. All builds across multiple accounts, enterprise and prod.

**Comment by chaucyzhang** [comment]
same here, the problem is in update_project_provisioning.rb:

**Comment by BDProject** [comment]
@yixiangfeng are you saying you resolved this problem today by making a change on your Apple Developer account, or this was something you've used in the past to fix?

**Comment by yixiangfeng** [comment]
@BDProject  yes. i remove all provisioning profile and use match to regenerate the provision profile

**Comment by perfectdim** [comment]
@yixiangfeng confirm! `force: true` update all profiles via `match` helps!

**Comment by jprinsloo** [comment]
If one needs to do this manually, does it mean deleting the existing provisioning profile and recreating it on the Apple Developer Portal?

**Comment by 2sem** [comment]
I found something different
success (yesterday)
<img width="947" alt="스크린샷 2022-04-13 오후 8 24 08" src="https://user-images.githubusercontent.com/16129260/163169984-150714b8-5e7c-402c-8d9a-a427f6f75db1.png">

fail(today)
<img width="948" alt="스크린샷 2022-04-13 오후 8 23 55" src="https://user-images.githubusercontent.com/16129260/163170024-1f11dd3b-1dfb-46b6-9917-d0f7d5a0b313.png">

fastlane is same 
<img width="328" alt="스크린샷 2022-04-13 오후 8 25 19" src="https://user-images.githubusercontent.com/16129260/163170125-5f82b846-205f-4099-bcf2-0f25d4904513.png">

**Comment by ttlenell** [comment]
> @yixiangfeng confirm! `force: true` update all profiles via `match` helps!

This worked fine for me!

**Comment by LifetimeCode** [comment]
> @yixiangfeng confirm! `force: true` update all profiles via `match` helps!

How to use this?

**Comment by BDProject** [comment]
> > @yixiangfeng confirm! `force: true` update all profiles via `match` helps!
> 
> How to use this?

Same how and where to set force to true? Anybody able to share sample code?

**Comment by yixiangfeng** [comment]
@LifetimeCode  you can go the `https://developer.apple.com/` login go to profile remove  the problem provision profile and  create a new one

**Comment by jprinsloo** [comment]
**From my previous comment:** 
_If one needs to do this manually, does it mean deleting the existing provisioning profile and recreating it on the Apple Developer Portal?_

I can confirm that by deleting the existing provisioning profile and recreating it on the Apple Developer Portal solved the issue on my side (for those who use Fastlane with GitHub Actions automation).

**Comment by perfectdim** [comment]
> > > @yixiangfeng confirm! `force: true` update all profiles via `match` helps!
> > 
> > 
> > How to use this?
> 
> Same how and where to set force to true? Anybody able to share sample code?

```
    match(
        app_identifier: APP_IDENTIFIERS,
        type: "development",
        output_path: CERTIFICATES_PATH,
        force: true
    )
    match(
        app_identifier: APP_IDENTIFIERS,
        type: "appstore",
        output_path: CERTIFICATES_PATH,
        force: true
    )
```

**Comment by fgroeger** [comment]
We had the same issue at our company, using `update_code_signing_settings` instead of `update_project_provisioning` worked for us without recreating the profiles 🙂

**Comment by BDProject** [comment]
> We had the same issue at our company, using `update_code_signing_settings` instead of `update_project_provisioning` worked for us without recreating the profiles 🙂

Can you share an example of the code you changed? I will try your suggestion if match force doesn't work.

**Comment by fgroeger** [comment]
This is my replacement code:
```
update_code_signing_settings(
    path: ".path/to/project.xcodeproj",
    use_automatic_signing: false,
    team_id: EXPORT_TEAM_ID,
    code_sign_identity: CODESIGNING_IDENTITY,
    profile_name: options[:provisioning_profile_name],
    targets: targets_to_change
  )
```

**Comment by EricSpiral** [comment]
> @yixiangfeng confirm! `force: true` update all profiles via `match` helps!

Can you explain this? Thank you!

**Comment by on3iro** [comment]
> This is my replacement code:
> 
> ```
> update_code_signing_settings(
>     path: ".path/to/project.xcodeproj",
>     use_automatic_signing: false,
>     team_id: EXPORT_TEAM_ID,
>     code_sign_identity: CODESIGNING_IDENTITY,
>     profile_name: options[:provisioning_profile_name],
>     targets: targets_to_change
>   )
> ```
> 
> We don't use match for the profiles though.

What parts did you replace exactly? :)

**Comment by fgroeger** [comment]
Not using `update_project_provisioning` anymore 🙂

**Comment by on3iro** [comment]
ah I see, thanks @fgroeger

**Comment by anutting** [comment]
why is update_project_provisioning suddenly no longer working? for me, swapping to update_code_signing_settings is not a 1 for 1 change from update_project_provisioning so it's not a good fix for this issue.

**Comment by jeebb** [comment]
the change to update_code_signing_settings does not work for me and I am not sure if it's the right approach in my case. Instead of that, this solution works for me: https://github.com/fastlane/fastlane/issues/20172#issuecomment-1097959496

**Comment by mattvv** [comment]
For me, I didn't want to update my update_project_provisioning.

I just did the following.
1) update to latest fastlane
2) fastlane match nuke distribution
3) fastlane match appstore

and then let the CI build.

**Comment by 2sem** [comment]
See my case
 
[Before] - fail
<img width="356" alt="스크린샷 2022-04-14 오전 10 55 40" src="https://user-images.githubusercontent.com/16129260/163299910-fcf9d818-548f-4ae5-908d-a7c11e19e567.png">

[After] - success
<img width="369" alt="스크린샷 2022-04-14 오전 10 56 13" src="https://user-images.githubusercontent.com/16129260/163299941-c98a7a88-95d6-49a8-be16-9892307266fb.png">

I hope this is helpful for someone.

**Comment by 417-72KI** [comment]
I tried to re-generate provisioning profiles.
1. Open https://developer.apple.com/account/resources/profiles/list
2. Select any provisioning profile
3. Click `Edit`
4. Click `Save`
5. Repeat 1 ~ 4 for all profiles

rebuilding now, it seems to be working.

**Comment by kchromik** [comment]
Weird, but @417-72KI solution works for me. Thanks.

**Comment by q1019736727** [comment]
> **From my previous comment:** _If one needs to do this manually, does it mean deleting the existing provisioning profile and recreating it on the Apple Developer Portal?_
> 
> I can confirm that by deleting the existing provisioning profile and recreating it on the Apple Developer Portal solved the issue on my side (for those who use Fastlane with GitHub Actions automation).

I manage dozens of projects, and if deleting profiles one by one is time-consuming, I don't know if there's a better way

**Comment by brent159753** [comment]
> I tried to re-generate provisioning profiles.
> 
> 1. Open https://developer.apple.com/account/resources/profiles/list
> 2. Select any provisioning profile
> 3. Click `Edit`
> 4. Click `Save`
> 5. Repeat 1 ~ 4 for all profiles
> 
> rebuilding now, it seems to be working.
> 
> Deleting was not required in my case.

This worked for us, thanks!

**Comment by Mishgan** [comment]
We have got the same issue in Unity Cloud Build  for out unity project:

```
46139: https://docs.fastlane.tools/codesigning/GettingStarted/
46140: Parsing mobile provisioning profile from '/BUILD_PATH/Library/MobileDevice/Provisioning Profiles/f494060c-80eb-403a-962d-848b675db384.mobileprovision'
46141: Going to update project 'Unity-iPhone.xcodeproj' with UUID
46142: Updating target Unity-iPhone...
46143: Updating configuration Release...
46144: +------------------+-----------+
46145: |         Lane Context         |
46146: +------------------+-----------+
46147: | DEFAULT_PLATFORM | ios       |
46148: | PLATFORM_NAME    | ios       |
46149: | LANE_NAME        | ios build |
46150: +------------------+-----------+
46151: +------+-----------------------------+-------------+
46152: |                 fastlane summary                 |
46153: +------+-----------------------------+-------------+
46154: | Step | Action                      | Time (in s) |
46155: +------+-----------------------------+-------------+
46156: | 1    | Verifying fastlane version  | 0           |
46157: | 2    | default_platform            | 0           |
46158: | 3    | set_info_plist_value        | 0           |
46159: | 💥   | update_project_provisioning | 0           |
46160: +------+-----------------------------+-------------+
46161: fastlane finished with errors
46162: /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:73:in `block (2 levels) in run': [!] undefined method `[]' for nil:NilClass (NoMethodError)
46163: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:57:in `each'
46164: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:57:in `block in run'
46165: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:49:in `each'
46166: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/actions/update_project_provisioning.rb:49:in `run'
46167: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
46168: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
46169: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
46170: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
46171: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
46172: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
46173: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
46174: 	from Fastfile:140:in `block (2 levels) in parsing_binding'
46175: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/lane.rb:33:in `call'
46176: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
46177: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
46178: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
46179: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
46180: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
46181: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
46182: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
46183: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
46184: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
46185: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
46186: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
46187: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
46188: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
46189: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
46190: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/gems/fastlane-2.182.0/bin/fastlane:23:in `<top (required)>'
46191: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `load'
46192: 	from /BUILD_PATH/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `<main>'
46193: ! build of 'mishgan-ios' failed. ! xcode build failed.
```

**Comment by burtsevyg** [comment]
Replace

```
    update_project_provisioning(
      profile: ENV["sigh_#{ENV['PROVIDER_VALUE']}_appstore_profile-path"],
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution"
    )    
```

to 

```
    update_code_signing_settings(
      profile_name: "match AppStore " + ENV['PROVIDER_VALUE'],
      build_configurations: "Release",
      code_sign_identity: "iPhone Distribution"
    )
```

fix my problem.

**Comment by tigerw** [comment]
```
> openssl pkcs7 -print_certs -text -in noisivorpelibom.mobileprovision -inform der
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 23 (0x17)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=US, O=Apple Inc., OU=Apple Certification Authority, CN=Apple Root CA
        Validity
            Not Before: Apr 12 17:43:28 2007 GMT
            Not After : Apr 12 17:43:28 2022 GMT
        Subject: C=US, O=Apple Inc., OU=Apple Certification Authority, CN=Apple iPhone Certification Authority
<snip>
```
Apple's intermediate certificates used to sign the mobileprovision file expired, best option is to re-generate the provisioning profiles, I suppose. See http://stackoverflow.com/a/71853423

**Comment by ToshKoevoets** [comment]
Hi All,

For those who didn't have the time to read everything, Apple expired a lot of Provision Profiles, here https://stackoverflow.com/questions/71850186/invalid-provisioning-profile-signature-state-error-validation-error-90165/71853423#71853423

Stackoverflow mainly offers manual solution, but with fastlane it can be done as well. Depending how you have your lane setup, when you run get_provisioning_profile there is a parameter force to renew its expiration date. Most likely better to just do once.

```
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # change to whatever works for you
      force: true,
      filename: "AppStore_" + ENV["APP_IDENTIFIER"] + ".mobileprovision" # Rename the local provisioning profile
    )
```

**Comment by luolisheng** [comment]
swapping to update_code_signing_settings work for me

**Comment by bryanrgriffin** [comment]
Where exactly is the profile_name retrieved for this code snippet?
```
update_code_signing_settings(
    path: ".path/to/project.xcodeproj",
    use_automatic_signing: false,
    team_id: EXPORT_TEAM_ID,
    code_sign_identity: CODESIGNING_IDENTITY,
    profile_name: options[:provisioning_profile_name],
    targets: targets_to_change
  )
```

**Comment by cristhianfms** [comment]
why `update_code_signing_settings` is working without renew provisioning profiles?

**Comment by tobiastornros** [comment]
Added `force:true` to `get_provisioning_profile` solved it for us. We followed this guide for the fastlane setup. https://thecodingmachine.github.io/react-native-boilerplate/docs/BetaBuild/#code-signing

**Comment by avas27JTG** [comment]
I was facing similar issue on creating Mattermost iOS build

solution that worked for me was to use below code
```
      update_code_signing_settings(
          profile_name: "match AppStore " + id,
          build_configurations: config_mode,
          code_sign_identity: 'iPhone Distribution',
          targets: target,
          path: './ios/Mattermost.xcodeproj'
      )
```
in place of
```
      update_project_provisioning(
          xcodeproj: './ios/Mattermost.xcodeproj',
          profile: ENV["#{profile}_profile-path"], # optional if you use sigh
          target_filter: ".*#{target}$", # matches name or type of a target
          build_configuration: config_mode,
          code_signing_identity: 'iPhone Distribution' # optionally specify the codesigning identity
      )
 ```
