### ISSUE TITLE
fastlane init crash

### ISSUE THREAD

**Issue by LayMui** [fastlane/fastlane#20183]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

when I run fastlane init after cleanup fastlane directory in my ios folder, 
i got this error 
gems/bundler-2.3.11/lib/bundler/shared_helpers.rb:117:in `rescue in filesystem_access': Bundler::Dsl::DSLError

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> here is the content of the Gemfile:
# Gemfile
source "https://rubygems.org"
gem 'fastlane'
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path) </pre>
</details
### Environment

fastlane env
Ignoring digest-crc-0.6.4 because its extensions are not built. Try: gem pristine digest-crc --version 0.6.4
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
[⠙] 🚀 Ignoring commonmarker-0.17.13 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.13
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring executable-hooks-1.6.1 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.1
Ignoring ffi-1.14.2 because its extensions are not built. Try: gem pristine ffi --version 1.14.2
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Ignoring sassc-2.4.0 because its extensions are not built. Try: gem pristine sassc --version 2.4.0
Ignoring unf_ext-0.0.8.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.1
[✔] 🚀 
[06:16:26]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.45.2 /Users/laymui/.gem/gems/bundler-2.3.11/lib/bundler/dsl.rb:517:in `read': Is a directory @ io_fread - /Users/laymui/dev/yara/react-native-stock-price-app/ios (Errno::EISDIR)
	from /Users/laymui/.gem/gems/bundler-2.3.11/lib/bundler/dsl.rb:517:in `contents'
	from /Users/laymui/.gem/gems/bundler-2.3.11/lib/bundler/dsl.rb:547:in `to_s'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:304:in `message'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:304:in `handle_unknown_error!'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:213:in `rescue_unknown_error'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:179:in `rescue in run!'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:128:in `run!'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/laymui/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.205.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

<details>
  <pre> [Gemfile content: # Gemfile
source "https://rubygems.org"
gem 'fastlane'
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)] </pre>
</details>

**Comment by LayMui** [comment]
sudo fastlane init resolved it
