### ISSUE TITLE
Gym Export Failed

### ISSUE THREAD

**Issue by ZihenMo** [fastlane/fastlane#20192]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.2.1                                                  |
| Ruby                        | 3.1.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.32.0 (Apple Git-132)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.205.1/libexec/bin/fastlane |
| Host                        | macOS 12.2.1 (21D62)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.1.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.3                                                    |
| Swift Version               | 5.6                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # desc "Push a new release build to the App Store"
  # lane :release do
  #   build_app(workspace: "Pool.xcworkspace", scheme: "Pool")
  #   upload_to_app_store
  # end

  desc "Debug beta"
  lane :build_debug do


    # increment_build_number(xcodeproj: "Pool.xcodeproj")
    app_name = "pool_debug_#{get_version_number()}"
    build_app(workspace: "Pool.xcworkspace", 
              scheme: "Pool", 
              configuration:"Debug", 
              clean: true,
              # export_xcargs: "-allowProvisioningUpdates",
              export_options: "./fastlane/ExportOptions.plist",
              output_name: app_name,
              output_directory: "./fastlane/Archives")
    system("curl -# -v -X POST -H 'token: viabtc_app_laosiji_666' -F 'file=@Archives/#{app_name}.ipa' http://18.167.38.162:5000/upload/pool/iOS | tee /dev/null")
  end

  lane :build_debug_push do
    app_name = "pool_debug_#{get_version_number()}"
    build_app(workspace: "Pool.xcworkspace", 
              scheme: "Pool", 
              configuration:"DebugPush", 
              clean: true,
              export_xcargs: "-allowProvisioningUpdates",
              export_options: "./fastlane/ExportOptions.plist",
              output_name: app_name,
              output_directory: "./fastlane/Archives")
    system("curl -# -v -X POST -H 'token: viabtc_app_laosiji_666' -F 'file=@Archives/#{app_name}.ipa' http://18.167.38.162:5000/upload/pool/iOS | tee /dev/null")
  end

  desc "Release beta"
  lane :build_release do

    # increment_build_number(xcodeproj: "Pool.xcodeproj")
    app_name = "pool_release_#{get_version_number()}"
    build_app(workspace: "Pool.xcworkspace", 
              scheme: "Pool", 
              configuration:"TestRelease", 
              clean: true,
              export_xcargs: "-allowProvisioningUpdates",
              export_options: "./fastlane/ExportOptions.plist",
              output_name: app_name,
              output_directory: "./fastlane/Archives")
    system("curl -# -v -X POST -H 'token: viabtc_app_laosiji_666' -F 'file=@Archives/#{app_name}.ipa' http://18.167.38.162:5000/upload/pool/iOS | tee /dev/null")
  end

  desc "配置版本"
  lane :set_version do |options|
    set_version(options[:version_number] , options[:build_number])
  end

  def set_version(version_number, build_number)
    increment_build_number(xcodeproj: "Pool.xcodeproj", build_number: build_number)
    increment_version_number(xcodeproj: "Pool.xcodeproj", version_number: version_number)
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.viabtc.pool2") # The bundle identifier of your app
apple_id("cchao2627@icloud.com") # Your Apple email address

itc_team_id("119848656") # App Store Connect Team ID
team_id("9MALJYN966") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.1       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.2        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.569.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.130.0      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-04-19**
</details>
-----------
erb):8:in `encode': \e[31m[!] code converter not found (xml_attr_content,xml_attr_quote)\e[0m (Encoding::ConverterNotFoundError)
	from (erb):8:in `block in generate'
	from (erb):6:in `each'
	from (erb):6:in `each_with_index'
	from (erb):6:in `generate'
	from /usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/erb.rb:905:in `eval'
	from /usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/erb.rb:905:in `result'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/junit_generator.rb:13:in `generate'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/lane_manager_base.rb:17:in `finish_fastlane'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/lane_manager.rb:67:in `cruise_lane'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/bin/fastlane:25:in `load'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/bin/fastlane:25:in `<main>'
(erb):8:in `encode': code converter not found (xml_attr_content,xml_attr_quote) (Encoding::ConverterNotFoundError)
	from (erb):8:in `block in generate'
	from (erb):6:in `each'
	from (erb):6:in `each_with_index'
	from (erb):6:in `generate'
	from /usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/erb.rb:905:in `eval'
	from /usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/erb.rb:905:in `result'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/junit_generator.rb:13:in `generate'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/lane_manager_base.rb:17:in `finish_fastlane'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/lane_manager.rb:67:in `cruise_lane'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/bin/fastlane:25:in `load'
	from /usr/local/Cellar/fastlane/2.205.1/libexec/bin/fastlane:25:in `<main>'

**Comment by maxckelly** [comment]
Have you found a solution for this? 

I'm getting the same issue after updating my Mac.

**Comment by Suri1044** [comment]
Any update on this issue. Gym is failing and its blocking the release. Need help plz
<img width="1327" alt="Screenshot 2022-04-21 at 11 39 43 PM" src="https://user-images.githubusercontent.com/68360396/164525301-d39fab21-290c-4d70-b2e3-2742a87e6a73.png">
<img width="1327" alt="Screenshot 2022-04-21 at 11 39 02 PM" src="https://user-images.githubusercontent.com/68360396/164525334-8ab10490-7c7d-443b-b68e-f0e1a608ddf8.png">

**Comment by Farr69** [comment]
Have you seen our new Code Signing Troubleshooting Guide? It will help you resolve the most common code signing issues 👍
