### ISSUE TITLE
app_store_connect_api_key  `Is a directory @ io_fread`

### ISSUE THREAD

**Issue by idelfonsog2** [fastlane/fastlane#20195]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> +---------------------------+---------+-----------------------------------------------------------+
|                                          Used plugins                                           |
+---------------------------+---------+-----------------------------------------------------------+
| Plugin                    | Version | Action                                                    |
+---------------------------+---------+-----------------------------------------------------------+
| fastlane-plugin-appcenter | 2.0.0   | appcenter_fetch_version_number, appcenter_fetch_devices,  |
|                           |         | appcenter_codepush_release_react, appcenter_upload        |
+---------------------------+---------+-----------------------------------------------------------+

[15:08:32]: -----------------------------
[15:08:32]: --- Step: update_fastlane ---
[15:08:32]: -----------------------------
[15:08:32]: Looking for updates for fastlane...
[15:08:32]: It seems that your Gem directory is not writable by your current user.
[15:08:32]: fastlane would need sudo rights to update itself, however, running 'sudo fastlane' is not recommended.
[15:08:32]: If you still want to use this action, please read the documentation on how to set this up:
[15:08:32]: https://docs.fastlane.tools/actions/update_fastlane/
[15:08:32]: ------------------------------
[15:08:32]: --- Step: default_platform ---
[15:08:32]: ------------------------------
[15:08:32]: Driving the lane 'ios install_certs_profiles' 🚀
[15:08:32]: ---------------------------------------------------------
[15:08:32]: --- Step: Switch to ios appstore_connect_api_key lane ---
[15:08:32]: ---------------------------------------------------------
[15:08:32]: Cruising over to lane 'ios appstore_connect_api_key' 🚖
[15:08:32]: ---------------------------------------
[15:08:32]: --- Step: app_store_connect_api_key ---
[15:08:32]: ---------------------------------------
+------------------+----------------------------+
|                 Lane Context                  |
+------------------+----------------------------+
| DEFAULT_PLATFORM | ios                        |
| PLATFORM_NAME    | ios                        |
| LANE_NAME        | ios install_certs_profiles |
+------------------+----------------------------+
[15:08:32]: Is a directory @ io_fread - /Users/NM276113/Developer/CorpHealthLab/iOS/CorpHealthLab

+------+---------------------------------------------+-------------+
|                         fastlane summary                         |
+------+---------------------------------------------+-------------+
| Step | Action                                      | Time (in s) |
+------+---------------------------------------------+-------------+
| 1    | update_fastlane                             | 0           |
| 2    | default_platform                            | 0           |
| 3    | Switch to ios appstore_connect_api_key lane | 0           |
| 💥   | app_store_connect_api_key                   | 0           |
+------+---------------------------------------------+-------------+

[15:08:32]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/app_store_connect_api_key.rb:33:in `binread': [!] Is a directory @ io_fread - /Users/NM276113/Developer/CorpHealthLab/iOS/CorpHealthLab (Errno::EISDIR)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/app_store_connect_api_key.rb:33:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:49:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:138:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>' </pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.3.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.35.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.3.1 (21E258)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.3                                                           |
| Swift Version               | 5.6                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:
// committed

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 2.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.31       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| emoji_regex                     | 3.2.3        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| public_suffix                   | 4.0.7        |
| excon                           | 0.92.2       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.1      |
| fastimage                       | 2.2.6        |
| json                            | 2.6.1        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.1       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.2        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.13.0       |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.578.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.130.1      |
| aws-sdk-kms                     | 1.56.0       |
| aws-sdk-s3                      | 1.113.0      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
| fastlane-plugin-appcenter       | 2.0.0        |
| csv                             | 3.0.9        |
</details>

*generated on:* **2022-04-19**
</details>

<details>
  <pre> `app_store_connect_api_key` failed with `/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/app_store_connect_api_key.rb:33:in `binread': [!] Is a directory @ io_fread - /Users/NM276113/Developer/CorpHealthLab/iOS/CorpHealthLab (Errno::EISDIR)` </pre>
</details>

**Comment by lucgrabowski** [comment]
It looks like `key_filepath` parameter in `appstore_connect_api_key` call points to a directory instead of a file.
Could you check if it's properly defined? If not, I'm not sure if it will be possible to help without seeing your Fastfile and more logs.
