### ISSUE TITLE
Screengrab cannot resolve the activity in multi flavour app

### ISSUE THREAD

**Issue by pennal** [fastlane/fastlane#20200]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
My app is a multi-flavour app, built as a whitelabel that then gets customisations for each flavour (customer). The app is about 2 years old, built with early releases from compose, and done completely in Kotlin. 

The app currently has a core component (called whitelabel) with all the logic, and then each flavour has some customisation on top to handle customer specific changes or resources.

I have been able to integrate fastlane for all previous stages except for screengrab, where it fails and I unfortunately do not know how to solve it anymore. I have tried a lot of different suggestions from the issues, SO, and everything else I could find.

I have followed the guide on fastlane (both the getting started and the dedicated action doc) and apart from some out-of-date info, I have been able to set it up.

Currently, I have been building the apps manually using gradle, and then feeding them to screngrab with this command:

``` bash
./gradlew clean
./gradlew assembleMyFlavourDebug assembleMyFlavourDebugAndroidTest
```
These work and generate the required APKs. First issue  is that this project does not have a simple AndroidTest gradle task, I had already asked this in [this discussion](https://github.com/fastlane/fastlane/discussions/19923) but I did not get a definitive answer.

Since then, I have worked through the multiple issues that popped up and redone the setup, but it seems that the issue stems from not being able to load the correct Activity to be displayed. To run the correct activity I am using the following test

```kotlin
import androidx.test.core.app.ActivityScenario
import ch.mycompany.whitel.MainActivity
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.JUnit4
import tools.fastlane.screengrab.Screengrab
import tools.fastlane.screengrab.locale.LocaleTestRule

@RunWith(JUnit4::class)
class MyFlavourScreengrabTest {

    @Rule @JvmField
    val localeTestRule = LocaleTestRule()

    @Test
    fun testTakeScreenshot() {
        ActivityScenario.launch(MainActivity::class.java)

        Screengrab.screenshot("before_button_click")
    }
}
```

##### Command executed

```bash
bundle exec fastlane screengrab
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> bundle exec fastlane screengrab
[✔] 🚀 
[15:55:43]: Successfully loaded '/Users/MyUser/Documents/Repos/mycompany/android-whitel/fastlane/Screengrabfile' 📄

+------------------+-------------------------------------------------------------------------------------------+
|                               Detected Values from './fastlane/Screengrabfile'                               |
+------------------+-------------------------------------------------------------------------------------------+
| app_package_name | ch.mycompany.myflavour                                                                   |
| app_apk_path     | app/build/outputs/apk/myFlavour/debug/app-myFlavour-debug.apk                         |
| tests_apk_path   | app/build/outputs/apk/androidTest/myFlavour/debug/app-myFlavour-debug-androidTest.apk |
+------------------+-------------------------------------------------------------------------------------------+

+-----------------------------+-------------------------------------------------------------------------------------------+
|                                             Summary for screengrab 2.205.1                                              |
+-----------------------------+-------------------------------------------------------------------------------------------+
| tests_package_name          | ch.mycompany.myflavour.test                                                              |
| locales                     | ["en-US"]                                                                                 |
| clear_previous_screenshots  | false                                                                                     |
| output_directory            | fastlane/metadata/android                                                                 |
| skip_open_summary           | false                                                                                     |
| app_package_name            | ch.mycompany.myflavour                                                                   |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner                                                   |
| ending_locale               | en-US                                                                                     |
| use_adb_root                | false                                                                                     |
| app_apk_path                | app/build/outputs/apk/myFlavour/debug/app-myFlavour-debug.apk                         |
| tests_apk_path              | app/build/outputs/apk/androidTest/myFlavour/debug/app-myFlavour-debug-androidTest.apk |
| device_type                 | phone                                                                                     |
| exit_on_test_failure        | true                                                                                      |
| reinstall_app               | false                                                                                     |
| use_timestamp_suffix        | true                                                                                      |
+-----------------------------+-------------------------------------------------------------------------------------------+

[15:55:43]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[15:55:43]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[15:55:43]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[15:55:43]: ▸ /sdcard
[15:55:43]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$ANDROID_DATA
[15:55:43]: ▸ /data
[15:55:43]: Cleaning screenshots on device
ls: /sdcard/ch.mycompany.myflavour/screengrab/en-US/images/screenshots: No such file or directory
[15:55:43]: Exit status: 1
ls: /sdcard/Android/data/ch.mycompany.myflavour/files/screengrab/en-US/images/screenshots: No such file or directory
[15:55:43]: Exit status: 1
ls: /data/user/0/ch.mycompany.myflavour/files/ch.mycompany.myflavour/screengrab/en-US/images/screenshots: No such file or directory
[15:55:44]: Exit status: 1
ls: /data/data/ch.mycompany.myflavour/files/ch.mycompany.myflavour/screengrab/en-US/images/screenshots: No such file or directory
[15:55:44]: Exit status: 1
ls: /data/data/ch.mycompany.myflavour/app_screengrab/en-US/images/screenshots: No such file or directory
[15:55:44]: Exit status: 1
ls: /data/data/ch.mycompany.myflavour/screengrab/en-US/images/screenshots: No such file or directory
[15:55:44]: Exit status: 1
[15:55:44]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[15:55:44]: ▸ 26
[15:55:44]: Installing app APK
[15:55:44]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/myFlavour/debug/app-myFlavour-debug.apk
[15:55:44]: ▸ Performing Streamed Install
[15:55:58]: ▸ Success
[15:55:58]: Installing tests APK
[15:55:58]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/androidTest/myFlavour/debug/app-myFlavour-debug-androidTest.apk
[15:55:58]: ▸ Performing Streamed Install
[15:56:01]: ▸ Success
[15:56:01]: Granting the permission necessary to change locales on the device
[15:56:01]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant ch.mycompany.myflavour android.permission.CHANGE_CONFIGURATION
[15:56:02]: Granting the permissions necessary to access device external storage
[15:56:02]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant ch.mycompany.myflavour android.permission.WRITE_EXTERNAL_STORAGE
[15:56:02]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant ch.mycompany.myflavour android.permission.READ_EXTERNAL_STORAGE
[15:56:02]: Enabling clean status bar
[15:56:02]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant ch.mycompany.myflavour android.permission.DUMP
[15:56:02]: ▸ Operation not allowed: java.lang.SecurityException: Package ch.mycompany.myflavour has not requested permission android.permission.DUMP
Operation not allowed: java.lang.SecurityException: Package ch.mycompany.myflavour has not requested permission android.permission.DUMP
[15:56:02]: Exit status: 1
[15:56:02]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell settings put global sysui_demo_allowed 1
[15:56:03]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop ch.mycompany.myflavour.test
[15:56:03]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop ch.mycompany.myflavour
[15:56:03]: Running tests for locale: en-US
[15:56:03]: $ /Users/MyUser/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en-US \
-e appendTimestamp true \
ch.mycompany.myflavour.test/androidx.test.runner.AndroidJUnitRunner
[15:56:04]: ▸ MyFlavourScreengrabTest:
[15:56:04]: ▸ Error in testTakeScreenshot(MyFlavourScreengrabTest):
[15:56:04]: ▸ java.lang.RuntimeException: Unable to resolve activity for: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=ch.mycompany.myflavour.test/ch.mycompany.whitel.MainActivity }
[15:56:04]: ▸   at androidx.test.core.app.InstrumentationActivityInvoker.startActivity(InstrumentationActivityInvoker.java:402)
[15:56:04]: ▸   at androidx.test.core.app.InstrumentationActivityInvoker.startActivity(InstrumentationActivityInvoker.java:437)
[15:56:04]: ▸   at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:265)
[15:56:04]: ▸   at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:195)
[15:56:04]: ▸   at MyFlavourScreengrabTest.testTakeScreenshot(MyFlavourScreengrabTest.kt:18)
[15:56:04]: ▸ Time: 0.026
[15:56:04]: ▸ There was 1 failure:
[15:56:04]: ▸ 1) testTakeScreenshot(MyFlavourScreengrabTest)
[15:56:04]: ▸ java.lang.RuntimeException: Unable to resolve activity for: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=ch.mycompany.myflavour.test/ch.mycompany.whitel.MainActivity }
[15:56:04]: ▸   at androidx.test.core.app.InstrumentationActivityInvoker.startActivity(InstrumentationActivityInvoker.java:402)
[15:56:04]: ▸   at androidx.test.core.app.InstrumentationActivityInvoker.startActivity(InstrumentationActivityInvoker.java:437)
[15:56:04]: ▸   at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:265)
[15:56:04]: ▸   at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:195)
[15:56:04]: ▸   at MyFlavourScreengrabTest.testTakeScreenshot(MyFlavourScreengrabTest.kt:18)
[15:56:04]: ▸   at java.lang.reflect.Method.invoke(Native Method)
[15:56:04]: ▸   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[15:56:04]: ▸   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[15:56:04]: ▸   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[15:56:04]: ▸   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[15:56:04]: ▸   at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:48)
[15:56:04]: ▸   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[15:56:04]: ▸   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[15:56:04]: ▸   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[15:56:04]: ▸   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[15:56:04]: ▸   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[15:56:04]: ▸   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[15:56:04]: ▸   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[15:56:04]: ▸   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[15:56:04]: ▸   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[15:56:04]: ▸   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[15:56:04]: ▸   at org.junit.runners.Suite.runChild(Suite.java:128)
[15:56:04]: ▸   at org.junit.runners.Suite.runChild(Suite.java:27)
[15:56:04]: ▸   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[15:56:04]: ▸   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[15:56:04]: ▸   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[15:56:04]: ▸   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[15:56:04]: ▸   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[15:56:04]: ▸   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[15:56:04]: ▸   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[15:56:04]: ▸   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[15:56:04]: ▸   at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[15:56:04]: ▸   at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
[15:56:04]: ▸   at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2074)
[15:56:04]: ▸ FAILURES!!!
[15:56:04]: ▸ Tests run: 1,  Failures: 1

[!] Tests failed for locale en-US on device emulator-5554
 </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.3.1                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 12.3.1 (21E258)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.3                                        |
| Swift Version               | 5.6                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
<PROPRIETARY AND NOT NEEDED, REMOVED>
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| bundler                         | 2.1.4        |
| uri                             | 0.10.0       |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.578.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.130.1      |
| aws-sdk-kms                     | 1.56.0       |
| aws-sdk-s3                      | 1.113.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.2       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.2        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.19.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-04-20**
</details></pre>
</details>

**Comment by pennal** [comment]
As it turns out, it was my mistake.

That error message showed up since I did not correctly register the activity in my `src/debug/AndroidManifest.xml`. I forgot to add the activity there and therefore it was not picked up.

That then led me to another error, one where the screenshots were taken but no content was shown. The status bar was there, and so were the controls at the bottom, but the app was not. The issue in this case had to do with my test class, that I changed to the following:

```kotlin
package ch.mycompany.myflavour

import androidx.test.ext.junit.rules.ActivityScenarioRule
import ch.mycompany.whitel.MainActivity
import org.junit.BeforeClass
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.JUnit4
import tools.fastlane.screengrab.DecorViewScreenshotStrategy
import tools.fastlane.screengrab.FalconScreenshotStrategy
import tools.fastlane.screengrab.Screengrab
import tools.fastlane.screengrab.UiAutomatorScreenshotStrategy
import tools.fastlane.screengrab.locale.LocaleTestRule


@RunWith(JUnit4::class)
class MyFlavourScreengrabTest {

    @Rule
    @JvmField
    val localeTestRule = LocaleTestRule()

    @get:Rule
    val activityTestRule = ActivityScenarioRule(MainActivity::class.java)

    @Test
    fun testTakeScreenshot() {
        // Set the default screenshot strategy, do not change!
        Screengrab.setDefaultScreenshotStrategy(UiAutomatorScreenshotStrategy())

        // Grab the screenshot
        Screengrab.screenshot("my_screenshot")
    }
}
```

Here the screenshots worked, but the content was not there. Since I was using generated activities, I forgot that I need to use the activity with an underscore after the name.

Added this activity in the `AndroidManifest.xml` and changed all occurrences of `MainActivity` in the test to `MainActivity_` and now everything works

Hopefully this can help somebody else!
