### ISSUE TITLE
Deliver fails promoting app to review, possible missing field

### ISSUE THREAD

**Issue by pennal** [fastlane/fastlane#20238]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We have a lane that takes care of uploading metadata/screenshots/build and promoting directly to review. Although all fields are correct, the lane fails with this issue:

```
The provided entity is missing a required attribute - You must provide a value for the attribute 'usesNonExemptEncryption' with this request
```

This is the redacted lane declaration:

```ruby
deliver(
    platform: "ios",
    app_identifier: bundleId,
    languages: ["it"],
    team_id: teamId,
    team_name: teamName,
    app_version: version,
    run_precheck_before_submit: false,
    force: true,
    ipa: "builds/#{bundleId}/#{xcodeTarget}-app-store.ipa",
    skip_metadata: true,
    skip_screenshots: true,
    metadata_path: "metadata/#{bundleId}",
    screenshots_path: "screenshots/#{bundleId}",
    submission_information: {
      add_id_info_uses_idfa: false,
      export_compliance_uses_encryption: true,
      export_compliance_is_exempt: true
    },
    submit_for_review: true,
    automatic_release: true,
  )
```

I have tried the following things:
 1. Splitting the different uploads (screens, metadata, etc) but the same error persists
 2. Removing and rebuilding the release, no luck
 3. Setting all values explicitly for the submission info, no luck

I have close to no knowledge of ruby, but looking at [this file](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_submission.rb) it seems to me that the field `usesNonExemptEncryption` is never mapped to the payload, therefore missing from the actual request.

Could anyone confirm?

##### Command executed

```bash
bundle exec fastlane store_distribution_lane
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [15:16:37]: ---------------------------------------------
[15:16:37]: --- Step: Switch to _distribute_lane lane ---
[15:16:37]: ---------------------------------------------
[15:16:37]: Cruising over to lane '_distribute_lane' 🚖
[15:16:37]: ----------------------------------------------------------
[15:16:37]: --- Step: Switch to _obtain_app_store_connect_key lane ---
[15:16:37]: ----------------------------------------------------------
[15:16:37]: Cruising over to lane '_obtain_app_store_connect_key' 🚖
[15:16:38]: Login Status Code: 200
[15:16:38]: Downloading 1c4a079a-d160-4877-860e-a982ed3361b7 to ./connect-api-key-file-APP_NAME.p8
[15:16:38]: URL: https://api.client-manager.loopalty.ch/static/1c4a079a-d160-4877-860e-a982ed3361b7
[15:16:38]: Finished downloading 1c4a079a-d160-4877-860e-a982ed3361b7 to ./connect-api-key-file-APP_NAME.p8
[15:16:38]: ---------------------------------------
[15:16:38]: --- Step: app_store_connect_api_key ---
[15:16:38]: ---------------------------------------
[15:16:38]: Cruising back to lane '_distribute_lane' 🚘
[15:16:38]: Downloading previous metadata...might take a white
[15:16:38]: -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[15:16:38]: --- Step: bundle exec fastlane deliver download_metadata -m metadata/BUNDLE_ID -u 'USERNAME' -a 'BUNDLE_ID' --api_key_path 'fastlane/IDENTIFIER.json' --languages 'it' ---
[15:16:38]: -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[15:16:38]: $ bundle exec fastlane deliver download_metadata -m metadata/BUNDLE_ID -u 'USERNAME' -a 'BUNDLE_ID' --api_key_path 'fastlane/IDENTIFIER.json' --languages 'it'
[15:16:41]: ▸ [15:16:41]: Creating authorization token for App Store Connect API
[15:16:42]: ▸ +--------------------------------------+-------------------------------+
[15:16:42]: ▸ |                       deliver 2.205.2 Summary                        |
[15:16:42]: ▸ +--------------------------------------+-------------------------------+
[15:16:42]: ▸ | metadata_path                        | metadata/BUNDLE_ID |
[15:16:42]: ▸ | username                             | USERNAME         |
[15:16:42]: ▸ | app_identifier                       | BUNDLE_ID          |
[15:16:42]: ▸ | api_key_path                         | fastlane/IDENTIFIER.json        |
[15:16:42]: ▸ | languages                            | ["it"]                        |
[15:16:42]: ▸ | screenshots_path                     | ./fastlane/screenshots        |
[15:16:42]: ▸ | platform                             | ios                           |
[15:16:42]: ▸ | edit_live                            | false                         |
[15:16:42]: ▸ | use_live_version                     | false                         |
[15:16:42]: ▸ | skip_binary_upload                   | false                         |
[15:16:42]: ▸ | skip_screenshots                     | false                         |
[15:16:42]: ▸ | skip_metadata                        | false                         |
[15:16:42]: ▸ | skip_app_version_update              | false                         |
[15:16:42]: ▸ | force                                | false                         |
[15:16:42]: ▸ | overwrite_screenshots                | false                         |
[15:16:42]: ▸ | sync_screenshots                     | false                         |
[15:16:42]: ▸ | submit_for_review                    | false                         |
[15:16:42]: ▸ | reject_if_possible                   | false                         |
[15:16:42]: ▸ | phased_release                       | false                         |
[15:16:42]: ▸ | reset_ratings                        | false                         |
[15:16:42]: ▸ | run_precheck_before_submit           | true                          |
[15:16:42]: ▸ | precheck_default_rule_level          | warn                          |
[15:16:42]: ▸ | ignore_language_directory_validation | false                         |
[15:16:42]: ▸ | precheck_include_in_app_purchases    | true                          |
[15:16:42]: ▸ +--------------------------------------+-------------------------------+
[15:16:46]: ▸ [15:16:46]: Writing to 'metadata/BUNDLE_ID/it/name.txt'
[15:16:46]: ▸ [15:16:46]: Writing to 'metadata/BUNDLE_ID/it/subtitle.txt'
[15:16:46]: ▸ [15:16:46]: Writing to 'metadata/BUNDLE_ID/it/privacy_url.txt'
[15:16:46]: ▸ [15:16:46]: Writing to 'metadata/BUNDLE_ID/it/apple_tv_privacy_policy.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/it/description.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/it/keywords.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/it/release_notes.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/it/support_url.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/it/marketing_url.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/it/promotional_text.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/primary_category.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/secondary_category.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/primary_first_sub_category.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/primary_second_sub_category.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/secondary_first_sub_category.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/secondary_second_sub_category.txt'
[15:16:48]: ▸ [15:16:48]: Writing to 'metadata/BUNDLE_ID/copyright.txt'
[15:16:49]: ▸ [15:16:49]: Writing to 'metadata/BUNDLE_ID/review_information/first_name.txt'
[15:16:49]: ▸ [15:16:49]: Writing to 'metadata/BUNDLE_ID/review_information/last_name.txt'
[15:16:49]: ▸ [15:16:49]: Writing to 'metadata/BUNDLE_ID/review_information/phone_number.txt'
[15:16:49]: ▸ [15:16:49]: Writing to 'metadata/BUNDLE_ID/review_information/email_address.txt'
[15:16:49]: ▸ [15:16:49]: Writing to 'metadata/BUNDLE_ID/review_information/demo_user.txt'
[15:16:49]: ▸ [15:16:49]: Writing to 'metadata/BUNDLE_ID/review_information/demo_password.txt'
[15:16:49]: ▸ [15:16:49]: Writing to 'metadata/BUNDLE_ID/review_information/notes.txt'
[15:16:49]: --------------------------------
[15:16:49]: --- Step: rm ./IDENTIFIER.json ---
[15:16:49]: --------------------------------
[15:16:49]: $ rm ./IDENTIFIER.json
[15:16:49]: ---------------------
[15:16:49]: --- Step: deliver ---
[15:16:49]: ---------------------
[15:16:49]: Creating authorization token for App Store Connect API

+----------------------------------------------------------+----------------------------------------------------+
|                                            deliver 2.205.2 Summary                                            |
+----------------------------------------------------------+----------------------------------------------------+
| platform                                                 | ios                                                |
| app_identifier                                           | BUNDLE_ID                               |
| languages                                                | ["it"]                                             |
| team_id                                                  | TEAM_ID                                         |
| team_name                                                | COMPANY                                      |
| app_version                                              | 1.7                                                |
| run_precheck_before_submit                               | false                                              |
| force                                                    | true                                               |
| ipa                                                      | builds/BUNDLE_ID/IDENTIFIER-app-store.ipa |
| skip_metadata                                            | true                                               |
| skip_screenshots                                         | true                                               |
| metadata_path                                            | metadata/BUNDLE_ID                      |
| screenshots_path                                         | screenshots/BUNDLE_ID                   |
| submission_information.add_id_info_uses_idfa             | false                                              |
| submission_information.export_compliance_uses_encryption | true                                               |
| submission_information.export_compliance_is_exempt       | true                                               |
| submit_for_review                                        | true                                               |
| automatic_release                                        | true                                               |
| api_key                                                  | ********                                           |
| edit_live                                                | false                                              |
| use_live_version                                         | false                                              |
| skip_binary_upload                                       | false                                              |
| skip_app_version_update                                  | false                                              |
| overwrite_screenshots                                    | false                                              |
| sync_screenshots                                         | false                                              |
| reject_if_possible                                       | false                                              |
| phased_release                                           | false                                              |
| reset_ratings                                            | false                                              |
| precheck_default_rule_level                              | warn                                               |
| ignore_language_directory_validation                     | false                                              |
| precheck_include_in_app_purchases                        | true                                               |
+----------------------------------------------------------+----------------------------------------------------+

[15:16:50]: Making sure the latest version on App Store Connect matches '1.7'...
[15:16:51]: '1.7' is the latest version on App Store Connect
[15:16:51]: Uploading binary to App Store Connect
[15:16:52]: Going to upload updated app to App Store Connect
[15:16:52]: This might take a few minutes. Please don't interrupt the script.
[15:21:26]: iTunes Transporter successfully finished its job
[15:21:26]: ------------------------------------------------------------------------------------------------------------------
[15:21:26]: --- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
[15:21:26]: ------------------------------------------------------------------------------------------------------------------
[15:21:26]: Finished the upload to App Store Connect
[15:21:27]: Selecting the latest build...
[15:21:27]: Waiting for processing on... app_id: 1502290793, app_version: 1.7, build_version: 75, platform: IOS
[15:21:29]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
[15:21:29]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[15:21:45]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[15:22:03]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[15:22:20]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[15:22:36]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[15:22:53]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[15:23:11]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[15:23:31]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:23:50]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:24:07]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:24:24]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:24:42]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:24:59]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:25:16]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:25:33]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:25:50]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:26:07]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:26:25]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:26:43]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:26:59]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:27:16]: Waiting for App Store Connect to finish processing the new build (1.7 - 75) for IOS
[15:27:33]: Successfully finished processing the build 1.7 - 75 for IOS
[15:27:33]: Selecting build 1.7 (75)...
[15:27:36]: Successfully selected build
[15:27:38]: Successfully updated IDFA declarations on App Store Connect
+--------------------+--------------------------------------------------------------------------------------------------------------+
|                                                           Lane Context                                                            |
+--------------------+--------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                                          |
| PLATFORM_NAME      |                                                                                                              |
| LANE_NAME          | store_distribution_lane                                                                                      |
| BUILD_NUMBER       | 75                                                                                                           |
| VERSION_NUMBER     | 1.7                                                                                                          |
| IPA_OUTPUT_PATH    | REPO_PATH/builds/BUNDLE_ID/IDENTIFIER-app-store.ipa          |
| XCODEBUILD_ARCHIVE | /Users/Lucas/Library/Developer/Xcode/Archives/2022-05-02/IDENTIFIER-app-store 2022-05-02 15.09.36.xcarchive    |
| DSYM_OUTPUT_PATH   | REPO_PATH/builds/BUNDLE_ID/IDENTIFIER-app-store.app.dSYM.zip |
+--------------------+--------------------------------------------------------------------------------------------------------------+
[15:27:42]: appStoreVersions with id 'APP_STORE_ID' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why.
The provided entity is missing a required attribute - You must provide a value for the attribute 'usesNonExemptEncryption' with this request

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | Switch to _build_for_appstore_lane lane                       | 0           |
| 3    | increment_build_number                                        | 2           |
| 4    | increment_version_number                                      | 2           |
| 5    | gym                                                           | 434         |
| 6    | Switch to _distribute_lane lane                               | 0           |
| 7    | Switch to _obtain_app_store_connect_key lane                  | 0           |
| 8    | app_store_connect_api_key                                     | 0           |
| 9    | bundle exec fastlane deliver download_metadata -m metadata/ch | 11          |
| 10   | rm ./IDENTIFIER.json                                            | 0           |
| 💥   | deliver                                                       | 652         |
+------+---------------------------------------------------------------+-------------+

[15:27:42]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Spaceship::UnexpectedResponse: [!] appStoreVersions with id 'APP_STORE_ID' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why.
The provided entity is missing a required attribute - You must provide a value for the attribute 'usesNonExemptEncryption' with this request
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:1209:in `post_review_submission_item'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post_review_submission_item'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/spaceship/lib/spaceship/connect_api/models/review_submission.rb:69:in `add_app_store_version_to_review_items'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/deliver/lib/deliver/submit_for_review.rb:49:in `create_review_submission'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/deliver/lib/deliver/submit_for_review.rb:26:in `submit!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/deliver/lib/deliver/runner.rb:223:in `submit_for_review'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/deliver/lib/deliver/runner.rb:65:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:396:in `block in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:221:in `block (2 levels) in parsing_binding'
  Fastfile:215:in `each'
  Fastfile:215:in `block in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>' </pre>
</details>

### Environment

<details>
  <pre> swift-driver version: 1.45.2 <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.3.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.3.1 (21E258)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.3                                                           |
| Swift Version               | 5.6                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
NOT NEEDED
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 1.17.2       |
| etc                             | 1.0.1        |
| forwardable                     | 1.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.581.0      |
| aws-sigv4                       | 1.5.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.130.2      |
| aws-sdk-kms                     | 1.56.0       |
| aws-sdk-s3                      | 1.113.2      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.19.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.2       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-05-02**
</details> </pre>
</details>

**Comment by pennal** [comment]
@joshdholtz I am taking the liberty to ping you as you requested in https://github.com/fastlane/fastlane/pull/16646

It looks like the change never got applied to the release version, I think these two are related

Let me know if I can provide any additional info/fix

**Comment by litebluetips** [comment]
I faced similar kind of issue last time, I am still searching for some proper solution
