### ISSUE TITLE
FastlaneCore::Interface::FastlaneShellError

### ISSUE THREAD

**Issue by qcks** [fastlane/fastlane#20259]
```

FAILURE: Build failed with an exception.

* What went wrong:
  Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
> Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
> Execution failed for JetifyTransform: /Users/user/work/MyProject/bundle_store/MyApp/build/app/intermediates/flutter/debug/libs.jar.
> Transform's input file does not exist: /Users/user/work/MyProject/bundle_store/MyApp/build/app/intermediates/flutter/debug/libs.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
379 actionable tasks: 325 executed, 54 up-to-date
\e[0m
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/3.0.0/forwardable.rb:238:in `sh'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
from Fastfile:33:in `block (2 levels) in parsing_binding'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/lane.rb:33:in `call'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
from /Users/user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.205.2/bin/fastlane:23:in `<top (required)>'
from /Users/user/.rbenv/versions/3.0.4/bin/fastlane:25:in `load'
from /Users/user/.rbenv/versions/3.0.4/bin/fastlane:25:in `<main>'
user@MacBook-Pro fastlane % 

```

**Comment by Erin69** [comment]
Methods inherited from FastlaneException
#caused_by_calling_ui_method?
