### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by lukepighetti** [fastlane/fastlane#20260]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

This Fastfile was working without any issues about a month ago. Went to run it today and received a `429` `RATE_LIMIT_EXCEEDED` error when trying to upload the binary to the App Store

##### Command executed

```
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    optional_changelog = options[:CHANGELOG]
    
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_symbols_to_crashlytics(dsym_path: "Runner.app.dSYM.zip")
    upload_to_testflight(
      changelog: optional_changelog,
    )
  end
end

```

##### Complete output when running fastlane, including the stack trace and command used

<details>

```
[08:15:35]: $ /usr/bin/xcrun /opt/homebrew/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.205.2/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/rd/3_d2xrys0ss934g5lhs2tky40000gn/T/gym_config20220510-41515-vlc907.plist' -archivePath /Users/lukepighetti/Library/Developer/Xcode/Archives/2022-05-10/Runner\ 2022-05-10\ 08.14.42.xcarchive -exportPath '/var/folders/rd/3_d2xrys0ss934g5lhs2tky40000gn/T/gym_output20220510-41515-ig9hz2' 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/rd/3_d2xrys0ss934g5lhs2tky40000gn/T/gym_config20220510-41515-vlc907.plist -archivePath '/Users/lukepighetti/Library/Developer/Xcode/Archives/2022-05-10/Runner 2022-05-10 08.14.42.xcarchive' -exportPath /var/folders/rd/3_d2xrys0ss934g5lhs2tky40000gn/T/gym_output20220510-41515-ig9hz2
2022-05-10 08:15:36.204 xcodebuild[44958:806735] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-10 08:15:36.204 xcodebuild[44958:806735] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-10 08:15:36.325 xcodebuild[44958:806735] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/rd/3_d2xrys0ss934g5lhs2tky40000gn/T/Runner_2022-05-10_08-15-36.325.xcdistributionlogs".
error: exportArchive: The request rate limit has been reached.: We’ve received too many API requests for this API key in the past 60 seconds. Please wait and try again.

Error Domain=ITunesSoftwareServiceErrorDomain Code=-19211 "The request rate limit has been reached.: We’ve received too many API requests for this API key in the past 60 seconds. Please wait and try again." UserInfo={status=429, code=RATE_LIMIT_EXCEEDED, title=The request rate limit has been reached., detail=We’ve received too many API requests for this API key in the past 60 seconds. Please wait and try again., NSLocalizedDescription=The request rate limit has been reached.: We’ve received too many API requests for this API key in the past 60 seconds. Please wait and try again., NSLocalizedFailureReason=Unable to perform upload.}

** EXPORT FAILED **
[08:15:39]: Exit status: 70

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.205.2                 |
| export_method | app-store               |
| sdk           | iPhoneOS15.4.sdk        |
+---------------+-------------------------+
```
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by tijm-wolters** [comment]
Also having this issue!

**Comment by sayard** [comment]
Experiencing the same issues, the builds were working fine 4-5 days ago

**Comment by lukepighetti** [comment]
App Store status appears to be green FWIW https://developer.apple.com/system-status/

**Comment by lukepighetti** [comment]
@sayard @tijm-wolters, are you dealing with a Flutter app?

**Comment by sayard** [comment]
@lukepighetti No, React Native in my case

**Comment by joshdholtz** [comment]
✨ OFFICIAL UPDATE

It looks like there are a lot of people have errors with this. There is a post on the Apple forums about it - https://developer.apple.com/forums/thread/705599

I'm going to assume this is probably **not** an issue that we can fix in _fastlane_ if its happening in all of the upload methods 😬 

But I will continue to observe!

---

Also, if we could not comment an "+1" and save the comments for anything that either helps debugging or has any status updates on Apple fixing this that would be 🔥 🙌

**Comment by JulesPatry** [comment]
Just to add more details to this issue,
fastlane's `build_app` method for my react native project is experiencing this issue deploying it to test flight.
`build_app(workspace: "PROJECT_NAME.xcworkspace", scheme: "PROJECT_NAME", clean: true, silent: false)`

**Comment by designervoid** [comment]
I have issue with packaging up the application. Anyone else?
```
ERROR [2022-05-10 19:58:36.73]: Error packaging up the application
```
Last 2 trace of logs:
```
/usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.205.2/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': \e[31m[!] Error packaging up the application\e[0m (FastlaneCore::Interface::FastlaneBuildFailure)
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.205.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        ```

**Comment by designervoid** [comment]
App Store fixed issues in `AMP - Developer Content Delivery`.
It's okay to deploy now.
That problem not with the `Fastlane`.
