### ISSUE TITLE
Fastfile:47:in `[]=': \e[31m[!] regexp not matched\e[0m (IndexError)

### ISSUE THREAD

**Issue by YingYou** [fastlane/fastlane#20289]
```
 from Fastfile:47:in `block in parsing_binding'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:127:in `platform'
        from Fastfile:28:in `parsing_binding'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/lane_manager.rb:15:in `new'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/lane_manager.rb:15:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/bin/fastlane:25:in `load'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/bin/fastlane:25:in `<main>'
Fastfile:47:in `[]=': regexp not matched (IndexError)
        from Fastfile:47:in `block in parsing_binding'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:127:in `platform'
        from Fastfile:28:in `parsing_binding'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/lane_manager.rb:15:in `new'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/lane_manager.rb:15:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/gems/fastlane-2.206.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/bin/fastlane:25:in `load'
        from /usr/local/Cellar/fastlane/2.205.2/libexec/bin/fastlane:25:in `<main>'
```

**Comment by lacostej** [comment]
This looks like an error in your Fastfile.  The parser complains in lines 28/47. 

I am closing this. Please reopen if you have more information.
