### ISSUE TITLE
After installing the plugin a problem occurs: no fastlane commands work.

### ISSUE THREAD

**Issue by eoshtanko** [fastlane/fastlane#20310]
### Discussed in https://github.com/fastlane/fastlane/discussions/20309

<div type='discussions-op-text'>

<sup>Originally posted by **eoshtanko** May 22, 2022</sup>
I'm trying to connect a plugin "discord_notifier": https://github.com/nikolas-theodosis/fastlane-discord_notifier (you can find it in this list: https://docs.fastlane.tools/plugins/available-plugins/)

After installing the plugin, a problem occurs: no fastlane commands work. The error occurs even when trying to call system commands like "bundle exec fastlane -v". I just can't call fastlane. But once I remove one line `gem 'fastlane-plugin-discord_notifier'` from the Pluginfile, everything starts working correctly again.
(It is also worth noting that I work locally, in the terminal)

------------------------------------------------------------------------------------------------
**Error:**
------------------------------------------------------------------------------------------------

```
[⠋] 🚀 bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/3.1.0/bin/fastlane)
/usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane/lib/fastlane/cli_tools_distributor.rb:126:in `ensure in take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError)

        FastlaneCore::UpdateChecker.show_update_status('fastlane', Fastlane::VERSION)
                    ^^^^^^^^^^^^^^^
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane/lib/fastlane/cli_tools_distributor.rb:126:in `take_off'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.1.0/bin/fastlane:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli.rb:483:in `exec'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/exe/bundle:36:in `<top (required)>'
	from /usr/local/opt/ruby/bin/bundle:25:in `load'
	from /usr/local/opt/ruby/bin/bundle:25:in `<main>'
/usr/local/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'sodium': dlopen(sodium, 0x0005): tried: 'sodium' (no such file), '/usr/local/lib/sodium' (no such file), '/usr/lib/sodium' (no such file), '/Users/miss.ekaterina/chat-app-eoshtanko/ChatApp/sodium' (no such file), '/usr/local/lib/sodium' (no such file), '/usr/lib/sodium' (no such file). (LoadError)
Could not open library 'libsodium.dylib': dlopen(libsodium.dylib, 0x0005): tried: 'libsodium.dylib' (no such file), '/usr/local/lib/libsodium.dylib' (no such file), '/usr/lib/libsodium.dylib' (no such file), '/Users/miss.ekaterina/chat-app-eoshtanko/ChatApp/libsodium.dylib' (no such file), '/usr/local/lib/libsodium.dylib' (no such file), '/usr/lib/libsodium.dylib' (no such file)
	from /usr/local/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
	from /usr/local/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `ffi_lib'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium.rb:12:in `extended'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:9:in `extend'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:9:in `<module:Version>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:6:in `<module:Sodium>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:4:in `<module:RbNaCl>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rbnacl-3.4.0/lib/rbnacl/sodium/version.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rbnacl-3.4.0/lib/rbnacl.rb:4:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rbnacl-3.4.0/lib/rbnacl.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/jwt-2.3.0/lib/jwt/signature.rb:7:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/jwt-2.3.0/lib/jwt/signature.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/jwt-2.3.0/lib/jwt/decode.rb:5:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/jwt-2.3.0/lib/jwt/decode.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/jwt-2.3.0/lib/jwt.rb:5:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/jwt-2.3.0/lib/jwt.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/spaceship/lib/spaceship/connect_api/token.rb:1:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/spaceship/lib/spaceship/connect_api/token.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/spaceship/lib/spaceship/connect_api.rb:3:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/spaceship/lib/spaceship/connect_api.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane_core/lib/fastlane_core/build_watcher.rb:1:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane_core/lib/fastlane_core/build_watcher.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane_core/lib/fastlane_core.rb:11:in `require_relative'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane_core/lib/fastlane_core.rb:11:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane/lib/fastlane.rb:1:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane/lib/fastlane.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane/lib/fastlane/cli_tools_distributor.rb:41:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/fastlane/lib/fastlane/cli_tools_distributor.rb:41:in `take_off'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.206.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.1.0/bin/fastlane:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli.rb:483:in `exec'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/exe/bundle:36:in `<top (required)>'
	from /usr/local/opt/ruby/bin/bundle:25:in `load'
	from /usr/local/opt/ruby/bin/bundle:25:in `<main>'
```

------------------------------------------------------------------------------------------------
**Gemfile:**
------------------------------------------------------------------------------------------------
```
# frozen_string_literal: true

source "https://rubygems.org"

gem "cocoapods", "1.11.3"
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

------------------------------------------------------------------------------------------------
**Pluginfile:**
------------------------------------------------------------------------------------------------

```
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-discord_notifier'
```

------------------------------------------------------------------------------------------------
**Fastlane environment:**
------------------------------------------------------------------------------------------------
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.0.1                                      |
| Ruby                        | 3.1.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.23.0                          |
| Installation Source         | /usr/local/lib/ruby/gems/3.1.0/bin/fastlane |
| Host                        | macOS 12.0.1 (21A559)                       |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.1.2/lib            |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                      |
| Swift Version               | 5.5.2                                       |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.1 | ✅ Up-To-Date  |

**Comment by lucgrabowski** [comment]
This is not a fastlane issue ;) You should install libsodium with homebrew and it should solve the problem
>Could not open library 'sodium': dlopen(sodium, 0x0005): tried: 'sodium' (no such file), ...

**Comment by Daneyl** [comment]
Had to update fastlane via `gem update fastlane` and then it worked for me

**Comment by dakshatsuraasa** [comment]
Still facing this issue.
