### ISSUE TITLE
Better exception message when localizing an iOS app 

### ISSUE THREAD

**Issue by vanniktech** [fastlane/fastlane#20336]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I've started localizing my app for a bunch of new languags and when pushing the changes I don't get the locale for which the app name is already registered.

##### Complete output when running fastlane, including the stack trace and command used

```
[00:11:17]: Will begin uploading metadata for '1.2.0' on App Store Connect
[00:11:17]: Uploading metadata to App Store Connect for version
[00:11:20]: Uploading metadata to App Store Connect for localized version 'de-DE'
[00:11:20]: Uploading metadata to App Store Connect for localized version 'it'
[00:11:20]: Uploading metadata to App Store Connect for localized version 'pt-BR'
[00:11:20]: Uploading metadata to App Store Connect for localized version 'tr'
[00:11:20]: Uploading metadata to App Store Connect for localized version 'pt-PT'
[00:11:20]: Uploading metadata to App Store Connect for localized version 'ru'
[00:11:20]: Uploading metadata to App Store Connect for localized version 'fr-FR'
[00:11:20]: Uploading metadata to App Store Connect for localized version 'es-ES'
[00:11:20]: Uploading metadata to App Store Connect for localized version 'fi'
[00:11:20]: Uploading metadata to App Store Connect for localized version 'en-US'
[00:11:21]: Uploading metadata to App Store Connect for localized version 'nl-NL'
[00:11:21]: Uploading metadata to App Store Connect for localized version 'uk'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'fr-FR'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'de-DE'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'pt-PT'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'it'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'en-US'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'fi'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'uk'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'pt-BR'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'nl-NL'
[00:11:24]: Uploading metadata to App Store Connect for localized info 'es-ES'
[00:11:26]: Uploading metadata to App Store Connect for localized info 'ru'
[00:11:26]: Uploading metadata to App Store Connect for localized info 'tr'
#<Thread:0x00007f89e418e1e0@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/queue_worker.rb:37 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
	5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/deliver/lib/deliver/upload_metadata.rb:218:in `block in upload'
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/models/app_info_localization.rb:34:in `update'
	3: from /Library/Ruby/Gems/2.6.0/gems/forwardable-1.3.1/lib/forwardable.rb:235:in `patch_app_info_localization'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:720:in `patch_app_info_localization'
	1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': The provided entity includes an attribute with a value that has already been used on a different account. - The app name you entered is already being used. If you have trademark rights to this name and would like it released for your use, submit a claim. - /data/attributes/name (Spaceship::UnexpectedResponse)
+--------------------+----------------------------------------------------------------------------------------------------------+
|                                                         Lane Context                                                          |
+--------------------+----------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                                      |
| PLATFORM_NAME      | ios                                                                                                      |
| LANE_NAME          | ios build_upload                                                                                         |
| IPA_OUTPUT_PATH    | /Users/niklas/dev/GitHub/vanniktech/ios/MeditationTimer/Meditation Timer.ipa                             |
| XCODEBUILD_ARCHIVE | /Users/niklas/Library/Developer/Xcode/Archives/2022-06-01/Meditation Timer 2022-06-01 00.09.17.xcarchive |
| DSYM_OUTPUT_PATH   | /Users/niklas/dev/GitHub/vanniktech/ios/MeditationTimer/Meditation Timer.app.dSYM.zip                    |
+--------------------+----------------------------------------------------------------------------------------------------------+
[00:11:28]: The provided entity includes an attribute with a value that has already been used on a different account. - The app name you entered is already being used. If you have trademark rights to this name and would like it released for your use, submit a claim. - /data/attributes/name
```

It's not really clear which locale is the one that's causing this. Ideally, this would be stated somewhere.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.6                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.33.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.6 (20G165)                                            |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This should make uploading to Apple much much faster.
ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t HTTP,Aspera,Signiant'
ENV['FASTLANE_ITC_TEAM_ID'] = '122415194' # This does deviate from Team ID on purpose! 122415194 (Niklas Baudy)
ENV["DELIVER_USER"] = "niklas.baudy@vanniktech.de"

default_platform(:ios)

platform :ios do
  lane :upload_dsyms do
    download_dsyms(version: "1.2.0", app_identifier: "com.vanniktech.meditationtimer.ios",)
    upload_symbols_to_crashlytics(gsp_path: "../MeditationTimer/GoogleService-Info.plist", binary_path: '../')
    clean_build_artifacts
  end

  lane :build_upload do |options|
    team_id("779A4D7K9R")

    build_app(
      scheme: "MeditationTimer",
      workspace: "../Vanniktech.xcworkspace",
      include_bitcode: true,
      export_team_id: "779A4D7K9R",
    )

    upload_to_app_store(
      skip_screenshots: !options[:uploadScreenshots],
      overwrite_screenshots: options[:uploadScreenshots],
      force: true,
      automatic_release: true,
    )
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.2       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.18.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.12.0       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.573.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.130.0      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| CFPropertyList                  | 3.0.5        |
| json                            | 2.6.1        |
| bundler                         | 2.3.9        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.1       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.2        |
| webrick                         | 1.7.0        |
| rake                            | 13.0.6       |
| forwardable                     | 1.3.1        |
| logger                          | 1.3.0        |
| date                            | 3.0.1        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| net-http-persistent             | 2.9.4        |
| net-http-pipeline               | 1.0.1        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.5.6        |
| fileutils                       | 1.4.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2022-06-01**
</details>

**Comment by vanniktech** [comment]
After looking at every locale (10+) I found the bad guy:

<img width="1125" alt="Screen Shot 2022-06-05 at 21 09 43" src="https://user-images.githubusercontent.com/5759366/172066614-08aa729b-19bd-425f-b17d-558848ae35f3.png">

Also the error message from the website tells me the locale (Spanish). It would be super helpful if fastlane did too.

**Comment by vanniktech** [comment]
Yeah still an issue.

**Comment by vanniktech** [comment]
Still an issue: 

```
[22:15:55]: The provided entity includes an attribute with a value that has already been used on a different account. - The app name you entered is already being used. If you have trademark rights to this name and would like it released for your use, submit a claim. - /data/attributes/name
```

getting this with version 2.208.0

**Comment by vanniktech** [comment]
Yeah still an issue. Leave me alone @fastlane-bot

**Comment by vanniktech** [comment]
I don't like you @fastlane-bot
