### ISSUE TITLE
Error when using `--game-center ios` setting

### ISSUE THREAD

**Issue by luisbosch** [fastlane/fastlane#20366]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We were running into with fastlane today, when trying to fetch information to build apps. It was running fine until we got reports of build failing today and the `game_center` setting seemed to be causing issue. We removed it and we're able to build now.

##### Command executed

```
fastlane produce enable_services --username #{options[:username]} --app_identifier \"#{options[:app_identifier]}\" --team_id #{options[:team_id]} --team_name \"#{options[:team_name]}\" --associated-domains --game-center ios --in-app-purchase
```

##### Complete output when running fastlane, including the stack trace and command used

Same command as above

```
[16:15:36]: Enabling services
[16:15:36]: 	Game Center

Looking for related GitHub issues on fastlane/fastlane...

/usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': \\e[31m[!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "e0b36ae4-b12d-42e4-8bfb-a73735d969b7",
    "status" : "409",
    "code" : "ENTITY_ERROR.ATTRIBUTE.INVALID",
    "title" : "An attribute in the provided entity has invalid value",
    "detail" : "The attribute 'settings' is invalid: 'GAME_CENTER_SETTING is not allowed for capability GAME_CENTER'",
    "source" : {
      "pointer" : "data/attributes/settings"
    }
  } ]
}\\e[0m
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:121:in `patch_bundle_id_capability'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `patch_bundle_id_capability'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/models/bundle_id.rb:88:in `update_capability'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/produce/lib/produce/service.rb:209:in `update'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/produce/lib/produce/service.rb:31:in `enable'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/produce/lib/produce/service.rb:12:in `enable'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/produce/lib/produce/commands_generator.rb:119:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/produce/lib/produce/commands_generator.rb:334:in `run'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/produce/lib/produce/commands_generator.rb:18:in `start'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/bin/fastlane:25:in `load'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/bin/fastlane:25:in `<main>'
\e[0m
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/fast_file.rb:223:in `block in sh'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/fast_file.rb:222:in `sh'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/fast_file.rb:216:in `sh'
	from Fastfile:218:in `block (2 levels) in parsing_binding'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/gems/fastlane-2.206.2/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/bin/fastlane:25:in `load'
	from /usr/local/Cellar/fastlane/2.206.2/libexec/bin/fastlane:25:in `<main>'
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by tguidon** [comment]
We're seeing an error that may be related. We use `fastlane produce` to create new client apps in the App Store and when running the following command, it looks like it's auto enabling Game Center, even though we do not include this capability in our Xcode project.

```ruby
produce(
  app_identifier: ENV["PRODUCT_BUNDLE_IDENTIFIER"],
  team_id: ENV["DEVELOPMENT_TEAM"],
  itc_team_id: ENV["ITC_TEAM_ID"],
  company_name: ENV["COMPANY_NAME"]
)
```

Modifying this command to be the following, will still turn on Game Center even though we pass in `off`.

```ruby
produce(
  app_identifier: ENV["PRODUCT_BUNDLE_IDENTIFIER"],
  team_id: ENV["DEVELOPMENT_TEAM"],
  itc_team_id: ENV["ITC_TEAM_ID"],
  company_name: ENV["COMPANY_NAME"],
  enable_services: {
    game_center: "off"
  }
)
```

The issue then arrises when we try and build this app after creating it with the above fastlane produce action. The following error is returned on CircleCI:

```bash
[17:51:27]: \e[31mError uploading ipa file: 
 [Transporter Error Output]: ERROR ITMS-90045: Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, key 'com.apple.developer.game-center' in 'Payload/$REDACTED.app/$REDACTED' is not supported.\r
[Transporter Error Output]: Return status of iTunes Transporter was 1: ERROR ITMS-90045: Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, key 'com.apple.developer.game-center' in 'Payload/$REDACTED.app/$REDACTED' is not supported.\r
[Transporter Error Output]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.\e[0m
```

I saw there were Game Center updates at WWDC earlier this week, I wonder if this is related? 

To resolve this issue, we have two solutions:
- Manually go into "Certificates, Identifiers & Profiles" at https://developer.apple.com/account/resources/identifiers/list and turn off Game Center for the given Identifier.
- Running `bundle exec fastlane produce disable_services -a com.marianatek.example --game-center --itc_team_id VALUE --team_id VALUE`

After one of those is completed, we can regenerate the provisioning profile with Match and the same `fastlane testflight` action will now succeed.

**Comment by shizu2014** [comment]
same progblem,game_center: "on"，Automatically open when creating app

**Comment by litebluetips** [comment]
I faced similar kind of issue last time, I am still searching for some proper solution

**Comment by RedFlus** [comment]
> Hi. Just to add, I'm also seeing game_center automatically being turned on when running produce. It seemed to start happening a couple of days after WWDC, and some Apple updates to the developer portal.

I have same question and didn't get satisfied solution.

**Comment by chandanchoubey112** [comment]
I am experiencing the same, `game_center: on` by default, Any news ?

**Comment by davidfrasch** [comment]
This is still an issue, even when doing 
```
enable_services: {
    game_center: "off"
  }
```

**Comment by assembleMHN** [comment]
Im still seeing this, and i cant get 

`	modify_services(
	  username: ENV["APPLE_ID"],
	  app_identifier: ENV["APP_IDENTIFIER"],
	  services: appFeatures
	)`

To turn it off, any news?
