### ISSUE TITLE
Resign command causes " No such file or directory - security" Error

### ISSUE THREAD

**Issue by dougblackjr** [fastlane/fastlane#20414]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running the `resign` command in the CLI, the process fails and gives an error of `No such file or directory - security`.

##### Command executed
`bundle exec fastlane run resign signing_identity:"Apple Distribution: MY COMPANY" provisioning_profile:my.mobileprovision ipa:my.ipa`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀 
[06:44:52]: --------------------
[06:44:52]: --- Step: resign ---
[06:44:52]: --------------------

[06:44:52]: Error accessing file, this might be due to fastlane's directory handling
[06:44:52]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
/var/lib/gems/3.0.0/gems/fastlane-2.206.2/sigh/lib/sigh/resign.rb:205:in ``': No such file or directory - security (Errno::ENOENT)
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/sigh/lib/sigh/resign.rb:205:in `request_valid_identities'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/sigh/lib/sigh/resign.rb:189:in `installed_identities'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/sigh/lib/sigh/resign.rb:131:in `sha1_for_signing_identity'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/sigh/lib/sigh/resign.rb:122:in `find_signing_identity'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/sigh/lib/sigh/resign.rb:37:in `resign'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/sigh/lib/sigh/resign.rb:19:in `resign'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/resign.rb:9:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/one_off.rb:42:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/one_off.rb:22:in `execute'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /var/lib/gems/3.0.0/gems/fastlane-2.206.2/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:25:in `load'
        from /usr/local/bin/fastlane:25:in `<top (required)>'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/cli/exec.rb:58:in `load'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/cli/exec.rb:23:in `run'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/cli.rb:479:in `exec'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/cli.rb:31:in `dispatch'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/cli.rb:25:in `start'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/exe/bundle:48:in `block in <top (required)>'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /var/lib/gems/3.0.0/gems/bundler-2.3.16/exe/bundle:36:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre>
### Stack

| Key                         | Value                                                                 |
| --------------------------- | --------------------------------------------------------------------- |
| OS                          | debian_based bookworm/sid                                             |
| Ruby                        | 3.0.2                                                                 |
| Bundler?                    | false                                                                 |
| Git                         | git version 2.34.1                                                    |
| Installation Source         | /usr/local/bin/fastlane                                               |
| Host                        | Pop!_OS 22.04 LTS debian_based bookworm/sid (5.17.5-76051705-generic) |
| Ruby Lib Dir                | /usr/lib                                                              |
| OpenSSL Version             | OpenSSL 3.0.2 15 Mar 2022                                             |
| Is contained                | false                                                                 |
| Is homebrew                 | false                                                                 |
| Is installed via Fabric.app | false                                                                 |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_US:en    | 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.6.0        |
| google-apis-playcustomapp_v1    | 0.9.0        |
| google-apis-androidpublisher_v3 | 0.23.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.12.0       |
| google-apis-storage_v1          | 0.16.0       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.2       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.601.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.131.2      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.1        |
| excon                           | 0.92.3       |
| json                            | 2.6.2        |
| rubyzip                         | 2.3.2        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.16       |
| multi_json                      | 1.15.0       |
| rake                            | 13.0.6       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| openssl                         | 3.0.0        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| etc                             | 1.2.0        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| mini_portile2                   | 2.7.1        |
| nokogiri                        | 1.13.1       |
| racc                            | 1.5.1        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
| oj                              | 3.13.9       |
| bigdecimal                      | 3.0.0        |
</details>

</pre>
</details>

**Comment by dougblackjr** [comment]
Is there any update on this? Has this been updated in new releases?
