### ISSUE TITLE
[!] undefined method `resolved_build_setting' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CongHaipeng** [fastlane/fastlane#20435]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.6                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.6 (20G165)                                            |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#---------- begin -----------

def update_build_number()
currentTime = Time.new.strftime("%Y%m%d")
    build = get_build_number()
    if build.include?"#{currentTime}."
      # => 为当天版本 计算迭代版本号
      lastStr = build[build.length-2..build.length-1]
      lastNum = lastStr.to_i
      lastNum = lastNum + 1
      lastStr = lastNum.to_s
      if lastNum < 10
        lastStr = lastStr.insert(0,"0")
      end
        build = "#{currentTime}.#{lastStr}"
      else
        # => 非当天版本 build 号重置
        build = "#{currentTime}.01"
    end
    puts("*************| 更新build #{build} |*************")
    # => 更改项目 build 号
    increment_build_number(
      build_number: "#{build}"
    )
end

def prepare_version(options)

    # 正式版本号
    increment_version_number(
        version_number: options[:version]
    )

    # 构建版本号
    update_build_number()
 end

 def get_update_description()

     return "版本号:\n\b\b#{ENV['APP_VERSION_RELEASE']} \n更新描述:\n\b\b#{ENV['RELEASE_NOTES']}"
   
 end

#---------- end -------------

#---------- begin -----------

fastlane_version "2.54.3"

default_platform :ios

platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "1).学习公社云 发布到 蒲公英"
  lane :beta_main_pgy do
    sh "fastlane beta_pgy --env StudyCommune"
  end

  desc "2).学习家园 发布到 蒲公英"
  lane :beta_plus_pgy do
    sh "fastlane beta_pgy --env LearningHome"
  end

  desc "3).学习公社云 发布到 苹果商店"
  lane :release_mian_apple do
    sh "fastlane release_apple --env StudyCommune"
  end

  desc "4).学习家园 发布到 苹果商店"
  lane :release_plus_apple do
    sh "fastlane release_apple --env LearningHome"
  end

  desc "5).学习公社云 和 学习家园 同时 发布到 蒲公英"
  lane :beta_all_pgy do
    sh "fastlane beta_pgy --env StudyCommune"
    sh "fastlane beta_pgy --env LearningHome"
  end

  desc "6).学习公社云 和 学习家园 同时 发布到 苹果TestFlight"
  lane :beta_all_apple do
    sh "fastlane beta_apple --env StudyCommune"
    sh "fastlane beta_apple --env LearningHome"
  end

  desc "7).学习公社云 和 学习家园 同时 发布到 苹果商店"
  lane :release_all_apple do
    sh "fastlane release_apple --env StudyCommune"
    sh "fastlane release_apple --env LearningHome"
  end

  desc "发布 指定版本 到 蒲公英"
  lane :beta_pgy do
    # 更新版本号
    increment_version_number_in_plist(target: ENV['SCHEME_NAME'], version_number: ENV['APP_VERSION_RELEASE'])
    
    gym(scheme: ENV['SCHEME_NAME'], 
      export_method: "ad-hoc",
      silent: true,  # 隐藏没有必要的信息
      clean: true  # 在构建前先clean
        )
    pgyer(api_key: "e4a56227c4e3a71d3825114f0d67827e", 
      user_key: "d70d3edcd40382fb8806bde319848f14", 
      update_description: get_update_description(), 
      password: "123456", 
      install_type: "2")
  end

  desc "发布 指定版本 到 苹果TestFlight"
  lane :beta_apple do

    # 更新版本号
    increment_version_number_in_plist(target: ENV['SCHEME_NAME'], version_number: ENV['APP_VERSION_RELEASE'])
    
    gym(scheme: ENV['SCHEME_NAME'],
      silent: true,  # 隐藏没有必要的信息
      clean: true  # 在构建前先clean
      )
    pilot
  end

  desc "发布 指定版本 到 苹果商店"
  lane :release_apple do

    # 更新版本号
    increment_version_number_in_plist(target: ENV['SCHEME_NAME'], 
      version_number: ENV['APP_VERSION_RELEASE'])
    
    gym(scheme: ENV['SCHEME_NAME'], 
      silent: true,  # 隐藏没有必要的信息
      clean: true  # 在构建前先clean
      )
    deliver
  end

#---------- end -------------

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

app_identifier ENV['APP_IDENTIFIER'] # The bundle identifier of your app

apple_id ENV['APPLE_ID'] # Your Apple email address

team_id ENV['TEAM_ID'] # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.207.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-pgyer      | 0.2.2   | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.5.1   | ✅ Up-To-Date  |
| fastlane-plugin-pgyer      | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 1.17.2       |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.24.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.17.0       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.37.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.602.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.131.2      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| CFPropertyList                  | 3.0.5        |
| json                            | 2.6.2        |
| webrick                         | 1.7.0        |
| rake                            | 13.0.6       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
| fastlane-plugin-pgyer           | 0.2.2        |
| fastlane-plugin-versioning      | 0.5.1        |
</details>

*generated on:* **2022-07-05**
</details>
How can I solve it

**Comment by crazymanish** [comment]
can you please post logs! exception/error stack-trace?

**Comment by idanbuberman** [comment]
same here.
![Screen Shot 2022-08-30 at 14 19 30](https://user-images.githubusercontent.com/6490582/187423671-da12e010-4d8d-446f-b9ce-53de371d1073.png)

`bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/3.0.0/bin/fastlane)
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-plugin-versioning-0.5.1/lib/fastlane/plugin/versioning/actions/get_info_plist_path.rb:38:in `find_path_using_target': \e[31m[!] undefined method `resolved_build_setting' for nil:NilClass\e[0m (NoMethodError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-plugin-versioning-0.5.1/lib/fastlane/plugin/versioning/actions/get_info_plist_path.rb:17:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-plugin-versioning-0.5.1/lib/fastlane/plugin/versioning/actions/increment_version_number_in_plist.rb:38:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:117:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:153:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.209.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/cli.rb:485:in `exec'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.20/exe/bundle:36:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'`

**Comment by idanbuberman** [comment]
Solved! all I added to do (for some reason...) - `build_configuration_name`!!!!!!!!

💪🏻🍭

**Comment by lucasGabrielDeAA** [comment]
For me the solution was to review the target name, and the issue was caused by a wrong capitalized string used as target's name.

For example: `OneSignalServiceExtensionFoobar` and I was trying to increment the number using the following name `OnesignalServiceExtensionFooBar`.

After changed this, the problem was solved

**Comment by iBotPeaches** [comment]
Doing some backlog cleanup. Sorry for notification. This hopefully was fixed, but the only stacktrace provided shows its an issue in a 3rd party plugin and not core - https://github.com/SiarheiFedartsou/fastlane-plugin-versioning

Thanks.
