### ISSUE TITLE
Fastlane Android Setup Issue

### ISSUE THREAD

**Issue by jigneshoxit** [fastlane/fastlane#20446]
/Users/Jignesh/.rubies/ruby-3.1.2/lib/ruby/3.1.0/open3.rb:222:in `spawn': \e[31m[!] Permission denied - /Users/Jignesh/Desktop/jignesh/iOS/MyProjects/nps-android-mobile-app/gradlew\e[0m (Errno::EACCES)
        from /Users/Jignesh/.rubies/ruby-3.1.2/lib/ruby/3.1.0/open3.rb:222:in `popen_run'
        from /Users/Jignesh/.rubies/ruby-3.1.2/lib/ruby/3.1.0/open3.rb:210:in `popen2e'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
        from /Users/Jignesh/.rubies/ruby-3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `sh'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:42:in `block (2 levels) in parsing_binding'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/Jignesh/.gem/ruby/3.1.2/gems/fastlane-2.207.0/bin/fastlane:23:in `<top (required)>'
        from /Users/Jignesh/.gem/ruby/3.1.2/bin/fastlane:25:in `load'
        from /Users/Jignesh/.gem/ruby/3.1.2/bin/fastlane:25:in `<main>'

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.2                                        |
| Ruby                        | 3.1.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.32.1 (Apple Git-133)          |
| Installation Source         | ~/.gem/ruby/3.1.2/bin/fastlane              |
| Host                        | macOS 12.2 (21D49)                          |
| Ruby Lib Dir                | ~/.rubies/ruby-3.1.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1o  3 May 2022                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.4                                        |
| Swift Version               | 5.6.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  desc "Send Notification to Slack"
  lane :slack_notification do |options|
    build_number = android_get_version_code()
    version_number = android_get_version_name()
    slack(
      slack_url: ENV['SLACK_URL'],
      message: "",
      success: true, # Optional, defaults to true.
      payload: {  # Optional, lets you specify any number of your own Slack attachments.
        "Project" => "Watercop",
        "Platform:" => "Android",
        "Environment" => ENV['ANDROID_BUILD_FLAVOUR'],
        "Version" => "#{version_number}\(#{build_number}\)",
        "Build Date" => Time.new.to_s,
        "Release Notes" => options[:releaseNote],
      },
      default_payloads: [],
    )
  end

  desc "Build Android"
  lane :buildAndroid do
    gradle(
      task: "clean",
    )
    gradle(
      task: "assemble",
      flavor: ENV['ANDROID_BUILD_FLAVOUR'],
      build_type: "Release",
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.oxit.watercop") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.207.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.4   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android        | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| error_highlight                           | 0.3.0        |
| did_you_mean                              | 1.6.1        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.6.0        |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.5        |
| public_suffix                             | 4.0.7        |
| addressable                               | 2.8.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| optparse                                  | 0.1.1        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| babosa                                    | 1.0.4        |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| excon                                     | 0.92.3       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| faraday-multipart                         | 1.0.4        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.0       |
| unf_ext                                   | 0.0.8.2      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.5        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.6        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.1        |
| dotenv                                    | 2.7.6        |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.4.1        |
| emoji_regex                               | 3.2.3        |
| aws-eventstream                           | 1.2.0        |
| aws-sigv4                                 | 1.5.0        |
| aws-sdk-kms                               | 1.57.0       |
| aws-sdk-s3                                | 1.114.0      |
| set                                       | 1.0.2        |
| nanaimo                                   | 0.3.0        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.1.0        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.22.0       |
| json                                      | 2.6.2        |
| bundler                                   | 2.3.7        |
| webrick                                   | 1.7.0        |
| httpclient                                | 2.8.3        |
| multi_json                                | 1.15.0       |
| signet                                    | 0.17.0       |
| os                                        | 1.1.4        |
| memoist                                   | 0.16.2       |
| googleauth                                | 1.2.0        |
| mini_mime                                 | 1.1.2        |
| retriable                                 | 3.1.2        |
| trailblazer-option                        | 0.1.2        |
| declarative                               | 0.0.20       |
| uber                                      | 0.1.0        |
| representable                             | 3.2.0        |
| google-apis-core                          | 0.7.0        |
| google-apis-playcustomapp_v1              | 0.10.0       |
| google-apis-androidpublisher_v3           | 0.24.0       |
| rake                                      | 13.0.6       |
| digest-crc                                | 0.6.4        |
| google-apis-storage_v1                    | 0.17.0       |
| google-apis-iamcredentials_v1             | 0.13.0       |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-env                          | 1.6.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.37.0       |
| aws-partitions                            | 1.603.0      |
| jmespath                                  | 1.6.1        |
| aws-sdk-core                              | 3.131.2      |
| forwardable                               | 1.3.2        |
| logger                                    | 1.5.0        |
| pathname                                  | 0.2.0        |
| shellwords                                | 0.1.0        |
| cgi                                       | 0.3.1        |
| date                                      | 3.2.2        |
| timeout                                   | 0.2.0        |
| stringio                                  | 3.0.1        |
| securerandom                              | 0.1.1        |
| uri                                       | 0.11.0       |
| openssl                                   | 3.0.0        |
| digest                                    | 3.1.0        |
| io-nonblock                               | 0.1.0        |
| ipaddr                                    | 1.2.4        |
| io-wait                                   | 0.2.1        |
| zlib                                      | 2.1.1        |
| resolv                                    | 0.2.1        |
| time                                      | 0.2.0        |
| open-uri                                  | 0.2.0        |
| mutex_m                                   | 0.1.1        |
| net-protocol                              | 0.1.2        |
| net-http                                  | 0.2.0        |
| ostruct                                   | 0.5.2        |
| english                                   | 0.7.1        |
| erb                                       | 2.2.3        |
| strscan                                   | 3.0.1        |
| abbrev                                    | 0.1.0        |
| io-console                                | 0.5.11       |
| tempfile                                  | 0.1.2        |
| delegate                                  | 0.2.0        |
| fileutils                                 | 1.6.0        |
| tmpdir                                    | 0.1.2        |
| base64                                    | 0.1.1        |
| singleton                                 | 0.1.1        |
| open3                                     | 0.1.1        |
| nkf                                       | 0.1.1        |
| prettyprint                               | 0.1.1        |
| pp                                        | 0.3.0        |
| find                                      | 0.1.1        |
| yaml                                      | 0.2.0        |
| psych                                     | 4.0.3        |
| fastlane-plugin-firebase_app_distribution | 0.3.4        |
| fastlane-plugin-versioning_android        | 0.1.0        |
</details>

*generated on:* **2022-07-08**
</details>

**Comment by jigneshoxit** [comment]
Not an issue
just need to do `chmod +x gradlew`
