### ISSUE TITLE
Unable to access analytics

### ISSUE THREAD

**Issue by lexicalninja** [fastlane/fastlane#20510]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When trying to use the Tunes analytics functions we receive the following error. Other parts of the Tunes module are working, but this one seems to not want to work. Any assistance would be appreciated. 

#### code
```ruby
lane :test do
     Spaceship::Tunes.select_team(team_id: ENV['TEAM_ID'])
     app = Spaceship::Tunes::Application.find(ENV['APP_ID'])
     analytics = app.analytics
     .....
  end
```

#### OUPUT
<details>
[✔] 🚀 
[11:55:41]: fastlane detected a Gemfile in the current directory
[11:55:41]: However, it seems like you didn't use `bundle exec`
[11:55:41]: To launch fastlane faster, please use
[11:55:41]: 
[11:55:41]: $ bundle exec fastlane test
[11:55:41]: 
[11:55:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+---------------------------+---------+-------------------------------------------+
|                                  Used plugins                                   |
+---------------------------+---------+-------------------------------------------+
| Plugin                    | Version | Action                                    |
+---------------------------+---------+-------------------------------------------+
| fastlane-plugin-slack_bot | 1.2.0   | fetch_files_slack, file_upload_to_slack,  |
|                           |         | post_to_slack, update_slack_message       |
+---------------------------+---------+-------------------------------------------+

[11:55:42]: ------------------------------
[11:55:42]: --- Step: default_platform ---
[11:55:42]: ------------------------------
[11:55:42]: Driving the lane 'ios test' 🚀
[11:55:42]: -----------------------------
[11:55:42]: --- Step: setup_circle_ci ---
[11:55:42]: -----------------------------
[11:55:42]: Not running on CI, skipping CI setup
[11:55:42]: ---------------------------------------
[11:55:42]: --- Step: app_store_connect_api_key ---
[11:55:42]: ---------------------------------------
Spaceship::Tunes::Application.all is deprecated
  It's using a temporary patch to keep it from raising an error but things may not work correctly
  Please consider switching to Spaceship::ConnectAPI if you can
  For more details - https://github.com/fastlane/fastlane/pull/20480
[11:56:37]: ERROR REPORT
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios test |
+------------------+----------+
[11:56:37]: <?xml version="1.0" encoding="UTF-8"?>
<String>There is no route for the path 'apps/1559609596/platforms/ios/versions/850821735'.</String>

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | setup_circle_ci           | 0           |
| 3    | app_store_connect_api_key | 0           |
+------+---------------------------+-------------+

[11:56:37]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/client.rb:771:in `parse_response': \e[31m[!] <?xml version="1.0" encoding="UTF-8"?> (Spaceship::UnexpectedResponse)
<String>There is no route for the path 'apps/1559609596/platforms/ios/versions/850821735'.</String>
\e[0m
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/tunes_client.rb:519:in `app_version_data'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/tunes_client.rb:510:in `app_version'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/application.rb:146:in `analytics'
        from Fastfile:120:in `block (2 levels) in parsing_binding'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `load'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `<main>'

</details>

#### Error
```console
/usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/client.rb:771:in `parse_response': \e[31m[!] <?xml version="1.0" encoding="UTF-8"?> (Spaceship::UnexpectedResponse)
<String>There is no route for the path 'apps/1559609596/platforms/ios/versions/850821735'.</String>
\e[0m
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/tunes_client.rb:519:in `app_version_data'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/tunes_client.rb:510:in `app_version'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/spaceship/lib/spaceship/tunes/application.rb:146:in `analytics'
        from Fastfile:122:in `block (2 levels) in parsing_binding'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `load'
        from /usr/local/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `<main>'
```

##### Complete output when running fastlane, including the stack trace and command used

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.208.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-slack_bot | 1.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.25.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.18.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.37.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.608.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.131.3      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
| fastlane-plugin-slack_bot       | 1.2.0        |
</details>

*generated on:* **2022-07-26**
</details>

**Comment by akring** [comment]
Same problem here

**Comment by waitingsnow** [comment]
Same problem, anyone solved this issue?

**Comment by lexicalninja** [comment]
Seems to still be a problem
