### ISSUE TITLE
fastlane match nuke development . undefined method `downcase' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by rainhees** [fastlane/fastlane#20525]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http/generic_request.rb:73:in `[]=': \e[31m[!] undefined method `downcase' for nil:NilClass (NoMethodError)

    @decode_content = false if key.downcase == 'accept-encoding'
                                  ^^^^^^^^^\e[0m
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/storage/gitlab/client.rb:93:in `execute_request'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/storage/gitlab/client.rb:46:in `files'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/storage/gitlab_secure_files.rb:103:in `download'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/nuke.rb:61:in `run'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/commands_generator.rb:181:in `block (3 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/commands_generator.rb:188:in `run'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/commands_generator.rb:26:in `start'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http/generic_request.rb:73:in `[]=': undefined method `downcase' for nil:NilClass (NoMethodError)

    @decode_content = false if key.downcase == 'accept-encoding'
                                  ^^^^^^^^^
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/storage/gitlab/client.rb:93:in `execute_request'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/storage/gitlab/client.rb:46:in `files'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/storage/gitlab_secure_files.rb:103:in `download'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/nuke.rb:61:in `run'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/commands_generator.rb:181:in `block (3 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/commands_generator.rb:188:in `run'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/match/lib/match/commands_generator.rb:26:in `start'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `<main>' </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.5                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.32.1 (Apple Git-133)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.208.0/libexec/bin/fastlane |
| Host                        | macOS 12.5 (21G72)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.4.1                                                     |
| Swift Version               | 5.6.1                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ko_KR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "-.xcodeproj")
    build_app(workspace: "-.xcworkspace", scheme: "-")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier("com.-.app") # The bundle identifier of your app
apple_id("-@-.co.kr") # Your Apple email address

itc_team_id("-") # App Store Connect Team ID
team_id("-") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.208.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.25.0       |
| emoji_regex                     | 3.2.3        |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| excon                           | 0.92.4       |
| json                            | 2.6.2        |
| dotenv                          | 2.8.1        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.17.0       |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.38.0       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.1        |
| aws-partitions                  | 1.615.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.6      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-08-05**
</details> </pre>
</details>

**Comment by ELMAJOULI** [comment]
same issue is there any update 😥 ?

**Comment by WilbertFeldman** [comment]
Also having this issue when trying to use gitlab secure files

**Comment by jeneena-jose** [comment]
Same.  I am also facing this issue with Gitlab secure files.

**Comment by SBSiarhei** [comment]
Same issue here: gilab secure files with the same error. Any workaround would be really appreciated!

**Comment by waqaramjad** [comment]
Anu update ?

**Comment by SunDog** [comment]
Same here. Trying to use Gitlab secure files but for me it breaks when executing `bundle exec fastlane match development`

**Comment by zhizas** [comment]
Same problem. Is there problem only for IOS?

**Comment by MichalAlgor** [comment]
I also had this problem. I've noticed that I forgot to put the `PRIVATE_TOKEN` before the command
 ```bundle exec fastlane match adhoc```
So when I enter the full command like
```PRIVATE_TOKEN=**** bundle exec fastlane match adhoc```
It works. So I guess specifying the `PRIVATE_TOKEN` in env or in Fastfile would also work

**Comment by sapa-denis** [comment]
Same problem for me. Any updates?

**Comment by bck01215** [comment]
same issue

**Comment by hassan8357** [comment]
> I also had this problem. I've noticed that I forgot to put the `PRIVATE_TOKEN` before the command
> `bundle exec fastlane match adhoc`
> So when I enter the full command like
> `PRIVATE_TOKEN=**** bundle exec fastlane match adhoc`
> It works. So I guess specifying the `PRIVATE_TOKEN` in env or in Fastfile would also work

Which private token?

**Comment by MichalAlgor** [comment]
@hassan8357 Sorry for not being clear enough. 
This is the private token for Gitlab since the issue were happening for Gitlab secure files storage option

**Comment by hassan8357** [comment]
> @hassan8357 Sorry for not being clear enough.
> This is the private token for Gitlab since the issue were happening for Gitlab secure files storage option

@MichalAlgor no worries, thanks for fast reply. Did you mean the Project Access Token?

**Comment by MichalAlgor** [comment]
> > @hassan8357 Sorry for not being clear enough.
> > This is the private token for Gitlab since the issue were happening for Gitlab secure files storage option
> 
> @MichalAlgor no worries, thanks for fast reply. Did you mean the Project Access Token?

@hassan8357 I used `Personal Access Tokens` but I guess the project access token should also work.

**Comment by hassan8357** [comment]
@MichalAlgor many thanks for your help
