### ISSUE TITLE
Uploading the very first version of my app yields `No data`

### ISSUE THREAD

**Issue by vanniktech** [fastlane/fastlane#20538]
Did a new app and wanted to upload it right from the beginning using:

```
default_platform(:ios)

platform :ios do
  lane :build_upload do |options|
    team_id("XXXXXXXXXX")

    build_app(
      scheme: "Foo",
      configuration: "Release",
      workspace: "../Bar.xcworkspace",
      include_bitcode: true,
      export_team_id: "XXXXXXXXXX",
    )

    upload_to_app_store(
      skip_screenshots: !options[:uploadScreenshots],
      overwrite_screenshots: options[:uploadScreenshots],
      force: true,
      automatic_release: true,
    )
  end
end
```

However this ended up as:

```
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/spaceship/lib/spaceship/connect_api/model.rb:82:in `parse': [!] No data (RuntimeError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/spaceship/lib/spaceship/connect_api/response.rb:62:in `to_models'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:147:in `fetch_app_store_review_detail'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/deliver/lib/deliver/upload_metadata.rb:628:in `set_review_attachment_file'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/deliver/lib/deliver/upload_metadata.rb:344:in `upload'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/deliver/lib/deliver/runner.rb:152:in `upload_metadata'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/deliver/lib/deliver/runner.rb:61:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:24:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.208.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.4                                                           |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.37.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.4 (21F79)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.4.1                                                         |
| Swift Version               | 5.6.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
ENV['FASTLANE_ITC_TEAM_ID'] = '122415194' # This does deviate from Team ID on purpose! 122415194 (Niklas Baudy)
ENV["DELIVER_USER"] = "niklas.baudy@vanniktech.de"

default_platform(:ios)

platform :ios do
  lane :upload_dsyms do
    download_dsyms(version: "1.0.0", app_identifier: "com.vanniktech.wizard.ios",)
    upload_symbols_to_crashlytics(gsp_path: "../Wizard/GoogleService-Info.plist", binary_path: '../')
    clean_build_artifacts
  end

  lane :build_upload do |options|
    team_id("779A4D7K9R")

    build_app(
      scheme: "Wizard",
      configuration: "Release",
      workspace: "../Vanniktech.xcworkspace",
      include_bitcode: true,
      export_team_id: "779A4D7K9R",
    )

    upload_to_app_store(
      skip_screenshots: !options[:uploadScreenshots],
      overwrite_screenshots: options[:uploadScreenshots],
      force: true,
      automatic_release: true,
    )
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.208.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.25.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.18.0       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.37.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.605.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.131.2      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| CFPropertyList                  | 3.0.5        |
| json                            | 2.6.2        |
| bundler                         | 2.3.19       |
| webrick                         | 1.7.0        |
| rake                            | 13.0.6       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2022-08-09**
</details>

**Comment by brandon-carpenter** [comment]
When I've encountered this error, it was due to missing information under App Review Information in Appstore Connect.  You may need to update your metadata

**Comment by Corkeries** [comment]
Without thinking, I compiled a version of my app using a "temporary self-signed certificate" (that's what Intell-J calls it anyway), and after testing locally I decided to upload that exact same APK to the Google play developer console for a proper beta test.

**Comment by vanniktech** [comment]
Yeah still an issue

**Comment by OriTheElf** [comment]
This answer might help: https://stackoverflow.com/questions/53326492/error-itms-90592-invalid-export-compliance-code-when-uploading-to-app-store

**Comment by jhong70** [comment]
Just came across this issue myself. The problem is that you haven't provided any app review information before, given this is a new app.

Based on the stack trace, `set_review_attachment_file` will fetch review details from App Store Connect and unsafely try to convert the response to a string.

Additionally, the step right before `set_review_attachment_file` is `set_review_information`. If you haven't provided any app review information before or via deliver `set_review_attachment_file` will fail.

So to fix, provide the app review information in the associated text files in your deliver metadata folder, or provide the information via `app_review_information` within the `Deliverfile`.

See the documentation for fastlane deliver for how to get that setup.

**Comment by vanniktech** [comment]
You're right. This was an error on my side. A better error message would be nice though.
