### ISSUE TITLE
[regression] pilot distribute_external asks for app_platform in non-interactive mode

### ISSUE THREAD

**Issue by pokeum** [fastlane/fastlane#20558]
I seems to have found a solution for https://github.com/fastlane/fastlane/issues/19351
```
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:170:in `verify_interactive!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:129:in `input'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/setup/setup_android.rb:56:in `fetch_information_for_appfile'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/setup/setup_android.rb:15:in `setup_android'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/setup/setup.rb:115:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/commands_generator.rb:123:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:170:in `verify_interactive!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:129:in `input'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/setup/setup_android.rb:56:in `fetch_information_for_appfile'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/setup/setup_android.rb:15:in `setup_android'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/setup/setup.rb:115:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/commands_generator.rb:123:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```
in mac do not run
```
fastlane init
```
instead run with sudo
```
sudo fastlane init
```

**Comment by Homenicks** [comment]
Einstein Bot dialogs with ease in a visual map, and use new smart routing features to escalate bot conversations to the rightexperts. Work faster in the Field Service Lightning dispatcher console with a pop-out map, long-term Gantt view, and newdrag-and-drop scheduling options. Set up skills-based routing in a jiffy with a handsome setup screen

**Comment by KieranKI** [comment]
I’m new as well.  Glad I found this community for support.
