### ISSUE TITLE
Getting errors when running fastlane match change_password

### ISSUE THREAD

**Issue by MargarytaChepiga** [fastlane/fastlane#20611]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi! I'm running into the same issue as described here:
https://github.com/fastlane/fastlane/issues/13963

So when I run the following command locally:

fastlane match change_password --verbose

I run into following error:

[!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call (FastlaneCore::Interface::FastlaneError)

I've checked my fastlane version and then ended up upgrading to the latest just to be sure. However, output is still the same.
Am I missing something on my end when executing the command? Thanks in advance for your help!

##### Command executed

fastlane match change_password --verbose

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀 
Successfully loaded Appfile at path '/Users/*****/****/fastlane/Appfile'
- app_identifier: 'com.***.****.ios'
-------
Successfully loaded Appfile at path '/Users//Users/*****/****/fastlane/Appfile'
- app_identifier: 'com.***.****.ios'
-------
Successfully loaded Appfile at path '/Users/*****/****/fastlane/Appfile'
- app_identifier: 'com.***.****.ios'
-------
Successfully loaded Appfile at path'/Users/*****/****/fastlane/Appfile'
- app_identifier: 'com.***.****.ios'
-------
Successfully loaded Appfile at path '/Users/*****/****/fastlane/Appfile'
- app_identifier: 'com.***.****.ios'
-------
Successfully loaded Appfile at path'/Users/*****/****/fastlane/Appfile'
- app_identifier: 'com.***.****.ios'
-------
Successfully loaded Appfile at path '/Users/*****/****/fastlane/Appfile'
- app_identifier: 'com.***.****.ios'
-------
 [2022-08-31 14:57:20.58]: New passphrase for Git Repo: *************

 [2022-08-31 14:57:39.96]: Type passphrase again: *************
WARN [2022-08-31 14:57:41.11]: To not be asked about this value, you can specify it using 'git_url'
 [2022-08-31 14:57:41.11]: URL to the git repo containing all the certificates: ssh://*****.git
INFO [2022-08-31 14:58:00.60]: Cloning remote git repo...
INFO [2022-08-31 14:58:00.60]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2022-08-31 14:58:00.60]: $ git clone ssh://git****.git /var/folders/***
INFO [2022-08-31 14:58:00.62]: ▸ Cloning into '/var/folders/***
INFO [2022-08-31 14:58:01.57]: ▸ remote: Enumerating objects: 383, done.
INFO [2022-08-31 14:58:01.61]: ▸ remote: Counting objects: 100% (99/99), done.
INFO [2022-08-31 14:58:01.61]: ▸ remote: Compressing objects: 100% (77/77), done.
INFO [2022-08-31 14:58:01.82]: ▸ remote: Total 383 (delta 20), reused 79 (delta 15), pack-reused 284
INFO [2022-08-31 14:58:01.82]: ▸ Receiving objects: 100% (383/383), 577.30 KiB | 2.78 MiB/s, done.
INFO [2022-08-31 14:58:01.82]: ▸ Resolving deltas: 100% (89/89), done.
INFO [2022-08-31 14:58:01.85]: $ git --no-pager branch --list origin/master --no-color -r
INFO [2022-08-31 14:58:01.87]: Checking out branch master...
INFO [2022-08-31 14:58:01.87]: $ git checkout --orphan master
INFO [2022-08-31 14:58:01.89]: ▸ Switched to a new branch 'master'
INFO [2022-08-31 14:58:01.89]: $ git reset --hard
WARN [2022-08-31 14:58:01.99]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2022-08-31 14:58:01.99]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2022-08-31 14:58:01.99]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2022-08-31 14:58:01.99]: Passphrase for Match storage: *************
 [2022-08-31 14:58:19.64]: Type passphrase again: *************
INFO [2022-08-31 14:58:20.60]: 🔓  Successfully decrypted certificates repo
keychain: "/Users/***/login.keychain-db"
(here was the keychain info followed by this message:)
**password has been deleted.**
INFO [2022-08-31 14:58:20.72]: 🔒  Successfully encrypted certificates repo
Traceback (most recent call last):
	19: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:22:in `<main>'
	18: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:22:in `eval'
	17: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	16: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	15: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/bin/fastlane:23:in `<top (required)>'
	14: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	13: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/commands_generator.rb:26:in `start'
	12: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/commands_generator.rb:188:in `run'
	11: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	10: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	 9: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 8: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 7: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 6: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/commands_generator.rb:106:in `block (2 levels) in run'
	 5: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/change_password.rb:44:in `update'
	 4: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/storage/interface.rb:59:in `save_changes!'
	 3: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/storage/interface.rb:59:in `chdir'
	 2: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/storage/interface.rb:81:in `block in save_changes!'
	 1: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call (FastlaneCore::Interface::FastlaneError)
	19: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:22:in `<main>'
	18: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:22:in `eval'
	17: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	16: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	15: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/bin/fastlane:23:in `<top (required)>'
	14: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	13: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/commands_generator.rb:26:in `start'
	12: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/commands_generator.rb:188:in `run'
	11: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	10: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	 9: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 8: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 7: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 6: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/commands_generator.rb:106:in `block (2 levels) in run'
	 5: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/change_password.rb:44:in `update'
	 4: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/storage/interface.rb:59:in `save_changes!'
	 3: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/storage/interface.rb:59:in `chdir'
	 2: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/match/lib/match/storage/interface.rb:81:in `block in save_changes!'
	 1: from /Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/margarytachepiga/.rvm/gems/ruby-2.6.3/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/in</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.5.1                                      |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.37.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | macOS 12.5.1 (21G83)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.1                                        |
| Swift Version               | 5.5.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.209.1 | ✅ Up-To-Date  |

 </pre>
</details>

**Comment by MargarytaChepiga** [comment]
Hey @ValeriyMaliuk ! My colleague updated fastlane version to latest and was able to run the command successfully. Hope this helps.
