### ISSUE TITLE
Fastlane swift: exit code 0 even when lane fails

### ISSUE THREAD

**Issue by kalinjul** [fastlane/fastlane#20649]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This is to reopen #20419. Still happens on latest fastlane.

Hi,
we're using fastlane swift and noticed that our pipelines were always green, regardless of errors in fastlane runs.
So i looked into fastlane swift and indeed, it does not exit with an error code at any point.
Errors are recorded:
https://github.com/fastlane/fastlane/blob/019bad7f9ded480c41ae6d36320aa940f90ec108/fastlane/swift/LaneFileProtocol.swift#L44
And if errors occured, "after" actions are not called:
https://github.com/fastlane/fastlane/blob/019bad7f9ded480c41ae6d36320aa940f90ec108/fastlane/swift/LaneFileProtocol.swift#L144

But it just exists successfully everytime. Is this expected? IMHO, it makes fastlane useless in pipelines as i don't want to deploy e.g. when tests fail :)

I have a PR open to fix this.

##### Command executed
fastlane lane archive

##### Complete output when running fastlane, including the stack trace and command used
Example of a failed run with exit code 0 in gitlab:
```
[1655721736.9429178]: error encountered while executing command:
serverError
[1655721736.942967]: Encountered a problem: FastlaneCore::Interface::FastlaneBuildFailure:
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/gym/lib/gym/error_handler.rb:73:in `handle_build_error'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/gym/lib/gym/runner.rb:114:in `block in build_app'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/command_executor.rb:84:in `execute'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/gym/lib/gym/runner.rb:110:in `build_app'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/gym/lib/gym/runner.rb:18:in `run'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/gym/lib/gym/manager.rb:19:in `work'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/actions/build_app.rb:68:in `run'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/actions/build_ios_app.rb:22:in `run'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:229:in `chdir'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:73:in `run'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:42:in `execute'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server.rb:181:in `execute_action_command'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server.rb:176:in `process_action_command'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server.rb:123:in `handle_action_command'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server.rb:86:in `parse_and_execute_command'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:166:in `block (2 levels) in run'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
/usr/local/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.204.3/bin/fastlane:23:in `<top (required)>'
/usr/local/Cellar/fastlane/2.204.3/libexec/bin/fastlane:25:in `load'
/usr/local/Cellar/fastlane/2.204.3/libexec/bin/fastlane:25:in `<main>'
[1655721736.942987]: Done running lane: build 🚀
section_end:1655721736:step_script
[0Ksection_start:1655721736:archive_cache
[0K[0K[36;1mSaving cache for successful job[0;m[0;m
[32;1mCreating cache fastlane-binary-cache-280336-non_protected...[0;m
Runtime platform                                  [0;m  arch[0;m=amd64 os[0;m=darwin pid[0;m=19111 revision[0;m=98daeee0 version[0;m=14.7.0
./FastlaneRunner/.build/x86_64-apple-macosx/debug/FastlaneRunner: found 1 matching files and directories[0;m 
Archive is up to date!                            [0;m 
[32;1mCreated cache[0;m
section_end:1655721737:archive_cache
[0Ksection_start:1655721737:upload_artifacts_on_success
[0K[0K[36;1mUploading artifacts for successful job[0;m[0;m
[32;1mUploading artifacts...[0;m
Runtime platform                                  [0;m  arch[0;m=amd64 os[0;m=darwin pid[0;m=19121 revision[0;m=98daeee0 version[0;m=14.7.0
section_end:1655721737:upload_artifacts_on_success
[0Ksection_start:1655721737:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1655721737:cleanup_file_variables
[0K[32;1mJob succeeded[0;m
```

**Comment by kalinjul** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 12.6                                                 |
| Ruby                        | 3.1.2                                                |
| Bundler?                    | false                                                |
| Git                         | git version 2.32.1 (Apple Git-133)                   |
| Installation Source         | ~/.brew/Cellar/fastlane/2.209.1/libexec/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                                  |
| Ruby Lib Dir                | ~/.brew/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                           |
| Is contained                | false                                                |
| Is homebrew                 | true                                                 |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version               | 13.4.1                                               |
| Swift Version               | 5.6.1                                                |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.209.1 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.4       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.1       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.25.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.17.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.38.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.620.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.1        |
| aws-sdk-core                    | 3.132.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>


*generated on:* **2022-09-19**
</details>

This fastlane env does not matter in any way.

**Comment by kalinjul** [comment]
Still valid. Am 19.10.2022 um 19:31 schrieb fastlane bot ***@***.***>:﻿
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
Please make sure to update to the latest fastlane version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
Friendly reminder: contributions are always welcome! Check out CONTRIBUTING.md for more information on how to help with fastlane and feel free to tackle this issue yourself 💪
This issue will be auto-closed if there is no reply within 1 month.

**Comment by andrzejrostkowski** [comment]
Problem still remains. 
I've managed to break pipeline in Jenkins thanks to the following line in rescue => ue - You can use it in other places as well :)
UI.message("#{notExistingVariable.toCauseError}")

**Comment by iBotPeaches** [comment]
Closing as dupe of #20419
