### ISSUE TITLE
`Spaceship::Client.handle_two_factor` can loop indefinitely in CI environments, causing Apple Account lockouts

### ISSUE THREAD

**Issue by geoff-sheldon-bfg** [fastlane/fastlane#20707]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
If `ENV[FASTLANE_SESSION]` has expired, and Spaceship is used in a CI environment that utilizes `FASTLANE_SESSION` to authenticate with the Apple APIs, Spaceship falls back on the `handle_two_factor` method, which attempts to request a 2fa code and verify in the CI's non-interactive shell.  When this fails, Fastlane handles the error by logging it, incrementing `depth`, and calling `handle_two_factor` again.  Unfortunately, outside of determining whether or not to output the first-time explanation of what's happening, `depth` is completely unused, which means this code loops until Apple locks the account for 12 hours - at which point Fastlane catches `Spaceship::AccessForbiddenError` and exits.

##### Command executed
Not relevant, the bug is visible in `spaceship/lib/spaceship/two_step_or_factor_client.rb`

##### Complete output when running fastlane, including the stack trace and command used
Relevant stack trace:

<details>

INFO [2022-09-21 22:19:47.37]: Current team: MyTeamName
Loading session from environment variable
Session loaded from environment variable is not valid. Continuing with normal login.
Two-factor Authentication (6 digits code) is enabled for account 'account@mywebsite.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Error: Incorrect verification code

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Error: Incorrect verification code

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Error: Incorrect verification code

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Error: Incorrect verification code

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Error: Incorrect verification code

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Error: Incorrect verification code

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Error: Incorrect verification code

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Error: Incorrect verification code

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Error: Incorrect verification code

Please enter the 6 digit code you received at +1 (•••) •••-••XX:
Requesting session...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
WARN [2022-09-21 22:20:04.18]: Lane Context:
INFO [2022-09-21 22:20:04.18]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"certs_and_profiles"}
ERROR [2022-09-21 22:20:04.18]: Access forbidden
ERROR [2022-09-21 22:20:04.18]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Access forbidden

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Access%20forbidden+repo:fastlane/fastlane
➡️  Match receives `Access Forbidden` response 
    https://github.com/fastlane/fastlane/issues/20530 [open] 1 💬
    2 weeks ago

➡️  Requesting preview sets with token based login throws access forbidden error
    https://github.com/fastlane/fastlane/issues/19788 [closed] 2 💬
    12 Jun 2022

➡️  undefined method `include?' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/20444 [closed] 73 💬
    a day ago

and 12 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Access%20forbidden&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/client.rb:925:in `handle_error': [!] The request could not be completed because: (Spaceship::AccessForbiddenError)
	Access forbidden
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/client.rb:902:in `block in send_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/client.rb:657:in `with_retry'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/client.rb:898:in `send_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/client.rb:742:in `request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:176:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:201:in `rescue in handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:183:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:201:in `rescue in handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:183:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:201:in `rescue in handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:183:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:201:in `rescue in handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:183:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:201:in `rescue in handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:183:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:201:in `rescue in handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:183:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:201:in `rescue in handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:183:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:201:in `rescue in handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:183:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:201:in `rescue in handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:183:in `handle_two_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:21:in `handle_two_step_or_factor'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/client.rb:515:in `send_shared_login_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/client.rb:XX4:in `do_login'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/client.rb:404:in `login'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/client.rb:366:in `login'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
	from Fastfile:28:in `block in parsing_binding'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
</details>

Ideally we would see this logic retried a maximum of 3 times, which is enough to account for short-term networking issues without locking teams out of their service account. The `depth` variable is already there and can likely be used for this purpose.

**Comment by geoff-sheldon-bfg** [comment]
Updated with a short blurb regarding `fastlane env`

**Comment by geoff-sheldon-bfg** [comment]
I can put together a quick PR, but I'm not sure which error to use to denote that a maximum number of retries has been exceeded.

**Comment by geoff-sheldon-bfg** [comment]
Please do not close this issue, this is at the very least undesired behavior.

**Comment by tychop** [comment]
*Bump

**Comment by afern247** [comment]
Same:

![image](https://user-images.githubusercontent.com/34192856/221187523-d90db713-4dfc-4f0c-b6e7-784f3668d4ef.png)

**Comment by regetskcob** [comment]
Same for me, even with the newest fastlane-version.

**Comment by adar2378** [comment]
*bump

**Comment by roshansrashtasoft** [comment]
![Screenshot 2024-02-12 at 18 46 48](https://github.com/fastlane/fastlane/assets/97586645/0cda18c7-de2a-4e1e-8306-5cc43f34502c)

Any solution ?
