### ISSUE TITLE
fastlane pilot:  betaAppLocalizations not found for this app. - betaAppLocalization must exist for an app

### ISSUE THREAD

**Issue by robert-go** [fastlane/fastlane#20723]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The build still uploaded but empty changelog and fastlane return error

##### Command executed

`fastlane ios testflight_prod`
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [14:25:05]: Successfully finished processing the build 1.0 - 5 for IOS
[14:25:06]: Successfully set the changelog for build
[14:25:07]: Distributing new build to testers: 1.0 - 5
+------------------------------------+--------------------------------------+
|                               Lane Context                                |
+------------------------------------+--------------------------------------+
| PLATFORM_NAME                      | ios                                  |
| LANE_NAME                          | ios testflight_prod                  |
| GIT_REPO_WAS_CLEAN_ON_START        | true                                 |
| VERSION_NUMBER                     | 1.0                                  |
| LATEST_TESTFLIGHT_BUILD_NUMBER     | 4                                    |
| LATEST_TESTFLIGHT_VERSION          | 1.0                                  |
| BUILD_NUMBER                       | 5                                    |
| SIGH_PROFILE_TYPE                  | app-store                            |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.spritely.irefer"=>"match       |
|                                    | AppStore com.spritely.irefer"}       |
| IPA_OUTPUT_PATH                    | /Users/minhdrminh/Projects/i-Refer-  |
|                                    | Mobile/iRefer Dev.ipa                |
| XCODEBUILD_ARCHIVE                 | /Users/minhdrminh/Library/Developer  |
|                                    | /Xcode/Archives/2022-10-04/iRefer    |
|                                    | Dev 2022-10-04 14.04.35.xcarchive    |
| DSYM_OUTPUT_PATH                   | /Users/minhdrminh/Projects/i-Refer-  |
|                                    | Mobile/iRefer Dev.app.dSYM.zip       |
+------------------------------------+--------------------------------------+
[14:25:08]: betaAppLocalizations not found for this app. - betaAppLocalization must exist for an app

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | setup_circle_ci        | 0           |
| 2    | ensure_git_status_cle  | 0           |
|      | an                     |             |
| 3    | app_store_connect_api  | 0           |
|      | _key                   |             |
| 4    | get_version_number     | 0           |
| 5    | latest_testflight_bui  | 2           |
|      | ld_number              |             |
| 6    | increment_build_numbe  | 1           |
|      | r                      |             |
| 7    | match                  | 8           |
| 8    | gym                    | 139         |
| 9    | git log -20            | 0           |
|      | --pretty=format:%s     |             |
| 💥   | pilot                  | 1107        |
+------+------------------------+-------------+

[14:25:08]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': \e[31m[!] betaAppLocalizations not found for this app. - betaAppLocalization must exist for an app\e[0m (Spaceship::UnexpectedResponse)
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:115:in `post_beta_app_review_submissions'
	from /opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/forwardable.rb:238:in `post_beta_app_review_submissions'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/models/build.rb:186:in `post_beta_app_review_submission'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/pilot/lib/pilot/build_manager.rb:435:in `distribute_build'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/pilot/lib/pilot/build_manager.rb:200:in `distribute'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/pilot/lib/pilot/build_manager.rb:79:in `upload'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:86:in `testflight'
	from Fastfile:51:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/bin/fastlane:25:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.6                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.37.0 (Apple Git-136)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.210.1/libexec/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                                        |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                                 |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.0.1                                                     |
| Swift Version               | 5.7                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :android do
  lane :beta_dev do
    changelog = sh("git log -20 --pretty=format:%s")
    sh "cd ../android && ENVFILE=.env.development ./gradlew assembleDevRelease --build-cache && cd .."
    appcenter_upload(
        api_token: ENV["APPCENTER_API_TOKEN"],
        owner_name: "spritelyco",
        app_name: "iRefer-Dev",
        file: "android/app/build/outputs/apk/development/release/app-development-release.apk",
        notify_testers: true,
        release_notes: changelog
    )
  end
  lane :beta_staging do
    changelog = sh("git log -20 --pretty=format:%s")
    sh "cd ../android && ENVFILE=.env.staging ./gradlew assembleStagingRelease --build-cache && cd .."
    appcenter_upload(
        api_token: ENV["APPCENTER_API_TOKEN"],
        owner_name: "spritelyco",
        app_name: "iRefer-Staging",
        file: "android/app/build/outputs/apk/staging/release/app-staging-release.apk",
        notify_testers: true,
        release_notes: changelog
    )
  end
  lane :beta_prod do
    changelog = sh("git log -20 --pretty=format:%s")
    sh "cd ../android && ENVFILE=.env.production ./gradlew assembleProductionRelease --build-cache && cd .."
    appcenter_upload(
        api_token: ENV["APPCENTER_API_TOKEN"],
        owner_name: "spritelyco",
        app_name: "iRefer",
        file: "android/app/build/outputs/apk/production/release/app-production-release.apk",
        notify_testers: true,
        release_notes: changelog
    )
  end
end

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Upload to Testflight"
  lane :testflight_staging do |options|
    testflight(options, "com.spritely.irefer.staging", "iRefer Staging")
  end

  lane :testflight_prod do |options|
    testflight(options, "com.spritely.irefer", "iRefer Prod")
  end
end

def testflight(options, app_identifier, scheme)
  setup_ci if ENV['CI']
  ensure_git_status_clean
  username = ENV["APPLE_ID_USERNAME"]
  api_key = app_store_connect_api_key(
    key_id: ENV["P8_KEY_ID"],
    key_content: ENV["P8_CONTENT"],
    is_key_content_base64: true,
    issuer_id: "8fb0d423-7d30-4b8a-9a46-c54ab2ed98e7"
  )
  increment_build_number(
    build_number: latest_testflight_build_number(
      initial_build_number: 1,
      api_key: api_key,
      app_identifier: app_identifier,
      version: get_version_number(xcodeproj: "./ios/iRefer.xcodeproj")
    ) + 1,
    xcodeproj: "./ios/iRefer.xcodeproj",
  )
  # Set up Distribution code signing and build the app
  match(type: "appstore", app_identifier: app_identifier, readonly: ENV['CI'])
  gym(
      scheme: scheme,
      workspace: "ios/iRefer.xcworkspace"
  )
  delete_keychain(name: "fastlane_tmp_keychain") if File.exist? File.expand_path("~/Library/Keychains/fastlane_tmp_keychain-db")
  if !options[:skip_upload]
    # Upload the binary to TestFlight and automatically publish
    # to the configured beta testing group
    
    changelog = sh("git log -20 --pretty=format:%s")
    pilot(
      api_key: api_key,
      app_identifier: app_identifier,
      groups: ["Testers"],
      skip_waiting_for_build_processing: ENV["SKIP_WAITING_FOR_TESTFLIGHT"] == "true" ? true : false,
      notify_external_testers: false,
      changelog: changelog
    )
  end
  reset_git_repo
end
  
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.210.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 2.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.4       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.5.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.27.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.14.0       |
| google-apis-storage_v1          | 0.17.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.42.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.633.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.1        |
| aws-sdk-core                    | 3.151.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
| fastlane-plugin-appcenter       | 2.0.0        |
| csv                             | 3.2.2        |
</details>

*generated on:* **2022-10-04**
</details> </pre>
</details>

**Comment by aatriff** [comment]
We are experiencing same problem. Is there any workarounds?

**Comment by syewchuk** [comment]
Possible work-around for the changelog:
If you manually enter the "What to Test" section of the latest build in App Store Connect and save, the changelog should start showing up for future builds.

**Comment by robert-go** [comment]
@syewchuk changelogs is updated on Testflight, but fastlane still return same error

**Comment by thyroscope-yoonwon** [comment]
+1 same problem 😭

**Comment by alteral** [comment]
Even though the error message is not that informative, I think I found a root cause. Creating an external testing group and filling in the `Test Information` on the app's page in Testflight has fixed the issue for me.

**Comment by kshestov** [comment]
> Even though the error message is not that informative, I think I found the root cause. Creating an `External Testing` group and filling in the `Test Information` on the app's page in Testflight has fixed the issue for me.

It works. Thank you

**Comment by jgoldschmidt** [comment]
Instead of "default", I specified "en-US" and the upload went well.
```
        localized_app_info: {
          "en-US": {
            feedback_email: "<email>",
            marketing_url: "",
            privacy_policy_url: "",
            description: "App Beta Version",
          }
        },
        localized_build_info: {
          "en-US": {
            whats_new: "<changelog>",
          }
        },
```

**Comment by abdushkur** [comment]
> Instead of "default", I specified "en-US" and the upload went well.
> 
> ```
>         localized_app_info: {
>           "en-US": {
>             feedback_email: "<email>",
>             marketing_url: "",
>             privacy_policy_url: "",
>             description: "App Beta Version",
>           }
>         },
>         localized_build_info: {
>           "en-US": {
>             whats_new: "<changelog>",
>           }
>         },
> ```

this worked for me, that  "default" : .... this on official documentation does not work.
