### ISSUE TITLE
[Android] Fastlane crashes when tests fails

### ISSUE THREAD

**Issue by Lutzifer** [fastlane/fastlane#20724]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I call the test using

```
platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
    gradle(task: "pixel2api30DebugAndroidTest")
  end
end
```

and after the test did run I get:

```
Settings Tests > Test sign off[pixel2api30] \e[33mSKIPPED \e[0m
Tests on pixel2api30 failed: There was 2 failure(s).

> Task :app:pixel2api30DebugAndroidTest FAILED

> Task :app:mergeDebugAndroidTestTestResultProtos
Test execution completed. See the report at: file:///Users/admin/dev/<Redacted>/<redacted>-android/app/build/reports/androidTests/managedDevice/allDevices/index.html

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:pixel2api30DebugAndroidTest'.
> There were failing tests. See the report at: file:///Users/admin/dev/<Redacted>/<redacted>-android/app/build/reports/androidTests/managedDevice/pixel2api30/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 22s
78 actionable tasks: 51 executed, 27 up-to-date
\e[0m
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `sh'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:11:in `block (2 levels) in parsing_binding'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/gems/fastlane-2.210.1/bin/fastlane:23:in `<top (required)>'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `load'
	from /Users/admin/dev/<Redacted>/<redacted>-android/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `<top (required)>'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:484:in `exec'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/admin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
	from /Users/admin/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
	from /Users/admin/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

I think fastlane should not crash in this situation, but handle the failing test gracefully.

##### Command executed
```
fastlane android test 
```

##### Complete output when running fastlane, including the stack trace and command used

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                  |
| --------------------------- | ---------------------------------------------------------------------- |
| OS                          | 12.6                                                                   |
| Ruby                        | 3.1.2                                                                  |
| Bundler?                    | true                                                                   |
| Git                         | git version 2.37.0 (Apple Git-136)                                     |
| Installation Source         | ~/dev/<Redacted>/vendor/bundle/ruby/3.1.0/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                                                    |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.2/lib                                            |
| OpenSSL Version             | OpenSSL 3.0.5 5 Jul 2022                                               |
| Is contained                | false                                                                  |
| Is homebrew                 | false                                                                  |
| Is installed via Fabric.app | false                                                                  |
| Xcode Path                  | /Applications/Xcode-14.0.0.app/Contents/Developer/                     |
| Xcode Version               | 14.0                                                                   |
| Swift Version               | 5.7                                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
add_extra_platforms(
  platforms: [:toolbelt],
)

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
    gradle(task: "pixel2api30DebugAndroidTest")
  end

  desc "Set Password for keystore for package #{CredentialsManager::AppfileConfig.try_fetch_value(:package_name)}"
  lane :set_password do
    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)
    password = prompt(text: "Password for keystore of #{package_name}: ")

    sh("security add-generic-password -a #{package_name} -s #{package_name} -w #{password}")
  end

  desc "Assemble the App with Release Config"
  lane :assembleRelease do
    gradle(task: "clean assembleRelease")
  end

  desc "Build and Submit a new Alpha Build to Google Play"
  lane :alpha do
    assembleRelease
    upload_to_play_store(track: 'alpha')
  end

  desc "Build and Submit a new Internal Build to Google Play"
  lane :releaseInternal do
    assembleRelease
    upload_to_play_store(track: 'internal')
  end

  desc "Build and Deploy a new version to the Google Play for Production"
  lane :deploy do
    assembleRelease
    upload_to_play_store
  end
  
  desc "Format using ktlint"
  lane :format do
    gradle(task: "ktlintFormat")
  end

end

platform :toolbelt do
  import "Fastfiles/GithubActions.Fastfile"
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("service.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("<redacted>") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.210.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| bundler                         | 2.3.7        |
| pathname                        | 0.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.641.0      |
| aws-sigv4                       | 1.5.2        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.158.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.93.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.5.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.0        |
| google-apis-androidpublisher_v3 | 0.29.0       |
| google-apis-playcustomapp_v1    | 0.11.0       |
| google-apis-iamcredentials_v1   | 0.15.0       |
| google-apis-storage_v1          | 0.19.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.43.0       |
| json                            | 2.6.2        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-10-04**
</details>

**Comment by lwasyl** [comment]
This still seems to be an issue
![image](https://github.com/fastlane/fastlane/assets/3951580/a6d2e596-f6eb-415d-8b3e-b67da8e8dd4f)
