### ISSUE TITLE
Unable to upload to testflight using FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD

### ISSUE THREAD

**Issue by lionel-alves** [fastlane/fastlane#20747]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When trying to use `upload_to_testflight` with `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` with Xcode 14.0.1, fastlane reports the following error:
```
/opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:280:in `build_upload_command': \e[31m[!] undefined method `shellescape' for nil:NilClass (NoMethodError)
```
##### Command executed
```
fastlane run upload_to_testflight skip_waiting_for_build_processing:true apple_id: "APP_APPLE_ID"
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀
[17:49:52]: fastlane detected a Gemfile in the current directory
[17:49:52]: However, it seems like you didn't use `bundle exec`
[17:49:52]: To launch fastlane faster, please use
[17:49:52]:
[17:49:52]: $ bundle exec fastlane run upload_to_testflight skip_waiting_for_build_processing:true apple_id: APP_APPLE_ID
[17:49:52]:
[17:49:52]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:49:53]: ----------------------------------
[17:49:53]: --- Step: upload_to_testflight ---
[17:49:53]: ----------------------------------
[17:49:53]: Ready to upload new build to TestFlight (App: )...
[17:49:55]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[17:49:55]: Going to upload updated app to App Store Connect
[17:49:55]: This might take a few minutes. Please don't interrupt the script.

Looking for related GitHub issues on fastlane/fastlane...

➡️  Specify IPA path as a parameter to deliver beta
    https://github.com/fastlane/fastlane/issues/244 [closed] 2 💬
    22 Sep 2016

➡️  commit_version_bump error in-spite of expected and actual changes being same
    https://github.com/fastlane/fastlane/issues/248 [closed] 2 💬
    22 Sep 2016

➡️  Sigh: Lane specific `team_id` and `app_identifier` not used
    https://github.com/fastlane/fastlane/issues/256 [closed] 23 💬
    22 Sep 2016

and 19330 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60shellescape%27%20for%20nil%0A%0A%20%20%20%20%20%20%20%20%28%22-u%20%23%7Busername.shellescape%7D%22%20unless%20use_api_key%29%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:280:in `build_upload_command': \e[31m[!] undefined method `shellescape' for nil:NilClass (NoMethodError)

        ("-u #{username.shellescape}" unless use_api_key),
                       ^^^^^^^^^^^^\e[0m
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:771:in `upload'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/pilot/lib/pilot/build_manager.rb:50:in `upload'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:280:in `build_upload_command': undefined method `shellescape' for nil:NilClass (NoMethodError)

        ("-u #{username.shellescape}" unless use_api_key),
                       ^^^^^^^^^^^^
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:771:in `upload'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/pilot/lib/pilot/build_manager.rb:50:in `upload'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/gems/fastlane-2.210.1/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.210.1/libexec/bin/fastlane:25:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.6                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.37.0 (Apple Git-136)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.210.1/libexec/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                                        |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                                 |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.0.1                                                     |
| Swift Version               | 5.7                                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight and submit to the Alpha testers group"
  lane :beta do |options|
    # api_key = app_store_connect_api_key(
    #   key_id: "D7QJXPYSL6 ",
    #   issuer_id: "b177bdef-ec14-4aa4-af7a-2f967056ff08",
    #   key_filepath: "./AuthKey_D7QJXPYSL6.p8",
    #   duration: 500, # optional (maximum 1200)
    #   in_house: false # optional but may be required if using match/sigh
    # )

    # sigh(
      # api_key: api_key,
      # adhoc: true,
      # force: true
    # )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: "1389635943"
    )

    # pilot(api_key: api_key)
    #certificates
    #gym(export_method: "app-store", workspace: @workspace, scheme: @scheme)
    # upload_to_testflight(
    #   changelog: 'Build is now ready for testing.',
    # )
    # tag

  end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end



```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.210.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.5.0        |
| emoji_regex                     | 3.2.3        |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| public_suffix                   | 5.0.0        |
| excon                           | 0.93.0       |
| json                            | 2.6.2        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.17.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.2.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.9.0        |
| google-apis-playcustomapp_v1    | 0.11.0       |
| google-apis-androidpublisher_v3 | 0.29.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.19.0       |
| google-apis-iamcredentials_v1   | 0.15.0       |
| google-cloud-errors             | 1.3.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.43.0       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-partitions                  | 1.644.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.159.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-10-14**
</details></pre>
</details>

**Comment by driemecker** [comment]
Got it working by setting these 3 environment variables:
* FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
* FASTLANE_USER
* PILOT_APPLE_ID

Had to look into the fastlane sources to figure out that the FASTLANE_USER var is needed to avoid the `undefined method` error in `build_upload_command`

**Comment by zedtux** [comment]
In 2024 this issue remain as I just faced it with the latest version of Fastlane. Too bad.
