### ISSUE TITLE
match import to S3 failing with EISDIR

### ISSUE THREAD

**Issue by Eldjotnar** [fastlane/fastlane#20785]
I am getting an error when attempting to run `fastlane match import`:

```
/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.159.0/lib/seahorse/client/plugins/response_target.rb:67:in `initialize': \e[31m[!] Is a directory @ rb_sysopen - /var/folders/h9/bdpkz4d95qsf34yx0nfjvhkm0000gn/T/d20221026-38814-mgwjr/\e[0m (Errno::EISDIR)
```

matchfile:
```
s3_bucket("app")

storage_mode("s3")
s3_region("us-east-1")
s3_object_prefix("ios/certs")
skip_certificate_matching(true)
skip_docs(true)
git_url("")

type("appstore")
team_id("...")
username("...")
```

fastlane env output:
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.6                                        |
| Ruby                        | 3.0.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.32.1 (Apple Git-133)          |
| Installation Source         | ~/.rvm/rubies/ruby-3.0.2/bin/fastlane       |
| Host                        | macOS 12.6 (21G115)                         |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1r  11 Oct 2022                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.4.1                                      |
| Swift Version               | 5.6.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.210.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.2.22       |
| pathname                        | 0.1.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.93.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| simctl                          | 1.6.8        |
| jwt                             | 2.5.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.0        |
| google-apis-playcustomapp_v1    | 0.11.0       |
| google-apis-androidpublisher_v3 | 0.29.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.15.0       |
| google-apis-storage_v1          | 0.19.0       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.43.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.644.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.159.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| json                            | 2.6.2        |
| rake                            | 13.0.6       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>


*generated on:* **2022-10-26**
</details>
```

**Comment by narusejyunnichi** [comment]
same error but with different version
`/usr/local/Cellar/fastlane/2.209.1/libexec/gems/aws-sdk-core-3.132.0/lib/seahorse/client/plugins/response_target.rb:67:in `initialize': Is a directory @ rb_sysopen - /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20221102-95914-sc1r1x/ (Errno::EISDIR)`

**Comment by narusejyunnichi** [comment]
I compare this file (response_target.rb) between @Eldjotnar‘s version and my version, and search this file update history in this repo (https://github.com/aws/aws-sdk-ruby)

since this file doesn't changed in two years and we use different version bug get same error. plus it shell work fine when last week in my case.

and i see the value indeed a directory like "/var/folders/zz/xxxxx/T/xxx/" when i try to print it. the response is "" at first time.
if skip the first item. the shell will be work fine again.
so i think maybe the response has some changed from AWS like insert a new empty string item at first in response array.  but i don't have build log from earlier version. can't prove it.

but doesn't matter. i just want know why and what happen actually.

---------
there is temporary way to fix it: change response_target.rb at line 67

`                
                $VAR1 = target[target.length - 1]
                if $VAR1 == "/"
                    target #or some file address
                else
                    ManagedFile.new("#{target}", 'w+b')
                end
`

i know that if the shell run on CI, this way can't work, but if at local agent. hope it will be helpful

if there has some solution by official or some AWS API i don't know.
please tell me so i can fix this problem on my CI 😭
