### ISSUE TITLE
[Regression] [pilot] altool failure causes upload_to_testflight to stall

### ISSUE THREAD

**Issue by dimitribouniol** [fastlane/fastlane#20799]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.210.1` (Xcode 14)
- Last working version: `2.204.3` (Xcode 13.4.1)

### Regression Description

Ever since updating to Xcode 14.1 and the latest version of fastlane, uploads to App Store Connect consistently succeed for one bundle ID, but consistently fail to two others (though they do succeed when the machine is freshly started!). This manifests by the process stalling on 
```
[18:08:22]: --- Step: upload_to_testflight ---
[18:08:22]: ----------------------------------
[18:08:22]: Creating authorization token for App Store Connect API
[18:08:22]: Ready to upload new build to TestFlight (App: ------)...
[18:08:22]: Going to upload updated app to App Store Connect
[18:08:22]: This might take a few minutes. Please don't interrupt the script.
```

As I understand it, the latest fastlane now uses altool rather than iTMSTransporter, but the altool code path seems to fall over when an error is throws, as the `report.xml` file (which is the only log I can find) reports the following stack trace:
<details>
  <pre>/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:67:in `execute_action'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
Fastfile:377:in `block (2 levels) in parsing_binding'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane.rb:33:in `call'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/fastlane-2.210.1/bin/fastlane:23:in `<top (required)>'
/opt/homebrew/lib/ruby/gems/3.1.0/bin/fastlane:25:in `load'
/opt/homebrew/lib/ruby/gems/3.1.0/bin/fastlane:25:in `<top (required)>'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/cli.rb:484:in `exec'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/opt/homebrew/Cellar/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
/opt/homebrew/bin/bundle:25:in `load'
/opt/homebrew/bin/bundle:25:in `<main>'

undefined method `zero?' for nil:NilClass

      @errors << "The call to the altool completed with a non-zero exit status: #{exit_status}. This indicates a failure." unless exit_status.zero?
                                                                                                                                             ^^^^^^```</pre>
</details>

Fixing this would allow fastlane to report the error rather than stall, helping developers like me debug our sporadic app-specific issues 😅  

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 12.6                                           |
| Ruby                        | 3.1.1                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.37.1 (Apple Git-137.1)           |
| Installation Source         | /opt/homebrew/lib/ruby/gems/3.1.0/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                            |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.1/lib            |
| OpenSSL Version             | OpenSSL 1.1.1m  14 Dec 2021                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version               | 14.1                                           |
| Swift Version               | 5.7.1                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do
  before_all do
    ENV["SLACK_URL"] = ENV["SLACK_URL_NOTICE"]
  end
  
  desc "Upload a new beta build to TestFlight"

  lane :version_bump do
    skip_docs
    version_number = increment_version_number(xcodeproj: "./---.xcodeproj", bump_type: "minor")
    build_number = increment_build_number(xcodeproj: "./---.xcodeproj", build_number: "4")
    clean_build_artifacts
    # TODO: Create a commit and PR automatically
  end

  lane :update_min_version do
    skip_docs
    version_number = get_version_number(xcodeproj: "./---.xcodeproj", target: "---")
    build_number = get_build_number(xcodeproj: "./---.xcodeproj")
    version_string = "#{version_number}-#{build_number}"
    puts "Setting Launch Darkly ios-app-minimum-supported-version: #{version_string}"
    sh("../tools/update_launchdarkly_variable.zsh", "ios-app-minimum-supported-version", version_string)
  end

  lane :beta do
    
    api_key = app_store_connect_api_key(
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_BASE64"], # encode with `base64 AuthKey.p8`
      is_key_content_base64: true,
      in_house: false
    )
    
    create_keychain(
      name: "keychain",
      password: "---",
      default_keychain: true,
      lock_when_sleeps: false,
      unlock: true,
      timeout: 3600,
    )
    match(
      type: 'appstore',
      readonly: true,
      shallow_clone: true,
      clone_branch_directly: true,
      git_private_key: ENV["MATCH_SSH_KEY"],
      keychain_name: "keychain",
      keychain_password: "---",
      app_identifier: [
        "---",
      ],
    )
    
    prev_build_number = latest_testflight_build_number(
      app_identifier: "---",
      api_key: api_key,
    )
    prev_version_number = get_version_number(xcodeproj: "./---.xcodeproj", target: "---")
    prev_tag = "builds/iosbeta/#{prev_version_number}-#{prev_build_number}"
    
    unless git_tag_exists(tag: prev_tag)
      prev_tag = last_git_tag(pattern: "builds/iosbeta/*")
    end

    build_number = increment_build_number(
      build_number: prev_build_number + 1,
      xcodeproj: "---.xcodeproj"
    )  
    version_number = get_version_number(xcodeproj: "./---.xcodeproj", target: "---")
    version_string = "#{version_number}-#{build_number}"

    changes = changelog_from_git_commits(between: [prev_tag, "HEAD"], pretty: "• *%aN:* %s — _[%h](https://github.com/---/commit/%H)_")
    ENV["SLACK_URL"] = ENV["SLACK_URL_NOTICE"]
    slack(
      pretext: "🛠 Fastlane: Starting to build:`Version #{version_number} (#{build_number})`!",
      channel: "#ios-engineering",
      payload: {
        "Build Date" => Time.new.to_s,
        "Changes" => changes,
      }
    )

    # Prep the public app first.
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---.xcodeproj",
      targets: "---",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---",
      targets: "---",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )

    build_app(
      scheme: "---",
      configuration: "Release",
      derived_data_path: "./output",
      output_directory: "./output",
      archive_path: "./output/Archive",
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "---",
      changelog: "• Minor bugfixes and improvements.",
      skip_waiting_for_build_processing: true
    )

    # Set the version explicitly in the Info.plist so Shake can parse it
    increment_version_number(
      version_number: version_number,
      xcodeproj: "./---.xcodeproj"
    )

    # download_dsyms(version: "latest") # if bitcode is enabled
    upload_symbols_to_shake(
      client_id: ENV["SHAKE_CLIENT_ID"],
      client_secret: ENV["SHAKE_CLIENT_SECRET"],
      bundle_id: "---",
      plist_path: "---/Info.plist"
    )

    # Next, prep the unlisted version.
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---.xcodeproj",
      targets: "---",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---.xcodeproj",
      targets: "OneSignalNotificationServiceExtension",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )

    build_app(
      scheme: "---",
      configuration: "Unlisted",
      derived_data_path: "./output",
      output_directory: "./output",
      archive_path: "./output/Archive",
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "---",
      changelog: "• Minor bugfixes and improvements.",
      skip_waiting_for_build_processing: true
    )

    # Add Git tags for the uploaded build
    tag = "builds/iosbeta/#{version_number}-#{build_number}"
    add_git_tag(tag: tag)
    push_git_tags

    # Update launch darkly with new version
    puts "Setting Launch Darkly Latest version to: #{version_string}"
    sh("../tools/update_launchdarkly_variable.zsh", "ios-latest-app-version", version_string)

    ENV["SLACK_URL"] = ENV["SLACK_URL_SUCCESS"]
    slack(
      pretext: "🚀 Fastlane: New Testflight build available:`Version #{version_number} (#{build_number})`!",
      channel: "#ios",
      success: true,
      default_payloads: ["lane"],
      payload: {
        "Build Date" => Time.new.to_s,
        "Changes" => changes,
      }
    )

    # Set the version explicitly in the Info.plist so Shake can parse it
    increment_version_number(
      version_number: version_number,
      xcodeproj: "./---.xcodeproj"
    )

    # download_dsyms(version: "latest") # if bitcode is enabled
    upload_symbols_to_shake(
      client_id: ENV["SHAKE_CLIENT_ID"],
      client_secret: ENV["SHAKE_CLIENT_SECRET"],
      bundle_id: "---",
      plist_path: "---/Info.plist"
    )
  end

  error do |lane, exception|
    ENV["SLACK_URL"] = ENV["SLACK_URL_NOTICE"]
    slack(
      message: "💥 iOS Fastlane failed for lane: #{lane}!",
      channel: "#ios-engineering",
      success: false,
      payload: {
        "Build Date" => Time.new.to_s,
      }
    )
  end

  lane :prs do

    api_key = app_store_connect_api_key(
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_BASE64"], # encode with `base64 AuthKey.p8`
      is_key_content_base64: true,
      in_house: false
    )

    create_keychain(
      name: "keychain",
      password: "---",
      default_keychain: true,
      lock_when_sleeps: false,
      unlock: true,
      timeout: 3600,
    )
    match(
      type: 'appstore',
      readonly: true,
      shallow_clone: true,
      clone_branch_directly: true,
      git_private_key: ENV["MATCH_SSH_KEY"],
      keychain_name: "keychain",
      keychain_password: "---",
      app_identifier: [
        "---",
      ],
    )

    version_number = increment_version_number(
      xcodeproj: "---.xcodeproj",
      version_number: ENV["PR_NUMBER"]
    )
    build_number = increment_build_number(
      xcodeproj: "---.xcodeproj",
      build_number: ENV["PR_NUMBER"] + "." + ENV["RUN_NUMBER"]
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---.xcodeproj",
      targets: "---",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---.xcodeproj",
      targets: "OneSignalNotificationServiceExtension",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )

    build_app(
      scheme: "---",
      configuration: "Internal",
      derived_data_path: "./output",
      output_directory: "./output",
      archive_path: "./output/Archive",
    )

    changelog = "PR: " + ENV["PR_TITLE"] + " (#" + ENV["PR_NUMBER"] + ")\n→ " + ENV["PR_BRANCH"] + "\n\n"
    changelog += changelog_from_git_commits(
      between: ["origin/main", "HEAD"],
      pretty: "• %aN: %s",
      merge_commit_filtering: "exclude_merges",
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "---",
      changelog: changelog,
      skip_waiting_for_build_processing: true
    )
  end

  lane :public_nightly do
    api_key = app_store_connect_api_key(
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_BASE64"], # encode with `base64 AuthKey.p8`
      is_key_content_base64: true,
      in_house: false
    )

    create_keychain(
      name: "keychain",
      password: "---",
      default_keychain: true,
      lock_when_sleeps: false,
      unlock: true,
      timeout: 3600,
    )
    match(
      type: 'appstore',
      readonly: true,
      shallow_clone: true,
      clone_branch_directly: true,
      git_private_key: ENV["MATCH_SSH_KEY"],
      keychain_name: "keychain",
      keychain_password: "---",
      app_identifier: [
        "---",
      ],
    )
    
    prev_build_number = latest_testflight_build_number(
      app_identifier: "---",
      api_key: api_key,
    )
    prev_version_number = get_version_number(xcodeproj: "./---.xcodeproj", target: "---")
    prev_tag = "builds/iosbeta/#{prev_version_number}-#{prev_build_number}"
    
    unless git_tag_exists(tag: prev_tag)
      prev_tag = last_git_tag(pattern: "builds/iosbeta/*")
    end

    build_number = increment_build_number(
      build_number: prev_build_number + 1,
      xcodeproj: "---.xcodeproj"
    )
    version_number = get_version_number(xcodeproj: "./---.xcodeproj", target: "---")
    version_string = "#{version_number}-#{build_number}"

    changes = changelog_from_git_commits(between: [prev_tag, "HEAD"], pretty: "• *%aN:* %s — _[%h](https://github.com/---/commit/%H)_")
    ENV["SLACK_URL"] = ENV["SLACK_URL_NOTICE"]
    slack(
      pretext: "🛠 Fastlane: Starting to build:`Version #{version_number} (#{build_number})`!",
      channel: "#ios-engineering",
      payload: {
        "Build Date" => Time.new.to_s,
        "Changes" => changes,
      }
    )

    # Prep the public app first.
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---.xcodeproj",
      targets: "---",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---.xcodeproj",
      targets: "OneSignalNotificationServiceExtension",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )

    build_app(
      scheme: "---",
      configuration: "Release",
      derived_data_path: "./output",
      output_directory: "./output",
      archive_path: "./output/Archive",
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "---",
      changelog: "• Minor bugfixes and improvements.",
      skip_waiting_for_build_processing: true
    )

    # Set the version explicitly in the Info.plist so Shake can parse it
    increment_version_number(
      version_number: version_number,
      xcodeproj: "./---.xcodeproj"
    )

    # download_dsyms(version: "latest") # if bitcode is enabled
    upload_symbols_to_shake(
      client_id: ENV["SHAKE_CLIENT_ID"],
      client_secret: ENV["SHAKE_CLIENT_SECRET"],
      bundle_id: "---",
      plist_path: "---/Info.plist"
    )
  end

  lane :unlisted_nightly do
    api_key = app_store_connect_api_key(
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_BASE64"], # encode with `base64 AuthKey.p8`
      is_key_content_base64: true,
      in_house: false
    )

    create_keychain(
      name: "keychain",
      password: "---",
      default_keychain: true,
      lock_when_sleeps: false,
      unlock: true,
      timeout: 3600,
    )
    match(
      type: 'appstore',
      readonly: true,
      shallow_clone: true,
      clone_branch_directly: true,
      git_private_key: ENV["MATCH_SSH_KEY"],
      keychain_name: "keychain",
      keychain_password: "---",
      app_identifier: [
        "---",
      ],
    )
    
    # Use the same build number as the public build. This lane usually runs right after it finishes uploading.
    build_number = latest_testflight_build_number(
      app_identifier: "---",
      api_key: api_key,
    )
    prev_tag = last_git_tag(pattern: "builds/iosbeta/*")

    increment_build_number(
      build_number: build_number,
      xcodeproj: "---.xcodeproj"
    )
    version_number = get_version_number(xcodeproj: "./---.xcodeproj", target: "---")
    version_string = "#{version_number}-#{build_number}"

    changes = changelog_from_git_commits(between: [prev_tag, "HEAD"], pretty: "• *%aN:* %s — _[%h](https://github.com/---/commit/%H)_")

    # Prep the public app first.
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---.xcodeproj",
      targets: "---",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "---.xcodeproj",
      targets: "OneSignalNotificationServiceExtension",
      code_sign_identity: "iPhone Distribution",
      profile_name: "---",
    )

    build_app(
      scheme: "---",
      configuration: "Unlisted",
      derived_data_path: "./output",
      output_directory: "./output",
      archive_path: "./output/Archive",
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "---",
      changelog: "• Minor bugfixes and improvements.",
      skip_waiting_for_build_processing: true
    )

    # Set the version explicitly in the Info.plist so Shake can parse it
    increment_version_number(
      version_number: version_number,
      xcodeproj: "./---.xcodeproj"
    )

    # Add Git tags for the uploaded build
    tag = "builds/iosbeta/#{version_number}-#{build_number}"
    add_git_tag(tag: tag)
    push_git_tags

    # Update launch darkly with new version
    puts "Setting Launch Darkly Latest version to: #{version_string}"
    sh("../tools/update_launchdarkly_variable.zsh", "ios-latest-app-version", version_string)

    ENV["SLACK_URL"] = ENV["SLACK_URL_SUCCESS"]
    slack(
      pretext: "🚀 Fastlane: New Testflight build available:`Version #{version_number} (#{build_number})`!",
      channel: "#ios",
      success: true,
      default_payloads: ["lane"],
      payload: {
        "Build Date" => Time.new.to_s,
        "Changes" => changes,
      }
    )

    # Set the version explicitly in the Info.plist so Shake can parse it
    increment_version_number(
      version_number: version_number,
      xcodeproj: "./---.xcodeproj"
    )

    # download_dsyms(version: "latest") # if bitcode is enabled
    upload_symbols_to_shake(
      client_id: ENV["SHAKE_CLIENT_ID"],
      client_secret: ENV["SHAKE_CLIENT_SECRET"],
      bundle_id: "---",
      plist_path: "---/Info.plist"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("---")
apple_id("---")
itc_team_id("---")
team_id("---")

for_lane :prs do
  app_identifier("---")
end

for_lane :public_nightly do
  app_identifier("---")
end

for_lane :unlisted_nightly do
  app_identifier("---")
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.210.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                  | Version | Update-Status |
| --------------------------------------- | ------- | ------------- |
| fastlane-plugin-upload_symbols_to_shake | 1.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                     | Version      |
| --------------------------------------- | ------------ |
| error_highlight                         | 0.3.0        |
| did_you_mean                            | 1.6.1        |
| bundler                                 | 2.3.7        |
| pathname                                | 0.2.0        |
| rake                                    | 13.0.6       |
| rexml                                   | 3.2.5        |
| CFPropertyList                          | 3.0.5        |
| public_suffix                           | 5.0.0        |
| addressable                             | 2.8.1        |
| artifactory                             | 3.0.15       |
| atomos                                  | 0.1.3        |
| aws-eventstream                         | 1.2.0        |
| aws-partitions                          | 1.648.0      |
| aws-sigv4                               | 1.5.2        |
| jmespath                                | 1.6.1        |
| aws-sdk-core                            | 3.162.0      |
| aws-sdk-kms                             | 1.58.0       |
| aws-sdk-s3                              | 1.115.0      |
| babosa                                  | 1.0.4        |
| claide                                  | 1.1.0        |
| colored                                 | 1.2          |
| colored2                                | 3.1.2        |
| highline                                | 2.0.3        |
| commander                               | 4.6.0        |
| declarative                             | 0.0.20       |
| digest-crc                              | 0.6.4        |
| unf_ext                                 | 0.0.8.2      |
| unf                                     | 0.1.4        |
| domain_name                             | 0.5.20190701 |
| dotenv                                  | 2.8.1        |
| emoji_regex                             | 3.2.3        |
| excon                                   | 0.93.0       |
| faraday-em_http                         | 1.0.0        |
| faraday-em_synchrony                    | 1.0.0        |
| faraday-excon                           | 1.1.0        |
| faraday-httpclient                      | 1.0.1        |
| multipart-post                          | 2.0.0        |
| faraday-multipart                       | 1.0.4        |
| faraday-net_http                        | 1.0.1        |
| faraday-net_http_persistent             | 1.2.0        |
| faraday-patron                          | 1.0.0        |
| faraday-rack                            | 1.0.0        |
| faraday-retry                           | 1.0.3        |
| ruby2_keywords                          | 0.0.5        |
| faraday                                 | 1.10.2       |
| http-cookie                             | 1.0.5        |
| faraday-cookie_jar                      | 0.0.7        |
| faraday_middleware                      | 1.2.0        |
| fastimage                               | 2.2.6        |
| gh_inspector                            | 1.1.3        |
| jwt                                     | 2.5.0        |
| memoist                                 | 0.16.2       |
| multi_json                              | 1.15.0       |
| os                                      | 1.1.4        |
| signet                                  | 0.17.0       |
| googleauth                              | 1.3.0        |
| httpclient                              | 2.8.3        |
| mini_mime                               | 1.1.2        |
| trailblazer-option                      | 0.1.2        |
| uber                                    | 0.1.0        |
| representable                           | 3.2.0        |
| retriable                               | 3.1.2        |
| webrick                                 | 1.7.0        |
| google-apis-core                        | 0.9.1        |
| google-apis-androidpublisher_v3         | 0.29.0       |
| google-apis-playcustomapp_v1            | 0.11.0       |
| google-apis-iamcredentials_v1           | 0.15.0       |
| google-apis-storage_v1                  | 0.19.0       |
| google-cloud-env                        | 1.6.0        |
| google-cloud-errors                     | 1.3.0        |
| google-cloud-core                       | 1.6.0        |
| google-cloud-storage                    | 1.43.0       |
| json                                    | 2.6.2        |
| mini_magick                             | 4.11.0       |
| naturally                               | 2.2.1        |
| optparse                                | 0.1.1        |
| plist                                   | 3.6.0        |
| rubyzip                                 | 2.3.2        |
| security                                | 0.1.3        |
| simctl                                  | 1.6.8        |
| terminal-notifier                       | 2.0.0        |
| unicode-display_width                   | 1.8.0        |
| terminal-table                          | 1.8.0        |
| tty-screen                              | 0.8.1        |
| tty-cursor                              | 0.7.1        |
| tty-spinner                             | 0.9.3        |
| word_wrap                               | 1.0.0        |
| nanaimo                                 | 0.3.0        |
| xcodeproj                               | 1.22.0       |
| rouge                                   | 2.0.7        |
| xcpretty                                | 0.3.0        |
| xcpretty-travis-formatter               | 1.0.1        |
| fastlane-plugin-upload_symbols_to_shake | 1.1.1        |
</details>

*generated on:* **2022-10-29**
</details></pre>
</details>

**Comment by dimitribouniol** [comment]
Said in other words...
These two blocks of code look different, but I don't know ruby, so no clue if it actually impacts anything 😅 

Good? https://github.com/fastlane/fastlane/blob/9db0159cba89885c5d760294e8c6c7e696bba031/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L70-L87

Bad: https://github.com/fastlane/fastlane/blob/9db0159cba89885c5d760294e8c6c7e696bba031/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L233-L246

**Comment by dimitribouniol** [comment]
This is still an issue for us on one of our older systems (stuck on macOS 12), though it seems altool no longer errors out on Ventura.
