### ISSUE TITLE
Fastlane supply failed

### ISSUE THREAD

**Issue by wiltwitt** [fastlane/fastlane#20791]
I am getting fastlane error.  It talks about permission issues but not sure what kind of permission I need to get
I am trying to publish my app using expo and this is the command I used 
"eas submit -p android"

Waiting for submission to complete. You can press Ctrl+C to exit.
✖ Something went wrong when submitting your app to Google Play Store.

We couldn't figure out what went wrong. See logs to learn more.

[logs] Starting the submit process
[logs] Downloading archive
[logs] Preparing artifact
[logs] Submitting Android app to Play Store...
[logs] Submitting the app with fastlane supply
[logs] /var/lib/gems/2.7.0/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1028:in `fetch_access_token': [!] Authorization failed.  Server message: (Signet::AuthorizationError)
[logs] {"error":"invalid_grant","error_description":"Invalid grant: account not found"}
[logs]  from /var/lib/gems/2.7.0/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1039:in `fetch_access_token!'
[logs]  from /var/lib/gems/2.7.0/gems/googleauth-1.3.0/lib/googleauth/signet.rb:75:in `block in fetch_access_token!'
[logs]  from /var/lib/gems/2.7.0/gems/googleauth-1.3.0/lib/googleauth/signet.rb:102:in `retry_with_error'I
[logs]  from /var/lib/gems/2.7.0/gems/googleauth-1.3.0/lib/googleauth/signet.rb:74:in `fetch_access_token!'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:53:in `initialize'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:19:in `new'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:19:in `make_from_config'
[logs] from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/uploader.rb:425:in `client'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/uploader.rb:7:in `perform_upload'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:40:in `block (2 levels) in run'
[logs]  from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
[logs]  from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
[logs]  from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[logs]  from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:61:in `run'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:13:in `start'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/bin/fastlane:23:in `<top (required)>'
[logs]  from /usr/local/bin/fastlane:23:in `load'
[logs]  from /usr/local/bin/fastlane:23:in `<main>'
[logs] /var/lib/gems/2.7.0/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1028:in `fetch_access_token': Authorization failed.  Server message: (Signet::AuthorizationError)
[logs] {"error":"invalid_grant","error_description":"Invalid grant: account not found"}
[logs]  from /var/lib/gems/2.7.0/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1039:in `fetch_access_token!'
[logs]  from /var/lib/gems/2.7.0/gems/googleauth-1.3.0/lib/googleauth/signet.rb:75:in `block in fetch_access_token!'
[logs]  from /var/lib/gems/2.7.0/gems/googleauth-1.3.0/lib/googleauth/signet.rb:102:in `retry_with_error'
[logs]  from /var/lib/gems/2.7.0/gems/googleauth-1.3.0/lib/googleauth/signet.rb:74:in `fetch_access_token!'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:53:in `initialize'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:19:in `new'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:19:in `make_from_config'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/uploader.rb:425:in `client'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/uploader.rb:7:in `perform_upload'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:40:in `block (2 levels) in run'
[logs]  from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
[logs]  from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
[logs]  from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[logs]  from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:61:in `run'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:13:in `start'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
[logs]  from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/bin/fastlane:23:in `<top (required)>'
[logs]  from /usr/local/bin/fastlane:23:in `load'
[logs]  from /usr/local/bin/fastlane:23:in `<main>'
[logs] +---------------------------------+-------------------------------------------------------------------------------+
[logs] |                                           Summary for supply 2.191.0                                            |
[logs] +---------------------------------+-------------------------------------------------------------------------------+
[logs] | aab                             | /tmp/submissions/c836ac5b-4992-4d3b-be33-e8112d442dfa/application_archive.aab |
[logs] | track                           | internal                                                                      |
[logs] | json_key                        | /tmp/submissions/c836ac5b-4992-4d3b-be33-e8112d442dfa/service-account.json    |
[logs] | package_name                    | com.angusenergy.GremlinTankMonitoring                                         |
[logs] | changes_not_sent_for_review     | false                                                                         |
[logs] | release_status                  | completed                                                                     |
[logs] | skip_upload_apk                 | false                                                                         |
[logs] | skip_upload_aab                 | false                                                                         |
[logs] | skip_upload_metadata            | false                                                                         |
[logs] | skip_upload_changelogs          | false                                                                         |
[logs] | skip_upload_images              | false                                                                         |
[logs] | skip_upload_screenshots         | false                                                                         |
[logs] | validate_only                   | false                                                                         |
[logs] | check_superseded_tracks         | false                                                                         |
[logs] | timeout                         | 300                                                                           |
[logs] | deactivate_on_promote           | true                                                                          |
[logs] | ack_bundle_installation_warning | false                                                                         |
[logs] +---------------------------------+-------------------------------------------------------------------------------+
[logs]
[logs]
[logs] Looking for related GitHub issues on fastlane/fastlane...
[logs]
[logs] Found no similar issues. To create a new issue, please visit:
[logs] https://github.com/fastlane/fastlane/issues/new
[logs] Run `fastlane env` to append the fastlane environment to your issue
[logs] Fastlane supply failed
[logs] Failed to submit the app

**Comment by wiltwitt** [comment]
anyone?

**Comment by sekarsivakumar** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.6.1                                                     |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.37.0 (Apple Git-136)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.211.0/libexec/bin/fastlane |
| Host                        | macOS 12.6.1 (21G217)                                      |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                                 |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.0.1                                                     |
| Swift Version               | 5.7                                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end

  # lane :beta do
  #   # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
  #   gradle(
  #     task: 'assemble',
  #     build_type: 'Release'
  #   )
  
  #   # ...
  # end
  desc "Submit a new Beta Build to Play Store"
  lane :beta do
    store_password = prompt(text: "12345678", secure_text: true)
    key_password = prompt(text: "12345678", secure_text: true)
    releaseFilePath = '/Volumes/Data/Release/android/app/my-upload-key.keystore'
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => "12345678",
        "android.injected.signing.key.alias" => "my-key-alias",
        "android.injected.signing.key.password" => "12345678",
      }
    )
    upload_to_play_store(
      track: 'internal'
    )
end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/Volumes/Data/Release/android/fastlane/file.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.") # e.g.appID com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.94.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.5.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.1        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.31.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-s3                      | 1.117.1      |
| set                             | 1.0.2        |
| json                            | 2.6.2        |
| aws-partitions                  | 1.668.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.168.2      |
| aws-sdk-kms                     | 1.60.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>


*generated on:* **2022-12-01**
</details>

**Comment by sekarsivakumar** [comment]
fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlane supply failed
    https://github.com/fastlane/fastlane/issues/20791 [open] 2 💬
    4 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1028:in `fetch_access_token': \e[31m[!] Authorization failed.  Server message: (Signet::AuthorizationError)
{"error":"invalid_grant","error_description":"Invalid grant: account not found"}\e[0m
        from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1039:in `fetch_access_token!'
        from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/googleauth-1.3.0/lib/googleauth/signet.rb:75:in `block in fetch_access_token!'

**Comment by covenantcodes** [comment]
I'm also getting a similar error, have you found a fix?

**Comment by adeubank** [comment]
Follow these steps to generate valid and link a valid service account. 

Then use the command `eas credentials` to re-upload the service account keys associated to EAS for your Google Play account.

**Comment by ahmad-elafify-pci** [comment]
> Follow these steps to generate valid and link a valid service account. https://github.com/expo/fyi/blob/main/creating-google-service-account.md
> 
> Then use the command `eas credentials` to re-upload the service account keys associated to EAS for your Google Play account.

ty

**Comment by iBotPeaches** [comment]
Cleaning up backlog - sorry for delay. As the error and others suggested - your authentication isn't quite perfect yet. I'll close this out as mainly support and 3 years old.

Sorry for the ping.
