### ISSUE TITLE
after upgrade from xcode 13.2 to xcode 14.0 fastlane build fails with below error

### ISSUE THREAD

**Issue by ShanthiRaweng** [fastlane/fastlane#20804]
### New Issue Checklist

- [ *] Updated fastlane to the latest version
- [* ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ *] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [* ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
<!-- Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'set -o pipefail && xcodebuild -scheme "SpursToolkit" -workspace "SpursToolkit.xcworkspace" -configuration "Release" -sdk "iphoneos" | tee '/Users/shanthi.karpaga/Library/Logs/fastlane/xcbuild/2022-10-31/8295/xcodebuild.log' | xcpretty --color --simple' was 65 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
** BUILD FAILED **

	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/xcodebuild.rb:274:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:11:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.210.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

/

**Comment by ShanthiRaweng** [comment]
bundle exec fastlane env
[✔] 🚀 
[19:35:45]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.62.8 <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.5.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.37.0 (Apple Git-136)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.5.1 (21G83)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 14.0                                                           |
| Swift Version               | 5.7                                                            |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :build_frameworks do
  xcversion(
    version:"14.0"
  )
  xcodebuild(
   scheme: "SpursToolkit",
   workspace: "SpursToolkit.xcworkspace",
   configuration: "Release",
   sdk:"iphonesimulator"
  )
  xcodebuild(
   scheme: "SpursToolkit",
   workspace: "SpursToolkit.xcworkspace",
   configuration: "Release",
   sdk:"iphoneos"
  )

  sh "../Script/ios-build-framework-script.sh"

end


lane :build do
  xcodebuild(
   scheme: "SpursToolkit",
   workspace: "SpursToolkit.xcworkspace",
   configuration: "Release",
   sdk:"iphonesimulator",
   archivePath: $BITRISE_DEPLOY_DIR
  )
  xcodebuild(
   scheme: "SpursToolkit",
   workspace: "SpursToolkit.xcworkspace",
   configuration: "Release",
   sdk:"iphoneos",
   archivePath: $BITRISE_DEPLOY_DIR
  )

  sh "../Script/ios-build-framework-script-bitrise.sh"

end

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.210.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                       | Version | Update-Status |
| ---------------------------- | ------- | ------------- |
| fastlane-plugin-act          | 1.2.1   | ✅ Up-To-Date  |
| fastlane-plugin-provisioning | 1.0.0   | ✅ Up-To-Date  |
| fastlane-plugin-slack_upload | 0.1.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 1.17.2       |
| etc                             | 1.0.1        |
| forwardable                     | 1.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.10       |
| i18n                            | 1.12.0       |
| minitest                        | 5.16.3       |
| tzinfo                          | 2.0.5        |
| zeitwerk                        | 2.6.0        |
| activesupport                   | 6.1.7        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.1        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.2        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.653.0      |
| aws-sigv4                       | 1.5.2        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.166.0      |
| aws-sdk-kms                     | 1.59.0       |
| aws-sdk-s3                      | 1.117.1      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| clamp                           | 1.3.2        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.5       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.3       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.6.3        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| cocoapods                       | 1.11.3       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.93.1       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.5.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.1        |
| google-apis-androidpublisher_v3 | 0.30.0       |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.43.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-act             | 1.2.1        |
| fastlane-plugin-provisioning    | 1.0.0        |
| gli                             | 2.21.0       |
| hashie                          | 5.0.0        |
| websocket-extensions            | 0.1.5        |
| websocket-driver                | 0.7.5        |
| slack-ruby-client               | 1.0.0        |
| fastlane-plugin-slack_upload    | 0.1.0        |
| mini_portile2                   | 2.8.0        |
| racc                            | 1.6.0        |
| nokogiri                        | 1.13.8       |
| slather                         | 2.7.2        |
| xcode-install                   | 2.8.1        |
</details>


*generated on:* **2022-10-31**
</details>
[19:35:49]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[19:35:49]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can
easily paste it on GitHub? (y/n)
n
[19:35:54]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
shanthi.karpaga@Shanthis-MacBook-Pro SpursToolkit %

**Comment by iBotPeaches** [comment]
Sorry we never visited this in time. Now that Xcode 14 is so old and Xcode 27 is out. I'm closing this out.
