### ISSUE TITLE
modify_services Does Not Work

### ISSUE THREAD

**Issue by enchorb** [fastlane/fastlane#20855]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Getting an error when running modify_services that teamId is an invalid attribute. I have my TEAMID set as an env variable but it isnt being passed into modify_services.

##### Command executed
```
    modify_services(
      app_identifier: "app.example.name",
      services: {
        access_wifi: "on",
        associated_domains: "on",
        auto_fill_credential: "on",
        hotspot: "on",
        push_notification: "on"
      }
    )
```

##### Complete output when running fastlane, including the stack trace and command used

```
/Users/name/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.206.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': \e[31m[!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "a8b8ab16-d0f8-4c75-ba1c-e76f853ce2a2",
    "status" : "409",
    "code" : "ENTITY_ERROR.ATTRIBUTE.ILLEGAL",
    "title" : "An attribute in the provided entity is not allowed for this request",
    "detail" : "The attribute 'teamId' can not be used with this request",
    "source" : {
      "pointer" : "data/attributes/teamId"
    }
  } ]
}\e[0m
```

</details>
[11:41:14]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[11:41:14]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
❯ bundle exec fastlane env
[✔] 🚀 
[11:41:39]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.62.15 <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 12.6                                                     |
| Ruby                        | 3.0.0                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.37.1 (Apple Git-137.1)                     |
| Installation Source         | ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                                      |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.0/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 14.1                                                     |
| Swift Version               | 5.7.1                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:
<details><summary>`./Appfile`</summary>

```ruby
apple_id "REDACTED"
team_id ENV["APPLE_TEAM_ID"]

# For more information about the Appfile, see: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status      |
| ----------------------------------------- | ------- | ------------------ |
| fastlane-plugin-versioning_android        | 0.1.0   | ✅ Up-To-Date       |
| fastlane-plugin-versioning                | 0.5.1   | ✅ Up-To-Date       |
| fastlane-plugin-firebase_app_distribution | 0.3.4   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.5.0        |
| bundler                                   | 2.3.6        |
| tsort                                     | 0.1.0        |
| set                                       | 1.0.1        |
| uri                                       | 0.10.1       |
| pathname                                  | 0.1.0        |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.5        |
| concurrent-ruby                           | 1.1.9        |
| i18n                                      | 1.9.1        |
| minitest                                  | 5.15.0       |
| tzinfo                                    | 2.0.4        |
| zeitwerk                                  | 2.5.4        |
| activesupport                             | 6.1.4.6      |
| public_suffix                             | 4.0.7        |
| addressable                               | 2.8.1        |
| httpclient                                | 2.8.3        |
| json                                      | 2.6.2        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.660.0      |
| aws-sigv4                                 | 1.5.2        |
| jmespath                                  | 1.6.1        |
| aws-sdk-core                              | 3.167.0      |
| aws-sdk-kms                               | 1.59.0       |
| aws-sdk-s3                                | 1.117.1      |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.5       |
| ethon                                     | 0.15.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.11.2       |
| cocoapods-deintegrate                     | 1.0.5        |
| cocoapods-downloader                      | 1.5.1        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.1        |
| cocoapods-trunk                           | 1.6.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.8.0        |
| ruby-macho                                | 2.5.1        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.22.0       |
| cocoapods                                 | 1.11.2       |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.4        |
| unf_ext                                   | 0.0.8.2      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.8.1        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.94.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| multipart-post                            | 2.0.0        |
| faraday-multipart                         | 1.0.4        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.2       |
| http-cookie                               | 1.0.5        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.6        |
| jwt                                       | 2.5.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.17.0       |
| googleauth                                | 1.3.0        |
| mini_mime                                 | 1.1.2        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.2.0        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.9.1        |
| google-apis-androidpublisher_v3           | 0.31.0       |
| google-apis-playcustomapp_v1              | 0.12.0       |
| google-apis-iamcredentials_v1             | 0.16.0       |
| google-apis-storage_v1                    | 0.19.0       |
| google-cloud-env                          | 1.6.0        |
| google-cloud-errors                       | 1.3.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.44.0       |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.3.4        |
| fastlane-plugin-versioning                | 0.5.1        |
| fastlane-plugin-versioning_android        | 0.1.0        |
| xcode-install                             | 2.8.0        |
</details>

*generated on:* **2022-11-14**
</details>

**Comment by hyh1256191239** [comment]
Hello, I'm not sure if you have solved this problem. I'm also experiencing this problem now, and I haven't found a solution yet. If you have solved it, could you please let me know?

**Comment by vadimkrutovlv** [comment]
@enchorb did you manage to solve this?

**Comment by GL33P-0R4NG3** [comment]
I found rather than not working it seems like I am unable to "turn off" some of the capabilities or set specific settings for example icloud i cannot set as off even when the error says: Unknown service 'off'. Valid values: 'xcode6_compatible', 'xcode5_compatible', 'off'. Im testing it right now so ill provide some detailed info later but just asking if someone does not have some solution yet....

**Comment by GL33P-0R4NG3** [comment]
Okay so here is the list which does not work at all:

<details>
<summary>Not working capabilities</summary>

```
        ## driver_kit: "off",                         	# Valid values: "on", "off"
        ## driver_kit_endpoint_security: "off",       	# Valid values: "on", "off"
        ## driver_kit_family_hid_device: "off",       	# Valid values: "on", "off"
        ## driver_kit_family_networking: "off",       	# Valid values: "on", "off"
        ## driver_kit_family_serial: "off",           	# Valid values: "on", "off"
        ## driver_kit_hid_event_service: "off",       	# Valid values: "on", "off"
        ## driver_kit_transport_hid: "off",           	# Valid values: "on", "off"
        ## sf_universal_link_api: "off",              	# Valid values: "on", "off"
        ## vp9_decoder: "off",                        	# Valid values: "on", "off"
        ## hotspot_helper: "off",                     	# Valid values: "on", "off"
        ## car_play_audio_app: "off",                	# Valid values: "on", "off"
        ## car_play_messaging_app: "off",       	# Valid values: "on", "off"
        ## car_play_navigation_app: "off",      	# Valid values: "on", "off"
        ## car_play_voip_calling_app: "off",          	# Valid values: "on", "off"
        ## critical_alerts: "off",                    	# Valid values: "on", "off"
```
</details>

all of them returns something like this:
```
/Users/admin/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/fastlane-2.227.0/spaceship/lib/spaceship/connect_api/api_client.rb:218:in 'Spaceship::ConnectAPI::APIClient#handle_response': [!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "0cb226e6-9e76-424a-aa00-ffa7e53e5c3f",
    "status" : "409",
    "code" : "ENTITY_ERROR.RELATIONSHIP.INVALID",
    "title" : "The provided entity includes a relationship with an invalid value",
    "detail" : "The provided entity includes a relationship with an invalid value",
    "source" : {
      "pointer" : "data/relationships/capabilities"
    }
  } ]
}

```

---

And for these:

```
        icloud: "off",                           	# Valid values: "xcode5_compatible", "xcode6_compatible", "off"
        ## game_center: "off",                        	# Valid values: "ios", "macos", off"
```

for icloud i cannot use the off option as I described comment above it returns: Unknown service 'off'. Valid values: 'xcode6_compatible', 'xcode5_compatible', 'off'.

and for game_center is seems to not work since it returns error that the setting does not exist or that it failed on the apple side i looked on the possible values and tried all but none worked for me... 

---
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 15.3                                                 |
| Ruby                        | 3.4.1                                                |
| Bundler?                    | false                                                |
| Git                         | git version 2.39.5 (Apple Git-154)                   |
| Installation Source         | ~/.local/share/mise/installs/ruby/3.4.1/bin/fastlane |
| Host                        | macOS 15.3 (24D60)                                   |
| Ruby Lib Dir                | ~/.local/share/mise/installs/ruby/3.4.1/lib          |
| OpenSSL Version             | OpenSSL 3.4.0 22 Oct 2024                            |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version               | 16.2                                                 |
| Swift Version               | 6.0.3                                                |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'json'

default_platform(:ios)

platform :ios do

  desc "Generic build lane for multiple projects"
  lane :build do |options|
    
    root = options[:root]
    tm_id = options[:team_id]
    project_name = options[:project_name]
    bundle_id = options[:bundle_id]    
    app_name = options[:app_name]
    export_method = options[:export_method] || "ad-hoc"

    # disable_automatic_code_signing(path: "#{project_name}")

    # Certificate fetching
    cert_id = lane_context[:cert_certificate_id]

    # Remove old provisioning profiles so new one can get created
    sh("export PROFILES_DIR=~/Library/MobileDevice/Provisioning\ Profiles rm -f '$PROFILES_DIR'/*.mobileprovision 2>/dev/null || true ")

    # Update Capabilities on Apple Developer Portal
    # sh("ruby #{root}/Resources/Scripts/AppleDeveloperPortal/update_provisioning.rb $(pwd)/.. #{bundle_id} #{app_name} #{tm_id}")
    
    #entitlements_json = sh("plutil -convert json -o - app.entitlements", capture: true)
    entitlements = {} # JSON.parse(entitlements_json)
    
    entitlements_to_services = {
      "com.apple.developer.networking.wifi-info" => "access_wifi",
      "com.apple.developer.default-data-protection" => "data_protection",
      # "com.apple.developer.icloud-container-identifiers" => "icloud",
      # "com.apple.developer.ubiquity-kvstore-identifier" => "icloud",
      "com.apple.developer.in-app-payments" => "apple_pay",
      "com.apple.developer.associated-domains" => "associated_domains",
      # "com.apple.developer.applesignin" => "sign_in_with_apple",
      # "com.apple.developer.pushkit.unrestricted-voip" => "push_kit",
      "com.apple.developer.auto-fill-credential-provider" => "auto_fill_credential",
      "com.apple.developer.healthkit" => "health_kit",
      "com.apple.developer.homekit" => "home_kit",
      # "com.apple.developer.in-app-payments" => "apple_pay",
      "com.apple.developer.inter-app-audio" => "inter_app_audio",
      "com.apple.developer.networking.multipath" => "multipath",
      "com.apple.developer.networking.networkextension" => "network_extension",
      "com.apple.developer.nfc.readersession.formats" => "nfc_tag_reading",
      "com.apple.developer.pass-type-identifiers" => "passbook", # deprecated but still present
      "com.apple.developer.vpn-entitlement" => "personal_vpn",
      "aps-environment" => "push_notification",
      "com.apple.developer.siri" => "siri_kit",
      "com.apple.security.application-groups" => "app_group",
      # "com.apple.developer.game-center" => "game_center",
      # "com.apple.developer.hotspot-helper" => "hotspot_helper",
      # "com.apple.developer.critical-alerts" => "critical_alerts",
      # "com.apple.developer.system-extension.install" => "system_extension",
      # "com.apple.developer.driverkit" => "driver_kit",
      # "com.apple.developer.kernel.extended-virtual-addressing" => "extended_virtual_address_space",
      # "com.apple.developer.networking.custom-protocol" => "custom_network_protocol",
      "com.apple.developer.wireless-configuration" => "wireless_accessory",
      # "com.apple.developer.driverkit.user-client-access" => "driver_kit_user_client_access",
      # "com.apple.developer.fileprovider.testing-mode" => "file_provider_testing_mode",
      # "com.apple.developer.hardened-runtime" => "hardened_runtime", # not actually modify_services
      "com.apple.developer.wallet" => "wallet",
      # "com.apple.developer.coremedia.hls.low-latency" => "low_latency_hls",
      # "com.apple.developer.usernotifications.communication" => "communication_notifications",
      # "com.apple.developer.shazamkit" => "shazam_kit",
      # "com.apple.developer.musickit" => "music_kit",
      # "com.apple.developer.group-activities" => "group_activities",
      # "com.apple.developer.healthkit.recalibration.estimation" => "health_kit_estimate_recalibration",
      # "com.apple.developer.usernotifications.time-sensitive" => "time_sensitive_notifications"
    }
    
    services_hash = {}

    entitlements_to_services.each do |ent_key, service_key|
      next if service_key == "data_protection" # we will handle it separately
      if entitlements[ent_key]
         services_hash[service_key.to_sym] = "on"
      else
         services_hash[service_key.to_sym] = "off"
      end
    end
    
    services_hash[:data_protection] = case entitlements["com.apple.developer.default-data-protection"]
    when "NSFileProtectionComplete"
        "complete"
    when "NSFileProtectionCompleteUnlessOpen"
        "unlessopen"
    when "NSFileProtectionCompleteUntilFirstUserAuthentication"
        "untilfirstauth"
    else
        "off"
    end
    
    modify_services(
      app_identifier: bundle_id,
      team_id: tm_id,
      # Optional
      # App services can be enabled during app creation
      services: # services_hash
        {
        # One # means that it works two # means its in testing since there are some issues with setting that capability

        access_wifi: "off",                        	# Valid values: "on", "off"
        app_attest: "off",                   		# Valid values: "on", "off"
        app_group: "off",                          	# Valid values: "on", "off"
        apple_pay: "off",                          	# Valid values: "on", "off"
        associated_domains: "off",                 	# Valid values: "on", "off"
        auto_fill_credential: "off",               	# Valid values: "on", "off"
        ## car_play_audio_app: "off",                	# Valid values: "on", "off"
        ## car_play_messaging_app: "off",       	    	# Valid values: "on", "off"
        ## car_play_navigation_app: "off",      		# Valid values: "on", "off"
        ## car_play_voip_calling_app: "off",          	# Valid values: "on", "off"
        class_kit: "off",                         	# Valid values: "on", "off"
        icloud: "xcode5_compatible",                           	# Valid values: "xcode5_compatible", "xcode6_compatible", "off"
        ## critical_alerts: "off",                    	# Valid values: "on", "off"
        custom_network_protocol: "off",            	# Valid values: "on", "off"
        data_protection: "complete",               	# Valid values: "complete", "unlessopen", "untilfirstauth", "off"
        extended_virtual_address_space: "off",     	# Valid values: "on", "off"
        file_provider_testing_mode: "off",         	# Valid values: "on", "off"
        fonts: "off",                              	# Valid values: "on", "off"
        ## game_center: "off",                        	# Valid values: "ios", "macos", off"
        health_kit: "off",                         	# Valid values: "on", "off"
        hls_interstitial_preview: "off",           	# Valid values: "on", "off"
        home_kit: "off",                           	# Valid values: "on", "off"
        hotspot: "off",                            	# Valid values: "on", "off"
        hotspot_helper: "off",                     	# Valid values: "on", "off"
        in_app_purchase: "on",                    	# Valid values: "on", "off"
        inter_app_audio: "off",                    	# Valid values: "on", "off"
        low_latency_hls: "off",                   	# Valid values: "on", "off"
        managed_associated_domains: "off",         	# Valid values: "on", "off"
        maps: "off",                               	# Valid values: "on", "off"
        multipath: "off",                          	# Valid values: "on", "off"
        network_extension: "off",                  	# Valid values: "on", "off"
        nfc_tag_reading: "on",                     	# Valid values: "on", "off"
        passbook: "off",                           	# Valid values: "on", "off" (deprecated)
        personal_vpn: "off",                       	# Valid values: "on", "off"
        push_notification: "off",                  	# Valid values: "on", "off"
        sign_in_with_apple: "off",                 	# Valid values: "on", "off"
        siri_kit: "off",                           	# Valid values: "on", "off"
        system_extension: "off",                   	# Valid values: "on", "off"
        user_management: "off",                    	# Valid values: "on", "off"
        vpn_configuration: "off",                  	# Valid values: "on", "off" (deprecated)
        wallet: "off",                             	# Valid values: "on", "off"
        wireless_accessory: "off",                 	# Valid values: "on", "off"
        ## driver_kit: "off",                         	# Valid values: "on", "off"
        ## driver_kit_endpoint_security: "off",       	# Valid values: "on", "off"
        ## driver_kit_family_hid_device: "off",       	# Valid values: "on", "off"
        ## driver_kit_family_networking: "off",       	# Valid values: "on", "off"
        ## driver_kit_family_serial: "off",           	# Valid values: "on", "off"
        ## driver_kit_hid_event_service: "off",       	# Valid values: "on", "off"
        ## driver_kit_transport_hid: "off",           	# Valid values: "on", "off"
        multitasking_camera_access: "off",         	# Valid values: "on", "off"
        ## sf_universal_link_api: "off",              	# Valid values: "on", "off"
        ## vp9_decoder: "off",                        	# Valid values: "on", "off"
        music_kit: "off",                          	# Valid values: "on", "off"
        shazam_kit: "off",                         	# Valid values: "on", "off"
        communication_notifications: "off",        	# Valid values: "on", "off"
        group_activities: "off",                   	# Valid values: "on", "off"
        health_kit_estimate_recalibration: "off",  	# Valid values: "on", "off"
        time_sensitive_notifications: "off",       	# Valid values: "on", "off"
      }
    )
    
    exit 0

    # Provisioning profile
    case export_method
    when "ad-hoc"
      sigh(app_identifier: bundle_id, team_id: tm_id, cert_id: cert_id, adhoc: true, force: true)
    when "app-store"
      sigh(app_identifier: bundle_id, team_id: tm_id, cert_id: cert_id, force: true)
    when "development"
      sigh(app_identifier: bundle_id, team_id: tm_id, cert_id: cert_id, development: true, force: true)
    else
      UI.user_error!("Unsupported export_method: #{export_method}") # it should never reach this line as checking will be in the main script...
    end

    profile_uuid = lane_context[:sigh_uuid]

    csid = sh("security find-identity -p codesigning -v | grep #{tm_id} | head -n1 | sed -E 's/^[[:space:]]*[0-9]+\\) [A-F0-9]+ \\\"(.*)\\\"/\\1/'", capture: true).strip

    puts("Using identity: #{csid}")

    update_code_signing_settings(use_automatic_signing: false, path: project_name, team_id: tm_id, bundle_identifier: bundle_id, code_sign_identity: csid, profile_uuid: profile_uuid)


    build_no = latest_testflight_build_number(
      app_identifier: bundle_id
    ) || 0

    build_no = build_no + 1

    increment_build_number(
      build_number: build_no
    )

    # Build using gym
    gym(
      project: "#{project_name}",
      export_method: export_method,
      output_directory: "./build/#{build_no}",
      clean: true,
      #export_options: {
      #  provisioningProfiles: {
      #    "#{bundle_id}" => profile_name
      #  },
      #  signingStyle: "manual",
      #  teamID: "#{tm_id}",
      #}
    )

    puts("Build finished for #{bundle_id}")

  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.24usw.testbuild") # The bundle identifier of your app
apple_id("team@xgode.com") # Your Apple Developer Portal username

itc_team_id("206103") # App Store Connect Team ID
team_id("F7SM98QCWV") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.227.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.7.0        |
| did_you_mean                    | 2.0.0        |
| syntax_suggest                  | 2.0.2        |
| public_suffix                   | 6.0.1        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| babosa                          | 1.0.4        |
| bundler                         | 2.6.3        |
| nkf                             | 0.2.0        |
| base64                          | 0.2.0        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.112.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.1.0        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.4       |
| faraday_middleware              | 1.2.1        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.8        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.4.0        |
| sysrandom                       | 1.0.5        |
| fastlane-sirp                   | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.10.1       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.2.1       |
| digest-crc                      | 0.7.0        |
| google-cloud-storage            | 1.47.0       |
| mini_magick                     | 4.13.2       |
| naturally                       | 2.2.1        |
| optparse                        | 0.6.0        |
| plist                           | 3.7.2        |
| rubyzip                         | 2.4.1        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.6.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.4.0        |
| xcodeproj                       | 1.27.0       |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.1        |
| logger                          | 1.7.0        |
| jmespath                        | 1.6.2        |
| aws-eventstream                 | 1.3.2        |
| aws-sigv4                       | 1.11.0       |
| aws-partitions                  | 1.1079.0     |
| aws-sdk-core                    | 3.222.1      |
| aws-sdk-kms                     | 1.99.0       |
| aws-sdk-s3                      | 1.183.0      |
| rexml                           | 3.4.1        |
| mutex_m                         | 0.3.0        |
| httpclient                      | 2.9.0        |
| google-cloud-errors             | 1.5.0        |
| google-cloud-core               | 1.8.0        |
| json                            | 2.10.2       |
| rouge                           | 3.28.0       |
| xcpretty                        | 0.4.1        |
| forwardable                     | 1.3.3        |
| pathname                        | 0.4.0        |
| shellwords                      | 0.2.2        |
| cgi                             | 0.4.1        |
| date                            | 3.4.1        |
| timeout                         | 0.4.3        |
| stringio                        | 3.1.2        |
| securerandom                    | 0.4.1        |
| uri                             | 1.0.2        |
| ipaddr                          | 1.2.7        |
| openssl                         | 3.3.0        |
| digest                          | 3.2.0        |
| io-nonblock                     | 0.3.1        |
| zlib                            | 3.2.1        |
| resolv                          | 0.6.0        |
| io-wait                         | 0.3.1        |
| time                            | 0.4.1        |
| open-uri                        | 0.5.0        |
| net-http                        | 0.6.0        |
| net-protocol                    | 0.2.2        |
| english                         | 0.8.0        |
| erb                             | 4.0.4        |
| strscan                         | 3.1.2        |
| abbrev                          | 0.1.2        |
| io-console                      | 0.8.0        |
| tempfile                        | 0.3.1        |
| delegate                        | 0.4.0        |
| fileutils                       | 1.7.3        |
| tmpdir                          | 0.3.1        |
| singleton                       | 0.3.0        |
| open3                           | 0.2.1        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.6.2        |
| find                            | 0.2.0        |
| ostruct                         | 0.6.1        |
| yaml                            | 0.4.0        |
| psych                           | 5.2.2        |
</details>


*generated on:* **2025-04-03**
</details>
