### ISSUE TITLE
Create new app version fails

### ISSUE THREAD

**Issue by phjs** [fastlane/fastlane#20904]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to create a lane to automate the creation of a patch app version. It should download the current metadata, create a new app version in App Store Connect where the patch part of the version number is increased (e.g.: 2.4.1 becomes 2.4.2), and then uploads the metadata to that version.
Unfortunately, this fails with the message `There is no route for the path 'apps/1234567890/platforms/ios/versions/create/'.` (regarding that, I only found [this](https://github.com/fastlane/fastlane/issues/19478) unanswered issue).

##### Command executed

        lane :bugFixVersion do 
                downloadMetadata
        
                newLiveVersion = "2.4.2"
        
                Spaceship::Tunes.login(ENV["USERNAME"])
                tunesApp = Spaceship::Tunes::Application.find(ENV["APP_ID"])
                tunesApp.create_version!(newLiveVersion)

                uploadMetadata
        end
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
    fastlane bugFixVersion --env AppName --verbose

[✔] 🚀 
[16:37:47]: Loading from './fastlane/.env.AppName'
DEBUG [2022-11-30 16:37:47.57]: Checking if there are any plugins that should be loaded...
INFO [2022-11-30 16:37:47.73]: ---------------------------
INFO [2022-11-30 16:37:47.73]: --- Step: shell command ---
INFO [2022-11-30 16:37:47.73]: ---------------------------
INFO [2022-11-30 16:37:47.90]: ------------------------------
INFO [2022-11-30 16:37:47.90]: --- Step: default_platform ---
INFO [2022-11-30 16:37:47.90]: ------------------------------
INFO [2022-11-30 16:37:47.90]: Driving the lane 'ios bugFixVersion' 🚀
Reading keychain entry, because either user or password were empty
Loading session from '/Users/user/.fastlane/spaceship/appleID/cookie'
Spaceship::Tunes::Application.all is deprecated
  It's using a temporary patch to keep it from raising an error but things may not work correctly
  Please consider switching to Spaceship::ConnectAPI if you can
  For more details - https://github.com/fastlane/fastlane/pull/20480
WARN [2022-11-30 16:38:01.40]: Lane Context:
INFO [2022-11-30 16:38:01.40]: {:ENVIRONMENT=>"AppName", :DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios bugFixVersion"}
ERROR [2022-11-30 16:38:01.40]: <?xml version="1.0" encoding="UTF-8"?>
<String>There is no route for the path 'apps/1234567890/platforms/ios/versions/create/'.</String>

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | shell command    | 0           |
| 2    | default_platform | 0           |
+------+------------------+-------------+

ERROR [2022-11-30 16:38:01.41]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: <?xml version="1.0" encoding="UTF-8"?>
<String>There is no route for the path 'apps/1234567890/platforms/ios/versions/create/'.</String>

URL: https://api.github.com/search/issues?q=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3CString%3EThere%20is%20no%20route%20for%20the%20path%20%27apps%2F1234567890%2Fplatforms%2Fios%2Fversions%2Fcreate%2F%27.%3C%2FString%3E%0A+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/spaceship/lib/spaceship/client.rb:771:in `parse_response': \e[31m[!] <?xml version="1.0" encoding="UTF-8"?> (Spaceship::UnexpectedResponse)
<String>There is no route for the path 'apps/1234567890/platforms/ios/versions/create/'.</String>
\e[0m
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/spaceship/lib/spaceship/tunes/tunes_client.rb:402:in `create_version!'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/spaceship/lib/spaceship/tunes/application.rb:236:in `create_version!'
	from Fastfile:268:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/spaceship/lib/spaceship/client.rb:771:in `parse_response': <?xml version="1.0" encoding="UTF-8"?> (Spaceship::UnexpectedResponse)
<String>There is no route for the path 'apps/1234567890/platforms/ios/versions/create/'.</String>
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/spaceship/lib/spaceship/tunes/tunes_client.rb:402:in `create_version!'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/spaceship/lib/spaceship/tunes/application.rb:236:in `create_version!'
	from Fastfile:268:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.211.0/libexec/bin/fastlane:25:in `<main>'
 </pre>
</details>

### Environment

<details>
  <pre> 
    <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.6                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.37.1 (Apple Git-137.1)                       |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.211.0/libexec/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                                        |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                                 |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.1                                                       |
| Swift Version               | 5.7.1                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require "json"
require 'mini_magick'
require 'fileutils'

# Fastlane

default_platform(:ios)

platform :ios do

    # Skip the creation of the fastlane/README.md file when running fastlane
    skip_docs

    lane :bugFixVersion do 
        
        downloadMetadata
        
        newLiveVersion = "2.4.2"
        
        Spaceship::Tunes.login(ENV["USERNAME"])
        tunesApp = Spaceship::Tunes::Application.find(ENV["APP_ID"])
        tunesApp.create_version!(newLiveVersion)

        uploadMetadata

    end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.94.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.5.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.1        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.31.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.660.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.167.0      |
| aws-sdk-kms                     | 1.59.0       |
| aws-sdk-s3                      | 1.117.1      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-11-30**
</details>
 </pre>
</details>

**Comment by thomasdaniel642** [comment]
Are you encountering an issue with Fastlane when creating a new app version in App Store Connect ? [LHI is now Optum Serve](https://www-lhiproviderportal.com)
