### ISSUE TITLE
create InAppPurchase product failure

### ISSUE THREAD

**Issue by change1wang73** [fastlane/fastlane#20933]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I had checked the product upload info is correct，but when I run the method `app.in_app_purchases.create!`, the problem coming。

##### Command executed

```
app.in_app_purchases.create!(
    type: iapType,
    versions: {
      'zh-Hans' => {
        name: product_name,
        description: description
      }
    },
    reference_name: product_name,
    product_id: product_id,
    cleared_for_sale: true,
    review_notes: nil,
    review_screenshot: screenshot_path,
    pricing_intervals: [
      {
        country: "WW",
        begin_date: nil,
        end_date: nil,
        tier: tier
      }
    ]  
  )
```
##### Complete output when running fastlane, including the stack trace and command used

```
/usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.211.0/spaceship/lib/spaceship/client.rb:771:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.211.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1418:in `create_iap!'
	from /usr/local/lib/ruby/gems/3.1.0/gems/fastlane-2.211.0/spaceship/lib/spaceship/tunes/iap.rb:76:in `create!'
	from IAP.rb:89:in `create_iap'
	from IAP.rb:206:in `block in create_iap_action'
	from IAP.rb:205:in `each'
	from IAP.rb:205:in `create_iap_action'
	from IAP.rb:218:in `<main>'
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.6                                                    |
| Ruby                        | 3.1.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.37.0 (Apple Git-136)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.211.0/libexec/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 14.0.1                                                  |
| Swift Version               | 5.7                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.94.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.5.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.1        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.31.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.660.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.167.0      |
| aws-sdk-kms                     | 1.59.0       |
| aws-sdk-s3                      | 1.117.1      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-12-14**
</details>
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by wade0317** [comment]
same too,  seems like it need use  connect api to create InAppPurchase , there is a new branch code for createing 
 InAppPurchase which is completed with connect api

**Comment by ps-attilio** [comment]
I have the same issue at this moment :(

**Comment by TCROC** [comment]
> same too, seems like it need use connect api to create InAppPurchase , there is a new branch code for createing InAppPurchase which is completed with connect api

Hey @wade0317 .  What is the name of that branch?
