### ISSUE TITLE
/opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)

### ISSUE THREAD

**Issue by KaranMehta3984** [fastlane/fastlane#20974]
$ fastlane beta

[16:51:10]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:51:10]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[16:51:11]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?
Looking for related GitHub issues on fastlane/fastlane...
➡️  Can not Publish to the App Store Production track
    https://github.com/fastlane/fastlane/issues/19674 [open] 24 💬
    2 weeks ago
➡️  Could not retrieve response as fastlane runs in non-interactive mode\e[0m (FastlaneCore::Interface::FastlaneCrash)
    https://github.com/fastlane/fastlane/issues/20661 [closed] 4 💬
    6 weeks ago
➡️   Could not retrieve response as fastlane runs in non-interactive mode\e[0m (FastlaneCore::Interface::FastlaneCrash)
    https://github.com/fastlane/fastlane/issues/20607 [closed] 4 💬
    6 weeks ago
and 58 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓
🔗  You can ⌘ + double-click on links to open them directly in your browser.
[16:51:12]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
/opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:[17](http://192.168.4.9/root/flutter-fastlane-demo/-/jobs/2475#L17)0:in `verify_interactive!'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:364:in `ensure_fastfile'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/commander-4.6.0/lib/commander/command.rb:[18](http://192.168.4.9/root/flutter-fastlane-demo/-/jobs/2475#L18)7:in `call'
	from /opt/homebrew/Cellar/fastlane/2.[21](http://192.168.4.9/root/flutter-fastlane-demo/-/jobs/2475#L21)1.0_1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:1[23](http://192.168.4.9/root/flutter-fastlane-demo/-/jobs/2475#L23):in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:170:in `verify_interactive!'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:364:in `ensure_fastfile'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:1[24](http://192.168.4.9/root/flutter-fastlane-demo/-/jobs/2475#L24):in `run!'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/fastlane:[25](http://192.168.4.9/root/flutter-fastlane-demo/-/jobs/2475#L25):in `load'
	from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/fastlane:25:in `<main>'
ERROR: Job failed: exit status 1

**Comment by KaranMehta3984** [comment]
[✔] 🚀 
[17:29:26]: fastlane detected a Gemfile in the current directory
[17:29:26]: However, it seems like you didn't use `bundle exec`
[17:29:26]: To launch fastlane faster, please use
[17:29:26]: 
[17:29:26]: $ bundle exec fastlane env
[17:29:26]: 
[17:29:26]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:29:26]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.45.2 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                        |
| --------------------------- | ------------------------------------------------------------ |
| OS                          | 12.6                                                         |
| Ruby                        | 3.2.0                                                        |
| Bundler?                    | false                                                        |
| Git                         | git version 2.32.0 (Apple Git-132)                           |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                                          |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.2.0/lib                          |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                                   |
| Is contained                | false                                                        |
| Is homebrew                 | true                                                         |
| Is installed via Fabric.app | false                                                        |
| Xcode Path                  | ~/Documents/Setup/Xcode.app/Contents/Developer/              |
| Xcode Version               | 13.3                                                         |
| Swift Version               | 5.6                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
before_all do
  ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']= '***-****-****-****'
end
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    increment_build_number(build_number: latest_testflight_build_number + 1, 
                           xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("**************") # The bundle identifier of your app
apple_id("***************") # Your Apple Developer Portal username

itc_team_id("******") # App Store Connect Team ID
team_id("**********") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.0.2        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.96.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.4.2        |
| simctl                          | 1.6.8        |
| jwt                             | 2.6.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.3        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.32.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.688.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.168.4      |
| aws-sdk-kms                     | 1.61.0       |
| aws-sdk-s3                      | 1.117.2      |
| set                             | 1.0.3        |
| forwardable                     | 1.3.3        |
| logger                          | 1.5.3        |
| pathname                        | 0.2.1        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.3.3        |
| timeout                         | 0.3.1        |
| securerandom                    | 0.2.2        |
| uri                             | 0.12.0       |
| openssl                         | 3.1.0        |
| digest                          | 3.1.1        |
| ipaddr                          | 1.2.5        |
| resolv                          | 0.2.2        |
| time                            | 0.2.1        |
| stringio                        | 3.0.4        |
| open-uri                        | 0.3.0        |
| mutex_m                         | 0.1.2        |
| net-http                        | 0.3.2        |
| net-protocol                    | 0.2.1        |
| ostruct                         | 0.5.5        |
| english                         | 0.7.2        |
| erb                             | 4.0.2        |
| abbrev                          | 0.1.1        |
| tempfile                        | 0.1.3        |
| delegate                        | 0.3.0        |
| fileutils                       | 1.7.0        |
| tmpdir                          | 0.1.3        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.2        |
| nkf                             | 0.1.2        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.4.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.1        |
| psych                           | 5.0.1        |
</details>

**Comment by Mehu007** [comment]
I am getting same error:-


[✔] 🚀 
[17:36:37]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:36:37]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.5.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.37.1 (Apple Git-137.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.5.1 (21G83)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |
| Swift Version               | 5.7.2                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
before_all do
  ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']= '************'
end
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    increment_build_number(build_number: latest_testflight_build_number + 1, 
                           xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("***********") # The bundle identifier of your app
apple_id("**********.com") # Your Apple Developer Portal username

itc_team_id("******") # App Store Connect Team ID
team_id("*********") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.96.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| simctl                          | 1.6.8        |
| jwt                             | 2.6.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.9.3        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.32.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.168.4      |
| aws-sdk-kms                     | 1.61.0       |
| aws-sdk-s3                      | 1.117.2      |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.5        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.22.0       |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| bundler                         | 2.1.4        |
| webrick                         | 1.7.0        |
| rake                            | 13.0.6       |
| aws-partitions                  | 1.688.0      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>


*generated on:* **2023-01-06**
</details>
[17:36:38]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[17:36:38]: 🙄  Wow, that's a lot of markdown text... should fastlane put it
into your clipboard, so you can easily paste it on GitHub? (y/n)
y
[17:37:27]: Successfully copied markdown into your clipboard 🎨
[17:37:27]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by RalissonMattias** [comment]
+1

**Comment by ramonpaolo** [comment]
+1

**Comment by afaq-karim** [comment]
Getting the same error when using GitHub actions any solutions?

**Comment by NoamEfergan** [comment]
+1

**Comment by moreirawebmaster** [comment]
+1

**Comment by gradam** [comment]
+1

**Comment by LukePJN** [comment]
+1

**Comment by sravanmetro** [comment]
+1

**Comment by nickkrykunov** [comment]
+1

**Comment by braedonwatkins** [comment]
Getting this too when following the docs for GitHub Actions. There's a lot of interesting options and additional steps that I have added which have gotten me to achieve different errors but to no avail. +1

**Comment by RefaelHalfBite** [comment]
for me it was Fastlane.txt 

it should be document and not txt file 
after o changed that everthing works

**Comment by shirakaba** [comment]
Here's my stacktrace. Just like the original comment, my error comes from a call to [ensure_fastfile](https://github.com/fastlane/fastlane/blob/e5dfe9e69f795f06c1420639faafc13fa4761a09/fastlane/lib/fastlane/commands_generator.rb#L109C14-L109C29):

```
/var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:174:in `verify_interactive!'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:138:in `confirm'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:373:in `ensure_fastfile'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /var/lib/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /var/lib/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /var/lib/gems/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /var/lib/gems/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:25:in `load'
	from /usr/local/bin/fastlane:25:in `<main>'
/var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:174:in `verify_interactive!'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:138:in `confirm'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:373:in `ensure_fastfile'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /var/lib/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /var/lib/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /var/lib/gems/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /var/lib/gems/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /var/lib/gems/3.2.0/gems/fastlane-2.228.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:25:in `load'
	from /usr/local/bin/fastlane:25:in `<main>'
Error: Process completed with exit code 1.
```

I worked out that I was calling fastlane from the **wrong working directory**, so it was unable to find my `Fastfile`. Thus, it tried to interactively ask whether it would be okay to generate one for me instead, but as the terminal was non-interactive, it had no choice but to terminate. It also explains how @RefaelHalfBite was able to resolve their case by renaming `Fastfile.txt` to `Fastfile`, because Fastlane wouldn't know to look for it if the filename went against expectations.

To illustrate:

```
.
├── package.json
├── fastlane
│   └── Fastfile
├── ios
└── android
^      ^--- ❌ Don't call `fastlane android deploy` from "android"!
└---------- ✅ Call `fastlane android deploy` from the root instead.
```

**Comment by str1ve21** [comment]
Reinstall pods fixed this issue for me

`cd ios && pod deintegrate && pod install --repo-update`
