### ISSUE TITLE
在macosx13.0.1 m1电脑上build_failure 

### ISSUE THREAD

**Issue by songxuhua** [fastlane/fastlane#20972]
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': [31m[!] Error building the application - see the log above[0m (FastlaneCore::Interface::FastlaneBuildFailure)
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/gym/lib/gym/error_handler.rb:73:in `handle_build_error'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/gym/lib/gym/runner.rb:114:in `block in build_app'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/command_executor.rb:84:in `execute'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/gym/lib/gym/runner.rb:110:in `build_app'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/gym/lib/gym/runner.rb:18:in `run'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/gym/lib/gym/manager.rb:19:in `work'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/gym/lib/gym/commands_generator.rb:45:in `block (2 levels) in run'
 from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
 from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
 from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
 from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/gym/lib/gym/commands_generator.rb:76:in `run'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/gym/lib/gym/commands_generator.rb:16:in `start'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
 from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.0/bin/fastlane:23:in `<top (required)>'
 from /usr/local/bin/fastlane:23:in `load'
 from /usr/local/bin/fastlane:23:in `<main>'

**Comment by mdgeist** [comment]
Really interesting to me that the logs show an older version of Fastlane then what your Fastlane env command shows.

You're also using an end of life version of Ruby might want to use 3.X.

Aside from that your logs don't show much in the way that could be helpful for anyone to assist you with, thats just me though.

**Comment by iBotPeaches** [comment]
Sorry we never visited this in time. I overhauled error system here to make it easier when a sub-command fails - https://github.com/fastlane/fastlane/pull/30097

Closing as resolved.
