### ISSUE TITLE
[supply] ignores skip_upload_changelogs

### ISSUE THREAD

**Issue by seagullua** [fastlane/fastlane#21007]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I pass a `skip_upload_changelogs: true` to `supply`. However the supply fails with the next error `Could not find release for version code 'X' to update changelog `

I expect the supply do not to touch the changelog if I am not asking for it. It makes me impossible to just update metadata without making and uploading a build

##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2023-01-23 13:22:59.17]: --------------------
INFO [2023-01-23 13:22:59.17]: --- Step: supply ---
INFO [2023-01-23 13:22:59.17]: --------------------

+------------------------------------+--------------------------------------+
|                        Summary for supply 2.211.0                         |
+------------------------------------+--------------------------------------+
| skip_upload_changelogs             | true                                 |
| package_name                       | my.app                      |
| skip_upload_apk                    | true                                 |
| skip_upload_aab                    | true                                 |
| track                              | internal                             |
| release_status                     | draft                                |
| version_code                       | 592                                  |
| metadata_path                      | ./fastlane/metadata/android          |
| json_key                           | fastlane/pc-api-google-play-api.json |
| skip_upload_metadata               | false                                |
| skip_upload_images                 | false                                |
| skip_upload_screenshots            | false                                |
| track_promote_release_status       | completed                            |
| validate_only                      | false                                |
| check_superseded_tracks            | false                                |
| timeout                            | 300                                  |
| deactivate_on_promote              | true                                 |
| changes_not_sent_for_review        | false                                |
| rescue_changes_not_sent_for_review | true                                 |
| ack_bundle_installation_warning    | false                                |
+------------------------------------+--------------------------------------+

DEBUG [2023-01-23 13:22:59.18]: Fetching a new access token from Google...
WARN [2023-01-23 13:23:00.59]: Lane Context:
INFO [2023-01-23 13:23:00.59]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>nil, :LANE_NAME=>"google_play_upload_metadata", "VERSION_CODE"=>592}
ERROR [2023-01-23 13:23:00.59]: Could not find release for version code '592' to update changelog
INFO [2023-01-23 13:23:00.60]: Successfully generated documentation at path

+------+-------------------------+-------------+
|               fastlane summary               |
+------+-------------------------+-------------+
| Step | Action                  | Time (in s) |
+------+-------------------------+-------------+
| 1    | default_platform        | 0           |
| 2    | Switch to prebuild lane | 0           |
| 3    | number_of_commits       | 0           |
| 4    | copy_files              | 0           |
| 5    | increment_version_code  | 0           |
| 💥   | supply                  | 1           |
+------+-------------------------+-------------+

DEBUG [2023-01-23 13:23:00.61]: All plugins are up to date
ERROR [2023-01-23 13:23:00.61]: fastlane finished with errors
DEBUG [2023-01-23 13:23:00.61]: All plugins are up to date
/usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Could not find release for version code '592' to update changelog\e[0m (FastlaneCore::Interface::FastlaneError)
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/supply/lib/supply/uploader.rb:89:in `block in perform_upload_meta'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/supply/lib/supply/uploader.rb:84:in `each'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/supply/lib/supply/uploader.rb:84:in `perform_upload_meta'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/supply/lib/supply/uploader.rb:35:in `perform_upload'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:21:in `block in parsing_binding'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/bin/fastlane:25:in `load'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/bin/fastlane:25:in `<main>'
/usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Could not find release for version code '592' to update changelog (FastlaneCore::Interface::FastlaneError)
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/supply/lib/supply/uploader.rb:89:in `block in perform_upload_meta'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/supply/lib/supply/uploader.rb:84:in `each'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/supply/lib/supply/uploader.rb:84:in `perform_upload_meta'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/supply/lib/supply/uploader.rb:35:in `perform_upload'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:21:in `block in parsing_binding'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/bin/fastlane:25:in `load'
        from /usr/local/Cellar/fastlane/2.211.0/libexec/bin/fastlane:25:in `<main>'

```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 13.1                                                    |
| Ruby                        | 3.1.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.39.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.211.0/libexec/bin/fastlane |
| Host                        | macOS 13.1 (22C65)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 14.2                                                    |
| Swift Version               | 5.7.2                                                   |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

lane :google_play_upload_metadata do
    build_number = prebuild()
    puts "Build number: #{build_number}"
    supply(
        skip_upload_changelogs: true,
        package_name: "my.app",
        skip_upload_apk: true,
        skip_upload_aab: true,
        track: "internal",
        release_status: "draft",
        version_code: build_number.to_s
    )
end

lane :prebuild do
    build_number = number_of_commits(all: true)
    puts build_number
    copy_files(
        source: "./fastlane/metadata/changelog.txt",
        destination: "./fastlane/metadata/android/default/changelogs/#{build_number}.txt"
        )
    increment_version_code(
      gradle_file_path: "app/build.gradle",
      version_code: build_number.to_s
    )
    build_number
end

lane :build_and_upload_metadata do
    build_number = prebuild()
    puts build_number

    sh "./prebuild.sh"
    gradle(task: 'bundle',build_type: 'Release')
    supply(
        package_name: "my.app",
        skip_upload_apk: true,
        track: "internal",
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        release_status: "draft",
        version_code: build_number
    )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("fastlane/pc-api-google-play-api.json")
package_name("my.app")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-file_manager           | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| error_highlight                        | 0.3.0        |
| did_you_mean                           | 1.6.1        |
| atomos                                 | 0.1.3        |
| rexml                                  | 3.2.5        |
| CFPropertyList                         | 3.0.5        |
| claide                                 | 1.1.0        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.3.0        |
| xcodeproj                              | 1.22.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.8.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.6.0        |
| addressable                            | 2.8.1        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| optparse                               | 0.1.1        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| artifactory                            | 3.0.15       |
| babosa                                 | 1.0.4        |
| colored                                | 1.2          |
| highline                               | 2.0.3        |
| commander                              | 4.6.0        |
| faraday-em_http                        | 1.0.0        |
| faraday-em_synchrony                   | 1.0.0        |
| faraday-excon                          | 1.1.0        |
| faraday-httpclient                     | 1.0.1        |
| faraday-multipart                      | 1.0.4        |
| faraday-net_http                       | 1.0.1        |
| faraday-net_http_persistent            | 1.2.0        |
| faraday-patron                         | 1.0.0        |
| faraday-rack                           | 1.0.0        |
| faraday-retry                          | 1.0.3        |
| ruby2_keywords                         | 0.0.5        |
| faraday                                | 1.10.2       |
| unf_ext                                | 0.0.8.2      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.5        |
| faraday-cookie_jar                     | 0.0.7        |
| faraday_middleware                     | 1.2.0        |
| fastimage                              | 2.2.6        |
| gh_inspector                           | 1.1.3        |
| naturally                              | 2.2.1        |
| rubyzip                                | 2.3.2        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.1        |
| dotenv                                 | 2.8.1        |
| simctl                                 | 1.6.8        |
| jwt                                    | 2.5.0        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.20       |
| trailblazer-option                     | 0.1.2        |
| representable                          | 3.2.0        |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.1.2        |
| memoist                                | 0.16.2       |
| multi_json                             | 1.15.0       |
| os                                     | 1.1.4        |
| signet                                 | 0.17.0       |
| googleauth                             | 1.3.0        |
| httpclient                             | 2.8.3        |
| webrick                                | 1.7.0        |
| google-apis-core                       | 0.9.1        |
| google-apis-playcustomapp_v1           | 0.12.0       |
| google-cloud-env                       | 1.6.0        |
| google-cloud-errors                    | 1.3.0        |
| google-cloud-core                      | 1.6.0        |
| google-apis-iamcredentials_v1          | 0.16.0       |
| google-apis-storage_v1                 | 0.19.0       |
| rake                                   | 13.0.6       |
| digest-crc                             | 0.6.4        |
| google-cloud-storage                   | 1.44.0       |
| emoji_regex                            | 3.2.3        |
| set                                    | 1.0.2        |
| public_suffix                          | 5.0.1        |
| excon                                  | 0.95.0       |
| json                                   | 2.6.3        |
| mini_magick                            | 4.12.0       |
| bundler                                | 2.3.11       |
| google-apis-androidpublisher_v3        | 0.32.0       |
| aws-eventstream                        | 1.2.0        |
| aws-sigv4                              | 1.5.2        |
| aws-partitions                         | 1.675.0      |
| jmespath                               | 1.6.2        |
| aws-sdk-core                           | 3.168.4      |
| aws-sdk-kms                            | 1.61.0       |
| aws-sdk-s3                             | 1.117.2      |
| forwardable                            | 1.3.2        |
| logger                                 | 1.5.0        |
| pathname                               | 0.2.0        |
| shellwords                             | 0.1.0        |
| cgi                                    | 0.3.1        |
| date                                   | 3.2.2        |
| timeout                                | 0.2.0        |
| stringio                               | 3.0.1        |
| securerandom                           | 0.1.1        |
| uri                                    | 0.11.0       |
| openssl                                | 3.0.0        |
| digest                                 | 3.1.0        |
| io-nonblock                            | 0.1.0        |
| ipaddr                                 | 1.2.4        |
| io-wait                                | 0.2.1        |
| zlib                                   | 2.1.1        |
| resolv                                 | 0.2.1        |
| time                                   | 0.2.0        |
| open-uri                               | 0.2.0        |
| mutex_m                                | 0.1.1        |
| net-protocol                           | 0.1.2        |
| net-http                               | 0.2.0        |
| ostruct                                | 0.5.2        |
| english                                | 0.7.1        |
| erb                                    | 2.2.3        |
| strscan                                | 3.0.1        |
| abbrev                                 | 0.1.0        |
| io-console                             | 0.5.11       |
| tempfile                               | 0.1.2        |
| delegate                               | 0.2.0        |
| fileutils                              | 1.6.0        |
| tmpdir                                 | 0.1.2        |
| base64                                 | 0.1.1        |
| singleton                              | 0.1.1        |
| open3                                  | 0.1.1        |
| nkf                                    | 0.1.1        |
| prettyprint                            | 0.1.1        |
| pp                                     | 0.3.0        |
| find                                   | 0.1.1        |
| yaml                                   | 0.2.0        |
| psych                                  | 4.0.3        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-file_manager           | 0.2.0        |
</details>

*generated on:* **2023-01-23**
</details></pre>
</details>

**Comment by tpneumat** [comment]
I can confirm that I have this exact same issue which is breaking our worflow.
