### ISSUE TITLE
 `block in parsing_binding': \e[31m[!] undefined method `gym' for true:TrueClass (NoMethodError)

### ISSUE THREAD

**Issue by AD-Paladins** [fastlane/fastlane#21097]
Hello there!
I've come with the next error every time I execute the command `bundle exec fastlane createIPA --env AppTargetOne`:

[✔] 🚀
[20:01:34]: Loading from './fastlane/.env.GIFRefreshControl'
[20:01:35]: ------------------------------
[20:01:35]: --- Step: default_platform ---
[20:01:35]: ------------------------------
[20:01:35]: Create Ipa as per scheme name 1. AppTargetOne 2. AppTargetTwo 3. AppTargetThree
[20:01:35]: Driving the lane 'createIPA' 🚀
[20:01:35]: -----------------------------------
[20:01:35]: --- Step: clean_build_artifacts ---
[20:01:35]: -----------------------------------
[20:01:35]: Cleaned up build artifacts 🐙
[20:01:35]: --------------------------------
[20:01:35]: --- Step: clear_derived_data ---
[20:01:35]: --------------------------------
[20:01:35]: Derived Data path located at: /Users/xxxxxx/Library/Developer/Xcode/DerivedData
[20:01:35]: Successfully cleared Derived Data ♻️
+---------------------------+-------------------+
|                 Lane Context                  |
+---------------------------+-------------------+
| ENVIRONMENT               | AppTargetOne |
| DEFAULT_PLATFORM          | ios               |
| PLATFORM_NAME             |                   |
| LANE_NAME                 | createIPA         |
| SIGH_PROFILE_PATHS        |                   |
| DSYM_PATHS                |                   |
| DSYM_LATEST_UPLOADED_DATE |                   |
+---------------------------+-------------------+
[20:01:35]: Error in your Fastfile at line 24
[20:01:35]:     22:	  clear_derived_data . #Delete existing derived data
[20:01:35]:     23:
[20:01:35]:  => 24:	  gym(
[20:01:35]:     25:	    scheme: ENV['SCHEME'],
[20:01:35]:     26:	    export_method:"ad-hoc",

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | default_platform      | 0           |
| 2    | clean_build_artifacts | 0           |
| 3    | clear_derived_data    | 0           |
+------+-----------------------+-------------+

[20:01:35]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/bin/fastlane)
Fastfile:24:in `block in parsing_binding': \e[31m[!] undefined method `gym' for true:TrueClass (NoMethodError)
Did you mean?  gem\e[0m
Did you mean?  gem
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/fastlane-2.212.1/bin/fastlane:23:in `<top (required)>'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `load'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `<top (required)>'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:492:in `exec'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
	from /Users/xxxxxxxx/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'

Bellow, my all my environment:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 13.2.1                                      |
| Ruby                        | 3.0.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.37.1 (Apple Git-137.1)        |
| Installation Source         | ~/.rvm/gems/ruby-3.0.0/bin/fastlane         |
| Host                        | macOS 13.2.1 (22D68)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1t  7 Feb 2023                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.2                                        |
| Swift Version               | 5.7.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

puts "Create Ipa as per scheme name 1. App1 2. App2 3. App3 "
lane :createIPA  do
  # build your iOS app
  clean_build_artifacts # Delete the local dSYM files
  clear_derived_data . #Delete existing derived data

  gym(
    scheme: ENV['SCHEME'],
    export_method:"ad-hoc",
    export_xcargs: "-allowProvisioningUpdates",
    include_bitcode: false,
    export_options: {
      uploadBitcode: false,
      uploadSymbols: false,
      compileBitcode: false,
      provisioningProfiles: {
            ENV['BUNDLE_IDENTIFIER'] => ENV['PROVISION_NAME_ADHOC'] #ENV['PROVISION_NAME_APPSTORE']
          },
          "signingStyle": "manual"
        }
      )
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("aaaaa.bbbbb.Ccccc") # The bundle identifier of your app
apple_id("xxxxxxx@yyyyyy.zzz") # Your Apple Developer Portal username

itc_team_id("xxxxxx") # App Store Connect Team ID
team_id("xxxxxxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.7.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.34.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.719.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.170.0      |
| aws-sdk-kms                     | 1.63.0       |
| aws-sdk-s3                      | 1.119.1      |
| tsort                           | 0.1.0        |
| set                             | 1.0.1        |
| uri                             | 0.10.1       |
| rexml                           | 3.2.5        |
| json                            | 2.6.3        |
| bundler                         | 2.4.7        |
| rake                            | 13.0.6       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| net-smtp                        | 0.2.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.6        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.1        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2023-03-01**
</details>

Exact ruby version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin22]
MacBook Pro 13-inch, M1, 2020

Regards!

**Comment by AD-Paladins** [comment]
Sorry.. there's a dot at the `clear_derived_data .` command....
Closing issue
