### ISSUE TITLE
Operation not permitted - /Users/prakash/Library/Accounts

### ISSUE THREAD

**Issue by prakashmali-fc** [fastlane/fastlane#21103]
[16:52:16]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Mac Catalyst, id:00008103-000A289011EA001E }
{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:00008103-000A289011EA001E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
{ platform:iOS Simulator, id:A30A9A04-2FA7-4E2A-A432-CD837A8F7595, OS:16.2, name:iPad (10th generation) }
{ platform:iOS Simulator, id:09DC35DD-46AC-49B2-84CE-87885B40CFBD, OS:16.2, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:D57D0CC2-CF21-4ED5-98D1-A6D7F7B2B275, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:90352F0D-3E28-4473-95F9-245BC90EEC5B, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:A62119E1-AA83-457D-816E-F4787202A57F, OS:16.2, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:4985ECE3-1DC8-4845-A96E-E29C20F22084, OS:16.2, name:iPhone 14 }
{ platform:iOS Simulator, id:E9081957-8DC7-481E-ADEF-7250C3679632, OS:16.2, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:8E1DCC1E-EC9C-443F-A6D8-E8A1CDD9B56B, OS:16.2, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:2D350938-F7FB-463E-B175-F672EF47AF3C, OS:16.2, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:3A55614B-E8DC-4E48-A5D4-16A9CDBA60C4, OS:16.2, name:iPhone SE (3rd generation) }
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Mac Catalyst, id:00008103-000A289011EA001E }
{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:00008103-000A289011EA001E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
{ platform:iOS Simulator, id:A30A9A04-2FA7-4E2A-A432-CD837A8F7595, OS:16.2, name:iPad (10th generation) }
{ platform:iOS Simulator, id:09DC35DD-46AC-49B2-84CE-87885B40CFBD, OS:16.2, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:D57D0CC2-CF21-4ED5-98D1-A6D7F7B2B275, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:90352F0D-3E28-4473-95F9-245BC90EEC5B, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:A62119E1-AA83-457D-816E-F4787202A57F, OS:16.2, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:4985ECE3-1DC8-4845-A96E-E29C20F22084, OS:16.2, name:iPhone 14 }
{ platform:iOS Simulator, id:E9081957-8DC7-481E-ADEF-7250C3679632, OS:16.2, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:8E1DCC1E-EC9C-443F-A6D8-E8A1CDD9B56B, OS:16.2, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:2D350938-F7FB-463E-B175-F672EF47AF3C, OS:16.2, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:3A55614B-E8DC-4E48-A5D4-16A9CDBA60C4, OS:16.2, name:iPhone SE (3rd generation) }
+------------------------------+--------------+
|                Lane Context                 |
+------------------------------+--------------+
| DEFAULT_PLATFORM             | ios          |
| PLATFORM_NAME                | ios          |
| LANE_NAME                    | ios ci_check |
| SCAN_GENERATED_XCRESULT_PATH |              |
| SCAN_DERIVED_DATA_PATH       | /Users       |
+------------------------------+--------------+
[16:52:21]: Operation not permitted - /Users/prakash/Library/Accounts

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | swiftlint        | 0           |
| 💥   | scan             | 122         |
+------+------------------+-------------+

[16:52:21]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

#######################################################################
# fastlane 2.212.1 is available. You are on 2.212.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.212.1 Fix for Apple ID lockout and Access Forbidden with new hashcash header
* [spaceship] Implements new hashcash header in auth flow (#21073) via Josh Holtz (@joshdholtz)
* [spaceship] Fix Apple ID 2FA with SMS (#21072) via Josh Holtz (@joshdholtz)

Please update using `bundle update fastlane`
bundler: failed to load command: fastlane (/Users/prakash/.gem/ruby/3.1.3/bin/fastlane)
<internal:dir>:128:in `[]': \e[31m[!] Operation not permitted - /Users/prakash/Library/Accounts\e[0m (Errno::EPERM)
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/scan/lib/scan/manager.rb:30:in `test_summary_filenames'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/actions/run_tests.rb:43:in `ensure in run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/actions/run_tests.rb:46:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:22:in `block (2 levels) in parsing_binding'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/prakash/.gem/ruby/3.1.3/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/prakash/.gem/ruby/3.1.3/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/bin/fastlane:23:in `<top (required)>'
	from /Users/prakash/.gem/ruby/3.1.3/bin/fastlane:25:in `load'
	from /Users/prakash/.gem/ruby/3.1.3/bin/fastlane:25:in `<top (required)>'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
	from /Users/prakash/.gem/ruby/3.1.3/bin/bundle:25:in `load'
	from /Users/prakash/.gem/ruby/3.1.3/bin/bundle:25:in `<main>'
<internal:dir>:128:in `[]': Operation not permitted - /Users/prakash/Library/Accounts (Errno::EPERM)
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/scan/lib/scan/manager.rb:30:in `test_summary_filenames'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/scan/lib/scan/manager.rb:12:in `work'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/actions/run_tests.rb:17:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:22:in `block (2 levels) in parsing_binding'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/prakash/.gem/ruby/3.1.3/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/prakash/.gem/ruby/3.1.3/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/prakash/.gem/ruby/3.1.3/gems/fastlane-2.212.0/bin/fastlane:23:in `<top (required)>'
	from /Users/prakash/.gem/ruby/3.1.3/bin/fastlane:25:in `load'
	from /Users/prakash/.gem/ruby/3.1.3/bin/fastlane:25:in `<top (required)>'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/prakash/.gem/ruby/3.1.3/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
	from /Users/prakash/.gem/ruby/3.1.3/bin/bundle:25:in `load'
	from /Users/prakash/.gem/ruby/3.1.3/bin/bundle:25:in `<main>'

**Comment by sergiocaserowl** [comment]
Did you solve it @prakashmali-fc? Facing the same issue now
