### ISSUE TITLE
User 'xxxxx@hotmail.com' does not have access to any teams with an active membership (RuntimeError)

### ISSUE THREAD

**Issue by Jacky-LinPeng** [fastlane/fastlane#21222]
My personal Apple ID, not joining any development group, and then I use the spaceship to log in and get mobileprovision, and there is an error
```
Spaceship.login('skodiboyy@hotmail.com', 'xxxxx')
```

Error desc:
```
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/portal/portal_client.rb:62:in `team_id': User 'skodiboyy@hotmail.com' does not have access to any teams with an active membership (RuntimeError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/portal/portal_client.rb:123:in `block in apps'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/client.rb:325:in `block in paging'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/client.rb:323:in `loop'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/client.rb:323:in `paging'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/portal/portal_client.rb:121:in `apps'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/portal/app.rb:85:in `all'
	from FreeAccount.rb:8:in `<main>'
```

I am curious that Xcode supports ordinary personal Apple Id(non-developer account) to get certificate, TeamID and profile. Although the profile is only valid for 7 days, but...why do I get the above error when I use Spaceship to get it?
<img width="931" alt="image" src="https://user-images.githubusercontent.com/15797691/233527101-47823fef-6580-4250-97f8-9b0fcf551ae4.png">
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/15797691/233527308-a531e95c-4add-4358-a582-4282634a55fa.png">

My personal understanding is: Spaceship and Xcode certificate description file management is through the developerservices2.apple.com interface service implementation, Xcode support personal AppleID obtain profile information, why Why can't Spaceship get it?
<img width="762" alt="image" src="https://user-images.githubusercontent.com/15797691/233527412-156c2218-72d7-4a70-802c-d3f38fb10396.png">

Hope to get your advice and help

**Comment by Jacky-LinPeng** [comment]
https://github.com/fastlane/fastlane/issues/6316

**Comment by Jacky-LinPeng** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

```
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 13.0                                                           |
| Ruby                        | 2.6.10                                                         |
| Bundler?                    | false                                                          |
| Git                         | git version 2.37.1 (Apple Git-137.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 13.0 (22A5365d)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 14.2                                                           |
| Swift Version               | 5.7.2                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.206.2 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.7.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 1.17.2       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.4.4        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 12.3.3       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.529.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.122.1      |
| aws-sdk-kms                     | 1.51.0       |
| aws-sdk-s3                      | 1.105.1      |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.5        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.22.0       |
| unicode-display_width           | 1.8.0        |
| public_suffix                   | 4.0.7        |
| json                            | 2.6.2        |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.3        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>


*generated on:* **2023-04-21**
</details>
```
