### ISSUE TITLE
slather error on Azure Fastlane - Xcode 14.3 - macOS-13

### ISSUE THREAD

**Issue by salvatoreboemia** [fastlane/fastlane#21306]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I upadated on Azure my pipeline in order to use latest version of macOS and Xcode (13 and 14.3), but the slather scan failed (only with new macOS and Xcode version)

**Azure error:**

```
Exit status of command 'slather coverage --cobertura-xml --build-directory ./DerivedData --output-directory ./DerivedData/test-output/slatherOutput --ignore Pods/\* --ignore fastlane/\* --ignore build/\* --ignore DerivedData/\* --verbose --scheme ProjectName --workspace ProjectName.xcworkspace ./ProjectName.xcodeproj' was 1 instead of 0.

Slathering...
/usr/local/lib/ruby/gems/3.0.0/gems/slather-2.7.4/lib/slather/project.rb:239:in `profdata_coverage_dir': No coverage directory found. (StandardError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/slather-2.7.4/lib/slather/project.rb:517:in `find_binary_files'
	from /usr/local/lib/ruby/gems/3.0.0/gems/slather-2.7.4/lib/slather/project.rb:336:in `configure'
	from /usr/local/lib/ruby/gems/3.0.0/gems/slather-2.7.4/lib/slather/command/coverage_command.rb:59:in `execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/slather-2.7.4/bin/slather:17:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/slather:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/slather:25:in `<main>'
No coverage directory found.

	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
	If you use a different Xcode configuration, did you specify it? (--configuration or 'configuration' in .slather.yml)
```

**And this is part of my fastlane file**

```
scan(
      workspace: MyWorkspace,
      clean: true,
      device: "iPhone 8",
      # devices: ["iPhone 8", "iPad Air"],
      #output_files: "TEST-report.xml",
      scheme: Targets::DEV,
      code_coverage: true,
      skip_build: true,
      skip_testing: "ProjectNameTargetAppUITests",
      output_directory: "./DerivedData/test-output/scan",
      derived_data_path: "./DerivedData")
    
    slather(
      build_directory: "./DerivedData",
      scheme: Targets::DEV,
      workspace: ProjectWorkspace,
      proj: MyProject,
      output_directory: "./DerivedData/test-output/slatherOutput", 
      cobertura_xml: true,
      verbose: true,
      ignore: ["Pods/*", "fastlane/*", "build/*", "DerivedData/*"])      
  end
```

Do you have any suggestions in order to fix this issue on Azure and fastlane?

Thanks a lot

**Comment by salvatoreboemia** [comment]
Azure Env

**Comment by salvatoreboemia** [comment]
News? I tried also on Xcode 15 and GitHub, bit I got the same error

**Comment by jarrodlombardo-EventBase** [comment]
This was working fine in XCode 14.2 and earlier. This is a XCode or Slather bug, not a fastlane issue.
I can't get my projects to show code coverage in XCode at all anymore, so it's more likely XCode is broken here than Slather.

**Comment by jarrodlombardo-EventBase** [comment]
Yeah, it's an XCode issue: https://developer.apple.com/forums/thread/734611
It seems that if you have any upstream dependencies that were built with XCode 14.2 or earlier, they will silently break your code coverage in XCode 14.3+.
