### ISSUE TITLE
Screengrab is not working with the latest adb version. 

### ISSUE THREAD

**Issue by SamAmco** [fastlane/fastlane#21300]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have a lane set up as follows: 

```
desc "Build and run the instrumented tests and take screenshots"
  lane :take_screenshots do
    capture_android_screenshots(
      locales: ["en-US"],
      clear_previous_screenshots: true,
      app_apk_path: "app/build/outputs/apk/prod/debug/app-prod-debug.apk",
      tests_apk_path: "./app/build/outputs/apk/androidTest/prod/debug/app-prod-debug-androidTest.apk",
      test_instrumentation_runner: "uk.co.brandwidth.connectedcustomerapp.BrandwidthHiltTestRunner",
      tests_package_name: "com.aml.connectedcustomerapp.test",
      app_package_name: "com.aml.connectedcustomerapp"
    )
  end
```

When running this lane I can see that the following commands are run: 

```
[✔] 🚀
+----------------------------------+---------+------------------+
|                         Used plugins                          |
+----------------------------------+---------+------------------+
| Plugin                           | Version | Action           |
+----------------------------------+---------+------------------+
| fastlane-plugin-get_version_name | 0.2.2   | get_version_name |
| fastlane-plugin-unzip            | 1.0.1   | unzip            |
+----------------------------------+---------+------------------+

[18:07:34]: ------------------------------
[18:07:34]: --- Step: default_platform ---
[18:07:34]: ------------------------------
[18:07:34]: Driving the lane 'take_screenshots' 🚀
[18:07:34]: -----------------------------------------
[18:07:34]: --- Step: capture_android_screenshots ---
[18:07:34]: -----------------------------------------

+-----------------------------+-------------------------------------------------------------------------------+
|                                       Summary for screengrab 2.212.2                                        |
+-----------------------------+-------------------------------------------------------------------------------+
| locales                     | ["en-US"]                                                                     |
| clear_previous_screenshots  | true                                                                          |
| app_apk_path                | app/build/outputs/apk/prod/debug/app-prod-debug.apk                           |
| tests_apk_path              | ./app/build/outputs/apk/androidTest/prod/debug/app-prod-debug-androidTest.apk |
| test_instrumentation_runner | uk.co.brandwidth.connectedcustomerapp.BrandwidthHiltTestRunner                |
| tests_package_name          | com.aml.connectedcustomerapp.test                                             |
| app_package_name            | com.aml.connectedcustomerapp                                                  |
| android_home                | /home/sam/Android/Sdk                                                         |
| output_directory            | fastlane/metadata/android                                                     |
| skip_open_summary           | true                                                                          |
| ending_locale               | en-US                                                                         |
| use_adb_root                | false                                                                         |
| device_type                 | phone                                                                         |
| exit_on_test_failure        | true                                                                          |
| reinstall_app               | false                                                                         |
| use_timestamp_suffix        | true                                                                          |
+-----------------------------+-------------------------------------------------------------------------------+

[18:07:34]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[18:07:34]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[18:07:34]: Clearing phoneScreenshots within fastlane/metadata/android
[18:07:34]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[18:07:34]: ▸ /sdcard
[18:07:34]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell echo \$ANDROID_DATA
[18:07:34]: ▸ /data
[18:07:34]: Cleaning screenshots on device
ls: /sdcard/com.aml.connectedcustomerapp/screengrab/en-US/images/screenshots: No such file or directory
[18:07:34]: Exit status: 1
ls: /sdcard/Android/data/com.aml.connectedcustomerapp/files/screengrab/en-US/images/screenshots: No such file or directory
[18:07:34]: Exit status: 1
run-as: unknown package: com.aml.connectedcustomerapp
[18:07:34]: Exit status: 1
run-as: unknown package: com.aml.connectedcustomerapp
[18:07:34]: Exit status: 1
run-as: unknown package: com.aml.connectedcustomerapp
[18:07:34]: Exit status: 1
run-as: unknown package: com.aml.connectedcustomerapp
[18:07:34]: Exit status: 1
[18:07:34]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[18:07:34]: ▸ 31
[18:07:34]: Installing app APK
[18:07:34]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/prod/debug/app-prod-debug.apk
[18:07:34]: ▸ Performing Incremental Install
[18:07:34]: ▸ Serving...
[18:07:34]: ▸ Success
[18:07:34]: ▸ Install command complete in 222 ms
[18:07:34]: Installing tests APK
[18:07:34]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 install -t -r ./app/build/outputs/apk/androidTest/prod/debug/app-prod-debug-androidTest.apk
[18:07:34]: ▸ Performing Incremental Install
[18:07:34]: ▸ Serving...
[18:07:34]: ▸ All files should be loaded. Notifying the device.
[18:07:34]: ▸ Success
[18:07:34]: ▸ Install command complete in 102 ms
[18:07:34]: Granting the permission necessary to change locales on the device
[18:07:34]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm grant com.aml.connectedcustomerapp android.permission.CHANGE_CONFIGURATION
[18:07:34]: Granting the permissions necessary to access device external storage
[18:07:34]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm grant com.aml.connectedcustomerapp android.permission.WRITE_EXTERNAL_STORAGE
[18:07:34]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm grant com.aml.connectedcustomerapp android.permission.READ_EXTERNAL_STORAGE
[18:07:34]: Enabling clean status bar
[18:07:34]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm grant com.aml.connectedcustomerapp android.permission.DUMP
[18:07:35]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell settings put global sysui_demo_allowed 1
[18:07:35]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.aml.connectedcustomerapp.test
[18:07:35]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.aml.connectedcustomerapp
[18:07:35]: Running tests for locale: en-US
[18:07:35]: $ /home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en-US \
--no-hidden-api-checks \
-e appendTimestamp true \
com.aml.connectedcustomerapp.test/uk.co.brandwidth.connectedcustomerapp.BrandwidthHiltTestRunner
[18:07:35]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.aml.connectedcustomerapp.test/uk.co.brandwidth.connectedcustomerapp.BrandwidthHiltTestRunner
[18:07:35]: ▸   at com.android.commands.am.Instrument.run(Instrument.java:524)
[18:07:35]: ▸   at com.android.commands.am.Am.runInstrument(Am.java:199)
[18:07:35]: ▸   at com.android.commands.am.Am.onRun(Am.java:80)
[18:07:35]: ▸   at com.android.internal.os.BaseCommand.run(BaseCommand.java:62)
[18:07:35]: ▸   at com.android.commands.am.Am.main(Am.java:50)
[18:07:35]: ▸   at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[18:07:35]: ▸   at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
android.util.AndroidException: INSTRUMENTATION_FAILED: com.aml.connectedcustomerapp.test/uk.co.brandwidth.connectedcustomerapp.BrandwidthHiltTestRunner
        at com.android.commands.am.Instrument.run(Instrument.java:524)
                at com.android.commands.am.Am.runInstrument(Am.java:199)
                        at com.android.commands.am.Am.onRun(Am.java:80)
                                at com.android.internal.os.BaseCommand.run(BaseCommand.java:62)
                                        at com.android.commands.am.Am.main(Am.java:50)
                                                at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
                                                        [18:07:35]: Exit status: 1
                                                        +------------------+------------------+
                                                        |            Lane Context             |
                                                        +------------------+------------------+
                                                        | DEFAULT_PLATFORM | android          |
                                                        | PLATFORM_NAME    |                  |
                                                        | LANE_NAME        | take_screenshots |
                                                        +------------------+------------------+
                                                        [18:07:35]: Exit status: 1

                                                        +------+-----------------------------+-------------+
                                                        |                 fastlane summary                 |
                                                        +------+-----------------------------+-------------+
                                                        | Step | Action                      | Time (in s) |
                                                        +------+-----------------------------+-------------+
                                                        | 1    | default_platform            | 0           |
                                                        | 💥   | capture_android_screenshots | 0           |
                                                        +------+-----------------------------+-------------+

                                                        [18:07:35]: fastlane finished with errors

                                                        [!] Exit status: 1
```
If I run the exact same list of commands manually it is successful and the instrumented tests start normally: 

```
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/prod/debug/app-prod-debug.apk
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 install -t -r ./app/build/outputs/apk/androidTest/prod/debug/app-prod-debug-androidTest.apk
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm grant com.aml.connectedcustomerapp android.permission.CHANGE_CONFIGURATION
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm grant com.aml.connectedcustomerapp android.permission.WRITE_EXTERNAL_STORAGE
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm grant com.aml.connectedcustomerapp android.permission.READ_EXTERNAL_STORAGE
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm grant com.aml.connectedcustomerapp android.permission.DUMP
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell settings put global sysui_demo_allowed 1
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.aml.connectedcustomerapp.test
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.aml.connectedcustomerapp
/home/sam/Android/Sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en-US \
--no-hidden-api-checks \
-e appendTimestamp true \
com.aml.connectedcustomerapp.test/uk.co.brandwidth.connectedcustomerapp.BrandwidthHiltTestRunner
```

After running the lane if i investigate the device I notice that the apk for the actual app (app-prod-debug.apk) is not actually installed. You can confirm this using: `adb shell pm list packages` The package is not there on the device. 

I managed to fix this issue on my machine by installing adb via apt using: 

`sudo apt install adb`

if i then run: 

`adb --version`

I get the output: 

```
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5ubuntu2
Installed as /usr/lib/android-sdk/platform-tools/adb
```

Now if i run the tests, both apks install successfully and the tests run. 

The version of adb that I have otherwise is installed with android studio is: 

```
Android Debug Bridge version 1.0.41                                                                                                                                                    
Version 34.0.1-9680074                                                                                                                                                                 
Installed as /home/sam/Android/Sdk/platform-tools/adb
```

With this version I see the above issue that the app apk is not properly installed via fastlane even though replicating fastlanes steps manually results in a successful installation. 

### Environment

[18:19:53]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                            |
| --------------------------- | ---------------------------------------------------------------- |
| OS                          | debian_based bullseye/sid                                        |
| Ruby                        | 3.1.2                                                            |
| Bundler?                    | true                                                             |
| Git                         | git version 2.25.1                                               |
| Installation Source         | ~/.rbenv/versions/3.1.2/bin/fastlane                             |
| Host                        | Ubuntu 20.04.3 LTS debian_based bullseye/sid (5.15.0-72-generic) |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.2/lib                                      |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                                      |
| Is contained                | false                                                            |
| Is homebrew                 | false                                                            |
| Is installed via Fabric.app | false                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_GB:en    | 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
...

desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    build_android_app(task: 'assembleProdDebug')
    build_android_app(task: 'assembleProdDebugAndroidTest')
  end

desc "Build and run the instrumented tests and take screenshots"
  lane :take_screenshots do
    capture_android_screenshots(
      locales: ["en-US"],
      clear_previous_screenshots: true,
      app_apk_path: "app/build/outputs/apk/prod/debug/app-prod-debug.apk",
      tests_apk_path: "./app/build/outputs/apk/androidTest/prod/debug/app-prod-debug-androidTest.apk",
      test_instrumentation_runner: "uk.co.brandwidth.connectedcustomerapp.BrandwidthHiltTestRunner",
      tests_package_name: "com.aml.connectedcustomerapp.test",
      app_package_name: "com.aml.connectedcustomerapp"
    )
  end

desc "Do a gradle build and then generate screenshots"
  lane :build_screenshots do
    build_for_screengrab
    take_screenshots
  end

desc "Do a clean gradle build and then generate screenshots"
  lane :clean_build_screenshots do
    gradle(task: "clean")
    build_screenshots
  end
...

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.aml.connectedcustomerapp.ConnectedCustomerApplication") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                           | Version | Update-Status |
| -------------------------------- | ------- | ------------- |
| fastlane-plugin-get_version_name | 0.2.2   | ✅ Up-To-Date  |
| fastlane-plugin-unzip            | 1.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                              | Version      |
| -------------------------------- | ------------ |
| error_highlight                  | 0.3.0        |
| did_you_mean                     | 1.6.1        |
| bundler                          | 2.3.24       |
| pathname                         | 0.2.0        |
| rake                             | 13.0.6       |
| rexml                            | 3.2.5        |
| CFPropertyList                   | 3.0.6        |
| public_suffix                    | 5.0.1        |
| addressable                      | 2.8.4        |
| artifactory                      | 3.0.15       |
| atomos                           | 0.1.3        |
| aws-eventstream                  | 1.2.0        |
| aws-partitions                   | 1.767.0      |
| aws-sigv4                        | 1.5.2        |
| jmespath                         | 1.6.2        |
| aws-sdk-core                     | 3.173.0      |
| aws-sdk-kms                      | 1.64.0       |
| aws-sdk-s3                       | 1.122.0      |
| babosa                           | 1.0.4        |
| claide                           | 1.1.0        |
| colored                          | 1.2          |
| colored2                         | 3.1.2        |
| highline                         | 2.0.3        |
| commander                        | 4.6.0        |
| declarative                      | 0.0.20       |
| digest-crc                       | 0.6.4        |
| unf_ext                          | 0.0.8.2      |
| unf                              | 0.1.4        |
| domain_name                      | 0.5.20190701 |
| dotenv                           | 2.8.1        |
| emoji_regex                      | 3.2.3        |
| excon                            | 0.99.0       |
| faraday-em_http                  | 1.0.0        |
| faraday-em_synchrony             | 1.0.0        |
| faraday-excon                    | 1.1.0        |
| faraday-httpclient               | 1.0.1        |
| multipart-post                   | 2.0.0        |
| faraday-multipart                | 1.0.4        |
| faraday-net_http                 | 1.0.1        |
| faraday-net_http_persistent      | 1.2.0        |
| faraday-patron                   | 1.0.0        |
| faraday-rack                     | 1.0.0        |
| faraday-retry                    | 1.0.3        |
| ruby2_keywords                   | 0.0.5        |
| faraday                          | 1.10.3       |
| http-cookie                      | 1.0.5        |
| faraday-cookie_jar               | 0.0.7        |
| faraday_middleware               | 1.2.0        |
| fastimage                        | 2.2.6        |
| gh_inspector                     | 1.1.3        |
| jwt                              | 2.7.0        |
| memoist                          | 0.16.2       |
| multi_json                       | 1.15.0       |
| os                               | 1.1.4        |
| signet                           | 0.17.0       |
| googleauth                       | 1.5.2        |
| httpclient                       | 2.8.3        |
| mini_mime                        | 1.1.2        |
| trailblazer-option               | 0.1.2        |
| uber                             | 0.1.0        |
| representable                    | 3.2.0        |
| retriable                        | 3.1.2        |
| webrick                          | 1.8.1        |
| google-apis-core                 | 0.11.0       |
| google-apis-androidpublisher_v3  | 0.42.0       |
| google-apis-playcustomapp_v1     | 0.13.0       |
| google-apis-iamcredentials_v1    | 0.17.0       |
| google-apis-storage_v1           | 0.19.0       |
| google-cloud-env                 | 1.6.0        |
| google-cloud-errors              | 1.3.1        |
| google-cloud-core                | 1.6.0        |
| google-cloud-storage             | 1.44.0       |
| json                             | 2.6.3        |
| mini_magick                      | 4.12.0       |
| naturally                        | 2.2.1        |
| optparse                         | 0.1.1        |
| plist                            | 3.7.0        |
| rubyzip                          | 2.3.2        |
| security                         | 0.1.3        |
| simctl                           | 1.6.10       |
| terminal-notifier                | 2.0.0        |
| unicode-display_width            | 1.8.0        |
| terminal-table                   | 1.8.0        |
| tty-screen                       | 0.8.1        |
| tty-cursor                       | 0.7.1        |
| tty-spinner                      | 0.9.3        |
| word_wrap                        | 1.0.0        |
| nanaimo                          | 0.3.0        |
| xcodeproj                        | 1.22.0       |
| rouge                            | 2.0.7        |
| xcpretty                         | 0.3.0        |
| xcpretty-travis-formatter        | 1.0.1        |
| fastlane-plugin-get_version_name | 0.2.2        |
| fastlane-plugin-unzip            | 1.0.1        |
| ffi                              | 1.15.5       |
| ffi-compiler                     | 1.0.1        |
| http-form_data                   | 2.3.0        |
| llhttp-ffi                       | 0.4.0        |
| http                             | 5.1.1        |
</details>

*generated on:* **2023-05-23**
</details>
[18:19:53]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[18:19:53]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m

**Comment by jpaas** [comment]
Same issue here. But no one answered this issue after a full year. Is fastlane still maintained?
