### ISSUE TITLE
The URL path is not valid - The resource 'resetRatingsRequests' does not exist

### ISSUE THREAD

**Issue by Krishsidu** [fastlane/fastlane#21328]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running "fastlane deliver" with the "reset_ratings" field in the Deliverfile set to true, we're getting the error below (see complete output)

##### Command executed
fastlane deliver -f --verbose --api_key_path ****

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': \e[31m[!] The URL path is not valid - The resource 'v1/resetRatingsRequests' does not exist\e[0m (Spaceship::UnexpectedResponse)
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:961:in `post_reset_ratings_request'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/forwardable.rb:238:in `post_reset_ratings_request'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:236:in `create_reset_ratings_request'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/deliver/lib/deliver/upload_metadata.rb:335:in `upload'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/deliver/lib/deliver/runner.rb:152:in `upload_metadata'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/deliver/lib/deliver/runner.rb:61:in `run'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:187:in `run'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:18:in `start'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/gems/fastlane-2.212.1/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.212.1/libexec/bin/fastlane:25:in `<main>'</pre>
</details>

### Environment
<details>
  <pre> ✅ fastlane environment ✅ </pre>
</details>

**Comment by Krishsidu** [comment]
@joshdholtz Can you take a look into this issue? This was raised couple of years back - https://github.com/fastlane/fastlane/issues/19250 but there was **no resolution** We are still facing the same issue.

**Comment by christruong90** [comment]
I am also still seeing this problem.

**Comment by SaiBhargav30393** [comment]
I am also seeing the issue.

**Comment by Jaelyn-DM** [comment]
I am seeing the issue as well.

**Comment by christruong90** [comment]
Any updates on this issue? Please help =(

**Comment by Ann2550** [comment]
Waiting for the solution!!

**Comment by Krishsidu** [comment]
Any update on this issue? Thanks.

**Comment by Krishsidu** [comment]
Any updates here?
