### ISSUE TITLE
The specified resource does not exist - There is no resource of type 'AppsV1' with id 'APPLE_TEAM_ID'

### ISSUE THREAD

**Issue by ohanqo** [fastlane/fastlane#21345]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

While submitting a binary to TestFlight, running our `deploy_testflight` lane, an error occurs:

`The specified resource does not exist - There is no resource of type 'AppsV1' with id 'APPLE_TEAM_ID'`
> I've obfuscated the team id and replaced it with APPLE_TEAM_ID.

The binary is correctly uploaded and available on TestFlight but the job still failed with the above error.

I think the error occurred when we tested the `distribute_external`, `groups` and `changelog` parameters. But the error is still present even without these parameters.

Our `deploy_testflight` lane is pretty simple:

```ruby
desc "Deploy new release to TestFlight"
lane :deploy_testflight do
  api_key = app_store_connect_api_key(
    key_id: APPLE_KEY_ID,
    issuer_id: APPLE_ISSUER_ID,
    key_content: APPLE_KEY_CONTENT,  
    duration: 1200,            
    in_house: false
  )

  upload_to_testflight(
    ipa:"build/appname.ipa",
    api_key: api_key,
    apple_id: APPLE_ID,
  )
end
```

##### Command executed

`fastlane deploy_testflight`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> $ fastlane deploy_testflight
[14:01:21]: fastlane detected a Gemfile in the current directory
[14:01:21]: However, it seems like you didn't use `bundle exec`
[14:01:21]: To launch fastlane faster, please use
[14:01:21]: 
[14:01:21]: $ bundle exec fastlane deploy_testflight
[14:01:21]: 
[14:01:21]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:01:25]: ------------------------------
[14:01:25]: --- Step: default_platform ---
[14:01:25]: ------------------------------
[14:01:25]: Driving the lane 'ios deploy_testflight' 🚀
[14:01:25]: ---------------------------------------
[14:01:25]: --- Step: app_store_connect_api_key ---
[14:01:25]: ---------------------------------------
[14:01:25]: ----------------------------------
[14:01:25]: --- Step: upload_to_testflight ---
[14:01:25]: ----------------------------------
[14:01:25]: Creating authorization token for App Store Connect API
[14:01:25]: Ready to upload new build to TestFlight (App: APPLE_TEAM_ID)...
[14:01:25]: Going to upload updated app to App Store Connect
[14:01:25]: This might take a few minutes. Please don't interrupt the script.
[14:02:07]: --------------------------------------------------------------------
[14:02:07]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
[14:02:07]: --------------------------------------------------------------------
[14:02:07]: Successfully uploaded the new binary to App Store Connect
[14:02:07]: Creating authorization token for App Store Connect API
[14:02:07]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[14:02:07]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
+------------------+-----------------------+
|               Lane Context               |
+------------------+-----------------------+
| DEFAULT_PLATFORM | ios                   |
| PLATFORM_NAME    | ios                   |
| LANE_NAME        | ios deploy_testflight |
+------------------+-----------------------+
[14:02:08]: The specified resource does not exist - There is no resource of type 'AppsV1' with id 'APPLE_TEAM_ID'
+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | app_store_connect_api_key | 0           |
| 💥   | upload_to_testflight      | 42          |
+------+---------------------------+-------------+
[14:02:08]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': \e[31m[!] The specified resource does not exist - There is no resource of type 'AppsV1' with id 'APPLE_TEAM_ID'\e[0m (Spaceship::UnexpectedResponse)
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:27:in `get_app'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `get_app'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/spaceship/lib/spaceship/connect_api/models/app.rb:101:in `get'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/pilot/lib/pilot/manager.rb:45:in `app'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/pilot/lib/pilot/build_manager.rb:123:in `wait_for_build_processing_to_be_complete'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/pilot/lib/pilot/build_manager.rb:78:in `upload'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:86:in `block (2 levels) in parsing_binding'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/bin/fastlane:23:in `<top (required)>'
	from /var/folders/hw/sw9nj0ld2w3_n7gjttrv22xc0000gp/T/frum_58942_1686916868499/bin/fastlane:25:in `load'
	from /var/folders/hw/sw9nj0ld2w3_n7gjttrv22xc0000gp/T/frum_58942_1686916868499/bin/fastlane:25:in `<main>'
/Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': The specified resource does not exist - There is no resource of type 'AppsV1' with id 'APPLE_TEAM_ID' (Spaceship::UnexpectedResponse)
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:27:in `get_app'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `get_app'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/spaceship/lib/spaceship/connect_api/models/app.rb:101:in `get'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/pilot/lib/pilot/manager.rb:45:in `app'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/pilot/lib/pilot/build_manager.rb:123:in `wait_for_build_processing_to_be_complete'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/pilot/lib/pilot/build_manager.rb:78:in `upload'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:86:in `block (2 levels) in parsing_binding'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/runner/.frum/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/bin/fastlane:23:in `<top (required)>'
	from /var/folders/hw/sw9nj0ld2w3_n7gjttrv22xc0000gp/T/frum_58942_1686916868499/bin/fastlane:25:in `load'
	from /var/folders/hw/sw9nj0ld2w3_n7gjttrv22xc0000gp/T/frum_58942_1686916868499/bin/fastlane:25:in `<main>'
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit status 1</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                |
| --------------------------- | ------------------------------------------------------------------------------------ |
| OS                          | 12.6.2                                                                               |
| Ruby                        | 3.1.2                                                                                |
| Bundler?                    | false                                                                                |
| Git                         | git version 2.37.1 (Apple Git-137.1)                                                 |
| Installation Source         | /var/folders/hw/sw9nj0ld2w3_n7gjttrv22xc0000gp/T/frum_609_1686902214806/bin/fastlane |
| Host                        | macOS 12.6.2 (21G320)                                                                |
| Ruby Lib Dir                | ~/.frum/versions/3.1.2/lib                                                           |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                                                          |
| Is contained                | false                                                                                |
| Is homebrew                 | false                                                                                |
| Is installed via Fabric.app | false                                                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                          |
| Xcode Version               | 14.2                                                                                 |
| Swift Version               | 5.7.2                                                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.213.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| emoji_regex                     | 3.2.3        |
| set                             | 1.0.2        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.6        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.22.0       |
| plist                           | 3.7.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.4        |
| excon                           | 0.99.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| dotenv                          | 2.8.1        |
| bundler                         | 2.4.13       |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.1        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.17.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.5.2        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.41.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.19.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-partitions                  | 1.762.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.172.0      |
| aws-sdk-kms                     | 1.64.0       |
| aws-sdk-s3                      | 1.122.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2023-06-16**
</details>

**Comment by cbjerg** [comment]
Getting this error as well. Looks like it is present on get_app_store_versions
```
 app = Spaceship::ConnectAPI.get_app(app_id: options[:appid]).first
 UI.message("app name is #{app.name}")
version = app.get_app_store_versions.first
UI.message("app_store_state is #{version.app_store_state}")
```

**Comment by lucasmarcal-faire** [comment]
Same here

**Comment by berktec** [comment]
same here

**Comment by buidanhnam** [comment]
same here

**Comment by dfed** [comment]
I was hitting this. Turns out I'd moved to a new app with a new `apple_id`, and this started happening when I removed the old app from the App Store. Updating the `apple_id` field to the correct ID for the new app fixed the issue. Hopefully that helps y'all.

**Comment by ir-fuel** [comment]
Same problem here. Started happening when I added a changelog to my upload_to_testflight call. It also asks for the right team now every time.

**Comment by alvindutt** [comment]
I am also facing this issue when using `AppStoreRelease@1` Task on AzureDevOps

error below 
`Run `fastlane env` to append the fastlane environment to your issue
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.221.1/spaceship/lib/spaceship/connect_api/api_client.rb:223:in `handle_response': [!] The specified resource does not exist - There is no resource of type 'apps' with id '$(app-specific-id)' (Spaceship::UnexpectedResponse)
`

Howver despite the error, the Release Task does upload the package to App Store

**Comment by ir-fuel** [comment]
This issue is still valid today in v2.222.0

**Comment by ir-fuel** [comment]
I still get this error without changelog in my fastfile, however the upload actually worked.
Tested on version 2.225.0
