### ISSUE TITLE
No such file or directory @ rb_sysopen .../.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rdoc/generator/template/darkfish/js/search.js

### ISSUE THREAD

**Issue by KBSchmidt** [fastlane/fastlane#21356]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We're building in CI ( Bitrise ) 

When the Fastlane step starts, it fails pretty quick with the following: 

```
[12:42:49]: --- Step: update_fastlane ---
[12:42:49]: -----------------------------
[12:42:49]: Looking for updates for fastlane...
[12:42:56]: Updating fastlane from 2.212.1 to 2.213.0... 🚀


[12:42:59]: Error accessing file, this might be due to fastlane's directory handling
[12:42:59]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details
bundler: failed to load command: fastlane (/Users/Vagrant/.asdf/installs/ruby/3.0.0/bin/fastlane)


/Users/vagrant/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/fileutils.rb:1414:in `initialize': No such file or directory @ rb_sysopen - /Users/vagrant/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rdoc/generator/template/darkfish/js/darkfish.js (Errno::ENOENT)
	from /Users/vagrant/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/fileutils.rb:1414:in `open'
```

Now where do I start investigating? 

-  Looks like bitrise uses ASDF to handle runtimes for ruby at least. Is it possible, that that their version skips  rdoc?
- Is it fastlanes directory handling fault? 

I'm at a loss here, and google wasn't helping either. Any thoughts?

##### Command executed

Update fastlane
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.6.3                                      |
| Ruby                        | 3.2.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.37.1 (Apple Git-137.1)        |
| Installation Source         | ~/.rbenv/versions/3.2.2/bin/fastlane        |
| Host                        | macOS 12.6.3 (21G419)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/3.2.2/lib                 |
| OpenSSL Version             | OpenSSL 3.1.0 14 Mar 2023                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.2                                        |
| Swift Version               | 5.7.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files: <dont want to share>

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.213.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-rename_android_package | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-load_json              | 0.0.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android     | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-firebase_management    | 1.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-appicon                | 0.16.0  | ✅ Up-To-Date  |
| fastlane-plugin-badge                  | 1.5.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| error_highlight                        | 0.5.1        |
| did_you_mean                           | 1.6.3        |
| syntax_suggest                         | 1.0.2        |
| atomos                                 | 0.1.3        |
| rexml                                  | 3.2.5        |
| CFPropertyList                         | 3.0.6        |
| claide                                 | 1.1.0        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.3.0        |
| xcodeproj                              | 1.22.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.8.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.7.0        |
| word_wrap                              | 1.0.0        |
| optparse                               | 0.1.1        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| artifactory                            | 3.0.15       |
| babosa                                 | 1.0.4        |
| colored                                | 1.2          |
| highline                               | 2.0.3        |
| commander                              | 4.6.0        |
| faraday-em_http                        | 1.0.0        |
| faraday-em_synchrony                   | 1.0.0        |
| faraday-excon                          | 1.1.0        |
| faraday-httpclient                     | 1.0.1        |
| faraday-multipart                      | 1.0.4        |
| faraday-net_http                       | 1.0.1        |
| faraday-net_http_persistent            | 1.2.0        |
| faraday-patron                         | 1.0.0        |
| faraday-rack                           | 1.0.0        |
| faraday-retry                          | 1.0.3        |
| ruby2_keywords                         | 0.0.5        |
| faraday                                | 1.10.3       |
| unf_ext                                | 0.0.8.2      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.5        |
| faraday-cookie_jar                     | 0.0.7        |
| faraday_middleware                     | 1.2.0        |
| gh_inspector                           | 1.1.3        |
| json                                   | 2.6.3        |
| mini_magick                            | 4.12.0       |
| naturally                              | 2.2.1        |
| rubyzip                                | 2.3.2        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.1        |
| dotenv                                 | 2.8.1        |
| simctl                                 | 1.6.10       |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.20       |
| trailblazer-option                     | 0.1.2        |
| representable                          | 3.2.0        |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.1.2        |
| httpclient                             | 2.8.3        |
| webrick                                | 1.8.1        |
| google-apis-core                       | 0.11.0       |
| google-apis-playcustomapp_v1           | 0.13.0       |
| google-cloud-env                       | 1.6.0        |
| google-cloud-errors                    | 1.3.1        |
| google-cloud-core                      | 1.6.0        |
| google-apis-iamcredentials_v1          | 0.17.0       |
| google-apis-storage_v1                 | 0.19.0       |
| rake                                   | 13.0.6       |
| digest-crc                             | 0.6.4        |
| google-cloud-storage                   | 1.44.0       |
| emoji_regex                            | 3.2.3        |
| set                                    | 1.0.3        |
| public_suffix                          | 5.0.1        |
| addressable                            | 2.8.4        |
| multipart-post                         | 2.3.0        |
| excon                                  | 0.100.0      |
| fastimage                              | 2.2.7        |
| bundler                                | 2.4.10       |
| jwt                                    | 2.7.1        |
| multi_json                             | 1.15.0       |
| signet                                 | 0.17.0       |
| os                                     | 1.1.4        |
| memoist                                | 0.16.2       |
| googleauth                             | 1.6.0        |
| google-apis-androidpublisher_v3        | 0.44.0       |
| aws-eventstream                        | 1.2.0        |
| aws-sigv4                              | 1.5.2        |
| aws-partitions                         | 1.781.0      |
| jmespath                               | 1.6.2        |
| aws-sdk-core                           | 3.175.0      |
| aws-sdk-kms                            | 1.67.0       |
| aws-sdk-s3                             | 1.126.0      |
| forwardable                            | 1.3.3        |
| logger                                 | 1.5.3        |
| pathname                               | 0.2.1        |
| shellwords                             | 0.1.0        |
| cgi                                    | 0.3.6        |
| date                                   | 3.3.3        |
| timeout                                | 0.3.1        |
| securerandom                           | 0.2.2        |
| uri                                    | 0.12.1       |
| openssl                                | 3.1.0        |
| digest                                 | 3.1.1        |
| ipaddr                                 | 1.2.5        |
| resolv                                 | 0.2.2        |
| time                                   | 0.2.2        |
| stringio                               | 3.0.4        |
| open-uri                               | 0.3.0        |
| mutex_m                                | 0.1.2        |
| net-http                               | 0.3.2        |
| net-protocol                           | 0.2.1        |
| ostruct                                | 0.5.5        |
| english                                | 0.7.2        |
| erb                                    | 4.0.2        |
| abbrev                                 | 0.1.1        |
| tempfile                               | 0.1.3        |
| delegate                               | 0.3.0        |
| fileutils                              | 1.7.0        |
| tmpdir                                 | 0.1.3        |
| base64                                 | 0.1.1        |
| singleton                              | 0.1.1        |
| open3                                  | 0.1.2        |
| nkf                                    | 0.1.2        |
| prettyprint                            | 0.1.1        |
| pp                                     | 0.4.0        |
| find                                   | 0.1.1        |
| yaml                                   | 0.2.1        |
| psych                                  | 5.0.1        |
| fastlane-plugin-rename_android_package | 0.1.0        |
| fastlane-plugin-load_json              | 0.0.1        |
| fastlane-plugin-versioning_android     | 0.1.1        |
| multi_xml                              | 0.6.0        |
| httparty                               | 0.21.0       |
| fastlane-plugin-firebase_management    | 1.1.0        |
| bigdecimal                             | 3.1.3        |
| csv                                    | 3.2.6        |
| pstore                                 | 0.1.2        |
| fastlane-plugin-appicon                | 0.16.0       |
| benchmark                              | 0.2.1        |
| badge                                  | 0.13.0       |
| fastlane-plugin-badge                  | 1.5.0        |
</details>

*generated on:* **2023-06-23**
</details></pre>
</details>

**Comment by ssilverr** [comment]
It looks to be a file access error as fastlane has stated. We commented the `update fastlane` out from the Fastfiles, and now it works correctly. 

Not sure who should look into this issue:
- fastlane to support .asdf runtime tool
- Bitrise
- asdf tool to support Fastlane
