### ISSUE TITLE
net_http is not registered on Faraday::Adapter

### ISSUE THREAD

**Issue by httpdss** [fastlane/fastlane#21395]
Im having some trouble using the slack plugin

if i run: `fastlane run slack`

this error shows up 

```
/var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/middleware_registry.rb:91:in `lookup_middleware': \e[31m[!] :net_http is not registered on Faraday::Adapter\e[0m (Faraday::Error)
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:114:in `adapter'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:77:in `build'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:65:in `initialize'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/options/connection_options.rb:19:in `new'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/options/connection_options.rb:19:in `new_builder'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/connection.rb:83:in `initialize'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday.rb:120:in `new'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday.rb:120:in `new'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/notification/slack.rb:6:in `initialize'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/slack.rb:11:in `new'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/slack.rb:11:in `initialize'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/slack.rb:173:in `new'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/slack.rb:173:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:25:in `load'
        from /usr/local/bin/fastlane:25:in `<main>'
/var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/middleware_registry.rb:91:in `lookup_middleware': :net_http is not registered on Faraday::Adapter (Faraday::Error)
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:114:in `adapter'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:77:in `build'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:65:in `initialize'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/options/connection_options.rb:19:in `new'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/options/connection_options.rb:19:in `new_builder'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday/connection.rb:83:in `initialize'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday.rb:120:in `new'
        from /var/lib/gems/3.0.0/gems/faraday-1.10.3/lib/faraday.rb:120:in `new'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/notification/slack.rb:6:in `initialize'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/slack.rb:11:in `new'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/slack.rb:11:in `initialize'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/slack.rb:173:in `new'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/slack.rb:173:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /var/lib/gems/3.0.0/gems/fastlane-2.213.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:25:in `load'
        from /usr/local/bin/fastlane:25:in `<main>'
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                            |
| --------------------------- | -------------------------------------------------------------------------------- |
| OS                          | debian_based bookworm/sid                                                        |
| Ruby                        | 3.0.2                                                                            |
| Bundler?                    | false                                                                            |
| Git                         | git version 2.34.1                                                               |
| Installation Source         | /usr/local/bin/fastlane                                                          |
| Host                        | Ubuntu 22.04.1 LTS debian_based bookworm/sid (5.15.90.1-microsoft-standard-WSL2) |
| Ruby Lib Dir                | /usr/lib                                                                         |
| OpenSSL Version             | OpenSSL 3.0.2 15 Mar 2022                                                        |
| Is contained                | false                                                                            |
| Is homebrew                 | false                                                                            |
| Is installed via Fabric.app | false                                                                            |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane


default_platform(:android)

platform :android do

  

  desc "Create a new build, increment version and deploy artifact"
  lane :deploy do

    slack(
        message: "starting build to AWS Code Artifact.",
        slack_url: ENV['SLACK_URL']
    )

  end

end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.xxxx.yyy") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.213.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.7.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.100.0      |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.7        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.6.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.45.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.786.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.6.0        |
| aws-sdk-core                    | 3.178.0      |
| aws-sdk-kms                     | 1.71.0       |
| aws-sdk-s3                      | 1.130.0      |
| set                             | 1.0.1        |
| public_suffix                   | 5.0.3        |
| addressable                     | 2.8.4        |
| multipart-post                  | 2.3.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| json                            | 2.6.3        |
| bundler                         | 2.3.5        |
| rake                            | 13.0.6       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| openssl                         | 3.0.0        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| net-http-persistent             | 2.9.4        |
| net-http                        | 0.1.1        |
| net-http-pipeline               | 1.0.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| etc                             | 1.2.0        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2023-07-13**
</details>

**Comment by Bear433** [comment]
Thanks for sharing this.

**Comment by Robertopera** [comment]
The error message you're encountering suggests that there is an issue with the Faraday gem's middleware registration when using the Slack plugin in Fastlane. Specifically, it's complaining that the :net_http adapter is not registered on Faraday::Adapter.

Here are some steps you can take to troubleshoot and resolve this issue:

Check Gem Versions: Ensure that you are using compatible versions of Fastlane, Faraday, and any other dependencies. Outdated or incompatible gem versions can sometimes cause issues.

Update Gems: Update your gems to the latest versions by running the following commands:

gem update fastlane
gem update faraday

Check Fastlane Configuration: Verify your Fastlane configuration and ensure that you have specified the correct Slack API token and other required parameters in your Fastfile.

Check Environment: Make sure that you are running Fastlane in the correct environment. Sometimes, gem conflicts can occur when using different versions of Ruby or gemsets.

Check Plugins: If you are using any custom plugins or have made modifications to the Fastlane configuration, ensure that they are correctly configured and not causing conflicts.

Reinstall Dependencies: In some cases, removing and reinstalling the required gems can help resolve conflicts. You can uninstall and reinstall Fastlane and Faraday using the following commands:

gem uninstall fastlane
gem uninstall faraday
gem install fastlane
gem install faraday

Ruby Version Manager (RVM) or rbenv: If you are using a Ruby version manager like RVM or rbenv, make sure that your Ruby version and gemset are correctly configured for your project.

Environment Variables: Ensure that any required environment variables, such as Slack API tokens, are set correctly.

Debugging: You can enable verbose debugging output for Fastlane by adding --verbose to your Fastlane command. This might provide more information about what's going wrong.

If none of the above steps [MyMileStoneCard](https://www.mymilestonecard.biz/) resolve the issue, you may want to check the Fastlane and Faraday GitHub repositories or forums for any known issues related to Slack integration or middleware registration. Additionally, if you're using a custom plugin, review its documentation and any reported issues.

Keep in mind that gem and library versions can change over time, so it's possible that updates or changes in dependencies have introduced this issue, and it may require waiting for an update or finding a workaround.
