### ISSUE TITLE
/usr/local/lib/ruby/2.7.0/fileutils.rb:139:in `chdir': No such file or directory @ dir_chdir -  (Errno::ENOENT)

### ISSUE THREAD

**Issue by omar-chaabouni** [fastlane/fastlane#21446]
### New Issue Checklist

- [*] Updated fastlane to the latest version
- [*] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [*] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [*] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I got this issue 
```
|               Lane Context               |
+---------------+--------------------------+
| PLATFORM_NAME | ios                      |
| LANE_NAME     | ios release_to_app_store |
+---------------+--------------------------+
[19:04:26]: No such file or directory @ dir_chdir - 
+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | app_store_connect_api_key | 0           |
| 💥   | deliver                   | 1           |
+------+---------------------------+-------------+
[19:04:26]: fastlane finished with errors
[19:04:26]: Error accessing file, this might be due to fastlane's directory handling
[19:04:26]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details
**/usr/local/lib/ruby/2.7.0/fileutils.rb:139:in `chdir': No such file or directory @ dir_chdir -  (Errno::ENOENT)**
	from /usr/local/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:649:in `execute'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:791:in `upload'
	from /usr/local/bundle/gems/fastlane-2.214.0/deliver/lib/deliver/runner.rb:219:in `upload_binary'
	from /usr/local/bundle/gems/fastlane-2.214.0/deliver/lib/deliver/runner.rb:65:in `run'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:53:in `block (2 levels) in parsing_binding'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/bundle/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/bundle/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/bundle/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/bundle/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/bundle/gems/fastlane-2.214.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/bundle/gems/fastlane-2.214.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bundle/bin/fastlane:23:in `load'
	from /usr/local/bundle/bin/fastlane:23:in `<main>'

```

##### Command executed

fastlane ios release_to_app_store

this is my code :
            - gem install fastlane 
            - export LC_ALL=fr_FR.UTF-8
            - export LANG=fr_FR.UTF-8
            - fastlane ios release_to_app_store
I am using ruby 2.7 docker image on bibtbucket pipelines
ruby version : ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]          

**Fastfile**:
```
app_store_connect_api_key(
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      key_content: ENV['APP_STORE_FASTLANE_API_AUTH_KEY_BASE64'],
      is_key_content_base64: true
    )
    
    deliver(
      app_identifier: app_identifier,
      username: apple_id,
      force: true,
      app_version: "0.2.24",
      ipa: ipa_path,
      submit_for_review: true,
      force: true,
      skip_metadata: true,
      skip_screenshots: true
    )
```

### Environment

ruby version : ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]

**Comment by omar-chaabouni** [comment]
Please help :(

**Comment by Stephens64a** [comment]
Ohh!! I'm also looking for the same... Someone please help.

**Comment by omar-chaabouni** [comment]
@Stephens64a you got a solution

**Comment by sangiraldo** [comment]
I have the same problem, please help

**Comment by omar-chaabouni** [comment]
I finally quit and decided to used codemagic

**Comment by moisesgaspar22** [comment]
Bump!!
having the same issue here, was there any developments on this?

**Comment by avoloshko** [comment]
the same problem occurred on

Ubuntu 22.0 LTS
gem "fastlane", '~> 2.217.0'

**Comment by Serveladik** [comment]
Same issue
Dfq is it always so much issues related to Apple Comany???

**Comment by iBotPeaches** [comment]
Sorry we never got to this in-time. We don't support Ruby 2.7 anymore and none of the confirmations here with a more modern Ruby version have a stacktrace to confirm.

I'll close this out as trying to clean up backlog.
