### ISSUE TITLE
iOS Tests using destination parameter crashes the tool (scan/runner.rb:50 undefined method 'each')

### ISSUE THREAD

**Issue by mikehouse** [fastlane/fastlane#21455]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hello.  I want to run iOS UITests for different OS version (iOS 15, iOS 16, iOS 17, etc.). I have installed all needed runtimes for Xcode 14.3 (iOS 15.5 and iOS 16.4 runtimes). Found all the needed iOS Simulators (UUIDs) which want to use for tests.

Then I run the tests agains iOS Simulator with iOS 15.5 like this

```ruby
run_tests(
  scheme: "MyUITests",
  destination: "platform=iOS Simulator,id=72D088E1-E457-43F3-A481-8420294E4600",
  skip_detect_devices: true
)
```

and I'm getting a crash like this:

```bash
fastlane-2.214.0/scan/lib/scan/runner.rb:50:in `test_app': \e[31m[!] undefined method `each' for nil:NilClass (NoMethodError)
```

Seems it tries to find a Simulator for some reasons, though `skip_detect_devices ` is set to `true`. To bypass this I set a random iOS Simulator like:

```ruby
run_tests(
  scheme: "MyUITests",
  devices: ["iPhone 14 Pro Max"], # iOS 16.4, id=78A24655-3E06-49CD-A1F3-A9CF39351252
  destination: "platform=iOS Simulator,id=72D088E1-E457-43F3-A481-8420294E4600",
  skip_detect_devices: true
)
```

The tests started to run on given `destination` Simulator, but some actions also done for "iPhone 14 Pro Max", but not with the `destination` Simulator, for example:

```bash
[00:10:48]: Resetting iPhone 14 Pro Max
[00:10:48]: Launch Simulator iPhone 14 Pro Max
[00:10:48]: $ open -a Simulator.app --args -CurrentDeviceUDID 78A24655-3E06-49CD-A1F3-A9CF39351252 &> /dev/null
[00:10:48]: Uninstall application com.myapp.id
[00:10:48]: $ xcrun simctl uninstall 78A24655-3E06-49CD-A1F3-A9CF39351252 com.myapp.id &> /dev/null
[00:10:48]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./MyProject.xcworkspace -scheme MyUITests  -destination 'platform=iOS Simulator,id=72D088E1-E457-43F3-A481-8420294E4600' ... clean build test | tee ...
```

As we can see the `uninstall ` action is done for wrong Simulator.

Thank you.

##### Complete output when running fastlane, including the stack trace and command used

<details>

```bash
/Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/scan/lib/scan/runner.rb:50:in `test_app': \e[31m[!] undefined method `each' for nil:NilClass (NoMethodError)

        Scan.devices.each do |device|
                    ^^^^^\e[0m
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/scan/lib/scan/runner.rb:24:in `run'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/scan/lib/scan/manager.rb:23:in `work'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/run_tests.rb:17:in `run'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:349:in `block (3 levels) in parsing_binding'
	from Fastfile:337:in `each'
	from Fastfile:337:in `block (2 levels) in parsing_binding'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/bin/fastlane:23:in `<top (required)>'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `load'
	from /Users/mikhaildemidov/Development/ios/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/bin/bundle:25:in `load'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/bin/bundle:25:in `<main>'
```

</details>

### Environment

<details>

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 13.5                                                       |
| Ruby                        | 3.1.3                                                      |
| Bundler?                    | true                                                       |
| Git                         | git version 2.39.2 (Apple Git-143)                         |
| Installation Source         | ~/Development/ios/vendor/bundle/ruby/3.1.0/bin/fastlane |
| Host                        | macOS 13.5 (22G74)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib                  |
| OpenSSL Version             | OpenSSL 3.0.7 1 Nov 2022                                   |
| Is contained                | false                                                      |
| Is homebrew                 | false                                                      |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.3                                                       |
| Swift Version               | 5.8                                                        |

</details>

**Comment by mikehouse** [comment]
Anybody ?

**Comment by stherold** [comment]
Same on my side

**Comment by houtzager** [comment]
We've been having the same problem in combination with [this issue](https://github.com/fastlane/fastlane/issues/22233).

We worked around it by turning off the reinstall_app option, and manually providing fresh simulators using `xcrun simctl` and the fastlane destination parameter. 

Looking at the crashlog, you can see the crash occurs on [line 50](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/runner.rb#L50), which is guarded by this reinstall_app configuration.
