### ISSUE TITLE
Fastlane pick the wrong ruby version

### ISSUE THREAD

**Issue by SeptatrivantoWandy** [fastlane/fastlane#21485]
### Discussed in https://github.com/fastlane/fastlane/discussions/21484

<div type='discussions-op-text'>

<sup>Originally posted by **SeptatrivantoWandy** August 25, 2023</sup>
Unable to use fastlane android codepush and resulting this error. Expected using ruby 2.7.4 because I already set ruby path installed with rbenv but fastlane use ruby system instead which version 2.6.0

```
/Library/Ruby/Site/2.6.0/rubygems/specification.rb:1466:in `rescue in block in activate_dependencies': Could not find 'xcodeproj' (>= 1.13.0, < 2.0.0) among 140 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/myusername/.gem/ruby/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0:/Users/myusername/.gem' at: /Users/myusername/.gem/specifications/fastlane-2.214.0.gemspec, execute `gem env` for more information
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1463:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1452:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1452:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1434:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:285:in `block in activate_bin_path'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:284:in `synchronize'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:284:in `activate_bin_path'
	from /usr/local/bin/fastlane:23:in `<main>'
/Library/Ruby/Site/2.6.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'xcodeproj' (>= 1.13.0, < 2.0.0) among 140 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/myusername/.gem/ruby/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0:/Users/myusername/.gem' , execute `gem env` for more information
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1464:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1452:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1452:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1434:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:285:in `block in activate_bin_path'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:284:in `synchronize'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:284:in `activate_bin_path'
	from /usr/local/bin/fastlane:23:in `<main>'
```

Macos version
13.5 (22G74)

fastlane installed version
fastlane 2.214.0

which fastlane
```
/usr/local/bin/fastlane
```

ruby --version
```
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [arm64-darwin22]
```

which --ruby
```
/Users/myusername/.rbenv/shims/ruby
```

gem --version
```
3.1.6
```

which gem
```
/Users/myusername/.rbenv/shims/gem
```

gem env
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.6
  - RUBY VERSION: 2.7.4 (2021-07-07 patchlevel 191) [arm64-darwin22]
  - INSTALLATION DIRECTORY: /Users/myusername/.gem
  - USER INSTALLATION DIRECTORY: /Users/myusername/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/myusername/.rbenv/versions/2.7.4/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /Users/myusername/.gem/bin
  - SPEC CACHE DIRECTORY: /Users/myusername/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/myusername/.rbenv/versions/2.7.4/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - arm64-darwin-22
  - GEM PATHS:
     - /Users/myusername/.gem
     - /Users/myusername/.gem/ruby/2.7.0
     - /Users/myusername/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/myusername/.rbenv/versions/2.7.4/bin
     - /opt/homebrew/Cellar/rbenv/1.2.0/libexec
     - /Library/Java/JavaVirtualMachines/jdk-11.0.16.1.jdk/Contents/Home/bin
     - /Users/myusername/.rbenv/shims
     - /Users/myusername/.rbenv/bin
     - /usr/local/bin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /usr/local/bin
     - /Library/Java/JavaVirtualMachines/jdk-11.0.16.1.jdk/Contents/Home/bin
     - /Users/myusername/.rbenv/shims
     - /Users/myusername/.rbenv/bin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /usr/local/bin
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
     - /Users/myusername/Library/Android/sdk/emulator
     - /Users/myusername/Library/Android/sdk/tools
     - /Users/myusername/Library/Android/sdk/tools/bin
     - /Users/myusername/Library/Android/sdk/platform-tools
     - /Applications/Visual Studio Code.app/Contents/Resources/app/bin
     - /Users/myusername/Documents/FlutterDeveloper/flutter/bin
     - /Users/myusername/Library/Android/sdk/emulator
     - /Users/myusername/Library/Android/sdk/tools
     - /Users/myusername/Library/Android/sdk/tools/bin
     - /Users/myusername/Library/Android/sdk/platform-tools
     - /Applications/Visual Studio Code.app/Contents/Resources/app/bin
     - /Users/myusername/Documents/FlutterDeveloper/flutter/bin
```

fastlane installed with bundle install
bundler --version
```
Bundler version 2.4.19
```

which bundler
```
/Users/myusername/.rbenv/shims/bundler
```

env path .zshrc
```
export PATH=/usr/local/bin:$PATH
eval $(/opt/homebrew/bin/brew shellenv)
export PATH=/usr/local/bin:$PATH
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
GEM_PATH=/Users/myusername/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.0.16.1.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
export GEM_HOME="$HOME/.gem"
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="$PATH:/Users/myusername/Documents/FlutterDeveloper/flutter/bin"
```

env path .bashrc
```
$(HOME)/.npm-packages

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
GEM_PATH=/Users/myusername/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0
eval "$(rbenv init -)"
```

Any solution to force fastlane use specific ruby version?</div>

**Comment by Tchaikovsky1114** [comment]
I having same issue with ruby 3.3.0
