### ISSUE TITLE
Android: `track_version_codes': \e[31m[!] undefined method `flat_map' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by trinitiwowka** [fastlane/fastlane#21500]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
      betaVersionCodes = get_google_play_track_version_codes(package_name: package_name, track: 'beta', json_key: json_key_file)

##### Complete output when running fastlane, including the stack trace and command used
/Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/supply/lib/supply/client.rb:444:in `track_version_codes': \e[31m[!] undefined method `flat_map' for nil:NilClass (NoMethodError)

        return result.releases.flat_map(&:version_codes) || []
                              ^^^^^^^^^\e[0m
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/supply/lib/supply/reader.rb:7:in `track_version_codes'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/google_play_track_version_codes.rb:26:in `run'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:195:in `block (2 levels) in parsing_binding'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:214:in `latest_googleplay_version_code'
	from Fastfile:232:in `block (2 levels) in parsing_binding'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/ххх/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.213.0/bin/fastlane:23:in `<top (required)>'
	from /Users/ххх/.rbenv/versions/3.1.2/bin/fastlane:25:in `load'
	from /Users/ххх/.rbenv/versions/3.1.2/bin/fastlane:25:in `<main>'

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment
`

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 13.2                                        |
| Ruby                        | 3.1.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.2 (Apple Git-143)          |
| Installation Source         | ~/.rbenv/versions/3.1.2/bin/fastlane        |
| Host                        | macOS 13.2 (22D49)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.2/lib                 |
| OpenSSL Version             | OpenSSL 3.1.0 14 Mar 2023                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.3                                        |
| Swift Version               | 5.8                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.213.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-increment_version_name | 0.0.10  | ✅ Up-To-Date  |
| fastlane-plugin-load_json              | 0.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| error_highlight                        | 0.3.0        |
| did_you_mean                           | 1.6.1        |
| atomos                                 | 0.1.3        |
| rexml                                  | 3.2.5        |
| CFPropertyList                         | 3.0.6        |
| claide                                 | 1.1.0        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.3.0        |
| xcodeproj                              | 1.22.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.8.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.7.0        |
| addressable                            | 2.8.4        |
| word_wrap                              | 1.0.0        |
| optparse                               | 0.1.1        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| artifactory                            | 3.0.15       |
| babosa                                 | 1.0.4        |
| colored                                | 1.2          |
| highline                               | 2.0.3        |
| commander                              | 4.6.0        |
| faraday-em_http                        | 1.0.0        |
| faraday-em_synchrony                   | 1.0.0        |
| faraday-excon                          | 1.1.0        |
| faraday-httpclient                     | 1.0.1        |
| faraday-multipart                      | 1.0.4        |
| faraday-net_http                       | 1.0.1        |
| faraday-net_http_persistent            | 1.2.0        |
| faraday-patron                         | 1.0.0        |
| faraday-rack                           | 1.0.0        |
| faraday-retry                          | 1.0.3        |
| ruby2_keywords                         | 0.0.5        |
| faraday                                | 1.10.3       |
| unf_ext                                | 0.0.8.2      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.5        |
| faraday-cookie_jar                     | 0.0.7        |
| faraday_middleware                     | 1.2.0        |
| gh_inspector                           | 1.1.3        |
| mini_magick                            | 4.12.0       |
| naturally                              | 2.2.1        |
| rubyzip                                | 2.3.2        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.1        |
| dotenv                                 | 2.8.1        |
| simctl                                 | 1.6.10       |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.20       |
| trailblazer-option                     | 0.1.2        |
| representable                          | 3.2.0        |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.1.2        |
| memoist                                | 0.16.2       |
| multi_json                             | 1.15.0       |
| os                                     | 1.1.4        |
| signet                                 | 0.17.0       |
| googleauth                             | 1.5.2        |
| httpclient                             | 2.8.3        |
| webrick                                | 1.8.1        |
| google-apis-core                       | 0.11.0       |
| google-apis-playcustomapp_v1           | 0.13.0       |
| google-cloud-env                       | 1.6.0        |
| google-cloud-errors                    | 1.3.1        |
| google-cloud-core                      | 1.6.0        |
| google-apis-iamcredentials_v1          | 0.17.0       |
| google-apis-storage_v1                 | 0.19.0       |
| rake                                   | 13.0.6       |
| digest-crc                             | 0.6.4        |
| google-cloud-storage                   | 1.44.0       |
| emoji_regex                            | 3.2.3        |
| set                                    | 1.0.2        |
| public_suffix                          | 5.0.1        |
| multipart-post                         | 2.3.0        |
| excon                                  | 0.100.0      |
| fastimage                              | 2.2.7        |
| json                                   | 2.6.3        |
| bundler                                | 2.4.18       |
| jwt                                    | 2.7.1        |
| google-apis-androidpublisher_v3        | 0.44.0       |
| aws-eventstream                        | 1.2.0        |
| aws-sigv4                              | 1.5.2        |
| aws-partitions                         | 1.781.0      |
| jmespath                               | 1.6.2        |
| aws-sdk-core                           | 3.175.0      |
| aws-sdk-kms                            | 1.67.0       |
| aws-sdk-s3                             | 1.126.0      |
| forwardable                            | 1.3.2        |
| logger                                 | 1.5.0        |
| pathname                               | 0.2.0        |
| shellwords                             | 0.1.0        |
| cgi                                    | 0.3.1        |
| date                                   | 3.2.2        |
| timeout                                | 0.2.0        |
| stringio                               | 3.0.1        |
| securerandom                           | 0.1.1        |
| uri                                    | 0.11.0       |
| openssl                                | 3.0.0        |
| digest                                 | 3.1.0        |
| io-nonblock                            | 0.1.0        |
| ipaddr                                 | 1.2.4        |
| io-wait                                | 0.2.1        |
| zlib                                   | 2.1.1        |
| resolv                                 | 0.2.1        |
| time                                   | 0.2.0        |
| open-uri                               | 0.2.0        |
| mutex_m                                | 0.1.1        |
| net-protocol                           | 0.1.2        |
| net-http                               | 0.2.0        |
| ostruct                                | 0.5.2        |
| english                                | 0.7.1        |
| erb                                    | 2.2.3        |
| strscan                                | 3.0.1        |
| abbrev                                 | 0.1.0        |
| io-console                             | 0.5.11       |
| tempfile                               | 0.1.2        |
| delegate                               | 0.2.0        |
| fileutils                              | 1.6.0        |
| tmpdir                                 | 0.1.2        |
| base64                                 | 0.1.1        |
| singleton                              | 0.1.1        |
| open3                                  | 0.1.1        |
| nkf                                    | 0.1.1        |
| prettyprint                            | 0.1.1        |
| pp                                     | 0.3.0        |
| find                                   | 0.1.1        |
| yaml                                   | 0.2.0        |
| psych                                  | 4.0.3        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-increment_version_name | 0.0.10       |
| fastlane-plugin-load_json              | 0.0.1        |
</details>

`

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by trinitiwowka** [comment]
Constant problems with this code to determine the version.
If such a "track" is not created, then an error appeared.

I found solution with this code, and it worked:

`
    lane :get_google_play_track_version_codes do |options|
      track_version_codes = [0]
      begin
        track_version_codes = google_play_track_version_codes(
          package_name: options[:package_name],
          track: options[:track],
          json_key: options[:json_key],
        )
      rescue => gptvcError
        if (gptvcError.class != Google::Apis::ClientError || gptvcError.status_code != 404)
          raise gptvcError
        end
      end
      track_version_codes
    end
`


But now the error is completely different. and it is reproduced in both 2.213.0 and 2.214.0

**Comment by StanislavARA** [comment]
this worked for me:

lane :get_google_play_track_version_codes do |options|
      track_version_codes = []
      track_version_codes
end

**Comment by trinitiwowka** [comment]
> 

But my solution worked perfectly for almost a year. and a couple broke in all my projects a few days ago.

**Comment by trinitiwowka** [comment]
I found solution. In this line https://github.com/fastlane/fastlane/blob/871eb67c0f4202cc017948034bffa96c6aca21d7/supply/lib/supply/client.rb#L477
just add 

```
        releases = result.releases
        return [] unless releases
        return releases.flat_map(&:version_codes) || []
```

**Comment by ivan901229** [comment]
I'm encountering the same issue as well and currently using a begin-rescue-end block to handle errors

**Comment by trinitiwowka** [comment]
> I'm encountering the same issue as well and currently using a begin-rescue-end block to handle error.

can you show example please?

**Comment by ivan901229** [comment]
My code closely resembles yours.
```
    ## Initialize the latest_internal_build_number with a default value of 0
    latest_internal_build_number = 0
    ## Attempt to fetch the internal test build numbers. If target track is not created, then an error appeared.
    begin
      latest_internal_build_numbers = google_play_track_version_codes(
        package_name: ENV['BUNDLE_ID'],
        track: "internal"
      )
      # Update the latest version number if successfully retrieved
      latest_internal_build_number = latest_internal_build_numbers.max unless latest_internal_build_numbers.empty?
    rescue StandardError => e
      puts "An error occurred: #{e.message} while fetching the latest internal build number"
    end
    options[:latest_internal_build_number] = latest_internal_build_number.to_s
```

**Comment by burak-pensa** [comment]
Hey guys, any progress on this?

**Comment by burak-pensa** [comment]
@trinitiwowka I saw another [PR](https://github.com/fastlane/fastlane/pull/21506) almost related to this one, still awaiting review. The best possible solution for now is to try catching a StandardError as @ivan901229 mentioned and continue.

```
def self.latest_build_number
	tracks = ["internal", "alpha", "beta", "production"]
	version_codes = []
	tracks.each do |track|
		begin
			vc =  google_play_track_version_codes(track: track)
		rescue 
			puts  "No track found for " + track
		else
			version_codes.concat(vc)
		end
	end
	version_codes.max
end
```

**Comment by danielesegato** [comment]
Hi I have this problem and it happens when the track version is configured like this:
<img width="638" alt="Screenshot 2023-10-12 at 10 23 22" src="https://github.com/fastlane/fastlane/assets/469948/7ac60d7f-9fb2-401f-9922-9204891ead18">

When requesting beta in this situation you get the error above.

**Comment by shawnlauzon** [comment]
I'm running into this problem as well. Looks like the process is stuck waiting for a test case from @danielesegato. Any way you could create a quick test so that they fix can get integrated?

**Comment by hpelitebook745G2** [comment]
I'm running into this issue as well, the code:
```
  previous_build_number = google_play_track_version_codes(track: "internal")[0]
  current_build_number = previous_build_number + 1
```
has been running for months and suddenly gave error:
```
Fastfile:18:in `block (2 levels) in parsing_binding': [!] undefined method `+' for nil:NilClass (NoMethodError)
```

**Comment by RomanTheLegend** [comment]
I've noticed that in my case the problem was that `Production` track didn't exist on Play Store because this was Draft app, so explicitly providing `track:internal` fixed the problem.

The error is very misleading - it should simply say "Track not found"

**Comment by iBotPeaches** [comment]
This was fixed in https://github.com/fastlane/fastlane/commit/d62e590db93f5515e5b4f298ccdeb9c5b4a00562  &   https://github.com/fastlane/fastlane/commit/ca73fac764922f1c72da5276f47035f4d06920fe

Sorry for delay.
