### ISSUE TITLE
The URL path is not valid - '/v1/apps/' is not a valid URL

### ISSUE THREAD

**Issue by dominikszocikpzpn** [fastlane/fastlane#21524]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Basically there is an error when you have enabled waiting for build processing in appstore connect. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Spaceship::UnexpectedResponse: [!] The URL path is not valid - '/v1/apps/' is not a valid URL
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:222:in `handle_response'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:27:in `get_app'
16:31:08     /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get_app'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/models/app.rb:101:in `get'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/pilot/lib/pilot/manager.rb:45:in `app'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/pilot/lib/pilot/build_manager.rb:123:in `wait_for_build_processing_to_be_complete'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/pilot/lib/pilot/build_manager.rb:78:in `upload'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
16:31:08     Fastfile:146:in `block (2 levels) in parsing_binding'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane.rb:33:in `call'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/bin/fastlane:23:in `load'
16:31:08     /Users/mobiledev/Downloads/teamcity_agent/work/.gems/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
16:31:08   Process exited with code 1 </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by SergeyLaukhin** [comment]
I have the same issue
The URL path is not valid - '/v1/apps/' is not a valid URL
