### ISSUE TITLE
Undefined method "for_mode" when managing certificates manually

### ISSUE THREAD

**Issue by fknbwdwn** [fastlane/fastlane#21527]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [2.215.1](https://github.com/fastlane/fastlane/releases/tag/2.215.1)
- Last working version: [2.214.0](https://github.com/fastlane/fastlane/releases/tag/2.214.0)]

### Regression Description
For a long time I have been manually managing certificates for various customers based on the documentation here: https://docs.fastlane.tools/advanced/other/#manually-manage-the-fastlane-match-repo and it has been working extremely well until recently. After updating the Fastlane version on my build machine to v2.215.1 I am not getting an undefined method error, namely on this line:
`storage = Match::Storage.for_mode("git", { git_url: git_url, shallow_clone: shallow_clone, git_branch: branch, clone_branch_directly: false})`

I found that simply using match out of the box did not provide some logic/functionality I needed when managing my certificates so I wound up having to bake my own workflow and if possible I'd like to avoid having to rewrite this portion.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>lanes/certificate:18:in `block (2 levels) in parsing_binding': \e[31m[!] undefined method `for_mode' for Match::Storage:Module\e[0m (NoMethodError)
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from lanes/certificate:254:in `block (2 levels) in parsing_binding'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:36:in `block (2 levels) in parsing_binding'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.215.1/bin/fastlane:23:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
        from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/cli.rb:483:in `exec'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/cli.rb:25:in `start'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
        from /usr/local/opt/ruby/bin/bundle:23:in `load'
        from /usr/local/opt/ruby/bin/bundle:23:in `<main>'</pre>
</details>

For now I have simply downgraded back to v2.214.0 to restore functionality, but this is something that will block me from updating to later releases of Fastlane.

**Comment by Westacular** [comment]
Just encountered this as well.

Here's the breaking change: https://github.com/fastlane/fastlane/commit/6627c28c65e1c992d55899a3b4e83b5396e6e6e9#diff-015832d73266bf667895af7a8cd7dea1d215eb2f9165c0327a11c1f09bea4e82R92

if you update your code from

```ruby
storage = Match::Storage.for_mode("git", { git_url: git_url, shallow_clone: shallow_clone, git_branch: branch, clone_branch_directly: false})
```

to

```ruby
storage = Match::Storage.from_params({ storage_mode: "git", git_url: git_url, shallow_clone: shallow_clone, git_branch: branch, clone_branch_directly: false})
```

... things should work again, provided you're also using v2.215.0 or later when you make the change.
