### ISSUE TITLE
Fastlane supply init: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by MartenM** [fastlane/fastlane#21529]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am currently trying to setup Fastlane for a project of mine. I didn't get the windows version to work, so I decided to switch to WSL.
`fastlane init` seems to work fine. However `fastlane supply init` seems to throw an error. The result (I think) is that I am missing the changelogs.

##### Command executed

fastlane supply init

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane supply init
[✔] 🚀
[21:32:38]: 🕗  Downloading metadata, images, screenshots...
[21:32:40]: 📝  Downloading metadata (nl-NL)
[21:32:40]: Writing to fastlane/metadata/android/nl-NL/title.txt...
[21:32:40]: Writing to fastlane/metadata/android/nl-NL/short_description.txt...
[21:32:40]: Writing to fastlane/metadata/android/nl-NL/full_description.txt...
[21:32:40]: Writing to fastlane/metadata/android/nl-NL/video.txt...
[21:32:40]: 🖼️  Downloading images (nl-NL)
[21:32:40]: Downloading `featureGraphic` for nl-NL...
[21:32:41]:     Downloaded - fastlane/metadata/android/nl-NL/images/featureGraphic.png
[21:32:41]: Downloading `icon` for nl-NL...
[21:32:42]:     Downloaded - fastlane/metadata/android/nl-NL/images/icon.png
[21:32:42]: Downloading `tvBanner` for nl-NL...
[21:32:42]: Downloading `phoneScreenshots` for nl-NL...
[21:32:43]:     Downloaded - fastlane/metadata/android/nl-NL/images/phoneScreenshots/1_nl-NL.png
[21:32:43]:     Downloaded - fastlane/metadata/android/nl-NL/images/phoneScreenshots/2_nl-NL.png
[21:32:43]:     Downloaded - fastlane/metadata/android/nl-NL/images/phoneScreenshots/3_nl-NL.png
[21:32:44]:     Downloaded - fastlane/metadata/android/nl-NL/images/phoneScreenshots/4_nl-NL.png
[21:32:44]:     Downloaded - fastlane/metadata/android/nl-NL/images/phoneScreenshots/5_nl-NL.png
[21:32:44]:     Downloaded - fastlane/metadata/android/nl-NL/images/phoneScreenshots/6_nl-NL.png
[21:32:44]:     Downloaded - fastlane/metadata/android/nl-NL/images/phoneScreenshots/7_nl-NL.png
[21:32:45]:     Downloaded - fastlane/metadata/android/nl-NL/images/phoneScreenshots/8_nl-NL.png
[21:32:45]: Downloading `sevenInchScreenshots` for nl-NL...
[21:32:45]: Downloading `tenInchScreenshots` for nl-NL...
[21:32:45]: Downloading `tvScreenshots` for nl-NL...
[21:32:46]: Downloading `wearScreenshots` for nl-NL...

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `*' for nil:NilClass frameit
    https://github.com/fastlane/fastlane/issues/21496 [open] 3 💬
    3 days ago

➡️  Android: `track_version_codes': \e[31m[!] undefined method `flat_map' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/21500 [open] 9 💬
    4 days ago

➡️  [!] undefined method `resolved_build_setting' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/20435 [open] 6 💬
    28 Nov 2022

and 491 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60name%27%20for%20nil&type=Issues&utf8=✓

/var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/client.rb:303:in `block in latest_version': \e[31m[!] undefined method `name' for nil:NilClass\e[0m (NoMethodError)
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/client.rb:303:in `reject'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/client.rb:303:in `latest_version'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/setup.rb:19:in `perform_download'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/commands_generator.rb:55:in `block (2 levels) in run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/commands_generator.rb:61:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/commands_generator.rb:13:in `start'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:25:in `load'
        from /usr/local/bin/fastlane:25:in `<main>'
/var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/client.rb:303:in `block in latest_version': undefined method `name' for nil:NilClass (NoMethodError)    
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/client.rb:303:in `reject'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/client.rb:303:in `latest_version'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/setup.rb:19:in `perform_download'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/commands_generator.rb:55:in `block (2 levels) in run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /var/lib/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/commands_generator.rb:61:in `run'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/supply/lib/supply/commands_generator.rb:13:in `start'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /var/lib/gems/3.0.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:25:in `load'
        from /usr/local/bin/fastlane:25:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>
### Stack

| Key                         | Value                                                                            |
| --------------------------- | -------------------------------------------------------------------------------- |
| OS                          | debian_based bookworm/sid                                                        |
| Ruby                        | 3.0.2                                                                            |
| Bundler?                    | false                                                                            |
| Git                         | git version 2.34.1                                                               |
| Installation Source         | /usr/local/bin/fastlane                                                          |
| Host                        | Ubuntu 22.04.3 LTS debian_based bookworm/sid (5.10.16.3-microsoft-standard-WSL2) |
| Ruby Lib Dir                | /usr/lib                                                                         |
| OpenSSL Version             | OpenSSL 3.0.2 15 Mar 2022                                                        |
| Is contained                | false                                                                            |
| Is homebrew                 | false                                                                            |
| Is installed via Fabric.app | false                                                                            |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("./play-store-console.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("nl.mstruijk.gyas_app") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.216.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| public_suffix                   | 5.0.3        |
| addressable                     | 2.8.5        |
| artifactory                     | 3.0.15       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.827.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.6.0        |
| aws-sdk-core                    | 3.183.0      |
| aws-sdk-kms                     | 1.71.0       |
| aws-sdk-s3                      | 1.135.0      |
| babosa                          | 1.0.4        |
| CFPropertyList                  | 3.0.6        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.103.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.7        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.7.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.18.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.1       |
| google-apis-androidpublisher_v3 | 0.49.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.44.0       |
| json                            | 2.5.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.4.2        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.23.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.1        |
| bundler                         | 2.4.19       |
| rexml                           | 3.2.6        |
| webrick                         | 1.8.1        |
| rake                            | 13.0.6       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| openssl                         | 3.0.0        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| etc                             | 1.2.0        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2023-09-23**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by chnbr** [comment]
Same problem here ! Please fix. I run 2.216.0

**Comment by kpturner** [comment]
I have the same issue - and it does seem to be related to getting change logs.  I am sure this worked before I added some release notes to a release on an internal track.  I wanted to verify the proper directory structure and file name for future deployments when I want to include a change log, so I thought the best way to do so was to add release notes in the console then download them with `supply init`.  Doing so results in the error in the OP.

**Comment by kpturner** [comment]
Seems this is my problem: https://github.com/fastlane/fastlane/issues/21505

**Comment by mgarbade** [comment]
Similar problem here:

- Windows 10
- ruby version: 3.2.2
- fastlane version: 2.217.0

Full error log:
```
$ fastlane supply init
[✔] 🚀
[12:47:57]: 🕗  Downloading metadata, images, screenshots...
[12:47:59]: 📝  Downloading metadata (en-US)
[12:47:59]: Writing to metadata/en-US/title.txt...
[12:47:59]: Writing to metadata/en-US/short_description.txt...
[12:47:59]: Writing to metadata/en-US/full_description.txt...
[12:47:59]: Writing to metadata/en-US/video.txt...
[12:47:59]: 🖼️  Downloading images (en-US)
[12:47:59]: Downloading `featureGraphic` for en-US...
[12:48:00]:     Downloaded - metadata/en-US/images/featureGraphic.jpeg
[12:48:00]: Downloading `icon` for en-US...
[12:48:01]:     Downloaded - metadata/en-US/images/icon.png
[12:48:01]: Downloading `tvBanner` for en-US...
[12:48:01]: Downloading `phoneScreenshots` for en-US...
[12:48:03]:     Downloaded - metadata/en-US/images/phoneScreenshots/1_en-US.png
[12:48:03]:     Downloaded - metadata/en-US/images/phoneScreenshots/2_en-US.png
[12:48:03]: Downloading `sevenInchScreenshots` for en-US...
[12:48:04]:     Downloaded - metadata/en-US/images/sevenInchScreenshots/1_en-US.png
[12:48:05]:     Downloaded - metadata/en-US/images/sevenInchScreenshots/2_en-US.png
[12:48:05]: Downloading `tenInchScreenshots` for en-US...
[12:48:05]:     Downloaded - metadata/en-US/images/tenInchScreenshots/1_en-US.jpeg
[12:48:06]:     Downloaded - metadata/en-US/images/tenInchScreenshots/2_en-US.jpeg
[12:48:06]: Downloading `tvScreenshots` for en-US...
[12:48:06]: Downloading `wearScreenshots` for en-US...

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `size' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/21530 [open] 4 💬
    5 days ago

➡️  Fastlane supply init: undefined method `name' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/21529 [open] 3 💬
    a week ago

➡️  undefined method `*' for nil:NilClass frameit
    https://github.com/fastlane/fastlane/issues/21496 [open] 3 💬
    20 Sep 2023

and 496 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60name%27%20for%20nil&type=Issues&utf8=✓

C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/client.rb:303:in `block in latest_version': [!] undefined method `name' for nil:NilClass (NoMethodError)

      latest_version = tracks.select { |t| t.track == Supply::Tracks::DEFAULT }.map(&:releases).flatten.reject { |r| r.name.nil? }.max_by(&:name)
                                                                                                                      ^^^^^
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/client.rb:303:in `reject'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/client.rb:303:in `latest_version'       
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/setup.rb:19:in `perform_download'       
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/commands_generator.rb:55:in `block (2 levels) in run'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'        
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/commands_generator.rb:61:in `run'       
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/commands_generator.rb:13:in `start'     
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/bin/fastlane:23:in `<main>'
C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/client.rb:303:in `block in latest_version': undefined method `name' for nil:NilClass (NoMethodError)

      latest_version = tracks.select { |t| t.track == Supply::Tracks::DEFAULT }.map(&:releases).flatten.reject { |r| r.name.nil? }.max_by(&:name)
                                                                                                                      ^^^^^
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/client.rb:303:in `reject'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/client.rb:303:in `latest_version'       
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/setup.rb:19:in `perform_download'       
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/commands_generator.rb:55:in `block (2 levels) in run'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'        
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/commands_generator.rb:61:in `run'       
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/commands_generator.rb:13:in `start'     
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from C:/Users/garbade/.local/share/gem/ruby/3.2.0/gems/fastlane-2.217.0/bin/fastlane:23:in `<main>'
```

**Comment by belakm** [comment]
I have this same issue

**Comment by litinskii** [comment]
I have this same issue

**Comment by stivlo** [comment]
https://github.com/fastlane/fastlane/pull/22039

**Comment by ndhunju** [comment]
> I commented on #21530 while my precise issue was this one, I was doing `fastlane supply init`. I can confirm that the problem was not having a production release. We had internal testing release, closed testing release, but we did not have any production release and that caused this undefined method problem.

@matusfedorko were you able to fix it without actually releasing the app to production?

**Comment by matusfedorko** [comment]
Uff, a tough question after such a long time. I think I only made it work by pushing to production track, but don't worry that you would accidentally publish your app in play store. It still has to go through review and stuff like that.

**Comment by delacruzbrandon** [comment]
No work around yet?

**Comment by qnp** [comment]
This PR https://github.com/fastlane/fastlane/pull/21506 fixes it, but it seems they won't merge it as fast as we would like...

**Comment by iBotPeaches** [comment]
Fixed in https://github.com/fastlane/fastlane/pull/21506
