### ISSUE TITLE
Trying to Deploy IOS App on Test-flight via Azure DevOps - I'm facing build error

### ISSUE THREAD

**Issue by Shayila** [fastlane/fastlane#21531]
I'm able to see artefacts in Pipeline - But on deployment in release its throwing failure issue.
 
**##### Complete output when running fastlane, including the stack trace and command used**

`2023-09-26T07:20:57.4233290Z ##[section]Starting: Publish to the App Store TestFlight track
2023-09-26T07:20:57.4250820Z ==============================================================================
2023-09-26T07:20:57.4251030Z Task         : Apple App Store Release
2023-09-26T07:20:57.4251120Z Description  : Release an app to TestFlight or the Apple App Store
2023-09-26T07:20:57.4252210Z Version      : 1.218.0
2023-09-26T07:20:57.4252300Z Author       : Microsoft Corporation
2023-09-26T07:20:57.4255200Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2023-09-26T07:20:57.4255860Z ==============================================================================
2023-09-26T07:20:57.6219400Z [command]/usr/local/opt/ruby@3.0/bin/gem install fastlane
2023-09-26T07:21:20.4685370Z Successfully installed fastlane-2.216.0
2023-09-26T07:21:20.4685840Z Parsing documentation for fastlane-2.216.0
2023-09-26T07:21:20.4686190Z Installing ri documentation for fastlane-2.216.0
2023-09-26T07:21:20.4686570Z Done installing documentation for fastlane after 19 seconds
2023-09-26T07:21:20.4686790Z 1 gem installed
2023-09-26T07:21:20.4995400Z [command]/usr/local/opt/ruby@3.0/bin/gem update fastlane -i /Users/runner/.gem-cache
2023-09-26T07:21:23.7611820Z Updating installed gems
2023-09-26T07:21:23.7612230Z Nothing to update
2023-09-26T07:21:23.7612650Z Gems already up-to-date: fastlane
2023-09-26T07:21:23.8018000Z [command]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane pilot upload --api_key_path /Users/runner/work/_temp/api_key***.json -i /Users/runner/work/r1/a/_Latest-Xcode-CI/drop/output/iphoneos/Release/LockScreen.ipa -a com.customeranalytics.cadevelopments --skip_submission true --skip_waiting_for_build_processing true -p 6466410765
2023-09-26T07:21:25.4723450Z [07:21:25]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2023-09-26T07:21:27.1444060Z [07:21:27]: Sending anonymous analytics information
2023-09-26T07:21:27.1445120Z [07:21:27]: Learn more at https://docs.fastlane.tools/#metrics
2023-09-26T07:21:27.1445440Z [07:21:27]: No personal or sensitive data is sent.
2023-09-26T07:21:27.1446020Z [07:21:27]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2023-09-26T07:21:27.1859170Z 
2023-09-26T07:21:27.1859800Z Looking for related GitHub issues on fastlane/fastlane...
2023-09-26T07:21:27.1860260Z 
2023-09-26T07:21:27.8751660Z ➡️   invalid curve name after brew upgrade?
2023-09-26T07:21:27.8860210Z     https://github.com/fastlane/fastlane/issues/20553 [open] 13 💬
2023-09-26T07:21:27.8866830Z     3 days ago
2023-09-26T07:21:27.8867150Z 
2023-09-26T07:21:27.8868020Z ➡️  get_cert_info: path name contains null byte 
2023-09-26T07:21:27.8868320Z     https://github.com/fastlane/fastlane/issues/20489 [closed] 8 💬
2023-09-26T07:21:27.8868570Z     22 Nov 2022
2023-09-26T07:21:27.8868640Z 
2023-09-26T07:21:27.8875040Z ➡️  I am using Azure Devops to Deploy IOS Application on Test-flight During build i received this error 
2023-09-26T07:21:27.8875510Z     https://github.com/fastlane/fastlane/issues/19937 [closed] 11 💬
2023-09-26T07:21:27.8879340Z     26 May 2022
2023-09-26T07:21:27.8880920Z 
2023-09-26T07:21:27.8882050Z and 13 more at: https://github.com/fastlane/fastlane/search?q=string%20contains%20null%20byte&type=Issues&utf8=✓
2023-09-26T07:21:27.8882860Z 
2023-09-26T07:21:27.8885390Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
2023-09-26T07:21:27.8887060Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `initialize': [!] string contains null byte (ArgumentError)
2023-09-26T07:21:27.8887690Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `new'
2023-09-26T07:21:27.8888230Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `create'
2023-09-26T07:21:27.8888780Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:49:in `from_json_file'
2023-09-26T07:21:27.8889800Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:33:in `from'
2023-09-26T07:21:27.8890500Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/manager.rb:23:in `login'
2023-09-26T07:21:27.8891460Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/manager.rb:19:in `start'
2023-09-26T07:21:27.8891950Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
2023-09-26T07:21:27.8892450Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
2023-09-26T07:21:27.8893090Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2023-09-26T07:21:27.8893600Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2023-09-26T07:21:27.8894240Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2023-09-26T07:21:27.8894790Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2023-09-26T07:21:27.8895540Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2023-09-26T07:21:27.8896080Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
2023-09-26T07:21:27.8896580Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
2023-09-26T07:21:27.8897080Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
2023-09-26T07:21:27.8897570Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
2023-09-26T07:21:27.8897920Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2023-09-26T07:21:27.8898370Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2023-09-26T07:21:27.8898910Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `initialize': string contains null byte (ArgumentError)
2023-09-26T07:21:27.8899440Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `new'
2023-09-26T07:21:27.8899960Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `create'
2023-09-26T07:21:27.8900490Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:49:in `from_json_file'
2023-09-26T07:21:27.8901020Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:33:in `from'
2023-09-26T07:21:27.8901470Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/manager.rb:23:in `login'
2023-09-26T07:21:27.8901960Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/manager.rb:19:in `start'
2023-09-26T07:21:27.8902430Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
2023-09-26T07:21:27.8902960Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
2023-09-26T07:21:27.8903450Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2023-09-26T07:21:27.8903880Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2023-09-26T07:21:27.8904380Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2023-09-26T07:21:27.8904910Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2023-09-26T07:21:27.8905680Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2023-09-26T07:21:27.8906140Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
2023-09-26T07:21:27.8906650Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
2023-09-26T07:21:27.8907360Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
2023-09-26T07:21:27.8908010Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
2023-09-26T07:21:27.8908600Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2023-09-26T07:21:27.8908920Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2023-09-26T07:21:27.8935390Z ##[error]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2023-09-26T07:21:27.8945640Z ##[section]Finishing: Publish to the App Store TestFlight track
`

**Comment by yalamandarao** [comment]
I'm also facing same issue  ##[error]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1

**Comment by SivaNous** [comment]
Any update on above issue, I am also facing the same.

```
2023-11-06T23:12:37.2611410Z ##[section]Starting: Publish to the App Store TestFlight track
2023-11-06T23:12:37.2617710Z ==============================================================================
2023-11-06T23:12:37.2617900Z Task         : Apple App Store Release
2023-11-06T23:12:37.2618000Z Description  : Release an app to TestFlight or the Apple App Store
2023-11-06T23:12:37.2618140Z Version      : 1.218.0
2023-11-06T23:12:37.2618220Z Author       : Microsoft Corporation
2023-11-06T23:12:37.2619290Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2023-11-06T23:12:37.2619510Z ==============================================================================
2023-11-06T23:12:37.7629460Z [command]/usr/local/opt/ruby@3.0/bin/gem install fastlane
2023-11-06T23:12:59.0392800Z Successfully installed fastlane-2.216.0
2023-11-06T23:12:59.0393450Z Parsing documentation for fastlane-2.216.0
2023-11-06T23:12:59.0394440Z Installing ri documentation for fastlane-2.216.0
2023-11-06T23:12:59.0395230Z Done installing documentation for fastlane after 17 seconds
2023-11-06T23:12:59.0396330Z 1 gem installed
2023-11-06T23:12:59.0708750Z [command]/usr/local/opt/ruby@3.0/bin/gem update fastlane -i /Users/runner/.gem-cache
2023-11-06T23:13:02.7203800Z Updating installed gems
2023-11-06T23:13:02.7239600Z Nothing to update
2023-11-06T23:13:02.7276970Z Gems already up-to-date: fastlane
2023-11-06T23:13:02.7905130Z [command]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane pilot upload --api_key_path /Users/runner/work/_temp/api_key***.json -i /Users/runner/work/r1/a/_8.0 - iOS/AppStoreDrop/Viewpoint.ipa -a a.b.c -p xxxxxxx
2023-11-06T23:13:04.1528810Z [23:13:04]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2023-11-06T23:13:06.1669070Z [23:13:06]: Sending anonymous analytics information
2023-11-06T23:13:06.1670640Z [23:13:06]: Learn more at https://docs.fastlane.tools/#metrics
2023-11-06T23:13:06.1674280Z [23:13:06]: No personal or sensitive data is sent.
2023-11-06T23:13:06.1675180Z [23:13:06]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2023-11-06T23:13:06.2096150Z 
2023-11-06T23:13:06.2105490Z Looking for related GitHub issues on fastlane/fastlane...
2023-11-06T23:13:06.2106560Z 
2023-11-06T23:13:07.3186810Z ➡️  Trying to Deploy IOS App on Test-flight via Azure DevOps - I'm facing build error
2023-11-06T23:13:07.3215390Z     https://github.com/fastlane/fastlane/issues/21531 [open] 1 💬
2023-11-06T23:13:07.3247000Z     a week ago
2023-11-06T23:13:07.3274620Z 
2023-11-06T23:13:07.3483520Z ➡️   invalid curve name after brew upgrade?
2023-11-06T23:13:07.3530130Z     https://github.com/fastlane/fastlane/issues/20553 [open] 13 💬
2023-11-06T23:13:07.3558320Z     6 weeks ago
2023-11-06T23:13:07.3638980Z 
2023-11-06T23:13:07.3657950Z ➡️  get_cert_info: path name contains null byte 
2023-11-06T23:13:07.3684220Z     https://github.com/fastlane/fastlane/issues/20489 [closed] 8 💬
2023-11-06T23:13:07.3708120Z     22 Nov 2022
2023-11-06T23:13:07.3717870Z 
2023-11-06T23:13:07.3781690Z and 14 more at: https://github.com/fastlane/fastlane/search?q=string%20contains%20null%20byte&type=Issues&utf8=✓
2023-11-06T23:13:07.3822700Z 
2023-11-06T23:13:07.3830570Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
2023-11-06T23:13:07.3840880Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `initialize': [!] string contains null byte (ArgumentError)
2023-11-06T23:13:07.3859530Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `new'
2023-11-06T23:13:07.3875540Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `create'
2023-11-06T23:13:07.3899450Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:49:in `from_json_file'
2023-11-06T23:13:07.3921090Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:33:in `from'
2023-11-06T23:13:07.3944230Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/manager.rb:23:in `login'
2023-11-06T23:13:07.3946910Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/manager.rb:19:in `start'
2023-11-06T23:13:07.3949770Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
2023-11-06T23:13:07.3960160Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
2023-11-06T23:13:07.3976330Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2023-11-06T23:13:07.4035330Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2023-11-06T23:13:07.4045110Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2023-11-06T23:13:07.4098420Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2023-11-06T23:13:07.4126270Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2023-11-06T23:13:07.4143310Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
2023-11-06T23:13:07.4159530Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
2023-11-06T23:13:07.4180540Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
2023-11-06T23:13:07.4203180Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
2023-11-06T23:13:07.4215460Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2023-11-06T23:13:07.4231610Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2023-11-06T23:13:07.4241510Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `initialize': string contains null byte (ArgumentError)
2023-11-06T23:13:07.4246840Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `new'
2023-11-06T23:13:07.4252680Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:71:in `create'
2023-11-06T23:13:07.4283240Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:49:in `from_json_file'
2023-11-06T23:13:07.4307800Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/token.rb:33:in `from'
2023-11-06T23:13:07.4338050Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/manager.rb:23:in `login'
2023-11-06T23:13:07.4359950Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/manager.rb:19:in `start'
2023-11-06T23:13:07.4369820Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
2023-11-06T23:13:07.4371920Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
2023-11-06T23:13:07.4388480Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2023-11-06T23:13:07.4391170Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2023-11-06T23:13:07.4399080Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2023-11-06T23:13:07.4415320Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2023-11-06T23:13:07.4422850Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2023-11-06T23:13:07.4449110Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
2023-11-06T23:13:07.4458560Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
2023-11-06T23:13:07.4543060Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
2023-11-06T23:13:07.4554860Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
2023-11-06T23:13:07.4568640Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2023-11-06T23:13:07.4586240Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2023-11-06T23:13:07.4683840Z ##[error]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2023-11-06T23:13:07.4750930Z ##[section]Finishing: Publish to the App Store TestFlight track
```

**Comment by brentos99** [comment]
I'm having the same issue, but I've never had it working before, so I cannot confirm if the problem is due to my configuration of my Pipeline or if this an actual bug?


```
      - task: AppStoreRelease@1
        inputs:
          serviceEndpoint: 'SCC.Apple'
          releaseTrack: 'TestFlight'
          appType: 'iOS'
          ipaPath: '$(Build.ArtifactStagingDirectory)/*.ipa'
```

**Comment by hfl0506** [comment]
I found below website can resolve my problem, I hope it can help others. 
1. create api key:
https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api
2. https://damienaicheh.github.io/azure/devops/2021/10/27/configure-azure-devops-app-store-en.html

I also added below code in Info.plist which inside the `<dict>` (not sure it related as well).
<key>CFBundleVersion</key>
<string>1.1</string>

here's my task of release build to app store:
- task: AppStoreRelease@1
            inputs:
              authType: "ApiKey"
              apiKeyId: $(appleKeyID)
              apiKeyIssuerId: $(issuerID)
              apitoken: $(encodedApiKey)
              releaseTrack: "TestFlight"
              appIdentifier: $(appID)
              appType: "iOS"
              ipaPath: // path to your build 
              shouldSkipWaitingForProcessing: true
              shouldSkipSubmission: true
              appSpecificId: $(appleID)

**Comment by brentos99** [comment]
I was able to fix this problem. 

The fix to is to the base64 encode of the .p8 file when you add it to the Service Connection. While the .p8 file downloaded from the Apple Developer portal looks like it's base64 encoded, it needs to be re-encoded, including the "-----BEGIN PRIVATE KEY-----" section. 

The link shared above by @hlf0506 ( https://damienaicheh.github.io/azure/devops/2021/10/27/configure-azure-devops-app-store-en.html ) gives instructions on how to do this, (copied and pasted below)


Concerning the API_KEY_ENCODED to generate it, just encode the content of the .p8 file as is. Do not change the format of the file otherwise it will not work. To convert your key to base64, put it in a txt file and run one of this command below, depending on your OS. You will get a file containing the base64 string that represent your API key.

**Windows**
`certutil -encode data.txt tmp.b64 && findstr /v /c:- tmp.b64 > data.b64 && del tmp.b64`
**Mac**
`base64 -i data.txt -o data.b64`
**Ubuntu**
`base64 data.txt > data.b64`

**Comment by GSFZamai** [comment]
> I found below website can resolve my problem, I hope it can help others.
> 
> 1. create api key:
>    https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api
> 2. https://damienaicheh.github.io/azure/devops/2021/10/27/configure-azure-devops-app-store-en.html
> 
> I also added below code in Info.plist which inside the `<dict>` (not sure it related as well).
> 
> ```
> <key>CFBundleVersion</key>
> <string>1.1</string>
> ```
> 
> here's my task of release build to app store:
> 
> ```
> - task: AppStoreRelease@1
>             inputs:
>               authType: "ApiKey"
>               apiKeyId: $(appleKeyID)
>               apiKeyIssuerId: $(issuerID)
>               apitoken: $(encodedApiKey)
>               releaseTrack: "TestFlight"
>               appIdentifier: $(appID)
>               appType: "iOS"
>               ipaPath: // path to your build 
>               shouldSkipWaitingForProcessing: true
>               shouldSkipSubmission: true
>               appSpecificId: $(appleID)
> ```

This solution worked for me too.
I've tested with Personal API key and didn't work.
With the Team Key worked!
Thank you!

**Comment by Li-Sim-Ideagen** [comment]
Hey guys, I followed the base64 encoding as well and it works! But I would really like to understand why does it need the API key to be encoded in base64 for it to work?

**Comment by stephan-wolf-ais** [comment]
This issue is really annoying  and needs to fixed by

Feature-Request: Accept the p8 File Content as is. It is base64 encoded and can be validated as is
