### ISSUE TITLE
pod_lib_lint is unable to find some dependencies (Bundler::GemNotFound) 

### ISSUE THREAD

**Issue by carsonhawley** [fastlane/fastlane#21560]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm experiencing issues using `pod_lib_lint` as a standalone action or as part of a custom lane. The resulting error claims that several packages could not be found in locally installed gems, even though they appear to be present. 

Disclaimer: I'm not a Ruby guy and I've had limited experience with Fastlane. Installed via homebrew.

##### Command executed

`fastlane run pod_lib_lint`

##### Complete output when running fastlane, including the stack trace and command used
```       
...
[✔] 🚀 
[20:43:27]: fastlane detected a Gemfile in the current directory
[20:43:27]: However, it seems like you didn't use `bundle exec`
[20:43:27]: To launch fastlane faster, please use
[20:43:27]: 
[20:43:27]: $ bundle exec fastlane run pod_lib_lint
[20:43:27]: 
[20:43:27]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+---------------------------------------------------------------------------------------------------------------------+
|                                                    Used plugins                                                     |
+----------------------------+---------+------------------------------------------------------------------------------+
| Plugin                     | Version | Action                                                                       |
+----------------------------+---------+------------------------------------------------------------------------------+
| fastlane-plugin-versioning | 0.5.2   | ci_build_number, get_app_store_version_number, get_build_number_from_plist,  |
|                            |         | get_build_number_from_xcodeproj, get_info_plist_path,                        |
|                            |         | get_version_number_from_git_branch, get_version_number_from_plist,           |
|                            |         | get_version_number_from_xcodeproj, increment_build_number_in_plist,          |
|                            |         | increment_build_number_in_xcodeproj, increment_version_number_in_plist,      |
|                            |         | increment_version_number_in_xcodeproj                                        |
+----------------------------+---------+------------------------------------------------------------------------------+

[20:43:27]: --------------------------
[20:43:27]: --- Step: pod_lib_lint ---
[20:43:27]: --------------------------
[20:43:27]: $ bundle exec pod lib lint
[20:43:28]: ▸ /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/definition.rb:524:in `materialize': Could not find json-2.6.3, digest-crc-0.6.5, unf_ext-0.0.8.2 in locally installed gems (Bundler::GemNotFound)
[20:43:28]: ▸ from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/definition.rb:197:in `specs'
[20:43:28]: ▸ from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/definition.rb:254:in `specs_for'
[20:43:28]: ▸ from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/runtime.rb:18:in `setup'
[20:43:28]: ▸ from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler.rb:171:in `setup'
[20:43:28]: ▸ from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/setup.rb:23:in `block in <top (required)>'
[20:43:28]: ▸ from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/ui/shell.rb:159:in `with_level'
[20:43:28]: ▸ from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/ui/shell.rb:111:in `silence'
[20:43:28]: ▸ from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/setup.rb:23:in `<top (required)>'
[20:43:28]: ▸ from <internal:/Users/bluebonsai/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
[20:43:28]: ▸ from <internal:/Users/bluebonsai/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
[20:43:28]: ▸ from /Users/bluebonsai/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems.rb:1370:in `<top (required)>'
[20:43:28]: ▸ from <internal:gem_prelude>:2:in `require'
[20:43:28]: ▸ from <internal:gem_prelude>:2:in `<internal:gem_prelude>'

Looking for related GitHub issues on fastlane/fastlane...

/Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Exit status of command 'bundle exec pod lib lint' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
/Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/definition.rb:524:in `materialize': Could not find json-2.6.3, digest-crc-0.6.5, unf_ext-0.0.8.2 in locally installed gems (Bundler::GemNotFound)
	from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/definition.rb:197:in `specs'
	from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/definition.rb:254:in `specs_for'
	from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/runtime.rb:18:in `setup'
	from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler.rb:171:in `setup'
	from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/setup.rb:23:in `block in <top (required)>'
	from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/ui/shell.rb:159:in `with_level'
	from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/ui/shell.rb:111:in `silence'
	from /Users/bluebonsai/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/bundler/setup.rb:23:in `<top (required)>'
	from <internal:/Users/bluebonsai/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/bluebonsai/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/bluebonsai/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems.rb:1370:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
\e[0m
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/pod_lib_lint.rb:31:in `run'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/bin/fastlane:25:in `load'
	from /Users/bluebonsai/homebrew/Cellar/fastlane/2.216.0/libexec/bin/fastlane:25:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 13.6                                                    |
| Ruby                        | 3.1.4                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.39.3 (Apple Git-145)                      |
| Installation Source         | ~/homebrew/Cellar/fastlane/2.216.0/libexec/bin/fastlane |
| Host                        | macOS 13.6 (22G120)                                     |
| Ruby Lib Dir                | ~/homebrew/Cellar/ruby@3.1/3.1.4/lib                    |
| OpenSSL Version             | OpenSSL 3.1.3 19 Sep 2023                               |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Library/Developer/CommandLineTools/                    |
| Xcode Version               |                                                         |
| Swift Version               | 5.9                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

...redacted

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.216.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.5.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| public_suffix                   | 5.0.3        |
| addressable                     | 2.8.5        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| bundler                         | 2.4.10       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.7        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.1       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.44.0       |
| jwt                             | 2.7.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.2        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.6.0        |
| aws-partitions                  | 1.834.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.185.1      |
| aws-sdk-kms                     | 1.72.0       |
| aws-sdk-s3                      | 1.136.0      |
| excon                           | 0.104.0      |
| multi_json                      | 1.15.0       |
| signet                          | 0.18.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| google-apis-androidpublisher_v3 | 0.50.0       |
| json                            | 2.6.3        |
| unicode-display_width           | 2.5.0        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.23.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.12.1       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.2        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
| fastlane-plugin-versioning      | 0.5.2        |
</details>

*generated on:* **2023-10-08**
</details>

**Comment by carsonhawley** [comment]
Update: I decided to rethink my strategy here. In retrospect, my assumption that homebrew'd fastlane and its version of Ruby would play nice with whatever version of homebrew'd cocoapods I had installed was unrealistic. Today I installed using Bundler and everything works as expected. 

Conclusion. If fastlane itself is the only dependency you'll need, homebrew is fine. Otherwise install via Bundler. Hope this points someone else in the right direction.
