### ISSUE TITLE
undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

### ISSUE THREAD

**Issue by AndrewLiu2021** [fastlane/fastlane#21585]
/usr/local/Cellar/fastlane/2.216.0/libexec/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^

**Comment by zhekix** [comment]
# https://github.com/CocoaPods/CocoaPods/issues/12081
gem 'activesupport', '~> 7.0.8'

Add these lines in Gemfile

**Comment by joomsch** [comment]
> `gem 'activesupport', '~> 7.0.8'`
> 
> Add this line in Gemfile and call `bundle install`

I've added `gem 'activesupport', '~> 7.0.8' ` to my gemfile and run `bundle install`, but I still get the above error. The output of `bundle install` shows the correct version (7.0.8) but when running fastlane it still tries to use `activesupport-7.1.1`. Any other ideas?

```
/opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
	from <internal:/opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods.rb:9:in `<top (required)>'
	from <internal:/opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/cocoapods-1.13.0/bin/pod:36:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/bin/pod:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/bin/pod:25:in `<main>'
error Command failed with exit code 1.
```

**Comment by mokagio** [comment]
Hey @joomsch, in the logs you shared, the Fastlane binary comes from the Homebrew installation (`/opt/homebrew/Cellar/fastlane`). I assume you have been invoking Fastlane with `fastlane`?

To use the one installed with Bundler, that is the one that should use the gem set defined in your `Gemfile`, you'll need to run it via `bundle exec fastlane`.

Hope this helps.

**Comment by broomfn** [comment]
Hi,

I'm getting the same issue when doing a "pod install"

```
$ pod install
Traceback (most recent call last):
	9: from /Users/developer/.rbenv/versions/2.7.3/bin/pod:23:in `<main>'
	8: from /Users/developer/.rbenv/versions/2.7.3/bin/pod:23:in `load'
	7: from /Users/developer/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/cocoapods-1.13.0/bin/pod:36:in `<top (required)>'
	6: from /Users/developer/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	5: from /Users/developer/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	4: from /Users/developer/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/cocoapods-1.13.0/lib/cocoapods.rb:9:in `<top (required)>'
	3: from /Users/developer/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	2: from /Users/developer/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	1: from /Users/developer/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
/Users/developer/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)
Did you mean?  deprecate_constant
```

Not using fastlane, any ideas how to fix it? I've tried the suggested Gemfile fix but still get the same issue 🤷‍♂️ 

Thanks

**Comment by mokagio** [comment]
@broomfn are you running `pod install` or `bundle exec pod install`?

The gems defined in `Gemfile` are used only when running through [Bundler](https://bundler.io/), that is, through `bundle exec <command>`.

**Comment by Jcarloluna** [comment]
> @broomfn are you running `pod install` or `bundle exec pod install`?
> 
> The gems defined in `Gemfile` are used only when running through [Bundler](https://bundler.io/), that is, through `bundle exec <command>`.

thanks, worked for me

**Comment by joomsch** [comment]
> Hey @joomsch, in the logs you shared, the Fastlane binary comes from the Homebrew installation (`/opt/homebrew/Cellar/fastlane`). I assume you have been invoking Fastlane with `fastlane`?
> 
> To use the one installed with Bundler, that is the one that should use the gem set defined in your `Gemfile`, you'll need to run it via `bundle exec fastlane`.
> 
> Hope this helps.

It did. Thank you so much!

**Comment by ingemar** [comment]
If you came here via a web search, you're probably looking for [Stand-Alone Active Support](https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support).

**Comment by rubywarlock** [comment]
Я столкнулся с этой ошибкой, но не понимаю причем тут clock.rb? ошибка возникает на строчке `require 'active_support/time'` в файле `spec_helper.rb`

**Comment by faizy-ahmed** [comment]
Delete `Gemfile.lock` and `run bundler exec pod install`
It resolves my issue on cocoapods 1.13.0.

**Comment by nikans** [comment]
This looks like it's breaking our project generation for newer Cocoapods and  Xcode with the latest command line tools (16.3)
