### ISSUE TITLE
Cannot run "match" when using an S3 bucket for storage: "The AWS Access Key Id you provided does not exist in our records."

### ISSUE THREAD

**Issue by kpturner** [fastlane/fastlane#21605]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have been following the documentation to set up S3 as a storage vehicle for `match`.

I ran `fastlane match init` and it created a fairly empty `Matchfile` 

I then confirm all my S3 credentials were working by playing around S3 from the command line using the AWS SDK.  This confirmed that I have the correct environment variables set up for S3 access.  This being so, I modified the `Matchfile` thus:
```
s3_bucket("<REDACTED>").  <--- This bucket does actually exist in AWS
s3_region(ENV["AWS_REGION"])
s3_access_key(ENV["AWS_ACCESS_KEY_ID"])
s3_secret_access_key(ENV["AWS_SECRET_ACCESS_KEY"])

storage_mode("s3")

type("appstore") # The default type, can be: appstore, adhoc, enterprise or development
``` 

##### Command executed
```
    match(
      type: "appstore",
      api_key_path: "fastlane/app-store-connect-api-key.json"
    )
```

Now it would be easy to presume that the AWS_ACCESS_KEY_ID is wrong - but it definitely is not.

When I step through the internal ruby Fastlane code I can see that it is using a helper function to access the S3 bucket.  The first thing it appears to do is this:

```
s3_client.find_bucket!(s3_bucket)
```
which I can see (via outputting debug logs) that it successfully does.  All good so far - it has found the bucket using the access key and secret provided.

It then tries to look through the objects in the bucket - which of course will be pointless at this stage because there won't be anything in the bucket.  It does so like this:
```
.objects(prefix: s3_object_prefix).each do |object|
    
end
``` 
This is what throws the error.   

But why is it trying to download data from a bucket that would be empty?

Am I supposed to be doing something else to populate the bucket first?

<details>
  <pre>
+-----------------------------------------------------------------+
|           Detected Values from './fastlane/Matchfile'           |
+----------------------+------------------------------------------+
| s3_bucket            | gifsa-ios-fastlane                       |
| s3_region            | eu-west-2                                |
| s3_access_key        | <REDACTED>                     |
| s3_secret_access_key | X<REDACTED> |
| storage_mode         | s3                                       |
| type                 | appstore                                 |
+----------------------+------------------------------------------+
 
 
+----------------------------------------------------------------------------------+
|                            Summary for match 2.216.0                             |
+----------------------------------------+-----------------------------------------+
| type                                   | appstore                                |
| api_key_path                           | fastlane/app-store-connect-api-key.json |
| readonly                               | false                                   |
| generate_apple_certs                   | true                                    |
| skip_provisioning_profiles             | false                                   |
| app_identifier                         | ["com.monito.app"]                      |
| username                               | tech@monito.com                         |
| team_id                                | ********                             |
| storage_mode                           | s3                                      |
| git_branch                             | master                                  |
| shallow_clone                          | false                                   |
| clone_branch_directly                  | false                                   |
| skip_google_cloud_account_confirmation | false                                   |
| s3_region                              | eu-west-2                               |
| s3_access_key                          | *********                    |
| s3_secret_access_key                   | ********                                |
| s3_bucket                              | gifsa-ios-fastlane                      |
| s3_skip_encryption                     | false                                   |
| gitlab_host                            | https://gitlab.com                      |
| keychain_name                          | login.keychain                          |
| force                                  | false                                   |
| force_for_new_devices                  | false                                   |
| include_mac_in_profiles                | false                                   |
| include_all_certificates               | false                                   |
| force_for_new_certificates             | false                                   |
| skip_confirmation                      | false                                   |
| safe_remove_certs                      | false                                   |
| skip_docs                              | false                                   |
| platform                               | ios                                     |
| derive_catalyst_app_identifier         | false                                   |
| fail_on_name_taken                     | false                                   |
| skip_certificate_matching              | false                                   |
| skip_set_partition_list                | false                                   |
| verbose                                | false                                   |
+----------------------------------------+-----------------------------------------+
 
+--------------------------+
|       Lane Context       |
+---------------+----------+
| PLATFORM_NAME | ios      |
| LANE_NAME     | ios beta |
+---------------+----------+
[17:13:26]: The AWS Access Key Id you provided does not exist in our records.
 
+--------------------------------+
|        fastlane summary        |
+------+-----------+-------------+
| Step | Action    | Time (in s) |
+------+-----------+-------------+
| 1    | load_json | 0           |
| 💥   | match     | 0           |
+------+-----------+-------------+
 
[17:13:26]: fastlane finished with errors
 
Looking for related GitHub issues on fastlane/fastlane...
 
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/kpturner/.gem/ruby/3.2.2/bin/fastlane)
/Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': [!] The AWS Access Key Id you provided does not exist in our records. (Aws::S3::Errors::InvalidAccessKeyId)
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-s3-1.136.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-s3-1.136.0/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-s3-1.136.0/lib/aws-sdk-s3/plugins/accelerate.rb:43:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/seahorse/client/plugins/request_callback.rb:89:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/seahorse/client/request.rb:72:in `send_request'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-s3-1.136.0/lib/aws-sdk-s3/client.rb:8904:in `list_objects_v2'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-s3-1.136.0/lib/aws-sdk-s3/bucket.rb:973:in `block (2 levels) in objects'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/plugins/user_agent.rb:28:in `feature'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-s3-1.136.0/lib/aws-sdk-s3/bucket.rb:972:in `block in objects'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/resources/collection.rb:101:in `each'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/resources/collection.rb:101:in `each'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/resources/collection.rb:101:in `block in non_empty_batches'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/resources/collection.rb:52:in `each'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/resources/collection.rb:52:in `each'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/resources/collection.rb:52:in `block in each'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/resources/collection.rb:58:in `each'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/resources/collection.rb:58:in `each'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/aws-sdk-core-3.185.1/lib/aws-sdk-core/resources/collection.rb:58:in `each'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/match/lib/match/storage/s3_storage.rb:117:in `download'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/match/lib/match/runner.rb:37:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from ../../../fastlane/Fastfile:48:in `block (2 levels) in parsing_binding'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/fastlane:25:in `load'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/fastlane:25:in `<top (required)>'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
        from /Users/kpturner/.rubies/ruby-3.2.2/bin/bundle:25:in `load'
        from /Users/kpturner/.rubies/ruby-3.2.2/bin/bundle:25:in `<main>'

  </pre>
</details>

### Environment

<details>
  <pre> 
 swift-driver version: 1.75.2 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 13.3.1                                      |
| Ruby                        | 3.2.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.0                          |
| Installation Source         | ~/.gem/ruby/3.2.2/bin/fastlane              |
| Host                        | macOS 13.3.1 (22E261)                       |
| Ruby Lib Dir                | ~/.rubies/ruby-3.2.2/lib                    |
| OpenSSL Version             | OpenSSL 3.1.2 1 Aug 2023                    |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.3.1                                      |
| Swift Version               | 5.8.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
dir = "#{__dir__.gsub("fastlane", "")}../"
package = load_json(json_path: "#{dir}/package.json")
newVersion = package['version']
puts "Overall package version: #{newVersion}"

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :beta do
    version = android_get_version_name()
    puts "Current version: #{version}"
    if (version != newVersion) then
      version = newVersion
      build = "0"
    else  
      build = android_get_version_code()
    end
    sh "npx capacitor-set-version -v #{package['version']} -b #{build}"
    increment_version_code(
      gradle_file_path: "app/build.gradle",
    )
    gradle(task: "clean assembleRelease")
    gradle(task: "bundle", build_type: 'Release')
    #upload_to_play_store(
    #  track: "internal",
    #  skip_upload_apk: true
    #)
  end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    #version = get_version_number(
    #  xcodeproj: "App.xcodeproj",
    #  target: "App"
    #)
    #puts "Current version: #{version}"
    #if (version != newVersion) then
    #  version = newVersion
    #  build = "0"
    #else  
    #  build = get_build_number()
    #end
    #sh "npx capacitor-set-version -v #{package['version']} -b #{build}"
    #increment_build_number(
    #  xcodeproj: "App.xcodeproj"
    #)
    match(
      type: "appstore",
      api_key_path: "fastlane/app-store-connect-api-key.json"
    )
    #match_nuke(
    #  type: "appstore", 
    #  api_key_path: "fastlane/app-store-connect-api-key.json"
    #)
    #get_certificates(
    #  api_key_path: "fastlane/app-store-connect-api-key.json"
    #)
    #get_provisioning_profile(
    #  api_key_path: "fastlane/app-store-connect-api-key.json"
    #)
    #update_code_signing_settings(
    #  use_automatic_signing: false,
    #  code_sign_identity: 'iPhone Distribution',
    #  profile_name: lane_context[SharedValues::SIGH_NAME]
    #)
    #build_app(workspace: "App.xcworkspace", scheme: "App")
    # upload_to_testflight( api_key_path: "fastlane/app-store-connect-api-key.json" )
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.216.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-load_json              | 0.0.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android     | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| error_highlight                        | 0.5.1        |
| did_you_mean                           | 1.6.3        |
| syntax_suggest                         | 1.0.2        |
| addressable                            | 2.8.5        |
| artifactory                            | 3.0.15       |
| jmespath                               | 1.6.2        |
| aws-eventstream                        | 1.2.0        |
| aws-sigv4                              | 1.6.1        |
| aws-sdk-core                           | 3.185.1      |
| aws-sdk-kms                            | 1.72.0       |
| aws-sdk-s3                             | 1.136.0      |
| babosa                                 | 1.0.4        |
| bundler                                | 2.4.10       |
| CFPropertyList                         | 3.0.6        |
| colored                                | 1.2          |
| highline                               | 2.0.3        |
| commander                              | 4.6.0        |
| dotenv                                 | 2.8.1        |
| emoji_regex                            | 3.2.3        |
| excon                                  | 0.104.0      |
| faraday-em_http                        | 1.0.0        |
| faraday-em_synchrony                   | 1.0.0        |
| faraday-excon                          | 1.1.0        |
| faraday-httpclient                     | 1.0.1        |
| multipart-post                         | 2.3.0        |
| faraday-multipart                      | 1.0.4        |
| faraday-net_http                       | 1.0.1        |
| faraday-net_http_persistent            | 1.2.0        |
| faraday-patron                         | 1.0.0        |
| faraday-rack                           | 1.0.0        |
| faraday-retry                          | 1.0.3        |
| ruby2_keywords                         | 0.0.5        |
| faraday                                | 1.10.3       |
| faraday_middleware                     | 1.2.0        |
| unf_ext                                | 0.0.8.2      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.5        |
| faraday-cookie_jar                     | 0.0.7        |
| fastimage                              | 2.2.7        |
| gh_inspector                           | 1.1.3        |
| google-apis-androidpublisher_v3        | 0.51.0       |
| google-apis-playcustomapp_v1           | 0.13.0       |
| google-cloud-env                       | 1.6.0        |
| google-cloud-errors                    | 1.3.1        |
| google-cloud-core                      | 1.6.0        |
| google-apis-iamcredentials_v1          | 0.17.0       |
| google-apis-storage_v1                 | 0.19.0       |
| jwt                                    | 2.7.1        |
| multi_json                             | 1.15.0       |
| os                                     | 1.1.4        |
| signet                                 | 0.18.0       |
| googleauth                             | 1.8.1        |
| digest-crc                             | 0.6.5        |
| mini_mime                              | 1.1.5        |
| google-cloud-storage                   | 1.44.0       |
| json                                   | 2.6.3        |
| mini_magick                            | 4.12.0       |
| naturally                              | 2.2.1        |
| optparse                               | 0.1.1        |
| plist                                  | 3.7.0        |
| rubyzip                                | 2.3.2        |
| security                               | 0.1.3        |
| simctl                                 | 1.6.10       |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 2.5.0        |
| terminal-table                         | 3.0.2        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| word_wrap                              | 1.0.0        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| xcpretty-travis-formatter              | 1.0.1        |
| set                                    | 1.0.3        |
| public_suffix                          | 5.0.3        |
| aws-partitions                         | 1.843.0      |
| rexml                                  | 3.2.6        |
| webrick                                | 1.8.1        |
| httpclient                             | 2.8.3        |
| retriable                              | 3.1.2        |
| trailblazer-option                     | 0.1.2        |
| declarative                            | 0.0.20       |
| uber                                   | 0.1.0        |
| representable                          | 3.2.0        |
| google-apis-core                       | 0.11.2       |
| rake                                   | 13.1.0       |
| nanaimo                                | 0.3.0        |
| colored2                               | 3.1.2        |
| claide                                 | 1.1.0        |
| atomos                                 | 0.1.3        |
| xcodeproj                              | 1.23.0       |
| forwardable                            | 1.3.3        |
| logger                                 | 1.5.3        |
| pathname                               | 0.2.1        |
| shellwords                             | 0.1.0        |
| cgi                                    | 0.3.6        |
| date                                   | 3.3.3        |
| timeout                                | 0.3.1        |
| securerandom                           | 0.2.2        |
| uri                                    | 0.12.1       |
| openssl                                | 3.1.0        |
| digest                                 | 3.1.1        |
| ipaddr                                 | 1.2.5        |
| resolv                                 | 0.2.2        |
| time                                   | 0.2.2        |
| stringio                               | 3.0.4        |
| open-uri                               | 0.3.0        |
| mutex_m                                | 0.1.2        |
| net-http                               | 0.3.2        |
| net-protocol                           | 0.2.1        |
| ostruct                                | 0.5.5        |
| english                                | 0.7.2        |
| erb                                    | 4.0.2        |
| abbrev                                 | 0.1.1        |
| tempfile                               | 0.1.3        |
| delegate                               | 0.3.0        |
| fileutils                              | 1.7.0        |
| tmpdir                                 | 0.1.3        |
| base64                                 | 0.1.1        |
| singleton                              | 0.1.1        |
| open3                                  | 0.1.2        |
| nkf                                    | 0.1.2        |
| prettyprint                            | 0.1.1        |
| pp                                     | 0.4.0        |
| find                                   | 0.1.1        |
| yaml                                   | 0.2.1        |
| psych                                  | 5.0.1        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-load_json              | 0.0.1        |
| fastlane-plugin-versioning_android     | 0.1.1        |
</details>

*generated on:* **2023-10-30**
</details>
 </pre>
</details>

**Comment by kpturner** [comment]
I seem to have managed to get this to work by simply removing the following lines from the `Matchfile` 

```
s3_access_key(ENV["AWS_ACCESS_KEY_ID"])
s3_secret_access_key(ENV["AWS_SECRET_ACCESS_KEY"])
```
