### ISSUE TITLE
Manual install fastlane on mac

### ISSUE THREAD

**Issue by MariuzM** [fastlane/fastlane#21614]
I want to install manually fastlane and have it in custom folder, then just PATH to direct to its bin

but when running `fastlane --version`

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fastlane/cli_tools_distributor (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/marius/dev/fastlane-2.216.0/bin/fastlane:12:in `<main>'
```

my zsh path setup 
```
export PATH=$HOME/dev/fastlane-2.216.0/bin:$PATH
```

Not sure if this is possible or do i just need to install via Brew ?

**Comment by max-ott** [comment]
My guess it's related to using the default Ruby on your Mac and permissions. I would recommend not directly working with the default Ruby on macOS.
