### ISSUE TITLE
Sigh Adhoc crashes for platform macOS

### ISSUE THREAD

**Issue by ViRb3** [fastlane/fastlane#21615]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The following commands work just fine:

```
fastlane sigh renew -a com.test.app --skip-install --development
fastlane sigh renew -a com.test.app --skip-install --adhoc
fastlane sigh renew -a com.test.app --skip-install --platform macos --development
```

But this one fails with exception:

```
fastlane sigh renew -a com.test.app --skip-install --platform macos --adhoc
```

The exception:

```
/opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:217:in `handle_response': \e[31m[!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "xxx",
    "status" : "409",
    "code" : "ENTITY_ERROR.RELATIONSHIP.NOT_ALLOWED",
    "title" : "A relationship in the provided entity is not allowed for this request",
    "resultCode" : 35,
    "detail" : "No devices can be associated to Provisioning Profiles for the App Store."
  } ]
}\e[0m
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:73:in `proxy_post'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:253:in `post_profiles'
	from /opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/forwardable.rb:238:in `post_profiles'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/models/profile.rb:80:in `create'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/sigh/lib/sigh/runner.rb:184:in `create_profile!'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/sigh/lib/sigh/runner.rb:54:in `run'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/sigh/lib/sigh/manager.rb:8:in `start'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/sigh/lib/sigh/commands_generator.rb:62:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/sigh/lib/sigh/commands_generator.rb:140:in `run'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/sigh/lib/sigh/commands_generator.rb:17:in `start'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.216.0/libexec/bin/fastlane:25:in `<main>'
```

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 14.1                                                       |
| Ruby                        | 3.1.4                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.42.0                                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.216.0/libexec/bin/fastlane |
| Host                        | macOS 14.1 (23B74)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby@3.1/3.1.4/lib                    |
| OpenSSL Version             | OpenSSL 3.1.0 14 Mar 2023                                  |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 15.0                                                       |
| Swift Version               | 5.9                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.216.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| public_suffix                   | 5.0.3        |
| addressable                     | 2.8.5        |
| artifactory                     | 3.0.15       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.827.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.6.0        |
| aws-sdk-core                    | 3.183.0      |
| aws-sdk-kms                     | 1.71.0       |
| aws-sdk-s3                      | 1.135.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.4.10       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.103.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.7        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.7.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.18.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.1       |
| google-apis-androidpublisher_v3 | 0.50.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.44.0       |
| json                            | 2.6.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.4.2        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.23.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.12.1       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.2        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
</details>

*generated on:* **2023-11-04**
</details> </pre>
</details>

**Comment by ViRb3** [comment]
Checked the Apple Dev Portal and did some googling, seems like the macOS platform simply doesn't support adhoc at all: https://developer.apple.com/forums/thread/671008. Oh well, all good with fastlane then!
