### ISSUE TITLE
android - Invalid request

### ISSUE THREAD

**Issue by luco** [fastlane/fastlane#21662]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Getting invalid request without returning what it's invalid.

##### Command executed

fastlane android release

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
+--------------------------------------------------------------------------------------------------------------+
|                                          Summary for supply 2.217.0                                          |
+------------------------------------+-------------------------------------------------------------------------+
| package_name                       | [redacted]                                                      |
| json_key                           | ./fastlane/PlayStoreAuth.json                                           |
| rollout                            | 1                                                                       |
| metadata_path                      | ./fastlane/metadata                                                     |
| aab                                | ./android/app/build/outputs/bundle/release/app-release.aab |
| skip_upload_images                 | true                                                                    |
| skip_upload_screenshots            | true                                                                    |
| skip_upload_metadata               | true                                                                    |
| timeout                            | 600                                                                     |
| release_status                     | completed                                                               |
| track                              | production                                                              |
| skip_upload_apk                    | false                                                                   |
| skip_upload_aab                    | false                                                                   |
| skip_upload_changelogs             | false                                                                   |
| sync_image_upload                  | false                                                                   |
| track_promote_release_status       | completed                                                               |
| validate_only                      | false                                                                   |
| check_superseded_tracks            | false                                                                   |
| deactivate_on_promote              | true                                                                    |
| changes_not_sent_for_review        | false                                                                   |
| rescue_changes_not_sent_for_review | true                                                                    |
| ack_bundle_installation_warning    | false                                                                   |
+------------------------------------+-------------------------------------------------------------------------+
</pre>

```
#<Thread:0x00000001080664a0 /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/queue_worker.rb:37 run> terminated with exception (report_on_exception is true):
/Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/interface.rb:184:in `abort_with_message!': android - Invalid request (FastlaneCore::Interface::FastlaneCommonException)
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/uploader.rb:526:in `rescue in block in create_meta_upload_worker'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/uploader.rb:517:in `block in create_meta_upload_worker'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
/Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.2/lib/google/apis/core/http_command.rb:244:in `check_status': Invalid request (Google::Apis::ClientError)
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.2/lib/google/apis/core/api_command.rb:135:in `check_status'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.2/lib/google/apis/core/http_command.rb:207:in `process_response'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.2/lib/google/apis/core/http_command.rb:326:in `execute_once'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.2/lib/google/apis/core/http_command.rb:131:in `block (2 levels) in do_retry'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.2/lib/google/apis/core/http_command.rb:128:in `block in do_retry'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.2/lib/google/apis/core/http_command.rb:118:in `do_retry'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.2/lib/google/apis/core/http_command.rb:109:in `execute'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.2/lib/google/apis/core/base_service.rb:418:in `execute_or_queue_command'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google-apis-androidpublisher_v3-0.53.0/lib/google/apis/androidpublisher_v3/service.rb:1181:in `get_edit_listing'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/client.rb:238:in `listing_for_language'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/supply/lib/supply/uploader.rb:519:in `block in create_meta_upload_worker'
	from /Users/user1/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
```

</details>

### Environment

<details>
  <pre>
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.217.0 | ✅ Up-To-Date  |
</pre>
</details>

**Comment by wjbeau** [comment]
I just got this too.  Couple additional data points in my case:

1. It created the release in Firebase but didn't do the tester distribution step
2. I didn't specify any release notes and my tester group name contains a space i.e. "Internal Testers" in case that might be a problem

**Comment by tommysuds** [comment]
I'm seeing this issue as well and like @wjbeau , it still created the release. I was able to add release notes

**Comment by tattivitorino** [comment]
@wjbeau @tommysuds same here.. it creates the release but it does not distribute.. and the only feedback I have is "Invalid request"

**Comment by Floul** [comment]
Same here. It created the release but have an error on this step:
```
Distributing release.
DEBUG -- : Sending HTTP post https://firebaseappdistribution.googleapis.com/v1/projects/MYPROJECTID/apps/MYAPPID/releases/58ej3q0k1keq8:distribute?
```

**Comment by marcus-sa** [comment]
+1 can't get it to work either

**Comment by gitperr** [comment]
Just encountered this issue as well, still working on debugging.

**Comment by Saipavangithub119** [comment]
I am using below code to upload apk file to firebase ( i have added environment variable in fastlane folder)

lane :beta do
  # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )

  # ...
end

platform :android do
    desc "My awesome app"
    lane :distribute do
        #build_android_app(...)
        # build_android_app is a built-in fastlane action.
        release = firebase_app_distribution(
            app: ENV['APP'],
            testers: ENV['TESTERS'],
            release_notes: "Lots of amazing new features to test out!",
            android_artifact_type: ENV['ANDROID_ARTIFACT_TYPE'],
            firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
            firebase_cli_path: ENV['FIREBASE_CLI_PATH'],
            apk_path: ENV['APK_PATH']
        )
    end
end


after this i ran fastlane androd distribute then it will produce the invalid request error 
![Uploading
![Screenshot 2024-04-11 152717](https://github.com/fastlane/fastlane/assets/91584130/43aa0758-d388-44aa-a4f8-1939a0f7f17e)
 image.png…]()

Could you please help me anyone available, this is urgent for me.

**Comment by gitperr** [comment]
For me it created the release and distributed it, but then failed afterwards:

```
INFO [2024-04-12 11:05:17.67]: ✅ Uploaded IPA successfully and created release 1.0 (0).
INFO [2024-04-12 11:05:17.68]: 📜 Setting release notes.
INFO [2024-04-12 11:05:18.66]: 📦 Distributing release.
WARN [2024-04-12 11:05:19.53]: Lane Context:
INFO [2024-04-12 11:05:19.53]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"distribute"}
ERROR [2024-04-12 11:05:19.53]: Invalid request
```

And I could see the build on Firebase, it's downloadable and it works too. Just that it errors out here.

One thing I figured:
- When I create the Firebase project + App by hand (clicking through the UI), Firebase setup works just fine with Fastlane. It is able to handle everything without errors
- When I do Firebase project + App creation by Terraform (so, in code), the setup does not work. Might have been a problem with Google provider for Terraform... But if this was the case, I'm guessing then everyone else here created their projects with Terraform?

**Comment by Kaddtechnologies** [comment]
Any update to this. Getting the same Invalid Request. 
Tried all of the options here and still doesnt work
```

  android - Invalid request
    https://github.com/fastlane/fastlane/issues/21662 [open] 9 💬
    4 days ago

➡️   Google Api Error: Invalid request - Package not found
    https://github.com/fastlane/fastlane/issues/21749 [open] 2 💬
    15 Feb 2024

➡️  Google Api Error: Invalid request - Version code x has already been used.
    https://github.com/fastlane/fastlane/issues/21642 [open] 7 💬
    5 weeks ago
```

**Comment by rowanibrahem** [comment]
I can't solve this issue , So how can you solve this ?

**Comment by Kaddtechnologies** [comment]
Yes turns out my local firebase cli was logged into the incorrect account i logged into the correct account that had the app I was trying to distribute then it worked.

This is for local firebase cli and fastlane

**Comment by mostafabrazi** [comment]
In my case, i was using `app bundle id` instead  of **Firbase app ID** in `app` property.
Check firebase app ID on the firebase console.

**Comment by wiencheck** [comment]
@mostafabrazi The test group name was what was causing the issue for me, I replaced all spaces with dashes and now everything's working again. Thanks!

**Comment by danielesegato** [comment]
The issue is that the firebase app distribution plugin hide too much of the error, you could get this error for many different reason and I'll argue that the fix to THIS bug would be to implement a proper error handling that gives actually useful information rather than a very useless "Invalid Request" I'm sure firebase is giving a proper error in return, the plugin is not logging it.

**Comment by jaydeepbhayani** [comment]
I have configurations for **com.anetos.parkme** and **com.anetos.parkme.debug** under one Firebase project.
debug build is uploading fine but the release build is not getting uploaded. By saying

` You can ⌘ + double-click on links to open them directly in your browser.
/opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:244:in `check_status': [!] Invalid request (Google::Apis::ClientError)
`
 I have checked the json key, sha-1 and package on firebase as well everything seems good only when I try to make release build it is not getting uploaded.
 
![Screenshot 2024-05-22 at 2 37 39 PM](https://github.com/fastlane/fastlane/assets/15911549/dde34a0f-e70b-4262-88a4-83b59c0b99a2)

**Comment by hasithmeth** [comment]
Hello!
I've had the same problem with my fastlane to firebase app distribution.
Solution was to 
1. Update your firebase tools
2. Make sure you go to the app distribution page and click get started button (otherwise it won't work)

good luck!

**Comment by AlekseyP18** [comment]
> mostafabrazi

Thanks bro, you helped very well!

**Comment by felixmede** [comment]
Had the same issue
the metadata folder looked like this: "fastlane/metadata/android/en-US/changelogs"
fixed it by removing the android folder so now it looks like this: "fastlane/metadata/en-US/changelogs"

**Comment by abdullahkaracabey** [comment]
I solved this problem after recreating the service account file from the Firebase console. I had previously created it from the google cloud console page and it did not work.

**Comment by Mairramer** [comment]
Checks if the service account is the same as the one defined in the firebase console. I was getting this error, because I had created it for another account.

**Comment by bstolyarov** [comment]
Fixed by generating a new private key (a new json file) in Firebase project settings - Service account. 
Before that, I tried to use a json file from the Google Cloud platform.

**Comment by habtamu** [comment]
> [@wjbeau](https://github.com/wjbeau) 's comment gave me the clues to solve this issue. My tester group also contained space. So instead of `Internal Testers`, you should use `internal-testers` to escape the space.

Fixed by navigating to 'Add Distribution' → 'Testers & Groups' and creating a new tester group (e.g., 'internal-tester').
and provides release notes on fastlane lane
example:
lane :deploy_on_firebase do |options|
    release_notes=""

    if options[:release_notes]
        release_notes = options[:release_notes]
    else
        commit = last_git_commit
        author = commit[:author_email]
        commit_message =  commit[:message]
        hash = commit[:abbreviated_commit_hash]
        release_notes = "[Fastlane build]\n[#{author}]\n[#{hash}]\n#{commit_message}"
    end

    firebase_app_distribution(
        android_artifact_path: lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS][0],
        app: ENV["FIREBASE_APP_ID"],
        groups: "internal-testers",
        service_credentials_file: "../firebase-distribution-cred.json"
    )
end

**Comment by wmaca-friday** [comment]
In my case, it was related to the metadata directory structure.
Where it was `./metadata/android/default/changelogs/default.txt`, I changed to `./metadata/en-US/changelogs/default.txt`.
