### ISSUE TITLE
No code signing identity found and can not create a new one because you enabled `readonly`

### ISSUE THREAD

**Issue by NandhiniYeganathan** [fastlane/fastlane#21679]
I have .p12 file and it's successfully added in the keychain. It's properly run in Xcode. while running in CI/CD using gitlab its showing this error. In the build stage working fine, but when we come to TestFlight build it's not working. 

+---------------------------------------------+
| Detected Values from './fastlane/Matchfile' |
+----------------------+----------------------+
| gitlab_project       | id             |
| gitlab_host          | https://gitlab.com/   |
| storage_mode         | gitlab_secure_files  |
| type                 | development          |
+----------------------+----------------------+
+-----------------------------------------------------------------------------------+
|                             Summary for match 2.217.0                             |
+----------------------------------------+------------------------------------------+
| type                                   | appstore                                 |
| app_identifier                         | ["com.bundle.id"] |
| readonly                               | true                                     |
| generate_apple_certs                   | true                                     |
| skip_provisioning_profiles             | false                                    |
| username                               | user       |
| team_id                                | id                               |
| storage_mode                           | gitlab_secure_files                      |
| git_branch                             | master                                   |
| shallow_clone                          | false                                    |
| clone_branch_directly                  | false                                    |
| skip_google_cloud_account_confirmation | false                                    |
| s3_skip_encryption                     | false                                    |
| gitlab_project                         | id                                 |
| gitlab_host                            | https://gitlab.com/                       |
| job_token                              | [token]                  |
| keychain_name                          | fastlane_tmp_keychain                    |
| force                                  | false                                    |
| force_for_new_devices                  | false                                    |
| include_mac_in_profiles                | false                                    |
| include_all_certificates               | false                                    |
| force_for_new_certificates             | false                                    |
| skip_confirmation                      | false                                    |
| safe_remove_certs                      | false                                    |
| skip_docs                              | false                                    |
| platform                               | ios                                      |
| derive_catalyst_app_identifier         | false                                    |
| fail_on_name_taken                     | false                                    |
| skip_certificate_matching              | false                                    |
| skip_set_partition_list                | false                                    |
| verbose                                | false                                    |
+----------------------------------------+------------------------------------------+
[14:06:55]: Initializing match for GitLab project on https://gitlab.com/
[14:06:59]: Couldn't find a valid code signing identity for distribution... creating one for you now
+--------------------------------------------------------------------------------------------+
|                                        Lane Context                                        |
+---------------------------+----------------------------------------------------------------+
| DEFAULT_PLATFORM          | ios                                                            |
| PLATFORM_NAME             | ios                                                            |
| LANE_NAME                 | ios beta                                                       |
| KEYCHAIN_PATH             | ~/Library/Keychains/fastlane_tmp_keychain                      |
| ORIGINAL_DEFAULT_KEYCHAIN | "/Library/Keychains/fastlane_tmp_keychain-db" |
+---------------------------+----------------------------------------------------------------+
[14:06:59]: No code signing identity found and can not create a new one because you enabled `readonly`
+---------------------------------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | setup_ci         | 0           |
| 3    | is_ci            | 0           |
| 💥   | match            | 3           |
+------+------------------+-------------+
[14:06:59]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
➡️  [match] errSecInternalComponent if not possible to prompt for keychain password
    https://github.com/fastlane/fastlane/issues/15185 [open] 150 💬
    23 Aug 2023
➡️  Could not install WWDR certificate
    https://github.com/fastlane/fastlane/issues/20960 [closed] 80 💬
    6 weeks ago
➡️  [match] Fixes Gitlab Secure Files API limit
    https://github.com/fastlane/fastlane/pull/21205 [closed] 5 💬
    04 Jul 2023
and 33 more at: [https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=✓](https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=%E2%9C%93)
🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] No code signing identity found and can not create a new one because you enabled `readonly`
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:144:in `fetch_certificate'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:73:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:42:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane.rb:41:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

Cleaning up project directory and file based variables

ERROR: Job failed: exit status 1

Any one please guide me on this. 

Thanks in advance.

**Comment by roilen** [comment]
I have the same issue, and I still can't find the answer.

**Comment by adrianilie9** [comment]
Same issue here, manually importing the certificate, key, and provisioning profile look fine in Xcode.

**Comment by muhammadhassan149** [comment]
I'm also facing same issue, any help

[12:01:52]: No code signing identity found and can not create a new one because you enabled `readonly`

+------------------------------------------------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | Verifying fastlane version      | 0           |
| 2    | ensure_git_branch               | 0           |
| 3    | ensure_git_status_clean         | 0           |
| 4    | git_pull                        | 3           |
| 5    | Switch to ios build lane        | 0           |
| 6    | Switch to ios certificates lane | 0           |
| 7    | match                           | 2           |
| 💥   | match                           | 2           |
+------+---------------------------------+-------------+

[12:01:52]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  No code signing identity found and can not create a new one because you enabled `readonly`
    https://github.com/fastlane/fastlane/issues/21679 [open] 2 💬
    a week ago

➡️  [match] errSecInternalComponent if not possible to prompt for keychain password
    https://github.com/fastlane/fastlane/issues/15185 [open] 150 💬
    23 Aug 2023

➡️  Could not install WWDR certificate
    https://github.com/fastlane/fastlane/issues/20960 [closed] 80 💬
    17 Oct 2023

and 34 more at: https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] No code signing identity found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneCrash)
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/match/lib/match/runner.rb:144:in `fetch_certificate'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/match/lib/match/runner.rb:73:in `run'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:14:in `block (2 levels) in parsing_binding'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:18:in `block (2 levels) in parsing_binding'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:24:in `block (2 levels) in parsing_binding'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/bin/fastlane:25:in `load'
        from /opt/homebrew/Cellar/fastlane/2.217.0/libexec/bin/fastlane:25:in `<main>'
muhammad@Muhammads-MacBook-Pro my_git_theq_app %

**Comment by marijnberends** [comment]
Same issue here, can't seem to find a solution. It did happen after updating the certificate

**Comment by marijnberends** [comment]
> While integrating the Fastlane, I am not create the new certificates, Just used the import command. Because we have already created the certificates earlier.
> 
> I have .p12 file and it's successfully added in the keychain. It's properly run in Xcode. while running in CI/CD using gitlab its showing this error. In the build stage working fine, but when we come to TestFlight build it's not working. (Native iOS App only)
> 
> +---------------------------------------------+ | Detected Values from './fastlane/Matchfile' | +----------------------+----------------------+ | gitlab_project | id | | gitlab_host | https://gitlab.com/ | | storage_mode | gitlab_secure_files | | type | development | +----------------------+----------------------+ +-----------------------------------------------------------------------------------+ | Summary for match 2.217.0 | +----------------------------------------+------------------------------------------+ | type | appstore | | app_identifier | ["com.bundle.id"] | | readonly | true | | generate_apple_certs | true | | skip_provisioning_profiles | false | | username | user | | team_id | id | | storage_mode | gitlab_secure_files | | git_branch | master | | shallow_clone | false | | clone_branch_directly | false | | skip_google_cloud_account_confirmation | false | | s3_skip_encryption | false | | gitlab_project | id | | gitlab_host | https://gitlab.com/ | | job_token | [token] | | keychain_name | fastlane_tmp_keychain | | force | false | | force_for_new_devices | false | | include_mac_in_profiles | false | | include_all_certificates | false | | force_for_new_certificates | false | | skip_confirmation | false | | safe_remove_certs | false | | skip_docs | false | | platform | ios | | derive_catalyst_app_identifier | false | | fail_on_name_taken | false | | skip_certificate_matching | false | | skip_set_partition_list | false | | verbose | false | +----------------------------------------+------------------------------------------+ [14:06:55]: Initializing match for GitLab project on https://gitlab.com/ [14:06:59]: Couldn't find a valid code signing identity for distribution... creating one for you now +--------------------------------------------------------------------------------------------+ | Lane Context | +---------------------------+----------------------------------------------------------------+ | DEFAULT_PLATFORM | ios | | PLATFORM_NAME | ios | | LANE_NAME | ios beta | | KEYCHAIN_PATH | ~/Library/Keychains/fastlane_tmp_keychain | | ORIGINAL_DEFAULT_KEYCHAIN | "/Library/Keychains/fastlane_tmp_keychain-db" | +---------------------------+----------------------------------------------------------------+ [14:06:59]: No code signing identity found and can not create a new one because you enabled `readonly` +---------------------------------------+ | fastlane summary | +------+------------------+-------------+ | Step | Action | Time (in s) | +------+------------------+-------------+ | 1 | default_platform | 0 | | 2 | setup_ci | 0 | | 3 | is_ci | 0 | | 💥 | match | 3 | +------+------------------+-------------+ [14:06:59]: fastlane finished with errors Looking for related GitHub issues on fastlane/fastlane... ➡️ [match] errSecInternalComponent if not possible to prompt for keychain password #15185 [open] 150 💬 23 Aug 2023 ➡️ Could not install WWDR certificate #20960 [closed] 80 💬 6 weeks ago ➡️ [match] Fixes Gitlab Secure Files API limit #21205 [closed] 5 💬 04 Jul 2023 and 33 more at: [https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=✓](https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=%E2%9C%93) 🔗 You can ⌘ + double-click on links to open them directly in your browser. bundler: failed to load command: fastlane (/usr/local/bin/fastlane) FastlaneCore::Interface::FastlaneCrash: [!] No code signing identity found and can not create a new one because you enabled `readonly` /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:144:in `fetch_certificate' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:73:in `run' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `chdir' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing' Fastfile:42:in `block (2 levels) in parsing_binding' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane.rb:41:in `call' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `chdir' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `execute' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run' /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call' /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run' /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!' /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off' /Library/Ruby/Gems/2.6.0/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>' /usr/local/bin/fastlane:23:in `load' /usr/local/bin/fastlane:23:in `<top (required)>'
> 
> Cleaning up project directory and file based variables
> 
> ERROR: Job failed: exit status 1
> 
> Any one please guide me on this.
> 
> Thanks in advance.

The issue for me was in the match password.
I've created a new repo, nuked my distribution certificates, updated the repo and reset the match by running fastlane match.
It will ask you for a password which is the match password. It will be added to your keychain under login.

**Comment by f-lab-max** [comment]
same issue here

**Comment by MarkMokhles3** [comment]
Anyone find a solution?!

**Comment by Dimon70007** [comment]
calling this for downloading updated profiles from apple developer portal
```
match(
      type: development,
      readonly: true,
      username: <myusername>,
      git_url: <mygitlab_repo_url>,
      generate_apple_certs: false,
      git_branch: master,
      shallow_clone: true,
      output_path: <my_dir_path>
    )
```
expected - fastlane match should download profiles from apple dev portal and upload they to my gitlab repo
received - error - No matching provisioning profiles found and cannot create a new one because you enabled `readonly`. Check the output above for more information.

**Comment by williamdes** [comment]
> Anyone find a solution?!

Yes, see last lines of https://github.com/fastlane/fastlane/issues/20960#issuecomment-2100198158

**Comment by maxkomarychev** [comment]
Not sure if the root issue is the same but I've noticed the same error when running `gym` after importing distribution cert and profile.

When running `fastlane match import` with latest fastlane 2.2.6 I have noticed that distribution certs and profiles were imported as *development* ones. With this `fastlane match appstore --readonly` naturally returned the error mentioned in the first ticket.

I went to match repo and manually renamed:
- `certs/development` => `certs/distribution`
- `profiles/development/Development_<bundle_id>.mobileprovision` => `profiles/development/AppStore_<bundle_id>.mobileprovision`

seems to work now 🤷
