### ISSUE TITLE
I have a Spaceship Login question and I need your help

### ISSUE THREAD

**Issue by Jacky-LinPeng** [fastlane/fastlane#21688]
------------------EN----------------------
I'm using a personal Apple ID, a non-paid developer account

When I log into my personal Apple Id in Xcode and check the Automaticlly manage siging in Xcode, it will help me create certificates and profiles automatically. Will Spaceship also help me create certificates and profiles?

When I use a paid developer account, Spaceship can correctly help me create a certificate and profile, but this time I use a personal non-paid developer account, Spaceship gives an error: Your account is in no teams (RuntimeError). I'm curious, why can Xcode create it but not Spaceship? Hope to get help from the official or experienced people
------------------CN----------------------
我使用的是个人Apple ID，非付费开发者账号

当我在Xcode登陆个人Apple Id并勾选Xcode的Automaticlly manage siging，它会帮助我自动创建证书和描述文件，Spaceship是不是也可以帮助我创建证书和描述文件？

当我使用付费的开发者账号，Spaceship可以正确的帮助我创建证书和描述文件，但是此次我使用的是个人的非付费开发者账号，Spaceship确报错： Your account is in no teams (RuntimeError)，我很好奇，为什么Xcode可以创建而Spaceship不可以呢？希望得到官方或者有经验的人的帮助

-------------------------------
<img width="916" alt="image" src="https://github.com/fastlane/fastlane/assets/15797691/13caab22-c8ad-4d26-a08e-4bfc4a81127f">
<img width="1217" alt="image" src="https://github.com/fastlane/fastlane/assets/15797691/7a5a77ca-3f6d-47eb-a403-390da6c4c2ec">
![2](https://github.com/fastlane/fastlane/assets/15797691/ed174bd8-db9a-4130-9f43-2db6f2386fbb)
![3](https://github.com/fastlane/fastlane/assets/15797691/3a100936-7a61-42ff-baea-fea9649e2abe)

# Spaceship 
## Code：
`
require "spaceship"
Spaceship.login('skodiboyy@hotmail.com', 'xxxxxxx')
Spaceship::Portal.select_team

`
## Error：
`
Available session is not valid any more. Continuing with normal login.
No teams available on the Developer Portal
You must accept an invitation to a team for it to be available
To learn more about teams and how to use them visit https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/portal/ui/select_team.rb:57:in `select_team': Your account is in no teams (RuntimeError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/portal/portal_client.rb:73:in `select_team'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/portal/spaceship.rb:43:in `select_team'
	from FreeAccount.rb:5:in `<main>'

`

**Comment by lacostej** [comment]
According to the code, there's a reference of supporting no teams

```
      # When the user has 2 step enabled, we might have to call this method again
      # This only occurs when the user doesn't have a team on App Store Connect
```

But #5834 added 8 years ago prevents from using spaceship without a team.

You could try modifying `spaceship/lib/spaceship/portal/portal_client.rb` so that it does

```
    # @return (String) The currently selected Team ID
    def team_id
      return @current_team_id if @current_team_id

      if teams.count > 1
        puts("The current user is in #{teams.count} teams. Pass a team ID or call `select_team` to choose a team. Using the first one for now.")
      end

      if teams.count == 0
        @current_team_id  = nil
      else
        @current_team_id ||= teams[0]['teamId']
      end
    end
```

and see if spaceship works for you. There might be other issues.
