### ISSUE TITLE
bundled ox breaks bundle console

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#21684]
We hardcode ox in our Gemfile to a very strict version.

It seems that some newer version of bundler are not compatible with that version.

I hit https://github.com/ohler55/ox/pull/301 when doing `bundle console`. This even on ruby 2.7.4.

```
Traceback (most recent call last):
	21: from /Users/lacostej/.rvm/gems/ruby-2.7.4/bin/bundle:23:in `<main>'
	20: from /Users/lacostej/.rvm/gems/ruby-2.7.4/bin/bundle:23:in `load'
	19: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'
	18: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	17: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'
	16: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'
	15: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	14: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'
	13: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	12: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	11: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	10: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/cli.rb:513:in `console'
	 9: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/cli/console.rb:15:in `run'
	 8: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler.rb:176:in `require'
	 7: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/runtime.rb:44:in `require'
	 6: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/runtime.rb:44:in `each'
	 5: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/runtime.rb:55:in `block in require'
	 4: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/runtime.rb:55:in `each'
	 3: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	 2: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/bundler-2.3.13/lib/bundler/runtime.rb:60:in `require'
	 1: from /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/ox-2.13.2/lib/ox.rb:79:in `<top (required)>'
/Users/lacostej/.rvm/gems/ruby-2.7.4/gems/ox-2.13.2/lib/ox.rb:79:in `require': dlopen(/Users/lacostej/.rvm/gems/ruby-2.7.4/gems/ox-2.13.2/ext/ox/ox.bundle, 0x0009): tried: '/Users/lacostej/.rvm/gems/ruby-2.7.4/gems/ox-2.13.2/ext/ox/ox.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/lacostej/.rvm/gems/ruby-2.7.4/gems/ox-2.13.2/ext/ox/ox.bundle' (no such file), '/Users/lacostej/.rvm/gems/ruby-2.7.4/gems/ox-2.13.2/ext/ox/ox.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) - /Users/lacostej/.rvm/gems/ruby-2.7.4/gems/ox-2.13.2/ext/ox/ox.bundle (LoadError)

```
A newer version of ox works, but is incompatible with ruby 2.6.

So when we drop ruby 2.6, we should relax the hard requirement on ox.

**Comment by iBotPeaches** [comment]
I think was technically fixed when I pulled your changes during the drop of Ruby 2.6 - https://github.com/fastlane/fastlane/commit/005c88780ac1cd59b281dc57194110fd1dd90e7f

As that moved away from a locked `ox` version
