### ISSUE TITLE
Fastlane match failing to create profile for OneSignalNotificationServiceExtension

### ISSUE THREAD

**Issue by markallanevans** [fastlane/fastlane#21714]
### New Issue Checklist

- [√] Updated fastlane to the latest version
- [√] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [√] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [√] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
A few days after upgrading to Xcode 15, fastlane is failing in the creation of certificates for OneSignalNotificationServiceExtension. As far as I'm aware, the only change is the update to Xcode 15 from previous successful runs.

 ```
{
  "errors" : [ {
    "id" : "a0bd721e-7e33-4ced-928a-fb3582bbbf8e",
    "status" : "409",
    "code" : "ENTITY_ERROR",
    "title" : "There is a problem with the request entity",
    "resultCode" : 35,
    "detail" : "You are not allowed to create 'iOS' profile with App ID 'ZAKJFKASKS'." // id changed
  } ]
}
```

##### Command executed
The issue fails on running fastlane match.

##### Complete output when running fastlane, including the stack trace and command used
```
Traceback (most recent call last):
        45: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `<main>'
        44: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `eval'
        43: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `<main>'
        42: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `load'
        41: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>'
        40: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        39: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        38: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        37: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        36: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        35: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        34: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        33: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        32: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        31: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        30: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        29: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        28: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        27: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        26: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        25: from Fastfile:71:in `block (2 levels) in parsing_binding'
        24: from Fastfile:33:in `update_certs'
        23: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        22: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        21: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        20: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        19: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        18: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        17: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        16: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run'
        15: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:86:in `run'
        14: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:86:in `each'
        13: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:87:in `block in run'
        12: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:87:in `loop'
        11: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:88:in `block (2 levels) in run'
        10: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:251:in `fetch_provisioning_profile'
         9: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/match/lib/match/generator.rb:110:in `generate_provisioning_profile'
         8: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/sigh/lib/sigh/manager.rb:8:in `start'
         7: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/sigh/lib/sigh/runner.rb:54:in `run'
         6: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/sigh/lib/sigh/runner.rb:184:in `create_profile!'
         5: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/connect_api/models/profile.rb:81:in `create'
         4: from /Users/markevans/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/forwardable.rb:235:in `post_profiles'
         3: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:253:in `post_profiles'
         2: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
         1: from /Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:73:in `proxy_post'
/Users/markevans/Code/wingfield/app/ios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/connect_api/api_client.rb:218:in `handle_response': \e[31m[!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "a0bd721e-7e33-4ced-928a-fb3582bbbf8e",
    "status" : "409",
    "code" : "ENTITY_ERROR",
    "title" : "There is a problem with the request entity",
    "resultCode" : 35,
    "detail" : "You are not allowed to create 'iOS' profile with App ID '------------'."
  } ]
}\e[0m
```

### Environment

<details>
  <pre> 

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.1.1                                      |
| Ruby                        | 2.7.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.39.3 (Apple Git-145)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.5/bin/fastlane         |
| Host                        | macOS 14.1.1 (23B81)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.5/lib                |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.0.1                                      |
| Swift Version               | 5.9                                         |
 </pre>
</details>

**Comment by pavelsg** [comment]
I suspect issue might be un-related to fastlane, as I get the same with pure XCode Could builds. It happens during "xcode -exportArchive" (Export archive for distribution) phase. The full error looks like this: IDEDistributionIssueSeverity=3, NSLocalizedDescription=Communication with Apple failed, NSLocalizedRecoverySuggestion=You are not allowed to create 'iOS' profile with App ID 'HUGFO2346FA'.

Interestingly enough, I can not find provided App ID anywhere in my developer account. 
@markallanevans can you please check whether App ID you are getting in the error message can be found anywhere in your appstoreconnect/developer account? Thanks!
