### ISSUE TITLE
Snapshot ignoring devices parameter

### ISSUE THREAD

**Issue by navanchauhan** [fastlane/fastlane#21752]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Although, Fastlane correctly detects that there is a Snapfile, and loads the devices correctly. It reverts to "Mac", and then erroring out 

##### Command executed

`bundle exec fastlane screenshots`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>➜  iGopherBrowser git:(main) ✗ bundle exec fastlane screenshots
[✔] 🚀
[23:58:50]: ------------------------------
[23:58:50]: --- Step: default_platform ---
[23:58:50]: ------------------------------
[23:58:50]: Driving the lane 'ios screenshots' 🚀
[23:58:51]: ---------------------------------
[23:58:51]: --- Step: capture_screenshots ---
[23:58:51]: ---------------------------------
[23:58:51]: Successfully loaded '/Users/navanchauhan/Developer/GitHub-Repos/iGopherBrowser/fastlane/Snapfile' 📄

+---------------------------------------------------------+
|       Detected Values from './fastlane/Snapfile'        |
+----------------------------+----------------------------+
| devices                    | ["iPhone 15", "iPhone 12"] |
| ios_version                | 17.2                       |
| languages                  | ["en-US"]                  |
| scheme                     | iGopherBrowserUITests      |
| clear_previous_screenshots | true                       |
| override_status_bar        | true                       |
+----------------------------+----------------------------+

[23:58:51]: Resolving Swift Package Manager dependencies...
[23:58:51]: $ xcodebuild -resolvePackageDependencies -scheme iGopherBrowserUITests -project ./iGopherBrowser.xcodeproj
[23:58:51]: ▸ Command line invocation:
[23:58:51]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme iGopherBrowserUITests -project ./iGopherBrowser.xcodeproj
[23:58:51]: ▸ User defaults from command line:
[23:58:51]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[23:58:52]: ▸ Resolve Package Graph
[23:58:52]: ▸ Resolved source packages:
[23:58:52]: ▸   swiftGopher: https://github.com/navanchauhan/swift-gopher @ master
[23:58:52]: ▸   swift-atomics: https://github.com/apple/swift-atomics.git @ 1.2.0
[23:58:52]: ▸   swift-nio: https://github.com/apple/swift-nio @ 2.62.0
[23:58:52]: ▸   swift-collections: https://github.com/apple/swift-collections.git @ 1.0.5
[23:58:52]: ▸   swift-nio-transport-services: https://github.com/apple/swift-nio-transport-services.git @ 1.20.0
[23:58:52]: ▸ resolved source packages: swiftGopher, swift-atomics, swift-nio, swift-collections, swift-nio-transport-services
[23:58:52]: $ xcodebuild -showBuildSettings -scheme iGopherBrowserUITests -project ./iGopherBrowser.xcodeproj

+-------------------------------------------------------------------------------------------------------------------+
|                                           Summary for snapshot 2.217.0                                            |
+--------------------------------------+----------------------------------------------------------------------------+
| scheme                               | iGopherBrowserUITests                                                      |
| project                              | ./iGopherBrowser.xcodeproj                                                 |
| devices                              | ["Mac"]                                                                    |
| languages                            | ["en-US"]                                                                  |
| launch_arguments                     | [""]                                                                       |
| output_directory                     | /Users/navanchauhan/Developer/GitHub-Repos/iGopherBrowser/fastlane/screen  |
|                                      | shots                                                                      |
| output_simulator_logs                | false                                                                      |
| ios_version                          | 17.2                                                                       |
| skip_open_summary                    | false                                                                      |
| skip_helper_version_check            | false                                                                      |
| clear_previous_screenshots           | true                                                                       |
| reinstall_app                        | false                                                                      |
| erase_simulator                      | false                                                                      |
| headless                             | true                                                                       |
| override_status_bar                  | true                                                                       |
| localize_simulator                   | false                                                                      |
| app_identifier                       | com.navanchauhan.iGopherBrowser                                            |
| buildlog_path                        | ~/Library/Logs/snapshot                                                    |
| clean                                | false                                                                      |
| number_of_retries                    | 1                                                                          |
| stop_after_first_error               | false                                                                      |
| result_bundle                        | false                                                                      |
| concurrent_simulators                | true                                                                       |
| disable_slide_to_type                | false                                                                      |
| skip_package_dependencies_resolution | false                                                                      |
| disable_package_automatic_updates    | false                                                                      |
| xcodebuild_formatter                 | xcpretty                                                                   |
| use_system_scm                       | false                                                                      |
| xcode_path                           | /Applications/Xcode.app                                                    |
+--------------------------------------+----------------------------------------------------------------------------+

[23:58:54]: Clearing previously generated screenshots
[23:58:54]: Building and running project - this might take some time...
+------------------------------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | ios             |
| LANE_NAME        | ios screenshots |
+------------------+-----------------+

+------------------------------------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 💥   | capture_screenshots | 3           |
+------+---------------------+-------------+

[23:58:54]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  snapshot doesn't seem to work for macOS apps
    https://github.com/fastlane/fastlane/issues/18709 [closed] 16 💬
    6 weeks ago

➡️  Snapshot with Catalyst fails at `latest_simulator_version_for_device`
    https://github.com/fastlane/fastlane/issues/18663 [closed] 4 💬
    21 Nov 2021

➡️  Upload to play store error - NoMethodError: [!] undefined method `each_with_index' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/18403 [closed] 57 💬
    24 May 2021

and 3 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60os_version%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/fastlane)
/Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/device_manager.rb:134:in `latest_simulator_version_for_device': [!] undefined method `os_version' for nil:NilClass (NoMethodError)

                  .os_version
                  ^^^^^^^^^^^
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `block (3 levels) in take_screenshots_simultaneously'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `each'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `group_by'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `block (2 levels) in take_screenshots_simultaneously'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each_with_index'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `block in take_screenshots_simultaneously'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `each'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `take_screenshots_simultaneously'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/snapshot/lib/snapshot/runner.rb:46:in `work'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/capture_ios_screenshots.rb:14:in `run'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:21:in `block (2 levels) in parsing_binding'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/fastlane:25:in `load'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/fastlane:25:in `<top (required)>'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:451:in `exec'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in `start'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/navanchauhan/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 14.0                                                     |
| Ruby                        | 3.2.2                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.39.3 (Apple Git-145)                       |
| Installation Source         | ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/fastlane |
| Host                        | macOS 14.0 (23A344)                                      |
| Ruby Lib Dir                | ~/.rbenv/versions/3.2.2/lib                              |
| OpenSSL Version             | OpenSSL 3.2.0 23 Nov 2023                                |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 15.0                                                     |
| Swift Version               | 5.9                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "iGopherBrowserUITests")
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.navanchauhan.iGopherBrowser") # The bundle identifier of your app
apple_id("XXX@icloud.com") # Your Apple Developer Portal username

itc_team_id("XXX") # App Store Connect Team ID
team_id("XXX") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

<details><summary>`./fastlane/Snapfile`</summary>

```ruby
# Uncomment the lines below you want to change by removing the # in the beginning

devices(["iPhone 15","iPhone 12"])
ios_version("17.2")
languages(["en-US",])
scheme("iGopherBrowserUITests")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
```

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.217.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.0.2        |
| bundler                         | 2.5.3        |
| pathname                        | 0.2.1        |
| rake                            | 13.1.0       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.6        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.3.0        |
| aws-partitions                  | 1.873.0      |
| aws-sigv4                       | 1.8.0        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.190.1      |
| aws-sdk-kms                     | 1.75.0       |
| aws-sdk-s3                      | 1.142.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.5        |
| domain_name                     | 0.6.20231109 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.108.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.7        |
| gh_inspector                    | 1.1.3        |
| google-cloud-env                | 2.1.0        |
| jwt                             | 2.7.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.18.0       |
| googleauth                      | 1.9.1        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.5        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.2       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.29.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.1        |
| google-cloud-storage            | 1.45.0       |
| json                            | 2.7.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.23.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2023-12-23**
</details>

**Comment by tunds** [comment]
Are there any updates on this I'm experiencing this behaviour as well, even if I pass in an explicit list of devices. Fastlane defaults to `Mac`

**Comment by Jon-Schneider** [comment]
I'm experiencing the same thing. Has anyone found a workaround?

**Comment by Jon-Schneider** [comment]
I found a workaround in my case, thanks to #21911. I'm setting up Fastlane and Snapshots on a Catalyst app, and either by default or on accident Mac got added to the Supported Destinations in my (newly added) Snapshots UI Test framework. Removing it (so only iOS targets remained) fixed it for me.

**Comment by huven** [comment]
The cause is in

snapshot/lib/snapshot/detect_values.rb

line 69 should be changed to read

      elsif config[:devices].nil? && Snapshot.project.mac?

as it currently is, it just always changes the devices value if the project is Mac enabled...

Is anybody familiar with sending the procedure for sending the PR for this?

**Comment by matrouthier** [comment]
Thank you @huven for finding the solution!  Now can we please merge it?  Would be greatly appreciated.
