### ISSUE TITLE
fastlane finished with errors

### ISSUE THREAD

**Issue by Dssssds** [fastlane/fastlane#21756]
```
$ bundle exec fastlane assemble
[✔] 🚀 
+---------------------------------------------------------------------------+
|                               Used plugins                                |
+----------------------------------------+---------+------------------------+
| Plugin                                 | Version | Action                 |
+----------------------------------------+---------+------------------------+
| fastlane-plugin-update_android_strings | 0.1.0   | update_android_strings |
+----------------------------------------+---------+------------------------+

[16:10:46]: ------------------------------
[16:10:46]: --- Step: default_platform ---
[16:10:46]: ------------------------------
[16:10:46]: Driving the lane 'android assemble' 🚀
[16:10:46]: ------------------------------------
[16:10:46]: --- Step: update_android_strings ---
[16:10:46]: ------------------------------------
+-------------------------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | android          |
| PLATFORM_NAME    | android          |
| LANE_NAME        | android assemble |
+------------------+------------------+
[16:10:46]: the argument to replace_text() must be a String

+---------------------------------------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 💥   | update_android_strings | 0           |
+------+------------------------+-------------+

[16:10:46]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
        32: from /Users/ds/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'
        31: from /Users/ds/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'
        30: from /Users/ds/.rvm/gems/ruby-2.7.5/bin/fastlane:23:in `<main>'
        29: from /Users/ds/.rvm/gems/ruby-2.7.5/bin/fastlane:23:in `load'
        28: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>'
        27: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        26: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        25: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        24: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        23: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        22: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        21: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        20: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        19: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        18: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        17: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        16: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        15: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        14: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        13: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        12: from Fastfile:22:in `block (2 levels) in parsing_binding'
        11: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        10: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
         9: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
         8: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
         7: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         6: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
         5: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         4: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-plugin-update_android_strings-0.1.0/lib/fastlane/plugin/update_android_strings/actions/update_android_strings_action.rb:36:in `run'
         3: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-plugin-update_android_strings-0.1.0/lib/fastlane/plugin/update_android_strings/helper/update_android_strings_helper.rb:11:in `updateXml'
         2: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-plugin-update_android_strings-0.1.0/lib/fastlane/plugin/update_android_strings/helper/update_android_strings_helper.rb:11:in `each'
         1: from /Users/ds/.rvm/gems/ruby-2.7.5/gems/fastlane-plugin-update_android_strings-0.1.0/lib/fastlane/plugin/update_android_strings/helper/update_android_strings_helper.rb:13:in `block in updateXml'
/Users/ds/.rvm/gems/ruby-2.7.5/gems/ox-2.14.17/lib/ox/element.rb:101:in `replace_text': \e[31m[!] the argument to replace_text() must be a String\e[0m (RuntimeError)
```
如何处理这个问题呢。

**Comment by lacostej** [comment]
Hello, you issue is triggered in this file https://github.com/BANG88/fastlane-plugin-update_android_strings/blob/master/lib/fastlane/plugin/update_android_strings/helper/update_android_strings_helper.rb#L13 which is part of the fastlane-plugin-update_android_strings plugin. I don't think thi is a fastlane problem.
