### ISSUE TITLE
[Regression] Scan fails when no device found

### ISSUE THREAD

**Issue by arc-v2** [fastlane/fastlane#21768]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x]  I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x]  I read [docs.fastlane.tools](https://docs.fastlane.tools/)
- [x]  I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

Breaking version: 2.218.0
Last working version: 2.217.0

### Regression Description

It happens when device name provided did not match the preinstalled simulators e.g. Xcode 14.2 doesn't have the 'iPhone 12' device present by default.

              Similar issue is present with **_scan_** too. Not sure if the cause is same but that is also a regression with similar stack trace. 

```
fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
➡️  Scan Support for connected devices
    https://github.com/fastlane/fastlane/pull/5159 [closed] 38 💬
    22 Sep 2017
🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/xyz/.gem/gems/fastlane-2.218.0/scan/lib/scan/detect_values.rb:295:in `block in detect_destination': [!] undefined method `os_type' for nil:NilClass (NoMethodError)
	from /Users/xyz/.gem/gems/fastlane-2.218.0/scan/lib/scan/detect_values.rb:295:in `map'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/scan/lib/scan/detect_values.rb:295:in `detect_destination'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/scan/lib/scan/detect_values.rb:53:in `set_additional_default_values'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/scan/lib/scan/module.rb:17:in `config='
	from /Users/xyz/.gem/gems/fastlane-2.218.0/scan/lib/scan/manager.rb:10:in `work'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/actions/run_tests.rb:17:in `run'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:57:in `block (2 levels) in parsing_binding'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/xyz/.gem/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/xyz/.gem/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/xyz/.gem/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/xyz/.gem/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/xyz/.gem/gems/fastlane-2.218.0/bin/fastlane:23:in `<top (required)>'
	from /Users/xyz/.gem/bin/fastlane:23:in `load'
	from /Users/xyz/.gem/bin/fastlane:23:in `<main>'
	
```
	
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 13.6.2                                      |
| Ruby                        | 3.2.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.43.0                          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | macOS 13.6.2 (22G320)                       |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.2.2_1/lib       |
| OpenSSL Version             | OpenSSL 3.1.1 30 May 2023                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.2                                        |
| Swift Version               | 5.7.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

_Originally posted by @vivek-dtdl in https://github.com/fastlane/fastlane/issues/21762#issuecomment-1875320286_

**Comment by arc-v2** [comment]
This seems to be introduced with https://github.com/fastlane/fastlane/pull/21677.
