### ISSUE TITLE
The provided entity includes an unknown attribute - 'availableInNewTerritories' is not an attribute on the resource 'apps' - /data/attributes/availableInNewTerritories

### ISSUE THREAD

**Issue by gabma** [fastlane/fastlane#21820]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running fastlane 2.217.0 and  2.219.0 fail uploading.
Upload used to work until today. No changes have been made to the script or store settings.

##### Complete output when running fastlane, including the stack trace and command used

```
/usr/local/bin/fastlane ios upload build:/Users/agent00/BuildServer/production/_current-artifacts/FlowerGarden-2.74.0-ios-store-469747-build.ipa metadata:/Users/agent00/BuildServer/production/_current-artifacts/metadata review:false submit:false package:dk.tactile.lilysgarden org:tactile_games_aps --verbose
```

<details>
  <pre> 
2024-01-18 13:10:25,106 [INFO]: INFO [2024-01-18 13:10:25.10]: Uploading app review information to App Store Connect
2024-01-18 13:10:26,893 [INFO]: INFO [2024-01-18 13:10:26.89]: Setting the app's age rating...
2024-01-18 13:10:28,241 [INFO]: INFO [2024-01-18 13:10:28.24]: App has no prices yet... Enabling all countries in App Store Connect
2024-01-18 13:10:31,269 [INFO]: WARN [2024-01-18 13:10:31.26]: Lane Context:
2024-01-18 13:10:31,272 [INFO]: INFO [2024-01-18 13:10:31.26]: {:PLATFORM_NAME=>:ios, :LANE_NAME=>"ios upload"}
2024-01-18 13:10:31,273 [INFO]: ERROR [2024-01-18 13:10:31.26]: The provided entity includes an unknown attribute - 'availableInNewTerritories' is not an attribute on the resource 'apps' - /data/attributes/availableInNewTerritories
2024-01-18 13:10:31,274 [INFO]: The provided entity includes an unknown relationship - 'prices' is not a relationship on the resource 'apps' - /data/relationships/prices
2024-01-18 13:10:31,274 [INFO]: The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories
2024-01-18 13:10:31,283 [INFO]: 
2024-01-18 13:10:31,285 [INFO]: +------------------------------------------+
2024-01-18 13:10:31,285 [INFO]: |             fastlane summary             |
2024-01-18 13:10:31,286 [INFO]: +------+---------------------+-------------+
2024-01-18 13:10:31,286 [INFO]: | Step | Action              | Time (in s) |
2024-01-18 13:10:31,287 [INFO]: +------+---------------------+-------------+
2024-01-18 13:10:31,288 [INFO]: | 1    | update_fastlane     | 0           |
2024-01-18 13:10:31,288 [INFO]: | 💥   | upload_to_app_store | 27          |
2024-01-18 13:10:31,289 [INFO]: +------+---------------------+-------------+
2024-01-18 13:10:31,290 [INFO]: 
2024-01-18 13:10:31,291 [INFO]: ERROR [2024-01-18 13:10:31.28]: fastlane finished with errors
2024-01-18 13:10:31,291 [INFO]: 
2024-01-18 13:10:31,292 [INFO]: Looking for related GitHub issues on fastlane/fastlane...
2024-01-18 13:10:31,292 [INFO]: Search query: The provided entity includes an unknown attribute - 'availableInNewTerritories' is not an attribute on the resource 'apps' - /data/attributes/availableInNewTerritories
2024-01-18 13:10:31,292 [INFO]: The provided entity includes an unknown relationship - 'prices' is not a relationship on the resource 'apps' - /data/relationships/prices
2024-01-18 13:10:31,293 [INFO]: The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories
2024-01-18 13:10:31,293 [INFO]: 
2024-01-18 13:10:31,293 [INFO]: URL: https://api.github.com/search/issues?q=The%20provided%20entity%20includes%20an%20unknown%20attribute%20-%20%27availableInNewTerritories%27%20is%20not%20an%20attribute%20on%20the%20resource%20%27apps%27%20-%20%2Fdata%2Fattributes%2FavailableInNewTerritories%0AThe%20provided%20entity%20includes%20an%20unknown%20relationship%20-%20%27prices%27%20is%20not%20a%20relationship%20on%20the%20resource%20%27apps%27%20-%20%2Fdata%2Frelationships%2Fprices%0AThe%20provided%20entity%20includes%20an%20unknown%20relationship%20-%20%27availableTerritories%27%20is%20not%20a%20relationship%20on%20the%20resource%20%27apps%27%20-%20%2Fdata%2Frelationships%2FavailableTerritories+repo:fastlane/fastlane
2024-01-18 13:10:31,488 [INFO]: ERROR [2024-01-18 13:10:31.48]: [31mError finding relevant GitHub issues: undefined method `map' for nil:NilClass[0m
2024-01-18 13:10:31,491 [INFO]: /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/api_client.rb:223:in `handle_response': [31m[!] The provided entity includes an unknown attribute - 'availableInNewTerritories' is not an attribute on the resource 'apps' - /data/attributes/availableInNewTerritories (Spaceship::UnexpectedResponse)
2024-01-18 13:10:31,493 [INFO]: The provided entity includes an unknown relationship - 'prices' is not a relationship on the resource 'apps' - /data/relationships/prices
2024-01-18 13:10:31,494 [INFO]: The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories[0m
2024-01-18 13:10:31,496 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/api_client.rb:136:in `patch'
2024-01-18 13:10:31,497 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:209:in `patch_app'
2024-01-18 13:10:31,498 [INFO]: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `patch_app'
2024-01-18 13:10:31,499 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/models/app.rb:109:in `update'
2024-01-18 13:10:31,500 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/deliver/lib/deliver/upload_price_tier.rb:38:in `upload'
2024-01-18 13:10:31,501 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/deliver/lib/deliver/runner.rb:161:in `upload_metadata'
2024-01-18 13:10:31,502 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/deliver/lib/deliver/runner.rb:61:in `run'
2024-01-18 13:10:31,503 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
2024-01-18 13:10:31,503 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
2024-01-18 13:10:31,504 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
2024-01-18 13:10:31,505 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
2024-01-18 13:10:31,506 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
2024-01-18 13:10:31,507 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
2024-01-18 13:10:31,507 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
2024-01-18 13:10:31,508 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2024-01-18 13:10:31,509 [INFO]: 	from Fastfile:47:in `block (2 levels) in parsing_binding'
2024-01-18 13:10:31,509 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane.rb:41:in `call'
2024-01-18 13:10:31,510 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
2024-01-18 13:10:31,511 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
2024-01-18 13:10:31,511 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
2024-01-18 13:10:31,512 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
2024-01-18 13:10:31,513 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
2024-01-18 13:10:31,514 [INFO]: 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
2024-01-18 13:10:31,514 [INFO]: Error uploading to fastlane: 1
</pre>
</details>

### Environment

<details>
  <pre>[✔] 🚀 
[09:23:26]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:23:27]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 13.6.3                                                         |
| Ruby                        | 2.6.10                                                         |
| Bundler?                    | false                                                          |
| Git                         | git version 2.39.2 (Apple Git-143)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 13.6.3 (22G436)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 3.3.6                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-14.3.1.app/Contents/Developer/             |
| Xcode Version               | 14.3.1                                                         |
| Swift Version               | 5.8.1                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.219.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-cloud-env                | 1.6.0        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| public_suffix                   | 5.0.3        |
| addressable                     | 2.8.5        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.6.1        |
| aws-partitions                  | 1.852.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.186.0      |
| aws-sdk-kms                     | 1.72.0       |
| aws-sdk-s3                      | 1.136.0      |
| bundler                         | 2.1.4        |
| CFPropertyList                  | 3.0.3        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.104.0      |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.7        |
| webrick                         | 1.7.0        |
| rexml                           | 3.2.6        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.7.1        |
| signet                          | 0.18.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.2       |
| google-apis-androidpublisher_v3 | 0.52.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.29.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.45.0       |
| unf_ext                         | 0.0.9.1      |
| json                            | 2.5.1        |
| mini_magick                     | 4.12.0       |
| plist                           | 3.7.0        |
| simctl                          | 1.6.10       |
| unicode-display_width           | 2.5.0        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.23.0       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.3        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2024-01-18**
</details>
[09:23:32]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[09:23:32]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)
y
[09:23:43]: Successfully copied markdown into your clipboard 🎨
[09:23:43]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅</pre>
</details>

**Comment by xalikoutis** [comment]
same here

**Comment by bvanderplanck** [comment]
Getting the exact same issue; anyone has a workaround ?

**Comment by crsantos** [comment]
Same as https://github.com/fastlane/fastlane/issues/21819

**Comment by gabma** [comment]
We eventually solved this by removing `price_tier: 0` from our fastlane configuration, and running 2.219.0

**Comment by LinusU** [comment]
Removing `price_tier` solved this for us as well, but maybe this issue should remain open since one might want to change the `price_tier`...

**Comment by tian13019692331** [comment]
Can everyone still set prices after the update

**Comment by muhammad67uzair** [comment]
i've tried using fastlane version 2.221.1, 2.219.0, 2.213.0, but still get this error.

**Comment by lukhol** [comment]
Any updates on this one?
