### ISSUE TITLE
Fastlane Precheck Failure - Unexpected Response

### ISSUE THREAD

**Issue by thejeff77** [fastlane/fastlane#21866]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane precheck fails with unexpected error. 

##### Command executed
`bundle exec fastlane precheck`

##### Complete output when running fastlane, including the stack trace and command used

```
developer@developer-MacBook-Pro someApp % bundle exec fastlane precheck

[✔] 🚀 

+------------------------------------------------------+
|             Summary for precheck 2.219.0             |
+--------------------------+---------------------------+
| app_identifier           | myappid |
| username                 | developer@gmail.com  |
| team_id                  | 119057288                 |
| platform                 | ios                       |
| default_rule_level       | error                     |
| include_in_app_purchases | true                      |
| use_live                 | false                     |
+--------------------------+---------------------------+

[11:05:22]: Starting login with user 'developer@gmail.com'
[11:05:24]: Successfully logged in
[11:05:24]: Checking app for precheck rule violations
[11:05:27]: Reading in-app purchases. If you have a lot, this might take a while
[11:05:27]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`

Looking for related GitHub issues on fastlane/fastlane...

➡️  [spaceship] Creation of in-app purchases returns NotFound error
    https://github.com/fastlane/fastlane/issues/19140 [open] 10 💬
    04 Aug 2021

➡️  create InAppPurchase product failure
    https://github.com/fastlane/fastlane/issues/20933 [open] 3 💬
    24 Jun 2023

➡️  deliver issue - Spaceship::UnexpectedResponse:
    https://github.com/fastlane/fastlane/issues/21062 [open] 0 💬
    18 Feb 2023

and 22 more at: https://github.com/fastlane/fastlane/search?q=%7B%22data%22%3D%3Enil%2C%20%22messages%22%3D%3E%7B%22warn%22%3D%3Enil%2C%20%22error%22%3D%3E%5B%22Not%20Found%22%5D%2C%20%22info%22%3D%3Enil%7D%2C%20%22statusCode%22%3D%3E%22ERROR%22%7D&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Spaceship::UnexpectedResponse: [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/client.rb:793:in `parse_response'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1320:in `load_iap'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/tunes/iap_list.rb:59:in `edit'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/rule_processor.rb:166:in `block in generate_app_items_to_check'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/rule_processor.rb:165:in `each'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/rule_processor.rb:165:in `generate_app_items_to_check'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/rule_processor.rb:47:in `process_app_and_version'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/runner.rb:126:in `check_for_rule_violations'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/runner.rb:58:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/commands_generator.rb:42:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/commands_generator.rb:72:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/commands_generator.rb:20:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 14.3.1                                                         |
| Ruby                        | 2.6.10                                                         |
| Bundler?                    | false                                                          |
| Git                         | git version 2.43.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 14.3.1 (23D60)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 3.3.6                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 15.2                                                           |
| Swift Version               | 5.9.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"

  lane :release do
    #increment_build_number(xcodeproj: "SomeApp.xcodeproj")
    #increment_version_number(
    #	bump_type: "patch",
    #	xcodeproj: "SomeApp.xcodeproj"
    #)
    
    #tests
    build_app(scheme: "SomeApp")
    deliver(
      skip_screenshots: true,
      app_identifier: "com.MFE.SomeApp",
      #individual_metadata_items: ['name', 'subtitle']
    )
  end

  lane :releasefull do
    
    build_app(scheme: "SomeApp")
    deliver(
      # overwrite_screenshots: true,
      skip_screenshots: false,
      app_identifier: "com.MFE.SomeApp",
    )
  end

  lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end

  lane :upload_screenshots do
    upload_to_app_store
  end

  # This lane doesn't work
  lane :coverage do
    
    tests
    
    xcov(
      #workspace: "SomeApp.xcodeproj",
      #scheme: "SomeAppTests",
      output_directory: "xcov_output",
      xccov_file_direct_path: ""
    )  
  end

  lane :tests do
    run_tests(
	open_report: true,
	scheme: "SomeAppTests",
	# test_without_building: true,
	buildlog_path: "./fastlane/fastlane-buildlog",
	# derived_data_path: "~/Library/Developer/Xcode/DerivedData",
	devices: ["iPad (9th generation)"],
        code_coverage: true,
        only_testing: ["SomeAppTests/PurchaseIdsTests",
	  "SomeAppTests/TranslateCacheTests"])
  end

  lane :build do
    build_app(scheme: "SomeApp")
  end

  

  lane :upload_metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      copyright: "Copyright Developer 2020",
      precheck_include_in_app_purchases: true,
    )
  end

  lane :beta do
    changelog = prompt(text: "Changelog: ")
    tests
    #sync_code_signing(type: "appstore")    # see code signing guide for more information
    build_app(scheme: "SomeApp")
    upload_to_testflight(
      groups: ["Customers"],
      distribute_external: true
    )
    #slack(message: "Successfully distributed a new beta build")
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("someApp") # The bundle identifier of your app
apple_id("developer@gmail.com") # Your Apple email address

itc_team_id("119057288") # App Store Connect Team ID
team_id("ZAR5QX7MAH") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.219.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| bundler                         | 1.17.2       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday_middleware              | 1.2.0        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-cloud-env                | 1.6.0        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.6        |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-partitions                  | 1.889.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.191.1      |
| aws-sdk-kms                     | 1.77.0       |
| aws-sdk-s3                      | 1.143.0      |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| excon                           | 0.109.0      |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| multipart-post                  | 2.4.0        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.9.1      |
| fastimage                       | 2.3.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.7.1        |
| signet                          | 0.18.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.29.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.1        |
| google-cloud-storage            | 1.45.0       |
| json                            | 2.7.1        |
| mini_magick                     | 4.12.0       |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| simctl                          | 1.6.10       |
| unicode-display_width           | 2.5.0        |
| tty-screen                      | 0.8.2        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.24.0       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.3        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2024-02-11**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by lacostej** [comment]
Hello, this indeed looks like either a problem in fastlane, or something in the Apple ecosystem we do not support.

Could you run the command again with `VERBOSE=true bundle exec fastlane precheck` to see what extra output we get?

it would be useful to pinpoint if this fails for all IAPs or just some in particular. The verbose mode could help us find out which IAP it fails with. You can also then check your appstoreconnect setup to see if you see something special for that IAP.

**Comment by thejeff77** [comment]
@lacostej  thanks for the response.

Running `bundle exec fastlane precheck --verbose` gives me pretty much the same output. See below.

Additional feedback regarding this issue:
- Precheckfile template does not include a way to skip in app purchase verification.
- Error handling doesn't seem to be working very well - unexpected errors shouldn't block the release.
- The string `You can disable IAP checking by setting the include_in_app_purchases flag to false` is very unhelpful, this should be a link to some documentation telling how to pass this string. For instance, in the lanes, its called something different: `precheck_include_in_app_purchases: false`, ++ nothing in the Precheckfile for this. A note to use `--include_in_app_purchases=false` would be helpful in the command itself, but often precheck isn't run on its own, its part of a deliver action.

Thanks again let me know if there is anything else I can provide to help.

 ```
developer@developer-MacBook-Pro  ~/Projects/myApp   master ●  bundle exec fastlane precheck --verbose                                                                   ✔  728  12:52:28 
[✔] 🚀 
Successfully loaded Appfile at path '/Users/developer/Projects/someProject/fastlane/Appfile'
- app_identifier: 'com.MFE.SomeApp'
- apple_id: 'developer@gmail.com'
- itc_team_id: '111114'
- team_id: 'someTeam'
-------
INFO [2024-02-17 12:53:01.42]: Successfully loaded '/Users/developer/Projects/someApp/fastlane/Precheckfile' 📄

+------------------------------------------------+
| Detected Values from './fastlane/Precheckfile' |
+--------------------------+---------------------+
| negative_apple_sentiment | {:level=>:error}    |
| curse_words              | {:level=>:error}    |
| future_functionality     | {:level=>:error}    |
| other_platforms          | {:level=>:error}    |
| placeholder_text         | {:level=>:error}    |
| test_words               | {:level=>:error}    |
| unreachable_urls         | {:level=>:error}    |
+--------------------------+---------------------+


+------------------------------------------------------------+
|                Summary for precheck 2.219.0                |
+--------------------------------+---------------------------+
| app_identifier                 | com.MFE.SomeApp |
| username                       | developer@gmail.com  |
| team_id                        | 111111                 |
| platform                       | ios                       |
| default_rule_level             | error                     |
| include_in_app_purchases       | true                      |
| use_live                       | false                     |
| negative_apple_sentiment.level | error                     |
| placeholder_text.level         | error                     |
| other_platforms.level          | error                     |
| future_functionality.level     | error                     |
| test_words.level               | error                     |
| curse_words.level              | error                     |
| unreachable_urls.level         | error                     |
+--------------------------------+---------------------------+

INFO [2024-02-17 12:53:01.43]: Starting login with user 'developer@gmail.com'
Reading keychain entry, because either user or password were empty
Loading session from '/Users/developer/.fastlane/spaceship/developer@gmail.com/cookie'
Looking for App Store Connect Team with ID 11111
INFO [2024-02-17 12:53:02.81]: Successfully logged in
INFO [2024-02-17 12:53:02.81]: Checking app for precheck rule violations
INFO [2024-02-17 12:53:05.91]: Reading in-app purchases. If you have a lot, this might take a while
INFO [2024-02-17 12:53:05.91]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`

Looking for related GitHub issues on fastlane/fastlane...
Search query: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}

URL: https://api.github.com/search/issues?q=%7B%22data%22%3D%3Enil%2C%20%22messages%22%3D%3E%7B%22warn%22%3D%3Enil%2C%20%22error%22%3D%3E%5B%22Not%20Found%22%5D%2C%20%22info%22%3D%3Enil%7D%2C%20%22statusCode%22%3D%3E%22ERROR%22%7D+repo:fastlane/fastlane
➡️  Fastlane Precheck Failure - Unexpected Response
    https://github.com/fastlane/fastlane/issues/21866 [open] 1 💬
    13 hours ago

➡️  create InAppPurchase product failure
    https://github.com/fastlane/fastlane/issues/20933 [open] 3 💬
    24 Jun 2023

➡️  [spaceship] Creation of in-app purchases returns NotFound error
    https://github.com/fastlane/fastlane/issues/19140 [closed] 11 💬
    13 hours ago

and 23 more at: https://github.com/fastlane/fastlane/search?q=%7B%22data%22%3D%3Enil%2C%20%22messages%22%3D%3E%7B%22warn%22%3D%3Enil%2C%20%22error%22%3D%3E%5B%22Not%20Found%22%5D%2C%20%22info%22%3D%3Enil%7D%2C%20%22statusCode%22%3D%3E%22ERROR%22%7D&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Spaceship::UnexpectedResponse: [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/client.rb:793:in `parse_response'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1320:in `load_iap'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/tunes/iap_list.rb:59:in `edit'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/rule_processor.rb:166:in `block in generate_app_items_to_check'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/rule_processor.rb:165:in `each'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/rule_processor.rb:165:in `generate_app_items_to_check'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/rule_processor.rb:47:in `process_app_and_version'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/runner.rb:126:in `check_for_rule_violations'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/runner.rb:58:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/commands_generator.rb:42:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/commands_generator.rb:72:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/precheck/lib/precheck/commands_generator.rb:20:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

**Comment by lacostej** [comment]
> Running `bundle exec fastlane precheck --verbose` gives me pretty much the same output. See below.

`bundle exec fastlane precheck --verbose` isn't the same as  `VERBOSE=true bundle exec fastlane precheck`

The `VERBOSE=true` changes the [way spaceship logs](https://github.com/fastlane/fastlane/blob/8c4903cfb1e2fefe8b06d69bd0c4f2bc9874eaf4/spaceship/lib/spaceship/client.rb#L244-L258).

**Comment by thejeff77** [comment]
Sorry for being dense.. but the first word on a shell is the command. There is no shell command called VERBOSE=true. Is this an environment setting I'll need to have on env or is this a setting in a fastlane file somewhere?

**Comment by thejeff77** [comment]
I've emailed this output to you. Thanks 👍

**Comment by thejeff77** [comment]
@lacostej I forgot where we left off on this. Somehow this is still happening

Curious how I set `include_in_app_purchases: false` globally in Fastfile or for anytime I run `fastlane precheck`

**Comment by BastianKusserow** [comment]
@thejeff77 did you ever found out what was causing the issues? We are getting the same error at the moment.
