### ISSUE TITLE
Apple changed AppStatus 'Ready for Sales' to 'Ready for Distribution'

### ISSUE THREAD

**Issue by naoigcat** [fastlane/fastlane#21877]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

An error occurs when `fastlane deliver download_metadata` is executed for an app whose status on AppStoreConnect is `Ready for Distribution`.

I think this is happening because [Apple changed the wording of AppStatus](https://developer.apple.com/news/releases/?id=02082024e).

> Ready for Sale has been renamed to Ready for Distribution, and now indicates that your app can be published. To view if your app is available on the App Store, visit Pricing and Availability.

##### Command executed

```sh
fastlane deliver download_metadata --app_identifier xxxxxx --username xxxxxx --team_id xxxxxx --force
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
[✔] 🚀 
[16:33:17]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:33:18]: Login to App Store Connect (xxxxxx)
[16:33:19]: Login successful

+----------------------------------------------------------------+
|                    deliver 2.219.0 Summary                     |
+--------------------------------------+-------------------------+
| app_identifier                       | xxxxxx                  |
| username                             | xxxxxx                  |
| team_id                              | xxxxxx                  |
| metadata_path                        | ./metadata              |
| force                                | true                    |
| screenshots_path                     | ./screenshots           |
| platform                             | ios                     |
| edit_live                            | false                   |
| use_live_version                     | false                   |
| skip_binary_upload                   | false                   |
| skip_screenshots                     | false                   |
| skip_metadata                        | false                   |
| skip_app_version_update              | false                   |
| overwrite_screenshots                | false                   |
| sync_screenshots                     | false                   |
| submit_for_review                    | false                   |
| verify_only                          | false                   |
| reject_if_possible                   | false                   |
| phased_release                       | false                   |
| reset_ratings                        | false                   |
| run_precheck_before_submit           | true                    |
| precheck_default_rule_level          | warn                    |
| ignore_language_directory_validation | false                   |
| precheck_include_in_app_purchases    | true                    |
+--------------------------------------+-------------------------+

Looking for related GitHub issues on fastlane/fastlane...

➡️  fastlint init crash
    https://github.com/fastlane/fastlane/issues/144 [closed] 3 💬
    22 Sep 2016

➡️  'sh' isn't available in custom actions
    https://github.com/fastlane/fastlane/issues/193 [closed] 4 💬
    22 Sep 2016

➡️  Cannot add_git_tag with my own provided tag name
    https://github.com/fastlane/fastlane/issues/180 [closed] 5 💬
    06 Dec 2016

and 20142 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60get_app_info_localizations%27%20for%20nil%0A%0A%20%20%20%20%20%20app_info_localizations%20%3D%20app_info.get_app_info_localizations%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/deliver/lib/deliver/setup.rb:70:in `generate_metadata_files': \e[31m[!] undefined method `get_app_info_localizations' for nil:NilClass (NoMethodError)

      app_info_localizations = app_info.get_app_info_localizations
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^\e[0m
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/deliver/lib/deliver/commands_generator.rb:181:in `block (2 levels) in run'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/bin/fastlane:25:in `load'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/bin/fastlane:25:in `<main>'
/Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/deliver/lib/deliver/setup.rb:70:in `generate_metadata_files': undefined method `get_app_info_localizations' for nil:NilClass (NoMethodError)

      app_info_localizations = app_info.get_app_info_localizations
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/deliver/lib/deliver/commands_generator.rb:181:in `block (2 levels) in run'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/bin/fastlane:25:in `load'
        from /Users/xxx/.asdf/installs/ruby/3.1.4/bin/fastlane:25:in `<main>'
</pre>
</details>

### Environment

<details>
<pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 14.3                                               |
| Ruby                        | 3.1.4                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.43.2                                 |
| Installation Source         | ~/.asdf/installs/ruby/3.1.4/bin/fastlane           |
| Host                        | macOS 14.3 (23D56)                                 |
| Ruby Lib Dir                | ~/.asdf/installs/ruby/3.1.4/lib                    |
| OpenSSL Version             | OpenSSL 3.1.4 24 Oct 2023                          |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-14.2.0.app/Contents/Developer/ |
| Xcode Version               | 14.2                                               |
| Swift Version               | 5.7.2                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.219.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday_middleware              | 1.2.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-cloud-env                | 1.6.0        |
| http-cookie                     | 1.0.5        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.2        |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.6        |
| base64                          | 0.2.0        |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-partitions                  | 1.892.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.191.2      |
| aws-sdk-kms                     | 1.77.0       |
| aws-sdk-s3                      | 1.143.0      |
| bundler                         | 2.4.22       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| excon                           | 0.109.0      |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| multipart-post                  | 2.4.0        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| fastimage                       | 2.3.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.7.1        |
| signet                          | 0.19.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.31.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.1        |
| google-cloud-storage            | 1.47.0       |
| domain_name                     | 0.6.20240107 |
| json                            | 2.7.1        |
| mini_magick                     | 4.12.0       |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| simctl                          | 1.6.10       |
| unicode-display_width           | 2.5.0        |
| tty-screen                      | 0.8.2        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.24.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.1.0        |
| securerandom                    | 0.2.0        |
| uri                             | 0.12.1       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.2        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.2.0        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.7.2        |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| nokogiri                        | 1.15.4       |
| racc                            | 1.7.3        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 5.1.2        |
| ox                              | 2.13.2       |
</details>

*generated on:* **2024-02-17**
</details>
</pre>
</details>

**Comment by lacostej** [comment]
oh well. We have to fix this. We have to look into the exact API changes both in the AppStoreConnect API client and in our spaceship implementation.

Is this something you want to experiment with? We could give some directions.

**Comment by lucgrabowski** [comment]
Hi, I spent time investigating what could be the cause of the issue from logs - missing `app_info` that causes fastlane crash when you're trying to download metadata. 
I checked fastlane code, changes in AppstoreConnect API and checked what requests are sent in web browser on AppstoreConnect page and I don't think that the issue is caused by those API changes. It looks more of an issue with data. 

During investigation I found out that I have a released app that doesn't have `app_info` related to proper app store version of the app, it relates to REPLACED_WITH_NEW_VERSION app store state and is somehow incomplete and downloading metadata fails the same way as in attached logs.

**Comment by iBotPeaches** [comment]
Cleaning up backlog. This was fixed in #21890
