### ISSUE TITLE
failed to authenticate with fastlane API key with Azure pipeline

### ISSUE THREAD

**Issue by arpitmishra-eaton** [fastlane/fastlane#21875]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi Team - We are deploying the iOS mobile app to the app store (PROD) using Fastlane version (2.219.0). we have provided the API key ID, issuer id, and Filepath. however, it asks for the password. 

##### Command executed

Please check the yaml executed and referring lane in Fastlane file.

 - script: >-
                
                fastlane ios release appstore \
                --api_key "
                    {
                        \"filepath\": \"$(API Key ID)\",
                        \"key_id\": \"$(API Issuer ID)\",
                        \"issuer_id\": \"$(API Key base 64)\"
                    }
                "
                build_number: **
                app_version: ***
                team_id: ***
                app_identifier: '******'
                metadata_path: '$(Build.SourcesDirectory)/ios/fastlane/metadata/en-US/release_notes.txt'
                
              displayName: Promote build to prod release
              workingDirectory: $(Build.SourcesDirectory)/ios/

fastlane file:

default_platform(:ios)

platform :ios do

  desc "Release Testflight Build"
  lane :release do |options|
  
    deliver(
     
      automatic_release: true,
      skip_binary_upload: false, 
      force: true,
      build_number: options[:build_number],
      submit_for_review: true,
      team_id: options[:team_id],
      app_version: options[:app_version],
      app_identifier: options[:app_identifier],
      metadata_path: options[:metadata_path],
      skip_screenshots: true,
      overwrite_screenshots: false,
      precheck_include_in_app_purchases: false,
      # https://github.com/artsy/eigen/blob/faa02e2746194d8d7c11899474de9c517435eca4/fastlane/Fastfile#L131-L149
      submission_information: {
        add_id_info_uses_idfa: false,
        }      
      )
 end
end

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [2024-02-15T06:48:57.4858150Z Generating script.
2024-02-15T06:48:57.4866170Z ========================== Starting Command Output ===========================
2024-02-15T06:48:57.4881610Z [command]/bin/bash --noprofile --norc /Users/runner/work/_temp/25151988-457d-4106-8c24-a4965455db04.sh
2024-02-15T06:48:59.4550050Z [06:48:59]: [33mfastlane detected a Gemfile in the current directory[0m
2024-02-15T06:48:59.4551950Z [06:48:59]: [33mHowever, it seems like you didn't use `bundle exec`[0m
2024-02-15T06:48:59.4552650Z [06:48:59]: [33mTo launch fastlane faster, please use[0m
2024-02-15T06:48:59.4552950Z [06:48:59]: 
2024-02-15T06:48:59.4553270Z [06:48:59]: [36m$ bundle exec fastlane ios release appstore  --api_key 
2024-02-15T06:48:59.4553570Z     {
2024-02-15T06:48:59.4554630Z         "filepath": "***",
2024-02-15T06:48:59.4555030Z         "key_id": "***",
2024-02-15T06:48:59.4556410Z         "issuer_id": "***"
2024-02-15T06:48:59.4557470Z     }
2024-02-15T06:48:59.4558070Z  build_number: ** app_version: *** team_id: *** app_identifier: ***** metadata_path: /Users/runner/work/1/s/ios/fastlane/metadata/en-US/release_notes.txt[0m
2024-02-15T06:48:59.4558840Z [06:48:59]: 
2024-02-15T06:48:59.4559320Z [06:48:59]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2024-02-15T06:49:01.3301470Z [06:49:01]: Sending anonymous analytics information
2024-02-15T06:49:01.3363940Z [06:49:01]: Learn more at https://docs.fastlane.tools/#metrics
2024-02-15T06:49:01.3520980Z [06:49:01]: No personal or sensitive data is sent.
2024-02-15T06:49:01.3547490Z [06:49:01]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2024-02-15T06:49:01.3569670Z [06:49:01]: [32m------------------------------[0m
2024-02-15T06:49:01.3600350Z [06:49:01]: [32m--- Step: default_platform ---[0m
2024-02-15T06:49:01.3616120Z [06:49:01]: [32m------------------------------[0m
2024-02-15T06:49:01.3631850Z [06:49:01]: [32mDriving the lane 'ios release' 🚀[0m
2024-02-15T06:49:01.4161550Z [06:49:01]: [32m---------------------[0m
2024-02-15T06:49:01.4184130Z [06:49:01]: [32m--- Step: deliver ---[0m
2024-02-15T06:49:01.4213570Z [06:49:01]: [32m---------------------[0m
2024-02-15T06:49:01.4232790Z [06:49:01]: [32mSuccessfully loaded '/Users/runner/work/1/s/ios/fastlane/Deliverfile' 📄[0m
2024-02-15T06:49:01.4264130Z [06:49:01]: [33mNo values defined in './fastlane/Deliverfile'[0m
2024-02-15T06:49:01.4298140Z [06:49:01]: Login to App Store Connect (arpitmishra@hgu.com)
2024-02-15T06:49:01.4568590Z [32m-------------------------------------------------------------------------------------[0m
2024-02-15T06:49:01.4596180Z [32mPlease provide your Apple Developer Program account credentials[0m
2024-02-15T06:49:01.4609110Z [32mThe login information you enter will be stored in your macOS Keychain[0m
2024-02-15T06:49:01.4634880Z [32mYou can also pass the password using the `FASTLANE_PASSWORD` environment variable[0m
2024-02-15T06:49:01.4655290Z [32mSee more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager[0m
2024-02-15T06:49:01.4678090Z [32m-------------------------------------------------------------------------------------[0m
2024-02-15T06:49:01.4697110Z +--------------------------------+
2024-02-15T06:49:01.4727520Z |          [33mLane Context[0m          |
2024-02-15T06:49:01.4739120Z +------------------+-------------+
2024-02-15T06:49:01.4761310Z | DEFAULT_PLATFORM | ios         |
2024-02-15T06:49:01.4786820Z | PLATFORM_NAME    | ios         |
2024-02-15T06:49:01.4809500Z | LANE_NAME        | ios release |
2024-02-15T06:49:01.4831090Z +------------------+-------------+
2024-02-15T06:49:01.4843850Z [06:49:01]: [31mMissing password for user arpitmishra@jdfs.com, and running in non-interactive shell[0m
2024-02-15T06:49:01.4958420Z 
2024-02-15T06:49:01.4975450Z +---------------------------------------+
2024-02-15T06:49:01.4991280Z |           [32mfastlane summary[0m            |
2024-02-15T06:49:01.4999730Z +------+------------------+-------------+
2024-02-15T06:49:01.5011870Z | Step | Action           | Time (in s) |
2024-02-15T06:49:01.5019860Z +------+------------------+-------------+
2024-02-15T06:49:01.5023140Z | 1    | default_platform | 0           |
2024-02-15T06:49:01.5033820Z | 💥   | [31mdeliver[0m          | 0           |
2024-02-15T06:49:01.5044370Z +------+------------------+-------------+
2024-02-15T06:49:01.5053110Z 
2024-02-15T06:49:01.5082650Z [06:49:01]: [31mfastlane finished with errors[0m
2024-02-15T06:49:01.5119300Z 
2024-02-15T06:49:01.5145450Z Looking for related GitHub issues on fastlane/fastlane...
2024-02-15T06:49:01.5145730Z 
2024-02-15T06:49:01.6767430Z Found no similar issues. To create a new issue, please visit:
2024-02-15T06:49:01.6824660Z https://github.com/fastlane/fastlane/issues/new
2024-02-15T06:49:01.6860860Z Run `fastlane env` to append the fastlane environment to your issue
2024-02-15T06:49:01.6941490Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': \e[31m[!] Missing password for user arpitmishra@eaton.com, and running in non-interactive shell\e[0m (RuntimeError)
2024-02-15T06:49:01.6981230Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
2024-02-15T06:49:01.7015890Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/client.rb:383:in `login'
2024-02-15T06:49:01.7054950Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/client.rb:355:in `login'
2024-02-15T06:49:01.7091500Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
2024-02-15T06:49:01.7117780Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
2024-02-15T06:49:01.7124160Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
2024-02-15T06:49:01.7138290Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/deliver/lib/deliver/runner.rb:43:in `login'
2024-02-15T06:49:01.7152820Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/deliver/lib/deliver/runner.rb:23:in `initialize'
2024-02-15T06:49:01.7156640Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `new'
2024-02-15T06:49:01.7165250Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
2024-02-15T06:49:01.7170100Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
2024-02-15T06:49:01.7179620Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
2024-02-15T06:49:01.7183600Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
2024-02-15T06:49:01.7186070Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
2024-02-15T06:49:01.7209410Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
2024-02-15T06:49:01.7211180Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
2024-02-15T06:49:01.7216250Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2024-02-15T06:49:01.7225680Z 	from Fastfile:23:in `block (2 levels) in parsing_binding'
2024-02-15T06:49:01.7241000Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane.rb:41:in `call'
2024-02-15T06:49:01.7246560Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
2024-02-15T06:49:01.7270690Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
2024-02-15T06:49:01.7290260Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
2024-02-15T06:49:01.7298240Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
2024-02-15T06:49:01.7310090Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
2024-02-15T06:49:01.7311100Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
2024-02-15T06:49:01.7340670Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2024-02-15T06:49:01.7366470Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2024-02-15T06:49:01.7417320Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2024-02-15T06:49:01.7443750Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2024-02-15T06:49:01.7466740Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2024-02-15T06:49:01.7477980Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
2024-02-15T06:49:01.7480850Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
2024-02-15T06:49:01.7487580Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
2024-02-15T06:49:01.7503720Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
2024-02-15T06:49:01.7513840Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2024-02-15T06:49:01.7520850Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2024-02-15T06:49:01.7569390Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': Missing password for user arpitmishra@eaton.com, and running in non-interactive shell (RuntimeError)
2024-02-15T06:49:01.7631630Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
2024-02-15T06:49:01.7653300Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/client.rb:383:in `login'
2024-02-15T06:49:01.7670790Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/client.rb:355:in `login'
2024-02-15T06:49:01.7687760Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
2024-02-15T06:49:01.7710610Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
2024-02-15T06:49:01.7746700Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
2024-02-15T06:49:01.7758280Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/deliver/lib/deliver/runner.rb:43:in `login'
2024-02-15T06:49:01.7771090Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/deliver/lib/deliver/runner.rb:23:in `initialize'
2024-02-15T06:49:01.7773980Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `new'
2024-02-15T06:49:01.7777230Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
2024-02-15T06:49:01.7779290Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
2024-02-15T06:49:01.7781970Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
2024-02-15T06:49:01.7784160Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
2024-02-15T06:49:01.7806730Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
2024-02-15T06:49:01.7813240Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
2024-02-15T06:49:01.7829010Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
2024-02-15T06:49:01.7839020Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2024-02-15T06:49:01.7846680Z 	from Fastfile:23:in `block (2 levels) in parsing_binding'
2024-02-15T06:49:01.7883130Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane.rb:41:in `call'
2024-02-15T06:49:01.7883740Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
2024-02-15T06:49:01.7884260Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
2024-02-15T06:49:01.7884850Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
2024-02-15T06:49:01.7899100Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
2024-02-15T06:49:01.7908440Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
2024-02-15T06:49:01.7911120Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
2024-02-15T06:49:01.7926910Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2024-02-15T06:49:01.7935000Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2024-02-15T06:49:01.7941820Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2024-02-15T06:49:01.7954560Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2024-02-15T06:49:01.7972210Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2024-02-15T06:49:01.7975870Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
2024-02-15T06:49:01.7979440Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
2024-02-15T06:49:01.7983240Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
2024-02-15T06:49:01.7998000Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
2024-02-15T06:49:01.8003050Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2024-02-15T06:49:01.8009370Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2024-02-15T06:49:01.8037960Z 
2024-02-15T06:49:01.8082700Z ##[error]Bash exited with code '1'.
2024-02-15T06:49:01.8152570Z ##[section]Finishing: Promote build to prod release] </pre>
</details>

### Environment

<details>
  <pre> 
2024-02-15T06:54:52.4234750Z ### Stack
2024-02-15T06:54:52.4307440Z 
2024-02-15T06:54:52.4408590Z | Key                         | Value                                            |
2024-02-15T06:54:52.4510300Z | --------------------------- | ------------------------------------------------ |
2024-02-15T06:54:52.4611480Z | OS                          | 12.7.3                                           |
2024-02-15T06:54:52.4712620Z | Ruby                        | 3.0.6                                            |
2024-02-15T06:54:52.4814130Z | Bundler?                    | false                                            |
2024-02-15T06:54:52.4915220Z | Git                         | git version 2.43.0                               |
2024-02-15T06:54:52.5016380Z | Installation Source         | /usr/local/lib/ruby/gems/3.0.0/bin/fastlane      |
2024-02-15T06:54:52.5117600Z | Host                        | macOS 12.7.3 (21H1015)                           |
2024-02-15T06:54:52.5218730Z | Ruby Lib Dir                | /usr/local/Cellar/ruby@3.0/3.0.6_1/lib           |
2024-02-15T06:54:52.5301360Z | OpenSSL Version             | OpenSSL 3.1.1 30 May 2023                        |
2024-02-15T06:54:52.5329800Z | Is contained                | false                                            |
2024-02-15T06:54:52.5402820Z | Is homebrew                 | false                                            |
2024-02-15T06:54:52.5438640Z | Is installed via Fabric.app | false                                            |
2024-02-15T06:54:52.5494480Z | Xcode Path                  | /Applications/Xcode_14.2.app/Contents/Developer/ |
2024-02-15T06:54:52.5537880Z | Xcode Version               | 14.2                                             |
2024-02-15T06:54:52.5569630Z | Swift Version               | 5.7.2                                            |

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.219.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

| ipaddr                          | 1.2.2        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.1        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

 
</pre>
</details>

**Comment by lacostej** [comment]
I believe `api_key` is an option to `deliver` but you seem to be passing it the fastlane CLI instead.

See how this is done in the [Passing parameters section](https://docs.fastlane.tools/advanced/lanes/) of the doc.

**Comment by arpitmishra-eaton** [comment]
Hi @lacostej  

I have tried the  CLI command:   fastlane ios release  filepath: $(API Key ID) key_id: $(API Issuer ID) issuer_id:$(API Key base 64) build_number: *** app_version:***** team_id:**** app_identifier:*******' metadata_path:'$(Build.SourcesDirectory)/ios/fastlane/metadata/en-US/release_notes.txt' 

and fastlane file: 

deliver(
      api_key = app_store_connect_api_key(
      key_id: options[:filepath],
      issuer_id: options[:key_id],
      key_content: options[:issuer_id],
      ),
      pilot(api_key: api_key),
      skip_binary_upload: false, 
      force: true,
      build_number: options[:build_number],
      automatic_release: true,
      submit_for_review: true,
     team_id: options[:team_id],
      app_version: options[:app_version],
      app_identifier: options[:app_identifier],
      metadata_path: options[:metadata_path],
      skip_screenshots: true,
      overwrite_screenshots: false,
      precheck_include_in_app_purchases: false,
      # https://github.com/artsy/eigen/blob/faa02e2746194d8d7c11899474de9c517435eca4/fastlane/Fastfile#L131-L149
      submission_information: {
        add_id_info_uses_idfa: false,
      }      
    )
               
and receiving "invalid curve issue"
