### ISSUE TITLE
[Sigh] Creating tvos provisioning profile fails when fetching devices.

### ISSUE THREAD

**Issue by MartinGonzalez** [fastlane/fastlane#21921]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.218.0, 2.219.0
- Last working version: 2.217.0

### Regression Description
When retying to retrieve or create a tvos provisioning profile it fails with the following error:

```
"errors" : [ {
    "id" : "207e0451-d14d-4c5a-8507-cdb14cf776af",
    "status" : "400",
    "code" : "PARAMETER_ERROR.INVALID",
    "title" : "A parameter has an invalid value",
    "detail" : "A parameter 'filter[platform]' has an invalid value : 'Empty filter values are not supported.'",
    "source" : {
      "parameter" : "filter[platform]"
    }
  } ]
}
```

These are the options I'm using (I just renamed some of them)

```
+-------------------------------------------------------------------------------------------------------------+
|                                          Summary for sigh 2.218.0                                           |
+-------------------------------------+-----------------------------------------------------------------------+
| username                            | my@user.com                                                 |
| skip_install                        | true                                                                  |
| skip_certificate_verification       | true                                                                  |
| force                               | true                                                                  |
| cert_id                             | MY_CERT_ID                                                            |
| platform                            | tvos                                                                  |
| team_id                             | MY_TEAM_ID                                                            |
| app_identifier                      | com.company.gamename                                |
| provisioning_name                   | Game Name Adhoc                            |
| filename                            | ../GameName/tvos_appstore_adhoc.mobileprovision |
| adhoc                               | true                                                                  |
| developer_id                        | false                                                                 |
| development                         | false                                                                 |
| include_mac_in_profiles             | false                                                                 |
| ignore_profiles_with_different_name | false                                                                 |
| skip_fetch_profiles                 | false                                                                 |
| include_all_certificates            | false                                                                 |
| readonly                            | false                                                                 |
| fail_on_name_taken                  | false                                                                 |
+-------------------------------------+-----------------------------------------------------------------------+
```

##### Complete output when running fastlane, including the stack trace and command used

```
from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:61:in `proxy_get'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:29:in `get'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:170:in `get_devices'
	from /Users/martingonzalez/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/forwardable.rb:238:in `get_devices'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/spaceship/lib/spaceship/connect_api/models/device.rb:56:in `all'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/spaceship/lib/spaceship/connect_api/models/device.rb:113:in `devices_for_platform'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/sigh/lib/sigh/runner.rb:221:in `devices_to_use'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/sigh/lib/sigh/runner.rb:182:in `create_profile!'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/sigh/lib/sigh/runner.rb:54:in `run'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/sigh/lib/sigh/manager.rb:8:in `start'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/sigh/lib/sigh/commands_generator.rb:62:in `block (2 levels) in run'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/sigh/lib/sigh/commands_generator.rb:140:in `run'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/sigh/lib/sigh/commands_generator.rb:17:in `start'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/gems/fastlane-2.218.0/bin/fastlane:23:in `<top (required)>'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/bin/fastlane:25:in `load'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/bin/fastlane:25:in `<main>'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/martingonzalez/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 14.2.1                                           |
| Ruby                        | 3.0.0                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.39.3 (Apple Git-145)               |
| Installation Source         | ~/.rvm/gems/ruby-3.0.0/bin/fastlane              |
| Host                        | macOS 14.2.1 (23C71)                             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.0/lib                     |
| OpenSSL Version             | OpenSSL 1.1.1t  7 Feb 2023                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-15.2.app/Contents/Developer/ |
| Xcode Version               | 15.2                                             |
| Swift Version               | 5.9.2                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.217.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.4.17       |
| pathname                        | 0.1.0        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| CFPropertyList                  | 3.0.6        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday_middleware              | 1.2.0        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| google-cloud-storage            | 1.44.0       |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.1        |
| public_suffix                   | 5.0.3        |
| addressable                     | 2.8.5        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.8.0        |
| aws-partitions                  | 1.844.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.186.0      |
| aws-sdk-kms                     | 1.72.0       |
| aws-sdk-s3                      | 1.136.0      |
| rexml                           | 3.2.6        |
| excon                           | 0.104.0      |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| fastimage                       | 2.2.7        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.7.1        |
| signet                          | 0.18.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.2       |
| google-apis-androidpublisher_v3 | 0.51.0       |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| json                            | 2.6.3        |
| unicode-display_width           | 2.5.0        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.23.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| net-smtp                        | 0.2.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.6        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.1        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
| ox                              | 2.13.2       |
</details>

*generated on:* **2024-03-13**
</details></pre>
</details>

**Comment by MartinGonzalez** [comment]
Closing it in favour of https://github.com/fastlane/fastlane/issues/21925
