### ISSUE TITLE
fastlane sigh download_all  and "Error parsing provisioning profile at path..."

### ISSUE THREAD

**Issue by harrimaatta** [fastlane/fastlane#21951]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane is run in macOS environment and it can be used by GitHub Actions. On the other words, there is running a self-hosted runner which is using fastlane. So, this in not included into specific project. 

I have a GitHub Action which downloads Apple's Provisioning Profiles at every night. When running a command <code>fastlane sigh download_all --api_key_path fastlane.json --output_path=pp_path </code> I got an error
<code>/opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Error parsing provisioning profile at path '/Users/user/Library/MobileDevice/Provisioning Profiles/AppStore_<random>_<project_bundle_id>' </code>

If I run <code>ls -la</code> in <code>/Users/user/Library/MobileDevice/Provisioning Profiles/ </code> looks that fastlane tries to install the provisioning profile file that doesn't exist in the path. 

Like, in case <code>
/opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Error parsing provisioning profile at path '/Users/jenkins/Library/MobileDevice/Provisioning Profiles/AppStore_a4205234.... </code>

Looks that <code> ls -la |wc -l </code> finds 44 hits (yes, we have a lot of projects...), but <code>ls -la AppStore_a420*</code> doesn't find any hits. 

I have also tried to use two GH Actions steps, where in first phase was used <code>--skip_install=true</code> and in next step not but this didn't fixed the issue. 

##### Command executed

fastlane sigh download_all --api_key_path fastlane.json --skip_certificate_verification --output_path=PP_PATH

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Error parsing provisioning profile at path '/Users/user/Library/MobileDevice/Provisioning Profiles/AppStore_a4205234....' (FastlaneCore::Interface::FastlaneCrash)
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:33:in `parse'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:39:in `uuid'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/manager.rb:39:in `install_profile'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:117:in `download_profile'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:83:in `block in download_profiles'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:80:in `each'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:80:in `download_profiles'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:73:in `download_all'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/manager.rb:35:in `download_all'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:84:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:[18](https://github.devcloud.elisa.fi/Tarmo/ios-provisioning-profile-install/actions/runs/2444409/job/5538023#step:8:19)7:in `call'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.2[20](https://github.devcloud.elisa.fi/Tarmo/ios-provisioning-profile-install/actions/runs/2444409/job/5538023#step:8:21).0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:140:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.[22](https://github.devcloud.elisa.fi/Tarmo/ios-provisioning-profile-install/actions/runs/2444409/job/5538023#step:8:23)0.0/sigh/lib/sigh/commands_generator.rb:17:in `start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/bin/fastlane:[23](https://github.devcloud.elisa.fi/Tarmo/ios-provisioning-profile-install/actions/runs/2444409/job/5538023#step:8:24):in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/fastlane:25:in `load'
	from /opt/homebrew/opt/ruby/bin/fastlane:25:in `<main>'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Error parsing provisioning profile at path '/Users/jenkins/Library/MobileDevice/Provisioning Profiles/AppStore_a4205234-4783-466c-9f1f-bc89ba5c09c1_fi.elisa.vakio.mobileprovision' (FastlaneCore::Interface::FastlaneCrash)
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:33:in `parse'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:39:in `uuid'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/manager.rb:39:in `install_profile'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:117:in `download_profile'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:83:in `block in download_profiles'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:80:in `each'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:80:in `download_profiles'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/download_all.rb:73:in `download_all'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/manager.rb:35:in `download_all'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:84:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:1[24](https://github.devcloud.elisa.fi/Tarmo/ios-provisioning-profile-install/actions/runs/2444409/job/5538023#step:8:25):in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:140:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:17:in `start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/fastlane:[25](https://github.devcloud.elisa.fi/Tarmo/ios-provisioning-profile-install/actions/runs/2444409/job/5538023#step:8:26):in `load'
	from /opt/homebrew/opt/ruby/bin/fastlane:25:in `<main>'
Error: Process completed with exit code 1.</pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 14.4.1                                          |
| Ruby                        | 3.3.0                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.39.3 (Apple Git-145)              |
| Installation Source         | /opt/homebrew/opt/ruby/bin/fastlane             |
| Host                        | macOS 14.4.1 (23E224)                           |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.0/lib             |
| OpenSSL Version             | OpenSSL 3.2.0 23 Nov 2023                       |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode15.2.app/Contents/Developer/ |
| Xcode Version               | 15.2                                            |
| Swift Version               | 5.9.2                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.220.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.6.0        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.0        |
| addressable                     | 2.8.6        |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-cloud-env                | 1.6.0        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.6        |
| xcodeproj                       | 1.24.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.0        |
| public_suffix                   | 5.0.5        |
| artifactory                     | 3.0.17       |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-partitions                  | 1.909.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.191.6      |
| aws-sdk-kms                     | 1.78.0       |
| aws-sdk-s3                      | 1.146.1      |
| bundler                         | 2.5.7        |
| base64                          | 0.2.0        |
| nkf                             | 0.2.0        |
| CFPropertyList                  | 3.0.7        |
| excon                           | 0.110.0      |
| multipart-post                  | 2.4.0        |
| fastimage                       | 2.3.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.8.1        |
| signet                          | 0.19.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| rake                            | 13.2.1       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.31.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.0        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.7.2        |
| forwardable                     | 1.3.3        |
| logger                          | 1.6.0        |
| pathname                        | 0.3.0        |
| shellwords                      | 0.2.0        |
| cgi                             | 0.4.1        |
| date                            | 3.3.4        |
| timeout                         | 0.4.1        |
| securerandom                    | 0.3.1        |
| cookiejar                       | 0.3.4        |
| eventmachine                    | 1.2.7        |
| em-socksify                     | 0.3.2        |
| http_parser.rb                  | 0.8.0        |
| em-http-request                 | 1.1.7        |
| resolv                          | 0.4.0        |
| openssl                         | 3.2.0        |
| digest                          | 3.1.1        |
| ipaddr                          | 1.2.6        |
| time                            | 0.3.0        |
| uri                             | 0.13.0       |
| stringio                        | 3.1.0        |
| open-uri                        | 0.4.1        |
| mutex_m                         | 0.2.0        |
| net-http                        | 0.4.1        |
| net-protocol                    | 0.2.2        |
| connection_pool                 | 2.4.1        |
| net-http-persistent             | 4.0.2        |
| patron                          | 0.13.3       |
| english                         | 0.8.0        |
| erb                             | 4.0.4        |
| abbrev                          | 0.1.2        |
| tempfile                        | 0.2.1        |
| delegate                        | 0.3.1        |
| fileutils                       | 1.7.2        |
| tmpdir                          | 0.2.0        |
| singleton                       | 0.2.0        |
| open3                           | 0.2.1        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.5.0        |
| find                            | 0.2.0        |
| ostruct                         | 0.6.0        |
| yaml                            | 0.3.0        |
| psych                           | 5.1.2        |
</details>

*generated on:* **2024-04-08**
</details>
 </pre>
</details>

**Comment by gregory109** [comment]
Hello, @harrimaatta 

While waiting for a fix, consider these workarounds:

Export to IDML or INX:
Export your InDesign document to either IDML (InDesign Markup Language) or INX (InDesign Interchange format).
Then reopen the IDML or INX file.
This process can sometimes eliminate problematic data and improve compatibility.
Test Different Fonts:
Experiment with different fonts for your button text.
Some fonts may handle non-ASCII characters better during export.
Limit Non-ASCII Characters:
If possible, limit the use of non-ASCII characters in button values.
While not ideal, it might help avoid the issue until a proper fix is available.


I hope this info is helpful to you.

Best Regard,
Gregory Chavez
