### ISSUE TITLE
Provisioning profile expiration comparison compares Time and DateTime

### ISSUE THREAD

**Issue by jboulter11** [fastlane/fastlane#21966]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.220.0
- Last working version: presumably before 2.220.0

### Regression Description

https://github.com/fastlane/fastlane/pull/21691

I believe this PR introduced a comparison between DateTime and Time objects which seems to not work on my machine.  Prior to that PR, there was no datetime-time comparison.  I'm not exactly clear why this breaks for me but seemingly not for others, I'm not a ruby expert, but ideally a more compatible comparison can be made that is more environment-tolerant.

##### Complete output when running fastlane, including the stack trace and command used

We're using the spaceship API in ruby roughly like this:
1. Call `Spaceship.provisioning_profile.development.all(mac: is_mac)` to get profiles
2. Loop over the profiles using forEach
3. Among other checks, we look at `profile.valid?` which causes this exception

Here's the relevant parts of the stack trace.  I'm trimming out our script's stack frames here.
<details>
  <pre>
/Users/jboulter/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.220.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:490:in `>': comparison of Time with DateTime failed (ArgumentError)
	from /Users/jboulter/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.220.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:490:in `valid?'
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 14.4.1                                             |
| Ruby                        | 3.1.2                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.43.0                                 |
| Installation Source         | ~/.rbenv/versions/3.1.2/bin/fastlane               |
| Host                        | macOS 14.4.1 (23E224)                              |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.2/lib                        |
| OpenSSL Version             | OpenSSL 3.2.1 30 Jan 2024                          |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-15.3.0.app/Contents/Developer/ |
| Xcode Version               | 15.3                                               |
| Swift Version               | 5.10                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.220.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| public_suffix                   | 5.0.5        |
| addressable                     | 2.8.6        |
| artifactory                     | 3.0.17       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.909.0      |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-sdk-core                    | 3.191.6      |
| aws-sdk-kms                     | 1.78.0       |
| aws-sdk-s3                      | 1.146.1      |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.110.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| base64                          | 0.1.1        |
| jwt                             | 2.8.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| rexml                           | 3.2.5        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.6.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.2.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.24.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.2        |
| bundler                         | 2.3.7        |
| nkf                             | 0.1.1        |
| CFPropertyList                  | 3.0.7        |
| multipart-post                  | 2.4.0        |
| unicode-display_width           | 2.5.0        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2024-04-10**
</details></pre>
</details>

**Comment by donaald795** [comment]
Thank you for posting that it could be just the thing to give inspiration to someone who needs it! Keep up the great work.

**Comment by ejskipper** [comment]
Hi, I've also had this issue, please see below error.

I was using an older version of fastlane to work around this, but recently I've also begun experiencing issues as described on https://github.com/fastlane/fastlane/issues/22248, which I would need to upgrade to version 2.223.1 to fix. Therefore I currently can't build and release my iOS app with fastlane, there's no version which is working for me. 

I'm currently looking to see if I can find a work-around for this issue, but a fix to ensure that we're comparing the same type here would be great 

```
bundler: failed to load command: fastlane (/Users/gitlabrunner/gems/ruby/3.3.0/bin/fastlane)
/Users/gitlabrunner/gems/ruby/3.3.0/gems/fastlane-2.224.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:490:in `>': [!] comparison of Time with DateTime failed (ArgumentError)
        expired = Time.now.utc > self.expires
                                 ^^^^^^^^^^^^
	from /Users/gitlabrunner/gems/ruby/3.3.0/gems/fastlane-2.224.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:490:in `valid?'
```
