### ISSUE TITLE
curb-1.0.0/lib/curl/easy.rb - Failed to read/open file

### ISSUE THREAD

**Issue by chiragchaplot** [fastlane/fastlane#21971]
Getting an issue on fastlane upload to appcenter. Issue seems to be in easy.rb file. But as a set up process I don't think we have interacted or touched this file. What could be a  potential fix?

	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'
**/usr/local/lib/ruby/gems/3.0.0/gems/curb-1.0.0/lib/curl/easy.rb:80:in `perform': Failed to open/read local data from file/application: client read function EOF fail, only only 172/173 of needed bytes read (Curl::Err::ReadError)**
	from /usr/local/lib/ruby/gems/3.0.0/gems/curb-1.0.0/lib/curl/easy.rb:383:in `http_put'
	from /usr/local/lib/ruby/gems/3.0.0/gems/curb-1.0.0/lib/curl/easy.rb:383:in `http_put'
	from Fastfile:262:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'

**Comment by boutil** [comment]
This is an incompatibility of the `curb` gem with curl 8.7.x. Something changed between the version 8.6 and 8.7 causing this issue.

The same kind of messages appear in a Debian bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1069258
and upstream curl mailing list (not related with curb, but with another software using curl)
https://curl.se/mail/lib-2024-03/0049.html

**Comment by iBotPeaches** [comment]
Sorry for delay, we don't have `curb` as a native dependency and as linked above. It was fixed in an updated gem version, so I'll close this out.
