### ISSUE TITLE
Unable to download metadata with user input

### ISSUE THREAD

**Issue by kraw-ios** [fastlane/fastlane#22001]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to download app store metadata of the current live version of the app and the only way that works it's by hardcoding the app_version in the command. I even tried `use_live_version true` and `edit_live true` but it doesn't seem to work.

However it only works if I hardcode it on the command, if I prompt for user input and I write the same version via the terminal input it gives me an error.

##### Command executed

This one works:

        sh('fastlane deliver download_metadata --force true --app_version 6.1 -m "$DLV_DOWNLOAD_METADATA_PATH" -u $DLV_ITUNESCONNECT_USERNAME -a $DLV_BUNDLE_ID')

This doesn't work:

	custom_version = prompt(text: "\nEnter the App Version Number to download metadata:")
	UI.message "Custom version #{custom_version}"
        sh('fastlane deliver download_metadata --force true --app_version custom_version -m "$DLV_DOWNLOAD_METADATA_PATH" -u $DLV_ITUNESCONNECT_USERNAME -a $DLV_BUNDLE_ID')

##### Complete output when running fastlane, including the stack trace and command used

[✔] 🚀 
[16:25:58]: Loading from './.env.sensitive'
[16:25:58]: fastlane detected a Gemfile in the current directory
[16:25:58]: However, it seems like you didn't use `bundle exec`
[16:25:58]: To launch fastlane faster, please use
[16:25:58]: 
[16:25:58]: $ bundle exec fastlane downloadMetadata
[16:25:58]: 
[16:25:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:25:59]: ------------------------------
[16:25:59]: --- Step: default_platform ---
[16:25:59]: ------------------------------
[16:25:59]: Driving the lane 'ios downloadMetadata' 🚀
[16:25:59]: --------------------
[16:25:59]: --- Step: prompt ---
[16:25:59]: --------------------
[16:25:59]: 
Enter the App Version Number to download metadata:
6.1
[16:26:04]: Custom version 6.1
[16:26:04]: ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[16:26:04]: --- Step: fastlane deliver download_metadata --force true --app_version custom_version -m "$DLV_DOWNLOAD_METADATA_PATH" -u $DLV_ITUNESCONNECT_USERNAME -a $DLV_BUNDLE_ID ---
[16:26:04]: ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[16:26:04]: $ fastlane deliver download_metadata --force true --app_version custom_version -m "$DLV_DOWNLOAD_METADATA_PATH" -u $DLV_ITUNESCONNECT_USERNAME -a $DLV_BUNDLE_ID
[16:26:04]: ▸ [16:26:04]: fastlane detected a Gemfile in the current directory
[16:26:04]: ▸ [16:26:04]: However, it seems like you didn't use `bundle exec`
[16:26:04]: ▸ [16:26:04]: To launch fastlane faster, please use
[16:26:04]: ▸ [16:26:04]:
[16:26:04]: ▸ [16:26:04]: $ bundle exec fastlane deliver download_metadata --force true --app_version custom_version -m ./sensitive/metadata -u sensitive -a sensitive
[16:26:04]: ▸ [16:26:04]:
[16:26:04]: ▸ [16:26:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:26:05]: ▸ [16:26:05]: Login to App Store Connect (sensitive)
[16:26:07]: ▸ [16:26:07]: Login successful
[16:26:08]: ▸ +------------------------------------------------------------+
[16:26:08]: ▸ |                  deliver 2.220.0 Summary                   |
[16:26:08]: ▸ +--------------------------------------+---------------------+
[16:26:08]: ▸ | force                                | true                |
[16:26:08]: ▸ | app_version                          | custom_version      |
[16:26:08]: ▸ | metadata_path                        | ./sensitive/metadata |
[16:26:08]: ▸ | username                             | sensitive   |
[16:26:08]: ▸ | app_identifier                       | sensitive  |
[16:26:08]: ▸ | screenshots_path                     | ./screenshots       |
[16:26:08]: ▸ | platform                             | ios                 |
[16:26:08]: ▸ | edit_live                            | false               |
[16:26:08]: ▸ | use_live_version                     | false               |
[16:26:08]: ▸ | skip_binary_upload                   | false               |
[16:26:08]: ▸ | skip_screenshots                     | false               |
[16:26:08]: ▸ | skip_metadata                        | false               |
[16:26:08]: ▸ | skip_app_version_update              | false               |
[16:26:08]: ▸ | overwrite_screenshots                | false               |
[16:26:08]: ▸ | screenshot_processing_timeout        | 3600                |
[16:26:08]: ▸ | sync_screenshots                     | false               |
[16:26:08]: ▸ | submit_for_review                    | false               |
[16:26:08]: ▸ | verify_only                          | false               |
[16:26:08]: ▸ | reject_if_possible                   | false               |
[16:26:08]: ▸ | version_check_wait_retry_limit       | 7                   |
[16:26:08]: ▸ | phased_release                       | false               |
[16:26:08]: ▸ | reset_ratings                        | false               |
[16:26:08]: ▸ | team_id                              | sensitive           |
[16:26:08]: ▸ | dev_portal_team_id                   | sensitive          |
[16:26:08]: ▸ | run_precheck_before_submit           | true                |
[16:26:08]: ▸ | precheck_default_rule_level          | warn                |
[16:26:08]: ▸ | ignore_language_directory_validatio  | false               |
[16:26:08]: ▸ | n                                    |                     |
[16:26:08]: ▸ | precheck_include_in_app_purchases    | true                |
[16:26:08]: ▸ +--------------------------------------+---------------------+
[16:26:11]: ▸ Looking for related GitHub issues on fastlane/fastlane...
[16:26:11]: ▸ Found no similar issues. To create a new issue, please visit:
[16:26:11]: ▸ https://github.com/fastlane/fastlane/issues/new
[16:26:11]: ▸ Run `fastlane env` to append the fastlane environment to your issue
[16:26:11]: ▸ /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/deliver/lib/deliver/commands_generator.rb:177:in `block (2 levels) in run': [!] Neither the current nor live version match specified app_version "custom_version" (RuntimeError)
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `load'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `<main>'
[16:26:11]: ▸ /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/deliver/lib/deliver/commands_generator.rb:177:in `block (2 levels) in run': Neither the current nor live version match specified app_version "custom_version" (RuntimeError)
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `load'
[16:26:11]: ▸ from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `<main>'
+-----------------------------------------+
|              Lane Context               |
+------------------+----------------------+
| ENVIRONMENT      | sensitive             |
| DEFAULT_PLATFORM | ios                  |
| PLATFORM_NAME    | ios                  |
| LANE_NAME        | ios downloadMetadata |
+------------------+----------------------+
[16:26:11]: Exit status of command 'fastlane deliver download_metadata --force true --app_version custom_version -m "$DLV_DOWNLOAD_METADATA_PATH" -u $DLV_ITUNESCONNECT_USERNAME -a $DLV_BUNDLE_ID' was 1 instead of 0.

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by gregory109** [comment]
The issue is likely due to the way the custom_version variable is being passed in the command. Try using string interpolation to include the custom_version variable in the command string:

sh("fastlane deliver download_metadata --force true --app_version #{custom_version} -m \"$DLV_DOWNLOAD_METADATA_PATH\" -u $DLV_ITUNESCONNECT_USERNAME -a $DLV_BUNDLE_ID")


This should correctly pass the value of custom_version to the --app_version parameter.


Best Regard,
Gregory Chavez
[destiny credit card](https://www.mydestiny-card.com)
