### ISSUE TITLE
`fastlane supply init` : `undefined method `name' for nil`

### ISSUE THREAD

**Issue by lukehutch** [fastlane/fastlane#22018]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I got the following when I ran `fastlane supply init` after `fastlane init`:

```
/usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/client.rb:303:in `block in latest_version': [!] undefined method `name' for nil (NoMethodError)

      latest_version = tracks.select { |t| t.track == Supply::Tracks::DEFAULT }.map(&:releases).flatten.reject { |r| r.name.nil? }.max_by(&:name)
                                                                                                                      ^^^^^
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/client.rb:303:in `reject'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/client.rb:303:in `latest_version'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/setup.rb:19:in `perform_download'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/commands_generator.rb:55:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/commands_generator.rb:61:in `run'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/commands_generator.rb:13:in `start'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `load'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `<main>'
/usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/client.rb:303:in `block in latest_version': undefined method `name' for nil (NoMethodError)

      latest_version = tracks.select { |t| t.track == Supply::Tracks::DEFAULT }.map(&:releases).flatten.reject { |r| r.name.nil? }.max_by(&:name)
                                                                                                                      ^^^^^
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/client.rb:303:in `reject'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/client.rb:303:in `latest_version'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/setup.rb:19:in `perform_download'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/commands_generator.rb:55:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/commands_generator.rb:61:in `run'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/supply/lib/supply/commands_generator.rb:13:in `start'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `load'
	from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `<main>'
```

**Comment by lukehutch** [comment]
This is a dup of #21529 -- closing
