### ISSUE TITLE
It took longer than expected to process your IPA, please try again.

### ISSUE THREAD

**Issue by jay368** [fastlane/fastlane#22035]
```
Looking for related GitHub issues on fastlane/fastlane...

➡️  [!] It took longer than expected to process your IPA, please try again. (FastlaneCore::Interface::FastlaneCrash)
    https://github.com/fastlane/fastlane/issues/22033 [open] 0 💬
    11 minutes ago

➡️  [deliver][pilot] use altool instead of using iTMSTransporter for Xcode 14
    https://github.com/fastlane/fastlane/pull/20631 [closed] 58 💬
    15 Sep 2022

➡️  Firebase App Distribution: 202 Response with Processing Error Doesn't Fail Lane
    https://github.com/fastlane/fastlane/issues/18590 [closed] 6 💬
    26 Oct 2021

and 4 more at: https://github.com/fastlane/fastlane/search?q=It%20took%20longer%20than%20expected%20to%20process%20your%20IPA%2C%20please%20try%20again.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] It took longer than expected to process your IPA, please try again. (FastlaneCore::Interface::FastlaneCrash)
        from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
```

fastlane Version : 2.220.0 (Latest version as of now)
fastlane-plugin-firebase_app_distribution Version : 0.9.1 (Latest version as of now)

Originally, I was using version 2.217.0, but this problem occurred and I thought the situation would improve with the update, but it was not resolved.

**Comment by junddao** [comment]
same problem

**Comment by tsoejima** [comment]
same here

**Comment by Shafran123** [comment]
Same here

**Comment by shawn-lin-013** [comment]
Occurred on Android too
```
/Users/xxx/.gem/gems/fastlane-2.204.2/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [31m[!] It took longer than expected to process your APK, please try again.[0m (FastlaneCore::Interface::FastlaneCrash)
```

**Comment by august-setel** [comment]
same here

**Comment by hakunatomata2** [comment]
+ 1

**Comment by Milutin-P** [comment]
Firebase App Distribution is down.
You can check the status of it here: https://status.firebase.google.com/

**Comment by kreshikhin** [comment]
Same

**Comment by dikynugraha1111** [comment]
same here.... piye iki dab

**Comment by setya7** [comment]
same here tenan iki, pie slur, down iki

**Comment by bwevers-thegummie** [comment]
same here

**Comment by wurongfeng1995** [comment]
Occurred on Android too

**Comment by thanospapazoglou** [comment]
Seems that the Firebase App Distribution is having issues at the moment.

https://status.firebase.google.com/

**Comment by RohmanBenyRiyanto** [comment]
Same error here, test on Android

**Comment by manucodin** [comment]
+1 here

**Comment by cristianeydev** [comment]
same here

**Comment by prasad-anecure** [comment]
same here

**Comment by tpapazoglou** [comment]
Seems to be fixed guys!
