### ISSUE TITLE
iOS - base64 encoded key parsing error

### ISSUE THREAD

**Issue by ibcylon** [fastlane/fastlane#22047]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Could not parsing base64 encoded API Key in .env key

alternative way, using key file path it works.

##### Command executed

```ruby
 #------------- AppStore Auth --------------------
  desc "Auth AppStoreConnect"
  lane :auth_app do

    app_store_connect_api_key(
      is_key_content_base64: true
    )
  end

 #.env File
APP_STORE_CONNECT_API_KEY_KEY= "encoded key"
  ```
key copied by using follow command
```shell
 openssl base64 < AuthKey_.p8 | tr -d '\n' | pbcopy
```
```shell
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Fastfile:7:in `block in parsing_binding': [!] uninitialized constant Fastlane::FastFile::[KeyString!@#$@$^%&#%^*%^*$^%&$#%$@$#$!%$#^%$#%&%#^$#%@#$!#$@] (NameError)
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:127:in `platform'
	from Fastfile:3:in `parsing_binding'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane_manager.rb:14:in `new'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane_manager.rb:14:in `cruise_lane'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `<main>'
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
    <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 14.4.1                                                     |
| Ruby                        | 3.3.1                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.39.3 (Apple Git-145)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.220.0/libexec/bin/fastlane |
| Host                        | macOS 14.4.1 (23E224)                                      |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.1/lib                        |
| OpenSSL Version             | OpenSSL 3.3.0 9 Apr 2024                                   |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 15.0.1                                                     |
| Swift Version               | 5.9                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ko_KR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.220.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                           | Version | Update-Status |
| -------------------------------- | ------- | ------------- |
| fastlane-plugin-discord_notifier | 0.1.7   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                              | Version      |
| -------------------------------- | ------------ |
| error_highlight                  | 0.6.0        |
| did_you_mean                     | 1.6.3        |
| syntax_suggest                   | 2.0.0        |
| public_suffix                    | 5.0.5        |
| addressable                      | 2.8.6        |
| artifactory                      | 3.0.17       |
| babosa                           | 1.0.4        |
| bundler                          | 2.5.9        |
| base64                           | 0.2.0        |
| CFPropertyList                   | 3.0.7        |
| colored                          | 1.2          |
| highline                         | 2.0.3        |
| commander                        | 4.6.0        |
| dotenv                           | 2.8.1        |
| emoji_regex                      | 3.2.3        |
| excon                            | 0.110.0      |
| faraday-em_http                  | 1.0.0        |
| faraday-em_synchrony             | 1.0.0        |
| faraday-excon                    | 1.1.0        |
| faraday-httpclient               | 1.0.1        |
| faraday-multipart                | 1.0.4        |
| faraday-net_http                 | 1.0.1        |
| faraday-net_http_persistent      | 1.2.0        |
| faraday-patron                   | 1.0.0        |
| faraday-rack                     | 1.0.0        |
| faraday-retry                    | 1.0.3        |
| ruby2_keywords                   | 0.0.5        |
| faraday                          | 1.10.3       |
| faraday_middleware               | 1.2.0        |
| domain_name                      | 0.6.20240107 |
| http-cookie                      | 1.0.5        |
| faraday-cookie_jar               | 0.0.7        |
| fastimage                        | 2.3.1        |
| gh_inspector                     | 1.1.3        |
| uber                             | 0.1.0        |
| declarative                      | 0.0.20       |
| trailblazer-option               | 0.1.2        |
| representable                    | 3.2.0        |
| retriable                        | 3.1.2        |
| mini_mime                        | 1.1.5        |
| jwt                              | 2.8.1        |
| multi_json                       | 1.15.0       |
| os                               | 1.1.4        |
| signet                           | 0.19.0       |
| googleauth                       | 1.8.1        |
| httpclient                       | 2.8.3        |
| google-apis-core                 | 0.11.3       |
| google-apis-androidpublisher_v3  | 0.54.0       |
| google-apis-playcustomapp_v1     | 0.13.0       |
| google-cloud-env                 | 1.6.0        |
| google-cloud-errors              | 1.4.0        |
| google-cloud-core                | 1.7.0        |
| google-apis-iamcredentials_v1    | 0.17.0       |
| google-apis-storage_v1           | 0.31.0       |
| digest-crc                       | 0.6.5        |
| google-cloud-storage             | 1.47.0       |
| mini_magick                      | 4.12.0       |
| naturally                        | 2.2.1        |
| plist                            | 3.7.1        |
| rubyzip                          | 2.3.2        |
| security                         | 0.1.5        |
| simctl                           | 1.6.10       |
| terminal-notifier                | 2.0.0        |
| unicode-display_width            | 2.5.0        |
| terminal-table                   | 3.0.2        |
| tty-screen                       | 0.8.2        |
| tty-cursor                       | 0.7.1        |
| tty-spinner                      | 0.9.3        |
| word_wrap                        | 1.0.0        |
| atomos                           | 0.1.3        |
| claide                           | 1.1.0        |
| colored2                         | 3.1.2        |
| nanaimo                          | 0.3.0        |
| xcodeproj                        | 1.24.0       |
| rouge                            | 2.0.7        |
| xcpretty                         | 0.3.0        |
| xcpretty-travis-formatter        | 1.0.1        |
| set                              | 1.1.0        |
| aws-eventstream                  | 1.3.0        |
| aws-sigv4                        | 1.8.0        |
| aws-partitions                   | 1.931.0      |
| jmespath                         | 1.6.2        |
| aws-sdk-core                     | 3.196.1      |
| aws-sdk-kms                      | 1.81.0       |
| aws-sdk-s3                       | 1.151.0      |
| strscan                          | 3.1.0        |
| rexml                            | 3.2.8        |
| nkf                              | 0.2.0        |
| multipart-post                   | 2.4.1        |
| rake                             | 13.2.1       |
| json                             | 2.7.2        |
| optparse                         | 0.5.0        |
| forwardable                      | 1.3.3        |
| logger                           | 1.6.0        |
| pathname                         | 0.3.0        |
| shellwords                       | 0.2.0        |
| cgi                              | 0.4.1        |
| date                             | 3.3.4        |
| timeout                          | 0.4.1        |
| securerandom                     | 0.3.1        |
| uri                              | 0.13.0       |
| openssl                          | 3.2.0        |
| digest                           | 3.1.1        |
| ipaddr                           | 1.2.6        |
| resolv                           | 0.3.0        |
| time                             | 0.3.0        |
| stringio                         | 3.1.0        |
| open-uri                         | 0.4.1        |
| mutex_m                          | 0.2.0        |
| net-http                         | 0.4.1        |
| net-protocol                     | 0.2.2        |
| english                          | 0.8.0        |
| erb                              | 4.0.3        |
| abbrev                           | 0.1.2        |
| tempfile                         | 0.2.1        |
| delegate                         | 0.3.1        |
| fileutils                        | 1.7.2        |
| tmpdir                           | 0.2.0        |
| ffi                              | 1.16.3       |
| rbnacl                           | 3.4.0        |
| singleton                        | 0.2.0        |
| open3                            | 0.2.1        |
| prettyprint                      | 0.2.0        |
| pp                               | 0.5.0        |
| find                             | 0.2.0        |
| ostruct                          | 0.6.0        |
| yaml                             | 0.3.0        |
| psych                            | 5.1.2        |
| http-accept                      | 1.7.0        |
| mime-types-data                  | 3.2024.0507  |
| mime-types                       | 3.5.2        |
| netrc                            | 0.11.0       |
| rest-client                      | 2.1.0        |
| opus-ruby                        | 1.0.1        |
| websocket                        | 1.2.10       |
| event_emitter                    | 0.2.6        |
| websocket-client-simple          | 0.8.0        |
| discordrb-webhooks               | 3.3.0        |
| discordrb                        | 3.3.0        |
| fastlane-plugin-discord_notifier | 0.1.7        |
</details>

*generated on:* **2024-05-23**
</details>
 </pre>
</details>

### Environment

<details>
  <pre> 
     fastlane 2.220
 </pre>
</details>

**Comment by gladys1258williams** [comment]
Issue #22047 involves a parsing error for a base64 encoded API key within an OS environment, requiring an alternative key file path solution. [vanillagift.com](https://www.vanilla-giftcardbalance.com)

**Comment by iBotPeaches** [comment]
I know this is 2y old, but I just [tested](https://github.com/fastlane/fastlane/issues/22281#issuecomment-4081502997) another bug which confirms I cannot replicate this. Closing as not reproducible.
