### ISSUE TITLE
Failed to sign application using multiple provisions

### ISSUE THREAD

**Issue by burakkilic41** [fastlane/fastlane#22057]
Hello everyone,
 
We want to re-sign an apple watch app. To sign the application, we need to use two provisions.
 
An error is received when trying to sign using the Resign method. Also, can we sign with multi provision in fastlane cli?
 
The resign method has been added to the fastfile as follows.

**Fastfile**
```
lane :do_resign do
resign(
  ipa: "app.ipa", # can omit if using the `ipa` action
  signing_identity: "Apple Distribution: xxx (xxx)",
  provisioning_profile: {
    "xxx.xxx.xxx" => "xxx.xxx.xxx.mobileprovision",
    "xxx.xxx.xxx.xxx" => "xxx.xxx.xxx.xxx.mobileprovision"
  }
)
end
```

**Error log:**

<details><summary>Details</summary>
<p>

11:19:10  DEBUG [2024-05-31 11:19:09.85]: Checking if there are any plugins that should be loaded...
11:19:10  INFO [2024-05-31 11:19:10.14]: [32mDriving the lane 'do_resign' 🚀[0m
11:19:10  INFO [2024-05-31 11:19:10.14]: [32m--------------------[0m
11:19:10  INFO [2024-05-31 11:19:10.14]: [32m--- Step: resign ---[0m
11:19:10  INFO [2024-05-31 11:19:10.14]: [32m--------------------[0m
11:19:10  [35m/usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/assets/resign.sh app.ipa xxxx -p xxx.xxx.xxx=/Users/burak/xxx.xxx.xxx.mobileprovision -p xxx.xxx.xxx.xxx=/Users/burak/xxx.xxx.xxx.xxx.mobileprovision       -v   app.ipa[0m
11:19:10  ls: _floatsignTemp/Payload/: No such file or directory
11:19:10  find: _floatsignTemp/Payload/: No such file or directory
11:19:10  Expected file does not exist: '_floatsignTemp/Payload//Info.plist'
11:19:10  Specified provisioning profile: '/Users/burak/xxx.xxx.xxx.mobileprovision' for bundle identifier: 'xxx.xxx.xxx'
11:19:10  Specified provisioning profile: '/Users/burak/xxx.xxx.xxx.xxx.mobileprovision' for bundle identifier: 'xxx.xxx.xxx.xxx'
11:19:10  Original file: 'app.ipa'
11:19:10  Certificate: 'xxxx'
11:19:10  Output file name: 'app.ipa'
11:19:10  Removing previous temporary directory: '_floatsignTemp'
11:19:10  ERROR [2024-05-31 11:19:10.60]: [31mSomething went wrong while code signing app.ipa[0m
11:19:10  WARN [2024-05-31 11:19:10.60]: [33m[33mLane Context:[0m
11:19:10  INFO [2024-05-31 11:19:10.60]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"do_resign"}
11:19:10  ERROR [2024-05-31 11:19:10.60]: [31mFailed to re-sign .ipa[0m
11:19:10  INFO [2024-05-31 11:19:10.60]: [32mSuccessfully generated documentation at path '/Users/burak/fastlane/README.md'[0m
11:19:10 
11:19:10  +-----------------------------+
11:19:10  |      [32mfastlane summary[0m       |
11:19:10  +------+--------+-------------+
11:19:10  | Step | Action | Time (in s) |
11:19:10  +------+--------+-------------+
11:19:10  | 💥   | [31mresign[0m | 0           |
11:19:10  +------+--------+-------------+
11:19:10 
11:19:10  ERROR [2024-05-31 11:19:10.60]: [31mfastlane finished with errors[0m
11:19:10  /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [31m[!] Failed to re-sign .ipa[0m (FastlaneCore::Interface::FastlaneError)

</p>
</details> 

**Fastlane env:**
<details><summary>Details</summary>
<p>

11:19:08  | Key                         | Value                                                   |
11:19:08  | --------------------------- | ------------------------------------------------------- |
11:19:08  | OS                          | 12.7.4                                                  |
11:19:08  | Ruby                        | 3.3.1                                                   |
11:19:08  | Bundler?                    | false                                                   |
11:19:08  | Git                         | git version 2.37.0 (Apple Git-136)                      |
11:19:08  | Installation Source         | /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane |
11:19:08  | Host                        | macOS 12.7.4                            |
11:19:08  | Ruby Lib Dir                | /usr/local/Cellar/ruby/3.3.1/lib                        |
11:19:08  | OpenSSL Version             | OpenSSL 3.3.0 9 Apr 2024                                |
11:19:08  | Is contained                | false                                                   |
11:19:08  | Is homebrew                 | true                                                    |
11:19:08  | Is installed via Fabric.app | false                                                   |
11:19:08  | Xcode Path                  | /Applications/Xcode14.app/Contents/Developer/           |
11:19:08  | Xcode Version               | 14.0                                                    |
11:19:08  | Swift Version               | 5.7                                                     |
11:19:08  
11:19:08  
11:19:08  ### System Locale
11:19:08  
11:19:08  | Variable | Value       |   |
11:19:08  | -------- | ----------- | - |
11:19:08  | LANG     | en_US.UTF-8 | ✅ |
11:19:08  | LC_ALL   | en_US.UTF-8 | ✅ |
11:19:08  | LANGUAGE |             |   |
11:19:08  
11:19:08  
11:19:08  ### fastlane files:
11:19:08  
11:19:08  <details><summary>`./fastlane/Fastfile`</summary>
11:19:08  
11:19:08  ```ruby
11:19:08  lane :do_resign do
11:19:08  resign(
11:19:08    ipa: "app.ipa", # can omit if using the `ipa` action
11:19:08    signing_identity: "Apple Distribution: xxx (xxx)",
11:19:08    provisioning_profile: {
11:19:08      "xxx.xxx.xxx" => "xxx.xxx.xxx.mobileprovision",
11:19:08      "xxx.xxx.xxx.xxx" => "xxx.xxx.xxx.xxx.mobileprovision"
11:19:08    }
11:19:08  )
11:19:08  end ```
11:19:08  </details>
11:19:08  **No Appfile found**
11:19:08  
11:19:08  
11:19:08  ### fastlane gems
11:19:08  
11:19:08  | Gem      | Version | Update-Status |
11:19:08  | -------- | ------- | ------------- |
11:19:08  | fastlane | 2.220.0 | ✅ Up-To-Date  |
11:19:08  
11:19:08  
11:19:08  ### Loaded fastlane plugins:
11:19:08  
11:19:08  **No plugins Loaded**
11:19:08  
11:19:08  
11:19:08  <details><summary><b>Loaded gems</b></summary>
11:19:08  
11:19:08  | Gem                             | Version      |
11:19:08  | ------------------------------- | ------------ |
11:19:08  | error_highlight                 | 0.6.0        |
11:19:08  | did_you_mean                    | 1.6.3        |
11:19:08  | syntax_suggest                  | 2.0.0        |
11:19:08  | public_suffix                   | 5.0.5        |
11:19:08  | addressable                     | 2.8.6        |
11:19:08  | artifactory                     | 3.0.17       |
11:19:08  | jmespath                        | 1.6.2        |
11:19:08  | aws-partitions                  | 1.907.0      |
11:19:08  | aws-eventstream                 | 1.3.0        |
11:19:08  | aws-sigv4                       | 1.8.0        |
11:19:08  | aws-sdk-core                    | 3.191.6      |
11:19:08  | aws-sdk-kms                     | 1.78.0       |
11:19:08  | aws-sdk-s3                      | 1.146.1      |
11:19:08  | babosa                          | 1.0.4        |
11:19:08  | bundler                         | 2.5.9        |
11:19:08  | rexml                           | 3.2.6        |
11:19:08  | nkf                             | 0.1.3        |
11:19:08  | base64                          | 0.2.0        |
11:19:08  | CFPropertyList                  | 3.0.7        |
11:19:08  | colored                         | 1.2          |
11:19:08  | highline                        | 2.0.3        |
11:19:08  | commander                       | 4.6.0        |
11:19:08  | dotenv                          | 2.8.1        |
11:19:08  | emoji_regex                     | 3.2.3        |
11:19:08  | excon                           | 0.110.0      |
11:19:08  | faraday-em_http                 | 1.0.0        |
11:19:08  | faraday-em_synchrony            | 1.0.0        |
11:19:08  | faraday-excon                   | 1.1.0        |
11:19:08  | faraday-httpclient              | 1.0.1        |
11:19:08  | multipart-post                  | 2.4.0        |
11:19:08  | faraday-multipart               | 1.0.4        |
11:19:08  | faraday-net_http                | 1.0.1        |
11:19:08  | faraday-net_http_persistent     | 1.2.0        |
11:19:08  | faraday-patron                  | 1.0.0        |
11:19:08  | faraday-rack                    | 1.0.0        |
11:19:08  | faraday-retry                   | 1.0.3        |
11:19:08  | ruby2_keywords                  | 0.0.5        |
11:19:08  | faraday                         | 1.10.3       |
11:19:08  | faraday_middleware              | 1.2.0        |
11:19:08  | domain_name                     | 0.6.20240107 |
11:19:08  | http-cookie                     | 1.0.5        |
11:19:08  | faraday-cookie_jar              | 0.0.7        |
11:19:08  | fastimage                       | 2.3.1        |
11:19:08  | gh_inspector                    | 1.1.3        |
11:19:08  | uber                            | 0.1.0        |
11:19:08  | declarative                     | 0.0.20       |
11:19:08  | trailblazer-option              | 0.1.2        |
11:19:08  | representable                   | 3.2.0        |
11:19:08  | retriable                       | 3.1.2        |
11:19:08  | mini_mime                       | 1.1.5        |
11:19:08  | jwt                             | 2.8.1        |
11:19:08  | multi_json                      | 1.15.0       |
11:19:08  | os                              | 1.1.4        |
11:19:08  | signet                          | 0.19.0       |
11:19:08  | googleauth                      | 1.8.1        |
11:19:08  | httpclient                      | 2.8.3        |
11:19:08  | google-apis-core                | 0.11.3       |
11:19:08  | google-apis-androidpublisher_v3 | 0.54.0       |
11:19:08  | google-apis-playcustomapp_v1    | 0.13.0       |
11:19:08  | google-cloud-env                | 1.6.0        |
11:19:08  | google-cloud-errors             | 1.4.0        |
11:19:08  | google-cloud-core               | 1.7.0        |
11:19:08  | google-apis-iamcredentials_v1   | 0.17.0       |
11:19:08  | google-apis-storage_v1          | 0.31.0       |
11:19:08  | rake                            | 13.2.0       |
11:19:08  | digest-crc                      | 0.6.5        |
11:19:08  | google-cloud-storage            | 1.47.0       |
11:19:08  | json                            | 2.7.1        |
11:19:08  | mini_magick                     | 4.12.0       |
11:19:08  | naturally                       | 2.2.1        |
11:19:08  | optparse                        | 0.4.0        |
11:19:08  | plist                           | 3.7.1        |
11:19:08  | rubyzip                         | 2.3.2        |
11:19:08  | security                        | 0.1.5        |
11:19:08  | simctl                          | 1.6.10       |
11:19:08  | terminal-notifier               | 2.0.0        |
11:19:08  | unicode-display_width           | 2.5.0        |
11:19:08  | terminal-table                  | 3.0.2        |
11:19:08  | tty-screen                      | 0.8.2        |
11:19:08  | tty-cursor                      | 0.7.1        |
11:19:08  | tty-spinner                     | 0.9.3        |
11:19:08  | word_wrap                       | 1.0.0        |
11:19:08  | atomos                          | 0.1.3        |
11:19:08  | claide                          | 1.1.0        |
11:19:08  | colored2                        | 3.1.2        |
11:19:08  | nanaimo                         | 0.3.0        |
11:19:08  | xcodeproj                       | 1.24.0       |
11:19:08  | rouge                           | 2.0.7        |
11:19:08  | xcpretty                        | 0.3.0        |
11:19:08  | xcpretty-travis-formatter       | 1.0.1        |
11:19:08  | set                             | 1.1.0        |
11:19:08  | forwardable                     | 1.3.3        |
11:19:08  | logger                          | 1.6.0        |
11:19:08  | pathname                        | 0.3.0        |
11:19:08  | shellwords                      | 0.2.0        |
11:19:08  | cgi                             | 0.4.1        |
11:19:08  | date                            | 3.3.4        |
11:19:08  | timeout                         | 0.4.1        |
11:19:08  | securerandom                    | 0.3.1        |
11:19:08  | uri                             | 0.13.0       |
11:19:08  | openssl                         | 3.2.0        |
11:19:08  | digest                          | 3.1.1        |
11:19:08  | ipaddr                          | 1.2.6        |
11:19:08  | resolv                          | 0.3.0        |
11:19:08  | time                            | 0.3.0        |
11:19:08  | stringio                        | 3.1.0        |
11:19:08  | open-uri                        | 0.4.1        |
11:19:08  | mutex_m                         | 0.2.0        |
11:19:08  | net-http                        | 0.4.1        |
11:19:08  | net-protocol                    | 0.2.2        |
11:19:08  | ostruct                         | 0.6.0        |
11:19:08  | english                         | 0.8.0        |
11:19:08  | erb                             | 4.0.3        |
11:19:08  | abbrev                          | 0.1.2        |
11:19:08  | tempfile                        | 0.2.1        |
11:19:08  | delegate                        | 0.3.1        |
11:19:08  | fileutils                       | 1.7.2        |
11:19:08  | tmpdir                          | 0.2.0        |
11:19:08  | singleton                       | 0.2.0        |
11:19:08  | open3                           | 0.2.1        |
11:19:08  | prettyprint                     | 0.2.0        |
11:19:08  | pp                              | 0.5.0        |
11:19:08  | find                            | 0.2.0        |
11:19:08  | yaml                            | 0.3.0        |
11:19:08  | psych                           | 5.1.2        |
</details>

</p>
</details>

**Comment by burakkilic41** [comment]
I used command bellow for resign the app, but I got an error again.
```
fastlane sigh resign app.ipa --signing_identity ‘xxx’ -p xxx.xxx.xxx=xxx.xxx.xxx.mobileprovision -p xxx.xxx.xxx.xxx=xxx.xxx.xxx.xxx.mobileprovision --verbose
``` 

13:52:21  [13:52:21]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
13:52:22  [35m/usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/assets/resign.sh app.ipa xxxxxxxxxxCertificateId -p xxx.xxx.xxx=/Users/burak/xxx.xxx.xxx.mobileprovision -p xxx.xxx.xxx.xxx=/Users/burak/xxx.xxx.xxx.xxx.mobileprovision       -v   app.ipa[0m
13:52:22  ls: _floatsignTemp/Payload/: No such file or directory
13:52:22  find: _floatsignTemp/Payload/: No such file or directory
13:52:22  Expected file does not exist: '_floatsignTemp/Payload//Info.plist'
13:52:22  Specified provisioning profile: '/Users/burak/xxx.xxx.xxx.mobileprovision' for bundle identifier: ‘xxx.xxx.xxx’
13:52:22  Specified provisioning profile: '/Users/burak/xxx.xxx.xxx.xxx.mobileprovision' for bundle identifier: ‘xxx.xxx.xxx.xxx’
13:52:22  Original file: 'app.ipa'
13:52:22  Certificate: 'xxxxxxxxxxCertificateId'
13:52:22  Output file name: 'app.ipa'
13:52:22  Removing previous temporary directory: '_floatsignTemp'
13:52:22  ERROR [2024-06-07 13:52:22.61]: [31mSomething went wrong while code signing app.ipa[0m
13:52:22  /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [31m[!] Failed to re-sign .ipa[0m (FastlaneCore::Interface::FastlaneError)
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/sigh/resign.rb:14:in `run'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:119:in `block (2 levels) in run'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:140:in `run'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:17:in `start'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `load'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `<main>'
13:52:22  /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Failed to re-sign .ipa (FastlaneCore::Interface::FastlaneError)
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/sigh/resign.rb:14:in `run'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:119:in `block (2 levels) in run'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:140:in `run'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/sigh/lib/sigh/commands_generator.rb:17:in `start'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `load'
13:52:22  	from /usr/local/Cellar/fastlane/2.220.0/libexec/bin/fastlane:25:in `<main>'

**Comment by jennifer0188** [comment]
Hello,

Resigning with Multiple Provisioning Profiles
Ensure Correct Paths: Double-check that the paths to your .ipa file and provisioning profiles are correct.

Update Fastfile: Make sure your Fastfile is correctly configured. Here's an example:


lane :do_resign do
  resign(
    ipa: "app.ipa",
    signing_identity: "Apple Distribution: xxx (xxx)",
    provisioning_profile: {
      "xxx.xxx.xxx" => "path/to/xxx.xxx.xxx.mobileprovision",
      "xxx.xxx.xxx.xxx" => "path/to/xxx.xxx.xxx.xxx.mobileprovision"
    }
  )
end

Check for Errors: Look at the error log to identify any specific issues. For example, if there's a missing file or incorrect path, address those issues
Using Fastlane CLI for Multi Provision Signing
Yes, you can sign with multiple provisions using Fastlane CLI. Here's an example command:

fastlane resign ipa:app.ipa signing_identity:"Apple Distribution: xxx (xxx)" provisioning_profile:{"xxx.xxx.xxx"=>"path/to/xxx.xxx.xxx.mobileprovision","xxx.xxx.xxx.xxx"=>"path/to/xxx.xxx.xxx.xxx.mobileprovision"}

I hope this is helpful to you.


Best Regard,
Jennifer Anderson
