### ISSUE TITLE
Can't use API Keys with notarize

### ISSUE THREAD

**Issue by foux** [fastlane/fastlane#22055]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to use notarize with an API Key. This API Key is valid and is working with other commands (match, ...). Putting the api_key in the same lane or in a pre-lane doesn't change anything.

##### Command executed
`bundle exec fastlane mac buildProd`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[17:39:07]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/3.3.0/bin/fastlane)
/usr/local/lib/ruby/gems/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `parse': [31m[!] unexpected token at 'Error: invalidAsn1 (JSON::ParserError)
'[0m
	from /usr/local/lib/ruby/gems/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `parse'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/actions/notarize.rb:85:in `notarytool'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/actions/notarize.rb:42:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:169:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.3.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.3.0/bin/fastlane:25:in `<top (required)>'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:451:in `exec'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.3.0/bin/bundle:25:in `load'
	from /usr/local/lib/ruby/gems/3.3.0/bin/bundle:25:in `<main>'
/usr/local/lib/ruby/gems/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `parse': unexpected token at 'Error: invalidAsn1 (JSON::ParserError)
'
	from /usr/local/lib/ruby/gems/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `parse'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/actions/notarize.rb:85:in `notarytool'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/actions/notarize.rb:42:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:169:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.3.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.3.0/bin/fastlane:25:in `<top (required)>'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:451:in `exec'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/Cellar/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.3.0/bin/bundle:25:in `load'
	from /usr/local/lib/ruby/gems/3.3.0/bin/bundle:25:in `<main>'
section_end:1716997147:step_script </pre>
</details>

### Environment

<details>
  <pre> [17:56:27]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                      |
| --------------------------- | -------------------------------------------------------------------------- |
| OS                          | 14.5                                                                       |
| Ruby                        | 3.3.1                                                                      |
| Bundler?                    | true                                                                       |
| Git                         | git version 2.39.3 (Apple Git-145)                                         |
| Installation Source         | ~/GIT/Limberapps/salesapps-universal/vendor/bundle/ruby/3.3.0/bin/fastlane |
| Host                        | macOS 14.5 (23F79)                                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.1/lib                                        |
| OpenSSL Version             | OpenSSL 3.3.0 9 Apr 2024                                                   |
| Is contained                | false                                                                      |
| Is homebrew                 | false                                                                      |
| Is installed via Fabric.app | false                                                                      |
| Xcode Path                  | /Applications/Xcode-15.2.0.app/Contents/Developer/                         |
| Xcode Version               | 15.2                                                                       |
| Swift Version               | 5.9.2                                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   | fr_FR.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Upload symbols to Raygun"
private_lane :uploadSymbols do |options|
  Dir.chdir("..") do
    sh('bash', './upload_symbols_to_raygun.sh', options[:dSymFilePath], ENV['RAYGUN_APP_ID'], ENV['RAYGUN_AUTH_TOKEN'])
  end
end

desc "Generate dmg"
private_lane :generateDmg do
  Dir.chdir("../dmg") do
    sh('mv', '../build/Salesapps.app.zip', '.')
    sh('unzip', '-o', 'Salesapps.app.zip')
    sh('cp', 'Salesapps.app/Contents/Resources/AppIcon.icns', '.')
    #sh('mv', 'Salesapps.app', ENV['dmg_app_name'] + '.app')
    sh('appdmg', 'conf.json', ENV['dmg_app_name'] + '.dmg')
    sh('mv', ENV['dmg_app_name'] + '.dmg', '../build/' + ENV['dmg_app_name'] + '.dmg')
    sh('rm', '-rf', ENV['dmg_app_name'] + '.app', 'Salesapps.app.zip', 'AppIcon.icns')
  end
end

before_all do |lane|
  setup_ci
  api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"]
  )
end

platform :ios do

  desc "Build simulator version"
  lane :buildSimulator do
    xcodes(select_for_current_build_only: true)
    cocoapods(
      try_repo_update_on_error: true
    )
    increment_build_number(build_number: number_of_commits)
    increment_version_number(
      version_number: ENV['version_number']
    )
    archive_path=gym(
      skip_package_ipa: true,
      destination: "generic/platform=iOS Simulator",
      configuration: "Debug",
      build_path: "build/simulator_build",
      silent: true,
      suppress_xcode_output: true,
      clean: true,
      catalyst_platform: "ios"
    )
    zip(
      path: "#{archive_path}/Products/Applications/Salesapps.app",
      output_path: "build/Simulator-#{get_version_number}.app.zip",
      verbose: false
    )
    sh "rm", "-rf", "build/simulator_build"
  end


  desc "Build with production configuration"
  lane :buildProd do
    xcodes(select_for_current_build_only: true)
    cocoapods(
      try_repo_update_on_error: true
    )
    match(
      type: "adhoc",
      force: false
    )
    increment_build_number(build_number: number_of_commits)
    increment_version_number(
      version_number: ENV['version_number']
    )
    gym(
      configuration: "AdHoc",
      output_directory: "build",
      output_name: "Prod-#{get_version_number}",
      export_options: { compileBitcode: false, manageAppVersionAndBuildNumber: false },
      silent: true,
      suppress_xcode_output: true,
      clean: true,
      catalyst_platform: "ios"
    )
    uploadSymbols(
      dSymFilePath: "build/Prod-#{get_version_number}.app.dSYM.zip"
    )
  end

  desc "Build with pre-production configuration"
  lane :buildPreprod do
    xcodes(select_for_current_build_only: true)
    cocoapods(
      try_repo_update_on_error: true
    )
    match(
      type: "adhoc",
      force: false
    )
    increment_build_number(build_number: number_of_commits)
    increment_version_number(
      version_number: ENV['version_number']
    )
    gym(
      configuration: "Preprod",
      output_directory: "build",
      output_name: "Preprod-#{get_version_number}",
      export_options: { compileBitcode: false, manageAppVersionAndBuildNumber: false },
      silent: true,
      suppress_xcode_output: true,
      clean: true,
      catalyst_platform: "ios"
    )
    uploadSymbols(
      dSymFilePath: "build/Preprod-#{get_version_number}.app.dSYM.zip"
    )
  end
end

platform :mac do

  desc "Build prod version"
  lane :buildProd do
    xcodes(select_for_current_build_only: true)
    cocoapods(
      try_repo_update_on_error: true
    )
    increment_build_number(build_number: number_of_commits)
    increment_version_number(
      version_number: ENV['version_number']
    )
    match(
      type: "developer_id",
      platform: "catalyst",
    )
    gym(
      configuration: "AdHoc",
      output_directory: "build",
      output_name: "Catalyst-Prod-#{get_version_number}",
      export_options: { compileBitcode: false, method: "developer-id" },
      silent: true,
      suppress_xcode_output: true,
      clean: true,
      catalyst_platform: "macos",
      skip_package_pkg: true
    )
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"]
    )
    notarize(
      package: "build/Salesapps.app",
      asc_provider:"44ES6AQG8S",
      api_key: api_key
    )
    generateDmg()
    dmg_app_name = ENV['dmg_app_name']
    sh('mv', "../build/#{ENV['dmg_app_name']}.dmg", "../build/#{ENV['dmg_app_name']}-Prod-#{get_version_number}.dmg")
  end

  desc "Build preprod version"
  lane :buildPreprod do
    xcodes(select_for_current_build_only: true)
    cocoapods(
      try_repo_update_on_error: true
    )
    increment_build_number(build_number: number_of_commits)
    increment_version_number(
      version_number: ENV['version_number']
    )
    match(
      type: "developer_id",
      platform: "catalyst"
    )
    gym(
      configuration: "Preprod",
      output_directory: "build",
      output_name: "Catalyst-Preprod-#{get_version_number}",
      export_options: { compileBitcode: false, method: "developer-id" },
      silent: true,
      suppress_xcode_output: true,
      clean: true,
      catalyst_platform: "macos",
      skip_package_pkg: true
    )
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"]
    )
    notarize(
      package: "build/Salesapps.app",
      asc_provider:"44ES6AQG8S",
      api_key: api_key
    )
    generateDmg()
    dmg_app_name = ENV['dmg_app_name']
    sh('mv', "../build/#{ENV['dmg_app_name']}.dmg", "../build/#{dmg_app_name}-Preprod-#{ENV['dmg_app_name']}.dmg")
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "identifier"
team_id "xxxx"
itc_team_id "xxxx"
ENV['version_number'] = "xxxx"
ENV['dmg_app_name'] = "xxxxx"
ENV["RAYGUN_APP_ID"] = "xxxx"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.220.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.6.0        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.0        |
| bundler                         | 2.5.9        |
| pathname                        | 0.3.0        |
| rake                            | 13.2.1       |
| base64                          | 0.2.0        |
| nkf                             | 0.2.0        |
| strscan                         | 3.1.0        |
| rexml                           | 3.2.8        |
| CFPropertyList                  | 3.0.7        |
| bigdecimal                      | 3.1.8        |
| concurrent-ruby                 | 1.3.1        |
| connection_pool                 | 2.4.1        |
| drb                             | 2.2.1        |
| i18n                            | 1.14.5       |
| minitest                        | 5.23.1       |
| mutex_m                         | 0.2.0        |
| tzinfo                          | 2.0.6        |
| activesupport                   | 7.1.3.3      |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.6        |
| httpclient                      | 2.8.3        |
| json                            | 2.7.2        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.17       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.3.0        |
| aws-partitions                  | 1.935.0      |
| aws-sigv4                       | 1.8.0        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.196.1      |
| aws-sdk-kms                     | 1.82.0       |
| aws-sdk-s3                      | 1.151.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.16.3       |
| ethon                           | 0.16.0       |
| typhoeus                        | 1.4.1        |
| cocoapods-core                  | 1.15.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 2.1          |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.24.0       |
| cocoapods                       | 1.15.2       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.5        |
| domain_name                     | 0.6.20240107 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.110.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.3.1        |
| jwt                             | 2.8.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.0        |
| google-cloud-storage            | 1.47.0       |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.5.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2024-05-29**
</details>
[17:56:29]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[17:56:29]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m
</pre>
</details>

**Comment by blanca236** [comment]
Hello,
It sounds like you’re encountering an issue with using the Notarize API Key. Here are some steps you can take to troubleshoot and resolve the issue: Check API Key Validity: Ensure that the API Key you are using is valid and has the necessary permissions for the Notarize command. Sometimes, API keys have different scopes or permissions. API Key Placement: Make sure that the API Key is correctly placed in your configuration. It should be in the appropriate section of your configuration file or script.
Update Fastlane: Ensure that you are using the latest version of Fastlane. Sometimes, issues are resolved in newer versions of the software. Check Documentation: Refer to the Notarize API documentation to ensure that you are following the correct procedure for using the API Key. There might be specific requirements or steps that need to be followed. Error Messages: Pay attention to any error messages you receive. They can provide clues about what might be going wrong. Common issues include incorrect API Key format, missing permissions, or network-related problems. Community Support: Check online forums, GitHub issues, or community support channels for similar issues. Other users might have encountered and resolved the same problem. Contact Support: If you have tried all the above steps and still cannot resolve the issue, consider reaching out to Notarize support for assistance. They can provide specific guidance based on your setup and the issue you are facing.
By following these steps, you should be able to identify and resolve the issue with using the Notarize API Key. If you need further assistance, feel free to ask!
Best Regard
[MyFordBenefits](https://www.my-fordbenefits.com)

**Comment by foux** [comment]
> Hello, It sounds like you’re encountering an issue with using the Notarize API Key. Here are some steps you can take to troubleshoot and resolve the issue: Check API Key Validity: Ensure that the API Key you are using is valid and has the necessary permissions for the Notarize command. 

The API key is valid (working on other lanes) and has the correct permissions

> Sometimes, API keys have different scopes or permissions. API Key Placement: Make sure that the API Key is correctly placed in your configuration. It should be in the appropriate section of your configuration file or script. 

Yep, all good, and working with other fastlane commands

> Update Fastlane: Ensure that you are using the latest version of Fastlane. Sometimes, issues are resolved in newer versions of the software. 

Already on latest version

> Check Documentation: Refer to the Notarize API documentation to ensure that you are following the correct procedure for using the API Key. There might be specific requirements or steps that need to be followed. 

I am

**Comment by m-kuhn** [comment]
Just had that same error `Error: invalidAsn1` (outside fastlane) and struggled to find any information anywhere.
It turned out that my private key was corrupted during copy paste (replaced newlines with spaces).

**Comment by iBotPeaches** [comment]
Closing as the error `invalidAsn1` suggests the key is malformed. OpenSSL got stricter and thus this became a problem when it probably wasn't in past. Our detection is better too now to detect it. Sorry it took us a bit to triage this.
