### ISSUE TITLE
[Deliver] Improve documentation for macOS since the Quick Start results with error

### ISSUE THREAD

**Issue by funnel20** [fastlane/fastlane#22107]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm a fan of Deliver for my iOS apps, and wanted to implement it for my first macOS app.
So I just run the Quick Start guide at https://docs.fastlane.tools/actions/deliver/#quick-start where `fastlane deliver init` resulted with **"undefined method `get_app_store_version_localizations' for nil:NilClass (NoMethodError)"**. See below for details.

It shows 2 relevant existing issues:
➡️  Uploading to App Store via deliver fails <NoMethodError: undefined method `get_app_store_version_localizations' for nil:NilClass>
    https://github.com/fastlane/fastlane/issues/18248 [closed] 5 💬
    26 Jun 2021

➡️  deliver: is macOS apps supported with deliver? devliver init fails
    https://github.com/fastlane/fastlane/issues/17367 [closed] 2 💬
    08 Jan 2021

Unfortunately both are closed by the bot, without any comments.

## Solution
When I focussed on the table with parameters, my eye was caught by `platform` which was set to "ios".
Reading the [parameter docu](https://docs.fastlane.tools/actions/deliver/#more-options) I discovered:
> The platform of your application (a.e. ios, osx).
>
> This option is optional. The default value is "ios" and deliver should be able to figure out the platform from your binary.
>
> However, in the case if multiple binaries present, you can specify a platform which you want to deliver explicitly.
> 
> The available options:
>
> 'ios'
> 'appletvos'
> 'osx'

When appending this parameter with value "osx", so `fastlane deliver init --platform "osx"` resulted in a correct initial download from App Store Connect without errors. ✅

# Mitigation
In order to assist users better to understand and resolve this issue themselves, I highly recommend to:

1. Reopen the above issues https://github.com/fastlane/fastlane/issues/18248 and https://github.com/fastlane/fastlane/issues/17367 and **add a clear comment with the above instruction** to include `--platform "osx"`. Because users that will face this issue will click on those links, but currently feel abandoned with no information.
2. Update the Description for key `platform` when using `fastlane action deliver` by showing all valid string values, since it currently only shows the default value:
   ```| platform   | The platform to use (optional)   | DELIVER_PLATFORM   | ios     |```
3. Update the Quick Start guide at https://docs.fastlane.tools/actions/deliver/#quick-start by excitedly mentioning to use parameter `--platform` when using another than iOS.

##### Command executed
`fastlane deliver init`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
(base) MBPMartnKoopman:fastlane Martijn$ fastlane deliver init
[✔] 🚀 
[15:15:35]: To not be asked about this value, you can specify it using 'username'
[15:15:35]: Your Apple ID Username: XXX
[15:15:42]: Login to App Store Connect (XXX)
[15:15:44]: Login successful
[15:15:44]: The Bundle Identifier of your App: YYY

+------------------------------------------------------------------+
|                     deliver 2.221.1 Summary                      |
+--------------------------------------+---------------------------+
| run_precheck_before_submit           | false                     |
| username                             | XXX                       |
| app_identifier                       | YYY                       |
| screenshots_path                     | ./screenshots             |
| metadata_path                        | ./metadata                |
| platform                             | ios                       |
| edit_live                            | false                     |
| use_live_version                     | false                     |
| skip_binary_upload                   | false                     |
| skip_screenshots                     | false                     |
| skip_metadata                        | false                     |
| skip_app_version_update              | false                     |
| force                                | false                     |
| overwrite_screenshots                | false                     |
| screenshot_processing_timeout        | 3600                      |
| sync_screenshots                     | false                     |
| submit_for_review                    | false                     |
| verify_only                          | false                     |
| reject_if_possible                   | false                     |
| version_check_wait_retry_limit       | 7                         |
| phased_release                       | false                     |
| reset_ratings                        | false                     |
| precheck_default_rule_level          | warn                      |
| ignore_language_directory_validation | false                     |
| precheck_include_in_app_purchases    | true                      |
+--------------------------------------+---------------------------+

[15:15:57]: Writing to './metadata/en-GB/name.txt'
[15:15:57]: Writing to './metadata/en-GB/subtitle.txt'
[15:15:57]: Writing to './metadata/en-GB/privacy_url.txt'
[15:15:57]: Writing to './metadata/en-GB/apple_tv_privacy_policy.txt'

Looking for related GitHub issues on fastlane/fastlane...

➡️  [deliver][produce][spaceship] Update to use new App Store Connect API endpoints
    https://github.com/fastlane/fastlane/pull/16626 [closed] 140 💬
    24 Nov 2023

➡️  Uploading to App Store via deliver fails <NoMethodError: undefined method `get_app_store_version_localizations' for nil:NilClass>
    https://github.com/fastlane/fastlane/issues/18248 [closed] 5 💬
    26 Jun 2021

➡️  deliver: is macOS apps supported with deliver? devliver init fails
    https://github.com/fastlane/fastlane/issues/17367 [closed] 2 💬
    08 Jan 2021

and 2 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60get_app_store_version_localizations%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	16: from /Users/Martijn/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	15: from /Users/Martijn/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	14: from /Users/Martijn/.rvm/gems/ruby-2.7.2/bin/fastlane:23:in `<main>'
	13: from /Users/Martijn/.rvm/gems/ruby-2.7.2/bin/fastlane:23:in `load'
	12: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/bin/fastlane:23:in `<top (required)>'
	11: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	10: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/commands_generator.rb:18:in `start'
	 9: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/commands_generator.rb:187:in `run'
	 8: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	 7: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	 6: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 5: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 4: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 3: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/commands_generator.rb:119:in `block (2 levels) in run'
	 2: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/setup.rb:20:in `run'
	 1: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/setup.rb:48:in `generate_deliver_file'
/Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/setup.rb:87:in `generate_metadata_files': undefined method `get_app_store_version_localizations' for nil:NilClass (NoMethodError)
	16: from /Users/Martijn/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	15: from /Users/Martijn/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	14: from /Users/Martijn/.rvm/gems/ruby-2.7.2/bin/fastlane:23:in `<main>'
	13: from /Users/Martijn/.rvm/gems/ruby-2.7.2/bin/fastlane:23:in `load'
	12: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/bin/fastlane:23:in `<top (required)>'
	11: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	10: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/commands_generator.rb:18:in `start'
	 9: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/commands_generator.rb:187:in `run'
	 8: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	 7: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	 6: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 5: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 4: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 3: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/commands_generator.rb:119:in `block (2 levels) in run'
	 2: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/setup.rb:20:in `run'
	 1: from /Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/setup.rb:48:in `generate_deliver_file'
/Users/Martijn/.rvm/gems/ruby-2.7.2/gems/fastlane-2.221.1/deliver/lib/deliver/setup.rb:87:in `generate_metadata_files': \e[31m[!] undefined method `get_app_store_version_localizations' for nil:NilClass\e[0m (NoMethodError)

</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.5                                        |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.3 (Apple Git-146)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.2/bin/fastlane         |
| Host                        | macOS 14.5 (23F79)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.4                                        |
| Swift Version               | 5.10                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.221.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.3.26       |
| artifactory                     | 3.0.15       |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.482.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-sdk-core                    | 3.119.0      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.98.0       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.6.0        |
| faraday_middleware              | 1.1.0        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.6.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 13.0.1       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| uri                             | 0.10.0       |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.1        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| json                            | 2.6.2        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.23.0       |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2024-06-22**
</details> </pre>
</details>

**Comment by monixca345** [comment]
Ojhk i want to know more on this topic.

**Comment by funnel20** [comment]
@monixca345 This is not YouTube or so where you subscribe to a topic and get bombarded with (irrelevant) information. This platform is where people help each other by using their brains. So when you need information, be specific in what you ask, so others can provide an accurate response.
