### ISSUE TITLE
Fastlane Snapshot devices defaults to Mac

### ISSUE THREAD

**Issue by tunds** [fastlane/fastlane#22150]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to run fastlane snapshot to generate screenshots for my project, but it keeps on failing with the following error 

```
/opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/device_manager.rb:135:in `latest_simulator_version_for_device': [!] undefined method `os_version' for nil
```

I am currently using Xcode 16 Beta 3 and I have noticed in the summary for the fastlane output, even though I am specifying the specific iPhone devices. Fastlane snapshot is defaulting to Mac as a device to take screenshots on.

##### Command executed
`fastlane snapshot --verbose`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[07:06:36]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
INFO [2024-07-19 07:06:36.90]: Successfully loaded '/Users/xxxxx/Developer/xxxxx/Snapfile' 📄

+----------------------------------------------------+
|         Detected Values from './Snapfile'          |
+----------------------------+-----------------------+
| devices                    | ["iPhone 15 Pro"]     |
| languages                  | ["en-US"]             |
| scheme                     | AppScreenshotsUITests |
| output_directory           | ./screenshots         |
| clear_previous_screenshots | true                  |
| override_status_bar        | true                  |
| ios_version                | 18.0                  |
+----------------------------+-----------------------+

DEBUG [2024-07-19 07:06:36.91]: Fetching available simulator devices
WARN [2024-07-19 07:06:37.05]: Resolving Swift Package Manager dependencies...
INFO [2024-07-19 07:06:37.05]: $ xcodebuild -resolvePackageDependencies -scheme AppScreenshotsUITests -project ./ColorPalletes.xcodeproj
INFO [2024-07-19 07:06:37.35]: ▸ Command line invocation:
INFO [2024-07-19 07:06:37.35]: ▸     /Applications/Xcode-16.0.0-Beta.3.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme AppScreenshotsUITests -project ./ColorPalletes.xcodeproj
INFO [2024-07-19 07:06:37.35]: ▸ User defaults from command line:
INFO [2024-07-19 07:06:37.35]: ▸     IDEPackageSupportUseBuiltinSCM = YES
INFO [2024-07-19 07:06:37.47]: ▸ Resolve Package Graph
INFO [2024-07-19 07:06:37.63]: ▸ Resolved source packages:
INFO [2024-07-19 07:06:37.63]: ▸   swift-algorithms: https://github.com/apple/swift-algorithms.git @ 1.2.0
INFO [2024-07-19 07:06:37.63]: ▸   swift-collections: https://github.com/apple/swift-collections.git @ 1.1.0
INFO [2024-07-19 07:06:37.63]: ▸   swift-numerics: https://github.com/apple/swift-numerics.git @ 1.0.2
INFO [2024-07-19 07:06:37.63]: ▸   ZIPFoundation: https://github.com/weichsel/ZIPFoundation.git @ 0.9.19
INFO [2024-07-19 07:06:37.63]: ▸ resolved source packages: swift-algorithms, swift-collections, swift-numerics, ZIPFoundation
INFO [2024-07-19 07:06:37.64]: $ xcodebuild -showBuildSettings -scheme AppScreenshotsUITests -project ./ColorPalletes.xcodeproj 2>&1
DEBUG [2024-07-19 07:06:38.38]: Fetching available simulator devices
DEBUG [2024-07-19 07:06:38.45]: Fetching available simulator devices
DEBUG [2024-07-19 07:06:38.53]: Found 46 simulators.
DEBUG [2024-07-19 07:06:38.53]: Fetching available simulator devices
DEBUG [2024-07-19 07:06:38.61]: Checking that helper files contain SnapshotHelperVersion [1.30]

+-----------------------------------------------------------------------------------------+
|                              Summary for snapshot 2.221.1                               |
+--------------------------------------+--------------------------------------------------+
| project                              | ./xxxx.xcodeproj                        |
| devices                              | ["Mac"]                                          |
| languages                            | ["en-US"]                                        |
| launch_arguments                     | [""]                                             |
| output_directory                     | /Users/xxxxx/Developer/xxxx/screenshots |
| output_simulator_logs                | false                                            |
| ios_version                          | 18.0                                             |
| skip_open_summary                    | false                                            |
| skip_helper_version_check            | false                                            |
| clear_previous_screenshots           | true                                             |
| reinstall_app                        | false                                            |
| erase_simulator                      | false                                            |
| headless                             | true                                             |
| override_status_bar                  | true                                             |
| localize_simulator                   | false                                            |
| buildlog_path                        | ~/Library/Logs/snapshot                          |
| clean                                | false                                            |
| scheme                               | AppScreenshotsUITests                            |
| number_of_retries                    | 1                                                |
| stop_after_first_error               | false                                            |
| result_bundle                        | false                                            |
| concurrent_simulators                | true                                             |
| disable_slide_to_type                | false                                            |
| skip_package_dependencies_resolution | false                                            |
| disable_package_automatic_updates    | false                                            |
| xcodebuild_formatter                 | xcpretty                                         |
| use_system_scm                       | false                                            |
| xcode_path                           | /Applications/Xcode-16.0.0-Beta.3.app            |
+--------------------------------------+--------------------------------------------------+

WARN [2024-07-19 07:06:38.62]: Clearing previously generated screenshots
INFO [2024-07-19 07:06:38.62]: Building and running project - this might take some time...
DEBUG [2024-07-19 07:06:38.63]: Fetching available simulator devices

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `os_version' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60os_version%27%20for%20nil+repo:fastlane/fastlane
➡️  Add explicit error for destination without simulator
    https://github.com/fastlane/fastlane/pull/21911 [open] 0 💬
    07 Mar 2024

➡️  Snapshot ignoring devices parameter
    https://github.com/fastlane/fastlane/issues/21752 [open] 1 💬
    9 hours ago

➡️  snapshot doesn't seem to work for macOS apps
    https://github.com/fastlane/fastlane/issues/18709 [closed] 16 💬
    10 Nov 2023

and 5 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60os_version%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/device_manager.rb:135:in `latest_simulator_version_for_device': [!] undefined method `os_version' for nil (NoMethodError)

                  .os_version
                  ^^^^^^^^^^^
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `block (3 levels) in take_screenshots_simultaneously'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `each'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `group_by'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `block (2 levels) in take_screenshots_simultaneously'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each_with_index'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `block in take_screenshots_simultaneously'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `each'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `take_screenshots_simultaneously'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/runner.rb:45:in `work'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/commands_generator.rb:42:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/commands_generator.rb:106:in `run'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/commands_generator.rb:16:in `start'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/device_manager.rb:135:in `latest_simulator_version_for_device': undefined method `os_version' for nil (NoMethodError)

                  .os_version
                  ^^^^^^^^^^^
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `block (3 levels) in take_screenshots_simultaneously'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `each'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `group_by'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `block (2 levels) in take_screenshots_simultaneously'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each_with_index'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `block in take_screenshots_simultaneously'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `each'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `take_screenshots_simultaneously'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/runner.rb:45:in `work'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/commands_generator.rb:42:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/commands_generator.rb:106:in `run'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/snapshot/lib/snapshot/commands_generator.rb:16:in `start'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/gems/fastlane-2.221.1/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.221.1/libexec/bin/fastlane:25:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 14.5                                                       |
| Ruby                        | 3.3.4                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.39.5 (Apple Git-153)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.221.1/libexec/bin/fastlane |
| Host                        | macOS 14.5 (23F79)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.4/lib                        |
| OpenSSL Version             | OpenSSL 3.3.1 4 Jun 2024                                   |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode-16.0.0-Beta.3.app/Contents/Developer/  |
| Xcode Version               | 16.0                                                       |
| Swift Version               | 6.0                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.221.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.6.0        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.0        |
| artifactory                     | 3.0.17       |
| babosa                          | 1.0.4        |
| bundler                         | 2.5.14       |
| rexml                           | 3.2.9        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.6        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.8.2        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.2.1       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| naturally                       | 2.2.1        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.24.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.0        |
| public_suffix                   | 6.0.0        |
| addressable                     | 2.8.7        |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-partitions                  | 1.957.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.201.2      |
| aws-sdk-kms                     | 1.88.0       |
| aws-sdk-s3                      | 1.156.0      |
| strscan                         | 3.1.0        |
| nkf                             | 0.2.0        |
| base64                          | 0.2.0        |
| excon                           | 0.111.0      |
| ruby2_keywords                  | 0.0.5        |
| json                            | 2.7.2        |
| mini_magick                     | 4.13.2       |
| optparse                        | 0.5.0        |
| forwardable                     | 1.3.3        |
| logger                          | 1.6.0        |
| pathname                        | 0.3.0        |
| shellwords                      | 0.2.0        |
| cgi                             | 0.4.1        |
| date                            | 3.3.4        |
| timeout                         | 0.4.1        |
| stringio                        | 3.1.1        |
| securerandom                    | 0.3.1        |
| uri                             | 0.13.0       |
| ipaddr                          | 1.2.6        |
| openssl                         | 3.2.0        |
| digest                          | 3.1.1        |
| io-nonblock                     | 0.3.0        |
| zlib                            | 3.1.1        |
| resolv                          | 0.3.0        |
| io-wait                         | 0.3.1        |
| time                            | 0.3.0        |
| open-uri                        | 0.4.1        |
| mutex_m                         | 0.2.0        |
| net-http                        | 0.4.1        |
| net-protocol                    | 0.2.2        |
| english                         | 0.8.0        |
| erb                             | 4.0.3        |
| abbrev                          | 0.1.2        |
| io-console                      | 0.7.1        |
| tempfile                        | 0.2.1        |
| delegate                        | 0.3.1        |
| fileutils                       | 1.7.2        |
| tmpdir                          | 0.2.0        |
| singleton                       | 0.2.0        |
| open3                           | 0.2.1        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.5.0        |
| find                            | 0.2.0        |
| ostruct                         | 0.6.0        |
| yaml                            | 0.3.0        |
| psych                           | 5.1.2        |
| bigdecimal                      | 3.1.5        |
</details>

*generated on:* **2024-07-19**
</details>
 </pre>
</details>

**Comment by Jon-Schneider** [comment]
I'm experiencing the same thing. Has anyone found a workaround?

**Comment by Jon-Schneider** [comment]
I found a workaround in my case, thanks to #21911. I'm setting up Fastlane and Snapshots on a Catalyst app, and either by default or on accident Mac got added to the Supported Destinations in my (newly added) Snapshots UI Test framework. Removing it (so only iOS targets remained) fixed it for me.

**Comment by Hesesses** [comment]
having the same problem, or more like devices array is always ignored

**Comment by jeffreyjackson** [comment]
Please fix this!  Thank you! 👍🏻
