### ISSUE TITLE
No such file or directory when trying to create cert.

### ISSUE THREAD

**Issue by assembleMHN** [fastlane/fastlane#22164]
Hi all, hope somebody can help me, as i have alot of certificates to create.

**### Issue Description**
Im running fast lane to create certificates for multiple developer accounts, this has worked great for years, but this morning it stopped working (at least this is when i found out it stopped working). Im getting a "No such file or directory @ rb_sysopen - /Users/XXXXXXXXXX/Certificates/development/XXXXXX A/S.cer" error and cannot move forward. I have of cause checked that the directory is correct, which it is. the file does  not exists as this is what fastlane needs to create but the file structure is correct, i did also try to create a dummy file in the path with that file name but it did not make a difference.

**##### Command executed**
    cert(
     development: true,
     username: ENV["APPLE_ID"],
     team_id: ENV["APPLE_DEV_TEAM_ID"],
     team_name: ENV["CONNECT_TEAM_NAME"],
     output_path: "~/Certificates/development/",
     filename: ENV["CONNECT_TEAM_NAME"]
    )

**##### Complete output when running fastlane, including the stack trace and command used**
08:07:33]: Running lane `ios make_certificates_all`. Next time you can do this by directly typing `bundle exec fastlane ios make_certificates_all` 🚀.
[08:07:33]: Driving the lane 'ios make_certificates_all' 🚀
[08:07:33]: --------------------------------
[08:07:33]: --- These ENV Files are run: ---
[08:07:33]: --------------------------------
[08:07:33]: ▸ xxxxxxxx
[08:07:33]: ----------------------------------------------------------
[08:07:33]: --- Step: Switch to ios set_environment_variables lane ---
[08:07:33]: ----------------------------------------------------------
[08:07:33]: Cruising over to lane 'ios set_environment_variables' 🚖
[08:07:33]: Cruising back to lane 'ios make_certificates_all' 🚘
[08:07:33]: ----------------------------------------------------------
[08:07:33]: --- Step: Switch to ios set_environment_variables lane ---
[08:07:33]: ----------------------------------------------------------
[08:07:33]: Cruising over to lane 'ios set_environment_variables' 🚖
[08:07:33]: Cruising back to lane 'ios make_certificates_all' 🚘
[08:07:33]: -------------------------------------------------
[08:07:33]: --- Step: Switch to ios make_certificate lane ---
[08:07:33]: -------------------------------------------------
[08:07:33]: Cruising over to lane 'ios make_certificate' 🚖
[08:07:33]: ------------------
[08:07:33]: --- Step: cert ---
[08:07:33]: ------------------

+---------------------------------------------------------------------------------------------+
|                                  Summary for cert 2.222.0                                   |
+-------------------------+-------------------------------------------------------------------+
| development             | true                                                              |
| username                |xxxxxxxxxxxxxxxxxxxxxxxx                                           |
| team_id                 | xxxxxxxxxxxxx                                                     |
| team_name               | xxxxxxxxxxxxx                                                     |
| filename                | xxxxxxxxxxxxx                                                     |
| force                   | false                                                             |
| generate_apple_certs    | true                                                              |
| keychain_path           | /Users/xxxxxxxxxxxxxxxxxxxxxx/Library/Keychains/login.keychain-db |
| skip_set_partition_list | false                                                             |
| platform                | ios                                                               |
+-------------------------+-------------------------------------------------------------------+

[08:07:33]: Starting login with user 'apple@xxxxxxxx.world'
[08:07:34]: Successfully logged in
[08:07:35]: --------------------------
[08:07:35]: --- Step: notification ---
[08:07:35]: --------------------------
+----------------------------------------------+
|                 Lane Context                 |
+------------------+---------------------------+
| DEFAULT_PLATFORM | ios                       |
| PLATFORM_NAME    | ios                       |
| LANE_NAME        | ios make_certificates_all |
+------------------+---------------------------+
[08:07:35]: Called from Fastfile at line 620
[08:07:35]: ```
[08:07:35]:     618:	
[08:07:35]:     619:	  private_lane :make_certificate do
[08:07:35]:  => 620:	    cert(
[08:07:35]:     621:	     development: true,
[08:07:35]:     622:	     username: ENV["APPLE_ID"],
[08:07:35]: ```
[08:07:35]: No such file or directory @ rb_sysopen - /Users/xxxxxxxxxxxxxxxxxxxxxx/Certificates/development/xxxxxxxx A/S.cer

+-------------------------------------------------------------------+
|                         fastlane summary                          |
+------+----------------------------------------------+-------------+
| Step | Action                                       | Time (in s) |
+------+----------------------------------------------+-------------+
| 1    | Verifying fastlane version                   | 0           |
| 2    | default_platform                             | 0           |
| 3    | Switch to ios set_environment_variables lane | 0           |
| 4    | Switch to ios set_environment_variables lane | 0           |
| 5    | Switch to ios make_certificate lane          | 0           |
| 💥   | cert                                         | 2           |
| 7    | notification                                 | 0           |
+------+----------------------------------------------+-------------+

[08:07:35]: fastlane finished with errors

[08:07:35]: Error accessing file, this might be due to fastlane's directory handling
[08:07:35]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

bundler: failed to load command: fastlane (/Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/fastlane)
/Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/cert/lib/cert/runner.rb:246:in `write': No such file or directory @ rb_sysopen - /Users/xxxxxxxxxxxxxxxxxxxxxx/Certificates/development/XXXXXX A/S.cer (Errno::ENOENT)
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/cert/lib/cert/runner.rb:246:in `store_certificate'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/cert/lib/cert/runner.rb:100:in `block in find_existing_cert'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/cert/lib/cert/runner.rb:95:in `each'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/cert/lib/cert/runner.rb:95:in `find_existing_cert'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/cert/lib/cert/runner.rb:48:in `run'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/cert/lib/cert/runner.rb:13:in `launch'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/get_certificates.rb:22:in `run'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:620:in `block (2 levels) in parsing_binding'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:615:in `block (3 levels) in parsing_binding'
	from Fastfile:612:in `each'
	from Fastfile:612:in `block (2 levels) in parsing_binding'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/fastlane:25:in `load'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/fastlane:25:in `<top (required)>'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli.rb:483:in `exec'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/cli.rb:25:in `start'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
	from /Users/xxxxxxxxxxxxxxxxxxxxxx/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
MacBook-Pro:swift_nemDialog xxxxxxxxxxxxxxxxxxxxxx$ 

Im running fastlane version 2.222.0, thank you in advance, hope some of you can help me out :)

Best Regards
Morten

**Comment by assembleMHN** [comment]
Im still having this issue, it came out of nothing been using this code for years, hope somebody can help!
