### ISSUE TITLE
i am unable to publish app to AppStore

### ISSUE THREAD

**Issue by nkoppala-facilgo** [fastlane/fastlane#22183]
Fastlane file
```
default_platform(:ios, '12.0')

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    match(app_identifier: 'com.facilgomobile.pmc', type:'appstore', readonly: true)

    build_app(
      workspace: "FacilgoMobile.xcworkspace",
      scheme: "FacilgoMobile",
      # export_method: "app-store"
    )

    app_store_connect_api_key(
      key_id: "######",
      issuer_id: "#####",
      key_content: File.read("/Users/naveenkoppala/Documents/facilgo/facilgo-mobile-pmc/ios/fastlane/AuthKey_ZHL37AG4MB.p8"),
      duration: 200,
      in_house: true
    )

      # Upload to TestFlight using app-specific password
    pilot(skip_waiting_for_build_processing: true)
    
    clean_build_artifacts
  end
end

```

Getting below error
`[12:54:30]: ---------------------------------------
[12:54:30]: --- Step: app_store_connect_api_key ---
[12:54:30]: ---------------------------------------
+---------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                   Lane Context                                                                    |
+------------------------------------+--------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                                          |
| PLATFORM_NAME                      | ios                                                                                                          |
| LANE_NAME                          | ios beta                                                                                                     |
| SIGH_PROFILE_TYPE                  | app-store                                                                                                    |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.facilgomobile.pmc"=>"match AppStore com.facilgomobile.pmc"}                                            |
| IPA_OUTPUT_PATH                    | /Users/naveenkoppala/Documents/facilgo/facilgo-mobile-pmc/ios/FacilgoMobile.ipa                              |
| XCODEBUILD_ARCHIVE                 | /Users/naveenkoppala/Library/Developer/Xcode/Archives/2024-08-14/FacilgoMobile 2024-08-14 12.47.16.xcarchive |
| DSYM_OUTPUT_PATH                   | /Users/naveenkoppala/Documents/facilgo/facilgo-mobile-pmc/ios/FacilgoMobile.app.dSYM.zip                     |
+------------------------------------+--------------------------------------------------------------------------------------------------------------+
[12:54:30]: Called from Fastfile at line 29
[12:54:30]: ```
[12:54:30]:     27:         )
[12:54:30]:     28:
[12:54:30]:  => 29:         app_store_connect_api_key(
[12:54:30]:     30:           key_id: "####",
[12:54:30]:     31:           issuer_id: "####",
[12:54:30]: ```
[12:54:30]: invalid curve name

+------------------------------------------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | match                     | 4           |
| 3    | build_app                 | 436         |
| 💥   | app_store_connect_api_key | 0           |
+------+---------------------------+-------------+

[12:54:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️   invalid curve name after brew upgrade?
    https://github.com/fastlane/fastlane/issues/20553 [open] 13 💬
    19 Feb 2024

➡️  Trying to Deploy IOS App on Test-flight via Azure DevOps - I'm facing build error
    https://github.com/fastlane/fastlane/issues/21531 [open] 5 💬
    02 Jan 2024

➡️  Unable to upload to testflight using Xcode 14 beta
    https://github.com/fastlane/fastlane/issues/20371 [closed] 154 💬
    5 weeks ago

and 8 more at: https://github.com/fastlane/fastlane/search?q=invalid%20curve%20name&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/spaceship/lib/spaceship/connect_api/token.rb:70:in `initialize': [!] invalid curve name (OpenSSL::PKey::ECError)
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/spaceship/lib/spaceship/connect_api/token.rb:70:in `new'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/spaceship/lib/spaceship/connect_api/token.rb:70:in `create'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/app_store_connect_api_key.rb:43:in `run'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:29:in `block (2 levels) in parsing_binding'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/bin/fastlane:25:in `load'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/bin/fastlane:25:in `<main>'
(base) ➜  ios git:(develop) ✗ fastlane action app_store_connect_api_key  `

**Comment by darrin569** [comment]
The error you're encountering, invalid curve name, is related to the OpenSSL library used by Fastlane to process the JWT tokens. This issue can occur due to incompatibilities between the Fastlane version, the OpenSSL version, or other dependencies.

Here are some steps you can take to troubleshoot and resolve this issue:

Update Fastlane: Ensure you are using the latest version of Fastlane. You can update Fastlane using Homebrew with the following command:

bash
Copy code
brew update
brew upgrade fastlane
Update OpenSSL: Ensure you have the latest version of OpenSSL installed. You can update OpenSSL with Homebrew:

bash
Copy code
brew update
brew upgrade openssl
Reinstall Fastlane: Sometimes, reinstalling Fastlane can resolve issues related to dependencies:

bash
Copy code
gem uninstall fastlane
gem install fastlane
Check Fastlane Dependencies: Make sure all Fastlane dependencies are correctly installed. Sometimes, reinstalling Fastlane dependencies can help:

bash
Copy code
bundle install
Validate Your JWT Key: Ensure that the JWT key you are using is valid and correctly formatted. If possible, generate a new API key in the Apple Developer portal and update the key details in your Fastlane configuration.

Consult Fastlane GitHub Issues: Since this issue appears to be somewhat known, checking Fastlane's GitHub issues and discussions might offer some specific fixes or workarounds:

[Fastlane GitHub Issues](https://github.com/fastlane/fastlane/issues) [Your Texas Benefits](https://www.yourtexas-benefits.com)
Fallback to an Older Version: If updating doesn't help, you might try rolling back to an earlier version of Fastlane that was working correctly. Use the command:

bash
Copy code
gem install fastlane -v '2.x.x'
Local Environment: Ensure that your local development environment (e.g., Ruby, Node.js) is up to date and properly configured.

After performing these steps, try running your Fastlane script again to see if the issue is resolved. If the problem persists, providing additional logs or context might help in further troubleshooting.

**Comment by martipello** [comment]
AI replies on issues is crazy

**Comment by omaranwaar** [comment]
Try to use 
in_house: false

**Comment by iBotPeaches** [comment]
The root issue of this was ` invalid curve name` which is caused by additional space or malformed key. OpenSSL increased its validation. Sorry for delay - closing this out as duplicate of #20553
