### ISSUE TITLE
[__NSArrayM insertObject:atIndex:]: object cannot be nil (-1010)

### ISSUE THREAD

**Issue by williamdes** [fastlane/fastlane#22182]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When the `MARKETING_VERSION` in  `project.pbxproj` contains non numbers/`.` chars it fails.
Works: `1.2.3`
Fails: `1.2.3-dev`

As reported in:
- https://github.com/fastlane/fastlane/issues/21462#issuecomment-1679868812
- https://github.com/fastlane/fastlane/issues/21706#issuecomment-1886503304

Either there is a bug somewhere in the Apple process or Fastlane fails to handle the version.
I think it should be handled in a better way for users to know what to do

https://github.com/fastlane/fastlane/blob/e1ab951b63aeb7a669b415708ffbe0e1346c0f59/pilot/lib/pilot/build_manager.rb#L55

Maybe there is no need to display the stack trace for user_error ?

```
fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Error uploading ipa file:  (FastlaneCore::Interface::FastlaneError)
 [Application Loader Error Output]: Exception caught. *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil (-1010)
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
	from fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:55:in `upload'
	from fastlane-2.222.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:82:in `block (2 levels) in parsing_binding'
	from fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from commander-4.6.0/lib/commander/command.rb:187:in `call'
	from commander-4.6.0/lib/commander/command.rb:157:in `run'
	from commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.3.4/x64/bin/fastlane:25:in `load'
	from /Users/runner/hostedtoolcache/Ruby/3.3.4/x64/bin/fastlane:25:in `<top (required)>'
	from bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `load'
	from bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from bundler-2.5.11/lib/bundler/cli/exec.rb:23:in `run'
	from bundler-2.5.11/lib/bundler/cli.rb:455:in `exec'
	from bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from bundler-2.5.11/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from bundler-2.5.11/lib/bundler/cli.rb:35:in `dispatch'
	from bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from bundler-2.5.11/lib/bundler/cli.rb:29:in `start'
	from bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
	from bundler-2.5.11/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from bundler-2.5.11/exe/bundle:20:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.3.4/x64/bin/bundle:25:in `load'
	from /Users/runner/hostedtoolcache/Ruby/3.3.4/x64/bin/bundle:25:in `<main>'
```

Ruby: 3.3.4

##### Command executed

It seems this was the last thing it was running. it should correspond to  `testflight(itc_provider: "xxxxxx")`

```
xcrun altool --upload-app -u xx@xx.xx -p YourPassword --asc-provider xxxxxx -t ios -f /var/folders/86/97zwv_355k77pgb_cm2kjsxw0000gy/T/db796090-0be3-4f02-9634-cd436e237311.ipa -k 100000
```

**Comment by williamdes** [comment]
Probably ref:
- https://stackoverflow.com/questions/19726988/what-values-should-i-use-for-cfbundleversion-and-cfbundleshortversionstring
- https://forums.developer.apple.com/forums/thread/729645

Lets see what you think about improving the message and version handling dear Fastlane devs

**Comment by amerllica** [comment]
This issue isn't about Fastlane only, it happens with any tool even by using Xcode GUI/CLI tools. It's very peculiar that iOS app versioning isn't `SemVer`!!! Its pattern is `x.y.z` and the x, y and z must be numbers.

The SemVer pattern contains a tag version, a hyphen and some other information like the distance number to the tag version or part of the commit hash etc which were not supported by Apple!!

The solution is only one thing, use the `x.y.z` pattern for `CFBundleShortVersionString` or `bundle-short-version-string`

**Comment by williamdes** [comment]
Closing this, contributors: feel free to add detection and fix this. Post an update here

**Comment by zerosum-0** [comment]
check plist also ...
blank ...
	<string>$(CURRENT_PROJECT_VERSION) </string>
