### ISSUE TITLE
Method missing

### ISSUE THREAD

**Issue by passmanagerapp** [fastlane/fastlane#22192]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Starting from last week, I have an error when I run pipeline for my Android app. The command line indicates the line of 46 at Fastfile is: 
          gradle(
            task: "assemble",
            flavor: "Tst",
            build_type: "Release",
            flags: "--stacktrace"
          )

##### Command executed
from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'

##### Complete output when running fastlane, including the stack trace and command used
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /usr/local/Cellar/ruby@3.0/3.0.7/lib/ruby/3.0.0/forwardable.rb:238:in `sh'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:46:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'

**Comment by WarrenBuffering** [comment]
I'm also getting this `method missing` error but it's coming from failed upload request to play store. Are you sure it's happening for you during build?

**Comment by intonarumori** [comment]
I have the same but for Apple App Store, 5 minutes before it was working fine, as far as I remember I didn't change anything.
