### ISSUE TITLE
[!] Permission denied - /.../gradlew (Errno::EACCES)

### ISSUE THREAD

**Issue by THEAccess** [fastlane/fastlane#22200]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I try to run a lane to build an android app I get `[!] Permission denied - /Users/username/Documents/AndroidStudioProjects/prj/gradlew (Errno::EACCES)
`

##### Command executed
```
bundle exec fastlane playstore
```

##### Complete output when running fastlane, including the stack trace and command used
```
bundle exec fastlane playstore
[✔] 🚀 
[10:49:15]: ------------------------------
[10:49:15]: --- Step: default_platform ---
[10:49:15]: ------------------------------
[10:49:15]: Driving the lane 'android playstore' 🚀
[10:49:15]: -----------------------------
[10:49:15]: --- Step: assembleRelease ---
[10:49:15]: -----------------------------
[10:49:15]: $ /Users/username/Documents/AndroidStudioProjects/prj/gradlew assembleRelease -p .
+---------------------------------------+
|             Lane Context              |
+-------------------+-------------------+
| DEFAULT_PLATFORM  | android           |
| PLATFORM_NAME     | android           |
| LANE_NAME         | android playstore |
| GRADLE_BUILD_TYPE | Release           |
+-------------------+-------------------+
[10:49:15]: Called from Fastfile at line 35
[10:49:15]: ```
[10:49:15]:     33:       desc "Deploy a new version to the Google Play"
[10:49:15]:     34:       lane :playstore do
[10:49:15]:  => 35:         gradle(
[10:49:15]:     36:           task: 'assemble',
[10:49:15]:     37:           build_type: 'Release'
[10:49:15]: ```
[10:49:15]: Permission denied - /Users/username/Documents/AndroidStudioProjects/prj/gradlew

+---------------------------------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | assembleRelease  | 0           |
+------+------------------+-------------+

[10:49:15]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/open3.rb:534:in `spawn': [!] Permission denied - /Users/username/Documents/AndroidStudioProjects/prj/gradlew (Errno::EACCES)
        from /opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/open3.rb:534:in `popen_run'
        from /opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/open3.rb:522:in `popen2e'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
        from /opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/forwardable.rb:240:in `sh'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:35:in `block (2 levels) in parsing_binding'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/bin/fastlane:25:in `load'
        from /opt/homebrew/Cellar/fastlane/2.222.0/libexec/bin/fastlane:25:in `<main>'

```

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 14.2                                                       |
| Ruby                        | 3.3.4                                                      |
| Bundler?                    | true                                                       |
| Git                         | git version 2.32.0                                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.222.0/libexec/bin/fastlane |
| Host                        | macOS 14.2 (23C64)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.4/lib                        |
| OpenSSL Version             | OpenSSL 3.3.1 4 Jun 2024                                   |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 15.1                                                       |
| Swift Version               | 5.9.2                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :playstore do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(
      rollout: '0.1',
      track: "production",
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.222.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.6.0        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.0        |
| pathname                        | 0.3.0        |
| rake                            | 13.2.1       |
| base64                          | 0.2.0        |
| nkf                             | 0.1.3        |
| strscan                         | 3.0.9        |
| rexml                           | 3.2.9        |
| CFPropertyList                  | 3.0.7        |
| public_suffix                   | 6.0.1        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.3.0        |
| aws-partitions                  | 1.958.0      |
| aws-sigv4                       | 1.9.0        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.201.3      |
| aws-sdk-kms                     | 1.88.0       |
| aws-sdk-s3                      | 1.156.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.4.22       |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.5        |
| domain_name                     | 0.6.20240107 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.111.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.6        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.8.2        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.5        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.0        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.7.1        |
| mini_magick                     | 4.13.2       |
| naturally                       | 2.2.1        |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.24.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2024-08-24**
</details>

**Comment by jrlawhorne** [comment]
I had this same problem in an older Cordova project when I set the `gradle_path` variable in my call to the directory that the `gradlew` file was in instead of the gradlew file itself.

This works for me:

```
    gradle(
      project_dir: "platforms/android",
      gradle_path: "tools/gradlew",
      task: "assemble",
      build_type: "Release"
    )
```

**Comment by iBotPeaches** [comment]
Indeed. As mentioned above its either not there or not executable. The logs spit out the location we looked to help debug it.

```
[10:49:15]: Permission denied - /Users/username/Documents/AndroidStudioProjects/prj/gradlew
```

Sorry it took years for this. Closing it out as support.
