### ISSUE TITLE
Xcode 16 - upload_to_testflight failed

### ISSUE THREAD

**Issue by salvatoreboemia** [fastlane/fastlane#22239]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
upload to test flight failed

### Error
```
[11:38:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Publish to Test Flight Error
    https://github.com/fastlane/fastlane/issues/18062 [closed] 5 💬
    24 Apr 2021

➡️  Pilot - undefined method `strip' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15204 [closed] 12 💬
    26 Nov 2019

➡️  some wrong happen when I use fastlane to upload an ipa file
    https://github.com/fastlane/fastlane/issues/14272 [closed] 6 💬
    11 Jun 2019

and 2 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60start_with%3F%27%20for%20nil&type=Issues&utf8=✓
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:685:in `initialize': \e[31m[!] undefined method `start_with?' for nil:NilClass\e[0m (NoMethodError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:412:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:412:in `transporter_for_selected_team'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:49:in `upload'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:276:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:685:in `initialize': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:412:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:412:in `transporter_for_selected_team'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:49:in `upload'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:276:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>
```

### My lane
```
lane :uploadTF do |options|
    upload_to_testflight(
      api_key_path: "myJson",
      ipa: "./DerivedData/Build/MyApp",
      changelog: options[:changelog],
      groups: [options[:team]],
      distribute_external: true,
      skip_waiting_for_build_processing: false
    )
  end
```

Only on a specific branch of Xcode 16, where I use in the GitHub Action `Xcode_16.app.`

And I notice that in the log it talks about pilot.

Archive works, only the upload fails

What's wrong?

Thanks

**Comment by p-sebastian** [comment]
Having the same issue on mac running XCode 16

**Comment by salvatoreboemia** [comment]
> Having the same issue on mac running XCode 16

For me, the local upload using Xcode 16.0 works fine.

**Comment by p-sebastian** [comment]
checking a bit more, it is the build that is incorrect, if building with fastlane, it will complete but the bundle appears to be wrong, taking that build and trying to upload with xcode will throw the same error of `Asset Validation Failed`

**Comment by p-sebastian** [comment]
Not related to fastlane at all but xcode 16 and stricter rules when uploading, pods shouldn't contain bitcode -> https://github.com/mapbox/mapbox-maps-ios/issues/2233#issuecomment-2363627443

**Comment by salvatoreboemia** [comment]
UPDATE

I tried locally with Fastlane and works fine. Probably is something related to GitHub runner. I really don't know

**Comment by salvatoreboemia** [comment]
the issue was caused by command line tool selected by GitHub automatically, they always select 15.4 instead new Xcode. I forced to use Xcode 16
