### ISSUE TITLE
Doesn't support the new Xcode 16 folder format (unknown ISA `PBXFileSystemSynchronizedRootGroup`)

### ISSUE THREAD

**Issue by sborovikov-belkacar** [fastlane/fastlane#22265]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
<p>
Xcode 16 introduces an interesting feature to convert groups in a project into regular folders.
</p>

https://developer.apple.com/documentation/xcode/managing-files-and-folders-in-your-xcode-project

<p>
This should significantly reduce the size of the Xcode project file. And most importantly, we will be able to say goodbye to conflicts in the project file forever and forget about the problem of lost files 
</p>
<p>
As I can see Fastlane doesn't supported it
</p>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> bundler: failed to load command: fastlane (/opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane)
/opt/homebrew/lib/ruby/gems/3.0.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid': \e[31m[!] `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["ECD642032CA44CD6006063AE"], "explicitFileTypes"=>{}, "explicitFolders"=>[], "path"=>"BelkaCar", "sourceTree"=>"<group>"}` (RuntimeError) </pre>
</details>

### Environment

<details>
  <pre> 
  
Xcode 16
  
bundler 2.5.20
faraday_middleware 1.2.1
faraday_middleware 1.2.1
fastlane-plugin-sentry 1.25.1
fastlane 2.223.1
xcode-install 2.8.1</pre>
</details>

**Comment by Jaythaking** [comment]
We have the same issue after updating to XCode 16 too

**Comment by sborovikov-belkacar** [comment]
https://github.com/CocoaPods/Xcodeproj/pull/975
I’ve checked this fix locally on my Mac within Fastlane in a project with the new Xcode folders format. It's working!

**Comment by froggomad** [comment]
I've been using Xcode 16 since release and just started running into issues today after adding test plans to a project

**Comment by nicolasvergoz** [comment]
This one seems more complete. It covers the `PBXFileSystemSynchronizedRootGroup`'s attributes as well
https://github.com/CocoaPods/Xcodeproj/pull/985/files

**Comment by luinily** [comment]
https://github.com/CocoaPods/Xcodeproj/pull/985 has been merged

**Comment by fabioferrero** [comment]
So guys since now Cocoapods/Xcodeproj released the [1.26.0](https://github.com/CocoaPods/Xcodeproj/releases/tag/1.26.0) version with the fix, are you releasing a new fastlane version?
For the moment I just forced Bundler to use at least the desired version of xcodeproj: in my Gemfile I added 
`gem 'xcodeproj', '>= 1.26.0'` 
and it solves the issue.

**Comment by nicolasvergoz** [comment]
I didn't have to update nor force `xcodeproj` version to have the `1.26.0` version. I don't know why.

Here is a part of the Gemfile I use :

```ruby
source 'https://rubygems.org'

gem "fastlane"
gem "slather"
```

And part of the Gemfile.lock :

```ruby
GEM
  remote: https://rubygems.org/
  specs:
    fastlane (2.225.0)
      xcodeproj (>= 1.13.0, < 2.0.0)
    slather (2.8.4)
      xcodeproj (~> 1.25)
    xcodeproj (1.26.0)
```

**Comment by fabioferrero** [comment]
Thanks @nicolasvergoz, I'll check if it is sufficient to update fastlane.

**Comment by KhazanGu** [comment]
Still unresolved in the fastlane 2.225.0

**Comment by viniciussoares** [comment]
Same here, converting the src from groups to folders breaks `get_version_number`

```
[14:58:56]: --------------------------------
[14:58:56]: --- Step: get_version_number ---
[14:58:56]: --------------------------------

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/UserName/.gem/ruby/3.3.0/bin/fastlane)
/Users/UserName/.gem/ruby/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid': [!] `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["241D16612CE681090092CB72", "241D16622CE681090092CB72", "241D16632CE681090092CB72", "241D16642CE681090092CB72"], "explicitFileTypes"=>{}, "explicitFolders"=>["Resources/Games/AR/0d76bc37-fd59-4ed7-83e1-3fa541d23fb5", "Resources/Games/AR/91798746-0f2d-4474-968b-9401ccabd27f", "Resources/Games/AR/d427f081-19e6-49fd-ab4c-4d18ab22d703", "Resources/Games/AR/e696ef4c-c0ab-4ffd-85c2-4b498b88ee84", "Resources/Games/AR/f3c4f714-78a2-4391-8505-aa07c31fc0b6", "Resources/SwiftGen Templates"], "path"=>"ProjectName", "sourceTree"=>"<group>"}` (RuntimeError)
```

**Comment by lordgift** [comment]
I think this issue cause by `xcodeproj-1.25.0`. So I try to upgrade it.

And yes, it's worked. First, I have to install `ruby 3.3.6` then `bundle install` to resolve bundle dependency and I got `xcodeproj-1.27.0`. But, this still not work fine, another issue is waiting 🥶 [XCode 16 fastlane does not build ipa](https://github.com/fastlane/fastlane/issues/22276).

**Comment by nippach** [comment]
@lordgift updating xcodeproj fixed the issue, thanks!

**Comment by radianttap** [comment]
Is there a way to force-update xcodeproj that fastlane uses inside GitHub runner image? 

Folders are one of the most useful improvements in Xcode project history and I can't understand why updated xcodeproj is not included in last releases.

**Comment by appfrilans** [comment]
Any news here?

**Comment by iBotPeaches** [comment]
I believe this issue boils down to updating our minimum version of `xcodeproj` to force end users to download that version. Fearful though moving our minimum up because I know in the React Native ecosystem some newer version of `xcodeproj` had some issues, so might need some folks who have updated chime in with their pipeline (flutter, native, rn, etc) and the version of `xcodeproj` they updated to.

```
spec.add_dependency('xcodeproj', '>= 1.13.0', '< 2.0.0') # Modify Xcode projects
```

Thankfully it seems the modern version of `xcodeproj` still support our minimum Ruby version.

**Comment by iBotPeaches** [comment]
This was released in 2.231.0 - fixed in: https://github.com/fastlane/fastlane/pull/29836
