### ISSUE TITLE
fastlane snapshot can't find simulator

### ISSUE THREAD

**Issue by fishcharlie** [fastlane/fastlane#22284]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

fastlane snapshot can't find simulator. This looks similar to #22233 but for snapshot not scan.

##### Command executed

fastlane snapshot

##### Complete output when running fastlane, including the stack trace and command used

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:18.0, name:iPhone 16 }
[13:47:34]: Exit status: 70
[13:47:34]: Tests failed while running on: iPhone 16

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 15.1                                                       |
| Ruby                        | 3.3.5                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.39.5 (Apple Git-154)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.224.0/libexec/bin/fastlane |
| Host                        | macOS 15.1 (24B5055e)                                      |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.5/lib                        |
| OpenSSL Version             | OpenSSL 3.3.1 4 Jun 2024                                   |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode_16.0.app/Contents/Developer/           |
| Xcode Version               | 16.0                                                       |
| Swift Version               | 6.0                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.224.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.6.0        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.0        |
| public_suffix                   | 6.0.1        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.984.0      |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.10.0       |
| aws-sdk-core                    | 3.209.1      |
| aws-sdk-kms                     | 1.94.0       |
| aws-sdk-s3                      | 1.167.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.5.18       |
| rexml                           | 3.3.8        |
| nkf                             | 0.1.3        |
| base64                          | 0.2.0        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.112.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.4       |
| faraday_middleware              | 1.2.1        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.7        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.9.3        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.1        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.2.1       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.7.1        |
| mini_magick                     | 4.13.2       |
| naturally                       | 2.2.1        |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.6.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.25.1       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.0        |
| forwardable                     | 1.3.3        |
| logger                          | 1.6.0        |
| pathname                        | 0.3.0        |
| shellwords                      | 0.2.0        |
| cgi                             | 0.4.1        |
| date                            | 3.3.4        |
| timeout                         | 0.4.1        |
| stringio                        | 3.1.1        |
| securerandom                    | 0.3.1        |
| uri                             | 0.13.1       |
| ipaddr                          | 1.2.6        |
| openssl                         | 3.2.0        |
| digest                          | 3.1.1        |
| io-nonblock                     | 0.3.0        |
| zlib                            | 3.1.1        |
| resolv                          | 0.3.0        |
| io-wait                         | 0.3.1        |
| time                            | 0.3.0        |
| open-uri                        | 0.4.1        |
| mutex_m                         | 0.2.0        |
| net-http                        | 0.4.1        |
| net-protocol                    | 0.2.2        |
| ostruct                         | 0.6.0        |
| english                         | 0.8.0        |
| erb                             | 4.0.3        |
| strscan                         | 3.0.9        |
| abbrev                          | 0.1.2        |
| io-console                      | 0.7.1        |
| tempfile                        | 0.2.1        |
| delegate                        | 0.3.1        |
| fileutils                       | 1.7.2        |
| tmpdir                          | 0.2.0        |
| singleton                       | 0.2.0        |
| open3                           | 0.2.1        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.5.0        |
| find                            | 0.2.0        |
| yaml                            | 0.3.0        |
| psych                           | 5.1.2        |
</details>

*generated on:* **2024-10-05**
</details>

**Comment by sam-bt** [comment]
I am having the same issue:

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:18.2, name:iPhone 16 Pro }
[11:17:12]: Exit status: 70
[11:17:12]: Tests failed while running on: iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, iPhone 16 Plus, iPad Pro 11-inch (M4)
[11:17:12]: Caught error... 70

I am certain that i have these simulators installed as I can run my ui tests and main app on them successfully.

My fastlane however, is installed using bundler.

**Comment by kprovorov** [comment]
So I fixed it by adding executable to UITests schema
<img width="1392" alt="Screenshot 2024-12-28 at 23 21 38" src="https://github.com/user-attachments/assets/d565e4d3-5d61-459d-a358-bcdd77ea8193" />

**Comment by sbeitzel** [comment]
I'm sad, since this *isn't* solving the problem for me.

My configuration:
 - Xcode Version 16.3 beta 2 (16E5121h)
 - `xcode-select` referencing the proper location: `/Applications/Xcode-beta.app/Contents/Developer`
 - fastlane version 2.226.0
 - ruby version 3.3.5

The UI test scheme does have an associated run target (and the tests will run manually from within Xcode, so I know that works all okay).

And yet, when I run the snapshots target in my project, I get this error:
`fastlane-2.226.0/fastlane_core/lib/fastlane_core/device_manager.rb:135:in `latest_simulator_version_for_device': [!] undefined method `os_version' for nil (NoMethodError)

                  .os_version
                  ^^^^^^^^^^^
	from /Users/sbeitzel/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.226.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:62:in `block (3 levels) in take_screenshots_simultaneously'
`
That said, there's an interesting difference between the configuration coming in from the Snapfile and the configuration that the snapshot plugin outputs at the beginning of its run:

`+------------------------------------------------------+
|      Detected Values from './fastlane/Snapfile'      |
+----------------------------+-------------------------+
| devices                    | ["iPhone 16 (18.4)"]    |
| languages                  | ["en-US"]               |
| scheme                     | RelativitiUIScreenshots |
| output_directory           | ./screenshots           |
| clear_previous_screenshots | true                    |
| override_status_bar        | true                    |
+----------------------------+-------------------------+
`

`+------------------------------------------------------------------------------------------+
|                               Summary for snapshot 2.226.0                               |
+--------------------------------------+---------------------------------------------------+
| scheme                               | RelativitiUIScreenshots                           |
| xcodebuild_formatter                 | xcbeautify                                        |
| project                              | ./Relativiti.xcodeproj                            |
| devices                              | ["Mac"]                                           |
| languages                            | ["en-US"]                                         |
`

Note that the `devices` entry is different. What's up with that?

**Comment by juanarzola** [comment]
> +------------------------------------------------------------------------------------------+
> |                               Summary for snapshot 2.226.0                               |
> +--------------------------------------+---------------------------------------------------+
> | scheme                               | RelativitiUIScreenshots                           |
> | xcodebuild_formatter                 | xcbeautify                                        |
> | project                              | ./Relativiti.xcodeproj                            |
> | devices                              | ["Mac"]                                           |
> | languages                            | ["en-US"]                                         |
> ```
> 
> Note that the `devices` entry is different. What's up with that?

@sbeitzel thanks to this insight - I am also hitting this issue. Seems like detect_values.rb overrides the config setup in `Snapfile` with "Mac":

https://github.com/fastlane/fastlane/blob/67c75b70ef3bb1ecf2c2fd31673f5c0e3aa1e644/snapshot/lib/snapshot/detect_values.rb#L69

hacking a little, changing that condition to not replace the configuration makes it continue with the config I setup:

```ruby
elsif config[:devices].nil? && Snapshot.project.mac?
```

however, I haven't been able to move forward because what probably is a different issue: I am using a simulator on 18.3.1, but that version's runtime is named 18.3 still causing `xcrun simctl list devices` to list 18.3 instead, then causing fastlane to try to run tests on a non-existing 18.3 simulator:

```
Unable to find a device matching the provided destination specifier:
		{ platform:iOS Simulator, OS:18.3, name:iPhone 16 Pro }
```
 
That second issue might not hit you though, since you are trying to use 18.4.

**Comment by juanarzola** [comment]
Using an iOS simulator running 18.1:

Changing: [fastlane/snapshot/lib/snapshot/detect_values.rb](https://github.com/fastlane/fastlane/blob/67c75b70ef3bb1ecf2c2fd31673f5c0e3aa1e644/snapshot/lib/snapshot/detect_values.rb#L69)

to:

```
elsif config[:devices].nil? && Snapshot.project.mac?
```

fixed it for me. I am not familiar enough with this code path to make a PR for this, just leaving it here for reference.

**Comment by d-reic** [comment]
> So I fixed it by adding executable to UITests schema <img alt="Screenshot 2024-12-28 at 23 21 38" width="1392" src="https://private-user-images.githubusercontent.com/20870537/399127886-d565e4d3-5d61-459d-a358-bcdd77ea8193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE5NTU3ODAsIm5iZiI6MTc1MTk1NTQ4MCwicGF0aCI6Ii8yMDg3MDUzNy8zOTkxMjc4ODYtZDU2NWU0ZDMtNWQ2MS00NTlkLWEzNTgtYmNkZDc3ZWE4MTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA4VDA2MTgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3M2FiYzI4Y2FiY2ZlYzA4ZmFhMzBlZGUzZTI1N2E4ZDg0MDU3NDE4OWM0YzRiY2VhMjRkZjI3MGQ3NjIyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jepgCxRtplWBMyo75p90loxR05fUiXKxVbBP5FTa56Q">

This should be added to the set-up guide!

**Comment by brightsider** [comment]
@iBotPeaches I think my issue is related to the latest update of Xcode and iOS SDK to 26.4.1, looks like them forgot to update minor version somewhere and that's why it happens to me

**Comment by jpalo** [comment]
Yea, something's not right. It even says it would revert to 26.4 as it cannot find 26.4.1, but still it uses 26.4.

```
[17:36:31]: $ xcodebuild -resolvePackageDependencies -workspace Runner.xcworkspace -scheme stgeorge -configuration Debug-stgeorge
[17:36:32]: ▸ Command line invocation:
[17:36:32]: ▸     /Applications/Xcode-26.4.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace Runner.xcworkspace -scheme stgeorge -configuration Debug-stgeorge
[17:36:32]: ▸ resolved source packages: 
[17:36:32]: $ xcodebuild -showBuildSettings -workspace Runner.xcworkspace -scheme stgeorge -configuration Debug-stgeorge 2>&1
[17:36:33]: Patching simulators '/Users/builder/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
Set: Entry, ":DevicePreferences:EE04D37A-FDE4-4222-B514-02A368ED2FB2:ConnectHardwareKeyboard", Does Not Exist
Set: Entry, ":DevicePreferences:72AE35E6-619D-463F-AB09-B0A51FF6A08C:ConnectHardwareKeyboard", Does Not Exist
Set: Entry, ":DevicePreferences:4703F852-5C8D-4D29-8DFF-153FBE6E7231:ConnectHardwareKeyboard", Does Not Exist
Set: Entry, ":DevicePreferences:576EE794-CD9A-4900-AC8D-BAD4E46D7757:ConnectHardwareKeyboard", Does Not Exist
[17:36:34]: Erasing iPhone 17 Pro Max...
[17:36:35]: Using device named 'iPhone 17 Pro Max' with version '26.4' because no match was found for version '26.4.1'
[17:36:35]: Running snapshot on: iPhone 17 Pro Max
[17:36:35]: $ set -o pipefail && xcodebuild -workspace Runner.xcworkspace -scheme stgeorge -configuration Debug-stgeorge -derivedDataPath /var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/snapshot_derived20260427-8051-bg6dg4 -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max,OS=26.4' FASTLANE_SNAPSHOT=YES FASTLANE_LANGUAGE=en-US TEST_TARGET_NAME=Runner clean build test | tee /Users/builder/Library/Logs/snapshot/Runner-stgeorge.log | xcbeautify
[17:36:35]: ▸ Loading...
[17:36:35]: ▸ ----- xcbeautify -----
[17:36:35]: ▸ Version: 3.2.1
[17:36:35]: ▸ ----------------------
[17:37:36]: ▸ 2026-04-27 17:37:36.210 xcodebuild[8425:31110] Writing error result bundle to /var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/ResultBundle_2026-27-04_17-37-0036.xcresult
[17:37:36]: ▸ xcodebuild: error: Unable to find a device matching the provided destination specifier:
[17:37:36]: ▸ 		{ platform:iOS Simulator, OS:26.4, name:iPhone 17 Pro Max }
[17:37:36]: ▸ 	The requested device could not be found because no available devices matched the request.
[17:37:36]: ▸ 	Available destinations for the "stgeorge" scheme:
[17:37:36]: ▸ 		{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:0000FE00-343A79319AA17942, name:My Mac }
[17:37:36]: ▸ 		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[17:37:36]: ▸ 		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
[17:37:36]: ▸ 		{ platform:visionOS Simulator, arch:arm64, variant:Designed for [iPad,iPhone], id:BD263D24-0346-4DBC-86C8-3573BE1D8889, OS:26.4.1, name:Apple Vision Pro }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:51823430-5D05-4B92-ACC0-759B5C3C4745, OS:26.3.1, name:iPad (A16) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:F81956D3-1AA5-4041-938B-85D78A8A3A40, OS:26.4.1, name:iPad (A16) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:95787899-A205-4119-9AFD-D0C1B2264F5D, OS:26.4.1, name:iPad Air 11-inch (M3) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:A4702695-0388-4F7E-A87F-02752E7A4123, OS:26.3.1, name:iPad Air 11-inch (M4) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:0429FC11-7FA1-489B-93D9-48CBCEC0BCF5, OS:26.4.1, name:iPad Air 11-inch (M4) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:4F07F439-858C-40D8-B03C-082D6DA5076A, OS:26.4.1, name:iPad Air 13-inch (M3) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:2517B967-97B6-4853-B623-865AC79E6CD3, OS:26.3.1, name:iPad Air 13-inch (M4) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:5DCE095A-C5A7-44E2-9855-557B256354AC, OS:26.4.1, name:iPad Air 13-inch (M4) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:DECB3D65-CD5E-4E9B-968E-AA715E8FCF1B, OS:26.3.1, name:iPad Pro 11-inch (M5) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:05E88953-3FA0-4295-B10F-E02BA3D7BDC2, OS:26.4.1, name:iPad Pro 11-inch (M5) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:5D1271A1-9FD6-4AB6-9336-D4894AF3851B, OS:26.3.1, name:iPad Pro 13-inch (M5) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:7FE105CF-C7BD-4A21-8B21-205A4CDB33E6, OS:26.4.1, name:iPad Pro 13-inch (M5) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:6CA4D283-CFAA-4195-B3B7-7AA17396929A, OS:26.3.1, name:iPad mini (A17 Pro) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:2D5DC6D9-37F4-43B4-AC90-9CCDEDF2719F, OS:26.4.1, name:iPad mini (A17 Pro) }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:541ACB68-260D-4BB9-8F15-469AEC9CC542, OS:26.4.1, name:iPhone 16e }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:6194E215-D356-4F46-89E4-93D533FB4090, OS:26.3.1, name:iPhone 17 }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:1114811B-9965-4FCA-A185-B1000429EC83, OS:26.4.1, name:iPhone 17 }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:1AAD40F4-4D0E-43E1-A1D6-3F8BCDC1966D, OS:26.3.1, name:iPhone 17 Pro }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:A813414F-88E4-4093-A95F-21DA5E1D6CEF, OS:26.4.1, name:iPhone 17 Pro }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:E35BE189-F1D8-4B8C-9C7F-6C1A1B0CBCF7, OS:26.3.1, name:iPhone 17 Pro Max }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:92F133BB-0DAD-4507-B194-12B9D0436AD5, OS:26.4.1, name:iPhone 17 Pro Max }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:7BA3776C-BF29-461E-B6A7-A3548CF4DA56, OS:26.3.1, name:iPhone 17e }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:0CDE9B50-D77B-423D-A081-A00E15B2B6C6, OS:26.4.1, name:iPhone 17e }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:C3644462-31C5-49B0-B169-C621DF13792C, OS:26.3.1, name:iPhone Air }
[17:37:36]: ▸ 		{ platform:iOS Simulator, arch:arm64, id:B0701068-FD6E-4C68-AD5F-6BC5FFEE8876, OS:26.4.1, name:iPhone Air }
[17:37:36]: Exit status: 70
[17:37:36]: Tests failed while running on: iPhone 17 Pro Max
```

**Comment by tbosensea** [comment]
Is there a solution or workaround out there yet?

**Comment by JanST123** [comment]
For me the workaround was adding `ios_version("26.2")` to the Snapfile. This does not have a patch version. You need to have iOS 26.2 installed of course.
