### ISSUE TITLE
fetch_access_token': [!] Authorization failed.  Server message: (Signet::AuthorizationError)

### ISSUE THREAD

**Issue by usama-sherazi** [fastlane/fastlane#26593]
INFO [2024-10-21 13:51:26.56]: 🕗  Downloading metadata, images, screenshots...
DEBUG [2024-10-21 13:51:26.56]: Fetching a new access token from Google...

Looking for related GitHub issues on fastlane/fastlane...
Search query: Authorization failed.  Server message:
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}

/opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/signet-0.19.0/lib/signet/oauth_2/client.rb:1061:in `fetch_access_token': [!] Authorization failed.  Server message: (Signet::AuthorizationError)
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/signet-0.19.0/lib/signet/oauth_2/client.rb:1076:in `fetch_access_token!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/googleauth-1.8.1/lib/googleauth/signet.rb:46:in `block in fetch_access_token!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/googleauth-1.8.1/lib/googleauth/signet.rb:66:in `retry_with_error'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/googleauth-1.8.1/lib/googleauth/signet.rb:45:in `fetch_access_token!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/client.rb:53:in `initialize'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/client.rb:19:in `new'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/client.rb:19:in `make_from_config'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/setup.rb:119:in `client'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/setup.rb:11:in `perform_download'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/commands_generator.rb:55:in `block (2 levels) in run'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/commands_generator.rb:61:in `run'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/commands_generator.rb:13:in `start'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `load'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/signet-0.19.0/lib/signet/oauth_2/client.rb:1061:in `fetch_access_token': Authorization failed.  Server message: (Signet::AuthorizationError)
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/signet-0.19.0/lib/signet/oauth_2/client.rb:1076:in `fetch_access_token!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/googleauth-1.8.1/lib/googleauth/signet.rb:46:in `block in fetch_access_token!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/googleauth-1.8.1/lib/googleauth/signet.rb:66:in `retry_with_error'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/googleauth-1.8.1/lib/googleauth/signet.rb:45:in `fetch_access_token!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/client.rb:53:in `initialize'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/client.rb:19:in `new'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/client.rb:19:in `make_from_config'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/setup.rb:119:in `client'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/setup.rb:11:in `perform_download'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/commands_generator.rb:55:in `block (2 levels) in run'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/commands_generator.rb:61:in `run'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/supply/lib/supply/commands_generator.rb:13:in `start'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `load'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `<main>'
        
        
        <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 15.0.1                                                     |
| Ruby                        | 3.3.5                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.39.5 (Apple Git-154)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane |
| Host                        | macOS 15.0.1 (24A348)                                      |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.5/lib                        |
| OpenSSL Version             | OpenSSL 3.3.1 4 Jun 2024                                   |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 16.0                                                       |
| Swift Version               | 6.0                                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:android)

# upload to internal test to Google Play
lane :internal do
  # build the app bundle if you haven't already
  #gradle(task: 'bundleRelease')
  # Upload to internal test
  upload_to_play_store(
    track: 'internal',
    aab: '../build/app/outputs/bundle/release/app-release.aab', # Update this path if your AAB is generated in a different location
    skip_upload_apk: true,
    skip_upload_images: true,
    skip_upload_screenshots: true,
    skip_upload_metadata: true,
    skip_upload_changelogs: true,
    skip_upload_aab: false,
  )
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("fastlane_config.json") 
package_name("com.mypackage.app") 

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.225.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                   | Version | Update-Status |
| ---------------------------------------- | ------- | ------------- |
| fastlane-plugin-flutter_versioncode_bump | 1.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                      | Version      |
| ---------------------------------------- | ------------ |
| error_highlight                          | 0.6.0        |
| did_you_mean                             | 1.6.3        |
| syntax_suggest                           | 2.0.0        |
| public_suffix                            | 6.0.1        |
| addressable                              | 2.8.7        |
| artifactory                              | 3.0.17       |
| jmespath                                 | 1.6.2        |
| aws-partitions                           | 1.992.0      |
| aws-eventstream                          | 1.3.0        |
| aws-sigv4                                | 1.10.0       |
| aws-sdk-core                             | 3.210.0      |
| aws-sdk-kms                              | 1.95.0       |
| aws-sdk-s3                               | 1.169.0      |
| babosa                                   | 1.0.4        |
| bundler                                  | 2.5.18       |
| rexml                                    | 3.3.8        |
| nkf                                      | 0.1.3        |
| base64                                   | 0.2.0        |
| CFPropertyList                           | 3.0.7        |
| colored                                  | 1.2          |
| highline                                 | 2.0.3        |
| commander                                | 4.6.0        |
| dotenv                                   | 2.8.1        |
| emoji_regex                              | 3.2.3        |
| excon                                    | 0.112.0      |
| faraday-em_http                          | 1.0.0        |
| faraday-em_synchrony                     | 1.0.0        |
| faraday-excon                            | 1.1.0        |
| faraday-httpclient                       | 1.0.1        |
| multipart-post                           | 2.4.1        |
| faraday-multipart                        | 1.0.4        |
| faraday-net_http                         | 1.0.2        |
| faraday-net_http_persistent              | 1.2.0        |
| faraday-patron                           | 1.0.0        |
| faraday-rack                             | 1.0.0        |
| faraday-retry                            | 1.0.3        |
| ruby2_keywords                           | 0.0.5        |
| faraday                                  | 1.10.4       |
| faraday_middleware                       | 1.2.1        |
| domain_name                              | 0.6.20240107 |
| http-cookie                              | 1.0.7        |
| faraday-cookie_jar                       | 0.0.7        |
| fastimage                                | 2.3.1        |
| sysrandom                                | 1.0.5        |
| fastlane-sirp                            | 1.0.0        |
| gh_inspector                             | 1.1.3        |
| uber                                     | 0.1.0        |
| declarative                              | 0.0.20       |
| trailblazer-option                       | 0.1.2        |
| representable                            | 3.2.0        |
| retriable                                | 3.1.2        |
| mini_mime                                | 1.1.5        |
| jwt                                      | 2.9.3        |
| multi_json                               | 1.15.0       |
| os                                       | 1.1.4        |
| signet                                   | 0.19.0       |
| googleauth                               | 1.8.1        |
| httpclient                               | 2.8.3        |
| google-apis-core                         | 0.11.3       |
| google-apis-androidpublisher_v3          | 0.54.0       |
| google-apis-playcustomapp_v1             | 0.13.0       |
| google-cloud-env                         | 1.6.0        |
| google-cloud-errors                      | 1.4.0        |
| google-cloud-core                        | 1.7.1        |
| google-apis-iamcredentials_v1            | 0.17.0       |
| google-apis-storage_v1                   | 0.31.0       |
| rake                                     | 13.2.1       |
| digest-crc                               | 0.6.5        |
| google-cloud-storage                     | 1.47.0       |
| json                                     | 2.7.1        |
| mini_magick                              | 4.13.2       |
| naturally                                | 2.2.1        |
| optparse                                 | 0.4.0        |
| plist                                    | 3.7.1        |
| rubyzip                                  | 2.3.2        |
| security                                 | 0.1.5        |
| simctl                                   | 1.6.10       |
| terminal-notifier                        | 2.0.0        |
| unicode-display_width                    | 2.6.0        |
| terminal-table                           | 3.0.2        |
| tty-screen                               | 0.8.2        |
| tty-cursor                               | 0.7.1        |
| tty-spinner                              | 0.9.3        |
| word_wrap                                | 1.0.0        |
| atomos                                   | 0.1.3        |
| claide                                   | 1.1.0        |
| colored2                                 | 3.1.2        |
| nanaimo                                  | 0.3.0        |
| xcodeproj                                | 1.25.1       |
| rouge                                    | 2.0.7        |
| xcpretty                                 | 0.3.0        |
| xcpretty-travis-formatter                | 1.0.1        |
| set                                      | 1.1.0        |
| forwardable                              | 1.3.3        |
| logger                                   | 1.6.0        |
| pathname                                 | 0.3.0        |
| shellwords                               | 0.2.0        |
| cgi                                      | 0.4.1        |
| date                                     | 3.3.4        |
| timeout                                  | 0.4.1        |
| stringio                                 | 3.1.1        |
| securerandom                             | 0.3.1        |
| uri                                      | 0.13.1       |
| ipaddr                                   | 1.2.6        |
| openssl                                  | 3.2.0        |
| digest                                   | 3.1.1        |
| io-nonblock                              | 0.3.0        |
| zlib                                     | 3.1.1        |
| resolv                                   | 0.3.0        |
| io-wait                                  | 0.3.1        |
| time                                     | 0.3.0        |
| open-uri                                 | 0.4.1        |
| mutex_m                                  | 0.2.0        |
| net-http                                 | 0.4.1        |
| net-protocol                             | 0.2.2        |
| ostruct                                  | 0.6.0        |
| english                                  | 0.8.0        |
| erb                                      | 4.0.3        |
| strscan                                  | 3.0.9        |
| abbrev                                   | 0.1.2        |
| io-console                               | 0.7.1        |
| tempfile                                 | 0.2.1        |
| delegate                                 | 0.3.1        |
| fileutils                                | 1.7.2        |
| tmpdir                                   | 0.2.0        |
| singleton                                | 0.2.0        |
| open3                                    | 0.2.1        |
| prettyprint                              | 0.2.0        |
| pp                                       | 0.5.0        |
| find                                     | 0.2.0        |
| yaml                                     | 0.3.0        |
| psych                                    | 5.1.2        |
| fastlane-plugin-flutter_versioncode_bump | 1.0.1        |
</details>

*generated on:* **2024-10-21**
</details>

**Comment by jpriollaud** [comment]
Seeing the same issue without fastlane, its related to signet, jwt and system clock but despite hours of searching I could not identify what/when caused the breaking change.  all i found was this [post](https://qiita.com/kawashinji/items/e92929613a1bd9195b8b) without a corresponding issue on github.

**Comment by SaintPepsi** [comment]
Experiencing the same issue. I googled the issue and came across this: https://stackoverflow.com/questions/48056381/google-client-invalid-jwt-token-must-be-a-short-lived-token

could this be related to the time a token is generated on your machine and the token getting verified on the server?

Since I got starlink, many auth related things stopped working properly, websites stop working and it's all related to time. some websites will say "Error: token generated in the future" or stuff like that.

My assumption is  "in a reasonable timeframe." refers to the time not matching up to the google play server, i.e. if I generate my token at +10UTC, and then authenticate with the server, but that connection goes through +3UTC, it will error because the server assumes there's something dodgy going on with the token timing

@jpriollaud @usama-sherazi Are you on a VPN? what do you use for internet? could anything there be affecting this?
