### ISSUE TITLE
2.225.0 Circle CI MacOS executor with XCode 16 reline/ansi.rb:233:in `winsize': [!] Operation not supported on socket - <STDIN> (Errno::EOPNOTSUPP)

### ISSUE THREAD

**Issue by kpturner** [fastlane/fastlane#27260]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We are trying to run Fastlane version 2.225.0 on a Circle CI job but Fastlane fails to load.
We are using the following `orb`:  "circleci/macos@2.5.2"
and the following executor:
```
  macos:
    resource_class: macos.m1.large.gen1
    macos:
      xcode: '16.0.0'
```

**No problems like this seem to occur using XCode 15.1.0**

##### Command executed
Any fastlane command fails as the bundler cannot load it. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
bundler: failed to load command: fastlane (/Users/distiller/.rbenv/versions/3.3.4/bin/fastlane)
/Users/distiller/.rbenv/versions/3.3.4/lib/ruby/3.3.0/reline/ansi.rb:233:in `winsize': [!] Operation not supported on socket - <STDIN> (Errno::EOPNOTSUPP)
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/3.3.0/reline/ansi.rb:233:in `get_screen_size'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/3.3.0/reline.rb:218:in `get_screen_size'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/3.3.0/forwardable.rb:240:in `get_screen_size'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:359:in `size_from_readline'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:111:in `size'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:129:in `width'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:90:in `header'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/actions_helper.rb:68:in `execute_action'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:9:in `parsing_binding'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane_manager.rb:14:in `new'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane_manager.rb:14:in `cruise_lane'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.3.4/bin/fastlane:25:in `load'
	from /Users/distiller/.rbenv/versions/3.3.4/bin/fastlane:25:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.3.4/bin/bundle:25:in `load'
	from /Users/distiller/.rbenv/versions/3.3.4/bin/bundle:25:in `<main>'
/Users/distiller/.rbenv/versions/3.3.4/lib/ruby/3.3.0/reline/ansi.rb:233:in `winsize': Operation not supported on socket - <STDIN> (Errno::EOPNOTSUPP)
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/3.3.0/reline/ansi.rb:233:in `get_screen_size'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/3.3.0/reline.rb:218:in `get_screen_size'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/3.3.0/forwardable.rb:240:in `get_screen_size'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:359:in `size_from_readline'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:111:in `size'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:129:in `width'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:90:in `header'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/actions_helper.rb:68:in `execute_action'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:9:in `parsing_binding'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane_manager.rb:14:in `new'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane_manager.rb:14:in `cruise_lane'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.3.4/bin/fastlane:25:in `load'
	from /Users/distiller/.rbenv/versions/3.3.4/bin/fastlane:25:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/distiller/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.3.4/bin/bundle:25:in `load'
	from /Users/distiller/.rbenv/versions/3.3.4/bin/bundle:25:in `<main>'

Exited with code exit status 1

 </pre>
</details>

### Environment

It is not possible to run this command as the bundler cannot load fastlane

**Comment by patattack69** [comment]
Github Actions gave me the same error for macos-14-large runners.

**Comment by ruby05guy** [comment]
Hello,

You've run into an environment compatibility issue with Fastlane on CircleCI.
Ruby Version Compatibility: Fastlane has certain compatibility requirements with Ruby. Since you're using Ruby 3.3.0, which is a relatively new release, it might not be fully compatible with Fastlane yet. Try downgrading to Ruby 3.1 or 3.2 to see if that stabilizes Fastlane loading.

Check Bundler Setup: Although Bundler is reported as false, Fastlane often requires Bundler to manage dependencies. Ensure that Bundler is installed and loaded by adding: gem install bundler
Then try running Fastlane using Bundler: bundle exec fastlane <your_lane>
Specify Xcode Version in the Executor: Since the issue is unique to Xcode 16, try explicitly defining xcode: 15.1.0 in the CircleCI config to maintain consistency. Alternatively, if Xcode 16 is required, ensure that the macOS executor and CircleCI orb are compatible with the latest Xcode version.

Update the CircleCI Orb: You’re currently using circleci/macos@2.5.2. Check if there’s [Ed Financial](https://www-edfinancial.com) an updated version of this orb, as updates often include compatibility improvements for newer Xcode versions and macOS environments.

Fastlane File Configurations: The absence of Fastfile and Appfile could mean that Fastlane doesn’t have access to the necessary configurations. Ensure that both files are present in your repository and configured for the target environment.

**Comment by bruffster-clgx** [comment]
@ruby05guy, for what it's worth, your first suggestion worked for me. Prior we'd been using xcode 15.x without issue in combo with Ruby 3.3, however Xcode was upgraded to 16 and apparently the combination of Xcode 16 + Ruby 3.3 + fastlane started causing us issues. I was able to use Xcode 16 + Ruby 3.2 + Fastlane without issue.

**Comment by kpturner** [comment]
I still get this even using Ruby 3.2.2
`/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/terminal/io_console.rb:24:in `echo=': [!] Operation not supported on socket - <STDIN> (Errno::EOPNOTSUPP)`

**Comment by rangaiOS** [comment]
Anyone got solution for this ? I'm also still facing the same  pipeline error.

**Comment by patattack69** [comment]
@rangaiOS 
I am running ruby 3.2

```workflow
jobs:
  my_job:
    runs-on: macos-14-large
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
```
and fastlane is loading as expected

**Comment by patattack69** [comment]
oh ya I forgot that this is in Github Actions so maybe you will get lucky with Circle CI :)

**Comment by iBotPeaches** [comment]
Sorry for delay. With M1 runners gone on CircleCI and Apple forcing Xcode 26 now. The criteria of this report have kinda decayed out. I'll close this out to keep backlog organized.

I updated templates for example CI for both CircleCI and GitHub Actions

 - https://github.com/fastlane/docs/commit/4bc1c1929f0bc9174fa4cecbfce9013368418540
 - https://github.com/fastlane/docs/commit/8c833ee8c1013efe78f045a22470dd850a40627c
