### ISSUE TITLE
An attribute value is not acceptable for the current resource state. - contentRightsDeclaration

### ISSUE THREAD

**Issue by EliaTolin** [fastlane/fastlane#27458]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The Fastlane upload_to_app_store step fails with the error “An attribute value is not acceptable for the current resource state - contentRightsDeclaration.” This issue appears during the submission phase after successfully building and uploading the binary to App Store Connect.

##### Command executed
./deploy_on_stores.sh

```bash
echo "### INCREMENT VERSION ###" &&
VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //' | tr -d '\n' | tr -d '\r' | cut -d" " -f1)

MAJOR=$(echo $VERSION | cut -d. -f1)
MINOR=$(echo $VERSION | cut -d. -f2)
PATCH=$(echo $VERSION | cut -d+ -f1)
BUILD=$(echo $VERSION | cut -d+ -f2)

PATCH=$((PATCH + 1))
BUILD=$((BUILD + 1))

NEW_VERSION="$MAJOR.$MINOR.$PATCH+$BUILD"

sed -i '' "s/version: $VERSION/version: $NEW_VERSION/" pubspec.yaml &&
echo "FROM $VERSION TO $NEW_VERSION" &&

echo "#### BUILD IOS ####" &&
cd ios && 
fastlane release

echo "### INCREMENT VERSION ###" &&
VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //' | tr -d '\n' | tr -d '\r' | cut -d" " -f1)

MAJOR=$(echo $VERSION | cut -d. -f1)
MINOR=$(echo $VERSION | cut -d. -f2)
PATCH=$(echo $VERSION | cut -d+ -f1)
BUILD=$(echo $VERSION | cut -d+ -f2)

PATCH=$((PATCH + 1))
BUILD=$((BUILD + 1))

NEW_VERSION="$MAJOR.$MINOR.$PATCH+$BUILD"

sed -i '' "s/version: $VERSION/version: $NEW_VERSION/" pubspec.yaml &&
echo "FROM $VERSION TO $NEW_VERSION" &&

echo "#### BUILD IOS ####" &&
cd ios && 
fastlane release
```

### INCREMENT VERSION ###
FROM 1.1.7+22 TO 1.1.8+23
#### BUILD IOS ####
[✔] 🚀 
[11:09:40]: fastlane detected a Gemfile in the current directory
[11:09:40]: However, it seems like you didn't use `bundle exec`
[11:09:40]: To launch fastlane faster, please use
[11:09:40]: 
[11:09:40]: $ bundle exec fastlane release
[11:09:40]: 
[11:09:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+--------------------------------------------------------------------------------+
|                                  Used plugins                                  |
+---------------------------------+---------+------------------------------------+
| Plugin                          | Version | Action                             |
+---------------------------------+---------+------------------------------------+
| fastlane-plugin-shorebird       | 0.2.0   | shorebird_patch, shorebird_release |
| fastlane-plugin-flutter_version | 1.0.0   | flutter_version                    |
+---------------------------------+---------+------------------------------------+

[11:09:40]: ------------------------------
[11:09:40]: --- Step: default_platform ---
[11:09:40]: ------------------------------
[11:09:40]: Driving the lane 'ios release' 🚀
[11:09:40]: --------------------------
[11:09:40]: --- Step: notification ---
[11:09:40]: --------------------------
[11:09:42]: -------------------------------
[11:09:42]: --- Step: shorebird_release ---
[11:09:42]: -------------------------------
[11:09:42]: $ shorebird release ios
[11:09:43]: ▸ ✓ Fetching apps (0.4s)
[11:12:44]: ▸ ✓ Building ipa with Flutter 3.24.3 (5a6dc546e8) (180.4s)
[11:12:44]: ▸ ✓ Fetching releases (0.4s)
[11:12:44]: ▸ 🚀 Ready to create a new release!
[11:12:44]: ▸ 📱 App: amazing_app (d14bd0e7-c8ab-4971-92e2-f84da77642b4)
[11:12:44]: ▸ 📦 Release Version: 1.1.8+23
[11:12:44]: ▸ 🕹️  Platform: ios
[11:12:44]: ▸ 🐦 Flutter Version: 3.24.3 (5a6dc546e8)
[11:12:45]: ▸ ✓ Fetching releases (0.3s)
[11:12:45]: ▸ ✓ Creating release (0.6s)
[11:12:45]: ▸ ✓ Updating release status (0.3s)
[11:13:14]: ▸ ✓ Uploading artifacts (28.9s)
[11:13:16]: ▸ ✓ Updating release status (1.8s)
[11:13:16]: ▸ ✅ Published Release 1.1.8+23!
[11:13:16]: ▸ Your next step is to upload your app to App Store Connect.
[11:13:16]: ▸ To upload to the App Store, do one of the following:
[11:13:16]: ▸ 1. Open ../build/ios/archive/Runner.xcarchive in Xcode and use the "Distribute App" flow.
[11:13:16]: ▸ 2. Drag and drop the build/ios/ipa/*.ipa bundle into the Apple Transporter macOS app (https://apps.apple.com/us/app/transporter/id1450874784).
[11:13:16]: ▸ 3. Run xcrun altool --upload-app --type ios -f build/ios/ipa/*.ipa --apiKey your_api_key --apiIssuer your_issuer_id.
[11:13:16]: ▸ See "man altool" for details about how to authenticate with the App Store Connect API key.
[11:13:16]: ▸ To create a patch for this release, run shorebird patch --platforms=ios --release-version=1.1.8+23
[11:13:16]: ▸ Note: shorebird patch --platforms=ios without the --release-version option will patch the current version of the app.
[11:13:17]: ▸ A new version of shorebird is available!
[11:13:17]: ▸ Run shorebird upgrade to upgrade.
Setting IPA_OUTPUT_PATH to ../build/ios/ipa/amazing_app.ipa
[11:13:17]: --------------------------
[11:13:17]: --- Step: notification ---
[11:13:17]: --------------------------
[11:13:18]: ---------------------------------
[11:13:18]: --- Step: upload_to_app_store ---
[11:13:18]: ---------------------------------
[11:13:18]: Successfully loaded '/Users/eliatolin/Desktop/foo/amazing_app/amazing_app/ios/fastlane/Deliverfile' 📄
[11:13:18]: No values defined in './fastlane/Deliverfile'
[11:13:18]: Login to App Store Connect (mail@foo.com)
[11:13:20]: Login successful

+---------------------------------------------------------------------------------------------------+
|                                      deliver 2.225.0 Summary                                      |
+----------------------------------------------------------------+----------------------------------+
| submit_for_review                                              | true                             |
| automatic_release                                              | true                             |
| force                                                          | true                             |
| ipa                                                            | ../build/ios/ipa/amazing_app.ipa |
| submission_information.content_rights_contains_third_party_co  | false                            |
| ntent                                                          |                                  |
| submission_information.content_rights_has_rights               | true                             |
| submission_information.export_compliance_encryption_updated    | false                            |
| submission_information.export_compliance_uses_encryption       | false                            |
| submission_information.add_id_info_uses_idfa                   | false                            |
| screenshots_path                                               | ./fastlane/screenshots           |
| metadata_path                                                  | ./fastlane/metadata              |
| app_version                                                    | 1.1.8                            |
| username                                                       | mail@foo.com            |
| app_identifier                                                 | com.bar.amazing_app    |
| platform                                                       | ios                              |
| edit_live                                                      | false                            |
| use_live_version                                               | false                            |
| skip_binary_upload                                             | false                            |
| skip_screenshots                                               | false                            |
| skip_metadata                                                  | false                            |
| skip_app_version_update                                        | false                            |
| overwrite_screenshots                                          | false                            |
| screenshot_processing_timeout                                  | 3600                             |
| sync_screenshots                                               | false                            |
| verify_only                                                    | false                            |
| reject_if_possible                                             | false                            |
| version_check_wait_retry_limit                                 | 7                                |
| phased_release                                                 | false                            |
| reset_ratings                                                  | false                            |
| team_id                                                        | 123456789                        |
| dev_portal_team_id                                             | ABCDEFGHIL                       |
| run_precheck_before_submit                                     | true                             |
| precheck_default_rule_level                                    | warn                             |
| ignore_language_directory_validation                           | false                            |
| precheck_include_in_app_purchases                              | true                             |
+----------------------------------------------------------------+----------------------------------+

[11:13:21]: Making sure the latest version on App Store Connect matches '1.1.8'...
[11:13:22]: Successfully set the version to '1.1.8'
[11:13:22]: Loading './fastlane/metadata/it/description.txt'...
[11:13:22]: Loading './fastlane/metadata/it/keywords.txt'...
[11:13:22]: Loading './fastlane/metadata/it/release_notes.txt'...
[11:13:22]: Loading './fastlane/metadata/it/support_url.txt'...
[11:13:22]: Loading './fastlane/metadata/it/marketing_url.txt'...
[11:13:22]: Loading './fastlane/metadata/it/promotional_text.txt'...
[11:13:22]: Loading './fastlane/metadata/it/name.txt'...
[11:13:22]: Loading './fastlane/metadata/it/subtitle.txt'...
[11:13:22]: Loading './fastlane/metadata/it/privacy_url.txt'...
[11:13:22]: Loading './fastlane/metadata/it/apple_tv_privacy_policy.txt'...
[11:13:22]: Loading './fastlane/metadata/copyright.txt'...
[11:13:22]: Loading './fastlane/metadata/primary_category.txt'...
[11:13:22]: Loading './fastlane/metadata/secondary_category.txt'...
[11:13:22]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[11:13:22]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[11:13:22]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[11:13:22]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[11:13:22]: Loading './fastlane/metadata/review_information/first_name.txt'...
[11:13:22]: Loading './fastlane/metadata/review_information/last_name.txt'...
[11:13:22]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[11:13:22]: Loading './fastlane/metadata/review_information/email_address.txt'...
[11:13:22]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[11:13:22]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[11:13:22]: Loading './fastlane/metadata/review_information/notes.txt'...
[11:13:27]: No changes to localized App Info detected. Skipping upload.
[11:13:28]: Will begin uploading metadata for '1.1.8' on App Store Connect
[11:13:28]: Uploading metadata to App Store Connect for version
[11:13:32]: Uploading metadata to App Store Connect for localized version 'it'
[11:13:34]: Uploading app review information to App Store Connect
[11:13:36]: Will begin uploading snapshots for '1.1.8' on App Store Connect
[11:13:36]: Starting with the upload of screenshots...
[✔] Waiting for all the screenshots to finish being processed... 
[11:13:37]: Successfully uploaded all screenshots
[✔] Sorting screenshots uploaded... 
[11:13:38]: Successfully uploaded screenshots to App Store Connect
[11:13:38]: Uploading binary to App Store Connect
[11:13:38]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[11:13:45]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[11:13:46]: Going to upload updated app to App Store Connect
[11:13:46]: This might take a few minutes. Please don't interrupt the script.
[11:15:33]: ------------------------------------------------------------------------------------------------------------------
[11:15:33]: --- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
[11:15:33]: ------------------------------------------------------------------------------------------------------------------
[11:15:33]: Finished the upload to App Store Connect
[11:15:33]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[11:15:33]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+----------------------------------------------------------+
|               Summary for precheck 2.225.0               |
+--------------------------+-------------------------------+
| default_rule_level       | warn                          |
| include_in_app_purchases | true                          |
| app_identifier           | com.bar.amazing_app |
| username                 | mail@foo.com         |
| platform                 | ios                           |
| team_id                  | 123456789                     |
| use_live                 | false                         |
+--------------------------+-------------------------------+

[11:15:33]: Checking app for precheck rule violations
[11:15:37]: Reading in-app purchases. If you have a lot, this might take a while
[11:15:37]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[11:15:38]: Done reading in-app purchases
[11:15:38]: ✅  Passed: No negative  sentiment
[11:15:38]: ✅  Passed: No placeholder text
[11:15:38]: ✅  Passed: No mentioning  competitors
[11:15:38]: ✅  Passed: No future functionality promises
[11:15:38]: ✅  Passed: No words indicating test content
[11:15:38]: ✅  Passed: No curse words
[11:15:38]: ✅  Passed: No words indicating your IAP is free
[11:15:38]: ✅  Passed: Incorrect, or missing copyright date
[11:15:39]: ✅  Passed: No broken urls
[11:15:39]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[11:15:40]: Selecting the latest build...
[11:15:40]: Waiting for processing on... app_id: 6737453972, app_version: 1.1.8, build_version: 23, platform: IOS
[11:15:40]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
[11:15:40]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[11:15:56]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[11:16:11]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[11:16:27]: Waiting for App Store Connect to finish processing the new build (1.1.8 - 23) for IOS
[11:16:43]: Waiting for App Store Connect to finish processing the new build (1.1.8 - 23) for IOS
[11:16:59]: Waiting for App Store Connect to finish processing the new build (1.1.8 - 23) for IOS
[11:17:15]: Waiting for App Store Connect to finish processing the new build (1.1.8 - 23) for IOS
[11:17:32]: Waiting for App Store Connect to finish processing the new build (1.1.8 - 23) for IOS
[11:17:48]: Waiting for App Store Connect to finish processing the new build (1.1.8 - 23) for IOS
[11:18:04]: Waiting for App Store Connect to finish processing the new build (1.1.8 - 23) for IOS
[11:18:20]: Waiting for App Store Connect to finish processing the new build (1.1.8 - 23) for IOS
[11:18:37]: Waiting for App Store Connect to finish processing the new build (1.1.8 - 23) for IOS
[11:18:53]: Successfully finished processing the build 1.1.8 - 23 for IOS
[11:18:53]: Selecting build 1.1.8 (23)...
[11:18:55]: Successfully selected build
+-----------------------------------------------------+
|                    Lane Context                     |
+------------------+----------------------------------+
| DEFAULT_PLATFORM | ios                              |
| PLATFORM_NAME    | ios                              |
| LANE_NAME        | ios release                      |
| IPA_OUTPUT_PATH  | ../build/ios/ipa/amazing_app.ipa |
+------------------+----------------------------------+
[11:18:56]: Called from Fastfile at line 12
[11:18:56]: ```
[11:18:56]:     10:         shorebird_release(platform: "ios")
[11:18:56]:     11:         notification(subtitle: "iOS - Finished Building 🤖", message: "Ready to upload...")
[11:18:56]:  => 12:         upload_to_app_store(
[11:18:56]:     13:           submit_for_review: true, 
[11:18:56]:     14:           automatic_release: true,
[11:18:56]: ```
[11:18:56]: An attribute value is not acceptable for the current resource state. - contentRightsDeclaration

+------------------------------------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 2    | notification        | 1           |
| 3    | shorebird_release   | 215         |
| 4    | notification        | 0           |
| 💥   | upload_to_app_store | 337         |
+------+---------------------+-------------+

+-------------------------------------------------+
|            Plugin updates available             |
+-----------------+--------------+----------------+
| Plugin          | Your Version | Latest Version |
+-----------------+--------------+----------------+
| flutter_version | 1.0.0        | 1.1.15         |
+-----------------+--------------+----------------+
[11:18:56]: To update all plugins, just run
[11:18:56]: $ bundle exec fastlane update_plugins

[11:18:56]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [deliver] Spaceship::UnexpectedResponse: An attribute value is not acceptable for the current resource state.
    https://github.com/fastlane/fastlane/issues/17307 [closed] 11 💬
    18 Feb 2021

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/spaceship/lib/spaceship/connect_api/api_client.rb:223:in `handle_response': [!] An attribute value is not acceptable for the current resource state. - contentRightsDeclaration (Spaceship::UnexpectedResponse)
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/spaceship/lib/spaceship/connect_api/api_client.rb:136:in `patch'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:215:in `patch_app'
        from /Users/eliatolin/.rubies/ruby-3.3.5/lib/ruby/3.3.0/forwardable.rb:240:in `patch_app'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/spaceship/lib/spaceship/connect_api/models/app.rb:109:in `update'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/deliver/lib/deliver/submit_for_review.rb:136:in `update_submission_information'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/deliver/lib/deliver/submit_for_review.rb:23:in `submit!'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/deliver/lib/deliver/runner.rb:261:in `submit_for_review'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/deliver/lib/deliver/runner.rb:71:in `run'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:12:in `block (2 levels) in parsing_binding'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/eliatolin/.gem/ruby/3.3.5/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
        from /Users/eliatolin/.gem/ruby/3.3.5/bin/fastlane:25:in `load'
        from /Users/eliatolin/.gem/ruby/3.3.5/bin/fastlane:25:in `<main>'
<details>
  <pre>
```
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    notification(subtitle: "iOS - Start Building 🆕", message: "We build the magic....")
    shorebird_release(platform: "ios")
    notification(subtitle: "iOS - Finished Building 🤖", message: "Ready to upload...")
    upload_to_app_store(
      submit_for_review: true, 
      automatic_release: true,
      force: true,
      ipa: "../build/ios/amazing_app/.ipa",
      submission_information: {
        content_rights_contains_third_party_content: false,
        content_rights_has_rights: true,
        export_compliance_encryption_updated: false,
        export_compliance_uses_encryption: false,
        add_id_info_uses_idfa: false
      }
    )
    notification(subtitle: "iOS - Submitted on stores ✅", message: "App is waiting for review...")
  end
end
 </pre>
</details>
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 15.0.1                                      |
| Ruby                        | 3.3.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.43.0                          |
| Installation Source         | ~/.gem/ruby/3.3.5/bin/fastlane              |
| Host                        | macOS 15.0.1 (24A348)                       |
| Ruby Lib Dir                | ~/.rubies/ruby-3.3.5/lib                    |
| OpenSSL Version             | OpenSSL 3.3.2 3 Sep 2024                    |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 16.0                                        |
| Swift Version               | 6.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.225.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.6.0        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.0        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.1000.0     |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.10.1       |
| aws-sdk-core                    | 3.211.0      |
| aws-sdk-kms                     | 1.95.0       |
| aws-sdk-s3                      | 1.169.0      |
| babosa                          | 1.0.4        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.112.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| faraday                         | 1.10.4       |
| faraday_middleware              | 1.2.1        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.7        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.1        |
| sysrandom                       | 1.0.5        |
| fastlane-sirp                   | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.9.3        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.1        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| mini_magick                     | 4.13.2       |
| naturally                       | 2.2.1        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.6.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.4.0        |
| xcodeproj                       | 1.27.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.0        |
| public_suffix                   | 6.0.1        |
| bundler                         | 2.5.22       |
| rexml                           | 3.3.9        |
| nkf                             | 0.2.0        |
| base64                          | 0.2.0        |
| ruby2_keywords                  | 0.0.5        |
| rake                            | 13.2.1       |
| json                            | 2.7.5        |
| optparse                        | 0.5.0        |
| forwardable                     | 1.3.3        |
| logger                          | 1.6.0        |
| pathname                        | 0.3.0        |
| shellwords                      | 0.2.0        |
| cgi                             | 0.4.1        |
| date                            | 3.3.4        |
| timeout                         | 0.4.1        |
| stringio                        | 3.1.1        |
| securerandom                    | 0.3.1        |
| uri                             | 0.13.1       |
| ipaddr                          | 1.2.6        |
| openssl                         | 3.2.0        |
| digest                          | 3.1.1        |
| io-nonblock                     | 0.3.0        |
| zlib                            | 3.1.1        |
| resolv                          | 0.3.0        |
| io-wait                         | 0.3.1        |
| time                            | 0.3.0        |
| open-uri                        | 0.4.1        |
| mutex_m                         | 0.2.0        |
| net-http                        | 0.4.1        |
| net-protocol                    | 0.2.2        |
| english                         | 0.8.0        |
| erb                             | 4.0.3        |
| strscan                         | 3.0.9        |
| abbrev                          | 0.1.2        |
| io-console                      | 0.7.1        |
| tempfile                        | 0.2.1        |
| delegate                        | 0.3.1        |
| fileutils                       | 1.7.2        |
| tmpdir                          | 0.2.0        |
| singleton                       | 0.2.0        |
| open3                           | 0.2.1        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.5.0        |
| find                            | 0.2.0        |
| ostruct                         | 0.6.0        |
| yaml                            | 0.3.0        |
| psych                           | 5.1.2        |
</details>

*generated on:* **2024-11-04**
</details>

<details>
  <pre> </pre>
</details>

**Comment by michelle653burkes** [comment]
Hello!
The "contentRightsDeclaration" error during the Fastlane upload_to_app_store step often occurs due to incorrect API key permissions or outdated parameters. Ensure your API key has the necessary permissions and update any deprecated parameters in your submission information. If the issue persists, try removing parameters like content_rights_has_rights and content_rights_contains_third_party_content.

**Comment by EliaTolin** [comment]
> Hello! The "contentRightsDeclaration" error during the Fastlane upload_to_app_store step often occurs due to incorrect API key permissions or outdated parameters. Ensure your API key has the necessary permissions and update any deprecated parameters in your submission information. If the issue persists, try removing parameters like content_rights_has_rights and content_rights_contains_third_party_content.

Thank u for your reply.
I use this API key in two apps and in one it work.

**Comment by EliaTolin** [comment]
I tried with:

`
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    notification(subtitle: "iOS - Start Building 🆕", message: "We build the magic....")
    shorebird_release(platform: "ios")
    notification(subtitle: "iOS - Finished Building 🤖", message: "Ready to upload...")
    upload_to_app_store(
      submit_for_review: true, 
      automatic_release: true,
      force: true,
      ipa: "../build/ios/ipa/foo.ipa",
      submission_information: {
        export_compliance_encryption_updated: false,
        export_compliance_uses_encryption: false,
        content_rights_contains_third_party_content: false,
        add_id_info_uses_idfa: false
      }
    )
    notification(subtitle: "iOS - Submitted on stores ✅", message: "App is waiting for review...")
  end
end
`
This configuration works perfectly in another app.

**Comment by redreceipt** [comment]
This is still an issue for us. We have 50 apps, this affects about 10 of them. Probably related, these are the apps where I can not edit "Content Rights" in App Store Connect. I'm expecting an edit button here. Any insight is appreciated.

<img width="860" height="193" alt="Image" src="https://github.com/user-attachments/assets/ccb1ea1a-94c7-4db4-ae3e-53fc0559022f" />

**Comment by ndemie** [comment]
Same issue here as above. We run multiple whitelabel apps. A very small portion of the apps run into this issue

**Comment by ndemie** [comment]
I narrowed down the issue. During first-time setup the question `Does your app contain, display, or access third-party content` is asked. When you answer yes here, Fastlane will always fail with this error.

The whole process succeeds, it's just that Fastlane doesn't submit the app for review. Very annoying
