### ISSUE TITLE
Fastlane 2.225.0 fails to launch with error about sysrandom

### ISSUE THREAD

**Issue by juri** [fastlane/fastlane#27548]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm running Fastlane 2.225.0 installed from Homebrew on macOS Sequoia. I _think_ the Ruby 3.3.6 update broke Fastlane, because it works on a computer that's still on 3.3.5. When I launch Fastlane, I get an error about `sysrandom` gem, even if it's just running `fastlane --version` in a folder with no Fastfile.

##### Command executed

`fastlane --version`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
% fastlane --version
/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1417:in `rescue in block in activate_dependencies': Could not find 'sysrandom' (~> 1.0) among 154 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/buildkite/.local/share/fastlane/3.3.0:/opt/homebrew/Cellar/fastlane/2.225.0/libexec' at: /opt/homebrew/Cellar/fastlane/2.225.0/libexec/specifications/fastlane-sirp-1.0.0.gemspec, execute `gem env` for more information
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1414:in `block in activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `each'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1385:in `activate'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1421:in `block in activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `each'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1385:in `activate'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems.rb:280:in `block in activate_bin_path'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems.rb:279:in `synchronize'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems.rb:279:in `activate_bin_path'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/dependency.rb:303:in `to_specs': Could not find 'sysrandom' (~> 1.0) - did find: [sysrandom-1.0.5] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/buildkite/.local/share/fastlane/3.3.0:/opt/homebrew/Cellar/fastlane/2.225.0/libexec' , execute `gem env` for more information
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1415:in `block in activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `each'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1385:in `activate'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1421:in `block in activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `each'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1403:in `activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1385:in `activate'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems.rb:280:in `block in activate_bin_path'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems.rb:279:in `synchronize'
        from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems.rb:279:in `activate_bin_path'
        from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `<main>'
  </pre>
</details>

### Environment

`fastlane env` fails the same as `--version`. Here's what `sw_vers` says:

```
ProductName:            macOS
ProductVersion:         15.1
BuildVersion:           24B83
```

**Comment by velma41abbott** [comment]
Hello,

You're encountering an issue where Fastlane is not working after updating Ruby to version 3.3.6 on macOS Sequoia, and it’s throwing an error related to the sysrandom gem. Since Fastlane works fine on a machine with Ruby 3.3.5, the issue seems to be specifically related to the new Ruby version.

Here’s a step-by-step checklist of things you can try to resolve this issue:
1. Check Ruby Version

Verify the exact Ruby version you're running with:
ruby -v
Ensure it is Ruby 3.3.6 (or whatever version you suspect is causing the issue).
2. Reinstall sysrandom Gem

The error might be related to a gem conflict or installation issue, especially with the updated Ruby version. Try reinstalling the sysrandom gem:
gem uninstall sysrandom
gem install sysrandom
3. Reinstall Fastlane

Since Fastlane is often tightly coupled with Ruby and its gems, try reinstalling Fastlane to ensure all dependencies are correct:brew uninstall fastlane
brew install fastlane
Alternatively, if you installed Fastlane via other means (like gem install fastlane), try reinstalling using that method.
4. Update Homebrew and Dependencies

Ensure that both Homebrew and all installed dependencies are up-to-date:brew update
brew upgrade
brew doctor
After updating Homebrew, you can try reinstalling Fastlane again.
5. Check for Known Issues on GitHub

Since you're already familiar with searching GitHub issues, check the Fastlane GitHub Issues for any reported problems related to Ruby 3.3.6 and sysrandom. You might find others with the same issue, along with possible solutions or workarounds.
6. Try a Different Ruby Version (Temporarily)

If the issue is definitely tied to Ruby 3.3.6, you could temporarily downgrade your Ruby version to 3.3.5 (which is working for you) using a version manager like rbenv or rvm:

    Install rbenv (if not already installed):brew install rbenv
nstall Ruby 3.3.5:
rbenv install 3.3.5
rbenv global 3.3.5
After switching Ruby versions, reinstall Fastlane:
gem install fastlane
7. Check for macOS Compatibility

Given that you're on macOS Sequoia (macOS 15.1), ensure that your Fastlane version (2.225.0) and Ruby are fully compatible with the macOS version you're using. Sometimes, newer macOS versions introduce compatibility issues with certain tools, especially after system updates.
8. Run fastlane env in Debug Mode

Run fastlane env again with debugging to capture more detailed logs. This might help pinpoint where the issue is occurring: FASTLANE_DEBUG=1 fastlane env
Look for anything unusual in the output, especially related to the sysrandom gem or Ruby environment.
9. Verify Dependencies

Sometimes, system dependencies like OpenSSL or other libraries can cause issues with gem installations. Make sure all required system libraries are correctly installed:brew install openssl


hope that helps!

**Comment by juri** [comment]
I worked around the problem by switching the project over to using `asdf` to install Ruby 3.3.5 and fastlane.

**Comment by Ladvace** [comment]
any updates?

**Comment by joshbuhler** [comment]
I ran into this issue as well after updating to Fastlane 2.226.0 on macOS 15.2. Resolved it by uninstalling Fastlane using `brew uninstall fastlane` and then re-installing using `brew install fastlane`.

**Comment by Ladvace** [comment]
In my case, I fixed it, uninstalling ruby, reinstalling it with brew and then installing Fastlane

**Comment by Brenndoerfer** [comment]
**This fixed it for me.** Downgrading to a specific version (2.224.0 of fastlane) with brew has become unnecessarily complex.

This version is the most recent working version. After this my eas build (expo) worked again.
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/4209dee/Formula/fastlane.rb


brew tap-new $USER/fastlane
brew tap homebrew/core --force
brew extract --version=2.224.0 fastlane $USER/fastlane
brew install fastlane@2.224.0
```

**Comment by iBotPeaches** [comment]
I fixed this in - https://github.com/fastlane/fastlane/pull/29973, released v1.1.0 of sirp which no longer depends on that old old version of sysrandom.

Closing this out.
