### ISSUE TITLE
Error: [!] Cannot update languages - could not find an editable version for 'IOS' (FastlaneCore::Interface::FastlaneError)

### ISSUE THREAD

**Issue by Computeeeeeeeeee** [fastlane/fastlane#28039]
Hi,

I am unable to upload new version for ios app in app store which has arabic language .Here ,ar-SA is not supported, as per apple we should use ar tag for arabic but if i use ar tag then that is not available for fastlane. Please suggest.

INFO [2024-11-14 16:27:06.68]: Detected languages: ["ar-SA", "default", "en-GB"]
INFO [2024-11-14 16:27:06.96]: Cannot find edit app store version... Retrying after 20 seconds (remaining: 6)
INFO [2024-11-14 16:27:27.18]: Cannot find edit app store version... Retrying after 40 seconds (remaining: 5)
INFO [2024-11-14 16:28:07.46]: Cannot find edit app store version... Retrying after 80 seconds (remaining: 4)
INFO [2024-11-14 16:29:27.76]: Cannot find edit app store version... Retrying after 160 seconds (remaining: 3)
INFO [2024-11-14 16:32:08.16]: Cannot find edit app store version... Retrying after 300 seconds (remaining: 2)
App Store Connect API token expired at 2024-11-14 16:35:26 +0000... refreshing

INFO [2024-11-14 16:32:08.16]: Cannot find edit app store version... Retrying after 300 seconds (remaining: 2)
App Store Connect API token expired at 2024-11-14 16:35:26 +0000... refreshing
INFO [2024-11-14 16:37:09.21]: Cannot find edit app store version... Retrying after 300 seconds (remaining: 1)
INFO [2024-11-14 16:42:09.81]: Cannot find edit app store version... Retrying after 300 seconds (remaining: 0)
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Cannot update languages - could not find an editable version for 'IOS' (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/deliver/lib/deliver/upload_metadata.rb:554:in `verify_available_version_languages!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/deliver/lib/deliver/upload_metadata.rb:97:in `upload'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/deliver/lib/deliver/runner.rb:152:in `upload_metadata'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/deliver/lib/deliver/runner.rb:61:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'

**Comment by allan735** [comment]
The issue likely stems from using "ar-SA" instead of "ar" for Arabic in your app metadata. App Store Connect requires "ar" for Arabic. Modify your app code or Fastlane script to use "ar" as the language code. Rebuild and test your app with the updated code. Refer to the Fastlane documentation for best practices. [Receiptify Music](https://www.receiptifys.com/)
