### ISSUE TITLE
2.225.0 match_nuke fails with "io_console.rb:24:in `echo=': [!] Operation not supported on socket" 

### ISSUE THREAD

**Issue by kpturner** [fastlane/fastlane#28303]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I try to run match_nuke it fails with 
`/Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/terminal/io_console.rb:24:in `echo=': [!] Operation not supported on socket - <STDIN> (Errno::EOPNOTSUPP)`

##### Command executed
`fastlane run match_nuke type:development api_key_path:"fastlane/app-store-connect-api-key.json"`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
    /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/terminal/io_console.rb:24:in `echo=': [!] Operation not supported on socket - <STDIN> (Errno::EOPNOTSUPP)
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/terminal/io_console.rb:24:in `restore_mode'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/terminal.rb:70:in `ensure in raw_no_echo_mode_exec'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/terminal.rb:70:in `raw_no_echo_mode_exec'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline.rb:608:in `get_response_character_mode'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/question.rb:522:in `get_response'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/question.rb:536:in `get_response_or_default'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/question_asker.rb:30:in `ask_once'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline.rb:223:in `ask'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline.rb:194:in `agree'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/forwardable.rb:240:in `agree'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/forwardable.rb:240:in `agree'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:139:in `confirm'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/match/lib/match/nuke.rb:189:in `filter_by_cert'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/match/lib/match/nuke.rb:59:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/match_nuke.rb:13:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from src/development.rb:22:in `ios_development_signing'
        from Fastfile:26:in `block (2 levels) in parsing_binding'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/fastlane:25:in `load'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/fastlane:25:in `<top (required)>'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/bundle:25:in `load'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/bundle:25:in `<main>'
/Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/terminal/io_console.rb:18:in `echo=': Operation not supported on socket - <STDIN> (Errno::EOPNOTSUPP)
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/terminal/io_console.rb:18:in `raw_no_echo_mode'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/terminal.rb:67:in `raw_no_echo_mode_exec'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline.rb:608:in `get_response_character_mode'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/question.rb:522:in `get_response'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/question.rb:536:in `get_response_or_default'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline/question_asker.rb:30:in `ask_once'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline.rb:223:in `ask'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/highline-2.0.3/lib/highline.rb:194:in `agree'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/forwardable.rb:240:in `agree'
        from /Users/kpturner/.rubies/ruby-3.2.2/lib/ruby/3.2.0/forwardable.rb:240:in `agree'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:139:in `confirm'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/match/lib/match/nuke.rb:189:in `filter_by_cert'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/match/lib/match/nuke.rb:59:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/match_nuke.rb:13:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from src/development.rb:22:in `ios_development_signing'
        from Fastfile:26:in `block (2 levels) in parsing_binding'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/fastlane:25:in `load'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/fastlane:25:in `<top (required)>'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/kpturner/.gem/ruby/3.2.2/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/bundle:25:in `load'
        from /Users/kpturner/.gem/ruby/3.2.2/bin/bundle:25:in `<main>'
  </pre>
</details>

### Environment
<details>
  <pre>
     <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.5                                        |
| Ruby                        | 3.2.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.0                          |
| Installation Source         | ~/.gem/ruby/3.2.2/bin/fastlane              |
| Host                        | macOS 14.5 (23F79)                          |
| Ruby Lib Dir                | ~/.rubies/ruby-3.2.2/lib                    |
| OpenSSL Version             | OpenSSL 3.2.0 23 Nov 2023                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 16.1                                        |
| Swift Version               | 6.0.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.225.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-load_json              | 0.0.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android     | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-slack_bot              | 1.4.0   | ✅ Up-To-Date  |
| fastlane-plugin-semantic_release       | 1.18.2  | ✅ Up-To-Date  |
| fastlane-plugin-browserstack           | 0.3.3   | ✅ Up-To-Date  |
| fastlane-plugin-sentry                 | 1.25.1  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| error_highlight                        | 0.6.0        |
| did_you_mean                           | 1.6.3        |
| syntax_suggest                         | 2.0.1        |
| babosa                                 | 1.0.4        |
| colored                                | 1.2          |
| highline                               | 2.0.3        |
| commander                              | 4.6.0        |
| dotenv                                 | 2.8.1        |
| emoji_regex                            | 3.2.3        |
| faraday-cookie_jar                     | 0.0.7        |
| sysrandom                              | 1.0.5        |
| fastlane-sirp                          | 1.0.0        |
| gh_inspector                           | 1.1.3        |
| google-cloud-env                       | 1.6.0        |
| naturally                              | 2.2.1        |
| rubyzip                                | 2.3.2        |
| security                               | 0.1.5        |
| simctl                                 | 1.6.10       |
| terminal-notifier                      | 2.0.0        |
| terminal-table                         | 3.0.2        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| word_wrap                              | 1.0.0        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| xcpretty-travis-formatter              | 1.0.1        |
| set                                    | 1.1.0        |
| public_suffix                          | 6.0.1        |
| addressable                            | 2.8.7        |
| artifactory                            | 3.0.17       |
| aws-eventstream                        | 1.3.0        |
| aws-sigv4                              | 1.10.1       |
| aws-partitions                         | 1.1011.0     |
| jmespath                               | 1.6.2        |
| aws-sdk-core                           | 3.213.0      |
| aws-sdk-kms                            | 1.96.0       |
| aws-sdk-s3                             | 1.172.0      |
| bundler                                | 2.5.22       |
| base64                                 | 0.2.0        |
| nkf                                    | 0.2.0        |
| rexml                                  | 3.3.9        |
| CFPropertyList                         | 3.0.7        |
| excon                                  | 0.112.0      |
| ruby2_keywords                         | 0.0.5        |
| faraday-retry                          | 1.0.3        |
| faraday-rack                           | 1.0.0        |
| faraday-patron                         | 1.0.0        |
| faraday-net_http_persistent            | 1.2.0        |
| faraday-net_http                       | 1.0.2        |
| multipart-post                         | 2.4.1        |
| faraday-multipart                      | 1.0.4        |
| faraday-httpclient                     | 1.0.1        |
| faraday-excon                          | 1.1.0        |
| faraday-em_synchrony                   | 1.0.0        |
| faraday-em_http                        | 1.0.0        |
| faraday                                | 1.10.4       |
| faraday_middleware                     | 1.2.1        |
| domain_name                            | 0.6.20240107 |
| http-cookie                            | 1.0.7        |
| fastimage                              | 2.3.1        |
| httpclient                             | 2.8.3        |
| multi_json                             | 1.15.0       |
| jwt                                    | 2.9.3        |
| signet                                 | 0.19.0       |
| os                                     | 1.1.4        |
| googleauth                             | 1.8.1        |
| mini_mime                              | 1.1.5        |
| retriable                              | 3.1.2        |
| trailblazer-option                     | 0.1.2        |
| declarative                            | 0.0.20       |
| uber                                   | 0.1.0        |
| representable                          | 3.2.0        |
| google-apis-core                       | 0.11.3       |
| google-apis-androidpublisher_v3        | 0.54.0       |
| google-apis-playcustomapp_v1           | 0.13.0       |
| rake                                   | 13.2.1       |
| digest-crc                             | 0.6.5        |
| google-apis-storage_v1                 | 0.31.0       |
| google-apis-iamcredentials_v1          | 0.17.0       |
| google-cloud-errors                    | 1.4.0        |
| google-cloud-core                      | 1.7.1        |
| google-cloud-storage                   | 1.47.0       |
| json                                   | 2.8.2        |
| mini_magick                            | 4.13.2       |
| optparse                               | 0.6.0        |
| plist                                  | 3.7.1        |
| unicode-display_width                  | 2.6.0        |
| tty-screen                             | 0.8.2        |
| nanaimo                                | 0.4.0        |
| colored2                               | 3.1.2        |
| claide                                 | 1.1.0        |
| atomos                                 | 0.1.3        |
| xcodeproj                              | 1.27.0       |
| forwardable                            | 1.3.3        |
| logger                                 | 1.6.1        |
| pathname                               | 0.3.0        |
| shellwords                             | 0.2.0        |
| cgi                                    | 0.4.1        |
| date                                   | 3.3.4        |
| timeout                                | 0.4.1        |
| securerandom                           | 0.3.2        |
| cookiejar                              | 0.3.4        |
| eventmachine                           | 1.2.7        |
| em-socksify                            | 0.3.3        |
| http_parser.rb                         | 0.8.0        |
| em-http-request                        | 1.1.7        |
| resolv                                 | 0.4.0        |
| openssl                                | 3.2.0        |
| digest                                 | 3.1.1        |
| ipaddr                                 | 1.2.7        |
| time                                   | 0.4.0        |
| uri                                    | 0.13.1       |
| open-uri                               | 0.4.1        |
| stringio                               | 3.1.1        |
| mutex_m                                | 0.2.0        |
| net-http                               | 0.4.1        |
| net-protocol                           | 0.2.2        |
| connection_pool                        | 2.4.1        |
| net-http-persistent                    | 4.0.4        |
| patron                                 | 0.13.3       |
| english                                | 0.8.0        |
| erb                                    | 4.0.4        |
| abbrev                                 | 0.1.2        |
| tempfile                               | 0.2.1        |
| delegate                               | 0.3.1        |
| tmpdir                                 | 0.2.0        |
| fileutils                              | 1.7.2        |
| singleton                              | 0.2.0        |
| open3                                  | 0.2.1        |
| pp                                     | 0.5.0        |
| prettyprint                            | 0.2.0        |
| find                                   | 0.2.0        |
| ostruct                                | 0.6.0        |
| yaml                                   | 0.3.0        |
| psych                                  | 5.1.2        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-load_json              | 0.0.1        |
| fastlane-plugin-versioning_android     | 0.1.1        |
| fastlane-plugin-slack_bot              | 1.4.0        |
| fastlane-plugin-semantic_release       | 1.18.2       |
| http-accept                            | 1.7.0        |
| netrc                                  | 0.11.0       |
| rest-client                            | 2.1.0        |
| fastlane-plugin-browserstack           | 0.3.3        |
| mime-types                             | 3.6.0        |
| mime-types-data                        | 3.2024.1105  |
| fastlane-plugin-sentry                 | 1.25.1       |
</details>

*generated on:* **2024-11-21**
</details> 
  </pre>
</details>

**Comment by kpturner** [comment]
This is a bit of a blocker for us so it is a bit disappointing that it has received no traction at all.

It seems that despite specifying `skip_confirmation: true` it is still trying to interact with terminal in some way. 

What is the recommended Ruby version for Fastlane 2.225.0 ?

**Comment by kpturner** [comment]
The problem is that the execution of `nuke_it_now!` is guarded by ` if` like so
```
if FastlaneCore::UI.confirm('Do you really want to nuke everything listed above?')
   nuke_it_now!
``` 
when it should be
```
if params[:skip_confirmation] || FastlaneCore::UI.confirm('Do you really want to nuke everything listed above?')
   nuke_it_now!
```

Until this is fixed I have had to clone the `match_nuke` action locally and implement this fix.

**Comment by rangaiOS** [comment]
Anyone got solution for this ? I'm also still facing the same  pipeline error.

**Comment by iBotPeaches** [comment]
Sorry for delay. I've put up a PR for this so we respect `skip_confirmation` - https://github.com/fastlane/fastlane/pull/30023
