### ISSUE TITLE
Parse error during notarization step

### ISSUE THREAD

**Issue by tsfischer** [fastlane/fastlane#28817]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Our pipeline occasionally errors out during the notarization step. What appears to be happening is that the notarytool is returning an error message, and then a JSON blob. The JSON blob shows that the notarization actually succeeded. However, Fastlane appears to be attempting to parse the entire output, including the error message, which results in an error and a failed build.

In the output below, note the following output from notarytool:

<pre>
INFO [2024-12-04 12:18:33.64]: ▸ 2024-12-04 12:18:33.645 notarytool[71723:207144] Error: execSQLStatement:onConnection:toCompletionWithRetry:writeLockHelp - SQL=CREATE INDEX request_key_index ON cfurl_cache_response(request_key);, error-code=1, error-message=no such table: main.cfurl_cache_response
INFO [2024-12-04 12:18:33.64]: ▸ 2024-12-04 12:18:33.645 notarytool[71723:207144] ERROR: NSURLStorageURLCacheDB _setDBSchema: DB=/Users/anka/Library/Caches/com.apple.gke.notary.tool/Cache.db index on request_key - no such table: main.cfurl_cache_response. ErrCode: 1.
INFO [2024-12-04 12:19:02.71]: ▸ {"id":"e82d9517-22c8-4497-ae62-0e05708b895d","message":"Processing complete","status":"Accepted"}
</pre>

It looks like Fastlane is expecting it to return only the final line (the JSON blob starting with "id"). I don't know why this error is happening (possibly an Apple bug?), but the command does seem to succeed even with it.

##### Command executed
Here is the relevant portion of the output

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
INFO [2024-12-04 12:18:32.31]: $ xcrun notarytool submit build/Artifacts/RemoteCapability.app.zip --output-format json --wait --key /var/folders/rz/ndm56hds6_79jhs8w76s7jg80000gn/T/20241204-71633-5855fk --key-id G29R7N8MBA --issuer 69a6de6e-75c9-47e3-e053-5b8c7c11a4d1
INFO [2024-12-04 12:18:33.64]: ▸ 2024-12-04 12:18:33.645 notarytool[71723:207144] Error: execSQLStatement:onConnection:toCompletionWithRetry:writeLockHelp - SQL=CREATE INDEX request_key_index ON cfurl_cache_response(request_key);, error-code=1, error-message=no such table: main.cfurl_cache_response
INFO [2024-12-04 12:18:33.64]: ▸ 2024-12-04 12:18:33.645 notarytool[71723:207144] ERROR: NSURLStorageURLCacheDB _setDBSchema: DB=/Users/anka/Library/Caches/com.apple.gke.notary.tool/Cache.db index on request_key - no such table: main.cfurl_cache_response. ErrCode: 1.
INFO [2024-12-04 12:19:02.71]: ▸ {"id":"e82d9517-22c8-4497-ae62-0e05708b895d","message":"Processing complete","status":"Accepted"}
WARN [2024-12-04 12:19:02.72]: Lane Context:
INFO [2024-12-04 12:19:02.72]: {:DEFAULT_PLATFORM=>:mac, :PLATFORM_NAME=>:mac, :LANE_NAME=>"mac notarize_remote_capability"}
ERROR [2024-12-04 12:19:02.72]: Called from Fastfile at line 169
ERROR [2024-12-04 12:19:02.72]: ```
ERROR [2024-12-04 12:19:02.72]:     167:	        options[:verbose] = true
ERROR [2024-12-04 12:19:02.72]:     168:	        options[:use_notarytool] = true
ERROR [2024-12-04 12:19:02.72]:  => 169:	        notarize(options)
ERROR [2024-12-04 12:19:02.72]:     170:	
ERROR [2024-12-04 12:19:02.72]:     171:	        # Tar artifact if it is an .app
ERROR [2024-12-04 12:19:02.72]: ```
ERROR [2024-12-04 12:19:02.73]: unexpected token at '-12-04 12:18:33.645 notarytool[71723:207144] Error: execSQLStatement:onConnection:toCompletionWithRetry:writeLockHelp - SQL=CREATE INDEX request_key_index ON cfurl_cache_response(request_key);, error-code=1, error-message=no such table: main.cfurl_cache_response
2024-12-04 12:18:33.645 notarytool[71723:207144] ERROR: NSURLStorageURLCacheDB _setDBSchema: DB=/Users/anka/Library/Caches/com.apple.gke.notary.tool/Cache.db index on request_key - no such table: main.cfurl_cache_response. ErrCode: 1.
{"id":"e82d9517-22c8-4497-ae62-0e05708b895d","message":"Processing complete","status":"Accepted"}
'
INFO [2024-12-04 12:19:02.77]: Successfully generated documentation at path '/Users/anka/workspace/wesome_Possum_Unified_App_PR-235/fastlane/README.md'

+---------------------------------------------------------+
|                    fastlane summary                     |
+------+------------------------------------+-------------+
| Step | Action                             | Time (in s) |
+------+------------------------------------+-------------+
| 1    | mkdir -p ../build/.fastlane_cache  | 0           |
| 2    | import_from_git                    | 0           |
| 3    | which mise                         | 0           |
| 4    | default_platform                   | 0           |
| 5    | Switch to mac notarize_custom lane | 0           |
| 💥   | notarize                           | 30          |
+------+------------------------------------+-------------+

ERROR [2024-12-04 12:19:02.78]: fastlane finished with errors
/Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `parse': [!] unexpected token at '-12-04 12:18:33.645 notarytool[71723:207144] Error: execSQLStatement:onConnection:toCompletionWithRetry:writeLockHelp - SQL=CREATE INDEX request_key_index ON cfurl_cache_response(request_key);, error-code=1, error-message=no such table: main.cfurl_cache_response (JSON::ParserError)
2024-12-04 12:18:33.645 notarytool[71723:207144] ERROR: NSURLStorageURLCacheDB _setDBSchema: DB=/Users/anka/Library/Caches/com.apple.gke.notary.tool/Cache.db index on request_key - no such table: main.cfurl_cache_response. ErrCode: 1.
{"id":"e82d9517-22c8-4497-ae62-0e05708b895d","message":"Processing complete","status":"Accepted"}
'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `parse'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/actions/notarize.rb:85:in `notarytool'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/actions/notarize.rb:42:in `run'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:169:in `block (2 levels) in parsing_binding'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:137:in `block (2 levels) in parsing_binding'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/bin/fastlane:23:in `<top (required)>'
	from /Users/anka/.rbenv/versions/3.3.5/bin/fastlane:25:in `load'
	from /Users/anka/.rbenv/versions/3.3.5/bin/fastlane:25:in `<main>'
/Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `parse': unexpected token at '-12-04 12:18:33.645 notarytool[71723:207144] Error: execSQLStatement:onConnection:toCompletionWithRetry:writeLockHelp - SQL=CREATE INDEX request_key_index ON cfurl_cache_response(request_key);, error-code=1, error-message=no such table: main.cfurl_cache_response (JSON::ParserError)
2024-12-04 12:18:33.645 notarytool[71723:207144] ERROR: NSURLStorageURLCacheDB _setDBSchema: DB=/Users/anka/Library/Caches/com.apple.gke.notary.tool/Cache.db index on request_key - no such table: main.cfurl_cache_response. ErrCode: 1.
{"id":"e82d9517-22c8-4497-ae62-0e05708b895d","message":"Processing complete","status":"Accepted"}
'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json-2.7.2/lib/json/common.rb:220:in `parse'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/actions/notarize.rb:85:in `notarytool'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/actions/notarize.rb:42:in `run'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:169:in `block (2 levels) in parsing_binding'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:137:in `block (2 levels) in parsing_binding'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.224.0/bin/fastlane:23:in `<top (required)>'
	from /Users/anka/.rbenv/versions/3.3.5/bin/fastlane:25:in `load'
	from /Users/anka/.rbenv/versions/3.3.5/bin/fastlane:25:in `<main>'
script returned exit code 1 </pre>
</details>

### Environment

<details>
  <pre><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.6.0        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.0        |
| public_suffix                   | 6.0.1        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.958.0      |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.9.0        |
| aws-sdk-core                    | 3.201.3      |
| aws-sdk-kms                     | 1.88.0       |
| aws-sdk-s3                      | 1.156.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.5.14       |
| strscan                         | 3.0.9        |
| rexml                           | 3.2.9        |
| nkf                             | 0.1.3        |
| base64                          | 0.2.0        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.111.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.6        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.8.2        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.2.1       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.7.1        |
| mini_magick                     | 4.13.2       |
| naturally                       | 2.2.1        |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.24.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.0        |
| forwardable                     | 1.3.3        |
| logger                          | 1.6.0        |
| pathname                        | 0.3.0        |
| shellwords                      | 0.2.0        |
| cgi                             | 0.4.1        |
| date                            | 3.3.4        |
| timeout                         | 0.4.1        |
| stringio                        | 3.1.1        |
| securerandom                    | 0.3.1        |
| uri                             | 0.13.0       |
| ipaddr                          | 1.2.6        |
| openssl                         | 3.2.0        |
| digest                          | 3.1.1        |
| io-nonblock                     | 0.3.0        |
| zlib                            | 3.1.1        |
| resolv                          | 0.3.0        |
| io-wait                         | 0.3.1        |
| time                            | 0.3.0        |
| open-uri                        | 0.4.1        |
| mutex_m                         | 0.2.0        |
| net-http                        | 0.4.1        |
| net-protocol                    | 0.2.2        |
| ostruct                         | 0.6.0        |
| english                         | 0.8.0        |
| erb                             | 4.0.3        |
| abbrev                          | 0.1.2        |
| io-console                      | 0.7.1        |
| tempfile                        | 0.2.1        |
| delegate                        | 0.3.1        |
| fileutils                       | 1.7.2        |
| tmpdir                          | 0.2.0        |
| singleton                       | 0.2.0        |
| open3                           | 0.2.1        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.5.0        |
| find                            | 0.2.0        |
| yaml                            | 0.3.0        |
| psych                           | 5.1.2        |
| bigdecimal                      | 3.1.5        |
 </pre>
</details>

**Comment by Lacy54** [comment]
Thank you for sharing..
[Att My Results](https://attmyresults.cloud/)

**Comment by vase4kin** [comment]
Hi, I had the same issue. The culprit was the `verbose` parameter; set it to false, and it will work.

**Comment by iBotPeaches** [comment]
Closing as fixed back in https://github.com/fastlane/fastlane/pull/29495
