### ISSUE TITLE
Android Supply command fails with an error `rescue in load_key': \e[31m[!] Invalid keyfile or passphrase\e[0m (ArgumentError)

### ISSUE THREAD

**Issue by saifudheenvk** [fastlane/fastlane#29175]
### Issue Description
Android supply command fails with an error like this
[✔] 🚀 
[10:32:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:32:54]: Sending anonymous analytics information
[10:32:54]: Learn more at https://docs.fastlane.tools/#metrics
[10:32:54]: No personal or sensitive data is sent.
[10:32:54]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[10:32:54]: Using deprecated option: '--issuer' (Use `--json_key` instead)
[10:32:54]: DEPRECATED --issuer OPTION. Use --json_key instead
[10:32:54]: Using deprecated option: '--key' (Use `--json_key` instead)

+-------------------------------------------------------------------------------+
|                          Summary for supply 2.226.0                           |
+------------------------------------+------------------------------------------+
| aab                                | /home/circleci/project/store.aab         |
| version_name                       | 107.5.2                                  |
| package_name                       | com.innovatise.myfitappuk                |
| metadata_path                      | /home/circleci/project/metadata          |
| key                                | /home/circleci/project/key.p12           |
| timeout                            | 600                                      |
| root_url                           | https://androidpublisher.googleapis.com/ |
| release_status                     | completed                                |
| track                              | production                               |
| skip_upload_apk                    | false                                    |
| skip_upload_aab                    | false                                    |
| skip_upload_metadata               | false                                    |
| skip_upload_changelogs             | false                                    |
| skip_upload_images                 | false                                    |
| skip_upload_screenshots            | false                                    |
| sync_image_upload                  | false                                    |
| track_promote_release_status       | completed                                |
| validate_only                      | false                                    |
| check_superseded_tracks            | false                                    |
| deactivate_on_promote              | true                                     |
| changes_not_sent_for_review        | false                                    |
| rescue_changes_not_sent_for_review | true                                     |
| ack_bundle_installation_warning    | false                                    |
+------------------------------------+------------------------------------------+

[10:32:54]: This type of authentication is deprecated. Please consider using JSON authentication instead

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:89:in `rescue in load_key': \e[31m[!] Invalid keyfile or passphrase\e[0m (ArgumentError)
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:80:in `load_key'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:35:in `load_from_pkcs12'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/client.rb:126:in `service_account_authentication'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/client.rb:18:in `make_from_config'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/uploader.rb:463:in `client'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/uploader.rb:11:in `perform_upload'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/commands_generator.rb:40:in `block (2 levels) in run'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/commands_generator.rb:61:in `run'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/commands_generator.rb:13:in `start'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/bin/fastlane:23:in `<top (required)>'
        from /home/circleci/.rbenv/versions/3.1.0/bin/fastlane:25:in `load'
        from /home/circleci/.rbenv/versions/3.1.0/bin/fastlane:25:in `<main>'
/home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:36:in `initialize': PKCS12_parse: unsupported (OpenSSL::PKCS12::PKCS12Error)
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:36:in `new'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:36:in `block in load_from_pkcs12'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:87:in `load_key'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:35:in `load_from_pkcs12'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/client.rb:126:in `service_account_authentication'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/client.rb:18:in `make_from_config'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/uploader.rb:463:in `client'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/uploader.rb:11:in `perform_upload'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/commands_generator.rb:40:in `block (2 levels) in run'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/commands_generator.rb:61:in `run'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/supply/lib/supply/commands_generator.rb:13:in `start'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.226.0/bin/fastlane:23:in `<top (required)>'
        from /home/circleci/.rbenv/versions/3.1.0/bin/fastlane:25:in `load'
        from /home/circleci/.rbenv/versions/3.1.0/bin/fastlane:25:in `<main>

##### Command executed
            fastlane supply --aab "${STORE_BUNDLE}" --version_name "${VERSION_NO}" --package_name "${PACKAGE_NAME}" --metadata_path "${TEMP_DIR}/metadata" --issuer "${ACCOUNT_EMAIL}" --key "${TEMP_DIR}/key.p12" --timeout 600 --root_url "https://androidpublisher.googleapis.com/"

Upload is getting succeeded with JSON key file. But when i check the console it supports both p12 and JSON files

**Comment by saifudheenvk** [comment]
@joshdholtz any idea

**Comment by Parkert4** [comment]
Thanks for sharing, I am very impressed with your post.

**Comment by iBotPeaches** [comment]
Sorry it took us a bit to respond here. Using deprecated logic you'll naturally face more challenges. Your OpenSSL version is having issues parsing your key, which may have been a formatting issues

```
/home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:36:in `initialize': PKCS12_parse: unsupported (OpenSSL::PKCS12::PKCS12Error)
/home/circleci/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.11.3/lib/google/api_client/auth/key_utils.rb:89:in `rescue in load_key': \e[31m[!] Invalid keyfile or passphrase\e[0m (ArgumentError)

```

We cleaned up a lot of our key code to be a bit more lenient (strip spaces) since the newer OpenSSL versions were quite strict. Ultimately since this is crashing outside of fastlane (OpenSSL/Google layer). I'll close this out.
