### ISSUE TITLE
Support Ruby 3.4

### ISSUE THREAD

**Issue by mataku** [fastlane/fastlane#29183]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Ruby 3.4 has been released.
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/

According to standard gems change, fastlane raises error (LoadError, NameError, etc.)

I believe these are the tasks that need to be done

- [ ] Update gems which depend on Ruby 3.4.0 standard gems if an update exists
- [ ] Add Ruby 3.4 standard gems dependencies if needed
- [ ] Fix tests
- [ ] Add Ruby 3.4 to the CI matrix

##### Command executed
bundle exec fastlane android build_debug

```ruby
# Fastfile
platform :android do
  lane :build_debug do
    gradle(task: "assembleDebug")
  end
end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
$ bundle exec fastlane android build_debug
[⠋] 🚀 /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/helper.rb:1: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
/Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/httpclient-2.8.3/lib/httpclient/auth.rb:11: warning: mutex_m was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add mutex_m to your Gemfile or gemspec to silence this warning.
/Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/highline-2.0.3/lib/highline.rb:17: warning: abbrev was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add abbrev to your Gemfile or gemspec to silence this warning.
[⠙] 🚀 bundler: failed to load command: fastlane (/Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/bin/fastlane)
/Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane/lib/fastlane/cli_tools_distributor.rb:126:in 'Fastlane::CLIToolsDistributor.take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError)

        FastlaneCore::UpdateChecker.show_update_status('fastlane', Fastlane::VERSION)
                    ^^^^^^^^^^^^^^^
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/bin/fastlane:23:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/bin/fastlane:25:in 'Kernel#load'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/bin/fastlane:25:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in 'Kernel.load'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in 'Bundler::CLI::Exec#kernel_load'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in 'Bundler::CLI#exec'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in 'Bundler::Thor.dispatch'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/exe/bundle:28:in 'block in <top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/exe/bundle:20:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/bin/bundle:25:in 'Kernel#load'
        from /Users/mataku/.rbenv/versions/3.4.0/bin/bundle:25:in '<main>'
/Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'Kernel.require': cannot load such file -- abbrev (LoadError)
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/highline-2.0.3/lib/highline.rb:17:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/highline-2.0.3/lib/highline/import.rb:10:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/commander-4.6.0/lib/commander.rb:26:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/configuration/commander_generator.rb:1:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:4:in 'Kernel#require_relative'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:4:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:3:in 'Kernel#require_relative'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/android_package_name_guesser.rb:3:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:1:in 'Kernel#require_relative'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/analytics/app_identifier_guesser.rb:1:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/analytics/action_completion_context.rb:1:in 'Kernel#require_relative'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/analytics/action_completion_context.rb:1:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core.rb:6:in 'Kernel#require_relative'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core.rb:6:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane/lib/fastlane.rb:1:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/3.4.0+1/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane/lib/fastlane/cli_tools_distributor.rb:41:in 'Fastlane::CLIToolsDistributor.take_off'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/bin/fastlane:23:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/bin/fastlane:25:in 'Kernel#load'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/bin/fastlane:25:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in 'Kernel.load'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in 'Bundler::CLI::Exec#kernel_load'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in 'Bundler::CLI#exec'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in 'Bundler::Thor.dispatch'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/exe/bundle:28:in 'block in <top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
        from /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/bundler-2.5.22/exe/bundle:20:in '<top (required)>'
        from /Users/mataku/.rbenv/versions/3.4.0/bin/bundle:25:in 'Kernel#load'
        from /Users/mataku/.rbenv/versions/3.4.0/bin/bundle:25:in '<main>'

</pre>
</details>

### Environment

I use fastlane 2.226.0 and got error: `fastlane env`

<details>
  <pre>
fastlane env
[⠋] 🚀 /Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/helper.rb:1: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
/Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/httpclient-2.8.3/lib/httpclient/auth.rb:11: warning: mutex_m was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add mutex_m to your Gemfile or gemspec to silence this warning.
/Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/highline-2.0.3/lib/highline.rb:17: warning: abbrev was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add abbrev to your Gemfile or gemspec to silence this warning.
[⠙] 🚀 bundler: failed to load command: fastlane (/Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/bin/fastlane)
/Users/mataku/.rbenv/versions/3.4.0/lib/ruby/gems/3.4.0+1/gems/fastlane-2.226.0/fastlane/lib/fastlane/cli_tools_distributor.rb:126:in 'Fastlane::CLIToolsDistributor.take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError)

        FastlaneCore::UpdateChecker.show_update_status('fastlane', Fastlane::VERSION)
</pre>
</details>

**Comment by jshier** [comment]
Ruby 3.4 worked just fine for me one I added the gems that are no longer part of the standard library (including one that will be removed in Ruby 3.5).

```ruby
# Until Fastlane includes them directly.
gem "abbrev"
gem "mutex_m"
gem "ostruct"
```

**Comment by kapitoshka438** [comment]
As for the "abbrev" warning, I guess the fix is to upgrade the ["commander"](https://github.com/commander-rb/commander) gem to 5.0.0 which upgrades the ["highline"](https://github.com/JEG2/highline) gem to 3.x.x which removes "abbrev" as an unused dependency.

**Comment by ruairioliverwv** [comment]
I

> Ruby 3.4 worked just fine for me once I added the gems that are no longer part of the standard library (including one that will be removed in Ruby 3.5).
> 
> # Until Fastlane includes them directly.
> gem "abbrev"
> gem "mutex_m"
> gem "ostruct"

This worked for me but I also needed on ruby 3.4.1
gem "nkf"

**Comment by blimmer** [comment]
For me, I just needed to add

```
gem "abbrev"
```
