### ISSUE TITLE
Match adhoc Provisioning Profile on Apple Developer Enterprise Program

### ISSUE THREAD

**Issue by ecorreyu** [fastlane/fastlane#29187]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We have an apple account in both the ‘Apple Developer Enterprise Program’ and the ‘Apple Developer Program’.

Then, we have generated with fastlane an enterprise certificate (in Apple Developer Enterprise Program) and a distribution certificate (in Apple Developer Program) and we have hosted them in GitLab.

This created the folders with the certificates inside:

certs/distribution
certs/enterprise

Next, we want to create a provisioning profile in the enterprise program, using the enterprise certificate, but this does not work as expected.

For some reason fastlane is trying to use the public program instead of the enterprise program.

##### Command executed
fastlane match

##### Complete output when running fastlane, including the stack trace and command used
+-----------------------------------------------------------------------------------------------------------------------------+
|                                                  Summary for match 2.226.0                                                  |
+----------------------------------------+------------------------------------------------------------------------------------+
| type                                   | adhoc                                                                              |
| readonly                               | false                                                                              |
| generate_apple_certs                   | false                                                                              |
| skip_provisioning_profiles             | false                                                                              |
| app_identifier                         | ["es.mercadona.MdonaTestApp.ent.dev"]                                              |
| username                               | explotacionapps@mercadona.com                                                      |
| team_id                                | ENTERPRISE                                                                         |
| team_name                              | ENTERPRISE S.A.                                                                     |
| storage_mode                           | git                                                                                |
| git_url                                | https://gitlab.com/administracion-cicd/movilidad/apple/certificados  |
|                                        | .git                                                                               |
| git_branch                             | develop                                                                            |
| git_full_name                          | apps                                                                   |
| git_user_email                         | apps@apps.com                                                      |
| shallow_clone                          | false                                                                              |
| clone_branch_directly                  | true                                                                               |
| git_basic_authorization                | ********                                                                           |
| skip_google_cloud_account_confirmation | false                                                                              |
| s3_skip_encryption                     | false                                                                              |
| gitlab_host                            | https://gitlab.com                                                                 |
| keychain_name                          | login.keychain                                                                     |
| keychain_password                      | ********                                                                           |
| force                                  | true                                                                               |
| force_for_new_devices                  | false                                                                              |
| include_mac_in_profiles                | false                                                                              |
| include_all_certificates               | false                                                                              |
| force_for_new_certificates             | false                                                                              |
| skip_confirmation                      | false                                                                              |
| safe_remove_certs                      | false                                                                              |
| skip_docs                              | false                                                                              |
| platform                               | ios                                                                                |
| derive_catalyst_app_identifier         | false                                                                              |
| fail_on_name_taken                     | true                                                                               |
| skip_certificate_matching              | false                                                                              |
| skip_set_partition_list                | false                                                                              |
| force_legacy_encryption                | false                                                                              |
| verbose                                | true                                                                               |
+----------------------------------------+------------------------------------------------------------------------------------+

INFO [2024-12-30 14:16:55.68]: Cloning remote git repo...
INFO [2024-12-30 14:16:55.68]: $ git clone https://gitlab.gcp.mercadona.com/administracion-cicd/movilidad/apple/certificados.git /var/folders/tw/x3rbdf454d16ss6r6k1mdr980000gr/T/d20241230-25457-n7acre -c http.extraheader='Authorization: Basic xxxxxxxx' -b develop --single-branch
INFO [2024-12-30 14:16:55.72]: ▸ Cloning into '/var/folders/tw/x3rbdf454d16ss6r6k1mdr980000gr/T/d20241230-25457-n7acre'...
INFO [2024-12-30 14:16:57.78]: ▸ remote: Enumerating objects: 72594, done.
INFO [2024-12-30 14:16:57.82]: ▸ remote: Counting objects: 100% (42579/42579), done.
INFO [2024-12-30 14:16:57.84]: ▸ remote: Compressing objects: 100% (3832/3832), done.
INFO [2024-12-30 14:17:24.79]: ▸ remote: Total 72594 (delta 42332), reused 38747 (delta 38747), pack-reused 30015 (from 1)
INFO [2024-12-30 14:17:24.79]: ▸ Receiving objects: 100% (72594/72594), 184.09 MiB | 6.84 MiB/s, done.
INFO [2024-12-30 14:17:24.96]: ▸ Resolving deltas: 100% (42332/42332), done.
INFO [2024-12-30 14:17:25.03]: Add git user config to local git repo...
INFO [2024-12-30 14:17:25.03]: $ git config user.name "Explotación apps"
INFO [2024-12-30 14:17:25.05]: $ git config user.email "explotacionapps@mercadona.com"
INFO [2024-12-30 14:17:25.07]: $ git --no-pager branch --list origin/develop --no-color -r
INFO [2024-12-30 14:17:25.08]: ▸   origin/develop
INFO [2024-12-30 14:17:25.08]: Checking out branch develop...
INFO [2024-12-30 14:17:25.08]: $ git checkout develop
INFO [2024-12-30 14:17:25.12]: ▸ Already on 'develop'
INFO [2024-12-30 14:17:25.12]: ▸ Your branch is up to date with 'origin/develop'.
INFO [2024-12-30 14:17:25.13]: 🔓  Decrypted 'PUBLIC.cer'
INFO [2024-12-30 14:17:25.13]: 🔓  Decrypted 'PUBLIC.p12'
INFO [2024-12-30 14:17:25.13]: 🔓  Decrypted 'ENTERPRISE.cer'
INFO [2024-12-30 14:17:25.14]: 🔓  Decrypted 'ENTERPRISE.p12'
INFO [2024-12-30 14:17:26.27]: 🔓  Successfully decrypted certificates repo
INFO [2024-12-30 14:17:26.27]: Verifying that the certificate and profile are still valid on the Dev Portal...
Reading keychain entry, because either user or password were empty
Loading session from '/Users/ecorreyu/.fastlane/spaceship/explotacionapps@mercadona.com/cookie'
DEBUG [2024-12-30 14:17:28.36]: Your certificate 'PUBLIC.cer' is valid
INFO [2024-12-30 14:17:28.36]: Installing certificate...
INFO [2024-12-30 14:17:28.36]: $ security default-keychain -d user
INFO [2024-12-30 14:17:28.41]: ▸     "/Users/ecorreyu/Library/Keychains/login.keychain-db"
DEBUG [2024-12-30 14:17:28.52]: Certificate 'PUBLIC.cer' is already installed on this machine

+---------------------------------------------------------------------+
|                        Installed Certificate                        |
+-------------------+-------------------------------------------------+
| User ID           | PUBLIC                                      |
| Common Name       | Apple Distribution: PUBLIC S.A. (PUBLIC) |
| Organisation Unit | PUBLIC                                      |
| Organisation      | Public S.A.                                  |
| Country           | ES                                              |
| Start Datetime    | 2024-01-25 16:44:03 UTC                         |
| End Datetime      | 2025-01-24 16:44:02 UTC                         |
+-------------------+-------------------------------------------------+

ERROR [2024-12-30 14:17:28.80]: Certificate 'PUBLIC' (stored in your storage) is not available on the Developer Portal
ERROR [2024-12-30 14:17:28.80]: for the user apps@apps.com
ERROR [2024-12-30 14:17:28.80]: Make sure to use the same user and team every time you run 'match' for this
ERROR [2024-12-30 14:17:28.80]: Git repository. This might be caused by revoking the certificate on the Dev Portal
ERROR [2024-12-30 14:17:28.80]: If missing certificate is a Developer ID Installer, you may need to auth with Apple ID instead of App Store API Key
/Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] To reset the certificates of your Apple account, you can use the `fastlane match nuke` feature, more information on https://docs.fastlane.tools/actions/match/ (FastlaneCore::Interface::FastlaneError)
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/spaceship_ensure.rb:79:in `certificates_exists'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/runner.rb:102:in `run'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/commands_generator.rb:54:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/commands_generator.rb:186:in `run'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/commands_generator.rb:26:in `start'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `<main>'
/Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': To reset the certificates of your Apple account, you can use the `fastlane match nuke` feature, more information on https://docs.fastlane.tools/actions/match/ (FastlaneCore::Interface::FastlaneError)
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/spaceship_ensure.rb:79:in `certificates_exists'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/runner.rb:102:in `run'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/commands_generator.rb:54:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/commands_generator.rb:186:in `run'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/match/lib/match/commands_generator.rb:26:in `start'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /Users/ecorreyu/.local/share/fastlane/3.3.0/gems/fastlane-2.226.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane:25:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 15.2                                                       |
| Ruby                        | 3.3.6                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.39.5 (Apple Git-154)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.225.0/libexec/bin/fastlane |
| Host                        | macOS 15.2 (24C101)                                        |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.6/lib                        |
| OpenSSL Version             | OpenSSL 3.4.0 22 Oct 2024                                  |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 16.1                                                       |
| Swift Version               | 6.0.2                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :ios do
  desc "Refirma el ipa proporcionado con el certificado de distribución enterprise o con el certificado de distribución developer"
  lane :resign_ipa do
    resign_app_identifiers = ENV["RESIGN_APP_IDENTIFIERS"]
    if resign_app_identifiers
      app_identifiers = resign_app_identifiers.split(',')
      provisioning_profile = {}
      app_identifiers.each { |app_identifier|
        match
        provisioning_profile[app_identifier] = ENV["sigh_#{app_identifier}_#{ENV["MATCH_TYPE"]}_profile-path"]
      }
    else
      match
      resign_app_identifier = ENV["RESIGN_APP_IDENTIFIER"]
      provisioning_profile = ENV["sigh_#{resign_app_identifier}_#{ENV["MATCH_TYPE"]}_profile-path"]
    end
    resign(
      provisioning_profile: provisioning_profile
    )
  end
  lane :print_resign_app_identifiers do
    UI.message("The value of MATCH_TYPE is: #{ENV['MATCH_TYPE']}")
    UI.message("The value of RESIGN_APP_IDENTIFIERS is: #{ENV['RESIGN_APP_IDENTIFIERS']}")
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.226.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.6.0        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.1        |
| public_suffix                   | 6.0.1        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| babosa                          | 1.0.4        |
| base64                          | 0.2.0        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.112.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.4       |
| faraday_middleware              | 1.2.1        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.1        |
| sysrandom                       | 1.0.5        |
| fastlane-sirp                   | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.9.3        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.1        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.2.1       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| mini_magick                     | 4.13.2       |
| multipart-post                  | 2.4.1        |
| naturally                       | 2.2.1        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.6.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| rouge                           | 3.28.0       |
| xcpretty                        | 0.4.0        |
| set                             | 1.1.0        |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.10.1       |
| aws-partitions                  | 1.1025.0     |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.214.0      |
| aws-sdk-kms                     | 1.96.0       |
| aws-sdk-s3                      | 1.176.1      |
| bundler                         | 2.5.23       |
| rexml                           | 3.4.0        |
| nkf                             | 0.2.0        |
| faraday-multipart               | 1.1.0        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.8        |
| json                            | 2.9.1        |
| optparse                        | 0.6.0        |
| nanaimo                         | 0.4.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.27.0       |
| forwardable                     | 1.3.3        |
| logger                          | 1.6.0        |
| pathname                        | 0.3.0        |
| shellwords                      | 0.2.0        |
| cgi                             | 0.4.1        |
| date                            | 3.3.4        |
| timeout                         | 0.4.1        |
| stringio                        | 3.1.1        |
| securerandom                    | 0.3.1        |
| uri                             | 0.13.1       |
| ipaddr                          | 1.2.6        |
| openssl                         | 3.2.0        |
| digest                          | 3.1.1        |
| io-nonblock                     | 0.3.0        |
| zlib                            | 3.1.1        |
| resolv                          | 0.3.0        |
| io-wait                         | 0.3.1        |
| time                            | 0.3.0        |
| open-uri                        | 0.4.1        |
| mutex_m                         | 0.2.0        |
| net-http                        | 0.4.1        |
| net-protocol                    | 0.2.2        |
| english                         | 0.8.0        |
| erb                             | 4.0.3        |
| strscan                         | 3.0.9        |
| abbrev                          | 0.1.2        |
| io-console                      | 0.7.1        |
| tempfile                        | 0.2.1        |
| delegate                        | 0.3.1        |
| fileutils                       | 1.7.2        |
| tmpdir                          | 0.2.0        |
| singleton                       | 0.2.0        |
| open3                           | 0.2.1        |
| racc                            | 1.8.1        |
| nokogiri                        | 1.16.7       |
| prettyprint                     | 0.2.0        |
| pp                              | 0.5.0        |
| find                            | 0.2.0        |
| ostruct                         | 0.6.0        |
| yaml                            | 0.3.0        |
| psych                           | 5.1.2        |
</details>

*generated on:* **2024-12-30**
</details>

**Comment by Edward357Johnson** [comment]
Hello!
It seems like Fastlane is using the wrong certificate for your provisioning profile. Ensure that the enterprise certificate is correctly imported and recognized by Fastlane using fastlane match import. Set the correct keychain for the enterprise certificate with MATCH_KEYCHAIN_NAME. Check your Fastlane configuration files to ensure the enterprise certificate is correctly referenced. Make sure you're using the latest version of Fastlane.
