### ISSUE TITLE
match: "UnexpectedResponse" when trying to do initial "match development"

### ISSUE THREAD

**Issue by siburb** [fastlane/fastlane#3603]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Match gets a "UnexpectedResponse" when trying to run for the first time - we've tried "match development" & "match adhoc", both fail with the same message. "match init" was successful. We've setup a new Apple Developer account specifically for the purpose, and the account logs in to developer.apple.com successfully.

##### Complete output when running fastlane, including the stack trace and command used

```
SBB-MacBook-Pro:Rec.IT sbb.moko$ match development

+-----------------------+--------------------------------------------------------+
|                            Summary for match 0.3.0                             |
+-----------------------+--------------------------------------------------------+
| git_url               | https://bitbucket.org/mokosocialmedia/ios-provisioning |
| type                  | development                                            |
| username              | appledev+provisioning@mokosocialmedia.com              |
| app_identifier        | com.mokosocialmedia.Rec-IT                             |
| keychain_name         | login.keychain                                         |
| readonly              | false                                                  |
| verbose               | false                                                  |
| force                 | false                                                  |
| shallow_clone         | true                                                   |
| force_for_new_devices | false                                                  |
+-----------------------+--------------------------------------------------------+

[16:06:01]: Cloning remote git repo...
[16:06:05]: 🔓  Successfully decrypted certificates repo
[16:06:05]: Verifying that the certificate and profile are still valid on the Dev Portal...
[16:06:35]: 🔒  Successfully encrypted certificates repo
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '1e822fd87ae30905dc710fa8de80ef09'
The crash report has been stored locally '/tmp/sentry_1e822fd87ae30905dc710fa8de80ef09.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/client.rb:300:in `parse_response': [!] {"creationTimestamp"=>"2016-03-08T08:06:34Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestUrl"=>"https://developerservices2.apple.com:443/services/QH65B2/listTeams.action", "responseId"=>"2e7e4d98-2a3f-4b47-8b8f-8203df49d928"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/portal_client.rb:63:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/portal_client.rb:79:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/spaceship_ensure.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:11:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:52:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:108:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:116:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.37.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Bump build number, commit & push to remote"
  lane :incrementBuild do

    # Bump build number
    increment_build_number

    # Commit and push to remote
    commit_version_bump(
      message: 'Build number bump by fastlane - buildnumber lane',
      force: true
    )
    push_to_git_remote
  end

  desc "Deploy a new build via HockeyApp"
  lane :hockey do

    # Bump build number
    increment_build_number

    # Download and install the latest AdHoc profile
    sigh(
      adhoc: true,
      force: true,
      output_path: "./fastlane/provisioning"
    )

    # Set version number to the one at the top of the CHANGELOG
    readme = File.read("../CHANGELOG.md")
    latest_version = readme.split("\n## ").first
    first_line = latest_version.split("\n").first
    version_number = first_line.split(" ")[1]

    increment_version_number(
        version_number: version_number
    )

    # Generate release notes from CHANGELOG
    release_notes = latest_version.split("\n")[1..-1].join("\n")
    puts release_notes

    # Create the IPA file - save in Temp folder
    profileUDID = lane_context[SharedValues::SIGH_UDID]
    puts "Profile UUID: #{profileUDID}"
    gym(
      xcargs: "PROVISIONING_PROFILE=#{profileUDID}",
      scheme: "xxxxxxx",
      silent: true
    )

    # Deploy via HockeyApp
    markdown_type = '1'
    hockey(
      api_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
      notes_type: markdown_type,
      notes: release_notes
    )

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts

    # Commit and push to remote
    commit_version_bump(
      message: 'Build number bump by fastlane - hockey lane',
      force: true
    )
    push_to_git_remote
  end

  desc "Upload a new build to iTunesConnect"
  lane :itunes do

    # Bump build number
    increment_build_number

    # Make sure everything is committed
    ensure_git_status_clean

    # Download and install the latest App Store profile
    sigh(
      output_path: "~/Documents/Temp"
    )

    # Create the IPA file - save in Temp folder
    gym(
      scheme: 'xxxxxx',
      silent: true,
      output_directory: "~/Documents/Temp/"
    )

    # Just upload the build - do nothing else
    deliver(
      skip_screenshots: true,
      skip_metadata: true,
      automatic_release: false,
      submit_for_review: false
    )

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts

    # Commit and push to remote
    commit_version_bump(
      message: 'Build Version Bump by fastlane',
      force: true
    )
    push_to_git_remote
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end
end
```

Matchfile:

```ruby
git_url "https://bitbucket.org/mokosocialmedia/ios-provisioning"

type "development" # The default type, can be: appstore, adhoc or development

app_identifier "com.mokosocialmedia.Rec-IT" 
username "appledev+provisioning@mokosocialmedia.com" # Apple Developer Portal username

# For all available options run `match --help`
```

### Environment

fastlane version (fastlane -v): v1.66.0
Do you use bundler, rbenv or rvm? NO

**Comment by vpolouchkine** [comment]
What happens if you set `--team_name` for `match`?

**Comment by siburb** [comment]
Hi @vpolouchkine. I get the same results if I explicitly name the team, or give the team_id - see output from both tries below. I also tried adding the team_id into the AppFile, but no change:

```
SBB-MacBook-Pro:Rec.IT sbb.moko$ match -b "78V574KDRJ"

+-----------------------+--------------------------------------------------------+
|                            Summary for match 0.3.0                             |
+-----------------------+--------------------------------------------------------+
| team_id               | 78V574KDRJ                                             |
| git_url               | https://bitbucket.org/mokosocialmedia/ios-provisioning |
| type                  | development                                            |
| app_identifier        | com.mokosocialmedia.Rec-IT                             |
| username              | xxxxxxxxx@mokosocialmedia.com              |
| keychain_name         | login.keychain                                         |
| readonly              | false                                                  |
| verbose               | false                                                  |
| force                 | false                                                  |
| shallow_clone         | true                                                   |
| force_for_new_devices | false                                                  |
+-----------------------+--------------------------------------------------------+

[14:56:48]: Cloning remote git repo...
[14:56:53]: 🔓  Successfully decrypted certificates repo
[14:56:53]: Verifying that the certificate and profile are still valid on the Dev Portal...
[14:57:23]: 🔒  Successfully encrypted certificates repo
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'c3defd42bf31b7839729c2207690c8d8'
The crash report has been stored locally '/tmp/sentry_c3defd42bf31b7839729c2207690c8d8.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/client.rb:300:in `parse_response': [!] {"creationTimestamp"=>"2016-03-09T06:57:22Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestUrl"=>"https://developerservices2.apple.com:443/services/QH65B2/listTeams.action", "responseId"=>"8a087995-13e7-4160-9263-acf7d943aace"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/portal_client.rb:63:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/portal_client.rb:79:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/spaceship_ensure.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:11:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:108:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:116:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'
SBB-MacBook-Pro:Rec.IT sbb.moko$ match --team_name "Moko Social Media Limited"

+-----------------------+--------------------------------------------------------+
|                            Summary for match 0.3.0                             |
+-----------------------+--------------------------------------------------------+
| team_name             | Moko Social Media Limited                              |
| git_url               | https://bitbucket.org/mokosocialmedia/ios-provisioning |
| type                  | development                                            |
| app_identifier        | com.mokosocialmedia.Rec-IT                             |
| username              | xxxxxxxxxxx@mokosocialmedia.com              |
| keychain_name         | login.keychain                                         |
| readonly              | false                                                  |
| team_id               | 78V574KDRJ                                             |
| verbose               | false                                                  |
| force                 | false                                                  |
| shallow_clone         | true                                                   |
| force_for_new_devices | false                                                  |
+-----------------------+--------------------------------------------------------+

[15:09:45]: Cloning remote git repo...
[15:09:49]: 🔓  Successfully decrypted certificates repo
[15:09:49]: Verifying that the certificate and profile are still valid on the Dev Portal...
[15:10:17]: 🔒  Successfully encrypted certificates repo
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '6ce0720eb2fb86d391b3c5584565a32d'
The crash report has been stored locally '/tmp/sentry_6ce0720eb2fb86d391b3c5584565a32d.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/client.rb:300:in `parse_response': [!] {"creationTimestamp"=>"2016-03-09T07:10:16Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestUrl"=>"https://developerservices2.apple.com:443/services/QH65B2/listTeams.action", "responseId"=>"6cf042d1-75ff-41ec-91b8-8cd6402627ca"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/portal_client.rb:63:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/portal_client.rb:79:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/spaceship_ensure.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:11:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:108:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:116:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'
```

**Comment by asfalcone** [comment]
Same exception + stack trying to select teams as #3891

**Comment by siburb** [comment]
I think I've found the cause of this (at least in my particular case).

The email address used to login to Apple Developer console has a "+" in it e.g. "appledev+provisioning@".

I tried with a normal address without the +, and it worked fine. Perhaps it is an issue with the escaping of the "+" character in the email address?

**Comment by TKBurner** [comment]
Thanks for following up @siburb! Can you let me know if you are still seeing this issue if you update your tools? We pushed an update last night for password characters and it should impact your email as well. Let me know how it's going :+1:

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (454/400 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:60948 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKsk-002lQa-VH
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:15 +0200
Date: Sat, 18 Jun 2016 11:21:29 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274089;
	bh=mSFcZ8k5O33obeOf5uFOh+QlhdqKoRO95Z5wFyeJRhM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ua5mBVnqSkLQAs8b2VYw/VtYLQDXn7wadUkpRxEVQhlGRcaLKkE/Zbedc0XOFbfI8
	 OE51JPHtS9vwk/ocdLJvhYtKiM+NzIsTYT+E2Eey0J807BUwKduoHexoQ5kEwKI4fR
	 rJ6wNGMEWgRvljum2A5IXaWZuNaZlMNnleL9sXnQ=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (455/400 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:60971 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKsl-002lQe-1M
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:16 +0200
Date: Sat, 18 Jun 2016 11:21:29 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274089;
	bh=nTKqBGoG55ADUVYWU7Ud57XtutmTZTuoBPN1prkgajg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=bTwhAybFzwiesrO87qlUdGs7Wkd2Vk5iyLMEK0G1KjJXU49UywjK3xwxfSc/wnsVu
	 PLbYwcfxXuJXaAerk37oGCHPBpJGLikcpdcHB2e2Q/CQdhzAEE4M4Szu/NWiDJSZu7
	 QzRa2bS0tJsv4GgbCzzLvcdWZzAtLAOwsC2uNKF0=
