### ISSUE TITLE
ensure_no_debug_code causes ruby RuntimeError

### ISSUE THREAD

**Issue by StephanPartzsch** [fastlane/fastlane#3605]
### Issue Description
I am using the `ensure_no_debug_code` action in my Fastfile. Everything works fine so far. But if the action finds something an ruby error occurs. But the overall build succeeds.
I am neither sure if this is expected behaviour nor how to deal with the output in case of a find. Best case would be if the build will be marked as unstable... 

##### Complete output when running fastlane, including the stack trace and command used

```
09:39:55 [09:39:55]: ----------------------------------
09:39:55 [09:39:55]: --- Step: ensure_no_debug_code ---
09:39:55 [09:39:55]: ----------------------------------
09:39:55 [09:39:55]: grep -R '// TODO' '/Users/jenkins/.jenkins/jobs/my_project__snapshot/workspace/myProject/Application'
09:39:55 [09:39:55]: Variable Dump:
09:39:55 [09:39:55]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios metrics"}
09:39:55 [09:39:55]: Found debug code '// TODO': 
09:39:55 
09:39:55 /Users/jenkins/.jenkins/jobs/my_project__snapshot/workspace/myProject/Application/Controller/Bookmarks/BookmarksManager.m:		// TODO: delete this
09:39:55 
09:39:55 +------+-------------------------------------+-------------+
09:39:55 |                     fastlane summary                     |
09:39:55 +------+-------------------------------------+-------------+
09:39:55 | Step | Action                              | Time (in s) |
09:39:55 +------+-------------------------------------+-------------+
09:39:55 | 1    | opt_out_usage                       | 0           |
09:39:55 | 2    | skip_docs                           | 0           |
09:39:55 | 3    | Verifying required fastlane version | 0           |
09:39:55 | 4    | default_platform                    | 0           |
09:39:55 | 5    | slather                             | 8           |
09:39:55 | 6    | cloc                                | 1           |
09:39:55 | 7    | ensure_no_debug_code                | 0           |
09:39:55 +------+-------------------------------------+-------------+
09:39:55 
09:39:55 [09:39:55]: fastlane finished with errors
09:39:55 -------------------------------------------------------------------------------------------
09:39:55 😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
09:39:55 👍  This makes resolving issues much easier and helps improve fastlane.
09:39:55 🔒  The reports will be stored securely on getsentry.com.
09:39:55 🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
09:39:55 -------------------------------------------------------------------------------------------
09:39:55 /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/actions/ensure_no_debug_code.rb:27:in `run': [!] Found debug code '// TODO':  (RuntimeError)
09:39:55 
09:39:55 /Users/jenkins/.jenkins/jobs/my_project__snapshot/workspace/myProject/Application/Controller/Bookmarks/BookmarksManager.m:		// TODO: delete this
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:129:in `block in execute_action'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `chdir'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `execute_action'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:149:in `method_missing'
09:39:55 	from Fastfile:58:in `block (2 levels) in parsing_binding'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:52:in `block in execute'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `chdir'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `execute'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/command_line_handler.rb:30:in `handle'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/bin/fastlane:38:in `block (2 levels) in run'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/bin/fastlane:156:in `run'
09:39:55 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/bin/fastlane:162:in `<top (required)>'
09:39:55 	from /usr/local/bin/fastlane:23:in `load'
09:39:55 	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Fastfile:
```ruby
skip_docs
fastlane_version "1.66.0"

default_platform :ios

platform :ios do


  # ----------------------------------------------------------------------------
  # GENERAL
  # ----------------------------------------------------------------------------

  before_all do
    # pod update
    # increment_build_number
  end


  # ----------------------------------------------------------------------------
  # PREPARE
  # ----------------------------------------------------------------------------

  desc "Checks Xcode and cleans derived data"
  lane :prepare do
    clear_derived_data
    verify_xcode
  end


  # ----------------------------------------------------------------------------
  # TEST
  # ----------------------------------------------------------------------------

  desc "Runs all the tests"
  lane :test do
    clear_derived_data
    scan(
      scheme: 'MyScheme',
      configuration: 'Debug',
      code_coverage: true,
      clean: true)
  end

  desc "Runs code metrics"
  lane :metrics do
    slather(
        proj: "myProject.xcodeproj",
        scheme: "MyScheme",
        input_format: "profdata",
        ignore: "../**/*/Xcode*",
        cobertura_xml: true,
        output_directory: "fastlane/code_coverage"
    )

    cloc(source_directory: 'my/Application', output_directory: 'fastlane/line_count', )

    ensure_no_debug_code(
        text: "// TODO",
        path: "./my/Application"
    )

    ensure_no_debug_code(
        text: "NSLog",
        path: "./myClient/Application"
    )
  end
```

### Environment

fastlane version (fastlane -v): 1.66.0
Do you use bundler, rbenv or rvm? No

**Comment by KrauseFx** [comment]
That's because you have `// TODO` in your source code:

```
09:39:55 [09:39:55]: Found debug code '// TODO': /Users/jenkins/.jenkins/jobs/my_project__snapshot/workspace/myProject/Application/Controller/Bookmarks/BookmarksManager.m:     // TODO: delete this
```

**Comment by StephanPartzsch** [comment]
Sure, I searched for the '// TODO'.
But why does this result in a runtime error? 

09:39:55 [09:39:55]: fastlane finished with errors

09:39:55 /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/actions/ensure_no_debug_code.rb:27:in `run': [!] Found debug code '// TODO':  (**RuntimeError**)

**Comment by KrauseFx** [comment]
@StephanPartzsch That just means fastlane has failed. Do you expect a different error class? I agree it's not beautiful to show the full stack trace. We're actually working on migrating the remaining fastlane actions to the new UI layer

**Comment by StephanPartzsch** [comment]
@KrauseFx Ahh, ok. Thought this is an unexpected error in fastlane because I says sth about crash reports. Maybe it will be a bit more clear if a different error class is used... At the moment it is not too self-explaining.
Besides this, great work! Looking forward to updates and improvements :)
