### ISSUE TITLE
Supply failed init option with error: applicationNotFound

### ISSUE THREAD

**Issue by krismort** [fastlane/fastlane#3628]
### Issue Description

I have tried getting supply to upload an android build/apk to google play but i get this error when supply is being run with init.  

##### Complete output when running fastlane, including the stack trace and command used
```
TEMP-DU-EL11-6:a53fcdb18986a3f5 admin$ /Library/android-sdk-macosx/build-tools/21.1.1/aapt dump badging android.apk | grep package:\ name
package: name='com.tastybits.testteamcity' versionCode='1' versionName='1.0' platformBuildVersionName='5.0.1-1624448'
TEMP-DU-EL11-6:a53fcdb18986a3f5 admin$ supply init --json_key ~/Dropbox/gplaydev.json
[02:01:33]: Fetching a new access token from Google...
[02:01:34]: To not be asked about this value, you can specify it using 'package_name'
The package name of the Application to modify: com.tastybits.testteamcity
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:202:in `check_status': [!] applicationNotFound: No application was found for the given package name. (Google::Apis::ClientError)
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/api_command.rb:103:in `check_status'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:170:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:275:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:96:in `execute'
```

### Environment

supply-0.5.2

**Comment by asfalcone** [comment]
@krismort It seems like there is no app with the package "com.tastybits.testteamcity" (Error from google API is: No application was found for the given package name). Can you confirm that that app exists in Google play already and that the account you're using for auth has access to it?

**Comment by krismort** [comment]
Isn't the first build what defines the package value when uploaded ?  I created an app but i cannot find a place in the google developer console where you can define a value like the packagename. I can try and upload one manually and see if that's the case.

**Comment by asfalcone** [comment]
`supply init` downloads existing metadata for an app. 

`supply` will upload new metadata for an app (or a new apk for an existing app), but cannot upload a brand new app due to Google API limitations. 

So you'll have to create the app in Google Developer Console first, then you can automate making updates to it (new builds, new metadata). Hope this helps!

**Comment by krismort** [comment]
Thanks, do you know if anyone has created a tool for automation of app creation and uploading the first app via  a headless browser or some homebrewn library like spaceship ?

**Comment by asfalcone** [comment]
I don't know of anything, but if you find a way let us know! 🚀
