### ISSUE TITLE
frameit: undefined method `find' for nil:NilClass

### ISSUE THREAD

**Issue by SpacyRicochet** [fastlane/fastlane#3644]
When trying to frame some single screenshots with frameit, each screenshot gives me the following error;

```
undefined method `find' for nil:NilClass
```

This looks like something @philipengberg mentioned in #1739, though I'm unsure if he solved it. Uninstalling and installing `imagemagick` didn't help either.

Deleting the `Framefile.json` does work, resulting in framed screenshots without a border. So I guess something is wrong in that file, but I can't figure out what.

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
➜  screenshots git:(feature/snapshotting) ✗ frameit silver
[17:52:14]: undefined method `find' for nil:NilClass
[17:52:14]: Unfortunately 3.5" device frames were discontinued. Skipping screen './en-US/iPhone4s-1Main.png'
[17:52:14]: Looked for: 'iPhone_4_Vert_Slvr.png'
[17:52:14]: undefined method `find' for nil:NilClass
[17:52:14]: undefined method `find' for nil:NilClass
[17:52:14]: undefined method `find' for nil:NilClass
[17:52:14]: undefined method `find' for nil:NilClass
[17:52:14]: Unfortunately 3.5" device frames were discontinued. Skipping screen './nl-NL/iPhone4s-1Main.png'
[17:52:14]: Looked for: 'iPhone_4_Vert_Slvr.png'
[17:52:14]: undefined method `find' for nil:NilClass
[17:52:14]: undefined method `find' for nil:NilClass
[17:52:14]: undefined method `find' for nil:NilClass
[17:52:14]: undefined method `find' for nil:NilClass
```

Verbose output of one failure

```
INFO [2016-03-09 17:48:59.12]: Parsing config file '/Users/brunoscheele/Projects/feedme/fastlane/screenshots/Framefile.json'
ERROR [2016-03-09 17:48:59.12]: undefined method `find' for nil:NilClass
ERROR [2016-03-09 17:48:59.12]: Backtrace:
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/lib/frameit/config_parser.rb:25:in `fetch_value'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/lib/frameit/editor.rb:267:in `fetch_config'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/lib/frameit/editor.rb:83:in `should_add_title?'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/lib/frameit/editor.rb:16:in `frame!'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/lib/frameit/screenshot.rb:76:in `frame!'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/lib/frameit/runner.rb:29:in `block in run'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/lib/frameit/runner.rb:21:in `each'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/lib/frameit/runner.rb:21:in `run'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/bin/frameit:39:in `block (2 levels) in run'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/bin/frameit:54:in `run'
	/Users/brunoscheele/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/frameit-2.5.1/bin/frameit:61:in `<top (required)>'
	/Users/brunoscheele/.rbenv/versions/2.2.3/bin/frameit:23:in `load'
	/Users/brunoscheele/.rbenv/versions/2.2.3/bin/frameit:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Framefile.json:
```json
{
  "default": {
    "keyword": {
      "font": "./fonts/GillSans.ttc",
      "color": "#FFFFFF"
    },
    "title": {
      "font": "./fonts/GillSans.ttc",
      "color": "#FFFFFF"
    },
    "background": "./background.jpg",
    "padding": 50
  }
}
```

### Environment

fastlane 1.66.0
rbenv

**Comment by i2amsam** [comment]
@SpacyRicochet your `Framefile` needs a `data` section, similar to the one [listed here](https://github.com/fastlane/fastlane/tree/master/frameit#framefilejson), here's the [crashing line](https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/config_parser.rb#L25).  :boom:
