### ISSUE TITLE
Snapshot on Xcode Server

### ISSUE THREAD

**Issue by reallyseth** [fastlane/fastlane#3646]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to run snapshot on an Xcode build server. It seems to run fine on my local machine, but when I run snapshot on the build server under the _xcsbuildd user, I get this output:

##### Complete output when running fastlane, including the stack trace and command used

```
home:code _xcsbuildd$ snapshot
[11:02:48]: xcrun xcodebuild -list -project './DashingDish.xcodeproj'
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/snapshot-1.11.1/lib/snapshot/runner.rb:232:in `match': [!] invalid byte sequence in US-ASCII (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.11.1/lib/snapshot/runner.rb:232:in `match'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.11.1/lib/snapshot/runner.rb:232:in `version_of_bundled_helper'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.11.1/lib/snapshot/runner.rb:240:in `verify_helper_is_current'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.11.1/lib/snapshot/runner.rb:23:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.11.1/bin/snapshot:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.11.1/bin/snapshot:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.11.1/bin/snapshot:84:in `<top (required)>'
	from /usr/local/bin/snapshot:23:in `load'
	from /usr/local/bin/snapshot:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile:
```ruby
# A list of devices you want to take the screenshots from
 devices([
   "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 5",
   "iPhone 4s"
 ])

languages([
  "en-US"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snaps\
hot#launch-arguments
launch_arguments(["-TestEmail email@email.com -TestPassword xxxxxxxxx"])

reinstall_app true

# The name of the scheme which contains the UI Tests
# scheme "SchemeName"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously genera\
ted screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help
```

### Environment

fastlane version (fastlane -v): 1.66.0
snapshot version: 1.11.1

**Comment by reallyseth** [comment]
Solved the issue with the suggestion here: 

https://github.com/fastlane/fastlane/issues/2573
