### ISSUE TITLE
[Transporter Error Output]: ERROR : "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format ."

### ISSUE THREAD

**Issue by rndcmo** [fastlane/fastlane#3657]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Pilot upload to the app store fails to upload due to error in icon.

##### Complete output when running fastlane, including the stack trace and command used

```
[10:58:36]: Successfully exported and compressed dSYM file
[10:58:36]: Successfully exported and signed the ipa file:
[10:58:36]: /Users/<currentUser>/Source/iOS/develop/iPhone/artifacts/<myApplication>Release.ipa
[10:58:36]: -------------------
[10:58:36]: --- Step: pilot ---
[10:58:36]: -------------------
[10:58:36]: Login to iTunes Connect (<myApplication>@<myDomain>)
[10:58:38]: Login successful
[10:58:39]: Ready to upload new build to TestFlight (App: <app_ID>)...
[10:58:39]: Going to upload updated app to iTunes Connect
[10:58:39]: This might take a few minutes, please don't interrupt the script
[10:58:42]: [Transporter]: INFO: Transporter is searching for updated software components.
[10:58:43]: [Transporter]: INFO: Transporter is up-to-date.
[10:58:43]: [Transporter]: INFO: Logging configured successfully.
[10:58:43]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
[10:58:43]: [Transporter]: DEBUG: Configuration refresh successful.
[10:58:43]: [Transporter]: DEBUG: Saving configuration to local path: /Users/<currentUser>/.itmstransporter/Defaults.properties
[10:58:43]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.8.8]
[10:58:43]: [Transporter]: INFO: OS identifier: Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[10:58:43]: [Transporter]: INFO: Memory: [JVM] 853M free, 982M total, 982M max [System] (Physical) 71M free, 16384M total (Swap) 971M free, 1024M total
[10:58:43]: [Transporter]: INFO: Upload mode selected.
[10:58:43]: [Transporter]: INFO: Examining the package at: /tmp/335023774.itmsp
[10:58:43]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
[10:58:43]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
[10:58:43]: [Transporter]: INFO: Gathering the list of valid files from the package ...
[10:58:43]: [Transporter]: DEBUG:   8bb85dd8ba9f50d6f14050f530d3436c.ipa will be verified by Apple's web service to determine if it is a valid file.
[10:58:43]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
[10:58:43]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
[10:58:43]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
[10:58:43]: [Transporter]: INFO: Performing authentication of package 335023774.itmsp ...
[10:58:43]: [Transporter]: DBG-X: Memory: [JVM] 843M free, 982M total, 982M max [System] (Physical) 93M free, 16384M total (Swap) 971M free, 1024M total
[10:58:43]: [Transporter]: DBG-X: Memory: [JVM] 843M free, 982M total, 982M max [System] (Physical) 93M free, 16384M total (Swap) 971M free, 1024M total
[10:58:43]: [Transporter]: DBG-X: Using operation named: authenticateForSession
[10:58:43]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[10:58:43]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[10:58:43]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[10:58:43]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[10:58:43]: [Transporter]: DBG-X:   parameter Password = **hidden value**
[10:58:43]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u <myApplication>@<myDomain> -p **hidden value** -f /tmp/335023774.itmsp -t DAV -t Signiant -k 100000
[10:58:43]: [Transporter]: DBG-X:   parameter Username = <myApplication>@<myDomain>
[10:58:43]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[10:58:43]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[10:58:43]: [Transporter]: INFO: id = 20160309105843-039
[10:58:43]: [Transporter]: DBG-X: Apple's web service operation return value:
[10:58:43]: [Transporter]: DBG-X:   parameter SessionId = CIOnDBIQb8pEfpH7Qae2Vzv6zJBkPw==
[10:58:43]: [Transporter]: DBG-X:   parameter SharedSecret = <shared_Secret>
[10:58:43]: [Transporter]: DBG-X: Deflated 451 bytes to 392
[10:58:43]: [Transporter]: DBG-X: Using operation named: validateMetadata
[10:58:43]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[10:58:43]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[10:58:43]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[10:58:43]: [Transporter]: DBG-X:   parameter Files = [8bb85dd8ba9f50d6f14050f530d3436c.ipa, metadata.xml]
[10:58:43]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
[10:58:43]: [Transporter]: DBG-X:   parameter MetadataChecksum = 4dd938f640fbd7177a692960b10e346c
[10:58:43]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
[10:58:43]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[10:58:43]: [Transporter]: DBG-X:   parameter PackageName = 335023774.itmsp
[10:58:43]: [Transporter]: DBG-X:   parameter PackageSize = 75428457
[10:58:43]: [Transporter]: DBG-X:   parameter Throttle = 100000
[10:58:43]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u <myApplication>@<myDomain> -p **hidden value** -f /tmp/335023774.itmsp -t DAV -t Signiant -k 100000
[10:58:43]: [Transporter]: DBG-X:   parameter Username = <myApplication>@<myDomain>
[10:58:43]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[10:58:43]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[10:58:43]: [Transporter]: INFO: id = 20160309105843-022
[10:58:44]: [Transporter]: DBG-X: Apple's web service operation return value:
[10:58:44]: [Transporter]: DBG-X:   parameter CPUToken = bf347532-47b8-488a-b394-3e9751ebf70a/1457549924228
[10:58:44]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=8bb85dd8ba9f50d6f14050f530d3436c.ipa}]
[10:58:44]: [Transporter]: DBG-X:   parameter FileSizes = {8bb85dd8ba9f50d6f14050f530d3436c.ipa=75428006}
[10:58:44]: [Transporter]: DBG-X:   parameter Checksums = {8bb85dd8ba9f50d6f14050f530d3436c.ipa=d5ba4ea997e6c9defc689bf0d356e98d}
[10:58:44]: [Transporter]: DBG-X:   parameter Success = true
[10:58:44]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, 8bb85dd8ba9f50d6f14050f530d3436c.ipa]
[10:58:44]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[10:58:44]: [Transporter]: DBG-X:   parameter ProviderNameForToken = <myCompany>
[10:58:44]: [Transporter]: INFO: The list of files requested for upload by Apple is: [metadata.xml, 8bb85dd8ba9f50d6f14050f530d3436c.ipa].  These are the files that will be uploaded.
[10:58:44]: [Transporter]: INFO: Starting media analysis of assets
[10:58:44]: [Transporter]: DEBUG: Handling asset: filename=8bb85dd8ba9f50d6f14050f530d3436c.ipa,uti=com.apple.ipa,role=source,describe=true
[10:58:44]: [Transporter]: DEBUG: Using container type tool name and version: iOS App Describer:1.24
[10:58:44]: [Transporter]: DEBUG: Using path: /tmp/335023774.itmsp/8bb85dd8ba9f50d6f14050f530d3436c.ipa
[10:59:06]: [Transporter]: DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@60cb7730
[10:59:06]: [Transporter]: DBG-X: Deflated 3836461 bytes to 507360
[10:59:06]: [Transporter]: INFO: Asset media analysis has completed
[10:59:06]: [Transporter]: DBG-X: Memory: [JVM] 901M free, 982M total, 982M max [System] (Physical) 213M free, 16384M total (Swap) 971M free, 1024M total
[10:59:06]: [Transporter]: DBG-X: Using operation named: lookupTransportDiagnostic
[10:59:06]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[10:59:06]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[10:59:06]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[10:59:06]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[10:59:06]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u <myApplication>@<myDomain> -p **hidden value** -f /tmp/335023774.itmsp -t DAV -t Signiant -k 100000
[10:59:06]: [Transporter]: DBG-X:   parameter Username = <myApplication>@<myDomain>
[10:59:06]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[10:59:06]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[10:59:06]: [Transporter]: INFO: id = 20160309105906-862
[10:59:07]: [Transporter]: DBG-X: Apple's web service operation return value:
[10:59:07]: [Transporter]: DBG-X:   parameter SigniantLoggingLevel = OFF
[10:59:07]: [Transporter]: DBG-X:   parameter AsperaLoggingLevel = OFF
[10:59:08]: [Transporter]: DBG-X: WebDAV status: 401
[10:59:08]: [Transporter]: DEBUG: Using token file path /Users/<currentUser>/.itmstransporter/UploadTokens/<currentUser>.local_Concur_335023774.itmsp.token
[10:59:08]: [Transporter]: DEBUG: Attempting exclusive file lock on token file
[10:59:08]: [Transporter]: DEBUG: Token exists, examining
[10:59:08]: [Transporter]: DEBUG: Token pid: 47940, found process = false; my pid: 68702
[10:59:08]: [Transporter]: DEBUG: Reusing existing token: 633fd573-4c89-4c0a-b666-4422b595eff1/1455135267339
[10:59:08]: [Transporter]: DEBUG: Set token: 633fd573-4c89-4c0a-b666-4422b595eff1/1455135267339
[10:59:08]: [Transporter]: DBG-X: Memory: [JVM] 895M free, 982M total, 982M max [System] (Physical) 213M free, 16384M total (Swap) 971M free, 1024M total
[10:59:08]: [Transporter]: DBG-X: Deflated 451 bytes to 392
[10:59:08]: [Transporter]: DBG-X: Using operation named: validateAssets
[10:59:08]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[10:59:08]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[10:59:08]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[10:59:08]: [Transporter]: DBG-X:   parameter CPUToken = 633fd573-4c89-4c0a-b666-4422b595eff1/1455135267339
[10:59:08]: [Transporter]: DBG-X:   parameter Files = [8bb85dd8ba9f50d6f14050f530d3436c.ipa, metadata.xml]
[10:59:08]: [Transporter]: DBG-X:   parameter MetadataChecksum = 4dd938f640fbd7177a692960b10e346c
[10:59:08]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
[10:59:08]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[10:59:08]: [Transporter]: DBG-X:   parameter PackageName = 335023774.itmsp
[10:59:08]: [Transporter]: DBG-X:   parameter PackageSize = 75428457
[10:59:08]: [Transporter]: DBG-X:   parameter Throttle = 100000
[10:59:08]: [Transporter]: DBG-X:   parameter Transport = DAV
[10:59:08]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u <myApplication>@<myDomain> -p **hidden value** -f /tmp/335023774.itmsp -t DAV -t Signiant -k 100000
[10:59:08]: [Transporter]: DBG-X:   parameter Username = <myApplication>@<myDomain>
[10:59:08]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[10:59:08]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[10:59:08]: [Transporter]: INFO: id = 20160309105908-677
[10:59:17]: [Transporter]: DBG-X: Apple's web service operation return value:
[10:59:17]: [Transporter]: DBG-X:   parameter ErrorMessage = ERROR : "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format .
[10:59:17]: [Transporter]: DBG-X:   parameter CPUToken = 633fd573-4c89-4c0a-b666-4422b595eff1/1455135267339
[10:59:17]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=8bb85dd8ba9f50d6f14050f530d3436c.ipa}]
[10:59:17]: [Transporter]: DBG-X:   parameter FileSizes = {8bb85dd8ba9f50d6f14050f530d3436c.ipa=75428006}
[10:59:17]: [Transporter]: DBG-X:   parameter Checksums = {8bb85dd8ba9f50d6f14050f530d3436c.ipa=d5ba4ea997e6c9defc689bf0d356e98d}
[10:59:17]: [Transporter]: DBG-X:   parameter Errors = [ERROR : "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format ."]
[10:59:17]: [Transporter]: DBG-X:   parameter ErrorCode = 1102
[10:59:17]: [Transporter]: DBG-X:   parameter Success = false
[10:59:17]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, 8bb85dd8ba9f50d6f14050f530d3436c.ipa]
[10:59:17]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
[10:59:17]: [Transporter Error Output]: ERROR : "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format ."
[10:59:17]: [Transporter]: DBG-X: The error code is: 1102
[10:59:17]: [Transporter]: INFO: Done performing authentication.
[10:59:17]: Transporter transfer failed.
[10:59:17]: 
[10:59:17]: ERROR : "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format ."
[10:59:17]: Return status of iTunes Transporter was 1: ERROR : "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format ."
[10:59:17]: ERROR : "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format ."
Return status of iTunes Transporter was 1: ERROR : "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format ."
[10:59:17]: Could not download/upload from iTunes Connect! It's probably related to your password or your internet connection.
[10:59:17]: Variable Dump:
[10:59:17]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios release", :SIGH_PROFILE_PATH=>"/Users/<currentUser>/Source/iOS/develop/iPhone/AppStore_com.<myCompany>.<myApplication>.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/<currentUser>/Source/iOS/develop/iPhone/AppStore_com.<myCompany>.<myApplication>.mobileprovision"], :SIGH_UDID=>"<my_UDID>", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/<currentUser>/Source/iOS/develop/iPhone/artifacts/<myApplication>Release.ipa", :DSYM_OUTPUT_PATH=>"/Users/<currentUser>/Source/iOS/develop/iPhone/artifacts/<myApplication>Release.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/<currentUser>/Library/Developer/Xcode/Archives/2016-03-09/<myApplication>Release 2016-03-09 10.50.02.xcarchive"}
[10:59:17]: Error uploading ipa file, more information see above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 35          |
| 4    | sigh                                | 6           |
| 5    | gym                                 | 525         |
| 6    | pilot                               | 41          |
+------+-------------------------------------+-------------+

[10:59:17]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '21dedb3240442524f10acf4d3d23a3a4'
The crash report has been stored locally '/tmp/sentry_21dedb3240442524f10acf4d3d23a3a4.json'
/usr/local/rvm/gems/ruby-2.2.0@<myApplication>/gems/pilot-1.4.1/lib/pilot/build_manager.rb:31:in `upload': [!] Error uploading ipa file, more information see above (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `chdir'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:42:in `block (2 levels) in parsing_binding'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/bin/fastlane:38:in `block (2 levels) in run'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/bin/fastlane:156:in `run'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/fastlane-1.66.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `load'
	from /usr/local/rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.0@<myApplication>/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.0@<myApplication>/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.48.0"

default_platform :ios

platform :ios do
before_all do

    cocoapods(podfile: "../Podfile")
#    DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"
# Run the pre-run scipt
# sh ./fastlane/prerun.sh
# ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
# increment_build_number
# xctool # run the tests of your app
end

desc "Submit a new <my_company> Mobile Release Build to Apple TestFlight"
desc "This will also make sure the profile is up to date"
lane :release do

sigh(app_identifier: "com.<my_company>.<my_company>mobile", username: "<my_company>mobile@<my_company>.com", team_id: "<my_teamID>")
ENV["MAIN_APP_PROFILE"]=lane_context[SharedValues::SIGH_UDID]

gym(clean: true, workspace: "<my_company>Mobile.xcworkspace", scheme: "<my_company>Mobile", configuration: "Release", output_name: "<my_company>MobileRelease", output_directory: "./artifacts", include_symbols: true, use_legacy_build_api: true) # Build your app - more options available
pilot(skip_submission:true)

desc "Submit a new <my_company> Mobile Enterprise build"
desc "This will also make sure the profile is up to date"
lane :enterprise do

sigh(app_identifier: "com.<my_company>.<my_company>mobile.enterprise", username: "<my_company>enterprise@<my_company>.com", team_id: "<my_teamID>")
ENV["MAIN_APP_PROFILE"]=lane_context[SharedValues::SIGH_UDID]

gym(clean: true, workspace: "<my_company>Mobile.xcworkspace", scheme: "<my_company>Mobile Enterprise", configuration: "Distribution", output_name: "<my_company>MobileEnterprise", output_directory: "./artifacts", include_symbols: true, use_legacy_build_api: true) # Build your app - more options available
end


desc "Create a Developer <my_company> Mobile Enterprise Build"
desc "This will also make sure the profile is up to date"
lane :dev_enterprise do

sigh(app_identifier: "com.<my_company>.<my_company>mobile.develop", username: "<my_company>mobile@<my_company>.com", team_id: "<my_teamID>")
ENV["MAIN_APP_PROFILE"]=lane_context[SharedValues::SIGH_UDID]

gym(clean: true, workspace: "<my_company>Mobile.xcworkspace", scheme: "<my_company>Mobile Enterprise", configuration: "Distribution", output_name: "<my_company>MobileEnterprise", output_directory: "./artifacts", include_symbols: true, use_legacy_build_api: true) # Build your app - more options available
end


desc "Create a new <my_company> Mobile Device Build"
desc "This will also make sure the profile is up to date"
lane :device do

sigh(app_identifier: "com.<my_company>.<my_company>mobile", username: "<my_company>mobile@<my_company>.com", team_id: "<my_teamID>")
ENV["MAIN_APP_PROFILE"]=lane_context[SharedValues::SIGH_UDID]

gym(clean: true, workspace: "<my_company>Mobile.xcworkspace", scheme: "<my_company>Mobile", configuration: "Debug", output_name: "<my_company>MobileDevice", output_directory: "./artifacts", include_symbols: true, use_legacy_build_api: true) # Build your app - more options available
end


desc "Create a new <my_company>Mobile Simulator Build"
desc "This will also make sure the profile is up to date"
lane :simulator do

sigh(app_identifier: "com.<my_company>.<my_company>mobile", username: "<my_company>mobile@<my_company>.com", team_id: "<my_teamID>")
ENV["MAIN_APP_PROFILE"]=lane_context[SharedValues::SIGH_UDID]

gym(clean: true,workspace: "<my_company>Mobile.xcworkspace", scheme: "<my_company>Mobile", configuration: "Debug", output_name: "<my_company>MobileSimulator", output_directory: "./artifacts", include_symbols: true, use_legacy_build_api: true, sdk: "iphonesimulator") # Build your app - more options available
end

desc "Create a new <my_company>Mobile Adhoc Build"
desc "This will also make sure the profile is up to date"
lane :adhoc do

  sigh(app_identifier: "com.<my_company>.<my_company>mobile", username: "<my_company>mobile@<my_company>.com", team_id: "<my_teamID>")
  ENV["MAIN_APP_PROFILE"]=lane_context[SharedValues::SIGH_UDID]

  gym(clean: true,workspace: "<my_company>Mobile.xcworkspace", scheme: "<my_company>Mobile", configuration: "Distribution", export_method: "ad-hoc", output_directory: "./artifacts", output_name: "<my_company>MobileAdhoc", include_symbols: true, use_legacy_build_api: true) # Build your app - more options available

  # sh "your_script.sh"
  # You can also use other beta testing services here
end

after_all do |lane|
# This block is called, only if the executed lane was successful
# slack(
#   message: "Successfully deployed new App Update."
# )
end


error do |lane, exception|
# slack(
#   message: exception.message,
#   success: false
# )
end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md


```

### Environment

fastlane version (fastlane -v): fastlane 1.66.0
Do you use bundler, rbenv or rvm? rvm and bundler
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
Bundler version 1.11.2

Updated bundler and bundles

**Comment by vpolouchkine** [comment]
Title? Did you mean icon?

**Comment by rndcmo** [comment]
Correct.  Apologies.

**Comment by vpolouchkine** [comment]
Gotcha. I'm assuming your app does in fact have the icon that `pilot` complains about?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (466/400 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:45232 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtH-002lbW-NC
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:48 +0200
Date: Sat, 18 Jun 2016 11:22:02 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274122;
	bh=Vj0wGltvLXElozXs4pRkNttRZscH3neFFJT+KsYT+Ig=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=h28n6MisL6b/DAsE9nQ3Kf1nKuFeMRlNMaAscONZyrHaMf2UdtLJOdi+fUaDk1cyo
	 2ibh0rGe6GlHB2BkbIaP79eeb482Z2E/Vn1gYfG58Dp7qOy+lkPOvgnQLEynUC4WjC
	 jtSt2uNTce/b3iExYRli6azNSRGJLPuFWJaW5VbA=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (467/400 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:45367 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtI-002lbc-AM
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:48 +0200
Date: Sat, 18 Jun 2016 11:22:03 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274123;
	bh=IdqTr5a/6wLVj5isqe7DO8R0p41T6s576e87nWP3+qk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=gjZZZonfoXVL6KBUVDv7+mBkhhiYJwaVmIvzPkHNlYNfGUwMgA1cROufQm5Y7QxUE
	 vsO0pueEkLg26oF60bedsLVPlzJ+uVXkToGPW8GJtBSDHt1ZIN6Hq4UeyKLxGui9D+
	 Mudoi9os1iq8hFW4IoP6CxUyrlyR7qg5ApYxKlbI=
