### ISSUE TITLE
Screengrab failing to recognize Instrumentation of flavor

### ISSUE THREAD

**Issue by pieisgood** [fastlane/fastlane#3661]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When I attempt to run screengrab against one of my flavors the instrumentation fails, but running my instrumentation tests out of android studio works perfectly fine. Any idea what's happening?
##### Complete output when running fastlane, including the stack trace and command used

```
Lees-MacBook-Pro:EzoicAndroid lee$ screengrab
Appfile: DEPRECATED issuer: use json_key_file instead
Appfile: DEPRECATED keyfile: use json_key_file instead
Appfile: DEPRECATED issuer: use json_key_file instead
Appfile: DEPRECATED keyfile: use json_key_file instead
Appfile: DEPRECATED issuer: use json_key_file instead
Appfile: DEPRECATED keyfile: use json_key_file instead

+-----------------------------+------------------------------------------------+
|                         Summary for screengrab 0.3.0                         |
+-----------------------------+------------------------------------------------+
| locales                     | ["en-US", "fr-FR", "it-IT"]                    |
| clear_previous_screenshots  | true                                           |
| tests_package_name          | com.ezoic.ezoicandroid.app416.test             |
| android_home                | //Users/lee/Library/Android/sdk                |
| output_directory            | fastlane/metadata/android                      |
| skip_open_summary           | false                                          |
| app_package_name            | com.ezoic.ezoicandroid.app416                  |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner |
| ending_locale               | en-US                                          |
| device_type                 | phone                                          |
+-----------------------------+------------------------------------------------+

[14:05:52]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[14:05:52]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[14:05:52]: Clearing phoneScreenshots within fastlane/metadata/android
[14:05:52]: $ adb devices -l
[14:05:52]: ▸ List of devices attached
[14:05:52]: ▸ emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
[14:05:52]: ▸ 31007950cc766200       device usb:336723968X product:degaswifiue model:SM_T230NU device:degaswifiue
[14:05:52]: Multiple connected devices, selecting the first one
[14:05:52]: To specify which connected device to use, use the -s (specific_device) config option
[14:05:52]: $ adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[14:05:52]: ▸ /storage/sdcard
[14:05:52]: Cleaning screenshots on device
[14:05:53]: To not be asked about this value, you can specify it using 'app_apk_path'
[14:05:53]: Select your debug app APK
1. app/app-release.apk
2. app/build/outputs/apk/app-app416-debug-androidTest-unaligned.apk
3. app/build/outputs/apk/app-app416-debug-unaligned.apk
4. app/build/outputs/apk/app-app416-debug.apk
?  3
[14:05:59]: To not be asked about this value, you can specify it using 'tests_apk_path'
[14:05:59]: Select your debug tests APK
1. app/app-release.apk
2. app/build/outputs/apk/app-app416-debug-androidTest-unaligned.apk
3. app/build/outputs/apk/app-app416-debug-unaligned.apk
4. app/build/outputs/apk/app-app416-debug.apk
?  2
[14:06:01]: Validating app APK
[14:06:01]: $ //Users/lee/Library/Android/sdk/build-tools/23.0.1/aapt dump permissions app/build/outputs/apk/app-app416-debug-unaligned.apk
[14:06:01]: ▸ package: com.ezoic.ezoicandroid.app416.debug
[14:06:01]: ▸ uses-permission: name='android.permission.INTERNET'
[14:06:01]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[14:06:01]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[14:06:01]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[14:06:01]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[14:06:01]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[14:06:01]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[14:06:01]: Installing app APK
[14:06:01]: $ adb -s emulator-5554 install -r app/build/outputs/apk/app-app416-debug-unaligned.apk
[14:06:03]: ▸ 2598 KB/s (4194888 bytes in 1.576s)
[14:06:04]: ▸ pkg: /data/local/tmp/app-app416-debug-unaligned.apk
[14:06:18]: ▸ Success
[14:06:18]: Installing tests APK
[14:06:18]: $ adb -s emulator-5554 install -r app/build/outputs/apk/app-app416-debug-androidTest-unaligned.apk
[14:06:18]: ▸ 2615 KB/s (1069541 bytes in 0.399s)
[14:06:18]: ▸ pkg: /data/local/tmp/app-app416-debug-androidTest-unaligned.apk
[14:06:24]: ▸ Success
[14:06:24]: Granting the permission necessary to change locales on the device
[14:06:24]: $ adb -s emulator-5554 shell pm grant com.ezoic.ezoicandroid.app416 android.permission.CHANGE_CONFIGURATION
[14:06:24]: ▸ Bad argument: java.lang.IllegalArgumentException: Unknown package: com.ezoic.ezoicandroid.app416
[14:06:24]: ▸ usage: pm list packages [-f] [-d] [-e] [-s] [-3] [-i] [-u] [--user USER_ID] [FILTER]
[14:06:24]: ▸ pm list permission-groups
[14:06:24]: ▸ pm list permissions [-g] [-f] [-d] [-u] [GROUP]
[14:06:24]: ▸ pm list instrumentation [-f] [TARGET-PACKAGE]
[14:06:24]: ▸ pm list features
[14:06:24]: ▸ pm list libraries
[14:06:24]: ▸ pm list users
[14:06:24]: ▸ pm path PACKAGE
[14:06:24]: ▸ pm dump PACKAGE
[14:06:24]: ▸ pm install [-lrtsfd] [-i PACKAGE] [PATH]
[14:06:24]: ▸ pm install-create [-lrtsfdp] [-i PACKAGE] [-S BYTES]
[14:06:24]: ▸ pm install-write [-S BYTES] SESSION_ID SPLIT_NAME [PATH]
[14:06:24]: ▸ pm install-commit SESSION_ID
[14:06:24]: ▸ pm install-abandon SESSION_ID
[14:06:24]: ▸ pm uninstall [-k] [--user USER_ID] PACKAGE
[14:06:24]: ▸ pm set-installer PACKAGE INSTALLER
[14:06:24]: ▸ pm clear [--user USER_ID] PACKAGE
[14:06:24]: ▸ pm enable [--user USER_ID] PACKAGE_OR_COMPONENT
[14:06:24]: ▸ pm disable [--user USER_ID] PACKAGE_OR_COMPONENT
[14:06:24]: ▸ pm disable-user [--user USER_ID] PACKAGE_OR_COMPONENT
[14:06:24]: ▸ pm disable-until-used [--user USER_ID] PACKAGE_OR_COMPONENT
[14:06:24]: ▸ pm hide [--user USER_ID] PACKAGE_OR_COMPONENT
[14:06:24]: ▸ pm unhide [--user USER_ID] PACKAGE_OR_COMPONENT
[14:06:24]: ▸ pm grant PACKAGE PERMISSION
[14:06:24]: ▸ pm revoke PACKAGE PERMISSION
[14:06:24]: ▸ pm set-install-location [0/auto] [1/internal] [2/external]
[14:06:24]: ▸ pm get-install-location
[14:06:24]: ▸ pm set-permission-enforced PERMISSION [true|false]
[14:06:24]: ▸ pm trim-caches DESIRED_FREE_SPACE
[14:06:24]: ▸ pm create-user [--profileOf USER_ID] [--managed] USER_NAME
[14:06:24]: ▸ pm remove-user USER_ID
[14:06:24]: ▸ pm get-max-users
[14:06:24]: ▸ pm list packages: prints all packages, optionally only
[14:06:24]: ▸ those whose package name contains the text in FILTER.  Options:
[14:06:24]: ▸ -f: see their associated file.
[14:06:24]: ▸ -d: filter to only show disbled packages.
[14:06:24]: ▸ -e: filter to only show enabled packages.
[14:06:24]: ▸ -s: filter to only show system packages.
[14:06:24]: ▸ -3: filter to only show third party packages.
[14:06:24]: ▸ -i: see the installer for the packages.
[14:06:24]: ▸ -u: also include uninstalled packages.
[14:06:24]: ▸ pm list permission-groups: prints all known permission groups.
[14:06:24]: ▸ pm list permissions: prints all known permissions, optionally only
[14:06:24]: ▸ those in GROUP.  Options:
[14:06:24]: ▸ -g: organize by group.
[14:06:24]: ▸ -f: print all information.
[14:06:24]: ▸ -s: short summary.
[14:06:24]: ▸ -d: only list dangerous permissions.
[14:06:24]: ▸ -u: list only the permissions users will see.
[14:06:24]: ▸ pm list instrumentation: use to list all test packages; optionally
[14:06:24]: ▸ supply <TARGET-PACKAGE> to list the test packages for a particular
[14:06:24]: ▸ application.  Options:
[14:06:24]: ▸ -f: list the .apk file for the test package.
[14:06:24]: ▸ pm list features: prints all features of the system.
[14:06:24]: ▸ pm list users: prints all users on the system.
[14:06:24]: ▸ pm path: print the path to the .apk of the given PACKAGE.
[14:06:24]: ▸ pm dump: print system state associated with the given PACKAGE.
[14:06:24]: ▸ pm install: install a single legacy package
[14:06:24]: ▸ pm install-create: create an install session
[14:06:24]: ▸ -l: forward lock application
[14:06:24]: ▸ -r: replace existing application
[14:06:24]: ▸ -t: allow test packages
[14:06:24]: ▸ -i: specify the installer package name
[14:06:24]: ▸ -s: install application on sdcard
[14:06:24]: ▸ -f: install application on internal flash
[14:06:24]: ▸ -d: allow version code downgrade
[14:06:24]: ▸ -p: partial application install
[14:06:24]: ▸ -S: size in bytes of entire session
[14:06:24]: ▸ pm install-write: write a package into existing session; path may
[14:06:24]: ▸ be '-' to read from stdin
[14:06:24]: ▸ -S: size in bytes of package, required for stdin
[14:06:24]: ▸ pm install-commit: perform install of fully staged session
[14:06:24]: ▸ pm install-abandon: abandon session
[14:06:24]: ▸ pm set-installer: set installer package name
[14:06:24]: ▸ pm uninstall: removes a package from the system. Options:
[14:06:24]: ▸ -k: keep the data and cache directories around after package removal.
[14:06:24]: ▸ pm clear: deletes all data associated with a package.
[14:06:24]: ▸ pm enable, disable, disable-user, disable-until-used: these commands
[14:06:24]: ▸ change the enabled state of a given package or component (written
[14:06:24]: ▸ as "package/class").
[14:06:24]: ▸ pm grant, revoke: these commands either grant or revoke permissions
[14:06:24]: ▸ to applications.  Only optional permissions the application has
[14:06:24]: ▸ declared can be granted or revoked.
[14:06:24]: ▸ pm get-install-location: returns the current install location.
[14:06:24]: ▸ 0 [auto]: Let system decide the best location
[14:06:24]: ▸ 1 [internal]: Install on internal device storage
[14:06:24]: ▸ 2 [external]: Install on external media
[14:06:24]: ▸ pm set-install-location: changes the default install location.
[14:06:24]: ▸ NOTE: this is only intended for debugging; using this can cause
[14:06:24]: ▸ applications to break and other undersireable behavior.
[14:06:24]: ▸ 0 [auto]: Let system decide the best location
[14:06:24]: ▸ 1 [internal]: Install on internal device storage
[14:06:24]: ▸ 2 [external]: Install on external media
[14:06:24]: ▸ pm trim-caches: trim cache files to reach the given free space.
[14:06:24]: ▸ pm create-user: create a new user with the given USER_NAME,
[14:06:24]: ▸ printing the new user identifier of the user.
[14:06:24]: ▸ pm remove-user: remove the user with the given USER_IDENTIFIER,
[14:06:24]: ▸ deleting all data associated with that user
[14:06:24]: $ adb -s emulator-5554 shell getprop ro.build.version.sdk
[14:06:24]: ▸ 22
[14:06:24]: Running tests for locale: en-US
[14:06:24]: $ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
com.ezoic.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner
[14:06:24]: ▸ INSTRUMENTATION_STATUS: id=ActivityManagerService
[14:06:24]: ▸ INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.ezoic.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner}
[14:06:24]: ▸ INSTRUMENTATION_STATUS_CODE: -1
[14:06:24]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.ezoic.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner
[14:06:24]: ▸ at com.android.commands.am.Am.runInstrument(Am.java:977)
[14:06:24]: ▸ at com.android.commands.am.Am.onRun(Am.java:317)
[14:06:24]: ▸ at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
[14:06:24]: ▸ at com.android.commands.am.Am.main(Am.java:97)
[14:06:24]: ▸ at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[14:06:24]: ▸ at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
[14:06:24]: Running tests for locale: fr-FR
[14:06:24]: $ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale fr_FR \
-e endingLocale en_US \
com.ezoic.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner
[14:06:25]: ▸ INSTRUMENTATION_STATUS: id=ActivityManagerService
[14:06:25]: ▸ INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.ezoic.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner}
[14:06:25]: ▸ INSTRUMENTATION_STATUS_CODE: -1
[14:06:25]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.ezoic.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner
[14:06:25]: ▸ at com.android.commands.am.Am.runInstrument(Am.java:977)
[14:06:25]: ▸ at com.android.commands.am.Am.onRun(Am.java:317)
[14:06:25]: ▸ at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
[14:06:25]: ▸ at com.android.commands.am.Am.main(Am.java:97)
[14:06:25]: ▸ at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[14:06:25]: ▸ at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
[14:06:25]: Running tests for locale: it-IT
[14:06:25]: $ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale it_IT \
-e endingLocale en_US \
com.ezoic.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner
[14:06:25]: ▸ INSTRUMENTATION_STATUS: id=ActivityManagerService
[14:06:25]: ▸ INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.some.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner}
[14:06:25]: ▸ INSTRUMENTATION_STATUS_CODE: -1
[14:06:25]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.ezoic.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner
[14:06:25]: ▸ at com.android.commands.am.Am.runInstrument(Am.java:977)
[14:06:25]: ▸ at com.android.commands.am.Am.onRun(Am.java:317)
[14:06:25]: ▸ at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
[14:06:25]: ▸ at com.android.commands.am.Am.main(Am.java:97)
[14:06:25]: ▸ at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[14:06:25]: ▸ at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
[14:06:25]: Pulling captured screenshots from the device
[14:06:25]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

[!] No screenshots were detected 📷❌

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
Using screengrab directly
```

### Environment

fastlane version (fastlane -v): 
Do you use bundler, rbenv or rvm? no

**Comment by lvh1** [comment]
I'm also getting the same error. Launching the tests from android studio works fine, but not through screengrab.
Screengrab 0.3.1, fastlane core 0.38.0 (due to a bug in 0.39.0 which also doesn't work), on Ubuntu 15.10.

**Comment by pieisgood** [comment]
Any ideas?

**Comment by TKBurner** [comment]
Hi @pieisgood , it looks like the failure is here:

[14:06:25]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.ezoic.ezoicandroid.app416.test/android.support.test.runner.AndroidJUnitRunner
[14:06:25]: ▸ at com.android.commands.am.Am.runInstrument(Am.java:977)
[14:06:25]: ▸ at com.android.commands.am.Am.onRun(Am.java:317)
[14:06:25]: ▸ at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
[14:06:25]: ▸ at com.android.commands.am.Am.main(Am.java:97)
[14:06:25]: ▸ at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[14:06:25]: ▸ at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
[14:06:25]: Pulling captured screenshots from the device
[14:06:25]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

@lvh1 are you getting an identical error?

Thanks!

**Comment by lvh1** [comment]
@TKBurner Yes, getting the exact same error.

**Comment by lvh1** [comment]
Turns out it was my mistake by using the wrong package name (forgot a dot).
So nevermind...

**Comment by TKBurner** [comment]
@lvh1 Thanks for letting me know! Closing this out :+1:
