### ISSUE TITLE
Potential Issue with Pilot

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#3670]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane seems to be throwing some strange error that I think is in the software - and not in my code.  As far as I can tell i'm running the latest version.

##### Complete output when running fastlane, including the stack trace and command used

```
/Users/jstein/.rvm/gems/ruby-2.1.0/gems/pilot-1.4.1/lib/pilot/build_manager.rb:87:in `wait_for_processing_build': [!] undefined method `builds' for nil:NilClass (NoMethodError)
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/pilot-1.4.1/lib/pilot/build_manager.rb:25:in `upload'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:339:in `block (2 levels) in parsing_binding'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:110:in `try_switch_to_lane'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from Fastfile:179:in `block (2 levels) in parsing_binding'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane_core-0.36.8/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/bin/fastlane:156:in `run'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/gems/fastlane-1.66.0/bin/fastlane:162:in `<top (required)>'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/bin/fastlane:23:in `load'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/bin/fastlane:23:in `<main>'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jstein/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# The failing line is - 339 which does
   pilot(verbose: true)
```

### Environment

fastlane version (fastlane -v): 1.66.0
Do you use bundler, rbenv or rvm? - RVM

**Comment by jeeftor** [comment]
I think this error is because my bundle was rejected for having code coverage ... -> Still not sure if there is a better way of handling the error on your end.

**Comment by TKBurner** [comment]
Thanks for following up @jeeftor! We'll have a look at this as a feature request. Hope that you have a wonderful week! 👍
