### ISSUE TITLE
Crashing when I try to do run match development

### ISSUE THREAD

**Issue by elianfish** [fastlane/fastlane#3692]
I get this following error each time I run match development . (match 0.3.0)
```
[15:23:14]: No existing profiles found, that match the certificates you have installed, creating a new one for you
[15:23:17]: Creating new provisioning profile for 'com.test.ysl1' with name 'match Development com.test.ysl1'
[15:23:20]: 🔒  Successfully encrypted certificates repo
/-------------------------------------------------------------------------------------------
 An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
 This makes resolving issues much easier and helps improve fastlane.
 The reports will be stored securely on getsentry.com.
 More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
/-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/client.rb:300:in `parse_response': [!] {"responseId"=>"612597ae-99e2-44af-bf8a-c721678335ba", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"There are no current devices on this team matching the provided device IDs.", "creationTimestamp"=>"2016-03-11T07:23:20Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action", "httpCode"=>200, "validationMessages"=>[{"validationKey"=>"deviceIds", "validationUserMessage"=>"There are no current devices on this team matching the provided device IDs."}]} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/portal_client.rb:352:in `create_provisioning_profile!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/provisioning_profile.rb:227:in `block in create!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/client.rb:195:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/provisioning_profile.rb:226:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/runner.rb:109:in `create_profile!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/runner.rb:39:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/generator.rb:55:in `generate_provisioning_profile'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:84:in `profile'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:52:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:108:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:116:in `<top (required)>'
	from /usr/bin/match:23:in `load'
	from /usr/bin/match:23:in `<main>'
```

**Comment by asfalcone** [comment]
@elianfish The error from apple is `There are no current devices on this team matching the provided device IDs.` Can you confirm this is setup correctly?

Please also provide the full output, including the command that you ran.

**Comment by tomaskraina** [comment]
I ran into the very same issue. New dev account with no devices in it. `sigh` blows up.

Here's the full output:

```
+-------------------------------------+----------------------------------+
|                         Summary for sigh 1.4.1                         |
+-------------------------------------+----------------------------------+
| app_identifier                      | **************                   |
| adhoc                               | false                            |
| development                         | true                             |
| username                            | *******************           |
| force                               | true                             |
| cert_id                             | ***********                       |
| provisioning_name                   | match Development ********* |
| ignore_profiles_with_different_name | true                             |
| skip_install                        | false                            |
| skip_fetch_profiles                 | false                            |
| skip_certificate_verification       | false                            |
+-------------------------------------+----------------------------------+

[14:55:45]: Starting login with user '******@*******'
[14:55:47]: Successfully logged in
[14:55:47]: Fetching profiles...
[14:55:49]: No existing profiles found, that match the certificates you have installed, creating a new one for you
[14:55:52]: Creating new provisioning profile for '**********' with name 'match Development *********'
[14:55:55]: 🔒  Successfully encrypted certificates repo
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:300:in `parse_response': [!] {"responseId"=>"51f5c37c-4822-4902-910a-6747a7729655", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"There are no current devices on this team matching the provided device IDs.", "creationTimestamp"=>"2016-03-12T13:55:55Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action", "httpCode"=>200, "validationMessages"=>[{"validationKey"=>"deviceIds", "validationUserMessage"=>"There are no current devices on this team matching the provided device IDs."}]} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:352:in `create_provisioning_profile!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/portal/provisioning_profile.rb:227:in `block in create!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/client.rb:195:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/portal/provisioning_profile.rb:226:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.1/lib/sigh/runner.rb:109:in `create_profile!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.1/lib/sigh/runner.rb:39:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.1/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/generator.rb:55:in `generate_provisioning_profile'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:84:in `profile'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/lib/match/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:52:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:108:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.3.0/bin/match:116:in `<top (required)>'
	from /usr/bin/match:23:in `load'
	from /usr/bin/match:23:in `<main>'
```

**Comment by elianfish** [comment]
@asfalcone thank you!
