### ISSUE TITLE
Unable to submit to review because of release notes.

### ISSUE THREAD

**Issue by chezzdev** [fastlane/fastlane#3716]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When I want to submit my application for review I get the error message that I hadn't specified release notes in needed language. But I do specify it in the Deliverfile.
##### Command used:
```
deliver \
  --skip_binary_upload \
  --skip_screenshots \
  --skip_metadata \
  --submit_for_review
```

##### Complete output when running fastlane, including the stack trace and command used

```
[02:18:05]: Login to iTunes Connect (user@company.com)
[02:18:10]: Login successful

+--------------------------------------------------------------------+-----------------------------+
|                                      deliver 1.10.3 Summary                                      |
+--------------------------------------------------------------------+-----------------------------+
| skip_binary_upload                                                 | true                        |
| skip_screenshots                                                   | true                        |
| skip_metadata                                                      | true                        |
| submit_for_review                                                  | true                        |
| force                                                              | true                        |
| price_tier                                                         | 0                           |
| app_rating_config_path                                             | itunes_rating_config.json   |
| submission_information.add_id_info_uses_idfa                       | false                       |
| submission_information.content_rights_contains_third_party_content | false                       |
| submission_information.content_rights_has_rights                   | false                       |
| submission_information.export_compliance_encryption_updated        | false                       |
| release_notes.en-US                                                | new                         |
| username                                                           | name@company.com            |
| app_identifier                                                     | com.company.app             |
| app_version                                                        | NEW_VERSION                 |
| ipa                                                                | app.ipa				       |
| automatic_release                                                  | false                       |
| screenshots_path                                                   | ./screenshots               |
| metadata_path                                                      | ./metadata                  |
+--------------------------------------------------------------------+-----------------------------+

[02:18:11]: Making sure the latest version on iTunes Connect matches 'NEW_VERSION' from the ipa file...
[02:18:13]: 'NEW_VERSION' is the latest version on iTunes Connect
[02:18:14]: Price Tier unchanged (tier 0)
[02:18:16]: Finished the upload to iTunes Connect
[02:18:18]: Selecting the latest build...
[02:18:22]: Selecting build 1.0.83 (2342)...
[02:18:23]: Successfully selected build
[02:18:23]: Submitting the app for review...
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] You must detail what's new in this version in English. (Spaceship::TunesClient::ITunesConnectError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/tunes/tunes_client.rb:708:in `prepare_app_submissions'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/tunes/app_submission.rb:117:in `create'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.23.0/lib/spaceship/tunes/application.rb:269:in `create_submission'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.10.3/lib/deliver/submit_for_review.rb:8:in `submit!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.10.3/lib/deliver/runner.rb:87:in `submit_for_review'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.10.3/lib/deliver/runner.rb:30:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:132:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.10.3/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
```

### Configuration Files

This is the Deliverfile:
```ruby
force true
price_tier 0
app_rating_config_path "itunes_rating_config.json"
submission_information({
	add_id_info_uses_idfa: false,
	content_rights_contains_third_party_content: false,
	content_rights_has_rights: false,
	export_compliance_encryption_updated: false
})
release_notes({"en-US" => "new"})
username "name@company.com"
app_identifier "com.company.app"
app_version "NEW_VERSION"
ipa "app.ipa"
automatic_release false
```
I have no other configuration files.
### Environment

➜  deliver --version
deliver 1.10.3
➜  fastlane --version
fastlane 1.66.0
Do you use bundler, rbenv or rvm? No.

**Comment by vpolouchkine** [comment]
What happens if you remove the `skip_metadata` flag?

**Comment by chezzdev** [comment]
Oh. I didn't think of release notes as metadata. Thanks, the issue's resolved.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (422/400 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:56519 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMl-000ale-VA
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:28 +0100
Date: Mon, 14 Mar 2016 15:51:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457995884;
	bh=LkUyM6Qaovd1u+fLxPx0DR74MEkv5Ph+CTDCw8g8/y8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=SnV6dW0MP+f8o5U29UeWP+2+M4j8bTWSCIfXQP2O1Z/xvZ5E13nO8klO4P2AIJhQb
	 TG8LiQl7vzWAnHeXgFr2GB9lS6K7IdJC1hPedxMql7Fmu8G88V1J7dM2oBwNVMq2PY
	 /O2wV0g2D2XjbFK9mawKqgXBl8oifaRx2HPcc6Qc=
