### ISSUE TITLE
pilot find fails to list details of tester

### ISSUE THREAD

**Issue by cedoucette** [fastlane/fastlane#3735]
When I try to print out details of a tester:

dhcp-10-92-132-228:System44 doucettec$ pilot find hmhmobiletest@gmail.com

it crashes:

```
[16:28:37]: Login to iTunes Connect (Charles.Doucette@hmhco.com)
[16:28:41]: Login successful
[16:28:41]: [hmhmobiletest@gmail.com]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Forbidden"], "info"=>nil}, "statusCode"=>"ERROR"}
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '940a6b0a006aabc3297f500a443dc1a7'
The crash report has been stored locally '/tmp/sentry_940a6b0a006aabc3297f500a443dc1a7.json'
/Library/Ruby/Gems/2.0.0/gems/pilot-1.4.1/lib/pilot/commands_generator.rb:41:in `handle_multiple': [!] Some operations failed: ["hmhmobiletest@gmail.com"] (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.4.1/lib/pilot/commands_generator.rb:93:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.4.1/lib/pilot/commands_generator.rb:125:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.4.1/lib/pilot/commands_generator.rb:16:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.4.1/bin/pilot:6:in `<top (required)>'
	from /usr/bin/pilot:23:in `load'
	from /usr/bin/pilot:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.66.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "System44") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "System44") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
```

### Environment

fastlane version (fastlane -v): dhcp-10-92-132-228:System44 doucettec$ fastlane -v
fastlane 1.66.0

Do you use bundler, rbenv or rvm?

**Comment by GantMan** [comment]
I have this as well.  It fails for a newer app, but works on another one.   Interesting.

**Comment by GantMan** [comment]
FYI:  787469c2645f95569b870c2c80662507 is the crashlog

**Comment by TKBurner** [comment]
Hi @GantMan. Great to hear from you. Can you try logging into  https://appleid.apple.com/ once with the email address associated with this app? This seems like it could be related to an issue we are seeing. Thanks!

**Comment by Fudge0952** [comment]
Hi @TKBurner. I got the same error. I attempted to log into [https://appleid.apple.com/](https://appleid.apple.com/) first and then try again but still got the same error. (printed error below and running on pilot version 1.5.0)

> $ pilot find tim.ellis@accelo.com
> [11:08:34]: Login to iTunes Connect (tim.ellis@accelo.com)
> [11:08:38]: Login successful
> [11:08:38]: [tim.ellis@accelo.com]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}
> 
> [!] Some operations failed: ["tim.ellis@accelo.com"]
> $ pilot -v
> pilot 1.5.0

**Comment by TKBurner** [comment]
Thanks for following up @Fudge0952. We are going to look into this over here! 👍

**Comment by jaleksynas** [comment]
Similar to #1895 (which is a result of account permissions). If you specify an app_id (-a) or apple_id (-p) does the request succeed?
