### ISSUE TITLE
failed by Jenkins, but passed if run it locally

### ISSUE THREAD

**Issue by 3a4oT** [fastlane/fastlane#382]
* fastlane - 1.6.0
* xctool - 0.2.4
* Xcode 6.4
* pod - 0.37.2
* OS X 10.10.4

**Fastfile**

```ruby

fastlane_version "1.6.0"

default_platform :ios


platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    cocoapods

    #customized
     ipa(
           workspace: 'ftol.xcworkspace',
           configuration: 'Release',
           scheme: 'ftol',
           ipa: 'ftol.ipa',
           clean: true,
         )

    #customized
    xctool :test , [
      "-workspace", "ftol.xcworkspace",
      "-scheme", "ftol",
      "-configuration", "Debug",
      "-reporter", "junit",
      "-sdk","iphonesimulator",
      "-arch","i386",
      "GCC_GENERATE_TEST_COVERAGE_FILES=YES", #Needed to gen coverage files used by lcov
      "GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES"#Needed to gen coverage files used by lcov
    ].join(" ")
  end

  # You can define as many lanes as you want
  lane :ftol do
    say("All is Cool ^_^")
  end
  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end


```

**Jenkins console output**

```
[37m[00:17:05]: [0m[SHELL]: Downloading dependencies
[37m[00:17:05]: [0m[SHELL]: Using Alamofire (1.2.3)
[37m[00:17:05]: [0m[SHELL]: Using EasyMapping (0.15.1)
[37m[00:17:05]: [0m[SHELL]: Generating Pods project
[37m[00:17:05]: [0m[SHELL]: Integrating client project
[37m[00:17:05]: [0m[32m-----------------[0m
[37m[00:17:05]: [0m[32m--- [0m[32mStep: ipa[0m[32m ---[0m
[37m[00:17:05]: [0m[32m-----------------[0m
[35m[00:17:05]: [0mset -o pipefail && krausefx-ipa build -s "ftol" --verbose | xcpretty
[37m[00:17:05]: [0m[SHELL COMMAND]: [33mset -o pipefail && krausefx-ipa build -s "ftol" --verbose | xcpretty[0m
[37m[00:17:11]: [0m[SHELL]: ▸ Cleaning Pods/Pods-Alamofire [Release]
[37m[00:17:11]: [0m[SHELL]: ▸ Cleaning Pods/Pods-EasyMapping [Release]
[37m[00:17:11]: [0m[SHELL]: ▸ Cleaning Pods/Pods [Release]
[37m[00:17:11]: [0m[SHELL]: ▸ Cleaning ftol/ftol [Release]
[37m[00:17:11]: [0m[SHELL]: ▸ Building Pods/Pods-EasyMapping [Release]
[37m[00:17:30]: [0m[SHELL]: ▸ Processing Info.plist
[37m[00:17:30]: [0m[SHELL]: ▸ Compiling EKCoreDataImporter.m
[37m[00:17:32]: [0m[SHELL]: ▸ Compiling EKManagedObjectMapper.m
[37m[00:17:32]: [0m[SHELL]: ▸ Compiling EKManagedObjectMapping.m
[37m[00:17:32]: [0m[SHELL]: ▸ Compiling EKManagedObjectModel.m
[37m[00:17:32]: [0m[SHELL]: ▸ Compiling EKMapper.m
[37m[00:17:32]: [0m[SHELL]: ▸ Compiling EKMappingBlocks.m
[37m[00:17:32]: [0m[SHELL]: ▸ Compiling EKObjectMapping.m
[37m[00:17:33]: [0m[SHELL]: ▸ Compiling EKObjectModel.m
[37m[00:17:33]: [0m[SHELL]: ▸ Compiling EKPropertyHelper.m
[37m[00:17:33]: [0m[SHELL]: ▸ Compiling EKPropertyMapping.m
[37m[00:17:33]: [0m[SHELL]: ▸ Compiling EKRelationshipMapping.m
[37m[00:17:33]: [0m[SHELL]: ▸ Compiling EKSerializer.m
[37m[00:17:33]: [0m[SHELL]: ▸ Compiling NSArray+FlattenArray.m
[37m[00:17:33]: [0m[SHELL]: ▸ Compiling NSDateFormatter+EasyMappingAdditions.m
[37m[00:17:33]: [0m[SHELL]: ▸ Compiling Pods-EasyMapping-dummy.m
[37m[00:17:35]: [0m[SHELL]: ▸ Compiling EasyMapping_vers.c
[37m[00:17:35]: [0m[SHELL]: ▸ Compiling EKCoreDataImporter.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKManagedObjectMapper.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKManagedObjectMapping.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKManagedObjectModel.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKMapper.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKMappingBlocks.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKObjectMapping.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKObjectModel.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKPropertyHelper.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKPropertyMapping.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKRelationshipMapping.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EKSerializer.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling NSArray+FlattenArray.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling NSDateFormatter+EasyMappingAdditions.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling Pods-EasyMapping-dummy.m
[37m[00:17:37]: [0m[SHELL]: ▸ Compiling EasyMapping_vers.c
[37m[00:17:37]: [0m[SHELL]: ▸ Linking EasyMapping
[37m[00:17:37]: [0m[SHELL]: ▸ Linking EasyMapping
[37m[00:17:38]: [0m[SHELL]: ▸ Generating 'EasyMapping.framework.dSYM'
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKCoreDataImporter.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKManagedObjectMapper.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKManagedObjectMapping.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKManagedObjectModel.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKMapper.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKMappingBlocks.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKObjectMapping.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKMappingProtocol.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKObjectModel.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKPropertyMapping.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKPropertyHelper.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKRelationshipMapping.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EKSerializer.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying EasyMapping.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying NSArray+FlattenArray.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying NSDateFormatter+EasyMappingAdditions.h
[37m[00:17:38]: [0m[SHELL]: ▸ Copying Pods-EasyMapping-umbrella.h
[37m[00:17:38]: [0m[SHELL]: ▸ Touching EasyMapping.framework
[37m[00:17:38]: [0m[SHELL]: ▸ Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Products/Release-iphoneos/Pods/EasyMapping.framework
[37m[00:17:39]: [0m[SHELL]: ▸ Building Pods/Pods-Alamofire [Release]
[37m[00:17:39]: [0m[SHELL]: ▸ Processing Info.plist
[37m[00:17:39]: [0m[SHELL]: ▸ Compiling Pods-Alamofire-dummy.m
[37m[00:17:39]: [0m[SHELL]: ▸ Compiling Alamofire_vers.c
[37m[00:17:39]: [0m[SHELL]: ▸ Compiling Pods-Alamofire-dummy.m
[37m[00:17:39]: [0m[SHELL]: ** BUILD FAILED **
[37m[00:17:39]: [0m[SHELL]: 
[37m[00:17:39]: [0m[SHELL]: 
[37m[00:17:39]: [0m[SHELL]: The following build commands failed:
[37m[00:17:39]: [0m[SHELL]: CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Products/Release-iphoneos/Pods/EasyMapping.framework
[37m[00:17:39]: [0m[SHELL]: CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Products/Release-iphoneos/Pods/Alamofire.framework
[37m[00:17:39]: [0m[SHELL]: (2 failures)
[37m[00:17:39]: [0m[SHELL]: ▸ Compiling Alamofire_vers.c
[37m[00:17:39]: [0m[SHELL]: ▸ Linking Alamofire
[37m[00:17:39]: [0m[SHELL]: ▸ Linking Alamofire
[37m[00:17:39]: [0m[SHELL]: ▸ Generating 'Alamofire.framework.dSYM'
[37m[00:17:39]: [0m[SHELL]: ▸ Copying Pods-Alamofire-umbrella.h
[37m[00:17:39]: [0m[SHELL]: ▸ Touching Alamofire.framework
[37m[00:17:39]: [0m[SHELL]: ▸ Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Products/Release-iphoneos/Pods/Alamofire.framework
[37m[00:17:39]: [0m[SHELL]: ▸ Building Pods/Pods-EasyMapping [Release]
[37m[00:17:55]: [0m[SHELL]: ▸ Processing Info.plist
[37m[00:17:55]: [0m[SHELL]: ▸ Compiling EKCoreDataImporter.m
[37m[00:17:55]: [0m[SHELL]: ▸ Compiling EKManagedObjectMapper.m
[37m[00:17:55]: [0m[SHELL]: ▸ Compiling EKManagedObjectMapping.m
[37m[00:17:55]: [0m[SHELL]: ▸ Compiling EKManagedObjectModel.m
[37m[00:17:55]: [0m[SHELL]: ▸ Compiling EKMapper.m
[37m[00:17:55]: [0m[SHELL]: ▸ Compiling EKMappingBlocks.m
[37m[00:17:55]: [0m[SHELL]: ▸ Compiling EKObjectMapping.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKObjectModel.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKPropertyHelper.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKPropertyMapping.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKRelationshipMapping.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKSerializer.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling NSArray+FlattenArray.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling NSDateFormatter+EasyMappingAdditions.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling Pods-EasyMapping-dummy.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EasyMapping_vers.c
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKCoreDataImporter.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKManagedObjectMapper.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKManagedObjectMapping.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKManagedObjectModel.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKMapper.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKMappingBlocks.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKObjectMapping.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKObjectModel.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKPropertyHelper.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKPropertyMapping.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKRelationshipMapping.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EKSerializer.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling NSArray+FlattenArray.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling NSDateFormatter+EasyMappingAdditions.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling Pods-EasyMapping-dummy.m
[37m[00:17:56]: [0m[SHELL]: ▸ Compiling EasyMapping_vers.c
[37m[00:17:56]: [0m[SHELL]: ▸ Linking EasyMapping
[37m[00:17:57]: [0m[SHELL]: ▸ Linking EasyMapping
[37m[00:17:57]: [0m[SHELL]: ▸ Generating 'EasyMapping.framework.dSYM'
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKCoreDataImporter.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKManagedObjectMapper.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKManagedObjectMapping.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKManagedObjectModel.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKMapper.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKMappingBlocks.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKMappingProtocol.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKObjectModel.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKObjectMapping.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKPropertyMapping.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKPropertyHelper.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKRelationshipMapping.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EKSerializer.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying EasyMapping.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying NSDateFormatter+EasyMappingAdditions.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying NSArray+FlattenArray.h
[37m[00:17:57]: [0m[SHELL]: ▸ Copying Pods-EasyMapping-umbrella.h
[37m[00:17:57]: [0m[SHELL]: ▸ Touching EasyMapping.framework
[37m[00:17:57]: [0m[SHELL]: ▸ Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Intermediates/ArchiveIntermediates/ftol/IntermediateBuildFilesPath/UninstalledProducts/EasyMapping.framework
[37m[00:17:57]: [0m[SHELL]: ▸ Building Pods/Pods-Alamofire [Release]
[37m[00:17:57]: [0m[SHELL]: ▸ Processing Info.plist
[37m[00:17:57]: [0m[SHELL]: ** ARCHIVE FAILED **
[37m[00:17:57]: [0m[SHELL]: 
[37m[00:17:57]: [0m[SHELL]: 
[37m[00:17:57]: [0m[SHELL]: The following build commands failed:
[37m[00:17:57]: [0m[SHELL]: CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Intermediates/ArchiveIntermediates/ftol/IntermediateBuildFilesPath/UninstalledProducts/Alamofire.framework
[37m[00:17:57]: [0m[SHELL]: (1 failure)
[37m[00:17:57]: [0m[SHELL]: ▸ Compiling Pods-Alamofire-dummy.m
[37m[00:17:57]: [0m[SHELL]: ▸ Compiling Alamofire_vers.c
[37m[00:17:57]: [0m[SHELL]: ▸ Compiling Pods-Alamofire-dummy.m
[37m[00:17:57]: [0m[SHELL]: ▸ Compiling Alamofire_vers.c
[37m[00:17:57]: [0m[SHELL]: ▸ Linking Alamofire
[37m[00:17:57]: [0m[SHELL]: ▸ Linking Alamofire
[37m[00:17:57]: [0m[SHELL]: ▸ Generating 'Alamofire.framework.dSYM'
[37m[00:17:57]: [0m[SHELL]: ▸ Copying Pods-Alamofire-umbrella.h
[37m[00:17:57]: [0m[SHELL]: ▸ Touching Alamofire.framework
[37m[00:17:57]: [0m[SHELL]: ▸ Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Intermediates/ArchiveIntermediates/ftol/IntermediateBuildFilesPath/UninstalledProducts/Alamofire.framework
[31m[00:17:57]: [0m[33m-------------------------------------------------------[0m
[31m[00:17:57]: [0m[33mOriginal Error:[0m
[31m[00:17:57]: [0m[33m => Exit status of command 'set -o pipefail && krausefx-ipa build -s "ftol" --verbose | xcpretty' was 256 instead of 0. 
▸ Cleaning Pods/Pods-Alamofire [Release]
▸ Cleaning Pods/Pods-EasyMapping [Release]
▸ Cleaning Pods/Pods [Release]
▸ Cleaning ftol/ftol [Release]
▸ Building Pods/Pods-EasyMapping [Release]
▸ Processing Info.plist
▸ Compiling EKCoreDataImporter.m
▸ Compiling EKManagedObjectMapper.m
▸ Compiling EKManagedObjectMapping.m
▸ Compiling EKManagedObjectModel.m
▸ Compiling EKMapper.m
▸ Compiling EKMappingBlocks.m
▸ Compiling EKObjectMapping.m
▸ Compiling EKObjectModel.m
▸ Compiling EKPropertyHelper.m
▸ Compiling EKPropertyMapping.m
▸ Compiling EKRelationshipMapping.m
▸ Compiling EKSerializer.m
▸ Compiling NSArray+FlattenArray.m
▸ Compiling NSDateFormatter+EasyMappingAdditions.m
▸ Compiling Pods-EasyMapping-dummy.m
▸ Compiling EasyMapping_vers.c
▸ Compiling EKCoreDataImporter.m
▸ Compiling EKManagedObjectMapper.m
▸ Compiling EKManagedObjectMapping.m
▸ Compiling EKManagedObjectModel.m
▸ Compiling EKMapper.m
▸ Compiling EKMappingBlocks.m
▸ Compiling EKObjectMapping.m
▸ Compiling EKObjectModel.m
▸ Compiling EKPropertyHelper.m
▸ Compiling EKPropertyMapping.m
▸ Compiling EKRelationshipMapping.m
▸ Compiling EKSerializer.m
▸ Compiling NSArray+FlattenArray.m
▸ Compiling NSDateFormatter+EasyMappingAdditions.m
▸ Compiling Pods-EasyMapping-dummy.m
▸ Compiling EasyMapping_vers.c
▸ Linking EasyMapping
▸ Linking EasyMapping
▸ Generating 'EasyMapping.framework.dSYM'
▸ Copying EKCoreDataImporter.h
▸ Copying EKManagedObjectMapper.h
▸ Copying EKManagedObjectMapping.h
▸ Copying EKManagedObjectModel.h
▸ Copying EKMapper.h
▸ Copying EKMappingBlocks.h
▸ Copying EKObjectMapping.h
▸ Copying EKMappingProtocol.h
▸ Copying EKObjectModel.h
▸ Copying EKPropertyMapping.h
▸ Copying EKPropertyHelper.h
▸ Copying EKRelationshipMapping.h
▸ Copying EKSerializer.h
▸ Copying EasyMapping.h
▸ Copying NSArray+FlattenArray.h
▸ Copying NSDateFormatter+EasyMappingAdditions.h
▸ Copying Pods-EasyMapping-umbrella.h
▸ Touching EasyMapping.framework
▸ Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Products/Release-iphoneos/Pods/EasyMapping.framework
▸ Building Pods/Pods-Alamofire [Release]
▸ Processing Info.plist
▸ Compiling Pods-Alamofire-dummy.m
▸ Compiling Alamofire_vers.c
▸ Compiling Pods-Alamofire-dummy.m
** BUILD FAILED **


The following build commands failed:
	CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Products/Release-iphoneos/Pods/EasyMapping.framework
	CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Products/Release-iphoneos/Pods/Alamofire.framework
(2 failures)
▸ Compiling Alamofire_vers.c
▸ Linking Alamofire
▸ Linking Alamofire
▸ Generating 'Alamofire.framework.dSYM'
▸ Copying Pods-Alamofire-umbrella.h
▸ Touching Alamofire.framework
▸ Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Products/Release-iphoneos/Pods/Alamofire.framework
▸ Building Pods/Pods-EasyMapping [Release]
▸ Processing Info.plist
▸ Compiling EKCoreDataImporter.m
▸ Compiling EKManagedObjectMapper.m
▸ Compiling EKManagedObjectMapping.m
▸ Compiling EKManagedObjectModel.m
▸ Compiling EKMapper.m
▸ Compiling EKMappingBlocks.m
▸ Compiling EKObjectMapping.m
▸ Compiling EKObjectModel.m
▸ Compiling EKPropertyHelper.m
▸ Compiling EKPropertyMapping.m
▸ Compiling EKRelationshipMapping.m
▸ Compiling EKSerializer.m
▸ Compiling NSArray+FlattenArray.m
▸ Compiling NSDateFormatter+EasyMappingAdditions.m
▸ Compiling Pods-EasyMapping-dummy.m
▸ Compiling EasyMapping_vers.c
▸ Compiling EKCoreDataImporter.m
▸ Compiling EKManagedObjectMapper.m
▸ Compiling EKManagedObjectMapping.m
▸ Compiling EKManagedObjectModel.m
▸ Compiling EKMapper.m
▸ Compiling EKMappingBlocks.m
▸ Compiling EKObjectMapping.m
▸ Compiling EKObjectModel.m
▸ Compiling EKPropertyHelper.m
▸ Compiling EKPropertyMapping.m
▸ Compiling EKRelationshipMapping.m
▸ Compiling EKSerializer.m
▸ Compiling NSArray+FlattenArray.m
▸ Compiling NSDateFormatter+EasyMappingAdditions.m
▸ Compiling Pods-EasyMapping-dummy.m
▸ Compiling EasyMapping_vers.c
▸ Linking EasyMapping
▸ Linking EasyMapping
▸ Generating 'EasyMapping.framework.dSYM'
▸ Copying EKCoreDataImporter.h
▸ Copying EKManagedObjectMapper.h
▸ Copying EKManagedObjectMapping.h
▸ Copying EKManagedObjectModel.h
▸ Copying EKMapper.h
▸ Copying EKMappingBlocks.h
▸ Copying EKMappingProtocol.h
▸ Copying EKObjectModel.h
▸ Copying EKObjectMapping.h
▸ Copying EKPropertyMapping.h
▸ Copying EKPropertyHelper.h
▸ Copying EKRelationshipMapping.h
▸ Copying EKSerializer.h
▸ Copying EasyMapping.h
▸ Copying NSDateFormatter+EasyMappingAdditions.h
▸ Copying NSArray+FlattenArray.h
▸ Copying Pods-EasyMapping-umbrella.h
▸ Touching EasyMapping.framework
▸ Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Intermediates/ArchiveIntermediates/ftol/IntermediateBuildFilesPath/UninstalledProducts/EasyMapping.framework
▸ Building Pods/Pods-Alamofire [Release]
▸ Processing Info.plist
** ARCHIVE FAILED **


The following build commands failed:
	CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Intermediates/ArchiveIntermediates/ftol/IntermediateBuildFilesPath/UninstalledProducts/Alamofire.framework
(1 failure)
▸ Compiling Pods-Alamofire-dummy.m
▸ Compiling Alamofire_vers.c
▸ Compiling Pods-Alamofire-dummy.m
▸ Compiling Alamofire_vers.c
▸ Linking Alamofire
▸ Linking Alamofire
▸ Generating 'Alamofire.framework.dSYM'
▸ Copying Pods-Alamofire-umbrella.h
▸ Touching Alamofire.framework
▸ Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/ftol-bzylruuslnhhledrwkjlnftibmev/Build/Intermediates/ArchiveIntermediates/ftol/IntermediateBuildFilesPath/UninstalledProducts/Alamofire.framework
[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/actions/ipa.rb:94:in `rescue in run': [31mA build error occured, this is usually related to code signing. Take a look at the error above[0m (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/actions/ipa.rb:66:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):32:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:36:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:29:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/runner.rb:29:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/bin/fastlane:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/bin/fastlane:128:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.6.0/bin/fastlane:134:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
[31m[00:17:57]: [0m[33mA build error occured. This can have many reasons, usually[0m
[31m[00:17:57]: [0m[33mit has something to do with code signing. The `ipa` action[0m
[31m[00:17:57]: [0m[33muses `shenzhen` under the hood: https://github.com/nomad/shenzhen[0m
[31m[00:17:57]: [0m[33mThe command that was used by fastlane:[0m
[31m[00:17:57]: [0m[33mkrausefx-ipa build -s "ftol" --verbose | xcpretty[0m
[31m[00:17:57]: [0m[33m-------------------------------------------------------[0m
[37m[00:17:57]: [0m[33mVariable Dump:[0m
[37m[00:17:57]: [0m{:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios ftol"}
[1m[31m[00:17:57]: [0m[0m[31mA build error occured, this is usually related to code signing. Take a look at the error above[0m
[1m[31m[00:17:58]: [0m[0m[31m fastlane finished with errors[0m
```

When I run "fastlane ftol" from jenkins user all is fine.

Thanx.

**Comment by KrauseFx** [comment]
As you can see in the output, it's a code signing issue. You can run `krausefx-ipa build -s "ftol" --verbose` to get the same result, which uses `shenzhen` and `xcodebuild` under the hood. That's all cause because you either run Jenkins as its own user or some profiles/certificates are missing. 

This is not an issue of `fastlane` itself.

**Comment by 3a4oT** [comment]
@KrauseFx thank you. I resolved it by removing *.mobileprovision from .gitignore. And I am not sure if it's the best solution, can you suggest something?. By the way, `krausefx-ipa build -s "ftol" --verbose` passed successfully from the local terminal via jenkins  user. Maybe I do not understand how it's works, I thought if it passed locally it should pass via ssh to.

**Comment by nklausni** [comment]
Having the same issue.
Running it locally as jenkins user works, but running as a jenkins process does not.

**Comment by dogo** [comment]
I was able to build using the jenkins user after add one step to unlock the keychain

![screen shot 2015-08-24 at 12 49 00 pm](https://cloud.githubusercontent.com/assets/1487375/9444718/a050cb4a-4a5e-11e5-8f98-e6252db49bbf.png)

**Comment by JaviSoto** [comment]
Hi @dogo!
I'm going to go ahead and close this issue for now since it's been inactive for a long time. Feel free to reply if the issue is still unresolved and we'd love to help you out!

**Comment by anmolnagpal** [comment]
Hi,

I'm getting below error.

```
[14:18:41]: fastlane finished with errors
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- gh_inspector (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:92:in `show_github_issues'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:43:in `rescue in run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:50:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:239:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.95.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by TKBurner** [comment]
Hi @anmolnagpal Thanks for reaching out. Can you submit a new issue for this. I want to make sure we get to the bottom of your issue. Thanks!

**Comment by KrauseFx** [comment]
@anmolnagpal Can you try updating your dependencies, just run `sudo gem update gh_inspector` or `bundle update` (if you use `bundler`) 🚀
