### ISSUE TITLE
Incorrect simulator version when running scan

### ISSUE THREAD

**Issue by TigerWolf** [fastlane/fastlane#3824]
### Issue Description

`fastlane test`

Sentry ID: e7e597a183bf4952b376efe6e0be73a3

When running `scan` - the build fails with:

`scan(scheme: "Development", device: "iPhone 6", sdk: "iphonesimulator9.2")`

```
▸ Build Succeeded
2016-03-18 10:15:44.847 xcodebuild[67206:4043334] [MT] IDETestOperationsObserverDebug: (D02C86DC-67F1-42E3-B904-F76E85BE76B9) Beginning test session D02C86DC-67F1-42E3-B904-F76E85BE76B9 with Xcode 7C1002 on target <DVTiPhoneSimulator: 0x7fb0b60a62c0> {
SimDevice: SimDevice : iPhone 6 (8C6A5111-48F9-4E80-B2F3-90B514434FE6) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6 } runtime={ SimRuntime : 8.1 (12B411) - com.apple.CoreSimulator.SimRuntime.iOS-8-1 }
} (8.1 (12B411))
xcodebuild: error: Failed to build workspace StudentAppiOS with scheme Development.
Reason: UI Testing is not supported on “iPhone 6” because it is running iOS Simulator 8.1 and UI Testing requires iOS Simulator 9.0 or later.
[10:15:44]: Exit status: 70
[10:15:46]: Successfully sent Slack notification
[10:15:46]: Variable Dump:
[10:15:46]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[10:15:46]: Error building/testing the application - see the log above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 25          |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | cocoapods                           | 14          |
| 5    | scan                                | 28          |
+------+-------------------------------------+-------------+

[10:15:46]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'e7e597a183bf4952b376efe6e0be73a3'
The crash report has been stored locally '/tmp/sentry_e7e597a183bf4952b376efe6e0be73a3.json'
/Users/a1673450/.rvm/gems/ruby-2.2.4@global/gems/scan-0.5.2/lib/scan/error_handler.rb:32:in `handle_build_error': [!] Error building/testing the application - see the log above (RuntimeError)
	from /Users/a1673450/.rvm/gems/ruby-2.2.4@global/gems/scan-0.5.2/lib/scan/runner.rb:31:in `block in test_app'
	from /Users/x/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.39.0/lib/fastlane_core/command_executor.rb:85:in `call'
	from /Users/x/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.39.0/lib/fastlane_core/command_executor.rb:85:in `execute'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/scan-0.5.2/lib/scan/runner.rb:23:in `test_app'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/scan-0.5.2/lib/scan/runner.rb:9:in `run'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/scan-0.5.2/lib/scan/manager.rb:10:in `work'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/actions/scan.rb:10:in `run'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:37:in `block (2 levels) in parsing_binding'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/x/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/bin/fastlane:156:in `run'
	from /Users/x/.rvm/gems/ruby-2.2.4@global/gems/fastlane-1.66.0/bin/fastlane:162:in `<top (required)>'
	from /Users/x/.rvm/rubies/ruby-2.2.4/bin/fastlane:23:in `load'
	from /Users/x/.rvm/rubies/ruby-2.2.4/bin/fastlane:23:in `<main>'
	from /Users/x/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/x/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

When adding: `destination: "platform=iOS Simulator,OS=9.2,name=iPhone 6"` - everything works correctly. 

```scan(scheme: "Development", device: "iPhone 6", sdk: "iphonesimulator9.2", destination: "platform=iOS Simulator,OS=9.2,name=iPhone 6") ```

It doesnt look like this is the correct appoach as I am warned about my workaround:

```
[10:18:05]: xcrun xcodebuild -list -workspace './StudentAppiOS.xcworkspace'
[10:18:07]: It's not recommended to set the `destination` value directly
[10:18:07]: Instead use the other options available in `scan --help`
[10:18:07]: Using your value 'platform=iOS Simulator,OS=9.2,name=iPhone 6' for now
[10:18:07]: because I trust you know what you're doing...
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Development", device: "iPhone 6", sdk: "iphonesimulator9.2") # , destination: "OS=9.2,name=iPhone 6"
  end

```

### Environment

fastlane version (fastlane -v):
 fastlane -v
fastlane 1.66.0

Do you use bundler, rbenv or rvm?
rvm
ruby 2.2.4p230

**Comment by vpolouchkine** [comment]
Can you please post the output of `instruments -s`?

**Comment by TigerWolf** [comment]
```
Known Devices:
Apple TV 1080p (9.1) [95317E2D-8B8F-4077-AE9D-070759B78C13]
iPad 2 (8.1) [D7F956A9-9D06-48A9-83F7-2236075DEF83]
iPad 2 (9.0) [E56841CA-7B83-4159-9036-D8C0FCEC5A71]
iPad 2 (9.2) [35172DBB-46BD-4FEF-B1CE-605F2F84CE3F]
iPad Air (8.1) [9CFEC8DE-13D4-45AB-89C7-6975D115930F]
iPad Air (9.0) [2FE71F50-208D-405A-A276-EC613C1D5C6A]
iPad Air (9.2) [A1633FF8-AA7F-4A68-BCF9-0821E39AB712]
iPad Air 2 (9.0) [EFFE1DF1-39B6-4196-9C4E-40CFBFC90E86]
iPad Air 2 (9.2) [2D0AF170-CCF5-4CDB-8C65-254AE49453F7]
iPad Pro (9.2) [CCD98FEB-82FD-46CF-BBA2-2C9CE320A5C6]
iPad Retina (8.1) [FB1ACF72-68EC-404C-858C-62F85EFC3ABB]
iPad Retina (9.0) [93956060-40A0-4F50-8AE9-8D9EBB2699EC]
iPad Retina (9.2) [61DA4790-8023-4354-9583-A2CCD6EA0E2F]
iPhone 4s (8.1) [D47F060F-829D-4633-8E26-9EEA887276C1]
iPhone 4s (9.0) [66EBAFC9-BFE3-45C8-BB72-38ABD4F11EA0]
iPhone 4s (9.2) [AF6D2B43-D190-4143-B02B-73F6954C8188]
iPhone 5 (8.1) [FDFF8BC7-AC90-4D72-899E-517C74D90901]
iPhone 5 (9.0) [009DA618-2719-4CD5-ACC5-F5792AA29680]
iPhone 5 (9.2) [AB176189-8F6E-4C39-961F-B7646D28699E]
iPhone 5s (8.1) [5FBD3EA0-C631-408F-A1E4-1DFEF7FAB0B0]
iPhone 5s (9.0) [B23490A9-1FBF-4CC2-A86B-4CDD496C45EB]
iPhone 5s (9.2) [9341003D-2FC4-4157-8386-0238848015C2]
iPhone 6 (8.1) [8C6A5111-48F9-4E80-B2F3-90B514434FE6]
iPhone 6 (9.0) [36312419-BECD-4DBB-927F-4215B2A31509]
iPhone 6 (9.2) [C7682B8E-0BCC-4AA6-94CE-04980B50A99E]
iPhone 6 Plus (8.1) [90EE7395-0415-42F1-82A6-38C595C685AB]
iPhone 6 Plus (9.0) [EE8F73D3-44EA-4221-B8BF-21AC4378B4D4]
iPhone 6 Plus (9.2) [D615170A-7FF9-4FB8-9A87-71DCE527359E]
iPhone 6s (9.0) [75AB12FE-3E2E-4A43-9056-DE588A2B6174]
iPhone 6s (9.2) [50181D34-5A96-4C4D-BC2C-B1512F719160]
iPhone 6s (9.2) + Apple Watch - 38mm (2.1) [E10E056F-C21B-472D-BE2B-D1147A1FF4F9]
iPhone 6s Plus (9.0) [B1D6BE5B-AC1A-42DD-89A7-09F107D78525]
iPhone 6s Plus (9.2) [24E9AFDC-05CA-4F50-B16C-5F9286415FEF]
iPhone 6s Plus (9.2) + Apple Watch - 42mm (2.1) [CA8AF26C-D7A9-437D-B184-AE56D9AA2C61]
Known Templates:
"Activity Monitor"
"Allocations"
"Automation"
"Blank"
"Cocoa Layout"
"Core Animation"
"Core Data"
"Counters"
"Energy Diagnostics"
"File Activity"
"GPU Driver"
"Leaks"
"Metal System Trace"
"Network"
"OpenGL ES Analysis"
"System Trace"
"System Usage"
"Time Profiler"
"Zombies"
```

**Comment by vpolouchkine** [comment]
What happens if you pass "iPhone 6 (9.2)" as `device`?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (485/400 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:42645)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKu7-002lqj-KT
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:39 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=V5qhsPlN1RqHrlPgmY8u++rQYZQ=; b=EhjgfQ3t6LaZWzLR
	csH7KJIE3ZCNOWJrYzcinPzE7YK4DXuFpdNUMvR8ffmQBMdxlviJy6qPNXb+MYOD
	QlJX6ibD4aC8ptlj844JVI4EzxgXHF0Bp6cYeVkE1cUUWsnfTLtzyBXG3mq81Wuj
	SQeCk+6DNEZ+m4IJIrziIM372as=
Received: by filter0617p1mdw1.sendgrid.net with SMTP id filter0617p1mdw1.32132.5765917B22
        2016-06-18 18:22:51.489439987 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id uMt-r1P2SyyQLpRwOl_2Dg
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:22:51.469 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:22:51 -0700

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (484/400 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:53822 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKu5-002lql-So
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:38 +0200
Date: Sat, 18 Jun 2016 11:22:52 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274172;
	bh=8XaiZlcmZ9aWLa37SF8WS+E1+RRN2isqD1QganOhLFQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=wWQfAHUiLsnawMaIMrufRFl93WmjGLUmWCljwWZJ9ZtNVx90YudQGqkZZUUaBxzUt
	 DqjWrmz4pWgKV0IsDaD3yksyj7+Z+kK9WJw9afN66pjhOPf67713c+wogaRzohE/W+
	 pwrjp01niILs2lcrz53uO4SVWMt0kT7IsqG9oM7g=

**Comment by calvinf** [comment]
Summarizing this issue for anybody who comes by later, run `instruments -s` from the command line to see the simulators you have available on your system and select one of those options to pass in as the "device" argument to `scan`.

```ruby
    lane :test do
        update_fastlane
        scan(
            scheme: "MyAppScheme",
            device: "iPhone 6s (9.3)",
        )
    end
```

If you're specifying the devices in your Snapfile or elsewhere, that part of the file would look like this:

```ruby
devices([
  "iPhone 6s (9.3)",
  "iPhone 6s Plus (9.3)",
  "iPhone 5s (9.3)",
  "iPhone 4s (9.3)",
])
```
