### ISSUE TITLE
I have a problem with snapshot 1.12.0.

### ISSUE THREAD

**Issue by longpham2310** [fastlane/fastlane#3874]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
All tests
Test Suite UITests.xctest started
UITests
✗ testExample, UI Testing Failure - Failed to perform AX action for monitoring the animations of <XCUIApplicationProcess: 0x7f9ed352a020  (37157)>, error: Error -25204 performing AXAction 2043

testExample, UI Testing Failure - Failed to perform AX action for monitoring the animations of <XCUIApplicationProcess: 0x7f9ed352a020 (37157)>, error: Error -25204 performing AXAction 2043
<unknown>:0
```
```


	 Executed 1 test, with 1 failure (0 unexpected) in 5.018 (5.022) seconds

[17:32:52]: Exit status: 65
[17:32:52]: Tests failed - check out the log above

+----------+---------+
|  snapshot results  |
+----------+---------+
| Device   | en-US   |
+----------+---------+
| iPhone 6 |  ❌      |
+----------+---------+

-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/snapshot-1.12.0/lib/snapshot/runner.rb:52:in `work': [!] Tests failed - check out the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.12.0/bin/snapshot:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.12.0/bin/snapshot:96:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.12.0/bin/snapshot:110:in `<top (required)>'
	from /usr/local/bin/snapshot:23:in `load'
	from /usr/local/bin/snapshot:23:in `<main>'
```

### Environment

fastlane version (fastlane -v): fastlane_version "1.66.0"
Do you use bundler, rbenv or rvm? No

**Comment by longpham2310** [comment]
The tests are success when I run by `Xcode` and xcodebuild.

**Comment by TKBurner** [comment]
Hi @longpham2310, great to hear from you! Can you send over the following information: https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md. 

I wanna take a look :+1:

**Comment by longpham2310** [comment]
Hi @TKBurner. I just update my issue. Can you have a look? Thanks!

**Comment by TKBurner** [comment]
@longpham2310 Thanks for following up. Are you still seeing this issue? Can you let me know what version of xCode you are using. We had an issue with Snapshot with 7.3.0 but pushed an update to snapshot yesterday.

Thanks!

**Comment by longpham2310** [comment]
@TKBurner .`xCode 7.3` , `snapshot 1.12.1`, `SnapshotHelper.swift` is latest. But this issue is still.

**Comment by TKBurner** [comment]
Hi @longpham2310 Can you send me the full output rather than just the error? I want to have a look at when this is happening. Thanks!

**Comment by longpham2310** [comment]
@TKBurner 
### console log:

```
Last login: Tue Mar 22 14:39:42 on ttys006
Long-Pham:~ longpham$ pwd
/Users/longpham
Long-Pham:~ longpham$ cd Projects/
Long-Pham:Projects longpham$ cd Test/
Long-Pham:Test longpham$ cd Test/
Long-Pham:Test longpham$ pwd
/Users/longpham/Projects/Test/Test
Long-Pham:Test longpham$ ls
ABOAuthCore			Test.xcodeproj
Flex				UITests
Font				TestEarlGreyUITests
GoogleSignIn.bundle		TestTests
GoogleSignIn.framework		TestUITests
HTTPServerCore			Stripe
Launch Screen.storyboard	Tests
NYSliderPopover			Vendor
NewRelic_iOS_Agent_3.324	X-Trace
PayPalMobile			build
PaymentKit			fastlane
Test				scripts
Long-Pham:Test longpham$ snapshot run
uninitialized constant CredentialsManager::AppfileConfig::Helper
uninitialized constant CredentialsManager::AppfileConfig::Helper
uninitialized constant CredentialsManager::AppfileConfig::Helper
[23:33:44]: xcrun xcodebuild -list -project './Test.xcodeproj'

+----------------------------+------------------------------------------------------+
|                            Summary for snapshot 1.12.1                            |
+----------------------------+------------------------------------------------------+
| devices                    | ["iPhone 6"]                                         |
| languages                  | ["en-US"]                                            |
| scheme                     | UITests                                |
| output_directory           | /Users/longpham/Projects/Test/Test/screenshots |
| project                    | ./Test.xcodeproj                                  |
| launch_arguments           | [""]                                                 |
| ios_version                | 9.3                                                  |
| skip_open_summary          | false                                                |
| clear_previous_screenshots | false                                                |
| reinstall_app              | false                                                |
| erase_simulator            | false                                                |
| buildlog_path              | ~/Library/Logs/snapshot                              |
| clean                      | false                                                |
| number_of_retries          | 0                                                    |
| stop_after_first_error     | false                                                |
+----------------------------+------------------------------------------------------+

[23:33:45]: Building and running project - this might take some time...
[23:33:46]: Patching '/Users/longpham/Library/Preferences/com.apple.iphonesimulator.plist' to scale simulator to 100%
[23:33:48]: ------------------------
[23:33:48]: --- iPhone 6 - en-US ---
[23:33:48]: ------------------------
[23:33:48]: $ set -o pipefail && xcodebuild -scheme 'UITests' -project './Test.xcodeproj' -derivedDataPath '/var/folders/61/g7f5drn54xq_hjgv1h10bzs80000gp/T/snapshot_derived20160323-72273-3gnz7r' -destination 'platform=iOS Simulator,id=0366915E-9EAC-4571-BD3B-9674B8091402,OS=9.3' build test | tee /Users/longpham/Library/Logs/snapshot/UITests-UITests.log | xcpretty 
[23:33:48]: ▸ Loading...

** TEST FAILED **

All tests
Test Suite UITests.xctest started
UITests
✗ testHomeScreen, UI Testing Failure - Failed to perform AX action for monitoring the animations of <XCUIApplicationProcess: 0x7f80f2c1c530 co.xxx.TestDev (75140)>, error: Error -25204 performing AXAction 2043


UITests.UITests
testHomeScreen, UI Testing Failure - Failed to perform AX action for monitoring the animations of <XCUIApplicationProcess: 0x7f80f2c1c530 co.xxx.TestDev (75140)>, error: Error -25204 performing AXAction 2043
<unknown>:0
```
```


	 Executed 1 test, with 1 failure (0 unexpected) in 6.908 (6.915) seconds

[23:37:42]: Exit status: 65
[23:37:42]: Tests failed - check out the log above

+----------+---------+
|  snapshot results  |
+----------+---------+
| Device   | en-US   |
+----------+---------+
| iPhone 6 |  ❌      |
+----------+---------+

-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/snapshot-1.12.1/lib/snapshot/runner.rb:52:in `work': [!] Tests failed - check out the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.12.1/bin/snapshot:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.12.1/bin/snapshot:96:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.12.1/bin/snapshot:110:in `<top (required)>'
	from /usr/local/bin/snapshot:23:in `load'
	from /usr/local/bin/snapshot:23:in `<main>'
Long-Pham:Test longpham$ 

```

### Snapshot logs file:

```
2016-03-23 23:37:33.764 XCTRunner[75138:4489718] Running tests...
23:37:33.991 XCTRunner[75138:4489748] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
23:37:33.998 XCTRunner[75138:4489748] _IDE_startExecutingTestPlanWithProtocolVersion:16
2016-03-23 23:37:34.382 XCTRunner[75138:4489718] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2016-03-23 23:37:34.984
Test Suite 'xxxUITests.xctest' started at 2016-03-23 23:37:34.985
Test Suite 'xxxUITests' started at 2016-03-23 23:37:34.986
Test Case '-[xxxUITests.xxxUITests testHomeScreen]' started.
    t =     0.00s     Start Test
    t =     0.00s     Set Up
    t =     0.05s         Launch co.xxx.xxxDev
2016-03-23 23:37:36.108 XCTRunner[75138:4489718] UIAccessibility Error adding -[DOMNode _moveRight:withHistory:]
2016-03-23 23:37:36.108 XCTRunner[75138:4489718] UIAccessibility Error adding -[DOMNode _moveLeft:withHistory:]
2016-03-23 23:37:36.108 XCTRunner[75138:4489718] UIAccessibility Error adding -[DOMNode _updateSelectionWithTextRange:withAffinityDownstream:]
2016-03-23 23:37:36.109 XCTRunner[75138:4489718] UIAccessibility Error adding +[DOMNode safeCategoryBaseClass]
2016-03-23 23:37:36.109 XCTRunner[75138:4489718] UIAccessibility Error adding -[UIWebFormAccessory initWithFrame:]
2016-03-23 23:37:36.109 XCTRunner[75138:4489718] UIAccessibility Error adding -[UIWebFormAccessory _accessibilityLoadAccessibilityInformation]
2016-03-23 23:37:36.109 XCTRunner[75138:4489718] UIAccessibility Error adding +[UIWebFormAccessory safeCategoryBaseClass]
2016-03-23 23:37:36.109 XCTRunner[75138:4489718] UIAccessibility Error adding +[UIWebFormSelectPeripheral createPeripheralWithDOMHTMLSelectElement:]
2016-03-23 23:37:36.110 XCTRunner[75138:4489718] UIAccessibility Error adding +[UIWebFormSelectPeripheral safeCategoryBaseClass]
2016-03-23 23:37:36.110 XCTRunner[75138:4489718] UIAccessibility Error adding -[UIWebSelectSinglePicker _accessibilityServesAsFirstElement]
2016-03-23 23:37:36.110 XCTRunner[75138:4489718] UIAccessibility Error adding +[UIWebSelectSinglePicker safeCategoryBaseClass]
2016-03-23 23:37:36.110 XCTRunner[75138:4489718] UIAccessibility Error adding -[UIWebSelectMultiplePicker _accessibilityServesAsFirstElement]
2016-03-23 23:37:36.111 XCTRunner[75138:4489718] UIAccessibility Error adding +[UIWebSelectMultiplePicker safeCategoryBaseClass]
2016-03-23 23:37:36.111 XCTRunner[75138:4489718] UIAccessibility Error adding -[UIWebPlugInView webPlugInStart]
2016-03-23 23:37:36.111 XCTRunner[75138:4489718] UIAccessibility Error adding +[UIWebPlugInView safeCategoryBaseClass]
    t =     3.76s             Waiting for accessibility to load
    t =     6.75s             Wait for app to idle
    t =     6.90s                 Assertion Failure: UI Testing Failure - Failed to perform AX action for monitoring the animations of <XCUIApplicationProcess: 0x7f80f2c1c530 co.xxx.xxxDev (75140)>, error: Error -25204 performing AXAction 2043
<unknown>:0: error: -[xxxUITests.xxxUITests testHomeScreen] : UI Testing Failure - Failed to perform AX action for monitoring the animations of <XCUIApplicationProcess: 0x7f80f2c1c530 co.xxx.xxxDev (75140)>, error: Error -25204 performing AXAction 2043
    t =     6.91s     Tear Down
Test Case '-[xxxUITests.xxxUITests testHomeScreen]' failed (6.908 seconds).
Test Suite 'xxxUITests' failed at 2016-03-23 23:37:41.897.
	 Executed 1 test, with 1 failure (0 unexpected) in 6.908 (6.911) seconds
Test Suite 'xxxUITests.xctest' failed at 2016-03-23 23:37:41.900.
	 Executed 1 test, with 1 failure (0 unexpected) in 6.908 (6.915) seconds
Test Suite 'All tests' failed at 2016-03-23 23:37:41.901.
	 Executed 1 test, with 1 failure (0 unexpected) in 6.908 (6.917) seconds
```

P/s: **The test is fine when I run by Xcode and command line tools.**

**Comment by TKBurner** [comment]
Thanks for following up! Can you reset your simulator data? That seems like it should fix this. I found similar issues reported here, https://forums.developer.apple.com/thread/4472

**Comment by longpham2310** [comment]
I did reset the simulator and clean ~DeliverData but the problem can't be solved.

**Comment by TKBurner** [comment]
Hi @longpham2310. Thanks for following up. It seems like this is related to 

Failed to perform AX action for monitoring the animations

This seems like it is a failure of your UI test. Can you run your UI test and send me the results?

Thanks!

Also check out this article for some context

http://stackoverflow.com/questions/32002330/ios-9-ui-testing-test-fails-because-target-control-isnt-available-yet

**Comment by longpham2310** [comment]
@TKBurner My test is very simple. 
```
func testHomeScreen() {
     snapshot("Welcome_01")
}

```

**Comment by TKBurner** [comment]
@longpham2310 Hi there, can you close and reopen xCode? I found other reports of users affected by this issue on Twitter. This seems like an issue with your session in xCode and rebooting it will fix this.

**Comment by barbaramartina** [comment]
I just want to mention I did run into the same issue while trying to solve another one. 
I was getting the log:  
**`Assertion Failure: UI Testing Failure - Failure getting list of active applications: AX error -25205`**  
Nor resetting the simulator, nor restarting XCode helped in my case.  
I debugged a while and if I removed the line where I was calling `tap()`, the error disappeared.  I still don't know exactly why.  

![screen shot 2016-05-18 at 12 33 39 pm](https://cloud.githubusercontent.com/assets/815372/15356042/989823b0-1cf6-11e6-80fe-bf3b2104338a.png)

**Comment by andertsk** [comment]
@barbaramartina Have the same problem in UI Testing with just tap() function

**Comment by TKBurner** [comment]
Hi @andertsk Thanks for following up. Do you still see this issue if you remove the tap function? Thanks!

**Comment by andertsk** [comment]
Hi @TKBurner thanks for reply, if i remove the tap function the problem is disappears.

**Comment by pghiraldelli** [comment]
@TKBurner @andertsk I'm having the same problem! Did you get any solution?

**Comment by TKBurner** [comment]
@andertsk Thanks for following up on this. Can you open a new issue so we can track it? Make sure fill out the full template. Thanks!

**Comment by suculent** [comment]
This is a XCTest issue. UIImageView is not a button:

```
extension XCUIElement {
    func forceTapElement() {
        if self.hittable {
            self.tap()
        }
        else {
            let coordinate: XCUICoordinate = self.coordinateWithNormalizedOffset(CGVectorMake(0.5, 0.5))
            coordinate.tap()
        }
    }
}
```
