### ISSUE TITLE
Cannot build app build missing extension error

### ISSUE THREAD

**Issue by aliHafizji** [fastlane/fastlane#389]
Below is the error I get while building the app with fastlane. 

```
[02:55:58]: -----------------
[02:55:58]: --- Step: ipa ---
[02:55:58]: -----------------


[02:56:04]: [SHELL]: 2015-07-07 02:56:04.415 xcodebuild[91363:3436280] [MT] DVTAssertions: Warning in /SourceCache/IDEFrameworks/IDEFrameworks-7720/IDEFoundation/SourceControl/Model/IDESourceControlManager.m:423
[02:56:04]: [SHELL]: Details:  Error Domain=com.apple.dt.IDESourceControlErrorDomain Code=-1 "Missing extension: public.vcs.subversion" UserInfo=0x7f96cc367bd0 {NSLocalizedDescription=Missing extension: public.vcs.subversion}
[02:56:04]: [SHELL]: Object:   <IDESourceControlManager: 0x7f96caf83850>
[02:56:04]: [SHELL]: Method:   -loadRepositories
[02:56:04]: [SHELL]: Thread:   <NSThread: 0x7f96c86225c0>{number = 1, name = main}
[02:56:04]: [SHELL]: Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
^C/Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/actions/actions_helper.rb:88:in `each': Interrupt
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/actions/actions_helper.rb:88:in `block in sh_no_action'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/actions/actions_helper.rb:87:in `popen'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/actions/actions_helper.rb:87:in `sh_no_action'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/actions/actions_helper.rb:72:in `sh'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/actions/ipa.rb:67:in `run'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):17:in `block (3 levels) in parse'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/runner.rb:39:in `call'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/runner.rb:39:in `block in execute'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/runner.rb:29:in `chdir'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/runner.rb:29:in `execute'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/bin/fastlane:39:in `block (2 levels) in run'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/bin/fastlane:128:in `run'
	from /Users/kauserali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.7.0/bin/fastlane:134:in `<top (required)>'
	from /Users/kauserali/.rbenv/versions/2.2.2/bin/fastlane:23:in `load'
	from /Users/kauserali/.rbenv/versions/2.2.2/bin/fastlane:23:in `<main>'
```

Any ideas what is going on here. All the schemes are marked shares. The app has 4 share extensions (however I don't see that being a problem)

@KrauseFx Any idea what the could be wrong?

**Comment by KrauseFx** [comment]
Can you try building yourself using `krausefx-ipa build -s "Scheme" --verbose` and see what's wrong? Also, you can pipe the output to `| xcpretty` to actually see relevant information.

**Comment by KrauseFx** [comment]
Any updates on this @aliHafizji

**Comment by JaviSoto** [comment]
I'm going to go ahead and close this issue for now since it's been inactive for a long time. Feel free to reply if you'd still like to get some help with this and we'll reopen it!
