### ISSUE TITLE
[match] Crash 9eb46651239f6ef77e8ea35d73c9bc17

### ISSUE THREAD

**Issue by retsohuang** [fastlane/fastlane#3897]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

fastlane finished with errors after run `bundle exec match development` on readonly mode.

##### Complete output when running fastlane, including the stack trace and command used

```
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '9eb46651239f6ef77e8ea35d73c9bc17'
The crash report has been stored locally '/tmp/sentry_9eb46651239f6ef77e8ea35d73c9bc17.json'
/Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/interface.rb:120:in `crash!': [!] No code signing identity found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneCrash)
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/match-0.4.0/lib/match/runner.rb:48:in `certificate'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/match-0.4.0/lib/match/runner.rb:17:in `run'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/actions/match.rb:11:in `run'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:40:in `block (2 levels) in parsing_binding'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/bin/fastlane:156:in `run'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1@global/gems/fastlane-1.67.0/bin/fastlane:162:in `<top (required)>'
	from /Users/retsohuang/.rvm/rubies/ruby-2.1.1/bin/fastlane:23:in `load'
	from /Users/retsohuang/.rvm/rubies/ruby-2.1.1/bin/fastlane:23:in `<main>'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/retsohuang/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
nothing
```

### Environment

fastlane version (fastlane -v): 1.67.0
Do you use bundler, rbenv or rvm? bundler

**Comment by KrauseFx** [comment]
The error message says 
```
No code signing identity found and can not create a new one because you enabled `readonly` 
```

**Comment by KrauseFx** [comment]
Do you have the code signing identity for development in your git repo in match?

**Comment by retsohuang** [comment]
No, that is new repo.

I have another crash when I use new account (The error message says no device id in there).

**Comment by KrauseFx** [comment]
So that's why you have to run `match` with `readonly` mode disabled, otherwise it can't create a new certificate
