### ISSUE TITLE
SecurityException: Permission android.permission.CHANGE_CONFIGURATION

### ISSUE THREAD

**Issue by iamapo** [fastlane/fastlane#3909]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I got an error when screengrab granting the permission android.permission.CHANGE_CONFIGURATION on Android 6.
On a Device with Android 4.4 it works fine.

##### Complete output when running fastlane, including the stack trace and command used

▸ java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[12:13:17]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:41)
[12:13:17]: ▸ at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:35)
[12:13:17]: ▸ at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[12:13:17]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[12:13:17]: ▸ at org.junit.runners.Suite.runChild(Suite.java:128)
[12:13:17]: ▸ at org.junit.runners.Suite.runChild(Suite.java:27)
[12:13:17]: ▸ at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[12:13:17]: ▸ at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[12:13:17]: ▸ at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[12:13:17]: ▸ at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[12:13:17]: ▸ at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[12:13:17]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[12:13:17]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[12:13:17]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[12:13:17]: ▸ at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
[12:13:17]: ▸ at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
[12:13:17]: ▸ at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
[12:13:17]: ▸ Caused by: java.lang.reflect.InvocationTargetException
[12:13:17]: ▸ at java.lang.reflect.Method.invoke(Native Method)
[12:13:17]: ▸ at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:36)
[12:13:17]: ▸ ... 16 more
[12:13:17]: ▸ Caused by: java.lang.SecurityException: Permission Denial: updateConfiguration() from pid=5598, uid=10351 requires android.permission.CHANGE_CONFIGURATION
[12:13:17]: ▸ at android.os.Parcel.readException(Parcel.java:1599)
[12:13:17]: ▸ at android.os.Parcel.readException(Parcel.java:1552)
[12:13:17]: ▸ at android.app.ActivityManagerProxy.updateConfiguration(ActivityManagerNative.java:3935)
[12:13:17]: ▸ ... 18 more
[12:13:17]: ▸ 2) Test mechanism
[12:13:17]: ▸ java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.putString(java.lang.String, java.lang.String)' on a null object reference
[12:13:17]: ▸ at android.support.test.internal.runner.listener.InstrumentationResultPrinter.reportFailure(InstrumentationResultPrinter.java:177)
[12:13:17]: ▸ at android.support.test.internal.runner.listener.InstrumentationResultPrinter.testFailure(InstrumentationResultPrinter.java:167)
[12:13:17]: ▸ at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:63)
[12:13:17]: ▸ at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:142)
[12:13:17]: ▸ at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
[12:13:17]: ▸ at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:138)
[12:13:17]: ▸ at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:132)
[12:13:17]: ▸ at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
[12:13:17]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:369)
[12:13:17]: ▸ at org.junit.runners.Suite.runChild(Suite.java:128)
[12:13:17]: ▸ at org.junit.runners.Suite.runChild(Suite.java:27)
[12:13:17]: ▸ at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[12:13:17]: ▸ at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[12:13:17]: ▸ at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[12:13:17]: ▸ at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[12:13:17]: ▸ at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[12:13:17]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[12:13:17]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[12:13:17]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[12:13:17]: ▸ at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
[12:13:17]: ▸ at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
[12:13:17]: ▸ at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
[12:13:17]: ▸ FAILURES!!!
[12:13:17]: ▸ Tests run: 0,  Failures: 2

### Environment

screengrab version (0.3.1):
Android 6

**Comment by TKBurner** [comment]
Hi @iamapo! CHANGE_CONFIGURATION requires for your app either to be signed by the firmware signing key or be installed on a system partition. You can see this by examining the framework manifest, where these permissions are defined. Can you take a look at your project?

**Comment by asfalcone** [comment]
@iamapo Just wanted to make sure you've followed the [manifest permissions](https://github.com/fastlane/fastlane/tree/master/screengrab#configuring-your-manifest-permissions) section of the setup guide.

**Comment by iamapo** [comment]
When i unsignd my app it works. This works for me

**Comment by TKBurner** [comment]
@iamapo Thanks for letting us know :+1:
