### ISSUE TITLE
ipa step fails

### ISSUE THREAD

**Issue by jmesmith** [fastlane/fastlane#394]
Hi,
I'm trying to get fastlane set up. It keeps failing on the ipa step. I've tried specifying a number of keys in the ipa command but nothing I do seems to help. I've looked over the guide and the examples and I'm having trouble wrapping my mind around what could be going wrong. Any help is much appreciated.

Here are the relevant lines in my Fastfile:

``` Ruby
 before_all do

  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # snapshot
    ipa(scheme: "Beta")
    sigh
    deliver(skip_deploy: true, beta: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
```

and here is the output:

```
fastlane beta
[13:06:45]: -------------------------------------------------
[13:06:45]: --- Step: Verifying required fastlane version ---
[13:06:45]: -------------------------------------------------
[13:06:45]: fastlane version valid
[13:06:45]: ------------------------------
[13:06:45]: --- Step: default_platform ---
[13:06:45]: ------------------------------
[13:06:45]: Driving the lane 'ios beta'
[13:06:45]: ------------------
[13:06:45]: --- Step: sigh ---
[13:06:45]: ------------------
[13:06:45]: Starting login
[13:06:45]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: my username
Multiple teams found, please enter the number of the team you want to use: 
2
[13:06:57]: Successfully logged in
[13:06:57]: Fetching profiles...
[13:06:57]: To not be asked about this value, you can specify it using 'app_identifier'
The bundle identifier of your app: com.myrealapp.identifier
[13:07:10]: Found 1 matching profile(s)
[13:07:10]: Downloading provisioning profile...
[13:07:11]: Successfully downloaded provisioning profile...
[13:07:11]: Installing provisioning profile...
[13:07:11]: Provisioning profile of app 'App Name' with the name 'App Name App Store 6/19' successfully analysed.
[13:07:11]: Profile successfully installed
./AppStore_com.myrealapp.identifier.mobileprovision
[13:07:11]: -----------------
[13:07:11]: --- Step: ipa ---
[13:07:11]: -----------------
[13:07:11]: set -o pipefail && krausefx-ipa build -s "Beta" -m "/Users/james/Documents/dev/ios/teeps/ArcKinect/AppStore_com.auto.lync.mobileprovision" | xcpretty
[13:07:11]: [SHELL COMMAND]: set -o pipefail && krausefx-ipa build -s "Beta" -m "/Users/james/Documents/dev/ios/teeps/ArcKinect/AppStore_com.auto.lync.mobileprovision" | xcpretty
```

It seems to get stuck on the last step

**Comment by KrauseFx** [comment]
So it doesn't really fail, but just hangs there? 

Can you try running 

```
krausefx-ipa build -s "Beta" -m "/Users/james/Documents/dev/ios/teeps/ArcKinect/AppStore_com.auto.lync.mobileprovision" 
```

and see what happens?

**Comment by jmesmith** [comment]
I managed to get an error eventually:

-----------------
[14:02:15]: --- Step: ipa ---
[14:02:15]: -----------------
[14:02:15]: set -o pipefail && krausefx-ipa build -s "Beta" | xcpretty
[14:02:15]: [SHELL COMMAND]: set -o pipefail && krausefx-ipa build -s "Beta" | xcpretty
[14:14:29]: [SHELL]: cp: /Users/james/Library/Developer/Xcode/DerivedData/ArcKinect-hirdjmhmvcrxgqdhzxevuxbjltkt/Build/Products/Beta Testing-iphoneos/ArcKinect.app.dSYM: No such file or directory
[14:14:29]: -------------------------------------------------------
[14:14:29]: Original Error:
[14:14:29]:  => Exit status of command 'set -o pipefail && krausefx-ipa build -s "Beta" | xcpretty' was 256 instead of 0. 
cp: /Users/james/Library/Developer/Xcode/DerivedData/ArcKinect-hirdjmhmvcrxgqdhzxevuxbjltkt/Build/Products/Beta Testing-iphoneos/ArcKinect.app.dSYM: No such file or directory

[14:14:29]: A build error occured. This can have many reasons, usually
[14:14:29]: it has something to do with code signing. The `ipa` action
[14:14:29]: uses `shenzhen` under the hood: https://github.com/nomad/shenzhen
[14:14:29]: The command that was used by fastlane:
[14:14:29]: krausefx-ipa build -s "Beta" | xcpretty
[14:14:29]: -------------------------------------------------------
[14:14:29]: Variable Dump:
[14:14:29]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios internal"}
[14:14:29]: A build error occured, this is usually related to code signing. Take a look at the error above
[14:14:30]: fastlane finished with errors
/Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/actions/ipa.rb:94:in `rescue in run': A build error occured, this is usually related to code signing. Take a look at the error above (RuntimeError)
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/actions/ipa.rb:66:in `run'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):39:in `block (3 levels) in parse'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/runner.rb:39:in `call'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/runner.rb:39:in `block in execute'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/runner.rb:29:in `chdir'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/runner.rb:29:in `execute'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/bin/fastlane:39:in `block (2 levels) in run'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/bin/fastlane:128:in `run'
	from /Users/james/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.7.0/bin/fastlane:134:in `<top (required)>'
	from /Users/james/.rvm/rubies/ruby-2.1.5/bin/fastlane:23:in `load'
	from /Users/james/.rvm/rubies/ruby-2.1.5/bin/fastlane:23:in `<main>'
	from /Users/james/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/james/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'


I have your snippet running right now and I'll post another comment with the result when it's finished

**Comment by jmesmith** [comment]
Your snippet produced the ipa successfully

**Comment by jmesmith** [comment]
Here's the output in case it's useful:

```
james:ArcKinect james$ krausefx-ipa build -s "Beta" -m "/Users/james/Documents/dev/ios/teeps/ArcKinect/AppStore_com.auto.lync.mobileprovision"
Configuration was not passed, defaulting to Debug
     xcodebuild  ArcKinect.xcodeproj
          xcrun  PackageApplication
            zip 
/Users/james/Documents/dev/ios/teeps/ArcKinect/Arc
Kinect.app.dSYM
~/Documents/dev/ios/teeps/ArcKinect ~/Documents/dev/ios/teeps/ArcKinect
~/Documents/dev/ios/teeps/ArcKinect
Successfully built:
/Users/james/Documents/dev/ios/teeps/ArcKinect/ArcKine
ct.ipa
```

**Comment by KrauseFx** [comment]
What was the issue and how did you fix it?

**Comment by KrauseFx** [comment]
Or does it only work when you run it yourself without `fastlane`?

**Comment by jmesmith** [comment]
Yeah it only worked when I used 

krausefx-ipa build -s "Beta" -m "/Users/james/Documents/dev/ios/teeps/ArcKinect/AppStore_com.auto.lync.mobileprovision".

**Comment by kreeger** [comment]
I'm getting a very similar error as well — fails on the `ipa` step. It works if I roll `fastlane` back to 1.6.0. I'm firing off a build of our app right now (to meet a deadline) but I'll edit my comment with the relevant backtrace (and what happens if I run `krausefx-ipa` by itself, too).

**Comment by a1cooke** [comment]
I am using Travis and the build hangs and eventually Travis aborts the build.

When I run it locally it works great.

@KrauseFx any thoughts?

**Comment by a1cooke** [comment]
In my case the issue was I had to specify the following in my .travis.yml file
`osx_image: xcode6.4`

By default Travis CI is using XCode 6.1

**Comment by jondot** [comment]
I have bumped into this as well. This happens when you have several `xcworkspace`s in the hosting folder, or a scheme that is not guessable.
In this case krausfx-ipa will ask a terminal question about the scheme or workspace and hang.

**Comment by kreeger** [comment]
For whatever it's worth, my project now builds just fine under v1.13.0!

**Comment by tomassliz** [comment]
I had the same problem. I had to specify configuration name too and everything is ok now.

**Comment by Froelund** [comment]
I encountered this exact issue. When the fastlane tools got to the ipa step, it just got stuck.
I fixed this by making my Scheme shared
Xcode -> Product -> Scheme -> Manage Schemes...

**Comment by KrauseFx** [comment]
Also, check out the new project [gym](https://github.com/fastlane/gym) which makes building much easier :+1:

**Comment by JaviSoto** [comment]
I'm going to go ahead and close this issue for now since it's been inactive for a long time. We hope that this got better thanks to `gym`, but feel free to reply if you'd still like to get some help with this and we'll reopen it!
