### ISSUE TITLE
increment_build_number broken with Ruby 2.2.4, Gem 2.4.8, fastlane 1.68.0

### ISSUE THREAD

**Issue by wkoszek** [fastlane/fastlane#3945]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I tried the newest `fastlane`, but it had many problems, so I'm describing something that has indication of working: fresh OSX El Captain + `rvm`/ruby 2.3.0 + `gem install fastlane` + `gem install cocoapods`. This combination can build & push my app to Crashlytics Beta with no problem, as long as I comment `increment_build_version`. With it commented out I'm getting:

```
[00:51:31]: ------------------------------------
[00:51:31]: --- Step: increment_build_number ---
[00:51:31]: ------------------------------------
[00:51:31]: $ cd /w/repos/sensorama-ios/Sensorama && agvtool next-version -all
[00:51:32]: ▸ There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.
[00:51:32]: Make sure to follow the steps to setup your Xcode project: https://developer.apple.com/library/ios/qa/qa1827/_index.html
Error happened![00:51:32]: Variable Dump:
[00:51:32]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :SIGH_PROFILE_TYPE=>"development", :SIGH_PROFILE_PATH=>"/w/repos/sensorama-ios/Sensorama/Development_com.koszek.Sensorama.mobileprovision", :SIGH_PROFILE_PATHS=>["/w/repos/sensorama-ios/Sensorama/Development_com.koszek.Sensorama.mobileprovision"], :SIGH_UDID=>"c13526b4-a9e1-4ce8-97de-879e8a376922"}
[00:51:32]: Exit status of command 'cd /w/repos/sensorama-ios/Sensorama && agvtool next-version -all' was 6 instead of 0.
There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.
```

##### Complete output when running fastlane, including the stack trace and command used

```
bash-3.2$ ./build.sh
[00:50:58]: -------------------------------------------------
[00:50:58]: --- Step: Verifying required fastlane version ---
[00:50:58]: -------------------------------------------------
[00:50:58]: fastlane version valid
[00:50:58]: ------------------------------
[00:50:58]: --- Step: default_platform ---
[00:50:58]: ------------------------------
[00:50:58]: Driving the lane 'ios beta' 🚀
[00:50:58]: -----------------------
[00:50:58]: --- Step: cocoapods ---
[00:50:58]: -----------------------
[00:50:58]: $ pod install
[00:50:59]: ▸ Updating local specs repositories
[00:51:01]: ▸ CocoaPods 1.0.0.beta.6 is available.
[00:51:01]: ▸ To update use: `sudo gem install cocoapods --pre`
[00:51:01]: ▸ [!] This is a test version we'd love you to try.
[00:51:01]: ▸ For more information see http://blog.cocoapods.org
[00:51:01]: ▸ and the CHANGELOG for this version http://git.io/BaH8pQ.
[00:51:01]: ▸ Analyzing dependencies
[00:51:03]: ▸ Downloading dependencies
[00:51:03]: ▸ Using AFNetworking (2.6.3)
[00:51:03]: ▸ Using AWSCognito (2.3.5)
[00:51:03]: ▸ Using AWSCore (2.3.5)
[00:51:03]: ▸ Using AWSS3 (2.3.5)
[00:51:03]: ▸ Using CocoaLumberjack (2.2.0)
[00:51:03]: ▸ Using Crashlytics (3.7.0)
[00:51:03]: ▸ Using Fabric (1.6.7)
[00:51:03]: ▸ Using JWTDecode (1.0.0)
[00:51:03]: ▸ Using Lock (1.22.0)
[00:51:03]: ▸ Using SimpleKeychain (0.7.0)
[00:51:03]: ▸ Generating Pods project
[00:51:06]: ▸ Integrating client project
[00:51:07]: ▸ Sending stats
[00:51:07]: ▸ Pod installation complete! There are 8 dependencies from the Podfile and 10 total pods installed.
[00:51:07]: --------------------------------------
[00:51:07]: --- Step: Switch to ios certs lane ---
[00:51:07]: --------------------------------------
[00:51:07]: Cruising over to lane 'ios certs' 🚖
[00:51:07]: -------------------
[00:51:07]: --- Step: slack ---
[00:51:07]: -------------------
[00:51:07]: Successfully sent Slack notification
[00:51:07]: -------------------
[00:51:07]: --- Step: match ---
[00:51:07]: -------------------

+-----------------------+-------------------------------------+
|                   Summary for match 0.4.0                   |
+-----------------------+-------------------------------------+
| app_identifier        | com.koszek.Sensorama                |
| type                  | development                         |
| git_url               | git@gitlab.com:wkoszek/appstore.git |
| force                 | true                                |
| username              | wkoszek@freebsd.org                 |
| keychain_name         | login.keychain                      |
| readonly              | false                               |
| team_id               | QQ5A9Q7C7Z                          |
| verbose               | false                               |
| shallow_clone         | false                               |
| force_for_new_devices | false                               |
| skip_docs             | false                               |
+-----------------------+-------------------------------------+

[00:51:08]: Cloning remote git repo...
[00:51:13]: 🔓  Successfully decrypted certificates repo
[00:51:13]: Verifying that the certificate and profile are still valid on the Dev Portal...
[00:51:14]: Installing certificate...

+-------------------------------------+----------------------------------------+
|                            Summary for sigh 1.6.0                            |
+-------------------------------------+----------------------------------------+
| app_identifier                      | com.koszek.Sensorama                   |
| adhoc                               | false                                  |
| development                         | true                                   |
| username                            | wkoszek@freebsd.org                    |
| force                               | true                                   |
| cert_id                             | B359A98SX2                             |
| provisioning_name                   | match Development com.koszek.Sensorama |
| ignore_profiles_with_different_name | true                                   |
| skip_install                        | false                                  |
| team_id                             | QQ5A9Q7C7Z                             |
| skip_fetch_profiles                 | false                                  |
| skip_certificate_verification       | false                                  |
+-------------------------------------+----------------------------------------+

[00:51:15]: Starting login with user 'wkoszek@freebsd.org'
[00:51:16]: Successfully logged in
[00:51:16]: Fetching profiles...
[00:51:16]: Found 1 matching profile(s)
[00:51:16]: Updating the profile to include all devices
[00:51:17]: Downloading provisioning profile...
[00:51:17]: Successfully downloaded provisioning profile...
[00:51:17]: Installing provisioning profile...
/var/folders/k6/sc44c8rd4xz0ckyl1g5ykwz40000gq/T/d20160326-86608-1s7mn9i/profiles/development/Development_com.koszek.Sensorama.mobileprovision
[00:51:17]: Installing provisioning profile...
[00:51:17]: 🔒  Successfully encrypted certificates repo
[00:51:17]: Pushing changes to remote git repo...

+----------------------+---------------------------------------+
|                Installed Provisioning Profile                |
+----------------------+---------------------------------------+
| App Identifier       | com.koszek.Sensorama                  |
| Type                 | development                           |
| UUID                 | c13526b4-a9e1-4ce8-97de-879e8a376922  |
| Environment Variable | sigh_com.koszek.Sensorama_development |
+----------------------+---------------------------------------+

[00:51:30]: All required keys, certificates and provisioning profiles are installed 🙌
[00:51:30]: Setting Provisioning Profile type to 'development'
[00:51:30]: Cruising back to lane 'ios beta' 🚘
[00:51:30]: ------------------
[00:51:30]: --- Step: sigh ---
[00:51:30]: ------------------

+-------------------------------------+----------------------+
|                   Summary for sigh 1.6.0                   |
+-------------------------------------+----------------------+
| development                         | true                 |
| adhoc                               | false                |
| skip_install                        | false                |
| force                               | false                |
| app_identifier                      | com.koszek.Sensorama |
| username                            | wkoszek@freebsd.org  |
| team_id                             | QQ5A9Q7C7Z           |
| ignore_profiles_with_different_name | false                |
| skip_fetch_profiles                 | false                |
| skip_certificate_verification       | false                |
+-------------------------------------+----------------------+

[00:51:30]: Starting login with user 'wkoszek@freebsd.org'
[00:51:30]: Successfully logged in
[00:51:30]: Fetching profiles...
[00:51:31]: Found 1 matching profile(s)
[00:51:31]: Downloading provisioning profile...
[00:51:31]: Successfully downloaded provisioning profile...
[00:51:31]: Installing provisioning profile...
/w/repos/sensorama-ios/Sensorama/Development_com.koszek.Sensorama.mobileprovision
[00:51:31]: Setting Provisioning Profile type to 'development'
[00:51:31]: ------------------------------------
[00:51:31]: --- Step: increment_build_number ---
[00:51:31]: ------------------------------------
[00:51:31]: $ cd /w/repos/sensorama-ios/Sensorama && agvtool next-version -all
[00:51:32]: ▸ There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.
[00:51:32]: Make sure to follow the steps to setup your Xcode project: https://developer.apple.com/library/ios/qa/qa1827/_index.html
Error happened![00:51:32]: Variable Dump:
[00:51:32]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :SIGH_PROFILE_TYPE=>"development", :SIGH_PROFILE_PATH=>"/w/repos/sensorama-ios/Sensorama/Development_com.koszek.Sensorama.mobileprovision", :SIGH_PROFILE_PATHS=>["/w/repos/sensorama-ios/Sensorama/Development_com.koszek.Sensorama.mobileprovision"], :SIGH_UDID=>"c13526b4-a9e1-4ce8-97de-879e8a376922"}
[00:51:32]: Exit status of command 'cd /w/repos/sensorama-ios/Sensorama && agvtool next-version -all' was 6 instead of 0.
There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.



+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 8           |
| 4    | Switch to ios certs lane            | 0           |
| 5    | slack                               | 0           |
| 6    | match                               | 22          |
| 7    | sigh                                | 1           |
| 8    | increment_build_number              | 0           |
+------+-------------------------------------+-------------+

[00:51:32]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '3c13335dbe24cd498e16eb7f34beacbc'
The crash report has been stored locally '/tmp/sentry_3c13335dbe24cd498e16eb7f34beacbc.json'
/Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/interface.rb:120:in `crash!': [!] Exit status of command 'cd /w/repos/sensorama-ios/Sensorama && agvtool next-version -all' was 6 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.


	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/actions/increment_build_number.rb:36:in `run'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:67:in `block (2 levels) in parsing_binding'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/bin/fastlane:156:in `run'
	from /Users/wk/.rvm/gems/ruby-2.2.4/gems/fastlane-1.68.0/bin/fastlane:162:in `<top (required)>'
	from /Users/wk/.rvm/gems/ruby-2.2.4/bin/fastlane:23:in `load'
	from /Users/wk/.rvm/gems/ruby-2.2.4/bin/fastlane:23:in `<main>'
	from /Users/wk/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/wk/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# vim: ai ts=2 sts=2 et sw=2 ft=ruby
fastlane_version "1.52.0"

default_platform :ios

def build_app
  gym(
    workspace: "Sensorama.xcworkspace",
    scheme: "Sensorama"
  )
end

platform :ios do
  before_all do
    cocoapods
  end

  desc "Installs FixCode which disables the \"Fix Issue\" button in Xcode"
  lane :xcode do
    install_xcode_plugin(
      url: "https://github.com/fastlane/FixCode/releases/download/0.2.0/FixCode.xcplugin.zip"
    )
  end

  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    slack(message: "certs", success: true)
    match(
      app_identifier: "com.koszek.Sensorama",
      type: "development",
      git_url: ENV['FASTLANE_GIT_URL'],
      force: true
    )
  end

  lane :appmake do
    slack(message: "appmake", success: true)
    produce(
       username: 'wkoszek@freebsd.org',
       app_identifier: 'com.koszek.Sensorama',
       app_name: 'Sensorama',
       language: 'English',
       app_version: '1.0',
       skip_itc: true,
     )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Deliver to Crashlytics"
  lane :crashlytics_beta do
    crashlytics(
       api_token: ENV['FABRIC_API_KEY'],
       build_secret:  ENV['FABRIC_BUILD_SECRET'],
       groups: 'sensorama-testers'
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    certs
    sigh(development: true)
    increment_build_number
    build_app
    #deliver
    crashlytics_beta
    frameit
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Sensorama") # Build your app - more options available
    deliver(force: true)
  end

  after_all do |lane|
    print "after lane #{lane}"
  end

  error do |lane, exception|
    print "Error happened!"
  end
end
```

### Environment

```
bash-3.2$ pod --version
0.39.0
bash-3.2$ gem -v
2.4.8
bash-3.2$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
bash-3.2$ which ruby
/Users/wk/.rvm/rubies/ruby-2.2.4/bin/ruby
bash-3.2$ which ge,
bash-3.2$ which gem
/Users/wk/.rvm/rubies/ruby-2.2.4/bin/gem
bash-3.2$ which pod
/Users/wk/.rvm/gems/ruby-2.2.4/bin/pod
```

**Comment by wkoszek** [comment]
When I comment the `increment_build_number` out, it works fine.

**Comment by MickeyHub** [comment]
did you [set up your Xcode project](https://developer.apple.com/library/ios/qa/qa1827/_index.html) first?

**Comment by wkoszek** [comment]
@MickeyHub Yes. I've been successfully using `fastlane` before I reinstalled my environment, and incrementing project number worked without an issue. After the reinstallation this error from the top showed up.

My screenshot:
![image](https://cloud.githubusercontent.com/assets/483344/14061589/0a0bbb5e-f341-11e5-81c1-0307508a9d7c.png)

**Comment by kcharwood** [comment]
I wonder if this is related to [this issue](https://github.com/fastlane/fastlane/issues/3877#issuecomment-201107122)?

**Comment by MickeyHub** [comment]
thx @kcharwood, both `CocoaPods` & `fastlane` depend `xcodeproj` gem, and `CocoaPods v0.39` restricts its mini version to 0.28.2, CocoaPods v1.0.0.beta6 restricts its mini version to 1.0.0.beta3 while `fastlane v1.68.0` restrict its to 0.20, so the original issue is attributed to `xcodeproj` gem, maybe fastlane should update the restriction for `xcodeproj`'s mini version.

**Comment by i2amsam** [comment]
@MickeyHub thanks for this table :+1: !  It looks like we might be in a bind here, we can't update our dependency because then we'd be in conflict with `CocoaPods 0.39` could you try updating to `CocoaPods 1.0.0.beta6` and `xcodeproj 1.0.0.beta.3` and seeing if that solves the problem?  If so, [this might be the issue to follow](https://github.com/CocoaPods/Xcodeproj/pull/356).

**Comment by Sega-Zero** [comment]
Is there any way to fix that without upgrading cocoapods? Cannot upgrade to 1.0.0.beta6 because of [this](https://github.com/CocoaPods/CocoaPods/issues/5082) bug.

**Comment by ffittschen** [comment]
@Sega-Zero If the bug you mentioned is not related to the `xcodeproj` gem, you could try upgrading only that one: `gem update xcodeproj --pre`

**Comment by Sega-Zero** [comment]
Should I also uninstall old (0.28.2) version? just upgrading a gem doesn't fixed an issue for me.
> $ gem update xcodeproj --pre
Updating installed gems
Updating xcodeproj
Fetching: claide-1.0.0.beta.3.gem (100%)
Successfully installed claide-1.0.0.beta.3
Fetching: xcodeproj-1.0.0.beta.3.gem (100%)
Successfully installed xcodeproj-1.0.0.beta.3
Parsing documentation for claide-1.0.0.beta.3
Installing ri documentation for claide-1.0.0.beta.3
Installing darkfish documentation for claide-1.0.0.beta.3
Parsing documentation for xcodeproj-1.0.0.beta.3
Installing ri documentation for xcodeproj-1.0.0.beta.3
Installing darkfish documentation for xcodeproj-1.0.0.beta.3
Done installing documentation for claide, xcodeproj after 11 seconds
Parsing documentation for claide-1.0.0.beta.3
Parsing documentation for xcodeproj-1.0.0.beta.3
Done installing documentation for claide, xcodeproj after 3 seconds
Gems updated: claide xcodeproj

> [19:04:52]: --------------------------------------
[19:04:52]: --- Step: increment_version_number ---
[19:04:52]: --------------------------------------
> [19:05:00]: $ cd /Users/travis/build/company/iOS/Project && agvtool new-marketing-version 1.6.807
[19:05:00]: ▸ Setting CFBundleShortVersionString of project Project to:
[19:05:00]: ▸ 1.6.807.
[19:05:00]: ▸ Updating CFBundleShortVersionString in Info.plist(s)...
[19:05:00]: ▸ Cannot find "Project/../				<key>INFOPLIST_FILE</key>"
> [19:05:00]: ------------------------------------
[19:05:00]: --- Step: increment_build_number ---
> [19:05:00]: ------------------------------------
[19:05:00]: $ cd /Users/travis/build/company/iOS/Project && agvtool new-version -all 1.6.807
[19:05:01]: ▸ Setting version of project Project to:
[19:05:01]: ▸ 1.6.807.
[19:05:01]: ▸ Also setting CFBundleVersion key (assuming it exists)
[19:05:01]: ▸ Updating CFBundleVersion in Info.plist(s)...
[19:05:01]: ▸ Cannot find "Project.xcodeproj/../				<key>INFOPLIST_FILE</key>"

**Comment by ffittschen** [comment]
@Sega-Zero Thats why I edited my post and wrote, that you need to specify the `1.0.0.beta.3` version in your `Gemfile`.

**Comment by Sega-Zero** [comment]
`gem 'xcodeproj', '>= 1.0.0.beta.3'` in my Gemfile did resolved the issue! Thank you!

**Comment by TKBurner** [comment]
@Sega-Zero Glad to hear you are up and running! I'm going to close this out but we'll keep looking into long term versioning issues. Thanks! :+1:
