### ISSUE TITLE
Error running upload_symbols_to_crashlytics

### ISSUE THREAD

**Issue by NachoSoto** [fastlane/fastlane#3951]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Running `upload_symbols_to_crashlytics` (after `download_dsyms`) fails.

##### Complete output when running fastlane, including the stack trace and command used
`fastlane symbols`

```
$ fastlane symbols
[18:38:16]: -------------------------------------------
[18:38:16]: --- Step: upload_symbols_to_crashlytics ---
[18:38:16]: -------------------------------------------
[18:38:16]: invalid byte sequence in UTF-8
[18:38:16]: Unable to find plist file at '_________/Carthage/Build/iOS/AsyncImageView.framework/Info.plist'
[18:38:16]: Variable Dump:
[18:38:16]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"symbols", :DSYM_PATHS=>[a bunch of files]}
[18:38:16]: undefined method `[]' for true:TrueClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | download_dsyms                      | 166         |
| 4    | upload_symbols_to_crashlytics       | 0           |
+------+-------------------------------------+-------------+

[18:38:16]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:12:in `block in run': [!] undefined method `[]' for true:TrueClass (NoMethodError)
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:9:in `each'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:9:in `run'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:71:in `block in parsing_binding'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/bin/fastlane:156:in `run'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0@global/gems/fastlane-1.68.0/bin/fastlane:162:in `<top (required)>'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0/bin/fastlane:23:in `load'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0/bin/fastlane:23:in `<main>'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/NachoSoto/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
desc "Upload symbols to Crashlytics"
lane :symbols do
  download_dsyms
  upload_symbols_to_crashlytics
end
```

### Environment

- fastlane version (`fastlane -v`): `fastlane 1.68.0`.
- Using `ram`.

### Other details

I don't understand the error `Unable to find plist file at '_________/Carthage/Build/iOS/AsyncImageView.framework/Info.plist'`. The file IS there:
<img width="838" alt="screen shot 2016-03-27 at 18 44 06" src="https://cloud.githubusercontent.com/assets/685609/14069217/eecf3e0e-f44b-11e5-8d01-7aa8fe5d2bd4.png">

I also don't understand why that's necessary for this?

**Comment by TKBurner** [comment]
@NachoSoto Thanks for reaching out! What happens if you delete and regenerate that info.plist? If you open the file itself is it of the expected format?

Thanks!

**Comment by NachoSoto** [comment]
Regenerating would mean I need to recompile the framework... but why would I need to do that? the `dSYM`s I downloaded are for whatever frameworks and versions I shipped with that particular version of the app.

[The file](https://github.com/NachoSoto/AsyncImageView/releases/tag/v0.1) is correct, yes.

**Comment by KrauseFx** [comment]
Thanks @NachoSoto, working on a fix now :+1:
