### ISSUE TITLE
incompatible character encoding error when using cocoapods 1.0.0

### ISSUE THREAD

**Issue by mborsten** [fastlane/fastlane#3969]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
> Compiling RealmSwift-dummy.m
> Linking RealmSwift
> Copying RealmSwift-umbrella.h
> Touching RealmSwift.framework
> Building Pods/Pods-Wildcard [Debug]
> Check Dependencies
> Processing Info.plist
> Compiling Pods-Wildcard-dummy.m
> Copying Pods-Wildcard-umbrella.h
> Touching Pods_Wildcard.framework
> Building Wildcard/Wildcard [Debug]
> Check Dependencies
> Running script '📦 Check Pods Manifest.lock'
incompatible character encodings: ASCII-8BIT and UTF-8
[11:56:38]: Variable Dump:
[11:56:38]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[11:56:38]: Error building/testing the application - see the log above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 4           |
| 4    | scan                                | 41          |
+------+-------------------------------------+-------------+

[11:56:38]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan/error_handler.rb:32:in `handle_build_error': [!] Error building/testing the application - see the log above (RuntimeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan/runner.rb:31:in `block in test_app'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.0/lib/fastlane_core/command_executor.rb:72:in `rescue in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.0/lib/fastlane_core/command_executor.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan/runner.rb:23:in `test_app'
	from /usr/local/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan/runner.rb:9:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan/manager.rb:10:in `work'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/actions/scan.rb:10:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:19:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/bin/fastlane:38:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/bin/fastlane:156:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.68.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.68.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean
    increment_build_number
    git_commit(path: "./", message: "changed build nr")
    gym(scheme: "Wildcard", use_legacy_build_api: true) # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    gym(scheme: "Wildcard") # Build your app - more options available
    deliver(force: true)
  end


  after_all do |lane|
  end

  error do |lane, exception|
  end
end
```

### Environment

fastlane version (fastlane -v): 1.68.0
bundler

### Description

When using cocoapods version 1.0.0-beta*, the pods gem adds build phases starting with a '📦' character.:

📦 Check Pods Manifest.lock
📦 Embed Pods Frameworks
📦 Copy Pods Resources

This results in the following error when running fastlane:

> Running script '📦 Check Pods Manifest.lock'
incompatible character encodings: ASCII-8BIT and UTF-8

If I remove the first character of the three different build phases that cocoapods adds, the script works fine.

**Comment by TKBurner** [comment]
Hi @mborsten! Hope you are doing well! Can you let me know exactly what commands you are running? Please reformat using this template: https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md

We really want to look into this! :+1:

**Comment by mborsten** [comment]
I've updated the issue

**Comment by TKBurner** [comment]
@mborsten Thanks for following up. We are going to look into this :+1:

**Comment by nicolasbraun** [comment]
I think this a been corrected by CP in 1.0.1

**Comment by KrauseFx** [comment]
Great to hear 👍

**Comment by mborsten** [comment]
I can confirm this is no longer a problem with CP 1.0.1
