### ISSUE TITLE
No json request was provided in the payload. (1269)

### ISSUE THREAD

**Issue by besi** [fastlane/fastlane#397]
I did follow these steps to upload an app to iTunes Testflight:

- I created a new project in Xcode
- I create the app in iTunes Connect using the bundle identifier
- I update the Deliveryfile
- I updated the Fastfile `ios.beta` lane:

        cert()
        sigh(adhoc: true)
        ipa(scheme: "WIReframeStudies")
        deliver(beta: true)

Now when I run `fastlane beta` I get the following error:

````bash
[17:07:15]: [Transporter Error Output]: No json request was provided in the payload. (1269)
[17:07:15]: [Transporter]: DBG-X: The error code is: 1269
[17:07:15]: [Transporter]: INFO: Done performing authentication.
[17:07:15]: Transporter transfer failed.
[17:07:15]: 
[17:07:15]: No json request was provided in the payload. (1269)
[17:07:15]: Return status of iTunes Transporter was 1: No json request was provided in the payload. (1269)
[17:07:15]: No json request was provided in the payload. (1269)
Return status of iTunes Transporter was 1: No json request was provided in the payload. (1269)
[17:07:15]: Variable Dump:
[17:07:15]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :CERT_FILE_PATH=>"/tmp/cert/xxxxxx-xxxxxx.cer", :CERT_CERTIFICATE_ID=>"xxxxxxx", :SIGH_PROFILE_PATH=>"/Users/me/MyProject/other_projects/MyProjecteframeStudies/AdHoc_com.forcklabs.MyProject.mobileprovision", :SIGH_UDID=>"1c2f-4503-b4cc-6c271c76e2b6", :IPA_OUTPUT_PATH=>"/Users/me/MyProject/other_projects/MyProject/MyProject.ipa", :DSYM_OUTPUT_PATH=>"/Users/me/MyProject/other_projects/MyProject/MyProject.app.dSYM.zip"}
[17:07:15]: Error uploading ipa file
[17:07:15]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:385:in `trigger_ipa_upload': Error uploading ipa file (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:48:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:133:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/actions/deliver.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/actions/deliver.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):49:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/runner.rb:39:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/runner.rb:39:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/runner.rb:29:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/runner.rb:29:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/bin/fastlane:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/bin/fastlane:128:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.0/bin/fastlane:134:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
````

**Comment by mikeandike** [comment]
Any update about this? 

I got the same error

**Comment by kylejm** [comment]
I too just got this error after upgrading to 1.27.0

**Comment by kylejm** [comment]
It's working again now though, after another try. ¯\_(ツ)_/¯

**Comment by rvi** [comment]
Just got this error while submitting my with Xcode. It appears randomly as said kylejm. It's not related to fastlane, this issue can be close.

**Comment by hash3r** [comment]
Some people said it helps to remove excessive certificates in keychains or select Standard architecture for both project and target.
Really weird and non-verbose error (

**Comment by JaviSoto** [comment]
Hey!
I'm going through some old issues to check up on them. Is this still happening to you folks? Thanks!

**Comment by kylejm** [comment]
I had it once a week or so ago, but didn't pay attention to what version I was on etc. Sorry! :weary:

**Comment by anton-matosov** [comment]
I had exact same error with Xcode manual upload. Simply resubmitting the same archive worked fine. 
So it is iTunes Connect issue, not fastlane tools.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
