### ISSUE TITLE
Screengrab doesn't work on Android N preview

### ISSUE THREAD

**Issue by martinfreeletics** [fastlane/fastlane#3981]
### Issue Description

I tried to run screengrab on a Nexus 6P with the Android N preview and screengrab crashes when trying to get the Context from the view. This is basically caused by 
```
Activity activity = this.scanForActivity(view.getContext());
if(activity == null) {
     throw new IllegalStateException("Couldn\'t get the activity from the view context");
}        
```
Maybe this is just a early preview problem, but on devices prior N the same tests work fine.

##### Stacktrace

```
java.lang.IllegalStateException: Couldn't get the activity from the view context
at tools.fastlane.screengrab.Screengrab$1.perform(Screengrab.java:81)
at android.support.test.espresso.ViewInteraction$1.run(ViewInteraction.java:144)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5849)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:763)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
```

### Environment

Screengrab version: 0.3.1

**Comment by TKBurner** [comment]
Thanks for reaching out @martinfreeletics! We haven't tested on Android N yet, but the team will look into this. We'll update on this thread :+1:

**Comment by mfurtak** [comment]
Hi @martinfreeletics - Thanks for the report :+1: 

I've reproduced this locally, and there seems to be many things to work out before this can start working. I don't have an ETA right now, but we'll track progress through this ticket. :rocket:

**Comment by matis11** [comment]
Problem still occurs on Android N - tested on Nexus 6P

**Comment by TKBurner** [comment]
@matis11 Thanks for following up on this. Can you run screengrab and share the full output? I definitely want to have to team take a look! Thanks!

**Comment by matis11** [comment]
@TKBurner Sure

For:
`Screengrab.screenshot("HereWasCustomName");`

Output is:
`java.lang.IllegalStateException: Couldn't get the activity from the view context
at tools.fastlane.screengrab.Screengrab$1.perform(Screengrab.java:81)
at android.support.test.espresso.ViewInteraction$1.run(ViewInteraction.java:144)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6044)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by TKBurner** [comment]
Hi! Thanks for following up with that. I'm going to mark this as a feature request, until there is a general release I'm not sure if the team will be able to prioritize. Thanks!

**Comment by mfurtak** [comment]
Hi all - I am working on a solution with #5621. If folks have time to help give it a try once it is on master, that'd be much appreciated! 👍

**Comment by mfurtak** [comment]
Hi folks, the changes from #5621 are now on master. If you have time to give it a try, that would be amazing.

The [README](https://github.com/fastlane/fastlane/tree/master/screengrab#improved-screenshot-capture-with-ui-automator) has more info about how enable the UiAutomator strategy, but note that v0.5.0 hasn't been released yet.
