### ISSUE TITLE
Deliver: Crash after "Activating language en-EN"

### ISSUE THREAD

**Issue by oskarn97** [fastlane/fastlane#4001]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Deliver crashes after "Activating language en-EN..."

##### Complete output when running fastlane, including the stack trace and command used

```

INFO [2016-03-31 18:21:44.91]: Making sure the latest version on iTunes Connect matches '1.0' from the ipa file...
INFO [2016-03-31 18:21:46.37]: '1.0' is the latest version on iTunes Connect
INFO [2016-03-31 18:21:47.59]: Activating language en-EN...
/Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	There are one or more errors on the page.
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/tunes/tunes_client.rb:358:in `block in update_app_version!'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/tunes/tunes_client.rb:870:in `with_tunes_retry'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/tunes/tunes_client.rb:351:in `update_app_version!'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/tunes/app_version.rb:275:in `save!'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.10.5/lib/deliver/upload_metadata.rb:130:in `verify_available_languages!'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.10.5/lib/deliver/upload_metadata.rb:22:in `upload'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.10.5/lib/deliver/runner.rb:58:in `upload_metadata'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.10.5/lib/deliver/runner.rb:21:in `run'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.10.5/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.10.5/lib/deliver/commands_generator.rb:132:in `run'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.10.5/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/Oskar/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.10.5/bin/deliver:5:in `<top (required)>'
	from /Users/Oskar/.rbenv/versions/2.2.3/bin/deliver:23:in `load'
	from /Users/Oskar/.rbenv/versions/2.2.3/bin/deliver:23:in `<main>'
```

**Comment by TKBurner** [comment]
@oskarn97 Thanks for reaching out. I wanted to know if this previously worked or if this is your first time setting up Deliver. Thanks!

**Comment by oskarn97** [comment]
Hi! It worked previously.

**Comment by vpolouchkine** [comment]
Can you please share your Deliverfile and Fastfile?

**Comment by oskarn97** [comment]
Solved it, was related due to "en-EN" being a wrong language code.

**Comment by TKBurner** [comment]
@oskarn97 Glad to hear you are up and running! Thanks for using Fastlane :+1:
