### ISSUE TITLE
Screengrab doesn't work with core 0.41

### ISSUE THREAD

**Issue by lucasvanhalst** [fastlane/fastlane#4008]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Screengrab crashes with fastlane core 0.41. Worked fine with core 0.38. 
But since Supply broke with core 0.38 I had to update it.
##### Command used
```
screengrab --app_package_name com.mobicage.rogerthat.em.be.az.damiaan --use_tests_in_packages com.mobicage.rogerthat.test.screenshots --clear_previous_screenshots --app_apk_path /home/jenkins/datajenkins/workspace/Android-1-App.rogerthat.build/android/rogerthat/build/outputs/apk/rogerthat-debug.apk --tests_apk_path /home/jenkins/datajenkins/workspace/Android-1-App.rogerthat.build/android/rogerthat/build/outputs/apk/rogerthat-debug-androidTest-unaligned.apk --locales nl-NL --device_type phone
```
##### Output
```
+-----------------------------+--------------------------------------------------------------------+
|                                   [32mSummary for screengrab 0.3.1[0m                                   |
+-----------------------------+--------------------------------------------------------------------+
| app_package_name            | com.mobicage.rogerthat.em.be.az.damiaan                            |
| use_tests_in_packages       | ["com.mobicage.rogerthat.test.screenshots"]                        |
| clear_previous_screenshots  | true                                                               |
| app_apk_path                | /home/jenkins/datajenkins/workspace/Android-1-App.rogerthat.bui... |
| tests_apk_path              | /home/jenkins/datajenkins/workspace/Android-1-App.rogerthat.bui... |
| locales                     | ["nl-NL"]                                                          |
| device_type                 | phone                                                              |
| tests_package_name          | com.mobicage.rogerthat.em.be.az.damiaan.test                       |
| output_directory            | fastlane/metadata/android                                          |
| skip_open_summary           | true                                                               |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner                     |
| ending_locale               | en-US                                                              |
+-----------------------------+--------------------------------------------------------------------+

[20:13:16]: Clearing phoneScreenshots within fastlane/metadata/android
[20:13:16]: [4m[36m$ adb devices -l[0m[0m
[20:13:16]: ▸ [35mList of devices attached[0m
[20:13:16]: ▸ [35m9885b645443150314e     device usb:1-2 product:hero2ltexx model:SM_G935F device:hero2lte[0m

ERROR:root:/var/lib/gems/2.1.0/gems/fastlane_core-0.41.0/lib/fastlane_core/crash_reporting/crash_reporting.rb:6:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)
	from /var/lib/gems/2.1.0/gems/fastlane_core-0.41.0/lib/fastlane_core/crash_reporting/crash_reporting.rb:6:in `file_path'
	from /var/lib/gems/2.1.0/gems/fastlane_core-0.41.0/lib/fastlane_core/crash_reporting/crash_reporting.rb:22:in `enabled?'
	from /var/lib/gems/2.1.0/gems/fastlane_core-0.41.0/lib/fastlane_core/crash_reporting/crash_reporting.rb:51:in `handle_crash'
	from /var/lib/gems/2.1.0/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:57:in `handle_unknown_error!'
	from /var/lib/gems/2.1.0/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:41:in `rescue in run!'
	from /var/lib/gems/2.1.0/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:22:in `run!'
	from /var/lib/gems/2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.1.0/gems/screengrab-0.3.1/bin/screengrab:56:in `run'
	from /var/lib/gems/2.1.0/gems/screengrab-0.3.1/bin/screengrab:62:in `<top (required)>'
	from /usr/local/bin/screengrab:22:in `load'
	from /usr/local/bin/screengrab:22:in `<main>'
```

### Environment

Fastlane core 0.41
Screengrab 0.3.1
Ubuntu 15.10
Ruby 2.1.5p273

**Comment by TKBurner** [comment]
@lvh1 Thanks for reporting this. We are going to have a look :+1:

**Comment by mfurtak** [comment]
Hi @lvh1 - thanks for the report! :+1: 

I don't think anything around this has changed recently. This stack trace indicates trouble that is occurring while attempting to report a different crash that is in progress!

The error is basically saying that you don't have a `HOME` variable set in the environment in which you are executing Ruby. Can you execute your command again, except prefix it with `HOME=/home/username` (replace your username) and add `--verbose` to the end of your command?

If you can run that, I'm hopeful that we'll see the problem that is causing this problem! :dart:

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.

**Comment by lucasvanhalst** [comment]
Oh right, totally forgot about this. It was probably my fault after all -- I was starting screengrab from a python script, and the `HOME` variable was probably not set in that environment.
