### ISSUE TITLE
Undefined method 'length' for nil:NilClass running supply

### ISSUE THREAD

**Issue by barriosnahuel** [fastlane/fastlane#4009]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

NoMethodError while trying to upload an APK to the alpha group: supply.rb:12:in `run': [31m[!] undefined method `length' for nil:NilClass

Note that with 1.68.0 I was able to upload the APK to the alpha group without any problems.

##### Complete output when running fastlane, including the stack trace and command used

```
[19:25:16]: [32m--------------------[0m
[19:25:16]: [32m--- Step: supply ---[0m
[19:25:16]: [32m--------------------[0m
[31mAppfile: DEPRECATED issuer: use json_key_file instead[0m
[31mAppfile: DEPRECATED keyfile: use json_key_file instead[0m
[31mAppfile: DEPRECATED issuer: use json_key_file instead[0m
[31mAppfile: DEPRECATED keyfile: use json_key_file instead[0m
[31mAppfile: DEPRECATED issuer: use json_key_file instead[0m
[31mAppfile: DEPRECATED keyfile: use json_key_file instead[0m
[31mAppfile: DEPRECATED issuer: use json_key_file instead[0m
[31mAppfile: DEPRECATED keyfile: use json_key_file instead[0m
[19:25:16]: [33mDEPRECATED --issuer OPTION. Use --json_key instead[0m
[31mAppfile: DEPRECATED issuer: use json_key_file instead[0m
[31mAppfile: DEPRECATED keyfile: use json_key_file instead[0m
[31mAppfile: DEPRECATED issuer: use json_key_file instead[0m
[31mAppfile: DEPRECATED keyfile: use json_key_file instead[0m
[19:25:16]: [33m[33mVariable Dump:[0m[0m
[19:25:16]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android alpha"}
[19:25:16]: [31mundefined method `length' for nil:NilClass[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 3           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | gradle                              | 23          |
| 5    | supply                              | 0           |
+------+-------------------------------------+-------------+

[19:25:16]: [31mfastlane finished with errors[0m
[33m-------------------------------------------------------------------------------------------[0m
[33mðŸ˜¨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.[0m
[33mðŸ‘  This makes resolving issues much easier and helps improve fastlane.[0m
[33mðŸ”’  The reports will be stored securely on getsentry.com.[0m
[33mðŸ™Š  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3[0m
[33m-------------------------------------------------------------------------------------------[0m
/home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/actions/supply.rb:12:in `run': [31m[!] undefined method `length' for nil:NilClass[0m (NoMethodError)
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/runner.rb:128:in `chdir'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:31:in `block (2 levels) in parsing_binding'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/lane.rb:36:in `call'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/lane.rb:36:in `call'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/runner.rb:46:in `chdir'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/runner.rb:46:in `execute'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/bin/fastlane:38:in `block (2 levels) in run'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/bin/fastlane:156:in `run'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fastlane-1.69.0/bin/fastlane:162:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bin/fastlane:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bin/fastlane:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'

travis_time:end:0086a51f:start=1459452269284197210,finish=1459452316737232867,duration=47453035657
[0Ktravis_fold:end:after_success
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
#!/bin/sh

gem install fastlane

fastlane alpha branch:$TRAVIS_BRANCH
```

### Environment

fastlane version (fastlane -v): 1.69.0
Do you use bundler, rbenv or rvm?

**Comment by barriosnahuel** [comment]
Closing because #4010 has more information about the issue
