### ISSUE TITLE
upload_symbols_to_crashlytics invalid byte sequence

### ISSUE THREAD

**Issue by jorystiefel** [fastlane/fastlane#4027]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Crash report: 41632663b2d44758677821fa59882787
This error happens on several machines.

##### Complete output when running fastlane, including the stack trace and command used

```
stiefel-OSX:appletv-99u stiefel$ fastlane refresh_dsyms
[11:34:01]: Driving the lane 'refresh_dsyms' 🚀
[11:34:01]: -----------------------------
[11:34:01]: --- Step: update_fastlane ---
[11:34:01]: -----------------------------
[11:34:01]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, match, pem, pilot, produce, scan, screengrab, sigh, snapshot, spaceship, supply...
[11:34:05]: Nothing to update ✅
[11:34:05]: ----------------------------
[11:34:05]: --- Step: download_dsyms ---
[11:34:05]: ----------------------------
[11:34:05]: Login to iTunes Connect (redacted@gmail.com)
[11:34:08]: Login successful
[11:34:08]: Looking for dSYM files for com.behance.99u
[11:34:09]: -------------------------------------------
[11:34:09]: --- Step: upload_symbols_to_crashlytics ---
[11:34:09]: -------------------------------------------
[11:34:09]: invalid byte sequence in UTF-8
[11:34:09]: Unable to find plist file at '/Users/stiefel/Developer/appletv-99u/appletv-99u/Crashlytics.framework/Info.plist'
[11:34:09]: invalid byte sequence in UTF-8
[11:34:09]: Unable to find plist file at '/Users/stiefel/Developer/appletv-99u/appletv-99u/Fabric.framework/Info.plist'
[11:34:09]: -----------------------------------
[11:34:09]: --- Step: clean_build_artifacts ---
[11:34:09]: -----------------------------------
[11:34:09]: Cleaned up build artifacts 🐙
[11:34:09]: Variable Dump:
[11:34:09]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"refresh_dsyms", :GET_INFO_PLIST_VALUE_CUSTOM_VALUE=>nil}
[11:34:09]: no implicit conversion of nil into String

+------+-------------------------------+-------------+
|                  fastlane summary                  |
+------+-------------------------------+-------------+
| Step | Action                        | Time (in s) |
+------+-------------------------------+-------------+
| 1    | update_fastlane               | 3           |
| 2    | download_dsyms                | 3           |
| 3    | upload_symbols_to_crashlytics | 0           |
| 4    | clean_build_artifacts         | 0           |
+------+-------------------------------+-------------+

[11:34:09]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '41632663b2d44758677821fa59882787'
The crash report has been stored locally '/tmp/sentry_41632663b2d44758677821fa59882787.json'
/Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:20:in `expand_path': [!] no implicit conversion of nil into String (TypeError)
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:20:in `block in run'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:20:in `collect'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:20:in `run'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:13:in `block in parsing_binding'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/stiefel/.gems/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/bin/fastlane:156:in `run'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :refresh_dsyms do
  unlock_keychain(
    path: "redacted",
    password: "redacted"
  )

  download_dsyms
  upload_symbols_to_crashlytics(binary_path: "./appletv-99u/Crashlytics.framework/uploadDSYM")
end
```

### Environment

fastlane version (fastlane -v): fastlane 1.70.0
Do you use bundler, rbenv or ram? No

```
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export FASTLANE_XCODE_LIST_TIMEOUT=60
```

**Comment by jorystiefel** [comment]
This happens on several machines I've tried. Both the of the plist files mentioned above do exist, despite the message `Unable to find plist file`

**Comment by KrauseFx** [comment]
@jorystiefel Can you try passing your Crashlytics API token using
```ruby
upload_symbols_to_crashlytics (api_token: "insert token here")
```

**Comment by jorystiefel** [comment]
@KrauseFx certainly, I did that, and got this error. Basically the same, but no longer complains about plist files or UTF-8

```
stiefel-OSX:appletv-99u stiefel$ fastlane refresh_dsyms
[14:52:22]: Driving the lane 'refresh_dsyms' 🚀
[14:52:22]: -----------------------------
[14:52:22]: --- Step: update_fastlane ---
[14:52:22]: -----------------------------
[14:52:22]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, match, pem, pilot, produce, scan, screengrab, sigh, snapshot, spaceship, supply...
[14:52:26]: Nothing to update ✅
[14:52:26]: -----------------------------
[14:52:26]: --- Step: unlock_keychain ---
[14:52:26]: -----------------------------
[14:52:26]: ----------------------------
[14:52:26]: --- Step: download_dsyms ---
[14:52:26]: ----------------------------
[14:52:26]: Login to iTunes Connect (redacted@gmail.com)
[14:52:28]: Login successful
[14:52:28]: Looking for dSYM files for com.behance.99u
[14:52:29]: -------------------------------------------
[14:52:29]: --- Step: upload_symbols_to_crashlytics ---
[14:52:29]: -------------------------------------------
[14:52:29]: -----------------------------------
[14:52:29]: --- Step: clean_build_artifacts ---
[14:52:29]: -----------------------------------
[14:52:29]: Cleaned up build artifacts 🐙
[14:52:29]: Variable Dump:
[14:52:29]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"refresh_dsyms"}
[14:52:29]: no implicit conversion of nil into String

+------+-------------------------------+-------------+
|                  fastlane summary                  |
+------+-------------------------------+-------------+
| Step | Action                        | Time (in s) |
+------+-------------------------------+-------------+
| 1    | update_fastlane               | 3           |
| 2    | unlock_keychain               | 0           |
| 3    | download_dsyms                | 3           |
| 4    | upload_symbols_to_crashlytics | 0           |
| 5    | clean_build_artifacts         | 0           |
+------+-------------------------------+-------------+

[14:52:29]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '5152d627ee35286e58ac36dff6d0e20e'
The crash report has been stored locally '/tmp/sentry_5152d627ee35286e58ac36dff6d0e20e.json'
/Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:20:in `expand_path': [!] no implicit conversion of nil into String (TypeError)
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:20:in `block in run'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:20:in `collect'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:20:in `run'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:18:in `block in parsing_binding'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/stiefel/.gems/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/bin/fastlane:156:in `run'
	from /Users/stiefel/.gems/gems/fastlane-1.70.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
stiefel-OSX:appletv-99u stiefel$ 
```

**Comment by KrauseFx** [comment]
Great, thanks, that helps! I'll push a fix. Basically you don't have any dSYM files to be uploaded:
```
[14:52:26]: ----------------------------
[14:52:26]: --- Step: download_dsyms ---
[14:52:26]: ----------------------------
[14:52:26]: Login to iTunes Connect (redacted@gmail.com)
[14:52:28]: Login successful
[14:52:28]: Looking for dSYM files for com.behance.99u
[14:52:29]: -------------------------------------------
```
I'll not only fix the crash, but also have a better messaging. This basically means that your app didn't get recompiled by Apple yet

**Comment by jorystiefel** [comment]
Awesome, thanks Felix! 👍

**Comment by KrauseFx** [comment]
Just pushed https://github.com/fastlane/fastlane/pull/4031, this will be in the next release :+1:

**Comment by jorystiefel** [comment]
I do not believe the update fixed the issue. The script no longer crashes, but there are a bunch of error messages and then it says it was successful.

Notice it still says it is unable to find those two .plist files even though they do exist at those paths. I wonder if it is because these are binary plist files, not XML.

When I log into iTunes Connect, I can download the dSYMs, so they definitely exist.

```
[10:20:45]: ----------------------------
[10:20:45]: --- Step: download_dsyms ---
[10:20:45]: ----------------------------
[10:20:45]: Login to iTunes Connect (redacted@gmail.com)
[10:20:50]: Login successful
[10:20:50]: Looking for dSYM files for com.redacted
[10:20:51]: No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet
[10:20:51]: -------------------------------------------
[10:20:51]: --- Step: upload_symbols_to_crashlytics ---
[10:20:51]: -------------------------------------------
[10:20:51]: invalid byte sequence in UTF-8
[10:20:51]: Unable to find plist file at '/Users/behance/.jenkins/workspace/99UTVAppCI-develop/appletv-99u/appletv-99u/Crashlytics.framework/Info.plist'
[10:20:51]: invalid byte sequence in UTF-8
[10:20:51]: Unable to find plist file at '/Users/behance/.jenkins/workspace/99UTVAppCI-develop/appletv-99u/appletv-99u/Fabric.framework/Info.plist'
[10:20:51]: Extracting '/Users/behance/.jenkins/workspace/99UTVAppCI-develop/appletv-99u/99U.app.dSYM.zip'...
[10:20:51]: $ unzip -qo /Users/behance/.jenkins/workspace/99UTVAppCI-develop/appletv-99u/99U.app.dSYM.zip
[10:20:51]: Uploading '99u Extension.appex.dSYM'...
[10:20:51]: Shell command exited with exit status 1 instead of 0.
[10:20:51]: Uploading '99U.app.dSYM'...
[10:20:51]: Shell command exited with exit status 1 instead of 0.
[10:20:51]: Successfully uploaded dSYM files to Crashlytics 💯

+------+-------------------------------+-------------+
|                  fastlane summary                  |
+------+-------------------------------+-------------+
| Step | Action                        | Time (in s) |
+------+-------------------------------+-------------+
| 1    | update_fastlane               | 0           |
| 2    | unlock_keychain               | 0           |
| 3    | download_dsyms                | 5           |
| 4    | upload_symbols_to_crashlytics | 0           |
+------+-------------------------------+-------------+
```

**Comment by TKBurner** [comment]
@jorystiefel Thanks for following up. We are going to look into this and will update on this thread. Thanks for using Fastlane 👍

**Comment by KrauseFx** [comment]
@jorystiefel Could you provide the crashlytics API key manually using
```ruby
upload_symbols_to_crashlytics(api_token: "my_token")
```

**Comment by KrauseFx** [comment]
The error message is basically just an issue with parsing your Info.plist file, which contains the crashlytics token.

**Comment by KrauseFx** [comment]
You can also pass the token using the environment variable `CRASHLYTICS_API_TOKEN`

**Comment by jorystiefel** [comment]
Thanks guys. Passing in the token manually in Fastfile made no difference.

**Comment by TKBurner** [comment]
@jorystiefel Thanks for following up. Can you share the output of fastlane -v? Also can you share your output of running this lane with the --verbose flag? Thanks!

**Comment by LukeDurrant** [comment]
I just ran into this issue fixed by make sure your using Crashlytics > 3.7.0 cocoapod as the upload-symbols wasn't included before then

**Comment by TKBurner** [comment]
@LukeDurrant Thanks for sharing! @jorystiefel Can you try this solution? Thanks 👍

**Comment by spanage** [comment]
I was seeing this exact same issue. Doing both of the following fixed it for me:

1. Updating to Crashlytics 3.8.0
2. Passing my Crasylytics token via the env variable CRASHLYTICS_API_TOKEN.

**Comment by TKBurner** [comment]
@spanage Thanks for sharing! Really glad you got up and running 👍

**Comment by esetnik** [comment]
I'm getting a similar issue with the same error message. Looks like it's trying to find the Crashlytics api token inside my Carthage framework dependencies.

```
[14:09:47]: Unable to find plist file at '/Users/xxx/Carthage/Build/iOS/Alamofire.framework/Info.plist'
```

I will experiment with manually specifying the crashlytics api token.

**Comment by TKBurner** [comment]
@esetnik Thanks for following up. Crashlytics always needs the api key in your info.plist. That is probably the source of your issue. Let me know how it goes!

**Comment by esetnik** [comment]
@TKBurner thanks for the tip. I didn't realize their installation instructions changed since I originally integrated Fabric. Interesting that everything seemed to work re. crash reporting / Fabric SDK initialization without the api token. I just reintegrated against their latest documentation and it's working fine now.

**Comment by TKBurner** [comment]
@esetnik Thanks for following up. Is it at the path, /Users/xxx/Carthage/Build/iOS/Alamofire.framework/Info.plist or is that a framework plist?

Does it open in the viewer in Xcode successfully?

**Comment by esetnik** [comment]
@TKBurner that path is for the `carthage` frameworks in my project. The actual plist containing the aforementioned Crashlytics APIKey is my application's `Info.plist` and is located at the root of my project. It seems that `upload_symbols_to_crashlytics` is doing a recursive search for all frameworks in the project. Note that the `upload_symbols_to_crashlytics` still works despite logging those errors. I think this indicates that it is ultimately finding my application's `Info.plist`.

**Comment by TKBurner** [comment]
@esetnik Are you getting any breaking errors at this point? Can you share the full output? Thanks so much and hope you have a great day!

**Comment by TKBurner** [comment]
@esetnik To clarify are you missing dSYMs after this or just seeing an error in your output? Thanks for working with me on this 👍

**Comment by esetnik** [comment]
Just an error in the output. The dSYM upload is working just fine. Thanks!

**Comment by TKBurner** [comment]
It looks like we are querying the plist for an API key, and then falling back to the info.plist. I'll let the team know, but I'm not sure how fast we'll be able to action this. Thanks!
