### ISSUE TITLE
update_info_plist crashing when the xcodeproj isn't found

### ISSUE THREAD

**Issue by tbaranes** [fastlane/fastlane#4037]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

If `update_info_plist` doesn't found the xcodeproj by using the parameter `xcodeproj`, or by looking in the current directory (if no path specified), the action will crash instead of raising a dedicated exception.

Also, if the xcodeproj isn't found in the current directory, shouldn't it search in the subdirectory? Just asking, not sure if that would be really great.

##### Complete output when running fastlane, including the stack trace and command used

```ruby
[23:18:46]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'ecb4eaa79d39f6942b8478993b2e7690'
The crash report has been stored locally '/tmp/sentry_ecb4eaa79d39f6942b8478993b2e7690.json'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/actions/update_info_plist.rb:21:in `join': [!] no implicit conversion of nil into String (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/actions/update_info_plist.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:111:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:110:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from Fastfile:41:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/bin/fastlane:162:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
before_all do  
end

lane :increment_ios_build do
  update_info_plist(
    plist_path: "plist_path,
    block: lambda { |plist|
      plist['CFBundleVersion'] = "10"
    }
  )
end

after_all do |lane|
end
```

Note: the `xcodeproj` mustn't be in the current directory.

### Environment

fastlane version (fastlane -v): 1.70.0
Do you use bundler, rbenv or ram? bundler

**Comment by TKBurner** [comment]
Thanks for reaching out @tbaranes. We are going to look into this. Hope that you have a great day! :+1:

**Comment by ohwutup** [comment]
Hey @tbaranes, Thanks again for letting us know about the issue! We would definitely be happy to review a PR with this fix! I am going to close the issue for now, but please feel free to reopen if you have a chance to bite off the work to check for nil there!
