### ISSUE TITLE
match development does not work on a enterprise project

### ISSUE THREAD

**Issue by hartbit** [fastlane/fastlane#4042]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I understand the risks of using match in an enterprise context and I accept them. I have successful run `MATCH_FORCE_ENTERPRISE=1 match --type enterprise` but `match --type development` does not work in the same project: 

```
$ match --type development --verbose

+-----------------------+------------------------------------------------+
|                        Summary for match 0.4.0                         |
+-----------------------+------------------------------------------------+
| type                  | development                                    |
| verbose               | true                                           |
| git_url               | <SECRET>                                       |
| app_identifier        | <CURRENT_APPID>                                |
| username              | <SECRET>                                       |
| keychain_name         | login.keychain                                 |
| readonly              | false                                          |
| team_id               | <SECRET>                                       |
| force                 | false                                          |
| shallow_clone         | false                                          |
| force_for_new_devices | false                                          |
| skip_docs             | false                                          |
+-----------------------+------------------------------------------------+

INFO [2016-04-04 10:31:37.32]: Cloning remote git repo...
INFO [2016-04-04 10:31:37.32]: $ git clone '<SECRET>' '/var/folders/6m/_77r35rj7030fbzbqh5vg68h0000gn/T/d20160404-8716-iosqjo'
INFO [2016-04-04 10:31:37.33]: ▸ Cloning into '/var/folders/6m/_77r35rj7030fbzbqh5vg68h0000gn/T/d20160404-8716-iosqjo'...
INFO [2016-04-04 10:31:39.09]: ▸ remote: Counting objects: 44, done.
INFO [2016-04-04 10:31:39.10]: ▸ remote: Compressing objects: 100% (41/41), done.
INFO [2016-04-04 10:31:39.17]: ▸ remote: Total 44 (delta 2), reused 0 (delta 0)
INFO [2016-04-04 10:31:39.17]: ▸ Receiving objects: 100% (44/44), 75.77 KiB | 0 bytes/s, done.
INFO [2016-04-04 10:31:39.17]: ▸ Resolving deltas: 100% (2/2), done.
INFO [2016-04-04 10:31:39.18]: ▸ Checking connectivity... done.
INFO [2016-04-04 10:31:39.22]: 🔓  Decrypted 'Y5SF93L6Q5.cer'
INFO [2016-04-04 10:31:39.26]: 🔓  Decrypted 'HQSWF5V794.cer'
INFO [2016-04-04 10:31:39.29]: 🔓  Decrypted '7VKQ92W85B.cer'
INFO [2016-04-04 10:31:39.33]: 🔓  Decrypted 'Y5SF93L6Q5.p12'
INFO [2016-04-04 10:31:39.37]: 🔓  Decrypted 'HQSWF5V794.p12'
INFO [2016-04-04 10:31:39.40]: 🔓  Decrypted '7VKQ92W85B.p12'
INFO [2016-04-04 10:31:39.43]: 🔓  Decrypted 'AppStore_<UNRELATED_APPID>.mobileprovision'
INFO [2016-04-04 10:31:39.47]: 🔓  Decrypted 'Development_<UNRELATED_APPID>.mobileprovision'
INFO [2016-04-04 10:31:39.50]: 🔓  Decrypted 'InHouse_<CURRENT_APPID>.mobileprovision'
INFO [2016-04-04 10:31:39.50]: 🔓  Successfully decrypted certificates repo
INFO [2016-04-04 10:31:39.53]: Verifying that the certificate and profile are still valid on the Dev Portal...
INFO [2016-04-04 10:31:43.47]: Installing certificate...
INFO [2016-04-04 10:31:43.47]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority'
<SECRET>
DEBUG [2016-04-04 10:31:45.11]: Certificate 'Y5SF93L6Q5.cer' is already installed on this machine
INFO [2016-04-04 10:31:45.11]: $ security import /var/folders/6m/_77r35rj7030fbzbqh5vg68h0000gn/T/d20160404-8716-iosqjo/certs/development/Y5SF93L6Q5.p12 -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign -T /usr/bin/security&> /dev/null
ERROR [2016-04-04 10:31:45.88]: Certificate 'Y5SF93L6Q5' (stored in your git repo) is not available on the Developer Portal
ERROR [2016-04-04 10:31:45.88]: for the user <SECRET>
ERROR [2016-04-04 10:31:45.88]: Make sure to use the same user and team every time you run 'match' for this
ERROR [2016-04-04 10:31:45.88]: Git repository. This might be caused by revoking the certificate on the Dev Portal
INFO [2016-04-04 10:31:45.88]: 🔒  Successfully encrypted certificates repo
/Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] To reset the certificates of your Apple account, you can use the `match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match (FastlaneCore::Interface::FastlaneError)
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/match-0.4.0/lib/match/spaceship_ensure.rb:48:in `certificate_exists'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/match-0.4.0/lib/match/runner.rb:18:in `run'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/match-0.4.0/bin/match:52:in `block (3 levels) in run'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/match-0.4.0/bin/match:108:in `run'
	from /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/match-0.4.0/bin/match:116:in `<top (required)>'
	from /Users/david/.rbenv/versions/2.2.2/bin/match:23:in `load'
	from /Users/david/.rbenv/versions/2.2.2/bin/match:23:in `<main>'
```

### Configuration Files

The `Matchfile` is faily basic:

Fastfile:
```ruby
git_url "<SECRET>"
type "development"
app_identifier "<CURRENT_APPID>" 
username "<SECRET>"
```

### Environment

fastlane version (fastlane -v): fastlane 1.70.0
Do you use bundler, rbenv or ram? rbenv
ruby --version: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]

**Comment by TKBurner** [comment]
Hi @hartbit!

Thanks for reaching out. Can you check and make sure you have the right code signing identity on your machine for this build scheme. ERROR [2016-04-04 10:31:45.88]: Make sure to use the same user and team every time you run 'match' for this
ERROR [2016-04-04 10:31:45.88]: Git repository. This might be caused by revoking the certificate on the Dev Portal

match was designed to have one git repository per Apple account. If you work in multiple teams, please create one repo for each of them. More information on codesigning.guide

**Comment by hartbit** [comment]
If match was designed to have one git repository per Apple account, then it's definitely not for us (all we work on are client projects where each project is a different Apple Team). And that would explain the issue. Is there a reason it was designed that way? Sounds awfully restrictive, no?

**Comment by TKBurner** [comment]
Thanks for following up. I'm sorry to hear that, it was designed this way to not over-complicate the flow. I'm going to flag this as a feature request and have more of the team members look it over. Thanks for working with us :+1:

**Comment by hartbit** [comment]
@TKBurner Thanks for the understanding :) Meanwhile, we've decided that it's too useful to go back. We'll have to do with one repo per client for now!

**Comment by KrauseFx** [comment]
We've previously discussed this [here](https://github.com/fastlane/fastlane/pull/3762#issuecomment-196947958) and [here](https://github.com/fastlane/fastlane/issues/1978). While experimenting with multiple teams support, we noticed that it adds too much complexity to both the code base, and the user interface for the user. We've decided to stick to the simple rule: One repo for each team.
