### ISSUE TITLE
sigh crashing with ""\x82" from ASCII-8BIT to UTF-8"

### ISSUE THREAD

**Issue by tpalmer** [fastlane/fastlane#4087]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
travispalmer$ sigh

+-------------------------------------+------------------------------+
|                       Summary for sigh 1.6.1                       |
+-------------------------------------+------------------------------+
| adhoc                               | false                        |
| skip_install                        | false                        |
| development                         | false                        |
| force                               | false                        |
| app_identifier                      | XXXXX                        |
| username                            | XXXXX                        |
| team_id                             | XXXXX                        |
| team_name                           | XXXXX                        |
| ignore_profiles_with_different_name | false                        |
| skip_fetch_profiles                 | false                        |
| skip_certificate_verification       | false                        |
+-------------------------------------+------------------------------+

[15:03:53]: Starting login with user 'XXXXX
[15:03:55]: Successfully logged in
[15:03:55]: Fetching profiles...
log writing failed. "\x82" from ASCII-8BIT to UTF-8
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '125c64f08bcf7ba9dc01a9879f41e67c'
The crash report has been stored locally '/tmp/sentry_125c64f08bcf7ba9dc01a9879f41e67c.json'
/Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/lib/sigh/runner.rb:87:in `block (2 levels) in fetch_profiles': [!] "\x82" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/lib/sigh/runner.rb:85:in `each'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/lib/sigh/runner.rb:85:in `block in fetch_profiles'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/lib/sigh/runner.rb:82:in `each'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/lib/sigh/runner.rb:82:in `find_all'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/lib/sigh/runner.rb:82:in `fetch_profiles'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/lib/sigh/runner.rb:20:in `run'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/lib/sigh/manager.rb:7:in `start'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/bin/sigh:35:in `block (2 levels) in run'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/bin/sigh:93:in `run'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/gems/sigh-1.6.1/bin/sigh:111:in `<top (required)>'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/bin/sigh:23:in `load'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/bin/sigh:23:in `<main>'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travispalmer/.rvm/gems/ruby-2.0.0-p643@hlt-ios/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

fastlane version (fastlane -v): 1.80.0
Do you use bundler, rbenv or rvm? bundler + rvm

**Comment by vpolouchkine** [comment]
Can you try updating `spaceship`?

**Comment by tpalmer** [comment]
I'm currently on 0.24.1 of spaceship, so unfortunately there is nothing to update to.

**Comment by vpolouchkine** [comment]
OK, would you mind putting back the original issue description for visibility?

**Comment by tpalmer** [comment]
Sure, I don't know what happened to it - but I've recreated it with a new Sentry ID

**Comment by lpenaflor** [comment]
This issue still occurs for me:
RVM ruby 2.2.4
Fastlane 1.92.0
Sigh 1.8.0

**Comment by vpolouchkine** [comment]
@lpenaflor Can you please share your setup? Full log, Fastfile, etc. Thanks!

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
