### ISSUE TITLE
Fastlane init fails.

### ISSUE THREAD

**Issue by m00sey** [fastlane/fastlane#4113]
### Issue Description

I update fastlane, ran `fastlane init` entered my Apple Id and get the following output.

```
Your Apple ID (e.g. fastlane@krausefx.com): foo@bar.com
[20:27:36]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[20:27:36]: Starting login with user 'foo@bar.com'
[20:27:37]: Could not find latest API Key from the Dev Portal - the server might be slow right now
[20:27:37]: An error occurred during the setup process. Falling back to manual setup!
```

If I continue with manual setup I get the following:

```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.24.1/lib/spaceship/portal/portal_client.rb:30:in `api_key': [!] Could not find latest API Key from the Dev Portal - the server might be slow right now (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.24.1/lib/spaceship/portal/portal_client.rb:38:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.24.1/lib/spaceship/client.rb:247:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.24.1/lib/spaceship/client.rb:210:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.24.1/lib/spaceship/client.rb:88:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.24.1/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.24.1/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/setup/setup_ios.rb:184:in `detect_if_app_is_available'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/setup/setup_ios.rb:92:in `ask_to_enable_other_tools'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/setup/setup_ios.rb:82:in `manual_setup'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/setup/setup_ios.rb:61:in `try_manual_setup'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/setup/setup_ios.rb:46:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/setup/setup_ios.rb:28:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/bin/fastlane:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/bin/fastlane:158:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/bin/fastlane:164:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

fastlane version (fastlane -v): fastlane 1.80.0
Do you use bundler, rbenv or rvm? No

I worked through the suggestions in https://github.com/fastlane/gym/issues/100#issuecomment-184335220, but they appeared to have no effect.

**Comment by shingt** [comment]
Might be fixed by this: https://github.com/fastlane/fastlane/pull/4115/files

**Comment by CsabaSzabo** [comment]
Thanks @shingt for the quick fix.

**Comment by m00sey** [comment]
Thanks @shingt all good here.

**Comment by m00sey** [comment]
Just a note, setup was flawless after that hiccup. 

Great work, thanks :)

**Comment by TKBurner** [comment]
Awesome @m00sey! Glad to hear it. Thanks for helping out @shingt :+1:
