### ISSUE TITLE
fastlane_core: fastlane_runner_spec fails locally, but passes in CI

### ISSUE THREAD

**Issue by bgerstle** [fastlane/fastlane#4121]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
`fastlane_core/fastlne_runner_spec` tests locally failed, but succeeded in CI:

##### Complete output when running tests, including the stack trace and command used

```
$ bundle exec rspec ./spec/fastlane_runner_spec.rb
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

Commander::Runner
  #handle_unknown_error
    should reraise errors that are not of special interest (FAILED - 1)
    should reraise errors that return nil from #preferred_error_info (FAILED - 2)
    should abort and show custom info for errors that have the Apple error info provider method with $verbose=false
    should reraise and show custom info for errors that have the Apple error info provider method with $verbose=true

Failures:

  1) Commander::Runner#handle_unknown_error should reraise errors that are not of special interest
     Failure/Error: expect do
       expected StandardError with "\e[31m[!] my message\e[0m", got #<StandardError: my message> with backtrace:
         # ./lib/fastlane_core/crash_reporting/crash_reporting.rb:56:in `handle_crash'
         # ./lib/fastlane_core/ui/fastlane_runner.rb:57:in `handle_unknown_error!'
         # ./spec/fastlane_runner_spec.rb:19:in `block (4 levels) in <top (required)>'
         # ./spec/fastlane_runner_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/fastlane_runner_spec.rb:18:in `block (3 levels) in <top (required)>'

  2) Commander::Runner#handle_unknown_error should reraise errors that return nil from #preferred_error_info
     Failure/Error: expect do
       expected StandardError with "\e[31m[!] my message\e[0m", got #<NilReturningError: my message> with backtrace:
         # ./lib/fastlane_core/crash_reporting/crash_reporting.rb:56:in `handle_crash'
         # ./lib/fastlane_core/ui/fastlane_runner.rb:57:in `handle_unknown_error!'
         # ./spec/fastlane_runner_spec.rb:25:in `block (4 levels) in <top (required)>'
         # ./spec/fastlane_runner_spec.rb:24:in `block (3 levels) in <top (required)>'
     # ./spec/fastlane_runner_spec.rb:24:in `block (3 levels) in <top (required)>'

Finished in 0.0105 seconds (files took 0.59638 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./spec/fastlane_runner_spec.rb:17 # Commander::Runner#handle_unknown_error should reraise errors that are not of special interest
rspec ./spec/fastlane_runner_spec.rb:23 # Commander::Runner#handle_unknown_error should reraise errors that return nil from #preferred_error_info
[Coveralls] Outside the CI environment, not sending data.
```

### Configuration Files

n/a

Fastfile: n/a

### Environment

fastlane version (fastlane -v): n/a, developing on `master`
Do you use bundler, rbenv or rvm? bundler :white_check_mark:, rbenv :white_check_mark:

**Comment by TKBurner** [comment]
@bgerstle Hi! Thanks for sending this over. It sounds like there might be a config issue on your side. Are you able to verify this on another device? Thanks :+1:

**Comment by bgerstle** [comment]
@TKBurner i'll give it a go, but you may be right.  My ruby environment is a bit of a mess atm. Will update if I'm able to try it out on another Mac or after I have time to tidy up my env again

**Comment by TKBurner** [comment]
Thanks @bgerstle I'll mark this as awaiting reply so you can update in a few days. Thanks!
