### ISSUE TITLE
Question - Scan doesn't find tests.

### ISSUE THREAD

**Issue by m00sey** [fastlane/fastlane#4149]
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I can run tests from xcode with command+u, they pass/fail as expected.

When I run them with scan I get the following success output:

```
[19:33:55]: ▸ Linking ScoirTests
[19:33:55]: ▸ ⚠️  ld: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/Developer/Library/Frameworks'
[19:33:55]: ▸ Generating 'ScoirTests.xctest.dSYM'
[19:33:55]: ▸ Running script 'Copy Pods Resources'
[19:33:55]: ▸ Running script 'Embed Pods Frameworks'
[19:33:56]: Running Tests: ▸ Touching ScoirTests.xctest
[19:34:00]: ▸ Test Succeeded
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 0     |
| Number of failures | 0     |
```

When I intentionally have a failing test I get a crash with the following outoput:

```
▸ Linking ScoirTests
⚠️  ld: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/Developer/Library/Frameworks'
▸ Generating 'ScoirTests.xctest.dSYM'
▸ Running script 'Copy Pods Resources'
▸ Running script 'Embed Pods Frameworks'
▸ Touching ScoirTests.xctest
** TEST FAILED **
[19:52:48]: Exit status: 65
[19:52:48]: Variable Dump:
[19:52:48]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[19:52:48]: Error building/testing the application - see the log above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 16          |
| 4    | scan                                | 268         |
+------+-------------------------------------+-------------+

[19:52:48]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '67bdfbe4e8e4a5bc5b7ab6189283b759'
The crash report has been stored locally '/tmp/sentry_67bdfbe4e8e4a5bc5b7ab6189283b759.json'
/Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/error_handler.rb:32:in `handle_build_error': [!] Error building/testing the application - see the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/runner.rb:31:in `block in test_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/command_executor.rb:85:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/command_executor.rb:85:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/runner.rb:23:in `test_app'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/runner.rb:9:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/scan.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:27:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Fastfile:
```ruby
  desc "Runs all the tests"
  lane :test do
    scan(
        scheme: "Scoir"
    )
  end
```

### Environment

fastlane version (fastlane -v): 1.81.0
Do you use bundler, rbenv or rvm? bundler

**Comment by TKBurner** [comment]
Hi @m00sey. Thanks for reaching out about this. Can you take a look at #3886 and let me know if this is a dupe. We are tracking an issue with scan right now in Xcode 7.3. Thanks!

**Comment by m00sey** [comment]
Yes, apologies, it looks like a dupe.

**Comment by TKBurner** [comment]
Thnaks @m00sey!
