### ISSUE TITLE
Supply doesn't support apk upload when multiple APKs are supported

### ISSUE THREAD

**Issue by CsabaSzabo** [fastlane/fastlane#4171]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Supply cannot upload APK when multi APKs are used in GooglePlay

```
+-------------------------+-----------------------------------+
|                  Summary for supply 0.6.2                   |
+-------------------------+-----------------------------------+
| apk                     | signed-app.apk                    |
| track                   | alpha                             |
| json_key                | ReleaseManagement-GooglePlay.json |
| skip_upload_metadata    | true                              |
| skip_upload_images      | true                              |
| skip_upload_screenshots | true                              |
| package_name            | net.skyscanner.android.main       |
| rollout                 | 1.0                               |
| skip_upload_apk         | false                             |
+-------------------------+-----------------------------------+

DEBUG [2016-04-12 17:00:16.60]: Fetching a new access token from Google...
INFO [2016-04-12 17:00:17.74]: Preparing apk at path 'signed-app.apk' for upload...
INFO [2016-04-12 17:00:22.10]: Updating track 'alpha'...
INFO [2016-04-12 17:00:22.65]: Uploading all changes to Google Play...
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'd9e6f353f5397d0ad1ca590a7dcc76a6'
The crash report has been stored locally '/tmp/sentry_d9e6f353f5397d0ad1ca590a7dcc76a6.json'
/usr/local/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:211:in `check_status': [!] multiApkShadowedActiveApk: Version 1603300543 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes. (Google::Apis::ClientError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.3/lib/google/apis/core/api_command.rb:102:in `check_status'
	from /usr/local/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:179:in `process_response'
	from /usr/local/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:286:in `execute_once'
	from /usr/local/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /usr/local/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /usr/local/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /usr/local/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /usr/local/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /usr/local/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /usr/local/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:96:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.3/lib/google/apis/core/base_service.rb:267:in `execute_or_queue_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.3/generated/google/apis/androidpublisher_v2/service.rb:91:in `commit_edit'
	from /usr/local/lib/ruby/gems/2.2.0/gems/supply-0.6.2/lib/supply/client.rb:100:in `commit_current_edit!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/supply-0.6.2/lib/supply/uploader.rb:29:in `perform_upload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/supply-0.6.2/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/supply-0.6.2/lib/supply/commands_generator.rb:57:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/supply-0.6.2/lib/supply/commands_generator.rb:15:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/supply-0.6.2/bin/supply:6:in `<top (required)>'
	from /usr/local/bin/supply:23:in `load'
	from /usr/local/bin/supply:23:in `<main>'
```

### Configuration Files

I'm calling supply from terminal and not from fastfle:

```bash
supply --apk signed-app.apk --track alpha --json_key key.json --skip_upload_metadata --skip_upload_images --skip_upload_screenshots --verbose --package_name net.app.id
```

### Environment

supply version (supply -v): 0.6.2

**Comment by CsabaSzabo** [comment]
It can a misunderstanding of the error log, it's just a versionCode conflict, it's not an issue
