### ISSUE TITLE
undefined method `fetch' for nil:NilClass

### ISSUE THREAD

**Issue by SunilProgramobil** [fastlane/fastlane#4207]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

While running fastlane without any dependencies it works fine but if we run the same command thorugh jenkins I see the follow ouput

##### Complete output when running fastlane, including the stack trace and command used

```
[EnvInject] - Loading node environment variables.
Building in workspace /Users/Shared/Jenkins/Home/jobs/HubApp/workspace
[ssh-agent] Looking for ssh-agent implementation...
[ssh-agent]   Java/JNR ssh-agent
[ssh-agent] Started.
[ssh-agent] Using credentials SSH
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url ssh://git@stash.staples.com:7999/mobile/mobilehub-ios.git # timeout=10
Fetching upstream changes from ssh://git@stash.staples.com:7999/mobile/mobilehub-ios.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git -c core.askpass=true fetch --tags --progress ssh://git@stash.staples.com:7999/mobile/mobilehub-ios.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/FastLane_Enabled_Branch^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/FastLane_Enabled_Branch^{commit} # timeout=10
Checking out Revision 6fed7f50373f4addb712ac2a25472bc7aa1f7d46 (refs/remotes/origin/FastLane_Enabled_Branch)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 6fed7f50373f4addb712ac2a25472bc7aa1f7d46
 > git rev-list 6fed7f50373f4addb712ac2a25472bc7aa1f7d46 # timeout=10
[EnvInject] - Executing scripts and injecting environment variables after the SCM step.
[EnvInject] - Injecting as environment variables the properties content 
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

[EnvInject] - Variables injected successfully.
[workspace] $ /bin/sh -xe /Users/Shared/Jenkins/tmp/hudson5138860643886149582.sh
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ fastlane beta
[10:16:42]: [32m-------------------------------------------------[0m
[10:16:42]: [32m--- Step: Verifying required fastlane version ---[0m
[10:16:42]: [32m-------------------------------------------------[0m
[10:16:42]: fastlane version valid
[10:16:42]: [32m------------------------------[0m
[10:16:42]: [32m--- Step: default_platform ---[0m
[10:16:42]: [32m------------------------------[0m
[10:16:42]: [32mDriving the lane 'ios beta' 🚀[0m
[10:16:42]: [32m-----------------------[0m
[10:16:42]: [32m--- Step: cocoapods ---[0m
[10:16:42]: [32m-----------------------[0m
[10:16:42]: [4m[36m$ pod install[0m[0m
[10:16:43]: ▸ [35mUpdating local specs repositories[0m
[10:16:49]: ▸ [35mCocoaPods 1.0.0.beta.6 is available.[0m
[10:16:49]: ▸ [35mTo update use: `gem install cocoapods --pre`[0m
[10:16:49]: ▸ [35m[!] This is a test version we'd love you to try.[0m
[10:16:49]: ▸ [35mFor more information see http://blog.cocoapods.org[0m
[10:16:49]: ▸ [35mand the CHANGELOG for this version http://git.io/BaH8pQ.[0m
[10:16:49]: ▸ [35mAnalyzing dependencies[0m
[10:16:52]: ▸ [35mDownloading dependencies[0m
[10:16:52]: ▸ [35mUsing Alamofire (3.2.0)[0m
[10:16:52]: ▸ [35mUsing AlamofireImage (2.3.1)[0m
[10:16:52]: ▸ [35mUsing Argo (2.2.0)[0m
[10:16:52]: ▸ [35mUsing Brightcove-Player-SDK (5.0.2)[0m
[10:16:52]: ▸ [35mUsing CocoaLumberjack (2.1.0)[0m
[10:16:52]: ▸ [35mUsing CrittercismSDK (5.5.5)[0m
[10:16:52]: ▸ [35mUsing Curry (1.4.0)[0m
[10:16:52]: ▸ [35mUsing GoogleAnalytics (3.14.0)[0m
[10:16:52]: ▸ [35mUsing GoogleTagManager (3.15.0)[0m
[10:16:52]: ▸ [35mUsing IQKeyboardManagerSwift (4.0.1)[0m
[10:16:52]: ▸ [35mUsing Locksmith (2.0.8)[0m
[10:16:52]: ▸ [35mUsing MBProgressHUD (0.9)[0m
[10:16:52]: ▸ [35mUsing ReachabilitySwift (2.3)[0m
[10:16:52]: ▸ [35mUsing UrbanAirship-iOS-SDK (6.4.0)[0m
[10:16:52]: ▸ [35mUsing apptentive-ios (2.1.2)[0m
[10:16:52]: ▸ [35mGenerating Pods project[0m
[10:16:55]: ▸ [35mIntegrating client project[0m
[10:16:55]: ▸ [35mSending stats[0m
[10:16:55]: ▸ [35mPod installation complete! There are 14 dependencies from the Podfile and 15 total pods installed.[0m
[10:16:55]: [32m-----------------[0m
[10:16:55]: [32m--- Step: gym ---[0m
[10:16:55]: [32m-----------------[0m
[10:16:55]: Installing provisioning profile...
security: cert import failed: A default keychain could not be found.
security: problem decoding
[10:16:55]: [31mError parsing provisioning profile at path '/Users/Shared/Jenkins/Home/jobs/HubApp/workspace/InHouse_com.staples.hub.prod.mobileprovision'[0m
[10:16:55]: [33m[33mVariable Dump:[0m[0m
[10:16:55]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
[10:16:55]: [31mundefined method `fetch' for nil:NilClass[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 13          |
| 4    | gym                                 | 0           |
+------+-------------------------------------+-------------+

[10:16:56]: [31mfastlane finished with errors[0m
[33m-------------------------------------------------------------------------------------------[0m
[33m😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.[0m
[33m👍  This makes resolving issues much easier and helps improve fastlane.[0m
[33m🔒  The reports will be stored securely on getsentry.com.[0m
[33m🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3[0m
[33m-------------------------------------------------------------------------------------------[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/provisioning_profile.rb:38:in `uuid': [31m[!] undefined method `fetch' for nil:NilClass[0m (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/provisioning_profile.rb:54:in `install'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/detect_values.rb:51:in `detect_provisioning_profile'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/detect_values.rb:15:in `set_additional_default_values'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym.rb:25:in `config='
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/manager.rb:4:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:34:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
[OS X] restore keychains as defined in global configuration
[workspace] $ /usr/bin/security list-keychains -s
[ssh-agent] Stopped.
Finished: FAILURE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "MobileHub-Prod") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "MobileHub-Prod") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by vpolouchkine** [comment]
Take a look at https://github.com/fastlane/fastlane/issues/360, looks similar.

**Comment by SunilProgramobil** [comment]
Couldn't figure out a way for it. I am still facing the same issue

**Comment by TKBurner** [comment]
@SunilProgramobil Thanks for updating. I'll make sure the team takes a look 👍
