### ISSUE TITLE
error when using to upload build to fabric crashlytics

### ISSUE THREAD

**Issue by PointlessReboot** [fastlane/fastlane#4222]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

```
Graemes-MacBook-Pro:android graemescott$ fastlane submit_unity_beta
[11:13:27]: -------------------------------------------------
[11:13:27]: --- Step: Verifying required fastlane version ---
[11:13:27]: -------------------------------------------------
[11:13:27]: fastlane version valid
[11:13:27]: ------------------------------
[11:13:27]: --- Step: default_platform ---
[11:13:27]: ------------------------------
[11:13:27]: Driving the lane 'android submit_unity_beta' 🚀
[11:13:27]: -------------------------
[11:13:27]: --- Step: crashlytics ---
[11:13:27]: -------------------------
[11:13:27]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[11:13:30]: Variable Dump:
[11:13:30]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android submit_unity_beta"}
[11:13:30]: Shell command exited with exit status 1 instead of 0.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | crashlytics                         | 2           |
+------+-------------------------------------+-------------+

[11:13:30]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'cb56bf64d90c8a7f2f957eb7ebad842e'
The crash report has been stored locally '/tmp/sentry_cb56bf64d90c8a7f2f957eb7ebad842e.json'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/crashlytics.rb:32:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:45:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Graemes-MacBook-Pro:android graemescott$ 

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  desc "Distribute a new unity Beta"
  lane :submit_unity_beta do
     crashlytics(
       emails: "graeme@zengami.com",
       api_token: "...",
       build_secret: "..."
     )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
don't think so..

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
not sure, don't think so..
[sentry_ea6e0bb015bd2c37260be6b25e38758c.json.txt](https://github.com/fastlane/fastlane/files/220371/sentry_ea6e0bb015bd2c37260be6b25e38758c.json.txt)

**Comment by vpolouchkine** [comment]
FYI I removed the Beta API key and Secret in your post.

**Comment by vpolouchkine** [comment]
Try adding `gradle(task: "assembleRelease")` in your `submit_unity_beta` lane.

**Comment by pedrosanta** [comment]
I'm also having this issue when trying to submit a Unity built APK using the instructions in the documentation: https://docs.fabric.io/unity/beta/index.html

**Comment by pedrosanta** [comment]
I also had to find the `crashlytics-devtools.jar` and download it on the Ant plugin here https://fabric.io/downloads/ant, to reach this point.

**Comment by pedrosanta** [comment]
@vpolouchkine I tried adding that task to the `submit_unity_beta` lane, but I didn't really had `gradle` installed (which I did with Homebrew `brew install gradle`) and then `gradlew` couldn't be found (which I fixed running `gradle init`) and then `"assembleRelease"` task wasn't found/defined.

The issue here is that I'm not exporting a full fledged Android project, I'm building an APK through Unity, and `gradle` and its tasks aren't defined.

Seems to me that might be something off beat on Fabric Unity documentation.

**Comment by TKBurner** [comment]
Hi @pedrosanta Thanks for following up. What happens when you manually set the apk_path parameter on the Crashlytics action?

Thanks 👍

**Comment by sweetmandm** [comment]
@PointlessReboot it can be enlightening to run the Crashlytics command manually. Fastlane seems to suppress the errors and just say `Shell command exited with exit status 1 instead of 0.` I caught two errors this way that were not discernible from the fastlane output -- one where my crashlytics group alias was wrong and another where I had gone into fabric.io and disabled the build number that I was trying to send out.

**Comment by sweetmandm** [comment]
@PointlessReboot the error output should be improved by https://github.com/fastlane/fastlane/pull/4526, which is in fastlane-1.86.0. If you update fastlane to the new version and try the command again, you might get some more descriptive error information.

**Comment by drdesai03** [comment]
Facing the same issue while uploading to beta store. below are --verbose from my run. 
```
INFO [2016-05-06 09:15:32.53]: ▸ BUILD SUCCESSFUL
INFO [2016-05-06 09:15:32.53]: ▸ Total time: 20.137 secs
INFO [2016-05-06 09:15:32.56]: ▸ This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
INFO [2016-05-06 09:15:32.95]: -------------------------
INFO [2016-05-06 09:15:32.95]: --- Step: crashlytics ---
INFO [2016-05-06 09:15:32.95]: -------------------------
INFO [2016-05-06 09:15:33.07]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2016-05-06 09:15:33.07]: java -jar /Users/Drup/workspaceNew/android.guava/AndroidSource/GuavaAndroid/fastlane/crashlytics-devtools.jar -androidRes . -apiKey ede1b6b2e188115c3c072795bc8cdf7ae263003b -apiSecret 714fba508d07642289adae3ee70e2a79feaaed0bf3869b9181cc1b582d4473a5 -uploadDist '/Users/Drup/workspaceNew/android.guava/AndroidSource/GuavaAndroid/app/build/outputs/apk/app-beta-debug.apk' -androidManifest '/var/folders/gg/19n7lr7d3y355glj7tmvn8ch0000gp/T/xml20160506-19722-3zdcns' -betaDistributionGroupAliases 'betaBuild' -betaDistributionNotifications true
WARN [2016-05-06 09:15:35.37]: Variable Dump:
INFO [2016-05-06 09:15:35.37]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android beta", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/Users/Drup/workspaceNew/android.guava/AndroidSource/GuavaAndroid/app/build/outputs/apk/app-beta-debug.apk", "/Users/Drup/workspaceNew/android.guava/AndroidSource/GuavaAndroid/app/build/outputs/apk/app-beta-release-unsigned.apk", "/Users/Drup/workspaceNew/android.guava/AndroidSource/GuavaAndroid/app/build/outputs/apk/app-releaseConfig-release-unsigned.apk"], :GRADLE_APK_OUTPUT_PATH=>"/Users/Drup/workspaceNew/android.guava/AndroidSource/GuavaAndroid/app/build/outputs/apk/app-releaseConfig-release-unsigned.apk"}
ERROR [2016-05-06 09:15:35.37]: Shell command exited with exit status 1 instead of 0.
INFO [2016-05-06 09:15:35.37]: Successfully generated documentation to path '/Users/Drup/workspaceNew/android.guava/AndroidSource/GuavaAndroid/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gradle                              | 20          |
| 4    | crashlytics                         | 2           |
+------+-------------------------------------+-------------+

ERROR [2016-05-06 09:15:35.38]: fastlane finished with errors

#######################################################################
# fastlane 1.86.1 is available. You are on 1.85.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################

1.86.1 Improvements
- Fixed directory in which commands are executed when calling actions from actions
- Removed unnecessary output when running `fastlane`
- Updated dependencies
- Improved docs

1.86.0 Many Improvements
* Introducing sub-tools, you can now run `fastlane gym` to run `gym`
* Added `repo_classifier` parameter to `nexus_upload` action
* Fix HttpForbidden and SSL connection problems on `appaloosa` action
* Make it easier to call another action from an action, you can now use `other_action.rocket` 🚀
* Added new `set_pod_key` action
* Improved default `crashlytics_path` in `crashlytics` action
* Added `use_libraries` option to `pod_push` action
* Added new `apteligent` action
* Make it possible to use `.slather.yml` on `slather` action
* Added new `Fastlane::TOOLS` constant
* Improved `crashlytics` action logging

Update using 'sudo gem update fastlane'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/helper/sh_helper.rb:47:in `sh_control_output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/actions/crashlytics.rb:32:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:31:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/commands_generator.rb:171:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/bin/fastlane:6:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

Below is my fastfile 

```
default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics(
        crashlytics_path: "fastlane/crashlytics-devtools.jar",
        apk_path: "app/build/outputs/apk/app-beta-debug.apk",
        groups: "betaBuild",
        api_token: "...",
        build_secret: "..."
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```

**Comment by sweetmandm** [comment]
@drdesai03 it looks like you're on an old version of fastlane, and the new version should have better error output to help you see what's going wrong. Try updating fastlane ([sudo] gem update fastlane) and see if it helps you figure out what's going on. In my experience the cause of failure is often something wrong in the config and not with fastlane itself, but the version of fastlane you're using won't show the errors.

**Comment by drdesai03** [comment]
@sweetmandm my fastlane is already updated. I have update it using gem update fastlane. Which config file you are talking about. Can you point me where I am doing wrong.

**Comment by sweetmandm** [comment]
@drdesai03 Sorry, by 'config' I mean the crashlytics options in the Fastfile.
It looks like the version of fastlane you're on is not up-to-date based on the log output you posted, which says:
```
#######################################################################
# fastlane 1.86.1 is available. You are on 1.85.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################
```
The helpful error messaging is in version 1.86, and it looks like you're using 1.85. Try this command to make sure you're on 1.86.1:
`fastlane --version`

After you update fastlane, I think fastlane will probably still fail, but it should give you extra error information in the log output so you can diagnose what's going wrong.

**Comment by TKBurner** [comment]
@drdesai03 Were you able to update Fastlane? We added some logging recently so you might get a more specific error message. Also can you set debug: true in your Crashlytics action? Thanks!
