### ISSUE TITLE
authentication.failed error when setting up match

### ISSUE THREAD

**Issue by mdamjanic7** [fastlane/fastlane#4231]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to set up match with an Apple Enterprise account, but it fails while getting teams. I can log in to developer.apple.com without any prompts or errors.

##### Complete output when running fastlane, including the stack trace and command used

```
➜  Projects MATCH_FORCE_ENTERPRISE="1" match development --verbose

+-----------------------+--------------------------------------------------------------------+
|                                  Summary for match 0.4.0                                   |
+-----------------------+--------------------------------------------------------------------+
| verbose               | true                                                               |
| git_url               | ssh://git@something.com/apple/match-enterprise.git |
| type                  | development                                                        |
| keychain_name         | login.keychain                                                     |
| readonly              | false                                                              |
| force                 | false                                                              |
| shallow_clone         | false                                                              |
| force_for_new_devices | false                                                              |
| skip_docs             | false                                                              |
+-----------------------+--------------------------------------------------------------------+

INFO [2016-04-16 23:43:14.22]: Cloning remote git repo...
INFO [2016-04-16 23:43:14.22]: $ git clone 'ssh://git@something.com:1337/apple/match-enterprise.git' '/var/folders/lx/zl43jm295ml673t4mfcvjn4m0000gn/T/d20160416-12343-15kdi32'
INFO [2016-04-16 23:43:14.22]: ▸ Cloning into '/var/folders/lx/zl43jm295ml673t4mfcvjn4m0000gn/T/d20160416-12343-15kdi32'...
INFO [2016-04-16 23:43:14.46]: ▸ warning: You appear to have cloned an empty repository.
INFO [2016-04-16 23:43:14.46]: ▸ Checking connectivity... done.
INFO [2016-04-16 23:43:14.50]: 🔓  Successfully decrypted certificates repo
WARN [2016-04-16 23:43:14.50]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: apple-portal-enterprise@nordeus.com
INFO [2016-04-16 23:43:19.86]: Verifying that the certificate and profile are still valid on the Dev Portal...
INFO [2016-04-16 23:43:24.56]: 🔒  Successfully encrypted certificates repo
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/client.rb:427:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
	authentication.failed
	Your session has expired.  Please log in.
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/portal_client.rb:51:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/portal_client.rb:67:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.4.0/lib/match/spaceship_ensure.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.4.0/lib/match/runner.rb:11:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.4.0/lib/match/runner.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.4.0/bin/match:52:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.4.0/bin/match:108:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.4.0/bin/match:116:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'

```

### Configuration Files

Not relevant

### Environment

fastlane version (run `fastlane -v`): fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by mdamjanic7** [comment]
Duplicate of  #2054
