### ISSUE TITLE
Crashlytics error (method not found)

### ISSUE THREAD

**Issue by slashmo** [fastlane/fastlane#4232]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]  (https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm getting the following errors when trying to run Crashlytics from my lane. 
My ruby version is **2.3.0**.

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane CrashlyticsBeta
[03:39:55]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
[03:39:55]: -------------------------------------------------
[03:39:55]: --- Step: Verifying required fastlane version ---
[03:39:55]: -------------------------------------------------
[03:39:55]: fastlane version valid
[03:39:55]: ------------------------------
[03:39:55]: --- Step: default_platform ---
[03:39:55]: ------------------------------
[03:39:55]: Driving the lane 'ios CrashlyticsBeta' 🚀
[03:39:55]: -----------------------
[03:39:55]: --- Step: cocoapods ---
[03:39:55]: -----------------------
[03:39:55]: $ pod install
[03:39:55]: ▸ Updating local specs repositories
[03:40:03]: ▸ CocoaPods 1.0.0.beta.8 is available.
[03:40:03]: ▸ To update use: `gem install cocoapods --pre`
[03:40:03]: ▸ [!] This is a test version we'd love you to try.
[03:40:03]: ▸ For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.0.0.beta.8
[03:40:04]: ▸ Analyzing dependencies
[03:40:04]: ▸ Downloading dependencies
[03:40:04]: ▸ Using Crashlytics (3.7.0)
[03:40:04]: ▸ Using Fabric (1.6.7)
[03:40:04]: ▸ Using Socket.IO-Client-Swift (6.1.0)
[03:40:04]: ▸ Generating Pods project
[03:40:05]: ▸ Integrating client project
[03:40:06]: ▸ Sending stats
[03:40:06]: ▸ Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.
[03:40:06]: ------------------------------------
[03:40:06]: --- Step: increment_build_number ---
[03:40:06]: ------------------------------------
[03:40:06]: $ cd /Users/slashmo/Google\ Drive/Development/Slashkeys/jooy/ios/Jooy && agvtool next-version -all
[03:40:06]: ▸ Setting version of project Jooy to:
[03:40:06]: ▸ 4.
[03:40:06]: ▸ Also setting CFBundleVersion key (assuming it exists)
[03:40:06]: ▸ Updating CFBundleVersion in Info.plist(s)...
[03:40:06]: ▸ Updated CFBundleVersion in "Jooy.xcodeproj/../Jooy/Info.plist" to 4
[03:40:06]: ▸ Updated CFBundleVersion in "Jooy.xcodeproj/../JooyTests/Info.plist" to 4
[03:40:06]: ▸ Updated CFBundleVersion in "Jooy.xcodeproj/../JooyUITests/Info.plist" to 4
[03:40:07]: -----------------
[03:40:07]: --- Step: gym ---
[03:40:07]: -----------------
[03:40:07]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816
[03:40:07]: xcrun xcodebuild -list -workspace 'Jooy.xcworkspace'

+----------------------+----------------------+
|            Summary for gym 1.6.2            |
+----------------------+----------------------+
| use_legacy_build_api | true                 |
| workspace            | Jooy.xcworkspace     |
| configuration        | Debug                |
| scheme               | Jooy                 |
| silent               | true                 |
| clean                | true                 |
| output_directory     | ../JooyBetaBuilds    |
| output_name          | Jooy-Beta            |
| destination          | generic/platform=iOS |
| buildlog_path        | ~/Library/Logs/gym   |
+----------------------+----------------------+

[03:40:10]: ▸ Cleaning Pods/Socket.IO-Client-Swift [Debug]
[03:40:10]: ▸ Check Dependencies
[03:40:10]: ▸ Cleaning Pods/Pods-Jooy [Debug]
[03:40:10]: ▸ Check Dependencies
[03:40:10]: ▸ Cleaning Jooy/Jooy [Debug]
[03:40:10]: ▸ Check Dependencies
[03:40:10]: ▸ Clean Succeeded
[03:40:10]: ▸ Building Pods/Socket.IO-Client-Swift [Debug]
[03:40:10]: ▸ Check Dependencies
[03:40:10]: ▸ Processing Info.plist
[03:40:11]: ▸ Compiling SocketAckEmitter.swift
[03:40:12]: ▸ Compiling SocketAckManager.swift
[03:40:12]: ▸ Compiling SocketAnyEvent.swift
[03:40:12]: ▸ Compiling SocketClientSpec.swift
[03:40:12]: ▸ Compiling SocketEngine.swift
[03:40:13]: ▸ Compiling SocketEngineClient.swift
[03:40:13]: ▸ Compiling SocketEnginePacketType.swift
[03:40:13]: ▸ Compiling SocketEnginePollable.swift
[03:40:13]: ▸ Compiling SocketEngineSpec.swift
[03:40:13]: ▸ Compiling SocketEngineWebsocket.swift
[03:40:13]: ▸ Compiling SocketEventHandler.swift
[03:40:13]: ▸ Compiling SocketIOClient.swift
[03:40:14]: ▸ Compiling SocketIOClientOption.swift
[03:40:14]: ▸ Compiling SocketIOClientStatus.swift
[03:40:14]: ▸ Compiling SocketLogger.swift
[03:40:14]: ▸ Compiling SocketPacket.swift
[03:40:14]: ▸ Compiling SocketParsable.swift
[03:40:14]: ▸ Compiling SocketStringReader.swift
[03:40:14]: ▸ Compiling SocketTypes.swift
[03:40:14]: ▸ Compiling SwiftRegex.swift
[03:40:14]: ▸ Compiling WebSocket.swift
[03:40:15]: ▸ Compiling SocketAckEmitter.swift
[03:40:16]: ▸ Compiling SocketAckManager.swift
[03:40:16]: ▸ Compiling SocketAnyEvent.swift
[03:40:16]: ▸ Compiling SocketClientSpec.swift
[03:40:16]: ▸ Compiling SocketEngine.swift
[03:40:17]: ▸ Compiling SocketEngineClient.swift
[03:40:17]: ▸ Compiling SocketEnginePacketType.swift
[03:40:17]: ▸ Compiling SocketEnginePollable.swift
[03:40:17]: ▸ Compiling SocketEngineSpec.swift
[03:40:17]: ▸ Compiling SocketEngineWebsocket.swift
[03:40:17]: ▸ Compiling SocketEventHandler.swift
[03:40:17]: ▸ Compiling SocketIOClient.swift
[03:40:18]: ▸ Compiling SocketIOClientOption.swift
[03:40:18]: ▸ Compiling SocketIOClientStatus.swift
[03:40:18]: ▸ Compiling SocketLogger.swift
[03:40:18]: ▸ Compiling SocketPacket.swift
[03:40:18]: ▸ Compiling SocketParsable.swift
[03:40:18]: ▸ Compiling SocketStringReader.swift
[03:40:18]: ▸ Compiling SocketTypes.swift
[03:40:18]: ▸ Compiling SwiftRegex.swift
[03:40:18]: ▸ Compiling WebSocket.swift
[03:40:19]: ▸ Compiling Socket.IO-Client-Swift-dummy.m
[03:40:19]: ▸ Compiling SocketIOClientSwift_vers.c
[03:40:19]: ▸ Compiling Socket.IO-Client-Swift-dummy.m
[03:40:19]: ▸ Compiling SocketIOClientSwift_vers.c
[03:40:19]: ▸ Linking SocketIOClientSwift
[03:40:20]: ▸ Linking SocketIOClientSwift
[03:40:20]: ▸ Copying Socket.IO-Client-Swift-umbrella.h
[03:40:20]: ▸ Touching SocketIOClientSwift.framework
[03:40:20]: ▸ Signing /Users/slashmo/Library/Developer/Xcode/DerivedData/Jooy-baytmpmkwifecbcoqnnrraacdceu/Build/Intermediates/ArchiveIntermediates/Jooy/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SocketIOClientSwift.framework
[03:40:20]: ▸ Building Pods/Pods-Jooy [Debug]
[03:40:20]: ▸ Check Dependencies
[03:40:20]: ▸ Processing Info.plist
[03:40:20]: ▸ Compiling Pods-Jooy-dummy.m
[03:40:20]: ▸ Compiling Pods_Jooy_vers.c
[03:40:20]: ▸ Compiling Pods-Jooy-dummy.m
[03:40:20]: ▸ Compiling Pods_Jooy_vers.c
[03:40:20]: ▸ Copying Pods-Jooy-umbrella.h
[03:40:21]: ▸ Touching Pods_Jooy.framework
[03:40:21]: ▸ Signing /Users/slashmo/Library/Developer/Xcode/DerivedData/Jooy-baytmpmkwifecbcoqnnrraacdceu/Build/Intermediates/ArchiveIntermediates/Jooy/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Pods_Jooy.framework
[03:40:21]: ▸ Building Jooy/Jooy [Debug]
[03:40:21]: ▸ Check Dependencies
[03:40:21]: ▸ Running script '📦 Check Pods Manifest.lock'
[03:40:21]: ▸ Compiling ViewController.swift
[03:40:21]: ▸ Compiling AppDelegate.swift
[03:40:21]: ▸ Compiling ViewController.swift
[03:40:21]: ▸ Compiling AppDelegate.swift
[03:40:21]: ▸ Linking Jooy
[03:40:22]: ▸ Linking Jooy
[03:40:22]: ▸ Compiling LaunchScreen.storyboard
[03:40:25]: ▸ Compiling Main.storyboard
[03:40:25]: ▸ Processing Info.plist
[03:40:25]: ▸ Generating 'Jooy.app.dSYM'
[03:40:25]: ▸ Running script '📦 Embed Pods Frameworks'
[03:40:25]: ▸ Running script '📦 Copy Pods Resources'
[03:40:25]: ▸ Running script '🐦 Fabric Run'
[03:40:25]: ▸ Touching Jooy.app
[03:40:29]: ▸ Signing /Users/slashmo/Library/Developer/Xcode/DerivedData/Jooy-baytmpmkwifecbcoqnnrraacdceu/Build/Intermediates/ArchiveIntermediates/Jooy/InstallationBuildProductsLocation/Applications/Jooy.app
[03:40:30]: ▸ Touching Jooy.app.dSYM
[03:40:30]: ▸ Archive Succeeded
[03:40:30]: Successfully stored the archive. You can find it in the Xcode Organizer.

[03:40:37]: Successfully exported and compressed dSYM file
[03:40:37]: Successfully exported and signed the ipa file:
[03:40:37]: /Users/slashmo/Google Drive/Development/Slashkeys/jooy/ios/JooyBetaBuilds/Jooy-Beta.ipa
[03:40:37]: -------------------------
[03:40:37]: --- Step: crashlytics ---
[03:40:37]: -------------------------
[03:40:37]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[03:40:45]: -------------------
[03:40:45]: --- Step: slack ---
[03:40:45]: -------------------
[03:40:47]: Successfully sent Slack notification
[03:40:47]: Variable Dump:
[03:40:47]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios CrashlyticsBeta", :BUILD_NUMBER=>"4", :IPA_OUTPUT_PATH=>"/Users/slashmo/Google Drive/Development/Slashkeys/jooy/ios/JooyBetaBuilds/Jooy-Beta.ipa", :DSYM_OUTPUT_PATH=>"/Users/slashmo/Google Drive/Development/Slashkeys/jooy/ios/JooyBetaBuilds/Jooy-Beta.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/slashmo/Library/Developer/Xcode/Archives/2016-04-17/Jooy-Beta 2016-04-17 03.40.09.xcarchive"}
[03:40:47]: Shell command exited with exit status 1 instead of 0.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 11          |
| 4    | increment_build_number              | 1           |
| 5    | gym                                 | 29          |
| 6    | crashlytics                         | 8           |
| 7    | slack                               | 1           |
+------+-------------------------------------+-------------+

[03:40:47]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'f3ec564ead178c53629988107cc0af29'
The crash report has been stored locally '/tmp/sentry_f3ec564ead178c53629988107cc0af29.json'
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/actions/crashlytics.rb:32:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:62:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
    before_all do
        ENV["SLACK_URL"] = "https://hooks.slack.com/services/dummy"
        cocoapods
    end

    desc "Runs all the tests"
    lane :test do
        scan
    end

    desc "Submit a new Beta Build to Apple TestFlight"
    desc "This will also make sure the profile is up to date"
    lane :beta do
        # match(type: "appstore") # more information: https://codesigning.guide
        gym(scheme: "Jooy") # Build your app - more options available
        pilot
        # sh "your_script.sh"
        # You can also use other beta testing services here (run `fastlane actions`)
    end

    desc "Deploy a new version to the App Store"
    lane :appstore do
        # match(type: "appstore")
        # snapshot
        gym(scheme: "Jooy") # Build your app - more options available
        deliver(force: true)
        # frameit
    end

    # You can define as many lanes as you want
    desc "Submit a new Crashlytics Beta and send a notification to Slack."
    lane :CrashlyticsBeta do
        increment_build_number
        gym(
            use_legacy_build_api: true,
            workspace: "Jooy.xcworkspace",
            configuration: "Debug",
            scheme: "Jooy",
            silent: true,
            clean: true,
            output_directory: "../JooyBetaBuilds", # Destination directory. Defaults to current directory.
            output_name: "Jooy-Beta.ipa", # specify the name of the .ipa file to generate (including file extension)
        )
        crashlytics(
            crashlytics_path: 'Pods/Crashlytics/iOS/Crashlytics.framework', # path to your ‘Crashlytics.framework’
            api_token: 'dummy',
            build_secret: 'dummy',
            ipa_path: '../JooyBetaBuilds/Jooy-Beta.ipa',
            notes: 'Latest Beta build',
            groups: [“internal-testers”]
        )
        slack(
            message: "Beta App successfully released!"
        )
    end

    after_all do |lane|
        # This block is called, only if the executed lane was successful

        # slack(
        #   message: "Successfully deployed new App Update."
        # )
    end

    error do |lane, exception|
        slack(
            message: exception.message,
            success: false
        )
    end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

### Environment

fastlane version (run `fastlane -v`): 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by fisch0920** [comment]
Run:
`fastlane --verbose CrashlyticsBeta`

And then take the command that crashlytics runs and execute it yourself to see the `submit` command's output which will tell you the error you're encountering.  For some reason, crashlytics currently swallows the crashlytics submit output.

**Comment by slashmo** [comment]
@fisch0920 I followed your instructions and got this error:

``` shell
2016-04-18 14:17:52.347 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (17)
2016-04-18 14:17:59.139 submit Crashlytics: Could not read release notes file at path /var/folders/37/19tll0m15xl9c8f6nbltnbb00000gn/T/changelog20160418-2257-1tc39ej, error: The file “changelog20160418-2257-1tc39ej” couldn’t be opened because there is no such file.
```

**Comment by vpolouchkine** [comment]
Looks like the `crashlytics` action wasn't able to create a temp file to hold the `notes`.

**Comment by vpolouchkine** [comment]
Can you try specifying it using `notes_path` directly?

**Comment by manuyavuz** [comment]
Hi all,

I've faced with the same error. My problem turned out to be having a long release note. Following is the output of manually running `submit` script:

```
2016-04-21 21:18:08.306 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (17)
2016-04-21 21:18:13.490 submit Crashlytics: Unable to add release notes: Validation failed: Body is too long (maximum is 16384 characters)
2016-04-21 21:18:13.490 submit Crashlytics: Failed to add notes to the release
``

Issue with fastlane is that it does not print above output into the console. Seems like it only check for the exit status, it does not redirect `submit` output to stdout.

It'd be great if we could print the command output to fastlane output.

**Comment by slashmo** [comment]
@vpolouchkine Sorry for the late answer ✌🏻 Where can I set the ```notes_path```?

**Comment by TKBurner** [comment]
Hi Slashmo, Thanks for following up. You can set it as a parameter in your fastfile. "notes_path: path/to/notes"

Let me know how it goes!
