### ISSUE TITLE
Could not find a matching code signing identity for type 'AdHoc'. You can use cert to generate one: 

### ISSUE THREAD

**Issue by xareelee** [fastlane/fastlane#4243]
I'm using `fastlane 1.81.0` with `match 0.4.0` / `cert 1.4.0` / `sigh 1.6.1`.

I'm using `match` to manage certificates and provisioning profile as recommended. But when I use `match adhoc`, it will fail to create a provisioning profile after creating a new certificate.

I use `Fastfile` to use `match`

```ruby

lane :match_all do 
    # only match in this lane
    match(
      type: "adhoc", 
      git_url: ".....",
      app_identifier: "....",
      username: "....",
      team_id: "....",
      force_for_new_devices: true
    )
end
``` 

then run the lane:

```sh
$ fastlane match_all
```

Now, for the first time, the match call `cert` and `sigh` to create the certificate and provisioning profile:

```
[18:33:27]: -------------------
[18:33:27]: --- Step: match ---
[18:33:27]: -------------------

+-----------------------+-----------------------------------------------------------------------+
|                                    Summary for match 0.4.0                                    |
+-----------------------+-----------------------------------------------------------------------+
| type                  | adhoc                                                                 |
| git_url               | ... |
| app_identifier        | ...                                                    |
| username              | ...                                           |
| team_id               | ...                                                            |
| force_for_new_devices | true                                                                  |
| keychain_name         | login.keychain                                                        |
| readonly              | false                                                                 |
| verbose               | false                                                                 |
| force                 | false                                                                 |
| shallow_clone         | false                                                                 |
| skip_docs             | false                                                                 |
+-----------------------+-----------------------------------------------------------------------+

[18:33:27]: Cloning remote git repo...
[18:33:28]: 🔓  Successfully decrypted certificates repo
[18:33:28]: Verifying that the certificate and profile are still valid on the Dev Portal...
[18:33:32]: Couldn't find a valid code signing identity in the git repo for distribution... creating one for you now

+---------------+-----------------------------------------------+
|                    Summary for cert 1.4.0                     |
+---------------+-----------------------------------------------+
| development   | false                                         |
| force         | true                                          |
| username      | ...                   |
| keychain_path | ... |
+---------------+-----------------------------------------------+

[18:33:32]: Starting login with user '...'
[18:33:36]: Successfully logged in
[18:33:40]: $ security import /var/folders/rd/qql_h2jd5gjfstmbddq8b95r0000gn/T/d20160418-6685-131bop9/certs/distribution/E5U74YFE8B.p12 -k '/Users/Xaree/Library/Keychains/login.keychain' -T /usr/bin/codesign -T /usr/bin/security
[18:33:40]: ▸ 1 key imported.
[18:33:40]: $ security import /var/folders/rd/qql_h2jd5gjfstmbddq8b95r0000gn/T/d20160418-6685-131bop9/certs/distribution/E5U74YFE8B.cer -k '/Users/Xaree/Library/Keychains/login.keychain' -T /usr/bin/codesign -T /usr/bin/security
[18:33:40]: ▸ 1 certificate imported.
[18:33:40]: Successfully generated E5U74YFE8B which was imported to the local machine.
[18:33:50]: Verifying the certificated is properly installed locally...
[18:33:50]: Successfully installed certificate E5U74YFE8B

+-------------------------------------+--------------------------------+
|                        Summary for sigh 1.6.1                        |
+-------------------------------------+--------------------------------+
| app_identifier                      | ...             |
| adhoc                               | true                           |
| development                         | false                          |
| username                            | ...    |
| force                               | true                           |
| cert_id                             | ...                     |
| provisioning_name                   | match AdHoc ... |
| ignore_profiles_with_different_name | true                           |
| skip_install                        | false                          |
| skip_fetch_profiles                 | false                          |
| skip_certificate_verification       | false                          |
+-------------------------------------+--------------------------------+

[18:33:51]: Starting login with user '...'
[18:33:54]: Successfully logged in
[18:33:54]: Fetching profiles...
[18:33:56]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[18:33:58]: No certificates for filter: Certificate ID: '...' 
[18:33:58]: 🔒  Successfully encrypted certificates repo
[18:33:58]: Variable Dump:
[18:33:58]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios match_all"}
[18:33:58]: Could not find a matching code signing identity for type 'AdHoc'. You can use cert to generate one: 
https://github.com/fastlane/fastlane/tree/master/cert

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | opt_out_usage                       | 0           |
| 3    | default_platform                    | 0           |
| 4    | match                               | 30          |
+------+-------------------------------------+-------------+

[18:33:58]: fastlane finished with errors

[!] Could not find a matching code signing identity for type 'AdHoc'. You can use cert to generate one: 
```

> I delete replace some private values with `...` in the above report.

After succeed to create a new certificate with `cert`, `sigh` raise an error with **`No certificates for filter: Certificate ID: '...' `** and **`Could not find a matching code signing identity for type 'AdHoc'. You can use cert to generate one:`**

BTW, if the `type` is `development` or `appstore`, it will succeed to create the provisioning profile.

**Comment by vpolouchkine** [comment]
Are you running against an enterprise account?

**Comment by helveticafire** [comment]
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Unable to find matching profile...

I am having a similar problem, not running an enterprise account.

We were trying to add a new device following some of the issues in this repo but `match development --force seems to be broken`
![screen shot 2016-06-15 at 11 21 22](https://cloud.githubusercontent.com/assets/1323872/16074593/75e471b0-32eb-11e6-8344-2acd7a951708.png)


##### Complete output when running fastlane, including the stack trace and command used

```
match --verbose development --force

+-----------------------+-----------------------------------------+
|                     Summary for match 0.6.1                     |
+-----------------------+-----------------------------------------+
| verbose               | development                             |
| force                 | true                                    |
| git_url               | git@github.com:org-name/repo-name |
| type                  | development                             |
| app_identifier        | com.test.test                      |
| username              | someusername@test.co                       |
| git_branch            | master                                  |
| keychain_name         | login.keychain                          |
| readonly              | false                                   |
| team_id               | alphanumeric                              |
| shallow_clone         | false                                   |
| force_for_new_devices | false                                   |
| skip_docs             | false                                   |
+-----------------------+-----------------------------------------+

INFO [2016-06-15 11:39:31.78]: Cloning remote git repo...
INFO [2016-06-15 11:39:31.78]: $ git clone 'git@github.com:org-name/repo-name' '/var/folders/z7/n4nj0mkn0m904czfl1grw6ym0000gn/T/d20160615-98123-g0oai'
INFO [2016-06-15 11:39:31.87]: ▸ Cloning into '/var/folders/z7/n4nj0mkn0m904czfl1grw6ym0000gn/T/d20160615-98123-g0oai'...
INFO [2016-06-15 11:39:35.14]: ▸ remote: Counting objects: 101, done.
INFO [2016-06-15 11:39:35.72]: ▸ remote: Total 101 (delta 0), reused 0 (delta 0), pack-reused 101
INFO [2016-06-15 11:39:35.72]: ▸ Receiving objects: 100% (101/101), 152.47 KiB | 204.00 KiB/s, done.
INFO [2016-06-15 11:39:35.72]: ▸ Resolving deltas: 100% (10/10), done.
INFO [2016-06-15 11:39:36.04]: ▸ Checking connectivity... done.
INFO [2016-06-15 11:39:36.19]: 🔓  Decrypted 'alphanumeric-1.cer'
INFO [2016-06-15 11:39:36.25]: 🔓  Decrypted 'alphanumeric-2.cer'
INFO [2016-06-15 11:39:36.31]: 🔓  Decrypted 'alphanumeric-3.cer'
INFO [2016-06-15 11:39:36.35]: 🔓  Decrypted 'alphanumeric-4.cer'
INFO [2016-06-15 11:39:36.41]: 🔓  Decrypted 'alphanumeric-1.p12'
INFO [2016-06-15 11:39:36.45]: 🔓  Decrypted 'alphanumeric-2.p12'
INFO [2016-06-15 11:39:36.52]: 🔓  Decrypted 'alphanumeric-3.p12'
INFO [2016-06-15 11:39:36.56]: 🔓  Decrypted 'alphanumeric-4.p12'
INFO [2016-06-15 11:39:36.62]: 🔓  Decrypted 'AdHoc_com.test.test.mobileprovision'
INFO [2016-06-15 11:39:36.69]: 🔓  Decrypted 'AppStore_com.test.test.mobileprovision'
INFO [2016-06-15 11:39:36.77]: 🔓  Decrypted 'Development_com.test.test.mobileprovision'
INFO [2016-06-15 11:39:36.77]: 🔓  Successfully decrypted certificates repo
INFO [2016-06-15 11:39:36.82]: Verifying that the certificate and profile are still valid on the Dev Portal...
INFO [2016-06-15 11:39:51.76]: Installing certificate...
INFO [2016-06-15 11:39:51.76]: $ security list-keychains -d user
INFO [2016-06-15 11:39:51.78]: ▸     "/Users/NAME_OF_USER/Library/Keychains/login.keychain"
INFO [2016-06-15 11:39:51.78]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/NAME_OF_USER/Library/Keychains/login.keychain
INFO [2016-06-15 11:39:51.81]: ▸ keychain: "/Users/NAME_OF_USER/Library/Keychains/login.keychain"
INFO [2016-06-15 11:39:51.81]: ▸ version: 256
INFO [2016-06-15 11:39:51.81]: ▸ class: 0x80001000
INFO [2016-06-15 11:39:51.81]: ▸ attributes:
INFO [2016-06-15 11:39:51.81]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-06-15 11:39:51.81]: ▸     "cenc"<uint32>=0x00000003
INFO [2016-06-15 11:39:51.81]: ▸     "ctyp"<uint32>=0x00000001
INFO [2016-06-15 11:39:51.81]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-06-15 11:39:51.81]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2016-06-15 11:39:51.81]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-06-15 11:39:51.81]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-06-15 11:39:51.81]: ▸     "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"
INFO [2016-06-15 11:39:51.82]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
INFO [2016-06-15 11:39:52.37]: $ security import /var/folders/z7/n4nj0mkn0m904czfl1grw6ym0000gn/T/d20160615-98123-g0oai/certs/development/alphanumeric.cer -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign -T /usr/bin/security&> /dev/null
INFO [2016-06-15 11:39:52.44]: $ security import /var/folders/z7/n4nj0mkn0m904czfl1grw6ym0000gn/T/d20160615-98123-g0oai/certs/development/alphanumeric.p12 -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign -T /usr/bin/security&> /dev/null

+-------------------------------------+--------------------------------------+
|                           Summary for sigh 1.8.0                           |
+-------------------------------------+--------------------------------------+
| app_identifier                      | com.test.test                   |
| adhoc                               | false                                |
| development                         | true                                 |
| username                            | someusername@test.co                    |
| force                               | true                                 |
| cert_id                             | alphanumeric                           |
| provisioning_name                   | match Development com.test.test |
| ignore_profiles_with_different_name | true                                 |
| team_id                             | alphanumeric                           |
| skip_install                        | false                                |
| skip_fetch_profiles                 | false                                |
| skip_certificate_verification       | false                                |
+-------------------------------------+--------------------------------------+

INFO [2016-06-15 11:39:53.73]: Starting login with user 'someusername@test.co'
INFO [2016-06-15 11:39:57.80]: Successfully logged in
INFO [2016-06-15 11:39:57.80]: Fetching profiles...
WARN [2016-06-15 11:39:58.85]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
WARN [2016-06-15 11:40:00.72]: No certificates for filter: Certificate ID: 'alphanumeric'
INFO [2016-06-15 11:40:00.72]: 🔒  Successfully encrypted certificates repo
/Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Could not find a matching code signing identity for type 'Development'. You can use cert to generate one:  (FastlaneCore::Interface::FastlaneError)
https://github.com/fastlane/fastlane/tree/master/cert
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/sigh-1.8.0/lib/sigh/runner.rb:167:in `certificate_to_use'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/sigh-1.8.0/lib/sigh/runner.rb:101:in `create_profile!'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/sigh-1.8.0/lib/sigh/runner.rb:39:in `run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/sigh-1.8.0/lib/sigh/manager.rb:7:in `start'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/generator.rb:57:in `generate_provisioning_profile'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/runner.rb:84:in `profile'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/runner.rb:21:in `run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/commands_generator.rb:121:in `run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/commands_generator.rb:12:in `start'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/bin/match:6:in `<top (required)>'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/bin/match:23:in `load'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/bin/match:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.95.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Submit build to Apple TestFlight"
  lane :testflight do
    match(type: "appstore")
    sh("../../../../util/new-build-number")
    gym(scheme: "Fy Release", clean: true, use_legacy_build_api: true, output_directory: "build")

    # use different delivery mechanism
    # see https://github.com/fastlane/fastlane/issues/2294

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    pilot(skip_submission: true, skip_waiting_for_build_processing: true)
  end

  desc "Build dev IPA"
  lane :devipa do
    match(type: "adhoc")
    gym(scheme: "Fy Release", clean: false, use_legacy_build_api: true,
        output_directory: "build",
        xcargs: "CODE_SIGN_IDENTITY=\"iPhone Developer\"")
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```

Matchfile:
```ruby
git_url "git@github.com:Project-J/fastlane-match"

type "development" # The default type, can be: appstore, adhoc or development

app_identifier "com.projectj.iamfy"
username "someusername@projectj.co" # Your Apple Developer Portal username

# For all available options run `match --help`
# Remove the # in the beginning of the line to enable the other options
```

### Environment

fastlane version 1.95.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm 1.27.0
ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]

**Comment by TKBurner** [comment]
@helveticafire Thanks for writing in. Can you let me know why you are running sigh after Match? You shouldn't need to do this. Thanks!

**Comment by helveticafire** [comment]
From looking at the fastlane code I believe using `--force` calls sigh manager https://github.com/fastlane/fastlane/blob/master/match/lib/match/generator.rb#L36 which calls https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/runner.rb which outputs sigh config.

**Comment by TKBurner** [comment]
Hi @helveticafire Can you try setting the `keychain_name` and also the `force_for_new_devices` parameters? Let me know if that clears things up and if it doesn't share the full output again. Thanks! 👍

**Comment by helveticafire** [comment]
Hi @TKBurner, 
Is this command, what you had in mind?

`match --verbose development --force keychain_name=login.keychain force_for_new_devices=true`

```
+-----------------------+-----------------------------------------+
|                     Summary for match 0.6.1                     |
+-----------------------+-----------------------------------------+
| verbose               | development                             |
| force                 | keychain_name=login.keychain            |
| git_url               | git@github.com:org-name/repo-name 	  |
| type                  | development                             |
| app_identifier        | com.test.test                      	  |
| username              | someusername@test.co              	  |
| git_branch            | master                                  |
| keychain_name         | login.keychain                          |
| readonly              | false                                   |
| team_id               | alphanumeric                            |
| shallow_clone         | false                                   |
| force_for_new_devices | false                                   |
| skip_docs             | false                                   |
+-----------------------+-----------------------------------------+

INFO [2016-06-21 11:23:07.62]: Cloning remote git repo...
INFO [2016-06-21 11:23:07.62]: $ git clone 'git@github.com:org-name/repo-name' '/var/folders/z7/n4nj0mkn0m904czfl1grw6ym0000gn/T/d20160621-5979-1dxz8am'
INFO [2016-06-21 11:23:07.69]: ▸ Cloning into '/var/folders/z7/n4nj0mkn0m904czfl1grw6ym0000gn/T/d20160621-5979-1dxz8am'...
INFO [2016-06-21 11:23:09.96]: ▸ remote: Counting objects: 101, done.
INFO [2016-06-21 11:23:10.65]: ▸ remote: Total 101 (delta 0), reused 0 (delta 0), pack-reused 101
INFO [2016-06-21 11:23:10.66]: ▸ Receiving objects: 100% (101/101), 152.47 KiB | 155.00 KiB/s, done.
INFO [2016-06-21 11:23:10.66]: ▸ Resolving deltas: 100% (10/10), done.
INFO [2016-06-21 11:23:10.82]: ▸ Checking connectivity... done.
INFO [2016-06-21 11:23:10.93]: 🔓  Decrypted 'alphanumeric-1.cer'
INFO [2016-06-21 11:23:10.97]: 🔓  Decrypted 'alphanumeric-2.cer'
INFO [2016-06-21 11:23:11.01]: 🔓  Decrypted 'alphanumeric-3.cer'
INFO [2016-06-21 11:23:11.07]: 🔓  Decrypted 'alphanumeric-4.cer'
INFO [2016-06-21 11:23:11.11]: 🔓  Decrypted 'alphanumeric-1.p12'
INFO [2016-06-21 11:23:11.17]: 🔓  Decrypted 'alphanumeric-2.p12'
INFO [2016-06-21 11:23:11.21]: 🔓  Decrypted 'alphanumeric-3.p12'
INFO [2016-06-21 11:23:11.27]: 🔓  Decrypted 'alphanumeric-4.p12'
INFO [2016-06-21 11:23:11.31]: 🔓  Decrypted 'AdHoc_com.test.test.mobileprovision'
INFO [2016-06-21 11:23:11.37]: 🔓  Decrypted 'AppStore_com.test.test.mobileprovision'
INFO [2016-06-21 11:23:11.41]: 🔓  Decrypted 'Development_com.test.test.mobileprovision'
INFO [2016-06-21 11:23:11.41]: 🔓  Successfully decrypted certificates repo
INFO [2016-06-21 11:23:11.45]: Verifying that the certificate and profile are still valid on the Dev Portal...
INFO [2016-06-21 11:23:26.45]: Installing certificate...
INFO [2016-06-21 11:23:26.45]: $ security list-keychains -d user
INFO [2016-06-21 11:23:26.46]: ▸     "/Users/NAME_OF_USER/Library/Keychains/login.keychain"
INFO [2016-06-21 11:23:26.46]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/NAME_OF_USER/Library/Keychains/login.keychain
INFO [2016-06-21 11:23:26.50]: ▸ keychain: "/Users/NAME_OF_USER/Library/Keychains/login.keychain"
INFO [2016-06-21 11:23:26.50]: ▸ version: 256
INFO [2016-06-21 11:23:26.50]: ▸ class: 0x80001000
INFO [2016-06-21 11:23:26.50]: ▸ attributes:
INFO [2016-06-21 11:23:26.50]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-06-21 11:23:26.50]: ▸     "cenc"<uint32>=0x00000003
INFO [2016-06-21 11:23:26.50]: ▸     "ctyp"<uint32>=0x00000001
INFO [2016-06-21 11:23:26.50]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-06-21 11:23:26.50]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2016-06-21 11:23:26.50]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-06-21 11:23:26.50]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-06-21 11:23:26.50]: ▸     "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"
INFO [2016-06-21 11:23:26.50]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
INFO [2016-06-21 11:23:27.01]: $ security import /var/folders/z7/n4nj0mkn0m904czfl1grw6ym0000gn/T/d20160621-5979-1dxz8am/certs/development/alphanumeric.cer -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign -T /usr/bin/security&> /dev/null
INFO [2016-06-21 11:23:27.08]: $ security import /var/folders/z7/n4nj0mkn0m904czfl1grw6ym0000gn/T/d20160621-5979-1dxz8am/certs/development/alphanumeric.p12 -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign -T /usr/bin/security&> /dev/null

+-------------------------------------+--------------------------------------+
|                           Summary for sigh 1.8.0                           |
+-------------------------------------+--------------------------------------+
| app_identifier                      | com.test.test                        |
| adhoc                               | false                                |
| development                         | true                                 |
| username                            | someusername@test.co                 |
| force                               | true                                 |
| cert_id                             | alphanumeric                         |
| provisioning_name                   | match Development com.test.test      |
| ignore_profiles_with_different_name | true                                 |
| team_id                             | alphanumeric                         |
| skip_install                        | false                                |
| skip_fetch_profiles                 | false                                |
| skip_certificate_verification       | false                                |
+-------------------------------------+--------------------------------------+

INFO [2016-06-21 11:23:28.16]: Starting login with user 'someusername@test.co'
INFO [2016-06-21 11:23:31.37]: Successfully logged in
INFO [2016-06-21 11:23:31.37]: Fetching profiles...
WARN [2016-06-21 11:23:32.40]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
WARN [2016-06-21 11:23:34.14]: No certificates for filter: Certificate ID: 'alphanumeric'
INFO [2016-06-21 11:23:34.20]: 🔒  Successfully encrypted certificates repo
/Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Could not find a matching code signing identity for type 'Development'. You can use cert to generate one:  (FastlaneCore::Interface::FastlaneError)
https://github.com/fastlane/fastlane/tree/master/cert
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/sigh-1.8.0/lib/sigh/runner.rb:167:in `certificate_to_use'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/sigh-1.8.0/lib/sigh/runner.rb:101:in `create_profile!'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/sigh-1.8.0/lib/sigh/runner.rb:39:in `run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/sigh-1.8.0/lib/sigh/manager.rb:7:in `start'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/generator.rb:57:in `generate_provisioning_profile'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/runner.rb:84:in `profile'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/runner.rb:21:in `run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/commands_generator.rb:121:in `run'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/lib/match/commands_generator.rb:12:in `start'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/gems/match-0.6.1/bin/match:6:in `<top (required)>'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/bin/match:23:in `load'
	from /Users/NAME_OF_USER/.rvm/gems/ruby-2.2.1@fy-ios/bin/match:23:in `<main>'
```

**Comment by TKBurner** [comment]
Hi @helveticafire! Thanks for following up. I noticed a few weird things. Verbose should be set to true, not development. You have alphanumeric as both your team name and cert_id is that correct?

Thanks!

**Comment by KrauseFx** [comment]
It seems like the certificate is not available on the Apple Developer Portal. Could you send a screenshot of the certificate list too? Did someone revoke your certificate maybe?

**Comment by xareelee** [comment]
@vpolouchkine 

Sorry for that I didn't follow this issue for a few months.

Yes, it is an **enterprise account**. And I currently do not use ad_hoc for this account anymore. But I still want to know what happened.

Thanks!

**Comment by KrauseFx** [comment]
Have you seen our new [Code Signing Guide](https://github.com/fastlane/fastlane/tree/master/fastlane/docs/Codesigning) yet? 👍

**Comment by xareelee** [comment]
After updating fastlane, I think this problem has been solved.

**Comment by TKBurner** [comment]
@xareelee Awesome! Thanks so much for letting us know. Closing this out.
