### ISSUE TITLE
No such file or directory - pod

### ISSUE THREAD

**Issue by fabioknoedt** [fastlane/fastlane#4247]
Hey guys,

I'm running in a weird error... from time to time `Fastlane` fails to run `cocoapods` in my CI environment (Mac OS X 10.11 using Bamboo agent).
If I run `pod install` outside of `Fastlane`, eveything works fine. When I run `cocoapods` inside of `Fastlane` `lane`, it fails:

```
  desc "Testing"
  lane :test do

    # Cocoapods install.
    cocoapods

    # Run all unit tests.
    scan

  end
```

```
18-Apr-2016 16:53:50	[16:53:50]: -----------------------
18-Apr-2016 16:53:50	[16:53:50]: --- Step: cocoapods ---
18-Apr-2016 16:53:50	[16:53:50]: -----------------------
18-Apr-2016 16:53:50	[16:53:50]: $ pod install
18-Apr-2016 16:53:50	[16:53:50]: Variable Dump:
18-Apr-2016 16:53:50	[16:53:50]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
18-Apr-2016 16:53:50	[16:53:50]: No such file or directory - pod
18-Apr-2016 16:53:50	
18-Apr-2016 16:53:50	+------+-------------------------------------+-------------+
18-Apr-2016 16:53:50	|                     fastlane summary                     |
18-Apr-2016 16:53:50	+------+-------------------------------------+-------------+
18-Apr-2016 16:53:50	| Step | Action                              | Time (in s) |
18-Apr-2016 16:53:50	+------+-------------------------------------+-------------+
18-Apr-2016 16:53:50	| 1    | Verifying required fastlane version | 0           |
18-Apr-2016 16:53:50	| 2    | default_platform                    | 0           |
18-Apr-2016 16:53:50	| 3    | cocoapods                           | 0           |
18-Apr-2016 16:53:50	| 4    | reset_git_repo                      | 0           |
18-Apr-2016 16:53:50	| 5    | clean_build_artifacts               | 0           |
18-Apr-2016 16:53:50	+------+-------------------------------------+-------------+
18-Apr-2016 16:53:50	
18-Apr-2016 16:53:50	[16:53:50]: fastlane finished with errors
18-Apr-2016 16:53:52	Successfully submitted a crash report. If this is a problem with one of the tools specifically,
18-Apr-2016 16:53:52	please submit an issue on GitHub and attach the following number to it: 'bffb92b21bb6b15a085139e3137bc5d4'
18-Apr-2016 16:53:52	The crash report has been stored locally '/tmp/sentry_bffb92b21bb6b15a085139e3137bc5d4.json'
18-Apr-2016 16:53:52	/Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:26:in `popen': [!] No such file or directory - pod (Errno::ENOENT)
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:26:in `sh_no_action'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/cocoapods.rb:27:in `run'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
18-Apr-2016 16:53:52	        from Fastfile:22:in `block (2 levels) in parsing_binding'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
18-Apr-2016 16:53:52	        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
18-Apr-2016 16:53:52	        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
18-Apr-2016 16:53:52	        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
18-Apr-2016 16:53:52	        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
18-Apr-2016 16:53:52	        from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
18-Apr-2016 16:53:52	        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
18-Apr-2016 16:53:52	        from /Users/<user>/.gem/ruby/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
18-Apr-2016 16:53:52	        from /usr/local/bin/fastlane:23:in `load'
18-Apr-2016 16:53:52	        from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by fabioknoedt** [comment]
I could fix the issue passing the `PATH` as an environment variable in the `Bamboo` plan:
`PATH="/usr/local/bin"`

<img width="718" alt="screen shot 2016-04-18 at 20 01 13" src="https://cloud.githubusercontent.com/assets/5463775/14614420/69be754c-05a1-11e6-84e8-72c9526b7198.png">

But it's very weird that `Fastlane` couldn't find `cocoapods` even with `PATH` defined in the `~./profile` and `~./bash_profile` files.

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll take a look.

**Comment by TKBurner** [comment]
@fabioknoedt Glad to hear you got around this with an environmental variable. It seems like the reason you need to pass this is a config on your local machine. For now keep passing the podfile as a parameter. Thanks! 👍
