### ISSUE TITLE
Help with importing actions from git

### ISSUE THREAD

**Issue by lcoderre** [fastlane/fastlane#4257]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to import **actions** from a remote git.  Importing **lanes** seems to work, but **not actions**. Down in the example below, if I were to move the three `carthage` calls directly in the lane instead of the action, it works. Why does it fail to see `carthage` as an available action? Can't we use actions in another action?

Thanks.

##### Complete output when running fastlane, including the stack trace and command used

```
lcoderre@macbook ~/dev/framework (master)$ fastlane                                                                                                                                                                       [2.1.3]
[08:13:00]: -----------------------------
[08:13:00]: --- Step: import_from_git ---
[08:13:00]: -----------------------------
[08:13:00]: Cloning remote git repo...
[08:13:00]: $ git clone 'MY_GIT_URL' '/var/folders/tr/lvy0p6xs6l3cjmb7mfs1s9h00000gn/T/fl_clone20160419-19492-1qimciq/fastlane-common.git' --depth 1 -n
[08:13:00]: ▸ Cloning into '/var/folders/tr/lvy0p6xs6l3cjmb7mfs1s9h00000gn/T/fl_clone20160419-19492-1qimciq/fastlane-common.git'...
[08:13:04]: $ cd '/var/folders/tr/lvy0p6xs6l3cjmb7mfs1s9h00000gn/T/fl_clone20160419-19492-1qimciq/fastlane-common.git' && git checkout HEAD 'fastlane/Fastfile'
[08:13:04]: $ cd '/var/folders/tr/lvy0p6xs6l3cjmb7mfs1s9h00000gn/T/fl_clone20160419-19492-1qimciq/fastlane-common.git' && git checkout HEAD 'fastlane/actions'
[08:13:04]: -------------------------------------------------
[08:13:04]: --- Step: Verifying required fastlane version ---
[08:13:04]: -------------------------------------------------
[08:13:04]: fastlane version valid
[08:13:04]: ------------------------------
[08:13:04]: --- Step: default_platform ---
[08:13:04]: ------------------------------
[08:13:04]: Successfully loaded custom action '/var/folders/tr/lvy0p6xs6l3cjmb7mfs1s9h00000gn/T/fl_clone20160419-19492-1qimciq/fastlane-common.git/fastlane/actions/build_framework.rb'.
[08:13:04]: Successfully loaded custom action '/var/folders/tr/lvy0p6xs6l3cjmb7mfs1s9h00000gn/T/fl_clone20160419-19492-1qimciq/fastlane-common.git/fastlane/actions/find_release_assets.rb'.
[08:13:04]: Clearing the git repo...
[08:13:04]: $ rm -rf '/var/folders/tr/lvy0p6xs6l3cjmb7mfs1s9h00000gn/T/fl_clone20160419-19492-1qimciq'
[08:13:04]: Welcome to fastlane! Here's what your app is setup to do:
+--------+-----------------------+------------------------------------+
|                       Available lanes to run                        |
+--------+-----------------------+------------------------------------+
| Number | Lane Name             | Description                        |
+--------+-----------------------+------------------------------------+
| 1      | ios make_framework    | Builds the current *.framework.zip |
| 2      | ios framework_release | Build and release to github        |
| 0      | cancel                | No selection, exit fastlane!       |
+--------+-----------------------+------------------------------------+
Which number would you like run?
1
[08:13:07]: Running lane `ios make_framework`. Next time you can do this by directly typing `fastlane ios make_framework` 🚀.
[08:13:07]: Driving the lane 'ios make_framework' 🚀
[08:13:07]: -----------------------------
[08:13:07]: --- Step: build_framework ---
[08:13:07]: -----------------------------
[08:13:07]: Variable Dump:
[08:13:07]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios make_framework"}
[08:13:07]: undefined method `carthage' for Fastlane::Actions::BuildFrameworkAction:Class

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | import_from_git                     | 3           |
| 4    | build_framework                     | 0           |
+------+-------------------------------------+-------------+

[08:13:07]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/var/folders/tr/lvy0p6xs6l3cjmb7mfs1s9h00000gn/T/fl_clone20160419-19492-1qimciq/fastlane-common.git/fastlane/actions/build_framework.rb:15:in `run': [!] undefined method `carthage' for Fastlane::Actions::BuildFrameworkAction:Class (NoMethodError)
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from ../../../../../var/folders/tr/lvy0p6xs6l3cjmb7mfs1s9h00000gn/T/fl_clone20160419-19492-1qimciq/fastlane-common.git/fastlane/Fastfile:21:in `block (2 levels) in parsing_binding'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Users/lcoderre/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /Users/lcoderre/.rbenv/versions/2.1.3/bin/fastlane:23:in `load'
	from /Users/lcoderre/.rbenv/versions/2.1.3/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

local Fastfile:
```ruby

import_from_git(url: remote_git_url_with_my_fastlane_common_files')

platform :ios do
  before_all do
    ENV["FL_VERSION_NUMBER_PROJECT"] = "MyFramework/MyFramework.xcodeproj"
    ENV["FL_BUILD_NUMBER_PROJECT"] = "MyFramework/MyFramework.xcodeproj"
  end

  # You can define as many lanes as you want
  after_all do |lane|
  end

  error do |lane, exception|
  end
end
```
remote (common) `fastlane/Fastfile`
```ruby
fastlane_version "1.81.0"

default_platform :ios

platform :ios do

  desc 'Builds the current *.framework.zip'
  lane :make_framework do |variable|
    build_framework
  end

end
```

remote (common) in `fastlane/actions/build_framework`
```ruby
module Fastlane
  module Actions
    module SharedValues
      # BUILD_FRAMEWORK_CUSTOM_VALUE = :BUILD_FRAMEWORK_CUSTOM_VALUE
    end

    class BuildFrameworkAction < Action
      def self.run(params)
        carthage(command: 'update', use_ssh:true, platform: "iOS")
        carthage(command: 'build', no_skip_current:true, platform: 'iOS')
        carthage(command: 'archive')
      end

      def self.description
        "Builds the current framework and outputs  release-ready .framework files"
      end

      def self.authors
        ["lcoderre"]
      end

      def self.is_supported?(platform)
        platform == :ios
      end
    end
  end
end
```

### Environment

fastlane version (run `fastlane -v`): `fastlane 1.81.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv yes

**Comment by mfurtak** [comment]
Hi @lcoderre 👋 

While it is possible to call actions from another action, it is not recommended, so that simple example you've shown will not work.

A simpler solution for code reuse within your `Fastfile`s is to use a [private lane](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#private-lanes). 

```ruby
desc 'Builds the current *.framework.zip'
lane :make_framework do |variable|
  build_framework
end

desc 'Builds the current framework and outputs  release-ready .framework files'
private_lane :build_framework do |options|
  carthage(command: 'update', use_ssh:true, platform: "iOS")
  carthage(command: 'build', no_skip_current:true, platform: 'iOS')
  carthage(command: 'archive')
end
```

Let me know if that works for your needs! 👍

**Comment by lcoderre** [comment]
Oh I see.  In that case, would it be possible to separate all my private lanes in different fastfiles but import them all once?

**Comment by mfurtak** [comment]
Sure, I think that could work. Let me know what you find! 🙌

**Comment by TKBurner** [comment]
Closing this issue out. Happy coding @lcoderre! 👊
