### ISSUE TITLE
scan crashes on master branch

### ISSUE THREAD

**Issue by bartoszj** [fastlane/fastlane#4316]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The `scan` crashes on the master branch. The main problem is that, the `:formatter` parameter with short version `:t` is conflicting with the `-t` / trace argument from `fastlane_core`. Second problem is that, the `CommanderGenerator.validate_short_switch` method is using undefined local variable `option`.

##### Stack trace 1:

```
/Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/ui/interface.rb:139:in `user_error!': -t is already used for the trace screen (key formatter) (FastlaneCore::Interface::FastlaneError)
	from /Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/configuration/commander_generator.rb:77:in `validate_short_switch'
	from /Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/configuration/commander_generator.rb:18:in `block in generate'
	from /Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/configuration/commander_generator.rb:13:in `each'
	from /Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/configuration/commander_generator.rb:13:in `generate'
	from /Users/bjanda/Documents/OtherProjects/fastlane/scan/lib/scan/commands_generator.rb:10:in `<class:CommandsGenerator>'
	from /Users/bjanda/Documents/OtherProjects/fastlane/scan/lib/scan/commands_generator.rb:7:in `<module:Scan>'
	from /Users/bjanda/Documents/OtherProjects/fastlane/scan/lib/scan/commands_generator.rb:6:in `<top (required)>'
	from ./bin/scan:5:in `require'
	from ./bin/scan:5:in `<main>'
```

##### Stack trace 2:
```
/Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/configuration/commander_generator.rb:76:in `validate_short_switch': undefined local variable or method `option' for #<FastlaneCore::CommanderGenerator:0x007fd89bac0938> (NameError)
    from /Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/configuration/commander_generator.rb:17:in `block in generate'
    from /Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/configuration/commander_generator.rb:13:in `each'
    from /Users/bjanda/.bundle/ruby/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/configuration/commander_generator.rb:13:in `generate'
    from /Users/bjanda/Documents/OtherProjects/fastlane/scan/lib/scan/commands_generator.rb:10:in `<class:CommandsGenerator>'
    from /Users/bjanda/Documents/OtherProjects/fastlane/scan/lib/scan/commands_generator.rb:7:in `<module:Scan>'
    from /Users/bjanda/Documents/OtherProjects/fastlane/scan/lib/scan/commands_generator.rb:6:in `<top (required)>'
    from ./bin/scan:5:in `require'
    from ./bin/scan:5:in `<main>'
```

### Environment

master branch, commit: `c60edbf`

### Suggested solution:
- fix the `validate_short_switch`
- change `:formatter` (`-t`) to something else.

**Comment by mfurtak** [comment]
Resolved with #4317
