### ISSUE TITLE
"undefined method `strip' for nil:NilClass" during init

### ISSUE THREAD

**Issue by simonarcher** [fastlane/fastlane#4330]
### New Issue Checklist

- [YES] Updated fastlane to the latest version
- [YES] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Installing Fastlane for the first time. Installation appears to have been succesfull.
Trying to add Fastlane to project, getting setup errors

##### Complete output when running fastlane, including the stack trace and command used

```
Simons-MacBook-Pro:MyAppFolder $ fastlane init
[22:08:53]: Detected iOS/Mac project in current directory...
[22:08:53]: This setup will help you get up and running in no time.
[22:08:53]: fastlane will check what tools you're already using and set up
[22:08:53]: the tool automatically for you. Have fun! 
[22:08:53]: Created new folder './fastlane'.
[22:08:53]: xcrun xcodebuild -list -workspace './xxxx.xcworkspace'
2016-04-22 22:08:53.957 xcodebuild[22350:37013201] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-22 22:08:54.991 xcodebuild[22361:37013268] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Your Apple ID (e.g. fastlane@krausefx.com): xxxxxx@xxxxxxx.xxx
[22:09:06]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[22:09:06]: Starting login with user 'xxxxx@xxxxxxxx.xx'
[22:09:09]: undefined method `strip' for nil:NilClass
[22:09:09]: An error occured during the setup process. Falling back to manual setup!
App Identifier (com.krausefx.app): XXXXXXXXXXX
[22:09:14]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
Would you like to create your app on iTunes Connect and the Developer Portal? (y/n)
y
[22:09:15]: Creating the app on iTunes Connect and the Apple Developer Portal
xcodebuild: error: If you specify a workspace then you must also specify a scheme.  Use -list to see the schemes in this workspace.

+----------------+---------------------------+
|         Summary for produce 1.1.1          |
+----------------+---------------------------+
| app_name       | App                       |
| app_identifier | XXXXXXXXXXX |
| username       | XXXXXXXXXXX    |
| sku            | XXXXXXXXXXX                |
| language       | English                   |
| skip_itc       | false                     |
| skip_devcenter | false                     |
| team_id        | [[DEV_PORTAL_TEAM_ID]]    |
+----------------+---------------------------+

[22:09:18]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[22:09:18]: Starting login with user 'xxxx@xxxxxx.xxx'
[22:09:21]: Error occurred with the setup program! Reverting changes now!
[22:09:21]: Deleting the 'fastlane' folder
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '8a19831471d5268413e87cd61ab0b829'
The crash report has been stored locally '/tmp/sentry_8a19831471d5268413e87cd61ab0b829.json'
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/net/http/header.rb:18:in `block in initialize_http_header': [!] undefined method `strip' for nil:NilClass (NoMethodError)
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/net/http/header.rb:16:in `each'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
DELETED DURING SETUP
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Not to my knowledge

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? None to my knowledge. Installed Ruby via homebrew

**Comment by TKBurner** [comment]
Hi @simonarcher Do you have a .xcodeproj file in this folder? If not, are you able to run the command:

xcrun xcodebuild -list -workspace './xxxx.xcworkspace'

It looks like this issue is either with your config or further up the chain. Thanks

**Comment by simonarcher** [comment]
Hi @TKBurner , when I run 'fastlane init' i do indeed have a .xcodeproj in my folder.

this is my folder when i run 'fastlane init' (and when I get the errors)

<img width="206" alt="image" src="https://cloud.githubusercontent.com/assets/10696147/14820689/fa2ccb98-0bc7-11e6-9884-7135d09f3112.png">

**Comment by TKBurner** [comment]
Thanks for following up @simonarcher. Are you able to run 
xcrun xcodebuild -list -workspace './xxxx.xcworkspace'?

Thanks!

**Comment by simonarcher** [comment]
Sure, @TKBurner !

this is the output.. (running this after the fastlane init fails and it deletes the fastlane files from my project folder)

`$ xcrun xcodebuild -list -workspace './MyApp.xcworkspace'
2016-04-26 17:02:49.753 xcodebuild[41288:525742] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Information about workspace "MyApp":
    Schemes:
        MyApp
        AKPickerView-Swift
        FLAnimatedImage
        FSCalendar
        JGProgressHUD
        LiquidFloatingActionButton
        LiquidFloatingActionButton-LiquidFloatingActionButton
        MBProgressHUD
        PickerView
        PickerView-PickerView
        PINCache
        PINRemoteImage
        Pods
        SwiftyJSON
$ `

**Comment by TKBurner** [comment]
Hi @simonarcher! Thanks for following up. This seems like it is a config issue.

 Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present i

Do you use FuzzyAutocomplete? We simply implement xcrun so it seems like it's not Fastlane related. 

Thanks!
