### ISSUE TITLE
invalid option: -c

### ISSUE THREAD

**Issue by goodcyg** [fastlane/fastlane#4354]
$ set -o pipefail && krausefx-ipa build -c "Release" -s "fastlanedemo" -d "./build" --ipa "fastlanedemo_1.2.2.22_InHouse.ipa" --no-archive --verbose | xcpretty
[00:01:05]: ▸ invalid option: -c
[00:01:05]: ▸ /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- aws-sdk (LoadError)
[00:01:05]: ▸ from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[00:01:05]: ▸ from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/plugins/s3.rb:1:in `<top (required)>'
[00:01:05]: ▸ from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[00:01:05]: ▸ from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[00:01:05]: ▸ from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/commands.rb:9:in `<top (required)>'
[00:01:05]: ▸ from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[00:01:05]: ▸ from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[00:01:05]: ▸ from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/gems/krausefx-shenzhen-0.14.7/bin/krausefx-ipa:25:in `<top (required)>'
[00:01:05]: ▸ from /Users/Jackson/.rvm/rubies/ruby-2.2.4/bin/krausefx-ipa:23:in `load'
[00:01:05]: ▸ from /Users/Jackson/.rvm/rubies/ruby-2.2.4/bin/krausefx-ipa:23:in `<main>'
[00:01:05]: ▸ from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `eval'
[00:01:05]: ▸ from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `<main>'
[00:01:05]: -------------------------------------------------------
[00:01:05]: Original Error:
[00:01:05]:  => Exit status of command 'set -o pipefail && krausefx-ipa build -c "Release" -s "fastlanedemo" -d "./build" --ipa "fastlanedemo_1.2.2.22_InHouse.ipa" --no-archive --verbose | xcpretty' was 1 instead of 0.
invalid option: -c
/Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- aws-sdk (LoadError)
	from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/plugins/s3.rb:1:in `<top (required)>'
	from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/commands.rb:9:in `<top (required)>'
	from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Jackson/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/gems/krausefx-shenzhen-0.14.7/bin/krausefx-ipa:25:in `<top (required)>'
	from /Users/Jackson/.rvm/rubies/ruby-2.2.4/bin/krausefx-ipa:23:in `load'
	from /Users/Jackson/.rvm/rubies/ruby-2.2.4/bin/krausefx-ipa:23:in `<main>'
	from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Jackson/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `<main>'

[00:01:05]: A build error occured. You are using legacy `shenzhen` for building
[00:01:05]: it is recommended to upgrade to `gym`: 
[00:01:05]: https://github.com/fastlane/fastlane/tree/master/gym
[00:01:05]: krausefx-ipa build -c "Release" -s "fastlanedemo" -d "./build" --ipa "fastlanedemo_1.2.2.22_InHouse.ipa" --no-archive --verbose | xcpretty
[00:01:05]: -------------------------------------------------------

fastlane 1.81.0
Do you use bundler to execute fastlane  NO
Do you use a Ruby environment manager rvm

**Comment by TKBurner** [comment]
Hi @goodcyg! Thanks for reaching out. Sorry to hear that you are running into this issue. Can you provide the full set of commands you are running? What are you expecting the -c option to do?

Thanks!

**Comment by goodcyg** [comment]
Hi @TKBurner  thanks
 I use this demo
https://github.com/everettjf/ios_ci_fastlane_demo
Modify the corresponding configuration  build.sh appfile and fastfile
To the project directory， run  sh build.sh 1.2.2 44
Above errors

mac book air OS X EI Captian 10.11.14
xcode 7.2.1
gem 2.5.1
ruby 2.2.4

**Comment by TKBurner** [comment]
Hi @goodcyg Thanks for following up. Is there a reason you aren't using gym to build your app? What happens if you run gym?

Thanks!

**Comment by goodcyg** [comment]
Hi @TKBurner thanks
At the present I will not use GRM。Do not know GRM package syntax

**Comment by goodcyg** [comment]
Hi @TKBurner thanks
At the present I will not use GYM。Do not know GYM package syntax

**Comment by TKBurner** [comment]
Hi @goodcyg,

Can you run:
set -o pipefail && krausefx-ipa build  -s "fastlanedemo" -d "./build" --ipa "fastlanedemo_1.2.2.22_InHouse.ipa" --no-archive --verbose | xcpretty

**Comment by goodcyg** [comment]
after update ruby ,it is work.

**Comment by TKBurner** [comment]
Awesome @goodcyg! Really glad to hear you got up and running. Thanks!
