### ISSUE TITLE
Running `latest_testflight_build_number` fails after team selection

### ISSUE THREAD

**Issue by mfurtak** [fastlane/fastlane#4357]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane beta --verbose
INFO [2016-04-25 16:55:45.55]: -------------------------------------------------
INFO [2016-04-25 16:55:45.55]: --- Step: Verifying required fastlane version ---
INFO [2016-04-25 16:55:45.55]: -------------------------------------------------
INFO [2016-04-25 16:55:45.55]: fastlane version valid
INFO [2016-04-25 16:55:45.55]: ------------------------------
INFO [2016-04-25 16:55:45.55]: --- Step: default_platform ---
INFO [2016-04-25 16:55:45.55]: ------------------------------
INFO [2016-04-25 16:55:45.55]: Driving the lane 'ios beta' 🚀
INFO [2016-04-25 16:55:45.55]: --------------------------------------------
INFO [2016-04-25 16:55:45.55]: --- Step: latest_testflight_build_number ---
INFO [2016-04-25 16:55:45.55]: --------------------------------------------
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
1) "Team A" (########)
2) "Team B" (########)
1
WARN [2016-04-25 16:56:07.60]: Variable Dump:
INFO [2016-04-25 16:56:07.60]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
ERROR [2016-04-25 16:56:07.60]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["operation_failed"]}, "statusCode"=>"ERROR"}
INFO [2016-04-25 16:56:07.60]: Successfully generated documentation to path '/Users/mfurtak/Documents/Code/fastlane/internal-examples/SingleView/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | latest_testflight_build_number      | 22          |
+------+-------------------------------------+-------------+

ERROR [2016-04-25 16:56:07.61]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.26.1/lib/spaceship/client.rb:427:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["operation_failed"]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.26.1/lib/spaceship/tunes/tunes_client.rb:508:in `build_trains'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.26.1/lib/spaceship/tunes/build_train.rb:48:in `all'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.26.1/lib/spaceship/tunes/application.rb:199:in `build_trains'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/actions/latest_testflight_build_number.rb:22:in `run'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:43:in `block (2 levels) in parsing_binding'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.3/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /Users/mfurtak/.rbenv/versions/2.2.3/bin/fastlane:23:in `load'
	from /Users/mfurtak/.rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.66.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  lane :match do
    match(readonly: false)
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    match(type: 'appstore', readonly: false)

    gym # Build your app - more options available
    pilot(skip_submission: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|

  end

  error do |lane, exception|
  end
end
```

### Environment

fastlane version (run `fastlane -v`): **1.81.0**

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **no**

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **rbenv**

**Comment by KrauseFx** [comment]
@sjlu, @pnicholls We noticed you upvoted this issue. Is this still something you experience and needs a fix?

**Comment by pnicholls** [comment]
hey @KrauseFx I did have `FASTLANE_ITC_TEAM_ID` set in my Fastfile but I just removed it and it still all appears to work so yeah I think this has been fixed?

Thanks for all your hard work!

**Comment by TKBurner** [comment]
@pnicholls Awesome! Thanks for following up here. We'll close this out. Hope you have a great day!
