### ISSUE TITLE
"fastlane run ssh" not working properly

### ISSUE THREAD

**Issue by nmayafit** [fastlane/fastlane#4363]
### Issue Description
Trying to run "fastlane run ssh username:"xxx" password:"yyy" host:"zzz" will result with a crash.
Also, when trying the same with "commands" param it will give an error "[!] 'commands' value must be a Array! Found String instead." although I put "commands:["ls"]". Tried all kinds of types with no luck.

##### Complete output when running fastlane, including the stack trace and command used

```
[16:17:45]: -----------------
[16:17:45]: --- Step: ssh ---
[16:17:45]: -----------------
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/ssh.rb:50:in `block in run': [!] undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.2/lib/net/ssh.rb:215:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/ssh.rb:49:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/one_off.rb:31:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:114:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

```

### Environment

fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by TKBurner** [comment]
Hi @nmayafit! Thanks for reaching out. Can you let me know if you are able to run this in a lane? I want to see if it's a command line issue or an issue with the actual params.

Thanks!

**Comment by nmayafit** [comment]
@TKBurner  I opened another bug a min ago regarding ssh as it seems I can't run specific commands in ssh. I'm not sure its related, but if I try to run simple ssh command (like cd or ls) from lane it will work.

**Comment by TKBurner** [comment]
@nmayafit Thanks for following up. I'm going to work with you on that ticket and close this one out. Let me know if you have a separate issue and we can open this one back up 👍
