### ISSUE TITLE
[Core] checking certificates fails because full path is not used

### ISSUE THREAD

**Issue by manuyavuz** [fastlane/fastlane#4387]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
WWDR certificate can't be found because `cert_checker.rb` gives just the file name of the found keychain file. However, `security` command requires the full path.

PS: I've submitted a simple PR (#4386)  which solves the issue.

##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2016-04-27 19:05:33.83]: Cruising back to lane 'ios betaCI' 🚘
INFO [2016-04-27 19:05:33.83]: ------------------
INFO [2016-04-27 19:05:33.83]: --- Step: cert ---
INFO [2016-04-27 19:05:33.83]: ------------------

+---------------+--------------------------------------------------+
|                      Summary for cert 1.4.0                      |
+---------------+--------------------------------------------------+
| development   | false                                            |
| force         | false                                            |
| username      | USER_NAME                          |
| keychain_path | /var/_xcsbuildd/Library/Keychains/login.keychain |
+---------------+--------------------------------------------------+

INFO [2016-04-27 19:05:34.09]: Starting login with user 'USER_NAME'
INFO [2016-04-27 19:05:37.82]: Successfully logged in
INFO [2016-04-27 19:05:41.02]: $ security list-keychains -d user
INFO [2016-04-27 19:05:41.03]: ▸     "/Library/Developer/XcodeServer/Keychains/Portal.keychain"
INFO [2016-04-27 19:05:41.03]: ▸     "/private/var/_xcsbuildd/Library/Keychains/login.keychain"
INFO [2016-04-27 19:05:41.03]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' Portal.keychain
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
INFO [2016-04-27 19:05:41.05]: $ security list-keychains -d user
INFO [2016-04-27 19:05:41.06]: ▸     "/Library/Developer/XcodeServer/Keychains/Portal.keychain"
INFO [2016-04-27 19:05:41.06]: ▸     "/private/var/_xcsbuildd/Library/Keychains/login.keychain"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1062  100  1062    0     0    832      0  0:00:01  0:00:01 --:--:--   832
security: SecKeychainItemImport: The specified keychain could not be found.
WARN [2016-04-27 19:05:42.38]: Variable Dump:
INFO [2016-04-27 19:05:42.38]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios betaCI"}
ERROR [2016-04-27 19:05:42.38]: Could not install WWDR certificate
INFO [2016-04-27 19:05:42.38]: Successfully generated documentation to path '/Library/Developer/XcodeServer/Integrations/Caches/918efdf2376e7e61b6efb43050018004/Source/Netmera/Example/fastlane/README.md'

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | default_platform      | 0           |
| 2    | Switch to ios cp lane | 0           |
| 3    | verify_pod_keys       | 4           |
| 4    | cocoapods             | 6           |
| 5    | cert                  | 8           |
+------+-----------------------+-------------+

ERROR [2016-04-27 19:05:42.39]: fastlane finished with errors
/var/_xcsbuildd/.gem/gems/fastlane_core-0.42.0/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Could not install WWDR certificate (FastlaneCore::Interface::FastlaneError)
	from /var/_xcsbuildd/.gem/gems/fastlane_core-0.42.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /var/_xcsbuildd/.gem/gems/fastlane_core-0.42.0/lib/fastlane_core/cert_checker.rb:63:in `block in install_wwdr_certificate'
	from /var/_xcsbuildd/.gem/gems/fastlane_core-0.42.0/lib/fastlane_core/cert_checker.rb:57:in `chdir'
	from /var/_xcsbuildd/.gem/gems/fastlane_core-0.42.0/lib/fastlane_core/cert_checker.rb:57:in `install_wwdr_certificate'
	from /var/_xcsbuildd/.gem/gems/fastlane_core-0.42.0/lib/fastlane_core/cert_checker.rb:19:in `installed_identies'
	from /var/_xcsbuildd/.gem/gems/fastlane_core-0.42.0/lib/fastlane_core/cert_checker.rb:7:in `installed?'
	from /var/_xcsbuildd/.gem/gems/cert-1.4.0/lib/cert/runner.rb:88:in `block in find_existing_cert'
	from /var/_xcsbuildd/.gem/gems/cert-1.4.0/lib/cert/runner.rb:80:in `each'
	from /var/_xcsbuildd/.gem/gems/cert-1.4.0/lib/cert/runner.rb:80:in `find_existing_cert'
	from /var/_xcsbuildd/.gem/gems/cert-1.4.0/lib/cert/runner.rb:31:in `run'
	from /var/_xcsbuildd/.gem/gems/cert-1.4.0/lib/cert/runner.rb:6:in `launch'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/actions/cert.rb:19:in `run'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/runner.rb:128:in `chdir'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:33:in `block (2 levels) in parsing_binding'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/lane.rb:36:in `call'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/lane.rb:36:in `call'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/runner.rb:46:in `chdir'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/runner.rb:46:in `execute'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/bin/fastlane:38:in `block (2 levels) in run'
	from /var/_xcsbuildd/.gem/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /var/_xcsbuildd/.gem/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /var/_xcsbuildd/.gem/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /var/_xcsbuildd/.gem/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /var/_xcsbuildd/.gem/gems/fastlane_core-0.42.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /var/_xcsbuildd/.gem/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/bin/fastlane:168:in `run'
	from /var/_xcsbuildd/.gem/gems/fastlane-1.82.0/bin/fastlane:174:in `<top (required)>'
	from /var/_xcsbuildd/.gem/bin/fastlane:23:in `load'
	from /var/_xcsbuildd/.gem/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  lane :betaCI do
    beta_dir = artifacts_dir + "beta/"
    .
    .
    cert(output_path: beta_dir)
    .
    .
  end
```

### Environment

fastlane version (run `fastlane -v`): 1.82.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by julianhirt** [comment]
Exactly same issue here.

**Comment by julianhirt** [comment]
I just have had the same issue here but I could resolve it locally. 
As you I have had multiple keychains. Within your logs you can see it receives to different keychains:

```
INFO [2016-04-27 19:05:41.02]: $ security list-keychains -d user
INFO [2016-04-27 19:05:41.03]: ▸     "/Library/Developer/XcodeServer/Keychains/Portal.keychain"
INFO [2016-04-27 19:05:41.03]: ▸     "/private/var/_xcsbuildd/Library/Keychains/login.keychain"
```

Can you check if these keychains both exist? For me there was only a weird reference within the 'keychain access'. I removed the reference and it worked fine.

**Comment by TKBurner** [comment]
Thanks for stepping in @juliangrosshauser! @manuyavuz Let me know if this keychain advice helped out 👍

**Comment by manuyavuz** [comment]
Hi,

As @lkraider pointed [here](https://github.com/fastlane/fastlane/pull/4386#issuecomment-215524061), Xcode Server looks has a different path for keychains, and `security` command seems to look for ~/Library/Keychains by default. Using the full path indeed works. 

Therefore, I think with the merged PR, the issue has been solved.

Thanks for quick feedbacks!

**Comment by TKBurner** [comment]
@manuyavuz Awesome! Thanks for following up 👍

**Comment by sergii-frost** [comment]
Hi, I am facing an issue in case if full path contains spaces. 
e.g. 

```
$ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/jenkins/.jenkins/workspace/My Project Jenkins Job/login.keychain
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
```

I fixed that by replacing spaces with "_" for my Jenkins job, but it is still quite common to have spaces there. FYI I am using [Jenkins Keychains and Provisioning Profiles plugin](https://wiki.jenkins-ci.org/display/JENKINS/Keychains+and+Provisioning+Profiles+Plugin) to manage keychains usage on Jenkins.

**Comment by lkraider** [comment]
Indeed, `#{keychain}` are not escaped, they should now be `'#{keychain}'`.

**Comment by TKBurner** [comment]
@sergii-frost Thanks for sharing this. Can you open a new issue so we can properly track this? Thanks! 👍

**Comment by sergii-frost** [comment]
@TKBurner sure, here you go https://github.com/fastlane/fastlane/issues/4734
