### ISSUE TITLE
Supply throws titleAlreadyUsed exception when trying to update an existing App

### ISSUE THREAD

**Issue by satbirjhuti** [fastlane/fastlane#4422]
### Issue Description
I was trying to update an existing App on the Play Store using Supple. It errored out with  `titleAlreadyUsed: You need to choose a different title for your app. This one is already used by another app. (Google::Apis::ClientError)`.

Crash report Number: c29b05f26e1952b9616d501f4638c0b7

##### Complete output when running fastlane, including the stack trace and command used

```
[15:08:36]: Updating track 'alpha'...
[15:08:37]: Uploading all changes to Google Play...
[15:08:39]: Variable Dump:
[15:08:39]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:android, :LANE_NAME=>"android googleplay", :GRADLE_ALL_APK_OUTPUT_PATHS=>[]}
[15:08:39]: titleAlreadyUsed: You need to choose a different title for your app. This one is already used by another app.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gradle                              | 16          |
| 4    | supply                              | 19          |
+------+-------------------------------------+-------------+

[15:08:39]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'c29b05f26e1952b9616d501f4638c0b7'
The crash report has been stored locally '/tmp/sentry_c29b05f26e1952b9616d501f4638c0b7.json'
/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:211:in `check_status': [!] titleAlreadyUsed: You need to choose a different title for your app. This one is already used by another app. (Google::Apis::ClientError)
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/api_command.rb:102:in `check_status'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:179:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:286:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/base_service.rb:267:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/generated/google/apis/androidpublisher_v2/service.rb:91:in `commit_edit'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/client.rb:100:in `commit_current_edit!'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/uploader.rb:29:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/actions/supply.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:81:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.42.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
[15:08:41] 'upload-apk-alpha' errored after 40 s
[15:08:41] Error in plugin 'gulp-shell'
Message:
    Command `fastlane android googleplay track:alpha json_key:/Users/satbirjhuti/src/mobile-frontend/clients/unata/android/deploy_keys.json package_name:com.unata.testapp metadata_path:/Users/satbirjhuti/src/mobile-frontend/clients/unata/android/metadata;` failed with exit code 1
[15:08:41] 'alpha-to-googleplay' errored after 40 s
[15:08:41] Error in plugin 'run-sequence'
Message:
    An error occured in task 'upload-apk-alpha'.

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.64.0"

default_platform :ios

platform :android do

  desc "Deploy a new alpha version to Google Play"
  lane :googleplay do |options|
    gradle(
      task: "assembleRelease",
      project_dir: "build/platforms/android"
      )
    supply(
      apk: "build/platforms/android/build/outputs/apk/android-x86-release.apk",
      track: options[:track],
      json_key: options[:json_key],
      package_name: options[:package_name],
      metadata_path: options[:metadata_path]
    )
  end

  desc "Deploy a new beta version to Google Play"
  lane :beta do |options|
    gradle(
      task: "assembleRelease",
      project_dir: "build/platforms/android"
      )
    supply(
      apk: "build/platforms/android/build/outputs/apk/android-x86-release.apk",
      track: "beta",
      json_key: options[:json_key],
      package_name: options[:package_name],
      metadata_path: options[:metadata_path]
    )
  end

  desc "Deploy a new Production version to Google Play"
  lane :prod do |options|
    gradle(
      task: "assembleRelease",
      project_dir: "build/platforms/android"
      )
    supply(
      apk: "build/platforms/android/build/outputs/apk/android-x86-release.apk",
      track: "production",
      json_key: options[:json_key],
      package_name: options[:package_name],
      metadata_path: options[:metadata_path]
    )
  end
end

```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.83.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by TKBurner** [comment]
Hi @satbirjhuti! Thanks for reaching out. Can you let me know what happens if you set package name directly rather than using an environmental variable? Thanks!

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.

**Comment by AndreyNikiforov** [comment]
faced with the same issue today when uploading first apk to production track using supply. Other tracks worked fine (I am using different package names for alpha-beta-prod versions of the app and so each of them use only one track in Google Play).

note: to start using supply in CI, I have to upload first build manually (otherwise supply fails with `applicationNotFound: No application was found for the given package name. (Google::Apis::ClientError)`)

I started suspecting if different Google Play tracks have different requirements.

**Comment by AndreyNikiforov** [comment]
figured out -- I was submitting under the same name (though with different package name).

**Comment by TKBurner** [comment]
@AndreyNikiforov Awesome!

**Comment by kevinthecity** [comment]
I also ran into this problem - although it was a user error. I had 2 lanes with 2 different `metadata` folders, however I accidentally had both lanes pointing to the same `metadata` folder. Updating to use their respective `metadata` folders fixed the issue.
