### ISSUE TITLE
Issue # f969b436554c93438db4a4967a981a6c: Error using frameit

### ISSUE THREAD

**Issue by asetiyadi** [fastlane/fastlane#4466]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I install the latest ImageMagick and frameit, but it throws an error

##### Complete output when running fastlane, including the stack trace and command used

```
Andis-MacBook-Pro:Home Report Final setiyadi$ frameit
[19:36:59]: ----------------------------------------------------
[19:36:59]: Looks like you'd like to install new device templates
[19:36:59]: The images can not be pre-installed due to licensing
[19:36:59]: Press Enter to get started
[19:36:59]: ----------------------------------------------------

[19:37:04]: ----------------------------------------------------
[19:37:04]: Download the zip files for the following devices
[19:37:04]: iPhone 6s, iPhone 6s Plus, iPhone SE, iPad mini 4 and iPad Pro
[19:37:04]: You only need to download the devices you want to use
[19:37:04]: Press Enter when you downloaded the zip files
[19:37:04]: ----------------------------------------------------

[19:37:51]: ----------------------------------------------------
[19:37:51]: Extract the downloaded files into the folder
[19:37:51]: '/Users/setiyadi/.frameit/devices_frames', which should be open in your Finder
[19:37:51]: You can just copy the whole content into it.
[19:37:51]: Press Enter when you extracted the files into the given folder
[19:37:51]: ----------------------------------------------------

[19:38:07]: Converting PSD file '/Users/setiyadi/.frameit/devices_frames/iPhone-SE-Silver.psd'
[19:38:07]: Removing white background 🚫 ⬜️
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'f969b436554c93438db4a4967a981a6c'
The crash report has been stored locally '/tmp/sentry_f969b436554c93438db4a4967a981a6c.json'
/Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:382:in `block in method_missing': [!] undefined method `details' for #<MiniMagick::Image:0x007f879b9bc3a8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:499:in `block in mogrify'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/tool.rb:52:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:492:in `mogrify'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:378:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:76:in `block (2 levels) in convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:75:in `reject'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:75:in `block in convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:61:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:61:in `convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:44:in `setup_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:7:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/runner.rb:13:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/bin/frameit:32:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/bin/frameit:32:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.42.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/bin/frameit:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/bin/frameit:72:in `<top (required)>'
	from /usr/local/bin/frameit:23:in `load'
	from /usr/local/bin/frameit:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.83.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    cert
    sigh
    gym(scheme: "Home Report") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Home Report") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.83.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by i2amsam** [comment]
Thanks for the report @asetiyadi 👍 , I just pushed a fix for this in `frameit` 2.6.1, could you give it a try and let me know if it fixes the problem?

**Comment by asetiyadi** [comment]
Hi Sam,

I uninstall frameit then reinstall following the steps from Github



When I ran frameit after the install was complete, now it does not show the Apple page to download the images.  Instead it shows log output as shown below.




Appreciate any advice on how to proceed.

Regards,
Andi

**Comment by i2amsam** [comment]
@asetiyadi I think you forgot to attach the output.  Could you check the version of frameit you're running with `frameit -v` and post that? 

Also, you'll need to run `frameit setup` again to convert the PSDs, but you can skip the first two steps if you already downloaded the frames from Apple.

**Comment by asetiyadi** [comment]
Hi Sam,

Thank you for the direction, the version that I have now is 2.6.1.  I ran “frameit setup” and got directed to download the psd files.  The “frameit” command now producing the screenshots with iPhone frame on it.  My follow up question, how do I pick whether I want to use the the black or white/silver iPhone for the frame?

Regards,
Andi

**Comment by asetiyadi** [comment]
Also .. I just ran “deliver”, iTunesConnect rejected the screenshot stating incorrect size.  Did I miss anything?




This is the screenshot it tries to push to iTunesConnect.



Regards,
Andi

**Comment by i2amsam** [comment]
Andi, you can run `frameit silver`, see the [readme](https://github.com/fastlane/fastlane/tree/master/frameit).

For the problem with `deliver` I'm not sure, your attachment doesn't seem to have been attached.  Could you open a new issue with that, the screenshot that was rejected and the output from the run?

**Comment by asetiyadi** [comment]
Hi Sam,

For the incorrect image size issue, I think this is the issue with “frameit”.  The size of the screenshots produced by “frameit” are rejected by iTunesConnect.  For example the image file for iPhone 6 with frame, is 613 x 1255.  It should be 750 x 1334.

Regards,
Andi

**Comment by TKBurner** [comment]
Hi @asetiyadi! Thanks for following up. Are you using titles on these frames? The output will only be the correct dimensions if you include a title. Thanks!
