### ISSUE TITLE
Issue 9d4acb17ddb18dba04990af308e0ba0e - Error with Slack messaging and Unusual Character?

### ISSUE THREAD

**Issue by timcamber** [fastlane/fastlane#4468]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Had an error when sending Slack message (I think?). All steps completed successfully and then I had an error / crash when sending the Slack command.

I see ":beta:Symbol" mentioned in the crash reporter. This app's bundle display name includes the β symbol in it; I wonder if this is related? Not sure if this is a problem in Fastlane's tools or Swift's messaging API?

##### Complete output when running fastlane, including the stack trace and command used

```
[14:27:08]: -------------------
[14:27:08]: --- Step: slack ---
[14:27:08]: -------------------
[14:27:08]: Successfully sent Slack notification
[14:27:08]: Variable Dump:
[14:27:08]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :GIT_REPO_WAS_CLEAN_ON_START=>true, :BUILD_NUMBER=>"148", :VERSION_NUMBER=>"1.5.0", :IPA_OUTPUT_PATH=>"[MY_PATH]", :DSYM_OUTPUT_PATH=>"[MY_PATH]", :XCODEBUILD_ARCHIVE=>"[MY_PATH]"}
[14:27:08]: undefined method `+' for :beta:Symbol

+------+-------------------------+-------------+
|               fastlane summary               |
+------+-------------------------+-------------+
| Step | Action                  | Time (in s) |
+------+-------------------------+-------------+
| 1    | default_platform        | 0           |
| 2    | cocoapods               | 21          |
| 3    | ensure_git_status_clean | 0           |
| 4    | increment_build_number  | 1           |
| 5    | get_version_number      | 0           |
| 6    | get_build_number        | 0           |
| 7    | gym                     | 364         |
| 8    | pilot                   | 1790        |
| 9    | clean_build_artifacts   | 0           |
| 10   | commit_version_bump     | 0           |
| 11   | slack                   | 0           |
+------+-------------------------+-------------+

[14:27:08]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '9d4acb17ddb18dba04990af308e0ba0e'
The crash report has been stored locally '/tmp/sentry_9d4acb17ddb18dba04990af308e0ba0e.json'
Fastfile:42:in `block (2 levels) in parsing_binding': [!] undefined method `+' for :beta:Symbol (NoMethodError)
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:56:in `call'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:56:in `block in execute'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.83.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane_core-0.43.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.83.0/bin/fastlane:168:in `run'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-1.83.0/bin/fastlane:174:in `<top (required)>'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/bin/fastlane:23:in `load'
	from /Users/timcamber/.rbenv/versions/2.0.0-p247/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
default_platform :ios

platform :ios do
  version = nil
  build_number = nil
  tag_string = nil

  before_all do
    ENV["SLACK_URL"] = SLACK_URL

    cocoapods
    
    ensure_git_status_clean # Make sure Git working directory is clean
    increment_build_number  # Increment Build Number

    version = get_version_number(xcodeproj: MY_PROJECT_FILE)
    build_number = get_build_number(xcodeproj: MY_PROJECT_FILE)

  end

  desc "Submit a new Alpha Build to Apple TestFlight"
  lane :alpha do
    gym(scheme: "[MY APP NAME] α")
    pilot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(scheme: "[MY APP NAME] β")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    gym(scheme: "[MY APP NAME] App Store") # Build your app - more options available
    deliver(force: true)
  end

  after_all do |lane|
    clean_build_artifacts
    commit_version_bump
    tag_string = lane + "/" + version + "(" + build_number + ")"
    add_git_tag(tag: tag_string)

    push_to_git_remote
    clean_build_artifacts
    reset_git_repo

    slack(
      message: "Successfully deployed update to [MY APP NAME]"
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
```

### Environment

fastlane version (run `fastlane -v`):
`fastlane 1.83.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
`rbenv`

**Comment by TKBurner** [comment]
Hi @timcamber! Hope you are doing well. I wanted to know if you've tested without this symbol? That'll help us track down the cause of this. Thanks!
