### ISSUE TITLE
Gym or deliver fails - because of a danish symbol in the ipa filename

### ISSUE THREAD

**Issue by mortenholmgaard** [fastlane/fastlane#4469]
### Issue Description
Gym or deliver fails - It  is because of a danish symbol in the ipa filename, because after the error I added the following argument to the gym command and then it works:
`output_name: "#{configuration}"`

##### Complete output when running fastlane, including the stack trace and command used
Crashreport: 49b20c8e96ee45921654799f735cbc73

```
[20:32:36]: ▸ Generating 'Å-festival.app.dSYM'
[20:32:38]: ▸ Running script 'Run Script'
[20:32:39]: ▸ Running script 'Embed Pods Frameworks'
[20:32:42]: ▸ Running script 'Copy Pods Resources'
[20:32:42]: ▸ Touching Å-festival.app
[20:32:53]: ▸ Signing /Users/mortenholmgaard/Library/Developer/Xcode/DerivedData/MyEvent-efvydhfgswgaqmgrhjjenvilnlvu/Build/Intermediates/ArchiveIntermediates/AaFestival/InstallationBuildProductsLocation/Applications/Å-festival.app
[20:32:55]: ▸ Touching Å-festival.app.dSYM
[20:32:58]: ▸ Archive Succeeded
[20:32:59]: Successfully stored the archive. You can find it in the Xcode Organizer.

[20:33:25]: Successfully exported and compressed dSYM file
[20:33:25]: Successfully exported and signed the ipa file:
[20:33:25]: /Users/mortenholmgaard/Code/MyEvent/fastlane/.AaFestival/Å-festival.ipa
[20:33:25]: ---------------------
[20:33:25]: --- Step: deliver ---
[20:33:25]: ---------------------
[20:33:26]: -----------------
[20:33:26]: --- Step: say ---
[20:33:26]: -----------------
[20:33:26]: $ say 'Socket is not connected'
[20:33:28]: Variable Dump:
[20:33:28]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"deploy_store", :CERT_FILE_PATH=>"/Users/mortenholmgaard/Code/MyEvent/.AaFestival/QX7G95VNY8.cer", :CERT_CERTIFICATE_ID=>"QX7G95VNY8", :PRODUCE_APPLE_ID=>"995025264", :SIGH_PROFILE_PATH=>"/Users/mortenholmgaard/Code/MyEvent/fastlane/.AaFestival/AppStore_dk.imu.aafestival.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/mortenholmgaard/Code/MyEvent/fastlane/.AaFestival/AppStore_dk.imu.aafestival.mobileprovision"], :SIGH_UDID=>"3ef496a8-2ec1-4d57-b2ed-e05aafe2ae98", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/mortenholmgaard/Code/MyEvent/fastlane/.AaFestival/Å-festival.ipa", :DSYM_OUTPUT_PATH=>"/Users/mortenholmgaard/Code/MyEvent/fastlane/.AaFestival/Å-festival.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/mortenholmgaard/Library/Developer/Xcode/Archives/2016-05-02/Å-festival 2016-05-02 20.31.01.xcarchive"}
[20:33:28]: Socket is not connected

+------+---------+-------------+
|       fastlane summary       |
+------+---------+-------------+
| Step | Action  | Time (in s) |
+------+---------+-------------+
| 1    | team_id | 0           |
| 2    | cert    | 10          |
| 3    | produce | 37          |
| 4    | sigh    | 9           |
| 5    | pem     | 4           |
| 6    | gym     | 153         |
| 7    | deliver | 0           |
| 8    | say     | 2           |
+------+---------+-------------+

[20:33:28]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '49b20c8e96ee45921654799f735cbc73'
The crash report has been stored locally '/tmp/sentry_49b20c8e96ee45921654799f735cbc73.json'
/Users/mortenholmgaard/.gems/gems/fastlane_core-0.42.1/lib/fastlane_core/configuration/configuration_file.rb:24:in `eval': [!] Socket is not connected (Errno::ENOTCONN)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:211:in `write0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:185:in `block in write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:202:in `writing'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:184:in `write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:325:in `write_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:136:in `exec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1410:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:319:in `block in open_http'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
	from (eval):20:in `block in initialize'
	from (eval):19:in `open'
	from (eval):19:in `initialize'
	from /Users/mortenholmgaard/.gems/gems/fastlane_core-0.42.1/lib/fastlane_core/configuration/configuration_file.rb:24:in `eval'
	from /Users/mortenholmgaard/.gems/gems/fastlane_core-0.42.1/lib/fastlane_core/configuration/configuration_file.rb:24:in `initialize'
	from /Users/mortenholmgaard/.gems/gems/fastlane_core-0.42.1/lib/fastlane_core/configuration/configuration.rb:153:in `new'
	from /Users/mortenholmgaard/.gems/gems/fastlane_core-0.42.1/lib/fastlane_core/configuration/configuration.rb:153:in `load_configuration_file'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/actions/deliver.rb:13:in `run'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:118:in `block in parsing_binding'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/mortenholmgaard/.gems/gems/fastlane_core-0.42.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/bin/fastlane:168:in `run'
	from /Users/mortenholmgaard/.gems/gems/fastlane-1.83.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
desc "Deploy a new version to the App Store"
lane :deploy_store do #Works!
  target = ENV["TARGET"]

  cert(output_path: "./.#{target}/")
  produce_app(true)
  sigh(output_path: "./fastlane/.#{target}/")
  push_certificates(false)

   gym(
   scheme: target,
   configuration: configuration,
   silent: true,
   clean: true,
   output_directory: "./fastlane/.#{target}/")
  
  deliver(submit_for_review: true)

  currentVersionNumber = get_version_number()
  currentBuildNumber = get_build_number()
  sh "git add -A"
  sh "git commit -m \"#{taget} version: #{currentVersionNumber}_#{currentBuildNumber}\""
  add_git_tag(tag: "#{taget}_#{currentVersionNumber}")
  push_to_git_remote
end
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.83.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No - install ruby with home-brew

**Comment by TKBurner** [comment]
Hi @mortenholmgaard Thanks for pointing this out. I'll let the team know about it, but it seems like you've found a viable solution. We'll continue to improve language support on an ongoing basis. Thanks!
