### ISSUE TITLE
frameit depends on newer version of Mini Magick

### ISSUE THREAD

**Issue by rodbegbie** [fastlane/fastlane#4472]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Frameit is crashing for me with the new iPhone SE images.  Seems like it's depending on a Mini Magick call that was added in [v4.2.0](https://github.com/minimagick/minimagick/releases/tag/v4.2.0).  The gemspec only requires 4.0.2

##### Complete output when running fastlane, including the stack trace and command used

```
12:46 $ frameit silver
[12:49:55]: Converting PSD file '/Users/rod/.frameit/devices_frames/iPhone SE/iPhone-SE-Silver-horizontal.psd'
[12:49:55]: Removing white background 🚫 ⬜️
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '64181bced9e89310f98e73caa0b71b92'
The crash report has been stored locally '/tmp/sentry_64181bced9e89310f98e73caa0b71b92.json'
/Users/rod/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:382:in `block in method_missing': [!] undefined method `details' for #<MiniMagick::Image:0x007fd323d76df8> (NoMethodError)
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:499:in `block in mogrify'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.0.4/lib/mini_magick/tool.rb:52:in `new'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:492:in `mogrify'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:378:in `method_missing'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:76:in `block (2 levels) in convert_frames'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:75:in `reject'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:75:in `block in convert_frames'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:61:in `each'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:61:in `convert_frames'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/lib/frameit/runner.rb:10:in `initialize'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/bin/frameit:42:in `new'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/bin/frameit:42:in `block (2 levels) in run'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.43.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/bin/frameit:57:in `run'
	from /Users/rod/.rvm/gems/ruby-2.2.4/gems/frameit-2.6.0/bin/frameit:72:in `<top (required)>'
	from /Users/rod/.rvm/gems/ruby-2.2.4/bin/frameit:23:in `load'
	from /Users/rod/.rvm/gems/ruby-2.2.4/bin/frameit:23:in `<main>'
	from /Users/rod/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rod/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm

**Comment by i2amsam** [comment]
Thanks for the report! This will be fixed in the next release with https://github.com/fastlane/fastlane/pull/4483

**Comment by i2amsam** [comment]
@rodbegbie this just went out with `frameit` 2.6.1, could you give it a try and let me know if it fixed it for you? Thanks!

**Comment by rodbegbie** [comment]
Thanks!  Sadly, bundler is unhappy because it clashes with the mini_magick version requested by `badge`  Guess I'll have to file a bug on their repo.

```
Bundler could not find compatible versions for gem "mini_magick":
  In Gemfile:
    badge was resolved to 0.0.1, which depends on
      mini_magick (~> 4.0.2)

    frameit (~> 2.6.1) was resolved to 2.6.1, which depends on
      mini_magick (~> 4.5.1)
```

**Comment by TKBurner** [comment]
Hi @rodbegbie! Thanks for following up. Badge pushed a change this morning, can you check against that? Thanks!

**Comment by rodbegbie** [comment]
Everything looks great now  Thanks for the help!

**Comment by TKBurner** [comment]
@rodbegbie Awesome! So glad to hear you are back up and running 👍
