### ISSUE TITLE
uninitialized constant InhouseAction

### ISSUE THREAD

**Issue by MickeyHub** [fastlane/fastlane#4498]
```
/Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/fast_file.rb:137:in `const_get': [31m[!] uninitialized constant InhouseAction[0m (NameError)
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/fast_file.rb:137:in `method_missing'
        from Fastfile:46:in `block (2 levels) in parsing_binding'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/lane.rb:36:in `call'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/lane.rb:36:in `call'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/runner.rb:52:in `block in execute'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/runner.rb:46:in `chdir'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/runner.rb:46:in `execute'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/commands_generator.rb:41:in `block (2 levels) in run'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/commands_generator.rb:171:in `run'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/commands_generator.rb:12:in `start'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/bin/fastlane:6:in `<top (required)>'
        from /Users/ngsserver/.rbenv/versions/2.2.3/bin/fastlane:23:in `load'
        from /Users/ngsserver/.rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'
```

**Comment by TKBurner** [comment]
@MickeyHub Thanks for reaching out! Can you format your issue according to our new issue template? https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md Thanks 👍

**Comment by MickeyHub** [comment]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

##### Complete output when running fastlane, including the stack trace and command used

```
/Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/fast_file.rb:137:in `const_get': �[31m[!] uninitialized constant InhouseAction�[0m (NameError)
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/fast_file.rb:137:in `method_missing'
        from Fastfile:46:in `block (2 levels) in parsing_binding'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/lane.rb:36:in `call'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/lane.rb:36:in `call'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/runner.rb:52:in `block in execute'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/runner.rb:46:in `chdir'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/runner.rb:46:in `execute'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/commands_generator.rb:41:in `block (2 levels) in run'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/commands_generator.rb:171:in `run'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/lib/fastlane/commands_generator.rb:12:in `start'
        from /Users/ngsserver/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.84.0/bin/fastlane:6:in `<top (required)>'
        from /Users/ngsserver/.rbenv/versions/2.2.3/bin/fastlane:23:in `load'
        from /Users/ngsserver/.rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'
```

### Configuration Files

Fastfile:
```ruby
opt_out_usage
update_fastlane
fastlane_version "1.41.0"

default_platform :ios

platform :ios do
  before_all do
    clear_derived_data
    ensure_git_status_clean
  end
  
  private_lane :ensure_branch_develop do
    ensure_git_branch(
      branch: 'develop'
    )
  end
  
  private_lane :clean_up_repo do
    reset_git_repo(
      disregard_gitignore: false
    )
  end
  
  private_lane :update_build_number do
    build_number = number_of_commits
    increment_build_number(build_number: build_number)
  end
  
  lane :fire do
    # ensure_branch_develop
    cocoapods
    update_build_number
    inhouse
  end
  
  lane :inhouse do
    home_dir = ENV['HOME']
    output_path = home_dir + "/.Cert/"
    # ensure cert dir exist
    ensure_cmd = "mkdir -pv " + output_path
    sh ensure_cmd
    # get latest cert and profile
    cert(output_path: output_path)
    sigh(
      adhoc: true,
      force: true,
      app_identifier: "com.specific_this.issue",
      output_path: output_path
    )
    # set Apollon main project provisioning profile
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
    gym
  end

  after_all do |lane|
    clean_up_repo
  end

  error do |lane, exception|
    clean_up_repo
    say "Shit"
  end
end

```

### Environment

fastlane version (run `fastlane -v`): 1.84.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by MickeyHub** [comment]
is anybody here?

**Comment by TKBurner** [comment]
Hi @MickeyHub! Thanks for working with us. Can you send the full output prior to the stack trace? I want to see which lane you are running and where the error happens. Thanks and have an awesome day!

**Comment by MickeyHub** [comment]
[KRA-FIRE-JOB1-446.txt](https://github.com/fastlane/fastlane/files/256224/KRA-FIRE-JOB1-446.txt)

**Comment by TKBurner** [comment]
Hi @MickeyHub! Thanks for following up. I noticed the error:

here does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings

Can you check this in your build settings? Thanks! 👍

**Comment by puttin** [comment]
We just update our `Fastfile` to avoid the `CURRENT_PROJECT_VERSION` problem in error section `Variable Dump`.

We have used Fastlane for some months, the `uninitialized constant InhouseAction` problem happens just these days.

It only happens when `cert` or `sigh` action is running.

**Comment by MickeyHub** [comment]
obviously, `CURRENT_PROJECT_VERSION` is not the reason.

**Comment by TKBurner** [comment]
Hi @MickeyHub 

Thanks for following up. What happens if you change out the line 'inhouse' in the fire lane to

  sh "fastlane inhouse"

Thanks!

**Comment by MickeyHub** [comment]
I use `sh "fastlane inhouse"` instead `inhouse`, the result is same before. 
```ruby
lane :fire do
    cocoapods
    update_build_number
    ENV["GYM_XCCONFIG"] = "./Configuration/AdHoc.xcconfig"
    sh "fastlane inhouse"
    upload_to_fir_im
 end
```
[KRA-FIRE-JOB1-460.txt](https://github.com/fastlane/fastlane/files/261549/KRA-FIRE-JOB1-460.txt)

**Comment by MickeyHub** [comment]
sorry for long time no reply, it's not work, and we may find the reason, when we use cert or sigh directly with command line, both failed with login into developer member or iTunes Connect, so maybe these failures can be attributed to spaceship, it provide both developer member and iTunes Connect API, we also find lots of issues related to spaceship opened recently.
It still failed although @KrauseFx release 0.27.0.
the log of cert is below: 
```
sqrt3-server:~ shayanbo$ cert

+---------------+--------------------------------------------------+
|                      Summary for cert 1.4.1                      |
+---------------+--------------------------------------------------+
| development   | false                                            |
| force         | false                                            |
| keychain_path | /Users/shayanbo/Library/Keychains/login.keychain |
+---------------+--------------------------------------------------+

[15:06:27]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: 791331313@qq.com
[15:06:32]: Starting login with user '791331313@qq.com'
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '6ad85c8ca3f27eead98fe6bd65e9a5ef'
The crash report has been stored locally '/tmp/sentry_6ad85c8ca3f27eead98fe6bd65e9a5ef.json'
/Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:363:in `finish': [!] buffer error (Zlib::BufError)
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:363:in `finish'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:265:in `ensure in inflater'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:264:in `inflater'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:280:in `read_body_0'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1134:in `block in get'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1421:in `block (2 levels) in transport_request'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:162:in `reading_body'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1420:in `block in transport_request'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/shayanbo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:407:in `block in send_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:325:in `with_retry'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:406:in `send_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:382:in `request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:316:in `itc_service_key'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:274:in `block in send_shared_login_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:407:in `block in send_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:325:in `with_retry'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:406:in `send_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:382:in `request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:273:in `send_shared_login_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/portal/portal_client.rb:35:in `send_login_request'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:349:in `do_login'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:225:in `login'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/client.rb:88:in `login'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/spaceship-0.26.3/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/cert-1.4.1/lib/cert/runner.rb:17:in `login'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/cert-1.4.1/lib/cert/runner.rb:27:in `run'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/cert-1.4.1/bin/cert:33:in `block (2 levels) in run'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.43.4/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/cert-1.4.1/bin/cert:49:in `run'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3@global/gems/cert-1.4.1/bin/cert:55:in `<top (required)>'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/bin/cert:23:in `load'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/bin/cert:23:in `<main>'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/shayanbo/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by MickeyHub** [comment]
I update spaceship to latest `0.27.1`, and `cert` and `sigh` both login successfully, I'll close it while CI is OK tonight.

**Comment by TKBurner** [comment]
@MickeyHub Awesome! Let me know how it goes! 👍

**Comment by puttin** [comment]
The result is good.

**Comment by MickeyHub** [comment]
thanks @TKBurner , everything is OK, maybe spaceship 0.27.1 works, I'll close this issues, thank you very much.
