### ISSUE TITLE
fastlane 1.85.0 crashing on Travis due to Ruby update

### ISSUE THREAD

**Issue by brockboland** [fastlane/fastlane#4524]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Yesterday morning, fastlane worked fine on Travis. Today, it's segfaulting, without any changes to fastlane config or `.travis.yml`. It's because Travis [updated their xcode7.3 image](https://blog.travis-ci.com/2016-05-05-xcode-731-is-here) to use ruby-2.0.0-p648 by default. I haven't tested this locally, but switching Travis back to use 2.0.0-p643 (the build it was using yesterday) fixed the problem.

Unfortunately, I don't have more time to dig into this right but I do have a workaround: add this to `.travis.yml`:

```yml
rvm:
  - 2.0.0-p643
```

##### Complete output when running fastlane, including the stack trace and command used

```
[0Ktravis_time:start:0487f038
[0K$ fastlane test

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/ext/parser.bundle: [BUG] Segmentation fault

ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin15.0.0]



-- Crash Report log information --------------------------------------------

   See Crash Report log file under the one of following:

     * ~/Library/Logs/CrashReporter

     * /Library/Logs/CrashReporter

     * ~/Library/Logs/DiagnosticReports

     * /Library/Logs/DiagnosticReports

   the more detail of.



-- Control frame information -----------------------------------------------

c:0019 p:-17525265735480 s:0057 e:000056 TOP    [FINISH]

c:0018 p:---- s:0055 e:000054 CFUNC  :require

c:0017 p:0009 s:0051 e:000050 CLASS  /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/ext.rb:13

c:0016 p:0011 s:0049 e:000048 CLASS  /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/ext.rb:12

c:0015 p:0057 s:0047 e:000046 TOP    /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/ext.rb:9 [FINISH]

c:0014 p:---- s:0045 e:000044 CFUNC  :require

c:0013 p:0019 s:0041 e:000040 CLASS  /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json.rb:58

c:0012 p:0017 s:0039 e:000038 TOP    /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json.rb:54 [FINISH]

c:0011 p:---- s:0037 e:000036 CFUNC  :require

c:0010 p:0007 s:0033 e:000032 TOP    /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core.rb:1 [FINISH]

c:0009 p:---- s:0031 e:000030 CFUNC  :require

c:0008 p:0007 s:0027 e:000026 TOP    /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/fastlane-1.85.0/lib/fastlane.rb:1 [FINISH]

c:0007 p:---- s:0025 e:000024 CFUNC  :require

c:0006 p:0027 s:0021 e:000020 TOP    /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/fastlane-1.85.0/bin/fastlane:4 [FINISH]

c:0005 p:---- s:0019 e:000018 CFUNC  :load

c:0004 p:0134 s:0015 E:001098 EVAL   /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/fastlane:23 [FINISH]

c:0003 p:---- s:0011 e:000010 CFUNC  :eval

c:0002 p:0118 s:0005 E:0017f0 EVAL   /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15 [FINISH]

c:0001 p:0000 s:0002 E:0010b8 TOP    [FINISH]



/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'

/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'

/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/fastlane:23:in `<main>'

/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/fastlane:23:in `load'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/fastlane-1.85.0/bin/fastlane:4:in `<top (required)>'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/fastlane-1.85.0/bin/fastlane:4:in `require'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/fastlane-1.85.0/lib/fastlane.rb:1:in `<top (required)>'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/fastlane-1.85.0/lib/fastlane.rb:1:in `require'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core.rb:1:in `<top (required)>'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core.rb:1:in `require'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json.rb:54:in `<top (required)>'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json.rb:58:in `<module:JSON>'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json.rb:58:in `require'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/ext.rb:9:in `<top (required)>'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/ext.rb:12:in `<module:JSON>'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/ext.rb:13:in `<module:Ext>'

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/ext.rb:13:in `require'



-- C level backtrace information -------------------------------------------



-- Other runtime information -----------------------------------------------



* Loaded script: /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/fastlane



* Loaded features:



    0 enumerator.so

    1 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/enc/encdb.bundle

    2 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/enc/trans/transdb.bundle

    3 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/rbconfig.rb

    4 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/thread.rb

    5 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/compatibility.rb

    6 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/defaults.rb

    7 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/deprecate.rb

    8 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/errors.rb

    9 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/version.rb

   10 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/requirement.rb

   11 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/platform.rb

   12 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb

   13 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/stub_specification.rb

   14 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/util/stringio.rb

   15 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb

   16 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/exceptions.rb

   17 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_gem.rb

   18 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/monitor.rb

   19 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb

   20 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems.rb

   21 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/path_support.rb

   22 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/dependency.rb

   23 /Users/travis/.rvm/gems/ruby-2.0.0-p648@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb

   24 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/etc.bundle

   25 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/fileutils.rb

   26 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/pathname.bundle

   27 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/pathname.rb

   28 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/environment_preserver.rb

   29 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/socket.bundle

   30 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/socket.rb

   31 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/timeout.rb

   32 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/protocol.rb

   33 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/common.rb

   34 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/generic.rb

   35 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/ftp.rb

   36 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/http.rb

   37 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/https.rb

   38 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/ldap.rb

   39 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/ldaps.rb

   40 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/mailto.rb

   41 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri.rb

   42 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/zlib.bundle

   43 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/stringio.bundle

   44 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http/exceptions.rb

   45 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http/header.rb

   46 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http/generic_request.rb

   47 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http/request.rb

   48 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http/requests.rb

   49 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http/response.rb

   50 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http/responses.rb

   51 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http/proxy_delta.rb

   52 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http/backward.rb

   53 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/net/http.rb

   54 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/date_core.bundle

   55 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/date/format.rb

   56 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/date.rb

   57 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/time.rb

   58 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/io/console.bundle

   59 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/user_interaction.rb

   60 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/request/http_pool.rb

   61 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/request/https_pool.rb

   62 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/request/connection_pools.rb

   63 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/request.rb

   64 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/cgi/core.rb

   65 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/cgi/util.rb

   66 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/cgi/cookie.rb

   67 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/cgi.rb

   68 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/uri_formatter.rb

   69 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/fcntl.bundle

   70 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/digest.bundle

   71 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/digest.rb

   72 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/openssl.bundle

   73 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/openssl/bn.rb

   74 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/openssl/cipher.rb

   75 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/openssl/config.rb

   76 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/openssl/digest.rb

   77 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/openssl/x509.rb

   78 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/openssl/buffering.rb

   79 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/openssl/ssl.rb

   80 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/openssl.rb

   81 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/securerandom.rb

   82 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/resolv.rb

   83 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/remote_fetcher.rb

   84 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/gem_remote_fetcher.rb

   85 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/gem_helpers.rb

   86 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/match_platform.rb

   87 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/rubygems_ext.rb

   88 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/config_file.rb

   89 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/ext/build_error.rb

   90 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/ext/builder.rb

   91 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/ext/configure_builder.rb

   92 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/delegate.rb

   93 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/tmpdir.rb

   94 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/tempfile.rb

   95 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/ext/ext_conf_builder.rb

   96 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/ext/rake_builder.rb

   97 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/optparse.rb

   98 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/command.rb

   99 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/ext/cmake_builder.rb

  100 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/ext.rb

  101 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/rubygems_integration.rb

  102 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/version.rb

  103 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/constants.rb

  104 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/current_ruby.rb

  105 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/errors.rb

  106 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler.rb

  107 /Users/travis/.rvm/gems/ruby-2.0.0-p648@global/gems/bundler-unload-1.0.2/lib/bundler-unload.rb

  108 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/digest/sha1.bundle

  109 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/environment.rb

  110 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/shared_helpers.rb

  111 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/runtime.rb

  112 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/settings.rb

  113 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/x86_64-darwin15.0.0/strscan.bundle

  114 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/source.rb

  115 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/source/path.rb

  116 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/source/git.rb

  117 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/text.rb

  118 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/name_tuple.rb

  119 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/spec_fetcher.rb

  120 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/source/rubygems.rb

  121 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/lockfile_parser.rb

  122 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/set.rb

  123 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/definition.rb

  124 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/dependency.rb

  125 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/ruby_dsl.rb

  126 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/dsl.rb

  127 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/source_list.rb

  128 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/lazy_specification.rb

  129 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/tsort.rb

  130 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/forwardable.rb

  131 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/spec_set.rb

  132 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/dep_proxy.rb

  133 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/index.rb

  134 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/remote_specification.rb

  135 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/stub_specification.rb

  136 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/endpoint_specification.rb

  137 /Users/travis/.rvm/gems/ruby-2.0.0-p648@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb

  138 /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/version.rb

  139 /Users/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/ostruct.rb

  140 /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/generic_object.rb

  141 /Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/common.rb



[NOTE]

You may have encountered a bug in the Ruby interpreter or extension libraries.

Bug reports are welcome.

Don't forget to include the above Crash Report log file.

For details: http://www.ruby-lang.org/bugreport.html



/Users/travis/build.sh: line 45:  2468 Abort trap: 6           fastlane test



travis_time:end:0487f038:start=1462467043253695000,finish=1462467045777455000,duration=2523760000
[0K

[31;1mThe command "fastlane test" exited with 134.[0m

travis_fold:start:cache.2
[0Kstore build cache

$ bundle clean

Removing cert (1.4.0)

Removing fastlane (1.82.0)

Removing fastlane_core (0.42.0)

Removing frameit (2.5.1)

Removing google-api-client (0.9.5)

Removing mini_magick (4.0.4)

Removing multi_json (1.11.3)

Removing pilot (1.5.0)

Removing produce (1.1.1)

Removing scan (0.5.2)

Removing sigh (1.6.1)

Removing spaceship (0.26.1)

travis_time:start:1150065c
[0K

travis_time:end:1150065c:start=1462467048070012000,finish=1462467048087448000,duration=17436000
[0Ktravis_time:start:266703a1
[0K[32;1mchange detected:

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/cert

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/commander

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/deliver

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/dotenv

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/fastlane

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/fastlane-credentials

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/frameit

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/generate-api

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/gym

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/httpclient

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/krausefx-ipa

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/match

/Users/travis/build/MyOrgName/MyAppname/vendor/bundle/ruby/2.0.0/bin/nokogiri

/Users

[0m

[32;1m...

[0m

[32;1mchanges detected, packing new archive[0m

.

.

[32;1muploading archive[0m



travis_time:end:266703a1:start=1462467048130873000,finish=1462467067014724000,duration=18883851000
[0Ktravis_fold:end:cache.2
[0K

Done. Your build exited with 1.

```

### Configuration Files
Fastfile has not changed between working and non-working builds. 

Gemfile:
```ruby
source 'https://rubygems.org'
gem 'fastlane', '~>1.85.0'
gem 'slather', '~>2.1'
```

### Environment

fastlane version (run `fastlane -v`): not available right now

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? Yes. From the travis output:

```
$ ruby --version

ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin15.0.0]

$ rvm --version

rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

$ bundle --version

Bundler version 1.12.2
```

**Comment by vpolouchkine** [comment]
Thanks for the report!

**Comment by solarce** [comment]
If this is wide-spread, we can revert our 7.3 image to `2.0.0-p643` but it would be helpful to know whether it's systemic or not

**Comment by TKBurner** [comment]
Hi @brockboland! Are you still seeing this issue when you update fastlane using fastlane run update_fastlane? 

Thanks!

**Comment by brockboland** [comment]
@bryanluby helped test this out with a fresh project and clean Fastfile, and wasn't ever able to replicate it. So I tried removing the `rvm` line from my Travis config on the same project, and it worked fine. I can only assume that Travis fixed some problem in their xcode7.3 image after I posted this. Sorry to bother you all!
