### ISSUE TITLE
Get stuck with this error when pilot

### ISSUE THREAD

**Issue by macbaszii** [fastlane/fastlane#4525]
I always have got this error since yesterday.
from the error. Should I update fastlane to latest version ?

I use CircleCI for build tools. my circle.yml file looks like this

```ruby
machine:
  xcode:
    version: 7.3
dependencies:
  pre:
    - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
    - sudo gem update fastlane
    - sudo gem update gym
test:
  override:
    - set -o pipefail &&
      xcodebuild
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_IDENTITY=
        PROVISIONING_PROFILE=
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6'
        -workspace Playground.xcworkspace
        -scheme "Playground"
        clean build test |
      tee $CIRCLE_ARTIFACTS/xcode_raw.log |
      xcpretty --color --report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml
deployment:
  staging:
    branch: develop
    commands:
    - fastlane staging
  production:
    branch: master
    commands:
    - fastlane production
```

in `pre` label, That's mean I force to update fastlane every times I build the app.

##### Complete output when running fastlane, including the stack trace and command used

```
[10:15:05]: -------------------
[10:15:05]: --- Step: pilot ---
[10:15:05]: -------------------

#######################################################################
# fastlane 1.85.0 is available. You are on 1.66.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################
# Run `sudo gem cleanup` from time to time to speed up fastlane
#######################################################################

1.85.0 Introducing Device Grid
- Added device_grid for fastlane, appetize and danger

- Improved `fastlane action` command

- Shell escape git commit / tag messages



## Introducing [Device Grid](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/device_grid/README.md#readme)



Ever dream of testing your app straight from a pull request? Well now you can! With [fastlane](https://fastlane.tools), [danger](https://github.com/danger/danger) and [appetize.io](https://appetize.io/), you can stream your latest changes right from the browser.



No more manually installing and testing your app just to review a PR.



![](https://raw.githubusercontent.com/fastlane/fastlane/1.85.0/fastlane/lib/fastlane/actions/device_grid/assets/GridExampleScreenshot.png)



All you have to do to preview your app is to click on one of the simulators, and you can stream the app right in your browser: [Open example PR](https://github.com/Themoji/ios/pull/12#issuecomment-215836315).



**[:rocket: Get started with Device Grid :rocket:](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/device_grid/README.md#readme)**

1.84.0 Improvements
* Use relocated ToolCollector as the basis for ActionCollector
* Improved lane selection description output
* Improved description of binary_path option of `upload_symbols_to_crashlytics` action
* Added rocket emoji as a fastlane binary 🚀
* Add `testers_groups` option to `testfairy` action
* Update `gradle` action documentation for command and output printing controls
* Add `pod_lib_lint` action
* Make body of commit optional in jenkins changelog generation

1.83.0 Improvements
* Give `gradle` action better control over command output
* Add support for `--verbose` and 'github_api_token' in `danger` action
* Add support for specifying short and bundle versions in `resign` action
* Add 'message' option to the `add_git_tag` action
* Fix bash syntax in auto completion script

To see all new releases, open https://github.com/fastlane/fastlane/releases

Update using 'sudo gem update fastlane'
/usr/local/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate frameit-2.6.1, because fastimage-1.9.0 conflicts with fastimage (~> 1.6.3) (Gem::ConflictError)
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1408:in `activate'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /usr/local/lib/ruby/gems/2.0.0/gems/pilot-1.5.1/lib/pilot/manager.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.0.0/gems/pilot-1.5.1/lib/pilot.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/actions/pilot.rb:40:in `available_options'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/configuration_helper.rb:4:in `parse'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:135:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `chdir'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:71:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/bin/fastlane:38:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /usr/local/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/bin/fastlane:156:in `run'
	from /usr/local/lib/ruby/gems/2.0.0/gems/fastlane-1.66.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.0.0/bin/fastlane:22:in `load'
	from /usr/local/lib/ruby/gems/2.0.0/bin/fastlane:22:in `<main>'

fastlane production returned exit code 1

Action failed: fastlane production
```

**Comment by vpolouchkine** [comment]
You're on a pretty old version of `fastlane`, I recommend upgrading as the first step.

**Comment by macbaszii** [comment]
@vpolouchkine yeah, the version on CircleCI is 1.66 by default. I tried to update before run everything (did you see `pre` label in `circle.yml` ?) It is not updated even I wrote the force update command. I don't know why.

**Comment by asfalcone** [comment]
Underly issue is here
```
Unable to activate frameit-2.6.1, because fastimage-1.9.0 conflicts with fastimage (~> 1.6.3) (Gem::ConflictError)
```

**Comment by i2amsam** [comment]
@macbaszii hrm, this is odd.  Nothing I see in `fastlane` depends on `fastimage-1.9.0`, so I suspect that this is getting added by `circle` somehow, perhaps this is also why `fastlane` is out of date despite the `pre` block.  I'd suggest adding a `Gemfile` to your project, for example:

```
source 'https://rubygems.org'

gem 'fastlane',  '=> 1.85'
```

and then doing `bundle install` where you are doing `gem install`, and 

```
bundle exec fastlane production
``` 

where you are calling it.  Let me know if that improves anything!

**Comment by macbaszii** [comment]
Thank you everyone. I have figured it out.
I have to put `sudo gem cleanup fastlane` after updated command.

It will remove default version and replace with latest version in CircleCI's machine.

**Comment by TKBurner** [comment]
@macbaszii Awesome! So glad to hear you got up and running. I'll close out this ticket 👍
