### ISSUE TITLE
Frameit fails on iPhone5 when executed from fastlane lane

### ISSUE THREAD

**Issue by ekolesnikov** [fastlane/fastlane#4553]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Frameit fails on iphone5/5s screenshots when executed as a part of the lane.
Works fine when run standalone using frameit command.

##### Complete output when running fastlane, including the stack trace and command used

```
ERROR [2016-05-07 19:01:46.91]: undefined method `[]' for nil:NilClass
ERROR [2016-05-07 19:01:46.91]: Backtrace:
        /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.1/lib/frameit/screenshot.rb:29:in `device_name'
        /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.1/lib/frameit/screenshot.rb:54:in `mac?'
        /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.1/lib/frameit/screenshot.rb:73:in `frame!'
        /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.1/lib/frameit/runner.rb:29:in `block in run'
        /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.1/lib/frameit/runner.rb:21:in `each'
        /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.1/lib/frameit/runner.rb:21:in `run'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/actions/frameit.rb:18:in `block in run'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/actions/frameit.rb:16:in `chdir'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/actions/frameit.rb:16:in `run'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/runner.rb:173:in `block (2 levels) in execute_action'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/runner.rb:158:in `block in execute_action'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/runner.rb:157:in `chdir'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/runner.rb:157:in `execute_action'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/runner.rb:111:in `trigger_action_by_name'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/fast_file.rb:130:in `method_missing'
        Fastfile:123:in `block (2 levels) in parsing_binding'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/lane.rb:33:in `call'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/lane.rb:33:in `call'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/runner.rb:52:in `block in execute'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/runner.rb:46:in `chdir'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/runner.rb:46:in `execute'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/command_line_handler.rb:30:in `handle'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
        /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
        /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/commands_generator.rb:172:in `run'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/commands_generator.rb:13:in `start'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
        /Library/Ruby/Gems/2.0.0/gems/fastlane-1.86.1/bin/fastlane:5:in `<top (required)>'
        /usr/local/bin/fastlane:23:in `load'
        /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  lane :rc do
    set_info_plist_value(
        path: ENV["TARGET_PLIST_FILE"],
        key: "CFBundleVersion",
        value: ENV["BUILD_NUMBER"]
    )
  
    match(type: "appstore", keychain_name: ENV["MATCH_KC"])
    cocoapods
    gym
    snapshot
    frameit
    deliver(force: true)
  end
```

### Environment

fastlane 1.86.1
frameit 2.6.1

**Comment by ekolesnikov** [comment]
So I used byebug to figure out what was going on. A bit unexpected behaviour.
Running standalone:
```
[26, 35] in /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.1/lib/frameit/screenshot.rb
   26:         return 'iPhone-6s-Plus'
   27:       when sizes::IOS_47
   28:         return 'iPhone-6s'
   29:       when sizes::IOS_40
   30:         byebug
=> 31:         return Frameit.config[:use_legacy_iphone5s] ? 'iPhone_5s' : 'iPhone-SE'
   32:       when sizes::IOS_35
   33:         return 'iPhone_4'
   34:       when sizes::IOS_IPAD
   35:         return 'iPad-mini'
(byebug) Frameit.config[:use_legacy_iphone5s]
false
(byebug) self
#<Frameit::Screenshot:0x007fc34c1a1758 @color="SpaceGray", @path="./fastlane/screenshots/en-AU/iPhone5s-A1first.png", @size=[640, 1136], @screen_size="iOS-4-in">
(byebug) Frameit.config
#<FastlaneCore::Configuration:0x007fc34b0a0fd0 @available_options=[#<FastlaneCore::ConfigItem:0x007fc34c839e08 @key=:use_legacy_iphone5s, @env_name="FRAMEIT_USE_LEGACY_IPHONE_5_S", @description="use iPhone 5s instead of iPhone SE frames", @short_option=nil, @default_value=false, @verify_block=nil, @is_string=false, @data_type=nil, @optional=true, @conflicting_options=nil, @conflict_block=nil, @deprecated=nil>], @values={}>
(byebug) Frameit
Frameit
```

Running 'fastlane rc':
```

[25, 34] in /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.1/lib/frameit/screenshot.rb
   25:         return 'iPhone-6s-Plus'
   26:       when sizes::IOS_47
   27:         return 'iPhone-6s'
   28:       when sizes::IOS_40
   29:         byebug
=> 30:         return Frameit.config[:use_legacy_iphone5s] ? 'iPhone_5s' : 'iPhone-SE'
   31:       when sizes::IOS_35
   32:         return 'iPhone_4'
   33:       when sizes::IOS_IPAD
   34:         return 'iPad-mini'

(byebug) Frameit.config[:use_legacy_iphone5s]
*** NoMethodError Exception: undefined method `[]' for nil:NilClass

nil
(byebug) Frameit
Frameit
(byebug) Frameit.config
nil
(byebug) self
#<Frameit::Screenshot:0x007fca9949afc8 @color="SpaceGray", @path="./en-AU/iPhone5s-A1first.png", @size=[640, 1136], @screen_size="iOS-4-in">
(byebug) self.config
*** NoMethodError Exception: undefined method `config' for #<Frameit::Screenshot:0x007fca9949afc8>

nil
```

Will keep you guys posted as I get deeper into it.

**Comment by ekolesnikov** [comment]
Ok, it seems that this happens when running frameit script, but there is no initialiser when frameit is executed as a part of the lane:

```ruby
  def load_config(options)
    o = options.__hash__.dup
    o.delete(:verbose)
    Frameit.config = FastlaneCore::Configuration.create(Frameit::Options.available_options, o)
  end
end

```

**Comment by ekolesnikov** [comment]
Ok, so apparently there are quite a few ways to do this, I would need a piece of advice before creating a pull request. Add to frameit.rb?

**Comment by i2amsam** [comment]
👍 Thanks for the detailed report @ekolesnikov !  I'm going to take a look at this.

**Comment by ekolesnikov** [comment]
Thanks for looking into this @i2amsam!

//off-topic mode on: could you ask Mr @TKBurner to have another look at https://github.com/fastlane/fastlane/issues/4482 please? I believe there was a bit of confusion there - not sure what would be the right github process to follow up.

**Comment by i2amsam** [comment]
@ekolesnikov I just released this fix with `fastlane 1.87.1` could you give it a try and let me know if it fixed the problem for you?  I'll ping @TKBurner about the other ticket.

**Comment by ekolesnikov** [comment]
@i2amsam confirmed frameit now working with iPhone SE frames from the lane. Thanks!

**Comment by KrauseFx** [comment]
Awesome work @i2amsam 🚀
