### ISSUE TITLE
Fastlane `init` error: Unable to activate deliver-1.11.3

### ISSUE THREAD

**Issue by ricardopereira** [fastlane/fastlane#4596]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
➜  demo-ios git:(automation-beta-build) ✗ fastlane init
[15:45:28]: Detected iOS/Mac project in current directory...
[15:45:28]: This setup will help you get up and running in no time.
[15:45:28]: fastlane will check what tools you're already using and set up
[15:45:28]: the tool automatically for you. Have fun!
[15:45:28]: Created new folder './fastlane'.
[15:45:28]: xcrun xcodebuild -list -workspace './Demo.xcworkspace'
Your Apple ID (e.g. fastlane@krausefx.com): dev@whitesmith.co
[15:45:36]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[15:45:36]: Starting login with user 'dev@whitesmith.co'

+----------------+---------------------------------------------------------------------------------+
|                                         Detected Values                                          |
+----------------+---------------------------------------------------------------------------------+
| Apple ID       | dev@whitesmith.co                                                          |
| App Name       | Demo                                                                        |
| App Identifier | co.whitesmith.demo                                                          |
| Workspace      | /Users/user/Repositories/Whitesmith/demo-ios/Demo.xcworkspace |
+----------------+---------------------------------------------------------------------------------+

Please confirm the above values (y/n)
y
[15:45:45]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
[15:45:45]: Loading up 'deliver', this might take a few seconds
/Users/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate deliver-1.11.3, because plist-3.2.0 conflicts with plist (~> 3.1.0) (Gem::ConflictError)
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1408:in `activate'
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems.rb:208:in `rescue in try_activate'
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems.rb:201:in `try_activate'
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane-1.87.0/lib/fastlane/setup/setup_ios.rb:226:in `enable_deliver'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane-1.87.0/lib/fastlane/setup/setup_ios.rb:73:in `default_setup'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane-1.87.0/lib/fastlane/setup/setup_ios.rb:34:in `run'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane-1.87.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:52:in `block (2 levels) in run'
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane_core-0.43.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane-1.87.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/user/.gem/ruby/2.2.0/gems/fastlane-1.87.0/bin/fastlane:5:in `<top (required)>'
	from /Users/user/.gem/ruby/2.2.0/bin/fastlane:22:in `load'
	from /Users/user/.gem/ruby/2.2.0/bin/fastlane:22:in `<main>'
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.87.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by TKBurner** [comment]
Hi @ricardopereira! Thanks for reaching out. Can you install the ruby gem plist 3.1.0? It looks like you have a version conflict. Thanks for working with me! 👍

**Comment by ricardopereira** [comment]
It's working now! Thank you :+1:

**Comment by TKBurner** [comment]
@ricardopereira Awesome! Really glad to hear you got up and running!
