### ISSUE TITLE
Snapshot: Looks like the number of screenshots (3) doesn't match the number of names (6)

### ISSUE THREAD

**Issue by markuswinkler** [fastlane/fastlane#4599]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I run snapshot it executes the UI test successfully but somehow thinks it should have double the screenshots.

snapfile is the default one.
UI test is setup in the most basic way.

    override func setUp() {
        super.setUp()
        
        continueAfterFailure = false
        XCUIDevice.sharedDevice().orientation = .Portrait
        
        let app = XCUIApplication()
        setupSnapshot(app)
        app.launch()
    }
    
    func testMenubar() {
        let app = XCUIApplication()
        
        app.buttons["MenuBar Chat"].tap()
        snapshot("0ChatScreen")
        app.buttons["MenuBar Browse"].tap()
        snapshot("0MatchScreen")
        app.buttons["MenuBar Stats"].tap()
        snapshot("0Stats")
    }

The test itself runs perfectly fine inside XCode and also executes with snapshot, however, for whatever reason snapshot thinks there should be twice the amount of snapshots at the first try.
Interestingly it succeeds on the second try (number_of_retries 1), but the first one ALWAYS fails.

any idea?

##### Complete output when running fastlane, including the stack trace and command used

```
    Looks like the number of screenshots (3) doesn't match the number of names (6)
    Copying '/Users/markus/..../screenshots/en-US/iPhone6Plus-FDataSnapshot, _ key: String, _ defaultValue: String) -> String.png'...
    Copying '/Users/markus/..../screenshots/en-US/iPhone6Plus-FDataSnapshot, _ key: String, _ defaultValue: Int) -> Int.png'...
    Copying '/Users/markus/..../screenshots/en-US/iPhone6Plus-FDataSnapshot) -> FirebaseAPI.ConversationData.png'...
    no implicit conversion of nil into String
```
when it tries to process the list then it obviously runs into an error processing a nil value.
```
    /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/collector.rb:32:in `join': [!] no implicit conversion of nil into String (TypeError)
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/collector.rb:32:in `block in fetch_screenshots'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/collector.rb:21:in `each'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/collector.rb:21:in `each_with_index'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/collector.rb:21:in `fetch_screenshots'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/runner.rb:190:in `launch'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/runner.rb:66:in `run_for_device_and_language'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/runner.rb:45:in `block (3 levels) in work'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/runner.rb:37:in `each'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/runner.rb:37:in `block (2 levels) in work'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/runner.rb:36:in `each'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/runner.rb:36:in `block in work'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/runner.rb:35:in `each'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/lib/snapshot/runner.rb:35:in `work'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/bin/snapshot:36:in `block (2 levels) in run'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/fastlane_core-0.43.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/bin/snapshot:96:in `run'
	from /Users/markus/.rvm/gems/ruby-2.2.3/gems/snapshot-1.12.2/bin/snapshot:110:in `<top (required)>'
	from /Users/markus/.rvm/gems/ruby-2.2.3/bin/snapshot:23:in `load'
	from /Users/markus/.rvm/gems/ruby-2.2.3/bin/snapshot:23:in `<main>'
	from /Users/markus/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/markus/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

default snapfile

### Environment

fastlane version (run `fastlane -v`):
snapshot 1.12.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
yes

**Comment by vpolouchkine** [comment]
Can you provide a sample repro project?

**Comment by markuswinkler** [comment]
Hmm, I created a new project with a similar setup. Everything seems to work fine.
Tricky problem. Unfortunately I can't share the code base where the problem originated.
Any advise?

**Comment by vpolouchkine** [comment]
What happens if you change the Snapfile to only target a single sim?

**Comment by markuswinkler** [comment]
same result. the first device it tries I get the result from above.

**Comment by TKBurner** [comment]
Hi @markuswinkler Thanks for following up. Can you share your snapfile as well as your Fastfile? I want to take a look! Thanks 👍

**Comment by markuswinkler** [comment]
@TKBurner, sure, thank you!
I don't use the snapshot command in the fastfile though, only directly via terminal.

snapfile
```
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
#   "iPhone 6",
#   "iPhone 6 Plus",
#   "iPhone 5",
   "iPhone 4s"
#   "iPad Retina",
#   "iPad Pro"
])

languages([
#  "en-US",
  "de-DE"
#  "it-IT",
#  ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
scheme "Pretzel"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./Pretzel.xcworkspace"

# For more information about all available options run
# snapshot --help

stop_after_first_error true
number_of_retries 1
configuration "Debug"
#localize_simulator true
```

fastfile
```
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.68.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods
    ensure_git_status_clean
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build your app"
  lane :build do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Pretzel",include_bitcode:true,include_symbols:true,clean:true,output_directory:"./build") 
  end

  desc "Increase build number and submit to TestFlight"
  lane :beta do
	increment_build_number
	#increment_version_number

	# Make sure our directory is clean, except for changes Fastlane has made
  	clean_build_artifacts

	commit_version_bump
	add_git_tag	
	push_to_git_remote

    gym(scheme: "Pretzel",include_bitcode:true,include_symbols:true,clean:true,output_directory:"./build") 
    pilot(skip_submission:true, distribute_external:false)
  end

  desc "Build only and submit to TestFlight"
  lane :beta_build_and_submit do
    gym(scheme: "Pretzel",include_bitcode:true,include_symbols:true,clean:true,output_directory:"./build") 
    pilot(skip_submission:true, distribute_external:false)
  end


  desc "Submit to TestFlight AND push to external"
  lane :beta_external do
    gym(scheme: "Pretzel",include_bitcode:true,include_symbols:true,clean:true,output_directory:"./build") 
    pilot(skip_submission:false, distribute_external:true)
  end


  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Pretzel",include_bitcode:true,include_symbols:false,clean:true,output_directory:"./build") 
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    say "Everything worked"
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

```

**Comment by vpolouchkine** [comment]
Can you remove 
```
stop_after_first_error true
number_of_retries 1
configuration "Debug"
```
and try again please?

**Comment by markuswinkler** [comment]
same result. :(
I noticed that the UITest app is launching the main app twice, first time super quick open close without really executing anything, the second time it really does the UI tests.

**Comment by vpolouchkine** [comment]
Hm, that's odd. I'm not sure if we are going to be able to debug this without repro steps.

**Comment by markuswinkler** [comment]
If this is completely new and unheard of behavior I know this is close to impossible
to debug without access to the project.
I really appreciate the feedback. Maybe someone else runs into the same issue.

**Comment by TKBurner** [comment]
@markuswinkler Thanks for following up. 

Can you try setting these params:

clear_previous_screenshots - true
reinstall_app - true
erase_simulator - true
clean - true

Thanks for working with us!

**Comment by markuswinkler** [comment]
Thank you for your help.
I tried the option and the result was the same, but it pointed me into a new direction.
I reduced the test to just one snapshot and got again the same error.
But this way I found out it's not a multiple, it just _adds_ 3 events
(before 3 events -> 6 expected, now 1 event -> 4 expected)

See below:

Test Suite:

```
import XCTest
import UIKit

class PretzelUITests: XCTestCase {
    
    override func setUp() {
        super.setUp()
        
        // Put setup code here. This method is called before the invocation of each test method in the class.
        
        // In UI tests it is usually best to stop immediately when a failure occurs.
        continueAfterFailure = false
        
        // UI tests must launch the application that they test. Doing this in setup will make sure it happens for each test method.
        XCUIDevice.sharedDevice().orientation = .Portrait
        
        let app = XCUIApplication()
        app.launchEnvironment = [ "UITest": "1" ]
        setupSnapshot(app)
        app.launch()
        // In UI tests it’s important to set the initial state - such as interface orientation - required for your tests before they run. The setUp method is a good place to do this.
    }
    
    override func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
        super.tearDown()
    }
    
    func testStart() {
        // Use recording to get started writing UI tests.
        // Use XCTAssert and related functions to verify your tests produce the correct results.
        snapshot("start")
    }
}
```

and the result:
```
[12:49:35]: Running Tests: ▸ Touching PretzelUITests.xctest
[12:49:54]: ▸ Test Succeeded
[12:49:54]: ▸ All tests
[12:49:54]: ▸ Test Suite PretzelUITests.xctest started
[12:49:54]: ▸ PretzelUITests
[12:49:54]: ▸ ✓ testStart (5.344 seconds)
[12:49:54]: ▸ 	 Executed 1 test, with 0 failures (0 unexpected) in 5.344 (5.346) seconds
[12:49:54]: ▸ 
[12:49:54]: Collecting screenshots...
[12:49:54]: Found 1 screenshots...
[12:49:54]: Looks like the number of screenshots (1) doesn't match the number of names (4)
[12:49:54]: Copying '/Users/markus/Dropbox/_Pretzel/tech/PretzelApp/screenshots/de-DE/iPhone4s-FDataSnapshot, _ key: String, _ defaultValue: String) -> String.png'...
[12:49:54]: no implicit conversion of nil into String
```

I tried to be as thorough as possible, cleaned the project & ran watchdog before running snapshot to make sure there are no old references.
Is it possible that there is a "ghosting" reference to names buried somewhere in the xcode project?

**Comment by TKBurner** [comment]
@markuswinkler Thanks for following up. What happens when you remove the snapshot('start') function from testStart? 👍

**Comment by markuswinkler** [comment]
```
[15:36:24]: Looks like the number of screenshots (0) doesn't match the number of names (3)
[15:36:24]: no implicit conversion of nil into String
```
so my suspicion was right. is there any way to track this down further?

**Comment by TKBurner** [comment]
Hi @markuswinkler! Can you send me a screenshot of the contents of the destination folder for these screenshots? Thanks!

**Comment by markuswinkler** [comment]
@TKBurner The destination folder is empty if I specify 0 events.

**Comment by TKBurner** [comment]
@markuswinkler Thanks for following up. I just looped in the core team and we'll follow up on this thread. I hope that you have a wonderful weekend! 👍

**Comment by markuswinkler** [comment]
@TKBurner Thank you! I really appreciate it, especially since it seems to be such an odd problem.
Wish you a great weekend too!

**Comment by RedPandaTk** [comment]
@markuswinkler, I was having a similar issue and it looks like for me, the issue was that my own logging statements were conflicting with snapshot.  Before each snapshot, I had a logging statement that had "snapshot:" in it.  It looked like snapshot was picking these up and expecting screenshots for these statements.  Once I removed these custom log statements, screenshots worked as expected and my count wasn't off.

So for example, if I had:

> 
print("custom_snapshot: blablabla taking a snapshot.png")
snapshot(filename, waitForLoadingIndicator: true)

Then snapshot would expect 2 screenshots, as opposed to if I just had:
>
snapshot(filename, waitForLoadingIndicator: true)

Then snapshot would only expect 1 screenshot.

**Comment by markuswinkler** [comment]
Ha! That's a good catch!
Unfortunately that doesn't apply to my case.
I even removed all snapshot lines and comments and it still says `Looks like the number of screenshots (0) doesn't match the number of names (3)`
