### ISSUE TITLE
getting uninitialized constant Spaceship::Client::ITunesConnectError while running cert

### ISSUE THREAD

**Issue by WilliamParty** [fastlane/fastlane#4633]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hi everybody!
I'm using fastlane for quite a while now, but today I'm getting the following issue out of the blue
> uninitialized constant Spaceship::Client::ITunesConnectError

Thank you for your time!

##### Complete output when running fastlane, including the stack trace and command used

```
18:07:54]: ------------------
[18:07:54]: --- Step: cert ---
[18:07:54]: ------------------

+---------------+--------------------------------------------------+
|                      Summary for cert 1.4.1                      |
+---------------+--------------------------------------------------+
| development   | false                                            |
| force         | false                                            |
| username      | aurelio.muccio@gmail.com                         |
| keychain_path | /Users/MBSAdmin/Library/Keychains/login.keychain |
+---------------+--------------------------------------------------+

[18:07:58]: Starting login with user 'aurelio.muccio@gmail.com'
[18:08:01]: -------------------
[18:08:01]: --- Step: slack ---
[18:08:01]: -------------------
[18:08:03]: Successfully sent Slack notification
[18:08:03]: Variable Dump:
[18:08:03]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios app_store", :BUILD_NUMBER=>"2"}
[18:08:03]: uninitialized constant Spaceship::Client::ITunesConnectError

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | git-ios-apps-update                 | 3           |
| 4    | increment_build_number              | 0           |
| 5    | commit_version_bump                 | 2           |
| 6    | push_to_git_remote                  | 4           |
| 7    | cert                                | 6           |
| 8    | slack                               | 1           |
+------+-------------------------------------+-------------+

[18:08:03]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:305:in `send_shared_login_request': [!] uninitialized constant Spaceship::Client::ITunesConnectError (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:35:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:346:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:225:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:88:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/lib/cert/runner.rb:17:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/lib/cert/runner.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/actions/cert.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/runner.rb:173:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/runner.rb:158:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/runner.rb:157:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/runner.rb:157:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/runner.rb:111:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/fast_file.rb:130:in `method_missing'
	from ../../../tools/fastlane/Fastfile:59:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.4/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

fastlane version (run `fastlane -v`): 1.88.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Nope

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? Nope

**Comment by KrauseFx** [comment]
Hey @WilliamParty, thanks for submitting this issue. I see what's the problem, and work on a fix right now 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/4669, this will be in the next release 👍

**Comment by WilliamParty** [comment]
Thank you Krause, have a nice day!

**Comment by KrauseFx** [comment]
It already is https://rubygems.org/gems/spaceship/versions/0.27.1 🚀
