### ISSUE TITLE
Sigh fails to login with emails containing a plus sign (+)

### ISSUE THREAD

**Issue by brockboland** [fastlane/fastlane#4637]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I've seen this a few times but haven't reported it yet: sigh seems to be unable to login to the Apple dev center when the email address includes a `+`

##### Complete output when running fastlane, including the stack trace and command used

Command:
```
sigh -a com.clientname.app -u "build+client@company.com" --adhoc -b 1234567890 -n "Client Ad-Hoc" --ignore_profiles_with_different_name 1 -z 1 --verbose
```

Output:
```
+-------------------------------------+-------------------------+
|                    Summary for sigh 1.8.0                     |
+-------------------------------------+-------------------------+
| app_identifier                      | com.clientname.app      |
| username                            | build+client@company.com|
| adhoc                               | true                    |
| team_id                             | 1234567890              |
| provisioning_name                   | Client Ad-Hoc           |
| ignore_profiles_with_different_name | 1                       |
| skip_certificate_verification       | 1                       |
| skip_install                        | false                   |
| development                         | false                   |
| force                               | false                   |
| skip_fetch_profiles                 | false                   |
+-------------------------------------+-------------------------+

INFO [2016-05-12 15:52:54.38]: Starting login with user 'build+client@company.com'
/Users/bboland/.rvm/gems/ruby-2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:427:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
  authentication.failed
  Your session has expired.  Please log in.
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:51:in `teams'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/spaceship-0.26.2/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:67:in `select_team'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:37:in `select_team'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:81:in `select_team'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/sigh-1.8.0/lib/sigh/runner.rb:16:in `run'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/sigh-1.8.0/lib/sigh/manager.rb:7:in `start'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/sigh-1.8.0/bin/sigh:35:in `block (2 levels) in run'
  from /Users/bboland/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
  from /Users/bboland/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
  from /Users/bboland/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
  from /Users/bboland/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/fastlane_core-0.43.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
  from /Users/bboland/.rvm/gems/ruby-2.2.0@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/sigh-1.8.0/bin/sigh:99:in `run'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/gems/sigh-1.8.0/bin/sigh:117:in `<top (required)>'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/bin/sigh:23:in `load'
  from /Users/bboland/.rvm/gems/ruby-2.2.0/bin/sigh:23:in `<main>'
```

### Environment

fastlane version (run `fastlane -v`): 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm
```
rvm --version
rvm 1.26.9 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
```

**Comment by brockboland** [comment]
I take it all back, again. When run from fastlane, this error was being output even though the issue seemed to be that I was naming an ad-hoc profile with the ad-hoc flag set to false, though I'm not sure why that produced an authentication error. Either way, I'm back in action.

**Comment by TKBurner** [comment]
@brockboland Awesome! So glad to hear you are back up and running 👍
