### ISSUE TITLE
cert cause "exception object expected" error

### ISSUE THREAD

**Issue by puttin** [fastlane/fastlane#4643]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

0. we have env variables `FASTLANE_USER` & `FASTLANE_PASSWORD` set
0. without using `fastlane`, just `cert`: `$ cert`

##### Complete output when running fastlane, including the stack trace and command used

```
+---------------+------------------------------------------------+
|                     Summary for cert 1.4.1                     |
+---------------+------------------------------------------------+
| development   | false                                          |
| force         | false                                          |
| username      | <our_secret_apple_id>                          |
| keychain_path | /Users/****/Library/Keychains/login.keychain |
+---------------+------------------------------------------------+

INFO [2016-05-13 10:37:16.02]: Starting login with user '<our_secret_apple_id>'
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:266:in `raise': [!] exception object expected (TypeError)
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:266:in `rescue in ensure in inflater'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:263:in `ensure in inflater'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:263:in `inflater'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:279:in `read_body_0'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1134:in `block in get'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1421:in `block (2 levels) in transport_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:162:in `reading_body'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1420:in `block in transport_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:313:in `itc_service_key'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:274:in `block in send_shared_login_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:273:in `send_shared_login_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:35:in `send_login_request'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:346:in `do_login'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:225:in `login'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:88:in `login'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cert-1.4.1/lib/cert/runner.rb:17:in `login'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cert-1.4.1/lib/cert/runner.rb:27:in `run'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cert-1.4.1/bin/cert:33:in `block (2 levels) in run'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.43.4/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cert-1.4.1/bin/cert:49:in `run'
	from /Users/****/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cert-1.4.1/bin/cert:55:in `<top (required)>'
	from /Users/****/.rbenv/versions/2.2.2/bin/cert:23:in `load'
	from /Users/****/.rbenv/versions/2.2.2/bin/cert:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
we are not using fastlane here, just `cert`

### Environment

fastlane version (run `fastlane -v`):
`fastlane 1.89.0`
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
`rbenv 1.0.0`

**Comment by vpolouchkine** [comment]
This is probably related to https://github.com/fastlane/fastlane/issues/4610. Will track it there.
