### ISSUE TITLE
[Proposal] Add alpha validation for apple watch icons

### ISSUE THREAD

**Issue by JunichiT** [fastlane/fastlane#4664]
### Issue Description
Hi, 

When I use `fastlane` on my iOS app including Watch app, I've got following error and failed to upload the app binary to iTunes Connect. (Kindly see the log below)

The reason I encountered this error is the invalid watch app icon (alpha-containing image). Apple thankfully sends a message about this issue _after sending app binary_.
But the problem is that _**it takes some wasteful time until receiving the message**_. (Status is revealed after sending app binary and waiting for the proceeding of iTunes Connect)

If we can notice this message before sending binary, I think `fastlane` will surely increase our productivity more. 
So I suggest to add alpha validation for apple watch icons. 

Thanks,
JunichiT

### Log
```
$ fastlane beta
~~
[00:43:46]: Successfully exported and compressed dSYM file
[00:43:46]: Successfully exported and signed the ipa file:
[00:43:46]: /path/to/myapp.ipa
[00:43:46]: -------------------
[00:43:46]: --- Step: pilot ---
[00:43:46]: -------------------
[00:43:47]: Login to iTunes Connect (j.tsurukawa@gmail.com)
[00:43:51]: Login successful
[00:43:51]: Ready to upload new build to TestFlight (App: xxxxxxxxxx)...
[00:43:52]: Going to upload updated app to iTunes Connect
[00:43:52]: This might take a few minutes, please don't interrupt the script
[00:45:23]: iTunes Transporter successfully finished its job
[00:45:23]: ------------------------------------------------------------------------------------------------------
[00:45:23]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[00:45:23]: ------------------------------------------------------------------------------------------------------
[00:45:23]: Successfully uploaded the new binary to iTunes Connect
[00:45:23]: Waiting for iTunes Connect to process the new build
[00:45:56]: Waiting for iTunes Connect to process the new build
[00:46:28]: Waiting for iTunes Connect to process the new build
[00:47:00]: Waiting for iTunes Connect to process the new build
[00:47:32]: Waiting for iTunes Connect to process the new build
[00:48:04]: Waiting for iTunes Connect to process the new build
[00:48:37]: Variable Dump:
[00:48:37]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/path/to/myapp.ipa", :DSYM_OUTPUT_PATH=>"/path/to/myapp.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/path/to/xcarchive"}
[00:48:37]: undefined method `train_version' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 129         |
| 4    | pilot                               | 291         |
+------+-------------------------------------+-------------+

[00:48:38]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/pilot-1.5.1/lib/pilot/build_manager.rb:91:in `wait_for_processing_build': [!] undefined method `train_version' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.5.1/lib/pilot/build_manager.rb:25:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:177:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:162:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:109:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:35:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment
OSX 10.11.4
fastlane 1.89.0
Xcode 7.3.1

**Comment by KrauseFx** [comment]
Hey @JunichiT, thanks for taking the time to submit this issue. Are you referring to the watch icon that is used in your app (Xcode project) or the one that gets uploaded to iTunes Connect for the store? 

The stack trace you posted is a separate issue, right?

**Comment by JunichiT** [comment]
Hi @KrauseFx, thank you for your reply. 

This is the icon, which is just a png file with alpha channel. 
![icon-24 2x](https://cloud.githubusercontent.com/assets/6250288/15276257/d79a546e-1b1d-11e6-92ec-0fc0a8085e7b.png)
I attach the message from iTunes Connect for more information below:
> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "MyApp". To process your delivery, the following issues must be corrected:
> 
> Invalid Icon - The watch application 'myapp.app/Watch/myappWatch.app' contains an icon file 'myapp.app/Watch/myappWatch.app/AppIcon24x24@2x.png' with an alpha channel. Icons should not have an alpha channel.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

I removed the alpha channel of the icon and redo `fastlane beta`, and it successfully uploaded app binary.

The stack trace can be a separate issue. But I posted in here because I think this might be a supplementary information. (I'm sorry if I'm wrong)

**Comment by KrauseFx** [comment]
@JunichiT Cool, thanks for letting me know. We decided not to do any metadata validation locally in fastlane, since validations change from Apple's side, and we don't want to maintain this extra. I'll close this issue for now, thanks for the suggestion
