### ISSUE TITLE
Supply tries to upload `app-debug.apk` to instead of `app-release.apk`

### ISSUE THREAD

**Issue by mmazzarolo** [fastlane/fastlane#4675]
Hello everyone!

### Issue Description
Supply tries to upload `app-debug.apk` instead of `app-release.apk` (I guess it checks for `apk_paths` instead of `apk` if running gradle and supply in the same lane... but why is `apk_paths` not empty?).

The interested line in the log output is:
`
[14:48:08]: Preparing apk at path '/Users/matteo/dev/tony-app-react/android/app/build/outputs/apk/app-debug.apk' for upload...`

##### Complete output when running fastlane, including the stack trace and command used

```
matteo@Mini-di-Patrick ~/d/tony-app-react (master)> fastlane android alpha
[14:46:55]: -------------------------------------------------
[14:46:55]: --- Step: Verifying required fastlane version ---
[14:46:55]: -------------------------------------------------
[14:46:55]: fastlane version valid
[14:46:55]: ------------------------------
[14:46:55]: --- Step: default_platform ---
[14:46:55]: ------------------------------
[14:46:55]: Driving the lane 'android alpha' 🚀
[14:46:55]: --------------------
[14:46:55]: --- Step: gradle ---
[14:46:55]: --------------------
[14:46:55]: $ /Users/matteo/dev/tony-app-react/android/gradlew assembleRelease -p android/
[14:46:57]: ▸ :app:preBuild UP-TO-DATE
[14:46:57]: ▸ :app:preReleaseBuild UP-TO-DATE
[14:46:57]: ▸ :app:checkReleaseManifest
[14:46:57]: ▸ :app:preDebugBuild UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:compileLint
[14:46:57]: ▸ :react-native-vector-icons:copyReleaseLint UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:preBuild UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:preReleaseBuild UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:checkReleaseManifest
[14:46:57]: ▸ :react-native-vector-icons:preDebugAndroidTestBuild UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:preDebugBuild UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:preDebugUnitTestBuild UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:preReleaseUnitTestBuild UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareComFacebookFrescoFresco081Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareComFacebookReactReactNative0161Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:prepareReleaseDependencies
[14:46:57]: ▸ :react-native-vector-icons:compileReleaseAidl UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:compileReleaseRenderscript UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:generateReleaseBuildConfig UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:generateReleaseAssets UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:mergeReleaseAssets UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:generateReleaseResValues UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:generateReleaseResources UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:mergeReleaseResources UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:processReleaseManifest UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:processReleaseResources UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:generateReleaseSources UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:processReleaseJavaRes UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:compileReleaseJavaWithJavac UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:extractReleaseAnnotations UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:mergeReleaseProguardFiles UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:packageReleaseJar UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:compileReleaseNdk UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:packageReleaseJniLibs UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:packageReleaseLocalJar UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:packageReleaseRenderscript UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:packageReleaseResources UP-TO-DATE
[14:46:57]: ▸ :react-native-vector-icons:bundleRelease UP-TO-DATE
[14:46:57]: ▸ :app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareComFacebookFrescoFresco081Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareComFacebookReactReactNative0222Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
[14:46:57]: ▸ :app:prepareTonyReactNativeVectorIconsUnspecifiedLibrary UP-TO-DATE
[14:46:57]: ▸ :app:prepareReleaseDependencies
[14:46:57]: ▸ :app:compileReleaseAidl UP-TO-DATE
[14:46:57]: ▸ :app:compileReleaseRenderscript UP-TO-DATE
[14:46:57]: ▸ :app:generateReleaseBuildConfig UP-TO-DATE
[14:46:57]: ▸ :app:generateReleaseAssets UP-TO-DATE
[14:46:57]: ▸ :app:mergeReleaseAssets UP-TO-DATE
[14:46:57]: ▸ :app:generateReleaseResValues UP-TO-DATE
[14:46:57]: ▸ :app:generateReleaseResources UP-TO-DATE
[14:46:58]: ▸ :app:mergeReleaseResources
[14:47:04]: ▸ :app:bundleReleaseJsAndAssets
[14:47:04]: ▸ bundle: Created ReactPackager
[14:47:14]: ▸ bundle: start
[14:47:14]: ▸ [14:47:14] <START> Whole Program Optimisations
[14:47:41]: ▸ [14:47:41] <END>   Whole Program Optimisations (26146ms)
[14:47:41]: ▸ [14:47:41] <START> minify
[14:47:54]: ▸ [14:47:54] <END>   minify (13722ms)
[14:47:54]: ▸ bundle: finish
[14:47:54]: ▸ bundle: Writing bundle output to: /Users/matteo/dev/tony-app-react/android/app/build/intermediates/assets/release/index.android.bundle
[14:47:54]: ▸ bundle: Closing client
[14:47:54]: ▸ bundle: Copying 7 asset files
[14:47:54]: ▸ bundle: Done writing bundle output
[14:47:54]: ▸ bundle: Done copying assets
[14:47:55]: ▸ :app:processReleaseManifest UP-TO-DATE
[14:47:55]: ▸ :app:processReleaseResourcesUnknown source file : warning: string 'catalyst_debugjs' has no default translation.
[14:47:55]: ▸ Unknown source file : warning: string 'catalyst_element_inspector' has no default translation.
[14:47:55]: ▸ Unknown source file : warning: string 'catalyst_jsload_error' has no default translation.
[14:47:55]: ▸ Unknown source file : warning: string 'catalyst_jsload_message' has no default translation.
[14:47:55]: ▸ Unknown source file : warning: string 'catalyst_jsload_title' has no default translation.
[14:47:55]: ▸ Unknown source file : warning: string 'catalyst_reloadjs' has no default translation.
[14:47:55]: ▸ Unknown source file : warning: string 'catalyst_settings' has no default translation.
[14:47:55]: ▸ Unknown source file : warning: string 'catalyst_settings_title' has no default translation.
[14:47:55]: ▸ :app:generateReleaseSources
[14:47:55]: ▸ :app:processReleaseJavaRes UP-TO-DATE
[14:47:55]: ▸ :app:compileReleaseJavaWithJavac UP-TO-DATE
[14:47:55]: ▸ :app:compileReleaseNdk UP-TO-DATE
[14:47:55]: ▸ :app:compileReleaseSources UP-TO-DATE
[14:47:56]: ▸ :app:lintVitalRelease
[14:47:56]: ▸ :app:preDexRelease UP-TO-DATE
[14:47:56]: ▸ :app:dexRelease UP-TO-DATE
[14:47:56]: ▸ :app:validateReleaseSigning
[14:47:59]: ▸ :app:packageRelease
[14:47:59]: ▸ :app:zipalignRelease
[14:47:59]: ▸ :app:assembleRelease
[14:47:59]: ▸ :react-native-vector-icons:compileReleaseSources UP-TO-DATE
[14:47:59]: ▸ :react-native-vector-icons:assembleRelease UP-TO-DATE
[14:47:59]: ▸ BUILD SUCCESSFUL
[14:47:59]: ▸ Total time: 1 mins 3.73 secs
[14:48:00]: --------------------
[14:48:00]: --- Step: supply ---
[14:48:00]: --------------------

+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                   Summary for supply 0.7.0                                                                                   |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| track                   | alpha                                                                                                                                                              |
| apk                     | android/app/build/outputs/apk/app-release.apk                                                                                                                      |
| apk_paths               | ["/Users/matteo/dev/tony-app-react/android/app/build/outputs/apk/app-debug.apk", "/Users/matteo/dev/tony-app-react/android/app/build/outputs/apk/app-release.apk"] |
| package_name            | it.myapp.myapp                                                                                                                                                 |
| rollout                 | 1.0                                                                                                                                                                |
| metadata_path           | ./fastlane/metadata/android                                                                                                                                        |
| json_key                | ./google-play-api-secret.json                                                                                                                                      |
| skip_upload_apk         | false                                                                                                                                                              |
| skip_upload_metadata    | false                                                                                                                                                              |
| skip_upload_images      | false                                                                                                                                                              |
| skip_upload_screenshots | false                                                                                                                                                              |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+

[14:48:04]: Preparing to upload for language 'it-IT'...
[14:48:06]: Uploading image file ./fastlane/metadata/android/it-IT/images/icon.png...
[14:48:07]: Updating changelog for code version '3' and language 'it-IT'...
[14:48:08]: Updating changelog for code version '4' and language 'it-IT'...
[14:48:08]: Preparing apk at path '/Users/matteo/dev/tony-app-react/android/app/build/outputs/apk/app-debug.apk' for upload...
[14:48:18]: Variable Dump:
[14:48:18]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:android, :LANE_NAME=>"android alpha", :GRADLE_BUILD_TYPE=>"Release", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/Users/matteo/dev/tony-app-react/android/app/build/outputs/apk/app-debug.apk", "/Users/matteo/dev/tony-app-react/android/app/build/outputs/apk/app-release.apk"], :GRADLE_APK_OUTPUT_PATH=>"/Users/matteo/dev/tony-app-react/android/app/build/outputs/apk/app-release.apk"}
[14:48:18]: apkUpgradeVersionConflict: APK specifies a version code that has already been used.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gradle                              | 64          |
| 4    | supply                              | 18          |
+------+-------------------------------------+-------------+

[14:48:18]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/lib/google/apis/core/http_command.rb:211:in `check_status': [!] apkUpgradeVersionConflict: APK specifies a version code that has already been used. (Google::Apis::ClientError)
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/lib/google/apis/core/api_command.rb:102:in `check_status'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/lib/google/apis/core/http_command.rb:179:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/lib/google/apis/core/upload.rb:198:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/lib/google/apis/core/upload.rb:275:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/lib/google/apis/core/base_service.rb:345:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.4/generated/google/apis/androidpublisher_v2/service.rb:660:in `upload_apk'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/client.rb:188:in `upload_apk'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:126:in `upload_binary_data'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:107:in `block in upload_binaries'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:106:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:106:in `upload_binaries'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:26:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/supply.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:177:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:162:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:109:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:32:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.86.1"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    sigh
    increment_build_number(xcodeproj: './ios/Tony.xcodeproj')
    gym(scheme: "Tony", project: './ios/Tony.xcodeproj')
    pilot(skip_submission: true)
  end

  after_all do |lane|
    slack(channel: "deploys", message: "Successfully deployed new Tony-iOS beta update.")
  end
end

platform :android do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Submit a new Alpha Build to Play Store"
  lane :alpha do
    gradle(task: "assemble", build_type: "Release", project_dir: "android/")
    supply(track: "alpha", apk: "android/app/build/outputs/apk/app-release.apk")
  end

  after_all do |lane|
    slack(channel: "deploys", message: "Successfully deployed new Tony-Android beta update.")
  end
end
```

### Environment

fastlane version (run `fastlane -v`): *1.89.0*

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? *No*

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? *No*

**Comment by asfalcone** [comment]
@mmazzarolo Thanks for the report. I'm surprised that `apk_paths` is not empty since I see that you're only running `assembleRelease` via gradle. Can you try adding a `gradle(task: 'clean')` before the assemble?

**Comment by mmazzarolo** [comment]
Sure! I'll give it a try tomorrow.

**Comment by mmazzarolo** [comment]
Hey @asfalcone, cleaning the project before assembling it worked, thank you and thanks for this awesome tool! 🌻 

```ruby
desc "Submit a new Alpha Build to Play Store"
lane :alpha do
  gradle(task: 'clean', project_dir: "android/") # <- Fixes it
  gradle(task: "assemble", build_type: "Release", project_dir: "android/")
  supply(track: "alpha", apk: "android/app/build/outputs/apk/app-release.apk")
end
```

**Comment by asfalcone** [comment]
@mmazzarolo So glad you're up and running! 👍

**Comment by colinyip** [comment]
same happened to me, i know it could be fixed with gradle clean, or setting apk_paths to ["RELEASE_APK_PATH"] instead of apk. But the sounds like more of a problem about the "apk_paths" setting. Shouldn't the default value be empty when apk is specified already? 😃

**Comment by TKBurner** [comment]
@colinyip Interesting suggestion. Right now we are going to stick with it the way it is as to not break others setups.
