### ISSUE TITLE
Build Artifacts into one location.

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#4676]
It would be great if all build artifcats from Fastlane like the IPA, DSYMs and Screenshots preview were put in one folder that I can simply add to a *.gitignore file.

**Comment by KrauseFx** [comment]
This is not something that can be changed easily now, since other systems might depend on it. Check out the `setup_jenkins` action, that pretty much does that. Is that useful for you?

**Comment by KrauseFx** [comment]
This is not something that can be changed easily now, since other systems might depend on it. Check out the `setup_jenkins` action, that pretty much does that. Is that useful for you?

**Comment by jcampbell05** [comment]
@KrauseFx That looks promising but not a fan of putting it all in one output folder in the middle of my computer. The reset git action helps me by removing the output files after fastlane is finished.

But perhaps in the future we could create a optional way of setting the outputs of all artifacts (If you ignore it then it will default to the default location per action)? I know it won't be overnight but it would be useful :)

**Comment by TKBurner** [comment]
@jcampbell05 Thanks for following up. I marked this as a feature request so we can see if anyone else is interested. We'll keep tracking on this thread. 👍

**Comment by SirobChilokin** [comment]
I am very much interested in this since we are making backups for all our builds. This would me very useful to my team. Fastlane rocks!

**Comment by jcampbell05** [comment]
this is a feature request :) so you shouldn't be closing it fastlane-bot

**Comment by jcampbell05** [comment]
Still not fixed 😀

**Comment by jcampbell05** [comment]
bump

**Comment by KrauseFx** [comment]
I actually like the idea, too bad we can't change the default behavior. What I'd suggest, we can have a new action called 
```ruby
set_fastlane_output_dir(path: "./fastlane/output")
```
at the top of the `Fastfile`, to set the output path for all other _fastlane_ action that generate and store a file. 

Is that something you'd be interested in working on?

**Comment by jcampbell05** [comment]
Sure do you know which vars I need to set?

**Comment by KrauseFx** [comment]
I think this is a pretty good list already: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/setup_jenkins.rb#L4-L18

Some things are not applicable, like the code signing identity.

**Comment by jcampbell05** [comment]
:) bump, must create tool for this

**Comment by denvercoder** [comment]
I wouldn’t mind taking a crack at this. Jcampbell05, have you started working on it?

**Comment by jcampbell05** [comment]
@denvercoder not at the moment :) go ahead.

**Comment by denvercoder** [comment]
I think I have the file done, although I am pretty ignorant about the project. It could be that I am way off. Plus I don't know ruby very well. But I am going to test this and I will post here if I need any assistance. ;)

**Comment by denvercoder** [comment]
@KrauseFx  Hi Felix, I have this done and I'm running the tests and there are tests failing that don't have anything to do with what I did. Should the test run be completely devoid of errors or are there a few tests that are known to not be passing?

**Comment by denvercoder** [comment]
Here are the tests that are failing
```
Failed examples:

rspec ./fastlane/spec/actions_specs/delete_keychain_spec.rb:8 # Fastlane Fastlane::FastFile Delete keychain Integration works with keychain name found locally
rspec ./fastlane/spec/actions_specs/delete_keychain_spec.rb:51 # Fastlane Fastlane::FastFile Delete keychain Integration works with keychain name that contain spaces and `"`
rspec ./fastlane/spec/actions_specs/zip_spec.rb:11 # Fastlane Fastlane::FastFile zip generates a valid zip command
rspec ./fastlane/spec/actions_specs/zip_spec.rb:19 # Fastlane Fastlane::FastFile zip generates a valid zip command without verbose output
rspec ./fastlane/spec/plugins_specs/plugin_generator_spec.rb:288 # Fastlane::PluginGenerator#generate All tests and style validation of the new plugin are passing rubocop validations are passing
rspec ./fastlane/spec/plugins_specs/plugin_generator_spec.rb:294 # Fastlane::PluginGenerator#generate All tests and style validation of the new plugin are passing `rake` runs both rspec and rubocop

rake aborted!
Command failed with status (1): [rspec --pattern ./**/*_spec.rb --format pr...]
/Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/Rakefile:19:in `block in <top (required)>'
/Users/dev/.rvm/gems/ruby-2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/dev/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/dev/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test_all
(See full trace by running task with --trace)

	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `sh_control_output'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/helper/sh_helper.rb:14:in `sh_no_action'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/fast_file.rb:177:in `block in sh'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/fast_file.rb:176:in `sh'
	from Fastfile:290:in `block (2 levels) in parsing_binding'
	from Fastfile:283:in `chdir'
	from Fastfile:283:in `block in parsing_binding'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:5:in `block in parsing_binding'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/dev/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/dev/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/dev/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/dev/Library/Mobile Documents/com~apple~CloudDocs/Projects/fastlane/bin/fastlane:20:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/dev/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/dev/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dev/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by KrauseFx** [comment]
Uh, I don't know where those failures are coming from, but I wouldn't worry about them. You can submit a PR, and Circle will automatically run the tests for you 👍  Thanks for working on this action

**Comment by jcampbell05** [comment]
:) @KrauseFx @denvercoder For future actions do you think there could be a new env variable we use and encourage actions to use for this action :)

**Comment by KrauseFx** [comment]
Yeah, absolutely. I think the action should be

```ruby
set_fastlane_output_dir(path: "./fastlane/output")
```

which under the hood sets an environment variable `FASTLANE_OUTPUT_DIRECTORY` that's being used as default for many of the output variables, including gym, etc.

**Comment by jcampbell05** [comment]
Any progress on this @denvercoder  ?

**Comment by janpio** [comment]
A bit late to the party, but:
`copy_artifacts` can be used to achieve this "manually" (with some configuration): https://docs.fastlane.tools/actions/copy_artifacts/

To copy the .ipa created by `gym` you can for example do this:
```
artifacts = []
artifacts << lane_context[SharedValues::IPA_OUTPUT_PATH] if lane_context[SharedValues::IPA_OUTPUT_PATH]
copy_artifacts(
   artifacts: artifacts
)
```

I haven't tried if this also works for other files like screenshots. Let us know if you do.

**Comment by jcampbell05** [comment]
@janpio  awesome,  :) may be a useful action to ship in the default template.
