### ISSUE TITLE
Windows + supply

### ISSUE THREAD

**Issue by Vetryanuj** [fastlane/fastlane#4711]
Hi guys. I want to use supply in my local machine with windows.
Supply init and gem installed. But when I want use `supply --help` or `supply init` I get erorors like  

```
D:\IWaiter\fastlane-master\fastlane-master\supply>gem install supply
Successfully installed supply-0.7.0
Parsing documentation for supply-0.7.0
Done installing documentation for supply after 1 seconds
1 gem installed
D:\fastlane-master\supply>supply --help
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
: cannot load such file -- pty (LoadError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fas
tlane_core/itunes_transporter.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fas
tlane_core.rb:15:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/opti
ons.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply.rb:3
:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/supply-0.7.0/bin/supply:4:in
 `<top (required)>'
        from C:/Ruby23-x64/bin/supply:23:in `load'
        from C:/Ruby23-x64/bin/supply:23:in `<main>'
```

So, I have any way to use Supply with windows?

**Comment by vpolouchkine** [comment]
As of now, `supply` is not supported on Windows.

**Comment by rspl17** [comment]
@vpolouchkine can you tell me what is supported on windows as I am not able to use it on windows 10

**Comment by TKBurner** [comment]
@rspl17 Currently neither of our Android tools are supported on Windows. Thanks for your interest!
