### ISSUE TITLE
`jira` action verifies wrong gem

### ISSUE THREAD

**Issue by SiarheiFedartsou** [fastlane/fastlane#4718]
Hi! I have a problem with `jira` action. I've installed `jira` gem and I have a crash during jira action work:
```/Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/lib/jira/cli.rb:28: warning: else without rescue is useless
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': /Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/lib/jira/cli.rb:24: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
/Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/lib/jira/cli.rb:65: syntax error, unexpected keyword_end, expecting end-of-input
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/lib/jira.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/bin/jira:6:in `<top (required)>'
	from /usr/local/bin/jira:23:in `load'
	from /usr/local/bin/jira:23:in `<main>'```

Lane code(most totally the same as in example) is:
```ruby
jira(
  url: "XXX",
  username: "XXX",
  password: "XXX",
  ticket_id: "XXX-NNN",
  comment_text: "Text to post as a comment"
)
```
It seems that currently `jira` action verifies wrong gem to be installed('jira', that obsolete), but should verify and use new 'jira-ruby' gem.

**Comment by TKBurner** [comment]
@SiarheiFedartsou We'll work with you on the PR for this. Thanks for finding this and for working with us! Hope you have a great day 👍
