### ISSUE TITLE
Scan "Couldn't parse the number of tests from the output"

### ISSUE THREAD

**Issue by andybest** [fastlane/fastlane#4736]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running fastlane on Jenkins, the build was failing with the following messages

```
...
Executed 47 tests, with 3 failures (3 unexpected) in 0.881 (0.938) seconds

** TEST FAILED **
[14:24:07]: Exit status: 65
[14:24:09]: Couldn't parse the number of tests from the output
[14:24:09]: Variable Dump:
[14:24:09]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[14:24:09]: undefined method `>' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 7           |
| 4    | scan                                | 47          |
+------+-------------------------------------+-------------+

[14:24:09]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/scan-0.6.1/lib/scan/runner.rb:61:in `handle_results': [!] undefined method `>' for nil:NilClass (NoMethodError)
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/scan-0.6.1/lib/scan/runner.rb:9:in `run'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/scan-0.6.1/lib/scan/manager.rb:10:in `work'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/actions/scan.rb:10:in `run'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/runner.rb:177:in `block (2 levels) in execute_action'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/runner.rb:162:in `block in execute_action'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `chdir'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `execute_action'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/runner.rb:109:in `trigger_action_by_name'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:19:in `block (2 levels) in parsing_binding'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/gems/fastlane-1.89.0/bin/fastlane:5:in `<top (required)>'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/bin/fastlane:23:in `load'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/bin/fastlane:23:in `<main>'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/bin/ruby_executable_hooks:15:in `eval'
	from /Users/administrator/.rvm/gems/ruby-2.0.0-p645/bin/ruby_executable_hooks:15:in `<main>'
```

It turns out that the JUnit test report was being generated with an extra property:

``` <testsuites name='MyProject.xctest' tests='49' failures='3'> ```

This may be to do with the fact that I am using the latest XCPretty (I fixed an issue that prevents the HTML output from rendering correctly [in this pull request](https://github.com/supermarin/xcpretty/pull/224) ).

I have submitted a pull request that implements a more robust regular expression for grabbing the number of tests from the JUnit output file. #4735 

### Environment

Fastlane 1.89.0

**Comment by vpolouchkine** [comment]
Thanks for the report and the PR.

**Comment by andybest** [comment]
Pull request was merged, so I'm going to close
