### ISSUE TITLE
Update documentation - initial call to `match development`

### ISSUE THREAD

**Issue by jlerner** [fastlane/fastlane#4741]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

If non-existent `git_branch` not specified, initial `match development` errors out mysteriously. 
```
undefined method `shellescape' for nil:NilClass (NoMethodError)
```
##### Complete output when running fastlane, including the stack trace and command used

```
$ match --verbose development

+-----------------------+-----------------------------------------------+
|                        Summary for match 0.6.0                        |
+-----------------------+-----------------------------------------------+
| verbose               | development                                   |
| git_url               | https://github.com/XYZ/certificates |
| type                  | development                                   |
| app_identifier        | x.y.z                         |
| username              | xyz@gmail.com                       |
| git_branch            | master                                        |
| keychain_name         | login.keychain                                |
| readonly              | false                                         |
| team_id               | 687E3VCFBS                                    |
| force                 | false                                         |
| shallow_clone         | false                                         |
| force_for_new_devices | false                                         |
| skip_docs             | false                                         |
+-----------------------+-----------------------------------------------+

INFO [2016-05-19 13:18:47.34]: Cloning remote git repo...
INFO [2016-05-19 13:18:47.34]: $ git clone 'https://github.com/XYZ/certificates' '/var/folders/wy/b89x2zc93msg7whr4r8ny2m00000gn/T/d20160519-1981-bw9b71'
INFO [2016-05-19 13:18:47.34]: ▸ Cloning into '/var/folders/wy/b89x2zc93msg7whr4r8ny2m00000gn/T/d20160519-1981-bw9b71'...
INFO [2016-05-19 13:18:47.77]: ▸ remote: Counting objects: 3, done.
INFO [2016-05-19 13:18:47.77]: ▸ remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
INFO [2016-05-19 13:18:47.77]: ▸ Unpacking objects: 100% (3/3), done.
INFO [2016-05-19 13:18:47.78]: ▸ Checking connectivity... done.
WARN [2016-05-19 13:18:47.78]: Migrating to new match...
INFO [2016-05-19 13:18:47.81]: 🔒  Successfully encrypted certificates repo
INFO [2016-05-19 13:18:47.81]: Cloning remote git repo...
INFO [2016-05-19 13:18:47.81]: $ git clone 'https://github.com/XYZ/certificates' '/var/folders/wy/b89x2zc93msg7whr4r8ny2m00000gn/T/d20160519-1981-1i367rl'
INFO [2016-05-19 13:18:47.82]: ▸ Cloning into '/var/folders/wy/b89x2zc93msg7whr4r8ny2m00000gn/T/d20160519-1981-1i367rl'...
INFO [2016-05-19 13:18:48.23]: ▸ remote: Counting objects: 3, done.
INFO [2016-05-19 13:18:48.23]: ▸ remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
INFO [2016-05-19 13:18:48.23]: ▸ Unpacking objects: 100% (3/3), done.
INFO [2016-05-19 13:18:48.24]: ▸ Checking connectivity... done.
INFO [2016-05-19 13:18:48.24]: 🔒  Successfully encrypted certificates repo
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '520767982783db9f8d314998ff9ee92a'
The crash report has been stored locally '/tmp/sentry_520767982783db9f8d314998ff9ee92a.json'
/Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:115:in `block in branch_exists?': [!] undefined method `shellescape' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:114:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:114:in `branch_exists?'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:89:in `checkout_branch'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:17:in `clone'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/change_password.rb:7:in `update'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:21:in `clone'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/commands_generator.rb:121:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/bin/match:6:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'
```

### Configuration Files

Fixed by adding `git_branch "team-xyz"` to `fastlane/Matchfile`.

### Environment

```
fastlane 1.89.0
match 0.6.0
```
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by KrauseFx** [comment]
Looking into this now, thanks 👍

**Comment by KrauseFx** [comment]
It seems like it crashes on changing the password `change_password.rb:7`, did you want to do that? 
```
    from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:17:in `clone'
    from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/change_password.rb:7:in `update'
    from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:21:in `clone'
```
I'll definitely work on a fix for this though, just curios on how I can reproduce this issue

**Comment by jlerner** [comment]
Hm - I wasn't trying to change a password.

**Comment by 5amfung** [comment]
I had the same issue when I ran `match nude development`.  I created a new git repo, ran `match init`, changed the username and app_identifier in Matchfile.

```
$ match nuke development
[15:22:48]: Cloning remote git repo...
[15:22:50]: Migrating to new match...
[15:22:50]: 🔒  Successfully encrypted certificates repo
[15:22:50]: Cloning remote git repo...
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:115:in `block in branch_exists?': [!] undefined method `shellescape' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:114:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:114:in `branch_exists?'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:89:in `checkout_branch'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:17:in `clone'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/change_password.rb:7:in `update'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:21:in `clone'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/nuke.rb:14:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/commands_generator.rb:114:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/commands_generator.rb:121:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/bin/match:6:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'

```
