### ISSUE TITLE
supply init returns that client_email is missing.

### ISSUE THREAD

**Issue by sylvek** [fastlane/fastlane#4751]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
> $ supply init                                                                                                          [±feature-2.3.x ●]
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:76:in `read_json_key': [!] missing client_email (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:59:in `make_creds'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/client.rb:53:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/client.rb:29:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/client.rb:29:in `make_from_config'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/setup.rb:99:in `client'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/setup.rb:9:in `perform_download'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
	from /usr/local/bin/supply:23:in `load'
	from /usr/local/bin/supply:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.89.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```

### Environment

fastlane version (run `fastlane -v`): 1.89.0

supply version: 0.7.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by sylvek** [comment]
my bad, i didn't create a correct json file!.
