### ISSUE TITLE
Error parsing Framefile.json

### ISSUE THREAD

**Issue by lorensr** [fastlane/fastlane#4772]
What's wrong with my Framefile? Adding a spec to the README would help. Currently only has an example:

https://github.com/fastlane/fastlane/tree/master/frameit#framefilejson

Thanks!

##### Complete output when running fastlane, including the stack trace and command used

```
$  frameit silver --verbose
DEBUG [2016-05-22 00:28:37.20]: Looking for iPhone-6s-Silver-vertical and found 2
DEBUG [2016-05-22 00:28:37.20]: Looking for iPhone-6s-Silver-vertical and found 2
INFO [2016-05-22 00:28:37.20]: Parsing config file '/Users/me/extra_parlay/fastlane/screenshots/Framefile.json'
ERROR [2016-05-22 00:28:37.20]: no implicit conversion of String into Integer
ERROR [2016-05-22 00:28:37.20]: Backtrace:
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/config_parser.rb:25:in `[]'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/config_parser.rb:25:in `block in fetch_value'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/config_parser.rb:25:in `each'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/config_parser.rb:25:in `find'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/config_parser.rb:25:in `fetch_value'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/editor.rb:267:in `fetch_config'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/editor.rb:83:in `should_add_title?'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/editor.rb:16:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/screenshot.rb:76:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/runner.rb:34:in `block in run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/runner.rb:26:in `each'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/lib/frameit/runner.rb:26:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/bin/frameit:42:in `block (2 levels) in run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/bin/frameit:57:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.6.2/bin/frameit:72:in `<top (required)>'
	/usr/local/bin/frameit:23:in `load'
	/usr/local/bin/frameit:23:in `<main>'
```

### Configuration Files

`Framefile.json`:
```json
{
  "default": {
    "title": {
      "color": "#545454",
      "fonts": [
        {
          "font": "./HelvFB.otf",
          "supported": ["en-US"]
        }
      ]
    },
    "background": "./background.jpg",
    "padding": 50
  },

  "data": {
    "filter": "new"
  }
}
```

Files:
```
Framefile.json
HelvFB.otf
background.jpg

en-US
  iPhone6_new.png
  title.strings
```

### Environment

fastlane version (run `fastlane -v`):
frameit 2.6.2

**Comment by lorensr** [comment]
Fixed by making `data` into an array with one object, but more documentation would be nice ☺️

**Comment by vpolouchkine** [comment]
Glad you're up and running! I'll make a note to update the docs. Feel free to submit a PR as well. :)
