### ISSUE TITLE
Trying to upload to Testflight Beta and getting permission denied error...

### ISSUE THREAD

**Issue by mmlittle** [fastlane/fastlane#482]
Hi,

So first off I'm new to Fastlane, so pardon stupid stuff.

I'm trying to push to TestFlight with "fastlane ios beta",  The app builds ok but fails when connecting to iTunes Connect.  I did this successfully with another app yesterday, so I'm just looking for help narrowing down the possible problems.  And yes, I did the DELIVER_USER and DELIVER_PASSWORD environment variables.  Thx  

[13:14:46]: ---------------------
[13:14:46]: --- Step: deliver ---
[13:14:46]: ---------------------
[13:14:47]: Got all information needed to deploy a new update ('[[APP_VERSION]]') for app '[[APP_IDENTIFIER]]'
[13:14:47]: Beta builds don't upload new metadata to iTunesConnect
[13:14:47]: Uploading ipa file to iTunesConnect
[13:14:47]: Variable Dump:
[13:14:47]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/tuple/Documents/iOSDev/BaconTest/BaconTest.ipa", :DSYM_OUTPUT_PATH=>"/Users/tuple/Documents/iOSDev/BaconTest/BaconTest.app.dSYM.zip"}
[13:14:47]: Permission denied - /tmp//0.itmsp//metadata.xml

**Comment by KrauseFx** [comment]
Could you please share your `Appfile`, `Fastfile` and let me know how you set the environment variables?

**Comment by mmlittle** [comment]
app_identifier "cx.xxxxxxx.Bxxxx" # The bundle identifier of your app
apple_id "gxxxx@wxxxxxxxxxe.com" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
team_name “xxxxxxx xxxx, LLC”
team_id "4xxxxxxxxH"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#the-appfile

**Comment by mmlittle** [comment]
<img width="640" alt="fas" src="https://cloud.githubusercontent.com/assets/2903463/9142899/5bd055ca-3d08-11e5-8991-ca6a21df6b65.png">

**Comment by mmlittle** [comment]
I set my environment variables by adding these two lines to my ~/.bash_profile.  And yes, I did restart the terminal window.

export DELIVER_USER=xxx@xxxxxxxxxx.com
export DELIVER_PASSWORD="xxxxxxx xxxxxxxxxx xxxx xxxxx!"

**Comment by mmlittle** [comment]
Here's the tail of the log.

[13:49:22]: Permission denied - /tmp//0.itmsp//metadata.xml

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ipa                                 | 9           |
| 4    | deliver                             | 0           |
+------+-------------------------------------+-------------+

[13:49:22]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/ipa_uploader.rb:63:in `write': Permission denied - /tmp//0.itmsp//metadata.xml (Errno::EACCES)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/ipa_uploader.rb:63:in `upload!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliver_process.rb:386:in `trigger_ipa_upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliver_process.rb:48:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:135:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:87:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:87:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/deliver.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/deliver.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):48:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/lane.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/lane.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by KrauseFx** [comment]
This is the same issue as https://github.com/KrauseFx/sigh/issues/147#issuecomment-126211994

You have to change the `"`, let me know if you need help doing that :+1:

**Comment by mmlittle** [comment]
Thanks, I got that one fixed but still having this issue.

<img width="1290" alt="log" src="https://cloud.githubusercontent.com/assets/2903463/9145571/10e091d4-3d1b-11e5-9ff3-00f7bcab7161.png">

**Comment by KrauseFx** [comment]
I'm confused, where does the `[[APP_VERSION]]` and `[[APP_IDENTIFIER]]` come from?

**Comment by mmlittle** [comment]
Um.. Dunno, I didn't write this.

I'm still getting this - any idea?

THx

Retina:BTS mike$ fastlane ios beta
[01:59:51]: -------------------------------------------------
[01:59:51]: --- Step: Verifying required fastlane version ---
[01:59:51]: -------------------------------------------------
[01:59:51]: fastlane version valid
[01:59:51]: ------------------------------
[01:59:51]: --- Step: default_platform ---
[01:59:51]: ------------------------------
[01:59:51]: Driving the lane 'ios beta' 🚀
[01:59:51]: -----------------
[01:59:51]: --- Step: ipa ---
[01:59:51]: -----------------
[01:59:51]: You haven't specified a scheme. This might cause problems. If you can't see any output, please pass a `scheme`
[01:59:51]: set -o pipefail && krausefx-ipa build  --verbose | xcpretty
[01:59:51]: [SHELL COMMAND]: set -o pipefail && krausefx-ipa build  --verbose | xcpretty
[01:59:54]: [SHELL]: ▸ Cleaning BradleyTest/BradleyTest [Release]
[01:59:54]: [SHELL]: ▸ Building BradleyTest/BradleyTest [Release]
[01:59:54]: [SHELL]: ▸ Compiling AppDelegate.m
[01:59:54]: [SHELL]: ▸ Compiling ViewController.m
[01:59:54]: [SHELL]: ▸ Compiling main.m
[01:59:54]: [SHELL]: ▸ Compiling ViewController.m
[01:59:54]: [SHELL]: ▸ Compiling AppDelegate.m
[01:59:54]: [SHELL]: ▸ Compiling main.m
[01:59:54]: [SHELL]: ▸ Linking BradleyTest
[01:59:54]: [SHELL]: ▸ Linking BradleyTest
[01:59:55]: [SHELL]: ▸ Processing Info.plist
[01:59:55]: [SHELL]: ▸ Generating 'BradleyTest.app.dSYM'
[01:59:55]: [SHELL]: ▸ Touching BradleyTest.app
[01:59:55]: [SHELL]: ▸ Signing /Users/mike/Library/Developer/Xcode/DerivedData/BradleyTest-fwztyueiffccapffdqneeihlfxrn/Build/Products/Release-iphoneos/BradleyTest.app
[01:59:55]: [SHELL]: ▸ Building BradleyTest/BradleyTest [Release]
[01:59:55]: [SHELL]: ▸ Compiling ViewController.m
[01:59:55]: [SHELL]: ▸ Compiling AppDelegate.m
[01:59:55]: [SHELL]: ▸ Compiling main.m
[01:59:55]: [SHELL]: ▸ Compiling ViewController.m
[01:59:55]: [SHELL]: ▸ Compiling AppDelegate.m
[01:59:55]: [SHELL]: ▸ Compiling main.m
[01:59:55]: [SHELL]: ▸ Linking BradleyTest
[01:59:55]: [SHELL]: ▸ Linking BradleyTest
[01:59:55]: [SHELL]: ▸ Processing Info.plist
[01:59:55]: [SHELL]: ▸ Generating 'BradleyTest.app.dSYM'
[01:59:55]: [SHELL]: ▸ Touching BradleyTest.app
[01:59:55]: [SHELL]: ▸ Signing /Users/mike/Library/Developer/Xcode/DerivedData/BradleyTest-fwztyueiffccapffdqneeihlfxrn/Build/Intermediates/ArchiveIntermediates/BradleyTest/InstallationBuildProductsLocation/Applications/BradleyTest.app
[01:59:56]: [SHELL]: ▸ Touching BradleyTest.app.dSYM
[01:59:57]: ------------------
[01:59:57]: --- Step: sigh ---
[01:59:57]: ------------------
[01:59:57]: Starting login
[01:59:58]: Successfully logged in
[01:59:58]: Fetching profiles...
[02:00:02]: Found 1 matching profile(s)
[02:00:02]: Downloading provisioning profile...
[02:00:03]: Successfully downloaded provisioning profile...
[02:00:03]: Installing provisioning profile...
[02:00:03]: Provisioning profile of app 'BradleyTest' with the name 'ProdBradleyTestProfile' successfully analysed.
[02:00:03]: Profile successfully installed
./AppStore_com.wexxxxxxe.BradleyTest.mobileprovision
[02:00:03]: ---------------------
[02:00:03]: --- Step: deliver ---
[02:00:03]: ---------------------
[02:00:03]: Got all information needed to deploy a new update ('[[APP_VERSION]]') for app 'com.wexxxxxxe.BradleyTest'
[02:00:03]: Beta builds don't upload new metadata to iTunesConnect
[02:00:03]: Uploading ipa file to iTunesConnect
[02:00:03]: Going to upload updated app to iTunesConnect
[02:00:03]: This might take a few minutes, please don't interrupt the script
[02:00:06]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
[02:00:06]: [Transporter]: INFO: Logging configured successfully.
[02:00:06]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.applem/transporter/Defaults.properties
[02:00:07]: [Transporter]: DEBUG: Configuration refresh successful.
[02:00:07]: [Transporter]: DEBUG: Saving configuration to local path: /Users/mike/.itmstransporter/Defaults.properties
[02:00:07]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.8.5]
[02:00:07]: [Transporter]: INFO: OS identifier: Mac OS X 10.10.4 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[02:00:07]: [Transporter]: INFO: Memory: [JVM] 30M free, 56M total, 910M max [System] (Physical) 70M free, 16384M total (Swap) 1582M free, 4096M total
[02:00:07]: [Transporter]: INFO: Upload mode selected.
[02:00:07]: [Transporter]: INFO: Examining the package at: /tmp/45.itmsp
[02:00:07]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
[02:00:07]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
[02:00:07]: [Transporter]: INFO: Gathering the list of valid files from the package ...
[02:00:07]: [Transporter]: DEBUG:   38e69724e3c849f5b7779957247c0d9b.ipa will be verified by Apple's web service to determine if it is a valid file.
[02:00:07]: [Transporter]: DEBUG:   3f91643b29195ab53b90952495440c02.ipa will be verified by Apple's web service to determine if it is a valid file.
[02:00:07]: [Transporter]: DEBUG:   44ca3a5b70600e4c9a3ca420a5fc4223.ipa will be verified by Apple's web service to determine if it is a valid file.
[02:00:07]: [Transporter]: DEBUG:   5fc5d1ae322fb9162e7cf840181a8d3d.ipa will be verified by Apple's web service to determine if it is a valid file.
[02:00:07]: [Transporter]: DEBUG:   69cd0806f0d2687e86ac0f66b8dfec8d.ipa will be verified by Apple's web service to determine if it is a valid file.
[02:00:07]: [Transporter]: DEBUG:   df813496275ddd725fa5d42823190d07.ipa will be verified by Apple's web service to determine if it is a valid file.
[02:00:07]: [Transporter]: DEBUG:   e33dd7d2605cf82e1e9dad14bb5acafd.ipa will be verified by Apple's web service to determine if it is a valid file.
[02:00:07]: [Transporter]: DEBUG:   f45f8bc59b852f0e92ec34038c2801f5.ipa will be verified by Apple's web service to determine if it is a valid file.
[02:00:07]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
[02:00:07]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
[02:00:07]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
[02:00:07]: [Transporter]: INFO: Performing authentication of package 45.itmsp ...
[02:00:07]: [Transporter]: DBG-X: Memory: [JVM] 4M free, 56M total, 910M max [System] (Physical) 97M free, 16384M total (Swap) 1582M free, 4096M total
[02:00:07]: [Transporter]: DBG-X: Memory: [JVM] 4M free, 56M total, 910M max [System] (Physical) 97M free, 16384M total (Swap) 1582M free, 4096M total
[02:00:07]: [Transporter]: DBG-X: Using operation named: authenticateForSession
[02:00:07]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[02:00:07]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[02:00:07]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[02:00:07]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.4 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[02:00:07]: [Transporter]: DBG-X:   parameter Password = **hidden value**
[02:00:07]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u gxxx@wexxxxxxe.com -p **hidden value** -f /tmp//45.itmsp -t Signiant -k 100000
[02:00:07]: [Transporter]: DBG-X:   parameter Username = gxxx@wexxxxxxe.com
[02:00:07]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[02:00:07]: [Transporter]: INFO: id = 20150809020007-510
[02:00:08]: [Transporter]: DBG-X: Apple's web service operation return value:
[02:00:08]: [Transporter]: DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)
[02:00:08]: [Transporter]: DBG-X:   parameter Errors = [Your Apple ID or password was entered incorrectly. (-20101)]
[02:00:08]: [Transporter]: DBG-X:   parameter ErrorCode = -20101
[02:00:08]: [Transporter]: DBG-X:   parameter Success = false
[02:00:08]: [Transporter]: DBG-X: Deflated 422 bytes to 368
[02:00:08]: [Transporter]: DBG-X: Using operation named: validateMetadata
[02:00:08]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[02:00:08]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[02:00:08]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.3
[02:00:08]: [Transporter]: DBG-X:   parameter Files = [38e69724e3c849f5b7779957247c0d9b.ipa, 3f91643b29195ab53b90952495440c02.ipa, 44ca3a5b70600e4c9a3ca420a5fc4223.ipa, 5fc5d1ae322fb9162e7cf840181a8d3d.ipa, 69cd0806f0d2687e86ac0f66b8dfec8d.ipa, df813496275ddd725fa5d42823190d07.ipa, e33dd7d2605cf82e1e9dad14bb5acafd.ipa, f45f8bc59b852f0e92ec34038c2801f5.ipa, metadata.xml]
[02:00:08]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
[02:00:08]: [Transporter]: DBG-X:   parameter MetadataChecksum = c8f4c97584c57dcd000e9054e73fd858
[02:00:08]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
[02:00:08]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.10.4 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_01_13_21_57-b00
[02:00:08]: [Transporter]: DBG-X:   parameter PackageName = 45.itmsp
[02:00:08]: [Transporter]: DBG-X:   parameter PackageSize = 352941
[02:00:08]: [Transporter]: DBG-X:   parameter Password = **hidden value**
[02:00:08]: [Transporter]: DBG-X:   parameter Throttle = 100000
[02:00:08]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u gxxx@wexxxxxxe.com -p **hidden value** -f /tmp//45.itmsp -t Signiant -k 100000
[02:00:08]: [Transporter]: DBG-X:   parameter Username = gxxx@wexxxxxxe.com
[02:00:08]: [Transporter]: DBG-X:   parameter Version = 1.8.5
[02:00:08]: [Transporter]: INFO: id = 20150809020008-610
[02:00:08]: [Transporter]: DBG-X: Apple's web service operation return value:
[02:00:08]: [Transporter]: DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)
[02:00:08]: [Transporter]: DBG-X:   parameter Errors = [Your Apple ID or password was entered incorrectly. (-20101)]
[02:00:08]: [Transporter]: DBG-X:   parameter ErrorCode = -20101
[02:00:08]: [Transporter]: DBG-X:   parameter Success = false
[02:00:08]: [Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)
It seems like the username or password for the account 'gxxx@wexxxxxxe.com' is wrong.
Please open the Keychain app, switch to `Passwords` and search for `deliver.`
You can then either remove the outdated entry or directly update it.
[02:00:08]: [Transporter]: DBG-X: The error code is: -20101
[02:00:08]: Transporter transfer failed.
[02:00:08]: 
[02:00:08]: Your Apple ID or password was entered incorrectly. (-20101)
[02:00:08]: Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
[02:00:08]: Your Apple ID or password was entered incorrectly. (-20101)
Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
[02:00:08]: Variable Dump:
[02:00:08]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/mike/Documents/iOSDev/BradleyTest/BradleyTest.ipa", :DSYM_OUTPUT_PATH=>"/Users/mike/Documents/iOSDev/BradleyTest/BradleyTest.app.dSYM.zip", :SIGH_PROFILE_PATH=>"/Users/mike/Documents/iOSDev/BradleyTest/AppStore_com.wexxxxxxe.BradleyTest.mobileprovision", :SIGH_UDID=>"76f7f3c5-313e-4033-aa3f-6a2d88853702"}
[02:00:08]: Error uploading ipa file

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ipa                                 | 5           |
| 4    | sigh                                | 6           |
| 5    | deliver                             | 5           |
+------+-------------------------------------+-------------+

[02:00:08]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliver_process.rb:387:in `trigger_ipa_upload': Error uploading ipa file (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliver_process.rb:48:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:135:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:87:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/deliverer.rb:87:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/deliver.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/deliver.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):48:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/lane.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/lane.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.15.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by mmlittle** [comment]
When I try to just run deliver this is what I get.

Retina:BTS mike$ deliver testflight
Could not automatically find the app ID, please enter it here (e.g. 956814360):  45XXXXXXVH
[03:30:23]: Ready to upload new build to TestFlight (com.wexxxxxxe.BradleyTest - 45XXXXXXVH)
[03:30:23]: Uploading ipa file to iTunesConnect
[03:30:23]: Going to upload updated app to iTunesConnect
[03:30:23]: This might take a few minutes, please don't interrupt the script
[03:30:23]: Waiting for iTunes Connect transporter to be finished.
[03:30:23]: iTunes Transporter progress... this might take a few minutes...
[03:30:27]: [Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)
It seems like the username or password for the account 'god@wearetuple.co' is wrong.
Please open the Keychain app, switch to `Passwords` and search for `deliver.`
You can then either remove the outdated entry or directly update it.
[03:30:27]: Transporter transfer failed.
[03:30:27]: 
[03:30:27]: Your Apple ID or password was entered incorrectly. (-20101)
[03:30:27]: Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
[03:30:27]: Your Apple ID or password was entered incorrectly. (-20101)
Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
/Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/testflight.rb:24:in `upload!': Error distributing new beta version! (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/commands_generator.rb:110:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/commands_generator.rb:140:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/lib/deliver/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.13.0/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'

**Comment by JaviSoto** [comment]
Hi @mmlittle!

I'm going through some old issues to see if I can help with them. Is this one still an issue? Have you made any progress on this? Thanks!

**Comment by asfalcone** [comment]
Going to close this issue since it has been open for a few months without follow up.
