### ISSUE TITLE
'Supply' gem is expecting client email in downloaded Json and it's missing

### ISSUE THREAD

**Issue by LovesBruins** [fastlane/fastlane#4829]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I followed the instruction for using the android 'supply' gem.  I downloaded the Json from Google Play Developer Console and used that as my input file.  The following is the result:

##### Complete output when running fastlane, including the stack trace and command used
Lorens-MacBook-Pro:android-app lorenrogers$ ~/.gem/ruby/2.3.0/gems/supply-0.6.2/bin/supply init -j client_secret_448431207003-vmmnj8bm6ptv554c2q406b6s0o9t39hc.apps.googleusercontent.com.json 
/Users/lorenrogers/.gem/ruby/2.3.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:76:in `read_json_key': [!] missing client_email (RuntimeError)
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:59:in `make_creds'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/supply-0.6.2/lib/supply/client.rb:53:in `initialize'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/supply-0.6.2/lib/supply/client.rb:29:in `new'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/supply-0.6.2/lib/supply/client.rb:29:in `make_from_config'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/supply-0.6.2/lib/supply/setup.rb:99:in `client'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/supply-0.6.2/lib/supply/setup.rb:9:in `perform_download'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/supply-0.6.2/lib/supply/commands_generator.rb:51:in `block (2 levels) in run'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.44.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/supply-0.6.2/lib/supply/commands_generator.rb:57:in `run'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/supply-0.6.2/lib/supply/commands_generator.rb:15:in `start'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/supply-0.6.2/bin/supply:6:in `<main>'
Lorens-MacBook-Pro:android-app lorenrogers$ 

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by LovesBruins** [comment]
I double-checked the instructions for 'supply' and realize that I did one step improperly when generating the json.  I believe I downloaded the correct json, and now I'm getting the following problem with 'Unauthorized':

Lorens-MacBook-Pro:android-app lorenrogers$ supply init -j Google\ Play\ Android\ Developer-5c3c1653ef75.json 
[13:44:03]: To not be asked about this value, you can specify it using 'package_name'
The package name of the Application to modify: com.retrieve.retrieve_dev_2250
/Users/lorenrogers/.gem/ruby/2.3.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:208:in `check_status': [!] Unauthorized (Google::Apis::AuthorizationError)
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/google-api-client-0.9.6/lib/google/apis/core/api_command.rb:104:in `check_status'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:179:in `process_response'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:286:in `execute_once'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/google-api-client-0.9.6/lib/google/apis/core/base_service.rb:345:in `execute_or_queue_command'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/google-api-client-0.9.6/generated/google/apis/androidpublisher_v2/service.rb:209:in `insert_edit'
	from /usr/local/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/client.rb:81:in `begin_edit'
	from /usr/local/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/setup.rb:9:in `perform_download'
	from /usr/local/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:51:in `block (2 levels) in run'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.44.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/lorenrogers/.gem/ruby/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
	from /usr/local/bin/supply:23:in `load'
	from /usr/local/bin/supply:23:in `<main>'

**Comment by LovesBruins** [comment]
AAHHHH! I forgot the last step.  Closing this issue.  Everything works fine
