### ISSUE TITLE
Frameit fails on screenshots with apostrophes in the title

### ISSUE THREAD

**Issue by dwhitlow** [fastlane/fastlane#4851]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Frameit fails on screenshots with apostrophes in the title

##### Complete output when running fastlane, including the stack trace and command used

`frameit silver --verbose`:
```
DEBUG [2016-05-25 14:22:55.58]: Looking for iPhone-6s-Plus-Silver-vertical and found 1
DEBUG [2016-05-25 14:22:55.58]: Looking for iPhone-6s-Plus-Silver-vertical and found 1
DEBUG [2016-05-25 14:22:55.58]: Parsing config file '/Users/dwhitlow/workspace/ios-hired/fastlane/screenshots/Framefile.json'
DEBUG [2016-05-25 14:22:58.01]: Falling back to default text as there was nothing specified in the .strings file
DEBUG [2016-05-25 14:22:58.49]: Using /Users/dwhitlow/workspace/ios-hired/fastlane/screenshots/./Gotham-Medium.otf as font the title of ./fr-FR/iPhone6sPlus-04interviews.png
DEBUG [2016-05-25 14:22:58.49]: Adding text 'Consultez vos demandes d'entretien ouvertes\net agissez'
ERROR [2016-05-25 14:22:59.33]: `mogrify -font /Users/dwhitlow/workspace/ios-hired/fastlane/screenshots/./Gotham-Medium.otf -gravity Center -pointsize 107 -draw text 0,0 'Consultez vos demandes d'entretien ouvertes
et agissez' -fill  /var/folders/0q/37wvffr17yx6l9jr94s5p5vr0000gn/T/mini_magick20160525-18033-1nbwo87.png` failed with error:
mogrify: non-conforming drawing primitive definition `entretien' @ error/draw.c/DrawImage/3169.

ERROR [2016-05-25 14:22:59.33]: Backtrace:
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/shell.rb:18:in `run'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:92:in `call'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:40:in `new'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:504:in `mogrify'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:384:in `combine_options'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:244:in `block in build_title_images'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:226:in `each'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:226:in `build_title_images'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:165:in `put_title_into_background'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:102:in `complex_framing'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:17:in `frame!'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/screenshot.rb:76:in `frame!'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/runner.rb:34:in `block in run'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/runner.rb:26:in `each'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/runner.rb:26:in `run'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/commands_generator.rb:46:in `block (2 levels) in run'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.44.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/commands_generator.rb:61:in `run'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/commands_generator.rb:12:in `start'
  /Users/dwhitlow/workspace/fastlane/frameit/bin/frameit:7:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Framefile.json:
```
{
    "default": {
        "title": {
            "font": "./Gotham-Medium.otf"
        },
        "background": "./background.png",
        "padding": 50
    },
    "data": [
        {
            "filter": "list"
        },
        {
            "filter": "profile"
        },
        {
            "filter": "request_interview"
        },
        {
            "filter": "interviews"
        },
        {
            "filter": "conversation"
        }
    ]
}
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.91.0
frameit 2.6.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

**Comment by TKBurner** [comment]
@dwhitlow Awesome to see you submit a PR already! Can you add a test to the spec file so we can merge this faster? Thanks! 👍

**Comment by dwhitlow** [comment]
Sounds good, I'll add tests for unescaped and already-escaped single quotes.
