### ISSUE TITLE
screengrab appending weird characters in the beginning and at end of commands executed

### ISSUE THREAD

**Issue by kpuneet** [fastlane/fastlane#4879]
### New Issue Checklist

- [ Y] Updated fastlane to the latest version
- [Y ] I have read the [Contribution Guidelines] (https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Running ScreenGrab on Jenkins : While executing 'screengrab" command some weird characters are getting appended at both beginning and at the end of the all command executed by screengrab which is not letting the tool run, when i execute the same command over shell it is working fine

----------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------

##### Complete output when running fastlane, including the stack trace and command used

`````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
/usr/bin/env bash /var/folders/g8/m6nw30110094mk5nh8pj991c0000gn/T/hudson1344588153603882317.sh
+-----------------------------+--------------------------------------------------------------------+
|                                   [32mSummary for screengrab 0.3.2[0m                                   |
+-----------------------------+--------------------------------------------------------------------+
| app_apk_path                | /Users/BuildBot/Desktop/Android-Screenshot/app-devGoogle-debug.apk |
| tests_apk_path              | /Users/BuildBot/Desktop/Android-Screenshot/app-devGoogle-debug-... |
| output_directory            | /Users/BuildBot/Desktop/Android-Screenshot                         |
| app_package_name            | com.test.android                                         |
| android_home                | /Users/BuildBot/Library/Android/sdk                                |
| clear_previous_screenshots  | true                                                               |
| device_type                 | phone                                                              |
| tests_package_name          | com.test.android.test                                    |
| locales                     | ["en-US"]                                                          |
| skip_open_summary           | false                                                              |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner                     |
| ending_locale               | en-US                                                              |
+-----------------------------+--------------------------------------------------------------------+

[10:44:27]: [33mLimiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.[0m
[10:44:27]: [33mConsider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.[0m
[10:44:27]: Clearing phoneScreenshots within /Users/BuildBot/Desktop/Android-Screenshot
[10:44:27]: [4m[36m$ adb devices -l[0m[0m
No such file or directory - fork failed
[33m-------------------------------------------------------------------------------------------[0m
[33m😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.[0m
[33m👍  This makes resolving issues much easier and helps improve fastlane.[0m
[33m🔒  The reports will be stored securely on getsentry.com.[0m
[33m🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3[0m
[33m-------------------------------------------------------------------------------------------[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.1/lib/fastlane_core/command_executor.rb:46:in `spawn': [31m[!] No such file or directory - fork failed[0m (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.1/lib/fastlane_core/command_executor.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/screengrab-0.3.2/lib/screengrab/runner.rb:80:in `select_device'
	from /Library/Ruby/Gems/2.0.0/gems/screengrab-0.3.2/lib/screengrab/runner.rb:52:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/screengrab-0.3.2/bin/screengrab:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/screengrab-0.3.2/bin/screengrab:56:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/screengrab-0.3.2/bin/screengrab:62:in `<main>'
/var/folders/g8/m6nw30110094mk5nh8pj991c0000gn/T/hudson1344588153603882317.sh: line 15: adb: command not found
Build step 'Execute shell' marked build as failure
Finished: FAILURE
``````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

### Configuration Files

screengrab -k '/Users/BuildBot/Desktop/Android-Screenshot/app-devGoogle-debug.apk' -b '/Users/BuildBot/Desktop/Android-Screenshot/app-devGoogle-debug-androidTest-unaligned.apk' -o '/Users/BuildBot/Desktop/Android-Screenshot' -a 'com.test.android' -n '/Users/BuildBot/Library/Android/sdk' --clear_previous_screenshots true -d phone

Fastfile:
```ruby
# INSERT CONTENT HERE : Not using fastfile , writing everyhing in screengrab script file pasted above
```

### Environment

fastlane version (run `fastlane -v`): 0.3.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by kpuneet** [comment]
Can someone please respond and let me know if you consider it a issue in Screengrab  tool ?

**Comment by vpolouchkine** [comment]
Does it run fine locally?

**Comment by kpuneet** [comment]
yes it runs absolutely fine locally , infact i tried running it on jenkins machine with same command/script and it worked flawlessly

**Comment by vpolouchkine** [comment]
You're not getting "weird characters" anymore?

**Comment by kpuneet** [comment]
No , what i am saying here is that I am running the same command on jenkins machine as well as on my local machine flawlessly
but when coming to execute the same command through jenkins Job , the above is the outcome.

**Comment by kpuneet** [comment]
any idea about it ?

**Comment by vpolouchkine** [comment]
I'm not sure, but the `adb: command not found` error sounds like it can't find it in in the PATH var.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Comment by BadPitt** [comment]
You can try: apt-get install android-tools-adb =)

**Comment by dumazy** [comment]
@kpuneet I'm having the exact same issue. Did you solve it?

**Comment by BadPitt** [comment]
try to add adb path in your environment:something like "your_path_to_sdk\Android\sdk\platform-tools\adb") or install android adb tools from repository

**Comment by dumazy** [comment]
@BadPitt I've added adb path in my environment, but apparently it got altered due a misconfiguration. This is no longer an issue. Thanks
