### ISSUE TITLE
Deliver fails with `Forbidden` error

### ISSUE THREAD

**Issue by gapl** [fastlane/fastlane#4899]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### Issue Description

When running deliver to deliver only an ipa file to iTC, fastlane exits with `Forbidden` error.

##### Complete output when running fastlane, including the stack trace and command used

Input: `fastlane app_store version_number:"2.1.0" --verbose`

```
DEBUG [2016-05-29 15:44:03.08]: Using version_number: 2.1.0
INFO [2016-05-29 15:44:03.09]: ------------------------------
INFO [2016-05-29 15:44:03.09]: --- Step: default_platform ---
INFO [2016-05-29 15:44:03.09]: ------------------------------
INFO [2016-05-29 15:44:03.12]: Driving the lane 'ios app_store' 🚀
INFO [2016-05-29 15:44:03.13]: -----------------------
INFO [2016-05-29 15:44:03.13]: --- Step: skip_docs ---
INFO [2016-05-29 15:44:03.13]: -----------------------
INFO [2016-05-29 15:44:03.13]: ---------------------
INFO [2016-05-29 15:44:03.13]: --- Step: deliver ---
INFO [2016-05-29 15:44:03.13]: ---------------------
INFO [2016-05-29 15:44:03.34]: Login to iTunes Connect (xxxxx@xxx.com)
INFO [2016-05-29 15:44:05.84]: Login successful

+--------------------+-------------------------------------+
|                  deliver 1.12.0 Summary                  |
+--------------------+-------------------------------------+
| app_identifier     | com.xxxx.xxxx           |
| username           | xxxxx@xxx.com |
| ipa                | result.ipa                          |
| force              | true                                |
| automatic_release  | false                               |
| submit_for_review  | false                               |
| skip_metadata      | true                                |
| skip_screenshots   | true                                |
| screenshots_path   | ./fastlane/screenshots              |
| metadata_path      | ./fastlane/metadata                 |
| app_version        | 2.1.0                               |
| skip_binary_upload | false                               |
+--------------------+-------------------------------------+

INFO [2016-05-29 15:44:06.60]: Making sure the latest version on iTunes Connect matches '2.1.0' from the ipa file...
INFO [2016-05-29 15:44:07.90]: '2.1.0' is the latest version on iTunes Connect
WARN [2016-05-29 15:44:15.16]: Variable Dump:
INFO [2016-05-29 15:44:15.16]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios app_store"}
ERROR [2016-05-29 15:44:15.16]: Forbidden

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | skip_docs        | 0           |
| 3    | deliver          | 12          |
+------+------------------+-------------+

ERROR [2016-05-29 15:44:15.17]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:174:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	Forbidden
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:313:in `block in update_app_version!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:864:in `with_tunes_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:306:in `update_app_version!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/app_version.rb:285:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.12.0/lib/deliver/upload_assets.rb:19:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.12.0/lib/deliver/runner.rb:61:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.12.0/lib/deliver/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/runner.rb:177:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/runner.rb:162:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/runner.rb:161:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/runner.rb:161:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/runner.rb:109:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:220:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.45.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.91.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Fastfile:
```ruby
lane :app_store do |options|
    deliver(
      app_version: options[:version_number],
      app_identifier: "com.xxxx.xxxx",
      username: "xxxxx@xxx.com",
      ipa: "result.ipa",
      force: true,
      automatic_release: false,
      submit_for_review: false,
      skip_metadata: true,
      skip_screenshots: true
    )
end
```

### Environment

fastlane version: `fastlane 1.91.0`

**Comment by vpolouchkine** [comment]
What is the role of the user logging into iTC?

**Comment by gapl** [comment]
It is set to `Developer`.

**Comment by vpolouchkine** [comment]
Can you try with an admin role?

**Comment by gapl** [comment]
Sorry for the late response. Tried with an admin role now - it works 🎉

**Comment by TKBurner** [comment]
@gapl Thanks for following up. Unfortunately this is because of the iTC api, but we will look into it going forward 👍

**Comment by TKBurner** [comment]
@gapl Thanks for following up. Unfortunately this is because of the iTC api, but we will look into it going forward 👍
