### ISSUE TITLE
Fastlane very slow

### ISSUE THREAD

**Issue by thomasjoulin** [fastlane/fastlane#4904]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane suddenly is very slow and uses 100% CPU. I've tried uninstalling and reinstalling fastlane, no luck. It used to work fine, I didn't update fastlane or any gem recently I think (I did update _after_ the issue occurred of course)

##### Complete output when running fastlane, including the stack trace and command used

```
➜  ~  time fastlane -v
fastlane 1.91.0
fastlane -v  210.40s user 1.80s system 98% cpu 3:35.40 total
```

if I kill the command (ctrl-C), I get this stacktrace:

```
➜  ~  time fastlane -v
^C/Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/stub_specification.rb:138:in `name': Interrupt
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:274:in `block in matching_specs'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:273:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:273:in `find_all'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:273:in `matching_specs'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:295:in `to_specs'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2440:in `block (2 levels) in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2440:in `block (2 levels) in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2440:in `block (2 levels) in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2440:in `block (2 levels) in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2440:in `block (2 levels) in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2440:in `block (2 levels) in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:961:in `block in find_in_unresolved_tree'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:959:in `reverse_each'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:959:in `find_in_unresolved_tree'
	from /Users/thomas/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:87:in `require'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/gems/fastlane-1.91.0/lib/fastlane/actions/actions_helper.rb:66:in `block in load_default_actions'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/gems/fastlane-1.91.0/lib/fastlane/actions/actions_helper.rb:65:in `each'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/gems/fastlane-1.91.0/lib/fastlane/actions/actions_helper.rb:65:in `load_default_actions'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/gems/fastlane-1.91.0/lib/fastlane.rb:27:in `load_actions'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/gems/fastlane-1.91.0/lib/fastlane/commands_generator.rb:12:in `start'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/gems/fastlane-1.91.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/gems/fastlane-1.91.0/bin/fastlane:5:in `<top (required)>'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `load'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `<main>'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/thomas/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Does not apply here I believe. I get the issue while running `fastlane -v` in a random directory

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

I use rvm

**Comment by KrauseFx** [comment]
Did you try [this](https://github.com/fastlane/fastlane#installation):
```
[sudo] gem cleanup
```

**Comment by thomasjoulin** [comment]
@KrauseFx thanks it worked! And thanks for a great project overall

**Comment by KrauseFx** [comment]
Yeah 🚀
