### ISSUE TITLE
PEM doesn't recognise FASTLANE_PASSWORD through Ansible

### ISSUE THREAD

**Issue by luc-codingdutchmen** [fastlane/fastlane#4916]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to run Fastlane through Ansible. The goal is to have a single source of information regarding my projects and having different playbooks to accomplish different tasks for these projects. One of these tasks is updating push provisioning profiles with Fastlane. 

I have a dictionary of projects, which I use with this Ansible Playbook:
```yaml
# Create all PEMs #
- name: create push profile for all fastlane projects
  shell: "pem --username '{{ item.value.ios_developer }}' \
               --app_identifier '{{ item.key }}' \
               --p12_password '{{ p12_password }}' \
               --output_path '{{ local_push_profiles_folder }}' \
               --verbose"
  connection: local
  with_dict: "{{ fastlane_push_projects }}"
  environment: 
    FASTLANE_PASSWORD: "{{ item.value.developer_pass }}"
```

To validate that Ansible is working properly, I've tried this variation (notice the `echo` before `pem`):
```yaml
# Create all PEMs #
- name: create push profile for all fastlane projects
  shell: "echo $FASTLANE_PASSWORD; pem --username '{{ item.value.ios_developer }}' \
               --app_identifier '{{ item.key }}' \
               --p12_password '{{ p12_password }}' \
               --output_path '{{ local_push_profiles_folder }}' \
               --verbose"
  connection: local
  with_dict: "{{ fastlane_push_projects }}"
  environment: 
    FASTLANE_PASSWORD: "{{ item.value.developer_pass }}"
```

##### Complete output when running fastlane, including the stack trace and command used

The output of the last playbook is this:
```
{
  "changed": true,
  "cmd": "echo $FASTLANE_PASSWORD; pem --username '<REDACTED_IOS_DEV_USERNAME>' --app_identifier '<REDACTED_BUNDLE_IDENTIFIER>' --p12_password '<REDACTED_P12_PASSWORD>' --output_path '/certificates/push_profiles' --verbose",
  "delta": "0:00:03.475554",
  "end": "2016-05-31 14:07:24.901470",
  "failed": true,
  "invocation": {
    "module_args": {
      "_raw_params": "echo $FASTLANE_PASSWORD; pem --username '<REDACTED_IOS_DEV_USERNAME>' --app_identifier '<REDACTED_BUNDLE_IDENTIFIER>' --p12_password '<REDACTED_P12_PASSWORD>' --output_path '/certificates/push_profiles' --verbose",
      "_uses_shell": true,
      "chdir": null,
      "creates": null,
      "executable": "/bin/bash",
      "removes": null,
      "warn": true
    },
    "module_name": "command"
  },
  "item": {
    "key": "<REDACTED_BUNDLE_IDENTIFIER>",
    "value": {
      "developer_pass": "<REDACTED_IOS_DEV_PASSWORD>",
      "ios_developer": "<REDACTED_IOS_DEV_USERNAME>",
      "name": "My App - App Store",
      "type": "appstore",
      "ua_key": "<REDACTED_URBAN_AIRSHIP_KEY>"
    }
  },
  "rc": 1,
  "start": "2016-05-31 14:07:21.425916",
  "stderr": "stty: stdin isn't a terminal\nstty: stdin isn't a terminal\nstty: stdin isn't a terminal\n/Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:961:in `get_response': \u001b[31m[!] undefined method `chr' for nil:NilClass\u001b[0m (NoMethodError)\n\tfrom /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:264:in `ask'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:227:in `agree'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.16.0/lib/credentials_manager/account_manager.rb:39:in `invalid_credentials'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:229:in `rescue in login'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:224:in `login'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:88:in `login'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/spaceship.rb:22:in `login'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/spaceship.rb:77:in `login'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/lib/pem/manager.rb:35:in `login'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/lib/pem/manager.rb:10:in `start'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/bin/pem:33:in `block (2 levels) in run'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.45.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/bin/pem:39:in `run'\n\tfrom /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/bin/pem:45:in `<top (required)>'\n\tfrom /usr/local/bin/pem:23:in `load'\n\tfrom /usr/local/bin/pem:23:in `<main>'",
  "stdout": "<REDACTED_IOS_DEV_PASSWORD>\n\n+------------------+---------------------------------------------+\n|                     \u001b[32mSummary for PEM 1.3.1\u001b[0m                      |\n+------------------+---------------------------------------------+\n| username         | <REDACTED_IOS_DEV_USERNAME>                        |\n| app_identifier   | <REDACTED_BUNDLE_IDENTIFIER>          |\n| p12_password     | <REDACTED_P12_PASSWORD>                                |\n| output_path      | /certificates/push_profiles |\n| development      | false                                       |\n| generate_p12     | true                                        |\n| force            | false                                       |\n| save_private_key | true                                        |\n+------------------+---------------------------------------------+\n\nINFO [2016-05-31 14:07:21.84]: Starting login with user '<REDACTED_IOS_DEV_USERNAME>'\n\u001b[31mThe login credentials for '<REDACTED_IOS_DEV_USERNAME>' seem to be wrong\u001b[0m\nDo you want to re-enter your password? (y/n)",
  "stdout_lines": [
    "<REDACTED_IOS_DEV_PASSWORD>",
    "",
    "+------------------+---------------------------------------------+",
    "|                     \u001b[32mSummary for PEM 1.3.1\u001b[0m   |",
    "+------------------+---------------------------------------------+",
    "| username         | <REDACTED_IOS_DEV_USERNAME>                 |",
    "| app_identifier   | <REDACTED_BUNDLE_IDENTIFIER>                |",
    "| p12_password     | <REDACTED_P12_PASSWORD>                     |",
    "| output_path      | /certificates/push_profiles                 |",
    "| development      | false                                       |",
    "| generate_p12     | true                                        |",
    "| force            | false                                       |",
    "| save_private_key | true                                        |",
    "+------------------+---------------------------------------------+",
    "",
    "INFO [2016-05-31 14:07:21.84]: Starting login with user '<REDACTED_IOS_DEV_USERNAME>'",
    "\u001b[31mThe login credentials for '<REDACTED_IOS_DEV_USERNAME>' seem to be wrong\u001b[0m",
    "Do you want to re-enter your password? (y/n)"
  ],
  "warnings": []
}
```

The pretty formatted output of `stderr` is: 
```
  stty: stdin isn't a terminal
  stty: stdin isn't a terminal
  stty: stdin isn't a terminal
  /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:961:in `get_response': \u001b[31m[!] undefined method `chr' for nil:NilClass\u001b[0m (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:227:in `agree'
    from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.16.0/lib/credentials_manager/account_manager.rb:39:in `invalid_credentials'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:229:in `rescue in login'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:224:in `login'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:88:in `login'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/spaceship.rb:22:in `login'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/spaceship.rb:77:in `login'
    from /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/lib/pem/manager.rb:35:in `login'
    from /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/lib/pem/manager.rb:10:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/bin/pem:33:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.45.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/bin/pem:39:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/bin/pem:45:in `<top (required)>'
    from /usr/local/bin/pem:23:in `load'
    from /usr/local/bin/pem:23:in `<main>'
```

### Issue description (continued)

When I run Fastlane PEM in terminal, without using Ansible, these commands work perfectly:
```
export FASTLANE_PASSWORD='REDACTED_IOS_DEV_PASSWORD';
pem --username '<REDACTED_IOS_DEV_USERNAME>' --app_identifier '<REDACTED_BUNDLE_IDENTIFIER>' --p12_password '<REDACTED_P12_PASSWORD>' --output_path '/certificates/push_profiles' --verbose
```

However, when I run the same command through Ansible, my password is not recognised. Using `echo` I can see the environment I'm working in does have the correct variable and value. It seems that Ruby / Fastlane is not able to get this variable from the environment.

I am aware that I can login once and store my username and password in my OS X keychain, after which PEM wil use the stored credentials. However, this requires me to run my commands directly in terminal each time an account is added or its password changed, which I would like to avoid.

### Configuration Files

I used no other configuration files. 

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.91.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by vpolouchkine** [comment]
This is not something on our radar. I'll keep this open for any upvotes.

**Comment by luc-codingdutchmen** [comment]
I am very, very sorry. This is not a bug in Ansible, Ruby or Fastlane - it is a bug between my ears. I had two different iTunes developer accounts in my config and I switched the passwords. I feel stupid.
