### ISSUE TITLE
unsupportedListingLanguage: Listing language da_ is not supported. 

### ISSUE THREAD

**Issue by priyakar** [fastlane/fastlane#4945]
![screen shot 2016-06-01 at 2 24 44 pm](https://cloud.githubusercontent.com/assets/8251036/15722870/bef33c76-280d-11e6-832e-1db8d7fae1c9.png)
### New Issue Checklist

- [y] Updated supply to the latest version
- [y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I run supply -json_key pathname and I get the above error on my first language which is danish (da_). I checked the list of supported languages and danish is a supported language. I was hoping if you could let me know if Im doing something wrong.

##### Complete output when running fastlane, including the stack trace and command used

```

I have attached my file structure below. I am using supply

+-------------------------+------------------------------------------------------------------------+
|                                     Summary for supply 0.7.0                                     |
+-------------------------+------------------------------------------------------------------------+
| json_key                | /pathname
| track                   | production                                                             |
| rollout                 | 1.0                                                                    |
| metadata_path           | ./fastlane/metadata/android                                            |
| skip_upload_apk         | false                                                                  |
| skip_upload_metadata    | false                                                                  |
| skip_upload_images      | false                                                                  |
| skip_upload_screenshots | false                                                                  |
+-------------------------+------------------------------------------------------------------------+

[14:13:28]: To not be asked about this value, you can specify it using 'package_name'
The package name of the Application to modify: packagename
![screen shot 2016-06-01 at 2 24 44 pm](https://cloud.githubusercontent.com/assets/8251036/15720968/d535a9b4-2804-11e6-81a1-d5ddaa2181f1.png)

[14:13:31]: Preparing to upload for language 'da_'...
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:211:in `check_status': [!] unsupportedListingLanguage: Listing language da_ is not supported. (Google::Apis::ClientError)
        from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/lib/google/apis/core/api_command.rb:102:in `check_status'
        from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:179:in `process_response'
        from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:286:in `execute_once'
        from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
        from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
        from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
        from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
        from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:104:in `block in execute'
        from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
        from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
        from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
        from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:96:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/lib/google/apis/core/base_service.rb:345:in `execute_or_queue_command'
        from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/generated/google/apis/androidpublisher_v2/service.rb:1300:in `get_listing'
        from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/client.rb:127:in `listing_for_language'
        from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:17:in `block in perform_upload'
        from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:13:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:13:in `perform_upload'
        from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.4/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
        from /usr/bin/supply:23:in `load'
        from /usr/bin/supply:23:in `<main>'

```

**Comment by priyakar** [comment]
update:  It works for me if I have a suffix to every language. For example, da or da- or da_ did not work but if I put da-DK it seems to work.

**Comment by TKBurner** [comment]
@priyakar Awesome! Really glad to hear you got up and running 👍
