### ISSUE TITLE
Deliver crashes due to permission errors on seemingly temporary file

### ISSUE THREAD

**Issue by remcohaszing** [fastlane/fastlane#4990]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Deliver fails to upload an app icon due to permission problems on `/tmp/57a31fdfb5a257b606d6b0cbcd9a4532.png`. The file is owned by a different user than the one running `deliver`. This looks like a random temporary file, but Deliver actually crashes on this exact file consistently.

A workaround is to delete the mentioned file.

##### Complete output when running deliver, including the stack trace and command used

```
$ /usr/local/bin/deliver --username XXX--ipa 'platforms/ios/build/device/XXX.ipa'
[16:40:40]: Login to iTunes Connect (support@d-centralize.nl)
[16:40:43]: Login successful

+--------------------------------------+-----------------------------------------------------------+
|                                      deliver 1.12.0 Summary                                      |
+--------------------------------------+-----------------------------------------------------------+
| username                             | XXX                                                       |
| ipa                                  | XXXo.ipa                                                  |
| app_icon                             | res/ios/icon-appstore.png                                 |
| app_rating_config_path               | rating.json                                               |
| price_tier                           | 0                                                         |
| force                                | true                                                      |
| automatic_release                    | true                                                      |
| submit_for_review                    | true                                                      |
| app_review_information.first_name    | XXX                                                       |
| app_review_information.last_name     | XXX                                                       |
| app_review_information.phone_number  | XXX                                                       |
| app_review_information.email_address | XXX                                                       |
| app_review_information.notes         | This app was built using Appsemble (https://www.appsem... |
| app_identifier                       | XXX                                                       |
| screenshots_path                     | ./screenshots                                             |
| metadata_path                        | ./metadata                                                |
| app_version                          | 2.2.0                                                     |
| skip_binary_upload                   | false                                                     |
| skip_screenshots                     | false                                                     |
| skip_metadata                        | false                                                     |
+--------------------------------------+-----------------------------------------------------------+

[16:40:47]: Making sure the latest version on iTunes Connect matches '2.2.0' from the ipa file...
[16:40:48]: '2.2.0' is the latest version on iTunes Connect
[16:40:48]: Loading './metadata/nl-NL/description.txt'...
[16:40:48]: Loading './metadata/nl-NL/keywords.txt'...
[16:40:48]: Loading './metadata/nl-NL/support_url.txt'...
[16:40:48]: Loading './metadata/nl-NL/marketing_url.txt'...
[16:40:48]: Loading './metadata/copyright.txt'...
[16:40:48]: Loading './metadata/primary_category.txt'...
[16:40:49]: Activating language nl-NL...
[16:40:51]: Uploading metadata to iTunes Connect
[16:40:52]: Successfully uploaded initial set of metadata to iTunes Connect
[16:40:54]: Starting with the upload of screenshots...
[16:40:54]: Uploading 24 screenshots for language nl-NL
[16:40:54]: Uploading './screenshots/nl-NL/1920001-1242x2208.png'...
[16:40:58]: Uploading './screenshots/nl-NL/1920001-2048x2732.png'...
[16:41:01]: Uploading './screenshots/nl-NL/1920001-640x1096.png'...
[16:41:03]: Uploading './screenshots/nl-NL/1920001-640x920.png'...
[16:41:05]: Uploading './screenshots/nl-NL/1920001-750x1334.png'...
[16:41:07]: Uploading './screenshots/nl-NL/1920001-768x1004.png'...
[16:41:08]: Uploading './screenshots/nl-NL/840001-1242x2208.png'...
[16:41:12]: Uploading './screenshots/nl-NL/840001-2048x2732.png'...
[16:41:15]: Uploading './screenshots/nl-NL/840001-640x1096.png'...
[16:41:22]: Uploading './screenshots/nl-NL/840001-640x920.png'...
[16:41:24]: Uploading './screenshots/nl-NL/840001-750x1334.png'...
[16:41:29]: Uploading './screenshots/nl-NL/840001-768x1004.png'...
[16:41:31]: Uploading './screenshots/nl-NL/840002-1242x2208.png'...
[16:41:34]: Uploading './screenshots/nl-NL/840002-2048x2732.png'...
[16:41:37]: Uploading './screenshots/nl-NL/840002-640x1096.png'...
[16:41:39]: Uploading './screenshots/nl-NL/840002-640x920.png'...
[16:41:41]: Uploading './screenshots/nl-NL/840002-750x1334.png'...
[16:41:44]: Uploading './screenshots/nl-NL/840002-768x1004.png'...
[16:41:45]: Uploading './screenshots/nl-NL/9660002-1242x2208.png'...
[16:41:48]: Uploading './screenshots/nl-NL/9660002-2048x2732.png'...
[16:41:51]: Uploading './screenshots/nl-NL/9660002-640x1096.png'...
[16:41:52]: Uploading './screenshots/nl-NL/9660002-640x920.png'...
[16:41:58]: Uploading './screenshots/nl-NL/9660002-750x1334.png'...
[16:42:00]: Uploading './screenshots/nl-NL/9660002-768x1004.png'...
[16:42:02]: Saving changes
[16:42:35]: Successfully uploaded screenshots to iTunes Connect
[16:42:36]: Price Tier unchanged (tier 0)
[16:42:37]: Uploading app icon...
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1393:in `initialize': [!] Permission denied @ rb_sysopen - /tmp/57a31fdfb5a257b606d6b0cbcd9a4532.png (Errno::EACCES)
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1393:in `open'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1393:in `block in copy_file'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
        from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.27.1/lib/spaceship/du/upload_file.rb:35:in `remove_alpha_channel'
        from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.27.1/lib/spaceship/du/upload_file.rb:18:in `from_path'
        from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.27.1/lib/spaceship/tunes/app_version.rb:314:in `upload_large_icon!'
        from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.12.0/lib/deliver/upload_assets.rb:11:in `upload'
        from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.12.0/lib/deliver/runner.rb:61:in `upload_metadata'
        from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.12.0/lib/deliver/runner.rb:21:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.12.0/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.46.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
        from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.12.0/lib/deliver/commands_generator.rb:132:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.12.0/lib/deliver/commands_generator.rb:12:in `start'
        from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.12.0/bin/deliver:5:in `<top (required)>'
        from /usr/local/bin/deliver:23:in `load'
        from /usr/local/bin/deliver:23:in `<main>'
```

### Configuration Files

Deliverfile:
```ruby
app_icon('res/ios/icon-appstore.png')
app_rating_config_path('rating.json')
price_tier(0)
force(true)  # If not specified, deliver will wait for user interaction.
automatic_release(true)
submit_for_review(true)
app_review_information(
  first_name: 'XXX',
  last_name: 'XXX',
  phone_number: 'XXX',
  email_address: 'XXX',
  notes: 'This app was built using Appsemble (https://www.appsemble.com).'
)
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.93.1
deliver 1.13.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No, I use a Ruby version installed using Homebrew.

**Comment by TKBurner** [comment]
Hi @remcohaszing Thanks for reaching out. It appears that requires write permissions to run this. Can you have the other user change the permissions for you to test this out? Thanks!
