### ISSUE TITLE
Error using frameit - mini magick Error: convert unable to open image

### ISSUE THREAD

**Issue by StuartMorris0** [fastlane/fastlane#5010]
Current fastlane version - 1.94.0
Current frameit version - 2.7.0

Just setup and trying to use frameit for the first time. I am getting the following error:  

```
Converting PSD file '/Users/username/.frameit/devices_frames/iPad Pro/iPad-Pro-Silver-horizontal.psd'
/Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/shell.rb:18:in `run': [!] `convert /var/folders/37/zh47_fw120g8y5b7r6x519jw0000gn/T/mini_magick20160605-39526-1pp15qr.psd[0] /var/folders/37/zh47_fw120g8y5b7r6x519jw0000gn/T/mini_magick20160605-39526-1b4xaje.png` failed with error: (MiniMagick::Error)
convert: unable to open image `/var/folders/37/zh47_fw120g8y5b7r6x519jw0000gn/T/mini_magick20160605-39526-1pp15qr.psd[0]': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no images defined `/var/folders/37/zh47_fw120g8y5b7r6x519jw0000gn/T/mini_magick20160605-39526-1b4xaje.png' @ error/convert.c/ConvertImageCommand/3257.
```

When checking the folder that mini magick is moving the files too they exist, then remove so not sure how to tell what is happening. Running 'frameit --verbose' gives me no other output.

Not sure if this is related to a previous issue at all, but the issue still occurs for me (although looks slightly different) https://github.com/fastlane-old/frameit/issues/12

**Comment by simonliotier** [comment]
I have the exact same issue. Fresh installs of frameit (2.7.0) and ImageMagick (6.9.4-7).

Here is the complete output: 

```
Converting PSD file '/Users/Simon/.frameit/devices_frames/iPhone-6s/iPhone 6s - Silver/iPhone-6s-Silver-horizontal.psd'
/Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/shell.rb:18:in `run': [!] `convert /var/folders/0z/10hf7cx93d769yh8pdrf8hkc0000gn/T/mini_magick20160606-18225-1chohg7.psd[0] /var/folders/0z/10hf7cx93d769yh8pdrf8hkc0000gn/T/mini_magick20160606-18225-1b0jeii.png` failed with error: (MiniMagick::Error)
convert: unable to open image `/var/folders/0z/10hf7cx93d769yh8pdrf8hkc0000gn/T/mini_magick20160606-18225-1chohg7.psd[0]': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no images defined `/var/folders/0z/10hf7cx93d769yh8pdrf8hkc0000gn/T/mini_magick20160606-18225-1b0jeii.png' @ error/convert.c/ConvertImageCommand/3257.

	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:92:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:40:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:349:in `format'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/frame_converter.rb:89:in `block in convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/frame_converter.rb:61:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/frame_converter.rb:61:in `convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/runner.rb:10:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:36:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:61:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/bin/frameit:7:in `<top (required)>'
	from /usr/local/bin/frameit:23:in `load'
	from /usr/local/bin/frameit:23:in `<main>'
```

**Comment by dantaylorseo** [comment]
Exact issue here:

```
Converting PSD file '/Users/DanTaylor/.frameit/devices_frames/iPad Pro/iPad-Pro-Silver-horizontal.psd'
/Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/shell.rb:18:in `run': [!] `convert /var/folders/lt/zn582hqn3731k_vzgj4l1j580000gn/T/mini_magick20160606-91204-hex813.psd[0] /var/folders/lt/zn582hqn3731k_vzgj4l1j580000gn/T/mini_magick20160606-91204-5lusut.png` failed with error: (MiniMagick::Error)
convert: unable to open image `/var/folders/lt/zn582hqn3731k_vzgj4l1j580000gn/T/mini_magick20160606-91204-hex813.psd[0]': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no images defined `/var/folders/lt/zn582hqn3731k_vzgj4l1j580000gn/T/mini_magick20160606-91204-5lusut.png' @ error/convert.c/ConvertImageCommand/3257.

	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:92:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:40:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:349:in `format'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/frame_converter.rb:89:in `block in convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/frame_converter.rb:61:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/frame_converter.rb:61:in `convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/runner.rb:10:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:36:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:61:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/bin/frameit:7:in `<top (required)>'
	from /usr/local/bin/frameit:23:in `load'
	from /usr/local/bin/frameit:23:in `<main>'
```

**Comment by windaddict** [comment]
I see it as well:

```
Converting PSD file '/Users/jknox/.frameit/devices_frames/iPad-mini-4/iPad-mini-Silver/iPad-mini-Silver-horizontal.psd'
/Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/shell.rb:18:in `run': [!] `convert /var/folders/b9/tz1p8_yd1dz61yb0vb0mt9km0000gn/T/mini_magick20160607-3169-p2nj7y.psd[0] /var/folders/b9/tz1p8_yd1dz61yb0vb0mt9km0000gn/T/mini_magick20160607-3169-1yq15es.png` failed with error: (MiniMagick::Error)
convert: unable to open image `/var/folders/b9/tz1p8_yd1dz61yb0vb0mt9km0000gn/T/mini_magick20160607-3169-p2nj7y.psd[0]': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no images defined `/var/folders/b9/tz1p8_yd1dz61yb0vb0mt9km0000gn/T/mini_magick20160607-3169-1yq15es.png' @ error/convert.c/ConvertImageCommand/3257.

	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:92:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:40:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:349:in `format'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/frame_converter.rb:89:in `block in convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/frame_converter.rb:61:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/frame_converter.rb:61:in `convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/runner.rb:10:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:36:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:61:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/bin/frameit:7:in `<top (required)>'
	from /usr/local/bin/frameit:23:in `load'
	from /usr/local/bin/frameit:23:in `<main>'
```

I attempted updating all gems and re-installing Image Magick.

**Comment by TKBurner** [comment]
Thanks all for reporting! I reached out to the core team so we can get eyes on this. 👍

**Comment by hannesoid** [comment]
+1

**Comment by dantaylorseo** [comment]
@TKBurner any update on this?

**Comment by TKBurner** [comment]
@dantaylorseo Thanks for following up. I just bumped this with the team. Thanks!

**Comment by jlaws** [comment]
TL/DR - Its not frameit, its imagemagick.  Try uninstalling then reinstalling imagemagick using Macports.

I had the same issue and tried reverting to frameit v2.6 and v2.5.  Neither worked.  The error appeared to be related to convert, which is part of imagemagick.  So I uninstalled imagemagick which was previously installed with Homebrew.  Downloaded Macports and installed imagemagick from there, hoping to get version 7.0, but it was still 6.9.4-4.  Tried frameit again and everything worked fine.

**Comment by windaddict** [comment]
I ran ```brew upgrade imagemagick```, and the error went away. Thanks!

**Comment by StuartMorris0** [comment]
@windaddict - what version of imagemagick do you have? I have the latest (6.9.4-7) which the issue happens with.

**Comment by hannesoid** [comment]
@jlaws I upgraded imagemagick `brew upgrade imagemagick`, now with version 6.9.4-9 the error ist gone, thanks!

**Comment by TKBurner** [comment]
@StuartMorris0 Have you tried upgrading to 4-9? Let me know how it goes 👍

**Comment by StuartMorris0** [comment]
When running upgrade I get a message saying error you already have the latest 6.9-4-7

**Comment by TKBurner** [comment]
Hi @StuartMorris0 Thanks for following up. Can you share the full set of commands you are using to upgrade? I want to take a look 👍

**Comment by StuartMorris0** [comment]
Yep as above, `brew upgrade imagemagick`

**Comment by TKBurner** [comment]
Hi @StuartMorris0 Thanks for following up. It looks like you might need to manually install the binary in this case: http://www.imagemagick.org/download/. The current version is 6.9 4-9.

Thanks!
