### ISSUE TITLE
gym unable to use   provisioning profile installed by match

### ISSUE THREAD

**Issue by lakamsani** [fastlane/fastlane#5017]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Match downloads and installs provisioning profile but gym fails saying provisioning profile is not found. Note that this setup has been working for a Adhoc and a developer profile just fine for the past few weeks. This is the ap store profile that is failing. 

##### Complete output when running fastlane, including the stack trace and command used

```

onkore-ios git:(master) ✗ fastlane --verbose tf
DEBUG [2016-06-06 10:36:42.60]: Checking if there are any plugins that should be loaded...
INFO [2016-06-06 10:36:42.62]: -------------------------------------------------
INFO [2016-06-06 10:36:42.62]: --- Step: Verifying required fastlane version ---
INFO [2016-06-06 10:36:42.62]: -------------------------------------------------
INFO [2016-06-06 10:36:42.62]: fastlane version valid
INFO [2016-06-06 10:36:42.63]: ------------------------------
INFO [2016-06-06 10:36:42.63]: --- Step: default_platform ---
INFO [2016-06-06 10:36:42.63]: ------------------------------
INFO [2016-06-06 10:36:42.66]: Driving the lane 'ios tf' 🚀
INFO [2016-06-06 10:36:42.67]: -----------------------
INFO [2016-06-06 10:36:42.67]: --- Step: cocoapods ---
INFO [2016-06-06 10:36:42.67]: -----------------------
INFO [2016-06-06 10:36:42.67]: $ pod install
INFO [2016-06-06 10:36:44.76]: ▸ Analyzing dependencies
INFO [2016-06-06 10:36:44.76]: ▸ Downloading dependencies
INFO [2016-06-06 10:36:44.76]: ▸ Using AFNetworkActivityLogger (2.0.1)
INFO [2016-06-06 10:36:44.76]: ▸ Using AFNetworking (2.6.3)
INFO [2016-06-06 10:36:44.76]: ▸ Using Alamofire (3.4.0)
INFO [2016-06-06 10:36:44.76]: ▸ Using CocoaLumberjack (2.3.0)
INFO [2016-06-06 10:36:44.76]: ▸ Using Crashlytics (3.7.0)
INFO [2016-06-06 10:36:44.76]: ▸ Using EZSwiftExtensions (1.4)
INFO [2016-06-06 10:36:44.76]: ▸ Using Fabric (1.6.7)
INFO [2016-06-06 10:36:44.76]: ▸ Using JSQMessagesViewController (7.2.0)
INFO [2016-06-06 10:36:44.76]: ▸ Using JSQSystemSoundPlayer (2.0.1)
INFO [2016-06-06 10:36:44.76]: ▸ Using KDCircularProgress (1.4.0)
INFO [2016-06-06 10:36:44.76]: ▸ Using Locksmith (2.0.8)
INFO [2016-06-06 10:36:44.76]: ▸ Using MBProgressHUD (0.9.2)
INFO [2016-06-06 10:36:44.76]: ▸ Using MZAppearance (1.1.6)
INFO [2016-06-06 10:36:44.76]: ▸ Using MZFormSheetController (3.1.3)
INFO [2016-06-06 10:36:44.76]: ▸ Using Socket.IO-Client-Swift (6.1.2)
INFO [2016-06-06 10:36:44.76]: ▸ Using SwiftMoment (0.4)
INFO [2016-06-06 10:36:44.76]: ▸ Using SwiftyJSON (2.3.2)
INFO [2016-06-06 10:36:44.76]: ▸ Using TIPBadgeManager (0.3.0)
INFO [2016-06-06 10:36:44.76]: ▸ Using TwitterCore (2.0.2)
INFO [2016-06-06 10:36:44.76]: ▸ Using TwitterKit (2.0.2)
INFO [2016-06-06 10:36:44.76]: ▸ Using UICountingLabel (1.4.0)
INFO [2016-06-06 10:36:44.77]: ▸ Using iCarousel (1.8.2)
INFO [2016-06-06 10:36:44.77]: ▸ Generating Pods project
INFO [2016-06-06 10:36:47.19]: ▸ Integrating client projects
INFO [2016-06-06 10:36:47.41]: ▸ Sending stats
INFO [2016-06-06 10:36:47.44]: ▸ Pod installation complete! There are 19 dependencies from the Podfile and 22 total pods installed.
INFO [2016-06-06 10:36:47.44]: ▸ [!] xcodeproj was renamed to `project`. Please use that from now on.
INFO [2016-06-06 10:36:47.44]: ▸ [!] xcodeproj was renamed to `project`. Please use that from now on.
INFO [2016-06-06 10:36:47.44]: ▸ [!] MZFormSheetController has been deprecated in favor of MZFormSheetPresentationController
INFO [2016-06-06 10:36:47.48]: -------------------
INFO [2016-06-06 10:36:47.48]: --- Step: match ---
INFO [2016-06-06 10:36:47.48]: -------------------

+-----------------------+-------------------------------------------+
|                      Summary for match 0.6.1                      |
+-----------------------+-------------------------------------------+
| app_identifier        | com.onkore.DanceOnkorePhone               |
| readonly              | true                                      |
| type                  | appstore                                  |
| git_url               | git@bitbucket.org:company/certs.git |
| username              | xyz@abc.com                        |
| git_branch            | master                                    |
| keychain_name         | login.keychain                            |
| team_id               | 12345678                                |
| verbose               | false                                     |
| force                 | false                                     |
| shallow_clone         | false                                     |
| force_for_new_devices | false                                     |
| skip_docs             | false                                     |
+-----------------------+-------------------------------------------+

INFO [2016-06-06 10:36:47.91]: Cloning remote git repo...
INFO [2016-06-06 10:36:47.91]: $ git clone 'git@bitbucket.org:company/certs.git' '/var/folders/69/5dwbppxx1h1c89l7msfw05fm0000gn/T/d20160606-12288-1vtpkbn'
INFO [2016-06-06 10:36:47.91]: ▸ Cloning into '/var/folders/69/5dwbppxx1h1c89l7msfw05fm0000gn/T/d20160606-12288-1vtpkbn'...
INFO [2016-06-06 10:36:50.21]: ▸ remote: Counting objects: 219, done.
INFO [2016-06-06 10:36:51.71]: ▸ remote: Compressing objects: 100% (209/209), done.
INFO [2016-06-06 10:36:54.66]: ▸ remote: Total 219 (delta 31), reused 0 (delta 0)
INFO [2016-06-06 10:36:54.66]: ▸ Receiving objects: 100% (219/219), 521.37 KiB | 158.00 KiB/s, done.
INFO [2016-06-06 10:36:54.67]: ▸ Resolving deltas: 100% (31/31), done.
INFO [2016-06-06 10:36:54.68]: ▸ Checking connectivity... done.
INFO [2016-06-06 10:36:54.76]: 🔓  Decrypted '7VSWF7JP9M.cer'
INFO [2016-06-06 10:36:54.84]: 🔓  Decrypted '7ZJ3R8PYFJ.cer'
INFO [2016-06-06 10:36:54.91]: 🔓  Decrypted '7VSWF7JP9M.p12'
INFO [2016-06-06 10:36:54.98]: 🔓  Decrypted '7ZJ3R8PYFJ.p12'
INFO [2016-06-06 10:36:55.06]: 🔓  Decrypted 'AdHoc_com.onkore.DanceOnkorePhone.Adhoc.mobileprovision'
INFO [2016-06-06 10:36:55.13]: 🔓  Decrypted 'AppStore_com.onkore.DanceOnkore.mobileprovision'
INFO [2016-06-06 10:36:55.21]: 🔓  Decrypted 'AppStore_com.onkore.DanceOnkorePhone.mobileprovision'
INFO [2016-06-06 10:36:55.27]: 🔓  Decrypted 'Development_com.onkore.DanceOnkore.Debug.mobileprovision'
INFO [2016-06-06 10:36:55.33]: 🔓  Decrypted 'Development_com.onkore.DanceOnkorePhone.Debug.mobileprovision'
INFO [2016-06-06 10:36:55.33]: 🔓  Successfully decrypted certificates repo
INFO [2016-06-06 10:36:55.33]: Installing certificate...
INFO [2016-06-06 10:36:55.33]: $ security list-keychains -d user
INFO [2016-06-06 10:36:55.35]: ▸     "/Users/vamsee/Library/Keychains/login.keychain"
INFO [2016-06-06 10:36:55.35]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/vamsee/Library/Keychains/login.keychain
INFO [2016-06-06 10:36:55.38]: ▸ keychain: "/Users/vamsee/Library/Keychains/login.keychain"
INFO [2016-06-06 10:36:55.38]: ▸ version: 256
INFO [2016-06-06 10:36:55.38]: ▸ class: 0x80001000
INFO [2016-06-06 10:36:55.38]: ▸ attributes:
INFO [2016-06-06 10:36:55.38]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-06-06 10:36:55.38]: ▸     "cenc"<uint32>=0x00000003
INFO [2016-06-06 10:36:55.38]: ▸     "ctyp"<uint32>=0x00000001
INFO [2016-06-06 10:36:55.38]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-06-06 10:36:55.38]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2016-06-06 10:36:55.38]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-06-06 10:36:55.38]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-06-06 10:36:55.38]: ▸     "snbr"<blob>=0x19
INFO [2016-06-06 10:36:55.38]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
DEBUG [2016-06-06 10:36:55.98]: Certificate '7ZJ3R8PYFJ.cer' is already installed on this machine
INFO [2016-06-06 10:36:55.98]: $ security import /var/folders/69/5dwbppxx1h1c89l7msfw05fm0000gn/T/d20160606-12288-1vtpkbn/certs/distribution/7ZJ3R8PYFJ.p12 -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign -T /usr/bin/security&> /dev/null
INFO [2016-06-06 10:36:56.04]: Installing provisioning profile...
WARN [2016-06-06 10:36:56.15]: Setting environment variable 'sigh_com.onkore.DanceOnkorePhone_appstore' to '947b2f83-633c-42dc-a807-c35043ad2f47'

+----------------------+-------------------------------------------+
|                  Installed Provisioning Profile                  |
+----------------------+-------------------------------------------+
| App Identifier       | com.onkore.DanceOnkorePhone               |
| Type                 | appstore                                  |
| UUID                 | 947b2f83-633c-42dc-a807-c35043ad2f47      |
| Environment Variable | sigh_com.onkore.DanceOnkorePhone_appstore |
+----------------------+-------------------------------------------+

INFO [2016-06-06 10:36:56.15]: All required keys, certificates and provisioning profiles are installed 🙌
INFO [2016-06-06 10:36:56.15]: 🔒  Successfully encrypted certificates repo
INFO [2016-06-06 10:36:56.15]: Setting Provisioning Profile type to 'app-store'
INFO [2016-06-06 10:36:56.16]: -----------------
INFO [2016-06-06 10:36:56.16]: --- Step: gym ---
INFO [2016-06-06 10:36:56.16]: -----------------
WARN [2016-06-06 10:36:56.21]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816
WARN [2016-06-06 10:36:56.28]: xcrun xcodebuild -list -workspace 'Onkore.xcworkspace'
2016-06-06 10:36:56.495 xcodebuild[12511:58318] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-06-06 10:36:58.429 xcodebuild[12526:58377] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs

+----------------------+----------------------+
|            Summary for gym 1.6.3            |
+----------------------+----------------------+
| workspace            | Onkore.xcworkspace   |
| scheme               | OnkoreiPhoneRelease  |
| output_directory     | archives             |
| clean                | true                 |
| use_legacy_build_api | true                 |
| include_bitcode      | true                 |
| export_method        | app-store            |
| destination          | generic/platform=iOS |
| output_name          | Onkore-iPhone        |
| silent               | false                |
| buildlog_path        | ~/Library/Logs/gym   |
+----------------------+----------------------+

+-------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
|                                                                                   Generated Build Command                                                                                   |
+-------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| Option                                                                              | Value                                                                                                 |
+-------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| set -o pipefail &&                                                                  |                                                                                                       |
| xcodebuild                                                                          |                                                                                                       |
| -workspace                                                                          | Onkore.xcworkspace                                                                                    |
| -scheme                                                                             | OnkoreiPhoneRelease                                                                                   |
| -destination                                                                        | generic/platform=iOS                                                                                  |
| -archivePath                                                                        | /Users/vamsee/Library/Developer/Xcode/Archives/2016-06-06/Onkore-iPhone 2016-06-06 10.37.01.xcarchive |
| clean                                                                               |                                                                                                       |
| archive                                                                             |                                                                                                       |
| | tee /Users/vamsee/Library/Logs/gym/Onkore-iPhone-OnkoreiPhoneRelease.log | xcpretty |                                                                                                       |
+-------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
INFO [2016-06-06 10:37:01.57]: $ set -o pipefail && xcodebuild -workspace 'Onkore.xcworkspace' -scheme 'OnkoreiPhoneRelease' -destination 'generic/platform=iOS' -archivePath '/Users/vamsee/Library/Developer/Xcode/Archives/2016-06-06/Onkore-iPhone 2016-06-06 10.37.01.xcarchive' clean archive | tee /Users/vamsee/Library/Logs/gym/Onkore-iPhone-OnkoreiPhoneRelease.log | xcpretty
INFO [2016-06-06 10:37:01.90]: ▸ 2016-06-06 10:37:01.904 xcodebuild[12551:58440] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs

INFO [2016-06-06 10:39:21.22]: ▸ Touching Pods_OnkoreiPhone.framework
INFO [2016-06-06 10:39:21.28]: ▸ Signing /Users/vamsee/Library/Developer/Xcode/DerivedData/Onkore-cqhdpxkmthcxrffvifokbmbpdrxi/Build/Intermediates/ArchiveIntermediates/OnkoreiPhoneRelease/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Pods_OnkoreiPhone.framework
INFO [2016-06-06 10:39:21.45]: ▸ Building Onkore-iPhone/OnkoreiPhone [Release]
INFO [2016-06-06 10:39:21.45]: ▸ Check Dependencies
INFO [2016-06-06 10:39:21.45]: ▸ ❌  Code Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.onkore.DanceOnkorePhone” were found.
INFO [2016-06-06 10:39:21.48]: ▸ ** ARCHIVE FAILED **
INFO [2016-06-06 10:39:21.48]: ▸ The following build commands failed:
INFO [2016-06-06 10:39:21.48]: ▸ Check dependencies
INFO [2016-06-06 10:39:21.48]: ▸ (1 failure)

▸ Touching Pods_OnkoreiPhone.framework
▸ Signing /Users/vamsee/Library/Developer/Xcode/DerivedData/Onkore-cqhdpxkmthcxrffvifokbmbpdrxi/Build/Intermediates/ArchiveIntermediates/OnkoreiPhoneRelease/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Pods_OnkoreiPhone.framework
▸ Building Onkore-iPhone/OnkoreiPhone [Release]
▸ Check Dependencies

❌  Code Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.onkore.DanceOnkorePhone” were found.


** ARCHIVE FAILED **


The following build commands failed:
Check dependencies
(1 failure)
ERROR [2016-06-06 10:39:21.55]: Exit status: 65
ERROR [2016-06-06 10:39:21.55]: You don't have a provisioning profile for the bundle identifier 'com.onkore.DanceOnkorePhone' installed on the local machine
ERROR [2016-06-06 10:39:21.55]: Make sure you have the profile on this computer and it's properly installed
ERROR [2016-06-06 10:39:21.55]: You can use sigh (https://github.com/fastlane/fastlane/tree/master/sigh) to download and install the provisioning profile
ERROR [2016-06-06 10:39:21.55]: Follow this guide: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/CodeSigning.md
WARN [2016-06-06 10:39:21.55]: Variable Dump:
INFO [2016-06-06 10:39:21.55]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios tf", :SIGH_PROFILE_TYPE=>"app-store"}
ERROR [2016-06-06 10:39:21.55]: Error building the application - see the log above
INFO [2016-06-06 10:39:21.55]: Successfully generated documentation to path '/Users/vamsee/Development/OnKore/onkore-ios/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 4           |
| 4    | match                               | 8           |
| 5    | gym                                 | 145         |
+------+-------------------------------------+-------------+

ERROR [2016-06-06 10:39:21.56]: fastlane finished with errors
/Users/vamsee/Software/ruby/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Error building the application - see the log above (FastlaneCore::Interface::FastlaneError)
	from /Users/vamsee/Software/ruby/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/vamsee/Software/ruby/gems/gym-1.6.3/lib/gym/error_handler.rb:53:in `handle_build_error'
	from /Users/vamsee/Software/ruby/gems/gym-1.6.3/lib/gym/runner.rb:101:in `block in build_app'
	from /Users/vamsee/Software/ruby/gems/fastlane_core-0.46.2/lib/fastlane_core/command_executor.rb:88:in `call'
	from /Users/vamsee/Software/ruby/gems/fastlane_core-0.46.2/lib/fastlane_core/command_executor.rb:88:in `execute'
	from /Users/vamsee/Software/ruby/gems/gym-1.6.3/lib/gym/runner.rb:97:in `build_app'
	from /Users/vamsee/Software/ruby/gems/gym-1.6.3/lib/gym/runner.rb:12:in `run'
	from /Users/vamsee/Software/ruby/gems/gym-1.6.3/lib/gym/manager.rb:10:in `work'


### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  desc "Submit a new  Build to TestFlight"
  lane :tf do
     
      match(app_identifier: "com.onkore.DanceOnkorePhone", readonly: true, type: "appstore")

      gym(
          workspace: 'Onkore.xcworkspace',
          scheme: 'OnkoreiPhoneRelease',
          output_directory: "archives",
          clean: true, use_legacy_build_api:true, include_bitcode:true
      )
      #pilot(app_identifier: "com.onkore.DanceOnkorePhone")
          

  end
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.94.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by lakamsani** [comment]
I changed the app id (due to other reasons) and created a new profile with push using product/pem and match/pilot  and it seems  to work fine now and uploading to iTunes connect. Not sure how to reproduce this. May be keep this open for a couple of more days and then close it

**Comment by TKBurner** [comment]
@lakamsani Sounds like a plan! I'm glad to hear you got up and running. Thanks!
