### ISSUE TITLE
Cannot create device grid - Undefined method `device_grid'

### ISSUE THREAD

**Issue by fwal** [fastlane/fastlane#5020]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Im trying to test the new device grid feature using danger but running into an exception when trying to generate the device grid.

##### Complete output when running fastlane, including the stack trace and command used

```
> bundle exec danger
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From [redacted]
 * [new ref]         refs/pull/1/merge -> danger_head
[12:37:25]: ------------------------------------------
[12:37:25]: --- Step: build_and_upload_to_appetize ---
[12:37:25]: ------------------------------------------
[12:37:25]: For a more detailed xcodebuild log open /Users/distiller/Library/Logs/fastlane/xcbuild/2016-06-06/661/xcodebuild.log
[12:37:25]: $ set -o pipefail && xcodebuild -workspace "Hype.xcworkspace" -scheme "Hype" -sdk "iphonesimulator" -derivedDataPath "/tmp/fastlane_build" CONFIGURATION_BUILD_DIR=/tmp/fastlane_build | tee '/Users/distiller/Library/Logs/fastlane/xcbuild/2016-06-06/661/xcodebuild.log' | xcpretty --color --simple
[12:37:26]: ▸ 2016-06-06 12:37:26.019 xcodebuild[675:7336] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk; its version (7.1) is below required minimum (9.3) for the iphonesimulator platform.
[12:37:26]: ▸ 2016-06-06 12:37:26.021 xcodebuild[675:7336] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk; its version (8.4) is below required minimum (9.3) for the iphonesimulator platform.
[12:37:26]: ▸ 2016-06-06 12:37:26.022 xcodebuild[675:7336] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk; its version (9.0) is below required minimum (9.3) for the iphonesimulator platform.
[12:37:26]: ▸ 2016-06-06 12:37:26.023 xcodebuild[675:7336] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk; its version (9.1) is below required minimum (9.3) for the iphonesimulator platform.
[12:37:26]: ▸ 2016-06-06 12:37:26.025 xcodebuild[675:7336] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk; its version (9.2) is below required minimum (9.3) for the iphonesimulator platform.
[12:37:28]: ▸ Building Hype/Hype [Debug]
[12:37:28]: ▸ Check Dependencies
[12:37:28]: ▸ Compiling SecondViewController.swift
[12:37:31]: ▸ Compiling AppDelegate.swift
[12:37:31]: ▸ Compiling FirstViewController.swift
[12:37:31]: ▸ Linking Hype
[12:37:31]: ▸ Compiling Main.storyboard
[12:37:36]: ▸ Compiling LaunchScreen.storyboard
[12:37:36]: ▸ Processing Info.plist
[12:37:36]: ▸ Touching Hype.app
[12:37:36]: ▸ Build Succeeded
[12:37:36]: Compressing /tmp/fastlane_build/Hype.app...
[12:37:36]: $ zip -r /tmp/fastlane_build/Result.zip Hype.app
[12:37:36]: ▸ adding: Hype.app/ (stored 0%)
[12:37:36]: ▸ adding: Hype.app/Assets.car (deflated 97%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/ (stored 0%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/LaunchScreen.storyboardc/ (stored 0%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib (deflated 42%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/LaunchScreen.storyboardc/Info.plist (deflated 42%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib (deflated 34%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/Main.storyboardc/ (stored 0%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/Main.storyboardc/8rJ-Kc-sve-view-QS5-Rx-YEW.nib (deflated 44%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/Main.storyboardc/9pv-A4-QxB-view-tsR-hK-woN.nib (deflated 44%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/Main.storyboardc/Info.plist (deflated 41%)
[12:37:36]: ▸ adding: Hype.app/Base.lproj/Main.storyboardc/UITabBarController-49e-Tb-3d3.nib (deflated 40%)
[12:37:36]: ▸ adding: Hype.app/Frameworks/ (stored 0%)
[12:37:36]: ▸ adding: Hype.app/Frameworks/libswiftContacts.dylib (deflated 84%)
[12:37:37]: ▸ adding: Hype.app/Frameworks/libswiftCore.dylib (deflated 72%)
[12:37:37]: ▸ adding: Hype.app/Frameworks/libswiftCoreGraphics.dylib (deflated 74%)
[12:37:37]: ▸ adding: Hype.app/Frameworks/libswiftCoreImage.dylib (deflated 88%)
[12:37:37]: ▸ adding: Hype.app/Frameworks/libswiftDarwin.dylib (deflated 73%)
[12:37:37]: ▸ adding: Hype.app/Frameworks/libswiftDispatch.dylib (deflated 84%)
[12:37:37]: ▸ adding: Hype.app/Frameworks/libswiftFoundation.dylib (deflated 72%)
[12:37:37]: ▸ adding: Hype.app/Frameworks/libswiftObjectiveC.dylib (deflated 73%)
[12:37:37]: ▸ adding: Hype.app/Frameworks/libswiftUIKit.dylib (deflated 75%)
[12:37:37]: ▸ adding: Hype.app/Hype (deflated 76%)
[12:37:37]: ▸ adding: Hype.app/Info.plist (deflated 34%)
[12:37:37]: ▸ adding: Hype.app/PkgInfo (stored 0%)
[12:37:37]: Successfully generated zip file at path '/tmp/fastlane_build/Result.zip'
[12:37:37]: Uploading apk to appetize... this might take a while
[12:37:38]: App URL: https://appetize.io/app/[redacted]
[12:37:38]: Manage URL: https://appetize.io/manage/[redacted]
[12:37:38]: Public Key: [redacted]
[12:37:38]: Build successfully uploaded to Appetize.io
[12:37:38]: Generated Public Key: [redacted]
bundler: failed to load command: danger (/Users/distiller/hype/vendor/bundle/ruby/2.0.0/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined method `device_grid' for #<Danger::Dangerfile:0x007fa3541579e0>. Updating the Danger gem might fix the issue.

 #  from Dangerfile:15
 #  -------------------------------------------
 #  
 >  device_grid(
 #    public_key: result,
 #  -------------------------------------------

  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:64:in `method_missing'
  Dangerfile:15:in `block in parse'
  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:177:in `eval'
  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:177:in `block in parse'
  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:173:in `instance_eval'
  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:173:in `parse'
  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/commands/runner.rb:54:in `run'
  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/bin/danger:5:in `<top (required)>'
  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/bin/danger:22:in `load'
  /Users/distiller/hype/vendor/bundle/ruby/2.0.0/bin/danger:22:in `<top (required)>'

bundle exec danger returned exit code 1
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.93.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```

Dangerfile
```ruby
# Fastlane device grid

options = {
  xcodebuild: {
      workspace: "Hype.xcworkspace",
      scheme: "Hype"
    }
}

require 'fastlane'
result = Fastlane::OneOff.run(action: "build_and_upload_to_appetize", parameters: options)

require 'fastlane/actions/device_grid/device_grid'

device_grid(
  public_key: result,
  languages: ["en", "de"],
  devices: ["iphone5s", "iphone6splus", "ipadair"]
)
```
### Environment

fastlane version (run `fastlane -v`):
`fastlane 1.94.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Yes, `bundle exec danger`

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by fwal** [comment]
Issue still exist in fastlane 1.94.1

**Comment by KrauseFx** [comment]
Working on this together with @neonichu and @orta, sorry for the troubles, we'll provide a fix 👍

**Comment by neonichu** [comment]
See #5060 for progress :+1:

**Comment by fwal** [comment]
Getting this with `fastlane 1.95.0`  and `danger 0.8.2`:
`Invalid Dangerfile file: cannot load such file -- fastlane/actions/device_grid/device_grid`

**Comment by fwal** [comment]
Never mind, saw the new config for device_grid now 😉
