### ISSUE TITLE
upload_symbols_to_crashlytics doesn't mention that Fabric.app or Fabric CocoaPods is required

### ISSUE THREAD

**Issue by hborders** [fastlane/fastlane#5021]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The `binary_path` parameter of the `upload_symbols_to_crashlytics` action should mention that it is required unless you have `/Applications/Fabric.app` or you used Fabric with CocoaPods.

##### Complete output when running fastlane, including the stack trace and command used

```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Please provide a path to the binary using binary_path: (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:80:in `find_binary_path'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/actions/upload_symbols_to_crashlytics.rb:7:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:66:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/commands_generator.rb:235:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/commands_generator.rb:18:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

When I install `Fabric.app` everything works as expected.

**Comment by TKBurner** [comment]
Hi @hborders is this similar to #4885 ? Thanks!

**Comment by hborders** [comment]
No, I think this is different. This is just a documentation request. If I run `fastlane action upload_symbols_to_crashlytics`, it doesn't say anything about `binary_path` being required, but it is if you don't have `Fabric.app` installed or if you don't consume `Fabric` with `CocoaPods`.

**Comment by TKBurner** [comment]
@hborders Thanks for explaining. I just sent this out to the core team. We should look into updating our error messaging.

Hope you have a great weekend coming up 👍

**Comment by TKBurner** [comment]
@hborders Just wanted to follow up that we'd love to see a PR for this error handling. If anyone is interested from the community that'd be 💯
