### ISSUE TITLE
is anyone getting `check_version_conflict': can't activate json-1.8.2, already activated json-1.8.3 (Gem::LoadError)

### ISSUE THREAD

**Issue by cuongta** [fastlane/fastlane#5023]
### Issue Description

All my lanes suddenly stopped working last friday. I'm getting the check_version_conflict err. Is anyone else also seeing this issue? Here's a typical lane:

##### Complete output when running fastlane, including the stack trace and command used

```
/usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2275:in `check_version_conflict': can't activate json-1.8.2, already activated json-1.8.3 (Gem::LoadError)
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1404:in `activate'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym.rb:1:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/actions/gym.rb:54:in `available_options'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/configuration_helper.rb:4:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:188:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:81:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/commands_generator.rb:48:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/commands_generator.rb:236:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/commands_generator.rb:18:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/bin/fastlane:5:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `load'
	from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :test_lane do
        update_info_plist(
            plist_path:'XXX/Info.plist',
            app_identifier:"com.xxx.XXX"
        )

        badge()
        sigh(adhoc: true)
        ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID] # use the UDID of the newly created provisioning profile
        gym(scheme: "Mist", use_legacy_build_api: true) # Build your app - more options available
        crashlytics(notifications: true, api_token: ENV["CRASHLYTICS_API_TOKEN"], build_secret: ENV["CRASHLYTICS_API_SECRET"], debug: true, emails:["xxx@xxx.com","ccc@ccc.com"])
        # sh "your_script.sh"
        # You can also use other beta testing services here
    end
```

### Environment

fastlane version (run `fastlane -v`):

fastlane 1.94.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
Do you have a Gemfile? If so, can you run `bundle update`? If not, can you run `gem cleanup`  and `gem update fastlane`?

**Comment by cuongta** [comment]
That works! Thanks
