### ISSUE TITLE
refresh_dsyms throws iTunesConnectError unable_to_get_build

### ISSUE THREAD

**Issue by janandre** [fastlane/fastlane#5044]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
MacBook-Pro-Jan-2:HsKAmpus-iOS janandre$ fastlane refresh_dsyms --verbose
DEBUG [2016-06-08 10:58:42.39]: Checking if there are any plugins that should be loaded...
INFO [2016-06-08 10:58:42.44]: -------------------------------------------------
INFO [2016-06-08 10:58:42.44]: --- Step: Verifying required fastlane version ---
INFO [2016-06-08 10:58:42.44]: -------------------------------------------------
INFO [2016-06-08 10:58:42.44]: fastlane version valid
INFO [2016-06-08 10:58:42.45]: ------------------------------
INFO [2016-06-08 10:58:42.45]: --- Step: default_platform ---
INFO [2016-06-08 10:58:42.45]: ------------------------------
INFO [2016-06-08 10:58:42.51]: Driving the lane 'ios refresh_dsyms' 🚀
INFO [2016-06-08 10:58:42.52]: ----------------------------
INFO [2016-06-08 10:58:42.52]: --- Step: download_dsyms ---
INFO [2016-06-08 10:58:42.52]: ----------------------------
INFO [2016-06-08 10:58:42.96]: Login to iTunes Connect (xxxxx@googlemail.com)
INFO [2016-06-08 10:58:47.36]: Login successful
INFO [2016-06-08 10:58:47.36]: Looking for dSYM files for de.hs-karlsruhe.hskampus
INFO [2016-06-08 10:58:49.92]: No dSYM URL for 2.0.1 (2.0.1)
INFO [2016-06-08 10:58:50.84]: No dSYM URL for 2.0.2 (2.0.2)
INFO [2016-06-08 10:58:51.76]: No dSYM URL for 2.1 (2.1)
INFO [2016-06-08 10:58:52.44]: No dSYM URL for 2.1.1 (2.1.1)
INFO [2016-06-08 10:58:53.60]: No dSYM URL for 3.0.1 (3.0)
INFO [2016-06-08 10:58:53.96]: No dSYM URL for 3.0 (3.0)
INFO [2016-06-08 10:58:57.04]: 🔑  Successfully downloaded dSYM file for 4.1.0 - 6 to 'de.hs-karlsruhe.hskampus-4.1.0-6.dSYM.zip'
INFO [2016-06-08 10:58:57.34]: -------------------
INFO [2016-06-08 10:58:57.34]: --- Step: slack ---
INFO [2016-06-08 10:58:57.34]: -------------------
INFO [2016-06-08 10:58:58.52]: Successfully sent Slack notification
INFO [2016-06-08 10:58:58.53]: --------------------------
INFO [2016-06-08 10:58:58.53]: --- Step: notification ---
INFO [2016-06-08 10:58:58.53]: --------------------------
WARN [2016-06-08 10:58:58.78]: Variable Dump:
INFO [2016-06-08 10:58:58.78]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios refresh_dsyms", :DSYM_PATHS=>["/Users/janandre/GitHub/HsKAmpus-iOS/de.hs-karlsruhe.hskampus-4.1.0-6.dSYM.zip"]}
ERROR [2016-06-08 10:58:58.78]: unable_to_get_build
INFO [2016-06-08 10:58:58.78]: Successfully generated documentation to path '/Users/janandre/GitHub/HsKAmpus-iOS/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | download_dsyms                      | 14          |
| 4    | slack                               | 1           |
| 5    | notification                        | 0           |
+------+-------------------------------------+-------------+

ERROR [2016-06-08 10:58:58.79]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:174:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	unable_to_get_build
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:548:in `build_details'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/build.rb:131:in `details'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/actions/download_dsyms.rb:44:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/actions/download_dsyms.rb:40:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/actions/download_dsyms.rb:40:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/actions/download_dsyms.rb:36:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/actions/download_dsyms.rb:36:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:223:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/commands_generator.rb:48:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/commands_generator.rb:236:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/commands_generator.rb:18:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.94.1/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :refresh_dsyms do
  download_dsyms                  # Download dSYM files from iTC
  upload_symbols_to_crashlytics   # Upload them to Crashlytics
  clean_build_artifacts           # Delete the local dSYM files
end
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.94.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by Urkman** [comment]
I also have this problem since the last update:

    [17:30:38]: Looking for dSYM files for de.xxx.xxx
    [17:30:40]: No dSYM URL for 2.3.1 (2.3)
    [17:30:42]: No dSYM URL for 3.0.1 (3.0)
    [17:30:42]: No dSYM URL for 3.0.2 (3.0)
    [17:30:42]: No dSYM URL for 3.0.3 (3.0)
    [17:30:43]: No dSYM URL for 8 (3.0)
    [17:30:43]: No dSYM URL for 3.0.4 (3.0)
    [17:30:44]: No dSYM URL for 3.0.5 (3.0)
    [17:30:44]: No dSYM URL for 6 (3.0)
    [17:30:45]: No dSYM URL for 9 (3.0)
    [17:30:47]: 🔑  Successfully downloaded dSYM file for 3.0 - 3.0.6 to 'de.xxx.xxx.dSYM.zip'
    [17:30:48]: No dSYM URL for 5 (3.0)
    [17:30:48]: No dSYM URL for 4 (3.0)
    [17:30:48]: Variable Dump:
    [17:30:48]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"9", :IPA_OUTPUT_PATH=>"/path/to/drf-tv-ios.ipa", :DSYM_OUTPUT_PATH=>"path/to/drf-tv-ios.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"path/to/drf-tv-ios 2016-06-09 16.54.47.xcarchive", :DSYM_PATHS=>["path/to/drf1tv-3.0-3.0.6.dSYM.zip"]}
    [17:30:48]: unable_to_get_build

After that the process stops... so, no upload, no slack notification and so on...

And as I said, before the last update this went fine...

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll take a look.

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/5082, which will be available in the next fastlane release 👍

**Comment by KrauseFx** [comment]
Preparing a new release, expect an update later today https://github.com/fastlane/fastlane/pull/5084 👍
