### ISSUE TITLE
Supply times out everytime and fails to upload APK

### ISSUE THREAD

**Issue by BKAppsmart** [fastlane/fastlane#5046]
### New Issue Checklist

- [x] Updated fastlane to the latest version (0.7.0)
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've read all the available issues in the past regarding this problem and I guess its a similar problem to issue [#3381](https://github.com/fastlane/fastlane/issues/3381) (closed) but something seems different about this...

We use supply and other fastlane tools everyday and they are vital to us, and for the past few days, supply in particular has been working fine, yesterday included, we recently switched from the depracted .p12 key to the .json version instead and all works fine, until today, now everytime we run supply, with our usual command it seems to take 20 minutes and then just Times Out! Everytime, below of-course is output logs and debug info...

There seems to me to be no reason why this is happening and I suspect that it has something to do with the google publisher api as (I could be wrong and please correct me if so) it seems they have been changing a lot of things recently with the way the api works... am I wrong? Also if that is the case where on earth can I get access to change logs or some form of information regarding what they are doing or current system status notifications?

##### Command used...
```
DEBUG=true supply --apk "OUR_APK_LOCATION.apk" --json_key "OUR_JSON_KEY.json" --package_name "PACKAGE_NAME_HERE"
```

##### Output...
```
+-------------------------+-----------------------------------------------------------+
|                              Summary for supply 0.7.0                               |
+-------------------------+-----------------------------------------------------------+
| apk                     | OUR_APK.apk |
| json_key                |JSON_KEY.json                          |
| package_name            | PACKAGENAME                                |
| track                   | production                                                |
| rollout                 | 1.0                                                       |
| skip_upload_apk         | false                                                     |
| skip_upload_metadata    | false                                                     |
| skip_upload_images      | false                                                     |
| skip_upload_screenshots | false                                                     |
+-------------------------+-----------------------------------------------------------+

D, [2016-06-08T12:35:20.833025 #4413] DEBUG -- : Sending HTTP post https://www.googleapis.com/androidpublisher/v2/applications/PACKAGENAME/edits?
D, [2016-06-08T12:35:21.874230 #4413] DEBUG -- : 200
D, [2016-06-08T12:35:21.874400 #4413] DEBUG -- : #<Hurley::Response POST https://www.googleapis.com/androidpublisher/v2/applications/PACKAGENAME/edits == 200 (70 bytes) 1029ms>
D, [2016-06-08T12:35:21.875113 #4413] DEBUG -- : Success - #<Google::Apis::AndroidpublisherV2::AppEdit:0x007fcde4c9eb68
 @expiry_time_seconds="1465389321",
 @id="15180554764376206227">

[12:35:21]: Preparing apk at path 'OUR_APK.apk' for upload...
D, [2016-06-08T12:35:21.876663 #4413] DEBUG -- : Sending upload start command to https://www.googleapis.com/upload/androidpublisher/v2/applications/PACKAGENAME/edits/...
D, [2016-06-08T12:35:22.269497 #4413] DEBUG -- : Upload status active
D, [2016-06-08T12:35:22.269599 #4413] DEBUG -- : Sending upload command to https://www.googleapis.com/upload/androidpublisher/v2/applications/PACKAGENAME/edits/...
D, [2016-06-08T12:40:22.565545 #4413] DEBUG -- : Error - #<Hurley::Timeout: HTTPClient::SendTimeoutError>

D, [2016-06-08T12:40:23.625335 #4413] DEBUG -- : Sending upload query command to https://www.googleapis.com/upload/androidpublisher/v2/applications/PACKAGENAME/edits/...
D, [2016-06-08T12:40:23.810620 #4413] DEBUG -- : Upload status active
D, [2016-06-08T12:40:23.810703 #4413] DEBUG -- : Sending upload command to https://www.googleapis.com/upload/androidpublisher/v2/applications/PACKAGENAME/edits/...
D, [2016-06-08T12:45:23.941714 #4413] DEBUG -- : Error - #<Hurley::Timeout: HTTPClient::SendTimeoutError>

D, [2016-06-08T12:45:25.896649 #4413] DEBUG -- : Sending upload query command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.appsmart.delivery.lupo/edits/...
D, [2016-06-08T12:45:26.093777 #4413] DEBUG -- : Upload status active
D, [2016-06-08T12:45:26.093862 #4413] DEBUG -- : Sending upload command to https://www.googleapis.com/upload/androidpublisher/v2/applications/com.appsmart.delivery.lupo/edits/...
```

_It continues like that for maybe 4 iterations and then it finally gives the output located below..._

##### Error from supply...
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `syswrite': [31m[!] execution expired[0m (Google::Apis::TransmissionError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `do_write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:337:in `write'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient/ssl_socket.rb:92:in `<<'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient/http.rb:582:in `dump_file'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient/http.rb:508:in `dump'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient/http.rb:959:in `dump'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:503:in `block in query'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:501:in `query'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:170:in `query'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient.rb:1238:in `do_get_block'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient.rb:1021:in `block in do_request'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient.rb:1129:in `protect_keep_alive_disconnected'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient.rb:1016:in `do_request'
	from /Library/Ruby/Gems/2.0.0/gems/httpclient-2.7.1/lib/httpclient.rb:858:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_client_adapter.rb:17:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/hurley-0.2/lib/hurley/client.rb:252:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_client_adapter.rb:16:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_client_adapter.rb:16:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/hurley-0.2/lib/hurley/client.rb:122:in `call_with_redirects'
	from /Library/Ruby/Gems/2.0.0/gems/hurley-0.2/lib/hurley/client.rb:89:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/hurley-0.2/lib/hurley/client.rb:71:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/upload.rb:244:in `send_upload_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/upload.rb:274:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/lib/google/apis/core/base_service.rb:267:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.3/generated/google/apis/androidpublisher_v2/service.rb:660:in `upload_apk'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/client.rb:188:in `upload_apk'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:126:in `upload_binary_data'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:107:in `block in upload_binaries'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:106:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:106:in `upload_binaries'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:26:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.44.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
	from /usr/local/bin/supply:23:in `load'
	from /usr/local/bin/supply:23:in `<main>'
```

_Again I want to say that it all worked fine yesterday and I have made no changes at my end_

### Configuration Files

Dont use a config file.

### Environment

fastlane version (1.94.1)
Supply version (0.7.0)

**Comment by asfalcone** [comment]
@BKAppsmart Thanks for submitting this issue. I think you're right, it does seem to be something on the google api side.

One thing you could try is updating the underlying version of the `google-api-client` we currently only require 0.9.3 but they've released a [few versions](https://github.com/google/google-api-ruby-client/releases) since, of course without any release notes that I can find, but seems worth a try!

**Comment by asfalcone** [comment]
Updated: I found the [changelog](https://github.com/google/google-api-ruby-client/blob/master/CHANGELOG.md) for `google-api-client!

**Comment by BKAppsmart** [comment]
Thanks so much for this reply and thank you so much for the change log this will be so useful!
And i've updated thanks to your advice and so far *crosses fingers* ..... it seems to work again. Thanks again!

**Comment by asfalcone** [comment]
Great @BKAppsmart! So glad that you're up and running. There could also have been some transient API issue on Google's part as well. I'm going to close this issue since you're all set now 👍
