### ISSUE TITLE
Adding plugin to existing Fastlane enabled project causes problems

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#5065]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After adding a new, un-edited, plugin using the `add_plugin` command, running `fastlane _lanename_` fails with `kernel_require.rb:126:in `require': cannot load such file -- fastlane/plugin/lyndsey_test (LoadError)`.

##### Complete output when running fastlane, including the stack trace and command used
`> fastlane inhouse`
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- fastlane/plugin/lyndsey_test (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/plugins/plugin_manager.rb:271:in `block in load_plugins'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/plugins/plugin_manager.rb:263:in `each'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/plugins/plugin_manager.rb:263:in `load_plugins'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/commands_generator.rb:17:in `start'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/bin/fastlane:5:in `<top (required)>'
	from /Users/lyndsey.ferguson/.gems/bin/fastlane:23:in `load'
	from /Users/lyndsey.ferguson/.gems/bin/fastlane:23:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.94.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme:"Tests")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Beta") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  lane :inhouse do
    unlock_keychain(path: "enterprise.keychain",
                password: "********",
                set_default: true)

    gym({
      :scheme => "Enterprise",
      :clean => true,
      :export_method => "enterprise",
      :use_legacy_build_api => true,
      :provisioning_profile_path => "InHouse.mobileprovision",
      })
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "AppStore") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

Gemfile:
```ruby
source 'https://rubygems.org'

gem 'xcpretty'
gem 'plist'
gem 'cocoapods'

gem 'fastlane'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
```

Pluginfile (created by Fastlane):
```ruby
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-lyndsey_test', path: '/Users/lyndsey.ferguson/repo/fastlane/fastlane-plugin-lyndsey_test'
```
### Environment

fastlane version (run `fastlane -v`): *1.94.1*

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? *No*

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? *No*

**Comment by mfurtak** [comment]
Hi @lyndsey-ferguson - thanks for the report 👍 

Can you please share the contents of the `Gemfile.lock` local to the project for which you're running `fastlane`? Thanks!

**Comment by lyndsey-ferguson** [comment]
Gemfile.lock:
```ruby
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    babosa (1.0.2)
    cert (1.4.1)
      fastlane_core (>= 0.29.1, < 1.0.0)
      spaceship (>= 0.22.0, < 1.0.0)
    claide (1.0.0)
    cocoapods (1.0.0)
      activesupport (>= 4.0.2)
      claide (>= 1.0.0, < 2z.0)
      cocoapods-core (= 1.0.0)
      cocoapods-deintegrate (>= 1.0.0, < 2.0)
      cocoapods-downloader (>= 1.0.0, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-stats (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.0.0, < 2.0)
      cocoapods-try (>= 1.0.0, < 2.0)
      colored (~> 1.2)
      escape (~> 0.0.4)
      fourflusher (~> 0.3.0)
      molinillo (~> 0.4.5)
      nap (~> 1.0)
      xcodeproj (>= 1.0.0, < 2.0)
    cocoapods-core (1.0.0)
      activesupport (>= 4.0.2)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
    cocoapods-deintegrate (1.0.0)
    cocoapods-downloader (1.0.0)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.0)
    cocoapods-stats (1.0.0)
    cocoapods-trunk (1.0.0)
      nap (>= 0.8, < 2.0)
      netrc (= 0.7.8)
    cocoapods-try (1.0.0)
    colored (1.2)
    commander (4.3.5)
      highline (~> 1.7.2)
    credentials_manager (0.16.0)
      colored
      commander (>= 4.3.5)
      highline (>= 1.7.1)
      security
    deliver (1.12.0)
      credentials_manager (>= 0.16.0, < 1.0.0)
      fastimage (~> 1.6)
      fastlane_core (>= 0.43.1, < 1.0.0)
      plist (~> 3.1.0)
      spaceship (>= 0.26.2, < 1.0.0)
    domain_name (0.5.20160310)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.1.1)
    escape (0.0.4)
    excon (0.45.4)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faraday-cookie_jar (0.0.6)
      faraday (>= 0.7.4)
      http-cookie (~> 1.0.0)
    faraday_middleware (0.10.0)
      faraday (>= 0.7.4, < 0.10)
    fastimage (1.6.8)
      addressable (~> 2.3, >= 2.3.5)
    fastlane (1.89.0)
      addressable (~> 2.3)
      cert (>= 1.4.1, < 2.0.0)
      credentials_manager (>= 0.16.0, < 1.0.0)
      deliver (>= 1.11.2, < 2.0.0)
      fastlane_core (>= 0.43.3, < 1.0.0)
      frameit (>= 2.6.2, < 3.0.0)
      gym (>= 1.6.3, < 2.0.0)
      krausefx-shenzhen (>= 0.14.7)
      match (>= 0.5.0, < 1.0.0)
      multipart-post (~> 2.0.0)
      pem (>= 1.3.1, < 2.0.0)
      pilot (>= 1.5.1, < 2.0.0)
      plist (~> 3.1.0)
      produce (>= 1.1.2, < 2.0.0)
      scan (>= 0.6.1, < 1.0.0)
      screengrab (>= 0.3.2, < 1.0.0)
      sigh (>= 1.8.0, < 2.0.0)
      slack-notifier (~> 1.3)
      snapshot (>= 1.12.1, < 2.0.0)
      spaceship (>= 0.26.2, < 1.0.0)
      supply (>= 0.6.2, < 1.0.0)
      terminal-notifier (~> 1.6.2)
      terminal-table (~> 1.4.5)
      xcodeproj (>= 0.20, < 2.0.0)
      xcpretty (>= 0.2.1)
    fastlane_core (0.45.0)
      babosa
      colored
      commander (= 4.3.5)
      credentials_manager (>= 0.16.0, < 1.0.0)
      excon (~> 0.45.0)
      highline (>= 1.7.2)
      json
      multi_json
      plist (~> 3.1)
      rubyzip (~> 1.1.6)
      terminal-table (~> 1.4.5)
    fourflusher (0.3.1)
    frameit (2.6.2)
      deliver (> 0.3)
      fastimage (~> 1.6.3)
      fastlane_core (>= 0.36.1, < 1.0.0)
      mini_magick (~> 4.5.1)
    fuzzy_match (2.0.4)
    google-api-client (0.9.8)
      addressable (~> 2.3)
      googleauth (~> 0.5)
      httpclient (~> 2.7)
      hurley (~> 0.1)
      memoist (~> 0.11)
      mime-types (>= 1.6)
      representable (~> 2.3.0)
      retriable (~> 2.0)
      thor (~> 0.19)
    googleauth (0.5.1)
      faraday (~> 0.9)
      jwt (~> 1.4)
      logging (~> 2.0)
      memoist (~> 0.12)
      multi_json (~> 1.11)
      os (~> 0.9)
      signet (~> 0.7)
    gym (1.6.3)
      fastlane_core (>= 0.43.1, < 1.0.0)
      plist
      rubyzip (>= 1.1.7)
      terminal-table
      xcpretty (>= 0.2.1)
    highline (1.7.8)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    httpclient (2.8.0)
    hurley (0.2)
    i18n (0.7.0)
    json (1.8.3)
    jwt (1.5.4)
    krausefx-shenzhen (0.14.7)
      commander (~> 4.3)
      dotenv (>= 0.7)
      faraday (~> 0.9)
      faraday_middleware (~> 0.9)
      highline (>= 1.7.2)
      json (~> 1.8)
      net-sftp (~> 2.1.2)
      plist (~> 3.1.0)
      rubyzip (~> 1.1)
      security (~> 0.1.3)
      terminal-table (~> 1.4.5)
    little-plugger (1.1.4)
    logging (2.1.0)
      little-plugger (~> 1.1)
      multi_json (~> 1.10)
    match (0.6.1)
      cert (>= 1.2.8, < 2.0.0)
      credentials_manager (>= 0.13.0, < 1.0.0)
      fastlane_core (>= 0.39.0, < 1.0.0)
      security
      sigh (>= 1.2.2, < 2.0.0)
      spaceship (>= 0.24.0, < 1.0.0)
    memoist (0.14.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_magick (4.5.1)
    minitest (5.9.0)
    molinillo (0.4.5)
    multi_json (1.12.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    nap (1.1.0)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (3.1.1)
    netrc (0.7.8)
    os (0.9.6)
    pem (1.3.1)
      fastlane_core (>= 0.43.1, < 1.0.0)
      spaceship (>= 0.26.2, < 1.0.0)
    pilot (1.8.0)
      credentials_manager (>= 0.3.0)
      fastlane_core (>= 0.41.2, < 1.0.0)
      spaceship (>= 0.27.0, < 1.0.0)
      terminal-table (~> 1.4.5)
    plist (3.1.0)
    produce (1.1.2)
      fastlane_core (>= 0.30.0, < 1.0.0)
      spaceship (>= 0.16.0, < 1.0.0)
    representable (2.3.0)
      uber (~> 0.0.7)
    retriable (2.1.0)
    rouge (1.10.1)
    rubyzip (1.1.7)
    scan (0.7.1)
      fastlane_core (>= 0.36.1, < 1.0.0)
      slack-notifier (~> 1.3)
      terminal-table
      xcpretty (>= 0.2.1)
      xcpretty-travis-formatter (>= 0.0.3)
    screengrab (0.3.2)
      fastlane_core (>= 0.38.0, < 1.0.0)
    security (0.1.3)
    sigh (1.8.0)
      fastlane_core (>= 0.36.1, < 1.0.0)
      plist (~> 3.1)
      spaceship (>= 0.22.0, < 1.0.0)
    signet (0.7.2)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (~> 1.5)
      multi_json (~> 1.10)
    slack-notifier (1.5.1)
    slim (3.0.7)
      temple (~> 0.7.6)
      tilt (>= 1.3.3, < 2.1)
    snapshot (1.12.3)
      fastimage (~> 1.6.3)
      fastlane_core (>= 0.36.1, < 1.0.0)
      plist (~> 3.1.0)
      xcpretty (>= 0.2.1)
    spaceship (0.27.1)
      colored
      credentials_manager (>= 0.9.0)
      faraday (~> 0.9)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 0.9)
      fastimage (~> 1.6)
      multi_xml (~> 0.5)
      plist (~> 3.1)
    supply (0.7.0)
      credentials_manager (>= 0.15.0)
      fastlane_core (>= 0.43.4)
      google-api-client (~> 0.9.1)
    temple (0.7.7)
    terminal-notifier (1.6.3)
    terminal-table (1.4.5)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.4)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uber (0.0.15)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.2)
    xcodeproj (1.0.0)
      activesupport (>= 3)
      claide (>= 1.0.0, < 2.0)
      colored (~> 1.2)
    xcpretty (0.2.2)
      rouge (~> 1.8)
    xcpretty-travis-formatter (0.0.4)
      xcpretty (~> 0.2, >= 0.0.7)

PLATFORMS
  ruby

DEPENDENCIES
  cocoapods (= 1.0.0)
  fastlane (= 1.89.0)
  plist
  slim
  xcpretty

BUNDLED WITH
   1.12.1
```

**Comment by mfurtak** [comment]
Great, thanks!

Can you please run `fastlane install_plugins` local to your fastlane project. Once that completes, we'll want to verify that your path ('/Users/lyndsey.ferguson/repo/fastlane/fastlane-plugin-lyndsey_test') from the `Pluginfile` made it into the `Gemfile.lock`.

I think it may be under-documented, but because you're trying to reference a plugin for testing locally, you'll need to invoke fastlane like this:

```
bundle exec fastlane inhouse
```

The `bundle exec` portion invokes [Bundler](http://bundler.io/) to help `fastlane` resolve your plugin from its non-standard path.

**Comment by lyndsey-ferguson** [comment]
Ok, using the command `bundle exec fastlane install_plugins` worked. And, I can run `fastlane` with `bundle exec fastlane inhouse` with success!

**Comment by mfurtak** [comment]
@lyndsey-ferguson Excellent!

The `bundle exec` part has its benefits! You may find that fastlane starts up considerably faster when invoked via `bundle exec` vs. without it.

Nevertheless, once you publish your plugin to RubyGems, and are able to remove the `path: '/Users/...'` bit from your `Pluginfile`, once you `install_plugins` one more time, I believe you can get away without using `bundle exec` (though you lose the benefits mentioned above).

There is other investigation to make `fastlane` use `bundle exec` without intervention from the user, so keep your eyes open for that news as well.

Cheers :tada:
