### ISSUE TITLE
gym frequently times out when calling xcrun xcodebuild -list

### ISSUE THREAD

**Issue by nevir** [fastlane/fastlane#5071]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I frequently (maybe 50% of the time) see timeouts on `gym` builds.  It always occurs when running `xcrun xcodebuild -list`.  There are also "Skipped SDK" warnings that show up (regardless of whether it times out):

```
[10:08:15]: xcrun xcodebuild -list -workspace '/path/to/Project.xcworkspace'
2016-06-09 10:08:15.315 xcodebuild[4990:13566] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk; its version (7.1) is below required minimum (9.3) for the iphonesimulator platform.
2016-06-09 10:08:15.316 xcodebuild[4990:13566] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk; its version (8.4) is below required minimum (9.3) for the iphonesimulator platform.
2016-06-09 10:08:15.317 xcodebuild[4990:13566] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk; its version (9.0) is below required minimum (9.3) for the iphonesimulator platform.
2016-06-09 10:08:15.317 xcodebuild[4990:13566] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk; its version (9.1) is below required minimum (9.3) for the iphonesimulator platform.
2016-06-09 10:08:15.318 xcodebuild[4990:13566] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk; its version (9.2) is below required minimum (9.3) for the iphonesimulator platform.
2016-06-09 10:08:16.267 xcodebuild[4994:13598] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk; its version (7.1) is below required minimum (9.3) for the iphonesimulator platform.
2016-06-09 10:08:16.268 xcodebuild[4994:13598] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk; its version (8.4) is below required minimum (9.3) for the iphonesimulator platform.
2016-06-09 10:08:16.269 xcodebuild[4994:13598] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk; its version (9.0) is below required minimum (9.3) for the iphonesimulator platform.
2016-06-09 10:08:16.269 xcodebuild[4994:13598] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk; its version (9.1) is below required minimum (9.3) for the iphonesimulator platform.
2016-06-09 10:08:16.269 xcodebuild[4994:13598] [MT] DVTSDK: Skipped SDK /Applications/Xcode-7.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk; its version (9.2) is below required minimum (9.3) for the iphonesimulator platform.

^^^ hangs forever at this point
```

Full gym command:

```
gym --workspace /code/Project.xcworkspace --scheme demo --output_directory /code/build/demo --xcargs '-derivedDataPath "/code/build/demo/_intermediates/ios"' --codesigning_identity 'iPhone Distribution: Team (##########)'
```

**Comment by nevir** [comment]
I've also turned on `--verbose`, hopefully I'll have more details once it fails again

**Comment by KrauseFx** [comment]
Does that happen on your machine or a CI system?

**Comment by nevir** [comment]
On a CI system (Circle CI's OS X machines) - unfortunately a private repo

**Comment by nevir** [comment]
Unfortunately, no additional detail when `--verbose` is on.  The `xcrun` command appears to be what's hanging

**Comment by nevir** [comment]
Looks like it's similar or same to https://github.com/fastlane-old/gym/issues/143

**Comment by funkybaboon** [comment]
I'm getting this error every time I'm running gym through Jenkins. Here's my error with verbose:

> WARN [2016-06-13 16:13:48.87]: xcrun xcodebuild -list -project ./TwitterDemo.xcodeproj
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] xcodebuild -list timed-out after 10 seconds. You might need to recreate the user schemes. You can override the timeout value with the environment variable FASTLANE_XCODE_LIST_TIMEOUT (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.46.3/lib/fastlane_core/project.rb:268:in `rescue in raw_info'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.46.3/lib/fastlane_core/project.rb:264:in `raw_info'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.46.3/lib/fastlane_core/project.rb:296:in `parsed_info'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.46.3/lib/fastlane_core/project.rb:93:in `schemes'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.46.3/lib/fastlane_core/project.rb:101:in `select_scheme'
	from /usr/local/lib/ruby/gems/2.3.0/gems/gym-1.6.3/lib/gym/detect_values.rb:56:in `detect_scheme'
	from /usr/local/lib/ruby/gems/2.3.0/gems/gym-1.6.3/lib/gym/detect_values.rb:24:in `set_additional_default_values'
	from /usr/local/lib/ruby/gems/2.3.0/gems/gym-1.6.3/lib/gym.rb:25:in `config='
	from /usr/local/lib/ruby/gems/2.3.0/gems/gym-1.6.3/lib/gym/manager.rb:4:in `work'
	from /usr/local/lib/ruby/gems/2.3.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:42:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:61:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:15:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/gym-1.6.3/bin/gym:6:in `<top (required)>'
	from /usr/local/bin/gym:23:in `load'
	from /usr/local/bin/gym:23:in `<main>'

**Comment by vpolouchkine** [comment]
@nevir Does that ^^ help?

**Comment by nevir** [comment]
@vpolouchkine sadly nope :(

**Comment by vpolouchkine** [comment]
Does it work as expected locally?

**Comment by nevir** [comment]
Yeah, I haven't experienced any timeouts locally :(

**Comment by dragvs** [comment]
I see such a problem in Travis CI builds too, never locally. On Travis it happens sporadically, I'm getting the following log:
`
...
INFO [2016-06-27 11:23:25.97]: -----------------
INFO [2016-06-27 11:23:25.97]: --- Step: gym ---
INFO [2016-06-27 11:23:25.97]: -----------------
WARN [2016-06-27 11:23:26.23]: xcrun xcodebuild -list -workspace ./Project.xcworkspace

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated`

Btw every build on Travis successfully executes the same command before the fastlane build launches:
`script:
- xcrun xcodebuild -list -workspace ./Project.xcworkspace`

**Comment by dragvs** [comment]
Looks like it's the known issue, same as for `scan` #4059, as `gym` also uses `xcodebuild -showBuildSettings` to read some project settings.
