### ISSUE TITLE
GYM: --codesigning_identity does not escape quotes

### ISSUE THREAD

**Issue by markokeeffe** [fastlane/fastlane#5089]
## Pull Request
https://github.com/fastlane/fastlane/pull/5088

### Issue Description

Gym fails when attempting to build an archive for a team name that has an apostrophe e.g.

```bash
gym --scheme "STL Link" --codesigning_identity "iPhone Distribution: St Leonard's College (XXXXXXXXXX)" --verbose
```

##### Complete output when running fastlane, including the stack trace and command used

```
gym --scheme "App Name" --codesigning_identity "iPhone Distribution: St Leonard's College (XXXXXXXXXX)" --verbose
WARN [2016-06-10 16:12:13.16]: xcrun xcodebuild -list -project './STL Link.xcodeproj'

+----------------------+--------------------------------------------------------+
|                             Summary for gym 1.6.3                             |
+----------------------+--------------------------------------------------------+
| scheme               | STL Link                                               |
| codesigning_identity | iPhone Distribution: St Leonard's College (XXXXXXXXXX) |
| project              | ./STL Link.xcodeproj                                   |
| destination          | generic/platform=iOS                                   |
| output_name          | STL Link                                               |
| clean                | false                                                  |
| output_directory     | .                                                      |
| silent               | false                                                  |
| use_legacy_build_api | false                                                  |
| buildlog_path        | ~/Library/Logs/gym                                     |
+----------------------+--------------------------------------------------------+
+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
|                                                                            Generated Build Command                                                                            |
+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| Option                                                                      | Value                                                                                           |
+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| set -o pipefail &&                                                          |                                                                                                 |
| xcodebuild                                                                  |                                                                                                 |
| -scheme                                                                     | STL Link                                                                                        |
| -project                                                                    | ./STL Link.xcodeproj                                                                            |
| -destination                                                                | generic/platform=iOS                                                                            |
| -archivePath                                                                | /Users/marko/Library/Developer/Xcode/Archives/2016-06-10/STL Link 2016-06-10 16.12.15.xcarchive |
| archive                                                                     |                                                                                                 |
| CODE_SIGN_IDENTITY='iPhone Distribution: St Leonard's College (XXXXXXXXXX)' |                                                                                                 |
| | tee /Users/marko/Library/Logs/gym/STL\ Link-STL\ Link.log | xcpretty        |                                                                                                 |
+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
INFO [2016-06-10 16:12:15.70]: $ set -o pipefail && xcodebuild -scheme 'STL Link' -project './STL Link.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/marko/Library/Developer/Xcode/Archives/2016-06-10/STL Link 2016-06-10 16.12.15.xcarchive' archive CODE_SIGN_IDENTITY='iPhone Distribution: St Leonard's College (XXXXXXXXXX)' | tee /Users/marko/Library/Logs/gym/STL\ Link-STL\ Link.log | xcpretty
INFO [2016-06-10 16:12:15.70]: ▸ sh: -c: line 0: syntax error near unexpected token `('
INFO [2016-06-10 16:12:15.70]: ▸ sh: -c: line 0: `set -o pipefail && xcodebuild -scheme 'STL Link' -project './STL Link.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/marko/Library/Developer/Xcode/Archives/2016-06-10/STL Link 2016-06-10 16.12.15.xcarchive' archive CODE_SIGN_IDENTITY='iPhone Distribution: St Leonard's College (XXXXXXXXXX)' | tee /Users/marko/Library/Logs/gym/STL\ Link-STL\ Link.log | xcpretty'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `set -o pipefail && xcodebuild -scheme 'STL Link' -project './STL Link.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/marko/Library/Developer/Xcode/Archives/2016-06-10/STL Link 2016-06-10 16.12.15.xcarchive' archive CODE_SIGN_IDENTITY='iPhone Distribution: St Leonard's College (XXXXXXXXXX)' | tee /Users/marko/Library/Logs/gym/STL\ Link-STL\ Link.log | xcpretty'
ERROR [2016-06-10 16:12:15.70]: Exit status: 2
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Error building the application - see the log above (FastlaneCore::Interface::FastlaneError)
from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/error_handler.rb:53:in `handle_build_error'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:101:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/command_executor.rb:88:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/command_executor.rb:88:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:97:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:61:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/bin/gym:6:in `<top (required)>'
	from /usr/bin/gym:23:in `load'
	from /usr/bin/gym:23:in `<main>'
```

### Configuration Files

No fastfile, just running gym from CLI

### Environment

fastlane version (run `fastlane -v`): 1.94.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by TKBurner** [comment]
HI @markokeeffe Thanks for reaching out. What happens if you manually escape the '

\'

Thanks!

**Comment by markokeeffe** [comment]
I tried all sorts of combinations of manual escaping without success. It will either bring a literal \ character into the string, or process it in the same manner as explained in the issue. 

Try it for yourself and you should see the results.


Mark

**Comment by TKBurner** [comment]
@markokeeffe Thanks for following up. Can you add a test to cover your PR? That'll help us get this merged faster. Thanks! 👍

**Comment by markokeeffe** [comment]
I can certainly give it a go, never really written any Ruby before!


Mark

**Comment by TKBurner** [comment]
@markokeeffe 👍
