### ISSUE TITLE
uninitialized constant Xcodeproj::Plist when using update_info_plist

### ISSUE THREAD

**Issue by wesbillman** [fastlane/fastlane#5105]
My lane has an `update_info_plist` step to modify some values. With version 1.95.0, I get an uninitialized constant error.

I manually ran `gem install xcodeproj` and was able to correct the error.

```
fastlane app_store
[12:44:57]: -----------------------------
[12:44:57]: --- Step: update_fastlane ---
[12:44:57]: -----------------------------
[12:44:57]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, match, pem, pilot, produce, scan, screengrab, sigh, snapshot, spaceship, supply...
[12:45:05]: Updating deliver from 1.12.0 to 1.13.1 ... 🚀
[12:45:09]: Finished updating deliver
[12:45:10]: Updating fastlane from 1.91.0 to 1.95.0 ... 🚀
[12:45:41]: Finished updating fastlane
[12:45:43]: Updating fastlane_core from 0.45.0 to 0.46.3 ... 🚀
[12:45:43]: Finished updating fastlane_core
[12:45:44]: Updating frameit from 2.6.2 to 2.7.0 ... 🚀
[12:45:44]: Finished updating frameit
[12:45:45]: Updating pilot from 1.8.0 to 1.9.2 ... 🚀
[12:45:45]: Finished updating pilot
[12:45:46]: Updating scan from 0.7.1 to 0.8.0 ... 🚀
[12:45:46]: Finished updating scan
[12:45:47]: Updating spaceship from 0.27.1 to 0.27.2 ... 🚀
[12:45:47]: Finished updating spaceship
[12:45:47]: Cleaning up old versions...
[12:45:49]: fastlane.tools successfully updated! I will now restart myself... 😴
[12:45:50]: -----------------------------
[12:45:50]: --- Step: update_fastlane ---
[12:45:50]: -----------------------------
[12:45:50]: -------------------------------------------------
[12:45:50]: --- Step: Verifying required fastlane version ---
[12:45:50]: -------------------------------------------------
[12:45:50]: fastlane version valid
[12:45:50]: ------------------------------
[12:45:50]: --- Step: default_platform ---
[12:45:50]: ------------------------------
[12:45:52]: Driving the lane 'ios app_store' 🚀
[12:45:53]: -------------------------------
[12:45:53]: --- Step: update_info_plist ---
[12:45:53]: -------------------------------
[12:45:53]: Variable Dump:
[12:45:53]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios app_store"}
[12:45:53]: uninitialized constant Xcodeproj::Plist

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | update_info_plist                   | 0           |
+------+-------------------------------------+-------------+

[12:45:53]: fastlane finished with errors
/Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/actions/update_info_plist.rb:37:in `run': [!] uninitialized constant Xcodeproj::Plist (NameError)
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:181:in `chdir'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:181:in `execute_action'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:162:in `block (2 levels) in parsing_binding'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:239:in `run'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/me/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.95.0/bin/fastlane:5:in `<top (required)>'
	from /Users/me/.rbenv/versions/2.2.3/bin/fastlane:23:in `load'
	from /Users/me/.rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
desc "Build App Store"
lane :app_store do
  update_info_plist(
    plist_path: "app/Info.plist",
    app_identifier: "REDACTED",
    display_name: "REDACTED"
  )
  build "APP", "Distribution", false
  pilot(app_identifier: "REDACTED")
end
```

### Environment

fastlane version (run `fastlane -v`):
`fastlane 1.95.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by TKBurner** [comment]
@wesbillman Thanks for pointing this out. Can you let me know if it persists if you update Fastlane via sudo gem update fastlane? The update_fastlane action doesn't handle non-fastlane dependencies.

Thanks!

**Comment by ncnlinh** [comment]
@TKBurner it happens to me, I updated using `sudo gem update fastlane` to fastlane 1.95. I used 1.91 previously and this action was working fine then

**Comment by TKBurner** [comment]
Hi @ncnlinh Thanks for letting me know. Can you let me know if you are able to navigate to and open your plist through your Xcode project? It looks like there is a linking issue in your build settings.

Thanks! 👍

**Comment by ncnlinh** [comment]
@TKBurner yes, everything was fine in Xcode. I actually had to `sudo gem install xcodeproj` to make it work and now it is working fine.

**Comment by TKBurner** [comment]
@ncnlinh Awesome! Really glad to hear you got up and running. Hope that you have a wonderful day! 👍

**Comment by davidkennedysc** [comment]
Should fastlane depend on a later version of xcodeproj? Just encountered this issue, not sure what the minimum version of xcodeproj I should upgrade to (I'm running old cocoapods so don't want to use the latest one)
