### ISSUE TITLE
Build and upload to appetize fails (Project has embedded WatchKit Extension)

### ISSUE THREAD

**Issue by scottdelly** [fastlane/fastlane#5107]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Using Travis-CI to build and upload to appetize when a PR is created. The build fails with the error:
`Check dependencies`

##### Complete output when running fastlane, including the stack trace and command used
Fastlane is invoked by Danger, a call to `bundle exec danger`
LOTS OF COMPILING then
```
▸ Building staance-app/Staance WatchKit Extension [Staging]
▸ Check Dependencies
** BUILD FAILED **


The following build commands failed:
        Check dependencies
(1 failure)
. Updating the Danger gem might fix the issue.

 #  from Dangerfile:25
 #  -------------------------------------------
 #  require 'fastlane'
 >  result = Fastlane::OneOff.run(action: "build_and_upload_to_appetize",
 #                            parameters: options)
 #  -------------------------------------------
 (Danger::DSLError)
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/interface.rb:139:in `user_error!'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/helper/sh_helper.rb:10:in `sh'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/actions/xcodebuild.rb:247:in `run'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/actions/build_and_upload_to_appetize.rb:13:in `run'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/runner.rb:182:in `block in execute_action'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/runner.rb:181:in `chdir'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/runner.rb:181:in `execute_action'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-1.95.0/lib/fastlane/one_off.rb:44:in `run'
        Dangerfile:25:in `block in parse'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-0.8.2/lib/danger/danger_core/dangerfile.rb:177:in `eval'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-0.8.2/lib/danger/danger_core/dangerfile.rb:177:in `block in parse'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-0.8.2/lib/danger/danger_core/dangerfile.rb:173:in `instance_eval'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-0.8.2/lib/danger/danger_core/dangerfile.rb:173:in `parse'
        /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-0.8.2/lib/danger/commands/runner.rb:56:in `run'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.95.0"

def project_file
  return 'staance-app.xcodeproj'
end

def match_git_url
  return "git@github.com:Staance/iOS-Codesign.git"
end

def goto_project_dir
  folder = File.join(project_file, '../..')

  command = [
    'cd',
    File.expand_path(folder).shellescape,
    '&&'
  ].join(' ')

  return command
end

def dev_project_bundle_ids
  return {"com.staance.staance-app.dev.watchkitapp.watchkitextension" => ".*WatchKit Extension.*",
                            "com.staance.staance-app.dev.watchkitapp" => ".*WatchKit App.*", 
                            "com.staance.staance-app.dev" => "^staance-app$"}
end


def   prod_project_bundle_ids
  return { "com.staance.staance-app.watchkitapp.watchkitextension"=> ".*WatchKit Extension.*",
                              "com.staance.staance-app.watchkitapp"=> ".*WatchKit App.*", 
                              "com.staance.staance-app"=> "^staance-app$"}
end

def update_version_number
  goto_project_dir
  formatDate = DateTime.now.strftime("%Y%m%d%H%M%S")
  command = [
    goto_project_dir,
    'agvtool',
    "new-version -all #{formatDate}"
  ].join(' ')
  sh("#{command}")

  commit_version_bump(
   message: "Bundle Version #{formatDate}",
   xcodeproj: project_file,
   force: true
  )
end

def match_update_dev_devices
  dev_project_bundle_ids.each { |bundle_id, configuration_filter|
    match(git_url: match_git_url,
          type: "development",
          app_identifier: bundle_id,
          force_for_new_devices: true)
  }
end

def match_app_dev
  # Get the latest provisioning profiles from the Dev Portal and 
  # update the project settings for each of the targets
  dev_project_bundle_ids.each { |bundle_id, configuration_filter|
    match(git_url: match_git_url,
          type: "development",
          app_identifier: bundle_id,
          readonly: true)
  }
end

def sign_app_dev
  # Get the latest provisioning profiles from the Dev Portal and 
  # update the project settings for each of the targets
  dev_project_bundle_ids.each { |bundle_id, configuration_filter|
    match(git_url: match_git_url,
          type: "development",
          app_identifier: bundle_id,
          readonly: true)
    sigh( app_identifier: bundle_id, 
          output_path: "/tmp", 
          development: true)
    update_project_provisioning(
          xcodeproj: project_file,
          build_configuration_filter: configuration_filter
    )
  }
end

def build_app_dev
  gym(
    scheme: "Develop",
    configuration: "Develop",
    output_name: "Staance-Develop"
  )
end

def build_app_staging
  gym(
    scheme: "Staging",
    configuration: "Staging",
    output_name: "Staance-Staging"
  )
end

def match_app_prod
  prod_project_bundle_ids.each { |bundle_id, configuration_filter|
    match(git_url: match_git_url,
          type: "appstore",
          app_identifier: bundle_id,
          readonly: true)
  }
end

def sign_app_prod
  # Get the latest provisioning profiles from the Dev Portal and 
  # update the project settings for each of the targets
  prod_project_bundle_ids.each { |bundle_id, configuration_filter|
    match(git_url: match_git_url,
          type: "appstore",
          app_identifier: bundle_id,
          readonly: true)
    sigh( app_identifier: bundle_id, 
          output_path: "/tmp", 
          development: false)
    update_project_provisioning(
          xcodeproj: project_file,
          build_configuration_filter: configuration_filter
    )
  }
end

def build_app_prod
  gym(
    scheme: "Production",
    configuration: "Production",
    output_name: "Staance"
  )
end

def release_notes_from_git
  return sh("git log --pretty=format:'• %s -- by %an %ar (%h)' --since=1.days --no-merges")
end

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services///"
  end

  desc "A lane for testing fastlane"
  lane :demo do
    update_version_number
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Update Provisioning Profiles For New Devices"
  lane :update_devices do
    match_update_dev_devices
  end

  desc "Download Development Provisioning Profiles"
  lane :match_dev do
    match_app_dev
  end

  desc "Download Production Provisioning Profiles"
  lane :match_prod do
    match_app_prod
  end

  desc "Submit a new Staging Build to Fabric"
  lane :fabric_staging do
    ensure_git_branch(branch: 'develop')
    update_version_number
    sign_app_dev
    build_app_staging
    crashlytics(api_token: "", 
                build_secret: "", 
                notes: release_notes_from_git)
    push_to_git_remote #Push updated version info
  end

  desc "Lane for the iOS Nightly Build"
  lane :nightly_build do
    ensure_git_branch(branch: 'develop')
    update_version_number
    sign_app_dev
    build_app_staging
    crashlytics(api_token: "", 
                build_secret: "", 
                notes: release_notes_from_git, 
                groups: "staance-nightly")
    push_to_git_remote #Push updated version info
  end

  desc "Submit a new Production Build to Fabric"
  lane :fabric_prod do
    ensure_git_branch(branch: 'develop')
    update_version_number
    sign_app_prod
    build_app_prod
    crashlytics(api_token: "", 
                build_secret: "", 
                notes: release_notes_from_git)
    push_to_git_remote #Push updated version info
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    ensure_git_branch(branch: 'master')
    update_version_number
    build_app_prod
    deliver(force: true)
    push_to_git_remote #Push updated version info
    # frameit
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    slack(
      message: "Successfully deployed to [lane]"
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
```

Dangerfile:
```ruby
# Sometimes it's a README fix, or something like that - which isn't relevant for
# including in a project's CHANGELOG for example
declared_trivial = pr_title.include? "#trivial"

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn("PR is classed as Work in Progress") if pr_title.include? "[WIP]"

# Warn when there is a big PR
warn("Big PR") if lines_of_code > 500

# Don't let testing shortcuts get into master by accident
fail("fdescribe left in tests") if `grep -r fdescribe specs/`.length > 1
fail("fit left in tests") if `grep -r "fit specs/ `.length > 1

puts "Running fastlane to generate and upload an ipa file..."

options = {
  xcodebuild: {
      workspace: "staance-app.xcworkspace",
      scheme: "Staging"
    }
}

require 'fastlane'
result = Fastlane::OneOff.run(action: "build_and_upload_to_appetize",
                          parameters: options)

require 'fastlane/actions/device_grid/device_grid'

device_grid(
  public_key: result,
  languages: ["en_US", "pt_BR"],
  devices: ["iphone5s", "iphone6", "iphone6splus"]
)
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.95.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
yes
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by KrauseFx** [comment]
We recently pushed a new danger update, can you update, and check the updated device_grid docs? Sorry for the inconvenience

**Comment by scottdelly** [comment]
I've updated to the latest versions of fastlane and danger several times since my last post. Still no luck

According to appetize docs, `xcodebuild -sdk iphonesimulator` should produce an output that is suitable to upload to appetize. However I run into the same error with this, so the issue does not appear to be related to fastlane or danger directly. Rather the command created by fastlane to build for appetize does not work.

It seems to be related to the fact that I have a watchkit extension and that I'm requesting a build for the iphonesimulator sdk. Running fastlane normally, building for Fabric which does not use the `-sdk` flag works just fine.

I've tried several other xcodebuild command variation with -destination instead of -sdk but they either wont build for the same reason, or they produce a non-simulator build that wont work on appetize.

**Comment by scottdelly** [comment]
I found that running:
`xcodebuild -workspace "myapp.xcworkspace" -scheme "Debug" -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' -derivedDataPath "/tmp/fastlane_build"` does produce a build that works on appetize.

The `-destination` argument requires that I specify a destination that is available on the current building machine. And for iOS Simulator, the `name` and `OS` fields are required.  Running `instruments -s devices` will output devices available on the current machine, but not in a format that can be directly piped to the `-destination` argument.

Is it possible to change the build_and_upload_to_appetize action to use `-destination` instead of `-sdk`? Is there a reasonable way to automatically figure out the right destination `name` and `OS` values?
