### ISSUE TITLE
undefined method `log_alert' for FastlaneCore::Helper:Module (NoMethodError)

### ISSUE THREAD

**Issue by arunabhdas** [fastlane/fastlane#5118]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
undefined method `log_alert' for FastlaneCore::Helper:Module (NoMethodError)
##### Complete output when running fastlane, including the stack trace and command used

```
==> fastlane provision
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:36:in `eval': [!] undefined method `log_alert' for FastlaneCore::Helper:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:137:in `method_missing'
	from (eval):2:in `block in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:36:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:36:in `block in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:33:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:33:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:27:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane_manager.rb:12:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:136:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:142:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Minimum version of fastlane
fastlane_version "1.32.1"
 
default_platform :ios
 
platform :ios do
 
  # 1 
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3 
    produce(
      app_name: 'HomeControlApp',
      language: 'English',
      app_version: '1.0',
      sku: '123abc'
    )
    # 4
    cert
    # 5
    sigh(force: true)
  end
 
  error do |lane, exception|
    # This block is called, if there was an error running a specific lane.
  end
 
end
```

### Environment

fastlane version (run `fastlane -v`):
==> fastlane -v
fastlane 1.32.1
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by KrauseFx** [comment]
You're using a really old version of fastlane, please update to the latest version 👍
