### ISSUE TITLE
Deliver fails to activate languages.

### ISSUE THREAD

**Issue by justin** [fastlane/fastlane#5151]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have setup a Git repository with all of our metadata for iTunes Connect.  When it tries to activate the languages, I get an error that there wer errors on the page.

The languages we support are already activated on the iTC portal.

##### Complete output when running fastlane, including the stack trace and command used

```
± deliver run --force=true --verbose
WARN [2016-06-16 18:18:32.85]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: justin@secondgear.io
INFO [2016-06-16 18:18:35.49]: Login to iTunes Connect (justin@secondgear.io)
INFO [2016-06-16 18:18:37.66]: Login successful

+--------------------+----------------------+
|          deliver 1.13.1 Summary           |
+--------------------+----------------------+
| force              | true                 |
| app_identifier     | com.ted.TED          |
| automatic_release  | false                |
| team_id            | 345778               |
| team_name          | TED Conferences      |
| username           | justin@secondgear.io |
| screenshots_path   | ./screenshots        |
| metadata_path      | ./metadata           |
| skip_binary_upload | false                |
| skip_screenshots   | false                |
| skip_metadata      | false                |
| submit_for_review  | false                |
+--------------------+----------------------+

INFO [2016-06-16 18:18:38.12]: Loading './metadata/de-DE/description.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/default/keywords.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/default/release_notes.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/default/support_url.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/default/marketing_url.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/default/name.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/default/privacy_url.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/en-US/description.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/es-ES/description.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/fr-FR/description.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/it/description.txt'...
INFO [2016-06-16 18:18:38.12]: Loading './metadata/ja/description.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/ko/description.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/nl-NL/description.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/pt-BR/description.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/ru/description.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/sv/description.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/tr/description.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/zh-Hans/description.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/zh-Hant/description.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/copyright.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/primary_category.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/secondary_category.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/primary_first_sub_category.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/primary_second_sub_category.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/secondary_first_sub_category.txt'...
INFO [2016-06-16 18:18:38.13]: Loading './metadata/secondary_second_sub_category.txt'...
INFO [2016-06-16 18:18:38.13]: Detected languages: ["de-DE", "en-US", "es-ES", "fr-FR", "it", "ja", "ko", "nl-NL", "pt-BR", "ru", "sv", "tr", "zh-Hans", "zh-Hant", "default", "pt"]
INFO [2016-06-16 18:18:40.32]: Activating languages de-DE, en-US, es-ES, fr-FR, it, ja, ko, nl-NL, pt-BR, ru, sv, tr, zh-Hans, zh-Hant, pt...
/Users/justin/.gem/gems/spaceship-0.27.2/lib/spaceship/tunes/tunes_client.rb:180:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	There are one or more errors on the page.
	from /Users/justin/.gem/gems/spaceship-0.27.2/lib/spaceship/tunes/tunes_client.rb:320:in `block in update_app_version!'
	from /Users/justin/.gem/gems/spaceship-0.27.2/lib/spaceship/tunes/tunes_client.rb:871:in `with_tunes_retry'
	from /Users/justin/.gem/gems/spaceship-0.27.2/lib/spaceship/tunes/tunes_client.rb:313:in `update_app_version!'
	from /Users/justin/.gem/gems/spaceship-0.27.2/lib/spaceship/tunes/app_version.rb:285:in `save!'
	from /Users/justin/.gem/gems/deliver-1.13.1/lib/deliver/upload_metadata.rb:130:in `verify_available_languages!'
	from /Users/justin/.gem/gems/deliver-1.13.1/lib/deliver/upload_metadata.rb:22:in `upload'
	from /Users/justin/.gem/gems/deliver-1.13.1/lib/deliver/runner.rb:58:in `upload_metadata'
	from /Users/justin/.gem/gems/deliver-1.13.1/lib/deliver/runner.rb:21:in `run'
	from /Users/justin/.gem/gems/deliver-1.13.1/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/justin/.gem/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/justin/.gem/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/justin/.gem/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/justin/.gem/gems/fastlane_core-0.46.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/justin/.gem/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/justin/.gem/gems/deliver-1.13.1/lib/deliver/commands_generator.rb:132:in `run'
	from /Users/justin/.gem/gems/deliver-1.13.1/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/justin/.gem/gems/deliver-1.13.1/bin/deliver:5:in `<top (required)>'
	from /Users/justin/.gem/bin/deliver:23:in `load'
	from /Users/justin/.gem/bin/deliver:23:in `<main>'

justin at MacBook-Pro in ~/Development/ios-metadata on master!
± 
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Deliverfile:
```ruby
app_identifier "com.ted.TED"
automatic_release false
team_id "OUR_TEAM_ID"
team_name "OUR_TEAM_NAME"
```

### Environment

deliver version (run `fastlane -v`): deliver 1.13.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No.

**Comment by KrauseFx** [comment]
When you go to iTunes Connect and try to manually change one little thing (e.g. update the description) and click on `Save`, does it work?
Also, could you try manually adding a new language and clicking `Save`? 👍

**Comment by justin** [comment]
Manually adding the languages in iTunes Connect works (albeit it takes forever to process whatever they are processing).

Updating the description on Dutch from no content to just a random string of text also worked.

**Comment by justin** [comment]
fwiw, we also have a tvOS target in the same bundle ID.  Not sure if that's useful info or not. :)

**Comment by croccio** [comment]
get same error. no tvOS, only iPhone and iPad

**Comment by jeffreyjackson** [comment]
Same here.  I can manually add the in iTunes, and then deliver will continue appropriately.
