### ISSUE TITLE
fastlane does not work after ruby upgrade to 2.3

### ISSUE THREAD

**Issue by punksta** [fastlane/fastlane#5190]
- [+] Updated fastlane to the latest version
- [+ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have error on start fastlane after upgrade ruby to 2.3
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'fastlane' (>= 0) among 20 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'

``` 
```
 whereis ruby
>/usr/bin/ruby
 echo $PATH
>/Users/user/Library/android_sdk/tools:/Users/user/Library/android_sdk/platform-tools:/Users/user/.rvm/gems/ruby-2.3.0/bin:/Users/user/.rvm/gems/ruby-2.3.0@global/bin:/Users/user/.rvm/rubies/ruby-2.3.0/bin:/Users/user/.rvm/bin:/Users/user/Library/android_sdk/tools:/Users/user/Library/android_sdk/platform-tools:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/user/.rvm/bin
```

**Comment by jcampbell05** [comment]
Do you use any kind of Ruby Version manager?

**Comment by punksta** [comment]
fixed

**Comment by TKBurner** [comment]
@punksta Awesome! Thanks for updating this thread 👍

**Comment by xserver** [comment]
```
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mail (LoadError)
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from Fastfile:2:in `parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:48:in `eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:48:in `block in parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:37:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:37:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:27:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/lane_manager.rb:12:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.51.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

@punksta 
```
fastlane --version
fastlane 1.102.0

ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

Fastlane must run in ruby 2.0 ?
I need install ruby 2.0 ?

**Comment by TKBurner** [comment]
@xserver What OS are you using? Were you able to get up and running? Thanks!

**Comment by KrauseFx** [comment]
@xserver what do you have in your Fastfile on line 2? You didn't share your Fastfile, but it seems like you have an error there

**Comment by xserver** [comment]
@TKBurner 
macOS 10.12 & Ruby 2.3 Error.
macOS 10.12 & Ruby 2.0 Success.

@KrauseFx 
line 2 are `require 'mail'`
Ruby 2.3 cannot load such file -- mail (LoadError)

so, the error from require mail (Ruby 2.3).

**Comment by TKBurner** [comment]
@xserver Can you install fastlane?` sudo gem install fastlane`?

**Comment by xserver** [comment]
using `gem install mail` resolve it.

The Error From Ruby can not load 'mail'

**Comment by TKBurner** [comment]
@xserver Awesome! So glad to hear you got up and running 👍

**Comment by xserver** [comment]
@TKBurner fastlane is so beautiful.
