### ISSUE TITLE
No identity found / Commander error

### ISSUE THREAD

**Issue by afestein** [fastlane/fastlane#5272]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When trying to run the device lane I receive several errors and I am unsure which is the most significant. Of particular note: 

`iPhone Developer: Tim Lindsay (69GNYAQJKU): no identity found`

`bundler: failed to load command: fastlane (/Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/fastlane)`

`NoMethodError: undefined method `error' for Commander::UI:Module`

I've removed and reinstalled certificates, and cleared my `~/Library/MobileDevice/Provisioning Profiles` directory several times. I also tried `match nuke development` to no avail. 

Any help would be greatly appreciated.

##### Complete output when running fastlane, including the stack trace and command used

When running the command `fastlane device --env development`

```
[15:59:57]: Loading from './fastlane/.env.development'
[15:59:57]: Driving the lane 'device' 🚀
[15:59:57]: -------------------
[15:59:57]: --- Step: match ---
[15:59:57]: -------------------

+-----------------------+------------------------------------------------+
|                        Summary for match 0.6.1                         |
+-----------------------+------------------------------------------------+
| app_identifier        | com.yesheis.yhi.staging                        |
| force_for_new_devices | true                                           |
| type                  | development                                    |
| git_url               | git@github.com:cvcnetwork/ios-certificates.git |
| git_branch            | master                                         |
| username              | devwebaccounts@cvglobal.co                     |
| keychain_name         | login.keychain                                 |
| readonly              | false                                          |
| verbose               | false                                          |
| force                 | false                                          |
| shallow_clone         | false                                          |
| skip_docs             | false                                          |
+-----------------------+------------------------------------------------+

[15:59:57]: Cloning remote git repo...
[16:00:07]: 🔓  Successfully decrypted certificates repo
[16:00:07]: Verifying that the certificate and profile are still valid on the Dev Portal...
[16:00:16]: Installing certificate...
[16:00:19]: Installing provisioning profile...

+----------------------+------------------------------------------+
|                 Installed Provisioning Profile                  |
+----------------------+------------------------------------------+
| App Identifier       | com.yesheis.yhi.staging                  |
| Type                 | development                              |
| UUID                 | b7196561-cc9e-4088-aa39-2205ca3f7eb7     |
| Environment Variable | sigh_com.yesheis.yhi.staging_development |
+----------------------+------------------------------------------+

[16:00:20]: All required keys, certificates and provisioning profiles are installed 🙌
[16:00:20]: 🔒  Successfully encrypted certificates repo
[16:00:20]: Setting Provisioning Profile type to 'development'
[16:00:20]: ----------------------------------------------------------------
[16:00:20]: --- Step: RUBYMOTION_ENV=development bundle exec rake device ---
[16:00:20]: ----------------------------------------------------------------
[16:00:20]: $ RUBYMOTION_ENV=development bundle exec rake device
[16:00:20]: ▸ (in /Users/afestein/code/yesheis-motion-ios)
[16:00:22]: ▸      Build ./build/iPhoneOS-9.0-Development
[16:00:23]: ▸     Create ./build/iPhoneOS-9.0-Development/yesDEVis.app/Info.plist
[16:00:23]: ▸       Copy ./resources/GoogleService-Info.plist
[16:00:23]: ▸     Create ./build/iPhoneOS-9.0-Development/yesDEVis.app/embedded.mobileprovision
[16:00:23]: ▸   Codesign ./build/iPhoneOS-9.0-Development/yesDEVis.app
[16:00:24]: ▸ iPhone Developer: Tim Lindsay (69GNYAQJKU): no identity found
[16:00:24]: ▸ rake aborted!
[16:00:24]: ▸ Command failed with status (1): [CODESIGN_ALLOCATE="/Applications/Xcode.app...]
[16:00:24]: ▸ /Library/RubyMotion/lib/motion/project/template/ios/builder.rb:98:in `codesign'
[16:00:24]: ▸ /Library/RubyMotion/lib/motion/project/app.rb:86:in `codesign'
[16:00:24]: ▸ /Library/RubyMotion/lib/motion/project/template/ios.rb:76:in `block (2 levels) in <top (required)>'
[16:00:24]: ▸ /Users/afestein/.rbenv/versions/2.2.3/bin/bundle:23:in `load'
[16:00:24]: ▸ /Users/afestein/.rbenv/versions/2.2.3/bin/bundle:23:in `<main>'
[16:00:24]: ▸ Tasks: TOP => device => archive => build:device
[16:00:24]: ▸ (See full trace by running task with --trace)
[16:00:24]: Variable Dump:
[16:00:24]: {:ENVIRONMENT=>"development", :PLATFORM_NAME=>nil, :LANE_NAME=>"device", :SIGH_PROFILE_TYPE=>"development"}
[16:00:24]: Exit status of command 'RUBYMOTION_ENV=development bundle exec rake device' was 1 instead of 0.
(in /Users/afestein/code/yesheis-motion-ios)
     Build ./build/iPhoneOS-9.0-Development
    Create ./build/iPhoneOS-9.0-Development/yesDEVis.app/Info.plist
      Copy ./resources/GoogleService-Info.plist
    Create ./build/iPhoneOS-9.0-Development/yesDEVis.app/embedded.mobileprovision
  Codesign ./build/iPhoneOS-9.0-Development/yesDEVis.app
iPhone Developer: Tim Lindsay (69GNYAQJKU): no identity found
rake aborted!
Command failed with status (1): [CODESIGN_ALLOCATE="/Applications/Xcode.app...]
/Library/RubyMotion/lib/motion/project/template/ios/builder.rb:98:in `codesign'
/Library/RubyMotion/lib/motion/project/app.rb:86:in `codesign'
/Library/RubyMotion/lib/motion/project/template/ios.rb:76:in `block (2 levels) in <top (required)>'
/Users/afestein/.rbenv/versions/2.2.3/bin/bundle:23:in `load'
/Users/afestein/.rbenv/versions/2.2.3/bin/bundle:23:in `<main>'
Tasks: TOP => device => archive => build:device
(See full trace by running task with --trace)


+------+----------------------------------------------------+-------------+
|                            fastlane summary                             |
+------+----------------------------------------------------+-------------+
| Step | Action                                             | Time (in s) |
+------+----------------------------------------------------+-------------+
| 1    | match                                              | 23          |
| 2    | RUBYMOTION_ENV=development bundle exec rake device | 3           |
+------+----------------------------------------------------+-------------+

[16:00:24]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:99:in `rescue in show_github_issues': undefined method `error' for Commander::UI:Module (NoMethodError)
	from /Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:89:in `show_github_issues'
	from /Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:43:in `rescue in run!'
	from /Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:50:in `run!'
	from /Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.96.0/lib/fastlane/commands_generator.rb:244:in `run'
	from /Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.96.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.96.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/afestein/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.96.0/bin/fastlane:5:in `<top (required)>'
	from /Users/afestein/.rbenv/versions/2.2.3/bin/fastlane:23:in `load'
	from /Users/afestein/.rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :device do
  match(
    app_identifier: ENV['IDENTIFIER'],
    force_for_new_devices: true,
    type: 'development'
  )
  sh "RUBYMOTION_ENV=development bundle exec rake device"
end
```

Matchfile: 
```
git_url "git@github.com:cvcnetwork/ios-certificates.git"

type "development"
```

### Environment

fastlane version (run `fastlane -v`): 
1.96.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
No, however this throws the same error.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? 
Yes, rbenv.

**Comment by KrauseFx** [comment]
Thanks for reporting this, I just pushed a fix: https://github.com/fastlane/fastlane/pull/5274

**Comment by KrauseFx** [comment]
This doesn't fix your actual error, being 
```
[16:00:20]: ----------------------------------------------------------------
[16:00:20]: --- Step: RUBYMOTION_ENV=development bundle exec rake device ---
[16:00:20]: ----------------------------------------------------------------
[16:00:20]: $ RUBYMOTION_ENV=development bundle exec rake device
[16:00:20]: ▸ (in /Users/afestein/code/yesheis-motion-ios)
[16:00:22]: ▸      Build ./build/iPhoneOS-9.0-Development
[16:00:23]: ▸     Create ./build/iPhoneOS-9.0-Development/yesDEVis.app/Info.plist
[16:00:23]: ▸       Copy ./resources/GoogleService-Info.plist
[16:00:23]: ▸     Create ./build/iPhoneOS-9.0-Development/yesDEVis.app/embedded.mobileprovision
[16:00:23]: ▸   Codesign ./build/iPhoneOS-9.0-Development/yesDEVis.app
[16:00:24]: ▸ iPhone Developer: Tim Lindsay (69GNYAQJKU): no identity found
[16:00:24]: ▸ rake aborted!
```
Your rake task doesn't work 👍

**Comment by KrauseFx** [comment]
Please update using `sudo gem update fastlane_core` or `bundle update` 🚀

**Comment by afestein** [comment]
Thanks @KrauseFx - that makes it much easier to troubleshoot the issue at hand 😄
