### ISSUE TITLE
Fastlane encoding error after update 1.89 -> 1.97

### ISSUE THREAD

**Issue by ColCh** [fastlane/fastlane#5282]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

It just fails after updating it to latest version

```
$ fastlane ios build
Appfile: DEPRECATED issuer: use json_key_file instead

Looking for related GitHub issues on fastlane/fastlane...

➡️  No value found for 'username' when try to Jenkins Integration with Fastlane. But the lane run successful via SSH.
   https://github.com/fastlane/fastlane/issues/4785 [closed] 2 💬
   5 weeks ago

➡️  Running fastlane from run script phase - encoding problem
   https://github.com/fastlane/fastlane/issues/1239 [closed] 5 💬
   5 weeks ago

/Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/fast_file.rb:20:in `tr!': [!] incompatible character encodings: US-ASCII and UTF-8 (Encoding::CompatibilityError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/fast_file.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/lane_manager.rb:12:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

ERROR: Build failed: exit status 1
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.68.0"

default_platform :ios

###################
# iOS
###################
platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Builds and signs iOS app"
  lane :build do
    gym(
      project: "ios/Mastermind.xcodeproj",
      scheme: "Mastermind",
      export_method: "development",
      archive_path: "./Mastermind.xcarchive"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide

    pilot(
      ipa: "Mastermind Code Breaker.ipa",
      distribute_external: false
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    deliver(
      skip_binary_upload: false,
      skip_metadata: false,
      force: true,
      submit_for_review: false, # Submit the new version for Review after uploading everything
      automatic_release: false  # Should the app be automatically released once it's approved?
    )
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

###################
# Android
###################
platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Builds and signs Android app"
  lane :build do
    gradle(task: "assembleRelease", project_dir: "android")
    FileUtils.cp lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH], "../Mastermind.apk", :verbose => true
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    #crashlytics
    supply(track: "beta", metadata_path: "fastlane/metadata/android", apk: "Mastermind.apk")

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Submit a new Alpha Build to Google Play"
  lane :alpha do
    supply(track: "alpha", metadata_path: "fastlane/metadata/android", apk: "Mastermind.apk")
  end

  desc "Deploy a new version to the Google Play"
  lane :production do
    supply(track: "production", metadata_path: "fastlane/metadata/android", apk: "Mastermind.apk")
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
```

### Environment

May be important - I'm running in OS X 10.10

fastlane version (run `fastlane -v`): 1.97.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? __NO__

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? __NO__

__AND__, It was just __fine__ on *1.89.0*

**Comment by TKBurner** [comment]
Hi @ColCh! Can you also include your Appfile? Thanks!

**Comment by ColCh** [comment]
Sure, sorry for the delay.

It contains some private info, I've replaced it with foo-bar's
```ruby
###################
# iOS
###################
app_identifier "com.app.identifier" # The bundle identifier of your app
apple_id "some@apple.id" # Your Apple email address

team_id "FOOBAR"  # Developer Portal Team ID

###################
# Android
###################
#FIXME: this is deprecated and we should use json file
issuer "company@some-long-string-of-ids"

package_name "com.there.ispackageid" # e.g. com.krausefx.app


# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```

**Comment by ColCh** [comment]
Additional info:
Ruby version :  `ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]`
LANG: `en_US.UTF-8`
AppFile, Fastfile encoding both `UTF-8`.

With this patch on I live system (for this file: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/fast_file.rb#L12...L20):
```diff
    # @return The runner which can be executed to trigger the given actions
    def initialize(path = nil)
      return unless (path || '').length > 0
      UI.user_error!("Could not find Fastfile at path '#{path}'") unless File.exist?(path)
      @path = File.expand_path(path)
      content = File.read(path)

+      UI.error content.encoding

      # From https://github.com/orta/danger/blob/master/lib/danger/Dangerfile.rb
      if content.tr!('“”‘’‛', %(""'''))
```

That's what I get for that line:
* in gui terminal : `[13:56:37]: UTF-8`
* in gitlab ci runner: `[14:06:23]: US-ASCII`

However, this is not a fastlane's error, it's mine or gitlab ci. Closing now, good luck!

**Comment by ColCh** [comment]
# FOR PEOPLE WHO WILL SEARCH:

I have no locale defined at all.

Related thing : http://apple.stackexchange.com/questions/21096/where-does-lang-variable-gets-set-in-mac-os-x

👍 👍 👍
