### ISSUE TITLE
projectNotLinked Issue 

### ISSUE THREAD

**Issue by dipskakadiya** [fastlane/fastlane#5283]
Hey,

I am trying to upload android app. As I already  liked Google Play Developer API with Google Play Developer Console but i still getting error
```
`check_status': [!] projectNotLinked: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console. (Google::Apis::ClientError)
```

![screen shot 2016-07-01 at 2 46 25 am](https://cloud.githubusercontent.com/assets/2979084/16504610/7c5afff8-3f36-11e6-9475-9aac30cd5d55.png)

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by dipskakadiya** [comment]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am trying to upload android app. As I already  liked Google Play Developer API with Google Play Developer Console but i still getting error

![screen shot 2016-07-01 at 2 46 25 am](https://cloud.githubusercontent.com/assets/2979084/16504610/7c5afff8-3f36-11e6-9475-9aac30cd5d55.png)

##### Complete output when running fastlane, including the stack trace and command used
```
dips:android dipesh$ supply

+-------------------------+------------------------------------------------------------------------+
|                                     Summary for supply 0.7.0                                     |
+-------------------------+------------------------------------------------------------------------+
| package_name            | com.ionicframework.starter                                             |
| track                   | production                                                             |
| rollout                 | 1.0                                                                    |
| json_key                | /Users/dipesh/Documents/AppBoss/DemoApp/platforms/android/Google Pl... |
| skip_upload_apk         | false                                                                  |
| skip_upload_metadata    | false                                                                  |
| skip_upload_images      | false                                                                  |
| skip_upload_screenshots | false                                                                  |
+-------------------------+------------------------------------------------------------------------+


Looking for related GitHub issues on fastlane/fastlane...

➡️  projectNotLinked Issue 
   https://github.com/fastlane/fastlane/issues/5283 [open] 1 💬
   12 hours ago

/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.9/lib/google/apis/core/http_command.rb:211:in `check_status': [!] projectNotLinked: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console. (Google::Apis::ClientError)
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.9/lib/google/apis/core/api_command.rb:102:in `check_status'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.9/lib/google/apis/core/http_command.rb:179:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.9/lib/google/apis/core/http_command.rb:286:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.9/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.9/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.9/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.9/lib/google/apis/core/base_service.rb:345:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.9/generated/google/apis/androidpublisher_v2/service.rb:209:in `insert_edit'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/client.rb:81:in `begin_edit'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:6:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
	from /usr/local/bin/supply:23:in `load'
	from /usr/local/bin/supply:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.97.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by dipskakadiya** [comment]
@vpolouchkine Please look into it asap.

**Comment by asfalcone** [comment]
@dipskakadiya Is this app already in Google Play console? `supply` is only used to update existing apps so you'll need to drag the APK into the console to get started. Let me know if this resolves your issue 👍

**Comment by dipskakadiya** [comment]
@asfalcone 
Thanks for follow up. I want to upload first app automatically.
There any way to upload first app using api?

**Comment by asfalcone** [comment]
No, the google api doesn't allow that programmatically unfortunately.
