### ISSUE TITLE
unable to play appaloosa with ruby 2.0.0

### ISSUE THREAD

**Issue by sylvek** [fastlane/fastlane#5318]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

i try to upload an apk from fastlane with appaloosa plugin.

##### Complete output when running fastlane, including the stack trace and command used

```
bundler: failed to load command: fastlane (/MY_HOME/.gem/ruby/2.0.0/bin/fastlane)
NameError: [31m[!] uninitialized constant Fastlane::Actions::AppaloosaAction::Net[0m
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/appaloosa.rb:27:in `upload_on_s3'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/appaloosa.rb:17:in `get_binary_link'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/appaloosa.rb:10:in `run'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:182:in `block in execute_action'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `chdir'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `execute_action'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/fast_file.rb:140:in `method_missing'
  Fastfile:23:in `block (2 levels) in parsing_binding'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:50:in `block in execute'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `chdir'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `execute'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/command_line_handler.rb:30:in `handle'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:244:in `run'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:20:in `start'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/gems/fastlane-1.97.2/bin/fastlane:5:in `<top (required)>'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/bin/fastlane:23:in `load'
  /home/jenkins/workspace/taxidriver-android-appaloosa/.gem/ruby/2.0.0/bin/fastlane:23:in `<top (required)>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.97.2"

default_platform :android

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Appaloosa"
  lane :beta do |options|
    gradle(
      task: "#{options[:task]}",
      properties: {
          "keyStore"  => "#{options[:keystore]}",
          "storePass" => "#{options[:password]}",
          "keyPass"   => "#{options[:password]}",
          "alias"     => "#{options[:password]}"
      })
    ENV["FL_APPALOOSA_BINARY"] = lane_context[Actions::SharedValues::GRADLE_APK_OUTPUT_PATH]
    appaloosa(group_ids: "4642", screenshots: "")
  end
end
```

### Environment

fastlane version (run `fastlane -v`):
1.97.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by bartverhavert** [comment]
@sylvek what did you do to make it work on ruby 2.1.0? I'm running ruby 2.3.1 using rbenv with fastlane at 1.105.0 and I'm having the same issue: `uninitialized constant Fastlane::Actions::AppaloosaAction::Net`

Any ideas?

**Comment by sylvek** [comment]
hi @bartverhavert , nothing special .. i just upgraded the version.
presently i use it everyday and it works like a charm

this is my own code…
```
desc "release a new version"
  lane :release do |options|
    gradle(task: "clean")
    gradle(
      task: options[:task],
      properties: {
          "keyStore"  => options[:keystore],
          "storePass" => options[:password],
          "keyPass"   => options[:password],
          "alias"     => options[:password]
      })
    if options[:to_appaloosa]
      lane_context[Actions::SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS].reject { |apk| apk[/-unaligned/] }.each do |release|
        puts "deploy #{release}"
        appaloosa(binary: release, group_ids: "4642", screenshots: "")
      end
    end
  end
```

Gemfile

```
source "https://rubygems.org"
ruby '2.1.0'
gem 'fastlane', '>= 1.97.1'
```

**Comment by bartverhavert** [comment]
Hi @sylvek, thanks for the quick response. I've updated ruby and fastlane but that didn't seem to fix it. I'll keep looking. Thanks anyway!

**Comment by bartverhavert** [comment]
FYI, it was a stupid rookie mistake. Even though `ruby -v` showed I was on 2.3.1 and I had installed fastlane for ruby 2.3.1 as well, running the fastlane command would still use the fastlane installation on the default ruby installation (2.0.0). I fixed it by removing all fastlane installations in the default ruby installation, so when now running `fastlane`, the fastlane installation of ruby 2.3.1 was used.

**Comment by sylvek** [comment]
:+1:

Le mar. 25 oct. 2016 11:39, Bart Verhavert <notifications@github.com> a
écrit :

**Comment by TKBurner** [comment]
@bartverhavert Awesome! Are you still running into your issue at this point or did the update fix things? Thanks!

**Comment by bartverhavert** [comment]
Hi @TKBurner, updating Fastlane and Ruby to their latest versions, as well as making sure the Fastlane installation of the rbenv managed Ruby version was used, made it all work. Thanks!

**Comment by TKBurner** [comment]
@bartverhavert Awesome! So glad to hear you got up and running 👍
