### ISSUE TITLE
Unable to patch `PackageApplication` script bundled in Xcode 8 beta.

### ISSUE THREAD

**Issue by rvandenbroek-aa** [fastlane/fastlane#5389]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When gym has `use_legacy_build_api` set to true, Xcode's `PackageApplication` perl script is patched to be able to create the IPA from the archive. In the new Xcode 8 beta the `PackageApplication` script got a small update which causes the md5 check on the script to fail and to cause gym to abort with the error `[!] Unable to patch the `PackageApplication` script bundled in Xcode. This is not supported.`

##### Complete output when running fastlane, including the stack trace and command used
Running gym with the Xcode 8 beta like so:

```
env DEVELOPER_DIR="/Applications/Xcode-beta.app" gym --verbose
```

causes the following output:

```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Unable to patch the `PackageApplication` script bundled in Xcode. This is not supported. (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/xcodebuild_fixes/package_application_fix.rb:23:in `block in patch_package_application'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/xcodebuild_fixes/package_application_fix.rb:13:in `patch_package_application'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/generators/package_command_generator_legacy.rb:14:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/generators/package_command_generator.rb:16:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:118:in `package_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:61:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/bin/gym:6:in `<top (required)>'
	from /usr/local/bin/gym:23:in `load'
	from /usr/local/bin/gym:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
opt_out_usage
skip_docs
fastlane_version "1.97.2"

default_platform :ios
platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :beta do
    sh 'rm -rf test_output'
    sh 'rm -rf report.xml'
    sh 'rm -rf build'

    ensure_git_status_clean
    increment_build_number
    build = get_build_number(xcodeproj: "Example.xcodeproj")

    gym(
      output_name: "Example-" + build + ".ipa",
      scheme: "Example"
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
```

Gymfile:
```ruby
clean true
silent true
sdk "iphoneos10.0"
use_legacy_build_api true
configuration "Debug"
include_bitcode true
output_directory "./fastlane/build"
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.97.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by rvandenbroek-aa** [comment]
Please see PR https://github.com/fastlane/fastlane/pull/5391 for a possible solution.

**Comment by tsheaff** [comment]
I'm experiencing the same issue.

**Comment by mfurtak** [comment]
It looks like this has been addressed with https://github.com/fastlane/fastlane/pull/5391, which should be shipped with the next release.

**Comment by tsheaff** [comment]
yes it has this solves the issue for me.

**Comment by TKBurner** [comment]
@rvandenbroek-aa Let me know if the PR resolves your issue! Thanks for pointing this out 👍

**Comment by mfurtak** [comment]
It looks like this went out with `gym` 1.7.0 👍
