### ISSUE TITLE
Fastlane still use old Apple account instead of new Apple Account 

### ISSUE THREAD

**Issue by biolinh** [fastlane/fastlane#5400]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### Issue Description
I am trying to let deliver, Appfile can communicate with many Developer Account which depend on the value of variables I  input in .env file. However, it doesn't work as I expect. 
In the first time, I use test@xyz.com as an Apple account
```
TEAM_NAME="XYZ (OPERATIONS) PTY LTD"
TEAM_ID=<APPLE_ID>
DELIVER_TEAM_ID=<ITUNES_ID>
MATCH_GIT_BRANCH=XYZ

CODE_SIGN_IDENTITY=iPhone Distribution: XYZ (OPERATIONS) PTY LTD
APPLE_ACCOUNT=test@xyz.com
FASTLANE_PASSWORD=mypassword
KEYCHAIN_PASSWORD=keychainpassword
```
In the next build,  I input another account linh@xyz.com
```
TEAM_NAME="XYZ (OPERATIONS) PTY LTD"
TEAM_ID=<APPLE_ID>
DELIVER_TEAM_ID=<ITUNES_ID>
MATCH_GIT_BRANCH=XYZ

CODE_SIGN_IDENTITY=iPhone Distribution: XYZ (OPERATIONS) PTY LTD
APPLE_ACCOUNT=test@xyz.com
FASTLANE_PASSWORD=mypassword
KEYCHAIN_PASSWORD=keychainpassword

```
But, It still receive the value of the first input variables.

##### 
When I run Fastlane with the Jenkins, I get the error: 
```
/bin/bash -l /Users/Jenkins/.jenkins/tmp/hudson2903648925353412758.sh
[31mThe login credentials for 'test@xyz.com' seem to be wrong[0m
Do you want to re-enter your password? (y/n)
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal

/Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:961:in `get_response': undefined method `chr' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
	from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:227:in `agree'
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.16.0/lib/credentials_manager/account_manager.rb:39:in `invalid_credentials'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/client.rb:229:in `rescue in login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/client.rb:224:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/client.rb:88:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Volumes/hdd2/Jenkins_FT_WS/RX-JMango360_2.1.x_brandedapp_fastlane/fastlane/actions/itunes_id.rb:4:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/actions/actions_helper.rb:81:in `block in load_external_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/actions/actions_helper.rb:80:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/actions/actions_helper.rb:80:in `load_external_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane.rb:35:in `load_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/commands_generator.rb:16:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

```

I try to run it in command line:

```
$ fastlane upload
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
```
Yes, It automatic use test@xyz.com 

Then, I check in Keychain access, I saw deliver.test@xyz.com in Passwords. I deleted it. 
After that, running fastlane again in command line, It returns as below:
```
fastlane upload
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` env variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for test@xyz.com): 
Password (for test@xyz.com): 
```
### Configuration Files

Fastfile:
```
  desc "Upload Screenshot to Apple Store"
  lane :upload do
    # snapshot
    deliver(skip_metadata: "true", submit_for_review: "false", screenshots_path: ENV["SCREENSHOTS_PATH"], skip_binary_upload: "true")
  end
```

DeliverFile

```
app_identifier ENV["BUNDLE_IDENTIFIER"] 
username ENV["APPLE_ACCOUNT"]
name ENV["APP_NAME"]
team_name ENV["TEAM_NAME"]
app_version ENV["BUNDLE_VERSION"]
team_id ENV["DELIVER_TEAM_ID"]
```

Appfile
```
app_identifier ENV["BUNDLE_IDENTIFIER"] 
apple_id ENV["APPLE_ACCOUNT"]
team_name ENV["TEAM_NAME"]
team_id ENV["TEAM_ID"]
```

### Environment

fastlane version (run `fastlane -v`): 1.97.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? y

fastlane-credentials --version: CredentialsManager 0.16.0

**Comment by ppengotsu** [comment]
Please confirm existing "fastlane/Deliverfile" file
if existing file , please delete "fastlane/Deliverfile" file or change username on file

**Comment by TKBurner** [comment]
@biolinh Did @ppengotsu suggestion help? Thanks!

**Comment by biolinh** [comment]
Thank you for all support. I already fixed it. It is because of itunes_id.rbscript in Action folder when I try to [migrate existing certificate to fastlnae match](http://macoscope.com/blog/simplify-your-life-with-fastlane-match/) . Therefore, when fastlane run, It call this account from it.

**Comment by TKBurner** [comment]
@biolinh Awesome! Really glad to hear you got up and running. Hope you have a wonderful weekend! 👍
