### ISSUE TITLE
frameit strings file quote 

### ISSUE THREAD

**Issue by adriantofan** [fastlane/fastlane#5404]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When using strings file with frameit, I have to escape each use of  '  otherwise it gives me the following error : `incompatible character encodings: UTF-8 and ASCII-8BIT`

##### Complete output when running fastlane, including the stack trace and command used

```
ERROR [2016-07-15 17:35:28.72]: incompatible character encodings: UTF-8 and ASCII-8BIT
ERROR [2016-07-15 17:35:28.72]: Backtrace:
	/usr/local/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/shell.rb:18:in `run'
	/usr/local/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:92:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:40:in `new'
	/usr/local/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:504:in `mogrify'
	/usr/local/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:384:in `combine_options'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/editor.rb:250:in `block in build_title_images'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/editor.rb:232:in `each'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/editor.rb:232:in `build_title_images'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/editor.rb:171:in `put_title_into_background'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/editor.rb:102:in `complex_framing'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/editor.rb:17:in `frame!'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/screenshot.rb:76:in `frame!'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/runner.rb:34:in `block in run'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/runner.rb:26:in `each'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/runner.rb:26:in `run'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:36:in `block (2 levels) in run'
	/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:61:in `run'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/lib/frameit/commands_generator.rb:12:in `start'
	/usr/local/lib/ruby/gems/2.2.0/gems/frameit-2.7.0/bin/frameit:7:in `<top (required)>'
	/usr/local/bin/frameit:23:in `load'
	/usr/local/bin/frameit:23:in `<main>'
```

### Environment

fastlane 1.97.2

**Comment by dvalenzuela-com** [comment]
Have you tried escaping your quotes?

**Comment by adriantofan** [comment]
Yes,  that is what I did, but I don't understand why I have to since it is a single quote in a double quoted string. 

Besides that the error message was not very helpful.

**Comment by TKBurner** [comment]
Hi @adriantofan Thanks for following up. The way our string parsing works means you'll need to escape like this. Thanks!
