### ISSUE TITLE
Push Notification Profile Maintenance

### ISSUE THREAD

**Issue by cytryn** [fastlane/fastlane#5441]
Hi all,

I am running fastlane on version 1.97.2
And I am trying to create new push profiles for my apps (multiple targets).

```ruby
desc "Create, download e export APN profiles"
  lane :push_profile do
    pem(
    app_identifier: ENV["BUNDLE_ID"],
    generate_p12: true,
    p12_password: "mypass",
    output_path: "./tmp/#{ENV["SCHEME"]}/push"
    )
  end
```

And I get the following error message if this is the first time that the certificate is being create
```
/Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/lib/pem/manager.rb:65:in `write': [!] No such file or directory - ./tmp/myTargetName/push/production_br.com.company.myTargetName.pkey (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/lib/pem/manager.rb:65:in `create_certificate'
	from /Library/Ruby/Gems/2.0.0/gems/pem-1.3.1/lib/pem/manager.rb:30:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/pem.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:155:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

And the second problem is that if the profile is already created, the script ends and does not download the profile.
I wanted it to be downloaded and exported in a .p12 file with my password.

Any ideas?

**Comment by KrauseFx** [comment]
It seems like your output path directory doesn't exist? `"./tmp/#{ENV["SCHEME"]}/push"`
Ideally `pem` would create it for you, but could you try creating it manually to see if that solves the problem?

**Comment by cytryn** [comment]
@KrauseFx indeed it worked! Thanks
It would be just great if `pem` could create the folder for me just like `gym` does with the builds.

What about the second part? 
Imagine I have a new developer in my team or that I have just bought a brand new mac and want to download all the profiles.
Is there a way I can "force" it to download the existing profile?

**Comment by KrauseFx** [comment]
@cytryn Why do you want to download push notification profiles? You have them on your server. There is no way to receive it from the Apple Dev Portal

**Comment by cytryn** [comment]
@KrauseFx In my actual case I want to generate the .p12 files with the given password to upload to Firebase.

I have 9 targets and it would be awesome if `pem` could download them all, generate the .p12 files with the given password so I could upload to firebase.

Otherwise I would just have to go to keychain and click export and set password 9 times.

Would it be possible?

**Comment by KrauseFx** [comment]
It's not possible to get the p12 or the pem file from , as  only stores the `.cer` file. You'll have to store it yourself 👍
