### ISSUE TITLE
Deliver without testing, metadata and screenshots

### ISSUE THREAD

**Issue by akudryashov** [fastlane/fastlane#5453]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

On my project I have only developer rights in iTunes Connect. And I wanna send only app into iTunes, without testing, metadata and screenshots.
Console links me to pilot issue, but i don't really need it.
skip_metadata and skip_screenshots help me with non updating some stuff. but with testing I have a problem.

##### Complete output when running fastlane, including the stack trace and command used

[12:18:15]: ------------------------------
[12:18:15]: --- Step: default_platform ---
[12:18:15]: ------------------------------
[12:18:15]: Driving the lane 'ios baby_ru_lane_appstore' 🚀
[12:18:15]: --------------------------------
[12:18:15]: --- Step: clear_derived_data ---
[12:18:15]: --------------------------------
[12:18:15]: Derived Data path located at: /Users/AntonKudryashov/Library/Developer/Xcode/DerivedData
[12:18:17]: Successfully cleared Derived Data ♻️
[12:18:17]: -----------------------
[12:18:17]: --- Step: cocoapods ---
[12:18:17]: -----------------------
[12:18:17]: $ pod install
[12:18:24]: ▸ Analyzing dependencies
[12:18:24]: ▸ Downloading dependencies
[12:18:24]: ▸ Using AFNetworking (2.5.4)
[12:18:24]: ▸ Using Bolts (1.7.0)
[12:18:24]: ▸ Using Branch (0.12.2)
[12:18:24]: ▸ Using ComponentKit (0.14)
[12:18:24]: ▸ Using DACircularProgress (2.3.1)
[12:18:24]: ▸ Using DZNEmptyDataSet (1.6.1)
[12:18:24]: ▸ Using DZNPhotoPickerController (2.0)
[12:18:24]: ▸ Using DeepStorm (1.1.0)
[12:18:24]: ▸ Using FBSDKCoreKit (4.12.0)
[12:18:24]: ▸ Using FBSDKLoginKit (4.12.0)
[12:18:24]: ▸ Using Flurry-iOS-SDK (7.6.3)
[12:18:24]: ▸ Using GDataXML-HTML (1.3.0)
[12:18:24]: ▸ Using Google (1.0.7)
[12:18:24]: ▸ Using Google-Mobile-Ads-SDK (7.8.1)
[12:18:24]: ▸ Using GoogleAnalytics (3.14.0)
[12:18:24]: ▸ Using GoogleConversionTracking (3.4.0)
[12:18:24]: ▸ Using GoogleNetworkingUtilities (1.2.1)
[12:18:24]: ▸ Using GoogleSymbolUtilities (1.1.1)
[12:18:24]: ▸ Using GoogleUtilities (1.3.1)
[12:18:24]: ▸ Using MBProgressHUD (0.9.2)
[12:18:24]: ▸ Using MSCMoreOptionTableViewCell (2.2)
[12:18:24]: ▸ Using MWPhotoBrowser (2.1.1)
[12:18:24]: ▸ Using MZAppearance (1.1.6)
[12:18:24]: ▸ Using MZFormSheetPresentationController (2.4.0)
[12:18:24]: ▸ Using RACollectionViewReorderableTripletLayout (0.1.0)
[12:18:24]: ▸ Using RESideMenu (4.0.7)
[12:18:24]: ▸ Using ReactiveCocoa (2.5)
[12:18:24]: ▸ Using SDWebImage (3.7.3)
[12:18:24]: ▸ Using SSKeychain (1.4.0)
[12:18:24]: ▸ Using Tune (4.3.0)
[12:18:24]: ▸ Using VK-ios-sdk (1.2.2)
[12:18:24]: ▸ Using YandexMobileMetrica (2.5.0)
[12:18:24]: ▸ Generating Pods project
[12:18:30]: ▸ Integrating client project
[12:18:30]: ▸ Sending stats
[12:18:30]: ▸ Pod installation complete! There are 23 dependencies from the Podfile and 32 total pods installed.
[12:18:30]: ▸ [!] Unable to read the license file `/Users/AntonKudryashov/Documents/projects/b2/baby.ru/Pods/DeepStorm/LICENSE.txt` for the spec `DeepStorm (1.1.0)`
[12:18:30]: ▸ [!] Unable to read the license file `/Users/AntonKudryashov/Documents/projects/b2/baby.ru/Pods/DeepStorm/LICENSE.txt` for the spec `DeepStorm (1.1.0)`
[12:18:30]: -------------------
[12:18:30]: --- Step: match ---
[12:18:30]: -------------------

+-----------------------+------------------------------------------------+
|                        Summary for match 0.6.1                         |
+-----------------------+------------------------------------------------+
| app_identifier        | ru.babik.babik                                 |
| type                  | appstore                                       |
| readonly              | true                                           |
| git_url               | git@gitlab.com:ID-IOS/Baby.ru-Certificates.git |
| username              | #appleID#                            |
| git_branch            | master                                         |
| keychain_name         | login.keychain                                 |
| team_id               | E998C2ZJFE                                     |
| verbose               | false                                          |
| force                 | false                                          |
| shallow_clone         | false                                          |
| force_for_new_devices | false                                          |
| skip_docs             | false                                          |
+-----------------------+------------------------------------------------+

[12:18:31]: Cloning remote git repo...
[12:18:35]: 🔓  Successfully decrypted certificates repo
[12:18:35]: Installing certificate...
[12:18:35]: Installing provisioning profile...

+----------------------+--------------------------------------+
|               Installed Provisioning Profile                |
+----------------------+--------------------------------------+
| App Identifier       | ru.babik.babik                       |
| Type                 | appstore                             |
| UUID                 | 07cdbb1d-ed3f-4ccb-aaaf-6553fc2a8dca |
| Environment Variable | sigh_ru.babik.babik_appstore         |
+----------------------+--------------------------------------+

[12:18:35]: All required keys, certificates and provisioning profiles are installed 🙌
[12:18:35]: 🔒  Successfully encrypted certificates repo
[12:18:35]: Setting Provisioning Profile type to 'app-store'
[12:18:35]: -----------------
[12:18:35]: --- Step: gym ---
[12:18:35]: -----------------
[12:18:35]: xcrun xcodebuild -list -workspace ./baby.ru.xcworkspace
2016-07-20 12:18:36.076 xcodebuild[90015:3182763] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-07-20 12:18:36.077 xcodebuild[90015:3182763] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ACCodeSnippetRepository.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-07-20 12:18:37.540 xcodebuild[90019:3182809] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-07-20 12:18:37.541 xcodebuild[90019:3182809] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ACCodeSnippetRepository.xcplugin' not present in DVTPlugInCompatibilityUUIDs

+----------------------+-----------------------+
|            Summary for gym 1.7.0             |
+----------------------+-----------------------+
| scheme               | baby.ru Release       |
| output_directory     | ./fastlane_store/     |
| clean                | true                  |
| export_method        | app-store             |
| workspace            | ./baby.ru.xcworkspace |
| destination          | generic/platform=iOS  |
| output_name          | baby.ru               |
| silent               | false                 |
| use_legacy_build_api | false                 |
| buildlog_path        | ~/Library/Logs/gym    |
+----------------------+-----------------------+

[12:18:43]: $ set -o pipefail && xcodebuild -workspace ./baby.ru.xcworkspace -scheme baby.ru\ Release -destination 'generic/platform=iOS' -archivePath '/Users/AntonKudryashov/Library/Developer/Xcode/Archives/2016-07-20/baby.ru 2016-07-20 12.18.43.xcarchive' clean archive | tee /Users/AntonKudryashov/Library/Logs/gym/baby.ru-baby.ru\ Release.log | xcpretty
[12:18:43]: ▸ 2016-07-20 12:18:43.951 xcodebuild[90040:3182894] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[12:18:43]: ▸ 2016-07-20 12:18:43.952 xcodebuild[90040:3182894] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ACCodeSnippetRepository.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[12:18:46]: ▸ Cleaning Pods/ComponentKit [Release]
[12:18:46]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/AFNetworking [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/Bolts [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/Branch [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/DACircularProgress [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/DZNEmptyDataSet [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/DZNPhotoPickerController [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/GDataXML-HTML [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/FBSDKCoreKit [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/Flurry-iOS-SDK-Flurry-iOS-SDK [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/Flurry-iOS-SDK [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/DeepStorm [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/MBProgressHUD [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/MSCMoreOptionTableViewCell [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/MWPhotoBrowser-MWPhotoBrowser [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/SDWebImage [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/MZAppearance [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/MZFormSheetPresentationController [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/MWPhotoBrowser [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/FBSDKLoginKit [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/RACollectionViewReorderableTripletLayout [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/RESideMenu [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:47]: ▸ Cleaning Pods/ReactiveCocoa [Release]
[12:18:47]: ▸ Check Dependencies
[12:18:48]: ▸ Cleaning Pods/SSKeychain [Release]
[12:18:48]: ▸ Check Dependencies
[12:18:48]: ▸ Cleaning Pods/VK-ios-sdk [Release]
[12:18:48]: ▸ Check Dependencies
[12:18:48]: ▸ Cleaning Pods/Pods-baby.ru [Release]
[12:18:48]: ▸ Check Dependencies
[12:18:48]: ▸ Cleaning baby.ru/baby.ru [Release]
[12:18:48]: ▸ Check Dependencies
[12:18:54]: ▸ Clean Succeeded
[12:18:54]: ▸ Building Pods/AFNetworking [Release]
[12:18:54]: ▸ Check Dependencies
[12:19:00]: ▸ Compiling AFHTTPRequestOperation.m
....
#here so long compiling process#
....
[12:27:49]: ▸ Compiling WelcomeScenarioStoryboard.storyboard
[12:27:58]: ▸ Processing InfoRelease.plist
[12:27:58]: ▸ Generating 'baby.ru.app.dSYM'
[12:28:08]: ▸ Running script 'Build Subversion Increment Script'
[12:28:08]: ▸ Running script 'Fabric'
[12:28:08]: ▸ Running script '[CP] Embed Pods Frameworks'
[12:28:08]: ▸ Running script '[CP] Copy Pods Resources'
[12:28:08]: ▸ Touching baby.ru.app
[12:28:08]: ▸ Signing /Users/AntonKudryashov/Library/Developer/Xcode/DerivedData/baby.ru-eemzegjylcyrnaghblodtkfefxbi/Build/Intermediates/ArchiveIntermediates/baby.ru\ Release/InstallationBuildProductsLocation/Applications/baby.ru.app
[12:28:11]: ▸ Touching baby.ru.app.dSYM
[12:28:11]: ▸ Archive Succeeded
[12:28:12]: $ /usr/bin/xcrun /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.7.0/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/vx/7cfqcjdd3d977745k0tcs2sr0000gn/T/gym_config20160720-89856-x8bvfh.plist' -archivePath '/Users/AntonKudryashov/Library/Developer/Xcode/Archives/2016-07-20/baby.ru 2016-07-20 12.18.43.xcarchive' -exportPath '/var/folders/vx/7cfqcjdd3d977745k0tcs2sr0000gn/T/gym_output20160720-89856-hr7eha' 
[12:28:27]: Compressing 1 dSYM(s)
[12:28:27]: $ cd '/Users/AntonKudryashov/Library/Developer/Xcode/Archives/2016-07-20/baby.ru 2016-07-20 12.18.43.xcarchive/dSYMs' && zip -r '/Users/AntonKudryashov/Documents/projects/b2/baby.ru/fastlane_store/baby.ru.app.dSYM.zip' *.dSYM
[12:28:31]: ▸   adding: baby.ru.app.dSYM/ (stored 0%)
[12:28:31]: ▸   adding: baby.ru.app.dSYM/Contents/ (stored 0%)
[12:28:31]: ▸   adding: baby.ru.app.dSYM/Contents/Info.plist (deflated 52%)
[12:28:31]: ▸   adding: baby.ru.app.dSYM/Contents/Resources/ (stored 0%)
[12:28:31]: ▸   adding: baby.ru.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
[12:28:31]: ▸   adding: baby.ru.app.dSYM/Contents/Resources/DWARF/baby.ru (deflated 73%)

[12:28:31]: Successfully exported and compressed dSYM file
[12:28:31]: Successfully exported and signed the ipa file:
[12:28:31]: /Users/AntonKudryashov/Documents/projects/b2/baby.ru/fastlane_store/baby.ru.ipa
[12:28:31]: ---------------------
[12:28:31]: --- Step: deliver ---
[12:28:31]: ---------------------
[12:28:31]: Login to iTunes Connect (#appleID#)
[12:28:37]: Login successful

+--------------------+-----------------------------------------------------------------------------+
|                                      deliver 1.13.1 Summary                                      |
+--------------------+-----------------------------------------------------------------------------+
| app_identifier     | ru.babik.babik                                                              |
| skip_metadata      | true                                                                        |
| skip_screenshots   | true                                                                        |
| force              | true                                                                        |
| submit_for_review  | true                                                                        |
| username           | #appleID#                                                         |
| ipa                | /Users/AntonKudryashov/Documents/projects/b2/baby.ru/fastlane_store/baby... |
| screenshots_path   | ./fastlane/screenshots                                                      |
| metadata_path      | ./fastlane/metadata                                                         |
| app_version        | 1.9.27                                                                      |
| skip_binary_upload | false                                                                       |
| automatic_release  | false                                                                       |
| dev_portal_team_id | E998C2ZJFE                                                                  |
+--------------------+-----------------------------------------------------------------------------+

[12:28:37]: Making sure the latest version on iTunes Connect matches '1.9.27' from the ipa file...
[12:28:42]: Variable Dump:
[12:28:42]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios baby_ru_lane_appstore", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/AntonKudryashov/Documents/projects/b2/baby.ru/fastlane_store/baby.ru.ipa", :DSYM_OUTPUT_PATH=>"/Users/AntonKudryashov/Documents/projects/b2/baby.ru/fastlane_store/baby.ru.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/AntonKudryashov/Library/Developer/Xcode/Archives/2016-07-20/baby.ru 2016-07-20 12.18.43.xcarchive"}
[12:28:42]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | default_platform   | 0           |
| 2    | clear_derived_data | 1           |
| 3    | cocoapods          | 13          |
| 4    | match              | 4           |
| 5    | gym                | 595         |
| 6    | deliver            | 11          |
+------+--------------------+-------------+

[12:28:42]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Error when trying to retrieve TestFlight tester data
   https://github.com/fastlane/fastlane/issues/1895 [open] 13 💬
   26 May 2016

➡️  pilot find fails to list details of tester
   https://github.com/fastlane/fastlane/issues/3735 [open] 7 💬
   4 days ago

➡️  pilot list throw an error
   https://github.com/fastlane/fastlane/issues/5043 [closed] 9 💬
   3 weeks ago

and 6 more at: https://github.com/fastlane/fastlane/search?q=%7B%22data%22=%3Enil,%20%22messages%22=%3E%7B%22warn%22=%3Enil,%20%22info%22=%3Enil,%20%22error%22=%3E[%22Forbidden%22]%7D,%20%22statusCode%22=%3E%22ERROR%22%7D&type=Issues&utf8=✓
/Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/client.rb:434:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/tunes/tunes_client.rb:269:in `create_version!'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/tunes/application.rb:158:in `create_version!'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/tunes/application.rb:177:in `ensure_version!'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deliver-1.13.1/lib/deliver/runner.rb:39:in `verify_version'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deliver-1.13.1/lib/deliver/runner.rb:20:in `run'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:177:in `block in execute_action'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:176:in `chdir'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:176:in `execute_action'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:25:in `block (2 levels) in parsing_binding'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/commands_generator.rb:244:in `run'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.98.0/bin/fastlane:5:in `<top (required)>'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /Users/AntonKudryashov/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

default_platform :ios
platform :ios do

  ############################## PRE ##############################
  before_all do
    clear_derived_data
    cocoapods
  end
  ############################## ad-hoc ##############################
  lane :baby_ru_lane_adhoc do
    match(app_identifier: "ru.babik.babik", type: "adhoc", readonly: true)
    fabric(scheme: "baby.ru Release", method: "ad-hoc")
  end

  ############################## appstore ##############################
  lane :baby_ru_lane_appstore do
    match(app_identifier: "ru.babik.babik", type: "appstore", readonly: true)
    gym(
        scheme: "baby.ru Release",
        output_directory: "./fastlane_store/",
        clean: true,
        export_method: "app-store"
        )
    deliver(
        app: 1039767144, 
        app_identifier: "ru.babik.babik", 
        skip_metadata: true, 
        skip_screenshots: true,
        force: true,
        submit_for_review: true
        )
  end
  
  ######################### PRIVATE LANES #########################
  private_lane :fabric do |options|
    scheme = options[:scheme]

    gym(
      scheme: scheme,
      output_directory: "./fastlane_temp/",
      clean: true,
      export_method: options[:method],
      include_symbols: true,
      include_bitcode: false
      )

    crashlytics(
      api_token: "fc34a35436522e9dd4aba1701b048a132863e1e8",
      build_secret: "0f6d3b43ff4472c73fff470ea39a91f0fa8064181b3544f8ee65b037a14867b6",
      notes: options[:scheme],
      groups: ['baby.ru-dev'],
      notifications: true
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # post actions
  end

  error do |lane, exception|
    # Error handler
  end
end

### Environment

fastlane version (run `fastlane -v`):
1.98.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
NO
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
NO. but Ruby latest. 2.3.1p1122.3.1p112

**Comment by akudryashov** [comment]
I have match(type: "adhoc") which provides valid certification. I already configured ad-hoc lane with fabric. see baby_ru_lane_adhoc. there is all fine. 
I really need only deliver ipa to iTunes connect without any additions(metadata, screenshots, testing, review...and etc). This must be pure ipa-delivering. How I can do it?

**Comment by akudryashov** [comment]
so i understood my mistake. I need to use 
pilot upload --skip_submission -i "./fastlane_store/baby.ru.ipa"
instead of deliver...

**Comment by TKBurner** [comment]
@akudryashov Awesome! So glad to hear you got up and running. Hope you have a wonderful day! 👍

**Comment by akudryashov** [comment]
Yeah, that's it) May be documentation about deliver should be links to pilot, because there is some misunderstanding... Actually feature called deliver and it's can't deliver only binary build... And pilot with testflight icon knocked me from right way. :) And I saw that --help for all components isn't have fully documentation - like something not done yet.. Sorry for my criticism...but it's not so clear.

**Comment by TKBurner** [comment]
@akudryashov Thanks for the feedback! We'll review the docs and improve this. Thanks!
