### ISSUE TITLE
After installing Plugin Fastlane is slow 

### ISSUE THREAD

**Issue by duncandee** [fastlane/fastlane#5475]
### Issue Description

I installed "fastlane add_plugin download_file"  and now fastlane is Sloooooooowwww 

Ran Command
 ```
time fastlane -v
[17:51:10]: Seems like launching fastlane takes a while - please run
[17:51:10]:
[17:51:10]: $ [sudo] gem cleanup
[17:51:10]:
[17:51:10]: to uninstall outdated gems and make fastlane launch faster
[17:51:10]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[17:51:10]: To get started with a Gemfile, run
[17:51:10]:
[17:51:10]: $ bundle init
[17:51:10]: $ echo 'gem "fastlane"' >> Gemfile
[17:51:10]: $ bundle install
[17:51:10]:
[17:51:10]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[17:51:10]: For more information, check out https://guides.cocoapods.org/using/a-gemfile.html
fastlane 1.98.0
fastlane -v  114.29s user 0.49s system 98% cpu 1:55.98 total
```

If i exit the command i get this trace

```
 ~  %  fastlane -v
^C/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:284:in `matching_specs': Interrupt
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:295:in `to_specs'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2440:in `block (2 levels) in traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2438:in `each'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2440:in `block (2 levels) in traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2438:in `each'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2440:in `block (2 levels) in traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2438:in `each'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2438:in `block in traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2437:in `each'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2437:in `traverse'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:961:in `block in find_in_unresolved_tree'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:959:in `reverse_each'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:959:in `find_in_unresolved_tree'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:87:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rexml/document.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.1/lib/fastlane_core/pkg_file_analyser.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.1/lib/fastlane_core.rb:19:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.98.0/lib/fastlane.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.98.0/lib/fastlane/cli_tools_distributor.rb:10:in `take_off'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.98.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

fastlane version (run `fastlane -v`):
1.98.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Tried it still slow
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by duncandee** [comment]
I had to uninstall ruby and then the issue got fixed.

**Comment by TKBurner** [comment]
@duncandee Awesome! Really glad to hear you got up and running 👍
