### ISSUE TITLE
!] SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by douglasalexandre** [fastlane/fastlane#5476]
When run `match appstore` i received this error:  

`Ruby version:` ```ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]```

```🔒  Successfully encrypted certificates repo
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '3273c8452427bde06139051c7105baae'
The crash report has been stored locally '/tmp/sentry_3273c8452427bde06139051c7105baae.json'
/Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `connect': [!] SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from /Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/bluesprogrammer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:404:in `block in send_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:322:in `with_retry'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:403:in `send_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:379:in `request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:313:in `itc_service_key'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:274:in `block in send_shared_login_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:404:in `block in send_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:322:in `with_retry'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:403:in `send_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:379:in `request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:273:in `send_shared_login_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/portal/portal_client.rb:35:in `send_login_request'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:346:in `do_login'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:225:in `login'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/client.rb:88:in `login'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/spaceship-0.25.1/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/match-0.6.1/lib/match/spaceship_ensure.rb:19:in `initialize'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/match-0.6.1/lib/match/runner.rb:11:in `new'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/match-0.6.1/lib/match/runner.rb:11:in `run'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/match-0.6.1/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/match-0.6.1/lib/match/commands_generator.rb:121:in `run'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/match-0.6.1/lib/match/commands_generator.rb:12:in `start'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/gems/match-0.6.1/bin/match:6:in `<top (required)>'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/bin/match:23:in `load'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/bin/match:23:in `<main>'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/bluesprogrammer/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by TKBurner** [comment]
Hi @douglasalexandre Did you run `match development` first on this project? Thanks!

**Comment by douglasalexandre** [comment]
@TKBurner No. I run first `match appstore`. Not work if run this first command?

**Comment by TKBurner** [comment]
@douglasalexandre You need to run match development first. Let me know how it goes if you do that. Thanks!

**Comment by douglasalexandre** [comment]
@TKBurner the same error happens. :/

**Comment by douglasalexandre** [comment]
Hi @TKBurner i solved problem! :) 

First, 
 i run this commands:
```breu update && breu upgrade openssl```
```rim osx-ssl-certs update all```
```rum reinstala ruby-2.2.3 --with-openssl-dir=/usr/local```

After it, i reinstalei `fastlane`, `match` and `cert`. Before of all process, the `Match` was licked with path of my osx system with `ruby version 2.0.0` and not with new version of `ruby` which was installed. After which i solver it, i had problem with number of certificates on apple portal, at least three certificates, Is right? When solved this too, `match development` and `match appstore` they worked normally! very good.. 👍 😃 

I documented this process and soon share for everyone.

Sorry for duplicate, triplicate of issue. :/

**Comment by TKBurner** [comment]
@douglasalexandre Awesome! So glad to hear you got up and running. System ruby tends to cause some problems so that makes sense. Hope that you have a wonderful week!
