### ISSUE TITLE
Support for produce with different credentials for DevCenter and iTC

### ISSUE THREAD

**Issue by krodak** [fastlane/fastlane#5482]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm unable to create application in both DevCenter and iTC when I have different credentials for each of them. It works fine if I use 2 different `produce` commands, with `skipt_devcenter` and another with `skip_itc`.
I do have different credentials stored in `AppFile`

##### Complete output when running fastlane, including the stack trace and command used

```
+----------------+--------------------------+
|         Summary for produce 1.1.2         |
+----------------+--------------------------+
| app_identifier | app_id, correct |
| app_name       | App Name             |
| language       | English                  |
| app_version    | 1.3.2                    |
| sku            | ym97y72                  |
| itc_team_id    | My iTC team ID, correct                 |
| itc_team_name  | My iTC team name, correct           |
| username       | myemailhere   |
| skip_itc       | false                    |
| skip_devcenter | false                    |
| team_id        | My team ID, correct              |
| team_name      | My Team Name, correct            |
+----------------+--------------------------+
INFO [2016-07-22 10:51:17.14]: [DevCenter] App 'app_id' already exists, nothing to do on the Dev Center
INFO [2016-07-22 10:51:23.25]: Creating new app 'App Name' on iTunes Connect
WARN [2016-07-22 10:51:23.76]: Variable Dump:
INFO [2016-07-22 10:51:23.76]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios add_app"}
ERROR [2016-07-22 10:51:23.76]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}
INFO [2016-07-22 10:51:23.76]: Successfully generated documentation to path '/Users/krodak/x8/git/howdy-ios/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | produce                             | 13          |
+------+-------------------------------------+-------------+

ERROR [2016-07-22 10:51:23.77]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}
and 7 more at: https://github.com/fastlane/fastlane/search?q={"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.28.0/lib/spaceship/client.rb:434:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.28.0/lib/spaceship/tunes/tunes_client.rb:231:in `create_application!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.28.0/lib/spaceship/tunes/application.rb:80:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.1.2/lib/produce/itunes_connect.rb:25:in `create_new_app'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.1.2/lib/produce/itunes_connect.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.1.2/lib/produce/manager.rb:8:in `start_producing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/actions/produce.rb:19:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/actions/produce.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/actions/produce.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:177:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:176:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:176:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:55:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Appfile:
```ruby
apple_id              "mydevcenteremail"
apple_dev_portal_id   "mydevcenteremail"
itunes_connect_id     "myitcemail"
team_name             "mydevname"
team_id               "mydevid"  # Developer Portal Team ID
```

Fastfile:
```ruby
  lane :add_app do |options|
    partner_id  = ""
    app_name    = ""
    if options[:partner]
      partner_id    = options[:partner]
    else
      partner_id    = prompt(text: "Complete given Bundle ID \"start.of.bundle.id.\" with partner name (lowercase, i.e.: testpartner): ")
    end
    partner_app_id  = "start.of.bundle.id.#{partner_id}"
    puts "Bundle identifier for the new app: #{partner_app_id} \n"
    ENV["APP_IDENTIFIER"]         = partner_app_id
    if options[:name]
      app_name    = options[:name]
    else
      app_name    = prompt(text: "Enter application name (visible in AppStore): ")
    end
    puts "App Store application name: #{app_name}"
    produce(
      app_identifier: ENV["APP_IDENTIFIER"],
      app_name:       app_name,
      app_version:    version,
      sku:            rand(36**7).to_s(36),
      itc_team_id:    CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      itc_team_name:  CredentialsManager::AppfileConfig.try_fetch_value(:team_name)
    )
    match(type: "appstore")
    match(type: "adhoc")
    match(type: "development")
    pem(generate_p12: true)
  end
```

### Environment
> fastlane version (run `fastlane -v`):

fastlane 1.98.0

> Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

> Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

ruby 2.0.0p648 (2015-12-16 revision 53162)

**Comment by TKBurner** [comment]
@krodak Thanks for reaching out. You should be able to accomplish this by implementing ENV rather than configuring in the app file. However, your solution of running produce twice is also viable. Thanks!

**Comment by krodak** [comment]
@TKBurner could you point me to the right ENV variables? I can't use `PRODUCE_USERNAME` for this.

**Comment by TKBurner** [comment]
Hi @krodak Thanks for replying you can get more info here:
https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md
https://github.com/bkeepers/dotenv

Thanks!
