### ISSUE TITLE
Creating new plugin and adding it crashes my fastline

### ISSUE THREAD

**Issue by FisherKK** [fastlane/fastlane#5484]
Hello,

I would like to create my own plugin for fastlane. I followed this[ guide](https://github.com/fastlane/fastlane/issues/4873). 

I believe I have followed everything that was written there. Yet after installing my fresh plugin (without any edits, state - after generation) I receive error while invoking fastlane command in terminal.

Here I post my log from terminal. Everything I have done in order to create/install my custom plugin.

```
Kamils-MacBook-Pro:MyProject F1sherKK$ sudo gem update fastlane --pre
Password:
Updating installed gems
Nothing to update
Kamils-MacBook-Pro:MyProject F1sherKK$ cd
Kamils-MacBook-Pro:~ F1sherKK$ mkdir TestEmulatorRun
Kamils-MacBook-Pro:~ F1sherKK$ cd TestEmulatorRun/
Kamils-MacBook-Pro:TestEmulatorRun F1sherKK$ fastlane new_plugin

What would you like to be the name of your plugin?
test_emulator_run

Please enter a short summary of this fastlane plugin:
Starts single emulator before running tests.

Your plugin was successfully generated at fastlane-plugin-test_emulator_run/ 🚀

To get started with using this plugin, run

    fastlane add_plugin test_emulator_run

from a fastlane-enabled app project directory and provide the following as the path:

 /Users/F1sherKK/TestEmulatorRun/fastlane-plugin-test_emulator_run

Kamils-MacBook-Pro:TestEmulatorRun F1sherKK$ cd
Kamils-MacBook-Pro:~ F1sherKK$ cd Dev/MyProject/
Kamils-MacBook-Pro:MyProject F1sherKK$ fastlane add_plugin test_emulator_run
[13:28:11]: Seems like the plugin is not available on RubyGems, what do you want to do?
1. Git URL
2. Local Path
3. RubyGems.org ('fastlane-plugin-test_emulator_run' seems to not be available there)
?  2
Please enter the relative path to the plugin you want to use. It has to point to the directory containing the
.gemspec file
/Users/F1sherKK/TestEmulatorRun/fastlane-plugin-test_emulator_run
[13:28:19]: Plugin 'fastlane-plugin-test_emulator_run' was added to './fastlane/Pluginfile'
[13:28:19]: It looks like fastlane plugins are not yet set up for this project.
[13:28:19]: fastlane will create a new Gemfile at path 'Gemfile'
[13:28:19]: This change is neccessary for fastlane plugins to work
Should fastlane modify the Gemfile at path 'Gemfile' for you? (y/n)
y
[13:28:25]: Successfully modified 'Gemfile'
[13:28:25]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
Successfully installed plugins
Kamils-MacBook-Pro:MyProject F1sherKK$ fastlane search_plugins
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fastlane/plugin/test_emulator_run (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/plugins/plugin_manager.rb:276:in `block in load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/plugins/plugin_manager.rb:268:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/plugins/plugin_manager.rb:268:in `load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/commands_generator.rb:17:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.98.0/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
Kamils-MacBook-Pro:MyProject F1sherKK$ 
```

What am I doing wrong?

**Comment by TKBurner** [comment]
Hi @FisherKK Thanks for reaching out about this. Before you add the local plugin what are your results for `fastlane search_plugins`? What happens when you provide the path `TestEmulatorRun/fastlane-plugin-test_emulator_run`

Thanks!

**Comment by FisherKK** [comment]
Hello @TKBurner, thanks for fast response :)

My output of `fastlane sarch_plugins` was correct:

Listing all available fastlane plugins
```
Kamils-MacBook-Pro:MyProject F1sherKK$ fastlane search_plugins
+--------------------------+---------------------------------------------------+-----------+
|                                Available fastlane plugins                                |
+--------------------------+---------------------------------------------------+-----------+
| Name                     | Description                                       | Downloads |
+--------------------------+---------------------------------------------------+-----------+
| ruby                     | Useful fastlane actions for Ruby projects         | 793       |
| versioning               | Allows to work set/get app version directly       | 769       |
|                          | to/from Info.plist                                |           |
| branding                 | Add some branding to your fastlane output         | 736       |
| instrumented_tests       | New action to run instrumented tests for android. | 616       |
|                          | This basically creates and boots an emulator      |           |
|                          | before running an gradle commands so that you can |           |
|                          | run instrumented tests against that emulator.     |           |
|                          | After the gradle command is executed, the avd     |           |
|                          | gets shut down and deleted. This is really        |           |
|                          | helpful on CI services, keeping them clean and    |           |
|                          | always having a fresh avd for testing.            |           |
| xamarin_build            | Build xamarin android\ios projects                | 603       |
| appicon                  | Generate required icon sizes and iconset from a   | 528       |
|                          | master application icon.                          |           |
| upload_folder_to_s3      | Upload a folder to S3                             | 506       |
| changelog                | Automate changes to your project CHANGELOG.md     | 477       |
| instabug                 | Uploads dSYM to Instabug                          | 476       |
| goodify_info_plist       | This plugin will update the plist so that the     | 458       |
|                          | built application can be deployed and managed     |           |
|                          | within BlackBerry's Good Dynamics Control Center  |           |
|                          | for Enterprise Mobility Management.               |           |
| emoji_fetcher            | Fetch the emoji font file and copy it to a local  | 450       |
|                          | directory                                         |           |
| apprepo                  | experimental fastlane plugin based on             | 450       |
|                          | https://github.com/suculent/apprepo SFTP uploader |           |
| no_u                     | no u                                              | 441       |
| github_status            | Provides the ability to display and act upon      | 427       |
|                          | GitHub server status as part of your build        |           |
| tpa                      | TPA gives you advanced user behaviour analytics,  | 403       |
|                          | app distribution, crash analytics and more        |           |
| xcake                    | Create your Xcode projects automatically using a  | 381       |
|                          | stupid simple DSL.                                |           |
| synx                     | Organise your Xcode project folder to match your  | 378       |
|                          | Xcode groups.                                     |           |
| ftp                      | Simple ftp upload and download for Fastlane       | 368       |
| clubmate                 | Print the Club Mate logo in your build output     | 351       |
| unzip                    | Extract compressed files in a ZIP                 | 348       |
| upload_symbols_to_hockey | Upload dSYM symbolication files to Hockey         | 336       |
| version_from_last_tag    | Perform a regex on last (latest) git tag and      | 309       |
|                          | perform a regex to extract a version number such  |           |
|                          | as Release 1.2.3                                  |           |
| poeditor_export          | Exports translations from POEditor.com            | 307       |
| carthage_cache           | A Fastlane plugin that allows to cache            | 305       |
|                          | Carthage/Build folder in Amazon S3.               |           |
| ascii_art                | Add some fun to your fastlane output.             | 281       |
| sentry                   | Upload symbols to Sentry                          | 261       |
| jira_transition          | Apply a JIRA transition to issues mentioned in    | 229       |
|                          | the changelog                                     |           |
| tunes                    | Play music using fastlane, because you can.       | 225       |
| ya_tu_sabes              | Ya tu sabes.                                      | 213       |
| figlet                   | Wrapper around figlet which makes large ascii     | 180       |
|                          | text words                                        |           |
+--------------------------+---------------------------------------------------+-----------+
```

In general, at the moment I am writing my own fastlane plugin and I made it work. But what bothers  me, is that since I have allowed fastlane to configure my project (it added `Gemfile`, `Gemfile.lock` and `Pluginfile`) I am unable to run my lanes with just `fastlane` and I have to always use `bundle exec fastlane` then it works. Is it intended behaviour?

-----

> What happens when you provide the path TestEmulatorRun/fastlane-plugin-test_emulator_run

Where should I add it?

**Comment by TKBurner** [comment]
Hi @FisherKK Thanks for following up. Can you run ruby -v? Also are you using rvm? Thanks!

**Comment by FisherKK** [comment]
Hello, sorry for delay.

```
Kamils-MacBook-Pro:~ F1sherKK$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

```
Kamils-MacBook-Pro:~ F1sherKK$ rvm
-bash: rvm: command not found
```

```
Kamils-MacBook-Pro:~ F1sherKK$ rvm --verbose
-bash: rvm: command not found
```

**Comment by TKBurner** [comment]
Hi @FisherKK Thanks for following up. Can you check your gem file for the following:

> Inside the newly created folder, edit the fastlane-plugin-[plugin_name].gemspec and add your gem as a dependency. It is recommended to also specify a version number requirement

Let me know if that clears things up!

**Comment by FisherKK** [comment]
Hi, I've understood where is the problem. 
I had only *.gemspec file all the time. I have generated *.gem file from it and uploaded to rubygems.org.
I have added dependency in my pluginfile of my project so it should look for my plugin in rubygems and now it works.
