### ISSUE TITLE
sigh No login data provided

### ISSUE THREAD

**Issue by Yspadadden** [fastlane/fastlane#549]
I tried to create a lane that builds an internal version of the app. I use sigh to generate the provisioning profile. But I don't have a company wide email to use for the developer account. So I want each developer to use his own account. 

I managed that by setting `apple_id ''` to empty. Sigh then prompts me for the login and the password if the password is not already in the keychain. But then sigh throws an error `No login data provided`. 

Here's the output: 

    ~/Documents/_Projects/BankDuLemon/iOS $ fastlane --trace accti8m
    [14:26:21]: Successfully loaded custom action '/Users/emario/Documents/_Projects/BankDuLemon/iOS/fastlane/actions/marvinupload.rb'.
    [14:26:21]: -------------------------------------------------
    [14:26:21]: --- Step: Verifying required fastlane version ---
    [14:26:21]: -------------------------------------------------
    [14:26:21]: fastlane version valid
    [14:26:21]: ------------------------------
    [14:26:21]: --- Step: default_platform ---
    [14:26:21]: ------------------------------
    [14:26:21]: Driving the lane 'ios accti8m' 🚀
    [14:26:21]: ------------------------------------
    [14:26:21]: --- Step: increment_build_number ---
    [14:26:21]: ------------------------------------
    [14:26:21]: [SHELL COMMAND]: cd /Users/emario/Documents/_Projects/BankDuLemon/iOS && agvtool next-version -all
    [14:26:21]: [SHELL]: Setting version of project BDL to:
    [14:26:21]: [SHELL]: 35.
    [14:26:21]: [SHELL]: 
    [14:26:21]: [SHELL]: Also setting CFBundleVersion key (assuming it exists)
    [14:26:21]: [SHELL]: 
    [14:26:21]: [SHELL]: Updating CFBundleVersion in Info.plist(s)...
    [14:26:21]: [SHELL]: 
    [14:26:21]: [SHELL]: Updated CFBundleVersion in "BDL.xcodeproj/../BDL WatchKit App/Info.plist" to 35
    [14:26:21]: [SHELL]: Updated CFBundleVersion in "BDL.xcodeproj/../BDL WatchKit Extension/Info.plist" to 35
    [14:26:21]: [SHELL]: Updated CFBundleVersion in "BDL.xcodeproj/../BDL/Info.plist" to 35
    [14:26:21]: [SHELL]: Updated CFBundleVersion in "BDL.xcodeproj/../BDLTests/Info.plist" to 35
    [14:26:21]: [SHELL]: 
    [14:26:21]: [SHELL]: 
    [14:26:22]: --------------------------------
    [14:26:22]: --- Step: get_version_number ---
    [14:26:22]: --------------------------------
    [14:26:22]: [SHELL COMMAND]: cd /Users/emario/Documents/_Projects/BankDuLemon/iOS && agvtool what-marketing-version -terse1
    [14:26:22]: [SHELL]: 1.0.2
    [14:26:22]: ------------------
    [14:26:22]: --- Step: sigh ---
    [14:26:22]: ------------------
    No username or password given. You can set environment variables:
    DELIVER_USER, DELIVER_PASSWORD
    -------------------------------------------------------------------------------------
    The login information you enter will be stored in your Mac OS Keychain
    More information about that on GitHub: https://github.com/fastlane/CredentialsManager
    -------------------------------------------------------------------------------------
    Username: <my email here>
    [14:26:45]: Starting login
    [14:26:45]: --------------------
    [14:26:45]: --- Step: notify ---
    [14:26:45]: --------------------
    [14:26:45]: Variable Dump:
    [14:26:45]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios accti8m", :BUILD_NUMBER=>"35", :VERSION_NUMBER=>"1.0.2"}
    [14:26:45]: No login data provided
    
    +------+-------------------------------------+-------------+
    |                     fastlane summary                     |
    +------+-------------------------------------+-------------+
    | Step | Action                              | Time (in s) |
    +------+-------------------------------------+-------------+
    | 1    | Verifying required fastlane version | 0           |
    | 2    | default_platform                    | 0           |
    | 3    | increment_build_number              | 1           |
    | 4    | get_version_number                  | 0           |
    | 5    | sigh                                | 22          |
    | 6    | notify                              | 0           |
    +------+-------------------------------------+-------------+
    
    [14:26:45]: fastlane finished with errors
    /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:149:in `login': No login data provided (Spaceship::Client::NoUserCredentialsError)
    	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:48:in `login'
    	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/portal/spaceship.rb:22:in `login'
    	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/portal/spaceship.rb:77:in `login'
    	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.6/lib/sigh/spaceship/runner.rb:11:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.6/lib/sigh/manager.rb:7:in `start'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/actions/sigh.rb:20:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:128:in `block in execute_action'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:127:in `chdir'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:127:in `execute_action'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/fast_file.rb:124:in `method_missing'
    	from (eval):60:in `block (3 levels) in parse'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/lane.rb:36:in `call'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/lane.rb:36:in `call'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:51:in `block in execute'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:46:in `chdir'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/runner.rb:46:in `execute'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/bin/fastlane:34:in `block (2 levels) in run'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/bin/fastlane:123:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.21.0/bin/fastlane:129:in `<top (required)>'
    	from /usr/bin/fastlane:23:in `load'
    	from /usr/bin/fastlane:23:in `<main>'
    ~/Documents/_Projects/BankDuLemon/iOS $

**Comment by KrauseFx** [comment]
Seems like it's the same issue as https://github.com/KrauseFx/sigh/issues/161

Did you try passing the Apple ID using environment variables? Each developer can then store the Apple ID to use in the `.bashsrc` to automatically fill-in the username.

**Comment by KrauseFx** [comment]
Sorry for the troubles, I'm working on a re-write on the credentials manager, as I'm aware there are some issues with certain setups.

**Comment by Yspadadden** [comment]
I did not try the env variable option. But I might look at it, if it becomes an issue. Right now, I'm the main guy who builds this particular project. It just would be nice, if it would work at some point in the future. But no hurry.

**Comment by superarts** [comment]
The only problem I found with .env is that when .env file is generated dynamically, the script that generates it needs to have the password stored as plain text, which is not ideal when we store that script in a source control repo. Guess I'll have to put the credential into another file that is not in the repo. Anyway I really hope local keychain works as expected since that should be the place to store things :)

**Comment by ohwutup** [comment]
Hey everyone, I am going to close this issue for now as it's been a while since there has been any activity. Please reopen the issue if any further problems come up and we will be happy to help! Thanks! :+1:
