### ISSUE TITLE
Ruby script execution fail (incompatible library version)

### ISSUE THREAD

**Issue by mlostekk** [fastlane/fastlane#5501]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am trying to execute a ruby script from within my fastfile with the line
`sh("ruby ../Beatsnap/Resources/Licenses/acknowledgementGenerator.rb Beatsnap/Settings.bundle/ Beatsnap/Resources/Licenses/")
`

But the script fails. Any idea what the reason might be? (Sorry, i am not familiar with the whole ruby ecosystem)

By the way, thats the script i am trying to execute from within the fastlane process

https://github.com/cvknage/iOS-AcknowledgementGenerator

##### Complete output when running fastlane, including the stack trace and command used

```
[23:13:55]: -------------------------------------------------
[23:13:55]: --- Step: Verifying required fastlane version ---
[23:13:55]: -------------------------------------------------
[23:13:55]: fastlane version valid
[23:13:55]: ------------------------------
[23:13:55]: --- Step: default_platform ---
[23:13:55]: ------------------------------
[23:13:55]: Driving the lane 'ios beta' 🚀
[23:13:55]: -----------------------
[23:13:55]: --- Step: cocoapods ---
[23:13:55]: -----------------------
[23:13:55]: $ pod install
[23:13:58]: ▸ Analyzing dependencies
[23:13:58]: ▸ Downloading dependencies
[23:13:58]: ▸ Using Bolts (1.7.0)
[23:13:58]: ▸ Using Crashlytics (3.7.2)
[23:13:58]: ▸ Using DGActivityIndicatorView (2.0)
[23:13:58]: ▸ Using FBSDKCoreKit (4.13.1)
[23:13:58]: ▸ Using FBSDKLoginKit (4.13.1)
[23:13:58]: ▸ Using Fabric (1.6.7)
[23:13:58]: ▸ Using KissXML (5.0.3)
[23:13:58]: ▸ Using Mixpanel (2.9.9)
[23:13:58]: ▸ Using QBImagePickerController (3.4.0)
[23:13:58]: ▸ Using SimulatorStatusMagic (1.8)
[23:13:58]: ▸ Generating Pods project
[23:14:00]: ▸ Integrating client project
[23:14:00]: ▸ Sending stats
[23:14:00]: ▸ Pod installation complete! There are 9 dependencies from the Podfile and 10 total pods installed.
[23:14:00]: ------------------------------------------------------------------------------------------------------------------------------------
[23:14:00]: --- Step: ruby ../Beatsnap/Resources/Licenses/acknowledgementGenerator.rb Beatsnap/Settings.bundle/ Beatsnap/Resources/Licenses/ ---
[23:14:00]: ------------------------------------------------------------------------------------------------------------------------------------
[23:14:00]: $ ruby ../Beatsnap/Resources/Licenses/acknowledgementGenerator.rb Beatsnap/Settings.bundle/ Beatsnap/Resources/Licenses/
[23:14:01]: ▸ /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /Library/Ruby/Gems/2.0.0/gems/libxml-ruby-2.9.0/lib/libxml_ruby.bundle (fatal)
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[23:14:01]: ▸ from /Library/Ruby/Gems/2.0.0/gems/libxml-ruby-2.9.0/lib/libxml.rb:8:in `rescue in <top (required)>'
[23:14:01]: ▸ from /Library/Ruby/Gems/2.0.0/gems/libxml-ruby-2.9.0/lib/libxml.rb:4:in `<top (required)>'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `require'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
[23:14:01]: ▸ from /Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.2/lib/cfpropertylist/rbLibXMLParser.rb:3:in `<top (required)>'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[23:14:01]: ▸ from /Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.2/lib/cfpropertylist/rbCFPropertyList.rb:98:in `<top (required)>'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[23:14:01]: ▸ from /Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.2/lib/CFPropertyList.rb:3:in `<top (required)>'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `require'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
[23:14:01]: ▸ from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
[23:14:01]: ▸ from ../Beatsnap/Resources/Licenses/acknowledgementGenerator.rb:51:in `<main>'
[23:14:01]: Variable Dump:
[23:14:01]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
[23:14:01]: Exit status of command 'ruby ../Beatsnap/Resources/Licenses/acknowledgementGenerator.rb Beatsnap/Settings.bundle/ Beatsnap/Resources/Licenses/' was 1 instead of 0.
/usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /Library/Ruby/Gems/2.0.0/gems/libxml-ruby-2.9.0/lib/libxml_ruby.bundle (fatal)
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/libxml-ruby-2.9.0/lib/libxml.rb:8:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/libxml-ruby-2.9.0/lib/libxml.rb:4:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.2/lib/cfpropertylist/rbLibXMLParser.rb:3:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.2/lib/cfpropertylist/rbCFPropertyList.rb:98:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.2/lib/CFPropertyList.rb:3:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from ../Beatsnap/Resources/Licenses/acknowledgementGenerator.rb:51:in `<main>'


+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | cocoapods                                                     | 4           |
| 4    | ruby ../Beatsnap/Resources/Licenses/acknowledgementGenerator. | 0           |
+------+---------------------------------------------------------------+-------------+

[23:14:01]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[23:14:01]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass

[!] Exit status of command 'ruby ../Beatsnap/Resources/Licenses/acknowledgementGenerator.rb Beatsnap/Settings.bundle/ Beatsnap/Resources/Licenses/' was 1 instead of 0.
/usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /Library/Ruby/Gems/2.0.0/gems/libxml-ruby-2.9.0/lib/libxml_ruby.bundle (fatal)
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/libxml-ruby-2.9.0/lib/libxml.rb:8:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/libxml-ruby-2.9.0/lib/libxml.rb:4:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.2/lib/cfpropertylist/rbLibXMLParser.rb:3:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.2/lib/cfpropertylist/rbCFPropertyList.rb:98:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.2/lib/CFPropertyList.rb:3:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from ../Beatsnap/Resources/Licenses/acknowledgementGenerator.rb:51:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.98.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods    
  end

desc "Build and distribute build to Crashlytics"
  lane :beta do
    # Generate acknowledgements
    sh("ruby ../Beatsnap/Resources/Licenses/acknowledgementGenerator.rb Beatsnap/Settings.bundle/ Beatsnap/Resources/Licenses/")
  end

end

```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.98.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by TKBurner** [comment]
Hi @mlostekk It looks like you are using ruby 2.0 can you upgrade (using RVM) to 2.3? I want to see if you are still affected by this issue. Thanks!

**Comment by mlostekk** [comment]
Ah! Thanks, using RVM with ruby 2.3 fixed all issues! Thanks and keep up the awesome work!
