### ISSUE TITLE
xcexport: `export_options_to_plist': [!] undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by hironytic** [fastlane/fastlane#5571]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

An error occurs on `xcexport` action with `export_options_plist` parameter which has no `manifest` value.

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane ios release
[07:17:52]: -------------------------------------------------
[07:17:52]: --- Step: Verifying required fastlane version ---
[07:17:52]: -------------------------------------------------
[07:17:52]: fastlane version valid
[07:17:52]: ------------------------------
[07:17:52]: --- Step: default_platform ---
[07:17:52]: ------------------------------
[07:17:52]: Driving the lane 'ios release' 🚀
[07:17:52]: -----------------------
[07:17:52]: --- Step: xcarchive ---
[07:17:52]: -----------------------
[07:17:52]: For a more detailed xcodebuild log open /Users/ichi/Library/Logs/fastlane/xcbuild/2016-08-02/5528/xcodebuild.log
[07:17:52]: $ set -o pipefail && xcodebuild -sdk "iphoneos" archive -scheme "AppExp10" -project "AppExp10.xcodeproj" -archivePath "_build/AppExp10.xcarchive" | tee '/Users/ichi/Library/Logs/fastlane/xcbuild/2016-08-02/5528/xcodebuild.log' | xcpretty --color --simple
[07:17:52]: ▸ Building AppExp10/AppExp10 [Release]
[07:17:52]: ▸ Check Dependencies
[07:17:53]: ▸ Compiling ViewController.swift
[07:17:53]: ▸ Compiling AppDelegate.swift
[07:17:53]: ▸ Compiling ViewController.swift
[07:17:54]: ▸ Compiling AppDelegate.swift
[07:17:54]: ▸ Linking AppExp10
[07:17:54]: ▸ Linking AppExp10
[07:17:54]: ▸ Compiling Main.storyboard
[07:17:56]: ▸ Compiling LaunchScreen.storyboard
[07:17:56]: ▸ Processing Info.plist
[07:17:56]: ▸ Generating 'AppExp10.app.dSYM'
[07:17:56]: ▸ Touching AppExp10.app
[07:18:00]: ▸ Signing /Users/ichi/Library/Developer/Xcode/DerivedData/AppExp10-coeziwmjgtvbiaezsiyubmmfaybj/Build/Intermediates/ArchiveIntermediates/AppExp10/InstallationBuildProductsLocation/Applications/AppExp10.app
[07:18:00]: ▸ Touching AppExp10.app.dSYM
[07:18:01]: ▸ Archive Succeeded
[07:18:01]: ----------------------
[07:18:01]: --- Step: xcexport ---
[07:18:01]: ----------------------
[07:18:01]: Variable Dump:
[07:18:01]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios release", :XCODEBUILD_DERIVED_DATA_PATH=>nil, :XCODEBUILD_ARCHIVE=>"_build/AppExp10.xcarchive", :IPA_OUTPUT_PATH=>"_build/export.ipa"}
[07:18:01]: undefined method `[]' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | xcarchive                           | 9           |
| 4    | xcexport                            | 0           |
+------+-------------------------------------+-------------+

[07:18:01]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  External testflight: undefined method `[]' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/5394 [closed] 6 💬
   5 days ago

➡️  Pilot tool is crashing with undefined method 'strip' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/3238 [open] 0 💬
   08 Mar 2016

➡️  spaceship/base.rb:43:in `lookup': undefined method `[]' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/2055 [open] 0 💬
   07 Mar 2016

and 144 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]'%20for%20nil&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/xcodebuild.rb:283:in `export_options_to_plist': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/xcodebuild.rb:140:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/xcodebuild.rb:472:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:177:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:18:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:248:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.99.0"

default_platform :ios

platform :ios do
  before_all do
    ENV['XCODE_PROJECT'] = 'AppExp10.xcodeproj'
    ENV['XCODE_SCHEME'] = 'AppExp10'
    ENV['XCODE_BUILD_PATH'] = '_build'
  end

  desc "Archive and export"
  lane :release do
    xcarchive(
      sdk: 'iphoneos',
    )
    
    xcexport(
      export_path: File.join(ENV['XCODE_BUILD_PATH'], 'export'),
      export_options_plist: {
        method: 'app-store',
        uploadSymbols: true,
      }
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Yes; rbenv

**Comment by KrauseFx** [comment]
Instead of using `xcarchive` and `xcexport` we recommend using [gym](https://fastlane.tools/gym) which makes it much easier to build and sign your app 👍

**Comment by hironytic** [comment]
Hi, this is a small example that can reproduce the problem.
In our actual project, we are using one `xcarchive` and two `xcexport`s from same archive, for ad-hoc and for app-store. Is it possible by using gym?

**Comment by KrauseFx** [comment]
Yeah, this should work in gym 👍 You want to create an ipa file, right?

**Comment by hironytic** [comment]
I want to create one xcarchive file and two ipa files from it.

**Comment by hironytic** [comment]
No matter whether I use gym or not, this problem should be fixed. I made a PR :sparkles:
