### ISSUE TITLE
[BUG] Segmentation fault

### ISSUE THREAD

**Issue by wuaschtikus** [fastlane/fastlane#5579]
##### Complete output when running fastlane, including the stack trace and command used

```
user@eopc-x016:/Volumes/ProjectsCaseSensitive/Mia-ios-app-network/fastlane$ fastlane
/Users/user/.gem/gems/json-2.0.2/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0023 p:-17560233796770 s:0104 e:000103 TOP    [FINISH]
c:0022 p:---- s:0102 e:000101 CFUNC  :require
c:0021 p:0196 s:0098 e:000097 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73
c:0020 p:0009 s:0088 e:000087 CLASS  /Users/user/.gem/gems/json-2.0.2/lib/json/ext.rb:7
c:0019 p:0011 s:0086 e:000085 CLASS  /Users/user/.gem/gems/json-2.0.2/lib/json/ext.rb:6
c:0018 p:0017 s:0084 e:000083 TOP    /Users/user/.gem/gems/json-2.0.2/lib/json/ext.rb:3 [FINISH]
c:0017 p:---- s:0082 e:000081 CFUNC  :require
c:0016 p:0196 s:0078 e:000077 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73
c:0015 p:0019 s:0068 e:000067 CLASS  /Users/user/.gem/gems/json-2.0.2/lib/json.rb:59
c:0014 p:0017 s:0066 e:000065 TOP    /Users/user/.gem/gems/json-2.0.2/lib/json.rb:55 [FINISH]
c:0013 p:---- s:0064 e:000063 CFUNC  :require
c:0012 p:0196 s:0060 e:000059 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73
c:0011 p:0007 s:0050 e:000049 TOP    /Users/user/.gem/gems/fastlane_core-0.48.3/lib/fastlane_core.rb:1 [FINISH]
c:0010 p:---- s:0048 e:000047 CFUNC  :require
c:0009 p:0196 s:0044 e:000043 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73
c:0008 p:0007 s:0034 e:000033 TOP    /Users/user/.gem/gems/fastlane-1.99.0/lib/fastlane.rb:1 [FINISH]
c:0007 p:---- s:0032 e:000031 CFUNC  :require
c:0006 p:0196 s:0028 e:000027 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73
c:0005 p:0022 s:0018 e:000017 METHOD /Users/user/.gem/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb:10
c:0004 p:0041 s:0012 e:000011 TOP    /Users/user/.gem/gems/fastlane-1.99.0/bin/fastlane:5 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0118 s:0006 E:0023f8 EVAL   /Users/user/.gem/ruby/2.0.0/bin/fastlane:23 [FINISH]
c:0001 p:0000 s:0002 E:000188 TOP    [FINISH]

/Users/user/.gem/ruby/2.0.0/bin/fastlane:23:in `<main>'
/Users/user/.gem/ruby/2.0.0/bin/fastlane:23:in `load'
/Users/user/.gem/gems/fastlane-1.99.0/bin/fastlane:5:in `<top (required)>'
/Users/user/.gem/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb:10:in `take_off'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/user/.gem/gems/fastlane-1.99.0/lib/fastlane.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/user/.gem/gems/fastlane_core-0.48.3/lib/fastlane_core.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/user/.gem/gems/json-2.0.2/lib/json.rb:55:in `<top (required)>'
/Users/user/.gem/gems/json-2.0.2/lib/json.rb:59:in `<module:JSON>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/user/.gem/gems/json-2.0.2/lib/json/ext.rb:3:in `<top (required)>'
/Users/user/.gem/gems/json-2.0.2/lib/json/ext.rb:6:in `<module:JSON>'
/Users/user/.gem/gems/json-2.0.2/lib/json/ext.rb:7:in `<module:Ext>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: /Users/user/.gem/ruby/2.0.0/bin/fastlane

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
    5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
    6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
    7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
    8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
    9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
   10 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/platform.rb
   11 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb
   12 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/exceptions.rb
   13 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   14 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   16 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   17 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
   18 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/path_support.rb
   20 /Users/user/.gem/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb
   21 /Users/user/.gem/gems/json-2.0.2/lib/json/version.rb
   22 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/ostruct.rb
   23 /Users/user/.gem/gems/json-2.0.2/lib/json/generic_object.rb
   24 /Users/user/.gem/gems/json-2.0.2/lib/json/common.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

### Environment

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by wuaschtikus** [comment]
Installing RVM resolved the problem.

**Comment by TKBurner** [comment]
@wuaschtikus Awesome! Really glad to hear you got up and running 👍
