### ISSUE TITLE
Generic error: [!] The request could not be completed because: Unexpected Error (I suspect it's due to user error.)

### ISSUE THREAD

**Issue by brockklein** [fastlane/fastlane#5594]
### New Issue Checklist

- [1.99.0] Updated fastlane to the latest version
- [ Yup!] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hello all, first time posting an issue here, but long time follower. 

I finally sat down and tried to set myself up to take full advantage of Fastlane's features for our setup. After powering through quite a few syntax/configuration mistakes I'm stuck on this last one.

Every command on every lane is working great except the final submission - I suspect I'm failing to account for something (been mainly using my `minor_update` lane).

Details below - any help would be greatly appreciated! (And hopefully if anyone else has made whatever mistake I did will benefit from this post.)

[report.xml.zip](https://github.com/fastlane/fastlane/files/399327/report.xml.zip)

##### Complete output when running fastlane, including the stack trace and command used

```
[07:18:37]: Variable Dump:
[07:18:37]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios retry_submit", :VERSION_NUMBER=>"1.5.0", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/brockklein/dev/Legit Apps/Event-Cast-iOS/Event Cast iOS.ipa", :DSYM_OUTPUT_PATH=>"/Users/brockklein/dev/Legit Apps/Event-Cast-iOS/Event Cast iOS.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/brockklein/Library/Developer/Xcode/Archives/2016-08-03/Event Cast iOS 2016-08-03 06.55.51.xcarchive"}
[07:18:37]: Unexpected Error

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | set_info_plist_value                | 0           |
| 4    | set_info_plist_value                | 0           |
| 5    | set_info_plist_value                | 0           |
| 6    | set_info_plist_value                | 0           |
| 7    | set_info_plist_value                | 0           |
| 8    | set_info_plist_value                | 0           |
| 9    | set_info_plist_value                | 0           |
| 10   | get_version_number                  | 0           |
| 11   | slack                               | 0           |
| 12   | match                               | 21          |
| 13   | gym                                 | 298         |
| 14   | deliver                             | 1067        |
| 15   | slack                               | 1           |
+------+-------------------------------------+-------------+

[07:18:37]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Can `deliver` detect when an app is pending developer release?
   https://github.com/fastlane/fastlane/issues/5261 [open] 3 💬
   5 weeks ago

➡️  Test failed. Exit status: 65
   https://github.com/fastlane/fastlane/issues/1679 [closed] 30 💬
   07 Jun 2016


[!] The request could not be completed because:
	Unexpected Error
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Deliverfile:
```ruby
###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/KrauseFx/deliver/blob/master/Deliverfile.md


###################### Automatically generated ######################
# Feel free to remove the following line if you use fastlane (which you should)

# app_identifier "com.legitapps.iu" # The bundle identifier of your app
# username "my apple id" # your Apple ID user

app_review_information(
  first_name: "Brock",
  last_name: "Klein",
  phone_number: "cellnumber",
  email_address: "info@legitapps.com",
  demo_user: '',
  demo_password: '',
  notes: ''
)

submission_information({
   add_id_info_serves_ads: false,
   add_id_info_limits_tracking: false,
   add_id_info_tracks_action: true,
   add_id_info_tracks_install: true,
   add_id_info_uses_idfa: true,
   content_rights_contains_third_party_content: false,
   content_rights_has_rights: false,
   export_compliance_available_on_french_store: false,
   export_compliance_ccat_file: false,
   export_compliance_contains_proprietary_cryptography: false,
   export_compliance_is_exempt: false,
   export_compliance_uses_encryption: false,
   export_compliance_encryption_updated: false,
   export_compliance_compliance_required: false
})


automatic_release true

app_rating_config_path "./fastlane/ratings.json"

submit_for_review true

price_tier 0

app_icon "./fastlane/icon.png"

copyright "#{Time.now.year} Legit Apps, LLC"

release_notes({
  'default' => "App version updated.",
  'en-US' => "Updated app version."
})

# Contents of ratings.json.
# ({
# 	  CARTOON_FANTASY_VIOLENCE: 0,
# 	  REALISTIC_VIOLENCE: 0,
# 	  PROLONGED_GRAPHIC_SADISTIC_REALISTIC_VIOLENCE: 0,
# 	  PROFANITY_CRUDE_HUMOR: 0,
# 	  MATURE_SUGGESTIVE: 0,
# 	  HORROR: 0,
# 	  MEDICAL_TREATMENT_INFO: 0,
# 	  ALCOHOL_TOBACCO_DRUGS: 0,
# 	  GAMBLING: 0,
# 	  SEXUAL_CONTENT_NUDITY: 0,
# 	  GRAPHIC_SEXUAL_CONTENT_NUDITY: 0,
# 	  UNRESTRICTED_WEB_ACCESS: 0,
# 	  GAMBLING_CONTESTS: 0
# 	})
```

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "slackUrl" 

    @plist_path = "Event Cast iOS/Info.plist"
    
    @user                  = 'my Apple ID'

    @bundle_id             = 'com.legitapps.uw'
    @app_name              = 'University of Washington New Huskies' 
    @display_name          = 'New Huskies'
    @app_id                = '105'
    @primary_color         = '#330070'
    @status_bar_color      = '#330070'
    @flurry_ios_id         = 'id'
    @one_signal_app_id     = 'id'


    # update_info_plist(
    #   plist_path: plist_path,
    #   display_name: display_name
    # )


    desc "Setting bundle ID"
    set_info_plist_value(path: @plist_path, key: 'CFBundleIdentifier',   value: @bundle_id)
    desc "Setting bundle display name"
    set_info_plist_value(path: @plist_path, key: 'CFBundleDisplayName',  value: @display_name)
    desc "Setting App ID"
    set_info_plist_value(path: @plist_path, key: 'App ID',               value: @app_id)
    desc "Setting primary color"
    set_info_plist_value(path: @plist_path, key: 'Main Color',           value: @primary_color)
    desc "Setting status bar color"
    set_info_plist_value(path: @plist_path, key: 'Status Bar Color',     value: @status_bar_color)
    desc "Setting Flurry App ID"
    set_info_plist_value(path: @plist_path, key: 'Flurry App ID',        value: @flurry_ios_id)
    desc "Setting One Signal App ID"
    set_info_plist_value(path: @plist_path, key: 'OneSignal App ID',     value: @one_signal_app_id)


    # increment_build_number
    # xctool # run the tests of your app
  end

  desc "Installs FixCode which disables the \"Fix Issue\" button in Xcode"
  lane :xcode do
    install_xcode_plugin(
      url: "https://github.com/fastlane/FixCode/releases/download/0.2.0/FixCode.xcplugin.zip"
    )
  end

  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    match(app_identifier: @bundle_id, type: "appstore", username: @user)
    match(app_identifier: @bundle_id, type: "development", username: @user)
  end

  desc "Prepare for screenshots."
  lane :set_app do
    # Don't need to do anything - just need to trigger the before_all settings updates.
  end 


  desc "Submit new app."
  lane :new do
    slack(
      message: "#{@app_name}: starting new app submission.",
      default_payloads: [] # reduce the notification to the minimum
    )

    produce(
      username: @user,
      app_identifier: @bundle_id,
      app_name: @app_name,
      language: 'English',
      app_version: '1.0.0'
    )

    match(app_identifier: @bundle_id, type: "appstore", username: @user)
    pem(app_identifier: @bundle_id, username: @user)
    gym(scheme: 'Event Cast iOS')

    deliver(
      username: @user,
      app_identifier: @bundle_id
    )

  end

  desc "Update existing app with minor update."
  lane :minor_update do

    version = increment_version_number(bump_type: "minor")

    slack(
      message: "#{@app_name}: starting minor update v#{version}.",
      default_payloads: [] # reduce the notification to the minimum
    )

    match(app_identifier: @bundle_id, type: "appstore", username: @user)
    gym(scheme: 'Event Cast iOS')

    deliver(
      force: true,
      username: @user
      )

  end

  desc "Update existing app wth major update."
  lane :major_update do

    version = increment_version_number(bump_type: "major")

    slack(
      message: "#{@app_name}: starting minor update v#{version}.",
      default_payloads: [] # reduce the notification to the minimum
    )

    match(app_identifier: @bundle_id, type: "appstore", username: @user)
    gym(scheme: 'Event Cast iOS')

    deliver(
      force: true,
      username: @user
      )

  end

  desc "Update existing app wth major update."
  lane :retry_submit do

    slack(
      message: "#{@app_name}: retrying submit for v#{get_version_number}.",
      default_payloads: [] # reduce the notification to the minimum
    )

    match(app_identifier: @bundle_id, type: "appstore", username: @user)
    gym(scheme: 'Event Cast iOS')

    deliver(
      force: true,
      username: @user
      )

  end


  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sigh
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    # snapshot
    sigh
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    slack(
      message: "#{@app_name}: successfully deployed v#{get_version_number}.",
      success: true
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

```

### Environment

fastlane version (run `fastlane -v`): **1.99.0**

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **I am not - should I?**

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **Using `rvm` system ruby (which is where I keep my Fastlane install).**

**Comment by brockklein** [comment]
Also, to clarify what my project state is after receiving this error: I am able to go into iTunesConnect, hit Submit, testify that I'm not encrypting(etc.) and everything works like a charm.

So I assume the problem is at the very end in the submit function of `deliver`/`spaceship`, but I am at a loss how to troubleshoot it.

**Comment by brockklein** [comment]
And that suspicion is now confirmed...here is the error output from running `fastlane retry_submit --verbose`.

```
WARN [2016-08-03 08:36:10.68]: Variable Dump:
INFO [2016-08-03 08:36:10.68]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios retry_submit", :VERSION_NUMBER=>"1.0", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/brockklein/dev/Legit Apps/Event-Cast-iOS/Event Cast iOS.ipa", :DSYM_OUTPUT_PATH=>"/Users/brockklein/dev/Legit Apps/Event-Cast-iOS/Event Cast iOS.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/brockklein/Library/Developer/Xcode/Archives/2016-08-03/Event Cast iOS 2016-08-03 08.14.22.xcarchive"}
ERROR [2016-08-03 08:36:10.68]: Unexpected Error
INFO [2016-08-03 08:36:10.68]: Successfully generated documentation to path '/Users/brockklein/dev/Legit Apps/Event-Cast-iOS/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | set_info_plist_value                | 0           |
| 4    | set_info_plist_value                | 0           |
| 5    | set_info_plist_value                | 0           |
| 6    | set_info_plist_value                | 0           |
| 7    | set_info_plist_value                | 0           |
| 8    | set_info_plist_value                | 0           |
| 9    | set_info_plist_value                | 0           |
| 10   | get_version_number                  | 0           |
| 11   | slack                               | 1           |
| 12   | match                               | 42          |
| 13   | gym                                 | 303         |
| 14   | deliver                             | 1005        |
| 15   | slack                               | 0           |
+------+-------------------------------------+-------------+

ERROR [2016-08-03 08:36:10.68]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Unexpected Error

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Unexpected%20Error+repo:fastlane/fastlane
➡️  Generic error: [!] The request could not be completed because: Unexpected Error (I suspect it's due to user error.)
   https://github.com/fastlane/fastlane/issues/5594 [open] 1 💬
   an hour ago

➡️  Can `deliver` detect when an app is pending developer release?
   https://github.com/fastlane/fastlane/issues/5261 [open] 3 💬
   5 weeks ago

➡️  Test failed. Exit status: 65
   https://github.com/fastlane/fastlane/issues/1679 [closed] 30 💬
   07 Jun 2016

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.29.1/lib/spaceship/tunes/tunes_client.rb:180:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	Unexpected Error
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.29.1/lib/spaceship/tunes/tunes_client.rb:698:in `send_app_submission'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_submission.rb:127:in `complete!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.13.1/lib/deliver/submit_for_review.rb:25:in `submit!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.13.1/lib/deliver/runner.rb:87:in `submit_for_review'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.13.1/lib/deliver/runner.rb:30:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:177:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:163:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.49.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:248:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Interesting, basically you get the message `Unexpected Error` from iTunes Connect directly, it's not raised by `fastlane` or `spaceship` as far as I can see. Does the same happen when you try do to it manually on iTunes Connect?

**Comment by brockklein** [comment]
@KrauseFx huh, oddly, no I have not encountered that error on iTunesConnect itself. 

We're in the process of publishing/updating about 40 apps for clients and I've done about 15 using the Fastlane config above. For every single one Fastlane works its beautiful magic and all I have to do is log in to iTunes Connect, hit submit, answer the three (or two) encryption/ads questions and I'm done. (Fastlane even successfully waits for the build to be done processing and adds it to the version on iTunes Connect.)

I have not encountered that `Unexpected Error` from iTunes Connect on any of them when I have gone to do that last step.

**Comment by brockklein** [comment]
I see now how I should have been able to see that the error was from iTunes Connect via 

`/Library/Ruby/Gems/2.0.0/gems/spaceship-0.29.1/lib/spaceship/tunes/tunes_client.rb:180:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)`

**Comment by brockklein** [comment]
Confirmed this was indeed user error. In my `deliverfile` (above) I was doing this:

```
content_rights_contains_third_party_content: false,
content_rights_has_rights: false,
```

in the `submission_information` section.

Apparently iTunes doesn't like it when you say you don't use third party content and then tell it that you don't have rights to that content...that you don't use.

So I left `content_rights_contains_third_party_content` as `false` but set `content_rights_has_rights` as `true`...essentially testifying that we have the rights to the nonexistent third party content that we don't use. 

Either way, no more `Unexpected error`!

**Comment by TKBurner** [comment]
@brockklein Awesome! So glad to hear you got up and running. Hope you have a great week!
