### ISSUE TITLE
cannot load such file -- fastlane_core

### ISSUE THREAD

**Issue by LyubomirDominik** [fastlane/fastlane#5607]
**Can someone suggest me how to fix this?**

If I run `fastlane test` from terminal - everything is okay, but I have os x server which run shell script with same command and it results with this errors: 

```
`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fastlane_core (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/bodyabilas/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-1.99.0/lib/fastlane.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/bodyabilas/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb:10:in `take_off'
	from /Users/bodyabilas/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-1.99.0/bin/fastlane:5:in `<main>'`
```

**Comment by romanr** [comment]
How did you fix this?
