### ISSUE TITLE
pilot fails to upload with ERROR ITMS-90055: "This bundle is invalid"

### ISSUE THREAD

**Issue by lakamsani** [fastlane/fastlane#5623]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
unable to upload via pilot

##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2016-08-06 01:17:32.56]: Successfully exported and compressed dSYM file
INFO [2016-08-06 01:17:32.56]: Successfully exported and signed the ipa file:
INFO [2016-08-06 01:17:32.56]: /Users/me/Development/company/company-ios/archives/MyApp.ipa
INFO [2016-08-06 01:17:32.59]: -------------------
INFO [2016-08-06 01:17:32.59]: --- Step: pilot ---
INFO [2016-08-06 01:17:32.59]: -------------------
INFO [2016-08-06 01:17:32.67]: Login to iTunes Connect (me@company.com)
INFO [2016-08-06 01:17:34.77]: Login successful
DEBUG [2016-08-06 01:17:34.78]: App identifier (com.company.MyApp)
INFO [2016-08-06 01:17:35.05]: Ready to upload new build to TestFlight (App: 1141640905)...
INFO [2016-08-06 01:17:35.87]: Wrote XML data to '/tmp/1141640905.itmsp'
INFO [2016-08-06 01:17:35.93]: Going to upload updated app to iTunes Connect
INFO [2016-08-06 01:17:35.93]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2016-08-06 01:17:36.00]: /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -classpath /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/lib/itmstransporter-launcher.jar com.apple.transporter.Application -m upload -u me@company.com -p YourPassword -f /tmp/1141640905.itmsp -t Signiant -k 100000 2>&1
DEBUG [2016-08-06 01:17:38.84]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
DEBUG [2016-08-06 01:17:39.02]: [Transporter]: INFO: Logging configured successfully.
DEBUG [2016-08-06 01:17:39.02]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2016-08-06 01:17:39.05]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2016-08-06 01:17:39.05]: [Transporter]: DEBUG: Saving configuration to local path: /Users/me/.itmstransporter/Defaults.properties
DEBUG [2016-08-06 01:17:39.05]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.8.9]
DEBUG [2016-08-06 01:17:39.05]: [Transporter]: INFO: OS identifier: Mac OS X 10.11.6 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-08-06 01:17:39.05]: [Transporter]: INFO: Memory: [JVM] 853M free, 982M total, 982M max [System] (Physical) 62M free, 16384M total (Swap) 1297M free, 5120M total
DEBUG [2016-08-06 01:17:39.05]: [Transporter]: INFO: Upload mode selected.
DEBUG [2016-08-06 01:17:39.07]: [Transporter]: INFO: Examining the package at: /tmp/1141640905.itmsp
DEBUG [2016-08-06 01:17:39.07]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
DEBUG [2016-08-06 01:17:39.07]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
DEBUG [2016-08-06 01:17:39.07]: [Transporter]: INFO: Gathering the list of valid files from the package ...
DEBUG [2016-08-06 01:17:39.07]: [Transporter]: DEBUG:   f6ead5de94dc8ff3f41a0a65ca182cb7.ipa will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2016-08-06 01:17:39.07]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2016-08-06 01:17:39.07]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
DEBUG [2016-08-06 01:17:39.07]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: INFO: Performing authentication of package 1141640905.itmsp ...
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X: Memory: [JVM] 843M free, 982M total, 982M max [System] (Physical) 62M free, 16384M total (Swap) 1297M free, 5120M total
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X: Memory: [JVM] 843M free, 982M total, 982M max [System] (Physical) 62M free, 16384M total (Swap) 1297M free, 5120M total
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.8
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.6 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X:   parameter Password = **hidden value**
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u me@company.com -p **hidden value** -f /tmp/1141640905.itmsp -t Signiant -k 100000
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X:   parameter Username = me@company.com
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X:   parameter Version = 1.8.9
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-08-06 01:17:39.12]: [Transporter]: INFO: id = 20160806011739-337
DEBUG [2016-08-06 01:17:39.42]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2016-08-06 01:17:39.42]: [Transporter]: DBG-X:   parameter SessionId = CIinDBIQDOcoe1BkSn+f6D5vBHA0Vg==
DEBUG [2016-08-06 01:17:39.42]: [Transporter]: DBG-X:   parameter SharedSecret = 3466bbb1-4d5c-4522-8ae3-1b32eb9e8452
DEBUG [2016-08-06 01:17:39.42]: [Transporter]: DBG-X: Deflated 453 bytes to 392
DEBUG [2016-08-06 01:17:39.42]: [Transporter]: DBG-X: Using operation named: validateMetadata
DEBUG [2016-08-06 01:17:39.42]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-08-06 01:17:39.42]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-08-06 01:17:39.42]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.8
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter Files = [f6ead5de94dc8ff3f41a0a65ca182cb7.ipa, metadata.xml]
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter MetadataChecksum = 832687a4a52ccf8ffec0749e56f08de0
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.6 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter PackageName = 1141640905.itmsp
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter PackageSize = 118690461
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u me@company.com -p **hidden value** -f /tmp/1141640905.itmsp -t Signiant -k 100000
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter Username = me@company.com
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter Version = 1.8.9
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-08-06 01:17:39.43]: [Transporter]: INFO: id = 20160806011739-229
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: DBG-X:   parameter CPUToken = 1c49e08a-815f-45c6-96d1-4f30a230de0b/1470471459838
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=f6ead5de94dc8ff3f41a0a65ca182cb7.ipa}]
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: DBG-X:   parameter FileSizes = {f6ead5de94dc8ff3f41a0a65ca182cb7.ipa=118690008}
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: DBG-X:   parameter Checksums = {f6ead5de94dc8ff3f41a0a65ca182cb7.ipa=5d2a535eae675c47c465c6e5c39e8e44}
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: DBG-X:   parameter Success = true
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, f6ead5de94dc8ff3f41a0a65ca182cb7.ipa]
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: DBG-X:   parameter ProviderNameForToken = PJGF3TV7MA
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: INFO: The list of files requested for upload by Apple is: [metadata.xml, f6ead5de94dc8ff3f41a0a65ca182cb7.ipa].  These are the files that will be uploaded.
DEBUG [2016-08-06 01:17:40.07]: [Transporter]: INFO: Starting media analysis of assets
DEBUG [2016-08-06 01:17:40.52]: [Transporter]: DEBUG: Handling asset: filename=f6ead5de94dc8ff3f41a0a65ca182cb7.ipa,uti=com.apple.ipa,role=source,describe=true
DEBUG [2016-08-06 01:17:40.52]: [Transporter]: DEBUG: Using container type tool name and version: iOS App Describer:1.24
DEBUG [2016-08-06 01:17:40.52]: [Transporter]: DEBUG: Using path: /tmp/1141640905.itmsp/f6ead5de94dc8ff3f41a0a65ca182cb7.ipa
DEBUG [2016-08-06 01:18:19.82]: [Transporter]: DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@7296c1fc
DEBUG [2016-08-06 01:18:20.21]: [Transporter]: DBG-X: Deflated 5973373 bytes to 1118681
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: INFO: Asset media analysis has completed
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X: Memory: [JVM] 894M free, 982M total, 982M max [System] (Physical) 285M free, 16384M total (Swap) 1297M free, 5120M total
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X: Using operation named: lookupTransportDiagnostic
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.8
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.6 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u me@company.com -p **hidden value** -f /tmp/1141640905.itmsp -t Signiant -k 100000
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X:   parameter Username = me@company.com
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X:   parameter Version = 1.8.9
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-08-06 01:18:20.23]: [Transporter]: INFO: id = 20160806011820-886
DEBUG [2016-08-06 01:18:22.03]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2016-08-06 01:18:22.03]: [Transporter]: DBG-X:   parameter SigniantLoggingLevel = OFF
DEBUG [2016-08-06 01:18:22.03]: [Transporter]: DBG-X:   parameter AsperaLoggingLevel = OFF
DEBUG [2016-08-06 01:18:22.08]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
DEBUG [2016-08-06 01:18:22.09]: [Transporter]: INFO: Using Signiant UDP transport
DEBUG [2016-08-06 01:18:22.09]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
DEBUG [2016-08-06 01:18:22.09]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
DEBUG [2016-08-06 01:18:22.09]: [Transporter]: INFO: Transfer engine: 10.6.0.59156
DEBUG [2016-08-06 01:18:22.10]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2016-08-06 01:18:22.13]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
DEBUG [2016-08-06 01:18:22.13]: [Transporter]: INFO: Processing URL list: mxwan://sgr206.apple.com:44001/
DEBUG [2016-08-06 01:18:22.13]: [Transporter]: INFO: Trying UDP sgr206.apple.com/17.152.249.106:44001...
DEBUG [2016-08-06 01:18:23.21]: [Transporter]: INFO: Connected to UDP sgr206.apple.com/17.152.249.106:44001
DEBUG [2016-08-06 01:18:23.27]: [Transporter]: INFO: Authenticating
DEBUG [2016-08-06 01:18:23.54]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
DEBUG [2016-08-06 01:18:23.54]: [Transporter]: INFO: Setting up data streams
DEBUG [2016-08-06 01:18:24.10]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTED
DEBUG [2016-08-06 01:18:24.10]: [Transporter]: INFO: Connected using WAN accelerator
DEBUG [2016-08-06 01:18:24.18]: [Transporter]: INFO:      File: cac0094a-6b27-4063-98ec-8a48fde9a12c3784683589648022871.txt 11/11, 100% completed
DEBUG [2016-08-06 01:18:24.20]: [Transporter]: DBG-X: The status for the file, cac0094a-6b27-4063-98ec-8a48fde9a12c3784683589648022871.txt, is TRANSFERRED.
DEBUG [2016-08-06 01:18:24.36]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2016-08-06 01:18:24.52]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2016-08-06 01:18:24.59]: [Transporter]: DEBUG: Using token file path /Users/me/.itmstransporter/UploadTokens/me-mb_PJGF3TV7MA_1141640905.itmsp.token
DEBUG [2016-08-06 01:18:24.59]: [Transporter]: DEBUG: Attempting exclusive file lock on token file
DEBUG [2016-08-06 01:18:24.59]: [Transporter]: DEBUG: Token exists, examining
DEBUG [2016-08-06 01:18:24.67]: [Transporter]: DEBUG: Token pid: 2607, found process = false; my pid: 18805
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DEBUG: Reusing existing token: ad257e2c-8fcf-4101-9a0d-d26662d75c98/1470470353564
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DEBUG: Set token: ad257e2c-8fcf-4101-9a0d-d26662d75c98/1470470353564
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X: Memory: [JVM] 937M free, 982M total, 982M max [System] (Physical) 199M free, 16384M total (Swap) 1297M free, 5120M total
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X: Deflated 453 bytes to 392
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X: Using operation named: validateAssets
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.8
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter CPUToken = ad257e2c-8fcf-4101-9a0d-d26662d75c98/1470470353564
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter Files = [f6ead5de94dc8ff3f41a0a65ca182cb7.ipa, metadata.xml]
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter MetadataChecksum = 832687a4a52ccf8ffec0749e56f08de0
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.6 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter PackageName = 1141640905.itmsp
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter PackageSize = 118690461
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter Transport = Signiant
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u me@company.com -p **hidden value** -f /tmp/1141640905.itmsp -t Signiant -k 100000
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter Username = me@company.com
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter Version = 1.8.9
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-08-06 01:18:24.75]: [Transporter]: INFO: id = 20160806011824-494
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter ErrorMessage = ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.company.MyApp'. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect.
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter CPUToken = ad257e2c-8fcf-4101-9a0d-d26662d75c98/1470470353564
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=f6ead5de94dc8ff3f41a0a65ca182cb7.ipa}]
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter FileSizes = {f6ead5de94dc8ff3f41a0a65ca182cb7.ipa=118690008}
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter Checksums = {f6ead5de94dc8ff3f41a0a65ca182cb7.ipa=5d2a535eae675c47c465c6e5c39e8e44}
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter Errors = [ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.company.MyApp'. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."]
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter ErrorCode = 1102
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter Success = false
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, f6ead5de94dc8ff3f41a0a65ca182cb7.ipa]
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
ERROR [2016-08-06 01:18:39.91]: [Transporter Error Output]: ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.company.MyApp'. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: DBG-X: The error code is: 1102
DEBUG [2016-08-06 01:18:39.91]: [Transporter]: INFO: Done performing authentication.
ERROR [2016-08-06 01:18:40.02]: Transporter transfer failed.
WARN [2016-08-06 01:18:40.02]:
ERROR [2016-08-06 01:18:40.02]: ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.company.MyApp'. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
ERROR [2016-08-06 01:18:40.09]: ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.company.MyApp'. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
Return status of iTunes Transporter was 1: ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.company.MyApp'. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
WARN [2016-08-06 01:18:40.11]: Variable Dump:
INFO [2016-08-06 01:18:40.11]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios tf", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/me/Development/company/company-ios/archives/MyApp.ipa", :DSYM_OUTPUT_PATH=>"/Users/me/Development/company/company-ios/archives/MyApp.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/me/Library/Developer/Xcode/Archives/2016-08-06/MyApp 2016-08-06 01.11.43.xcarchive"}
ERROR [2016-08-06 01:18:40.11]: Error uploading ipa file, for more information see above
INFO [2016-08-06 01:18:40.11]: Successfully generated documentation to path '/Users/me/Development/company/company-ios/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 23          |
| 4    | match                               | 7           |
| 5    | gym                                 | 352         |
| 6    | pilot                               | 67          |
+------+-------------------------------------+-------------+

ERROR [2016-08-06 01:18:40.12]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Error uploading ipa file, for more information see above

URL: https://api.github.com/search/issues?q=Error%20uploading%20ipa%20file,%20for%20more%20information%20see%20above+repo:fastlane/fastlane
➡️  Generated .ipa size too big
   https://github.com/fastlane/fastlane/issues/519 [open] 48 💬
   2 days ago

➡️  Always get `Transportation Failed` for App Extension Target
   https://github.com/fastlane/fastlane/issues/5467 [open] 5 💬
   3 days ago

➡️  iTunes Transporter succeeds eventually but  fastlane reports an error
   https://github.com/fastlane/fastlane/issues/1896 [open] 19 💬
   2 weeks ago

and 48 more at: https://github.com/fastlane/fastlane/search?q=Error uploading ipa file, for more information see above&type=Issues&utf8=✓
/Users/me/Software/ruby/gems/fastlane_core-0.48.3/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Error uploading ipa file, for more information see above (FastlaneCore::Interface::FastlaneError)
	from /Users/me/Software/ruby/gems/fastlane_core-0.48.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/me/Software/ruby/gems/pilot-1.10.0/lib/pilot/build_manager.rb:22:in `upload'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/runner.rb:177:in `block in execute_action'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `chdir'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `execute_action'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:139:in `block (2 levels) in parsing_binding'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Users/me/Software/ruby/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/me/Software/ruby/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/me/Software/ruby/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/me/Software/ruby/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/me/Software/ruby/gems/fastlane_core-0.48.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/me/Software/ruby/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:248:in `run'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Users/me/Software/ruby/gems/fastlane-1.99.0/bin/fastlane:5:in `<top (required)>'
	from /Users/me/Software/ruby/bin/fastlane:23:in `load'
	from /Users/me/Software/ruby/bin/fastlane:23:in `<main>'

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
pilot(app_identifier: 'com.company.MyApp', changelog: File.read("release-notes.txt"))
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.99.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by lakamsani** [comment]
Fixed this using info from: https://github.com/fastlane/fastlane/issues/5623. My Appfile had a app_identifier that pointed to my first app which was uploading fine. But when I tried my second app for the first time I got this error as I suspect it was using the IPA path corresponding to the first app when the ipa option was not specified to the pilot command in the lane. With the ipa path from gym passed into pilot, upload worked but failed with the error being discussed in https://github.com/fastlane/fastlane/issues/5125. We can close this and I will follow that one.
