### ISSUE TITLE
cert does fatal error when creating certificate due to "Permission Denied"

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5632]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running cert with a multi-team development user, 

##### Complete output when running fastlane, including the stack trace and command used

```
/usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:172:in `write': [!] Permission denied @ rb_sysopen - /Users/xxxxx/dev/platopus/Build/X3F9328AZM.cer (Errno::EACCES)
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:172:in `store_certificate'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:85:in `block in find_existing_cert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:80:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:80:in `find_existing_cert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:31:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/bin/cert:33:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.48.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/bin/cert:49:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/bin/cert:55:in `<top (required)>'
	from /usr/local/bin/cert:22:in `load'
	from /usr/local/bin/cert:22:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):
cert -v
cert 1.4.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
base mac system with ruby installed with brew

All running on a user with non-root permissions.

**Comment by lferro9000** [comment]
The permission issue was due to the fact that the user that needed to run cert was not the user that holded the permissions for the keystore. Bit of a mess, so closing this one as a non-issue.
