### ISSUE TITLE
cert is using wrong keychain to store credentials / password

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5637]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When issuing cert with -k parameter to state which keychain to use to store the credentials / passwords, cert nevertheless uses a different keychain. And fails to store them.

Of notice, the keychain was open before the cert command with:

security -v unlock-keychain -p "xxxx" "${PWD}/cert.keychain"

##### Complete output when running cert, including the stack trace and command used

```
$ cert -k cert.keychain 

+---------------+---------------+
|    Summary for cert 1.4.1     |
+---------------+---------------+
| keychain_path | cert.keychain |
| development   | false         |
| force         | false         |
+---------------+---------------+

[16:53:08]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: xxxx@xxx.xxx
[16:53:29]: Starting login with user 'xxxx@xxx.xxx'
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` env variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for xxxx@xxx.xxx): **********
security: SecKeychainAddInternetPassword <NULL>: User interaction is not allowed.
Could not store password in keychain
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) xxxxxxxxxx "xxxxxxxxxx" (Company/Organization)
2) xxxxxxxxxx "xxxxxxxxxx" (Company/Organization)
3) xxxxxxxxxx "xxxxxxxxxx" (Company/Organization)
4) xxxxxxxxxx "xxxxxxxxxx" (Company/Organization)
3
[16:53:38]: Successfully logged in

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:172:in `write': [!] Permission denied @ rb_sysopen - /Users/xxxx/keystores/X3F9328AZM.cer (Errno::EACCES)
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:172:in `store_certificate'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:85:in `block in find_existing_cert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:80:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:80:in `find_existing_cert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:31:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/bin/cert:33:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/bin/cert:49:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/bin/cert:55:in `<top (required)>'
	from /usr/local/bin/cert:22:in `load'
	from /usr/local/bin/cert:22:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

cert version (run `cert -v`):
cert 1.4.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Standard mac os ruby with brew on top to avoid read-only errors. Fully updated to latest.

**Comment by vpolouchkine** [comment]
```
/usr/local/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:172:in `write': [!] Permission denied @ rb_sysopen - /Users/xxxx/keystores/X3F9328AZM.cer (Errno::EACCES)
```

Looks like there is a permission issue wrt to the keychain ownership.

**Comment by lferro9000** [comment]
Yes, but the problem is that the stated keystore isn't the keystore configured to be accessed, which should be cert.keychain, not X3F9328AZM.cer.

Does the keychain need to be stated as absolute path (and not relative as it was)?

**Comment by vpolouchkine** [comment]
Yeah, I believe so: https://github.com/fastlane/fastlane/pull/4386
