### ISSUE TITLE
updated to pilot 1.10.0 and receiving FastlaneCore::Feature (NameError)

### ISSUE THREAD

**Issue by lam2558** [fastlane/fastlane#5641]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
updated to pilot 1.10.0 and receiving FastlaneCore::Feature (NameError)

##### Complete output when running fastlane, including the stack trace and command used

```
/usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.10.0/lib/pilot/features.rb:1:in `<top (required)>': uninitialized constant FastlaneCore::Feature (NameError)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.10.0/lib/pilot.rb:6:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.10.0/bin/pilot:4:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'
Performing Post build task...
```

**Comment by lam2558** [comment]
issue is non related to pilot. closing

**Comment by TKBurner** [comment]
@lam2558 Thanks for letting us know. Hope you have a great week 👍

**Comment by trevoriancox** [comment]
Just ran into this too. Was fixed by: 

`sudo gem update fastlane_core`
