### ISSUE TITLE
Produce: Fails on app iTC creation stage.

### ISSUE THREAD

**Issue by Wojcik** [fastlane/fastlane#5651]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Start getting this error on 4 August. Each time produce tries to create a new app it fails on iTC stage. Weird thing that even the script fails I can see the new app in the iTunes Connect. This happens for all our new apps.
The script launched for the second time gives output
```
[DevCenter] App 'com.bundle.id' already exists, nothing to do on the Dev Center
[16:47:26]: [iTC] App 'com.bundle.id' already exists (1134320172), nothing to do on iTunes Connect
```
and completes without any errors. 
### Stack trace 
```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Something went wrong when creating the new app - it's not listed in the App's list (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.1.4/lib/produce/itunes_connect.rb:33:in `create_new_app'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.1.4/lib/produce/itunes_connect.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.1.4/lib/produce/manager.rb:8:in `start_producing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/produce.rb:19:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/produce.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/produce.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:177:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:176:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:133:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:248:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'`

```
### Environment

- fastlane version (run fastlane -v): 1.99.0
- produce 1.1.4

Do you use bundler to execute fastlane (i.e. bundle exec fastlane)? NO

Do you use a Ruby environment manager (e.g. chruby, rbenv, rvm)? NO

**Comment by KrauseFx** [comment]
Thanks for reporting the issue @Wojcik, I can reproduce and will work on a fix 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/5688, which will be in the next release 🚀

**Comment by Wojcik** [comment]
Fantastic!
