### ISSUE TITLE
[Spaceship] TypeError: no implicit conversion of String into Integer in app_version.rb:641

### ISSUE THREAD

**Issue by HeEAaD** [fastlane/fastlane#5652]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
We experienced are crash with spaceship (0.30.0). 
Looks like the parsing of the trailers is broken. Was it an array before?

spaceship/tunes/app_version.rb:636 which crashes for us (see the attached stacktrace):
```
        display_families.each do |display_family|
          trailers = display_family.fetch("trailer", {}).fetch("value")
          next if trailers.nil?

          trailers.each do |trailer|
            trailer_data = trailer["value"]
            next if trailer_data.nil?
            data = {
                device_type: display_family['name'],
                language: row["language"]
            }.merge(trailer_data)
            result << Tunes::AppTrailer.factory(data)
          end
        end
```

This resolves the crash for us:
```
        display_families.each do |display_family|
          trailer_data = display_family.fetch("trailer", {}).fetch("value")
          next if trailer_data.nil?
          data = {
              device_type: display_family['name'],
              language: row["language"]
          }.merge(trailer_data)
          result << Tunes::AppTrailer.factory(data)
        end
```

##### Fastlane stacktrace

```
14:48:09 TypeError: [!] no implicit conversion of String into Integer
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:641:in `[]'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:641:in `block (2 levels) in setup_trailers_for'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:640:in `each'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:640:in `block in setup_trailers_for'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:636:in `each'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:636:in `setup_trailers_for'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:625:in `block in setup_trailers'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:623:in `each'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:623:in `setup_trailers'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:304:in `setup'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/base.rb:182:in `initialize'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:158:in `new'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:158:in `factory'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:180:in `find'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/spaceship-0.30.0/lib/spaceship/tunes/application.rb:102:in `edit_version'
14:48:09   Fastfile:330:in `block in parsing_binding'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane.rb:33:in `call'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:50:in `block in execute'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `chdir'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/runner.rb:46:in `execute'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/command_line_handler.rb:30:in `handle'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:248:in `run'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/commands_generator.rb:20:in `start'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
14:48:09   /Library/Ruby/Gems/2.0.0/gems/fastlane-1.99.0/bin/fastlane:5:in `<top (required)>'
14:48:09   /usr/local/bin/fastlane:23:in `load'
14:48:09   /usr/local/bin/fastlane:23:in `<top (required)>'
```

### Environment

fastlane 1.99.0
spaceship 0.30.0
Crash with and without `bundle exec`.

**Comment by KrauseFx** [comment]
Hey @HeEAaD, thanks for submitting this issue. It's true, with the latest changes on iTunes Connect we had to re-write how screenshots are parsed, and didn't have the time to update the trailers code yet (see https://github.com/fastlane/fastlane/pull/5646).

Since I don't have access to any trailer-enabled apps right now, do you have the chance to take a dive into fixing this? I assume the code change is very similar to what we did with screenshots on #5646.

**Comment by KrauseFx** [comment]
Oh wait, does that mean you're not trying to upload a trailer, but `deliver` just doesn't work, because you have a trailer?

**Comment by HeEAaD** [comment]
Yes, I was not uploading a trailer.

The easiest ways to reproduce this issue:
1. open spaceship
2. try to get the app version infos: `Spaceship::Tunes::Application.find(123456789).live_version`
3. exception:
```TypeError: no implicit conversion of String into Integer
from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.30.0/lib/spaceship/tunes/app_version.rb:641:in `[]'
```

**Comment by KrauseFx** [comment]
This code is working for me, as I don't have a trailer. I'll push a hotfix release ASAP 🚀

**Comment by KrauseFx** [comment]
Just prepared https://github.com/fastlane/fastlane/pull/5661 and https://github.com/fastlane/fastlane/pull/5660 🚀 

Once the tests pass, the release will be live

**Comment by KrauseFx** [comment]
Thanks for the providing the fix @HeEAaD, the new release is live https://github.com/fastlane-old/spaceship/releases/tag/0.31.1. Could you update and let us know if that works for you?

**Comment by rbobbins** [comment]
@KrauseFx 0.31.1 is working for me; was running into the same issue.

**Comment by HeEAaD** [comment]
0.31.1 fixed the issue and is working like charm. Danke Felix!

**Comment by KrauseFx** [comment]
Yeah, great to hear, thanks everyone for your help 👍
