### ISSUE TITLE
🔑 Spaceship: NoMethodError being thrown in setup_screenshots_for(row)

### ISSUE THREAD

**Issue by brockklein** [fastlane/fastlane#5676]
### New Issue Checklist

- [ 1.99.0] Updated fastlane to the latest version
- [2x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hey all - just noticed that Spaceship is raising a `NoMethodError` due to a call being placed on a `nil` object.

When you run `app.edit_version` or `app.live_version` `setup_screenshots_for(row)` is called somewhere in the stack. I'm not familiar enough with Spaceship to offer much more. I traced the calls back a bit but got lost when `setup_screenshots` (which calls `setup_screenshots_for(row)`) was called in multiple places.

If I were more versed in the projected I'd submit a pr but I suspect I'd waste more time than I'd save, so I opted for this method instead. ☺️ 

```
 def setup_screenshots_for(row)
        display_families = row.fetch("displayFamilies", {}).fetch("value", nil)
        return [] unless display_families

        result = []

        display_families.each do |display_family|
          # {
          #   "name": "iphone6Plus",
          #   "scaled": {
          #     "value": false,
          #     "isEditable": false,
          #     "isRequired": false,
          #     "errorKeys": null
          #   },
          #   "screenshots": {
          #     "value": [{
          #       "value": {
          #         "assetToken": "Purple62/v4/08/0a/04/080a0430-c2cc-2577-f491-9e0a09c58ffe/mzl.pbcpzqyg.jpg",
          #         "sortOrder": 1,
          #         "type": null,
          #         "originalFileName": "ios-414-1.jpg"
          #       },
          #       "isEditable": true,
          #       "isRequired": false,
          #       "errorKeys": null
          #     }, {
          #       "value": {
          #         "assetToken": "Purple71/v4/de/81/aa/de81aa10-64f6-332e-c974-9ee46adab675/mzl.cshkjvwl.jpg",
          #         "sortOrder": 2,
          #         "type": null,
          #         "originalFileName": "ios-414-2.jpg"
          #       },
          #       "isEditable": true,
          #       "isRequired": false,
          #       "errorKeys": null
          #     }],
          #     "isEditable": true,
          #     "isRequired": false,
          #     "errorKeys": null
          #   },
          #   "trailer": {
          #     "value": null,
          #     "isEditable": true,
          #     "isRequired": false,
          #     "errorKeys": null
          #   }
          # }

          display_family.fetch("screenshots", {}).fetch("value", []).each do |screenshot|
            screenshot_data = screenshot["value"]
            data = {
                device_type: display_family['name'],
                language: row["language"]
            }.merge(screenshot_data)
            result << Tunes::AppScreenshot.factory(data)
          end
        end

        return result
      end
```

##### Complete output when running fastlane, including the stack trace and command used

```
Successfully logged in to the Developer Portal

---------------------------------------
| Welcome to the spaceship playground |
---------------------------------------

Enter docs to open up the documentation
Enter exit to exit the spaceship playground
Enter _ to access the return value of the last executed command

Just enter the commands and confirm with Enter
[1] pry(main)> Spaceship::Application.find('com.legitapps.anderson')
=> <Spaceship::Tunes::Application 
	apple_id="1117417412", 
	name="Anderson University Events", 
	vendor_id="1464187529", 
	bundle_id="com.legitapps.anderson", 
	last_modified=1470749966000, 
	issues_count=0, 
	app_icon_preview_url="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/83/44/27/834427dc-66cc-1485-eab3-48de6628624e/pr_source.png/340x340bb-80.png">
[2] pry(main)> app = Spaceship::Application.find('com.legitapps.anderson')
=> <Spaceship::Tunes::Application 
	apple_id="1117417412", 
	name="Anderson University Events", 
	vendor_id="1464187529", 
	bundle_id="com.legitapps.anderson", 
	last_modified=1470749966000, 
	issues_count=0, 
	app_icon_preview_url="https://is3-ssl.mzstatic.com/image/thumb/Purple62/v4/83/44/27/834427dc-66cc-1485-eab3-48de6628624e/pr_source.png/340x340bb-80.png">
[3] pry(main)> app.latest_version
NoMethodError: undefined method `fetch' for nil:NilClass
from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:546:in `setup_screenshots_for'
[4] pry(main)> app.live_version
NoMethodError: undefined method `fetch' for nil:NilClass
from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:546:in `setup_screenshots_for'
[5] pry(main)> app.edit_version
=> nil
[6] pry(main)> 
```

### Environment

fastlane version (run `fastlane -v`): 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No, manage it manually.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? Yes.

**Comment by brockklein** [comment]
Updating `deliver` might be a good idea...

Problem solved...

**Comment by KrauseFx** [comment]
Yeah, glad to hear you got it resolved 👍
