### ISSUE TITLE
spaceship commander version incorrectly reported

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5685]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When running "spaceship" without any other parameter, the version of commander is stated as non-compliant with the requirements when the version installed complies with it.

##### Complete output when running fastlane, including the stack trace and command used

```
$ spaceship
WARN: Unresolved specs during Gem::Specification.reset:
      commander (>= 4.3.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Username: ^C/usr/local/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:869:in `eof?': Interrupt
	from /usr/local/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:869:in `get_line'
	from /usr/local/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:891:in `get_response'
	from /usr/local/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.31.1/bin/spaceship:37:in `<top (required)>'
	from /usr/local/bin/spaceship:22:in `load'
	from /usr/local/bin/spaceship:22:in `<main>'

$ sudo gem install commander
Successfully installed commander-4.4.0
Parsing documentation for commander-4.4.0
Done installing documentation for commander after 0 seconds
1 gem installed
$ spaceship
WARN: Unresolved specs during Gem::Specification.reset:
      commander (>= 4.3.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Username: 
```

### Configuration Files
No configuration files.

### Environment
latest versions of spaceship / commander etc

**Comment by lferro9000** [comment]
This was also sorted by:

https://github.com/fastlane/fastlane/issues/5654

So closing it down.
