### ISSUE TITLE
sigh doesn't accept 2FA password

### ISSUE THREAD

**Issue by justin** [fastlane/fastlane#5694]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When trying to run `sigh` it will constantly tell me that my password is invalid. I have tried creating a new password in the Apple ID portal, but still get failures.

##### Complete output when running fastlane, including the stack trace and command used

```
± sigh --verbose                                       

+-------------------------------------+-----------------+
|                Summary for sigh 1.9.0                 |
+-------------------------------------+-----------------+
| adhoc                               | false           |
| skip_install                        | false           |
| development                         | false           |
| force                               | false           |
| app_identifier                      | com.ted.TED     |
| team_id                             | 4Z6E862WH7      |
| team_name                           | TED Conferences |
| ignore_profiles_with_different_name | false           |
| skip_fetch_profiles                 | false           |
| skip_certificate_verification       | false           |
+-------------------------------------+-----------------+

WARN [2016-08-10 12:06:11.56]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: justinw@me.com
INFO [2016-08-10 12:06:13.96]: Starting login with user 'justinw@me.com'
The login credentials for 'justinw@me.com' seem to be wrong
Do you want to re-enter your password? (y/n)
y
Removing Keychain entry for user 'justinw@me.com'...
keychain: "/Users/justin/Library/Keychains/login.keychain"
version: 256
class: "inet"
attributes:
    0x00000007 <blob>="deliver.justinw@me.com"
    0x00000008 <blob>=<NULL>
    "acct"<blob>="justinw@me.com"
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303136303831303138303233345A00  "20160810180234Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303136303831303138303233345A00  "20160810180234Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="deliver.justinw@me.com"
    "type"<uint32>=<NULL>
password has been deleted.
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` env variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for justinw@me.com): *******************
The login credentials for 'justinw@me.com' seem to be wrong
Do you want to re-enter your password? (y/n)
n
Please run this tool again to apply the new password

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Invalid User Credentials

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Invalid%20User%20Credentials+repo:fastlane/fastlane
➡️  Code signing fails for Enterprise distribution
   https://github.com/fastlane/fastlane/issues/3193 [closed] 85 💬
   23 Mar 2016

/Users/justin/.gem/gems/spaceship-0.31.1/lib/spaceship/client.rb:91:in `login': [!] The request could not be completed because: (Spaceship::Client::InvalidUserCredentialsError)
	Invalid User Credentials
	from /Users/justin/.gem/gems/spaceship-0.31.1/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Users/justin/.gem/gems/spaceship-0.31.1/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Users/justin/.gem/gems/sigh-1.9.0/lib/sigh/runner.rb:15:in `run'
	from /Users/justin/.gem/gems/sigh-1.9.0/lib/sigh/manager.rb:7:in `start'
	from /Users/justin/.gem/gems/sigh-1.9.0/lib/sigh/commands_generator.rb:35:in `block (2 levels) in run'
	from /Users/justin/.gem/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/justin/.gem/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/justin/.gem/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/justin/.gem/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/justin/.gem/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/justin/.gem/gems/sigh-1.9.0/lib/sigh/commands_generator.rb:97:in `run'
	from /Users/justin/.gem/gems/sigh-1.9.0/lib/sigh/commands_generator.rb:11:in `start'
	from /Users/justin/.gem/gems/sigh-1.9.0/bin/sigh:6:in `<top (required)>'
	from /Users/justin/.gem/bin/sigh:23:in `load'
	from /Users/justin/.gem/bin/sigh:23:in `<main>'

```

### Configuration Files

N/A

### Environment

sigh version (run `sigh -v`): 1.9.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No. Just Homebrew.

**Comment by KrauseFx** [comment]
Hey @justin, sorry for the troubles. In `sigh`, you don't need an application specific password, but you provide your real password instead. `sigh` will automatically detect that your user has 2-factor enabled and send a notification to your phone, which you can then enter into fastlane 👍 

Let me know if that works for you.

**Comment by justin** [comment]
Derp. Yeah. Thanks.

**Comment by KrauseFx** [comment]
Awesome 👍
