### ISSUE TITLE
Spaceship parsing fails with "undefined method `fetch' for nil:NilClass"

### ISSUE THREAD

**Issue by olegoid** [fastlane/fastlane#5701]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

If bundle has no screenshots and/or trailers attached spaceship parsing fails
with "undefined method `fetch' for nil:NilClass".

##### Complete output when running fastlane, including the stack trace and command used

```
/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:575:in `setup_trailers_for': [!] undefined method `fetch' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:569:in `block in setup_trailers'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:567:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:567:in `setup_trailers'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:304:in `setup'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/base.rb:182:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:158:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:158:in `factory'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/app_version.rb:180:in `find'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/application.rb:102:in `edit_version'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.29.1/lib/spaceship/tunes/application.rb:108:in `latest_version'
	from /usr/local/lib/ruby/gems/2.3.0/gems/submission_runner-0.4.4/lib/submission_runner/projects/project.rb:144:in `request_last_build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/submission_runner-0.4.4/lib/submission_runner/projects/project.rb:79:in `update_versions'
	from /usr/local/lib/ruby/gems/2.3.0/gems/submission_runner-0.4.4/lib/submission_runner/submission_manager.rb:62:in `run_submission'
	from /usr/local/lib/ruby/gems/2.3.0/gems/submission_runner-0.4.4/lib/submission_runner/commands_generator.rb:28:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/submission_runner-0.4.4/lib/submission_runner/commands_generator.rb:34:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/submission_runner-0.4.4/bin/submission_runner:6:in `<top (required)>'
	from /usr/local/bin/submission_runner:23:in `load'
	from /usr/local/bin/submission_runner:23:in `<main>'
```

### Configuration Files

NAN. Calling spaceship code from another ruby file.

### Environment

fastlane version (run `fastlane -v`): 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? *NO*

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? *NO*

**Comment by olegoid** [comment]
Possible fix: https://github.com/fastlane/fastlane/pull/5702

**Comment by TKBurner** [comment]
@olegoid Thanks! We'll work with you on the PR. Hope you have a wonderful weekend! 👍
