### ISSUE TITLE
Xcode8 issue when packaging an application

### ISSUE THREAD

**Issue by garnett** [fastlane/fastlane#5756]
### New Issue Checklist

- [*] Updated fastlane to the latest version
- [*] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
/Users/denis/.rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:1392:in `initialize': [!] No such file or directory @ rb_sysopen - /Applications/Xcode-beta5.app/Contents/Developer//Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreBluetooth.dylib (Errno::ENOENT)
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gym-1.7.0/lib/gym/xcodebuild_fixes/swift_fix.rb:30:in `block (2 levels) in swift_library_fix'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gym-1.7.0/lib/gym/xcodebuild_fixes/swift_fix.rb:27:in `each'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gym-1.7.0/lib/gym/xcodebuild_fixes/swift_fix.rb:27:in `block in swift_library_fix'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gym-1.7.0/lib/gym/xcodebuild_fixes/swift_fix.rb:20:in `swift_library_fix'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gym-1.7.0/lib/gym/runner.rb:83:in `fix_package'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gym-1.7.0/lib/gym/runner.rb:21:in `run'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gym-1.7.0/lib/gym/manager.rb:10:in `work'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:177:in `block in execute_action'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:176:in `chdir'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:176:in `execute_action'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:29:in `block (2 levels) in parsing_binding'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/commands_generator.rb:248:in `run'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Users/denis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.100.0/bin/fastlane:5:in `<top (required)>'
	from /Users/denis/.rbenv/versions/2.3.0/bin/fastlane:22:in `load'
	from /Users/denis/.rbenv/versions/2.3.0/bin/fastlane:22:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
default_platform :ios

$:.unshift File.dirname(__FILE__)
require 'lib/utils.rb'

platform :ios do
    before_all do
        ensure_git_status_clean
    end

    after_all do
        reset_git_repo(disregard_gitignore: false)
    end

    lane :beta do |options|

        unless options[:skip_tests]
            scan(
                workspace: "swiftGift2.xcworkspace",
                scheme: "SwiftGift",
                device: "iPhone 6s"
            )
        end

        sh "cd .. && script/colorize_icon.sh"

        increment_build_number

        gym(
            scheme: "SwiftGift",
            configuration: "Beta",
            output_directory: "./build",
            use_legacy_build_api: true,
            clean: true
        )
        deploy_beta
    end

    lane :deploy_beta do
        crashlytics(
            ipa_path: "./build/SwiftGift.ipa",
            crashlytics_path: "./Pods/Crashlytics",
            api_token: ENV['CRASHLYTICS_API_KEY'],
            build_secret: ENV['CRASHLYTICS_BUILD_KEY'],
            notes_path: "CHANGELOG_SHORT.md",
            notifications: false,
            groups: "All"
        )
    end

    lane :testflight do
        ensure_git_branch
        increment_build_number

        gym(
            scheme: "SwiftGift",
            configuration: "Store",
            output_directory: "./build",
            use_legacy_build_api: true,
            clean: true
        )

        pilot(
            skip_submission: true,
            skip_waiting_for_build_processing: true,
            ipa: "./build/SwiftGift.ipa",
            distribute_external: false
        )

        commit_version_bump(xcodeproj: "swiftGift2.xcodeproj")
    end

    lane :upload_screenshots do
        deliver(
            submit_for_review: false,
            skip_binary_upload: true,
            skip_metadata: true
        )
    end
end
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.100.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by garnett** [comment]
I'm using Xcode8 beta5. Interesting thing I've discovered:

```
ls /Applications/Xcode-beta.app/Contents/Developer//Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/ | grep Bluetooth
```

outputs:
```
libswiftCoreBluetooth.dylib
```

However, ```ls /Applications/Xcode-beta5.app/Contents/Developer//Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/ | grep Bluetooth``` does not find bluetooth dylib.

No idea why it is missing, but it looks like fastlane should search inside current toolchain and copy only existing files.

**Comment by KrauseFx** [comment]
Could you try using `gym` without the legacy build API?

**Comment by garnett** [comment]
@KrauseFx it solved the issue! Now I have another related to Message extensions, but I'll create dedicated ticket for that.

**Comment by KrauseFx** [comment]
Perfect, thanks @garnett 👍
