### ISSUE TITLE
Error: No such file or directory @ dir_chdir -

### ISSUE THREAD

**Issue by mariocads** [fastlane/fastlane#5789]
Hi, 
when I try to upload a build to the appstore i get an error while action deliver.
Error:

```
/usr/lib/ruby/2.3.0/fileutils.rb:128:in `chdir': [!] No such file or directory @ dir_chdir -  (Errno::ENOENT)
        from /usr/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
        from /var/lib/gems/2.3.0/gems/fastlane_core-0.50.2/lib/fastlane_core/itunes_transporter.rb:253:in `execute'
        from /var/lib/gems/2.3.0/gems/fastlane_core-0.50.2/lib/fastlane_core/itunes_transporter.rb:357:in `upload'
        from /var/lib/gems/2.3.0/gems/deliver-1.13.2/lib/deliver/runner.rb:82:in `upload_binary'
        from /var/lib/gems/2.3.0/gems/deliver-1.13.2/lib/deliver/runner.rb:25:in `run'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/actions/deliver.rb:18:in `run'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:177:in `block in execute_action'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:176:in `chdir'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:176:in `execute_action'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/fast_file.rb:140:in `method_missing'
        from Fastfile:29:in `block (2 levels) in parsing_binding'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/lane.rb:33:in `call'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:50:in `block in execute'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:46:in `chdir'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:46:in `execute'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /var/lib/gems/2.3.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/commands_generator.rb:248:in `run'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/commands_generator.rb:20:in `start'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
        from /var/lib/gems/2.3.0/gems/fastlane-1.100.0/bin/fastlane:5:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'
```

As my setup is using Ubuntu, not a Mac... I am guessing that the upload may be only initiated by a Mac... or by XCode, but I am not sure...

Many thanks
Mario

**Comment by renanrmelo** [comment]
+1

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by asfalcone** [comment]
@mariocads You need to have the [itms transporter](https://github.com/fastlane/fastlane/blob/6ceab313410c2ae68bd9f6ee7cf91a73e4f59400/fastlane_core/lib/fastlane_core/helper.rb#L124) on the machine in order to use `deliver`. It is not expected for this to work on Ubuntu.

**Comment by onedal88** [comment]
@mariocads After spending lot of hours i get link to "Linux" installer to iTunes Transporter. 
Here: 
`https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/Transporter__Linux/bin`

Save script as 'install_script' and run:
```bash
./install_script.sh --target /your/path/to/itms
```

Self-extract script forking for me, tested on Ubuntu 16.04. In next step you need set FASTLANE_ITUNES_TRANSPORTER_PATH=/your/path/to/items

Now, i trying perform upload, but all test ends with this: 
```
[2016-09-29 15:51:34 UTC] <main> DEBUG: com.apple.jingle.leghorn.fileformat.exceptions.DescriptionException: java.lang.UnsupportedOperationException: Uploads of Mac and iOS apps are only supported on OS X.
	at com.apple.jingle.leghorn.software.AbstractSoftwareDescriber.describe(AbstractSoftwareDescriber.java:61)
	at com.apple.jingle.leghorn.software.AbstractSoftwareDescriber.describe(AbstractSoftwareDescriber.java:43)
	at com.apple.jingle.leghorn.software.AbstractSoftwareDescriber.describe(AbstractSoftwareDescriber.java:32)
	at com.apple.jingle.leghorn.fileformat.Verifier.describe(Verifier.java:241)
	at com.apple.jingle.leghorn.fileformat.Verifier.describe(Verifier.java:224)
	at com.apple.transporter.util.LeghornUtil.describeAsset(LeghornUtil.java:79)
	at com.apple.transporter.operation.Verify.describeAssets(Verify.java:462)
	at com.apple.transporter.operation.Upload.performUploadRequest(Upload.java:176)
	at com.apple.transporter.operation.Upload.performUploadRequest(Upload.java:101)
	at com.apple.transporter.operation.Upload.performRequest(Upload.java:1039)
	at com.apple.transporter.operation.Verify.execute(Verify.java:94)
	at com.apple.transporter.Application.begin(Application.java:135)
	at com.apple.transporter.osgi.TransporterService.run(TransporterService.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.apple.transporter.osgi.OSGiBootstrapper.runTransporter(OSGiBootstrapper.java:578)
	at com.apple.transporter.osgi.OSGiBootstrapper.bootstrap(OSGiBootstrapper.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.apple.transporter.Application.start(Application.java:133)
	at com.apple.transporter.Application.main(Application.java:357)
Caused by: java.lang.UnsupportedOperationException: Uploads of Mac and iOS apps are only supported on OS X.
	at com.apple.transporter.softwaresupport.SoftwareSupportServiceImpl$1.invoke(SoftwareSupportServiceImpl.java:173)
	at com.apple.jingle.leghorn.software.AbstractSoftwareDescriber.describe(AbstractSoftwareDescriber.java:59)
	... 24 more
```

**Comment by TKBurner** [comment]
@mariocads This is a limitation imposed by Apple. What input did you give for that error? Thanks!

**Comment by pernilla** [comment]
I'm a little bit confused. Should it be possible to upload ipa on a linux machine? I too get the error with "No such file or directory @ dir_chdir"? The following link https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/Transporter__Linux/bin only rerouted me to itunes connect page.

**Comment by KrauseFx** [comment]
Sorry, Linux is currently not officially supported by _fastlane_

**Comment by pernilla** [comment]
Thanks.
