### ISSUE TITLE
Fastlane android deploy issue

### ISSUE THREAD

**Issue by mattfred** [fastlane/fastlane#5800]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am using fastlane for android builds. I have a lane with does a check build and a lane that deploys to hockey app. Both of these work fine. However, when I try to do a lane that deploys the app, it seems like fastlane is not setup correctly.

##### Complete output when running fastlane, including the stack trace and command used

```
Starting: ....
[19:49:34][Step 2/2] in directory: ....
[19:49:35][Step 2/2] [15:49:35]: Could not find fastlane in current directory. Would you like to set it up?
[19:49:35][Step 2/2] 
[19:49:35][Step 2/2] Looking for related GitHub issues on fastlane/fastlane...
[19:49:35][Step 2/2] 
[19:49:35][Step 2/2] ➡️  How to call deliver download_metadata from fastlane
[19:49:35][Step 2/2]    https://github.com/fastlane/fastlane/issues/5397 [closed] 8   
[19:49:35][Step 2/2]    3 weeks ago
[19:49:35][Step 2/2] 
[19:49:35][Step 2/2] ➡️  Jenkins cannot find FastLane
[19:49:35][Step 2/2]    https://github.com/fastlane/fastlane/issues/4864 [closed] 0   
[19:49:35][Step 2/2]    26 May 2016
[19:49:35][Step 2/2] 
[19:49:35][Step 2/2] ➡️  Deliver - Non-Interactive Mode not working for initial setup
[19:49:35][Step 2/2]    https://github.com/fastlane/fastlane/issues/4820 [closed] 1   
[19:49:35][Step 2/2]    27 May 2016
[19:49:35][Step 2/2] 
[19:49:35][Step 2/2] and 1 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓
[19:49:35][Step 2/2] /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
[19:49:35][Step 2/2] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/implementations/shell.rb:119:in `verify_interactive!'
[19:49:35][Step 2/2] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/implementations/shell.rb:97:in `confirm'
[19:49:35][Step 2/2] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
[19:49:35][Step 2/2] 	from /Users/autoloop/.gem/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:256:in `ensure_fastfile'
[19:49:35][Step 2/2] 	from /Users/autoloop/.gem/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:48:in `block (2 levels) in run'
[19:49:35][Step 2/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
[19:49:35][Step 2/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
[19:49:35][Step 2/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
[19:49:35][Step 2/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
[19:49:35][Step 2/2] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
[19:49:35][Step 2/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
[19:49:35][Step 2/2] 	from /Users/autoloop/.gem/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
[19:49:35][Step 2/2] 	from /Users/autoloop/.gem/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
[19:49:35][Step 2/2] 	from /Users/autoloop/.gem/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
[19:49:35][Step 2/2] 	from /Users/autoloop/.gem/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
[19:49:35][Step 2/2] 	from /Users/autoloop/.gem/bin/fastlane:23:in `load'
[19:49:35][Step 2/2] 	from /Users/autoloop/.gem/bin/fastlane:23:in `<main>'
[19:49:35][Step 2/2] Process exited with code 1
[19:49:36][Step 2/2] Step Build (Command Line) failed
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
desc "Deploy a new version to the Google Play"
  lane :store do |options|
  gradle(task: "clean",
           properties: {
           'versCode' => options[:build_number]
           })
    gradle(task: "assembleRelease",
          properties: {
          'versCode' => options[:build_number]
          })
    supply
  end
```

### Environment

fastlane version (run `fastlane -v`):
fastlane_version "1.100.0"

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by asfalcone** [comment]
@mattfred Can you share the command you're running and the directory you're running it in?

**Comment by mattfred** [comment]
This was an issue with git. I have it fixed now. Thanks
