### ISSUE TITLE
undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by Reedyuk** [fastlane/fastlane#5817]
##### Complete output when running fastlane, including the stack trace and command used

```
+------------------------------------------------------------------------------+
| (0) deploy-to-itunesconnect-deliver@2.6.1                                    |
+------------------------------------------------------------------------------+
| id: deploy-to-itunesconnect-deliver                                          |
| version: 2.6.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-08-19T10:29:51-07:00                                              |
+------------------------------------------------------------------------------+
|

Config:
 * ipa_path: /Users/vagrant/deploy/AppName.ipa
 * pkg_path: 
 * itunescon_user: someemail
 * password: ***
 * app_id: APPID
 * submit_for_beta: no
 * skip_metadata: yes
 * skip_screenshots: yes
 * team_id: 
 * team_name: 
 * update_deliver: yes

# Setup

 (i) deliver already installed
 (i) updating  deliver...

 (i) Which ruby: /usr/local/bin/ruby
 (i) Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

 -> using brew (/usr/local/bin/ruby) ruby
$ gem install deliver --no-document
Successfully installed spaceship-0.31.3
Successfully installed fastlane_core-0.50.2
Successfully installed deliver-1.13.2
3 gems installed

 (i) Setup took 3 seconds to complete


# Deploy


**Note:** if your password
contains special characters
and you experience problems, please
consider changing your password
to something with only
alphanumeric characters.


**Be advised** that this
step uses a well maintained, open source tool which
uses *undocumented and unsupported APIs* (because the current
iTunes Connect platform does not have a documented and supported API)
to perform the deployment.
This means that when the API changes
**this step might fail until the tool is updated**.

[10:30:02]: Login to iTunes Connect (emailaddress)
[10:30:04]: Login successful

+--------------------+----------------------------------+
|                deliver 1.13.2 Summary                 |
+--------------------+----------------------------------+
| ipa                | /Users/vagrant/deploy/appname.ipa |
| skip_screenshots   | true                             |
| skip_metadata      | true                             |
| force              | true                             |
| app_identifier     | com.AppName.app.AppName            |
| screenshots_path   | ./screenshots                    |
| metadata_path      | ./metadata                       |
| app_version        | 1.0.0                            |
| username           | email                 |
| skip_binary_upload | false                            |
| submit_for_review  | false                            |
| automatic_release  | false                            |
+--------------------+----------------------------------+

[10:30:05]: Making sure the latest version on iTunes Connect matches '1.0.0' from the ipa file...
[10:30:06]: '1.0.0' is the latest version on iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...

[10:30:07]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass

[!] The request could not be completed because:
	Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. There is an error for 1 of your localizations.
 [!] Error description: Deploy failed!
     (i) Exit code was: 1
 (i) Calling cleanup function before exit
-> finalcleanup

# Error


**Error Description**:


Deploy failed!


*See the logs for more information*


**If this is the very first build**
of the app you try to deploy to iTunes Connect then you might want to upload the first
build manually to make sure it fulfills the initial iTunes Connect submission
verification process.
```

### Environment

Using Bitrise - Xcode 7.3.1, on OS X 10.11.4

I asked their support and they have said its an issue with fast lane.
I submitted the app manually via Xcode on my local machine and it worked fine, so i know that there is nothing wrong with the app/code.

**Comment by asfalcone** [comment]
@Reedyuk Thanks for reporting. Can you find the logs from this build that would include the `fastlane` stack trace so we can get to the bottom of this issue? Thanks 👍

**Comment by Reedyuk** [comment]
hmm, that would appear is all i get from the output in Bitrise.

**Comment by Reedyuk** [comment]
```
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/app_version.rb:546:in `setup_screenshots_for': [!] undefined method `fetch' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/app_version.rb:540:in `block in setup_screenshots'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/app_version.rb:538:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/app_version.rb:538:in `setup_screenshots'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/app_version.rb:303:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/base.rb:182:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/app_version.rb:158:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/app_version.rb:158:in `factory'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/app_version.rb:180:in `find'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/application.rb:102:in `edit_version'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.26.2/lib/spaceship/tunes/application.rb:168:in `ensure_version!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.11.2/lib/deliver/runner.rb:39:in `verify_version'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.11.2/lib/deliver/runner.rb:20:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.11.2/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.11.2/lib/deliver/commands_generator.rb:132:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.11.2/lib/deliver/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.11.2/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
 [!] Error description: Deploy failed!
     (i) Exit code was: 1
 (i) Calling cleanup function before exit
-> finalcleanup
```

**Comment by Reedyuk** [comment]
When i dont update my bitrise config to 1.13.2, then i get a stacktrace.

**Comment by jlubeck** [comment]
I'm running into this error as well but when running deliver.

[!] The request could not be completed because:
	Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. There are one or more errors on the page.

**Comment by Reedyuk** [comment]
Yes, it seems like Apple have changed something since allowing the 5.5." screen images to automatically down scale for the smaller devices.

**Comment by asfalcone** [comment]
@Reedyuk Did you say that the error is fixed in `deliver 1.13.2` ?

**Comment by Reedyuk** [comment]
No sorry, the error is still there.

**Comment by asfalcone** [comment]
I believe this is a duplicate of https://github.com/fastlane/fastlane/issues/5643 which we fixed in `spaceship 0.30.0` and `deliver 1.13.2`. Can you update to the latest tools and let me know if it is fixed? If not, please add an updated stacktrace so we can debug further. Thanks 👍

**Comment by Reedyuk** [comment]
I'm using 1.13.2, i'm using Bitrise, that is the full log that i am getting.

**Comment by asfalcone** [comment]
The stack trace you posted indicates that `1.11.2` is being used:
```
    from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.11.2/lib/deliver/runner.rb:39:in `verify_version'
    from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.11.2/lib/deliver/runner.rb:20:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.11.2/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
```

**Comment by Reedyuk** [comment]
The original post:
```
+--------------------+----------------------------------+
|                deliver 1.13.2 Summary                 |
+--------------------+----------------------------------+
```

**Comment by jlubeck** [comment]
As a personal note, the error "Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly" I'm also getting on Itunes connect directly. So I'm not sure this is a fastlane issue.

**Comment by asfalcone** [comment]
Ah, I see. The stacktrace you posted does not match the original issue you mentioned @Reedyuk 

The error is `Screenshots and app previews for the largest display sizes of your app’s primary localization must be uploaded directly. There is an error for 1 of your localizations.` which, as @jlubeck mentioned is coming from Apple.

**Comment by Reedyuk** [comment]
Very odd, i can upload via Xcode fine, but using Deliver, its failing. I do believe it is something Apple's end, but i need more evidence. I have contacted them about it.

**Comment by ShadeApps** [comment]
I have the same issue both on iTunes Connect and Deliver and I'm 100% confident it's a bug on Apple's side, been having this issue for the past 2 days and our app is stuck on screenshot upload process permanently.

**Comment by jlubeck** [comment]
Hey Sergey, (and eveyone else having this issue on iTunes Connect). Call
apple at Developer Customer support and let them know. When I called
yesterday, they told me they were not aware of the situation, so the more
people having it, the faster the'll hopefully fix it.

*_____**_*
Jan Lübeck
Chief Technology Officer
fyrastudio.com

**Comment by TKBurner** [comment]
@ShadeApps Can you let me know the error you get from iTC? Just want to make sure it matches up. Thanks all!

**Comment by Reedyuk** [comment]
![itc-fail](https://cloud.githubusercontent.com/assets/3853006/17922469/0ee06424-69d7-11e6-9426-4d6e90659deb.png)

**Comment by Reedyuk** [comment]
it makes me think that this is a bug their end because the error text is repeated, which is something you would generally do for placeholder text.

**Comment by ShadeApps** [comment]
@TKBurner apparently for now the bug is gone and I am able to submit new apps as well as update old ones.

**Comment by Reedyuk** [comment]
magically started working for me too. Apple issue

**Comment by TKBurner** [comment]
@ShadeApps @Reedyuk Thanks so much for updating this. Really glad to hear you are up and running. Hope you have a wonderful day! 👍
