### ISSUE TITLE
PEM [!] 784: unexpected token at 'Bad Request'

### ISSUE THREAD

**Issue by gregk8288** [fastlane/fastlane#5849]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
For the last two days whenever I run PEM as part of Fastlane, I get the following error. 
`[07:04:30]: 784: unexpected token at 'Bad Request'`
I am able to see on the developer centre that the production push certificates have not been created yet either. 

##### Complete output when running fastlane, including the stack trace and command used

```
[07:04:18]: Starting login with user 'greg@hellocrowd.net'
[07:04:21]: Successfully logged in
[07:04:23]: Creating a new push certificate for app 'net.hellocrowd.yzrwv9q9t'.
[07:04:28]: -------------------
[07:04:28]: --- Step: slack ---
[07:04:28]: -------------------
[07:04:30]: Successfully sent Slack notification
[07:04:30]: Variable Dump:
[07:04:30]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios sns_firebase", :PRODUCE_APPLE_ID=>"1146502408", :CERT_FILE_PATH=>"/Users/gregkockott/www/App_Deployments/YZRWV9Q9T/iOS/6PL5VW7DJ8.cer", :CERT_CERTIFICATE_ID=>"6PL5VW7DJ8", :SIGH_PROFILE_PATH=>"/Users/gregkockott/www/App_Deployments/YZRWV9Q9T/iOS/AppStore_net.hellocrowd.yzrwv9q9t.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/gregkockott/www/App_Deployments/YZRWV9Q9T/iOS/AppStore_net.hellocrowd.yzrwv9q9t.mobileprovision"], :SIGH_UDID=>"571ffc9b-7501-4051-b817-5b30daf308b9", :SIGH_PROFILE_TYPE=>"app-store"}
[07:04:30]: 784: unexpected token at 'Bad Request'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | bundle_install   | 0           |
| 2    | update_fastlane  | 8           |
| 3    | default_platform | 0           |
| 4    | cocoapods        | 9           |
| 5    | produce          | 14          |
| 6    | cert             | 6           |
| 7    | sigh             | 13          |
| 8    | pem              | 10          |
| 9    | slack            | 2           |
+------+------------------+-------------+

[07:04:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  "unexpected token at 'Bad Request'" from Spaceship when attempting to repair a provisioning profile
   https://github.com/fastlane/fastlane/issues/5813 [closed] 34 💬
   10 hours ago

➡️  Spaceship– 'Bad Request' and crash on `match development`
   https://github.com/fastlane/fastlane/issues/5798 [closed] 21 💬
   10 hours ago

➡️  Produce fails to create a new app id
   https://github.com/fastlane/fastlane/issues/5797 [closed] 27 💬
   9 hours ago

and 2 more at: https://github.com/fastlane/fastlane/search?q=784:%20unexpected%20token%20at%20'Bad%20Request'&type=Issues&utf8=✓
bundler: failed to load command: fastlane (/Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/fastlane)
Faraday::ParsingError: [!] 784: unexpected token at 'Bad Request'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/json_pure-1.8.3/lib/json/common.rb:155:in `parse'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/json_pure-1.8.3/lib/json/common.rb:155:in `parse'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/spaceship-0.31.7/lib/spaceship/client.rb:411:in `block in send_request'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/spaceship-0.31.7/lib/spaceship/client.rb:328:in `with_retry'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/spaceship-0.31.7/lib/spaceship/client.rb:410:in `send_request'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/spaceship-0.31.7/lib/spaceship/client.rb:385:in `request'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/spaceship-0.31.7/lib/spaceship/portal/portal_client.rb:299:in `create_certificate!'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/spaceship-0.31.7/lib/spaceship/portal/certificate.rb:298:in `create!'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/pem-1.3.2/lib/pem/manager.rb:47:in `create_certificate'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/pem-1.3.2/lib/pem/manager.rb:30:in `start'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/actions/pem.rb:19:in `run'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:175:in `block in execute_action'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `chdir'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `execute_action'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:140:in `method_missing'
  Fastfile:37:in `block (2 levels) in parsing_binding'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `chdir'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `execute'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
  /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<top (required)>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
bundle_install
update_fastlane

default_platform :ios

platform :ios do
    before_all do
        ENV["SLACK_URL"] = "https://hooks.slack.com/services/******"
        cocoapods
        produce(
            username: "greg@******.net",
            app_name: "RAF-S CONNECT",
            app_identifier: "net.hellocrowd.******"
            )
        apple_id = ENV["PRODUCE_APPLE_ID"]
        cert
        sigh
    end
  
    desc "This will also make sure the profile is up to date"
    lane :sns_firebase do
        pem(
            save_private_key: true,
            pem_name: "push",
            new_profile: proc do |profile_path| 
                puts profile_path
                pem_sns(package_id: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier).split('.').last.upcase)
            end
            )
        url_firebase
    end
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?  rvm

**Comment by gregk8288** [comment]
@fastlane-bot - I don't think this is a code signing issue. Cert and Sign both run without issue:
```[07:03:57]: ------------------
[07:03:57]: --- Step: cert ---
[07:03:57]: ------------------

+---------------+-----------------------------------------------------+
|                       Summary for cert 1.4.1                        |
+---------------+-----------------------------------------------------+
| development   | false                                               |
| force         | false                                               |
| username      | greg@hellocrowd.net                                 |
| team_id       | HL7N5T6N6H                                          |
| keychain_path | /Users/gregkockott/Library/Keychains/login.keychain |
+---------------+-----------------------------------------------------+

[07:03:57]: Starting login with user 'greg@hellocrowd.net'
[07:04:00]: Successfully logged in
[07:04:04]: Found the certificate 6PL5VW7DJ8 (HELLOCROWD (PTY) LTD) which is installed on the local machine. Using this one.
[07:04:04]: Verifying the certificated is properly installed locally...
[07:04:04]: Successfully installed certificate 6PL5VW7DJ8
[07:04:04]: Use signing certificate '6PL5VW7DJ8' from now on!
[07:04:04]: ------------------
[07:04:04]: --- Step: sigh ---
[07:04:04]: ------------------

+-------------------------------------+--------------------------+
|                     Summary for sigh 1.9.0                     |
+-------------------------------------+--------------------------+
| adhoc                               | false                    |
| skip_install                        | false                    |
| development                         | false                    |
| force                               | false                    |
| app_identifier                      | net.hellocrowd.yzrwv9q9t |
| username                            | greg@hellocrowd.net      |
| team_id                             | HL7N5T6N6H               |
| ignore_profiles_with_different_name | false                    |
| cert_id                             | 6PL5VW7DJ8               |
| skip_fetch_profiles                 | false                    |
| skip_certificate_verification       | false                    |
+-------------------------------------+--------------------------+

[07:04:04]: Starting login with user 'greg@hellocrowd.net'
[07:04:08]: Successfully logged in
[07:04:08]: Fetching profiles...
[07:04:16]: Found 1 matching profile(s)
[07:04:16]: Downloading provisioning profile...
[07:04:18]: Successfully downloaded provisioning profile...
[07:04:18]: Installing provisioning profile...
/Users/gregkockott/www/App_Deployments/YZRWV9Q9T/iOS/AppStore_net.hellocrowd.yzrwv9q9t.mobileprovision
[07:04:18]: Setting Provisioning Profile type to 'app-store'```

**Comment by TKBurner** [comment]
@gregk8288 Thanks for reaching out. You can follow along on #5827 As this is related. Thanks!

**Comment by KrauseFx** [comment]
@gregk8288 Have you tried the latest spaceship release 👍
