### ISSUE TITLE
Use spaceship to delete a app, has error!!!

### ISSUE THREAD

**Issue by zhouzerong** [fastlane/fastlane#5850]
i use ruby code directly @KrauseFx   the spaceship version is 0.31.7

**# Add a app like this:**
Spaceship.app.create!(bundle_id: "com.yukharekid.ki760", name: "iopName0")
and it's success !!!

**# Now i want to delete it like this:**
app = Spaceship.app.find("com.yukharekid.ki760")
app.delete!
```
**# there is something wrong,log below:**
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse': 757: unexpected token at 'Bad Request' (Faraday::ParsingError)
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.7/lib/spaceship/client.rb:411:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.7/lib/spaceship/client.rb:328:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.7/lib/spaceship/client.rb:410:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.7/lib/spaceship/client.rb:385:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.7/lib/spaceship/portal/portal_client.rb:191:in `delete_app!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.7/lib/spaceship/portal/app.rb:115:in `delete!'
	from /Users/shenyuan/vshare/zhMe_fastlane/produceSdd.rb:51:in `<main>'
```

**Comment by TKBurner** [comment]
You can follow over on #5827. Closing as duplicate.
