### ISSUE TITLE
Gym fails when building a Swift 2.3 Xcode 8 project with `libswiftCoreBluetooth.dylib` missing

### ISSUE THREAD

**Issue by bonzoq** [fastlane/fastlane#5863]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`Gym` fails when building an XCode8 Swift 2.3 project with the following error:

`[!] No such file or directory - /Applications/Xcode-beta-6.app/Contents/Developer//Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreBluetooth.dylib`

This happens with `use_legacy_build_api` both set and not set.
##### Complete output when running fastlane, including the stack trace and command used

```

$ fastlane beta

[20:32:24]: -----------------
[20:32:24]: --- Step: gym ---
[20:32:24]: -----------------
[20:32:24]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816
[20:32:24]: Installing provisioning profile...
[20:32:24]: xcodebuild -list -project ./app.xcodeproj

+---------------------------+-----------------------------------------------------------+
|                                 Summary for gym 1.7.0                                 |
+---------------------------+-----------------------------------------------------------+
| scheme                    | ourapp                                                   |
| use_legacy_build_api      | true                                                      |
| project                   | ./app.xcodeproj                                          |
| provisioning_profile_path | /Users/marcin/Desktop/client/app/ourapp.mobileprovision |
| destination               | generic/platform=iOS                                      |
| output_name               | app                                                      |
| clean                     | false                                                     |
| output_directory          | .                                                         |
| silent                    | false                                                     |
| buildlog_path             | ~/Library/Logs/gym                                        |
+---------------------------+-----------------------------------------------------------+

[20:32:29]: $ set -o pipefail && xcodebuild -scheme ourapp -project ./app.xcodeproj -destination 'generic/platform=iOS' -archivePath '/Users/marcin/Library/Developer/Xcode/Archives/2016-08-23/app 2016-08-23 20.32.29.xcarchive' archive | tee /Users/marcin/Library/Logs/gym/app-ourapp.log | xcpretty
[20:32:30]: ▸ Building app/ourapp [Release]


[20:38:00]: No such file or directory - /Applications/Xcode-beta-6.app/Contents/Developer//Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreBluetooth.dylib

[20:38:00]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `initialize': [!] No such file or directory - /Applications/Xcode-beta-6.app/Contents/Developer//Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreBluetooth.dylib (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `copy_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:477:in `copy_file'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/xcodebuild_fixes/swift_fix.rb:30:in `block (2 levels) in swift_library_fix'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/xcodebuild_fixes/swift_fix.rb:27:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/xcodebuild_fixes/swift_fix.rb:27:in `block in swift_library_fix'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/xcodebuild_fixes/swift_fix.rb:20:in `swift_library_fix'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/runner.rb:83:in `fix_package'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:175:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:81:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.93.1"

default_platform :ios

platform :ios do
  
  lane :commitBump do
    commit_version_bump(
        message: 'Bump build numer [fastlane]',
        force: true,
        xcodeproj: "app.xcodeproj"
    )

  end

  lane :pushToGit do
      push_to_git_remote
  end

  lane :beta do
      
      changelog = prompt(text: "What's new: ", multi_line_end_keyword: "END")
      
      build = increment_build_number
      
    gym(scheme: "ourapp", use_legacy_build_api: true) 
    
    commit_version_bump(
                        message: 'Build Version Bump by fastlane',
                        force: true,
                        xcodeproj: "app.xcodeproj"
                        )
                        
    pilot(
        team_id: "changed on purpose when submitting this issue",
        team_name: "our team”,
		skip_waiting_for_build_processing: true,
        changelog: changelog
    )
    
          
    push_to_git_remote

  end

  
end

```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.101.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
NO
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
NO

**Comment by TKBurner** [comment]
@bonzoq Thanks for reporting this. I've reached out to the core team to let them know. We don't officially support Xcode 8 yet, but they'll want to take a look because it's in the pipeline.

Thanks!

**Comment by bonzoq** [comment]
@TKBurner Thanks for handling my report. I realized how helpful `fastlane` is for releasing Testflight builds, now that we temporarily can't use it with Xcode 8. Keep up the good work guys.

**Comment by nafu** [comment]
Adding toolchain option will solve this problem.
e.g. https://github.com/fastlane/fastlane/pull/5864

**Comment by TKBurner** [comment]
@nafu Awesome! Thanks for the PR!

**Comment by bonzoq** [comment]
@nafu thanks for solving this!

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/6018, to show a better error message when this happens 👍

**Comment by bonzoq** [comment]
Love how you guys take care of everything @KrauseFx @nafu @TKBurner  👍 🚀 ❤️

**Comment by KrauseFx** [comment]
Sorry it took so long, we just pushed the new release 🚀 Let us know how it works for you?

**Comment by bonzoq** [comment]
Interesting. This issue didn't occur in fastlane ver. 1.102.0 anymore. 

Anyways, thanks for your work!

**Comment by netbe** [comment]
Got this error with Xcode 8.1 on a swift 2.3 project.  `toolchain: :swift_2_3` did solve the issue

**Comment by TKBurner** [comment]
@netbe Thanks for sharing, glad you got up and running!
