### ISSUE TITLE
Running fastlane on Bitrise - non-interactive mode

### ISSUE THREAD

**Issue by mrmartineau** [fastlane/fastlane#5867]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Running a build for a new app (one that has a slightly different stack than previous apps I've setup) in Bitrise and I'm getting a few errors that I haven't before.. Now the first seems fairly explanatory but fastlane should be there in the right directory so I don't think its an issue. The second `crash` error is more ambiguous and is what I'd like to know more about. Any ideas as to why its crashing? @viktorbenei 

```
[04:07:35]: Could not find fastlane in current directory. Would you like to set it up?`
```

```
`crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode 
```

##### Complete output when running fastlane, including the stack trace and command used

```
+------------------------------------------------------------------------------+
| (5) fastlane                                                                 |
+------------------------------------------------------------------------------+
| id: fastlane                                                                 |
| version: 2.2.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-08-24T04:07:23-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
$ cd .

 (i) No Gemfile found - using system installed fastlane ...
 (i) Updating fastlane ...
$ gem install fastlane --no-document
Successfully installed gh_inspector-1.0.2
Successfully installed fastlane_core-0.50.3
Successfully installed spaceship-0.31.8
Successfully installed cert-1.4.1
Successfully installed sigh-1.9.0
Successfully installed match-0.6.2
Successfully installed supply-0.7.0
Successfully installed scan-0.11.3
Successfully installed pilot-1.10.0
Successfully installed gym-1.7.0
Successfully installed produce-1.2.0
Successfully installed pem-1.3.2
Successfully installed deliver-1.13.3
Successfully installed frameit-2.7.0
Successfully installed snapshot-1.13.1
Successfully installed word_wrap-1.0.0
Successfully installed xcode-install-2.0.2
Successfully installed krausefx-shenzhen-0.14.10
Successfully installed fastlane-1.101.0
19 gems installed

Fastlane version:
$ fastlane --version
fastlane 1.101.0

Run fastlane:
$ fastlane ios appaloosa
[04:07:35]: Could not find fastlane in current directory. Would you like to set it up?

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlane android deploy issue
   https://github.com/fastlane/fastlane/issues/5800 [closed] 2 💬
   a day ago

➡️  How to call deliver download_metadata from fastlane
   https://github.com/fastlane/fastlane/issues/5397 [closed] 8 💬
   4 weeks ago

➡️  Jenkins cannot find FastLane
   https://github.com/fastlane/fastlane/issues/4864 [closed] 0 💬
   26 May 2016

and 2 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/implementations/shell.rb:119:in `verify_interactive!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/implementations/shell.rb:97:in `confirm'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:256:in `ensure_fastfile'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:48:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | fastlane (exit code: 1)                                      | 14 sec   |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-fastlane/issues           |
| Source: https://github.com/bitrise-io/steps-fastlane                         |
+----+--------------------------------------------------------------+----------+
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.101.0"

before_all do
  slack(
    message: "Fastlane: App build started!"
  )
end

platform :ios do

  desc "Create an IPA"
  lane :appaloosa do
    match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    # deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(
      message: "Fastlane: App successfully built!"
    )
  end

  error do |lane, exception|
    slack(
      message: 'Fastlane: ' + exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

### Environment

fastlane version (run `fastlane -v`): `fastlane 1.101.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by asfalcone** [comment]
@mrmartineau is fastlane being run from the project directory where there is a Fastfile or a fastlane folder?

**Comment by mrmartineau** [comment]
@asfalcone yes. there is a `fastlane` directory in the root of the project and a `Fastfile` inside that. It is strange that the error occurs because I have setup 2 other apps recently with the same file/folder structure

```
└── fastlane
    ├── Appfile
    ├── Fastfile
    ├── Gymfile
    ├── Matchfile
    ├── README.md
    └── report.xml
```

**Comment by asfalcone** [comment]
Seems very strange. Can you echo the working directory during your run just to confirm?

**Comment by mrmartineau** [comment]
@asfalcone I did on both sides of the fastlane step (from within Bitrise) and the path was always root.. for some inexplicable reason, it is now working. Thanks for your help

**Comment by asfalcone** [comment]
@mrmartineau Glad to hear you're up and running! If there is a step that was required of you, it would be great if you could contribute to the [bitrise fastlane setup repo](https://github.com/bitrise-io/steps-fastlane/issues) so others don't run into the same pain! 👍
