### ISSUE TITLE
Produce gives an error even when successfully creating an app on iTunes Connect

### ISSUE THREAD

**Issue by GabrielCartier** [fastlane/fastlane#5874]
When running produce to create an app on iTunes connect, it seems like you get an error even though the application was successfully created. 

I have ran the test with and without skipping the dev center. Without skipping the dev center, I had a proper output, no error.
Check the output below for the information.

### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
[19:04:07]: Creating new app 'XXX' on iTunes Connect
[19:04:08]: Waiting for the newly created application to be available on iTunes Connect...
[19:04:18]: Waiting for the newly created application to be available on iTunes Connect...
[19:04:29]: Waiting for the newly created application to be available on iTunes Connect...
[19:04:39]: Waiting for the newly created application to be available on iTunes Connect...
[19:04:50]: Waiting for the newly created application to be available on iTunes Connect...
[19:05:00]: Waiting for the newly created application to be available on iTunes Connect...
[19:05:11]: Waiting for the newly created application to be available on iTunes Connect...
[19:05:22]: Successfully created new app 'XXXX' on iTunes Connect with ID XXXX

Looking for related GitHub issues on fastlane/fastlane...

➡️  pilot upload: undefined method `apple_id' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/3311 [closed] 1 💬
   08 Mar 2016

➡️  Fastlane still use old Apple account instead of new Apple Account 
   https://github.com/fastlane/fastlane/issues/5400 [open] 2 💬
   2 weeks ago

➡️  🔑 Spaceship: NoMethodError being thrown in setup_screenshots_for(row)
   https://github.com/fastlane/fastlane/issues/5676 [closed] 2 💬
   2 weeks ago

and 12 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60apple_id'%20for%20nil&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:53:in `create_new_app': [!] undefined method `apple_id' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/manager.rb:8:in `start_producing'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:127:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:11:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/bin/produce:6:in `<top (required)>'
	from /usr/local/bin/produce:23:in `load'
	from /usr/local/bin/produce:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Command was:
```
produce -u XXX -a XXX -q "XXX" -b XXX -d

+----------------+------------------------+
|        Summary for produce 1.2.0        |
+----------------+------------------------+
| username       | XXX|
| app_identifier | XXX       |
| app_name       | XXX  |
| team_id        | XXX             |
| skip_devcenter | true                   |
| sku            | XXX             |
| language       | English                |
| skip_itc       | false                  |
+----------------+------------------------+
```

### Environment

fastlane version (run `fastlane -v`): produce 1.2.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
Interesting, it seems like produce can't find the newly created application. Did this happen before?

**Comment by drorbiran** [comment]
We have the same issue.
It started today.
produce ver 1.2.0

```
[12:00:50][Step 1/1] [05:00:50]: Creating new app 'XXX' on iTunes Connect

[12:00:51][Step 1/1] Looking for related GitHub issues on fastlane/fastlane...
[12:00:51][Step 1/1] 
[12:00:52][Step 1/1] ������  undefined method `fetch' for nil:NilClass
[12:00:52][Step 1/1]    https://github.com/fastlane/fastlane/issues/5677 [open] 1 ����
[12:00:52][Step 1/1]    2 weeks ago
[12:00:52][Step 1/1] 
[12:00:52][Step 1/1] ������  Produce: undefined method `[]=' for nil:NilClass
[12:00:52][Step 1/1]    https://github.com/fastlane/fastlane/issues/5875 [closed] 6 ����
[12:00:52][Step 1/1]    5 hours ago
[12:00:52][Step 1/1] 
[12:00:52][Step 1/1] ������  undefined method `map' for nil:NilClass
[12:00:52][Step 1/1]    https://github.com/fastlane/fastlane/issues/5817 [closed] 23 ����
[12:00:52][Step 1/1]    19 hours ago
[12:00:52][Step 1/1] 
[12:00:52][Step 1/1] and 158 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]='%20for%20nil&type=Issues&utf8=���
[12:00:52][Step 1/1] /Users/vagrant/agent/work/b227cdd6c1438eaa/vendor/bundle/ruby/2.0.0/gems/spaceship-0.31.6/lib/spaceship/tunes/tunes_client.rb:232:in `create_application!': [!] undefined method `[]=' for nil:NilClass (NoMethodError)
```

**Comment by asfalcone** [comment]
@drorbiran did https://github.com/fastlane/fastlane/pull/5877 fix your issue? Run `gem update spaceship` to get spaceship 0.31.10 and let me know.

**Comment by drorbiran** [comment]
@asfalcone The update solved it. Thanks!

**Comment by GabrielCartier** [comment]
@KrauseFx yes, first time it happened to me. I got some stuff to create and test today, let me try it again with skipping dev center and then I'll tell you if it works or not.
I know exactly the steps I took to try it out.

**Comment by GabrielCartier** [comment]
I did some other test and didn't run into any issue related to that. Must've been a weird ITC response.

Thanks guys!

**Comment by TKBurner** [comment]
@GabrielCartier Awesome! Thanks so much for following up. So glad you got up and running.
