### ISSUE TITLE
Produce: undefined method `[]=' for nil:NilClass

### ISSUE THREAD

**Issue by trustyfrog** [fastlane/fastlane#5875]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X ] I have read the [Contribution Guidelines)

### Issue Description

Just a pretty bland produce using the same script I've run before. One went through this morning with no problem. This one, and another like it, started failing.

##### Complete output when running fastlane, including the stack trace and command used

```
[13:49:47]: Creating new app 'XXXX' on the Apple Dev Center
[13:49:49]: Created app XXXX
[13:49:50]: [32mFinished creating new app 'XXXX' on the Dev Center[0m
[13:50:03]: [32mCreating new app 'XXXX' on iTunes Connect[0m
[13:50:07]: [33m[33mVariable Dump:[0m[0m
[13:50:07]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios prepare"}
[13:50:07]: [31mundefined method `[]=' for nil:NilClass[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | mobi_ios_copy_assets                | 0           |
| 4    | update_info_plist                   | 0           |
| 5    | update_info_plist                   | 0           |
| 6    | update_info_plist                   | 0           |
| 7    | update_info_plist                   | 0           |
| 8    | [31mproduce[0m                             | 24          |
+------+-------------------------------------+-------------+

[13:50:08]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mundefined method `fetch' for nil:NilClass[0m
   https://github.com/fastlane/fastlane/issues/5677 [[31mopen[0m] 1 💬
   2 weeks ago

➡️  [33mundefined method `map' for nil:NilClass[0m
   https://github.com/fastlane/fastlane/issues/5817 [[32mclosed[0m] 23 💬
   9 hours ago

➡️  [33mPilot tool is crashing with undefined method 'strip' for nil:NilClass (NoMethodError)[0m
   https://github.com/fastlane/fastlane/issues/3238 [[31mopen[0m] 0 💬
   08 Mar 2016

and 157 more at: https://github.com/fastlane/fastlane/search?q=undefined method `[]=' for nil&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.9/lib/spaceship/tunes/tunes_client.rb:232:in `create_application!': [31m[!] undefined method `[]=' for nil:NilClass[0m (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.9/lib/spaceship/tunes/application.rb:80:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:25:in `create_new_app'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/manager.rb:8:in `start_producing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/actions/produce.rb:19:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/actions/produce.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/actions/produce.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:175:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:97:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE

### Configuration Files

Fastfile:

        # Create the app.
        produce(
                team_id: XXXX,
                username: XXXX,
                app_identifier: XXXX,
                app_name: XXXX,
                sku: XXXX,
                app_version: XXXX,
                language: XXXX)
```

### Environment

fastlane version (run `fastlane -v`):1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?NO

**Comment by trustyfrog** [comment]
If I manually create the app in iTC it still fails.

**Comment by trustyfrog** [comment]
If I run produce from Terminal I get the same error.

**Comment by cagataycali** [comment]
+1

**Comment by KrauseFx** [comment]
Hey @trustyfrog @cagataycali, thanks for the report and letting us know. Seems like something has changed on iTunes Connect, and we needed to update spaceship, I just prepared a fix via https://github.com/fastlane/fastlane/pull/5877. 

Once the build is green, I'll prepare a new release for you :rocket

**Comment by trustyfrog** [comment]
I guessed as much. Thanks for sorting it so quickly.

**Comment by KrauseFx** [comment]
Thanks for the patience, the new release is live with spaceship 0.31.10, please update using `[sudo ] gem update spaceship` or if you're using bundler use `bundle update` 👍 

Let us know if that fixes the issue for you 🚀
