### ISSUE TITLE
Produce gives odd Nil error instead of creating app (can create new app in iTunesConnect).

### ISSUE THREAD

**Issue by programmin1** [fastlane/fastlane#5891]
### New Issue Checklist
- [X] Updated produce to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When I use produce to create a new app, it gave an odd error.
I tried it several times, and it does work when I add it manually on iTunesConnect.
##### Complete output when running fastlane, including the stack trace and command used

```
[12:39:05]: Creating new app 'NameoftheApp' on iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `fetch' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/5677 [open] 1 💬
   2 weeks ago

➡️  Produce: undefined method `[]=' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/5875 [closed] 6 💬
   13 hours ago

➡️  undefined method `map' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/5817 [closed] 23 💬
   a day ago

and 158 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]='%20for%20nil&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.6/lib/spaceship/tunes/tunes_client.rb:232:in `create_application!': [!] undefined method `[]=' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.6/lib/spaceship/tunes/application.rb:80:in `create!'
    from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:25:in `create_new_app'
    from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:12:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/manager.rb:8:in `start_producing'
    from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:37:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:127:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:11:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/bin/produce:6:in `<top (required)>'
    from /usr/local/bin/produce:23:in `load'
    from /usr/local/bin/produce:23:in `<main>'
```
### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
Please update to the latest `spaceship` using `[sudo] gem update spaceship`

**Comment by asfalcone** [comment]
@programmin1 can you let us know if `spaceship` 0.31.10 fixes the issue for you?

**Comment by programmin1** [comment]
Oddly enough it worked before I updated it today, probably iTunes issue.

**Comment by TKBurner** [comment]
Hi @programmin1 Can you run `spaceship -v` and share the results? Thanks!
