### ISSUE TITLE
import_from_git  undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by chrissingh** [fastlane/fastlane#5892]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

import_from_git failing overtime because of a undefined method.
Just updated to the latest fast lane and started running into issues.
##### Complete output when running fastlane, including the stack trace and command used

```
[16:29:41]: -------------------------------------------------
[16:29:41]: --- Step: Verifying required fastlane version ---
[16:29:41]: -------------------------------------------------
[16:29:41]: fastlane version valid
[16:29:41]: ------------------------------
[16:29:41]: --- Step: default_platform ---
[16:29:41]: ------------------------------
[16:29:41]: Driving the lane 'ios deploy' 🚀
[16:29:41]: PodLock Exist!!
[16:29:41]: Pod Folder Exist!!
[16:29:42]: -------------------------
[16:29:42]: --- Step: pod install ---
[16:29:42]: -------------------------
[16:29:42]: $ pod install
[16:29:42]: ▸ [in /Users/a206411610/.jenkins/jobs/GolfNowOne-iOS-Beta/workspace]
[16:29:45]: ▸ Analyzing dependencies
[16:29:45]: ▸ Downloading dependencies
[16:29:45]: ▸ Installing AFNetworking (1.3.4)
[16:29:45]: ▸ Installing AWSCore (2.4.3)
[16:29:45]: ▸ Installing AWSS3 (2.4.3)
[16:29:45]: ▸ Installing CHRTextFieldFormatter (1.0.1)
[16:29:45]: ▸ Installing CocoaAsyncSocket (7.4.3)
[16:29:45]: ▸ Installing Crashlytics (3.7.0)
[16:29:45]: ▸ Installing Fabric (1.6.7)
[16:29:45]: ▸ Installing ISO8601DateFormatterValueTransformer (0.6.1)
[16:29:45]: ▸ Installing MBProgressHUD (0.9.2)
[16:29:45]: ▸ Installing OpenSans (1.0.3)
[16:29:45]: ▸ Installing PureLayout (3.0.1)
[16:29:45]: ▸ Installing REMenu (1.10)
[16:29:45]: ▸ Installing RKValueTransformers (1.1.3)
[16:29:45]: ▸ Installing RestKit (0.26.0)
[16:29:45]: ▸ Installing SOCKit (1.1)
[16:29:45]: ▸ Installing SSZipArchive (1.2)
[16:29:45]: ▸ Installing SmartPopNavigationController (0.1.2)
[16:29:45]: ▸ Installing SmartUITableView (0.2.9)
[16:29:45]: ▸ Installing TPKeyboardAvoiding (1.2.11)
[16:29:45]: ▸ Installing TransitionKit (2.2.1)
[16:29:45]: ▸ Installing UIAlertView-Blocks (1.0)
[16:29:45]: ▸ Installing ZXingObjC (3.1.0)
[16:29:45]: ▸ Generating Pods project
[16:29:48]: ▸ Integrating client project
[16:29:48]: ▸ Sending stats
[16:29:48]: ▸ Pod installation complete! There are 16 dependencies from the Podfile and 22 total pods installed.
[16:29:48]: ▸ [!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
[16:29:48]: ▸ [!] The `NativeiOSBooker [Debug]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods-NativeiOSBooker/Pods-NativeiOSBooker.debug.xcconfig'. This can lead to problems with the CocoaPods installation
[16:29:48]: ▸ [!] The `NativeiOSBooker [Release]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods-NativeiOSBooker/Pods-NativeiOSBooker.release.xcconfig'. This can lead to problems with the CocoaPods installation
[16:29:48]: ▸ - Use the `$(inherited)` flag, or
[16:29:48]: ▸ - Remove the build settings from the target.
[16:29:48]: ▸ - Use the `$(inherited)` flag, or
[16:29:48]: ▸ - Remove the build settings from the target.
[16:29:48]: -----------------------------
[16:29:48]: --- Step: import_from_git ---
[16:29:48]: -----------------------------
[16:29:48]: Cloning remote git repo...
[16:29:48]: $ git clone 'https://bigmega@xxxxxxxxx.org/xxxxx/xxxx-common.git' '/var/folders/4f/hqw_0rb13jg3xpykgkl163f00000gp/T/fl_clone20160825-60956-1cx0jf0/golfnow-common.git' --depth 1 -n --branch master
[16:29:48]: ▸ Cloning into '/var/folders/4f/hqw_0rb13jg3xpykgkl163f00000gp/T/fl_clone20160825-60956-1cx0jf0/golfnow-common.git'...
[16:29:50]: $ cd '/var/folders/4f/hqw_0rb13jg3xpykgkl163f00000gp/T/fl_clone20160825-60956-1cx0jf0/golfnow-common.git' && git checkout master 'fastlane/Fastfile'
[16:29:50]: $ cd '/var/folders/4f/hqw_0rb13jg3xpykgkl163f00000gp/T/fl_clone20160825-60956-1cx0jf0/golfnow-common.git' && git checkout master 'fastlane/actions'
[16:29:50]: ▸ error: pathspec 'fastlane/actions' did not match any file(s) known to git.
/Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jira-0.1.0/lib/jira/cli.rb:28: warning: else without rescue is useless
[16:29:50]: Variable Dump:
[16:29:50]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy"}
[16:29:50]: undefined method `[]' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | pod install                         | 6           |
| 4    | import_from_git                     | 1           |
+------+-------------------------------------+-------------+

[16:29:50]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `fetch' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/5677 [open] 1 💬
   2 weeks ago

➡️  Produce: undefined method `[]=' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/5875 [closed] 6 💬
   14 hours ago

➡️  undefined method `map' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/5817 [closed] 23 💬
   a day ago

and 159 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]'%20for%20nil&type=Issues&utf8=✓
/Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:51:in `rescue in block in parse': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:41:in `block in parse'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:37:in `chdir'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:37:in `parse'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:193:in `import'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:237:in `block in import_from_git'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:206:in `import_from_git'
	from Fastfile:31:in `block (2 levels) in parsing_binding'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:206:in `call'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:206:in `execute_flow_block'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:46:in `block in execute'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/a206411610/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /Users/a206411610/.rbenv/versions/2.2.3/bin/fastlane:23:in `load'
	from /Users/a206411610/.rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure

### Configuration Files
```
Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`): fast lane 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by asfalcone** [comment]
@chrissingh can you please share your Fastfile? What are you trying to import from git? Thanks!

**Comment by chrissingh** [comment]
I was able to resolve my issues on our build server. I reinstalled a few gems. We did realize krausefx-ipa no longer support uploading to UberTesters. So we had to change that command to a CURL upload and everything seems to be working normally again. Thank you for your reply.

**Comment by TKBurner** [comment]
@chrissingh Awesome! Really glad to hear you got up and running. Hope you have a wonderful day!
