### ISSUE TITLE
Question: Should running UI Tests with scan require an executable set in the scheme?

### ISSUE THREAD

**Issue by cooksimo** [fastlane/fastlane#5896]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When running scan on a default UI Test scheme I get the following error:
##### Complete output when running fastlane, including the stack trace and command used

```
scan --workspace App.xcworkspace --device "iPhone 6 Plus" --scheme "UITests"
[09:57:35]: xcodebuild -list -workspace App.xcworkspace

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Spaceship] TypeError: no implicit conversion of String into Integer in app_version.rb:641
   https://github.com/fastlane/fastlane/issues/5652 [closed] 9 💬
   2 weeks ago

➡️  no implicit conversion of nil into String
   https://github.com/fastlane/fastlane/issues/3379 [closed] 3 💬
   08 Mar 2016

➡️  [No implicit conversion of nil into String] on supply init
   https://github.com/fastlane/fastlane/issues/3377 [closed] 5 💬
   08 Mar 2016

and 33 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `include?': [!] no implicit conversion of nil into String (TypeError)
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `block in default_device_ios'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `default_device_ios'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan/detect_values.rb:23:in `set_additional_default_values'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan.rb:27:in `config='
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan/manager.rb:4:in `work'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan/commands_generator.rb:41:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan/commands_generator.rb:60:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/lib/scan/commands_generator.rb:14:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.11.3/bin/scan:6:in `<top (required)>'
    from /usr/local/bin/scan:23:in `load'
    from /usr/local/bin/scan:23:in `<main>'
```

The default UITest scheme does not have an executable set, this doesn't seem to be required for XCode to run these tests, but scan fails. Is it expected that the scheme needs an executable set?(when I set this to the main app executable everything works fine)
### Environment

fastlane version (run `fastlane -v`): scan version 0.11.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by tanhuiya** [comment]
I have the same error with you .

**Comment by TKBurner** [comment]
@revile Can you try using ruby 2.3+ and let me know if you are still seeing this issue. It looks like you are using system ruby and that might be why you are running into this issue. Thanks!
