### ISSUE TITLE
Scan fails for Logical Unit Test Scheme

### ISSUE THREAD

**Issue by timothy-volvo** [fastlane/fastlane#5901]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When passing in a Logical Unit Test Scheme into scan, it fails trying to determine the deployment target as "xcodebuild -showBuildSettings" doesn't return any values for Logical Unit Test Scheme unless the test build action is passed in. This worked until #5640 introduced the call to check the deployment target.

One possible solution would be to have the FastlaneCore::Project class check the scheme type to adjust the buildaction accordingly:

```
    def build_xcodebuild_showbuildsettings_command
      # We also need to pass the workspace and scheme to this command
      command = "xcodebuild -showBuildSettings #{xcodebuild_parameters.join(' ')} #{build_xcodebuild_showbuildsettings_action}"
      command += " 2> /dev/null" if xcodebuild_suppress_stderr
      command
    end

    def build_xcodebuild_showbuildsettings_action
      
      if options[:scheme] and scheme_buildable_name.end_with?".xctest"
        return "test"
      else
        return "build" #could also be ""
      end
    end

   def scheme_buildable_name
      # Not Sure how to extract from .xcscheme, maybe a xcodeproj class or xml parser to access
      # Scheme/BuildAction/BuildActionEntries/BuildActionEntry/BuildableReference#BuildableName
   end
```

##### Complete output when running fastlane, including the stack trace and command used

```
/usr/local/lib/ruby/gems/2.3.0/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `include?': [!] no implicit conversion of nil into String (TypeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `block in default_device_ios'
	from /usr/local/lib/ruby/gems/2.3.0/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `default_device_ios'
	from /usr/local/lib/ruby/gems/2.3.0/gems/scan-0.11.3/lib/scan/detect_values.rb:23:in `set_additional_default_values'
	from /usr/local/lib/ruby/gems/2.3.0/gems/scan-0.11.3/lib/scan.rb:27:in `config='
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/actions/scan.rb:14:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:175:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from ../xcutils/xcfastlane/Fastfile:606:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:153:in `try_switch_to_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:108:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from ../xcutils/xcfastlane/Fastfile:208:in `block (3 levels) in parsing_binding'
	from ../xcutils/xcfastlane/Fastfile:199:in `each'
	from ../xcutils/xcfastlane/Fastfile:199:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

```

### Configuration Files

N/A

### Environment

fastlane version (run `fastlane -v`): fastlane 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by TKBurner** [comment]
@timothy-volvo Hope you are doing well! Sorry to hear that you ran into this. Any chance you are interested in submitting a PR to correct this behavior? I'm marking this as help wanted in case anyone wants to submit a PR around this. Thanks!

**Comment by timothy-volvo** [comment]
Sure, the only reason I didn't was I wasn't sure the best was to parse the xcscheme (see psuedo code in initial comment). Xcodeproj seems to have a class, but nothing else in fastlane core depends on it so I was hesitant to introduce that dependency. There are some actions that use xcodeproj, but not the core itself.

**Comment by TKBurner** [comment]
Thanks @timothy-volvo. I think you can rely on this dependency.

Thanks!

**Comment by timothy-volvo** [comment]
As is turns out there might not be an issue here.

When Xcode creates a Scheme for a Unit Test is only has the Test action enable. When only the Test action is enable, xcodebuild -showBuildSettings doesn't show any settings for the build action only the test action as I originally reported.  However, xcodebuild also fails to run the test since no Run action has been defined. Once the Run action is enabled xcodebuild -showBuildSettings works as expected for the build action.

I have a patch ready using REMXML, but will hold off unless I see the issue again

**Comment by TKBurner** [comment]
@timothy-volvo Thanks for the update. I'm going to close this for now but feel free to ping it and I'll reopen once we have more info. Thanks and have a great weekend! 👍
