### ISSUE TITLE
784: unexpected token at 'Bad Request'

### ISSUE THREAD

**Issue by ziadtamim** [fastlane/fastlane#5903]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Today whenever I try to run Match, I get the following error: 
`[!] 784: unexpected token at 'Bad Request'`
##### Complete output when running fastlane, including the stack trace and command used

```
[15:18:08]: Starting login with user 'santanajk@aol.com'
[15:18:11]: Successfully logged in
[15:18:11]: Fetching profiles...
[15:18:12]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[15:18:17]: Creating new provisioning profile for 'com.intensifystudio.stx' with name 'match Development com.intensifystudio.stx'
[15:18:22]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...

➡️  PEM [!] 784: unexpected token at 'Bad Request'
   https://github.com/fastlane/fastlane/issues/5849 [closed] 3 💬
   a day ago

➡️  Still getting '757: unexpected token at "Bad Request"'
   https://github.com/fastlane/fastlane/issues/5827 [closed] 59 💬
   a day ago

➡️  "unexpected token at 'Bad Request'" from Spaceship when attempting to repair a provisioning profile
   https://github.com/fastlane/fastlane/issues/5813 [closed] 36 💬
   2 days ago

and 4 more at: https://github.com/fastlane/fastlane/search?q=784:%20unexpected%20token%20at%20'Bad%20Request'&type=Issues&utf8=✓
/Users/ziadtamim/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `parse': [!] 784: unexpected token at 'Bad Request' (Faraday::ParsingError)
    from /Users/ziadtamim/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `parse'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/spaceship-0.31.10/lib/spaceship/client.rb:413:in `block in send_request'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/spaceship-0.31.10/lib/spaceship/client.rb:330:in `with_retry'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/spaceship-0.31.10/lib/spaceship/client.rb:412:in `send_request'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/spaceship-0.31.10/lib/spaceship/client.rb:387:in `request'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/spaceship-0.31.10/lib/spaceship/portal/portal_client.rb:370:in `create_provisioning_profile!'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/spaceship-0.31.10/lib/spaceship/portal/provisioning_profile.rb:230:in `block in create!'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/spaceship-0.31.10/lib/spaceship/client.rb:330:in `with_retry'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/spaceship-0.31.10/lib/spaceship/portal/provisioning_profile.rb:229:in `create!'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/sigh-1.9.0/lib/sigh/runner.rb:113:in `create_profile!'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/sigh-1.9.0/lib/sigh/runner.rb:39:in `run'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/sigh-1.9.0/lib/sigh/manager.rb:7:in `start'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/match-0.6.2/lib/match/generator.rb:57:in `generate_provisioning_profile'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/match-0.6.2/lib/match/runner.rb:84:in `profile'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/match-0.6.2/lib/match/runner.rb:21:in `run'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/match-0.6.2/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/match-0.6.2/lib/match/commands_generator.rb:121:in `run'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/match-0.6.2/lib/match/commands_generator.rb:12:in `start'
    from /Users/ziadtamim/.rvm/gems/ruby-2.3.1@global/gems/match-0.6.2/bin/match:6:in `<top (required)>'
    from /Users/ziadtamim/.rvm/rubies/ruby-2.3.1/bin/match:23:in `load'
    from /Users/ziadtamim/.rvm/rubies/ruby-2.3.1/bin/match:23:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.101.0"

default_platform :ios

APP_NAME = "App Name"

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/T0E8Q..."

  end

  ##### Apple Member Center ######

  desc "Updates the development provisioning profiles"
  lane :dev_certificates_update do
    match(type: "development", app_identifier: BUNDLE_ID, username: USERNAME, readonly: false, force: true)
    match(type: "development", app_identifier: BUNDLE_ID_WATCH, username: USERNAME, readonly: false, force: true)
    match(type: "development", app_identifier: BUNDLE_ID_WATCH_EXTENSION, username: USERNAME, readonly: false, force: true)
  end

  desc "Updates the distribution provisioning profiles"
  lane :dist_certificates_update do
    match(type: "appstore", app_identifier: BUNDLE_ID, username: USERNAME, readonly: false, force: true)
    match(type: "appstore", app_identifier: BUNDLE_ID_WATCH, username: USERNAME, readonly: false, force: true)
    match(type: "appstore", app_identifier: BUNDLE_ID_WATCH_EXTENSION, username: USERNAME, readonly: false, force: true)
  end

  # Test
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    install_pods
    build_local
    pilot(skip_waiting_for_build_processing: true)
  end

  desc "Deploy a new version to the App Store"
  lane :deploy_appstore do
    install_pods
    build_local
    deliver(force: true)
  end

  # Private
  private_lane :build_local do |options|
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })

    gym({ workspace: APP_NAME + ".xcworkspace",
     output_name: APP_NAME,
     configuration: "Release",
     clean: true, 
     scheme: APP_NAME })
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
Hey @ziadtamim, thanks for submitting this issue. We prepared a fix for the problem with https://github.com/fastlane/fastlane/pull/5908. Could you give it a try before we publish a new release? 

```
git clone -b spaceship-csrf-fix --single-branch git@github.com:fastlane/fastlane.git
cd fastlane/spaceship
[sudo] gem install bundler
bundle install
rake install
```
and then give it a try again 👍

**Comment by ziadtamim** [comment]
Thanks @KrauseFx. It's working now.

**Comment by KrauseFx** [comment]
Thanks for letting us know @ziadtamim 👍  Great to hear
