### ISSUE TITLE
How to install certificates from repo while Apple maintenance

### ISSUE THREAD

**Issue by k06a** [fastlane/fastlane#5917]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Looks like Apple maintenance prevent match to work at all. I there any way to run match to just install certificates from repo and skip profiles check in Apple Dev Center?

##### Complete output when running fastlane, including the stack trace and command used

```
[14:11:15]: Cloning remote git repo...
[14:11:39]: 🔓  Successfully decrypted certificates repo
[14:11:39]: Verifying that the certificate and profile are still valid on the Dev Portal...
[14:13:30]: Installing certificate...
[14:14:04]: 🔒  Successfully encrypted certificates repo
[14:14:04]: Variable Dump:
[14:14:04]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios adhoc"}
[14:14:04]: <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
     <key>resultCode</key>
     <integer>503</integer>
     <key>userString</key>
     <string>The Apple Developer website is undergoing maintenance. For details, visit developer.apple.com/system-status.</string>
     <key>resultString</key>
     <string>The Apple Developer website is undergoing maintenance. For details, visit developer.apple.com/system-status.</string>
     <key>httpCode</key>
     <integer>503</integer>
     <key>userLocale</key>
     <string>en_US</string>
  </dict>
</plist>

        from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/spaceship-0.31.10/lib/spaceship/portal/portal_client.rb:352:in `provisioning_profiles'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/spaceship-0.31.10/lib/spaceship/portal/provisioning_profile.rb:246:in `all'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/match-0.6.2/lib/match/runner.rb:103:in `device_count_different?'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/match-0.6.2/lib/match/runner.rb:79:in `profile'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/match-0.6.2/lib/match/runner.rb:21:in `run'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/actions/match.rb:11:in `run'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/runner.rb:175:in `block in execute_action'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `chdir'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `execute_action'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:57:in `block (2 levels) in parsing_binding'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/bin/fastlane:22:in `load'
	from /Users/k06a/.rvm/gems/ruby-2.2.5/bin/fastlane:22:in `<main>'
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
RVM

**Comment by k06a** [comment]
Just did `match decrypt` and manually imported all profiles and certificates from repo.

**Comment by KrauseFx** [comment]
You can run `match --readonly` to not access the developer portal and just use the git profiles 👍

**Comment by k06a** [comment]
@KrauseFx thanks!

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/5922, to show the message right when the error occurs
