### ISSUE TITLE
wrong number of arguments (given 1, expected 2) in snapshot runner.rb:200

### ISSUE THREAD

**Issue by cwilhelm** [fastlane/fastlane#5976]
##### Complete output when running fastlane, including the stack trace and command used

```
WARN [2016-09-01 17:28:33.32]: Erasing iPhone 6 Plus...
DEBUG [2016-09-01 17:28:33.39]: Fetching available simulator devices
ERROR [2016-09-01 17:28:33.48]: wrong number of arguments (given 1, expected 2)
ERROR [2016-09-01 17:28:33.48]: Backtrace:
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/test_command_generator.rb:67:in `find_device'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:200:in `open_simulator_for_device'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:151:in `launch'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:70:in `run_for_device_and_language'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:76:in `rescue in run_for_device_and_language'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:70:in `run_for_device_and_language'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:49:in `block (3 levels) in work'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:37:in `each'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:37:in `each_with_index'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:37:in `block (2 levels) in work'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:36:in `each'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:36:in `block in work'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:35:in `each'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:35:in `each_with_index'
        /usr/local/lib/ruby/gems/2.3.0/gems/snapshot-1.14.0/lib/snapshot/runner.rb:35:in `work'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/actions/snapshot.rb:17:in `run'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:175:in `block in execute_action'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `chdir'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `execute_action'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:140:in `method_missing'
        ../../../../../../../../../../../var/folders/_7/x9hx93w16lz4y5clj8g44xx40000gn/T/fl_clone20160901-32843-h2y4jo/fastlane.git/fastlane/Fastfile.ios:101:in `block (4 levels) in parsing_binding'
        ../../../../../../../../../../../var/folders/_7/x9hx93w16lz4y5clj8g44xx40000gn/T/fl_clone20160901-32843-h2y4jo/fastlane.git/fastlane/Fastfile.ios:92:in `each'
        ../../../../../../../../../../../var/folders/_7/x9hx93w16lz4y5clj8g44xx40000gn/T/fl_clone20160901-32843-h2y4jo/fastlane.git/fastlane/Fastfile.ios:92:in `block (3 levels) in parsing_binding'
        ../../../../../../../../../../../var/folders/_7/x9hx93w16lz4y5clj8g44xx40000gn/T/fl_clone20160901-32843-h2y4jo/fastlane.git/fastlane/Fastfile.ios:91:in `each'
        ../../../../../../../../../../../var/folders/_7/x9hx93w16lz4y5clj8g44xx40000gn/T/fl_clone20160901-32843-h2y4jo/fastlane.git/fastlane/Fastfile.ios:91:in `block (2 levels) in parsing_binding'
        ../../../../../../../../../../../var/folders/_7/x9hx93w16lz4y5clj8g44xx40000gn/T/fl_clone20160901-32843-h2y4jo/fastlane.git/fastlane/Fastfile.ios:89:in `loop'
        ../../../../../../../../../../../var/folders/_7/x9hx93w16lz4y5clj8g44xx40000gn/T/fl_clone20160901-32843-h2y4jo/fastlane.git/fastlane/Fastfile.ios:89:in `block in parsing_binding'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:153:in `try_switch_to_lane'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:108:in `trigger_action_by_name'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:140:in `method_missing'
        ../../../../../../../../../../../var/folders/_7/x9hx93w16lz4y5clj8g44xx40000gn/T/fl_clone20160901-32843-h2y4jo/fastlane.git/fastlane/Fastfile.ios:33:in `block (2 levels) in parsing_binding'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:49:in `block in execute'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `chdir'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `execute'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/command_line_handler.rb:30:in `handle'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
        /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
        /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:246:in `run'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:20:in `start'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
        /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
        /usr/local/bin/fastlane:23:in `load'
        /usr/local/bin/fastlane:23:in `<main>'
```
### Environment

fastlane 1.102.0

**Comment by TKBurner** [comment]
Hi @cwilhelm Thanks for the PR. Can you add testing to it so we can merge faster? We'll work with you there 👍 Thanks!

**Comment by KrauseFx** [comment]
Perfect, thanks @cwilhelm. I saw that the parameter was missing, however I couldn't cause a crash locally. In what use-cases did this cause an issue? Should we do a release for this change?

**Comment by cwilhelm** [comment]
My call of snapshot is 
```
snapshot(
    app_identifier: app_identifier,
    reinstall_app: true,
    localize_simulator: true,
   skip_open_summary: true
)
```
which fastlane outputs as
```
+----------------------------+-----------------------------------------------------------------+
|                                   Summary for snapshot 1.14.0                                    |
+----------------------------+-----------------------------------------------------------------+
| app_identifier             | com.ieffects.xxx.demo.dev                                       |
| reinstall_app              | true                                                                |
| localize_simulator         | true                                                                |
| skip_open_summary          | true                                                                |
| devices                    | ["iPhone 6s", "iPhone 6s Plus", "iPhone 5s"]                        |
| languages                  | ["en-US", "de-DE"]                                                  |
| scheme                     | xxxDemo-dev                                                     |
| workspace                  | ./xxxDemo.xcworkspace                                           |
| output_directory           | /Users/cwilhelm/Documents/workspace/ifxshop/shops/iphone/xxx... |
| launch_arguments           | [""]                                                                |
| clear_previous_screenshots | false                                                               |
| erase_simulator            | false                                                               |
| buildlog_path              | ~/Library/Logs/snapshot                                             |
| clean                      | false                                                               |
| number_of_retries          | 1                                                                   |
| stop_after_first_error     | false                                                               |
+----------------------------+------------------------------------------------------------------+
```
and the before mentioned backtrace. Do you need more information?

**Comment by KrauseFx** [comment]
I tried running it with the exact same parameters and it's working just as expected for me. Could you upload a demo project or get it to fail on the snapshot sample project?

**Comment by cwilhelm** [comment]
👍 for newer releases.
