### ISSUE TITLE
Custom script in lane not found

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#6005]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I can't run a custom script in a lane. The [README](https://github.com/fastlane/fastlane/blob/master/README.md) only has `sh "./customScript.sh"` but it doesn't have more details. Adding a script as `sh "./fastlane/screenshots/clear_logs.sh"`, fails with `/Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/helper/sh_helper.rb:35:in`popen': [!] No such file or directory - ./fastlane/screenshots/clear_logs.sh (Errno::ENOENT)`
##### Complete output when running fastlane, including the stack trace and command used

```
❯ fastlane screenshots
[22:48:46]: -------------------------------------------------
[22:48:46]: --- Step: Verifying required fastlane version ---
[22:48:46]: -------------------------------------------------
[22:48:46]: fastlane version valid
[22:48:46]: ------------------------------
[22:48:46]: --- Step: default_platform ---
[22:48:46]: ------------------------------
[22:48:46]: Driving the lane 'ios screenshots' 🚀
[22:48:46]: --------------------------------------------------
[22:48:46]: --- Step: ./fastlane/screenshots/clear_logs.sh ---
[22:48:46]: --------------------------------------------------
[22:48:46]: $ ./fastlane/screenshots/clear_logs.sh
[22:48:46]: Variable Dump:
[22:48:46]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios screenshots"}
[22:48:46]: No such file or directory - ./fastlane/screenshots/clear_logs.sh

+------+--------------------------------------+-------------+
|                     fastlane summary                      |
+------+--------------------------------------+-------------+
| Step | Action                               | Time (in s) |
+------+--------------------------------------+-------------+
| 1    | Verifying required fastlane version  | 0           |
| 2    | default_platform                     | 0           |
| 3    | ./fastlane/screenshots/clear_logs.sh | 0           |
+------+--------------------------------------+-------------+

[22:48:46]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/helper/sh_helper.rb:35:in `popen': [!] No such file or directory - ./fastlane/screenshots/clear_logs.sh (Errno::ENOENT)
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/helper/sh_helper.rb:35:in `sh_control_output'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/helper/sh_helper.rb:14:in `sh_no_action'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:170:in `block in sh'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:169:in `sh'
        from Fastfile:27:in `block (2 levels) in parsing_binding'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:49:in `block in execute'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `chdir'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:246:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:20:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
fastlane_version "1.101.0"

default_platform :ios

platform :ios do
    desc "Creates App Store screenshots"
    lane :screenshots do
        sh "./fastlane/screenshots/clear_logs.sh"

        snapshot
    end
end

```
### Environment

fastlane version (run `fastlane -v`): `fastlane 1.102.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by TKBurner** [comment]
Hi @revolter Are you running from the project folder or the fastlane folder? Can you try the other? Thanks!

**Comment by revolter** [comment]
I am running from the project folder. Is there any possibility for it to show the full path that it's trying to run? It would help a lot.

**Comment by KrauseFx** [comment]
`sh` is being executed in your project folder, not in fastlane as far as I know. Could you give it a try to prepend the path with `..`?

**Comment by maschall** [comment]
@KrauseFx in our Fastfile, we have to do the following `sh 'cd ..; pod update'` for it to work properly (pod update can be ran from any subfolder, but our post_install required from the project folder).

**Comment by KrauseFx** [comment]
@maschall yeah, that sounds about right 👍
