### ISSUE TITLE
No code signing identity found in readonly - and exhausted in default mode

### ISSUE THREAD

**Issue by geoHeil** [fastlane/fastlane#6059]
### Issue Description

The certificates were created and saved to a git repository. Unfortunately fastlane has problem retrieving the keys. In case `--readonl`y is **not** used apple declines to create a new certificate because some were already created

##### Complete output when running fastlane, including the stack trace and command used

```
match development --readonly --verbose --git_url git@gitlab.faktorzehn.at:MaklerApp/certificates.git

+-----------------------+-----------------------------------------------------+
|                           Summary for match 0.6.3                           |
+-----------------------+-----------------------------------------------------+
| readonly              | true                                                |
| verbose               | true                                                |
| git_url               | url.git |
| type                  | development                                         |
| git_branch            | master                                              |
| app_identifier        | app.id                                  |
| username              | e-mail                               |
| keychain_name         | login.keychain                                      |
| team_id               | id                                          |
| force                 | false                                               |
| shallow_clone         | false                                               |
| force_for_new_devices | false                                               |
| skip_docs             | false                                               |
+-----------------------+-----------------------------------------------------+

INFO [2016-09-09 15:49:47.38]: Cloning remote git repo...
INFO [2016-09-09 15:49:47.38]: $ git clone 'git@gitlab.faktorzehn.at:MaklerApp/certificates.git' '/var/folders/0r/dh5tqhf14r571yqlh0037n7c0000gn/T/d20160909-8804-13zu7vr'
INFO [2016-09-09 15:49:47.38]: ▸ Cloning into '/var/folders/0r/dh5tqhf14r571yqlh0037n7c0000gn/T/d20160909-8804-13zu7vr'...
INFO [2016-09-09 15:49:47.89]: ▸ remote: Counting objects: 33, done.
INFO [2016-09-09 15:49:47.89]: ▸ remote: Compressing objects: 100% (27/27), done.
INFO [2016-09-09 15:49:47.89]: ▸ remote: Total 33 (delta 3), reused 0 (delta 0)
INFO [2016-09-09 15:49:47.89]: ▸ Receiving objects: 100% (33/33), 57.95 KiB | 0 bytes/s, done.
INFO [2016-09-09 15:49:47.89]: ▸ Resolving deltas: 100% (3/3), done.
INFO [2016-09-09 15:49:47.94]: 🔓  Decrypted '6F4CUUG955.cer'
INFO [2016-09-09 15:49:47.98]: 🔓  Decrypted '6F4CUUG955.p12'
INFO [2016-09-09 15:49:48.02]: 🔓  Decrypted 'AdHoc_at.faktorzehn.eule.mobileprovision'
INFO [2016-09-09 15:49:48.05]: 🔓  Decrypted 'AppStore_at.faktorzehn.eule.mobileprovision'
INFO [2016-09-09 15:49:48.09]: 🔓  Decrypted 'AppStore_at.faktorzehn.eule.staging.mobileprovision'
INFO [2016-09-09 15:49:48.09]: 🔓  Successfully decrypted certificates repo
WARN [2016-09-09 15:49:48.09]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now
INFO [2016-09-09 15:49:48.10]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...
Search query: No code signing identity found and can not create a new one because you enabled `readonly`

URL: https://api.github.com/search/issues?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60+repo:fastlane/fastlane
➡️  No matching provisioning profiles found in `readonly` mode
   https://github.com/fastlane/fastlane/issues/1979 [closed] 9 💬
   a week ago

➡️  Match for Jenkins, provisioning profile could not be found when using readonly
   https://github.com/fastlane/fastlane/issues/3444 [closed] 5 💬
   29 Jun 2016

➡️  pilot crashes on upload
   https://github.com/fastlane/fastlane/issues/4821 [open] 22 💬
   2 weeks ago

and 3 more at: https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=✓
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] No code signing identity found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneCrash)
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.3/lib/match/runner.rb:54:in `certificate'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.3/lib/match/runner.rb:17:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.3/lib/match/commands_generator.rb:53:in `block (3 levels) in run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.3/lib/match/commands_generator.rb:119:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.3/lib/match/commands_generator.rb:12:in `start'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.6.3/bin/match:6:in `<top (required)>'
       	from /usr/local/bin/match:23:in `load'
       	from /usr/local/bin/match:23:in `<main>'
```

### Configuration Files

I use https://github.com/platanus/fastlane-cordova

### Environment

fastlane version: fastlane 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by geoHeil** [comment]
In case I run match nuke clearly the certificate is listed and found in the repository.

**Comment by KrauseFx** [comment]
Could you post the complete tree (all files and folders) of your git repo that contains your certificates and profiles?

**Comment by geoHeil** [comment]
That would be 
```
├── README.md
├── certs
│   └── distribution
│       ├── 6F4CUUG955.cer
│       └── 6F4CUUG955.p12
├── match_version.txt
└── profiles
    ├── adhoc
    │   └── AdHoc_at.faktorzehn.eule.mobileprovision
    └── appstore
        ├── AppStore_at.faktorzehn.eule.mobileprovision
        └── AppStore_at.faktorzehn.eule.staging.mobileprovision

5 directories, 7 files
```

**Comment by KrauseFx** [comment]
Yeah, but that's why it's not working. You have to run _match_ without readonly, so that it can create the missing development certificates and profiles 👍

**Comment by geoHeil** [comment]
So I need to nuke it first?
Because apple tells me the number of certificates is exhausted...
Felix Krause <notifications@github.com> schrieb am Mo. 19. Sep. 2016 um
22:01:

**Comment by KrauseFx** [comment]
Yeah
