### ISSUE TITLE
`fastlane actions` and `fastlane init` both fail

### ISSUE THREAD

**Issue by drosenstark** [fastlane/fastlane#6064]
I'm stuck at step 1. Thanks for any help.

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Stack trace instead of output for `fastlane actions` and `fastlane init`

## fastlane actions
```
/Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source': uninitialized constant Gem::Source (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
	from /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:322:in `have_file?'
	from /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:79:in `contains_requirable_file?'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1082:in `block (2 levels) in find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2621:in `[]'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2621:in `block (2 levels) in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `block in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2627:in `block (2 levels) in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `block in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1078:in `block in find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1077:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1077:in `find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:86:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/source.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
	from /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:322:in `have_file?'
	from /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:79:in `contains_requirable_file?'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1082:in `block (2 levels) in find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2621:in `[]'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2621:in `block (2 levels) in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `block in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2627:in `block (2 levels) in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `block in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1078:in `block in find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1077:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1077:in `find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:86:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_integration.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler.rb:11:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugin_manager.rb:3:in `<class:PluginManager>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugin_manager.rb:2:in `<module:Fastlane>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugin_manager.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane.rb:22:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

## fastlane init
```
same output as above
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
n/a
```

### Environment

fastlane version (run `fastlane -v`): **same error!**

`gem list` produces

```
fastlane (1.102.0)
fastlane_core (0.51.0, 0.36.1, 0.33.0)
```

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **No**

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **No**

### Other Info

Ruby Version: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
Gem Version: 2.6.6

**Comment by drosenstark** [comment]
Sorry, El Capitan problem. Solved by redoing the install using `sudo gem install -n /usr/local/bin fastlane --verbose`

**Comment by isolution-de** [comment]
Having the same issue, how did you resolve it?

**Comment by drosenstark** [comment]
@isolution-de  Sorry, I moved the issue here: https://github.com/fastlane/fastlane/issues/6065#issuecomment-246719051  Thanks!
