### ISSUE TITLE
all fastlane commands fail

### ISSUE THREAD

**Issue by drosenstark** [fastlane/fastlane#6065]
I managed to get `fastlane` to install on El Capitan using `sudo gem install -n /usr/local/bin fastlane --verbose` but fastlane itself doesn't work. Thanks for any help.

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Stack trace instead of output for `fastlane actions` and `fastlane init`

## fastlane actions
```
/Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source': uninitialized constant Gem::Source (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
	from /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:322:in `have_file?'
	from /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:79:in `contains_requirable_file?'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1082:in `block (2 levels) in find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2621:in `[]'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2621:in `block (2 levels) in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `block in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2627:in `block (2 levels) in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `block in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1078:in `block in find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1077:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1077:in `find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:86:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/source.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
	from /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:322:in `have_file?'
	from /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:79:in `contains_requirable_file?'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1082:in `block (2 levels) in find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2621:in `[]'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2621:in `block (2 levels) in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `block in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2627:in `block (2 levels) in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2616:in `block in traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2614:in `traverse'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1078:in `block in find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1077:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1077:in `find_in_unresolved_tree'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:86:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler/rubygems_integration.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.0/lib/bundler.rb:11:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugin_manager.rb:3:in `<class:PluginManager>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugin_manager.rb:2:in `<module:Fastlane>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugin_manager.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane.rb:22:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

## fastlane init
```
same output as above
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
n/a
```

### Environment

fastlane version (run `fastlane -v`): **same error!**

`gem list` produces

```
fastlane (1.102.0)
fastlane_core (0.51.0, 0.36.1, 0.33.0)
```

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **No**

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **No**

### Other Info

Ruby Version: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
Gem Version: 2.6.6

**Comment by PetrosIchor** [comment]
I was getting very similar issues a moment ago.  For my, bundler updated to 1.13 (pushed yesterday).   Removing that version and rolling back fixed fastlane and other gem related issues I was having. 
So:
gem uninstall bundler -v1.13

**Comment by drosenstark** [comment]
That worked! I had to do

sudo gem uninstall bundler -v1.13

which uninstalled the whole thing, and then a fancier thing for El Cap

sudo gem install -n /usr/local/bin bundler -v 1.12

Now I'm up and running. Thanks!

**Comment by chanricle** [comment]
Thanks `drosenstark` provide commands! I have tried these command, but when I check bundler version 
```
➜  ~ bundler -v
Bundler version 1.13.0
```

The default version of Bundler is 1.13.0. So I ran uninstall command like
```
gem uninstall bundler

Select gem to uninstall:
 1. bundler-1.12.0
 2. bundler-1.13.0
 3. All versions
> 2
Successfully uninstalled bundler-1.13.0
```

After this, my default bundler version is 1.12.0, and fastlane worked !

**Comment by isolution-de** [comment]
On mac OS Sierra I had the same issue.
After updating gems, uninstalling bundler (sudo gem uninstall bundler) with all dependencies and reinstalling (got bundler 1.13.1) it seems to work for now.

**Comment by TKBurner** [comment]
@isolution-de Thanks for letting us know! Really glad to hear you got up and running 👍
