### ISSUE TITLE
cert tool giving SecKeychainItemImport write permissions error

### ISSUE THREAD

**Issue by doapp-ryanp** [fastlane/fastlane#6083]
fastlane 1.102.0
cert 1.4.2

Running `cert` in Jenkins. Jenkins running as the single OSX login user.

`cert` output:

```
+---------------+-------------------------------------------------------+
|                        [32mSummary for cert 1.4.2[0m                         |
+---------------+-------------------------------------------------------+
| team_id       | THETEAMID                                            |
| username      | ourusername                             |
| development   | false                                                 |
| force         | false                                                 |
| keychain_path | /Users/ouruser/Library/Keychains/login.keychain |
+---------------+-------------------------------------------------------+

[13:57:23]: Starting login with user '...'
[13:57:26]: Successfully logged in

2016-09-12 13:57:30,044 ERROR security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1062  100  1062    0     0   1552      0 --:--:-- --:--:-- --:--:--  1554
security: SecKeychainItemImport: write permissions error
[31m
[!] Could not install WWDR certificate[0m

2016-09-12 13:57:30,045 ERROR Could not determine which signing id to use
2016-09-12 13:57:30,045 ERROR Existing ids: []
2016-09-12 13:57:30,045 ERROR New ids: []
2016-09-12 13:57:30,045 ERROR Exiting abnormally Cannot determine which signing id to use
Traceback (most recent call last):
  File "./builder.py", line 159, in main
    build_platform.configure()
  File "/Users/ouruser/jenkins-home/workspace/MLN-Production-iTunes/mln/bld/IOSBuildPlatform.py", line 175, in configure
    self.establish_signing_identity()
  File "/Users/ouruser/jenkins-home/workspace/MLN-Production-iTunes/mln/bld/IOSBuildPlatform.py", line 881, in establish_signing_identity
    signing_identity_cert_id, existed = self.create_if_necessary_signing_id(self.temp_dir)
  File "/Users/ouruser/jenkins-home/workspace/MLN-Production-iTunes/mln/bld/IOSBuildPlatform.py", line 630, in create_if_necessary_signing_id
    raise KnownCertificateException("Cannot determine which signing id to use")
KnownCertificateException: Cannot determine which signing id to use
```

perms are correct:

```
ls -al /Users/ouruser/Library/Keychains/login.keychain
-rw-r--r--@ 1 ouruser  staff  357720 Sep 12 13:55 /Users/ouruser/Library/Keychains/login.keychain
```

Any idea what may be going on here?

**Comment by doapp-ryanp** [comment]
Closing, didnt have updated WWDR

**Comment by TKBurner** [comment]
@doapp-ryanp Thanks for letting us know. So glad you got up and running!
