### ISSUE TITLE
Support for App-Specific Password or something.

### ISSUE THREAD

**Issue by bwdowikowski** [fastlane/fastlane#6095]
### New Issue Checklist
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] Updated fastlane to the latest version
### Issue Description

I have two-factor authorization on my appleID and I'm trying to work with xcode server and fastlane. 
So as post-trigger I've setted lane that goes throu cert,sigh,gym and eventually crashlytics. I'm also setting enviroment variable FASTLANE_PASSWORD.  But since bot is starting this script then I can't type 6-digit code every time, that would be pointless also I would rather keep two-factor authorization. The solution should be App-Specific password, but they also not working. After contacting Apple they say that this password would work only with third-party application but with they sites will not work.  So is there a propper solution for that kind of situation?
### Log with main password

```
#!/bin/sh

export FASTLANE_PASSWORD=MASTER_PASSWORD

cd "$XCS_SOURCE_DIR/czyPojade"
/usr/local/bin/fastlane ios devBot

[14:09:31]: [32m-------------------------------------------------[0m
[14:09:31]: [32m--- Step: Verifying required fastlane version ---[0m
[14:09:31]: [32m-------------------------------------------------[0m
[14:09:31]: fastlane version valid
[14:09:31]: [32m------------------------------[0m
[14:09:31]: [32m--- Step: default_platform ---[0m
[14:09:31]: [32m------------------------------[0m
[14:09:31]: [32mDriving the lane 'ios devBot' 🚀[0m
[14:09:31]: [32m----------------------------------[0m
[14:09:31]: [32m--- Step: set_info_plist_value ---[0m
[14:09:31]: [32m----------------------------------[0m
[14:09:31]: [32m------------------[0m
[14:09:31]: [32m--- Step: cert ---[0m
[14:09:31]: [32m------------------[0m

+---------------+--------------------------------------------------+
|                      [32mSummary for cert 1.4.1[0m                      |
+---------------+--------------------------------------------------+
| username      | blazej.wdowikowski@best-bw.pl                    |
| development   | true                                             |
| force         | false                                            |
| team_id       | B799ALMBWW                                       |
| keychain_path | /var/_xcsbuildd/Library/Keychains/login.keychain |
+---------------+--------------------------------------------------+

[14:09:31]: Starting login with user 'blazej.wdowikowski@best-bw.pl'
Two Factor Authentication for account 'blazej.wdowikowski@best-bw.pl' is enabled
Please enter the 6 digit code: 
[32m#######################################################################[0m
[32m# cert 1.4.2 is available. You are on 1.4.1.[0m
[32m# It is recommended to use the latest version.[0m
[32m# Update using 'sudo gem update cert'.[0m
[32m#######################################################################[0m

[32m1.4.2 Improvements[0m
* Update fastlane_core and spaceship dependencies (#5943)
[32m
Update using 'sudo gem update cert'[0m
[14:09:36]: [33m[33mVariable Dump:[0m[0m
[14:09:36]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios devBot"}
[14:09:36]: [31mundefined method `strip' for nil:NilClass[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | set_info_plist_value                | 0           |
| 4    | [31mcert[0m                                | 4           |
+------+-------------------------------------+-------------+

[14:09:36]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mPilot tool is crashing with undefined method 'strip' for nil:NilClass (NoMethodError)[0m
   https://github.com/fastlane/fastlane/issues/3238 [[31mopen[0m] 0 💬
   15 hours ago

➡️  [33mProduce: undefined method `[]=' for nil:NilClass[0m
   https://github.com/fastlane/fastlane/issues/5875 [[32mclosed[0m] 6 💬
   3 weeks ago

➡️  [33mxcexport: `export_options_to_plist': [!] undefined method `[]' for nil:NilClass (NoMethodError)[0m
   https://github.com/fastlane/fastlane/issues/5571 [[32mclosed[0m] 6 💬
   4 weeks ago

and 14 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60strip'%20for%20nil&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline/question.rb:413:in `remove_whitespace': [31m[!] undefined method `strip' for nil:NilClass[0m (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:873:in `get_line'
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:891:in `get_response'
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/two_step_client.rb:53:in `handle_two_factor'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/two_step_client.rb:40:in `handle_two_step'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:297:in `send_shared_login_request'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:369:in `do_login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:227:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:90:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/portal/spaceship.rb:22:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/portal/spaceship.rb:77:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/cert-1.4.1/lib/cert/runner.rb:17:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/cert-1.4.1/lib/cert/runner.rb:27:in `run'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/actions/cert.rb:19:in `run'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:175:in `block in execute_action'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `chdir'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `execute_action'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:140:in `method_missing'
    from Fastfile:44:in `block (2 levels) in parsing_binding'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:49:in `block in execute'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `chdir'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `execute'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.51.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:246:in `run'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:20:in `start'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
    from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `load'
    from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `<main>'

```
### Log with App-Specific password

```
#!/bin/sh

export FASTLANE_PASSWORD=APP_SPECIFIC_PASSWORD

cd "$XCS_SOURCE_DIR/czyPojade"
/usr/local/bin/fastlane ios devBot

[14:15:32]: [32m-------------------------------------------------[0m
[14:15:32]: [32m--- Step: Verifying required fastlane version ---[0m
[14:15:32]: [32m-------------------------------------------------[0m
[14:15:32]: fastlane version valid
[14:15:32]: [32m------------------------------[0m
[14:15:32]: [32m--- Step: default_platform ---[0m
[14:15:32]: [32m------------------------------[0m
[14:15:32]: [32mDriving the lane 'ios devBot' 🚀[0m
[14:15:32]: [32m----------------------------------[0m
[14:15:32]: [32m--- Step: set_info_plist_value ---[0m
[14:15:32]: [32m----------------------------------[0m
[14:15:32]: [32m------------------[0m
[14:15:32]: [32m--- Step: cert ---[0m
[14:15:32]: [32m------------------[0m

+---------------+--------------------------------------------------+
|                      [32mSummary for cert 1.4.1[0m                      |
+---------------+--------------------------------------------------+
| username      | blazej.wdowikowski@best-bw.pl                    |
| development   | true                                             |
| force         | false                                            |
| team_id       | B799ALMBWW                                       |
| keychain_path | /var/_xcsbuildd/Library/Keychains/login.keychain |
+---------------+--------------------------------------------------+

[14:15:32]: Starting login with user 'blazej.wdowikowski@best-bw.pl'
[31mThe login credentials for 'blazej.wdowikowski@best-bw.pl' seem to be wrong[0m
Do you want to re-enter your password? (y/n)

[32m#######################################################################[0m
[32m# cert 1.4.2 is available. You are on 1.4.1.[0m
[32m# It is recommended to use the latest version.[0m
[32m# Update using 'sudo gem update cert'.[0m
[32m#######################################################################[0m

[32m1.4.2 Improvements[0m
* Update fastlane_core and spaceship dependencies (#5943)
[32m
Update using 'sudo gem update cert'[0m
[14:15:35]: [33m[33mVariable Dump:[0m[0m
[14:15:35]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios devBot"}
[14:15:35]: [31mundefined method `chr' for nil:NilClass[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | set_info_plist_value                | 0           |
| 4    | [31mcert[0m                                | 2           |
+------+-------------------------------------+-------------+

[14:15:35]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mFastlane still use old Apple account instead of new Apple Account [0m
   https://github.com/fastlane/fastlane/issues/5400 [[32mclosed[0m] 4 💬
   2 weeks ago

➡️  [33mPEM doesn't recognise FASTLANE_PASSWORD through Ansible[0m
   https://github.com/fastlane/fastlane/issues/4916 [[32mclosed[0m] 2 💬
   01 Jun 2016

➡️  [33mJenkins... Password (for my_email_address): stty: stdin isn't a terminal[0m
   https://github.com/fastlane/fastlane/issues/2238 [[32mclosed[0m] 23 💬
   07 Jun 2016

and 1 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60chr'%20for%20nil&type=Issues&utf8=✓
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
/Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:961:in `get_response': [31m[!] undefined method `chr' for nil:NilClass[0m (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:227:in `agree'
    from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.16.0/lib/credentials_manager/account_manager.rb:39:in `invalid_credentials'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:231:in `rescue in login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:226:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:90:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/portal/spaceship.rb:22:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/spaceship-0.32.0/lib/spaceship/portal/spaceship.rb:77:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/cert-1.4.1/lib/cert/runner.rb:17:in `login'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/cert-1.4.1/lib/cert/runner.rb:27:in `run'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/actions/cert.rb:19:in `run'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:175:in `block in execute_action'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `chdir'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `execute_action'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:140:in `method_missing'
    from Fastfile:44:in `block (2 levels) in parsing_binding'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:49:in `block in execute'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `chdir'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `execute'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.51.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:246:in `run'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:20:in `start'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
    from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
    from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `load'
    from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
default_platform :ios

platform :ios do
  before_all do    
  end

  desc "Runs all the tests"
  lane :test do
    cocoapods
    scan(
      scheme: "czyPojade"
    )
  end

  desc "Submit a new Beta Build to Fabric"
  desc "This will also make sure the profile is up to date"
  lane :devBot do

    plistFile = "./czyPojade/Info.plist"
    buildNumber = Time.new.strftime("%Y%m%d%H%M")
    set_info_plist_value(
      path: plistFile,
      key: 'CFBundleVersion',
      value:  buildNumber
    )

    cert(
      username:"blazej.wdowikowski@best-bw.pl",
      output_path: "./fastlane/cert",
      development: true
    )
    sigh(
      output_path: "./fastlane/sigh",
      provisioning_name: "CzyPojade",
      development: true,
      ignore_profiles_with_different_name: true
    )
    gym(
      output_directory: "./fastlane/gym",
      scheme: "czyPojade"
    )
    crashlytics(
      api_token: TOKEN,
      build_secret: SECRET,
      groups: "beta",
      notes_path: "./fastlane/releaseNotes"
    )

  end

  desc "Screenshot" 
  lane :screenshot do
    snapshot
  end

  desc "Deploy a new version to the App Store"
  lane :prod do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
### Environment

fastlane version (run `fastlane -v`): 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? 
No

**Comment by Dudi00** [comment]
No but I will and be back with feedback 👍

**Comment by Dudi00** [comment]
Ok I did read it and there is no word about logging in but I've changed cert and sigh to match :)

But back to issue, are there other solutions than remove two-factor authorization and put apple id password to enviroment?

**Comment by TKBurner** [comment]
@Dudi00 Is your developer account in your login keychain?

**Comment by antgly** [comment]
Same issue here as @Dudi00. Using two factor auth because of the new Sierra Apple Watch Mac unlock feature requiring it to be on.

**Comment by Dudi00** [comment]
@TKBurner Yes it is

**Comment by Dudi00** [comment]
@antgly So at this moment you did remove two factor auth?

**Comment by antgly** [comment]
I have. I'll try again this weekend.

**Comment by TKBurner** [comment]
@Dudi00 @antgly Just wanted you to know I reached out to the core team about this today. I'll update this thread once I have more info. Thanks!

**Comment by antgly** [comment]
Thanks @TKBurner! :)

**Comment by TKBurner** [comment]
Hi @antgly @Dudi00. I had a chance to talk with Felix about this. Can you follow the steps here and see if that works for you https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification?

**Comment by akaralar** [comment]
@TKBurner I managed to get this working but I usually don't receive any code to my devices, and on Apple login pages there is an option to send an SMS instead if no code is received. Here is a [screenshot](https://dl.dropboxusercontent.com/spa/6d4j003yz96ozkz/2nq5f2__.png). But the command line doesn't give that option, just expects a 6 digit code. Is there any possibility that if we don't receive the code while the cli is it's waiting for it, we have options other than entering the code, such as resend code and send with sms (those in the screenshot)?

**Comment by TKBurner** [comment]
@akaralar Thanks for following up. Can you let me know the sequence of events that triggers this for you? Right now we don't have a mechanism to resend in place.

Thanks!

**Comment by JohannesDeml** [comment]
Not quite sure if this issue is still relevant. For me it was necessary to create an app -specific password in order to use e.g. pilot.

You can create the password here:
https://appleid.apple.com/account/manage
![bildschirmfoto 2016-11-03 um 13 02 55](https://cloud.githubusercontent.com/assets/4518980/19965340/d8f17c36-a1c6-11e6-9f2c-957e9b0b267d.png)

Thanks for supporting the process even with two-factor authentication. I got some really helpful error messages.

**Comment by TKBurner** [comment]
@JohannesDeml Thanks for letting me know that it worked. So once you input the app specific password it was stored to your keychain or did you set it with an ENV?

**Comment by akaralar** [comment]
@TKBurner I found out that my problem was related to apple 2fa as well, not bitbucket as I have stated previously. I resolved it by going through the spaceship 2 step verification part. Thanks!

**Comment by JohannesDeml** [comment]
@akaralar I can approve, the problem occurred to me as well, because of 2fa for the apple account.

@TKBurner I guess it was stored in my keychain, I didn't really have to do anything other than enter the password once I was prompted to do so. Really awesome experience. 👍

**Comment by fabware** [comment]
Same issue here, 2FA enabled.

Only I need to know is how to input  app specific password,  frustrating.

**Comment by JohannesDeml** [comment]
@fabware I had to fill it out once I ran pilot. It was a simple prompt in the commandline, nothing special to do here.

**Comment by TKBurner** [comment]
@fabware Did you get up and running? You should just enter it when prompted for your password in pilot.

**Comment by fabware** [comment]
@JohannesDeml @TKBurner Yes, I got it running JUST ENTER THE PASSWORD after enable app specific password in appleid.apple.com. It rock and running, thank you guys for such great product.

This information comes too pricy, after poke around with several obsolete fastlane-old issues which circularly linked each other, and after blindly following spaceship instructions, and finally accidentally get it work by another try.

It would be nice to have it noted somewhere in the docs, messy issues isn't the right place for it.

**Comment by TKBurner** [comment]
@fabware Thanks for following up. Glad to hear you got up and running 👍

**Comment by KrauseFx** [comment]
Check out the new 2 factor docs: https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth

**Comment by KrauseFx** [comment]
Hey everyone, _fastlane_ now fully supports both two-factor and two-step verification 👋 

Please make sure to update to the latest version of _fastlane_ by running 

```
fastlane update_fastlane
```

If you use a `Gemfile`, just run `bundle update`

### On your computer 🚀
To use _fastlane_ with two-factor, just run _fastlane_ as you usually would. You'll be asked for the verification method, and a 4 or 6 digits pin. Everything will just work out of the box 📦 

### On your continuous integration system 💻 
Check out the [official two-factor docs](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth) for more information on how to setup two-step on CI system. You'll have to authenticate on your local machine to get a session cookie, which you then transfer to your CI.

----

If you have any issues setting this up, please submit [a new issue](https://github.com/fastlane/fastlane/issues/new) so we can help you get up and running 👍

**Comment by fabware** [comment]
Great, I thought I was the only one have two-factor verification problem.

Will try it later.
