### ISSUE TITLE
Fastlane does not support fastlane directory to be a symlink

### ISSUE THREAD

**Issue by lietu** [fastlane/fastlane#612]
If you run `fastlane` in a location where `fastlane/Fastfile` is available but the `fastlane` directory is a symbolic link (`ln -s ~/fastlane .` or such) you get an error:

```
$ fastlane ios beta
[14:14:32]: -------------------------------------------------
[14:14:32]: --- Step: Verifying required fastlane version ---
[14:14:32]: -------------------------------------------------
[14:14:32]: fastlane version valid
[14:14:32]: ------------------------------
[14:14:32]: --- Step: default_platform ---
[14:14:32]: ------------------------------
[14:14:32]: Driving the lane 'ios beta' 🚀
[14:14:32]: -----------------
[14:14:32]: --- Step: gym ---
[14:14:32]: -----------------
[14:14:33]: Variable Dump:
[14:14:33]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
[14:14:33]: No project/workspace found in the current directory.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 0           |
+------+-------------------------------------+-------------+

[14:14:33]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.2.0/gems/gym-0.7.2/lib/gym/detect_values.rb:16:in `set_additional_default_values': No project/workspace found in the current directory. (RuntimeError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/gym-0.7.2/lib/gym.rb:24:in `config='
        from /usr/local/lib/ruby/gems/2.2.0/gems/gym-0.7.2/lib/gym/manager.rb:4:in `work'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/actions/gym.rb:20:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/runner.rb:128:in `block in execute_action'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/runner.rb:127:in `chdir'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/runner.rb:127:in `execute_action'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/fast_file.rb:134:in `method_missing'
        from (eval):31:in `block (3 levels) in parse'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/runner.rb:48:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/runner.rb:48:in `block in execute'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/runner.rb:46:in `chdir'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/runner.rb:46:in `execute'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/lib/fastlane/command_line_handler.rb:31:in `handle'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/bin/fastlane:36:in `block (2 levels) in run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/bin/fastlane:127:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.28.0/bin/fastlane:133:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'
```

If replacing `ln -s ~/fastlane .` with e.g. `cp -a ~/fastlane .` it works fine.

Tested on Max OS X 10.10.5.

**Comment by KrauseFx** [comment]
The error message is

```
[14:14:33]: No project/workspace found in the current directory.
```

Are you sure this has something to do with the symlink?

**Comment by jimjeffers** [comment]
Hey @KrauseFx I'm having the same issue. I am noticing some oddities. The possible culprit is that I am seeing this warning pop up in the log during gym: `/Users/jim/.rvm/gems/ruby-2.2.2/gems/credentials_manager-0.8.2/lib/credentials_manager/appfile_config.rb:31: warning: conflicting chdir during another chdir block`

```
[08:04:59]: -----------------
[08:04:59]: --- Step: gym ---
[08:04:59]: -----------------
/Users/jim/.rvm/gems/ruby-2.2.2/gems/credentials_manager-0.8.2/lib/credentials_manager/appfile_config.rb:31: warning: conflicting chdir during another chdir block
/Users/jim/.rvm/gems/ruby-2.2.2/gems/credentials_manager-0.8.2/lib/credentials_manager/appfile_config.rb:31: warning: conflicting chdir during another chdir block
[08:04:59]: Variable Dump:
[08:04:59]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"18", :SIGH_PROFILE_PATH=>"[redacted]", :SIGH_PROFILE_PATHS=>["[redacted]"], :SIGH_UDID=>"[redacted]", :SIGH_PROFILE_TYPE=>"app-store"}
[08:04:59]: No project/workspace found in the current directory.
```

**Comment by jimjeffers** [comment]
I should mention I'm using `fastlane 1.30.1` and XCode7 on the latest build of Yosemite. Haven't updated to El Capitan just yet.

**Comment by KrauseFx** [comment]
@jimjeffers 
I'm really sorry about this. Your issue seems to be caused by a release yesterday which had a race condition in [fastlane_core](https://github.com/fastlane/fastlane_core). Could you please update using `sudo gem update fastlane_core` and let me know if this fixes your issue?

**Comment by ohwutup** [comment]
closing this as there has been no recent activity @jimjeffers please reopen if you are still having issues! thanks! :sweet_potato:

**Comment by jimjeffers** [comment]
@ohwutup @KrauseFx Sorry for leaving you hanging but my issue was resolved by the more recent releases of fastlane after I posted about this issue. Thanks for the awesome progress you guys are making on the project.
