### ISSUE TITLE
Permission denied (publickey) when running match

### ISSUE THREAD

**Issue by WedgeSparda** [fastlane/fastlane#6122]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

When trying to run my lane I can't login to my private repository in **Bitbucket** in order to initiate all the process. Also I noticed that no username and password are added to my keychain but don't know why. 

The error i'm getting is this:

```
+-----------------------+--------------------------------------------------------+
|                            Summary for match 0.6.4                             |
+-----------------------+--------------------------------------------------------+
| verbose               | true                                                   |
| git_url               | git@bitbucket.org:************* |
| type                  | development                                            |
| username              | *****@******                                       |
| git_branch            | master                                                 |
| keychain_name         | login.keychain                                         |
| readonly              | false                                                  |
| team_id               | ZZNL45U6E6                                             |
| force                 | false                                                  |
| shallow_clone         | false                                                  |
| force_for_new_devices | false                                                  |
| skip_docs             | false                                                  |
+-----------------------+--------------------------------------------------------+

INFO [2016-09-14 17:11:39.82]: Cloning remote git repo...
INFO [2016-09-14 17:11:39.82]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@bitbucket.org:*************' '/var/folders/fb/p1tzyvn911x6w478q7gqd22w0000gn/T/d20160914-68997-1b2of1j'
INFO [2016-09-14 17:11:39.86]: ▸ Cloning into '/var/folders/fb/p1tzyvn911x6w478q7gqd22w0000gn/T/d20160914-68997-1b2of1j'...
INFO [2016-09-14 17:11:40.73]: ▸ Permission denied (publickey).
INFO [2016-09-14 17:11:40.73]: ▸ fatal: Could not read from remote repository.
INFO [2016-09-14 17:11:40.73]: ▸ Please make sure you have the correct access rights
INFO [2016-09-14 17:11:40.73]: ▸ and the repository exists.
Cloning into '/var/folders/fb/p1tzyvn911x6w478q7gqd22w0000gn/T/d20160914-68997-1b2of1j'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR [2016-09-14 17:11:40.73]: Exit status: 128
INFO [2016-09-14 17:11:40.73]: 🔒  Successfully encrypted certificates repo
/Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane_core-0.51.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Exit status: 128 (FastlaneCore::Interface::FastlaneError)
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane_core-0.51.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane_core-0.51.0/lib/fastlane_core/command_executor.rb:90:in `execute'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/match-0.6.4/lib/match/git_helper.rb:13:in `clone'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/match-0.6.4/lib/match/runner.rb:10:in `run'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/match-0.6.4/lib/match/commands_generator.rb:53:in `block (3 levels) in run'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane_core-0.51.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/match-0.6.4/lib/match/commands_generator.rb:119:in `run'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/match-0.6.4/lib/match/commands_generator.rb:12:in `start'
	from /Users/Wedge/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/match-0.6.4/bin/match:6:in `<top (required)>'
	from /Users/Wedge/.rbenv/versions/2.1.3/bin/match:23:in `load'
	from /Users/Wedge/.rbenv/versions/2.1.3/bin/match:23:in `<main>'
```

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  lane :send_crashlytics do
    ENV["APP_IDENTIFIER"] = "my.app.identifier"

    match(app_identifier: ENV["APP_IDENTIFIER"],
              git_branch: ENV["APP_IDENTIFIER"],
                    type: "development")
    gym(scheme: "My-Scheme")

    crashlytics(
        api_token: ENV["CRASHLYTICS_API_TOKEN"],
        build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
        groups: ["fixers"],
        notifications: true
      )
  end
```

### Environment

fastlane version (run `fastlane -v`): 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? 
No

**Comment by WedgeSparda** [comment]
BTW, I'm using XCode 8.

**Comment by TKBurner** [comment]
@WedgeSparda Are you using Sierra too by any chance? Can you try unlocking the keychain before running the rest of the commands? Do you have 2-Factor setup on Bitbucket?

**Comment by WedgeSparda** [comment]
> Are you using Sierra too by any chance?

No, still using El Capitan

> Can you try unlocking the keychain before running the rest of the commands?

I tried that but command is asking me for the path to the keychain file and don't know where is this file created.

> Do you have 2-Factor setup on Bitbucket?

No

**Comment by WedgeSparda** [comment]
Anyone can help with this? :(

**Comment by WedgeSparda** [comment]
So finally I figured out my problem.

I needed a SSH Key from Bitbucket in order to login to my repository. So i followed these steps https://confluence.atlassian.com/bitbucket/set-up-ssh-for-git-728138079.html and finally I managed to log in to my repository from match.

**Comment by TKBurner** [comment]
@WedgeSparda Awesome! So glad to hear you got up and running. Hope you have a great day!
