### ISSUE TITLE
Stdc++ library issue for installing fastlane on Fedora 24

### ISSUE THREAD

**Issue by hamid-rocket** [fastlane/fastlane#6172]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I cannot install fastlane on Fedora 24.
it seems it cannot find stdc++ even though I have already installed the library:

> sudo dnf install libstdc++
##### Complete output when running fastlane, including the stack trace and command used

> [sudo] gem install fastlane

```
Building native extensions.  This could take a while...
ERROR:  Error installing fastlane:
    ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20160918-17518-1hlk31p.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib64
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/$(RUBY_BASE_NAME)
    --with-static-libstdc++
    --without-static-libstdc++
    --with-stdc++lib
    --without-stdc++lib
/usr/share/ruby/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/share/ruby/mkmf.rb:541:in `try_link0'
    from /usr/share/ruby/mkmf.rb:556:in `try_link'
    from /usr/share/ruby/mkmf.rb:735:in `try_func'
    from /usr/share/ruby/mkmf.rb:966:in `block in have_library'
    from /usr/share/ruby/mkmf.rb:911:in `block in checking_for'
    from /usr/share/ruby/mkmf.rb:351:in `block (2 levels) in postpone'
    from /usr/share/ruby/mkmf.rb:321:in `open'
    from /usr/share/ruby/mkmf.rb:351:in `block in postpone'
    from /usr/share/ruby/mkmf.rb:321:in `open'
    from /usr/share/ruby/mkmf.rb:347:in `postpone'
    from /usr/share/ruby/mkmf.rb:910:in `checking_for'
    from /usr/share/ruby/mkmf.rb:961:in `have_library'
    from extconf.rb:6:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/share/gems/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /usr/local/lib64/gems/ruby/unf_ext-0.0.7.2/gem_make.out
```

**Comment by TKBurner** [comment]
@hamid-rocket Sorry for the delay in getting to this thread. What happens if you use RVM to manage your ruby versions? Thanks!
