### ISSUE TITLE
[produce] not make app in itunes connect

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#6234]
Hello. i cannot make app through produce. see log
if i make this actions by hand it is make very fast and all good. 
but if i make through produce it is SUCCESS make in dev center, and make an opportunity in ItunesConnect. But when run make app in ItunesConnect it is freeze, apps dont make in itunesconnect and i dont can make app in future with this bundle_id forever in itunecconnect and in future this app not show in account.
please help me
OS - macOS sierra 
XCODE 8
fastlane and plugins - last version on this moment

CONFIGURATION
```
		produce(
			username: 'login',
			app_identifier: bundle_id,
			app_name: name,
			language: 'Russian',
			app_version: "1.0",
			sku: sku,
			team_name: team_id
		)

```

LOG
```
[20:05:19]: ---------------------
[20:05:19]: --- Step: produce ---
[20:05:19]: ---------------------

+----------------+---------------------+
|      Summary for produce 1.2.0       |
+----------------+---------------------+
| username       | login    |
| app_identifier | bundle_id |
| app_name       | KZ7                 |
| language       | Russian             |
| app_version    | 1.0                 |
| sku            | kz_foodsoul_chain_7 |
| team_name      | team_id        |
| skip_itc       | false               |
| skip_devcenter | false               |
| team_id        | XXXXXX          |
+----------------+---------------------+

[20:05:27]: Creating new app 'KZ7' on the Apple Dev Center
[20:05:31]: Created app XXXXXXXXXX
[20:05:32]: Finished creating new app 'KZ7' on the Dev Center
[20:05:39]: Creating new app 'KZ7' on iTunes Connect
[20:05:56]: Waiting for the newly created application to be available on iTunes Connect...
[20:06:12]: Waiting for the newly created application to be available on iTunes Connect...
[20:06:44]: Waiting for the newly created application to be available on iTunes Connect...
[20:06:59]: Waiting for the newly created application to be available on iTunes Connect...
[20:07:12]: Waiting for the newly created application to be available on iTunes Connect...
[20:07:25]: Waiting for the newly created application to be available on iTunes Connect...
[20:07:36]: Waiting for the newly created application to be available on iTunes Connect...
[20:07:48]: Waiting for the newly created application to be available on iTunes Connect...
[20:08:01]: Waiting for the newly created application to be available on iTunes Connect...
[20:08:13]: Waiting for the newly created application to be available on iTunes Connect...
[20:08:24]: Waiting for the newly created application to be available on iTunes Connect...
[20:08:36]: Waiting for the newly created application to be available on iTunes Connect...
[20:08:49]: Waiting for the newly created application to be available on iTunes Connect...
[20:09:01]: Waiting for the newly created application to be available on iTunes Connect...
[20:09:12]: Waiting for the newly created application to be available on iTunes Connect...
[20:09:24]: Waiting for the newly created application to be available on iTunes Connect...
[20:09:35]: Waiting for the newly created application to be available on iTunes Connect...
[20:09:47]: Waiting for the newly created application to be available on iTunes Connect...
[20:09:59]: Waiting for the newly created application to be available on iTunes Connect...
[20:10:28]: Waiting for the newly created application to be available on iTunes Connect...
[20:10:39]: Waiting for the newly created application to be available on iTunes Connect...
[20:10:51]: Waiting for the newly created application to be available on iTunes Connect...
[20:11:03]: Waiting for the newly created application to be available on iTunes Connect...
[20:11:14]: Waiting for the newly created application to be available on iTunes Connect...
[20:11:26]: Waiting for the newly created application to be available on iTunes Connect...
[20:11:38]: Waiting for the newly created application to be available on iTunes Connect...
[20:11:50]: Waiting for the newly created application to be available on iTunes Connect...
[20:12:01]: Waiting for the newly created application to be available on iTunes Connect...
[20:12:22]: Waiting for the newly created application to be available on iTunes Connect...
[20:12:34]: Waiting for the newly created application to be available on iTunes Connect...
[20:12:45]: Waiting for the newly created application to be available on iTunes Connect...
[20:12:57]: Waiting for the newly created application to be available on iTunes Connect...
[20:13:23]: Waiting for the newly created application to be available on iTunes Connect...
[20:13:35]: Waiting for the newly created application to be available on iTunes Connect...
[20:13:47]: Waiting for the newly created application to be available on iTunes Connect...
[20:13:58]: Waiting for the newly created application to be available on iTunes Connect...
[20:14:10]: Waiting for the newly created application to be available on iTunes Connect...
[20:14:21]: Waiting for the newly created application to be available on iTunes Connect...
[20:14:33]: Waiting for the newly created application to be available on iTunes Connect...
[20:14:46]: Waiting for the newly created application to be available on iTunes Connect...
[20:14:58]: Waiting for the newly created application to be available on iTunes Connect...
[20:15:09]: Waiting for the newly created application to be available on iTunes Connect...
[20:15:21]: Waiting for the newly created application to be available on iTunes Connect...
[20:15:33]: Waiting for the newly created application to be available on iTunes Connect...
[20:15:46]: Waiting for the newly created application to be available on iTunes Connect...
[20:15:58]: Waiting for the newly created application to be available on iTunes Connect...
[20:16:10]: Waiting for the newly created application to be available on iTunes Connect...
[20:16:21]: Waiting for the newly created application to be available on iTunes Connect...
[20:16:33]: Waiting for the newly created application to be available on iTunes Connect...
[20:16:45]: Waiting for the newly created application to be available on iTunes Connect...
[20:17:02]: Waiting for the newly created application to be available on iTunes Connect...
[20:17:14]: Waiting for the newly created application to be available on iTunes Connect...
[20:17:25]: Waiting for the newly created application to be available on iTunes Connect...
[20:17:36]: Variable Dump:
[20:17:36]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios create"}
[20:17:36]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"}

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | rm -f '/Users/dmitriy_suharev/Documents/FoodSoul/Project/iOS_ | 0           |
| 4    | produce                                                       | 737         |
+------+---------------------------------------------------------------+-------------+

[20:17:36]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Accessing BUNDLE type of application fails in client.app_version
   https://github.com/fastlane/fastlane/issues/2020 [open] 0 💬
   a week ago

➡️  Deliver fails to create a new version in iTunes Connect for a Mac App
   https://github.com/fastlane/fastlane/issues/6152 [open] 0 💬
   4 days ago

➡️  Unexpected Error
   https://github.com/fastlane/fastlane/issues/3032 [closed] 2 💬
   08 Mar 2016

and 3 more at: https://github.com/fastlane/fastlane/search?q=%7B%22data%22=%3Enil,%20%22messages%22=%3E%7B%22warn%22=%3Enil,%20%22error%22=%3E[%22Unexpected%20Error%22],%20%22info%22=%3Enil%7D,%20%22statusCode%22=%3E%22ERROR%22%7D&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.33.0/lib/spaceship/client.rb:450:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.33.0/lib/spaceship/tunes/tunes_client.rb:195:in `applications'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.33.0/lib/spaceship/tunes/application.rb:56:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.33.0/lib/spaceship/tunes/application.rb:62:in `find'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:59:in `fetch_application'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:45:in `create_new_app'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/manager.rb:8:in `start_producing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/actions/produce.rb:19:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/actions/produce.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/actions/produce.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/runner.rb:186:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:179:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.103.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by GandjaFuzz** [comment]
i fix this

**Comment by TKBurner** [comment]
@GandjaFuzz Awesome! Thanks so much for using our tools 👍

**Comment by convitza** [comment]
Hi @GandjaFuzz , how do you fix this error? could you please share?
Thanks

**Comment by gregk8288** [comment]
@GandjaFuzz Could you share with us how you fixed this error. I am having the exactly same issue.

**Comment by GandjaFuzz** [comment]
it is problem with ItunesConnect API. 
Try:
Restart Mac
Restart Router(Connection to Internet)
Increase the number of loops in deliver
On average, the data appear in 4 hours. But that rarely happens

**Comment by pedro380085** [comment]
This was the solution for me too, waited until the next day and voilá, iTunes Connect is working again.
