### ISSUE TITLE
pilot upload failure undefined method `builds' for nil:NilClass

### ISSUE THREAD

**Issue by geoHeil** [fastlane/fastlane#6267]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Upload to testflight is failing
##### Complete output when running fastlane, including the stack trace and command used

undefined method `builds' for nil:NilClass
```
Successfully uploaded the new binary to iTunes Connect
INFO [2016-09-23 14:14:09.23]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
INFO [2016-09-23 14:14:09.23]: Waiting for iTunes Connect to process the new build
INFO [2016-09-23 14:14:41.48]: Waiting for iTunes Connect to finish processing the new build (0.0.24 - 0.0.24)
INFO [2016-09-23 14:15:13.21]: Waiting for iTunes Connect to finish processing the new build (0.0.24 - 0.0.24)
WARN [2016-09-23 14:15:46.33]: Variable Dump:
INFO [2016-09-23 14:15:46.33]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy", :CORDOVA_APP_ID=>"my.app.id", :SIGH_PROFILE_TYPE=>"app-store", :CORDOVA_APP_NAME=>"app", :IPA_OUTPUT_PATH=>"app.ipa", :DSYM_OUTPUT_PATH=>"path.app.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"app 2016-09-23 14.13.15.xcarchive"}
ERROR [2016-09-23 14:15:46.33]: undefined method `builds' for nil:NilClass
INFO [2016-09-23 14:15:46.33]:

/usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.10.0/lib/pilot/build_manager.rb:142:in `wait_for_processing_build': [!] undefined method `builds' for nil:NilClass (NoMethodError)
       	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.10.0/lib/pilot/build_manager.rb:34:in `upload'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/actions/pilot.rb:18:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:187:in `block in execute_action'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `chdir'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `execute_action'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/fast_file.rb:140:in `method_missing'
       	from Fastfile:191:in `block (2 levels) in parsing_binding'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/lane.rb:33:in `call'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:165:in `try_switch_to_lane'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:120:in `trigger_action_by_name'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/fast_file.rb:140:in `method_missing'
       	from Fastfile:142:in `block (2 levels) in parsing_binding'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/lane.rb:33:in `call'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:49:in `block in execute'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `chdir'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `execute'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/command_line_handler.rb:30:in `handle'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:246:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:20:in `start'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
       	from /usr/local/bin/fastlane:22:in `load'
       	from /usr/local/bin/fastlane:22:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
require 'yaml'
require 'ostruct'

fastlane_version "1.68.0"

default_platform :ios

# Load configuration
config_file = File.expand_path("config.yml")
begin
  config = YAML.load(open(config_file))
rescue
  Helper.log.error "Config file not found"
  Helper.log.error "Please add a config.yml file in your fastlane directory"
  Helper.log.error "Check http://github.com/platanus/fastlane-base for information"
  Helper.log.error "about the structure of the config file"
  exit 1
end

config = OpenStruct.new(config)
if config.stages.nil?
  Helper.log.error "Required key missing (stages)"
  Helper.log.error "Please add a stages key with the stages you want to define"
  exit 1
end

# Public methods

def cordova_project_path
  "platforms/ios/#{app_name_sanitized}.xcodeproj"
end

# http://stackoverflow.com/questions/1939333/how-to-make-a-ruby-string-safe-for-a-filesystem
def app_name_sanitized
  cordova_get_app_name.gsub(/[^0-9A-Za-z.\-]/, '_')
end

def cordova_plist_path
  "#{app_name_sanitized}/#{app_name_sanitized}-Info.plist"
end

def app_name_for(environment)
  if environment == "production"
    cordova_get_app_name
  else
    "#{cordova_get_app_name} - #{environment.capitalize}"
  end
end

def app_id_for(environment)
  if environment == "production"
    cordova_get_app_id
  else
    "#{cordova_get_app_id}.#{environment}"
  end
end

# Lanes
platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # increment_build_number

    # xctool # run the tests of your app
  end

  desc "Create app ids for each of the stages"
  lane :create do |options|
    config.stages.each_key do |stage|
      stage_config = config.stages[stage]
      app_name = app_name_for(stage)
      app_id = app_id_for(stage)
      produce(
        username: stage_config["apple_id"],
        team_id: stage_config["team_id"],
        app_identifier: app_id,
        app_name: app_name
      )
    end
  end

  desc "Create necessary profiles and certificates"
  lane :certs do
    config.stages.each_key do |stage|
      app_id = app_id_for(stage)
      stage_config = config.stages[stage]

      %w(appstore development).each do |sign_type|
        match(
          username: stage_config["apple_id"],
          team_id: stage_config["team_id"],
          app_identifier: app_id,
          git_url: stage_config["certificates_url"],
          type: sign_type
        )
      end
    end
  end

  desc "READ necessary profiles and certificates"
    lane :certsRead do
      config.stages.each_key do |stage|
        app_id = app_id_for(stage)
        stage_config = config.stages[stage]

        %w(appstore development).each do |sign_type|
          match(
            username: stage_config["apple_id"],
            team_id: stage_config["team_id"],
            app_identifier: app_id,
            git_url: stage_config["certificates_url"],
            type: sign_type,
            readonly: true
          )
        end
      end
    end

  desc "Enable app services services"
  desc "Params:"
  desc "[enable|disable]:[services,...] to enable or disable a service"
  lane :service do |options|
    config.stages.each_key do |stage|
      options[:stage] = stage
      update_services(options)

      services_to_enable = options[:enable];

      if services_to_enable
        push_certs(options) if options[:enable].match /push/
      end
    end
  end

  desc "Upload only app to testflight or appstore"
  desc "Params:"
  desc "to: [apstore, testflight] Deployment destination"
  desc "stage: Application build environment"
  lane :deploy do |options|
    if options[:to] == 'testflight'
      do_testflight(options)
    elsif options[:to] == 'appstore'
      do_appstore(options)
    end
  end

  desc "Deploy as well to testflight or appstore"
    desc "Params:"
    desc "to: [apstore, testflight] Deployment destination"
    desc "stage: Application build environment"
    lane :deployToTesters do |options|
      if options[:to] == 'testflight'
        do_testflightDeploy(options)
      elsif options[:to] == 'appstore'
        do_appstore(options)
      end
    end

  private_lane :build do |options|

    stage = options[:stage]
    stage_config = config.stages[stage]
    app_id = app_id_for(stage)

    match(
      username: stage_config["apple_id"],
      team_id: stage_config["team_id"],
      app_identifier: app_id,
      git_url: stage_config["certificates_url"],
      type: "appstore",
      readonly: true
    )

    sh "cordova prepare --env=#{stage}"

    update_app_identifier(
      xcodeproj: cordova_project_path,
      plist_path: cordova_plist_path,
      app_identifier: app_id
    )

    recreate_schemes(
      project: cordova_project_path
    )

    gym(
      verbose: true,
      project: cordova_project_path,
      scheme: app_name_sanitized,
      xcconfig: "platforms/ios/cordova/build-release.xcconfig"
    )
  end

  desc "Upload to testflight"
  private_lane :do_testflight do |options|
    stage = options[:stage]
    stage_config = config.stages[stage]
    app_id = app_id_for(stage)

    build(options)

    pilot(
      username: stage_config["apple_id"],
      team_id: stage_config["team_id"],
      app_identifier: app_id,
      skip_submission: true
    )
  end

  desc "Upload to testflight and deploy to testers"
    private_lane :do_testflightDeploy do |options|
      stage = options[:stage]
      stage_config = config.stages[stage]
      app_id = app_id_for(stage)

      build(options)

      pilot(
        username: stage_config["apple_id"],
        team_id: stage_config["team_id"],
        app_identifier: app_id,
        skip_submission: false
      )
    end

  desc "Upload the appstore"
  private_lane :do_appstore do |options|
    stage = options[:stage]
    stage_config = config.stages[stage]
    app_id = app_id_for(stage)

    build(options)

    deliver(
      username: stage_config["apple_id"],
      team_id: stage_config["team_id"],
      app_identifier: app_id,
      force: true,
      submit_for_review: false,
      skip_metadata: true,
      skip_screenshots: true
    )
  end

  desc "Update services using produce"
  private_lane :update_services do |options|
    stage = options[:stage]
    stage_config = config.stages[stage]
    app_id = app_id_for(stage)

    %w(enable disable).each do |state|
      next unless services = options[state.to_sym]

      produce_service(
        action: state,
        app_identifier: app_id,
        username: stage_config['apple_id'],
        team_id: stage_config['team_id'],
        services: services.split(",")
      )
    end
  end

  desc "Runs produce cli services to enable and disable"
  private_lane :produce_service do |options|
    command = []
    command << "produce #{options[:action]}_services"
    command << "--app_identifier #{options[:app_identifier]}"
    command << "--username #{options[:username]}"
    command << "--team_id #{options[:team_id]}"
    options[:services].each do |service|
      command << "--#{service}"
    end
    sh command.join(' ')
  end

  desc "Create and upload the push certificates"
  private_lane :push_certs do |options|
    stage = options[:stage]
    stage_config = config.stages[stage]
    app_id = app_id_for(stage)
    sandbox = stage != 'production'
    development = (stage =~ /staging|production/).nil?

    pem(
      app_identifier: app_id,
      username: stage_config['apple_id'],
      team_id: stage_config['team_id'],
      development: development,
      generate_p12: false,
      save_private_key: false,
      output_path: "./fastlane",
      new_profile: proc do |profile_path|
        require 'openssl'
        require 'aws-sdk'

        pem = File.read(profile_path)
        pkey = OpenSSL::PKey::RSA.new(pem)
        cert = OpenSSL::X509::Certificate.new(pem)

        Aws.config[:region] = 'us-east-1'
        sns = Aws::SNS::Client.new

        resp = sns.create_platform_application({
          name: app_id,
          platform: sandbox ? 'APNS_SANDBOX' : 'APNS',
          attributes: { # required
            'PlatformCredential' => pkey.to_s,
            'PlatformPrincipal' => cert.to_s
          }
        })

        puts "------------------ A new Application was created in AWS SNS ------------------ ".yellow
        puts "Application Name: #{app_id}".yellow
        puts "Application ARN: #{resp.platform_application_arn}".yellow
      end
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  desc "Deploy a beta to the Google Play"
  lane :deployBeta do
    # TODO make this nice and dynamic + load as well from config.yml
    #config.json_key_file
    #config.package_name

    sh 'supply -p at.faktorzehn.eule -a alpha --json_key googlePlay_e93f68bb7e4c.json --verbose -b ../Eule.apk'
    --apk
    supply -p
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end




# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
```

### Environment

fastlane version (run `fastlane -v`):
1.104.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by TKBurner** [comment]
Hi @geoHeil Thanks for reaching out. Does the build appear on iTunes connect after this? Thanks!

**Comment by bimawa** [comment]
@geoHeil  catch same issue, after receive mail from apple
>This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

add this key, and all work done.

**Comment by richlong** [comment]
Hi, I was getting the same error but also got an email from Apple but mine was related to NSCalendarsUsageDescription in the plist. I've added this and successfully submitted to TestFlight.

**Comment by TKBurner** [comment]
@geoHeil Did you get up and running? Thanks!

**Comment by geoHeil** [comment]
@TKBurner unfortunately it did not show up. I got an E-Mail from Apple only when submitting via XCode

**Comment by geoHeil** [comment]
I think I found the cause - cannot finally confirm it yet: 
CAMERA_USAGE_DESCRIPTION in cordova.xml is not correctly / not at all transferred to the info.plist

**Comment by geoHeil** [comment]
somehow the web view is not updated from the GitHub e-mails.
regarding the strange / long string: according to https://github.com/apache/cordova-plugin-camera NSCameraUsageDescription is correct.

The problem for me was some caching issues -> I still got the old plugin.

**Comment by geoHeil** [comment]
Yes. But not on all computers see the other issue with the wwdr
certificate.
Todd Burner <notifications@github.com> schrieb am Di. 27. Sep. 2016 um
22:42:

**Comment by TKBurner** [comment]
@geoHeil Glad to hear you got up and running!Let me know if you run into any more issues.
