### ISSUE TITLE
Error detecting currently used Xcode installation

### ISSUE THREAD

**Issue by rodriguv** [fastlane/fastlane#6275]
### Issue Description

I get this error message during the gym step "Error detecting currently used Xcode installation." I noticed the xcode_path in fastlane might be adding an extra "/" that interrupts finding the path.

My DEVELOPER_DIR doesn't seem to be the issue:

C02JV7HYDKQ1:[DIRECTORY] rodriguv$ echo $DEVELOPER_DIR
/Applications/Xcode8.app/Contents/Developer/Contents/Developer
##### Complete output when running fastlane, including the stack trace and command used

```
▸ Check Dependencies
** ARCHIVE FAILED **


The following build commands failed:
Check dependencies
(1 failure)
[14:09:39]: Exit status: 65
[14:09:39]: Variable Dump:
[14:09:39]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"nickplay_international_dev_enterprise", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios enterprise", :BUILD_NUMBER=>"There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings."}
[14:09:39]: Error building the application - see the log above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | opt_out_usage                       | 0           |
| 3    | default_platform                    | 0           |
| 4    | Switch to ios build lane            | 0           |
| 5    | Switch to ios env_vars lane         | 0           |
| 6    | Switch to ios prebuild lane         | 0           |
| 7    | xcode_select                        | 0           |
| 8    | increment_build_number              | 1           |
| 9    | update_plist_build_number           | 0           |
| 10   | modify_build_settings_key_value     | 2           |
| 11   | update_app_identifier               | 0           |
| 12   | unlock_keychain                     | 0           |
| 13   | update_project_provisioning         | 1           |
| 14   | gym                                 | 116         |
+------+-------------------------------------+-------------+

[14:09:39]: fastlane finished with errors

[!] Error building the application - see the log above
```

When I use "gym --verbose", i get this error message:

```
C02JV7HYDKQ1:[DIRECTORY] rodriguv$ gym --verbose
sh: /Applications/Xcode8.app/Contents/Developer/Contents/Developer//usr/bin/xcodebuild: No such file or directory
ERROR [2016-09-23 14:09:48.12]: undefined method `split' for nil:NilClass
ERROR [2016-09-23 14:09:48.12]: Error detecting currently used Xcode installation
/Users/rodriguv/.rvm/gems/ruby-2.1.5@global/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Unable to locate Xcode. Please make sure to have Xcode installed on your machine (FastlaneCore::Interface::FastlaneError)
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5@global/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/gems/gym-1.10.0/lib/gym/xcode.rb:14:in `pre_7?'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/gems/gym-1.10.0/lib/gym/detect_values.rb:22:in `set_additional_default_values'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/gems/gym-1.10.0/lib/gym.rb:26:in `config='
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/gems/gym-1.10.0/lib/gym/manager.rb:4:in `work'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/gems/gym-1.10.0/lib/gym/commands_generator.rb:42:in `block (2 levels) in run'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5@global/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/gems/gym-1.10.0/lib/gym/commands_generator.rb:61:in `run'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/gems/gym-1.10.0/lib/gym/commands_generator.rb:15:in `start'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/gems/gym-1.10.0/bin/gym:6:in `<top (required)>'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/bin/gym:23:in `load'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/bin/gym:23:in `<main>'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /Users/rodriguv/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
gym(
      scheme: scheme,
      configuration: configuration,
      clean: true,
      include_bitcode: false,
      workspace: ENV["APP_WORKSPACE"],
      output_directory: "./output/",
      output_name: ipa_name,
      codesigning_identity: identity,
      export_method: export_method,
      provisioning_profile_path: profile_path,
      use_legacy_build_api: ENV["LEGACY_BUILD_API"],
      xcargs: ENV["XCARGS"]
    )
```
### Environment

fastlane version (run `fastlane -v`):
1.104.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Yes
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Yes

**Comment by rodriguv** [comment]
not code signing related.

**Comment by rodriguv** [comment]
In the fastlane/fastlane_core/lib/fastlane_core/helper.rb, does it add an extra "/"

```
 # @return the full path to the Xcode developer tools of the currently
    #  running system
    def self.xcode_path
      return "" if self.is_test? and !self.is_mac?
      `xcode-select -p`.delete("\n") + "/"
    end

    # @return The version of the currently used Xcode installation (e.g. "7.0")
    def self.xcode_version
      return @xcode_version if @xcode_version

      begin
        output = `DEVELOPER_DIR='' "#{xcode_path}/usr/bin/xcodebuild" -version`
        @xcode_version = output.split("\n").first.split(' ')[1]
```

**Comment by KrauseFx** [comment]
So by removing or adding the training `/` this issue would be fixed?

**Comment by rodriguv** [comment]
I might be wrong, but maybe?

**Comment by TKBurner** [comment]
@rodriguv Can you test this out? We'd love to see a PR from you!

**Comment by KrauseFx** [comment]
👍

**Comment by MichaelMagnoli** [comment]
I came across this exact error and this solution fixed my issue:
http://stackoverflow.com/a/17980786
