### ISSUE TITLE
Couldn't find newly created app on iTunes Connect - please check the website for more information

### ISSUE THREAD

**Issue by RaInvis** [fastlane/fastlane#6281]
/Users/RaInVis/.rvm/gems/ruby-2.3.0@global/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Couldn't find newly created app on iTunes Connect - please check the website for more information (FastlaneCore::Interface::FastlaneCrash)

The question makes me crash....who can help me ??  The question is appearing at creating app on itunes connect....I dont know how to solve it...

**Comment by TKBurner** [comment]
@RaInvis Thanks for reaching out. Can you please submit using the full issue template? Make sure you have your full input and output. Thanks!

**Comment by KrauseFx** [comment]
Could you also post a screenshot of the iTunes Connect page?

**Comment by igorstimoli** [comment]
I had the same error twice today
Here is the log output (just replaced some sensible data with ******

```
[11:12:01]: [32m---------------------[0m
[11:12:01]: [32m--- Step: produce ---[0m
[11:12:01]: [32m---------------------[0m

+----------------+---------------------------+
|         [32mSummary for produce 1.2.0[0m          |
+----------------+---------------------------+
| app_name       | ******            |
| language       | UK English                |
| app_version    | 1.0                       |
| sku            | ******                  |
| team_name      | ******               |
| username       | ******    |
| app_identifier | ****** |
| skip_itc       | false                     |
| skip_devcenter | false                     |
| team_id        | ******                |
+----------------+---------------------------+

[11:12:15]: Creating new app ****** on the Apple Dev Center
[11:12:20]: Created app ******
[11:12:22]: [32mFinished creating new app ****** on the Dev Center[0m
[11:12:26]: [32mCreating new app ****** on iTunes Connect[0m
[11:12:40]: Waiting for the newly created application to be available on iTunes Connect...
[11:12:51]: Waiting for the newly created application to be available on iTunes Connect...
[11:13:04]: Waiting for the newly created application to be available on iTunes Connect...
[11:13:15]: Waiting for the newly created application to be available on iTunes Connect...
[11:13:27]: Waiting for the newly created application to be available on iTunes Connect...
[11:13:39]: Waiting for the newly created application to be available on iTunes Connect...
[11:13:51]: Waiting for the newly created application to be available on iTunes Connect...
[11:14:02]: Waiting for the newly created application to be available on iTunes Connect...
[11:14:25]: Waiting for the newly created application to be available on iTunes Connect...
[11:14:37]: Waiting for the newly created application to be available on iTunes Connect...
[11:14:48]: Waiting for the newly created application to be available on iTunes Connect...
[11:15:01]: Waiting for the newly created application to be available on iTunes Connect...
[11:15:13]: Waiting for the newly created application to be available on iTunes Connect...
[11:15:29]: Waiting for the newly created application to be available on iTunes Connect...
[11:15:41]: Waiting for the newly created application to be available on iTunes Connect...
[11:15:53]: Waiting for the newly created application to be available on iTunes Connect...
[11:16:04]: Waiting for the newly created application to be available on iTunes Connect...
[11:16:16]: Waiting for the newly created application to be available on iTunes Connect...
[11:16:27]: Waiting for the newly created application to be available on iTunes Connect...
[11:16:39]: Waiting for the newly created application to be available on iTunes Connect...
[11:16:50]: Waiting for the newly created application to be available on iTunes Connect...
[11:17:02]: Waiting for the newly created application to be available on iTunes Connect...
[11:17:13]: Waiting for the newly created application to be available on iTunes Connect...
[11:17:25]: Waiting for the newly created application to be available on iTunes Connect...
[11:17:36]: Waiting for the newly created application to be available on iTunes Connect...
[11:17:47]: Waiting for the newly created application to be available on iTunes Connect...
[11:17:58]: Waiting for the newly created application to be available on iTunes Connect...
[11:18:10]: Waiting for the newly created application to be available on iTunes Connect...
[11:18:21]: Waiting for the newly created application to be available on iTunes Connect...
[11:18:33]: Waiting for the newly created application to be available on iTunes Connect...
[11:18:44]: Waiting for the newly created application to be available on iTunes Connect...
[11:18:56]: Waiting for the newly created application to be available on iTunes Connect...
[11:19:07]: Waiting for the newly created application to be available on iTunes Connect...
[11:19:19]: Waiting for the newly created application to be available on iTunes Connect...
[11:19:30]: Waiting for the newly created application to be available on iTunes Connect...
[11:19:42]: Waiting for the newly created application to be available on iTunes Connect...
[11:19:53]: Waiting for the newly created application to be available on iTunes Connect...
[11:20:04]: Waiting for the newly created application to be available on iTunes Connect...
[11:20:16]: Waiting for the newly created application to be available on iTunes Connect...
[11:20:28]: Waiting for the newly created application to be available on iTunes Connect...
[11:20:39]: Waiting for the newly created application to be available on iTunes Connect...
[11:20:51]: Waiting for the newly created application to be available on iTunes Connect...
[11:21:02]: Waiting for the newly created application to be available on iTunes Connect...
[11:21:14]: Waiting for the newly created application to be available on iTunes Connect...
[11:21:25]: Waiting for the newly created application to be available on iTunes Connect...
[11:21:37]: Waiting for the newly created application to be available on iTunes Connect...
[11:21:48]: Waiting for the newly created application to be available on iTunes Connect...
[11:22:00]: Waiting for the newly created application to be available on iTunes Connect...
[11:22:11]: Waiting for the newly created application to be available on iTunes Connect...
[11:22:23]: Waiting for the newly created application to be available on iTunes Connect...
[11:22:34]: Waiting for the newly created application to be available on iTunes Connect...
[11:22:46]: Waiting for the newly created application to be available on iTunes Connect...
[11:22:58]: Waiting for the newly created application to be available on iTunes Connect...
[11:23:09]: Waiting for the newly created application to be available on iTunes Connect...
[11:23:21]: Waiting for the newly created application to be available on iTunes Connect...
[11:23:33]: Waiting for the newly created application to be available on iTunes Connect...
[11:23:45]: Waiting for the newly created application to be available on iTunes Connect...
[11:23:57]: Waiting for the newly created application to be available on iTunes Connect...
[11:24:08]: Waiting for the newly created application to be available on iTunes Connect...
[11:24:21]: [33m[33mVariable Dump:[0m[0m
[11:24:21]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"deploy", :BUILD_NUMBER=>"There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings."}
[11:24:21]: [31mCouldn't find newly created app on iTunes Connect - please check the website for more information[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | team_id                             | 0           |
| 3    | increment_build_number              | 2           |
| 4    | [31mproduce[0m                             | 738         |
+------+-------------------------------------+-------------+

[11:24:21]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mCouldn't find newly created app on iTunes Connect - please check the website for more information[0m
   https://github.com/fastlane/fastlane/issues/6281 [[31mopen[0m] 2 💬
   a day ago

/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:132:in `crash!': [31m[!] Couldn't find newly created app on iTunes Connect - please check the website for more information[0m (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:39:in `create_new_app'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/itunes_connect.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/manager.rb:8:in `start_producing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/actions/produce.rb:19:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/actions/produce.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/actions/produce.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:39:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
```

**Comment by dral3x** [comment]
Happened also to me. It seems a bug of iTunes Connect. 
An hour later I checked manually and the app was created and editable.

It does not happens regularly so it's hard to detect.

**Comment by TKBurner** [comment]
@igorstimoli Did the app eventually appear on iTC? Thanks!

**Comment by igorstimoli** [comment]
@TKBurner Sorry for the big delay answering to this.
The app did appear after a while with not metadata in it
Btw I didn't get this error anymore

**Comment by TKBurner** [comment]
@igor-makarov Thanks! It sounds like it was related to processing time. Please do let me know if you run into this again!

**Comment by igor-makarov** [comment]
You meant @igorstimoli, @TKBurner...

**Comment by igorstimoli** [comment]
@TKBurner
Just to let you know that this issue didn't happen for a while now

**Comment by shirkan** [comment]
Had this error today:


+----------------+-----------------------------------------------------+
|                      Summary for produce 1.3.1                       |
+----------------+-----------------------------------------------------+
| username       | shtuvistudio@gmail.com                              |
| app_identifier | com.shtuvistudio.christmassurprisingbonuscasinoslot |
| app_name       | Christmas Surprising Bonus Casino Slot              |
| app_version    | 1.0                                                 |
| sku            | accslot_291116_54321                                |
| language       | English                                             |
| skip_itc       | false                                               |
| skip_devcenter | false                                               |
+----------------+-----------------------------------------------------+

[13:04:37]: Creating new app 'Christmas Surprising Bonus Casino Slot' on the Apple Dev Center
[13:04:41]: Created app PNGF6VDQEQ
[13:04:42]: Finished creating new app 'Christmas Surprising Bonus Casino Slot' on the Dev Center
[13:04:46]: Creating new app 'Christmas Surprising Bonus Casino Slot' on iTunes Connect
[13:04:55]: Waiting for the newly created application to be available on iTunes Connect...
[13:05:10]: Waiting for the newly created application to be available on iTunes Connect...
[13:05:26]: Waiting for the newly created application to be available on iTunes Connect...
[13:05:42]: Waiting for the newly created application to be available on iTunes Connect...
[13:05:57]: Waiting for the newly created application to be available on iTunes Connect...
[13:06:13]: Waiting for the newly created application to be available on iTunes Connect...
[13:06:29]: Waiting for the newly created application to be available on iTunes Connect...
[13:06:45]: Waiting for the newly created application to be available on iTunes Connect...
[13:07:00]: Waiting for the newly created application to be available on iTunes Connect...
[13:07:16]: Waiting for the newly created application to be available on iTunes Connect...
[13:07:32]: Waiting for the newly created application to be available on iTunes Connect...
[13:07:48]: Waiting for the newly created application to be available on iTunes Connect...
[13:08:04]: Waiting for the newly created application to be available on iTunes Connect...
[13:08:19]: Waiting for the newly created application to be available on iTunes Connect...
[13:08:35]: Waiting for the newly created application to be available on iTunes Connect...
[13:08:51]: Waiting for the newly created application to be available on iTunes Connect...
[13:09:07]: Waiting for the newly created application to be available on iTunes Connect...
[13:09:23]: Waiting for the newly created application to be available on iTunes Connect...
[13:09:39]: Waiting for the newly created application to be available on iTunes Connect...
[13:09:55]: Waiting for the newly created application to be available on iTunes Connect...
[13:10:11]: Waiting for the newly created application to be available on iTunes Connect...
[13:10:27]: Waiting for the newly created application to be available on iTunes Connect...
[13:10:43]: Waiting for the newly created application to be available on iTunes Connect...
[13:10:59]: Waiting for the newly created application to be available on iTunes Connect...
[13:11:14]: Waiting for the newly created application to be available on iTunes Connect...
[13:11:30]: Waiting for the newly created application to be available on iTunes Connect...
[13:11:46]: Waiting for the newly created application to be available on iTunes Connect...
[13:12:02]: Waiting for the newly created application to be available on iTunes Connect...
[13:12:17]: Waiting for the newly created application to be available on iTunes Connect...
[13:12:33]: Waiting for the newly created application to be available on iTunes Connect...
[13:12:49]: Waiting for the newly created application to be available on iTunes Connect...
[13:13:04]: Waiting for the newly created application to be available on iTunes Connect...
[13:13:20]: Waiting for the newly created application to be available on iTunes Connect...
[13:13:36]: Waiting for the newly created application to be available on iTunes Connect...
[13:13:52]: Waiting for the newly created application to be available on iTunes Connect...
[13:14:08]: Waiting for the newly created application to be available on iTunes Connect...
[13:14:23]: Waiting for the newly created application to be available on iTunes Connect...
[13:14:39]: Waiting for the newly created application to be available on iTunes Connect...
[13:14:55]: Waiting for the newly created application to be available on iTunes Connect...
[13:15:11]: Waiting for the newly created application to be available on iTunes Connect...
[13:15:27]: Waiting for the newly created application to be available on iTunes Connect...
[13:15:42]: Waiting for the newly created application to be available on iTunes Connect...
[13:15:58]: Waiting for the newly created application to be available on iTunes Connect...
[13:16:14]: Waiting for the newly created application to be available on iTunes Connect...
[13:16:29]: Waiting for the newly created application to be available on iTunes Connect...
[13:16:45]: Waiting for the newly created application to be available on iTunes Connect...
[13:17:01]: Waiting for the newly created application to be available on iTunes Connect...
[13:17:17]: Waiting for the newly created application to be available on iTunes Connect...
[13:17:32]: Waiting for the newly created application to be available on iTunes Connect...
[13:17:48]: Waiting for the newly created application to be available on iTunes Connect...
[13:18:04]: Waiting for the newly created application to be available on iTunes Connect...
[13:18:19]: Waiting for the newly created application to be available on iTunes Connect...
[13:18:35]: Waiting for the newly created application to be available on iTunes Connect...
[13:18:51]: Waiting for the newly created application to be available on iTunes Connect...
[13:19:06]: Waiting for the newly created application to be available on iTunes Connect...
[13:19:22]: Waiting for the newly created application to be available on iTunes Connect...
[13:19:38]: Waiting for the newly created application to be available on iTunes Connect...
[13:19:54]: Waiting for the newly created application to be available on iTunes Connect...
[13:20:10]: Waiting for the newly created application to be available on iTunes Connect...
[13:20:25]: Waiting for the newly created application to be available on iTunes Connect...
[13:20:41]: Waiting for the newly created application to be available on iTunes Connect...
[13:20:57]: Waiting for the newly created application to be available on iTunes Connect...
[13:21:12]: Waiting for the newly created application to be available on iTunes Connect...
[13:21:28]: Waiting for the newly created application to be available on iTunes Connect...
[13:21:44]: Waiting for the newly created application to be available on iTunes Connect...
[13:22:00]: Waiting for the newly created application to be available on iTunes Connect...
[13:22:16]: Waiting for the newly created application to be available on iTunes Connect...
[13:22:31]: Waiting for the newly created application to be available on iTunes Connect...
[13:22:47]: Waiting for the newly created application to be available on iTunes Connect...
[13:23:03]: Waiting for the newly created application to be available on iTunes Connect...
[13:23:19]: Waiting for the newly created application to be available on iTunes Connect...
[13:23:35]: Waiting for the newly created application to be available on iTunes Connect...
[13:23:50]: Waiting for the newly created application to be available on iTunes Connect...
[13:24:06]: Waiting for the newly created application to be available on iTunes Connect...
[13:24:22]: Waiting for the newly created application to be available on iTunes Connect...
[13:24:38]: Waiting for the newly created application to be available on iTunes Connect...
[13:24:54]: Waiting for the newly created application to be available on iTunes Connect...
[13:25:10]: Waiting for the newly created application to be available on iTunes Connect...
[13:25:25]: Waiting for the newly created application to be available on iTunes Connect...
[13:25:41]: Waiting for the newly created application to be available on iTunes Connect...
[13:25:57]: Waiting for the newly created application to be available on iTunes Connect...
[13:26:12]: Waiting for the newly created application to be available on iTunes Connect...
[13:26:28]: Waiting for the newly created application to be available on iTunes Connect...
[13:26:44]: Waiting for the newly created application to be available on iTunes Connect...
[13:26:59]: Waiting for the newly created application to be available on iTunes Connect...
[13:27:15]: Waiting for the newly created application to be available on iTunes Connect...
[13:27:31]: Waiting for the newly created application to be available on iTunes Connect...
[13:27:47]: Waiting for the newly created application to be available on iTunes Connect...
[13:28:02]: Waiting for the newly created application to be available on iTunes Connect...
[13:28:18]: Waiting for the newly created application to be available on iTunes Connect...
[13:28:34]: Waiting for the newly created application to be available on iTunes Connect...
[13:28:49]: Waiting for the newly created application to be available on iTunes Connect...
[13:29:05]: Waiting for the newly created application to be available on iTunes Connect...
[13:29:21]: Waiting for the newly created application to be available on iTunes Connect...
[13:29:37]: Waiting for the newly created application to be available on iTunes Connect...
[13:29:53]: Waiting for the newly created application to be available on iTunes Connect...
[13:30:08]: Waiting for the newly created application to be available on iTunes Connect...
[13:30:24]: Waiting for the newly created application to be available on iTunes Connect...
[13:30:40]: Waiting for the newly created application to be available on iTunes Connect...
[13:30:55]: Waiting for the newly created application to be available on iTunes Connect...
[13:31:11]: Waiting for the newly created application to be available on iTunes Connect...
[13:31:27]: Waiting for the newly created application to be available on iTunes Connect...
[13:31:42]: Waiting for the newly created application to be available on iTunes Connect...
[13:31:58]: Waiting for the newly created application to be available on iTunes Connect...
[13:32:14]: Waiting for the newly created application to be available on iTunes Connect...
[13:32:30]: Waiting for the newly created application to be available on iTunes Connect...
[13:32:46]: Waiting for the newly created application to be available on iTunes Connect...
[13:33:01]: Waiting for the newly created application to be available on iTunes Connect...
[13:33:21]: Waiting for the newly created application to be available on iTunes Connect...
[13:33:37]: Waiting for the newly created application to be available on iTunes Connect...
[13:33:53]: Waiting for the newly created application to be available on iTunes Connect...
[13:34:09]: Waiting for the newly created application to be available on iTunes Connect...
[13:34:24]: Waiting for the newly created application to be available on iTunes Connect...
[13:34:40]: Waiting for the newly created application to be available on iTunes Connect...
[13:34:56]: Waiting for the newly created application to be available on iTunes Connect...
[13:35:12]: Waiting for the newly created application to be available on iTunes Connect...
[13:35:28]: Waiting for the newly created application to be available on iTunes Connect...
[13:35:43]: Waiting for the newly created application to be available on iTunes Connect...
[13:35:59]: Waiting for the newly created application to be available on iTunes Connect...
[13:36:15]: Waiting for the newly created application to be available on iTunes Connect...
[13:36:31]: Waiting for the newly created application to be available on iTunes Connect...
[13:36:46]: Waiting for the newly created application to be available on iTunes Connect...
[13:37:02]: Waiting for the newly created application to be available on iTunes Connect...
[13:37:18]: Waiting for the newly created application to be available on iTunes Connect...
[13:37:34]: Waiting for the newly created application to be available on iTunes Connect...
[13:37:51]: Waiting for the newly created application to be available on iTunes Connect...
[13:38:08]: Waiting for the newly created application to be available on iTunes Connect...
[13:38:24]: Waiting for the newly created application to be available on iTunes Connect...
[13:38:40]: Waiting for the newly created application to be available on iTunes Connect...
[13:38:55]: Waiting for the newly created application to be available on iTunes Connect...
[13:39:11]: Waiting for the newly created application to be available on iTunes Connect...
[13:39:27]: Waiting for the newly created application to be available on iTunes Connect...
[13:39:43]: Waiting for the newly created application to be available on iTunes Connect...
[13:39:59]: Waiting for the newly created application to be available on iTunes Connect...
[13:40:14]: Waiting for the newly created application to be available on iTunes Connect...
[13:40:30]: Waiting for the newly created application to be available on iTunes Connect...
[13:40:46]: Waiting for the newly created application to be available on iTunes Connect...
[13:41:01]: Waiting for the newly created application to be available on iTunes Connect...
[13:41:17]: Waiting for the newly created application to be available on iTunes Connect...
[13:41:33]: Waiting for the newly created application to be available on iTunes Connect...
[13:41:48]: Waiting for the newly created application to be available on iTunes Connect...
[13:42:04]: Waiting for the newly created application to be available on iTunes Connect...
[13:42:20]: Waiting for the newly created application to be available on iTunes Connect...
[13:42:36]: Waiting for the newly created application to be available on iTunes Connect...
[13:42:51]: Waiting for the newly created application to be available on iTunes Connect...
[13:43:07]: Waiting for the newly created application to be available on iTunes Connect...
[13:43:23]: Waiting for the newly created application to be available on iTunes Connect...
[13:43:39]: Waiting for the newly created application to be available on iTunes Connect...
[13:43:54]: Waiting for the newly created application to be available on iTunes Connect...
[13:44:10]: Waiting for the newly created application to be available on iTunes Connect...
[13:44:26]: Waiting for the newly created application to be available on iTunes Connect...
[13:44:42]: Waiting for the newly created application to be available on iTunes Connect...
[13:44:58]: Waiting for the newly created application to be available on iTunes Connect...
[13:45:13]: Waiting for the newly created application to be available on iTunes Connect...
[13:45:29]: Waiting for the newly created application to be available on iTunes Connect...
[13:45:45]: Waiting for the newly created application to be available on iTunes Connect...
[13:46:01]: Waiting for the newly created application to be available on iTunes Connect...
[13:46:17]: Waiting for the newly created application to be available on iTunes Connect...
[13:46:33]: Waiting for the newly created application to be available on iTunes Connect...
[13:46:49]: Waiting for the newly created application to be available on iTunes Connect...
[13:47:04]: Waiting for the newly created application to be available on iTunes Connect...
[13:47:20]: Waiting for the newly created application to be available on iTunes Connect...
[13:47:36]: Waiting for the newly created application to be available on iTunes Connect...
[13:47:52]: Waiting for the newly created application to be available on iTunes Connect...
[13:48:08]: Waiting for the newly created application to be available on iTunes Connect...
[13:48:23]: Waiting for the newly created application to be available on iTunes Connect...
[13:48:39]: Waiting for the newly created application to be available on iTunes Connect...
[13:48:55]: Waiting for the newly created application to be available on iTunes Connect...
[13:49:10]: Waiting for the newly created application to be available on iTunes Connect...
[13:49:26]: Waiting for the newly created application to be available on iTunes Connect...
[13:49:42]: Waiting for the newly created application to be available on iTunes Connect...
[13:49:58]: Waiting for the newly created application to be available on iTunes Connect...
[13:50:14]: Waiting for the newly created application to be available on iTunes Connect...
[13:50:29]: Waiting for the newly created application to be available on iTunes Connect...
[13:50:45]: Waiting for the newly created application to be available on iTunes Connect...
[13:51:01]: Waiting for the newly created application to be available on iTunes Connect...
[13:51:16]: Waiting for the newly created application to be available on iTunes Connect...
[13:51:32]: Waiting for the newly created application to be available on iTunes Connect...
[13:51:48]: Waiting for the newly created application to be available on iTunes Connect...
[13:52:04]: Waiting for the newly created application to be available on iTunes Connect...
[13:52:19]: Waiting for the newly created application to be available on iTunes Connect...
[13:52:35]: Waiting for the newly created application to be available on iTunes Connect...
[13:52:52]: Waiting for the newly created application to be available on iTunes Connect...
[13:53:08]: Waiting for the newly created application to be available on iTunes Connect...
[13:53:24]: Waiting for the newly created application to be available on iTunes Connect...
[13:53:40]: Waiting for the newly created application to be available on iTunes Connect...
[13:53:56]: Waiting for the newly created application to be available on iTunes Connect...
[13:54:11]: Waiting for the newly created application to be available on iTunes Connect...
[13:54:27]: Waiting for the newly created application to be available on iTunes Connect...
[13:54:43]: Waiting for the newly created application to be available on iTunes Connect...
[13:54:58]: Waiting for the newly created application to be available on iTunes Connect...
[13:55:14]: Waiting for the newly created application to be available on iTunes Connect...
[13:55:51]: Waiting for the newly created application to be available on iTunes Connect...
[13:56:07]: Waiting for the newly created application to be available on iTunes Connect...
[13:56:23]: Waiting for the newly created application to be available on iTunes Connect...
[13:56:39]: Waiting for the newly created application to be available on iTunes Connect...
[13:56:55]: Waiting for the newly created application to be available on iTunes Connect...
[13:57:10]: Waiting for the newly created application to be available on iTunes Connect...
[13:57:26]: Waiting for the newly created application to be available on iTunes Connect...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Couldn't find newly created app on iTunes Connect - please check the website for more information
   https://github.com/fastlane/fastlane/issues/6281 [closed] 9 💬
   3 days ago

➡️  Produce fails to create app on iTunes Connect
   https://github.com/fastlane/fastlane/issues/6368 [open] 5 💬
   7 weeks ago

➡️  Deliver fails with "Unexpected Error" after uploading package to iTunes Connect
   https://github.com/fastlane/fastlane/issues/6455 [closed] 51 💬
   5 weeks ago

/Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Couldn't find newly created app on iTunes Connect - please check the website for more information (FastlaneCore::Interface::FastlaneCrash)
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/produce-1.3.1/lib/produce/itunes_connect.rb:39:in `create_new_app'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/produce-1.3.1/lib/produce/itunes_connect.rb:12:in `run'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/produce-1.3.1/lib/produce/manager.rb:8:in `start_producing'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/produce-1.3.1/lib/produce/commands_generator.rb:35:in `block (2 levels) in run'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/produce-1.3.1/lib/produce/commands_generator.rb:133:in `run'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/produce-1.3.1/lib/produce/commands_generator.rb:11:in `start'
	from /Users/Shirkan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/produce-1.3.1/bin/produce:6:in `<top (required)>'
	from /Users/Shirkan/.rbenv/versions/2.3.1/bin/produce:23:in `load'
	from /Users/Shirkan/.rbenv/versions/2.3.1/bin/produce:23:in `<main>'

**Comment by shirkan** [comment]
I strongly believe it's an issue with iTunes Connect (App ID created successfully on Developer Center).
On a different account, I have an update waiting for 5 days to be reviewed.

**Comment by GT-3** [comment]
happen also to me. any idea what is the reason for that?

**Comment by shirkan** [comment]
It took only 14 hours, but in the end it finally showed up in iTunes Connect.

**Comment by GandjaFuzz** [comment]
having this problem too
