### ISSUE TITLE
scan stuck after finished running tests

### ISSUE THREAD

**Issue by yeyimilk** [fastlane/fastlane#6290]
### New Issue Checklist
- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I have installed the latest version of scan, but not fastlane.
It's awesome and works well in my server mac pro if directly open the server mac pro command line and enter 
`scan --workspace myApp.xcworkspace --scheme myApp --device 'iPhone 6' clean` 
However, if I put this command in the Jenkins job, it's always loading after finished running the tests. I try to use another mac to access the server mac pro through ssh, the same problem happens even I use the same command line.
##### Complete output when running fastlane, including the stack trace and command used

```
15:38:52: ▸ ValidatorTest
15:38:52: ▸ ✓ Password (0.007 seconds)
15:38:52: ▸ ✓ Number (0.005 seconds)
15:38:52: ▸ ✓ NewLine (0.005 seconds)
15:38:52: ▸ ✓ Hash (0.006 seconds)
15:38:52: ▸ ✓ At (0.005 seconds)
15:38:52: ▸ ✓ Mail (0.008 seconds)
15:38:52: ▸ ✓ Phone (0.252 seconds)
15:38:52: ▸ ✓ URL (0.039 seconds)
15:38:52: ▸ Executed 38 tests, with 0 failures (0 unexpected) in 16.332 (17.564) seconds

^C^C
Cancelled... use --verbose to show the stack trace
XXXXs-Mac-Pro:XXX xxx$ scan --verbose
INFO [2016-09-26 16:10:50.04]: $ xcodebuild -list -workspace ./XXX.xcworkspace
Select Scheme: 
1. XXX
2. XXXCore
3. socketio
4. Analytics
5. DTCoreText
6. DTFoundation
7. IDMPhotoBrowser
8. JTCalendar
9. MGSwipeTableCell
10. Pods
11. SDWebImage
12. SnapKit
13. TTTAttributedLabel
14. YYText
?
```
# 

If I run the command line directly in the mac server, here is the success output

```
[15:08:50]: ▸ ValidatorTest
[15:08:50]: ▸ ✓ Password (0.001 seconds)
[15:08:50]: ▸ ✓ Number (0.001 seconds)
[15:08:50]: ▸ ✓ NewLine (0.001 seconds)
[15:08:50]: ▸ ✓ Hash (0.001 seconds)
[15:08:50]: ▸ ✓ At (0.001 seconds)
[15:08:50]: ▸ ✓ Mail (0.001 seconds)
[15:08:50]: ▸ ✓ Phone (0.003 seconds)
[15:08:50]: ▸ ✓ URL (0.010 seconds)
[15:08:50]: ▸      Executed 38 tests, with 0 failures (0 unexpected) in 0.240 (0.302) seconds
[15:08:50]: ▸ 
[15:08:50]: ▸ Test Succeeded
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 38    |
| Number of failures | 0     |
+--------------------+-------+
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:
Fastfile:
### Environment

fastlane version (run `fastlane -v`):
Xcode 7.3.1,  OS X 10.11.6
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by yeyimilk** [comment]
```
?  ^C/Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:870:in `gets': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:870:in `get_line'
	from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:891:in `get_response'
	from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
	from /Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline.rb:365:in `choose'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/project.rb:137:in `select_scheme'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.13.0/lib/scan/detect_values.rb:21:in `set_additional_default_values'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.13.0/lib/scan.rb:27:in `config='
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.13.0/lib/scan/manager.rb:4:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.13.0/lib/scan/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.13.0/lib/scan/commands_generator.rb:60:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.13.0/lib/scan/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.13.0/bin/scan:6:in `<top (required)>'
	from /usr/local/bin/scan:23:in `load'
	from /usr/local/bin/scan:23:in `<main>'
```

**Comment by TKBurner** [comment]
@yeyimilk Thanks for reaching out. Can you try setting the --scheme parameter of _scan_?
