### ISSUE TITLE
Does not have access to any teams with an active membership... Have Certs on laptop

### ISSUE THREAD

**Issue by XPMCoding** [fastlane/fastlane#6316]
### New Issue Checklist
- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.34.1/lib/spaceship/portal/portal_client.rb:47:in `team_id': User 'vrx96701@xzsok.com' does not have access to any teams with an active membership (RuntimeError)
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.34.1/lib/spaceship/portal/portal_client.rb:92:in `block in apps'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.34.1/lib/spaceship/client.rb:183:in `block in paging'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.34.1/lib/spaceship/client.rb:181:in `loop'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.34.1/lib/spaceship/client.rb:181:in `paging'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.34.1/lib/spaceship/portal/portal_client.rb:90:in `apps'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.34.1/lib/spaceship/portal/app.rb:80:in `all'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.34.1/lib/spaceship/portal/portal_client.rb:449:in `ensure_csrf'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.34.1/lib/spaceship/portal/portal_client.rb:139:in `create_app!'
    from /Users/jacobfolsom/Desktop/su-a-cyder/evilsnap/su-a-cyder.rb:4:in `<main>'
#!# Process Failed!
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
update_fastlane
skip_docs

desc "Run bundle install and tests"
lane :test do
  validate_repo(tool_name: detect_tool)
end

desc "Increment the version number of this gem"
lane :bump do |options|
  tool_name = options[:tool] || detect_tool
  path = "./lib/#{tool_name}/version.rb"

  latest_release = current_version(tool: tool_name)
  `open https://github.com/#{github_url(tool: tool_name)}/compare/#{latest_release}...master`

  local_version = version_get_podspec(path: path) # here, to not show the lane change

  puts "Live Version: #{latest_release}"
  puts "Local Version: #{local_version}"

  bump_type ||= 'minor' if prompt(text: "New Feature?", boolean: true)
  bump_type ||= 'patch' if bump_type.nil? && prompt(text: "Bugfix/Improvements?", boolean: true)

  if bump_type
    version_bump_podspec(path: path, bump_type: bump_type)
    git_commit(path: path,
               message: "Version Bump by fastlane")
    push_to_git_remote
  else
    puts "Doing nothing..."
  end
end

desc "Does everything that's needed for a release, this includes running tests and verifying the GitHub release"
lane :release do |options|
  # Fetching all information required for the release
  #
  tool_name = options[:tool] || detect_tool

  # Verifying RubyGems version
  #
  validate_repo(tool_name: tool_name)

  require "../lib/#{tool_name}/version"
  version = module_ref(tool_name: tool_name)::VERSION
  old_version = current_version(tool: tool_name)
  puts "Deploying #{tool_name} #{version}"
  if Gem::Version.new(version) <= Gem::Version.new(old_version)
    UI.user_error!("Version number #{version} was already deployed")
  end

  # Git verification
  #
  ensure_git_status_clean
  ensure_git_branch(branch: 'master')
  git_pull
  push_to_git_remote

  # Preparing GitHub Release
  #
  github_release = get_github_release(url: github_url(tool: tool_name), version: version)
  if (github_release || {}).fetch('body', '').length == 0
    print_release_changelog(tool: tool_name, old_version: old_version)

    # For now, continue to open the git comparison from the old repository, so that we can
    # catch any changes that were made before the mono-repo change (eventually remove this)
    `open https://github.com/#{github_url(tool: tool_name)}/compare/#{old_version}...master`

    title = prompt(text: 'Title: ')
    description = prompt(text: "Please enter a changelog: ",
                         multi_line_end_keyword: "END")

    github_release = set_github_release(
      repository_name: github_url(tool: tool_name),
      name: [version, title].join(" "),
      tag_name: version,
      description: description,
      is_draft: false
    )

    release_url = github_release['html_url']
    clipboard(value: release_url)

    message = [title, description, release_url].join("\n\n")
    add_fastlane_git_tag(tag: "#{tool_name}/#{version}", message: message)
  end

  # Actual release
  #
  sh "gem push ../pkg/#{tool_name}-#{version}.gem"

  # After publishing
  #
  if ENV['SLACK_URL']
    slack(
      channel: "releases",
      default_payloads: [],
      message: "Successfully released [#{tool_name} #{version}](#{release_url}) :rocket:",
      payload: {
        "New" => github_release['body']
      }
    )
  end

  puts "You can now tweet:".green
  tag_url = "https://github.com/fastlane/fastlane/releases/tag/#{tool_name}/#{version}"
  puts "[#{tool_name}] #{github_release['name']} #{tag_url}"
end

error do |lane, exception|
  if ENV['SLACK_URL']
    slack(channel: "testing", message: exception.to_s, success: false)
  end
end

desc "Verifies all tests pass and the current state of the repo is valid"
private_lane :validate_repo do |options|
  # Verifying that no debug code is in the code base
  #
  ensure_no_debug_code(text: "pry", extension: ".rb", path: "./lib/") # debugging code
  ensure_no_debug_code(text: "TODO", extension: ".rb", path: "./lib/") # TODOs
  ensure_no_debug_code(text: "now: ", extension: ".rb", path: "./lib/") # rspec focus
  ensure_no_debug_code(text: "<<<<<<<", extension: ".rb", path: "./lib/") # Merge conflict

  rubocop if File.exist?("../.rubocop.yml") # some project don't yet use rubocop

  # Restricted from running on Travis CI because it causes builds to hang.
  #
  unless ENV['TRAVIS']
    # Verifying the --help command
    #
    tool_name = options[:tool_name]
    binary_path = File.join("..", "bin", tool_name)
    unless no_binary.include? tool_name
      content = sh "PAGER=cat #{binary_path} --help"
      ["--version", "https://fastlane.tools", tool_name].each do |current|
        UI.user_error!("--help missing information: '#{current}'") unless content.include? current
      end
    end
  end

  # Running ruby things
  #
  sh "cd .. && bundle install"
  sh "cd .. && rake install"

  # Run the tests
  #
  sh "cd .. && bundle exec rspec"
end

desc "e.g. fastlane/deliver"
private_lane :github_url do |options|
  ["fastlane", options[:tool]].join("/")
end

desc "Get the version number of the last release"
private_lane :current_version do |options|
  puts "Checking the latest version on RubyGems"
  download(url: "https://rubygems.org/api/v1/gems/#{options[:tool]}.json")["version"]
end

desc "All repos that don't have a binary to test"
private_lane :no_binary do
  ['fastlane_core', 'spaceship', 'credentials_manager']
end

desc "Detects the name of the tool based on the current directory"
private_lane :detect_tool do
  Dir["../*.gemspec"].last.match(/(\w+).gemspec/)[1]
end

desc "Get a reference to the module of this tool"
desc "This method can be overwritten by the individual Fastfiles of the tools (e.g. PEM)"
private_lane :module_ref do |options|
  Object.const_get(options[:tool_name].split('_').collect(&:capitalize).join)
end

desc "Print out the changelog since the last tagged release"
private_lane :print_release_changelog do |options|
  tool_name = options[:tool]
  old_version = options[:old_version]

  cmd = "git log --pretty='* %B' #{tool_name}/#{old_version}...HEAD --no-merges .."
  puts "Changes since release #{old_version}:\n" + `#{cmd}`.gsub("\n\n", "\n")
end

desc "Add a git tag in the fastlane repo for this release"
private_lane :add_fastlane_git_tag do |options|
  `git tag -am #{options[:message].shellescape} #{options[:tag].shellescape}`
  push_git_tags
end


```
### Environment

fastlane version (run `fastlane -v`): fastlane 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
@XPMCoding Can you let me know what lane you are running when you see this? Can you share the full input and output of the lane so I can take a look at what's going on. I can't wait to get to the bottom of this. Thanks!
