### ISSUE TITLE
Xcode 8 - Provisioning profile ignored [Gym]

### ISSUE THREAD

**Issue by ATS-RyanPowell** [fastlane/fastlane#6317]
The provisioning profile is ignored when building with gym. When setting either the command argument '--provisioning_profile_path' or setting via gymfile, the environment variable is not set when calling xcodebuild

Output
```
Dev-iMac-2:webviewer-ios ats$ gym --verbose
INFO [2016-09-28 15:11:46.82]: Installing provisioning profile...
INFO [2016-09-28 15:11:46.95]: $ xcodebuild -list -project ./WebViewer.xcodeproj
INFO [2016-09-28 15:11:47.48]: $ xcodebuild clean -showBuildSettings -scheme WebViewer -project ./WebViewer.xcodeproj
ERROR [2016-09-28 15:11:48.02]: Couldn't find specified configuration 'release'.

+---------------------------+---------------------------------------------------------------+
|                                  Summary for gym 1.10.0                                   |
+---------------------------+---------------------------------------------------------------+
| scheme                    | WebViewer                                                     |
| output_directory          | ./build/                                                      |
| result_bundle             | ./build/                                                      |
| buildlog_path             | ./build/                                                      |
| codesigning_identity      | iPhone Distribution: MyCertificate        |
| provisioning_profile_path | /Users/Shared/Public/iOS/Provision/enterprise.mobileprovision |
| clean                     | true                                                          |
| use_legacy_build_api      | false                                                         |
| project                   | ./WebViewer.xcodeproj                                         |
| destination               | generic/platform=iOS                                          |
| output_name               | WebViewer                                                     |
| silent                    | false                                                         |
+---------------------------+---------------------------------------------------------------+

+---------------------------------------------------------------------------------------------------------------+--------------------------+
|                                                         Generated Build Command                                                          |
+---------------------------------------------------------------------------------------------------------------+--------------------------+
| Option                                                                                                        | Value                    |
+---------------------------------------------------------------------------------------------------------------+--------------------------+
| set -o pipefail &&                                                                                            |                          |
| xcodebuild                                                                                                    |                          |
| -scheme WebViewer                                                                                             |                          |
| -project ./WebViewer.xcodeproj                                                                                |                          |
| -destination                                                                                                  | generic/platform=iOS     |
| -archivePath /Users/ats/Library/Developer/Xcode/Archives/2016-09-28/WebViewer\ 2016-09-28\ 15.11.48.xcarchive |                          |
| -resultBundlePath                                                                                             | ./build/WebViewer.result |
| clean                                                                                                         |                          |
| archive                                                                                                       |                          |
| CODE_SIGN_IDENTITY=iPhone\ Distribution:\ MyCertificate                                |                          |
| | tee /Users/ats/Desktop/webviewer-ios/build/WebViewer-WebViewer.log                                           |                          |
| | xcpretty                                                                                                     |                          |
+---------------------------------------------------------------------------------------------------------------+--------------------------+
INFO [2016-09-28 15:11:48.03]: $ set -o pipefail && xcodebuild -scheme WebViewer -project ./WebViewer.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/ats/Library/Developer/Xcode/Archives/2016-09-28/WebViewer\ 2016-09-28\ 15.11.48.xcarchive -resultBundlePath './build/WebViewer.result' clean archive CODE_SIGN_IDENTITY=iPhone\ Distribution:\ Advanced\ Thinking\ Systems\ Limited | tee /Users/ats/Desktop/webviewer-ios/build/WebViewer-WebViewer.log | xcpretty
INFO [2016-09-28 15:11:48.10]: ▸ xcodebuild: error: Existing file at -resultBundlePath "/Users/ats/Desktop/webviewer-ios/build/WebViewer.result"
xcodebuild: error: Existing file at -resultBundlePath "/Users/ats/Desktop/webviewer-ios/build/WebViewer.result"
ERROR [2016-09-28 15:11:48.26]: Exit status: 64
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Error building the application - see the log above (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.10.0/lib/gym/error_handler.rb:53:in `handle_build_error'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.10.0/lib/gym/runner.rb:101:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/command_executor.rb:88:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/command_executor.rb:88:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.10.0/lib/gym/runner.rb:97:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.10.0/lib/gym/runner.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.10.0/lib/gym/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.10.0/lib/gym/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.10.0/lib/gym/commands_generator.rb:61:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.10.0/lib/gym/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.10.0/bin/gym:6:in `<top (required)>'
	from /usr/local/bin/gym:23:in `load'
	from /usr/local/bin/gym:23:in `<main>'
```

### Additional

Gymfile used with above
```
#App configuration
scheme "WebViewer"
configuration "release"

#Output
output_directory "./build/"
result_bundle "./build/"
buildlog_path "./build/"

#Code signing
codesigning_identity "iPhone Distribution: MyCertificate"
provisioning_profile_path "/Users/Shared/Public/iOS/Provision/enterprise.mobileprovision"

#Flags
clean true
use_legacy_build_api false
```

xcode tail log for above
```
Dev-iMac-2:webviewer-ios ats$ tail /Users/ats/Desktop/webviewer-ios/build/WebViewer-WebViewer.log

=== BUILD TARGET WebViewer OF PROJECT WebViewer WITH CONFIGURATION Release ===

Check dependencies
WebViewer requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
```

Also, this Gymfile did work with Xcode 7. 

### Software Versions
gym 1.10.0
xcode 8.0
macOS 10.11.6

**Comment by pedro380085** [comment]
provisioning_profile_path is deprecated on xcode 8, use the new provisioning_specifier.

**Comment by Ryandev** [comment]
If that is the case feedback from gym stating provisioning_profile_path  it's no longer supported on Xcode 8 would be helpful

**Comment by TKBurner** [comment]
@ATS-RyanPowell You will need to setup this in your build settings in Xcode. Thanks!

**Comment by rocco** [comment]
@TKBurner how about an automatically generated .xcodeproj e.g. by Cordova then - this cannot be built on a CI/build server (without opening XCode in general)?

**Comment by TKBurner** [comment]
@rocco Very interesting. Are you not able to setup the manual code signing on this generated project? Unfortunately, that's the only way to get it to work properly.

**Comment by rocco** [comment]
@TKBurner the Cordova/Ionic project contains only

    attributes = {
        LastUpgradeCheck = 510;
    };

in its PBXProject section after you freshly generate it. The `TargetAttributes` key is missing there. My solution currently is to run 

    xcproj = Xcodeproj::Project.open(xcodeprojpath)
    xcproj.build_configurations.each do |item|
        item.build_settings['DEVELOPMENT_TEAM'] = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
        item.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = "iPhone Distribution"
        item.build_settings['PROVISIONING_PROFILE'] = "b4439b9e-a0da-4a24-819e-6b611001328a"
        item.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = "match AppStore com.roccogeorgi.mycoolapp"
        # ....
    end
    xcproj.save

in my Fastfile (to set provisioning profiles manually) resulting in this:

    attributes = {
        LastUpgradeCheck = 510;
        TargetAttributes = {
            1D6058900D05DD3D006BFB54 = {
                DevelopmentTeam = ABC12345678;
            };
        };
    };

Xcode shows no checkbox anymore next to `Automatically manage signing` and the CLI build works w/o opening Xcode.

**Comment by TKBurner** [comment]
@rocco That's really cool. Is there a way we can integrate this into _fastlane_ so others will have an easier time too? Thanks!

**Comment by rocco** [comment]
@TKBurner I am not quite sure yet how _match_ fits into the picture here. I use **two** _match_ calls just before the code block above - one with type "development" and one with type "adhoc" to get appropriate provisioning profiles and ENV vars, then I am setting these provisioning profile's values to "Signing (Debug)" and "Signing (Release)" sections (as called in Xcode) using similar code as above as it is impossible to do the [recommended Xcode setup for _match_](https://docs.fastlane.tools/codesigning/xcode-project) on a CI server. 

While this works well, I feel like _match_ (which is already excellent btw.) could help me out more here and provide for setting "Debug" and "Release" signing in one call as well as changing Xcode's signing setup from "Automatic" to "Manual" which is just another key/value in the pbxproj file. This way the whole thing would be condensable to one _match_ call and make the (also excellent) [xcodeproj gem](https://rubygems.org/gems/xcodeproj) redundant. 

So how about extending _match_?

**Comment by TKBurner** [comment]
@rocco Thanks for the idea. I agree, we are seeing more and more people with several match commands in a row.  I want to leave this open as a feature request and we'll see if others are interested too 👍

**Comment by rocco** [comment]
It would help if the type: key in _match_ would accept an array - similar to app_identifier:
