### ISSUE TITLE
Cannot run fastlane on Xcode Server bot

### ISSUE THREAD

**Issue by fcamaster** [fastlane/fastlane#6318]
### Issue Description

Cannot run fastlane from Xcode bot trigger (error: Could not retrieve response as fastlane runs in non-interactive mode).
I've read many issues here and none of that worked for me.

##### Complete output when running fastlane, including the stack trace and command used

This is what I get when I try to run fastlane from Xcode bot:

export LC_ALL="en_US.UTF8"
export PATH=/usr/local/bin:$PATH
fastlane ios after_integration --verbose

```
[16:21:07]: [33mSeems like launching fastlane takes a while - please run[0m
[16:21:07]: 
[16:21:07]: [4m[36m$ [sudo] gem cleanup[0m[0m
[16:21:07]: 
[16:21:07]: [33mto uninstall outdated gems and make fastlane launch faster[0m
[16:21:07]: [33mAlternatively it's recommended to start using a Gemfile to lock your dependencies[0m
[16:21:07]: [33mTo get started with a Gemfile, run[0m
[16:21:07]: 
[16:21:07]: [4m[36m$ bundle init[0m[0m
[16:21:07]: [4m[36m$ echo 'gem "fastlane"' >> Gemfile[0m[0m
[16:21:07]: [4m[36m$ bundle install[0m[0m
[16:21:07]: 
[16:21:07]: [33mAfter creating the Gemfile and Gemfile.lock, commit those files into version control[0m
[16:21:07]: [33mFor more information, check out https://guides.cocoapods.org/using/a-gemfile.html[0m
DEBUG [2016-09-28 16:21:18.44]: Checking if there are any plugins that should be loaded...
WARN [2016-09-28 16:21:18.54]: [33mCould not find fastlane in current directory. Would you like to set it up?[0m

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  [33mRunning fastlane on Bitrise - non-interactive mode[0m
   https://github.com/fastlane/fastlane/issues/5867 [[32mclosed[0m] 5 💬
   5 weeks ago

➡️  [33mFastlane android deploy issue[0m
   https://github.com/fastlane/fastlane/issues/5800 [[32mclosed[0m] 2 💬
   5 weeks ago

➡️  [33mBug - using fastlane to run fastlane (as shell script) fails when interaction required[0m
   https://github.com/fastlane/fastlane/issues/3788 [[32mclosed[0m] 3 💬
   a week ago

and 3 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:132:in `crash!': [31m[!] Could not retrieve response as fastlane runs in non-interactive mode[0m (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/implementations/shell.rb:119:in `verify_interactive!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/implementations/shell.rb:97:in `confirm'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:256:in `ensure_fastfile'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:48:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

This is what I get when I run the command directly from the project directory:
bundle exec fastlane ios after_integration
```
[16:53:58]: -----------------------------
[16:53:58]: --- Step: update_fastlane ---
[16:53:58]: -----------------------------
[16:53:58]: Looking for updates for credentials_manager, fastlane_core, spaceship, cert, deliver, frameit, gym, sigh, match, pem, pilot, produce, scan, screengrab, snapshot, supply, fastlane...
[16:53:58]: It seems that your Gem directory is not writable by your current User.
[16:53:58]: Fastlane would need sudo rights to update itself, however, running 'sudo fastlane' is not recommended.
[16:53:58]: If you still want to use this action, please read the Actions.md documentation on a guide how to set this up.
[16:53:58]: -------------------------------------------------
[16:53:58]: --- Step: Verifying required fastlane version ---
[16:53:58]: -------------------------------------------------
[16:53:58]: fastlane version valid
[16:53:58]: ------------------------------
[16:53:58]: --- Step: default_platform ---
[16:53:58]: ------------------------------
[16:53:58]: Driving the lane 'ios after_integration' 🚀
[16:53:58]: ----------------------------------
[16:53:58]: --- Step: get_info_plist_value ---
[16:53:58]: ----------------------------------
[16:53:58]: ----------------------------------
[16:53:58]: --- Step: get_info_plist_value ---
[16:53:58]: ----------------------------------
[16:53:58]: -------------------
[16:53:58]: --- Step: slack ---
[16:53:58]: -------------------
[16:53:59]: Successfully sent Slack notification

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | get_info_plist_value                | 0           |
| 5    | get_info_plist_value                | 0           |
| 6    | slack                               | 0           |
+------+-------------------------------------+-------------+

[16:53:59]: fastlane.tools finished successfully 🎉
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby

update_fastlane

fastlane_version "1.104.0"
default_platform :ios
platform :ios do

  before_all do
    ENV["SLACK_URL"] ||= "https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXXX/XXXXXXXXXXXXXXXXXXXX"
  end

  after_all do |lane|
  end

  error do |lane, exception|
    # reset_git_repo(force: true)
    slack(
      message: "Failed to build #{ENV['XL_TARGET']}: #{exception.message}",
      success: false
    )
  end

  # Custom lanes

  desc 'Do basic setup, as installing cocoapods dependencies and fetching profiles, before start integration.'
  lane :before_integration do
    plist_file = './MyApp/MyApp-Info.plist'

    increase_build_number(plist_file)

    # Run `pod install`
    cocoapods

  end

  lane :after_integration do
    plist_file = './MyApp/MyApp-Info.plist'

    tag_base_path = ENV['XL_TAG_BASE_PATH']
    tag_base_path = "#{tag_base_path}/" unless tag_base_path.nil? || tag_base_path == ''
    tag_link = ENV['XL_TAG_LINK']

    # Get the build and version numbers from the project's plist file
    build_number = get_info_plist_value(
      path: plist_file,
      key: 'CFBundleVersion',
    )
    version_number = get_info_plist_value(
      path: plist_file,
      key: 'CFBundleShortVersionString',
    )

    ENV['XL_VERSION_NUMBER'] = "#{version_number}"
    ENV['XL_BUILD_NUMBER'] = "#{build_number}"

    # TODO: upload to iTunes Connect

    slack(
      message: "#{ENV['XL_TARGET']} #{ENV['XL_VERSION_NUMBER']}.#{ENV['XL_BUILD_NUMBER']} successfully released",
    )
  end
  
end
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by fcamaster** [comment]
Hi, anybody?

**Comment by TKBurner** [comment]
@fcamaster Have you run `fastlane init` on this project yet? What directory are you running from? Can you run from the project directory? Thanks!

**Comment by fcamaster** [comment]
Thanks for the answer @TKBurner 

Have you run fastlane init on this project yet?  Yes
What directory are you running from?  Root of the project directory
Can you run from the project directory?  I did it. The log is on the issue above "Configuration files"

**Comment by TKBurner** [comment]
Can you run `ls` on that folder and share the output? It looks like the fastlane folder is not where it is expected. Thanks!

**Comment by fcamaster** [comment]
This is the output of **ls**:
```
Gemfile
Gemfile.lock
MyApp
MyApp.xcodeproj
MyApp.xcworkspace
Podfile
Podfile.lock
Pods
fastlane

```
**ls** of the fastline folder: 
```
Fastfile
README.md
report.xml
```

Gemfile just in case it helps:
```
source "https://rubygems.org"

gem "fastlane"
gem "cocoapods"
```

Note: I added the Gemfile later, before I was trying also without Gemfile. Same error.

**Comment by TKBurner** [comment]
@fcamaster What happens if you run fastlane init? Does it work after that setup or still fail? Are you using RVM? It seems like the fastlane bot might be using system ruby instead of the one you setup with _fastlane_.

**Comment by fcamaster** [comment]
I tried again, and seems it has been fixed with the latest version. Thanks!

**Comment by TKBurner** [comment]
@fcamaster Awesome! So glad to hear you are up and running 👍
