### ISSUE TITLE
No matching provisioning profiles found and can not create a new one because you enabled `readonly`

### ISSUE THREAD

**Issue by lukewakeford** [fastlane/fastlane#6320]
I am experiencing exactly the same issue as discussed here -> #1979
I am running Fastlane version 1.104.0

Here is my match code (which I run twice for two app ids) both for enterprise/InHouse certificates and profiles.

    match(
      type: "appstore",
      git_url: ENV['PROVISIONING_REPO'],
      username: ENV['PRODUCE_USERNAME'],
      app_identifier: ENV['PRODUCE_APP_IDENTIFIER'],
      readonly: true,
      verbose: true
    )

and here is the output

```
[16:34:19]: -------------------
[16:34:19]: --- Step: match ---
[16:34:19]: -------------------

+-----------------------+---------------------------------------------------------+
|                             Summary for match 0.8.0                             |
+-----------------------+---------------------------------------------------------+
| type                  | appstore                                                |
| git_url               | git@xxxxxxxxxxxxxxxx|
| username              | xxxxxxxxxxxxxxxx                                       |
| app_identifier        | xxxxxxxxxxxxxxxx                            |
| readonly              | true                                                    |
| verbose               | true                                                    |
| git_branch            | master                                                  |
| keychain_name         | login.keychain                                          |
| force                 | false                                                   |
| shallow_clone         | false                                                   |
| force_for_new_devices | false                                                   |
| skip_docs             | false                                                   |
+-----------------------+---------------------------------------------------------+

INFO [2016-09-28 16:34:19.67]: Cloning remote git repo...
INFO [2016-09-28 16:34:19.67]: $ GIT_TERMINAL_PROMPT=0 git clone 'xxxxxxxxxxxxxxxx' '/var/folders/jg/679wq2q95q780r5nxgxpt8yh0000gn/T/d20160928-60028-9bbkh8'
INFO [2016-09-28 16:34:19.67]: ▸ Cloning into '/var/folders/jg/679wq2q95q780r5nxgxpt8yh0000gn/T/d20160928-60028-9bbkh8'...
INFO [2016-09-28 16:34:20.83]: ▸ remote: Counting objects: 304, done.
INFO [2016-09-28 16:34:21.02]: ▸ remote: Compressing objects: 100% (295/295), done.
INFO [2016-09-28 16:34:21.42]: ▸ remote: Total 304 (delta 51), reused 0 (delta 0)
INFO [2016-09-28 16:34:21.42]: ▸ Receiving objects: 100% (304/304), 742.56 KiB | 0 bytes/s, done.
INFO [2016-09-28 16:34:21.43]: ▸ Resolving deltas: 100% (51/51), done.
INFO [2016-09-28 16:34:21.44]: ▸ Checking connectivity... done.
INFO [2016-09-28 16:34:21.47]: 🔓  Decrypted 'xxxxxxxxxxxxxxxx.cer'
INFO [2016-09-28 16:34:21.48]: 🔓  Decrypted 'xxxxxxxxxxxxxxxx.cer'
INFO [2016-09-28 16:34:21.49]: 🔓  Decrypted 'xxxxxxxxxxxxxxxx.p12'
INFO [2016-09-28 16:34:21.50]: 🔓  Decrypted 'xxxxxxxxxxxxxxxx.p12'
INFO [2016-09-28 16:34:21.50]: 🔓  Decrypted 'InHouse_com.xxxxxxxxxxxxxxxx.mobileprovision'
INFO [2016-09-28 16:34:21.51]: 🔓  Decrypted 'InHouse_com.xxxxxxxxxxxxxxxx.mobileprovision'
INFO [2016-09-28 16:34:21.52]: 🔓  Decrypted 'InHouse_com.xxxxxxxxxxxxxxxx.mobileprovision'
INFO [2016-09-28 16:34:21.54]: 🔓  Decrypted 'Development_com.xxxxxxxxxxxxxxxx.mobileprovision'
INFO [2016-09-28 16:34:21.55]: 🔓  Decrypted 'Development_com.xxxxxxxxxxxxxxxx.mobileprovision'
INFO [2016-09-28 16:34:21.55]: 🔓  Successfully decrypted certificates repo
INFO [2016-09-28 16:34:21.55]: Installing certificate...
INFO [2016-09-28 16:34:21.55]: $ security list-keychains -d user
INFO [2016-09-28 16:34:21.57]: ▸     "/Users/luke/Library/Keychains/login.keychain"
INFO [2016-09-28 16:34:21.57]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/luke/Library/Keychains/login.keychain
INFO [2016-09-28 16:34:21.62]: ▸ keychain: "/Users/luke/Library/Keychains/login.keychain"
INFO [2016-09-28 16:34:21.62]: ▸ version: 256
INFO [2016-09-28 16:34:21.62]: ▸ class: 0x80001000 
INFO [2016-09-28 16:34:21.62]: ▸ attributes:
INFO [2016-09-28 16:34:21.62]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-09-28 16:34:21.62]: ▸     "cenc"<uint32>=0x00000003 
INFO [2016-09-28 16:34:21.62]: ▸     "ctyp"<uint32>=0x00000001 
INFO [2016-09-28 16:34:21.62]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-09-28 16:34:21.62]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2016-09-28 16:34:21.62]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-09-28 16:34:21.62]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-09-28 16:34:21.62]: ▸     "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"
INFO [2016-09-28 16:34:21.62]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
DEBUG [2016-09-28 16:34:22.26]: Certificate 'xxxxxxxxxxxxxxxx.cer' is already installed on this machine
INFO [2016-09-28 16:34:22.26]: $ security import /var/folders/jg/679wq2q95q780r5nxgxpt8yh0000gn/T/d20160928-60028-9bbkh8/certs/distribution/WWC7P72FH7.p12 -k /Users/luke/Library/Keychains/login.keychain -T /usr/bin/codesign -T /usr/bin/security
security: SecKeychainItemImport: The specified item already exists in the keychain.
INFO [2016-09-28 16:34:22.33]: 🔒  Successfully encrypted certificates repo
WARN [2016-09-28 16:34:22.34]: Variable Dump:
INFO [2016-09-28 16:34:22.34]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios Beta"}
ERROR [2016-09-28 16:34:22.34]: No matching provisioning profiles found and can not create a new one because you enabled `readonly`
INFO [2016-09-28 16:34:22.34]: Successfully generated documentation at path '/Users/luke/xxxxxxxxxxxxxxxx/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 3           |
| 4    | unlock_keychain                     | 0           |
| 5    | match                               | 2           |
+------+-------------------------------------+-------------+

ERROR [2016-09-28 16:34:22.35]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] No matching provisioning profiles found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.8.0/lib/match/runner.rb:91:in `fetch_provisioning_profile'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.8.0/lib/match/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/actions/match.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:14:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

Match seems to want to update my profiles every time and then fails to find them since readonly is enabled.

**[!] No matching provisioning profiles found and can not create a new one because you enabled `readonly**

@bobbeat mentioned that it may be because Match is looking for profiles prepended with AppStore not InHouse.. is this a Match bug that can be fixed?

I have also tried using `MATCH_FORCE_ENTERPRISE="1"` - This makes no difference at all.

@KrauseFx I also couldn't find the new issue that you request be submitted, are you able to help with this?

**Comment by lukewakeford** [comment]
I have also just tried with the `type` set to `development` and it works absolutely fine in readonly.

**Comment by KrauseFx** [comment]
Sorry, enterprise profiles are currently not officially supported in _match_

**Comment by lukewakeford** [comment]
@KrauseFx Thanks for the response, any chance we can make the readonly flag work anyway? especially when forcing enterprise provisioning using `MATCH_FORCE_ENTERPRISE="1"` This would seriously help my workflow.

I need to do enterprise provisioning with Fastlane on a CI machine that doesn't doesn't have write access to repositories - neither do I want to give it write access for security using match.

**Comment by jlubeck** [comment]
Hey @lukewakeford, make sure you use type: enterprise and MATCH_FORCE_ENTERPRISE="1" when both creating and reading the certificate. Then it works.

**Comment by TKBurner** [comment]
@lukewakeford Hope the workaround solves this for you. Since we don't currently support this I'm going to close it. Feel free to add a +1 to the feature request.

**Comment by jlubeck** [comment]
hey @TKBurner, where is that feature request?

**Comment by TKBurner** [comment]
@lukewakeford We'll keep tracking this as a feature request. I think we are going to learn that enterprise certs are more common among our community than we think. Thanks!

**Comment by lukewakeford** [comment]
@TKBurner Which work around is that? - using the flag MATCH_FORCE_ENTERPRISE="1" makes no difference when i have match set to readonly - I have had to allow my CI machine git write permissions and set readonly to false when using enterprise provisioning.

@jlubeck Can you advise how to ensure the flag is used when reading and writing? I am just adding it above match in my Fastfile.

    MATCH_FORCE_ENTERPRISE="1"
    match(
      type: ENV['MATCH_TYPE'],
      git_url: ENV['PROVISIONING_REPO'],
      username: ENV['PRODUCE_USERNAME'],
      app_identifier: ENV['PRODUCE_APP_IDENTIFIER'],
      readonly: ENV['MATCH_READONLY']
    )

Also how do I +1 the feature request?

**Comment by TKBurner** [comment]
@lukewakeford Please bump: #5193
