### ISSUE TITLE
Modifing project file with Xcodeproj makes gym not able to find the project file

### ISSUE THREAD

**Issue by gcamp** [fastlane/fastlane#6330]
## New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm changing some things in the Xcode project before building (see Fastfile excerpt below), and after I save the project, gym is unable to find the project, as if the current path changed. However, it didn't change, as confirmed with `Dir.pwd` before and after the `project.save` command. 

If I set the project file manually, the error is 

```
/Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:59:in `chdir': [!] No such file or directory @ dir_chdir - ./fastlane/ (Errno::ENOENT)
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:59:in `rescue in execute'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:44:in `execute'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/gcamp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
	from /Users/gcamp/.rbenv/versions/2.2.3/bin/fastlane:23:in `load'
	from /Users/gcamp/.rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'
```

### Configuration Files

Fastfile:
```ruby
def update_transit_target
    require 'xcodeproj'

    project = Xcodeproj::Project.open("../#{XCODE_PROJ}")
    target = project.native_targets.find {|s| s.name == "TransitBeta" }

    yield(target)

    project.save

    gym
end
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by KrauseFx** [comment]
That's the full Fastfile?

**Comment by gcamp** [comment]
No it's only a excerpt. Here is the full Fastlane : 

```XCODE_VERSION = "8.0"

ARCHIVE_PATH = "./build/Transit.xcarchive"

XCODE_PROJ = "Transit.xcodeproj"
INFO_PLIST_PATH = "Transit-Info.plist"
WIDGET_INFO_PLIST_PATH = "Widget/Info.plist"
WATCH_INFO_PLIST_PATH = "Transit Watch/Info.plist"
WATCH_EXTENSION_INFO_PLIST_PATH = "Transit Watch Extension/Info.plist"

CONFIG_MODIFIED_FILES = ["Transit-Info.plist", "Widget/Info.plist", "Transit Watch/Info.plist", "Transit Watch Extension/Info.plist", "TransitTests/Info.plist", "Transit.entitlements",
   "Submodules/transitLib/configuration.json", "Resources/Images.xcassets", "Transit Watch/Assets.xcassets", XCODE_PROJ]

# This is the minimum version number required.
fastlane_version "1.103.0"

default_platform :ios

platform :ios do

  desc "Send a build to install.transitapp.com"
  lane :install do |options|
    context = build_from_config(config: options[:config], entreprise_build: true)

    info_plist_path = "#{ARCHIVE_PATH}/Products/Applications/Transit.app/Info.plist"

    sh("curl -F 'bundle_identifier=#{context[:bundle_id]}' \
     -F 'version=#{get_info_plist_value(key: "CFBundleVersion", path: info_plist_path)}' \
     -F 'version_short=#{get_info_plist_value(key: "CFBundleShortVersionString", path: info_plist_path)}' \
     -F 'title=#{options[:config_name]}' \
     -F 'os=ios' \
     -F 'app_file=@#{context[:ipa_path]}' \
     -F 'img_file=@#{app_path}/AppIcon60x60@3x.png' \
     -F 'install_string=Install #{options[:config_name]}' \
     https://install.transitapp.com/whitelabeling")
  end

  desc "Submit a new Beta Build to Apple TestFlight for internal use"
  lane :internal do |options|
    increase_version
    build_from_config(config: options[:config], entreprise_build: true)
  end

  desc "Submit a new Beta Build to Apple TestFlight and send to beta tester"
  lane :beta do
    increase_version
    build_from_config(config: options[:config], entreprise_build: false)
  end

  desc "Take the latest build and sent it to Testflight beta testers"
  lane :beta_submit do
    #pilot
  end

  desc "Deploy and submit a new version to the App Store"
  lane :release do
    update_fastlane

    increase_version
    build_from_config(config: options[:config], entreprise_build: false)
  end

  desc "Submit the latest build available on the App Store without uploading anything."
  lane :submit do
    deliver(force: true, skip_metadata: true, skip_binary_upload: true, skip_screenshots: true, submit_for_review: true)
  end

  ######### BUILD ############
  desc "Update build number to commit number"
  lane :build_from_config do |options|
    ensure_xcode_version(version: XCODE_VERSION)

    context = apply_config(options)

    ipa_path = gym(
    scheme: "TransitBeta-Shared",
    archive_path: ARCHIVE_PATH,
    output_directory: "./build/",
    xcargs: "TRANSIT_PRODUCT_NAME='#{context[:display_name]}'",
    output_name: context[:display_name],
    export_method: options[:entreprise_build] ? "enterprise" : "app-store",
    use_legacy_build_api: options[:entreprise_build],
    include_symbols: options[:entreprise_build]
    )

    restore

    context[:ipa_path] = ipa_path
    context
  end

  private_lane :increase_version do


    update_build_number
  end

  ######### APPLYING A CONFIG ############

  desc "Update data from config with name"
  desc "Will backup the config files before if it wasn't done before"
  desc "You can restore the backup after with restore_config_files"
  lane :apply_config do |options|
    if !File.exist?(CONFIG_MODIFIED_FILES[0])
      backup
    end

    build_number = number_of_commits
    increment_build_number(build_number: build_number)

    config_name = options[:config] ? options[:config] : "Transit"
    config_path = "../Submodules/transitLib/Transit-WhitelabelConfig/#{config_name}";
    ios_config_path = "#{config_path}/iOS/";
    team_id = "55F3M8Q72J"

    new_bundle_id = File.read("#{ios_config_path}bundle_identifier.txt")
    raise "bundle identifers should have 3 components, no more, no less" unless new_bundle_id.count('.') == 2
    if options[:entreprise_build]
      new_bundle_id = "#{new_bundle_id}-beta";

      ENV["MATCH_FORCE_ENTERPRISE"] = "1" #allow match to use entreprise account. See https://github.com/fastlane-old/match/issues/57
      team_id = "3C2289U2VJ"
      update_project_team(teamid: team_id, path: XCODE_PROJ)
    end

    update_bundle_id(new_bundle_id, team_id, options[:entreprise_build] ? "enterprise" : "appstore")
    
    set_info_plist_value(value: "production", key: "aps-environment", path: "Transit.entitlements")

    display_name = File.read("#{ios_config_path}display_name.txt")
    if !display_name.empty?
      set_info_plist_value(value: display_name, key: "CFBundleDisplayName", path: INFO_PLIST_PATH)
      url_scheme = display_name.downcase
      url_scheme.sub! ' ', '-'
      update_url_schemes(url_schemes: [url_scheme], path: INFO_PLIST_PATH)
      set_info_plist_value(value: url_scheme, key: "SPURLScheme", path: WIDGET_INFO_PLIST_PATH)
    else
      display_name = get_info_plist_value(key: "CFBundleDisplayName", path: INFO_PLIST_PATH)
    end

    FileUtils.cp("#{config_path}/configuration.json", "../Submodules/transitLib/configuration.json", { preserve: true })

    update_assets("../Resources/Images.xcassets", "#{ios_config_path}/Resources/")
    update_assets("../Transit Watch/Assets.xcassets", "#{ios_config_path}/Resources-watch/")

    if File.file?("#{ios_config_path}remove_watch.txt")
      remove_watch_from_project
    end

    if File.file?("#{ios_config_path}remove_widget.txt")
      remove_widget_from_project
    end

    { :config_name => "CAL", :display_name => "CAL", :bundle_id => "hello" } #Return config name for other lanes to use
  end

  lane :remove_widget do
    remove_watch_from_project
end

  def remove_watch_from_project
    update_transit_target do |target|
      target.dependencies.reject! { |dependency| dependency.target.name == "Transit Watch" }
      target.build_phases.reject! { |phase| phase.is_a?(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase) && phase.name == "Embed Watch Content"  }
    end
  end

  def remove_widget_from_project
    update_transit_target do |target|
      target.dependencies.reject! { |dependency| dependency.target.name == "NearbyWidget" }
      target.build_phases.reject! { |phase| phase.is_a?(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase) && phase.name == "Embed App Extensions"  }
    end
  end

  def update_transit_target
    require 'xcodeproj'

    project = Xcodeproj::Project.open("../#{XCODE_PROJ}")
    target = project.native_targets.find {|s| s.name == "TransitBeta" }

    yield(target)

    project.save
  end

  def update_assets(assets_path, replacements_path)
    Dir.glob("#{replacements_path}/*.imageset") do |imageset|
      replacement_imageset = "#{assets_path}/#{File.basename(imageset)}"
      FileUtils.rm_r(replacement_imageset)
      FileUtils.cp_r(imageset, replacement_imageset)
    end
  end

  def update_push_notif_cert(team_id, app_identifier, development)
    temp_folder = "temp_certs"
    FileUtils.rm_r(temp_folder, {force: true})
    FileUtils.rm_r("../Transit-Users", {force: true})
    FileUtils.mkdir(temp_folder)

    revoke_push_notif_cert_if_nessesary(team_id, app_identifier, development)

    pem(
    output_path: "fastlane/#{temp_folder}",
    team_id: team_id,
    app_identifier: app_identifier,
    development: development,
    new_profile: proc do |pem|
      UI.message("We have a new push certificate, updating in Transit-Users and in the server".yellow)

      pem_basename = File.basename(pem, '.*')
      cert_path = "fastlane/#{temp_folder}/#{app_identifier}-cert.pem"
      key_path = "fastlane/#{temp_folder}/#{app_identifier}-key.pem"
      FileUtils.cp("fastlane/#{temp_folder}/#{pem_basename}.pem", cert_path)
      sh("openssl pkcs12 -in fastlane/#{temp_folder}/#{pem_basename}.p12 -passin pass: -out #{key_path} -nodes")

      FileUtils.rm_r("fastlane/Transit-Users", {force: true})
      sh("git clone -q git@github.com:TransitApp/Transit-Users.git")
      destination_cert_path = "Transit-Users/certificates/#{File.basename(cert_path)}"
      if File.exist?(destination_cert_path)
        FileUtils.rm(destination_cert_path)
      end
      FileUtils.cp(cert_path, destination_cert_path)

      destination_key_path = "Transit-Users/certificates/#{File.basename(key_path)}"
      if File.exist?(destination_key_path)
        FileUtils.rm(destination_key_path)
      end
      FileUtils.cp(key_path, destination_key_path)

      UI.message("Commiting the changes to the Transit-Users repo".green)
      sh("cd Transit-Users && git add . && git commit -am 'Update certificate for #{app_identifier}' && git push && cd ..")

      #Sync the new content of certificates to the servers
      sh("rsync -avz -e ssh Transit-Users/certificates root@staging.transitapp.com:/var/transit-users/current/")
      sh("rsync -avz -e ssh Transit-Users/certificates deploy@api.transitapp.com:/home/deploy/www/transit-users/current/")

      FileUtils.rm_r("Transit-Users")
    end
    )

    FileUtils.rm_r(temp_folder)
  end

  def revoke_push_notif_cert_if_nessesary(team_id, app_identifier, development)
    # Check if we have two push certificates, if we do revoke the oldest
    require 'spaceship'

    Spaceship.login
    Spaceship.client.team_id = team_id

    if development
      certificates = Spaceship.certificate.development_push.all
    else
      certificates = Spaceship.certificate.production_push.all
    end
    certificates.select!{ |cert| cert.name == app_identifier }

    if certificates.length == 2 #we have two certs, revoke the oldest
      UI.important("Revoking an old certificate because we have two with the same id".yellow)
      certificates.sort! { |a,b| a.created <=> b.created }
      certificates.each { |cert| puts "#{cert.name} #{cert.id} #{cert.created}"}
      certificates[0].revoke!
      UI.message("Certificate with ID: #{certificates[1].id} revoked".green)
    end
  end

  def update_bundle_id(new_bundle_id, team_id, profile_type)
    widget_bundle_id = "#{new_bundle_id}.Widget"
    watch_bundle_id = "#{new_bundle_id}.watchkitapp"
    watch_extenstion_bundle_id = "#{new_bundle_id}.watchkitapp.watchkitextension"
    group_id = "group.#{new_bundle_id}"

    #update the info plists and entitlements
    update_app_identifier(app_identifier: new_bundle_id, plist_path: INFO_PLIST_PATH)
    update_app_identifier(app_identifier: widget_bundle_id, plist_path: WIDGET_INFO_PLIST_PATH)
    update_app_identifier(app_identifier: watch_bundle_id, plist_path: WATCH_INFO_PLIST_PATH)
    set_info_plist_value(value: new_bundle_id, key: "WKCompanionAppBundleIdentifier", path: WATCH_INFO_PLIST_PATH)
    update_app_identifier(app_identifier: watch_extenstion_bundle_id, plist_path: WATCH_EXTENSION_INFO_PLIST_PATH)
    update_info_plist(plist_path: WATCH_EXTENSION_INFO_PLIST_PATH,
      block: lambda { |plist|
        plist['NSExtension']['NSExtensionAttributes']['WKAppBundleIdentifier'] = watch_bundle_id
      })
    update_app_group_identifiers(entitlements_file: 'Transit.entitlements', app_group_identifiers: [group_id])

    #add capabilities to app ID. Produce doesn't have complete fastlane integration, use sh instead https://github.com/fastlane-old/produce/issues/81
    produce(skip_itc: true, team_id: team_id, app_identifier: new_bundle_id, app_name: new_bundle_id)
    produce(skip_itc: true, team_id: team_id, app_identifier: widget_bundle_id, app_name: widget_bundle_id)
    produce(skip_itc: true, team_id: team_id, app_identifier: watch_bundle_id, app_name: watch_bundle_id)
    produce(skip_itc: true, team_id: team_id, app_identifier: watch_extenstion_bundle_id, app_name: watch_extenstion_bundle_id)
    sh "produce enable_services -a #{new_bundle_id} --team_id #{team_id} --push-notification --app-group"
    sh "produce enable_services -a #{widget_bundle_id} --team_id #{team_id} --app-group"
    sh "produce group --team_id #{team_id} --group_identifier #{group_id} --group_name '#{group_id} app group'" #create new app group
    sh "produce associate_group -a #{new_bundle_id} --team_id #{team_id} #{group_id}"
    sh "produce associate_group -a #{widget_bundle_id} --team_id #{team_id} #{group_id}"

    update_push_notif_cert(team_id, new_bundle_id, false) #prod certs

    #update prov profile
    match(type: profile_type, git_branch: team_id, team_id: team_id, app_identifier: new_bundle_id)
    ENV["transit.app_profile"] = ENV["sigh_#{new_bundle_id}_#{profile_type}_profile-name"]
    match(type: profile_type, git_branch: team_id, team_id: team_id, app_identifier: widget_bundle_id)
    ENV["transit.widget_profile"] = ENV["sigh_#{widget_bundle_id}_#{profile_type}_profile-name"]
    match(type: profile_type, git_branch: team_id, team_id: team_id, app_identifier: watch_bundle_id)
    ENV["transit.watch_profile"] = ENV["sigh_#{watch_bundle_id}_#{profile_type}_profile-name"]
    match(type: profile_type, git_branch: team_id, team_id: team_id, app_identifier: watch_extenstion_bundle_id)
    ENV["transit.watchextension_profile"] = ENV["sigh_#{watch_extenstion_bundle_id}_#{profile_type}_profile-name"]
  end

  desc "Backup the files modified by applying a config"
  lane :backup do
    CONFIG_MODIFIED_FILES.each { |x| FileUtils.copy_entry("../#{x}", "../#{x}.back", { preserve: true, remove_destination: true }) }
  end

  desc "Restore the files modified by applying a config"
  lane :restore do
    CONFIG_MODIFIED_FILES.each { |x|
      backup_path = "../#{x}.back"
      if File.exist?(backup_path)
        FileUtils.copy_entry(backup_path, "../#{x}", { preserve: true, remove_destination: true })
        FileUtils.rm_r(backup_path)
      end
    }
  end

  error do |lane|
    restore #Restore files after a failure
  end
end
```

**Comment by gcamp** [comment]
Problem happens when I run either ```remove_watch_from_project``` or ```remove_widget_from_project```

**Comment by TKBurner** [comment]
@gcamp Are you using RVM or system ruby?

**Comment by gcamp** [comment]
I use rbenv

**Comment by idomizrachi** [comment]
I'm also having the same issue.
Will update if I find a solution for this

**Comment by rcgilbert** [comment]
I'm having the same issue as well.  Using RVM.

**Comment by TKBurner** [comment]
@gcamp @idomizrachi @rcgilbert Are you running fastlane from your project folder or the fastlane folder. It looks like the pwd might being changed in your lane and that's causing the issue. I want to get to the bottom of this. Thanks!

**Comment by rcgilbert** [comment]
@TKBurner I was seeing this issue running fastlane from both my project folder and fastlane folder.  The latest release of fastlane(v1.105.0) seems to have fixed the problem for me though.

**Comment by gcamp** [comment]
@TKBurner I usually use fastlane from my project folder but the same problem is happening when running from the fastlane project. 1.105.0 didn't fixed it for me. 

FYI I tried to see if `Dir.pwd` was changing and it doesn't. Also tried to change manually the current directory and it didn't work.

**Comment by idomizrachi** [comment]
@TKBurner I see the problem from both the project and fastlane path.
Also checked the working-dir and it doesn't change.

These are the lines in my fastfile that use the xcodeproj: ("Pod" is a private library that remove a build phase from the project)
puts "Remove \"Embed Pods Frameworks\" from ShareExtensionTarget"
puts "#{Dir.pwd}"
Pod.remove_frameworks("../Project.xcodeproj", "ShareExtensionTarget") #Remove "Embed Pods Frameworks" from Share Extension. relative to /fastlane path
puts "After - #{Dir.pwd}"

Gym runs if I comment the "Pod.remove_frameworks(...)" command

**Comment by TKBurner** [comment]
@idomizrachi @gcamp Sorry to hear that you are still running into this. This seems like it is an issue with gym. I looped in the core team so they can take a look. Thanks!

**Comment by mfurtak** [comment]
Hi all, I did some exploration to try to reproduce. Here's the `Fastfile` I used.

```ruby
fastlane_version "1.103.0"

default_platform :ios

XCODE_PROJ = 'SingleView.xcodeproj'.freeze
CONFIG_MODIFIED_FILES = [XCODE_PROJ].freeze

def do_xcodeproj
  require 'xcodeproj'

  project = Xcodeproj::Project.open("../#{XCODE_PROJ}")
  target = project.native_targets.find {|s| s.name == "SingleView" }

  yield(target)

  project.save
end

platform :ios do
  desc "Backup the files modified by applying a config"
  lane :backup do
    CONFIG_MODIFIED_FILES.each do |x|
      FileUtils.copy_entry("../#{x}", "../#{x}.back", { preserve: true, remove_destination: true })
    end
  end

  desc "Restore the files modified by applying a config"
  lane :restore do
    CONFIG_MODIFIED_FILES.each do |x|
      backup_path = "../#{x}.back"
      if File.exist?(backup_path)
        FileUtils.copy_entry(backup_path, "../#{x}", { preserve: true, remove_destination: true })
        FileUtils.rm_r(backup_path)
      end
    end
  end

  lane :apply_config do |options|
    if !File.exist?(CONFIG_MODIFIED_FILES[0])
      backup
    end

    do_xcodeproj do |target|
      target.build_phases.reject! { |phase| phase.is_a?(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase) }
    end
  end

  lane :build do
    apply_config

    match(readonly: true)
    gym(scheme: 'SingleView', export_method: 'development')

    restore
  end

  error do |lane, exception|
    restore
  end
end
```

I wasn't able to reproduce the problem when running that `fastlane build` on my test project.

What would be really 💯 would be if someone could share a small, self-contained test project that exhibits the problem. 👍

Thanks!

**Comment by MikeBlair** [comment]
@gcamp they've released a new version of xcodeproj which fixed a similar issue for me.  It is in 1.3.2: https://github.com/CocoaPods/Xcodeproj/releases/tag/1.3.2

**Comment by gcamp** [comment]
@MikeBlair Indeed xcodeproj 1.3.2 seems to have fixed it. thanks 

@mfurtak Sorry you had to took the time to look into it. Thanks for your hard work!

**Comment by mfurtak** [comment]
@gcamp No worries at all - glad you're up and running! 👍
