### ISSUE TITLE
Sigh resign creates the wrong application bundle identifier if the original bundle id is a substring of the new bundle id using the app entitlements

### ISSUE THREAD

**Issue by mdubs** [fastlane/fastlane#6331]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When running the resign script with use_app_entitlements option (to resign from com.company.application to com.company.application-enterprise), the entitlements are extracted out of the provisioning profile (in our case it gives an application-identifier value of

```
        <key>application-identifier</key>
        <string>1234567890.com.company.application-enterprise</string>
```

after going through the entitlements to migrate, it then additionally changes all instances of the old identifier (com.company.application) to the new identifier.  This results in the entitlements file having an application-identifier of com.company.application-enterprise-enterprise and it can't be installed.
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
Note 
Appfile

``` ruby
app_identifier "com.company.application" # The bundle identifier of your app
```

Fastfile

``` ruby
  lane :create_enterprise do
    sigh(
      username: "{REDACTED APP STORE USERNAME}",
      skip_certificate_verification: true
    )

    xcarchive_path = "#{project_directory}/temp/application.xcarchive"
    compressed_xcarchive_path = "#{project_directory}/output/application.xcarchive.tar.gz"
    gym(
      archive_path: xcarchive_path
    )

    app_id = "com.company.application-enterprise"
    sigh(
      app_identifier: app_id,
      username: "{REDACTED ENTERPRISE USERNAME}",
      skip_certificate_verification: true
    )
    resign(
      signing_identity: "iPhone Distribution: {REDACTED}",
      use_app_entitlements: true
    )
  end
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0
sigh 1.11.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by mdubs** [comment]
Thanks fastlane-bot but I believe this is an issue with the resign script.  I have a solution that works for us but I can't run the tests.  I've run `bundle install` in the fastlane directory but then it can't load rspec
```bash
macbookpro-4b18:fastlane michael$ bundle show rspec
/Library/Ruby/Gems/2.0.0/gems/rspec-3.1.0
macbookpro-4b18:fastlane michael$ bundle exec rspec
bundler: failed to load command: rspec (/usr/local/bin/rspec)
LoadError: cannot load such file -- spec_helper
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `require'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `block in requires='
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `each'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `requires='
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:103:in `block in process_options_into'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `each'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `process_options_into'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:22:in `configure'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:95:in `setup'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
  /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
  /usr/local/bin/rspec:23:in `load'
  /usr/local/bin/rspec:23:in `<top (required)>'
```
```bash
macbookpro-4b18:fastlane michael$ bundle exec rake test_all

====================
| Testing fastlane |
====================
bundle exec rspec --format documentation --format j --out rspec_logs.json
Could not find gem 'fastlane-plugin-clubmate' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
[[FAILURE]] with repo 'fastlane' due to

Command failed with status (7): [bundle exec rspec --format documentation -...]


=========================
| Testing fastlane_core |
=========================
bundle exec rspec --format documentation --format j --out rspec_logs.json
Could not find gem 'fastlane-plugin-clubmate' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
[[FAILURE]] with repo 'fastlane_core' due to

Command failed with status (7): [bundle exec rspec --format documentation -...]


===================
| Testing deliver |
===================
bundle exec rspec --format documentation --format j --out rspec_logs.json
Could not find gem 'fastlane-plugin-clubmate' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
[[FAILURE]] with repo 'deliver' due to

Command failed with status (7): [bundle exec rspec --format documentation -...]


====================
| Testing snapshot |
====================
bundle exec rspec --format documentation --format j --out rspec_logs.json
```

**Comment by TKBurner** [comment]
@mdubs Looks like your gemfile has an issue. Can you make sure you are including your plugin in it? https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#readme
