### ISSUE TITLE
Gym always fails with "Check Dependencies" error 65 but xcodebuild command succeeds

### ISSUE THREAD

**Issue by mcocaro** [fastlane/fastlane#6353]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When using fastlane to build the app, Gym will always fail with error:

▸ Check Dependencies
** ARCHIVE FAILED **

The following build commands failed:
Check dependencies
(1 failure)
ERROR [2016-09-30 14:16:05.45]: Exit status: 65

However, when I execute the xcodebuild command separately, it SUCCEEDS to build the archive correctly.

##### Complete output when running fastlane, including the stack trace and command used

```
/Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Error building the application - see the log above (FastlaneCore::Interface::FastlaneError)
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/gym-1.10.0/lib/gym/error_handler.rb:53:in `handle_build_error'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/gym-1.10.0/lib/gym/runner.rb:101:in `block in build_app'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane_core-0.52.0/lib/fastlane_core/command_executor.rb:88:in `execute'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/gym-1.10.0/lib/gym/runner.rb:97:in `build_app'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/gym-1.10.0/lib/gym/runner.rb:12:in `run'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/gym-1.10.0/lib/gym/manager.rb:10:in `work'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `chdir'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:121:in `block (2 levels) in parsing_binding'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/martin/.rvm/gems/ruby-2.3.1/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
	from /Users/martin/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
	from /Users/martin/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>'
	from /Users/martin/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/martin/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :build do

    cocoapods

    increment_build_number # version bump

    match(
      app_identifier: "xxxxxxt", 
      type:"development"
    )

    gym(
      scheme: "xxx-Test",
      use_legacy_build_api: true,
      configuration: "Debug"
    ) # Build your app - more options available

  end
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.104.0, XCode 8.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by nicnocquee** [comment]
I also just got this. From other issues, check the log file in `~/Library/Logs/gym/<app_name>.log`. Mine was provisioning profile problem

**Comment by mcocaro** [comment]
Thanks @nicnocquee ! Found out the issue was the Pod dependencies didn't have the SWIFT_VERSION setting so ended up putting it in the `pod install` post-install script.

**Comment by mortenholmgaard** [comment]
@KrauseFx pleases add this info `~/Library/Logs/gym/<app_name>.log` in the error messages gym/fastlane is showing.
