### ISSUE TITLE
Match calls cert with the wrong keychain

### ISSUE THREAD

**Issue by iCarambaa** [fastlane/fastlane#6375]
### New Issue Checklist
- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I have a separate keychain called "buildserver.keychain" that I use with match. I ran match nuke and wanted to recreate my certificates afterward and notices in the verbose output that match runs cert to create a new code signing identity but uses the login.keychain here. Possible workaround is to set the cert keychain using an environment variable.

If you confirm this issue I can work on a PR.
##### Complete output when running fastlane, including the stack trace and command used

```
11:39:29 +-----------------------+---------------------------------------+
11:39:29 |                    [32mSummary for match 0.8.0[0m                    |
11:39:29 +-----------------------+---------------------------------------+
11:39:29 | git_branch            | xxx                    |
11:39:29 | app_identifier        | xxx             |
11:39:29 | force_for_new_devices | true                                  |
11:39:29 | username              | xxx                    |
11:39:29 | verbose               | true                                  |
11:39:29 | type                  | appstore                              |
11:39:29 | git_url               | xxx |
11:39:29 | keychain_name         | buildserver.keychain                  |
11:39:29 | readonly              | false                                 |
11:39:29 | force                 | false                                 |
11:39:29 | shallow_clone         | false                                 |
11:39:29 | skip_docs             | false                                 |
11:39:29 +-----------------------+---------------------------------------+
11:39:29 
11:39:29 INFO [2016-10-04 11:39:29.48]: Cloning remote git repo...
11:39:29 INFO [2016-10-04 11:39:29.48]: [4m[36m$ GIT_TERMINAL_PROMPT=0 git clone 'xxx' '/var/folders/t1/lycltk3d5xv8lkmsqcwfr_9m00007x/T/d20161004-16740-dhmqrv'[0m[0m
11:39:29 INFO [2016-10-04 11:39:29.49]: ▸ [35mCloning into '/var/folders/t1/lycltk3d5xv8lkmsqcwfr_9m00007x/T/d20161004-16740-dhmqrv'...[0m
11:39:30 INFO [2016-10-04 11:39:30.66]: ▸ [35mremote: Counting objects: 253, done.[0m
11:39:30 INFO [2016-10-04 11:39:30.74]: ▸ [35mremote: Compressing objects: 100% (66/66), done.[0m
11:39:31 INFO [2016-10-04 11:39:31.26]: ▸ [35mremote: Total 253 (delta 6), reused 0 (delta 0), pack-reused 178[0m
11:39:31 INFO [2016-10-04 11:39:31.26]: ▸ [35mReceiving objects: 100% (253/253), 935.46 KiB | 0 bytes/s, done.[0m
11:39:31 INFO [2016-10-04 11:39:31.26]: ▸ [35mResolving deltas: 100% (27/27), done.[0m
11:39:31 INFO [2016-10-04 11:39:31.36]: ▸ [35mChecking connectivity... done.[0m
11:39:31 INFO [2016-10-04 11:39:31.37]: [4m[36m$ git branch --list origin/xxx --no-color -r[0m[0m
11:39:31 INFO [2016-10-04 11:39:31.37]: ▸ [35morigin/xxx[0m
11:39:31 INFO [2016-10-04 11:39:31.37]: Checking out branch xxx...
11:39:31 INFO [2016-10-04 11:39:31.37]: [4m[36m$ git checkout xxx[0m[0m
11:39:31 INFO [2016-10-04 11:39:31.39]: ▸ [35mBranch xxx set up to track remote branch xxx from origin.[0m
11:39:31 INFO [2016-10-04 11:39:31.39]: ▸ [35mSwitched to a new branch 'xxx'[0m
11:39:31 INFO [2016-10-04 11:39:31.39]: [32m🔓  Successfully decrypted certificates repo[0m
11:39:31 INFO [2016-10-04 11:39:31.42]: Verifying that the certificate and profile are still valid on the Dev Portal...
11:39:33 WARN [2016-10-04 11:39:33.60]: [33mCouldn't find a valid code signing identity in the git repo for distribution... creating one for you now[0m
11:39:33 
11:39:33 +---------------+--------------------------------------------------------+
11:39:33 |                         [32mSummary for cert 1.4.2[0m                         |
11:39:33 +---------------+--------------------------------------------------------+
11:39:33 | development   | false                                                  |
11:39:33 | force         | true                                                   |
11:39:33 | username      | xxx                                     |
11:39:33 | keychain_path | /Users/Shared/Jenkins/Library/Keychains/login.keychain |
11:39:33 +---------------+--------------------------------------------------------+
11:39:33 
11:39:33 INFO [2016-10-04 11:39:33.66]: Starting login with user 'xxx'
11:39:35 INFO [2016-10-04 11:39:35.17]: Successfully logged in
11:39:38 INFO [2016-10-04 11:39:38.58]: [4m[36m$ security import /var/folders/t1/lycltk3d5xv8lkmsqcwfr_9m00007x/T/d20161004-16740-dhmqrv/certs/distribution/2CLZY584MR.p12 -k '/Users/Shared/Jenkins/Library/Keychains/login.keychain' -T /usr/bin/codesign -T /usr/bin/security[0m[0m
11:39:38 security: SecKeychainItemImport: User interaction is not allowed.
11:39:38 INFO [2016-10-04 11:39:38.63]: [4m[36m$ security import /var/folders/t1/lycltk3d5xv8lkmsqcwfr_9m00007x/T/d20161004-16740-dhmqrv/certs/distribution/2CLZY584MR.cer -k '/Users/Shared/Jenkins/Library/Keychains/login.keychain' -T /usr/bin/codesign -T /usr/bin/security[0m[0m
11:39:38 INFO [2016-10-04 11:39:38.72]: ▸ [35m1 certificate imported.[0m
11:39:38 INFO [2016-10-04 11:39:38.72]: [32mSuccessfully generated 2CLZY584MR which was imported to the local machine.[0m
11:39:38 INFO [2016-10-04 11:39:38.72]: [4m[36m$ security list-keychains -d user[0m[0m
11:39:38 INFO [2016-10-04 11:39:38.73]: ▸ [35m    "/Users/Shared/Jenkins/Library/Keychains/buildserver.keychain"[0m
11:39:38 INFO [2016-10-04 11:39:38.73]: ▸ [35m    "/Users/Shared/Jenkins/Library/Keychains/login.keychain"[0m
11:39:38 INFO [2016-10-04 11:39:38.73]: [4m[36m$ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/Shared/Jenkins/Library/Keychains/buildserver.keychain[0m[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35mkeychain: "/Users/Shared/Jenkins/Library/Keychains/buildserver.keychain"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35mversion: 256[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35mclass: 0x80001000 [0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35mattributes:[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "cenc"<uint32>=0x00000003 [0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "ctyp"<uint32>=0x00000001 [0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"[0m
11:39:39 INFO [2016-10-04 11:39:39.18]: Verifying the certificate is properly installed locally...
11:39:39 INFO [2016-10-04 11:39:39.18]: [32m🔒  Successfully encrypted certificates repo[0m
11:39:39 
11:39:39 Looking for related GitHub issues on fastlane/fastlane...
11:39:39 Search query: Could not find the newly generated certificate installed
11:39:39 
11:39:39 URL: https://api.github.com/search/issues?q=Could%20not%20find%20the%20newly%20generated%20certificate%20installed+repo:fastlane/fastlane
11:39:39 ➡️  [33mCould not find the newly generated certificate installed[0m
11:39:39    https://github.com/fastlane/fastlane/issues/3098 [[32mclosed[0m] 0 💬
11:39:39    2 weeks ago
11:39:39 
11:39:39 ➡️  [33mCould not find the newly generated certificate installed[0m
11:39:39    https://github.com/fastlane/fastlane/issues/3099 [[32mclosed[0m] 3 💬
11:39:39    2 weeks ago
11:39:39 
11:39:39 ➡️  [33mCould not find the newly generated certificate installed[0m
11:39:39    https://github.com/fastlane/fastlane/issues/3419 [[32mclosed[0m] 24 💬
11:39:39    2 weeks ago
11:39:39 
11:39:39 and 10 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20find%20the%20newly%20generated%20certificate%20installed&type=Issues&utf8=✓
11:39:39 /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [31m[!] Could not find the newly generated certificate installed[0m (FastlaneCore::Interface::FastlaneError)
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cert-1.4.2/lib/cert/runner.rb:10:in `launch'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/generator.rb:19:in `generate_certificate'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/runner.rb:55:in `fetch_certificate'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/runner.rb:17:in `run'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/commands_generator.rb:53:in `block (3 levels) in run'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/commands_generator.rb:119:in `run'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/commands_generator.rb:12:in `start'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/bin/match:6:in `<top (required)>'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/bin/match:22:in `load'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/bin/match:22:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Did not run in a Fastfile but from the command line.

```
match appstore --git_branch xxx -a xy -u username --force_for_new_devices --verbose
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by KrauseFx** [comment]
Nice catch, that definitely is an error that should be fixed. Can you prepare a PR for this? 👍
