### ISSUE TITLE
Pilot Upload Failure undefined method `builds' for nil:NilClass

### ISSUE THREAD

**Issue by wkwyatt** [fastlane/fastlane#6381]
### New Issue Checklist

- [x] Updated fastlane to the latest version
fastlane 1.104.0
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Pilot Upload Failure undefined method `builds' for nil:NilClass

##### Complete output when running fastlane, including the stack trace and command used
`fastlane beta`

```
[14:32:37]: Variable Dump:
[14:32:37]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :SIGH_PROFILE_PATH=>"/Users/wkwyatt/Desktop/Narwhal/GMP/gmp-app/client_ionic_app/platforms/ios/AppStore_com.coke.gmp.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/wkwyatt/Desktop/Narwhal/GMP/gmp-app/client_ionic_app/platforms/ios/AppStore_com.coke.gmp.mobileprovision"], :SIGH_UDID=>"b0c41025-d392-4c13-8465-b3b35b59b292", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/wkwyatt/Desktop/Narwhal/GMP/gmp-app/client_ionic_app/platforms/ios/GMP.ipa", :DSYM_OUTPUT_PATH=>"/Users/wkwyatt/Desktop/Narwhal/GMP/gmp-app/client_ionic_app/platforms/ios/GMP.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/wkwyatt/Library/Developer/Xcode/Archives/2016-10-04/GMP 2016-10-04 14.28.37.xcarchive"}
[14:32:37]: undefined method `builds' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | sigh                                | 7           |
| 4    | gym                                 | 77          |
| 5    | pilot                               | 171         |
+------+-------------------------------------+-------------+

[14:32:37]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  pilot upload failure undefined method `builds' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/6267 [closed] 9 💬
   an hour ago

➡️  Undefined method `exitstatus' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/2077 [closed] 6 💬
   2 weeks ago

➡️  Undefined method `strip' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/1811 [closed] 8 💬
   2 weeks ago

and 30 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60builds'%20for%20nil&type=Issues&utf8=✓
/Users/wkwyatt/.rvm/gems/ruby-2.2.3@global/gems/pilot-1.10.0/lib/pilot/build_manager.rb:142:in `wait_for_processing_build': [!] undefined method `builds' for nil:NilClass (NoMethodError)
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3@global/gems/pilot-1.10.0/lib/pilot/build_manager.rb:34:in `upload'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `chdir'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:37:in `block (2 levels) in parsing_binding'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `load'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `<main>'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/wkwyatt/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    # increment_build_number()
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    sigh
    gym(scheme: "GMP") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "GMP") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by wkwyatt** [comment]
I have read over the code signing troubleshooting guide.  It doesn't seem to be the issue.

**Comment by wkwyatt** [comment]
I did a `sudo gem install pilot` for the update but now pilot builds seems to not run at all.

**Comment by KrauseFx** [comment]
The pull request is merged, however this also requires a new release, which we'll do first thing in the morning tomorrow 👍 If you know a bit about ruby, you can install the gem from the GitHub source too in the mean-time

**Comment by wkwyatt** [comment]
Thank you!  You're Awesome!

**Comment by wkwyatt** [comment]
I'm not sure how to install from GitHub, but are there notifications I can sign up for so that I know when the new releases happen?  Thx

**Comment by KrauseFx** [comment]
@wkwyatt Best is to follow us on Twitter [@fastlanetools](https://twitter.com/fastlanetools) 👍
