### ISSUE TITLE
uninitialized constant Fastlane::Actions::SharedValues::GYM_SCHEME

### ISSUE THREAD

**Issue by MaximusMcCann** [fastlane/fastlane#6465]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

How do I access the shared values?  Want to access GYM_SCHEME in another lane

##### Complete output when running fastlane, including the stack trace and command used

```
Fastfile:8:in `block (2 levels) in parsing_binding': [!] uninitialized constant Fastlane::Actions::SharedValues::GYM_SCHEME (NameError)
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:165:in `try_switch_to_lane'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:120:in `trigger_action_by_name'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:19:in `block (2 levels) in parsing_binding'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/commands_generator.rb:244:in `run'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/bin/fastlane:5:in `<top (required)>'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/bin/fastlane:22:in `load'
	from /Users/maximusmccann/.rbenv/versions/2.3.1/bin/fastlane:22:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.105.0"

default_platform :ios

platform :ios do
  desc "Delete ipa and dSYMs for failed builds"
  private_lane :test2 do |options|
    _scheme = lane_context[Actions::SharedValues::GYM_SCHEME]
    put "#{_scheme}"
  end

  desc "Test fastlane stuff"
  lane :test do
    gym
    test2
  end
end

```

### Environment

fastlane version (run `fastlane -v`): 1.105.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by KrauseFx** [comment]
There is no `GYM_SCHEME` variable. You can't access this, sorry

**Comment by KrauseFx** [comment]
What are you trying to do exactly?

**Comment by MaximusMcCann** [comment]
After compiling and running some other scripts, am looking to do some folder/file cleaning.  Was hoping to not have to pass the scheme around a bunch and just pull it in from whatever scheme was last use to build.

```
  desc "Archive ipa and zip files created in build process by scheme"
  private_lane :archive_build_files_for_scheme do |options|
	_scheme = options[:scheme] ? options[:scheme] : lane_context[Actions::SharedValues::GYM_SCHEME]
	_dirname = File.expand_path('../buildArchive') 
	FileUtils.mkdir_p(_dirname) unless File.directory?(_dirname)

	_date = DateTime.parse(Time.now.to_s).strftime("%Y-%m-%d-%H:%M_")

	_filename = "#{_scheme}.ipa"
	_oldPath =  "../#{_filename}"
	_newPath = "#{_dirname}/#{_date}#{_filename}"

	if File.exist?(_oldPath)
		FileUtils.mv(_oldPath, _newPath)
	end

	_filename = "#{_scheme}.app.dSYM.zip"
	_oldPath =  "../#{_filename}"
	_newPath = "#{_dirname}/#{_date}#{_filename}"

	if File.exist?(_oldPath)
		FileUtils.mv(_oldPath, _newPath)
	end
  end
```

Feels like I don't quite understand what the `Env Var` column is for when running `fastlane action <action>`.  I was thinking after the action was run it would set those `Env Var`s

Cheers

**Comment by KrauseFx** [comment]
The environment variable is used to set the value, but you can't receive it using that, sorry. Currently there is no way to get the used scheme from _gym_

**Comment by MaximusMcCann** [comment]
All good.  Appreciate all you work on Fastlane 👍
