### ISSUE TITLE
Codesigning "No applicable devices found"

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#6495]
Called [gym](https://fastlane.tools/gym) using
```ruby
gym(scheme: "Themoji", export_method: "ad-hoc", export_team_id: "ABC...")
```

Used OS: macOS Sierra
Used Xcode: 8.0

Used plist file

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>ad-hoc</string>
	<key>teamID</key>
	<string>N8X438SEU2</string>
</dict>
</plist>
```

Generated export command (new lines for better readability)
```
/usr/bin/xcrun /Library/Ruby/Gems/2.0.0/gems/gym-1.11.0/lib/assets/wrap_xcodebuild/xcbuild-safe.sh 
-exportArchive 
-exportOptionsPlist '/var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/gym_config20161010-7967-asw94y.plist' 
-archivePath /Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji\ 2016-10-10\ 20.04.52.xcarchive 
-exportPath '/var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/gym_output20161010-7967-y1r6se' 
```

simplified export command

```
/usr/bin/xcrun /Library/Ruby/Gems/2.0.0/gems/gym-1.11.0/lib/assets/wrap_xcodebuild/xcbuild-safe.sh 
-exportArchive 
-exportOptionsPlist '/tmp/my.plist' 
-archivePath /Users/.../something.xcarchive 
-exportPath '/tmp/output' 
```

**Update 1**
The error message is generated by the bundled `ipatool`:

```
2016-10-11 03:05:13 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:15:in `require': cannot load such file -- cfpropertylist (LoadError)
```

so it's related to the third party dependency [CFPropertyList](https://github.com/ckruse/CFPropertyList). Since Xcode doesn't make use of bundler, it seems like the `ipatool` has a problem loading the third party dependency, depending on the Ruby environment.

**Update 2**
We already have [xcodebuild-safe.sh](https://github.com/fastlane/fastlane/blob/master/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh) which should unset the environment variables of rbenv and rvm during the build process, however some people still run into the `cfpropertylist` issue, even with the stock macOS installation.

**Update 3**
Even though I'm using stock Ruby on this fresh MacBook with Sierra, I'm using bundler. The `cfpropertylist` gem is not bundled with _fastlane_ and doesn't get shipped with Xcode (which it should), instead of relying on the user's machine.

**Update 4**
It seems like `CFPropertyList` is not the only gem that Xcode needs:

- [CFPropertyList](https://github.com/ckruse/CFPropertyList)
- [sqlite3](https://github.com/sparklemotion/sqlite3-ruby)

**Update 5**
Adding those 2 gems as a dependency actually fixes the problem. I'll see if there is a way to unset the bundler environment for this external script, so that we don't have to add additional dependencies to _fastlane_

There are [15 similar issues](https://github.com/fastlane/fastlane/search?q=cfpropertylist&type=Issues&utf8=%E2%9C%93), let's see if somebody found a solution for this already.

[This one](https://github.com/fastlane/fastlane/issues/3193) seems definitely relevant, and has a lot of discussion about this problem.

**Update 6**
`Bundler.with_clean_env` and similar didn't work, however unsetting the bundler environment variables like we already do for rbenv and rvm setups solves the problem:

**Update 7**
Submitted a pull request https://github.com/fastlane/fastlane/pull/6497

```
unset RUBYLIB
unset RUBYOPT
unset _ORIGINAL_GEM_PATH
unset BUNDLE_BIN_PATH
unset BUNDLE_GEMFILE
unset GEM_HOME
unset GEM_PATH
unset RUBYLIB
unset RUBYOPT
unset BUNDLE_BIN_PATH
unset _ORIGINAL_GEM_PATH
unset BUNDLE_GEMFILE
```

---

**Build error output:**
```
INFO [2016-10-10 20:05:11.69]: ▸ Touching Themoji.app.dSYM
INFO [2016-10-10 20:05:11.93]: ▸ Archive Succeeded
DEBUG [2016-10-10 20:05:12.08]: Stored the archive in: /Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive
INFO [2016-10-10 20:05:12.09]: $ /usr/bin/xcrun /Library/Ruby/Gems/2.0.0/gems/gym-1.11.0/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/gym_config20161010-7967-asw94y.plist' -archivePath /Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji\ 2016-10-10\ 20.04.52.xcarchive -exportPath '/var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/gym_output20161010-7967-y1r6se' 
INFO [2016-10-10 20:05:12.11]: ▸ + xcodebuild -exportArchive -exportOptionsPlist /var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/gym_config20161010-7967-asw94y.plist -archivePath '/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive' -exportPath /var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/gym_output20161010-7967-y1r6se
INFO [2016-10-10 20:05:12.49]: ▸ 2016-10-10 20:05:12.491 xcodebuild[8335:60633] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/Themoji_2016-10-10_20-05-12.490.xcdistributionlogs'.
INFO [2016-10-10 20:05:12.66]: ▸ 1.2.840.113635.100.1.61
INFO [2016-10-10 20:05:13.04]: ▸ 2016-10-10 20:05:13.048 xcodebuild[8335:60633] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7fe5eeef4440>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
INFO [2016-10-10 20:05:13.04]: ▸ error: exportArchive: No applicable devices found.
INFO [2016-10-10 20:05:13.05]: ▸ Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
INFO [2016-10-10 20:05:13.05]: ▸ ** EXPORT FAILED **
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/gym_config20161010-7967-asw94y.plist -archivePath '/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive' -exportPath /var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/gym_output20161010-7967-y1r6se
2016-10-10 20:05:12.491 xcodebuild[8335:60633] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/Themoji_2016-10-10_20-05-12.490.xcdistributionlogs'.
1.2.840.113635.100.1.61
2016-10-10 20:05:13.048 xcodebuild[8335:60633] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7fe5eeef4440>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.

Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}

** EXPORT FAILED **
ERROR [2016-10-10 20:05:13.06]: Exit status: 70
ERROR [2016-10-10 20:05:13.06]: 2016-10-11 03:05:12 +0000 [MT] Running step: IDEDistributionSigningAssetsStep with <IDEDistributionContext: 0x7fe5ee8f8470; archive(resolved)='<IDEArchive: 0x7fe5eee24ab0>', distributionTask(resolved)='2', distributionMethod(resolved)='<IDEDistributionMethodAdHoc: 0x7fe5ec7a5c30>', teamID(resolved)='(null)'>
  Chain (2, self inclusive):
  <IDEDistributionContext: 0x7fe5ee8f8470; archive = '(null)', distributionMethod='<IDEDistributionMethodAdHoc: 0x7fe5ec7a5c30>', teamID='(null)'>
  <IDEDistributionContext: 0x7fe5eee277d0; archive = '<IDEArchive: 0x7fe5eee24ab0>', distributionMethod='(null)', teamID='(null)'>
</IDEDistributionContext: 0x7fe5ee8f8470>
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed556e0:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftUIKit.dylib'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftUIKit.dylib" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftUIKit.dylib" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed4d4a0:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftCoreGraphics.dylib'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftCoreGraphics.dylib" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftCoreGraphics.dylib" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed4ecc0:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftFoundation.dylib'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftFoundation.dylib" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftFoundation.dylib" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed54030:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftObjectiveC.dylib'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftObjectiveC.dylib" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftObjectiveC.dylib" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed4b650:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftCore.dylib'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftCore.dylib" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftCore.dylib" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed4feb0:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftDarwin.dylib'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftDarwin.dylib" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftDarwin.dylib" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eee3bba0:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/EmojiKit.framework'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/EmojiKit.framework" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/EmojiKit.framework" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed51420:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftDispatch.dylib'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftDispatch.dylib" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftDispatch.dylib" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed56a40:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/PKHUD.framework'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/PKHUD.framework" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/PKHUD.framework" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed4aa30:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftContacts.dylib'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftContacts.dylib" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftContacts.dylib" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] [OPTIONAL] Didn't find archived user entitlements for <DVTFilePath:0x7fe5eed4ed30:'/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftCoreImage.dylib'>: Error Domain=NSCocoaErrorDomain Code=4 "Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftCoreImage.dylib" did not contain a "archived-expanded-entitlements.xcent" resource." UserInfo={NSLocalizedDescription=Item at "/Users/felixkrause/Library/Developer/Xcode/Archives/2016-10-10/Themoji 2016-10-10 20.04.52.xcarchive/Products/Applications/Themoji.app/Frameworks/libswiftCoreImage.dylib" did not contain a "archived-expanded-entitlements.xcent" resource.}
2016-10-11 03:05:12 +0000 [MT] Running step: IDEDistributionThinningStep with <IDEDistributionContext: 0x7fe5eed21d20; archive(resolved)='<IDEArchive: 0x7fe5eee24ab0>', distributionTask(resolved)='2', distributionMethod(resolved)='<IDEDistributionMethodAdHoc: 0x7fe5ec7a5c30>', teamID(resolved)='N8X438SEU2'>
  Chain (3, self inclusive):
  <IDEDistributionContext: 0x7fe5eed21d20; archive = '(null)', distributionMethod='(null)', teamID='N8X438SEU2'>
  <IDEDistributionContext: 0x7fe5ee8f8470; archive = '(null)', distributionMethod='<IDEDistributionMethodAdHoc: 0x7fe5ec7a5c30>', teamID='(null)'>
  <IDEDistributionContext: 0x7fe5eee277d0; archive = '<IDEArchive: 0x7fe5eee24ab0>', distributionMethod='(null)', teamID='(null)'>
</IDEDistributionContext: 0x7fe5eed21d20>
2016-10-11 03:05:12 +0000 [MT] Running /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool '/var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/IDEDistributionThinningStep.SzI' '--json' '/var/folders/qq/5l_bf23d7_g0h2sv2k66xq_00000gn/T/ipatool-json-filepath-jARuxQ' '--info' '--toolchain' '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr' '--platforms' '/Applications/Xcode.app/Contents/Developer/Platforms'
2016-10-11 03:05:12 +0000  ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
2016-10-11 03:05:13 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1432: warning: assigned but unused variable - minVersion
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1432: warning: assigned but unused variable - sdkVersion
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1441: warning: assigned but unused variable - sourceVersion
2016-10-11 03:05:13 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1529: warning: shadowing outer local variable - node
2016-10-11 03:05:13 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2250: warning: shadowing outer local variable - machoFile
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2250: warning: shadowing outer local variable - machoImage
2016-10-11 03:05:13 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2431: warning: assigned but unused variable - flag
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2431: warning: assigned but unused variable - transformer
2016-10-11 03:05:13 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2648: warning: assigned but unused variable - exc
2016-10-11 03:05:13 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:708: warning: assigned but unused variable - output
2016-10-11 03:05:13 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:15:in `require': cannot load such file -- cfpropertylist (LoadError)
  from /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:15:in `<main>'
2016-10-11 03:05:13 +0000 [MT] /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool exited with 1
2016-10-11 03:05:13 +0000 [MT] ipatool JSON: (null)

ERROR [2016-10-10 20:05:13.06]: There was an error exporting your application
ERROR [2016-10-10 20:05:13.06]: Unfortunately the new Xcode export API is unstable and causes problems on some projects
ERROR [2016-10-10 20:05:13.06]: You can temporary use the :use_legacy_build_api option to get the build to work again
WARN [2016-10-10 20:05:13.10]: Variable Dump:
INFO [2016-10-10 20:05:13.10]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios yolo"}
ERROR [2016-10-10 20:05:13.10]: Error packaging up the application
INFO [2016-10-10 20:05:13.11]: Successfully generated documentation at path '/Users/felixkrause/ios/fastlane/README.md'

DEBUG [2016-10-10 20:05:13.11]: All plugins are up to date
ERROR [2016-10-10 20:05:13.11]: fastlane finished with errors
DEBUG [2016-10-10 20:05:13.12]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Error packaging up the application
  /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/interface.rb:145:in `user_error!'
  /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Library/Ruby/Gems/2.0.0/gems/gym-1.11.0/lib/gym/error_handler.rb:94:in `handle_package_error'
  /Library/Ruby/Gems/2.0.0/gems/gym-1.11.0/lib/gym/runner.rb:125:in `block in package_app'
  /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.1/lib/fastlane_core/command_executor.rb:88:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.1/lib/fastlane_core/command_executor.rb:88:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/gym-1.11.0/lib/gym/runner.rb:121:in `package_app'
  /Library/Ruby/Gems/2.0.0/gems/gym-1.11.0/lib/gym/runner.rb:20:in `run'
  /Library/Ruby/Gems/2.0.0/gems/gym-1.11.0/lib/gym/manager.rb:10:in `work'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/actions/gym.rb:24:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/runner.rb:187:in `block in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/runner.rb:186:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/runner.rb:186:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/fast_file.rb:140:in `method_missing'
  Fastfile:47:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/commands_generator.rb:244:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/commands_generator.rb:20:in `start'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-1.105.1/bin/fastlane:5:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

**Comment by KrauseFx** [comment]
Pull request is live https://github.com/fastlane/fastlane/pull/6497

**Comment by KrauseFx** [comment]
File a radar, feel free to dupe https://openradar.appspot.com/28726736 👍
