### ISSUE TITLE
Fastlane from interactive terminal crashes and claims non-interactive mode

### ISSUE THREAD

**Issue by destructionglacialcyclicalperplexing** [fastlane/fastlane#6558]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Unable to run any commands that require input from the terminal. They all fail with the same error. Commands tried are: `bundle exec fastlane init` `match init` `match change_password` `pem`

##### Complete output when running fastlane, including the stack trace and command used

```
match init
[10:23:37]: Please create a new, private git repository
[10:23:37]: to store the certificates and profiles there
[10:23:37]: URL of the Git Repo: 

Looking for related GitHub issues on fastlane/fastlane...

➡️  Cannot run fastlane on Xcode Server bot
   https://github.com/fastlane/fastlane/issues/6318 [open] 7 💬
   2 days ago

➡️  Running fastlane on Bitrise - non-interactive mode
   https://github.com/fastlane/fastlane/issues/5867 [closed] 5 💬
   25 Aug 2016

➡️  Fastlane android deploy issue
   https://github.com/fastlane/fastlane/issues/5800 [closed] 2 💬
   22 Aug 2016

and 4 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/implementations/shell.rb:119:in `verify_interactive!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/implementations/shell.rb:92:in `input'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.8.1/lib/match/setup.rb:8:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.8.1/lib/match/commands_generator.rb:70:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.8.1/lib/match/commands_generator.rb:119:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.8.1/lib/match/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.8.1/bin/match:6:in `<top (required)>'
	from /usr/local/bin/match:22:in `load'
	from /usr/local/bin/match:22:in `<main>'
```

### Environment

fastlane version (run `fastlane -v`): 

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Y

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? N

What Xcode version do you use (e.g. 7.3, 8.0) 8.0

**Comment by destructionglacialcyclicalperplexing1** [comment]
Fixed by putting `sudo` before every command but not sure why that works

**Comment by TKBurner** [comment]
Hi @destructionglacialcyclicalperplexing1 You should try rvm, this will prevent you from needing to use sudo. Thanks!
