### ISSUE TITLE
Slack integration generates error

### ISSUE THREAD

**Issue by robincalmegard** [fastlane/fastlane#658]
Hello,

I just can't figure out why this is happening when trying to send a Slack notification in an action:

```
[21:03:23]: no implicit conversion of nil into Hash

+------+-----------------+-------------+
|           fastlane summary           |
+------+-----------------+-------------+
| Step | Action          | Time (in s) |
+------+-----------------+-------------+
| 1    | ./getChanges.sh | 0           |
| 2    | cocoapods       | 24          |
| 3    | team_name       | 0           |
| 4    | build_beta      | 306         |
+------+-----------------+-------------+

[21:03:23]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/slack.rb:191:in `merge': no implicit conversion of nil into Hash (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/slack.rb:191:in `deep_merge'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/slack.rb:181:in `generate_slack_attachments'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/slack.rb:42:in `run'
	from /Users/robicalm/code/ios/iphone/fastlane/actions/build_beta.rb:63:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/fast_file.rb:137:in `method_missing'
	from (eval):145:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:127:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:133:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

Here's a snippet from the action:

```
        if (params.include? :slack)
          Fastlane::Actions::SlackAction.run({
            message: "An iOS app (" + appname + "[" + ENV['GENERATE_APPFILE_APP_IDENTIFIER'] + "]) was successfully built and uploaded to Crashlytics.",
            channel: "dev-general",
            success: true,
            payload: {'appname' => appname, 'appidentifier' => ENV['GENERATE_APPFILE_APP_IDENTIFIER']}
          })
        end
```

Any ideas?

**Comment by KrauseFx** [comment]
Why do you call `Fastlane::Actions::SlackAction.run`? Do you call the slack action from a custom action? 

It should work when having the exact same code in your `Fastfile`, right?

**Comment by robincalmegard** [comment]
Actually this is not my work from the beginning. I’m new to Fastlane and I’m just trying to fix stuff in someone else’s code. :)

My predecessor apparently made a quite advanced setup using custom actions instead of putting everything in the Fastfile and calling Fastlane::Actions::SlackAction.run used to work, but apparently not anymore. They’ve made the same thing with sigh which also stopped working after a recent update.

Maybe I should rewrite the whole setup instead?

**Comment by KrauseFx** [comment]
Probably. You should have the actions in your `Fastfile` :+1: You can share a bit more of your setup

**Comment by ohwutup** [comment]
Hey @robincalmegard, I'm going to close this issue for now as it has been a while since there has been activity on it. Please feel free to reopen it if you are still having issues. Thanks! :earth_africa:
