### ISSUE TITLE
when pilot upload,it reports that `operation not permitted`

### ISSUE THREAD

**Issue by diaojunxian** [fastlane/fastlane#6600]
When use the command `pilot upload --username ${username} --app_identifier ${bundle_id}`,it repoerted below
```
09:28:08]: Login to iTunes Connect (xxx@xxx.com)

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in `initialize': [!] Operation not permitted - /tmp/spaceship1476754088_23199.log (Errno::EPERM)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/logger.rb:601:in `create_logfile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/logger.rb:596:in `open_logfile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/logger.rb:551:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/logger.rb:318:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/logger.rb:318:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/client.rb:137:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/client.rb:137:in `logger'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/client.rb:433:in `log_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/client.rb:377:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/client.rb:278:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/tunes/tunes_client.rb:160:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/client.rb:411:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/client.rb:230:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/client.rb:90:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.0/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.10.1/lib/pilot/manager.rb:15:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.10.1/lib/pilot/manager.rb:8:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.10.1/lib/pilot/build_manager.rb:78:in `list'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.10.1/lib/pilot/commands_generator.rb:78:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.2/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.10.1/lib/pilot/commands_generator.rb:135:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.10.1/lib/pilot/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.10.1/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'

```
Why it happened?It worked yesterday,but it did not work now.What can I do to solve it?

**Comment by KrauseFx** [comment]
Do you have write access to `/tmp/spaceship1476754088_23199.log`?

**Comment by diaojunxian** [comment]
@KrauseFx Sorry,I don not know how to confirm ,I can't find `/tmp/spaceship1476754088_23199.log`

**Comment by diaojunxian** [comment]
@KrauseFx It worked now,I had checked the answer and solved it`http://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled`
