### ISSUE TITLE
No APK S3 upload?

### ISSUE THREAD

**Issue by MaximusMcCann** [fastlane/fastlane#6620]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Wondering why the APK option was removed from `s3`.  I see it here: https://github.com/joshdholtz/fastlane-plugin-s3/blob/master/lib/fastlane/plugin/s3/actions/s3_action.rb  
Is there an alternate tool to use instead?

##### Complete output when running fastlane, including the stack trace and command used

```
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
```

### Environment

fastlane version (run `fastlane -v`): 1.105.3
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv
What Xcode version do you use (e.g. 7.3, 8.0) n/a

**Comment by KrauseFx** [comment]
You can use @joshdholtz's fastlane plugin if you want Android support, check out the documentation on how to start using this plugin: https://github.com/joshdholtz/fastlane-plugin-s3

**Comment by MaximusMcCann** [comment]
Took me a while, but finally realized I needed to manually have fastlane source from the git repo. [Note 1]

However, I'm now receiving `Plugin 'S3' overwrites already loaded action 's3'`.  Full error:
```
bundle exec fastlane beta
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:9: warning: already initialized constant Fastlane::Actions::SharedValues::S3_IPA_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/actions/s3.rb:7: warning: previous definition of S3_IPA_OUTPUT_PATH was here
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:10: warning: already initialized constant Fastlane::Actions::SharedValues::S3_DSYM_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/actions/s3.rb:8: warning: previous definition of S3_DSYM_OUTPUT_PATH was here
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:11: warning: already initialized constant Fastlane::Actions::SharedValues::S3_PLIST_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/actions/s3.rb:9: warning: previous definition of S3_PLIST_OUTPUT_PATH was here
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:12: warning: already initialized constant Fastlane::Actions::SharedValues::S3_HTML_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/actions/s3.rb:10: warning: previous definition of S3_HTML_OUTPUT_PATH was here
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:13: warning: already initialized constant Fastlane::Actions::SharedValues::S3_VERSION_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/actions/s3.rb:11: warning: previous definition of S3_VERSION_OUTPUT_PATH was here
[22:13:12]: Plugin 'S3' overwrites already loaded action 's3'
```

Appreciate all the help!!


1.  
```
bundle exec fastlane add_plugin s3
+-------------------------------------+---------+---------------------+
|                            Used plugins                             |
+-------------------------------------+---------+---------------------+
| Plugin                              | Version | Action              |
+-------------------------------------+---------+---------------------+
| fastlane-plugin-upload_folder_to_s3 | 0.3.0   | upload_folder_to_s3 |
+-------------------------------------+---------+---------------------+

[22:03:34]: Seems like the plugin is not available on RubyGems, what do you want to do?
1. Git URL // <---- THIS WAS KEY (to anyone who comes across this post)
2. Local Path
3. RubyGems.org ('fastlane-plugin-s3' seems to not be available there)
?
```

**Comment by joshdholtz** [comment]
@MaximusMcCann Looks like I never got around to pushing that to gem out 😇  Thanks for the reminder! I will get that done.

**Comment by MaximusMcCann** [comment]
Many thanks!!

**Comment by MaximusMcCann** [comment]
Unfortunately, still having troubles here.  Overwrite issues :/
There's a difference in outcomes between running `fastlane update_plugins` & `bundle exec fastlane update_plugins` [Note 1]
First one hard crashes while second completes (albeit with warnings).  When I then try to run my lane I receive the same errors/warnings respectively.  Using `bundle exec` gets further, but then defaults to using the old `s3`.  Any thoughts on how to override would be much appreciated.  

Going to fork Josh's and change the name...

Cheers

Note 1.
```
➜  repo git:(master) ✗ fastlane update_plugins
[19:49:36]: Seems like launching fastlane takes a while
[19:49:36]: fastlane detected a Gemfile in this directory
[19:49:36]: however it seems like you don't use `bundle exec`
[19:49:36]: to launch fastlane faster, please use
[19:49:36]:
[19:49:36]: $ bundle exec fastlane update_plugins
[19:49:36]: For more information, check out https://guides.cocoapods.org/using/a-gemfile.html
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- fastlane/plugin/s3 (LoadError)
	from /Users/aa/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/plugins/plugin_manager.rb:276:in `block in load_plugins'
	from /Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/plugins/plugin_manager.rb:268:in `each'
	from /Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/plugins/plugin_manager.rb:268:in `load_plugins'
	from /Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/commands_generator.rb:17:in `start'
	from /Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/bin/fastlane:5:in `<top (required)>'
	from /Users/aa/.rbenv/versions/2.1.1/bin/fastlane:23:in `load'
	from /Users/aa/.rbenv/versions/2.1.1/bin/fastlane:23:in `<main>'

➜  repo git:(master) ✗ bundle exec fastlane update_plugins
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:9: warning: already initialized constant Fastlane::Actions::SharedValues::S3_IPA_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/libfastlane/actions/s3.rb:7: warning: previous definition of S3_IPA_OUTPUT_PATH was here
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:10: warning: already initialized constant Fastlane::Actions::SharedValues::S3_DSYM_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/actions/s3.rb:8: warning: previous definition of S3_DSYM_OUTPUT_PATH was here
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:11: warning: already initialized constant Fastlane::Actions::SharedValues::S3_PLIST_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/actions/s3.rb:9: warning: previous definition of S3_PLIST_OUTPUT_PATH was here
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:12: warning: already initialized constant Fastlane::Actions::SharedValues::S3_HTML_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/actions/s3.rb:10: warning: previous definition of S3_HTML_OUTPUT_PATH was here
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/fastlane-plugin-s3-60af8111cc89/lib/fastlane/plugin/s3/actions/s3_action.rb:13: warning: already initialized constant Fastlane::Actions::SharedValues::S3_VERSION_OUTPUT_PATH
/Users/aa/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/fastlane-1.105.3/lib/fastlane/actions/s3.rb:11: warning: previous definition of S3_VERSION_OUTPUT_PATH was here
[19:50:34]: Plugin 'S3' overwrites already loaded action 's3'
+-------------------------------------+---------+---------------------+
|                            Used plugins                             |
+-------------------------------------+---------+---------------------+
| Plugin                              | Version | Action              |
+-------------------------------------+---------+---------------------+
| fastlane-plugin-upload_folder_to_s3 | 0.3.0   | upload_folder_to_s3 |
| fastlane-plugin-s3                  | 0.1.0   | s3                  |
+-------------------------------------+---------+---------------------+

Updating plugin dependencies...
Successfully updated plugins
```

**Comment by TKBurner** [comment]
@MaximusMcCann Did you end up getting up and running? Let me know if you are still running into any issues. Thanks!

**Comment by MaximusMcCann** [comment]
@TKBurner I solved the problem and put out a pull-request here: https://github.com/joshdholtz/fastlane-plugin-s3/pull/1

Cheers

**Comment by TKBurner** [comment]
@MaximusMcCann Awesome! Thanks 👍
