### ISSUE TITLE
Unsupported screen size for iPhone SE (4inch) screenshot with deliver.

### ISSUE THREAD

**Issue by williamsjj** [fastlane/fastlane#6624]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [  X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Deliver is refusing to upload valid (320x568) iPhone SE screenshots.

##### Complete output when running fastlane, including the stack trace and command used

```
$ deliver upload_metadata
[19:19:12]: Login to iTunes Connect (xxxx)
[19:19:14]: Login successful

+--------------------+---------------------------------------+
|                   deliver 1.14.2 Summary                   |
+--------------------+---------------------------------------+
| app_identifier     | com.myapp |
| username           | xxxx                      |
| submit_for_review  | false                                 |
| screenshots_path   | ./fastlane/screenshots                |
| metadata_path      | ./fastlane/metadata                   |
| skip_binary_upload | false                                 |
| skip_screenshots   | false                                 |
| skip_metadata      | false                                 |
| force              | false                                 |
| automatic_release  | false                                 |
| dev_portal_team_id | yyyy                            |
+--------------------+---------------------------------------+


[!] Unsupported screen size [320, 568] for path './fastlane/screenshots/en-US/iPhoneSE-02ShowBrowseHistoryForUser.png'
```

### Environment

fastlane version (run `fastlane -v`):

deliver 1.14.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

No

What Xcode version do you use (e.g. 7.3, 8.0)

8.0

**Comment by TKBurner** [comment]
@williamsjj Thanks for reaching out. Can you please run `fastlane run update_fastlane` and then add the --verbose flag your run of deliver? Thanks!

**Comment by williamsjj** [comment]
Here ya go:

```
$ deliver --verbose upload_metadata
Successfully loaded Appfile at path ' ... /fastlane/Appfile'
- app_identifier: 'com.myapp'
- apple_id: 'apple_id'
- team_id: 'team_id'
-------
INFO [2016-10-19 18:55:43.79]: Successfully loaded ' ... /fastlane/Deliverfile' 📄

+-----------------------+---------------------------------------+
|         Detected Values from './fastlane/Deliverfile'         |
+-----------------------+---------------------------------------+
| app_identifier        | com.myapp |
| username              | apple_id                      |
| submit_for_review     | false                                 |
+-----------------------+---------------------------------------+

INFO [2016-10-19 18:55:43.79]: Login to iTunes Connect (apple_id)
Looking for iTunes Connect Team with ID XXX
INFO [2016-10-19 18:55:46.14]: Login successful

+--------------------+---------------------------------------+
|                   deliver 1.14.2 Summary                   |
+--------------------+---------------------------------------+
| app_identifier     | com.myapp |
| username           | apple_id                      |
| submit_for_review  | false                                 |
| screenshots_path   | ./fastlane/screenshots                |
| metadata_path      | ./fastlane/metadata                   |
| skip_binary_upload | false                                 |
| skip_screenshots   | false                                 |
| skip_metadata      | false                                 |
| force              | false                                 |
| automatic_release  | false                                 |
| dev_portal_team_id | team_id                            |
+--------------------+---------------------------------------+

/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.3/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Unsupported screen size [320, 568] for path './fastlane/screenshots/en-US/iPhoneSE-02ShowBrowseHistoryForUser.png' (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/app_screenshot.rb:163:in `calculate_screen_size'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/app_screenshot.rb:43:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/upload_screenshots.rb:90:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/upload_screenshots.rb:90:in `block (2 levels) in collect_screenshots_for_languages'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/upload_screenshots.rb:81:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/upload_screenshots.rb:81:in `block in collect_screenshots_for_languages'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/upload_screenshots.rb:64:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/upload_screenshots.rb:64:in `collect_screenshots_for_languages'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/upload_screenshots.rb:57:in `collect_screenshots'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/runner.rb:50:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.3/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/commands_generator.rb:128:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.14.2/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
```

**Comment by williamsjj** [comment]
Nevermind. My fault...since snapshot isn't working (NSMutableAttributedString bug in UI Testing), I took these screenshots manually in the simulator and the scale was 50%.
