### ISSUE TITLE
register_devices action is broken due to Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by kdawgwilk** [fastlane/fastlane#6632]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a cmd that scans for devices plugged into the computer and then gets their UDID and adds it to the Apple Dev Portal using the `register_devices` action but it seems to be broken right now.  I am guessing this is due to changes made on Apple's Dev Portal API

##### Complete output when running fastlane, including the stack trace and command used

```
[11:06:49]: -------------------------------------------------
[11:06:49]: --- Step: Verifying required fastlane version ---
[11:06:49]: -------------------------------------------------
[11:06:49]: Your fastlane version 1.105.3 matches the minimum requirement of 1.99  ✅
[11:06:49]: ------------------------------
[11:06:49]: --- Step: default_platform ---
[11:06:49]: ------------------------------
[11:06:49]: Driving the lane 'add_devices' 🚀
[11:06:49]: Searching connected devices...
[11:06:51]: Devices to be added:

[11:06:51]: Device Name: My iPhone
[11:06:51]: Device UDID: 8000XXXXXXXXXXXXXXXXXXXXXXXXab76cc09
[11:06:51]: ------------------------------
[11:06:51]: --- Step: register_devices ---
[11:06:51]: ------------------------------
[11:06:55]: Variable Dump:
[11:06:55]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"add_devices"}
[11:06:55]: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Shield</center>
</body>
</html>


+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥    | register_devices                    | 3           |
+------+-------------------------------------+-------------+

[11:06:55]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  silent option is not available in ipa block
   https://github.com/fastlane/fastlane/issues/403 [closed] 4 💬
   4 weeks ago

 (Spaceship::Client::UnexpectedResponse)ems/spaceship-0.36.0/lib/spaceship/client.rb:400:in `parse_response': [!] <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Shield</center>
</body>
</html>

	from /Users/username/.rvm/gems/ruby-2.2.1/gems/spaceship-0.36.0/lib/spaceship/portal/portal_client.rb:256:in `create_device!'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/spaceship-0.36.0/lib/spaceship/portal/device.rb:155:in `create!'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/actions/register_devices.rb:25:in `block in run'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/actions/register_devices.rb:23:in `each'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/actions/register_devices.rb:23:in `map'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/actions/register_devices.rb:23:in `run'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/runner.rb:186:in `chdir'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/runner.rb:186:in `execute_action'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:154:in `block in parsing_binding'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/lane.rb:33:in `call'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/lane.rb:33:in `call'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/runner.rb:45:in `execute'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane_core-0.52.3/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/commands_generator.rb:244:in `run'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/username/.rvm/gems/ruby-2.2.1/gems/fastlane-1.105.3/bin/fastlane:5:in `<top (required)>'
	from /Users/username/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/username/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/username/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/username/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
#####################################################
####### Adds plugged in device to Profiles ##########
#####################################################
desc "Add connected device UDID to Apple Dev Portal"
desc "Refresh provisioning profiles"
lane :add_devices do
    puts "Searching connected devices..."
    stdout, stderr, status = Open3.capture3("instruments -s devices")

    matches = stdout.scan(/(.*)\s\(.*\[(.*)\]\n/)
    devices = {}
    if matches.length < 1
        puts "No connected devices found!"
        puts "Try unplugging and plugging back in"
    else
        puts "Devices to be added:\n"
        for match in matches do
            name, udid = match[0], match[1]

            devices[name] = udid
            puts "Device Name: #{name}"
            puts "Device UDID: #{udid}\n"
        end

        register_devices(devices: devices)
        fix_provisioning
    end
end
```

### Environment

fastlane version (run `fastlane -v`): `1.105.3`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? `rvm`

What Xcode version do you use (e.g. 7.3, 8.0) `8.0`

**Comment by TKBurner** [comment]
@kdawgwilk Thanks for reaching out. Does this affect a new blank project or just your existing project? This will help us look into it. Thanks!

**Comment by kdawgwilk** [comment]
Well I just tried with the Spaceship interactive shell and the `create!(name: "Device Name", udid: "XXXX")` succeeded just fine...so I am not sure where the problem is now...

**Comment by KrauseFx** [comment]
Maybe it was a temporary server error?

**Comment by kdawgwilk** [comment]
@KrauseFx indeed it was!  Everything is all good now 👍

**Comment by GabrielCartier** [comment]
I'm getting that same exact error today. Also tried with Spaceship shell directly with no success.
```
Spaceship::Client::UnexpectedResponse: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Shield</center>
</body>
</html>
```

**Comment by kdawgwilk** [comment]
@GabrielCartier probably due to dev portal updates?

**Comment by GabrielCartier** [comment]
Could be, in that case, Spaceship have to update their code too no?

**Comment by kdawgwilk** [comment]
With my issue it resolved itself, I would try again in a few hours

**Comment by KrauseFx** [comment]
Make sure to use the latest release of _spaceship_ 👍

**Comment by GabrielCartier** [comment]
I'm at `0.36.2` for _spaceship_. Also been like this the whole day. I can keep the issue alive if the issue resolve itself.

**Comment by TKBurner** [comment]
@GabrielCartier Thanks for following up. Can you let me know if you are still running into this issue? It seems intermittent for the other affected users. Hope you have a great weekend coming up. 👍

**Comment by GabrielCartier** [comment]
Yup, today it's working! 👍

**Comment by thaiduy** [comment]
Don't know if you guys still encounter this issue or not, but I still, even after 2 weeks since the first time I ran into it.
I called `register_devices` and received the same error line:

    (Spaceship::Client::UnexpectedResponse)eship-0.37.0/lib/spaceship/client.rb:400:in `parse_response': [!] <html>

I'm using spaceship 0.37.0, match 0.11.0
I tried using spaceship interactive shell and succeeded.

**Comment by TKBurner** [comment]
@thaiduy Do you still get this error 100% of the time? Are you able to create a spaceship session successfully? Thanks!

**Comment by kivannc** [comment]
@TKBurner I am getting this error all the time. I am able to crate at spaceship session successfully. I am using register devices like below. and the devices.txt was created by fabric app. 

 `register_devices(
    devices_file: "devices.txt",
    team_id: "XXXXXX",
    team_name: "XXXXXXX XXXXX",
    username: "xxx@xxx.xxx"
  )`

**Comment by TKBurner** [comment]
@kivannc Can you send me the output of `fastlane env` I want to check your openssl information and make sure you are up to date on our gems.

**Comment by iandundas** [comment]
I'm having the same issue as @thaiduy and @kivannc with `register_devices` today (was fine at the weekend). I can also create a spaceship session successfully too. My `fastlane env` is:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                         |
| ------------------- | --------------------------------------------- |
| OS                  | 10.12.1                                       |
| Ruby                | 2.2.2                                         |
| Bundler?            | false                                         |
| Git                 | git version 2.10.0                            |
| Installation Source | /Users/ian/.rbenv/versions/2.2.2/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                    |
| Ruby Lib Dir        | /Users/ian/.rbenv/versions/2.2.2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2a 19 Mar 2015                    |
| Is contained        | false                                         |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/   |
| Xcode Version       | 8.1                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# This is a fountain of knowledge: https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md
# This is how ENV variables work: https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md#environment-variables
# TODO:
#   - setup codesigning properly
#   https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md

# update_fastlane
fastlane_version "1.32.1" # This is the minimum version number required.

default_platform :ios

platform :ios do
  ############################## PRE ##############################
  before_all do

    File.delete("Tacks.ipa") if File.exist? "Tacks.ipa"
    File.delete("Tacks.app.dSYM.zip")  if File.exist? "Tacks.app.dSYM.zip"

    ensure_git_status_clean
    # cocoapods

  end

  ######################### DEBUGGING LANES #######################

  desc "Ian testing things"
  lane :ian do
  end

  desc "Does nothing but run before_all/after_all hooks"
  lane :nothing do
  end


  ######################### PUBLIC LANES ##########################

    # 'InternalTesting' => :debug, # Fabric, test builds
    # 'Preproduction' => :release, # TestFlight - ReleaseCandidate builds
    # 'AppStore' => :release, # Pushed to AppStore

  desc "Sends an internal build to Fabric. Debugging enabled etc."
  lane :ship_internal do
    increase_build_number
    fabric(scheme: "InternalTesting")
  end

  desc "Send a beta to Testflight. Should be equivelant to App Store."
  lane :ship_preproduction do
    version_increase
    increase_build_number
    itc(scheme: "Preproduction")
  end

  desc "Make a release to iTunes Connect"
  lane :ship_appstore do
    version_increase
    increase_build_number
    itc(scheme: "AppStore")
  end


  ######################### VERSIONING LANES ##########################

  desc "prompts user to enter type of version increase. is persistant about it.."
  lane :version_increase do
    entered = prompt(text:"Increment version number? [no/patch/minor/major]")
    case entered
    when "patch"
      increment_version_number(
        bump_type: "patch" # Automatically increment patch version number
      )
    when "minor"
      increment_version_number(
        bump_type: "minor" # Automatically increment minor version number
      )
    when "major"
      increment_version_number(
        bump_type: "major" # Automatically increment major version number
      )
    else
      ian
    end
  end

  #added as a lane so it can be called from CLI.
  #fastlane run increment_build_number` also works
  desc "Update build number"
  lane :increase_build_number do
      # increment build number in all relevant plist files
      new_build_number = increment_build_number

      # find all modified .plist files, and modify the new build number to contain ".$(CONFIGURATION)" at the end.
      # This took like two hours to work out, lol.
      `git st --porcelain`.to_enum(:scan, /"?Tacks\s*.+.plist"?/).map { Regexp.last_match }.each do |match|
        file_path = match.to_s
        sh "/usr/libexec/PlistBuddy -c \"Set :CFBundleVersion #{new_build_number}.\\\$(CONFIGURATION)\" ../#{match.to_s}"
      end
  end



  # 1.1.0 -> 1.1.1
  lane :increase_patch_number do
    increment_version_number(
      bump_type: "patch" # Automatically increment patch version number
    )
  end

  # 1.1.1 -> 1.2.0
  lane :increase_minor_number do
    increment_version_number(
      bump_type: "minor" # Automatically increment minor version number
    )
  end

  # 1.1.1 -> 2.0
  lane :increase_major_number do
    increment_version_number(
      bump_type: "major" # Automatically increment minor version number
    )
  end

  ######################### OTHER LANES #########################

  # run with `fastlane run carthage` to skip ensure_git_status_clean
  lane :cartage do
    carthage(
      platform: "iOS",
      use_binaries: false, # --no-use-binaries
    )
  end

  # https://littlebitesofcocoa.com/225-downloading-dsyms-with-fastlane
  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTunes Connect
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  ######################### PRIVATE LANES #########################
  #------------------------- Crashlytics -------------------------#
  private_lane :fabric do |options|
    scheme = options[:scheme]

    # sigh(
    #   # skip_install: true,
    #   development: true,
    #   app_identifier: "cc.Tacks.ios.InternalTesting"
    # )

    register_devices(devices_file: "./fastlane/BetaTesters")

    # fastlane run match git_url:"https://github.com/iandundas/tackscertificates" type:"adhoc" force_for_new_devices:true app_identifier:"cc.Tacks.ios.InternalTesting"
    match(
      git_url: "https://github.com/iandundas/tackscertificates",
      type: "adhoc",
      force_for_new_devices: true,
      app_identifier: "cc.Tacks.ios.InternalTesting")

    build(
      scheme: scheme,
      # signId: ENV['SIGNING_IDENTITY_DEV']
    )

    # environment = scheme.upcase
    # api = File.read("../Fitbay/Constants/environment_constants.h").scan(/\d\.*/).join

    crashlytics(
      ipa_path: "Tacks.ipa",
      notes_path: "./ReleaseNotes.md",
      # crashlytics_path: './Vendor/Crashlytics.framework',
      # groups: 'beta-testers'
      # notes: "Running on #{environment} #{api}",
      # groups: ['fitbay-test']
    )

    # post_to_slack(scheme: scheme, destination: "Crashlytics")
  end


  #--------------------------- App Store -------------------------#

  private_lane :itc do |options|
    scheme = options[:scheme]

    sigh(
      skip_install: true,
      development: false,
      app_identifier: scheme == "AppStore" ? "cc.Tacks.ios" : "cc.Tacks.ios.Preproduction"
    )

    build(
      scheme: scheme,
      # signId: ENV['SIGNING_IDENTITY_PROD']
    )

    pilot(
      ipa: "Tacks.ipa",
      skip_submission: (scheme == "AppStore"),
    )

    # post_to_slack(scheme: scheme, destination: "TestFlight")

  end


  ############################# UTIL ##############################

  desc "Builds the project and produces an IPA file"
  private_lane :build do |options|
    scheme = options[:scheme]
    signingId = options[:signId]

    # or run manually:
    # bundle exec fastlane run gym scheme:InternalTesting configuration:InternalTesting clean:true project:Tacks.xcodeproj output_name:Tacks.ipa output_directory:/Users/ian/Desktop/TacksArchive/Output build_path:/Users/ian/Desktop/TacksArchive/Build

    gym(
      scheme: scheme,
      configuration: scheme,
      clean: true,
      include_bitcode: false,
      project: "Tacks.xcodeproj",
      # output_directory: "../",
      output_name: "Tacks.ipa",
      # codesigning_identity: "#{signingId}",
      # xcargs: "ARCHIVE=NO" # Used to tell the Fabric run script NOT to upload dSYM file
    )
  end

  desc "Resets the simulators and runs snapshot"
  private_lane :reset_and_snapshot do
    # first wipe the simulators (presumably the UI testing works best on a virgin app)
    ENV['SNAPSHOT_FORCE_DELETE'] = "true"
    sh "snapshot reset_simulators"
    # next run the snapshotting tool:
    snapshot
  end

  desc "Runs snapshot"
  lane :do_snapshot do
    snapshot
  end

  ############################# POST ##############################

  # This block is called, only if the executed lane was successful
  after_all do |lane|
    clean_build_artifacts

    version = get_version_number(xcodeproj: "Tacks.xcodeproj")
    build = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]

    commit_version_bump(
      message: "Fastlane bump: #{version} (#{build})",
      xcodeproj: './Tacks.xcodeproj'
    )
    notification(title: "🤖", message: "Fastlane finished '#{lane}' successfully") # Mac OS X Notification
  end

  error do |lane, exception|
      # slack(
      #   message: exception.message,
      #   success: false
      # )
    notification(title: "🤖", subtitle: "Fastlane '#{lane}' errored", message: exception.message) # Mac OS X Notification
  end
end


# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "cc.Tacks.ios" # The bundle identifier of your app
apple_id "contact@iandundas.co.uk" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
team_name "Ian Dundas"
# team_id "Q2CBPJ58CA"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.1  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.57.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| highline            | 1.7.8   |
| commander           | 4.4.0   |
| terminal-table      | 1.4.5   |
| net-sftp            | 2.1.2   |
| security            | 0.1.3   |
| krausefx-shenzhen   | 0.14.11 |
| xcpretty            | 0.2.4   |
| multipart-post      | 2.0.0   |
| word_wrap           | 1.0.0   |
| colored             | 1.2     |
| credentials_manager | 0.16.2  |
| multi_xml           | 0.5.5   |
| faraday-cookie_jar  | 0.0.6   |
| fastimage           | 1.6.8   |
| mini_magick         | 4.5.1   |
| babosa              | 1.0.2   |
| rubyzip             | 1.1.7   |
| gh_inspector        | 1.0.2   |
| fastlane_core       | 0.57.0  |
| json                | 2.0.2   |
| excon               | 0.54.0  |
| plist               | 3.2.0   |
| xcode-install       | 2.0.9   |
| CFPropertyList      | 2.3.3   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
</details>


*generated on:* **2016-11-23**
</details>

**Comment by iandundas** [comment]
Huh it's working again now - the response is a bit weird listing an array of nils though:

```
bundle exec fastlane run register_devices devices_file:./fastlane/BetaTesters
[14:36:36]: ------------------------------
[14:36:36]: --- Step: register_devices ---
[14:36:36]: ------------------------------
[14:36:41]: Fetching list of currently registered devices...
[14:36:42]: Successfully registered new devices.
[14:36:42]: Result: [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil]```

**Comment by orkenstein** [comment]
The same happens to me today:
```
Spaceship::Client::UnexpectedResponse: [!] <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Shield</center>
</body>
</html>
```

**Comment by orkenstein** [comment]
In my case the issue was **´** symbol in `devices.txt`:
```
The Future´s iPhone7 -> The Future's iPhone7
```
How to avoid this in future?
