### ISSUE TITLE
Use sigh variables in plugin

### ISSUE THREAD

**Issue by ericertl** [fastlane/fastlane#6644]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Hi. I'm trying to create a new plugin to delete invalid or expired provisioning profiles, reusing the code for repair_all in sigh.
We used to name profiles as "App name App Store", but as some apps changed names (and the certificate expired invalidating all the profiles) we now changed the naming convention to "com.company.appname AppStore". I need a way to bulk delete all these invalid profiles as I have thousands of them.
I've tried to follow the plugins instructions in fastlane/fastlane/docs/Plugins.md but I'm getting errors when trying to use Sigh or Spaceship.

I know I need to add some includes and declare Sigh and Spaceship somewhere, but I don't know how or where (Did I mention I don't code in Ruby?). Can anyone help? (ignore the comment in the profile.delete! line as I wanted to test it before doing something wrong with the profiles)

``` ruby
def self.run(params)
        UI.message "Starting login with user '#{Sigh.config[:username]}'"
        Spaceship.login(Sigh.config[:username], nil)
        Spaceship.select_team
        UI.message "Successfully logged in"

        # Select all 'Invalid' or 'Expired' provisioning profiles
        broken_profiles = Spaceship.provisioning_profile.all.find_all do |profile|
          (profile.status == "Invalid" or profile.status == "Expired")
        end

        if broken_profiles.count == 0
          UI.success "All provisioning profiles are valid, nothing to do"
          return
        end

        UI.success "Going to delete #{broken_profiles.count} provisioning profiles"

        # Iterate over all broken profiles and repair them
        broken_profiles.each do |profile|
          UI.message "Deleting profile '#{profile.name}'..."
          #profile.delete! # yes, that's all you need to delete a profile
        end

        UI.success "Successfully deleted #{broken_profiles.count} provisioning profiles"
      end
```
##### Complete output when running fastlane, including the stack trace and command used

```
fastlane test
+---------------------------------+---------+-----------------+
|                        Used plugins                         |
+---------------------------------+---------+-----------------+
| Plugin                          | Version | Action          |
+---------------------------------+---------+-----------------+
| fastlane-plugin-delete_profiles | 0.1.0   | delete_profiles |
+---------------------------------+---------+-----------------+

[11:25:26]: Driving the lane 'test' 🚀
[11:25:26]: -----------------------------
[11:25:26]: --- Step: delete_profiles ---
[11:25:26]: -----------------------------
[11:25:26]: Variable Dump:
[11:25:26]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"test"}
[11:25:26]: uninitialized constant Fastlane::Actions::DeleteProfilesAction::Sigh

+------+-----------------+-------------+
|           fastlane summary           |
+------+-----------------+-------------+
| Step | Action          | Time (in s) |
+------+-----------------+-------------+
| 💥    | delete_profiles | 0           |
+------+-----------------+-------------+

[11:25:26]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/Users/eric/Projects/fastlanePlugin/fastlane-plugin-delete_profiles/lib/fastlane/plugin/delete_profiles/actions/delete_profiles_action.rb:5:in `run': [!] uninitialized constant Fastlane::Actions::DeleteProfilesAction::Sigh (NameError)
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/runner.rb:187:in `block in execute_action'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/runner.rb:186:in `chdir'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/runner.rb:186:in `execute_action'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/fast_file.rb:140:in `method_missing'
    from Fastfile:2:in `block in parsing_binding'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/lane.rb:33:in `call'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/runner.rb:49:in `block in execute'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/runner.rb:45:in `chdir'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/runner.rb:45:in `execute'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.3/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/commands_generator.rb:244:in `run'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/commands_generator.rb:20:in `start'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
    from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.105.3/bin/fastlane:5:in `<top (required)>'
    from /Users/eric/.rbenv/versions/2.3.1/bin/fastlane:22:in `load'
    from /Users/eric/.rbenv/versions/2.3.1/bin/fastlane:22:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
lane :test do
  delete_profiles
end
```
### Environment

fastlane version (run `fastlane -v`): fastlane 1.105.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? YES

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

What Xcode version do you use (e.g. 7.3, 8.0) 8.0

**Comment by KrauseFx** [comment]
```
        UI.message "Starting login with user '#{Sigh.config[:username]}'"
        Spaceship.login(Sigh.config[:username], nil)
```
Basically those 2 lines are the problem: you're trying to access `Sigh.config`, which doesn't exist. Try using `params[:username]` instead. 

make sure to define this option in the `available_options` method in your action
