### ISSUE TITLE
frameit 3.0 not work in FastFile

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#6700]
i install frameit 3.0.0, but write that not upgrade
frameit install 3.0.0, but write that not upgrade
```
### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12                                       |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.36.1  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| deliver             | 1.14.3  | ✅ Up-To-Date        |
| snapshot            | 1.16.2  | ✅ Up-To-Date        |
| frameit             | 2.8.0   | 🚫 Update availaible |
| pem                 | 1.3.2   | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| pilot               | 1.11.0  | ✅ Up-To-Date        |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.8.1   | 🚫 Update availaible |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| fastlane            | 1.106.0 | ✅ Up-To-Date        |
```

having this error 
```
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'frameit' (< 3.0.0, >= 2.8.0) - did find: [frameit-3.0.0] (Gem::LoadError)
Checked in 'GEM_PATH=/Users/Shared/Jenkins/.gem/ruby/2.3.0:/usr/local/lib/ruby/gems/2.3.0:/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/specification.rb:1438:in `block in activate_dependencies'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `each'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `activate_dependencies'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/specification.rb:1409:in `activate'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by KrauseFx** [comment]
Thanks for reporting this, I'll push a fix in a minute 👍

**Comment by KrauseFx** [comment]
https://github.com/fastlane/fastlane/pull/6701
https://github.com/fastlane/fastlane/pull/6702

Almost ready

**Comment by GandjaFuzz** [comment]
big thanks!!!

**Comment by KrauseFx** [comment]
Cool, does it work for you now?
