### ISSUE TITLE
Deliver fails with `invalid request body`

### ISSUE THREAD

**Issue by ldiqual** [fastlane/fastlane#6710]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When trying to deliver my app to iTunes connect, I get the following error:

```
invalid request body
```

Deliver is used as part of a lane, and I'm retrying using `bundle exec deliver`.

##### Complete output when running fastlane, including the stack trace and command used

```
[ldiqual@ldiqual-mbp-2 app]$ bundle exec deliver --verbose
Successfully loaded Appfile at path '/Users/ldiqual/Company/app/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/ldiqual/Company/app/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/ldiqual/Company/app/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/ldiqual/Company/app/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/ldiqual/Company/app/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/ldiqual/Company/app/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/ldiqual/Company/app/fastlane/Appfile'
-------
INFO [2016-10-24 19:25:42.01]: Successfully loaded '/Users/ldiqual/Company/app/fastlane/Deliverfile' 📄

+-----------------------+-----------------------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------------+-----------------------+
| skip_screenshots      | true                  |
| skip_metadata         | true                  |
| force                 | true                  |
+-----------------------+-----------------------+

INFO [2016-10-24 19:25:42.01]: Login to iTunes Connect (lois@company.com)
Looking for iTunes Connect Team with ID 123456

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
    invalid request body

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09invalid%20request%20body+repo:fastlane/fastlane
➡️  pilot crashes on upload
   https://github.com/fastlane/fastlane/issues/4821 [open] 23 💬
   3 days ago

➡️  Unable to log in to iTunes Connect - returns HTML
   https://github.com/fastlane/fastlane/issues/2149 [closed] 18 💬
   5 weeks ago

➡️  [pilot] fails with only internal testers
   https://github.com/fastlane/fastlane/issues/4907 [closed] 42 💬
   3 weeks ago

bundler: failed to load command: deliver (/Users/ldiqual/.rbenv/versions/2.3.1/bin/deliver)
Spaceship::TunesClient::ITunesConnectError: [!] The request could not be completed because:
    invalid request body
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/tunes/tunes_client.rb:218:in `handle_itc_response'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/tunes/tunes_client.rb:94:in `team_id='
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/tunes/tunes_client.rb:121:in `select_team'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/runner.rb:15:in `login'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/runner.rb:7:in `initialize'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/commands_generator.rb:47:in `new'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/commands_generator.rb:128:in `run'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/commands_generator.rb:12:in `start'
  /Users/ldiqual/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/bin/deliver:5:in `<top (required)>'
  /Users/ldiqual/.rbenv/versions/2.3.1/bin/deliver:22:in `load'
  /Users/ldiqual/.rbenv/versions/2.3.1/bin/deliver:22:in `<top (required)>'
```

### Deliverfile

```
skip_screenshots true
skip_metadata true
force true
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.12                                             |
| Ruby                | 2.3.1                                             |
| Bundler?            | true                                              |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/       |
| Xcode Version       | 8.0                                               |
| Git                 | git version 2.8.4 (Apple Git-73)                  |
| Installation Source | /Users/ldiqual/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12 (16A323)                           |
| Ruby Lib Dir        | /Users/ldiqual/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                       |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

Redacted
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.36.1  | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| deliver             | 1.14.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.9.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| pilot               | 1.11.0  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| snapshot            | 1.16.2  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.106.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded***


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.13.5       |
| io-console                | 0.4.5        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.3.8        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.53.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.0       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.0.rc.2   |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 1.0.1        |
| molinillo                 | 0.5.2        |
| xcodeproj                 | 1.3.3        |
| cocoapods                 | 1.1.0.rc.2   |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.19       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.7        |
</details>


*generated on:* **2016-10-24**
</details>

**Comment by henrykwan82** [comment]
I just tried uploading a build to test flight and i am also running into this error.

**Comment by summera** [comment]
Also running into this. See: https://github.com/fastlane/fastlane/issues/6711. Think I found the cause

**Comment by JoelMason27** [comment]
I am also hitting the exact same error.

**Comment by luskin** [comment]
same here...

**Comment by thaiduy** [comment]
Could be a TestFlight error? Earlier this morning we uploaded an update to TestFlight, but can not update/install it to our devices. TestFlight keeps saying "Could not install <app name>. The encryption information is unavailable. Try again"

**Comment by summera** [comment]
@thaiduy this is different and occurs on selecting team. See #6711

**Comment by orira** [comment]
Same here

**Comment by irace** [comment]
Also seeing this.

**Comment by ChrisVolentine** [comment]
Also getting this. Happens when trying to select a team

**Comment by ToroLiu** [comment]
Same here ...

More ...

Execute `pilot list`,  get `invalid request body` too. Failed when logging into iTunes Connect.

**Comment by ChrisVolentine** [comment]
Looks like there's a potential 'fix' in #6711

**Comment by webpolis** [comment]
why is Fastlane so fragile? Every week my builds break! :(

**Comment by KrauseFx** [comment]
Hey everyone, thanks for the reports, I can reproduce the issue, I'm working on a fix 🚀

**Comment by LeBlaaanc** [comment]
@webpolis seems like there's a pretty straightforward answer to that question... if Apple exposed a formal API Fastlane would be less problematic.

**Comment by KrauseFx** [comment]
Hey, thanks for your patience everyone, we were able to push new releases for _spaceship_, _pilot_ and _deliver_, please update to the latest release using `[sudo] gem update deliver` or `[sudo] gem update pilot`. If you're using `bundler` use `bundle update` instead 👍 

Special thanks to @summera for providing a super fast fix, and @milch for reviewing all the required version bumps and dependency updates :rocket: 

Please let us know if that solves the issue for you.

**Comment by webpolis** [comment]
@LeBlaaanc yeah, I just noted that Fastlane was doing web scraping under the hood. I wish I don't have to build anything for Apple, but it's still causing nightmares to all developers worldwide :)

**Comment by KrauseFx** [comment]
@webpolis It's actually not web-scraping, _fastlane_ uses [spaceship](https://spaceship.airforce), which an HTTP client that directly communicates with Apple's API endpoints, including the Apple Developer Portal and iTunes Connect 👍

**Comment by ldiqual** [comment]
@KrauseFx Updated my bundle and now the build uploads correctly. Thank you so much for your reactivity! Have a great night.

**Comment by mangofever** [comment]
Wow!! Great work! Thanks, @KrauseFx

**Comment by janiduw** [comment]
@KrauseFx , thank you so much for the quick turnaround on this. Amazing work !

**Comment by r-massanet** [comment]
Thanks a lot for the quick fix!

**Comment by rpzzzzzz** [comment]
Thanks a lot!

**Comment by DBocksteger** [comment]
is the version in the current gem including this fix, too?

**Comment by nazeehshoura** [comment]
Thanks a lot for the quick fix!
