### ISSUE TITLE
Match - 2FA - Fixnum is not a String

### ISSUE THREAD

**Issue by iv-mexx** [fastlane/fastlane#6768]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I've just activated 2FA for my apple account. 
At first try, `match` worked fine (requesting the 2FA code), but `pilot` did not. 

In https://github.com/fastlane/fastlane/issues/6171 I found a proposed solution ( https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification ). 

However, as soon as I add the `export FASTLANE_SESSION=....` to my `~/.zshrc`, `match` does not work anymore.

Removing the FASTLANE_SESSION makes `match` work again, but at the end I'll have to upload the .ipa by hand.
##### Complete output when running fastlane, including the stack trace and command used

```
[10:34:12]: -------------------------------------------------
[10:34:12]: --- Step: Verifying required fastlane version ---
[10:34:12]: -------------------------------------------------
[10:34:12]: Your fastlane version 1.106.2 matches the minimum requirement of 1.81.0  ✅
[10:34:12]: ------------------------------
[10:34:12]: --- Step: default_platform ---
[10:34:12]: ------------------------------
[10:34:12]: Name of the lane 'appstore' is already taken by the action named 'appstore'
[10:34:12]: Driving the lane 'ios beta' 🚀
[10:34:12]: -------------------
[10:34:12]: --- Step: match ---
[10:34:12]: -------------------
[10:34:13]: Successfully loaded '/Users/mexx/code/echocardiography/echocardiography-ios/fastlane/Matchfile' 📄

+----------------------+-------------------------------------------------------------------+
|                       Detected Values from './fastlane/Matchfile'                        |
+----------------------+-------------------------------------------------------------------+
| git_url              | <correct git url> |
| app_identifier       | <correct app identifier>                                              |
| team_id              | <correct team id>                                                        |
+----------------------+-------------------------------------------------------------------+


+-----------------------+-------------------------------------------------------------------+
|                                 Summary for match 0.10.0                                  |
+-----------------------+-------------------------------------------------------------------+
| type                  | appstore                                                          |
| git_url               | <correct git url> |
| app_identifier        | <correct app identifier>                                              |
| team_id               | <correct team id>                                                        |
| git_branch            | master                                                            |
| username              | chmelarmarkus@gmail.com                                           |
| keychain_name         | login.keychain                                                    |
| readonly              | false                                                             |
| verbose               | false                                                             |
| force                 | false                                                             |
| shallow_clone         | false                                                             |
| force_for_new_devices | false                                                             |
| skip_docs             | false                                                             |
+-----------------------+-------------------------------------------------------------------+

[10:34:13]: Cloning remote git repo...
[10:34:14]: 🔓  Successfully decrypted certificates repo
[10:34:14]: Verifying that the certificate and profile are still valid on the Dev Portal...
Error loading session from environment
Make sure to pass the session in a valid format
[10:34:14]: 🔒  Successfully encrypted certificates repo
[10:34:14]: Variable Dump:
[10:34:14]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
[10:34:14]: Fixnum is not a String

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥    | match                               | 1           |
+------+-------------------------------------+-------------+

[10:34:14]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  --decimals flag type must be Fixnum not String
   https://github.com/fastlane/fastlane/issues/4881 [closed] 1 💬
   27 May 2016

➡️  [slather action] Fix --decimals flag type
   https://github.com/fastlane/fastlane/pull/4880 [closed] 3 💬
   27 May 2016

➡️  * latest_testflight_build_number crash
   https://github.com/fastlane/fastlane/pull/1200 [closed] 8 💬
   24 Mar 2016

/Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/http-cookie-1.0.3/lib/http/cookie.rb:373:in `value=': [!] Fixnum is not a String (TypeError)
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/http-cookie-1.0.3/lib/http/cookie.rb:680:in `block in yaml_initialize'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/http-cookie-1.0.3/lib/http/cookie.rb:674:in `each'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/http-cookie-1.0.3/lib/http/cookie.rb:674:in `yaml_initialize'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/http-cookie-1.0.3/lib/http/cookie.rb:667:in `init_with'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:382:in `init_with'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:374:in `revive'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `block in register_empty'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `each'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `register_empty'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:141:in `visit_Psych_Nodes_Sequence'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/nodes/node.rb:38:in `to_ruby'
    from /Users/mexx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:253:in `load'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/http-cookie-1.0.3/lib/http/cookie_jar/yaml_saver.rb:24:in `load'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:325:in `block in load'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `open'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `load'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/spaceship-0.36.2/lib/spaceship/two_step_client.rb:95:in `load_session_from_env'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/spaceship-0.36.2/lib/spaceship/client.rb:250:in `send_shared_login_request'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/spaceship-0.36.2/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/spaceship-0.36.2/lib/spaceship/client.rb:411:in `do_login'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/spaceship-0.36.2/lib/spaceship/client.rb:230:in `login'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/spaceship-0.36.2/lib/spaceship/client.rb:90:in `login'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/spaceship-0.36.2/lib/spaceship/portal/spaceship.rb:22:in `login'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/spaceship-0.36.2/lib/spaceship/portal/spaceship.rb:77:in `login'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/match-0.10.0/lib/match/spaceship_ensure.rb:19:in `initialize'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/match-0.10.0/lib/match/runner.rb:14:in `new'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/match-0.10.0/lib/match/runner.rb:14:in `run'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/actions/match.rb:11:in `run'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/runner.rb:187:in `block in execute_action'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `chdir'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `execute_action'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/fast_file.rb:140:in `method_missing'
    from Fastfile:47:in `block (2 levels) in parsing_binding'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/lane.rb:33:in `call'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/runner.rb:49:in `block in execute'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/runner.rb:45:in `chdir'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/runner.rb:45:in `execute'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:52:in `block (2 levels) in run'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:246:in `run'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:23:in `start'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/gems/fastlane-1.106.2/bin/fastlane:5:in `<top (required)>'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/bin/fastlane:23:in `load'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/bin/fastlane:23:in `<main>'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/bin/ruby_executable_hooks:15:in `eval'
    from /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/bin/ruby_executable_hooks:15:in `<main>'
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>

✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| --- | --- |
| OS | 10.11.6 |
| Ruby | 2.3.0 |
| Bundler? | true |
| Xcode Path | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version | 8.0 |
| Git | git version 2.10.1 |
| Installation Source | /Users/mexx/.rvm/gems/ruby-2.3.0@iosdev/bin/fastlane |
| Host | Mac OS X 10.11.6 (15G1004) |
| Ruby Lib Dir | /Users/mexx/.rvm/rubies/ruby-2.3.0/lib |
| OpenSSL Version | OpenSSL 1.0.2j  26 Sep 2016 |
### fastlane files:

<details><summary>

`./fastlane/Fastfile`</summary>

``` ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit screenshots to the App Store"
  desc "This will generate the screenshots first"
  lane :screenshots do
    snapshot
    frameit
    deliver(
      skip_screenshots: false,
      skip_metadata: true,
      skip_binary_upload: true,
      submit_for_review: false,
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # increment_build_number
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Echocardiography") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # increment_build_number
    match(type: "appstore")
    # snapshot
    gym(scheme: "Echocardiography") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

</details>

<details><summary>

`./fastlane/Appfile`</summary>

``` ruby
app_identifier "at.oegari.tee-report" # The bundle identifier of your app
apple_id "chmelarmarkus@gmail.com" # Your Apple email address

team_id "Z4H29J75Y7"  # Developer Portal Team ID
itc_team_id "16942800"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```

</details>
### fastlane gems

| Gem | Version | Update-Status |
| --- | --- | --- |
| credentials_manager | 0.16.2 | ✅ Up-To-Date |
| fastlane_core | 0.53.0 | ✅ Up-To-Date |
| spaceship | 0.36.2 | ✅ Up-To-Date |
| cert | 1.4.3 | ✅ Up-To-Date |
| deliver | 1.14.5 | ✅ Up-To-Date |
| frameit | 3.0.0 | ✅ Up-To-Date |
| gym | 1.11.3 | ✅ Up-To-Date |
| sigh | 1.11.2 | ✅ Up-To-Date |
| match | 0.10.0 | ✅ Up-To-Date |
| pem | 1.3.2 | ✅ Up-To-Date |
| pilot | 1.11.1 | ✅ Up-To-Date |
| produce | 1.2.1 | ✅ Up-To-Date |
| scan | 0.13.1 | ✅ Up-To-Date |
| screengrab | 0.5.5 | ✅ Up-To-Date |
| snapshot | 1.16.2 | ✅ Up-To-Date |
| supply | 0.7.1 | ✅ Up-To-Date |
| fastlane | 1.106.2 | ✅ Up-To-Date |
### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary>

<b>Loaded gems</b></summary>

| Gem | Version |
| --- | --- |
| did_you_mean | 1.0.0 |
| executable-hooks | 1.3.2 |
| bundler-unload | 1.0.2 |
| rubygems-bundler | 1.4.4 |
| bundler | 1.13.6 |
| io-console | 0.4.5 |
| i18n | 0.7.0 |
| json | 1.8.3 |
| minitest | 5.9.1 |
| thread_safe | 0.3.5 |
| tzinfo | 1.2.2 |
| activesupport | 4.2.7.1 |
| addressable | 2.4.0 |
| babosa | 1.0.2 |
| colored | 1.2 |
| highline | 1.7.8 |
| commander | 4.4.0 |
| security | 0.1.3 |
| credentials_manager | 0.16.2 |
| excon | 0.54.0 |
| gh_inspector | 1.0.2 |
| multi_json | 1.12.1 |
| plist | 3.1.0 |
| rubyzip | 1.1.7 |
| terminal-table | 1.4.5 |
| fastlane_core | 0.53.0 |
| multipart-post | 2.0.0 |
| faraday | 0.9.2 |
| unf_ext | 0.0.7.2 |
| unf | 0.1.4 |
| domain_name | 0.5.20160826 |
| http-cookie | 1.0.3 |
| faraday-cookie_jar | 0.0.6 |
| faraday_middleware | 0.10.0 |
| fastimage | 1.6.8 |
| multi_xml | 0.5.5 |
| claide | 1.0.1 |
| fuzzy_match | 2.0.4 |
| nap | 1.1.0 |
| cocoapods-core | 1.1.1 |
| cocoapods-deintegrate | 1.0.1 |
| cocoapods-downloader | 1.1.2 |
| cocoapods-plugins | 1.0.0 |
| cocoapods-search | 1.0.0 |
| cocoapods-stats | 1.0.0 |
| netrc | 0.7.8 |
| cocoapods-trunk | 1.1.1 |
| cocoapods-try | 1.1.0 |
| escape | 0.0.4 |
| fourflusher | 2.0.1 |
| molinillo | 0.5.2 |
| xcodeproj | 1.3.3 |
| cocoapods | 1.1.1 |
| dotenv | 2.1.1 |
| mini_magick | 4.5.1 |
| rouge | 1.11.1 |
| xcpretty | 0.2.4 |
| net-ssh | 3.2.0 |
| net-sftp | 2.1.2 |
| krausefx-shenzhen | 0.14.10 |
| slack-notifier | 1.5.1 |
| xcpretty-travis-formatter | 0.0.4 |
| jwt | 1.5.6 |
| little-plugger | 1.1.4 |
| logging | 2.1.0 |
| memoist | 0.15.0 |
| os | 0.9.6 |
| signet | 0.7.3 |
| googleauth | 0.5.1 |
| httpclient | 2.8.2.4 |
| hurley | 0.2 |
| mime-types-data | 3.2016.0521 |
| mime-types | 3.1 |
| uber | 0.0.15 |
| representable | 2.3.0 |
| retriable | 2.1.0 |
| google-api-client | 0.9.19 |
| terminal-notifier | 1.7.1 |
| word_wrap | 1.0.0 |
| xcode-install | 2.0.8 |

</details>

_generated on:_ **2016-10-27**
</details>

**Comment by iv-mexx** [comment]
✅ Yes, I've seen the Code Signing Guide and thats why I'm using match.
❌ Its not a code signing issue, its an issue with 2FA

**Comment by KrauseFx** [comment]
It seems like the content of `FASTLANE_SESSION` is somehow invalid, can you share how it looks like using `ENV | grep "FASTLANE"`, feel free to remove some characters of the actual content of the cookies.

**Comment by iv-mexx** [comment]
Sure: 

```
FASTLANE_SESSION=---\n- !ruby/object:HTTP::Cookie\n  name: DES5a4gc7\n  value: HBEAIUFPAN241T\n  domain: idmsa.apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 2592000\n  created_at: 2016-10-27 10:06:54.150424000 +02:00\n  accessed_at: 2016-10-27 10:33:36.419478000 +02:00\n- !ruby/object:HTTP::Cookie\n  name: dslang\n  value: US-EN\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2016-10-27 10:33:37.119526000 +02:00\n  accessed_at: &1 2016-10-27 10:33:37.121054000 +02:00\n- !ruby/object:HTTP::Cookie\n  name: itcdq\n  value: 0\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2016-10-27 10:16:58.531515000 +02:00\n  accessed_at: *1\n
```

To be clear: thats exactly the output I get from `spaceauth`.

In comparison with the example in https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification, it seems that I have two additional cookies.

If manually remove the other two cookies, `match` works, but pilot fails with `[Transporter Error Output]: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)`.

Oh, and if I skip match and use all three cookies, `pilot` fails the same way `match` does (`Fixnum is not a String`) so I guess its the same problem there.

**Comment by b3ll** [comment]
+1 can't use travis without this happening

**Comment by milch** [comment]
@iv-mexx I'm trying to replicate your issue, however `match` always seems to be working for me. Can you try clearing `~/.spaceship/<email>/cookie` and running `spaceauth` again? 

Also, are you using Two Factor Authentication (set up on an iOS device or the System Preferences on macOS) or Two Step Verifitcation (set up on the appleid.apple.com)?

**Comment by suzhaev** [comment]
@milch same issue.
Two Factor Authentication

Okay. I cleaned cookie. Run spaceauth again, then run fastlane:

```
[17:06:31]: This might take a few minutes. Please don't interrupt the script.
[17:06:36]: [Transporter Error Output]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
[17:06:36]: Transporter transfer failed.
[17:06:36]: 
[17:06:36]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
[17:06:36]: Your account has 2 step verification enabled
[17:06:36]: Please go to https://appleid.apple.com/account/manage
[17:06:36]: and generate an application specific password for
[17:06:36]: the iTunes Transporter, which is used to upload builds
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
[17:06:36]: Variable Dump:
[17:06:36]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta_client", :IPA_OUTPUT_PATH=>"/Users/***/Desktop/ios/***/***", :DSYM_OUTPUT_PATH=>"/Users/***/Desktop/ios/***/***", :XCODEBUILD_ARCHIVE=>"/Users/***/Library/Developer/Xcode/Archives/2016-11-01/*** 2016-11-01 17.06.11.xcarchive"}
[17:06:36]: Missing password for user ***@gmail.com, and running in non-interactive shell

```

**Comment by iv-mexx** [comment]
@milch I'm using 2FA, the one where I'm getting a 6-digit code to my iPhone.

Btw, I noticed that [this guide](https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification) seems to confuse the terms as well: The headline talks about "2 Step Verification", but the text then talks about "2 Factor Verification".


Anyway: Clearing `~/.spaceauth` fixed the Problem with `match` crashing.
However, `pilot` still fails with `[Transporter Error Output]: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)`.

Did I misunderstand, does 2FA not work with Fastlane after all, do I need to create an app-specific password? And how do I use that?

**Comment by TKBurner** [comment]
@iv-mexx Thanks for following up. I looped in the core team so they can take a look. Hope you have a great day!

**Comment by iv-mexx** [comment]
Thanks @TKBurner 👍

**Comment by iosdevben** [comment]
I'm not experiencing the `Fixnum is not a String` issue but spaceauth is not helping.

Initially I was seeing the Fixum error so I tried clearing ~/.spaceship and rerunning spaceauth then setting the FASTLANE_SESSION environment variable again.

Now it's failing with the following errors:
```
[08:26:42]: Uploading metadata to iTunes Connect
[08:26:45]: Successfully uploaded initial set of metadata to iTunes Connect
[08:26:49]: Uploading binary to iTunes Connect
[08:26:50]: Going to upload updated app to iTunes Connect
[08:26:50]: This might take a few minutes. Please don't interrupt the script.
[08:26:58]: [Transporter Error Output]: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
[08:26:58]: Transporter transfer failed.
[08:26:58]: 
[08:26:58]: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
[08:26:58]: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
Return status of iTunes Transporter was 1: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

**Comment by mpirri** [comment]
Hello all, sorry for the delay in getting back to you about this!

So, we just shipped a new version of `fastlane_core` (version 0.56.0) that should fix this issue.  Specifically, now when you get the "Please sign in with an app-specific password." message, you will be properly asked to enter that password.

To get this new fix, do `gem update fastlane_core` and you should upgrade to 0.56.0. At this point, `deliver` should start working again.

Please let us know if this is not working for you. Closing this issue now.

**Comment by mpirri** [comment]
An update!  _fastlane_ 1.110.0 has this change in it, so you can just update to the latest fastlane (or `deliver` or `pilot`) and you will get the fix. Thanks again!

**Comment by KrauseFx** [comment]
Hey everyone, _fastlane_ now fully supports both two-factor and two-step verification 👋 

Please make sure to update to the latest version of _fastlane_ by running 

```
fastlane update_fastlane
```

If you use a `Gemfile`, just run `bundle update`

### On your computer 🚀
To use _fastlane_ with two-factor, just run _fastlane_ as you usually would. You'll be asked for the verification method, and a 4 or 6 digits pin. Everything will just work out of the box 📦 

### On your continuous integration system 💻 
Check out the [official two-factor docs](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth) for more information on how to setup two-step on CI system. You'll have to authenticate on your local machine to get a session cookie, which you then transfer to your CI.

----

If you have any issues setting this up, please submit [a new issue](https://github.com/fastlane-old/spaceship/issues/new) so we can help you get up and running 👍
