### ISSUE TITLE
error: No applicable devices found

### ISSUE THREAD

**Issue by ildarsharafutdinov** [fastlane/fastlane#6769]
fastlane 1.106.1
Xcode 8

```
    provision = "sigh_#{options[:sign_provision]}_#{options[:sign_type]}"
    xcodebuild(
      workspace: options[:workspace],
      scheme: options[:scheme],
      archive: true,
      clean: true,
      build_settings: {
        "PRODUCT_BUNDLE_IDENTIFIER" => app_identifier,
        "CODE_SIGN_IDENTITY" => options[:sign_identity],
        "PROVISIONING_PROFILE" => ENV[provision],
        "PROVISIONING_PROFILE_SPECIFIER" => ENV[provision],
        "DEVELOPMENT_TEAM" => "",
        "JOBS" => 4,
      },
    )

    if options[:export_ipa]
      xcexport(
        export_options_plist: {
          method: "ad-hoc",
        },
      )
    end
```

Here is the error:
```
INFO [2016-10-27 14:57:37.62]: ----------------------
INFO [2016-10-27 14:57:37.62]: --- Step: xcexport ---
INFO [2016-10-27 14:57:37.62]: ----------------------
Successfully loaded Appfile at path '/Users/ildar/.../fastlane/Appfile'
-------
INFO [2016-10-27 14:57:37.63]: For a more detailed xcodebuild log open /Users/ildar/Library/Logs/fastlane/xcbuild/2016-10-27/72988/xcodebuild.log
INFO [2016-10-27 14:57:37.63]: $ set -o pipefail && xcodebuild -exportOptionsPlist "/var/folders/zk/9j2yt_lj0hj4pf_qyk46j2gc0000gn/T/exportOptions20161027-72988-zhl5rc.plist" -exportArchive -archivePath "Publication.xcarchive" -exportPath "Publication" | tee '/Users/ildar/Library/Logs/fastlane/xcbuild/2016-10-27/72988/xcodebuild.log' | xcpretty --color --simple
INFO [2016-10-27 14:57:37.95]: ▸ 2016-10-27 14:57:37.951 xcodebuild[74991:720778] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/zk/9j2yt_lj0hj4pf_qyk46j2gc0000gn/T/Publication_2016-10-27_14-57-37.949.xcdistributionlogs'.
INFO [2016-10-27 14:57:38.04]: ▸ 1.2.840.113635.100.1.61
INFO [2016-10-27 14:57:38.27]: ▸ 2016-10-27 14:57:38.274 xcodebuild[74991:720778] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7faf857400e0>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
INFO [2016-10-27 14:57:38.27]: ▸ error: exportArchive: No applicable devices found.
INFO [2016-10-27 14:57:38.27]: ▸ Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
WARN [2016-10-27 14:57:38.29]: Variable Dump:
INFO [2016-10-27 14:57:38.29]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios upload_to_hockey_for_...", :BUILD_NUMBER_REPOSITORY=>"5e74393", :SIGH_PROFILE_TYPE=>"ad-hoc", :XCODEBUILD_DERIVED_DATA_PATH=>nil, :XCODEBUILD_ARCHIVE=>"Publication.xcarchive", :IPA_OUTPUT_PATH=>"Publication.ipa"}
ERROR [2016-10-27 14:57:38.29]: Exit status of command 'set -o pipefail && xcodebuild -exportOptionsPlist "/var/folders/zk/9j2yt_lj0hj4pf_qyk46j2gc0000gn/T/exportOptions20161027-72988-zhl5rc.plist" -exportArchive -archivePath "Publication.xcarchive" -exportPath "Publication" | tee '/Users/ildar/Library/Logs/fastlane/xcbuild/2016-10-27/72988/xcodebuild.log' | xcpretty --color --simple' was 70 instead of 0.
2016-10-27 14:57:37.951 xcodebuild[74991:720778] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/zk/9j2yt_lj0hj4pf_qyk46j2gc0000gn/T/Publication_2016-10-27_14-57-37.949.xcdistributionlogs'.
1.2.840.113635.100.1.61
2016-10-27 14:57:38.274 xcodebuild[74991:720778] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7faf857400e0>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.

Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
```

However, if I copy and run the command manually in terminal export succeeds!
```
xcodebuild -exportOptionsPlist "/var/folders/zk/9j2yt_lj0hj4pf_qyk46j2gc0000gn/T/exportOptions20161027-72988-zhl5rc.plist" -exportArchive -archivePath "Publication.xcarchive" -exportPath "Publication"
2016-10-27 14:58:51.841 xcodebuild[75068:721943] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/zk/9j2yt_lj0hj4pf_qyk46j2gc0000gn/T/Publication_2016-10-27_14-58-51.840.xcdistributionlogs'.
1.2.840.113635.100.1.61
Exported Publication.xcarchive to: /Users/ildar/.../Publication
** EXPORT SUCCEEDED **
```

Any idea what goes wrong?

**Comment by ildarsharafutdinov** [comment]
This seems to be the reason:

```2016-10-27 14:17:08 +0000  ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
2016-10-27 14:17:09 +0000  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs': Your bundle is locked to json (1.8.3), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of json (1.8.3) has removed it. You'll need to update your bundle to a different version of json (1.8.3) that hasn't been removed in order to install. (Bundler::GemNotFound)
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2016-10-27 14:17:09 +0000 [MT] /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool exited with 1
2016-10-27 14:17:09 +0000 [MT] ipatool JSON: (null)```

**Comment by ildarsharafutdinov** [comment]
In case someone else faces the issue, make sure you use default system ruby.

I had to uninstall ruby 2.3.0 in order to make fastlane work.

**Comment by TKBurner** [comment]
@ildarsharafutdinov Thanks for letting us know. We've seen this frequently lately and are looking into a longer term solution. Hope that you have a great weekend coming up. 👍

**Comment by TKBurner** [comment]
@ildarsharafutdinov Thanks for reaching out. Can you set the `workspace` parameter on xcexport?

**Comment by jk** [comment]
> I had to uninstall ruby 2.3.0 in order to make fastlane work.
@ildarsharafutdinov So which version did you use then which worked for you? I also tried to uninstall my non-system version and ended up with 2.0.0 which fastlance complains about because of it incompatibilities in terms of SSL/TLS.

**Comment by ildarsharafutdinov** [comment]
```
ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
```
