### ISSUE TITLE
Last version forcing to use "js_file" in snapshot.js

### ISSUE THREAD

**Issue by yeradis** [fastlane/fastlane#677]
```
FATAL [2015-10-07 19:49:33.40]: Could not determine which UIAutomation file to use. Please pass a path to your Javascript file using 'js_file'.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | snapshot                            | 1           |
+------+-------------------------------------+-------------+

FATAL [2015-10-07 19:49:33.41]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/snapshot-0.10.1/lib/snapshot/snapshot_config.rb:176:in `js_file': Could not determine which UIAutomation file to use. Please pass a path to your Javascript file using 'js_file'. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-0.10.1/lib/snapshot/runner.rb:9:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/actions/snapshot.rb:27:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/actions/snapshot.rb:25:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/actions/snapshot.rb:25:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:137:in `method_missing'
	from (eval):73:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:136:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:142:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by ohwutup** [comment]
hey @yeradis apologies for the long time since you have submitted the issue, there have been a number of changes since this was opened. would you mind updating to the latest versions of the tools and give your workflow another try? i am going to close this for now, but feel free to reopen if necessary!
