### ISSUE TITLE
Screengrab doesn't work on Android 7

### ISSUE THREAD

**Issue by virusman** [fastlane/fastlane#6844]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When trying to capture a screenshot on API >= 24 (Android 7), it fails with the following error:

`
java.lang.RuntimeException: Unable to capture screenshot.
at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:57)
at tools.fastlane.screengrab.UiAutomatorScreenshotStrategy.takeScreenshot(UiAutomatorScreenshotStrategy.java:39)
at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)
at com.test.app.tests.screenshots.MainScreenshotsTest.mainScreenshotTest(MainScreenshotsTest.java:45)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
at android.app.ContextImpl.checkMode(ContextImpl.java:2162)
at android.app.ContextImpl.getDir(ContextImpl.java:1983)
at android.content.ContextWrapper.getDir(ContextWrapper.java:278)
at tools.fastlane.screengrab.FileWritingScreenshotCallback.getFilesDirectory(FileWritingScreenshotCallback.java:70)
at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:39)`

The main error is `MODE_WORLD_READABLE no longer supported`: screengrab tries to create a world-readable file (`context.getDir("screengrab", 1)`) in the internal storage, which is not possible anymore on API >= 24

### Environment
screengrab 0.5.5
Android 7.0 on Nexus 5X

**Comment by TKBurner** [comment]
Hi @virusman Can you please run `fastlane run update_fastlane` and then let me know if the error presents itself again. If it does, send over the full input and output and the output of `fastlane env`

I'd love ot take a look! Thanks 👍

**Comment by virusman** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.12.1                                           |
| Ruby                | 2.3.1                                             |
| Bundler?            | false                                             |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/       |
| Xcode Version       | 8.1                                               |
| Git                 | git version 2.9.3 (Apple Git-75)                  |
| Installation Source | /Users/virusman/.rvm/gems/ruby-2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                        |
| Ruby Lib Dir        | /Users/virusman/.rvm/rubies/ruby-2.3.1/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                       |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| deliver             | 1.14.5  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.2  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded***


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.12.5       |
| io-console                | 0.4.5        |
| highline                  | 1.7.8        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| faraday                   | 0.9.1        |
| faraday_middleware        | 0.10.0       |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| multipart-post            | 2.0.0        |
| multi_xml                 | 0.5.5        |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| colored                   | 1.2          |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| commander                 | 4.4.0        |
| babosa                    | 1.0.2        |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.53.0       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.1        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.0        |
| google-api-client         | 0.9.9        |
| excon                     | 0.45.4       |
| claide                    | 1.0.0.beta.3 |
| xcodeproj                 | 1.0.0.beta.3 |
</details>


*generated on:* **2016-11-03**
</details>

**Comment by virusman** [comment]
The issue is in the screengrab Android java library, fastlane toolchain is very unlikely to be related.

**Comment by TKBurner** [comment]
@virusman Thanks for following up. Can you let me know if this affects all projects including a new blank one? We haven't heard any other reports of this. Thanks!

**Comment by virusman** [comment]
I found the cause. I've been running the tests with others, without Screengrab. The app didn't have a runtime permission to write to external storage, so Screengrab runtime couldn't save the screenshots. Running screengrab fixes this, since it adds the permission via adb.

**Comment by kpogz** [comment]
I seem to be having a similar issue as well getting the permissions but only on Bitrise (CI). I run the test using screengrab like virusman, the log indicated that i have permissions:
heres the first piece of screengrab log:
+-----------------------------+--------------------------------------------------------------------+
|                                  Summary for screengrab 2.13.0                                   |
+-----------------------------+--------------------------------------------------------------------+
| app_package_name            | com.selfcarecatalyst.healthstorylines.acromegaly                   |
| use_tests_in_packages       | ["healthstorylines.selfcarecatalysts.com.healthstorylines.UITes... |
| app_apk_path                | app/build/outputs/apk/app-acromegaly-debug.apk                     |
| tests_apk_path              | app/build/outputs/apk/app-acromegaly-debug-androidTest.apk         |
| output_directory            | fastlane/metadata/Acro                                             |
| skip_open_summary           | true                                                               |
| locales                     | ["en-US"]                                                          |
| clear_previous_screenshots  | true                                                               |
| tests_package_name          | com.selfcarecatalyst.healthstorylines.acromegaly.test              |
| android_home                | /opt/android-sdk-linux                                             |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner                     |
| ending_locale               | en-US                                                              |
| device_type                 | phone                                                              |
| exit_on_test_failure        | true                                                               |
| reinstall_app               | false                                                              |
+-----------------------------+--------------------------------------------------------------------+

[16:27:56]: Clearing phoneScreenshots within fastlane/metadata/Acro
[16:27:56]: $ adb devices -l
[16:27:57]: ▸ List of devices attached
[16:27:57]: ▸ emulator-5554          device product:sdk model:sdk device:generic
[16:27:57]: $ adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[16:27:57]: ▸ /storage/sdcard
[16:27:57]: Cleaning screenshots on device
[16:27:57]: Validating app APK
[16:27:57]: $ /opt/android-sdk-linux/build-tools/25.0.2/aapt dump permissions app/build/outputs/apk/app-acromegaly-debug.apk
[16:27:57]: ▸ package: com.selfcarecatalyst.healthstorylines.acromegaly
[16:27:57]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[16:27:57]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[16:27:57]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[16:27:57]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[16:27:57]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[16:27:57]: ▸ permission: com.selfcarecatalyst.healthstorylines.permission.C2D_MESSAGE
[16:27:57]: ▸ uses-permission: name='com.selfcarecatalyst.healthstorylines.permission.C2D_MESSAGE'
[16:27:57]: ▸ uses-permission: name='android.permission.INTERNET'
[16:27:57]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[16:27:57]: ▸ uses-permission: name='android.permission.ACCESS_WIFI_STATE'
[16:27:57]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[16:27:57]: ▸ uses-permission: name='android.permission.VIBRATE'
[16:27:57]: ▸ uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
[16:27:57]: ▸ uses-permission: name='android.permission.READ_SYNC_SETTINGS'
[16:27:57]: ▸ uses-permission: name='android.permission.WRITE_SYNC_SETTINGS'
[16:27:57]: ▸ uses-permission: name='android.permission.GET_ACCOUNTS'
[16:27:57]: ▸ uses-permission: name='android.permission.AUTHENTICATE_ACCOUNTS'


The Error is here:

healthstorylines.selfcarecatalysts.com.healthstorylines.UITests.demoScreenshots.GooglePlayStoreScreengrab:
[16:30:41]: ▸ Error in test_demoScreenshots(healthstorylines.selfcarecatalysts.com.healthstorylines.UITests.demoScreenshots.GooglePlayStoreScreengrab):
[16:30:41]: ▸ java.lang.RuntimeException: Unable to capture screenshot.
[16:30:41]: ▸ at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:57)
[16:30:41]: ▸ at tools.fastlane.screengrab.UiAutomatorScreenshotStrategy.takeScreenshot(UiAutomatorScreenshotStrategy.java:39)
[16:30:41]: ▸ at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
[16:30:41]: ▸ at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
[16:30:41]: ▸ at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)
[16:30:41]: ▸ at healthstorylines.selfcarecatalysts.com.healthstorylines.UITests.demoScreenshots.GooglePlayStoreScreengrab.demoScreenshots(GooglePlayStoreScreengrab.java:51)



Also i noticed when testing locally on the nexus 6p, screengrab outputs a special line to say its adding the EXTERNAL_WRITE permission, but on other devices, it just lists the permissions its using as shown in this log. when it does this it says:

[21:44:07]: Granting the permission necessary to change locales on the device
[21:44:07]: $ adb -s 192.168.58.101:5555 shell pm grant com.selfcarecatalyst.healthstorylines.acromegaly android.permission.CHANGE_CONFIGURATION
[21:44:07]: $ adb -s 192.168.58.101:5555 shell getprop ro.build.version.sdk
[21:44:07]: ▸ 23
[21:44:07]: Granting the permissions necessary to access device external storage
[21:44:07]: $ adb -s 192.168.58.101:5555 shell pm grant com.selfcarecatalyst.healthstorylines.acromegaly android.permission.WRITE_EXTERNAL_STORAGE
[21:44:08]: $ adb -s 192.168.58.101:5555 shell pm grant com.selfcarecatalyst.healthstorylines.acromegaly android.permission.READ_EXTERNAL_STORAGE
