### ISSUE TITLE
Deliver upload error

### ISSUE THREAD

**Issue by patrykmol** [fastlane/fastlane#6909]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Executing `deliver` fails with following error.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
deliver
[15:34:40]: [32mSuccessfully loaded '/path/Deliverfile' 📄[0m


Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:248:in `block (2 levels) in recalc_column_widths': [31m[!] undefined method `to_h' for [[17, [1]], [0, [0]]]:Array[0m (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `block in recalc_column_widths'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `recalc_column_widths'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:339:in `column_widths'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:97:in `column_width'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:7:in `block in render'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `block in render'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/configuration/configuration_file.rb:49:in `puts'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/configuration/configuration_file.rb:49:in `puts'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/configuration/configuration_file.rb:49:in `print_resulting_config_values'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/configuration/configuration_file.rb:27:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/configuration/configuration.rb:157:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/configuration/configuration.rb:157:in `load_configuration_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/commands_generator.rb:52:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/commands_generator.rb:149:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12                                                          |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.0                                                            |
| Git                 | git version 2.8.4 (Apple Git-73)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12 (16A323)                                        |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| terminal-table            | 1.4.5   |
| json                      | 1.8.2   |
| faraday_middleware        | 0.10.0  |
| dotenv                    | 2.1.1   |
| net-ssh                   | 3.2.0   |
| net-sftp                  | 2.1.2   |
| plist                     | 3.1.0   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.10 |
| slack-notifier            | 1.5.1   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| activesupport             | 4.2.7.1 |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| colored                   | 1.2     |
| nanaimo                   | 0.2.2   |
| xcodeproj                 | 1.4.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| multipart-post            | 2.0.0   |
| xcode-install             | 2.0.8   |
| word_wrap                 | 1.0.0   |
| commander                 | 4.4.0   |
| babosa                    | 1.0.2   |
| gh_inspector              | 1.0.2   |
| credentials_manager       | 0.16.2  |
| fastlane_core             | 0.53.0  |
| bundler                   | 1.13.6  |
| multi_xml                 | 0.5.5   |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| logging                   | 2.1.0   |
| jwt                       | 1.5.6   |
| memoist                   | 0.15.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.3   |
| googleauth                | 0.5.1   |
| httpclient                | 2.8.2.4 |
| google-api-client         | 0.9.19  |
| highline                  | 1.7.8   |
| excon                     | 0.52.0  |
| rubyzip                   | 1.1.7   |
</details>


*generated on:* **2016-11-08**
</details>
```

**Comment by hjanuschka** [comment]
can you please share your `Deliverfile` - seems to be some wrong variable inside

**Comment by patrykmol** [comment]
```
app_identifier "com.eclipsesource.tabrisjs" # The bundle identifier of your app
username "email@email.com" # your Apple ID user
app_version "1.11.0" # App version
automatic_release false # Set to manual release
ipa "./tabris-js-app.ipa" # App location
#screenshots_path "./resources/ios/screenshots" # Path to screenshots
force true # Disabled HTML report generation
```

**Comment by patrykmol** [comment]
Updating ruby to 2.3.0 helped ...sort of. Everything works from terminal however when Jenkins invokes `deliver` it still uses 2.0.0. Rebooting build machine didn't help. Closing for now.

**Comment by carsten-wenderdel** [comment]
I've had a failure with a very similar stack trace when calling "fastlane" (fastlane version 2.x.x).
What helped in my case: Uninstall fastlane und terminal-table. After reinstall of fastlane I now have terminal-table version 1.7.3 instead of 1.7.2 - this might have been the problem.
Ruby version is the preinstalled one from El Capitan: ruby 2.0.0p648

**Comment by salabaha** [comment]
I had this issue as well and was able to resolve it by updating terminal-table to version 1.7.3. (gem update terminal-table)
