### ISSUE TITLE
: can't activate nokogiri-1.5.6, already activated nokogiri-1.6.6.2 (Gem::LoadError)

### ISSUE THREAD

**Issue by sarthak03** [fastlane/fastlane#691]
Hi

I recently switched laptops. And receiving this error on running `fastlane sample_lane` -

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1995:in `raise_if_conflicts': can't activate nokogiri-1.5.6, already activated nokogiri-1.6.6.2 (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:96:in `block in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:95:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:95:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml.rb:6:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:33:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/junit_generator.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/bin/fastlane:6:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

On performing - `sudo gem cleanup` and `sudo gem install`, the error still persists. What's the fix for this?

**Comment by KrauseFx** [comment]
You could try using `rvm` instead of the built-in ruby.

**Comment by sarthak03** [comment]
On trying to install `rvm` on my mac, it gave me the following error. 
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- utils/inreplace (LoadError)
```
Really stuck with this. Is there a way to fix ruby or reinstall from scratch?

**Comment by xfreebird** [comment]
Have you upgraded to El Capitan ?

Try ```sudo chown -R $(whoami):admin /usr/local```

**Comment by sarthak03** [comment]
No I'm still on OSX Yosemite. I did switch my laptop recently and transferred all data from the previous mac using transfer assistance. Everything else is working fine. 

Is there a way to remove, reinstall  and ruby, brew and its related components.

**Comment by xfreebird** [comment]
This might help you:

```shell
sudo gem install rubygems-update
sudo update_rubygems
```

**Comment by xfreebird** [comment]
With brew is easy:
unistall:
```ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"```

then install again:
```ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"```

for system ruby is harder, the command from the previous post might help.

**Comment by KrauseFx** [comment]
The new version of `fastlane` doesn't require `nokogiri` any more: https://github.com/fastlane/fastlane/releases/tag/1.36.2
