### ISSUE TITLE
Produce crashes while app creation

### ISSUE THREAD

**Issue by Desnoo** [fastlane/fastlane#6960]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I run produce to create a new app and it already exists, produce will crash after the existence check.
Seems like an error to me.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
INFO [2016-11-11 18:32:12.11]: [DevCenter] App 'xxx' already exists, nothing to do on the Dev Center
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 4)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 3)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 2)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 1)...

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Unauthorized Access

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Unauthorized%20Access+repo:fastlane/fastlane
➡️  Binary upload invalid / [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["ITC.response.error.OPERATION_FAILED"], "info"=>nil}, "statusCode"=>"ERROR"}
   https://github.com/fastlane/fastlane/issues/6419 [open] 54 💬
   2 days ago

➡️  In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels , at least 72 DPI, and in the RGB color space - deliver 1.1.0
   https://github.com/fastlane/fastlane/issues/1590 [closed] 42 💬
   18 Jun 2016

➡️  sigh: authentication.failed / Your session has expired.  Please log in.
   https://github.com/fastlane/fastlane/issues/4157 [closed] 16 💬
   28 Jun 2016

/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/client.rb:450:in `block in send_request': [!] The request could not be completed because: (Spaceship::Client::UnauthorizedAccessError)
	Unauthorized Access
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/client.rb:347:in `with_retry'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/client.rb:444:in `send_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/client.rb:385:in `request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:50:in `teams'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:118:in `select_team'
	from /usr/local/lib/ruby/gems/2.3.0/gems/produce-1.3.0/lib/produce/itunes_connect.rb:10:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/produce-1.3.0/lib/produce/manager.rb:8:in `start_producing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/produce-1.3.0/lib/produce/commands_generator.rb:35:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/produce-1.3.0/lib/produce/commands_generator.rb:133:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/produce-1.3.0/lib/produce/commands_generator.rb:11:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/produce-1.3.0/bin/produce:6:in `<top (required)>'
	from /usr/local/bin/produce:23:in `load'
	from /usr/local/bin/produce:23:in `<main>'

```

**Comment by Desnoo** [comment]
The problem was that the user had no access to the itunes connect. Sorry for bothering.
