### ISSUE TITLE
Have to run "sudo" to run fastlane

### ISSUE THREAD

**Issue by zwang** [fastlane/fastlane#6973]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Have to run "sudo fastlane" everytime. Otherwise having the error like below:

Ignoring bigdecimal-1.2.7 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.2.7
Ignoring io-console-0.4.6 because its extensions are not built.  Try: gem pristine io-console --version 0.4.6
Ignoring json-2.0.2 because its extensions are not built.  Try: gem pristine json --version 2.0.2
Ignoring psych-2.1.1 because its extensions are not built.  Try: gem pristine psych --version 2.1.1
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem fastlane (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/bin/fastlane:22:in `<main>'

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.43.0"

default_platform :ios

def get_profile_name(uuid)
    profiles_path = File.expand_path("~") + "/Library/MobileDevice/Provisioning Profiles/*.mobileprovision"
    profile_paths = Dir[profiles_path]

    profile_paths.each do |profile_path|
      profile = Plist.parse_xml(`security cms -D -i '#{profile_path}'`)
      if profile['UUID'] == uuid
        return profile['Name']
      end
    end
  end

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # update_fastlane
    # ensure_git_status_clean
    # carthage(platform: 'iOS')

    # xctool # run the tests of your app
  end
  
  desc "Bump up build number and commit changes"
  lane :bumpup do
    increment_build_number
    commit_version_bump(message: 'Version Bump by fastlane', xcodeproj: './Plato.xcodeproj')
  end

  desc "Runs all the tests"
  lane :test do
    # snapshot
    scan(project: "Plato.xcodeproj", scheme: "Tests", clean: true, code_coverage: true)
    # ensure_no_debug_code(text: "// TODO")
  end

  desc "Submit a new Dev Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :dev do
    # scan(project: "Plato.xcodeproj", scheme: "Tests", clean: true)
    # increment_build_number(build_number: ENV['BUILD_NUMBER'])
    cert
    sigh(output_path: "fastlane/sigh_output")
    # use the UID of the newly created provisioning profile
    # https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
    # profile_name = get_profile_name lane_context[SharedValues::SIGH_UDID]
    gym(scheme: "Plato", configuration: "Dev", clean: true) # Build your app - more options available
    # gym(scheme: "Plato", configuration: "Dev", clean: true, xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{profile_name}'") # Build your app - more options available
    # commit_version_bump(message: 'Version Bump by fastlane', xcodeproj: './Plato.xcodeproj')
    # push_to_git_remote(
    #   remote: 'origin',          # optional, default: 'origin'
    #   local_branch: 'develop',   # optional, aliased by 'branch', default: 'master'
    #   remote_branch: 'develop',  # optional, default is set to local_branch
    #   force: false,              # optional, default: false
    # )
    pilot(distribute_external: false)
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Submit a new Stage Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :stage do
    scan(project: "Plato.xcodeproj", scheme: "Tests", clean: true)
    increment_build_number(build_number: ENV['BUILD_NUMBER'])
    cert
    sigh(output_path: "fastlane/sigh_output")
    # use the UID of the newly created provisioning profile
    # https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
    gym(scheme: "Plato", configuration: "Stage") # Build your app - more options available
    # commit_version_bump(message: 'Version Bump by fastlane', xcodeproj: './Plato.xcodeproj')
    # push_to_git_remote(
    #   remote: 'origin',          # optional, default: 'origin'
    #   local_branch: 'develop',   # optional, aliased by 'branch', default: 'master'
    #   remote_branch: 'develop',  # optional, default is set to local_branch
    #   force: false,              # optional, default: false
    # )
    pilot(distribute_external: false)
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
  
  lane :qa do
    scan(project: "Plato.xcodeproj", scheme: "Tests", clean: true)
    increment_build_number(build_number: ENV['BUILD_NUMBER'])
    cert
    sigh(output_path: "fastlane/sigh_output")
    # use the UID of the newly created provisioning profile
    # https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
    gym(scheme: "Plato", configuration: "Qa") # Build your app - more options available
    # commit_version_bump(message: 'Version Bump by fastlane', xcodeproj: './Plato.xcodeproj')
    # push_to_git_remote(
    #   remote: 'origin',          # optional, default: 'origin'
    #   local_branch: 'develop',   # optional, aliased by 'branch', default: 'master'
    #   remote_branch: 'develop',  # optional, default is set to local_branch
    #   force: false,              # optional, default: false
    # )
    pilot(distribute_external: true)
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
  
  desc "Same as Dev and QA but point to Production and have production settings and do beta testing"
  lane :beta do
    scan(project: "Plato.xcodeproj", scheme: "Tests", clean: true)
    increment_build_number(build_number: ENV['BUILD_NUMBER'])
    cert
    sigh(output_path: "fastlane/sigh_output")
    # use the UID of the newly created provisioning profile
    # https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
    gym(scheme: "Plato", configuration: "Prod") # Build your app - more options available
    # commit_version_bump(message: 'Version Bump by fastlane', xcodeproj: './Plato.xcodeproj')
    # push_to_git_remote(
    #   remote: 'origin',          # optional, default: 'origin'
    #   local_branch: 'develop',   # optional, aliased by 'branch', default: 'master'
    #   remote_branch: 'develop',  # optional, default is set to local_branch
    #   force: false,              # optional, default: false
    # )
    pilot(distribute_external: true)
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    # snapshot
    sigh
    gym(scheme: "Plato") # Build your app - more options available
    # deliver(force: true)
    # frameit
  end
  
  lane :pushgit do
      push_to_git_remote(
      remote: 'origin',          # optional, default: 'origin'
      local_branch: 'develop',   # optional, aliased by 'branch', default: 'master'
      remote_branch: 'develop',  # optional, default is set to local_branch
      force: false,              # optional, default: false
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.platoapp.Plato.Dev" # The bundle identifier of your app
apple_id "dev@platoteam.com" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
# team_name "Felix Krause"
# team_id "Q2CBPJ58CA"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.1.1        |
| xcodeproj                 | 1.4.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.55.0       |
| bundler                   | 1.13.6       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-11-12**
</details>

**Comment by hjanuschka** [comment]
have you tried

`brew doctor`  - maybe the permissions on some folders are messed up.

**Comment by zwang** [comment]
@hjanuschka  Thanks for the help. I did try `brew doctor` and it shows my system is ready to brew. Still having the same problem. I guess it is because of this issue: https://github.com/rbenv/rbenv/issues/947

I have to do `sudo` to use `gem`

**Comment by TKBurner** [comment]
@zwang Has this worked before? Are you on Sierra? How do you manage your ruby versions? Thanks!

**Comment by zwang** [comment]
@TKBurner Yes, I think it works before without `sudo`. I am on Sierra, macOS X 10.12.1.  I use rbenv and ruby-build to manage ruby dependencies. It feels like a rbenv ruby-build issue as I linked here: 
https://github.com/rbenv/rbenv/issues/947

**Comment by TKBurner** [comment]
Hi @zwang Can you share your full output? It looks like your fastlane is using system ruby.

**Comment by zwang** [comment]
@TKBurner  it is actually the full output. It just stops there. Before I install rbenv and ruby-build, it is using the system ruby, which is version 2.0. Here is the output regarding ruby version:

```
➜  ~ rbenv versions
  system
* 2.3.1 (set by /usr/local/var/rbenv/version)
```

**Comment by TKBurner** [comment]
Hi @zwang Can you run `which ruby` Thanks!

**Comment by zwang** [comment]
Sure, it is 
```
➜  Pla git:(develop) which ruby
/usr/local/var/rbenv/shims/ruby
```
I think it points to the ruby 2.3.1, which is the only version I installed. 
Thank you.

**Comment by TKBurner** [comment]
@zwang Can you re-install bundler? Thanks!

**Comment by paco-medina** [comment]
I'm having the same issue, even after re-installing bundler, any updates on the solution?

**Comment by KrauseFx** [comment]
We've worked on a new, bundled version of _fastlane_, which contains all required dependencies in one package, give it a try [here](https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/latest.zip) and let us know how it goes 🚀

**Comment by paco-medina** [comment]
This fixed it for me, thanks! :+1:
