### ISSUE TITLE
TERM is missing or TERM=dumb leads to build failure.

### ISSUE THREAD

**Issue by alex-schwartzman** [fastlane/fastlane#703]
STR:
unset TERM
fastlane ios beta

I have noticed, that when I run my build on console, where TERM variable is not set, I get the errors mentioned below, and then build failure. If I set TERM=dumb, fastlane does not complain anymore about missing TERM variable, but still build fails. If I specify TERM=xterm-256color, everything builds successfully.

fastlane version 1.33.0
MacOS 10.10.5 (14F27)

```
37m[11:12:53]: [0m[33mset -o pipefail && xcodebuild -scheme 'CoolApp Alpha' -project './CoolApp.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/Haje/Library/Developer/Xcode/Archives/2015-10-16/CoolApp Alpha 2015-10-16 11.12.53.xcarchive' archive | tee '/Users/Haje/Library/Logs/gym/CoolApp Alpha-CoolApp Alpha.log' | xcpretty[0m
TERM environment variable not set.
[36m▸ Building CoolApp/Share With CoolApp Alpha [Release][0m
TERM environment variable not set.
[36m▸ Compiling ShareViewController.m[0m
TERM environment variable not set.
[36m▸ Compiling ShareViewController.m[0m
TERM environment variable not set.
[36m▸ Linking Share\ With\ CoolApp\ Alpha[0m
TERM environment variable not set.
[36m▸ Linking Share\ With\ CoolApp\ Alpha[0m
TERM environment variable not set.
[36m▸ Generating 'Share\ With\ CoolApp\ Alpha.appex.dSYM'[0m
TERM environment variable not set.
[36m▸ Touching Share[0m
TERM environment variable not set.
```
and then
```
▸ Compiling TCDetailsHeaderView.xib
▸ Compiling TCTutorialOverlayView.xib
▸ Compiling TCExpenseStatusIndicator.xib
▸ Generating 'CoolApp\ Alpha.app.dSYM'
▸ Running script 'Run Script'
▸ Running script 'Run Script'
▸ Copying /Users/Haje/Library/Developer/Xcode/DerivedData/CoolApp-bxgbfwltaimzsxgjhlfcunzcwzwd/ArchiveIntermediates/CoolApp\ Alpha/BuildProductsPath/Release-iphoneos/Share\ With\ CoolApp\ Alpha.appex
skipping copy phase strip, binary is code signed: /Users/Haje/Library/Developer/Xcode/DerivedData/CoolApp-bxgbfwltaimzsxgjhlfcunzcwzwd/ArchiveIntermediates/CoolApp Alpha/IntermediateBuildFilesPath/UninstalledProducts/Share With CoolApp Alpha.appex/Share With CoolApp Alpha
▸ Touching CoolApp
▸ Signing /Users/Haje/Library/Developer/Xcode/DerivedData/CoolApp-bxgbfwltaimzsxgjhlfcunzcwzwd/ArchiveIntermediates/CoolApp\ Alpha/InstallationBuildProductsLocation/Applications/CoolApp\ Alpha.app
▸ Touching CoolApp
[37m[11:14:47]: [0mExit status: 1
[37m[11:14:47]: [0m[33mVariable Dump:[0m
[37m[11:14:47]: [0m{:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
[1m[31m[11:14:47]: [0m[0m[31mError building the application - see the log above[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 122         |
+------+-------------------------------------+-------------+

[1m[31m[11:14:47]: [0m[0m[31mfastlane finished with errors[0m
/Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/error_handler.rb:52:in `handle_build_error': [31mError building the application - see the log above[0m (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/runner.rb:80:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.22.2/lib/fastlane_core/command_executor.rb:62:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.22.2/lib/fastlane_core/command_executor.rb:62:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/runner.rb:76:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/manager.rb:8:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:31:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/runner.rb:48:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/runner.rb:48:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/bin/fastlane:136:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.0/bin/fastlane:142:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

:)

**Comment by xfreebird** [comment]
The same happens and for me.

It looks like an ```gym``` issue see https://github.com/fastlane/gym/issues/127 https://github.com/fastlane/gym/issues/125 .

**Comment by xfreebird** [comment]
This was fixed. It works for me.

**Comment by KrauseFx** [comment]
Make sure to update `fastlane` to the latest version, you're using an old version
