### ISSUE TITLE
Error code signing using fastlane after migration from xCode 7 to xCode 8.1

### ISSUE THREAD

**Issue by fhperuchi** [fastlane/fastlane#7088]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi! It was working with xCode 7 but is not working after I migrated to **xCode 8**. Please help me! It's driving me crazy.

### Error

❌  Code signing is required for product type 'Application' in SDK 'iOS 10.1'

### Important note

I generate the xCode 8 project through [Meteor](https://www.meteor.com/). Please, see the image below:

![image](https://cloud.githubusercontent.com/assets/4641123/20445513/7b3f55b6-adbc-11e6-9aa3-b89163ea87a9.png)

#### Command I've used:
```
FL_UNLOCK_KEYCHAIN_SET_DEFAULT=true FL_UNLOCK_KEYCHAIN_PATH=/Users/jenkins/Library/Keychains/login.keychain FL_UNLOCK_KEYCHAIN_PASSWORD=****** fastlane --verbose ios test_flight username:abc@abc.com password:******
```

#### Command output:
```
Successfully loaded Appfile at path '/Users/jenkins/.jenkinsslave/workspace/cavadinha_app_homolog_meteor_itunes_google_play_publish/fastlane/Appfile'
- app_identifier: 'com.Cavadinha'
- apple_id: 'applestore@tecsinapse.com.br'
- apple_dev_portal_id: 'applestore@tecsinapse.com.br'
- itunes_connect_id: 'applestore@tecsinapse.com.br'
- team_id: 'YXZWB2384X'
- itc_team_id: 'YXZWB2384X'
- itc_team_name: 'TecSinapse Tecnologia da Informação Ltda'
-------
DEBUG [2016-11-18 15:11:17.63]: Checking if there are any plugins that should be loaded...
DEBUG [2016-11-18 15:11:17.64]: Using username: applestore@tecsinapse.com.br
DEBUG [2016-11-18 15:11:17.64]: Using password: *****
INFO [2016-11-18 15:11:17.65]: -------------------------------------------------
INFO [2016-11-18 15:11:17.65]: --- Step: Verifying required fastlane version ---
INFO [2016-11-18 15:11:17.65]: -------------------------------------------------
INFO [2016-11-18 15:11:17.65]: Your fastlane version 1.110.0 matches the minimum requirement of 1.101.0  ✅
INFO [2016-11-18 15:11:17.66]: ------------------------------
INFO [2016-11-18 15:11:17.66]: --- Step: default_platform ---
INFO [2016-11-18 15:11:17.66]: ------------------------------
INFO [2016-11-18 15:11:17.76]: Driving the lane 'ios test_flight' 🚀
INFO [2016-11-18 15:11:17.77]: -----------------------------
INFO [2016-11-18 15:11:17.77]: --- Step: unlock_keychain ---
INFO [2016-11-18 15:11:17.77]: -----------------------------
DEBUG [2016-11-18 15:11:17.77]: Taking value for 'path' from environment variable 'FL_UNLOCK_KEYCHAIN_PATH'
DEBUG [2016-11-18 15:11:17.77]: Taking value for 'set_default' from environment variable 'FL_UNLOCK_KEYCHAIN_SET_DEFAULT'
DEBUG [2016-11-18 15:11:17.84]: Taking value for 'password' from environment variable 'FL_UNLOCK_KEYCHAIN_PASSWORD'
INFO [2016-11-18 15:11:17.94]: ------------------------------
INFO [2016-11-18 15:11:17.94]: --- Step: recreate_schemes ---
INFO [2016-11-18 15:11:17.94]: ------------------------------
INFO [2016-11-18 15:11:17.94]: Recreate schemes for project: build_files/ios/project/Cavadinha.xcodeproj
INFO [2016-11-18 15:11:18.14]: ----------------------------------
INFO [2016-11-18 15:11:18.14]: --- Step: set_info_plist_value ---
INFO [2016-11-18 15:11:18.14]: ----------------------------------
INFO [2016-11-18 15:11:18.14]: -----------------
INFO [2016-11-18 15:11:18.15]: --- Step: gym ---
INFO [2016-11-18 15:11:18.15]: -----------------
INFO [2016-11-18 15:11:18.46]: $ xcodebuild -list -project build_files/ios/project/Cavadinha.xcodeproj
INFO [2016-11-18 15:11:20.45]: $ xcodebuild clean -showBuildSettings -scheme Cavadinha -project build_files/ios/project/Cavadinha.xcodeproj

+----------------------+---------------------------------------------+
|                       Summary for gym 1.12.0                       |
+----------------------+---------------------------------------------+
| project              | build_files/ios/project/Cavadinha.xcodeproj |
| scheme               | Cavadinha                                   |
| destination          | generic/platform=iOS                        |
| output_name          | Cavadinha                                   |
| clean                | false                                       |
| output_directory     | .                                           |
| silent               | false                                       |
| use_legacy_build_api | false                                       |
| buildlog_path        | ~/Library/Logs/gym                          |
| xcode_path           | /Applications/Xcode.app                     |
+----------------------+---------------------------------------------+

+-------------------------------------------------------------------------------------------------------------------+----------------------+
|                                                         Generated Build Command                                                          |
+-------------------------------------------------------------------------------------------------------------------+----------------------+
| Option                                                                                                            | Value                |
+-------------------------------------------------------------------------------------------------------------------+----------------------+
| set -o pipefail &&                                                                                                |                      |
| xcodebuild                                                                                                        |                      |
| -scheme Cavadinha                                                                                                 |                      |
| -project build_files/ios/project/Cavadinha.xcodeproj                                                              |                      |
| -destination                                                                                                      | generic/platform=iOS |
| -archivePath /Users/jenkins/Library/Developer/Xcode/Archives/2016-11-18/Cavadinha\ 2016-11-18\ 15.11.22.xcarchive |                      |
| archive                                                                                                           |                      |
| | tee /Users/jenkins/Library/Logs/gym/Cavadinha-Cavadinha.log                                                      |                      |
| | xcpretty                                                                                                         |                      |
+-------------------------------------------------------------------------------------------------------------------+----------------------+
INFO [2016-11-18 15:11:22.23]: $ set -o pipefail && xcodebuild -scheme Cavadinha -project build_files/ios/project/Cavadinha.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/jenkins/Library/Developer/Xcode/Archives/2016-11-18/Cavadinha\ 2016-11-18\ 15.11.22.xcarchive archive | tee /Users/jenkins/Library/Logs/gym/Cavadinha-Cavadinha.log | xcpretty
INFO [2016-11-18 15:11:24.19]: ▸ Building CordovaLib/CordovaLib [Release]
INFO [2016-11-18 15:11:24.22]: ▸ Check Dependencies
INFO [2016-11-18 15:11:24.61]: ▸ Copying CDVWebViewEngineProtocol.h
INFO [2016-11-18 15:11:24.62]: ▸ Copying CDVScreenOrientationDelegate.h
INFO [2016-11-18 15:11:24.62]: ▸ Copying CDV.h
INFO [2016-11-18 15:11:24.62]: ▸ Copying CDVCommandDelegateImpl.h
INFO [2016-11-18 15:11:24.62]: ▸ Copying CDVCommandQueue.h
INFO [2016-11-18 15:11:24.64]: ▸ Copying CDVWhitelist.h
INFO [2016-11-18 15:11:24.65]: ▸ Copying CDVAppDelegate.h
INFO [2016-11-18 15:11:24.66]: ▸ Copying CDVPlugin+Resources.h
INFO [2016-11-18 15:11:24.66]: ▸ Copying CDVAvailability.h
INFO [2016-11-18 15:11:24.67]: ▸ Copying CDVUIWebViewDelegate.h
INFO [2016-11-18 15:11:24.67]: ▸ Copying CDVPluginResult.h
INFO [2016-11-18 15:11:24.67]: ▸ Copying NSMutableArray+QueueAdditions.h
INFO [2016-11-18 15:11:24.67]: ▸ Copying CDVInvokedUrlCommand.h
INFO [2016-11-18 15:11:24.67]: ▸ Copying NSDictionary+CordovaPreferences.h
INFO [2016-11-18 15:11:24.67]: ▸ Copying CDVPlugin.h
INFO [2016-11-18 15:11:24.68]: ▸ Copying CDVURLProtocol.h
INFO [2016-11-18 15:11:24.68]: ▸ Copying CDVAvailabilityDeprecated.h
INFO [2016-11-18 15:11:24.68]: ▸ Copying CDVCommandDelegate.h
INFO [2016-11-18 15:11:24.68]: ▸ Copying CDVUserAgentUtil.h
INFO [2016-11-18 15:11:24.68]: ▸ Copying CDVTimer.h
INFO [2016-11-18 15:11:24.68]: ▸ Copying CDVConfigParser.h
INFO [2016-11-18 15:11:24.68]: ▸ Copying CDVViewController.h
INFO [2016-11-18 15:11:24.71]: ▸ Precompiling CordovaLib_Prefix.pch
INFO [2016-11-18 15:11:25.22]: ▸ Precompiling CordovaLib_Prefix.pch
INFO [2016-11-18 15:11:25.34]: ▸ Compiling CDVViewController.m
INFO [2016-11-18 15:11:26.34]: ▸ Compiling NSDictionary+CordovaPreferences.m
INFO [2016-11-18 15:11:26.34]: ▸ Compiling CDVAppDelegate.m
INFO [2016-11-18 15:11:26.34]: ▸ Compiling CDVUIWebViewDelegate.m
INFO [2016-11-18 15:11:26.41]: ▸ Compiling CDVCommandDelegateImpl.m
INFO [2016-11-18 15:11:26.58]: ▸ Compiling CDVJSON_private.m
INFO [2016-11-18 15:11:26.58]: ▸ Compiling CDVWhitelist.m
INFO [2016-11-18 15:11:26.83]: ▸ Compiling CDVInvokedUrlCommand.m
INFO [2016-11-18 15:11:26.83]: ▸ Compiling CDVTimer.m
INFO [2016-11-18 15:11:26.85]: ▸ Compiling CDVUserAgentUtil.m
INFO [2016-11-18 15:11:27.11]: ▸ Compiling CDVConfigParser.m
INFO [2016-11-18 15:11:27.12]: ▸ Compiling CDVGestureHandler.m
INFO [2016-11-18 15:11:27.43]: ▸ Compiling CDVHandleOpenURL.m
INFO [2016-11-18 15:11:27.43]: ▸ Compiling CDVUIWebViewNavigationDelegate.m
INFO [2016-11-18 15:11:27.99]: ▸ Compiling NSMutableArray+QueueAdditions.m
INFO [2016-11-18 15:11:27.99]: ▸ Compiling CDVCommandQueue.m
INFO [2016-11-18 15:11:28.11]: ▸ Compiling CDVPluginResult.m
INFO [2016-11-18 15:11:28.52]: ▸ Compiling CDVPlugin+Resources.m
INFO [2016-11-18 15:11:28.55]: ▸ Compiling CDVURLProtocol.m
INFO [2016-11-18 15:11:29.05]: ▸ Compiling CDVUIWebViewEngine.m
INFO [2016-11-18 15:11:29.11]: ▸ Compiling CDVPlugin.m
INFO [2016-11-18 15:11:29.45]: ▸ Compiling CDVLocalStorage.m
INFO [2016-11-18 15:11:30.00]: ▸ Compiling CDVIntentAndNavigationFilter.m
INFO [2016-11-18 15:11:30.00]: ▸ Compiling CDVViewController.m
INFO [2016-11-18 15:11:31.13]: ▸ Compiling NSDictionary+CordovaPreferences.m
INFO [2016-11-18 15:11:31.13]: ▸ Compiling CDVAppDelegate.m
INFO [2016-11-18 15:11:31.13]: ▸ Compiling CDVUIWebViewDelegate.m
INFO [2016-11-18 15:11:31.13]: ▸ Compiling CDVCommandDelegateImpl.m
INFO [2016-11-18 15:11:31.56]: ▸ Compiling CDVJSON_private.m
INFO [2016-11-18 15:11:31.57]: ▸ Compiling CDVWhitelist.m
INFO [2016-11-18 15:11:32.13]: ▸ Compiling CDVInvokedUrlCommand.m
INFO [2016-11-18 15:11:32.13]: ▸ Compiling CDVTimer.m
INFO [2016-11-18 15:11:32.13]: ▸ Compiling CDVUserAgentUtil.m
INFO [2016-11-18 15:11:32.65]: ▸ Compiling CDVConfigParser.m
INFO [2016-11-18 15:11:32.65]: ▸ Compiling CDVGestureHandler.m
INFO [2016-11-18 15:11:32.87]: ▸ Compiling CDVHandleOpenURL.m
INFO [2016-11-18 15:11:32.99]: ▸ Compiling CDVUIWebViewNavigationDelegate.m
INFO [2016-11-18 15:11:33.15]: ▸ Compiling NSMutableArray+QueueAdditions.m
INFO [2016-11-18 15:11:33.15]: ▸ Compiling CDVCommandQueue.m
INFO [2016-11-18 15:11:33.67]: ▸ Compiling CDVPluginResult.m
INFO [2016-11-18 15:11:33.67]: ▸ Compiling CDVPlugin+Resources.m
INFO [2016-11-18 15:11:34.05]: ▸ Compiling CDVURLProtocol.m
INFO [2016-11-18 15:11:34.08]: ▸ Compiling CDVUIWebViewEngine.m
INFO [2016-11-18 15:11:34.56]: ▸ Compiling CDVPlugin.m
INFO [2016-11-18 15:11:34.58]: ▸ Compiling CDVIntentAndNavigationFilter.m
INFO [2016-11-18 15:11:35.32]: ▸ Compiling CDVLocalStorage.m
INFO [2016-11-18 15:11:35.58]: ▸ Building library libCordova.a
INFO [2016-11-18 15:11:35.63]: ▸ Building library libCordova.a
INFO [2016-11-18 15:11:37.46]: ▸ Building Cavadinha/Cavadinha [Release]
INFO [2016-11-18 15:11:37.46]: ▸ Check Dependencies
INFO [2016-11-18 15:11:37.47]: ▸ ❌  Code signing is required for product type 'Application' in SDK 'iOS 10.1'
INFO [2016-11-18 15:11:37.47]: ▸ ** ARCHIVE FAILED **
INFO [2016-11-18 15:11:37.47]: ▸ The following build commands failed:
INFO [2016-11-18 15:11:37.47]: ▸ Check dependencies
INFO [2016-11-18 15:11:37.47]: ▸ (1 failure)
▸ Building CordovaLib/CordovaLib [Release]
▸ Check Dependencies
▸ Copying CDVWebViewEngineProtocol.h
▸ Copying CDVScreenOrientationDelegate.h
▸ Copying CDV.h
▸ Copying CDVCommandDelegateImpl.h
▸ Copying CDVCommandQueue.h
▸ Copying CDVWhitelist.h
▸ Copying CDVAppDelegate.h
▸ Copying CDVPlugin+Resources.h
▸ Copying CDVAvailability.h
▸ Copying CDVUIWebViewDelegate.h
▸ Copying CDVPluginResult.h
▸ Copying NSMutableArray+QueueAdditions.h
▸ Copying CDVInvokedUrlCommand.h
▸ Copying NSDictionary+CordovaPreferences.h
▸ Copying CDVPlugin.h
▸ Copying CDVURLProtocol.h
▸ Copying CDVAvailabilityDeprecated.h
▸ Copying CDVCommandDelegate.h
▸ Copying CDVUserAgentUtil.h
▸ Copying CDVTimer.h
▸ Copying CDVConfigParser.h
▸ Copying CDVViewController.h
▸ Precompiling CordovaLib_Prefix.pch
▸ Precompiling CordovaLib_Prefix.pch
▸ Compiling CDVViewController.m
▸ Compiling NSDictionary+CordovaPreferences.m
▸ Compiling CDVAppDelegate.m
▸ Compiling CDVUIWebViewDelegate.m
▸ Compiling CDVCommandDelegateImpl.m
▸ Compiling CDVJSON_private.m
▸ Compiling CDVWhitelist.m
▸ Compiling CDVInvokedUrlCommand.m
▸ Compiling CDVTimer.m
▸ Compiling CDVUserAgentUtil.m
▸ Compiling CDVConfigParser.m
▸ Compiling CDVGestureHandler.m
▸ Compiling CDVHandleOpenURL.m
▸ Compiling CDVUIWebViewNavigationDelegate.m
▸ Compiling NSMutableArray+QueueAdditions.m
▸ Compiling CDVCommandQueue.m
▸ Compiling CDVPluginResult.m
▸ Compiling CDVPlugin+Resources.m
▸ Compiling CDVURLProtocol.m
▸ Compiling CDVUIWebViewEngine.m
▸ Compiling CDVPlugin.m
▸ Compiling CDVLocalStorage.m
▸ Compiling CDVIntentAndNavigationFilter.m
▸ Compiling CDVViewController.m
▸ Compiling NSDictionary+CordovaPreferences.m
▸ Compiling CDVAppDelegate.m
▸ Compiling CDVUIWebViewDelegate.m
▸ Compiling CDVCommandDelegateImpl.m
▸ Compiling CDVJSON_private.m
▸ Compiling CDVWhitelist.m
▸ Compiling CDVInvokedUrlCommand.m
▸ Compiling CDVTimer.m
▸ Compiling CDVUserAgentUtil.m
▸ Compiling CDVConfigParser.m
▸ Compiling CDVGestureHandler.m
▸ Compiling CDVHandleOpenURL.m
▸ Compiling CDVUIWebViewNavigationDelegate.m
▸ Compiling NSMutableArray+QueueAdditions.m
▸ Compiling CDVCommandQueue.m
▸ Compiling CDVPluginResult.m
▸ Compiling CDVPlugin+Resources.m
▸ Compiling CDVURLProtocol.m
▸ Compiling CDVUIWebViewEngine.m
▸ Compiling CDVPlugin.m
▸ Compiling CDVIntentAndNavigationFilter.m
▸ Compiling CDVLocalStorage.m
▸ Building library libCordova.a
▸ Building library libCordova.a
▸ Building Cavadinha/Cavadinha [Release]
▸ Check Dependencies

❌  Code signing is required for product type 'Application' in SDK 'iOS 10.1'


** ARCHIVE FAILED **


The following build commands failed:
Check dependencies
(1 failure)
ERROR [2016-11-18 15:11:37.57]: Exit status: 65
ERROR [2016-11-18 15:11:37.57]: 📋  For a more detailed error log, check the full log at:
ERROR [2016-11-18 15:11:37.57]: 📋  /Users/jenkins/Library/Logs/gym/Cavadinha-Cavadinha.log
INFO [2016-11-18 15:11:37.59]: -------------------
INFO [2016-11-18 15:11:37.59]: --- Step: slack ---
INFO [2016-11-18 15:11:37.59]: -------------------
DEBUG [2016-11-18 15:11:37.59]: Taking value for 'slack_url' from environment variable 'SLACK_URL'
DEBUG [2016-11-18 15:11:37.59]: Taking value for 'channel' from environment variable 'FL_SLACK_CHANNEL'
DEBUG [2016-11-18 15:11:37.59]: Taking value for 'channel' from environment variable 'FL_SLACK_CHANNEL'
INFO [2016-11-18 15:11:37.87]: Successfully sent Slack notification
WARN [2016-11-18 15:11:37.87]: Variable Dump:
INFO [2016-11-18 15:11:37.87]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test_flight"}
ERROR [2016-11-18 15:11:37.87]: Error building the application - see the log above
INFO [2016-11-18 15:11:37.88]: Successfully generated documentation at path '/Users/jenkins/.jenkinsslave/workspace/cavadinha_app_homolog_meteor_itunes_google_play_publish/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | unlock_keychain                     | 0           |
| 4    | recreate_schemes                    | 0           |
| 5    | set_info_plist_value                | 0           |
| 💥    | gym                                 | 19          |
| 7    | slack                               | 0           |
+------+-------------------------------------+-------------+

ERROR [2016-11-18 15:11:37.90]: fastlane finished with errors
/usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane_core-0.56.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Error building the application - see the log above (FastlaneCore::Interface::FastlaneError)
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane_core-0.56.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/gym-1.12.0/lib/gym/error_handler.rb:54:in `handle_build_error'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/gym-1.12.0/lib/gym/runner.rb:101:in `block in build_app'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane_core-0.56.0/lib/fastlane_core/command_executor.rb:88:in `execute'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/gym-1.12.0/lib/gym/runner.rb:97:in `build_app'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/gym-1.12.0/lib/gym/runner.rb:12:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/gym-1.12.0/lib/gym/manager.rb:14:in `work'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/actions/gym.rb:24:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/runner.rb:187:in `block in execute_action'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/runner.rb:186:in `chdir'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/runner.rb:186:in `execute_action'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:29:in `block (2 levels) in parsing_binding'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/commands_generator.rb:95:in `block (2 levels) in run'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane_core-0.56.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/commands_generator.rb:292:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/commands_generator.rb:36:in `start'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/fastlane-1.110.0/bin/fastlane:5:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.3.1/bin/fastlane:23:in `load'
        from /usr/local/rvm/rubies/ruby-2.3.1/bin/fastlane:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

[15:04:47]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                         |
| ------------------- | --------------------------------------------- |
| OS                  | 10.11.6                                       |
| Ruby                | 2.3.1                                         |
| Bundler?            | false                                         |
| Git                 | git version 2.9.3 (Apple Git-75)              |
| Installation Source | /usr/local/rvm/rubies/ruby-2.3.1/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                    |
| Ruby Lib Dir        | /usr/local/rvm/rubies/ruby-2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                   |
| Is contained        | false                                         |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/   |
| Xcode Version       | 8.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required. Update this, if you use features of a newer version
fastlane_version '1.101.0'

default_platform :ios

before_all do
  ENV['SLACK_URL'] = 'https://hooks.slack.com/services/abc/abc'
end

platform :ios do

  desc 'Submit a new Beta Build to Apple TestFlight'
  lane :test_flight do
    unlock_keychain

    recreate_schemes(
      project: 'build_files/ios/project/Cavadinha.xcodeproj'
    )

    set_info_plist_value(
      key: 'ITSAppUsesNonExemptEncryption',
      value: 'false',
      path: 'build_files/ios/project/Cavadinha/Cavadinha-Info.plist'
    )

    gym(
        project: 'build_files/ios/project/Cavadinha.xcodeproj',
        scheme: 'Cavadinha'
    )

    testflight(
        skip_waiting_for_build_processing: true
    )

  end

  desc 'Deploy a new app version to iTunnes Connect'
  lane :app_store do
    unlock_keychain

  recreate_schemes(
      project: 'build_files/ios/project/Cavadinha.xcodeproj'
    )

    gym(
      project: 'build_files/ios/project/Cavadinha.xcodeproj',
      scheme: 'Cavadinha'
    )

    deliver(force: true)
  end

  after_all do |lane|
    slack(
      message: 'Cavadinha successfully published on iTunnes Connect!',
      use_webhook_configured_username_and_icon: true,
      success: true
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      use_webhook_configured_username_and_icon: true,
      success: false
    )
  end
end

platform :android do

  desc 'Deploy a new app version to the Google Play'
  lane :googleplay do
    supply(
      package_name: 'com.Cavadinha',
      json_key: 'app/cavadinha_play_store_file.json',
      apk_paths: %w(build_files/android/cavadinha-armv7.apk build_files/android/cavadinha-x86.apk)
    )
  end

  after_all do |lane|
    slack(
      message: 'Cavadinha successfully published on Google Play!',
      use_webhook_configured_username_and_icon: true,
      success: true
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      use_webhook_configured_username_and_icon: true,
      success: false
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.Cavadinha"
apple_id "applestore@tecsinapse.com.br"
apple_dev_portal_id "applestore@tecsinapse.com.br"
itunes_connect_id "applestore@tecsinapse.com.br"
team_id "YXZWB2384X"
itc_team_id "YXZWB2384X"
itc_team_name "TecSinapse Tecnologia da Informação Ltda"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date  |
| deliver             | 1.15.1  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.56.0       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
</details>


*generated on:* **2016-11-18**
</details>

**Comment by fhperuchi** [comment]
@fastlane-bot yes. I saw this link content, but I didn't help me.

**Comment by hjanuschka** [comment]
can you have a look at this issue-comment, https://github.com/fastlane/fastlane/issues/6832#issuecomment-257883114 hopefully this will help you. please let me know.

**Comment by fhperuchi** [comment]
Thank you @hjanuschka ! It solved my problem. :+1: 

I had to implement this way:

  ```
update_project_provisioning(
        xcodeproj: 'build_files/ios/project/Cavadinha.xcodeproj',
        profile: 'app/env/match_AppStore_comCavadinha.mobileprovision',
        target_filter: '.*',
        build_configuration: '.*'
    )

    gym(
        project: 'build_files/ios/project/Cavadinha.xcodeproj',
        scheme: 'Cavadinha'
    )

    testflight
```

**Comment by hjanuschka** [comment]
good to hear ! can you close the issue?

**Comment by milch** [comment]
@fhperuchi Since your problem seems to be solved, I'm going to close this. @hjanuschka thanks for the help!
