### ISSUE TITLE
how to configure "--xcpretty_report_json"?

### ISSUE THREAD

**Issue by diaojunxian** [fastlane/fastlane#7140]
Hi, I had add `--xcpretty_report_json "path"`,and I would like to get the xcpretty `json-compilation-database`，but I had got the log,you could see that it had archive succeeded  ：
```
▸ Archive Succeeded
/Users/djx/.rvm/gems/ruby-2.3.1@global/gems/xcpretty-0.2.4/lib/xcpretty/reporters/json_compilation_database.rb:45:in `initialize': Is a directory @ rb_sysopen - /Users/djx/Documents/MIFit2-iOS/APP/2016_11_23_11_08_out/ (Errno::EISDIR)
from /Users/djx/.rvm/gems/ruby-2.3.1@global/gems/xcpretty-0.2.4/lib/xcpretty/reporters/json_compilation_database.rb:45:in `open'
from /Users/djx/.rvm/gems/ruby-2.3.1@global/gems/xcpretty-0.2.4/lib/xcpretty/reporters/json_compilation_database.rb:45:in `write_report'
from /Users/djx/.rvm/gems/ruby-2.3.1@global/gems/xcpretty-0.2.4/lib/xcpretty/reporters/reporter.rb:30:in `finish'
from /Users/djx/.rvm/gems/ruby-2.3.1@global/gems/xcpretty-0.2.4/bin/xcpretty:89:in `each'
from /Users/djx/.rvm/gems/ruby-2.3.1@global/gems/xcpretty-0.2.4/bin/xcpretty:89:in `<top (required)>'
from /Users/djx/.rvm/rubies/ruby-2.3.1/bin/xcpretty:22:in `load'
from /Users/djx/.rvm/rubies/ruby-2.3.1/bin/xcpretty:22:in `<main>'
from /Users/djx/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `eval'
from /Users/djx/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `<main>'
[11:16:09]: Exit status: 1
```
And my gym code is:
```
DEVELOPER_DIR="/Applications/Xcode.app" gym --workspace ${workspace_path} 
--scheme ${scheme} --clean true 
--configuration ${configuration} 
--export_method ${export_method} 
--archive_path ${archive_path} 
--codesigning_identity "${rightDistributionSign}" 
--xcpretty_report_json ${ipa_path} 
--export_options ${ExoptionPlist} --output_directory ${ipa_path} --output_name ${ipa_name} || exit

```

**Comment by hjanuschka** [comment]
hmmm @diaojunxian  have you tried setting xcpretty_report_json to a filename instead of ipa_path?

**Comment by diaojunxian** [comment]
@hjanuschka  thanks a lot, I had solved it.
