### ISSUE TITLE
[Spaceship] Can not create a new localization language on ItunesConnect

### ISSUE THREAD

**Issue by richarddigifit** [fastlane/fastlane#7161]
### Issue Description

I am trying to add a new language to my app on ItunesConnect

I am using the following Ruby code to do so with Spaceship

```ruby
app_itunes = Spaceship::Tunes::Application.find(bundle_id)
v = app_itunes.edit_version
v.create_languages(["nl"])
v.save!
```

However this produces an error
```
/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:221:in `handle_itc_response': There are one or more errors on the page. (Spaceship::TunesClient::ITunesConnectError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:369:in `block in update_app_version!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:964:in `with_tunes_retry'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:362:in `update_app_version!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.37.0/lib/spaceship/tunes/app_version.rb:299:in `save!'
	from my_script.rb:27:in `<main>'
```

**Comment by richarddigifit** [comment]
I don't have the fastlane gem installed... I just use the spaceship ruby exposed functions

**Comment by hjanuschka** [comment]
@richarddigifit have you tried? `nl-NL`

**Comment by hjanuschka** [comment]
also - for working with spaceship - try setting `VERBOSE=1` as an env ;)
it will debug http traffic from and to apple 🙏

**Comment by richarddigifit** [comment]
ahh thank you, guess I should have read the documentation better haha
