### ISSUE TITLE
Issue uploading w/deliver, only when run in Jenkins

### ISSUE THREAD

**Issue by elliot-nelson** [fastlane/fastlane#7225]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm encountering an issue that I'm not sure how to tackle.  I am running `deliver` on OSX, and everything about it works just fine -- but when I run the same shell script from within a Jenkins context, the Application Loader barfs when it attempts to describe the IPA -- it seems to be deflating only a few kilobytes instead of the full IPA (which then causes an "invalid binary" error).

I _don't_ think there is anything wrong with fastlane in this case, I think there is a negative interaction between Jenkins and Application Loader.  Opening an issue in the desperate hope that someone has seen a similar issue, or has an idea what might fix it (I've been scouring Google with no luck whatsoever).  Or perhaps can tell me if this jingle.leghorn thing (whatever is deflating the binary) has additional options I can pass to it.

##### Complete output when running fastlane, including the stack trace and command used

Quick preface, so you know what to look for.  Here is the snippet of the logs where things go awry:

```
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: INFO: Starting media analysis of assets
DEBUG [2016-11-29 06:45:00.67]: [Transporter]: DEBUG: Handling asset: filename=459ccdda2286f3794c61fd6fb59b477e.ipa,uti=com.apple.ipa,role=source,describe=true
DEBUG [2016-11-29 06:45:00.67]: [Transporter]: DEBUG: Using container type tool name and version: iOS App Describer:1.25
DEBUG [2016-11-29 06:45:00.67]: [Transporter]: DEBUG: Using path: /tmp/429775439.itmsp/459ccdda2286f3794c61fd6fb59b477e.ipa
DEBUG [2016-11-29 06:45:01.81]: [Transporter]: DBG-X: Asset description: <?xml version="1.1" encoding="UTF-8"?>
DEBUG [2016-11-29 06:45:01.81]: [Transporter]: DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@162d677b
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X: Deflated 2173 bytes to 807
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: INFO: Asset media analysis has completed
```

As you can see, the deflated bytes are way too small -- almost like it is mixing up the contents of the XML file with the contents of the IPA file (and that telltale "Asset description" line).  Here is what a successful run looks like:

```
DEBUG [2016-11-29 06:18:53.53]: [Transporter]: INFO: Starting media analysis of assets
DEBUG [2016-11-29 06:18:53.96]: [Transporter]: DEBUG: Handling asset: filename=459ccdda2286f3794c61fd6fb59b477e.ipa,uti=com.apple.ipa,role=source,describe=true
DEBUG [2016-11-29 06:18:53.96]: [Transporter]: DEBUG: Using container type tool name and version: iOS App Describer:1.25
DEBUG [2016-11-29 06:18:53.96]: [Transporter]: DEBUG: Using path: /tmp/429775439.itmsp/459ccdda2286f3794c61fd6fb59b477e.ipa
DEBUG [2016-11-29 06:19:22.67]: [Transporter]: DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@1879c4e3
DEBUG [2016-11-29 06:19:22.97]: [Transporter]: DBG-X: Deflated 4582229 bytes to 686068
DEBUG [2016-11-29 06:19:22.98]: [Transporter]: INFO: Asset media analysis has completed
```

That additional DBG-X line is missing, and the byte count is correct.  (I have run both the successful and failure cases dozens of times, and every time the log comes out the same -- everything before this section is identical.)

Here's a complete run of the failing case:

```
DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS=-t DAV deliver -u dpreleasebot@company.com -i ./build_output/APP.ipa --skip_screenshots --skip_metadata --verbose
INFO [2016-11-29 06:44:42.26]: Login to iTunes Connect (dpreleasebot@company.com)
Looking for iTunes Connect Team with ID XXXXXX
INFO [2016-11-29 06:44:45.13]: Login successful

+-----------------------+-----------------------+
|            [32mdeliver 1.16.0 Summary[0m             |
+-----------------------+-----------------------+
| username              | dpreleasebot@company.com  |
| ipa                   | ./build_output/APP.ipa |
| skip_screenshots      | true                  |
| skip_metadata         | true                  |
| app_identifier        | com.comp.compgo         |
| screenshots_path      | ./screenshots         |
| metadata_path         | ./metadata            |
| app_version           | 8.0.0                 |
| platform              | ios                   |
| skip_binary_upload    | false                 |
| force                 | false                 |
| submit_for_review     | false                 |
| automatic_release     | false                 |
| overwrite_screenshots | false                 |
+-----------------------+-----------------------+

INFO [2016-11-29 06:44:46.31]: Making sure the latest version on iTunes Connect matches '8.0.0' from the ipa file...
INFO [2016-11-29 06:44:48.47]: [32m'8.0.0' is the latest version on iTunes Connect[0m
INFO [2016-11-29 06:44:56.63]: Uploading binary to iTunes Connect
INFO [2016-11-29 06:44:56.93]: [32mWrote XML data to '/tmp/429775439.itmsp'[0m
INFO [2016-11-29 06:44:57.08]: Going to upload updated app to iTunes Connect
INFO [2016-11-29 06:44:57.08]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
DEBUG [2016-11-29 06:44:57.15]: /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -classpath /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/lib/itmstransporter-launcher.jar com.apple.transporter.Application -m upload -u dpreleasebot@company.com -p YourPassword -f /tmp/429775439.itmsp -t DAV -t Signiant -k 100000 2>&1
DEBUG [2016-11-29 06:44:59.08]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
DEBUG [2016-11-29 06:44:59.18]: [Transporter]: INFO: Logging configured successfully.
DEBUG [2016-11-29 06:44:59.18]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2016-11-29 06:44:59.20]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2016-11-29 06:44:59.20]: [Transporter]: DEBUG: Saving configuration to local path: /Users/hadronci/.itmstransporter/Defaults.properties
DEBUG [2016-11-29 06:44:59.20]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.9.1]
DEBUG [2016-11-29 06:44:59.20]: [Transporter]: INFO: OS identifier: Mac OS X 10.12.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-11-29 06:44:59.21]: [Transporter]: INFO: Memory: [JVM] 853M free, 982M total, 982M max [System] (Physical) 11146M free, 16384M total (Swap) 0 free, 0 total
DEBUG [2016-11-29 06:44:59.21]: [Transporter]: INFO: Upload mode selected.
DEBUG [2016-11-29 06:44:59.22]: [Transporter]: INFO: Examining the package at: /tmp/429775439.itmsp
DEBUG [2016-11-29 06:44:59.22]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
DEBUG [2016-11-29 06:44:59.22]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
DEBUG [2016-11-29 06:44:59.22]: [Transporter]: INFO: Gathering the list of valid files from the package ...
DEBUG [2016-11-29 06:44:59.22]: [Transporter]: DEBUG:   459ccdda2286f3794c61fd6fb59b477e.ipa will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2016-11-29 06:44:59.22]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2016-11-29 06:44:59.22]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
DEBUG [2016-11-29 06:44:59.22]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
DEBUG [2016-11-29 06:44:59.24]: [Transporter]: INFO: Performing authentication of package 429775439.itmsp ...
DEBUG [2016-11-29 06:44:59.24]: [Transporter]: DBG-X: Memory: [JVM] 838M free, 982M total, 982M max [System] (Physical) 11134M free, 16384M total (Swap) 0 free, 0 total
DEBUG [2016-11-29 06:44:59.24]: [Transporter]: DBG-X: Memory: [JVM] 838M free, 982M total, 982M max [System] (Physical) 11134M free, 16384M total (Swap) 0 free, 0 total
DEBUG [2016-11-29 06:44:59.24]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2016-11-29 06:44:59.24]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-11-29 06:44:59.24]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-11-29 06:44:59.24]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.0
DEBUG [2016-11-29 06:44:59.24]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.12.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-11-29 06:44:59.25]: [Transporter]: DBG-X:   parameter Password = **hidden value**
DEBUG [2016-11-29 06:44:59.25]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u dpreleasebot@company.com -p **hidden value** -f /tmp/429775439.itmsp -t DAV -t Signiant -k 100000
DEBUG [2016-11-29 06:44:59.25]: [Transporter]: DBG-X:   parameter Username = dpreleasebot@company.com
DEBUG [2016-11-29 06:44:59.25]: [Transporter]: DBG-X:   parameter Version = 1.9.1
DEBUG [2016-11-29 06:44:59.25]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-11-29 06:44:59.25]: [Transporter]: INFO: id = 20161129064459-636
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter SessionId = **hidden value**
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter SharedSecret = **hidden value**
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X: Deflated 451 bytes to 392
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X: Using operation named: validateMetadata
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.0
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter Files = [459ccdda2286f3794c61fd6fb59b477e.ipa, metadata.xml]
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter MetadataChecksum = 7ac6da2c5b6e9101eb54bc6dc52f3fa5
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.12.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter PackageName = 429775439.itmsp
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter PackageSize = 64955312
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u dpreleasebot@company.com -p **hidden value** -f /tmp/429775439.itmsp -t DAV -t Signiant -k 100000
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter Username = dpreleasebot@company.com
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter Version = 1.9.1
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-11-29 06:44:59.51]: [Transporter]: INFO: id = 20161129064459-306
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: DBG-X:   parameter CPUToken = 768734d7-fa59-4858-a29d-f4bcea9d261b/1480430700093
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=459ccdda2286f3794c61fd6fb59b477e.ipa}]
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: DBG-X:   parameter FileSizes = {459ccdda2286f3794c61fd6fb59b477e.ipa=64954861}
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: DBG-X:   parameter Checksums = {459ccdda2286f3794c61fd6fb59b477e.ipa=d33e35a5eaccf8d5ee0fd9f9c97eded6}
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: DBG-X:   parameter Success = true
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, 459ccdda2286f3794c61fd6fb59b477e.ipa]
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: DBG-X:   parameter ProviderNameForToken = HomeBoxOfficeInc
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: INFO: The list of files requested for upload by Apple is: [metadata.xml, 459ccdda2286f3794c61fd6fb59b477e.ipa].  These are the files that will be uploaded.
DEBUG [2016-11-29 06:45:00.23]: [Transporter]: INFO: Starting media analysis of assets
DEBUG [2016-11-29 06:45:00.67]: [Transporter]: DEBUG: Handling asset: filename=459ccdda2286f3794c61fd6fb59b477e.ipa,uti=com.apple.ipa,role=source,describe=true
DEBUG [2016-11-29 06:45:00.67]: [Transporter]: DEBUG: Using container type tool name and version: iOS App Describer:1.25
DEBUG [2016-11-29 06:45:00.67]: [Transporter]: DEBUG: Using path: /tmp/429775439.itmsp/459ccdda2286f3794c61fd6fb59b477e.ipa
DEBUG [2016-11-29 06:45:01.81]: [Transporter]: DBG-X: Asset description: <?xml version="1.1" encoding="UTF-8"?>
DEBUG [2016-11-29 06:45:01.81]: [Transporter]: DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@162d677b
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X: Deflated 2173 bytes to 807
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: INFO: Asset media analysis has completed
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X: Memory: [JVM] 761M free, 982M total, 982M max [System] (Physical) 11073M free, 16384M total (Swap) 0 free, 0 total
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X: Using operation named: lookupTransportDiagnostic
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.0
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.12.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u dpreleasebot@company.com -p **hidden value** -f /tmp/429775439.itmsp -t DAV -t Signiant -k 100000
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X:   parameter Username = dpreleasebot@company.com
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X:   parameter Version = 1.9.1
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-11-29 06:45:01.97]: [Transporter]: INFO: id = 20161129064501-794
DEBUG [2016-11-29 06:45:04.46]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2016-11-29 06:45:04.46]: [Transporter]: DBG-X:   parameter SigniantLoggingLevel = OFF
DEBUG [2016-11-29 06:45:04.46]: [Transporter]: DBG-X:   parameter AsperaLoggingLevel = OFF
DEBUG [2016-11-29 06:45:04.75]: [Transporter]: DBG-X: WebDAV status: 401
DEBUG [2016-11-29 06:45:04.76]: [Transporter]: DEBUG: Using token file path /Users/hadronci/.itmstransporter/UploadTokens/build-ios.local_HomeBoxOfficeInc_429775439.itmsp.token
DEBUG [2016-11-29 06:45:04.76]: [Transporter]: DEBUG: Attempting exclusive file lock on token file
DEBUG [2016-11-29 06:45:04.76]: [Transporter]: DEBUG: Token exists, examining
DEBUG [2016-11-29 06:45:04.78]: [Transporter]: DEBUG: Token pid: 85498, found process = false; my pid: 91058
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DEBUG: Reusing existing token: 6ec395c0-4c67-4e8c-9a1f-878b86c5a2d9/1480428244992
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DEBUG: Set token: 6ec395c0-4c67-4e8c-9a1f-878b86c5a2d9/1480428244992
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X: Memory: [JVM] 746M free, 982M total, 982M max [System] (Physical) 11071M free, 16384M total (Swap) 0 free, 0 total
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X: Deflated 451 bytes to 392
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X: Using operation named: validateAssets
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.0
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter CPUToken = 6ec395c0-4c67-4e8c-9a1f-878b86c5a2d9/1480428244992
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter Files = [459ccdda2286f3794c61fd6fb59b477e.ipa, metadata.xml]
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter MetadataChecksum = 7ac6da2c5b6e9101eb54bc6dc52f3fa5
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.12.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter PackageName = 429775439.itmsp
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter PackageSize = 64955312
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter Transport = DAV
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u dpreleasebot@company.com -p **hidden value** -f /tmp/429775439.itmsp -t DAV -t Signiant -k 100000
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter Username = dpreleasebot@company.com
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter Version = 1.9.1
DEBUG [2016-11-29 06:45:04.81]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2016-11-29 06:45:04.82]: [Transporter]: INFO: id = 20161129064504-191
DEBUG [2016-11-29 06:45:05.48]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2016-11-29 06:45:05.48]: [Transporter]: DBG-X:   parameter ErrorMessage = ERROR ITMS-90168: "The binary you uploaded was invalid.
DEBUG [2016-11-29 06:45:05.48]: [Transporter]: DBG-X:   parameter CPUToken = 6ec395c0-4c67-4e8c-9a1f-878b86c5a2d9/1480428244992
DEBUG [2016-11-29 06:45:05.48]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{UTI=com.apple.ipa, Role=source, ShouldDescribeAsset=true, Filename=459ccdda2286f3794c61fd6fb59b477e.ipa}]
DEBUG [2016-11-29 06:45:05.48]: [Transporter]: DBG-X:   parameter FileSizes = {459ccdda2286f3794c61fd6fb59b477e.ipa=64954861}
DEBUG [2016-11-29 06:45:05.48]: [Transporter]: DBG-X:   parameter Checksums = {459ccdda2286f3794c61fd6fb59b477e.ipa=d33e35a5eaccf8d5ee0fd9f9c97eded6}
DEBUG [2016-11-29 06:45:05.48]: [Transporter]: DBG-X:   parameter Errors = [ERROR ITMS-90168: "The binary you uploaded was invalid."]
DEBUG [2016-11-29 06:45:05.48]: [Transporter]: DBG-X:   parameter ErrorCode = 1102
DEBUG [2016-11-29 06:45:05.49]: [Transporter]: DBG-X:   parameter Success = false
DEBUG [2016-11-29 06:45:05.49]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, 459ccdda2286f3794c61fd6fb59b477e.ipa]
DEBUG [2016-11-29 06:45:05.49]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
ERROR [2016-11-29 06:45:05.49]: [31m[Transporter Error Output]: ERROR ITMS-90168: "The binary you uploaded was invalid."
[0m
DEBUG [2016-11-29 06:45:05.49]: [Transporter]: DBG-X: The error code is: 1102
DEBUG [2016-11-29 06:45:05.49]: [Transporter]: INFO: Done performing authentication.
ERROR [2016-11-29 06:45:05.64]: [31mTransporter transfer failed.[0m
WARN [2016-11-29 06:45:05.64]: [33m[0m
ERROR [2016-11-29 06:45:05.64]: [31mERROR ITMS-90168: "The binary you uploaded was invalid."
[0m
ERROR [2016-11-29 06:45:05.71]: [31mERROR ITMS-90168: "The binary you uploaded was invalid."
Return status of iTunes Transporter was 1: ERROR ITMS-90168: "The binary you uploaded was invalid."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not upload binary to iTunes Connect. Check out the error above

URL: https://api.github.com/search/issues?q=Could%20not%20upload%20binary%20to%20iTunes%20Connect.%20Check%20out%20the%20error%20above+repo:fastlane/fastlane
➡️  [33mIssues with deliver, can't upload binary / IPA[0m
   https://github.com/fastlane/fastlane/issues/6151 [[31mopen[0m] 35 💬
   56 minutes ago

➡️  [33mBinary upload invalid / [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["ITC.response.error.OPERATION_FAILED"], "info"=>nil}, "statusCode"=>"ERROR"}[0m
   https://github.com/fastlane/fastlane/issues/6419 [[31mopen[0m] 60 💬
   5 days ago

➡️  [33mCould not upload binary to iTunes Connect[0m
   https://github.com/fastlane/fastlane/issues/4339 [[32mclosed[0m] 19 💬
   03 Oct 2016

and 39 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20upload%20binary%20to%20iTunes%20Connect.%20Check%20out%20the%20error%20above&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [31m[!] Could not upload binary to iTunes Connect. Check out the error above[0m (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.16.0/lib/deliver/runner.rb:84:in `upload_binary'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.16.0/lib/deliver/runner.rb:25:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.16.0/lib/deliver/commands_generator.rb:63:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.16.0/lib/deliver/commands_generator.rb:149:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.16.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.16.0/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.1                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.1 (16B2555)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date        |
| spaceship           | 0.38.1  | ✅ Up-To-Date        |
| deliver             | 1.16.0  | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.3.1   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.1        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.57.1       |
| bundler                   | 1.13.6       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
</details>

*generated on:* **2016-11-29**
</details>

**Comment by elliot-nelson** [comment]
I've discovered the source of the issue -- our Jenkins script was setting a magic environment variable `TOOLS_PATH`.  No idea why, but if I eliminate this var, the Loader behaves as expected.  Going to go ahead and close this issue.
