### ISSUE TITLE
Undefined method `fetch` for nil:NilClass (NoMethodError) again?

### ISSUE THREAD

**Issue by javascriptlove** [fastlane/fastlane#7307]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

First of all, now i hate apple even more... but I'm willing to figure out how to fight the beast. The issue here is pretty strange and i'm trying to figure out where could i dig more. I can successfully pass the `cert` step to validate certificates, then i successfully unlock-keychain with mac's `security` thing, then i run sigh, it successfully finds the certs, downloads proper profile, puts it in the file, and i can even process the result `.mobileprovision` file with `security cms -D -i '$path_here'`.

MOREOVER, and this is the most important notice - i run the build in an automated Bamboo environment. And that's where it fails. If i connect to same bamboo agent via SSH and run the exactly same `sigh` command - it runs just fine.

And, even if after the failed run, i go with SSH to that project folder, i can run `sigh` just fine.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

And this is the important piece of error from the actual build:

```
5-Dec-2016 16:34:16	INFO [2016-12-05 16:34:16.67]: Starting login with user 'xxx@xxx'
05-Dec-2016 16:34:18	INFO [2016-12-05 16:34:18.71]: Successfully logged in
05-Dec-2016 16:34:18	INFO [2016-12-05 16:34:18.71]: Fetching profiles...
05-Dec-2016 16:34:21	INFO [2016-12-05 16:34:21.36]: $ security list-keychains -d user
05-Dec-2016 16:34:21	INFO [2016-12-05 16:34:21.38]: ?     "/Library/Keychains/System.keychain"
05-Dec-2016 16:34:21	INFO [2016-12-05 16:34:21.38]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Library/Keychains/System.keychain
05-Dec-2016 16:34:21	INFO [2016-12-05 16:34:21.42]: ? keychain: "/Library/Keychains/System.keychain"
05-Dec-2016 16:34:21	INFO [2016-12-05 16:34:21.42]: ? version: 256
05-Dec-2016 16:34:21	INFO [2016-12-05 16:34:21.42]: ? class: 0x80001000 
05-Dec-2016 16:34:21	INFO [2016-12-05 16:34:21.42]: ? attributes:
05-Dec-2016 16:34:21	INFO [2016-12-05 16:34:21.42]: ?     #### a lot of attributes here 
05-Dec-2016 16:34:22	INFO [2016-12-05 16:34:22.46]: Found 1 matching profile(s)
05-Dec-2016 16:34:22	WARN [2016-12-05 16:34:22.46]: Downloading provisioning profile...
05-Dec-2016 16:34:24	INFO [2016-12-05 16:34:24.84]: Successfully downloaded provisioning profile...
05-Dec-2016 16:34:24	ERROR [2016-12-05 16:34:24.88]: Error parsing provisioning profile at path '/Users/bamboo/bamboo-agent-home/xml-data/build-dir/LIN-EXO29-EIOS/.built_app/ios/project/AppStore_com.linguahouse.expemoapp.mobileprovision'
05-Dec-2016 16:34:24	
05-Dec-2016 16:34:24	Looking for related GitHub issues on fastlane/fastlane...
05-Dec-2016 16:34:24	Search query: undefined method `fetch' for nil
05-Dec-2016 16:34:24	
05-Dec-2016 16:34:24	URL: https://api.github.com/search/issues?q=undefined%20method%20%60fetch'%20for%20nil+repo:fastlane/fastlane
05-Dec-2016 16:34:25	??  undefined method `fetch' for nil:NilClass
05-Dec-2016 16:34:25	   https://github.com/fastlane/fastlane/issues/5677 [closed] 3 ?
05-Dec-2016 16:34:25	   6 weeks ago
05-Dec-2016 16:34:25	
05-Dec-2016 16:34:25	??  undefined method `fetch' for nil:NilClass
05-Dec-2016 16:34:25	   https://github.com/fastlane/fastlane/issues/880 [closed] 6 ?
05-Dec-2016 16:34:25	   6 weeks ago
05-Dec-2016 16:34:25	
05-Dec-2016 16:34:25	??  'itc_service_key': [!] undefined method `[]' for nil:NilClass
05-Dec-2016 16:34:25	   https://github.com/fastlane/fastlane/issues/6167 [closed] 5 ?
05-Dec-2016 16:34:25	   22 Sep 2016
05-Dec-2016 16:34:25	
05-Dec-2016 16:34:25	and 51 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60fetch'%20for%20nil&type=Issues&utf8=?
05-Dec-2016 16:34:25	Error ERROR on sr-bundle
05-Dec-2016 16:34:31	/Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane_core-0.57.2/lib/fastlane_core/provisioning_profile.rb:38:in `uuid': [!] undefined method `fetch' for nil:NilClass (NoMethodError)
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/sigh-1.12.0/lib/sigh/manager.rb:38:in `install_profile'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/sigh-1.12.0/lib/sigh/manager.rb:25:in `start'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/sigh-1.12.0/lib/sigh/commands_generator.rb:56:in `block (2 levels) in run'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane_core-0.57.2/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/sigh-1.12.0/lib/sigh/commands_generator.rb:120:in `run'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/sigh-1.12.0/lib/sigh/commands_generator.rb:11:in `start'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/sigh-1.12.0/bin/sigh:6:in `<top (required)>'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/bin/sigh:22:in `load'
05-Dec-2016 16:34:31	        from /Users/bamboo/.fastlane/bin/bundle/bin/sigh:22:in `<main>'
```

### Environment

I included some log output from the Bamboo agent build run, 

```
build	05-Dec-2016 16:28:06	 --===-- 
build	05-Dec-2016 16:28:06	Using ruby:  ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
build	05-Dec-2016 16:28:06	/Users/bamboo/.rvm/rubies/ruby-2.3.3/bin/ruby
build	05-Dec-2016 16:28:08	Using fastlane:  fastlane 1.111.0
build	05-Dec-2016 16:28:08	/Users/bamboo/.fastlane/bin/fastlane
build	05-Dec-2016 16:28:08	Using xcodebuild:  Xcode 7.3.1 Build version 7D1014
build	05-Dec-2016 16:28:08	/usr/bin/xcodebuild
build	05-Dec-2016 16:28:08	User name:  bamboo
build	05-Dec-2016 16:28:08	 --===-- 
```

This is output from fastlane env. The main difference i see here is that fastlane env for some reason outputted ruby 2.2.4. Could it be the reason?

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12                                       |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1                          |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| deliver             | 1.16.0  | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.57.2  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.2   | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| sigh                | 1.12.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| spaceship           | 0.38.4  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.0        |
| concurrent-ruby           | 1.0.2        |
| credentials_manager       | 0.16.2       |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| fastlane_core             | 0.57.2       |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| krausefx-shenzhen         | 0.14.11      |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| net-sftp                  | 2.1.2        |
| net-ssh                   | 3.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| xcodeproj                 | 1.4.1        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2016-12-05**
</details>
```

**Comment by javascriptlove** [comment]
Additionally, if i put `--skip_install` for `sigh`, it continues, but then the `gym` step will fail with exactly the same error

```
06-Dec-2016 11:19:43	gym --scheme XXX --configuration Debug --use_legacy_build_api --output_directory ../ --output_name debug.ipa
06-Dec-2016 11:19:45	[11:19:45]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816
06-Dec-2016 11:19:45	[11:19:45]: Installing provisioning profile...
06-Dec-2016 11:19:45	[11:19:45]: Error parsing provisioning profile at path '/Users/bamboo/bamboo-agent-home/xml-data/build-dir/LIN-EXO29-EIOS/.built_app/ios/project/xxx.mobileprovision'
...
06-Dec-2016 11:19:47	/Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane_core-0.57.2/lib/fastlane_core/provisioning_profile.rb:38:in `uuid': [!] undefined method `fetch' for nil:NilClass (NoMethodError)
```
