### ISSUE TITLE
Supply gem missing dependencies

### ISSUE THREAD

**Issue by lkraider** [fastlane/fastlane#7344]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Installing only the `supply` gem on a clean install, there are missing dependencies:

```
$ supply --help
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'multi_json' (>= 1.0.0) among 11 total gem(s) (Gem::LoadError)
(...)
```

```
$ gem install multi_json
WARNING:  You don't have ~/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Successfully installed multi_json-1.12.1
1 gem installed
$ supply --help
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- google/apis/androidpublisher_v2 (LoadError)
(...)
```

```
$ gem install google-api-client
WARNING:  You don't have ~/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Successfully installed uber-0.0.15
Successfully installed representable-2.3.0
Successfully installed retriable-2.1.0
Fetching: public_suffix-2.0.4.gem (100%)
Successfully installed public_suffix-2.0.4
Fetching: addressable-2.5.0.gem (100%)
Successfully installed addressable-2.5.0
Successfully installed mime-types-data-3.2016.0521
Successfully installed mime-types-3.1
Successfully installed hurley-0.2
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.10.0.gem (100%)
Successfully installed faraday-0.10.0
Successfully installed little-plugger-1.1.4
Successfully installed logging-2.1.0
Successfully installed jwt-1.5.6
Successfully installed memoist-0.15.0
Successfully installed os-0.9.6
Successfully installed signet-0.7.3
Successfully installed googleauth-0.5.1
Successfully installed httpclient-2.8.2.4
Fetching: google-api-client-0.9.20.gem (100%)
Successfully installed google-api-client-0.9.20
19 gems installed


$ supply --help
  supply

  Command line tool for updating Android apps and their metadata on the Google Play Store
(...)
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                  |
| ------------------- | ------------------------------------------------------ |
| OS                  | 10.11.6                                                |
| Ruby                | 2.3.1                                                  |
| Bundler?            | false                                                  |
| Xcode Path          | ~/Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                                    |
| Git                 | git version 2.10.1                                     |
| Installation Source | /usr/local/bin/fastlane                                |
| Host                | Mac OS X 10.11.6 (15G1108)                             |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib                     |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem | Version | Update-Status |
| --- | ------- | ------------- |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem          | Version |
| ------------ | ------- |
| did_you_mean | 1.0.0   |
| json         | 1.8.3   |
| io-console   | 0.4.5   |
</details>

*generated on:* **2016-12-06**
</details>

**Comment by asfalcone** [comment]
@lkraider Is this still an issue after our upgrade to monogem? Let me know!

**Comment by lkraider** [comment]
Missing fastlane_core now it seems:

```
$ supply --help
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fastlane_core (LoadError)
```

**Comment by mfurtak** [comment]
@lkraider What output do you get from `gem list supply` and `gem which supply`?

**Comment by lkraider** [comment]
@mfurtak I just tested again, seems it's now a problem only with `brew gem` (whereas before was in any env). I tried installing on a clean environment without using brew gem and seems to work:

```
$ gem install supply
WARNING:  You don't have ~/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Successfully installed uber-0.0.15
Successfully installed representable-2.3.0
Successfully installed retriable-2.1.0
Fetching: public_suffix-2.0.5.gem (100%)
Successfully installed public_suffix-2.0.5
Successfully installed addressable-2.5.0
Successfully installed mime-types-data-3.2016.0521
Successfully installed mime-types-3.1
Successfully installed hurley-0.2
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.10.1.gem (100%)
Successfully installed faraday-0.10.1
Successfully installed little-plugger-1.1.4
Successfully installed multi_json-1.12.1
Successfully installed logging-2.1.0
Successfully installed jwt-1.5.6
Successfully installed memoist-0.15.0
Successfully installed os-0.9.6
Successfully installed signet-0.7.3
Successfully installed googleauth-0.5.1
Fetching: httpclient-2.8.3.gem (100%)
Successfully installed httpclient-2.8.3
Successfully installed google-api-client-0.9.20
Successfully installed colored-1.2
Successfully installed slack-notifier-1.5.1
Successfully installed i18n-0.7.0
Successfully installed thread_safe-0.3.5
Successfully installed tzinfo-1.2.2
Fetching: concurrent-ruby-1.0.4.gem (100%)
Successfully installed concurrent-ruby-1.0.4
Successfully installed activesupport-4.2.7.1
Fetching: CFPropertyList-2.3.4.gem (100%)
Successfully installed CFPropertyList-2.3.4
Successfully installed claide-1.0.1
Fetching: nanaimo-0.2.3.gem (100%)
Successfully installed nanaimo-0.2.3
Fetching: xcodeproj-1.4.2.gem (100%)
Successfully installed xcodeproj-1.4.2
Successfully installed rouge-1.11.1
Successfully installed xcpretty-0.2.4
Successfully installed terminal-notifier-1.7.1
Fetching: unicode-display_width-1.1.2.gem (100%)
Successfully installed unicode-display_width-1.1.2
Fetching: terminal-table-1.7.3.gem (100%)
Successfully installed terminal-table-1.7.3
Fetching: plist-3.2.0.gem (100%)
Successfully installed plist-3.2.0
Successfully installed word_wrap-1.0.0
Successfully installed babosa-1.0.2
Successfully installed highline-1.7.8
Fetching: commander-4.4.3.gem (100%)
Successfully installed commander-4.4.3
Successfully installed excon-0.54.0
Building native extensions.  This could take a while...
Successfully installed unf_ext-0.0.7.2
Successfully installed unf-0.1.4
Fetching: domain_name-0.5.20161129.gem (100%)
Successfully installed domain_name-0.5.20161129
Successfully installed http-cookie-1.0.3
Successfully installed faraday-cookie_jar-0.0.6
Fetching: fastimage-2.0.1.gem (100%)
Successfully installed fastimage-2.0.1
Successfully installed gh_inspector-1.0.2
Successfully installed mini_magick-4.5.1
Fetching: multi_xml-0.6.0.gem (100%)
Successfully installed multi_xml-0.6.0
Fetching: rubyzip-1.2.0.gem (100%)
Successfully installed rubyzip-1.2.0
Successfully installed security-0.1.3
Successfully installed xcpretty-travis-formatter-0.0.4
Successfully installed dotenv-2.1.1
Fetching: bundler-1.13.7.gem (100%)
Successfully installed bundler-1.13.7
Fetching: faraday_middleware-0.10.1.gem (100%)
Successfully installed faraday_middleware-0.10.1
Fetching: fastlane-2.7.0.gem (100%)
Successfully installed fastlane-2.7.0
Fetching: supply-1.0.0.gem (100%)
Please use `fastlane supply` instead of `supply` from now on.
Successfully installed supply-1.0.0
59 gems installed
```

```
$ ~/.gem/ruby/2.3.0/bin/supply --help
[WARNING] You are calling supply directly. Usage of the tool name without the `fastlane` prefix is deprecated in fastlane 2.0
Please update your scripts to use `fastlane supply --help` instead.
  supply

  Command line tool for updating Android apps and their metadata on the Google Play Store
(...)
```

```
$ gem list supply

*** LOCAL GEMS ***

supply (1.0.0)
```
```
$ gem which supply
~/.gem/ruby/2.3.0/gems/fastlane-2.7.0/supply/lib/supply.rb
```


Output using `brew gem`:

```
$ brew gem install supply --homebrew-ruby
==> Fetching supply from gem source
Downloaded supply-1.0.0
Warning: Cannot verify integrity of supply-1.0.0.gem
A checksum was not provided for this resource
For your reference the SHA256 is: d6186c987517bed6bdfc39cec63eebec397a695117c6db69e5388aaa2f0d6ab4
==> /usr/local/bin/gem install ~/Library/Caches/Homebrew/supply-1.0.0.gem --no-ri --no-rdoc --no-wrapper --no-
🍺  /usr/local/Cellar/gem-supply/1.0.0: 3,887 files, 62.1M, built in 54 seconds
```

```
$ supply --help
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fastlane_core (LoadError)
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/gem-supply/1.0.0/gems/supply-1.0.0/lib/supply/options.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/gem-supply/1.0.0/gems/supply-1.0.0/lib/supply.rb:3:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/gem-supply/1.0.0/gems/supply-1.0.0/bin/supply:4:in `<top (required)>'
	from /usr/local/bin/supply:5:in `load'
	from /usr/local/bin/supply:5:in `<main>'
```

```
$ ls -1 /usr/local/Cellar/gem-supply/1.0.0/gems/
CFPropertyList-2.3.4
activesupport-4.2.7.1
addressable-2.5.0
babosa-1.0.2
bundler-1.13.7
claide-1.0.1
colored-1.2
commander-4.4.3
domain_name-0.5.20161129
dotenv-2.1.1
excon-0.54.0
faraday-0.10.1
faraday-cookie_jar-0.0.6
faraday_middleware-0.10.1
fastimage-2.0.1
fastlane-2.7.0
gh_inspector-1.0.2
google-api-client-0.9.20
googleauth-0.5.1
highline-1.7.8
http-cookie-1.0.3
httpclient-2.8.3
hurley-0.2
i18n-0.7.0
json-1.8.3
jwt-1.5.6
little-plugger-1.1.4
logging-2.1.0
memoist-0.15.0
mime-types-3.1
mime-types-data-3.2016.0521
mini_magick-4.5.1
minitest-5.10.1
multi_json-1.12.1
multi_xml-0.6.0
multipart-post-2.0.0
nanaimo-0.2.3
os-0.9.6
plist-3.2.0
public_suffix-2.0.5
representable-2.3.0
retriable-2.1.0
rouge-1.11.1
rubyzip-1.2.0
security-0.1.3
signet-0.7.3
slack-notifier-1.5.1
supply-1.0.0
terminal-notifier-1.7.1
terminal-table-1.7.3
thread_safe-0.3.5
tzinfo-1.2.2
uber-0.0.15
unf-0.1.4
unf_ext-0.0.7.2
unicode-display_width-1.1.2
word_wrap-1.0.0
xcodeproj-1.4.2
xcpretty-0.2.4
xcpretty-travis-formatter-0.0.4
```

I consider this issue closed, seeing as it's only an issue with the brew gem env.

**Comment by mfurtak** [comment]
@lkraider OK, gotcha! Thanks. 👍 

As a heads-up, since _fastlane_ 2.0, we've moved to a "monogem" deployment for all _fastlane_ tools. What that means is that _supply_ 1.0.0 is the last release you should expect to see for the _supply_ gem! 🚚 

From now on, all tools are distributed in the _fastlane_ gem, and that should be the only gem you need to have installed to use them. Running `supply` separately should still work, but the preferred way to invoke _supply_ from the command line is now `fastlane supply`.

It's recommended that you remove all of the old independent _fastlane_ tool gems after installing _fastlane_ 2.x.

Hope that helps - please let me know if you have any questions! 🚀
