### ISSUE TITLE
No such file or directory @ dir_initialize - /var/folders/ww/mm2w8mjx35g0v6zn7ncm5pjc0000gn/T/d20161208-17114-wq2xwm/profiles/development (Errno::ENOENT)

### ISSUE THREAD

**Issue by jacinzhang** [fastlane/fastlane#7377]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```shell
[23:56:41]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/runner.rb:114:in `open': [!] No such file or directory @ dir_initialize - /var/folders/ww/mm2w8mjx35g0v6zn7ncm5pjc0000gn/T/d20161208-17114-wq2xwm/profiles/development (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/runner.rb:114:in `entries'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/runner.rb:114:in `fetch_provisioning_profile'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/runner.rb:36:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/runner.rb:35:in `loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/runner.rb:35:in `block in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/runner.rb:34:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/runner.rb:34:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/commands_generator.rb:53:in `block (3 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.58.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/commands_generator.rb:119:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/lib/match/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.11.1/bin/match:6:in `<top (required)>'
	from /usr/local/bin/match:22:in `load'
	from /usr/local/bin/match:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```shell
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.58.0  | 🚫 Update availaible |
| spaceship           | 0.38.5  | ✅ Up-To-Date        |
| deliver             | 1.16.1  | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.1   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| produce             | 1.3.2   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| sigh                | 1.12.1  | ✅ Up-To-Date        |
| match               | 0.11.1  | ✅ Up-To-Date        |
| fastlane            | 1.111.0 | ✅ Up-To-Date        |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.0   |
| highline                  | 1.7.8   |
| terminal-table            | 1.4.5   |
| json                      | 1.8.3   |
| dotenv                    | 2.1.1   |
| net-ssh                   | 3.2.0   |
| net-sftp                  | 2.1.2   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.11 |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| multi_json                | 1.12.1  |
| colored                   | 1.2     |
| excon                     | 0.54.0  |
| gh_inspector              | 1.0.2   |
| credentials_manager       | 0.16.2  |
| fastlane_core             | 0.58.0  |
| bundler                   | 1.13.6  |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| babosa                    | 1.0.2   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| activesupport             | 4.2.7.1 |
| commander                 | 4.4.1   |
| io-console                | 0.4.5   |
| plist                     | 3.2.0   |
| claide                    | 1.0.1   |
| xcode-install             | 2.0.9   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.1   |
</details>


*generated on:* **2016-12-08**
</details>
```

**Comment by bernikowich-cedoni** [comment]
Have you tried `--readonly false`? I have same issue when there was no AppStore profile and readonly was set to `true`.

**Comment by jacinzhang** [comment]
thanks, I resolved it.

**Comment by KrauseFx** [comment]
@jacinzhang How did you resolve it?

**Comment by jacinzhang** [comment]
I have tried many times, and this error seems random.

**Comment by jzemljic** [comment]
I encountered the same error running match with `--readonly true`, certificate was already installed, but the adhoc provisioning profile was missing. `--readonly false` resolved the issue.

**Comment by lkraider** [comment]
Same error here:
```
fastlane match development --readonly

[13:52:27]: No such file or directory @ dir_initialize - /var/folders/_w/8tt1pmpn57396yh6x0lmykzh0000gn/T/d20170428-64943-fh5eig/profiles/development

.gem/ruby/2.4.0/gems/fastlane-2.28.5/match/lib/match/runner.rb:122:in `open': No such file or directory @ dir_initialize - /var/folders/_w/8tt1pmpn57396yh6x0lmykzh0000gn/T/d20170428-64943-fh5eig/profiles/development (Errno::ENOENT)
```

The actual issue is that there was no development provisioning profile in the Member Center. Running without `readonly` created the profile and fixed the issue.
