### ISSUE TITLE
changing .plist PRODUCT_NAME causes version not updated and "Redundant Binary Upload" error

### ISSUE THREAD

**Issue by ravelab** [fastlane/fastlane#7429]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I want to change the app name by changing .plist PRODUCT_NAME, but afterward, event though the build number is incremented to '46', the pilot uploaded version is still '44' and gives me "Redundant Binary Upload" error 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[17:23:40]: $ cd /Users/alan/workspace/AudioCards/ios && agvtool next-version -all && cd -
[17:23:41]: ▸ Setting version of project AudioCards to:
[17:23:41]: ▸ 46.
[17:23:41]: ▸ Also setting CFBundleVersion key (assuming it exists)
[17:23:41]: ▸ Updating CFBundleVersion in Info.plist(s)...
[17:23:41]: ▸ Updated CFBundleVersion in "AudioCards.xcodeproj/../AudioCards/Info.plist" to 46
[17:23:41]: ▸ Updated CFBundleVersion in "AudioCards.xcodeproj/../AudioCardsUITests/Info.plist" to 46
[17:23:41]: ▸ /Users/alan/workspace/AudioCards

......

[17:28:33]: Successfully exported and compressed dSYM file
[17:28:33]: Successfully exported and signed the ipa file:
[17:28:33]: /Users/alan/workspace/AudioCards/Ian Flashcards.ipa
[17:28:34]: -------------------
[17:28:34]: --- Step: pilot ---
[17:28:34]: -------------------
[17:28:34]: Login to iTunes Connect (alanpc@gmail.com)
[17:28:37]: Login successful
[17:28:38]: Ready to upload new build to TestFlight (App: 1171647738)...
[17:28:38]: Going to upload updated app to iTunes Connect
[17:28:38]: This might take a few minutes. Please don't interrupt the script.
[17:29:09]: [Transporter Error Output]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '44' for version '1.2'"
[17:29:09]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '44' for version '1.2'"
[17:29:09]: You have to change the build number of your app to upload your ipa file
[17:29:09]: [Transporter Error Output]: ERROR ITMS-90186: "Invalid Pre-Release Train. The train version '1.2' is closed for new build submissions"
[17:29:09]: [Transporter Error Output]: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.2] in the Info.plist file must contain a higher version than that of the previously approved version [1.2]."
[17:29:09]: Transporter transfer failed.
[17:29:09]: 
[17:29:09]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '44' for version '1.2'"
ERROR ITMS-90186: "Invalid Pre-Release Train. The train version '1.2' is closed for new build submissions"
ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.2] in the Info.plist file must contain a higher version than that of the previously approved version [1.2]."
[17:29:09]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '44' for version '1.2'"
ERROR ITMS-90186: "Invalid Pre-Release Train. The train version '1.2' is closed for new build submissions"
ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.2] in the Info.plist file must contain a higher version than that of the previously approved version [1.2]."
Return status of iTunes Transporter was 1: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload\nERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.2] in the Info.plist file must contain a higher version than that of the previously approved version [1.2]."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[17:29:09]: Variable Dump:
[17:29:09]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :SIGH_PROFILE_TYPE=>"app-store", :BUILD_NUMBER=>"46", :IPA_OUTPUT_PATH=>"/Users/alan/workspace/AudioCards/Ian Flashcards.ipa", :DSYM_OUTPUT_PATH=>"/Users/alan/workspace/AudioCards/Ian Flashcards.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/alan/Library/Developer/Xcode/Archives/2016-12-11/Ian Flashcards 2016-12-11 17.23.48.xcarchive"}
[17:29:09]: Error uploading ipa file, for more information see above

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

imac:AudioCards alan$ fastlane env
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2274:in `check_version_conflict': can't activate json-2.0.2, already activated json-1.8.3 (Gem::LoadError)
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1403:in `activate'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.59.0/lib/fastlane_core.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by ravelab** [comment]
after deleting old binary and rebuild again, the new name works.
