### ISSUE TITLE
undefined `build' for Pilot::BuildManager

### ISSUE THREAD

**Issue by connected-rkam** [fastlane/fastlane#7439]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When using the testflight action with:
    skip_submission: false,
    distribute_external: false,
    skip_waiting_for_build_processing: false,
    update_build_info_on_upload: true

It gives an error "undefined `build' for Pilot::BuildManager".

Looking at the stack trace, in pilot/lib/pilot/build_manager.rb when it runs wait_for_processing_build and should_update_build_information(options) returns true, there is an error trying to call build.update_build_information because there is no variable called build in the scope. I'm guessing this build refers to latest_build? When we renamed build to latest_build, it seemed to have fixed the issue.

##### Complete output when running fastlane, including the stack trace and command used

ERROR [2016-12-09 15:37:35.33]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined `build' for Pilot::BuildManager
Did you mean?  builds
```
URL: https://api.github.com/search/issues?q=undefined%20%60build'%20for%20Pilot::BuildManager%0ADid%20you%20mean?%20%20builds+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pilot-1.12.1/lib/pilot/build_manager.rb:140:in `block in wait_for_processing_build': [!] undefined local variable or method `build' for #<Pilot::BuildManager:0x007fe864c1aa08> (NameError)
Did you mean?  builds
Did you mean?  builds
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pilot-1.12.1/lib/pilot/build_manager.rb:122:in `loop'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pilot-1.12.1/lib/pilot/build_manager.rb:122:in `wait_for_processing_build'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pilot-1.12.1/lib/pilot/build_manager.rb:34:in `upload'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/actions/testflight.rb:5:in `run'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:186:in `chdir'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:111:in `block (2 levels) in parsing_binding'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:165:in `try_switch_to_lane'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:120:in `trigger_action_by_name'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:92:in `block (2 levels) in parsing_binding'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/commands_generator.rb:95:in `block (2 levels) in run'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/commands_generator.rb:292:in `run'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/commands_generator.rb:36:in `start'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/bin/fastlane:5:in `<top (required)>'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/bin/fastlane:22:in `load'
	from /Users/cl-dev5/.rbenv/versions/2.3.3/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  def change_log_since_last_tag
    # http://git-scm.com/docs/pretty-formats
    # <short hash> <commit title>
    return changelog_from_git_commits(pretty: '%h %s')
  end

  def tag_string(version_number, build_number)
    "v#{version_number}_build_#{build_number}"
  end

  lane :cl_build_debug do
    gym(
      use_legacy_build_api: true,
      configuration: "Debug",
      include_symbols: true,
      include_bitcode: true
    )
  end

  lane :cl_build_release do
    gym(
      use_legacy_build_api: true,
      include_bitcode: true
    )
  end
  
  lane :cl_match_distribution do
    match(
      type: "appstore",
      verbose: true,
    )
  end

  desc "Build and submit the app on TestFlight."
  desc "Usage: fastlane cl_testflight [version_number:x.y.z] | [bump_type:(major|minor|patch)]"
  lane :cl_testflight do |options|
    # verify parameters
    version_number = options[:version_number]
    bump_type = options[:bump_type] #TODO check bump_type values (major, minor, patch)
    if (version_number != nil && bump_type != nil)
      raise "Cannot specify both version_number and bump_type"
    end

    ensure_git_branch
    ensure_git_status_clean

    # run match
    cl_match_distribution

    # version and build number incrementing/setting
    build_number = "0"
    if version_number != nil || bump_type != nil
      # version_number or bump_type is specified, reset build number
      version_number = increment_version_number(version_number: version_number, bump_type: bump_type)
      build_number = increment_build_number(build_number: 0)
    else
      # no version number change, just increment build number
      version_number = get_version_number
      build_number = increment_build_number
    end

    # build 
    cl_build_release

    # testflight
    verify_build
    change_log = change_log_since_last_tag
    puts "CL LOG: CHANGE LOG: #{change_log}"

    # commit version and add git tags
    complete_version_number = tag_string(version_number, build_number)
    commit_version_bump(
        message: "Version bump to #{complete_version_number}",
        xcodeproj: "App.xcodeproj"
      )
    add_git_tag tag:complete_version_number
    push_to_git_remote
    cl_testflight_internal_upload(changelog: change_log)
    slack(message: "Build #{complete_version_number} uploaded to TestFlight")
  end
  
  lane :cl_verify_xcode do
    verify_xcode
  end

  lane :cl_testflight_internal_upload do |options|
    change_log = options[:changelog]
    testflight(
      changelog: change_log,
      skip_submission: false,
      distribute_external: false,
      skip_waiting_for_build_processing: false,
      update_build_info_on_upload: true,
      beta_app_description: "Description",
      beta_app_feedback_email: ""
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
     slack(
       message: exception.message,
       success: false
     )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "** hidden **" # The bundle identifier of your app
apple_id "** hidden **" # Your Apple email address

team_id "** hidden **"  # Developer Portal Team ID
itc_team_name "** hidden **"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| did_you_mean        | 1.0.0   |
| json                | 1.8.3   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.1   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.2.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.59.0  |
| io-console          | 0.4.5   |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.8.5   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.4   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.3   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-12-12**
</details>

**Comment by KrauseFx** [comment]
Can you update to the latest fastlane/pilot release?

**Comment by connected-rkam** [comment]
@KrauseFx I have updated fastlane, spaceship, and pilot to the latest release and am still getting the error. On the latest version I can still see the line of code that is causing the error. In Pilot's [build_manager.rb, line 153](https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L153) it is using running `build.update_build_information`. Perhaps it should be `latest_build.update_build_information` since there is no 'build' variable in that scope?

**Comment by estellemasso** [comment]
Getting the same error as well. Any timeline when this can be fixed please?

**Comment by KrauseFx** [comment]
Nice catch, looking into this now, thanks 👍
