### ISSUE TITLE
increment_build_number fails with absolute path to xcodeproj

### ISSUE THREAD

**Issue by kaoskorobase** [fastlane/fastlane#747]
Passing an absolute path to the `xcodeproj` parameter of `increment_build_number` fails because of the way the folder is assembled:

~~~~
sh: line 0: cd: /Users/sk/projects/locosonic/locosonic-player/Users/sk/projects/locosonic/locosonic-player/ios: No such file or directory
~~~~

Backtrace:

~~~~
sh: line 0: cd: /Users/sk/projects/locosonic/locosonic-player/Users/sk/projects/locosonic/locosonic-player/ios: No such file or directory
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/helper/sh_helper.rb:8:in `sh'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/actions/increment_build_number.rb:36:in `run'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:137:in `block (2 levels) in parsing_binding'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/bin/fastlane:152:in `run'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/bin/fastlane:158:in `<top (required)>'
	from /Users/sk/.rvm/gems/ruby-2.1.1/bin/fastlane:23:in `load'
	from /Users/sk/.rvm/gems/ruby-2.1.1/bin/fastlane:23:in `<main>'
	from /Users/sk/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sk/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
~~~~

Fastlane 1.34.0 on OSX.

**Comment by xfreebird** [comment]
Thanks @kaoskorobase, indeed that is a bug:

```ruby
        folder = params[:xcodeproj] ? File.join('.', params[:xcodeproj], '..') : '.'
        File.expand_path(folder).shellescape
```

**Comment by kaoskorobase** [comment]
For the record, the same probably applies to [increment_version_number](https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/increment_version_number.rb).

**Comment by KrauseFx** [comment]
Thanks you two, closed with https://github.com/fastlane/fastlane/pull/748
