### ISSUE TITLE
gradle action fails if gradlew is in subdirectory

### ISSUE THREAD

**Issue by kaoskorobase** [fastlane/fastlane#749]
In this project, `gradlew` is in `$SOURCE_DIR/android/gradlew` and the fastlane configuration files in `$SOURCE_DIR/fastlane`. The `gradle` action is called like this:

~~~~
gradle(
        gradle_path: "android/gradlew",
        task: "lint#{app_variant}Release",
        flags: "--info"
      )
~~~~

Expected: `gradlew` should be called with `android` as its working directory.

~~~~
/Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/helper/sh_helper.rb:36:in `sh_no_action': Exit status of command 'android/gradlew lintLocosonicPlayerRelease --info' was 1 instead of 0.  (RuntimeError)
Starting Build
Settings evaluated using empty settings script.
Projects loaded. Root project using empty build file.
Included projects: [root project 'locosonic-player']
Evaluating root project 'locosonic-player' using empty build file.
All projects evaluated.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'lintLocosonicPlayerRelease' not found in root project 'locosonic-player'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 1.159 secs
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/helper/sh_helper.rb:8:in `sh'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/action.rb:67:in `sh'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/helper/gradle_helper.rb:30:in `trigger'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/actions/gradle.rb:14:in `run'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:249:in `block (3 levels) in parsing_binding'
	from Fastfile:58:in `call'
	from Fastfile:58:in `mk_production_lane'
	from Fastfile:248:in `block (2 levels) in parsing_binding'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/bin/fastlane:152:in `run'
	from /Users/sk/.rvm/gems/ruby-2.1.1/gems/fastlane-1.34.0/bin/fastlane:158:in `<top (required)>'
	from /Users/sk/.rvm/gems/ruby-2.1.1/bin/fastlane:23:in `load'
	from /Users/sk/.rvm/gems/ruby-2.1.1/bin/fastlane:23:in `<main>'
	from /Users/sk/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sk/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
~~~~

**Comment by asfalcone** [comment]
@kaoskorobase this is fixed and will be available in the next release of fastlane! 🚀

**Comment by kaoskorobase** [comment]
Cool, thanks!

**Comment by lennyk** [comment]
for posterity:

it seems the way to do this is by using `project_dir`, not `gradle_path`. Updating @kaoskorobase's example:

```
gradle(
        project_dir: "./android",
        task: "lint#{app_variant}Release",
        flags: "--info"
      )
```

**Comment by TKBurner** [comment]
@lennyk Thanks for your tip!
