### ISSUE TITLE
gem install fastlane started to fail

### ISSUE THREAD

**Issue by viktorbenei** [fastlane/fastlane#7508]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane install/update (`gem install fastlane --no-document`) started to fail on bitrise.io:

```
gem install fastlane --no-document
/usr/local/lib/ruby/gems/2.2.0/gems/xcode-install-2.0.9/bin/🎉 maybe `gem pristine xcode-install` will fix it?
ERROR:  While executing gem ... (Gem::Package::PathError)
    installing into parent path /usr/local/lib/ruby/gems/2.2.0/gems/lib/core_ext/class.rb of /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.0.0 is not allowed
Successfully installed xcpretty-0.2.4
Successfully installed gh_inspector-1.0.2
Successfully installed word_wrap-1.0.0
Successfully installed xcode-install-2.0.9
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

There's a preinstalled version, running `fastlane env` with it:

```
fastlane env
[11:24:38]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |
| Git                 | git version 2.10.2                          |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.36.2  | 🚫 Update availaible |
| fastlane_core       | 0.53.0  | 🚫 Update availaible |
| deliver             | 1.14.5  | 🚫 Update availaible |
| snapshot            | 1.16.3  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.3.2   | 🚫 Update availaible |
| cert                | 1.4.3   | 🚫 Update availaible |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.2.1   | 🚫 Update availaible |
| gym                 | 1.11.3  | 🚫 Update availaible |
| pilot               | 1.11.1  | 🚫 Update availaible |
| scan                | 0.13.1  | 🚫 Update availaible |
| supply              | 0.7.1   | 🚫 Update availaible |
| match               | 0.10.0  | 🚫 Update availaible |
| screengrab          | 0.5.5   | 🚫 Update availaible |
| fastlane            | 1.106.2 | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded***


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.1.2        |
| xcodeproj                 | 1.4.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types                | 1.25.1       |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2016-12-15**
</details>
[11:24:48]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub?

Looking for related GitHub issues on fastlane/fastlane...

➡️  Running fastlane on Bitrise - non-interactive mode
   https://github.com/fastlane/fastlane/issues/5867 [closed] 5 💬
   a week ago

➡️  Fastlane android deploy issue
   https://github.com/fastlane/fastlane/issues/5800 [closed] 2 💬
   a week ago

➡️  Deliver - Non-Interactive Mode not working for initial setup
   https://github.com/fastlane/fastlane/issues/4820 [closed] 1 💬
   3 weeks ago

and 8 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

#######################################################################
# fastlane 2.0.0 is available. You are on 1.106.2.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################

2.0.0 fastlane 2.0
From now on, all of _fastlane_ is inside the _fastlane_ gem :tada: This will enable us to be a lot faster and more efficient in the future :rocket:

#### What changes for you?** :warning:

- If you run some tools directly without _fastlane_, please run `fastlane [tool]` instead of `[tool]` (e.g. `fastlane gym ...`). If you don't prefix your commands, the old version of the tool will be used. Using the tool's name directly is now deprecated.
- If you have a `Gemfile`, update it to just include `gem "fastlane"`, and not any of the other tools any more
- As a plugin maintainer, make sure to remove dependencies to _spaceship_ and _fastlane_core_ (I submitted PRs to all public plugins for that this was the case)

#### Why did we change this? :white_check_mark:

- Make releases much simpler, just one gem to ship
- No more internal dependency updates
- No more version conflicts if we add some methods to some sub-gems
- 1 PR could modify multiple tools and tests are still passing (does not mean we have to, but we can for example to update _spaceship_ and _deliver_ at the same time if necessary)

1.111.0 Improvements
* Update internal dependencies (#7208)
* Update message when `sonar-runner` isn't installed (#7214)
* Fix call `set_info_plist_value` resulting in binary plist file (#7188)
* Refactor `ensure_xcode_version` to do more work in Ruby (#7205)
* Improve unexpected output in `ensure_xcode_version` action (#7171)
* Use HTTPS for root certificate in `update_project_provisioning` action (#6970)
* Add `reporter` option to `swiftlint` action (#7126)
* Fix `unlock_keychain` action on macOS Sierra (#7077)
* Add `verbose` option to `pod_push` action (#7078)
* Ensure `live` option of `latest_testflight_build_number` is a boolean (#7082)
* Anonymize paths in `fastlane env` output (#7037)

1.110.0 Improvements
* Deprecate SIGH_UDID in favor of corrected SIGH_UUID
* Remove .positive? to support ruby < 2.3
* Clarify version number error messaging when Xcode project is not set up correctly
* Ignore CocoaPods paths
* Update `fastlane_version` action to show new update message
* Set fail_build to expect a string
* Add bitrise.io git_branch ENV variable check
* Add option to provide -framework option for archive Carthage command
* Update dependency to latest `fastlane_core` to fix app-specific password prompting
* Unit tests run on Sierra

To see all new releases, open https://github.com/fastlane/fastlane/releases

Update using 'sudo gem update fastlane'
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/implementations/shell.rb:119:in `verify_interactive!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/implementations/shell.rb:97:in `confirm'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:237:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:246:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:23:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Thanks for the report, we got it via https://github.com/fastlane/fastlane/issues/7501#issuecomment-267417276 and yanked the gem for now 👍 
Please try again using the old release. We're working on a fix

**Comment by hernangonzalez** [comment]
+1 just tried to update

**Comment by KrauseFx** [comment]
We have a fix, we have an update ready in a minute 👍

**Comment by viktorbenei** [comment]
Awesome, thanks @KrauseFx  ;)

**Comment by KrauseFx** [comment]
Alright, we just pushed fastlane 2.0.1, it's the exact same code, however there was an invalid symlink from an outdated RubyGems version bundled, causing this issue. Please let us know if that fixes the issue for you 👍

**Comment by milch** [comment]
See also our discussion in #7501

**Comment by viktorbenei** [comment]
Seems to be fixed, thank you! ;)

**Comment by milch** [comment]
@viktorbenei Great, thanks for letting us know!
