### ISSUE TITLE
SCP action fails when using it to download files

### ISSUE THREAD

**Issue by ffittschen** [fastlane/fastlane#7568]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The `scp` action fails, when it is being used to download files via scp, because of a typo ([scp.rb:19](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/scp.rb#L19)).

##### Complete output when running fastlane, including the stack trace and command used
```
$ fastlane scp_test
[22:35:14]: Driving the lane 'scp_test' 🚀
[22:35:14]: -----------------
[22:35:14]: --- Step: scp ---
[22:35:14]: -----------------
+---------------+----------+
|       Lane Context       |
+---------------+----------+
| PLATFORM_NAME |          |
| LANE_NAME     | scp_test |
+---------------+----------+
[22:35:31]: undefined method `[]' for nil:NilClass

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 💥   | scp    | 17          |
+------+--------+-------------+

[22:35:31]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Undefined method `fetch` for nil:NilClass (NoMethodError) again?
   https://github.com/fastlane/fastlane/issues/7307 [open] 2 💬
   2 weeks ago

➡️  deliver fails with: [!] undefined method `description' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/7356 [closed] 5 💬
   a week ago

➡️  `supported_platforms': [!] undefined method `split' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/7141 [closed] 43 💬
   a week ago

and 196 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]'%20for%20nil&type=Issues&utf8=✓
/Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/actions/scp.rb:19:in `block in run': [!] undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-scp-1.2.1/lib/net/scp.rb:207:in `start'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/actions/scp.rb:11:in `run'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/runner.rb:227:in `block (2 levels) in execute_action'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/runner.rb:212:in `block in execute_action'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/runner.rb:211:in `chdir'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/runner.rb:211:in `execute_action'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/runner.rb:133:in `trigger_action_by_name'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
    from Fastfile:3:in `block in parsing_binding'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/lane.rb:33:in `call'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/runner.rb:45:in `chdir'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/runner.rb:45:in `execute'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/cli_tools_distributor.rb:60:in `take_off'
    from /Users/<username>/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5/bin/fastlane:5:in `<top (required)>'
    from /Users/<username>/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
    from /Users/<username>/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Hey, thanks for reporting this. Do you want to submit a pull request to fix this? 👍

**Comment by ffittschen** [comment]
Already created one #7569 😉. This issue is for Google and Danger 😄

**Comment by KrauseFx** [comment]
Awesome, thank you :rocket;
