### ISSUE TITLE
Bundler cyclic dependency error on installation

### ISSUE THREAD

**Issue by milch** [fastlane/fastlane#7573]
Currently there is an issue with a cyclic dependency error going around that happens when installing using bundler. 

The cause of that is that both `fastlane` and `xcode-install` depend on each other. This will be fixed once the following PRs are merged and a new version of fastlane is released:

- ~~#7571~~ #7554 
- https://github.com/KrauseFx/xcode-install/pull/191
- (Version Bump #7572)

If you encounter this issue with bundler, please consider using an alternative installation method in the meantime (e.g. `brew cask install fastlane`)

**Comment by humblehacker** [comment]
Tried to install fastlane from homebrew as recommended, but that fails with:

```
Fastlane update available
Please run `brew cask reinstall fastlane`
/Users/david/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- aws-sdk (LoadError)
	from /Users/david/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/david/src/easyshiftios2/.fastlane/helper/quri_s3_helper.rb:1:in `<top (required)>'
	from /Users/david/src/easyshiftios2/fastlane/actions/quri_store_artifacts.rb:1:in `require_relative'
	from /Users/david/src/easyshiftios2/fastlane/actions/quri_store_artifacts.rb:1:in `<top (required)>'
	from /Users/david/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/david/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/david/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.0/fastlane/lib/fastlane/actions/actions_helper.rb:109:in `block in load_external_actions'
	from /Users/david/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.0/fastlane/lib/fastlane/actions/actions_helper.rb:108:in `each'
	from /Users/david/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.0/fastlane/lib/fastlane/actions/actions_helper.rb:108:in `load_external_actions'
	from /Users/david/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.0/fastlane/lib/fastlane.rb:37:in `load_actions'
	from /Users/david/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.0/fastlane/lib/fastlane/commands_generator.rb:29:in `start'
	from /Users/david/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/david/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.1.0/bin/fastlane:5:in `<top (required)>'
	from /Users/david/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/david/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'```
