### ISSUE TITLE
 Could not find app with app identifier

### ISSUE THREAD

**Issue by klausbreyer** [fastlane/fastlane#761]
heyhey, 

I am using fastlane.tools for the first time. Also it is the first time I want to deliver an iOS App. 

So I did as instructed fastlane init, but it does not like my app identifier. 

```
kb1$ fastlane init
[18:03:35]: This setup will help you get up and running in no time.
[18:03:35]: First, it will move the config files from `deliver` and `snapshot`
[18:03:35]: into the subfolder `fastlane`.

[18:03:35]: fastlane will check what tools you're already using and set up
[18:03:35]: the tool automatically for you. Have fun!
Do you want to get started? This will move your Deliverfile and Snapfile (if they exist) (y/n)
/Library/Ruby/Gems/2.0.0/gems/highline-1.7.8/lib/highline/system_extensions.rb:212: warning: Insecure world writable dir /usr/local/lib/node_modules/ in PATH, mode 040777
y
Do you have everything commited in version control? If not please do so! (y/n)
y
[18:03:38]: Created new folder './fastlane'.
[18:03:38]: ------------------------------
[18:03:38]: To not re-enter your username and app identifier every time you run one of the fastlane tools or fastlane, these will be stored from now on.
App Identifier (com.krausefx.app): farm.owl.moveengine
Your Apple ID (fastlane@krausefx.com): kb@klaus-breyer.de
[18:03:49]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
Do you want to setup 'deliver', which is used to upload app screenshots, app metadata and app updates to the App Store? (y/n)
y
[18:03:51]: Loading up 'deliver', this might take a few seconds
[18:03:52]: Login to iTunes Connect (kb@klaus-breyer.de)
[18:03:53]: Login successful
[18:03:53]: Error occurred with the setup program! Reverting changes now!
[18:03:53]: Deleting the 'fastlane' folder
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`
👍  This makes resolving issues much easier and helps improving fastlane
🔒  The reports might contain personal data, but will be stored securely on getsentry.com
✨  Once crash reporting is enabled, you have much cleaner output when something goes wrong
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------

#######################################################################
# fastlane 1.36.0 is available. You are on 1.33.6.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
# To see what's new, open https://github.com/KrauseFx/fastlane/releases.
#######################################################################
/Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/detect_values.rb:28:in `find_app': Could not find app with app identifier 'farm.owl.moveengine' in your account (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/detect_values.rb:5:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/runner.rb:8:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.6/lib/fastlane/setup.rb:109:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.6/lib/fastlane/setup.rb:109:in `ask_to_enable_other_tools'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.6/lib/fastlane/setup.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.6/bin/fastlane:48:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.6/bin/fastlane:152:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.6/bin/fastlane:158:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

I have set it in the developer zone and in my xcode project as well. Did I miss something? 

![screen shot 2015-10-28 at 18 04 42](https://cloud.githubusercontent.com/assets/32771/10796495/ad00d3ee-7d9e-11e5-836a-ab1a55169d59.png)
![screen shot 2015-10-28 at 18 04 29](https://cloud.githubusercontent.com/assets/32771/10796497/ad064b8a-7d9e-11e5-9fa3-130216db0745.png)

**Comment by KrauseFx** [comment]
@klausbreyer I assume the app is not available on iTunes Connect? Since you want to use `deliver`, it verifies the app is available there. Also, please update `deliver` :+1:

**Comment by klausbreyer** [comment]
Thanks you Felix.I had to create the app in itunes connect manually. Also I updated fastlane!
I thought I just have to install fastlane tools, and everything is taken care of. :) 

But this whole thing with the appstore, itunes connect and provisioning profiles confuses me, like a lot. 
Is there somewhere a real beginner guide for a first time app deployment at the appstore with fastlane tools?

**Comment by klausbreyer** [comment]
I managed to get through. 

What I have has had needed (?) was something like: 

run one time manually fastlane, cert, sigh, gym, pilot upload and fix bugs and missing stuff on the way. 

maybe I have just overlooked it. But keep on the good work - I can imagine now what pain and obstacles you removed with this set of tools from the previous deployment process.
