### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by jpgarcia** [fastlane/fastlane#7639]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm getting a `Permission denied - /Users/jpg/Projects/sample/mobile/android`

This is my Fastfile
```ruby
gradle_path = './android'

platform :android do

  desc 'Build and publish to the play store in BETA mode the Staging environmet'
  lane :staging_beta do    
    gradle(
      gradle_path: gradle_path
      task: 'assemble',
      flavor: 'staging',
      build_type: 'Release',
    )

    supply(track: 'beta')
  end  
end
```

The error:
```bash
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `popen': [!] Permission denied - /Users/jpg/Projects/sample/mobile/android (Errno::EACCES)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `sh_control_output'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/action.rb:98:in `sh'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/actions/gradle.rb:49:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/runner.rb:227:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/runner.rb:212:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/runner.rb:211:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/runner.rb:211:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/runner.rb:133:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:9:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by joshdholtz** [comment]
@jpgarcia Your `gradle_path` needs to be the path the `gradlew` executable. I don't know your complete setup but if your `./android` directory has a `gradlew` executable in it, the following example _should hopefully_ work for you 😇 

```rb
gradle_path = './android/gradlew'

platform :android do

  desc 'Build and publish to the play store in BETA mode the Staging environmet'
  lane :staging_beta do    
    gradle(
      gradle_path: gradle_path
      task: 'assemble',
      flavor: 'staging',
      build_type: 'Release',
    )

    supply(track: 'beta')
  end  
end
```

**Comment by jpgarcia** [comment]
Hey @joeydong thanks for your advice! I just needed to add the `project_dir: './android'` to the gradle task and just worked!

Closing the issue!

**Comment by joshdholtz** [comment]
@jpgarcia Glad everything is solved! Happy developing 🎊  🎉
