### ISSUE TITLE
uninitialized constant CredentialsManager::PasswordManager

### ISSUE THREAD

**Issue by hojberg** [fastlane/fastlane#7653]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Trying to upload with pilot I get the error below.
I've set my `apple_id`, i'm not sure what this even means?

```
$ bundle exec fastlane pilot upload                                                                                                  
[21:51:43]: uninitialized constant CredentialsManager::PasswordManager

[!] Invalid default value for username, doesn't match verify_block
```

### Environment
```
$ bundle exec fastlane env                                                                                                          
[21:55:49]: Generating fastlane environment output, this might take a few seconds...

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/simonhojberg/.rbenv/versions/2.1.3/bin/fastlane)
NoMethodError: [!] undefined method `sensitive_strings' for FastlaneCore::Configuration:Class
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/environment_printer.rb:7:in `output'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/commands_generator.rb:223:in `block (2 levels) in run'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.2/lib/commander/command.rb:153:in `run'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.2/lib/commander/runner.rb:446:in `run_active_command'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane_core-1.0.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/commander-4.4.2/lib/commander/delegates.rb:15:in `run!'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
  /Users/hojberg/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-2.2.0/bin/fastlane:5:in `<top (required)>'
  /Users/hojberg/.rbenv/versions/2.1.3/bin/fastlane:23:in `load'
  /Users/hojberg/.rbenv/versions/2.1.3/bin/fastlane:23:in `<top (required)>'
```

**Comment by hojberg** [comment]
To be clear the above does include output from `fastlane env`

**Comment by joshdholtz** [comment]
@hojberg What version of `fastlane` are you running? Can you make sure you are running the latest (`2.2.0`)?

**Comment by joshdholtz** [comment]
Nevermind, I don't know why I didn't look in the output 😬

**Comment by hojberg** [comment]
@joshdholtz I am:

```
$ bundle exec fastlane --version
fastlane 2.2.0
```

You can even see that in the stack trace above.

**Comment by milch** [comment]
@hojberg Sorry about that, your issues seem very unusual. I've never seen an error like that before and it certainly shouldn't happen. Can you try reinstalling fastlane via homebrew? (i.e. run `brew cask install fastlane` in your terminal)

**Comment by hojberg** [comment]
I was previously using a different fastlane version (I believe 2.1.x), was there a change in format in the FastFile, AppFile, DeliverFile?

**Comment by milch** [comment]
@hojberg No, there weren't any changes that could produce an output like you posted.

**Comment by hojberg** [comment]
Getting issues with homebrew too:

```
$ brew install Caskroom/cask/fastlane                                                                                                
==> brew cask install Caskroom/cask/fastlane
Error: No available formula with the name "brew-cask"
Error: Cask 'fastlane' definition is invalid: Bad header line: parse failed
```

I installed this originally via rubygems and have not had issues before, but just got back to this ios app 6 months later :(

**Comment by milch** [comment]
@hojberg Can you run `brew update` please? It seems like you are running a very outdated version of `brew`/`brew cask`

**Comment by hojberg** [comment]
The homebrew version worked :)
