### ISSUE TITLE
CircleCI fails with Errno::EMFILE

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#7660]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

```
/Users/distiller/.gem/ruby/2.3.1/gems/coveralls-0.8.17/lib/coveralls/output.rb:63:in `require': Too many open files - getcwd (Errno::EMFILE)
  from /Users/distiller/.gem/ruby/2.3.1/gems/coveralls-0.8.17/lib/coveralls/output.rb:63:in `format'
  from /Users/distiller/.gem/ruby/2.3.1/gems/coveralls-0.8.17/lib/coveralls/output.rb:90:in `puts'
  from /Users/distiller/.gem/ruby/2.3.1/gems/coveralls-0.8.17/lib/coveralls/simplecov.rb:78:in `display_error'
  from /Users/distiller/.gem/ruby/2.3.1/gems/coveralls-0.8.17/lib/coveralls/simplecov.rb:74:in `rescue in format'
  from /Users/distiller/.gem/ruby/2.3.1/gems/coveralls-0.8.17/lib/coveralls/simplecov.rb:56:in `format'
  from /Users/distiller/.gem/ruby/2.3.1/gems/simplecov-0.12.0/lib/simplecov/result.rb:47:in `format!'
  from /Users/distiller/.gem/ruby/2.3.1/gems/simplecov-0.12.0/lib/simplecov/configuration.rb:172:in `block in at_exit'
  from /Users/distiller/.gem/ruby/2.3.1/gems/simplecov-0.12.0/lib/simplecov/defaults.rb:67:in `block in <top (required)>'
```

See https://circleci.com/gh/fastlane/fastlane/6783

should we add `ulimit -n 4096` or similar before launching the build?

**Comment by KrauseFx** [comment]
Where does this error come from? Does it occur on every build? How can we fix it in a clean wy

**Comment by hjanuschka** [comment]
i think it depends on which VM you land! - i recall when we raised it to 400 - i think @lacostej proposal to raise it to 4096 is good to go.

@DanToml or will this blow something up.

**Comment by DanToml** [comment]
@hjanuschka Should be fine 👍
