### ISSUE TITLE
fastlane doesn't work after the latest update

### ISSUE THREAD

**Issue by larryonoff** [fastlane/fastlane#772]
I get the following error.

```
/usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate xcpretty-travis-formatter-0.0.4, because xcpretty-0.1.12 conflicts with xcpretty (>= 0.0.7, ~> 0.2) (Gem::ConflictError)
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /usr/local/opt/rbenv/versions/2.2.3/bin/fastlane:22:in `<main>'
```

**Comment by KrauseFx** [comment]
I just pushed updates for all the gems, could you try again?

**Comment by larryonoff** [comment]
Thanks! It works now.
