### ISSUE TITLE
Deliver error due to "Unknown keyword: note"

### ISSUE THREAD

**Issue by eugeneshih** [fastlane/fastlane#7756]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm getting a failure in deliver. The error reported is "Unknown keyword: note". I looked at the stack trace and see that itunes_transporter.rb on line 383:

```
      account_manager = CredentialsManager::AccountManager.new(user: @user,
                                                             prefix: TWO_STEP_HOST_PREFIX,
                                                               note: "application-specific")
```

initializes account_manager with a new parameter named note. However, my version if credentials_manager (version 1.0.0) doesn't seem to have that in the initialize method:

```
    def initialize(user: nil, password: nil, prefix: nil)
```

I see that the `note` parameter was added yesterday.

https://github.com/fastlane/fastlane/commit/6e0780e8a95d1ae0367d676be91dbd2c0863b024

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
```
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
ArgumentError: [!] unknown keyword: note
  /usr/local/lib/ruby/gems/2.3.0/gems/credentials_manager-1.0.0/lib/credentials_manager/account_manager.rb:8:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:383:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:383:in `load_password_for_transporter'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:298:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/deliver-2.0.1/lib/deliver/runner.rb:82:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/deliver-2.0.1/lib/deliver/runner.rb:82:in `upload_binary'
  /usr/local/lib/ruby/gems/2.3.0/gems/deliver-2.0.1/lib/deliver/runner.rb:25:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/actions/deliver.rb:16:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/runner.rb:232:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/runner.rb:213:in `chdir'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:227:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/bin/fastlane:15:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
```

**Comment by eugeneshih** [comment]
Maybe this is because I've still got the old gems lying around and I need to remove them.

**Comment by fassko** [comment]
I just wanted to create issue for this. I have the same with fastlane 2.5.0

**Comment by eugeneshih** [comment]
I've resolved this issue. It turns out that I still the old legacy fastlane gems in my Gemfile. so I commented out / removed the old legacy gems.

```
gem "fastlane"
gem "xcodeproj", ">= 1.3.3"
gem "cocoapods", ">= 1.2.0.beta"
gem "aws-sdk"
# gem "deliver"
# gem "gym"
# gem "spaceship"
# gem "produce"
# gem "sigh"
# gem "pem"
```

**Comment by KrauseFx** [comment]
Hey everyone, thanks for reporting and this, as you already found out the issue is caused since you have the pre-2.0 gems in your Gemfile. Please update your Gemfile to only include `fastlane` (and in your case also `cocoapods` and `aws-sdk`), run `bundle update` and try again 👍

**Comment by fassko** [comment]
I had to remove the spaceship from my Gemfile and it worked. Thanks!

**Comment by KrauseFx** [comment]
Great to hear 👍
