### ISSUE TITLE
can't uninstall firim....

### ISSUE THREAD

**Issue by madordie** [fastlane/fastlane#7801]
How can I recover from this error

```
$ fastlane --help
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'firim' (~> 0) among 138 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/fastlane_require.rb:10:in `install_gem_if_needed'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:276:in `block in load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:268:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:268:in `load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:33:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by madordie** [comment]
😭😭😭

```
$ fastlane env
[20:54:09]: Generating fastlane environment output, this might take a few seconds...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'firim' (~> 0) among 138 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/fastlane_require.rb:10:in `install_gem_if_needed'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:276:in `block in load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:268:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:268:in `load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/environment_printer.rb:56:in `print_loaded_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/environment_printer.rb:27:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:223:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Do you run _fastlane_ using bundler? If so, can you share your Gemfile? If not, can you run `gem uninstall fastlane firim` and `gem cleanup` and `gem install fastlane` (with sudo if required)

**Comment by madordie** [comment]
```
  $ history
  519  gem uninstall fastlane firim
  520  sudo gem uninstall fastlane firim
  521  sudo gem uninstall firim
  522  gem cleanup
  523  sudo gem install fastlane
```
__ then __  
```
$ fastlane env
[21:21:43]: Generating fastlane environment output, this might take a few seconds...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'firim' (~> 0) among 138 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/fastlane_require.rb:10:in `install_gem_if_needed'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:276:in `block in load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:268:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:268:in `load_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/environment_printer.rb:56:in `print_loaded_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/environment_printer.rb:27:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:223:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>
```

In the history, I run `fastlane add_plugin firim`。

[fastlane tools docs](https://docs.fastlane.tools/actions/#plugins) have [firim](https://github.com/whlsxl/firim/tree/master/fastlane-plugin-firim), I installed it,But then it happened.🤦‍♂️

**Comment by KrauseFx** [comment]
You have to submit that issue to the plugin page, as this is not an issue with _fastlane_ itself, please submit the issue there: https://github.com/whlsxl/firim

**Comment by mfurtak** [comment]
If you're looking to remove everything about `firim`, the `firim` gem is a dependency of `fastlane-plugin-firim`. Please make sure to also remove

```
gem 'fastlane-plugin-firim'
```

from `fastlane/Pluginfile` if it is still there. 👍
