### ISSUE TITLE
Enterprise profile - No code signing identity found and can not create a new one because you enabled `readonly`

### ISSUE THREAD

**Issue by cyupa** [fastlane/fastlane#7822]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

###  I am running fastlane using match on a CI machine (Jenkins). I am trying to sign the app with an Enterprise profile. I have previously generated the certificate and profile locally and pushed them to the match repository.

One thing I have noticed is that for an enterprise profile it generates an `InHouse_my.app.identifier.inhouse.mobileprovision`.
 I used to rename this to `AppStore_my.app.identifier.inhouse.mobileprovision`and on match 0.8 this worked fine.
Since upgrading I am no longer able to do so.

I am creating the keychain `BuilderKeychain.keychain` before passing it to match.

Even though everything seems to be in place match fails to find the provisioning profile.

```
INFO [2017-01-11 17:08:37.42]: -------------------
INFO [2017-01-11 17:08:37.42]: --- Step: match ---
INFO [2017-01-11 17:08:37.42]: -------------------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/opt/ci/jenkins/workspace/ProjectName/fastlane/Appfile'
-------
INFO [2017-01-11 17:08:38.11]: Successfully loaded '/opt/ci/jenkins/workspace/ProjectName/fastlane/Matchfile' 📄

+------------+-----------------------------------------------------+
|           Detected Values from './fastlane/Matchfile'            |
+------------+-----------------------------------------------------+
| git_url    | git@server.net:Project/iOSCodeSigning.git           |
| git_branch | MYTEAMID                                            |
| verbose    | true                                                |
| username   | my.name@email.com                                   |
+------------+-----------------------------------------------------+

DEBUG [2017-01-11 17:08:38.11]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'

+-----------------------+-----------------------------------------------------+
|                           Summary for match 2.7.0                           |
+-----------------------+-----------------------------------------------------+
| type                  | appstore                                            |
| keychain_name         | BuilderKeychain.keychain                            |
| keychain_password     | XXXXXXXXX                                           |
| app_identifier        | my.app.identifier.inhouse                           |
| readonly              | true                                                |
| git_url               | git@server.net:Project/iOSCodeSigning.git           |
| git_branch            | MYTEAMID                                            |
| verbose               | true                                                |
| username              | my.name@email.com                                   |
| team_id               | MYTEAMID                                            |
| force                 | false                                               |
| skip_confirmation     | false                                               |
| shallow_clone         | false                                               |
| force_for_new_devices | false                                               |
| skip_docs             | false                                               |
+-----------------------+-----------------------------------------------------+

ERROR [2017-01-11 17:08:38.12]: Enterprise profiles are currently not officially supported in _match_, you might run into issues
INFO [2017-01-11 17:08:38.14]: Cloning remote git repo...
INFO [2017-01-11 17:08:38.14]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@server.net:Project/iOSCodeSigning.git' '/var/folders/s6/kfgl2w450kq_l9hsml6r0k5m0000gn/T/d20170111-32851-1b7yhr7'
INFO [2017-01-11 17:08:38.15]: ▸ Cloning into '/var/folders/s6/kfgl2w450kq_l9hsml6r0k5m0000gn/T/d20170111-32851-1b7yhr7'...
INFO [2017-01-11 17:08:39.35]: ▸ remote: Counting objects: 300, done.
INFO [2017-01-11 17:08:39.47]: ▸ remote: Compressing objects: 100% (281/281), done.
INFO [2017-01-11 17:08:39.69]: ▸ remote: Total 300 (delta 34), reused 0 (delta 0)
INFO [2017-01-11 17:08:39.69]: ▸ Receiving objects: 100% (300/300), 438.73 KiB | 0 bytes/s, done.
INFO [2017-01-11 17:08:39.69]: ▸ Resolving deltas: 100% (34/34), done.
INFO [2017-01-11 17:08:39.70]: ▸ Checking connectivity... done.
INFO [2017-01-11 17:08:39.71]: $ git branch --list origin/MYTEAMID --no-color -r
INFO [2017-01-11 17:08:39.72]: ▸ origin/MYTEAMID
INFO [2017-01-11 17:08:39.72]: Checking out branch MYTEAMID...
INFO [2017-01-11 17:08:39.72]: $ git checkout MYTEAMID
INFO [2017-01-11 17:08:39.73]: ▸ Branch MYTEAMID set up to track remote branch MYTEAMID from origin.
INFO [2017-01-11 17:08:39.74]: ▸ Switched to a new branch 'MYTEAMID'
INFO [2017-01-11 17:08:39.86]: 🔓  Decrypted 'F4ME6FQ6KA.cer'
INFO [2017-01-11 17:08:39.87]: 🔓  Decrypted 'YX2JX8ARDE.cer'
INFO [2017-01-11 17:08:39.88]: 🔓  Decrypted 'F4ME6FQ6KA.p12'
INFO [2017-01-11 17:08:39.88]: 🔓  Decrypted 'YX2JX8ARDE.p12'
INFO [2017-01-11 17:08:39.89]: 🔓  Decrypted 'AppStore_my.app.identifier.inhouse.mobileprovision'
INFO [2017-01-11 17:08:39.89]: 🔓  Decrypted 'InHouse_my.app.identifier.inhouse.mobileprovision'
INFO [2017-01-11 17:08:39.90]: 🔓  Decrypted 'Development_my.app.identifier.inhouse.mobileprovision'
INFO [2017-01-11 17:08:39.90]: 🔓  Successfully decrypted certificates repo
WARN [2017-01-11 17:08:39.90]: Couldn't find a valid code signing identity in the git repo for enterprise... creating one for you now
INFO [2017-01-11 17:08:39.91]: 🔒  Successfully encrypted certificates repo
INFO [2017-01-11 17:08:39.91]: -------------------
INFO [2017-01-11 17:08:39.91]: --- Step: is_ci ---
INFO [2017-01-11 17:08:39.91]: -------------------
INFO [2017-01-11 17:08:39.92]: -------------------
INFO [2017-01-11 17:08:39.92]: --- Step: slack ---
INFO [2017-01-11 17:08:39.92]: -------------------
DEBUG [2017-01-11 17:08:39.92]: Taking value for 'slack_url' from environment variable 'SLACK_URL'
INFO [2017-01-11 17:08:40.60]: Successfully sent Slack notification
WARN [2017-01-11 17:08:40.60]: Lane Context:
INFO [2017-01-11 17:08:40.61]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"pp", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios publish", :XCODEBUILD_DERIVED_DATA_PATH=>"build", :VERSION_NUMBER=>"1.4.0-PP", :BUILD_NUMBER=>"140.1235", :SCAN_DERIVED_DATA_PATH=>"build", :SCAN_GENERATED_PLIST_FILES=>[], :SCAN_GENERATED_PLIST_FILE=>nil}
ERROR [2017-01-11 17:08:40.61]: No code signing identity found and can not create a new one because you enabled `readonly`
```

```
/Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane_core/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] No code signing identity found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneCrash)
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/match/lib/match/runner.rb:72:in `fetch_certificate'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/match/lib/match/runner.rb:30:in `run'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/actions/match.rb:8:in `run'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:232:in `block (2 levels) in execute_action'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:171:in `block (2 levels) in parsing_binding'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:188:in `try_switch_to_lane'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:143:in `trigger_action_by_name'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:132:in `block (2 levels) in parsing_binding'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.7.0/bin/fastlane:15:in `<top (required)>'
	from /Users/jenkins/.rbenv/versions/2.3.0/bin/fastlane:23:in `load'
	from /Users/jenkins/.rbenv/versions/2.3.0/bin/fastlane:23:in `<main>'

```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                         |
| ------------------- | --------------------------------------------- |
| OS                  | 10.11.6                                       |
| Ruby                | 2.3.0                                         |
| Bundler?            | false                                         |
| Git                 | git version 2.8.4 (Apple Git-73)              |
| Installation Source | ~/.rbenv/versions/2.3.0/bin/fastlane          |
| Host                | Mac OS X 10.11.6 (15G1212)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.0/lib                   |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                   |
| Is contained        | false                                         |
| Xcode Path          | /Applications/Xcode-8.app/Contents/Developer/ |
| Xcode Version       | 8.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import_from_git(url: "https://github.com/xfreebird/fastlane-utils")

default_platform :ios

platform :ios do

  before_all do
    set_bloodhound_host
    setup_jenkins

    sh "security list-keychains -d user"
    if File.exists?(File.expand_path("~/Library/Keychains/BuilderKeychain.keychain"))
       puts "Deleting existing keychain"
       FileUtils.rm_f(File.expand_path("~/Library/Keychains/BuilderKeychain.keychain"))
    end

    create_keychain(
        name: "BuilderKeychain.keychain",
        # path: "./bs_keychain.keychain",
        unlock: true,
        timeout: false,
        lock_when_sleeps: false,
        lock_after_timeout: false,
        password: "password",
        add_to_search_list: true
    )
    xcclean(
      configuration: "#{ENV['XCODE_CONFIGURATION']}",
      derivedDataPath: "#{ENV['XCODE_BUILD_PATH']}"
    )

    lock_pods {
        # use cocoapods 1.0.0 specified in the Gemfile
        cocoapods
    }

    if is_ci?
      sh "git config user.name 'Mobile CI'"
      sh "git config user.email 'my@email.com'"
    end
  end

  desc "Runs snapshot"
  lane :uisnapshots do
    # lock_simulator {
    #   snapshot
    # }
  end

  desc "Runs all the tests"
  lane :test do
    puts "Unit tests are disabled for CI. Need to fix the issue with the CI build machines"
    unittest
  end

  desc "Runs all the unittests"
  lane :unittest do
    lock_simulator {
      close_simulator
      sh "echo 'y' | snapshot reset_simulators"
      warmup_simulator
      uninstall_simapp("#{ENV['APP_IDENTIFIER']}")
      scan
    }
    # Create code coverage reports
    slather
  end

  desc "Create Sonar reports"
  lane :sonarqube do
    unittest
    oclint({
      select_reqex: /(Project\/CoreData\/|Project\/AppDelegate\/).+m/
    })
  end

  lane :publish do
    createchangelog
    bt_update_app_identifier
    appstore_build = ["appstore"].include? ENV['BS_BUILD_PROFILE']
    stage_build = ["preproduction"].include? ENV['BS_BUILD_PROFILE']
    beta_build = ["kt"].include? ENV['BS_BUILD_PROFILE']

    unittest

    if appstore_build
      itunesconnect
    elsif stage_build
      # push version bump changes to git branch
      hockeyapp(gitrelease: false, gitupdate: true)
    elsif beta_build
      # create git release and tag
      hockeyapp(gitrelease: true, gitupdate: false)
    else
      # beta builds
      hockeyapp(gitrelease: false, gitupdate: false)
    end

    if is_ci?
      slack(
        message: "New release !\n Version: #{ENV['BS_VERSION']}\nBuild number: #{ENV['BS_BUILD_NUMBER']}",
        success: true,
        payload: {
          "Build Date" => Time.new.to_s,
          "Built by" => "Jenkins",
        }
      )
    end
  end

  desc "Create OCR Universal Framework"
  lane :buildocrlib do
    sh "cd ../Thirdparty/OCRCamera && ./ios-build-framework-script.sh"
  end

  desc "Create Change log"
  private_lane :createchangelog do
    unless ENV['CHANGELOG']
      previous_release_tag = "#{get_version_number.strip}_#{get_build_number.strip}"
      previous_release_commit = sh "git rev-list #{previous_release_tag} -n 1"
      current_commit = sh "git rev-parse HEAD"
      change_log =  sh("git log #{previous_release_commit.strip}...#{current_commit.strip} | grep -v branch | grep NETDV003 | sed 's/^ *//;s/ *$//' | sort").split("\n")
      change_log.uniq!
      ENV['CHANGELOG'] = change_log.join("\n")
      ENV['FL_HOCKEY_NOTES'] = change_log.join("<br>\n")
    end

    puts "Changelog:"
    puts "#{ENV['CHANGELOG']}"
  end

  private_lane :hockeyapp do |options|
    bt_update_project_version(options)
    ENV["MATCH_FORCE_ENTERPRISE"] = "1"
    match(
      type: "appstore",
      keychain_name: "BuilderKeychain.keychain",
      keychain_password: "password",
      app_identifier: "#{ENV['APP_IDENTIFIER']}",
      readonly: true
    )
    gym

    if options[:gitrelease]
      git_release
    end

    if options[:gitupdate]
      git_update_changes
    end

    hockey
  end

  desc "Deploy a new version to the App Store/Testflight. Must set FASTLANE_PASSWORD env var"
  private_lane :itunesconnect do
    bt_update_project_version(gitrelease: false, gitupdate: true)
    ENV["MATCH_FORCE_ENTERPRISE"] = "1"
    match(
      type: "appstore",
      keychain_name: "BuilderKeychain.keychain",
      keychain_password: "password",
      app_identifier: "#{ENV['APP_IDENTIFIER']}",
      readonly: true
    )
    gym

#    hockey(upload_dsym_only: true)
#    git_update_changes
  end

  private_lane :update_version_variables do
    # Use Jenkins BUILD_NUMBER, if it exists
    ci_build_number = ENV['BUILD_NUMBER'] ? ENV['BUILD_NUMBER'] : "0"

    # for xcode project settings
    ENV['BS_APP_VERSION'] = get_version_number
    ENV['BS_PROJECT_VERSION'] = get_build_number

    unless ENV['APP_VERSION'].to_s.empty?
      ENV['BS_APP_VERSION'] = ENV['APP_VERSION']
    end

    # for Info.plist from build
    ENV['BS_VERSION'] = "#{ENV['BS_APP_VERSION']}#{ENV['APP_VER_SUFFIX']}"
    ENV['BS_BUILD_NUMBER'] = "#{ENV['BS_PROJECT_VERSION']}.#{ci_build_number}"

    puts "App Version: #{ENV['BS_VERSION']} Build Number: #{ENV['BS_BUILD_NUMBER']}"
  end

  private_lane :bt_update_project_version do |options|
    if options[:gitrelease]
      # increment build number only for git release
      increment_build_number
    end

    update_version_variables

    # set build number and version in Info.plist
    increment_build_number(build_number: ENV['BS_BUILD_NUMBER'])
    increment_version_number(version_number: ENV['BS_VERSION'])
  end

  # set PRODUCT_BUNDLE_IDENTIFIER
  private_lane :bt_update_app_identifier do
    sh "cat ../Project.xcodeproj/project.pbxproj | \
        sed s/'PRODUCT_BUNDLE_IDENTIFIER = .*;'/'PRODUCT_BUNDLE_IDENTIFIER = \"#{ENV['APP_IDENTIFIER']}\";'/g > new.project.pbxproj"
    sh "mv new.project.pbxproj ../Project.xcodeproj/project.pbxproj"
  end

  private_lane :git_release do
    sh "git fetch --all"
    sh "git reset --hard"
    sh "git checkout develop"
    sh "git pull origin develop"

    increment_build_number(build_number: ENV['BS_PROJECT_VERSION'])
    increment_version_number(version_number: ENV['BS_APP_VERSION'])

    release_name = "#{ENV['BS_APP_VERSION']}_#{ENV['BS_PROJECT_VERSION']}"

    sh "git checkout '../ProjectTests/Info.plist'"
    sh "git add '../Project.xcodeproj' '../Project/Supporting Files/Info.plist'"
    sh "git commit -m 'Release #{release_name}'"
    sh "git reset --hard"
    sh "git checkout master"
    sh "git pull origin master"
    sh "git merge -X theirs develop"
    sh "git tag -a '#{release_name}' -m 'Release #{release_name}'"
    sh "git branch release/#{release_name}"
    sh "git checkout release/#{release_name}"
    sh "git push origin master develop 'release/#{release_name}' '#{release_name}'"
    sh "git push origin '#{release_name}'"
  end

  private_lane :git_update_changes do
    branch = is_ci? ? ENV['Branch'] : git_branch

    sh "git fetch --all"
    sh "git reset --hard"
    sh "git checkout '#{branch}'"

    increment_build_number(build_number: ENV['BS_PROJECT_VERSION'])
    increment_version_number(version_number: ENV['BS_APP_VERSION'])

    release_name = "#{ENV['BS_APP_VERSION']}_#{ENV['BS_BUILD_NUMBER']}"
    release_message = "Release #{ENV['BS_APP_VERSION']} #{ENV['BS_BUILD_PROFILE']}"

    if ENV['BS_BUILD_PROFILE'] == "appstore"
      release_name = "appstore_#{release_name}"
    end

    sh "git tag -a '#{release_name}' -m '#{release_message}'"
    sh "git push origin '#{release_name}'"
  end

  error do |lane, exception|
    if is_ci?
        message = "Build on lane #{lane} failed with #{exception}!"
        if message.length >= 10000
            puts "Message bigger than 10,000: #{exception}"
            message = message[0, 9999]
        end
        slack(
          message: message,
          success: false,
          payload: {
            "Build Date" => Time.new.to_s,
            "Built by" => "Jenkins",
          }
        )
    end
  end
end

# set bloodhound IP and defalt ADBMobileConfig
def set_bloodhound_host
  bloodhound_host = ENV['BLOODHOUNDIP']

  if bloodhound_host
    puts "Configuring bloodhound with IP #{bloodhound_host}"
    adb_bloodhound_config = "Project/Supporting Files/Configurations/ADBMobile/ADBMobileConfig"
    sh "cat '../#{adb_bloodhound_config}-Bloodhound.json' | sed s/localhost/#{bloodhound_host}/g > '../#{adb_bloodhound_config}.sed'"
    sh "cp -fv '../#{adb_bloodhound_config}.sed' '../#{adb_bloodhound_config}-Bloodhound.json'"
    sh "cp -fv '../#{adb_bloodhound_config}.sed' '../#{adb_bloodhound_config}-Testing.json'"
    sh "cp -fv '../#{adb_bloodhound_config}.sed' '../#{adb_bloodhound_config}-Production.json'"

    ENV['APP_VER_SUFFIX'] = "-bloodhound"
  end
end

after_all do
  delete_keychain(name: "BuilderKeychain.keychain")
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#the-appfile
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.7.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| rubyzip                   | 1.2.0        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-01-11**
</details>

**Comment by cyupa** [comment]
At a second look, match doesn't seem to use the `BuilderKeychain.keychain` keychain at all.

**Comment by cyupa** [comment]
Running `fastlane match appstore --readonly` does not replicate this issue. It manages to install the required certificate.

**Comment by PetrosIchor** [comment]
If the enterprise match task is failing, it might be because you are not setting the force enterprise flag.  Match officially does not support enterprise, you need to set the force environment variable for it to work. 

When match runs with the flag enabling enterprise, it'll show a message that enterprise is not supported.  That's a good way to know it's attempting to use enterprise.

**Comment by cyupa** [comment]
I don't think that's true. I have managed to "fix" this issue by renaming the profiles generated by Match in the Git repository. I'm not sure if we could do this but, specifying an enterprise flag when running `match init` would benefit as I see it right now. 

I see that when setting `MATCH_FORCE_ENTERPRISE` to true, Match looks for profiles that are named `InHouse_*.mobileprovision` but when those profiles are generated, they start with `AppStore`.
This is just an idea, maybe I missed it in the docs.

Last but not least, thank you all for this great tool. I've been using fastlane for over an year and I couldn't imagine going on without it. Thank you all for constantly improving this tool and listening to our needs. 👏
