### ISSUE TITLE
Unable to run deliver for OSX target: unknown keyword: platform

### ISSUE THREAD

**Issue by SemenovAlexander** [fastlane/fastlane#7876]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After update from 2.5.0 to 2.8.0 I'm no longer able to upload binary file to iTunesConnect using deliver, it always fails with error below.
I use bundler to run fastlane and use system Ruby, which is shipped with OSX Sierra:
`ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]`

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
Successfully loaded Appfile at path '/Volumes/Workspace/Xcode/vpn-shield-mac-osx/fastlane/Appfile'
- app_identifier: '***'
- apple_id: '***'
- team_name: '***.'
- team_id: '***'
-------
INFO [2017-01-16 14:23:00.53]: options: #<FastlaneCore::Configuration:0x007f9e97490f38>
INFO [2017-01-16 14:23:00.53]: Login to iTunes Connect (jenkins.2kgroup@gmail.com)
Looking for iTunes Connect Team with ID 117739172
INFO [2017-01-16 14:23:04.89]: Login successful
INFO [2017-01-16 14:23:06.63]: $ xar -C /var/folders/n7/zhqf84d17gb2cy88blm_s2100000gn/T/d20170116-28193-v0exih -xf artifacts/vpnshield.pkg

+-----------------------+---------------------------+
|               deliver 2.8.0 Summary               |
+-----------------------+---------------------------+
| pkg                   | artifacts/vpnshield.pkg   |
| skip_screenshots      | true                      |
| skip_metadata         | true                      |
| platform              | osx                       |
| screenshots_path      | ./fastlane/screenshots    |
| metadata_path         | ./fastlane/metadata       |
| app_version           | 2.16                      |
| username              | jenkins.2kgroup@gmail.com |
| app_identifier        | com.stidia.vpnshield      |
| edit_live             | false                     |
| skip_binary_upload    | false                     |
| force                 | false                     |
| submit_for_review     | false                     |
| automatic_release     | false                     |
| dev_portal_team_id    | 77NL99R8C4                |
| dev_portal_team_name  | Defendemus sp. z o.o.     |
| overwrite_screenshots | false                     |
+-----------------------+---------------------------+

INFO [2017-01-16 14:23:06.68]: Making sure the latest version on iTunes Connect matches '2.16' from the ipa file...
INFO [2017-01-16 14:23:08.62]: '2.16' is the latest version on iTunes Connect
INFO [2017-01-16 14:23:12.62]: Uploading binary to iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...
Search query: unknown keyword: platform

URL: https://api.github.com/search/issues?q=unknown%20keyword:%20platform+repo:fastlane/fastlane
➡️  Can't send pkg to iTC
   https://github.com/fastlane/fastlane/issues/7772 [closed] 9 💬
   a week ago

➡️  fastlane/snapshot/example fails
   https://github.com/fastlane/fastlane/issues/6288 [open] 10 💬
   23 Nov 2016

➡️  Remove Shenzhen dependency
   https://github.com/fastlane/fastlane/pull/6991 [closed] 19 💬
   5 weeks ago

bundler: failed to load command: fastlane (/Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/bin/fastlane)
ArgumentError: [!] unknown keyword: platform
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/deliver/lib/deliver/runner.rb:93:in `upload_binary'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/deliver/lib/deliver/runner.rb:26:in `run'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/deliver/lib/deliver/commands_generator.rb:62:in `block (2 levels) in run'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/bundler/gems/fastlane-f9b00c832ed1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/deliver/lib/deliver/commands_generator.rb:148:in `run'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/bin/fastlane:15:in `<top (required)>'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/bin/fastlane:23:in `load'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/bin/fastlane:23:in `<top (required)>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
[14:26:14]: Generating fastlane environment output, this might take a few seconds...

Looking for related GitHub issues on fastlane/fastlane...

➡️  uninitialized constant CredentialsManager::PasswordManager
   https://github.com/fastlane/fastlane/issues/7653 [closed] 11 💬
   4 days ago

bundler: failed to load command: fastlane (/Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/bin/fastlane)
NoMethodError: [!] undefined method `sensitive_strings' for FastlaneCore::Configuration:Class
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/fastlane/lib/fastlane/environment_printer.rb:7:in `output'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/fastlane/lib/fastlane/commands_generator.rb:223:in `block (2 levels) in run'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/bundler/gems/fastlane-f9b00c832ed1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/fastlane-2.8.0/bin/fastlane:15:in `<top (required)>'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/bin/fastlane:23:in `load'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/bin/fastlane:23:in `<top (required)>'
```

**Comment by SemenovAlexander** [comment]
Hmm, now looking more to output, I can see, that new fastlane monogem somehow interferes with older installation here (I use snapshot from PR #7363 to take screenshots of my Mac app. which is also installed via bundler):

`  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/bundler/gems/fastlane-f9b00c832ed1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Volumes/Workspace/Xcode/vpn-shield-mac-osx/.vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'`

**Comment by mfurtak** [comment]
@SemenovAlexander Yes, because the _fastlane_ monogem includes _snapshot_, it can be hazardous to have both the old, independent gems and the new, _fastlane_ monogem installed.

Is it possible for you to rebase your PR on master, and then install the _fastlane_ monogem from your fork? That should then include your _snapshot_ changes, and you should be able to uninstall the separate _snapshot_ gem.

**Comment by mfurtak** [comment]
It looks like @ohwutup is working to get your other PR merged, though, so perhaps you will not need this setup for much longer... 👍

**Comment by SemenovAlexander** [comment]
@mfurtak  yeap, I've rebased my changes on latest master and now all works fine for me. 

But still, I think, it would be nice to detect already installed old gems and warn user, he could have problems with such setup. 
This issue was pretty unexpected and hard to debug for me, as user, who not much familiar with ruby.

**Comment by mfurtak** [comment]
Great, I'm glad you're back in a working state.

I definitely hear you, with regard to the gem changes and the older tools' gems. We'll do some thinking about how improve this situation 👍
