### ISSUE TITLE
Error building the application with strange sometime

### ISSUE THREAD

**Issue by icyleaf** [fastlane/fastlane#788]
In my project, i using jenkins with mac mini as slave to build ipa and upload it. same code and same environment, sometime it always throw same error:

```bash
▸ Copying UMSocialLocalizable.strings
▸ Compiling UMShareEditViewControlleriPad.xib
▸ Compiling UMSShareListController.xib
▸ Compiling UMShareEditViewController.xib
** ARCHIVE FAILED **


The following build commands failed:
CompileXIB QYER/Normal/Guide/View/QYGuideDetailBottomBar.xib
CompileXIB QYER/Resource/Third-Party/UMeng/UMShare_Sdk/UMSocial_Sdk_4.2.3/SocialSDKXib/UMShareEditViewController.xib
(2 failures)
[12:32:22]: Exit status: 65
[12:32:22]: [Fastlane] Error: Error building the application - see the log above
[12:32:22]: Variable Dump:
[12:32:22]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios jenkins", :JENKINS_CHANGLOG=>"some string about build changelog ", :JENKINS_CVS_BRANCH=>"develop", :JENKINS_CVS_COMMIT=>"fd4a972b83b3668d768cf4fcb6a0714d9bff090e", :JENKINS_CI_URL=>"http://ci.host/job/Qyer%20App%20iPhone/1412/", :SIGH_PROFILE_PATH=>"/Users/qyer/Jenkins/Jenkins/workspace/Qyer App iPhone/AdHoc_com.qyer.qyerguide.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/qyer/Jenkins/Jenkins/workspace/Qyer App iPhone/AdHoc_com.qyer.qyerguide.mobileprovision"], :SIGH_UDID=>"9190597e-5f51-481e-8d52-5bafd4b19cf9", :SIGH_PROFILE_TYPE=>"ad-hoc"}
[12:32:22]: Error building the application - see the log above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | jenkins                             | 0           |
| 4    | unlock_keychain                     | 0           |
| 5    | cocoapods                           | 50          |
| 6    | xcode_select                        | 0           |
| 7    | sigh                                | 40          |
| 8    | gym                                 | 298         |
+------+-------------------------------------+-------------+

[12:32:24]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`
👍  This makes resolving issues much easier and helps improving fastlane
🔒  The reports might contain personal data, but will be stored securely on getsentry.com
✨  Once crash reporting is enabled, you have much cleaner output when something goes wrong
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/gym-1.1.4/lib/gym/error_handler.rb:52:in `handle_build_error': Error building the application - see the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.1.4/lib/gym/runner.rb:80:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/command_executor.rb:62:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/command_executor.rb:62:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.1.4/lib/gym/runner.rb:76:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.1.4/lib/gym/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.1.4/lib/gym/manager.rb:8:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:92:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/bin/fastlane:152:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.36.4/bin/fastlane:158:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

here is my `Fastlane` file:

```ruby
fastlane_version "1.16.0"
default_platform :ios
platform :ios do
  before_all do
      # fetch and parse some env variables and save to fastlane shared env.
      jenkins
      unlock_keychain(
        path: 'login.keychain',
        password: ENV['MAC_KEYCHAIN_PASSWORD']
      )
    cocoapods
    xcode_select "/Applications/Xcode.app"
  end

  lane :jenkins do
    sigh(
      adhoc: true
    )
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    gym(
      scheme: "QYER",
      configuration: "AdHoc",
      sdk: "iphoneos",
      clean: true,
      use_legacy_build_api: true,
    )
```

ENV:
* OS: Mac mini 10.11
* Ruby(system): 2.0.0p481
* Xcode: 7.1
* fastlane: 1.36.1
* gym: 1.1.4

**Comment by xfreebird** [comment]
@icyleaf try updating ```CFPropertyList``` system Ruby gem.

```bash
sudo gem update CFPropertyList
```

The older version of this gem is known to cause ```xcodebuild archive``` command to fail.

**Comment by icyleaf** [comment]
yes, i had upgrade `CFPropertyList ` to the latest version: **2.3.2**

**Comment by xfreebird** [comment]
In this case check ```xcodebuild``` logs created by ```gym```, there you might get more clues.
The default logs are located at ```~/Library/Logs/gym```.

Have you tried using ```gym``` without ```use_legacy_build_api: true```.

```ruby
gym(
      scheme: "QYER",
      configuration: "AdHoc",
      sdk: "iphoneos",
      clean: true,
      export_method: 'ad-hoc'
    )
```
Are you using system Ruby, or ```rbenv``` or ```rvm``` ?

**Comment by icyleaf** [comment]
System ruby. But why does it can be success build and archive with nothing change sometime? 

it running about 1 week using this `Fastlane` file, most time is ok.

**Comment by icyleaf** [comment]
Just 5 minutes ago, i press build button with same code, it success :(

**Comment by xfreebird** [comment]
You need to see that in ```xcodebuild``` logs. You could alos share them here. It might be something particular to your case.

**Comment by icyleaf** [comment]
Okay.

**Comment by icyleaf** [comment]
Watched error log:
```
CompileXIB QYER/Resource/Third-Party/UMeng/UMShare_Sdk/UMSocial_Sdk_4.2.3/SocialSDKXib/UMShareEditViewController.xib
    cd "/Users/qyer/Jenkins/Jenkins/workspace/Qyer App iPhone"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin/:/usr/local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin"
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module QYER --output-partial-info-plist /Users/qyer/Library/Developer/Xcode/DerivedData/QYER-csvncpqjuntqjydjrwniwfsygubr/Build/Intermediates/ArchiveIntermediates/QYER/IntermediateBuildFilesPath/QYER.build/AdHoc-iphoneos/QYER.build/UMShareEditViewController-PartialInfo.plist --auto-activate-custom-fonts --target-device iphone --minimum-deployment-target 7.0 --output-format human-readable-text --compile /Users/qyer/Library/Developer/Xcode/DerivedData/QYER-csvncpqjuntqjydjrwniwfsygubr/Build/Intermediates/ArchiveIntermediates/QYER/InstallationBuildProductsLocation/Applications/QYER.app/UMShareEditViewController.nib /Users/qyer/Jenkins/Jenkins/workspace/Qyer\ App\ iPhone/QYER/Resource/Third-Party/UMeng/UMShare_Sdk/UMSocial_Sdk_4.2.3/SocialSDKXib/UMShareEditViewController.xib
2015-11-03 08:33:58.258 ibtoold[41799:20224396] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEInterfaceBuilder/IDEInterfaceBuilder-9059/InterfaceBuilderKit/Utilities/IBAbstractInterfaceBuilderPlatformToolManager.m:253
Details:  Failed to attach to Interface Builder Cocoa Touch Tool with error: Error Domain=com.apple.InterfaceBuilder Code=-1 "Encountered an error communicating with Interface Builder Cocoa Touch Tool." UserInfo=0x7f933e691050 {NSUnderlyingError=0x7f933e618d60 "Failed to launch Interface Builder Cocoa Touch Tool via CoreSimulator spawn", NSLocalizedDescription=Encountered an error communicating with Interface Builder Cocoa Touch Tool., NSLocalizedRecoverySuggestion=Please check Console.app for crash reports for "Interface Builder Cocoa Touch Tool" for further information., NSLocalizedFailureReason=Interface Builder Cocoa Touch Tool (41809) failed to launch}
Object:   <IBCocoaTouchToolManager>
Method:   +_THREADSAFE_launchNewToolWithLaunchContext:executionContext:toolProxyClass:failureContext:requestingMethod:error:forReason:
Thread:   <NSThread: 0x7f933bc4fb40>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-11-03 08:33:58.923 ibtoold[41799:20224396] [MT] IBPlatformTool: *** Failed to launch tool with description <IBCocoaTouchPlatformToolDescription: 0x7f933ea07f90> System content 1x for IBCocoaTouchFramework w/ default fidelity: Encountered an error communicating with Interface Builder Cocoa Touch Tool. (Failure reason: Interface Builder Cocoa Touch Tool (41809) failed to launch): Failed to launch Interface Builder Cocoa Touch Tool via CoreSimulator spawn: Failed to handshake with platform tool (Failure reason: Failed to open connection over FIFOs with platform tool): : Failed to open FIFOs for handshaking with platform tool (Failure reason: Timed out waiting for FIFOs to open. Most likely Interface Builder Cocoa Touch Tool crashed before it could open the other end.)
2015-11-03 08:34:07.939 ibtoold[41799:20224396] [MT] IBPlatformTool: Failed to write out diagnostics for marshalling failure: Error Domain=NSCocoaErrorDomain Code=516 "Failed to write out diagnostics for failure" UserInfo=0x7f933ed10af0 {NSLocalizedDescription=Failed to write out diagnostics for failure, NSUnderlyingError=0x7f933ed10610 "Failed to setup directory for failure diagnostics"}
/* com.apple.ibtool.errors */
/Users/qyer/Jenkins/Jenkins/workspace/Qyer App iPhone/QYER/Resource/Third-Party/UMeng/UMShare_Sdk/UMSocial_Sdk_4.2.3/SocialSDKXib/UMShareEditViewController.xib: error: Internal error. Please file a bug at bugreport.apple.com and attach all crash logs from ~/Library/Logs/DiagnosticReports.
    Recovery Suggestion: Please check Console.app for crash reports for "Interface Builder Cocoa Touch Tool" for further information.
    Underlying Errors:
        Description: Encountered an error communicating with Interface Builder Cocoa Touch Tool.
        Failure Reason: Interface Builder Cocoa Touch Tool (41809) failed to launch
        Recovery Suggestion: Please check Console.app for crash reports for "Interface Builder Cocoa Touch Tool" for further information.
        Underlying Errors:
            Description: Failed to launch Interface Builder Cocoa Touch Tool via CoreSimulator spawn
            Underlying Errors:
                Description: Failed to handshake with platform tool
                Failure Reason: Failed to open connection over FIFOs with platform tool
                Underlying Errors:
                    Description:
                    Recovery Suggestion: Try restarting your computer
                    Underlying Errors:
                        Description: Failed to open FIFOs for handshaking with platform tool
                        Failure Reason: Timed out waiting for FIFOs to open. Most likely Interface Builder Cocoa Touch Tool crashed before it could open the other end.
```

**Comment by icyleaf** [comment]
> Recovery Suggestion: Try restarting your computer

i will try it :(

**Comment by icyleaf** [comment]
after restarting computer and build again, throws same error again:

```
CompileXIB QYER/Resource/Third-Party/UMeng/UMShare_Sdk/UMSocial_Sdk_4.2.3/SocialSDKXib/UMShareEditViewController.xib
    cd "/Users/qyer/Jenkins/Jenkins/workspace/Qyer App iPhone"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin/:/usr/local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin"
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module QYER --output-partial-info-plist /Users/qyer/Library/Developer/Xcode/DerivedData/QYER-csvncpqjuntqjydjrwniwfsygubr/Build/Intermediates/ArchiveIntermediates/QYER/IntermediateBuildFilesPath/QYER.build/AdHoc-iphoneos/QYER.build/UMShareEditViewController-PartialInfo.plist --auto-activate-custom-fonts --target-device iphone --minimum-deployment-target 7.0 --output-format human-readable-text --compile /Users/qyer/Library/Developer/Xcode/DerivedData/QYER-csvncpqjuntqjydjrwniwfsygubr/Build/Intermediates/ArchiveIntermediates/QYER/InstallationBuildProductsLocation/Applications/QYER.app/UMShareEditViewController.nib /Users/qyer/Jenkins/Jenkins/workspace/Qyer\ App\ iPhone/QYER/Resource/Third-Party/UMeng/UMShare_Sdk/UMSocial_Sdk_4.2.3/SocialSDKXib/UMShareEditViewController.xib
2015-11-03 11:07:29.476 ibtoold[6794:10289] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEInterfaceBuilder/IDEInterfaceBuilder-9059/InterfaceBuilderKit/Utilities/IBAbstractInterfaceBuilderPlatformToolManager.m:253
Details:  Failed to attach to Interface Builder Cocoa Touch Tool with error: Error Domain=com.apple.InterfaceBuilder Code=-1 "Encountered an error communicating with Interface Builder Cocoa Touch Tool." UserInfo=0x7f9255566320 {NSUnderlyingError=0x7f92559569c0 "Failed to launch Interface Builder Cocoa Touch Tool via CoreSimulator spawn", NSLocalizedDescription=Encountered an error communicating with Interface Builder Cocoa Touch Tool., NSLocalizedRecoverySuggestion=Please check Console.app for crash reports for "Interface Builder Cocoa Touch Tool" for further information., NSLocalizedFailureReason=Interface Builder Cocoa Touch Tool (6798) failed to launch}
Object:   <IBCocoaTouchToolManager>
Method:   +_THREADSAFE_launchNewToolWithLaunchContext:executionContext:toolProxyClass:failureContext:requestingMethod:error:forReason:
Thread:   <NSThread: 0x7f9252c3a880>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-11-03 11:07:29.522 ibtoold[6794:10289] [MT] IBPlatformTool: *** Failed to launch tool with description <IBCocoaTouchPlatformToolDescription: 0x7f9252d2e4b0> System content 1x for IBCocoaTouchFramework w/ default fidelity: Encountered an error communicating with Interface Builder Cocoa Touch Tool. (Failure reason: Interface Builder Cocoa Touch Tool (6798) failed to launch): Failed to launch Interface Builder Cocoa Touch Tool via CoreSimulator spawn: Failed to handshake with platform tool (Failure reason: Failed to open connection over FIFOs with platform tool): : Failed to open FIFOs for handshaking with platform tool (Failure reason: Timed out waiting for FIFOs to open. Most likely Interface Builder Cocoa Touch Tool crashed before it could open the other end.)
```

**Comment by xfreebird** [comment]
It looks to me an ```xcodebuild``` bug, try to reinstall/install latest ```Xcode``` or try to see if you have the same behaviour with an ```Xcode beta```.

**Comment by icyleaf** [comment]
it is not works after reinstall xcode 7.1, but i try build with `xcodebuild` and `xcexport` action, it works:

```ruby
    xcodebuild(
      clean: true,
      archive: true,
      workspace: 'QYER.xcworkspace',
      configuration: 'AdHoc',
      scheme: 'QYER',
      sdk: 'iphoneos',
    )

    xcexport
```

`xcodebuild` and `xcexport`:
```bash
set -o pipefail && xcodebuild -archivePath "QYER.xcarchive" -configuration "AdHoc" -scheme "QYER" -sdk "iphoneos" -workspace "QYER.xcworkspace" archive clean | tee '/Users/qyer/Library/Logs/fastlane/xcbuild/2015-11-04/65092/xcodebuild.log' | xcpretty --color --simple

set -o pipefail && xcodebuild -archivePath "QYER.xcarchive" -exportArchive -exportFormat "ipa" -exportPath "QYER" | tee '/Users/qyer/Library/Logs/fastlane/xcbuild/2015-11-04/65092/xcodebuild.log' | xcpretty --color --simple
```


`gym`:
```bash
set -o pipefail && xcodebuild -workspace './QYER.xcworkspace' -scheme 'QYER' -configuration 'AdHoc' -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath '/Users/qyer/Library/Developer/Xcode/Archives/2015-11-03/QYER 2015-11-03 17.19.48.xcarchive' clean archive | tee '/Users/qyer/Library/Logs/gym/QYER-QYER.log' | xcpretty
```

**Comment by zyzof** [comment]
I came across this issue page whilst googling the same error message (from a different project).

This was occurring approximately every second attempt to build my project with Xcode 7.1. I've updated to Xcode 7.2 and it's yet to reoccur.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
