### ISSUE TITLE
Can't run test lane inside itself

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#791]
Trying to run the following inside the test lane:
`test(app: 'lib')`
The idea is to run tests of lib before the app itself.

But I get and error:
`no implicit conversion of Hash into Integer`

**Comment by KrauseFx** [comment]
Please provide your `Fastfile`, the full output and the stack trace so I can help you resolve this issue :+1:

**Comment by yakimant** [comment]
Sure! Here is an imaginary part of code:
```
 16   lane :test do |options|
 17     if options[:app] == 'app'
 18       test(app: 'lib')
 19     end
 20
 21     buildAndTest(app: options[:app])
 22   end
 23
 24   private_lane :buildAndTest do |options|
 25     puts "Building #{options[:app]}"
 26   end
```

And the output:
```
13:45:24]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[13:45:24]: no implicit conversion of Hash into Integer
```

And the stack trace:
```
Fastfile:18:in `test': no implicit conversion of Hash into Integer (TypeError)
	from Fastfile:18:in `block (2 levels) in parsing_binding'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/bin/fastlane:152:in `run'
	from /Users/yakimant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.37.0/bin/fastlane:158:in `<top (required)>'
	from /Users/yakimant/.rbenv/versions/2.2.2/bin/fastlane:23:in `load'
	from /Users/yakimant/.rbenv/versions/2.2.2/bin/fastlane:23:in `<main>'
```

I'm not in Ruby so much, but maybe there is a built in test function?

**Comment by yakimant** [comment]
Yes, I think, that it's because of defined test() method somewhere.

**Comment by KrauseFx** [comment]
Mh, it might be some kind of name conflict. 

Is that the full `Fastfile`?

Try
```ruby
 16   lane :test do |options|
 17     options[:app] = 'lib' if options[:app] == 'app'
 20
 21     buildAndTest(app: options[:app])
 22   end
 23
 24   private_lane :buildAndTest do |options|
 25     puts "Building #{options[:app]}"
 26   end
```

**Comment by yakimant** [comment]
Yes, some conflict around test. If I just rename to test1 - everything is fine.
I wrote here, because test should be quite famous lane name)

Code is not the same, because I wanted to run buildAndTest lane twice in case of app (for lib and app) and once in case of lib.

But anyway - thank you!

**Comment by ohwutup** [comment]
Going to close this issue for now as its been a while (since my birthday actually! :tada:) since there has been activity. Please feel free to reopen if necessary! :cake:
