### ISSUE TITLE
TypeError at the end of fastlane run on Travis

### ISSUE THREAD

**Issue by bgerstle** [fastlane/fastlane#792]
Seems to be while fastlane attempts to retrieve the changelog for the latest version, after its work is finished on an older version.  Works fine locally, but fails [on Travis](https://travis-ci.org/wikimedia/wikipedia-ios/builds/90796826#L2524):

```
#######################################################################
# fastlane 1.39.0 is available. You are on 1.38.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################
# Run `sudo gem cleanup` from time to time to speed up fastlane
#######################################################################
/Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:8:in `[]': no implicit conversion of String into Integer (TypeError)
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:8:in `block in show_changes'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:7:in `each'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:7:in `each_with_index'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:7:in `show_changes'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/update_checker.rb:63:in `show_update_message'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/update_checker.rb:46:in `show_update_status'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.38.0/bin/fastlane:162:in `ensure in <top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.38.0/bin/fastlane:162:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/fastlane:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by bgerstle** [comment]
[Seems to work](https://travis-ci.org/wikimedia/wikipedia-ios/builds/88928750#L2459) in 1.37

**Comment by KrauseFx** [comment]
Interesting, thanks :+1:

**Comment by bgerstle** [comment]
@KrauseFx unfortunately, this problem has [resurfaced](https://travis-ci.org/wikimedia/wikipedia-ios/builds/90365776#L2483) now that fastlane has progressed to 1.38 and we're still using 1.37.  I can take a quick look to see if there's a simple fix, any hints to where I should start?

**Comment by bgerstle** [comment]
just happened [again](https://travis-ci.org/wikimedia/wikipedia-ios/builds/90787028#L2484)

**Comment by bgerstle** [comment]
For now we're working around this by disabling update checks & changelog display in Travis.

**Comment by bgerstle** [comment]
@KrauseFx sorry, i realize now they link I originally posted was bad. I've updated it to a recently failing build (at least until it's restarted) and also copy/pasted the stack trace.

**Comment by KrauseFx** [comment]
@bgerstle At least `fastlane` shouldn't crash, it should silently *not* display a changelog, right?

**Comment by bgerstle** [comment]
It's silent now that I'm using the environment variables which cause it to
skip updates nor display the changelog.

**Comment by KrauseFx** [comment]
Okay cool :+1:
