### ISSUE TITLE
Update_Info_Plist Unexpected end of string while parsing

### ISSUE THREAD

**Issue by MaximusMcCann** [fastlane/fastlane#7929]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Even setting 

```
      newId = "com.test.test"
      newName = "TEST"
      update_info_plist(app_identifier: newId, display_name: newName)
```

```
[22:11:29]: -------------------------------
[22:11:29]: --- Step: update_info_plist ---
[22:11:29]: -------------------------------
+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios enterprise |
+------------------+----------------+
[22:11:29]: [!] Unexpected end of string while parsing
 #  -------------------------------------------
1>
    ^
 #  -------------------------------------------


+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | update_fastlane   | 8           |
| 2    | default_platform  | 0           |
| 3    | cocoapods         | 3           |
| 4    | git_branch        | 0           |
| 5    | git_branch        | 0           |
| 6    | git_branch        | 0           |
| 💥   | update_info_plist | 0           |
| 💥   | update_info_plist | 0           |
+------+-------------------+-------------+

[22:30:08]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Improve Beta Setup
   https://github.com/fastlane/fastlane/pull/1 [closed] 1 💬
   16 Dec 2014

➡️  Update_Info_Plist Unexpected end of string while parsing
   https://github.com/fastlane/fastlane/issues/7929 [open] 0 💬
   a minute ago

➡️  Deliver fails with "Unexpected Error" after uploading package to iTunes Connect
   https://github.com/fastlane/fastlane/issues/6455 [closed] 51 💬
   25 Oct 2016

and 2 more at: https://github.com/fastlane/fastlane/search?q=[!]%20Unexpected%20end%20of%20string%20while%20parsing%0A%20%23%20%20-------------------------------------------%0A1%3E%20%20%0A%20%20%20%20%5E%0A%20%23%20%20-------------------------------------------%0A&type=Issues&utf8=✓

🔗 You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/a/.rbenv/versions/2.3.3/bin/fastlane)
Nanaimo::Reader::ParseError: [!] [!] [!] Unexpected end of string while parsing
 #  -------------------------------------------
1>
    ^
 #  -------------------------------------------

 #  -------------------------------------------
1>
    ^
 #  -------------------------------------------

  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:129:in `parse_object'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:106:in `parse!'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/plist.rb:27:in `read_from_path'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/actions/update_info_plist.rb:37:in `run'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:239:in `block (2 levels) in execute_action'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:213:in `chdir'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:92:in `block (2 levels) in parsing_binding'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:63:in `block in execute'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:59:in `chdir'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:59:in `rescue in execute'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:44:in `execute'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
  /Users/a/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
  /Users/a/.rbenv/versions/2.3.3/bin/fastlane:22:in `load'
  /Users/a/.rbenv/versions/2.3.3/bin/fastlane:22:in `<top (required)>'

```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.test.test-test-test" # The bundle identifier of your app
apple_id "nothing@example.com" # Your Apple email address

team_id "aaaaaa"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

<details><summary><b>Loaded gems</b></summary>

| Gem                                   | Version      |
| ------------------------------------- | ------------ |
| did_you_mean                          | 1.0.0        |
| bundler                               | 1.13.7       |
| io-console                            | 0.4.5        |
| CFPropertyList                        | 2.3.4        |
| i18n                                  | 0.7.0        |
| json                                  | 1.8.6        |
| minitest                              | 5.10.1       |
| thread_safe                           | 0.3.5        |
| tzinfo                                | 1.2.2        |
| activesupport                         | 4.2.7.1      |
| public_suffix                         | 2.0.5        |
| addressable                           | 2.5.0        |
| rubyzip                               | 1.2.0        |
| apktools                              | 0.7.1        |
| aws-sigv4                             | 1.0.0        |
| jmespath                              | 1.3.1        |
| aws-sdk-core                          | 2.6.49       |
| aws-sdk-resources                     | 2.6.49       |
| aws-sdk                               | 2.6.49       |
| babosa                                | 1.0.2        |
| claide                                | 1.0.1        |
| fuzzy_match                           | 2.0.4        |
| nap                                   | 1.1.0        |
| cocoapods-core                        | 1.1.1        |
| cocoapods-deintegrate                 | 1.0.1        |
| cocoapods-downloader                  | 1.1.3        |
| cocoapods-plugins                     | 1.0.0        |
| cocoapods-search                      | 1.0.0        |
| cocoapods-stats                       | 1.0.0        |
| netrc                                 | 0.7.8        |
| cocoapods-trunk                       | 1.1.2        |
| cocoapods-try                         | 1.1.0        |
| colored                               | 1.2          |
| escape                                | 0.0.4        |
| fourflusher                           | 2.0.1        |
| gh_inspector                          | 1.0.3        |
| molinillo                             | 0.5.5        |
| nanaimo                               | 0.2.3        |
| xcodeproj                             | 1.4.2        |
| cocoapods                             | 1.1.1        |
| highline                              | 1.7.8        |
| commander                             | 4.4.3        |
| unf_ext                               | 0.0.7.2      |
| unf                                   | 0.1.4        |
| domain_name                           | 0.5.20161129 |
| dotenv                                | 2.1.2        |
| excon                                 | 0.54.0       |
| multipart-post                        | 2.0.0        |
| faraday                               | 0.11.0       |
| http-cookie                           | 1.0.3        |
| faraday-cookie_jar                    | 0.0.6        |
| faraday_middleware                    | 0.11.0       |
| fastimage                             | 2.0.1        |
| jwt                                   | 1.5.6        |
| little-plugger                        | 1.1.4        |
| multi_json                            | 1.12.1       |
| logging                               | 2.1.0        |
| memoist                               | 0.15.0       |
| os                                    | 0.9.6        |
| signet                                | 0.7.3        |
| googleauth                            | 0.5.1        |
| httpclient                            | 2.8.3        |
| hurley                                | 0.2          |
| mime-types-data                       | 3.2016.0521  |
| mime-types                            | 3.1          |
| uber                                  | 0.0.15       |
| representable                         | 2.3.0        |
| retriable                             | 2.1.0        |
| google-api-client                     | 0.9.20       |
| mini_magick                           | 4.5.1        |
| multi_xml                             | 0.6.0        |
| plist                                 | 3.2.0        |
| security                              | 0.1.3        |
| slack-notifier                        | 1.5.1        |
| terminal-notifier                     | 1.7.1        |
| unicode-display_width                 | 1.1.3        |
| terminal-table                        | 1.7.3        |
| word_wrap                             | 1.0.0        |
| rouge                                 | 1.11.1       |
| xcpretty                              | 0.2.4        |
| xcpretty-travis-formatter             | 0.0.4        |
| proxies                               | 0.2.1        |
| s3                                    | 0.3.25       |
</details>

*generated on:* **2017-01-19**
</details>

**Comment by MaximusMcCann** [comment]
Smells of a nanaimo issue :(

**Comment by MaximusMcCann** [comment]
Have also tried setting the `scheme` & `plist` path, but receive no `UI.user_error`s so :/

**Comment by MaximusMcCann** [comment]
SOLUTION.  Double check your Info.plist isn't corrupt!  Have 2 plist files, the one I was referencing was somehow blank.
