### ISSUE TITLE
fastlane action for pilot to distribute a previously uploaded binary

### ISSUE THREAD

**Issue by ceyhuno** [fastlane/fastlane#7957]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is there a fastlane action similar to `pilot distribute` that distributes a previously uploaded binary so I can use it in a lane?

**Comment by hjanuschka** [comment]
hey @ceyhuno i am not quite sure if there is a build in action for that.

but you can do it with spaceship (inside your fastfile 👍 )

```ruby
Spaceship::Tunes.login
app = Spaceship::Tunes::Application.find("my.app.id")
version = app.edit_version

# to submit latest build do it with this
use_build = version.candidate_builds.first

# for specific build_number use this.
use_build = version.candidate_builds.find(build_version: "BUILD_NR").first

# if you wan't to update changelog and stuff
#use_build.update_build_information!(whats_new:"Whats new", description: "Description", feedback_email: "email@host.com")

version.select_build(use_build)
version.save!

# now the select build is assigned to the edit_version
# for exact same behaviour as distribute

# you also have to this

uploaded_build.client.submit_testflight_build_for_review!(
  app_id: use_build.build_train.application.apple_id,
  train: use_build.build_train.version_string,
  build_number: use_build.build_version,
  platform: use_build.platform
)
uploaded_build.build_train.update_testing_status!(true, "external", use_build)
```


let me know if this helps you.

**Comment by ceyhuno** [comment]
I wrote it directly into a lane like this:
```ruby
lane :beta do
    Spaceship::Tunes.login
    app = Spaceship::Tunes::Application.find("my.app.id") #I replaced this id
    version = app.edit_version

    use_build = version.candidate_builds.first

    version.select_build(use_build)
    version.save!

    uploaded_build.client.submit_testflight_build_for_review!(
      app_id: use_build.build_train.application.apple_id,
      train: use_build.build_train.version_string,
      build_number: use_build.build_version,
      platform: use_build.platform
    )

    uploaded_build.build_train.update_testing_status!(true, "internal", use_build)
end
```

I got an error saying: 
```
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NameError: [!] uninitialized constant Fastlane::FastFile::Spaceship
  Fastfile:172:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

**Comment by hjanuschka** [comment]
Mea culpa! - you have to add `require "spaceship"` at the top of your fastfile.

**Comment by ceyhuno** [comment]
OK but now I got an error `NoMethodError: [!] undefined method 'application' for nil:NilClass`. Seems like the `use_build.build_train` is `nil`. What might be the reason?

**Comment by hjanuschka** [comment]
ok - thats sad, can you try this:


```ruby
lane :beta do
    Spaceship::Tunes.login
    app = Spaceship::Tunes::Application.find("my.app.id") #I replaced this id
    version = app.edit_version

    use_build = version.candidate_builds.first

    version.select_build(use_build)
    version.save!

    uploaded_build.client.submit_testflight_build_for_review!(
      app_id: use_build.apple_id,
      train: use_build.train_version,
      build_number: use_build.build_version,
      platform: use_build.platform
    )

    uploaded_build.build_train.update_testing_status!(true, "internal", use_build)
end
```

seems to be in that case we' dont have the build_train et-all

**Comment by ceyhuno** [comment]
`uploaded_build` is actually `use_build` right? so i tried like this `use_build.client.submit_testflight_build_for_review!(...`. But now I got an error about metadata like `
[English]: What to Test is required. [English]: Beta App Description is required. [English]: Marketing URLs are required. ....` etc.

Normally for an internal release iTunes Connect doesn't ask about such information and I tried now to release the build manually and it got released immediately without any errors.

**Comment by hjanuschka** [comment]
yeah upload_build was a typo.

strange - does it fail on `update_testing_status` or directly after `submit_testflight_build_for_review``


ohhh wait, you use "internal" - right? - then i think you don't have to `submit_testflight_build_for_review`


the build selection + `save!`  + `update_testing_status` should be enough for testflight only testing.

**Comment by ceyhuno** [comment]
Now it worked! Thank you @hjanuschka 👍 Here is the entire thing:

```
lane :beta do
    Spaceship::Tunes.login
    app = Spaceship::Tunes::Application.find("my.app.id") #I replaced this id
    version = app.edit_version

    use_build = version.candidate_builds.first

    version.select_build(use_build)
    version.save!

    train_version = use_build.train_version
    train = app.build_trains[train_version]
    
    train.update_testing_status!(true, "internal", use_build)
end
```

I ended up getting the `train` from the `app` because the `use_build.build_train` was `nil` like I said.

**Comment by hjanuschka** [comment]
@ceyhuno glad it worked, and thx for the final result as a reference! issue can be closed ?

**Comment by ceyhuno** [comment]
Yes 👍 thanks again!
