### ISSUE TITLE
The App Name you entered has already been used.

### ISSUE THREAD

**Issue by parleer** [fastlane/fastlane#8079]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to deliver a new version of an existing app. The app is already created in iTunes Connect. 

The error output is:
```
opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/tunes/tunes_client.rb:223:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	The App Name you entered has already been used. The App Name you entered has already been used.
```
But there's no mention of what name it's trying to use? Why isn't it matching to to my existing app and trying to deliver a new version?

##### Complete output when running fastlane, including the stack trace and command used

```
bundle exec fastlane deliver --force true --verbose
Successfully loaded Appfile at path '/Users/me/Developer/app/app-ios/fastlane/Appfile'
- apple_id: 'XXXX@gmail.com'
- team_id: 'XXXX'
- team_name: 'XXXX'
-------
INFO [2017-02-01 12:47:58.54]: Successfully loaded '/Users/me/Developer/app/app-ios/fastlane/Deliverfile' 📄
WARN [2017-02-01 12:47:58.54]: No values defined in './fastlane/Deliverfile'
INFO [2017-02-01 12:47:58.54]: Login to iTunes Connect (XXXX@gmail.com)
Looking for iTunes Connect Team with ID XXXX
INFO [2017-02-01 12:48:00.86]: Login successful

+-----------------------+--------------------------------+
|                 deliver 2.13.0 Summary                 |
+-----------------------+--------------------------------+
| app_identifier        | com.XXXX.XXXX                  |
| app_version           | 1.0                            |
| team_id               | XXXX                           |
| force                 | true                           |
| screenshots_path      | ./fastlane/screenshots         |
| metadata_path         | ./fastlane/metadata            |
| username              | XXXX@gmail.com                 |
| edit_live             | false                          |
| ipa                   | app.ipa                        |
| platform              | ios                            |
| skip_binary_upload    | false                          |
| skip_screenshots      | false                          |
| skip_metadata         | false                          |
| submit_for_review     | false                          |
| automatic_release     | false                          |
| dev_portal_team_id    | XXXX                           |
| dev_portal_team_name  | XXXX                           |
| overwrite_screenshots | false                          |
+-----------------------+--------------------------------+

INFO [2017-02-01 12:48:01.42]: Making sure the latest version on iTunes Connect matches '1.0' from the ipa file...
INFO [2017-02-01 12:48:02.44]: '1.0' is the latest version on iTunes Connect
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/en-US/description.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/en-US/keywords.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/en-US/release_notes.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/en-US/support_url.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/en-US/name.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/copyright.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/primary_category.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/secondary_category.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
INFO [2017-02-01 12:48:02.44]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
INFO [2017-02-01 12:48:03.19]: Activating language en-US...
INFO [2017-02-01 12:48:05.72]: Uploading metadata to iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	The App Name you entered has already been used. The App Name you entered has already been used.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09The%20App%20Name%20you%20entered%20has%20already%20been%20used.%20The%20App%20Name%20you%20entered%20has%20already%20been%20used.+repo:fastlane/fastlane
➡️  Unable to create an app on itunes connect via spaceship or produce.  Error: The App Name you entered has already been used 
   https://github.com/fastlane/fastlane/issues/5102 [closed] 10 💬
   4 weeks ago

➡️  Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/7274 [closed] 4 💬
   02 Dec 2016

➡️  Produce failing to create app in iTunesConnect
   https://github.com/fastlane/fastlane/issues/5728 [closed] 11 💬
   01 Dec 2016

and 2 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09The%20App%20Name%20you%20entered%20has%20already%20been%20used.%20The%20App%20Name%20you%20entered%20has%20already%20been%20used.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/tunes/tunes_client.rb:223:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	The App Name you entered has already been used. The App Name you entered has already been used.
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/tunes/tunes_client.rb:255:in `update_app_details!'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/tunes/app_details.rb:75:in `save!'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/deliver/lib/deliver/upload_metadata.rb:86:in `upload'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/deliver/lib/deliver/runner.rb:62:in `upload_metadata'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/deliver/lib/deliver/runner.rb:21:in `run'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/deliver/lib/deliver/commands_generator.rb:62:in `block (2 levels) in run'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/deliver/lib/deliver/commands_generator.rb:148:in `run'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane-2.13.0/bin/fastlane:15:in `<top (required)>'
	from /opt/local/bin/fastlane:23:in `load'
	from /opt/local/bin/fastlane:23:in `<main>'

```

### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/me/Developer/XXXX/XXXX-ios/fastlane/Appfile'
- apple_id: 'XXXX@gmail.com'
- team_id: 'XXXX'
- team_name: 'XXXX'
-------
INFO [2017-02-01 13:04:13.24]: Successfully loaded custom action '/Users/me/Developer/XXXX/XXXX-ios/fastlane/actions/app_name.rb'.
INFO [2017-02-01 13:04:13.24]: Successfully loaded custom action '/Users/me/Developer/XXXX/XXXX-ios/fastlane/actions/build_number_icon.rb'.
INFO [2017-02-01 13:04:13.24]: Successfully loaded custom action '/Users/me/Developer/XXXX/XXXX-ios/fastlane/actions/color_icon.rb'.
WARN [2017-02-01 13:04:13.25]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2017-02-01 13:04:14.18]: Checking if there are any plugins that should be loaded...
```
</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.2.6                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.11.0                          |
| Installation Source | /opt/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | /opt/local/lib                              |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

</details>

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane


# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.63.0"

default_platform :ios


platform :ios do


  before_all do
    # Environemnt variables are set using gem dotenv and .env.default. If multiple environments are
    # needed, you can run fastlane with the --env environment_name to load .env.environment_name 
    # instead of .env.default.

    # In addition to the .env.* method of loading environment variables, we also load a local 'keys'
    # file, if it exists. This is a standard ruby file and can be used to keep passwords outside of 
    # the git repo. See fastlane/keys.template for an example.
    load_keys
  end

  # After all steps have completed successfully, run this
  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    if ENV["SLACK_URL"]
      slack(
        message: "lane executed successfully",
        success: true,
        default_payloads: [:test_result, :git_branch]
      )
    else
      notify("Lane #{lane} completed successfully!")  
    end
    #clean_build_artifacts
  end

  # If there was an error, run this
  error do |lane, exception|
    if ENV["SLACK_URL"]
      slack(
        message: exception.to_s,
        success: false
      )
    else 
      notify("Lane #{lane} failed to complete.")      
    end
    #clean_build_artifacts
  end


  desc "Install pod dependencies"
  lane :install_pods do
    cocoapods
  end


  # https://github.com/FixIssue/FixCode
  # Xcode 8+ no longer loads unsigned plugins; therefore this project is deprecated. 
  #/*
  # # Run this lane on your development machine once
  # desc "Installs FixCode which disables the \"Fix Issue\" button in Xcode"
  # lane :xcode do
  #   install_xcode_plugin(
  #     url: "https://github.com/fastlane/FixCode/releases/download/0.2.0/FixCode.xcplugin.zip"
  #   )
  # end
  #*/

  #### Apple Member Center ####

  desc "Produces all used App IDs and provision services"
  lane :prod do
    produce(app_identifier: 'com.XXXX.XXXX.debug', app_name: 'XXXX Debug', skip_itc: true)
    produce(app_identifier: 'com.XXXX.XXXX.alpha', app_name: 'XXXX Alpha', skip_itc: true)
    produce(app_identifier: 'com.XXXX.XXXX.beta', app_name: 'XXXX Beta', skip_itc: true)
	produce(app_identifier: 'com.XXXX.XXXX', app_name: 'XXXX', skip_itc: true)
    sh "produce group -g group.com.XXXX.XXXX"
    sh "produce enable_services -a com.XXXX.XXXX --app-group"
    sh "produce associate_group -a com.XXXX.XXXX group.com.XXXX.XXXX"
    sh "produce enable_services -a com.XXXX.XXXX.debug --app-group"
    sh "produce associate_group -a com.XXXX.XXXX.debug group.com.XXXX.XXXX"
    sh "produce enable_services -a com.XXXX.XXXX.alpha --app-group"
    sh "produce associate_group -a com.XXXX.XXXX.alpha group.com.XXXX.XXXX"
    sh "produce enable_services -a com.XXXX.XXXX.beta --app-group"
    sh "produce associate_group -a com.XXXX.XXXX.beta group.com.XXXX.XXXX"
  end


  # Run this lane on your development machine once.
  desc "Fetches certificates and provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    match(app_identifier: "com.XXXX.XXXX.debug", type: "development")
    match(app_identifier: "com.XXXX.XXXX.alpha", type: "adhoc")
    match(app_identifier: "com.XXXX.XXXX.beta", type: "adhoc")
    match(app_identifier: "com.XXXX.XXXX", type: "appstore")
  end

  desc "Runs all the tests"
  lane :test do
    return if test_disabled?
    scan
  end

  desc "Create new screenshots for the App Store in all languages and device types; additionally, this will add device frames around the screenshots and add the correct titles"
  lane :screenshots do
    match(app_identifier: "com.XXXX.XXXX", type: "development")
    snapshot(reinstall_app: true)
    frameit(white: true, path: './fastlane/screenshots')
  end


  desc "Uploads metadata only - no ipa file will be uploaded - You'll get a summary of the collected metadata before it's uploaded"
  lane :upload_metadata do
    deliver(metadata_only: true)
  end


  private_lane :build_app do |options|

    # This part is done only when the app is not for the "production" environment
    if not options[:release]
      # Modulate the color of the icons
      color_icon(
        modulation: "#{options[:modulation]}"
      )
      # Add the build number to the icon
      build_number_icon
    end

    # Update the app name
    app_name(
      plist_path: "#{options[:project_name]}/Info.plist",
      app_name: options[:app_name]
    )

    # Update the app identifier
    update_app_identifier(
      xcodeproj: "#{options[:project_name]}.xcodeproj",
      plist_path: "#{options[:project_name]}/Info.plist",
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    )

    # Update app group identifiers
    # update_app_group_identifiers(
    #   entitlements_file: "#{options[:project_name]}/XXXX.entitlements",
    #   app_group_identifiers: ["group.com.XXXX.XXXX#{options[:app_identifier_suffix]}"]
    # )

    # Install the certificate and provisioning profiles
    match(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      force_for_new_devices: true, 
      type: options[:match_type]
    )
    
    # Version bump
    increment_build_number(
      build_number: options[:build_number],
      xcodeproj: "#{options[:project_name]}.xcodeproj"
    )

    # Build the app
    gym(
      scheme: "#{options[:scheme]}",
      configuration: options[:configuration],
      #provisioning_profile_path: options[:profile],
      codesigning_identity: options[:codesigning_identity],
      export_method: options[:export_method],
    )

  end

  # Publish to Testflight
  private_lane :publish_testflight do |options|

    # Generate a changelog with GIT since the last successful build in Jenkins
    changelog = sh("git log --graph --pretty=format:'%h -%d %s <%an>' --abbrev-commit #{ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || 'HEAD^^^^^'}..HEAD")

    # Send the app to Testflight
    pilot(
      changelog: "#{changelog.to_s}",
      skip_submission: false,
      distribute_external: true, 
      beta_app_feedback_email: "support@XXXX.com",
      beta_app_description: "This is the beta release of the XXXX iOS App",
    )
  end

  # Publish to Crashlytics
  private_lane :publish_fabric do |options|

    changelog = options[:changelog]
    if changelog.to_s == ''
      # Generate a changelog with GIT since the last successful build in Jenkins
      changelog = sh("git log --graph --pretty=format:'%h -%d %s <%an>' --abbrev-commit #{ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || 'HEAD^^^^^'}..HEAD")
    end
    # Send the app to Crashlytics 
    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      notes: "#{changelog.to_s}",
      groups: "#{options[:groups]}",
      notifications: true,
      debug: options[:debug]
    )
  end


  # Publish to the AppStore
  private_lane :publish_appstore do |options|
    deliver(force: true)
  end


  desc "Build and publish an Alpha version to Fabric."
  lane :alpha_fabric do
    build_app(
      release:false,
      modulation:66.6,
      app_name:"XXXX α",
      app_identifier_suffix:".alpha",
      match_type:"adhoc",
      configuration:"Alpha",
      codesigning_identity:"iPhone Distribution: XXXX",
      export_method:"ad-hoc",
      project_name:"XXXX",
      scheme:"XXXX",
      build_number: ENV["BUILD_NUMBER"]
    )
    publish_fabric(
      debug:true, 
      groups:"alphagroup",
    )
  end

  desc "Build and publish the Beta version to Fabric"
  lane :beta_fabric do
    build_app(
      release:false,
      modulation:166.6,
      app_name:"XXXX β",
      app_identifier_suffix:".beta",
      match_type:"adhoc",
      configuration:"Beta",
      codesigning_identity:"iPhone Distribution: XXXX",
      export_method:"ad-hoc",
      project_name:"XXXX",
      scheme:"XXXX",
      build_number: ENV["BUILD_NUMBER"]
    )
    publish_fabric(
      debug:true,
      groups:"betagroup",
      changelog: changelog_from_git_commits(commits_count: 1, pretty: '%h - %d %s')
    )
  end

  desc "Build and publish the Release version to the AppStore"
  lane :release_appstore do
    build_app(
      release:true,
      app_name:"XXXX",
      app_identifier_suffix:"",
      match_type:"appstore",
      configuration:"Release",
      codesigning_identity:"iPhone Distribution: XXXX",
      export_method:"app-store",
      project_name:"XXXX",
      scheme:"XXXX Release",
      build_number: ENV["BUILD_NUMBER"]
    )
    publish_fabric(
      debug:false, 
      groups:"releasegroup"
    )
    publish_appstore
  end

end

def compare_url
  last_bump_hash = sh("cd ../;git log --pretty=format:'%s %h' | grep -i '^version bump [0-9]\\{12\\}\\b' | awk '{print $NF}' | head -n1").strip
  current_hash = sh("git rev-parse HEAD").strip
  "http://gitlab.XXXX.com/XXXX/XXXX-ios/compare?from=#{last_bump_hash}&to=#{current_hash}"
end

def change_log_since_last_tag
  # http://git-scm.com/docs/pretty-formats
  # <short hash> <commit title>
  return changelog_from_git_commits(pretty: '%h %s')
end

def version_string(version_number, build_number)
  "#{version_number} (#{build_number})"
end

def tag_name(build_type, version_number, build_number)
  "#{build_type}/#{version_number}/#{build_number}"
end

def load_keys
  begin
    import("keys")
  rescue => exception
    UI.important("fastlane/keys file not found. To use this Fastfile, copy fastlane/keys.template into fastlane/keys and fill in the values")
    #raise exception
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md

apple_id "XXXX@gmail.com"
team_id "XXXX"  # Developer Portal Team ID
team_name "XXXX"
for_platform :ios do
	app_identifier "com.XXXX.XXXX" 
	for_lane :alpha_fabric do
	  app_identifier "com.XXXX.XXXX.alpha"
	end
	for_lane :beta_fabric do
	  app_identifier "com.XXXX.XXXX.beta"
	end
	for_lane :release_appstore do
	  app_identifier "com.XXXX.XXXX"
	end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.13.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.5        |
| ruby-macho                | 0.2.6        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.2.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

**Comment by parleer** [comment]
Delivering the ipa via Application Loader worked just fine. Not sure why fastlane deliver isn't working.

**Comment by hjanuschka** [comment]
@parleer application loader does not update metadata, fastlane/deliver does. 
can you check your `name.txt` inside your metadata folder (in each language) - to see if it might have changed to a name, that is already taken.

alternatively you could download the current metadata, to ensure you are in sync with your store entry.


`fastlane deliver download_metadata`

> please backup all stuff, as it will overwrite things in fastlane/metadata

**Comment by parleer** [comment]
@hjanuschka that worked...almost...now getting the following Transporter Error, but it's no longer complaining about the app name:

```

[15:23:13]: Making sure the latest version on iTunes Connect matches '1.0' from the ipa file...
[15:23:14]: '1.0' is the latest version on iTunes Connect
[15:23:14]: Loading './fastlane/metadata/en-US/description.txt'...
[15:23:14]: Loading './fastlane/metadata/en-US/keywords.txt'...
[15:23:14]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[15:23:14]: Loading './fastlane/metadata/en-US/support_url.txt'...
[15:23:14]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[15:23:14]: Loading './fastlane/metadata/en-US/name.txt'...
[15:23:14]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[15:23:14]: Loading './fastlane/metadata/copyright.txt'...
[15:23:14]: Loading './fastlane/metadata/primary_category.txt'...
[15:23:14]: Loading './fastlane/metadata/secondary_category.txt'...
[15:23:14]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[15:23:14]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[15:23:14]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[15:23:14]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[15:23:15]: Activating language en-US...
[15:23:18]: Uploading metadata to iTunes Connect
[15:23:20]: Successfully uploaded set of metadata to iTunes Connect
[15:23:21]: Starting with the upload of screenshots...
[15:23:21]: Successfully uploaded screenshots to iTunes Connect
[15:23:23]: Uploading binary to iTunes Connect
[15:23:23]: Going to upload updated app to iTunes Connect
[15:23:23]: This might take a few minutes. Please don't interrupt the script.
[15:24:40]: [Transporter Error Output]: The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
[15:25:24]: [Transporter Error Output]: The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
[15:26:12]: [Transporter Error Output]: The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
[15:27:14]: [Transporter Error Output]: The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
[15:28:28]: [Transporter Error Output]: The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
[15:29:42]: [Transporter Error Output]: An exception has occurred: Warning: The same packet was resent too many times without acknowledgement.
[15:29:42]: [Transporter Error Output]: An exception has occurred: Warning: The same packet was resent too many times without acknowledgement.
[15:29:42]: [Transporter Error Output]: The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
[15:29:42]: [Transporter Error Output]: The max number of retries was performed. The package will not be uploaded.
[15:29:43]: Transporter transfer failed.
[15:29:43]: 
[15:29:43]: The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
An exception has occurred: Warning: The same packet was resent too many times without acknowledgement.
An exception has occurred: Warning: The same packet was resent too many times without acknowledgement.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The max number of retries was performed. The package will not be uploaded.
[15:29:43]: The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
An exception has occurred: Warning: The same packet was resent too many times without acknowledgement.
An exception has occurred: Warning: The same packet was resent too many times without acknowledgement.
The file, 9c6ad7a314053838fda15665f237b04f.ipa, did not complete its upload.
The max number of retries was performed. The package will not be uploaded.
\nThe max number of retries was performed. The package will not be uploaded.d.s without acknowledgement.ete its upload.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

I seem to remember dealing with this Transporter error on the last app I created, but can't remember how to resolve it; I think it may have just went away on it's own... strange that publishing to Crashlytics never has these type of transport issues...

**Comment by KrauseFx** [comment]
This looks like a different error, can you submit a separate issue for this? Are you behind a proxy?

**Comment by parleer** [comment]
I'll mark this as closed and open another issue if the Transporter error continues.
