### ISSUE TITLE
Produce fails with SyntaxError 

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#8092]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Suddenly (right after upgrading to 2.14.0) produce starts failing with error with a stacktrace below.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```ruby
[22:20:36]: ---------------------
[22:20:36]: --- Step: produce ---
[22:20:36]: ---------------------
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios auto |
| VERSION_NUMBER   | 1.0.1705 |
| BUILD_NUMBER     | 1.0.1705 |
+------------------+----------+
+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | git_branch                                                    | 0           |
| 3    | awk -F '=' '/PRODUCT_BUNDLE_IDENTIFIER/ {print $2; exit}' ../ | 0           |
| 4    | last_git_commit                                               | 0           |
| 5    | sed -i '' "s#\(Pods\.framework in Frameworks \*/ = {isa = PBX | 0           |
| 6    | Switch to ios beta lane                                       | 0           |
| 7    | Switch to ios build lane                                      | 0           |
| 8    | increment_version_number                                      | 5           |
| 9    | increment_build_number                                        | 0           |
| 10   | produce                                                       | 0           |
+------+---------------------------------------------------------------+-------------+
[22:20:36]: fastlane finished with errors
/Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/spaceship/lib/spaceship/tunes/tunes.rb:8:in `require': /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1056: syntax error, unexpected ',' (SyntaxError)
...l, purchase_id: nil, currency:, tier:)
...                               ^
/Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1431: syntax error, unexpected keyword_end, expecting end-of-input
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/spaceship/lib/spaceship/tunes/tunes.rb:8:in `<top (required)>'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/spaceship/lib/spaceship.rb:10:in `require'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/spaceship/lib/spaceship.rb:10:in `<top (required)>'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/produce/lib/produce/developer_center.rb:1:in `require'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/produce/lib/produce/developer_center.rb:1:in `<top (required)>'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/produce/lib/produce.rb:4:in `require'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/produce/lib/produce.rb:4:in `<top (required)>'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/actions/produce.rb:38:in `require'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/actions/produce.rb:38:in `available_options'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/configuration_helper.rb:4:in `parse'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:223:in `block (2 levels) in execute_action'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:32:in `block (2 levels) in parsing_binding'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:188:in `try_switch_to_lane'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:143:in `trigger_action_by_name'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:74:in `block (2 levels) in parsing_binding'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:188:in `try_switch_to_lane'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:143:in `trigger_action_by_name'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:95:in `block (2 levels) in parsing_binding'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/travis/build/<redacted>/<redacted>/vendor/bundle/ruby/2.0.0/gems/fastlane-2.14.0/bin/fastlane:15:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/fastlane:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
The command "./build.sh" exited with 1.
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```ruby
<details><summary>  fastlane environment  </summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.0.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.0                          |
| Installation Source | ~/.rvm/gems/ruby-2.0.0-p648/bin/fastlane    |
| Host                | Mac OS X 10.11.6 (15G1004)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.0.0-p648/lib           |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 |   |
| LC_ALL   | en_US.UTF-8 |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.0  |   Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**



<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.2       |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-02-02**
```

**Comment by andyh2** [comment]
Issue is caused by this PR: https://github.com/fastlane/fastlane/pull/7834

**Comment by Sega-Zero** [comment]
btw, when trying to call fastlane with `--capture_output`, I get an error:
> INFO [2017-02-02 23:02:29.40]: -----------------------------
> INFO [2017-02-02 23:02:29.40]: --- Step: last_git_commit ---
> INFO [2017-02-02 23:02:29.40]: -----------------------------
> ERROR [2017-02-02 23:02:29.40]: You passed invalid parameters to 'last_git_commit'.
> ERROR [2017-02-02 23:02:29.40]: Check out the error below and available options by running `fastlane action last_git_commit`
> 
> Looking for related GitHub issues on fastlane/fastlane...
> Search query: undefined method `each' for nil
> 
> URL: https://api.github.com/search/issues?q=undefined%20method%20%60each'%20for%20nil+repo:fastlane/fastlane
> ➡️  [!] Undefined method `description' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/7686 [closed] 9 
   4 weeks ago
> 
> ➡️  undefined method `<<' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/6731 [closed] 7 
   a week ago
> 
> ➡️  gym fails with undefined method `each_with_object' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/6834 [closed] 4 
   a day ago
> 
> and 71 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60each'%20for%20nil&type=Issues&utf8=✓

Should I create a separate issue for that?

**Comment by KrauseFx** [comment]
Thanks for the report, looking into this right now 🚀

**Comment by KrauseFx** [comment]
Fix is about to go live, sorry for introducing this

**Comment by KrauseFx** [comment]
The new release is live [2.14.1](https://github.com/fastlane/fastlane/releases/tag/2.14.1), please update to the most recent version and let me know if that fixes the problem.

Again, I'm super sorry this happened, we'll add more tests to cover this area as well 👍
