### ISSUE TITLE
You are not permitted to create provisioning profiles for team.

### ISSUE THREAD

**Issue by dzan** [fastlane/fastlane#8183]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to use match to do the provisioning. When I remove any previous key for `applematch@company.com` from my keychain and dev portal and try again I end up with this:

> You are not permitted to create provisioning profiles for team.  Please contact one of your team admins, who can create a profile on your behalf.

```
INFO [2017-02-09 09:14:01.53]: Successfully loaded '/Users/user/Projects/oursoftware/tests/ObjC/sampleapp/fastlane/Matchfile' 📄

+----------+------------------------------------------------+
|        Detected Values from './fastlane/Matchfile'        |
+----------+------------------------------------------------+
| git_url  | git@bitbucket.org:company/certificates.git |
| type     | development                                    |
| username | applematch@company.com                     |
+----------+------------------------------------------------+

DEBUG [2017-02-09 09:14:01.53]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'

+-----------------------+------------------------------------------------+
|                        Summary for match 2.14.2                        |
+-----------------------+------------------------------------------------+
| verbose               | development                                    |
| git_url               | git@bitbucket.org:company/certificates.git |
| type                  | development                                    |
| username              | applematch@company.com                     |
| git_branch            | master                                         |
| app_identifier        | com.oursoftware.objectivec.sampleapp          |
| keychain_name         | login.keychain                                 |
| readonly              | false                                          |
| team_id               | XEM832IQPV                                     |
| force                 | false                                          |
| skip_confirmation     | false                                          |
| shallow_clone         | false                                          |
| force_for_new_devices | false                                          |
| skip_docs             | false                                          |
| platform              | ios                                            |
+-----------------------+------------------------------------------------+

INFO [2017-02-09 09:14:01.54]: Cloning remote git repo...
INFO [2017-02-09 09:14:01.54]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@bitbucket.org:company/certificates.git' '/var/folders/l4/k30c_qr12vn5wbc90b0m6xcr0000gn/T/d20170209-48940-gfad06'
INFO [2017-02-09 09:14:01.55]: ▸ Cloning into '/var/folders/l4/k30c_qr12vn5wbc90b0m6xcr0000gn/T/d20170209-48940-gfad06'...
INFO [2017-02-09 09:14:07.46]: ▸ remote: Counting objects: 75, done.
INFO [2017-02-09 09:14:07.57]: ▸ remote: Compressing objects: 100% (71/71), done.
INFO [2017-02-09 09:14:07.88]: ▸ remote: Total 75 (delta 11), reused 0 (delta 0)
INFO [2017-02-09 09:14:07.88]: ▸ Receiving objects: 100% (75/75), 149.60 KiB | 0 bytes/s, done.
INFO [2017-02-09 09:14:07.88]: ▸ Resolving deltas: 100% (11/11), done.
INFO [2017-02-09 09:14:07.89]: ▸ Checking connectivity... done.
INFO [2017-02-09 09:14:07.89]: 🔓  Successfully decrypted certificates repo
INFO [2017-02-09 09:14:07.93]: Verifying that the certificate and profile are still valid on the Dev Portal...
WARN [2017-02-09 09:14:12.61]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now
Successfully loaded Appfile at path '/Users/user/Projects/oursoftware/tests/ObjC/sampleapp/fastlane/Appfile'
- app_identifier: 'com.oursoftware.objectivec.sampleapp'
- apple_id: 'applematch@company.com'
- team_id: 'XEM832IQPV'
-------

+---------------+----------------------------------------------+
|                   Summary for cert 2.14.2                    |
+---------------+----------------------------------------------+
| development   | true                                         |
| force         | true                                         |
| username      | applematch@company.com                   |
| team_id       | XEM832IQPV                                   |
| keychain_path | /Users/user/Library/Keychains/login.keychain |
| platform      | ios                                          |
+---------------+----------------------------------------------+

INFO [2017-02-09 09:14:12.63]: Starting login with user 'applematch@company.com'
INFO [2017-02-09 09:14:15.81]: Successfully logged in
INFO [2017-02-09 09:14:18.91]: $ security import /var/folders/l4/k30c_qr12vn5wbc90b0m6xcr0000gn/T/d20170209-48940-gfad06/certs/development/P4E6934A9W.p12 -k '/Users/user/Library/Keychains/login.keychain' -P '' -T /usr/bin/codesign -T /usr/bin/security
INFO [2017-02-09 09:14:19.01]: ▸ 1 key imported.
INFO [2017-02-09 09:14:19.03]: $ security import /var/folders/l4/k30c_qr12vn5wbc90b0m6xcr0000gn/T/d20170209-48940-gfad06/certs/development/P4E6934A9W.cer -k '/Users/user/Library/Keychains/login.keychain' -P '' -T /usr/bin/codesign -T /usr/bin/security
INFO [2017-02-09 09:14:19.08]: ▸ 1 certificate imported.
INFO [2017-02-09 09:14:19.09]: Successfully generated P4E6934A9W which was imported to the local machine.
INFO [2017-02-09 09:14:19.09]: $ security list-keychains -d user
INFO [2017-02-09 09:14:19.11]: ▸     "/Users/user/Library/Keychains/login.keychain"
INFO [2017-02-09 09:14:19.11]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/user/Library/Keychains/login.keychain
INFO [2017-02-09 09:14:19.15]: ▸ keychain: "/Users/user/Library/Keychains/login.keychain"
INFO [2017-02-09 09:14:19.15]: ▸ version: 256
INFO [2017-02-09 09:14:19.15]: ▸ class: 0x80001000
INFO [2017-02-09 09:14:19.15]: ▸ attributes:
INFO [2017-02-09 09:14:19.15]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-02-09 09:14:19.15]: ▸     "cenc"<uint32>=value
INFO [2017-02-09 09:14:19.15]: ▸     "ctyp"<uint32>=value
INFO [2017-02-09 09:14:19.15]: ▸     "hpky"<blob>=value
INFO [2017-02-09 09:14:19.15]: ▸     "issu"<blob>=value
INFO [2017-02-09 09:14:19.15]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-02-09 09:14:19.15]: ▸     "skid"<blob>=value
INFO [2017-02-09 09:14:19.15]: ▸     "snbr"<blob>=value
INFO [2017-02-09 09:14:19.15]: ▸     "subj"<blob>=value
INFO [2017-02-09 09:14:19.55]: Verifying the certificate is properly installed locally...
INFO [2017-02-09 09:14:19.55]: Successfully installed certificate P4E6934A9W

+-------------------------------------+---------------------------------------------------------+
|                                    Summary for sigh 2.14.2                                    |
+-------------------------------------+---------------------------------------------------------+
| app_identifier                      | com.oursoftware.objectivec.sampleapp                   |
| username                            | applematch@company.com                              |
| force                               | true                                                    |
| cert_id                             | P4E6934A9W                                              |
| provisioning_name                   | match Development com.oursoftware.objectivec.sampleapp |
| ignore_profiles_with_different_name | true                                                    |
| team_id                             | XEM832IQPV                                              |
| platform                            | ios                                                     |
| development                         | true                                                    |
| adhoc                               | false                                                   |
| skip_install                        | false                                                   |
| skip_fetch_profiles                 | false                                                   |
| skip_certificate_verification       | false                                                   |
+-------------------------------------+---------------------------------------------------------+

INFO [2017-02-09 09:14:20.34]: Starting login with user 'applematch@company.com'
INFO [2017-02-09 09:14:23.38]: Successfully logged in
INFO [2017-02-09 09:14:23.38]: Fetching profiles...
WARN [2017-02-09 09:14:25.93]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
INFO [2017-02-09 09:14:28.36]: $ security list-keychains -d user
INFO [2017-02-09 09:14:28.37]: ▸     "/Users/user/Library/Keychains/login.keychain"
INFO [2017-02-09 09:14:28.37]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/user/Library/Keychains/login.keychain
INFO [2017-02-09 09:14:28.39]: ▸ keychain: "/Users/user/Library/Keychains/login.keychain"
INFO [2017-02-09 09:14:28.39]: ▸ version: 256
INFO [2017-02-09 09:14:28.39]: ▸ class: 0x80001000
INFO [2017-02-09 09:14:28.39]: ▸ attributes:
INFO [2017-02-09 09:14:28.39]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-02-09 09:14:28.39]: ▸     "cenc"<uint32>=value
INFO [2017-02-09 09:14:28.39]: ▸     "ctyp"<uint32>=value
INFO [2017-02-09 09:14:28.39]: ▸     "hpky"<blob>=value
INFO [2017-02-09 09:14:28.39]: ▸     "issu"<blob>=value
INFO [2017-02-09 09:14:28.39]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-02-09 09:14:28.39]: ▸     "skid"<blob>=value
INFO [2017-02-09 09:14:28.39]: ▸     "snbr"<blob>=value
INFO [2017-02-09 09:14:28.39]: ▸     "subj"<blob>=value
WARN [2017-02-09 09:14:30.21]: Creating new provisioning profile for 'com.oursoftware.objectivec.sampleapp' with name 'match Development com.oursoftware.objectivec.sampleapp for ios platform'
ERROR [2017-02-09 09:14:33.89]: An error occured while verifying your certificates and profiles with the Apple Developer Portal.
ERROR [2017-02-09 09:14:33.89]: If you already have your certificates stored in git, you can run `match` in readonly mode
ERROR [2017-02-09 09:14:33.89]: to just install the certificates and profiles without accessing the Dev Portal.
ERROR [2017-02-09 09:14:33.89]: To do so, just pass `readonly: true` to your match call.
INFO [2017-02-09 09:14:33.89]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...
Search query: Apple provided the following error info:
        You are not permitted to create provisioning profiles for team.  Please contact one of your team admins, who can create a profile on your behalf.

URL: https://api.github.com/search/issues?q=Apple%20provided%20the%20following%20error%20info:%0A%09You%20are%20not%20permitted%20to%20create%20provisioning%20profiles%20for%20team.%20%20Please%20contact%20one%20of%20your%20team%20admins,%20who%20can%20create%20a%20profile%20on%20your%20behalf.+repo:fastlane/fastlane
➡️  [Match] Reusing manually generated certificates and provisioning
   https://github.com/fastlane/fastlane/issues/7133 [closed] 4 💬
   a week ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/spaceship/lib/spaceship/client.rb:450:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
        You are not permitted to create provisioning profiles for team.  Please contact one of your team admins, who can create a profile on your behalf.
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/spaceship/lib/spaceship/portal/portal_client.rb:454:in `create_provisioning_profile!'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:245:in `block in create!'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/spaceship/lib/spaceship/client.rb:386:in `with_retry'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:244:in `create!'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/sigh/lib/sigh/runner.rb:131:in `create_profile!'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/sigh/lib/sigh/runner.rb:35:in `run'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/sigh/lib/sigh/manager.rb:7:in `start'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/generator.rb:68:in `generate_provisioning_profile'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/runner.rb:130:in `fetch_provisioning_profile'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/runner.rb:40:in `block (2 levels) in run'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/runner.rb:39:in `loop'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/runner.rb:39:in `block in run'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/runner.rb:38:in `each'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/runner.rb:38:in `run'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/commands_generator.rb:52:in `block (3 levels) in run'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/command.rb:153:in `run'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/runner.rb:446:in `run_active_command'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/delegates.rb:15:in `run!'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/commands_generator.rb:118:in `run'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/match/lib/match/commands_generator.rb:12:in `start'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/bin/fastlane:15:in `<top (required)>'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/bin/fastlane:22:in `load'
        from /Users/user/.fastlane/bin/fastlane_lib/bundle/bin/fastlane:22:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.11.6                                          |
| Ruby                | 2.2.4                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.9.2                                |
| Installation Source | ~/.fastlane/bin/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G31)                         |
| Ruby Lib Dir        | ~/.fastlane/bin/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained        | true                                             |
| Is homebrew         | false                                            |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version       | 8.2.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.3.0"

default_platform :ios

platform :ios do
  before_all do

...

  lane :build do

    # We need a profile to be available.
    #cert(
    #  development: true,
    #  username: ENV['IXG_APPLE_USER'],
    #)

    #sigh(
    #  development: true,
    #  username: ENV['IXG_APPLE_USER'],
    #)

    match(
      git_url: "git@bitbucket.org:company/certificates.git",
      type: "development",
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    )

    # Build.
    gym(
      clean: true,
      scheme: ENV['IXG_SCHEME'],
      include_bitcode: true,
      export_method: "development",
      buildlog_path: ".",
      disable_xcpretty: true,
    )

  end
...
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.oursoftware.objectivec.sampleapp" # The bundle identifier of your app
apple_id "applematch@company.com" # Your Apple email address

team_id "XEM832IQPV"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-02-09**
</details>

**Comment by ohayon** [comment]
Hey @dzan 👋, could you explain a little more about the problem? What do you mean by "a previous key"? 🐙
