### ISSUE TITLE
Supply action throws an error when uploading it with the mapping file

### ISSUE THREAD

**Issue by BobString** [fastlane/fastlane#8187]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When using the supply action with a mapping file, it throws a NoMethodError in 
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/supply/lib/supply/client.rb:223: undefined method upload_edit_deobfuscationfile 

The method in question:
```
supply(
  track: "alpha",
  json_key: ENV["GOOGLE_JSON_FILE"],
  apk: "#{apkOutPutPath}",
  mapping: mappingRoute + "release/mapping.txt",
  skip_upload_images: true,
  skip_upload_screenshots: true,
  skip_upload_metadata: skipMetadata,
  validate_only: true
)
```
Changing validate_only to false still gives the same error. When the mapping line is removed the method doesn't throws any error.

##### Complete output when running fastlane, including the stack trace and command used
```
+-------------------------+------------------------------------------------------------------------+
|                                    Summary for supply 2.14.2                                     |
+-------------------------+------------------------------------------------------------------------+
| track                   | alpha                                                                  |
| json_key                | /correctPath/to/key |
| apk                     | /correctPath/to/apk  |
| mapping                 | /correctPath/to/mapping |
| skip_upload_images      | true                                                                   |
| skip_upload_screenshots | true                                                                   |
| skip_upload_metadata    | false                                                                  |
| validate_only           | false                                                                   |
| package_name            | com.pacakge.app                                             |
| rollout                 | 0.1                                                                    |
| metadata_path           | ./fastlane/metadata/android                                            |
| skip_upload_apk         | false                                                                  |
+-------------------------+------------------------------------------------------------------------+


undefined method `upload_edit_deobfuscationfile' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007f8d699f8690>
Did you mean?  upload_expansion_file

/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/supply/lib/supply/client.rb:223:in `block in upload_mapping': [!] undefined method `upload_edit_deobfuscationfile' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007f8d699f8690> (NoMethodError)
Did you mean?  upload_expansion_file
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/supply/lib/supply/client.rb:360:in `call_google_api'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/supply/lib/supply/client.rb:222:in `upload_mapping'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/supply/lib/supply/uploader.rb:121:in `block in upload_binaries'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/supply/lib/supply/uploader.rb:119:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/supply/lib/supply/uploader.rb:119:in `upload_binaries'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/supply/lib/supply/uploader.rb:26:in `perform_upload'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/actions/supply.rb:19:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:239:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:205:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

It seems with only an android aplication the fastlane env doesn't produce a succesful output:

```
[!] Error detecting currently used Xcode installation, please ensure that you have Xcode installed and set it using `sudo xcode-select -s [path]`
```

**Comment by BobString** [comment]
Here you go:
```
[14:11:17]: Generating fastlane environment output, this might take a few seconds...
sh: /Library/Developer/CommandLineTools//usr/bin/xcodebuild: No such file or directory
[14:11:17]: undefined method `split' for nil:NilClass

[!] Error detecting currently used Xcode installation, please ensure that you have Xcode installed and set it using `sudo xcode-select -s [path]`
```

**Comment by tmtrademarked** [comment]
This looks similar to an error I thought I fixed a while ago (https://github.com/fastlane/fastlane/pull/7763). What version of Fastlane are you using? I think this should be fixed in 2.6.0+

Check the version of the google-api-client gem you have installed. You need at least 0.9.20, which the gemfspec for Supply should be installing. (But maybe you ended up with an old version somehow?)

**Comment by BobString** [comment]
Yeah you were right! The fastlane version was 2.14.2 but the google-api-client gem is 0.9.11. Updating everything now, could it be because I was using "gem update fastlane" specifically?

Thanks for your help!

**Comment by tmtrademarked** [comment]
Hmm - that's odd. I'm not familiar enough with ruby to understand exactly why that would fail to update. :-/ Glad it's working for you, at least, though!
