### ISSUE TITLE
character encoding: US-ASCII and UTF-8

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#8234]
I'm suddenly getting this new fastlane error

> [!] incompatible character encodings: US-ASCII and UTF-8 (Encoding::CompatibilityError)

```
/Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane/lib/fastlane/fast_file.rb:20:in `tr!': [!] incompatible character encodings: US-ASCII and UTF-8 (Encoding::CompatibilityError)
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane/lib/fastlane/fast_file.rb:20:in `initialize'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane/lib/fastlane/lane_manager.rb:12:in `new'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/fastlane/lib/fastlane/cli_tools_distributor.rb:63:in `take_off'
	from /Users/admin/.rvm/gems/ruby-2.2.0/gems/fastlane-2.15.1/bin/fastlane:15:in `<top (required)>'
	from /Users/admin/.rvm/gems/ruby-2.2.0/bin/fastlane:22:in `load'
	from /Users/admin/.rvm/gems/ruby-2.2.0/bin/fastlane:22:in `<main>'
	from /Users/admin/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/admin/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

I dont believe i've changed anything that i'm aware of.  Is this a fastlane error or something related to my software? 

Thanks

**Comment by flyeek** [comment]
I met this problem, and checked that my `LANG` environment variable value is unset. By setting the correct `LANG` environment variable before executing fastlane command, the problem is solved.

`export LANG="en_US.UTF-8`

**Comment by hite** [comment]
@flyeek` export LANG="en_US.UTF-8"` save my whole day
