### ISSUE TITLE
Unable to infer app version on CircleCI

### ISSUE THREAD

**Issue by philwebster** [fastlane/fastlane#8245]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Sometime in the last month, uploading to iTunes Connect stopped working with an error about being unable to infer the app version. I did a little digging and am thinking it may have started after the IPA file analyzer was refactored in #7587. Manually uploading the archive works fine and the `CFBundleShortVersionString` is set in the IPA's Info.plist.

##### Complete output when running fastlane, including the stack trace and command used
```
+----------------------+-----------------------------------+
|                  Summary for gym 2.16.0                  |
+----------------------+-----------------------------------+
| scheme               | Production                        |
| configuration        | Production                        |
| include_symbols      | true                              |
| output_directory     | /tmp/circle-artifacts.4QRBirO     |
| output_name          | OurApp                            |
| toolchain            | swift_3_1                         |
| export_method        | app-store                         |
| workspace            | ./OurApp.xcworkspace              |
| destination          | generic/platform=iOS              |
| clean                | false                             |
| silent               | false                             |
| use_legacy_build_api | false                             |
| buildlog_path        | /tmp/circle-artifacts.4QRBirO/gym |
| xcode_path           | /Applications/Xcode-8.2.app       |
+----------------------+-----------------------------------+
```
...
```
[10:35:08]: Successfully exported and compressed dSYM file
[10:35:08]: Successfully exported and signed the ipa file:
[10:35:08]: /tmp/circle-artifacts.4QRBirO/OurApp.ipa
[10:35:08]: ------------------------------
[10:35:08]: --- Step: backup_xcarchive ---
[10:35:08]: ------------------------------
[10:35:08]: Compressing /Users/distiller/Library/Developer/Xcode/Archives/2017-02-14/OurApp 2017-02-14 10.15.45.xcarchive
[10:35:08]: $ cd "/Users/distiller/Library/Developer/Xcode/Archives/2017-02-14" && zip -r -X "/var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/backup_xcarchive20170214-9522-o1mskh/OurApp 2017-02-14 10.15.45.xcarchive.zip" "OurApp 2017-02-14 10.15.45.xcarchive" > /dev/null
[10:35:32]: ---------------------
[10:35:32]: --- Step: deliver ---
[10:35:32]: ---------------------
[10:35:32]: Login to iTunes Connect (fastlane@company.com)
[10:35:37]: Login successful
+-----------------------+--------------------------------------------------------------------------+
|                                           Lane Context                                           |
+-----------------------+--------------------------------------------------------------------------+
| PLATFORM_NAME         |                                                                          |
| LANE_NAME             | send_to_itunes                                                           |
| SIGH_PROFILE_TYPE     | app-store                                                                |
| IPA_OUTPUT_PATH       | /tmp/circle-artifacts.4QRBirO/OurApp.ipa                                 |
| DSYM_OUTPUT_PATH      | /tmp/circle-artifacts.4QRBirO/OurApp.app.dSYM.zip                        |
| XCODEBUILD_ARCHIVE    | /Users/distiller/Library/Developer/Xcode/Archives/2017-02-14/OurApp 2... |
| BACKUP_XCARCHIVE_FILE | /tmp/circle-artifacts.4QRBirO/OurApp 2017-02-14 10.15.45.xcarchive.zip   |
+-----------------------+--------------------------------------------------------------------------+
[10:35:39]: Could not infer your app's version
```

Relevant portion of our Fastfile:
```
lane :send_to_itunes do

  run_buildnumber_script

  team_id = "ABCDEFG"
  app_identifier = "com.company.OurApp"
  force_match_appstore

  install_match(team_id, app_identifier)

  gym(
    scheme: 'Production',
    configuration: 'Production',
    include_symbols: true,
    output_directory: ENV['CIRCLE_ARTIFACTS'],
    output_name: 'OurApp.ipa',
    toolchain: :swift_3_1
  )

  save_archive_to_artifacts

  deliver(
    username: ENV['DELIVER_USER'],
    app_identifier: ENV['DELIVER_APP_IDENTIFER'],
    app: ENV['DELIVER_APPLE_ID'],
    ipa: "#{ENV['CIRCLE_ARTIFACTS']}/OurApp.ipa",
    force: true,
    skip_metadata: true
  )
end
```
### Environment

CircleCI
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                    |
| ------------------- | -------------------------------------------------------- |
| OS                  | 10.11.6                                                  |
| Ruby                | 2.3.1                                                    |
| Bundler?            | true                                                     |
| Git                 | git version 2.10.2                                       |
| Installation Source | ~/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                               |
| Ruby Lib Dir        | /opt/rubies/ruby-2.3.1/lib                               |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                              |
| Is contained        | false                                                    |
| Is homebrew         | false                                                    |
| Xcode Path          | /Applications/Xcode-8.2.app/Contents/Developer/          |
| Xcode Version       | 8.2.1                                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane            | 2.16.0  | ✅ Up-To-Date  |
| credentials_manager | 1.0.0   | ✅ Up-To-Date  |
| spaceship           | 1.0.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.6        |
| rake                      | 10.4.2       |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.0.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 0.3.2        |
| molinillo                 | 0.4.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.0.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types                | 2.99.3       |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| credentials_manager       | 1.0.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| rest-client               | 1.8.0        |
| slather                   | 2.3.0        |
```

**Comment by lacostej** [comment]
@philwebster are you able to add the little change I am pulling in in #8247 and run again to give us the exact reason this is failing? Thanks!

**Comment by philwebster** [comment]
Yep! Will do.

**Comment by philwebster** [comment]
Here's the error:
```
[12:21:26]: Login to iTunes Connect (fastlane@remind101.com)
[12:21:31]: Login successful
[12:21:32]: "\xDF" from ASCII-8BIT to UTF-8
```

**Comment by lacostej** [comment]
@philwebster have you double checked your locale setup?

**Comment by philwebster** [comment]
This is the output of `locale` from an ssh build:
```
distiller-build-107:~ distiller$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by philwebster** [comment]
Still figuring this out. This is the plist from the ipa generated by gym and it probably shouldn't be garbled:
![screenshot 2017-02-16 12 19 26](https://cloud.githubusercontent.com/assets/763550/23039462/660c26ac-f442-11e6-9f9e-6d13c22204e4.png)

**Comment by hjanuschka** [comment]
can you share the `run_buildnumber_script` -> maybe this issue is a good starting point. 
https://github.com/fastlane/fastlane/issues/6810

**Comment by philwebster** [comment]
Thanks! Here's the script:
```
#!/bin/bash

# Only update build number in certain configurations -- for release or for a beta build.
echo "configuration $CONFIGURATION"

if [ "$CONFIGURATION" = "Fastlane" ] ||
 [ "$CONFIGURATION" = "Latest" ] ||
 [ "$CONFIGURATION" = "RC" ] ||
 [ "$CONFIGURATION" = "Production" ]
then

plist=./OurApp/Resources/plist/OurApp-Info.plist

#Number of minutes since January 1st, 2015 at 0:00:00
buildNumber=$(python -c "import time; from datetime import datetime; print int( (datetime.today()-datetime(2015,1,1,0,0,0)).total_seconds()/60 )")

/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${plist}"

echo "set build number to $buildNumber"

fi
```

**Comment by hjanuschka** [comment]
@philwebster  could you try looking at the plist before the `PlistBuddy` and afterwards, and lets see if the `.plist` is already garbaged, or `PlistBuddy` does it.


i think you could also try another aproach directly via fastlane.


```
increment_version_number(version_number: "1.2.3")
```

**Comment by mfurtak** [comment]
I could be wrong, but that looks like it was converted to a binary plist format (bplist) http://osxdaily.com/2016/03/10/convert-plist-file-xml-binary-mac-os-x-plutil/

**Comment by lacostej** [comment]
@philwebster @hjanuschka It's probably not garbled but in binary format. And given the way the code is, it should be readable, because fastlane converts it back into xml again after unpacking the ipa.

If you want to experiment with the fastlane code you could download this file:

https://raw.githubusercontent.com/fastlane/fastlane/master/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb

And use it in the following way

```
$ irb
2.2.4 :002 > require './ipa_file_analyser'
 => true 
2.2.4 :003 > FastlaneCore::IpaFileAnalyser.fetch_info_plist_file('path/to/your.ipa')
=> {"BuildMachineOSBuild"=>"15C50", "CFBundleDevelopmentRegion"=>"en", "CFBundleDisplayName"=>"UnityLab", "CFBundleExecutable"=>"UnityLab", "CFBundleIconFiles"...}
```

**Comment by lacostej** [comment]
I would love to know where the error is happening exactly. If you are unable to reproduce the problem with the `ipa_file_analyser`, maybe you can modify your `deliver/lib/deliver/detect_values.rb` file so that

```
UI.error(ex)
```
become
```
UI.error("#{ex.message}\n#{ex.backtrace.join('\n')}")
```

**Comment by philwebster** [comment]
Great, I'll give that a try and report back.

**Comment by mfurtak** [comment]
@lacostej @philwebster If you just want the backtrace, then running with the `--verbose` should turn that on for `UI.user_error!()`

**Comment by lacostej** [comment]
@mfurtak I want the stack of the previous error, to see where the issue fails within the ipa analysis.

**Comment by philwebster** [comment]
To use `ipa_file_analyser` locally, I had to `gem install rubyzip` (after installing `plist` and trying `zip`). Then `fetch_app_version` worked fine:
```
irb(main):003:0> FastlaneCore::IpaFileAnalyser.fetch_app_version('/Users/pwebster/Downloads/Remind.ipa')
=> "7.3"
```

I'm really new to Ruby, so it's totally possible I'm doing something wrong. Locally, I'm on 2.2.2, but I see this error in Circle logs in a few places:
```
chruby: unknown Ruby: 2.2.2
The Gemfile's dependencies are satisfied
```

**Comment by philwebster** [comment]
And this is output from running with `--verbose` on Circle:
```
ERROR [2017-02-16 14:22:12.83]: fastlane finished with errors
bundler: failed to load command: fastlane (/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Could not infer your app's version
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/interface.rb:146:in `user_error!'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/deliver/lib/deliver/detect_values.rb:60:in `rescue in find_version'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/deliver/lib/deliver/detect_values.rb:51:in `find_version'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/deliver/lib/deliver/detect_values.rb:9:in `run!'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/deliver/lib/deliver/runner.rb:8:in `initialize'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/deliver.rb:16:in `new'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/deliver.rb:16:in `run'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `chdir'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:88:in `block in parsing_binding'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/cli_tools_distributor.rb:63:in `take_off'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/fastlane-2.17.1/bin/fastlane:15:in `<top (required)>'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  /Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'

bundle exec fastlane send_to_itunes --verbose returned exit code 1
```

**Comment by lacostej** [comment]
I sent #8286 to help you troubleshoot further. Feel free to use that version of fastlane from my tree if you know how to do that. (if you use bundler, specify it in your Gemfile as a git repo and the branch / commit for the pull request)

**Comment by philwebster** [comment]
Thank you so much! Here's the output:
```
[10:01:56]: ---------------------
[10:01:56]: --- Step: deliver ---
[10:01:56]: ---------------------
[10:01:56]: Login to iTunes Connect (fastlane@remind101.com)
[10:02:01]: Login successful
[10:02:03]: "\xDF" from ASCII-8BIT to UTF-8
/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:40:in `write'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:40:in `block (2 levels) in fetch_info_plist_file'\n/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:37:in `block in fetch_info_plist_file'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:31:in `fetch_info_plist_file'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:15:in `fetch_app_version'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/deliver/lib/deliver/detect_values.rb:54:in `find_version'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/deliver/lib/deliver/detect_values.rb:9:in `run!'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/deliver/lib/deliver/runner.rb:8:in `initialize'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/actions/deliver.rb:16:in `new'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/actions/deliver.rb:16:in `run'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/runner.rb:217:in `chdir'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/runner.rb:217:in `execute_action'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'\nFastfile:88:in `block in parsing_binding'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/lane.rb:33:in `call'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/runner.rb:49:in `block in execute'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/runner.rb:45:in `chdir'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/runner.rb:45:in `execute'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/commands_generator.rb:302:in `run'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/commands_generator.rb:42:in `start'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/fastlane/lib/fastlane/cli_tools_distributor.rb:63:in `take_off'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-0183457fa5c6/bin/fastlane:15:in `<top (required)>'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'\n/Users/distiller/r101-ios-teacher/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'\n/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'\n/opt/rubies/ruby-2.3.1/bin/bundle:23:in `load'\n/opt/rubies/ruby-2.3.1/bin/bundle:23:in `<main>'
+-----------------------+--------------------------------------------------------------------------+
|                                           Lane Context                                           |
+-----------------------+--------------------------------------------------------------------------+
| PLATFORM_NAME         |                                                                          |
| LANE_NAME             | send_to_itunes                                                           |
| SIGH_PROFILE_TYPE     | app-store                                                                |
| IPA_OUTPUT_PATH       | /tmp/circle-artifacts.zM8uKFg/Remind.ipa                                 |
| DSYM_OUTPUT_PATH      | /tmp/circle-artifacts.zM8uKFg/Remind.app.dSYM.zip                        |
| XCODEBUILD_ARCHIVE    | /Users/distiller/Library/Developer/Xcode/Archives/2017-02-17/Remind 2... |
| BACKUP_XCARCHIVE_FILE | /tmp/circle-artifacts.zM8uKFg/Remind 2017-02-17 09.38.18.xcarchive.zip   |
+-----------------------+--------------------------------------------------------------------------+
[10:02:03]: Could not infer your app's version

+------+-----------------------------------+-------------+
|                    fastlane summary                    |
+------+-----------------------------------+-------------+
| Step | Action                            | Time (in s) |
+------+-----------------------------------+-------------+
| 1    | cd .. && ./scripts/buildnumber.sh | 0           |
| 2    | match                             | 1           |
| 3    | gym                               | 1395        |
| 4    | backup_xcarchive                  | 28          |
| 💥   | deliver                           | 7           |
+------+-----------------------------------+-------------+
```

**Comment by lacostej** [comment]
@philwebster 

have you tried fully setting your ruby encoding environment?

```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

It looks like only `LANG` is set

**Comment by philwebster** [comment]
Same error after setting those environment variables, unfortunately:
`[14:11:17]: Could not infer your app's version`

I'm thinking I should make a very minimal project and try building/uploading that on Circle to see what happens.

**Comment by lacostej** [comment]
Have you tried with `export LC_CTYPE=en_US.UTF-8`

I see that one issue you reference to is using this as workaround

**Comment by lacostej** [comment]
If you want to experiment further, you could try this branch / patch: https://github.com/lacostej/fastlane/tree/binary_analysis

**Comment by philwebster** [comment]
Using your `binary_analysis` branch seems to have worked!

`[12:40:11]: Making sure the latest version on iTunes Connect matches '7.3' from the ipa file...`

**Comment by AymenFarrah** [comment]
have same issue, testFlight fail ! 
 "\xDF" from ASCII-8BIT to UTF-8
with the last update of fastlane

**Comment by lacostej** [comment]
@philwebster have you also tried setting the LC_TYPE on the official version?

**Comment by philwebster** [comment]
Hey @lacostej, I still get `Could not infer your app's version` with `LC_TYPE` set on the official version.

**Comment by philwebster** [comment]
We are back in business! Thanks so much for all the help @lacostej!
