### ISSUE TITLE
Can't get Master/Slave device error

### ISSUE THREAD

**Issue by dpettit** [fastlane/fastlane#8258]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I was in the middle of testing, just changing a couple android UiDevice settings to see how they played out, when I randomly started receiving this error.  

I didn't do any updates, or change anything else -- just running a script and swapping out a couple of mUIDevice.swipe() settings.

Any idea on how to fix?
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
*************************************************************
Begin BT-A-4 script execution...
*************************************************************
Phone_-_Nexus_4_-_API_19
Phone_-_Nexus_4_-_API_22
Phone_-_Nexus_4_-_API_23
Phone_-_Nexus_4_-_API_25
Phone_-_Nexus_5X_-_API_22
Phone_-_Nexus_5_-_API_19
Phone_-_Nexus_5_-_API_22
Phone_-_Nexus_5_-_API_23
Phone_-_Nexus_6P_-_API_22
Phone_-_Nexus_6P_-_API_23
Phone_-_Nexus_6_-_API_19
Phone_-_Nexus_6_-_API_22
Phone_-_Nexus_6_-_API_23
Phone_-_Nexus_S_-_API_19
Phone_-_Nexus_S_-_API_22
Phone_-_Nexus_S_-_API_23
Tablet_-_Nexus_10_-_API_19
Tablet_-_Nexus_10_-_API_22
Tablet_-_Nexus_10_-_API_23
Tablet_-_Nexus_7_-_API_19
Tablet_-_Nexus_7_-_API_22
Tablet_-_Nexus_7_-_API_23
Tablet_-_Nexus_7_2012_-_API_19
Tablet_-_Nexus_7_2012_-_API_22
Tablet_-_Nexus_7_2012_-_API_23
Tablet_-_Nexus_9_-_API_19
Tablet_-_Nexus_9_-_API_22
Tablet_-_Nexus_9_-_API_23
Tablet_-_WSVGA_7_-_API_19
Tablet_-_WSVGA_7_-_API_22
Tablet_-_WSVGA_7_-_API_23
Tablet_-_WXGA_10_1_-_API_19
Tablet_-_WXGA_10_1_-_API_22
Tablet_-_WXGA_10_1_-_API_23

No open emulators found!

Build ScreengrabDebugAndroidTest and ScreengrabDebug using Gradle...

error: no emulator detected
[11:21:02]: -------------------------------------------------
[11:21:02]: --- Step: Verifying required fastlane version ---
[11:21:02]: -------------------------------------------------
[11:21:02]: Your fastlane version 2.16.0 matches the minimum requirement of 1.104.0  ✅
[11:21:02]: ------------------------------
[11:21:02]: --- Step: default_platform ---
[11:21:02]: ------------------------------
[11:21:02]: Driving the lane 'android buildDebug' 🚀
[11:21:02]: --------------------
[11:21:02]: --- Step: gradle ---
[11:21:02]: --------------------
[11:21:02]: $ /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/gradlew clean assembleScreengrabDebugAndroidTest assembleScreengrabDebug -p .
[11:21:05]: ▸ Incremental java compilation is an incubating feature.
[11:21:06]: ▸ :clean
[11:21:06]: ▸ :preBuild UP-TO-DATE
[11:21:06]: ▸ :preScreengrabDebugBuild UP-TO-DATE
[11:21:06]: ▸ :checkScreengrabDebugManifest
[11:21:06]: ▸ :preScreengrabDebugAndroidTestBuild UP-TO-DATE
[11:21:06]: ▸ :preScreengrabReleaseBuild UP-TO-DATE
[11:21:06]: ▸ :prepareComAndroidSupportTestEspressoEspressoCore222Library
[11:21:06]: ▸ :prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library
[11:21:06]: ▸ :prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
[11:21:06]: ▸ :prepareComAndroidSupportTestRules05Library
[11:21:06]: ▸ :prepareComAndroidSupportTestRunner05Library
[11:21:06]: ▸ :prepareComAndroidSupportTestUiautomatorUiautomatorV18212Library
[11:21:06]: ▸ :prepareToolsFastlaneScreengrab055Library
[11:21:06]: ▸ :prepareScreengrabDebugDependencies
[11:21:06]: ▸ :compileScreengrabDebugAidl
[11:21:06]: ▸ :compileScreengrabDebugRenderscript
[11:21:06]: ▸ :generateScreengrabDebugBuildConfig
[11:21:06]: ▸ :generateScreengrabDebugResValues
[11:21:06]: ▸ :generateScreengrabDebugResources
[11:21:06]: ▸ :mergeScreengrabDebugResources
[11:21:06]: ▸ :processScreengrabDebugManifest
[11:21:07]: ▸ :processScreengrabDebugResources
[11:21:07]: ▸ :generateScreengrabDebugSources
[11:21:07]: ▸ :incrementalScreengrabDebugJavaCompilationSafeguard
[11:21:07]: ▸ :compileScreengrabDebugJavaWithJavac
[11:21:07]: ▸ :compileScreengrabDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
[11:21:07]: ▸ Note: /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/src/com/talespring/wrapper/AndroidHTMLWrapper.java uses or overrides a deprecated API.
[11:21:07]: ▸ Note: Recompile with -Xlint:deprecation for details.
[11:21:07]: ▸ :prepareScreengrabDebugAndroidTestDependencies
[11:21:07]: ▸ :compileScreengrabDebugAndroidTestAidl
[11:21:07]: ▸ :processScreengrabDebugAndroidTestManifest
[11:21:07]: ▸ :compileScreengrabDebugAndroidTestRenderscript
[11:21:07]: ▸ :generateScreengrabDebugAndroidTestBuildConfig
[11:21:07]: ▸ :generateScreengrabDebugAndroidTestResValues
[11:21:07]: ▸ :generateScreengrabDebugAndroidTestResources
[11:21:07]: ▸ :mergeScreengrabDebugAndroidTestResources
[11:21:07]: ▸ :processScreengrabDebugAndroidTestResources
[11:21:07]: ▸ :generateScreengrabDebugAndroidTestSources
[11:21:07]: ▸ :incrementalScreengrabDebugAndroidTestJavaCompilationSafeguard
[11:21:07]: ▸ :compileScreengrabDebugAndroidTestJavaWithJavac
[11:21:07]: ▸ :compileScreengrabDebugAndroidTestNdk UP-TO-DATE
[11:21:07]: ▸ :compileScreengrabDebugAndroidTestSources
[11:21:07]: ▸ :mergeScreengrabDebugAndroidTestShaders
[11:21:07]: ▸ :compileScreengrabDebugAndroidTestShaders
[11:21:07]: ▸ :generateScreengrabDebugAndroidTestAssets
[11:21:07]: ▸ :mergeScreengrabDebugAndroidTestAssets
[11:21:07]: ▸ :transformClassesWithDexForScreengrabDebugAndroidTest
[11:21:07]: ▸ :mergeScreengrabDebugAndroidTestJniLibFolders
[11:21:07]: ▸ :transformNative_libsWithMergeJniLibsForScreengrabDebugAndroidTest
[11:21:07]: ▸ :processScreengrabDebugAndroidTestJavaRes UP-TO-DATE
[11:21:08]: ▸ :transformResourcesWithMergeJavaResForScreengrabDebugAndroidTest
[11:21:08]: ▸ :validateSigningScreengrabDebugAndroidTest
[11:21:08]: ▸ :packageScreengrabDebugAndroidTest
[11:21:08]: ▸ :assembleScreengrabDebugAndroidTest
[11:21:08]: ▸ :compileScreengrabDebugNdk UP-TO-DATE
[11:21:08]: ▸ :compileScreengrabDebugSources
[11:21:08]: ▸ :mergeScreengrabDebugShaders
[11:21:08]: ▸ :compileScreengrabDebugShaders
[11:21:08]: ▸ :generateScreengrabDebugAssets
[11:21:08]: ▸ :mergeScreengrabDebugAssets
[11:21:12]: ▸ :transformClassesWithDexForScreengrabDebug
[11:21:12]: ▸ :mergeScreengrabDebugJniLibFolders
[11:21:12]: ▸ :transformNative_libsWithMergeJniLibsForScreengrabDebug
[11:21:12]: ▸ :processScreengrabDebugJavaRes
[11:21:12]: ▸ :transformResourcesWithMergeJavaResForScreengrabDebug
[11:21:12]: ▸ :validateSigningScreengrabDebug
[11:21:13]: ▸ :packageScreengrabDebug
[11:21:13]: ▸ :assembleScreengrabDebug
[11:21:13]: ▸ BUILD SUCCESSFUL
[11:21:13]: ▸ Total time: 11.302 secs
[11:21:13]: ▸ This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gradle                              | 11          |
+------+-------------------------------------+-------------+

[11:21:14]: fastlane.tools finished successfully 🎉

Debug Build complete!

Emulator avd started, waiting for boot
List of devices attached

Hax is enabled
Hax ram_size 0x60000000
HAX is working and emulator runs in fast virt mode.
emulator: Listening for console connections on port: 5554
emulator: Serial number of this emulator (for ADB): emulator-5554
...waiting
...waiting
...waiting
...waiting
...waiting
Device online, initiating screengrab for device type: phone...

[11:21:35]: Successfully loaded '/Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/fastlane/Screengrabfile' 📄

+----------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
|                                                             Detected Values from './fastlane/Screengrabfile'                                                             |
+----------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| android_home               | /Users/tsdev/Library/Android/sdk                                                                                                            |
| use_tests_in_classes       | ["androidTest.java.AndroidHTMLWrapperTest"]                                                                                                 |
| tests_package_name         | com.talespring.wrapper.mydaddy.test                                                                                                         |
| app_apk_path               | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-screengrab-debug.apk             |
| tests_apk_path             | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-screengrab-debug-androidTest.apk |
| locales                    | ["en-US"]                                                                                                                                   |
| clear_previous_screenshots | true                                                                                                                                        |
+----------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+

+-----------------------------+--------------------------------------------------------------------+
|                                  Summary for screengrab 2.16.0                                   |
+-----------------------------+--------------------------------------------------------------------+
| device_type                 | phone                                                              |
| app_package_name            | com.talespring.mydaddy.android                                     |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner                     |
| android_home                | /Users/tsdev/Library/Android/sdk                                   |
| use_tests_in_classes        | ["androidTest.java.AndroidHTMLWrapperTest"]                        |
| tests_package_name          | com.talespring.wrapper.mydaddy.test                                |
| app_apk_path                | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyD... |
| tests_apk_path              | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyD... |
| locales                     | ["en-US"]                                                          |
| clear_previous_screenshots  | true                                                               |
| output_directory            | fastlane/metadata/android                                          |
| skip_open_summary           | false                                                              |
| ending_locale               | en-US                                                              |
| exit_on_test_failure        | true                                                               |
| reinstall_app               | false                                                              |
+-----------------------------+--------------------------------------------------------------------+

[11:21:35]: Clearing phoneScreenshots within fastlane/metadata/android
[11:21:35]: $ adb devices -l
can't get Master/Slave device

Looking for related GitHub issues on fastlane/fastlane...

➡️  Remove Shenzhen dependency
   https://github.com/fastlane/fastlane/pull/6991 [closed] 19 💬
   12 Dec 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/fastlane_core/lib/fastlane_core/command_executor.rb:46:in `spawn': [!] can't get Master/Slave device (RuntimeError)
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/fastlane_core/lib/fastlane_core/command_executor.rb:46:in `execute'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/screengrab/lib/screengrab/runner.rb:354:in `run_adb_command'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/screengrab/lib/screengrab/runner.rb:76:in `select_device'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/screengrab/lib/screengrab/runner.rb:52:in `run'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/screengrab/lib/screengrab/commands_generator.rb:41:in `block (2 levels) in run'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/screengrab/lib/screengrab/commands_generator.rb:58:in `run'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/screengrab/lib/screengrab/commands_generator.rb:11:in `start'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/fastlane/lib/fastlane/cli_tools_distributor.rb:49:in `take_off'
	from /Users/tsdev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.16.0/bin/fastlane:15:in `<top (required)>'
	from /Users/tsdev/.rbenv/versions/2.3.3/bin/fastlane:22:in `load'
	from /Users/tsdev/.rbenv/versions/2.3.3/bin/fastlane:22:in `<main>'
pimac:TS_Scripts tsdev$ 

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.16.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.5        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-02-15**
</details>

**Comment by dpettit** [comment]
Alas, I restarted my machine, and the issue seems to have resolved!  Sorry about that.

Closing the issue.
