### ISSUE TITLE
What is the proper way to call an action from another action?

### ISSUE THREAD

**Issue by kcharwood** [fastlane/fastlane#826]
Building up some custom action that depend on others, and can't quite figure out the best way.

**Comment by kcharwood** [comment]
For example, I want to call `prompt` from within an action.

**Comment by xfreebird** [comment]
For example you want to call ```PromptAction``` action. 
The class name for that action is ```PromptAction```, you can find that by looking at the implementation of the action https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/prompt.rb

Then in your own action you would call:
```Fastlane::Actions::PromptAction(text: "Please input your password:")```

Hope this helps.

**Comment by KrauseFx** [comment]
Thanks @xfreebird, I'll update `Advanced.md` to cover this :+1:

**Comment by kcharwood** [comment]
I'm trying something similar to that, but I am getting a crash. Here is a simply example:

```Ruby
module Fastlane
  module Actions
    class FunAction < Action
      def self.run(params)
        Fastlane::Actions::PromptAction(
          text: "Do you have fun?",
          boolean: true,
          ci_input: "y"
        )
      end

      def self.authors
        ["kcharwood"]
      end

      def self.is_supported?(platform)
        return true
      end
    end
  end
end
```

```
$ fastlane run fun
[15:33:37]: Successfully loaded custom action '/Users/kevin.harwood/GIT/AFNetworking/fastlane/actions/fun.rb'.
[15:33:37]: -----------------
[15:33:37]: --- Step: fun ---
[15:33:37]: -----------------
Successfully submitted crash report. If this is a problem with one of the tools you want to report
please submit an issue on GitHub and attach the following number to it: '97761fb37466e3bed6e753c8dafd87a1'
Also stored the crash report locally '/tmp/sentry_97761fb37466e3bed6e753c8dafd87a1.json'
```

I get this from the crash log:

```
"message": "NoMethodError: undefined method `PromptAction' for Fastlane::Actions:Module",
```

See anything I'm doing dumb?

**Comment by KrauseFx** [comment]
@kcharwood sorry, it should be 

```ruby
  Actions::DeliverAction.run(text: "Please input your password:", 
                              key: 123)
```

**Comment by kcharwood** [comment]
Thanks @KrauseFx. That works for actions packed into fastlane!

But, if I want to call my own custom actions, that reside in the same repo, that fails. Do those belong in a different namespace?

**Comment by KrauseFx** [comment]
@kcharwood Interesting, I don't know, can you share the files you use so I can reproduce the issue?

**Comment by xfreebird** [comment]
@KrauseFx why the ```prompt``` action can't be called like this ```Fastlane::Actions::PromptAction(text: "Please input your password:")``` from custom actions ? Is it treated in a special way ?

**Comment by KrauseFx** [comment]
@xfreebird prompt should work too. What's the error?

**Comment by serluca** [comment]
I'm trying to do call sigh from another action in this way 

```
Actions::SighAction.run(
            adhoc: true,
            force: true
          )
```

but I do receive this error
`Something went wrong with the deployment: wrong number of arguments (1 for 0)`

any idea?

**Comment by KrauseFx** [comment]
@serluca Please share the complete output and stack trace

**Comment by serluca** [comment]
@KrauseFx 

Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '005673a4cb07620d4a991b77c8a0edfc'
```
The crash report has been stored locally '/tmp/sentry_005673a4cb07620d4a991b77c8a0edfc.json'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/print_table.rb:10:in `values': [!] wrong number of arguments (1 for 0) (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/print_table.rb:10:in `print_values'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.5.0/lib/sigh/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.5.0/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/actions/sigh.rb:20:in `run'
	from /Users/serpicoluca/Workspace/rc-ios/fastlane/actions/fetch_provisioning.rb:12:in `block in run'
	from /Users/serpicoluca/Workspace/rc-ios/fastlane/actions/fetch_provisioning.rb:10:in `each'
	from /Users/serpicoluca/Workspace/rc-ios/fastlane/actions/fetch_provisioning.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:18:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.66.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Thanks @serluca, that was super helpful, I just pushed a fix https://github.com/fastlane/fastlane/pull/3852 and it will be live in the next release next week :+1:

**Comment by serluca** [comment]
@KrauseFx any news on this?

**Comment by TKBurner** [comment]
Hi @serluca we are still working on getting this merged into master. Checkout #3852 to track progress :+1:

**Comment by KrauseFx** [comment]
Sorry for taking so long, this is now merged into master and will be in the next release :+1:
