### ISSUE TITLE
fastlane beta- undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007fcf2b4d7900>

### ISSUE THREAD

**Issue by zoufishanmehdi** [fastlane/fastlane#8290]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Trying to run fastlane beta. Keep getting this error `undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007fcf2b4d7900>.` I also referred to a previous [issue](https://github.com/fastlane/fastlane/issues/7901) and added `cert` and `sigh` to the Fastfile to fix possible codesigning issues but it still doesn't work. 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
[15:04:09]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
[15:04:09]: -------------------------------------------------
[15:04:09]: --- Step: Verifying required fastlane version ---
[15:04:09]: -------------------------------------------------
[15:04:09]: Your fastlane version 2.17.1 matches the minimum requirement of 2.14.2  ✅
[15:04:09]: ------------------------------
[15:04:09]: --- Step: default_platform ---
[15:04:09]: ------------------------------
[15:04:09]: Name of the lane 'appstore' is already taken by the action named 'appstore'
[15:04:09]: Driving the lane 'ios beta' 🚀
[15:04:09]: -----------------------
[15:04:09]: --- Step: cocoapods ---
[15:04:09]: -----------------------
[15:04:09]: Installing Ruby gem 'cocoapods'...
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[15:04:13]: undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007fcf2b4d7900>

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | cocoapods                           | 4           |
+------+-------------------------------------+-------------+

[15:04:13]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007ffb208656a0>
   https://github.com/fastlane/fastlane/issues/7901 [closed] 4 💬
   2 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/fastlane_require.rb:36:in `install_gem_if_needed': [!] undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007fcf2b4d7900> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/helper/gem_helper.rb:7:in `verify_gem!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/cocoapods.rb:5:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:21:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:259:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:259:in `execute_flow_block'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/cli_tools_distributor.rb:63:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.17.1/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by KrauseFx** [comment]
Could you run `bundle init` and use the following content: 

```ruby
source "https://rubygems.org"

gem "fastlane"
gem "cocoapods"
```

Then run `bundle update` and run `fastlane` using `bundle exec fastlane beta`. Check in the `Gemfile` and `Gemfile.lock`. Let me know if that works. More information on the [docs page](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile)  🚀

**Comment by zoufishanmehdi** [comment]
@KrauseFx Thank you for your response. Do I only have to use `bundle exec fastlane beta` the first time and can use `fastlane beta` after that?

**Comment by hjanuschka** [comment]
once you switched to a gemfile you supposed to use all fastlane commands with "bundle exec " in front. you could give the contained version a try: https://github.com/fastlane/fastlane#installation installing via installer script (this comes with everything ready to run).

**Comment by KrauseFx** [comment]
I'll close this issue due to inactivity now. Feel free to re-open it, or submit a new one if you have the chance 👍 Thanks
