### ISSUE TITLE
fastlane updater crashes while updating

### ISSUE THREAD

**Issue by generalpf** [fastlane/fastlane#831]
We're running fastlane on a build machine with the command `fastlane unit_test` and this is the output, which fails the build on Jenkins:

```
10:00:12 +------+---------------------------------------------------------------+-------------+
10:00:12 |                                  fastlane summary                                  |
10:00:12 +------+---------------------------------------------------------------+-------------+
10:00:12 | Step | Action                                                        | Time (in s) |
10:00:12 +------+---------------------------------------------------------------+-------------+
10:00:12 | 1    | opt_out_usage                                                 | 0           |
10:00:12 | 2    | Verifying required fastlane version                           | 0           |
10:00:12 | 3    | default_platform                                              | 0           |
10:00:12 | 4    | bundle_install                                                | 0           |
10:00:12 | 5    | cocoapods                                                     | 11          |
10:00:12 | 6    | /usr/libexec/PlistBuddy -c 'Set CFBundleShortVersionString 2. | 0           |
10:00:12 | 7    | /usr/libexec/PlistBuddy -c 'Set CFBundleShortVersionString 2. | 0           |
10:00:12 | 8    | /usr/libexec/PlistBuddy -c 'Set CFBundleShortVersionString 2. | 0           |
10:00:12 | 9    | /usr/libexec/PlistBuddy -c 'Set CFBundleShortVersionString 2. | 0           |
10:00:12 | 10   | scan                                                          | 94          |
10:00:12 | 11   | slack                                                         | 0           |
10:00:12 +------+---------------------------------------------------------------+-------------+
10:00:12 
10:00:12 [10:00:12]: fastlane.tools finished successfully 🎉
10:00:12 /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:8:in `[]': no implicit conversion of String into Integer (TypeError)
10:00:12 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:8:in `block in show_changes'
10:00:12 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:7:in `each'
10:00:12 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:7:in `each_with_index'
10:00:12 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/changelog.rb:7:in `show_changes'
10:00:12 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/update_checker.rb:63:in `show_update_message'
10:00:12 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.26.1/lib/fastlane_core/update_checker/update_checker.rb:46:in `show_update_status'
10:00:12 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.38.0/bin/fastlane:162:in `<top (required)>'
10:00:12 	from /usr/bin/fastlane:23:in `load'
10:00:12 	from /usr/bin/fastlane:23:in `<main>'
10:00:12 
10:00:12 #######################################################################
10:00:12 # fastlane 1.38.1 is available. You are on 1.38.0.
10:00:12 # It is recommended to use the latest version.
10:00:12 # Update using 'sudo gem update fastlane'.
10:00:12 #######################################################################
10:00:12 # Run `sudo gem cleanup` from time to time to speed up fastlane
10:00:12 #######################################################################
```

If we log in to the build machine and manually update the fastlane gem, it works, but that's a painful workaround.

**Comment by mortenholmgaard** [comment]
I might have the same error when updating fastlane - or a very similar one:
>sudo gem update fastlane
Updating installed gems
Updating fastlane
Fetching: spaceship-0.14.1.gem (100%)
Successfully installed spaceship-0.14.1
Fetching: sigh-1.1.3.gem (100%)
Successfully installed sigh-1.1.3
Fetching: scan-0.2.1.gem (100%)
Successfully installed scan-0.2.1
Fetching: fastlane-1.39.0.gem (100%)
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String

I have tried to run `sudo gem cleanup` but still same error.

**Comment by KrauseFx** [comment]
Thanks for reporting this, I'm working on a fix :+1:

**Comment by KrauseFx** [comment]
This is fixed now, please update using `sudo gem update fastlane_core`

@mortenholmgaard you didn't post the stack trace + the crash report ID, so I can't tell if it's the same error.

**Comment by mortenholmgaard** [comment]
I didn't get a crash report ID because it was run as a direct command with `sudo gem update fastlane`
Is that command not valid any more? 
The update works fine with `sudo gem update fastlane_core` but isn't the above command still suppose to work?

**Comment by KrauseFx** [comment]
@mortenholmgaard `sudo gem update...` is not a `fastlane` thing, but part of RubyGems and therefore out of my control

**Comment by generalpf** [comment]
Thank you @KrauseFx !

**Comment by KrauseFx** [comment]
:+1:
