### ISSUE TITLE
[!] Google Api Error: publishingDailySaveQuotaExceeded: Daily save quota exceeded.

### ISSUE THREAD

**Issue by s-gagandeep** [fastlane/fastlane#8390]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am getting below error while updating apk to alpha on playtore
[!] Google Api Error: publishingDailySaveQuotaExceeded: Daily save quota exceeded.

And i haven't updated the app today, so i am not sure why i am getting this error, as this is my first attempt to update the app on alpha.
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
  lane :flavor1 do
    supply(
    track: 'alpha',
    skip_upload_metadata: 'true',
    skip_upload_images: 'true',
    skip_upload_screenshots: 'true',
    package_name: 'com.flavor1.src',
    apk_paths: ["/Users/Involvio/..."]
    )
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by KirillMakarov** [comment]
+1
I have the same error "[!] Google Api Error: publishingDailySaveQuotaExceeded: Daily save quota exceeded." after publishing just 5 apk (split by abi).

**Comment by mhillebert** [comment]
+1
Same issue. Started Yesterday. Still happens today.
```
UncaughtThrowError: [31m[!] uncaught throw #<FastlaneCore::Interface::FastlaneError: Google Api Error: publishingDailySaveQuotaExceeded: Daily save quota exceeded.>[0m
  Fastfile:416:in `throw'
  Fastfile:416:in `rescue in perform_android_build'
  Fastfile:389:in `perform_android_build'
  Fastfile:243:in `block in parsing_binding'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:192:in `try_switch_to_lane'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:147:in `trigger_action_by_name'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:249:in `block in parsing_binding'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
  /Users/jenkins/.gem/ruby/2.2.3/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Users/jenkins/.gem/ruby/2.2.3/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Users/jenkins/.gem/ruby/2.2.3/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  /Users/jenkins/.gem/ruby/2.2.3/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/jenkins/.gem/ruby/2.2.3/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
  /Users/jenkins/.gem/ruby/2.2.3/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
  /Users/jenkins/.gem/ruby/2.2.3/bin/fastlane:23:in `load'
  /Users/jenkins/.gem/ruby/2.2.3/bin/fastlane:23:in `<top (required)>'
```

**Comment by hjanuschka** [comment]
@mfurtak  probably related to: https://github.com/fastlane/fastlane/pull/8474?

**Comment by mfurtak** [comment]
Hi everyone 👋 

This is a rate limiting error message from the Play API that is outside of the control of fastlane and supply, but we'd like to look into it further in case there's something we could be doing better. 👍  Please provide information about your fastlane environment by pasting the output of `fastlane env` here. 

Thanks!

**Comment by mfurtak** [comment]
Also, it would be helpful to know how often you're calling supply per day, and how many APK variants you are publishing.

**Comment by tmtrademarked** [comment]
Hmm, that's very odd - doesn't seem obvious how #8474 would have caused the Play API to trigger rate limiting more aggressively. If anything, I'd think it would *reduce* the traffic from supply to Play.

**Comment by mfurtak** [comment]
@tmtrademarked My feeling is the same is yours, so I'm not too suspicious of that change yet 👍

**Comment by hjanuschka** [comment]
doesn't seem to be connected, sorry i think i thought in the wrong direction 😢

**Comment by mfurtak** [comment]
No worries @hjanuschka - looking at the recent changes is always a good idea 👍

**Comment by jeffc-kpcc** [comment]
For what it's worth, I'm _also_ getting this same error. Even though this is the first time I've tried uploading an alpha today and even though (near as I can tell) the Google Play API Manager shows no API usage at all.

I'm not sure if this helps at all, but if I pass a 'validate_only' flag it is fine (and validates okay). This only happens when I try uploading a build.

Has anyone figured out a cause for - or solution to - this?

```
+-------------------------+-------------------------------------------------+
|                         Summary for supply 2.23.0                         |
+-------------------------+-------------------------------------------------+
| track                   | alpha                                           |
| json_key                | app/src/main/assets/google_service_account.json |
| apk                     | app/build/outputs/apk/app-release-signed.apk    |
| package_name            | (package name goes here)                        |
| skip_upload_metadata    | 1                                               |
| skip_upload_images      | 1                                               |
| skip_upload_screenshots | 1                                               |
| rollout                 | 0.1                                             |
| metadata_path           | ./metadata                                      |
| skip_upload_apk         | false                                           |
| validate_only           | false                                           |
+-------------------------+-------------------------------------------------+

DEBUG [2017-03-30 10:10:39.70]: Fetching a new access token from Google...
INFO [2017-03-30 10:10:40.73]: Preparing to upload for language 'en-US'...
INFO [2017-03-30 10:10:41.03]: Preparing apk at path 'app/build/outputs/apk/app-release-signed.apk' for upload...
INFO [2017-03-30 10:10:46.26]: Updating track 'alpha'...
INFO [2017-03-30 10:10:46.99]: Uploading all changes to Google Play...
/Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/interface.rb:146:in `user_error!': [!] Google Api Error: publishingDailySaveQuotaExceeded: Daily save quota exceeded. (FastlaneCore::Interface::FastlaneError)
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/supply/lib/supply/client.rb:362:in `rescue in call_google_api'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/supply/lib/supply/client.rb:360:in `call_google_api'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/supply/lib/supply/client.rb:113:in `commit_current_edit!'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/supply/lib/supply/uploader.rb:36:in `perform_upload'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/supply/lib/supply/commands_generator.rb:59:in `run'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/supply/lib/supply/commands_generator.rb:12:in `start'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/bin/fastlane:20:in `<top (required)>'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/bin/fastlane:22:in `load'
	from /Users/xcodeserver/.rbenv/versions/2.4.0/bin/fastlane:22:in `<main>'
```

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.2                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.12.2 (16C68)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| faraday_middleware        | 0.11.0.1     |
| bundler                   | 1.14.3       |
</details>


*generated on:* **2017-03-30**
</details>
```

**Comment by jeffc-kpcc** [comment]
BTW, when I set DEBUG = 1 and run the upload I get a number of 500 error responses on the 'commit' calls before it fails.
