### ISSUE TITLE
[Regression] 784: unexpected token at 'Bad Request' reintroduced in 2.19

### ISSUE THREAD

**Issue by casz** [fastlane/fastlane#8409]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

2.19 Gives Bad Request while 2.18.3 works
Guessing #8359 or #8363 changed something

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane ios development

WARN [2017-03-01 18:28:39.57]: Creating new provisioning profile for 'beep' with name 'match Development beep' for 'ios' platform
WARN [2017-03-01 18:28:43.37]: Lane Context:
INFO [2017-03-01 18:28:43.37]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios development"}
ERROR [2017-03-01 18:28:43.37]: 784: unexpected token at 'Bad Request'
INFO [2017-03-01 18:28:43.37]: Successfully generated documentation at path

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 3           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 💥   | match                               | 23          |
+------+-------------------------------------+-------------+

ERROR [2017-03-01 18:28:43.37]: fastlane finished with errors

/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse': [!] 784: unexpected token at 'Bad Request' (Faraday::ParsingError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:50:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `post'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/spaceship/lib/spaceship/client.rb:534:in `block in send_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/spaceship/lib/spaceship/client.rb:386:in `with_retry'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/spaceship/lib/spaceship/client.rb:533:in `send_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/spaceship/lib/spaceship/client.rb:430:in `request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/spaceship/lib/spaceship/portal/portal_client.rb:507:in `create_provisioning_profile!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:250:in `block in create!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/spaceship/lib/spaceship/client.rb:386:in `with_retry'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:249:in `create!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/sigh/lib/sigh/runner.rb:131:in `create_profile!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/sigh/lib/sigh/runner.rb:35:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/sigh/lib/sigh/manager.rb:7:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/match/lib/match/generator.rb:68:in `generate_provisioning_profile'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/match/lib/match/runner.rb:130:in `fetch_provisioning_profile'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/match/lib/match/runner.rb:40:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/match/lib/match/runner.rb:39:in `loop'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/match/lib/match/runner.rb:39:in `block in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/match/lib/match/runner.rb:38:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/match/lib/match/runner.rb:38:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/actions/match.rb:8:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:49:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

```
default_platform :ios

platform :ios do
  before_all do
    ENV['GIT_URL'] = 'gitty'
  end

  lane :development do |options|
    match(
      git_url: ENV['GIT_URL'],
      git_branch: "someBranch",
      type: 'development',
      username: '',
      team_id: '',
      team_name: '',
      app_identifier: '',
      force_for_new_devices: true
    )
  end
end
```

**Comment by tabrindle** [comment]
Have a similar issue `[12:41:29]: 776: unexpected token at 'Bad Request'`

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1                          |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Is homebrew         | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.18.3"

default_platform :ios

app_name = "Shopping Annuity"
app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

platform :ios do

  lane :development_profiles do
    match(type: 'development', app_identifier: "#{app_identifier}")
  end

  lane :appstore_profiles do
    match(type: 'appstore', app_identifier: "#{app_identifier}")
  end

  lane :profiles do
    development_profiles
    appstore_profiles
  end

  lane :build_development do
    if is_ci?
      unlock_keychain
    end
    development_profiles
    gym(
      configuration: "Debug",
      output_name: "#{app_name}-development.ipa"
    )
  end

  lane :build_release do
    if is_ci?
      unlock_keychain
    end
    appstore_profiles
    gym(
      configuration: "Release",
      output_name: "#{app_name}-release.ipa"
    )
  end

  lane :hockeyapp do |options|
    hockey(
      ipa: "builds/#{Time.now.strftime('%F')}/#{app_name}-#{(options[:release] ? "release" : "development")}.ipa",
      dsym: "builds/#{Time.now.strftime('%F')}/#{app_name}-#{(options[:release] ? "release" : "development")}.app.dSYM.zip",
      api_token: "2e2f1260692140dba94474a4b66e9a56",
      notes: "Build " + (ENV["BUILD_NUMBER"] ? ENV["BUILD_NUMBER"] + " " : "") + "From " + git_branch + " branch on " + Time.now.strftime('%F') + " at " + Time.now.strftime('%T'),
      notify: "0"
    )
  end

  lane :ci do
    build_development
    hockeyapp
  end

  lane :beta do
    build_release
    pilot
  end

  lane :release do
    deliver(
      ipa: "builds/#{Time.now.strftime('%F')}/#{app_name}-release.ipa",
      force: true,
      skip_metadata: true,
      skip_screenshots: true
    )
  end

  lane :screenshots do
    deliver(
      skip_binary_upload: true
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end

platform :android do

  lane :build_development do
    Dir.chdir ".." do
      sh("platforms/android/cordova/clean")
    end
    gradle(
      task: "cdvBuildDebug",
      project_dir: "platforms/android/",
      properties: {
        'android.useDeprecatedNdk' => true
      }
    )
    Dir.chdir ".." do
      sh("mkdir -p builds/#{Time.now.strftime('%F')}/")
      sh("cp -f platforms/android/build/outputs/apk/android-armv7-debug.apk builds/#{Time.now.strftime('%F')}/")
      sh("cp -f platforms/android/build/outputs/apk/android-x86-debug.apk builds/#{Time.now.strftime('%F')}/")
    end
  end

  lane :build_release do
    Dir.chdir ".." do
      sh("platforms/android/cordova/clean")
    end
    gradle(
      task: "cdvBuildRelease",
      project_dir: "platforms/android/",
      properties: {
        'android.useDeprecatedNdk' => true
      }
    )
    Dir.chdir ".." do
      sh("mkdir -p builds/#{Time.now.strftime('%F')}/")
      sh("cp -f platforms/android/build/outputs/apk/android-armv7-release.apk builds/#{Time.now.strftime('%F')}/")
      sh("cp -f platforms/android/build/outputs/apk/android-x86-release.apk builds/#{Time.now.strftime('%F')}/")
    end
  end

  lane :hockeyapp do |options|
    hockey(
      apk: "builds/#{Time.now.strftime('%F')}/android-armv7-#{(options[:release] ? "release" : "debug")}.apk",
      api_token: "2e2f1260692140dba94474a4b66e9a56",
      notes: "Build " + (ENV["BUILD_NUMBER"] ? ENV["BUILD_NUMBER"] + " " : "") + "From " + git_branch + " branch on " + Time.now.strftime('%F') + " at " + Time.now.strftime('%T'),
      notify: "0"
    )
  end

  lane :release do |options|
    supply(
      track: options[:track],
      apk_paths: ["builds/#{Time.now.strftime('%F')}/android-x86-release.apk", "builds/#{Time.now.strftime('%F')}/android-armv7-release.apk"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  lane :ci do
    build_development
    hockeyapp
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.marketamerica.shoppingannuity"
apple_id "mobile@marketamerica.com"
json_key_file "fastlane/.playstore_key.json"
package_name "com.marketamerica.shoppingannuity"
team_id "N773NSP5U4"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-03-01**
</details>

**Comment by asfalcone** [comment]
Thanks for submitting. This seems related to #8408. We're taking a look now!
