### ISSUE TITLE
UTF-8 issue in deliver

### ISSUE THREAD

**Issue by peterklima** [fastlane/fastlane#8422]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Running "deliver run -u ㊙️ -a ㊙️ -z ㊙️ --skip_binary_upload --automatic_release true --skip_screenshots": it complains about an UTF-8 issue?

##### Complete output when running fastlane, including the stack trace and command used

```
$ deliver run -u ㊙️ -a ㊙️     -z ㊙️     --skip_binary_upload     --automatic_release true     --skip_screenshots
[09:45:53]: Successfully loaded '/Users/㊙️/git/㊙️/source_code/fastlane/Deliverfile' 📄
[09:45:53]: No values defined in './fastlane/Deliverfile'
[09:45:53]: Login to iTunes Connect (㊙️)
[09:45:56]: Login successful

+-----------------------+------------------------+
|             deliver 2.19.1 Summary             |
+-----------------------+------------------------+
| username              | ㊙️                     |
| app_identifier        | ㊙️                     |
| app_version           | ㊙️                     |
| skip_binary_upload    | true                   |
| automatic_release     | true                   |
| skip_screenshots      | true                   |
| screenshots_path      | ./fastlane/screenshots |
| metadata_path         | ./fastlane/metadata    |
| edit_live             | false                  |
| platform              | ios                    |
| skip_metadata         | false                  |
| force                 | false                  |
| submit_for_review     | false                  |
| dev_portal_team_id    | ㊙️                     |
| overwrite_screenshots | false                  |
+-----------------------+------------------------+

[09:45:58]: Making sure the latest version on iTunes Connect matches '㊙️' from the ipa file...
[09:46:01]: '㊙️' is the latest version on iTunes Connect
[09:46:01]: Loading './fastlane/metadata/de-DE/description.txt'...
[09:46:01]: Loading './fastlane/metadata/de-DE/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/de-DE/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/de-DE/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/de-DE/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/de-DE/name.txt'...
[09:46:01]: Loading './fastlane/metadata/de-DE/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-AU/description.txt'...
[09:46:01]: Loading './fastlane/metadata/en-AU/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/en-AU/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/en-AU/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-AU/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-AU/name.txt'...
[09:46:01]: Loading './fastlane/metadata/en-AU/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-CA/description.txt'...
[09:46:01]: Loading './fastlane/metadata/en-CA/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/en-CA/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/en-CA/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-CA/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-CA/name.txt'...
[09:46:01]: Loading './fastlane/metadata/en-CA/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-GB/description.txt'...
[09:46:01]: Loading './fastlane/metadata/en-GB/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/en-GB/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/en-GB/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-GB/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-GB/name.txt'...
[09:46:01]: Loading './fastlane/metadata/en-GB/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-US/description.txt'...
[09:46:01]: Loading './fastlane/metadata/en-US/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/en-US/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/en-US/name.txt'...
[09:46:01]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/es-ES/description.txt'...
[09:46:01]: Loading './fastlane/metadata/es-ES/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/es-ES/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/es-ES/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/es-ES/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/es-ES/name.txt'...
[09:46:01]: Loading './fastlane/metadata/es-ES/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/es-MX/description.txt'...
[09:46:01]: Loading './fastlane/metadata/es-MX/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/es-MX/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/es-MX/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/es-MX/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/es-MX/name.txt'...
[09:46:01]: Loading './fastlane/metadata/es-MX/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-CA/description.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-CA/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-CA/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-CA/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-CA/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-CA/name.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-CA/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-FR/description.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-FR/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-FR/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-FR/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-FR/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-FR/name.txt'...
[09:46:01]: Loading './fastlane/metadata/fr-FR/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/it/description.txt'...
[09:46:01]: Loading './fastlane/metadata/it/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/it/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/it/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/it/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/it/name.txt'...
[09:46:01]: Loading './fastlane/metadata/it/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-BR/description.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-BR/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-BR/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-BR/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-BR/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-BR/name.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-BR/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-PT/description.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-PT/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-PT/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-PT/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-PT/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-PT/name.txt'...
[09:46:01]: Loading './fastlane/metadata/pt-PT/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/ru/description.txt'...
[09:46:01]: Loading './fastlane/metadata/ru/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/ru/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/ru/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/ru/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/ru/name.txt'...
[09:46:01]: Loading './fastlane/metadata/ru/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/th/description.txt'...
[09:46:01]: Loading './fastlane/metadata/th/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/th/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/th/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/th/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/th/name.txt'...
[09:46:01]: Loading './fastlane/metadata/th/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/zh-Hans/description.txt'...
[09:46:01]: Loading './fastlane/metadata/zh-Hans/keywords.txt'...
[09:46:01]: Loading './fastlane/metadata/zh-Hans/release_notes.txt'...
[09:46:01]: Loading './fastlane/metadata/zh-Hans/support_url.txt'...
[09:46:01]: Loading './fastlane/metadata/zh-Hans/marketing_url.txt'...
[09:46:01]: Loading './fastlane/metadata/zh-Hans/name.txt'...
[09:46:01]: Loading './fastlane/metadata/zh-Hans/privacy_url.txt'...
[09:46:01]: Loading './fastlane/metadata/copyright.txt'...
[09:46:01]: Loading './fastlane/metadata/primary_category.txt'...
[09:46:01]: Loading './fastlane/metadata/secondary_category.txt'...
[09:46:01]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[09:46:01]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[09:46:01]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[09:46:01]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[09:46:01]: #<ArgumentError: invalid byte sequence in UTF-8>
[09:46:01]: /Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/html_generator.rb:55:in `split'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/html_generator.rb:55:in `split_keywords'
(erb):173:in `block in render'
(erb):146:in `each'
(erb):146:in `render'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/2.2.0/erb.rb:863:in `eval'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/2.2.0/erb.rb:863:in `result'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/html_generator.rb:44:in `render'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/html_generator.rb:10:in `run'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/runner.rb:115:in `validate_html'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/runner.rb:59:in `upload_metadata'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/runner.rb:21:in `run'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/commands_generator.rb:63:in `block (2 levels) in run'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/commands_generator.rb:164:in `run'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/deliver/lib/deliver/commands_generator.rb:12:in `start'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
/Users/㊙️/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/bin/fastlane:15:in `<top (required)>'
/Users/㊙️/.fastlane/bin/bundle/bin/fastlane:22:in `load'
/Users/㊙️/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

I run directly deliver, as described in the issue above.

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.2.6   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| CFPropertyList             | 2.3.5        |
| activesupport              | 4.2.7.1      |
| addressable                | 2.5.0        |
| babosa                     | 1.0.2        |
| bigdecimal                 | 1.2.6        |
| bundler                    | 1.14.3       |
| claide                     | 1.0.1        |
| cocoapods                  | 1.2.0        |
| cocoapods-core             | 1.2.0        |
| cocoapods-deintegrate      | 1.0.1        |
| cocoapods-downloader       | 1.1.3        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.0.0        |
| cocoapods-trunk            | 1.1.2        |
| cocoapods-try              | 1.1.0        |
| colored                    | 1.2          |
| commander                  | 4.4.3        |
| domain_name                | 0.5.20161129 |
| dotenv                     | 2.2.0        |
| escape                     | 0.0.4        |
| excon                      | 0.54.0       |
| faraday                    | 0.11.0       |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.11.0.1     |
| fastimage                  | 2.0.1        |
| fastlane-plugin-versioning | 0.2.6        |
| fourflusher                | 2.0.1        |
| fuzzy_match                | 2.0.4        |
| gh_inspector               | 1.0.3        |
| google-api-client          | 0.9.26       |
| googleauth                 | 0.5.1        |
| highline                   | 1.7.8        |
| http-cookie                | 1.0.3        |
| httpclient                 | 2.8.3        |
| hurley                     | 0.2          |
| i18n                       | 0.7.0        |
| io-console                 | 0.4.3        |
| json                       | 1.8.1        |
| jwt                        | 1.5.6        |
| libxml-ruby                | 2.9.0        |
| little-plugger             | 1.1.4        |
| logging                    | 2.1.0        |
| memoist                    | 0.15.0       |
| mime-types                 | 3.1          |
| mime-types-data            | 3.2016.0521  |
| mini_magick                | 4.5.1        |
| minitest                   | 5.4.3        |
| molinillo                  | 0.5.6        |
| multi_json                 | 1.12.1       |
| multi_xml                  | 0.6.0        |
| multipart-post             | 2.0.0        |
| nanaimo                    | 0.2.3        |
| nap                        | 1.1.0        |
| netrc                      | 0.7.8        |
| nokogiri                   | 1.5.6        |
| os                         | 0.9.6        |
| plist                      | 3.2.0        |
| power_assert               | 0.2.2        |
| psych                      | 2.0.8        |
| public_suffix              | 2.0.5        |
| rake                       | 10.4.2       |
| rdoc                       | 4.2.0        |
| representable              | 2.3.0        |
| retriable                  | 2.1.0        |
| rouge                      | 1.11.1       |
| ruby-macho                 | 0.2.6        |
| rubygems-update            | 2.5.2        |
| rubyzip                    | 1.2.0        |
| security                   | 0.1.3        |
| signet                     | 0.7.3        |
| slack-notifier             | 1.5.1        |
| sqlite3                    | 1.3.13       |
| terminal-notifier          | 1.7.1        |
| terminal-table             | 1.7.3        |
| test-unit                  | 3.0.8        |
| thread_safe                | 0.3.5        |
| tty-screen                 | 0.5.0        |
| tzinfo                     | 1.2.2        |
| uber                       | 0.0.15       |
| unf                        | 0.1.4        |
| unf_ext                    | 0.0.7.2      |
| unicode-display_width      | 1.1.3        |
| word_wrap                  | 1.0.0        |
| xcodeproj                  | 1.4.2        |
| xcpretty                   | 0.2.4        |
| xcpretty-travis-formatter  | 0.0.4        |
</details>

*generated on:* **2017-03-02**
</details>

**Comment by ohayon** [comment]
Hey @peterklima, thanks for raising the issue! Would you mind sharing a bit more of the output from your terminal to give some more context we can look at? Thanks! 🐙

**Comment by peterklima** [comment]
Since it is failing while uploading meta data to the App Store I compressed you the metadata.
[metadata.zip](https://github.com/fastlane/fastlane/files/816243/metadata.zip)
