### ISSUE TITLE
fastlane finished with errors

### ISSUE THREAD

**Issue by lycaste** [fastlane/fastlane#844]
when i build the [code](https://github.com/artsy/eidolon) there always some errors.
so how i can slove these problem...it  perplex me for a lone time

```
 [SHELL]: ### Error
[13:09:42]: [SHELL]: 
[13:09:42]: [SHELL]: ```
[13:09:42]: [SHELL]: NoMethodError - undefined method `[]' for false:FalseClass
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/keyring.rb:14:in `from_hash'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/keyring_liberator.rb:68:in `get_keyring_at_path'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/keyring_liberator.rb:60:in `block in get_all_keyrings'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/keyring_liberator.rb:59:in `each'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/keyring_liberator.rb:59:in `get_all_keyrings'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/keyring_liberator.rb:28:in `get_current_keyring'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/pod/command/keys.rb:29:in `get_current_keyring'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/pod/command/keys/set.rb:41:in `run'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
[13:09:42]: [SHELL]: /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
[13:09:42]: [SHELL]: /usr/local/bin/pod:23:in `load'
[13:09:42]: [SHELL]: /usr/local/bin/pod:23:in `<main>'
[13:09:42]: [SHELL]: ```
[13:09:42]: [SHELL]: 
[13:09:42]: [SHELL]: ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[13:09:42]: [SHELL]: 
[13:09:42]: [SHELL]: [!] Oh no, an error occurred.
[13:09:42]: [SHELL]: 
[13:09:42]: [SHELL]: Search for existing GitHub issues similar to yours:
[13:09:42]: [SHELL]: https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%5B%5D%27+for+false%3AFalseClass&type=Issues
[13:09:42]: [SHELL]: 
[13:09:42]: [SHELL]: If none exists, create a ticket, with the template displayed above, on:
[13:09:42]: [SHELL]: https://github.com/CocoaPods/CocoaPods/issues/new
[13:09:42]: [SHELL]: 
[13:09:42]: [SHELL]: Be sure to first read the contributing guide for details on how to properly submit a ticket:
[13:09:42]: [SHELL]: https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
[13:09:42]: [SHELL]: 
[13:09:42]: [SHELL]: Don't forget to anonymize any private data!
[13:09:42]: [SHELL]: 
[13:09:42]: Unable to deploy, resetting git repository.
[13:09:42]: -----------------------------------
[13:09:42]: --- Step: clean_build_artifacts ---
[13:09:42]: -----------------------------------
[13:09:42]: Cleaned up build artifacts 🐙
[13:09:42]: ----------------------------
[13:09:42]: --- Step: reset_git_repo ---
[13:09:42]: ----------------------------
[13:09:42]: Variable Dump:
[13:09:42]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"oss"}
[13:09:42]: This is a destructive and potentially dangerous action. To protect from data loss, please add the `ensure_git_status_clean` action to the beginning of your lane, or if you're absolutely sure of what you're doing then call this action with the :force option.

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | cd .. ; bundle exec pod keys set ArtsyAPIClientSecret '-' Eid | 19          |
| 3    | clean_build_artifacts                                         | 0           |
| 4    | reset_git_repo                                                | 0           |
+------+---------------------------------------------------------------+-------------+

[13:09:42]: fastlane finished with errors
```

**Comment by KrauseFx** [comment]
Mentioning @ashfurrow @orta to jump in here, it looks like that's not an `fastlane` issue but a `cocoapods-keys` thing.

**Comment by orta** [comment]
I think I fixed this, try updating to `1.6.0` for keys

**Comment by lycaste** [comment]
There is something wrong with the ruby,i update my ruby ,its ok now

**Comment by KrauseFx** [comment]
Oh yeah, thanks @orta
