### ISSUE TITLE
undefined local variable or method `cert' for #<Sigh::Runner:...>

### ISSUE THREAD

**Issue by kas-kad** [fastlane/fastlane#8456]
### New Issue Checklist

- [yes] Updated fastlane to the latest version
- [no] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
$ fastlane sigh --development

+-------------------------------------+-------------------------------------+
|                          Summary for sigh 2.19.2                          |
+-------------------------------------+-------------------------------------+
| development                         | true                                |
| adhoc                               | false                               |
| skip_install                        | false                               |
| force                               | false                               |
| app_identifier                      | com.myapp 							|
| team_id                             | T6U248P7YM                          |
| ignore_profiles_with_different_name | false                               |
| skip_fetch_profiles                 | false                               |
| skip_certificate_verification       | false                               |
| platform                            | ios                                 |
+-------------------------------------+-------------------------------------+

[11:51:44]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: mymail@mymail.com
[11:51:51]: Starting login with user 'mymail@mymail.com'
[11:51:54]: Successfully logged in
[11:51:54]: Fetching profiles...
[11:51:55]: Verifying certificates...

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined local variable or method `cert' for #<Sigh::Runner:...>
   https://github.com/fastlane/fastlane/issues/8456 [open] 0 💬
   17 minutes ago

➡️  undefined method `[]=' for nil:NilClass for sigh manage
   https://github.com/fastlane/fastlane/issues/6751 [closed] 15 💬
   4 weeks ago

➡️  Undefined method `fetch` for nil:NilClass (NoMethodError) again?
   https://github.com/fastlane/fastlane/issues/7307 [closed] 4 💬
   3 weeks ago

and 34 more at: https://github.com/fastlane/fastlane/search?q=undefined%20%60cert'%20for%20Sigh::Runner&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/runner.rb:126:in `block (2 levels) in fetch_profiles': [!] undefined local variable or method `cert' for #<Sigh::Runner:0x007f8caaa520b0> (NameError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/runner.rb:119:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/runner.rb:119:in `block in fetch_profiles'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/runner.rb:101:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/runner.rb:101:in `find_all'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/runner.rb:101:in `fetch_profiles'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/runner.rb:20:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/manager.rb:7:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/commands_generator.rb:55:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/commands_generator.rb:123:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.19.2/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.5                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.11.5 (15F34)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-wait_xcrun | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version |
| -------------------------- | ------- |
| did_you_mean               | 1.0.0   |
| slack-notifier             | 1.5.1   |
| claide                     | 1.0.1   |
| colored                    | 1.2     |
| nanaimo                    | 0.2.3   |
| xcodeproj                  | 1.4.2   |
| rouge                      | 1.11.1  |
| xcpretty                   | 0.2.4   |
| terminal-notifier          | 1.7.1   |
| unicode-display_width      | 1.1.3   |
| terminal-table             | 1.7.3   |
| plist                      | 3.2.0   |
| public_suffix              | 2.0.5   |
| addressable                | 2.5.0   |
| multipart-post             | 2.0.0   |
| word_wrap                  | 1.0.0   |
| tty-screen                 | 0.5.0   |
| babosa                     | 1.0.2   |
| highline                   | 1.7.8   |
| commander                  | 4.4.3   |
| faraday                    | 0.11.0  |
| http-cookie                | 1.0.3   |
| faraday-cookie_jar         | 0.0.6   |
| gh_inspector               | 1.0.3   |
| mini_magick                | 4.5.1   |
| multi_json                 | 1.12.1  |
| multi_xml                  | 0.6.0   |
| security                   | 0.1.3   |
| xcpretty-travis-formatter  | 0.0.4   |
| bundler                    | 1.13.5  |
| json                       | 2.0.3   |
| io-console                 | 0.4.5   |
| excon                      | 0.55.0  |
| rubyzip                    | 1.2.1   |
| fastlane-plugin-wait_xcrun | 0.1.1   |
</details>

*generated on:* **2017-03-07**
</details>

**Comment by kas-kad** [comment]
the commit that broke things:
https://github.com/fastlane/fastlane/commit/1e7b08032d9e030c998cf65c7fc7256beb6ce5fa

**Comment by hjanuschka** [comment]
this PR https://github.com/fastlane/fastlane/pull/8394 @joshdholtz can you have a look ? looks like `cert` is not defined in this case.

**Comment by hjanuschka** [comment]
@kas-kad i prepared a PR: https://github.com/fastlane/fastlane/pull/8457 could you give it a try?

**Comment by kas-kad** [comment]
@hjanuschka 
now it's better
```

+-------------------------------------+-------------------------------------+
|                          Summary for sigh 2.19.2                          |
+-------------------------------------+-------------------------------------+
| development                         | true                                |
| adhoc                               | false                               |
| skip_install                        | false                               |
| force                               | false                               |
| app_identifier                      | com.infobip.mobilemessaging.example |
| team_id                             | T6U248P7YM                          |
| ignore_profiles_with_different_name | false                               |
| skip_fetch_profiles                 | false                               |
| skip_certificate_verification       | false                               |
| platform                            | ios                                 |
+-------------------------------------+-------------------------------------+

[12:26:28]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: kadochnikov.andr@gmail.com
[12:26:35]: Starting login with user 'kadochnikov.andr@gmail.com'
[12:26:40]: Successfully logged in
[12:26:40]: Fetching profiles...
[12:26:41]: Verifying certificates...
[12:26:48]: Certificate for Provisioning Profile 'Mobile Messaging Example - Development' not available locally: D8HLFR9G6T, skipping this one...
[12:26:48]: Certificate for Provisioning Profile 'Mobile Messaging Example - Development' not available locally: 62NRV5PBES, skipping this one...
[12:26:49]: Certificate for Provisioning Profile 'Mobile Messaging Example - Development' not available locally: 528498GTG5, skipping this one...
[12:26:49]: Certificate for Provisioning Profile 'Mobile Messaging Example - Development' not available locally: E345RE9WRX, skipping this one...
[12:26:49]: Certificate for Provisioning Profile 'Mobile Messaging Example - Development' not available locally: U5VVSCF3TG, skipping this one...
[12:26:50]: Certificate for Provisioning Profile 'Mobile Messaging Example - Development' not available locally: 2GG4P54QQK, skipping this one...
[12:26:53]: Cannot download cert X4XHH93295 - Couldn't download certificate, got this instead: {"responseId"=>"80def118-52ef-472f-9695-20b6fde1efc5", "resultCode"=>7100, "resultString"=>"Certificate 'X4XHH93295' not found", "userString"=>"There is no certificate with ID 'X4XHH93295' on this team.", "creationTimestamp"=>"2017-03-07T12:26:53Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/downloadCertificateContent.action", "httpCode"=>200}
[12:26:54]: Cannot download cert H29YDV5Z7X - Couldn't download certificate, got this instead: {"responseId"=>"e6a769ec-6e96-4048-9a3c-8aadd09b2926", "resultCode"=>7100, "resultString"=>"Certificate 'H29YDV5Z7X' not found", "userString"=>"There is no certificate with ID 'H29YDV5Z7X' on this team.", "creationTimestamp"=>"2017-03-07T12:26:54Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/downloadCertificateContent.action", "httpCode"=>200}
[12:26:57]: Certificate for Provisioning Profile 'com.infobip.mobilemessaging.example Development' not available locally: D8HLFR9G6T, skipping this one...
[12:26:57]: Certificate for Provisioning Profile 'com.infobip.mobilemessaging.example Development' not available locally: 62NRV5PBES, skipping this one...
[12:26:58]: Certificate for Provisioning Profile 'com.infobip.mobilemessaging.example Development' not available locally: 528498GTG5, skipping this one...
[12:26:58]: Certificate for Provisioning Profile 'com.infobip.mobilemessaging.example Development' not available locally: E345RE9WRX, skipping this one...
[12:26:58]: Found 1 matching profile(s)
[12:26:58]: Downloading provisioning profile...
[12:27:01]: Successfully downloaded provisioning profile...
[12:27:01]: Installing provisioning profile...
```

**Comment by hjanuschka** [comment]
@kas-kad  many thx for your help - working on adding a spec for the PR

**Comment by KrauseFx** [comment]
This should be resolved now 👍  Thanks everybody
