### ISSUE TITLE
make_changelog_from_jenkins failing on Jenkins on line 12

### ISSUE THREAD

**Issue by freynolds** [fastlane/fastlane#8476]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/make_changelog_from_jenkins.rb

make_changelog_from_jenkins failing on Jenkins, It fails in line 12

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
Started by user Apps
Building in workspace ...
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@bitbucket.org:....git # timeout=10
Fetching upstream changes from git@bitbucket.org:....git
 > git --version # timeout=10
 > git fetch --tags --progress git@bitbucket.org:....git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/.../^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/.../^{commit} # timeout=10
Checking out Revision ... (refs/remotes/origin/...)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ...
 > git rev-list ... # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.*)\.url # timeout=10
 > git config --get submodule. SDK.url # timeout=10
 > git config -f .gitmodules --get submodule. SDK.path # timeout=10
 > git submodule update --init --recursive  SDK
 > git config --get submodule. History SDK.url # timeout=10
 > git config -f .gitmodules --get submodule.  SDK.path # timeout=10
 > git submodule update --init --recursive   SDK
[...] $ /bin/sh -xe /var/folders/wm/zpmrb2t92n90xzsm96lftrz40000gn/T/hudson863588814265463097.sh
+ fastlane buildci
[16:04:17]: [32m-------------------------------------------------[0m
[16:04:17]: [32m--- Step: Verifying required fastlane version ---[0m
[16:04:17]: [32m-------------------------------------------------[0m
[16:04:17]: Your fastlane version 2.19.3 matches the minimum requirement of 1.59.0  ✅
[16:04:17]: [32m------------------------------[0m
[16:04:17]: [32m--- Step: default_platform ---[0m
[16:04:17]: [32m------------------------------[0m
[16:04:17]: [31mName of the lane 'appstore' is already taken by the action named 'appstore'[0m
[16:04:17]: [32mDriving the lane 'ios buildci' 🚀[0m
[16:04:17]: [32m-------------------------------------[0m
[16:04:17]: [32m--- Step: ensure_git_status_clean ---[0m
[16:04:17]: [32m-------------------------------------[0m
[16:04:17]: [32mGit status is clean, all good! 💪[0m
[16:04:17]: [32m------------------------------[0m
[16:04:17]: [32m--- Step: recreate_schemes ---[0m
[16:04:17]: [32m------------------------------[0m
[16:04:17]: Recreate schemes for project: ....xcodeproj
[16:04:17]: [32m------------------------------------[0m
[16:04:17]: [32m--- Step: increment_build_number ---[0m
[16:04:17]: [32m------------------------------------[0m
[16:04:17]: [4m[36m$ agvtool new-version -all 2017.03.08.16.04 && cd -[0m[0m
[16:04:18]: ▸ [35mSetting version of project ... to:[0m
[16:04:18]: ▸ [35m2017.03.08.16.04.[0m
[16:04:18]: ▸ [35mAlso setting CFBundleVersion key (assuming it exists)[0m
[16:04:18]: ▸ [35mUpdating CFBundleVersion in Info.plist(s)...[0m
[16:04:18]: ▸ [35mUpdated CFBundleVersion in "....xcodeproj/../...UITests/Info.plist" to 2017.03.08.16.04[0m
[16:04:18]: ▸ [35mUpdated CFBundleVersion in "....xcodeproj/../.../Info.plist" to 2017.03.08.16.04[0m
[16:04:18]: ▸ [35mUpdated CFBundleVersion in "....xcodeproj/../...Tests/Info.plist" to 2017.03.08.16.04[0m
[16:04:18]: ▸ [35m/.../a[0m
[16:04:18]: [32m-----------------------------------------[0m
[16:04:18]: [32m--- Step: make_changelog_from_jenkins ---[0m
[16:04:18]: [32m-----------------------------------------[0m
[16:04:18]: [32m--------------------------[0m
[16:04:18]: [32m--- Step: notification ---[0m
[16:04:18]: [32m--------------------------[0m
+-----------------------------+------------------+
|                  [33mLane Context[0m                  |
+-----------------------------+------------------+
| DEFAULT_PLATFORM            | ios              |
| PLATFORM_NAME               | ios              |
| LANE_NAME                   | ios buildci      |
| GIT_REPO_WAS_CLEAN_ON_START | true             |
| BUILD_NUMBER                | 2017.03.08.16.04 |
+-----------------------------+------------------+
[16:04:18]: [31mundefined method `+' for nil:NilClass[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ensure_git_status_clean             | 0           |
| 4    | recreate_schemes                    | 0           |
| 5    | increment_build_number              | 0           |
| 💥   | [31mmake_changelog_from_jenkins[0m         | 0           |
| 7    | notification                        | 0           |
+------+-------------------------------------+-------------+

[16:04:18]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mundefined method `id' for nil:NilClass while fastlane sigh repair[0m
   https://github.com/fastlane/fastlane/issues/8184 [[31mopen[0m] 3 💬
   a week ago

➡️  [33mundefined local variable or method `cert' for #<Sigh::Runner:...>[0m
   https://github.com/fastlane/fastlane/issues/8456 [[31mopen[0m] 5 💬
   a day ago

➡️  [33m[!] undefined method `sub' for nil:NilClass (NoMethodError)[0m
   https://github.com/fastlane/fastlane/issues/8426 [[32mclosed[0m] 5 💬
   8 hours ago

and 220 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60+'%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/make_changelog_from_jenkins.rb:12:in `run': [31m[!] undefined method `+' for nil:NilClass[0m (NoMethodError)
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:211:in `block (2 levels) in parsing_binding'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /Users/.../.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
	from /Users/.../.rbenv/versions/2.4.0/bin/fastlane:22:in `load'
	from /Users/.../.rbenv/versions/2.4.0/bin/fastlane:22:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.3                                           |
| Ruby                        | 2.4.0                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.10.1 (Apple Git-78)                 |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane              |
| Host                        | Mac OS X 10.12.3 (16D32)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-8.2.1.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.59.0"

default_platform :ios

platform :ios do
  before_all do
    skip_docs
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

 

  lane :buildci do
    ensure_git_status_clean()

    beta_app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

    recreate_schemes(project: "....xcodeproj")

    build_number = Time.new.strftime("%Y.%m.%d.%H.%M")
    increment_build_number build_number: build_number

    changelog = make_changelog_from_jenkins(include_commit_body:true)

    match(
      type:"adhoc",
      app_identifier: beta_app_identifier,
      force: true
    )

    ENV["PROFILE_UDID"] = ENV["sigh_" + beta_app_identifier + "_adhoc"]

    # Build and sign your app
    xcversion(version: "8.2.1")
    gym(output_directory: "dist",
      silent: true,
      suppress_xcode_output: true,
      scheme: "...")

    # Distribute via Crashlytics
    crashlytics(
        api_token: '...',
        build_secret: '...',
        notes: "Version prod CI\nChange Log:\n" + changelog,
        groups: "...",
        notifications: false)

    reset_git_repo(force: true)

  end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com....." # The bundle identifier of your app
apple_id "apps@....com" # Your Apple email address

team_id "..."  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-03-08**
</details>

**Comment by hjanuschka** [comment]
took me a while to figure out 👍 


irb:
```
2.3.0 :004 > b = ENV["AAAA"] + "123"
NoMethodError: undefined method `+' for nil:NilClass
	from (irb):4
	from /Users/hjanuschka/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

can you check that jenkins sets `BUILD_URL` ? seems like it is not set.

**Comment by freynolds** [comment]
Thanks @hjanuschka for your response!
Setting that global env solved that.

Now I'm getting an error of auth of jenkins, I'm going to use this https://github.com/fastlane/fastlane/issues/1348#issuecomment-268384192 solution! 

My regards
