### ISSUE TITLE
sigh: `block in load_profiles': [!] undefined method `[]=' for nil:NilClass

### ISSUE THREAD

**Issue by j2kun** [fastlane/fastlane#8494]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`fastlane sigh manage` fails to load provisioning profiles.

### Captured Output

```
$ fastlane sigh manage
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[12:05:44]: Loading Provisioning profiles from ~/Library/MobileDevice/Provisioning Profiles/

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `id' for nil:NilClass while fastlane sigh repair
   https://github.com/fastlane/fastlane/issues/8184 [open] 3 💬
   a week ago

➡️  undefined method `install_gem' for #<Gem::Commands::InstallCommand
   https://github.com/fastlane/fastlane/issues/8489 [open] 1 💬
   2 hours ago

➡️  undefined local variable or method `cert' for #<Sigh::Runner:...>
   https://github.com/fastlane/fastlane/issues/8456 [open] 5 💬
   3 days ago

and 222 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]='%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/jenkins/.gems/gems/fastlane-2.19.3/sigh/lib/sigh/local_manage.rb:131:in `block in load_profiles': [!] undefined method `[]=' for nil:NilClass (NoMethodError)
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/sigh/lib/sigh/local_manage.rb:129:in `each'
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/sigh/lib/sigh/local_manage.rb:129:in `load_profiles'
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/sigh/lib/sigh/local_manage.rb:46:in `list_profiles'
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/sigh/lib/sigh/local_manage.rb:9:in `start'
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/sigh/lib/sigh/commands_generator.rb:117:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/sigh/lib/sigh/commands_generator.rb:123:in `run'
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	from /Users/jenkins/.gems/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.3                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.10.1 (Apple Git-78)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

fastlane_version "2.14.2"
default_platform :ios

before_all do 
  update_fastlane
end

platform :ios do
  before_all do |lane, options|
    Actions.lane_context[SharedValues::VERSION_NUMBER] = get_version_number(xcodeproj: "ios/two1inbox.xcodeproj")
    Actions.lane_context[:DESCRIPTION] = changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
  end

  desc "Runs all the tests"
  lane :test do
    # sh "npm test"
    scan(configuration: "Release")
  end

  desc "Build and install on a USB-connected device in debug mode"
  lane :device_debug do
    match(type: "development", readonly: true)
    gym(configuration: "Debug", output_directory: "ios/build/Products/debug/", output_name: "21_debug.ipa")
    install_on_device(skip_wifi: true)
  end

  ########### CodePush ########### 
  
  desc "Codepush to the deployment given in options"
  lane :codepush_to do |options|
    codepush(
      app_name: 'two1inbox',
      dry_run: options[:dry_run],
      target_binary_version: Actions.lane_context[SharedValues::VERSION_NUMBER],
      deployment: options[:deployment],
      description: 'test' # Actions.lane_context[:DESCRIPTION] 
    )
  end

  desc "Codepush to 21 employees only"
  lane :codepush_staging do |options|
    codepush_to(deployment: 'alpha', **options)
  end

  desc "Codepush to prod"
  lane :codepush_prod do |options|
    codepush_to(deployment: 'prod', **options)
  end

  desc "Promote codepush deployment from staging to prod"
  lane :codepush_promote_staging_to_prod do |options|
    codepush_promote(
      app_name: 'two1inbox',
      dry_run: options[:dry_run],
      source_deployment: 'alpha',
      target_deployment: 'prod',
      description: Actions.lane_context[:DESCRIPTION] 
    )
  end

  ########### Deployments ########### 

  desc "Pre deployment actions"
  lane :pre_deploy do
    raise ArgumentError, 'Env missing CRASHLYTICS_BETA_API_KEY' unless ENV.key?('CRASHLYTICS_BETA_API_KEY')
    raise ArgumentError, 'Env missing CRASHLYTICS_BETA_BUILD_SECRET' unless ENV.key?('CRASHLYTICS_BETA_BUILD_SECRET')
  end

  desc "Post deployment actions"
  lane :post_deploy do
    clean_build_artifacts
  end

  desc "Deploy an alpha build to 21 employees only"
  lane :deploy_staging do |options|
    pre_deploy
    match(type: "development", readonly: true)
    gym(configuration: "Staging", output_directory: "ios/build/Products/staging/")

    crashlytics(  
      crashlytics_path: "./ios/Crashlytics.framework",
      api_token: ENV['CRASHLYTICS_BETA_API_KEY'],
      build_secret: ENV['CRASHLYTICS_BETA_BUILD_SECRET'],
      notes: 'test', # Actions.lane_context[:DESCRIPTION],
      groups: ["21-employees"],  # this value is the 'group alias' as found on the Fabric website
    )
    
    post_deploy
  end

  desc "Deploy a production build to the AppStore"
  lane :deploy_prod do |options|
    pre_deploy
    
    # bump & commit version number, and update shared variable

    match(type: "appstore", readonly: true)
    gym(configuration: "Release", output_directory: "ios/build/Products/release/")

    # tell this command where to find the JS bundle output by gym or just rebuild?
    # codepush_promote_staging_to_prod 

    # snap
    # deliver

    post_deploy
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# General config 
app_identifier ENV["APP_IDENTIFIER"] || "com.twentyone.two1mobile"
apple_id ENV['APPLE_ID'] || "Set your APPLE_ID in .env or .env.X invoke with --env X"
team_id "UDGT6TK344"  # Developer Portal Team ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-03-10**
</details>

**Comment by j2kun** [comment]
This may be related to the fact that I have what appears to be an invalid provisioning profile on my system:

```
$ ls -l ~/Library/MobileDevice/Provisioning\ Profiles/
-rw-r--r--  1 jenkins  staff  12460 Mar  1 12:31 UUID not found.mobileprovision
...
```

Not sure how that got there, but it appears to fix the problem.
