### ISSUE TITLE
pilot action failed. Possibly because of two iTunes Connect teams.

### ISSUE THREAD

**Issue by larryonoff** [fastlane/fastlane#852]
I think that error occurs for me because I'm in two iTunes Connect teams under the same account.

I solved the issue by prefixing team id into app id, but I think there should be way to set team_id in e.g. Deliverfile.

Please see the error below.
```
[21:08:04]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
✨  Once crash reporting is enabled, you get a clean output when something goes wrong.
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/manager.rb:42:in `fetch_app_id': Couldn't find app 'com.my.app' on the account of my@account.com' (RuntimeError)
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/manager.rb:21:in `app'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/build_manager.rb:8:in `upload'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/actions/pilot.rb:15:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:127:in `chdir'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:55:in `block (2 levels) in parsing_binding'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/lane.rb:36:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:46:in `chdir'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:46:in `execute'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/bin/fastlane:35:in `block (2 levels) in run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/bin/fastlane:152:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.39.0/bin/fastlane:158:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.3/bin/fastlane:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'
```

**Comment by xfreebird** [comment]
Have you tried specifying the team name through ```FASTLANE_TEAM_NAME```  env variable ?

```ruby
ENV['FASTLANE_TEAM_NAME'] = 'Team Name'
```

**Comment by KrauseFx** [comment]
The team selection is currently only implemented for the Apple Developer Portal. As of now `spaceship` doesn't support being in multiple team.s

**Comment by larryonoff** [comment]
@xfreebird I haven't tried ```FASTLANE_TEAM_NAME```. Is it supported in the latest version?

**Comment by larryonoff** [comment]
@KrauseFx :sob:. Very good that team id prefix for app id works now. But in other case I won't be able to use my love fastlane :(

**Comment by xfreebird** [comment]
Yes, but as @KrauseFx wrote that is only  for ```Apple Developer Portal```.

**Comment by larryonoff** [comment]
@xfreebird Thank you for the answer. I believe that @KrauseFx will add support soon.

**Comment by ohwutup** [comment]
hey @larryonoff! I am going to close this issue for now as it has been a while since there has been activity on here, but please reopen the issue if you have tested this out with up-to-date versions of the tools and we will definitely figure out whats going on. Thanks! :100:

**Comment by larryonoff** [comment]
@ohwutup The issue has been solved already. Thanks!
