### ISSUE TITLE
"Can't modify frozen String" error when setting output_name in Gymfile via ENV[...]

### ISSUE THREAD

**Issue by timothycosta** [fastlane/fastlane#8548]
### New Issue Checklist

- [*] Updated fastlane to the latest version
- [*] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
`Can't modify frozen String` error when setting `output_name` in Gymfile via `ENV[...]` 
Related Issue: https://github.com/fastlane/fastlane/issues/5206
The same workaround from that issue applies here: use `ENV[...].dup`

Gymfile:
```
output_directory "./bin/"
output_name ENV['APP_NAME']
workspace "./Fastlane Test.xcworkspace"
scheme "Fastlane Test"
export_method "app-store"
```

Fastfile lane:
```
  lane :build do
    gym
  end
```

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane --verbose --env en build
DEBUG [2017-03-16 14:05:38.73]: Checking if there are any plugins that should be loaded...
INFO [2017-03-16 14:05:38.75]: -------------------------------------------------
INFO [2017-03-16 14:05:38.75]: --- Step: Verifying required fastlane version ---
INFO [2017-03-16 14:05:38.75]: -------------------------------------------------
INFO [2017-03-16 14:05:38.75]: Your fastlane version 2.20.0 matches the minimum requirement of 2.20.0  ✅
INFO [2017-03-16 14:05:38.75]: ------------------------------
INFO [2017-03-16 14:05:38.75]: --- Step: default_platform ---
INFO [2017-03-16 14:05:38.75]: ------------------------------
INFO [2017-03-16 14:05:38.76]: Loading from './.env.en'
INFO [2017-03-16 14:05:38.76]: Driving the lane 'ios build' 🚀
INFO [2017-03-16 14:05:38.76]: -----------------------
INFO [2017-03-16 14:05:38.76]: --- Step: cocoapods ---
INFO [2017-03-16 14:05:38.76]: -----------------------
INFO [2017-03-16 14:05:38.91]: gem 'cocoapods' is already installed
INFO [2017-03-16 14:05:38.91]: $ pod install
INFO [2017-03-16 14:05:39.65]: ▸ Analyzing dependencies
INFO [2017-03-16 14:05:39.65]: ▸ Downloading dependencies
INFO [2017-03-16 14:05:39.65]: ▸ Generating Pods project
INFO [2017-03-16 14:05:39.65]: ▸ Integrating client project
INFO [2017-03-16 14:05:40.11]: ▸ Sending stats
INFO [2017-03-16 14:05:40.11]: ▸ Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.
INFO [2017-03-16 14:05:40.12]: ▸ [!] The Podfile does not contain any dependencies.
INFO [2017-03-16 14:05:40.13]: -----------------
INFO [2017-03-16 14:05:40.13]: --- Step: gym ---
INFO [2017-03-16 14:05:40.13]: -----------------
ERROR [2017-03-16 14:05:40.23]: Error setting value 'Fastlane Test - English' for option 'output_name'
WARN [2017-03-16 14:05:40.23]: Lane Context:
INFO [2017-03-16 14:05:40.23]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"en", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build"}
ERROR [2017-03-16 14:05:40.23]: can't modify frozen String
INFO [2017-03-16 14:05:40.23]: Successfully generated documentation at path '/Users/timothycosta/Desktop/Fastlane Test/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 1           |
| 💥   | gym                                 | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-03-16 14:05:40.24]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:25:in `eval': [!] can't modify frozen String (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:119:in `valid?'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:104:in `verify!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:250:in `set'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:70:in `method_missing'
	from (eval):14:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:25:in `eval'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:25:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:174:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:174:in `load_configuration_file'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/gym/lib/gym/detect_values.rb:10:in `set_additional_default_values'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/gym/lib/gym.rb:25:in `config='
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/gym/lib/gym/manager.rb:4:in `work'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/gym.rb:21:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:84:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.20.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.20.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  lane :provision do
    produce(
      app_name: ENV['APP_NAME'],
      language: "English",
      app_version: "1.0",
      sku: ENV['APP_SKU'],
    )
  #cert
  #sigh(force: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

  lane :check_env do
    puts "app_identifier: #{ENV['APP_IDENTIFIER']}"
    puts "app name: #{ENV['APP_NAME']}"
    puts "sku: #{ENV['APP_SKU']}"
  end

  lane :build do
    gym
  end
end
```

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier ENV['APP_IDENTIFIER'] || "com.timothycosta.FastlaneTest"# The bundle identifier of your app
apple_id "timothycosta@gmail.com" # Your Apple email address

team_id "UBBHS69627"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.20.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-03-16**
</details>

**Comment by KrauseFx** [comment]
Thanks for submitting this, this is a bug we need to fix, but for now, you can use the following code to make it work:

```ruby
output_name ENV['APP_NAME'].to_s
```

**Comment by timothycosta** [comment]
Yeah, this isn't too hard to workaround.  Is `.to_s` generally preferable to `.dup`?

**Comment by KrauseFx** [comment]
Ah yeah, `.dup` is totally fine as well 👍  It's tracked as a bug, and it's something we're gonna fix, does the workaround work for you in the mean-time?

**Comment by timothycosta** [comment]
Yes, I had it working when I opened this.  I was just curious since this is my first dive into ruby.
Thanks!

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/issues/8562, which will be in the next fastlane release 🚀 Thanks again for reporting this error
