### ISSUE TITLE
Error - Is a directory @ io_fread

### ISSUE THREAD

**Issue by rcarvalho** [fastlane/fastlane#8576]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Failure on hockey command. It consistently fails when we run fastlane on CircleCi. It was previously working. The only thing we updated recently was React Native. This appears to be distinct from issue #1110, which was concerning a macbuild and not an iOS build.

Here is my Fastfile
```
    match(type: "development")
    gym(
      scheme: "Farewell - Acceptance",
      project: './ios/Farewell.xcodeproj'
    )
    hockey(
      api_token: ENV['HOCKEY_APP_KEY'],
      public_identifier: ENV['PUBLIC_IDENTIFIER']
    )
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

```
distiller-build-21:mobile distiller$ bundle exec fastlane ios acceptance
+---------------------------------------------+---------+-----------------------------+
|                                    Used plugins                                     |
+---------------------------------------------+---------+-----------------------------+
| Plugin                                      | Version | Action                      |
+---------------------------------------------+---------+-----------------------------+
| fastlane-plugin-commit_android_version_bump | 0.1.3   | commit_android_version_bump |
+---------------------------------------------+---------+-----------------------------+

[14:48:38]: -------------------------------------------------
[14:48:38]: --- Step: Verifying required fastlane version ---
[14:48:38]: -------------------------------------------------
[14:48:38]: Your fastlane version 2.20.0 matches the minimum requirement of 1.111.0  ✅
[14:48:38]: ------------------------------
[14:48:38]: --- Step: default_platform ---
[14:48:38]: ------------------------------
[14:48:38]: Driving the lane 'ios acceptance' 🚀
[14:48:38]: -------------------
[14:48:38]: --- Step: match ---
[14:48:38]: -------------------
[14:48:38]: Successfully loaded '/Users/distiller/mobile/fastlane/Matchfile' 📄

+---------+---------------------------------------------+
|      Detected Values from './fastlane/Matchfile'      |
+---------+---------------------------------------------+
| git_url | git@github.com:farewell-io/certificates.git |
+---------+---------------------------------------------+


+-----------------------+---------------------------------------------+
|                       Summary for match 1.0.0                       |
+-----------------------+---------------------------------------------+
| type                  | development                                 |
| git_url               | git@github.com:farewell-io/certificates.git |
| git_branch            | master                                      |
| app_identifier        | io.farewell.farewell                        |
| username              | andres@farewell.io                          |
| keychain_name         | login.keychain                              |
| readonly              | false                                       |
| team_id               | CZXHS76GWX                                  |
| verbose               | false                                       |
| force                 | false                                       |
| skip_confirmation     | false                                       |
| shallow_clone         | false                                       |
| force_for_new_devices | false                                       |
| skip_docs             | false                                       |
+-----------------------+---------------------------------------------+

[14:48:38]: Cloning remote git repo...
[14:48:39]: 🔓  Successfully decrypted certificates repo
[14:48:39]: Verifying that the certificate and profile are still valid on the Dev Portal...
[14:48:41]: Installing certificate...

+-------------------+-----------------------------------------------+
|                       Installed Certificate                       |
+-------------------+-----------------------------------------------+
| User ID           | ZC7T687GNT                                    |
| Common Name       | iPhone Developer: Andres Camacho (382W5TUQZ7) |
| Organisation Unit | CZXHS76GWX                                    |
| Organisation      | FareWell, LLC                                 |
| Country           | US                                            |
| Start Datetime    | Dec 12 19:12:12 2016 GMT                      |
| End Datetime      | Dec 12 19:12:12 2017 GMT                      |
+-------------------+-----------------------------------------------+

[14:48:42]: Installing provisioning profile...

+---------------------+----------------------------------------------------+----------------------------------------+
|                                          Installed Provisioning Profile                                           |
+---------------------+----------------------------------------------------+----------------------------------------+
| Parameter           | Environment Variable                               | Value                                  |
+---------------------+----------------------------------------------------+----------------------------------------+
| App Identifier      |                                                    | io.farewell.farewell                   |
| Type                |                                                    | development                            |
| Profile UUID        | sigh_io.farewell.farewell_development              | 852cbd65-0652-499e-97b9-653026e1899d   |
| Profile Name        | sigh_io.farewell.farewell_development_profile-name | match Development io.farewell.farewell |
| Development Team ID | sigh_io.farewell.farewell_development_team-id      | CZXHS76GWX                             |
+---------------------+----------------------------------------------------+----------------------------------------+

[14:48:42]: All required keys, certificates and provisioning profiles are installed 🙌
[14:48:42]: 🔒  Successfully encrypted certificates repo
[14:48:42]: Setting Provisioning Profile type to 'development'
[14:48:42]: -----------------
[14:48:42]: --- Step: gym ---
[14:48:42]: -----------------
[14:48:42]: $ xcodebuild -list -project ./ios/Farewell.xcodeproj
[14:48:44]: $ xcodebuild clean -showBuildSettings -scheme Farewell\ -\ Acceptance -project ./ios/Farewell.xcodeproj

+----------------------+-----------------------------------+
|                  Summary for gym 2.0.0                   |
+----------------------+-----------------------------------+
| scheme               | Farewell - Acceptance             |
| project              | ./ios/Farewell.xcodeproj          |
| export_method        | development                       |
| destination          | generic/platform=iOS              |
| output_name          | Farewell - Acceptance             |
| clean                | false                             |
| output_directory     | .                                 |
| silent               | false                             |
| use_legacy_build_api | false                             |
| buildlog_path        | /tmp/circle-artifacts.zE9FdQn/gym |
| xcode_path           | /Applications/Xcode-8.0.app       |
+----------------------+-----------------------------------+

[14:48:46]: $ set -o pipefail && xcodebuild -scheme Farewell\ -\ Acceptance -project ./ios/Farewell.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/distiller/Library/Developer/Xcode/Archives/2017-03-17/Farewell\ -\ Acceptance\ 2017-03-17\ 14.48.46.xcarchive build | tee /tmp/circle-artifacts.zE9FdQn/gym/Farewell\ -\ Acceptance-Farewell\ -\ Acceptance.log | xcpretty
[14:48:48]: ▸ Building React/yoga [Release]
[14:48:48]: ▸ Check Dependencies
[14:48:48]: ▸ Building React/jschelpers [Release]
[14:48:48]: ▸ Check Dependencies
[14:48:48]: ▸ Building React/cxxreact [Release]
[14:48:48]: ▸ Check Dependencies
[14:48:48]: ▸ Building React/React [Release]
[14:48:48]: ▸ Check Dependencies
[14:48:48]: ▸ Running script 'Start Packager'
[14:48:49]: ▸ Running script 'Include RCTJSCProfiler'
[14:48:49]: ▸ Building RCTSettings/RCTSettings [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RNIntercom/RNIntercom [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTAnimation/RCTAnimation [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTNetwork/RCTNetwork [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTVibration/RCTVibration [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RNDeviceInfo/RNDeviceInfo [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building ART/ART [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTSplashScreen/RCTSplashScreen [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTAppleHealthKit/RCTAppleHealthKit [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTActionSheet/RCTActionSheet [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RNKeychain/RNKeychain [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RNMotionManager/RNMotionManager [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building BVLinearGradient/BVLinearGradient [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTWebSocket/RCTWebSocket [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTGeolocation/RCTGeolocation [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTText/RCTText [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTLinking/RCTLinking [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building RCTImage/RCTImage [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Building Farewell/Farewell - Acceptance [Release]
[14:48:49]: ▸ Check Dependencies
[14:48:49]: ▸ Running script 'Bundle React Native code and images'
[14:49:06]: ▸ the transform cache was reset.
[14:50:55]: ▸ Running script 'Run Script'
[14:50:55]: ▸ Touching Farewell\ -\ Acceptance.app
[14:50:55]: ▸ Signing /Users/distiller/Library/Developer/Xcode/DerivedData/Farewell-dfhdevjogzsvaqfdffqagadbssnx/Build/Products/Release-iphoneos/Farewell\ -\ Acceptance.app
[14:50:57]: ▸ Build Succeeded
[14:50:57]: Exporting Files:
[14:50:59]: 	 ▸ Farewell - Acceptance.app
[14:50:59]: 	 ▸ Farewell - Acceptance.app.dSYM
[14:50:59]: 	 ▸ include
[14:50:59]: 	 ▸ libART.a
[14:50:59]: 	 ▸ libBVLinearGradient.a
[14:50:59]: 	 ▸ libcxxreact.a
[14:50:59]: 	 ▸ libjschelpers.a
[14:50:59]: 	 ▸ libRCTActionSheet.a
[14:50:59]: 	 ▸ libRCTAnimation.a
[14:50:59]: 	 ▸ libRCTAppleHealthKit.a
[14:50:59]: 	 ▸ libRCTGeolocation.a
[14:50:59]: 	 ▸ libRCTImage.a
[14:50:59]: 	 ▸ libRCTLinking.a
[14:50:59]: 	 ▸ libRCTNetwork.a
[14:50:59]: 	 ▸ libRCTSettings.a
[14:50:59]: 	 ▸ libRCTSplashScreen.a
[14:50:59]: 	 ▸ libRCTText.a
[14:50:59]: 	 ▸ libRCTVibration.a
[14:50:59]: 	 ▸ libRCTWebSocket.a
[14:50:59]: 	 ▸ libReact.a
[14:50:59]: 	 ▸ libRNDeviceInfo.a
[14:50:59]: 	 ▸ libRNIntercom.a
[14:50:59]: 	 ▸ libRNKeychain.a
[14:50:59]: 	 ▸ libRNMotionManager.a
[14:50:59]: 	 ▸ libyoga.a
[14:50:59]: --------------------
[14:50:59]: --- Step: hockey ---
[14:50:59]: --------------------
[14:50:59]: Starting with file(s) upload to HockeyApp... this could take some time.
[14:51:00]: -------------------
[14:51:00]: --- Step: slack ---
[14:51:00]: -------------------
[14:51:00]: Successfully sent Slack notification
+--------------------+-----------------------------------------------------------------------------+
|                                           Lane Context                                           |
+--------------------+-----------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                         |
| PLATFORM_NAME      | ios                                                                         |
| LANE_NAME          | ios acceptance                                                              |
| SIGH_PROFILE_TYPE  | development                                                                 |
| DSYM_OUTPUT_PATH   | /Users/distiller/Library/Developer/Xcode/DerivedData/Farewell-dfhdevjogz... |
| XCODEBUILD_ARCHIVE | /Users/distiller/Library/Developer/Xcode/Archives/2017-03-17/Farewell - ... |
+--------------------+-----------------------------------------------------------------------------+
[14:51:00]: Is a directory @ io_fread - /Users/distiller/Library/Developer/Xcode/DerivedData/Farewell-dfhdevjogzsvaqfdffqagadbssnx/Build/Products

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 4           |
| 4    | gym                                 | 137         |
| 💥   | hockey                              | 0           |
| 6    | slack                               | 0           |
+------+-------------------------------------+-------------+

[14:51:00]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/distiller/mobile/vendor/bundle/ruby/2.3.0/bin/fastlane)
Errno::EISDIR: [!] Is a directory @ io_fread - /Users/distiller/Library/Developer/Xcode/DerivedData/Farewell-dfhdevjogzsvaqfdffqagadbssnx/Build/Products
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb:102:in `read'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb:102:in `method_missing'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb:29:in `read'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/upload_io.rb:34:in `read'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/generic_request.rb:206:in `copy_stream'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/generic_request.rb:206:in `send_request_with_body_stream'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/generic_request.rb:123:in `exec'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1435:in `block in transport_request'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1407:in `request'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1398:in `request'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:33:in `call'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/request/url_encoded.rb:15:in `call'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/request/multipart.rb:14:in `call'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `post'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/hockey.rb:63:in `upload_build'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/hockey.rb:47:in `upload'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/hockey.rb:161:in `run'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:217:in `chdir'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:65:in `block (2 levels) in parsing_binding'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/bin/fastlane:20:in `<top (required)>'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'
```

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.11.6                                         |
| Ruby                        | 2.3.1                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.10.2                              |
| Installation Source         | ~/mobile/vendor/bundle/ruby/2.3.0/bin/fastlane  |
| Host                        | Mac OS X 10.11.6 (15G1108)                      |
| Ruby Lib Dir                | /opt/rubies/ruby-2.3.1/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-8.0.app/Contents/Developer/ |
| Xcode Version               | 8.0                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.20.0  | ✅ Up-To-Date  |
| gym      | 2.0.0   | ✅ Up-To-Date  |
| match    | 1.0.0   | ✅ Up-To-Date  |
| pilot    | 2.0.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-commit_android_version_bump | 0.1.3   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.0.2        |
| bundler                                     | 1.14.6       |
| io-console                                  | 0.4.6        |
| CFPropertyList                              | 2.3.5        |
| i18n                                        | 0.8.1        |
| minitest                                    | 5.10.1       |
| thread_safe                                 | 0.3.6        |
| tzinfo                                      | 1.2.2        |
| activesupport                               | 4.2.8        |
| public_suffix                               | 2.0.5        |
| addressable                                 | 2.5.0        |
| builder                                     | 3.2.3        |
| mime-types                                  | 2.99.3       |
| xml-simple                                  | 1.1.5        |
| aws-s3                                      | 0.6.3        |
| babosa                                      | 1.0.2        |
| claide                                      | 1.0.1        |
| colored                                     | 1.2          |
| highline                                    | 1.7.8        |
| commander                                   | 4.4.3        |
| unf_ext                                     | 0.0.7.2      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20170223 |
| dotenv                                      | 2.2.0        |
| excon                                       | 0.55.0       |
| multipart-post                              | 2.0.0        |
| faraday                                     | 0.11.0       |
| http-cookie                                 | 1.0.3        |
| faraday-cookie_jar                          | 0.0.6        |
| faraday_middleware                          | 0.11.0.1     |
| fastimage                                   | 2.1.0        |
| gh_inspector                                | 1.0.3        |
| jwt                                         | 1.5.6        |
| little-plugger                              | 1.1.4        |
| multi_json                                  | 1.12.1       |
| logging                                     | 2.2.0        |
| memoist                                     | 0.15.0       |
| os                                          | 0.9.6        |
| signet                                      | 0.7.3        |
| googleauth                                  | 0.5.1        |
| httpclient                                  | 2.8.3        |
| hurley                                      | 0.2          |
| uber                                        | 0.0.15       |
| representable                               | 2.3.0        |
| retriable                                   | 2.1.0        |
| google-api-client                           | 0.9.28       |
| json                                        | 1.8.6        |
| mini_magick                                 | 4.5.1        |
| multi_xml                                   | 0.6.0        |
| plist                                       | 3.2.0        |
| rubyzip                                     | 1.2.1        |
| security                                    | 0.1.3        |
| slack-notifier                              | 1.5.1        |
| terminal-notifier                           | 1.7.1        |
| unicode-display_width                       | 1.1.3        |
| terminal-table                              | 1.7.3        |
| tty-screen                                  | 0.5.0        |
| word_wrap                                   | 1.0.0        |
| nanaimo                                     | 0.2.3        |
| xcodeproj                                   | 1.4.2        |
| rouge                                       | 1.11.1       |
| xcpretty                                    | 0.2.4        |
| xcpretty-travis-formatter                   | 0.0.4        |
| fastlane-plugin-commit_android_version_bump | 0.1.3        |
| http-exceptions                             | 0.1.1        |
| httparty                                    | 0.13.7       |
| mimemagic                                   | 0.3.0        |
| netrc                                       | 0.11.0       |
| parallel                                    | 1.10.0       |
| rest-client                                 | 1.8.0        |
| rainforest                                  | 2.1.0        |
| ruby-progressbar                            | 1.8.1        |
| rainforest-cli                              | 1.12.1       |
```

**Comment by MaxMillington** [comment]
Also getting this error on ios build

**Comment by KrauseFx** [comment]
```
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/hockey.rb:63:in `upload_build'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/hockey.rb:47:in `upload'
  /Users/distiller/mobile/vendor/bundle/ruby/2.3.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/hockey.rb:161:in `run'
```

It seems like it can't upload the app to hockey

```
+--------------------+-----------------------------------------------------------------------------+
|                                           Lane Context                                           |
+--------------------+-----------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                         |
| PLATFORM_NAME      | ios                                                                         |
| LANE_NAME          | ios acceptance                                                              |
| SIGH_PROFILE_TYPE  | development                                                                 |
| DSYM_OUTPUT_PATH   | /Users/distiller/Library/Developer/Xcode/DerivedData/Farewell-dfhdevjogz... |
| XCODEBUILD_ARCHIVE | /Users/distiller/Library/Developer/Xcode/Archives/2017-03-17/Farewell - ... |
+--------------------+-----------------------------------------------------------------------------+
```

Interestingly there is no `ipa` file here in the lane context. You mentioned you want to build an iOS app, right? Looking at the _gym_ output it looks like it built an Mac archive.

**Comment by MaxMillington** [comment]
@KrauseFx @rcarvalho Strange. It looks like this is definitely caused by the relatively recent React Native upgrade to 0.40 which included some breaking changes. I got my app into a good state where the build passes, and then all I do is upgrade React Native and then the fastlane build fails. 

It looks like someone else has had the same problem with fastlane after upgrading React Native. http://stackoverflow.com/questions/41956364/fastlane-reactnative-0-40-does-not-compile. I've tried his solution that he suggests but not working for me yet...

**Comment by MaxMillington** [comment]
@KrauseFx @rcarvalho Looks like we are having success building the app with fastlane locally after incorporating some of the changes in XCodee listed here: http://stackoverflow.com/questions/41477241/react-native-xcode-upgrade-and-now-rctconvert-h-not-found/41488258#41488258 , but this fails when trying to build using Circle CI. Any suggestions of where to look for discrepancies between circle and my local machine?

**Comment by KrauseFx** [comment]
@MaxMillington Sorry, I actually don't know, can you provide a sample project that can reproduce the issue?

**Comment by rcarvalho** [comment]
@KrauseFx The strange part is that if you look at the gym command, it specifies the destination as "generic/platform=iOS". However, the output is not an ipa file. What else could be affecting gym to change the output?

**Comment by KrauseFx** [comment]
It's usually related to the Xcode project, something's probably wrong there

**Comment by rcarvalho** [comment]
So, in doing more debugging we've narrowed it down to a strange issue with match. On my local working machine, I get the following output, "Summary for match 2.20.0", even though when I do a gem list my version of match is actually 1.0.0. In that summary the platform shows ios. However, on the offending system, the output says, "Summary form match 1.0.0" and there is no entry for platform.

**Comment by KrauseFx** [comment]
Make sure to run `[sudo] gem cleanup` and maybe also `gem uninstall match`

**Comment by adamgrossman** [comment]
Working with @rcarvalho --
When I run `fastlane match -v` I get `match 1.0.0`, whereas when @rcarvalho runs `fastlane match -v`, he gets `match 2.20.0`

Everything seems to be the same between our machines except for this difference. Is there a way to update my version?

**Comment by rcarvalho** [comment]
@adamgrossman Yes, my fastlane match -v is 2.20.0, but when I do a gem list my version says 1.0.0. However, @KrauseFx, I don't want to uninstall the gems and cleanup my system since it is the only system that actually builds the ipa file correctly. We tried to run gem cleanup and gem uninstall match on the offending systems and it doesn't seem to make a difference.

**Comment by KrauseFx** [comment]
Yes, fastlane is a mono gem now, pleases uninstall the _match_ gem and just use `fastlane match` from now

**Comment by rcarvalho** [comment]
That's what it was. Thanks, @KrauseFx. My computer was newer and so somehow I was only using the Fastlane gem, even though our Gemfile specified gym and match because it was created a while ago.

**Comment by KrauseFx** [comment]
Great to hear @rcarvalho 👍
