### ISSUE TITLE
Unable to get provisioning profiles

### ISSUE THREAD

**Issue by kashyapmukkamala** [fastlane/fastlane#860]
For my lane which is 

```
lane :beta do
    sigh
    increment_build_number
    increment_version_number
    gym
  end
```

This is the error I get 

```
 'download_certificate': Couldn't download provisioning profile, got this instead: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> (Spaceship::Client::UnexpectedResponse)


<html lang="en-us">
<head>
    <title>Try your request again.</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="pics-label" content='(pics-1.1 "http://www.icra.org/ratingsv02.html" l gen true for "http://www.apple.com" r (cz 1 lz 1 nz 1 oz 1 vz 1) "http://www.rsac.org/ratingsv01.html" l gen true for "http://www.apple.com" r (n 0 s 0 v 0 l 0))'>
    <meta name="Author" content="Apple Inc.">
    <meta name="viewport" content="width=1024">
    <link rel="stylesheet" type="text/css" href="https://devimages.apple.com.edgekey.net/global/styles/ext/2.2/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="https://devimages.apple.com.edgekey.net/assets/apps/styles/asst/1.0/xtheme-developer.css" />
    <link rel="stylesheet" href="https://devimages.apple.com.edgekey.net/assets/styles/base.css" type="text/css" charset="utf-8">
    <link rel="stylesheet" href="https://devimages.apple.com.edgekey.net/assets/styles/adc.css" type="text/css" charset="utf-8">
    <script src="https://devimages.apple.com.edgekey.net/global/scripts/lib/prototype.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://devimages.apple.com.edgekey.net/global/scripts/lib/scriptaculous.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://devimages.apple.com.edgekey.net/global/scripts/browserdetect.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://devimages.apple.com.edgekey.net/global/scripts/apple_core.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://devimages.apple.com.edgekey.net/global/scripts/search_decorator.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://devimages.apple.com.edgekey.net/global/scripts/adc_core.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" charset="utf-8">
        document.write('<link rel="stylesheet" type="text/css" href="https://devimages.apple.com.edgekey.net/assets/styles/script.css" media="screen">')
    </script>
</head>
<body id="error">
    <div id="globalheader">
    <h1><a href="/">Apple Developer</a></h1>
    <ul id="gh-nav">
        <li id="gh-nav-technologies"><a href="/technologies/">Technologies</a></li>
        <li id="gh-nav-resources"><a href="/resources/">Resources</a></li>
        <li id="gh-nav-devcenters"><a href="/programs/">Programs</a></li>
        <li id="gh-nav-support"><a href="/support/">Support</a></li>
        <li id="gh-nav-membercenter"><a href="/membercenter/">Member Center</a></li>
    </ul>


</div>



    <div id="content" class="box">
        <div class="cap boxtop"></div>  
            <div class="msg warn">
                <h4>We are unable to process your request.</h4>
                <p>An unknown error occurred. Please <a href="index.action">try again</a>.
            </div><!--/msg-->
        <div class="cap boxbottom"></div>
    </div>

<div id="globalfooter">
    <p class="gf-buy">Shop the <a href="http://www.apple.com/store/">Apple Online Store</a> (1-800-MY-APPLE), visit an <a href="http://www.apple.com/retail/">Apple Retail Store</a>, or find a <a href="http://www.apple.com/buy/locator/">reseller</a>.</p>   
    <ul class="gf-links piped">
        <li><a class="first" href="/sitemap/">Site Map</a></li>
        <li><a href="/rss/">RSS Feeds</a></li>

    </ul>   
    <div class="gf-sosumi">
        <p>Copyright &copy; <script>document.write(new Date().getFullYear())</script> Apple Inc. All rights reserved.</p>
        <ul class="piped">
            <li><a href="http://www.apple.com/legal/terms/site.html" class="first">Terms of Use</a></li>
            <li><a href="http://www.apple.com/legal/privacy/">Privacy Policy</a></li>
        </ul>

    </div>
</div><!--/globalfooter-->
</body>
</html>
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.1/lib/spaceship/portal/certificate.rb:256:in `download_raw'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/lib/sigh/runner.rb:82:in `block (2 levels) in fetch_profiles'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/lib/sigh/runner.rb:80:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/lib/sigh/runner.rb:80:in `block in fetch_profiles'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/lib/sigh/runner.rb:77:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/lib/sigh/runner.rb:77:in `find_all'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/lib/sigh/runner.rb:77:in `fetch_profiles'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/lib/sigh/runner.rb:20:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/lib/sigh/manager.rb:7:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/bin/sigh:34:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/bin/sigh:89:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.3/bin/sigh:107:in `<top (required)>'
    from /usr/bin/sigh:23:in `load'
    from /usr/bin/sigh:23:in `<main>' 

```

**Comment by kraftydevil** [comment]
It points to your sigh configuration. It's similar to an issue that I'm having but my issue is with spaceship calls in a ruby script.

The error message, "Couldn't download provisioning profile...", looks like it is returned by one of the Apple APIs.

I suspect it has something to do with asking for a recently updated provisioning profile that's not yet ready to be downloaded but that might an issue unique to my script.

**Comment by ohwutup** [comment]
Hey everyone! I'm going to close this due to inactivity, please feel free to reopen if necessary! :tada:
