### ISSUE TITLE
crash in scan.rb - no implicit conversion of nil into Array

### ISSUE THREAD

**Issue by battlmonstr** [fastlane/fastlane#8677]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
$ fastlane all
[16:02:06]: ------------------
[16:02:06]: --- Step: scan ---
[16:02:06]: ------------------
[16:02:06]: $ xcodebuild -list -workspace xxx.xcworkspace
[16:02:16]: Command timed out after 10 seconds on try 1 of 4, trying again...
[16:02:26]: Command timed out after 10 seconds on try 2 of 4, trying again...
[16:02:36]: Command timed out after 10 seconds on try 3 of 4, trying again...
[16:02:46]: Command timed out after 10 seconds on try 4 of 4
+------------------------+-------------------+
|                Lane Context                |
+------------------------+-------------------+
| DEFAULT_PLATFORM       | ios               |
| PLATFORM_NAME          | ios               |
| LANE_NAME              | ios all           |
| SCAN_DERIVED_DATA_PATH | build/DerivedData |
+------------------------+-------------------+
[16:02:46]: no implicit conversion of nil into Array
[16:02:47]: fastlane finished with errors
.../fastlane/lib/fastlane/actions/scan.rb:32:in `-': [!] no implicit conversion of nil into Array (TypeError)
	from .../fastlane/lib/fastlane/actions/scan.rb:32:in `ensure in run'
	from .../fastlane/lib/fastlane/actions/scan.rb:34:in `run'
	from .../fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from .../fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from .../fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from .../fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from .../fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from .../fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from .../fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:9:in `block (2 levels) in parsing_binding'
	from .../fastlane/lib/fastlane/lane.rb:33:in `call'
	from .../fastlane/lib/fastlane/lane.rb:33:in `call'
	from .../fastlane/lib/fastlane/runner.rb:192:in `try_switch_to_lane'
	from .../fastlane/lib/fastlane/fast_file.rb:282:in `test'
	from Fastfile:51:in `block (2 levels) in parsing_binding'
	from .../fastlane/lib/fastlane/lane.rb:33:in `call'
	from .../fastlane/lib/fastlane/lane.rb:33:in `call'
	from .../fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from .../fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from .../fastlane/lib/fastlane/runner.rb:45:in `execute'
	from .../fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from .../fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from .../fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from .../vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from .../vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from .../vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from .../vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from .../fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from .../vendor/bundle/ruby/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from .../fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from .../fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from .../fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from .../bin/fastlane:15:in `<top (required)>'
	from .../ruby-2.0.0-p648/bin/fastlane:23:in `load'
	from .../ruby-2.0.0-p648/bin/fastlane:23:in `<main>'
	from .../ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from .../ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.0.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.0                          |
| Installation Source | ~/.rvm/gems/ruby-2.0.0-p648/bin/fastlane    |
| Host                | Mac OS X 10.11.6 (15G1004)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.0.0-p648/lib           |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.19.1  |   Update available |

```

**Comment by mfurtak** [comment]
Thanks for the fix in #8678 🚀
