### ISSUE TITLE
incompatible character encodings: UTF-8 and US-ASCII in a Jenkins Pipeline

### ISSUE THREAD

**Issue by maximepontoire** [fastlane/fastlane#8680]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
I'm trying to integrate my fastlane project in Jenkins 2.51. I'm facing the following issue (either in a fast lane env or using a lane). I'm not facing the issue when running it manually in the project.
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build and upload to Crashlytics)
[Pipeline] sh
[workspace] Running shell script
+ export TERM=xterm-256color
+ TERM=xterm-256color
[Pipeline] sh
[workspace] Running shell script
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
[Pipeline] sh
[workspace] Running shell script
+ export LANGUAGE=en_US.UTF-8
+ LANGUAGE=en_US.UTF-8
[Pipeline] sh
[workspace] Running shell script
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
[Pipeline] sh
[workspace] Running shell script
+ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
[Pipeline] sh
[workspace] Running shell script
+ /usr/local/bin/fastlane env
[14:54:25]: [33mGenerating fastlane environment output, this might take a few seconds...[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mcharacter encoding: US-ASCII and UTF-8[0m
   https://github.com/fastlane/fastlane/issues/8234 [[31mopen[0m] 2 💬
   a week ago

➡️  [33mfastlane not working after updating ruby.[0m
   https://github.com/fastlane/fastlane/issues/8529 [[31mopen[0m] 3 💬
   2 weeks ago

➡️  [33mNo value found for 'username' when try to Jenkins Integration with Fastlane. But the lane run successful via SSH.[0m
   https://github.com/fastlane/fastlane/issues/4785 [[32mclosed[0m] 2 💬
   19 Nov 2016

and 2 more at: https://github.com/fastlane/fastlane/search?q=incompatible%20character%20encodings:%20UTF-8%20and%20US-ASCII&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/environment_printer.rb:25:in `get': [31m[!] incompatible character encodings: UTF-8 and US-ASCII[0m (Encoding::CompatibilityError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:233:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.7.1                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 0.2.6        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-03-28**
</details>

**Comment by maximepontoire** [comment]
I've solved my issue : in Jenkins,

I've set an environment variable : LC_ALL with the value en_US.UTF-8.

Every build is ok now
