### ISSUE TITLE
I can't call puts from the Fastfile - uninitialized constant Fastlane::FastFile::Fastlane::Actions::PutsAction (NameError)

### ISSUE THREAD

**Issue by daveols** [fastlane/fastlane#8700]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

As per the title - when I try to call `puts` from the Fastfile, the below error is thrown.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```sh
[19:28:05]: uninitialized constant Fastlane::FastFile::Fastlane::Actions::PutsAction

[19:28:05]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/fast_file.rb:277:in `puts': [!] uninitialized constant Fastlane::FastFile::Fastlane::Actions::PutsAction (NameError)
	from Fastfile:139:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```sh
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

...

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| did_you_mean                                          | 1.1.0        |
| slack-notifier                                        | 1.5.1        |
| i18n                                                  | 0.8.1        |
| thread_safe                                           | 0.3.6        |
| tzinfo                                                | 1.2.3        |
| minitest                                              | 5.10.1       |
| activesupport                                         | 4.2.8        |
| CFPropertyList                                        | 2.3.5        |
| claide                                                | 1.0.1        |
| colored                                               | 1.2          |
| nanaimo                                               | 0.2.3        |
| xcodeproj                                             | 1.4.2        |
| rouge                                                 | 1.11.1       |
| xcpretty                                              | 0.2.4        |
| terminal-notifier                                     | 1.7.1        |
| unicode-display_width                                 | 1.1.3        |
| terminal-table                                        | 1.7.3        |
| plist                                                 | 3.2.0        |
| public_suffix                                         | 2.0.5        |
| addressable                                           | 2.5.0        |
| multipart-post                                        | 2.0.0        |
| word_wrap                                             | 1.0.0        |
| tty-screen                                            | 0.5.0        |
| babosa                                                | 1.0.2        |
| highline                                              | 1.7.8        |
| commander-fastlane                                    | 4.4.4        |
| excon                                                 | 0.55.0       |
| faraday                                               | 0.11.0       |
| unf_ext                                               | 0.0.7.2      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20170223 |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| fastimage                                             | 2.1.0        |
| gh_inspector                                          | 1.0.3        |
| uber                                                  | 0.0.15       |
| representable                                         | 2.3.0        |
| retriable                                             | 2.1.0        |
| mime-types-data                                       | 3.2016.0521  |
| mime-types                                            | 3.1          |
| hurley                                                | 0.2          |
| little-plugger                                        | 1.1.4        |
| multi_json                                            | 1.12.1       |
| logging                                               | 2.2.0        |
| jwt                                                   | 1.5.6        |
| memoist                                               | 0.15.0       |
| os                                                    | 0.9.6        |
| signet                                                | 0.7.3        |
| googleauth                                            | 0.5.1        |
| httpclient                                            | 2.8.3        |
| google-api-client                                     | 0.9.28       |
| mini_magick                                           | 4.5.1        |
| multi_xml                                             | 0.6.0        |
| rubyzip                                               | 1.2.1        |
| security                                              | 0.1.3        |
| xcpretty-travis-formatter                             | 0.0.4        |
| dotenv                                                | 2.2.0        |
| bundler                                               | 1.14.6       |
| faraday_middleware                                    | 0.11.0.1     |
| json                                                  | 2.0.3        |
| io-console                                            | 0.4.6        |
| openssl                                               | 2.0.2        |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0        |
```

**Comment by PetrosIchor** [comment]
You might want to try rolling back to an earlier ruby version to see if that's the culprit.  Do other print method work such as `print` or `p`?

**Comment by mfurtak** [comment]
@daveols This is a strange situation, and I can't reproduce it locally. 😞 

If you'd be willing to do an experiment for me, try editing

```
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/fast_file.rb
```

and change line 277 from

```ruby
Fastlane::Actions::PutsAction.run([value])
```

to 

```ruby
::Fastlane::Actions::PutsAction.run([value])
```

save, and run again. Do you see any difference?

**Comment by KrauseFx** [comment]
@mfurtak Maybe this is related to Ruby 2.4.0 somehow?

**Comment by mfurtak** [comment]
I thought the same, so I switched to Ruby 2.4 when I tried to reproduce, but it didn't seem to matter 😞

**Comment by daveols** [comment]
@PetrosIchor other print methods work as expected. I think there's only an issue with `puts` because it is overwritten by fastlane.

@mfurtak Very strange! ~~Changing that line had no effect. In fact, commenting out that entire file had no effect! Perhaps~~ I forgot I had updated fastlane to 2.24 so of course it did nothing. Changing that line actually fixed the issue! Doesn't seem like a clean solution though.

**Comment by mfurtak** [comment]
Wild! Thanks for running the experiment. The error shows Ruby trying to prefix the path of the current module as the root of namespace for the `PutsAction` call. Prefixing the `PutsAction` call with `::` tells Ruby that the namespace we're giving is absolute.

Still, it's not clear why this is failing for you and not me, so more thought and research is needed. We'll get back to you. :+1:

**Comment by mfurtak** [comment]
@daveols While the setup sounds really simple, if you could share a small Fastfile that reproduces the problem for you, that would be really helpful. Thanks!

**Comment by daveols** [comment]
@mfurtak 

I've resolved the issue! 

It seems it was caused by importing a custom action using `import` instead of `fastlane_require`.

Hope this helps any confused folk in the future 🎉

**Comment by mfurtak** [comment]
@daveols Whew! Glad you are back in business. :rocket:

Could you share an example of the approach that was causing the problem? That would really help us investigate further!
