### ISSUE TITLE
full_gem_path uninitialized constant error when running fastlane spaceship

### ISSUE THREAD

**Issue by rounak** [fastlane/fastlane#8712]
### Issue Description

Ruby full_gem_path error when running fastlane spaceship

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.3/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.3/lib/bundler.rb:12:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:5:in `<class:PluginManager>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:4:in `<module:Fastlane>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.23.0/fastlane/lib/fastlane.rb:22:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/cli_tools_distributor.rb:18:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.23.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

Same error when trying to run this as well.

**Comment by KrauseFx** [comment]
That's a RubyGems bug, please update using `gem update --system`

**Comment by KrauseFx** [comment]
Maybe this command needs to be prefixed with `sudo`

**Comment by rounak** [comment]
Will do, thanks!

**Comment by asfalcone** [comment]
@rounak I'm going to close out this issue for now. 👍
