### ISSUE TITLE
Fastlane ruby error

### ISSUE THREAD

**Issue by andreyslyusar** [fastlane/fastlane#875]
I am new with fastlane, trying to build lane run next issue:

```
$ fastlane dev-deploy
[13:40:54]: -------------------------------------------------
[13:40:54]: --- Step: Verifying required fastlane version ---
[13:40:54]: -------------------------------------------------
[13:40:54]: fastlane version valid
[13:40:54]: ------------------------------
[13:40:54]: --- Step: default_platform ---
[13:40:54]: ------------------------------
[13:40:54]: /Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:136:in `method_missing'
Fastfile:38:in `block in parsing_binding'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:108:in `call'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:108:in `platform'
Fastfile:24:in `parsing_binding'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:48:in `eval'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:48:in `block in parse'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:37:in `chdir'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:37:in `parse'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:27:in `initialize'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/lane_manager.rb:12:in `new'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/command_line_handler.rb:31:in `handle'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/bin/fastlane:35:in `block (2 levels) in run'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/bin/fastlane:152:in `run'
/Users/Opium/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/fastlane-1.39.0/bin/fastlane:158:in `<top (required)>'
/Users/Opium/.rbenv/versions/2.0.0-p645/bin/fastlane:23:in `load'
/Users/Opium/.rbenv/versions/2.0.0-p645/bin/fastlane:23:in `<main>'
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '0fadef224136f540d9deff9061f770a7'
The crash report has been stored locally '/tmp/sentry_0fadef224136f540d9deff9061f770a7.json'
```

```
$ ruby --version
ruby 2.0.0p645 (2015-04-13 revision 50299) [x86_64-darwin14.3.0]
```

```
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.39.0"

default_platform :ios


platform :ios do
  before_all do
	ensure_git_status_clean	   
    cocoapods
        
    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
  end
  
  desc "Deploy development server target build"
  lane :dev-deploy do 
  
  end
  
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sigh
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    snapshot
    sigh
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
```

**Comment by KrauseFx** [comment]
I think you're not allowed to use a `-` in your lane name. Could you try renaming the lane?

**Comment by andreyslyusar** [comment]
@KrauseFx Thanks a lot. Indeed ```-``` was a problem.
