### ISSUE TITLE
Match "[!] No code signing identity found and can not create a new one because you enabled `readonly`"

### ISSUE THREAD

**Issue by blakeanderson** [fastlane/fastlane#8810]
### New Issue Checklist

[x] Updated fastlane to the latest version
[x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After successfully running `match` to create certs and prov profiles, attempting to run `match --readonly` always fails w/ "[!] No code signing identity found and can not create a new one because you enabled `readonly`"
```
fastlane match -u ios@test.com --verbose
...
INFO [2017-04-06 20:54:32.13]: All required keys, certificates and provisioning profiles are installed 🙌
```

```
fastlane match -u ios@test.com --verbose --readonly

+----------------+-----------------------------------------------+
|          Detected Values from './fastlane/Matchfile'           |
+----------------+-----------------------------------------------+
| git_url        | git@github.com:Test/ios-certificates.git |
| type           | development                                   |
| app_identifier | com.Test                                 |
+----------------+-----------------------------------------------+

DEBUG [2017-04-06 20:54:49.58]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'

+-----------------------+-----------------------------------------------+
|                       Summary for match 2.26.0                        |
+-----------------------+-----------------------------------------------+
| verbose               | true                                          |
| username              | ios@Test.com                             |
| readonly              | true                                          |
| git_url               | git@github.com:Test/ios-certificates.git |
| type                  | development                                   |
| app_identifier        | com.Test                                 |
| git_branch            | master                                        |
| keychain_name         | login.keychain                                |
| team_id               | QW6T5Q39LV                                    |
| force                 | false                                         |
| skip_confirmation     | false                                         |
| shallow_clone         | false                                         |
| force_for_new_devices | false                                         |
| skip_docs             | false                                         |
| platform              | ios                                           |
+-----------------------+-----------------------------------------------+

INFO [2017-04-06 20:54:49.59]: Cloning remote git repo...
INFO [2017-04-06 20:54:49.59]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:Test/ios-certificates.git' '/var/folders/zw/fl39dvl97fb7z_xdw9rygbpm0000gn/T/d20170406-96094-1acs8d4'
INFO [2017-04-06 20:54:49.61]: ▸ Cloning into '/var/folders/zw/fl39dvl97fb7z_xdw9rygbpm0000gn/T/d20170406-96094-1acs8d4'...
INFO [2017-04-06 20:54:50.19]: ▸ remote: Counting objects: 267, done.
INFO [2017-04-06 20:54:50.30]: ▸ remote: Compressing objects: 100% (230/230), done.
INFO [2017-04-06 20:54:50.54]: ▸ remote: Total 267 (delta 33), reused 250 (delta 19), pack-reused 0
INFO [2017-04-06 20:54:50.54]: ▸ Receiving objects: 100% (267/267), 858.87 KiB | 0 bytes/s, done.
INFO [2017-04-06 20:54:50.54]: ▸ Resolving deltas: 100% (33/33), done.
INFO [2017-04-06 20:54:50.68]: 🔓  Decrypted '898C48T5YD.cer'
INFO [2017-04-06 20:54:50.70]: 🔓  Decrypted '94C25MDZA3.cer'
INFO [2017-04-06 20:54:50.72]: 🔓  Decrypted 'F3M62YU8E7.cer'
INFO [2017-04-06 20:54:50.74]: 🔓  Decrypted 'N9Y88MCQW6.cer'
INFO [2017-04-06 20:54:50.76]: 🔓  Decrypted 'P777TYF595.cer'
INFO [2017-04-06 20:54:50.78]: 🔓  Decrypted 'VV642H5HCF.cer'
INFO [2017-04-06 20:54:50.80]: 🔓  Decrypted 'R5XQ523ZNZ.cer'
INFO [2017-04-06 20:54:50.82]: 🔓  Decrypted 'AppStore_com.Test.mobileprovision'
INFO [2017-04-06 20:54:50.84]: 🔓  Decrypted 'Development_com.Test.mobileprovision'
INFO [2017-04-06 20:54:50.84]: 🔓  Successfully decrypted certificates repo
WARN [2017-04-06 20:54:50.84]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

/Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/fastlane_core/lib/fastlane_core/ui/interface.rb:138:in `crash!': [!] No code signing identity found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneCrash)
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/runner.rb:76:in `fetch_certificate'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/runner.rb:34:in `run'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/commands_generator.rb:39:in `block (2 levels) in run'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/commands_generator.rb:130:in `run'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/commands_generator.rb:12:in `start'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/bin/fastlane:20:in `<top (required)>'
	from /Users/blakeanderson/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/blakeanderson/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

```

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.0  | ✅ Up-To-Date  |

**Comment by mattoakesnet** [comment]
Getting the same issue.

If I run `fastlane match appstore` from a blank state it correctly creates a certificate and profiles. Running it again creates another certificate and messes up the profiles. Running it with `readonly: true` always says there is no certificate.

**Comment by Narsail** [comment]
I have the same problem as @mattoakesnet . This problem is messing up my whole day so far.

**Comment by RosyTucker** [comment]
Same issue

**Comment by KrauseFx** [comment]
Did this work in previous versions? What happens if you disable `readonly` mode for one run and run it again? Can you share the complete output?

**Comment by blakeanderson** [comment]
@KrauseFx 

- 2.26.0 is the first version I've used `match`
- If I disable `readonly` I then run into the `Could not create another Development certificate, reached the maximum number of available Development certificates` issue

```
+----------------+-----------------------------------------------+
|          Detected Values from './fastlane/Matchfile'           |
+----------------+-----------------------------------------------+
| git_url        | git@github.com:Test/ios-certificates.git |
| type           | development                                   |
| app_identifier | com.Test                                 |
+----------------+-----------------------------------------------+

DEBUG [2017-04-07 10:38:25.86]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'

+-----------------------+-----------------------------------------------+
|                       Summary for match 2.26.0                        |
+-----------------------+-----------------------------------------------+
| verbose               | true                                          |
| username              | ios@Test.com                             |
| git_url               | git@github.com:Test/ios-certificates.git |
| type                  | development                                   |
| app_identifier        | com.Test                                 |
| git_branch            | master                                        |
| keychain_name         | login.keychain                                |
| readonly              | false                                         |
| team_id               | QW6T5Q39LV                                    |
| force                 | false                                         |
| skip_confirmation     | false                                         |
| shallow_clone         | false                                         |
| force_for_new_devices | false                                         |
| skip_docs             | false                                         |
| platform              | ios                                           |
+-----------------------+-----------------------------------------------+

INFO [2017-04-07 10:38:25.91]: Cloning remote git repo...
INFO [2017-04-07 10:38:25.91]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:Test/ios-certificates.git' '/var/folders/zw/fl39dvl97fb7z_xdw9rygbpm0000gn/T/d20170407-4610-iy7yrm'
INFO [2017-04-07 10:38:25.99]: ▸ Cloning into '/var/folders/zw/fl39dvl97fb7z_xdw9rygbpm0000gn/T/d20170407-4610-iy7yrm'...
INFO [2017-04-07 10:38:27.14]: ▸ remote: Counting objects: 267, done.
INFO [2017-04-07 10:38:27.28]: ▸ remote: Compressing objects: 100% (230/230), done.
INFO [2017-04-07 10:38:27.57]: ▸ remote: Total 267 (delta 33), reused 250 (delta 19), pack-reused 0
INFO [2017-04-07 10:38:27.57]: ▸ Receiving objects: 100% (267/267), 858.87 KiB | 0 bytes/s, done.
INFO [2017-04-07 10:38:27.57]: ▸ Resolving deltas: 100% (33/33), done.
INFO [2017-04-07 10:38:27.92]: 🔓  Decrypted '898C48T5YD.cer'
INFO [2017-04-07 10:38:27.95]: 🔓  Decrypted '94C25MDZA3.cer'
INFO [2017-04-07 10:38:27.98]: 🔓  Decrypted 'F3M62YU8E7.cer'
INFO [2017-04-07 10:38:28.01]: 🔓  Decrypted 'N9Y88MCQW6.cer'
INFO [2017-04-07 10:38:28.03]: 🔓  Decrypted 'P777TYF595.cer'
INFO [2017-04-07 10:38:28.06]: 🔓  Decrypted 'VV642H5HCF.cer'
INFO [2017-04-07 10:38:28.08]: 🔓  Decrypted 'R5XQ523ZNZ.cer'
INFO [2017-04-07 10:38:28.11]: 🔓  Decrypted 'AppStore_com.Test.mobileprovision'
INFO [2017-04-07 10:38:28.14]: 🔓  Decrypted 'Development_com.Test.mobileprovision'
INFO [2017-04-07 10:38:28.14]: 🔓  Successfully decrypted certificates repo
INFO [2017-04-07 10:38:28.38]: Verifying that the certificate and profile are still valid on the Dev Portal...
WARN [2017-04-07 10:38:32.00]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+----------------------------------------------------------+
|                         Summary for cert 2.26.0                          |
+---------------+----------------------------------------------------------+
| development   | true                                                     |
| force         | true                                                     |
| username      | ios@Test.com                                        |
| team_id       | QW6T5Q39LV                                               |
| keychain_path | /Users/blakeanderson/Library/Keychains/login.keychain-db |
| generate_p12  | false                                                    |
| platform      | ios                                                      |
+---------------+----------------------------------------------------------+

INFO [2017-04-07 10:38:32.02]: Starting login with user 'ios@Test.com'
INFO [2017-04-07 10:38:34.15]: Successfully logged in

/Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!': [!] Could not create another Development certificate, reached the maximum number of available Development certificates. (FastlaneCore::Interface::FastlaneError)
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/cert/lib/cert/runner.rb:151:in `rescue in create_certificate'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/cert/lib/cert/runner.rb:146:in `create_certificate'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/cert/lib/cert/runner.rb:37:in `run'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/cert/lib/cert/runner.rb:6:in `launch'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/generator.rb:20:in `generate_certificate'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/runner.rb:77:in `fetch_certificate'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/runner.rb:34:in `run'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/commands_generator.rb:39:in `block (2 levels) in run'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/commands_generator.rb:130:in `run'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/match/lib/match/commands_generator.rb:12:in `start'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	from /Users/blakeanderson/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.0/bin/fastlane:20:in `<top (required)>'
	from /Users/blakeanderson/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/blakeanderson/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by RosyTucker** [comment]
Rolling back to 2.25.0 fixes it for me

**Comment by Narsail** [comment]
@RosyTucker How did you roll back?

**Comment by KrauseFx** [comment]
I can reproduce this issue and I'm working on a fix, sorry about this. It was introduced via https://github.com/fastlane/fastlane/pull/8440

**Comment by KrauseFx** [comment]
We rolled back the change that introduced the problem, and ship a new release in about 15 minutes. Really sorry for the troubles. Once the new release is live, please update using `fastlane update_fastlane`

**Comment by mattoakesnet** [comment]
Thanks for the quick action on this!

**Comment by blakeanderson** [comment]
Thanks for the fix!
