### ISSUE TITLE
[WIP] pilot needs to be upgraded to work with new iTunes Connect

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#8856]
```
be fastlane pilot add -e test@krausefx.com --team_id 18742800 --verbose

INFO [2017-04-11 14:24:07.07]: Login to iTunes Connect (felix@sunapps.net)
Looking for iTunes Connect Team with ID 18742800
INFO [2017-04-11 14:24:11.34]: Login successful
INFO [2017-04-11 14:24:13.83]: Existing tester test@krausefx.com
ERROR [2017-04-11 14:24:15.41]: Could not add test@krausefx.com to app: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>[""], "info"=>nil}, "statusCode"=>"ERROR"}
ERROR [2017-04-11 14:24:15.41]: Could not create tester test@krausefx.com
ERROR [2017-04-11 14:24:15.41]: [test@krausefx.com]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>[""], "info"=>nil}, "statusCode"=>"ERROR"}
bundler: failed to load command: fastlane (/Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Some operations failed: [test@krausefx.com]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>[""], "info"=>nil}, "statusCode"=>"ERROR"}
  /Users/fkrause/Developer/fastlane/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!'
  /Users/fkrause/Developer/fastlane/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/commands_generator.rb:37:in `handle_multiple'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/commands_generator.rb:94:in `block (2 levels) in run'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
  /Users/fkrause/Developer/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/commands_generator.rb:158:in `run'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/commands_generator.rb:12:in `start'
  /Users/fkrause/Developer/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /Users/fkrause/Developer/fastlane/bin/fastlane:20:in `<top (required)>'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/fastlane:22:in `load'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/fastlane:22:in `<top (required)>'
```

**Comment by KrauseFx** [comment]
This is the actual stack trace

```
bundler: failed to load command: fastlane (/Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/fastlane)
Spaceship::Client::UnexpectedResponse: [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>[""], "info"=>nil}, "statusCode"=>"ERROR"}
  /Users/fkrause/Developer/fastlane/spaceship/lib/spaceship/client.rb:459:in `parse_response'
  /Users/fkrause/Developer/fastlane/spaceship/lib/spaceship/tunes/tunes_client.rb:1427:in `update_tester_from_app!'
  /Users/fkrause/Developer/fastlane/spaceship/lib/spaceship/tunes/tunes_client.rb:1250:in `add_tester_to_app!'
  /Users/fkrause/Developer/fastlane/spaceship/lib/spaceship/tunes/tester.rb:193:in `add_to_app!'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/tester_manager.rb:40:in `add_tester'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/commands_generator.rb:30:in `public_send'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/commands_generator.rb:30:in `handle_multiple'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/commands_generator.rb:94:in `block (2 levels) in run'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
  /Users/fkrause/Developer/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/commands_generator.rb:158:in `run'
  /Users/fkrause/Developer/fastlane/pilot/lib/pilot/commands_generator.rb:12:in `start'
  /Users/fkrause/Developer/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /Users/fkrause/Developer/fastlane/bin/fastlane:20:in `<top (required)>'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/fastlane:22:in `load'
  /Users/fkrause/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/fastlane:22:in `<top (required)>'
```

**Comment by KrauseFx** [comment]
The adding to app doesn't work

**Comment by runloop** [comment]
Is there a way to add testers to a particular app while this is broken?

**Comment by KrauseFx** [comment]
@runloop Unfortunately for now, just manually using iTunes Connect, however parts of it are also broken right now 😢

**Comment by KrauseFx** [comment]
I'll leave this issue open, however please subscribe to the WIP PR for updates: https://github.com/fastlane/fastlane/pull/8871
