### ISSUE TITLE
Failed to install ruby gem 'badge' 

### ISSUE THREAD

**Issue by jrmybrault** [fastlane/fastlane#8875]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Lane run fails when using badge action.

### Captured Output

Command Used: `launch_on_sim scheme:fastlane.demo env:qualif`
<details><summary>Output/Log</summary>

```

DEBUG [2017-04-13 10:37:22.54]: Checking if there are any plugins that should be loaded...
DEBUG [2017-04-13 10:37:22.60]: Using scheme: fastlane.demo
DEBUG [2017-04-13 10:37:22.60]: Using env: qualif
INFO [2017-04-13 10:37:22.60]: -------------------------------------------------
INFO [2017-04-13 10:37:22.60]: --- Step: Verifying required fastlane version ---
INFO [2017-04-13 10:37:22.60]: -------------------------------------------------
INFO [2017-04-13 10:37:22.60]: Your fastlane version 2.26.1 matches the minimum requirement of 2.26.1  ✅
INFO [2017-04-13 10:37:22.61]: ------------------------------
INFO [2017-04-13 10:37:22.61]: --- Step: default_platform ---
INFO [2017-04-13 10:37:22.61]: ------------------------------
INFO [2017-04-13 10:37:22.61]: Driving the lane 'ios launch_on_sim' 🚀
INFO [2017-04-13 10:37:22.62]: -----------------------
INFO [2017-04-13 10:37:22.62]: --- Step: cocoapods ---
INFO [2017-04-13 10:37:22.62]: -----------------------
INFO [2017-04-13 10:37:22.92]: gem 'cocoapods' is already installed
INFO [2017-04-13 10:37:22.92]: $ pod install
INFO [2017-04-13 10:37:24.68]: ▸ Analyzing dependencies
INFO [2017-04-13 10:37:24.68]: ▸ Downloading dependencies
INFO [2017-04-13 10:37:24.68]: ▸ Using Crashlytics (3.8.4)
INFO [2017-04-13 10:37:24.68]: ▸ Using Fabric (1.6.11)
INFO [2017-04-13 10:37:24.68]: ▸ Using OHAutoNIBi18n (0.2.0)
INFO [2017-04-13 10:37:24.68]: ▸ Using R.swift (3.2.0)
INFO [2017-04-13 10:37:24.68]: ▸ Using R.swift.Library (3.0.2)
INFO [2017-04-13 10:37:24.68]: ▸ Generating Pods project
INFO [2017-04-13 10:37:24.68]: ▸ Integrating client project
INFO [2017-04-13 10:37:25.18]: ▸ Sending stats
INFO [2017-04-13 10:37:25.19]: ▸ Pod installation complete! There are 4 dependencies from the Podfile and 5 total pods installed.
INFO [2017-04-13 10:37:25.23]: ----------------------------------------
INFO [2017-04-13 10:37:25.23]: --- Step: Switch to ios archive lane ---
INFO [2017-04-13 10:37:25.23]: ----------------------------------------
INFO [2017-04-13 10:37:25.23]: Cruising over to lane 'ios archive' 🚖
INFO [2017-04-13 10:37:25.24]: --------------------------------
INFO [2017-04-13 10:37:25.24]: --- Step: get_version_number ---
INFO [2017-04-13 10:37:25.24]: --------------------------------
INFO [2017-04-13 10:37:25.24]: $ cd /Users/jbr15998/Documents/dev/iOS/fastlane.demo && agvtool what-marketing-version -terse
INFO [2017-04-13 10:37:25.76]: ▸ "fastlane.demo.xcodeproj/../fastlane.demo/Info.plist"=1.0
INFO [2017-04-13 10:37:25.77]: ▸ "fastlane.demo.xcodeproj/../fastlane.demoTests/Info.plist"=1.0
INFO [2017-04-13 10:37:25.78]: ▸ "fastlane.demo.xcodeproj/../fastlane.demoUITests/Info.plist"=1.0
INFO [2017-04-13 10:37:25.78]: -------------------
INFO [2017-04-13 10:37:25.78]: --- Step: badge ---
INFO [2017-04-13 10:37:25.78]: -------------------
WARN [2017-04-13 10:37:26.00]: Installing Ruby gem 'badge'...
WARN [2017-04-13 10:37:30.59]: Lane Context:
INFO [2017-04-13 10:37:30.59]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios launch_on_sim", :VERSION_NUMBER=>"1.0"}
ERROR [2017-04-13 10:37:30.59]: ERROR: Failed to build gem native extension.

    current directory: /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/curb-0.9.3/ext
/Users/jbr15998/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170413-57563-pgmqx1.rb extconf.rb
checking for curl-config... yes
checking for curlinfo_appconnect_time... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/jbr15998/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
	--with-curl-dir
	--without-curl-dir
	--with-curl-include
	--without-curl-include=${curl-dir}/include
	--with-curl-lib
	--without-curl-lib=${curl-dir}/lib
/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:524:in `with_werror'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:52:in `block in have_constant'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from extconf.rb:44:in `have_constant'
	from extconf.rb:62:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/curb-0.9.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/curb-0.9.3 for inspection.
Results logged to /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/curb-0.9.3/gem_make.out

INFO [2017-04-13 10:37:30.59]: Successfully generated documentation at path '/Users/jbr15998/Documents/dev/iOS/fastlane.demo/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 2           |
| 4    | Switch to ios archive lane          | 0           |
| 5    | get_version_number                  | 0           |
| 💥   | badge                               | 4           |
+------+-------------------------------------+-------------+

ERROR [2017-04-13 10:37:30.60]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: ERROR: Failed to build gem native extension.

    current directory: /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/curb-0.9.3/ext
/Users/jbr15998/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170413-57563-pgmqx1.rb extconf.rb
checking for curl-config... yes
checking for curlinfo_appconnect_time... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/jbr15998/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
	--with-curl-dir
	--without-curl-dir
	--with-curl-include
	--without-curl-include=${curl-dir}/include
	--with-curl-lib
	--without-curl-lib=${curl-dir}/lib
/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:524:in `with_werror'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:52:in `block in have_constant'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from extconf.rb:44:in `have_constant'
	from extconf.rb:62:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/curb-0.9.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/curb-0.9.3 for inspection.
Results logged to /Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/curb-0.9.3/gem_make.out

URL: https://api.github.com/search/issues?q=ERROR:%20Failed%20to%20build%20gem%20native%20extension.%0A%0A%20%20%20%20current%20directory:%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/curb-0.9.3/ext%0A/Users/jbr15998/.fastlane/bin/bundle/bin/ruby%20-r%20./siteconf20170413-57563-pgmqx1.rb%20extconf.rb%0Achecking%20for%20curl-config...%20yes%0Achecking%20for%20curlinfo_appconnect_time...%20***%20extconf.rb%20failed%20***%0ACould%20not%20create%20Makefile%20due%20to%20some%20reason,%20probably%20lack%20of%20necessary%0Alibraries%20and/or%20headers.%20%20Check%20the%20mkmf.log%20file%20for%20more%20details.%20%20You%20may%0Aneed%20configuration%20options.%0A%0AProvided%20configuration%20options:%0A%09--with-opt-dir%0A%09--without-opt-dir%0A%09--with-opt-include%0A%09--without-opt-include=$%7Bopt-dir%7D/include%0A%09--with-opt-lib%0A%09--without-opt-lib=$%7Bopt-dir%7D/lib%0A%09--with-make-prog%0A%09--without-make-prog%0A%09--srcdir=.%0A%09--curdir%0A%09--ruby=/Users/jbr15998/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)%0A%09--with-curl-dir%0A%09--without-curl-dir%0A%09--with-curl-include%0A%09--without-curl-include=$%7Bcurl-dir%7D/include%0A%09--with-curl-lib%0A%09--without-curl-lib=$%7Bcurl-dir%7D/lib%0A/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in%20%60try_do':%20The%20compiler%20failed%20to%20generate%20an%20executable%20file.%20(RuntimeError)%0AYou%20have%20to%20install%20development%20tools%20first.%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in%20%60block%20in%20try_compile'%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:524:in%20%60with_werror'%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in%20%60try_compile'%0A%09from%20extconf.rb:52:in%20%60block%20in%20have_constant'%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in%20%60block%20in%20checking_for'%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in%20%60block%20(2%20levels)%20in%20postpone'%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in%20%60open'%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in%20%60block%20in%20postpone'%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in%20%60open'%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in%20%60postpone'%0A%09from%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in%20%60checking_for'%0A%09from%20extconf.rb:44:in%20%60have_constant'%0A%09from%20extconf.rb:62:in%20%60%3Cmain%3E'%0A%0ATo%20see%20why%20this%20extension%20failed%20to%20compile,%20please%20check%20the%20mkmf.log%20which%20can%20be%20found%20here:%0A%0A%20%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/curb-0.9.3/mkmf.log%0A%0Aextconf%20failed,%20exit%20code%201%0A%0AGem%20files%20will%20remain%20installed%20in%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/curb-0.9.3%20for%20inspection.%0AResults%20logged%20to%20/Users/jbr15998/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/curb-0.9.3/gem_make.out%0A+repo:fastlane/fastlane
ERROR [2017-04-13 10:37:31.03]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.26.1"

default_platform :ios

platform :ios do

    before_all do
        # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
        # ensure_git_status_clean

        cocoapods(use_bundle_exec: false)
    end

    desc "Run tests"
    lane :test do
        scan(scheme: "fastlane.demo")
        slather
    end

    desc "Build"
    lane :build do |options|
        gym(scheme: options[:"scheme"],
            clean: true,
            configuration: 'Debug')
    end

    desc "Archive"
    lane :archive do |options|
        # Get env from options
        # Update icon with backup_file => badge => restore_badge
        # Upload archive on nexus (scp ?)

        ipa_basename = ENV['IPA_BASENAME']
        ipa_name_suffix = "-v#{get_version_number}-#{options[:env]}"
        ipa_name = "#{ipa_basename}#{ipa_name_suffix}.ipa"
        ipa_path = "#{ENV['BUILD_DIR']}/#{ipa_name}"

        #color = options[:"env"] == "qualif" ? "blue" : "green"
        badge(shield: "Version-#{ipa_name_suffix}-blue")

        gym(scheme: options[:"scheme"],
            clean: true,
            configuration: options[:"configuration"],
            output_directory: ENV['BUILD_DIR'],
            output_name: "#{ipa_name}",
            export_method: "development")

            puts ipa_path
    end

    desc "Archive and launch on simulator"
    lane :launch_on_sim do

        ipa_path = archive(configuration: 'Debug')
        #sh("unzip #{ipa_path}")
        #app_path = "#{ENV['BUILD_DIR']}/Payloads/#{ipa_basename}"
        #simulator(ipa_path: "builds/#{final_name}")
    end

    desc "Install ipa on simulator"
    lane :install_ipa_on_sim do |options|
        ipa_path = options[:"ipa_path"]

        sh("open -a Simulator")
        sh("xcrun simctl install booted #{ipa_path}")
    end

    desc "Submit to TestFlight"
    lane :beta do
        # match(type: "appstore") # more information: https://codesigning.guide
        gym
        pilot
    end

    desc "Submit to AppStore"
    lane :store do
        # match(type: "appstore")
        # snapshot
        gym # Build your app - more options available
        deliver(force: true)
        # frameit
    end

    # You can define as many lanes as you want

    after_all do |lane|
        # This block is called, only if the executed lane was successful

        # slack(
        #   message: "Successfully deployed new App Update."
        # )
    end

    error do |lane, exception|
        #   slack(message: exception.message,
        #     success: false,
        #     payload: { "Output" => exception.error_info.to_s })
    end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.opengroupe.fastlane.demo" # The bundle identifier of your app
apple_id "jeremy.brault@open-groupe.com" # Your Apple email address

team_id "VEHHT4GGZS"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| psych                     | 2.0.8        |
</details>

*generated on:* **2017-04-13**
</details>

### Additional info

Here is the content of the log file mentioned in the output :

find_executable: checking for curl-config... -------------------- yes

--------------------

"/usr/bin/clang -o conftest -I/Users/jbr15998/.fastlane/bin/bundle/include/ruby-2.2.0/x86_64-darwin15 -I/Users/jbr15998/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/backward -I/Users/jbr15998/.fastlane/bin/bundle/include/ruby-2.2.0 -I. -I/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.13.0/fastlane_lib/dependencies/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -pipe  -g conftest.c  -L. -L/Users/jbr15998/.fastlane/bin/bundle/lib -L. -L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.13.0/fastlane_lib/dependencies/lib -fstack-protector     -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc  -lcurl"
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk' [-Wmissing-sysroot]
In file included from conftest.c:1:
In file included from /Users/jbr15998/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/jbr15998/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/jbr15998/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

**Comment by timritzer** [comment]
Definitely an issue when trying to install gems inside fastlane on 10.12. Very frustrating.

**Comment by slhodson969** [comment]
I'm having the same issue when trying to use the badge action.

**Comment by slhodson969** [comment]
I fixed my issue by installing imagemagick@6

`brew install imagemagick@6`

I tried this because of this issue https://github.com/HazAT/badge/issues/46
