### ISSUE TITLE
Error on require gem

### ISSUE THREAD

**Issue by regnerjr** [fastlane/fastlane#889]
When running any lane on latest fast lane an error is thrown when trying to include a gem.
We are including the 'rest-client' gem to do a github comment when builds finish. 
The 'rest-client' gem is listed in our Gemfile, and installed.

Thanks for any help. 

```
$ fastlane --version
fastlane 1.41.0
$ gem list | grep rest
rest-client (1.8.0)
```

The error message is:
```
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- rest-client (LoadError)
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from Fastfile:18:in `parsing_binding'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/lib/fastlane/fast_file.rb:48:in `eval'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/lib/fastlane/fast_file.rb:48:in `block in parse'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/lib/fastlane/fast_file.rb:37:in `chdir'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/lib/fastlane/fast_file.rb:37:in `parse'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/lib/fastlane/fast_file.rb:27:in `initialize'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/lib/fastlane/lane_manager.rb:12:in `new'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/bin/fastlane:35:in `block (2 levels) in run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/bin/fastlane:152:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.0/bin/fastlane:158:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.3/bin/fastlane:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'
```

(Note: this error is not generated on fast lane 1.39.0)

# Fastfile

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available
require 'rest-client'

fastlane_version "1.39.0"

default_platform :ios

def load_env(the_env) Dotenv.overload ".env.#{the_env.to_s.downcase}" end

platform :ios do
  before_all do
    ENV['IS_PULL_REQUEST'] = ENV['PULL']
    ENV['SERVER_ENV'] = ENV['env']
    if is_ci()
      ENV['ARTIFACTS'] = ENV['CIRCLE_ARTIFACTS']
    else
      ENV['ARTIFACTS'] = "./fastlane/artifacts/"
    end
  end

  lane :setup do
    carthage(platform: 'iOS',
             use_binaries: false)
    cocoapods
  end

  lane :xcode do
    install_xcode_plugin(
      url: "https://github.com/fastlane/FixCode/releases/download/0.1.0/FixCode.xcplugin.zip"
    )
  end

  lane :test do
    setup()
    scan(
      clean: true,
      scheme: ENV['SCHEME'],
      output_directory: ENV['ARTIFACTS'],
      buildlog_path: ENV['ARTIFACTS'],
      configuration: 'Debug',
      destination: 'platform=iOS Simulator,OS=9.0,name=iPhone 6',
      sdk: 'iphonesimulator',
      slack_only_on_failure: true
    )
  end

  lane :build do
    setup()

    cert(output_path: "./certs")
    sigh(output_path: "./fastlane/profiles")
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

    gym(
      scheme: ENV['SCHEME'],
      configuration: ENV['CONFIGURATION'],
      codesigning_identity: ENV['IDENTITY'],
      output_directory: './fastlane/build',
      buildlog_path: ENV['ARTIFACTS'],
      use_legacy_build_api: true
    )
  end

  lane :increment do
    increment_build_number build_number: "3000.#{ENV['CIRCLE_BUILD_NUM']}"
  end

  desc "Build an ipa locally"
  lane :local do
    load_env(:recengine)
    load_env(:alpha)
    load_env(:dev)

    increment_build_number build_number: "3000.1568"

    build()
  end

  desc "Submit a new Dev Build to Hockeyapp"
  lane :qa do
    load_env(:nsi)
    load_env(:qa)

    if !is_ci() || ENV['IS_PULL_REQUEST']
      env = "dev"
      if ENV['SERVER_ENV']
        env = ENV['SERVER_ENV']
      end

      load_env(:"#{env}")

      increment()
      build()

      hockey(
        ipa: Actions.lane_context[ Actions::SharedValues::IPA_OUTPUT_PATH ],
        public_identifier: ENV["HOCKEY_DEV_APP_ID"],
        notes: Actions.last_git_commit,
        api_token: ENV['HOCKEYAPP_TOKEN']
      )
      config_url = Actions.lane_context[SharedValues::HOCKEY_BUILD_INFORMATION]['config_url']
      version = config_url.split('/')[-1]

      post_comment_to_pr("CircleCI: Download requested build hitting the #{env} server for #{ENV["CIRCLE_SHA1"]} at #{Actions.lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]}/app_versions/#{version}/")
    end
  end

  desc "Submit a new Alpha Build to Apple TestFlight, that points to the dev server"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    load_env(:recengine)
    load_env(:alpha)
    load_env(:dev)

    if !is_ci() || ENV['IS_PULL_REQUEST'] || ENV['RUN_NIGHTLY_BUILD']
      increment()
      build()

      pilot(changelog: Actions.last_git_commit)

      slack(
        message: "fastlane deploy of Alpha app to TestFlight was successful :rocket:, expect a push from :apple:",
        success: true,
        default_payloads: [:lane, :test_result, :git_branch, :git_author]
      )
    end

  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    load_env(:recengine)
    load_env(:beta)
    load_env(:prod)

    increment()
    build()

    pilot(changelog: Actions.last_git_commit)

    slack(
      message: "fastlane deploy of TRIPSTR BETA to TestFlight was successful :rocket:, expect a push from :apple:",
      success: true,
      default_payloads: [:lane, :test_result, :git_branch, :git_author]
    )

  end

  def post_comment_to_pr(comment)
    github_token = ENV['GITHUB_TOKEN']
    repo = ENV['REPO']
    owner = ENV['OWNER']
    issue_number = ENV['PULL']

    if github_token && repo && owner && issue_number
      url = "https://api.github.com/repos/#{owner}/#{repo}/issues/#{issue_number}/comments"
      body = comment

      puts "Trying to post to URL - #{url}"
      RestClient.post url, {body: body}.to_json, {Authorization: "token #{github_token}"}
    end
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # Leaving this in case we want it later
    # slack(
    #   message: "fastlane deploy to TestFlight was successful :rocket:, check yo mail",
    #   success: true,
    #   default_payloads: [:lane, :test_result, :git_branch, :git_author]
    # )
  end

  error do |lane, exception|
    if ENV['IS_PULL_REQUEST'] && ENV['REPO'] && ENV['OWNER']
      post_comment_to_pr("CircleCI: Unable to complete build request for #{ENV["CIRCLE_SHA1"]}. See https://circleci.com/gh/#{ENV['OWNER']}/#{ENV['REPO']}/#{ENV['CIRCLE_BUILD_NUM']}")
    else
      if is_ci()
        slack(
          message: exception.message,
          success: false
        )
      end
    end
  end
end


# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
```

**Comment by jcampbell05** [comment]
You can't require gems in the current DSL. Fastlane parses the fastlane file in a safe way so you can't just use any ruby method.
