### ISSUE TITLE
Build gets stuck on "Running script 'Check Pods Manifest.lock" when running on El Capitan

### ISSUE THREAD

**Issue by chaitanyakuber** [fastlane/fastlane#893]
## Summary

Build gets stuck on "Running script 'Check Pods Manifest.lock" when running on El Capitan and never finishes.

## Log Output

When I cancel I see

```
▸ Running script 'Check Pods Manifest.lock'
^C/Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.26.5/lib/fastlane_core/command_executor.rb:27:in `each': Interrupt
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.26.5/lib/fastlane_core/command_executor.rb:27:in `block in execute'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.26.5/lib/fastlane_core/command_executor.rb:26:in `spawn'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.26.5/lib/fastlane_core/command_executor.rb:26:in `execute'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gym-1.1.6/lib/gym/runner.rb:76:in `build_app'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gym-1.1.6/lib/gym/runner.rb:10:in `run'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gym-1.1.6/lib/gym/manager.rb:8:in `work'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/actions/gym.rb:22:in `run'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:18:in `block (2 levels) in parsing_binding'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:46:in `execute'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/bin/fastlane:152:in `run'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.41.1/bin/fastlane:158:in `<top (required)>'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/fastlane:23:in `load'
	from /Users/chaitanya/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/fastlane:23:in `<main>'
```

Has anyone else seen this and been able to resolve ?

**Comment by digitaliceltd** [comment]
We got this for a while, however it turned out it wasnt actually stuck. Are you running this on a swift project? It may be that XCPretty needs updating, as older versions never produced any outputs for SwiftCompile. If we left it long enough we eventually saw something happening.

Hope this helps

**Comment by chaitanyakuber** [comment]
Nope, not a Swift project.
New thinking is it could be xcode 7.1.1 related

**Comment by ohwutup** [comment]
Hey everyone, I am going to close this issue as its been a while since there has been some activity. Please try updating to the newest versions of the tools and if you're still having an issue feel free to comment and we will reopen it! Thanks! :octopus:
