### ISSUE TITLE
'xcodebuild -showBuildSettings' without 'clean' timed-out

### ISSUE THREAD

**Issue by thasegaw** [fastlane/fastlane#9008]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
`xcode -showBuildSettings` without `clean` is slower than `xcode -showBuildSettings` with `clean`.
Because most of our project spend over 10 sec on executing this, _fastlane_ fail to build due to timeout.
```
$ time xcodebuild -showBuildSettings -workspace ./SampleApp.xcworkspace -scheme SampleApp -configuration Debug
    The name of this job.             :xcodebuild -showBuildSettings -workspace ./SampleApp.xcworkspace -scheme
    CPU seconds spent in user mode.   :9.88s
    CPU seconds spent in kernel mode. :2.21s
    Elapsed time in seconds.          :13.41s
    The  CPU percentage.              :90%

$ time xcodebuild clean -showBuildSettings -workspace ./Sample.xcworkspace -scheme SampleApp -configuration Debug
    The name of this job.             :xcodebuild clean -showBuildSettings -workspace ./Sample.xcworkspace
    CPU seconds spent in user mode.   :2.24s
    CPU seconds spent in kernel mode. :0.78s
    Elapsed time in seconds.          :3.10s
    The  CPU percentage.              :97%
```

If `clean` action does not influence other _fastlane_ action,  `showBuildSettings` should be executed with `clean`.
The difference between the command without `clean` and the command with `clean` is ..
```
-Build settings for action build and target Sample:
-    ACTION = build
+Build settings for action clean and target Sample:
+    ACTION = clean
     AD_HOC_CODE_SIGNING_ALLOWED = NO
     ALTERNATE_GROUP = YAHOO\Domain Users
     ALTERNATE_MODE = u+w,go-w,a+rX
@@ -26,7 +26,7 @@
     AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
     BITCODE_GENERATION_MODE = marker
     BUILD_ACTIVE_RESOURCES_ONLY = NO
-    BUILD_COMPONENTS = headers build
+    BUILD_COMPONENTS =
     BUILD_DIR = /Users/thasegaw/Library/Developer/Xcode/DerivedData/Sample-bfnxxtalriumqkdwoxzbqvxknuvk/Build/Products
     BUILD_ROOT = /Users/thasegaw/Library/Developer/Xcode/DerivedData/Sample-bfnxxtalriumqkdwoxzbqvxknuvk/Build/Products
     BUILD_STYLE =
```

##### Complete output when running fastlane, including the stack trace and command used
```
[15:50:18]: Command timed out after 10 seconds on try 1 of 4, trying again...
[15:50:28]: Command timed out after 10 seconds on try 2 of 4, trying again...
[15:50:38]: Command timed out after 10 seconds on try 3 of 4, trying again...
[15:50:49]: Command timed out after 10 seconds on try 4 of 4
.
.
.
[15:50:49]: xcodebuild -showBuildSettings timed-out after 10 seconds and 3 retries. You can override the timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | xcode_select                        | 0           |
| 4    | sigh                                | 6           |
| 5    | sigh                                | 4           |
| 6    | sigh                                | 4           |
| 7    | sigh                                | 4           |
| 8    | sigh                                | 4           |
| 💥   | gym                                 | 44          |
+------+-------------------------------------+-------------+

[15:50:49]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/ui/interface.rb:138:in `crash!': [!] xcodebuild -showBuildSettings timed-out after 10 seconds and 3 retries. You can override the timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES  (FastlaneCore::Interface::FastlaneCrash)
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/project.rb:310:in `rescue in build_settings'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/project.rb:302:in `build_settings'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/project.rb:250:in `supported_platforms'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/project.rb:238:in `mac?'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/gym/lib/gym/detect_values.rb:98:in `detect_platform'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/gym/lib/gym/detect_values.rb:31:in `set_additional_default_values'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/gym/lib/gym.rb:25:in `config='
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/gym/lib/gym/manager.rb:4:in `work'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/actions/gym.rb:21:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/runner.rb:226:in `chdir'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
    from Fastfile:31:in `block (2 levels) in parsing_binding'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/lane.rb:33:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/lane.rb:33:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/runner.rb:45:in `chdir'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/runner.rb:45:in `execute'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.28.5/bin/fastlane:20:in `<top (required)>'
    from /usr/local/bin/fastlane:23:in `load'
    from /usr/local/bin/fastlane:23:in `<main>'
[15:50:55]: Exit status of command: 'fastlane build' was 1
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.12.4                                                 |
| Ruby                        | 2.3.1                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.12.2                                      |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane                    |
| Host                        | Mac OS X 10.12.4 (16E195)                               |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                             |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode/Xcode_8_3_1.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.17.0"
 
default_platform :ios
 
 
platform :ios do
 
  before_all do
  end
 
  desc "Build and Deploy a new version to the Approduce"
  lane :build do
    gym(scheme: 'test',
      export_method: "enterprise"
    )
  end

  after_all do |lane|
  end
 
  error do |lane, exception|
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.5  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| json                      | 1.8.5        |
| io-console                | 0.4.5        |
| bundler                   | 1.14.6       |
</details>

*generated on:* **2017-04-27**
</details>

**Comment by nishitsplashmath** [comment]
I am facing the same issue. I am using snapshot to automate the snapshot generation. This is what i get in my test report "[!] xcodebuild -showBuildSettings timed-out after 10 seconds and 3 retries. You can override the timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES". I tried setting "FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT" in the snapfile but it didn't work.

**Comment by jaybowong** [comment]
Same here. I got this timeout issue A LOT. I've already updated fastlane to v2.28.7.

It's wired to me that this simple command `xcodebuild -showBuildSettings -workspace MyApp.xcworkspace -scheme MyApp` would lead to a timeout. Maybe my MacBook is too slow?

Would it be a simple solution to increase the 10s timeout to 30s?

```
[21:33:30]: -----------------
[21:33:30]: --- Step: gym ---
[21:33:30]: -----------------
[21:33:30]: $ xcodebuild -list -workspace MyApp.xcworkspace
[21:33:36]: $ xcodebuild -showBuildSettings -workspace MyApp.xcworkspace -scheme MyApp
[21:33:46]: Command timed out after 10 seconds on try 1 of 4, trying again...
[21:33:56]: Command timed out after 10 seconds on try 2 of 4, trying again...
[21:34:06]: Command timed out after 10 seconds on try 3 of 4, trying again...
[21:34:16]: Command timed out after 10 seconds on try 4 of 4
+--------------------+-------------------------------------------------------------------------------+
|                                            Lane Context                                            |
+--------------------+-------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                           |
| PLATFORM_NAME      | ios                                                                           |
| LANE_NAME          | ios store                                                                     |
| BUILD_NUMBER       | 1104                                                                          |
| IPA_OUTPUT_PATH    | /Users/jaybo/Downloads/fastlane-output/MyApp2.7.2(1104)-store-production-ad  |
|                    | hoc.ipa                                                                       |
| DSYM_OUTPUT_PATH   | /Users/jaybo/Downloads/fastlane-output/MyApp2.7.2(1104)-store-production-ad  |
|                    | hoc.app.dSYM.zip                                                              |
| XCODEBUILD_ARCHIVE | /Users/jaybo/Downloads/fastlane-output/MyApp2.7.2(1104)-store-production.xc  |
|                    | archive                                                                       |
+--------------------+-------------------------------------------------------------------------------+
[21:34:16]: xcodebuild -showBuildSettings timed-out after 10 seconds and 3 retries. You can override the timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES 

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 4           |
| 4    | gym                                 | 106         |
| 💥   | gym                                 | 45          |
+------+-------------------------------------+-------------+

[21:34:16]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/interface.rb:138:in `crash!': [!] xcodebuild -showBuildSettings timed-out after 10 seconds and 3 retries. You can override the timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES  (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/project.rb:310:in `rescue in build_settings'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/project.rb:302:in `build_settings'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/project.rb:250:in `supported_platforms'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/project.rb:238:in `mac?'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/gym/lib/gym/detect_values.rb:98:in `detect_platform'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/gym/lib/gym/detect_values.rb:31:in `set_additional_default_values'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/gym/lib/gym.rb:25:in `config='
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/gym/lib/gym/manager.rb:4:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/actions/gym.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from /Users/jaybo/MyApp/ios/fastlane/tasks.rb:254:in `export_development_ipa_and_upload'
	from /Users/jaybo/MyApp/ios/fastlane/tasks.rb:65:in `do_all_tasks'
	from Fastfile:50:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.7/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by mgrebenets** [comment]
@thasegaw What's your Xcode version?

As far as I can see from the code, requirement to use `clean` was removed for Xcode 8.3 and above.

For example:

```ruby
      if FastlaneCore::Helper.xcode_at_least?('8.3')
        command = "xcodebuild -showBuildSettings #{xcodebuild_parameters.join(' ')}"
      else
        command = "xcodebuild clean -showBuildSettings #{xcodebuild_parameters.join(' ')}"
      end
```

There used to be an issue with not using `clean` in 8.2. Then it seems everyone though it was fixed in 8.3. But then you have this issue again.

So maybe it wasn't fixed with 8.3 and `clean` needs to be brought back.

**Comment by thasegaw** [comment]
@mgrebenets My version is 8.3.1. Maybe this issue is caused by performance of mac. 
It does not occur with Macbook Pro 2016(3.3 GHz i7, 16 GB RAM).

**Comment by taquitos** [comment]
Lots of little things changed between 8.3.x versions 😓 maybe upgrading will help too

**Comment by thasegaw** [comment]
This issue is caused by performance of my mac.
