### ISSUE TITLE
`brew cask install fastlane` fails in install script

### ISSUE THREAD

**Issue by aksswami** [fastlane/fastlane#9013]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Installing `fastlane` with `brew-cask` fails. fastlane files are getting copied to home_dir but after that install script exit with <signal 13>. This results in brew cask reporting that fastlane failed to install.

```
brew cask install fastlane
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/fastlane.zip
Already downloaded: /Users/XXX/Library/Caches/Homebrew/Cask/fastlane--2.28.4.zip
==> Verifying checksum for Cask fastlane
==> Installing Cask fastlane
==> Running installer script /usr/local/Caskroom/fastlane/2.28.4/install
==>
==> fastlane is already installed at /Users/XXX/.fastlane/bin
==> The installer will now run the uninstall script to remove your existing fastlane bundle...
==>
==>
==> You can now remove fastlane from your search path by editing your ~/.zshrc file.
==> fastlane was uninstalled successfully!
==>
==>
==> Done uninstalling, your regular installation will now commence. 🚕 💨
==> Installing fastlane to /Users/XXX/.fastlane/bin... this might take a few seconds
==>
==>
==> Successfully copied fastlane to /Users/XXX/.fastlane/bin
==>
==>
Error: Command failed to execute!

==> Failed command:
#<Pathname:/usr/local/Caskroom/fastlane/2.28.4/install> -p -u -b

==> Standard Output of failed command:
fastlane is already installed at /Users/XXX/.fastlane/bin
The installer will now run the uninstall script to remove your existing fastlane bundle...
You can now remove fastlane from your search path by editing your ~/.zshrc file.
fastlane was uninstalled successfully!
Done uninstalling, your regular installation will now commence. 🚕 💨
Installing fastlane to /Users/XXX/.fastlane/bin... this might take a few seconds
Successfully copied fastlane to /Users/XXX/.fastlane/bin



==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 4807 SIGPIPE (signal 13)>
Error: nothing to install
```

**Comment by aksswami** [comment]
The installer is working fine, if I download the zip and execute it with option `-u -p -b`.

```
./install -u -p -b
fastlane is already installed at /Users/XXX/.fastlane/bin
The installer will now run the uninstall script to remove your existing fastlane bundle...
You can now remove fastlane from your search path by editing your ~/.zshrc file.
fastlane was uninstalled successfully!
Done uninstalling, your regular installation will now commence. 🚕 💨
Installing fastlane to /Users/XXX/.fastlane/bin... this might take a few seconds
Successfully copied fastlane to /Users/XXX/.fastlane/bin

Updating installed gems
Updating fastlane
Fetching: fastlane-2.28.5.gem (100%)
Successfully installed fastlane-2.28.5
Gems updated: fastlane
Cleaning up installed gems...
Attempting to uninstall fastlane-2.28.3
Successfully uninstalled fastlane-2.28.3
Clean Up Complete
Detected shell config file at path '~/.zshrc'
Please add the following line to your zsh profile:

export PATH="$HOME/.fastlane/bin:$PATH"

After doing so close the terminal session and restart it to start using fastlane 🚀
```

**Comment by aksswami** [comment]
Dump with `--debug` flag.

```
brew cask install fastlane --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/fastlane.zip
==> Calling curl with args ["https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/fastlane.zip", "-C", "0", "-o", "#<Pathname:/Users/XXX/Library/Caches/Homebrew/Cask/fastlane--2.28.4.zip.incomplete>"]
######################################################################## 100.0%
==> Downloaded to -> /Users/XXX/Library/Caches/Homebrew/Cask/fastlane--2.28.4.zip
==> Verifying download
==> Determining which verifications to run for Cask fastlane
==> Checking for verification class Hbc::Verify::Checksum
==> No checksum defined for Cask fastlane, skipping verification
==> 0 verifications defined
==> Installing Cask fastlane
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/XXX/Library/Caches/Homebrew/Cask/fastlane--2.28.4.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/XXX/Library/Caches/Homebrew/Cask/fastlane--2.28.4.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/XXX/Library/Caches/Homebrew/Cask/fastlane--2.28.4.zip", "/var/folders/vh/6szrc2g109z1t5xn63gdhxz00000gn/T/d20170428-26525-1yj1271"]
==> Creating metadata directory /usr/local/Caskroom/fastlane/.metadata/2.28.4/20170427210354.949.
==> Creating metadata subdirectory /usr/local/Caskroom/fastlane/.metadata/2.28.4/20170427210354.949/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask fastlane
==> 2 artifact/s defined
#<Hbc::Artifact::Installer:0x007fca813ef500>
#<Hbc::Artifact::Uninstall:0x007fca813ef460>
==> Installing artifact of class Hbc::Artifact::Installer
==> Running installer script /usr/local/Caskroom/fastlane/2.28.4/install
==> Executing: ["/bin/chmod", "--", "+x", "/usr/local/Caskroom/fastlane/2.28.4/install"]
==> Executing: ["/usr/local/Caskroom/fastlane/2.28.4/install", "-p", "-u", "-b"]
==>
==> fastlane is already installed at /Users/XXX/.fastlane/bin
==> The installer will now run the uninstall script to remove your existing fastlane bundle...
==>
==>
==> You can now remove fastlane from your search path by editing your ~/.zshrc file.
==> fastlane was uninstalled successfully!
==>
==> Done uninstalling, your regular installation will now commence. 🚕 💨
==> Installing fastlane to /Users/XXX/.fastlane/bin... this might take a few seconds
==>
==>
==> Successfully copied fastlane to /Users/XXX/.fastlane/bin
==>
==>
==> Purging files for version 2.28.4 of Cask fastlane
Error: Command failed to execute!

==> Failed command:
#<Pathname:/usr/local/Caskroom/fastlane/2.28.4/install> -p -u -b

==> Standard Output of failed command:
fastlane is already installed at /Users/XXX/.fastlane/bin
The installer will now run the uninstall script to remove your existing fastlane bundle...
You can now remove fastlane from your search path by editing your ~/.zshrc file.
fastlane was uninstalled successfully!
Done uninstalling, your regular installation will now commence. 🚕 💨
Installing fastlane to /Users/XXX/.fastlane/bin... this might take a few seconds
Successfully copied fastlane to /Users/XXX/.fastlane/bin



==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 26670 SIGPIPE (signal 13)>
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
```
