### ISSUE TITLE
Premission Denied while running shell script

### ISSUE THREAD

**Issue by nsainath1** [fastlane/fastlane#905]
Hi, 

I am getting permission denied error while i try to run shell script file. 

I have copied file to "/Users/Nanjunda/Desktop/MyProject/fastlane/scripts/uploadToDropbox.sh"

Fastfile
```
default_platform :ios
platform :ios do
  before_all do
    increment_build_number
  end

  lane :UAT do
    gym(workspace: “./Project.xcworkspace")
  end

  after_all do
    sh "./scripts/uploadToDropbox.sh"  
  end
end
```

Error 

```
[22:59:27]: ------------------------------------------
[22:59:27]: --- Step: ./scripts/uploadToDropbox.sh ---
[22:59:27]: ------------------------------------------
[22:59:27]: [SHELL COMMAND]: ./scripts/uploadToDropbox.sh
[22:59:27]: Variable Dump:
[22:59:27]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios UAT", :BUILD_NUMBER=>"66"}
[22:59:27]: Permission denied - ./scripts/uploadToDropbox.sh

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | default_platform             | 0           |
| 2    | increment_build_number       | 0           |
| 3    | ./scripts/uploadToDropbox.sh | 0           |
+------+------------------------------+-------------+

[22:59:27]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/helper/sh_helper.rb:25:in `popen': Permission denied - ./scripts/uploadToDropbox.sh (Errno::EACCES)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/helper/sh_helper.rb:25:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/fast_file.rb:182:in `block in sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/fast_file.rb:181:in `sh'
	from Fastfile:44:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/runner.rb:55:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/runner.rb:55:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/bin/fastlane:136:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/bin/fastlane:142:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

```

**Comment by xfreebird** [comment]
Mostly likely its missing the execution permission.

```shell
chmod +x ./scripts/uploadToDropbox.sh
```

then commit the changes.

**Comment by nsainath1** [comment]
Changed my code to 

```
  after_all do
    sh chmod +x ./scripts/uploadToDropbox.sh
  end
```

But i see below error now 

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.3/lib/fastlane/fast_file.rb:52:in `rescue in block in parse': Syntax error in your Fastfile on line 44: Fastfile:44: syntax error, unexpected tIDENTIFIER, expecting keyword_end (RuntimeError)
    sh chmod +x ./scripts/uploadToDropbox.sh
```

**Comment by nsainath1** [comment]
Thanks it worked. 

```
sh "bash ./scripts/uploadToDropbox.sh" 
```

**Comment by nsainath1** [comment]
I made the above change. When i run fastlane. It will be waiting for a key input. Unless i hit enter it will never proceed further. 

Below the code 

```
  after_all do
    sh "bash ./scripts/dropbox_uploader.sh"
  end
```
I have cleared all the content of .sh file to - 

```
echo "Print this..."

```

**Comment by xfreebird** [comment]
It has to work. It must be something else.

When I wrote ```chmod +x ./scripts/uploadToDropbox.sh```. I meant you to execute that manually from command line to make the script executable. The error you initially were getting is because the "./scripts/uploadToDropbox.sh" is missing the executable flag.

**Comment by omerjanjua** [comment]
In my FastFile I did 
`sh "chmod 775 ./scripts/dropbox_uploader.sh"`
then `sh "./scripts/dropbox_uploader.sh"`
works fine for me.

**Comment by nsainath1** [comment]
@omerjanjua Your solution solves the problem. 

Closing the issue
