### ISSUE TITLE
unlock_keychain fails using Jenkins - exit status 181

### ISSUE THREAD

**Issue by agustindc-rga** [fastlane/fastlane#9073]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
On a mac with macOS Sierra, running jenkins.
**unlock_keychain** is failing with a exit status of 181. Performing the same commands via terminal (as the jenkins user) works correctly.
This also occurs when using the **setup_jenkins** action.

However if I log in as another user and copy the .keychain file to  ~/Desktop then the **unlock_keychain** command works well.

"Shell command exited with exit status 181 instead of 0."

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

bash-3.2$ fastlane run unlock_keychain path:*******/Jenkins.keychain password:"*****" add_to_search_list:replace --capture_output
### Captured Output

Command Used: `run unlock_keychain path:*******/Jenkins.keychain password:******* add_to_search_list:replace`
<details><summary>Output/Log</summary>

```

DEBUG [2017-05-04 14:39:54.51]: Checking if there are any plugins that should be loaded...
DEBUG [2017-05-04 14:39:54.54]: Using path: *******/Jenkins.keychain
DEBUG [2017-05-04 14:39:54.54]: Using password: *******
DEBUG [2017-05-04 14:39:54.54]: Using add_to_search_list: replace
INFO [2017-05-04 14:39:54.55]: -----------------------------
INFO [2017-05-04 14:39:54.55]: --- Step: unlock_keychain ---
INFO [2017-05-04 14:39:54.55]: -----------------------------


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.3                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.10.1 (Apple Git-78)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode8.2.1.app/Contents/Developer/               |
| Xcode Version               | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.8 | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.9.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.0       |
</details>

*generated on:* **2017-05-04**
</details>
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!': [!] Shell command exited with exit status 181 instead of 0. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/helper/sh_helper.rb:55:in `sh_control_output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/helper/sh_helper.rb:10:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/actions/unlock_keychain.rb:26:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/one_off.rb:41:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/commands_generator.rb:192:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.8/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by agustindc-rga** [comment]
Some more information:

If I run the following commands instead of **unlock_keychain** then **match** seems to work correctly and the build continues successfully.

```
/usr/bin/security unlock-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
/usr/bin/security -v list-keychains -s "${KEYCHAIN_PATH}"
/usr/bin/security -v set-keychain-settings -t 600 "${KEYCHAIN_PATH}"
/usr/bin/security -v default-keychain -s "${KEYCHAIN_PATH}"
```

**Comment by lyndsey-ferguson** [comment]
You wrote that Jenkins fails to do this. Usually Jenkins is setup to run as a different user. Are you the using the Jenkins account when you get the error? Also, Jenkins will usually log into a slave with a different shell environment than a regular user, are you certain that you are using the same environment (in terms of which ENV variables are setup).

**Comment by agustindc-rga** [comment]
Yes the errors occur both when triggering the jenkins job (which runs as the jenkins user) and also when acting the the jenkins user in the terminal (via `su jenkins`).

**Comment by agustindc-rga** [comment]
I've also found the using the following fastlane commands also work since they mirror the commands mentioned in a previous comment:

**Comment by lyndsey-ferguson** [comment]
Can you run `printenv` for the Jenkins user and a user that can run this command without the failure and post the results here (taking out any sensitive info)?

**Comment by lacostej** [comment]
I have a similar error caused by a (it seems) different scenario. I'll create an issue and link it here.

**Comment by lacostej** [comment]
@agustindc-rga in #9462 the heuristic was incorrectly identifying the keychain path, causing 181 errors. I fixed the issue.

Maybe your issue was caused by a similar problem. If not, I just added some more logging which coud help us understand why it fails for you.

If you are able to try the fastlane github HEAD and let us know how it goes.
