### ISSUE TITLE
Spaceship, returns an error when you tried to test with apple id without membership

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#9098]
ruby 2.4.0

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When i have tried to connect with apple id without membership i have got this error

```
 Spaceship::Tunes.login(username, password)
  Spaceship::Tunes::Application.all

```
##### Complete output when running fastlane, including the stack trace and command used

```
> You can use: `--capture_output` as the last commandline argument to get that collected for you

NameError: uninitialized constant FastlaneCore::Globals
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/globals.rb:7:in `verbose?'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:475:in `rescue in with_retry'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:463:in `with_retry'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:618:in `send_request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:507:in `request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/tunes_client.rb:238:in `applications'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/application.rb:53:in `all'
	from (irb):21
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

pc67:Transporter Michelin$ bundle exec fastlane env
/Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/fastlane/lib/fastlane/commands_generator.rb:45:in `ensure in start': uninitialized constant FastlaneCore::Globals (NameError)
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/fastlane/lib/fastlane/commands_generator.rb:51:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/bin/fastlane:20:in `<top (required)>'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bin/fastlane:22:in `load'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bin/fastlane:22:in `<main>'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>

**Comment by KrauseFx** [comment]
There is something wrong with the imports happening. It looks like you're using _fastlane_ from `rails`, right? Can you try adding `require 'fastlane_core'`?

**Comment by bolom** [comment]
@KrauseFx same error

```
pc67:Transporter Michelin$ rails c
/Users/Michelin/.rvm/gems/ruby-2.4.0/gems/to_words-1.1.0/lib/to_words.rb:37: warning: constant ::Fixnum is deprecated
Loading development environment (Rails 5.0.2)
2.4.0 :001 > require 'fastlane_core'
 => false 
2.4.0 :002 > require 'fastlane'
 => false 
2.4.0 :003 > require 'spaceship'
 => false 
2.4.0 :004 > Spaceship::Tunes.login(username, password)
(...)
2.4.0 :007 > Spaceship::Tunes.login(username, password)
 => #<Spaceship::TunesClient:0x007fa25038b798 @current_team_id=nil, @cookie=#<HTTP::CookieJar:0x007fa25038b590 @store=#<HTTP::CookieJar::HashStore:0x007fa24c32ed80 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fa24c32ece0>, @logger=nil, @gc_threshold=150, @jar={"idmsa.apple.com"=>{"/"=>{"aa"=>#<HTTP::Cookie:name="aa", value="654C018F3A43CA9518D31BC0B567A283", domain="idmsa.apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>}}, "apple.com"=>{"/"=>{"dslang"=>#<HTTP::Cookie:name="dslang", value="US-EN", domain="apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>, "site"=>#<HTTP::Cookie:name="site", value="USA", domain="apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>, "acn01"=>#<HTTP::Cookie:name="acn01", value="aZDt+GAtWGaq8Jf9vmD4rkGV6qfVusqN5WkbZwASKV5yivoL", domain="apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=31536000, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>, "myacinfo"=>#<HTTP::Cookie:name="myacinfo", value="DAWTKNV2b41a99187c2b883aa6359d7ee84e3874b020b537a035454e610a4c47cd6790266e9b31a33d95ceef2d23a29379fcb066fae652b0a9c58a63cdb922bb29e5010401fdac74f30e5b7c4175c15162ddd0f2c6a87bef05836ac795cee5db5c7693a6b92743b2d4902a9a3c8c24ad2ff0054d0de3ceaa4d91dfa9eb19523c13be1412b7952c2d68ec50f01c596fa8a14000046109cb9965791677e536cc6d1bd06a0ecc1b3e69025e86107543d7dd4ba926bde11245d5c2f8c9cde297ba05ad7b32fab51a00765e43383fab3c4150d7227b8a209eb546da64fa04d3546b970eff6ea15ed998b1ea8bd3e0487dd1a69b6fbb7b37616137646634663238313639343565653530383934383862346539343636353965613362373564MVRYV2", domain="apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>}}, "itunesconnect.apple.com"=>{"/"=>{"dqsid"=>#<HTTP::Cookie:name="dqsid", value="H1zNR-mt5K3hhORAfwpX-0uNYFzLH5IkymCxxAqPQH8", domain="itunesconnect.apple.com", for_domain=false, path="/", secure=true, httponly=true, expires=nil, max_age=1800, created_at=2017-05-09 12:41:44 -0400, accessed_at=2017-05-09 12:41:44 -0400 origin=https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa>, "wosid"=>#<HTTP::Cookie:name="wosid", value="Nizi6WueGDdpOw8yxsyLi0", domain="itunesconnect.apple.com", for_domain=false, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:44 -0400, accessed_at=2017-05-09 12:41:44 -0400 origin=https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa>, "woinst"=>#<HTTP::Cookie:name="woinst", value="5765", domain="itunesconnect.apple.com", for_domain=false, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:44 -0400, accessed_at=2017-05-09 12:41:44 -0400 origin=https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa>}}}, @gc_index=8>>, @client=#<Faraday::Connection:0x007fa24c32e768 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.11.0"}, @params={}, @options=#<Faraday::RequestOptions timeout=300, open_timeout=300>, @ssl=#<Faraday::SSLOptions verify=true>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fa24c32e650 @handlers=[FaradayMiddleware::ParseJson, FaradayMiddleware::ParseXml, FaradayMiddleware::PlistMiddleware, Faraday::CookieJar, Faraday::Adapter::NetHttp], @app=#<FaradayMiddleware::ParseJson:0x007fa2528aaa38 @app=#<FaradayMiddleware::ParseXml:0x007fa2528aaad8 @app=#<FaradayMiddleware::PlistMiddleware:0x007fa2528aab78 @app=#<Faraday::CookieJar:0x007fa2528aabf0 @app=#<Faraday::Adapter::NetHttp:0x007fa2528aac90 @app=#<Proc:0x007fa2528aada8@/Users/Michelin/.rvm/gems/ruby-2.4.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:152 (lambda)>, @connection_options={}, @config_block=nil>, @jar=#<HTTP::CookieJar:0x007fa25038b590 @store=#<HTTP::CookieJar::HashStore:0x007fa24c32ed80 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fa24c32ece0>, @logger=nil, @gc_threshold=150, @jar={"idmsa.apple.com"=>{"/"=>{"aa"=>#<HTTP::Cookie:name="aa", value="654C018F3A43CA9518D31BC0B567A283", domain="idmsa.apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>}}, "apple.com"=>{"/"=>{"dslang"=>#<HTTP::Cookie:name="dslang", value="US-EN", domain="apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>, "site"=>#<HTTP::Cookie:name="site", value="USA", domain="apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>, "acn01"=>#<HTTP::Cookie:name="acn01", value="aZDt+GAtWGaq8Jf9vmD4rkGV6qfVusqN5WkbZwASKV5yivoL", domain="apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=31536000, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>, "myacinfo"=>#<HTTP::Cookie:name="myacinfo", value="DAWTKNV2b41a99187c2b883aa6359d7ee84e3874b020b537a035454e610a4c47cd6790266e9b31a33d95ceef2d23a29379fcb066fae652b0a9c58a63cdb922bb29e5010401fdac74f30e5b7c4175c15162ddd0f2c6a87bef05836ac795cee5db5c7693a6b92743b2d4902a9a3c8c24ad2ff0054d0de3ceaa4d91dfa9eb19523c13be1412b7952c2d68ec50f01c596fa8a14000046109cb9965791677e536cc6d1bd06a0ecc1b3e69025e86107543d7dd4ba926bde11245d5c2f8c9cde297ba05ad7b32fab51a00765e43383fab3c4150d7227b8a209eb546da64fa04d3546b970eff6ea15ed998b1ea8bd3e0487dd1a69b6fbb7b37616137646634663238313639343565653530383934383862346539343636353965613362373564MVRYV2", domain="apple.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:43 -0400, accessed_at=2017-05-09 12:41:43 -0400 origin=https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42>}}, "itunesconnect.apple.com"=>{"/"=>{"dqsid"=>#<HTTP::Cookie:name="dqsid", value="H1zNR-mt5K3hhORAfwpX-0uNYFzLH5IkymCxxAqPQH8", domain="itunesconnect.apple.com", for_domain=false, path="/", secure=true, httponly=true, expires=nil, max_age=1800, created_at=2017-05-09 12:41:44 -0400, accessed_at=2017-05-09 12:41:44 -0400 origin=https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa>, "wosid"=>#<HTTP::Cookie:name="wosid", value="Nizi6WueGDdpOw8yxsyLi0", domain="itunesconnect.apple.com", for_domain=false, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:44 -0400, accessed_at=2017-05-09 12:41:44 -0400 origin=https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa>, "woinst"=>#<HTTP::Cookie:name="woinst", value="5765", domain="itunesconnect.apple.com", for_domain=false, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2017-05-09 12:41:44 -0400, accessed_at=2017-05-09 12:41:44 -0400 origin=https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa>}}}, @gc_index=8>>>, @options={:content_type=>/\bplist$/}, @content_types=[/\bplist$/]>, @options={:content_type=>/\bxml$/}, @content_types=[/\bxml$/]>, @options={:content_type=>/\bjson$/}, @content_types=[/\bjson$/]>>, @url_prefix=#<URI::HTTPS https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/>, @proxy=nil>, @du_client=#<Spaceship::DUClient:0x007fa252859548 @current_team_id=nil, @cookie=#<HTTP::CookieJar:0x007fa252859480 @store=#<HTTP::CookieJar::HashStore:0x007fa2528593e0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fa252859390>, @logger=nil, @gc_threshold=150, @jar={}, @gc_index=0>>, @client=#<Faraday::Connection:0x007fa252858f58 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.11.0"}, @params={}, @options=#<Faraday::RequestOptions timeout=300, open_timeout=300>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fa252858e40 @handlers=[FaradayMiddleware::ParseJson, FaradayMiddleware::ParseXml, FaradayMiddleware::PlistMiddleware, Faraday::CookieJar, Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTPS https://du-itc.itunes.apple.com/>, @proxy=nil>>, @user="malavoi+fr@gmail.com", @password="t@p@1ID?972", @loggedin=true, @content_provider_id=nil, @sso_token_for_image=nil, @sso_token_for_video=nil, @logger=#<Logger:0x007fa24fbca798 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x007fa24fbca6f8 @datetime_format=nil>, @formatter=#<Proc:0x007fa2528ab9d8@/Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:236>, @logdev=#<Logger::LogDevice:0x007fa24fbca6a8 @shift_period_suffix="%Y%m%d", @shift_size=1048576, @shift_age=0, @filename="/tmp/spaceship1494348101_2920.log", @dev=#<File:/tmp/spaceship1494348101_2920.log>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fa24fbca608>>>, @service_key="e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42"> 
2.4.0 :008 > Spaceship::Tunes::Application.all
NameError: uninitialized constant FastlaneCore::Globals
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/globals.rb:7:in `verbose?'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:475:in `rescue in with_retry'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:463:in `with_retry'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:618:in `send_request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:507:in `request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/tunes_client.rb:238:in `applications'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/application.rb:53:in `all'
	from (irb):8
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
2.4.0 :009 > 

```

**Comment by KrauseFx** [comment]
Can you update the file at path `/Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/globals.rb` and replace line number 7 with 

```ruby
if Object.const_defined?("FastlaneCore") && FastlaneCore.const_defined?("Globals")
```
and run again, without running `bundle update` or `bundle install`?

**Comment by bolom** [comment]
it's returns me an UnauthorizedAccessError however I am not sure if it's correct.  When i am logged directly i have got that

![capture d ecran 10](https://cloud.githubusercontent.com/assets/72155/25863441/e474dc16-34b9-11e7-8c4b-ff040b217d8d.png)


```
2.4.0 :004 >  Spaceship::Tunes::Application.all
Spaceship::Client::UnauthorizedAccessError: Unauthorized Access
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:624:in `block in send_request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:463:in `with_retry'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:618:in `send_request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:507:in `request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/tunes_client.rb:238:in `applications'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/application.rb:53:in `all'
	from (irb):4
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by KrauseFx** [comment]
That error doesn't seem related to the original one, right?

**Comment by bolom** [comment]
> That error doesn't seem related to the original one, right?

I think so.

**Test one** 

```
module Spaceship
  class Globals
    # if spaceship is run with a FastlaneCore available respect the global state there
    # otherwise fallback to $verbose
    def self.verbose?
      if Object.const_defined?("FastlaneCore")
        return FastlaneCore::Globals.verbose?
      end
      return $verbose
    end
  end
end
```

Error

```
2.4.0 :005 >  Spaceship::Tunes::Application.all
NameError: uninitialized constant FastlaneCore::Globals
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/globals.rb:7:in `verbose?'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:475:in `rescue in with_retry'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:463:in `with_retry'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:618:in `send_request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:507:in `request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/tunes_client.rb:238:in `applications'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/application.rb:53:in `all'
	from (irb):5
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Test two**

```
module Spaceship
  class Globals
    # if spaceship is run with a FastlaneCore available respect the global state there
    # otherwise fallback to $verbose
    def self.verbose?
      if Object.const_defined?("FastlaneCore")
        return if Object.const_defined?("FastlaneCore") && FastlaneCore.const_defined?("Globals")
      end
      return $verbose
    end
  end
end

```

Error returned
```
2.4.0 :004 >  Spaceship::Tunes::Application.all
Spaceship::Client::UnauthorizedAccessError: Unauthorized Access
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:624:in `block in send_request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:463:in `with_retry'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:618:in `send_request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/client.rb:507:in `request'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/tunes_client.rb:238:in `applications'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/bundler/gems/fastlane-fc00d68e667c/spaceship/lib/spaceship/tunes/application.rb:53:in `all'
	from (irb):4
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/Michelin/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
2.4.0 :005 > 

```
