### ISSUE TITLE
Updating to 2.9.1 caused failure in deliver step

### ISSUE THREAD

**Issue by aric87** [fastlane/fastlane#9141]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When using 2.29.0, I didn't have any screenshots or metadata, and everything still worked. After updating to 2.29.1, I get a chomp error, but the script continues to run. At the end, I don't have a binary pushed to the store. 

The initial command that's run: `fastlane release scheme:"$FOLDERNAME"`

It looks like the loop for TRADE_REPRESENTATIVE_CONTACT_INFORMATION_VALUES is still running, event though there aren't any defined in the options? 

I was able to update the deliver command in the fastfile to this:     `deliver(force: true, skip_screenshots:true, skip_metadata: true)`  to get it working. 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

the script is run through a lane, but the relevant failures for deliver are here: 
```
[11:26:20]: Login successful

+-----------------------+---------------------------------------------------------------------------------------------------------------+
|                                                        deliver 2.29.1 Summary                                                         |
+-----------------------+---------------------------------------------------------------------------------------------------------------+
| force                 | true                                                                                                          |
| ipa                   | /Users/membersfirst/Code/Cordova/Projects/Stonebridge Country Club/platforms/ios/Stonebridge Country Club.ipa |
| screenshots_path      | ./fastlane/screenshots                                                                                        |
| metadata_path         | ./fastlane/metadata                                                                                           |
| app_version           | 1.1.2                                                                                                         |
| username              | appdev@membersfirst.com                                                                                       |
| app_identifier        | com.membersfirst.stonebridgecountryclub                                                                       |
| edit_live             | false                                                                                                         |
| platform              | ios                                                                                                           |
| skip_binary_upload    | false                                                                                                         |
| skip_screenshots      | false                                                                                                         |
| skip_metadata         | false                                                                                                         |
| submit_for_review     | false                                                                                                         |
| automatic_release     | false                                                                                                         |
| dev_portal_team_id    | M7P78RNDNU                                                                                                    |
| overwrite_screenshots | false                                                                                                         |
+-----------------------+---------------------------------------------------------------------------------------------------------------+

[11:26:21]: Making sure the latest version on iTunes Connect matches '1.1.2' from the ipa file...
[11:26:22]: '1.1.2' is the latest version on iTunes Connect
+--------------------+------------------------------------------------------------------------------------------------------------------------+
|                                                                Lane Context                                                                 |
+--------------------+------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                                                    |
| PLATFORM_NAME      | ios                                                                                                                    |
| LANE_NAME          | ios release                                                                                                            |
| IPA_OUTPUT_PATH    | /Users/membersfirst/Code/Cordova/Projects/Stonebridge Country Club/platforms/ios/Stonebridge Country Club.ipa          |
| DSYM_OUTPUT_PATH   | /Users/membersfirst/Code/Cordova/Projects/Stonebridge Country Club/platforms/ios/Stonebridge Country Club.app.dSYM.zip |
| XCODEBUILD_ARCHIVE | /Users/membersfirst/Library/Developer/Xcode/Archives/2017-05-11/Stonebridge Country Club 2017-05-11 11.25.54.xcarchive |
+--------------------+------------------------------------------------------------------------------------------------------------------------+
[11:26:24]: undefined method `chomp' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 25          |
| 💥   | deliver                             | 5           |
+------+-------------------------------------+-------------+

[11:26:24]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  set_trade_representative_contact_information: undefined method `chomp' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/9140 [open] 0 💬
    4 minutes ago

➡️  how to get XCode user defined settings in a lane
    https://github.com/fastlane/fastlane/issues/6795 [closed] 11 💬
    30 Jan 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/deliver/lib/deliver/upload_metadata.rb:253:in `block in set_trade_representative_contact_information': [!] undefined method `chomp' for nil:NilClass (NoMethodError)
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/deliver/lib/deliver/upload_metadata.rb:252:in `each'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/deliver/lib/deliver/upload_metadata.rb:252:in `set_trade_representative_contact_information'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/deliver/lib/deliver/upload_metadata.rb:115:in `upload'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/deliver/lib/deliver/runner.rb:62:in `upload_metadata'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/deliver/lib/deliver/runner.rb:21:in `run'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/actions/deliver.rb:16:in `run'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:49:in `block (2 levels) in parsing_binding'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.29.1/bin/fastlane:20:in `<top (required)>'
	from /Users/membersfirst/.rvm/rubies/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/membersfirst/.rvm/rubies/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/membersfirst/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.106.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    ENV["GIT_URL"] = "https://bitbucket.org/MF_Development/certificates"

    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    username = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
    team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do |options|
    # snapshot
    gym(scheme: options[:scheme])
    deliver(force: true)
    # frameit
  end

  desc "Add app to iTunes Connect and Dev Portal and create certificates"
  lane :prepare do |options|
    produce(
      app_name: options[:app_name]
    )
    pem(
      generate_p12: true,
      p12_password: "M3mF1rst",
      save_private_key: true,
      output_path: "certificates"
    )
    pem(
      development: true,
      generate_p12: true,
      p12_password: "M3mF1rst",
      save_private_key: true,
      output_path: "certificates"
    )
    match(
      type: "appstore",
      git_url: ENV["GIT_URL"],
      force_for_new_devices: true
    )
    match(
      type: "development",
      git_url: ENV["GIT_URL"],
      force_for_new_devices: true
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.membersfirst.neptunecove" # The bundle identifier of your app
apple_id "appdev@membersfirst.com" # Your Apple email address
team_id "M7P78RNDNU"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.29.1  | ✅ Up-To-Date  |
| match    | 1.0.0   | ✅ Up-To-Date  |
| pem      | 2.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-05-11**
</details>

**Comment by aric87** [comment]
submitted the same time as another issue. Closing in favor of https://github.com/fastlane/fastlane/issues/9140
