### ISSUE TITLE
This build could not be used for external testing because the build is not approved MANY TIMES

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#917]
I've got this stack trace yesterday after pushing update to TestFlight:

```
Update using 'sudo gem update fastlane'
/Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.1/lib/spaceship/tunes/tunes_client.rb:163:in `handle_itc_response': This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. (Spaceship::TunesClient::ITunesConnectError)
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.1/lib/spaceship/tunes/tunes_client.rb:474:in `update_build_trains!'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.1/lib/spaceship/tunes/build_train.rb:100:in `update_testing_status!'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/pilot-1.0.1/lib/pilot/build_manager.rb:109:in `distribute_build'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/pilot-1.0.1/lib/pilot/build_manager.rb:22:in `upload'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/actions/pilot.rb:15:in `run'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/runner.rb:128:in `block in execute_action'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/runner.rb:127:in `chdir'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/runner.rb:127:in `execute_action'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:149:in `method_missing'
    from Fastfile:54:in `block (2 levels) in parsing_binding'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/lane.rb:36:in `call'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/lane.rb:36:in `call'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/runner.rb:51:in `block in execute'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/runner.rb:46:in `chdir'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/runner.rb:46:in `execute'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/bin/fastlane:35:in `block (2 levels) in run'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/bin/fastlane:152:in `run'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.39.0/bin/fastlane:158:in `<top (required)>'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

I was on 1.39.0. I did not notice any useful release notes on this so probably this issue is still exists. It killed 'slack' command so nobody received release notes from me :( We use internal testing only.

**Comment by pronebird** [comment]
log from today:

```
[18:49:32]: Waiting for iTunes Connect to finish processing the new build (1.0 - 82)
[18:50:02]: Successfully finished processing the build
[18:50:02]: You can now tweet: 
[18:50:02]: iTunes Connect #iosprocessingtime 77 minutes
[18:50:02]: Distributing new build to testers
[18:50:09]: Variable Dump:
[18:50:09]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/pronebird/dev/AppName/AppName.ipa", :DSYM_OUTPUT_PATH=>"/Users/pronebird/dev/AppName/AppName.app.dSYM.zip", :SIGH_PROFILE_PATH=>"/Users/pronebird/dev/AppName/AppStore_com.doman.AppName.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/pronebird/dev/AppName/AppStore_com.doman.AppName.mobileprovision"], :SIGH_UDID=>"37a2e3d0-1a2d-4b18-8483-4359d2c969ef", :SIGH_PROFILE_TYPE=>"app-store"}
[18:50:09]: This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | cocoapods                           | 16          |
| 5    | gym                                 | 49          |
| 6    | sigh                                | 14          |
| 7    | pilot                               | 4717        |
+------+-------------------------------------+-------------+

[18:50:09]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
✨  Once crash reporting is enabled, you get a clean output when something goes wrong.
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.2/lib/spaceship/tunes/tunes_client.rb:163:in `handle_itc_response': This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. (Spaceship::TunesClient::ITunesConnectError)
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.2/lib/spaceship/tunes/tunes_client.rb:476:in `update_build_trains!'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.2/lib/spaceship/tunes/build_train.rb:100:in `update_testing_status!'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/pilot-1.0.1/lib/pilot/build_manager.rb:109:in `distribute_build'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/pilot-1.0.1/lib/pilot/build_manager.rb:22:in `upload'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/actions/pilot.rb:15:in `run'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/runner.rb:128:in `block in execute_action'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/runner.rb:127:in `chdir'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/runner.rb:127:in `execute_action'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/fast_file.rb:149:in `method_missing'
    from Fastfile:54:in `block (2 levels) in parsing_binding'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/lane.rb:36:in `call'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/lane.rb:36:in `call'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/runner.rb:51:in `block in execute'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/runner.rb:46:in `chdir'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/runner.rb:46:in `execute'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/bin/fastlane:35:in `block (2 levels) in run'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/bin/fastlane:152:in `run'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.42.0/bin/fastlane:158:in `<top (required)>'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by pronebird** [comment]
Fastlane should not __DIE__ if build is already published.

**Comment by MartinRogalla** [comment]
Ran into the same problem. Would consider this a bug. It's hardcoded to submit it for external beta testing... https://github.com/fastlane/pilot/blob/66a68c78e8eb0191b25de0b152dc9edc4afabfa4/lib/pilot/build_manager.rb#L109-L109

**Comment by aktec** [comment]
Same error.

**Comment by raiffeisennet** [comment]
Same issue here

**Comment by self-creative** [comment]
Same issue too

**Comment by jontelang** [comment]
Same issue here.

**Comment by manuelmarcos** [comment]
Same here too

**Comment by holleboom** [comment]
Same here

**Comment by caoer** [comment]
same issue here too

**Comment by eha11** [comment]
same here.

**Comment by self-creative** [comment]
everybody, I wanna  know,this bug is the spacship's bug or the iTunes‘ bug.about one mouth ago, i used spaceship 0.13.1,and it works OK,but since i upload an error ipa to ITC ,it always raise this issue.

**Comment by pronebird** [comment]
@self-creative @MartinRogalla pointed out that this is pilot's bug.

**Comment by self-creative** [comment]
@pronebird Thanks,Hope it will  be resolved.You konw,every day now, I need manully update build versions for tester.What a bad story,,,,Oh no ,,,heros I need help

**Comment by MartinRogalla** [comment]
@pronebird, I'm not so sure. My ruby skills have much to be desired, but switching the string at https://github.com/fastlane/pilot/blob/66a68c78e8eb0191b25de0b152dc9edc4afabfa4/lib/pilot/build_manager.rb#L109-L109 from `external` to `internal` didn't help for me. So maybe Apple's API has changed and Spaceship needs some modifications.

**Comment by MartinRogalla** [comment]
I just verified that `app.build_trains["...."].update_testing_status!(true, 'internal')` does work. So it is indeed a problem with pilot and not with spaceship. (haha I'm loving these names...)

**Comment by KrauseFx** [comment]
I just checked, `pilot` is calling this line by default
```ruby
uploaded_build.build_train.update_testing_status!(true, 'external')
```

How about I add an option to choose between internal and external testing?

**Comment by KrauseFx** [comment]
Please update to https://github.com/fastlane/pilot/releases/tag/1.2.0 and try the new option. Let me know if that fixes the problem.

Sorry for not replying earlier, I was swamped with the release of [match](https://github.com/fastlane/match)

**Comment by self-creative** [comment]
@KrauseFx hi,I only use spaceship and raise this issue,it will also solved in this update ?

**Comment by self-creative** [comment]
@KrauseFx  hi,I only use spaceship and raise this issue,it will also solved in this update ?

**Comment by pronebird** [comment]
This patch works for me. Thanks @KrauseFx!

**Comment by self-creative** [comment]
my code : 
train = app.build_trains["1.1.0"]
train.builds[0].submit_for_beta_review!(parameters)

But,it also raise following issue:

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.18.0/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.18.0/lib/spaceship/tunes/tunes_client.rb:520:in `update_build_trains!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.18.0/lib/spaceship/tunes/build_train.rb:105:in `update_testing_status!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.18.0/lib/spaceship/tunes/build.rb:152:in `submit_for_beta_review!'

**Comment by kdawgwilk** [comment]
@self-creative I am also getting this error :( @KrauseFx Is pilot not able to submit builds to external testers if it has already gone through beta app review?
