### ISSUE TITLE
Gym fails IPA export in schema including WatchKit App

### ISSUE THREAD

**Issue by fukazayo** [fastlane/fastlane#9260]
### New Issue Checklist

- [v] Updated fastlane to the latest version
- [v] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I created a simple iOS App with WatchKit App project and try to build using gym.
But gym fails IPA export in a schema including WatcKit App.
(Gym succeeds IPA export in a schema without WatchKit App.)

### Captured Output

Command Used: `debug`
<details><summary>Output/Log</summary>

```

DEBUG [2017-05-24 15:27:58.52]: Checking if there are any plugins that should be loaded...
INFO [2017-05-24 15:27:58.52]: -------------------------------------------------
INFO [2017-05-24 15:27:58.52]: --- Step: Verifying required fastlane version ---
INFO [2017-05-24 15:27:58.52]: -------------------------------------------------
INFO [2017-05-24 15:27:58.52]: Your fastlane version 2.33.0 matches the minimum requirement of 2.33.0  ✅
INFO [2017-05-24 15:27:58.52]: ------------------------------
INFO [2017-05-24 15:27:58.52]: --- Step: default_platform ---
INFO [2017-05-24 15:27:58.52]: ------------------------------
ERROR [2017-05-24 15:27:58.52]: Name of the lane 'debug' is already taken by the action named 'debug'
INFO [2017-05-24 15:27:58.52]: Driving the lane 'ios debug' 🚀
INFO [2017-05-24 15:27:58.53]: -----------------
INFO [2017-05-24 15:27:58.53]: --- Step: gym ---
INFO [2017-05-24 15:27:58.53]: -----------------
INFO [2017-05-24 15:27:58.75]: $ xcodebuild -list -project ./WatchKitTest.xcodeproj -configuration Debug
INFO [2017-05-24 15:27:59.41]: $ xcodebuild -showBuildSettings -scheme WatchKitTest\ WatchKit\ App -project ./WatchKitTest.xcodeproj -configuration Debug

+----------------------+--------------------------------------+
|                   Summary for gym 2.33.0                    |
+----------------------+--------------------------------------+
| configuration        | Debug                                |
| export_method        | development                          |
| scheme               | WatchKitTest WatchKit App            |
| project              | ./WatchKitTest.xcodeproj             |
| destination          | generic/platform=iOS                 |
| output_name          | WatchKitTest WatchKit App            |
| build_path           | /Users/fukazayo/Library/Developer/X  |
|                      | code/Archives/2017-05-24             |
| clean                | false                                |
| output_directory     | .                                    |
| silent               | false                                |
| skip_package_ipa     | false                                |
| use_legacy_build_api | false                                |
| buildlog_path        | ~/Library/Logs/gym                   |
| xcode_path           | /Applications/Xcode.app              |
+----------------------+--------------------------------------+

+--------------------------------------+----------------------+
|                   Generated Build Command                   |
+--------------------------------------+----------------------+
| Option                               | Value                |
+--------------------------------------+----------------------+
| set -o pipefail &&                   |                      |
| xcodebuild                           |                      |
| -scheme WatchKitTest\ WatchKit\ App  |                      |
| -project ./WatchKitTest.xcodeproj    |                      |
| -configuration Debug                 |                      |
| -destination                         | generic/platform=iOS |
| -archivePath                         |                      |
| /Users/fukazayo/Library/Developer/X  |                      |
| code/Archives/2017-05-24/WatchKitTe  |                      |
| st\ WatchKit\ App\ 2017-05-24\       |                      |
| 15.28.00.xcarchive                   |                      |
| archive                              |                      |
| | tee                                |                      |
| /Users/fukazayo/Library/Logs/gym/Wa  |                      |
| tchKitTest\ WatchKit\                |                      |
| App-WatchKitTest\ WatchKit\ App.log  |                      |
| | xcpretty                           |                      |
+--------------------------------------+----------------------+
INFO [2017-05-24 15:28:00.27]: $ set -o pipefail && xcodebuild -scheme WatchKitTest\ WatchKit\ App -project ./WatchKitTest.xcodeproj -configuration Debug -destination 'generic/platform=iOS' -archivePath /Users/fukazayo/Library/Developer/Xcode/Archives/2017-05-24/WatchKitTest\ WatchKit\ App\ 2017-05-24\ 15.28.00.xcarchive archive | tee /Users/fukazayo/Library/Logs/gym/WatchKitTest\ WatchKit\ App-WatchKitTest\ WatchKit\ App.log | xcpretty
INFO [2017-05-24 15:28:01.13]: ▸ Building WatchKitTest/WatchKitTest WatchKit Extension [Debug]
INFO [2017-05-24 15:28:01.14]: ▸ Check Dependencies
INFO [2017-05-24 15:28:01.30]: ▸ Compiling NotificationController.swift
INFO [2017-05-24 15:28:01.39]: ▸ Compiling ExtensionDelegate.swift
INFO [2017-05-24 15:28:01.43]: ▸ Compiling InterfaceController.swift
INFO [2017-05-24 15:28:01.62]: ▸ Linking WatchKitTest\
INFO [2017-05-24 15:28:02.16]: ▸ Processing Info.plist
INFO [2017-05-24 15:28:02.21]: ▸ Touching WatchKitTest\ WatchKit\ Extension.appex
INFO [2017-05-24 15:28:02.22]: ▸ Signing /Users/fukazayo/Library/Developer/Xcode/DerivedData/WatchKitTest-fmeonnvedbljyvacplvpbzuxfvhe/Build/Intermediates/ArchiveIntermediates/WatchKitTest\ WatchKit\ App/IntermediateBuildFilesPath/UninstalledProducts/watchos/WatchKitTest\ WatchKit\ Extension.appex
INFO [2017-05-24 15:28:02.32]: ▸ Building WatchKitTest/WatchKitTest WatchKit App [Debug]
INFO [2017-05-24 15:28:02.32]: ▸ Check Dependencies
INFO [2017-05-24 15:28:02.34]: ▸ Compiling Interface.storyboard
INFO [2017-05-24 15:28:02.82]: ▸ Processing Info.plist
INFO [2017-05-24 15:28:02.84]: ▸ Copying /Users/fukazayo/Library/Developer/Xcode/DerivedData/WatchKitTest-fmeonnvedbljyvacplvpbzuxfvhe/Build/Intermediates/ArchiveIntermediates/WatchKitTest\ WatchKit\ App/BuildProductsPath/Debug-watchos/WatchKitTest\ WatchKit\ Extension.appex
INFO [2017-05-24 15:28:02.89]: ▸ Touching WatchKitTest\ WatchKit\ App.app
INFO [2017-05-24 15:28:04.01]: ▸ Signing /Users/fukazayo/Library/Developer/Xcode/DerivedData/WatchKitTest-fmeonnvedbljyvacplvpbzuxfvhe/Build/Intermediates/ArchiveIntermediates/WatchKitTest\ WatchKit\ App/IntermediateBuildFilesPath/UninstalledProducts/watchos/WatchKitTest\ WatchKit\ App.app
INFO [2017-05-24 15:28:04.22]: ▸ Building WatchKitTest/WatchKitTest [Debug]
INFO [2017-05-24 15:28:04.22]: ▸ Check Dependencies
INFO [2017-05-24 15:28:04.30]: ▸ Compiling ViewController.swift
INFO [2017-05-24 15:28:04.43]: ▸ Compiling AppDelegate.swift
INFO [2017-05-24 15:28:04.69]: ▸ Compiling ViewController.swift
INFO [2017-05-24 15:28:04.81]: ▸ Compiling AppDelegate.swift
INFO [2017-05-24 15:28:04.98]: ▸ Linking WatchKitTest
INFO [2017-05-24 15:28:05.17]: ▸ Linking WatchKitTest
INFO [2017-05-24 15:28:05.22]: ▸ Compiling LaunchScreen.storyboard
INFO [2017-05-24 15:28:05.48]: ▸ Compiling Main.storyboard
INFO [2017-05-24 15:28:05.76]: ▸ Processing Info.plist
INFO [2017-05-24 15:28:05.78]: ▸ Copying /Users/fukazayo/Library/Developer/Xcode/DerivedData/WatchKitTest-fmeonnvedbljyvacplvpbzuxfvhe/Build/Intermediates/ArchiveIntermediates/WatchKitTest\ WatchKit\ App/BuildProductsPath/Debug-watchos/WatchKitTest\ WatchKit\ App.app
INFO [2017-05-24 15:28:05.97]: ▸ Touching WatchKitTest.app
INFO [2017-05-24 15:28:07.97]: ▸ Signing /Users/fukazayo/Library/Developer/Xcode/DerivedData/WatchKitTest-fmeonnvedbljyvacplvpbzuxfvhe/Build/Intermediates/ArchiveIntermediates/WatchKitTest\ WatchKit\ App/InstallationBuildProductsLocation/Applications/WatchKitTest.app
INFO [2017-05-24 15:28:09.34]: ▸ Archive Succeeded
DEBUG [2017-05-24 15:28:09.51]: Stored the archive in: /Users/fukazayo/Library/Developer/Xcode/Archives/2017-05-24/WatchKitTest WatchKit App 2017-05-24 15.28.00.xcarchive
WARN [2017-05-24 15:28:10.69]: Lane Context:
INFO [2017-05-24 15:28:10.69]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios debug"}
ERROR [2017-05-24 15:28:10.69]: no implicit conversion of nil into String
INFO [2017-05-24 15:28:10.69]: Successfully generated documentation at path '/Users/fukazayo/Desktop/WatchKitTest/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | gym                 | 10          |
+------+---------------------+-------------+

ERROR [2017-05-24 15:28:10.70]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: no implicit conversion of nil into String

URL: https://api.github.com/search/issues?q=no%20implicit%20conversion%20of%20nil%20into%20String+repo:fastlane/fastlane
➡️  "no implicit conversion of nil into String" when executing snapshpt
    https://github.com/fastlane/fastlane/issues/7433 [open] 6 💬
    6 weeks ago

➡️  "no implicit conversion of nil into String" in fastlane init
    https://github.com/fastlane/fastlane/issues/8083 [closed] 5 💬
    6 weeks ago

➡️  "no implicit conversion of nil into String" when running "fastlane update_fastlane"
    https://github.com/fastlane/fastlane/issues/7405 [closed] 4 💬
    a week ago

and 53 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

/Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/actions/gym.rb:21:in `expand_path': [!] no implicit conversion of nil into String (TypeError)
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/actions/gym.rb:21:in `run'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:7:in `block (2 levels) in parsing_binding'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/gems/fastlane-2.33.0/bin/fastlane:20:in `<top (required)>'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/fukazayo/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.33.0"

default_platform :ios

platform :ios do
  lane :debug do
    gym(
      configuration: "Debug",
      export_method: "development",
      scheme: "WatchKitTest WatchKit App"
    )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.33.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.0       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| openssl                   | 2.0.2        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.7.2        |
</details>

*generated on:* **2017-05-24**
</details>

**Comment by fukazayo** [comment]
I checked the Code Signing Troubleshooting Guide, but there was no explanation about this issue.

**Comment by iDaniel89** [comment]
Hello @fukazayo,

I'm getting the same issue with fastlane/gym 2.45.0 ... Where you able to find a solution?
