### ISSUE TITLE
[Regression] Scan failing on reading junit_report temp file as of v2.34.0

### ISSUE THREAD

**Issue by chrishawkinsnz** [fastlane/fastlane#9268]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When attempting to run Scan it is failing with an error complaining of not being able to find some JUnit log file. We don't use JUnit as part of our project so this was particularly surprising.  I've attached the bottom few pages of Fastlane's output below. 

It would be my guess that the issue is related to this PR https://github.com/fastlane/fastlane/pull/7365.  But I can't pretend to understand enough of what is going on right now to know for sure. 

```
+----------------------------+-------------------------------------------------------------------------------------+
|                                                   Lane Context                                                   |
+----------------------------+-------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                                 |
| PLATFORM_NAME              | ios                                                                                 |
| LANE_NAME                  | ios runUnitTests                                                                    |
| SCAN_DERIVED_DATA_PATH     | /Users/mobile/.jenkins/workspace/CI - Trade Me iOS Pull Requests/iosapp/derivedData |
| SCAN_GENERATED_PLIST_FILES | []                                                                                  |
| SCAN_GENERATED_PLIST_FILE  |                                                                                     |
+----------------------------+-------------------------------------------------------------------------------------+
[12:16:45]: No such file or directory @ rb_sysopen - /var/folders/dp/qgbyxqt10mxbjw6gg2p72vbw0000gn/T/junit_report20170525-86740-19nw7dm

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | update_fastlane                                               | 4           |
| 4    | import_from_git                                               | 4           |
| 5    | Switch to ios configure lane                                  | 0           |
| 6    | Switch to ios setup lane                                      | 0           |
| 7    | bundle_install                                                | 0           |
| 8    | setup_jenkins                                                 | 0           |
| 9    | clean_build_artifacts                                         | 0           |
| 10   | clear_derived_data                                            | 0           |
| 11   | update_cache                                                  | 0           |
| 12   | xcode_select                                                  | 0           |
| 💥   | scan                                                          | 459         |
| 14   | xcodebuild -project ../*.xcodeproj -showBuildSettings 2>/dev/ | 3           |
| 15   | slack                                                         | 1           |
+------+---------------------------------------------------------------+-------------+

[12:16:45]: fastlane finished with errors

[12:16:45]: Error accessing file, this might be due to fastlane's directory handling
[12:16:45]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:84:in `read': No such file or directory @ rb_sysopen - /var/folders/dp/qgbyxqt10mxbjw6gg2p72vbw0000gn/T/junit_report20170525-86740-19nw7dm (Errno::ENOENT)
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:84:in `test_results'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:49:in `handle_results'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:9:in `run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/manager.rb:14:in `work'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/actions/scan.rb:22:in `run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from ../../../../../../../var/folders/dp/qgbyxqt10mxbjw6gg2p72vbw0000gn/T/fl_clone20170525-86740-wfvzbb/fastlane.git/fastlane/SharedFastfile:37:in `block (2 levels) in parsing_binding'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/bin/fastlane:20:in `<top (required)>'
	from /Users/mobile/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /Users/mobile/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'
```

### Environment

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.18.0"

default_platform :ios

import_from_git(url: 'https://tmstash/scm/bt/fastlane.git', path: 'fastlane/SharedFastfile')

platform :ios do

  before_all do
    configure
    setup
    
    if Helper.is_ci?
      update_cache(
        url: 'https://api.trademe.co.nz/v1/Categories.json',
        data_path: 'TradeMeMain/Resources/Data/categories.json',
        plist_path: 'TradeMeMain/Resources/Data/eTags.plist')

      xcode_select "/Applications/Xcode.app"
    end
  end

  private_lane :configure do |options|
    ENV["TM_TEAM"] = "central-testers"
    ENV["TM_UNIT_TEST_SCHEME"] = "TradeMeMain Tests"
    ENV["TM_UI_TEST_SCHEME"] = "TradeMeUITests"
    ENV["TM_SCHEME"] = "TradeMeMain"
  end

  # You can define as many lanes as you want

  after_all do |lane|
  end
end

# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "nz.co.trademe.trademe" # The bundle identifier of your app

# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-badge   | 0.8.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.12.5       |
| json                      | 2.0.4        |
| io-console                | 0.4.5        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.2.0        |
| faraday                   | 0.12.0.1     |
| faraday_middleware        | 0.11.0.1     |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| google-api-client         | 0.9.28       |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| fastimage                 | 2.1.0        |
| colored2                  | 3.1.2        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| fastlane-plugin-appicon   | 0.6.0        |
| curb                      | 0.9.3        |
| badge                     | 0.8.4        |
| fastlane-plugin-badge     | 0.8.2        |
</details>

*generated on:* **2017-05-25**
</details>

**Comment by keatongreve** [comment]
Looking into this.

@chrishawkinsnz After each (failed) run, have you verified that there is no file at the temp file path mentioned in the console? e.g. `/var/folders/dp/qgbyxqt10mxbjw6gg2p72vbw0000gn/T/junit_report20170525-86740-19nw7dm` from your output above (it changes each run). I'm pretty sure it's not there, but wanted to be certain.

Also, could you post the initial output of the `scan` action, which contains the `xcodebuild` commands that are run? Here's what mine looks like:
```
keaton.greve $ bundle exec fastlane unit_tests
+----------------------------------+---------+---------------------------+
|                              Used plugins                              |
+----------------------------------+---------+---------------------------+
| Plugin                           | Version | Action                    |
+----------------------------------+---------+---------------------------+
| fastlane-plugin-upload_to_onesky | 0.1.1   | upload_to_onesky          |
| fastlane-plugin-slack_status     | 0.1.0   | failed_tests_slack_status |
+----------------------------------+---------+---------------------------+

[09:01:30]: Driving the lane 'unit_tests' 🚀
[09:01:30]: ------------------
[09:01:30]: --- Step: scan ---
[09:01:30]: ------------------
[09:01:30]: $ xcodebuild -list -workspace REDACTED.xcworkspace -configuration Debug
[09:01:35]: $ xcodebuild -showBuildSettings -workspace REDACTED.xcworkspace -scheme REDACTED -configuration Debug
[09:01:43]: $ xcodebuild -list -workspace REDACTED.xcworkspace -configuration Debug
[09:01:45]: $ xcodebuild -showBuildSettings -workspace REDACTED.xcworkspace -scheme REDACTED -configuration Debug

+------------------------+-------------------------+
|             Summary for scan 2.35.0              |
+------------------------+-------------------------+
| scheme                 | REDACTED                |
| workspace              | REDACTED.xcworkspace    |
| device                 | iPad Air                |
| configuration          | Debug                   |
| derived_data_path      | gym_build               |
| output_types           | junit                   |
| code_coverage          | true                    |
| skip_build             | true                    |
| clean                  | false                   |
| output_directory       | ./fastlane/test_output  |
| buildlog_path          | ~/Library/Logs/scan     |
| include_simulator_logs | false                   |
| open_report            | false                   |
| skip_slack             | false                   |
| slack_only_on_failure  | false                   |
| use_clang_report_name  | false                   |
| fail_build             | true                    |
| xcode_path             | /Applications/Xcode.app |
+------------------------+-------------------------+

[09:01:52]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace REDACTED.xcworkspace -scheme REDACTED -configuration Debug -destination 'platform=iOS Simulator,id=BD258495-6B99-4E44-8722-636FA8624362' -derivedDataPath 'gym_build' -enableCodeCoverage YES test | tee '/Users/keaton.greve/Library/Logs/scan/REDACTED-REDACTED.log' | xcpretty  --report junit --output /Users/keaton.greve/GitHub/REDACTED/fastlane/test_output/report.junit --report junit --output /var/folders/6m/23g44hsx3k7gk7w65h5dp24mth8dwh/T/junit_report20170525-70764-ccuqar
```

That last line in particular, here's what it looks like when split across a few lines:
```
[09:01:52]: $ set -o pipefail && 
  env NSUnbufferedIO=YES 
  xcodebuild 
  -workspace REDACTED.xcworkspace 
  -scheme REDACTED 
  -configuration Debug 
  -destination 'platform=iOS Simulator,id=BD258495-6B99-4E44-8722-636FA8624362' 
  -derivedDataPath 'gym_build' 
  -enableCodeCoverage YES test
  | tee '/Users/keaton.greve/Library/Logs/scan/REDACTED-REDACTED.log'
  | xcpretty 
    --report junit --output /Users/keaton.greve/GitHub/REDACTED/fastlane/test_output/report.junit
    --report junit --output /var/folders/6m/23g44hsx3k7gk7w65h5dp24mth8dwh/T/junit_report20170525-70764-ccuqar
```

**Comment by keatongreve** [comment]
Also I noticed you are using a fastfile imported from another git repository:
`import_from_git(url: 'https://tmstash/scm/bt/fastlane.git', path: 'fastlane/SharedFastfile')`
If possible, could you print any contents you are able to share? I believe the lane `runUnitTests` must be defined there.

**Comment by keatongreve** [comment]
Last request! If possible, could you test my fix (#9276). You should be able to install it like so:
```
gem 'fastlane', github: 'keatongreve/fastlane', branch: 'scan-fix-9268'
```

**Comment by trevor-e** [comment]
Not sure if it's related, but ever since 2.34.0 `scan` won't generate any test reports for us, causing all Jenkins jobs to fail. I had to downgrade to 2.33.0 for now.

**Comment by keatongreve** [comment]
@trevor-e could you also provide the initial output of scan, as well as the parameters you use when calling it? See the example in https://github.com/fastlane/fastlane/issues/9268#issuecomment-304019067.

**Comment by trevor-e** [comment]
```
+------------------------+---------------------------------------------------------------------------------------+
|                                            Summary for scan 2.35.0                                             |
+------------------------+---------------------------------------------------------------------------------------+
| workspace              | <app>.xcworkspace                                                                     |
| scheme                 | <scheme>                                                                                |
| clean                  | true                                                                                  |
| buildlog_path          | /Users/<user>/.jenkins/workspace/<scheme> tests                                        |
| derived_data_path      | /Users/<user>/Library/Developer/Xcode/DerivedData/<app>-ghyxnfploxnlvfbizgaqwyayfwbu |
| skip_build             | false                                                                                 |
| output_directory       | ./fastlane/test_output                                                                |
| output_types           | html,junit                                                                            |
| include_simulator_logs | false                                                                                 |
| open_report            | false                                                                                 |
| skip_slack             | false                                                                                 |
| slack_only_on_failure  | false                                                                                 |
| use_clang_report_name  | false                                                                                 |
| xcode_path             | /Applications/Xcode.app                                                               |
+------------------------+---------------------------------------------------------------------------------------+

[17:31:18]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace <app>.xcworkspace -scheme <scheme> -destination 'platform=iOS Simulator,id=5E1EBA9D-7A4F-46A5-A308-ACFFFD64C5A9' -derivedDataPath '/Users/<user>/Library/Developer/Xcode/DerivedData/<app>-ghyxnfploxnlvfbizgaqwyayfwbu' clean build test | tee '/Users/<user>/.jenkins/workspace/<scheme> tests/<scheme>-<scheme>.log' | xcpretty  --report html --output /Users/<user>/.jenkins/workspace/<scheme> tests/fastlane/test_output/report.html --report junit --output /Users/<user>/.jenkins/workspace/<scheme> tests/fastlane/test_output/report.junit --report junit --output /var/folders/bn/y5hxkvm9625gwfdtdl4f527h0000gp/T/junit_report20170525-35604-3okzid
[17:31:18]: ▸ Loading...
```

When the tests finish you can see it doesn't mention creating the test outputs:

```
[17:36:17]: ▸ Test Succeeded
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 1348  |
| Number of failures | 0     |
+--------------------+-------+

Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: Test reports were found but none of them are new. Did tests run?
```

However, on 2.33.0 (which works) it does:

```
[18:42:12]: ▸ Test Succeeded
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 1348  |
| Number of failures | 0     |
+--------------------+-------+

[18:42:21]: Successfully generated report at '/Users/<user>/.jenkins/workspace/<scheme> tests/fastlane/test_output/report.html'
[18:42:25]: Successfully generated report at '/Users/<user>/.jenkins/workspace/<scheme> tests/fastlane/test_output/report.junit'
```

**Comment by keatongreve** [comment]
thank you @trevor-e, that is very helpful! it appears you have spaces in your paths, and i did not account for that. i'll work on a fix.

**Comment by chrishawkinsnz** [comment]
I see this has been closed but I just wanted to add that I can confirm @keatongreve's fix did indeed fix my issue.  Thanks!
