### ISSUE TITLE
New scan "Couldn't parse the number of tests from the output"

### ISSUE THREAD

**Issue by brentleyjones** [fastlane/fastlane#9285]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When using 2.35.0 scan can't parse a successful test run, when using raw output.

```
+------------------------+-------------------------------------------------------------------------------------------+
|                                             Summary for scan 2.35.0.                                               |
+------------------------+-------------------------------------------------------------------------------------------+
| xctestrun              | xctestrun/tests.xctestrun                                                                 |
| scheme                 | Project Test                                                                              |
| devices                | ["iPhone 7"]                                                                              |
| workspace              | ./RedBrick.xcworkspace                                                                    |
| derived_data_path      | /Users/buildsvc/Library/Developer/Xcode/DerivedData/Project-arhcibeokaxbvveramdwumyfzkwq  |
| clean                  | false                                                                                     |
| skip_build             | false                                                                                     |
| output_directory       | ./fastlane/test_output                                                                    |
| output_style           | raw                                                                                       |
| output_types           | html,junit                                                                                |
| buildlog_path          | ~/Library/Logs/scan                                                                       |
| include_simulator_logs | false                                                                                     |
| open_report            | false                                                                                     |
| skip_slack             | false                                                                                     |
| slack_only_on_failure  | false                                                                                     |
| use_clang_report_name  | false                                                                                     |
| fail_build             | true                                                                                      |
| xcode_path             | /Applications/Xcode-8.3.2.app                                                             |
+------------------------+-------------------------------------------------------------------------------------------+

...

[11:01:12]: ▸ Test Suite 'Project-iOS - Functional Tests-Runner.app' passed at 2017-05-25 11:01:12.926.
[11:01:12]: ▸ Executed 75 tests, with 0 failures (0 unexpected) in 946.354 (946.385) seconds
[11:01:12]: ▸ Test Suite 'All tests' passed at 2017-05-25 11:01:12.926.
[11:01:12]: ▸ Executed 75 tests, with 0 failures (0 unexpected) in 946.354 (946.386) seconds
[11:01:13]: ▸ ** TEST EXECUTE SUCCEEDED **
[11:01:13]: Couldn't parse the number of tests from the output
```

#7365 seems to have been what broke it. Running on 2.33.0 works.

Unrelated, it crashes right after as well:

```
[11:01:19]: fastlane failed to write the crash report to /Users/buildsvc/.fastlane/latest_crash.json.
[11:01:19]: Sending crash report...
[11:01:19]: The stacktrace is sanitized so no personal information is sent.
[11:01:19]: To see what we are sending, look here: /Users/buildsvc/.fastlane/latest_crash.json
[11:01:19]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[11:01:19]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
+----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                         Lane Context                                                                                          |
+----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                                                                                                              |
| PLATFORM_NAME              | ios                                                                                                                                                              |
| LANE_NAME                  | ios xctestrun                                                                                                                                                    |
| SCAN_DERIVED_DATA_PATH     | /Users/buildsvc/Library/Developer/Xcode/DerivedData/Project-arhcibeokaxbvveramdwumyfzkwq                                                                         |
| SCAN_GENERATED_PLIST_FILES | ["/Users/buildsvc/Library/Developer/Xcode/DerivedData/Project-arhcibeokaxbvveramdwumyfzkwq/Logs/Test/AB1C19D9-ACEB-4D76-A3D1-86B911F9A35B_TestSummaries.plist"]  |
| SCAN_GENERATED_PLIST_FILE  | /Users/buildsvc/Library/Developer/Xcode/DerivedData/Project-arhcibeokaxbvveramdwumyfzkwq/Logs/Test/AB1C19D9-ACEB-4D76-A3D1-86B911F9A35B_TestSummaries.plist      |
+----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[11:01:19]: undefined method `>' for nil:NilClass

/Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:52:in `handle_results': [!] undefined method `>' for nil:NilClass (NoMethodError)
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:9:in `run'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/manager.rb:14:in `work'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/actions/scan.rb:22:in `run'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:42:in `block (2 levels) in parsing_binding'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/buildsvc/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/bin/fastlane:20:in `<top (required)>'
	from /Users/buildsvc/.rbenv/versions/2.3.3/bin/fastlane:22:in `load'
	from /Users/buildsvc/.rbenv/versions/2.3.3/bin/fastlane:22:in `<main>'
```

**Comment by keatongreve** [comment]
@brentleyjones I just tested my PR with `output_style: raw`, things are looking good. we're hoping to push this fix soon.

**Comment by brentleyjones** [comment]
@keatongreve 2.35.1 fixes our issue as well, thanks!

**Comment by KrauseFx** [comment]
Great to hear, thanks 👍
