### ISSUE TITLE
Unauthorized access error

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#930]
```
/Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.2/lib/spaceship/client.rb:263:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.2/lib/spaceship/tunes/tunes_client.rb:464:in `build_trains'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.2/lib/spaceship/tunes/build_train.rb:48:in `all'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/spaceship-0.14.2/lib/spaceship/tunes/application.rb:195:in `build_trains'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/pilot-1.0.1/lib/pilot/build_manager.rb:83:in `wait_for_processing_build'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/pilot-1.0.1/lib/pilot/build_manager.rb:21:in `upload'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/actions/pilot.rb:15:in `run'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:54:in `block (2 levels) in parsing_binding'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/runner.rb:46:in `execute'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/bin/fastlane:152:in `run'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/gems/fastlane-1.41.1/bin/fastlane:158:in `<top (required)>'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/pronebird/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rompic** [comment]
we experienced this as well today. There were some problems with itunes-connect today as well (e.g. it was not possible to add new versions for a few hours) so maybe apple had some general problems.

**Comment by pronebird** [comment]
@rompic the build has been published.

**Comment by ohwutup** [comment]
Hey everyone. This issue has been addressed in a couple of more recent releases of Fastlane. Please try updating your versions of the gems and let us know if there is still an issue. If so, we will definitely reopen the issue to discuss. Thanks!! :dog:
