### ISSUE TITLE
fastlane failing to remove report.xml after build task completes

### ISSUE THREAD

**Issue by devdavidkarlsson** [fastlane/fastlane#9309]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Suddenly failing to run fastlane from build server, haven't been able to isolate the cause.
I am only running a very simple task, verifying a files content. This has worked before....

**The issue appears after the normal task has completed, some operation is trying to change/remove report.xml but fails.**

Tried installing new version of ruby.
Tried upgrading to latest fastlane.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
+ export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Users/server/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Users/server/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ chmod -R 755 mex-ios-repo
+ chown -R server:staff ..
+ chmod +x ./devops-repo/mex-ios-pipeline/scripts/review-changelog.sh
+ sudo -H -u server sh -c devops-repo/mex-ios-pipeline/scripts/review-changelog.sh
Please make sure that the CHANGELOG below is valid:
No entry for terminal type "unknown";
using dumb terminal settings.
[14:12:33]: ------------------------------
[14:12:33]: --- Step: default_platform ---
[14:12:33]: ------------------------------
[14:12:33]: Driving the lane 'ios review_changes' 🚀
[14:12:33]: ----------------------------------
[14:12:33]: --- Step: ensure_xcode_version ---
[14:12:33]: ----------------------------------
[14:12:33]: $ xcversion selected
[14:12:34]: ▸ Xcode 8.3.2
[14:12:34]: ▸ Build version 8E2002
[14:12:34]: Selected Xcode version is correct: 8.3.2
[14:12:34]: --------------------------------
[14:12:34]: --- Step: get_version_number ---
[14:12:34]: --------------------------------
[14:12:34]: $ cd /opt/concourse/worker/volumes/live/288086e1-16fd-4838-5bf8-a3158d83d4ba/volume && agvtool what-marketing-version -terse

.... LINES REMOVED FOR PRIVACY ....

[14:12:36]: ▸ "Mex.xcodeproj/../UITests/Info.plist"=2.6.0
[14:12:36]: ------------------------------
[14:12:36]: --- Step: get_build_number ---
[14:12:36]: ------------------------------
[14:12:36]: $ cd /opt/concourse/worker/volumes/live/288086e1-16fd-4838-5bf8-a3158d83d4ba/volume && agvtool what-version -terse
[14:12:37]: ▸ 72
[14:12:37]: --------------------------------------------------------------------
[14:12:37]: Step: Reading changelog from: /opt/concourse/worker/volumes/live/288086e1-16fd-4838-5bf8-a3158d83d4ba/volume/CHANGELOG.json
[14:12:37]: --------------------------------------------------------------------
[14:12:37]: --------------------------------------
[14:12:37]: --- Step: get changelog for: 2.6.0 ---
[14:12:37]: --------------------------------------
[14:12:37]: Please verify content of the changelog (and it's triggers) below: 
[14:12:37]: ✅  Trigger: none
[14:12:37]: ✅  Changelog: Environment Test. Security Test Findings Implementations.
[14:12:37]: ⚠️ If YOU find the changelog (☝️ ) correct you may proceed with an Alpha/Beta release  ⚠️

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/server/.rbenv/versions/2.4.1/bin/fastlane)
Errno::EACCES: [!] Permission denied @ rb_sysopen - ./fastlane/report.xml
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/junit_generator.rb:17:in `write'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/junit_generator.rb:17:in `generate'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/lane_manager.rb:82:in `finish_fastlane'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/lane_manager.rb:68:in `cruise_lane'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/server/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.35.1/bin/fastlane:20:in `<top (required)>'
  /Users/server/.rbenv/versions/2.4.1/bin/fastlane:22:in `load'
  /Users/server/.rbenv/versions/2.4.1/bin/fastlane:22:in `<top (required)>'

```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

skip_docs
default_platform :ios

$apps = {.... LINES REMOVED FOR PRIVACY ....}

#Get bundle_id for app scheme and error if not found:
def bundle_id(scheme)
   bundle_id = $apps[scheme];
   if bundle_id != nil
     return bundle_id
   else
     UI.crash!("No matching bundle found for: " + scheme + " in the fastfile")
   end
end



platform :ios do
  before_all do |lane, options|
    ensure_xcode_version(version: "8.3.2")
#if options[:keychainpass] != nil
#			unlock_keychain(
#				path: "/Users/server/Library/Keychains/login.keychain",
#				password: options[:keychainpass]
#			)
#		end
  end

  ###########
  # Testing #
  ###########

  desc "Runs all the tests"
  lane :test do |options|
		sh 'killall "Simulator" || true'
		version = get_version_number(xcodeproj: "Mex.xcodeproj")
		build_number = get_build_number(xcodeproj: "Mex.xcodeproj")


    if options[:scheme] != nil

			# Individual app specified by parameters
			scan(scheme: options[:scheme],
				devices: ["iPhone SE", "iPhone 7", "iPhone 7 Plus"],
				output_directory: "fastlane/test_output/" + version + "_" + build_number + "/" + bundle_id(options[:scheme])
			)


    else



			#Run UI tests on all apps
			$apps.each do |scheme, app_identifier|

				scan(scheme: scheme,
					devices: ["iPhone SE", "iPhone 7", "iPhone 7 Plus"],
					output_directory: "fastlane/test_output/" + version + "_" + build_number + "/" + app_identifier
				)

			end
    end
  end

  ###############
  # Screenshots #
  ###############

  desc "Take screenshots"
  lane :screenshots do

		version = get_version_number(xcodeproj: "Mex.xcodeproj")
		build_number = get_build_number(xcodeproj: "Mex.xcodeproj")

		#Debug test one
    #snapshot(scheme: "UITests LO Norway Screenshots", devices: ["iPhone 5s"], languages:["en-US","da-DK","nb-NO","sv-SE"])

    #Run UI tests on all apps
    $apps.each do |scheme, app_identifier|

      snapshot(   scheme: "UITests " + scheme + " Screenshots",
                 devices: ["iPhone 5s", "iPhone 7", "iPhone 7 Plus"],
               languages: ["da-DK",
                           "en-US",
                           "nb-NO",
                           "sv-SE"],
        output_directory: "fastlane/screenshots/" + version + "_" + build_number + "/" + app_identifier,
       skip_open_summary: true,
      localize_simulator: true

      )

    end

  end


  ################
  # Certificates #
  ################

  desc "Certificates"
  lane :certificates do

    match(type: "development", readonly: true, verbose: true, app_identifier: $apps.values.map{|s| s + ".debug"})
    match(type: "adhoc",       readonly: true, verbose: true, app_identifier: $apps.values.map{|s| s + ".alpha"})
    match(type: "appstore",    readonly: true, verbose: true, app_identifier: $apps.values)

  end


  ####################
  # Version handling #
  ####################

  desc "Increment the app version patch"
  lane :bump_patch do
    increment_version_number(
      bump_type: "patch"
    )

    commit_version_bump(
      message: "Bumped app version to patch version " + get_version_number(xcodeproj: "Mex.xcodeproj"),
      xcodeproj: "Mex.xcodeproj",
    )

  end

  desc "Increment the app version minor"
  lane :bump_minor do
    increment_version_number(
      bump_type: "minor"
    )

    commit_version_bump(
      message: "Bumped app version to minor version " + get_version_number(xcodeproj: "Mex.xcodeproj"),
      xcodeproj: "Mex.xcodeproj",
    )

  end

  desc "Increment the app version major"
  lane :bump_major do
    increment_version_number(
      bump_type: "major"
    )

    commit_version_bump(
      message: "Bumped app version to major version " + get_version_number(xcodeproj: "Mex.xcodeproj"),
      xcodeproj: "Mex.xcodeproj",
    )

  end

  desc "Increment the build number"
  lane :bump_build_number do

    # Bump the build number
    increment_build_number

    commit_version_bump(
      message: "Bumped build number",
      xcodeproj: "Mex.xcodeproj",
    )

  end

  ####################
  # Get version      #
  ####################

  desc "Output the version of the app to a file for use by the CI"
  lane :version do |options|
    version = get_version_number(xcodeproj: "Mex.xcodeproj")
    sh "echo " + version + " > APP_VERSION"
  end


  ####################
  # Review changelog #
  ####################

def arrayify(var)
  if var.kind_of?(String)
    var=[var]
  end
  return var
end

def review_schemes(schemes)
  schemes = arrayify(schemes)
  #Check that scheme is valid:
  if schemes.kind_of?(Array)
    schemes.each do |scheme|
      bundle_id(scheme);
    end
  end
  return schemes
end

  desc "Make sure the CHANGELOG.json has the appropriate data"
  lane :review_changes do |options|

    # ensure_git_status_clean

    version = get_version_number(xcodeproj: "Mex.xcodeproj")
    build_number = get_build_number(xcodeproj: "Mex.xcodeproj")

    changelogPath = File.expand_path("../CHANGELOG.json")
    UI.header("Step: Reading changelog from: " + changelogPath)
    changelog = JSON.parse(open(changelogPath).read)

    #Verify the changelog contents after parsing the json-file:
    version_found = false
    changelog.each{ |change|
      if change["version"] == version then
        version_found = true;
        trigger = change["trigger"]
        changes = change["changes"]
        schemes = review_schemes(change["schemes"])||Array.new

        #Validate what can be validated automatically:
        if (trigger && !(trigger.include?("alpha") || trigger.include?("beta")) ) then
          UI.crash!("Unrecognized trigger in CHANGELOG.json, alpha or beta allowed. Found:" + trigger)
        end
        if not (changes) then
          UI.crash!("Expected to find changes property in CHANGELOG.json")
        end





        #Present the user with the parsed values:
        UI.header("Step: get changelog for: "+ version)
        UI.important("Please verify content of the changelog (and it's triggers) below: ")
        UI.important("✅  Trigger: " + (trigger ? trigger.join(", ") : "none"))
        UI.important("✅  Changelog: " + changes)
        schemes.each do |scheme|
          UI.important("✅  Scheme: " + scheme)
        end
        UI.success("⚠️ If YOU find the changelog (☝️ ) correct you may proceed with an Alpha/Beta release  ⚠️");
      end
    }
    if version_found == false then
      UI.header("None of the versions found in changelog did not match the expected. Found:");
      changelog.each do |key, value|
        UI.error(key)
        UI.error(value)

      UI.crash!("app plist versions does not match CHANGELOG.json version. Expected to find: "+ version)
    end
  end

  end



  ################
  # Alpha builds #
  ################

  desc "Submit a new alpha build of all apps to Crashlytics"
  lane :alpha do |options|

    bundle_install
    cocoapods

    ensure_git_status_clean

    version = get_version_number(xcodeproj: "Mex.xcodeproj")


    # Ask the user of fastlane to enter a changelog if not CI
    if options[:ci] != nil
      changelogPath = File.expand_path("../CHANGELOG.json")
      UI.header("Step: Reading changelog from: " + changelogPath)
      changelogHash = JSON.parse(open(changelogPath).read)
      change = changelogHash.select{|hash| hash["version"] == version }.first
      changelog = change["changes"];
      schemes = review_schemes(change["schemes"])

    else
      changelog = prompt(text: "Enter the change log: ",
                         multi_line_end_keyword: "END")
    end

    build_number = get_build_number(xcodeproj: "Mex.xcodeproj")

    badge(shield: version + "-" + build_number + "-orange", dark: true)


    #Build and ship to Crashlytics

    #Ship the current scheme from argument:
    if options[:scheme] != nil

      UI.important('🔐 Proceeding with: 📱 : '+options[:scheme] +",  🆔 : "+  bundle_id(options[:scheme]));

      match(type: "adhoc",
            app_identifier: bundle_id(options[:scheme])+ ".alpha",
            readonly: true)
      UI.important('🔓 Ready for building ⚒.');
      # Individual app specified by parameters
      alpha_build(scheme: options[:scheme], app_identifier: bundle_id(options[:scheme]) + ".alpha", changelog: changelog)


    #Ship all apps from the CI CHANGELOG.json schemes array:
    elsif schemes.kind_of?(Array)
      #filter $apps
      apps_for_release = $apps.select { |key, _| schemes.include? key
      }
      apps_for_release.map{|scheme, app_identifier| UI.important('🔐 Proceeding with: 📱 : '+scheme +",  🆔 : "+  app_identifier);
      }

      match(type: "adhoc",
            app_identifier: apps_for_release.values.map{|s| s + ".alpha"},
            readonly: true)
            UI.important('🔓 Ready for building ⚒.');

      #All selected apps
      apps_for_release.each do |scheme, app_identifier|

        alpha_build(scheme: scheme, app_identifier: app_identifier + ".alpha", changelog: changelog)

      end

    #Ship all apps since nohing was specified:
    else
      match(type: "adhoc",
            app_identifier: $apps.values.map{|s| s + ".alpha"},
            readonly: true)

      #All apps
      $apps.each do |scheme, app_identifier|

        alpha_build(scheme: scheme, app_identifier: app_identifier + ".alpha", changelog: changelog)

      end
    end



    # Removing the icons being created by badge
    reset_git_repo(skip_clean: true)

    # Bump the build number
    increment_build_number

    commit_version_bump(
      message: "Sent Alpha " + version + " (" + build_number + ") to Crashlytics",
      xcodeproj: "Mex.xcodeproj",
    )


  end


  desc "Submit a new alpha build to Crashlytics"
  private_lane :alpha_build do |options|


    gym(scheme: options[:scheme],
        configuration: "Alpha")


    # Distribute via Crashlytics
    crashlytics(crashlytics_path: "./Pods/Crashlytics",
                notes: options[:changelog],
                groups: "alpha-testing")


    # Removing build files
    clean_build_artifacts

  end


  ###############
  # Beta builds #
  ###############



  desc "Submit a new beta build of all apps"
  lane :beta do |options|
    bundle_install
    cocoapods

    ensure_git_status_clean

    version = get_version_number(xcodeproj: "Mex.xcodeproj")


    # Ask the user of fastlane to enter a changelog
    if options[:ci] != nil
      changelogPath = File.expand_path("../CHANGELOG.json")
      UI.header("Step: Reading changelog from: " + changelogPath)
      changelogHash = JSON.parse(open(changelogPath).read)
      change = changelogHash.select{|hash| hash["version"] == version }.first
      changelog = change["changes"];
    else
      changelog = prompt(text: "Enter the change log: ",
                         multi_line_end_keyword: "END")
    end


    #Build and ship to TestFlight

    if options[:scheme] != nil

      match(type: "appstore",
            app_identifier: bundle_id(options[:scheme]),
            readonly: true)

      # Individual app specified by parameters
      beta_build(scheme: options[:scheme], app_identifier: bundle_id(options[:scheme]), changelog: changelog)


    else

      match(type: "appstore",
            app_identifier: $apps.values,
            readonly: true)

      #All apps
       $apps.each do |scheme, app_identifier|

         beta_build(scheme: scheme, app_identifier: app_identifier, changelog: changelog)

       end

    end



    build_number = get_build_number(xcodeproj: "Mex.xcodeproj")

    # Bump the build number
    increment_build_number

    commit_version_bump(
      message: "Sent Beta " + version + " (" + build_number + ") to iTunes Connect",
      xcodeproj: "Mex.xcodeproj",
    )


  end


  desc "Submit a new build to TestFlight"
  private_lane :beta_build do |options|


    gym(scheme: options[:scheme],
        configuration: "Distribution",
        use_legacy_build_api: true)



    # Distribute via TestFlight
    pilot(changelog: options[:changelog],
          skip_waiting_for_build_processing: true,
          skip_submission: true)

    # Removing build files
    clean_build_artifacts

  end


end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "digital@entercard.com" # Your Apple email address

team_id "M7BTYTWU2E"  # Developer Portal Team ID```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.15.0       |
| io-console                | 0.4.6        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 0.2.6        |
| CFPropertyList            | 2.3.5        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| dotenv                    | 2.2.1        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| xcode-install             | 2.1.1        |
| curb                      | 0.9.3        |
| badge                     | 0.8.4        |
</details>

**Comment by hjanuschka** [comment]
@devdavidkarlsson according to the stacktrace you are having permission errors.
check that the `fastlane/report.xml` is owned by the same user that tries to remove it.

**Comment by devdavidkarlsson** [comment]
The file is created by fastlane I think, it is not checked into the repo. If the fastlane task can create it I would assume that it can remove it if it wants to...

**Comment by devdavidkarlsson** [comment]
This is probably an error from my build server rather than from fastlane itself.

https://github.com/concourse/concourse/issues/1231
