### ISSUE TITLE
Fastlane init: Unauthorized Access

### ISSUE THREAD

**Issue by emcniece** [fastlane/fastlane#9321]
Branched from https://github.com/fastlane/fastlane/issues/9241

Hitting this issue running `fastlane init` for the first time. I'm in Canada.

Output of `fastlane init`:

```
+----------------+------------------------------+
|          Summary for produce 2.35.1           |
+----------------+------------------------------+
| app_name       | ***                          |
| app_identifier | ***                          |
| username       | ***                          |
| sku            | 1496186454                   |
| platform       | ios                          |
| language       | English                      |
| skip_itc       | false                        |
| skip_devcenter | false                        |
| team_id        | ***                          |
+----------------+------------------------------+

[16:20:55]: [DevCenter] App '***' already exists, nothing to do on the Dev Center
[16:21:14]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
[16:21:14]: Starting login with user '***'
[16:21:33]: Error occurred with the setup program! Reverting changes now!
[16:21:33]: Deleting the 'fastlane' folder
[16:21:34]: fastlane failed to write the crash report to /Users/***/.fastlane/latest_crash.json.
[16:21:34]: Sending crash report...
[16:21:34]: The stacktrace is sanitized so no personal information is sent.
[16:21:34]: To see what we are sending, look here: /Users/***/.fastlane/latest_crash.json
[16:21:34]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[16:21:34]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile

Looking for related GitHub issues on fastlane/fastlane...

➡️  fastlane init error
    https://github.com/fastlane/fastlane/issues/9241 [open] 20 💬
    4 days ago

➡️  2 Factor on Travis CI
    https://github.com/fastlane/fastlane/issues/9244 [closed] 6 💬
    a week ago

➡️  Produce crashes while app creation
    https://github.com/fastlane/fastlane/issues/6960 [closed] 2 💬
    12 Feb 2017

and 4 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Unauthorized%20Access&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
        Unauthorized Access
```

Output of `fastlane env`:

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.3/bin/fastlane       |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
</details>


*generated on:* **2017-05-30**
</details>
```

Dump of `~/.fastlane/latest_crash.json`: (wish it showed the API endpoint in here)

```
{"eventTime":"2017-05-30T23:37:37+00:00","serviceContext":{"service":"fastlane","version":"2.35.1"},"message":"[EXCEPTION]: Spaceship::Client::UnauthorizedAccessError: Unauthorized Access\n[fastlane_path]/spaceship/lib/spaceship/client.rb:677:in `block in send_request'\n[fastlane_path]/spaceship/lib/spaceship/client.rb:516:in `with_retry'\n[fastlane_path]/spaceship/lib/spaceship/client.rb:671:in `send_request'\n[fastlane_path]/spaceship/lib/spaceship/client.rb:560:in `request'\n[fastlane_path]/spaceship/lib/spaceship/client.rb:186:in `user_details_data'\n[fastlane_path]/spaceship/lib/spaceship/client.rb:132:in `teams'\n[fastlane_path]/spaceship/lib/spaceship/tunes/tunes_client.rb:62:in `select_team'\n[fastlane_path]/spaceship/lib/spaceship/tunes/spaceship.rb:30:in `select_team'\n[fastlane_path]/fastlane/lib/fastlane/setup/setup_ios.rb:223:in `detect_if_app_is_available'\n[fastlane_path]/fastlane/lib/fastlane/setup/setup_ios.rb:127:in `ask_to_enable_other_tools'\n[fastlane_path]/fastlane/lib/fastlane/setup/setup_ios.rb:117:in `manual_setup'\n[fastlane_path]/fastlane/lib/fastlane/setup/setup_ios.rb:73:in `try_manual_setup'\n[fastlane_path]/fastlane/lib/fastlane/setup/setup_ios.rb:59:in `rescue in run'\n[fastlane_path]/fastlane/lib/fastlane/setup/setup_ios.rb:30:in `run'\n[fastlane_path]/fastlane/lib/fastlane/setup/setup.rb:29:in `run'\n[fastlane_path]/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'\n[gem_home]@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'\n[gem_home]@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'\n[gem_home]@global/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'\n[fastlane_path]/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'\n[gem_home]@global/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'\n[fastlane_path]/fastlane/lib/fastlane/commands_generator.rb:303:in `run'\n[fastlane_path]/fastlane/lib/fastlane/commands_generator.rb:42:in `start'\n[fastlane_path]/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'\n[fastlane_path]/bin/fastlane:20:in `<top (required)>'\n~/.rvm/rubies/ruby-2.3.3/bin/fastlane:22:in `load'\n~/.rvm/rubies/ruby-2.3.3/bin/fastlane:22:in `<main>'\n[gem_home]/bin/ruby_executable_hooks:15:in `eval'\n[gem_home]/bin/ruby_executable_hooks:15:in `<main>'"}%
```

Next step: testing iTunes Connect login and changing teams.

@taquitos when I visit https://itunesconnect.apple.com I am forwarded to the [Getting Started](https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/gettingstarted) page, and the 4 big icons link away to informational/sales-type pages.

I am able to access iTunes Connect through https://developer.apple.com/account/#/itunes-connect/*** and doing so shows a login form very briefly before switching to the 4-icon display.

I am part of a team and I was not the top-level "team agent". Could this be a permission/access control issue?

**Comment by taquitos** [comment]
Ohh, interesting, that would suggest that the account you're using doesn't actually belong to a team yet.

Maybe try opening up https://itunesconnect.apple.com in an incognito tab. You might have a cookie set where you're using a different account.

If you're sure you're logging in with the correct account, it would indicate a permission/access control issue.

**Comment by emcniece** [comment]
```
...
[19:24:01]: Starting login with user '***'
[19:24:26]: Optional: The scheme name of your app (If you don't need one, just hit Enter):
[19:24:38]: 'snapshot' not enabled.
[19:24:38]: 'cocoapods' not enabled.
[19:24:38]: 'carthage' not enabled.
[19:24:38]: Created new file './fastlane/Fastfile'. Edit it to manage your own deployment lanes.
[19:24:38]: fastlane will collect the number of errors for each action to detect integration issues
[19:24:38]: No sensitive/private information will be uploaded
[19:24:38]: Learn more at https://github.com/fastlane/fastlane#metrics
```

It was a permissions issue! Granting team member access to developer.apple.com does not seem to carry over to itunesconnect.apple.com. After the team agent added my user to iTunes Connect, `fastlane init` worked as expected.

**Comment by taquitos** [comment]
Yey! Thank you for following up, this is really great information for us to remember next time somebody else has a problem 👍
