### ISSUE TITLE
Fastfile:3:in `+': [!] no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by javascriptlove** [fastlane/fastlane#9335]
After updating to the recent fastlane, I seem to get error with a very basic fastfile like this:

```
lane :update_project_codesigning do |options|
   update_project_provisioning(
      xcodeproj: Dir.getwd + "/" + Dir["*.xcodeproj"].first,
      profile: Dir.getwd + "/" + Dir["AppStore_*.mobileprovision"].first,
      target_filter: ".*",
      build_configuration: "Release",
   )
   update_project_provisioning(
      xcodeproj: Dir.getwd + "/" + Dir["*.xcodeproj"].first,
      profile: Dir.getwd + "/" + Dir["Development_*.mobileprovision"].first,
      target_filter: ".*",
      build_configuration: "Debug",
   )
   update_project_team(
      path: Dir.getwd + "/" + Dir["*.xcodeproj"].first,
      teamid: ENV['MOBILE_TEAM_ID']
   )
end
```

Any idea where to dig for issues? I assume it expects the platform name somewhere, but I couldn't find any information/example in docs about where and how to provide it

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Stack trace:

```
Fastfile:3:in `+': [!] no implicit conversion of nil into String (TypeError)
	from Fastfile:3:in `block in parsing_binding'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/bamboo/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/bin/fastlane:20:in `<top (required)>'
	from /Users/bamboo/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/bamboo/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

Command Used: `update_project_codesigning`
<details><summary>Output/Log</summary>

```

DEBUG [2017-06-01 12:06:45.58]: Checking if there are any plugins that should be loaded...
INFO [2017-06-01 12:06:45.60]: Driving the lane 'update_project_codesigning' 🚀
WARN [2017-06-01 12:06:45.60]: Lane Context:
INFO [2017-06-01 12:06:45.60]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"update_project_codesigning"}
ERROR [2017-06-01 12:06:45.60]: no implicit conversion of nil into String
INFO [2017-06-01 12:06:45.61]: Successfully generated documentation at path '/Users/bamboo/bamboo-agent-home/xml-data/build-dir/LIN-EXO3-BIBA/.built_app/ios/project/fastlane/README.md'
ERROR [2017-06-01 12:06:45.61]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: no implicit conversion of nil into String

URL: https://api.github.com/search/issues?q=no%20implicit%20conversion%20of%20nil%20into%20String+repo:fastlane/fastlane
➡️  "no implicit conversion of nil into String" when executing snapshpt
    https://github.com/fastlane/fastlane/issues/7433 [open] 6 💬
    07 Apr 2017

➡️  "no implicit conversion of nil into String" in fastlane init
    https://github.com/fastlane/fastlane/issues/8083 [closed] 5 💬
    13 Apr 2017

➡️  "no implicit conversion of nil into String" when running "fastlane update_fastlane"
    https://github.com/fastlane/fastlane/issues/7405 [closed] 4 💬
    2 weeks ago

and 55 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :update_project_codesigning do |options|
   update_project_provisioning(
      xcodeproj: Dir.getwd + "/" + Dir["*.xcodeproj"].first,
      profile: Dir.getwd + "/" + Dir["AppStore_*.mobileprovision"].first,
      target_filter: ".*",
      build_configuration: "Release",
   )
   update_project_provisioning(
      xcodeproj: Dir.getwd + "/" + Dir["*.xcodeproj"].first,
      profile: Dir.getwd + "/" + Dir["Development_*.mobileprovision"].first,
      target_filter: ".*",
      build_configuration: "Debug",
   )
   update_project_team(
      path: Dir.getwd + "/" + Dir["*.xcodeproj"].first,
      teamid: ENV['MOBILE_TEAM_ID']
   )
end```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.36.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |

</details>


*generated on:* **2017-06-01**

**Comment by javascriptlove** [comment]
Ok finally found, that was an error in Dir["*.xcodeproj"].first - it returns nil. Ignore this
