### ISSUE TITLE
[Version 2.36.0] WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK

### ISSUE THREAD

**Issue by Katkov** [fastlane/fastlane#9355]
Command: **fastlane beta**
Output:
```
[22:43:08]: -------------------------
[22:43:08]: --- Step: crashlytics ---
[22:43:08]: -------------------------
[22:43:08]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[22:43:09]:  WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/michaelkatkov/AndroidStudioProjects/occ-app-android/app/build/outputs/apk/app-release.apk
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/michaelkatkov/AndroidStudioProjects/occ-app-android/app/build/outputs/apk/app-release.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more

+-----------------------------+--------------------------------------+
|                            Lane Context                            |
+-----------------------------+--------------------------------------+
| DEFAULT_PLATFORM            | android                              |
| PLATFORM_NAME               |                                      |
| LANE_NAME                   | beta                                 |
| GRADLE_ALL_APK_OUTPUT_PATHS | ["/Users/michaelkatkov/AndroidStudi  |
|                             | oProjects/occ-app-android/app/build  |
|                             | /outputs/apk/app-release.apk"]       |
| GRADLE_APK_OUTPUT_PATH      | /Users/michaelkatkov/AndroidStudioP  |
|                             | rojects/occ-app-android/app/build/o  |
|                             | utputs/apk/app-release.apk           |
+-----------------------------+--------------------------------------+
[22:43:09]: Shell command exited with exit status 1 instead of 0.

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | gradle              | 8           |
| 💥   | crashlytics         | 0           |
+------+---------------------+-------------+

[22:43:09]: fastlane finished with errors
```
### Environment

> 
> <details><summary>✅ fastlane environment ✅</summary>
> 
> ### Stack
> 
> | Key                         | Value                                       |
> | --------------------------- | ------------------------------------------- |
> | OS                          | 10.12.4                                     |
> | Ruby                        | 2.2.4                                       |
> | Bundler?                    | false                                       |
> | Git                         | git version 2.11.0 (Apple Git-81)           |
> | Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
> | Host                        | Mac OS X 10.12.4 (16E195)                   |
> | Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
> | OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
> | Is contained                | true                                        |
> | Is homebrew                 | false                                       |
> | Is installed via Fabric.app | false                                       |
> | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
> | Xcode Version               | 8.3.2                                       |
> 
> 
> ### System Locale
> 
> | Variable | Value       |   |
> | -------- | ----------- | - |
> | LANG     | en_US.UTF-8 | ✅ |
> | LC_ALL   | en_US.UTF-8 | ✅ |
> | LANGUAGE | en_US.UTF-8 | ✅ |
> 
> 
> ### fastlane files:
> 
> <details><summary>`./fastlane/Fastfile`</summary>
> 
> ```ruby
> # More documentation about how to customize your build
> # can be found here:
> # https://docs.fastlane.tools
> fastlane_version "1.109.0"
> 
> # This value helps us track success metrics for Fastfiles
> # we automatically generate. Feel free to remove this line
> # once you get things running smoothly!
> generated_fastfile_id "15ade1db-63be-4be2-984a-8bd53f770ae0"
> 
> default_platform :android
> 
> # Fastfile actions accept additional configuration, but
> # don't worry, fastlane will prompt you for required
> # info which you can add here later
> lane :beta do
>   # build the release variant
>   gradle(task: "assembleRelease")
> 
>   # upload to Beta by Crashlytics
>   crashlytics(
>     api_token: "c50ba69a7e11f2756e519cc88c6f0ee98177147f",
>     build_secret: "2556efffc865f3d465c4c053216975b88477e351bed769f344cd0d750ac43f5e"
>   )
> end
> ```
> </details>
> 
> <details><summary>`./fastlane/Appfile`</summary>
> 
> ```ruby
> # The Appfile can be used to specify information that's used across all fastlane
> # tools, like your username or the app's bundle identifier.
> #
> # For more details, check out the documentation at:
> # https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
> 
> # app_identifier "com.your.app" # the bundle identifier of your app
> # apple_id "apple@fastlane.tools" # Your Apple ID
> ```
> </details>
> 
> ### fastlane gems
> 
> | Gem      | Version | Update-Status |
> | -------- | ------- | ------------- |
> | fastlane | 2.36.0  | ✅ Up-To-Date  |
> 
> 
> ### Loaded fastlane plugins:
> 
> **No plugins Loaded**
> 
> 
> <details><summary><b>Loaded gems</b></summary>
> 
> | Gem                       | Version      |
> | ------------------------- | ------------ |
> | CFPropertyList            | 2.3.5        |
> | addressable               | 2.5.1        |
> | babosa                    | 1.0.2        |
> | bigdecimal                | 1.2.6        |
> | bundler                   | 1.14.6       |
> | claide                    | 1.0.1        |
> | colored                   | 1.2          |
> | colored2                  | 3.1.2        |
> | commander-fastlane        | 4.4.4        |
> | domain_name               | 0.5.20170404 |
> | dotenv                    | 2.2.0        |
> | excon                     | 0.55.0       |
> | faraday                   | 0.12.1       |
> | faraday-cookie_jar        | 0.0.6        |
> | faraday_middleware        | 0.11.0.1     |
> | fastimage                 | 2.1.0        |
> | gh_inspector              | 1.0.3        |
> | google-api-client         | 0.9.28       |
> | googleauth                | 0.5.1        |
> | highline                  | 1.7.8        |
> | http-cookie               | 1.0.3        |
> | httpclient                | 2.8.3        |
> | hurley                    | 0.2          |
> | io-console                | 0.4.3        |
> | json                      | 1.8.1        |
> | jwt                       | 1.5.6        |
> | libxml-ruby               | 3.0.0        |
> | little-plugger            | 1.1.4        |
> | logging                   | 2.2.2        |
> | memoist                   | 0.15.0       |
> | mime-types                | 3.1          |
> | mime-types-data           | 3.2016.0521  |
> | mini_magick               | 4.5.1        |
> | minitest                  | 5.4.3        |
> | multi_json                | 1.12.1       |
> | multi_xml                 | 0.6.0        |
> | multipart-post            | 2.0.0        |
> | nanaimo                   | 0.2.3        |
> | nokogiri                  | 1.5.6        |
> | os                        | 0.9.6        |
> | plist                     | 3.2.0        |
> | power_assert              | 0.2.2        |
> | psych                     | 2.0.8        |
> | public_suffix             | 2.0.5        |
> | rake                      | 10.4.2       |
> | rdoc                      | 4.2.0        |
> | representable             | 2.3.0        |
> | retriable                 | 2.1.0        |
> | rouge                     | 1.11.1       |
> | rubygems-update           | 2.5.2        |
> | rubyzip                   | 1.2.1        |
> | security                  | 0.1.3        |
> | signet                    | 0.7.3        |
> | slack-notifier            | 1.5.1        |
> | sqlite3                   | 1.3.13       |
> | terminal-notifier         | 1.7.1        |
> | terminal-table            | 1.7.3        |
> | test-unit                 | 3.0.8        |
> | tty-screen                | 0.5.0        |
> | uber                      | 0.0.15       |
> | unf                       | 0.1.4        |
> | unf_ext                   | 0.0.7.4      |
> | unicode-display_width     | 1.1.3        |
> | word_wrap                 | 1.0.0        |
> | xcodeproj                 | 1.4.4        |
> | xcpretty                  | 0.2.6        |
> | xcpretty-travis-formatter | 0.0.4        |
> </details>
> 
> 
> *generated on:* **2017-06-03**
> </details>
>

**Comment by Katkov** [comment]
I found a problem. I just forgot to add Crashlytics plugin to my project
