### ISSUE TITLE
Issue when use create_keychain

### ISSUE THREAD

**Issue by lowki93** [fastlane/fastlane#9366]
Hello, 

i try to run this : 

```
create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      unlock: true,
      timeout: 3600,
      password: ENV["MATCH_KEYCHAIN_PASSWORD"]
    )
```

and i have this error : 
```
[22:59:59]: ------------------------------
[22:59:59]: --- Step: default_platform ---
[22:59:59]: ------------------------------
[22:59:59]: Driving the lane 'ios depoy_fabric' 🚀
bordell[22:59:59]: -----------------------------
[22:59:59]: --- Step: update_fastlane ---
[22:59:59]: -----------------------------
[22:59:59]: Looking for updates for fastlane...
[23:00:17]: Nothing to update ✅
[23:00:17]:
[23:00:17]: Please help us test early releases of fastlane by opting into nightly builds 🌃
[23:00:17]: Just replace your `update_fastlane` call with
[23:00:17]:
[23:00:17]: ▸ update_fastlane(nightly: true)
[23:00:17]:
[23:00:17]: Nightly builds are reviewed and tested just like the public releases 🚂
[23:00:17]:
[23:00:17]: -----------------------------
[23:00:17]: --- Step: create_keychain ---
[23:00:17]: -----------------------------
[23:00:18]: -------------------
[23:00:18]: --- Step: slack ---
[23:00:18]: -------------------
[23:00:19]: Successfully sent Slack notification
+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | ios              |
| PLATFORM_NAME    | ios              |
| LANE_NAME        | ios depoy_fabric |
+------------------+------------------+
[23:00:19]: Shell command exited with exit status 48 instead of 0.

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | update_fastlane  | 17          |
| 💥   | create_keychain  | 0           |
| 4    | slack            | 0           |
+------+------------------+-------------+

[23:00:19]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Colour codes included in slack message
    https://github.com/fastlane/fastlane/issues/48 [closed] 5 💬
    22 Sep 2016

➡️  upload_symbols_to_crashlytics is reporting success, but Fabric is reporting missing dSYMs
    https://github.com/fastlane/fastlane/issues/8053 [open] 10 💬
    3 weeks ago

➡️  Set 'log: true' while calling 'Fastlane::Actions.sh' if CLI option --verbose
    https://github.com/fastlane/fastlane/issues/6878 [closed] 7 💬
    07 Apr 2017

and 9 more at: https://github.com/fastlane/fastlane/search?q=Shell%20command%20exited%20with%20exit%20status%2048%20instead%20of%200.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!': [!] Shell command exited with exit status 48 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/helper/sh_helper.rb:55:in `sh_control_output'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/helper/sh_helper.rb:10:in `sh'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/actions/create_keychain.rb:25:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:55:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

do you have an idea ??

fastlane -v : 
```
fastlane installation at path:
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.36.0/bin/fastlane
-----------------------------
fastlane 2.36.0
```

**Comment by lowki93** [comment]
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

before_all do
  update_fastlane(nightly: false)
end

platform :ios do

  before_all do
    ENV["SLACK_URL"] ||= "https://hooks.slack.com/services/....."
    ENV["MATCH_KEYCHAIN_NAME"] ||= "ios-build.keychain-db"
    ENV["MATCH_KEYCHAIN_PASSWORD"] ||= "test"
    print("bordell")
  end

  # Instalation
  desc "Install the Xcode version used by Aircall"
  lane :install_xcode do
    xcode_install(version: "8.3")
  end

  desc "Install all certificat and provisionning profile"
  lane :instal_certificat do
  match(
    type: "appstore",
    keychain_name: "Aircall",
    keychain_password: "aircall"
  )
  match(
    type: "adhoc",
    keychain_name: "Aircall",
    keychain_password: "aircall"
  )
  match(
    type: "development",
    app_identifier: ["com.aircall.Aircall-Staging", "com.aircall.Aircall-Dev"],
    keychain_name: "Aircall",
    keychain_password: "aircall"
  )
  end

  desc "Run unit test"
  lane :unit_test do
    scan(
      scheme: "Aircall-staging",
      workspace: "Aircall.xcworkspace",
      clean: true,
      sdk: "iphonesimulator",
      devices: ["iPhone 6"]
    )
  end

  desc "Deploy with Fabric"
  lane :depoy_fabric do
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
      password: ENV["MATCH_KEYCHAIN_PASSWORD"]
    )
    unlock_keychain(
      path: ENV["MATCH_KEYCHAIN_NAME"],
      add_to_search_list: true,
      password: ENV['MATCH_KEYCHAIN_PASSWORD']
    )
    match(
      type: "adhoc",
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      readonly: true
    )
    gym(
      scheme: "Aircall",
      export_method: "ad-hoc"
    )
    crashlytics(
      api_token: "...",
      build_secret: "...",
      groups: ["iOS"]
    )
    slack(
       message: "New version has been deploy on Fabric"
    )
    delete_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"]
    )
  end
  error do |lane, exception|
     slack(
       message: exception.message,
       success: false
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.aircall.Aircall" # The bundle identifier of your app
apple_id "budain.kevin@yahoo.fr" # Your Apple email address

team_id "3ML357Q795" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
</details>


*generated on:* **2017-06-06**
</details>
```

**Comment by GoodMirek** [comment]
Is it possible that the keychain file already exists from the previous run?
If the keychain already exists on the CI system it needs to be delete first, otherwise create_keychain fails.
