### ISSUE TITLE
Failure after all screenshots taken, html not created

### ISSUE THREAD

**Issue by ko0f** [fastlane/fastlane#9394]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After taking all screenshots, an exception is thrown, screenshots.html not created.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
```

[10:22:49]: Collecting screenshots...
[10:22:49]: Found 5 screenshots...
[10:22:49]: Copying '/Users/...-d41d8cd98f00b204e9800998ecf8427e.png'...
[10:22:49]: Copying '/Users/...-d41d8cd98f00b204e9800998ecf8427e.png'...
[10:22:49]: Copying '/Users/...-d41d8cd98f00b204e9800998ecf8427e.png'...
[10:22:49]: Copying '/Users/...-d41d8cd98f00b204e9800998ecf8427e.png'...
[10:22:49]: Copying '/Users/...-d41d8cd98f00b204e9800998ecf8427e.png'...

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/string_filters.rb:38:in `wordwrap': [!] upper is smaller than lower in repeat range: /.{1,0}(?:\s+|$)/ (RegexpError)
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/print_table.rb:75:in `transform_row'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/print_table.rb:102:in `block (2 levels) in transform_output'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/print_table.rb:101:in `map'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/print_table.rb:101:in `block in transform_output'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/print_table.rb:100:in `map'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/print_table.rb:100:in `transform_output'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/snapshot/lib/snapshot/runner.rb:127:in `print_results'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/snapshot/lib/snapshot/runner.rb:60:in `work'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/snapshot/lib/snapshot/commands_generator.rb:37:in `block (2 levels) in run'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/snapshot/lib/snapshot/commands_generator.rb:100:in `run'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/snapshot/lib/snapshot/commands_generator.rb:11:in `start'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/.../.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/bin/fastlane:20:in `<top (required)>'
	from /Users/.../.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/.../.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

```

### Environment
```

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-06-07**

```

**Comment by galoz** [comment]
It happens to me as well

/Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/fastlane_core/lib/fastlane_core/string_filters.rb:38:in `wordwrap': [!] upper is smaller than lower in repeat range: /.{1,0}(?:\s+|$)/ (RegexpError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/fastlane_core/lib/fastlane_core/print_table.rb:75:in `transform_row'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/fastlane_core/lib/fastlane_core/print_table.rb:102:in `block (2 levels) in transform_output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/fastlane_core/lib/fastlane_core/print_table.rb:101:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/fastlane_core/lib/fastlane_core/print_table.rb:101:in `block in transform_output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/fastlane_core/lib/fastlane_core/print_table.rb:100:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/fastlane_core/lib/fastlane_core/print_table.rb:100:in `transform_output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/snapshot/lib/snapshot/runner.rb:127:in `print_results'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/snapshot/lib/snapshot/runner.rb:60:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/snapshot/lib/snapshot/commands_generator.rb:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/snapshot/lib/snapshot/commands_generator.rb:100:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/snapshot/lib/snapshot/commands_generator.rb:11:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.48.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by ima747** [comment]
Same. I did delete the screenshots folder just after starting the command while it was still compiling.

**Comment by ohayon** [comment]
Thanks for reporting this issue everyone! We just merged a fix for this and it will go out in our next release! 🚀
