### ISSUE TITLE
supply ssl error

### ISSUE THREAD

**Issue by Vrtak-CZ** [fastlane/fastlane#9399]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
OpenSSL::PKey::RSAError: [!] Neither PUB key nor PRIV key: not enough data
  /usr/local/lib/ruby/gems/2.4.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:69:in `initialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:69:in `new'
  /usr/local/lib/ruby/gems/2.4.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:69:in `make_creds'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/supply/lib/supply/client.rb:59:in `initialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/supply/lib/supply/client.rb:36:in `new'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/supply/lib/supply/client.rb:36:in `make_from_config'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/supply/lib/supply/uploader.rb:174:in `client'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/actions/supply.rb:21:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:40:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.37.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.37.0'

default_platform :android

platform :android do
  desc 'Build Android APK with Gradle'
  lane :build do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: './android',
      print_command: false,
      properties: {
        'RELEASE_STORE_PASSWORD' => ENV['ANDROID_RELEASE_KEYSTORE_PASS'],
        'RELEASE_KEY_PASSWORD' => ENV['ANDROID_RELEASE_CERT_PASS']
      }
    )
  end

  desc 'Build and Push APP to Google Play'
  lane :googleplay do
    build

    supply(
      apk: './android/app/build/outputs/apk/app-release.apk',
      track: 'alpha',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "./fastlane/google-play.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.company.app" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-yarn                   | 1.0     | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.1.0        |
| io-console                             | 0.4.6        |
| CFPropertyList                         | 2.3.5        |
| i18n                                   | 0.8.4        |
| minitest                               | 5.10.2       |
| thread_safe                            | 0.3.6        |
| tzinfo                                 | 1.2.3        |
| activesupport                          | 4.2.8        |
| public_suffix                          | 2.0.5        |
| addressable                            | 2.5.1        |
| babosa                                 | 1.0.2        |
| bundler                                | 1.14.6       |
| claide                                 | 1.0.1        |
| fuzzy_match                            | 2.0.4        |
| nap                                    | 1.1.0        |
| cocoapods-core                         | 1.2.1        |
| cocoapods-deintegrate                  | 1.0.1        |
| cocoapods-downloader                   | 1.1.3        |
| cocoapods-plugins                      | 1.0.0        |
| cocoapods-search                       | 1.0.0        |
| cocoapods-stats                        | 1.0.0        |
| netrc                                  | 0.7.8        |
| cocoapods-trunk                        | 1.2.0        |
| cocoapods-try                          | 1.1.0        |
| colored2                               | 3.1.2        |
| escape                                 | 0.0.4        |
| fourflusher                            | 2.0.1        |
| gh_inspector                           | 1.0.3        |
| molinillo                              | 0.5.7        |
| ruby-macho                             | 1.1.0        |
| nanaimo                                | 0.2.3        |
| xcodeproj                              | 1.4.4        |
| cocoapods                              | 1.2.1        |
| colored                                | 1.2          |
| highline                               | 1.7.8        |
| commander-fastlane                     | 4.4.4        |
| unf_ext                                | 0.0.7.4      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20170404 |
| dotenv                                 | 2.2.1        |
| excon                                  | 0.56.0       |
| multipart-post                         | 2.0.0        |
| faraday                                | 0.12.1       |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday_middleware                     | 0.11.0.1     |
| fastimage                              | 2.1.0        |
| jwt                                    | 1.5.6        |
| little-plugger                         | 1.1.4        |
| multi_json                             | 1.12.1       |
| logging                                | 2.2.2        |
| memoist                                | 0.15.0       |
| os                                     | 0.9.6        |
| signet                                 | 0.7.3        |
| googleauth                             | 0.5.1        |
| httpclient                             | 2.8.3        |
| hurley                                 | 0.2          |
| mime-types-data                        | 3.2016.0521  |
| mime-types                             | 3.1          |
| uber                                   | 0.0.15       |
| representable                          | 2.3.0        |
| retriable                              | 2.1.0        |
| google-api-client                      | 0.9.28       |
| json                                   | 2.1.0        |
| mini_magick                            | 4.5.1        |
| multi_xml                              | 0.6.0        |
| plist                                  | 3.3.0        |
| rubyzip                                | 1.2.1        |
| security                               | 0.1.3        |
| slack-notifier                         | 1.5.1        |
| terminal-notifier                      | 1.8.0        |
| unicode-display_width                  | 1.2.1        |
| terminal-table                         | 1.8.0        |
| tty-screen                             | 0.5.0        |
| word_wrap                              | 1.0.0        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.2.8        |
| xcpretty-travis-formatter              | 0.0.4        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-yarn                   | 1.0          |
| openssl                                | 2.0.3        |
</details>

**Comment by Vrtak-CZ** [comment]
Btw it works on Friday (2017-06-02) and we did not make any changes (except fastlane update).
