### ISSUE TITLE
why i get Error parsing provisioning profile at path ??? i m doing ipa resigh, how to fixed it? pls help.  

### ISSUE THREAD

**Issue by zuodd** [fastlane/fastlane#9407]
/Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/interface.rb:119:in `crash!': [31m[!] Error parsing provisioning profile at path '/Library/WebServer/Documents/iPaResign/2017-06-08-09-22-34.mobileprovision'[0m (FastlaneCore::Interface::FastlaneCrash)
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:31:in `parse'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:37:in `uuid'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/sigh/lib/sigh/manager.rb:38:in `install_profile'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/sigh/lib/sigh/manager.rb:25:in `start'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/sigh/lib/sigh/commands_generator.rb:55:in `block (2 levels) in run'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/sigh/lib/sigh/commands_generator.rb:123:in `run'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/bin/fastlane:20:in `'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/bin/fastlane:23:in `load'
	from /Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/bin/fastlane:23:in `
'
	from /Users/dongdongzuo/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dongdongzuo/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `

**Comment by zuodd** [comment]
i call the shell command in php:

$output = shell_exec('export PATH=/Users/dongdongzuo/.rvm/gems/ruby-2.3.2/bin:/Users/dongdongzuo/.rvm/gems/ruby-2.3.2@global/bin:/Users/dongdongzuo/.rvm/rubies/ruby-2.3.2/bin:/Users/dongdongzuo/.rvm/bin:$PATH && export HOME=/Users/dongdongzuo && sh /Library/WebServer/Documents/iPaResign/auto_build.sh 2>&1 1> /dev/null');

**Comment by zuodd** [comment]
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.0       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
</details>

**Comment by zuodd** [comment]
/Users/dongdongzuo/.rvm/gems/ruby-2.3.2@global/gems/fastlane-2.37.0/bin/fastlane
-----------------------------
fastlane 2.37.0
