### ISSUE TITLE
undefined method `-' for {:retry_count=>2}:Hash

### ISSUE THREAD

**Issue by octopitus** [fastlane/fastlane#9485]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

```
/Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/spaceship/lib/spaceship/client.rb:522:in `rescue in with_retry': [!] undefined method `-' for {:retry_count=>2}:Hash (NoMethodError)
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/spaceship/lib/spaceship/client.rb:516:in `with_retry'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/spaceship/lib/spaceship/test_flight/client.rb:32:in `get_builds_for_train'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/spaceship/lib/spaceship/test_flight/build.rb:89:in `builds_for_train'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane_core/lib/fastlane_core/build_watcher.rb:33:in `matching_build'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane_core/lib/fastlane_core/build_watcher.rb:11:in `block in wait_for_build_processing_to_be_complete'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane_core/lib/fastlane_core/build_watcher.rb:10:in `loop'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane_core/lib/fastlane_core/build_watcher.rb:10:in `wait_for_build_processing_to_be_complete'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/pilot/lib/pilot/build_manager.rb:38:in `upload'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/actions/pilot.rb:15:in `run'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:38:in `block (2 levels) in parsing_binding'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/yul/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/bin/fastlane:20:in `<top (required)>'
	from /Users/yul/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/yul/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G1510)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.27.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    increment_build_number(build_number: options[:build_number])
    gym(
      scheme: "LeapXpert",
      export_method: "app-store"
    )
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.leapxpert.user.staging"
apple_id "ka@codelink.io" # Your Apple email address

team_id "R97P9Y344B" # Developer Portal Team ID
itc_team_name "Valep Limited"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.38.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-15**
</details>

**Comment by ohayon** [comment]
Hey @octopitus, could you share some more of the output from before the stack trace to give a bit more context about what is going on when this crashes? Thanks! 🐙

**Comment by DmitryBespalov** [comment]
```
[21:38:19]: Waiting for iTunes Connect to finish processing the new build (1.0 - 37)
[21:38:50]: Waiting for iTunes Connect to finish processing the new build (1.0 - 37)
[21:39:22]: Waiting for iTunes Connect to finish processing the new build (1.0 - 37)
[21:39:55]: Waiting for iTunes Connect to finish processing the new build (1.0 - 37)
[21:40:27]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:40:58]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:41:30]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:42:01]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:42:32]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:43:05]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:43:40]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:44:19]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:44:51]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:45:22]: Build doesn't show up in the build list any more, waiting for it to appear again
[21:45:59]: fastlane failed to write the crash report to /Users/macbookpro/.fastlane/latest_crash.json.
[21:45:59]: Sending crash report...
[21:45:59]: The stacktrace is sanitized so no personal information is sent.
[21:45:59]: To see what we are sending, look here: /Users/macbookpro/.fastlane/latest_crash.json
[21:45:59]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[21:45:59]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
+------------------------------------+--------------------------------------+
|                               Lane Context                                |
+------------------------------------+--------------------------------------+
| DEFAULT_PLATFORM                   | ios                                  |
| PLATFORM_NAME                      | ios                                  |
| LANE_NAME                          | ios beta                             |
| GIT_REPO_WAS_CLEAN_ON_START        | true                                 |
| BUILD_NUMBER                       | 37                                   |
| SIGH_PROFILE_TYPE                  | app-store                            |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"XXX"=>  |
|                                    | "match AppStore                      |
|                                    | XXX"}     |
| IPA_OUTPUT_PATH                    | /Users/macbookpro/Documents/Zoom     |
|                                    | Labs/projects/socialanalyzer-ios/Bu  |
|                                    | ild/SocialAnalyzer.ipa               |
| DSYM_OUTPUT_PATH                   | /Users/macbookpro/Documents/Zoom     |
|                                    | Labs/projects/socialanalyzer-ios/Bu  |
|                                    | ild/SocialAnalyzer.app.dSYM.zip      |
| XCODEBUILD_ARCHIVE                 | /Users/macbookpro/Library/Developer  |
|                                    | /Xcode/Archives/2017-06-15/SocialAn  |
|                                    | alyzer 2017-06-15                    |
|                                    | 21.27.21.xcarchive                   |
+------------------------------------+--------------------------------------+
[21:45:59]: undefined method `-' for {:retry_count=>2}:Hash

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | ensure_git_status_cle  | 0           |
|      | an                     |             |
| 4    | increment_build_numbe  | 7           |
|      | r                      |             |
| 5    | commit_version_bump    | 0           |
| 6    | push_to_git_remote     | 2           |
| 7    | match                  | 9           |
| 8    | gym                    | 181         |
| 💥   | pilot                  | 946         |
+------+------------------------+-------------+

[21:45:59]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `-' for {:retry_count=>2}:Hash
    https://github.com/fastlane/fastlane/issues/9485 [open] 1 💬
    5 hours ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/macbookpro/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/spaceship/lib/spaceship/client.rb:522:in `rescue in with_retry': [!] undefined method `-' for {:retry_count=>2}:Hash (NoMethodError)
```


This is what was my output

**Comment by miroslavkovac** [comment]
Seams like an issue with 2.38.1 version. I rolled back to 2.37.0 and it works fine for me.

**Comment by KrauseFx** [comment]
Thanks for letting us know, we'll fix that as soon as possible, already prepared a fix https://github.com/fastlane/fastlane/pull/9495

**Comment by octopitus** [comment]
wow, thanks @KrauseFx, that was too fast.

**Comment by ohayon** [comment]
We will be getting this out in a release in just a little bit!
