### ISSUE TITLE
INSTRUMENTATION_FAILED error when running screengrab on multi-flavor setup

### ISSUE THREAD

**Issue by jdbenito** [fastlane/fastlane#9510]
### New Issue Checklist

- [x] Updated fastlane to the latest version 2.39.1
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a multi-product-flavour project. Here's a snippet of my build.gradle file:

```
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.zenith"
        minSdkVersion 16
        targetSdkVersion 25
        multiDexEnabled true
        . . .
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        testApplicationId "com.zenith"
        testHandleProfiling true
        testFunctionalTest true
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
        Sandbox {
            applicationIdSuffix ".sandbox"
            . . . 
        }
        Demo {
            applicationIdSuffix ".demo"
            . . .
        }
    }
```

I am also fairly new to Espresso so I just setup a simple screenshot grab on the first page that loads.

The UI test passes fine when I run it both through the IDE and command line through gradle.

A thing of note is that the package name declared in my AndroidManifest is different from the applicationId declared in the app's build.gradle. Also my flavours append a suffix to the applicationId.

Here is the log that I get back upon running ```fastlane screengrab```

```fastlane screengrab
[15:01:45]: Successfully loaded '/Users/jben/Workspaces/android-myproject/fastlane/Screengrabfile' 📄

+----------------------------+--------------------------------------+
|         Detected Values from './fastlane/Screengrabfile'          |
+----------------------------+--------------------------------------+
| app_apk_path               | /Users/jben/Workspaces/android-mypr  |
|                            | oject/app/build/outputs/apk/app-San  |
|                            | dbox-debug.apk                       |
| tests_apk_path             | /Users/jben/Workspaces/android-mypr  |
|                            | oject/app/build/outputs/apk/app-San  |
|                            | dbox-debug-androidTest.apk           |
| locales                    | ["en-US"]                            |
| clear_previous_screenshots | true                                 |
+----------------------------+--------------------------------------+

[15:01:45]: The `aapt` command could not be found on your PATH
[15:01:45]: Please ensure that the Android SDK is installed and you have the build tools downloaded and present on your PATH

+-----------------------------+--------------------------------------+
|                   Summary for screengrab 2.39.1                    |
+-----------------------------+--------------------------------------+
| app_apk_path                | /Users/jben/Workspaces/android-mypr  |
|                             | oject/app/build/outputs/apk/app-San  |
|                             | dbox-debug.apk                       |
| tests_apk_path              | /Users/jben/Workspaces/android-mypr  |
|                             | oject/app/build/outputs/apk/app-San  |
|                             | dbox-debug-androidTest.apk           |
| locales                     | ["en-US"]                            |
| clear_previous_screenshots  | true                                 |
| tests_package_name          | com.hermes.myproject.test            |
| output_directory            | fastlane/metadata/android            |
| skip_open_summary           | false                                |
| app_package_name            | com.hermes.myproject                 |
| test_instrumentation_runner | android.support.test.runner.Android  |
|                             | JUnitRunner                          |
| ending_locale               | en-US                                |
| device_type                 | phone                                |
| exit_on_test_failure        | true                                 |
| reinstall_app               | false                                |
+-----------------------------+--------------------------------------+

[15:01:46]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[15:01:46]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[15:01:46]: Clearing phoneScreenshots within fastlane/metadata/android
[15:01:46]: $ adb devices -l
[15:01:46]: ▸ List of devices attached
[15:01:46]: ▸ emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
[15:01:46]: $ adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[15:01:46]: ▸ /storage/sdcard
[15:01:46]: Cleaning screenshots on device
[15:01:46]: The `aapt` command could not be found on your system, so your app APK could not be validated
[15:01:46]: Installing app APK
[15:01:46]: $ adb -s emulator-5554 install -r /Users/jben/Workspaces/android-myproject/app/build/outputs/apk/app-Sandbox-debug.apk
[15:01:46]: ▸ /Users/jben/Workspaces/android-myproject/app/build/outputs/apk/app-Sandbox-debug.apk: 1 file pushed. 54.2 MB/s (3153783 bytes in 0.056s)
[15:01:46]: ▸ pkg: /data/local/tmp/app-Sandbox-debug.apk
[15:01:48]: ▸ Success
[15:01:48]: Installing tests APK
[15:01:48]: $ adb -s emulator-5554 install -r /Users/jben/Workspaces/android-myproject/app/build/outputs/apk/app-Sandbox-debug-androidTest.apk
[15:01:48]: ▸ /Users/jben/Workspaces/android-myproject/app/build/outputs/apk/app-Sandbox-debug-androidTest.apk: 1 file pushed. 20.9 MB/s (1171941 bytes in 0.054s)
[15:01:48]: ▸ pkg: /data/local/tmp/app-Sandbox-debug-androidTest.apk
[15:01:49]: ▸ Success
[15:01:49]: Granting the permission necessary to change locales on the device
[15:01:49]: $ adb -s emulator-5554 shell pm grant com.hermes.myproject android.permission.CHANGE_CONFIGURATION
[15:01:49]: ▸ Bad argument: java.lang.IllegalArgumentException: Unknown package: com.hermes.myproject
[15:01:49]: ▸ usage: pm list packages [-f] [-d] [-e] [-s] [-3] [-i] [-u] [--user USER_ID] [FILTER]
[15:01:49]: ▸ pm list permission-groups
[15:01:49]: ▸ pm list permissions [-g] [-f] [-d] [-u] [GROUP]
[15:01:49]: ▸ pm list instrumentation [-f] [TARGET-PACKAGE]
[15:01:49]: ▸ pm list features
[15:01:49]: ▸ pm list libraries
[15:01:49]: ▸ pm list users
[15:01:49]: ▸ pm path PACKAGE
[15:01:49]: ▸ pm dump PACKAGE
[15:01:49]: ▸ pm install [-lrtsfd] [-i PACKAGE] [PATH]
[15:01:49]: ▸ pm install-create [-lrtsfdp] [-i PACKAGE] [-S BYTES]
[15:01:49]: ▸ pm install-write [-S BYTES] SESSION_ID SPLIT_NAME [PATH]
[15:01:49]: ▸ pm install-commit SESSION_ID
[15:01:49]: ▸ pm install-abandon SESSION_ID
[15:01:49]: ▸ pm uninstall [-k] [--user USER_ID] PACKAGE
[15:01:49]: ▸ pm set-installer PACKAGE INSTALLER
[15:01:49]: ▸ pm clear [--user USER_ID] PACKAGE
[15:01:49]: ▸ pm enable [--user USER_ID] PACKAGE_OR_COMPONENT
[15:01:49]: ▸ pm disable [--user USER_ID] PACKAGE_OR_COMPONENT
[15:01:49]: ▸ pm disable-user [--user USER_ID] PACKAGE_OR_COMPONENT
[15:01:49]: ▸ pm disable-until-used [--user USER_ID] PACKAGE_OR_COMPONENT
[15:01:49]: ▸ pm hide [--user USER_ID] PACKAGE_OR_COMPONENT
[15:01:49]: ▸ pm unhide [--user USER_ID] PACKAGE_OR_COMPONENT
[15:01:49]: ▸ pm grant PACKAGE PERMISSION
[15:01:49]: ▸ pm revoke PACKAGE PERMISSION
[15:01:49]: ▸ pm set-install-location [0/auto] [1/internal] [2/external]
[15:01:49]: ▸ pm get-install-location
[15:01:49]: ▸ pm set-permission-enforced PERMISSION [true|false]
[15:01:49]: ▸ pm trim-caches DESIRED_FREE_SPACE
[15:01:49]: ▸ pm create-user [--profileOf USER_ID] [--managed] USER_NAME
[15:01:49]: ▸ pm remove-user USER_ID
[15:01:49]: ▸ pm get-max-users
[15:01:49]: ▸ pm list packages: prints all packages, optionally only
[15:01:49]: ▸ those whose package name contains the text in FILTER.  Options:
[15:01:49]: ▸ -f: see their associated file.
[15:01:49]: ▸ -d: filter to only show disbled packages.
[15:01:49]: ▸ -e: filter to only show enabled packages.
[15:01:49]: ▸ -s: filter to only show system packages.
[15:01:49]: ▸ -3: filter to only show third party packages.
[15:01:49]: ▸ -i: see the installer for the packages.
[15:01:49]: ▸ -u: also include uninstalled packages.
[15:01:49]: ▸ pm list permission-groups: prints all known permission groups.
[15:01:49]: ▸ pm list permissions: prints all known permissions, optionally only
[15:01:49]: ▸ those in GROUP.  Options:
[15:01:49]: ▸ -g: organize by group.
[15:01:49]: ▸ -f: print all information.
[15:01:49]: ▸ -s: short summary.
[15:01:49]: ▸ -d: only list dangerous permissions.
[15:01:49]: ▸ -u: list only the permissions users will see.
[15:01:49]: ▸ pm list instrumentation: use to list all test packages; optionally
[15:01:49]: ▸ supply <TARGET-PACKAGE> to list the test packages for a particular
[15:01:49]: ▸ application.  Options:
[15:01:49]: ▸ -f: list the .apk file for the test package.
[15:01:49]: ▸ pm list features: prints all features of the system.
[15:01:49]: ▸ pm list users: prints all users on the system.
[15:01:49]: ▸ pm path: print the path to the .apk of the given PACKAGE.
[15:01:49]: ▸ pm dump: print system state associated with the given PACKAGE.
[15:01:49]: ▸ pm install: install a single legacy package
[15:01:49]: ▸ pm install-create: create an install session
[15:01:49]: ▸ -l: forward lock application
[15:01:49]: ▸ -r: replace existing application
[15:01:49]: ▸ -t: allow test packages
[15:01:49]: ▸ -i: specify the installer package name
[15:01:49]: ▸ -s: install application on sdcard
[15:01:49]: ▸ -f: install application on internal flash
[15:01:49]: ▸ -d: allow version code downgrade
[15:01:49]: ▸ -p: partial application install
[15:01:49]: ▸ -S: size in bytes of entire session
[15:01:49]: ▸ pm install-write: write a package into existing session; path may
[15:01:49]: ▸ be '-' to read from stdin
[15:01:49]: ▸ -S: size in bytes of package, required for stdin
[15:01:49]: ▸ pm install-commit: perform install of fully staged session
[15:01:49]: ▸ pm install-abandon: abandon session
[15:01:49]: ▸ pm set-installer: set installer package name
[15:01:49]: ▸ pm uninstall: removes a package from the system. Options:
[15:01:49]: ▸ -k: keep the data and cache directories around after package removal.
[15:01:49]: ▸ pm clear: deletes all data associated with a package.
[15:01:49]: ▸ pm enable, disable, disable-user, disable-until-used: these commands
[15:01:49]: ▸ change the enabled state of a given package or component (written
[15:01:49]: ▸ as "package/class").
[15:01:49]: ▸ pm grant, revoke: these commands either grant or revoke permissions
[15:01:49]: ▸ to applications.  Only optional permissions the application has
[15:01:49]: ▸ declared can be granted or revoked.
[15:01:49]: ▸ pm get-install-location: returns the current install location.
[15:01:49]: ▸ 0 [auto]: Let system decide the best location
[15:01:49]: ▸ 1 [internal]: Install on internal device storage
[15:01:49]: ▸ 2 [external]: Install on external media
[15:01:49]: ▸ pm set-install-location: changes the default install location.
[15:01:49]: ▸ NOTE: this is only intended for debugging; using this can cause
[15:01:49]: ▸ applications to break and other undersireable behavior.
[15:01:49]: ▸ 0 [auto]: Let system decide the best location
[15:01:49]: ▸ 1 [internal]: Install on internal device storage
[15:01:49]: ▸ 2 [external]: Install on external media
[15:01:49]: ▸ pm trim-caches: trim cache files to reach the given free space.
[15:01:49]: ▸ pm create-user: create a new user with the given USER_NAME,
[15:01:49]: ▸ printing the new user identifier of the user.
[15:01:49]: ▸ pm remove-user: remove the user with the given USER_IDENTIFIER,
[15:01:49]: ▸ deleting all data associated with that user
[15:01:49]: $ adb -s emulator-5554 shell getprop ro.build.version.sdk
[15:01:49]: ▸ 22
[15:01:49]: Running tests for locale: en-US
[15:01:49]: $ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
com.hermes.myproject.test/android.support.test.runner.AndroidJUnitRunner
[15:01:49]: ▸ INSTRUMENTATION_STATUS: id=ActivityManagerService
[15:01:49]: ▸ INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.hermes.myproject.test/android.support.test.runner.AndroidJUnitRunner}
[15:01:49]: ▸ INSTRUMENTATION_STATUS_CODE: -1
[15:01:49]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.hermes.myproject.test/android.support.test.runner.AndroidJUnitRunner
[15:01:49]: ▸ at com.android.commands.am.Am.runInstrument(Am.java:977)
[15:01:49]: ▸ at com.android.commands.am.Am.onRun(Am.java:317)
[15:01:49]: ▸ at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
[15:01:49]: ▸ at com.android.commands.am.Am.main(Am.java:97)
[15:01:49]: ▸ at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[15:01:49]: ▸ at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
[15:01:49]: Pulling captured screenshots from the device
[15:01:49]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

[!] No screenshots were detected 📷❌
```

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.39.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

**Comment by jdbenito** [comment]
@KrauseFx any ideas or some guidance on this? would be really appreciated, thanks!

**Comment by jdbenito** [comment]
anyone with any ideas on how to handle this?

**Comment by kassim** [comment]
run

**Comment by kassim** [comment]
run 
`adb -s YOUR_EMULATOR_NAME shell pm list packages`

and make sure you're targetting the correct package (that it is actually present in the list)

what I found was I had appended `.debug` to my debug builds so what I thought was my package name was wrong
