### ISSUE TITLE
Crashlytics Beta Android Upload fails due to inactive project

### ISSUE THREAD

**Issue by oleschaper** [fastlane/fastlane#9529]
Since a few days, I always get an error when trying to upload an android apk to crashlytics beta.

Exception:
--

```
[23:05:12]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[23:05:14]: Shell command exited with exit status 1 instead of 0.
[23:05:14]:  WARN - Crashlytics had a problem uploading the distribution. Project XXX is inactive
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it had a problem uploading the distribution.Project XXX is inactive
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:91)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more

[23:05:14]: Build successfully uploaded to Crashlytics Beta 🌷
```

--

Fastfile Call:
```
    crashlytics(
      apk_path: "builds/Android/#{ENV['FL_PROJECT_NAME']}_#{version}.#{build}.apk",
      notes: changelog,
      groups: ["internal_android"]
    )
```

--

I also tried without notes and groups defined, same error.

In another thread I've read that this could be an issue if you have a new project (identifier) that never received any events yet. This can not be the case for us, the upload worked fine before and still does on ios. I also started the app multiple times on android.

Any idea what could be the problem?

Thank you very much!

**Comment by oleschaper** [comment]
Nobody?

**Comment by oleschaper** [comment]
Ok, so if anyone runs into the same problem, for me it seems to be due to a Unity 5.6.1 bug.
The package name (bundle identifier) was replaced during the build process with the default one, generated from the company name and product name (like this: unity.companyname.productname).
The crashlytics error message is misleading, there just is no project with that package name, but it just tells me the project NAME is inactive (without mentioning the package name/bundle identifier).
