### ISSUE TITLE
Cannot post to slack after pem file is generated

### ISSUE THREAD

**Issue by mono0926** [fastlane/fastlane#958]
I cannot post to slack after pem file is generated.
What should I do?

Fastfile:
```ruby
lane :check_pem do
  pem(
    force: true,
    new_profile: proc do |profile_path| 
      slack(
        message: "@mono Pem file is regenerated!!!!!",
        channel: "#ios-feed"
      )
    end
  )
end
```

Output:
```sh
[22:03:46]: Existing push notification profile 'Ghost Release' is valid for 43 more days.
[22:03:46]: You already have an existing push certificate, but a new one will be created since the --force option has been set.
[22:03:46]: Creating a new push certificate for app 'com.aquatica.ghost.release'.
[22:03:48]: Private key: /Users/mono/Documents/Git/Aquatica/Ghost-IOS/production_com.aquatica.ghost.release.pkey
[22:03:48]: p12 certificate: /Users/mono/Documents/Git/Aquatica/Ghost-IOS/production_com.aquatica.ghost.release.p12
[22:03:48]: PEM: /Users/mono/Documents/Git/Aquatica/Ghost-IOS/production_com.aquatica.ghost.release.pem
[22:03:48]: -------------------
[22:03:48]: --- Step: slack ---
[22:03:48]: -------------------
fatal: Not a git repository (or any of the parent directories): .git
[22:03:48]: Variable Dump:
[22:03:48]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios check_pem"}
[22:03:48]: Exit status of command 'git log -1 --pretty=%B' was 128 instead of 0.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | slack                               | 0           |
| 4    | pem                                 | 12          |
+------+-------------------------------------+-------------+

[22:03:48]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '33898b1025034661317ca9e7106e8738'
The crash report has been stored locally '/tmp/sentry_33898b1025034661317ca9e7106e8738.json'
```

If slack command only, post was succeeded.
```ruby
lane :check_pem do
  slack(
    message: "@mono Pem file is regenerated!!!!!",
    channel: "#ios-feed"
  )
end
```

---
fastlane version is 1.45.0

**Comment by KrauseFx** [comment]
I assume the block is being executed in a different folder context, maybe try wrapping it inside
```ruby
Dir.chdir("..") do
  pem
end
```

**Comment by ffittschen** [comment]
I'm getting the same error without usage of `pem`. I use slack in the `after_all do |lane|` block.

For me the critical line is `Exit status of command 'git log -1 --pretty=%B' was 128 instead of 0.` as well.

Crash log:
```
[23:05:08]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
✨  Once crash reporting is enabled, you get a clean output when something goes wrong.
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
>> /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/helper/sh_helper.rb:40:in `sh_no_action'
>>  : Exit status of command 'git log -1 --pretty=%B' was 128 instead of 0. (RuntimeError)
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/helper/git_helper.rb:24:in `last_git_commit_formatted_with'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/helper/git_helper.rb:52:in `last_git_commit_message'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/actions/slack.rb:172:in `generate_slack_attachments'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/actions/slack.rb:42:in `run'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/runner.rb:128:in `block in execute_action'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/runner.rb:127:in `chdir'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/runner.rb:127:in `execute_action'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/fast_file.rb:149:in `method_missing'
>>  from Fastfile:157:in `block in parsing_binding'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/runner.rb:66:in `call'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/runner.rb:66:in `block in execute'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/runner.rb:61:in `chdir'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/runner.rb:61:in `rescue in execute'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/runner.rb:45:in `execute'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/lib/fastlane/command_line_handler.rb:30:in `handle'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/bin/fastlane:35:in `block (2 levels) in run'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/bin/fastlane:152:in `run'
>>  from /Users/appdev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane-1.45.0/bin/fastlane:158:in `<top (required)>'
>>  from /Users/appdev/.rbenv/versions/2.2.2/bin/fastlane:23:in `load'
>>  from /Users/appdev/.rbenv/versions/2.2.2/bin/fastlane:23:in `<main>'
```

**Comment by mono0926** [comment]
@KrauseFx 

Thanks, but `pem` was succeeded from the first.
Then problem is `slack` command, specified at `new_profile`, was failed.
How should I change this code?

```ruby
lane :check_pem do
  pem(
    force: true,
    new_profile: proc do |profile_path| 
      slack(
        message: "@mono Pem file is regenerated!!!!!",
        channel: "#ios-feed"
      )
    end
  )
end
```

**Comment by KrauseFx** [comment]
Interesting, thanks for all the information, will take a look at this now :+1:

**Comment by KrauseFx** [comment]
Quick question, do you use `git` in this directory?

**Comment by mono0926** [comment]
@KrauseFx 

Yes :octocat:

**Comment by KrauseFx** [comment]
@mono0926 does `slack` work for you when it's outside the `pem` block?

**Comment by mono0926** [comment]
@KrauseFx 

Yes :santa:

**Comment by KrauseFx** [comment]
So yeah, these are 2 different errors - I just fixed the one from @ffittschen, working on yours next :+1:

**Comment by KrauseFx** [comment]
@mono0926 Please try this:

```ruby
lane :check_pem do
  pem(
    force: true,
    new_profile: proc do |profile_path| 
     Dir.chdir("./my_project") do
      slack(
        message: "@mono Pem file is regenerated!!!!!",
        channel: "#ios-feed"
      )
     end
    end
  )
end
```

**Comment by mono0926** [comment]
@KrauseFx 

Thanks, the lane finished successfully :tada: 

```ruby
lane :check_pem do
  current = Dir.pwd
  pem(
    force: true,
    new_profile: proc do |profile_path| 
      Dir.chdir(current) do
        slack(
          message: "@mono Pem file is regenerated!!!!!",
          channel: "#ios-feed"
        )
      end
    end
  )
end
```

Is the nested lane not supported as a general rule?

**Comment by KrauseFx** [comment]
@mono0926 It's not supported currently :+1:

**Comment by mono0926** [comment]
@KrauseFx 

Okay, thanks :japanese_castle:

**Comment by ffittschen** [comment]
@KrauseFX
Just tested it for my case: works perfectly, thanks!

**Comment by KrauseFx** [comment]
Yeah :rocket:
