### ISSUE TITLE
Pulling captured screenshots from the device... No screenshots were detected, again!

### ISSUE THREAD

**Issue by dpettit** [fastlane/fastlane#9599]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Possibly related to closed issue #8217?

Same script ran successfully earlier this evening, and I received screenshots from each emulator device just fine.  No updates were made, no changes to system or configuration, and no updates to code.  I have seen the "Instrumentation_status" errors in the past, but only if my live device was attached at the time my script was run.  However, now I receive the error every time I run my script.

When I run code manually in Android Studio, it runs just fine.  Only when I run via the CLI do I receive the errors.

Any ideas as to why, or how to fix?
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

################################################################################
Starting BT-A-3 script execution...
################################################################################
Current Tap delay setting: 2 seconds, but this does not yet work for Android.

Number of pages that need screengrabs: 14
Generating Android Instrumentation Test code for taking screengrabs...

Processing page number: 1
Processing page number: 2
Processing page number: 3
Processing page number: 4
Processing page number: 5
Processing page number: 6
Processing page number: 7
Processing page number: 8
Processing page number: 9
Processing page number: 10
Processing page number: 11
Processing page number: 12
Processing page number: 13
Processing page number: 14

Android tests were created for 14 pages.

End BT-A-3 script execution; returning control to main script.
*************************************************************
Alias name (shortname) = mydaddy

Keystore directory = /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/Resources/fastlane-android/keys

Find-Alias found the following: mydaddy, Nov 17, 2016, PrivateKeyEntry, 
Certificate fingerprint (SHA1): CB:E3:11:CD:5A:FC:E1:69:EF:35:36:7E:64:3E:03:1E:D2:87:C3:8F

Alias found, no need to create a new one.

*************************************************************
Begin BT-A-4 script execution...
*************************************************************
Android_TV_-1080p-API_24
Phone_-_Nexus_4_-_API_19
Phone_-_Nexus_4_-_API_22
Phone_-_Nexus_4_-_API_23
Phone_-_Nexus_4_-_API_25
Phone_-_Nexus_5X_-_API_22
Phone_-_Nexus_5_-_API_19
Phone_-_Nexus_5_-_API_22
Phone_-_Nexus_5_-_API_24
Phone_-_Nexus_5_-_API_26
Phone_-_Nexus_6P_-_API_22
Phone_-_Nexus_6P_-_API_23
Phone_-_Nexus_6_-_API_19
Phone_-_Nexus_6_-_API_22
Phone_-_Nexus_6_-_API_23
Phone_-_Nexus_S_-_API_19
Phone_-_Nexus_S_-_API_22
Phone_-_Nexus_S_-_API_23
Tablet_-_Nexus_10_-_API_19
Tablet_-_Nexus_10_-_API_22
Tablet_-_Nexus_10_-_API_23
Tablet_-_Nexus_7_-_API_19
Tablet_-_Nexus_7_-_API_22
Tablet_-_Nexus_7_-_API_23
Tablet_-_Nexus_7_2012_-_API_19
Tablet_-_Nexus_7_2012_-_API_22
Tablet_-_Nexus_7_2012_-_API_23
Tablet_-_Nexus_7_2012_-_API_23_-_2
Tablet_-_Nexus_9_-_API_19
Tablet_-_Nexus_9_-_API_22
Tablet_-_Nexus_9_-_API_23
Tablet_-_WSVGA_7_-_API_19
Tablet_-_WSVGA_7_-_API_22
Tablet_-_WSVGA_7_-_API_23
Tablet_-_WXGA_10_1_-_API_19
Tablet_-_WXGA_10_1_-_API_22
Tablet_-_WXGA_10_1_-_API_23

No open emulators found!

Build DebugAndroidTest and Debug using Gradle...

error: no emulator detected
[23:53:59]: -------------------------------------------------
[23:53:59]: --- Step: Verifying required fastlane version ---
[23:53:59]: -------------------------------------------------
[23:53:59]: Your fastlane version 2.41.0 matches the minimum requirement of 1.104.0  ✅
[23:53:59]: ------------------------------
[23:53:59]: --- Step: default_platform ---
[23:53:59]: ------------------------------
[23:53:59]: Driving the lane 'android buildDebug' 🚀
[23:53:59]: --------------------
[23:53:59]: --- Step: gradle ---
[23:53:59]: --------------------
[23:53:59]: $ /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/gradlew clean assembleDebugAndroidTest assembleDebug -p .
[23:54:00]: ▸ Parallel execution is an incubating feature.
[23:54:00]: ▸ NDK is missing a "platforms" directory.
[23:54:00]: ▸ If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/tsdev/Library/Android/sdk/ndk-bundle.
[23:54:00]: ▸ If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
[23:54:00]: ▸ Incremental java compilation is an incubating feature.
[23:54:00]: ▸ :clean
[23:54:00]: ▸ :preBuild UP-TO-DATE
[23:54:00]: ▸ :preDebugBuild UP-TO-DATE
[23:54:00]: ▸ :checkDebugManifest
[23:54:00]: ▸ :preReleaseBuild UP-TO-DATE
[23:54:00]: ▸ :prepareComAndroidSupportTestEspressoEspressoCore221Library
[23:54:00]: ▸ :prepareComAndroidSupportTestEspressoEspressoIdlingResource221Library
[23:54:00]: ▸ :preDebugAndroidTestBuild UP-TO-DATE
[23:54:00]: ▸ :prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
[23:54:00]: ▸ :prepareComAndroidSupportTestRules05Library
[23:54:00]: ▸ :prepareComAndroidSupportTestRunner05Library
[23:54:00]: ▸ :prepareComAndroidSupportTestUiautomatorUiautomatorV18212Library
[23:54:00]: ▸ :prepareToolsFastlaneScreengrab055Library
[23:54:00]: ▸ :prepareDebugDependencies
[23:54:00]: ▸ :compileDebugAidl
[23:54:00]: ▸ :compileDebugRenderscript
[23:54:00]: ▸ :generateDebugBuildConfig
[23:54:00]: ▸ :generateDebugResValues
[23:54:00]: ▸ :generateDebugResources
[23:54:00]: ▸ :mergeDebugResources
[23:54:00]: ▸ :processDebugManifest
[23:54:00]: ▸ :processDebugResources
[23:54:00]: ▸ :generateDebugSources
[23:54:00]: ▸ :incrementalDebugJavaCompilationSafeguard
[23:54:00]: ▸ :javaPreCompileDebug
[23:54:00]: ▸ :compileDebugJavaWithJavac
[23:54:00]: ▸ :compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
[23:54:00]: ▸ Note: /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/src/com/talespring/wrapper/AndroidHTMLWrapper.java uses or overrides a deprecated API.
[23:54:00]: ▸ Note: Recompile with -Xlint:deprecation for details.
[23:54:00]: ▸ :prepareDebugAndroidTestDependencies
[23:54:00]: ▸ :compileDebugAndroidTestAidl
[23:54:00]: ▸ :processDebugAndroidTestManifest
[23:54:00]: ▸ :compileDebugAndroidTestRenderscript
[23:54:00]: ▸ :generateDebugAndroidTestBuildConfig
[23:54:00]: ▸ :generateDebugAndroidTestResValues
[23:54:00]: ▸ :generateDebugAndroidTestResources
[23:54:00]: ▸ :mergeDebugAndroidTestResources
[23:54:00]: ▸ :processDebugAndroidTestResources
[23:54:00]: ▸ :generateDebugAndroidTestSources
[23:54:00]: ▸ :incrementalDebugAndroidTestJavaCompilationSafeguard
[23:54:00]: ▸ :javaPreCompileDebugAndroidTest
[23:54:00]: ▸ :compileDebugAndroidTestJavaWithJavac
[23:54:00]: ▸ :compileDebugAndroidTestNdk UP-TO-DATE
[23:54:00]: ▸ :compileDebugAndroidTestSources
[23:54:00]: ▸ :mergeDebugAndroidTestShaders
[23:54:00]: ▸ :compileDebugAndroidTestShaders
[23:54:00]: ▸ :generateDebugAndroidTestAssets
[23:54:00]: ▸ :mergeDebugAndroidTestAssets
[23:54:00]: ▸ :transformClassesWithDexForDebugAndroidTest
[23:54:00]: ▸ :mergeDebugAndroidTestJniLibFolders
[23:54:00]: ▸ :transformNativeLibsWithMergeJniLibsForDebugAndroidTest
[23:54:00]: ▸ :processDebugAndroidTestJavaRes UP-TO-DATE
[23:54:00]: ▸ :transformResourcesWithMergeJavaResForDebugAndroidTest
[23:54:00]: ▸ :validateSigningDebugAndroidTest
[23:54:00]: ▸ :packageDebugAndroidTest
[23:54:00]: ▸ :assembleDebugAndroidTest
[23:54:00]: ▸ :compileDebugNdk UP-TO-DATE
[23:54:00]: ▸ :compileDebugSources
[23:54:00]: ▸ :mergeDebugShaders
[23:54:00]: ▸ :compileDebugShaders
[23:54:00]: ▸ :generateDebugAssets
[23:54:00]: ▸ :mergeDebugAssets
[23:54:01]: ▸ :transformClassesWithDexForDebug
[23:54:01]: ▸ :mergeDebugJniLibFolders
[23:54:01]: ▸ :transformNativeLibsWithMergeJniLibsForDebug
[23:54:01]: ▸ :processDebugJavaRes
[23:54:01]: ▸ :transformResourcesWithMergeJavaResForDebug
[23:54:01]: ▸ :validateSigningDebug
[23:54:01]: ▸ :packageDebug
[23:54:01]: ▸ :assembleDebug
[23:54:01]: ▸ BUILD SUCCESSFUL
[23:54:01]: ▸ Total time: 2.319 secs

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | gradle              | 2           |
+------+---------------------+-------------+

[23:54:02]: fastlane.tools finished successfully 🎉

Debug Build complete!

Emulator avd started, waiting for boot
List of devices attached

Hax is enabled
Hax ram_size 0x80000000
HAX is working and emulator runs in fast virt mode.
...waiting
...waiting
...waiting
...waiting
...waiting
Device online, initiating screengrab for device type: phone...

[23:54:27]: Successfully loaded '/Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/fastlane/Screengrabfile' 📄

+----------------------------+------------------------------------------------------------------------+
|                          Detected Values from './fastlane/Screengrabfile'                           |
+----------------------------+------------------------------------------------------------------------+
| android_home               | /Users/tsdev/Library/Android/sdk                                       |
| use_tests_in_classes       | ["androidTest.java.AndroidHTMLWrapperTest"]                            |
| tests_package_name         | com.talespring.wrapper.mydaddy.test                                    |
| app_apk_path               | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1  |
|                            | .30-ANDROID/build/outputs/apk/mydaddy-debug.apk                        |
| tests_apk_path             | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1  |
|                            | .30-ANDROID/build/outputs/apk/mydaddy-debug-androidTest.apk            |
| locales                    | ["en-US"]                                                              |
| clear_previous_screenshots | true                                                                   |
+----------------------------+------------------------------------------------------------------------+

+-----------------------------+------------------------------------------------------------------------+
|                                    Summary for screengrab 2.41.0                                     |
+-----------------------------+------------------------------------------------------------------------+
| device_type                 | phone                                                                  |
| app_package_name            | com.talespring.mydaddy                                                 |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner                         |
| android_home                | /Users/tsdev/Library/Android/sdk                                       |
| use_tests_in_classes        | ["androidTest.java.AndroidHTMLWrapperTest"]                            |
| tests_package_name          | com.talespring.wrapper.mydaddy.test                                    |
| app_apk_path                | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1  |
|                             | .30-ANDROID/build/outputs/apk/mydaddy-debug.apk                        |
| tests_apk_path              | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1  |
|                             | .30-ANDROID/build/outputs/apk/mydaddy-debug-androidTest.apk            |
| locales                     | ["en-US"]                                                              |
| clear_previous_screenshots  | true                                                                   |
| output_directory            | fastlane/metadata/android                                              |
| skip_open_summary           | false                                                                  |
| ending_locale               | en-US                                                                  |
| exit_on_test_failure        | true                                                                   |
| reinstall_app               | false                                                                  |
+-----------------------------+------------------------------------------------------------------------+

[23:54:27]: Clearing phoneScreenshots within fastlane/metadata/android
[23:54:27]: $ adb devices -l
[23:54:27]: ▸ List of devices attached
[23:54:27]: ▸ emulator-5554          device product:sdk_google_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64
[23:54:27]: $ adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[23:54:27]: ▸ /sdcard
[23:54:27]: Cleaning screenshots on device
[23:54:27]: Validating app APK
[23:54:27]: $ /Users/tsdev/Library/Android/sdk/build-tools/26.0.0/aapt dump permissions /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-debug.apk
[23:54:27]: ▸ package: com.talespring.mydaddy
[23:54:27]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[23:54:27]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[23:54:27]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[23:54:27]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[23:54:27]: ▸ uses-permission: name='android.permission.INTERNET'
[23:54:27]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[23:54:27]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[23:54:27]: Installing app APK
[23:54:27]: $ adb -s emulator-5554 install -r /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-debug.apk
[23:54:28]: ▸ /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-debug.apk: 1 file pushed. 37.3 MB/s (20872357 bytes in 0.533s)
[23:54:28]: ▸ pkg: /data/local/tmp/mydaddy-debug.apk
[23:54:30]: ▸ Success
[23:54:30]: Installing tests APK
[23:54:30]: $ adb -s emulator-5554 install -r /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-debug-androidTest.apk
[23:54:30]: ▸ /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-debug-androidTest.apk: 1 file pushed. 2.0 MB/s (3747 bytes in 0.002s)
[23:54:31]: ▸ pkg: /data/local/tmp/mydaddy-debug-androidTest.apk
[23:54:31]: ▸ Success
[23:54:31]: Granting the permission necessary to change locales on the device
[23:54:31]: $ adb -s emulator-5554 shell pm grant com.talespring.mydaddy android.permission.CHANGE_CONFIGURATION
[23:54:31]: $ adb -s emulator-5554 shell getprop ro.build.version.sdk
[23:54:31]: ▸ 23
[23:54:31]: Granting the permissions necessary to access device external storage
[23:54:31]: $ adb -s emulator-5554 shell pm grant com.talespring.mydaddy android.permission.WRITE_EXTERNAL_STORAGE
[23:54:32]: $ adb -s emulator-5554 shell pm grant com.talespring.mydaddy android.permission.READ_EXTERNAL_STORAGE
[23:54:32]: Running tests for locale: en-US
[23:54:32]: $ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
-e class androidTest.java.AndroidHTMLWrapperTest \
com.talespring.wrapper.mydaddy.test/android.support.test.runner.AndroidJUnitRunner
[23:54:32]: ▸ INSTRUMENTATION_STATUS: id=ActivityManagerService
[23:54:32]: ▸ INSTRUMENTATION_STATUS: Error=Unable to find instrumentation target package: com.talespring.mydaddy.android
[23:54:32]: ▸ INSTRUMENTATION_STATUS_CODE: -1
[23:54:32]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.talespring.wrapper.mydaddy.test/android.support.test.runner.AndroidJUnitRunner
[23:54:32]: ▸ at com.android.commands.am.Am.runInstrument(Am.java:1093)
[23:54:32]: ▸ at com.android.commands.am.Am.onRun(Am.java:371)
[23:54:32]: ▸ at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
[23:54:32]: ▸ at com.android.commands.am.Am.main(Am.java:100)
[23:54:32]: ▸ at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[23:54:32]: ▸ at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
[23:54:32]: Pulling captured screenshots from the device
[23:54:32]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

[!] No screenshots were detected 📷❌
pimac:TS_Scripts tsdev$ coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.41.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| json                      | 2.0.2        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-06-28**
</details>

**Comment by dpettit** [comment]
Figured it out.  I'm not sure why, but I was seeing references to "wrapper", as in "com.talespring.wrapper.mydaddy.test", as the test file.  I changed that to "com.talespring.mydaddy.test" and it works fine now.

It was working fine before, but perhaps something was fixed recently, and after I made that change, and updated fastlane, it now works!

Sorry to bother you!!!  I will close the issue now!

**Comment by dpettit** [comment]
You guys rock!
