### ISSUE TITLE
Screengrab fails on >= API Level 24

### ISSUE THREAD

**Issue by dpettit** [fastlane/fastlane#9676]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Fastlane Screengrab works flawlessly now with API <= 23.  However, if I use an emulator >= API Level 24, the script exits with "/sdcard Cleaning screenshots on device with exit status 1." 

The android test script that controls screengrabs fails at that point.

As far as how everything looks when the test is being run, I see the emulator open and execute the first page, and then fail around the time the first screengrab executes.

Any ideas on what might be cause this, or how to fix it?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

################################################################################
Starting BT-A-3 script execution...
################################################################################
Current Tap delay setting: 2 seconds, but this does not yet work for Android.

Number of pages that need screengrabs: 14
Generating Android Instrumentation Test code for taking screengrabs...

Processing page number: 1
Processing page number: 2
Processing page number: 3
Processing page number: 4
Processing page number: 5
Processing page number: 6
Processing page number: 7
Processing page number: 8
Processing page number: 9
Processing page number: 10
Processing page number: 11
Processing page number: 12
Processing page number: 13
Processing page number: 14

Android tests were created for 14 pages.

End BT-A-3 script execution; returning control to main script.
*************************************************************
Alias name (shortname) = mydaddy

Keystore directory = /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/Resources/fastlane-android/keys

Find-Alias found the following: mydaddy, Jul 4, 2017, PrivateKeyEntry, 
Certificate fingerprint (SHA1): CB:E3:11:CD:5A:FC:E1:69:EF:35:36:7E:64:3E:03:1E:D2:87:C3:8F

Alias found, no need to create a new one.

*************************************************************
Begin BT-A-4 script execution...
*************************************************************
Android_TV_-1080p-API_24
Phone_-_Nexus_4_-_API_19
Phone_-_Nexus_4_-_API_22
Phone_-_Nexus_4_-_API_23
Phone_-_Nexus_4_-_API_25
Phone_-_Nexus_5X_-_API_22
Phone_-_Nexus_5_-_API_19
Phone_-_Nexus_5_-_API_22
Phone_-_Nexus_5_-_API_24
Phone_-_Nexus_5_-_API_26
Phone_-_Nexus_6P_-_API_22
Phone_-_Nexus_6P_-_API_23
Phone_-_Nexus_6_-_API_19
Phone_-_Nexus_6_-_API_22
Phone_-_Nexus_6_-_API_23
Phone_-_Nexus_S_-_API_19
Phone_-_Nexus_S_-_API_22
Phone_-_Nexus_S_-_API_23
Tablet_-_Nexus_10_-_API_19
Tablet_-_Nexus_10_-_API_22
Tablet_-_Nexus_10_-_API_23
Tablet_-_Nexus_7_-_API_19
Tablet_-_Nexus_7_-_API_22
Tablet_-_Nexus_7_-_API_23
Tablet_-_Nexus_7_2012_-_API_19
Tablet_-_Nexus_7_2012_-_API_22
Tablet_-_Nexus_7_2012_-_API_23
Tablet_-_Nexus_7_2012_-_API_23_-_2
Tablet_-_Nexus_9_-_API_19
Tablet_-_Nexus_9_-_API_22
Tablet_-_Nexus_9_-_API_23
Tablet_-_WSVGA_7_-_API_19
Tablet_-_WSVGA_7_-_API_22
Tablet_-_WSVGA_7_-_API_23
Tablet_-_WXGA_10_1_-_API_19
Tablet_-_WXGA_10_1_-_API_22
Tablet_-_WXGA_10_1_-_API_23

No open emulators found!

Build DebugAndroidTest and Debug using Gradle...

error: no emulator detected
[15:58:39]: -------------------------------------------------
[15:58:39]: --- Step: Verifying required fastlane version ---
[15:58:39]: -------------------------------------------------
[15:58:39]: Your fastlane version 2.44.1 matches the minimum requirement of 1.104.0  ✅
[15:58:39]: ------------------------------
[15:58:39]: --- Step: default_platform ---
[15:58:39]: ------------------------------
[15:58:39]: Driving the lane 'android buildDebug' 🚀
[15:58:39]: --------------------
[15:58:39]: --- Step: gradle ---
[15:58:39]: --------------------
[15:58:39]: $ /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/gradlew clean assembleDebugAndroidTest assembleDebug -p .
[15:58:40]: ▸ Parallel execution is an incubating feature.
[15:58:40]: ▸ NDK is missing a "platforms" directory.
[15:58:40]: ▸ If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/tsdev/Library/Android/sdk/ndk-bundle.
[15:58:40]: ▸ If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
[15:58:40]: ▸ Incremental java compilation is an incubating feature.
[15:58:40]: ▸ :clean
[15:58:40]: ▸ :preBuild UP-TO-DATE
[15:58:40]: ▸ :preDebugBuild UP-TO-DATE
[15:58:40]: ▸ :checkDebugManifest
[15:58:40]: ▸ :preReleaseBuild UP-TO-DATE
[15:58:40]: ▸ :prepareComAndroidSupportTestEspressoEspressoCore221Library
[15:58:40]: ▸ :prepareComAndroidSupportTestEspressoEspressoIdlingResource221Library
[15:58:40]: ▸ :preDebugAndroidTestBuild UP-TO-DATE
[15:58:40]: ▸ :prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
[15:58:40]: ▸ :prepareComAndroidSupportTestRules05Library
[15:58:40]: ▸ :prepareComAndroidSupportTestRunner05Library
[15:58:40]: ▸ :prepareComAndroidSupportTestUiautomatorUiautomatorV18212Library
[15:58:40]: ▸ :prepareToolsFastlaneScreengrab055Library
[15:58:40]: ▸ :prepareDebugDependencies
[15:58:40]: ▸ :compileDebugAidl
[15:58:40]: ▸ :compileDebugRenderscript
[15:58:40]: ▸ :generateDebugBuildConfig
[15:58:40]: ▸ :generateDebugResValues
[15:58:40]: ▸ :generateDebugResources
[15:58:40]: ▸ :mergeDebugResources
[15:58:40]: ▸ :processDebugManifest
[15:58:40]: ▸ :processDebugResources
[15:58:40]: ▸ :generateDebugSources
[15:58:40]: ▸ :incrementalDebugJavaCompilationSafeguard
[15:58:40]: ▸ :javaPreCompileDebug
[15:58:40]: ▸ :compileDebugJavaWithJavac
[15:58:40]: ▸ :compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
[15:58:40]: ▸ Note: /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/src/com/talespring/wrapper/AndroidHTMLWrapper.java uses or overrides a deprecated API.
[15:58:40]: ▸ Note: Recompile with -Xlint:deprecation for details.
[15:58:40]: ▸ :prepareDebugAndroidTestDependencies
[15:58:40]: ▸ :compileDebugAndroidTestAidl
[15:58:40]: ▸ :processDebugAndroidTestManifest
[15:58:40]: ▸ :compileDebugAndroidTestRenderscript
[15:58:40]: ▸ :generateDebugAndroidTestBuildConfig
[15:58:40]: ▸ :generateDebugAndroidTestResValues
[15:58:40]: ▸ :generateDebugAndroidTestResources
[15:58:40]: ▸ :mergeDebugAndroidTestResources
[15:58:40]: ▸ :processDebugAndroidTestResources
[15:58:40]: ▸ :generateDebugAndroidTestSources
[15:58:40]: ▸ :incrementalDebugAndroidTestJavaCompilationSafeguard
[15:58:40]: ▸ :javaPreCompileDebugAndroidTest
[15:58:40]: ▸ :compileDebugAndroidTestJavaWithJavac
[15:58:40]: ▸ :compileDebugAndroidTestNdk UP-TO-DATE
[15:58:40]: ▸ :compileDebugAndroidTestSources
[15:58:40]: ▸ :mergeDebugAndroidTestShaders
[15:58:40]: ▸ :compileDebugAndroidTestShaders
[15:58:40]: ▸ :generateDebugAndroidTestAssets
[15:58:40]: ▸ :mergeDebugAndroidTestAssets
[15:58:40]: ▸ :transformClassesWithDexForDebugAndroidTest
[15:58:40]: ▸ :mergeDebugAndroidTestJniLibFolders
[15:58:40]: ▸ :transformNativeLibsWithMergeJniLibsForDebugAndroidTest
[15:58:40]: ▸ :processDebugAndroidTestJavaRes UP-TO-DATE
[15:58:40]: ▸ :transformResourcesWithMergeJavaResForDebugAndroidTest
[15:58:40]: ▸ :validateSigningDebugAndroidTest
[15:58:40]: ▸ :packageDebugAndroidTest
[15:58:40]: ▸ :assembleDebugAndroidTest
[15:58:40]: ▸ :compileDebugNdk UP-TO-DATE
[15:58:40]: ▸ :compileDebugSources
[15:58:40]: ▸ :mergeDebugShaders
[15:58:40]: ▸ :compileDebugShaders
[15:58:40]: ▸ :generateDebugAssets
[15:58:41]: ▸ :mergeDebugAssets
[15:58:41]: ▸ :transformClassesWithDexForDebug
[15:58:41]: ▸ :mergeDebugJniLibFolders
[15:58:41]: ▸ :transformNativeLibsWithMergeJniLibsForDebug
[15:58:41]: ▸ :processDebugJavaRes
[15:58:41]: ▸ :transformResourcesWithMergeJavaResForDebug
[15:58:41]: ▸ :validateSigningDebug
[15:58:41]: ▸ :packageDebug
[15:58:41]: ▸ :assembleDebug
[15:58:41]: ▸ BUILD SUCCESSFUL
[15:58:41]: ▸ Total time: 2.485 secs

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 3    | gradle                       | 2           |
+------+------------------------------+-------------+

[15:58:42]: fastlane.tools finished successfully 🎉

Debug Build complete!

Emulator avd started, waiting for boot
List of devices attached

Warning: requested RAM 3072M too high for your system. Reducing to maximum supported size 2048M
Hax is enabled
Hax ram_size 0x80000000
HAX is working and emulator runs in fast virt mode.
...waiting
...waiting
...waiting
...waiting
Device online, initiating screengrab for device type: phone...

[15:59:07]: Successfully loaded '/Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/fastlane/Screengrabfile' 📄

+----------------------------+-----------------------------------------------+
|              Detected Values from './fastlane/Screengrabfile'              |
+----------------------------+-----------------------------------------------+
| android_home               | /Users/tsdev/Library/Android/sdk              |
| use_tests_in_classes       | ["androidTest.java.AndroidHTMLWrapperTest"]   |
| tests_package_name         | com.talespring.mydaddy.test                   |
| app_apk_path               | /Users/tsdev/Documents/TaleSpring/RandD/TS-A  |
|                            | uto-Publish/wip/MyDaddy-1.30-ANDROID/build/o  |
|                            | utputs/apk/mydaddy-debug.apk                  |
| tests_apk_path             | /Users/tsdev/Documents/TaleSpring/RandD/TS-A  |
|                            | uto-Publish/wip/MyDaddy-1.30-ANDROID/build/o  |
|                            | utputs/apk/mydaddy-debug-androidTest.apk      |
| locales                    | ["en-US"]                                     |
| clear_previous_screenshots | true                                          |
+----------------------------+-----------------------------------------------+

+-----------------------------+-----------------------------------------------+
|                        Summary for screengrab 2.44.1                        |
+-----------------------------+-----------------------------------------------+
| device_type                 | phone                                         |
| app_package_name            | com.talespring.mydaddy                        |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunn  |
|                             | er                                            |
| android_home                | /Users/tsdev/Library/Android/sdk              |
| use_tests_in_classes        | ["androidTest.java.AndroidHTMLWrapperTest"]   |
| tests_package_name          | com.talespring.mydaddy.test                   |
| app_apk_path                | /Users/tsdev/Documents/TaleSpring/RandD/TS-A  |
|                             | uto-Publish/wip/MyDaddy-1.30-ANDROID/build/o  |
|                             | utputs/apk/mydaddy-debug.apk                  |
| tests_apk_path              | /Users/tsdev/Documents/TaleSpring/RandD/TS-A  |
|                             | uto-Publish/wip/MyDaddy-1.30-ANDROID/build/o  |
|                             | utputs/apk/mydaddy-debug-androidTest.apk      |
| locales                     | ["en-US"]                                     |
| clear_previous_screenshots  | true                                          |
| output_directory            | fastlane/metadata/android                     |
| skip_open_summary           | false                                         |
| ending_locale               | en-US                                         |
| exit_on_test_failure        | true                                          |
| reinstall_app               | false                                         |
+-----------------------------+-----------------------------------------------+

[15:59:07]: Clearing phoneScreenshots within fastlane/metadata/android
[15:59:07]: $ adb devices -l
[15:59:07]: ▸ List of devices attached
[15:59:07]: ▸ emulator-5554          device product:sdk_google_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64
[15:59:07]: $ adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[15:59:07]: ▸ /sdcard
[15:59:07]: Cleaning screenshots on device
ls: /sdcard/com.talespring.mydaddy/screengrab: No such file or directory
[15:59:07]: Exit status: 1
ls: /data/data/com.talespring.mydaddy/app_screengrab: Permission denied
[15:59:07]: Exit status: 1
[15:59:07]: Validating app APK
[15:59:07]: $ /Users/tsdev/Library/Android/sdk/build-tools/26.0.0/aapt dump permissions /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-debug.apk
[15:59:07]: ▸ package: com.talespring.mydaddy
[15:59:07]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[15:59:07]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[15:59:07]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[15:59:07]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[15:59:07]: ▸ uses-permission: name='android.permission.INTERNET'
[15:59:07]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[15:59:07]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[15:59:07]: Installing app APK
[15:59:07]: $ adb -s emulator-5554 install -r /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-debug.apk
[15:59:11]: ▸ Success
[15:59:11]: Installing tests APK
[15:59:11]: $ adb -s emulator-5554 install -r /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/wip/MyDaddy-1.30-ANDROID/build/outputs/apk/mydaddy-debug-androidTest.apk
[15:59:12]: ▸ Success
[15:59:12]: Granting the permission necessary to change locales on the device
[15:59:12]: $ adb -s emulator-5554 shell pm grant com.talespring.mydaddy android.permission.CHANGE_CONFIGURATION
[15:59:12]: $ adb -s emulator-5554 shell getprop ro.build.version.sdk
[15:59:12]: ▸ 25
[15:59:12]: Granting the permissions necessary to access device external storage
[15:59:12]: $ adb -s emulator-5554 shell pm grant com.talespring.mydaddy android.permission.WRITE_EXTERNAL_STORAGE
[15:59:12]: $ adb -s emulator-5554 shell pm grant com.talespring.mydaddy android.permission.READ_EXTERNAL_STORAGE
[15:59:12]: Running tests for locale: en-US
[15:59:12]: $ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
-e class androidTest.java.AndroidHTMLWrapperTest \
com.talespring.mydaddy.test/android.support.test.runner.AndroidJUnitRunner
glTexImage2D: got err pre :( 0x502 internal 0x1908 format 0x1908 type 0x1401
glTexImage2D: got err pre :( 0x502 internal 0x1908 format 0x1908 type 0x1401
[15:59:16]: ▸ androidTest.java.AndroidHTMLWrapperTest:
[15:59:16]: ▸ Error in testSwipeNextPage(androidTest.java.AndroidHTMLWrapperTest):
[15:59:16]: ▸ java.lang.IllegalStateException: Couldn't get the activity from the view context
[15:59:16]: ▸ at tools.fastlane.screengrab.DecorViewScreenshotStrategy$ScreenshotViewAction.perform(DecorViewScreenshotStrategy.java:69)
[15:59:16]: ▸ at android.support.test.espresso.ViewInteraction$1.run(ViewInteraction.java:144)
[15:59:16]: ▸ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
[15:59:16]: ▸ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[15:59:16]: ▸ at android.os.Handler.handleCallback(Handler.java:751)
[15:59:16]: ▸ at android.os.Handler.dispatchMessage(Handler.java:95)
[15:59:16]: ▸ at android.os.Looper.loop(Looper.java:154)
[15:59:16]: ▸ at android.app.ActivityThread.main(ActivityThread.java:6119)
[15:59:16]: ▸ at java.lang.reflect.Method.invoke(Native Method)
[15:59:16]: ▸ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[15:59:16]: ▸ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[15:59:17]: ▸ .
[15:59:17]: ▸ Time: 4.147
[15:59:17]: ▸ There was 1 failure:
[15:59:17]: ▸ 1) testSwipeNextPage(androidTest.java.AndroidHTMLWrapperTest)
[15:59:17]: ▸ java.lang.IllegalStateException: Couldn't get the activity from the view context
[15:59:17]: ▸ at tools.fastlane.screengrab.DecorViewScreenshotStrategy$ScreenshotViewAction.perform(DecorViewScreenshotStrategy.java:69)
[15:59:17]: ▸ at android.support.test.espresso.ViewInteraction$1.run(ViewInteraction.java:144)
[15:59:17]: ▸ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
[15:59:17]: ▸ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[15:59:17]: ▸ at android.os.Handler.handleCallback(Handler.java:751)
[15:59:17]: ▸ at android.os.Handler.dispatchMessage(Handler.java:95)
[15:59:17]: ▸ at android.os.Looper.loop(Looper.java:154)
[15:59:17]: ▸ at android.app.ActivityThread.main(ActivityThread.java:6119)
[15:59:17]: ▸ at java.lang.reflect.Method.invoke(Native Method)
[15:59:17]: ▸ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[15:59:17]: ▸ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[15:59:17]: ▸ FAILURES!!!
[15:59:17]: ▸ Tests run: 2,  Failures: 1

[!] Tests failed for locale en-US on device emulator-5554
pimac:TS_Scripts tsdev$ coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioInputDeviceIOProc
Reason: Invalid argument
coreaudio: Could not lock voice for audioOutputDeviceIOProc
Reason: Invalid argument
pimac:TS_Scripts tsdev$ 
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2017-07-05**
</details>

**Comment by ima747** [comment]
I am just getting started with screengrab but I am seeing the same behavior. I did a lot of setup under API 22, everything works fine, but trying on 24 or 25 it fails. Trying to run the UITest directly from Android Studio gives me the following in the test log

java.lang.IllegalStateException: Couldn't get the activity from the view context
at tools.fastlane.screengrab.DecorViewScreenshotStrategy$ScreenshotViewAction.perform(DecorViewScreenshotStrategy.java:69)
at android.support.test.espresso.ViewInteraction$1.run(ViewInteraction.java:144)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ohayon** [comment]
Hey @ima747 - We just recently pushed out some updates that should fix this I believe, would you mind sharing the output of `fastlane env` so we can see a bit more context about your environment? Thank you!! 🐙 🚀

**Comment by ima747** [comment]
Appologies, have to sanitize out my fastlane files



<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G29)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.50.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-demo_mode | 1.0.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| json                      | 2.1.0        |
| excon                     | 0.58.0       |
| faraday                   | 0.12.2       |
| faraday_middleware        | 0.12.0       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| fastlane-plugin-demo_mode | 1.0.0        |
</details>


*generated on:* **2017-08-02**
</details>

**Comment by ima747** [comment]
Don't know if it's related, but I noticed that screenshots are also not capturing the device software buttons (just a black bar) or the status bar contents (just see the bar empty in screenshots) on API 23. I haven't gone back to check older ones yet.

**Comment by ima747** [comment]
After re-reading the screengrab page I added Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy()); to the start of my screenshot test which appears to have resolved the issue.
I understand there are legacy concerns around changing the default strategy, but perhaps smart switching on 24+ where the legacy method is not compatible, or considering deprecating it more aggressively as it's unlikely that a large volume of users are explicitly taking screenshots on deprecated APIs (but keeping it available because you never know...) would be appropriate.
