### ISSUE TITLE
Gym failing with "no implicit conversion of Symbol into Integer" in 2.45.0 when using sigh for profile selection

### ISSUE THREAD

**Issue by sbusch-mobivention** [fastlane/fastlane#9684]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Using the newest version i always get the same error in gym. I tried using it in different projects and the result is always the same

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `hockeymobi`
<details><summary>Output/Log</summary>

```

DEBUG [2017-07-06 13:10:23.17]: Checking if there are any plugins that should be loaded...
INFO [2017-07-06 13:10:23.32]: -------------------------------------------------
INFO [2017-07-06 13:10:23.32]: --- Step: Verifying required fastlane version ---
INFO [2017-07-06 13:10:23.32]: -------------------------------------------------
INFO [2017-07-06 13:10:23.32]: Your fastlane version 2.45.0 matches the minimum requirement of 1.99.0  ✅
INFO [2017-07-06 13:10:23.32]: ------------------------------
INFO [2017-07-06 13:10:23.32]: --- Step: default_platform ---
INFO [2017-07-06 13:10:23.32]: ------------------------------
ERROR [2017-07-06 13:10:23.32]: Name of the lane 'hockey' is already taken by the action named 'hockey'
ERROR [2017-07-06 13:10:23.32]: Name of the lane 'appstore' is already taken by the action named 'appstore'
INFO [2017-07-06 13:10:23.32]: Driving the lane 'ios hockeymobi' 🚀
INFO [2017-07-06 13:10:23.33]: -----------------------
INFO [2017-07-06 13:10:23.33]: --- Step: cocoapods ---
INFO [2017-07-06 13:10:23.33]: -----------------------
INFO [2017-07-06 13:10:23.59]: gem 'cocoapods' is already installed
INFO [2017-07-06 13:10:23.59]: $ pod install
INFO [2017-07-06 13:10:29.21]: ▸ Analyzing dependencies
INFO [2017-07-06 13:10:29.21]: ▸ Downloading dependencies
INFO [2017-07-06 13:10:29.21]: ▸ Using ActionSheetPicker-3.0 (2.2.0)
INFO [2017-07-06 13:10:29.21]: ▸ Using Alamofire (4.3.0)
INFO [2017-07-06 13:10:29.21]: ▸ Using BigInt (2.1.2)
INFO [2017-07-06 13:10:29.21]: ▸ Using CSV.swift (1.1.2)
INFO [2017-07-06 13:10:29.21]: ▸ Using CocoaLumberjack (3.0.0)
INFO [2017-07-06 13:10:29.21]: ▸ Using FRHyperLabel (1.0.3)
INFO [2017-07-06 13:10:29.21]: ▸ Using HockeySDK-Source (4.1.3)
INFO [2017-07-06 13:10:29.21]: ▸ Using IHKeyboardAvoiding (3.7)
INFO [2017-07-06 13:10:29.21]: ▸ Using NSData+MD5Digest (1.0.0)
INFO [2017-07-06 13:10:29.21]: ▸ Using ReachabilitySwift (3)
INFO [2017-07-06 13:10:29.21]: ▸ Using SBImage (2.0.1)
INFO [2017-07-06 13:10:29.21]: ▸ Using SVProgressHUD (2.1.2)
INFO [2017-07-06 13:10:29.21]: ▸ Using SWXMLHash (3.0.4)
INFO [2017-07-06 13:10:29.21]: ▸ Using SipHash (1.1.1)
INFO [2017-07-06 13:10:29.21]: ▸ Using SnapKit (3.1.2)
INFO [2017-07-06 13:10:29.21]: ▸ Using SwiftDate (4.0.13)
INFO [2017-07-06 13:10:29.21]: ▸ Using ZXingObjC (3.2.1)
INFO [2017-07-06 13:10:29.21]: ▸ Generating Pods project
INFO [2017-07-06 13:10:29.21]: ▸ Integrating client project
INFO [2017-07-06 13:10:30.06]: ▸ Sending stats
INFO [2017-07-06 13:10:30.49]: ▸ Pod installation complete! There are 16 dependencies from the Podfile and 17 total pods installed.
INFO [2017-07-06 13:10:30.49]: ▸ [!] Automatically assigning platform ios with version 9.0 on target LottoBayern because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
INFO [2017-07-06 13:10:30.49]: ▸ [!] Automatically assigning platform ios with version 9.0 on target LottoBayern2 because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
INFO [2017-07-06 13:10:30.49]: ▸ [!] Automatically assigning platform ios with version 9.0 on target LottoBayern Test because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
INFO [2017-07-06 13:10:30.49]: ▸ [!] The `LottoBayern [Debug]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-LottoBayern/Pods-LottoBayern.debug.xcconfig'. This can lead to problems with the CocoaPods installation
INFO [2017-07-06 13:10:30.49]: ▸ [!] The `LottoBayern [Release]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-LottoBayern/Pods-LottoBayern.release.xcconfig'. This can lead to problems with the CocoaPods installation
INFO [2017-07-06 13:10:30.49]: ▸ [!] The `LottoBayern2 [Debug]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-LottoBayern2/Pods-LottoBayern2.debug.xcconfig'. This can lead to problems with the CocoaPods installation
INFO [2017-07-06 13:10:30.49]: ▸ [!] The `LottoBayern2 [Release]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-LottoBayern2/Pods-LottoBayern2.release.xcconfig'. This can lead to problems with the CocoaPods installation
INFO [2017-07-06 13:10:30.49]: ▸ [!] The `LottoBayern Test [Debug]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-LottoBayern Test/Pods-LottoBayern Test.debug.xcconfig'. This can lead to problems with the CocoaPods installation
INFO [2017-07-06 13:10:30.49]: ▸ [!] The `LottoBayern Test [Release]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-LottoBayern Test/Pods-LottoBayern Test.release.xcconfig'. This can lead to problems with the CocoaPods installation
INFO [2017-07-06 13:10:30.51]: ▸ - Use the `$(inherited)` flag, or
INFO [2017-07-06 13:10:30.51]: ▸ - Remove the build settings from the target.
INFO [2017-07-06 13:10:30.51]: ▸ - Use the `$(inherited)` flag, or
INFO [2017-07-06 13:10:30.51]: ▸ - Remove the build settings from the target.
INFO [2017-07-06 13:10:30.51]: ▸ - Use the `$(inherited)` flag, or
INFO [2017-07-06 13:10:30.51]: ▸ - Remove the build settings from the target.
INFO [2017-07-06 13:10:30.51]: ▸ - Use the `$(inherited)` flag, or
INFO [2017-07-06 13:10:30.51]: ▸ - Remove the build settings from the target.
INFO [2017-07-06 13:10:30.51]: ▸ - Use the `$(inherited)` flag, or
INFO [2017-07-06 13:10:30.51]: ▸ - Remove the build settings from the target.
INFO [2017-07-06 13:10:30.51]: ▸ - Use the `$(inherited)` flag, or
INFO [2017-07-06 13:10:30.51]: ▸ - Remove the build settings from the target.
INFO [2017-07-06 13:10:30.55]: ------------------
INFO [2017-07-06 13:10:30.55]: --- Step: sigh ---
INFO [2017-07-06 13:10:30.55]: ------------------
Successfully loaded Appfile at path '/Users/sbusch/Documents/Projects/LottoBayern/fastlane/Appfile'
- app_identifier: 'com.xxxxx.LottoBayern'
- apple_id: 'hweid@xxxx.com'
- team_id: 'YUGBE78GPQ'
- itc_team_name: 'xxxxx'
-------

+-------------------------------------+-----------------------------+
|                      Summary for sigh 2.45.0                      |
+-------------------------------------+-----------------------------+
| provisioning_name                   | Lotto Bayern Ad Hoc         |
| cert_id                             | 7PX2BU9WCU                  |
| adhoc                               | true                        |
| development                         | false                       |
| skip_install                        | false                       |
| force                               | false                       |
| app_identifier                      | com.xxxxx.LottoBayern |
| username                            | hweid@xxxxx.com       |
| team_id                             | YUGBE78GPQ                  |
| ignore_profiles_with_different_name | false                       |
| skip_fetch_profiles                 | false                       |
| skip_certificate_verification       | false                       |
| platform                            | ios                         |
+-------------------------------------+-----------------------------+

INFO [2017-07-06 13:10:30.60]: Starting login with user 'hweid@xxxxx.com'
INFO [2017-07-06 13:10:33.49]: Successfully logged in
INFO [2017-07-06 13:10:33.49]: Fetching profiles...
INFO [2017-07-06 13:10:36.78]: Verifying certificates...
INFO [2017-07-06 13:10:37.64]: $ security list-keychains -d user
INFO [2017-07-06 13:10:37.77]: ▸     "/Users/sbusch/Library/Keychains/login.keychain-db"
INFO [2017-07-06 13:10:37.77]: ▸     "/Users/sbusch/Library/Application Support/Adobe/AIR/ELS/Simfy/PrivateEncryptedDatak"
INFO [2017-07-06 13:10:37.77]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/sbusch/Library/Keychains/login.keychain-db
INFO [2017-07-06 13:10:37.85]: ▸ keychain: "/Users/sbusch/Library/Keychains/login.keychain-db"
INFO [2017-07-06 13:10:37.85]: ▸ version: 512
INFO [2017-07-06 13:10:37.85]: ▸ class: 0x80001000 
INFO [2017-07-06 13:10:37.85]: ▸ attributes:
INFO [2017-07-06 13:10:37.85]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-07-06 13:10:37.85]: ▸     "cenc"<uint32>=0x00000003 
INFO [2017-07-06 13:10:37.85]: ▸     "ctyp"<uint32>=0x00000001 
INFO [2017-07-06 13:10:37.85]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2017-07-06 13:10:37.85]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2017-07-06 13:10:37.85]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-07-06 13:10:37.85]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2017-07-06 13:10:37.85]: ▸     "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"
INFO [2017-07-06 13:10:37.85]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
INFO [2017-07-06 13:10:40.34]: Found 1 matching profile(s)
WARN [2017-07-06 13:10:40.34]: Downloading provisioning profile...
INFO [2017-07-06 13:10:41.71]: Successfully downloaded provisioning profile...
INFO [2017-07-06 13:10:41.93]: Installing provisioning profile...
/Users/sbusch/Documents/Projects/LottoBayern/AdHoc_com.xxxxx.LottoBayern.mobileprovision
INFO [2017-07-06 13:10:42.09]: Setting Provisioning Profile type to 'ad-hoc'
INFO [2017-07-06 13:10:42.10]: -----------------
INFO [2017-07-06 13:10:42.10]: --- Step: gym ---
INFO [2017-07-06 13:10:42.10]: -----------------
WARN [2017-07-06 13:10:42.59]: Lane Context:
INFO [2017-07-06 13:10:42.59]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios hockeymobi", :SIGH_PROFILE_PATH=>"/Users/sbusch/Documents/Projects/LottoBayern/AdHoc_com.xxxxxx.LottoBayern.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/sbusch/Documents/Projects/LottoBayern/AdHoc_com.xxxxx.LottoBayern.mobileprovision"], :SIGH_UDID=>"28c43cd5-fab3-4907-a1b7-920a92c2c90f", :SIGH_UUID=>"28c43cd5-fab3-4907-a1b7-920a92c2c90f", :SIGH_PROFILE_TYPE=>"ad-hoc"}
ERROR [2017-07-06 13:10:42.59]: no implicit conversion of Symbol into Integer
INFO [2017-07-06 13:10:42.59]: Successfully generated documentation at path '/Users/sbusch/Documents/Projects/LottoBayern/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | cocoapods           | 7           |
| 4    | sigh                | 11          |
| 💥   | gym                 | 0           |
+------+---------------------+-------------+

ERROR [2017-07-06 13:10:42.62]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: no implicit conversion of Symbol into Integer

URL: https://api.github.com/search/issues?q=no%20implicit%20conversion%20of%20Symbol%20into%20Integer+repo:fastlane/fastlane
➡️  Gym failing after upgrade to 2.38.1 "no implicit conversion of Symbol into Integer"
    https://github.com/fastlane/fastlane/issues/9490 [closed] 2 💬
    3 weeks ago

➡️  Error: no implicit conversion of Symbol into Integer
    https://github.com/fastlane/fastlane/issues/1051 [closed] 1 💬
    22 Sep 2016

➡️  problem parsing options array for TestFairy
    https://github.com/fastlane/fastlane/issues/9226 [closed] 4 💬
    6 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G23a)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["HIPCHAT_API_VERSION"] = "1"
    ENV["HIPCHAT_API_TOKEN"] = "xxxx"
    cocoapods(repo_update: false)

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to HockeyApp (mobi Version)"
  lane :hockeymobi do
    sigh(provisioning_name: "Lotto Bayern Ad Hoc", cert_id: "7PX2BU9WCU", adhoc: true)

    gym(scheme: "LottoBayern2", export_options:"fastlane/adhoc.plist") # Build your app - more options available
    # dsym_zip
    hockey(api_token: 'xxx', notify: "0")
    version = get_version_number()
    build = get_info_plist_value(path: 'LottoBayern/LottoBayern2-Info.plist', key: 'CFBundleVersion')
    dl = lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
    hipchat(
      message: "Neue mobivention Version #{version} (#{build}) bei HockeyApp verfügbar: <a href=\"#{dl}\">#{dl}</a>",
      message_format: "html", # or "text", defaults to "html"
      channel: "Lotto Bayern Dev",
      success: true,
      notify_room: true
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Submit a new Beta Build to HockeyApp"
  desc "This will also make sure the profile is up to date"
  lane :hockey do
    cert()
    sigh(provisioning_name: "SÄPP Ad Hoc", adhoc: true)
    gym(scheme: "LottoBayern", export_options:"fastlane/adhoc.plist") # Build your app - more options available
    # dsym_zip
    hockey(api_token: 'xxxx', notify: "0")
    version = get_version_number()
    build = get_info_plist_value(path: 'LottoBayern/LottoBayern-Info.plist', key: 'CFBundleVersion')
    dl = lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
    hipchat(
      message: "Neue Version #{version} (#{build}) bei HockeyApp verfügbar: <a href=\"#{dl}\">#{dl}</a>",
      message_format: "html", # or "text", defaults to "html"
      channel: "Lotto Bayern Dev",
      success: true,
      notify_room: true
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Submit a new Test Beta Build to HockeyApp"
  lane :hockeytest do
    cert()
    sigh(provisioning_name: "SÄPP Test Ad Hoc", adhoc: true)
    gym(scheme: "LottoBayern Test", export_options:"fastlane/adhoc.plist") # Build your app - more options available
    # dsym_zip
    hockey(api_token: 'xxxx', notify: "0")
    version = get_version_number()
    build = get_info_plist_value(path: 'LottoBayern Test-Info.plist', key: 'CFBundleVersion')
    dl = lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
    hipchat(
        message: "Neue (Test) Version #{version} (#{build}) bei HockeyApp verfügbar: <a href=\"#{dl}\">#{dl}</a>",
        message_format: "html", # or "text", defaults to "html"
        channel: "Lotto Bayern Dev",
        success: true,
        notify_room: true
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    cert()
    sigh(provisioning_name: "SÄPP AppStore", adhoc: false)
    gym(scheme: "LottoBayern", export_options:"fastlane/store.plist") # Build your app - more options available
    deliver(force: true, skip_screenshots: true, skip_metadata: true)
    # frameit
    version = get_version_number()
    build = get_info_plist_value(path: 'LottoBayern/LottoBayern-Info.plist', key: 'CFBundleVersion')
    hipchat(
      message: "Neue Version #{version} (#{build}) zu iTunes Connect hochgeladen",
      message_format: "html", # or "text", defaults to "html"
      channel: "Lotto Bayern Dev",
      success: true,
      notify_room: true
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "de.xxx.service" # The bundle identifier of your app
apple_id "technik@xxx.com" # Your Apple email address

team_id "xxx"  # Developer Portal Team ID
itc_team_name "xxxx"

for_lane :hockeytest do
    app_identifier 'de.xxx.service'
end

for_lane :hockeymobi do
  app_identifier 'com.xxxx.LottoBayern'
  apple_id "hweid@xxxx.com" # Your Apple email address

  team_id "xxxx"  # Developer Portal Team ID
  itc_team_name "xxxx"
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.45.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| bigdecimal                | 1.3.0        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2017-07-06**
</details>

**Comment by sbusch-mobivention** [comment]
Apparently capture_output copies everything but the stack trace for me, so here is that:

```
/Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/actions/gym.rb:29:in `[]': [!] no implicit conversion of Symbol into Integer (TypeError)
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/actions/gym.rb:29:in `run'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:35:in `block (2 levels) in parsing_binding'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:56:in `run!'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
        from /Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/bin/fastlane:20:in `<top (required)>'
        from /Users/sbusch/.rbenv/versions/2.4.1/bin/fastlane:22:in `load'
        from /Users/sbusch/.rbenv/versions/2.4.1/bin/fastlane:22:in `<main>'

```

**Comment by sbusch-mobivention** [comment]
Changed the title, because apparently sigh is the culprit

Current code (doesn't work):
```
  lane :hockeymobi do
    sigh(provisioning_name: "Lotto Bayern Ad Hoc", cert_id: "xxxx", adhoc: true)

    gym(scheme: "LottoBayern2", export_options:"fastlane/adhoc.plist")
```

Works:
```
  lane :hockeymobi do
    gym(scheme: "LottoBayern2", export_options:"fastlane/adhoc.plist")
```

Also doesn't work:
```
  lane :hockeymobi do
    cert()
    sigh(provisioning_name: "Lotto Bayern Ad Hoc", cert_id: "xxxx", adhoc: true)

    gym(scheme: "LottoBayern2", export_options:"fastlane/adhoc.plist")
```

**Comment by KrauseFx** [comment]
Awesome, thanks for submitting this detailed bug report, diving into this now 👍

**Comment by KrauseFx** [comment]
Ugh, I can't seem to reproduce, things work fine for me. Are you running the most recent release (`fastlane -v`)? Also, do you have anything else special about your setup? Any environment variables, or other things in your `Fastfile` or `Appfile`?

**Comment by sbusch-mobivention** [comment]
> Are you running the most recent release (fastlane -v)?
```
 ❯❯❯ fastlane -v                                                                                                                                                                                                               ⏎ 1.1features ✭ ✱
fastlane installation at path:
/Users/sbusch/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.45.0/bin/fastlane
-----------------------------
fastlane 2.45.0
```
looks good (I uninstalled and reinstalled it to be sure :))

> Also, do you have anything else special about your setup? 

Not that I know of. I have a ton of different Apple Teams in which I am logged in, but that shouldn't matter here, right?

> Any environment variables, or other things in your Fastfile or Appfile?

No, it's all up there, I just anonymized some Keys and company names

Is there any way I can get you more info? I will also try this on other machines/see if I can scrape together anything else

**Comment by sbusch-mobivention** [comment]
I did add `puts values[:export_options]` to gym.rb and I do just get:

`fastlane/adhoc.plist`

So maybe the combination of using sigh with an export options plist is the problem here?

**Comment by KrauseFx** [comment]
Where does the `fastlane/adhoc.plist` come from, and why does it only fail with _sigh_ before _gym_?

**Comment by sbusch-mobivention** [comment]
> Where does the fastlane/adhoc.plist come from

I'm not sure I understand that question correctly, It's either:
* ...the output of `puts values[:export_options]` which I put in gym.rb before line 29
* ...an export options file that I wrote according to spec:

```
<plist version="1.0">
<dict>
        <key>method</key>
        <string>ad-hoc</string>
        <key>compileBitcode</key>
        <false/>
        <key>uploadBitcode</key>
        <false/>
</dict>
</plist>
```

> why does it only fail with sigh before gym?

Because the block containing line 29 in gym.rb will not be entered, if you don't use sigh

**Comment by sbusch-mobivention** [comment]
I created a minimal project for reproduction: 
http://uploads.mobivention.eu/download/31b7fa9fc0a29add7d5994d8b615d454

I removed the Appfile for security reasons, you will have to add your own one.

**Comment by KrauseFx** [comment]
Awesome, thanks. The `plist` file is what's causing the error, just pushed a fix, and will be fixed in the next release 👍

**Comment by sbusch-mobivention** [comment]
So this is basically the same fix that I tested and it does fix the issue.

But will this not cause further problems down the line, because the profiles only get added to export_options IFF export_options is a hash? If export_options is indeed a string, will the profile selected by sigh (or match as well) not be unavailable later when exporting, since it actually got never got added to export_options?

(This is propably its own issue, so I apologize if is should be listed somewhere else)

**Comment by KrauseFx** [comment]
Ahh, yeah, nice catch. Maybe we should just show a message and let the person know to have full responsibility of providing the profile? Or is that too bad?

**Comment by sbusch-mobivention** [comment]
I think that's propably fine, if supplying the options as a hash is a viable alternative. It should be, right?

**Comment by KrauseFx** [comment]
What do you mean?

**Comment by sbusch-mobivention** [comment]
I mean: If we supply export_options as a hash, the profile from match/sigh would be added to said hash and everything works as it should be, right?

In which case, I think directing the user to that line of action seems to be fine
