### ISSUE TITLE
Fastlane not working on macOS 10.13 (beta 1 or 2)

### ISSUE THREAD

**Issue by dwarfland** [fastlane/fastlane#9685]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

trying to run any fast lane tool gives something like

```
Floorshow:Weather mh [master]+ $ deliver
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'deliver' (>= 0) among 37 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/mh/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/deliver:22:in `<main>'
```

### Environment

doesn't work either, due to what seems a hardcoded rugby version?
```
$ fastlane env
-bash: /usr/local/bin/fastlane: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory
```

**Comment by KrauseFx** [comment]
Could you provide a little more details on how you installed _fastlane_? The _deliver_ gem was deprecated about 9 months ago, in favor of the _fastlane_ gem. Make sure to install use use the fastlane gem 👍

**Comment by dwarfland** [comment]
i quote:

> $ fastlane env
> -bash: /usr/local/bin/fastlane: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by dwarfland** [comment]
i dont recall how i originally installed (ages ago), but i "reinstalled" via " sudo gem install fastlane -NV", which have no errors, but the errors running `fastlane` or `deliver` persist.

**Comment by KrauseFx** [comment]
> i quote:
> > $ fastlane env
> > -bash: /usr/local/bin/fastlane: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

Nice, but that's a crash, and not how _fastlane_ was installed 😉 

Could you give the homebrew or zip based installation a try? You can find more information [here](https://docs.fastlane.tools/#choose-your-installation-method)

**Comment by dwarfland** [comment]
"but that's a crash, and not how fastlane was installed " < yes, that was in response to being domino i didn't provide the output of `fastlane env`. ;)

i'll try installing view brew.

**Comment by dwarfland** [comment]
No joy, still:

```
==> 
==> Updating installed gems
==> Updating fastlane
==> Successfully installed commander-fastlane-4.4.5
==> Successfully installed declarative-0.0.9
==> Successfully installed declarative-option-0.1.0
==> Successfully installed representable-3.0.4
==> Successfully installed google-api-client-0.12.0
==> Successfully installed fastlane-2.45.0
==> Gems updated: commander-fastlane declarative declarative-option fastlane google-api-client representable
==> Cleaning up installed gems...
==> Attempting to uninstall fastlane-2.28.3
==> Successfully uninstalled fastlane-2.28.3
==> Attempting to uninstall commander-fastlane-4.4.4
==> Successfully uninstalled commander-fastlane-4.4.4
==> Attempting to uninstall google-api-client-0.9.28
==> Successfully uninstalled google-api-client-0.9.28
==> Attempting to uninstall representable-2.3.0
==> Successfully uninstalled representable-2.3.0
==> Clean Up Complete
==> Detected shell config file at path '~/.bash_profile'
==> Please add the following line to your bash profile:
==> 
==> export PATH="$HOME/.fastlane/bin:$PATH"
==> 
==> After doing so close the terminal session and restart it to start using fastlane 🚀
==> 
🍺  fastlane was successfully installed!
Floorshow:~ mh $ fastlane
-bash: /usr/local/bin/fastlane: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory
```

note that Ruby 2.0 doesn't exist on 10.13, only 2.3:

```
Floorshow:~ mh $ ls /System/Library/Frameworks/Ruby.framework/Versions/
2.3     Current
```

**Comment by KrauseFx** [comment]
Try running `~/.fastlane/bin/fastlane env`

**Comment by dwarfland** [comment]
hmm, that one works.

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.13                                            |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.11.0 (Apple Git-81)                |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.13 (17A291m)                         |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | true                                             |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | ~/Applications/Xcode-8.3.app/Contents/Developer/ |
| Xcode Version               | 8.3                                              |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.45.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-07-10**
</details>
```

**Comment by dwarfland** [comment]
so what's the cleanest way to get the version in /user/local/bin to work again, as well? (just copying/linking the binaries into there doesn't seem to be enough)

**Comment by KrauseFx** [comment]
Adding a symlink to whatever directory is in your `$PATH` to `~/.fastlane/bin/fastlane` should do the trick

**Comment by dwarfland** [comment]
ok, thanx, i'll do that and clean out the old versions in /bin then.

**Comment by dwarfland** [comment]
oh, wait, misread. no just adding a symlink TO fastlane did not do the trick, thats the first thing i tried before i even asked.

```
Floorshow:~ mh $ fastlane
/usr/local/bin/fastlane: line 13: /usr/local/bin/bundle/bin/bundle-env: Not a directory
/usr/local/bin/fastlane: line 13: exec: /usr/local/bin/bundle/bin/bundle-env: cannot execute: Not a directory
Floorshow:~ mh $ deliver
/usr/local/bin/deliver: line 3: /usr/local/bin/bundle/bin/bundle-env: Not a directory
/usr/local/bin/deliver: line 3: exec: /usr/local/bin/bundle/bin/bundle-env: cannot execute: Not a directory
Floorshow:~ mh $ 
```

and i'd rather not pollute my path with adding ~/.fastlane/bin/ to it...

**Comment by KrauseFx** [comment]
That's weird... sorry, I can't help. Setting up the path depends on your system configuration and works for most other users. Just make sure as a result you're calling `~/.fastlane/bin/fastlane`. Alternatively, you can start [using a Gemfile](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile), which is something we recommend 👍

**Comment by dwarfland** [comment]
k, thanx.
