### ISSUE TITLE
Pilot reported "invalid byte sequence in US-ASCII" after token expiration

### ISSUE THREAD

**Issue by PawelWesolowski** [fastlane/fastlane#9689]
### New Issue Checklist

- [yes] Updated fastlane to the latest version
- [yes] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
First I have tried export LANG=en_US.UTF-8 as described in [this issue](https://github.com/fastlane/fastlane/issues/227). But then I realised that my token for 2FA has probably expired. Updated the token and the problem was gone.
I hope it is be helpful for others who experience this ;)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[18:15:23]	[Step 3/4] /Users/sss/.rvm/gems/ruby-2.3.0@global/gems/highline-1.7.8/lib/highline.rb:730:in `gsub': [!] invalid byte sequence in US-ASCII (ArgumentError)
[18:15:23]	[Step 3/4] from /Users/sss/.rvm/gems/ruby-2.3.0@global/gems/highline-1.7.8/lib/highline.rb:730:in `format_statement'
[18:15:23]	[Step 3/4] from /Users/sss/.rvm/gems/ruby-2.3.0@global/gems/highline-1.7.8/lib/highline.rb:621:in `say'
[18:15:23]	[Step 3/4] from /Users/sss/.rvm/gems/ruby-2.3.0@global/gems/highline-1.7.8/lib/highline.rb:261:in `ask'
[18:15:23]	[Step 3/4] from /Users/sss/.rvm/gems/ruby-2.3.0@global/gems/highline-1.7.8/lib/highline.rb:365:in `choose'
[18:15:23]	[Step 3/4] from /Users/sss/.rvm/gems/ruby-2.3.0/gems/fastlane-2.45.0/spaceship/lib/spaceship/two_step_client.rb:35:in `handle_two_step'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

/Users/sss/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:60:in `getwd': No such file or directory - getcwd (Errno::ENOENT)
	from /Users/sss/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:60:in `pwd'

**Comment by KrauseFx** [comment]
Uh, I don't know where this error comes from, seems like it's related to your terminal / mac setup. Could you try running the same on another Mac and see if that works?

**Comment by kalafun** [comment]
Any updates? I just ran into the same issue using fastlane testflight on Teamcity Mac Pro Server. Works on my mac though.

**Comment by kalafun** [comment]
Just fixed it with:
https://github.com/fastlane/fastlane/issues/227
take a look at the response from phatblat

**Comment by ohayon** [comment]
Glad you got that fixed and thanks for pointing to your solution @kalafun !! 🚀

**Comment by PawelWesolowski** [comment]
Sorry for late response. @KrauseFx  I did try and it was working fine on my Mac. Just like it was for @kalafun - this problem was only on my TeamCity Mac build agent.
