### ISSUE TITLE
update_fastlane not working

### ISSUE THREAD

**Issue by revile** [fastlane/fastlane#969]
I get the following error when trying to run the update_fastlane action:
```
[17:25:08]: -----------------------------
[17:25:08]: --- Step: update_fastlane ---
[17:25:08]: -----------------------------
[17:25:08]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, pem, pilot, produce, scan, sigh, snapshot, spaceship, supply...
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
✨  Once crash reporting is enabled, you get a clean output when something goes wrong.
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/actions/update_fastlane.rb:56:in `run': undefined method `highest_installed_gems' for #<Gem::Commands::UpdateCommand:0x007fa902bd4c70> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:15:in `parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/fast_file.rb:48:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/fast_file.rb:48:in `block in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/fast_file.rb:37:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/fast_file.rb:37:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/fast_file.rb:27:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/lane_manager.rb:12:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/bin/fastlane:152:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/bin/fastlane:158:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by Gladkov-Art** [comment]
I've got another problem, related to ```update_fastlane```. Spaceship updates on every ```update_fastlane``` run 
```
[19:16:49]: -----------------------------
[19:16:49]: --- Step: update_fastlane ---
[19:16:49]: -----------------------------
[19:16:49]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, pem, pilot, produce, scan, sigh, snapshot, spaceship, supply...
[19:17:13]: Updating spaceship from 0.15.1 to 0.15.2 ...
```

**Comment by micnguyen** [comment]
Similar issue happening here at #804

**Comment by huynguyen** [comment]
It looks like you are running the default installation of ruby on OSX and not a ruby version manager like (rvm, rbenv, chruby). 

You probably need to update rubygems itself as OSX ships with an old version.
`sudo gem update --system`

**Comment by KrauseFx** [comment]
@milch Could you take a quick look at this? :+1:

**Comment by jacobvanorder** [comment]
@huynguyen that worked for me. Thanks! :+1:

**Comment by vpolouchkine** [comment]
I'm going to close this Issue, but feel free to create a new one if you're still hitting this.
