### ISSUE TITLE
Fastlane crashing in sh_helper.rb

### ISSUE THREAD

**Issue by benjaminboxler** [fastlane/fastlane#988]
Crash occurs when running test targets in a certain order

```
▸ Check Dependencies
▸ Check Dependencies
▸ Building Pods/AFNetworking [Debug]
▸ Check Dependencies
▸ Building Pods/Alamofire [Debug]
▸ Check Dependencies
▸ Building Pods/BFCropInterface [Debug]
▸ Check Dependencies
▸ Building Pods/Bond [Debug]
▸ Check Dependencies
▸ Building Pods/ConfidoIOS [Debug]
▸ Check Dependencies
▸ Building Pods/Flurry-iOS-SDK-Flurry-iOS-SDK [Debug]
▸ Check Dependencies
▸ Building Pods/Flurry-iOS-SDK [Debug]
▸ Check Dependencies
▸ Building Pods/OAuthSwift [Debug]
▸ Check Dependencies
▸ Building Pods/SMPageControl [Debug]
▸ Check Dependencies
▸ Building Pods/SwiftyJSON [Debug]
▸ Check Dependencies
▸ Building Pods/Pods-Expend [Debug]
▸ Check Dependencies
▸ Building Expend/Expend [Debug]
▸ Check Dependencies
▸ Compiling BuildKey.swift
▸ Compiling AppEnvironment.swift
▸ Compiling LaunchViewController.swift
▸ Compiling DeviceKeyPair.swift
▸ Compiling EmailValidator.swift
▸ Compiling SecretStore.swift
▸ Compiling UIButton+Shadow.swift
▸ Compiling KeyValueObserver.swift
▸ Compiling _Client.swift
▸ Compiling AttachmentsCell.swift
▸ Compiling SyncEntryExpenseClaim.swift
▸ Compiling UILabel+Expend.swift
▸ Compiling _PaymentMethod.swift
▸ Compiling _UserContext.swift
▸ Compiling _Person.swift
▸ Compiling ExpendToolBar.swift
▸ Compiling ManagedObjectContext.swift
▸ Compiling SyncRecordEntry.swift
▸ Compiling Person.swift
▸ Compiling _Director.swift
▸ Compiling Array.swift
▸ Compiling FloatLabelTextField.swift
▸ Compiling PaymentSuggestion.swift
▸ Compiling NSDate.swift
▸ Compiling AttachmentsDataSource.swift
▸ Compiling SuggestionViewCell.swift
▸ Compiling SuggestionsViewController.swift
▸ Compiling ExpenseClaimEditor.swift
▸ Compiling HTTPSessionManager.swift
▸ Compiling SyncTask.swift
▸ Compiling EditExpenseViewController.swift
▸ Compiling Payment.swift
▸ Compiling CategoryCell.swift
▸ Compiling CategoryPickerController.swift
▸ Compiling Gallery.swift
▸ Compiling _OAuthProvider.swift
▸ Compiling DataSource.swift
▸ Compiling ReachabilityHandler.swift
▸ Compiling EditExpenseDateCell.swift
▸ Compiling _SyncEntryExpenseClaim.swift
▸ Compiling HTTPAPI.swift
▸ Compiling _ContactEmail.swift
▸ Compiling TestUniverseProvider.swift
▸ Compiling ContactItem.swift
▸ Compiling SeparatorCell.swift
▸ Compiling CrunchRESTProvider.swift
▸ Compiling UserContext+Operation.swift
▸ Compiling ExpendCertificates.swift
▸ Compiling SuggestionsTableView.swift
▸ Compiling _Company.swift
▸ Compiling UISegmentedControl.swift
▸ Compiling AddExpenseLineCell.swift
▸ Compiling CameraViewController.swift
▸ Compiling TaxType.swift
▸ Compiling _ExpenseCategoryGroup.swift
▸ Compiling _Currency.swift
▸ Compiling PaymentMethodPickerDataSource.swift
▸ Compiling Events.swift
▸ Compiling TaxTypePickerCell.swift
▸ Compiling Store.swift
▸ Compiling _SyncFullSync.swift
▸ Compiling _ContactItem.swift
▸ Compiling V3CrunchAccountingContextToV4CrunchAccountingContext.swift
▸ Compiling AttachmentMigrationPolicy.swift
▸ Compiling UIAlertController.swift
▸ Compiling _AccountingContext.swift
▸ Compiling CrunchProvider.swift
▸ Compiling PaymentAccount.swift
▸ Compiling Feature.swift
▸ Compiling OAuthProvider.swift
▸ Compiling ExpensesViewController.swift
▸ Compiling RegisterEmailController.swift
▸ Compiling String+Condense.swift
▸ Compiling OAuthSupport.swift
▸ Compiling Attachment.swift
▸ Compiling ExpensesViewCell.swift
▸ Compiling _TestUniverse.swift
▸ Compiling _Credential.swift
▸ Compiling _PaymentAccount.swift
▸ Compiling Party.swift
▸ Compiling Model+JSON.swift
▸ Compiling HTTPJSONOperation.swift
▸ Compiling VerticalDecelerationBehavior.swift
▸ Compiling String+Data.swift
▸ Compiling CrunchAccountingContextMigrationPolicy.swift
▸ Compiling RootPresenter.swift
▸ Compiling String+Validation.swift
▸ Compiling ContactNumber.swift
▸ Compiling HTTPJSONRequestSerializer.swift
▸ Compiling EmptyStateView.swift
▸ Compiling UserDefaultKeys.swift
▸ Compiling _BankAccount.swift
▸ Compiling SyncEntry.swift
▸ Compiling ContactEmail.swift
▸ Compiling CrunchHTTPOperation.swift
▸ Compiling UITestsStore.swift
▸ Compiling TableCellAutoReusable.swift
▸ Compiling PopupView.swift
▸ Compiling TranslucentToolbar.swift
▸ Compiling CardPageController.swift
▸ Compiling TestUniverse.swift
▸ Compiling ExpenseLineCell.swift
▸ Compiling _OAuthCredential.swift
▸ Compiling ExpenseLine.swift
▸ Compiling _Payment.swift
▸ Compiling CrunchHTTPExpenseClaim.swift
▸ Compiling _TestProvider.swift
▸ Compiling _Supplier.swift
▸ Compiling LoginWebViewController.swift
▸ Compiling CrunchHTTPGetPaymentMethods.swift
▸ Compiling EditExpenseLineCell.swift
▸ Compiling HTTPOAuthRequestSerializer.swift
▸ Compiling ExpenseClaimAttributeEditor.swift
▸ Compiling UITableView.swift
▸ Compiling ContactAddress.swift
▸ Compiling _CreditCardAccount.swift
▸ Compiling ExpensesTableView.swift
▸ Compiling Money.swift
▸ Compiling _CrunchProvider.swift
▸ Compiling SyncFullSync.swift
▸ Compiling String+JSON.swift
▸ Compiling EmptyStateTableView.swift
▸ Compiling CreditCardAccount.swift
▸ Compiling ExpenseCategory.swift
▸ Compiling Provider.swift
▸ Compiling EmailValidator.swift
▸ Compiling SecretStore.swift
▸ Compiling UIButton+Shadow.swift
▸ Compiling KeyValueObserver.swift
▸ Compiling _Client.swift
▸ Compiling AttachmentsCell.swift
▸ Compiling SyncEntryExpenseClaim.swift
▸ Compiling UILabel+Expend.swift
▸ Compiling _PaymentMethod.swift
▸ Compiling _UserContext.swift
▸ Compiling _Person.swift
▸ Compiling ExpendToolBar.swift
▸ Compiling ManagedObjectContext.swift
▸ Compiling SyncRecordEntry.swift
▸ Compiling Person.swift
▸ Compiling _Director.swift
▸ Compiling Array.swift
▸ Compiling FloatLabelTextField.swift
▸ Compiling PaymentSuggestion.swift
▸ Compiling NSDate.swift
▸ Compiling AttachmentsDataSource.swift
▸ Compiling SuggestionViewCell.swift
▸ Compiling SuggestionsViewController.swift
▸ Compiling ExpenseClaimEditor.swift
▸ Compiling HTTPSessionManager.swift
▸ Compiling SyncTask.swift
▸ Compiling EditExpenseViewController.swift
▸ Compiling Payment.swift
▸ Compiling CategoryCell.swift
▸ Compiling CategoryPickerController.swift
▸ Compiling Gallery.swift
▸ Compiling _OAuthProvider.swift
▸ Compiling DataSource.swift
▸ Compiling ReachabilityHandler.swift
▸ Compiling EditExpenseDateCell.swift
▸ Compiling _SyncEntryExpenseClaim.swift
▸ Compiling HTTPAPI.swift
▸ Compiling _ContactEmail.swift
▸ Compiling TestUniverseProvider.swift
▸ Compiling ContactItem.swift
▸ Compiling SeparatorCell.swift
▸ Compiling CrunchRESTProvider.swift
▸ Compiling UserContext+Operation.swift
▸ Compiling ExpendCertificates.swift
▸ Compiling SuggestionsTableView.swift
▸ Compiling _Company.swift
▸ Compiling UISegmentedControl.swift
▸ Compiling AddExpenseLineCell.swift
▸ Compiling CameraViewController.swift
▸ Compiling TaxType.swift
▸ Compiling _ExpenseCategoryGroup.swift
▸ Compiling _Currency.swift
▸ Compiling PaymentMethodPickerDataSource.swift
▸ Compiling Events.swift
▸ Compiling TaxTypePickerCell.swift
▸ Compiling Store.swift
▸ Compiling _SyncFullSync.swift
▸ Compiling _ContactItem.swift
▸ Compiling V3CrunchAccountingContextToV4CrunchAccountingContext.swift
▸ Compiling AttachmentMigrationPolicy.swift
▸ Compiling UIAlertController.swift
▸ Compiling _AccountingContext.swift
▸ Compiling CrunchProvider.swift
▸ Compiling PaymentAccount.swift
▸ Compiling Feature.swift
▸ Compiling OAuthProvider.swift
▸ Compiling ExpensesViewController.swift
▸ Compiling RegisterEmailController.swift
▸ Compiling String+Condense.swift
▸ Compiling OAuthSupport.swift
▸ Compiling Attachment.swift
▸ Compiling ExpensesViewCell.swift
▸ Compiling _TestUniverse.swift
▸ Compiling _Credential.swift
▸ Compiling _PaymentAccount.swift
▸ Compiling Party.swift
▸ Compiling Model+JSON.swift
▸ Compiling HTTPJSONOperation.swift
▸ Compiling VerticalDecelerationBehavior.swift
▸ Compiling String+Data.swift
▸ Compiling CrunchAccountingContextMigrationPolicy.swift
▸ Compiling RootPresenter.swift
▸ Compiling String+Validation.swift
▸ Compiling ContactNumber.swift
▸ Compiling HTTPJSONRequestSerializer.swift
▸ Compiling EmptyStateView.swift
▸ Compiling UserDefaultKeys.swift
▸ Compiling _BankAccount.swift
▸ Compiling SyncEntry.swift
▸ Compiling ContactEmail.swift
▸ Compiling CrunchHTTPOperation.swift
▸ Compiling UITestsStore.swift
▸ Compiling TableCellAutoReusable.swift
▸ Compiling PopupView.swift
▸ Compiling TranslucentToolbar.swift
▸ Compiling CardPageController.swift
▸ Compiling TestUniverse.swift
▸ Compiling ExpenseLineCell.swift
▸ Compiling _OAuthCredential.swift
▸ Compiling ExpenseLine.swift
▸ Compiling _Payment.swift
▸ Compiling CrunchHTTPExpenseClaim.swift
▸ Compiling _TestProvider.swift
▸ Compiling _Supplier.swift
▸ Compiling LoginWebViewController.swift
▸ Compiling CrunchHTTPGetPaymentMethods.swift
▸ Compiling EditExpenseLineCell.swift
▸ Compiling HTTPOAuthRequestSerializer.swift
▸ Compiling ExpenseClaimAttributeEditor.swift
▸ Compiling UITableView.swift
▸ Compiling ContactAddress.swift
▸ Compiling _CreditCardAccount.swift
▸ Compiling ExpensesTableView.swift
▸ Compiling Money.swift
▸ Compiling _CrunchProvider.swift
▸ Compiling SyncFullSync.swift
▸ Compiling String+JSON.swift
▸ Compiling EmptyStateTableView.swift
▸ Compiling CreditCardAccount.swift
▸ Compiling ExpenseCategory.swift
▸ Compiling Provider.swift
▸ Touching Expend.app
▸ Building Pods/KIF [Debug]
▸ Check Dependencies
▸ Building Pods/OHHTTPStubs [Debug]
▸ Check Dependencies
▸ Building Pods/Pods-ExpendAcceptanceTests [Debug]
▸ Check Dependencies
▸ Building Expend/ExpendAcceptanceTests [Debug]
▸ Check Dependencies
▸ Touching ExpendAcceptanceTests.xctest
▸ Building Pods/Pods-ExpendTests [Debug]
▸ Check Dependencies
▸ Building Expend/ExpendTests [Debug]
▸ Check Dependencies
▸ Touching ExpendTests.xctest
▸ Building Expend/ExpendUITests [Debug]
▸ Check Dependencies
All tests
Test Suite ExpendUITests.xctest started
EditExpenseUITests
    ✓ testCreateExpense (18.907 seconds)
    ✗ testCreateExpenseAndDeleteDraft, UI Testing Failure - No matches found for "Delete Draft" Button
    ✗ testCreateExpenseAndSaveDraft, UI Testing Failure - No matches found for "Save Draft" Button
    ✓ testEditExpenseLineAmount (12.447 seconds)
ExpenseViewControllerUITests
    ✗ testCanCopyFromTableViewCell, UI Testing Failure - Failed to scroll to visible (by AX action) Button 0x7fe310e7e0f0: traits: 8589934593, {{188.0, 27.5}, {77.0, 29.0}}, label: 'Submitted', error: Error -25204 performing AXAction 2003
    ✗ testSubmittedExpenseClaimThatIsEmptyDoesntDisplayAllCells, UI Testing Failure - Failed to scroll to visible (by AX action) Button 0x7fe310c3b9e0: traits: 8589934593, {{188.0, 27.5}, {77.0, 29.0}}, label: 'Submitted', error: Error -25204 performing AXAction 2003
OldEditExpenseUITests
    ✗ testInputFormManual, UI Testing Failure - No matches found for "Use Photo" Button
PartyPickerUITests
    ✓ testPickClientToRecharge (15.953 seconds)
    ✓ testPickSupplier (16.518 seconds)
    ✓ testPickSupplierWithDefaultCategory (12.172 seconds)
RegisterEmailUITests
** TEST FAILED **

    ✗ testRegisterEmail, XCTAssertFalse failed -
ShortcutApplicationUITests
    ✓ testNewExpenseLaunchesCamera (3.455 seconds)


ExpendUITests.EditExpenseUITests
  testCreateExpenseAndDeleteDraft, UI Testing Failure - No matches found for "Delete Draft" Button
  /Users/benjaminboxler/Documents/Xcode/Expend/expend-ios-app/ExpendUITests/EditExpenseUITests.swift:102
  ```
        app.buttons[L.Buttons.cancel].tap()
        app.buttons[L.Buttons.deleteDraft].tap()

  ```

  testCreateExpenseAndSaveDraft, UI Testing Failure - No matches found for "Save Draft" Button
  /Users/benjaminboxler/Documents/Xcode/Expend/expend-ios-app/ExpendUITests/EditExpenseUITests.swift:125
  ```
        app.buttons[L.Buttons.cancel].tap()
        app.buttons[L.Buttons.saveDraft].tap()

  ```

ExpendUITests.ExpenseViewControllerUITests
  testCanCopyFromTableViewCell, UI Testing Failure - Failed to scroll to visible (by AX action) Button 0x7fe310e7e0f0: traits: 8589934593, {{188.0, 27.5}, {77.0, 29.0}}, label: 'Submitted', error: Error -25204 performing AXAction 2003
  <unknown>:0
  ```
  ```

  testSubmittedExpenseClaimThatIsEmptyDoesntDisplayAllCells, UI Testing Failure - Failed to scroll to visible (by AX action) Button 0x7fe310c3b9e0: traits: 8589934593, {{188.0, 27.5}, {77.0, 29.0}}, label: 'Submitted', error: Error -25204 performing AXAction 2003
  <unknown>:0
  ```
  ```

ExpendUITests.OldEditExpenseUITests
  testInputFormManual, UI Testing Failure - No matches found for "Use Photo" Button
  /Users/benjaminboxler/Documents/Xcode/Expend/expend-ios-app/ExpendUITests/OldEditExpenseUITests.swift:24
  ```
        app.cells.elementBoundByIndex(0).tap()
        app.buttons[L.Buttons.usePhoto].tap()

  ```

ExpendUITests.RegisterEmailUITests
  testRegisterEmail, XCTAssertFalse failed -
  /Users/benjaminboxler/Documents/Xcode/Expend/expend-ios-app/ExpendUITests/RegisterEmailUITests.swift:21
  ```
        app.buttons[L.Buttons.cancel].tap()
        XCTAssertFalse(textField.exists)

  ```


	 Executed 12 tests, with 6 failures (0 unexpected) in 122.525 (122.569) seconds

All tests
KIF.framework
Test Suite ExpendAcceptanceTests.xctest started
A_WelcomeAcceptanceTests
    ✓ test_connectToCrunch_success (6.544 seconds)
    ✓ test_connectToCrunch_unknownError (7.086 seconds)
    ✓ test_skipAndThenLogout (9.194 seconds)
ExpenseClaimAcceptanceTests
    ✓ testCropImage (32.404 seconds)
    ✓ testDeleteImage (32.720 seconds)
    ✓ testDeleteImageFromDraft (37.106 seconds)
    ✓ testInputFormSuggestions (54.933 seconds)
    ✓ testRotateImage (30.332 seconds)
    ✓ testSwipingImageCameraSheet (45.498 seconds)
ExpensesAcceptanceTests
    ✓ test_AddNewExpenseClaim (19.058 seconds)
    ✓ test_EditFirstExpenseClaim (19.222 seconds)
    ✓ test_SwipeDeleteAfterReachingSubmitted (13.462 seconds)
    ✓ testDraftsSegmentSelectedAfterSavingAsDraft (12.521 seconds)
    ✓ testEditAndEnsureThatTheEditActuallyHappens (33.431 seconds)
FailedExpenseAcceptanceTests
    ✓ testShowErrorForFailedExpenseClaim (9.134 seconds)
RemoveExpenseTests
    ✓ testRemoveExpense (11.754 seconds)
SettingsAcceptanceTests
    ✓ testAllElementsAreVisible (10.235 seconds)
SubmittedSegmentSelectedAfterSubmittingTests
    ✓ testSubmittedSegmentSelectedAfterSubmitting (10.571 seconds)


	 Executed 18 tests, with 0 failures (0 unexpected) in 395.205 (395.241) seconds


	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/actions/xcodebuild.rb:227:in `run'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/actions/xcodebuild.rb:473:in `run'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:61:in `run_test'
	from Fastfile:56:in `block in run_tests'
	from Fastfile:55:in `each'
	from Fastfile:55:in `run_tests'
	from Fastfile:132:in `block (2 levels) in parsing_binding'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/bin/fastlane:153:in `run'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/gems/fastlane-1.47.0/bin/fastlane:159:in `<top (required)>'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/bin/fastlane:23:in `load'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/bin/fastlane:23:in `<main>'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/benjaminboxler/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by KrauseFx** [comment]
Please share the complete output, it seems like it's a build error.

**Comment by benjaminboxler** [comment]
updated description

**Comment by KrauseFx** [comment]
It seems like your tests fail:

```
EditExpenseUITests
    ✓ testCreateExpense (18.907 seconds)
    ✗ testCreateExpenseAndDeleteDraft, UI Testing Failure - No matches found for "Delete Draft" Button
    ✗ testCreateExpenseAndSaveDraft, UI Testing Failure - No matches found for "Save Draft" Button
    ✓ testEditExpenseLineAmount (12.447 seconds)
ExpenseViewControllerUITests
    ✗ testCanCopyFromTableViewCell, UI Testing Failure - Failed to scroll to visible (by AX action) Button 0x7fe310e7e0f0: traits: 8589934593, {{188.0, 27.5}, {77.0, 29.0}}, label: 'Submitted', error: Error -25204 performing AXAction 2003
    ✗ testSubmittedExpenseClaimThatIsEmptyDoesntDisplayAllCells, UI Testing Failure - Failed to scroll to visible (by AX action) Button 0x7fe310c3b9e0: traits: 8589934593, {{188.0, 27.5}, {77.0, 29.0}}, label: 'Submitted', error: Error -25204 performing AXAction 2003
OldEditExpenseUITests
    ✗ testInputFormManual, UI Testing Failure - No matches found for "Use Photo" Button
PartyPickerUITests
    ✓ testPickClientToRecharge (15.953 seconds)
    ✓ testPickSupplier (16.518 seconds)
    ✓ testPickSupplierWithDefaultCategory (12.172 seconds)
RegisterEmailUITests
** TEST FAILED **

    ✗ testRegisterEmail, XCTAssertFalse failed -
ShortcutApplicationUITests
```
