### ISSUE TITLE
Error Handler not protected from nil on line 238

### ISSUE THREAD

**Issue by casz** [fastlane/fastlane#9905]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The gym build error was expected, developer forgot to commit stuff.

But the error_handler failed properly printing the error due to `Nil`

https://github.com/fastlane/fastlane/blob/6a82b16373568b0d2cd793998dd6164503831aef/gym/lib/gym/error_handler.rb#L238

```
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/error_handler.rb:238:in `block (2 levels) in print_environment_information': [!] undefined method `downcase' for nil:NilClass (NoMethodError)
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
+------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
|                                                                             Lane Context                                                                             |
+------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                                                             |
| PLATFORM_NAME                      | ios                                                                                                                             |
| LANE_NAME                          | ios alpha                                                                                                                       |
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/jenkins/Library/Keychains/jenkins.keychain-db"                                                                        |
| BUILD_NUMBER                       | 1                                                                                                                               |
| SIGH_PROFILE_TYPE                  | ad-hoc                                                                                                                          |
| MATCH_PROVISIONING_PROFILE_MAPPING | {["com.widex.app", "com.widex.app.watchapp", "com.widex.app.watchapp.watchkitextension"]=>nil} |
+------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
[16:40:47]: undefined method `downcase' for nil:NilClass

+------+----------------------------------------+-------------+
|                      fastlane summary                       |
+------+----------------------------------------+-------------+
| Step | Action                                 | Time (in s) |
+------+----------------------------------------+-------------+
| 1    | Verifying required fastlane version    | 0           |
| 2    | xcversion                              | 0           |
| 3    | default_platform                       | 0           |
| 4    | is_ci                                  | 0           |
| 5    | Switch to ios build lane               | 0           |
| 6    | Switch to ios pods lane                | 0           |
| 7    | cocoapods                              | 2           |
| 8    | setup_jenkins                          | 0           |
| 9    | increment_build_number                 | 2           |
| 10   | Switch to ios automatic_signing🚔 lane | 0           |
| 11   | automatic_code_signing                 | 0           |
| 12   | automatic_code_signing                 | 0           |
| 13   | automatic_code_signing                 | 0           |
| 14   | automatic_code_signing                 | 0           |
| 15   | automatic_code_signing                 | 0           |
| 16   | automatic_code_signing                 | 0           |
| 17   | automatic_code_signing                 | 0           |
| 18   | match                                  | 1           |
| 💥   | gym                                    | 22          |
| 20   | Switch to ios automatic_signing🚔 lane | 0           |
| 21   | automatic_code_signing                 | 0           |
| 22   | automatic_code_signing                 | 0           |
| 23   | automatic_code_signing                 | 0           |
| 24   | automatic_code_signing                 | 0           |
| 25   | automatic_code_signing                 | 0           |
| 26   | automatic_code_signing                 | 0           |
| 27   | automatic_code_signing                 | 0           |
+------+----------------------------------------+-------------+

[16:40:47]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  DeviceManager.connected_devices fails parsing USB data
    https://github.com/fastlane/fastlane/issues/7723 [closed] 5 💬
    04 Apr 2017

➡️  fastlane 1.88.0 crash when executed without parameters
    https://github.com/fastlane/fastlane/issues/4626 [closed] 3 💬
    09 Nov 2016

➡️  Remove Shenzhen dependency
    https://github.com/fastlane/fastlane/pull/6991 [closed] 19 💬
    13 Mar 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/error_handler.rb:238:in `block (2 levels) in print_environment_information': [!] undefined method `downcase' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/error_handler.rb:237:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/error_handler.rb:237:in `block in print_environment_information'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/error_handler.rb:236:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/error_handler.rb:236:in `print_environment_information'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/error_handler.rb:57:in `handle_build_error'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/runner.rb:90:in `block in build_app'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane_core/lib/fastlane_core/command_executor.rb:88:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/runner.rb:86:in `build_app'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/runner.rb:11:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/gym/lib/gym/manager.rb:14:in `work'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/actions/gym.rb:52:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:85:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:116:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.49.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
script returned exit code 1
```

### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```


Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `length' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60length'%20for%20nil+repo:fastlane/fastlane
➡️  Actions::EnsureGitStatusCleanAction.run(nil) Crashes on Dirty Branch
    https://github.com/fastlane/fastlane/issues/9747 [open] 3 💬
    2 weeks ago

➡️  fastlane pilot find: undefined method `length' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/8885 [closed] 1 💬
    2 weeks ago

➡️  undefined method `install_gem' for #<Gem::Commands::InstallCommand
    https://github.com/fastlane/fastlane/issues/8489 [closed] 2 💬
    09 Jun 2017

and 19 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60length'%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.3                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.49.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-07-31**
</details>

**Comment by casz** [comment]
fastlane env --capture_output seems to also throw a nil on .length
https://github.com/fastlane/fastlane/blob/60bac7e4a2a6c1e19d1cd20eb83201e7d0cb9e48/fastlane_core/lib/fastlane_core/globals.rb#L19
