### ISSUE TITLE
Is there an official support of screengrab for Kotlin projects?

### ISSUE THREAD

**Issue by BennX** [fastlane/fastlane#9926]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
We have a Kotlin project and included screengrab into the build pipeline. While running screengrab we end in a failure that some classes couldn't be found. Anyways we have screenshots on the devices SD card even though that it crashed. 

As the title mentioned, is there an official support for kotlin projects? 
Are there any experiences with kotlin projects?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
 *--capture_output ends in an invalid command*

Anyways:
```
DefaultUser@SomeMachine  ~/workspace/**-project-name  screengrab ● ⍟4  fastlane screengrab --verbose                                        1 ↵  1231  17:55:39
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[09:52:10]: fastlane detected a Gemfile in the current directory
[09:52:10]: however it seems like you don't use `bundle exec`
[09:52:10]: to launch fastlane faster, please use
[09:52:10]:
[09:52:10]: $ bundle exec fastlane screengrab --verbose
[09:52:10]:
[09:52:10]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
INFO [2017-08-02 09:52:13.04]: Successfully loaded '/Users/DefaultUser/workspace/**-project-name/fastlane/Screengrabfile' 📄

+----------------------------+---------------------------------------------------------------+
|                      Detected Values from './fastlane/Screengrabfile'                      |
+----------------------------+---------------------------------------------------------------+
| app_package_name           | hidden.package.name.beta                                  |
| app_apk_path               | build/outputs/apk/**-project-name-beta-debug.apk             |
| tests_apk_path             | build/outputs/apk/**-project-name-beta-debug-androidTest.apk |
| clear_previous_screenshots | true                                                          |
+----------------------------+---------------------------------------------------------------+

+-----------------------------+---------------------------------------------------------------+
|                                Summary for screengrab 2.50.0                                |
+-----------------------------+---------------------------------------------------------------+
| app_package_name            | hidden.package.name.beta                                  |
| app_apk_path                | build/outputs/apk/**-project-name-beta-debug.apk             |
| tests_apk_path              | build/outputs/apk/**-project-name-beta-debug-androidTest.apk |
| clear_previous_screenshots  | true                                                          |
| tests_package_name          | hidden.package.name.beta.test                             |
| locales                     | ["en-US"]                                                     |
| output_directory            | fastlane/metadata/android                                     |
| skip_open_summary           | false                                                         |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner                |
| ending_locale               | en-US                                                         |
| device_type                 | phone                                                         |
| exit_on_test_failure        | true                                                          |
| reinstall_app               | false                                                         |
+-----------------------------+---------------------------------------------------------------+

WARN [2017-08-02 09:52:13.54]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
WARN [2017-08-02 09:52:13.54]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
INFO [2017-08-02 09:52:13.54]: Clearing phoneScreenshots within fastlane/metadata/android
INFO [2017-08-02 09:52:13.54]: $ adb devices -l
INFO [2017-08-02 09:52:13.55]: ▸ List of devices attached
INFO [2017-08-02 09:52:13.58]: ▸ 10160abdccc81403       device usb:342032384X product:zerofltexx model:SM_G920F device:zeroflte
INFO [2017-08-02 09:52:13.58]: $ adb -s 10160abdccc81403 shell echo \$EXTERNAL_STORAGE
INFO [2017-08-02 09:52:13.67]: ▸ /sdcard
INFO [2017-08-02 09:52:13.67]: Cleaning screenshots on device
INFO [2017-08-02 09:52:13.80]: ▸ en-DE
INFO [2017-08-02 09:52:13.80]: $ adb -s 10160abdccc81403 shell rm -rf /sdcard/hidden.package.name.beta/screengrab
INFO [2017-08-02 09:52:14.00]: ▸ ls: /data/data/hidden.package.name.beta/app_screengrab: Permission denied
ls: /data/data/hidden.package.name.beta/app_screengrab: Permission denied
ERROR [2017-08-02 09:52:14.00]: Exit status: 1
WARN [2017-08-02 09:52:14.00]: The `aapt` command could not be found on your system, so your app APK could not be validated
INFO [2017-08-02 09:52:14.00]: Installing app APK
INFO [2017-08-02 09:52:14.00]: $ adb -s 10160abdccc81403 install -r build/outputs/apk/**-project-name-beta-debug.apk
INFO [2017-08-02 09:52:21.79]: ▸ Success
INFO [2017-08-02 09:52:21.79]: Installing tests APK
INFO [2017-08-02 09:52:21.79]: $ adb -s 10160abdccc81403 install -r build/outputs/apk/**-project-name-beta-debug-androidTest.apk
INFO [2017-08-02 09:52:25.64]: ▸ Success
INFO [2017-08-02 09:52:25.64]: Granting the permission necessary to change locales on the device
INFO [2017-08-02 09:52:25.64]: $ adb -s 10160abdccc81403 shell pm grant hidden.package.name.beta android.permission.CHANGE_CONFIGURATION
INFO [2017-08-02 09:52:26.84]: $ adb -s 10160abdccc81403 shell getprop ro.build.version.sdk
INFO [2017-08-02 09:52:26.89]: ▸ 24
INFO [2017-08-02 09:52:26.90]: Granting the permissions necessary to access device external storage
INFO [2017-08-02 09:52:26.90]: $ adb -s 10160abdccc81403 shell pm grant hidden.package.name.beta android.permission.WRITE_EXTERNAL_STORAGE
INFO [2017-08-02 09:52:27.75]: $ adb -s 10160abdccc81403 shell pm grant hidden.package.name.beta android.permission.READ_EXTERNAL_STORAGE
INFO [2017-08-02 09:52:28.61]: Running tests for locale: en-US
INFO [2017-08-02 09:52:28.61]: $ adb -s 10160abdccc81403 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
hidden.package.name.beta.test/android.support.test.runner.AndroidJUnitRunner
INFO [2017-08-02 09:52:42.53]: ▸ hidden.package.name.AgentUITest:..
INFO [2017-08-02 09:53:07.26]: ▸ hidden.package.name.ContractUITest:......
INFO [2017-08-02 09:53:34.17]: ▸ hidden.package.name.LoginUITest:.......
INFO [2017-08-02 09:54:07.33]: ▸ hidden.package.name.SettingsUITest:.....
INFO [2017-08-02 09:54:15.58]: ▸ hidden.package.name.TabBarTest:.
INFO [2017-08-02 09:54:17.62]: ▸ hidden.package.name.TermsAndConditionsTest:.
INFO [2017-08-02 09:54:17.62]: ▸ Time: 105,572
INFO [2017-08-02 09:54:17.62]: ▸ There were 2 failures:
INFO [2017-08-02 09:54:17.62]: ▸ 1) org.assertj.core.internal.cglib.transform.AbstractProcessTask
INFO [2017-08-02 09:54:17.62]: ▸ java.lang.ClassNotFoundException: org.assertj.core.internal.cglib.transform.AbstractProcessTask
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.Class.classForName(Native Method)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.Class.forName(Class.java:400)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
INFO [2017-08-02 09:54:17.62]: ▸ at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1962)
INFO [2017-08-02 09:54:17.62]: ▸ Caused by: java.lang.ClassNotFoundException: org.assertj.core.internal.cglib.transform.AbstractProcessTask
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.VMClassLoader.findLoadedClass(Native Method)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
INFO [2017-08-02 09:54:17.62]: ▸ ... 9 more
INFO [2017-08-02 09:54:17.62]: ▸ Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/tools/ant/Task;
INFO [2017-08-02 09:54:17.62]: ▸ ... 9 more
INFO [2017-08-02 09:54:17.62]: ▸ Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.tools.ant.Task" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/hidden.package.name.beta.test-2/base.apk", zip file "/data/app/hidden.package.name.beta-1/base.apk"],nativeLibraryDirectories=[/data/app/hidden.package.name.beta.test-2/lib/arm64, /data/app/hidden.package.name.beta-1/lib/arm64, /system/lib64, /vendor/lib64]]
INFO [2017-08-02 09:54:17.62]: ▸ at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
INFO [2017-08-02 09:54:17.62]: ▸ ... 9 more
INFO [2017-08-02 09:54:17.62]: ▸ 2) org.assertj.core.internal.cglib.transform.AbstractTransformTask
INFO [2017-08-02 09:54:17.62]: ▸ java.lang.ClassNotFoundException: org.assertj.core.internal.cglib.transform.AbstractTransformTask
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.Class.classForName(Native Method)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.Class.forName(Class.java:400)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
INFO [2017-08-02 09:54:17.62]: ▸ at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
INFO [2017-08-02 09:54:17.62]: ▸ at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1962)
INFO [2017-08-02 09:54:17.62]: ▸ Caused by: java.lang.ClassNotFoundException: org.assertj.core.internal.cglib.transform.AbstractTransformTask
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.VMClassLoader.findLoadedClass(Native Method)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
INFO [2017-08-02 09:54:17.62]: ▸ ... 9 more
INFO [2017-08-02 09:54:17.62]: ▸ Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/tools/ant/Task;
INFO [2017-08-02 09:54:17.62]: ▸ ... 9 more
INFO [2017-08-02 09:54:17.62]: ▸ Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.tools.ant.Task" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/hidden.package.name.beta.test-2/base.apk", zip file "/data/app/hidden.package.name.beta-1/base.apk"],nativeLibraryDirectories=[/data/app/hidden.package.name.beta.test-2/lib/arm64, /data/app/hidden.package.name.beta-1/lib/arm64, /system/lib64, /vendor/lib64]]
INFO [2017-08-02 09:54:17.62]: ▸ at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
INFO [2017-08-02 09:54:17.62]: ▸ at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
INFO [2017-08-02 09:54:17.62]: ▸ ... 9 more
INFO [2017-08-02 09:54:17.62]: ▸ FAILURES!!!
INFO [2017-08-02 09:54:17.62]: ▸ Tests run: 22,  Failures: 2
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/fastlane_core/lib/fastlane_core/ui/interface.rb:162:in `test_failure!': [!] Tests failed for locale en-US on device 10160abdccc81403 (FastlaneCore::Interface::FastlaneTestFailure)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/screengrab/lib/screengrab/runner.rb:255:in `run_tests_for_locale'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/screengrab/lib/screengrab/runner.rb:234:in `block in run_tests'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/screengrab/lib/screengrab/runner.rb:228:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/screengrab/lib/screengrab/runner.rb:228:in `run_tests'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/screengrab/lib/screengrab/runner.rb:66:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/screengrab/lib/screengrab/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/screengrab/lib/screengrab/commands_generator.rb:58:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/screengrab/lib/screengrab/commands_generator.rb:11:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment
I am not allowed to post the env. Sorry.

**Comment by ohayon** [comment]
Hey everyone! As of now, we have not updated screengrab to support Kotlin yet 😞 . We would love it if some people from the community would like to step in and beat us to the punch here! Would anyone like to submit a PR with Kotlin support? 🙏  🚀
