### ISSUE TITLE
cli_tools_distributor.rb:69:in `ensure in take_off' uninitialized constant FastlaneCore::UpdateChecker (NameError) 

### ISSUE THREAD

**Issue by rubnov** [fastlane/fastlane#9958]
### Issue Description

I've updated fastlane to the latest version (2.50.1) and am now getting the following error when running any fastlane command (e.g. `fastlane info`):

```
/Users/rotem.rubnov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/cli_tools_distributor.rb:69:in `ensure in take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError)
	from /Users/rotem.rubnov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/cli_tools_distributor.rb:69:in `take_off'
	from /Users/rotem.rubnov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.50.1/bin/fastlane:20:in `<top (required)>'
	from /Users/rotem.rubnov/.rvm/rubies/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/rotem.rubnov/.rvm/rubies/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/rotem.rubnov/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rotem.rubnov/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

`fastlane env` produces the exact same error above.

```
$ rvm --version
rvm 1.29.1 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
$ rvm current
ruby-2.4.0
``` 

Running on OS X 10.12.6 (16G29)

Already tried: 

```
sudo gem uninstall fastlane
rm -rf /Users/rotem.rubnov/.rvm/gems/ruby-2.4.0/bin/fastlane
rm -rf ~/.fastlane
rvm reinstall 2.4.0
sudo gem install fastlane
```

**Comment by rubnov** [comment]
This seems to resolve the issue: 
`rvm @global`

**Comment by ohayon** [comment]
Glad you got it working @rubnov !! 🚀
